### ISSUE TITLE
crash when looking for a nonexistent destructor

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10068]
Migrated from [rt.perl.org#71952](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=71952) (status was 'resolved')

Searchable as RT71952$

**Comment by p5pRT** [comment]
### From @ntyni

This is a bug report for perl from Niko Tyni \<ntyni@&#8203;debian\.org>\,
generated with the help of perlbug 1\.39 running under perl 5\.10\.1\.




---
The optimization of empty DESTROY methods introduced in commit
fbb3ee5af3d4 causes a null pointer dereference when a destructor is
declared but not defined\.

% perl \-e 'sub M&#8203;::DESTROY; bless \{\}\, "M"'
zsh&#8203;: segmentation fault \(core dumped\) 

This is seen in the real world with AutoLoader / AutoSplit\, where
the crash prevents autoloading a DESTROY method\.

 http&#8203;://bugs\.debian\.org/564074

Blead backtrace&#8203;:

Core was generated by \`\./miniperl \-e sub M&#8203;::DESTROY; bless \{\}\, "M"'\.
Program terminated with signal 11\, Segmentation fault\.
\#0  0x000000000054f83a in Perl\_sv\_clear \(my\_perl=0x2207010\, sv=0x220ae28\) at sv\.c&#8203;:5661
5661                || CvSTART\(destructor\)\->op\_next\->op\_type \!= OP\_LEAVESUB\)\)
\(gdb\) bt
\#0  0x000000000054f83a in Perl\_sv\_clear \(my\_perl=0x2207010\, sv=0x220ae28\) at sv\.c&#8203;:5661
\#1  0x0000000000551b49 in Perl\_sv\_free2 \(my\_perl=0x2207010\, sv=0x220ae28\) at sv\.c&#8203;:5936
\#2  0x000000000054f6a6 in Perl\_sv\_clear \(my\_perl=0x2207010\, sv=0x220af78\) at sv\.c&#8203;:5638
\#3  0x0000000000551b49 in Perl\_sv\_free2 \(my\_perl=0x2207010\, sv=0x220af78\) at sv\.c&#8203;:5936
\#4  0x00000000005cab0b in Perl\_free\_tmps \(my\_perl=0x2207010\) at scope\.c&#8203;:167
\#5  0x0000000000709457 in perl\_run \(my\_perl=0x2207010\) at perl\.c&#8203;:2234
\#6  0x00000000006d9921 in main \(argc=3\, argv=0x7fff5ac22a48\, env=0x7fff5ac22a68\) at miniperlmain\.c&#8203;:117

Proposed patch attached\.


---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=medium


---
Site configuration information for perl 5\.10\.1&#8203;:

Configured by Debian Project at Sat Nov 21 19&#8203;:18&#8203;:01 UTC 2009\.

Summary of my perl5 \(revision 5 version 10 subversion 1\) configuration&#8203;:
&nbsp;   
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.31\-1\-amd64\, archname=x86\_64\-linux\-gnu\-thread\-multi
&nbsp;    uname='linux madeleine 2\.6\.31\-1\-amd64 \#1 smp mon nov 16 04&#8203;:44&#8203;:38 utc 2009 x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN \-Dcccdlflags=\-fPIC \-Darchname=x86\_64\-linux\-gnu \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.10 \-Darchlib=/usr/lib/perl/5\.10 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.10\.1 \-Dsitearch=/usr/local/lib/perl/5\.10\.1 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1 \-Dsiteman3dir=/usr/local/man/man3 \-Dman1ext=1 \-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Ud\_ualarm \-Uusesfio \-Uusenm \-DDEBUGGING=\-g \-Doptimize=\-O2 \-Duseshrplib \-Dlibperl=libperl\.so\.5\.10\.1 \-Dd\_dosuid \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2 \-g'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.3\.4'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64
&nbsp;    libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    libc=/lib/libc\-2\.10\.1\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.10\.1
&nbsp;    gnulibc\_version='2\.10\.1'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-g \-L/usr/local/lib \-fstack\-protector'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl 5\.10\.1&#8203;:
&nbsp;    /etc/perl
&nbsp;    /usr/local/lib/perl/5\.10\.1
&nbsp;    /usr/local/share/perl/5\.10\.1
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/perl/5\.10
&nbsp;    /usr/share/perl/5\.10
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    \.



---
Environment for perl 5\.10\.1&#8203;:
&nbsp;    HOME=/home/niko
&nbsp;    LANG=en\_US\.UTF\-8
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LC\_CTYPE=fi\_FI\.UTF\-8
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/niko/bin&#8203;:/home/niko/bin&#8203;:/home/niko/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/local/games&#8203;:/usr/games&#8203;:/sbin&#8203;:/usr/sbin&#8203;:/sbin&#8203;:/usr/sbin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/zsh

**Comment by p5pRT** [comment]
### From @ntyni

<details><summary>0001-Fix-a-NULL-pointer-dereference-when-looking-for-a-DE.patch</summary>

```diff
From 16026715863b1a3a6e99df6686834c9238922539 Mon Sep 17 00:00:00 2001
From: Niko Tyni <ntyni@debian.org>
Date: Fri, 8 Jan 2010 21:21:57 +0200
Subject: [PATCH] Fix a NULL pointer dereference when looking for a DESTROY method

The empty DESTROY method optimization introduced by commit
fbb3ee5af3d would crash the interpreter if a DESTROY method
was declared but not actually defined.

This is seen in the real world with AutoLoader / AutoSplit,
where the crash defeats autoloading a DESTROY method.
---
 sv.c          |    3 ++-
 t/op/method.t |   11 ++++++++++-
 2 files changed, 12 insertions(+), 2 deletions(-)

diff --git a/sv.c b/sv.c
index fb82caf..ed4be5f 100644
--- a/sv.c
+++ b/sv.c
@@ -5658,7 +5658,8 @@ Perl_sv_clear(pTHX_ register SV *const sv)
 			&& !CvCONST(destructor)
 			/* Don't bother calling an empty destructor */
 			&& (CvISXSUB(destructor)
-			|| CvSTART(destructor)->op_next->op_type != OP_LEAVESUB))
+			|| (CvSTART(destructor)
+			    && (CvSTART(destructor)->op_next->op_type != OP_LEAVESUB))))
 		{
 		    SV* const tmpref = newRV(sv);
 	            SvREADONLY_on(tmpref);   /* DESTROY() could be naughty */
diff --git a/t/op/method.t b/t/op/method.t
index afa8cfb..d2914c4 100644
--- a/t/op/method.t
+++ b/t/op/method.t
@@ -10,7 +10,7 @@ BEGIN {
     require "test.pl";
 }
 
-print "1..78\n";
+print "1..79\n";
 
 @A::ISA = 'B';
 @B::ISA = 'C';
@@ -292,3 +292,12 @@ EOT
 	"check if UNIVERSAL::AUTOLOAD works",
     );
 }
+{
+    fresh_perl_is(<<'EOT',
+sub M::DESTROY; bless {}, "M" ; print "survived\n";
+EOT
+    "survived",
+    {},
+	"no crash with a declared but missing DESTROY method"
+    );
+}
-- 
1.6.6


```
</details>

**Comment by p5pRT** [comment]
### From @tsee

Thanks\, applied as 1f15e670edb515b744e9021b4a42a7955da83093\!

\-\-Steffen

**Comment by p5pRT** [comment]
@tsee - Status changed from 'new' to 'resolved'
