### ISSUE TITLE
assertion failures when running with -t switch and tainted @INC

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10105]
Migrated from [rt.perl.org#72330](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=72330) (status was 'resolved')

Searchable as RT72330$

**Comment by p5pRT** [comment]
### From @ntyni

This is a bug report for perl from Niko Tyni \<ntyni@&#8203;debian\.org>\,
generated with the help of perlbug 1\.39 running under perl 5\.11\.4\.




---
A suitable combination of tainted @&#8203;INC\, the '\-t' switch and stubs for
undefined constants causes an assertion failure with \-DDEBUGGING and
intermittent segmentation faults otherwise\.

Originally reported as http&#8203;://bugs\.debian\.org/565703\, reproducible
on current bleadperl&#8203;:

% \./perl \-t \-Ilib \-e 'unshift @&#8203;INC\, shift; require Fcntl' foo
Insecure dependency in require while running with \-t switch at \-e line 1\.
Insecure dependency in require while running with \-t switch at \-e line 1\.
Insecure dependency in require while running with \-t switch at lib/Fcntl\.pm line 58\.
Insecure dependency in require while running with \-t switch at lib/Fcntl\.pm line 58\.
Insecure dependency in require while running with \-t switch at lib/Fcntl\.pm line 58\.
Insecure dependency in require while running with \-t switch at lib/Fcntl\.pm line 62\.
Insecure dependency in require while running with \-t switch at lib/Fcntl\.pm line 62\.
Insecure dependency in require while running with \-t switch at lib/Fcntl\.pm line 62\.
perl&#8203;: gv\.c&#8203;:241&#8203;: Perl\_gv\_init&#8203;: Assertion \`\!\(\(gv\)\->sv\_flags & 0x00004000\)' failed\.
zsh&#8203;: abort \(core dumped\)  \./perl \-t \-Ilib \-e 'unshift @&#8203;INC\, shift; require Fcntl' foo

Other variants include

% echo 'XSLoader&#8203;::load\(q\(Fcntl\)\)' > T\.pm && \./perl \-Ilib \-MXSLoader \-I\. \-t \-e 'unshift @&#8203;INC\, shift; require T; \*a = \\&\{"Fcntl&#8203;::S\_IFWHT"\}' foo
Insecure dependency in require while running with \-t switch at \-e line 1\.
\[\.\.\.\]
perl&#8203;: mg\.c&#8203;:219&#8203;: Perl\_mg\_get&#8203;: Assertion \`\!\(\(\(\_svmagic\)\->sv\_flags & \(0x40000000|0x00040000\)\) == \(0x40000000|0x00040000\)\)' failed\.

and 

% echo 'XSLoader&#8203;::load\(q\(POSIX\)\)' > T\.pm && \./perl \-Ilib \-MXSLoader \-I\. \-t \-e 'unshift @&#8203;INC\, shift; require T; \*a = \\&\{"POSIX&#8203;::CLK\_TCK"\}' foo

which fails in the same way\.

The problem seems to be related to the stubs for undefined constants;
the ones used above are not defined on this platform\.

\./perl \-Ilib \-MPOSIX \-E 'say POSIX&#8203;::CLK\_TCK'
Your vendor has not defined POSIX macro CLK\_TCK\, used at \-e line 1
\./perl \-Ilib \-MFcntl \-E 'say Fcntl&#8203;::S\_IFWHT'
Your vendor has not defined Fcntl macro S\_IFWHT\, used at \-e line 1\.


Blead backtrace of the first case&#8203;:

Core was generated by \`\./perl \-t \-Ilib \-e unshift @&#8203;INC\, shift; require Fcntl foo'\.
Program terminated with signal 6\, Aborted\.
\#0  0x00007f86090b5f55 in \*\_\_GI\_raise \(sig=\<value optimized out>\)
&nbsp;    at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:64
64  \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;: No such file or directory\.
&nbsp;    in \.\./nptl/sysdeps/unix/sysv/linux/raise\.c
\(gdb\) bt
\#0  0x00007f86090b5f55 in \*\_\_GI\_raise \(sig=\<value optimized out>\)
&nbsp;    at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:64
\#1  0x00007f86090b8d90 in \*\_\_GI\_abort \(\) at abort\.c&#8203;:88
\#2  0x00007f86090af07a in \*\_\_GI\_\_\_assert\_fail \(assertion=0x74b9d8 "\!\(\(gv\)\->sv\_flags & 0x00004000\)"\, 
&nbsp;    file=\<value optimized out>\, line=241\, function=0x7524df "Perl\_gv\_init"\) at assert\.c&#8203;:78
\#3  0x0000000000464e44 in Perl\_gv\_init \(my\_perl=0xd20010\, gv=0xd7ab10\, stash=0xd42898\, 
&nbsp;    name=0xd88528 "S\_IFWHT"\, len=7\, multi=2\) at gv\.c&#8203;:241
\#4  0x000000000046c902 in Perl\_gv\_fetchpvn\_flags \(my\_perl=0xd20010\, nambeg=0xd88528 "S\_IFWHT"\, 
&nbsp;    full\_len=7\, flags=3\, sv\_type=SVt\_PVCV\) at gv\.c&#8203;:1142
\#5  0x000000000046af9b in Perl\_gv\_fetchsv \(my\_perl=0xd20010\, name=0xd885c0\, flags=3\, sv\_type=SVt\_PVCV\)
&nbsp;    at gv\.c&#8203;:911
\#6  0x000000000043eec0 in Perl\_ck\_rvconst \(my\_perl=0xd20010\, o=0xd89670\) at op\.c&#8203;:6788
\#7  0x000000000042c343 in Perl\_newUNOP \(my\_perl=0xd20010\, type=17\, flags=0\, first=0xd89630\) at op\.c&#8203;:3109
\#8  0x000000000043d7b4 in Perl\_newCVREF \(my\_perl=0xd20010\, flags=0\, o=0xd89630\) at op\.c&#8203;:6393
\#9  0x00000000004991f2 in Perl\_yylex \(my\_perl=0xd20010\) at toke\.c&#8203;:6056
\#10 0x00000000004c0fd9 in Perl\_yyparse \(my\_perl=0xd20010\) at perly\.c&#8203;:414
\#11 0x000000000065280f in S\_doeval \(my\_perl=0xd20010\, gimme=2\, startop=0x0\, outside=0x0\, seq=0\)
&nbsp;    at pp\_ctl\.c&#8203;:3089
\#12 0x0000000000659836 in Perl\_pp\_require \(my\_perl=0xd20010\) at pp\_ctl\.c&#8203;:3657
\#13 0x0000000000518cb7 in Perl\_runops\_debug \(my\_perl=0xd20010\) at dump\.c&#8203;:2049
\#14 0x00000000004548ea in S\_run\_body \(my\_perl=0xd20010\, oldscope=1\) at perl\.c&#8203;:2308
\#15 0x0000000000453bb2 in perl\_run \(my\_perl=0xd20010\) at perl\.c&#8203;:2233
\#16 0x000000000042302d in main \(argc=6\, argv=0x7fffb80bc108\, env=0x7fffb80bc140\) at perlmain\.c&#8203;:117



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=low


---
Site configuration information for perl 5\.11\.4&#8203;:

Configured by niko at Sun Jan 24 20&#8203;:28&#8203;:38 EET 2010\.

Summary of my perl5 \(revision 5 version 11 subversion 4\) configuration&#8203;:
&nbsp;  Commit id&#8203;: fe61459e95657c432074058bd8854fec03559335
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.32\-trunk\-amd64\, archname=x86\_64\-linux\-gnu\-thread\-multi
&nbsp;    uname='linux madeleine 2\.6\.32\-trunk\-amd64 \#1 smp sun jan 10 22&#8203;:40&#8203;:40 utc 2010 x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN \-Dcccdlflags=\-fPIC \-Darchname=x86\_64\-linux\-gnu \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.11 \-Darchlib=/usr/lib/perl/5\.11 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.11\.4 \-Dsitearch=/usr/local/lib/perl/5\.11\.4 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1 \-Dsiteman3dir=/usr/local/man/man3 \-Dman1ext=1 \-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Ud\_ualarm \-Uusesfio \-Uusenm \-DDEBUGGING=both \-Doptimize=\-O0 \-Dusedevel \-Uuseshrplib \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O0 \-g'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.4\.3 20100108 \(prerelease\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64
&nbsp;    libs=\-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc \-lgdbm\_compat
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    libc=/lib/libc\-2\.10\.2\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.10\.2'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O0 \-g \-L/usr/local/lib \-fstack\-protector'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl 5\.11\.4&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/lib/perl/5\.11\.4
&nbsp;    /usr/local/share/perl/5\.11\.4
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/perl/5\.11
&nbsp;    /usr/share/perl/5\.11
&nbsp;    \.



---
Environment for perl 5\.11\.4&#8203;:
&nbsp;    HOME=/home/niko
&nbsp;    LANG=en\_US\.UTF\-8
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LC\_CTYPE=fi\_FI\.UTF\-8
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/niko/bin&#8203;:/home/niko/bin&#8203;:/home/niko/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/local/games&#8203;:/usr/games&#8203;:/sbin&#8203;:/usr/sbin&#8203;:/sbin&#8203;:/usr/sbin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/zsh

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Jan 24\, 2010 at 11&#8203;:02&#8203;:46AM \-0800\, Niko Tyni wrote&#8203;:
> perl&#8203;: gv\.c&#8203;:241&#8203;: Perl\_gv\_init&#8203;: Assertion \`\!\(\(gv\)\->sv\_flags & 0x00004000\)' failed\.

This appears to have been introduced in 5\.10\.0

\-\- 
The Enterprise is captured by a vastly superior alien intelligence which
does not put them on trial\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#10

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Jan 24\, 2010 at 11&#8203;:02&#8203;:46AM \-0800\, Niko Tyni wrote&#8203;:
> Other variants include
> 
> % echo 'XSLoader&#8203;::load\(q\(Fcntl\)\)' > T\.pm && \./perl \-Ilib \-MXSLoader \-I\. \-t \-e 'unshift @&#8203;INC\, shift; require T; \*a = \\&\{"Fcntl&#8203;::S\_IFWHT"\}' foo
> Insecure dependency in require while running with \-t switch at \-e line 1\.
> \[\.\.\.\]
> perl&#8203;: mg\.c&#8203;:219&#8203;: Perl\_mg\_get&#8203;: Assertion \`\!\(\(\(\_svmagic\)\->sv\_flags & \(0x40000000|0x00040000\)\) == \(0x40000000|0x00040000\)\)' failed\.

I can trigger the same assertion failure with the following simplified
code&#8203;:

$ cat /tmp/Foo\.pm
package Foo;
our $foo; sub f \{ $foo \}
1;

$ \./perl \-t \-I/tmp \-e 'unshift @&#8203;INC\, $^X; require Foo'
Insecure dependency in require while running with \-t switch at \-e line 1\.
Insecure dependency in require while running with \-t switch at \-e line 1\.
perl&#8203;: mg\.c&#8203;:219&#8203;: Perl\_mg\_get&#8203;: Assertion \`\!\(\(\(\_svmagic\)\->sv\_flags & \(0x40000000|0x00040000\)\) == \(0x40000000|0x00040000\)\)' failed\.
Aborted

It boils down to&#8203;:
having a tainted @&#8203;INC then doing a require with \-t \(rather than \-T\)
prints the taint warning\, then proceeds to compile the whole of Foo\.pm
with PL\_tainted=1\. This means that everything during the compilation gets
tainted\, in particular\, the name SVs in pads\, so they get taint magic
attached\. This then fails the assertion added by Nicholas&#8203;:

&nbsp;    commit 885ffcb307023fbe2047bd0c0e016f18bebc1fb3
&nbsp;    Author&#8203;:     Nicholas Clark \<nick@&#8203;ccl4\.org>
&nbsp;    AuthorDate&#8203;: Tue May 2 17&#8203;:00&#8203;:56 2006 \+0000
&nbsp;    Commit&#8203;:     Nicholas Clark \<nick@&#8203;ccl4\.org>
&nbsp;    CommitDate&#8203;: Tue May 2 17&#8203;:00&#8203;:56 2006 \+0000

&nbsp;    Assert that SvMAGIC\(\) isn't being called on PVMGs which are using the
&nbsp;    same union to store the stash for our\.

&nbsp;    \.\.\.

&nbsp;    @&#8203;@&#8203; \-1164\,6 \+1164\,8 @&#8203;@&#8203; the scalar's value cannot change unless written to\.
&nbsp;     \#    define SvMAGIC\(sv\)                            \\
&nbsp;        \(\*\(\{ SV \*const \_svi = \(SV \*\) sv;                \\
&nbsp;        assert\(SvTYPE\(\_svi\) >= SVt\_PVMG\);                \\
&nbsp;    \+        if\(SvTYPE\(\_svi\) == SVt\_PVMG\)                \\
&nbsp;    \+        assert\(\!SvPAD\_OUR\(\_svi\)\);                \\


I'm assuming\, Nicholas\, that this assertion is correct\, and thus its the
names SVs getting tainted that is BAD and needs fixing?

In which case\, its a bit unclear to me what to do\. Doing a whole compi;e
tainted is a bit of a strange things to do\. Arguably if a require or
similar tries to compile something tainted under \-t\, we could print the
warning\, then reset PL\_tainting so the compilation is done untainted\.
Which might suppress some further taint warnings\, but would stop the
crashes\.

I would speculate that the other reported assertion failures have a
similar root cause\.

Anyway\, probably not something for 5\.12\, even though its a 5\.10 regression\.

\-\- 
Modern art&#8203;:
&nbsp;    "It's easy\, I could have done that\!"
&nbsp;    "Yes\, but you didn't"

**Comment by p5pRT** [comment]
### From @rgarcia

On 9 February 2010 01&#8203;:17\, Dave Mitchell \<davem@&#8203;iabyn\.com> wrote&#8203;:
> On Sun\, Jan 24\, 2010 at 11&#8203;:02&#8203;:46AM \-0800\, Niko Tyni wrote&#8203;:
>> Other variants include
>>
>> % echo 'XSLoader&#8203;::load\(q\(Fcntl\)\)' > T\.pm && \./perl \-Ilib \-MXSLoader \-I\. \-t \-e 'unshift @&#8203;INC\, shift; require T; \*a = \\&\{"Fcntl&#8203;::S\_IFWHT"\}' foo
>> Insecure dependency in require while running with \-t switch at \-e line 1\.
>> \[\.\.\.\]
>> perl&#8203;: mg\.c&#8203;:219&#8203;: Perl\_mg\_get&#8203;: Assertion \`\!\(\(\(\_svmagic\)\->sv\_flags & \(0x40000000|0x00040000\)\) == \(0x40000000|0x00040000\)\)' failed\.
>
> I can trigger the same assertion failure with the following simplified
> code&#8203;:
>
> $ cat /tmp/Foo\.pm
> package Foo;
> our $foo; sub f \{ $foo \}
> 1;
>
> $ \./perl \-t \-I/tmp \-e 'unshift @&#8203;INC\, $^X; require Foo'
> Insecure dependency in require while running with \-t switch at \-e line 1\.
> Insecure dependency in require while running with \-t switch at \-e line 1\.
> perl&#8203;: mg\.c&#8203;:219&#8203;: Perl\_mg\_get&#8203;: Assertion \`\!\(\(\(\_svmagic\)\->sv\_flags & \(0x40000000|0x00040000\)\) == \(0x40000000|0x00040000\)\)' failed\.
> Aborted
>
> It boils down to&#8203;:
> having a tainted @&#8203;INC then doing a require with \-t \(rather than \-T\)
> prints the taint warning\, then proceeds to compile the whole of Foo\.pm
> with PL\_tainted=1\. This means that everything during the compilation gets
> tainted\, in particular\, the name SVs in pads\, so they get taint magic
> attached\. This then fails the assertion added by Nicholas&#8203;:
>
>    commit 885ffcb307023fbe2047bd0c0e016f18bebc1fb3
>    Author&#8203;:     Nicholas Clark \<nick@&#8203;ccl4\.org>
>    AuthorDate&#8203;: Tue May 2 17&#8203;:00&#8203;:56 2006 \+0000
>    Commit&#8203;:     Nicholas Clark \<nick@&#8203;ccl4\.org>
>    CommitDate&#8203;: Tue May 2 17&#8203;:00&#8203;:56 2006 \+0000
>
>        Assert that SvMAGIC\(\) isn't being called on PVMGs which are using the
>        same union to store the stash for our\.
>
>    \.\.\.
>
>    @&#8203;@&#8203; \-1164\,6 \+1164\,8 @&#8203;@&#8203; the scalar's value cannot change unless written to\.
>     \#    define SvMAGIC\(sv\)                                                    \\
>            \(\*\(\{ SV \*const \_svi = \(SV \*\) sv;                            \\
>                assert\(SvTYPE\(\_svi\) >= SVt\_PVMG\);                               \\
>    \+       if\(SvTYPE\(\_svi\) == SVt\_PVMG\)                                \\
>    \+           assert\(\!SvPAD\_OUR\(\_svi\)\);                               \\
>
>
> I'm assuming\, Nicholas\, that this assertion is correct\, and thus its the
> names SVs getting tainted that is BAD and needs fixing?
>
> In which case\, its a bit unclear to me what to do\. Doing a whole compi;e
> tainted is a bit of a strange things to do\. Arguably if a require or
> similar tries to compile something tainted under \-t\, we could print the
> warning\, then reset PL\_tainting so the compilation is done untainted\.
> Which might suppress some further taint warnings\, but would stop the
> crashes\.

Yes\, that sounds like a reasonable line in the sand to draw\. Code
loaded via a tainted @&#8203;INC could be considered tainted\, but for the
sake of only reporting warnings\, we should choose the practical side\.

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, Feb 09\, 2010 at 12&#8203;:52&#8203;:48PM \+0100\, Rafael Garcia\-Suarez wrote&#8203;:
> On 9 February 2010 01&#8203;:17\, Dave Mitchell \<davem@&#8203;iabyn\.com> wrote&#8203;:
> > On Sun\, Jan 24\, 2010 at 11&#8203;:02&#8203;:46AM \-0800\, Niko Tyni wrote&#8203;:
> >> Other variants include
> >>
> >> % echo 'XSLoader&#8203;::load\(q\(Fcntl\)\)' > T\.pm && \./perl \-Ilib \-MXSLoader \-I\. \-t \-e 'unshift @&#8203;INC\, shift; require T; \*a = \\&\{"Fcntl&#8203;::S\_IFWHT"\}' foo
> >> Insecure dependency in require while running with \-t switch at \-e line 1\.
> >> \[\.\.\.\]
> >> perl&#8203;: mg\.c&#8203;:219&#8203;: Perl\_mg\_get&#8203;: Assertion \`\!\(\(\(\_svmagic\)\->sv\_flags & \(0x40000000|0x00040000\)\) == \(0x40000000|0x00040000\)\)' failed\.

\(note to self\) This might also be related to

&nbsp;    http&#8203;://www\.perlmonks\.org/?node\_id=822374

So I'll need to check that too when I get round to fixing it\.


\-\- 
It's not that I'm afraid to die\, I just don't want to be there when it
happens\.
&nbsp;    \-\- Woody Allen

**Comment by p5pRT** [comment]
### From @nwc10

On Tue\, Feb 09\, 2010 at 12&#8203;:52&#8203;:48PM \+0100\, Rafael Garcia\-Suarez wrote&#8203;:

> > It boils down to&#8203;:
> > having a tainted @&#8203;INC then doing a require with \-t \(rather than \-T\)
> > prints the taint warning\, then proceeds to compile the whole of Foo\.pm
> > with PL\_tainted=1\. This means that everything during the compilation gets
> > tainted\, in particular\, the name SVs in pads\, so they get taint magic
> > attached\. This then fails the assertion added by Nicholas&#8203;:
> >
> >    commit 885ffcb307023fbe2047bd0c0e016f18bebc1fb3
> >    Author&#8203;:     Nicholas Clark \<nick@&#8203;ccl4\.org>
> >    AuthorDate&#8203;: Tue May 2 17&#8203;:00&#8203;:56 2006 \+0000
> >    Commit&#8203;:     Nicholas Clark \<nick@&#8203;ccl4\.org>
> >    CommitDate&#8203;: Tue May 2 17&#8203;:00&#8203;:56 2006 \+0000
> >
> >        Assert that SvMAGIC\(\) isn't being called on PVMGs which are using the
> >        same union to store the stash for our\.
> >
> >    \.\.\.
> >
> >    @&#8203;@&#8203; \-1164\,6 \+1164\,8 @&#8203;@&#8203; the scalar's value cannot change unless written to\.
> >     \#    define SvMAGIC\(sv\)                                                    \\
> >            \(\*\(\{ SV \*const \_svi = \(SV \*\) sv;                            \\
> >                assert\(SvTYPE\(\_svi\) >= SVt\_PVMG\);                               \\
> >    \+       if\(SvTYPE\(\_svi\) == SVt\_PVMG\)                                \\
> >    \+           assert\(\!SvPAD\_OUR\(\_svi\)\);                               \\
> >
> >
> > I'm assuming\, Nicholas\, that this assertion is correct\, and thus its the
> > names SVs getting tainted that is BAD and needs fixing?

Yes\, and yes\.

Otherwise you end up with pointers which half the core code thinks point
to MAGIC structures\, and half the code thinks points to HVx\.

> > In which case\, its a bit unclear to me what to do\. Doing a whole compi;e
> > tainted is a bit of a strange things to do\. Arguably if a require or
> > similar tries to compile something tainted under \-t\, we could print the
> > warning\, then reset PL\_tainting so the compilation is done untainted\.
> > Which might suppress some further taint warnings\, but would stop the
> > crashes\.
> 
> Yes\, that sounds like a reasonable line in the sand to draw\. Code
> loaded via a tainted @&#8203;INC could be considered tainted\, but for the
> sake of only reporting warnings\, we should choose the practical side\.

This seems like the best solution\.

Nicholas Clark

**Comment by p5pRT** [comment]
### From @ntyni

On Sun\, Jan 24\, 2010 at 11&#8203;:02&#8203;:46AM \-0800\, Niko Tyni wrote&#8203;:
> \# New Ticket Created by  Niko Tyni 
> \# Please include the string&#8203;:  \[perl \#72330\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: http&#8203;://rt\.perl\.org/rt3/Ticket/Display\.html?id=72330 >
> 
> A suitable combination of tainted @&#8203;INC\, the '\-t' switch and stubs for
> undefined constants causes an assertion failure with \-DDEBUGGING and
> intermittent segmentation faults otherwise\.
> 
> Originally reported as http&#8203;://bugs\.debian\.org/565703\, reproducible
> on current bleadperl&#8203;:
> 
> % \./perl \-t \-Ilib \-e 'unshift @&#8203;INC\, shift; require Fcntl' foo
> Insecure dependency in require while running with \-t switch at \-e line 1\.
> Insecure dependency in require while running with \-t switch at \-e line 1\.
> Insecure dependency in require while running with \-t switch at lib/Fcntl\.pm line 58\.
> Insecure dependency in require while running with \-t switch at lib/Fcntl\.pm line 58\.
> Insecure dependency in require while running with \-t switch at lib/Fcntl\.pm line 58\.
> Insecure dependency in require while running with \-t switch at lib/Fcntl\.pm line 62\.
> Insecure dependency in require while running with \-t switch at lib/Fcntl\.pm line 62\.
> Insecure dependency in require while running with \-t switch at lib/Fcntl\.pm line 62\.
> perl&#8203;: gv\.c&#8203;:241&#8203;: Perl\_gv\_init&#8203;: Assertion \`\!\(\(gv\)\->sv\_flags & 0x00004000\)' failed\.
> zsh&#8203;: abort \(core dumped\)  \./perl \-t \-Ilib \-e 'unshift @&#8203;INC\, shift; require Fcntl' foo

This crash seems to have been fixed since\. Bisecting gives

commit 0f94cb1fe27e58a59d3391214dab34037ab184db
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Thu Nov 27 22&#8203;:30&#8203;:54 2014 \-0800

&nbsp;    \[perl \#123223\] Make PADNAME a separate type
&nbsp;    
&nbsp;    distinct from SV\.  This should fix the CPAN modules that were failing
&nbsp;    when the PadnameLVALUE flag was added\, because it shared the same
&nbsp;    bit as SVs\_OBJECT and pad names were going through code paths not
&nbsp;    designed to handle pad names\.
&nbsp;    
&nbsp;    Unfortunately\, it will probably break other CPAN modules\, but I think
&nbsp;    this change is for the better\, as it makes both pad names and SVs sim\-
&nbsp;    pler and makes pad names take less memory\.

So this ticket can probably be closed?

Thanks\,
\-\- 
Niko Tyni   ntyni@&#8203;debian\.org

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @iabyn

On Fri\, Apr 29\, 2016 at 09&#8203;:23&#8203;:41AM \+0300\, Niko Tyni wrote&#8203;:
> This crash seems to have been fixed since\. Bisecting gives
> 
> commit 0f94cb1fe27e58a59d3391214dab34037ab184db
> Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
> Date&#8203;:   Thu Nov 27 22&#8203;:30&#8203;:54 2014 \-0800
> 
>     \[perl \#123223\] Make PADNAME a separate type
>     
>     distinct from SV\.  This should fix the CPAN modules that were failing
>     when the PadnameLVALUE flag was added\, because it shared the same
>     bit as SVs\_OBJECT and pad names were going through code paths not
>     designed to handle pad names\.
>     
>     Unfortunately\, it will probably break other CPAN modules\, but I think
>     this change is for the better\, as it makes both pad names and SVs sim\-
>     pler and makes pad names take less memory\.
> 
> So this ticket can probably be closed?

Closed now\, thanks\.

\-\- 
"There's something wrong with our bloody ships today\, Chatfield\."
&nbsp;    \-\- Admiral Beatty at the Battle of Jutland\, 31st May 1916\.
