### ISSUE TITLE
@_ is pre-allocated for every sub

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10119]
Migrated from [rt.perl.org#72416](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=72416) (status was 'resolved')

Searchable as RT72416$

**Comment by p5pRT** [comment]
### From @nwc10

[Body was too large for import. Click here for the attachment in RT](https://rt-archive.perl.org/perl5/Ticket/Attachment/WithHeaders/311544)

**Comment by p5pRT** [comment]
### From @nwc10

Applied as 77bac227771c643a8a6e305b2bac4665a8f772d1\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Applied as 77bac227771c643a8a6e305b2bac4665a8f772d1\.

**Comment by p5pRT** [comment]
@nwc10 - Status changed from 'new' to 'resolved'

**Comment by p5pRT** [comment]
### From @avar

On Sun\, May 30\, 2010 at 10&#8203;:56\, Nicholas Clark via RT
\<perlbug\-comment@&#8203;perl\.org> wrote&#8203;:
> Applied as 77bac227771c643a8a6e305b2bac4665a8f772d1\.

This caused a regression in v5\.13\.1\.\.v5\.13\.2 when running
DBD&#8203;::SQLite's tests\. Its t/13\_create\_collation\.t test now segfaults
using DBI 1\.611 \(for perl 5\.013002 on x86\_64\-linux\)\.
http&#8203;://gist\.github\.com/449891 is the script I used to bisect it\.

\(gdb\) run \-Mblib t/13\_create\_collation\.t
Starting program&#8203;: /tmp/perl/bin/perl5\.13\.1 \-Mblib t/13\_create\_collation\.t
1\.\.25
ok 1 \- can't override builtin perl collation
ok 2 \- can't delete builtin perl collation
ok 3 \- can't override registered collation
ok 4 \- overridden collation
ok 5 \- The object isa DBI&#8203;::db
ok 6 \- collate perl \(Bergere\, Berg��e\, HAT\, HOT\, berger\, berg��e\,
ferme\, f��e\, f��u\, f��e\, h��er\, h��aut\, h��a��e\, h����oclite\, h��re\,
h��e // Bergere\, Berg��e\, HAT\, HOT\, berger\, berg��e\, ferme\, f��e\,
f��u\, f��e\, h��er\, h��aut\, h��a��e\, h����oclite\, h��re\, h��e\)
ok 7 \- collate perllocale \(berg��e\, Berg��e\, berger\, Bergere\, f��e\,
f��e\, ferme\, f��u\, h��a��e\, HAT\, h��aut\, h��e\, h��er\, h����oclite\,
HOT\, h��re // berg��e\, Berg��e\, berger\, Bergere\, f��e\, f��e\, ferme\,
f��u\, h��a��e\, HAT\, h��aut\, h��e\, h��er\, h����oclite\, HOT\, h��re\)

Program received signal SIGSEGV\, Segmentation fault\.
0x00007ffff70257f7 in memcpy \(\) from /lib/libc\.so\.6
\(gdb\) bt full
\#0  0x00007ffff70257f7 in memcpy \(\) from /lib/libc\.so\.6
No symbol table info available\.
\#1  0x0000000000488839 in Perl\_pp\_entersub \(\)
No symbol table info available\.
\#2  0x0000000000433b66 in Perl\_call\_sv \(\)
No symbol table info available\.
\#3  0x00007fffefd2cc55 in sqlite\_db\_collation\_dispatcher \(\) from
/tmp/DBD\-SQLite\-1\.30\_03/blib/arch/auto/DBD/SQLite/SQLite\.so
No symbol table info available\.
\#4  0x00007fffefd312b1 in sqlite\_db\_create\_collation \(\) from
/tmp/DBD\-SQLite\-1\.30\_03/blib/arch/auto/DBD/SQLite/SQLite\.so
\#5  0x00007fffefd2b6e6 in XS\_DBD\_\_SQLite\_\_db\_create\_collation \(\) from
/tmp/DBD\-SQLite\-1\.30\_03/blib/arch/auto/DBD/SQLite/SQLite\.so
No symbol table info available\.
\#6  0x00007ffff03d7de3 in XS\_DBI\_dispatch \(\) from
/tmp/perl/lib/site\_perl/5\.13\.1/x86\_64\-linux/auto/DBI/DBI\.so
No symbol table info available\.
\#7  0x0000000000488a22 in Perl\_pp\_entersub \(\)
No symbol table info available\.
\#8  0x00000000004873a3 in Perl\_runops\_standard \(\)
No symbol table info available\.
\#9  0x0000000000433711 in Perl\_call\_sv \(\)
No symbol table info available\.
\#10 0x00007fffefd2c560 in sqlite\_db\_collation\_needed\_dispatcher \(\)
from /tmp/DBD\-SQLite\-1\.30\_03/blib/arch/auto/DBD/SQLite/SQLite\.so
No symbol table info available\.
\#11 0x00007fffefd5cd5b in sqlite3GetCollSeq \(\) from
/tmp/DBD\-SQLite\-1\.30\_03/blib/arch/auto/DBD/SQLite/SQLite\.so
No symbol table info available\.
\#12 0x00007fffefd5dab1 in sqlite3LocateCollSeq \(\) from
/tmp/DBD\-SQLite\-1\.30\_03/blib/arch/auto/DBD/SQLite/SQLite\.so
No symbol table info available\.
\#13 0x00007fffefd5e910 in sqlite3ExprSetColl \(\) from
/tmp/DBD\-SQLite\-1\.30\_03/blib/arch/auto/DBD/SQLite/SQLite\.so
No symbol table info available\.
\#14 0x00007fffefd78abd in sqlite3Parser \(\) from
/tmp/DBD\-SQLite\-1\.30\_03/blib/arch/auto/DBD/SQLite/SQLite\.so
No symbol table info available\.
\#15 0x00007fffefd7988f in sqlite3RunParser \(\) from
/tmp/DBD\-SQLite\-1\.30\_03/blib/arch/auto/DBD/SQLite/SQLite\.so
No symbol table info available\.
\#16 0x00007fffefd7b9c4 in sqlite3Prepare \(\) from
/tmp/DBD\-SQLite\-1\.30\_03/blib/arch/auto/DBD/SQLite/SQLite\.so
No symbol table info available\.
\#17 0x00007fffefd7bc5a in sqlite3LockAndPrepare \(\) from
/tmp/DBD\-SQLite\-1\.30\_03/blib/arch/auto/DBD/SQLite/SQLite\.so
No symbol table info available\.
\-\-\-Type \<return> to continue\, or q \<return> to quit\-\-\-
\#18 0x00007fffefd7be98 in sqlite3\_prepare\_v2 \(\) from
/tmp/DBD\-SQLite\-1\.30\_03/blib/arch/auto/DBD/SQLite/SQLite\.so
No symbol table info available\.
\#19 0x00007fffefd300b8 in sqlite\_st\_prepare \(\) from
/tmp/DBD\-SQLite\-1\.30\_03/blib/arch/auto/DBD/SQLite/SQLite\.so
No symbol table info available\.
\#20 0x00007fffefd27375 in XS\_DBD\_\_SQLite\_\_st\_\_prepare \(\) from
/tmp/DBD\-SQLite\-1\.30\_03/blib/arch/auto/DBD/SQLite/SQLite\.so
No symbol table info available\.
\#21 0x0000000000488a22 in Perl\_pp\_entersub \(\)
No symbol table info available\.
\#22 0x00000000004873a3 in Perl\_runops\_standard \(\)
No symbol table info available\.
\#23 0x0000000000433711 in Perl\_call\_sv \(\)
No symbol table info available\.
\#24 0x00007ffff03d5fcd in XS\_DBI\_dispatch \(\) from
/tmp/perl/lib/site\_perl/5\.13\.1/x86\_64\-linux/auto/DBI/DBI\.so
No symbol table info available\.
\#25 0x0000000000488a22 in Perl\_pp\_entersub \(\)
No symbol table info available\.
\#26 0x00000000004873a3 in Perl\_runops\_standard \(\)
No symbol table info available\.
\#27 0x0000000000433711 in Perl\_call\_sv \(\)
No symbol table info available\.
\#28 0x00007ffff03d5fcd in XS\_DBI\_dispatch \(\) from
/tmp/perl/lib/site\_perl/5\.13\.1/x86\_64\-linux/auto/DBI/DBI\.so
No symbol table info available\.
\#29 0x0000000000488a22 in Perl\_pp\_entersub \(\)
No symbol table info available\.
\#30 0x00000000004873a3 in Perl\_runops\_standard \(\)
No symbol table info available\.
\#31 0x00000000004341b1 in perl\_run \(\)
No symbol table info available\.
\#32 0x000000000042072c in main \(\)
No symbol table info available\.

**Comment by p5pRT** [comment]
### From @nwc10

On Wed\, Jun 23\, 2010 at 01&#8203;:20&#8203;:11PM \+0000\, Ævar Arnfjörð Bjarmason wrote&#8203;:
> On Sun\, May 30\, 2010 at 10&#8203;:56\, Nicholas Clark via RT
> \<perlbug\-comment@&#8203;perl\.org> wrote&#8203;:
> > Applied as 77bac227771c643a8a6e305b2bac4665a8f772d1\.
> 
> This caused a regression in v5\.13\.1\.\.v5\.13\.2 when running
> DBD&#8203;::SQLite's tests\. Its t/13\_create\_collation\.t test now segfaults
> using DBI 1\.611 \(for perl 5\.013002 on x86\_64\-linux\)\.
> http&#8203;://gist\.github\.com/449891 is the script I used to bisect it\.

Aha\. That seems to be bug 72334\.
I've applied Gerrard's patch as 8f443ca6a3a77930ce80210fd1c0e9ee627daa9e
and that seems to fix this\.

Nicholas Clark
