### ISSUE TITLE
BBC assertion in autovivification.pm

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10207]
Migrated from [rt.perl.org#73242](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=73242) (status was 'rejected')

Searchable as RT73242$

**Comment by p5pRT** [comment]
### From @schwern

#### Created by @schwern



Attempting to eval a dumped closure which makes use of autovivification\.pm
results in an assertion failure in 5\.11\.5 which does not happen in 5\.10\.1\.
I don't know if autoviv or Perl is doing something naughty\, but something
changed in Perl\.

Here is the assertion\.

Assertion failed&#8203;: \(SvTYPE\(\_svuvx\) == SVt\_IV || SvTYPE\(\_svuvx\) >= SVt\_PVIV\)\, 
function a\_hint\, file autovivification\.xs\, line 133\.

Stack trace follows\.

\#0  0x92a30732 in kill$UNIX2003 \(\)
\#1  0x92ac398d in raise \(\)
\#2  0x92ad9a44 in abort \(\)
\#3  0x92ac65ec in \_\_assert\_rtn \(\)
\#4  0x00439ace in a\_hint \(my\_perl=0x800000\) at autovivification\.xs&#8203;:133
\#5  0x0043bd31 in a\_ck\_deref \(my\_perl=0x800000\, o=0x573060\) at 
autovivification\.xs&#8203;:642
\#6  0x0000c89a in Perl\_newUNOP \(my\_perl=0x800000\, type=15\, flags=0\, 
first=0x5c9570\) at op\.c&#8203;:3109
\#7  0x0001f680 in Perl\_newSVREF \(my\_perl=0x800000\, o=0x5c9570\) at op\.c&#8203;:6408
\#8  0x000ba5e8 in Perl\_yyparse \(my\_perl=0x800000\) at perly\.y&#8203;:1330
\#9  0x0027dcd0 in S\_doeval \(my\_perl=0x800000\, gimme=3\, startop=0x0\, 
outside=0x803b10\, seq=159\) at pp\_ctl\.c&#8203;:3089
\#10 0x0028778b in Perl\_pp\_entereval \(my\_perl=0x800000\) at pp\_ctl\.c&#8203;:3763
\#11 0x001118e1 in Perl\_runops\_debug \(my\_perl=0x800000\) at dump\.c&#8203;:2049
\#12 0x000382cd in S\_run\_body \(my\_perl=0x800000\, oldscope=1\) at perl\.c&#8203;:2308
\#13 0x00037366 in perl\_run \(my\_perl=0x800000\) at perl\.c&#8203;:2233
\#14 0x0000236d in main \(argc=2\, argv=0xbffff4d0\, env=0xbffff4dc\) at perlmain\.c&#8203;:117

The demonstration code follows\.

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
\#\!/usr/bin/perl

use autovivification;

\{
&nbsp;     my $foo = 42;

&nbsp;     sub closure \{
&nbsp;         return $foo;
&nbsp;     \}
\}

my @&#8203;options = qw/Indent Terse Useqq Sortkeys Deparse/;
sub as\_perl \{
&nbsp;     require Data&#8203;::Dumper;

&nbsp;     my $self    = shift;
&nbsp;     my $dumper = Data&#8203;::Dumper\->new\(\[$self\]\);

&nbsp;     for my $option \(@&#8203;options\) \{
&nbsp;         my \($opt\, @&#8203;opt\_args\) = ref $option ? @&#8203;$option : \($option\, 1\);

&nbsp;         $dumper\->$opt\(@&#8203;opt\_args\) if $dumper\->can\($opt\);
&nbsp;     \}

&nbsp;     return $dumper\->Dump;
\}


my $closure = \\&closure;
print eval\( as\_perl\($closure\) \);
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

<details><summary>Perl Info</summary>

```

Flags:
     category=core
     severity=medium

Site configuration information for perl 5.11.5:

Configured by schwern at Fri Feb 26 19:24:36 PST 2010.

Summary of my perl5 (revision 5 version 11 subversion 5) configuration:
   Commit id: b3289bd223cc434b2247c06d40ffe8d467f241de
   Platform:
     osname=darwin, osvers=10.2.0, archname=darwin-thread-multi-2level
     uname='darwin windhund 10.2.0 darwin kernel version 10.2.0: tue nov 3 
10:37:10 pst 2009; root:xnu-1486.2.11~1release_i386 i386 i386 macbook1,1 darwin '
     config_args='-Ode -DEBUGGING=both -Doptimize=-g 
-Dprefix=/usr/local/perl/5.11.5 -Dusedevel -Duseithreads 
-Dperladmin=schwern@pobox.com -Dcf_email=schwern@pobox.com 
-Dmyhostname=windhund -Dmydomain=.schwern.org -Uversiononly -Uinstallusrbinperl'
     hint=recommended, useposix=true, d_sigaction=define
     useithreads=define, usemultiplicity=define
     useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
     use64bitint=undef, use64bitall=undef, uselongdouble=undef
     usemymalloc=n, bincompat5005=undef
   Compiler:
     cc='cc', ccflags ='-fno-common -DPERL_DARWIN -no-cpp-precomp -DDEBUGGING 
-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include 
-I/opt/local/include',
     optimize='-g',
     cppflags='-no-cpp-precomp -fno-common -DPERL_DARWIN -no-cpp-precomp 
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include 
-I/opt/local/include'
     ccversion='', gccversion='4.2.1 (Apple Inc. build 5646) (dot 1)', 
gccosandvers=''
     intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
     d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
     ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', 
lseeksize=8
     alignbytes=8, prototype=define
   Linker and Libraries:
     ld='env MACOSX_DEPLOYMENT_TARGET=10.3 cc', ldflags =' -fstack-protector 
-L/usr/local/lib -L/opt/local/lib'
     libpth=/usr/local/lib /opt/local/lib /usr/lib
     libs=-lgdbm -ldbm -ldl -lm -lutil -lc
     perllibs=-ldl -lm -lutil -lc
     libc=/usr/lib/libc.dylib, so=dylib, useshrplib=false, libperl=libperl.a
     gnulibc_version=''
   Dynamic Linking:
     dlsrc=dl_dlopen.xs, dlext=bundle, d_dlsymun=undef, ccdlflags=' '
     cccdlflags=' ', lddlflags=' -bundle -undefined dynamic_lookup 
-L/usr/local/lib -L/opt/local/lib -fstack-protector'

Locally applied patches:



@INC for perl 5.11.5:
     /usr/local/perl/5.11.5/lib/site_perl/5.11.5/darwin-thread-multi-2level
     /usr/local/perl/5.11.5/lib/site_perl/5.11.5
     /usr/local/perl/5.11.5/lib/5.11.5/darwin-thread-multi-2level
     /usr/local/perl/5.11.5/lib/5.11.5
     .


Environment for perl 5.11.5:
     DYLD_LIBRARY_PATH (unset)
     HOME=/Users/schwern
     LANG=en_US.UTF-8
     LANGUAGE (unset)
     LC_CTYPE=en_US.UTF-8
     LD_LIBRARY_PATH (unset)
     LOGDIR (unset)
 
PATH=/Users/schwern/bin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/Users/schwern/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin
     PERL_AUTOINSTALL=--defaultdeps
     PERL_BADLANG (unset)
     SHELL=/bin/bash


```
</details>

**Comment by p5pRT** [comment]
### From @rgarcia

On 2 March 2010 21&#8203;:05\, Michael G Schwern \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> Attempting to eval a dumped closure which makes use of autovivification\.pm
> results in an assertion failure in 5\.11\.5 which does not happen in 5\.10\.1\.
> I don't know if autoviv or Perl is doing something naughty\, but something
> changed in Perl\.
>
> Here is the assertion\.
>
> Assertion failed&#8203;: \(SvTYPE\(\_svuvx\) == SVt\_IV || SvTYPE\(\_svuvx\) >= SVt\_PVIV\)\,
> function a\_hint\, file autovivification\.xs\, line 133\.
>
> Stack trace follows\.
>
> \#0  0x92a30732 in kill$UNIX2003 \(\)
> \#1  0x92ac398d in raise \(\)
> \#2  0x92ad9a44 in abort \(\)
> \#3  0x92ac65ec in \_\_assert\_rtn \(\)
> \#4  0x00439ace in a\_hint \(my\_perl=0x800000\) at autovivification\.xs&#8203;:133
> \#5  0x0043bd31 in a\_ck\_deref \(my\_perl=0x800000\, o=0x573060\) at
> autovivification\.xs&#8203;:642

This fails in one of the replacements for the ck\_\* functions set up by
autovivification\.pm\. So I'd blame the module :\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From perl@profvince.com


> On 2 March 2010 21&#8203;:05\, Michael G Schwern \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
>   
>> Attempting to eval a dumped closure which makes use of autovivification\.pm
>> results in an assertion failure in 5\.11\.5 which does not happen in 5\.10\.1\.
>> I don't know if autoviv or Perl is doing something naughty\, but something
>> changed in Perl\.
>>
>> Here is the assertion\.
>>
>> Assertion failed&#8203;: \(SvTYPE\(\_svuvx\) == SVt\_IV || SvTYPE\(\_svuvx\) >= SVt\_PVIV\)\,
>> function a\_hint\, file autovivification\.xs\, line 133\.
>>
>> Stack trace follows\.
>>
>> \#0  0x92a30732 in kill$UNIX2003 \(\)
>> \#1  0x92ac398d in raise \(\)
>> \#2  0x92ad9a44 in abort \(\)
>> \#3  0x92ac65ec in \_\_assert\_rtn \(\)
>> \#4  0x00439ace in a\_hint \(my\_perl=0x800000\) at autovivification\.xs&#8203;:133
>> \#5  0x0043bd31 in a\_ck\_deref \(my\_perl=0x800000\, o=0x573060\) at
>> autovivification\.xs&#8203;:642
>>     
> This fails in one of the replacements for the ck\_\* functions set up by
> autovivification\.pm\. So I'd blame the module :\)
>   

No\, it has nothing to do with check functions\. This fails in a\_hint\(\)\,
specifically when calling this macro :

\#define a\_detag\(H\) \(\(\(H\) && SvOK\(H\)\) ? SvUVX\(H\) : 0\)

SvUVX is called on a value fetched from %^H that only this module could
have created\, and that was created as this IV :

SV = IV\(0xa3c200\) at 0xa3c208
&nbsp;  REFCNT = 1
&nbsp;  FLAGS = \(IOK\,pIOK\)
&nbsp;  IV = 0

But when it segfaults\, the value fetched is :

SV = PV\(0xb8d8d0\) at 0xb76578
&nbsp;  REFCNT = 1
&nbsp;  FLAGS = \(TEMP\,POK\,READONLY\,pPOK\)
&nbsp;  PV = 0xcfb5ed "0"
&nbsp;  CUR = 1
&nbsp;  LEN = 0

The obvious fix is to use SvUV instead of SvUVX\, but I'd still like to
know why the hint value became a PV\.

Also\, it also happens since perl 5\.11\.1\.

Vincent\.

**Comment by p5pRT** [comment]
### From perl@profvince.com


> Also\, it also happens since perl 5\.11\.1\.
>   

Actually\, even in the official release of 5\.11\.0\.

**Comment by p5pRT** [comment]
### From perl@profvince.com


> No\, it has nothing to do with check functions\. This fails in a\_hint\(\)\,
> specifically when calling this macro :
>
> \#define a\_detag\(H\) \(\(\(H\) && SvOK\(H\)\) ? SvUVX\(H\) : 0\)
>
> SvUVX is called on a value fetched from %^H that only this module could
> have created\, and that was created as this IV :
>   
In fact\, the value is directly fetched from the hints chain\. If it's
fetched it from %^H instead\, the test case no longer segfaults\.

I'm not really sure of what happens here\.

Vincent\.

**Comment by p5pRT** [comment]
### From bitcard@profvince.com

When the code compiled with autovivification in use get passed through
B&#8203;::Deparse\, the "use autovivification" line is replaced by

&nbsp;    $^H\{autovivification\} = q\(0\);

which sets the hint to a pure string\. It's then fetched back from the
hints chain as a PV\, causing the error\.

I've fixed the issue in autovivification\.

**Comment by p5pRT** [comment]
bitcard@profvince.com - Status changed from 'open' to 'rejected'
