### ISSUE TITLE
B::PADOP->gv should not allow fetching values from a pad that's not the op's

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10277]
Migrated from [rt.perl.org#74040](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=74040) (status was 'resolved')

Searchable as RT74040$

**Comment by p5pRT** [comment]
### From @rafl

#### Created by rafl@perldition.org



Commit f7461760 broke Devel\-Caller\, at least on some perls\.

The tests segfault while calling B&#8203;::PADOP\->gv\, which is trying to
dereference a NULL SV from the current pad\.

The code in question is this define in B\.xs&#8203;:

 \#define PADOP\_gv\(o\)    \(\(o\->op\_padix \\
&nbsp;                          && SvTYPE\(PAD\_SVl\(o\->op\_padix\)\) == SVt\_PVGV\) \\
&nbsp;                         ? \(GV\*\)PAD\_SVl\(o\->op\_padix\) : \(GV \*\)NULL\)


PAD\_SVl returns NULL\, causing a segfault in SvTYPE\. I suspect the GV
downgrading introduced in f7461760 is causing NULL GVs to show in the
pad\, where there previously weren't any\.

Unfortunately I'm unable to to come up with a test case that involves
only B itself\. However\, the attached patch fixes the issue by checking
PAD\_SVl\(o\->op\_padix\) before calling SvTYPE&#8203;:

<details><summary>Perl Info</summary>

```

Flags:
    category=library
    severity=high
    module=B

Site configuration information for perl 5.12.0:

Configured by rafl at Sun Apr  4 00:53:53 CEST 2010.

Summary of my perl5 (revision 5 version 12 subversion 0) configuration:
   
  Platform:
    osname=linux, osvers=2.6.32.3, archname=x86_64-linux-thread-multi
    uname='linux seekuh 2.6.32.3 #2 smp mon jan 18 12:48:27 cet 2010 x86_64 gnulinux '
    config_args='-Dusedevel -DEBUGGING -Doptimize=-O0 -ggdb3 -Accflags=-Wall -Wextra -des -Dusethreads -Dusemultiplicity -Dprefix=/tmp/rc3-inst'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -Wall -Wextra -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O0 -ggdb3',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -Wall -Wextra -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.4.3', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64
    libs=-lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lpthread -lc -lgdbm_compat
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
    libc=/lib/libc-2.10.2.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.10.2'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -O0 -ggdb3 -L/usr/local/lib -fstack-protector'

Locally applied patches:
    RC3


@INC for perl 5.12.0:
    /tmp/rc3-inst/lib/perl5/site_perl/5.12.0/x86_64-linux-thread-multi
    /tmp/rc3-inst/lib/perl5/site_perl/5.12.0
    /tmp/rc3-inst/lib/perl5/5.12.0/x86_64-linux-thread-multi
    /tmp/rc3-inst/lib/perl5/5.12.0
    .


Environment for perl 5.12.0:
    HOME=/home/rafl
    LANG=C
    LANGUAGE (unset)
    LC_CTYPE=de_DE.UTF-8
    LD_LIBRARY_PATH=/home/rafl/.local/lib:
    LOGDIR (unset)
    PATH=/home/rafl/.perl/bin:/home/rafl/.local/bin:/home/rafl/.perl/bin:/home/rafl/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/games
    PERL_BADLANG (unset)
    SHELL=zsh

```
</details>

**Comment by p5pRT** [comment]
### From @rafl

<details><summary>0001-Make-sure-PADOP_gv-checks-that-the-pad-actually-cont.patch</summary>

```diff
From 8a5fca807c0394d03ed7cb9268cc4a5564996868 Mon Sep 17 00:00:00 2001
From: Florian Ragwitz <rafl@debian.org>
Date: Sun, 4 Apr 2010 04:36:11 +0200
Subject: [PATCH] Make sure PADOP_gv checks that the pad actually contains a scalar before dereferencing it as such.

Since commit f7461760 the pads might contain NULL SVs for GVs that have been
downgraded.
---
 ext/B/B.xs |    1 +
 1 files changed, 1 insertions(+), 0 deletions(-)

diff --git a/ext/B/B.xs b/ext/B/B.xs
index 2b6fb8d..3586e76 100644
--- a/ext/B/B.xs
+++ b/ext/B/B.xs
@@ -1135,6 +1135,7 @@ SVOP_gv(o)
 #define PADOP_padix(o)	o->op_padix
 #define PADOP_sv(o)	(o->op_padix ? PAD_SVl(o->op_padix) : Nullsv)
 #define PADOP_gv(o)	((o->op_padix \
+			  && PAD_SVl(o->op_padix) \
 			  && SvTYPE(PAD_SVl(o->op_padix)) == SVt_PVGV) \
 			 ? (GV*)PAD_SVl(o->op_padix) : (GV *)NULL)
 
-- 
1.7.0.3


```
</details>

**Comment by p5pRT** [comment]
### From @avar

On Sun\, Apr 4\, 2010 at 03&#8203;:01\, Florian Ragwitz \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> \# New Ticket Created by  Florian Ragwitz
> \# Please include the string&#8203;:  \[perl \#74040\]
> \# in the subject line of all future correspondence about this issue\.
> \# \<URL&#8203;: http&#8203;://rt\.perl\.org/rt3/Ticket/Display\.html?id=74040 >
>
>
>
> This is a bug report for perl from rafl@&#8203;perldition\.org\,
> generated with the help of perlbug 1\.39 running under perl 5\.12\.0\.
>
>
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
>
> Commit f7461760 broke Devel\-Caller\, at least on some perls\.
>
> The tests segfault while calling B&#8203;::PADOP\->gv\, which is trying to
> dereference a NULL SV from the current pad\.
>
> The code in question is this define in B\.xs&#8203;:
>
>  \#define PADOP\_gv\(o\)    \(\(o\->op\_padix \\
>                          && SvTYPE\(PAD\_SVl\(o\->op\_padix\)\) == SVt\_PVGV\) \\
>                         ? \(GV\*\)PAD\_SVl\(o\->op\_padix\) : \(GV \*\)NULL\)
>
>
> PAD\_SVl returns NULL\, causing a segfault in SvTYPE\. I suspect the GV
> downgrading introduced in f7461760 is causing NULL GVs to show in the
> pad\, where there previously weren't any\.
>
> Unfortunately I'm unable to to come up with a test case that involves
> only B itself\. However\, the attached patch fixes the issue by checking
> PAD\_SVl\(o\->op\_padix\) before calling SvTYPE&#8203;:

I've tested this both on the current blead and blead \+ rafl's patch\.
Here's blead on Devel&#8203;::Caller's test suite&#8203;:

&nbsp;    ok 62 \- package called\_assign\(@&#8203;T&#8203;::flange\)
&nbsp;    ok 63 \- package called\_assign\(%T&#8203;::bar\)
&nbsp;    ok 64 \- package called\_assign\(%T&#8203;::baz\)
&nbsp;    ok 65 \- package called\_assign\(%T&#8203;::quux\, %T&#8203;::bar\)

&nbsp;    Program received signal SIGSEGV\, Segmentation fault\.
&nbsp;    0x00007ffff10b082f in XS\_B\_\_PADOP\_gv \(my\_perl=0xa0b010\, cv=\<value
optimized out>\) at B\.c&#8203;:2657
&nbsp;    2657            RETVAL = PADOP\_gv\(o\);
&nbsp;    \(gdb\) bt
&nbsp;    \#0  0x00007ffff10b082f in XS\_B\_\_PADOP\_gv \(my\_perl=0xa0b010\,
cv=\<value optimized out>\) at B\.c&#8203;:2657
&nbsp;    \#1  0x000000000057cfa6 in Perl\_pp\_entersub \(my\_perl=0xa0b010\) at
pp\_hot\.c&#8203;:2882
&nbsp;    \#2  0x0000000000519e0b in Perl\_runops\_debug \(my\_perl=0xa0b010\) at
dump\.c&#8203;:2049
&nbsp;    \#3  0x0000000000454908 in S\_run\_body \(my\_perl=0xa0b010\,
oldscope=1\) at perl\.c&#8203;:2303
&nbsp;    \#4  0x0000000000453c56 in perl\_run \(my\_perl=0xa0b010\) at perl\.c&#8203;:2233
&nbsp;    \#5  0x00000000004230ad in main \(argc=3\, argv=0x7fffffffe0e8\,
env=0x7fffffffe108\) at perlmain\.c&#8203;:117

But with rafl's patch all tests are OK&#8203;:

&nbsp;    ok 65 \- package called\_assign\(%T&#8203;::quux\, %T&#8203;::bar\)
&nbsp;    ok 66 \- package called\_assign\(%T&#8203;::flange\)
&nbsp;    ok 67 \- called\_as\_method
&nbsp;    ok 68 \- called\_as\_method
&nbsp;    ok 69 \- called\_as\_method
&nbsp;    ok 70
&nbsp;    \# cunning coy tests
&nbsp;    ok 71 \- real\( $coy\, $coy \)
&nbsp;    \# concat
&nbsp;    ok 72 \- real\( $coy\, $coy \)
&nbsp;    \# print 1

Devel&#8203;::Caller is depended on by a lot of CPAN\[1\]\, in particular
MX&#8203;::Params&#8203;::Validate is used by a lot of Moose modules\.

I'd say this warrants a RC4\.

1\. http&#8203;://deps\.cpantesters\.org/depended\-on\-by\.pl?dist=Devel\-Caller\-2\.04
2\. http&#8203;://deps\.cpantesters\.org/depended\-on\-by\.pl?dist=MooseX\-Params\-Validate\-0\.14

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @nwc10

On Sat\, Apr 03\, 2010 at 08&#8203;:01&#8203;:25PM \-0700\, Florian Ragwitz wrote&#8203;:

> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
> 
> Commit f7461760 broke Devel\-Caller\, at least on some perls\.
> 
> The tests segfault while calling B&#8203;::PADOP\->gv\, which is trying to
> dereference a NULL SV from the current pad\.
> 
> The code in question is this define in B\.xs&#8203;:
> 
>  \#define PADOP\_gv\(o\)    \(\(o\->op\_padix \\
>                           && SvTYPE\(PAD\_SVl\(o\->op\_padix\)\) == SVt\_PVGV\) \\
>                          ? \(GV\*\)PAD\_SVl\(o\->op\_padix\) : \(GV \*\)NULL\)
> 
> 
> PAD\_SVl returns NULL\, causing a segfault in SvTYPE\. I suspect the GV
> downgrading introduced in f7461760 is causing NULL GVs to show in the
> pad\, where there previously weren't any\.

Vincent is right \- this smells bad\.

0x00002ac24582620a in XS\_B\_\_PADOP\_gv \(my\_perl=0xa0b010\, cv=0xca25e8\)
&nbsp;    at B\.c&#8203;:2657
2657            RETVAL = PADOP\_gv\(o\);
\(gdb\) p o\->op\_padix
$1 = 258
\(gdb\) p my\_perl\->Icurpad
$2 = \(SV \*\*\) 0xd5cbd8
\(gdb\) p my\_perl\->Icurpad\[258\]
$3 = \(SV \*\) 0x0

Right\. So the value at that offset \*is\* NULL\.

\(gdb\) p my\_perl\->Icomppad
$4 = \(AV \*\) 0xd1e458
\(gdb\) p my\_perl\->Icomppad\->sv\_u\.svu\_array
$5 = \(SV \*\*\) 0xd5cbd8
\(gdb\) call Perl\_sv\_dump\(my\_perl\, my\_perl\->Icomppad\)
SV = PVAV\(0xcdafa8\) at 0xd1e458
&nbsp;  REFCNT = 1
&nbsp;  FLAGS = \(\)
&nbsp;  ARRAY = 0xd5cbd8
&nbsp;  FILL = 217
&nbsp;  MAX = 253
&nbsp;  ARYLEN = 0x0
&nbsp;  FLAGS = \(REAL\)


But that array only has 218 elements\, offsets 0 to 217\. So 258 is way out of
bounds\. How did \*that\* happen?

Here's what the neighbouring non\-NULL entries \(that far out of range\) look
like&#8203;:

\(gdb\) call Perl\_sv\_dump\(my\_perl\, my\_perl\->Icurpad\[257\]\)
SV = UNKNOWN\(0x48\) \(0x50ec8348e5894855\) at 0x55ba1c
&nbsp;  REFCNT = 3363670344
&nbsp;  FLAGS = \(PADSTALE\,PADMY\,SMG\,IOK\,NOK\,ROK\,WEAKREF\,READONLY\,PCS\_IMPORTED\,EVALED\)
\(gdb\) call Perl\_sv\_dump\(my\_perl\, my\_perl\->Icurpad\[259\]\)

Program received signal SIGSEGV\, Segmentation fault\.
0x0000000000516fa4 in Perl\_sv\_dump \(my\_perl=0xa0b010\, sv=0x10502a4\)
&nbsp;    at dump\.c&#8203;:2012
2012        if \(SvROK\(sv\)\)
The program being debugged was signaled while in a function called from GDB\.
GDB remains in the frame where the signal was received\.
To change this behavior use "set unwindonsignal on"
Evaluation of the expression containing the function \(Perl\_sv\_dump\) will be abandoned\.


Ooopsy\.

I think\, therefore\, that the patch \(unfortunately\) is papering over symptoms\,
rather than addressing the real underlying cause\. Unfortunately\, I don't know
what the underlying cause is\, and don't have time right now to work it out\.
\(Only hunch \- what type is the op? Is it the correct type for PADOP\_gv to be
valid on it?\)

Nicholas Clark

**Comment by p5pRT** [comment]
### From @nwc10

On Sun\, Apr 04\, 2010 at 10&#8203;:15&#8203;:24PM \+0100\, Nicholas Clark wrote&#8203;:
> On Sat\, Apr 03\, 2010 at 08&#8203;:01&#8203;:25PM \-0700\, Florian Ragwitz wrote&#8203;:
> 
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > \[Please describe your issue here\]
> > 
> > Commit f7461760 broke Devel\-Caller\, at least on some perls\.
> > 
> > The tests segfault while calling B&#8203;::PADOP\->gv\, which is trying to
> > dereference a NULL SV from the current pad\.
> > 
> > The code in question is this define in B\.xs&#8203;:
> > 
> >  \#define PADOP\_gv\(o\)    \(\(o\->op\_padix \\
> >                           && SvTYPE\(PAD\_SVl\(o\->op\_padix\)\) == SVt\_PVGV\) \\
> >                          ? \(GV\*\)PAD\_SVl\(o\->op\_padix\) : \(GV \*\)NULL\)
> > 
> > 
> > PAD\_SVl returns NULL\, causing a segfault in SvTYPE\. I suspect the GV
> > downgrading introduced in f7461760 is causing NULL GVs to show in the
> > pad\, where there previously weren't any\.
> 
> Vincent is right \- this smells bad\.
> 
> 0x00002ac24582620a in XS\_B\_\_PADOP\_gv \(my\_perl=0xa0b010\, cv=0xca25e8\)
>     at B\.c&#8203;:2657
> 2657            RETVAL = PADOP\_gv\(o\);
> \(gdb\) p o\->op\_padix
> $1 = 258
> \(gdb\) p my\_perl\->Icurpad
> $2 = \(SV \*\*\) 0xd5cbd8
> \(gdb\) p my\_perl\->Icurpad\[258\]
> $3 = \(SV \*\) 0x0
> 
> Right\. So the value at that offset \*is\* NULL\.
> 
> \(gdb\) p my\_perl\->Icomppad
> $4 = \(AV \*\) 0xd1e458
> \(gdb\) p my\_perl\->Icomppad\->sv\_u\.svu\_array
> $5 = \(SV \*\*\) 0xd5cbd8
> \(gdb\) call Perl\_sv\_dump\(my\_perl\, my\_perl\->Icomppad\)
> SV = PVAV\(0xcdafa8\) at 0xd1e458
>   REFCNT = 1
>   FLAGS = \(\)
>   ARRAY = 0xd5cbd8
>   FILL = 217
>   MAX = 253
>   ARYLEN = 0x0
>   FLAGS = \(REAL\)
> 
> 
> But that array only has 218 elements\, offsets 0 to 217\. So 258 is way out of
> bounds\. How did \*that\* happen?

This is a different run&#8203;:

\(gdb\) call Perl\_get\_cv\(my\_perl\, "Devel&#8203;::Caller&#8203;::called\_with"\, 0\)
$9 = \(CV \*\) 0xd1e4a0
\(gdb\) call Perl\_sv\_dump\(my\_perl\, $9\)
SV = PVCV\(0xd115c0\) at 0xd1e4a0
&nbsp;  REFCNT = 6
&nbsp;  FLAGS = \(\)
&nbsp;  COMP\_STASH = 0xa63d60 "Devel&#8203;::Caller"
&nbsp;  START = 0xd2c830 ===> 0
&nbsp;  ROOT = 0xd5f5e0
&nbsp;  GVGV&#8203;::GV = 0xd1e2d8   "Devel&#8203;::Caller" :&#8203;: "called\_with"
&nbsp;  FILE = "/home/nick/\.cpan/build/Devel\-Caller\-2\.04\-NwLzGr/blib/lib/Devel/Caller\.pm"
&nbsp;  DEPTH = 1
&nbsp;  FLAGS = 0x0
&nbsp;  OUTSIDE\_SEQ = 1832
&nbsp;  PADLIST = 0xd1e4b8
&nbsp;  OUTSIDE = 0xa63cd0 \(UNIQUE\)
\(gdb\) call Perl\_sv\_dump\(my\_perl\,  0xd1e4b8\)
SV = PVAV\(0xcdaff8\) at 0xd1e4b8
&nbsp;  REFCNT = 1
&nbsp;  FLAGS = \(\)
&nbsp;  ARRAY = 0xd2c638
&nbsp;  FILL = 1
&nbsp;  MAX = 3
&nbsp;  ARYLEN = 0x0
&nbsp;  FLAGS = \(\)
\(gdb\) p my\_perl\->Icomppad
$10 = \(AV \*\) 0xd1e4e8
\(gdb\) p my\_perl\->Icurpad
$11 = \(SV \*\*\) 0xd5cc68
\(gdb\) p \(\(SV \*\*\)0xd2c638\)\[0\]
$12 = \(struct sv \*\) 0xd1e4d0
\(gdb\) p \(\(SV \*\*\)0xd2c638\)\[1\]
$13 = \(struct sv \*\) 0xd1e4e8
\(gdb\) p my\_perl\->Icomppad\->sv\_u\.svu\_array
$14 = \(SV \*\*\) 0xd5cc68

Note that at the time of the call the current pad\, as held in PL\_comppad and
PL\_curpad is the pad of Devel&#8203;::Caller&#8203;::called\_with\, not main\. Yet the code in
B\.xs is accessing that pad instead of main's pad\, using offsets in the OPs
for main's pad\.

If I'm right\, I don't know how this ever worked\.

\(Specifically\, B&#8203;::PADOP&#8203;::sv and B&#8203;::PADOP&#8203;::gv\, except when the current pad
happens to be the pad for the OPs in question\)

Nicholas Clark

**Comment by p5pRT** [comment]
### From @nwc10

On Mon\, Apr 05\, 2010 at 08&#8203;:57&#8203;:02AM \+0100\, Nicholas Clark wrote&#8203;:
> On Sun\, Apr 04\, 2010 at 10&#8203;:15&#8203;:24PM \+0100\, Nicholas Clark wrote&#8203;:

> > But that array only has 218 elements\, offsets 0 to 217\. So 258 is way out of
> > bounds\. How did \*that\* happen?

> If I'm right\, I don't know how this ever worked\.

Pure chance\.

> \(Specifically\, B&#8203;::PADOP&#8203;::sv and B&#8203;::PADOP&#8203;::gv\, except when the current pad
> happens to be the pad for the OPs in question\)

If I patch B\.xs like this&#8203;:

<details><summary>Inline Patch</summary>

```diff
diff --git a/ext/B/B.xs b/ext/B/B.xs
index 2b6fb8d..3c05970 100644
--- a/ext/B/B.xs
+++ b/ext/B/B.xs
@@ -1151,6 +1151,14 @@ PADOP_sv(o)
 B::GV
 PADOP_gv(o)
 	B::PADOP o
+    CODE:
+        if (PADOP_padix(o) > AvFILL(PL_comppad)) {
+	   PerlIO_printf(PerlIO_stderr(), "%d > %d\n",
+	    (int)PADOP_padix(o), (int) AvFILL(PL_comppad));
+	}
+	RETVAL = PADOP_gv(o);
+    OUTPUT:
+	RETVAL
 
 MODULE = B	PACKAGE = B::PVOP		PREFIX = PVOP_
 


```
</details>
then this is what a run with 5.10.1 looks like:

ok 56 \- package called\_assign\($T&#8203;::bar\)
ok 57 \- package called\_assign\($T&#8203;::baz\)
ok 58 \- package called\_assign\($T&#8203;::quux\, $T&#8203;::bar\)
ok 59 \- package called\_assign\(@&#8203;T&#8203;::bar\)
ok 60 \- package called\_assign\(@&#8203;T&#8203;::baz\)
ok 61 \- package called\_assign\(@&#8203;T&#8203;::quux\, @&#8203;T&#8203;::bar\)
ok 62 \- package called\_assign\(@&#8203;T&#8203;::flange\)
ok 63 \- package called\_assign\(%T&#8203;::bar\)
ok 64 \- package called\_assign\(%T&#8203;::baz\)
ok 65 \- package called\_assign\(%T&#8203;::quux\, %T&#8203;::bar\)
216 > 212
ok 66 \- package called\_assign\(%T&#8203;::flange\)
ok 67 \- called\_as\_method
ok 68 \- called\_as\_method
ok 69 \- called\_as\_method
ok 70

whereas this is what a run with 5\.12\.0\-RC3 looks like

ok 56 \- package called\_assign\($T&#8203;::bar\)
ok 57 \- package called\_assign\($T&#8203;::baz\)
ok 58 \- package called\_assign\($T&#8203;::quux\, $T&#8203;::bar\)
ok 59 \- package called\_assign\(@&#8203;T&#8203;::bar\)
ok 60 \- package called\_assign\(@&#8203;T&#8203;::baz\)
220 > 217
ok 61 \- package called\_assign\(@&#8203;T&#8203;::quux\, @&#8203;T&#8203;::bar\)
226 > 217
ok 62 \- package called\_assign\(@&#8203;T&#8203;::flange\)
235 > 217
ok 63 \- package called\_assign\(%T&#8203;::bar\)
242 > 217
ok 64 \- package called\_assign\(%T&#8203;::baz\)
249 > 217
252 > 217
ok 65 \- package called\_assign\(%T&#8203;::quux\, %T&#8203;::bar\)
258 > 217
ok 66 \- package called\_assign\(%T&#8203;::flange\)
ok 67 \- called\_as\_method
ok 68 \- called\_as\_method
ok 69 \- called\_as\_method
ok 70

So there always was a problem\. If you look at the actual code in Devel&#8203;::Caller&#8203;:

&nbsp;            my $consider = \($op\->name eq "gvsv"\) ? $op : $prev;
&nbsp;            my $gv = $consider\->gv;
&nbsp;            print "consider&#8203;: $consider "\, $consider\->name\, " gv $gv\\n"
&nbsp;              if $DEBUG;
&nbsp;            if \(ref $consider eq 'B&#8203;::PADOP'\) \{
&nbsp;                print "GV is really a padgv\\n" if $DEBUG;
&nbsp;                $gv = $padv\->ARRAYelt\( $consider\->padix \);
&nbsp;                print "NEW GV $gv\\n" if $DEBUG;
&nbsp;            \}

Note that as we're dealing with a PADOP\, all it uses the return of \->gv for
is to print out debugging\. $gv is then \*correctly\* assigned by getting the
pad index\, and then \*longhand\* looking up at that index \*in the correct pad\*\.

So that code will work as long as the \(out of bounds\) memory address that
happens to be read by B&#8203;::PADOP&#8203;::gv isn't NULL\, and points \*somewhere\* valid\,
given that the code here will read a memory location and then wrap up a
pointer\, but \*then nothing does anything with it\*&#8203;:

\#define PADOP\_gv\(o\)    \(\(o\->op\_padix \\
&nbsp;              && SvTYPE\(PAD\_SVl\(o\->op\_padix\)\) == SVt\_PVGV\) \\
&nbsp;             ? \(GV\*\)PAD\_SVl\(o\->op\_padix\) : \(GV \*\)NULL\)


So how come B&#8203;::Concise works?

&nbsp;    elsif \($h\{class\} eq "SVOP" or $h\{class\} eq "PADOP"\) \{
&nbsp;    unless \($h\{name\} eq 'aelemfast' and $op\->flags & OPf\_SPECIAL\) \{
&nbsp;        my $idx = \($h\{class\} eq "SVOP"\) ? $op\->targ : $op\->padix;
&nbsp;        my $preferpv = $h\{name\} eq "method\_named";
&nbsp;        if \($h\{class\} eq "PADOP" or \!$\{$op\->sv\}\) \{
&nbsp;        my $sv = \(\($curcv\->PADLIST\->ARRAY\)\[1\]\->ARRAY\)\[$idx\];
&nbsp;        $h\{arg\} = "\[" \. concise\_sv\($sv\, \\%h\, $preferpv\) \. "\]";
&nbsp;        $h\{targarglife\} = $h\{targarg\} = "";
&nbsp;        \} else \{
&nbsp;        $h\{arg\} = "\(" \. concise\_sv\($op\->sv\, \\%h\, $preferpv\) \. "\)";
&nbsp;        \}
&nbsp;    \}
&nbsp;    \}


Because it do \*doesn't use\* the B&#8203;::PADOP&#8203;::gv in anger\. It too does the lookup
\*longhand\* \*in the correct pad\*\.

So\, the simplest work around seems to be to proffer Richard a patch for
Devel&#8203;::Caller that reorders the debug code after the PADOP lookup\.

The correct fix is to refactor B\.xs so that its objects for OPs \(or at least
PADOPs\) hold a reference back to their pad \(or their CV\)\, and change PADOP\_sv
and PADOP\_gv to use that reference\, rather than randomly looking at offsets
from the current pad\.

Nicholas Clark

**Comment by p5pRT** [comment]
### From @rafl

On Sun\, Apr 04\, 2010 at 02&#8203;:15&#8203;:59PM \-0700\, Nicholas Clark via RT wrote&#8203;:
> But that array only has 218 elements\, offsets 0 to 217\. So 258 is way out of
> bounds\. How did \*that\* happen?

> \(Only hunch \- what type is the op? Is it the correct type for PADOP\_gv to be
> valid on it?\)

It's an OP\_GV\, so it's a valid PADOP for threaded perls\. The opcode is
being created manually \(i\.e\. not using newPADOP\, newGVOP or anything
like that\) in Perl\_ck\_rvconst\. At that time\, the padix there is within
the bounds of the comppad\, and contains the expected value instead of a
NULL\.

I still have no idea what's causing it to disappear later\. Initially I
expected the op\_clear parts of f7461760 to be responsible somehow\, but
that doesn't seem to be the case\. gv\_try\_downgrade is never called for
the GV in question\.

Could it be related to the slightly changed order of op construction
that f7461760 introduced?


\-\- 
BOFH excuse \#146&#8203;:
Communications satellite used by the military for star wars\.

**Comment by p5pRT** [comment]
### From @rafl

On Mon\, Apr 05\, 2010 at 01&#8203;:52&#8203;:55AM \-0700\, Nicholas Clark via RT wrote&#8203;:
> Because it do \*doesn't use\* the B&#8203;::PADOP&#8203;::gv in anger\. It too does the lookup
> \*longhand\* \*in the correct pad\*\.
>
> So\, the simplest work around seems to be to proffer Richard a patch for
> Devel&#8203;::Caller that reorders the debug code after the PADOP lookup\.

You're absolutely right\. The patch is at
http&#8203;://github\.com/rafl/perl\-devel\-caller/commit/248a23390eef48a73bb717be085da58ce50ff784

Richard has been notified\.


Thanks\!

\-\- 
BOFH excuse \#123&#8203;:
user to computer ratio too high\.

**Comment by p5pRT** [comment]
### From zefram@fysh.org

It is impossible for B to determine which pad an op refers to\, and
when an XS method is called it's rather unlikely that an appropriate
pad will be available at all\.  The B&#8203;::PADOP&#8203;::gv method was therefore
misconceived\.  Since this ticket was opened\, it has been tweaked in commit
3a23d767cf63fb2e8de3d79eadee49bbc33eec53 by DaveM\, who was evidently
unaware of this ticket but independently discovered the bogosity\.  That's
probably the best resolution available\.  This ticket should be closed\.

\-zefram

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
