### ISSUE TITLE
5.12.0 crash on diverse platforms

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10335]
Migrated from [rt.perl.org#74542](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=74542) (status was 'resolved')

Searchable as RT74542$

**Comment by p5pRT** [comment]
### From occitan@esperanto.org

One of the utilities of makepp SEGVs in the regression test on each of Linux 
x86 and Win \(both ActiveState\) and Solaris 10 Sparc self compiled as 32bit\. 
This last worked with CPAN testers on i86pc\-solaris\-V5\.11\.5\.

I have narrowed it down to the following little test&#8203;:

\#\!/usr/bin/perl \-w

sub f \{
&nbsp;   lstat '/';
&nbsp;   \-d \_;
\}

$\_ = split /x/\, f;

The context split \(with any regexp\) is needed\, though it crashes in \-d \_\.

\#0  0x0810f3fb in Perl\_pp\_ftrowned \(\)
\#1  0x080cb352 in Perl\_runops\_standard \(\)
\#2  0x08074af2 in S\_run\_body \(\)
\#3  0x0807498a in perl\_run \(\)
\#4  0x08060ded in main \(\)

Besides a fix for future versions\, I am desperate for a workaround ;\-\)

coralament / best Grötens / liebe Grüße / best regards / elkorajn salutojn
Daniel Pfeiffer

\-\- 
lerne / learn / apprends / lär dig / ucz się    Esperanto&#8203;:
&nbsp;                     http&#8203;://lernu\.net  /  http&#8203;://ikurso\.net

**Comment by p5pRT** [comment]
### From @rgarcia

On 21 April 2010 02&#8203;:03\, Daniel Pfeiffer \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> One of the utilities of makepp SEGVs in the regression test on each of Linux
> x86 and Win \(both ActiveState\) and Solaris 10 Sparc self compiled as 32bit\.
> This last worked with CPAN testers on i86pc\-solaris\-V5\.11\.5\.
>
> I have narrowed it down to the following little test&#8203;:
>
> \#\!/usr/bin/perl \-w
>
> sub f \{
>   lstat '/';
>   \-d \_;
> \}
>
> $\_ = split /x/\, f;
>
> The context split \(with any regexp\) is needed\, though it crashes in \-d \_\.
>
> \#0  0x0810f3fb in Perl\_pp\_ftrowned \(\)
> \#1  0x080cb352 in Perl\_runops\_standard \(\)
> \#2  0x08074af2 in S\_run\_body \(\)
> \#3  0x0807498a in perl\_run \(\)
> \#4  0x08060ded in main \(\)
>
> Besides a fix for future versions\, I am desperate for a workaround ;\-\)

Apparently\, a workaround is to use a perl compiled with \-DDEBUGGING support\.\.\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @nwc10

On Wed\, Apr 21\, 2010 at 03&#8203;:08&#8203;:58PM \+0200\, Rafael Garcia\-Suarez wrote&#8203;:
> On 21 April 2010 02&#8203;:03\, Daniel Pfeiffer \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> > One of the utilities of makepp SEGVs in the regression test on each of Linux
> > x86 and Win \(both ActiveState\) and Solaris 10 Sparc self compiled as 32bit\.
> > This last worked with CPAN testers on i86pc\-solaris\-V5\.11\.5\.
> >
> > I have narrowed it down to the following little test&#8203;:
> >
> > \#\!/usr/bin/perl \-w
> >
> > sub f \{
> >   lstat '/';
> >   \-d \_;
> > \}
> >
> > $\_ = split /x/\, f;
> >
> > The context split \(with any regexp\) is needed\, though it crashes in \-d \_\.
> >
> > \#0  0x0810f3fb in Perl\_pp\_ftrowned \(\)
> > \#1  0x080cb352 in Perl\_runops\_standard \(\)
> > \#2  0x08074af2 in S\_run\_body \(\)
> > \#3  0x0807498a in perl\_run \(\)
> > \#4  0x08060ded in main \(\)
> >
> > Besides a fix for future versions\, I am desperate for a workaround ;\-\)
> 
> Apparently\, a workaround is to use a perl compiled with \-DDEBUGGING support\.\.\.

I'm not sure\. I've now build a perl without that on Linux\, and I see no
problem either\. I can't replicate this\.

$ \./perl \-Ilib \-V
Summary of my perl5 \(revision 5 version 13 subversion 0\) configuration&#8203;:
&nbsp;  Derived from&#8203;: f768f60b565004f735138c26b9a0823b95e9f470
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.18\.8\-xenu\, archname=x86\_64\-linux
&nbsp;    uname='linux eris 2\.6\.18\.8\-xenu \#1 smp sat oct 3 10&#8203;:27&#8203;:42 bst 2009 x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel=y \-Dcc=ccache gcc \-Dld=gcc \-Ubincompat5005 \-Uinstallusrbinperl \-Dcf\_email=nick@&#8203;ccl4\.org \-Dperladmin=nick@&#8203;ccl4\.org \-Dinc\_version\_list=  \-Dinc\_version\_list\_init=0 \-Doptimize=\-Os \-Uusethreads \-Uuse64bitall \-Uusemymalloc \-Duseperlio \-Dprefix=~/Sandpit/snap5\.9\.x\-v5\.13\.0\-14\-gf768f60 \-Uusevendorprefix \-Uvendorprefix=~/Sandpit/snap5\.9\.x\-v5\.13\.0\-14\-gf768f60 \-Dinstallman1dir=none \-Dinstallman3dir=none \-Uuserelocatableinc \-de'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=undef\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache gcc'\, ccflags ='\-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-Os'\,
&nbsp;    cppflags='\-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.3\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='gcc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64
&nbsp;    libs=\-lnsl \-ldb \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=/lib/libc\-2\.7\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.7'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-Os \-L/usr/local/lib \-fstack\-protector'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: PERL\_DONT\_CREATE\_GVSV PERL\_MALLOC\_WRAP PERL\_USE\_DEVEL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_PERLIO
&nbsp;                        USE\_PERL\_ATOF
&nbsp;  Locally applied patches&#8203;:
&nbsp;        uncommitted\-changes
&nbsp;  Built under linux
&nbsp;  Compiled at Apr 21 2010 14&#8203;:21&#8203;:19
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /home/nick/Sandpit/snap5\.9\.x\-v5\.13\.0\-14\-gf768f60/lib/perl5/site\_perl/5\.13\.0/x86\_64\-linux
&nbsp;    /home/nick/Sandpit/snap5\.9\.x\-v5\.13\.0\-14\-gf768f60/lib/perl5/site\_perl/5\.13\.0
&nbsp;    /home/nick/Sandpit/snap5\.9\.x\-v5\.13\.0\-14\-gf768f60/lib/perl5/5\.13\.0/x86\_64\-linux
&nbsp;    /home/nick/Sandpit/snap5\.9\.x\-v5\.13\.0\-14\-gf768f60/lib/perl5/5\.13\.0
&nbsp;    \.


So I'm not sure how to replicate this\, or\, for that matter\, what changes
ActiveState make from the 5\.12\.0 release to build their perl


A&#8203;: could you send the output of perl \-V for your perl on Linux
B&#8203;: are you able to build the 5\.12\.0 release from source \(on Linux is most
&nbsp;   useful\) and replicate your problem with that? Stack traces sadly aren't
&nbsp;   that useful unless they have debugging symbols\.
&nbsp;   \(Source is at http&#8203;://www\.cpan\.org/src/perl\-5\.12\.0\.tar\.bz2 for example\)

Nicholas Clark
&nbsp;

**Comment by p5pRT** [comment]
### From @jdhedden

On Wed\, Apr 21\, 2010 at 09&#8203;:34\, Nicholas Clark \<nick@&#8203;ccl4\.org> wrote&#8203;:
> On Wed\, Apr 21\, 2010 at 03&#8203;:08&#8203;:58PM \+0200\, Rafael Garcia\-Suarez wrote&#8203;:
>> On 21 April 2010 02&#8203;:03\, Daniel Pfeiffer \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
>> > One of the utilities of makepp SEGVs in the regression test on each of Linux
>> > x86 and Win \(both ActiveState\) and Solaris 10 Sparc self compiled as 32bit\.
>> > This last worked with CPAN testers on i86pc\-solaris\-V5\.11\.5\.
>> >
>> > I have narrowed it down to the following little test&#8203;:
>> >
>> > \#\!/usr/bin/perl \-w
>> >
>> > sub f \{
>> >   lstat '/';
>> >   \-d \_;
>> > \}
>> >
>> > $\_ = split /x/\, f;
>> >
>> > The context split \(with any regexp\) is needed\, though it crashes in \-d \_\.
>> >
>> > \#0  0x0810f3fb in Perl\_pp\_ftrowned \(\)
>> > \#1  0x080cb352 in Perl\_runops\_standard \(\)
>> > \#2  0x08074af2 in S\_run\_body \(\)
>> > \#3  0x0807498a in perl\_run \(\)
>> > \#4  0x08060ded in main \(\)
>> >
>> > Besides a fix for future versions\, I am desperate for a workaround ;\-\)
>>
>> Apparently\, a workaround is to use a perl compiled with \-DDEBUGGING support\.\.\.
>
> I'm not sure\. I've now build a perl without that on Linux\, and I see no
> problem either\. I can't replicate this\.

I tried this with blead under Cygwin on Windows\, and it segfaults\.

**Comment by p5pRT** [comment]
### From @rgs

This is now fixed by the patch below\, which I would like to nominate for inclusion in 5\.12\.1\.

commit 94fa954eaae532928977ae7f7290536783269b6e
Author&#8203;: Rafael Garcia\-Suarez \<rgs@&#8203;consttype\.org>
Date&#8203;:   Wed Apr 21 15&#8203;:47&#8203;:36 2010 \+0200

&nbsp;    Fix \[perl \#74542\] 5\.12\.0 crash on diverse platforms
&nbsp;    
&nbsp;    Filetest ops don't always expect an op on the stack\, so we should use
&nbsp;    TOPs only if we're sure that we're not stat'ing the \_ filehandle\.
&nbsp;    This is indicated by OPf\_KIDS \(as checked in ck\_ftst\)\.

<details><summary>Inline Patch</summary>

```diff
diff --git a/pp.h b/pp.h
index 9d078af..c36502a 100644
--- a/pp.h
+++ b/pp.h
@@ -474,7 +474,8 @@ Does not use C<TARG>.  See also C<XPUSHu>, C<mPUSHu> and 

```
</details>
C<PUSHu>.
 \#define tryAMAGICftest\(chr\)                            \\
&nbsp;     STMT\_START \{                                       \\
&nbsp;        assert\(chr \!= '?'\);                             \\
\-       if \(SvAMAGIC\(TOPs\)\) \{                           \\
\+       if \(\(PL\_op\->op\_flags & OPf\_KIDS\)                \\
\+               && SvAMAGIC\(TOPs\)\) \{                    \\
&nbsp;            const char tmpchr = \(chr\);                  \\
&nbsp;            SV \* const tmpsv = amagic\_call\(TOPs\,        \\
&nbsp;                newSVpvn\_flags\(&tmpchr\, 1\, SVs\_TEMP\)\,   \\

**Comment by p5pRT** [comment]
@rgs - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From perl@profvince.com


> On 21 April 2010 02&#8203;:03\, Daniel Pfeiffer\<perlbug\-followup@&#8203;perl\.org>  wrote&#8203;:
>    
>> One of the utilities of makepp SEGVs in the regression test on each of Linux
>> x86 and Win \(both ActiveState\) and Solaris 10 Sparc self compiled as 32bit\.
>> This last worked with CPAN testers on i86pc\-solaris\-V5\.11\.5\.
>>
>> I have narrowed it down to the following little test&#8203;:
>>
>> \#\!/usr/bin/perl \-w
>>
>> sub f \{
>>    lstat '/';
>>    \-d \_;
>> \}
>>
>> $\_ = split /x/\, f;
>>
>> The context split \(with any regexp\) is needed\, though it crashes in \-d \_\.
>>
>> \#0  0x0810f3fb in Perl\_pp\_ftrowned \(\)
>> \#1  0x080cb352 in Perl\_runops\_standard \(\)
>> \#2  0x08074af2 in S\_run\_body \(\)
>> \#3  0x0807498a in perl\_run \(\)
>> \#4  0x08060ded in main \(\)
>>
>> Besides a fix for future versions\, I am desperate for a workaround ;\-\)
>>      
> Apparently\, a workaround is to use a perl compiled with \-DDEBUGGING support\.\.\.
>    

Replacing the bare '\_' with '\*\_' will also prevent the segfault\.

Vincent\.

**Comment by p5pRT** [comment]
### From perl@profvince.com


> This is now fixed by the patch below\, which I would like to nominate for inclusion in 5\.12\.1\.
>    
I approve of this patch\.

V\.

**Comment by p5pRT** [comment]
### From @obra




On Wed\, Apr 21\, 2010 at 04&#8203;:37&#8203;:53PM \+0200\, Vincent Pit wrote&#8203;:
> 
> >This is now fixed by the patch below\, which I would like to nominate for inclusion in 5\.12\.1\.
> I approve of this patch\.

\+1

> 
> V\.

\-\-
