### ISSUE TITLE
segfault in PerlIOBuf_fill when filehandle is closed in a signal handler

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10422]
Migrated from [rt.perl.org#75556](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=75556) (status was 'resolved')

Searchable as RT75556$

**Comment by p5pRT** [comment]
### From chrisb@debian.org


This is a bug report for perl from chrisb@&#8203;debian\.org\,
generated with the help of perlbug 1\.39 running under perl 5\.10\.1\.




---
This bug was originally filed in the Debian Bug Tracking System&#8203;:
http&#8203;://bugs\.debian\.org/cgi\-bin/bugreport\.cgi?bug=275357

If a blocking read operation is interrupted by a signal\, and the signal
handler then closes the filehandle\, perl will segfault when it returns from
the signal\.

== bug\.pl ==
\#\!/usr/bin/perl

$SIG\{ALRM\} = sub \{ close\(FIFO\) \};
open \(FIFO\, "\< fifo"\);
alarm\(1\); 
$\_ = \<FIFO>;
============

Steps to reproduce&#8203;:

$ mknod fifo p
$ cat > fifo &
$ perl bug\.pl

When the alarm is triggered\, the perl process will segfault&#8203;:

Starting program&#8203;: /usr/bin/debugperl 275357\.pl 
\[Thread debugging using libthread\_db enabled\]

Program received signal SIGSEGV\, Segmentation fault\.
0x000000000059de23 in PerlIOBuf\_fill \(my\_perl=0x870010\, f=0x88ca88\) at perlio\.c&#8203;:3901
3901    perlio\.c&#8203;: No such file or directory\.
&nbsp;        in perlio\.c
\(gdb\) bt
\#0  0x000000000059de23 in PerlIOBuf\_fill \(my\_perl=0x870010\, f=0x88ca88\) at perlio\.c&#8203;:3901
\#1  0x000000000059b228 in Perl\_PerlIO\_fill \(my\_perl=0x5\, f=0x8a1638\) at perlio\.c&#8203;:1725
\#2  0x000000000059c1fb in PerlIOBase\_read \(my\_perl=0x870010\, f=0x88ca88\, vbuf=\<value optimized out>\, count=1\) at perlio\.c&#8203;:2143
\#3  0x000000000059c338 in PerlIO\_getc \(f=0x88ca88\) at perlio\.c&#8203;:5066
\#4  0x0000000000506251 in Perl\_sv\_gets \(my\_perl=\<value optimized out>\, sv=0x8a4038\, fp=\<value optimized out>\, append=0\) at sv\.c&#8203;:6853
\#5  0x00000000004cf66f in Perl\_do\_readline \(my\_perl=0x870010\) at pp\_hot\.c&#8203;:1665
\#6  0x000000000049b34b in Perl\_runops\_debug \(my\_perl=0x870010\) at dump\.c&#8203;:1968
\#7  0x000000000043d04f in S\_run\_body \(my\_perl=\<value optimized out>\) at perl\.c&#8203;:2431
\#8  perl\_run \(my\_perl=\<value optimized out>\) at perl\.c&#8203;:2349
\#9  0x0000000000421b4c in main \(argc=2\, argv=0x7fffffffdac8\, env=0x7fffffffdae0\) at perlmain\.c&#8203;:117

This perlbug output and the above backtrace are with perl 5\.10\.1\, but I've
also tested with blead and the issue is still present\.

There's some extra analysis on the Debian bug report&#8203;:

==========
PerlIOUnix\_read has a loop which makes a blocking read\, and calls
PERL\_ASYNC\_CHECK\(\) if the read is interrupted by a signal\.

Once PERL\_ASYNC\_CHECK\(\) has returned\, the pointers "f" and "buf"
in PerlIOUnix\_read are pointing to freed space\, which looks fairly
simple to detect and handle\.  Similar bugs also need fixing
elsewhere in perlio\.c\.
==========



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=medium


---
Site configuration information for perl 5\.10\.1&#8203;:

Configured by Debian Project at Sun Apr 11 20&#8203;:09&#8203;:49 UTC 2010\.

Summary of my perl5 \(revision 5 version 10 subversion 1\) configuration&#8203;:
&nbsp;   
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.32\-3\-amd64\, archname=x86\_64\-linux\-gnu\-thread\-multi
&nbsp;    uname='linux madeleine 2\.6\.32\-3\-amd64 \#1 smp wed feb 24 18&#8203;:07&#8203;:42 utc 2010 x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN \-Dcccdlflags=\-fPIC \-Darchname=x86\_64\-linux\-gnu \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.10 \-Darchlib=/usr/lib/perl/5\.10 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.10\.1 \-Dsitearch=/usr/local/lib/perl/5\.10\.1 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1 \-Dsiteman3dir=/usr/local/man/man3 \-Dman1ext=1 \-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Ud\_ualarm \-Uusesfio \-Uusenm \-DDEBUGGING=\-g \-Doptimize=\-O2 \-Duseshrplib \-Dlibperl=libperl\.so\.5\.10\.1 \-Dd\_dosuid \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2 \-g'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.4\.3'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64
&nbsp;    libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    libc=/lib/libc\-2\.10\.2\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.10\.1
&nbsp;    gnulibc\_version='2\.10\.2'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-g \-L/usr/local/lib \-fstack\-protector'

Locally applied patches&#8203;:
&nbsp;    DEBPKG&#8203;:debian/arm\_thread\_stress\_timeout \- http&#8203;://bugs\.debian\.org/501970 Raise the timeout of ext/threads/shared/t/stress\.t to accommodate slower build hosts
&nbsp;    DEBPKG&#8203;:debian/cpan\_config\_path \- Set location of CPAN&#8203;::Config to /etc/perl as /usr may not be writable\.
&nbsp;    DEBPKG&#8203;:debian/cpan\_definstalldirs \- Provide a sensible INSTALLDIRS default for modules installed from CPAN\.
&nbsp;    DEBPKG&#8203;:debian/db\_file\_ver \- http&#8203;://bugs\.debian\.org/340047 Remove overly restrictive DB\_File version check\.
&nbsp;    DEBPKG&#8203;:debian/doc\_info \- Replace generic man\(1\) instructions with Debian\-specific information\.
&nbsp;    DEBPKG&#8203;:debian/enc2xs\_inc \- http&#8203;://bugs\.debian\.org/290336 Tweak enc2xs to follow symlinks and ignore missing @&#8203;INC directories\.
&nbsp;    DEBPKG&#8203;:debian/errno\_ver \- http&#8203;://bugs\.debian\.org/343351 Remove Errno version check due to upgrade problems with long\-running processes\.
&nbsp;    DEBPKG&#8203;:debian/extutils\_hacks \- Various debian\-specific ExtUtils changes
&nbsp;    DEBPKG&#8203;:debian/fakeroot \- Postpone LD\_LIBRARY\_PATH evaluation to the binary targets\.
&nbsp;    DEBPKG&#8203;:debian/instmodsh\_doc \- Debian policy doesn't install \.packlist files for core or vendor\.
&nbsp;    DEBPKG&#8203;:debian/ld\_run\_path \- Remove standard libs from LD\_RUN\_PATH as per Debian policy\.
&nbsp;    DEBPKG&#8203;:debian/libnet\_config\_path \- Set location of libnet\.cfg to /etc/perl/Net as /usr may not be writable\.
&nbsp;    DEBPKG&#8203;:debian/m68k\_thread\_stress \- http&#8203;://bugs\.debian\.org/495826 Disable some threads tests on m68k for now due to missing TLS\.
&nbsp;    DEBPKG&#8203;:debian/mod\_paths \- Tweak @&#8203;INC ordering for Debian
&nbsp;    DEBPKG&#8203;:debian/module\_build\_man\_extensions \- http&#8203;://bugs\.debian\.org/479460 Adjust Module&#8203;::Build manual page extensions for the Debian Perl policy
&nbsp;    DEBPKG&#8203;:debian/perl\_synopsis \- http&#8203;://bugs\.debian\.org/278323 Rearrange perl\.pod
&nbsp;    DEBPKG&#8203;:debian/prune\_libs \- http&#8203;://bugs\.debian\.org/128355 Prune the list of libraries wanted to what we actually need\.
&nbsp;    DEBPKG&#8203;:debian/use\_gdbm \- Explicitly link against \-lgdbm\_compat in ODBM\_File/NDBM\_File\. 
&nbsp;    DEBPKG&#8203;:fixes/assorted\_docs \- http&#8203;://bugs\.debian\.org/443733 \[384f06a\] Math&#8203;::BigInt&#8203;::CalcEmu documentation grammar fix
&nbsp;    DEBPKG&#8203;:fixes/net\_smtp\_docs \- http&#8203;://bugs\.debian\.org/100195 \[rt\.cpan\.org \#36038\] Document the Net&#8203;::SMTP 'Port' option
&nbsp;    DEBPKG&#8203;:fixes/processPL \- http&#8203;://bugs\.debian\.org/357264 \[rt\.cpan\.org \#17224\] Always use PERLRUNINST when building perl modules\.
&nbsp;    DEBPKG&#8203;:debian/perlivp \- http&#8203;://bugs\.debian\.org/510895 Make perlivp skip include directories in /usr/local
&nbsp;    DEBPKG&#8203;:fixes/pod2man\-index\-backslash \- http&#8203;://bugs\.debian\.org/521256 Escape backslashes in \.IX entries
&nbsp;    DEBPKG&#8203;:debian/disable\-zlib\-bundling \- Disable zlib bundling in Compress&#8203;::Raw&#8203;::Zlib
&nbsp;    DEBPKG&#8203;:fixes/kfreebsd\_cppsymbols \- http&#8203;://bugs\.debian\.org/533098 \[3b910a0\] Add gcc predefined macros to $Config\{cppsymbols\} on GNU/kFreeBSD\.
&nbsp;    DEBPKG&#8203;:debian/cpanplus\_definstalldirs \- http&#8203;://bugs\.debian\.org/533707 Configure CPANPLUS to use the site directories by default\.
&nbsp;    DEBPKG&#8203;:debian/cpanplus\_config\_path \- Save local versions of CPANPLUS&#8203;::Config&#8203;::System into /etc/perl\.
&nbsp;    DEBPKG&#8203;:fixes/kfreebsd\-filecopy\-pipes \- http&#8203;://bugs\.debian\.org/537555 \[16f708c\] Fix File&#8203;::Copy&#8203;::copy with pipes on GNU/kFreeBSD
&nbsp;    DEBPKG&#8203;:fixes/anon\-tmpfile\-dir \- http&#8203;://bugs\.debian\.org/528544 \[perl \#66452\] Honor TMPDIR when open\(\)ing an anonymous temporary file
&nbsp;    DEBPKG&#8203;:fixes/abstract\-sockets \- http&#8203;://bugs\.debian\.org/329291 \[89904c0\] Add support for Abstract namespace sockets\.
&nbsp;    DEBPKG&#8203;:fixes/hurd\_cppsymbols \- http&#8203;://bugs\.debian\.org/544307 \[eeb92b7\] Add gcc predefined macros to $Config\{cppsymbols\} on GNU/Hurd\.
&nbsp;    DEBPKG&#8203;:fixes/autodie\-flock \- http&#8203;://bugs\.debian\.org/543731 Allow for flock returning EAGAIN instead of EWOULDBLOCK on linux/parisc
&nbsp;    DEBPKG&#8203;:fixes/archive\-tar\-instance\-error \- http&#8203;://bugs\.debian\.org/539355 \[rt\.cpan\.org \#48879\] Separate Archive&#8203;::Tar instance error strings from each other
&nbsp;    DEBPKG&#8203;:fixes/positive\-gpos \- http&#8203;://bugs\.debian\.org/545234 \[perl \#69056\] \[c584a96\] Fix \\\\G crash on first match
&nbsp;    DEBPKG&#8203;:debian/devel\-ppport\-ia64\-optim \- http&#8203;://bugs\.debian\.org/548943 Work around an ICE on ia64
&nbsp;    DEBPKG&#8203;:fixes/trie\-logic\-match \- http&#8203;://bugs\.debian\.org/552291 \[perl \#69973\] \[0abd0d7\] Fix a DoS in Unicode processing \[CVE\-2009\-3626\]
&nbsp;    DEBPKG&#8203;:fixes/hppa\-thread\-eagain \- http&#8203;://bugs\.debian\.org/554218 make the threads\-shared test suite more robust\, fixing failures on hppa
&nbsp;    DEBPKG&#8203;:fixes/crash\-on\-undefined\-destroy \- http&#8203;://bugs\.debian\.org/564074 \[perl \#71952\] \[1f15e67\] Fix a NULL pointer dereference when looking for a DESTROY method
&nbsp;    DEBPKG&#8203;:fixes/tainted\-errno \- http&#8203;://bugs\.debian\.org/574129 \[perl \#61976\] \[be1cf43\] fix an errno stringification bug in taint mode
&nbsp;    DEBPKG&#8203;:patchlevel \- http&#8203;://bugs\.debian\.org/567489 List packaged patches for 5\.10\.1\-12 in patchlevel\.h



---
@&#8203;INC for perl 5\.10\.1&#8203;:
&nbsp;    /etc/perl
&nbsp;    /usr/local/lib/perl/5\.10\.1
&nbsp;    /usr/local/share/perl/5\.10\.1
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/perl/5\.10
&nbsp;    /usr/share/perl/5\.10
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    \.



---
Environment for perl 5\.10\.1&#8203;:
&nbsp;    HOME=/home/chrisb
&nbsp;    LANG=en\_GB\.UTF\-8
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LC\_ALL=en\_GB\.UTF\-8
&nbsp;    LC\_CTYPE=en\_GB\.UTF\-8
&nbsp;    LC\_MESSAGES=en\_GB\.UTF\-8
&nbsp;    LC\_TIME=en\_GB\.UTF\-8
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/chrisb/bin&#8203;:/home/chrisb/bin&#8203;:/usr/bin&#8203;:/home/chrisb/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/games
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @iabyn

Still present in blead

**Comment by p5pRT** [comment]
### From @cpansprout

> PerlIOUnix\_read has a loop which makes a blocking read\, and calls
> PERL\_ASYNC\_CHECK\(\) if the read is interrupted by a signal\.
> 
> Once PERL\_ASYNC\_CHECK\(\) has returned\, the pointers "f" and "buf"
> in PerlIOUnix\_read are pointing to freed space\, which looks fairly
> simple to detect and handle\. Similar bugs also need fixing
> elsewhere in perlio\.c\.

I don’t know a lot about C\, but I think that the freed memory could be re\-used for something else\, in which case checking that it has been freed \(how do you do that\, BTW?\) will not be reliable\. \(Someone please correct me if I’m wrong\.\) Maybe we need some sort of refcounting mechanism for PerlIOl’s\. How much of the PerlIO API is public?

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Jul 25\, 2010 at 01&#8203;:02&#8203;:01PM \-0700\, Father Chrysostomos wrote&#8203;:
> > PerlIOUnix\_read has a loop which makes a blocking read\, and calls
> > PERL\_ASYNC\_CHECK\(\) if the read is interrupted by a signal\.
> > 
> > Once PERL\_ASYNC\_CHECK\(\) has returned\, the pointers "f" and "buf"
> > in PerlIOUnix\_read are pointing to freed space\, which looks fairly
> > simple to detect and handle\. Similar bugs also need fixing
> > elsewhere in perlio\.c\.
> 
> I don’t know a lot about C\, but I think that the freed memory could be
> re\-used for something else\, in which case checking that it has been
> freed \(how do you do that\, BTW?\) will not be reliable\. \(Someone please
> correct me if I’m wrong\.\) Maybe we need some sort of refcounting
> mechanism for PerlIOl’s\. How much of the PerlIO API is public?

Now fixed \(sort\-of\) by the following set of commits&#8203;:

&nbsp;    303f2dc3d5bda8ee962db318dd53acb167c07485
&nbsp;    16865ff7e97c2532fd2001d68cf18909acb0d838
&nbsp;    8995e67d43b457d0463f0581e10b390bc378c894
&nbsp;    cc6623a84b782d30463b9046c2916f35064a7e3f
&nbsp;    abf9167d3fff002ddaed53abb44d638387bca978

but most specifically by that last one&#8203;:

commit abf9167d3fff002ddaed53abb44d638387bca978
Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
AuthorDate&#8203;: Mon Nov 22 19&#8203;:18&#8203;:49 2010 \+0000
Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
CommitDate&#8203;: Fri Nov 26 16&#8203;:01&#8203;:34 2010 \+0000

&nbsp;    Make PerlIO marginally reentrant
&nbsp;    
&nbsp;    Currently if an operation on a file handle is interrupted\, and if
&nbsp;    the signal handler accesses that same file handle \(e\.g\. closes it\)\,
&nbsp;    then perl will crash\. See \[perl \#75556\]\.
&nbsp;    
&nbsp;    This commit provides some basic infrastructure to avoid segfaults\.
&nbsp;    Basically it adds a lock count field to each handle \(by re\-purposing the
&nbsp;    unused flags field in the PL\_perlio array\)\, then each time a signal
&nbsp;    handler is called\, the count is incremented\. Then various parts of PerlIO
&nbsp;    use a positive count to change behaviour\. Most importantly\, when layers
&nbsp;    are popped\, the PerlIOl structure is cleared\, but not freed\, and is left
&nbsp;    in the chain of layers\. This means that callers still holding pointers to
&nbsp;    the various layers won't access freed structures\. It does however mean
&nbsp;    that PerlIOl structs may be leaked\, and possibly slots in PL\_perlio\. But
&nbsp;    this is better than crashing\.
&nbsp;    
&nbsp;    Not much has been done to give sensible behaviour on re\-entrancy; for
&nbsp;    example\, a buffer that has already been written once might get written
&nbsp;    again\. Fixing this sort of thing would require a large\-scale audit of
&nbsp;    perlio\.c\.


Note that the glib fread\(\) function crashes if you call fclose\(\) in a
signal\-handler\, so we're better than that now :\-\)

\-\- 
"The GPL violates the U\.S\. Constitution\, together with copyright\,
antitrust and export control laws"
&nbsp;    \-\- SCO smoking crack again\.

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
