### ISSUE TITLE
Deleting non-existent values from %ENV causes segfault when compiled with PERL_USE_SAFE_PUTENV

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10565]
Migrated from [rt.perl.org#77372](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=77372) (status was 'open')

Searchable as RT77372$

**Comment by p5pRT** [comment]
### From chrishammond@ymail.com

#### Created by chrishammond@ymail.com



Hi\,

I've got an instance of Perl 5\.12\.1 which has been compiled using the PERL\_USE\_SAFE\_PUTENV flag defined\, and have noted that it segfaults if you try to clear a non\-existent value from the magic %ENV hash if local'ed\.


Using 5\.12\.1 compiled with with&#8203;:
config\_args="\-Accflags=\-DPERL\_USE\_SAFE\_PUTENV"


perl \-e "local %ENV;delete $ENV\{q\{UNDEFINED\}\}"
or
DEFINED=YES perl \-e "local %ENV;delete $ENV\{q\{DEFINED\}\}"

Segmentation fault \(core dumped\)

Process terminating with default action of signal 11 \(SIGSEGV\)&#8203;: dumping core

Invalid read of size 8
unsetenv \(setenv\.c&#8203;:295\)
by Perl\_magic\_clearenv




No seg fault from&#8203;:

DEFINED=YES perl \-e "delete local $ENV\{q\{DEFINED\}\}"
or
perl \-e "delete local $ENV\{q\{UNDEFINED\}\}"
or
DEFINED=YES perl \-e "local %ENV=%ENV;delete $ENV\{q\{DEFINED\}\}"
or
perl \-e "local %ENV=%ENV;delete $ENV\{q\{UNDEFINED\}\}"



Some code that does this&#8203;:
Math&#8203;::Pari utils/Math/PariBuild\.pm
Some code that did this&#8203;:
Google\-Chart 0\.05014 t/90\_env\_proxy\.t


Thanks\,

Chris

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.12.1:

Configured by pmbuild at Wed Aug 18 04:31:57 EDT 2010.

Summary of my perl5 (revision 5 version 12 subversion 1) configuration:
   
  Platform:
    osname=linux, osvers=2.6.18-194.3.1.el5, archname=x86_64-linux-thread-multi
    uname='linux ngbuilda01 2.6.18-194.3.1.el5 #1 smp sun may 2 04:17:42 edt 2010 x86_64 x86_64 x86_64 gnulinux '
    config_args='-des -Dprefix=/home/chammond/perl -Duseshrplib -Dusethreads -Accflags=-DPERL_USE_SAFE_PUTENV'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DPERL_USE_SAFE_PUTENV -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DPERL_USE_SAFE_PUTENV -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.3.2 20081105 (Red Hat 4.3.2-14)', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64 /usr/local/lib64
    libs=-lnsl -ldb -ldl -lm -lcrypt -lutil -lpthread -lc
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
    libc=/lib/libc-2.5.so, so=so, useshrplib=true, libperl=libperl.so
    gnulibc_version='2.5'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E -Wl,-rpath,/home/chammond/perl/lib/5.12.1/x86_64-linux-thread-multi/CORE'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector'

Locally applied patches:
    


@INC for perl 5.12.1:
    /home/chammond/perl/lib/site_perl/5.12.1/x86_64-linux-thread-multi
    /home/chammond/perl/lib/site_perl/5.12.1
    /home/chammond/perl/lib/5.12.1/x86_64-linux-thread-multi
    /home/chammond/perl/lib/5.12.1
    .


Environment for perl 5.12.1:
    HOME=/home/chammond
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/chammond/perl/bin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
chrishammond@ymail.com - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Aug 23\, 2010 at 02&#8203;:08&#8203;:21AM \-0700\, chrishammond@&#8203;ymail\.com wrote&#8203;:
> I've got an instance of Perl 5\.12\.1 which has been compiled using the
> PERL\_USE\_SAFE\_PUTENV flag defined\, and have noted that it segfaults if
> you try to clear a non\-existent value from the magic %ENV hash if
> local'ed\.
> 
> Using 5\.12\.1 compiled with with&#8203;:
> config\_args="\-Accflags=\-DPERL\_USE\_SAFE\_PUTENV"
> 
> perl \-e "local %ENV;delete $ENV\{q\{UNDEFINED\}\}"
> or
> DEFINED=YES perl \-e "local %ENV;delete $ENV\{q\{DEFINED\}\}"
> 
> Segmentation fault \(core dumped\)
> 
> Process terminating with default action of signal 11 \(SIGSEGV\)&#8203;: dumping core
> 
> Invalid read of size 8
> unsetenv \(setenv\.c&#8203;:295\)
> by Perl\_magic\_clearenv

I'm unable to reproduce this\, either on blead\, nor with a 5\.12\.1
configured as close as possible to the OPs\. Can anyone else do better?

Here's my config&#8203;:

Summary of my perl5 \(revision 5 version 12 subversion 1\) configuration&#8203;:
&nbsp;   
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.18\-194\.3\.1\.el5\, archname=x86\_64\-linux\-thread\-multi
&nbsp;    uname='linux ngbuilda01 2\.6\.18\-194\.3\.1\.el5 \#1 smp sun may 2 04&#8203;:17&#8203;:42 edt 2010 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;    config\_args='\-des \-Dprefix=/home/chammond/perl \-Duseshrplib \-Dusethreads \-Accflags=\-DPERL\_USE\_SAFE\_PUTENV'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DPERL\_USE\_SAFE\_PUTENV \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DPERL\_USE\_SAFE\_PUTENV \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.3\.2 20081105 \(Red Hat 4\.3\.2\-14\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64 /usr/local/lib64
&nbsp;    libs=\-lnsl \-ldb \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    libc=/lib/libc\-2\.5\.so\, so=so\, useshrplib=true\, libperl=libperl\.so
&nbsp;    gnulibc\_version='2\.5'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E \-Wl\,\-rpath\,/home/chammond/perl/lib/5\.12\.1/x86\_64\-linux\-thread\-multi/CORE'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-L/usr/local/lib \-fstack\-protector'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl 5\.12\.1&#8203;:
&nbsp;    /home/chammond/perl/lib/site\_perl/5\.12\.1/x86\_64\-linux\-thread\-multi
&nbsp;    /home/chammond/perl/lib/site\_perl/5\.12\.1
&nbsp;    /home/chammond/perl/lib/5\.12\.1/x86\_64\-linux\-thread\-multi
&nbsp;    /home/chammond/perl/lib/5\.12\.1
&nbsp;    \.



---
Environment for perl 5\.12\.1&#8203;:
&nbsp;    HOME=/home/chammond
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/chammond/perl/bin&#8203;:/bin&#8203;:/usr/sbin&#8203;:/usr/bin&#8203;:/usr/local/bin&#8203;:/usr/local/sbin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash



> Summary of my perl5 \(revision 5 version 12 subversion 1\) configuration&#8203;:
>    
>   Platform&#8203;:
>     osname=linux\, osvers=2\.6\.18\-194\.3\.1\.el5\, archname=x86\_64\-linux\-thread\-multi
>     uname='linux ngbuilda01 2\.6\.18\-194\.3\.1\.el5 \#1 smp sun may 2 04&#8203;:17&#8203;:42 edt 2010 x86\_64 x86\_64 x86\_64 gnulinux '
>     config\_args='\-des \-Dprefix=/home/chammond/perl \-Duseshrplib \-Dusethreads \-Accflags=\-DPERL\_USE\_SAFE\_PUTENV'
>     hint=recommended\, useposix=true\, d\_sigaction=define
>     useithreads=define\, usemultiplicity=define
>     useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
>     use64bitint=define\, use64bitall=define\, uselongdouble=undef
>     usemymalloc=n\, bincompat5005=undef
>   Compiler&#8203;:
>     cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DPERL\_USE\_SAFE\_PUTENV \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
>     optimize='\-O2'\,
>     cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DPERL\_USE\_SAFE\_PUTENV \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
>     ccversion=''\, gccversion='4\.3\.2 20081105 \(Red Hat 4\.3\.2\-14\)'\, gccosandvers=''
>     intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
>     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
>     ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
>     alignbytes=8\, prototype=define
>   Linker and Libraries&#8203;:
>     ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
>     libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64 /usr/local/lib64
>     libs=\-lnsl \-ldb \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
>     perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
>     libc=/lib/libc\-2\.5\.so\, so=so\, useshrplib=true\, libperl=libperl\.so
>     gnulibc\_version='2\.5'
>   Dynamic Linking&#8203;:
>     dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E \-Wl\,\-rpath\,/home/chammond/perl/lib/5\.12\.1/x86\_64\-linux\-thread\-multi/CORE'
>     cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-L/usr/local/lib \-fstack\-protector'
> 
> Locally applied patches&#8203;:
>     
> 
> \-\-\-
> @&#8203;INC for perl 5\.12\.1&#8203;:
>     /home/chammond/perl/lib/site\_perl/5\.12\.1/x86\_64\-linux\-thread\-multi
>     /home/chammond/perl/lib/site\_perl/5\.12\.1
>     /home/chammond/perl/lib/5\.12\.1/x86\_64\-linux\-thread\-multi
>     /home/chammond/perl/lib/5\.12\.1
>     \.
> 
> \-\-\-
> Environment for perl 5\.12\.1&#8203;:
>     HOME=/home/chammond
>     LANG \(unset\)
>     LANGUAGE \(unset\)
>     LD\_LIBRARY\_PATH \(unset\)
>     LOGDIR \(unset\)
>     PATH=/home/chammond/perl/bin&#8203;:/bin&#8203;:/usr/sbin&#8203;:/usr/bin&#8203;:/usr/local/bin&#8203;:/usr/local/sbin
>     PERL\_BADLANG \(unset\)
>     SHELL=/bin/bash

\-\- 
Lear&#8203;: Dost thou call me fool\, boy?
Fool&#8203;: All thy other titles thou hast given away; that thou wast born with\.

**Comment by p5pRT** [comment]
### From @doughera88

On Wed\, 25 Aug 2010\, Dave Mitchell wrote&#8203;:

> On Mon\, Aug 23\, 2010 at 02&#8203;:08&#8203;:21AM \-0700\, chrishammond@&#8203;ymail\.com wrote&#8203;:
> > I've got an instance of Perl 5\.12\.1 which has been compiled using the
> > PERL\_USE\_SAFE\_PUTENV flag defined\, and have noted that it segfaults if
> > you try to clear a non\-existent value from the magic %ENV hash if
> > local'ed\.
> > 
> > Using 5\.12\.1 compiled with with&#8203;:
> > config\_args="\-Accflags=\-DPERL\_USE\_SAFE\_PUTENV"
> > 
> > perl \-e "local %ENV;delete $ENV\{q\{UNDEFINED\}\}"
> > or
> > DEFINED=YES perl \-e "local %ENV;delete $ENV\{q\{DEFINED\}\}"
> > 
> > Segmentation fault \(core dumped\)
> > 
> > Process terminating with default action of signal 11 \(SIGSEGV\)&#8203;: dumping core
> > 
> > Invalid read of size 8
> > unsetenv \(setenv\.c&#8203;:295\)
> > by Perl\_magic\_clearenv
> 
> I'm unable to reproduce this\, either on blead\, nor with a 5\.12\.1
> configured as close as possible to the OPs\. Can anyone else do better?

I was able to reproduce it on Debian Linux/x86\. The 'local' is essential 
to producing the crash\.  I don't know why\. I'm hoping that tomorrow I'll 
have a chance to examine it further\.

myuname='linux xxx 2\.6\.26\-2\-686 \#1 smp thu aug 19 03&#8203;:44&#8203;:10 utc 2010 i686 gnulinux '
config\_args='\-des \-Doptimize=\-g \-Accflags=\-DPERL\_USE\_SAFE\_PUTENV'


\(gdb\) run \-e 'local %ENV; delete $ENV\{q\{UNDEFINED\}\};'
Starting program&#8203;: /dev/shm/perl\-5\.12\.1/perl \-e 'local %ENV; delete $ENV\{q\{UNDEFINED\}\};'

Program received signal SIGSEGV\, Segmentation fault\.
0xb75c14bf in unsetenv \(\) from /lib/i686/cmov/libc\.so\.6
\(gdb\) where
\#0  0xb75c14bf in unsetenv \(\) from /lib/i686/cmov/libc\.so\.6
\#1  0x08140f24 in Perl\_my\_setenv \(nam=0x98056e0 "UNDEFINED"\, val=0x0\) at util\.c&#8203;:1728
\#2  0x08150a95 in Perl\_magic\_clearenv \(sv=0x97fb298\, mg=0x9805080\) at mg\.c&#8203;:1194
\#3  0x0814b765 in Perl\_mg\_clear \(sv=0x97fb298\) at mg\.c&#8203;:406
\#4  0x0816639e in S\_hv\_delete\_common \(hv=0x97fb158\, keysv=0x98096f0\, key=0x980b900 "UNDEFINED"\, klen=9\, k\_flags=0\, 
&nbsp;    d\_flags=68\, hash=0\) at hv\.c&#8203;:943
\#5  0x08164e8c in Perl\_hv\_common \(hv=0x97fb158\, keysv=0x98096f0\, key=0x980b900 "UNDEFINED"\, klen=9\, flags=0\, 
&nbsp;    action=68\, val=0x0\, hash=0\) at hv\.c&#8203;:406
\#6  0x0821d390 in Perl\_pp\_delete \(\) at pp\.c&#8203;:4876
\#7  0x0813a010 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2049
\#8  0x0808c48d in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2308
\#9  0x0808b96c in perl\_run \(my\_perl=0x97f8008\) at perl\.c&#8203;:2233
\#10 0x08062c4b in main \(argc=3\, argv=0xbf82ad24\, env=0xbf82ad34\) at perlmain\.c&#8203;:117

\-\- 
&nbsp;    Andy Dougherty        doughera@&#8203;lafayette\.edu

**Comment by p5pRT** [comment]
### From @doy

I can't reproduce this either\. Is this still a problem?

\-doy
