### ISSUE TITLE
[BUG t/lib/English.t 5.005_63] Segfault, probably due to tying.

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#1064]
Migrated from [rt.perl.org#2016](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=2016) (status was 'resolved')

Searchable as RT2016$

**Comment by p5pRT** [comment]
### From @schwern

[English.pm](https://rt-archive.perl.org/perl5/Ticket/Attachment/6969/6825/English.pm)

**Comment by p5pRT** [comment]
### From @gsar

On Fri\, 21 Jan 2000 13&#8203;:06&#8203;:47 EST\, Michael G Schwern wrote&#8203;:
>The segfault occurs on line 26&#8203;:
>
>        print $PREMATCH\, $MATCH\, $POSTMATCH;
>
>$PREMATCH\, $MATCH and $POSTMATCH at this point are all variables tied
>into English&#8203;::Evil so I presume this is a tying problem and the stack
>trace seems to confirm that\.
>
>Here is a stack trace from the point of the segfault\.
>
>\#0  0x400e8c25 in memmove \(\) from /lib/libc\.so\.6
>\#1  0x80c18de in Perl\_sv\_setpvn \(sv=0x813f420\, 
>    ptr=0x5 \<Address 0x5 out of bounds>\, len=5\) at sv\.c&#8203;:2720
&nbsp;         ^^^

It would seem PL\_curpm\->op\_pmregexp\->subbeg is invalid at this point\, but
the code passes it to sv\_setpvn\(\) without checking\.

>\#2  0x80a7d2f in Perl\_magic\_get \(sv=0x813f420\, mg=0x8193308\) at mg\.c&#8203;:547
>\#3  0x80a703b in Perl\_mg\_get \(sv=0x813f420\) at mg\.c&#8203;:96
>\#4  0x80c084c in Perl\_sv\_setsv \(dstr=0x813f42c\, sstr=0x813f420\) at sv\.c&#8203;:2452
>\#5  0x80c598d in Perl\_sv\_mortalcopy \(oldstr=0x813f420\) at sv\.c&#8203;:4216
>\#6  0x80e6e5e in Perl\_pp\_return \(\) at pp\_ctl\.c&#8203;:1819
>\#7  0x80b223d in Perl\_runops\_debug \(\) at run\.c&#8203;:56


Sarathy
gsar@&#8203;ActiveState\.com
