### ISSUE TITLE
Death with stackdump on CORE::GLOBAL::require

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10699]
Migrated from [rt.perl.org#78260](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=78260) (status was 'resolved')

Searchable as RT78260$

**Comment by p5pRT** [comment]
### From @EvanCarroll

This will cause perl to abort with a scary stack dump\.
BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require

\-\- 
Evan Carroll \- me@&#8203;evancarroll\.com
System Lord of the Internets
web&#8203;: http&#8203;://www\.evancarroll\.com
ph&#8203;: 281\.901\.0011

**Comment by p5pRT** [comment]
### From @cpansprout

On Thu Oct 07 00&#8203;:07&#8203;:46 2010\, me@&#8203;evancarroll\.com wrote&#8203;:
> This will cause perl to abort with a scary stack dump\.
> BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require
> 

Thank you for your report\. I cannot reproduce this will any perl version
I have installed\, from 5\.6\.2 to 5\.13\.5\. Could you sent the output of
perl \-V \(with a capital V\)?

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @EvanCarroll

> On Thu Oct 07 00&#8203;:07&#8203;:46 2010\, me@&#8203;evancarroll\.com wrote&#8203;:
>> This will cause perl to abort with a scary stack dump\.
>> BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require

You sure\, it seems to work on every version of perl&#8203;:

$ perl \-e'BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require'

> Thank you for your report\. I cannot reproduce this will any perl version
> I have installed\, from 5\.6\.2 to 5\.13\.5\. Could you sent the output of
> perl \-V \(with a capital V\)?

$ perl \-V
Summary of my perl5 \(revision 5 version 10 subversion 1\) configuration&#8203;:

&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.24\-27\-server\, archname=i486\-linux\-gnu\-thread\-multi
&nbsp;    uname='linux vernadsky 2\.6\.24\-27\-server \#1 smp fri mar 12 01&#8203;:45&#8203;:06
utc 2010 i686 gnulinux '
&nbsp;    config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN
\-Dcccdlflags=\-fPIC \-Darchname=i486\-linux\-gnu \-Dprefix=/usr
\-Dprivlib=/usr/share/perl/5\.10 \-Darchlib=/usr/lib/perl/5\.10
\-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5
\-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local
\-Dsitelib=/usr/local/share/perl/5\.10\.1
\-Dsitearch=/usr/local/lib/perl/5\.10\.1 \-Dman1dir=/usr/share/man/man1
\-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1
\-Dsiteman3dir=/usr/local/man/man3 \-Dman1ext=1 \-Dman3ext=3perl
\-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Ud\_ualarm \-Uusesfio
\-Uusenm \-DDEBUGGING=\-g \-Doptimize=\-O2 \-Duseshrplib
\-Dlibperl=libperl\.so\.5\.10\.1 \-Dd\_dosuid \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN
\-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include
\-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2 \-g'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing
\-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.4\.3'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,
lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib /usr/lib64
&nbsp;    libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    libc=/lib/libc\-2\.11\.1\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.10\.1
&nbsp;    gnulibc\_version='2\.11\.1'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-g \-L/usr/local/lib
\-fstack\-protector'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: MULTIPLICITY PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_IMPLICIT\_CONTEXT PERL\_MALLOC\_WRAP USE\_ITHREADS
&nbsp;                        USE\_LARGE\_FILES USE\_PERLIO USE\_REENTRANT\_API
&nbsp;  Built under linux
&nbsp;  Compiled at Apr 23 2010 07&#8203;:36&#8203;:53
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /etc/perl
&nbsp;    /usr/local/lib/perl/5\.10\.1
&nbsp;    /usr/local/share/perl/5\.10\.1
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/perl/5\.10
&nbsp;    /usr/share/perl/5\.10
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    \.

\-\- 
Evan Carroll \- me@&#8203;evancarroll\.com
System Lord of the Internets
web&#8203;: http&#8203;://www\.evancarroll\.com
ph&#8203;: 281\.901\.0011

**Comment by p5pRT** [comment]
### From @rurban

2010/10/11 Evan Carroll \<me@&#8203;evancarroll\.com>&#8203;:
>> On Thu Oct 07 00&#8203;:07&#8203;:46 2010\, me@&#8203;evancarroll\.com wrote&#8203;:
>>> This will cause perl to abort with a scary stack dump\.
>>> BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require
>
> You sure\, it seems to work on every version of perl&#8203;:
>
> $ perl \-e'BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require'
>
>> Thank you for your report\. I cannot reproduce this will any perl version
>> I have installed\, from 5\.6\.2 to 5\.13\.5\. Could you sent the output of
>> perl \-V \(with a capital V\)?

I can reproduce it with most of my perls on cygwin\, just 5\.6\.2
\(DEBUGGING and no threads\) works ok\.

$ perl5\.6\.2d\-nt \-e "BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require"

$ perl5\.8\.9d\-nt \-e "BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require"
assertion botched \(chunk's tail overwrite?\)&#8203;: \(\(unsigned int
\*\)\(\(caddr\_t\)ovp \+ nbytes\)\)\[\-1\] == 0x55555555 \(malloc\.c&#8203;:2079\)
Aborted \(core dumped\)

$ perl5\.10\.1 \-e "BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require"
Segmentation fault \(core dumped\)

$ perl5\.10\.1d\-nt \-e "BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require"
Segmentation fault \(core dumped\)

$ perl5\.12\.0 \-e "BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require"
Segmentation fault \(core dumped\)

$ perl5\.13\.5d \-e "BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require"
Segmentation fault \(core dumped\)

$ perl5\.13\.5d\-nt \-e "BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require"
Segmentation fault \(core dumped\)

\(gdb\) bt
\#0  0x6b237c55 in Perl\_append\_elem \(\) from /usr/local/bin/cygperl5\_10\_1d\-nt\.dll
\#1  0x6b24c068 in Perl\_ck\_require \(\) from /usr/local/bin/cygperl5\_10\_1d\-nt\.dll
\#2  0x6b238979 in Perl\_newOP \(\) from /usr/local/bin/cygperl5\_10\_1d\-nt\.dll
\#3  0x6b2c1d29 in Perl\_yyparse \(\) from /usr/local/bin/cygperl5\_10\_1d\-nt\.dll
\#4  0x6b2569b5 in S\_parse\_body \(\) from /usr/local/bin/cygperl5\_10\_1d\-nt\.dll
\#5  0x6b254f9d in perl\_parse \(\) from /usr/local/bin/cygperl5\_10\_1d\-nt\.dll
\#6  0x540011e6 in \_fu3\_\_PL\_exit\_flags \(\)
\#7  0x0130a160 in ?? \(\)
\#8  0x54001229 in \_fu3\_\_PL\_exit\_flags \(\)
\#9  0x00000003 in ?? \(\)
\#10 0x01309f40 in ?? \(\)
\#11 0x00000000 in ?? \(\)

No more symbols on this machine of mine\, sorry\.
\-\- 
Reini Urban

**Comment by p5pRT** [comment]
### From @cpansprout

On Tue Oct 12 07&#8203;:43&#8203;:05 2010\, rurban wrote&#8203;:
> 2010/10/11 Evan Carroll \<me@&#8203;evancarroll\.com>&#8203;:
> >> On Thu Oct 07 00&#8203;:07&#8203;:46 2010\, me@&#8203;evancarroll\.com wrote&#8203;:
> >>> This will cause perl to abort with a scary stack dump\.
> >>> BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require
> >
> > You sure\, it seems to work on every version of perl&#8203;:
> >
> > $ perl \-e'BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require'
> >
> >> Thank you for your report\. I cannot reproduce this will any perl
> version
> >> I have installed\, from 5\.6\.2 to 5\.13\.5\. Could you sent the output
> of
> >> perl \-V \(with a capital V\)?
> 
> I can reproduce it with most of my perls on cygwin\, just 5\.6\.2
> \(DEBUGGING and no threads\) works ok\.
> 
> $ perl5\.6\.2d\-nt \-e "BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require"
> 
> $ perl5\.8\.9d\-nt \-e "BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require"
> assertion botched \(chunk's tail overwrite?\)&#8203;: \(\(unsigned int
> \*\)\(\(caddr\_t\)ovp \+ nbytes\)\)\[\-1\] == 0x55555555 \(malloc\.c&#8203;:2079\)
> Aborted \(core dumped\)

That makes me wonder whether this is related to \#104034\.  Evan Carrol is
not using perl’s malloc\, so it might be some memory corruption somewhere
that is very hard to trigger\, but pops up here and there\.  It’s still
nearly impossible to debug\, though\.

> 
> $ perl5\.10\.1 \-e "BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require"
> Segmentation fault \(core dumped\)
> 
> $ perl5\.10\.1d\-nt \-e "BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \};
> require"
> Segmentation fault \(core dumped\)
> 
> $ perl5\.12\.0 \-e "BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require"
> Segmentation fault \(core dumped\)
> 
> $ perl5\.13\.5d \-e "BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \}; require"
> Segmentation fault \(core dumped\)
> 
> $ perl5\.13\.5d\-nt \-e "BEGIN\{ \*CORE&#8203;::GLOBAL&#8203;::require = sub \{\} \};
> require"
> Segmentation fault \(core dumped\)
> 
> \(gdb\) bt
> \#0  0x6b237c55 in Perl\_append\_elem \(\) from
> /usr/local/bin/cygperl5\_10\_1d\-nt\.dll
> \#1  0x6b24c068 in Perl\_ck\_require \(\) from
> /usr/local/bin/cygperl5\_10\_1d\-nt\.dll
> \#2  0x6b238979 in Perl\_newOP \(\) from /usr/local/bin/cygperl5\_10\_1d\-
> nt\.dll
> \#3  0x6b2c1d29 in Perl\_yyparse \(\) from /usr/local/bin/cygperl5\_10\_1d\-
> nt\.dll
> \#4  0x6b2569b5 in S\_parse\_body \(\) from /usr/local/bin/cygperl5\_10\_1d\-
> nt\.dll
> \#5  0x6b254f9d in perl\_parse \(\) from /usr/local/bin/cygperl5\_10\_1d\-
> nt\.dll
> \#6  0x540011e6 in \_fu3\_\_PL\_exit\_flags \(\)
> \#7  0x0130a160 in ?? \(\)
> \#8  0x54001229 in \_fu3\_\_PL\_exit\_flags \(\)
> \#9  0x00000003 in ?? \(\)
> \#10 0x01309f40 in ?? \(\)
> \#11 0x00000000 in ?? \(\)
> 
> No more symbols on this machine of mine\, sorry\.


\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From perl@profvince.com

> That makes me wonder whether this is related to \#104034\.  Evan Carrol is
> not using perl’s malloc\, so it might be some memory corruption somewhere
> that is very hard to trigger\, but pops up here and there\.  It’s still
> nearly impossible to debug\, though\.

I could reproduce the issue and am working on fixing it\.


Vincent\.

**Comment by p5pRT** [comment]
### From perl@profvince.com

On 20/11/2011 11&#8203;:34\, Vincent Pit wrote&#8203;:
>> That makes me wonder whether this is related to \#104034\.  Evan Carrol is
>> not using perl’s malloc\, so it might be some memory corruption somewhere
>> that is very hard to trigger\, but pops up here and there\.  It’s still
>> nearly impossible to debug\, though\.
>
> I could reproduce the issue and am working on fixing it\.
>
>
> Vincent\.
>

This is now fixed in blead by commit 7c864bb3\. Thank you for reporting 
this issue\.


Vincent\.

**Comment by p5pRT** [comment]
bitcard@profvince.com - Status changed from 'open' to 'resolved'
