### ISSUE TITLE
Pl_op getting corrupt value

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10807]
Migrated from [rt.perl.org#78932](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=78932) (status was 'resolved')

Searchable as RT78932$

**Comment by p5pRT** [comment]
### From cburel@rhythm.com

This is a bug report for perl fromcburel@&#8203;rhythm\.com
generated with the help of perlbug 1\.39 running under perl 5\.13\.6\.


\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
Hi\,
I'm the developer of the Perl Qt4 language bindings\, and I've run into some strange behavior in my testing\.  It manifests itself in the form of either A\) A subroutine ending before all the statements in that subroutine have been executed\, B\) Perl die'ing with the error "panic&#8203;: memory wrap" or B\) Perl segfaulting in Perl\_runops\_debug\(\) at line 2120 in dump\.c of perl 5\.13\.6\.  This line reads&#8203;:
while \(\(PL\_op = PL\_op\->op\_ppaddr\(aTHX\)\)\)

The code in the bindings is making a call to Perl using the C API\.  It happens durring a call to call\_sv\, and the context is&#8203;:
&nbsp;     dSP;
&nbsp;     ENTER;
&nbsp;     SAVETMPS;
&nbsp;     PUSHMARK\(SP\);
&nbsp;     EXTEND\(SP\, \_items\);
&nbsp;     for\(int i=0;i\<\_items;\+\+i\)\{
&nbsp;         PUSHs\(\(newSVsv\(\_sp\[i\]\)\)\);
&nbsp;     \}
&nbsp;     PUTBACK;
&nbsp;     int count = call\_sv\(\(SV\*\)GvCV\(gv\)\, G\_SCALAR\);

In debugging\, I've stepped into the call\_sv function\, and watched as the new myop variable gets created\, and myop\.op\_next is set to NULL\, and the current value of PL\_op is saved and then set to myop\.  All is good so far\.  But then throughout the course of the runops loop that follows\, I've been able to see that at some point the value of myop\.op\_next is changed to something like 0xffffff\, which shouldn't happen\.  So then when perl tries to call the function at 0xffffff\, it segfaults\.

I know the binding's code could be responsible for this\, but it isn't manipulating the op sequence at all\.  So I really doubt that's the problem\.

I also know that bug reports without reproducible test cases are really hard to tackle\, but unfortunately this isn't code that I can post\.  I'll try and get something reproducible\.

Some relavent info from gdb&#8203;:
\(gdb\) bt 5
\#0  0x00000000081d7c70 in ?? \(\)
\#1  0x00002aaaaad9bc50 in Perl\_runops\_debug \(my\_perl=0x603010\) at dump\.c&#8203;:2120
\#2  0x00002aaaaad24c95 in Perl\_call\_sv \(my\_perl=0x603010\, sv=0x567f940\, flags=2\) at perl\.c&#8203;:2596
\#3  0x00002aaaac9ead25 in PerlQt4&#8203;::InvokeSlot&#8203;::callMethod \(this=0x7fffffff7660\) at /pts/testPipe/share/Qt4/def/dat/kdebindings/perl/qtcore/src/marshall\_types\.cpp&#8203;:719
\#4  0x00002aaaac9eb0c6 in PerlQt4&#8203;::InvokeSlot&#8203;::next \(this=0x7fffffff7660\) at /pts/testPipe/share/Qt4/def/dat/kdebindings/perl/qtcore/src/marshall\_types\.cpp&#8203;:734
\(More stack frames follow\.\.\.\)

\(gdb\) p my\_perl\->Iop
$12 = \(OP \*\) 0x8362980

\(gdb\) p \*my\_perl\->Iop
$13 = \{op\_next = 0x79a2cf8\, op\_sibling = 0x2000000c00000001\, op\_ppaddr = 0x8368328\, op\_targ = 137775496\, op\_type = 1\, op\_opt = 0\, op\_latefree = 0\, op\_latefreed = 0\, op\_attached = 0\, op\_spare = 0\, op\_flags = 0 '\\0'\,
&nbsp;   op\_private = 0 '\\0'\}

\(gdb\) up 0
\#1  0x00002aaaaad9bc50 in Perl\_runops\_debug \(my\_perl=0x603010\) at dump\.c&#8203;:2120
2120        \} while \(\(PL\_op = PL\_op\->op\_ppaddr\(aTHX\)\)\);

\(gdb\) p Perl\_op\_dump\( my\_perl\,&my\_perl\->Iperlio\[3\]\, my\_perl\->Iop \)
\{
1   TYPE = leavegiven  ===>  2
&nbsp;     FLAGS = \(UNKNOWN\,KIDS\,PARENS\,ATTACHED\)
\}
$14 = void

<details><summary>Perl Info</summary>

```

Flags:
     category=core
     severity=medium

Site configuration information for perl 5.13.6:

Configured by cburel at Sun Nov  7 17:03:26 PST 2010.

Summary of my perl5 (revision 5 version 13 subversion 6) configuration:

   Platform:
     osname=linux, osvers=2.6.27.23-6rh, archname=linux-linux-thread-multi
     uname='linux lid612 2.6.27.23-6rh #1 smp thu feb 4 16:28:02 pst 2010 x86_64 x86_64 x86_64 gnulinux '
     config_args='-ds -e -ds -e -Dprefix=//fs/is09n6/ifs/rla/testPipe/share/Qt4/def/dat/perl13 -Dvendorprefix=/fs/is09n6/ifs/rla/testPipe/share/Qt4/def/dat/perl13/ -Dusethreads -Di_db -Di_dbm -Di_ndbm -Di_gdbm -Duseshrplib=true -Doptimize=-fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -Wall -pipe -Accflags=-DPERL_USE_SAFE_PUTENV -Dusedevel'
     hint=recommended, useposix=true, d_sigaction=define
     useithreads=define, usemultiplicity=define
     useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
     use64bitint=define, use64bitall=define, uselongdouble=undef
     usemymalloc=n, bincompat5005=undef
   Compiler:
     cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DPERL_USE_SAFE_PUTENV -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
     optimize='-fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -Wall -pipe',
     cppflags='-D_REENTRANT -D_GNU_SOURCE -DPERL_USE_SAFE_PUTENV -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
     ccversion='', gccversion='4.3.2 [gcc-4_3-branch revision 141291]', gccosandvers=''
     intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
     d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
     ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
     alignbytes=8, prototype=define
   Linker and Libraries:
     ld='cc', ldflags =' -fstack-protector -L/usr/local/lib'
     libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64 /usr/local/lib64
     libs=-lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lpthread -lc -lgdbm_compat
     perllibs=-lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
     libc=/lib/libc-2.9.so, so=so, useshrplib=true, libperl=libperl.so
     gnulibc_version='2.9'
   Dynamic Linking:
     dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E -Wl,-rpath,//fs/is09n6/ifs/rla/testPipe/share/Qt4/def/dat/perl13/lib/5.13.6/linux-linux-thread-multi/CORE'
     cccdlflags='-fPIC', lddlflags='-shared -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -Wall -pipe -L/usr/local/lib'

Locally applied patches:



@INC for perl 5.13.6:
     //fs/is09n6/ifs/rla/testPipe/share/Qt4/def/dat/perl13/lib/site_perl/5.13.6/linux-linux-thread-multi
     //fs/is09n6/ifs/rla/testPipe/share/Qt4/def/dat/perl13/lib/site_perl/5.13.6
     /fs/is09n6/ifs/rla/testPipe/share/Qt4/def/dat/perl13//lib/vendor_perl/5.13.6/linux-linux-thread-multi
     /fs/is09n6/ifs/rla/testPipe/share/Qt4/def/dat/perl13//lib/vendor_perl/5.13.6
     //fs/is09n6/ifs/rla/testPipe/share/Qt4/def/dat/perl13/lib/5.13.6/linux-linux-thread-multi
     //fs/is09n6/ifs/rla/testPipe/share/Qt4/def/dat/perl13/lib/5.13.6
     .


Environment for perl 5.13.6:
     HOME=/home/cburel
     LANG=en_US.UTF-8
     LANGUAGE=
     LD_LIBRARY_PATH=/usr/lib64/mpi/gcc/openmpi/lib64
     LOGDIR (unset)
     PATH=/home/cburel/bin:/local/a/kde-4.5.1/bin:/local/a/qt-4.6.3/qt/bin:/home/cburel/bin:/muse/bin:/usr/apps/bin:/usr/local/prod/bin:/usr/local/rnh/bin:/usr/site/bin:/usr/local/bin:/opt/kde3/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/lsd/bin:/opt/gnome/bin:/usr/games:.:/usr/X11R6/bin
     PERL_BADLANG (unset)
     SHELL=/usr/lsd/bin/tcsh


```
</details>

**Comment by p5pRT** [comment]
### From cburel@rhythm.com

Turns out this was the result of an unbalanced stack\.  I had more ENTERs 
than LEAVEs\, and that's what was causing the problem\.

Can someone cancel this?

**Comment by p5pRT** [comment]
### From @tonycoz

Closed at requestor's request\.

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'new' to 'resolved'
