### ISSUE TITLE
5.14.0-RC2 op/threads.t failures

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#11309]
Migrated from [rt.perl.org#90006](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=90006) (status was 'resolved')

Searchable as RT90006$

**Comment by p5pRT** [comment]
### From alex.hartmaier@gmail.com

I've compiled my perl with the following options \(full perl \-V output
below\)&#8203;:
\-Dusethreads \-Duselargefiles \-Dcccdlflags= \-Dlddlflags\+=\-fPIC \-Duseshrplib
\-Dlibperl=libperl\.so \-Dusemymalloc

The failing test output is&#8203;:

\[ahartmai@&#8203;ahartmai\-nb perl\-5\.14\.0\-RC2\]$
LD\_LIBRARY\_PATH=/home/ahartmai/perl5/perlbrew/build/perl\-5\.14\.0\-RC2; prove
\-e\./perl \-vl t/op/threads\.t
t/op/threads\.t \.\.
1\.\.24
ok 1 \- delete\(\) under threads
ok 2 \- weaken ref under threads
ok 3 \- weaken ref \\\#2 under threads
\# parent 17409&#8203;: continue
\# kid 1 before sort
\# parent 17409&#8203;: continue
\# parent 17409&#8203;: waiting for join
\# kid 2 before sort
\# kid 2 after sort\, sleeping 1
\# kid 1 after sort\, sleeping 1
\# kid 2 exit
\# kid 1 exit
\# parent 17409&#8203;: thread exited
\# parent 17409&#8203;: waiting for join
\# parent 17409&#8203;: thread exited
ok 4
ok 5 \- cloning constant subs
ok 6 \- Ensure PL\_linestr can be cloned
ok 7 \- threads in CHECK block
ok 8 \- threads in INIT block
ok 9 \- Bug \\\#41138
Failed 15/24 subtests

Test Summary Report


---
t/op/threads\.t \(Wstat&#8203;: 11 Tests&#8203;: 9 Failed&#8203;: 0\)
&nbsp;  Non\-zero wait status&#8203;: 11
&nbsp;  Parse errors&#8203;: Bad plan\.  You planned 24 tests but ran 9\.
Files=1\, Tests=9\,  3 wallclock secs \( 0\.04 usr  0\.00 sys \+  3\.04 cusr  0\.20
csys =  3\.28 CPU\)
Result&#8203;: FAIL



\[ahartmai@&#8203;ahartmai\-nb perl\-5\.14\.0\-RC2\]$ \./perl \-Ilib \-V
Summary of my perl5 \(revision 5 version 14 subversion 0\) configuration&#8203;:

&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.38\-8\-generic\,
archname=x86\_64\-linux\-thread\-multi
&nbsp;    uname='linux ahartmai\-nb 2\.6\.38\-8\-generic \#42\-ubuntu smp mon apr 11
03&#8203;:31&#8203;:24 utc 2011 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;    config\_args='\-de
\-Dprefix=/home/ahartmai/perl5/perlbrew/perls/perl\-5\.14\.0\-RC2 \-Dusethreads
\-Duselargefiles \-Dcccdlflags= \-Dlddlflags\+=\-fPIC \-Duseshrplib
\-Dlibperl=libperl\.so \-Dusemymalloc'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=y\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-pipe
\-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE
\-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-pipe
\-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.5\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,
lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib /usr/lib/x86\_64\-linux\-gnu /lib64
/usr/lib64
&nbsp;    libs=\-lnsl \-ldb \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    libc=\, so=so\, useshrplib=true\, libperl=libperl\.so
&nbsp;    gnulibc\_version='2\.13'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E
\-Wl\,\-rpath\,/home/ahartmai/perl5/perlbrew/perls/perl\-5\.14\.0\-RC2/lib/5\.14\.0/x86\_64\-linux\-thread\-multi/CORE'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-L/usr/local/lib
\-fstack\-protector'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: MULTIPLICITY MYMALLOC PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_IMPLICIT\_CONTEXT PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV USE\_64\_BIT\_ALL USE\_64\_BIT\_INT
&nbsp;                        USE\_ITHREADS USE\_LARGE\_FILES USE\_PERLIO
USE\_PERL\_ATOF
&nbsp;                        USE\_REENTRANT\_API
&nbsp;  Locally applied patches&#8203;:
&nbsp;    RC2
&nbsp;  Built under linux
&nbsp;  Compiled at May  6 2011 14&#8203;:28&#8203;:09
&nbsp;  %ENV&#8203;:

PERLBREW\_PATH="/home/ahartmai/perl5/perlbrew/bin&#8203;:/home/ahartmai/perl5/perlbrew/perls/current/bin"
&nbsp;    PERLBREW\_PERL="perl\-5\.12\.3"
&nbsp;    PERLBREW\_ROOT="/home/ahartmai/perl5/perlbrew"
&nbsp;    PERLBREW\_VERSION="0\.19"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib

/home/ahartmai/perl5/perlbrew/perls/perl\-5\.14\.0\-RC2/lib/site\_perl/5\.14\.0/x86\_64\-linux\-thread\-multi
&nbsp;    /home/ahartmai/perl5/perlbrew/perls/perl\-5\.14\.0\-RC2/lib/site\_perl/5\.14\.0

/home/ahartmai/perl5/perlbrew/perls/perl\-5\.14\.0\-RC2/lib/5\.14\.0/x86\_64\-linux\-thread\-multi
&nbsp;    /home/ahartmai/perl5/perlbrew/perls/perl\-5\.14\.0\-RC2/lib/5\.14\.0
&nbsp;    \.

Best regards\, Alex \(abraxxa\)

**Comment by p5pRT** [comment]
### From @obra


Reproduced locally with Ubuntu natty x86\_64 and

\./Configure \-des \-Dusethreads \-Duselargefiles \-Dcccdlflags=
\-Dlddlflags\+=\-fPIC \-Duseshrplib \-Dlibperl=libperl\.so \-Dusemymalloc


t/op/threads\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.perl&#8203;:
malloc\.c&#8203;:3096&#8203;: sYSMALLOc&#8203;: Assertion \`\(old\_top == \(\(\(mbinptr\) \(\(\(char \*\)
&\(\(av\)\->bins\[\(\(1\) \- 1\) \* 2\]\)\) \- \_\_builtin\_offsetof \(struct malloc\_chunk\,
fd\)\)\)\) && old\_size == 0\) || \(\(unsigned long\) \(old\_size\) >= \(unsigned
long\)\(\(\(\(\_\_builtin\_offsetof \(struct malloc\_chunk\, fd\_nextsize\)\)\+\(\(2 \*
\(sizeof\(size\_t\)\)\) \- 1\)\) & ~\(\(2 \* \(sizeof\(size\_t\)\)\) \- 1\)\)\) &&
\(\(old\_top\)\->size & 0x1\) && \(\(unsigned long\)old\_end & pagemask\) == 0\)'
failed\.


On Fri  6\.May'11 at  6&#8203;:03&#8203;:41 \-0700\, Alexander Hartmaier wrote&#8203;:
> \# New Ticket Created by  Alexander Hartmaier 
> \# Please include the string&#8203;:  \[perl \#90006\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: http&#8203;://rt\.perl\.org/rt3/Ticket/Display\.html?id=90006 >
> 
> 
> I've compiled my perl with the following options \(full perl \-V output
> below\)&#8203;:
> \-Dusethreads \-Duselargefiles \-Dcccdlflags= \-Dlddlflags\+=\-fPIC \-Duseshrplib
> \-Dlibperl=libperl\.so \-Dusemymalloc
> 
> The failing test output is&#8203;:
> 
> \[ahartmai@&#8203;ahartmai\-nb perl\-5\.14\.0\-RC2\]$
> LD\_LIBRARY\_PATH=/home/ahartmai/perl5/perlbrew/build/perl\-5\.14\.0\-RC2; prove
> \-e\./perl \-vl t/op/threads\.t
> t/op/threads\.t \.\.
> 1\.\.24
> ok 1 \- delete\(\) under threads
> ok 2 \- weaken ref under threads
> ok 3 \- weaken ref \\\#2 under threads
> \# parent 17409&#8203;: continue
> \# kid 1 before sort
> \# parent 17409&#8203;: continue
> \# parent 17409&#8203;: waiting for join
> \# kid 2 before sort
> \# kid 2 after sort\, sleeping 1
> \# kid 1 after sort\, sleeping 1
> \# kid 2 exit
> \# kid 1 exit
> \# parent 17409&#8203;: thread exited
> \# parent 17409&#8203;: waiting for join
> \# parent 17409&#8203;: thread exited
> ok 4
> ok 5 \- cloning constant subs
> ok 6 \- Ensure PL\_linestr can be cloned
> ok 7 \- threads in CHECK block
> ok 8 \- threads in INIT block
> ok 9 \- Bug \\\#41138
> Failed 15/24 subtests
> 
> Test Summary Report
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> t/op/threads\.t \(Wstat&#8203;: 11 Tests&#8203;: 9 Failed&#8203;: 0\)
>   Non\-zero wait status&#8203;: 11
>   Parse errors&#8203;: Bad plan\.  You planned 24 tests but ran 9\.
> Files=1\, Tests=9\,  3 wallclock secs \( 0\.04 usr  0\.00 sys \+  3\.04 cusr  0\.20
> csys =  3\.28 CPU\)
> Result&#8203;: FAIL
> 
> 
> 
> \[ahartmai@&#8203;ahartmai\-nb perl\-5\.14\.0\-RC2\]$ \./perl \-Ilib \-V
> Summary of my perl5 \(revision 5 version 14 subversion 0\) configuration&#8203;:
> 
>   Platform&#8203;:
>     osname=linux\, osvers=2\.6\.38\-8\-generic\,
> archname=x86\_64\-linux\-thread\-multi
>     uname='linux ahartmai\-nb 2\.6\.38\-8\-generic \#42\-ubuntu smp mon apr 11
> 03&#8203;:31&#8203;:24 utc 2011 x86\_64 x86\_64 x86\_64 gnulinux '
>     config\_args='\-de
> \-Dprefix=/home/ahartmai/perl5/perlbrew/perls/perl\-5\.14\.0\-RC2 \-Dusethreads
> \-Duselargefiles \-Dcccdlflags= \-Dlddlflags\+=\-fPIC \-Duseshrplib
> \-Dlibperl=libperl\.so \-Dusemymalloc'
>     hint=recommended\, useposix=true\, d\_sigaction=define
>     useithreads=define\, usemultiplicity=define
>     useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
>     use64bitint=define\, use64bitall=define\, uselongdouble=undef
>     usemymalloc=y\, bincompat5005=undef
>   Compiler&#8203;:
>     cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-pipe
> \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE
> \-D\_FILE\_OFFSET\_BITS=64'\,
>     optimize='\-O2'\,
>     cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-pipe
> \-fstack\-protector \-I/usr/local/include'
>     ccversion=''\, gccversion='4\.5\.2'\, gccosandvers=''
>     intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
>     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
>     ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,
> lseeksize=8
>     alignbytes=8\, prototype=define
>   Linker and Libraries&#8203;:
>     ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
>     libpth=/usr/local/lib /lib /usr/lib /usr/lib/x86\_64\-linux\-gnu /lib64
> /usr/lib64
>     libs=\-lnsl \-ldb \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
>     perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
>     libc=\, so=so\, useshrplib=true\, libperl=libperl\.so
>     gnulibc\_version='2\.13'
>   Dynamic Linking&#8203;:
>     dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E
> \-Wl\,\-rpath\,/home/ahartmai/perl5/perlbrew/perls/perl\-5\.14\.0\-RC2/lib/5\.14\.0/x86\_64\-linux\-thread\-multi/CORE'
>     cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-L/usr/local/lib
> \-fstack\-protector'
> 
> 
> Characteristics of this binary \(from libperl\)&#8203;:
>   Compile\-time options&#8203;: MULTIPLICITY MYMALLOC PERL\_DONT\_CREATE\_GVSV
>                         PERL\_IMPLICIT\_CONTEXT PERL\_MALLOC\_WRAP
>                         PERL\_PRESERVE\_IVUV USE\_64\_BIT\_ALL USE\_64\_BIT\_INT
>                         USE\_ITHREADS USE\_LARGE\_FILES USE\_PERLIO
> USE\_PERL\_ATOF
>                         USE\_REENTRANT\_API
>   Locally applied patches&#8203;:
>     RC2
>   Built under linux
>   Compiled at May  6 2011 14&#8203;:28&#8203;:09
>   %ENV&#8203;:
> 
> PERLBREW\_PATH="/home/ahartmai/perl5/perlbrew/bin&#8203;:/home/ahartmai/perl5/perlbrew/perls/current/bin"
>     PERLBREW\_PERL="perl\-5\.12\.3"
>     PERLBREW\_ROOT="/home/ahartmai/perl5/perlbrew"
>     PERLBREW\_VERSION="0\.19"
>   @&#8203;INC&#8203;:
>     lib
> 
> /home/ahartmai/perl5/perlbrew/perls/perl\-5\.14\.0\-RC2/lib/site\_perl/5\.14\.0/x86\_64\-linux\-thread\-multi
>     /home/ahartmai/perl5/perlbrew/perls/perl\-5\.14\.0\-RC2/lib/site\_perl/5\.14\.0
> 
> /home/ahartmai/perl5/perlbrew/perls/perl\-5\.14\.0\-RC2/lib/5\.14\.0/x86\_64\-linux\-thread\-multi
>     /home/ahartmai/perl5/perlbrew/perls/perl\-5\.14\.0\-RC2/lib/5\.14\.0
>     \.
> 
> Best regards\, Alex \(abraxxa\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @obra


\./Configure \-des \-Dusethreads \-Dusemymalloc
make
cd t; LD\_LIBRARY\_PATH=\.\. \.\./perl \-I\.\./lib op/threads\.t


is enough to trigger the segfault\. on both 5\.14\.0\-RC2 and maint\-5\.12 on
Ubuntu natty\.

As far as I can tell\, this is \_not\_ a regression\. That means that it's
release critical\.

**Comment by p5pRT** [comment]
### From @tonycoz

Backtrace when built with \-DEBUGGING \-Duseithreads \-Dusemymalloc&#8203;:

rogram received signal SIGSEGV\, Segmentation fault\.
Perl\_padlist\_dup \(my\_perl=0x7ffff00b88a0\, srcpad=\<value optimised out>\, 
&nbsp;    param=0x7fffffffde70\) at pad\.c&#8203;:1956
1956                const char sigil = SvPVX\_const\(names\[ix\]\)\[0\];
\(gdb\) bt
\#0  Perl\_padlist\_dup \(my\_perl=0x7ffff00b88a0\, srcpad=\<value optimised out>\, 
&nbsp;    param=0x7fffffffde70\) at pad\.c&#8203;:1956
\#1  0x000000000050efbf in S\_sv\_dup\_common \(my\_perl=0x7ffff00b88a0\, 
&nbsp;    sstr=0x96a820\, param=0x7fffffffde70\) at sv\.c&#8203;:12114
\#2  0x000000000050ffde in Perl\_sv\_dup \(my\_perl=0x7ffff00b88a0\, 
&nbsp;    sstr=\<value optimised out>\, param=0x7fffffffde70\) at sv\.c&#8203;:12140
\#3  0x00000000005110e7 in Perl\_mg\_dup \(my\_perl=0x7ffff00b88a0\, mg=0x9684c8\, 
&nbsp;    param=0x7fffffffde70\) at sv\.c&#8203;:11483
\#4  0x000000000050f60a in S\_sv\_dup\_common \(my\_perl=0x7ffff00b88a0\, 
&nbsp;    sstr=0x96ad90\, param=0x7fffffffde70\) at sv\.c&#8203;:11899
\#5  0x0000000000510070 in Perl\_sv\_dup\_inc \(my\_perl=\<value optimised out>\, 
&nbsp;    sstr=\<value optimised out>\, param=\<value optimised out>\) at sv\.c&#8203;:12134
\#6  0x00000000004df3a9 in Perl\_he\_dup \(my\_perl=0x7ffff00b88a0\, e=0x95e290\, 
&nbsp;    shared=\<value optimised out>\, param=0x7fffffffde70\) at hv\.c&#8203;:187
\#7  0x000000000050f157 in S\_sv\_dup\_common \(my\_perl=0x7ffff00b88a0\, 
&nbsp;    sstr=0x914958\, param=0x7fffffffde70\) at sv\.c&#8203;:12017
\#8  0x000000000050ffde in Perl\_sv\_dup \(my\_perl=0x7ffff00b88a0\, 
&nbsp;    sstr=\<value optimised out>\, param=0x7fffffffde70\) at sv\.c&#8203;:12140
\#9  0x000000000050fa47 in S\_sv\_dup\_common \(my\_perl=0x7ffff00b88a0\, 
&nbsp;    sstr=0x93f830\, param=0x7fffffffde70\) at sv\.c&#8203;:11936
\#10 0x000000000050ffde in Perl\_sv\_dup \(my\_perl=0x7ffff00b88a0\, 
&nbsp;    sstr=\<value optimised out>\, param=0x7fffffffde70\) at sv\.c&#8203;:12140
\-\-\-Type \<return> to continue\, or q \<return> to quit\-\-\-
\#11 0x000000000051cda4 in perl\_clone \(proto\_perl=0x8f0010\, flags=2\)
&nbsp;    at sv\.c&#8203;:12933
\#12 0x00007ffff689d51d in S\_ithread\_create \(my\_perl=0x8f0010\, 
&nbsp;    cv=\<value optimised out>\) at threads\.xs&#8203;:776
\#13 XS\_threads\_create \(my\_perl=0x8f0010\, cv=\<value optimised out>\)
&nbsp;    at threads\.xs&#8203;:1087
\#14 0x00000000004f7df1 in Perl\_pp\_entersub \(my\_perl=0x8f0010\) at
pp\_hot\.c&#8203;:3046
\#15 0x00000000004b9d1d in Perl\_runops\_debug \(my\_perl=0x8f0010\) at
dump\.c&#8203;:2267
\#16 0x0000000000441da3 in S\_run\_body \(my\_perl=0x8f0010\) at perl\.c&#8203;:2350
\#17 perl\_run \(my\_perl=0x8f0010\) at perl\.c&#8203;:2268
\#18 0x000000000041a17c in main \(argc=3\, argv=0x7fffffffe2a8\, 
&nbsp;    env=0x7fffffffe2c8\) at perlmain\.c&#8203;:120
\(gdb\)

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, May 07\, 2011 at 04&#8203;:18&#8203;:03PM \-0400\, Jesse Vincent wrote&#8203;:
> 
> \./Configure \-des \-Dusethreads \-Dusemymalloc
> make
> cd t; LD\_LIBRARY\_PATH=\.\. \.\./perl \-I\.\./lib op/threads\.t
> 
> 
> is enough to trigger the segfault\. on both 5\.14\.0\-RC2 and maint\-5\.12 on
> Ubuntu natty\.
> 
> As far as I can tell\, this is \_not\_ a regression\. That means that it's
> release critical\. 

Now fixed by the commits

&nbsp;    692fcd37585c5b7f1e0e1a30148e0451f2f963eb
&nbsp;    50f626ad600f0bdc3dd1e79057149c3dca9e2f45
&nbsp;    f144f1e3c6a65ce611177737a21b1166f07ef373

It's basically various issues relating to running out of memory while
cloning a new thread\. The perl malloc expects a certain environment to be
present and correct\, and that may not be the case is the malloc occurs
during the early stages of the clone\.

The commits above fix the specific issues\, although I suspect there's a
can of worms waiting to be opened there\, should one dig deeper\. Indeed\,
at one point I noticed that malloc's attempt to output an "Out of
memory\!" warning to STDERR using PerlIO was triggering a recursive call to
malloc\(\) from the bowels of PerlIO\, and eventually blowing the stack\. But
I think that sort sort of issue is for another day\. The specific
threads/clone\-related issue reported has been fixed\.

\-\- 
print\+qq&$\}$"$/$s$\,$a$d$g$s$@&#8203;$\.$q$\,$&#8203;:$\.$q$^$\,$@&#8203;$a$~$;$\.$q$m&if\+map\{m\,^\\d\{0\\\,\}\,\,$\{$&#8203;::\{$'\}\}=chr\($"\+=$&||1\)\}q&10m22\,42\}6&#8203;:17a2~2\.3@&#8203;3;^2dg3q/s"&=~m\*\\d\\\*\.\*g

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
