### ISSUE TITLE
t/op/threads failure / crash on Debian GNU/kFreeBSD

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#11553]
Migrated from [rt.perl.org#96272](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=96272) (status was 'resolved')

Searchable as RT96272$

**Comment by p5pRT** [comment]
### From @ntyni


This is a bug report for perl from Niko Tyni \<ntyni@&#8203;debian\.org>\,
generated with the help of perlbug 1\.39 running under perl 5\.15\.1\.




---
We're seeing a non\-deterministic failure of test 25 \(the last one\)
of t/op/threads\.t on multiprocessor Debian GNU/kFreeBSD systems\.

The failure can be reduced to this&#8203;:

 \./perl \-Ilib \-Mthreads \-e 'threads\->create\(sub \{\}\)\->detach; fork'

which crashes here in a KVM virtual machine about 10% of the time\.

The test triggering the crash was added during the 5\.13 series in commit
2e0cfa16dea85dd33 fixing \[perl \#78494\]\, but I can reproduce the crash
on 5\.12\.4 too\.

It seems possible that the bug is in libc / kernel land\, but FWIW I
haven't been able to trigger it on a FreeBSD 8\.2\-RELEASE system\. I've
notified the Debian kFreeBSD porters\, and will update this ticket if I
get more information\.

If this turns out to be a bug somewhere else\, perhaps the test should
be run in a fresh perl instance and skipped on gnukfreebsd?

The issue is tracked on the Debian side as http&#8203;://bugs\.debian\.org/628493

The backtrace is

&nbsp;  Program terminated with signal 11\, Segmentation fault\.
&nbsp;  \#0  0x28491062 in nanosleep \(\) at \.\./sysdeps/unix/syscall\-template\.S&#8203;:82
&nbsp;  82  \.\./sysdeps/unix/syscall\-template\.S&#8203;: No such file or directory\.
&nbsp;      in \.\./sysdeps/unix/syscall\-template\.S
&nbsp;  \(gdb\) bt
&nbsp;  \#0  0x28491062 in nanosleep \(\) at \.\./sysdeps/unix/syscall\-template\.S&#8203;:82
&nbsp;  \#1  0x2848f358 in \_\_pthread\_acquire \(spinlock=\<value optimized out>\) at spinlock\.c&#8203;:728
&nbsp;  \#2  0x2848f4ce in wait\_node\_free \(lock=0x83ebec0\) at spinlock\.c&#8203;:307
&nbsp;  \#3  \_\_pthread\_alt\_unlock \(lock=0x83ebec0\) at spinlock\.c&#8203;:591
&nbsp;  \#4  0x2848c85f in \_\_pthread\_mutex\_unlock \(mutex=0x83ebeb0\) at mutex\.c&#8203;:199
&nbsp;  \#5  0x08159a51 in Perl\_atfork\_unlock \(\) at util\.c&#8203;:2975
&nbsp;  \#6  0x2848cb86 in \_\_pthread\_fork \(b=0x285c19e0\) at ptfork\.c&#8203;:72
&nbsp;  \#7  0x2852dbd1 in \_\_libc\_fork \(\) at \.\./linuxthreads/sysdeps/unix/sysv/linux/fork\.c&#8203;:39
&nbsp;  \#8  0x2848cab4 in \_\_fork \(\) at ptfork\.c&#8203;:84
&nbsp;  \#9  0x08159a8a in Perl\_my\_fork \(\) at util\.c&#8203;:2991
&nbsp;  \#10 0x0829a080 in Perl\_pp\_fork \(my\_perl=0x83ebfb0\) at pp\_sys\.c&#8203;:4021
&nbsp;  \#11 0x08151247 in Perl\_runops\_debug \(my\_perl=0x83ebfb0\) at dump\.c&#8203;:2204
&nbsp;  \#12 0x0808ef07 in S\_run\_body \(my\_perl=0x83ebfb0\, oldscope=1\) at perl\.c&#8203;:2351
&nbsp;  \#13 0x0808e208 in perl\_run \(my\_perl=0x83ebfb0\) at perl\.c&#8203;:2269
&nbsp;  \#14 0x0805fc9a in main \(argc=5\, argv=0xbfbfe7b8\, env=0xbfbfe7d0\) at perlmain\.c&#8203;:120



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=low


---
Site configuration information for perl 5\.15\.1&#8203;:

Configured by niko at Thu Aug  4 14&#8203;:19&#8203;:19 EEST 2011\.

Summary of my perl5 \(revision 5 version 15 subversion 1\) configuration&#8203;:
&nbsp;  Local Commit&#8203;: 8a8f86a04d86583490b4ce4a9821ef57289394a9
&nbsp;  Ancestor&#8203;: 9cfd094e6d0a842551c1c58e998eb057cd8425e3
&nbsp;  Platform&#8203;:
&nbsp;    osname=gnukfreebsd\, osvers=8\.2\-1\-686\-smp\, archname=i686\-gnukfreebsd\-thread\-multi
&nbsp;    uname='gnukfreebsd kbsd32 8\.2\-1\-686\-smp \#0 sun jul 10 20&#8203;:35&#8203;:30 utc 2011 i686 i386 qemu virtual cpu version 0\.14\.1 gnukfreebsd '
&nbsp;    config\_args='\-Dusethreads \-Dusedevel \-DDEBUGGING \-des \-Doptimize=\-g \-O0'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g \-O0'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.6\.1'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib /usr/lib/i386\-kfreebsd\-gnu
&nbsp;    libs=\-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc \-lgdbm\_compat
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    libc=\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.13'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fpic'\, lddlflags='\-shared \-L/usr/local/lib \-fstack\-protector'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl 5\.15\.1&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.15\.1/i686\-gnukfreebsd\-thread\-multi
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.15\.1
&nbsp;    /usr/local/lib/perl5/5\.15\.1/i686\-gnukfreebsd\-thread\-multi
&nbsp;    /usr/local/lib/perl5/5\.15\.1
&nbsp;    \.



---
Environment for perl 5\.15\.1&#8203;:
&nbsp;    HOME=/home/niko
&nbsp;    LANG=en\_US\.UTF\-8
&nbsp;    LANGUAGE=en\_US&#8203;:en
&nbsp;    LC\_CTYPE=fi\_FI\.UTF\-8
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/local/games&#8203;:/usr/games
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @jkeenan

On Thu Aug 04 05&#8203;:19&#8203;:21 2011\, ntyni@&#8203;debian\.org wrote&#8203;:
> 
> This is a bug report for perl from Niko Tyni \<ntyni@&#8203;debian\.org>\,
> generated with the help of perlbug 1\.39 running under perl 5\.15\.1\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> We're seeing a non\-deterministic failure of test 25 \(the last one\)
> of t/op/threads\.t on multiprocessor Debian GNU/kFreeBSD systems\.
> 
> The failure can be reduced to this&#8203;:
> 
>  \./perl \-Ilib \-Mthreads \-e 'threads\->create\(sub \{\}\)\->detach; fork'
> 
> which crashes here in a KVM virtual machine about 10% of the time\.

List&#8203;:  is there anyone testing a threaded perl on Debian GNU/kFreeBSD
who could comment on this problem?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @stevenc99

Hi\!

This seems to have been a bug in GNU/kFreeBSD's threads implementation
in eglibc;  this was just confirmed as fixed and the Debian bug report
closed \(http&#8203;://bugs\.debian\.org/628493\) so I'm also marking it as
resolved here too\.

Thank you\.

**Comment by p5pRT** [comment]
### From @stevenc99

I don't seem to have permissions to close this bug\, but please see my
previous comment and either Niko or an admin here kindly mark this as
resolved\.  Thanks\.

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
