### ISSUE TITLE
SIGSEGV with incorrect backreferences in ?{ }

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#11600]
Migrated from [rt.perl.org#97754](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=97754) (status was 'resolved')

Searchable as RT97754$

**Comment by p5pRT** [comment]
### From Clive.Darke@qa.com

Subject&#8203;: SIGSEGV with incorrect backreferences in ?\{ \}
Message\-Id&#8203;: \<5\.14\.1\_6016\_1314277599@&#8203;BIGFOOT\<mailto&#8203;:5\.14\.1\_6016\_1314277599@&#8203;BIGFOOT>>
Reply\-To&#8203;: clive\.darke@&#8203;qa\.com\<mailto&#8203;:clive\.darke@&#8203;qa\.com>
To&#8203;: perlbug@&#8203;perl\.org\<mailto&#8203;:perlbug@&#8203;perl\.org>
From&#8203;: clive\.darke@&#8203;qa\.com\<mailto&#8203;:clive\.darke@&#8203;qa\.com>

This is a bug report for perl from clive\.darke@&#8203;qa\.com\<mailto&#8203;:clive\.darke@&#8203;qa\.com>\,
generated with the help of perlbug 1\.39 running under perl 5\.14\.1\.
Here is the code that will create the problem&#8203;:
\(yes\, I know it is incorrect\, and that the feature is experimental\)
&nbsp;    use strict;
&nbsp;    use warnings;
&nbsp;    my $txt = 'ABC12D42EF';
&nbsp;    $txt =~ /\[A\-Z\]\(\\d\+\)\[A\-Z\]\(\\d\+\)\(?\{\\g\{1\} \+ \\g\{2\}\}\)\[A\-Z\]/p;
&nbsp;    print "\\$^R&#8203;: $^R $\{^MATCH\} $1 $2\\n";

Perl 5\.14\.1
&nbsp;    On Windows 7\(32\-bit\) gives a Memory Access Violation \(C0000005\)

&nbsp;    On Linux gives a SIGSEGV and core dump&#8203;:

&nbsp;    $ gdb \-c core\.4908 /usr/bin/perl

&nbsp;    GNU gdb \(GDB\) Red Hat Enterprise Linux \(7\.0\.1\-32\.el5\_6\.2\)
&nbsp;    Copyright \(C\) 2009 Free Software Foundation\, Inc\.
&nbsp;    License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
&nbsp;    This is free software&#8203;: you are free to change and redistribute it\.
&nbsp;    There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
&nbsp;    and "show warranty" for details\.
&nbsp;    This GDB was configured as "i386\-redhat\-linux\-gnu"\.
&nbsp;    For bug reporting instructions\, please see&#8203;:
&nbsp;    \<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.\.\.
&nbsp;    Reading symbols from /usr/bin/perl\.\.\.\(no debugging symbols found\)\.\.\.done\.
&nbsp;    Reading symbols from /lib/libnsl\.so\.1\.\.\.\(no debugging symbols found\)\.\.\.done\.
&nbsp;    Loaded symbols for /lib/libnsl\.so\.1
&nbsp;    Reading symbols from /lib/libdl\.so\.2\.\.\.\(no debugging symbols found\)\.\.\.done\.
&nbsp;    Loaded symbols for /lib/libdl\.so\.2
&nbsp;    Reading symbols from /lib/libm\.so\.6\.\.\.\(no debugging symbols found\)\.\.\.done\.
&nbsp;    Loaded symbols for /lib/libm\.so\.6
&nbsp;    Reading symbols from /lib/libcrypt\.so\.1\.\.\.\(no debugging symbols found\)\.\.\.done\.
&nbsp;    Loaded symbols for /lib/libcrypt\.so\.1
&nbsp;    Reading symbols from /lib/libutil\.so\.1\.\.\.\(no debugging symbols found\)\.\.\.done\.
&nbsp;    Loaded symbols for /lib/libutil\.so\.1
&nbsp;    Reading symbols from /lib/libpthread\.so\.0\.\.\.\(no debugging symbols found\)\.\.\.done\.
&nbsp;    Loaded symbols for /lib/libpthread\.so\.0
&nbsp;    Reading symbols from /lib/libc\.so\.6\.\.\.\(no debugging symbols found\)\.\.\.done\.
&nbsp;    Loaded symbols for /lib/libc\.so\.6
&nbsp;    Reading symbols from /lib/ld\-linux\.so\.2\.\.\.\(no debugging symbols found\)\.\.\.done\.
&nbsp;    Loaded symbols for /lib/ld\-linux\.so\.2
&nbsp;    Core was generated by \`perl re\.pl'\.
&nbsp;    Program terminated with signal 11\, Segmentation fault\.
&nbsp;    \#0  0x0810f1c9 in Perl\_leave\_scope \(\)
&nbsp;    \(gdb\) bt
&nbsp;    \#0  0x0810f1c9 in Perl\_leave\_scope \(\)
&nbsp;    \#1  0x080702d8 in S\_my\_exit\_jump \(\)
&nbsp;    \#2  0x080703bf in Perl\_my\_failure\_exit \(\)
&nbsp;    \#3  0x0811bc03 in Perl\_die\_unwind \(\)
&nbsp;    \#4  0x080c3b87 in Perl\_vcroak \(\)
&nbsp;    \#5  0x080c3bf5 in Perl\_croak \(\)
&nbsp;    \#6  0x080dd6b8 in S\_method\_common \(\)
&nbsp;    \#7  0x080dd8ce in Perl\_pp\_method\_named \(\)
&nbsp;    \#8  0x080dd176 in Perl\_runops\_standard \(\)
&nbsp;    \#9  0x0813e74f in S\_regtry \(\)
&nbsp;    \#10 0x08145e2d in S\_find\_byclass \(\)
&nbsp;    \#11 0x0814847e in Perl\_regexec\_flags \(\)
&nbsp;    \#12 0x080e3584 in Perl\_pp\_match \(\)
&nbsp;    \#13 0x080dd176 in Perl\_runops\_standard \(\)
&nbsp;    \#14 0x08073b17 in perl\_run \(\)
&nbsp;    \#15 0x0805ce75 in main \(\)
&nbsp;    \(gdb\) quit

&nbsp;    $ perl \-v

&nbsp;    This is perl 5\, version 14\, subversion 1 \(v5\.14\.1\) built for i686\-linux\-thread\-multi

&nbsp;    Copyright 1987\-2011\, Larry Wall

&nbsp;    Perl may be copied only under the terms of either the Artistic License or the
&nbsp;    GNU General Public License\, which may be found in the Perl 5 source kit\.

&nbsp;    Complete documentation for Perl\, including FAQ lists\, should be found on
&nbsp;    this system using "man perl" or "perldoc perl"\.  If you have access to the
&nbsp;    Internet\, point your browser at http&#8203;://www\.perl\.org/\, the Perl Home Page\.

&nbsp;    $ exit
&nbsp;    exit

&nbsp;    Script done on Thu 25 Aug 2011 01&#8203;:52&#8203;:39 PM BST


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=medium


---
Site configuration information for perl 5\.14\.1&#8203;:
Configured by gecko at Thu Jun 16 18&#8203;:50&#8203;:00 2011\.
Summary of my perl5 \(revision 5 version 14 subversion 1\) configuration&#8203;:

&nbsp;  Platform&#8203;:
&nbsp;    osname=MSWin32\, osvers=5\.2\, archname=MSWin32\-x86\-multi\-thread
&nbsp;    uname=''
&nbsp;    config\_args='undef'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=undef
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cl'\, ccflags ='\-nologo \-GF \-W3 \-MD \-Zi \-DNDEBUG \-O1 \-DWIN32 \-D\_CONSOLE \-DNO\_STRICT \-DPERL\_TEXTMODE\_SCRIPTS \-DUSE\_SITECUSTOMIZE \-DPERL\_IMPLICIT\_CONTEXT \-DPERL\_IMPLICIT\_SYS \-DUSE\_PERLIO \-D\_USE\_32BIT\_TIME\_T'\,
&nbsp;    optimize='\-MD \-Zi \-DNDEBUG \-O1'\,
&nbsp;    cppflags='\-DWIN32'
&nbsp;    ccversion='12\.00\.8168'\, gccversion=''\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=undef\, longlongsize=8\, d\_longdbl=define\, longdblsize=8
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='\_\_int64'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='link'\, ldflags ='\-nologo \-nodefaultlib \-debug \-opt&#8203;:ref\,icf  \-libpath&#8203;:"C&#8203;:\\Perl\\lib\\CORE"  \-machine&#8203;:x86'
&nbsp;    libpth=\\lib
&nbsp;    libs=oldnames\.lib kernel32\.lib user32\.lib gdi32\.lib winspool\.lib  comdlg32\.lib advapi32\.lib shell32\.lib ole32\.lib oleaut32\.lib  netapi32\.lib uuid\.lib ws2\_32\.lib mpr\.lib winmm\.lib  version\.lib odbc32\.lib odbccp32\.lib comctl32\.lib msvcrt\.lib
&nbsp;    perllibs=oldnames\.lib kernel32\.lib user32\.lib gdi32\.lib winspool\.lib  comdlg32\.lib advapi32\.lib shell32\.lib ole32\.lib oleaut32\.lib  netapi32\.lib uuid\.lib ws2\_32\.lib mpr\.lib winmm\.lib  version\.lib odbc32\.lib odbccp32\.lib comctl32\.lib msvcrt\.lib
&nbsp;    libc=msvcrt\.lib\, so=dll\, useshrplib=true\, libperl=perl514\.lib
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_win32\.xs\, dlext=dll\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags=' '\, lddlflags='\-dll \-nologo \-nodefaultlib \-debug \-opt&#8203;:ref\,icf  \-libpath&#8203;:"C&#8203;:\\Perl\\lib\\CORE"  \-machine&#8203;:x86'
Locally applied patches&#8203;:
&nbsp;    ACTIVEPERL\_LOCAL\_PATCHES\_ENTRY


---
@&#8203;INC for perl 5\.14\.1&#8203;:
&nbsp;    C&#8203;:/Perl/site/lib
&nbsp;    C&#8203;:/Perl/lib
&nbsp;    \.


---
Environment for perl 5\.14\.1&#8203;:
&nbsp;    HOME \(unset\)
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=C&#8203;:\\Perl\\site\\bin;C&#8203;:\\Perl\\bin;C&#8203;:\\Perl64\\site\\bin;C&#8203;:\\Perl64\\bin;C&#8203;:\\Program Files \(x86\)\\ATI Stream\\bin\\x86\_64;C&#8203;:\\Program Files \(x86\)\\ATI Stream\\bin\\x86;C&#8203;:\\Windows\\system32;C&#8203;:\\Windows;C&#8203;:\\Windows\\System32\\Wbem;C&#8203;:\\Windows\\System32\\WindowsPowerShell\\v1\.0\\;C&#8203;:\\Program Files \(x86\)\\ATI Technologies\\ATI\.ACE\\Core\-Static;c&#8203;:\\Program Files \(x86\)\\Microsoft SQL Server\\90\\Tools\\binn\\;C&#8203;:\\Program Files \(x86\)\\Lua\\5\.1;C&#8203;:\\Program Files \(x86\)\\Lua\\5\.1\\clibs;C&#8203;:\\Program Files \(x86\)\\QuickTime\\QTSystem\\
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL \(unset\)

Clive Darke
Product Consultant
QA
Vale House Pynes Hill Exeter Devon EX2 5AZ

Email       clive\.darke@&#8203;qa\.com\<mailto&#8203;:clive\.darke@&#8203;qa\.com>
Web        http&#8203;://www\.qa\.com/

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
QA works with organisations to transform performance through learning\. We are dedicated to making our clients more successful through the provision of world\-class training services\.
To find out more visit www\.qa\.com

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material\. Any review\, retransmission\, dissemination or other use of\, or taking of any action in reliance upon\, this information by persons or entities other than the intended recipient is prohibited\. If you received this in error\, please contact the sender and delete the material from any computer\.

QA Ltd\. Rath House\, 55\-65 Uxbridge Road\, Slough\, Berkshire\,SL1 1SG\.
QA Ltd\. is a company registered in England with company registration number&#8203;:2413137

Scanned by ICRITICAL

**Comment by p5pRT** [comment]
### From Clive.Darke@qa.com

Subject&#8203;: SIGSEGV with incorrect backreferences in ?\{ \}
Message\-Id&#8203;: \<5\.14\.1\_6016\_1314277599@&#8203;BIGFOOT>
Reply\-To&#8203;: clive\.darke@&#8203;qa\.com
To&#8203;: perlbug@&#8203;perl\.org
From&#8203;: clive\.darke@&#8203;qa\.com


This is a bug report for perl from clive\.darke@&#8203;qa\.com\,
generated with the help of perlbug 1\.39 running under perl 5\.14\.1\.

Here is the code that will create the problem&#8203;:
\(yes\, I know it is incorrect\, and that the feature is experimental\)

&nbsp;    use strict;
&nbsp;    use warnings;

&nbsp;    my $txt = 'ABC12D42EF';
&nbsp;    $txt =~ /\[A\-Z\]\(\\d\+\)\[A\-Z\]\(\\d\+\)\(?\{\\g\{1\} \+ \\g\{2\}\}\)\[A\-Z\]/p;
&nbsp;    print "\\$^R&#8203;: $^R $\{^MATCH\} $1 $2\\n";
&nbsp;    
Perl 5\.14\.1 
&nbsp;    On Windows 7\(32\-bit\) gives a Memory Access Violation \(C0000005\)
&nbsp;    
&nbsp;    On Linux gives a SIGSEGV and core dump&#8203;:
&nbsp;    
&nbsp;    $ gdb \-c core\.4908 /usr/bin/perl
&nbsp;    
&nbsp;    GNU gdb \(GDB\) Red Hat Enterprise Linux \(7\.0\.1\-32\.el5\_6\.2\)
&nbsp;    Copyright \(C\) 2009 Free Software Foundation\, Inc\.
&nbsp;    License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
&nbsp;    This is free software&#8203;: you are free to change and redistribute it\.
&nbsp;    There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
&nbsp;    and "show warranty" for details\.
&nbsp;    This GDB was configured as "i386\-redhat\-linux\-gnu"\.
&nbsp;    For bug reporting instructions\, please see&#8203;:
&nbsp;    \<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.\.\.
&nbsp;    Reading symbols from /usr/bin/perl\.\.\.\(no debugging symbols found\)\.\.\.done\.
&nbsp;    Reading symbols from /lib/libnsl\.so\.1\.\.\.\(no debugging symbols found\)\.\.\.done\.
&nbsp;    Loaded symbols for /lib/libnsl\.so\.1
&nbsp;    Reading symbols from /lib/libdl\.so\.2\.\.\.\(no debugging symbols found\)\.\.\.done\.
&nbsp;    Loaded symbols for /lib/libdl\.so\.2
&nbsp;    Reading symbols from /lib/libm\.so\.6\.\.\.\(no debugging symbols found\)\.\.\.done\.
&nbsp;    Loaded symbols for /lib/libm\.so\.6
&nbsp;    Reading symbols from /lib/libcrypt\.so\.1\.\.\.\(no debugging symbols found\)\.\.\.done\.
&nbsp;    Loaded symbols for /lib/libcrypt\.so\.1
&nbsp;    Reading symbols from /lib/libutil\.so\.1\.\.\.\(no debugging symbols found\)\.\.\.done\.
&nbsp;    Loaded symbols for /lib/libutil\.so\.1
&nbsp;    Reading symbols from /lib/libpthread\.so\.0\.\.\.\(no debugging symbols found\)\.\.\.done\.
&nbsp;    Loaded symbols for /lib/libpthread\.so\.0
&nbsp;    Reading symbols from /lib/libc\.so\.6\.\.\.\(no debugging symbols found\)\.\.\.done\.
&nbsp;    Loaded symbols for /lib/libc\.so\.6
&nbsp;    Reading symbols from /lib/ld\-linux\.so\.2\.\.\.\(no debugging symbols found\)\.\.\.done\.
&nbsp;    Loaded symbols for /lib/ld\-linux\.so\.2
&nbsp;    Core was generated by \`perl re\.pl'\.
&nbsp;    Program terminated with signal 11\, Segmentation fault\.
&nbsp;    \#0  0x0810f1c9 in Perl\_leave\_scope \(\)
&nbsp;    \(gdb\) bt
&nbsp;    \#0  0x0810f1c9 in Perl\_leave\_scope \(\)
&nbsp;    \#1  0x080702d8 in S\_my\_exit\_jump \(\)
&nbsp;    \#2  0x080703bf in Perl\_my\_failure\_exit \(\)
&nbsp;    \#3  0x0811bc03 in Perl\_die\_unwind \(\)
&nbsp;    \#4  0x080c3b87 in Perl\_vcroak \(\)
&nbsp;    \#5  0x080c3bf5 in Perl\_croak \(\)
&nbsp;    \#6  0x080dd6b8 in S\_method\_common \(\)
&nbsp;    \#7  0x080dd8ce in Perl\_pp\_method\_named \(\)
&nbsp;    \#8  0x080dd176 in Perl\_runops\_standard \(\)
&nbsp;    \#9  0x0813e74f in S\_regtry \(\)
&nbsp;    \#10 0x08145e2d in S\_find\_byclass \(\)
&nbsp;    \#11 0x0814847e in Perl\_regexec\_flags \(\)
&nbsp;    \#12 0x080e3584 in Perl\_pp\_match \(\)
&nbsp;    \#13 0x080dd176 in Perl\_runops\_standard \(\)
&nbsp;    \#14 0x08073b17 in perl\_run \(\)
&nbsp;    \#15 0x0805ce75 in main \(\)
&nbsp;    \(gdb\) quit
&nbsp;    
&nbsp;    $ perl \-v
&nbsp;    
&nbsp;    This is perl 5\, version 14\, subversion 1 \(v5\.14\.1\) built for i686\-linux\-thread\-multi
&nbsp;    
&nbsp;    Copyright 1987\-2011\, Larry Wall
&nbsp;    
&nbsp;    Perl may be copied only under the terms of either the Artistic License or the
&nbsp;    GNU General Public License\, which may be found in the Perl 5 source kit\.
&nbsp;    
&nbsp;    Complete documentation for Perl\, including FAQ lists\, should be found on
&nbsp;    this system using "man perl" or "perldoc perl"\.  If you have access to the
&nbsp;    Internet\, point your browser at http&#8203;://www\.perl\.org/\, the Perl Home Page\.
&nbsp;    
&nbsp;    $ exit
&nbsp;    exit
&nbsp;    
&nbsp;    Script done on Thu 25 Aug 2011 01&#8203;:52&#8203;:39 PM BST



---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=medium


---
Site configuration information for perl 5\.14\.1&#8203;:

Configured by gecko at Thu Jun 16 18&#8203;:50&#8203;:00 2011\.

Summary of my perl5 \(revision 5 version 14 subversion 1\) configuration&#8203;:
&nbsp;   
&nbsp;  Platform&#8203;:
&nbsp;    osname=MSWin32\, osvers=5\.2\, archname=MSWin32\-x86\-multi\-thread
&nbsp;    uname=''
&nbsp;    config\_args='undef'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=undef
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cl'\, ccflags ='\-nologo \-GF \-W3 \-MD \-Zi \-DNDEBUG \-O1 \-DWIN32 \-D\_CONSOLE \-DNO\_STRICT \-DPERL\_TEXTMODE\_SCRIPTS \-DUSE\_SITECUSTOMIZE \-DPERL\_IMPLICIT\_CONTEXT \-DPERL\_IMPLICIT\_SYS \-DUSE\_PERLIO \-D\_USE\_32BIT\_TIME\_T'\,
&nbsp;    optimize='\-MD \-Zi \-DNDEBUG \-O1'\,
&nbsp;    cppflags='\-DWIN32'
&nbsp;    ccversion='12\.00\.8168'\, gccversion=''\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=undef\, longlongsize=8\, d\_longdbl=define\, longdblsize=8
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='\_\_int64'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='link'\, ldflags ='\-nologo \-nodefaultlib \-debug \-opt&#8203;:ref\,icf  \-libpath&#8203;:"C&#8203;:\\Perl\\lib\\CORE"  \-machine&#8203;:x86'
&nbsp;    libpth=\\lib
&nbsp;    libs=oldnames\.lib kernel32\.lib user32\.lib gdi32\.lib winspool\.lib  comdlg32\.lib advapi32\.lib shell32\.lib ole32\.lib oleaut32\.lib  netapi32\.lib uuid\.lib ws2\_32\.lib mpr\.lib winmm\.lib  version\.lib odbc32\.lib odbccp32\.lib comctl32\.lib msvcrt\.lib
&nbsp;    perllibs=oldnames\.lib kernel32\.lib user32\.lib gdi32\.lib winspool\.lib  comdlg32\.lib advapi32\.lib shell32\.lib ole32\.lib oleaut32\.lib  netapi32\.lib uuid\.lib ws2\_32\.lib mpr\.lib winmm\.lib  version\.lib odbc32\.lib odbccp32\.lib comctl32\.lib msvcrt\.lib
&nbsp;    libc=msvcrt\.lib\, so=dll\, useshrplib=true\, libperl=perl514\.lib
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_win32\.xs\, dlext=dll\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags=' '\, lddlflags='\-dll \-nologo \-nodefaultlib \-debug \-opt&#8203;:ref\,icf  \-libpath&#8203;:"C&#8203;:\\Perl\\lib\\CORE"  \-machine&#8203;:x86'

Locally applied patches&#8203;:
&nbsp;    ACTIVEPERL\_LOCAL\_PATCHES\_ENTRY



---
@&#8203;INC for perl 5\.14\.1&#8203;:
&nbsp;    C&#8203;:/Perl/site/lib
&nbsp;    C&#8203;:/Perl/lib
&nbsp;    \.



---
Environment for perl 5\.14\.1&#8203;:
&nbsp;    HOME \(unset\)
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=C&#8203;:\\Perl\\site\\bin;C&#8203;:\\Perl\\bin;C&#8203;:\\Perl64\\site\\bin;C&#8203;:\\Perl64\\bin;C&#8203;:\\Program Files \(x86\)\\ATI Stream\\bin\\x86\_64;C&#8203;:\\Program Files \(x86\)\\ATI Stream\\bin\\x86;C&#8203;:\\Windows\\system32;C&#8203;:\\Windows;C&#8203;:\\Windows\\System32\\Wbem;C&#8203;:\\Windows\\System32\\WindowsPowerShell\\v1\.0\\;C&#8203;:\\Program Files \(x86\)\\ATI Technologies\\ATI\.ACE\\Core\-Static;c&#8203;:\\Program Files \(x86\)\\Microsoft SQL Server\\90\\Tools\\binn\\;C&#8203;:\\Program Files \(x86\)\\Lua\\5\.1;C&#8203;:\\Program Files \(x86\)\\Lua\\5\.1\\clibs;C&#8203;:\\Program Files \(x86\)\\QuickTime\\QTSystem\\
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL \(unset\)

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Aug 25\, 2011 at 06&#8203;:14&#8203;:09AM \-0700\, Darke\, Clive wrote&#8203;:
> Here is the code that will create the problem&#8203;:
> \(yes\, I know it is incorrect\, and that the feature is experimental\)
> 
>     use strict;
>     use warnings;
> 
>     my $txt = 'ABC12D42EF';
>     $txt =~ /\[A\-Z\]\(\\d\+\)\[A\-Z\]\(\\d\+\)\(?\{\\g\{1\} \+ \\g\{2\}\}\)\[A\-Z\]/p;
>     print "\\$^R&#8203;: $^R $\{^MATCH\} $1 $2\\n";
>     
> Perl 5\.14\.1 
>     On Windows 7\(32\-bit\) gives a Memory Access Violation \(C0000005\)
>     
>     On Linux gives a SIGSEGV and core dump&#8203;:

Thanks for the report\. This is a known issue which is currently being
worked on\.

\-\- 
"But Sidley Park is already a picture\, and a most amiable picture too\.
The slopes are green and gentle\. The trees are companionably grouped at
intervals that show them to advantage\. The rill is a serpentine ribbon
unwound from the lake peaceably contained by meadows on which the right
amount of sheep are tastefully arranged\." \-\- Lady Croom\, "Arcadia"

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Thu Aug 25 06&#8203;:14&#8203;:08 2011\, Clive\.Darke@&#8203;qa\.com wrote&#8203;:
>     use strict;
>     use warnings;
>    my $txt = 'ABC12D42EF';
>     $txt =~ /\[A\-Z\]\(\\d\+\)\[A\-Z\]\(\\d\+\)\(?\{\\g\{1\}
>    \+ \\g\{2\}\}\)\[A\-Z\]/p;
>     print "\\$^R&#8203;: $^R $\{^MATCH\} $1 $2\\n";

This has been fixed not to crash any more\, by the commits leading up to
eb58a7e122\, but your code is faulty in its use of \\g\{\}\.  Inside
\(?\{\.\.\.\}\)\, what you have is Perl code\, not a regular expression\, so you
want $1 and $2\, not \\g\{\.\.\.\}\.  \\g\{1\} \+ \\g\{2\} is interpreted as \\1\->g \+ \\2\->g\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From Clive.Darke@qa.com

Thanks\,  I was aware that the code was faulty \(typo\)\, and mentioned that on the report\.  I was more concerned about the SEGV\.

Clive Darke
Principle Technologist for Open Source Programming
QA
Vale House Pynes Hill Exeter Devon EX2 5AZ

Email      clive\.darke@&#8203;qa\.com
Web        http&#8203;://www\.qa\.com/
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
From&#8203;: Father Chrysostomos via RT \[perlbug\-followup@&#8203;perl\.org\]
Sent&#8203;: 14 June 2012 17&#8203;:46
To&#8203;: Darke\, Clive
Subject&#8203;: \[perl \#97754\] SIGSEGV with incorrect backreferences in ?\{ \}

On Thu Aug 25 06&#8203;:14&#8203;:08 2011\, Clive\.Darke@&#8203;qa\.com wrote&#8203;:
>     use strict;
>     use warnings;
>    my $txt = 'ABC12D42EF';
>     $txt =~ /\[A\-Z\]\(\\d\+\)\[A\-Z\]\(\\d\+\)\(?\{\\g\{1\}
>    \+ \\g\{2\}\}\)\[A\-Z\]/p;
>     print "\\$^R&#8203;: $^R $\{^MATCH\} $1 $2\\n";

This has been fixed not to crash any more\, by the commits leading up to
eb58a7e122\, but your code is faulty in its use of \\g\{\}\.  Inside
\(?\{\.\.\.\}\)\, what you have is Perl code\, not a regular expression\, so you
want $1 and $2\, not \\g\{\.\.\.\}\.  \\g\{1\} \+ \\g\{2\} is interpreted as \\1\->g \+ \\2\->g\.

\-\-

Father Chrysostomos

QA works with organisations to transform performance through learning\. We are dedicated to making our clients more successful through the provision of world\-class training services\.
To find out more visit www\.qa\.com

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material\. Any review\, retransmission\, dissemination or other use of\, or taking of any action in reliance upon\, this information by persons or entities other than the intended recipient is prohibited\. If you received this in error\, please contact the sender and delete the material from any computer\.

QA Ltd\. Rath House\, 55\-65 Uxbridge Road\, Slough\, Berkshire\,SL1 1SG\.
QA Ltd\. is a company registered in England with company registration number&#8203;:2413137
Scanned by ICRITICAL
