### ISSUE TITLE
d527ce7c pp_caller UTF8 cleanup broke B::C XSLoader

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#11696]
Migrated from [rt.perl.org#101336](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=101336) (status was 'resolved')

Searchable as RT101336$

**Comment by p5pRT** [comment]
### From @rurban

This is a bug report for perl from rurban@&#8203;cpan\.org\,
generated with the help of perlbug 1\.39 running under perl 5\.14\.2\.




---
This commit d527ce7c3632e2eaebee9f962268da87e0becd51
Author&#8203;: Brian Fraser \<fraserbn@&#8203;gmail\.com>
Date&#8203;:   Mon Sep 26 15&#8203;:32&#8203;:45 2011 \-0700

&nbsp;    pp\_ctl\.c&#8203;: pp\_caller UTF8 cleanup\.

using the stash hek instead of the stash name broke the B&#8203;::C compiler\,
esp\. for XSLoader\, loading dynamic modules from within C\.
Overwriting the static cop with the new HEK fails with

\#0  0x00007fff812fd0b6 in \_\_kill \(\)
\#1  0x00007fff8139d9f6 in abort \(\)
\#2  0x00007fff8138a9bc in \_\_assert\_rtn \(\)
\#3  0x00000001002ae422 in S\_unshare\_hek\_or\_pvn \(hek=0x10062d1e8\,
str=0x0\, len=0\, hash=0\) at hv\.c&#8203;:2588
\#4  0x00000001002ae3a6 in Perl\_unshare\_hek \(hek=0x10062d1e8\) at hv\.c&#8203;:2561
\#5  0x000000010030da9c in Perl\_sv\_force\_normal\_flags \(sv=0x1000cf990\,
flags=4\) at sv\.c&#8203;:4829
\#6  0x000000010030c4a8 in Perl\_sv\_usepvn\_flags \(sv=0x1000cf990\,
ptr=0x100608650 "Data&#8203;::Dumper"\, len=12\, flags=256\) at sv\.c&#8203;:4659
\#7  0x000000010030c08b in Perl\_sv\_sethek \(sv=0x1000cf990\,
hek=0x100608648\) at sv\.c&#8203;:4618
\#8  0x00000001003974ad in Perl\_pp\_caller \(\) at pp\_ctl\.c&#8203;:1911
\#9  0x000000010025d2af in Perl\_runops\_debug \(\) at dump\.c&#8203;:2201
\#10 0x000000010017ab91 in Perl\_call\_sv \(sv=0x1000c96b0\, flags=5\) at perl\.c&#8203;:2665
\#11 0x000000010017a56e in Perl\_call\_pv \(sub\_name=0x1000a4b8d
"XSLoader&#8203;::load"\, flags=5\) at perl\.c&#8203;:2568
\#12 0x000000010009fd20 in dl\_init \(\) at ccode45\.c&#8203;:28187

This was not an issue with the stashname\.
Repro&#8203;:
$ cpan B&#8203;::C
$ t/testc\.sh 45

I found no way to workaround this\.


---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=high


---
Site configuration information for perl 5\.14\.2&#8203;:

Configured by rurban at Tue Sep 27 12&#8203;:28&#8203;:28 CDT 2011\.

Summary of my perl5 \(revision 5 version 14 subversion 2\) configuration&#8203;:

&nbsp;  Platform&#8203;:
&nbsp;    osname=darwin\, osvers=10\.8\.0\, archname=darwin\-x86\-64\-nothreads
&nbsp;    uname='darwin air\.local 10\.8\.0 darwin kernel version 10\.8\.0&#8203;: tue
jun 7 16&#8203;:33&#8203;:36 pdt 2011; root&#8203;:xnu\-1504\.15\.3~1release\_i386 i386 '
&nbsp;    config\_args='\-de \-Dusedtrace \-Dmksymlinks \-Doptimize=\-Os
\-Uuseithreads \-Dcc=gcc\-mp\-4\.6 \-Accflags=\-m64 \-Duseshrplib
\-Dld=gcc\-mp\-4\.6 \-Accflags=\-mssse3 \-Darchname=darwin\-x86\-64\-nothreads'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc\-mp\-4\.6'\, ccflags ='\-fno\-common \-DPERL\_DARWIN \-m64 \-mssse3
\-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include
\-I/opt/local/include'\,
&nbsp;    optimize='\-Os'\,
&nbsp;    cppflags='\-fno\-common \-DPERL\_DARWIN \-m64 \-mssse3
\-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include
\-I/opt/local/include'
&nbsp;    ccversion=''\, gccversion='4\.6\.1 20110325 \(prerelease\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,
lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='env MACOSX\_DEPLOYMENT\_TARGET=10\.3 cc'\, ldflags ='
\-fstack\-protector \-L/usr/local/lib \-L/opt/local/lib'
&nbsp;    libpth=/usr/local/lib /opt/local/lib /usr/lib
&nbsp;    libs=\-lgdbm \-ldbm \-ldl \-lm \-lutil \-lc
&nbsp;    perllibs=\-ldl \-lm \-lutil \-lc
&nbsp;    libc=\, so=dylib\, useshrplib=true\, libperl=libperl\.dylib
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=bundle\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags=' '\, lddlflags=' \-bundle \-undefined dynamic\_lookup
\-L/usr/local/lib \-L/opt/local/lib \-fstack\-protector'

Locally applied patches&#8203;:




---
@&#8203;INC for perl 5\.14\.2&#8203;:
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.14\.2/darwin\-x86\-64\-nothreads
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.14\.2
&nbsp;    /usr/local/lib/perl5/5\.14\.2/darwin\-x86\-64\-nothreads
&nbsp;    /usr/local/lib/perl5/5\.14\.2
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.14\.1
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.14\.0
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.10\.1
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.8\.9
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.6\.2
&nbsp;    /usr/local/lib/perl5/site\_perl
&nbsp;    \.



---
Environment for perl 5\.14\.2&#8203;:
&nbsp;    DYLD\_LIBRARY\_PATH \(unset\)
&nbsp;    HOME=/Users/rurban
&nbsp;    LANG=en\_US\.UTF\-8
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LC\_CTYPE=en\_US\.UTF\-8
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/opt/local/libexec/gnubin&#8203;:/opt/local/bin&#8203;:/opt/local/sbin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/sbin&#8203;:/sbin&#8203;:/usr/local/bin&#8203;:/usr/X11/bin&#8203;:/Users/rurban/bin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

\-\- 
Reini Urban
http&#8203;://cpanel\.net/   http&#8203;://www\.perl\-compiler\.org/

**Comment by p5pRT** [comment]
### From @rurban

Found a workaround
http&#8203;://code\.google\.com/p/perl\-compiler/issues/detail?id=77

I added a XSLoader&#8203;::load\_file function with a sane API in r1190\, which does not use caller\(\) and 
its new problem with using HEK instead of the stashname PV\. We have no caller info since we 
freeze/thaw the state after BEGIN\, when the bootstrap call was already made\, and we have no 
caller information for this call\. We successfully faked it until 5\.15\.3 in dl\_init\(\)\, now we use our 
private XSLoader&#8203;::load\_file\(\)
\-\-
Reini Urban

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Found a workaround
http&#8203;://code\.google\.com/p/perl\-compiler/issues/detail?id=77

I added a XSLoader&#8203;::load\_file function with a sane API in r1190\, which does not use caller\(\) and 
its new problem with using HEK instead of the stashname PV\. We have no caller info since we 
freeze/thaw the state after BEGIN\, when the bootstrap call was already made\, and we have no 
caller information for this call\. We successfully faked it until 5\.15\.3 in dl\_init\(\)\, now we use our 
private XSLoader&#8203;::load\_file\(\)
\-\-
Reini Urban

**Comment by p5pRT** [comment]
@rurban - Status changed from 'new' to 'resolved'

**Comment by p5pRT** [comment]
### From @cpansprout

On Mon Oct 17 11&#8203;:30&#8203;:05 2011\, rurban wrote&#8203;:
> Found a workaround
> http&#8203;://code\.google\.com/p/perl\-compiler/issues/detail?id=77
> 
> I added a XSLoader&#8203;::load\_file function with a sane API in r1190\, which
> does not use caller\(\) and
> its new problem with using HEK instead of the stashname PV\. We have no
> caller info since we
> freeze/thaw the state after BEGIN\, when the bootstrap call was already
> made\, and we have no
> caller information for this call\. We successfully faked it until
> 5\.15\.3 in dl\_init\(\)\, now we use our
> private XSLoader&#8203;::load\_file\(\)

Thank you\.  I was going to try and look at this\, but I only got as far
as staring at the offending change and wondering how it could have
broken anything\.\.\.\.
