### ISSUE TITLE
5.15.9 breaks Glib

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#12014]
Migrated from [rt.perl.org#111974](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=111974) (status was 'resolved')

Searchable as RT111974$

**Comment by p5pRT** [comment]
### From kaffeetisch@gmx.de

#### Created by kaffeetisch@gmx.de



I probably shouldn't have reported this at the bottom of another thread
\(\<http&#8203;://perl\.markmail\.org/thread/7be6f2t47bqrtjnr>\)\, so here it is again&#8203;:

With perl 5\.15\.9 \(and blead\) multiple of Glib's tests segfault\.  This
reproduces the issue&#8203;:

&nbsp;   use Glib;
&nbsp;   my $obj = Glib&#8203;::Object\->new;
&nbsp;   $obj\->\{key\} = 'val';

gdb says&#8203;:

Program received signal SIGSEGV\, Segmentation fault\.
0x080ed041 in Perl\_mg\_clear \(my\_perl=0x81fa008\, sv=0x81fe3d0\) at mg\.c&#8203;:376
376        if \(vtbl && vtbl\->svt\_clear\)
\(gdb\) bt
\#0  0x080ed041 in Perl\_mg\_clear \(my\_perl=0x81fa008\, sv=0x81fe3d0\) at 
mg\.c&#8203;:376
\#1  0x08107264 in Perl\_hv\_undef\_flags \(my\_perl=0x81fa008\, hv=0x81fe3d0\,
&nbsp;     flags=2\) at hv\.c&#8203;:1872
\#2  0x08122976 in Perl\_sv\_clear \(my\_perl=0x81fa008\, orig\_sv=0x81fe3d0\)
&nbsp;     at sv\.c&#8203;:6294
\#3  0x08123146 in Perl\_sv\_free2 \(my\_perl=0x81fa008\, sv=0x81fe3d0\) at 
sv\.c&#8203;:6506
\#4  0x08129a87 in Perl\_sv\_unref\_flags \(my\_perl=0x696c6174\, ref=0x8217270\,
&nbsp;     flags=1\) at sv\.c&#8203;:9623
\#5  0x0811f776 in Perl\_sv\_force\_normal\_flags \(my\_perl=0x81fa008\, 
sv=0x8217270\,
&nbsp;     flags=1\) at sv\.c&#8203;:4834
\#6  0x0814f6e9 in Perl\_leave\_scope \(my\_perl=0x81fa008\, base=0\) at 
scope\.c&#8203;:914
\#7  0x0814d1ff in Perl\_pop\_scope \(my\_perl=0x696c6174\) at scope\.c&#8203;:110
\#8  0x08158155 in Perl\_pp\_leave \(my\_perl=0x81fa008\) at pp\_ctl\.c&#8203;:2152
\#9  0x0810c4e7 in Perl\_runops\_standard \(my\_perl=0x81fa008\) at run\.c&#8203;:41
\#10 0x0807d373 in S\_run\_body \(my\_perl=0x81fa008\, oldscope=1\) at perl\.c&#8203;:2400
\#11 0x0807ce5b in perl\_run \(my\_perl=0x81fa008\) at perl\.c&#8203;:2318
\#12 0x0805d96d in main \(argc=2\, argv=0xbffff594\, env=0xbffff5a0\)
&nbsp;     at perlmain\.c&#8203;:120

valgrind says&#8203;:

==26758== Conditional jump or move depends on uninitialised value\(s\)
==26758==    at 0x80ED06B&#8203;: Perl\_mg\_clear \(mg\.c&#8203;:370\)
==26758==    by 0x8107263&#8203;: Perl\_hv\_undef\_flags \(hv\.c&#8203;:1872\)
==26758==    by 0x8122975&#8203;: Perl\_sv\_clear \(sv\.c&#8203;:6294\)
==26758==    by 0x8123145&#8203;: Perl\_sv\_free2 \(sv\.c&#8203;:6506\)
==26758==    by 0x8129A86&#8203;: Perl\_sv\_unref\_flags \(sv\.c&#8203;:9623\)
==26758==    by 0x811F775&#8203;: Perl\_sv\_force\_normal\_flags \(sv\.c&#8203;:4834\)
==26758==    by 0x814F6E8&#8203;: Perl\_leave\_scope \(scope\.c&#8203;:914\)
==26758==    by 0x814D1FE&#8203;: Perl\_pop\_scope \(scope\.c&#8203;:110\)
==26758==    by 0x8158154&#8203;: Perl\_pp\_leave \(pp\_ctl\.c&#8203;:2152\)
==26758==    by 0x810C4E6&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==26758==    by 0x807D372&#8203;: S\_run\_body \(perl\.c&#8203;:2400\)
==26758==    by 0x807CE5A&#8203;: perl\_run \(perl\.c&#8203;:2318\)
==26758==    by 0x805D96C&#8203;: main \(perlmain\.c&#8203;:120\)
==26758==
==26758== Use of uninitialised value of size 4
==26758==    at 0x80ED02A&#8203;: Perl\_mg\_clear \(mg\.c&#8203;:371\)
==26758==    by 0x8107263&#8203;: Perl\_hv\_undef\_flags \(hv\.c&#8203;:1872\)
==26758==    by 0x8122975&#8203;: Perl\_sv\_clear \(sv\.c&#8203;:6294\)
==26758==    by 0x8123145&#8203;: Perl\_sv\_free2 \(sv\.c&#8203;:6506\)
==26758==    by 0x8129A86&#8203;: Perl\_sv\_unref\_flags \(sv\.c&#8203;:9623\)
==26758==    by 0x811F775&#8203;: Perl\_sv\_force\_normal\_flags \(sv\.c&#8203;:4834\)
==26758==    by 0x814F6E8&#8203;: Perl\_leave\_scope \(scope\.c&#8203;:914\)
==26758==    by 0x814D1FE&#8203;: Perl\_pop\_scope \(scope\.c&#8203;:110\)
==26758==    by 0x8158154&#8203;: Perl\_pp\_leave \(pp\_ctl\.c&#8203;:2152\)
==26758==    by 0x810C4E6&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==26758==    by 0x807D372&#8203;: S\_run\_body \(perl\.c&#8203;:2400\)
==26758==    by 0x807CE5A&#8203;: perl\_run \(perl\.c&#8203;:2318\)
==26758==    by 0x805D96C&#8203;: main \(perlmain\.c&#8203;:120\)
==26758==
==26758== Use of uninitialised value of size 4
==26758==    at 0x80ED033&#8203;: Perl\_mg\_clear \(mg\.c&#8203;:374\)
==26758==    by 0x8107263&#8203;: Perl\_hv\_undef\_flags \(hv\.c&#8203;:1872\)
==26758==    by 0x8122975&#8203;: Perl\_sv\_clear \(sv\.c&#8203;:6294\)
==26758==    by 0x8123145&#8203;: Perl\_sv\_free2 \(sv\.c&#8203;:6506\)
==26758==    by 0x8129A86&#8203;: Perl\_sv\_unref\_flags \(sv\.c&#8203;:9623\)
==26758==    by 0x811F775&#8203;: Perl\_sv\_force\_normal\_flags \(sv\.c&#8203;:4834\)
==26758==    by 0x814F6E8&#8203;: Perl\_leave\_scope \(scope\.c&#8203;:914\)
==26758==    by 0x814D1FE&#8203;: Perl\_pop\_scope \(scope\.c&#8203;:110\)
==26758==    by 0x8158154&#8203;: Perl\_pp\_leave \(pp\_ctl\.c&#8203;:2152\)
==26758==    by 0x810C4E6&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==26758==    by 0x807D372&#8203;: S\_run\_body \(perl\.c&#8203;:2400\)
==26758==    by 0x807CE5A&#8203;: perl\_run \(perl\.c&#8203;:2318\)
==26758==    by 0x805D96C&#8203;: main \(perlmain\.c&#8203;:120\)
==26758==
==26758== Invalid read of size 4
==26758==    at 0x80ED041&#8203;: Perl\_mg\_clear \(mg\.c&#8203;:376\)
==26758==    by 0x8107263&#8203;: Perl\_hv\_undef\_flags \(hv\.c&#8203;:1872\)
==26758==    by 0x8122975&#8203;: Perl\_sv\_clear \(sv\.c&#8203;:6294\)
==26758==    by 0x8123145&#8203;: Perl\_sv\_free2 \(sv\.c&#8203;:6506\)
==26758==    by 0x8129A86&#8203;: Perl\_sv\_unref\_flags \(sv\.c&#8203;:9623\)
==26758==    by 0x811F775&#8203;: Perl\_sv\_force\_normal\_flags \(sv\.c&#8203;:4834\)
==26758==    by 0x814F6E8&#8203;: Perl\_leave\_scope \(scope\.c&#8203;:914\)
==26758==    by 0x814D1FE&#8203;: Perl\_pop\_scope \(scope\.c&#8203;:110\)
==26758==    by 0x8158154&#8203;: Perl\_pp\_leave \(pp\_ctl\.c&#8203;:2152\)
==26758==    by 0x810C4E6&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==26758==    by 0x807D372&#8203;: S\_run\_body \(perl\.c&#8203;:2400\)
==26758==    by 0x807CE5A&#8203;: perl\_run \(perl\.c&#8203;:2318\)
==26758==    by 0x805D96C&#8203;: main \(perlmain\.c&#8203;:120\)
==26758==  Address 0x696c6180 is not stack'd\, malloc'd or \(recently\) free'd
==26758==
==26758==
==26758== Process terminating with default action of signal 11 \(SIGSEGV\)
==26758==  Access not within mapped region at address 0x696C6180
==26758==    at 0x80ED041&#8203;: Perl\_mg\_clear \(mg\.c&#8203;:376\)
==26758==    by 0x8107263&#8203;: Perl\_hv\_undef\_flags \(hv\.c&#8203;:1872\)
==26758==    by 0x8122975&#8203;: Perl\_sv\_clear \(sv\.c&#8203;:6294\)
==26758==    by 0x8123145&#8203;: Perl\_sv\_free2 \(sv\.c&#8203;:6506\)
==26758==    by 0x8129A86&#8203;: Perl\_sv\_unref\_flags \(sv\.c&#8203;:9623\)
==26758==    by 0x811F775&#8203;: Perl\_sv\_force\_normal\_flags \(sv\.c&#8203;:4834\)
==26758==    by 0x814F6E8&#8203;: Perl\_leave\_scope \(scope\.c&#8203;:914\)
==26758==    by 0x814D1FE&#8203;: Perl\_pop\_scope \(scope\.c&#8203;:110\)
==26758==    by 0x8158154&#8203;: Perl\_pp\_leave \(pp\_ctl\.c&#8203;:2152\)
==26758==    by 0x810C4E6&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==26758==    by 0x807D372&#8203;: S\_run\_body \(perl\.c&#8203;:2400\)
==26758==    by 0x807CE5A&#8203;: perl\_run \(perl\.c&#8203;:2318\)
==26758==    by 0x805D96C&#8203;: main \(perlmain\.c&#8203;:120\)
==26758==  If you believe this happened as a result of a stack
==26758==  overflow in your program's main thread \(unlikely but
==26758==  possible\)\, you can try to increase the size of the
==26758==  main thread stack using the \-\-main\-stacksize= flag\.
==26758==  The main thread stack size used in this run was 8388608\.

\(In case you cannot find Glib on CPAN\-\-\-there's some index issue
currently\-\-\-you can use
\<http&#8203;://sourceforge\.net/projects/gtk2\-perl/files/Glib/1\.242/Glib\-1\.242\.tar\.gz/download>\.\)

'git bisect' points at the below commit as the culprit\.

On 06\.03\.2012 15&#8203;:35\, Dave Mitchell wrote&#8203;:
 > commit 5bec93bead1c10563a402404de095bbdf398790f
 > Author&#8203;:     David Mitchell\<davem@&#8203;iabyn\.com>
 > AuthorDate&#8203;: Tue Mar 6 14&#8203;:26&#8203;:27 2012 \+0000
 > Commit&#8203;:     David Mitchell\<davem@&#8203;iabyn\.com>
 > CommitDate&#8203;: Tue Mar 6 14&#8203;:26&#8203;:27 2012 \+0000
 >
 >      fix slowdown in nested hash freeing

<details><summary>Perl Info</summary>

```

Flags:
     category=core
     severity=medium

Site configuration information for perl 5.15.9:

Configured by torsten at Sun Mar 25 14:02:45 CEST 2012.

Summary of my perl5 (revision 5 version 15 subversion 9) configuration:

   Platform:
     osname=linux, osvers=3.0.0-16-generic-pae, 
archname=i686-linux-thread-multi
     uname='linux home.hcsiteeffak.de 3.0.0-16-generic-pae #29-ubuntu 
smp tue feb 14 13:56:31 utc 2012 i686 athlon i386 gnulinux '
     config_args='-Dprefix=/opt/perls/perl-5.15.9 -Dusethreads 
-Doptimize=-g -Dusedevel -des'
     hint=recommended, useposix=true, d_sigaction=define
     useithreads=define, usemultiplicity=define
     useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
     use64bitint=undef, use64bitall=undef, uselongdouble=undef
     usemymalloc=n, bincompat5005=undef
   Compiler:
     cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing 
-pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE 
-D_FILE_OFFSET_BITS=64',
     optimize='-g',
     cppflags='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe 
-fstack-protector -I/usr/local/include'
     ccversion='', gccversion='4.6.1', gccosandvers=''
     intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
     d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
     ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', 
lseeksize=8
     alignbytes=4, prototype=define
   Linker and Libraries:
     ld='cc', ldflags =' -fstack-protector -L/usr/local/lib'
     libpth=/usr/local/lib /lib/i386-linux-gnu /lib/../lib 
/usr/lib/i386-linux-gnu /usr/lib/../lib /lib /usr/lib
     libs=-lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lpthread -lc 
-lgdbm_compat
     perllibs=-lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
     libc=, so=so, useshrplib=false, libperl=libperl.a
     gnulibc_version='2.13'
   Dynamic Linking:
     dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
     cccdlflags='-fPIC', lddlflags='-shared -g -L/usr/local/lib 
-fstack-protector'

Locally applied patches:



@INC for perl 5.15.9:
     /opt/perls/perl-5.15.9-lib/lib/perl5/i686-linux-thread-multi
     /opt/perls/perl-5.15.9-lib/lib/perl5
     /opt/perls/perl-5.15.9/lib/site_perl/5.15.9/i686-linux-thread-multi
     /opt/perls/perl-5.15.9/lib/site_perl/5.15.9
     /opt/perls/perl-5.15.9/lib/5.15.9/i686-linux-thread-multi
     /opt/perls/perl-5.15.9/lib/5.15.9
     .


Environment for perl 5.15.9:
     HOME=/home/torsten
     LANG=de_DE.UTF-8
     LANGUAGE=en
     LC_COLLATE=en_US.UTF-8
     LC_CTYPE=en_US.UTF-8
     LC_MEASUREMENT=de_DE.UTF-8
     LC_MESSAGES=en_US.UTF-8
     LC_MONETARY=de_DE.UTF-8
     LC_NUMERIC=de_DE.UTF-8
     LC_PAPER=de_DE.UTF-8
     LC_TIME=de_DE.UTF-8
     LD_LIBRARY_PATH (unset)
     LOGDIR (unset)
 
PATH=/opt/perls/perl-5.15.9-lib/bin:/opt/perls/perl-5.15.9/bin:/opt/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
     PERL5LIB=/opt/perls/perl-5.15.9-lib/lib/perl5
     PERL5PREFIX=/opt/perls/perl-5.15.9-lib
     PERL_BADLANG (unset)
     PERL_MB_OPT=--install_base=/opt/perls/perl-5.15.9-lib
     PERL_MM_OPT=INSTALL_BASE=/opt/perls/perl-5.15.9-lib
     SHELL=/usr/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @cpansprout

On Sun Mar 25 07&#8203;:56&#8203;:30 2012\, kaffeetisch@&#8203;gmx\.de wrote&#8203;:
> With perl 5\.15\.9 \(and blead\) multiple of Glib's tests segfault\.  This
> reproduces the issue&#8203;:
> 
>    use Glib;
>    my $obj = Glib&#8203;::Object\->new;
>    $obj\->\{key\} = 'val';
> 
> 'git bisect' points at the below commit as the culprit\.
> 
> On 06\.03\.2012 15&#8203;:35\, Dave Mitchell wrote&#8203;:
>  > commit 5bec93bead1c10563a402404de095bbdf398790f
>  > Author&#8203;:     David Mitchell\<davem@&#8203;iabyn\.com>
>  > AuthorDate&#8203;: Tue Mar 6 14&#8203;:26&#8203;:27 2012 \+0000
>  > Commit&#8203;:     David Mitchell\<davem@&#8203;iabyn\.com>
>  > CommitDate&#8203;: Tue Mar 6 14&#8203;:26&#8203;:27 2012 \+0000
>  >
>  >      fix slowdown in nested hash freeing

This is a new regression in the last month\.  I think we really need to
fix this before 5\.16\.  Can this be made a blocker?

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

fixed with f37f40f4443470b7a9dc16c4549f9074ff36057b

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @rjbs

\* Father Chrysostomos via RT \<perlbug\-followup@&#8203;perl\.org> \[2012\-03\-25T13&#8203;:52&#8203;:43\]
> This is a new regression in the last month\.  I think we really need to
> fix this before 5\.16\.  Can this be made a blocker?

Done\.

\-\- 
rjbs

**Comment by p5pRT** [comment]
### From @andk

>>>>> On Sun\, 25 Mar 2012 07&#8203;:56&#8203;:31 \-0700\, Torsten Schoenfeld \(via RT\) \<perlbug\-followup@&#8203;perl\.org> said&#8203;:

 tsch> \(In case you cannot find Glib on CPAN\-\-\-there's some index issue
 tsch> currently\-\-\-you can use
 tsch> \<http&#8203;://sourceforge\.net/projects/gtk2\-perl/files/Glib/1\.242/Glib\-1\.242\.tar\.gz/download>\.\)

If I can help you to resolve the indexing issue\, please let me know\.
Having a distro that is both not indexed and involved in a blocker is a
pita\.

>>>>> On Mon\, 26 Mar 2012 22&#8203;:22&#8203;:22 \-0400\, Ricardo Signes \<perl\.p5p@&#8203;rjbs\.manxome\.org> said&#8203;:

 rjbs> \* Father Chrysostomos via RT \<perlbug\-followup@&#8203;perl\.org> \[2012\-03\-25T13&#8203;:52&#8203;:43\]
 >> This is a new regression in the last month\.  I think we really need to
 >> fix this before 5\.16\.  Can this be made a blocker?

 rjbs> Done\.

Fixed with v5\.15\.9\-39\-gf37f40f according to Message\-ID&#8203;:
\<20120326140153\.GB2918@&#8203;iabyn\.com>

Tested by myself against XAOC/Glib\-1\.242\.tar\.gz\, XAOC/Glib\-1\.250\.tar\.gz\,
and XAOC/Glib\-1\.252\_001\.tar\.gz

\-\- 
andreas
