### ISSUE TITLE
Not OK: perl v5.5.660 on Linux-i686 -Dusemymalloc

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#1212]
Migrated from [rt.perl.org#2195](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=2195) (status was 'resolved')

Searchable as RT2195$

**Comment by p5pRT** [comment]
### From jtobey@ne.mediaone.net

#### Created by jtobey@john-edwin-tobey.org



t/pragma/warning\.t fails in utf8 in free\(\)&#8203;:

$ \./perl harness pragma/warnings\.t 
pragma/warnings\.\.\.\.\.ok 338/348PROG&#8203;:                                          
\# utf8\.c \[utf8\_to\_uv\] \-W
use utf8 ;
my $a = "snstorm" ;
\{
&nbsp;    no warnings 'utf8' ;
&nbsp;    my $a = "snstorm";
&nbsp;    use warnings 'utf8' ;
&nbsp;    my $a = "snstorm";
\}
EXPECTED&#8203;:
Malformed UTF\-8 character at \- line 3\.
Malformed UTF\-8 character at \- line 8\.
GOT&#8203;:
Malformed UTF\-8 character at \- line 3\.
assertion botched \(chunk's tail overwrite?\)&#8203;: \*\(\(char \*\)\(\(caddr\_t\)ovp \+ nbytes \- sizeof \(unsigned int\) \+ i\)\) == 0x55
pragma/warnings\.\.\.\.\.ok 348/348FAILED test 339                                
&nbsp;        Failed 1/348 tests\, 99\.71% okay
Failed Test  Status Wstat Total Fail  Failed  List of failed
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
pragma/warnings             348    1   0\.29%  339
Failed 1/1 test scripts\, 0\.00% okay\. 1/348 subtests failed\, 99\.71% okay\.


Here is the backtrace from GDB&#8203;:

\(gdb\) r \-I\.\./lib tmp
Starting program&#8203;: /src/perl5\.5\.660/t/perl \-I\.\./lib tmp
Malformed UTF\-8 character at tmp line 3\.
assertion botched \(chunk's tail overwrite?\)&#8203;: \*\(\(char \*\)\(\(caddr\_t\)ovp \+ nbytes \- sizeof \(unsigned int\) \+ i\)\) == 0x55

Program received signal SIGABRT\, Aborted\.
0x400af5d1 in kill \(\) from /lib/libc\.so\.6
\(gdb\) bt
\#0  0x400af5d1 in kill \(\) from /lib/libc\.so\.6
\#1  0x400af2b8 in raise \(\) from /lib/libc\.so\.6
\#2  0x400b0911 in abort \(\) from /lib/libc\.so\.6
\#3  0x805f789 in botch \(\) at malloc\.c&#8203;:963
\#4  0x806016c in free \(mp=0x81070e8\) at malloc\.c&#8203;:1558
\#5  0x80a647e in Perl\_sv\_clear \(sv=0x8109420\) at sv\.c&#8203;:3666
\#6  0x80a6739 in Perl\_sv\_free \(sv=0x8109420\) at sv\.c&#8203;:3782
\#7  0x8078d91 in S\_op\_clear \(o=0x810ba08\) at op\.c&#8203;:798
\#8  0x8078ca9 in Perl\_op\_free \(o=0x810ba08\) at op\.c&#8203;:745
\#9  0x8078c6c in Perl\_op\_free \(o=0x810b9c8\) at op\.c&#8203;:733
\#10 0x807affc in Perl\_fold\_constants \(o=0x810b9c8\) at op\.c&#8203;:2239
\#11 0x807b2d5 in Perl\_convert \(type=67\, flags=0\, o=0x810ba08\) at op\.c&#8203;:2344
\#12 0x8076d33 in Perl\_yyparse \(\) at perly\.y&#8203;:422
\#13 0x805bc71 in S\_parse\_body \(env=0x0\, xsinit=0x8059ac0 \<xs\_init>\)
&nbsp;    at perl\.c&#8203;:1198
\#14 0x805b333 in perl\_parse \(my\_perl=0x80fb408\, xsinit=0x8059ac0 \<xs\_init>\, 
&nbsp;    argc=3\, argv=0xbffffd14\, env=0x0\) at perl\.c&#8203;:813
\#15 0x8059a79 in main \(argc=3\, argv=0xbffffd14\, env=0xbffffd24\)
&nbsp;    at perlmain\.c&#8203;:51

<details><summary>Perl Info</summary>

```


Site configuration information for perl v5.5.650:

Configured by jtobey at Fri Feb 11 02:13:31 EST 2000.

Summary of my perl5 (revision 5.0 version 5 subversion 650) configuration:
  Platform:
    osname=linux, osvers=2.2.14pre16, archname=i686-linux
    uname='linux feynman 2.2.14pre16 #1 thu dec 23 19:33:36 est 1999 i686 unknown '
    config_args='-Dcc=gcc -Dprefix=/usr/local -Doptimize=-g -O2 -ders'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef
    usesocks=undef useperlio=undef d_sfio=undef
    use64bits=undef uselargefiles=define usemultiplicity=undef
  Compiler:
    cc='gcc', optimize='-g -O2', gccversion=2.95.2 19991109 (Debian GNU/Linux)
    cppflags='-Dbool=char -DHAS_BOOL -DDEBUGGING -fno-strict-aliasing -I/usr/local/include'
    ccflags ='-Dbool=char -DHAS_BOOL -DDEBUGGING -fno-strict-aliasing -I/usr/local/include'
    stdchar='char', d_stdstdio=define, usevfork=false
    intsize=4, longsize=4, ptrsize=4, doublesize=8
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lndbm -lgdbm -ldbm -ldb -ldl -lm -lc -lposix -lcrypt
    libc=/lib/libc-2.1.2.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.5.650:
    /usr/local/lib/perl5/5.5.650/i686-linux
    /usr/local/lib/perl5/5.5.650
    /usr/local/lib/perl5/site_perl/5.5.650/i686-linux
    /usr/local/lib/perl5/site_perl/5.5.650
    /usr/local/lib/perl5/site_perl/5.005/i686-linux
    /usr/local/lib/perl5/site_perl/5.005
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.5.650:
    HOME=/home/jtobey
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/jtobey/bin:/jtobey/local/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/usr/local/sbin:/usr/sbin:/sbin
    PERL_BADLANG (unset)
    SHELL=/bin/bash


```
</details>
