### ISSUE TITLE
scope.c:529: Perl_save_clearsv: Assertion `(_svpad)->sv_flags & 0x00040000' failed.

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#12165]
Migrated from [rt.perl.org#113574](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=113574) (status was 'rejected')

Searchable as RT113574$

**Comment by p5pRT** [comment]
### From @daxim

#### Created by @daxim



crashes often under Devel&#8203;::REPL\, gdb backtrace&#8203;:

$ gdb perl
GNU gdb \(GDB\) SUSE \(7\.3\-41\.1\.2\)
Copyright \(C\) 2011 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-suse\-linux"\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.\.\.
Reading symbols from /home/daxim/local/share/perlbrew/perls/perl\-5\.16\.0/bin/perl\.\.\.done\.
\(gdb\) run \`which re\.pl\`
Starting program&#8203;: /home/daxim/local/share/perlbrew/perls/perl\-5\.16\.0/bin/perl \`which re\.pl\`
$ use ClassLoader; my $f = Archive&#8203;::Any\->new\("/"\)
perl&#8203;: scope\.c&#8203;:529&#8203;: Perl\_save\_clearsv&#8203;: Assertion \`\(\_svpad\)\->sv\_flags & 0x00040000' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff711bb25 in raise \(\) from /lib64/libc\.so\.6
\(gdb\) bt full
\#0  0x00007ffff711bb25 in raise \(\) from /lib64/libc\.so\.6
No symbol table info available\.
\#1  0x00007ffff711cf9b in abort \(\) from /lib64/libc\.so\.6
No symbol table info available\.
\#2  0x00007ffff71149fe in \_\_assert\_fail\_base \(\) from /lib64/libc\.so\.6
No symbol table info available\.
\#3  0x00007ffff7114aa2 in \_\_assert\_fail \(\) from /lib64/libc\.so\.6
No symbol table info available\.
\#4  0x0000000000550a6c in Perl\_save\_clearsv \(my\_perl=0x89c010\, svp=\<optimized out>\) at scope\.c&#8203;:529
&nbsp;        \_svpad = \<optimized out>
&nbsp;        offset = \<optimized out>
&nbsp;        offset\_shifted = \<optimized out>
&nbsp;        \_\_PRETTY\_FUNCTION\_\_ = "Perl\_save\_clearsv"
\#5  0x00000000004f9dc1 in Perl\_pp\_padsv \(my\_perl=0x89c010\) at pp\_hot\.c&#8203;:312
&nbsp;        sp = 0x246c690
&nbsp;        targ = 0x34b9648
\#6  0x00000000004bebe8 in Perl\_runops\_debug \(my\_perl=0x89c010\) at dump\.c&#8203;:2119
No locals\.
\#7  0x0000000000441410 in Perl\_call\_sv \(my\_perl=0x89c010\, sv=0x8d2b28\, flags=13\) at perl\.c&#8203;:2705
&nbsp;        sp = \<optimized out>
&nbsp;        myop = \{op\_next = 0x0\, op\_sibling = 0x0\, op\_ppaddr = 0\, op\_targ = 0\, op\_type = 0\, op\_opt = 0\, op\_latefree = 0\, op\_latefreed = 0\, op\_attached = 0\, op\_spare = 0\,
&nbsp;          op\_flags = 65 'A'\, op\_private = 0 '\\000'\, op\_first = 0x0\, op\_other = 0x7fffffffd0b0\}
&nbsp;        method\_op = \{op\_next = 0x0\, op\_sibling = 0x80\, op\_ppaddr = 0\, op\_targ = 210453397510\, op\_type = 91\, op\_opt = 0\, op\_latefree = 0\, op\_latefreed = 0\,
&nbsp;          op\_attached = 0\, op\_spare = 0\, op\_flags = 0 '\\000'\, op\_private = 0 '\\000'\, op\_first = 0x7c00000077\}
&nbsp;        oldmark = 0
&nbsp;        retval = 0
&nbsp;        oldscope = 4
&nbsp;        oldcatch = false
&nbsp;        ret = \<optimized out>
&nbsp;        oldop = 0x0
&nbsp;        cur\_env = \{je\_prev = 0x7fffffffd1b0\, je\_buf = \{\{\_\_jmpbuf = \{9251624\, \-8184946506956403117\, 9050128\, 140737488343216\, 1\, 0\, 8184946505334525523\,
&nbsp;                \-8184947021819802029\}\, \_\_mask\_was\_saved = 0\, \_\_saved\_mask = \{\_\_val = \{9251864\, 18446744073709551615\, 9027600\, 0\, 9029688\, 9027600\, 9251864\, 5\, 9251840\, 1\,
&nbsp;                  9027600\, 9288592\, 5\, 9251840\, 1\, 4330461\}\}\}\}\, je\_ret = 3\, je\_mustcatch = false\}
&nbsp;        \_\_PRETTY\_FUNCTION\_\_ = "Perl\_call\_sv"
\#8  0x0000000000441f07 in Perl\_call\_list \(my\_perl=0x89c010\, oldscope=2\, paramList=0x8d2c30\) at perl\.c&#8203;:4782
&nbsp;        atsv = \<optimized out>
&nbsp;        oldline = 3
&nbsp;        cv = 0x8d2b28
&nbsp;        len = 9251840
&nbsp;        ret = \<optimized out>
&nbsp;        cur\_env = \{je\_prev = 0x7fffffffd5d0\, je\_buf = \{\{\_\_jmpbuf = \{9027600\, \-8184945294299230637\, 9251624\, 2\, 1\, 0\, 8184946505426800211\, \-8184947021518860717\}\,
&nbsp;              \_\_mask\_was\_saved = 0\, \_\_saved\_mask = \{\_\_val = \{9047120\, 9047120\, 0\, 9251888\, 9251624\, 0\, 9027600\, 1\, 0\, 5143726\, 0\, 5281746\, 9251840\, 1\, 0\, 9029112\}\}\}\}\,
&nbsp;          je\_ret = 0\, je\_mustcatch = false\}
&nbsp;        \_\_PRETTY\_FUNCTION\_\_ = "Perl\_call\_list"
\#9  0x00000000004207e8 in S\_process\_special\_blocks \(my\_perl=0x89c010\, fullname=\<optimized out>\, gv=0x8d2c00\, cv=0x8d2b28\) at op\.c&#8203;:6882
&nbsp;        oldscope = 2
&nbsp;        colon = \<optimized out>
&nbsp;        name = \<optimized out>
&nbsp;        \_\_PRETTY\_FUNCTION\_\_ = "S\_process\_special\_blocks"
\#10 0x0000000000439228 in Perl\_newATTRSUB\_flags \(my\_perl=0x89c010\, floor=37\, o=\<optimized out>\, proto=\<optimized out>\, attrs=0x0\, block=0x8dbea0\, flags=0\) at op\.c&#8203;:6852
\-\-\-Type \<return> to continue\, or q \<return> to quit\-\-\-
&nbsp;        gv = \<optimized out>
&nbsp;        ps = \<optimized out>
&nbsp;        ps\_len = 0
&nbsp;        ps\_utf8 = 0
&nbsp;        cv = 0x8d2b28
&nbsp;        const\_sv = 0x0
&nbsp;        gv\_fetch\_flags = \<optimized out>
&nbsp;        namlen = 5
&nbsp;        o\_is\_gv = \<optimized out>
&nbsp;        name = \<optimized out>
&nbsp;        \_\_PRETTY\_FUNCTION\_\_ = "Perl\_newATTRSUB\_flags"
&nbsp;        has\_name = \<optimized out>
&nbsp;        name\_is\_utf8 = false
\#11 0x000000000043a050 in Perl\_newATTRSUB \(my\_perl=\<optimized out>\, floor=\<optimized out>\, o=\<optimized out>\, proto=\<optimized out>\, attrs=\<optimized out>\,
&nbsp;    block=\<optimized out>\) at op\.c&#8203;:6499
No locals\.
\#12 0x000000000043a482 in Perl\_utilize \(my\_perl=0x89c010\, aver=1\, floor=37\, version=\<optimized out>\, idop=0x8dab70\, arg=\<optimized out>\) at op\.c&#8203;:4681
&nbsp;        pack = \<optimized out>
&nbsp;        imop = \<optimized out>
&nbsp;        veop = \<optimized out>
&nbsp;        use\_version = 0x0
\#13 0x00000000004816b2 in Perl\_yyparse \(my\_perl=0x89c010\, gramtype=\<optimized out>\) at perly\.y&#8203;:363
&nbsp;        yystate = \<optimized out>
&nbsp;        yyn = 32
&nbsp;        yyresult = \<optimized out>
&nbsp;        yytoken = 20
&nbsp;        parser = 0x8d6df0
&nbsp;        ps = 0x8d7330
&nbsp;        yyval = \<optimized out>
&nbsp;        \_\_PRETTY\_FUNCTION\_\_ = "Perl\_yyparse"
\#14 0x00000000004464df in S\_parse\_body \(my\_perl=0x89c010\, env=0x0\, xsinit=0x420280 \<xs\_init>\) at perl\.c&#8203;:2246
&nbsp;        rsfp = 0x8bcb20
&nbsp;        argc = \<optimized out>
&nbsp;        argv = 0x7fffffffd810
&nbsp;        scriptname = \<optimized out>
&nbsp;        dosearch = false
&nbsp;        c = \<optimized out>
&nbsp;        doextract = \<optimized out>
&nbsp;        cddir = \<optimized out>
&nbsp;        linestr\_sv = 0x0
&nbsp;        add\_read\_e\_script = \<optimized out>
&nbsp;        lex\_start\_flags = 0
&nbsp;        \_\_PRETTY\_FUNCTION\_\_ = "S\_parse\_body"
\#15 0x0000000000447eba in perl\_parse \(my\_perl=0x89c010\, xsinit=0x420280 \<xs\_init>\, argc=2\, argv=\<optimized out>\, env=0x0\) at perl\.c&#8203;:1633
&nbsp;        oldscope = 1
&nbsp;        ret = 0
&nbsp;        cur\_env = \{je\_prev = 0x89c288\, je\_buf = \{\{\_\_jmpbuf = \{140737488345096\, \-8184946506956140973\, 9024520\, 0\, 0\, 0\, 8184946505535852115\, \-8184947022552756653\}\,
&nbsp;              \_\_mask\_was\_saved = 0\, \_\_saved\_mask = \{\_\_val = \{0\, 9083296\, 0\, 0\, 9027600\, 9027600\, 9042000\, 140737353799336\, 140737488345088\, 0\, 0\, 5281746\,
&nbsp;                  140737488345088\, 4988007\, 9027600\, 9027600\}\}\}\}\, je\_ret = 0\, je\_mustcatch = false\}
&nbsp;        \_\_PRETTY\_FUNCTION\_\_ = "perl\_parse"
\-\-\-Type \<return> to continue\, or q \<return> to quit\-\-\-
\#16 0x00000000004200db in main \(argc=2\, argv=0x7fffffffd808\, env=0x7fffffffd820\) at perlmain\.c&#8203;:118
&nbsp;        exitstatus = \<optimized out>
&nbsp;        i = \<optimized out>

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.16.0:

Configured by daxim at Tue May 22 09:09:52 CEST 2012.

Summary of my perl5 (revision 5 version 16 subversion 0) configuration:
   
  Platform:
    osname=linux, osvers=3.1.10-1.9-desktop, archname=x86_64-linux-thread-multi-ld
    uname='linux champion 3.1.10-1.9-desktop #1 smp preempt thu apr 5 18:48:38 utc 2012 (4a97ec8) x86_64 x86_64 x86_64 gnulinux '
    config_args='-de -Dprefix=/home/daxim/local/share/perlbrew/perls/perl-5.16.0 -DDEBUGGING -Dusemorebits -Dusethreads -Dcf_email=daxim@cpan.org -Dperladmin=daxim@cpan.org -Accflags=-fPIC'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=define, uselongdouble=define
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -fPIC -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2 -g',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fPIC -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.6.2', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='long double', nvsize=16, Off_t='off_t', lseeksize=8
    alignbytes=16, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib /lib/../lib64 /usr/lib/../lib64 /lib /usr/lib /lib64 /usr/lib64 /usr/local/lib64
    libs=-lnsl -lndbm -lgdbm -ldb -ldl -lm -lcrypt -lutil -lpthread -lc -lgdbm_compat
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
    libc=/lib/libc-2.15.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.15'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -g -L/usr/local/lib -fstack-protector'

Locally applied patches:
    


@INC for perl 5.16.0:
    /home/daxim/local/share/perlbrew/perls/perl-5.16.0/lib/site_perl/5.16.0/x86_64-linux-thread-multi-ld
    /home/daxim/local/share/perlbrew/perls/perl-5.16.0/lib/site_perl/5.16.0
    /home/daxim/local/share/perlbrew/perls/perl-5.16.0/lib/5.16.0/x86_64-linux-thread-multi-ld
    /home/daxim/local/share/perlbrew/perls/perl-5.16.0/lib/5.16.0
    .


Environment for perl 5.16.0:
    HOME=/home/daxim
    LANG=de_DE.UTF-8
    LANGUAGE=
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/daxim/local/share/perlbrew/bin:/home/daxim/local/share/perlbrew/perls/perl-5.16.0/bin:/home/daxim/local/bin:/opt/kde3/sbin:/sbin:/usr/sbin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/games:/opt/kde3/bin:/usr/lib64/jvm/jre/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/usr/lib/qt3/bin
    PERLBREW_BASHRC_VERSION=0.42
    PERLBREW_HOME=/home/daxim/.perlbrew
    PERLBREW_MANPATH=/home/daxim/local/share/perlbrew/perls/perl-5.16.0/man
    PERLBREW_PATH=/home/daxim/local/share/perlbrew/bin:/home/daxim/local/share/perlbrew/perls/perl-5.16.0/bin
    PERLBREW_PERL=perl-5.16.0
    PERLBREW_ROOT=/home/daxim/local/share/perlbrew
    PERLBREW_VERSION=0.42
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Jun 10\, 2012 at 11&#8203;:04&#8203;:17AM \-0700\, Lars DÉªá´á´á´á´á´¡ è¿ªææ¯ wrote&#8203;:
> crashes often under Devel&#8203;::REPL\, gdb backtrace&#8203;:

Thanks for the report\.

The assert and backtrace show that perl is somewhere in the middle of
executing a file loaded via 'use'\, and that it is just executing a
'my $foo' instruction\, but has discovered that the 'foo' in the relevant
pad slot isn't marked as being a lexical var\.

Other than that\, there's not a lot more that can be deduced\. Are you able
to supply a complete working test script that can reproduce the problem;
preferable one that is stripped down as far as possible\, and that has as
few external dependencies as possible?

\-\- 
The Enterprise is involved in a bizarre time\-warp experience which is in
some way unconnected with the Late 20th Century\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#14

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @daxim

I don't know how to strip this down\. I already asked on \#p5p for help\,
but got warnocked\.

&nbsp;    > perlbrew \-n \-v install perl\-5\.16\.0 \-\-as perl\-RT113574 \-DDEBUGGING
&nbsp;    \-Dusemorebits \-Dusethreads \-Dcf\_email=daxim@&#8203;cpan\.org
&nbsp;    \-Dperladmin=daxim@&#8203;cpan\.org \-Accflags=\-fPIC

&nbsp;    > perlbrew switch perl\-RT113574

&nbsp;    > cpanm \-n Devel&#8203;::REPL ClassLoader Archive&#8203;::Any File&#8203;::Next
&nbsp;    B&#8203;::Keywords Term&#8203;::ReadLine&#8203;::Gnu

&nbsp;    > re\.pl

&nbsp;    $ use ClassLoader; my $f = Archive&#8203;::Any\->new\("/"\)
&nbsp;    perl&#8203;: scope\.c&#8203;:529&#8203;: Perl\_save\_clearsv&#8203;: Assertion \`\(\_svpad\)\->sv\_flags
&nbsp;    & 0x00040000' failed\.
&nbsp;    Aborted

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Jun 11\, 2012 at 10&#8203;:09&#8203;:36PM \+0200\, Lars DÉªá´á´á´á´á´¡ è¿ªææ¯ wrote&#8203;:
> I don't know how to strip this down\. I already asked on \#p5p for help\,
> but got warnocked\.

Unless I'm missing something\, you haven't supplied the re\.pl test script
yet\. Even not stripped down\, that would be something to work with\.


\-\- 
Atheism is a religion like not collecting stamps is a hobby

**Comment by p5pRT** [comment]
### From @rurban

On Tue\, Jun 12\, 2012 at 7&#8203;:39 AM\, Dave Mitchell \<davem@&#8203;iabyn\.com> wrote&#8203;:
> On Mon\, Jun 11\, 2012 at 10&#8203;:09&#8203;:36PM \+0200\, Lars DÉªá´á´á´á´á´¡ è¿ªææ¯ wrote&#8203;:
>> I don't know how to strip this down\. I already asked on \#p5p for help\,
>> but got warnocked\.
>
> Unless I'm missing something\, you haven't supplied the re\.pl test script
> yet\. Even not stripped down\, that would be something to work with\.

Devel&#8203;::REPL installs it\.
It contains

use Devel&#8203;::REPL&#8203;::Script 'run'
\-\- 
Reini Urban
http&#8203;://cpanel\.net/ Â  http&#8203;://www\.perl\-compiler\.org/

**Comment by p5pRT** [comment]
### From @daxim

known bug in Devel&#8203;::LexAlias

https://rt.cpan.org/Ticket/Display.html?id=74862

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

known bug in Devel&#8203;::LexAlias

https://rt.cpan.org/Ticket/Display.html?id=74862

**Comment by p5pRT** [comment]
@daxim - Status changed from 'open' to 'rejected'
