### ISSUE TITLE
TryCatch toke error with (??{$any})  $ws \\] )? @

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#12290]
Migrated from [rt.perl.org#114242](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=114242) (status was 'resolved')

Searchable as RT114242$

**Comment by p5pRT** [comment]
### From @rurban


This is a bug report for perl from rurban@&#8203;cpanel\.net\,
generated with the help of perlbug 1\.39 running under perl 5\.17\.2\.




---
The toke\.c part for compiling a \(?\{\.\.\}\) expression creates an invalid string\.

The string "\(??\{$any\}\)  $ws \\\\\] \)? @&#8203;" which appears in TryCatch 
creates for
toke\.c&#8203;:
4702            NEXTVAL\_NEXTTOKE\.opval =
4703                \(OP\*\)newSVOP\(OP\_CONST\, 0\,
4704                newSVpvn\(PL\_sublex\_info\.re\_eval\_start\,
4705                    PL\_bufptr \- PL\_sublex\_info\.re\_eval\_start\)\);
a negative length&#8203;:
\(gdb\) p PL\_bufptr
$2 = 0x105f054 "  $ws \\\\\] \)? "
\(gdb\) p  PL\_sublex\_info
$3 = \{super\_state = 10 '\\n'\, sub\_inwhat = 31\, sub\_op = 0x1067f08\,
super\_bufptr = 0x0\, super\_bufend = 0x0\, 
&nbsp;  re\_eval\_start = 0x10655fa "\(??\{$any\}\)  $ws \\\\\] \)? @&#8203;"\}

repro&#8203;:
gdb \-\-args /usr/local/bin/perl5\.17\.2d\-nt \-Mblib t/invalid\.t
\(gdb\) b sv\.c&#8203;:4469
\# panic&#8203;: sv\_setpvn called with negative strlen
\(gdb\) bt
\#0  Perl\_sv\_setpvn \(sv=0x1069db0\, ptr=0x10655fa "\(??\{$any\}\)  $ws \\\\\] \)? @&#8203;"\,
\#len=18446744073709525594\) at sv\.c&#8203;:4469
\#1  0x00007ffff7bc77d3 in Perl\_newSVpvn \(buffer=0x10655fa "\(??\{$any\}\)  $ws
\#\\\\\] \)? @&#8203;"\, len=18446744073709525594\) at sv\.c&#8203;:8400
\#2  0x00007ffff7a7ad42 in Perl\_yylex \(\) at toke\.c&#8203;:4703
\#3  0x00007ffff7aac794 in Perl\_yyparse \(gramtype=258\) at perly\.c&#8203;:334
\#4  0x00007ffff7c35a5c in S\_doeval \(gimme=2\, outside=0x0\, seq=6541\, hh=0x0\)
\#at pp\_ctl\.c&#8203;:3449
\#5  0x00007ffff7c3c671 in Perl\_pp\_require \(\) at pp\_ctl\.c&#8203;:4003
\(gdb\) up 2
\.\.\.



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=high


---
Site configuration information for perl 5\.17\.2&#8203;:

Configured by rurban at Fri Jul 20 13&#8203;:46&#8203;:41 CDT 2012\.

Summary of my perl5 \(revision 5 version 17 subversion 2\) configuration&#8203;:
&nbsp;   
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.2\.0\-2\-amd64\, archname=x86\_64\-linux\-debug
&nbsp;    uname='linux reini 3\.2\.0\-2\-amd64 \#1 smp mon may 21 17&#8203;:45&#8203;:41 utc 2012 x86\_64 gnulinux '
&nbsp;    config\_args='\-de \-Dusedevel \-Dinstallman1dir=none \-Dinstallman3dir=none \-Dinstallsiteman1dir=none \-Dinstallsiteman3dir=none \-DEBUGGING \-Doptimize=\-g3 \-Uuseithreads \-Accflags='\-msse4\.2' \-Accflags='\-march=corei7' \-Dcf\_email='rurban@&#8203;cpanel\.net' \-Dperladmin='rurban@&#8203;cpanel\.net' \-Duseshrplib'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-msse4\.2 \-march=corei7 \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g3'\,
&nbsp;    cppflags='\-msse4\.2 \-march=corei7 \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.7\.1'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lc \-lgdbm\_compat
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=\, so=so\, useshrplib=true\, libperl=libperl\.so
&nbsp;    gnulibc\_version='2\.13'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E \-Wl\,\-rpath\,/usr/local/lib/perl5/5\.17\.2/x86\_64\-linux\-debug/CORE'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g3 \-L/usr/local/lib \-fstack\-protector'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl 5\.17\.2&#8203;:
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.17\.2/x86\_64\-linux\-debug
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.17\.2
&nbsp;    /usr/local/lib/perl5/5\.17\.2/x86\_64\-linux\-debug
&nbsp;    /usr/local/lib/perl5/5\.17\.2
&nbsp;    /usr/local/lib/perl5/site\_perl
&nbsp;    \.



---
Environment for perl 5\.17\.2&#8203;:
&nbsp;    HOME=/home/rurban
&nbsp;    LANG=en\_US\.UTF\-8
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/rurban/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/local/games&#8203;:/usr/games
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Jul 23\, 2012 at 07&#8203;:21&#8203;:27AM \-0700\, rurban@&#8203;cpanel\.net wrote&#8203;:
> The toke\.c part for compiling a \(?\{\.\.\}\) expression creates an invalid string\.
> 
> The string "\(??\{$any\}\)  $ws \\\\\] \)? @&#8203;" which appears in TryCatch 
> creates for
> toke\.c&#8203;:
> 4702            NEXTVAL\_NEXTTOKE\.opval =
> 4703                \(OP\*\)newSVOP\(OP\_CONST\, 0\,
> 4704                newSVpvn\(PL\_sublex\_info\.re\_eval\_start\,
> 4705                    PL\_bufptr \- PL\_sublex\_info\.re\_eval\_start\)\);
> a negative length&#8203;:

Fixed with the following&#8203;:


commit c76419315df6965e6d8ba598dad9a8d5169b5859
Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
AuthorDate&#8203;: Tue Jul 24 15&#8203;:11&#8203;:29 2012 \+0100
Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
CommitDate&#8203;: Tue Jul 24 15&#8203;:17&#8203;:42 2012 \+0100

&nbsp;    lex\_grow\_linestr\(\)&#8203;: update re\_eval\_start
&nbsp;    
&nbsp;    As seen in \[perl \#114242\]\, the TryCatch test suite triggers this bug\.
&nbsp;    lex\_grow\_linestr\(\) was reallocing the PL\_linestr buffer and updating all
&nbsp;    pointers within it\, but was failing to update
&nbsp;    PL\_sublex\_info\.re\_eval\_start\.
&nbsp;    
&nbsp;    Unfortunately\, lex\_grow\_linestr\(\) doesn't seem to be used in core outside
&nbsp;    of hereto docs\, and due to a separate parser bug\, hereto docs can't
&nbsp;    currently be used within /\(?\{\}\)/\, so I can't add tests for it yet\.

\-\- 
Any \[programming\] language that doesn't occasionally surprise the
novice will pay for it by continually surprising the expert\.
&nbsp;   \-\- Larry Wall

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @rurban

On Tue\, Jul 24\, 2012 at 9&#8203;:20 AM\, Dave Mitchell \<davem@&#8203;iabyn\.com> wrote&#8203;:
> On Mon\, Jul 23\, 2012 at 07&#8203;:21&#8203;:27AM \-0700\, rurban@&#8203;cpanel\.net wrote&#8203;:
>> The toke\.c part for compiling a \(?\{\.\.\}\) expression creates an invalid string\.
>>
>> The string "\(??\{$any\}\)  $ws \\\\\] \)? @&#8203;" which appears in TryCatch
>> creates for
>> toke\.c&#8203;:
>> 4702              NEXTVAL\_NEXTTOKE\.opval =
>> 4703                      \(OP\*\)newSVOP\(OP\_CONST\, 0\,
>> 4704                          newSVpvn\(PL\_sublex\_info\.re\_eval\_start\,
>> 4705                                  PL\_bufptr \- PL\_sublex\_info\.re\_eval\_start\)\);
>> a negative length&#8203;:
>
> Fixed with the following&#8203;:
>
>
> commit c76419315df6965e6d8ba598dad9a8d5169b5859
> Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
> AuthorDate&#8203;: Tue Jul 24 15&#8203;:11&#8203;:29 2012 \+0100
> Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
> CommitDate&#8203;: Tue Jul 24 15&#8203;:17&#8203;:42 2012 \+0100
>
>     lex\_grow\_linestr\(\)&#8203;: update re\_eval\_start
>
>     As seen in \[perl \#114242\]\, the TryCatch test suite triggers this bug\.
>     lex\_grow\_linestr\(\) was reallocing the PL\_linestr buffer and updating all
>     pointers within it\, but was failing to update
>     PL\_sublex\_info\.re\_eval\_start\.
>
>     Unfortunately\, lex\_grow\_linestr\(\) doesn't seem to be used in core outside
>     of hereto docs\, and due to a separate parser bug\, hereto docs can't
>     currently be used within /\(?\{\}\)/\, so I can't add tests for it yet\.

Fix confirmed\.
Thanks\!

ASH/TryCatch\-1\.003000\.tar\.gz
All tests successful\.
Files=10\, Tests=58\, 11 wallclock secs \( 0\.08 usr  0\.01 sys \+  9\.58
cusr  0\.36 csys = 10\.03 CPU\)

PS&#8203;: I don't think allowing heredoc inside /\(?\{\}\)/ would be a good
idea\, so I'm quite comfortable with the current state\.
A possible testcase could be constructed with XS&#8203;::APItest I assume\.
But I fail to understand this module\.
\-\- 
Reini Urban
http&#8203;://cpanel\.net/   http&#8203;://www\.perl\-compiler\.org/

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
