### ISSUE TITLE
perl -DA -e '' segfaults

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#12314]
Migrated from [rt.perl.org#114368](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=114368) (status was 'resolved')

Searchable as RT114368$

**Comment by p5pRT** [comment]
### From @mauke

#### Created by @mauke



% perl \-DA \-e ''   

EXECUTING\.\.\.

zsh&#8203;: segmentation fault  perl \-DA \-e ''

% gdb \-\-args perl \-DA \-e ''
GNU gdb \(Gentoo 7\.3\.1 p2\) 7\.3\.1
Copyright \(C\) 2011 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "i686\-pc\-linux\-gnu"\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://bugs\.gentoo\.org/>\.\.\.
Reading symbols from /home/mauke/usr/perlbrew/perls/5\.16\.0\-debug/bin/perl\.\.\.done\.
\(gdb\) r
Starting program&#8203;: /home/mauke/usr/perlbrew/perls/5\.16\.0\-debug/bin/perl \-DA \-e ''

EXECUTING\.\.\.


Program received signal SIGSEGV\, Segmentation fault\.
S\_mg\_findext\_flags \(sv=\<optimized out>\, type=37\, vtbl=0x0\, flags=0\) at mg\.c&#8203;:395
395                 if \(mg\->mg\_type == type && \(\!flags || mg\->mg\_virtual == vtbl\)\) \{
\(gdb\) bt
\#0  S\_mg\_findext\_flags \(sv=\<optimized out>\, type=37\, vtbl=0x0\, flags=0\) at mg\.c&#8203;:395
\#1  0x08101a85 in Perl\_mg\_find \(sv=0x82a7f38\, type=37\) at mg\.c&#8203;:415
\#2  0x08116d60 in Perl\_hv\_placeholders\_get \(hv=0x82a7f38\) at hv\.c&#8203;:2821
\#3  0x0811b07e in Perl\_hv\_assert \(hv=0x82a7f38\) at hv\.c&#8203;:3485
\#4  0x0811b38b in Perl\_hv\_undef\_flags \(hv=0x82a7f38\, flags=2\) at hv\.c&#8203;:1792
\#5  0x0813bcf4 in Perl\_sv\_clear \(orig\_sv=0x82a7f38\) at sv\.c&#8203;:6295
\#6  0x0813bea1 in Perl\_sv\_free2 \(sv=0x82a7f38\) at sv\.c&#8203;:6507
\#7  0x08084945 in perl\_destruct \(my\_perl=0x82a5008\) at perl\.c&#8203;:793
\#8  0x0806504a in main \(argc=4\, argv=0xbfffe574\, env=0xbfffe588\) at perlmain\.c&#8203;:131
\(gdb\) p mg
$1 = \(MAGIC \*\) 0x42
\(gdb\) 

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

This perlbug was built using Perl 5.12.1 - Thu Jun  3 20:09:15 CEST 2010
It is being executed now by  Perl 5.16.0 - Mon May 21 12:24:16 CEST 2012.

Site configuration information for perl 5.16.0:

Configured by mauke at Mon May 21 12:24:16 CEST 2012.

Summary of my perl5 (revision 5 version 16 subversion 0) configuration:
   
  Platform:
    osname=linux, osvers=2.6.38-gentoo-r6, archname=i686-linux
    uname='linux nora 2.6.38-gentoo-r6 #1 preempt sat aug 6 03:05:34 cest 2011 i686 amd athlon(tm) 64 processor 3200+ authenticamd gnulinux '
    config_args='-Dcc=cgcc -Dprefix=/home/mauke/usr/local -Dman1dir=none -Dman3dir=none -Dinc_version_list=none -Doptimize=-O2 -flto'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=undef, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cgcc', ccflags ='-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2 -flto',
    cppflags='-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.6.3', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cgcc', ldflags ='-fstack-protector -L/usr/local/lib -O2 -flto'
    libpth=/usr/local/lib /lib/../lib /usr/lib/../lib /lib /usr/lib
    libs=-lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/libc-2.14.1.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.14.1'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -flto -L/usr/local/lib -fstack-protector'

Locally applied patches:
    SAVEARGV0 - disable magic open in <ARGV>


@INC for perl 5.16.0:
    /home/mauke/usr/local/lib/perl5/site_perl/5.16.0/i686-linux
    /home/mauke/usr/local/lib/perl5/site_perl/5.16.0
    /home/mauke/usr/local/lib/perl5/5.16.0/i686-linux
    /home/mauke/usr/local/lib/perl5/5.16.0
    .


Environment for perl 5.16.0:
    HOME=/home/mauke
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_COLLATE=POSIX
    LD_LIBRARY_PATH=/home/mauke/usr/local/lib
    LOGDIR (unset)
    PATH=/home/mauke/usr/perlbrew/bin:/home/mauke/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/i686-pc-linux-gnu/gcc-bin/4.4.5:/opt/sun-jdk-1.4.2.13/bin:/opt/sun-jdk-1.4.2.13/jre/bin:/opt/sun-jdk-1.4.2.13/jre/javaws:/opt/dmd/bin:/usr/games/bin
    PERLBREW_BASHRC_VERSION=0.43
    PERLBREW_HOME=/home/mauke/.perlbrew
    PERLBREW_PATH=/home/mauke/usr/perlbrew/bin
    PERLBREW_ROOT=/home/mauke/usr/perlbrew
    PERLBREW_VERSION=0.27
    PERL_BADLANG (unset)
    PERL_UNICODE=SAL
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @cpansprout

Fixed by a444d2d4f3777a\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
