### ISSUE TITLE
cond_signal does not wake up a thread

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#12316]
Migrated from [rt.perl.org#114378](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=114378) (status was 'rejected')

Searchable as RT114378$

**Comment by p5pRT** [comment]
### From matti.linnanvuori@portalify.com

#### Created by matti@portalify.com



cond\_signal does not wake another thread up even though I think it should\.
The same problem appears in perl 5\.10\.0 in SLES 11 SP1\.
The main thread joins the other thread forever&#8203;:

8/2/12 12&#8203;:19&#8203;:01\.930 PM aplicom&#8203;: Failed to receive data from the socket&#8203;: Interrupted system call
8/2/12 12&#8203;:19&#8203;:01\.930 PM aplicom&#8203;: Closing the socket
8/2/12 12&#8203;:19&#8203;:01\.930 PM aplicom&#8203;: Killing the post thread
8/2/12 12&#8203;:19&#8203;:01\.931 PM aplicom&#8203;: Locking to signal termination
8/2/12 12&#8203;:19&#8203;:01\.931 PM aplicom&#8203;: Signaling the post thread to terminate
8/2/12 12&#8203;:19&#8203;:01\.931 PM aplicom&#8203;: Joining the post thread

sub post \{
&nbsp;    $SIG\{'TERM'\} = \\&termination\_flag;

&nbsp;    my $ua = LWP&#8203;::UserAgent\->new;
&nbsp;    $ua\->timeout\( $configuration\->\{'timeout'\} \);

&nbsp;    while \($run\) \{
&nbsp;        my %post;
&nbsp;        \{
&nbsp;            syslog LOG\_DEBUG\, "Locking to check for new location GeoJSON data";
&nbsp;            lock %location;
&nbsp;            until \( %location or not $run \) \{
&nbsp;                syslog LOG\_DEBUG\, "Waiting for location GeoJSON data";
&nbsp;                cond\_wait %location;
&nbsp;            \}
&nbsp;            %post = %location;
&nbsp;        \}
&nbsp;        if \(%post\) \{
&nbsp;            my %feature;
&nbsp;            while \( my \( $id\, $feature \) = each %post \) \{
&nbsp;                $feature\{$id\} = encode\_json $feature;
&nbsp;            \}
&nbsp;            my $content = '\{"type"&#8203;:"FeatureCollection"\,"features"&#8203;:\['
&nbsp;              \. join\( '\,'\, values %feature \) \. '\]\}';
&nbsp;            syslog LOG\_INFO\, "Posting location data $content";
&nbsp;            my $response = $ua\->post\(
&nbsp;                $configuration\->\{'url'\}\,
&nbsp;                'Content\-Type' => 'application/json'\,
&nbsp;                'Content'      => $content
&nbsp;            \);

&nbsp;            if \( $response\->is\_success \) \{
&nbsp;                syslog LOG\_INFO\,  $response\->as\_string;
&nbsp;                syslog LOG\_DEBUG\, "Locking to delete the posted location data";
&nbsp;                lock %location;
&nbsp;                while \( my \( $id\, $feature \) = each %location \) \{
&nbsp;                    if \( $feature\{$id\} eq encode\_json $feature \) \{
&nbsp;                        delete $location\{$id\};
&nbsp;                    \}
&nbsp;                \}
&nbsp;            \}
&nbsp;            else \{
&nbsp;                syslog LOG\_WARNING\, $response\->as\_string;
&nbsp;                sleep $run \* $configuration\->\{'retry'\};
&nbsp;            \}
&nbsp;        \}
&nbsp;    \}
&nbsp;    syslog LOG\_NOTICE\, "The post subroutine terminating";
\}

until \( $thread = threads\->create\('post'\) or not $run \) \{
&nbsp;    syslog LOG\_ERR\, "Failed to create the post thread&#8203;: $\!\. Retrying";
&nbsp;    sleep $run \* $configuration\->\{'retry'\};
\}

if \( defined $thread \) \{
&nbsp;    syslog LOG\_NOTICE\, "Killing the post thread";
&nbsp;    $thread\->kill\('SIGTERM'\);
\}

syslog LOG\_NOTICE\, "Locking to signal termination";
lock %location;
syslog LOG\_NOTICE\, "Signaling the post thread to terminate";
cond\_signal %location;

if \( defined $thread \) \{
&nbsp;    syslog LOG\_NOTICE\, "Joining the post thread";
&nbsp;    $thread\->join\(\);
\}


GNU gdb 6\.3\.50\-20050815 \(Apple version gdb\-1752\) \(Sat Jan 28 03&#8203;:02&#8203;:46 UTC 2012\)
Copyright 2004 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and you are
welcome to change it and/or distribute copies of it under certain conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for details\.
This GDB was configured as "x86\_64\-apple\-darwin"\.
\(gdb\) attach 363
NRkm\.\!28DQ
Attaching to process 363\.
Reading symbols for shared libraries \. done
Reading symbols for shared libraries \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\. done
Reading symbols for shared libraries \+ done
0x00007fff960ffe42 in \_\_semwait\_signal \(\)
\(gdb\) NRkm\.\!28DQ
Undefined command&#8203;: "NRkm"\.  Try "help"\.
\(gdb\) bt
\#0  0x00007fff960ffe42 in \_\_semwait\_signal \(\)
\#1  0x00007fff93bec97e in pthread\_join \(\)
\#2  0x000000010d0f2def in XS\_threads\_join \(\)
\#3  0x000000010cfe7a9c in Perl\_pp\_entersub \(\)
\#4  0x000000010cfe5ec8 in Perl\_runops\_standard \(\)
\#5  0x000000010cf8ce51 in perl\_run \(\)
\#6  0x000000010cf74d32 in main \(\)
\(gdb\) thread 1
\[Switching to thread 1 \(process 363\)\, "com\.apple\.main\-thread"\]
0x00007fff960ffe42 in \_\_semwait\_signal \(\)
\(gdb\) bt
\#0  0x00007fff960ffe42 in \_\_semwait\_signal \(\)
\#1  0x00007fff93bec97e in pthread\_join \(\)
\#2  0x000000010d0f2def in XS\_threads\_join \(\)
\#3  0x000000010cfe7a9c in Perl\_pp\_entersub \(\)
\#4  0x000000010cfe5ec8 in Perl\_runops\_standard \(\)
\#5  0x000000010cf8ce51 in perl\_run \(\)
\#6  0x000000010cf74d32 in main \(\)
\(gdb\) thread 2
\[Switching to thread 2 \(process 363\)\]
0x00007fff960ffbca in \_\_psynch\_cvwait \(\)
\(gdb\) bt
\#0  0x00007fff960ffbca in \_\_psynch\_cvwait \(\)
\#1  0x00007fff93c3a274 in \_pthread\_cond\_wait \(\)
\#2  0x000000010d23de78 in XS\_threads\_\_shared\_cond\_wait \(\)
\#3  0x000000010cfe7a9c in Perl\_pp\_entersub \(\)
\#4  0x000000010cfe5ec8 in Perl\_runops\_standard \(\)
\#5  0x000000010cf8c6af in Perl\_call\_sv \(\)
\#6  0x000000010d0f512b in ithread\_mg\_free \(\)
\#7  0x00007fff93c368bf in \_pthread\_start \(\)
\#8  0x00007fff93c39b75 in thread\_start \(\)
\(gdb\) 

<details><summary>Perl Info</summary>

```

Flags:
    category=library
    severity=medium
    module=threads::shared

Site configuration information for perl 5.12.3:

Configured by _mdnsresponder at Wed May 25 17:39:19 PDT 2011.

Summary of my perl5 (revision 5 version 12 subversion 3) configuration:
   
  Platform:
    osname=darwin, osvers=11.0, archname=darwin-thread-multi-2level
    uname='darwin doublemagnum.apple.com 11.0 darwin kernel version 11.0.0: wed dec 22 11:00:23 pst 2010; root:xnu-1699.18.1~1release_x86_64 x86_64 '
    config_args='-ds -e -Dprefix=/usr -Dccflags=-g  -pipe  -Dldflags= -Dman3ext=3pm -Duseithreads -Duseshrplib -Dinc_version_list=none -Dcc=llvm-gcc-4.2'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='llvm-gcc-4.2', ccflags ='-arch x86_64 -arch i386 -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -I/usr/local/include',
    optimize='-Os',
    cppflags='-g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='llvm-gcc-4.2 -mmacosx-version-min=10.7', ldflags ='-arch x86_64 -arch i386 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib
    libs=-ldbm -ldl -lm -lutil -lc
    perllibs=-ldl -lm -lutil -lc
    libc=, so=dylib, useshrplib=true, libperl=libperl.dylib
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=bundle, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags='-arch x86_64 -arch i386 -bundle -undefined dynamic_lookup -L/usr/local/lib -fstack-protector'

Locally applied patches:
    /Library/Perl/Updates/<version> comes before system perl directories
    installprivlib and installarchlib points to the Updates directory


@INC for perl 5.12.3:
    /Library/Perl/5.12/darwin-thread-multi-2level
    /Library/Perl/5.12
    /Network/Library/Perl/5.12/darwin-thread-multi-2level
    /Network/Library/Perl/5.12
    /Library/Perl/Updates/5.12.3/darwin-thread-multi-2level
    /Library/Perl/Updates/5.12.3
    /System/Library/Perl/5.12/darwin-thread-multi-2level
    /System/Library/Perl/5.12
    /System/Library/Perl/Extras/5.12/darwin-thread-multi-2level
    /System/Library/Perl/Extras/5.12
    .


Environment for perl 5.12.3:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/matti
    LANG (unset)
    LANGUAGE (unset)
    LC_CTYPE=UTF-8
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/usr/local/git/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash




```
</details>

**Comment by p5pRT** [comment]
### From mattilinnanvuori@yahoo.com

This a deadlock because the killing thread holds a lock while joining\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

This a deadlock because the killing thread holds a lock while joining\.

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Aug 02\, 2012 at 02&#8203;:36&#8203;:34AM \-0700\, Matti Linnanvuori wrote&#8203;:
> cond\_signal does not wake another thread up even though I think it should\.
> The same problem appears in perl 5\.10\.0 in SLES 11 SP1\.
> The main thread joins the other thread forever&#8203;:

Its difficult to say for certain\, since you don't provide complete code\,
but it looks like the fault is here&#8203;:

> lock %location;
> syslog LOG\_NOTICE\, "Signaling the post thread to terminate";
> cond\_signal %location;
> 
> if \( defined $thread \) \{
>     syslog LOG\_NOTICE\, "Joining the post thread";
>     $thread\->join\(\);
> \}

You don't unlock %location before trying to join the thread\. Note that
cond\_signal\(\) itself does not unlock the variable \(and so cond\_wait\(\)
hangs trying to relock the var\)\.

So you probably need to wrap the lock and cond\_signal lines above in a
\{\.\.\. \} block\, so that the lock is released before attempting to join

As a more general comment\, I'd recommend try to avoid using cond\_wait and
cond\_signal wherever possible\. They are a very low\-level interface\, and
are notoriously hard to get right\. Use something higher level&#8203;: often
a simple perl\-level lock is sufficient \(it uses condition variables under
the hood to ensure that a process waiting on a lock gets woken up\)\,
or possibly something like Thread&#8203;::Queue\.

\-\- 
This is a great day for France\!
&nbsp;    \-\- Nixon at Charles De Gaulle's funeral

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From mattilinnanvuori@yahoo.com

The bug was indeed in that the joining thread held the lock while the thread being joined waited 
for the same lock in cond\_wait\. So this is not such a Perl bug\, even though the warning that 
cond\_wait emits when used on an unlocked variable contributed to the bug\, so the Perl 
specification is partly to blame\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

The bug was indeed in that the joining thread held the lock while the thread being joined waited 
for the same lock in cond\_wait\. So this is not such a Perl bug\, even though the warning that 
cond\_wait emits when used on an unlocked variable contributed to the bug\, so the Perl 
specification is partly to blame\.

**Comment by p5pRT** [comment]
### From mattilinnanvuori@yahoo.com

What I meant that if Perl did not emit a warning when calling cond\_signal on an unlocked 
variable\, I would not have locked the variable and so the bug would not have been written\. The 
no warnings 'threads' to avoid the warning seems such an unclean hack\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

What I meant that if Perl did not emit a warning when calling cond\_signal on an unlocked 
variable\, I would not have locked the variable and so the bug would not have been written\. The 
no warnings 'threads' to avoid the warning seems such an unclean hack\.

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Aug 02\, 2012 at 10&#8203;:21&#8203;:24PM \-0700\, Matti Linnanvuori via RT wrote&#8203;:
> What I meant that if Perl did not emit a warning when calling cond\_signal on an unlocked 
> variable\, I would not have locked the variable and so the bug would not have been written\. The 
> no warnings 'threads' to avoid the warning seems such an unclean hack\.

I think you misunderstand\. For correct use of cond\_signal\, you \*must\* hold
the lock first\(\*\)\, so perl's warning is correct\. Your mistake was in not
subsequently unlocking the var\.

\* because otherwise you can't be sure that the other thread has yet
reached cond\_wait\(\)\, so the signal could get lost and deadlock ensue\.
Which is another reason why you should avoid cond\_wait/signal for most
code\. It's too hard to get right\.

\-\- 
"There's something wrong with our bloody ships today\, Chatfield\."
&nbsp;    \-\- Admiral Beatty at the Battle of Jutland\, 31st May 1916\.

**Comment by p5pRT** [comment]
### From @dcollinsn

On Fri Aug 03 03&#8203;:09&#8203;:02 2012\, davem wrote&#8203;:
> I think you misunderstand\. For correct use of cond\_signal\, you \*must\*
> hold
> the lock first\(\*\)\, so perl's warning is correct\. Your mistake was in
> not
> subsequently unlocking the var\.

Closing as not a bug\.

\-\- 
Respectfully\,
Dan Collins

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Fri Aug 03 03&#8203;:09&#8203;:02 2012\, davem wrote&#8203;:
> I think you misunderstand\. For correct use of cond\_signal\, you \*must\*
> hold
> the lock first\(\*\)\, so perl's warning is correct\. Your mistake was in
> not
> subsequently unlocking the var\.

Closing as not a bug\.

\-\- 
Respectfully\,
Dan Collins

**Comment by p5pRT** [comment]
@dcollinsn - Status changed from 'open' to 'rejected'
