### ISSUE TITLE
crash with invalid free in regex engine

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#12568]
Migrated from [rt.perl.org#115752](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=115752) (status was 'resolved')

Searchable as RT115752$

**Comment by p5pRT** [comment]
### From @mauke

#### Created by @mauke



$ cat irc\.pl
\#\!/usr/bin/perl
use warnings;
use strict;

for my $num \('4000752057698530'\, '4000608912607415'\, '4000966220145415'\) \{
&nbsp;    my $tmp = $num;
&nbsp;    my $x;
&nbsp;    $tmp =~ s/^\(\.\{6\}\)\(\.\*?\)\(?\{ $x = $^N; $x =~ s\{\.\}\{%\}g; \}\)\(\.\{4\}\)$/$1\#$2/;
\}
\_\_END\_\_
$ perl irc\.pl
Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\) line 1\.
Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\) line 1\.
Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\) line 1\.
Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\) line 1\.
Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\) line 1\.
Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\) line 1\.
Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\) line 1\.
\*\*\* glibc detected \*\*\* perl&#8203;: double free or corruption \(fasttop\)&#8203;: 0x08708f68 \*\*\*
======= Backtrace&#8203;: =========
/lib/i686/cmov/libc\.so\.6\(\+0x6af71\)\[0xb7585f71\]
/lib/i686/cmov/libc\.so\.6\(\+0x6c7c8\)\[0xb75877c8\]
/lib/i686/cmov/libc\.so\.6\(cfree\+0x6d\)\[0xb758a8ad\]
perl\(Perl\_regexec\_flags\+0x6c3\)\[0x81368d3\]
======= Memory map&#8203;: ========
08048000\-0818c000 r\-xp 00000000 08&#8203;:01 9979965    /home/mauke/usr/bin/perl
0818c000\-0818f000 rw\-p 00144000 08&#8203;:01 9979965    /home/mauke/usr/bin/perl
086de000\-08720000 rw\-p 00000000 00&#8203;:00 0          \[heap\]
b7200000\-b7221000 rw\-p 00000000 00&#8203;:00 0 
b7221000\-b7300000 \-\-\-p 00000000 00&#8203;:00 0 
b738a000\-b73a3000 r\-xp 00000000 08&#8203;:01 9978052    /home/mauke/usr/lib/libgcc\_s\.so\.1
b73a3000\-b73a4000 rw\-p 00019000 08&#8203;:01 9978052    /home/mauke/usr/lib/libgcc\_s\.so\.1
b73a4000\-b7519000 r\-\-p 00000000 08&#8203;:01 6710221    /usr/lib/locale/locale\-archive
b7519000\-b751b000 rw\-p 00000000 00&#8203;:00 0 
b75da000\-b771a000 r\-xp 00000000 08&#8203;:01 4923415    /lib/i686/cmov/libc\-2\.11\.3\.so
b771a000\-b771b000 \-\-\-p 00140000 08&#8203;:01 4923415    /lib/i686/cmov/libc\-2\.11\.3\.so
b771b000\-b771d000 r\-\-p 00140000 08&#8203;:01 4923415    /lib/i686/cmov/libc\-2\.11\.3\.so
b771d000\-b771e000 rw\-p 00142000 08&#8203;:01 4923415    /lib/i686/cmov/libc\-2\.11\.3\.so
b771e000\-b7721000 rw\-p 00000000 00&#8203;:00 0 
b7721000\-b7723000 r\-xp 00000000 08&#8203;:01 4923406    /lib/i686/cmov/libutil\-2\.11\.3\.so
b7723000\-b7724000 r\-\-p 00001000 08&#8203;:01 4923406    /lib/i686/cmov/libutil\-2\.11\.3\.so
b7724000\-b7725000 rw\-p 00002000 08&#8203;:01 4923406    /lib/i686/cmov/libutil\-2\.11\.3\.so
b7725000\-b772e000 r\-xp 00000000 08&#8203;:01 4923400    /lib/i686/cmov/libcrypt\-2\.11\.3\.so
b772e000\-b772f000 r\-\-p 00008000 08&#8203;:01 4923400    /lib/i686/cmov/libcrypt\-2\.11\.3\.so
b772f000\-b7730000 rw\-p 00009000 08&#8203;:01 4923400    /lib/i686/cmov/libcrypt\-2\.11\.3\.so
b7730000\-b7757000 rw\-p 00000000 00&#8203;:00 0 
b7757000\-b777b000 r\-xp 00000000 08&#8203;:01 4923397    /lib/i686/cmov/libm\-2\.11\.3\.so
b777b000\-b777c000 r\-\-p 00023000 08&#8203;:01 4923397    /lib/i686/cmov/libm\-2\.11\.3\.so
b777c000\-b777d000 rw\-p 00024000 08&#8203;:01 4923397    /lib/i686/cmov/libm\-2\.11\.3\.so
b777d000\-b777e000 rw\-p 00000000 00&#8203;:00 0 
b777e000\-b7780000 r\-xp 00000000 08&#8203;:01 4923396    /lib/i686/cmov/libdl\-2\.11\.3\.so
b7780000\-b7781000 r\-\-p 00001000 08&#8203;:01 4923396    /lib/i686/cmov/libdl\-2\.11\.3\.so
b7781000\-b7782000 rw\-p 00002000 08&#8203;:01 4923396    /lib/i686/cmov/libdl\-2\.11\.3\.so
b7782000\-b7795000 r\-xp 00000000 08&#8203;:01 4923399    /lib/i686/cmov/libnsl\-2\.11\.3\.so
b7795000\-b7796000 r\-\-p 00012000 08&#8203;:01 4923399    /lib/i686/cmov/libnsl\-2\.11\.3\.so
b7796000\-b7797000 rw\-p 00013000 08&#8203;:01 4923399    /lib/i686/cmov/libnsl\-2\.11\.3\.so
b7797000\-b7799000 rw\-p 00000000 00&#8203;:00 0 
b77a4000\-b77ab000 r\-\-s 00000000 08&#8203;:01 6694164    /usr/lib/gconv/gconv\-modules\.cache
b77ab000\-b77ad000 rw\-p 00000000 00&#8203;:00 0 
b77ad000\-b77ae000 r\-xp 00000000 00&#8203;:00 0          \[vdso\]
b77ae000\-b77c9000 r\-xp 00000000 08&#8203;:01 4907447    /lib/ld\-2\.11\.3\.so
b77c9000\-b77ca000 r\-\-p 0001b000 08&#8203;:01 4907447    /lib/ld\-2\.11\.3\.so
b77ca000\-b77cb000 rw\-p 0001c000 08&#8203;:01 4907447    /lib/ld\-2\.11\.3\.so
bfdc2000\-bfdd7000 rw\-p 00000000 00&#8203;:00 0          \[stack\]
Aborted
$ MALLOC\_CHECK\_=2 gdb \-\-args ~/perl5/perlbrew/perls/perl\-5\.16\.1\-d/bin/perl irc\.pl
GNU gdb \(GDB\) 7\.0\.1\-debian
Copyright \(C\) 2009 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "i486\-linux\-gnu"\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.\.\.
Reading symbols from /home/mauke/perl5/perlbrew/perls/perl\-5\.16\.1\-d/bin/perl\.\.\.done\.
\(gdb\) r
Starting program&#8203;: /home/mauke/perl5/perlbrew/perls/perl\-5\.16\.1\-d/bin/perl irc\.pl
Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\) line 1\.
Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\) line 1\.
Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\) line 1\.
Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\) line 1\.
Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\) line 1\.
Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\) line 1\.
Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\) line 1\.

Program received signal SIGABRT\, Aborted\.
0xb7fe2416 in \_\_kernel\_vsyscall \(\)
\(gdb\) bt
\#0  0xb7fe2416 in \_\_kernel\_vsyscall \(\)
\#1  0xb7e39781 in \*\_\_GI\_raise \(sig=6\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:64
\#2  0xb7e3cbb2 in \*\_\_GI\_abort \(\) at abort\.c&#8203;:92
\#3  0xb7e79f9b in malloc\_printerr \(action=2\, str=0x6 \<Address 0x6 out of bounds>\, ptr=0x82d0258\) at malloc\.c&#8203;:6272
\#4  0xb7e7e916 in \*\_\_GI\_\_\_libc\_free \(mem=0x6\) at malloc\.c&#8203;:3700
\#5  0x081d677f in Perl\_regexec\_flags \(rx=0x82d2188\, stringarg=0x82c13d8 "891"\, strend=\<value optimized out>\, 
&nbsp;    strbeg=0x82c13d8 "891"\, minend=0\, sv=0x82c25e8\, data=0x0\, flags=2\) at regexec\.c&#8203;:2554
\#6  0x08126051 in Perl\_pp\_subst \(\) at pp\_hot\.c&#8203;:2167
\#7  0x080f43d0 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2119
\#8  0x081c7b1a in S\_regmatch \(reginfo=0xbffff298\, startpos=0xbffff27c\) at regexec\.c&#8203;:4329
\#9  S\_regtry \(reginfo=0xbffff298\, startpos=0xbffff27c\) at regexec\.c&#8203;:2738
\#10 0x081d6f94 in Perl\_regexec\_flags \(rx=0x82c25d8\, stringarg=0x82dc7c8 "4000608912607415"\, strend=0x82dc7d8 ""\, 
&nbsp;    strbeg=0x82dc7c8 "4000608912607415"\, minend=0\, sv=0x82c2628\, data=0x0\, flags=3\) at regexec\.c&#8203;:2186
\#11 0x08126051 in Perl\_pp\_subst \(\) at pp\_hot\.c&#8203;:2167
\#12 0x080f43d0 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2119
\#13 0x080878e8 in S\_run\_body \(my\_perl=0x82af008\) at perl\.c&#8203;:2402
\#14 perl\_run \(my\_perl=0x82af008\) at perl\.c&#8203;:2320
\#15 0x08062085 in main \(argc=2\, argv=0xbffff564\, env=0xbffff570\) at perlmain\.c&#8203;:120
\(gdb\) frame 5
\#5  0x081d677f in Perl\_regexec\_flags \(rx=0x82d2188\, stringarg=0x82c13d8 "891"\, strend=\<value optimized out>\, 
&nbsp;    strbeg=0x82c13d8 "891"\, minend=0\, sv=0x82c25e8\, data=0x0\, flags=2\) at regexec\.c&#8203;:2554
2554            RX\_MATCH\_COPY\_FREE\(rx\);
\(gdb\) 

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.16.2:

Configured by mauke at Thu Nov  1 15:23:47 CET 2012.

Summary of my perl5 (revision 5 version 16 subversion 2) configuration:
   
  Platform:
    osname=linux, osvers=2.6.32-5-686, archname=i686-linux
    uname='linux debian-vb 2.6.32-5-686 #1 smp sun sep 23 09:49:36 utc 2012 i686 gnulinux '
    config_args='-Dprefix=/home/mauke/usr -Doptimize=-O2 -flto -Dldflags=-fstack-protector -L/usr/local/lib -O2 -flto -Dlddlflags=-shared -O2 -flto -L/usr/local/lib -fstack-protector -Dcf_email=l.mai@web.de -Dperladmin=none -de'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=undef, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2 -flto',
    cppflags='-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.7.1', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags ='-fstack-protector -L/usr/local/lib -O2 -flto'
    libpth=/usr/local/lib /lib/../lib /usr/lib/../lib /lib /usr/lib /usr/lib/i486-linux-gnu /usr/lib64
    libs=-lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/libc-2.11.3.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.11.3'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -flto -L/usr/local/lib -fstack-protector'

Locally applied patches:
    SAVEARGV0 - disable magic open in <ARGV>


@INC for perl 5.16.2:
    /home/mauke/usr/lib/perl5/site_perl/5.16.2/i686-linux
    /home/mauke/usr/lib/perl5/site_perl/5.16.2
    /home/mauke/usr/lib/perl5/5.16.2/i686-linux
    /home/mauke/usr/lib/perl5/5.16.2
    /home/mauke/usr/lib/perl5/site_perl/5.16.1/i686-linux
    /home/mauke/usr/lib/perl5/site_perl/5.16.1
    /home/mauke/usr/lib/perl5/site_perl
    .


Environment for perl 5.16.2:
    HOME=/home/mauke
    LANG=en_US.utf8
    LANGUAGE (unset)
    LC_COLLATE=POSIX
    LD_LIBRARY_PATH=/home/mauke/usr/lib
    LOGDIR (unset)
    PATH=/home/mauke/perl5/perlbrew/bin:/home/mauke/.cabal/bin:/home/mauke/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    PERLBREW_BASHRC_VERSION=0.55
    PERLBREW_HOME=/home/mauke/.perlbrew
    PERLBREW_ROOT=/home/mauke/perl5/perlbrew
    PERL_BADLANG (unset)
    PERL_UNICODE=SAL
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @cpansprout

On Thu Nov 15 17&#8203;:21&#8203;:55 2012\, mauke\- wrote&#8203;:
> 
> This is a bug report for perl from l\.mai@&#8203;web\.de\,
> generated with the help of perlbug 1\.39 running under perl 5\.16\.2\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
> 
> $ cat irc\.pl
> \#\!/usr/bin/perl
> use warnings;
> use strict;
> 
> for my $num \('4000752057698530'\, '4000608912607415'\,
>    '4000966220145415'\) \{
>     my $tmp = $num;
>     my $x;
>     $tmp =~ s/^\(\.\{6\}\)\(\.\*?\)\(?\{ $x = $^N; $x =~ s\{\.\}\{%\}g;
>    \}\)\(\.\{4\}\)$/$1\#$2/;
> \}
> \_\_END\_\_
> $ perl irc\.pl
> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>    line 1\.
> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>    line 1\.
> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>    line 1\.
> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>    line 1\.
> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>    line 1\.
> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>    line 1\.
> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>    line 1\.
> \*\*\* glibc detected \*\*\* perl&#8203;: double free or corruption \(fasttop\)&#8203;:
>    0x08708f68 \*\*\*

And I thought we made the regular expression engine reëntrant in 5\.14\.0\.
 It’s still broken in blead\, too\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Thu Nov 15 17&#8203;:21&#8203;:55 2012\, mauke\- wrote&#8203;:
> $ cat irc\.pl
> \#\!/usr/bin/perl
> use warnings;
> use strict;
> 
> for my $num \('4000752057698530'\, '4000608912607415'\,
>    '4000966220145415'\) \{
>     my $tmp = $num;
>     my $x;
>     $tmp =~ s/^\(\.\{6\}\)\(\.\*?\)\(?\{ $x = $^N; $x =~ s\{\.\}\{%\}g;
>    \}\)\(\.\{4\}\)$/$1\#$2/;
> \}
> \_\_END\_\_
> $ perl irc\.pl
> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>    line 1\.
> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>    line 1\.
> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>    line 1\.
> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>    line 1\.
> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>    line 1\.
> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>    line 1\.
> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>    line 1\.
> \*\*\* glibc detected \*\*\* perl&#8203;: double free or corruption \(fasttop\)&#8203;:
>    0x08708f68 \*\*\*

This appears to be fixed in blead\.  Anyone want to do a bisect?

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @andk

"Father Chrysostomos via RT" \<perlbug\-followup@&#8203;perl\.org> writes&#8203;:

> On Thu Nov 15 17&#8203;:21&#8203;:55 2012\, mauke\- wrote&#8203;:
>> $ cat irc\.pl
>> \#\!/usr/bin/perl
>> use warnings;
>> use strict;
>> 
>> for my $num \('4000752057698530'\, '4000608912607415'\,
>>    '4000966220145415'\) \{
>>     my $tmp = $num;
>>     my $x;
>>     $tmp =~ s/^\(\.\{6\}\)\(\.\*?\)\(?\{ $x = $^N; $x =~ s\{\.\}\{%\}g;
>>    \}\)\(\.\{4\}\)$/$1\#$2/;
>> \}
>> \_\_END\_\_
>> $ perl irc\.pl
>> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>>    line 1\.
>> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>>    line 1\.
>> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>>    line 1\.
>> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>>    line 1\.
>> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>>    line 1\.
>> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>>    line 1\.
>> Use of uninitialized value $num in substitution \(s///\) at \(re\_eval 1\)
>>    line 1\.
>> \*\*\* glibc detected \*\*\* perl&#8203;: double free or corruption \(fasttop\)&#8203;:
>>    0x08708f68 \*\*\*
>
> This appears to be fixed in blead\.  Anyone want to do a bisect?

I did not see the double free corruption\, just the unini warnings\, hope
this would trigger the same result\.

commit f5df269c5cef57294662d0b1f80a468b91f13643
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Fri Jul 5 23&#8203;:59&#8203;:46 2013 \-0700

&nbsp;    \[perl \#117917\] /\(?\{ m|\.\.\.| \}\) \(?\{ $1 \}\)/
&nbsp;    
&nbsp;    A regular expression invoked inside a regular expression code block
&nbsp;    can cause other code blocks in the same outer regular expression to
&nbsp;    see the wrong values in $1\.
&nbsp;    
&nbsp;    PL\_curpm holds a pointer to the match operator from which $1\, $2\, etc\.
&nbsp;    get their values\.
&nbsp;    
&nbsp;    Normally PL\_curpm is set at the end of a match\.
&nbsp;    
&nbsp;    When code blocks are embedded inside a regular expression\, PL\_curpm
&nbsp;    is set during a match to point to PL\_reg\_curpm\, which is a dummy op
&nbsp;    pointing to the current regular expression\.
&nbsp;    
&nbsp;    S\_setup\_eval\_state is called at the beginning of regexp execution\.
&nbsp;    It is responsible for setting up PL\_regcurpm and making PL\_curpm
&nbsp;    point to it\.
&nbsp;    
&nbsp;    Code blocks are executed using the multicall API\.  PUSH\_MULTICALL
&nbsp;    records the value of PL\_curpm and POP\_MULTICALL makes sure that the
&nbsp;    previous value of PL\_curpm is restored\.
&nbsp;    
&nbsp;    Executing a code block can cause PL\_curpm to point to something else\.
&nbsp;    Since we don’t necessarily do POP\_MULTICALL between code block calls
&nbsp;    within a single regular expression \(sometimes we do\, depending on
&nbsp;    backtracking\)\, PL\_curpm may not have been restored when a second code
&nbsp;    block fires\.  So we have to restore it to point to PL\_reg\_curpm manu\-
&nbsp;    ally after calling a code block\.

:100644 100644 12548d5d21a3aa0fcbd8ad761725c653f9ee0570 6367e2ee694cc417f1b9af7c034a680de9d9f4ec M      regexec\.c
:040000 040000 c78bbe1ce042a4fbb98f17c1296a256f568809d9 08fff18890e8685274e71818159d584c6c32ac08 M      t
bisect run success
That took 459 seconds

\-\- 
andreas

**Comment by p5pRT** [comment]
### From @cpansprout

On Sat Jul 27 01&#8203;:04&#8203;:34 2013\, andreas\.koenig\.7os6VVqR@&#8203;franz\.ak\.mind\.de wrote&#8203;:
> "Father Chrysostomos via RT" \<perlbug\-followup@&#8203;perl\.org> writes&#8203;:
> 
> > On Thu Nov 15 17&#8203;:21&#8203;:55 2012\, mauke\- wrote&#8203;:
> >> $ cat irc\.pl
> >> \#\!/usr/bin/perl
> >> use warnings;
> >> use strict;
> >>
> >> for my $num \('4000752057698530'\, '4000608912607415'\,
> >>    '4000966220145415'\) \{
> >>     my $tmp = $num;
> >>     my $x;
> >>     $tmp =~ s/^\(\.\{6\}\)\(\.\*?\)\(?\{ $x = $^N; $x =~ s\{\.\}\{%\}g;
> >>    \}\)\(\.\{4\}\)$/$1\#$2/;
> >> \}
> >> \_\_END\_\_
> >
> > This appears to be fixed in blead\.  Anyone want to do a bisect?
> 
> I did not see the double free corruption\,

I think Dave Mitchell’s re\-eval work fixed that in 5\.18\.

> just the unini warnings\,
> hope
> this would trigger the same result\.
> 
> commit f5df269c5cef57294662d0b1f80a468b91f13643
> Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
> Date&#8203;:   Fri Jul 5 23&#8203;:59&#8203;:46 2013 \-0700
> 
>     \[perl \#117917\] /\(?\{ m|\.\.\.| \}\) \(?\{ $1 \}\)/
> 
>     A regular expression invoked inside a regular expression code
> block
>     can cause other code blocks in the same outer regular expression
> to
>     see the wrong values in $1\.
\.\.\.
> bisect run success
> That took 459 seconds

Thank you\.  That makes sense\.  Closing ticket\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
