### ISSUE TITLE
Segmentation fault when using Storable on DB_File

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#12626]
Migrated from [rt.perl.org#115972](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=115972) (status was 'resolved')

Searchable as RT115972$

**Comment by p5pRT** [comment]
### From @fangly

This is a bug report for perl from florent\.angly@&#8203;gmail\.com\,
generated with the help of perlbug 1\.39 running under perl 5\.14\.2\.




---
Hi\,

 From the acknowledgments and the test suite of Storable\, it appears 
that this module should support serialization and deserialization of 
tied hashes\. However\, I encountered a segmentation fault when trying to 
freeze and thaw DB\_File tied hashes using Storable\.

This code reproduces the issue&#8203;:
&nbsp;     use strict;
&nbsp;     use warnings;
&nbsp;     use DB\_File;
&nbsp;     use Storable qw\(freeze thaw\);
&nbsp;     tie my %offsets\, 'DB\_File'\, 'file\.idx'\, O\_CREAT|O\_RDWR\, 0644 or die 
"Problem&#8203;: $\!";
&nbsp;     $offsets\{4\} = 235;
&nbsp;     my $thing = thaw freeze \\%offsets;

Note that the bug is reproducible when using GDBM\_File instead of 
DB\_File\. Note also\, that the segmentation fault is triggered by the 
thaw\(\) statement\, but happens at the very end of the script\, during 
garbage collection\.

I generated a stack trace for this error&#8203;:
&nbsp;     \(gdb\) bt
&nbsp;     \#0  0x00007ffff73b7118 in main\_arena \(\) from 
/lib/x86\_64\-linux\-gnu/libc\.so\.6
&nbsp;     \#1  0x00007ffff652fe68 in \_\_db\_errcall \(\) from 
/usr/lib/x86\_64\-linux\-gnu/libdb\-5\.1\.so
&nbsp;     \#2  0x00007ffff653013e in \_\_db\_errx \(\) from 
/usr/lib/x86\_64\-linux\-gnu/libdb\-5\.1\.so
&nbsp;     \#3  0x00007ffff6533911 in \_\_dbc\_close\_pp \(\) from 
/usr/lib/x86\_64\-linux\-gnu/libdb\-5\.1\.so
&nbsp;     \#4  0x00007ffff67d9345 in XS\_DB\_File\_DESTROY \(my\_perl=0x603010\, 
cv=\<optimized out>\) at DB\_File\.c&#8203;:1749
&nbsp;     \#5  0x00007ffff7b155ac in Perl\_pp\_entersub \(my\_perl=0x603010\) at 
pp\_hot\.c&#8203;:3046
&nbsp;     \#6  0x00007ffff7aa8a11 in Perl\_call\_sv 
\(my\_perl=my\_perl@&#8203;entry=0x603010\, sv=sv@&#8203;entry=0x78bf80\, 
flags=flags@&#8203;entry=45\) at perl\.c&#8203;:2647
&nbsp;     \#7  0x00007ffff7b1ba79 in S\_curse \(check\_refcnt=1 '\\001'\, 
sv=0x78a460\, my\_perl=0x603010\) at sv\.c&#8203;:6342
&nbsp;     \#8  Perl\_sv\_clear \(my\_perl=my\_perl@&#8203;entry=0x603010\, 
orig\_sv=orig\_sv@&#8203;entry=0x623ca8\) at sv\.c&#8203;:6073
&nbsp;     \#9  0x00007ffff7b1c132 in Perl\_sv\_free2 
\(my\_perl=my\_perl@&#8203;entry=0x603010\, sv=0x623ca8\) at sv\.c&#8203;:6474
&nbsp;     \#10 0x00007ffff7af6808 in S\_mg\_free\_struct \(my\_perl=0x603010\, 
sv=\<optimized out>\, mg=0x640b80\) at mg\.c&#8203;:566
&nbsp;     \#11 0x00007ffff7af736e in Perl\_mg\_free 
\(my\_perl=my\_perl@&#8203;entry=0x603010\, sv=sv@&#8203;entry=0x6245c0\) at mg\.c&#8203;:588
&nbsp;     \#12 0x00007ffff7b1b70a in Perl\_sv\_clear 
\(my\_perl=my\_perl@&#8203;entry=0x603010\, orig\_sv=orig\_sv@&#8203;entry=0x606b78\) at 
sv\.c&#8203;:6085
&nbsp;     \#13 0x00007ffff7b1c132 in Perl\_sv\_free2 
\(my\_perl=my\_perl@&#8203;entry=0x603010\, sv=0x606b78\) at sv\.c&#8203;:6474
&nbsp;     \#14 0x00007ffff7b41920 in Perl\_free\_tmps 
\(my\_perl=my\_perl@&#8203;entry=0x603010\) at scope\.c&#8203;:167
&nbsp;     \#15 0x00007ffff7aae574 in perl\_run \(my\_perl=0x603010\) at perl\.c&#8203;:2273
&nbsp;     \#16 0x0000000000400f89 in main \(argc=2\, argv=0x7fffffffe818\, 
env=0x7fffffffe830\) at perlmain\.c&#8203;:120

Best\,

Florent


---


---
Flags&#8203;:
&nbsp;     category=library
&nbsp;     severity=low
&nbsp;     module=Storable


---
Site configuration information for perl 5\.14\.2&#8203;:

Configured by Debian Project at Sun Nov  4 10&#8203;:59&#8203;:22 UTC 2012\.

Summary of my perl5 \(revision 5 version 14 subversion 2\) configuration&#8203;:

&nbsp;   Platform&#8203;:
&nbsp;     osname=linux\, osvers=3\.2\.0\-4\-amd64\, 
archname=x86\_64\-linux\-gnu\-thread\-multi
&nbsp;     uname='linux madeleine 3\.2\.0\-4\-amd64 \#1 smp debian 3\.2\.32\-1 x86\_64 
gnulinux '
&nbsp;     config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN 
\-D\_FORTIFY\_SOURCE=2 \-g \-O2 \-fstack\-protector \-\-param=ssp\-buffer\-size=4 
\-Wformat \-Werror=format\-security \-Dldflags= \-Wl\,\-z\,relro 
\-Dlddlflags=\-shared \-Wl\,\-z\,relro \-Dcccdlflags=\-fPIC 
\-Darchname=x86\_64\-linux\-gnu \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.14 
\-Darchlib=/usr/lib/perl/5\.14 \-Dvendorprefix=/usr 
\-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/perl5 
\-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.14\.2 
\-Dsitearch=/usr/local/lib/perl/5\.14\.2 \-Dman1dir=/usr/share/man/man1 
\-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1 
\-Dsiteman3dir=/usr/local/man/man3 \-Duse64bitint \-Dman1ext=1 
\-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Ud\_ualarm 
\-Uusesfio \-Uusenm \-Ui\_libutil \-DDEBUGGING=\-g \-Doptimize=\-O2 \-Duseshrplib 
\-Dlibperl=libperl\.so\.5\.14\.2 \-des'
&nbsp;     hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;     useithreads=define\, usemultiplicity=define
&nbsp;     useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;     use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;     usemymalloc=n\, bincompat5005=undef
&nbsp;   Compiler&#8203;:
&nbsp;     cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN 
\-fstack\-protector \-fno\-strict\-aliasing \-pipe \-I/usr/local/include 
\-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;     optimize='\-O2 \-g'\,
&nbsp;     cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fstack\-protector 
\-fno\-strict\-aliasing \-pipe \-I/usr/local/include'
&nbsp;     ccversion=''\, gccversion='4\.7\.2'\, gccosandvers=''
&nbsp;     intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;     ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, 
lseeksize=8
&nbsp;     alignbytes=8\, prototype=define
&nbsp;   Linker and Libraries&#8203;:
&nbsp;     ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;     libpth=/usr/local/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib 
/usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib /usr/lib
&nbsp;     libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;     perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;     libc=\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.14\.2
&nbsp;     gnulibc\_version='2\.13'
&nbsp;   Dynamic Linking&#8203;:
&nbsp;     dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;     cccdlflags='\-fPIC'\, lddlflags='\-shared \-L/usr/local/lib 
\-fstack\-protector'

Locally applied patches&#8203;:




---
@&#8203;INC for perl 5\.14\.2&#8203;:
&nbsp;     /etc/perl
&nbsp;     /usr/local/lib/perl/5\.14\.2
&nbsp;     /usr/local/share/perl/5\.14\.2
&nbsp;     /usr/lib/perl5
&nbsp;     /usr/share/perl5
&nbsp;     /usr/lib/perl/5\.14
&nbsp;     /usr/share/perl/5\.14
&nbsp;     /usr/local/lib/site\_perl
&nbsp;     \.



---
Environment for perl 5\.14\.2&#8203;:
&nbsp;     HOME=/home/floflooo
&nbsp;     LANG=en\_AU\.utf8
&nbsp;     LANGUAGE \(unset\)
&nbsp;     LD\_LIBRARY\_PATH \(unset\)
&nbsp;     LOGDIR \(unset\)
&nbsp;     PATH=/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/local/games&#8203;:/usr/games
&nbsp;     PERL\_BADLANG \(unset\)
&nbsp;     SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @Leont

On Sun Dec 02 17&#8203;:49&#8203;:11 2012\, fangly wrote&#8203;:
>  From the acknowledgments and the test suite of Storable\, it appears 
> that this module should support serialization and deserialization of 
> tied hashes\. However\, I encountered a segmentation fault when trying to 
> freeze and thaw DB\_File tied hashes using Storable\.

The problem isn't ties\, it's that the DB\_File object is implemented in C
and thus can't be serialized easily\.
 
> Note that the bug is reproducible when using GDBM\_File instead of 
> DB\_File\. Note also\, that the segmentation fault is triggered by the 
> thaw\(\) statement\, but happens at the very end of the script\, during 
> garbage collection\.

I bet it's reproducible on any class using T\_PTROBJ\. When the Perl
object is serialized\, it copies the \*pointer\* to the C object\, not the
object itself\, so when it is deserialized it you end up with two perl
objects pointing to the same C object\. When the perl objects are
destroyed\, the C object will be destroyed twice\, resulting in a
segfault\. Something similar happens after thread\-cloning AFAIK\. I'm not
sure this can be fixed sanely \(it would require either cloning the BDB
object\, or refcounting and locking it\)\, possibly it should die on
freezing instead of segfaulting much later\.

Leon

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @bulk88

On Mon Dec 03 18&#8203;:03&#8203;:35 2012\, LeonT wrote&#8203;:
> I bet it's reproducible on any class using T\_PTROBJ\. When the Perl
> object is serialized\, it copies the \*pointer\* to the C object\, not the
> object itself\, so when it is deserialized it you end up with two perl
> objects pointing to the same C object\. When the perl objects are
> destroyed\, the C object will be destroyed twice\, resulting in a
> segfault\. Something similar happens after thread\-cloning AFAIK\. I'm not
> sure this can be fixed sanely \(it would require either cloning the BDB
> object\, or refcounting and locking it\)\, possibly it should die on
> freezing instead of segfaulting much later\.
> 
> Leon

The rest of this post has nothing specific about DB\_File\.

The problem you describe isn't very difficult to fix\. I have an
implementation of it at 

https://metacpan.org/source/BULKDD/Win32-API-0.74/Callback/Callback.xs#L624
https://metacpan.org/source/BULKDD/Win32-API-0.74/Callback/Callback.xs#L656
https://metacpan.org/source/BULKDD/Win32-API-0.74/Callback/Callback.xs#L294

It adds a refcount of the number of interps/SVs that own a malloc block\.
Last :&#8203;:DESTROY or whichever :&#8203;:DESTROY wins the refcnt=0 race frees it\.
It uses Win32 atomic operations\. The refcount is stuck onto the end of
the HeapAlloc block\, with alignment padding if required\. A pointer to
the refcount is stored in the mg struct\. There is no realloc style
operation in my API and its write once \(at creation\, not shown in links
above\)\, read many\, so locks/synchronization is only required for the
freeing/DESTROY aspect\.

\-\- 
bulk88 ~ bulk88 at hotmail\.com

**Comment by p5pRT** [comment]
### From @fangly


> The problem you describe isn't very difficult to fix\. I have an
> implementation of it

Thanks for the reply bulk88\, but do you suggest that my code could be 
changed to make it work? Or did you mean that a fix could be made for 
Storable? If that's the case\, would you be able to fix Storable?
Thanks\,
Florent

**Comment by p5pRT** [comment]
### From @bulk88

On Tue Mar 05 17&#8203;:25&#8203;:24 2013\, fangly wrote&#8203;:
> 
> > The problem you describe isn't very difficult to fix\. I have an
> > implementation of it
> 
> Thanks for the reply bulk88\, but do you suggest that my code could be 
> changed to make it work? Or did you mean that a fix could be made for 
> Storable? If that's the case\, would you be able to fix Storable?
> Thanks\,
> Florent
> 

I was speaking generically about the problem LeonT described with Perl\,
XS\, and C libraries\, I don't know anything specific about DB\_File\.
Storable specifically has an API
http&#8203;://search\.cpan\.org/~ams/Storable\-2\.39/Storable\.pm\#Hooks for classes
to define subs so they can de/serialize themselves correctly\, often with
XSUBs\. The simplest fix would be to die\(\) to happen a hypothetical
DB\_File&#8203;::STORABLE\_freeze\(\) and this would turn a SEGV to a friendly
fatal error \( see example
https://metacpan.org/source/FLORA/perl-5.17.4/cpan/Compress-Raw-Bzip2/lib/Compress/Raw/Bzip2.pm#L93
 \)\. A similar thing is often done for psuedo and/or fork see
http&#8203;://perldoc\.perl\.org/perlmod\.html\#CLONE\_SKIP \. The more complicated
but correct fix would be to implement a STORABLE\_freeze\(\) and do all the
correct C\-land fixups on the tied var/obj\.

\-\- 
bulk88 ~ bulk88 at hotmail\.com

**Comment by p5pRT** [comment]
### From @bulk88

On Tue Mar 05 17&#8203;:44&#8203;:04 2013\, bulk88 wrote&#8203;:
> On Tue Mar 05 17&#8203;:25&#8203;:24 2013\, fangly wrote&#8203;:
> > Thanks for the reply bulk88\, but do you suggest that my code could
> be
> > changed to make it work? Or did you mean that a fix could be made
> for
> > Storable? If that's the case\, would you be able to fix Storable?
> > Thanks\,
> > Florent
> >
> 
> I was speaking generically about the problem LeonT described with

If the solution is implementing Storable hooks in DB\_File\, then I think
this ticket needs to be moved to DB\_File's CPAN RT Queue for someone
familiar \(AKA authors/maintainers\) with DB\_File to respond since there
were no answers specific to DB\_File so far \(3 months\)\.

\-\- 
bulk88 ~ bulk88 at hotmail\.com

**Comment by p5pRT** [comment]
### From @pmqs

Sorry for not responding to this sooner \- just happened to notice this 
thread pop up on p5p\. If it was on the CPAN queue I would have spotted 
it immediately\.



I will \(at least\) get DB\_File to do the same as Compress&#8203;::Raw&#8203;::Bzip2 
\(another of my modules\) and die gracefully\.



Florent \- I'm curious about why you need Storable for DB\_File at all\. 
DB\_File already persists Perl hashes & array to disk\, so I'm not clear 
what extra Storable support gives us\.



cheers

Paul

**Comment by p5pRT** [comment]
### From @pmqs

Turns out DB\_File can  handle freeze/thaw gracefully since version
1\.823\. Perl 1\.14\.2 only has DB\_File 1\.821

Paul

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @fangly

On 06/03/13 20&#8203;:45\, Paul Marquess via RT wrote&#8203;:
> Florent \- I'm curious about why you need Storable for DB\_File at all\.
> DB\_File already persists Perl hashes & array to disk\, so I'm not clear
> what extra Storable support gives us\.
Paul\, the reason I need Storable for DB\_File is that I want to use some 
objects with Threads&#8203;::Queue&#8203;::Any\, which rely of Storable to do its job\. 
The objects do not inherit from DB\_File itself\, but they do keep a 
record of the DB\_File object they need to work\.


On 09/03/13 22&#8203;:44\, Paul Marquess via RT wrote&#8203;:
> Turns out DB\_File can  handle freeze/thaw gracefully since version
> 1\.823\. Perl 1\.14\.2 only has DB\_File 1\.821
>
That's good that DB\_File now dies instead of segfaulting\.

However\, the reason I originally posted this report on the Perl5 tracker 
is that the segmentation fault is not specific to DB\_File\. It also 
happens with GDBM\_File\, and possibly other such modules&#8203;:
> use strict;
> use warnings;
> use GDBM\_File;
> use Storable qw\(freeze thaw\);
> tie my %offsets\, 'GDBM\_File'\, 'file\.idx'\, &GDBM\_WRCREAT\, 0640 or die 
> "Problem&#8203;: $\!\\n";
> $offsets\{4\} = 235;
> my $thing = thaw freeze \\%offsets;

Should all XXX\_File modules implement hooks for Storable \(as mentioned 
by bulk88\)?

Or is it that Storable could be smarter about dealing with XXX\_File 
objects? What do the Storable maintainers think?

Florent

**Comment by p5pRT** [comment]
### From @lizmat


On Mar 11\, 2013\, at 3&#8203;:39 AM\, Florent Angly \<florent\.angly@&#8203;gmail\.com> wrote&#8203;:

> On 06/03/13 20&#8203;:45\, Paul Marquess via RT wrote&#8203;:
>> Florent \- I'm curious about why you need Storable for DB\_File at all\.
>> DB\_File already persists Perl hashes & array to disk\, so I'm not clear
>> what extra Storable support gives us\.
> Paul\, the reason I need Storable for DB\_File is that I want to use some objects with Threads&#8203;::Queue&#8203;::Any\, which rely of Storable to do its job\. The objects do not inherit from DB\_File itself\, but they do keep a record of the DB\_File object they need to work\.

From the pod of Thread&#8203;::Queue&#8203;::Any&#8203;:

\# specify class with "freeze" and "thaw" methods
use Thread&#8203;::Queue&#8203;::Any serializer => 'Storable';

So maybe another serializer might do the job for you?  Maybe Sereal?



Liz

**Comment by p5pRT** [comment]
### From @tsee

On 03/11/2013 03&#8203;:39 AM\, Florent Angly wrote&#8203;:
> On 06/03/13 20&#8203;:45\, Paul Marquess via RT wrote&#8203;:
>> Florent \- I'm curious about why you need Storable for DB\_File at all\.
>> DB\_File already persists Perl hashes & array to disk\, so I'm not clear
>> what extra Storable support gives us\.
> Paul\, the reason I need Storable for DB\_File is that I want to use some
> objects with Threads&#8203;::Queue&#8203;::Any\, which rely of Storable to do its job\.
> The objects do not inherit from DB\_File itself\, but they do keep a
> record of the DB\_File object they need to work\.

> However\, the reason I originally posted this report on the Perl5 tracker
> is that the segmentation fault is not specific to DB\_File\. It also
> happens with GDBM\_File\, and possibly other such modules&#8203;:

> Should all XXX\_File modules implement hooks for Storable \(as mentioned
> by bulk88\)?
>
> Or is it that Storable could be smarter about dealing with XXX\_File
> objects? What do the Storable maintainers think?

FWIW\, I think there is no "Storable maintainer" outside the general 
"supported by perl5\-porters"\.

I think Storable should UNDER NO CIRCUMSTANCES add support for specific 
other modules\[1\]\. The XXX\_File modules could add hooks OR this could be 
a case of "don't do that" since serializing those types of object is at 
least a very shady thing to begin with\.

\-\-Steffen

\[1\] Without looking at the Storable code again\, I bet that there's a 
bunch of crazy exceptions in there already\, but that should serve as an 
example of what NOT to do\.

**Comment by p5pRT** [comment]
### From @fangly

Thanks for the answers\. The best seem to have the different XX\_File
modules have hooks for Storable\.

I have filed a separate bug report for DB\_File at
https://rt.cpan.org/Ticket/Display.html?id=84184&results=8cc77d5768d33c8b8c3aebdaffd39622

I have also confirmed that GDBM\_File\, NDBM\_File\, ODBM\_File and SDBM\_File
exhibit the same issue\. Since these modules are maintained and shipped
with perl\, should the present bug report be updated or a new one started?
