### ISSUE TITLE
Segmentation fault on using NYTProf

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#12704]
Migrated from [rt.perl.org#116409](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=116409) (status was 'rejected')

Searchable as RT116409$

**Comment by p5pRT** [comment]
### From perl-diddler@tlinx.org

#### Created by perl-diddler@tlinx.org



> dedup three four
Processed 7123 files\, 5 dirs^C   \(runs\.\.\.to completion\)

> perl \-d&#8203;:NYTProf \.\./bin/dedup three four               
Can't use string \("three"\) as a subroutine ref while "strict refs" in use at \.\./bin/dedup line 1256\.
 at \.\./bin/dedup line 1256\.
&nbsp;        main&#8203;::verify\_same\_dev\_pathargs\('ARRAY\(0x2562098\)'\) called at \.\./bin/dedup line 1299
&nbsp;        main&#8203;::process\_n\_verify\_args\('three'\, 'four'\) called at \.\./bin/dedup line 1441
Segmentation fault \(core dumped\)

It seems a bug against NYTProf that it is corrupting my prog's args\, but
perl is dying\, so maybe perl is giving it false info?


> gdb perl core
\.\.\.
Program terminated with signal 11\, Segmentation fault\.
\#0  incr\_sub\_inclusive\_time \(my\_perl=0x882010\, subr\_entry=0xb98650\) at NYTProf\.xs&#8203;:1970
1970            while \(\*p\)
\(gdb\) where
\#0  incr\_sub\_inclusive\_time \(my\_perl=0x882010\, subr\_entry=0xb98650\) at NYTProf\.xs&#8203;:1970
\#1  0x00000000004d51fc in Perl\_leave\_scope \(\)
\#2  0x0000000000436173 in ?? \(\)
\#3  0x000000000043cd8a in Perl\_my\_failure\_exit \(\)
\#4  0x00000000004deb11 in Perl\_die\_unwind \(\)
\#5  0x0000000000482076 in Perl\_croak\_sv \(\)
\#6  0x0000000000482089 in Perl\_die\_sv \(\)
\#7  0x00000000004e819b in Perl\_pp\_die \(\)
\#8  0x000000000049f6a6 in Perl\_runops\_standard \(\)
\#9  0x0000000000436b19 in Perl\_call\_sv \(\)
\#10 0x0000000000480af8 in ?? \(\)
\#11 0x000000000048213e in Perl\_vcroak \(\)
\#12 0x0000000000482207 in Perl\_die \(\)
\#13 0x00000000004a69c1 in Perl\_pp\_entersub \(\)
\#14 0x00007ff8684277ac in pp\_subcall\_profiler \(my\_perl=0x882010\, is\_slowop=1\) at NYTProf\.xs&#8203;:2519
\#15 0x00007ff867a9965c in XS\_Time\_\_HiRes\_stat \(my\_perl=0x882010\, cv=\<optimized out>\) at HiRes\.xs&#8203;:1253
\#16 0x00000000004a6ee2 in Perl\_pp\_entersub \(\)
\#17 0x00007ff8684277ac in pp\_subcall\_profiler \(my\_perl=0x882010\, is\_slowop=0\) at NYTProf\.xs&#8203;:2519
\#18 0x000000000049f6a6 in Perl\_runops\_standard \(\)
\#19 0x000000000043cc42 in perl\_run \(\)
\#20 0x000000000041ec5b in main \(\)


I was going to try to find out why my args were being corrupted\, but
then I noticed the core dump\.\.\.and figured that's the least of my
problems\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

This perlbug was built using Perl 5.16.1 - Mon Sep 10 13:51:31 UTC 2012
It is being executed now by  Perl 5.16.1 - Mon Sep 10 13:45:59 UTC 2012.

Site configuration information for perl 5.16.1:

Configured by abuild at Mon Sep 10 13:45:59 UTC 2012.

Summary of my perl5 (revision 5 version 16 subversion 1) configuration:
   
  Platform:
    osname=linux, osvers=3.4.6-2.10-default, archname=x86_64-linux-thread-multi
    uname='linux build35 3.4.6-2.10-default #1 smp thu jul 26 09:36:26 utc 2012 (641c197) x86_64 x86_64 x86_64 gnulinux '
    config_args='-ds -e -Dprefix=/usr -Dvendorprefix=/usr -Dinstallusrbinperl -Dusethreads -Di_db -Di_dbm -Di_ndbm -Di_gdbm -Dd_dbm_open -Duseshrplib=true -Doptimize=-fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -Wall -pipe -Accflags=-DPERL_USE_SAFE_PUTENV -Dotherlibdirs=/usr/lib/perl5/site_perl'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DPERL_USE_SAFE_PUTENV -fno-strict-aliasing -pipe -fstack-protector -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -Wall -pipe',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DPERL_USE_SAFE_PUTENV -fno-strict-aliasing -pipe -fstack-protector'
    ccversion='', gccversion='4.7.1 20120723 [gcc-4_7-branch revision 189773]', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib64 -fstack-protector'
    libpth=/lib64 /usr/lib64 /usr/local/lib64
    libs=-lm -ldl -lcrypt -lpthread
    perllibs=-lm -ldl -lcrypt -lpthread
    libc=/lib64/libc-2.16.so, so=so, useshrplib=true, libperl=libperl.so
    gnulibc_version='2.16'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E -Wl,-rpath,/usr/lib/perl5/5.16.1/x86_64-linux-thread-multi/CORE'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib64 -fstack-protector'

Locally applied patches:
    


@INC for perl 5.16.1:
    /home/law/bin/lib
    /usr/lib/perl5/site_perl/5.16.1/x86_64-linux-thread-multi
    /usr/lib/perl5/site_perl/5.16.1
    /usr/lib/perl5/vendor_perl/5.16.1/x86_64-linux-thread-multi
    /usr/lib/perl5/vendor_perl/5.16.1
    /usr/lib/perl5/5.16.1/x86_64-linux-thread-multi
    /usr/lib/perl5/5.16.1
    /usr/lib/perl5/site_perl/5.16.1/x86_64-linux-thread-multi
    /usr/lib/perl5/site_perl/5.16.1
    /usr/lib/perl5/site_perl
    /usr/lib/perl5/vendor_perl/5.16.0/x86_64-linux-thread-multi
    /usr/lib/perl5/vendor_perl/5.16.0
    /usr/lib/perl5/vendor_perl
    /usr/lib/perl5/site_perl
    .


Environment for perl 5.16.1:
    HOME=/home/law
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_COLLATE=C
    LC_CTYPE=en_US.UTF-8
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=.:/sbin:/usr/local/sbin:/home/law/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/games:/opt/kde3/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/opt/dell/srvadmin/bin:/usr/sbin:/etc/local/func_lib:/home/law/lib:/home/law/bin/lib
    PERL5OPT=-CSA -I/home/law/bin/lib
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From perl-diddler@tlinx.org

FWIW \.\. this seems to be something in NYTProf\.\.\.

I ran the same prog\, same args with 'FastProf' and that
worked fine\.

**Comment by p5pRT** [comment]
perl-diddler@tlinx.org - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @jkeenan

Devel&#8203;::NYTProf is not part of the Perl 5 core distribution&#8203;:

\#\#\#\#\#
$ corelist Devel&#8203;::NYTProf

Devel&#8203;::NYTProf was not in CORE \(or so I think\)

\#\#\#\#\#

Hence\, rt\.perl\.org is not the correct location to locate bugs in the module or to get help using 
it\.  Please consult the module's POD or http&#8203;://search\.cpan\.org/~timb/Devel\-NYTProf\-4\.23/\.

Closing ticket\.

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Devel&#8203;::NYTProf is not part of the Perl 5 core distribution&#8203;:

\#\#\#\#\#
$ corelist Devel&#8203;::NYTProf

Devel&#8203;::NYTProf was not in CORE \(or so I think\)

\#\#\#\#\#

Hence\, rt\.perl\.org is not the correct location to locate bugs in the module or to get help using 
it\.  Please consult the module's POD or http&#8203;://search\.cpan\.org/~timb/Devel\-NYTProf\-4\.23/\.

Closing ticket\.

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
@jkeenan - Status changed from 'open' to 'rejected'
