### ISSUE TITLE
NULL reference in Perl_hv_undef_flags

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#12709]
Migrated from [rt.perl.org#116441](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=116441) (status was 'resolved')

Searchable as RT116441$

**Comment by p5pRT** [comment]
### From manu@netbsd.org


This is a bug report for perl from manu@&#8203;netbsd\.org\,
generated with the help of perlbug 1\.39 running under perl 5\.14\.2\.




---
NB&#8203;: report was not generated on the machine the bug can be observed\.

In perl\-5\.16\.2's Perl\_hv\_undef\_flags\, hv parameter is deferenced 
before being checked as non NULL\. As a consequence\, I get SIGSEGV
with apaache\-1\.3\.42 and mod\_perl\-1\.31 on httpd startup\.

Program received signal SIGSEGV\, Segmentation fault\.
\[Switching to LWP 1\]
Perl\_hv\_undef\_flags \(my\_perl=0xbb537800\, hv=0x0\, flags=0\) at hv\.c&#8203;:1788
1788        const bool save = \!\!SvREFCNT\(hv\);
\(gdb\) bt
\#0  Perl\_hv\_undef\_flags \(my\_perl=0xbb537800\, hv=0x0\, flags=0\) at hv\.c&#8203;:1788
\#1  0xbb646f8e in perl\_util\_cleanup \(\) from /usr/pkg/lib/httpd/mod\_perl\.so
\#2  0xbb639b10 in perl\_shutdown \(\) from /usr/pkg/lib/httpd/mod\_perl\.so
\#3  0xbb639ec3 in mp\_dso\_unload \(\) from /usr/pkg/lib/httpd/mod\_perl\.so
\#4  0x08073524 in ap\_clear\_pool \(\)
\#5  0x08081956 in main \(\)


The patch below fixes the problem&#8203;:

<details><summary>Inline Patch</summary>

```diff
--- hv.c.orig   2013-01-17 08:54:13.000000000 +0100
+++ hv.c        2013-01-17 08:55:42.000000000 +0100
@@ -1784,14 +1784,16 @@
 {
     dVAR;
     register XPVHV* xhv;
     const char *name;
-    const bool save = !!SvREFCNT(hv);
+    bool save;

     if (!hv)
        return;
+
     DEBUG_A(Perl_hv_assert(aTHX_ hv));
     xhv = (XPVHV*)SvANY(hv);
+    save = !!SvREFCNT(hv);

     /* The name must be deleted before the call to hfreeeeentries so that
        CVs are anonymised properly. But the effective name must be pre-
        served until after that call (and only deleted afterwards if the

-----------------------------------------------------------------
---

```
</details>
Flags:
&nbsp;    category=core
&nbsp;    severity=critical


---
Site configuration information for perl 5\.14\.2&#8203;:

Configured by manu at Mon Aug 13 14&#8203;:49&#8203;:35 UTC 2012\.

Summary of my perl5 \(revision 5 version 14 subversion 2\) configuration&#8203;:
&nbsp;   
&nbsp;  Platform&#8203;:
&nbsp;    osname=netbsd\, osvers=5\.1\.2\, archname=i386\-netbsd\-thread\-multi
&nbsp;    uname='netbsd lego 5\.1\.2 netbsd 5\.1\.2 \(xen3\_domu\) \#0&#8203;: thu feb 2 17&#8203;:18&#8203;:31 utc 2012 builds@&#8203;b6\.netbsd\.org&#8203;:homebuildsabnetbsd\-5\-1\-2\-releasei386201202021012z\-objhomebuildsabnetbsd\-5\-1\-2\-releasesrcsysarchi386compilexen3\_domu i386 '
&nbsp;    config\_args='\-sde \-D ccflags=\-O2   \-pthread  \-I/usr/include \-D ldflags=  \-pthread  \-L/usr/lib \-Wl\,\-R/usr/lib \-Wl\,\-R/usr/pkg/lib \-Duseshrplib \-Duseithreads \-Uusemymalloc'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-O2 \-pthread \-I/usr/include \-fno\-strict\-aliasing \-pipe \-fstack\-protector'\,
&nbsp;    optimize='\-O2   \-pthread  \-I/usr/include'\,
&nbsp;    cppflags='\-O2 \-pthread \-I/usr/include \-fno\-strict\-aliasing \-pipe \-fstack\-protector'
&nbsp;    ccversion=''\, gccversion='4\.1\.3 20080704 prerelease \(NetBSD nb2 20081120\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags ='\-Wl\,\-R/usr/pkg/lib \-Wl\,\-rpath\,/usr/pkg/lib \-fstack\-protector \-L/usr/pkg/lib'
&nbsp;    libpth=/lib /usr/lib /usr/pkg/lib
&nbsp;    libs=\-lm \-lcrypt \-lpthread
&nbsp;    perllibs=\-lm \-lcrypt \-lpthread
&nbsp;    libc=/lib/libc\.so\, so=so\, useshrplib=true\, libperl=libperl\.so
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E  \-Wl\,\-R/usr/pkg/lib/perl5/5\.14\.0/i386\-netbsd\-thread\-multi/CORE'
&nbsp;    cccdlflags='\-DPIC \-fPIC '\, lddlflags='\-Wl\,\-R/usr/pkg/lib \-\-whole\-archive \-shared  \-L/usr/pkg/lib \-fstack\-protector'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl 5\.14\.2&#8203;:
&nbsp;    /usr/pkg/lib/perl5/site\_perl/5\.14\.0/i386\-netbsd\-thread\-multi
&nbsp;    /usr/pkg/lib/perl5/site\_perl/5\.14\.0
&nbsp;    /usr/pkg/lib/perl5/vendor\_perl/5\.14\.0/i386\-netbsd\-thread\-multi
&nbsp;    /usr/pkg/lib/perl5/vendor\_perl/5\.14\.0
&nbsp;    /usr/pkg/lib/perl5/5\.14\.0/i386\-netbsd\-thread\-multi
&nbsp;    /usr/pkg/lib/perl5/5\.14\.0
&nbsp;    \.



---
Environment for perl 5\.14\.2&#8203;:
&nbsp;    HOME=/home2/manu
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/bin&#8203;:/usr/bin&#8203;:/usr/pkg/bin&#8203;:/usr/X11R6/bin&#8203;:/usr/local/bin&#8203;:/sbin&#8203;:/usr/sbin&#8203;:/usr/pkg/sbin&#8203;:/usr/local/sbin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/ksh

**Comment by p5pRT** [comment]
### From @rgs

This should be fixed by commit 8a50cd03a18f63853c30d77231f3eed37cdf7efa

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@rgs - Status changed from 'open' to 'resolved'
