### ISSUE TITLE
segfault after upgrade to 5.18.0-1

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#13001]
Migrated from [rt.perl.org#118203](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=118203) (status was 'resolved')

Searchable as RT118203$

**Comment by p5pRT** [comment]
### From @hakon1912

#### Created by @hakon1912



I just upgraded perl from 5\.16\.3\.3 \-> 5\.18\.0\-1\, which seems to be the
cause a segfault in urxvt\.

backtrace&#8203;:
\#0  0x00007f95045ed4dc in Perl\_sv\_vcatpvfn\_flags \(\)
&nbsp;   from /usr/lib/perl5/core\_perl/CORE/libperl\.so
\#1  0x00007f95045f0072 in Perl\_sv\_vsetpvfn \(\) from /usr/lib/perl5/core\_perl/CORE/libperl\.so
\#2  0x00007f95045f00f5 in Perl\_vnewSVpvf \(\) from /usr/lib/perl5/core\_perl/CORE/libperl\.so
\#3  0x00007f95045f0257 in Perl\_newSVpvf \(\) from /usr/lib/perl5/core\_perl/CORE/libperl\.so
\#4  0x00007f95045cacb6 in Perl\_xs\_apiversion\_bootcheck \(\)
&nbsp;      from /usr/lib/perl5/core\_perl/CORE/libperl\.so
\#5  0x000000000043a99c in boot\_urxvt \(\)
\#6  0x00007f95045e9821 in Perl\_pp\_entersub \(\) from /usr/lib/perl5/core\_perl/CORE/libperl\.so
\#7  0x00007f95045e1e26 in Perl\_runops\_standard \(\)
&nbsp;         from /usr/lib/perl5/core\_perl/CORE/libperl\.so
\#8  0x00007f95045733b0 in Perl\_call\_sv \(\) from /usr/lib/perl5/core\_perl/CORE/libperl\.so
\#9  0x00007f9504575477 in Perl\_call\_list \(\) from /usr/lib/perl5/core\_perl/CORE/libperl\.so
\#10 0x00007f950455b48f in S\_process\_special\_blocks \(\)
&nbsp;            from /usr/lib/perl5/core\_perl/CORE/libperl\.so
\#11 0x00007f950456ca9c in Perl\_newATTRSUB\_flags \(\)
&nbsp;               from /usr/lib/perl5/core\_perl/CORE/libperl\.so
\#12 0x00007f950456d5f0 in Perl\_newATTRSUB \(\) from /usr/lib/perl5/core\_perl/CORE/libperl\.so
\#13 0x00007f95045a0094 in Perl\_yyparse \(\) from /usr/lib/perl5/core\_perl/CORE/libperl\.so
\#14 0x00007f950457915c in perl\_parse \(\) from /usr/lib/perl5/core\_perl/CORE/libperl\.so
\#15 0x0000000000455a73 in rxvt\_perl\_interp&#8203;::init\(\) \(\)
\#16 0x0000000000455b0b in rxvt\_perl\_interp&#8203;::init\(rxvt\_term\*\) \(\)
\#17 0x00000000004243fc in rxvt\_term&#8203;::init\_resources\(int\, char const\* const\*\) \(\)
\#18 0x000000000042578a in rxvt\_term&#8203;::init2\(int\, char const\* const\*\) \(\)
\#19 0x000000000041883c in main \(\)

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.14.2:

Configured by Debian Project at Wed Apr 10 16:58:16 UTC 2013.

Summary of my perl5 (revision 5 version 14 subversion 2) configuration:
   
  Platform:
    osname=linux, osvers=3.2.0-4-amd64, archname=x86_64-linux-gnu-thread-multi
    uname='linux madeleine 3.2.0-4-amd64 #1 smp debian 3.2.39-2 x86_64 gnulinux '
    config_args='-Dusethreads -Duselargefiles -Dccflags=-DDEBIAN -D_FORTIFY_SOURCE=2 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Dldflags= -Wl,-z,relro -Dlddlflags=-shared -Wl,-z,relro -Dcccdlflags=-fPIC -Darchname=x86_64-linux-gnu -Dprefix=/usr -Dprivlib=/usr/share/perl/5.14 -Darchlib=/usr/lib/perl/5.14 -Dvendorprefix=/usr -Dvendorlib=/usr/share/perl5 -Dvendorarch=/usr/lib/perl5 -Dsiteprefix=/usr/local -Dsitelib=/usr/local/share/perl/5.14.2 -Dsitearch=/usr/local/lib/perl/5.14.2 -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 -Dsiteman1dir=/usr/local/man/man1 -Dsiteman3dir=/usr/local/man/man3 -Duse64bitint -Dman1ext=1 -Dman3ext=3perl -Dpager=/usr/bin/sensible-pager -Uafs -Ud_csh -Ud_ualarm -Uusesfio -Uusenm -Ui_libutil -DDEBUGGING=-g -Doptimize=-O2 -Duseshrplib -Dlibperl=libperl.so.5.14.2 -des'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fstack-protector -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2 -g',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fstack-protector -fno-strict-aliasing -pipe -I/usr/local/include'
    ccversion='', gccversion='4.7.2', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib /lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib /usr/lib
    libs=-lgdbm -lgdbm_compat -ldb -ldl -lm -lpthread -lc -lcrypt
    perllibs=-ldl -lm -lpthread -lc -lcrypt
    libc=, so=so, useshrplib=true, libperl=libperl.so.5.14.2
    gnulibc_version='2.13'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib -fstack-protector'

Locally applied patches:
    


@INC for perl 5.14.2:
    /home/hakon/perl5/lib/perl5/x86_64-linux-gnu-thread-multi
    /home/hakon/perl5/lib/perl5/x86_64-linux-gnu-thread-multi
    /home/hakon/perl5/lib/perl5
    /etc/perl
    /usr/local/lib/perl/5.14.2
    /usr/local/share/perl/5.14.2
    /usr/lib/perl5
    /usr/share/perl5
    /usr/lib/perl/5.14
    /usr/share/perl/5.14
    /usr/local/lib/site_perl
    .


Environment for perl 5.14.2:
    HOME=/home/hakon
    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/hakon/bin:/home/hakon/perl5/bin:/usr/sbin/:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    PERL5LIB=/home/hakon/perl5/lib/perl5/x86_64-linux-gnu-thread-multi:/home/hakon/perl5/lib/perl5
    PERL_BADLANG (unset)
    PERL_LOCAL_LIB_ROOT=/home/hakon/perl5
    PERL_MB_OPT=--install_base /home/hakon/perl5
    PERL_MM_OPT=INSTALL_BASE=/home/hakon/perl5
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @jkeenan

On Mon May 27 13&#8203;:48&#8203;:42 2013\, haakonwikene@&#8203;gmail\.com wrote&#8203;:
> 
> This is a bug report for perl from haakonwikene@&#8203;gmail\.com\,
> generated with the help of perlbug 1\.39 running under perl 5\.14\.2\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
> 
> I just upgraded perl from 5\.16\.3\.3 \-> 5\.18\.0\-1\, which seems to be the
> cause a segfault in urxvt\.
> 
> backtrace&#8203;:
> \#0  0x00007f95045ed4dc in Perl\_sv\_vcatpvfn\_flags \(\)
>    from /usr/lib/perl5/core\_perl/CORE/libperl\.so
> \#1  0x00007f95045f0072 in Perl\_sv\_vsetpvfn \(\) from
>    /usr/lib/perl5/core\_perl/CORE/libperl\.so
> \#2  0x00007f95045f00f5 in Perl\_vnewSVpvf \(\) from
>    /usr/lib/perl5/core\_perl/CORE/libperl\.so
> \#3  0x00007f95045f0257 in Perl\_newSVpvf \(\) from
>    /usr/lib/perl5/core\_perl/CORE/libperl\.so
> \#4  0x00007f95045cacb6 in Perl\_xs\_apiversion\_bootcheck \(\)
>       from /usr/lib/perl5/core\_perl/CORE/libperl\.so
> \#5  0x000000000043a99c in boot\_urxvt \(\)
> \#6  0x00007f95045e9821 in Perl\_pp\_entersub \(\) from
>    /usr/lib/perl5/core\_perl/CORE/libperl\.so
> \#7  0x00007f95045e1e26 in Perl\_runops\_standard \(\)
>          from /usr/lib/perl5/core\_perl/CORE/libperl\.so
> \#8  0x00007f95045733b0 in Perl\_call\_sv \(\) from
>    /usr/lib/perl5/core\_perl/CORE/libperl\.so
> \#9  0x00007f9504575477 in Perl\_call\_list \(\) from
>    /usr/lib/perl5/core\_perl/CORE/libperl\.so
> \#10 0x00007f950455b48f in S\_process\_special\_blocks \(\)
>             from /usr/lib/perl5/core\_perl/CORE/libperl\.so
> \#11 0x00007f950456ca9c in Perl\_newATTRSUB\_flags \(\)
>                from /usr/lib/perl5/core\_perl/CORE/libperl\.so
> \#12 0x00007f950456d5f0 in Perl\_newATTRSUB \(\) from
>    /usr/lib/perl5/core\_perl/CORE/libperl\.so
> \#13 0x00007f95045a0094 in Perl\_yyparse \(\) from
>    /usr/lib/perl5/core\_perl/CORE/libperl\.so
> \#14 0x00007f950457915c in perl\_parse \(\) from
>    /usr/lib/perl5/core\_perl/CORE/libperl\.so
> \#15 0x0000000000455a73 in rxvt\_perl\_interp&#8203;::init\(\) \(\)
> \#16 0x0000000000455b0b in rxvt\_perl\_interp&#8203;::init\(rxvt\_term\*\) \(\)
> \#17 0x00000000004243fc in rxvt\_term&#8203;::init\_resources\(int\, char const\*
>    const\*\) \(\)
> \#18 0x000000000042578a in rxvt\_term&#8203;::init2\(int\, char const\* const\*\) \(\)
> \#19 0x000000000041883c in main \(\)
> 
> 
> \[Please do not change anything below this line\]
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \-\-\-
> Flags&#8203;:
>     category=core
>     severity=low
> \-\-\-
> Site configuration information for perl 5\.14\.2&#8203;:
> 
> Configured by Debian Project at Wed Apr 10 16&#8203;:58&#8203;:16 UTC 2013\.
> 
> Summary of my perl5 \(revision 5 version 14 subversion 2\)
>    configuration&#8203;:
> 
>   Platform&#8203;:
>     osname=linux\, osvers=3\.2\.0\-4\-amd64\, archname=x86\_64\-linux\-gnu\-
>    thread\-multi
>     uname='linux madeleine 3\.2\.0\-4\-amd64 \#1 smp debian 3\.2\.39\-2 x86\_64
>    gnulinux '
>     config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN
>    \-D\_FORTIFY\_SOURCE=2 \-g \-O2 \-fstack\-protector
>    \-\-param=ssp\-buffer\-size=4 \-Wformat \-Werror=format\-security
>    \-Dldflags= \-Wl\,\-z\,relro \-Dlddlflags=\-shared \-Wl\,\-z\,relro
>    \-Dcccdlflags=\-fPIC \-Darchname=x86\_64\-linux\-gnu \-Dprefix=/usr
>    \-Dprivlib=/usr/share/perl/5\.14 \-Darchlib=/usr/lib/perl/5\.14
>    \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5
>    \-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local
>    \-Dsitelib=/usr/local/share/perl/5\.14\.2
>    \-Dsitearch=/usr/local/lib/perl/5\.14\.2 \-Dman1dir=/usr/share/man/man1
>    \-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1
>    \-Dsiteman3dir=/usr/local/man/man3 \-Duse64bitint \-Dman1ext=1
>    \-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh
>    \-Ud\_ualarm \-Uusesfio \-Uusenm \-Ui\_libutil \-DDEBUGGING=\-g
>    \-Doptimize=\-O2 \-Duseshrplib \-Dlibperl=libperl\.so\.5\.14\.2 \-des'


That's certainly an abundance of configuration options\.  May I suggest
starting with just '\-des' and adding options until you get to the
problem you describe?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon May 27 13&#8203;:48&#8203;:42 2013\, haakonwikene@&#8203;gmail\.com wrote&#8203;:
> I just upgraded perl from 5\.16\.3\.3 \-> 5\.18\.0\-1\, which seems to be the
> cause a segfault in urxvt\.

perl5\-porters don't distribute a version 5\.16\.3\.3 or 5\.18\.0\-1\.

You might want to start with a Debian bug report\.

Also the version information in your report is unrelated to either of
those versions\.

If you did install 5\.18\.0 from source over 5\.16\.3 you may need to
rebuild rxvt too\, the perl ABI isn't stable between major releases\.

Tony

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, May 27\, 2013 at 04&#8203;:14&#8203;:49PM \-0700\, Tony Cook via RT wrote&#8203;:
> On Mon May 27 13&#8203;:48&#8203;:42 2013\, haakonwikene@&#8203;gmail\.com wrote&#8203;:
> > I just upgraded perl from 5\.16\.3\.3 \-> 5\.18\.0\-1\, which seems to be the
> > cause a segfault in urxvt\.
> 
> perl5\-porters don't distribute a version 5\.16\.3\.3 or 5\.18\.0\-1\.
> 
> You might want to start with a Debian bug report\.
> 
> Also the version information in your report is unrelated to either of
> those versions\.
> 
> If you did install 5\.18\.0 from source over 5\.16\.3 you may need to
> rebuild rxvt too\, the perl ABI isn't stable between major releases\.

Especially as the code is crashing at a point in
Perl\_xs\_apiversion\_bootcheck where it's formatting a "version mismatch"
error&#8203;:


> \#3  0x00007f95045f0257 in Perl\_newSVpvf \(\) from
>    /usr/lib/perl5/core\_perl/CORE/libperl\.so
> \#4  0x00007f95045cacb6 in Perl\_xs\_apiversion\_bootcheck \(\)
>       from /usr/lib/perl5/core\_perl/CORE/libperl\.so

&nbsp;    xpt = Perl\_newSVpvf\(aTHX\_ "Perl API version %"SVf
&nbsp;                " of %"SVf" does not match %"SVf\,
&nbsp;                compver\_string\, module\, runver\_string\);

\-\- 
Indomitable in retreat\, invincible in advance\, insufferable in victory
&nbsp;    \-\- Churchill on Montgomery

**Comment by p5pRT** [comment]
### From @hakon1912

On Tue\, May 28\, 2013 at 1&#8203;:14 AM\, Tony Cook via RT
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> Also the version information in your report is unrelated to either of
> those versions\.

Sooo\.\.\. I just realised I sent the bug report from the wrong machine\.\.\.\. Sorry
about that\.

Upgrading rxvt solved the problem\.

**Comment by p5pRT** [comment]
### From @jkeenan

On Tue May 28 17&#8203;:24&#8203;:35 2013\, haakonwikene@&#8203;gmail\.com wrote&#8203;:
> On Tue\, May 28\, 2013 at 1&#8203;:14 AM\, Tony Cook via RT
> \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> > Also the version information in your report is unrelated to either
> of
> > those versions\.
> 
> Sooo\.\.\. I just realised I sent the bug report from the wrong
> machine\.\.\.\. Sorry
> about that\.
> 
> Upgrading rxvt solved the problem\.
> 

Closing per request from original poster\.  Thank you very much\.

**Comment by p5pRT** [comment]
@jkeenan - Status changed from 'open' to 'resolved'
