### ISSUE TITLE
lexical subs code segmentation fault

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#13034]
Migrated from [rt.perl.org#118521](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=118521) (status was 'resolved')

Searchable as RT118521$

**Comment by p5pRT** [comment]
### From @mauke

#### Created by @mauke



% perl \-we 'use feature qw\(lexical\_subs\); my sub foo; sub foo \{ foo \} foo'
The lexical\_subs feature is experimental at \-e line 1\.
zsh&#8203;: segmentation fault  perl \-we 'use feature qw\(lexical\_subs\); my sub foo; sub foo \{ foo \} foo'

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

This perlbug was built using Perl 5.12.1 - Thu Jun  3 20:09:15 CEST 2010
It is being executed now by  Perl 5.18.0 - Fri May 24 23:20:48 CEST 2013.

Site configuration information for perl 5.18.0:

Configured by mauke at Fri May 24 23:20:48 CEST 2013.

Summary of my perl5 (revision 5 version 18 subversion 0) configuration:
   
  Platform:
    osname=linux, osvers=3.5.7-gentoo, archname=i686-linux
    uname='linux nora 3.5.7-gentoo #5 preempt sat jan 26 16:46:10 cet 2013 i686 amd athlon(tm) 64 processor 3200+ authenticamd gnulinux '
    config_args=''
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=undef, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2 -flto',
    cppflags='-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.8.0', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags ='-fstack-protector -L/usr/local/lib -O2 -flto'
    libpth=/usr/local/lib /lib/../lib /usr/lib/../lib /lib /usr/lib
    libs=-lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/libc-2.15.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.15'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -flto -L/usr/local/lib -fstack-protector'

Locally applied patches:
    SAVEARGV0 - disable magic open in <ARGV>


@INC for perl 5.18.0:
    /home/mauke/usr/local/lib/perl5/site_perl/5.18.0/i686-linux
    /home/mauke/usr/local/lib/perl5/site_perl/5.18.0
    /home/mauke/usr/local/lib/perl5/5.18.0/i686-linux
    /home/mauke/usr/local/lib/perl5/5.18.0
    .


Environment for perl 5.18.0:
    HOME=/home/mauke
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_COLLATE=POSIX
    LD_LIBRARY_PATH=/home/mauke/usr/local/lib
    LOGDIR (unset)
    PATH=/home/mauke/usr/perlbrew/bin:/home/mauke/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/i686-pc-linux-gnu/gcc-bin/4.6.3:/opt/sun-jdk-1.4.2.13/bin:/opt/sun-jdk-1.4.2.13/jre/bin:/opt/sun-jdk-1.4.2.13/jre/javaws:/opt/dmd/bin:/usr/games/bin
    PERLBREW_BASHRC_VERSION=0.43
    PERLBREW_HOME=/home/mauke/.perlbrew
    PERLBREW_PATH=/home/mauke/usr/perlbrew/bin
    PERLBREW_ROOT=/home/mauke/usr/perlbrew
    PERLBREW_VERSION=0.27
    PERL_BADLANG (unset)
    PERL_UNICODE=SAL
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @mauke

On Mon Jun 17 15&#8203;:05&#8203;:20 2013\, mauke\- wrote&#8203;:
> % perl \-we 'use feature qw\(lexical\_subs\); my sub foo; sub foo \{ foo \}
>    foo'
> The lexical\_subs feature is experimental at \-e line 1\.
> zsh&#8203;: segmentation fault  perl \-we 'use feature qw\(lexical\_subs\); my
>    sub foo; sub foo \{ foo \} foo'

The lexical\_subs feature is experimental at \-e line 1\.

Program received signal SIGSEGV\, Segmentation fault\.
Perl\_gv\_efullname4 \(sv=sv@&#8203;entry=0x82e2c78\, gv=0x0\, prefix=prefix@&#8203;entry=0x0\, 
&nbsp;    keepmain=keepmain@&#8203;entry=true\) at gv\.c&#8203;:2070
2070        const GV \* const egv = GvEGVx\(gv\);
\(gdb\) bt
\#0  Perl\_gv\_efullname4 \(sv=sv@&#8203;entry=0x82e2c78\, gv=0x0\,
prefix=prefix@&#8203;entry=0x0\, 
&nbsp;    keepmain=keepmain@&#8203;entry=true\) at gv\.c&#8203;:2070
\#1  0x08139750 in Perl\_sub\_crush\_depth \(cv=cv@&#8203;entry=0x82d4dd8\) at
pp\_hot\.c&#8203;:2899
\#2  0x0813a84b in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:2842
\#3  0x081057b0 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2213
\#4  0x0808d9e8 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2467
\#5  perl\_run \(my\_perl=0x82c1008\) at perl\.c&#8203;:2383
\#6  0x08063833 in main \(argc=3\, argv=0xbfffeb24\, env=0xbfffeb34\) at
perlmain\.c&#8203;:114
\(gdb\)

**Comment by p5pRT** [comment]
### From @Leont

On Tue\, Jun 18\, 2013 at 12&#8203;:05 AM\, l\.mai@&#8203;web\.de
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> % perl \-we 'use feature qw\(lexical\_subs\); my sub foo; sub foo \{ foo \} foo'
> The lexical\_subs feature is experimental at \-e line 1\.
> zsh&#8203;: segmentation fault  perl \-we 'use feature qw\(lexical\_subs\); my sub foo; sub foo \{ foo \} foo'

It seems it tries to lookup use the GV for the deep recursion warning\,
but doesn't take into account that the CV might not have a CvGV\. I'm
not sure what's the right way to lookup the name of a lexical sub
though\.

Leon

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Mon Jun 17 15&#8203;:44&#8203;:02 2013\, LeonT wrote&#8203;:
> On Tue\, Jun 18\, 2013 at 12&#8203;:05 AM\, l\.mai@&#8203;web\.de
> \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> > % perl \-we 'use feature qw\(lexical\_subs\); my sub foo; sub foo \{ foo
> \} foo'
> > The lexical\_subs feature is experimental at \-e line 1\.
> > zsh&#8203;: segmentation fault  perl \-we 'use feature qw\(lexical\_subs\); my
> sub foo; sub foo \{ foo \} foo'
> 
> It seems it tries to lookup use the GV for the deep recursion warning\,
> but doesn't take into account that the CV might not have a CvGV\. I'm
> not sure what's the right way to lookup the name of a lexical sub
> though\.

CvNAME\_HEK\.  I’ll tackle this after I have finished with my
constant/PADTMP foray \(unless someone beats me to it :\-\)\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @mauke

On Mo\. 17\. Jun\. 2013\, 17&#8203;:57&#8203;:48\, sprout wrote&#8203;:
> On Mon Jun 17 15&#8203;:44&#8203;:02 2013\, LeonT wrote&#8203;:
> > On Tue\, Jun 18\, 2013 at 12&#8203;:05 AM\, l\.mai@&#8203;web\.de
> > \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> > > % perl \-we 'use feature qw\(lexical\_subs\); my sub foo; sub foo \{ foo
> > \} foo'
> > > The lexical\_subs feature is experimental at \-e line 1\.
> > > zsh&#8203;: segmentation fault  perl \-we 'use feature qw\(lexical\_subs\); my
> > sub foo; sub foo \{ foo \} foo'
> > 
> > It seems it tries to lookup use the GV for the deep recursion warning\,
> > but doesn't take into account that the CV might not have a CvGV\. I'm
> > not sure what's the right way to lookup the name of a lexical sub
> > though\.
> 
> CvNAME\_HEK\.  I’ll tackle this after I have finished with my
> constant/PADTMP foray \(unless someone beats me to it :\-\)\.
 
I've attached a patch\. Is this what you meant by CvNAME\_HEK?

**Comment by p5pRT** [comment]
### From @mauke

<details><summary>0001-don-t-crash-on-deep-recursion-warnings-in-lexical-su[1].patch</summary>

```diff
From 32f3fbcadfe0a9d381c145edd3f74b242d67e7b2 Mon Sep 17 00:00:00 2001
From: Lukas Mai <l.mai@web.de>
Date: Tue, 18 Jun 2013 09:51:32 +0200
Subject: [PATCH] don't crash on deep recursion warnings in lexical subs
 (#118521)
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="------------1.8.1.5"

This is a multi-part message in MIME format.
--------------1.8.1.5
Content-Type: text/plain; charset=UTF-8; format=fixed
Content-Transfer-Encoding: 8bit

---
 pp_hot.c      | 17 ++++++++++++-----
 t/op/lexsub.t | 10 +++++++++-
 2 files changed, 21 insertions(+), 6 deletions(-)


--------------1.8.1.5
Content-Type: text/x-patch; name="0001-don-t-crash-on-deep-recursion-warnings-in-lexical-su.patch"
Content-Transfer-Encoding: 8bit
Content-Disposition: attachment; filename="0001-don-t-crash-on-deep-recursion-warnings-in-lexical-su.patch"

diff --git a/pp_hot.c b/pp_hot.c
index e19776b..5cfe4b0 100644
--- a/pp_hot.c
+++ b/pp_hot.c
@@ -2893,12 +2893,19 @@ Perl_sub_crush_depth(pTHX_ CV *cv)
     PERL_ARGS_ASSERT_SUB_CRUSH_DEPTH;
 
     if (CvANON(cv))
-	Perl_warner(aTHX_ packWARN(WARN_RECURSION), "Deep recursion on anonymous subroutine");
+        Perl_warner(aTHX_ packWARN(WARN_RECURSION), "Deep recursion on anonymous subroutine");
     else {
-	SV* const tmpstr = sv_newmortal();
-	gv_efullname3(tmpstr, CvGV(cv), NULL);
-	Perl_warner(aTHX_ packWARN(WARN_RECURSION), "Deep recursion on subroutine \"%"SVf"\"",
-		    SVfARG(tmpstr));
+        HEK *const hek = CvNAME_HEK(cv);
+        SV *tmpstr;
+        if (hek) {
+            tmpstr = sv_2mortal(newSVhek(hek));
+        }
+        else {
+            tmpstr = sv_newmortal();
+            gv_efullname3(tmpstr, CvGV(cv), NULL);
+        }
+        Perl_warner(aTHX_ packWARN(WARN_RECURSION), "Deep recursion on subroutine \"%"SVf"\"",
+                    SVfARG(tmpstr));
     }
 }
 
diff --git a/t/op/lexsub.t b/t/op/lexsub.t
index d70f2cc..27b6de7 100644
--- a/t/op/lexsub.t
+++ b/t/op/lexsub.t
@@ -8,7 +8,7 @@ BEGIN {
     *bar::like = *like;
 }
 no warnings 'deprecated';
-plan 134;
+plan 135;
 
 # -------------------- Errors with feature disabled -------------------- #
 
@@ -695,3 +695,11 @@ eval 'sub not_lexical7 { my @x }';
     }
   }
 }
+
+like runperl(
+      switches => [ '-Mfeature=:all', '-Mwarnings=FATAL,all', '-M-warnings=experimental::lexical_subs' ],
+      prog     => 'my sub foo; sub foo { foo } foo',
+      stderr   => 1
+     ),
+     qr/Deep recursion on subroutine "foo"/,
+    'deep recursion warnings for lexical subs do not crash';

--------------1.8.1.5--



```
</details>

**Comment by p5pRT** [comment]
### From @cpansprout

On Tue Jun 18 00&#8203;:58&#8203;:28 2013\, mauke\- wrote&#8203;:
> On Mo\. 17\. Jun\. 2013\, 17&#8203;:57&#8203;:48\, sprout wrote&#8203;:
> > On Mon Jun 17 15&#8203;:44&#8203;:02 2013\, LeonT wrote&#8203;:
> > > On Tue\, Jun 18\, 2013 at 12&#8203;:05 AM\, l\.mai@&#8203;web\.de
> > > \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> > > > % perl \-we 'use feature qw\(lexical\_subs\); my sub foo; sub foo \{ foo
> > > \} foo'
> > > > The lexical\_subs feature is experimental at \-e line 1\.
> > > > zsh&#8203;: segmentation fault  perl \-we 'use feature qw\(lexical\_subs\); my
> > > sub foo; sub foo \{ foo \} foo'
> > > 
> > > It seems it tries to lookup use the GV for the deep recursion warning\,
> > > but doesn't take into account that the CV might not have a CvGV\. I'm
> > > not sure what's the right way to lookup the name of a lexical sub
> > > though\.
> > 
> > CvNAME\_HEK\.  I’ll tackle this after I have finished with my
> > constant/PADTMP foray \(unless someone beats me to it :\-\)\.
>  
> I've attached a patch\. Is this what you meant by CvNAME\_HEK?

Yes\.  Thank you for beating me to it\.  I have applied your patch as
07b2687d2246\.


\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
