### ISSUE TITLE
usemymalloc cannot handle long strings

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#13273]
Migrated from [rt.perl.org#119829](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=119829) (status was 'resolved')

Searchable as RT119829$

**Comment by p5pRT** [comment]
### From @cpansprout

usemymalloc cannot handle long strings

$ \./perl \-Ilib \-e 'my $x=" "x\($\{\\2\}\*\*31\+20\);'
Segmentation fault&#8203;: 11

\(gdb\) bt
\#0  0x000000010007ac70 in fill\_pat\_4bytes \(s=0x1009eda00 "ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??ޭ??"\.\.\.\, nbytes=2147487744\, fill=0x1004a9840 "ޭ??ޭ??ޭ??ޭ??????????????????AUTOLOAD"\) at malloc\.c&#8203;:1158
\#1  0x000000010007a51f in morecore \(bucket=31\) at malloc\.c&#8203;:1772
\#2  0x00000001000793ec in Perl\_malloc \(nbytes=2147479588\) at malloc\.c&#8203;:1287
\#3  0x000000010007bcd7 in Perl\_realloc \(mp=0x1009a9468\, nbytes=2147483670\) at malloc\.c&#8203;:2097
\#4  0x000000010025d62c in Perl\_sv\_grow \(my\_perl=0x100803200\, sv=0x100997460\, newlen=2147483670\) at sv\.c&#8203;:1532
\#5  0x000000010030b6b7 in Perl\_pp\_repeat \(my\_perl=0x100803200\) at pp\.c&#8203;:1729
\#6  0x00000001001b016c in Perl\_runops\_debug \(my\_perl=0x100803200\) at dump\.c&#8203;:2261
\#7  0x0000000100060702 in S\_run\_body \(my\_perl=0x100803200\, oldscope=1\) at perl\.c&#8203;:2500
\#8  0x000000010005f6d5 in perl\_run \(my\_perl=0x100803200\) at perl\.c&#8203;:2416
\#9  0x0000000100001428 in main \(argc=3\, argv=0x7fff5fbffa80\, env=0x7fff5fbffaa0\) at perlmain\.c&#8203;:112

For me\, it happens with any number larger than 1073745906\.

$ \./perl \-Ilib \-e 'my $x=" "x 1073745907'
Segmentation fault&#8203;: 11

I am also compiling with mad\+threads\, if that makes any difference\.


Summary of my perl5 \(revision 5 version 19 subversion 3\) configuration&#8203;:
&nbsp;  Commit id&#8203;: a496ca38c9dd66846ae327cc193078aee36ae004
&nbsp;  Platform&#8203;:
&nbsp;    osname=darwin\, osvers=12\.2\.0\, archname=darwin\-thread\-multi\-2level
&nbsp;    uname='darwin pint\.local 12\.2\.0 darwin kernel version 12\.2\.0&#8203;: sat aug 25 00&#8203;:48&#8203;:52 pdt 2012; root&#8203;:xnu\-2050\.18\.24~1release\_x86\_64 x86\_64 '
&nbsp;    config\_args='\-Dusemymalloc \-Duseithreads \-Dmad \-de \-Dusedevel \-Doptimize=\-ggdb3 \-Aoptimize=\-O0 \-DDEBUGGING'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=y\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-fno\-common \-DPERL\_DARWIN \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'\,
&nbsp;    optimize='\-ggdb3 \-O0'\,
&nbsp;    cppflags='\-fno\-common \-DPERL\_DARWIN \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.2\.1 Compatible Apple LLVM 4\.2 \(clang\-425\.0\.27\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='env MACOSX\_DEPLOYMENT\_TARGET=10\.3 cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib
&nbsp;    libs=\-ldbm \-ldl \-lm \-lutil \-lc
&nbsp;    perllibs=\-ldl \-lm \-lutil \-lc
&nbsp;    libc=\, so=dylib\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=bundle\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags=' '\, lddlflags=' \-bundle \-undefined dynamic\_lookup \-L/usr/local/lib \-fstack\-protector'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES MULTIPLICITY MYMALLOC
&nbsp;                        PERLIO\_LAYERS PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD
&nbsp;                        PERL\_IMPLICIT\_CONTEXT PERL\_MAD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_NEW\_COPY\_ON\_WRITE PERL\_PRESERVE\_IVUV
&nbsp;                        PERL\_TRACK\_MEMPOOL PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_ITHREADS USE\_LARGE\_FILES
&nbsp;                        USE\_LOCALE USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_PERLIO USE\_PERL\_ATOF
&nbsp;                        USE\_REENTRANT\_API
&nbsp;  Built under darwin
&nbsp;  Compiled at Aug 11 2013 14&#8203;:54&#8203;:13
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.19\.3/darwin\-thread\-multi\-2level
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.19\.3
&nbsp;    /usr/local/lib/perl5/5\.19\.3/darwin\-thread\-multi\-2level
&nbsp;    /usr/local/lib/perl5/5\.19\.3
&nbsp;    /usr/local/lib/perl5/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Fixed in commit 64072da0d64f4e24d5d3f53f391a1fb7a5121ac0\.

\-zefram

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
