### ISSUE TITLE
a2p access before start of buffer

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#13351]
Migrated from [rt.perl.org#120244](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=120244) (status was 'resolved')

Searchable as RT120244$

**Comment by p5pRT** [comment]
### From guenther@openbsd.org


This is a bug report for perl from guenther@&#8203;openbsd\.org\,
generated with the help of perlbug 1\.39 running under perl 5\.16\.3\.



---
a2p can try to access before the beginning of a buffer\, which is
undefined behavior of course and leads to crashes\.  Example input
file which triggers this\, truncated down to right after the point
a2p crashes on it\.



---
\#    $OpenBSD&#8203;: parse\_structinfo\.awk\,v 1\.1 2009/08/09 23&#8203;:04&#8203;:49 miod Exp $
\#
\# Copyright \(c\) 2009 Miodrag Vallat\.
\#
\# Permission to use\, copy\, modify\, and distribute this software for any
\# purpose with or without fee is hereby granted\, provided that the above
\# copyright notice and this permission notice appear in all copies\.
\#
\# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
\# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
\# MERCHANTABILITY AND FITNESS\. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
\# ANY SPECIAL\, DIRECT\, INDIRECT\, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
\# WHATSOEVER RESULTING FROM LOSS OF USE\, DATA OR PROFITS\, WHETHER IN AN
\# ACTION OF CONTRACT\, NEGLIGENCE OR OTHER TORTIOUS ACTION\, ARISING OUT OF
\# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE\.
\#



---
Backtrace from core&#8203;:

\#0  0x0000168c98703d68 in str\_gets \(str=0x168e9fd35200\, fp=0x168e9e16ef00\)
&nbsp;    at str\.c&#8203;:203
203                     if \(bp \<= str\->str\_ptr || bp\[\-2\] \!= '\\\\'\)
\(gdb\) bt
\#0  0x0000168c98703d68 in str\_gets \(str=0x168e9fd35200\, fp=0x168e9e16ef00\)
&nbsp;    at str\.c&#8203;:203
\#1  0x0000168c9870b8bf in yylex \(\) from /tmp/a2p
\#2  0x0000168c9870ea2c in yyparse \(\) from /tmp/a2p
\#3  0x0000168c9870fe20 in main \(\) from /tmp/a2p
\(gdb\) p bp \- str\->str\_ptr
$1 = 1
\(gdb\) 


Fix&#8203;:

Index&#8203;: gnu/usr\.bin/perl/x2p/str\.c
===================================================================
RCS file&#8203;: /cvs/src/gnu/usr\.bin/perl/x2p/str\.c\,v
retrieving revision 1\.12
diff \-u \-p \-r1\.12 str\.c
\-\-\- gnu/usr\.bin/perl/x2p/str\.c    25 Mar 2013 20&#8203;:41&#8203;:01 \-0000    1\.12
\+\+\+ gnu/usr\.bin/perl/x2p/str\.c    1 Oct 2013 22&#8203;:42&#8203;:05 \-0000
@&#8203;@&#8203; \-200\,7 \+200\,7 @&#8203;@&#8203; str\_gets\(register STR \*str\, register FIL
&nbsp;     for \(;;\) \{
&nbsp;     while \(\-\-cnt >= 0\) \{
&nbsp;         if \(\(\*bp\+\+ = \*ptr\+\+\) == newline\) \{
\-        if \(bp \<= str\->str\_ptr || bp\[\-2\] \!= '\\\\'\)
\+        if \(bp \<= str\->str\_ptr \+ 1 || bp\[\-2\] \!= '\\\\'\)
&nbsp;             goto thats\_all\_folks;
&nbsp;         else \{
&nbsp;             line\+\+;

Philip Guenther



---


---
Flags&#8203;:
&nbsp;    category=utilities
&nbsp;    severity=high


---
Site configuration information for perl 5\.16\.3&#8203;:

Configured by root at Thu Jan  1  0&#8203;:00&#8203;:00 UTC 1970\.

Summary of my perl5 \(revision 5 version 16 subversion 3\) configuration&#8203;:
&nbsp;   
&nbsp;  Platform&#8203;:
&nbsp;    osname=openbsd\, osvers=5\.4\, archname=amd64\-openbsd
&nbsp;    uname='openbsd'
&nbsp;    config\_args='\-dsE \-Dopenbsd\_distribution=defined \-Dccflags=\-DNO\_LOCALE\_NUMERIC \-DNO\_LOCALE\_COLLATE \-Dmksymlinks'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-DNO\_LOCALE\_NUMERIC \-DNO\_LOCALE\_COLLATE \-fno\-strict\-aliasing \-fno\-delete\-null\-pointer\-checks \-pipe \-fstack\-protector \-I/usr/local/include'\,
&nbsp;    optimize='\-O2'\,
&nbsp;    cppflags='\-DNO\_LOCALE\_NUMERIC \-DNO\_LOCALE\_COLLATE \-fno\-strict\-aliasing \-fno\-delete\-null\-pointer\-checks \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.2\.1 20070719 '\, gccosandvers='openbsd5\.4'
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags ='\-Wl\,\-E  \-fstack\-protector'
&nbsp;    libpth=/usr/lib
&nbsp;    libs=\-lm \-lutil \-lc
&nbsp;    perllibs=\-lm \-lutil \-lc
&nbsp;    libc=/usr/lib/libc\.so\.70\.0\, so=so\, useshrplib=true\, libperl=libperl\.so\.14\.0
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-R/usr/libdata/perl5/amd64\-openbsd/5\.16\.3/CORE'
&nbsp;    cccdlflags='\-DPIC \-fPIC '\, lddlflags='\-shared \-fPIC  \-fstack\-protector'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl 5\.16\.3&#8203;:
&nbsp;    /usr/local/libdata/perl5/site\_perl/amd64\-openbsd
&nbsp;    /usr/libdata/perl5/site\_perl/amd64\-openbsd
&nbsp;    /usr/local/libdata/perl5/site\_perl
&nbsp;    /usr/libdata/perl5/site\_perl
&nbsp;    /usr/libdata/perl5/amd64\-openbsd/5\.16\.3
&nbsp;    /usr/local/libdata/perl5/amd64\-openbsd/5\.16\.3
&nbsp;    /usr/libdata/perl5
&nbsp;    /usr/local/libdata/perl5
&nbsp;    \.



---
Environment for perl 5\.16\.3&#8203;:
&nbsp;    HOME=/home/users/guenther
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/users/guenther/bin&#8203;:/usr/local/bin&#8203;:/bin&#8203;:/usr/bin&#8203;:/usr/local/sbin&#8203;:/sbin&#8203;:/usr/sbin&#8203;:/usr/X11R6/bin&#8203;:/usr/games
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/ksh

**Comment by p5pRT** [comment]
### From @jkeenan

On Wed Oct 16 22&#8203;:12&#8203;:32 2013\, guenther@&#8203;openbsd\.org wrote&#8203;:
> 
> This is a bug report for perl from guenther@&#8203;openbsd\.org\,
> generated with the help of perlbug 1\.39 running under perl 5\.16\.3\.
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> 
> a2p can try to access before the beginning of a buffer\, which is
> undefined behavior of course and leads to crashes\.  Example input
> file which triggers this\, truncated down to right after the point
> a2p crashes on it\.
> 
> \-\-\-\-\-\-
> \#    $OpenBSD&#8203;: parse\_structinfo\.awk\,v 1\.1 2009/08/09 23&#8203;:04&#8203;:49 miod Exp $
> \#
> \# Copyright \(c\) 2009 Miodrag Vallat\.
> \#
> \# Permission to use\, copy\, modify\, and distribute this software for
> any
> \# purpose with or without fee is hereby granted\, provided that the
> above
> \# copyright notice and this permission notice appear in all copies\.
> \#
> \# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
> WARRANTIES
> \# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
> \# MERCHANTABILITY AND FITNESS\. IN NO EVENT SHALL THE AUTHOR BE LIABLE
> FOR
> \# ANY SPECIAL\, DIRECT\, INDIRECT\, OR CONSEQUENTIAL DAMAGES OR ANY
> DAMAGES
> \# WHATSOEVER RESULTING FROM LOSS OF USE\, DATA OR PROFITS\, WHETHER IN
> AN
> \# ACTION OF CONTRACT\, NEGLIGENCE OR OTHER TORTIOUS ACTION\, ARISING OUT
> OF
> \# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE\.
> \#
> 
> \-\-\-\-\-\-
> 
> Backtrace from core&#8203;:
> 
> \#0  0x0000168c98703d68 in str\_gets \(str=0x168e9fd35200\,
> fp=0x168e9e16ef00\)
>     at str\.c&#8203;:203
> 203                     if \(bp \<= str\->str\_ptr || bp\[\-2\] \!= '\\\\'\)
> \(gdb\) bt
> \#0  0x0000168c98703d68 in str\_gets \(str=0x168e9fd35200\,
> fp=0x168e9e16ef00\)
>     at str\.c&#8203;:203
> \#1  0x0000168c9870b8bf in yylex \(\) from /tmp/a2p
> \#2  0x0000168c9870ea2c in yyparse \(\) from /tmp/a2p
> \#3  0x0000168c9870fe20 in main \(\) from /tmp/a2p
> \(gdb\) p bp \- str\->str\_ptr
> $1 = 1
> \(gdb\)
> 
> 
> Fix&#8203;:
> 
> Index&#8203;: gnu/usr\.bin/perl/x2p/str\.c
> ===================================================================
> RCS file&#8203;: /cvs/src/gnu/usr\.bin/perl/x2p/str\.c\,v
> retrieving revision 1\.12
> diff \-u \-p \-r1\.12 str\.c
> \-\-\- gnu/usr\.bin/perl/x2p/str\.c    25 Mar 2013 20&#8203;:41&#8203;:01 \-0000    1\.12
> \+\+\+ gnu/usr\.bin/perl/x2p/str\.c    1 Oct 2013 22&#8203;:42&#8203;:05 \-0000
> @&#8203;@&#8203; \-200\,7 \+200\,7 @&#8203;@&#8203; str\_gets\(register STR \*str\, register FIL
>      for \(;;\) \{
>      while \(\-\-cnt >= 0\) \{
>          if \(\(\*bp\+\+ = \*ptr\+\+\) == newline\) \{
> \-        if \(bp \<= str\->str\_ptr || bp\[\-2\] \!= '\\\\'\)
> \+        if \(bp \<= str\->str\_ptr \+ 1 || bp\[\-2\] \!= '\\\\'\)
>              goto thats\_all\_folks;
>          else \{
>              line\+\+;
> 
> Philip Guenther
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \-\-\-
> Flags&#8203;:
>     category=utilities
>     severity=high
> \-\-\-
> Site configuration information for perl 5\.16\.3&#8203;:
> 
> Configured by root at Thu Jan  1  0&#8203;:00&#8203;:00 UTC 1970\.
> 
> Summary of my perl5 \(revision 5 version 16 subversion 3\)
> configuration&#8203;:
> 
>   Platform&#8203;:
>     osname=openbsd\, osvers=5\.4\, archname=amd64\-openbsd
>     uname='openbsd'
>     config\_args='\-dsE \-Dopenbsd\_distribution=defined
> \-Dccflags=\-DNO\_LOCALE\_NUMERIC \-DNO\_LOCALE\_COLLATE \-Dmksymlinks'
>     hint=recommended\, useposix=true\, d\_sigaction=define
>     useithreads=undef\, usemultiplicity=undef
>     useperlio=define\, d\_sfio=undef\, uselargefiles=define\,
> usesocks=undef
>     use64bitint=define\, use64bitall=define\, uselongdouble=undef
>     usemymalloc=n\, bincompat5005=undef
>   Compiler&#8203;:
>     cc='cc'\, ccflags ='\-DNO\_LOCALE\_NUMERIC \-DNO\_LOCALE\_COLLATE
> \-fno\-strict\-aliasing \-fno\-delete\-null\-pointer\-checks \-pipe
> \-fstack\-protector \-I/usr/local/include'\,
>     optimize='\-O2'\,
>     cppflags='\-DNO\_LOCALE\_NUMERIC \-DNO\_LOCALE\_COLLATE
> \-fno\-strict\-aliasing \-fno\-delete\-null\-pointer\-checks \-pipe
> \-fstack\-protector \-I/usr/local/include'
>     ccversion=''\, gccversion='4\.2\.1 20070719 '\,
> gccosandvers='openbsd5\.4'
>     intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
>     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\,
> longdblsize=16
>     ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,
> lseeksize=8
>     alignbytes=8\, prototype=define
>   Linker and Libraries&#8203;:
>     ld='cc'\, ldflags ='\-Wl\,\-E  \-fstack\-protector'
>     libpth=/usr/lib
>     libs=\-lm \-lutil \-lc
>     perllibs=\-lm \-lutil \-lc
>     libc=/usr/lib/libc\.so\.70\.0\, so=so\, useshrplib=true\,
> libperl=libperl\.so\.14\.0
>     gnulibc\_version=''
>   Dynamic Linking&#8203;:
>     dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-
> R/usr/libdata/perl5/amd64\-openbsd/5\.16\.3/CORE'
>     cccdlflags='\-DPIC \-fPIC '\, lddlflags='\-shared \-fPIC
> \-fstack\-protector'
> 
> Locally applied patches&#8203;:
> 
> 
> \-\-\-
> @&#8203;INC for perl 5\.16\.3&#8203;:
>     /usr/local/libdata/perl5/site\_perl/amd64\-openbsd
>     /usr/libdata/perl5/site\_perl/amd64\-openbsd
>     /usr/local/libdata/perl5/site\_perl
>     /usr/libdata/perl5/site\_perl
>     /usr/libdata/perl5/amd64\-openbsd/5\.16\.3
>     /usr/local/libdata/perl5/amd64\-openbsd/5\.16\.3
>     /usr/libdata/perl5
>     /usr/local/libdata/perl5
>     \.
> 
> \-\-\-
> Environment for perl 5\.16\.3&#8203;:
>     HOME=/home/users/guenther
>     LANG \(unset\)
>     LANGUAGE \(unset\)
>     LD\_LIBRARY\_PATH \(unset\)
>     LOGDIR \(unset\)
>    
PATH=/home/users/guenther/bin&#8203;:/usr/local/bin&#8203;:/bin&#8203;:/usr/bin&#8203;:/usr/local/sbin&#8203;:/sbin&#8203;:/usr/sbin&#8203;:/usr/X11R6/bin&#8203;:/usr/games
>     PERL\_BADLANG \(unset\)
>     SHELL=/bin/ksh


I tried to reproduce this problem on blead on our dromedary server\,
which is Linux x86\_64\.  I could not\.  My calls and results&#8203;:

\#\#\#\#\#\#\#\#\#\#
$ \./x2p/a2p \.\./p5p/parse\_structinfo\.awk 

\#\!/usr/local/bin/perl5\.19\.5
eval 'exec /usr/local/bin/perl \-S $0 $\{1\+"$@&#8203;"\}'
&nbsp;    if $running\_under\_some\_shell;
&nbsp;                        \# this emulates \#\! processing on NIH machines\.
&nbsp;                        \# \(remove \#\! line above if indigestible\)

eval '$'\.$1\.'$2;' while $ARGV\[0\] =~ /^\(\[A\-Za\-z\_0\-9\]\+=\)\(\.\*\)/ && shift;
&nbsp;                        \# process any FOO=bar switches

\# $OpenBSD&#8203;: parse\_structinfo\.awk\,v 1\.1 2009/08/09 23&#8203;:04&#8203;:49 miod Exp $
\#
\# Copyright \(c\) 2009 Miodrag Vallat\.
\#
\# Permission to use\, copy\, modify\, and distribute this software for any
\# purpose with or without fee is hereby granted\, provided that the above
\# copyright notice and this permission notice appear in all copies\.
\#
\# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
\# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
\# MERCHANTABILITY AND FITNESS\. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
\# ANY SPECIAL\, DIRECT\, INDIRECT\, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
\# WHATSOEVER RESULTING FROM LOSS OF USE\, DATA OR PROFITS\, WHETHER IN AN
\# ACTION OF CONTRACT\, NEGLIGENCE OR OTHER TORTIOUS ACTION\, ARISING OUT OF
\# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE\.
\#

$ file x2p/a2p
x2p/a2p&#8203;: ELF 64\-bit LSB executable\, x86\-64\, version 1 \(SYSV\)\,
dynamically linked \(uses shared libs\)\, for GNU/Linux 2\.6\.18\, not stripped

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @jkeenan

On Thu Oct 17 16&#8203;:44&#8203;:13 2013\, jkeenan wrote&#8203;:
> 
> I tried to reproduce this problem on blead on our dromedary server\,
> which is Linux x86\_64\.  I could not\.  My calls and results&#8203;:
> 


I also tried to reproduce this problem on blead on Darwin 11\.4\.2 x86\_64\.  I could not\.  I got the 
same\, non\-crashing output as I did on Linux\.

Is there anyone on list who has access to OpenBSD who could look into this?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From guenther@sendmail.com

On Thu\, 17 Oct 2013\, James E Keenan via RT wrote&#8203;:
> I tried to reproduce this problem on blead on our dromedary server\, 
> which is Linux x86\_64\.  I could not\.  My calls and results&#8203;:

That just says that the malloc in that OS is more forgiving with access 
before the start of the buffer\.  OpenBSD's malloc is very unforgiving to 
find these sorts of issues\.  Perhaps valgrind would show the problem\.


Philip

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Oct 17\, 2013 at 04&#8203;:44&#8203;:14PM \-0700\, James E Keenan via RT wrote&#8203;:
> On Wed Oct 16 22&#8203;:12&#8203;:32 2013\, guenther@&#8203;openbsd\.org wrote&#8203;:
> > a2p can try to access before the beginning of a buffer\, which is
> > undefined behavior of course and leads to crashes\.  Example input
> > file which triggers this\, truncated down to right after the point
> > a2p crashes on it\.

> I tried to reproduce this problem on blead on our dromedary server\,
> which is Linux x86\_64\.  I could not\.  My calls and results&#8203;:

I also couldn't reproduce it \(even with valgrind\)\, but from visual
inspection the patch looked good\, so I've applied it as\,

&nbsp;    a7ed8fa56423636ca5e455bcd62684a54672da57

with thanks to the OP\.


\-\- 
Dave's first rule of Opera&#8203;:
If something needs saying\, say it&#8203;: don't warble it\.

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
