### ISSUE TITLE
Bleadperl recently introduced a new SEGV

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#13637]
Migrated from [rt.perl.org#121362](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=121362) (status was 'resolved')

Searchable as RT121362$

**Comment by p5pRT** [comment]
### From @andk

v5\.19\.9\-64\-g111f73b was the first perl on which I noticed a segv while
running the tests of RJBS/Number\-Tolerant\-1\.703\.tar\.gz

It's not bisectable because it's intermittent\.

\(gdb\) bt
\#0  malloc\_consolidate \(av=av@&#8203;entry=0x2b1a68423640 \<main\_arena>\)
&nbsp;    at malloc\.c&#8203;:4094
\#1  0x00002b1a680f8d77 in \_int\_malloc \(av=0x2b1a68423640 \<main\_arena>\, 
&nbsp;    bytes=4080\) at malloc\.c&#8203;:3379
\#2  0x00002b1a680fb083 in \_\_GI\_\_\_libc\_malloc \(bytes=4080\) at malloc\.c&#8203;:2859
\#3  0x000000000048ab42 in Perl\_safesysmalloc \(size=size@&#8203;entry=4080\)
&nbsp;    at util\.c&#8203;:130
\#4  0x00000000004b0a57 in Perl\_more\_bodies \(my\_perl=my\_perl@&#8203;entry=0x13ab010\, 
&nbsp;    sv\_type=sv\_type@&#8203;entry=SVt\_PVGV\, body\_size=body\_size@&#8203;entry=48\, 
&nbsp;    arena\_size=arena\_size@&#8203;entry=4080\) at sv\.c&#8203;:1059
\#5  0x00000000004b8084 in Perl\_sv\_upgrade \(my\_perl=my\_perl@&#8203;entry=0x13ab010\, 
&nbsp;    sv=sv@&#8203;entry=0x1e91cd8\, new\_type=new\_type@&#8203;entry=SVt\_PVGV\) at sv\.c&#8203;:1364
\#6  0x000000000043dd37 in Perl\_gv\_init\_pvn \(my\_perl=my\_perl@&#8203;entry=0x13ab010\, 
&nbsp;    gv=gv@&#8203;entry=0x1e91cd8\, stash=stash@&#8203;entry=0x1e913f0\, 
&nbsp;    name=name@&#8203;entry=0x14c74d0 "intersection"\, len=len@&#8203;entry=12\, 
&nbsp;    flags=flags@&#8203;entry=2\) at gv\.c&#8203;:366
\#7  0x000000000044146a in Perl\_gv\_fetchmeth\_pvn \(
&nbsp;    my\_perl=my\_perl@&#8203;entry=0x13ab010\, stash=stash@&#8203;entry=0x1e913f0\, 
&nbsp;    name=name@&#8203;entry=0x14c74d0 "intersection"\, len=len@&#8203;entry=12\, 
&nbsp;    level=level@&#8203;entry=0\, flags=flags@&#8203;entry=768\) at gv\.c&#8203;:700
\#8  0x000000000043ed3f in Perl\_gv\_fetchmethod\_pvn\_flags \(
&nbsp;    my\_perl=my\_perl@&#8203;entry=0x13ab010\, stash=stash@&#8203;entry=0x1e913f0\, 
&nbsp;    name=0x14c74d0 "intersection"\, len=\<optimized out>\, flags=768\) at gv\.c&#8203;:1002
\#9  0x000000000043f195 in Perl\_gv\_fetchmethod\_sv\_flags \(
&nbsp;    my\_perl=my\_perl@&#8203;entry=0x13ab010\, stash=0x1e913f0\, 
&nbsp;    namesv=namesv@&#8203;entry=0x1791f60\, flags=\<optimized out>\, flags@&#8203;entry=768\)
&nbsp;    at gv\.c&#8203;:935
\#10 0x00000000004a7e37 in S\_method\_common \(my\_perl=my\_perl@&#8203;entry=0x13ab010\, 
&nbsp;    meth=meth@&#8203;entry=0x1791f60\, hashp=hashp@&#8203;entry=0x7fff44c4c62c\)
&nbsp;    at pp\_hot\.c&#8203;:3081
\#11 0x00000000004b03e7 in Perl\_pp\_method\_named \(my\_perl=0x13ab010\)
&nbsp;    at pp\_hot\.c&#8203;:2961
\#12 0x00000000004a7ae6 in Perl\_runops\_standard \(my\_perl=0x13ab010\) at run\.c&#8203;:42
\#13 0x00000000004427e1 in Perl\_amagic\_call \(my\_perl=my\_perl@&#8203;entry=0x13ab010\, 
&nbsp;    left=left@&#8203;entry=0x13d8088\, right=\<optimized out>\, right@&#8203;entry=0x13d81a8\, 
&nbsp;    method=method@&#8203;entry=46\, flags=0\) at gv\.c&#8203;:3254
\#14 0x0000000000443a33 in Perl\_try\_amagic\_bin \(
&nbsp;    my\_perl=my\_perl@&#8203;entry=0x13ab010\, method=method@&#8203;entry=46\, 
&nbsp;    flags=flags@&#8203;entry=4\) at gv\.c&#8203;:2742
\#15 0x00000000004cea8a in Perl\_pp\_bit\_and \(my\_perl=0x13ab010\) at pp\.c&#8203;:2183
\#16 0x00000000004a7ae6 in Perl\_runops\_standard \(my\_perl=0x13ab010\) at run\.c&#8203;:42
\#17 0x000000000043cb84 in S\_run\_body \(oldscope=1\, my\_perl=0x13ab010\)
&nbsp;    at perl\.c&#8203;:2449
\#18 perl\_run \(my\_perl=0x13ab010\) at perl\.c&#8203;:2365
\#19 0x000000000041bdcb in main \(argc=2\, argv=0x7fff44c4ca08\, 
&nbsp;    env=0x7fff44c4ca20\) at perlmain\.c&#8203;:112


\-\- 
andreas

**Comment by p5pRT** [comment]
### From @khwilliamson

On 03/02/2014 09&#8203;:56 PM\, \(Andreas J\. Koenig\) \(via RT\) wrote&#8203;:
> \# New Ticket Created by  \(Andreas J\. Koenig\)
> \# Please include the string&#8203;:  \[perl \#121362\]
> \# in the subject line of all future correspondence about this issue\.
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=121362 >
>
>
> v5\.19\.9\-64\-g111f73b was the first perl on which I noticed a segv while
> running the tests of RJBS/Number\-Tolerant\-1\.703\.tar\.gz
>
> It's not bisectable because it's intermittent\.
>
> \(gdb\) bt
> \#0  malloc\_consolidate \(av=av@&#8203;entry=0x2b1a68423640 \<main\_arena>\)
>      at malloc\.c&#8203;:4094
> \#1  0x00002b1a680f8d77 in \_int\_malloc \(av=0x2b1a68423640 \<main\_arena>\,
>      bytes=4080\) at malloc\.c&#8203;:3379
> \#2  0x00002b1a680fb083 in \_\_GI\_\_\_libc\_malloc \(bytes=4080\) at malloc\.c&#8203;:2859
> \#3  0x000000000048ab42 in Perl\_safesysmalloc \(size=size@&#8203;entry=4080\)
>      at util\.c&#8203;:130
> \#4  0x00000000004b0a57 in Perl\_more\_bodies \(my\_perl=my\_perl@&#8203;entry=0x13ab010\,
>      sv\_type=sv\_type@&#8203;entry=SVt\_PVGV\, body\_size=body\_size@&#8203;entry=48\,
>      arena\_size=arena\_size@&#8203;entry=4080\) at sv\.c&#8203;:1059
> \#5  0x00000000004b8084 in Perl\_sv\_upgrade \(my\_perl=my\_perl@&#8203;entry=0x13ab010\,
>      sv=sv@&#8203;entry=0x1e91cd8\, new\_type=new\_type@&#8203;entry=SVt\_PVGV\) at sv\.c&#8203;:1364
> \#6  0x000000000043dd37 in Perl\_gv\_init\_pvn \(my\_perl=my\_perl@&#8203;entry=0x13ab010\,
>      gv=gv@&#8203;entry=0x1e91cd8\, stash=stash@&#8203;entry=0x1e913f0\,
>      name=name@&#8203;entry=0x14c74d0 "intersection"\, len=len@&#8203;entry=12\,
>      flags=flags@&#8203;entry=2\) at gv\.c&#8203;:366
> \#7  0x000000000044146a in Perl\_gv\_fetchmeth\_pvn \(
>      my\_perl=my\_perl@&#8203;entry=0x13ab010\, stash=stash@&#8203;entry=0x1e913f0\,
>      name=name@&#8203;entry=0x14c74d0 "intersection"\, len=len@&#8203;entry=12\,
>      level=level@&#8203;entry=0\, flags=flags@&#8203;entry=768\) at gv\.c&#8203;:700
> \#8  0x000000000043ed3f in Perl\_gv\_fetchmethod\_pvn\_flags \(
>      my\_perl=my\_perl@&#8203;entry=0x13ab010\, stash=stash@&#8203;entry=0x1e913f0\,
>      name=0x14c74d0 "intersection"\, len=\<optimized out>\, flags=768\) at gv\.c&#8203;:1002
> \#9  0x000000000043f195 in Perl\_gv\_fetchmethod\_sv\_flags \(
>      my\_perl=my\_perl@&#8203;entry=0x13ab010\, stash=0x1e913f0\,
>      namesv=namesv@&#8203;entry=0x1791f60\, flags=\<optimized out>\, flags@&#8203;entry=768\)
>      at gv\.c&#8203;:935
> \#10 0x00000000004a7e37 in S\_method\_common \(my\_perl=my\_perl@&#8203;entry=0x13ab010\,
>      meth=meth@&#8203;entry=0x1791f60\, hashp=hashp@&#8203;entry=0x7fff44c4c62c\)
>      at pp\_hot\.c&#8203;:3081
> \#11 0x00000000004b03e7 in Perl\_pp\_method\_named \(my\_perl=0x13ab010\)
>      at pp\_hot\.c&#8203;:2961
> \#12 0x00000000004a7ae6 in Perl\_runops\_standard \(my\_perl=0x13ab010\) at run\.c&#8203;:42
> \#13 0x00000000004427e1 in Perl\_amagic\_call \(my\_perl=my\_perl@&#8203;entry=0x13ab010\,
>      left=left@&#8203;entry=0x13d8088\, right=\<optimized out>\, right@&#8203;entry=0x13d81a8\,
>      method=method@&#8203;entry=46\, flags=0\) at gv\.c&#8203;:3254
> \#14 0x0000000000443a33 in Perl\_try\_amagic\_bin \(
>      my\_perl=my\_perl@&#8203;entry=0x13ab010\, method=method@&#8203;entry=46\,
>      flags=flags@&#8203;entry=4\) at gv\.c&#8203;:2742
> \#15 0x00000000004cea8a in Perl\_pp\_bit\_and \(my\_perl=0x13ab010\) at pp\.c&#8203;:2183
> \#16 0x00000000004a7ae6 in Perl\_runops\_standard \(my\_perl=0x13ab010\) at run\.c&#8203;:42
> \#17 0x000000000043cb84 in S\_run\_body \(oldscope=1\, my\_perl=0x13ab010\)
>      at perl\.c&#8203;:2449
> \#18 perl\_run \(my\_perl=0x13ab010\) at perl\.c&#8203;:2365
> \#19 0x000000000041bdcb in main \(argc=2\, argv=0x7fff44c4ca08\,
>      env=0x7fff44c4ca20\) at perlmain\.c&#8203;:112
>
>


Often\, these kind of errors are found by running valgrind\. 
Porting/bisect\.pl has an option to bisect those&#8203;:

\# When did this test program start generating errors from valgrind?
\*           \.\.\./Porting/bisect\.pl \-\-valgrind \.\./test\_prog\.pl

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @andk

Karl Williamson \<public@&#8203;khwilliamson\.com> writes&#8203;:

> Often\, these kind of errors are found by running valgrind\.

Maybe it's this\, starting with v5\.19\.9\-63\-g3d147ac when running
t/union\_more\.t in Number\-Tolerant\-1\.703&#8203;:

==4659== Invalid read of size 4
==4659==    at 0x441DC5&#8203;: Perl\_Gv\_AMupdate \(gv\.c&#8203;:2616\)
==4659==    by 0x44240D&#8203;: Perl\_amagic\_call \(gv\.c&#8203;:2865\)
==4659==    by 0x443A32&#8203;: Perl\_try\_amagic\_bin \(gv\.c&#8203;:2742\)
==4659==    by 0x4CEB98&#8203;: Perl\_pp\_bit\_or \(pp\.c&#8203;:2213\)
==4659==    by 0x4A7AE5&#8203;: Perl\_runops\_standard \(run\.c&#8203;:42\)
==4659==    by 0x43CB83&#8203;: perl\_run \(perl\.c&#8203;:2449\)
==4659==    by 0x41BDCA&#8203;: main \(perlmain\.c&#8203;:112\)
==4659==  Address 0x7cb6ad4 is 180 bytes inside a block of size 184 free'd
==4659==    at 0x4C2B7AE&#8203;: realloc \(vg\_replace\_malloc\.c&#8203;:687\)
==4659==    by 0x48AFB9&#8203;: Perl\_safesysrealloc \(util\.c&#8203;:244\)
==4659==    by 0x49FEA2&#8203;: S\_hsplit \(hv\.c&#8203;:1179\)
==4659==    by 0x4A34DC&#8203;: Perl\_hv\_common \(hv\.c&#8203;:870\)
==4659==    by 0x4A416D&#8203;: Perl\_hv\_common\_key\_len \(hv\.c&#8203;:336\)
==4659==    by 0x441385&#8203;: Perl\_gv\_fetchmeth\_pvn \(gv\.c&#8203;:693\)
==4659==    by 0x43ED3E&#8203;: Perl\_gv\_fetchmethod\_pvn\_flags \(gv\.c&#8203;:1002\)
==4659==    by 0x43F194&#8203;: Perl\_gv\_fetchmethod\_sv\_flags \(gv\.c&#8203;:935\)
==4659==    by 0x442009&#8203;: Perl\_Gv\_AMupdate \(gv\.c&#8203;:2566\)
==4659==    by 0x44240D&#8203;: Perl\_amagic\_call \(gv\.c&#8203;:2865\)
==4659==    by 0x443A32&#8203;: Perl\_try\_amagic\_bin \(gv\.c&#8203;:2742\)
==4659==    by 0x4CEB98&#8203;: Perl\_pp\_bit\_or \(pp\.c&#8203;:2213\)
==4659== 

But I get a lot of other output from valgrind that looks alarming also
with other bleadperls\. So if the above doesn't guide you\, feel free to
guide me\.

\-\- 
andreas

**Comment by p5pRT** [comment]
### From @nwc10

Dave\.\.\.

On Mon\, Mar 03\, 2014 at 10&#8203;:27&#8203;:40PM \+0100\, Andreas Koenig wrote&#8203;:
> Karl Williamson \<public@&#8203;khwilliamson\.com> writes&#8203;:
> 
> > Often\, these kind of errors are found by running valgrind\.
> 
> Maybe it's this\, starting with v5\.19\.9\-63\-g3d147ac when running
> t/union\_more\.t in Number\-Tolerant\-1\.703&#8203;:
> 
> ==4659== Invalid read of size 4
> ==4659==    at 0x441DC5&#8203;: Perl\_Gv\_AMupdate \(gv\.c&#8203;:2616\)
> ==4659==    by 0x44240D&#8203;: Perl\_amagic\_call \(gv\.c&#8203;:2865\)
> ==4659==    by 0x443A32&#8203;: Perl\_try\_amagic\_bin \(gv\.c&#8203;:2742\)
> ==4659==    by 0x4CEB98&#8203;: Perl\_pp\_bit\_or \(pp\.c&#8203;:2213\)
> ==4659==    by 0x4A7AE5&#8203;: Perl\_runops\_standard \(run\.c&#8203;:42\)
> ==4659==    by 0x43CB83&#8203;: perl\_run \(perl\.c&#8203;:2449\)
> ==4659==    by 0x41BDCA&#8203;: main \(perlmain\.c&#8203;:112\)
> ==4659==  Address 0x7cb6ad4 is 180 bytes inside a block of size 184 free'd
> ==4659==    at 0x4C2B7AE&#8203;: realloc \(vg\_replace\_malloc\.c&#8203;:687\)
> ==4659==    by 0x48AFB9&#8203;: Perl\_safesysrealloc \(util\.c&#8203;:244\)
> ==4659==    by 0x49FEA2&#8203;: S\_hsplit \(hv\.c&#8203;:1179\)
> ==4659==    by 0x4A34DC&#8203;: Perl\_hv\_common \(hv\.c&#8203;:870\)
> ==4659==    by 0x4A416D&#8203;: Perl\_hv\_common\_key\_len \(hv\.c&#8203;:336\)
> ==4659==    by 0x441385&#8203;: Perl\_gv\_fetchmeth\_pvn \(gv\.c&#8203;:693\)
> ==4659==    by 0x43ED3E&#8203;: Perl\_gv\_fetchmethod\_pvn\_flags \(gv\.c&#8203;:1002\)
> ==4659==    by 0x43F194&#8203;: Perl\_gv\_fetchmethod\_sv\_flags \(gv\.c&#8203;:935\)
> ==4659==    by 0x442009&#8203;: Perl\_Gv\_AMupdate \(gv\.c&#8203;:2566\)
> ==4659==    by 0x44240D&#8203;: Perl\_amagic\_call \(gv\.c&#8203;:2865\)
> ==4659==    by 0x443A32&#8203;: Perl\_try\_amagic\_bin \(gv\.c&#8203;:2742\)
> ==4659==    by 0x4CEB98&#8203;: Perl\_pp\_bit\_or \(pp\.c&#8203;:2213\)
> ==4659== 

That will be a subtle bug that we all missed in 3d147ac29d12abdb

The aux structure is stored after the hash's array\. The array is getting
reallocated on a split\. Hence the \(cached\) pointer to the aux structure in
Perl\_Gv\_AMupdate\(\) is stale\. I don't have time in the near future to attempt
a fix\, or audit for similar possibilities with taking pointers to aux
structures\. Sorry\.

Nicholas Clark

**Comment by p5pRT** [comment]
### From @khwilliamson

On 03/03/2014 02&#8203;:27 PM\, Andreas Koenig wrote&#8203;:
> But I get a lot of other output from valgrind that looks alarming also
> with other bleadperls\. So if the above doesn't guide you\, feel free to
> guide me\.

Please send the alarming things to this list\, so we can see what else is 
problematic\.

**Comment by p5pRT** [comment]
### From @andk

Karl Williamson \<public@&#8203;khwilliamson\.com> writes&#8203;:

> On 03/03/2014 02&#8203;:27 PM\, Andreas Koenig wrote&#8203;:
>> But I get a lot of other output from valgrind that looks alarming also
>> with other bleadperls\. So if the above doesn't guide you\, feel free to
>> guide me\.
>
> Please send the alarming things to this list\, so we can see what else
> is problematic\.

It turned out it's the linux dynaloader that causes the base noise\, so
nothing in perl itself\. The other thing of interest I found in perl has
just got a separate perlbug \(\#121373\)

\-\- 
andreas

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Mar 03\, 2014 at 09&#8203;:58&#8203;:01PM \+0000\, Nicholas Clark wrote&#8203;:
> That will be a subtle bug that we all missed in 3d147ac29d12abdb
> 
> The aux structure is stored after the hash's array\. The array is getting
> reallocated on a split\. Hence the \(cached\) pointer to the aux structure in
> Perl\_Gv\_AMupdate\(\) is stale\. I don't have time in the near future to attempt
> a fix\, or audit for similar possibilities with taking pointers to aux
> structures\. Sorry\.


Thanks for the diagnosis \. Fixed with 45479970582\.

\-\- 
In economics\, the exam questions are the same every year\.
They just change the answers\.

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, Mar 04\, 2014 at 07&#8203;:16&#8203;:14PM \+0000\, Dave Mitchell wrote&#8203;:
> On Mon\, Mar 03\, 2014 at 09&#8203;:58&#8203;:01PM \+0000\, Nicholas Clark wrote&#8203;:
> > That will be a subtle bug that we all missed in 3d147ac29d12abdb
> > 
> > The aux structure is stored after the hash's array\. The array is getting
> > reallocated on a split\. Hence the \(cached\) pointer to the aux structure in
> > Perl\_Gv\_AMupdate\(\) is stale\. I don't have time in the near future to attempt
> > a fix\, or audit for similar possibilities with taking pointers to aux
> > structures\. Sorry\.
> 
> 
> Thanks for the diagnosis \. Fixed with 45479970582\.

And I've now audited core for similar possible situations with
339441efdfcbaef5dbf131db2224abb35f5ae920


\-\- 
But Pity stayed his hand\. "It's a pity I've run out of bullets"\,
he thought\. \-\- "Bored of the Rings"
