### ISSUE TITLE
Segfault in perl (including perl-5.18.2 and bleadperl with PERL_NO_COW) after using @+

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#13707]
Migrated from [rt.perl.org#121573](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=121573) (status was 'resolved')

Searchable as RT121573$

**Comment by p5pRT** [comment]
### From @shlomif

Hi all\,

mahmoud on Freenode's \#perl channel reported a segfault in Perl reproduced
using the attached program \(which is compressed using xz\)\. It can also be
found in this GitHub repository&#8203;:

https://github.com/shlomif/file-slurp-related-perl-segfault \(note&#8203;: it's no
longer related to File&#8203;::Slurp and happens without slurping\)\.

Here is some discussion of it on \#p5p on irc\.perl\.org&#8203;:

Apr 02 17&#8203;:53&#8203;:48 \<rindolf>    Hi all\. https://github.com/shlomif/file-slurp-related-perl-segfault \- this segfault was reported on Freenode's \#perl by mahmoud\. We were able to reproduce it with perl\-5\.18\.2 on Mageia\, and some older perls installed from perlbrew including perl\-5\.16\.x\, and on other systems\.
Apr 02 17&#8203;:53&#8203;:49 \<dipsy>    \[ shlomif/file\-slurp\-related\-perl\-segfault · GitHub \]
Apr 02 17&#8203;:54&#8203;:03 \<rindolf>    IT doesn't appear to segfault bleadperl though\.
Apr 02 18&#8203;:41&#8203;:05 \<ilmari>    rindolf&#8203;: no need for slurping either\, inlining the text \(with 'use utf8;'\) also breaks
Apr 02 18&#8203;:41&#8203;:22 \<rindolf>    ilmari&#8203;: OK\.
Apr 02 19&#8203;:07&#8203;:14 \<ilmari>    rindolf&#8203;: bisecting now
Apr 02 19&#8203;:12&#8203;:58 \<rindolf>    ilmari&#8203;: thanks\!
Apr 02 19&#8203;:34&#8203;:37 \<ilmari>    bah
Apr 02 19&#8203;:34&#8203;:41 \<ilmari>    rindolf&#8203;: commit 13b0f67d12a6400f01bbc27945223ca68a12a7ef
Apr 02 19&#8203;:34&#8203;:50 \<ilmari>        re\-enable Copy\-on\-Write by default\.
Apr 02 19&#8203;:35&#8203;:22 \<rindolf>    ilmari&#8203;: ah\.
Apr 02 19&#8203;:35&#8203;:24 \<rindolf>    ilmari&#8203;: thanks\.
Apr 02 19&#8203;:35&#8203;:36 \<rindolf>    ilmari&#8203;: is this where it was fixed or where it was introduced?
Apr 02 19&#8203;:35&#8203;:47 \<ilmari>    that's where it was fixed
Apr 02 19&#8203;:35&#8203;:56 \*    ilmari tries blead with PERL\_NO\_COW
Apr 02 19&#8203;:36&#8203;:20 \<rindolf>    ilmari&#8203;: thanks again\.
Apr 03 13&#8203;:01&#8203;:30 \<rindolf>    ilmari&#8203;: hi\, are you there?
Apr 03 13&#8203;:02&#8203;:02 \<ilmari>    rindolf&#8203;: yup
Apr 03 13&#8203;:02&#8203;:19 \<ilmari>    fsvo "here"\, still on my first coffee\.\.\.
Apr 03 13&#8203;:05&#8203;:39 \<rindolf>    ilmari&#8203;: ah\.
Apr 03 13&#8203;:06&#8203;:07 \<rindolf>    ilmari&#8203;: so what do we do about that segfault?
Apr 03 13&#8203;:06&#8203;:41 \<ilmari>    rindolf&#8203;: I don't know\, it's beyond my knowledge to fix
Apr 03 13&#8203;:07&#8203;:00 \<rindolf>    ilmari&#8203;: OK\, did it also happen with PERL\_NO\_COW?
Apr 03 13&#8203;:07&#8203;:06 \<ilmari>    17&#8203;:40 \<@&#8203;ilmari> yep\, still segfaults in blead without COW
Apr 03 13&#8203;:07&#8203;:31 \<tomboh>    rindolf&#8203;: do you know of an old version of perl where the same code doesn't segfault?
Apr 03 13&#8203;:07&#8203;:47 \<tomboh>    or has it always done so?
Apr 03 13&#8203;:07&#8203;:53 \<ilmari>    looks like it's running off the end of the string somewhere in the handling of @&#8203;\- magic
Apr 03 13&#8203;:07&#8203;:54 \<rindolf>    ilmari&#8203;: OK\, then I think I'll report it using perlbug\.
Apr 03 13&#8203;:10&#8203;:05 \<ilmari>    tomboh&#8203;: segfaults with 5\.8\.9 and 5\.10\.1 at least



---
Please investigate it\, and let me know if I can further help\. \(Also please
credit mahmoud in the commit that fixes it\.

Regards\,

&nbsp;    Shlomi Fish

\-\- 


---
Shlomi Fish       http&#8203;://www\.shlomifish\.org/
Funny Anti\-Terrorism Story \- http&#8203;://shlom\.in/enemy

“I simply hate\, detest\, loathe\, despise\, and abhor redundancy\.”
&nbsp;    — http&#8203;://uncyclopedia\.org/wiki/Redundancy

Please reply to list if it's a mailing list post \- http&#8203;://shlom\.in/reply \.

**Comment by p5pRT** [comment]
### From @shlomif

[perl-5-segfault.pl.xz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1286432/678877/perl-5-segfault.pl.xz)

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Apr 03\, 2014 at 03&#8203;:30&#8203;:10AM \-0700\, shlomif@&#8203;shlomifish\.org wrote&#8203;:
> mahmoud on Freenode's \#perl channel reported a segfault in Perl reproduced
> using the attached program \(which is compressed using xz\)\. It can also be
> found in this GitHub repository&#8203;:

It can be reduced \(with valgrind\) to the following&#8203;:

&nbsp;    $\_ = " de\.\\x\{100\}";
&nbsp;    $x = $\-\[0\] if s/\\bde\\b//;

It's a variant of the issues we had with something like

&nbsp;    /abc/;
&nbsp;    eval '$&';

where perl hasn't "seen" $& yet\, and so doesn't know to make a copy
of the match string; then trying to calculate the value of $& becomes
problematic\.

In the bug report case\, for a utf8 match string\, using $\-\[0\] on a utf8
match string involves doing byte\-to\-utf8 offset calculations on the match
string \- which hasn't been copied and so isn't available\.

Given that one of the main purposes of COW is to fix bugs like his\, I
don't think it's worth trying to fix this for non\-COW builds\.

\(Or to put it another way\, we've already fixed this bug\. If people want to
disable the bug fix\, that becomes their problem\.\)

\-\- 
A power surge on the Bridge is rapidly and correctly diagnosed as a faulty
capacitor by the highly\-trained and competent engineering staff\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#9

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @wolfsage

I've reduced the test case to lol2\.pl \(attached\)\, which I think is
representative of the issue\.

Interestingly\, this segfault apperas to have gone away and come back
many times over a long period of time\.

It always seems to be here&#8203;:

&nbsp;    \(gdb\) bt
&nbsp;    \#0  0x00000000004fd4d8 in Perl\_utf8\_length \(\)
&nbsp;    \#1  0x0000000000484908 in Perl\_magic\_regdatum\_get \(\)
&nbsp;    \#2  0x000000000048407e in Perl\_mg\_get \(\)

I don't have anything before 5\.6\.0 \(no utf8\.pm\)\, but since then\,
somewhere between 5\.6\.2 and 5\.7\.3\, it broke with commit&#8203;:

&nbsp;  commit 983ffd37e39751798fdd14853511af238c5fe291
&nbsp;  Author&#8203;: Jarkko Hietaniemi \<jhi@&#8203;iki\.fi>
&nbsp;  Date&#8203;:   Sun Oct 21 16&#8203;:12&#8203;:08 2001 \+0000

&nbsp;      Implement multicharacter case mappings where a single
&nbsp;      Unicode character can be mapped into several\.

Was "fixed" in 5\.8\.4 with commit&#8203;:

&nbsp;  commit 08952adc863bc4a67f8bd3d4c7da553683565739
&nbsp;  Author&#8203;: Jarkko Hietaniemi \<jhi@&#8203;iki\.fi>
&nbsp;  Date&#8203;:   Wed Mar 3 11&#8203;:37&#8203;:21 2004 \+0200

Was broken again in 5\.9\.0 with an unknown commit \(bisect fails for me\)\.

And was fixed again in 5\.9\.1 with commit&#8203;:

b08cf34e02b6d68e83a46f7566341e6914ff1a2e is the first bad commit
commit b08cf34e02b6d68e83a46f7566341e6914ff1a2e
Author&#8203;: Jarkko Hietaniemi \<jhi@&#8203;iki\.fi>
Date&#8203;:   Wed Mar 3 11&#8203;:37&#8203;:21 2004 \+0200

&nbsp;    Speed up the unicode case mappings \(for /i\, lc\, uc\, etc\)\.
&nbsp;    Subject&#8203;: \[PATCH\] \[perl \#24826\]
&nbsp;    Message\-Id&#8203;: \<9B5CBF96\-6CE5\-11D8\-83B0\-00039362CB92@&#8203;iki\.fi>

&nbsp;    p4raw\-id&#8203;: //depot/perl@&#8203;22427

And appeared fine until 5\.13\.4\, when this commit again "broke" it\, and
it keeps going&#8203;:

&nbsp;  commit f12005599f648e675af22dfef1047191e260bc48
&nbsp;  Author&#8203;: Wolfram Humann \<w\.c\.humann@&#8203;arcor\.de>
&nbsp;  Date&#8203;:   Fri Aug 13 17&#8203;:20&#8203;:26 2010 \-0700

&nbsp;      make string\-append on win32 100 times faster

&nbsp;      When a string grows \(e\.g\. gets appended to\)\, perl calls sv\_grow\. When
&nbsp;      sv\_grow decides that the memory currently allocated to the string is
&nbsp;      insufficient\, it calls saferealloc\. Depending on whether or not perl
&nbsp;      was compiled with 'usemymalloc' this calls realloc in either perls
&nbsp;      internal version or on the operating system\. Perl requests from
&nbsp;      realloc just the amount of memory required for the current
&nbsp;      operation\. With 'usemymalloc' this is not a problem because it rounds
&nbsp;      up memory allocation to a certain geometric progression anyway\. When
&nbsp;      the operating system's realloc is called\, this may or may not lead to
&nbsp;      desaster\, depending on how it's implemented\. On win32 it does lead to
&nbsp;      desaster&#8203;: when I loop 1000 times and each time append 1000 chars to an
&nbsp;      initial string size of 10 million\, the memory grows from 10\.000e6 to
&nbsp;      10\.001e6 to 10\.002e6 and so on 1000 times till it ends at 11\.000e6\.

Attached is history\.txt\, which contains the results of running lol2\.pl
against all versions of Perl I have from 5\.6\.0 up with default
configuration \(\-des \-Dusedevel \+ a few unrelated\)\. Lines that say
"DONE" succeeded\, others died in some signal \(segfault probably\)\.

Hope that helps\.

\-\- Matthew Horsfall \(alh\)

**Comment by p5pRT** [comment]
### From @wolfsage

/home/mhorsfall/dpppperls/default/perl\-5\.6\.0/bin/perl5\.6\.0 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.6\.1/bin/perl5\.6\.1 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.6\.2/bin/perl5\.6\.2 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.7\.3/bin/perl5\.7\.3 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.8\.0/bin/perl5\.8\.0 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.8\.1/bin/perl5\.8\.1 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.8\.2/bin/perl5\.8\.2 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.8\.3/bin/perl5\.8\.3 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.8\.4/bin/perl5\.8\.4 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.8\.5/bin/perl5\.8\.5 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.8\.6/bin/perl5\.8\.6 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.8\.7/bin/perl5\.8\.7 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.8\.8/bin/perl5\.8\.8 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.8\.9/bin/perl5\.8\.9 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.9\.0/bin/perl5\.9\.0 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.9\.1/bin/perl5\.9\.1 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.9\.2/bin/perl5\.9\.2 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.9\.3/bin/perl5\.9\.3 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.9\.4/bin/perl5\.9\.4 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.9\.5/bin/perl5\.9\.5 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.10\.0/bin/perl5\.10\.0 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.10\.1/bin/perl5\.10\.1 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.11\.0/bin/perl5\.11\.0 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.11\.1/bin/perl5\.11\.1 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.11\.2/bin/perl5\.11\.2 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.11\.3/bin/perl5\.11\.3 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.11\.4/bin/perl5\.11\.4 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.11\.5/bin/perl5\.11\.5 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.12\.0/bin/perl5\.12\.0 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.12\.1/bin/perl5\.12\.1 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.12\.1\-RC1/bin/perl5\.12\.1 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.12\.1\-RC2/bin/perl5\.12\.1 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.12\.2\-RC1/bin/perl5\.12\.2 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.12\.2/bin/perl5\.12\.2 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.12\.3/bin/perl5\.12\.3 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.12\.4/bin/perl5\.12\.4 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.12\.4\-RC2/bin/perl5\.12\.4 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.12\.4\-RC1/bin/perl5\.12\.4 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.12\.5/bin/perl5\.12\.5 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.13\.0/bin/perl5\.13\.0 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.13\.1/bin/perl5\.13\.1 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.13\.2/bin/perl5\.13\.2 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.13\.3/bin/perl5\.13\.3 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.13\.4/bin/perl5\.13\.4 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.13\.5/bin/perl5\.13\.5 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.13\.6/bin/perl5\.13\.6 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.13\.7/bin/perl5\.13\.7 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.13\.8/bin/perl5\.13\.8 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.13\.9/bin/perl5\.13\.9 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.13\.10/bin/perl5\.13\.10 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.13\.11/bin/perl5\.13\.11 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.14\.0\-RC3/bin/perl5\.14\.0 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.14\.0\-RC1/bin/perl5\.14\.0 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.14\.0\-RC2/bin/perl5\.14\.0 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.14\.0/bin/perl5\.14\.0 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.14\.1/bin/perl5\.14\.1 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.14\.1\-RC1/bin/perl5\.14\.1 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.14\.2/bin/perl5\.14\.2 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.14\.2\-RC1/bin/perl5\.14\.2 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.14\.3/bin/perl5\.14\.3 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.14\.4/bin/perl5\.14\.4 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.14\.4\-RC2/bin/perl5\.14\.4 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.14\.4\-RC1/bin/perl5\.14\.4 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.15\.0/bin/perl5\.15\.0 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.15\.1/bin/perl5\.15\.1 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.15\.2/bin/perl5\.15\.2 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.15\.3/bin/perl5\.15\.3 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.15\.4/bin/perl5\.15\.4 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.15\.5/bin/perl5\.15\.5 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.15\.6/bin/perl5\.15\.6 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.15\.7/bin/perl5\.15\.7 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.15\.8/bin/perl5\.15\.8 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.15\.9/bin/perl5\.15\.9 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.16\.0\-RC1/bin/perl5\.16\.0 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.16\.0/bin/perl5\.16\.0 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.16\.0\-RC2/bin/perl5\.16\.0 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.16\.1/bin/perl5\.16\.1 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.16\.2/bin/perl5\.16\.2 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.16\.3/bin/perl5\.16\.3 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.17\.0/bin/perl5\.17\.0 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.17\.1/bin/perl5\.17\.1 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.17\.2/bin/perl5\.17\.2 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.17\.3/bin/perl5\.17\.3 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.17\.4/bin/perl5\.17\.4 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.17\.5/bin/perl5\.17\.5 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.17\.6/bin/perl5\.17\.6 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.17\.7/bin/perl5\.17\.7 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.17\.8/bin/perl5\.17\.8 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.17\.9/bin/perl5\.17\.9 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.17\.10/bin/perl5\.17\.10 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.17\.11/bin/perl5\.17\.11 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.18\.0\-RC3/bin/perl5\.18\.0 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.18\.0\-RC2/bin/perl5\.18\.0 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.18\.0\-RC4/bin/perl5\.18\.0 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.18\.0/bin/perl5\.18\.0 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.18\.0\-RC1/bin/perl5\.18\.0 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.18\.1/bin/perl5\.18\.1 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.19\.0/bin/perl5\.19\.0 lol2\.pl&#8203;:
/home/mhorsfall/dpppperls/default/perl\-5\.19\.1/bin/perl5\.19\.1 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.19\.2/bin/perl5\.19\.2 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.19\.3/bin/perl5\.19\.3 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.19\.4/bin/perl5\.19\.4 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.19\.5/bin/perl5\.19\.5 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.19\.6/bin/perl5\.19\.6 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.19\.7/bin/perl5\.19\.7 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.19\.8/bin/perl5\.19\.8 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.19\.9/bin/perl5\.19\.9 lol2\.pl&#8203;:DONE
/home/mhorsfall/dpppperls/default/perl\-5\.19\.10/bin/perl5\.19\.10 lol2\.pl&#8203;:DONE

**Comment by p5pRT** [comment]
### From @wolfsage

[lol2.pl](https://rt-archive.perl.org/perl5/Ticket/Attachment/1286448/678891/lol2.pl)

**Comment by p5pRT** [comment]
### From @wolfsage

On Thu\, Apr 3\, 2014 at 11&#8203;:16 AM\, Dave Mitchell \<davem@&#8203;iabyn\.com> wrote&#8203;:
> On Thu\, Apr 03\, 2014 at 03&#8203;:30&#8203;:10AM \-0700\, shlomif@&#8203;shlomifish\.org wrote&#8203;:
>> mahmoud on Freenode's \#perl channel reported a segfault in Perl reproduced
>> using the attached program \(which is compressed using xz\)\. It can also be
>> found in this GitHub repository&#8203;:
>
> It can be reduced \(with valgrind\) to the following&#8203;:
>
>     $\_ = " de\.\\x\{100\}";
>     $x = $\-\[0\] if s/\\bde\\b//;
>
> It's a variant of the issues we had with something like
>
>     /abc/;
>     eval '$&';
>
> where perl hasn't "seen" $& yet\, and so doesn't know to make a copy
> of the match string; then trying to calculate the value of $& becomes
> problematic\.
>
> In the bug report case\, for a utf8 match string\, using $\-\[0\] on a utf8
> match string involves doing byte\-to\-utf8 offset calculations on the match
> string \- which hasn't been copied and so isn't available\.
>
> Given that one of the main purposes of COW is to fix bugs like his\, I
> don't think it's worth trying to fix this for non\-COW builds\.
>
> \(Or to put it another way\, we've already fixed this bug\. If people want to
> disable the bug fix\, that becomes their problem\.\)

Ahh\, good timing\. Well then ignore my previous email I suppose\!

\-\- Matthew Horsfall \(alh\)

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
