### ISSUE TITLE
SEGV in Perl_hv_common with 5.20.1 and Encode 2.62

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14126]
Migrated from [rt.perl.org#122873](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=122873) (status was 'rejected')

Searchable as RT122873$

**Comment by p5pRT** [comment]
### From @andk

Thanks to Slaven Rezić for bringing this candidate to my attention\.

The SEGV only happens occasionally while running the test
t/302\-content\-negotiation\-charset\.t that comes with
DROLSKY/HTTP\-Headers\-ActionPack\-0\.09\.tar\.gz with
DANKOGAI/Encode\-2\.62\.tar\.gz installed\.

I just have observed it with 5\.20\.1 but according to cpantesters it
seems the same happened with 5\.20\.0\, 5\.21\.1\, and 5\.21\.3\.

Very similar to my current observation is
http&#8203;://www\.cpantesters\.org/cpan/report/45835631 where Encode
2\.60 was involved\.

Here is my stacktrace&#8203;:

&nbsp;  Core was generated by \`/home/sand/src/perl/repoperls/installed\-perls/perl/v5\.20\.1/127e/bin/perl \-Mblib'\.
&nbsp;  Program terminated with signal SIGSEGV\, Segmentation fault\.
&nbsp;  \#0  0x0000000000499570 in Perl\_hv\_common \(hv=0xa\, keysv=0x2d7b8f0\, 
&nbsp;      key=0x2d86b70 "iso\-8859\-2"\, klen=10\, flags=\-1022775292\, action=10\, val=0x0\, 
&nbsp;      hash=1\) at hv\.c&#8203;:637

&nbsp;  warning&#8203;: Source file is more recent than executable\.
&nbsp;  637             goto not\_found;
&nbsp;  \(gdb\) bt
&nbsp;  \#0  0x0000000000499570 in Perl\_hv\_common \(hv=0xa\, keysv=0x2d7b8f0\, 
&nbsp;      key=0x2d86b70 "iso\-8859\-2"\, klen=10\, flags=\-1022775292\, action=10\, val=0x0\, 
&nbsp;      hash=1\) at hv\.c&#8203;:637
&nbsp;  \#1  0x00000000004a5d8a in Perl\_pp\_helem \(\) at pp\_hot\.c&#8203;:1768
&nbsp;  \#2  0x000000000049e0e3 in Perl\_runops\_standard \(\) at run\.c&#8203;:42
&nbsp;  \#3  0x0000000000435371 in Perl\_call\_sv \(sv=0x2d81c20\, flags=flags@&#8203;entry=2\)
&nbsp;      at perl\.c&#8203;:2756
&nbsp;  \#4  0x0000000000435828 in Perl\_call\_pv \(
&nbsp;      sub\_name=sub\_name@&#8203;entry=0x7fd6d1916c10 "Encode&#8203;::MIME&#8203;::Name&#8203;::get\_mime\_name"\, 
&nbsp;      flags=flags@&#8203;entry=2\) at perl\.c&#8203;:2645
&nbsp;  \#5  0x00007fd6d191387a in XS\_Encode\_\_XS\_mime\_name \(cv=\<optimized out>\)
&nbsp;      at Encode\.xs&#8203;:715
&nbsp;  \#6  0x00000000004a5220 in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:2794
&nbsp;  \#7  0x000000000049e0e3 in Perl\_runops\_standard \(\) at run\.c&#8203;:42
&nbsp;  \#8  0x000000000043b8c8 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2456
&nbsp;  \#9  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2372
&nbsp;  \#10 0x000000000041de25 in main \(argc=3\, argv=0x7ffffd6ab278\, env=0x7ffffd6ab298\)
&nbsp;      at perlmain\.c&#8203;:114

I attach a valgrind output from running

&nbsp;  env PERL\_DESTRUCT\_LEVEL=2 valgrind  \-\-num\-callers=5 \\
&nbsp;  /home/sand/src/perl/repoperls/installed\-perls/perl/v5\.20\.1/127e/bin/perl \\
&nbsp;  \-Mblib  t/302\-content\-negotiation\-charset\.t

\-\- 
andreas

**Comment by p5pRT** [comment]
### From @andk

==22122== Memcheck\, a memory error detector
==22122== Copyright \(C\) 2002\-2013\, and GNU GPL'd\, by Julian Seward et al\.
==22122== Using Valgrind\-3\.9\.0 and LibVEX; rerun with \-h for copyright info
==22122== Command&#8203;: /home/sand/src/perl/repoperls/installed\-perls/perl/v5\.20\.1/127e/bin/perl \-Mblib t/302\-content\-negotiation\-charset\.t
==22122== 
ok 1 \- use HTTP&#8203;::Headers&#8203;::ActionPack;
ok 2 \- An object of class 'HTTP&#8203;::Headers&#8203;::ActionPack&#8203;::ContentNegotiation' isa 'HTTP&#8203;::Headers&#8203;::ActionPack&#8203;::ContentNegotiation'
ok 3 \- \.\.\. got nothing back when there are no choices
==22122== Invalid write of size 8
==22122==    at 0x6C3C869&#8203;: XS\_Encode\_\_XS\_mime\_name \(Encode\.xs&#8203;:713\)
==22122==    by 0x4A521F&#8203;: Perl\_pp\_entersub \(pp\_hot\.c&#8203;:2794\)
==22122==    by 0x49E0E2&#8203;: Perl\_runops\_standard \(run\.c&#8203;:42\)
==22122==    by 0x43B8C7&#8203;: perl\_run \(perl\.c&#8203;:2456\)
==22122==    by 0x41DE24&#8203;: main \(perlmain\.c&#8203;:114\)
==22122==  Address 0x5d36c00 is 32 bytes inside a block of size 1\,024 free'd
==22122==    at 0x4C2A7CE&#8203;: realloc \(vg\_replace\_malloc\.c&#8203;:687\)
==22122==    by 0x4842C9&#8203;: Perl\_safesysrealloc \(util\.c&#8203;:244\)
==22122==    by 0x49C870&#8203;: Perl\_av\_extend\_guts \(av\.c&#8203;:154\)
==22122==    by 0x4CA5F9&#8203;: Perl\_stack\_grow \(scope\.c&#8203;:38\)
==22122==    by 0x49E78F&#8203;: Perl\_pp\_const \(pp\_hot\.c&#8203;:44\)
==22122== 
==22122== Invalid write of size 8
==22122==    at 0x43523F&#8203;: Perl\_call\_sv \(perl\.c&#8203;:2721\)
==22122==    by 0x6C3C879&#8203;: XS\_Encode\_\_XS\_mime\_name \(Encode\.xs&#8203;:715\)
==22122==    by 0x4A521F&#8203;: Perl\_pp\_entersub \(pp\_hot\.c&#8203;:2794\)
==22122==    by 0x49E0E2&#8203;: Perl\_runops\_standard \(run\.c&#8203;:42\)
==22122==    by 0x43B8C7&#8203;: perl\_run \(perl\.c&#8203;:2456\)
==22122==  Address 0x5d36c08 is 40 bytes inside a block of size 1\,024 free'd
==22122==    at 0x4C2A7CE&#8203;: realloc \(vg\_replace\_malloc\.c&#8203;:687\)
==22122==    by 0x4842C9&#8203;: Perl\_safesysrealloc \(util\.c&#8203;:244\)
==22122==    by 0x49C870&#8203;: Perl\_av\_extend\_guts \(av\.c&#8203;:154\)
==22122==    by 0x4CA5F9&#8203;: Perl\_stack\_grow \(scope\.c&#8203;:38\)
==22122==    by 0x49E78F&#8203;: Perl\_pp\_const \(pp\_hot\.c&#8203;:44\)
==22122== 
==22122== Invalid read of size 8
==22122==    at 0x4A4DC1&#8203;: Perl\_pp\_entersub \(pp\_hot\.c&#8203;:2531\)
==22122==    by 0x435795&#8203;: Perl\_call\_sv \(perl\.c&#8203;:2756\)
==22122==    by 0x6C3C879&#8203;: XS\_Encode\_\_XS\_mime\_name \(Encode\.xs&#8203;:715\)
==22122==    by 0x4A521F&#8203;: Perl\_pp\_entersub \(pp\_hot\.c&#8203;:2794\)
==22122==    by 0x49E0E2&#8203;: Perl\_runops\_standard \(run\.c&#8203;:42\)
==22122==  Address 0x5d36c08 is 40 bytes inside a block of size 1\,024 free'd
==22122==    at 0x4C2A7CE&#8203;: realloc \(vg\_replace\_malloc\.c&#8203;:687\)
==22122==    by 0x4842C9&#8203;: Perl\_safesysrealloc \(util\.c&#8203;:244\)
==22122==    by 0x49C870&#8203;: Perl\_av\_extend\_guts \(av\.c&#8203;:154\)
==22122==    by 0x4CA5F9&#8203;: Perl\_stack\_grow \(scope\.c&#8203;:38\)
==22122==    by 0x49E78F&#8203;: Perl\_pp\_const \(pp\_hot\.c&#8203;:44\)
==22122== 
==22122== Invalid read of size 8
==22122==    at 0x4C2CB38&#8203;: memcpy@&#8203;@&#8203;GLIBC\_2\.14 \(mc\_replace\_strmem\.c&#8203;:882\)
==22122==    by 0x4A5058&#8203;: Perl\_pp\_entersub \(pp\_hot\.c&#8203;:2702\)
==22122==    by 0x435795&#8203;: Perl\_call\_sv \(perl\.c&#8203;:2756\)
==22122==    by 0x6C3C879&#8203;: XS\_Encode\_\_XS\_mime\_name \(Encode\.xs&#8203;:715\)
==22122==    by 0x4A521F&#8203;: Perl\_pp\_entersub \(pp\_hot\.c&#8203;:2794\)
==22122==  Address 0x5d36c00 is 32 bytes inside a block of size 1\,024 free'd
==22122==    at 0x4C2A7CE&#8203;: realloc \(vg\_replace\_malloc\.c&#8203;:687\)
==22122==    by 0x4842C9&#8203;: Perl\_safesysrealloc \(util\.c&#8203;:244\)
==22122==    by 0x49C870&#8203;: Perl\_av\_extend\_guts \(av\.c&#8203;:154\)
==22122==    by 0x4CA5F9&#8203;: Perl\_stack\_grow \(scope\.c&#8203;:38\)
==22122==    by 0x49E78F&#8203;: Perl\_pp\_const \(pp\_hot\.c&#8203;:44\)
==22122== 
==22122== Invalid write of size 8
==22122==    at 0x49E9DA&#8203;: Perl\_pp\_gv \(pp\_hot\.c&#8203;:99\)
==22122==    by 0x49E0E2&#8203;: Perl\_runops\_standard \(run\.c&#8203;:42\)
==22122==    by 0x435370&#8203;: Perl\_call\_sv \(perl\.c&#8203;:2756\)
==22122==    by 0x6C3C879&#8203;: XS\_Encode\_\_XS\_mime\_name \(Encode\.xs&#8203;:715\)
==22122==    by 0x4A521F&#8203;: Perl\_pp\_entersub \(pp\_hot\.c&#8203;:2794\)
==22122==  Address 0x5d36c00 is 32 bytes inside a block of size 1\,024 free'd
==22122==    at 0x4C2A7CE&#8203;: realloc \(vg\_replace\_malloc\.c&#8203;:687\)
==22122==    by 0x4842C9&#8203;: Perl\_safesysrealloc \(util\.c&#8203;:244\)
==22122==    by 0x49C870&#8203;: Perl\_av\_extend\_guts \(av\.c&#8203;:154\)
==22122==    by 0x4CA5F9&#8203;: Perl\_stack\_grow \(scope\.c&#8203;:38\)
==22122==    by 0x49E78F&#8203;: Perl\_pp\_const \(pp\_hot\.c&#8203;:44\)
==22122== 
==22122== Invalid read of size 8
==22122==    at 0x4A0746&#8203;: Perl\_pp\_rv2av \(pp\_hot\.c&#8203;:871\)
==22122==    by 0x49E0E2&#8203;: Perl\_runops\_standard \(run\.c&#8203;:42\)
==22122==    by 0x435370&#8203;: Perl\_call\_sv \(perl\.c&#8203;:2756\)
==22122==    by 0x6C3C879&#8203;: XS\_Encode\_\_XS\_mime\_name \(Encode\.xs&#8203;:715\)
==22122==    by 0x4A521F&#8203;: Perl\_pp\_entersub \(pp\_hot\.c&#8203;:2794\)
==22122==  Address 0x5d36c00 is 32 bytes inside a block of size 1\,024 free'd
==22122==    at 0x4C2A7CE&#8203;: realloc \(vg\_replace\_malloc\.c&#8203;:687\)
==22122==    by 0x4842C9&#8203;: Perl\_safesysrealloc \(util\.c&#8203;:244\)
==22122==    by 0x49C870&#8203;: Perl\_av\_extend\_guts \(av\.c&#8203;:154\)
==22122==    by 0x4CA5F9&#8203;: Perl\_stack\_grow \(scope\.c&#8203;:38\)
==22122==    by 0x49E78F&#8203;: Perl\_pp\_const \(pp\_hot\.c&#8203;:44\)
==22122== 
==22122== Invalid write of size 8
==22122==    at 0x4A0845&#8203;: Perl\_pp\_rv2av \(pp\_hot\.c&#8203;:908\)
==22122==    by 0x49E0E2&#8203;: Perl\_runops\_standard \(run\.c&#8203;:42\)
==22122==    by 0x435370&#8203;: Perl\_call\_sv \(perl\.c&#8203;:2756\)
==22122==    by 0x6C3C879&#8203;: XS\_Encode\_\_XS\_mime\_name \(Encode\.xs&#8203;:715\)
==22122==    by 0x4A521F&#8203;: Perl\_pp\_entersub \(pp\_hot\.c&#8203;:2794\)
==22122==  Address 0x5d36c00 is 32 bytes inside a block of size 1\,024 free'd
==22122==    at 0x4C2A7CE&#8203;: realloc \(vg\_replace\_malloc\.c&#8203;:687\)
==22122==    by 0x4842C9&#8203;: Perl\_safesysrealloc \(util\.c&#8203;:244\)
==22122==    by 0x49C870&#8203;: Perl\_av\_extend\_guts \(av\.c&#8203;:154\)
==22122==    by 0x4CA5F9&#8203;: Perl\_stack\_grow \(scope\.c&#8203;:38\)
==22122==    by 0x49E78F&#8203;: Perl\_pp\_const \(pp\_hot\.c&#8203;:44\)
==22122== 
==22122== Invalid write of size 8
==22122==    at 0x4A0087&#8203;: Perl\_pp\_aelemfast \(pp\_hot\.c&#8203;:740\)
==22122==    by 0x49E0E2&#8203;: Perl\_runops\_standard \(run\.c&#8203;:42\)
==22122==    by 0x435370&#8203;: Perl\_call\_sv \(perl\.c&#8203;:2756\)
==22122==    by 0x6C3C879&#8203;: XS\_Encode\_\_XS\_mime\_name \(Encode\.xs&#8203;:715\)
==22122==    by 0x4A521F&#8203;: Perl\_pp\_entersub \(pp\_hot\.c&#8203;:2794\)
==22122==  Address 0x5d36c08 is 40 bytes inside a block of size 1\,024 free'd
==22122==    at 0x4C2A7CE&#8203;: realloc \(vg\_replace\_malloc\.c&#8203;:687\)
==22122==    by 0x4842C9&#8203;: Perl\_safesysrealloc \(util\.c&#8203;:244\)
==22122==    by 0x49C870&#8203;: Perl\_av\_extend\_guts \(av\.c&#8203;:154\)
==22122==    by 0x4CA5F9&#8203;: Perl\_stack\_grow \(scope\.c&#8203;:38\)
==22122==    by 0x49E78F&#8203;: Perl\_pp\_const \(pp\_hot\.c&#8203;:44\)
==22122== 
==22122== Invalid read of size 8
==22122==    at 0x4A5C56&#8203;: Perl\_pp\_helem \(pp\_hot\.c&#8203;:1745\)
==22122==    by 0x49E0E2&#8203;: Perl\_runops\_standard \(run\.c&#8203;:42\)
==22122==    by 0x435370&#8203;: Perl\_call\_sv \(perl\.c&#8203;:2756\)
==22122==    by 0x6C3C879&#8203;: XS\_Encode\_\_XS\_mime\_name \(Encode\.xs&#8203;:715\)
==22122==    by 0x4A521F&#8203;: Perl\_pp\_entersub \(pp\_hot\.c&#8203;:2794\)
==22122==  Address 0x5d36c08 is 40 bytes inside a block of size 1\,024 free'd
==22122==    at 0x4C2A7CE&#8203;: realloc \(vg\_replace\_malloc\.c&#8203;:687\)
==22122==    by 0x4842C9&#8203;: Perl\_safesysrealloc \(util\.c&#8203;:244\)
==22122==    by 0x49C870&#8203;: Perl\_av\_extend\_guts \(av\.c&#8203;:154\)
==22122==    by 0x4CA5F9&#8203;: Perl\_stack\_grow \(scope\.c&#8203;:38\)
==22122==    by 0x49E78F&#8203;: Perl\_pp\_const \(pp\_hot\.c&#8203;:44\)
==22122== 
==22122== Invalid read of size 8
==22122==    at 0x4A5C59&#8203;: Perl\_pp\_helem \(pp\_hot\.c&#8203;:1746\)
==22122==    by 0x49E0E2&#8203;: Perl\_runops\_standard \(run\.c&#8203;:42\)
==22122==    by 0x435370&#8203;: Perl\_call\_sv \(perl\.c&#8203;:2756\)
==22122==    by 0x6C3C879&#8203;: XS\_Encode\_\_XS\_mime\_name \(Encode\.xs&#8203;:715\)
==22122==    by 0x4A521F&#8203;: Perl\_pp\_entersub \(pp\_hot\.c&#8203;:2794\)
==22122==  Address 0x5d36c00 is 32 bytes inside a block of size 1\,024 free'd
==22122==    at 0x4C2A7CE&#8203;: realloc \(vg\_replace\_malloc\.c&#8203;:687\)
==22122==    by 0x4842C9&#8203;: Perl\_safesysrealloc \(util\.c&#8203;:244\)
==22122==    by 0x49C870&#8203;: Perl\_av\_extend\_guts \(av\.c&#8203;:154\)
==22122==    by 0x4CA5F9&#8203;: Perl\_stack\_grow \(scope\.c&#8203;:38\)
==22122==    by 0x49E78F&#8203;: Perl\_pp\_const \(pp\_hot\.c&#8203;:44\)
==22122== 
==22122== Invalid write of size 8
==22122==    at 0x4A5E3C&#8203;: Perl\_pp\_helem \(pp\_hot\.c&#8203;:1816\)
==22122==    by 0x49E0E2&#8203;: Perl\_runops\_standard \(run\.c&#8203;:42\)
==22122==    by 0x435370&#8203;: Perl\_call\_sv \(perl\.c&#8203;:2756\)
==22122==    by 0x6C3C879&#8203;: XS\_Encode\_\_XS\_mime\_name \(Encode\.xs&#8203;:715\)
==22122==    by 0x4A521F&#8203;: Perl\_pp\_entersub \(pp\_hot\.c&#8203;:2794\)
==22122==  Address 0x5d36c00 is 32 bytes inside a block of size 1\,024 free'd
==22122==    at 0x4C2A7CE&#8203;: realloc \(vg\_replace\_malloc\.c&#8203;:687\)
==22122==    by 0x4842C9&#8203;: Perl\_safesysrealloc \(util\.c&#8203;:244\)
==22122==    by 0x49C870&#8203;: Perl\_av\_extend\_guts \(av\.c&#8203;:154\)
==22122==    by 0x4CA5F9&#8203;: Perl\_stack\_grow \(scope\.c&#8203;:38\)
==22122==    by 0x49E78F&#8203;: Perl\_pp\_const \(pp\_hot\.c&#8203;:44\)
==22122== 
==22122== Invalid read of size 8
==22122==    at 0x4A4BD0&#8203;: Perl\_pp\_leavesub \(pp\_hot\.c&#8203;:2496\)
==22122==    by 0x49E0E2&#8203;: Perl\_runops\_standard \(run\.c&#8203;:42\)
==22122==    by 0x435370&#8203;: Perl\_call\_sv \(perl\.c&#8203;:2756\)
==22122==    by 0x6C3C879&#8203;: XS\_Encode\_\_XS\_mime\_name \(Encode\.xs&#8203;:715\)
==22122==    by 0x4A521F&#8203;: Perl\_pp\_entersub \(pp\_hot\.c&#8203;:2794\)
==22122==  Address 0x5d36c00 is 32 bytes inside a block of size 1\,024 free'd
==22122==    at 0x4C2A7CE&#8203;: realloc \(vg\_replace\_malloc\.c&#8203;:687\)
==22122==    by 0x4842C9&#8203;: Perl\_safesysrealloc \(util\.c&#8203;:244\)
==22122==    by 0x49C870&#8203;: Perl\_av\_extend\_guts \(av\.c&#8203;:154\)
==22122==    by 0x4CA5F9&#8203;: Perl\_stack\_grow \(scope\.c&#8203;:38\)
==22122==    by 0x49E78F&#8203;: Perl\_pp\_const \(pp\_hot\.c&#8203;:44\)
==22122== 
==22122== Invalid write of size 8
==22122==    at 0x4A4BFE&#8203;: Perl\_pp\_leavesub \(pp\_hot\.c&#8203;:2501\)
==22122==    by 0x49E0E2&#8203;: Perl\_runops\_standard \(run\.c&#8203;:42\)
==22122==    by 0x435370&#8203;: Perl\_call\_sv \(perl\.c&#8203;:2756\)
==22122==    by 0x6C3C879&#8203;: XS\_Encode\_\_XS\_mime\_name \(Encode\.xs&#8203;:715\)
==22122==    by 0x4A521F&#8203;: Perl\_pp\_entersub \(pp\_hot\.c&#8203;:2794\)
==22122==  Address 0x5d36c00 is 32 bytes inside a block of size 1\,024 free'd
==22122==    at 0x4C2A7CE&#8203;: realloc \(vg\_replace\_malloc\.c&#8203;:687\)
==22122==    by 0x4842C9&#8203;: Perl\_safesysrealloc \(util\.c&#8203;:244\)
==22122==    by 0x49C870&#8203;: Perl\_av\_extend\_guts \(av\.c&#8203;:154\)
==22122==    by 0x4CA5F9&#8203;: Perl\_stack\_grow \(scope\.c&#8203;:38\)
==22122==    by 0x49E78F&#8203;: Perl\_pp\_const \(pp\_hot\.c&#8203;:44\)
==22122== 
==22122== Invalid read of size 8
==22122==    at 0x6C3C87E&#8203;: XS\_Encode\_\_XS\_mime\_name \(Encode\.xs&#8203;:717\)
==22122==    by 0x4A521F&#8203;: Perl\_pp\_entersub \(pp\_hot\.c&#8203;:2794\)
==22122==    by 0x49E0E2&#8203;: Perl\_runops\_standard \(run\.c&#8203;:42\)
==22122==    by 0x43B8C7&#8203;: perl\_run \(perl\.c&#8203;:2456\)
==22122==    by 0x41DE24&#8203;: main \(perlmain\.c&#8203;:114\)
==22122==  Address 0x5d36c00 is 32 bytes inside a block of size 1\,024 free'd
==22122==    at 0x4C2A7CE&#8203;: realloc \(vg\_replace\_malloc\.c&#8203;:687\)
==22122==    by 0x4842C9&#8203;: Perl\_safesysrealloc \(util\.c&#8203;:244\)
==22122==    by 0x49C870&#8203;: Perl\_av\_extend\_guts \(av\.c&#8203;:154\)
==22122==    by 0x4CA5F9&#8203;: Perl\_stack\_grow \(scope\.c&#8203;:38\)
==22122==    by 0x49E78F&#8203;: Perl\_pp\_const \(pp\_hot\.c&#8203;:44\)
==22122== 
ok 4 \- \.\.\. first value in the header wins when priorities are equal
ok 5 \- \.\.\. higher priority charset is chosen over lower
ok 6 \- \.\.\. got ISO\-8859\-1 even when it is not explicitly asked for
ok 7 \- \.\.\. charset explicitly listed in header is preferred over ISO\-8859\-1 default
ok 8 \- \.\.\. got default back when the default is in list of choices and default is ok
ok 9 \- \.\.\. got default back when the default is in list of choices but not an exact match and default is ok
ok 10 \- \.\.\. got nothing back when default is not in list of choices
ok 11 \- \.\.\. if default is listed as priority 0\.0 it is not returned
ok 12 \- \.\.\. if default is listed as priority 0 it is not returned \(0 == 0\.0\)
ok 13 \- \.\.\. if \* is listed as priority 0\.0 then default is not returned
ok 14 \- \.\.\. if \* is listed as priority 0\.5 but default is 0\.0 then default is not returned\, but \* can match other choices
ok 15 \- \.\.\. charsets in header are canonicalized
ok 16 \- \.\.\. the match is returned as formatted in the list of choices\, without canonicalization
1\.\.16
==22122== 
==22122== HEAP SUMMARY&#8203;:
==22122==     in use at exit&#8203;: 7\,998\,904 bytes in 23\,148 blocks
==22122==   total heap usage&#8203;: 68\,345 allocs\, 45\,197 frees\, 16\,433\,032 bytes allocated
==22122== 
==22122== LEAK SUMMARY&#8203;:
==22122==    definitely lost&#8203;: 0 bytes in 0 blocks
==22122==    indirectly lost&#8203;: 0 bytes in 0 blocks
==22122==      possibly lost&#8203;: 5\,236\,190 bytes in 3\,197 blocks
==22122==    still reachable&#8203;: 2\,762\,714 bytes in 19\,951 blocks
==22122==         suppressed&#8203;: 0 bytes in 0 blocks
==22122== Rerun with \-\-leak\-check=full to see details of leaked memory
==22122== 
==22122== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==22122== ERROR SUMMARY&#8203;: 14 errors from 14 contexts \(suppressed&#8203;: 2 from 2\)

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue Sep 30 18&#8203;:30&#8203;:09 2014\, andreas\.koenig\.7os6VVqR@&#8203;franz\.ak\.mind\.de wrote&#8203;:
> Thanks to Slaven Rezić for bringing this candidate to my attention\.
> 
> The SEGV only happens occasionally while running the test
> t/302\-content\-negotiation\-charset\.t that comes with
> DROLSKY/HTTP\-Headers\-ActionPack\-0\.09\.tar\.gz with
> DANKOGAI/Encode\-2\.62\.tar\.gz installed\.

This is a bug in Encode\.

I've reported this upstream with a fix as https://rt.cpan.org/Ticket/Display.html?id=99264

The problem is Member\_mime\_name\(\) calls call\_pv\(\)\, which can reallocate the stack\, but then continues to use the old stack\.

Adding SPAGAIN fixes it\. Method\_perlio\_ok\(\) has a similar problem which I've also patched\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'rejected'
