### ISSUE TITLE
Segmentation failed on calling method of undef with use warnings FATAL => 'all'

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14319]
Migrated from [rt.perl.org#123398](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=123398) (status was 'resolved')

Searchable as RT123398$

**Comment by p5pRT** [comment]
### From @hurricup

#### Created by @hurricup



Example below leads to segmentation fault\. Works fine without warnings FATAL => 'all'&#8203;:

\#\!/usr/bin/perl
package Foo;
use strict; use utf8; use warnings FATAL => 'all'; 

sub new
\{
&nbsp;    return bless\{ 'field' => undef \}\, 'Foo';
\}

sub DESTROY
\{
&nbsp;    my $self = shift;
&nbsp;    $self\->\{'field'\}\->missing\_method;
\}

package main;

my $foo = new Foo;
undef\($foo\);

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=critical

Site configuration information for perl 5.20.1:

Configured by root at Sun Dec  7 13:23:13 MSK 2014.

Summary of my perl5 (revision 5 version 20 subversion 1) configuration:
   
  Platform:
    osname=freebsd, osvers=9.3-release-p4, archname=amd64-freebsd-thread-multi
    uname='freebsd storage.cobweb-software.com 9.3-release-p4 freebsd 9.3-release-p4 #0 r273928: sat nov 1 17:16:18 msk 2014 root@storage.cobweb-software.com:usrobjusrsrcsysgeneric amd64 '
    config_args='-sde -Dprefix=/usr/local -Dlibperl=libperl.so.5.20 -Darchlib=/usr/local/lib/perl5/5.20/mach -Dprivlib=/usr/local/lib/perl5/5.20 -Dman3dir=/usr/local/lib/perl5/5.20/perl/man/man3 -Dman1dir=/usr/local/man/man1 -Dsitearch=/usr/local/lib/perl5/site_perl/mach/5.20 -Dsitelib=/usr/local/lib/perl5/site_perl -Dscriptdir=/usr/local/bin -Dsiteman3dir=/usr/local/lib/perl5/site_perl/man/man3 -Dsiteman1dir=/usr/local/man/man1 -Ui_malloc -Ui_iconv -Uinstallusrbinperl -Dcc=cc -Duseshrplib -Dinc_version_list=none -Dccflags=-DAPPLLIB_EXP="/usr/local/lib/perl5/5.20/BSDPAN" -Dotherlibdirs=/usr/local/lib/perl5/site_perl/5.20:/usr/local/lib/perl5/site_perl/5.20/mach -Doptimize=-g -DDEBUGGING -Ui_gdbm -Dusemultiplicity=y -Duse64bitint -Dusethreads=y -Dusemymalloc=n'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-DAPPLLIB_EXP="/usr/local/lib/perl5/5.20/BSDPAN" -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include',
    optimize='-g',
    cppflags='-DAPPLLIB_EXP="/usr/local/lib/perl5/5.20/BSDPAN" -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.2.1 20070831 patched [FreeBSD]', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags ='-pthread -Wl,-E  -fstack-protector -L/usr/local/lib'
    libpth=/usr/lib /usr/local/lib /usr/include/gcc/4.2 /usr/lib
    libs=-lgdbm -lm -lcrypt -lutil
    perllibs=-lm -lcrypt -lutil
    libc=, so=so, useshrplib=true, libperl=libperl.so.5.20
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='  -Wl,-R/usr/local/lib/perl5/5.20/mach/CORE'
    cccdlflags='-DPIC -fPIC', lddlflags='-shared  -L/usr/local/lib -fstack-protector'



@INC for perl 5.20.1:
    /raid/www/lib
    /usr/local/lib/perl5/5.20/BSDPAN
    /usr/local/lib/perl5/site_perl/mach/5.20
    /usr/local/lib/perl5/site_perl
    /usr/local/lib/perl5/5.20/mach
    /usr/local/lib/perl5/5.20
    /usr/local/lib/perl5/site_perl/5.20
    /usr/local/lib/perl5/site_perl/5.20/mach
    .


Environment for perl 5.20.1:
    HOME=/root
    LANG=ru_RU.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/root/bin
    PERL5LIB=/raid/www/lib
    PERL_BADLANG (unset)
    SHELL=/bin/csh

```
</details>

**Comment by p5pRT** [comment]
### From @hurricup

#### Created by @hurricup



Example below leads to segmentation fault\. Works fine without warnings
FATAL => 'all'&#8203;:

\#\!/usr/bin/perl
package Foo;
use strict; use utf8; use warnings FATAL => 'all';

sub new
\{
&nbsp;    return bless\{ 'field' => undef \}\, 'Foo';
\}

sub DESTROY
\{
&nbsp;    my $self = shift;
&nbsp;    $self\->\{'field'\}\->missing\_method;
\}

package main;

my $foo = new Foo;
undef\($foo\);

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=critical

Site configuration information for perl 5.20.1:

Configured by root at Sun Dec  7 13:23:13 MSK 2014.

Summary of my perl5 (revision 5 version 20 subversion 1) configuration:

  Platform:
    osname=freebsd, osvers=9.3-release-p4,
archname=amd64-freebsd-thread-multi
    uname='freebsd storage.cobweb-software.com 9.3-release-p4 freebsd
9.3-release-p4 #0 r273928: sat nov 1 17:16:18 msk 2014
root@storage.cobweb-software.com:usrobjusrsrcsysgeneric amd64 '
    config_args='-sde -Dprefix=/usr/local -Dlibperl=libperl.so.5.20
-Darchlib=/usr/local/lib/perl5/5.20/mach
-Dprivlib=/usr/local/lib/perl5/5.20
-Dman3dir=/usr/local/lib/perl5/5.20/perl/man/man3
-Dman1dir=/usr/local/man/man1
-Dsitearch=/usr/local/lib/perl5/site_perl/mach/5.20
-Dsitelib=/usr/local/lib/perl5/site_perl -Dscriptdir=/usr/local/bin
-Dsiteman3dir=/usr/local/lib/perl5/site_perl/man/man3
-Dsiteman1dir=/usr/local/man/man1 -Ui_malloc -Ui_iconv -Uinstallusrbinperl
-Dcc=cc -Duseshrplib -Dinc_version_list=none
-Dccflags=-DAPPLLIB_EXP="/usr/local/lib/perl5/5.20/BSDPAN"
-Dotherlibdirs=/usr/local/lib/perl5/site_perl/5.20:/usr/local/lib/perl5/site_perl/5.20/mach
-Doptimize=-g -DDEBUGGING -Ui_gdbm -Dusemultiplicity=y -Duse64bitint
-Dusethreads=y -Dusemymalloc=n'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-DAPPLLIB_EXP="/usr/local/lib/perl5/5.20/BSDPAN"
-DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -DDEBUGGING -fno-strict-aliasing
-pipe -fstack-protector -I/usr/local/include',
    optimize='-g',
    cppflags='-DAPPLLIB_EXP="/usr/local/lib/perl5/5.20/BSDPAN"
-DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -DDEBUGGING -fno-strict-aliasing
-pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.2.1 20070831 patched [FreeBSD]',
gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t',
lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags ='-pthread -Wl,-E  -fstack-protector -L/usr/local/lib'
    libpth=/usr/lib /usr/local/lib /usr/include/gcc/4.2 /usr/lib
    libs=-lgdbm -lm -lcrypt -lutil
    perllibs=-lm -lcrypt -lutil
    libc=, so=so, useshrplib=true, libperl=libperl.so.5.20
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='
 -Wl,-R/usr/local/lib/perl5/5.20/mach/CORE'
    cccdlflags='-DPIC -fPIC', lddlflags='-shared  -L/usr/local/lib
-fstack-protector'



@INC for perl 5.20.1:
    /raid/www/lib
    /usr/local/lib/perl5/5.20/BSDPAN
    /usr/local/lib/perl5/site_perl/mach/5.20
    /usr/local/lib/perl5/site_perl
    /usr/local/lib/perl5/5.20/mach
    /usr/local/lib/perl5/5.20
    /usr/local/lib/perl5/site_perl/5.20
    /usr/local/lib/perl5/site_perl/5.20/mach
    .


Environment for perl 5.20.1:
    HOME=/root
    LANG=ru_RU.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/root/bin
    PERL5LIB=/raid/www/lib
    PERL_BADLANG (unset)
    SHELL=/bin/csh

```
</details>

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue Dec 09 12&#8203;:27&#8203;:08 2014\, hurricup@&#8203;gmail\.com wrote&#8203;:
> Example below leads to segmentation fault\. Works fine without warnings
> FATAL => 'all'&#8203;:
> 
> \#\!/usr/bin/perl
> package Foo;
>  use strict; use utf8; use warnings FATAL => 'all';
> 
> sub new
> \{
>     return bless\{ 'field' => undef \}\, 'Foo';
> \}
> 
> sub DESTROY
> \{
>     my $self = shift;
>     $self\->\{'field'\}\->missing\_method;
> \}
> 
> package main;
> 
> my $foo = new Foo;
> undef\($foo\);

This is recursing deeply&#8203;:

\#0  0x000000000051d269 in Perl\_sv\_grow \(sv=sv@&#8203;entry=0x1576988\, newlen=16\)
&nbsp;    at sv\.c&#8203;:1620
\#1  0x0000000000532b6a in Perl\_sv\_catpvn\_flags \(dsv=dsv@&#8203;entry=0x1576988\, 
&nbsp;    sstr=sstr@&#8203;entry=0x690396 "\\t\(in cleanup\) %\-p"\, slen=14\, 
&nbsp;    flags=flags@&#8203;entry=0\) at sv\.c&#8203;:5464
\#2  0x0000000000510798 in Perl\_sv\_vcatpvfn\_flags \(sv=sv@&#8203;entry=0x1576988\, 
&nbsp;    pat=pat@&#8203;entry=0x690396 "\\t\(in cleanup\) %\-p"\, patlen=patlen@&#8203;entry=17\, 
&nbsp;    args=args@&#8203;entry=0x7ffffff7f348\, svargs=0x0\, svmax=0\, 
&nbsp;    maybe\_tainted=maybe\_tainted@&#8203;entry=0x0\, flags=flags@&#8203;entry=0\) at sv\.c&#8203;:11354
\#3  0x0000000000514b7b in Perl\_sv\_vsetpvfn \(sv=sv@&#8203;entry=0x1576988\, 
&nbsp;    pat=pat@&#8203;entry=0x690396 "\\t\(in cleanup\) %\-p"\, patlen=17\, 
&nbsp;    args=args@&#8203;entry=0x7ffffff7f348\, svargs=svargs@&#8203;entry=0x0\, 
&nbsp;    svmax=svmax@&#8203;entry=0\, maybe\_tainted=maybe\_tainted@&#8203;entry=0x0\) at sv\.c&#8203;:10683
\#4  0x00000000004d5118 in Perl\_vmess \(pat=0x690396 "\\t\(in cleanup\) %\-p"\, 
&nbsp;    args=0x7ffffff7f348\) at util\.c&#8203;:1451
\#5  0x00000000004d559a in Perl\_vwarner \(err=\<optimized out>\, 
&nbsp;    pat=\<optimized out>\, args=\<optimized out>\) at util\.c&#8203;:1926
\#6  0x00000000004d57ce in Perl\_ck\_warner \(err=err@&#8203;entry=12\, 
&nbsp;    pat=pat@&#8203;entry=0x690396 "\\t\(in cleanup\) %\-p"\) at util\.c&#8203;:1905
\#7  0x000000000056b19a in Perl\_die\_unwind \(msv=msv@&#8203;entry=0x1576958\)
&nbsp;    at pp\_ctl\.c&#8203;:1613
\#8  0x00000000004d566e in Perl\_vwarner \(err=\<optimized out>\, 
&nbsp;    pat=\<optimized out>\, args=\<optimized out>\) at util\.c&#8203;:1933
\#9  0x00000000004d57ce in Perl\_ck\_warner \(err=err@&#8203;entry=12\, 
&nbsp;    pat=pat@&#8203;entry=0x690396 "\\t\(in cleanup\) %\-p"\) at util\.c&#8203;:1905
\#10 0x000000000056b19a in Perl\_die\_unwind \(msv=msv@&#8203;entry=0x1576928\)
&nbsp;    at pp\_ctl\.c&#8203;:1613
\#11 0x00000000004d566e in Perl\_vwarner \(err=\<optimized out>\, 
&nbsp;    pat=\<optimized out>\, args=\<optimized out>\) at util\.c&#8203;:1933
\#12 0x00000000004d57ce in Perl\_ck\_warner \(err=err@&#8203;entry=12\, 
&nbsp;    pat=pat@&#8203;entry=0x690396 "\\t\(in cleanup\) %\-p"\) at util\.c&#8203;:1905
\#13 0x000000000056b19a in Perl\_die\_unwind \(msv=msv@&#8203;entry=0x15768f8\)
&nbsp;    at pp\_ctl\.c&#8203;:1613
\#14 0x00000000004d566e in Perl\_vwarner \(err=\<optimized out>\, 
&nbsp;    pat=\<optimized out>\, args=\<optimized out>\) at util\.c&#8203;:1933
\#15 0x00000000004d57ce in Perl\_ck\_warner \(err=err@&#8203;entry=12\, 
&nbsp;    pat=pat@&#8203;entry=0x690396 "\\t\(in cleanup\) %\-p"\) at util\.c&#8203;:1905
\#16 0x000000000056b19a in Perl\_die\_unwind \(msv=msv@&#8203;entry=0x15768c8\)
&nbsp;    at pp\_ctl\.c&#8203;:1613
\.\.\.
\#4244 0x00000000004d3c98 in Perl\_vcroak \(pat=\<optimized out>\, 
&nbsp;    args=args@&#8203;entry=0x7fffffffe278\) at util\.c&#8203;:1681
\#4245 0x00000000004d3dbc in Perl\_croak \(
&nbsp;    pat=pat@&#8203;entry=0x65ced0 "Can't call method \\"%\-p\\" on an undefined value"\)
&nbsp;    at util\.c&#8203;:1726
\#4246 0x00000000004f88ad in S\_opmethod\_stash \(meth=0x8f7b48\) at pp\_hot\.c&#8203;:3428
\#4247 0x00000000005083f7 in Perl\_pp\_method\_named \(\) at pp\_hot\.c&#8203;:3539

\#4248 0x00000000004d1f1a in Perl\_runops\_debug \(\) at dump\.c&#8203;:2230
\#4249 0x000000000044afb6 in Perl\_call\_sv \(sv=sv@&#8203;entry=0x8eac40\, 
&nbsp;    flags=flags@&#8203;entry=45\) at perl\.c&#8203;:2730
\#4250 0x000000000050b2b9 in S\_curse \(sv=sv@&#8203;entry=0x8d6130\, 
&nbsp;    check\_refcnt=check\_refcnt@&#8203;entry=true\) at sv\.c&#8203;:6871
\#4251 0x000000000050b846 in Perl\_sv\_clear \(orig\_sv=orig\_sv@&#8203;entry=0x8d6130\)
&nbsp;    at sv\.c&#8203;:6499
\#4252 0x000000000050c7e5 in Perl\_sv\_free2 \(sv=0x8d6130\, rc=\<optimized out>\)
&nbsp;    at sv\.c&#8203;:6972
\#4253 0x000000000053d73d in Perl\_pp\_undef \(\) at pp\.c&#8203;:984
\#4254 0x00000000004d1f1a in Perl\_runops\_debug \(\) at dump\.c&#8203;:2230

\#4255 0x0000000000453fff in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2421
\#4256 perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2344
\#4257 0x0000000000424845 in main \(argc=3\, argv=0x7fffffffe8e8\, 
&nbsp;    env=0x7fffffffe908\) at perlmain\.c&#8203;:116

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Tue Dec 09 15&#8203;:19&#8203;:12 2014\, tonyc wrote&#8203;:
> On Tue Dec 09 12&#8203;:27&#8203;:08 2014\, hurricup@&#8203;gmail\.com wrote&#8203;:
> > Example below leads to segmentation fault\. Works fine without
> > warnings
> > FATAL => 'all'&#8203;:
> >
> > \#\!/usr/bin/perl
> > package Foo;
> >  use strict; use utf8; use warnings FATAL => 'all';
> >
> > sub new
> > \{
> >     return bless\{ 'field' => undef \}\, 'Foo';
> > \}
> >
> > sub DESTROY
> > \{
> >     my $self = shift;
> >     $self\->\{'field'\}\->missing\_method;
> > \}
> >
> > package main;
> >
> > my $foo = new Foo;
> > undef\($foo\);
> 
> This is recursing deeply&#8203;:

Oh\, \*that\* bug\.  Last time this came up\, no one could decide exactly how it should behave\.

Errors in destructors are turned into warning\.  If those warnings are fatal\, then they get turned into errors\, but errors in destructors are caught and turned into warnings\.\.\.\.

I don’t remember how the previous conversation ended\, or which ticket it was in \(it was a side issue in the ticket in question\, so it’s hard to search for it\)\.

Should we just ignore the fatality in this case and emit a warning?

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue Dec 09 16&#8203;:11&#8203;:46 2014\, sprout wrote&#8203;:
> Errors in destructors are turned into warning\.  If those warnings are
> fatal\, then they get turned into errors\, but errors in destructors are
> caught and turned into warnings\.\.\.\.
> 
> I don’t remember how the previous conversation ended\, or which ticket
> it was in \(it was a side issue in the ticket in question\, so it’s hard
> to search for it\)\.
> 
> Should we just ignore the fatality in this case and emit a warning?

I think so\.

Tony

**Comment by p5pRT** [comment]
### From @mauke

Am 10\.12\.2014 um 03&#8203;:37 schrieb Tony Cook via RT&#8203;:
> On Tue Dec 09 16&#8203;:11&#8203;:46 2014\, sprout wrote&#8203;:
>> Errors in destructors are turned into warning\.  If those warnings are
>> fatal\, then they get turned into errors\, but errors in destructors are
>> caught and turned into warnings\.\.\.\.
>>
>> I don’t remember how the previous conversation ended\, or which ticket
>> it was in \(it was a side issue in the ticket in question\, so it’s hard
>> to search for it\)\.
>>
>> Should we just ignore the fatality in this case and emit a warning?
>
> I think so\.

Seems reasonable to me\.

\-\- 
Lukas Mai \<plokinom@&#8203;gmail\.com>

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, Dec 09\, 2014 at 12&#8203;:28&#8203;:24PM \-0800\, via RT wrote&#8203;:
> Example below leads to segmentation fault\. Works fine without warnings
> FATAL => 'all'&#8203;:
> 
> \#\!/usr/bin/perl
> package Foo;
> use strict; use utf8; use warnings FATAL => 'all';
> 
> sub new
> \{
>     return bless\{ 'field' => undef \}\, 'Foo';
> \}
> 
> sub DESTROY
> \{
>     my $self = shift;
>     $self\->\{'field'\}\->missing\_method;
> \}
> 
> package main;
> 
> my $foo = new Foo;
> undef\($foo\);

It's getting stuck in a recursive loop\, emitting a warning which gets
upgraded to a croak \(due to FATAL => 'all'\) which emits a warning\,
and so on until either the stack blows or memory is exhausted\.

The bit I don't understand is that die\_unwind\(\)\, in addition to croaking
with this message&#8203;:

&nbsp;    Can't call method "missing\_method" on an undefined value

is first attempting to emit this warning&#8203;:

&nbsp;    \\t\(in cleanup\) Can't call method "missing\_method" on an undefined value


The actual code in pp\_ctl\.c is&#8203;:

&nbsp;    if \(in\_eval & EVAL\_KEEPERR\) \{
&nbsp;        Perl\_ck\_warner\(aTHX\_ packWARN\(WARN\_MISC\)\, "\\t\(in cleanup\) %"SVf\,
&nbsp;               SVfARG\(exceptsv\)\);
&nbsp;    \}

and EVAL\_KEEPERR is true because S\_curse\(\) has done

&nbsp;    call\_cv\("DESTROY"\, G\_DISCARD|G\_EVAL|G\_KEEPERR|G\_VOID\);

Because I don't understand the whole die / $@&#8203; / stack unwind malarky\,
I don't feel in a position to know how to fix this\. Zefram? Anyone else?


\-\- 
You live and learn \(although usually you just live\)\.

**Comment by p5pRT** [comment]
### From @iabyn

On Wed\, Dec 10\, 2014 at 03&#8203;:47&#8203;:19PM \+0000\, Dave Mitchell wrote&#8203;:
> On Tue\, Dec 09\, 2014 at 12&#8203;:28&#8203;:24PM \-0800\, via RT wrote&#8203;:
> > Example below leads to segmentation fault\. Works fine without warnings
> > FATAL => 'all'&#8203;:

Ah I see now this is a duplicate of \#123398\. Any further discussion should
be on that ticket\.

\-\- 
It's not that I'm afraid to die\, I just don't want to be there when it
happens\.
&nbsp;    \-\- Woody Allen

**Comment by p5pRT** [comment]
### From @cpansprout

On Wed Dec 10 07&#8203;:47&#8203;:44 2014\, davem wrote&#8203;:
> On Tue\, Dec 09\, 2014 at 12&#8203;:28&#8203;:24PM \-0800\, via RT wrote&#8203;:
> > Example below leads to segmentation fault\. Works fine without warnings
> > FATAL => 'all'&#8203;:
> > 
> > \#\!/usr/bin/perl
> > package Foo;
> > use strict; use utf8; use warnings FATAL => 'all';
> > 
> > sub new
> > \{
> >     return bless\{ 'field' => undef \}\, 'Foo';
> > \}
> > 
> > sub DESTROY
> > \{
> >     my $self = shift;
> >     $self\->\{'field'\}\->missing\_method;
> > \}
> > 
> > package main;
> > 
> > my $foo = new Foo;
> > undef\($foo\);
> 
> It's getting stuck in a recursive loop\, emitting a warning which gets
> upgraded to a croak \(due to FATAL => 'all'\) which emits a warning\,
> and so on until either the stack blows or memory is exhausted\.
> 
> The bit I don't understand is that die\_unwind\(\)\, in addition to croaking
> with this message&#8203;:
> 
>     Can't call method "missing\_method" on an undefined value
> 
> is first attempting to emit this warning&#8203;:
> 
>     \\t\(in cleanup\) Can't call method "missing\_method" on an undefined value
> 
> 
> The actual code in pp\_ctl\.c is&#8203;:
> 
>     if \(in\_eval & EVAL\_KEEPERR\) \{
>         Perl\_ck\_warner\(aTHX\_ packWARN\(WARN\_MISC\)\, "\\t\(in cleanup\) %"SVf\,
>                SVfARG\(exceptsv\)\);
>     \}
> 
> and EVAL\_KEEPERR is true because S\_curse\(\) has done
> 
>     call\_cv\("DESTROY"\, G\_DISCARD|G\_EVAL|G\_KEEPERR|G\_VOID\);
> 
> Because I don't understand the whole die / $@&#8203; / stack unwind malarky\,
> I don't feel in a position to know how to fix this\. Zefram? Anyone else?

Either we need to check for a fatal warning and disable it temporarily \(in die\_unwind\)\, or when turning the warning into an error first make check that \!\(PL\_in\_eval & EVAL\_KEEPERR\) \(in the warnings code itself\)\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @mauke

On Wed Dec 10 08&#8203;:47&#8203;:43 2014\, sprout wrote&#8203;:
> 
> Either we need to check for a fatal warning and disable it temporarily
> \(in die\_unwind\)\, or when turning the warning into an error first make
> check that \!\(PL\_in\_eval & EVAL\_KEEPERR\) \(in the warnings code itself\)\.

I've attached a patch to do the latter\. Comments?

And how can I write a test for this that fails nicely? Some ulimit hackery?

**Comment by p5pRT** [comment]
### From @mauke

<details><summary>0001-don-t-fatalize-warnings-during-unwinding-123398.patch</summary>

```diff
From cc84a7c92a6f33ef6ac239d916132fa38ff1b689 Mon Sep 17 00:00:00 2001
From: Lukas Mai <l.mai@web.de>
Date: Thu, 12 Feb 2015 13:29:29 +0100
Subject: [PATCH] don't fatalize warnings during unwinding (#123398)

---
 util.c | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)

diff --git a/util.c b/util.c
index 9ffdbde..0e4c2ce 100644
--- a/util.c
+++ b/util.c
@@ -1939,7 +1939,10 @@ Perl_vwarner(pTHX_ U32  err, const char* pat, va_list* args)
 {
     dVAR;
     PERL_ARGS_ASSERT_VWARNER;
-    if (PL_warnhook == PERL_WARNHOOK_FATAL || ckDEAD(err)) {
+    if (
+        (PL_warnhook == PERL_WARNHOOK_FATAL || ckDEAD(err)) &&
+        !(PL_in_eval & EVAL_KEEPERR)
+    ) {
 	SV * const msv = vmess(pat, args);
 
 	if (PL_parser && PL_parser->error_count) {
-- 
2.3.0


```
</details>

**Comment by p5pRT** [comment]
### From @wchristian

It seems to me that this behavior is not isolated to fatal warnings\, but also runtime strict exceptions\. I may be wrong\, but here's the result i am seeing on my windows Perl&#8203;:

&nbsp;    C&#8203;:\\>perl \-e "use warnings FATAL => 'all'; sub DESTROY \{ my $x \+ 1;\}; bless \{\}"
&nbsp;    
&nbsp;    C&#8203;:\\>perl \-e "use warnings FATAL => 'all'; my $x \+ 1;"
&nbsp;    Useless use of addition \(\+\) in void context at \-e line 1\.
&nbsp;    
&nbsp;    C&#8203;:\\>perl \-e "use strict; my $r = 'f'; sub DESTROY \{ $$r; \}; bless \{\}"
&nbsp;    
&nbsp;    C&#8203;:\\>perl \-e "use strict; my $r = 'f'; $$r;"
&nbsp;    Can't use string \("f"\) as a SCALAR ref while "strict refs" in use at \-e line 1\.

**Comment by p5pRT** [comment]
### From @wchristian

On Tue Mar 17 10&#8203;:49&#8203;:20 2015\, Mithaldu wrote&#8203;:
> I may be wrong

I was wrong\, was seeing scoping oddities\.

That said\, while i'm poking this\, Mauke's patch above has been sitting there for a while and deserves attention\.

**Comment by p5pRT** [comment]
### From @tonycoz

On Thu Feb 12 04&#8203;:55&#8203;:24 2015\, mauke\- wrote&#8203;:
> On Wed Dec 10 08&#8203;:47&#8203;:43 2014\, sprout wrote&#8203;:
> > 
> > Either we need to check for a fatal warning and disable it temporarily
> > \(in die\_unwind\)\, or when turning the warning into an error first make
> > check that \!\(PL\_in\_eval & EVAL\_KEEPERR\) \(in the warnings code itself\)\.
> 
> I've attached a patch to do the latter\. Comments?
> 
> And how can I write a test for this that fails nicely? Some ulimit hackery?

Thanks\, applied as 46b27d2f2c37f40dde845f9b4743975c69f2cc27\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
@mauke - Status changed from 'pending release' to 'resolved'
