### ISSUE TITLE
Segmentation fault while parsing incorrect code

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14438]
Migrated from [rt.perl.org#123652](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=123652) (status was 'resolved')

Searchable as RT123652$

**Comment by p5pRT** [comment]
### From thecrux@gmail.com

Got interesting SIGSEGV case

&nbsp;    $ perl \-e '$1=eval\{a&#8203;:\}'
&nbsp;    zsh&#8203;: segmentation fault  perl \-e '$1=eval\{a&#8203;:\}'

SIGSEGV reproduced for Perl 5\.16\, 5\.18\, 5\.20\, blead\. Perl 5\.8\.9 seems not affected

When debugging enabled i've got SIGABRT instead of SIGSEGV

&nbsp;    $ perlbrew use perl\-5\.21\.6\-thr\-dbg
&nbsp;    $ gdb \-\-args perl \-e '$1=eval\{a&#8203;:\}'
&nbsp;    \(gdb\) run
&nbsp;    Program received signal SIGABRT\, Aborted\.
&nbsp;    0x00007ffff7106365 in \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:56

&nbsp;    $\(gdb\) bt
&nbsp;    \#0  0x00007ffff7106365 in \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:56
&nbsp;    \#1  0x00007ffff71077e8 in \_\_GI\_abort \(\) at abort\.c&#8203;:90
&nbsp;    \#2  0x00007ffff70ff3b3 in \_\_assert\_fail\_base \(fmt=0x7ffff723e6f8 "%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\, 
&nbsp;    assertion=assertion@&#8203;entry=0x60d840 "\(\(LOGOP\*\)o\)\->op\_other\->op\_type == OP\_LEAVETRY"\, file=file@&#8203;entry=0x6ab222 "op\.c"\, 
&nbsp;    line=line@&#8203;entry=12600\, function=function@&#8203;entry=0x614e6d \<\_\_PRETTY\_FUNCTION\_\_\.22182> "Perl\_rpeep"\) at assert\.c&#8203;:92
&nbsp;    \#3  0x00007ffff70ff462 in \_\_GI\_\_\_assert\_fail \(
&nbsp;    assertion=assertion@&#8203;entry=0x60d840 "\(\(LOGOP\*\)o\)\->op\_other\->op\_type == OP\_LEAVETRY"\, file=file@&#8203;entry=0x6ab222 "op\.c"\, 
&nbsp;    line=line@&#8203;entry=12600\, function=function@&#8203;entry=0x614e6d \<\_\_PRETTY\_FUNCTION\_\_\.22182> "Perl\_rpeep"\) at assert\.c&#8203;:101
&nbsp;    \#4  0x0000000000431bed in Perl\_rpeep \(my\_perl=0x8e7010\, o=0x919688\) at op\.c&#8203;:12600
&nbsp;    \.\.\.

&nbsp;    \(gdb\)frame 4
&nbsp;    \(gdb\)list
&nbsp;    12598    
&nbsp;    12599            case OP\_ENTERTRY&#8203;:
&nbsp;    12600            assert\(cLOGOPo\->op\_other\->op\_type == OP\_LEAVETRY\);
&nbsp;    12601            DEFER\(cLOGOPo\->op\_other\);
&nbsp;    12602            break;
&nbsp;    12603

**Comment by p5pRT** [comment]
### From @jkeenan

On Thu Jan 22 06&#8203;:15&#8203;:40 2015\, crux wrote&#8203;:
> Got interesting SIGSEGV case
> 
> $ perl \-e '$1=eval\{a&#8203;:\}'
> zsh&#8203;: segmentation fault  perl \-e '$1=eval\{a&#8203;:\}'
> 
> SIGSEGV reproduced for Perl 5\.16\, 5\.18\, 5\.20\, blead\. Perl 5\.8\.9 seems
> not affected
> 
> When debugging enabled i've got SIGABRT instead of SIGSEGV
> 
> $ perlbrew use perl\-5\.21\.6\-thr\-dbg
> $ gdb \-\-args perl \-e '$1=eval\{a&#8203;:\}'
> \(gdb\) run
> Program received signal SIGABRT\, Aborted\.
> 0x00007ffff7106365 in \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at
> \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:56
> 
> $\(gdb\) bt
> \#0  0x00007ffff7106365 in \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at
> \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:56
> \#1  0x00007ffff71077e8 in \_\_GI\_abort \(\) at abort\.c&#8203;:90
>  \#2  0x00007ffff70ff3b3 in \_\_assert\_fail\_base \(fmt=0x7ffff723e6f8
> "%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\,
>  assertion=assertion@&#8203;entry=0x60d840 "\(\(LOGOP\*\)o\)\->op\_other\->op\_type ==
> OP\_LEAVETRY"\, file=file@&#8203;entry=0x6ab222 "op\.c"\,
> line=line@&#8203;entry=12600\, function=function@&#8203;entry=0x614e6d
> \<\_\_PRETTY\_FUNCTION\_\_\.22182> "Perl\_rpeep"\) at assert\.c&#8203;:92
> \#3  0x00007ffff70ff462 in \_\_GI\_\_\_assert\_fail \(
>  assertion=assertion@&#8203;entry=0x60d840 "\(\(LOGOP\*\)o\)\->op\_other\->op\_type ==
> OP\_LEAVETRY"\, file=file@&#8203;entry=0x6ab222 "op\.c"\,
> line=line@&#8203;entry=12600\, function=function@&#8203;entry=0x614e6d
> \<\_\_PRETTY\_FUNCTION\_\_\.22182> "Perl\_rpeep"\) at assert\.c&#8203;:101
> \#4  0x0000000000431bed in Perl\_rpeep \(my\_perl=0x8e7010\, o=0x919688\) at
> op\.c&#8203;:12600
> \.\.\.
> 
> \(gdb\)frame 4
> \(gdb\)list
>        12598
> 12599               case OP\_ENTERTRY&#8203;:
> 12600                   assert\(cLOGOPo\->op\_other\->op\_type ==
> OP\_LEAVETRY\);
> 12601                   DEFER\(cLOGOPo\->op\_other\);
> 12602                   break;
>        12603

Confirmed; see attachment\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @jkeenan

\[perl\] 88 $ \./perl \-e '$1=eval\{a&#8203;:\}'
perl&#8203;: op\.c&#8203;:13712&#8203;: Perl\_rpeep&#8203;: Assertion \`\(\(LOGOP\*\)\(o\)\)\->op\_other\->op\_type == OP\_LEAVETRY' failed\.
Aborted \(core dumped\)

\[perl\] 89 $ gdb \-\-args \./perl \-e '$1=eval\{a&#8203;:\}'
GNU gdb \(Ubuntu 7\.7\.1\-0ubuntu5~14\.04\.2\) 7\.7\.1
Copyright \(C\) 2014 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from \./perl\.\.\.done\.
\(gdb\) run
Starting program&#8203;: /home/jkeenan/gitwork/perl/perl \-e \\$1=eval\\\{a&#8203;:\\\}
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
perl&#8203;: op\.c&#8203;:13712&#8203;: Perl\_rpeep&#8203;: Assertion \`\(\(LOGOP\*\)\(o\)\)\->op\_other\->op\_type == OP\_LEAVETRY' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff70e9cc9 in \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:56
56    \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;: No such file or directory\.
\(gdb\) bt
\#0  0x00007ffff70e9cc9 in \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:56
\#1  0x00007ffff70ed0d8 in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007ffff70e2b86 in \_\_assert\_fail\_base \(
&nbsp;    fmt=0x7ffff72343d0 "%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\, 
&nbsp;    assertion=assertion@&#8203;entry=0x607140 "\(\(LOGOP\*\)\(o\)\)\->op\_other\->op\_type == OP\_LEAVETRY"\, 
&nbsp;    file=file@&#8203;entry=0x6a0aea "op\.c"\, line=line@&#8203;entry=13712\, 
&nbsp;    function=function@&#8203;entry=0x60ab66 \<\_\_PRETTY\_FUNCTION\_\_\.22275> "Perl\_rpeep"\) at assert\.c&#8203;:92
\#3  0x00007ffff70e2c32 in \_\_GI\_\_\_assert\_fail \(
&nbsp;    assertion=assertion@&#8203;entry=0x607140 "\(\(LOGOP\*\)\(o\)\)\->op\_other\->op\_type == OP\_LEAVETRY"\, 
&nbsp;    file=file@&#8203;entry=0x6a0aea "op\.c"\, line=line@&#8203;entry=13712\, 
&nbsp;    function=function@&#8203;entry=0x60ab66 \<\_\_PRETTY\_FUNCTION\_\_\.22275> "Perl\_rpeep"\) at assert\.c&#8203;:101
\#4  0x0000000000439270 in Perl\_rpeep \(my\_perl=0x8e2010\, o=0x9189a8\) at op\.c&#8203;:13712
\#5  0x000000000042eb1c in Perl\_newPROG \(my\_perl=0x8e2010\, o=0x919210\) at op\.c&#8203;:4100
\#6  0x000000000048e23b in Perl\_yyparse \(my\_perl=my\_perl@&#8203;entry=0x8e2010\, gramtype=gramtype@&#8203;entry=258\)
&nbsp;    at perly\.y&#8203;:120
\#7  0x000000000044e140 in S\_parse\_body \(xsinit=0x41d540 \<xs\_init>\, env=0x0\, my\_perl=0x8e2010\) at perl\.c&#8203;:2273
\#8  perl\_parse \(my\_perl=0x8e2010\, xsinit=xsinit@&#8203;entry=0x41d540 \<xs\_init>\, argc=\<optimized out>\, 
&nbsp;    argv=\<optimized out>\, env=env@&#8203;entry=0x0\) at perl\.c&#8203;:1607
\#9  0x000000000041d3a9 in main \(argc=3\, argv=0x7fffffffd9d8\, env=0x7fffffffd9f8\) at perlmain\.c&#8203;:114
\(gdb\) frame 4
\#4  0x0000000000439270 in Perl\_rpeep \(my\_perl=0x8e2010\, o=0x9189a8\) at op\.c&#8203;:13712
13712            assert\(cLOGOPo\->op\_other\->op\_type == OP\_LEAVETRY\);
\(gdb\) list
13707             \* process the rest of the code \*/
13708            DEFER\(cLOOP\->op\_lastop\);
13709            break;
13710    
13711            case OP\_ENTERTRY&#8203;:
13712            assert\(cLOGOPo\->op\_other\->op\_type == OP\_LEAVETRY\);
13713            DEFER\(cLOGOPo\->op\_other\);
13714            break;
13715    
13716        case OP\_SUBST&#8203;:
\(gdb\) 




Summary of my perl5 \(revision 5 version 21 subversion 9\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 6a40a726ac1d6a8f37527d834a781fc5c38e12f0
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.13\.0\-44\-generic\, archname=x86\_64\-linux\-thread\-multi
&nbsp;    uname='linux zareason 3\.13\.0\-44\-generic \#73\-ubuntu smp tue dec 16 00&#8203;:22&#8203;:43 utc 2014 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;    config\_args='\-des \-Dusedevel \-DDEBUGGING \-Duseithreads'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2 \-g'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.8\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/4\.8/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-g \-L/usr/local/lib \-fstack\-protector'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES MULTIPLICITY PERLIO\_LAYERS
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD
&nbsp;                        PERL\_IMPLICIT\_CONTEXT PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_NEW\_COPY\_ON\_WRITE PERL\_PRESERVE\_IVUV
&nbsp;                        PERL\_TRACK\_MEMPOOL PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_ITHREADS USE\_LARGE\_FILES
&nbsp;                        USE\_LOCALE USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_PERLIO
&nbsp;                        USE\_PERL\_ATOF USE\_REENTRANT\_API
&nbsp;  Built under linux
&nbsp;  Compiled at Jan 22 2015 21&#8203;:57&#8203;:41
&nbsp;  %ENV&#8203;:
&nbsp;    PERL5LIB="/home/jkeenan/perl5/lib/perl5"
&nbsp;    PERLBREW\_BASHRC\_VERSION="0\.67"
&nbsp;    PERLBREW\_HOME="/home/jkeenan/\.perlbrew"
&nbsp;    PERLBREW\_MANPATH="/home/jkeenan/perl5/perlbrew/perls/perl\-5\.20\.1/man"
&nbsp;    PERLBREW\_PATH="/home/jkeenan/perl5/perlbrew/bin&#8203;:/home/jkeenan/perl5/perlbrew/perls/perl\-5\.20\.1/bin"
&nbsp;    PERLBREW\_PERL="perl\-5\.20\.1"
&nbsp;    PERLBREW\_ROOT="/home/jkeenan/perl5/perlbrew"
&nbsp;    PERLBREW\_VERSION="0\.67"
&nbsp;    PERL\_LOCAL\_LIB\_ROOT="/home/jkeenan/perl5"
&nbsp;    PERL\_MB\_OPT="\-\-install\_base "/home/jkeenan/perl5""
&nbsp;    PERL\_MM\_OPT="INSTALL\_BASE=/home/jkeenan/perl5"
&nbsp;    PERL\_WORKDIR="gitwork/perl"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /home/jkeenan/perl5/lib/perl5
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.21\.9/x86\_64\-linux\-thread\-multi
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.21\.9
&nbsp;    /usr/local/lib/perl5/5\.21\.9/x86\_64\-linux\-thread\-multi
&nbsp;    /usr/local/lib/perl5/5\.21\.9
&nbsp;    \.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Thu Jan 22 06&#8203;:15&#8203;:40 2015\, crux wrote&#8203;:
> Got interesting SIGSEGV case
> 
> $ perl \-e '$1=eval\{a&#8203;:\}'
> zsh&#8203;: segmentation fault  perl \-e '$1=eval\{a&#8203;:\}'
> 
> SIGSEGV reproduced for Perl 5\.16\, 5\.18\, 5\.20\, blead\. Perl 5\.8\.9 seems
> not affected

5\.21\.4 is unaffected\.  5\.14\.4 crashes\.

Your subject is slightly wrong\.  The code is not invalid\.  \(It just dies at run time because $1 is read\-only\.\)  You can have a label at the end of a block\.

I’ll run a bisect\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @cpansprout

On Thu Jan 22 21&#8203;:56&#8203;:06 2015\, sprout wrote&#8203;:
> On Thu Jan 22 06&#8203;:15&#8203;:40 2015\, crux wrote&#8203;:
> > Got interesting SIGSEGV case
> >
> > $ perl \-e '$1=eval\{a&#8203;:\}'
> > zsh&#8203;: segmentation fault  perl \-e '$1=eval\{a&#8203;:\}'
> >
> > SIGSEGV reproduced for Perl 5\.16\, 5\.18\, 5\.20\, blead\. Perl 5\.8\.9 seems
> > not affected
> 
> 5\.21\.4 is unaffected\.  5\.14\.4 crashes\.
> 
> Your subject is slightly wrong\.  The code is not invalid\.  \(It just
> dies at run time because $1 is read\-only\.\)  You can have a label at
> the end of a block\.
> 
> I’ll run a bisect\.

$  \.\./perl\.git/Porting/bisect\.pl \-\-target=miniperl \-\-start=v5\.12\.0 \-\-end=v5\.14\.4 \-e 'eval\{$1=eval\{a&#8203;:\}\}'
\.\.\.
eae48c8938e50ebb341a72c2886c5ae8587092a5 is the first bad commit
commit eae48c8938e50ebb341a72c2886c5ae8587092a5
Author&#8203;: Zefram \<zefram@&#8203;fysh\.org>
Date&#8203;:   Tue Oct 19 21&#8203;:16&#8203;:11 2010 \+0100

&nbsp;    refactor and regularise label/statement grammar

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @jkeenan

On Thu Jan 22 21&#8203;:56&#8203;:06 2015\, sprout wrote&#8203;:
> On Thu Jan 22 06&#8203;:15&#8203;:40 2015\, crux wrote&#8203;:
> > Got interesting SIGSEGV case
> >
> > $ perl \-e '$1=eval\{a&#8203;:\}'
> > zsh&#8203;: segmentation fault  perl \-e '$1=eval\{a&#8203;:\}'
> >
> > SIGSEGV reproduced for Perl 5\.16\, 5\.18\, 5\.20\, blead\. Perl 5\.8\.9 seems
> > not affected
> 
> 5\.21\.4 is unaffected\.  5\.14\.4 crashes\.
> 
> Your subject is slightly wrong\.  The code is not invalid\.  \(It just
> dies at run time because $1 is read\-only\.\)  You can have a label at
> the end of a block\.
> 

So\, can we have the attempt to assign to $1 throw a more tidy exception?



\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @cpansprout

Fixed in 2f465e0\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'resolved' to 'pending release'

**Comment by p5pRT** [comment]
### From thecrux@gmail.com

On Sat\, Jan 24\, 2015 at 05&#8203;:23&#8203;:34PM \-0800\, Father Chrysostomos via RT wrote&#8203;:
> Fixed in 2f465e0\.

Great\, thank you\. Whether this fix will be ported to stable 5\.20 branch?

**Comment by p5pRT** [comment]
### From @steve-m-hay

On Sat Jan 24 23&#8203;:39&#8203;:31 2015\, crux wrote&#8203;:
> On Sat\, Jan 24\, 2015 at 05&#8203;:23&#8203;:34PM \-0800\, Father Chrysostomos via RT wrote&#8203;:
> > Fixed in 2f465e0\.
> 
> Great\, thank you\. Whether this fix will be ported to stable 5\.20 branch?
> 

It looks like a suitable candidate for backporting\, so I've just added it to the voting file\, and it will be in 5\.20\.2 if a couple of other committers agree&#8203;:

http&#8203;://perl5\.git\.perl\.org/perl\.git/commit/f10d2881c7

**Comment by p5pRT** [comment]
### From @khwilliamson

Thanks for submitting this ticket

The issue should be resolved with the release today of Perl v5\.22\, available at http&#8203;://www\.perl\.org/get\.html
If you find that the problem persists\, feel free to reopen this ticket

\-\- 
Karl Williamson for the Perl 5 porters team

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
