### ISSUE TITLE
Segmentation fault in Perl_sv_setpvn()

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14460]
Migrated from [rt.perl.org#123710](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=123710) (status was 'resolved')

Searchable as RT123710$

**Comment by p5pRT** [comment]
### From thecrux@gmail.com

Simple test case produced sigsegv&#8203;:

&nbsp;    $ perl \-e '$x|=\*x=0'

\(gdb\) bt
\#0  Perl\_sv\_setpvn \(sv=0xe59e10\, ptr=0xbe35e9 ""\, len=0\) at sv\.c&#8203;:4915
\#1  0x000000000097df87 in Perl\_do\_vop \(optype=94\, sv=0xe59e10\, left=0xe59e10\, right=0xe59df8\) at doop\.c&#8203;:1022
\#2  0x00000000008478b9 in Perl\_pp\_bit\_or \(\) at pp\.c&#8203;:2257
\#3  0x000000000077382b in Perl\_runops\_standard \(\) at run\.c&#8203;:41
\#4  0x00000000004e5e1f in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2423
\#5  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2346
\#6  0x0000000000426c7c in main \(argc=3\, argv=0x7fffffffe488\, env=0x7fffffffe4a8\) at perlmain\.c&#8203;:116
\#7  0x00007ffff70d4ec5 in \_\_libc\_start\_main \(main=0x426870 \<main>\, argc=3\, argv=0x7fffffffe488\, 
&nbsp;    init=\<optimized out>\, fini=\<optimized out>\, rtld\_fini=\<optimized out>\, stack\_end=0x7fffffffe478\)
&nbsp;    at libc\-start\.c&#8203;:287
\#8  0x0000000000426cf3 in \_start \(\)

\(gdb\) list
4910        \}
4911        SvUPGRADE\(sv\, SVt\_PV\);
4912
4913        dptr = SvGROW\(sv\, len \+ 1\);
4914        Move\(ptr\,dptr\,len\,char\);
4915        dptr\[len\] = '\\0';
4916        SvCUR\_set\(sv\, len\);
4917        \(void\)SvPOK\_only\_UTF8\(sv\);          /\* validate pointer \*/
4918        SvTAINT\(sv\);
4919        if \(SvTYPE\(sv\) == SVt\_PVCV\) CvAUTOLOAD\_off\(sv\);


Crash reproduced with perl 5\.12\, 5\.16\, 5\.18\, 5\.21\.8
Bug was found by afl fuzzer \(http&#8203;://lcamtuf\.coredump\.cx/afl/\)

**Comment by p5pRT** [comment]
### From @cpansprout

On Sun Feb 01 13&#8203;:11&#8203;:02 2015\, crux wrote&#8203;:
> Simple test case produced sigsegv&#8203;:
> 
> $ perl \-e '$x|=\*x=0'

\*x=0 frees $x after $x is already on the stack\.   This is another one for \#77706\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @hvds

Found by AFL \(\<http&#8203;://lcamtuf\.coredump\.cx/afl>\)&#8203;:

% \./miniperl \-e '$x\.=\*x=0'
Segmentation fault \(core dumped\)
% 

4918        dptr\[len\] = '\\0';
\(gdb\) where
\#0  0x00000000005b5d76 in Perl\_sv\_setpvn \(sv=0xad0498\, ptr=0x7acea7 ""\, len=0\)
&nbsp;    at sv\.c&#8203;:4918
\#1  0x0000000000575574 in Perl\_pp\_concat \(\) at pp\_hot\.c&#8203;:292
\#2  0x000000000052a15e in Perl\_runops\_debug \(\) at dump\.c&#8203;:2231
\#3  0x00000000004098c7 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2423
\#4  0x0000000000408f0b in perl\_run \(my\_perl=0xaaf010\) at perl\.c&#8203;:2346
\#5  0x00000000004508b7 in main \(argc=3\, argv=0x7fffdb70cbb8\, 
&nbsp;    env=0x7fffdb70cbd8\) at miniperlmain\.c&#8203;:122

If I read it right\, the $x is stacked first; the assignment to \*x then frees the already\-stacked $x; by the time we get to sv\_setpvn the destination is a freed SV \(type = 0xff\)\, so the SvGROW returns a null pointer that we then try to write to\.

I guess in a sense this is just another example of the unrefcounted stacks issue; I'm not sure that's all that's missing here\, though\.

Hugo

**Comment by p5pRT** [comment]
### From @hvds

Ah\, I see \[perl \#123804\] is near\-identical to \[perl \#123710\]\, I'll merge\.

**Comment by p5pRT** [comment]
### From @geeknik

Built v5\.21\.10 \(v5\.21\.9\-43\-g2c3f32a\) with the following command line&#8203;:

/Configure \-des \-Dusedevel \-DDEBUGGING \-Dcc=afl\-gcc \-Doptimize=\-O2\\ \-g && AFL\_HARDEN=1 make \-j12 test\-prep

Bug found with AFL \(http&#8203;://lcamtuf\.coredump\.cx/afl\)

Valgrind&#8203;:
perl&#8203;: sv\.c&#8203;:3977&#8203;: S\_glob\_assign\_glob&#8203;: Assertion \`\(\(svtype\)\(\(\_gvgp\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_gvgp\)\->sv\_flags & 0xff\)\) == SVt\_PVLV' failed\.
==57720== 
==57720== Process terminating with default action of signal 6 \(SIGABRT\)
==57720==    at 0x5B55165&#8203;: raise \(raise\.c&#8203;:64\)
==57720==    by 0x5B583DF&#8203;: abort \(abort\.c&#8203;:92\)
==57720==    by 0x5B4E310&#8203;: \_\_assert\_fail \(assert\.c&#8203;:81\)
==57720==    by 0x994558&#8203;: S\_glob\_assign\_glob \(sv\.c&#8203;:3977\)
==57720==    by 0x959E91&#8203;: Perl\_sv\_setsv\_flags \(sv\.c&#8203;:4426\)
==57720==    by 0x8B4E17&#8203;: Perl\_pp\_sassign \(pp\_hot\.c&#8203;:231\)
==57720==    by 0x7CB49E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2237\)
==57720==    by 0x53B4C8&#8203;: perl\_run \(perl\.c&#8203;:2427\)
==57720==    by 0x42B167&#8203;: main \(perlmain\.c&#8203;:116\)
==57720== 

GDB&#8203;:
gdb\-peda$ file ~/perl/perl
gdb\-peda$ set args test26\-min
gdb\-peda$ r
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
perl&#8203;: sv\.c&#8203;:3977&#8203;: S\_glob\_assign\_glob&#8203;: Assertion \`\(\(svtype\)\(\(\_gvgp\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_gvgp\)\->sv\_flags & 0xff\)\) == SVt\_PVLV' failed\.

Program received signal SIGABRT\, Aborted\.
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-registers\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
RAX&#8203;: 0x0 
RBX&#8203;: 0x7fffffffe63b \-\-> 0x736574006c726570 \('perl'\)
RCX&#8203;: 0xffffffffffffffff 
RDX&#8203;: 0x6 
RSI&#8203;: 0xf5ac 
RDI&#8203;: 0xf5ac 
RBP&#8203;: 0x7ffff6ea9a07 \-\-> 0x257325732500203a \('&#8203;: '\)
RSP&#8203;: 0x7fffffffde98 \-\-> 0x7ffff6d923e0 \(\<\*\_\_GI\_abort\+384>&#8203;:    mov    rdx\,QWORD PTR fs&#8203;:0x10\)
RIP&#8203;: 0x7ffff6d8f165 \(\<\*\_\_GI\_raise\+53>&#8203;:    cmp    rax\,0xfffffffffffff000\)
R8 : 0x7ffff7fdd700 \(0x00007ffff7fdd700\)
R9 : 0x733e2d2970677667 \('gvgp\)\->s'\)
R10&#8203;: 0x8 
R11&#8203;: 0x206 
R12&#8203;: 0xeb3590 \("\(\(svtype\)\(\(\_gvgp\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_gvgp\)\->sv\_flags & 0xff\)\) == SVt\_PVLV"\)
R13&#8203;: 0xf4bd40 \("S\_glob\_assign\_glob"\)
R14&#8203;: 0x7ffff6ea9a07 \-\-> 0x257325732500203a \('&#8203;: '\)
R15&#8203;: 0xf89
EFLAGS&#8203;: 0x206 \(carry PARITY adjust zero sign trap INTERRUPT direction overflow\)
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-code\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
&nbsp;   0x7ffff6d8f15b \<\*\_\_GI\_raise\+43>&#8203;:    movsxd rdi\,eax
&nbsp;   0x7ffff6d8f15e \<\*\_\_GI\_raise\+46>&#8203;:    mov    eax\,0xea
&nbsp;   0x7ffff6d8f163 \<\*\_\_GI\_raise\+51>&#8203;:    syscall 
=> 0x7ffff6d8f165 \<\*\_\_GI\_raise\+53>&#8203;:    cmp    rax\,0xfffffffffffff000
&nbsp;   0x7ffff6d8f16b \<\*\_\_GI\_raise\+59>&#8203;:    ja     0x7ffff6d8f182 \<\*\_\_GI\_raise\+82>
&nbsp;   0x7ffff6d8f16d \<\*\_\_GI\_raise\+61>&#8203;:    repz ret 
&nbsp;   0x7ffff6d8f16f \<\*\_\_GI\_raise\+63>&#8203;:    nop
&nbsp;   0x7ffff6d8f170 \<\*\_\_GI\_raise\+64>&#8203;:    test   eax\,eax
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-stack\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
0000| 0x7fffffffde98 \-\-> 0x7ffff6d923e0 \(\<\*\_\_GI\_abort\+384>&#8203;:    mov    rdx\,QWORD PTR fs&#8203;:0x10\)
0008| 0x7fffffffdea0 \-\-> 0xeb3590 \("\(\(svtype\)\(\(\_gvgp\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_gvgp\)\->sv\_flags & 0xff\)\) == SVt\_PVLV"\)
0016| 0x7fffffffdea8 \-\-> 0x7ffff6eab9c1 \-\-> 0x706c6568007325 \('%s'\)
0024| 0x7fffffffdeb0 \-\-> 0x7fffffffded0 \-\-> 0x3000000018 
0032| 0x7fffffffdeb8 \-\-> 0xf89 
0040| 0x7fffffffdec0 \-\-> 0x7fffffffdfc0 \-\-> 0x7fffffffe63b \-\-> 0x736574006c726570 \('perl'\)
0048| 0x7fffffffdec8 \-\-> 0x7ffff6dc3fe6 \(\<\_\_fxprintf\+310>&#8203;:    lea    rsp\,\[rbp\-0x20\]\)
0056| 0x7fffffffded0 \-\-> 0x3000000018 
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
Legend&#8203;: code\, data\, rodata\, value
Stopped reason&#8203;: SIGABRT
0x00007ffff6d8f165 in \*\_\_GI\_raise \(sig=\<optimized out>\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:64
64    \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;: No such file or directory\.

Hexdump of 11\-byte test case&#8203;:
0000000 3024 2a3d 3d78 7824 2a3d 0030          
000000b

System Info&#8203;: Debian 7\, Kernel 3\.2\.65\-1\+deb7u1 x86\_64\, GCC 4\.9\.2\, libc 2\.13\-38\+deb7u7

**Comment by p5pRT** [comment]
### From @geeknik

[test26-min](https://rt-archive.perl.org/perl5/Ticket/Attachment/1334304/712845/test26-min)

**Comment by p5pRT** [comment]
### From @hvds

This is the same as \[perl \#123710\]\, cascading asssignment to a scalar and its glob\.

I'll merge them\.

Hugo

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @dcollinsn

\[perl \#125840\] was fixed in blead\, however is only a symptom of this larger bug\. To aid anyone attempting to resolve this\, an odd testcase\, in that it actually throws an assert fail on perls built with \-DDEBUGGING\.

Testcase&#8203;:
$0\*=$=\*=\*==$$=0

Perl 5\.10 exits with an error message&#8203;:
Modification of a read\-only value attempted at \-e line 1\.

Blead segfaults with no output

A \-DDEBUGGING blead throws the following assert fail&#8203;:
miniperl&#8203;: sv\.c&#8203;:1792&#8203;: Perl\_sv\_setnv&#8203;: Assertion \`PL\_valid\_types\_NV\_set\[\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) & 0xf\]' failed\.

**Comment by p5pRT** [comment]
### From @iabyn

On Wed\, Aug 26\, 2015 at 01&#8203;:17&#8203;:04PM \-0700\, Dan Collins via RT wrote&#8203;:
> \[perl \#125840\] was fixed in blead\, however is only a symptom of this larger bug\. To aid anyone attempting to resolve this\, an odd testcase\, in that it actually throws an assert fail on perls built with \-DDEBUGGING\.
> 
> Testcase&#8203;:
> $0\*=$=\*=\*==$$=0
> 
> Perl 5\.10 exits with an error message&#8203;:
> Modification of a read\-only value attempted at \-e line 1\.
> 
> Blead segfaults with no output
> 
> A \-DDEBUGGING blead throws the following assert fail&#8203;:
> miniperl&#8203;: sv\.c&#8203;:1792&#8203;: Perl\_sv\_setnv&#8203;: Assertion \`PL\_valid\_types\_NV\_set\[\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) & 0xf\]' failed\.

Presumably my bigger fix for \[perl \#125840\]\, 3c62f09f418b63bd\, which was
applied on Aug 30\, fixes that too? Certainly I don't see the assertion\.

\-\- 
You're only as old as you look\.

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue Sep 01 07&#8203;:14&#8203;:27 2015\, davem wrote&#8203;:
> On Wed\, Aug 26\, 2015 at 01&#8203;:17&#8203;:04PM \-0700\, Dan Collins via RT wrote&#8203;:
> > \[perl \#125840\] was fixed in blead\, however is only a symptom of this
> > larger bug\. To aid anyone attempting to resolve this\, an odd
> > testcase\, in that it actually throws an assert fail on perls built
> > with \-DDEBUGGING\.
> >
> > Testcase&#8203;:
> > $0\*=$=\*=\*==$$=0
> >
> > Perl 5\.10 exits with an error message&#8203;:
> > Modification of a read\-only value attempted at \-e line 1\.
> >
> > Blead segfaults with no output
> >
> > A \-DDEBUGGING blead throws the following assert fail&#8203;:
> > miniperl&#8203;: sv\.c&#8203;:1792&#8203;: Perl\_sv\_setnv&#8203;: Assertion
> > \`PL\_valid\_types\_NV\_set\[\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) & 0xf\]'
> > failed\.
> 
> Presumably my bigger fix for \[perl \#125840\]\, 3c62f09f418b63bd\, which
> was
> applied on Aug 30\, fixes that too? Certainly I don't see the
> assertion\.

Yes\, your fix also fixed this\. Closing\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for submitting this report\.  You have helped make Perl better\.
&nbsp;    
With the release of Perl 5\.24\.0 on May 9\, 2016\, this and 149 other issues have been resolved\.

Perl 5\.24\.0 may be downloaded via https://metacpan.org/release/RJBS/perl-5.24.0

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
