### ISSUE TITLE
Segmentation fault in Perl_pp_subtract()

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14461]
Migrated from [rt.perl.org#123711](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=123711) (status was 'resolved')

Searchable as RT123711$

**Comment by p5pRT** [comment]
### From thecrux@gmail.com

Another testcase&#8203;:

&nbsp;    $ perl \-e '0\-5x\-l\{0\}'

\(gdb\) run
Program received signal SIGSEGV\, Segmentation fault\.
0x000000000083ef0b in Perl\_pp\_subtract \(\) at pp\.c&#8203;:1786
1786        tryAMAGICbin\_MG\(subtr\_amg\, AMGf\_assign|AMGf\_numeric\);

\(gdb\) bt
\#0  0x000000000083ef0b in Perl\_pp\_subtract \(\) at pp\.c&#8203;:1786
\#1  0x000000000077382b in Perl\_runops\_standard \(\) at run\.c&#8203;:41
\#2  0x00000000004e5e1f in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2423
\#3  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2346
\#4  0x0000000000426c7c in main \(argc=3\, argv=0x7fffffffe488\, env=0x7fffffffe4a8\) at perlmain\.c&#8203;:116
\#5  0x00007ffff70d4ec5 in \_\_libc\_start\_main \(main=0x426870 \<main>\, argc=3\, argv=0x7fffffffe488\, 
&nbsp;    init=\<optimized out>\, fini=\<optimized out>\, rtld\_fini=\<optimized out>\, stack\_end=0x7fffffffe478\)
&nbsp;    at libc\-start\.c&#8203;:287
\#6  0x0000000000426cf3 in \_start \(\)

\(gdb\) list
1781    \}
1782
1783    PP\(pp\_subtract\)
1784    \{
1785        dSP; dATARGET; bool useleft; SV \*svl\, \*svr;
1786        tryAMAGICbin\_MG\(subtr\_amg\, AMGf\_assign|AMGf\_numeric\);
1787        svr = TOPs;
1788        svl = TOPm1s;
1789        useleft = USE\_LEFT\(svl\);
1790    \#ifdef PERL\_PRESERVE\_IVUV

Crash reproduced with perl 5\.12\, 5\.16\, 5\.18\, 5\.21\.8
Bug was found by afl fuzzer \(http&#8203;://lcamtuf\.coredump\.cx/afl/\)

**Comment by p5pRT** [comment]
### From @cpansprout

On Sun Feb 01 13&#8203;:15&#8203;:58 2015\, crux wrote&#8203;:
> Another testcase&#8203;:
> 
> $ perl \-e '0\-5x\-l\{0\}'
> 
> \(gdb\) run
> Program received signal SIGSEGV\, Segmentation fault\.
> 0x000000000083ef0b in Perl\_pp\_subtract \(\) at pp\.c&#8203;:1786
> 1786        tryAMAGICbin\_MG\(subtr\_amg\, AMGf\_assign|AMGf\_numeric\);

That looks like a parsing bug\.  The op tree is junk&#8203;:

$ \./perl \-ILib \-MO=Concise \-e '0\-5x\-l\{0\}'
a  \<@&#8203;> leave\[1 ref\] vKP/REFC \->\(end\)
1     \<0> enter \->2
2     \<;> nextstate\(main 1 \-e&#8203;:1\) v&#8203;:\{ \->3
9     \<2> subtract\[t2\] vK/2 \->a
3        \<$> const\[IV 0\] s \->4
8        \<2> repeat\[t1\] sK/2 \->9
4           \<$> const\[IV 5\] s \->5
7           \<1> ftlink sK/1 \->8
\-              \<@&#8203;> lineseq sK \->7
5                 \<;> nextstate\(main 2 \-e&#8203;:1\) v \->6
6                 \<$> const\[IV 0\] s \->7
\-e syntax OK

Somehow the argument to \-l is interpreted as a block\, but the resulting op tree has no enter/leave to protect the stack\, so the nextstate op stomps on stack entries in use by the rest of the statement\.

It seems other filetest ops have the same bug&#8203;:

$ \./perl \-ILib \-MO=Concise \-e '\-b\{0\}'
5  \<@&#8203;> leave\[1 ref\] vKP/REFC \->\(end\)
1     \<0> enter \->2
\-     \<;> ex\-nextstate\(main 1 \-e&#8203;:1\) v&#8203;:\{ \->2
4     \<1> ftblk vK/1 \->5
\-        \<@&#8203;> lineseq sK \->4
2           \<;> nextstate\(main 2 \-e&#8203;:1\) v \->3
3           \<$> const\[IV 0\] s \->4
\-e syntax OK

I suppose no one has ever put \{ after a filetest before\.  This may be related to // handling\, because the expectation is XTERMORDORDOR \(excerpt from \-DT output follows\)&#8203;:

\#\#\# 1&#8203;:LEX\_NORMAL/XTERMORDORDOR "\{0\}\\n"
\#\#\# \<== '\{'

And the bug does not affect 5\.8\.  I am currently running a bisect\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Sun Feb 01 13&#8203;:50&#8203;:14 2015\, sprout wrote&#8203;:
> I suppose no one has ever put \{ after a filetest before\.  This may be
> related to // handling\, because the expectation is XTERMORDORDOR
> \(excerpt from \-DT output follows\)&#8203;:
> 
> \#\#\# 1&#8203;:LEX\_NORMAL/XTERMORDORDOR "\{0\}\\n"
> \#\#\# \<== '\{'
> 
> And the bug does not affect 5\.8\.  I am currently running a bisect\.

$  \.\./perl\.git/Porting/bisect\.pl \-\-target=miniperl \-\-start=perl\-5\.8\.0 \-\-end=perl\-5\.10\.1 \-e '0\-5x\-l\{0\}'
\.\.\.
6f33ba736d46c2f5bfdb2405fd09d82ec18a1d07 is the first bad commit
commit 6f33ba736d46c2f5bfdb2405fd09d82ec18a1d07
Author&#8203;: Rafael Garcia\-Suarez \<rgarciasuarez@&#8203;gmail\.com>
Date&#8203;:   Sun Aug 25 18&#8203;:42&#8203;:46 2002 \+0000

&nbsp;    Fix parsing problems with the // operator\.
&nbsp;    Make // able to follow various unary operators used without
&nbsp;    arguments or parens \(shift\, pop\, getc\, pos\, readline\,
&nbsp;    readlink\, undef\, umask\, and the filetest operators\)\, as
&nbsp;    well as the \<FH> operator\.
&nbsp;    
&nbsp;    p4raw\-id&#8203;: //depot/perl@&#8203;17777

It’s not just filetest operators that are affected\.

$ \./perl \-ILib \-MO=Concise \-e 'getc\{0\}'
6  \<@&#8203;> leave\[1 ref\] vKP/REFC \->\(end\)
1     \<0> enter \->2
\-     \<;> ex\-nextstate\(main 1 \-e&#8203;:1\) v&#8203;:\{ \->2
5     \<1> getc\[t1\] vK/1 \->6
4        \<1> rv2gv sK\*/FAKE\,1 \->5
\-           \<@&#8203;> lineseq sK \->4
2              \<;> nextstate\(main 2 \-e&#8203;:1\) v \->3
3              \<$> const\[IV 0\] s \->4
\-e syntax OK

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @cpansprout

Fixed in 83a85f4\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thanks for submitting this ticket

The issue should be resolved with the release today of Perl v5\.22\, available at http&#8203;://www\.perl\.org/get\.html
If you find that the problem persists\, feel free to reopen this ticket

\-\- 
Karl Williamson for the Perl 5 porters team

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
