### ISSUE TITLE
Perl_rpeep: Assertion `!(o2->op_flags & ~(3|32|128))' failed (op.c:12894)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14470]
Migrated from [rt.perl.org#123735](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=123735) (status was 'resolved')

Searchable as RT123735$

**Comment by p5pRT** [comment]
### From @geeknik

Built v5\.21\.9 \(v5\.21\.8\-200\-ga57d3d4\) using the following command line&#8203;:

\./Configure \-des \-Dusedevel \-DDEBUGGING \-Dcc=afl\-gcc \-Doptimize=\-O2\\ \-g && AFL\_HARDEN=1 make \-j6 test\-prep

Bug found with AFL \(http&#8203;://lcamtuf\.coredump\.cx/afl\)

GDB output&#8203;:
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
perl&#8203;: op\.c&#8203;:12894&#8203;: Perl\_rpeep&#8203;: Assertion \`\!\(o2\->op\_flags & ~\(3|32|128\)\)' failed\.

Program received signal SIGABRT\, Aborted\.
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-registers\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
RAX&#8203;: 0x0 
RBX&#8203;: 0x7fffffffe653 \-\-> 0x6e696d006c726570 \('perl'\)
RCX&#8203;: 0xffffffffffffffff 
RDX&#8203;: 0x6 
RSI&#8203;: 0x76ee 
RDI&#8203;: 0x76ee 
RBP&#8203;: 0x7ffff6ea9a07 \-\-> 0x257325732500203a \('&#8203;: '\)
RSP&#8203;: 0x7fffffffdcf8 \-\-> 0x7ffff6d923e0 \(\<\*\_\_GI\_abort\+384>&#8203;:    mov    rdx\,QWORD PTR fs&#8203;:0x10\)
RIP&#8203;: 0x7ffff6d8f165 \(\<\*\_\_GI\_raise\+53>&#8203;:    cmp    rax\,0xfffffffffffff000\)
R8 : 0x7ffff7fdd700 \(0x00007ffff7fdd700\)
R9 : 0x207367616c665f70 \('p\_flags '\)
R10&#8203;: 0x8 
R11&#8203;: 0x206 
R12&#8203;: 0xe77cd3 \("\!\(o2\->op\_flags & ~\(3|32|128\)\)"\)
R13&#8203;: 0xe8c013 \("Perl\_rpeep"\)
R14&#8203;: 0x7ffff6ea9a07 \-\-> 0x257325732500203a \('&#8203;: '\)
R15&#8203;: 0x325e \('^2'\)
EFLAGS&#8203;: 0x206 \(carry PARITY adjust zero sign trap INTERRUPT direction overflow\)
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-code\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
&nbsp;   0x7ffff6d8f15b \<\*\_\_GI\_raise\+43>&#8203;:    movsxd rdi\,eax
&nbsp;   0x7ffff6d8f15e \<\*\_\_GI\_raise\+46>&#8203;:    mov    eax\,0xea
&nbsp;   0x7ffff6d8f163 \<\*\_\_GI\_raise\+51>&#8203;:    syscall 
=> 0x7ffff6d8f165 \<\*\_\_GI\_raise\+53>&#8203;:    cmp    rax\,0xfffffffffffff000
&nbsp;   0x7ffff6d8f16b \<\*\_\_GI\_raise\+59>&#8203;:    ja     0x7ffff6d8f182 \<\*\_\_GI\_raise\+82>
&nbsp;   0x7ffff6d8f16d \<\*\_\_GI\_raise\+61>&#8203;:    repz ret 
&nbsp;   0x7ffff6d8f16f \<\*\_\_GI\_raise\+63>&#8203;:    nop
&nbsp;   0x7ffff6d8f170 \<\*\_\_GI\_raise\+64>&#8203;:    test   eax\,eax
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-stack\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
0000| 0x7fffffffdcf8 \-\-> 0x7ffff6d923e0 \(\<\*\_\_GI\_abort\+384>&#8203;:    mov    rdx\,QWORD PTR fs&#8203;:0x10\)
0008| 0x7fffffffdd00 \-\-> 0xe77cd3 \("\!\(o2\->op\_flags & ~\(3|32|128\)\)"\)
0016| 0x7fffffffdd08 \-\-> 0x7ffff6eab9c1 \-\-> 0x706c6568007325 \('%s'\)
0024| 0x7fffffffdd10 \-\-> 0x7fffffffdd30 \-\-> 0x3000000018 
0032| 0x7fffffffdd18 \-\-> 0x325e \('^2'\)
0040| 0x7fffffffdd20 \-\-> 0x7fffffffde20 \-\-> 0x7fffffffe653 \-\-> 0x6e696d006c726570 \('perl'\)
0048| 0x7fffffffdd28 \-\-> 0x7ffff6dc3fe6 \(\<\_\_fxprintf\+310>&#8203;:    lea    rsp\,\[rbp\-0x20\]\)
0056| 0x7fffffffdd30 \-\-> 0x3000000018 
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
Legend&#8203;: code\, data\, rodata\, value
Stopped reason&#8203;: SIGABRT
0x00007ffff6d8f165 in \*\_\_GI\_raise \(sig=\<optimized out>\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:64
64    \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;: No such file or directory\.
gdb\-peda$ bt
\#0  0x00007ffff6d8f165 in \*\_\_GI\_raise \(sig=\<optimized out>\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:64
\#1  0x00007ffff6d923e0 in \*\_\_GI\_abort \(\) at abort\.c&#8203;:92
\#2  0x00007ffff6d88311 in \*\_\_GI\_\_\_assert\_fail \(assertion=assertion@&#8203;entry=0xe77cd3 "\!\(o2\->op\_flags & ~\(3|32|128\)\)"\, file=\<optimized out>\, file@&#8203;entry=0xf253e2 "op\.c"\, line=line@&#8203;entry=0x325e\, function=function@&#8203;entry=0xe8c013 "Perl\_rpeep"\) at assert\.c&#8203;:81
\#3  0x00000000004962b9 in Perl\_rpeep \(o=0x1185b78\) at op\.c&#8203;:12894
\#4  0x000000000048b6f6 in Perl\_newPROG \(o=\<optimized out>\) at op\.c&#8203;:4087
\#5  0x0000000000662f94 in Perl\_yyparse \(gramtype=\<optimized out>\) at perly\.y&#8203;:120
\#6  0x000000000052d275 in S\_parse\_body \(env=env@&#8203;entry=0x0\, xsinit=xsinit@&#8203;entry=0x42d080 \<xs\_init>\) at perl\.c&#8203;:2273
\#7  0x000000000053324f in perl\_parse \(my\_perl=\<optimized out>\, xsinit=0x42d080 \<xs\_init>\, argc=\<optimized out>\, argv=\<optimized out>\, env=0x0\) at perl\.c&#8203;:1607
\#8  0x000000000042cc8c in main \(argc=0x2\, argv=0x7fffffffe3d8\, env=0x7fffffffe3f0\) at perlmain\.c&#8203;:114
\#9  0x00007ffff6d7bead in \_\_libc\_start\_main \(main=\<optimized out>\, argc=\<optimized out>\, ubp\_av=\<optimized out>\, init=\<optimized out>\, fini=\<optimized out>\, rtld\_fini=\<optimized out>\, stack\_end=0x7fffffffe3c8\) at libc\-start\.c&#8203;:244
\#10 0x000000000042cfa5 in \_start \(\)

Hexdump of the test case&#8203;:
0000000 7270 6e69 0a74 796d 7228 0029          
000000b

**Comment by p5pRT** [comment]
### From @geeknik

[minitc.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1329492/709676/minitc.gz)

**Comment by p5pRT** [comment]
### From @iabyn

On Wed\, Feb 04\, 2015 at 08&#8203;:39&#8203;:48PM \-0800\, Brian Carpenter wrote&#8203;:
> Built v5\.21\.9 \(v5\.21\.8\-200\-ga57d3d4\) using the following command line&#8203;:
> 
> \./Configure \-des \-Dusedevel \-DDEBUGGING \-Dcc=afl\-gcc \-Doptimize=\-O2\\ \-g && AFL\_HARDEN=1 make \-j6 test\-prep
> 
> Bug found with AFL \(http&#8203;://lcamtuf\.coredump\.cx/afl\)
> 
> GDB output&#8203;:
> \[Thread debugging using libthread\_db enabled\]
> Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
> perl&#8203;: op\.c&#8203;:12894&#8203;: Perl\_rpeep&#8203;: Assertion \`\!\(o2\->op\_flags & ~\(3|32|128\)\)' failed\.

Thanks for the report\. Fixed with
20c46147ebf1319e284a39fb6afe6a572f067e47\.

\-\- 
The Enterprise successfully ferries an alien VIP from one place to another
without serious incident\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#7

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@hvds - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thanks for submitting this ticket

The issue should be resolved with the release today of Perl v5\.22\, available at http&#8203;://www\.perl\.org/get\.html
If you find that the problem persists\, feel free to reopen this ticket

\-\- 
Karl Williamson for the Perl 5 porters team

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
