### ISSUE TITLE
Perl_utf16_to_utf8: Assertion `(sizeof((uv)) == 1) || !(((unsigned long)((uv))) & ~0x3FF)' failed (utf8.c:1273)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14471]
Migrated from [rt.perl.org#123736](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=123736) (status was 'resolved')

Searchable as RT123736$

**Comment by p5pRT** [comment]
### From @geeknik

Built v5\.21\.9 \(v5\.21\.8\-200\-ga57d3d4\) using the following command line&#8203;:

\./Configure \-des \-Dusedevel \-DDEBUGGING \-Dcc=afl\-gcc \-Doptimize=\-O2\\ \-g && AFL\_HARDEN=1 make \-j6 test\-prep

Bug found with AFL \(http&#8203;://lcamtuf\.coredump\.cx/afl\)

GDB output&#8203;:
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
perl&#8203;: utf8\.c&#8203;:1273&#8203;: Perl\_utf16\_to\_utf8&#8203;: Assertion \`\(sizeof\(\(uv\)\) == 1\) || \!\(\(\(unsigned long\)\(\(uv\)\)\) & ~0x3FF\)' failed\.

Program received signal SIGABRT\, Aborted\.
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-registers\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
RAX&#8203;: 0x0 
RBX&#8203;: 0x7fffffffe617 \-\-> 0x3a6469006c726570 \('perl'\)
RCX&#8203;: 0xffffffffffffffff 
RDX&#8203;: 0x6 
RSI&#8203;: 0x18b8 
RDI&#8203;: 0x18b8 
RBP&#8203;: 0x7ffff6ea9a07 \-\-> 0x257325732500203a \('&#8203;: '\)
RSP&#8203;: 0x7fffffffd658 \-\-> 0x7ffff6d923e0 \(\<\*\_\_GI\_abort\+384>&#8203;:    mov    rdx\,QWORD PTR fs&#8203;:0x10\)
RIP&#8203;: 0x7ffff6d8f165 \(\<\*\_\_GI\_raise\+53>&#8203;:    cmp    rax\,0xfffffffffffff000\)
R8 : 0x7ffff7fdd700 \(0x00007ffff7fdd700\)
R9 : 0x6f6c2064656e6769 \('igned lo'\)
R10&#8203;: 0x8 
R11&#8203;: 0x206 
R12&#8203;: 0xf2bb08 \("\(sizeof\(\(uv\)\) == 1\) || \!\(\(\(unsigned long\)\(\(uv\)\)\) & ~0x3FF\)"\)
R13&#8203;: 0xf2cae0 \("Perl\_utf16\_to\_utf8"\)
R14&#8203;: 0x7ffff6ea9a07 \-\-> 0x257325732500203a \('&#8203;: '\)
R15&#8203;: 0x4f9
EFLAGS&#8203;: 0x206 \(carry PARITY adjust zero sign trap INTERRUPT direction overflow\)
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-code\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
&nbsp;   0x7ffff6d8f15b \<\*\_\_GI\_raise\+43>&#8203;:    movsxd rdi\,eax
&nbsp;   0x7ffff6d8f15e \<\*\_\_GI\_raise\+46>&#8203;:    mov    eax\,0xea
&nbsp;   0x7ffff6d8f163 \<\*\_\_GI\_raise\+51>&#8203;:    syscall 
=> 0x7ffff6d8f165 \<\*\_\_GI\_raise\+53>&#8203;:    cmp    rax\,0xfffffffffffff000
&nbsp;   0x7ffff6d8f16b \<\*\_\_GI\_raise\+59>&#8203;:    ja     0x7ffff6d8f182 \<\*\_\_GI\_raise\+82>
&nbsp;   0x7ffff6d8f16d \<\*\_\_GI\_raise\+61>&#8203;:    repz ret 
&nbsp;   0x7ffff6d8f16f \<\*\_\_GI\_raise\+63>&#8203;:    nop
&nbsp;   0x7ffff6d8f170 \<\*\_\_GI\_raise\+64>&#8203;:    test   eax\,eax
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-stack\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
0000| 0x7fffffffd658 \-\-> 0x7ffff6d923e0 \(\<\*\_\_GI\_abort\+384>&#8203;:    mov    rdx\,QWORD PTR fs&#8203;:0x10\)
0008| 0x7fffffffd660 \-\-> 0xf2bb08 \("\(sizeof\(\(uv\)\) == 1\) || \!\(\(\(unsigned long\)\(\(uv\)\)\) & ~0x3FF\)"\)
0016| 0x7fffffffd668 \-\-> 0x7ffff6eab9c1 \-\-> 0x706c6568007325 \('%s'\)
0024| 0x7fffffffd670 \-\-> 0x7fffffffd690 \-\-> 0x3000000018 
0032| 0x7fffffffd678 \-\-> 0x4f9 
0040| 0x7fffffffd680 \-\-> 0x7fffffffd780 \-\-> 0x7fffffffe617 \-\-> 0x3a6469006c726570 \('perl'\)
0048| 0x7fffffffd688 \-\-> 0x7ffff6dc3fe6 \(\<\_\_fxprintf\+310>&#8203;:    lea    rsp\,\[rbp\-0x20\]\)
0056| 0x7fffffffd690 \-\-> 0x3000000018 
\[\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\]
Legend&#8203;: code\, data\, rodata\, value
Stopped reason&#8203;: SIGABRT
0x00007ffff6d8f165 in \*\_\_GI\_raise \(sig=\<optimized out>\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:64
64    \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;: No such file or directory\.
gdb\-peda$ bt
\#0  0x00007ffff6d8f165 in \*\_\_GI\_raise \(sig=\<optimized out>\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:64
\#1  0x00007ffff6d923e0 in \*\_\_GI\_abort \(\) at abort\.c&#8203;:92
\#2  0x00007ffff6d88311 in \*\_\_GI\_\_\_assert\_fail \(assertion=assertion@&#8203;entry=0xf2bb08 "\(sizeof\(\(uv\)\) == 1\) || \!\(\(\(unsigned long\)\(\(uv\)\)\) & ~0x3FF\)"\, file=\<optimized out>\, file@&#8203;entry=0xf2af29 "utf8\.c"\, line=line@&#8203;entry=0x4f9\, function=function@&#8203;entry=0xf2cae0 "Perl\_utf16\_to\_utf8"\) at assert\.c&#8203;:81
\#3  0x0000000000cf2c31 in Perl\_utf16\_to\_utf8 \(p=\<optimized out>\, d=\<optimized out>\, bytelen=\<optimized out>\, newlen=\<optimized out>\) at utf8\.c&#8203;:1273
\#4  0x00000000005a049e in S\_utf16\_textfilter \(idx=0x0\, sv=0x117a0d8\, maxlen=\<optimized out>\) at toke\.c&#8203;:10929
\#5  0x00000000004263f4 in S\_add\_utf16\_textfilter \(s=s@&#8203;entry=0x1182122 "\\004"\, reversed=reversed@&#8203;entry=0x0\) at toke\.c&#8203;:10969
\#6  0x0000000000632e7a in S\_swallow\_bom \(s=0x1182122 "\\004"\) at toke\.c&#8203;:10804
\#7  Perl\_yylex \(\) at toke\.c&#8203;:4735
\#8  0x000000000065c275 in Perl\_yyparse \(gramtype=\<optimized out>\) at perly\.c&#8203;:322
\#9  0x000000000052d275 in S\_parse\_body \(env=env@&#8203;entry=0x0\, xsinit=xsinit@&#8203;entry=0x42d080 \<xs\_init>\) at perl\.c&#8203;:2273
\#10 0x000000000053324f in perl\_parse \(my\_perl=\<optimized out>\, xsinit=0x42d080 \<xs\_init>\, argc=\<optimized out>\, argv=\<optimized out>\, env=0x0\) at perl\.c&#8203;:1607
\#11 0x000000000042cc8c in main \(argc=0x2\, argv=0x7fffffffe398\, env=0x7fffffffe3b0\) at perlmain\.c&#8203;:114
\#12 0x00007ffff6d7bead in \_\_libc\_start\_main \(main=\<optimized out>\, argc=\<optimized out>\, ubp\_av=\<optimized out>\, init=\<optimized out>\, fini=\<optimized out>\, rtld\_fini=\<optimized out>\, stack\_end=0x7fffffffe388\) at libc\-start\.c&#8203;:244
\#13 0x000000000042cfa5 in \_start \(\)

Test case hexdump&#8203;:
0000000 fffe 0004                              
0000004

**Comment by p5pRT** [comment]
### From @geeknik

[utf8abort.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1329501/709681/utf8abort.gz)

**Comment by p5pRT** [comment]
### From @hvds

In short&#8203;:

% perl \-e 'print "\\xff\\xfe\\x00\\x04"' | \./miniperl
miniperl&#8203;: utf8\.c&#8203;:1273&#8203;: Perl\_utf16\_to\_utf8&#8203;: Assertion \`\(sizeof\(\(uv\)\) == 1\) || \!\(\(\(unsigned long\)\(\(uv\)\)\) & ~0x3FF\)' failed\.
Aborted \(core dumped\)
% 

The input represents a BOM followed by a UTF16 codepoint 0x400; the same
problem will occur for any UTF16 input with a codepoint in the range
0x400\-0x7ff\. This occurs because in utf16\_to\_utf8\(\) we have&#8203;:

&nbsp;        if \(uv \<= MAX\_UTF8\_TWO\_BYTE\) \{
&nbsp;            \*d\+\+ = UTF8\_TWO\_BYTE\_HI\(UNI\_TO\_NATIVE\(uv\)\);
&nbsp;            \*d\+\+ = UTF8\_TWO\_BYTE\_LO\(UNI\_TO\_NATIVE\(uv\)\);
&nbsp;            continue;
&nbsp;        \}

\.\. but the UTF8\_TWO\_BYTE\_\* macros assert uv \<= MAX\_PORTABLE\_UTF8\_TWO\_BYTE\,
which isn't the same&#8203;:

\#define MAX\_UTF8\_TWO\_BYTE 0x7FF
\#define MAX\_PORTABLE\_UTF8\_TWO\_BYTE 0x3FF    /\* constrained by EBCDIC \*/

Changing the 'if' check to use the same guard&#8203;:

\-\-\- a/utf8\.c
\+\+\+ b/utf8\.c
@&#8203;@&#8203; \-1269\,7 \+1269\,7 @&#8203;@&#8203; Perl\_utf16\_to\_utf8\(pTHX\_ U8\* p\, U8\* d\, I32 bytelen\, I32 \*n
&nbsp;            \*d\+\+ = LATIN1\_TO\_NATIVE\(\(U8\) uv\);
&nbsp;            continue;
&nbsp;        \}
\-       if \(uv \<= MAX\_UTF8\_TWO\_BYTE\) \{
\+       if \(uv \<= MAX\_PORTABLE\_UTF8\_TWO\_BYTE\) \{
&nbsp;            \*d\+\+ = UTF8\_TWO\_BYTE\_HI\(UNI\_TO\_NATIVE\(uv\)\);
&nbsp;            \*d\+\+ = UTF8\_TWO\_BYTE\_LO\(UNI\_TO\_NATIVE\(uv\)\);
&nbsp;            continue;

\.\. doesn't help\, because then we convert 0x400 to utf8 as \\xe0 \\x90 \\x80
rather than \\xD0 \\x80\, which we then complain very noisily about&#8203;:

% perl \-e 'print "\\xff\\xfe\\x00\\x04"' | \./miniperl
Passing malformed UTF\-8 to "\_Perl\_IDStart" is deprecated at \- line 1\.
Malformed UTF\-8 character \(3 bytes\, need 2\, after start byte 0xe0\) at \- line 1\.
Unrecognized character \\x\{0\}; marked by \<\-\- HERE after \<\-\- HERE near column 1 at \- line 1\.
% 

I'm not sure what the way forward is here\, but I guess it also implies we
have limited tests for UTF16\.

Karl\, do you have any ideas?

Hugo

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @khwilliamson

On 02/11/2015 11&#8203;:20 AM\, hv@&#8203;crypt\.org wrote&#8203;:
> In short&#8203;:
>
> % perl \-e 'print "\\xff\\xfe\\x00\\x04"' | \./miniperl
> miniperl&#8203;: utf8\.c&#8203;:1273&#8203;: Perl\_utf16\_to\_utf8&#8203;: Assertion \`\(sizeof\(\(uv\)\) == 1\) || \!\(\(\(unsigned long\)\(\(uv\)\)\) & ~0x3FF\)' failed\.
> Aborted \(core dumped\)
> %
>
> The input represents a BOM followed by a UTF16 codepoint 0x400; the same
> problem will occur for any UTF16 input with a codepoint in the range
> 0x400\-0x7ff\. This occurs because in utf16\_to\_utf8\(\) we have&#8203;:
>
>          if \(uv \<= MAX\_UTF8\_TWO\_BYTE\) \{
>              \*d\+\+ = UTF8\_TWO\_BYTE\_HI\(UNI\_TO\_NATIVE\(uv\)\);
>              \*d\+\+ = UTF8\_TWO\_BYTE\_LO\(UNI\_TO\_NATIVE\(uv\)\);
>              continue;
>          \}
>
> \.\. but the UTF8\_TWO\_BYTE\_\* macros assert uv \<= MAX\_PORTABLE\_UTF8\_TWO\_BYTE\,
> which isn't the same&#8203;:
>
> \#define MAX\_UTF8\_TWO\_BYTE 0x7FF
> \#define MAX\_PORTABLE\_UTF8\_TWO\_BYTE 0x3FF    /\* constrained by EBCDIC \*/
>
> Changing the 'if' check to use the same guard&#8203;:
>
> \-\-\- a/utf8\.c
> \+\+\+ b/utf8\.c
> @&#8203;@&#8203; \-1269\,7 \+1269\,7 @&#8203;@&#8203; Perl\_utf16\_to\_utf8\(pTHX\_ U8\* p\, U8\* d\, I32 bytelen\, I32 \*n
>              \*d\+\+ = LATIN1\_TO\_NATIVE\(\(U8\) uv\);
>              continue;
>          \}
> \-       if \(uv \<= MAX\_UTF8\_TWO\_BYTE\) \{
> \+       if \(uv \<= MAX\_PORTABLE\_UTF8\_TWO\_BYTE\) \{
>              \*d\+\+ = UTF8\_TWO\_BYTE\_HI\(UNI\_TO\_NATIVE\(uv\)\);
>              \*d\+\+ = UTF8\_TWO\_BYTE\_LO\(UNI\_TO\_NATIVE\(uv\)\);
>              continue;
>
> \.\. doesn't help\, because then we convert 0x400 to utf8 as \\xe0 \\x90 \\x80
> rather than \\xD0 \\x80\, which we then complain very noisily about&#8203;:
>
> % perl \-e 'print "\\xff\\xfe\\x00\\x04"' | \./miniperl
> Passing malformed UTF\-8 to "\_Perl\_IDStart" is deprecated at \- line 1\.
> Malformed UTF\-8 character \(3 bytes\, need 2\, after start byte 0xe0\) at \- line 1\.
> Unrecognized character \\x\{0\}; marked by \<\-\- HERE after \<\-\- HERE near column 1 at \- line 1\.
> %
>
> I'm not sure what the way forward is here\, but I guess it also implies we
> have limited tests for UTF16\.
>
> Karl\, do you have any ideas?
>
> Hugo
>

The guard in the macros should drop the PORTABLE\.  That was my attempt 
to keep people \(like myself\) from writing unportable code\.  But it's 
wrong here\, and can be so in general\.

The reason that your change failed is because further down in the code 
it assumes that 'uv' must require more than 2 bytes in UTF\-8\, and just 
processes it as if it does\.  Your change left the things representable 
by 2 bytes on ASCII platforms but not EBCDIC out in the cold\.

It does look like we need more UTF\-16 tests\.

In looking at the code\, I notice some performance sloppiness in the 
surrogate testing\.  The usual case is not to be a surrogate\, but here 
that gets tested twice\, once for being a high surrogate\, and once for 
being a low\.  Fewer branches in the usual case would be done if the test 
were for any surrogate\, and only if it is one\, do we need to figure out 
which type\.  This adds a branch in the abnormal case\.  This is a micro 
optimization\, and I wonder if a n optimizing compiler would be likely to 
realize this\.  Some UNLIKELY\(\)'s might help\.

**Comment by p5pRT** [comment]
### From @hvds

I've now pushed d52b857690&#8203;:
&nbsp;    fix assertions for UTF8\_TWO\_BYTE\_HI/LO
&nbsp;    
&nbsp;    Replace the stricter MAX\_PORTABLE\_UTF8\_TWO\_BYTE check with a looser
&nbsp;    MAX\_UTF8\_TWO\_BYTE check\, else we can't correctly convert codepoints in
&nbsp;    the range 0x400\-0x7ff from utf16 to utf8 on non\-ebcdic platforms\.

There may be fallout on EBCDIC&#8203;: I'll wait to close this ticket until we get some smoke results\.

Hugo

**Comment by p5pRT** [comment]
### From @hvds

For reference&#8203;: here's a rather different test case for the same issue\.

% perl \-e '0=~v91\.1100'
perl&#8203;: regcomp\.c&#8203;:11442&#8203;: S\_alloc\_maybe\_populate\_EXACT&#8203;: Assertion \`\(sizeof\(code\_point\) == 1\) || \!\(\(\(unsigned long\)\(code\_point\)\) & ~0x3FF\)' failed\.
Aborted \(core dumped\)
% 

Hugo

**Comment by p5pRT** [comment]
### From @hvds

On Thu Feb 12 04&#8203;:33&#8203;:52 2015\, hv wrote&#8203;:
> There may be fallout on EBCDIC&#8203;: I'll wait to close this ticket until
> we get some smoke results\.

There were problems for EBCDIC in the new io/bom\.t tests\, but those have now been fixed in Karl's ebcdic branch\, so I think we're done here\.

Hugo

**Comment by p5pRT** [comment]
@hvds - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

On Tue Feb 17 05&#8203;:53&#8203;:08 2015\, hv wrote&#8203;:
> On Thu Feb 12 04&#8203;:33&#8203;:52 2015\, hv wrote&#8203;:
> > There may be fallout on EBCDIC&#8203;: I'll wait to close this ticket until
> > we get some smoke results\.
> 
> There were problems for EBCDIC in the new io/bom\.t tests\, but those
> have now been fixed in Karl's ebcdic branch\, so I think we're done
> here\.
> 
> Hugo

Agreed\, and now pushed to blead as 828350902c4a64aa014ca4a0448c0e2f86d01647
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
### From @khwilliamson

Thanks for submitting this ticket

The issue should be resolved with the release today of Perl v5\.22\, available at http&#8203;://www\.perl\.org/get\.html
If you find that the problem persists\, feel free to reopen this ticket

\-\- 
Karl Williamson for the Perl 5 porters team

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
