### ISSUE TITLE
-Do can't survive main stash clear

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14514]
Migrated from [rt.perl.org#123849](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=123849) (status was 'resolved')

Searchable as RT123849$

**Comment by p5pRT** [comment]
### From @hvds

AFL \(\<http&#8203;://lcamtuf\.coredump\.cx/afl/>\) finds this&#8203;:

% \./miniperl \-Do \-e '%&#8203;:: = \(\)'
\(\-e&#8203;:0\)  sv\_upgrade clearing PL\_stashcache
\(\-e&#8203;:0\)  sv\_upgrade clearing PL\_stashcache
\(\-e&#8203;:0\)  sv\_upgrade clearing PL\_stashcache
\(\-e&#8203;:0\)  sv\_upgrade clearing PL\_stashcache
\(\-e&#8203;:0\)  sv\_upgrade clearing PL\_stashcache
\(\-e&#8203;:2\)  Looking for method DESTROY in package IO&#8203;::File
\(\-e&#8203;:2\)  Looking for method DESTROY in package UNIVERSAL
\(\-e&#8203;:2\)  Looking for method AUTOLOAD in package IO&#8203;::File
\(\-e&#8203;:2\)  Looking for method AUTOLOAD in package UNIVERSAL

EXECUTING\.\.\.

\(\-e&#8203;:1\)  gp\_free clearing PL\_stashcache for 'PerlIO'
\(\-e&#8203;:1\)  miniperl&#8203;: sv\.c&#8203;:2963&#8203;: Perl\_sv\_2pv\_flags&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= SVt\_PVAV && \(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= SVt\_PVHV && \(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= SVt\_PVFM' failed\.
Aborted \(core dumped\)
% 

\(That started off as&#8203;: \-e '%&#8203;::=$^D=o'\.\)

Not sure how much we care about this\, but it might be a symptom of something nastier\.

\(gdb\) where
\#0  0x00007ffff72edbb9 in \_\_GI\_raise \(sig=sig@&#8203;entry=6\)
&nbsp;    at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:56
\#1  0x00007ffff72f0fc8 in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007ffff72e6a76 in \_\_assert\_fail\_base \(
&nbsp;    fmt=0x7ffff7438370 "%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\, 
&nbsp;    assertion=assertion@&#8203;entry=0x7b3148 "\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= SVt\_PVAV && \(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= SVt\_PVHV && \(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= SVt\_PVFM"\, file=file@&#8203;entry=0x7b0814 "sv\.c"\, 
&nbsp;    line=line@&#8203;entry=2963\, 
&nbsp;    function=function@&#8203;entry=0x7ccd80 \<\_\_PRETTY\_FUNCTION\_\_\.15222> "Perl\_sv\_2pv\_flags"\) at assert\.c&#8203;:92
\#3  0x00007ffff72e6b22 in \_\_GI\_\_\_assert\_fail \(
&nbsp;    assertion=0x7b3148 "\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= SVt\_PVAV && \(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= SVt\_PVHV && \(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= SVt\_PVFM"\, file=0x7b0814 "sv\.c"\, line=2963\, 
&nbsp;    function=0x7ccd80 \<\_\_PRETTY\_FUNCTION\_\_\.15222> "Perl\_sv\_2pv\_flags"\)
&nbsp;    at assert\.c&#8203;:101
\#4  0x000000000059da14 in Perl\_sv\_2pv\_flags \(sv=0xa553d0\, lp=0x7fffffffd3a8\, 
&nbsp;    flags=34\) at sv\.c&#8203;:2962
\#5  0x00000000005db25d in Perl\_sv\_vcatpvfn\_flags \(sv=0xa55a00\, 
&nbsp;    pat=0x7c40d0 "sv\_clear clearing PL\_stashcache for '%\-p'\\n"\, patlen=42\, 
&nbsp;    args=0x7fffffffd9d8\, svargs=0x0\, svmax=0\, maybe\_tainted=0x0\, flags=0\)
&nbsp;    at sv\.c&#8203;:11451
\#6  0x00000000005d98a6 in Perl\_sv\_vsetpvfn \(sv=0xa55a00\, 
&nbsp;    pat=0x7c40d0 "sv\_clear clearing PL\_stashcache for '%\-p'\\n"\, patlen=42\, 
&nbsp;    args=0x7fffffffd9d8\, svargs=0x0\, svmax=0\, maybe\_tainted=0x0\) at sv\.c&#8203;:10739
\#7  0x00000000005d16d1 in Perl\_vnewSVpvf \(
&nbsp;    pat=0x7c40d0 "sv\_clear clearing PL\_stashcache for '%\-p'\\n"\, 
&nbsp;    args=0x7fffffffd9d8\) at sv\.c&#8203;:9372
\#8  0x00000000006da6eb in PerlIO\_vprintf \(f=0xa4f390\, 
&nbsp;    fmt=0x7c40d0 "sv\_clear clearing PL\_stashcache for '%\-p'\\n"\, 
&nbsp;    ap=0x7fffffffda88\) at perlio\.c&#8203;:4970
\#9  0x00000000006c5e59 in Perl\_vdeb \(
&nbsp;    pat=0x7c40d0 "sv\_clear clearing PL\_stashcache for '%\-p'\\n"\, 
&nbsp;    args=0x7fffffffda88\) at deb\.c&#8203;:73
\#10 0x00000000006c5aa1 in Perl\_deb \(
&nbsp;    pat=0x7c40d0 "sv\_clear clearing PL\_stashcache for '%\-p'\\n"\) at deb\.c&#8203;:51
\#11 0x00000000005c27fb in Perl\_sv\_clear \(orig\_sv=0xa553d0\) at sv\.c&#8203;:6621
\#12 0x00000000005c54ae in Perl\_sv\_free2 \(sv=0xa553d0\, rc=1\) at sv\.c&#8203;:7028
\#13 0x0000000000450b8a in S\_SvREFCNT\_dec \(sv=0xa553d0\) at inline\.h&#8203;:166
\#14 0x000000000046541c in Perl\_gp\_free \(gv=0xa553b8\) at gv\.c&#8203;:2546
\#15 0x00000000005c3446 in Perl\_sv\_clear \(orig\_sv=0xa553b8\) at sv\.c&#8203;:6680
\#16 0x00000000005c54ae in Perl\_sv\_free2 \(sv=0xa553b8\, rc=1\) at sv\.c&#8203;:7028
\#17 0x00000000005628bd in S\_SvREFCNT\_dec \(sv=0xa553b8\) at inline\.h&#8203;:166
\#18 0x00000000005673b7 in S\_hfreeentries \(hv=0xa41fb0\) at hv\.c&#8203;:1742
\#19 0x0000000000566de5 in Perl\_hv\_clear \(hv=0xa41fb0\) at hv\.c&#8203;:1642
\#20 0x000000000057b6a1 in Perl\_pp\_aassign \(\) at pp\_hot\.c&#8203;:1146
\#21 0x000000000052a13d in Perl\_runops\_debug \(\) at dump\.c&#8203;:2231
\#22 0x00000000004098c7 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2423
\#23 0x0000000000408f0b in perl\_run \(my\_perl=0xa40010\) at perl\.c&#8203;:2346
\#24 0x00000000004508d1 in main \(argc=4\, argv=0x7fffffffe638\, 
&nbsp;    env=0x7fffffffe660\) at miniperlmain\.c&#8203;:122

Hugo

**Comment by p5pRT** [comment]
### From @cpansprout

On Mon Feb 16 09&#8203;:03&#8203;:55 2015\, hv wrote&#8203;:
> AFL \(\<http&#8203;://lcamtuf\.coredump\.cx/afl/>\) finds this&#8203;:
> 
> % \./miniperl \-Do \-e '%&#8203;:: = \(\)'
> \(\-e&#8203;:0\)  sv\_upgrade clearing PL\_stashcache
> \(\-e&#8203;:0\)  sv\_upgrade clearing PL\_stashcache
> \(\-e&#8203;:0\)  sv\_upgrade clearing PL\_stashcache
> \(\-e&#8203;:0\)  sv\_upgrade clearing PL\_stashcache
> \(\-e&#8203;:0\)  sv\_upgrade clearing PL\_stashcache
> \(\-e&#8203;:2\)  Looking for method DESTROY in package IO&#8203;::File
> \(\-e&#8203;:2\)  Looking for method DESTROY in package UNIVERSAL
> \(\-e&#8203;:2\)  Looking for method AUTOLOAD in package IO&#8203;::File
> \(\-e&#8203;:2\)  Looking for method AUTOLOAD in package UNIVERSAL
> 
> EXECUTING\.\.\.
> 
> \(\-e&#8203;:1\)  gp\_free clearing PL\_stashcache for 'PerlIO'
> \(\-e&#8203;:1\)  miniperl&#8203;: sv\.c&#8203;:2963&#8203;: Perl\_sv\_2pv\_flags&#8203;: Assertion
> \`\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= SVt\_PVAV && \(\(svtype\)\(\(sv\)\-
> >sv\_flags & 0xff\)\) \!= SVt\_PVHV && \(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!=
> SVt\_PVFM' failed\.
> Aborted \(core dumped\)
>  %
> 
> \(That started off as&#8203;: \-e '%&#8203;::=$^D=o'\.\)
> 
> Not sure how much we care about this\, but it might be a symptom of
> something nastier\.

This bisects to&#8203;:

103f5a36127499843005aa988becbcdca21384af is the first bad commit
commit 103f5a36127499843005aa988becbcdca21384af
Author&#8203;: Nicholas Clark \<nick@&#8203;ccl4\.org>
Date&#8203;:   Sun Sep 23 22&#8203;:05&#8203;:16 2012 \+0200

&nbsp;    \-Do now also reports updates and use of PL\_stashcache\.

which may not be so surprising\.

But this code in sv\_clear looks very suspicious&#8203;:

&nbsp;                    DEBUG\_o\(Perl\_deb\(aTHX\_ "sv\_clear clearing PL\_stashcache for '%"SVf"'\\n"\,
&nbsp;                                     SVfARG\(sv\)\)\);

Just before that we put the name of the stash in the ‘name’ variable\, but never use it\.  I think this is a typo\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Sun Mar 01 14&#8203;:22&#8203;:57 2015\, sprout wrote&#8203;:
> On Mon Feb 16 09&#8203;:03&#8203;:55 2015\, hv wrote&#8203;:
> > AFL \(\<http&#8203;://lcamtuf\.coredump\.cx/afl/>\) finds this&#8203;:
> >
> > % \./miniperl \-Do \-e '%&#8203;:: = \(\)'
> > \(\-e&#8203;:0\)  sv\_upgrade clearing PL\_stashcache
> > \(\-e&#8203;:0\)  sv\_upgrade clearing PL\_stashcache
> > \(\-e&#8203;:0\)  sv\_upgrade clearing PL\_stashcache
> > \(\-e&#8203;:0\)  sv\_upgrade clearing PL\_stashcache
> > \(\-e&#8203;:0\)  sv\_upgrade clearing PL\_stashcache
> > \(\-e&#8203;:2\)  Looking for method DESTROY in package IO&#8203;::File
> > \(\-e&#8203;:2\)  Looking for method DESTROY in package UNIVERSAL
> > \(\-e&#8203;:2\)  Looking for method AUTOLOAD in package IO&#8203;::File
> > \(\-e&#8203;:2\)  Looking for method AUTOLOAD in package UNIVERSAL
> >
> > EXECUTING\.\.\.
> >
> > \(\-e&#8203;:1\)  gp\_free clearing PL\_stashcache for 'PerlIO'
> > \(\-e&#8203;:1\)  miniperl&#8203;: sv\.c&#8203;:2963&#8203;: Perl\_sv\_2pv\_flags&#8203;: Assertion
> > \`\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= SVt\_PVAV && \(\(svtype\)\(\(sv\)\-
> > > sv\_flags & 0xff\)\) \!= SVt\_PVHV && \(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\)
> > > \!=
> > SVt\_PVFM' failed\.
> > Aborted \(core dumped\)
> >  %
> >
> > \(That started off as&#8203;: \-e '%&#8203;::=$^D=o'\.\)
> >
> > Not sure how much we care about this\, but it might be a symptom of
> > something nastier\.
> 
> This bisects to&#8203;:
> 
> 103f5a36127499843005aa988becbcdca21384af is the first bad commit
> commit 103f5a36127499843005aa988becbcdca21384af
> Author&#8203;: Nicholas Clark \<nick@&#8203;ccl4\.org>
> Date&#8203;:   Sun Sep 23 22&#8203;:05&#8203;:16 2012 \+0200
> 
> \-Do now also reports updates and use of PL\_stashcache\.
> 
> which may not be so surprising\.
> 
> But this code in sv\_clear looks very suspicious&#8203;:
> 
> DEBUG\_o\(Perl\_deb\(aTHX\_ "sv\_clear clearing PL\_stashcache for
> '%"SVf"'\\n"\,
>                  SVfARG\(sv\)\)\);
> 
> Just before that we put the name of the stash in the ‘name’ variable\,
> but never use it\.  I think this is a typo\.

Fixed in 813d2eb17\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for submitting this ticket\.

The issue should now be resolved with the release today of Perl v5\.22\, which is available at http&#8203;://www\.perl\.org/get\.html
\-\- 
Karl Williamson for the Perl 5 team

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
