### ISSUE TITLE
SEGV reading through null HEK* in hv_ename_add

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14512]
Migrated from [rt.perl.org#123847](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=123847) (status was 'resolved')

Searchable as RT123847$

**Comment by p5pRT** [comment]
### From @hvds

AFL \(\<http&#8203;://lcamtuf\.coredump\.cx/afl/>\) finds this&#8203;:

% \./miniperl \-e '%0=\*&#8203;:=\*&#8203;::&#8203;::=0'
Segmentation fault \(core dumped\)
% 

The code looks similar to the glob overwriting cases in \[perl \#123710\]\, but the failure mode is quite different&#8203;:

Program received signal SIGSEGV\, Segmentation fault\.
0x000000000056afbc in Perl\_hv\_ename\_add \(hv=0xa56108\, name=0xa62460 "&#8203;:"\, 
&nbsp;    len=1\, flags=0\) at hv\.c&#8203;:2342
2342                     \(HEK\_UTF8\(\*hekp\) || \(flags & SVf\_UTF8\)\) 
\(gdb\) where
\#0  0x000000000056afbc in Perl\_hv\_ename\_add \(hv=0xa56108\, name=0xa62460 "&#8203;:"\, 
&nbsp;    len=1\, flags=0\) at hv\.c&#8203;:2342
\#1  0x000000000055a651 in S\_mro\_gather\_and\_rename \(stashes=0xa557c0\, 
&nbsp;    seen\_stashes=0xa55790\, stash=0xa56108\, oldstash=0x0\, namesv=0xa61400\)
&nbsp;    at mro\.c&#8203;:992
\#2  0x000000000055953b in Perl\_mro\_package\_moved \(stash=0xa56108\, 
&nbsp;    oldstash=0x0\, gv=0xa613e8\, flags=0\) at mro\.c&#8203;:844
\#3  0x00000000005a9e33 in S\_glob\_assign\_glob \(dstr=0xa613e8\, sstr=0xa61418\, 
&nbsp;    dtype=9\) at sv\.c&#8203;:4005
\#4  0x00000000005afa88 in Perl\_sv\_setsv\_flags \(dstr=0xa613e8\, sstr=0xa61418\, 
&nbsp;    flags=1538\) at sv\.c&#8203;:4426
\#5  0x0000000000574add in Perl\_pp\_sassign \(\) at pp\_hot\.c&#8203;:231
\#6  0x000000000052a13d in Perl\_runops\_debug \(\) at dump\.c&#8203;:2231
\#7  0x00000000004098c7 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2423
\#8  0x0000000000408f0b in perl\_run \(my\_perl=0xa40010\) at perl\.c&#8203;:2346
\#9  0x00000000004508d1 in main \(argc=3\, argv=0x7fffffffe638\, 
&nbsp;    env=0x7fffffffe658\) at miniperlmain\.c&#8203;:122
\(gdb\) p hekp
$1 = \(HEK \*\*\) 0xa5f820
\(gdb\) p \*hekp
$2 = \(HEK \*\) 0x0
\(gdb\) p /x \*hv
$3 = \{sv\_any = 0xa47ec0\, sv\_refcnt = 0x1\, sv\_flags = 0x3200000c\, sv\_u = \{
&nbsp;    svu\_pv = 0xa59150\, svu\_iv = 0xa59150\, svu\_uv = 0xa59150\, svu\_nv = 0x0\, 
&nbsp;    svu\_rv = 0xa59150\, svu\_rx = 0xa59150\, svu\_array = 0xa59150\, 
&nbsp;    svu\_hash = 0xa59150\, svu\_gp = 0xa59150\, svu\_fp = 0xa59150\}\}
\(gdb\) p \*aux
$4 = \{xhv\_name\_u = \{xhvnameu\_name = 0xa5f820\, xhvnameu\_names = 0xa5f820\}\, 
&nbsp;  xhv\_backreferences = 0x0\, xhv\_eiter = 0x0\, xhv\_riter = \-1\, 
&nbsp;  xhv\_name\_count = \-2\, xhv\_mro\_meta = 0xa5f4e0\, xhv\_rand = 1738015991\, 
&nbsp;  xhv\_last\_rand = 1738015991\, xhv\_fill\_lazy = 0\, xhv\_aux\_flags = 0\}
\(gdb\) p aux\->xhv\_name\_u\.xhvnameu\_names\[0\]@&#8203;2
$5 = \{0x0\, 0xa4d368\}

Not sure what's supposed to be happening here \- the else branch \(when not aux\->xhv\_name\_count\) clearly knows when it stores existing\_name to xhvnameu\_names\[0\] that it might be NULL\, that's why our name\_count is \-2\, so how can it be right to loop as far as xhvnameu\_names\[0\] in the if branch?

Hugo

**Comment by p5pRT** [comment]
### From @cpansprout

On Mon Feb 16 04&#8203;:37&#8203;:51 2015\, hv wrote&#8203;:
> AFL \(\<http&#8203;://lcamtuf\.coredump\.cx/afl/>\) finds this&#8203;:
> 
> % \./miniperl \-e '%0=\*&#8203;:=\*&#8203;::&#8203;::=0'
> Segmentation fault \(core dumped\)
>  %
> 
> The code looks similar to the glob overwriting cases in \[perl
> \#123710\]\, but the failure mode is quite different&#8203;:
> 
> Program received signal SIGSEGV\, Segmentation fault\.
>  0x000000000056afbc in Perl\_hv\_ename\_add \(hv=0xa56108\, name=0xa62460
> "&#8203;:"\,
>     len=1\, flags=0\) at hv\.c&#8203;:2342
>  2342                     \(HEK\_UTF8\(\*hekp\) || \(flags & SVf\_UTF8\)\)
> \(gdb\) where
>  \#0  0x000000000056afbc in Perl\_hv\_ename\_add \(hv=0xa56108\,
> name=0xa62460 "&#8203;:"\,
>     len=1\, flags=0\) at hv\.c&#8203;:2342
>  \#1  0x000000000055a651 in S\_mro\_gather\_and\_rename \(stashes=0xa557c0\,
>     seen\_stashes=0xa55790\, stash=0xa56108\, oldstash=0x0\,
> namesv=0xa61400\)
>     at mro\.c&#8203;:992
>  \#2  0x000000000055953b in Perl\_mro\_package\_moved \(stash=0xa56108\,
>     oldstash=0x0\, gv=0xa613e8\, flags=0\) at mro\.c&#8203;:844
>  \#3  0x00000000005a9e33 in S\_glob\_assign\_glob \(dstr=0xa613e8\,
> sstr=0xa61418\,
>     dtype=9\) at sv\.c&#8203;:4005
>  \#4  0x00000000005afa88 in Perl\_sv\_setsv\_flags \(dstr=0xa613e8\,
> sstr=0xa61418\,
>     flags=1538\) at sv\.c&#8203;:4426
> \#5  0x0000000000574add in Perl\_pp\_sassign \(\) at pp\_hot\.c&#8203;:231
> \#6  0x000000000052a13d in Perl\_runops\_debug \(\) at dump\.c&#8203;:2231
> \#7  0x00000000004098c7 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2423
> \#8  0x0000000000408f0b in perl\_run \(my\_perl=0xa40010\) at perl\.c&#8203;:2346
>  \#9  0x00000000004508d1 in main \(argc=3\, argv=0x7fffffffe638\,
>     env=0x7fffffffe658\) at miniperlmain\.c&#8203;:122
> \(gdb\) p hekp
> $1 = \(HEK \*\*\) 0xa5f820
> \(gdb\) p \*hekp
> $2 = \(HEK \*\) 0x0
> \(gdb\) p /x \*hv
> $3 = \{sv\_any = 0xa47ec0\, sv\_refcnt = 0x1\, sv\_flags = 0x3200000c\, sv\_u
> = \{
>      svu\_pv = 0xa59150\, svu\_iv = 0xa59150\, svu\_uv = 0xa59150\, svu\_nv =
> 0x0\,
>      svu\_rv = 0xa59150\, svu\_rx = 0xa59150\, svu\_array = 0xa59150\,
>     svu\_hash = 0xa59150\, svu\_gp = 0xa59150\, svu\_fp = 0xa59150\}\}
> \(gdb\) p \*aux
>  $4 = \{xhv\_name\_u = \{xhvnameu\_name = 0xa5f820\, xhvnameu\_names =
> 0xa5f820\}\,
>    xhv\_backreferences = 0x0\, xhv\_eiter = 0x0\, xhv\_riter = \-1\,
>    xhv\_name\_count = \-2\, xhv\_mro\_meta = 0xa5f4e0\, xhv\_rand =
> 1738015991\,
>   xhv\_last\_rand = 1738015991\, xhv\_fill\_lazy = 0\, xhv\_aux\_flags = 0\}
> \(gdb\) p aux\->xhv\_name\_u\.xhvnameu\_names\[0\]@&#8203;2
> $5 = \{0x0\, 0xa4d368\}
> 
> Not sure what's supposed to be happening here \- the else branch \(when
> not aux\->xhv\_name\_count\) clearly knows when it stores existing\_name to
> xhvnameu\_names\[0\] that it might be NULL\, that's why our name\_count is
> \-2\, so how can it be right to loop as far as xhvnameu\_names\[0\] in the
> if branch?

Bisect&#8203;:

1f656fcf060e343780f7a91a2ce567e8a9de9414 is the first bad commit
commit 1f656fcf060e343780f7a91a2ce567e8a9de9414
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Fri Apr 15 22&#8203;:33&#8203;:31 2011 \-0700

&nbsp;    Followup to 088225f/\[perl \#88132\]&#8203;: packages ending with :

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Mon Mar 02 22&#8203;:09&#8203;:39 2015\, sprout wrote&#8203;:
> On Mon Feb 16 04&#8203;:37&#8203;:51 2015\, hv wrote&#8203;:
> > AFL \(\<http&#8203;://lcamtuf\.coredump\.cx/afl/>\) finds this&#8203;:
> > 
> > % \./miniperl \-e '%0=\*&#8203;:=\*&#8203;::&#8203;::=0'
> > Segmentation fault \(core dumped\)
> >  %
> > 
> > The code looks similar to the glob overwriting cases in \[perl
> > \#123710\]\, but the failure mode is quite different&#8203;:
> > 
> > Program received signal SIGSEGV\, Segmentation fault\.
> >  0x000000000056afbc in Perl\_hv\_ename\_add \(hv=0xa56108\, name=0xa62460
> > "&#8203;:"\,
> >     len=1\, flags=0\) at hv\.c&#8203;:2342
> >  2342                     \(HEK\_UTF8\(\*hekp\) || \(flags & SVf\_UTF8\)\)
> > \(gdb\) where
> >  \#0  0x000000000056afbc in Perl\_hv\_ename\_add \(hv=0xa56108\,
> > name=0xa62460 "&#8203;:"\,
> >     len=1\, flags=0\) at hv\.c&#8203;:2342
> >  \#1  0x000000000055a651 in S\_mro\_gather\_and\_rename \(stashes=0xa557c0\,
> >     seen\_stashes=0xa55790\, stash=0xa56108\, oldstash=0x0\,
> > namesv=0xa61400\)
> >     at mro\.c&#8203;:992
> >  \#2  0x000000000055953b in Perl\_mro\_package\_moved \(stash=0xa56108\,
> >     oldstash=0x0\, gv=0xa613e8\, flags=0\) at mro\.c&#8203;:844
> >  \#3  0x00000000005a9e33 in S\_glob\_assign\_glob \(dstr=0xa613e8\,
> > sstr=0xa61418\,
> >     dtype=9\) at sv\.c&#8203;:4005
> >  \#4  0x00000000005afa88 in Perl\_sv\_setsv\_flags \(dstr=0xa613e8\,
> > sstr=0xa61418\,
> >     flags=1538\) at sv\.c&#8203;:4426
> > \#5  0x0000000000574add in Perl\_pp\_sassign \(\) at pp\_hot\.c&#8203;:231
> > \#6  0x000000000052a13d in Perl\_runops\_debug \(\) at dump\.c&#8203;:2231
> > \#7  0x00000000004098c7 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2423
> > \#8  0x0000000000408f0b in perl\_run \(my\_perl=0xa40010\) at perl\.c&#8203;:2346
> >  \#9  0x00000000004508d1 in main \(argc=3\, argv=0x7fffffffe638\,
> >     env=0x7fffffffe658\) at miniperlmain\.c&#8203;:122
> > \(gdb\) p hekp
> > $1 = \(HEK \*\*\) 0xa5f820
> > \(gdb\) p \*hekp
> > $2 = \(HEK \*\) 0x0
> > \(gdb\) p /x \*hv
> > $3 = \{sv\_any = 0xa47ec0\, sv\_refcnt = 0x1\, sv\_flags = 0x3200000c\, sv\_u
> > = \{
> >      svu\_pv = 0xa59150\, svu\_iv = 0xa59150\, svu\_uv = 0xa59150\, svu\_nv =
> > 0x0\,
> >      svu\_rv = 0xa59150\, svu\_rx = 0xa59150\, svu\_array = 0xa59150\,
> >     svu\_hash = 0xa59150\, svu\_gp = 0xa59150\, svu\_fp = 0xa59150\}\}
> > \(gdb\) p \*aux
> >  $4 = \{xhv\_name\_u = \{xhvnameu\_name = 0xa5f820\, xhvnameu\_names =
> > 0xa5f820\}\,
> >    xhv\_backreferences = 0x0\, xhv\_eiter = 0x0\, xhv\_riter = \-1\,
> >    xhv\_name\_count = \-2\, xhv\_mro\_meta = 0xa5f4e0\, xhv\_rand =
> > 1738015991\,
> >   xhv\_last\_rand = 1738015991\, xhv\_fill\_lazy = 0\, xhv\_aux\_flags = 0\}
> > \(gdb\) p aux\->xhv\_name\_u\.xhvnameu\_names\[0\]@&#8203;2
> > $5 = \{0x0\, 0xa4d368\}
> > 
> > Not sure what's supposed to be happening here \- the else branch \(when
> > not aux\->xhv\_name\_count\) clearly knows when it stores existing\_name to
> > xhvnameu\_names\[0\] that it might be NULL\, that's why our name\_count is
> > \-2\, so how can it be right to loop as far as xhvnameu\_names\[0\] in the
> > if branch?
> 
> Bisect&#8203;:
> 
> 1f656fcf060e343780f7a91a2ce567e8a9de9414 is the first bad commit
> commit 1f656fcf060e343780f7a91a2ce567e8a9de9414
> Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
> Date&#8203;:   Fri Apr 15 22&#8203;:33&#8203;:31 2011 \-0700
> 
>     Followup to 088225f/\[perl \#88132\]&#8203;: packages ending with :

Here is a clearer example\, which goes back to 5\.14&#8203;:

$ \./miniperl \-e '%0; \*bar&#8203;::=\*foo&#8203;::=0'

The %0 hash needs to be vivified beforehand\, and the two globs assigned to need to be stash globs \(fq names ending in :&#8203;:\)\.

The logic in hv\_ename\_add is wrong\, and probably has been so since I wrote it\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @cpansprout

Fixed in 3d50185\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for submitting this ticket\.

The issue should now be resolved with the release today of Perl v5\.22\, which is available at http&#8203;://www\.perl\.org/get\.html
\-\- 
Karl Williamson for the Perl 5 team

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
