### ISSUE TITLE
\C yields check_locale_boundary_crossing assertion failure

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14520]
Migrated from [rt.perl.org#123861](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=123861) (status was 'resolved')

Searchable as RT123861$

**Comment by p5pRT** [comment]
### From @hvds

AFL \(\<http&#8203;://lcamtuf\.coredump\.cx/afl/>\) finds this&#8203;:

% \./perl \-Ilib \-e '"\\700" =~ /\\C0/il'
\\C is deprecated in regex; marked by \<\-\- HERE in m/\\C \<\-\- HERE 0/ at \-e line 1\.
perl&#8203;: utf8\.c&#8203;:1884&#8203;: S\_check\_locale\_boundary\_crossing&#8203;: Assertion \`\(\(U8\)\(\*p\) >= 0xc4\)' failed\.
Aborted \(core dumped\)
% 

I guess this is the sort of reason why \\C was deprecated in the first place\, but I wonder if we could be doing a better job to detect this and either disallow it earlier or in some other way survive better\.

Hugo

**Comment by p5pRT** [comment]
### From @hvds

Here's a variant that triggers a different assert&#8203;:

% \./perl \-Ilib \-e '"0\\7000"=~m\{\\C\+?0\}'
\\C is deprecated in regex; marked by \<\-\- HERE in m/\\C \<\-\- HERE \+?0/ at \-e line 1\.
perl&#8203;: regexec\.c&#8203;:6606&#8203;: S\_regmatch&#8203;: Assertion \`n == \(32767\) || locinput == li' failed\.
Aborted \(core dumped\)
% 

Hugo

**Comment by p5pRT** [comment]
### From @cpansprout

On Tue Feb 17 18&#8203;:22&#8203;:58 2015\, hv wrote&#8203;:
> Here's a variant that triggers a different assert&#8203;:
> 
> % \./perl \-Ilib \-e '"0\\7000"=~m\{\\C\+?0\}'
> \\C is deprecated in regex; marked by \<\-\- HERE in m/\\C \<\-\- HERE \+?0/ at
> \-e line 1\.
> perl&#8203;: regexec\.c&#8203;:6606&#8203;: S\_regmatch&#8203;: Assertion \`n == \(32767\) || locinput
> == li' failed\.
> Aborted \(core dumped\)
>  %

I have a debugging 5\.14\.4 installed\, and it doesn’t fail the assertion\.  When was this bug introduced?

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @hvds

On Sun Feb 22 11&#8203;:20&#8203;:18 2015\, sprout wrote&#8203;:
> On Tue Feb 17 18&#8203;:22&#8203;:58 2015\, hv wrote&#8203;:
> > Here's a variant that triggers a different assert&#8203;:
> >
> > % \./perl \-Ilib \-e '"0\\7000"=~m\{\\C\+?0\}'
> > \\C is deprecated in regex; marked by \<\-\- HERE in m/\\C \<\-\- HERE \+?0/
> > at
> > \-e line 1\.
> > perl&#8203;: regexec\.c&#8203;:6606&#8203;: S\_regmatch&#8203;: Assertion \`n == \(32767\) || locinput
> > == li' failed\.
> > Aborted \(core dumped\)
> >  %
> 
> I have a debugging 5\.14\.4 installed\, and it doesn’t fail the
> assertion\.  When was this bug introduced?

The first case \(/\\C0/il\) bisects to quite recently&#8203;:

commit 1d39b2cd2a278ed0630f07bd7598726910eb6427
Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
Date&#8203;:   Fri Dec 26 18&#8203;:31&#8203;:04 2014 \-0700

&nbsp;    Simplify foldEQ\_utf8
&nbsp;    
&nbsp;    This moves the uncommon case of handling inputs under non\-UTF\-8 locales
&nbsp;    out of this function to the functions it calls\, which already have the
&nbsp;    logic to handle it\.  This simplifies this function\, cutting a couple
&nbsp;    branches each time through the loop from the common usage\.
&nbsp;    
&nbsp;    The locale handling is slowed down somewhat\, but even if that were a
&nbsp;    concern\, another simpler function is normally used for locale handling\.
&nbsp;    This gets called only when one or both of the comparison strings is
&nbsp;    UTF\-8\, which should be comparatively rare for non\-UTF8 locales\.

The second case was in 5\.18&#8203;:

commit eb72505db041952a73ba9a9f4714951706fda0c3
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Thu Sep 13 19&#8203;:58&#8203;:25 2012 \+0100

&nbsp;    regmatch\(\)&#8203;: remove reginput from CURLY etc
&nbsp;    
&nbsp;    reginput mostly tracked locinput\, except when regrepeat\(\) was called\.
&nbsp;    With a bit of jiggling\, it could be eliminated for these blocks of code\.
&nbsp;    
&nbsp;    This is part of a campaign to eliminate the reginput variable\.

Hugo

**Comment by p5pRT** [comment]
### From @khwilliamson

On 02/22/2015 06&#8203;:59 PM\, Hugo van der Sanden via RT wrote&#8203;:
> On Sun Feb 22 11&#8203;:20&#8203;:18 2015\, sprout wrote&#8203;:
>> On Tue Feb 17 18&#8203;:22&#8203;:58 2015\, hv wrote&#8203;:
>>> Here's a variant that triggers a different assert&#8203;:
>>>
>>> % \./perl \-Ilib \-e '"0\\7000"=~m\{\\C\+?0\}'
>>> \\C is deprecated in regex; marked by \<\-\- HERE in m/\\C \<\-\- HERE \+?0/
>>> at
>>> \-e line 1\.
>>> perl&#8203;: regexec\.c&#8203;:6606&#8203;: S\_regmatch&#8203;: Assertion \`n == \(32767\) || locinput
>>> == li' failed\.
>>> Aborted \(core dumped\)
>>>   %
>>
>> I have a debugging 5\.14\.4 installed\, and it doesn’t fail the
>> assertion\.  When was this bug introduced?
>
> The first case \(/\\C0/il\) bisects to quite recently&#8203;:
>
> commit 1d39b2cd2a278ed0630f07bd7598726910eb6427
> Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
> Date&#8203;:   Fri Dec 26 18&#8203;:31&#8203;:04 2014 \-0700
>
>      Simplify foldEQ\_utf8
>
>      This moves the uncommon case of handling inputs under non\-UTF\-8 locales
>      out of this function to the functions it calls\, which already have the
>      logic to handle it\.  This simplifies this function\, cutting a couple
>      branches each time through the loop from the common usage\.
>
>      The locale handling is slowed down somewhat\, but even if that were a
>      concern\, another simpler function is normally used for locale handling\.
>      This gets called only when one or both of the comparison strings is
>      UTF\-8\, which should be comparatively rare for non\-UTF8 locales\.

This bisect doesn't really mean anything\.  Things were added that didn't 
need this assert before\.

I'm having trouble reproducing it\.  What locale is in effect?
>
> The second case was in 5\.18&#8203;:
>
> commit eb72505db041952a73ba9a9f4714951706fda0c3
> Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
> Date&#8203;:   Thu Sep 13 19&#8203;:58&#8203;:25 2012 \+0100
>
>      regmatch\(\)&#8203;: remove reginput from CURLY etc
>
>      reginput mostly tracked locinput\, except when regrepeat\(\) was called\.
>      With a bit of jiggling\, it could be eliminated for these blocks of code\.
>
>      This is part of a campaign to eliminate the reginput variable\.
>
> Hugo
>
> \-\-\-
> via perlbug&#8203;:  queue&#8203;: perl5 status&#8203;: open
> https://rt-archive.perl.org/perl5/Ticket/Display.html?id=123861
>


I don't know what to do here\.  It would be a lot of work to adequately 
support \\C\, a deprecated feature that we want to get rid of yesterday\, 
and no one should want to pour effort into\.  One thing that comes to 
mind would be to set a flag during regex execution when \\C matches a 
partial UTF\-8 character\, and then add code that tests that flag\, and 
says to other code that you had better be extra careful\.  But this is a 
lot of \(wasted\) work\.

**Comment by p5pRT** [comment]
### From @hvds

On Sat Feb 28 20&#8203;:43&#8203;:06 2015\, public@&#8203;khwilliamson\.com wrote&#8203;:
> On 02/22/2015 06&#8203;:59 PM\, Hugo van der Sanden via RT wrote&#8203;:
> > On Sun Feb 22 11&#8203;:20&#8203;:18 2015\, sprout wrote&#8203;:
> >> On Tue Feb 17 18&#8203;:22&#8203;:58 2015\, hv wrote&#8203;:
> >>> Here's a variant that triggers a different assert&#8203;:
> >>>
> >>> % \./perl \-Ilib \-e '"0\\7000"=~m\{\\C\+?0\}'
> >>> \\C is deprecated in regex; marked by \<\-\- HERE in m/\\C \<\-\- HERE \+?0/
> >>> at
> >>> \-e line 1\.
> >>> perl&#8203;: regexec\.c&#8203;:6606&#8203;: S\_regmatch&#8203;: Assertion \`n == \(32767\) ||
> >>> locinput
> >>> == li' failed\.
> >>> Aborted \(core dumped\)
> >>>   %
> >>
> >> I have a debugging 5\.14\.4 installed\, and it doesn’t fail the
> >> assertion\.  When was this bug introduced?
> >
> > The first case \(/\\C0/il\) bisects to quite recently&#8203;:
> >
> > commit 1d39b2cd2a278ed0630f07bd7598726910eb6427
> > Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
> > Date&#8203;:   Fri Dec 26 18&#8203;:31&#8203;:04 2014 \-0700
> >
> > Simplify foldEQ\_utf8
> >
> > This moves the uncommon case of handling inputs under non\-UTF\-8
> > locales
> > out of this function to the functions it calls\, which already have
> > the
> > logic to handle it\.  This simplifies this function\, cutting a couple
> > branches each time through the loop from the common usage\.
> >
> > The locale handling is slowed down somewhat\, but even if that were a
> > concern\, another simpler function is normally used for locale
> > handling\.
> > This gets called only when one or both of the comparison strings is
> > UTF\-8\, which should be comparatively rare for non\-UTF8 locales\.
> 
> This bisect doesn't really mean anything\.  Things were added that
> didn't
> need this assert before\.
> 
> I'm having trouble reproducing it\.  What locale is in effect?

C locale&#8203;:

% LC\_ALL=C \./perl \-Ilib \-e '"\\700" =~ /\\C0/il'
\\C is deprecated in regex; marked by \<\-\- HERE in m/\\C \<\-\- HERE 0/ at \-e line 1\.
perl&#8203;: utf8\.c&#8203;:1890&#8203;: S\_check\_locale\_boundary\_crossing&#8203;: Assertion \`\(\(U8\)\(\*p\) >= 0xc4\)' failed\.
Aborted \(core dumped\)
% 

In utf8\.c&#8203;:Perl\_\_to\_utf8\_fold\_flags\, it's assumed we're at the start of a well\-formed character; in this case\, however\, we're calling it with p pointing at the second octet of \[\\xc7 \\x80\]\, so we fail the tests UTF8\_IS\_INVARIANT\(\*p\) and UTF8\_IS\_DOWNGRADEABLE\_START\(\*p\) and fall through to&#8203;:
&nbsp;    else \{  /\* utf8\, ord above 255 \*/

Here's the full stack trace&#8203;:

perl&#8203;: utf8\.c&#8203;:1890&#8203;: S\_check\_locale\_boundary\_crossing&#8203;: Assertion \`\(\(U8\)\(\*p\) >= 0xc4\)' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff70e9bb9 in \_\_GI\_raise \(sig=sig@&#8203;entry=6\)
&nbsp;    at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:56
56      \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;: No such file or directory\.
\(gdb\) where
\#0  0x00007ffff70e9bb9 in \_\_GI\_raise \(sig=sig@&#8203;entry=6\)
&nbsp;    at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:56
\#1  0x00007ffff70ecfc8 in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007ffff70e2a76 in \_\_assert\_fail\_base \(
&nbsp;    fmt=0x7ffff7234370 "%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\, 
&nbsp;    assertion=assertion@&#8203;entry=0x80c65e "\(\(U8\)\(\*p\) >= 0xc4\)"\, 
&nbsp;    file=file@&#8203;entry=0x80bf15 "utf8\.c"\, line=line@&#8203;entry=1890\, 
&nbsp;    function=function@&#8203;entry=0x80dd20 \<\_\_PRETTY\_FUNCTION\_\_\.14465> "S\_check\_locale\_boundary\_crossing"\) at assert\.c&#8203;:92
\#3  0x00007ffff70e2b22 in \_\_GI\_\_\_assert\_fail \(
&nbsp;    assertion=0x80c65e "\(\(U8\)\(\*p\) >= 0xc4\)"\, file=0x80bf15 "utf8\.c"\, 
&nbsp;    line=1890\, 
&nbsp;    function=0x80dd20 \<\_\_PRETTY\_FUNCTION\_\_\.14465> "S\_check\_locale\_boundary\_crossing"\) at assert\.c&#8203;:101
\#4  0x00000000006d7499 in S\_check\_locale\_boundary\_crossing \(p=0xa64751 "\\200"\, 
&nbsp;    result=128\, ustrp=0x7fffffffd510 "\\200\\325\\377\\377\\377\\177"\, 
&nbsp;    lenp=0x7fffffffd4b8\) at utf8\.c&#8203;:1890
\#5  0x00000000006d828f in Perl\_\_to\_utf8\_fold\_flags \(p=0xa64751 "\\200"\, 
&nbsp;    ustrp=0x7fffffffd510 "\\200\\325\\377\\377\\377\\177"\, lenp=0x7fffffffd4b8\, 
&nbsp;    flags=3 '\\003'\) at utf8\.c&#8203;:2229
\#6  0x00000000006e159d in Perl\_foldEQ\_utf8\_flags \(s1=0xa646c8 "0"\, pe1=0x0\, 
&nbsp;    l1=1\, u1=false\, s2=0xa64751 "\\200"\, pe2=0x7fffffffd668\, l2=0\, u2=true\, 
&nbsp;    flags=2\) at utf8\.c&#8203;:4084
\#7  0x00000000006c38a3 in S\_regmatch \(reginfo=0x7fffffffe1a0\, 
&nbsp;    startpos=0xa64750 "\\307\\200"\, prog=0xa646c0\) at regexec\.c&#8203;:5473
\#8  0x00000000006bc227 in S\_regtry \(reginfo=0x7fffffffe1a0\, 
&nbsp;    startposp=0x7fffffffdd48\) at regexec\.c&#8203;:3492
\#9  0x00000000006b1a3c in S\_find\_byclass \(prog=0xa649d0\, c=0xa646c0\, 
&nbsp;    s=0xa64750 "\\307\\200"\, strend=0xa64752 ""\, reginfo=0x7fffffffe1a0\)
&nbsp;    at regexec\.c&#8203;:1809
\#10 0x00000000006bb5a8 in Perl\_regexec\_flags \(rx=0xa614f0\, 
&nbsp;    stringarg=0xa64750 "\\307\\200"\, strend=0xa64752 ""\, 
&nbsp;    strbeg=0xa64750 "\\307\\200"\, minend=0\, sv=0xa61430\, data=0x0\, flags=97\)
&nbsp;    at regexec\.c&#8203;:3244
\#11 0x00000000005988f1 in Perl\_pp\_match \(\) at pp\_hot\.c&#8203;:1486
\#12 0x0000000000545c42 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2237
\#13 0x0000000000460555 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2427
\#14 0x000000000045fb99 in perl\_run \(my\_perl=0xa42010\) at perl\.c&#8203;:2350
\#15 0x000000000041eee5 in main \(argc=4\, argv=0x7fffffffe638\, 
&nbsp;    env=0x7fffffffe660\) at perlmain\.c&#8203;:116
\(gdb\)

Hugo

**Comment by p5pRT** [comment]
### From @khwilliamson

The entire \\C construct\, which this ticket is about\, is being removed as of 5\.24\, so bugs with it are no longer relevant
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for submitting this report\.  You have helped make Perl better\.
&nbsp;    
With the release of Perl 5\.24\.0 on May 9\, 2016\, this and 149 other issues have been resolved\.

Perl 5\.24\.0 may be downloaded via https://metacpan.org/release/RJBS/perl-5.24.0

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
