### ISSUE TITLE
compcv refcount (again)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14553]
Migrated from [rt.perl.org#123963](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=123963) (status was 'open')

Searchable as RT123963$

**Comment by p5pRT** [comment]
### From @hvds

They're getting harder to find\, or at least to minimize\. :\)

AFL \(\<http&#8203;://lcamtuf\.coredump\.cx/afl/>\) finds this&#8203;:

% perl \-e 'print "m\\x\{0\}\\x\{1\}\\x\{0\}0000@&#8203;\\x\{0\}\\x\{13\}\\x\{ff\}000000\\x\{1\}\\x\{0\}"' | \./miniperl \-c
miniperl&#8203;: sv\.c&#8203;:6537&#8203;: Perl\_sv\_clear&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= \(svtype\)0xff' failed\.
Aborted \(core dumped\)
% 

This looks like another compcv refcount issue&#8203;:

\(gdb\) where
\#0  0x00007ffff72edbb9 in \_\_GI\_raise \(sig=sig@&#8203;entry=6\)
&nbsp;    at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:56
\#1  0x00007ffff72f0fc8 in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007ffff72e6a76 in \_\_assert\_fail\_base \(
&nbsp;    fmt=0x7ffff7438370 "%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\, 
&nbsp;    assertion=assertion@&#8203;entry=0x7b4980 "\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= \(svtype\)0xff"\, file=file@&#8203;entry=0x7a1134 "sv\.c"\, line=line@&#8203;entry=6537\, 
&nbsp;    function=function@&#8203;entry=0x7bdb15 \<\_\_PRETTY\_FUNCTION\_\_\.17333> "Perl\_sv\_clear"\) at assert\.c&#8203;:92
\#3  0x00007ffff72e6b22 in \_\_GI\_\_\_assert\_fail \(
&nbsp;    assertion=0x7b4980 "\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= \(svtype\)0xff"\, 
&nbsp;    file=0x7a1134 "sv\.c"\, line=6537\, 
&nbsp;    function=0x7bdb15 \<\_\_PRETTY\_FUNCTION\_\_\.17333> "Perl\_sv\_clear"\)
&nbsp;    at assert\.c&#8203;:101
\#4  0x00000000005c2c4d in Perl\_sv\_clear \(orig\_sv=0xa262c8\) at sv\.c&#8203;:6537
\#5  0x00000000005c5af6 in Perl\_sv\_free2 \(sv=0xa262c8\, rc=1\) at sv\.c&#8203;:7031
\#6  0x00000000004b343c in S\_SvREFCNT\_dec \(sv=0xa262c8\) at inline\.h&#8203;:166
\#7  0x00000000004b82f3 in Perl\_yyparse \(gramtype=258\) at perly\.c&#8203;:423
\#8  0x0000000000408c19 in S\_parse\_body \(env=0x0\, xsinit=0x4509d7 \<xs\_init>\)
&nbsp;    at perl\.c&#8203;:2277
\#9  0x00000000004078b5 in perl\_parse \(my\_perl=0xa24010\, 
&nbsp;    xsinit=0x4509d7 \<xs\_init>\, argc=3\, argv=0x7fffffffe638\, env=0x0\)
&nbsp;    at perl\.c&#8203;:1611
\#10 0x0000000000450939 in main \(argc=3\, argv=0x7fffffffe638\, 
&nbsp;    env=0x7fffffffe658\) at miniperlmain\.c&#8203;:120
\(gdb\) 

Hugo

**Comment by p5pRT** [comment]
### From @cpansprout

On Mon Mar 02 00&#8203;:50&#8203;:54 2015\, hv wrote&#8203;:
> They're getting harder to find\, or at least to minimize\. :\)
> 
> AFL \(\<http&#8203;://lcamtuf\.coredump\.cx/afl/>\) finds this&#8203;:
> 
> % perl \-e 'print
> "m\\x\{0\}\\x\{1\}\\x\{0\}0000@&#8203;\\x\{0\}\\x\{13\}\\x\{ff\}000000\\x\{1\}\\x\{0\}"' | \./miniperl
> \-c
> miniperl&#8203;: sv\.c&#8203;:6537&#8203;: Perl\_sv\_clear&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\-
> >sv\_flags & 0xff\)\) \!= \(svtype\)0xff' failed\.
> Aborted \(core dumped\)
>  %

$ perl \-CS \-e 'print "use utf8; m|\\@&#8203;\\x\{ff13\}|"' | \./miniperl \-Ilib \-c
Assertion failed&#8203;: \(SvTYPE\(sv\) \!= \(svtype\)SVTYPEMASK\)\, function Perl\_sv\_clear\, file sv\.c\, line 6537\.
Abort trap&#8203;: 6

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @hvds

I've restarted AFL with a new build of blead at 923ed5809c\, which is running way cleaner since \(I guess\) the \[perl \#123802\] issues were nailed\.

It has reported only one crash so far\, and I suspect it's another instance of the issue in this ticket&#8203;:

% perl \-e 'print chr\(hex\($\_\)\) for qw\{2f 00 40 00 40 10 64 a0 2f 00 40 80 65 a0 a1 0a\}' | \./miniperl \-c
miniperl&#8203;: sv\.c&#8203;:6537&#8203;: Perl\_sv\_clear&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= \(svtype\)0xff' failed\.
Aborted \(core dumped\)
% 

\.\. with a similar backtrace\.

Hugo

**Comment by p5pRT** [comment]
### From @cpansprout

On Mon Mar 02 16&#8203;:05&#8203;:03 2015\, hv wrote&#8203;:
> I've restarted AFL with a new build of blead at 923ed5809c\, which is
> running way cleaner since \(I guess\) the \[perl \#123802\] issues were
> nailed\.
> 
> It has reported only one crash so far\, and I suspect it's another
> instance of the issue in this ticket&#8203;:
> 
> % perl \-e 'print chr\(hex\($\_\)\) for qw\{2f 00 40 00 40 10 64 a0 2f 00 40
> 80 65 a0 a1 0a\}' | \./miniperl \-c
> miniperl&#8203;: sv\.c&#8203;:6537&#8203;: Perl\_sv\_clear&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\-
> >sv\_flags & 0xff\)\) \!= \(svtype\)0xff' failed\.
> Aborted \(core dumped\)
>  %
> 
> \.\. with a similar backtrace\.
> 
> Hugo

In both cases we have a regular expression containing an @&#8203; followed by a non\-ASCII digit\.

A bisect points to f25ce8440\.

f25ce84407dda38dcbb46145067fe57d29d1ef7c is the first bad commit
commit f25ce84407dda38dcbb46145067fe57d29d1ef7c
Author&#8203;: Karl Williamson \<public@&#8203;khwilliamson\.com>
Date&#8203;:   Mon Jan 6 12&#8203;:22&#8203;:02 2014 \-0700

&nbsp;    isWORDCHAR\_uni\(\)\, isDIGIT\_utf8\(\) etc no longer go out to disk
&nbsp;    
&nbsp;    Previous commits in this series have caused all the POSIX classes to be
&nbsp;    completely specified at C compile time\.  This allows us to revise the
&nbsp;    base function used by all these macros to use these definitions\,
&nbsp;    avoiding reading them in from disk\.

\-DT output shows that the lexer emits @&#8203; \, THING instead of @&#8203; WORD\.

The resulting failure mode is similar to \#123802 \(with LEX\_INTERPSTART this time\)\, though I don’t know that there is a way to trigger it that does not depend on this Unicode bug\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @cpansprout

On Mon Mar 02 17&#8203;:50&#8203;:47 2015\, sprout wrote&#8203;:
> On Mon Mar 02 16&#8203;:05&#8203;:03 2015\, hv wrote&#8203;:
> > I've restarted AFL with a new build of blead at 923ed5809c\, which is
> > running way cleaner since \(I guess\) the \[perl \#123802\] issues were
> > nailed\.
> >
> > It has reported only one crash so far\, and I suspect it's another
> > instance of the issue in this ticket&#8203;:
> >
> > % perl \-e 'print chr\(hex\($\_\)\) for qw\{2f 00 40 00 40 10 64 a0 2f 00 40
> > 80 65 a0 a1 0a\}' | \./miniperl \-c
> > miniperl&#8203;: sv\.c&#8203;:6537&#8203;: Perl\_sv\_clear&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\-
> > > sv\_flags & 0xff\)\) \!= \(svtype\)0xff' failed\.
> > Aborted \(core dumped\)
> >  %
> >
> > \.\. with a similar backtrace\.
> >
> > Hugo
> 
> In both cases we have a regular expression containing an @&#8203; followed by
> a non\-ASCII digit\.
> 
> A bisect points to f25ce8440\.
> 
> f25ce84407dda38dcbb46145067fe57d29d1ef7c is the first bad commit
> commit f25ce84407dda38dcbb46145067fe57d29d1ef7c
> Author&#8203;: Karl Williamson \<public@&#8203;khwilliamson\.com>
> Date&#8203;:   Mon Jan 6 12&#8203;:22&#8203;:02 2014 \-0700
> 
> isWORDCHAR\_uni\(\)\, isDIGIT\_utf8\(\) etc no longer go out to disk
> 
> Previous commits in this series have caused all the POSIX classes to
> be
> completely specified at C compile time\.  This allows us to revise the
> base function used by all these macros to use these definitions\,
> avoiding reading them in from disk\.
> 
> \-DT output shows that the lexer emits @&#8203; \, THING instead of @&#8203; WORD\.
> 
> The resulting failure mode is similar to \#123802 \(with LEX\_INTERPSTART
> this time\)\, though I don’t know that there is a way to trigger it that
> does not depend on this Unicode bug\.

scan\_const sees what looks like an @&#8203; followed by a valid identifier\, so it stops before the @&#8203;\.  Shortly thereafter\, parse\_ident rejects the fullwidth 3 \(\\x\{ff13\}\) as not being valid at the beginning of an identifier\.  So the lexer is not consistent with itself\.

scan\_const is using isWORDCHAR\_lazy\_if\.  parse\_ident is using isIDFIRST\_utf8\.  Did f25ce84407d indirectly change the behaviour of either of those?

Since this is a regression\, I think we ought to address it before 5\.22\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @khwilliamson

On 03/02/2015 10&#8203;:50 PM\, Father Chrysostomos via RT wrote&#8203;:
> On Mon Mar 02 17&#8203;:50&#8203;:47 2015\, sprout wrote&#8203;:
>> On Mon Mar 02 16&#8203;:05&#8203;:03 2015\, hv wrote&#8203;:
>>> I've restarted AFL with a new build of blead at 923ed5809c\, which is
>>> running way cleaner since \(I guess\) the \[perl \#123802\] issues were
>>> nailed\.
>>>
>>> It has reported only one crash so far\, and I suspect it's another
>>> instance of the issue in this ticket&#8203;:
>>>
>>> % perl \-e 'print chr\(hex\($\_\)\) for qw\{2f 00 40 00 40 10 64 a0 2f 00 40
>>> 80 65 a0 a1 0a\}' | \./miniperl \-c
>>> miniperl&#8203;: sv\.c&#8203;:6537&#8203;: Perl\_sv\_clear&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\-
>>>> sv\_flags & 0xff\)\) \!= \(svtype\)0xff' failed\.
>>> Aborted \(core dumped\)
>>>   %
>>>
>>> \.\. with a similar backtrace\.
>>>
>>> Hugo
>>
>> In both cases we have a regular expression containing an @&#8203; followed by
>> a non\-ASCII digit\.
>>
>> A bisect points to f25ce8440\.
>>
>> f25ce84407dda38dcbb46145067fe57d29d1ef7c is the first bad commit
>> commit f25ce84407dda38dcbb46145067fe57d29d1ef7c
>> Author&#8203;: Karl Williamson \<public@&#8203;khwilliamson\.com>
>> Date&#8203;:   Mon Jan 6 12&#8203;:22&#8203;:02 2014 \-0700
>>
>> isWORDCHAR\_uni\(\)\, isDIGIT\_utf8\(\) etc no longer go out to disk
>>
>> Previous commits in this series have caused all the POSIX classes to
>> be
>> completely specified at C compile time\.  This allows us to revise the
>> base function used by all these macros to use these definitions\,
>> avoiding reading them in from disk\.
>>
>> \-DT output shows that the lexer emits @&#8203; \, THING instead of @&#8203; WORD\.
>>
>> The resulting failure mode is similar to \#123802 \(with LEX\_INTERPSTART
>> this time\)\, though I don’t know that there is a way to trigger it that
>> does not depend on this Unicode bug\.
>
> scan\_const sees what looks like an @&#8203; followed by a valid identifier\, so it stops before the @&#8203;\.  Shortly thereafter\, parse\_ident rejects the fullwidth 3 \(\\x\{ff13\}\) as not being valid at the beginning of an identifier\.  So the lexer is not consistent with itself\.

I think we should do an audit of the uses of these\.  In this case\, WORD 
is inappropriate\.  My guess is that there are other instances of the 
same\, which only bite us on unaccustomed Unicode characters\.
>
> scan\_const is using isWORDCHAR\_lazy\_if\.  parse\_ident is using isIDFIRST\_utf8\.  Did f25ce84407d indirectly change the behaviour of either of those?

Looking at the commit\, the behavior change was inadvertent

>
> Since this is a regression\, I think we ought to address it before 5\.22\.

Agreed\, and I see you have already added it to the blockers\.
>

**Comment by p5pRT** [comment]
### From @cpansprout

On Fri Mar 06 10&#8203;:38&#8203;:31 2015\, public@&#8203;khwilliamson\.com wrote&#8203;:
> On 03/02/2015 10&#8203;:50 PM\, Father Chrysostomos via RT wrote&#8203;:
> > scan\_const sees what looks like an @&#8203; followed by a valid identifier\,
> > so it stops before the @&#8203;\.  Shortly thereafter\, parse\_ident rejects
> > the fullwidth 3 \(\\x\{ff13\}\) as not being valid at the beginning of an
> > identifier\.  So the lexer is not consistent with itself\.
> 
> I think we should do an audit of the uses of these\.  In this case\,
> WORD
> is inappropriate\.  My guess is that there are other instances of the
> same\, which only bite us on unaccustomed Unicode characters\.


I have fixed this particular case in 9d58dbc\.  I have not done the audit\, so this ticket should stay open\, but I am removing it from the blockers’ list\.

> >
> > scan\_const is using isWORDCHAR\_lazy\_if\.  parse\_ident is using
> > isIDFIRST\_utf8\.  Did f25ce84407d indirectly change the behaviour of
> > either of those?
> 
> Looking at the commit\, the behavior change was inadvertent
> 
> >
> > Since this is a regression\, I think we ought to address it before
> > 5\.22\.
> 
> Agreed\, and I see you have already added it to the blockers\.
> >


\-\- 

Father Chrysostomos
