### ISSUE TITLE
Segfault in Perl_lex_read_space found with afl-fuzz.

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14740]
Migrated from [rt.perl.org#125363](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=125363) (status was 'resolved')

Searchable as RT125363$

**Comment by p5pRT** [comment]
### From edy.burt@gmail.com

#### Created by edy.burt@gmail.com



Executing "\[m\#" \(without quotes or a trailing newline\) causes comment
scanning loop to go outside the buffer and eventually segfault&#8203;:

Program received signal SIGSEGV\, Segmentation fault\.
0x00007ffff7a89fc1 in Perl\_lex\_read\_space \(\) from
/nix/store/qp6sn6zqf36d43x0i4yvak1zk9ld43js\-perl\-5\.20\.2/lib/perl5/5\.20\.2/x86\_64\-linux\-thread\-multi/CORE/libperl\.so
\(gdb\) bt
\#0  0x00007ffff7a89fc1 in Perl\_lex\_read\_space \(\) from
/nix/store/qp6sn6zqf36d43x0i4yvak1zk9ld43js\-perl\-5\.20\.2/lib/perl5/5\.20\.2/x86\_64\-linux\-thread\-multi/CORE/libperl\.so
\#1  0x00007ffff7a8a15e in S\_skipspace\_flags \(\) from
/nix/store/qp6sn6zqf36d43x0i4yvak1zk9ld43js\-perl\-5\.20\.2/lib/perl5/5\.20\.2/x86\_64\-linux\-thread\-multi/CORE/libperl\.so
\#2  0x00007ffff7a8e3fe in S\_scan\_pat \(\) from
/nix/store/qp6sn6zqf36d43x0i4yvak1zk9ld43js\-perl\-5\.20\.2/lib/perl5/5\.20\.2/x86\_64\-linux\-thread\-multi/CORE/libperl\.so
\#3  0x00007ffff7aa24aa in Perl\_yylex \(\) from
/nix/store/qp6sn6zqf36d43x0i4yvak1zk9ld43js\-perl\-5\.20\.2/lib/perl5/5\.20\.2/x86\_64\-linux\-thread\-multi/CORE/libperl\.so
\#4  0x00007ffff7aa44d8 in Perl\_yyparse \(\) from
/nix/store/qp6sn6zqf36d43x0i4yvak1zk9ld43js\-perl\-5\.20\.2/lib/perl5/5\.20\.2/x86\_64\-linux\-thread\-multi/CORE/libperl\.so
\#5  0x00007ffff7a7e1cd in perl\_parse \(\) from
/nix/store/qp6sn6zqf36d43x0i4yvak1zk9ld43js\-perl\-5\.20\.2/lib/perl5/5\.20\.2/x86\_64\-linux\-thread\-multi/CORE/libperl\.so
\#6  0x0000000000400fcb in main \(\)

<details><summary>Perl Info</summary>

```

Flags:
   category=core
   severity=high

Site configuration information for perl 5.20.2:

Configured by nixbld at Tue May  5 11:33:05 UTC 2015.

Summary of my perl5 (revision 5 version 20 subversion 2) configuration:

 Platform:
   osname=linux, osvers=3.12.27, archname=x86_64-linux-thread-multi
   uname='linux localhost 3.12.27 #1-nixos smp thu jan 1 00:00:01 utc
1970 x86_64 gnulinux '
   config_args='-de -Dcc=cc -Uinstallusrbinperl
-Dinstallstyle=lib/perl5 -Duseshrplib
-Dlocincpth=/nix/store/c2zjp7bqmp5wvpkrpl7p7sfhxbdyfryy-glibc-2.21/include
-Dloclibpth=/nix/store/c2zjp7bqmp5wvpkrpl7p7sfhxbdyfryy-glibc-2.21/lib
-Dusethreads -Dprefix=/nix/store/qp6sn6zqf36d43x0i4yvak1zk9ld43js-perl-5.20.2
-Dman1dir=/nix/store
/qp6sn6zqf36d43x0i4yvak1zk9ld43js-perl-5.20.2/share/man/man1
-Dman3dir=/nix/store/qp6sn6zqf36d43x0i4yvak1zk9ld43js-perl-5.20.2/share/man/man3'
   hint=recommended, useposix=true, d_sigaction=define
   useithreads=define, usemultiplicity=define
   use64bitint=define, use64bitall=define, uselongdouble=undef
   usemymalloc=n, bincompat5005=undef
 Compiler:
   cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv
-fno-strict-aliasing -pipe -fstack-protector
-I/nix/store/c2zjp7bqmp5wvpkrpl7p7sfhxbdyfryy-glibc-2.21/include
-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
   optimize='-O2',
   cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing
-pipe -fstack-protector
-I/nix/store/c2zjp7bqmp5wvpkrpl7p7sfhxbdyfryy-glibc-2.21/include'
   ccversion='', gccversion='4.8.4', gccosandvers=''
   intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
   d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
   ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t',
lseeksize=8
   alignbytes=8, prototype=define
 Linker and Libraries:
   ld='cc', ldflags =' -fstack-protector
-L/nix/store/c2zjp7bqmp5wvpkrpl7p7sfhxbdyfryy-glibc-2.21/lib'
   libpth=/nix/store/qr35kb3cd1vb21a6mqa43xwmjy7jrbcq-gcc-4.8.4/lib
/nix/store/qr35kb3cd1vb21a6mqa43xwmjy7jrbcq-gcc-4.8.4/lib/gcc/x86_64-unknown-linux-gnu/4.8.4/include-fixed
/nix/store/c2zjp7bqmp5wvpkrpl7p7sfhxbdyfryy-glibc-2.21/lib
   libs=-lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
   perllibs=-lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
   libc=, so=so, useshrplib=true, libperl=libperl.so
   gnulibc_version='2.21'
 Dynamic Linking:
   dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E
-Wl,-rpath,/nix/store/qp6sn6zqf36d43x0i4yvak1zk9ld43js-perl-5.20.2/lib/perl5/5.20.2/x86_64-linux-thread-multi/CORE'
   cccdlflags='-fPIC', lddlflags='-shared -O2
-L/nix/store/c2zjp7bqmp5wvpkrpl7p7sfhxbdyfryy-glibc-2.21/lib
-fstack-protector'



@INC for perl 5.20.2:
   /home/eddy/.nix-profile/lib/perl5/site_perl/5.20.2/x86_64-linux-thread-multi
   /home/eddy/.nix-profile/lib/perl5/site_perl/5.20.2
   /home/eddy/.nix-profile/lib/perl5/site_perl
   /nix/var/nix/profiles/default/lib/perl5/site_perl
   /run/current-system/sw/lib/perl5/site_perl/5.20.2/x86_64-linux-thread-multi
   /run/current-system/sw/lib/perl5/site_perl/5.20.2
   /run/current-system/sw/lib/perl5/site_perl
   /nix/store/qp6sn6zqf36d43x0i4yvak1zk9ld43js-perl-5.20.2/lib/perl5/site_perl/5.20.2/x86_64-linux-thread-multi
   /nix/store/qp6sn6zqf36d43x0i4yvak1zk9ld43js-perl-5.20.2/lib/perl5/site_perl/5.20.2
   /nix/store/qp6sn6zqf36d43x0i4yvak1zk9ld43js-perl-5.20.2/lib/perl5/5.20.2/x86_64-linux-thread-multi
   /nix/store/qp6sn6zqf36d43x0i4yvak1zk9ld43js-perl-5.20.2/lib/perl5/5.20.2
   .


Environment for perl 5.20.2:
   HOME=/home/eddy
   LANG=en_GB.UTF-8
   LANGUAGE=

```
</details>

**Comment by p5pRT** [comment]
### From @ilmari

Eddy B\. \(via RT\) \<perlbug\-followup@&#8203;perl\.org> writes&#8203;:

> Executing "\[m\#" \(without quotes or a trailing newline\) causes comment
> scanning loop to go outside the buffer and eventually segfault&#8203;:

This is fixed in 5\.22\, where it dies with "Search pattern not
terminated"\.  Bisect points to this commit\, which eliminates the
offending skipspace\(\) call&#8203;:

commit 4963771dd10435273997ef50267b3ebd07dfb80b
Author&#8203;: Dagfinn Ilmari Mannsåker \<ilmari@&#8203;ilmari\.org>
Date&#8203;:   Thu Jan 2 14&#8203;:06&#8203;:51 2014 \+0100

&nbsp;    Remove "ternary operator parsed as search pattern" warning
&nbsp;    
&nbsp;    Since ?PATTERN? without 'm' is no longer supported\, there is no
&nbsp;    ambiguity any more\.



\-\- 
"A disappointingly low fraction of the human race is\,
 at any given time\, on fire\." \- Stig Sandbeck Mathisen

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
