### ISSUE TITLE
S_glob_assign_glob: Assertion `((svtype)((_gvgp)->sv_flags & 0xff)) == SVt_PVGV || ((svtype)((_gvgp)->sv_flags & 0xff)) == SVt_PVLV' failed (sv.c:3979)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14741]
Migrated from [rt.perl.org#125368](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=125368) (status was 'resolved')

Searchable as RT125368$

**Comment by p5pRT** [comment]
### From @geeknik

The following "script" causes an assertion failure in Perl v5\.23\.0 \(v5\.22\.0\-85\-g16ac183\)\.

perl \-e '$x=\*x=$x=\*>'
perl&#8203;: sv\.c&#8203;:3979&#8203;: S\_glob\_assign\_glob&#8203;: Assertion \`\(\(svtype\)\(\(\_gvgp\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_gvgp\)\->sv\_flags & 0xff\)\) == SVt\_PVLV' failed\.
Aborted

The same script also causes a null ptr deref and seg fault in Perl v5\.21\.7 \(v5\.21\.6\-602\-ge9d2bd8\)&#8203;:

==8620== Invalid read of size 8
==8620==    at 0x7779FC&#8203;: Perl\_pp\_gvsv \(pp\_hot\.c&#8203;:65\)
==8620==    by 0x775A6A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==8620==    by 0x4F3DBE&#8203;: perl\_run \(perl\.c&#8203;:2421\)
==8620==    by 0x42AB1B&#8203;: main \(perlmain\.c&#8203;:116\)
==8620==  Address 0x0 is not stack'd\, malloc'd or \(recently\) free'd
==8620== 
==8620== 
==8620== Process terminating with default action of signal 11 \(SIGSEGV\)
==8620==  Access not within mapped region at address 0x0
==8620==    at 0x7779FC&#8203;: Perl\_pp\_gvsv \(pp\_hot\.c&#8203;:65\)
==8620==    by 0x775A6A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==8620==    by 0x4F3DBE&#8203;: perl\_run \(perl\.c&#8203;:2421\)
==8620==    by 0x42AB1B&#8203;: main \(perlmain\.c&#8203;:116\)
==8620==  If you believe this happened as a result of a stack
==8620==  overflow in your program's main thread \(unlikely but
==8620==  possible\)\, you can try to increase the size of the
==8620==  main thread stack using the \-\-main\-stacksize= flag\.
==8620==  The main thread stack size used in this run was 8388608\.
Segmentation fault

Program received signal SIGSEGV\, Segmentation fault\.
0x00000000007779fc in Perl\_pp\_gvsv \(\) at pp\_hot\.c&#8203;:65
65    pp\_hot\.c&#8203;: No such file or directory\.
\(gdb\) bt
\#0  0x00000000007779fc in Perl\_pp\_gvsv \(\) at pp\_hot\.c&#8203;:65
\#1  0x0000000000775a6b in Perl\_runops\_standard \(\) at run\.c&#8203;:41
\#2  0x00000000004f3dbf in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2421
\#3  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2344
\#4  0x000000000042ab1c in main \(argc=2\, argv=0x7fffffffe388\, 
&nbsp;    env=0x7fffffffe3a0\) at perlmain\.c&#8203;:116
\#5  0x00007ffff6f98ead in \_\_libc\_start\_main \(main=\<optimized out>\, 
&nbsp;    argc=\<optimized out>\, ubp\_av=\<optimized out>\, init=\<optimized out>\, 
&nbsp;    fini=\<optimized out>\, rtld\_fini=\<optimized out>\, stack\_end=0x7fffffffe378\)
&nbsp;    at libc\-start\.c&#8203;:244
\#6  0x000000000042ab95 in \_start \(\)
\(gdb\) i r
rax            0x3f0    1008
rbx            0xe28b58    14846808
rcx            0x0    0
rdx            0x0    0
rsi            0x0    0
rdi            0xe3b020    14921760
rbp            0xe28b60    0xe28b60
rsp            0x7fffffffe120    0x7fffffffe120
r8             0xe466a8    14968488
r9             0xe3cf70    14929776
r10            0x0    0
r11            0xe46c30    14969904
r12            0x42ab6c    4369260
r13            0x7fffffffe380    140737488348032
r14            0x0    0
r15            0x0    0
rip            0x7779fc    0x7779fc \<Perl\_pp\_gvsv\+260>
eflags         0x10246    \[ PF ZF IF RF \]
cs             0x33    51
ss             0x2b    43
ds             0x0    0
es             0x0    0
fs             0x0    0
gs             0x0    0

This bug was found with AFL \(http&#8203;://lcamtuf\.coredump\.cx/afl/\)

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue Jun 09 09&#8203;:40&#8203;:17 2015\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> The following "script" causes an assertion failure in Perl v5\.23\.0
> \(v5\.22\.0\-85\-g16ac183\)\.
> 
> perl \-e '$x=\*x=$x=\*>'

This can be simplified to&#8203;:

&nbsp;  perl \-e '\*x=$x=\*>'

There's nothing special about \*>&#8203;:

&nbsp;  perl \-e '\*x=$x=\*y'

will also assert\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @geeknik

FYI\, this bug doesn't appear to affect perl 5\, version 20\, subversion 2 \(v5\.20\.2\) built for i386\-freebsd\-thread\-multi\-64int on FreeBSD 9\.3\-RELEASE\-p9\.

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue Jun 09 09&#8203;:40&#8203;:17 2015\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> The following "script" causes an assertion failure in Perl v5\.23\.0
> \(v5\.22\.0\-85\-g16ac183\)\.
> 
> perl \-e '$x=\*x=$x=\*>'
> perl&#8203;: sv\.c&#8203;:3979&#8203;: S\_glob\_assign\_glob&#8203;: Assertion \`\(\(svtype\)\(\(\_gvgp\)\-
> >sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_gvgp\)\->sv\_flags & 0xff\)\)
> == SVt\_PVLV' failed\.
> Aborted

Looks like this was fixed in&#8203;:

commit 3c62f09f418b63bd79a6cbd20aaec4d992a6cc64
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Sun Aug 30 09&#8203;:48&#8203;:28 2015 \+0100

&nbsp;    RT \#125840 stop \*x = $x doing bad things
&nbsp;    
&nbsp;    If $x is a GV then \*x's GP would be freed before $x's GP is assigned to
&nbsp;    it\. That would prematurely free $x\, so protect it with a temporary ref
&nbsp;    count bump\.

Closing\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for submitting this report\.  You have helped make Perl better\.
&nbsp;    
With the release of Perl 5\.24\.0 on May 9\, 2016\, this and 149 other issues have been resolved\.

Perl 5\.24\.0 may be downloaded via https://metacpan.org/release/RJBS/perl-5.24.0

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
