### ISSUE TITLE
null ptr deref -> bcmp (mc_replace_strmem.c:889) | S_scan_doc: Assertion 's' failed (toke.c:9314)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14789]
Migrated from [rt.perl.org#125540](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=125540) (status was 'resolved')

Searchable as RT125540$

**Comment by p5pRT** [comment]
### From @geeknik

While fuzzing Perl built from git source \(v5\.23\.0\-69\-gf907dd3\)\, I came across the following "script" that causes an assertion failure at toke\.c&#8203;:9314&#8203;:

geeknik@&#8203;h5n2&#8203;:\~$ ~/perl/perl test03\-min
$\# is no longer supported at test03\-min line 1\.
Use of bare \<\< to mean \<\<"" is deprecated at test03\-min line 1\.
perl&#8203;: toke\.c&#8203;:9314&#8203;: S\_scan\_heredoc&#8203;: Assertion \`s' failed\.
Aborted

It also causes Perl v5\.21\.6\-602\-ge9d2bd8 to segfault at mc\_replace\_strmem\.c&#8203;:889&#8203;:

$\# is no longer supported at test03\-min line 1\.
Use of bare \<\< to mean \<\<"" is deprecated at test03\-min line 1\.
==54432== Invalid read of size 1
==54432==    at 0x4C2B0B9&#8203;: bcmp \(mc\_replace\_strmem\.c&#8203;:889\)
==54432==    by 0x58CC9E&#8203;: Perl\_yylex \(toke\.c&#8203;:9259\)
==54432==    by 0x5C60B4&#8203;: Perl\_yyparse \(perly\.c&#8203;:322\)
==54432==    by 0x4F0874&#8203;: perl\_parse \(perl\.c&#8203;:2271\)
==54432==    by 0x42A87B&#8203;: main \(perlmain\.c&#8203;:114\)
==54432==  Address 0x0 is not stack'd\, malloc'd or \(recently\) free'd
==54432== 
==54432== 
==54432== Process terminating with default action of signal 11 \(SIGSEGV\)
==54432==  Access not within mapped region at address 0x0
==54432==    at 0x4C2B0B9&#8203;: bcmp \(mc\_replace\_strmem\.c&#8203;:889\)
==54432==    by 0x58CC9E&#8203;: Perl\_yylex \(toke\.c&#8203;:9259\)
==54432==    by 0x5C60B4&#8203;: Perl\_yyparse \(perly\.c&#8203;:322\)
==54432==    by 0x4F0874&#8203;: perl\_parse \(perl\.c&#8203;:2271\)
==54432==    by 0x42A87B&#8203;: main \(perlmain\.c&#8203;:114\)
==54432==  If you believe this happened as a result of a stack
==54432==  overflow in your program's main thread \(unlikely but
==54432==  possible\)\, you can try to increase the size of the
==54432==  main thread stack using the \-\-main\-stacksize= flag\.
==54432==  The main thread stack size used in this run was 8388608\.
Segmentation fault

$\# is no longer supported at test03\-min line 1\.
Use of bare \<\< to mean \<\<"" is deprecated at test03\-min line 1\.

Program received signal SIGSEGV\, Segmentation fault\.
\_\_memcmp\_sse4\_1 \(\) at \.\./sysdeps/x86\_64/multiarch/memcmp\-sse4\.S&#8203;:936
936    \.\./sysdeps/x86\_64/multiarch/memcmp\-sse4\.S&#8203;: No such file or directory\.
\(gdb\) bt
\#0  \_\_memcmp\_sse4\_1 \(\) at \.\./sysdeps/x86\_64/multiarch/memcmp\-sse4\.S&#8203;:936
\#1  0x000000000058cc9f in S\_scan\_heredoc \(s=0x0\) at toke\.c&#8203;:9259
\#2  Perl\_yylex \(\) at toke\.c&#8203;:5876
\#3  0x00000000005c60b5 in Perl\_yyparse \(gramtype=\<optimized out>\) at perly\.c&#8203;:322
\#4  0x00000000004f0875 in S\_parse\_body \(xsinit=0x42ac70 \<xs\_init>\, env=0x0\) at perl\.c&#8203;:2271
\#5  perl\_parse \(my\_perl=\<optimized out>\, xsinit=0x42ac70 \<xs\_init>\, argc=\<optimized out>\, 
&nbsp;    argv=\<optimized out>\, env=0x0\) at perl\.c&#8203;:1605
\#6  0x000000000042a87c in main \(argc=2\, argv=0x7fffffffe3a8\, env=0x7fffffffe3c0\) at perlmain\.c&#8203;:114
\#7  0x00007ffff6f98ead in \_\_libc\_start\_main \(main=\<optimized out>\, argc=\<optimized out>\, 
&nbsp;    ubp\_av=\<optimized out>\, init=\<optimized out>\, fini=\<optimized out>\, rtld\_fini=\<optimized out>\, 
&nbsp;    stack\_end=0x7fffffffe398\) at libc\-start\.c&#8203;:244
\#8  0x000000000042ab95 in \_start \(\)
\(gdb\) i r
rax            0xe4205b    14950491
rbx            0xe4205b    14950491
rcx            0xa0a    2570
rdx            0x2    2
rsi            0xe4300a    14954506
rdi            0x2    2
rbp            0xe42020    0xe42020
rsp            0x7fffffffd938    0x7fffffffd938
r8             0xe3fd60    14941536
r9             0x3    3
r10            0xe26f30    14839600
r11            0x7ffff70d03f0    140737338213360
r12            0xe3aff8    14921720
r13            0xe42eb0    14954160
r14            0x0    0
r15            0x0    0
rip            0x7ffff70b00b2    0x7ffff70b00b2 \<\_\_memcmp\_sse4\_1\+3522>
eflags         0x10203    \[ CF IF RF \]
cs             0x33    51
ss             0x2b    43
ds             0x0    0
es             0x0    0
fs             0x0    0
gs             0x0    0

**Comment by p5pRT** [comment]
### From @geeknik

[test03-min](https://rt-archive.perl.org/perl5/Ticket/Attachment/1355911/725061/test03-min)

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers a segfault in the Perl interpreter\. The testcase is the attached file&#8203;:

$ od \-c out/allcrash/f2i000048
0000000   \-   r  \\v   d   $   \#   \<   \<   \<   \<
0000012

When executed\, this prints the following&#8203;:
dcollins@&#8203;nightshade64&#8203;:\~$ \./perl/perl f2i000048 
$\# is no longer supported at f2i000048 line 1\.
Use of bare \<\< to mean \<\<"" is deprecated at f2i000048 line 1\.
Segmentation fault
dcollins@&#8203;nightshade64&#8203;:\~$ \./perldebug/perl f2i000048 
$\# is no longer supported at f2i000048 line 1\.
Use of bare \<\< to mean \<\<"" is deprecated at f2i000048 line 1\.
perl&#8203;: toke\.c&#8203;:9575&#8203;: S\_scan\_heredoc&#8203;: Assertion \`s' failed\.
Aborted


\*\*GDB\*\*

\(gdb\) run
Starting program&#8203;: /home/dcollins/perl/perl f2i000048
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
$\# is no longer supported at f2i000048 line 1\.
Use of bare \<\< to mean \<\<"" is deprecated at f2i000048 line 1\.

Program received signal SIGSEGV\, Segmentation fault\.
0x00007ffff6e04f42 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt 
\#0  0x00007ffff6e04f42 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x0000000000598534 in S\_scan\_heredoc \(s=0x0\) at toke\.c&#8203;:9581
\#2  Perl\_yylex \(\) at toke\.c&#8203;:6134
\#3  0x00000000005b7d35 in Perl\_yyparse \(gramtype=gramtype@&#8203;entry=258\) at perly\.c&#8203;:322
\#4  0x00000000004e78cd in S\_parse\_body \(xsinit=0x4274e0 \<xs\_init>\, env=0x0\) at perl\.c&#8203;:2312
\#5  perl\_parse \(my\_perl=\<optimized out>\, xsinit=xsinit@&#8203;entry=0x4274e0 \<xs\_init>\, argc=\<optimized out>\, argv=\<optimized out>\, env=env@&#8203;entry=0x0\) at perl\.c&#8203;:1634
\#6  0x0000000000427108 in main \(argc=2\, argv=0x7fffffffe358\, env=0x7fffffffe370\) at perlmain\.c&#8203;:114
\(gdb\) f 1
\#1  0x0000000000598534 in S\_scan\_heredoc \(s=0x0\) at toke\.c&#8203;:9581
9581                   && memNE\(s\,PL\_tokenbuf\,len\) \)
\(gdb\) info locals
linestr = 0xe65d08
bufend = 0xe6e25b ""
olds = 0xe6e25a ";"
cx = 0xe53dd8
term = \<optimized out>
d = 0x0
peek = \<optimized out>
origline = 1
tmpstr = 0xe65dc8
e = \<optimized out>
infile = \<optimized out>
shared = 0xe6e220
op\_type = 2
len = 2


\*\*VALGRIND\*\*

==14515== Memcheck\, a memory error detector
==14515== Copyright \(C\) 2002\-2015\, and GNU GPL'd\, by Julian Seward et al\.
==14515== Using Valgrind\-3\.11\.0 and LibVEX; rerun with \-h for copyright info
==14515== Command&#8203;: \./perl/perl f2i000048
==14515== 
$\# is no longer supported at f2i000048 line 1\.
Use of bare \<\< to mean \<\<"" is deprecated at f2i000048 line 1\.
==14515== Invalid read of size 1
==14515==    at 0x4C2D8B5&#8203;: \_\_memcmp\_sse4\_1 \(vg\_replace\_strmem\.c&#8203;:1094\)
==14515==    by 0x598533&#8203;: S\_scan\_heredoc \(toke\.c&#8203;:9581\)
==14515==    by 0x598533&#8203;: Perl\_yylex \(toke\.c&#8203;:6134\)
==14515==    by 0x5B7D34&#8203;: Perl\_yyparse \(perly\.c&#8203;:322\)
==14515==    by 0x4E78CC&#8203;: S\_parse\_body \(perl\.c&#8203;:2312\)
==14515==    by 0x4E78CC&#8203;: perl\_parse \(perl\.c&#8203;:1634\)
==14515==    by 0x427107&#8203;: main \(perlmain\.c&#8203;:114\)
==14515==  Address 0x0 is not stack'd\, malloc'd or \(recently\) free'd
==14515== 
==14515== 
==14515== Process terminating with default action of signal 11 \(SIGSEGV\)
==14515==  Access not within mapped region at address 0x0
==14515==    at 0x4C2D8B5&#8203;: \_\_memcmp\_sse4\_1 \(vg\_replace\_strmem\.c&#8203;:1094\)
==14515==    by 0x598533&#8203;: S\_scan\_heredoc \(toke\.c&#8203;:9581\)
==14515==    by 0x598533&#8203;: Perl\_yylex \(toke\.c&#8203;:6134\)
==14515==    by 0x5B7D34&#8203;: Perl\_yyparse \(perly\.c&#8203;:322\)
==14515==    by 0x4E78CC&#8203;: S\_parse\_body \(perl\.c&#8203;:2312\)
==14515==    by 0x4E78CC&#8203;: perl\_parse \(perl\.c&#8203;:1634\)
==14515==    by 0x427107&#8203;: main \(perlmain\.c&#8203;:114\)
==14515==  If you believe this happened as a result of a stack
==14515==  overflow in your program's main thread \(unlikely but
==14515==  possible\)\, you can try to increase the size of the
==14515==  main thread stack using the \-\-main\-stacksize= flag\.
==14515==  The main thread stack size used in this run was 8388608\.
==14515== 
==14515== HEAP SUMMARY&#8203;:
==14515==     in use at exit&#8203;: 126\,829 bytes in 646 blocks
==14515==   total heap usage&#8203;: 739 allocs\, 93 frees\, 143\,644 bytes allocated
==14515== 
==14515== LEAK SUMMARY&#8203;:
==14515==    definitely lost&#8203;: 328 bytes in 1 blocks
==14515==    indirectly lost&#8203;: 2\,617 bytes in 39 blocks
==14515==      possibly lost&#8203;: 0 bytes in 0 blocks
==14515==    still reachable&#8203;: 123\,884 bytes in 606 blocks
==14515==         suppressed&#8203;: 0 bytes in 0 blocks
==14515== Rerun with \-\-leak\-check=full to see details of leaked memory
==14515== 
==14515== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==14515== ERROR SUMMARY&#8203;: 1 errors from 1 contexts \(suppressed&#8203;: 0 from 0\)
Segmentation fault


\*\*PERL \-V\*\*

Summary of my perl5 \(revision 5 version 23 subversion 6\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 572cd85091706ffa2e19db60c41c6bb106297e3a
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt11\-1\+deb8u4 \(2015\-09\-19\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='5\.2\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/x86\_64\-unknown\-linux\-gnu/5\.2\.0/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Dec  4 2015 16&#8203;:50&#8203;:14
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    perl/lib
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.6/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.6
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.6/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.6
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.5
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @dcollinsn

[f2i000048](https://rt-archive.perl.org/perl5/Ticket/Attachment/1378386/740381/f2i000048)

**Comment by p5pRT** [comment]
### From @geeknik

Maybe a dupe of 125540?

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Fri Jul 03 09&#8203;:57&#8203;:24 2015\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> While fuzzing Perl built from git source \(v5\.23\.0\-69\-gf907dd3\)\, I came
> across the following "script" that causes an assertion failure at
> toke\.c&#8203;:9314&#8203;:
> 
> geeknik@&#8203;h5n2&#8203;:\~$ ~/perl/perl test03\-min
> $\# is no longer supported at test03\-min line 1\.
> Use of bare \<\< to mean \<\<"" is deprecated at test03\-min line 1\.
> perl&#8203;: toke\.c&#8203;:9314&#8203;: S\_scan\_heredoc&#8203;: Assertion \`s' failed\.
> Aborted

The attached should fix this\.

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

<details><summary>0001-perl-125540-handle-already-being-at-EOF-while-not-fi.patch</summary>

```diff
From 87ee70413aa5b8f8c6ebeea5d0e3f9fe6a8300f1 Mon Sep 17 00:00:00 2001
From: Tony Cook <tony@develop-help.com>
Date: Wed, 20 Jan 2016 15:35:13 +1100
Subject: [perl #125540] handle already being at EOF while not finding a
 heredoc terminator

In some cases, S_scan_heredoc() can already be at end of file and
PL_rsfp is NULL.  If we're on the final line and that line has no
newline we'd assert or crash.

Now, if we don't find that newline, we obviously can't find the
terminator, so go straight to reporting the missing terminator.

I considered setting s to PL_bufend, but that would just be more
work to print the same message.
---
 t/op/heredoc.t | 10 +++++++++-
 toke.c         |  5 +++--
 2 files changed, 12 insertions(+), 3 deletions(-)

diff --git a/t/op/heredoc.t b/t/op/heredoc.t
index dadf105..8fe0c0f 100644
--- a/t/op/heredoc.t
+++ b/t/op/heredoc.t
@@ -7,7 +7,7 @@ BEGIN {
 }
 
 use strict;
-plan(tests => 40);
+plan(tests => 41);
 
 
 # heredoc without newline (#65838)
@@ -98,4 +98,12 @@ HEREDOC
         {},
         "don't use an invalid oldoldbufptr"
     );
+
+    # [perl #125540] this asserted or crashed
+    fresh_perl_like(
+	q(map d$#<<<<),
+	qr/Can't find string terminator "" anywhere before EOF at - line 1\./,
+	{},
+	"Don't assert parsing a here-doc if we hit EOF early"
+    );
 }
diff --git a/toke.c b/toke.c
index 23c3521..d1c3b23 100644
--- a/toke.c
+++ b/toke.c
@@ -9577,9 +9577,10 @@ S_scan_heredoc(pTHX_ char *s)
 		goto streaming;
 	    }
 	  }
-	else {	/* eval */
+	else {	/* eval or we've already hit EOF */
 	    s = (char*)memchr((void*)s, '\n', PL_bufend - s);
-	    assert(s);
+	    if (!s)
+                goto interminable;
 	}
 	linestr = shared->ls_linestr;
 	bufend = SvEND(linestr);
-- 
2.1.4


```
</details>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue Jan 19 20&#8203;:36&#8203;:15 2016\, tonyc wrote&#8203;:
> On Fri Jul 03 09&#8203;:57&#8203;:24 2015\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> > While fuzzing Perl built from git source \(v5\.23\.0\-69\-gf907dd3\)\, I came
> > across the following "script" that causes an assertion failure at
> > toke\.c&#8203;:9314&#8203;:
> > 
> > geeknik@&#8203;h5n2&#8203;:\~$ ~/perl/perl test03\-min
> > $\# is no longer supported at test03\-min line 1\.
> > Use of bare \<\< to mean \<\<"" is deprecated at test03\-min line 1\.
> > perl&#8203;: toke\.c&#8203;:9314&#8203;: S\_scan\_heredoc&#8203;: Assertion \`s' failed\.
> > Aborted
> 
> The attached should fix this\.

Applied to blead as 23c4e91245a43fb7bbe5215e27ca989e3b410552\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @tonycoz

On Sat Dec 05 01&#8203;:36&#8203;:33 2015\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> Maybe a dupe of 125540?

Yes\, it's a duplicate\, the fix for 125540 fixes this\.

Tony

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for submitting this report\.  You have helped make Perl better\.
&nbsp;    
With the release of Perl 5\.24\.0 on May 9\, 2016\, this and 149 other issues have been resolved\.

Perl 5\.24\.0 may be downloaded via https://metacpan.org/release/RJBS/perl-5.24.0

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
