### ISSUE TITLE
Perl_sv_clear: Assertion `((svtype)((sv)->sv_flags & 0xff)) != (svtype)0xff' failed (sv.c:6395)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14785]
Migrated from [rt.perl.org#125534](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=125534) (status was 'open')

Searchable as RT125534$

**Comment by p5pRT** [comment]
### From @geeknik

While fuzzing Perl built from git source \(v5\.23\.0\-69\-gf907dd3\)\, I came across the following "script" that causes an assertion failure at sv\.c&#8203;:6395\.

perl \-e 'map\{%0=map\{0\}m 0 0\}%0=map\{0\}0'

It also causes Perl v5\.21\.6\-602\-ge9d2bd8 to segfault at sv\.c&#8203;:5837\.

\#0  S\_sv\_unmagicext\_flags \(sv=sv@&#8203;entry=0xe3a710\, type=type@&#8203;entry=60\, vtbl=vtbl@&#8203;entry=0x0\, 
&nbsp;    flags=flags@&#8203;entry=0\) at sv\.c&#8203;:5837
\#1  0x00000000007b7321 in S\_sv\_unmagicext\_flags \(flags=0\, vtbl=0x0\, type=60\, sv=0xe3a710\) at sv\.c&#8203;:5832
\#2  Perl\_sv\_unmagic \(type=60\, sv=0xe3a710\) at sv\.c&#8203;:5879
\#3  Perl\_sv\_clear \(orig\_sv=orig\_sv@&#8203;entry=0xe3a710\) at sv\.c&#8203;:6511
\#4  0x00000000007b1118 in Perl\_sv\_free2 \(sv=0xe3a710\, rc=\<optimized out>\) at sv\.c&#8203;:6972
\#5  0x00000000008baabd in S\_SvREFCNT\_dec \(sv=\<optimized out>\) at inline\.h&#8203;:166
\#6  Perl\_leave\_scope \(base=3\) at scope\.c&#8203;:866
\#7  0x00000000008ef0f0 in Perl\_pp\_mapwhile \(\) at pp\_ctl\.c&#8203;:1067
\#8  0x0000000000775a6b in Perl\_runops\_standard \(\) at run\.c&#8203;:41
\#9  0x00000000004f3dbf in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2421
\#10 perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2344
\#11 0x000000000042ab1c in main \(argc=2\, argv=0x7fffffffe3a8\, env=0x7fffffffe3c0\) at perlmain\.c&#8203;:116
\#12 0x00007ffff6f98ead in \_\_libc\_start\_main \(main=\<optimized out>\, argc=\<optimized out>\, 
&nbsp;    ubp\_av=\<optimized out>\, init=\<optimized out>\, fini=\<optimized out>\, rtld\_fini=\<optimized out>\, 
&nbsp;    stack\_end=0x7fffffffe398\) at libc\-start\.c&#8203;:244
\#13 0x000000000042ab95 in \_start \(\)

**Comment by p5pRT** [comment]
### From @rjbs

\* Brian Carpenter \<perlbug\-followup@&#8203;perl\.org> \[2015\-07\-02T14&#8203;:29&#8203;:46\]
> While fuzzing Perl built from git source \(v5\.23\.0\-69\-gf907dd3\)\, I came across
> the following "script" that causes an assertion failure at sv\.c&#8203;:6395\.

We have a small backlog of tickets of this sort&#8203;: fuzzing leading to assertion
failures\, segvs\, etc\.

Is it worth organizing these under a meta\-ticket for tracking as one or more
category?

\-\- 
rjbs

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @dcollinsn

I have a local text file to categorize the tickets I have opened of this
type\, with a one line description of each\. For example&#8203;:

\*Assert fails without other symptoms
\*\*NEW   126257 op\.c      2762  \`\(o\->op\_flags & 3\) \!= 1'
&nbsp;   0/x$0my@&#8203;m&#8203;:d
\*\*NEW   126258 op\.c      717   \`\!\(o\->op\_private &
~PL\_op\_private\_valid\[type\]\)' grep$0\,0\}
\*\*NEW   126260 regexec\.c 5389  \`\(\(\(U8\)\(\*l\) & 0xfe\) == 0xc2\)'
&nbsp;    /0\\G|0\+|/>>s>>\\x\{100\}>>s>>>g/0
\*\*NEW   126261 sv\.c      11449 \`\(IV\)elen >= 0'
&nbsp;    /00000000/0?s>>000000000000000000000000>g
x/0000000000000\[0000000▒0000000000\[\.00\./i\\0000
\*\*FIXED 126404 regcomp\.c 13810 \`\(\! \(\(current\)\->sv\_flags & 0x00000100\)\)'
&nbsp;   00\./\(?\[\!\(\)\]\)/
\*\*      ?????? pp\_sys\.c  690   \`\(\(\(\(rgv\)\->sv\_flags &
\(0x00004000|0x00008000\)\)' pipe$$5\,0

A meta\-ticket could track all the open ones\, but it might be more helpful
for triage if all fuzzers \(and static analysis users\, perhaps?\) were to
make this information available in a more centralized fashion \(where
multiple users can edit it\)\. Is there a suitable place to do that? Failing
all else\, a Google spreadsheet perhaps?

\-\-
Dan

On Tue\, Oct 27\, 2015 at 10&#8203;:30 PM\, Ricardo Signes \<perl\.p5p@&#8203;rjbs\.manxome\.org>
wrote&#8203;:

> \* Brian Carpenter \<perlbug\-followup@&#8203;perl\.org> \[2015\-07\-02T14&#8203;:29&#8203;:46\]
> > While fuzzing Perl built from git source \(v5\.23\.0\-69\-gf907dd3\)\, I came
> across
> > the following "script" that causes an assertion failure at sv\.c&#8203;:6395\.
>
> We have a small backlog of tickets of this sort&#8203;: fuzzing leading to
> assertion
> failures\, segvs\, etc\.
>
> Is it worth organizing these under a meta\-ticket for tracking as one or
> more
> category?
>
> \-\-
> rjbs
>

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Jul 02\, 2015 at 11&#8203;:29&#8203;:46AM \-0700\, Brian Carpenter wrote&#8203;:
> perl \-e 'map\{%0=map\{0\}m 0 0\}%0=map\{0\}0'
> 
> It also causes Perl v5\.21\.6\-602\-ge9d2bd8 to segfault at sv\.c&#8203;:5837\.

It's another stack\-not\-refocunted issue\.

\-\- 
A walk of a thousand miles begins with a single step\.\.\.
then continues for another 1\,999\,999 or so\.
