### ISSUE TITLE
S_gv_stashpvn_internal: Assertion `((svtype)((_gvgp)->sv_flags & 0xff)) == SVt_PVGV || ((svtype)((_gvgp)->sv_flags & 0xff)) == SVt_PVLV' failed (gv.c:1416)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14790]
Migrated from [rt.perl.org#125541](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=125541) (status was 'resolved')

Searchable as RT125541$

**Comment by p5pRT** [comment]
### From @geeknik

The attached script causes an assertion failure in Perl v5\.23\.0\-69\-gf907dd3\. Does not crash or cause any errors in Perl 5\.21\.6\-602\-ge9d2bd8\.

perl&#8203;: gv\.c&#8203;:1416&#8203;: S\_gv\_stashpvn\_internal&#8203;: Assertion \`\(\(svtype\)\(\(\_gvgp\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_gvgp\)\->sv\_flags & 0xff\)\) == SVt\_PVLV' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6d90165 in \*\_\_GI\_raise \(sig=\<optimized out>\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:64
64    \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;: No such file or directory\.
\(gdb\) bt
\#0  0x00007ffff6d90165 in \*\_\_GI\_raise \(sig=\<optimized out>\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:64
\#1  0x00007ffff6d933e0 in \*\_\_GI\_abort \(\) at abort\.c&#8203;:92
\#2  0x00007ffff6d89311 in \*\_\_GI\_\_\_assert\_fail \(
&nbsp;    assertion=0xeb4b30 "\(\(svtype\)\(\(\_gvgp\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_gvgp\)\->sv\_flags & 0xff\)\) == SVt\_PVLV"\, file=\<optimized out>\, line=1416\, function=0xef2580 "S\_gv\_stashpvn\_internal"\)
&nbsp;    at assert\.c&#8203;:81
\#3  0x0000000000562d15 in Perl\_gv\_stashsv \(\) at gv\.c&#8203;:1416
\#4  0x0000000000907453 in Perl\_pp\_method\_redir \(\) at pp\_hot\.c&#8203;:3583
\#5  0x00000000007cdfcf in Perl\_runops\_debug \(\) at dump\.c&#8203;:2224
\#6  0x000000000053c819 in perl\_run \(\)
\#7  0x000000000042af18 in main \(\) at perlmain\.c&#8203;:116
\(gdb\) i r
rax            0x0    0
rbx            0x7fffffffe624    140737488348708
rcx            0xffffffffffffffff    \-1
rdx            0x6    6
rsi            0xeead    61101
rdi            0xeead    61101
rbp            0x7ffff6ea9c67    0x7ffff6ea9c67
rsp            0x7fffffffde58    0x7fffffffde58
r8             0x7ffff7fdc700    140737353991936
r9             0x564c56505f745653    6218440088690644563
r10            0x8    8
r11            0x202    514
r12            0xeb4b30    15420208
r13            0xef2580    15672704
r14            0x7ffff6ea9c67    140737335958631
r15            0x588    1416
rip            0x7ffff6d90165    0x7ffff6d90165 \<\*\_\_GI\_raise\+53>
eflags         0x202    \[ IF \]
cs             0x33    51
ss             0x2b    43
ds             0x0    0
es             0x0    0
fs             0x0    0
gs             0x0    0

**Comment by p5pRT** [comment]
### From @geeknik

[test28-min](https://rt-archive.perl.org/perl5/Ticket/Attachment/1355920/725066/test28-min)

**Comment by p5pRT** [comment]
### From @cpansprout

On Fri Jul 03 10&#8203;:03&#8203;:56 2015\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> The attached script causes an assertion failure in Perl v5\.23\.0\-69\-
> gf907dd3\. Does not crash or cause any errors in Perl 5\.21\.6\-602\-
> ge9d2bd8\.

When I try bisecting\, it crashes for all perls I can compile\.

Here is my one\-liner version&#8203;:

$ \./miniperl \-e '%&#8203;::=\(\); J\->$\{\\"&#8203;::"\}'

gv\_fetchpvn\_flags assumes that $&#8203;::\{"main&#8203;::"\} holds a GV\.  If it does not\, things go awry\.  %&#8203;::=\(\) is what wipes $&#8203;::\{"main&#8203;::"\}\.  So the solution would be to restore \*main&#8203;:: somewhere\, but I am not sure which would be the best place to do it\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

Fixed in d2fcb1d\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
