### ISSUE TITLE
Perl segfaults with a regex_sets error message

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14851]
Migrated from [rt.perl.org#125805](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=125805) (status was 'resolved')

Searchable as RT125805$

**Comment by p5pRT** [comment]
### From @dcollinsn

The search on this bug tracker doesn't seem to search issue descriptions\, but in any event I can't figure out how to tell if this is a duplicate or not\. Searches for the test case\, regex\_sets\, segfault\, and the first bad revision id didn't reveal any obvious duplicates\.

Test case is the 12\-byte file&#8203;:

00\./\(?\[\(\)\]\)/

dcollins@&#8203;nagios&#8203;:/usr/local/perl\-afl/out/allcrash$ \.\./\.\./bin/perl \-w f2i000041
The regex\_sets feature is experimental in regex; marked by \<\-\- HERE in m/\(?\[ \<\-\- HERE \(\)\]\)/ at f2i000041 line 1\.
Segmentation fault

Git bisect revealed&#8203;:

6798c95dd27b33efd71f394c18649af7bbaf42b7 is the first bad commit
commit 6798c95dd27b33efd71f394c18649af7bbaf42b7
Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
Date&#8203;:   Wed Feb 25 23&#8203;:19&#8203;:39 2015 \-0700

&nbsp;    Change /\(?\[\.\.\.\]\) to have normal operator precedence
&nbsp;    
&nbsp;    This experimental feature now has the intersection operator \("&"\) higher
&nbsp;    precedence than the other binary operators\.

:100644 100644 ce36c6c64ad7f52f32f18c3af5faea7782e77f8f a909f7d5bc6cacd8ecd0e292d17587460c2dabf5 M    embed\.fnc
:100644 100644 acbd1ea23a511c4a9573674d10dc6e8577bac513 4d9ca18439ad72b5d955b46ab4fc1ae60fbdab9e M    embed\.h
:040000 040000 abe9c29891251f534ae7654827701484c00e5d5a 56738de91977828568e55a1fa42af9d52602a07c M    pod
:100644 100644 4bc200dae6b4e45492c0aa6dd8724e44175e1180 f45a4a36173bc16a1e8c9491298708ef75e252a7 M    proto\.h
:100644 100644 d736a0131ac2c50c3753ddd332b3fc524ebe7514 51065d58f2df92a3a2e1ccd520280f4c9e62c952 M    regcomp\.c
:040000 040000 90b8d23d6c4c6de5357d08f14baf1f1e201274c1 487395998bc1558eb521b752f277bac3bdb8e770 M    t
bisect run success

dcollins@&#8203;nagios&#8203;:/usr/local/perl\-afl/out/allcrash$ \.\./\.\./bin/perl \-V
Summary of my perl5 \(revision 5 version 23 subversion 2\) configuration&#8203;:
&nbsp;  Derived from&#8203;: 9728ed0a4dcaca9d7fddf6ce9c5736ed3aacd487
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.32\-5\-686\, archname=i686\-linux\-64int\-ld
&nbsp;    uname='linux nagios 2\.6\.32\-5\-686 \#1 smp tue may 13 16&#8203;:33&#8203;:32 utc 2014 i686 gnulinux '
&nbsp;    config\_args=''
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=undef\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='afl\-gcc'\, ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.4\.5'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12\, longdblkind=3
&nbsp;    ivtype='long long'\, ivsize=8\, nvtype='long double'\, nvsize=12\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='afl\-gcc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/i486\-linux\-gnu/4\.4\.5/include\-fixed /usr/lib /lib/\.\./lib /usr/lib/\.\./lib /lib /usr/lib/i486\-linux\-gnu /usr/lib64
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.11\.3\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.11\.3'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV USE\_64\_BIT\_INT USE\_LARGE\_FILES
&nbsp;                        USE\_LOCALE USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Locally applied patches&#8203;:
&nbsp;    uncommitted\-changes
&nbsp;  Built under linux
&nbsp;  Compiled at Aug 11 2015 16&#8203;:38&#8203;:21
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.2/i686\-linux\-64int\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.2
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.2/i686\-linux\-64int\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.2
&nbsp;    \.

\(gdb\) run
Starting program&#8203;: /usr/local/perl\-afl/bin/perl f2i000041
\[Thread debugging using libthread\_db enabled\]
The regex\_sets feature is experimental in regex; marked by \<\-\- HERE in m/\(?\[ \<\-\- HERE \(\)\]\)/ at f2i000041 line 1\.

Program received signal SIGSEGV\, Segmentation fault\.
0x0827543e in S\_invlist\_iterinit \(pRExC\_state=0xbffff024\, 
&nbsp;    return\_invlist=\<value optimized out>\, flagp=\<value optimized out>\, 
&nbsp;    depth=5\, oregcomp\_parse=0x8743a39 "?\[\(\)\]\)"\) at regcomp\.c&#8203;:9122
9122        \*get\_invlist\_iter\_addr\(invlist\) = 0;
\(gdb\) bt
\#0  0x0827543e in S\_invlist\_iterinit \(pRExC\_state=0xbffff024\, 
&nbsp;    return\_invlist=\<value optimized out>\, flagp=\<value optimized out>\, 
&nbsp;    depth=5\, oregcomp\_parse=0x8743a39 "?\[\(\)\]\)"\) at regcomp\.c&#8203;:9122
\#1  S\_handle\_regex\_sets \(pRExC\_state=0xbffff024\, 
&nbsp;    return\_invlist=\<value optimized out>\, flagp=\<value optimized out>\, 
&nbsp;    depth=5\, oregcomp\_parse=0x8743a39 "?\[\(\)\]\)"\) at regcomp\.c&#8203;:13943
\#2  0x0825702d in S\_reg \(pRExC\_state=0xbffff024\, paren=\<value optimized out>\, 
&nbsp;    flagp=\<value optimized out>\, depth=5\) at regcomp\.c&#8203;:10427
\#3  0x08278abe in S\_regatom \(pRExC\_state=0xbffff024\, 
&nbsp;    flagp=\<value optimized out>\, depth=\<value optimized out>\)
&nbsp;    at regcomp\.c&#8203;:11733
\#4  S\_regpiece \(pRExC\_state=0xbffff024\, flagp=\<value optimized out>\, 
&nbsp;    depth=\<value optimized out>\) at regcomp\.c&#8203;:10808
\#5  0x0828636d in S\_regbranch \(pRExC\_state=0xbffff024\, flagp=0xbfffee18\, 
&nbsp;    first=\<value optimized out>\, depth=2\) at regcomp\.c&#8203;:10733
\#6  0x0824fb4b in S\_reg \(pRExC\_state=0xbffff024\, paren=\<value optimized out>\, 
&nbsp;    flagp=\<value optimized out>\, depth=1\) at regcomp\.c&#8203;:10483
\#7  0x0828a000 in Perl\_re\_op\_compile \(patternp=0x0\, pat\_count=0\, 
&nbsp;    expr=0x8743914\, eng=0x870a420\, old\_re=0x0\, is\_bare\_re=0x0\, 
&nbsp;    orig\_rx\_flags=0\, pm\_flags=0\) at regcomp\.c&#8203;:6881
\#8  0x080d50a8 in Perl\_pmruntime \(o=0x8743934\, expr=0x8743914\, repl=0x0\, 
&nbsp;    isreg=true\, floor=0\) at op\.c&#8203;:5579
\#9  0x081ce568 in Perl\_yyparse \(gramtype=258\) at perly\.y&#8203;:1038
\#10 0x0810f4af in S\_parse\_body \(env=\<value optimized out>\, 
&nbsp;    xsinit=\<value optimized out>\) at perl\.c&#8203;:2296
\#11 0x081128c9 in perl\_parse \(my\_perl=0x8729008\, xsinit=0x8065dc0 \<xs\_init>\, 
&nbsp;    argc=2\, argv=0xbffff4e4\, env=0x0\) at perl\.c&#8203;:1626
\#12 0x08065b85 in main \(argc=2\, argv=0xbffff4e4\, env=0xbffff4f0\)
&nbsp;    at perlmain\.c&#8203;:114
\(gdb\) l
9117    PERL\_STATIC\_INLINE void
9118    S\_invlist\_iterinit\(SV\* invlist\)    /\* Initialize iterator for invlist \*/
9119    \{
9120        PERL\_ARGS\_ASSERT\_INVLIST\_ITERINIT;
9121    
9122        \*get\_invlist\_iter\_addr\(invlist\) = 0;
9123    \}
9124    
9125    PERL\_STATIC\_INLINE void
9126    S\_invlist\_iterfinish\(SV\* invlist\)
\(gdb\) 

==1344== Memcheck\, a memory error detector
==1344== Copyright \(C\) 2002\-2010\, and GNU GPL'd\, by Julian Seward et al\.
==1344== Using Valgrind\-3\.6\.0\.SVN\-Debian and LibVEX; rerun with \-h for copyright info
==1344== Command&#8203;: \.\./\.\./bin/perl f2i000041
==1344== 
The regex\_sets feature is experimental in regex; marked by \<\-\- HERE in m/\(?\[ \<\-\- HERE \(\)\]\)/ at f2i000041 line 1\.
==1344== Invalid write of size 4
==1344==    at 0x827543E&#8203;: S\_handle\_regex\_sets \(regcomp\.c&#8203;:9122\)
==1344==    by 0x825702C&#8203;: S\_reg \(regcomp\.c&#8203;:10427\)
==1344==    by 0x8278ABD&#8203;: S\_regpiece \(regcomp\.c&#8203;:11733\)
==1344==    by 0x828636C&#8203;: S\_regbranch \(regcomp\.c&#8203;:10733\)
==1344==    by 0x824FB4A&#8203;: S\_reg \(regcomp\.c&#8203;:10483\)
==1344==    by 0x8289FFF&#8203;: Perl\_re\_op\_compile \(regcomp\.c&#8203;:6881\)
==1344==    by 0x80D50A7&#8203;: Perl\_pmruntime \(op\.c&#8203;:5579\)
==1344==    by 0x81CE567&#8203;: Perl\_yyparse \(perly\.y&#8203;:1038\)
==1344==    by 0x810F4AE&#8203;: S\_parse\_body \(perl\.c&#8203;:2296\)
==1344==    by 0x81128C8&#8203;: perl\_parse \(perl\.c&#8203;:1626\)
==1344==    by 0x8065B84&#8203;: main \(perlmain\.c&#8203;:114\)
==1344==  Address 0x18 is not stack'd\, malloc'd or \(recently\) free'd
==1344== 
==1344== 
==1344== Process terminating with default action of signal 11 \(SIGSEGV\)
==1344==  Access not within mapped region at address 0x18
==1344==    at 0x827543E&#8203;: S\_handle\_regex\_sets \(regcomp\.c&#8203;:9122\)
==1344==    by 0x825702C&#8203;: S\_reg \(regcomp\.c&#8203;:10427\)
==1344==    by 0x8278ABD&#8203;: S\_regpiece \(regcomp\.c&#8203;:11733\)
==1344==    by 0x828636C&#8203;: S\_regbranch \(regcomp\.c&#8203;:10733\)
==1344==    by 0x824FB4A&#8203;: S\_reg \(regcomp\.c&#8203;:10483\)
==1344==    by 0x8289FFF&#8203;: Perl\_re\_op\_compile \(regcomp\.c&#8203;:6881\)
==1344==    by 0x80D50A7&#8203;: Perl\_pmruntime \(op\.c&#8203;:5579\)
==1344==    by 0x81CE567&#8203;: Perl\_yyparse \(perly\.y&#8203;:1038\)
==1344==    by 0x810F4AE&#8203;: S\_parse\_body \(perl\.c&#8203;:2296\)
==1344==    by 0x81128C8&#8203;: perl\_parse \(perl\.c&#8203;:1626\)
==1344==    by 0x8065B84&#8203;: main \(perlmain\.c&#8203;:114\)
==1344==  If you believe this happened as a result of a stack
==1344==  overflow in your program's main thread \(unlikely but
==1344==  possible\)\, you can try to increase the size of the
==1344==  main thread stack using the \-\-main\-stacksize= flag\.
==1344==  The main thread stack size used in this run was 8388608\.
==1344== 
==1344== HEAP SUMMARY&#8203;:
==1344==     in use at exit&#8203;: 115\,550 bytes in 667 blocks
==1344==   total heap usage&#8203;: 754 allocs\, 87 frees\, 120\,444 bytes allocated
==1344== 
==1344== LEAK SUMMARY&#8203;:
==1344==    definitely lost&#8203;: 168 bytes in 1 blocks
==1344==    indirectly lost&#8203;: 2\,683 bytes in 40 blocks
==1344==      possibly lost&#8203;: 12\,878 bytes in 293 blocks
==1344==    still reachable&#8203;: 99\,821 bytes in 333 blocks
==1344==         suppressed&#8203;: 0 bytes in 0 blocks
==1344== Rerun with \-\-leak\-check=full to see details of leaked memory
==1344== 
==1344== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==1344== ERROR SUMMARY&#8203;: 1 errors from 1 contexts \(suppressed&#8203;: 25 from 8\)
Segmentation fault

**Comment by p5pRT** [comment]
### From @khwilliamson

Thanks for reporting this\.  I'll fix it
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thanks for finding and reporting this\.  Now fixed in blead by commit
e7cce976d7dd1f4fda1f387d02c6403f43346e9c
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
@mauke - Status changed from 'pending release' to 'resolved'
