### ISSUE TITLE
Segfault on bareword as loop index

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14886]
Migrated from [rt.perl.org#125972](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=125972) (status was 'resolved')

Searchable as RT125972$

**Comment by p5pRT** [comment]
### From internationils@gmx.net


This is a bug report for perl from internationils@&#8203;gmx\.net\,
generated with the help of perlbug 1\.40 running under perl 5\.20\.2\.

\#\!/usr/bin/perl
\# This is perl 5\, version 20\, subversion 2 \(v5\.20\.2\) built for x86\_64\-linux\-gnu\-thread\-multi
\# \(with 42 registered patches\, see perl \-V for more detail\)

use strict;
use warnings;

sub something \{ my $subvar= shift; \}
my $table="";
my @&#8203;tablename = \("tix\_ALL"\, "tix\_2"\, "tix\_3"\);
my $loop=0;

$table = something\("$tablename\[$loop\]\_table"\);
something\("\./$table\.csv"\) if\(0\);
\#SEGFAULT HERE due to 'loop' instead of '$loop'
print "Writing table $tablename\[loop\]\\n";


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=low


---
Site configuration information for perl 5\.20\.2&#8203;:

Configured by Debian Project at Sun May  3 16&#8203;:16&#8203;:25 UTC 2015\.

Summary of my perl5 \(revision 5 version 20 subversion 2\) configuration&#8203;:
&nbsp;   
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.2\.0\-4\-amd64\, archname=x86\_64\-linux\-gnu\-thread\-multi
&nbsp;    uname='linux x86\-csail\-01 3\.2\.0\-4\-amd64 \#1 smp debian 3\.2\.68\-1\+deb7u1 x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN \-D\_FORTIFY\_SOURCE=2 \-g \-O2 \-fstack\-protector\-strong \-Wformat \-Werror=format\-security \-Dldflags= \-Wl\,\-z\,relro \-Dlddlflags=\-shared \-Wl\,\-z\,relro \-Dcccdlflags=\-fPIC \-Darchname=x86\_64\-linux\-gnu \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.20 \-Darchlib=/usr/lib/x86\_64\-linux\-gnu/perl/5\.20 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/x86\_64\-linux\-gnu/perl5/5\.20 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.20\.2 \-Dsitearch=/usr/local/lib/x86\_64\-linux\-gnu/perl/5\.20\.2 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1 \-Dsiteman3dir=/usr/local/man/man3 \-Duse64bitint \-Dman1ext=1 \-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Ud\_ualarm \-Uusesfio \-Uusenm \-Ui\_libutil \-Uversiononly \-DDEBUGGING=\-g \-Doptimize=\-O2 \-Duseshrplib \-Dlibperl=libperl\.so\.5\.20\.2 \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fwrapv \-fno\-strict\-aliasing \-pipe \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2 \-g'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fwrapv \-fno\-strict\-aliasing \-pipe \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.9\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/4\.9/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.20
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-L/usr/local/lib \-fstack\-protector'

Locally applied patches&#8203;:
&nbsp;    DEBPKG&#8203;:debian/cpan\_definstalldirs \- Provide a sensible INSTALLDIRS default for modules installed from CPAN\.
&nbsp;    DEBPKG&#8203;:debian/db\_file\_ver \- http&#8203;://bugs\.debian\.org/340047 Remove overly restrictive DB\_File version check\.
&nbsp;    DEBPKG&#8203;:debian/doc\_info \- Replace generic man\(1\) instructions with Debian\-specific information\.
&nbsp;    DEBPKG&#8203;:debian/enc2xs\_inc \- http&#8203;://bugs\.debian\.org/290336 Tweak enc2xs to follow symlinks and ignore missing @&#8203;INC directories\.
&nbsp;    DEBPKG&#8203;:debian/errno\_ver \- http&#8203;://bugs\.debian\.org/343351 Remove Errno version check due to upgrade problems with long\-running processes\.
&nbsp;    DEBPKG&#8203;:debian/libperl\_embed\_doc \- http&#8203;://bugs\.debian\.org/186778 Note that libperl\-dev package is required for embedded linking
&nbsp;    DEBPKG&#8203;:fixes/respect\_umask \- Respect umask during installation
&nbsp;    DEBPKG&#8203;:debian/writable\_site\_dirs \- Set umask approproately for site install directories
&nbsp;    DEBPKG&#8203;:debian/extutils\_set\_libperl\_path \- EU&#8203;:MM&#8203;: set location of libperl\.a under /usr/lib
&nbsp;    DEBPKG&#8203;:debian/no\_packlist\_perllocal \- Don't install \.packlist or perllocal\.pod for perl or vendor
&nbsp;    DEBPKG&#8203;:debian/prefix\_changes \- Fiddle with \*PREFIX and variables written to the makefile
&nbsp;    DEBPKG&#8203;:debian/fakeroot \- Postpone LD\_LIBRARY\_PATH evaluation to the binary targets\.
&nbsp;    DEBPKG&#8203;:debian/instmodsh\_doc \- Debian policy doesn't install \.packlist files for core or vendor\.
&nbsp;    DEBPKG&#8203;:debian/ld\_run\_path \- Remove standard libs from LD\_RUN\_PATH as per Debian policy\.
&nbsp;    DEBPKG&#8203;:debian/libnet\_config\_path \- Set location of libnet\.cfg to /etc/perl/Net as /usr may not be writable\.
&nbsp;    DEBPKG&#8203;:debian/mod\_paths \- Tweak @&#8203;INC ordering for Debian
&nbsp;    DEBPKG&#8203;:debian/module\_build\_man\_extensions \- http&#8203;://bugs\.debian\.org/479460 Adjust Module&#8203;::Build manual page extensions for the Debian Perl policy
&nbsp;    DEBPKG&#8203;:debian/prune\_libs \- http&#8203;://bugs\.debian\.org/128355 Prune the list of libraries wanted to what we actually need\.
&nbsp;    DEBPKG&#8203;:fixes/net\_smtp\_docs \- \[rt\.cpan\.org \#36038\] http&#8203;://bugs\.debian\.org/100195 Document the Net&#8203;::SMTP 'Port' option
&nbsp;    DEBPKG&#8203;:debian/perlivp \- http&#8203;://bugs\.debian\.org/510895 Make perlivp skip include directories in /usr/local
&nbsp;    DEBPKG&#8203;:debian/deprecate\-with\-apt \- http&#8203;://bugs\.debian\.org/747628 Point users to Debian packages of deprecated core modules
&nbsp;    DEBPKG&#8203;:debian/squelch\-locale\-warnings \- http&#8203;://bugs\.debian\.org/508764 Squelch locale warnings in Debian package maintainer scripts
&nbsp;    DEBPKG&#8203;:debian/skip\-upstream\-git\-tests \- Skip tests specific to the upstream Git repository
&nbsp;    DEBPKG&#8203;:debian/patchlevel \- http&#8203;://bugs\.debian\.org/567489 List packaged patches for 5\.20\.2\-3\+deb8u1 in patchlevel\.h
&nbsp;    DEBPKG&#8203;:debian/skip\-kfreebsd\-crash \- http&#8203;://bugs\.debian\.org/628493 \[perl \#96272\] Skip a crashing test case in t/op/threads\.t on GNU/kFreeBSD
&nbsp;    DEBPKG&#8203;:fixes/document\_makemaker\_ccflags \- http&#8203;://bugs\.debian\.org/628522 \[rt\.cpan\.org \#68613\] Document that CCFLAGS should include $Config\{ccflags\}
&nbsp;    DEBPKG&#8203;:debian/find\_html2text \- http&#8203;://bugs\.debian\.org/640479 Configure CPAN&#8203;::Distribution with correct name of html2text
&nbsp;    DEBPKG&#8203;:debian/perl5db\-x\-terminal\-emulator\.patch \- http&#8203;://bugs\.debian\.org/668490 Invoke x\-terminal\-emulator rather than xterm in perl5db\.pl
&nbsp;    DEBPKG&#8203;:debian/cpan\-missing\-site\-dirs \- http&#8203;://bugs\.debian\.org/688842 Fix CPAN&#8203;::FirstTime defaults with nonexisting site dirs if a parent is writable
&nbsp;    DEBPKG&#8203;:fixes/memoize\_storable\_nstore \- \[rt\.cpan\.org \#77790\] http&#8203;://bugs\.debian\.org/587650 Memoize&#8203;::Storable&#8203;: respect 'nstore' option not respected
&nbsp;    DEBPKG&#8203;:debian/regen\-skip \- Skip a regeneration check in unrelated git repositories
&nbsp;    DEBPKG&#8203;:fixes/regcomp\-mips\-optim \- \[perl \#122817\] http&#8203;://bugs\.debian\.org/754054 Downgrade the optimization of regcomp\.c on mips and mipsel due to a gcc\-4\.9 bug
&nbsp;    DEBPKG&#8203;:debian/makemaker\-pasthru \- http&#8203;://bugs\.debian\.org/758471 Pass LD settings through to subdirectories
&nbsp;    DEBPKG&#8203;:fixes/perldoc\-less\-R \- \[rt\.cpan\.org \#98636\] http&#8203;://bugs\.debian\.org/758689 Tell the 'less' pager to allow terminal escape sequences
&nbsp;    DEBPKG&#8203;:fixes/pod\_man\_reproducible\_date \- http&#8203;://bugs\.debian\.org/759405 Support POD\_MAN\_DATE in Pod&#8203;::Man for the left\-hand footer
&nbsp;    DEBPKG&#8203;:fixes/io\_uncompress\_gunzip\_inmemory \- http&#8203;://bugs\.debian\.org/747363 \[rt\.cpan\.org \#95494\] Fix gunzip to in\-memory file handle
&nbsp;    DEBPKG&#8203;:fixes/socket\_test\_recv\_fix \- http&#8203;://bugs\.debian\.org/758718 \[perl \#122657\] Compare recv return value to peername in socket test
&nbsp;    DEBPKG&#8203;:fixes/hurd\_socket\_recv\_todo \- http&#8203;://bugs\.debian\.org/758718 \[perl \#122657\] TODO checking the result of recv\(\) on hurd
&nbsp;    DEBPKG&#8203;:fixes/regexp\-performance \- \[0fa70a0\] http&#8203;://bugs\.debian\.org/777556 \[perl \#123743\] simpify and speed up /\.\*\.\.\./ handling
&nbsp;    DEBPKG&#8203;:fixes/failed\_require\_diagnostics \- http&#8203;://bugs\.debian\.org/781120 \[perl \#123270\] Report inaccesible file on failed require
&nbsp;    DEBPKG&#8203;:fixes/array\-cloning \- http&#8203;://bugs\.debian\.org/779357 \[perl \#124127\] \[902d169\] fix cloning arrays with unused elements
&nbsp;    DEBPKG&#8203;:fixes/perldb\-threads \- http&#8203;://bugs\.debian\.org/779357 \[perl \#124127\] \[41ef2c6\] lib/perl5db\.pl&#8203;: Restore noop lock prototype



---
@&#8203;INC for perl 5\.20\.2&#8203;:
&nbsp;    /home/nils/perl5/lib/perl5/x86\_64\-linux\-gnu\-thread\-multi
&nbsp;    /home/nils/perl5/lib/perl5
&nbsp;    /etc/perl
&nbsp;    /usr/local/lib/x86\_64\-linux\-gnu/perl/5\.20\.2
&nbsp;    /usr/local/share/perl/5\.20\.2
&nbsp;    /usr/lib/x86\_64\-linux\-gnu/perl5/5\.20
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/x86\_64\-linux\-gnu/perl/5\.20
&nbsp;    /usr/share/perl/5\.20
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    \.



---
Environment for perl 5\.20\.2&#8203;:
&nbsp;    HOME=/home/nils
&nbsp;    LANG=C
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/nils/perl5/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/local/games&#8203;:/usr/games
&nbsp;    PERL5LIB=/home/nils/perl5/lib/perl5
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    PERL\_LOCAL\_LIB\_ROOT=/home/nils/perl5
&nbsp;    PERL\_MB\_OPT=\-\-install\_base "/home/nils/perl5"
&nbsp;    PERL\_MM\_OPT=INSTALL\_BASE=/home/nils/perl5
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @nicomen

$ gdb \-\-args perl \-e '30; "$a\[b\]";'
GNU gdb \(Ubuntu 7\.10\-0ubuntu1\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from perl\.\.\.Reading symbols from /usr/lib/debug//usr/bin/perl\.\.\.done\.
done\.
\(gdb\) run
Starting program&#8203;: /usr/bin/perl \-e 30\\;\\ \\"\\$a\\\[b\\\]\\"\\;
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.

Program received signal SIGSEGV\, Segmentation fault\.
0x000000000052ffe1 in Perl\_my\_atof \(my\_perl=my\_perl@&#8203;entry=0x7a9010\, s=0x7d8f40 "b"\) at numeric\.c&#8203;:857
857    numeric\.c&#8203;: No such file or directory\.
\(gdb\) bt
\#0  0x000000000052ffe1 in Perl\_my\_atof \(my\_perl=my\_perl@&#8203;entry=0x7a9010\, s=0x7d8f40 "b"\) at numeric\.c&#8203;:857
\#1  0x00000000004c50e1 in S\_sv\_2iuv\_common \(my\_perl=my\_perl@&#8203;entry=0x7a9010\, sv=sv@&#8203;entry=0x7d3c70\) at sv\.c&#8203;:2214
\#2  0x00000000004c578b in Perl\_sv\_2iv\_flags \(my\_perl=my\_perl@&#8203;entry=0x7a9010\, sv=0x7d3c70\, flags=flags@&#8203;entry=2\) at sv\.c&#8203;:2404
\#3  0x000000000042bac5 in Perl\_rpeep \(my\_perl=0x7a9010\, o=0x7d8cc0\) at op\.c&#8203;:11814
\#4  0x00000000004266fc in Perl\_newPROG \(my\_perl=0x7a9010\, o=0x7d8d00\) at op\.c&#8203;:3361
\#5  0x0000000000465735 in Perl\_yyparse \(my\_perl=0x7a9010\, gramtype=8223088\) at perly\.y&#8203;:147
\#6  0x000000000043cd0d in S\_parse\_body \(xsinit=0x41bed0 \<xs\_init>\, env=0x0\, my\_perl=\<optimized out>\) at perl\.c&#8203;:2298
\#7  perl\_parse \(my\_perl=\<optimized out>\, xsinit=xsinit@&#8203;entry=0x41bed0 \<xs\_init>\, argc=\<optimized out>\, argv=\<optimized out>\, env=env@&#8203;entry=0x0\) at perl\.c&#8203;:1607
\#8  0x000000000041bd29 in main \(argc=3\, argv=0x7fffffffdd88\, env=0x7fffffffdda8\) at perlmain\.c&#8203;:112

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

$ gdb \-\-args perl \-e '30; "$a\[b\]";'
GNU gdb \(Ubuntu 7\.10\-0ubuntu1\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from perl\.\.\.Reading symbols from /usr/lib/debug//usr/bin/perl\.\.\.done\.
done\.
\(gdb\) run
Starting program&#8203;: /usr/bin/perl \-e 30\\;\\ \\"\\$a\\\[b\\\]\\"\\;
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.

Program received signal SIGSEGV\, Segmentation fault\.
0x000000000052ffe1 in Perl\_my\_atof \(my\_perl=my\_perl@&#8203;entry=0x7a9010\, s=0x7d8f40 "b"\) at numeric\.c&#8203;:857
857    numeric\.c&#8203;: No such file or directory\.
\(gdb\) bt
\#0  0x000000000052ffe1 in Perl\_my\_atof \(my\_perl=my\_perl@&#8203;entry=0x7a9010\, s=0x7d8f40 "b"\) at numeric\.c&#8203;:857
\#1  0x00000000004c50e1 in S\_sv\_2iuv\_common \(my\_perl=my\_perl@&#8203;entry=0x7a9010\, sv=sv@&#8203;entry=0x7d3c70\) at sv\.c&#8203;:2214
\#2  0x00000000004c578b in Perl\_sv\_2iv\_flags \(my\_perl=my\_perl@&#8203;entry=0x7a9010\, sv=0x7d3c70\, flags=flags@&#8203;entry=2\) at sv\.c&#8203;:2404
\#3  0x000000000042bac5 in Perl\_rpeep \(my\_perl=0x7a9010\, o=0x7d8cc0\) at op\.c&#8203;:11814
\#4  0x00000000004266fc in Perl\_newPROG \(my\_perl=0x7a9010\, o=0x7d8d00\) at op\.c&#8203;:3361
\#5  0x0000000000465735 in Perl\_yyparse \(my\_perl=0x7a9010\, gramtype=8223088\) at perly\.y&#8203;:147
\#6  0x000000000043cd0d in S\_parse\_body \(xsinit=0x41bed0 \<xs\_init>\, env=0x0\, my\_perl=\<optimized out>\) at perl\.c&#8203;:2298
\#7  perl\_parse \(my\_perl=\<optimized out>\, xsinit=xsinit@&#8203;entry=0x41bed0 \<xs\_init>\, argc=\<optimized out>\, argv=\<optimized out>\, env=env@&#8203;entry=0x0\) at perl\.c&#8203;:1607
\#8  0x000000000041bd29 in main \(argc=3\, argv=0x7fffffffdd88\, env=0x7fffffffdda8\) at perlmain\.c&#8203;:112

**Comment by p5pRT** [comment]
### From @wolfsage

On Thu\, Sep 3\, 2015 at 7&#8203;:51 AM\, Nils \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:


> \#\!/usr/bin/perl
> \# This is perl 5\, version 20\, subversion 2 \(v5\.20\.2\) built for x86\_64\-linux\-gnu\-thread\-multi
> \# \(with 42 registered patches\, see perl \-V for more detail\)
>
> use strict;
> use warnings;
>
> sub something \{ my $subvar= shift; \}
> my $table="";
> my @&#8203;tablename = \("tix\_ALL"\, "tix\_2"\, "tix\_3"\);
> my $loop=0;
>
> $table = something\("$tablename\[$loop\]\_table"\);
> something\("\./$table\.csv"\) if\(0\);
> \#SEGFAULT HERE due to 'loop' instead of '$loop'
> print "Writing table $tablename\[loop\]\\n";

I believe this reduces to&#8203;:

&nbsp;  perl \-e '0; $a\[b\]'

Seemingly broken in 5\.19\.3 with

commit 515abc43ad7e359e9f2f1fedb73378c13fd16348
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Sat Aug 10 10&#8203;:41&#8203;:11 2013 \-0700

&nbsp;    Set PL\_curcop to NULL in op\.c&#8203;:S\_cop\_free

Seemingly fixed in 5\.21\.5\, in passing\, by&#8203;:

commit f5b5c2a37af8753575a60bff8620560576946b4a
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Mon Oct 13 20&#8203;:37&#8203;:29 2014 \-0700

&nbsp;    Simplify double\-nextstate optimisation

&nbsp;    \[\.\.\.\]

\-\- Matthew Horsfall \(alh\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Nicolas Mendoza via RT wrote&#8203;:
>Program received signal SIGSEGV\, Segmentation fault\.
>0x000000000052ffe1 in Perl\_my\_atof \(my\_perl=my\_perl@&#8203;entry=0x7a9010\, s=0x7d8f40 "b"\) at numeric\.c&#8203;:857

That's DECLARE\_STORE\_LC\_NUMERIC\_SET\_TO\_NEEDED\(\)\.  Presumably failing via
the need to check lexical locale flags\, which tries to use PL\_curcop\.
Both the apparent breaking and apparent fixing commits were concerned
with cops\, but the nature of the apparent fixing one doesn't fill me
with confidence that the problem is really fixed\.  You should look at
the state of PL\_curcop at the moment of segv&#8203;: I'm pretty sure it's either
null or pointing at a broken op structure\.

\-zefram

**Comment by p5pRT** [comment]
### From @iabyn

On Fri\, Sep 04\, 2015 at 08&#8203;:11&#8203;:04PM \+0100\, Zefram wrote&#8203;:
> Nicolas Mendoza via RT wrote&#8203;:
> >Program received signal SIGSEGV\, Segmentation fault\.
> >0x000000000052ffe1 in Perl\_my\_atof \(my\_perl=my\_perl@&#8203;entry=0x7a9010\, s=0x7d8f40 "b"\) at numeric\.c&#8203;:857
> 
> That's DECLARE\_STORE\_LC\_NUMERIC\_SET\_TO\_NEEDED\(\)\.  Presumably failing via
> the need to check lexical locale flags\, which tries to use PL\_curcop\.
> Both the apparent breaking and apparent fixing commits were concerned
> with cops\, but the nature of the apparent fixing one doesn't fill me
> with confidence that the problem is really fixed\.  You should look at
> the state of PL\_curcop at the moment of segv&#8203;: I'm pretty sure it's either
> null or pointing at a broken op structure\.

Looking at this further\, the SEGV in 5\.20\.0 happened due the "delete spare
COP when two are adjacent" code in rpeep\. That code was calling
S\_cop\_free\(\)\, which after v5\.19\.2\-370\-g515abc4 sets PL\_curcop to NULL if
PL\_curcop is the cop being freed\.

The simplified deduplication code introduced by v5\.21\.4\-465\-gf5b5c2a
doesn't call S\_cop\_free\(\) any more\, so its no longer an issue\.

So I'll close this ticket\.

\-\- 
All wight\. I will give you one more chance\. This time\, I want to hear
no Wubens\. No Weginalds\. No Wudolf the wed\-nosed weindeers\.
&nbsp;    \-\- Life of Brian

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
