### ISSUE TITLE
Another segfault in a child of Perl_runops_standard, this one in Perl_pp_stat

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14910]
Migrated from [rt.perl.org#126064](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126064) (status was 'resolved')

Searchable as RT126064$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc=afl\-gcc \-Duselongdouble \-Duse64bitint \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and filtering out testcases that are merely iterations of "\#\!perl \-u"\, I have located the following testcase that triggers a segmentation fault in the perl interpreter\. The testcase is the 14 character file&#8203;:

stat\+stat\+stat

As with 126042\, this seems to be an instance of multiple instances of the same thing being on the stack\, related to the stack not being refcounted\. However\, unlike earlier instances of this bug that I have found\, Valgrind finds an earlier error\, namely an invalid 32\-bit read 4 bytes before a region alloced in Perl\_init\_stacks\. Accordingly\, I do not know whether this \(and 126042\) should be depending on the 77706 tracking bug\.

\*\*GDB\*\*

GNU gdb \(GDB\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "i686\-pc\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from \.\./bin/perl\.\.\.done\.
\(gdb\) run
Starting program&#8203;: /usr/local/perl\-afl/bin/perl allcrash/f3i000000
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/libthread\_db\.so\.1"\.
Warning&#8203;: Use of "stat" without parentheses is ambiguous at allcrash/f3i000000 line 1\.
Warning&#8203;: Use of "stat" without parentheses is ambiguous at allcrash/f3i000000 line 1\.

Program received signal SIGSEGV\, Segmentation fault\.
0x085001b6 in Perl\_pp\_stat \(\) at pp\_sys\.c&#8203;:2869
2869                                      : \!\!\(sv=POPs\, gv = MAYBE\_DEREF\_GV\(sv\)\)\) \{
\(gdb\) bt
\#0  0x085001b6 in Perl\_pp\_stat \(\) at pp\_sys\.c&#8203;:2869
\#1  0x08350c5b in Perl\_runops\_standard \(\) at run\.c&#8203;:41
\#2  0x08116c47 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2456
\#3  perl\_run \(my\_perl=0x87d8008\) at perl\.c&#8203;:2379
\#4  0x08068762 in main \(argc=2\, argv=0xbffff4a4\, env=0xbffff4b0\)
&nbsp;    at perlmain\.c&#8203;:116

\*\*VALGRIND\*\*

==22561== Memcheck\, a memory error detector
==22561== Copyright \(C\) 2002\-2013\, and GNU GPL'd\, by Julian Seward et al\.
==22561== Using Valgrind\-3\.10\.1 and LibVEX; rerun with \-h for copyright info
==22561== Command&#8203;: \.\./bin/perl allcrash/f3i000000
==22561== 
Warning&#8203;: Use of "stat" without parentheses is ambiguous at allcrash/f3i000000 line 1\.
Warning&#8203;: Use of "stat" without parentheses is ambiguous at allcrash/f3i000000 line 1\.
==22561== Invalid read of size 4
==22561==    at 0x85001B0&#8203;: Perl\_pp\_stat \(pp\_sys\.c&#8203;:2869\)
==22561==    by 0x8350C5A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==22561==    by 0x8116C46&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==22561==    by 0x8116C46&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==22561==    by 0x8068761&#8203;: main \(perlmain\.c&#8203;:116\)
==22561==  Address 0x42bffd4 is 4 bytes before a block of size 512 alloc'd
==22561==    at 0x402A0DE&#8203;: malloc \(vg\_replace\_malloc\.c&#8203;:296\)
==22561==    by 0x82B3AF3&#8203;: Perl\_safesysmalloc \(util\.c&#8203;:153\)
==22561==    by 0x8343B47&#8203;: Perl\_av\_extend\_guts \(av\.c&#8203;:182\)
==22561==    by 0x8343CBF&#8203;: Perl\_av\_extend \(av\.c&#8203;:80\)
==22561==    by 0x845CEDD&#8203;: Perl\_new\_stackinfo \(scope\.c&#8203;:56\)
==22561==    by 0x80FF36D&#8203;: Perl\_init\_stacks \(perl\.c&#8203;:4063\)
==22561==    by 0x80FF84D&#8203;: perl\_construct \(perl\.c&#8203;:249\)
==22561==    by 0x80684B8&#8203;: main \(perlmain\.c&#8203;:110\)
==22561== 
==22561== Invalid read of size 4
==22561==    at 0x85001B6&#8203;: Perl\_pp\_stat \(pp\_sys\.c&#8203;:2869\)
==22561==    by 0x8350C5A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==22561==    by 0x8116C46&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==22561==    by 0x8116C46&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==22561==    by 0x8068761&#8203;: main \(perlmain\.c&#8203;:116\)
==22561==  Address 0x8 is not stack'd\, malloc'd or \(recently\) free'd
==22561== 
==22561== 
==22561== Process terminating with default action of signal 11 \(SIGSEGV\)
==22561==  Access not within mapped region at address 0x8
==22561==    at 0x85001B6&#8203;: Perl\_pp\_stat \(pp\_sys\.c&#8203;:2869\)
==22561==    by 0x8350C5A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==22561==    by 0x8116C46&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==22561==    by 0x8116C46&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==22561==    by 0x8068761&#8203;: main \(perlmain\.c&#8203;:116\)
==22561==  If you believe this happened as a result of a stack
==22561==  overflow in your program's main thread \(unlikely but
==22561==  possible\)\, you can try to increase the size of the
==22561==  main thread stack using the \-\-main\-stacksize= flag\.
==22561==  The main thread stack size used in this run was 8388608\.
==22561== 
==22561== HEAP SUMMARY&#8203;:
==22561==     in use at exit&#8203;: 98\,503 bytes in 621 blocks
==22561==   total heap usage&#8203;: 732 allocs\, 111 frees\, 116\,732 bytes allocated
==22561== 
==22561== LEAK SUMMARY&#8203;:
==22561==    definitely lost&#8203;: 160 bytes in 1 blocks
==22561==    indirectly lost&#8203;: 2\,584 bytes in 38 blocks
==22561==      possibly lost&#8203;: 0 bytes in 0 blocks
==22561==    still reachable&#8203;: 95\,759 bytes in 582 blocks
==22561==         suppressed&#8203;: 0 bytes in 0 blocks
==22561== Rerun with \-\-leak\-check=full to see details of leaked memory
==22561== 
==22561== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==22561== ERROR SUMMARY&#8203;: 2 errors from 2 contexts \(suppressed&#8203;: 0 from 0\)
Segmentation fault

\*\*PERL \-V\*\*

Summary of my perl5 \(revision 5 version 23 subversion 3\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 801fcc250783bc56ec8033a5940b3257bcd9a7db
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.32\-5\-686\, archname=i686\-linux\-64int\-ld
&nbsp;    uname='linux nagios 2\.6\.32\-5\-686 \#1 smp tue may 13 16&#8203;:33&#8203;:32 utc 2014 i686 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=afl\-gcc \-Duselongdouble \-Duse64bitint \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=undef\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='afl\-gcc'\, ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='5\.2\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12\, longdblkind=3
&nbsp;    ivtype='long long'\, ivsize=8\, nvtype='long double'\, nvsize=12\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/i686\-pc\-linux\-gnu/5\.2\.0/include\-fixed /usr/lib /lib/\.\./lib /usr/lib/\.\./lib /lib /usr/lib/i486\-linux\-gnu /usr/lib64
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.22\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.22'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_INT
&nbsp;                        USE\_LARGE\_FILES USE\_LOCALE USE\_LOCALE\_COLLATE
&nbsp;                        USE\_LOCALE\_CTYPE USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME
&nbsp;                        USE\_LONG\_DOUBLE USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Sep 13 2015 22&#8203;:47&#8203;:04
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.3/i686\-linux\-64int\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.3
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.3/i686\-linux\-64int\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.3
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.2
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @cpansprout

On Tue Sep 15 19&#8203;:23&#8203;:00 2015\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> Greetings Porters\,
> 
> I have compiled bleadperl with the afl\-gcc compiler using&#8203;:
> 
> \./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc=afl\-gcc
> \-Duselongdouble \-Duse64bitint \-Doptimize=\-g \-Uversiononly \-Uman1dir
> \-Uman3dir \-des
> AFL\_HARDEN=1 make && make test
> 
> And then fuzzed the resulting binary using&#8203;:
> 
> AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;
> 
> After reducing testcases using \`afl\-tmin\` and filtering out testcases
> that are merely iterations of "\#\!perl \-u"\, I have located the
> following testcase that triggers a segmentation fault in the perl
> interpreter\. The testcase is the 14 character file&#8203;:
> 
> stat\+stat\+stat
> 
> As with 126042\, this seems to be an instance of multiple instances of
> the same thing being on the stack\, related to the stack not being
> refcounted\.

It has nothing to do with the stack not being refcounted\, but stack corruption resulting from perl losing track of where the current stack pointer is meant to be\.  It is reading past the beginning of the stack\.

I have just fixed it in 7f399b4008\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
