### ISSUE TITLE
Segfault/assert fail while requiring IO::File in an attempt to resolve a missing method on a hash, hv_common expects SVt_PVHV but got SVt_PV

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14939]
Migrated from [rt.perl.org#126188](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126188) (status was 'open')

Searchable as RT126188$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitint \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and filtering out testcases that are merely iterations of "\#\!perl \-u"\, I have located the following testcase that triggers a segmentation fault in the perl interpreter\. The testcase is the 19\-character file&#8203;:

%0=f fffff%&#8203;::=fffff

which was further manually reduced to the 8\-character file&#8203;:

f f%&#8203;::=f

Debugging perls instead report&#8203;:

miniperl&#8203;: hv\.c&#8203;:355&#8203;: Perl\_hv\_common&#8203;: Assertion \`\(\(svtype\)\(\(hv\)\->sv\_flags & 0xff\)\) == SVt\_PVHV' failed\.

Expected behavior is the same as the similar test 'f f$&#8203;::=f'\, which crashes with "Can't locate object method "f" via package "f" \(perhaps you forgot to load "f"?\)"\. Once upon a time that happened\, however\, interestingly\, that changed when xdg added code to automatically require IO&#8203;::File when a filehandle method call would fail because the method would not be found \(see bisect\)\. What's more\, I tested&#8203;:

dcollins@&#8203;nightshade&#8203;:/usr/local/perl\-afl/out$ \.\./bin/perl \-e 'f f%&#8203;::=f'
Segmentation fault
dcollins@&#8203;nightshade&#8203;:/usr/local/perl\-afl/out$ \.\./bin/perl \-MIO&#8203;::File \-e 'f f%&#8203;::=f'
Can't locate object method "f" via package "IO&#8203;::File" at \-e line 1\.

So it seems like this is some weird case of an error while loading the module in this way\, or loading it while this odd construct is on the stack\.

\*\*GDB\*\*

dcollins@&#8203;nightshade&#8203;:\~/perl$ gdb \-\-args \./perl \.\./crash
GNU gdb \(GDB\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "i686\-pc\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from \./perl\.\.\.done\.
\(gdb\) run
Starting program&#8203;: /home/dcollins/perl/perl \.\./crash
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/libthread\_db\.so\.1"\.

Program received signal SIGSEGV\, Segmentation fault\.
0x08325e4c in Perl\_hv\_common \(hv=0x87db2e0\, keysv=0x0\, 
&nbsp;    key=0x8725f9f "require"\, klen=7\, flags=\<optimized out>\, action=32\, 
&nbsp;    val=0x0\, hash=603707530\) at hv\.c&#8203;:671
671        if \(HeHASH\(entry\) \!= hash\)        /\* strings can't be equal \*/
\(gdb\) bt
\#0  0x08325e4c in Perl\_hv\_common \(hv=0x87db2e0\, keysv=0x0\, 
&nbsp;    key=0x8725f9f "require"\, klen=7\, flags=\<optimized out>\, action=32\, 
&nbsp;    val=0x0\, hash=603707530\) at hv\.c&#8203;:671
\#1  0x083288c6 in Perl\_hv\_common\_key\_len \(hv=0x87db2e0\, 
&nbsp;    key=0x8725f9f "require"\, klen\_i32=7\, action=32\, val=0x0\, hash=0\)
&nbsp;    at hv\.c&#8203;:333
\#2  0x0813d436 in Perl\_gv\_override \(name=0x8725f9f "require"\, len=7\)
&nbsp;    at gv\.c&#8203;:3592
\#3  0x080cdf4f in Perl\_ck\_require \(o=0x87eb844\) at op\.c&#8203;:10644
\#4  0x080a4ad7 in Perl\_newUNOP \(type=339\, flags=\<optimized out>\, 
&nbsp;    first=0x87eb864\) at op\.c&#8203;:4809
\#5  0x081cf859 in Perl\_yyparse \(gramtype=258\) at perly\.y&#8203;:1004
\#6  0x0846d51d in S\_doeval \(gimme=gimme@&#8203;entry=1\, 
&nbsp;    outside=outside@&#8203;entry=0x87db420\, seq=\<optimized out>\, hh=0x0\)
&nbsp;    at pp\_ctl\.c&#8203;:3391
\#7  0x084d05c6 in Perl\_pp\_entereval \(\) at pp\_ctl\.c&#8203;:4198
\#8  0x080fda66 in Perl\_eval\_sv \(sv=0x87dbbdc\, flags=4\) at perl\.c&#8203;:2882
\#9  0x080fe602 in Perl\_require\_pv \(pv=0x87489bf "IO/File\.pm"\) at perl\.c&#8203;:2989
\#10 0x08121ddd in Perl\_gv\_fetchmethod\_pvn\_flags \(stash=0x87ebb94\, 
&nbsp;    name=\<optimized out>\, len=1\, flags=768\) at gv\.c&#8203;:1088
\#11 0x0812319a in Perl\_gv\_fetchmethod\_sv\_flags \(stash=0x87ebb94\, 
&nbsp;    namesv=0x87ec3c8\, flags=768\) at gv\.c&#8203;:1001
\#12 0x0837efa7 in Perl\_pp\_method\_named \(\) at pp\_hot\.c&#8203;:3783
\#13 0x0835103b in Perl\_runops\_standard \(\) at run\.c&#8203;:41
\-\-\-Type \<return> to continue\, or q \<return> to quit\-\-\-
\#14 0x08116f27 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2456
\#15 perl\_run \(my\_perl=0x87d9008\) at perl\.c&#8203;:2379
\#16 0x08068992 in main \(argc=2\, argv=0xbffff4c4\, env=0xbffff4d0\)
&nbsp;    at perlmain\.c&#8203;:116
\(gdb\) p entry
$1 = \(HE \*\) 0x45524f43
\(gdb\) p hash
$2 = 603707530
\(gdb\) p \*\(\(HE \*\) entry\)
Cannot access memory at address 0x45524f43
\(gdb\) q
A debugging session is active\.

&nbsp;    Inferior 1 \[process 6902\] will be killed\.

Quit anyway? \(y or n\) y

'entry' is set to this value on line 637\, entry = \(HvARRAY\(hv\)\)\[hash & \(I32\) HvMAX\(hv\)\];
where\,
\(gdb\) p hash    
$3 = 4130847814
\(gdb\) p hv
$4 = \(HV \*\) 0x822e2e0
\(gdb\) p \*hv
$5 = \{sv\_any = 0x822ef58\, sv\_refcnt = 1\, sv\_flags = 268452867\, sv\_u = \{
&nbsp;    svu\_pv = 0x82393e4 "CORE"\, svu\_iv = 136549348\, svu\_uv = 136549348\, 
&nbsp;    svu\_rv = 0x82393e4\, svu\_rx = 0x82393e4\, svu\_array = 0x82393e4\, 
&nbsp;    svu\_hash = 0x82393e4\, svu\_gp = 0x82393e4\, svu\_fp = 0x82393e4\}\}

sv\_flags decodes to 0x10004403\, SVf\_IsCOW | SVp\_POK | SVf\_POK | SVt\_PV\. I'm not sure if sv\_flags is corrupted here or if sv\_u is\, but entry is getting "CORE" written to it \(0x45524f43 decodes to "EROC"\) instead of a pointer value\.

\*\*VALGRIND\*\*

dcollins@&#8203;nightshade&#8203;:\~/perl$ valgrind \./perl \.\./crash
==11682== Memcheck\, a memory error detector
==11682== Copyright \(C\) 2002\-2013\, and GNU GPL'd\, by Julian Seward et al\.
==11682== Using Valgrind\-3\.10\.1 and LibVEX; rerun with \-h for copyright info
==11682== Command&#8203;: \./perl \.\./crash
==11682== 
==11682== Invalid read of size 4
==11682==    at 0x8325E4C&#8203;: Perl\_hv\_common \(hv\.c&#8203;:671\)
==11682==    by 0x83288C5&#8203;: Perl\_hv\_common\_key\_len \(hv\.c&#8203;:333\)
==11682==    by 0x813D435&#8203;: Perl\_gv\_override \(gv\.c&#8203;:3592\)
==11682==    by 0x80CDF4E&#8203;: Perl\_ck\_require \(op\.c&#8203;:10644\)
==11682==    by 0x80A4AD6&#8203;: Perl\_newUNOP \(op\.c&#8203;:4809\)
==11682==    by 0x81CF858&#8203;: Perl\_yyparse \(perly\.y&#8203;:1004\)
==11682==    by 0x846D51C&#8203;: S\_doeval \(pp\_ctl\.c&#8203;:3391\)
==11682==    by 0x84D05C5&#8203;: Perl\_pp\_entereval \(pp\_ctl\.c&#8203;:4198\)
==11682==    by 0x80FDA65&#8203;: Perl\_eval\_sv \(perl\.c&#8203;:2882\)
==11682==    by 0x80FE601&#8203;: Perl\_require\_pv \(perl\.c&#8203;:2989\)
==11682==    by 0x8121DDC&#8203;: Perl\_gv\_fetchmethod\_pvn\_flags \(gv\.c&#8203;:1088\)
==11682==    by 0x8123199&#8203;: Perl\_gv\_fetchmethod\_sv\_flags \(gv\.c&#8203;:1001\)
==11682==  Address 0x45524f47 is not stack'd\, malloc'd or \(recently\) free'd
==11682== 
==11682== 
==11682== Process terminating with default action of signal 11 \(SIGSEGV\)
==11682==  Access not within mapped region at address 0x45524F47
==11682==    at 0x8325E4C&#8203;: Perl\_hv\_common \(hv\.c&#8203;:671\)
==11682==    by 0x83288C5&#8203;: Perl\_hv\_common\_key\_len \(hv\.c&#8203;:333\)
==11682==    by 0x813D435&#8203;: Perl\_gv\_override \(gv\.c&#8203;:3592\)
==11682==    by 0x80CDF4E&#8203;: Perl\_ck\_require \(op\.c&#8203;:10644\)
==11682==    by 0x80A4AD6&#8203;: Perl\_newUNOP \(op\.c&#8203;:4809\)
==11682==    by 0x81CF858&#8203;: Perl\_yyparse \(perly\.y&#8203;:1004\)
==11682==    by 0x846D51C&#8203;: S\_doeval \(pp\_ctl\.c&#8203;:3391\)
==11682==    by 0x84D05C5&#8203;: Perl\_pp\_entereval \(pp\_ctl\.c&#8203;:4198\)
==11682==    by 0x80FDA65&#8203;: Perl\_eval\_sv \(perl\.c&#8203;:2882\)
==11682==    by 0x80FE601&#8203;: Perl\_require\_pv \(perl\.c&#8203;:2989\)
==11682==    by 0x8121DDC&#8203;: Perl\_gv\_fetchmethod\_pvn\_flags \(gv\.c&#8203;:1088\)
==11682==    by 0x8123199&#8203;: Perl\_gv\_fetchmethod\_sv\_flags \(gv\.c&#8203;:1001\)
==11682==  If you believe this happened as a result of a stack
==11682==  overflow in your program's main thread \(unlikely but
==11682==  possible\)\, you can try to increase the size of the
==11682==  main thread stack using the \-\-main\-stacksize= flag\.
==11682==  The main thread stack size used in this run was 8388608\.
==11682== 
==11682== HEAP SUMMARY&#8203;:
==11682==     in use at exit&#8203;: 90\,158 bytes in 421 blocks
==11682==   total heap usage&#8203;: 843 allocs\, 422 frees\, 118\,299 bytes allocated
==11682== 
==11682== LEAK SUMMARY&#8203;:
==11682==    definitely lost&#8203;: 156 bytes in 1 blocks
==11682==    indirectly lost&#8203;: 2\,592 bytes in 37 blocks
==11682==      possibly lost&#8203;: 0 bytes in 0 blocks
==11682==    still reachable&#8203;: 87\,410 bytes in 383 blocks
==11682==         suppressed&#8203;: 0 bytes in 0 blocks
==11682== Rerun with \-\-leak\-check=full to see details of leaked memory
==11682== 
==11682== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==11682== ERROR SUMMARY&#8203;: 1 errors from 1 contexts \(suppressed&#8203;: 0 from 0\)
Segmentation fault

\*\*BISECT\*\*

15e6cdd91beb4cefae4b65e855d68cf64766965d is the first bad commit
commit 15e6cdd91beb4cefae4b65e855d68cf64766965d
Author&#8203;: David Golden \<dagolden@&#8203;cpan\.org>
Date&#8203;:   Sun Nov 28 23&#8203;:12&#8203;:12 2010 \-0500

&nbsp;    Filehandle method calls load IO&#8203;::File on demand
&nbsp;    
&nbsp;    When a method call on a filehandle would die because the method can not
&nbsp;    be resolved and L\<IO&#8203;::File> has not been loaded\, Perl now loads IO&#8203;::File
&nbsp;    via C\<require> and attempts method resolution again&#8203;:
&nbsp;    
&nbsp;      open my $fh\, ">"\, $file;
&nbsp;      $fh\->binmode\("&#8203;:raw"\);     \# loads IO&#8203;::File and succeeds
&nbsp;    
&nbsp;    This also works for globs like STDOUT\, STDERR and STDIN&#8203;:
&nbsp;    
&nbsp;      STDOUT\->autoflush\(1\);
&nbsp;    
&nbsp;    Because this on\-demand load only happens if method resolution fails\, the
&nbsp;    legacy approach of manually loading an IO&#8203;::File parent class for partial
&nbsp;    method support still works as expected&#8203;:
&nbsp;    
&nbsp;      use IO&#8203;::Handle;
&nbsp;      open my $fh\, ">"\, $file;
&nbsp;      $fh\->autoflush\(1\);        \# IO&#8203;::File not loaded

:100644 100644 5ddf5ccc2d313c25b50eebbb6f75cc6bdf8b2e8c d9281f462a045d2bbe376d81a8b86a974032156c M    MANIFEST
:100644 100644 5fd385bd11b37a1c8c20146b1818e751376ec45e 4775bccf3701af1b081a9bf3ee1c30c68f177b9b M    gv\.c
:040000 040000 af27b0f4e6fb40d5844054153ea1db83456d7f2c e41af2cb54480c0010fbde174abab7036745f482 M    pod
:040000 040000 1c79c8de724651339b2360962d73754e999cc5b5 e4fb3294c6b8f2a69a4ccb849898ad8d6884bd91 M    t
bisect run success

\*\*PERL \-V\*\*

dcollins@&#8203;nightshade&#8203;:\~/perl$ \./perl \-Ilib \-V
Summary of my perl5 \(revision 5 version 23 subversion 4\) configuration&#8203;:
&nbsp;  Commit id&#8203;: e120c24fe257993e9cbf4c567194bec2792f3ccc
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.32\-5\-686\, archname=i686\-linux\-64int\-ld
&nbsp;    uname='linux nightshade 2\.6\.32\-5\-686 \#1 smp tue may 13 16&#8203;:33&#8203;:32 utc 2014 i686 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitint \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=undef\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='5\.2\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12\, longdblkind=3
&nbsp;    ivtype='long long'\, ivsize=8\, nvtype='long double'\, nvsize=12\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/i686\-pc\-linux\-gnu/5\.2\.0/include\-fixed /usr/lib /lib/\.\./lib /usr/lib/\.\./lib /lib /usr/lib/i486\-linux\-gnu /usr/lib64
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.22\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.22'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_INT
&nbsp;                        USE\_LARGE\_FILES USE\_LOCALE USE\_LOCALE\_COLLATE
&nbsp;                        USE\_LOCALE\_CTYPE USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME
&nbsp;                        USE\_LONG\_DOUBLE USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Sep 25 2015 09&#8203;:13&#8203;:06
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4/i686\-linux\-64int\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4/i686\-linux\-64int\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.3
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.2
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @tonycoz

On Fri Sep 25 10&#8203;:32&#8203;:29 2015\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> which was further manually reduced to the 8\-character file&#8203;:
> 
> f f%&#8203;::=f
> 
> Debugging perls instead report&#8203;:
> 
> miniperl&#8203;: hv\.c&#8203;:355&#8203;: Perl\_hv\_common&#8203;: Assertion \`\(\(svtype\)\(\(hv\)\-
> >sv\_flags & 0xff\)\) == SVt\_PVHV' failed\.
> 
> Expected behavior is the same as the similar test 'f f$&#8203;::=f'\, which
> crashes with "Can't locate object method "f" via package "f" \(perhaps
> you forgot to load "f"?\)"\. Once upon a time that happened\, however\,
> interestingly\, that changed when xdg added code to automatically
> require IO&#8203;::File when a filehandle method call would fail because the
> method would not be found \(see bisect\)\. What's more\, I tested&#8203;:
> 
> dcollins@&#8203;nightshade&#8203;:/usr/local/perl\-afl/out$ \.\./bin/perl \-e 'f f%&#8203;::=f'
> Segmentation fault
> dcollins@&#8203;nightshade&#8203;:/usr/local/perl\-afl/out$ \.\./bin/perl \-MIO&#8203;::File \-e
> 'f f%&#8203;::=f'
> Can't locate object method "f" via package "IO&#8203;::File" at \-e line 1\.
> 
> So it seems like this is some weird case of an error while loading the
> module in this way\, or loading it while this odd construct is on the
> stack\.

What's happening is the assignment&#8203;:

&nbsp;  %&#8203;::=f

is releasing the sv PL\_globalstash points at\, which is then re\-used when an overload for require is checked for\, setting it to "CORE"\.

Modifying hv\_clear\(\) to reinitialize PL\_globalstash gets past that bug\, but fails further on \(trashing the symbol table is bad\.\)

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @geeknik

Triggered in v5\.25\.5 \(v5\.25\.4\-130\-g7aa7bbc\) w/ AFL \+ ASAN\.

\./perl \-e '\*0=d$^$^=%0=\*0=$0=$^=$0=\*0=$0=$V'
Scalar found where operator expected at \-e line 1\, near "$^$^"
&nbsp;        \(Missing operator before $^?\)
&nbsp;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      : hv\.c&#8203;:355&#8203;: void \*Perl\_hv\_common\(HV \*\, SV \*\, const char \*\, STRLEN\, int\, int\, SV \*\, U32\)&#8203;: Assertion \`\(\(svtype\)\(\(hv\)\->sv\_flags & 0xff\)\) == SVt\_PVHV' failed\.
Aborted

**Comment by p5pRT** [comment]
### From @geeknik

Triggered in Perl v5\.25\.6 \(v5\.25\.5\-76\-g91dca83\) with AFL\+ASAN\.

Odd number of elements in hash assignment at test113 line 1\.
Can't locate package IO&#8203;::Handle for @&#8203;IO&#8203;::File&#8203;::ISA at test113 line 1\.
Can't locate package IO&#8203;::Seekable for @&#8203;IO&#8203;::File&#8203;::ISA at test113 line 1\.
Can't locate package IO&#8203;::Handle for @&#8203;IO&#8203;::File&#8203;::ISA at test113 line 1\.
Can't locate package IO&#8203;::Seekable for @&#8203;IO&#8203;::File&#8203;::ISA at test113 line 1\.
Unrecognized escape \\m passed through in regex; marked by \<\-\- HERE in
m/;ememee\-c¦¦;@&#8203;&#8203;:: e; cme;@&#8203;&#8203;:: =2A^D= \\m \<\-\- HERE ¦9&#8203;: =^D=
\\PPPPPPPPPPPPPPPPPPPPPPPPPPPPPm/ at test113 line 1\.
perl&#8203;: hv\.c&#8203;:355&#8203;: void \*Perl\_hv\_common\(HV \*\, SV \*\, const char \*\, STRLEN\, int\,
int\, SV \*\, U32\)&#8203;: Assertion \`\(\(svtype\)\(\(hv\)\->sv\_flags & 0xff\)\) == SVt\_PVHV'
failed\.
Aborted

The attached doesn't always trigger this assertion failure failure though\,
it also returns&#8203;:

Odd number of elements in hash assignment at test113 line 1\.
Can't locate package Exporter for @&#8203;IO&#8203;::File&#8203;::ISA at test113 line 1\.
Can't locate package Exporter for @&#8203;IO&#8203;::File&#8203;::ISA at test113 line 1\.
Unrecognized escape \\m passed through in regex; marked by \<\-\- HERE in
m/;ememee\-c¦¦;@&#8203;&#8203;:: e; cme;@&#8203;&#8203;:: =2A^D= \\m \<\-\- HERE ¦9&#8203;: =^D=
\\PPPPPPPPPPPPPPPPPPPPPPPPPPPPPm/ at test113 line 1\.
Can't locate utf8\.pm in @&#8203;INC \(you may need to install the utf8 module\)
\(@&#8203;INC contains&#8203;: /usr/local/lib/perl5/site\_perl/5\.25\.6/x86\_64\-linux
/usr/local/lib/perl5/site\_perl/5\.25\.6
/usr/local/lib/perl5/5\.25\.6/x86\_64\-linux /usr/local/lib/perl5/5\.25\.6 \.\) at
test113 line 1\.
BEGIN failed\-\-compilation aborted\.

and

Odd number of elements in hash assignment at test113 line 1\.
Can't locate package IO&#8203;::Handle for @&#8203;IO&#8203;::File&#8203;::ISA at test113 line 1\.
Can't locate package IO&#8203;::Seekable for @&#8203;IO&#8203;::File&#8203;::ISA at test113 line 1\.
Can't locate package IO&#8203;::Handle for @&#8203;IO&#8203;::File&#8203;::ISA at test113 line 1\.
Can't locate package IO&#8203;::Seekable for @&#8203;IO&#8203;::File&#8203;::ISA at test113 line 1\.
Unrecognized escape \\m passed through in regex; marked by \<\-\- HERE in
m/;ememee\-c¦¦;@&#8203;&#8203;:: e; cme;@&#8203;&#8203;:: =2A^D= \\m \<\-\- HERE ¦9&#8203;: =^D=
\\PPPPPPPPPPPPPPPPPPPPPPPPPPPPPm/ at test113 line 1\.
Can't locate utf8\.pm in @&#8203;INC \(you may need to install the utf8 module\)
\(@&#8203;INC contains&#8203;: /usr/local/lib/perl5/site\_perl/5\.25\.6/x86\_64\-linux
/usr/local/lib/perl5/site\_perl/5\.25\.6
/usr/local/lib/perl5/5\.25\.6/x86\_64\-linux /usr/local/lib/perl5/5\.25\.6 \.\) at
test113 line 1\.
BEGIN failed\-\-compilation aborted\.
Can't locate package IO&#8203;::Handle for @&#8203;IO&#8203;::File&#8203;::ISA during global
destruction\.
Can't locate package IO&#8203;::Seekable for @&#8203;IO&#8203;::File&#8203;::ISA during global
destruction\.
Can't locate package Exporter for @&#8203;IO&#8203;::File&#8203;::ISA during global destruction\.
Can't locate package IO&#8203;::Handle for @&#8203;IO&#8203;::File&#8203;::ISA during global
destruction\.
Can't locate package IO&#8203;::Seekable for @&#8203;IO&#8203;::File&#8203;::ISA during global
destruction\.
Can't locate package Exporter for @&#8203;IO&#8203;::File&#8203;::ISA during global destruction\.

and

Odd number of elements in hash assignment at test113 line 1\.
Can't locate package Exporter for @&#8203;IO&#8203;::File&#8203;::ISA at test113 line 1\.
Can't locate package Exporter for @&#8203;IO&#8203;::File&#8203;::ISA at test113 line 1\.
Unrecognized escape \\m passed through in regex; marked by \<\-\- HERE in
m/;ememee\-c¦¦;@&#8203;&#8203;:: e; cme;@&#8203;&#8203;:: =2A^D= \\m \<\-\- HERE ¦9&#8203;: =^D=
\\PPPPPPPPPPPPPPPPPPPPPPPPPPPPPm/ at test113 line 1\.
Can't locate utf8\.pm in @&#8203;INC \(you may need to install the utf8 module\)
\(@&#8203;INC contains&#8203;: /usr/local/lib/perl5/site\_perl/5\.25\.6/x86\_64\-linux
/usr/local/lib/perl5/site\_perl/5\.25\.6
/usr/local/lib/perl5/5\.25\.6/x86\_64\-linux /usr/local/lib/perl5/5\.25\.6 \.\) at
test113 line 1\.
BEGIN failed\-\-compilation aborted\.

**Comment by p5pRT** [comment]
### From @geeknik

[test113.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1431277/773755/test113.gz)

**Comment by p5pRT** [comment]
### From @hvds

This reduces to&#8203;:

% PERL\_HASH\_SEED=1 \./miniperl \-e '%&#8203;::=\(\); /$^D \\PX/'
miniperl&#8203;: hv\.c&#8203;:355&#8203;: Perl\_hv\_common&#8203;: Assertion \`\(\(svtype\)\(\(hv\)\->sv\_flags & 0xff\)\) == SVt\_PVHV' failed\.
Aborted \(core dumped\)
% 

\(The HASH\_SEED determines the order the %&#8203;:: keys are freed\, and thus whether it fails; you may need a different value to reproduce\.\)

This appears to happen because PL\_globalstash gets freed when all its references disappear during the '%&#8203;:: = \(\)'\, and gets recreated only as a PVAV\.

Giving it an artificial SvREFCNT\_inc in S\_init\_main\_stash\(\) stops the coredump\, but I'm not sure there's any sane situation it'd be needed\, nor that it'd be the right answer if there is\.

Hugo

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @dur-randir

> \./perl \-e '\*0=d$^$^=%0=\*0=$0=$^=$0=\*0=$0=$V'

This is a duplicate of https://rt.perl.org/Public/Bug/Display.html?id=126188

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

> \./perl \-e '\*0=d$^$^=%0=\*0=$0=$^=$0=\*0=$0=$V'

This is a duplicate of https://rt.perl.org/Public/Bug/Display.html?id=126188

**Comment by p5pRT** [comment]
### From @dur-randir

> % PERL\_HASH\_SEED=1 \./miniperl \-e '%&#8203;::=\(\); /$^D \\PX/'

This is a duplicate of https://rt.perl.org/Public/Bug/Display.html?id=126188

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

> % PERL\_HASH\_SEED=1 \./miniperl \-e '%&#8203;::=\(\); /$^D \\PX/'

This is a duplicate of https://rt.perl.org/Public/Bug/Display.html?id=126188
