### ISSUE TITLE
Double-free in Perl_free_tmps

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14943]
Migrated from [rt.perl.org#126199](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126199) (status was 'open')

Searchable as RT126199$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitint \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and filtering out testcases that are merely iterations of "\#\!perl \-u"\, I have located the following testcase that triggers a double free in the perl interpreter\. The testcase is the 134\-character file&#8203;:

du\_S\.Ak\.SA\.=$\[\.=\_\.Ak\.SA\.=$\[\.=$\[=$$$\_S\.Ak\.S\.=$\[\.=$\[=$$$A\.k\.SA\.=$\[\.=\*\[=$$$\_S\.AkAk\.SA\.=%\[=\_\_S\.Ak\.SA\.=$\[\.=$\[=$S\.Ak\.SA\.=$\[\.=\_\.Ak\.SA\.=$\[\.$$$

Any attempt to reduce this testcase causes the bug to disappear\.

dcollins@&#8203;nightshade&#8203;:/usr/local/perl\-afl/out$ \.\./bin/perl f2/crashes/id\\&#8203;:000000\\\,sig\\&#8203;:06\\\,src\\&#8203;:006941\+020231\\\,op\\&#8203;:splice\\\,rep\\&#8203;:2ig\\&#8203;:06\\\,src\\
\*\*\* Error in \`\.\./bin/perl'&#8203;: double free or corruption \(\!prev\)&#8203;: 0x0a21c3f0 \*\*\*
======= Backtrace&#8203;: =========
/lib/libc\.so\.6\(\+0x68c9b\)\[0xb7589c9b\]
/lib/libc\.so\.6\(\+0x6eef7\)\[0xb758fef7\]
/lib/libc\.so\.6\(\+0x6f6a1\)\[0xb75906a1\]
\.\./bin/perl\(Perl\_sv\_clear\+0x609\)\[0x838b2c9\]
\.\./bin/perl\(Perl\_sv\_free2\+0x191\)\[0x8386cd1\]
\.\./bin/perl\(Perl\_free\_tmps\+0x27a\)\[0x845e6ea\]
\.\./bin/perl\(perl\_run\+0xaf5\)\[0x8116ec5\]
\.\./bin/perl\(main\+0x392\)\[0x8068972\]
/lib/libc\.so\.6\(\_\_libc\_start\_main\+0xf7\)\[0xb7539447\]
\.\./bin/perl\[0x80689d7\]
======= Memory map&#8203;: ========
08048000\-087d8000 r\-xp 00000000 08&#8203;:01 192212     /usr/local/perl\-afl/bin/perl
087d8000\-087da000 rw\-p 00790000 08&#8203;:01 192212     /usr/local/perl\-afl/bin/perl
0a215000\-0a258000 rw\-p 00000000 00&#8203;:00 0          \[heap\]
b7200000\-b7221000 rw\-p 00000000 00&#8203;:00 0 
b7221000\-b7300000 \-\-\-p 00000000 00&#8203;:00 0 
b7364000\-b7380000 r\-xp 00000000 08&#8203;:01 1219379    /usr/local/lib/libgcc\_s\.so\.1
b7380000\-b7381000 rw\-p 0001b000 08&#8203;:01 1219379    /usr/local/lib/libgcc\_s\.so\.1
b7391000\-b751f000 r\-\-p 00000000 08&#8203;:01 1209425    /usr/lib/locale/locale\-archive
b751f000\-b7521000 rw\-p 00000000 00&#8203;:00 0 
b7521000\-b76d1000 r\-xp 00000000 08&#8203;:01 858184     /lib/libc\-2\.22\.so
b76d1000\-b76d3000 r\-\-p 001b0000 08&#8203;:01 858184     /lib/libc\-2\.22\.so
b76d3000\-b76d4000 rw\-p 001b2000 08&#8203;:01 858184     /lib/libc\-2\.22\.so
b76d4000\-b76d7000 rw\-p 00000000 00&#8203;:00 0 
b76d7000\-b76d9000 r\-xp 00000000 08&#8203;:01 858182     /lib/libutil\-2\.22\.so
b76d9000\-b76da000 r\-\-p 00001000 08&#8203;:01 858182     /lib/libutil\-2\.22\.so
b76da000\-b76db000 rw\-p 00002000 08&#8203;:01 858182     /lib/libutil\-2\.22\.so
b76db000\-b76e4000 r\-xp 00000000 08&#8203;:01 439490     /lib/libcrypt\-2\.22\.so
b76e4000\-b76e5000 r\-\-p 00008000 08&#8203;:01 439490     /lib/libcrypt\-2\.22\.so
b76e5000\-b76e6000 rw\-p 00009000 08&#8203;:01 439490     /lib/libcrypt\-2\.22\.so
b76e6000\-b770e000 rw\-p 00000000 00&#8203;:00 0 
b770e000\-b7759000 r\-xp 00000000 08&#8203;:01 858147     /lib/libm\-2\.22\.so
b7759000\-b775a000 r\-\-p 0004b000 08&#8203;:01 858147     /lib/libm\-2\.22\.so
b775a000\-b775b000 rw\-p 0004c000 08&#8203;:01 858147     /lib/libm\-2\.22\.so
b775b000\-b775e000 r\-xp 00000000 08&#8203;:01 858149     /lib/libdl\-2\.22\.so
b775e000\-b775f000 r\-\-p 00002000 08&#8203;:01 858149     /lib/libdl\-2\.22\.so
b775f000\-b7760000 rw\-p 00003000 08&#8203;:01 858149     /lib/libdl\-2\.22\.so
b7760000\-b7777000 r\-xp 00000000 08&#8203;:01 858160     /lib/libnsl\-2\.22\.so
b7777000\-b7778000 r\-\-p 00016000 08&#8203;:01 858160     /lib/libnsl\-2\.22\.so
b7778000\-b7779000 rw\-p 00017000 08&#8203;:01 858160     /lib/libnsl\-2\.22\.so
b7779000\-b777b000 rw\-p 00000000 00&#8203;:00 0 
b777b000\-b7794000 r\-xp 00000000 08&#8203;:01 439491     /lib/libpthread\-2\.22\.so
b7794000\-b7795000 r\-\-p 00018000 08&#8203;:01 439491     /lib/libpthread\-2\.22\.so
b7795000\-b7796000 rw\-p 00019000 08&#8203;:01 439491     /lib/libpthread\-2\.22\.so
b7796000\-b7798000 rw\-p 00000000 00&#8203;:00 0 
b779c000\-b779d000 rw\-p 00000000 00&#8203;:00 0 
b779d000\-b77a7000 r\-xp 00000000 08&#8203;:01 216674     /usr/local/perl\-afl/lib/5\.23\.4/i686\-linux\-64int\-ld/auto/arybase/arybase\.so
b77a7000\-b77a8000 rw\-p 00009000 08&#8203;:01 216674     /usr/local/perl\-afl/lib/5\.23\.4/i686\-linux\-64int\-ld/auto/arybase/arybase\.so
b77a8000\-b77a9000 rw\-p 00000000 00&#8203;:00 0 
b77a9000\-b77aa000 r\-xp 00000000 00&#8203;:00 0          \[vdso\]
b77aa000\-b77cc000 r\-xp 00000000 08&#8203;:01 858183     /lib/ld\-2\.22\.so
b77cc000\-b77cd000 r\-\-p 00021000 08&#8203;:01 858183     /lib/ld\-2\.22\.so
b77cd000\-b77ce000 rw\-p 00022000 08&#8203;:01 858183     /lib/ld\-2\.22\.so
bf88d000\-bf8a2000 rw\-p 00000000 00&#8203;:00 0          \[stack\]
Aborted


\*\*GDB\*\*

Program received signal SIGABRT\, Aborted\.
0xb7fdb424 in \_\_kernel\_vsyscall \(\)
\(gdb\) bt  
\#0  0xb7fdb424 in \_\_kernel\_vsyscall \(\)
\#1  0xb7d7ebd6 in \_\_GI\_raise \(sig=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:55
\#2  0xb7d801a7 in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#3  0xb7dbbca0 in \_\_libc\_message \(do\_abort=2\, 
&nbsp;    fmt=0xb7eb31d0 "\*\*\* Error in \`%s'&#8203;: %s&#8203;: 0x%s \*\*\*\\n"\)
&nbsp;    at \.\./sysdeps/posix/libc\_fatal\.c&#8203;:175
\#4  0xb7dc1ef7 in malloc\_printerr \(action=\<optimized out>\, 
&nbsp;    str=0xb7eb3240 "double free or corruption \(\!prev\)"\, ptr=\<optimized out>\, 
&nbsp;    ar\_ptr=0xb7f05780 \<main\_arena>\) at malloc\.c&#8203;:5000
\#5  0xb7dc26a1 in \_int\_free \(av=0xb7f05780 \<main\_arena>\, p=\<optimized out>\, 
&nbsp;    have\_lock=0\) at malloc\.c&#8203;:3861
\#6  0x0838b2c9 in Perl\_sv\_clear \(orig\_sv=0x87ece88\) at sv\.c&#8203;:6606
\#7  0x08386cd1 in Perl\_sv\_free2 \(sv=0x87ece88\, rc=1\) at sv\.c&#8203;:6881
\#8  0x0845e6ea in S\_SvREFCNT\_dec\_NN \(sv=\<optimized out>\) at inline\.h&#8203;:177
\#9  Perl\_free\_tmps \(\) at scope\.c&#8203;:182
\#10 0x08116ec5 in perl\_run \(my\_perl=0x87da008\) at perl\.c&#8203;:2384
\#11 0x08068972 in main \(argc=2\, argv=0xbffff484\, env=0xbffff490\)
&nbsp;    at perlmain\.c&#8203;:116
\(gdb\) 


\*\*VALGRIND\*\*

As usual\, valgrind seems to modify the behavior slightly\, but this call to memmove\(\) on blocks of memory that are already freed seems to be quite relevant\.

dcollins@&#8203;nightshade&#8203;:/usr/local/perl\-afl/out$ valgrind \.\./bin/perl f2/crashes/id\\&#8203;:000000\\\,sig\\&#8203;:06\\\,src\\&#8203;:006941\+020231\\\,op\\&#8203;:splice\\\,rep\\&#8203;:2
==28572== Memcheck\, a memory error detector
==28572== Copyright \(C\) 2002\-2013\, and GNU GPL'd\, by Julian Seward et al\.
==28572== Using Valgrind\-3\.10\.1 and LibVEX; rerun with \-h for copyright info
==28572== Command&#8203;: \.\./bin/perl f2/crashes/id&#8203;:000000\,sig&#8203;:06\,src&#8203;:006941\+020231\,op&#8203;:splice\,rep&#8203;:2
==28572== 
==28572== Invalid write of size 1
==28572==    at 0x83CB717&#8203;: Perl\_sv\_setpvn \(sv\.c&#8203;:4851\)
==28572==    by 0x835594F&#8203;: Perl\_pp\_concat \(pp\_hot\.c&#8203;:286\)
==28572==    by 0x835106A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==28572==    by 0x8116EB6&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==28572==    by 0x8116EB6&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==28572==    by 0x8068971&#8203;: main \(perlmain\.c&#8203;:116\)
==28572==  Address 0x4303238 is 0 bytes inside a block of size 10 free'd
==28572==    at 0x402B0B0&#8203;: free \(vg\_replace\_malloc\.c&#8203;:473\)
==28572==    by 0x838B2C8&#8203;: Perl\_sv\_clear \(sv\.c&#8203;:6606\)
==28572==    by 0x8386CD0&#8203;: Perl\_sv\_free2 \(sv\.c&#8203;:6881\)
==28572==    by 0x811B455&#8203;: S\_SvREFCNT\_dec \(inline\.h&#8203;:166\)
==28572==    by 0x811B455&#8203;: Perl\_gp\_free \(gv\.c&#8203;:2539\)
==28572==    by 0x83AB7C8&#8203;: Perl\_sv\_setsv\_flags \(sv\.c&#8203;:4507\)
==28572==    by 0x835392E&#8203;: Perl\_pp\_sassign \(pp\_hot\.c&#8203;:225\)
==28572==    by 0x835106A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==28572==    by 0x8116EB6&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==28572==    by 0x8116EB6&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==28572==    by 0x8068971&#8203;: main \(perlmain\.c&#8203;:116\)
==28572== 
==28572== Invalid write of size 4
==28572==    at 0x402DAB2&#8203;: \_\_GI\_memmove \(vg\_replace\_strmem\.c&#8203;:1110\)
==28572==    by 0x83C7194&#8203;: memmove \(string3\.h&#8203;:59\)
==28572==    by 0x83C7194&#8203;: Perl\_sv\_catpvn\_flags \(sv\.c&#8203;:5370\)
==28572==    by 0x83555B4&#8203;: Perl\_pp\_concat \(pp\_hot\.c&#8203;:310\)
==28572==    by 0x835106A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==28572==    by 0x8116EB6&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==28572==    by 0x8116EB6&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==28572==    by 0x8068971&#8203;: main \(perlmain\.c&#8203;:116\)
==28572==  Address 0x4303238 is 0 bytes inside a block of size 10 free'd
==28572==    at 0x402B0B0&#8203;: free \(vg\_replace\_malloc\.c&#8203;:473\)
==28572==    by 0x838B2C8&#8203;: Perl\_sv\_clear \(sv\.c&#8203;:6606\)
==28572==    by 0x8386CD0&#8203;: Perl\_sv\_free2 \(sv\.c&#8203;:6881\)
==28572==    by 0x811B455&#8203;: S\_SvREFCNT\_dec \(inline\.h&#8203;:166\)
==28572==    by 0x811B455&#8203;: Perl\_gp\_free \(gv\.c&#8203;:2539\)
==28572==    by 0x83AB7C8&#8203;: Perl\_sv\_setsv\_flags \(sv\.c&#8203;:4507\)
==28572==    by 0x835392E&#8203;: Perl\_pp\_sassign \(pp\_hot\.c&#8203;:225\)
==28572==    by 0x835106A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==28572==    by 0x8116EB6&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==28572==    by 0x8116EB6&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==28572==    by 0x8068971&#8203;: main \(perlmain\.c&#8203;:116\)
==28572== 
==28572== Invalid write of size 2
==28572==    at 0x402DB23&#8203;: \_\_GI\_memmove \(vg\_replace\_strmem\.c&#8203;:1110\)
==28572==    by 0x83C7194&#8203;: memmove \(string3\.h&#8203;:59\)
==28572==    by 0x83C7194&#8203;: Perl\_sv\_catpvn\_flags \(sv\.c&#8203;:5370\)
==28572==    by 0x83555B4&#8203;: Perl\_pp\_concat \(pp\_hot\.c&#8203;:310\)
==28572==    by 0x835106A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==28572==    by 0x8116EB6&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==28572==    by 0x8116EB6&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==28572==    by 0x8068971&#8203;: main \(perlmain\.c&#8203;:116\)
==28572==  Address 0x4303244 is 2 bytes after a block of size 10 free'd
==28572==    at 0x402B0B0&#8203;: free \(vg\_replace\_malloc\.c&#8203;:473\)
==28572==    by 0x838B2C8&#8203;: Perl\_sv\_clear \(sv\.c&#8203;:6606\)
==28572==    by 0x8386CD0&#8203;: Perl\_sv\_free2 \(sv\.c&#8203;:6881\)
==28572==    by 0x811B455&#8203;: S\_SvREFCNT\_dec \(inline\.h&#8203;:166\)
==28572==    by 0x811B455&#8203;: Perl\_gp\_free \(gv\.c&#8203;:2539\)
==28572==    by 0x83AB7C8&#8203;: Perl\_sv\_setsv\_flags \(sv\.c&#8203;:4507\)
==28572==    by 0x835392E&#8203;: Perl\_pp\_sassign \(pp\_hot\.c&#8203;:225\)
==28572==    by 0x835106A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==28572==    by 0x8116EB6&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==28572==    by 0x8116EB6&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==28572==    by 0x8068971&#8203;: main \(perlmain\.c&#8203;:116\)
==28572== 
==28572== Invalid write of size 1
==28572==    at 0x83C71D8&#8203;: Perl\_sv\_catpvn\_flags \(sv\.c&#8203;:5392\)
==28572==    by 0x83555B4&#8203;: Perl\_pp\_concat \(pp\_hot\.c&#8203;:310\)
==28572==    by 0x835106A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==28572==    by 0x8116EB6&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==28572==    by 0x8116EB6&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==28572==    by 0x8068971&#8203;: main \(perlmain\.c&#8203;:116\)
==28572==  Address 0x4303246 is 4 bytes after a block of size 10 free'd
==28572==    at 0x402B0B0&#8203;: free \(vg\_replace\_malloc\.c&#8203;:473\)
==28572==    by 0x838B2C8&#8203;: Perl\_sv\_clear \(sv\.c&#8203;:6606\)
==28572==    by 0x8386CD0&#8203;: Perl\_sv\_free2 \(sv\.c&#8203;:6881\)
==28572==    by 0x811B455&#8203;: S\_SvREFCNT\_dec \(inline\.h&#8203;:166\)
==28572==    by 0x811B455&#8203;: Perl\_gp\_free \(gv\.c&#8203;:2539\)
==28572==    by 0x83AB7C8&#8203;: Perl\_sv\_setsv\_flags \(sv\.c&#8203;:4507\)
==28572==    by 0x835392E&#8203;: Perl\_pp\_sassign \(pp\_hot\.c&#8203;:225\)
==28572==    by 0x835106A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==28572==    by 0x8116EB6&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==28572==    by 0x8116EB6&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==28572==    by 0x8068971&#8203;: main \(perlmain\.c&#8203;:116\)
==28572== 
==28572== Invalid read of size 1
==28572==    at 0x402DAE0&#8203;: \_\_GI\_memmove \(vg\_replace\_strmem\.c&#8203;:1110\)
==28572==    by 0x83C7194&#8203;: memmove \(string3\.h&#8203;:59\)
==28572==    by 0x83C7194&#8203;: Perl\_sv\_catpvn\_flags \(sv\.c&#8203;:5370\)
==28572==    by 0x83555B4&#8203;: Perl\_pp\_concat \(pp\_hot\.c&#8203;:310\)
==28572==    by 0x835106A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==28572==    by 0x8116EB6&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==28572==    by 0x8116EB6&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==28572==    by 0x8068971&#8203;: main \(perlmain\.c&#8203;:116\)
==28572==  Address 0x4303238 is 0 bytes inside a block of size 10 free'd
==28572==    at 0x402B0B0&#8203;: free \(vg\_replace\_malloc\.c&#8203;:473\)
==28572==    by 0x838B2C8&#8203;: Perl\_sv\_clear \(sv\.c&#8203;:6606\)
==28572==    by 0x8386CD0&#8203;: Perl\_sv\_free2 \(sv\.c&#8203;:6881\)
==28572==    by 0x811B455&#8203;: S\_SvREFCNT\_dec \(inline\.h&#8203;:166\)
==28572==    by 0x811B455&#8203;: Perl\_gp\_free \(gv\.c&#8203;:2539\)
==28572==    by 0x83AB7C8&#8203;: Perl\_sv\_setsv\_flags \(sv\.c&#8203;:4507\)
==28572==    by 0x835392E&#8203;: Perl\_pp\_sassign \(pp\_hot\.c&#8203;:225\)
==28572==    by 0x835106A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==28572==    by 0x8116EB6&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==28572==    by 0x8116EB6&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==28572==    by 0x8068971&#8203;: main \(perlmain\.c&#8203;:116\)
==28572== 
==28572== Invalid read of size 1
==28572==    at 0x402DAEB&#8203;: \_\_GI\_memmove \(vg\_replace\_strmem\.c&#8203;:1110\)
==28572==    by 0x83C7194&#8203;: memmove \(string3\.h&#8203;:59\)
==28572==    by 0x83C7194&#8203;: Perl\_sv\_catpvn\_flags \(sv\.c&#8203;:5370\)
==28572==    by 0x83555B4&#8203;: Perl\_pp\_concat \(pp\_hot\.c&#8203;:310\)
==28572==    by 0x835106A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==28572==    by 0x8116EB6&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==28572==    by 0x8116EB6&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==28572==    by 0x8068971&#8203;: main \(perlmain\.c&#8203;:116\)
==28572==  Address 0x430323a is 2 bytes inside a block of size 10 free'd
==28572==    at 0x402B0B0&#8203;: free \(vg\_replace\_malloc\.c&#8203;:473\)
==28572==    by 0x838B2C8&#8203;: Perl\_sv\_clear \(sv\.c&#8203;:6606\)
==28572==    by 0x8386CD0&#8203;: Perl\_sv\_free2 \(sv\.c&#8203;:6881\)
==28572==    by 0x811B455&#8203;: S\_SvREFCNT\_dec \(inline\.h&#8203;:166\)
==28572==    by 0x811B455&#8203;: Perl\_gp\_free \(gv\.c&#8203;:2539\)
==28572==    by 0x83AB7C8&#8203;: Perl\_sv\_setsv\_flags \(sv\.c&#8203;:4507\)
==28572==    by 0x835392E&#8203;: Perl\_pp\_sassign \(pp\_hot\.c&#8203;:225\)
==28572==    by 0x835106A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==28572==    by 0x8116EB6&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==28572==    by 0x8116EB6&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==28572==    by 0x8068971&#8203;: main \(perlmain\.c&#8203;:116\)
==28572== 
==28572== 
==28572== HEAP SUMMARY&#8203;:
==28572==     in use at exit&#8203;: 136\,520 bytes in 805 blocks
==28572==   total heap usage&#8203;: 1\,414 allocs\, 609 frees\, 226\,471 bytes allocated
==28572== 
==28572== LEAK SUMMARY&#8203;:
==28572==    definitely lost&#8203;: 0 bytes in 0 blocks
==28572==    indirectly lost&#8203;: 0 bytes in 0 blocks
==28572==      possibly lost&#8203;: 16\,925 bytes in 9 blocks
==28572==    still reachable&#8203;: 119\,595 bytes in 796 blocks
==28572==         suppressed&#8203;: 0 bytes in 0 blocks
==28572== Rerun with \-\-leak\-check=full to see details of leaked memory
==28572== 
==28572== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==28572== ERROR SUMMARY&#8203;: 21 errors from 6 contexts \(suppressed&#8203;: 0 from 0\)


\*\*PERL \-V\*\*

dcollins@&#8203;nightshade&#8203;:/usr/local/perl\-afl/out$ \.\./bin/perl \-V
Summary of my perl5 \(revision 5 version 23 subversion 4\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 7a36e618ad808bf649080137e3fb56386d8420e3
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.32\-5\-686\, archname=i686\-linux\-64int\-ld
&nbsp;    uname='linux nightshade 2\.6\.32\-5\-686 \#1 smp tue may 13 16&#8203;:33&#8203;:32 utc 2014 i686 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitint \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=undef\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='5\.2\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12\, longdblkind=3
&nbsp;    ivtype='long long'\, ivsize=8\, nvtype='long double'\, nvsize=12\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/i686\-pc\-linux\-gnu/5\.2\.0/include\-fixed /usr/lib /lib/\.\./lib /usr/lib/\.\./lib /lib /usr/lib/i486\-linux\-gnu /usr/lib64
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.22\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.22'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_INT
&nbsp;                        USE\_LARGE\_FILES USE\_LOCALE USE\_LOCALE\_COLLATE
&nbsp;                        USE\_LOCALE\_CTYPE USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME
&nbsp;                        USE\_LONG\_DOUBLE USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Sep 24 2015 13&#8203;:01&#8203;:10
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4/i686\-linux\-64int\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4/i686\-linux\-64int\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.3
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.2
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From perl@profvince.com



Le 26/09/2015 16&#8203;:42\, Dan Collins \(via RT\) a écrit :
> \# New Ticket Created by  Dan Collins
> \# Please include the string&#8203;:  \[perl \#126199\]
> \# in the subject line of all future correspondence about this issue\.
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126199 >
>
>
> Greetings Porters\,
>
> I have compiled bleadperl with the afl\-gcc compiler using&#8203;:
>
> \./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitint \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
> AFL\_HARDEN=1 make && make test
>
> And then fuzzed the resulting binary using&#8203;:
>
> AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;
>
> After reducing testcases using \`afl\-tmin\` and filtering out testcases that are merely iterations of "\#\!perl \-u"\, I have located the following testcase that triggers a double free in the perl interpreter\. The testcase is the 134\-character file&#8203;:
>
> du\_S\.Ak\.SA\.=$\[\.=\_\.Ak\.SA\.=$\[\.=$\[=$$$\_S\.Ak\.S\.=$\[\.=$\[=$$$A\.k\.SA\.=$\[\.=\*\[=$$$\_S\.AkAk\.SA\.=%\[=\_\_S\.Ak\.SA\.=$\[\.=$\[=$S\.Ak\.SA\.=$\[\.=\_\.Ak\.SA\.=$\[\.$$$

Using a debugging and poisonous perl\, I can reduce this to :

$\[ \.= \*\[ = 'y'

which seems to be yet another incarnation of the "stack is not 
refcounted" bug\.


Vincent

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'
