### ISSUE TITLE
SIGFPE integer divide by zero in S_make_trie

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14945]
Migrated from [rt.perl.org#126206](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126206) (status was 'resolved')

Searchable as RT126206$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitint \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers a floating point exception in the perl interpreter\. The testcase is the attached 11\-character file&#8203;:

dcollins@&#8203;nagios&#8203;:\~/perl$ od \-c /usr/local/perl\-afl/out/allcrash/f3i000002
0000000   t   \.   /   \\   N   \{   \} 337   |   /   i

This is very similar to \[perl \#125990\]\, however this testcase never triggered that bug\, and was presumably missed when the fuzzer found it alongside the many testcases that did\. A debugging perl produces no other interesting output\.

The version of 5\.20\.2 that shipped with my Debian does not have this bug\. The result of a bisect run is shown below\, and the problem does arise from the same commit\, where \\N\{\} forces /d to /u\. 

\*\*GDB\*\*

dcollins@&#8203;nagios&#8203;:\~/perl$ gdb \-\-args \./perl /usr/local/perl\-afl/out/allcrash/f3i000002
GNU gdb \(GDB\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "i686\-pc\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from \./perl\.\.\.done\.
\(gdb\) run
Starting program&#8203;: /home/dcollins/perl/perl /usr/local/perl\-afl/out/allcrash/f3i000002
bt\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/libthread\_db\.so\.1"\.

Program received signal SIGFPE\, Arithmetic exception\.
0x08119636 in S\_make\_trie \(pRExC\_state=0xbfffed64\, startbranch=0x8477d8c\, 
&nbsp;    first=0x8477d8c\, last=0x8477da4\, tail=0x8477da4\, word\_count=2\, flags=35\, 
&nbsp;    depth=1\) at regcomp\.c&#8203;:2775
2775                accept\_state = TRIE\_NODENUM\( state \);
\(gdb\) bt
\#0  0x08119636 in S\_make\_trie \(pRExC\_state=0xbfffed64\, startbranch=0x8477d8c\, 
&nbsp;    first=0x8477d8c\, last=0x8477da4\, tail=0x8477da4\, word\_count=2\, flags=35\, 
&nbsp;    depth=1\) at regcomp\.c&#8203;:2775
\#1  0x08123811 in S\_study\_chunk \(pRExC\_state=0xbfffed64\, scanp=0xbfffeb54\, 
&nbsp;    minlenp=0xbfffeb5c\, deltap=0xbfffeb68\, last=0x8477da8\, data=0xbfffece4\, 
&nbsp;    stopparen=\-1\, recursed\_depth=0\, and\_withp=0x8478f60\, flags=12288\, depth=0\)
&nbsp;    at regcomp\.c&#8203;:4368
\#2  0x08132920 in Perl\_re\_op\_compile \(patternp=0x0\, pat\_count=1\, 
&nbsp;    expr=0x8477cdc\, eng=0x83917e0 \<PL\_core\_reg\_engine>\, old\_re=0x0\, 
&nbsp;    is\_bare\_re=0x0\, orig\_rx\_flags=4\, pm\_flags=4\) at regcomp\.c&#8203;:7296
\#3  0x08071183 in Perl\_pmruntime \(o=0x8477ca4\, expr=0x8477cdc\, repl=0x0\, 
&nbsp;    isreg=true\, floor=0\) at op\.c&#8203;:5579
\#4  0x08107385 in Perl\_yyparse \(gramtype=258\) at perly\.y&#8203;:1038
\#5  0x0809b04e in S\_parse\_body \(env=0x0\, xsinit=0x80612f8 \<xs\_init>\)
&nbsp;    at perl\.c&#8203;:2304
\#6  0x0809983a in perl\_parse \(my\_perl=0x845d008\, xsinit=0x80612f8 \<xs\_init>\, 
&nbsp;    argc=2\, argv=0xbffff4a4\, env=0x0\) at perl\.c&#8203;:1634
\#7  0x08061252 in main \(argc=2\, argv=0xbffff4a4\, env=0xbffff4b0\)
&nbsp;    at perlmain\.c&#8203;:114
\(gdb\) info locals
uc = 0x8477d94 "\\002%\\004"
e = 0x8477d94 "\\002%\\004"
state = 1
accept\_state = 0
wordlen = 0
noper = 0x8477d90
charid = 0
trie = 0x8478fe0
widecharmap = 0x0
revcharmap = 0x8470614
cur = 0x8477d8c
len = 0
uvc = 0
curword = 0
next\_alloc = 1
jumper = 0x0
nextbranch = 0x0
convert = 0x8477d8c
prev\_states = 0x8477d40
folder = 0x842e540 \<PL\_fold\_latin1> ""
data\_slot = 0
trie\_words = 0x0
re\_trie\_maxbuff = 0x8470600
re\_debug\_flags = 0
\_\_PRETTY\_FUNCTION\_\_ = "S\_make\_trie"


\*\*VALGRIND\*\*

dcollins@&#8203;nagios&#8203;:\~/perl$ valgrind \./perl /usr/local/perl\-afl/out/allcrash/f3i000002
==16731== Memcheck\, a memory error detector
==16731== Copyright \(C\) 2002\-2013\, and GNU GPL'd\, by Julian Seward et al\.
==16731== Using Valgrind\-3\.10\.1 and LibVEX; rerun with \-h for copyright info
==16731== Command&#8203;: \./perl /usr/local/perl\-afl/out/allcrash/f3i000002
==16731== 
==16731== 
==16731== Process terminating with default action of signal 8 \(SIGFPE\)
==16731==  Integer divide by zero at address 0x6356C3A2
==16731==    at 0x811963B&#8203;: S\_make\_trie \(regcomp\.c&#8203;:2775\)
==16731==    by 0x8123810&#8203;: S\_study\_chunk \(regcomp\.c&#8203;:4368\)
==16731==    by 0x813291F&#8203;: Perl\_re\_op\_compile \(regcomp\.c&#8203;:7296\)
==16731==    by 0x8071182&#8203;: Perl\_pmruntime \(op\.c&#8203;:5579\)
==16731==    by 0x8107384&#8203;: Perl\_yyparse \(perly\.y&#8203;:1038\)
==16731==    by 0x809B04D&#8203;: S\_parse\_body \(perl\.c&#8203;:2304\)
==16731==    by 0x8099839&#8203;: perl\_parse \(perl\.c&#8203;:1634\)
==16731==    by 0x8061251&#8203;: main \(perlmain\.c&#8203;:114\)
==16731== 
==16731== HEAP SUMMARY&#8203;:
==16731==     in use at exit&#8203;: 108\,665 bytes in 658 blocks
==16731==   total heap usage&#8203;: 752 allocs\, 94 frees\, 113\,684 bytes allocated
==16731== 
==16731== LEAK SUMMARY&#8203;:
==16731==    definitely lost&#8203;: 156 bytes in 1 blocks
==16731==    indirectly lost&#8203;: 2\,593 bytes in 37 blocks
==16731==      possibly lost&#8203;: 0 bytes in 0 blocks
==16731==    still reachable&#8203;: 105\,916 bytes in 620 blocks
==16731==         suppressed&#8203;: 0 bytes in 0 blocks
==16731== Rerun with \-\-leak\-check=full to see details of leaked memory
==16731== 
==16731== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==16731== ERROR SUMMARY&#8203;: 0 errors from 0 contexts \(suppressed&#8203;: 0 from 0\)
Floating point exception


\*\*BISECT\*\*

75697d6e4ef98ece405210de48e7529d01b619bf is the first bad commit
commit 75697d6e4ef98ece405210de48e7529d01b619bf
Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
Date&#8203;:   Sun Dec 21 22&#8203;:02&#8203;:30 2014 \-0700

&nbsp;    Empty \\N\{\} in regex pattern should force /d to /u
&nbsp;    
&nbsp;    \\N\{\} is for Unicode names\, even if the name is actually omitted\.
&nbsp;    \(Accepting an empty name is\, I believe\, an accident\, and now is
&nbsp;    supported only for backwards compatibility\.\)

:100644 100644 e6ddb803aae9f37f00d2f0f38fd109f05bf0bcb6 c2521a97ccee8d15370822c3b975be2628fcddb2 M    regcomp\.c
:040000 040000 218758eff11e9ad6989600b1a4a93ca23c3da3cf a6a3a35946820a1f6e9b6f99f414edc78099b63b M    t
bisect run success


\*\*PERL \-V\*\*

dcollins@&#8203;nagios&#8203;:\~/perl$ \./perl \-V
Summary of my perl5 \(revision 5 version 23 subversion 4\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 7a36e618ad808bf649080137e3fb56386d8420e3
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.32\-5\-686\, archname=i686\-linux\-64int\-ld
&nbsp;    uname='linux nagios 2\.6\.32\-5\-686 \#1 smp tue may 13 16&#8203;:33&#8203;:32 utc 2014 i686 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitint \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=undef\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='5\.2\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12\, longdblkind=3
&nbsp;    ivtype='long long'\, ivsize=8\, nvtype='long double'\, nvsize=12\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/i686\-pc\-linux\-gnu/5\.2\.0/include\-fixed /usr/lib /lib/\.\./lib /usr/lib/\.\./lib /lib /usr/lib/i486\-linux\-gnu /usr/lib64
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.22\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.22'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_INT
&nbsp;                        USE\_LARGE\_FILES USE\_LOCALE USE\_LOCALE\_COLLATE
&nbsp;                        USE\_LOCALE\_CTYPE USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME
&nbsp;                        USE\_LONG\_DOUBLE USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Sep 25 2015 21&#8203;:59&#8203;:04
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4/i686\-linux\-64int\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4/i686\-linux\-64int\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.3
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.2
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @dcollinsn

[f3i000002](https://rt-archive.perl.org/perl5/Ticket/Attachment/1368122/733430/f3i000002)

**Comment by p5pRT** [comment]
### From @dcollinsn

A simpler testcase&#8203;:

/\\N\{\}Ss|/i

\*\* GDB \*\* 

Starting program&#8203;: /usr/local/perl\-afl/bin/perl \-e /\\\\N\\\{\\\}Ss\\|/i
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.

Program received signal SIGFPE\, Arithmetic exception\.
0x00000000007497ce in S\_make\_trie \(pRExC\_state=0x7fffffffddc0\, startbranch=0x0\, first=0x0\, last=0x1e\, tail=0x3\, word\_count=18933704\, flags=35\, depth=1\) at regcomp\.c&#8203;:2847
2847            const U32 laststate = TRIE\_NODENUM\( next\_alloc \);
\(gdb\) bt
\#0  0x00000000007497ce in S\_make\_trie \(pRExC\_state=0x7fffffffddc0\, startbranch=0x0\, first=0x0\, last=0x1e\, tail=0x3\, word\_count=18933704\, flags=35\, depth=1\) at regcomp\.c&#8203;:2847
\#1  0x0000000000769d6c in S\_study\_chunk \(pRExC\_state=0x7fffffffdce0\, scanp=0x0\, minlenp=0x0\, deltap=0x1e\, last=0x3\, data=0x120e7b0\, stopparen=\-1\, recursed\_depth=0\, flags=10240\, depth=0\, and\_withp=\<optimized out>\) at regcomp\.c&#8203;:4368
\#2  0x00000000007998f8 in Perl\_re\_op\_compile \(patternp=0x120eae0\, pat\_count=0\, expr=0x120e7b0\, eng=0x1e\, old\_re=0x7\, is\_bare\_re=0x7fffffffdd80\, orig\_rx\_flags=4\, pm\_flags=4\) at regcomp\.c&#8203;:7296
\#3  0x00000000004e8872 in Perl\_pmruntime \(o=0x120e978\, expr=0x120e938\, repl=0x0\, isreg=30\, floor=7938400\) at op\.c&#8203;:5572
\#4  0x000000000066f2ed in Perl\_yyparse \(gramtype=18934136\) at perly\.y&#8203;:1038
\#5  0x000000000053a8d5 in S\_parse\_body \(env=env@&#8203;entry=0x0\, xsinit=xsinit@&#8203;entry=0x42c840 \<xs\_init>\) at perl\.c&#8203;:2304
\#6  0x0000000000542653 in perl\_parse \(my\_perl=\<optimized out>\, xsinit=xsinit@&#8203;entry=0x42c840 \<xs\_init>\, argc=\<optimized out>\, argv=\<optimized out>\, env=env@&#8203;entry=0x0\) at perl\.c&#8203;:1634
\#7  0x000000000042c468 in main \(argc=3\, argv=0x7fffffffe648\, env=0x7fffffffe668\) at perlmain\.c&#8203;:114
\(gdb\) info locals
state = 18933704
trie = 0x120fdd0
len = 0
uvc = 0
next\_alloc = 1
folder = 0xfbab40 \<PL\_fold\_latin1> ""
re\_debug\_flags = 0
\_\_PRETTY\_FUNCTION\_\_ = "S\_make\_trie"

\*\* VALGRIND \*\*

==15719== Memcheck\, a memory error detector
==15719== Copyright \(C\) 2002\-2015\, and GNU GPL'd\, by Julian Seward et al\.
==15719== Using Valgrind\-3\.11\.0 and LibVEX; rerun with \-h for copyright info
==15719== Command&#8203;: \.\./bin/perl \-e /\\\\N\{\}Ss|/i
==15719==
==15719==
==15719== Process terminating with default action of signal 8 \(SIGFPE\)
==15719==  Integer divide by zero at address 0x80418779B
==15719==    at 0x7497BC&#8203;: S\_make\_trie \(regcomp\.c&#8203;:2847\)
==15719==    by 0x769D6B&#8203;: S\_study\_chunk\.constprop\.51 \(regcomp\.c&#8203;:4368\)
==15719==    by 0x7998F7&#8203;: Perl\_re\_op\_compile \(regcomp\.c&#8203;:7296\)
==15719==    by 0x4E8871&#8203;: Perl\_pmruntime \(op\.c&#8203;:5572\)
==15719==    by 0x66F2EC&#8203;: Perl\_yyparse \(perly\.y&#8203;:1038\)
==15719==    by 0x53A8D4&#8203;: S\_parse\_body \(perl\.c&#8203;:2304\)
==15719==    by 0x542652&#8203;: perl\_parse \(perl\.c&#8203;:1634\)
==15719==    by 0x42C467&#8203;: main \(perlmain\.c&#8203;:114\)
==15719==
==15719== HEAP SUMMARY&#8203;:
==15719==     in use at exit&#8203;: 122\,004 bytes in 573 blocks
==15719==   total heap usage&#8203;: 662 allocs\, 89 frees\, 130\,332 bytes allocated
==15719==
==15719== LEAK SUMMARY&#8203;:
==15719==    definitely lost&#8203;: 176 bytes in 1 blocks
==15719==    indirectly lost&#8203;: 1\,993 bytes in 20 blocks
==15719==      possibly lost&#8203;: 16 bytes in 1 blocks
==15719==    still reachable&#8203;: 119\,819 bytes in 551 blocks
==15719==         suppressed&#8203;: 0 bytes in 0 blocks
==15719== Rerun with \-\-leak\-check=full to see details of leaked memory
==15719==
==15719== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==15719== ERROR SUMMARY&#8203;: 0 errors from 0 contexts \(suppressed&#8203;: 0 from 0\)
Floating point exception

\*\* PERL \-V \*\*

Summary of my perl5 \(revision 5 version 23 subversion 4\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 94757bf7ac8451b3588578f287f9c511a04011bf
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt11\-1\+deb8u4 \(2015\-09\-19\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.9\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/4\.9/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Sep 30 2015 16&#8203;:39&#8203;:59
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4
&nbsp;    \.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @demerphq

\\N\{\} was creating an EMPTY node\, which was tickling a secondary issue with trie construction from alternations with EXACTFU\_SS nodes in them\.  

commit 944e05e3d149b21eef2ceb8d255da390afb267a2
Author&#8203;: Yves Orton \<demerphq@&#8203;gmail\.com>
Date&#8203;:   Wed Mar 9 20&#8203;:00&#8203;:53 2016 \+0100

&nbsp;    Fix Perl \#126206&#8203;: handle NOTHING regops and EXACTFU\_SS regops in make\_trie\(\) properly
&nbsp;    
&nbsp;    \.\.\. and avoid dereffing non\-EXACT nodes unnecessarily at the same
&nbsp;    time\. This fixes https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126206

**Comment by p5pRT** [comment]
@demerphq - Status changed from 'open' to 'resolved'
