### ISSUE TITLE
Illegal division by zero leads to Assertion `(((U8)(*l) & 0xfe) == 0xc2)' failed.

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14964]
Migrated from [rt.perl.org#126260](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126260) (status was 'resolved')

Searchable as RT126260$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers an assert fail in the perl interpreter\, but which \(correctly\) errors out in non\-debugging perl\. The simplest testcase is the 30\-character file&#8203;:

/0\\G|0\+|/>>s>>\\x\{100\}>>s>>>g/0

In a not\-debugging perl\, the output is&#8203;:
Illegal division by zero at allcrash/f1i000171 line 1\.

In a debugging perl\, the output is&#8203;:
perl&#8203;: regexec\.c&#8203;:5389&#8203;: S\_regmatch&#8203;: Assertion \`\(\(\(U8\)\(\*l\) & 0xfe\) == 0xc2\)' failed\.
Aborted

\*\*GDB\*\*
Starting program&#8203;: /home/dcollins/perldebug/perl allcrash/f1i000171
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
perl&#8203;: regexec\.c&#8203;:5389&#8203;: S\_regmatch&#8203;: Assertion \`\(\(\(U8\)\(\*l\) & 0xfe\) == 0xc2\)' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6cf4107 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6cf4107 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x00007ffff6cf54e8 in abort \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#2  0x00007ffff6ced226 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#3  0x00007ffff6ced2d2 in \_\_assert\_fail \(\)
&nbsp;   from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#4  0x0000000000ce3bdd in S\_regmatch \(prog=\<optimized out>\,
&nbsp;    startpos=\<optimized out>\, reginfo=\<optimized out>\) at regexec\.c&#8203;:5389
\#5  S\_regtry \(reginfo=0x5fd4\, startposp=0x5fd4\) at regexec\.c&#8203;:3524
\#6  0x0000000000d2310d in Perl\_regexec\_flags \(rx=0x1206a30\,
&nbsp;    stringarg=0x5fd4 \<error&#8203;: Cannot access memory at address 0x5fd4>\,
&nbsp;    strend=0x11ffef2 ""\, strbeg=0x11ffef0 "Ā"\, minend=0\, sv=0x1212cf0\,
&nbsp;    data=0x0\, flags=152\) at regexec\.c&#8203;:3385
\#7  0x000000000090250f in Perl\_pp\_subst \(\) at pp\_hot\.c&#8203;:3054
\#8  0x00000000007df04f in Perl\_runops\_debug \(\) at dump\.c&#8203;:2224
\#9  0x00000000005448e9 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2456
\#10 perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2379
\#11 0x000000000042c708 in main \(argc=2\, argv=0x7fffffffe658\,
&nbsp;    env=0x7fffffffe670\) at perlmain\.c&#8203;:116
\(gdb\) f 4
\#4  0x0000000000ce3bdd in S\_regmatch \(prog=\<optimized out>\,
&nbsp;    startpos=\<optimized out>\, reginfo=\<optimized out>\) at regexec\.c&#8203;:5389
5389                                if \(EIGHT\_BIT\_UTF8\_TO\_NATIVE\(\*l\, \*\(l\+1\)\) \!= \* \(U8\*\) s\)
\(gdb\) info locals
e = 0x6 \<error&#8203;: Cannot access memory at address 0x6>
s = 0x5fd4 \<error&#8203;: Cannot access memory at address 0x5fd4>
state\_num = 128
re\_debug\_flags = 0
classnum = 18874098
nextchr = 8
maxopenparen = 0
result = 128


\*\*PERL \-V\*\*
dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-V
Summary of my perl5 \(revision 5 version 23 subversion 4\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 94757bf7ac8451b3588578f287f9c511a04011bf
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt11\-1\+deb8u4 \(2015\-09\-19\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.9\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/4\.9/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Oct  2 2015 22&#8203;:41&#8203;:42
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Oct 04\, 2015 at 07&#8203;:02&#8203;:09AM \-0700\, Dan Collins wrote&#8203;:
> /0\\G|0\+|/>>s>>\\x\{100\}>>s>>>g/0
> 
> In a not\-debugging perl\, the output is&#8203;:
> Illegal division by zero at allcrash/f1i000171 line 1\.
> 
> In a debugging perl\, the output is&#8203;:
> perl&#8203;: regexec\.c&#8203;:5389&#8203;: S\_regmatch&#8203;: Assertion \`\(\(\(U8\)\(\*l\) & 0xfe\) == 0xc2\)' failed\.
> Aborted

The division by zero was a slight red herring; the assertion failure
actually happened during the substitution preceding it\.

Should be fixed by the following&#8203;:

commit 4cf1a8671a76422d533dc736bb493fe337c71937
Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
AuthorDate&#8203;: Wed Dec 2 14&#8203;:53&#8203;:59 2015 \+0000
Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
CommitDate&#8203;: Wed Dec 2 15&#8203;:13&#8203;:59 2015 \+0000

&nbsp;    /\.\.\\G/&#8203;: use chars\, not bytes
&nbsp;    
&nbsp;    In something like /\.\.\\G/\, the engine should start trying to match two
&nbsp;    chars before pos\(\)\. It was actually trying to match two bytes before\.

\-\- 
Fire extinguisher \(n\) a device for holding open fire doors\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for submitting this report\.  You have helped make Perl better\.
&nbsp;    
With the release of Perl 5\.24\.0 on May 9\, 2016\, this and 149 other issues have been resolved\.

Perl 5\.24\.0 may be downloaded via https://metacpan.org/release/RJBS/perl-5.24.0

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
