### ISSUE TITLE
grep and map lead to Perl_op_free: Assertion `!(o->op_private & ~PL_op_private_valid[type])' failed.

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14963]
Migrated from [rt.perl.org#126258](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126258) (status was 'resolved')

Searchable as RT126258$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers an assert fail in the perl interpreter\, but which \(correctly\) errors out in non\-debugging perl\. The simplest testcase is the 9\-character file&#8203;:

grep$0\,0\}

In a not\-debugging perl\, the output is&#8203;:
Unmatched right curly bracket at \.\./uncat/f3i000003 line 1\, at end of line
syntax error at \.\./uncat/f3i000003 line 1\, near "0\}"
Execution of \.\./uncat/f3i000003 aborted due to compilation errors\.

In a debugging perl\, the output is&#8203;:
Unmatched right curly bracket at \.\./uncat/f3i000003 line 1\, at end of line
syntax error at \.\./uncat/f3i000003 line 1\, near "0\}"
Execution of \.\./uncat/f3i000003 aborted due to compilation errors\.
perl&#8203;: op\.c&#8203;:717&#8203;: Perl\_op\_free&#8203;: Assertion \`\!\(o\->op\_private & ~PL\_op\_private\_valid\[type\]\)' failed\.
Aborted

Other failing testcases that might help you understand what's going on here&#8203;:
grep$0\,0\}
map\\0\,0\} \<\<\-\-\- Literal backslash
map\\n0\,0\} \<\<\-\-\- Literal newline
0%grep\{\.\}0
0%N\{\.\}0%grep%0\,0
map\\nmap\,0 \<\<\-\-\- Literal newline

\*\*GDB\*\*
dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ gdb \-\-args \./perl \-Ilib \.\./uncat/f3i000003   GNU gdb \(GDB\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-unknown\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from \./perl\.\.\.done\.
\(gdb\) run
Starting program&#8203;: /home/dcollins/perldebug/perl \-Ilib \.\./uncat/f3i000003
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
Unmatched right curly bracket at \.\./uncat/f3i000003 line 1\, at end of line
syntax error at \.\./uncat/f3i000003 line 1\, near "0\}"
Execution of \.\./uncat/f3i000003 aborted due to compilation errors\.
perl&#8203;: op\.c&#8203;:717&#8203;: Perl\_op\_free&#8203;: Assertion \`\!\(o\->op\_private & ~PL\_op\_private\_valid\[type\]\)' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6cf4107 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6cf4107 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x00007ffff6cf54e8 in abort \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#2  0x00007ffff6ced226 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#3  0x00007ffff6ced2d2 in \_\_assert\_fail \(\)
&nbsp;   from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#4  0x000000000043f359 in Perl\_op\_free \(o=0x12118b0\) at op\.c&#8203;:717
\#5  0x0000000000529301 in perl\_destruct \(my\_perl=\<optimized out>\)
&nbsp;    at perl\.c&#8203;:777
\#6  0x000000000042c660 in main \(argc=3\, argv=0x7fffffffe648\,
&nbsp;    env=0x7fffffffe668\) at perlmain\.c&#8203;:127
\(gdb\) frame 4
\#4  0x000000000043f359 in Perl\_op\_free \(o=0x12118b0\) at op\.c&#8203;:717
717                 assert\(\!\(o\->op\_private & ~PL\_op\_private\_valid\[type\]\)\);
\(gdb\) info locals
type = 169
defer\_ix = \<optimized out>
defer\_stack\_alloc = \<optimized out>
defer\_stack = \<optimized out>
\_\_PRETTY\_FUNCTION\_\_ = "Perl\_op\_free"


\*\*PERL \-V\*\*
dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-V
Summary of my perl5 \(revision 5 version 23 subversion 4\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 94757bf7ac8451b3588578f287f9c511a04011bf
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt11\-1\+deb8u4 \(2015\-09\-19\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.9\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/4\.9/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Oct  2 2015 22&#8203;:41&#8203;:42
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Oct 04\, 2015 at 04&#8203;:13&#8203;:28AM \-0700\, Dan Collins wrote&#8203;:
> I have compiled bleadperl with the afl\-gcc compiler using&#8203;:
> 
> \./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des
> AFL\_HARDEN=1 make && make test
> 
> And then fuzzed the resulting binary using&#8203;:
> 
> AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;
> 
> After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers an assert fail in the perl interpreter\, but which \(correctly\) errors out in non\-debugging perl\. The simplest testcase is the 9\-character file&#8203;:
> 
> grep$0\,0\}
\[snip\]
> In a debugging perl\, the output is&#8203;:
> Unmatched right curly bracket at \.\./uncat/f3i000003 line 1\, at end of line
> syntax error at \.\./uncat/f3i000003 line 1\, near "0\}"
> Execution of \.\./uncat/f3i000003 aborted due to compilation errors\.
> perl&#8203;: op\.c&#8203;:717&#8203;: Perl\_op\_free&#8203;: Assertion \`\!\(o\->op\_private & ~PL\_op\_private\_valid\[type\]\)' failed\.
> Aborted

I've pushed a general fix for these sorts of issues with&#8203;:

commit 09681a13f07600082e5a7efbc9c978f62b24c502
Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
AuthorDate&#8203;: Thu Nov 19 15&#8203;:49&#8203;:03 2015 \+0000
Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
CommitDate&#8203;: Thu Nov 19 16&#8203;:00&#8203;:31 2015 \+0000

&nbsp;    op\_free\(\)&#8203;: don't assert op\_private ok when erred
&nbsp;    
&nbsp;    \[perl \#126258\]
&nbsp;    
&nbsp;    op\_free includes an assert to make sure each op's op\_private field
&nbsp;    only has the flags set that are expected for that op\. It's a thing I added
&nbsp;    at the same time I added the regen/op\_private mechanism\, and is more a
&nbsp;    general "make sure people are only setting the flags we know about" test\.
&nbsp;    
&nbsp;    However\, if the op tree is being freed after a compilation error\, some
&nbsp;    op's flags may be in an inconsistent state; so skip the assert in that case\.
&nbsp;    
&nbsp;    e\.g\.
&nbsp;    
&nbsp;        perl \-e 'grep$0\,0\}'


\-\- 
Modern art&#8203;:
&nbsp;    "That's easy\, I could have done that\!"
&nbsp;    "Ah\, but you didn't\!"

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @mauke

Am 19\.11\.2015 um 17&#8203;:02 schrieb Dave Mitchell&#8203;:
> I've pushed a general fix for these sorts of issues with&#8203;:
>
> commit 09681a13f07600082e5a7efbc9c978f62b24c502
> Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
> AuthorDate&#8203;: Thu Nov 19 15&#8203;:49&#8203;:03 2015 \+0000
> Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
> CommitDate&#8203;: Thu Nov 19 16&#8203;:00&#8203;:31 2015 \+0000
>
>      op\_free\(\)&#8203;: don't assert op\_private ok when erred
>
>      \[perl \#126258\]
>
>      op\_free includes an assert to make sure each op's op\_private field
>      only has the flags set that are expected for that op\. It's a thing I added
>      at the same time I added the regen/op\_private mechanism\, and is more a
>      general "make sure people are only setting the flags we know about" test\.
>
>      However\, if the op tree is being freed after a compilation error\, some
>      op's flags may be in an inconsistent state; so skip the assert in that case\.
>
>      e\.g\.
>
>          perl \-e 'grep$0\,0\}'
>

 From this description I would have expected something like&#8203;:

&nbsp;     if \(\!\(PL\_parser && PL\_parser\->error\_count\)\) \{
&nbsp;         assert\(\.\.\.\);
&nbsp;     \}

i\.e\. assert unless we're currently parsing and there has been an error\.

But the patch actually does

&nbsp;     if \(PL\_parser && \!PL\_parser\->error\_count\) \{
&nbsp;         assert\(\.\.\.\);
&nbsp;     \}

Is this intentional?

\-\- 
Lukas Mai \<plokinom@&#8203;gmail\.com>

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Nov 19\, 2015 at 09&#8203;:22&#8203;:03PM \+0100\, Lukas Mai wrote&#8203;:
> From this description I would have expected something like&#8203;:
> 
>     if \(\!\(PL\_parser && PL\_parser\->error\_count\)\) \{
>         assert\(\.\.\.\);
>     \}
> 
> i\.e\. assert unless we're currently parsing and there has been an error\.
> 
> But the patch actually does
> 
>     if \(PL\_parser && \!PL\_parser\->error\_count\) \{
>         assert\(\.\.\.\);
>     \}
> 
> Is this intentional?

Yes\. If there's a compilation error in the main body of the program
\(as opposed to code that was evalled/required/used\)\, then by the time the
defective optree is is freed\, PL\_parser is already NULL&#8203;: so we have
no way of knowing whether it compiled ok or not; so always skip on a NULL
PL\_parser\.

\-\- 
"I do not resent criticism\, even when\, for the sake of emphasis\,
it parts for the time with reality"\.
&nbsp;    \-\- Winston Churchill\, House of Commons\, 22nd Jan 1941\.

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
