### ISSUE TITLE
Segmentation fault in Perl_sv_catpvn_flags

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14976]
Migrated from [rt.perl.org#126319](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126319) (status was 'resolved')

Searchable as RT126319$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers a segmentation fault in the perl interpreter\. The testcase is the file&#8203;:

/\\b\{sb\}\\b\{wb\}//b\{\}//>s>>>g>>0

The fuzzer seems to have started from the testcase in \[perl \#126260\]\, but is does not appear to be at all related \- that is a regexp related bug\, while this bug is occurring in sv\.c\.

\*\*GDB\*\*

\(gdb\) run
Starting program&#8203;: /usr/local/perl\-afl/bin/perl allcrash/f4i000027
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.

Program received signal SIGSEGV\, Segmentation fault\.
0x00007ffff6df5b9c in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6df5b9c in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x00000000009f5567 in memmove \(\_\_len=18446744073709551615\, \_\_src=0x1213001\, 
&nbsp;    \_\_dest=\<optimized out>\) at /usr/include/x86\_64\-linux\-gnu/bits/string3\.h&#8203;:57
\#2  Perl\_sv\_catpvn\_flags \(dsv=0x12056a0\, sstr=0x1213001 ""\, 
&nbsp;    slen=18446744073709551615\, flags=16384\) at sv\.c&#8203;:5370
\#3  0x000000000090410e in Perl\_pp\_subst \(\) at pp\_hot\.c&#8203;:3055
\#4  0x00000000007dec7f in Perl\_runops\_debug \(\) at dump\.c&#8203;:2224
\#5  0x0000000000544469 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2456
\#6  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2379
\#7  0x000000000042c6f8 in main \(argc=2\, argv=0x7fffffffe348\, env=0x7fffffffe360\)
&nbsp;    at perlmain\.c&#8203;:116


\*\*VALGRIND\*\*

==19889== Memcheck\, a memory error detector
==19889== Copyright \(C\) 2002\-2015\, and GNU GPL'd\, by Julian Seward et al\.
==19889== Using Valgrind\-3\.11\.0 and LibVEX; rerun with \-h for copyright info
==19889== Command&#8203;: \.\./bin/perl allcrash/f4i000027
==19889== 
==19889== Invalid write of size 8
==19889==    at 0x4C2C04B&#8203;: memcpy@&#8203;GLIBC\_2\.2\.5 \(vg\_replace\_strmem\.c&#8203;:1017\)
==19889==    by 0x9F5566&#8203;: memmove \(string3\.h&#8203;:57\)
==19889==    by 0x9F5566&#8203;: Perl\_sv\_catpvn\_flags \(sv\.c&#8203;:5370\)
==19889==    by 0x90410D&#8203;: Perl\_pp\_subst \(pp\_hot\.c&#8203;:3055\)
==19889==    by 0x7DEC7E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==19889==    by 0x544468&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==19889==    by 0x544468&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==19889==    by 0x42C6F7&#8203;: main \(perlmain\.c&#8203;:116\)
==19889==  Address 0x5f814c8 is 8 bytes inside a block of size 10 alloc'd
==19889==    at 0x4C27C0F&#8203;: malloc \(vg\_replace\_malloc\.c&#8203;:299\)
==19889==    by 0x7EFD6C&#8203;: Perl\_safesysmalloc \(util\.c&#8203;:153\)
==19889==    by 0x98BD5F&#8203;: Perl\_sv\_grow \(sv\.c&#8203;:1624\)
==19889==    by 0x9BBDBB&#8203;: Perl\_sv\_setpvn \(sv\.c&#8203;:4849\)
==19889==    by 0x9BD012&#8203;: Perl\_newSVpvn\_flags \(sv\.c&#8203;:9085\)
==19889==    by 0x901BF4&#8203;: Perl\_pp\_subst \(pp\_hot\.c&#8203;:3001\)
==19889==    by 0x7DEC7E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==19889==    by 0x544468&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==19889==    by 0x544468&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==19889==    by 0x42C6F7&#8203;: main \(perlmain\.c&#8203;:116\)
==19889== 
==19889== Invalid read of size 8
==19889==    at 0x4C2C048&#8203;: memcpy@&#8203;GLIBC\_2\.2\.5 \(vg\_replace\_strmem\.c&#8203;:1017\)
==19889==    by 0x9F5566&#8203;: memmove \(string3\.h&#8203;:57\)
==19889==    by 0x9F5566&#8203;: Perl\_sv\_catpvn\_flags \(sv\.c&#8203;:5370\)
==19889==    by 0x90410D&#8203;: Perl\_pp\_subst \(pp\_hot\.c&#8203;:3055\)
==19889==    by 0x7DEC7E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==19889==    by 0x544468&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==19889==    by 0x544468&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==19889==    by 0x42C6F7&#8203;: main \(perlmain\.c&#8203;:116\)
==19889==  Address 0x5f81420 is 6 bytes after a block of size 10 alloc'd
==19889==    at 0x4C27C0F&#8203;: malloc \(vg\_replace\_malloc\.c&#8203;:299\)
==19889==    by 0x7EFD6C&#8203;: Perl\_safesysmalloc \(util\.c&#8203;:153\)
==19889==    by 0x98BD5F&#8203;: Perl\_sv\_grow \(sv\.c&#8203;:1624\)
==19889==    by 0x9EA7D7&#8203;: Perl\_sv\_pvn\_force\_flags \(sv\.c&#8203;:9871\)
==19889==    by 0x901316&#8203;: Perl\_pp\_subst \(pp\_hot\.c&#8203;:2991\)
==19889==    by 0x7DEC7E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==19889==    by 0x544468&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==19889==    by 0x544468&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==19889==    by 0x42C6F7&#8203;: main \(perlmain\.c&#8203;:116\)
==19889== 
==19889== Invalid read of size 8
==19889==    at 0x4C2C056&#8203;: memcpy@&#8203;GLIBC\_2\.2\.5 \(vg\_replace\_strmem\.c&#8203;:1017\)
==19889==    by 0x9F5566&#8203;: memmove \(string3\.h&#8203;:57\)
==19889==    by 0x9F5566&#8203;: Perl\_sv\_catpvn\_flags \(sv\.c&#8203;:5370\)
==19889==    by 0x90410D&#8203;: Perl\_pp\_subst \(pp\_hot\.c&#8203;:3055\)
==19889==    by 0x7DEC7E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==19889==    by 0x544468&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==19889==    by 0x544468&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==19889==    by 0x42C6F7&#8203;: main \(perlmain\.c&#8203;:116\)
==19889==  Address 0x5f81428 is 14 bytes after a block of size 10 alloc'd
==19889==    at 0x4C27C0F&#8203;: malloc \(vg\_replace\_malloc\.c&#8203;:299\)
==19889==    by 0x7EFD6C&#8203;: Perl\_safesysmalloc \(util\.c&#8203;:153\)
==19889==    by 0x98BD5F&#8203;: Perl\_sv\_grow \(sv\.c&#8203;:1624\)
==19889==    by 0x9EA7D7&#8203;: Perl\_sv\_pvn\_force\_flags \(sv\.c&#8203;:9871\)
==19889==    by 0x901316&#8203;: Perl\_pp\_subst \(pp\_hot\.c&#8203;:2991\)
==19889==    by 0x7DEC7E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==19889==    by 0x544468&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==19889==    by 0x544468&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==19889==    by 0x42C6F7&#8203;: main \(perlmain\.c&#8203;:116\)
==19889== 
==19889== 
==19889== Process terminating with default action of signal 11 \(SIGSEGV\)
==19889==  Access not within mapped region at address 0x6350000
==19889==    at 0x4C2C04B&#8203;: memcpy@&#8203;GLIBC\_2\.2\.5 \(vg\_replace\_strmem\.c&#8203;:1017\)
==19889==    by 0x9F5566&#8203;: memmove \(string3\.h&#8203;:57\)
==19889==    by 0x9F5566&#8203;: Perl\_sv\_catpvn\_flags \(sv\.c&#8203;:5370\)
==19889==    by 0x90410D&#8203;: Perl\_pp\_subst \(pp\_hot\.c&#8203;:3055\)
==19889==    by 0x7DEC7E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==19889==    by 0x544468&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==19889==    by 0x544468&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==19889==    by 0x42C6F7&#8203;: main \(perlmain\.c&#8203;:116\)
==19889==  If you believe this happened as a result of a stack
==19889==  overflow in your program's main thread \(unlikely but
==19889==  possible\)\, you can try to increase the size of the
==19889==  main thread stack using the \-\-main\-stacksize= flag\.
==19889==  The main thread stack size used in this run was 8388608\.
==19889== 
==19889== HEAP SUMMARY&#8203;:
==19889==     in use at exit&#8203;: 122\,132 bytes in 648 blocks
==19889==   total heap usage&#8203;: 783 allocs\, 135 frees\, 148\,398 bytes allocated
==19889== 
==19889== LEAK SUMMARY&#8203;:
==19889==    definitely lost&#8203;: 328 bytes in 1 blocks
==19889==    indirectly lost&#8203;: 2\,631 bytes in 39 blocks
==19889==      possibly lost&#8203;: 0 bytes in 0 blocks
==19889==    still reachable&#8203;: 119\,173 bytes in 608 blocks
==19889==         suppressed&#8203;: 0 bytes in 0 blocks
==19889== Rerun with \-\-leak\-check=full to see details of leaked memory
==19889== 
==19889== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==19889== ERROR SUMMARY&#8203;: 998087 errors from 3 contexts \(suppressed&#8203;: 0 from 0\)


\*\*PERL \-V\*\*

Summary of my perl5 \(revision 5 version 23 subversion 4\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 94757bf7ac8451b3588578f287f9c511a04011bf
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt11\-1\+deb8u4 \(2015\-09\-19\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.9\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/4\.9/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Sep 30 2015 16&#8203;:39&#8203;:59
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @tonycoz

On Sat Oct 10 14&#8203;:20&#8203;:55 2015\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> Greetings Porters\,
> 
> I have compiled bleadperl with the afl\-gcc compiler using&#8203;:
> 
> \./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache
> afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly
> \-Uman1dir \-Uman3dir \-des
> AFL\_HARDEN=1 make && make test
> 
> And then fuzzed the resulting binary using&#8203;:
> 
> AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;
> 
> After reducing testcases using \`afl\-tmin\` and performing additional
> minimization by hand\, I have located the following testcase that
> triggers a segmentation fault in the perl interpreter\. The testcase is
> the file&#8203;:
> 
> /\\b\{sb\}\\b\{wb\}//b\{\}//>s>>>g>>0
> 
> The fuzzer seems to have started from the testcase in \[perl \#126260\]\,
> but is does not appear to be at all related \- that is a regexp related
> bug\, while this bug is occurring in sv\.c\.

This can be simplified&#8203;:

tony@&#8203;mars&#8203;:\.\.\./git/perl$ \./perl \-e '/\\b\{wb\}/; s///g'
Segmentation fault
tony@&#8203;mars&#8203;:\.\.\./git/perl$ \./perl \-e '/\\b\{sb\}/; s///g'
Segmentation fault
tony@&#8203;mars&#8203;:\.\.\./git/perl$ \./perl \-e '/\\b\{gcb\}/; s///g'
Segmentation fault
tony@&#8203;mars&#8203;:\.\.\./git/perl$ \./perl \-e '/\\b/; s///g'
tony@&#8203;mars&#8203;:\.\.\./git/perl$ 

Looking at it further\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @khwilliamson

This is now fixed in blead by commit 
f0bd363c36d925d8d3dfe3b68715763c850b171a

Thank you for spotting this\.  It led to me finding several more bugs with this feature\.
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

On 10/19/2015 12&#8203;:52 PM\, Karl Williamson via RT wrote&#8203;:
> This is now fixed in blead by commit
> f0bd363c36d925d8d3dfe3b68715763c850b171a
>
> Thank you for spotting this\.  It led to me finding several more bugs with this feature\.
>

I meant to include text\, but forgot\, in the final commit message talking 
about how these bugs cancelled each other out except in rare cases\, so 
that everything passed the extensive test suite furnished by Unicode\, 
until I started fixing things\.

The commit message for 139a998acd6eae73587ff4f048925394f73682d9
also was supposed to have said the TODOs were instituted 6 commits earlier\.

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for submitting this report\.  You have helped make Perl better\.
&nbsp;    
With the release of Perl 5\.24\.0 on May 9\, 2016\, this and 149 other issues have been resolved\.

Perl 5\.24\.0 may be downloaded via https://metacpan.org/release/RJBS/perl-5.24.0

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
