### ISSUE TITLE
'x' operator on list causes segfault and confuses valgrind, 64-bit version

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14972]
Migrated from [rt.perl.org#126309](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126309) (status was 'resolved')

Searchable as RT126309$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers a segmentation fault in the perl interpreter\. The testcase is the file&#8203;:

@&#8203;0\[\(0\)x~0\]

As you might expect\, ~0 is functioning as a really big number here\, and this also segfaults&#8203;:

@&#8203;0\[\(0\)x18446744073709551615\]

However\, this does not&#8203;:

@&#8203;0\[\(0\)x8446744073709551615\] => Out of memory during array extend at \-e line 1\.

And this gets awkward&#8203;:

@&#8203;0\[\(0\)x1446744073709551615\] => panic&#8203;: realloc\, size=11573952589676414152 at \-e line 1\.

This appears to be related to \[perl \#125937\]\, although this persists after that bug was fixed \(and this bug is the bigger badder 64\-bit brother of that one\)

\*\*GDB\*\*

\(gdb\) run
Starting program&#8203;: /usr/local/perl\-afl/bin/perl \-e @&#8203;0\\\[\\\(0\\\)x\\~0\\\]
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.

Program received signal SIGSEGV\, Segmentation fault\.
0x00007ffff6d4f735 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6d4f735 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x0000000000805220 in memcpy \(\_\_len=131072\, \_\_src=0x11f3a30\, 
&nbsp;    \_\_dest=\<optimized out>\) at /usr/include/x86\_64\-linux\-gnu/bits/string3\.h&#8203;:51
\#2  Perl\_repeatcpy \(to=0x11f3a30 "\\030\` \\001"\, from=0x11f3a28 "\\030\` \\001"\, len=8\, 
&nbsp;    count=9223372036854775806\) at util\.c&#8203;:3133
\#3  0x0000000000a7ac5b in Perl\_pp\_repeat \(\) at pp\.c&#8203;:1744
\#4  0x00000000007dec7f in Perl\_runops\_debug \(\) at dump\.c&#8203;:2224
\#5  0x0000000000544469 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2456
\#6  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2379
\#7  0x000000000042c6f8 in main \(argc=3\, argv=0x7fffffffe348\, env=0x7fffffffe368\)
&nbsp;    at perlmain\.c&#8203;:116
\(gdb\) f 2
\#2  Perl\_repeatcpy \(to=0x11f3a30 "\\030\` \\001"\, from=0x11f3a28 "\\030\` \\001"\, len=8\, 
&nbsp;    count=9223372036854775806\) at util\.c&#8203;:3133
3133            memcpy\(p\, to\, size\);
\(gdb\) info locals
size = 131072
p = \<optimized out>
items = \<optimized out>
linear = 4
half = 4611686018427387903
\_\_PRETTY\_FUNCTION\_\_ = "Perl\_repeatcpy"
\(gdb\) f 3
\#3  0x0000000000a7ac5b in Perl\_pp\_repeat \(\) at pp\.c&#8203;:1744
1744            \}
\(gdb\) info locals
max = 9223372036854775807
sv = 0x7fffffffffffffff
infnan = false
\_\_PRETTY\_FUNCTION\_\_ = "Perl\_pp\_repeat"


\*\*VALGRIND\*\*

Valgrind had a bad time with this one&#8203;:

==50624== Memcheck\, a memory error detector
==50624== Copyright \(C\) 2002\-2015\, and GNU GPL'd\, by Julian Seward et al\.
==50624== Using Valgrind\-3\.11\.0 and LibVEX; rerun with \-h for copyright info
==50624== Command&#8203;: \.\./bin/perl \-e @&#8203;0\[\(0\)x~0\]
==50624== 
==50624== Invalid write of size 8
==50624==    at 0x4C2C363&#8203;: memcpy@&#8203;@&#8203;GLIBC\_2\.14 \(vg\_replace\_strmem\.c&#8203;:1018\)
==50624==    by 0x80521F&#8203;: memcpy \(string3\.h&#8203;:51\)
==50624==    by 0x80521F&#8203;: Perl\_repeatcpy \(util\.c&#8203;:3133\)
==50624==    by 0xA7AC5A&#8203;: Perl\_pp\_repeat \(pp\.c&#8203;:1744\)
==50624==    by 0x7DEC7E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==50624==    by 0x544468&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==50624==    by 0x544468&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==50624==    by 0x42C6F7&#8203;: main \(perlmain\.c&#8203;:116\)
==50624==  Address 0x5f54fe0 is 0 bytes after a block of size 1\,024 alloc'd
==50624==    at 0x4C27C0F&#8203;: malloc \(vg\_replace\_malloc\.c&#8203;:299\)
==50624==    by 0x7EFD6C&#8203;: Perl\_safesysmalloc \(util\.c&#8203;:153\)
==50624==    by 0x8C3468&#8203;: Perl\_av\_extend\_guts \(av\.c&#8203;:182\)
==50624==    by 0xB0E1BF&#8203;: Perl\_new\_stackinfo \(scope\.c&#8203;:56\)
==50624==    by 0x520F5A&#8203;: Perl\_init\_stacks \(perl\.c&#8203;:4063\)
==50624==    by 0x521515&#8203;: perl\_construct \(perl\.c&#8203;:249\)
==50624==    by 0x42C403&#8203;: main \(perlmain\.c&#8203;:110\)
==50624== 
==50624== Invalid read of size 8
==50624==    at 0x4C2C36E&#8203;: memcpy@&#8203;@&#8203;GLIBC\_2\.14 \(vg\_replace\_strmem\.c&#8203;:1018\)
==50624==    by 0x80521F&#8203;: memcpy \(string3\.h&#8203;:51\)
==50624==    by 0x80521F&#8203;: Perl\_repeatcpy \(util\.c&#8203;:3133\)
==50624==    by 0xA7AC5A&#8203;: Perl\_pp\_repeat \(pp\.c&#8203;:1744\)
==50624==    by 0x7DEC7E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==50624==    by 0x544468&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==50624==    by 0x544468&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==50624==    by 0x42C6F7&#8203;: main \(perlmain\.c&#8203;:116\)
==50624==  Address 0x5f54fe0 is 0 bytes after a block of size 1\,024 alloc'd
==50624==    at 0x4C27C0F&#8203;: malloc \(vg\_replace\_malloc\.c&#8203;:299\)
==50624==    by 0x7EFD6C&#8203;: Perl\_safesysmalloc \(util\.c&#8203;:153\)
==50624==    by 0x8C3468&#8203;: Perl\_av\_extend\_guts \(av\.c&#8203;:182\)
==50624==    by 0xB0E1BF&#8203;: Perl\_new\_stackinfo \(scope\.c&#8203;:56\)
==50624==    by 0x520F5A&#8203;: Perl\_init\_stacks \(perl\.c&#8203;:4063\)
==50624==    by 0x521515&#8203;: perl\_construct \(perl\.c&#8203;:249\)
==50624==    by 0x42C403&#8203;: main \(perlmain\.c&#8203;:110\)
==50624== 

valgrind&#8203;: m\_mallocfree\.c&#8203;:303 \(get\_bszB\_as\_is\)&#8203;: Assertion 'bszB\_lo == bszB\_hi' failed\.
valgrind&#8203;: Heap block lo/hi size mismatch&#8203;: lo = 1088\, hi = 100058968\.
This is probably caused by your program erroneously writing past the
end of a heap block and corrupting heap metadata\.  If you fix any
invalid writes reported by Memcheck\, this assertion failure will
probably go away\.  Please try that before reporting this as a bug\.


host stacktrace&#8203;:
==50624==    at 0x38084838&#8203;: show\_sched\_status\_wrk \(m\_libcassert\.c&#8203;:343\)
==50624==    by 0x38084954&#8203;: report\_and\_quit \(m\_libcassert\.c&#8203;:415\)
==50624==    by 0x38084AE1&#8203;: vgPlain\_assert\_fail \(m\_libcassert\.c&#8203;:481\)
==50624==    by 0x380922ED&#8203;: get\_bszB\_as\_is \(m\_mallocfree\.c&#8203;:301\)
==50624==    by 0x380922ED&#8203;: get\_bszB \(m\_mallocfree\.c&#8203;:311\)
==50624==    by 0x380922ED&#8203;: get\_pszB \(m\_mallocfree\.c&#8203;:385\)
==50624==    by 0x380922ED&#8203;: vgPlain\_describe\_arena\_addr \(m\_mallocfree\.c&#8203;:1527\)
==50624==    by 0x3807DEEB&#8203;: vgPlain\_describe\_addr \(m\_addrinfo\.c&#8203;:186\)
==50624==    by 0x3807C763&#8203;: vgMemCheck\_update\_Error\_extra \(mc\_errors\.c&#8203;:1141\)
==50624==    by 0x3808092A&#8203;: vgPlain\_maybe\_record\_error \(m\_errormgr\.c&#8203;:813\)
==50624==    by 0x3807BD2A&#8203;: vgMemCheck\_record\_address\_error \(mc\_errors\.c&#8203;:760\)
==50624==    by 0x3805A018&#8203;: mc\_LOADVn\_slow \(mc\_main\.c&#8203;:1392\)
==50624==    by 0x803C85AF7&#8203;: ???
==50624==    by 0x80355BF2F&#8203;: ???
==50624==    by 0x80200833F&#8203;: ???
==50624==    by 0x80521F&#8203;: memcpy \(string3\.h&#8203;:51\)
==50624==    by 0x80521F&#8203;: Perl\_repeatcpy \(util\.c&#8203;:3133\)
==50624==    by 0x80200833F&#8203;: ???
==50624==    by 0x80521F&#8203;: memcpy \(string3\.h&#8203;:51\)
==50624==    by 0x80521F&#8203;: Perl\_repeatcpy \(util\.c&#8203;:3133\)

sched status&#8203;:
&nbsp;  running\_tid=1

Thread 1&#8203;: status = VgTs\_Runnable \(lwpid 50624\)
==50624==    at 0x4C2C360&#8203;: memcpy@&#8203;@&#8203;GLIBC\_2\.14 \(vg\_replace\_strmem\.c&#8203;:1018\)
==50624==    by 0x80521F&#8203;: memcpy \(string3\.h&#8203;:51\)
==50624==    by 0x80521F&#8203;: Perl\_repeatcpy \(util\.c&#8203;:3133\)
==50624==    by 0xA7AC5A&#8203;: Perl\_pp\_repeat \(pp\.c&#8203;:1744\)
==50624==    by 0x7DEC7E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==50624==    by 0x544468&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==50624==    by 0x544468&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==50624==    by 0x42C6F7&#8203;: main \(perlmain\.c&#8203;:116\)


Note&#8203;: see also the FAQ in the source distribution\.
It contains workarounds to several common problems\.
In particular\, if Valgrind aborted or crashed after
identifying problems in your program\, there's a good chance
that fixing those problems will prevent Valgrind aborting or
crashing\, especially if it happened in m\_mallocfree\.c\.

If that doesn't help\, please report this bug to&#8203;: www\.valgrind\.org

In the bug report\, send all the above text\, the valgrind
version\, and what OS and version you are using\.  Thanks\.


\*\*PERL \-V\*\*

Summary of my perl5 \(revision 5 version 23 subversion 4\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 94757bf7ac8451b3588578f287f9c511a04011bf
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt11\-1\+deb8u4 \(2015\-09\-19\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.9\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/4\.9/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Sep 30 2015 16&#8203;:39&#8203;:59
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @dcollinsn

This now crashes with the following message\, without a segfault\, on both debugging and nondebugging perls on the same platform&#8203;:

panic&#8203;: av\_extend\_guts\(\) negative count \(\-9223372036854775681\)

dcollins@&#8203;nightshade64&#8203;:/usr/local/perl\-afl/out$ \.\./bin/perl \-V
Summary of my perl5 \(revision 5 version 23 subversion 4\) configuration&#8203;:
&nbsp;  Commit id&#8203;: a7dba6f870a82e3be87bda50593cb5d2042277fd
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt11\-1\+deb8u4 \(2015\-09\-19\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DDEBUG\_LEAKING\_SCALARS \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.9\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/4\.9/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Oct 15 2015 20&#8203;:35&#8203;:14
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Oct 19\, 2015 at 01&#8203;:32&#8203;:24PM \-0700\, Dan Collins via RT wrote&#8203;:
> This now crashes with the following message\, without a segfault\, on both
> debugging and nondebugging perls on the same platform&#8203;:
> 
> panic&#8203;: av\_extend\_guts\(\) negative count \(\-9223372036854775681\)

Technically that's correct\, in that its catching the error and throwing
a panic\, but the error message could be better\.

I've just pushed out a branch for smoking\, smoke\-me/davem/repeat that
changes the panic to

&nbsp;    Out of memory during stack extend

and also fixes a spurious g\+\+ compiler warning from my earlier messing
about with EXTEND\(\) etc\.

\-\- 
Monto Blanco\.\.\. scorchio\!

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, Oct 20\, 2015 at 04&#8203;:46&#8203;:50PM \+0100\, Dave Mitchell wrote&#8203;:
> On Mon\, Oct 19\, 2015 at 01&#8203;:32&#8203;:24PM \-0700\, Dan Collins via RT wrote&#8203;:
> > This now crashes with the following message\, without a segfault\, on both
> > debugging and nondebugging perls on the same platform&#8203;:
> > 
> > panic&#8203;: av\_extend\_guts\(\) negative count \(\-9223372036854775681\)
> 
> Technically that's correct\, in that its catching the error and throwing
> a panic\, but the error message could be better\.
> 
> I've just pushed out a branch for smoking\, smoke\-me/davem/repeat that
> changes the panic to
> 
>     Out of memory during stack extend
> 
> and also fixes a spurious g\+\+ compiler warning from my earlier messing
> about with EXTEND\(\) etc\.

and now merged as&#8203;:

e9548aa6723a88345976cfd7d3b37feb4e405ae9

\-\- 
My Dad used to say 'always fight fire with fire'\, which is probably why
he got thrown out of the fire brigade\.

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for submitting this report\.  You have helped make Perl better\.
&nbsp;    
With the release of Perl 5\.24\.0 on May 9\, 2016\, this and 149 other issues have been resolved\.

Perl 5\.24\.0 may be downloaded via https://metacpan.org/release/RJBS/perl-5.24.0

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
