### ISSUE TITLE
Segmentation fault in unpack (Perl_unpackstring has a rather odd pointer 0x303030303030304b)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14978]
Migrated from [rt.perl.org#126326](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126326) (status was 'rejected')

Searchable as RT126326$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers a segmentation fault in the perl interpreter\. The testcase is the file&#8203;:

unpack p\,K0000000

\*\*GDB\*\*

\(gdb\) run
Starting program&#8203;: /usr/local/perl\-afl/bin/perl \-e unpack\\ p\,K0000000
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.

Program received signal SIGSEGV\, Segmentation fault\.
0x00007ffff6d40c8a in strlen \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) b
Breakpoint 1 at 0x7ffff6d40c8a
\(gdb\) bt
\#0  0x00007ffff6d40c8a in strlen \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x0000000000a273ec in Perl\_newSVpv \(
&nbsp;    s=0x303030303030304b \<error&#8203;: Cannot access memory at address 0x303030303030304b>\, len=\<optimized out>\) at sv\.c&#8203;:9149
\#2  0x0000000000e2ba5c in S\_unpack\_rec \(symptr=0x303030303030304b\,
&nbsp;    symptr@&#8203;entry=0x7fffffffe310\, s=0x120e9b8 ""\, strbeg=0x0\,
&nbsp;    strbeg@&#8203;entry=0x120e9b0 "K0000000"\, strend=0x11f3a28 "\\320Y \\001"\,
&nbsp;    new\_s=0x11f3a28\, new\_s@&#8203;entry=0x0\) at pp\_pack\.c&#8203;:1564
\#3  0x0000000000eb123d in Perl\_unpackstring \(pat=pat@&#8203;entry=0x120e780 "p"\,
&nbsp;    patend=0x120e781 ""\, s=0x120e9b0 "K0000000"\, strend=0x120e9b8 ""\,
&nbsp;    flags=flags@&#8203;entry=0\) at pp\_pack\.c&#8203;:835
\#4  0x0000000000eb227f in Perl\_pp\_unpack \(\) at pp\_pack\.c&#8203;:1839
\#5  0x00000000007dec7f in Perl\_runops\_debug \(\) at dump\.c&#8203;:2224
\#6  0x0000000000544469 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2456
\#7  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2379
\#8  0x000000000042c6f8 in main \(argc=3\, argv=0x7fffffffe648\,
&nbsp;    env=0x7fffffffe668\) at perlmain\.c&#8203;:116
\(gdb\) f 3
\#3  0x0000000000eb123d in Perl\_unpackstring \(pat=pat@&#8203;entry=0x120e780 "p"\,
&nbsp;    patend=0x120e781 ""\, s=0x120e9b0 "K0000000"\, strend=0x120e9b8 ""\,
&nbsp;    flags=flags@&#8203;entry=0\) at pp\_pack\.c&#8203;:835
835         return unpack\_rec\(&sym\, s\, s\, strend\, NULL \);
\(gdb\) info locals
sym = \{patptr = 0x120e781 ""\, patend = 0x120e781 ""\, grpbeg = 0x0\,
&nbsp;  grpend = 0x0\, code = 112\, length = 1\, howlen = e\_no\_len\, level = 0\,
&nbsp;  flags = 0\, strbeg = 0\, previous = 0x0\}
\_\_PRETTY\_FUNCTION\_\_ = "Perl\_unpackstring"


\*\*VALGRIND\*\*

==23046== Memcheck\, a memory error detector
==23046== Copyright \(C\) 2002\-2015\, and GNU GPL'd\, by Julian Seward et al\.
==23046== Using Valgrind\-3\.11\.0 and LibVEX; rerun with \-h for copyright info
==23046== Command&#8203;: \.\./bin/perl \-e unpack\\ p\,K0000000
==23046==
==23046== Invalid read of size 1
==23046==    at 0x4C2ABC2&#8203;: strlen \(vg\_replace\_strmem\.c&#8203;:454\)
==23046==    by 0xA273EB&#8203;: Perl\_newSVpv \(sv\.c&#8203;:9149\)
==23046==    by 0xE2BA5B&#8203;: S\_unpack\_rec \(pp\_pack\.c&#8203;:1564\)
==23046==    by 0xEB123C&#8203;: Perl\_unpackstring \(pp\_pack\.c&#8203;:835\)
==23046==    by 0xEB227E&#8203;: Perl\_pp\_unpack \(pp\_pack\.c&#8203;:1839\)
==23046==    by 0x7DEC7E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==23046==    by 0x544468&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==23046==    by 0x544468&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==23046==    by 0x42C6F7&#8203;: main \(perlmain\.c&#8203;:116\)
==23046==  Address 0x303030303030304b is not stack'd\, malloc'd or \(recently\) free'd
==23046==
==23046==
==23046== Process terminating with default action of signal 11 \(SIGSEGV\)
==23046==  General Protection Fault
==23046==    at 0x4C2ABC2&#8203;: strlen \(vg\_replace\_strmem\.c&#8203;:454\)
==23046==    by 0xA273EB&#8203;: Perl\_newSVpv \(sv\.c&#8203;:9149\)
==23046==    by 0xE2BA5B&#8203;: S\_unpack\_rec \(pp\_pack\.c&#8203;:1564\)
==23046==    by 0xEB123C&#8203;: Perl\_unpackstring \(pp\_pack\.c&#8203;:835\)
==23046==    by 0xEB227E&#8203;: Perl\_pp\_unpack \(pp\_pack\.c&#8203;:1839\)
==23046==    by 0x7DEC7E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==23046==    by 0x544468&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==23046==    by 0x544468&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==23046==    by 0x42C6F7&#8203;: main \(perlmain\.c&#8203;:116\)
==23046==
==23046== HEAP SUMMARY&#8203;:
==23046==     in use at exit&#8203;: 110\,006 bytes in 539 blocks
==23046==   total heap usage&#8203;: 635 allocs\, 96 frees\, 126\,694 bytes allocated
==23046==
==23046== LEAK SUMMARY&#8203;:
==23046==    definitely lost&#8203;: 176 bytes in 1 blocks
==23046==    indirectly lost&#8203;: 1\,989 bytes in 20 blocks
==23046==      possibly lost&#8203;: 0 bytes in 0 blocks
==23046==    still reachable&#8203;: 107\,841 bytes in 518 blocks
==23046==         suppressed&#8203;: 0 bytes in 0 blocks
==23046== Rerun with \-\-leak\-check=full to see details of leaked memory
==23046==
==23046== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==23046== ERROR SUMMARY&#8203;: 1 errors from 1 contexts \(suppressed&#8203;: 0 from 0\)
Segmentation fault


\*\*PERL \-V\*\*

Summary of my perl5 \(revision 5 version 23 subversion 4\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 94757bf7ac8451b3588578f287f9c511a04011bf
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt11\-1\+deb8u4 \(2015\-09\-19\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.9\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/4\.9/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Sep 30 2015 16&#8203;:39&#8203;:59
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @mauke

Am 11\.10\.2015 um 13&#8203;:50 schrieb Dan Collins \(via RT\)&#8203;:
> \# New Ticket Created by  Dan Collins
> \# Please include the string&#8203;:  \[perl \#126326\]
> \# in the subject line of all future correspondence about this issue\.
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126326 >
>
>
> Greetings Porters\,
>
> I have compiled bleadperl with the afl\-gcc compiler using&#8203;:
>
> \./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
> AFL\_HARDEN=1 make && make test
>
> And then fuzzed the resulting binary using&#8203;:
>
> AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;
>
> After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers a segmentation fault in the perl interpreter\. The testcase is the file&#8203;:
>
> unpack p\,K0000000

This one is working as intended\, I think\. unpack 'p' takes a packed 
pointer and reads a nul\-terminated string from it\. Your "packed pointer" 
is the string \(bareword\) "K0000000"\, which turns into the "rather odd" 
0x303030303030304b because 'K' is ASCII 0x4b and '0' is ASCII 0x30\.

pack/unpack P/p are inherently unsafe because they work on raw pointers\.

\-\- 
Lukas Mai \<plokinom@&#8203;gmail\.com>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @dcollinsn

Ah yes\, of course\. I wasn't thinking that unpack was dealing with raw
pointers\. I agree that this one at least is not a bug\.

On Sun\, Oct 11\, 2015 at 7&#8203;:55 AM\, Lukas Mai \<plokinom@&#8203;gmail\.com> wrote&#8203;:

> Am 11\.10\.2015 um 13&#8203;:50 schrieb Dan Collins \(via RT\)&#8203;:
>
>> \# New Ticket Created by  Dan Collins
>> \# Please include the string&#8203;:  \[perl \#126326\]
>> \# in the subject line of all future correspondence about this issue\.
>> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126326 >
>>
>>
>> Greetings Porters\,
>>
>> I have compiled bleadperl with the afl\-gcc compiler using&#8203;:
>>
>> \./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache
>> afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly
>> \-Uman1dir \-Uman3dir \-des
>> AFL\_HARDEN=1 make && make test
>>
>> And then fuzzed the resulting binary using&#8203;:
>>
>> AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;
>>
>> After reducing testcases using \`afl\-tmin\` and performing additional
>> minimization by hand\, I have located the following testcase that triggers a
>> segmentation fault in the perl interpreter\. The testcase is the file&#8203;:
>>
>> unpack p\,K0000000
>>
>
> This one is working as intended\, I think\. unpack 'p' takes a packed
> pointer and reads a nul\-terminated string from it\. Your "packed pointer" is
> the string \(bareword\) "K0000000"\, which turns into the "rather odd"
> 0x303030303030304b because 'K' is ASCII 0x4b and '0' is ASCII 0x30\.
>
> pack/unpack P/p are inherently unsafe because they work on raw pointers\.
>
> \-\-
> Lukas Mai \<plokinom@&#8203;gmail\.com>
>

**Comment by p5pRT** [comment]
### From @tonycoz

On Sun Oct 11 04&#8203;:58&#8203;:35 2015\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> Ah yes\, of course\. I wasn't thinking that unpack was dealing with raw
> pointers\. I agree that this one at least is not a bug\.

Marking as rejected\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'rejected'
