### ISSUE TITLE
Segmentation fault in pack (S_pack_rec tries to access unallocated memory)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14977]
Migrated from [rt.perl.org#126325](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126325) (status was 'resolved')

Searchable as RT126325$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers a segmentation fault in the perl interpreter\. The testcase is the file&#8203;:

pack\+WH200000\,\\0

Today I'm reporting a pair of bugs related to pack/unpack\. They appeared to be related\, but GDB shows that they have very different behaviours\. This is by far the tamer of the two\.

\*\*GDB\*\*

\(gdb\) run
Starting program&#8203;: /usr/local/perl\-afl/bin/perl \-e pack\+WH200000\,\\\\0
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.

Program received signal SIGSEGV\, Segmentation fault\.
S\_pack\_rec \(cat=0x0\, cat@&#8203;entry=0x1205af0\, symptr=0x2fcc0\, beglist=0x1\,
&nbsp;    beglist@&#8203;entry=0x11f3a30\, endlist=0x7ffff7e1d015\, endlist@&#8203;entry=0x11f3a38\)
&nbsp;    at pp\_pack\.c&#8203;:2503
2503                        \} else if \(isALPHA\(\*str\)\)
\(gdb\) bt
\#0  S\_pack\_rec \(cat=0x0\, cat@&#8203;entry=0x1205af0\, symptr=0x2fcc0\, beglist=0x1\,
&nbsp;    beglist@&#8203;entry=0x11f3a30\, endlist=0x7ffff7e1d015\, endlist@&#8203;entry=0x11f3a38\)
&nbsp;    at pp\_pack\.c&#8203;:2503
\#1  0x0000000000eb2f5f in Perl\_packlist \(endlist=0x11f3a38\,
&nbsp;    beglist=0x11f3a30\, patend=\<optimized out>\, pat=\<optimized out>\,
&nbsp;    cat=0x1205af0\) at pp\_pack\.c&#8203;:1971
\#2  Perl\_pp\_pack \(\) at pp\_pack\.c&#8203;:3128
\#3  0x00000000007dec7f in Perl\_runops\_debug \(\) at dump\.c&#8203;:2224
\#4  0x0000000000544469 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2456
\#5  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2379
\#6  0x000000000042c6f8 in main \(argc=3\, argv=0x7fffffffe648\,
&nbsp;    env=0x7fffffffe668\) at perlmain\.c&#8203;:116
\(gdb\) info locals
str = 0xfeb000 \<error&#8203;: Cannot access memory at address 0xfeb000>
utf8\_flags = 195775
fromlen = 0
howlen = e\_number
lookahead = \{patptr = 0x120e788 ""\, patend = 0x120e788 ""\, grpbeg = 0x0\,
&nbsp;  grpend = 0x0\, code = 72\, length = 200000\, howlen = e\_number\, level = 0\,
&nbsp;  flags = 9\, strbeg = 0\, previous = 0x0\}
utf8 = 207
\_\_PRETTY\_FUNCTION\_\_ = "S\_pack\_rec"
\(gdb\) f 1
\#1  0x0000000000eb2f5f in Perl\_packlist \(endlist=0x11f3a38\,
&nbsp;    beglist=0x11f3a30\, patend=\<optimized out>\, pat=\<optimized out>\,
&nbsp;    cat=0x1205af0\) at pp\_pack\.c&#8203;:1971
1971        \(void\)pack\_rec\( cat\, &sym\, beglist\, endlist \);
\(gdb\) info locals
sym = \{patptr = 0x120e788 ""\, patend = 0x120e788 ""\, grpbeg = 0x0\,
&nbsp;  grpend = 0x0\, code = 72\, length = 200000\, howlen = e\_number\, level = 0\,
&nbsp;  flags = 9\, strbeg = 0\, previous = 0x0\}


\*\*VALGRIND\*\*

==31388== Memcheck\, a memory error detector
==31388== Copyright \(C\) 2002\-2015\, and GNU GPL'd\, by Julian Seward et al\.
==31388== Using Valgrind\-3\.11\.0 and LibVEX; rerun with \-h for copyright info
==31388== Command&#8203;: \.\./bin/perl \-e pack\+WH200000\,\\\\0
==31388==
==31388== Invalid read of size 1
==31388==    at 0xEA3014&#8203;: S\_pack\_rec \(pp\_pack\.c&#8203;:2503\)
==31388==    by 0xEB2F5E&#8203;: Perl\_packlist \(pp\_pack\.c&#8203;:1971\)
==31388==    by 0xEB2F5E&#8203;: Perl\_pp\_pack \(pp\_pack\.c&#8203;:3128\)
==31388==    by 0x7DEC7E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==31388==    by 0x544468&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==31388==    by 0x544468&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==31388==    by 0x42C6F7&#8203;: main \(perlmain\.c&#8203;:116\)
==31388==  Address 0xfeb000 is not stack'd\, malloc'd or \(recently\) free'd
==31388==
==31388==
==31388== Process terminating with default action of signal 11 \(SIGSEGV\)
==31388==  Access not within mapped region at address 0xFEB000
==31388==    at 0xEA3014&#8203;: S\_pack\_rec \(pp\_pack\.c&#8203;:2503\)
==31388==    by 0xEB2F5E&#8203;: Perl\_packlist \(pp\_pack\.c&#8203;:1971\)
==31388==    by 0xEB2F5E&#8203;: Perl\_pp\_pack \(pp\_pack\.c&#8203;:3128\)
==31388==    by 0x7DEC7E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==31388==    by 0x544468&#8203;: S\_run\_body \(perl\.c&#8203;:2456\)
==31388==    by 0x544468&#8203;: perl\_run \(perl\.c&#8203;:2379\)
==31388==    by 0x42C6F7&#8203;: main \(perlmain\.c&#8203;:116\)
==31388==  If you believe this happened as a result of a stack
==31388==  overflow in your program's main thread \(unlikely but
==31388==  possible\)\, you can try to increase the size of the
==31388==  main thread stack using the \-\-main\-stacksize= flag\.
==31388==  The main thread stack size used in this run was 8388608\.
==31388==
==31388== HEAP SUMMARY&#8203;:
==31388==     in use at exit&#8203;: 310\,063 bytes in 540 blocks
==31388==   total heap usage&#8203;: 639 allocs\, 99 frees\, 327\,593 bytes allocated
==31388==
==31388== LEAK SUMMARY&#8203;:
==31388==    definitely lost&#8203;: 176 bytes in 1 blocks
==31388==    indirectly lost&#8203;: 1\,989 bytes in 20 blocks
==31388==      possibly lost&#8203;: 0 bytes in 0 blocks
==31388==    still reachable&#8203;: 307\,898 bytes in 519 blocks
==31388==         suppressed&#8203;: 0 bytes in 0 blocks
==31388== Rerun with \-\-leak\-check=full to see details of leaked memory
==31388==
==31388== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==31388== ERROR SUMMARY&#8203;: 1 errors from 1 contexts \(suppressed&#8203;: 0 from 0\)
Segmentation fault


\*\*PERL \-V\*\*

Summary of my perl5 \(revision 5 version 23 subversion 4\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 94757bf7ac8451b3588578f287f9c511a04011bf
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt11\-1\+deb8u4 \(2015\-09\-19\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.9\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/4\.9/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Sep 30 2015 16&#8203;:39&#8203;:59
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @tonycoz

On Sun Oct 11 04&#8203;:49&#8203;:37 2015\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> After reducing testcases using \`afl\-tmin\` and performing additional
> minimization by hand\, I have located the following testcase that
> triggers a segmentation fault in the perl interpreter\. The testcase is
> the file&#8203;:
> 
> pack\+WH200000\,\\0

The attached seems to fix it\.

I'm going to review the other pack handlers to check for similar issues\.

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

<details><summary>0001-perl-126325-don-t-read-past-the-end-of-the-source-fo.patch</summary>

```diff
From 45f3993798e8339daceeb6b1a0ce606da9e8a613 Mon Sep 17 00:00:00 2001
From: Tony Cook <tony@develop-help.com>
Date: Thu, 22 Oct 2015 12:03:05 +1100
Subject: [perl #126325] don't read past the end of the source for pack [Hh]

With a utf8 target but a non-utf8 source, pack Hh would read past the
end of the source when given a length, due to an incorrect condition.
---
 pp_pack.c   |  2 +-
 t/op/pack.t | 22 +++++++++++++++++++++-
 2 files changed, 22 insertions(+), 2 deletions(-)

diff --git a/pp_pack.c b/pp_pack.c
index 96dfd20..044ea7f 100644
--- a/pp_pack.c
+++ b/pp_pack.c
@@ -2488,7 +2488,7 @@ S_pack_rec(pTHX_ SV *cat, tempsym_t* symptr, SV **beglist, SV **endlist )
 	    if (howlen == e_star) len = fromlen;
 	    field_len = (len+1)/2;
 	    GROWING(utf8, cat, start, cur, field_len);
-	    if (!utf8 && len > (I32)fromlen) len = fromlen;
+	    if (!utf8_source && len > (I32)fromlen) len = fromlen;
 	    bits = 0;
 	    l = 0;
 	    if (datumtype == 'H')
diff --git a/t/op/pack.t b/t/op/pack.t
index e348693..a2da636 100644
--- a/t/op/pack.t
+++ b/t/op/pack.t
@@ -12,7 +12,7 @@ my $no_endianness = $] > 5.009 ? '' :
 my $no_signedness = $] > 5.009 ? '' :
   "Signed/unsigned pack modifiers not available on this perl";
 
-plan tests => 14708;
+plan tests => 14712;
 
 use strict;
 use warnings qw(FATAL all);
@@ -2024,3 +2024,23 @@ is $o::num, 1,     'pack "c" does call num overloading';
 #[perl #123874]: argument underflow leads to corrupt length
 eval q{ pack "pi/x" };
 ok(1, "argument underflow did not crash");
+
+{
+    # [perl #126325] pack [hH] with a unicode string
+    # the hex encoders would read past the end of the string, using
+    # invalid source bytes
+    my $twenty_nuls = "\0" x 20;
+    # This is the case that failed
+    is(pack("WH40", 0x100, ""), "\x{100}$twenty_nuls",
+       "check pack H zero fills (utf8 target)");
+    my $up_nul = "\0";
+
+    utf8::upgrade($up_nul);
+    # check the other combinations too
+    is(pack("WH40", 0x100, $up_nul), "\x{100}$twenty_nuls",
+       "check pack H zero fills (utf8 target/source)");
+    is(pack("H40", ""), $twenty_nuls,
+       "check pack H zero fills (utf8 none)");
+    is(pack("H40", $up_nul), $twenty_nuls,
+       "check pack H zero fills (utf8 source)");
+}
-- 
2.1.4


```
</details>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Wed Oct 21 18&#8203;:05&#8203;:47 2015\, tonyc wrote&#8203;:
> On Sun Oct 11 04&#8203;:49&#8203;:37 2015\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> > After reducing testcases using \`afl\-tmin\` and performing additional
> > minimization by hand\, I have located the following testcase that
> > triggers a segmentation fault in the perl interpreter\. The testcase is
> > the file&#8203;:
> > 
> > pack\+WH200000\,\\0
> 
> The attached seems to fix it\.

Pushed as 0403a1ad8ff01aaac2d09a986ea6bb5210472459\.

> I'm going to review the other pack handlers to check for similar issues\.

The others seemed ok to me\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'resolved'
