### ISSUE TITLE
Segfault (access not within mapped region at 0x8) in Perl_pp_iter

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14985]
Migrated from [rt.perl.org#126361](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126361) (status was 'open')

Searchable as RT126361$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers a segmentation fault in the perl interpreter\. The testcase is the file&#8203;:

\*\_=a for 0\.\.1

Interestingly the following sequence which appears similar shows different behavior&#8203;:

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-e '\*\_="" for 0\.\.1'
Segmentation fault
dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-e '@&#8203;x=0\.\.1; \*\_="" for 0\.\.1'
Segmentation fault
dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-e '@&#8203;x=0\.\.1; \*\_="" for @&#8203;x'
dcollins@&#8203;nightshade64&#8203;:\~/perldebug$

And the use of \*\_ is relevant&#8203;:

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-e '\*\_=a for 0\.\.1'
Segmentation fault
dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-e '\*x=a for 0\.\.1'
dcollins@&#8203;nightshade64&#8203;:\~/perldebug$

So I wonder if this is a problem due to the for statement modifying \*\_ while it is on the stack\. The crash occurs in Perl\_pp\_iter as shown below \- I assume that either Sv\_REFCNT or SvMAGICAL accesses the second element of the struct at oldsv\, and the first element of that struct is a pointer\, since the accessed address is 0x8 on 64\-bit and 0x4 on 32\-bit\. I have no perl that does not crash here\, so a bisect was not attempted\.

\*\*GDB\*\*

\(gdb\) run
Starting program&#8203;: /home/dcollins/perldebug/perl \-e \\\*\_=a\\ for\\ 0\.\.1
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.

Program received signal SIGSEGV\, Segmentation fault\.
0x00000000009004d6 in Perl\_pp\_iter \(\) at pp\_hot\.c&#8203;:2585
2585            if \(LIKELY\(SvREFCNT\(oldsv\) == 1 && \!SvMAGICAL\(oldsv\)\)\) \{
\(gdb\) bt
\#0  0x00000000009004d6 in Perl\_pp\_iter \(\) at pp\_hot\.c&#8203;:2585
\#1  0x00000000007e0aff in Perl\_runops\_debug \(\) at dump\.c&#8203;:2224
\#2  0x0000000000544229 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2459
\#3  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2382
\#4  0x000000000042c028 in main \(argc=3\, argv=0x7fffffffe658\,
&nbsp;    env=0x7fffffffe678\) at perlmain\.c&#8203;:116
\(gdb\) info locals
cur = 1
sp = 0x11f5a20
cx = 0x11f5e88
oldsv = 0x0
itersvp = 0x1200470
\_\_PRETTY\_FUNCTION\_\_ = "Perl\_pp\_iter"
\(gdb\) f 1
\#1  0x00000000007e0aff in Perl\_runops\_debug \(\) at dump\.c&#8203;:2224
2224        \} while \(\(PL\_op = PL\_op\->op\_ppaddr\(aTHX\)\)\);
\(gdb\) p PL\_op
$1 = \(OP \*\) 0x12107c0
\(gdb\) p \*PL\_op
$2 = \{op\_next = 0x1210ce8\, op\_sibling = 0x1210d30\,
&nbsp;  op\_ppaddr = 0x8ffc50 \<Perl\_pp\_iter>\, op\_targ = 0\, op\_type = 200\,
&nbsp;  op\_opt = 1\, op\_slabbed = 1\, op\_savefree = 0\, op\_static = 0\, op\_folded = 0\,
&nbsp;  op\_moresib = 1\, op\_spare = 0\, op\_flags = 2 '\\002'\, op\_private = 0 '\\000'\}
\(gdb\)


\*\*VALGRIND\*\*

==24813== Memcheck\, a memory error detector
==24813== Copyright \(C\) 2002\-2015\, and GNU GPL'd\, by Julian Seward et al\.
==24813== Using Valgrind\-3\.11\.0 and LibVEX; rerun with \-h for copyright info
==24813== Command&#8203;: \./perl \-e \*\_=a\\ for\\ 0\.\.1
==24813==
==24813== Invalid read of size 8
==24813==    at 0x9004D6&#8203;: Perl\_pp\_iter \(pp\_hot\.c&#8203;:2585\)
==24813==    by 0x7E0AFE&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==24813==    by 0x544228&#8203;: S\_run\_body \(perl\.c&#8203;:2459\)
==24813==    by 0x544228&#8203;: perl\_run \(perl\.c&#8203;:2382\)
==24813==    by 0x42C027&#8203;: main \(perlmain\.c&#8203;:116\)
==24813==  Address 0x8 is not stack'd\, malloc'd or \(recently\) free'd
==24813==
==24813==
==24813== Process terminating with default action of signal 11 \(SIGSEGV\)
==24813==  Access not within mapped region at address 0x8
==24813==    at 0x9004D6&#8203;: Perl\_pp\_iter \(pp\_hot\.c&#8203;:2585\)
==24813==    by 0x7E0AFE&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==24813==    by 0x544228&#8203;: S\_run\_body \(perl\.c&#8203;:2459\)
==24813==    by 0x544228&#8203;: perl\_run \(perl\.c&#8203;:2382\)
==24813==    by 0x42C027&#8203;: main \(perlmain\.c&#8203;:116\)
==24813==  If you believe this happened as a result of a stack
==24813==  overflow in your program's main thread \(unlikely but
==24813==  possible\)\, you can try to increase the size of the
==24813==  main thread stack using the \-\-main\-stacksize= flag\.
==24813==  The main thread stack size used in this run was 8388608\.
==24813==
==24813== HEAP SUMMARY&#8203;:
==24813==     in use at exit&#8203;: 110\,107 bytes in 541 blocks
==24813==   total heap usage&#8203;: 642 allocs\, 101 frees\, 127\,693 bytes allocated
==24813==
==24813== LEAK SUMMARY&#8203;:
==24813==    definitely lost&#8203;: 176 bytes in 1 blocks
==24813==    indirectly lost&#8203;: 1\,974 bytes in 20 blocks
==24813==      possibly lost&#8203;: 0 bytes in 0 blocks
==24813==    still reachable&#8203;: 107\,957 bytes in 520 blocks
==24813==         suppressed&#8203;: 0 bytes in 0 blocks
==24813== Rerun with \-\-leak\-check=full to see details of leaked memory
==24813==
==24813== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==24813== ERROR SUMMARY&#8203;: 1 errors from 1 contexts \(suppressed&#8203;: 0 from 0\)
Segmentation fault


\*\*PERL \-V\*\*

Summary of my perl5 \(revision 5 version 23 subversion 4\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 94757bf7ac8451b3588578f287f9c511a04011bf
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt11\-1\+deb8u4 \(2015\-09\-19\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.9\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/4\.9/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Oct 11 2015 21&#8203;:47&#8203;:48
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @geeknik

Most likely a dupe of https://rt-archive.perl.org/perl5/Ticket/Display.html?id=123994.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'
