### ISSUE TITLE
SIGSEGV after panic: reg_node overrun, invalid write in S_regatom

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14998]
Migrated from [rt.perl.org#126406](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126406) (status was 'resolved')

Searchable as RT126406$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers a segmentation fault in the perl interpreter\. The testcase is the file&#8203;:

/\.0\\N\{6\,0\}0\\N\{6\,0\}000000000000000000000000000000000/

The output is the following&#8203;:

panic&#8203;: reg\_node overrun trying to emit 0\, 1633dec>=1633de8 at \-e line 1\.
Segmentation fault


\*\*GDB\*\*

\(gdb\) run
Starting program&#8203;: /home/dcollins/perldebug/perl \-e /\.0\\\\N\\\{6\,0\\\}0\\\\N\\\{6\,0\\\}000000000000000000000000000000000/
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
panic&#8203;: reg\_node overrun trying to emit 0\, 1211f7c>=1211f78 at \-e line 1\.

Program received signal SIGSEGV\, Segmentation fault\.
0x00007ffff6d38528 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6d38528 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x000000000043a1cc in Perl\_opslab\_free \(slab=0x1211cf0\) at op\.c&#8203;:418
\#2  0x000000000043f246 in Perl\_opslab\_force\_free \(slab=\<optimized out>\) at op\.c&#8203;:461
\#3  0x000000000068beea in Perl\_cv\_undef\_flags \(cv=0x11f3210\, flags=0\) at pad\.c&#8203;:354
\#4  0x000000000093c5f0 in Perl\_sv\_clear \(orig\_sv=0x11f3210\) at sv\.c&#8203;:6462
\#5  0x000000000093f9bc in Perl\_sv\_free2 \(sv=0x11f3210\, rc=\<optimized out>\) at sv\.c&#8203;:6885
\#6  0x000000000052d011 in S\_SvREFCNT\_dec \(sv=\<optimized out>\) at inline\.h&#8203;:166
\#7  perl\_destruct \(my\_perl=\<optimized out>\) at perl\.c&#8203;:785
\#8  0x000000000042be70 in main \(argc=3\, argv=0x7fffffffe318\, env=0x7fffffffe338\) at perlmain\.c&#8203;:127
\(gdb\) info locals
No symbol table info available\.
\(gdb\) f 1
\#1  0x000000000043a1cc in Perl\_opslab\_free \(slab=0x1211cf0\) at op\.c&#8203;:418
418        PerlMemShared\_free\(slab\);
\(gdb\) info locals
slab2 = 0x0
\_\_PRETTY\_FUNCTION\_\_ = "Perl\_opslab\_free"


\*\*VALGRIND\*\*

==44674== Memcheck\, a memory error detector
==44674== Copyright \(C\) 2002\-2015\, and GNU GPL'd\, by Julian Seward et al\.
==44674== Using Valgrind\-3\.11\.0 and LibVEX; rerun with \-h for copyright info
==44674== Command&#8203;: /home/dcollins/perldebug/perl \-e /\.0\\\\N\{6\,0\}0\\\\N\{6\,0\}000000000000000000000000000000000/
==44674== 
==44674== Invalid write of size 1
==44674==    at 0x72BC0C&#8203;: S\_regatom \(regcomp\.c&#8203;:12792\)
==44674==    by 0x73A835&#8203;: S\_regpiece \(regcomp\.c&#8203;:10880\)
==44674==    by 0x73A835&#8203;: S\_regbranch \(regcomp\.c&#8203;:10805\)
==44674==    by 0x75D006&#8203;: S\_reg\.constprop\.46 \(regcomp\.c&#8203;:10550\)
==44674==    by 0x79B9A8&#8203;: Perl\_re\_op\_compile \(regcomp\.c&#8203;:6953\)
==44674==    by 0x4E7EC1&#8203;: Perl\_pmruntime \(op\.c&#8203;:5580\)
==44674==    by 0x66F07C&#8203;: Perl\_yyparse \(perly\.y&#8203;:1032\)
==44674==    by 0x53A658&#8203;: S\_parse\_body \(perl\.c&#8203;:2307\)
==44674==    by 0x5423E2&#8203;: perl\_parse \(perl\.c&#8203;:1634\)
==44674==    by 0x42BC87&#8203;: main \(perlmain\.c&#8203;:114\)
==44674==  Address 0x5f7c858 is 0 bytes after a block of size 120 alloc'd
==44674==    at 0x4C27C0F&#8203;: malloc \(vg\_replace\_malloc\.c&#8203;:299\)
==44674==    by 0x7F13BC&#8203;: Perl\_safesysmalloc \(util\.c&#8203;:153\)
==44674==    by 0x79AE5D&#8203;: Perl\_re\_op\_compile \(regcomp\.c&#8203;:6803\)
==44674==    by 0x4E7EC1&#8203;: Perl\_pmruntime \(op\.c&#8203;:5580\)
==44674==    by 0x66F07C&#8203;: Perl\_yyparse \(perly\.y&#8203;:1032\)
==44674==    by 0x53A658&#8203;: S\_parse\_body \(perl\.c&#8203;:2307\)
==44674==    by 0x5423E2&#8203;: perl\_parse \(perl\.c&#8203;:1634\)
==44674==    by 0x42BC87&#8203;: main \(perlmain\.c&#8203;:114\)
==44674== 
panic&#8203;: reg\_node overrun trying to emit 0\, 5f7c85c>=5f7c858 at \-e line 1\.
==44674== 
==44674== HEAP SUMMARY&#8203;:
==44674==     in use at exit&#8203;: 110\,368 bytes in 571 blocks
==44674==   total heap usage&#8203;: 739 allocs\, 168 frees\, 141\,739 bytes allocated
==44674== 
==44674== LEAK SUMMARY&#8203;:
==44674==    definitely lost&#8203;: 0 bytes in 0 blocks
==44674==    indirectly lost&#8203;: 0 bytes in 0 blocks
==44674==      possibly lost&#8203;: 0 bytes in 0 blocks
==44674==    still reachable&#8203;: 110\,368 bytes in 571 blocks
==44674==         suppressed&#8203;: 0 bytes in 0 blocks
==44674== Rerun with \-\-leak\-check=full to see details of leaked memory
==44674== 
==44674== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==44674== ERROR SUMMARY&#8203;: 1 errors from 1 contexts \(suppressed&#8203;: 0 from 0\)


\*\*PERL \-V\*\*

Summary of my perl5 \(revision 5 version 23 subversion 4\) configuration&#8203;:
&nbsp;  Commit id&#8203;: a7dba6f870a82e3be87bda50593cb5d2042277fd
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt11\-1\+deb8u4 \(2015\-09\-19\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DDEBUG\_LEAKING\_SCALARS \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.9\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/4\.9/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Oct 15 2015 20&#8203;:45&#8203;:21
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4
&nbsp;    \.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thanks for the report\.

Fixed by 9457bb3f08028eb92e8c712a484c94d427c6009a

\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for submitting this report\.  You have helped make Perl better\.
&nbsp;    
With the release of Perl 5\.24\.0 on May 9\, 2016\, this and 149 other issues have been resolved\.

Perl 5\.24\.0 may be downloaded via https://metacpan.org/release/RJBS/perl-5.24.0

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
