### ISSUE TITLE
SIGSEGV in S_study_chunk - access inside an unallocated block in arena "client"

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14997]
Migrated from [rt.perl.org#126405](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126405) (status was 'resolved')

Searchable as RT126405$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers a segmentation fault in the perl interpreter\. The testcase is the file&#8203;:

/\(?&#8203;:\.||\)\(?|\)000000000@&#8203;/

This one comes with a valgrind message I haven't seen before\, and a search of RT reveals no open tickets referencing S\_study\_chunk\.

\*\*GDB\*\*

\(gdb\) run
Starting program&#8203;: /home/dcollins/perldebug/perl \-e /\\\(\\?&#8203;:\.\\|\\|\\\)\\\(\\?\\|\\\)000000000@&#8203;/
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.

Program received signal SIGSEGV\, Segmentation fault\.
S\_study\_chunk \(pRExC\_state=0x7fffffffd9c0\, scanp=0x40\, minlenp=0x12800\, deltap=0x1211ee0\, last=0x40\, data=0x40\, stopparen=\-1\, recursed\_depth=0\, flags=11264\, depth=0\, 
&nbsp;    and\_withp=\<optimized out>\) at regcomp\.c&#8203;:3922
3922               && \(\(PL\_regkind\[OP\(n\)\] == NOTHING && \(noff = NEXT\_OFF\(n\)\)\)
\(gdb\) bt
\#0  S\_study\_chunk \(pRExC\_state=0x7fffffffd9c0\, scanp=0x40\, minlenp=0x12800\, deltap=0x1211ee0\, last=0x40\, data=0x40\, stopparen=\-1\, recursed\_depth=0\, flags=11264\, depth=0\, 
&nbsp;    and\_withp=\<optimized out>\) at regcomp\.c&#8203;:3922
\#1  0x00000000007a53c4 in Perl\_re\_op\_compile \(patternp=0x1211fb0\, pat\_count=2048\, expr=0x2c00\, eng=0x1211ee0\, old\_re=0x7fffffffd9a0\, is\_bare\_re=0xd\, orig\_rx\_flags=0\, 
&nbsp;    pm\_flags=0\) at regcomp\.c&#8203;:7158
\#2  0x00000000004e7ec2 in Perl\_pmruntime \(o=0x1211e68\, expr=0x1211e28\, repl=0x12800\, isreg=224\, floor=7948352\) at op\.c&#8203;:5580
\#3  0x000000000066f07d in Perl\_yyparse \(gramtype=18947688\) at perly\.y&#8203;:1032
\#4  0x000000000053a659 in S\_parse\_body \(env=env@&#8203;entry=0x0\, xsinit=xsinit@&#8203;entry=0x42c060 \<xs\_init>\) at perl\.c&#8203;:2307
\#5  0x00000000005423e3 in perl\_parse \(my\_perl=\<optimized out>\, xsinit=xsinit@&#8203;entry=0x42c060 \<xs\_init>\, argc=\<optimized out>\, argv=\<optimized out>\, env=env@&#8203;entry=0x0\)
&nbsp;    at perl\.c&#8203;:1634
\#6  0x000000000042bc88 in main \(argc=3\, argv=0x7fffffffe338\, env=0x7fffffffe358\) at perlmain\.c&#8203;:114
\(gdb\) info locals
noff = 75776
min\_subtract = 0
unfolded\_multi\_char = false
scan = 0x1211f28
data\_fake = \{pos\_min = 0\, pos\_delta = 0\, last\_found = 0x0\, last\_end = 0\, last\_start\_min = 0\, last\_start\_max = 0\, longest = 0x0\, longest\_fixed = 0x0\, offset\_fixed = 0\, 
&nbsp;  minlen\_fixed = 0x0\, lookbehind\_fixed = 0\, longest\_float = 0x0\, offset\_float\_min = 0\, offset\_float\_max = 0\, minlen\_float = 0x0\, lookbehind\_float = 0\, flags = 0\, 
&nbsp;  whilem\_c = 0\, last\_closep = 0x7fffffffd9a0\, start\_class = 0x7fffffffd800\}
re\_debug\_flags = 0


\*\*VALGRIND\*\*

==41612== Memcheck\, a memory error detector
==41612== Copyright \(C\) 2002\-2015\, and GNU GPL'd\, by Julian Seward et al\.
==41612== Using Valgrind\-3\.11\.0 and LibVEX; rerun with \-h for copyright info
==41612== Command&#8203;: /home/dcollins/perldebug/perl \-e /\(?&#8203;:\.||\)\(?|\)000000000@&#8203;/
==41612== 
==41612== Invalid read of size 1
==41612==    at 0x761CA4&#8203;: S\_study\_chunk\.constprop\.51 \(regcomp\.c&#8203;:3922\)
==41612==    by 0x7A53C3&#8203;: Perl\_re\_op\_compile \(regcomp\.c&#8203;:7158\)
==41612==    by 0x4E7EC1&#8203;: Perl\_pmruntime \(op\.c&#8203;:5580\)
==41612==    by 0x66F07C&#8203;: Perl\_yyparse \(perly\.y&#8203;:1032\)
==41612==    by 0x53A658&#8203;: S\_parse\_body \(perl\.c&#8203;:2307\)
==41612==    by 0x5423E2&#8203;: perl\_parse \(perl\.c&#8203;:1634\)
==41612==    by 0x42BC87&#8203;: main \(perlmain\.c&#8203;:114\)
==41612==  Address 0x5fc67a9 is 293\,625 bytes inside an unallocated block of size 4\,002\,608 in arena "client"
==41612== 
==41612== 
==41612== HEAP SUMMARY&#8203;:
==41612==     in use at exit&#8203;: 118\,228 bytes in 572 blocks
==41612==   total heap usage&#8203;: 772 allocs\, 200 frees\, 143\,760 bytes allocated
==41612== 
==41612== LEAK SUMMARY&#8203;:
==41612==    definitely lost&#8203;: 0 bytes in 0 blocks
==41612==    indirectly lost&#8203;: 0 bytes in 0 blocks
==41612==      possibly lost&#8203;: 0 bytes in 0 blocks
==41612==    still reachable&#8203;: 118\,228 bytes in 572 blocks
==41612==         suppressed&#8203;: 0 bytes in 0 blocks
==41612== Rerun with \-\-leak\-check=full to see details of leaked memory
==41612== 
==41612== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==41612== ERROR SUMMARY&#8203;: 1 errors from 1 contexts \(suppressed&#8203;: 0 from 0\)


\*\*PERL \-V\*\*

Summary of my perl5 \(revision 5 version 23 subversion 4\) configuration&#8203;:
&nbsp;  Commit id&#8203;: a7dba6f870a82e3be87bda50593cb5d2042277fd
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt11\-1\+deb8u4 \(2015\-09\-19\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DDEBUG\_LEAKING\_SCALARS \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.9\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/4\.9/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Oct 15 2015 20&#8203;:45&#8203;:21
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.4
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @khwilliamson

On 10/19/2015 08&#8203;:30 PM\, Dan Collins \(via RT\) wrote&#8203;:
> \# New Ticket Created by  Dan Collins
> \# Please include the string&#8203;:  \[perl \#126405\]
> \# in the subject line of all future correspondence about this issue\.
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126405 >
>
>
> Greetings Porters\,
>
> I have compiled bleadperl with the afl\-gcc compiler using&#8203;:
>
> \./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
> AFL\_HARDEN=1 make && make test
>
> And then fuzzed the resulting binary using&#8203;:
>
> AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;
>
> After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers a segmentation fault in the perl interpreter\. The testcase is the file&#8203;:
>
> /\(?&#8203;:\.||\)\(?|\)000000000@&#8203;/
>
> This one comes with a valgrind message I haven't seen before\, and a search of RT reveals no open tickets referencing S\_study\_chunk\.
>

I have bisected this to the following commit

3018b823898645e44b8c37c70ac5c6302b031381 is the first bad commit
commit 3018b823898645e44b8c37c70ac5c6302b031381
Author&#8203;: Karl Williamson \<public@&#8203;khwilliamson\.com>
Date&#8203;:   Mon Dec 17 21&#8203;:37&#8203;:40 2012 \-0700

&nbsp;     Consolidate some regex OPS

&nbsp;     The regular rexpression operation POSIXA works on any of the 
\(currently\)
&nbsp;     16 posix classes \(like \\w and \[&#8203;:graph&#8203;:\]\) under the regex modifier /a\.
&nbsp;     This commit creates similar operations for the other modifiers&#8203;: POSIXL
&nbsp;     \(for /l\)\, POSIXD \(for /d\)\, POSIXU \(for /u\)\, plus their complements\.

&nbsp;     It causes these ops to be generated instead of the ALNUM\, DIGIT\,
&nbsp;     HORIZWS\, SPACE\, and VERTWS ops\, as well as all their variants\.  The net
&nbsp;     saving is 22 regnode types\.

&nbsp;     The reason to do this is for maintenance\.  As of this commit\, there are
&nbsp;     now 22 fewer node types for which code has to be maintained\.  The code
&nbsp;     for each variant was essentially the same logic\, but on different
&nbsp;     operands\.  It would be easy to make a change to one copy and forget to
&nbsp;     make the corresponding change in the others\.  Indeed\, this patch fixes
&nbsp;     \[perl \#114272\] in which one copy was out of sync with others\.

&nbsp;     This patch actually reduces the number of separate code paths to 5&#8203;:
&nbsp;     POSIXA\, NPOSIXA\, POSIXL\, POSIXD\, and POSIXU\.  The complements of the
&nbsp;     last 3 use the same code path as their non\-complemented version\, except
&nbsp;     that a variable is initialized differently\.  The code then XORs this
&nbsp;     variable with its result to do the complementing or not\.  Further\, the
&nbsp;     POSIXD branch now just checks if the target string being matched is
&nbsp;     UTF\-8 or not\, and then jumps to either the POSIXU or POSIXA code
&nbsp;     respectively\.  So\, there are effectively only 4 cases that are coded&#8203;:
&nbsp;     POSIXA\, NPOSIXA\, POSIXL\, and POSIXU\.  \(POSIXA doesn't have to worry
&nbsp;     about UTF\-8\, while NPOSIXA does\, hence these for efficiency are coded
&nbsp;     separately\.\)

&nbsp;     Removing all this code saves memory\.  The output of the Linux size
&nbsp;     command shows that the perl executable was shrunk by 33K bytes on my
&nbsp;     platform compiled under \-O0 \(\.7%\) and by 18K bytes \(1\.3%\) under \-O2\.

&nbsp;     The reason this patch was doable was previous work in numbering the
&nbsp;     POSIX classes\, so that they could be indexed in arrays and bit
&nbsp;     positions\.  This is a large patch; I didn't see how to break it into
&nbsp;     smaller components\.

&nbsp;     I chose to make this code more efficient as opposed to saving even more
&nbsp;     memory\.  Thus there is a separate loop that is jumped to after we know
&nbsp;     we have to load a swash; this just saves having to test if the swash is
&nbsp;     loaded each time through the loop\.  I avoid loading the swash until
&nbsp;     absolutely necessary\.  In places in the previous version of this code\,
&nbsp;     the swash was loaded when the input was UTF\-8\, even if it wasn't yet
&nbsp;     needed \(and might never be if the input didn't contain anything above
&nbsp;     Latin1\); apparently to avoid the extra test per iteration\.

&nbsp;     The Perl test suite runs slightly faster on my platform with this patch
&nbsp;     under \-O0\, and the speeds are indistinguishable under \-O2\.  This is in
&nbsp;     spite of these new POSIX regops being unknown to the regex optimizer
&nbsp;     \(this will be addressed in future commits\)\, and extra machine
&nbsp;     instructions being required for each character \(the xor\, and some
&nbsp;     shifting and masking\)\.  I expect this is a result of better 
caching\, and
&nbsp;     not loading swashes unless absolutely necessary\.

> \*\*GDB\*\*
>
> \(gdb\) run
> Starting program&#8203;: /home/dcollins/perldebug/perl \-e /\\\(\\?&#8203;:\.\\|\\|\\\)\\\(\\?\\|\\\)000000000@&#8203;/
> \[Thread debugging using libthread\_db enabled\]
> Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
>
> Program received signal SIGSEGV\, Segmentation fault\.
> S\_study\_chunk \(pRExC\_state=0x7fffffffd9c0\, scanp=0x40\, minlenp=0x12800\, deltap=0x1211ee0\, last=0x40\, data=0x40\, stopparen=\-1\, recursed\_depth=0\, flags=11264\, depth=0\,
>      and\_withp=\<optimized out>\) at regcomp\.c&#8203;:3922
> 3922               && \(\(PL\_regkind\[OP\(n\)\] == NOTHING && \(noff = NEXT\_OFF\(n\)\)\)
> \(gdb\) bt
> \#0  S\_study\_chunk \(pRExC\_state=0x7fffffffd9c0\, scanp=0x40\, minlenp=0x12800\, deltap=0x1211ee0\, last=0x40\, data=0x40\, stopparen=\-1\, recursed\_depth=0\, flags=11264\, depth=0\,
>      and\_withp=\<optimized out>\) at regcomp\.c&#8203;:3922
> \#1  0x00000000007a53c4 in Perl\_re\_op\_compile \(patternp=0x1211fb0\, pat\_count=2048\, expr=0x2c00\, eng=0x1211ee0\, old\_re=0x7fffffffd9a0\, is\_bare\_re=0xd\, orig\_rx\_flags=0\,
>      pm\_flags=0\) at regcomp\.c&#8203;:7158
> \#2  0x00000000004e7ec2 in Perl\_pmruntime \(o=0x1211e68\, expr=0x1211e28\, repl=0x12800\, isreg=224\, floor=7948352\) at op\.c&#8203;:5580
> \#3  0x000000000066f07d in Perl\_yyparse \(gramtype=18947688\) at perly\.y&#8203;:1032
> \#4  0x000000000053a659 in S\_parse\_body \(env=env@&#8203;entry=0x0\, xsinit=xsinit@&#8203;entry=0x42c060 \<xs\_init>\) at perl\.c&#8203;:2307
> \#5  0x00000000005423e3 in perl\_parse \(my\_perl=\<optimized out>\, xsinit=xsinit@&#8203;entry=0x42c060 \<xs\_init>\, argc=\<optimized out>\, argv=\<optimized out>\, env=env@&#8203;entry=0x0\)
>      at perl\.c&#8203;:1634
> \#6  0x000000000042bc88 in main \(argc=3\, argv=0x7fffffffe338\, env=0x7fffffffe358\) at perlmain\.c&#8203;:114
> \(gdb\) info locals
> noff = 75776
> min\_subtract = 0
> unfolded\_multi\_char = false
> scan = 0x1211f28
> data\_fake = \{pos\_min = 0\, pos\_delta = 0\, last\_found = 0x0\, last\_end = 0\, last\_start\_min = 0\, last\_start\_max = 0\, longest = 0x0\, longest\_fixed = 0x0\, offset\_fixed = 0\,
>    minlen\_fixed = 0x0\, lookbehind\_fixed = 0\, longest\_float = 0x0\, offset\_float\_min = 0\, offset\_float\_max = 0\, minlen\_float = 0x0\, lookbehind\_float = 0\, flags = 0\,
>    whilem\_c = 0\, last\_closep = 0x7fffffffd9a0\, start\_class = 0x7fffffffd800\}
> re\_debug\_flags = 0
>
>
> \*\*VALGRIND\*\*
>
> ==41612== Memcheck\, a memory error detector
> ==41612== Copyright \(C\) 2002\-2015\, and GNU GPL'd\, by Julian Seward et al\.
> ==41612== Using Valgrind\-3\.11\.0 and LibVEX; rerun with \-h for copyright info
> ==41612== Command&#8203;: /home/dcollins/perldebug/perl \-e /\(?&#8203;:\.||\)\(?|\)000000000@&#8203;/
> ==41612==
> ==41612== Invalid read of size 1
> ==41612==    at 0x761CA4&#8203;: S\_study\_chunk\.constprop\.51 \(regcomp\.c&#8203;:3922\)
> ==41612==    by 0x7A53C3&#8203;: Perl\_re\_op\_compile \(regcomp\.c&#8203;:7158\)
> ==41612==    by 0x4E7EC1&#8203;: Perl\_pmruntime \(op\.c&#8203;:5580\)
> ==41612==    by 0x66F07C&#8203;: Perl\_yyparse \(perly\.y&#8203;:1032\)
> ==41612==    by 0x53A658&#8203;: S\_parse\_body \(perl\.c&#8203;:2307\)
> ==41612==    by 0x5423E2&#8203;: perl\_parse \(perl\.c&#8203;:1634\)
> ==41612==    by 0x42BC87&#8203;: main \(perlmain\.c&#8203;:114\)
> ==41612==  Address 0x5fc67a9 is 293\,625 bytes inside an unallocated block of size 4\,002\,608 in arena "client"
> ==41612==
> ==41612==
> ==41612== HEAP SUMMARY&#8203;:
> ==41612==     in use at exit&#8203;: 118\,228 bytes in 572 blocks
> ==41612==   total heap usage&#8203;: 772 allocs\, 200 frees\, 143\,760 bytes allocated
> ==41612==
> ==41612== LEAK SUMMARY&#8203;:
> ==41612==    definitely lost&#8203;: 0 bytes in 0 blocks
> ==41612==    indirectly lost&#8203;: 0 bytes in 0 blocks
> ==41612==      possibly lost&#8203;: 0 bytes in 0 blocks
> ==41612==    still reachable&#8203;: 118\,228 bytes in 572 blocks
> ==41612==         suppressed&#8203;: 0 bytes in 0 blocks
> ==41612== Rerun with \-\-leak\-check=full to see details of leaked memory
> ==41612==
> ==41612== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
> ==41612== ERROR SUMMARY&#8203;: 1 errors from 1 contexts \(suppressed&#8203;: 0 from 0\)
>
>
> \*\*PERL \-V\*\*
>
> Summary of my perl5 \(revision 5 version 23 subversion 4\) configuration&#8203;:
>    Commit id&#8203;: a7dba6f870a82e3be87bda50593cb5d2042277fd
>    Platform&#8203;:
>      osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
>      uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt11\-1\+deb8u4 \(2015\-09\-19\) x86\_64 gnulinux '
>      config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DDEBUG\_LEAKING\_SCALARS \-des'
>      hint=recommended\, useposix=true\, d\_sigaction=define
>      useithreads=undef\, usemultiplicity=undef
>      use64bitint=define\, use64bitall=define\, uselongdouble=define
>      usemymalloc=n\, bincompat5005=undef
>    Compiler&#8203;:
>      cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
>      optimize='\-g'\,
>      cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
>      ccversion=''\, gccversion='4\.9\.2'\, gccosandvers=''
>      intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
>      d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
>      ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
>      alignbytes=16\, prototype=define
>    Linker and Libraries&#8203;:
>      ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
>      libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/4\.9/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
>      libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
>      perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
>      libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
>      gnulibc\_version='2\.19'
>    Dynamic Linking&#8203;:
>      dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
>      cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'
>
>
> Characteristics of this binary \(from libperl\)&#8203;:
>    Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
>                          PERL\_DONT\_CREATE\_GVSV
>                          PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
>                          PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
>                          USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
>                          USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
>                          USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
>                          USE\_PERLIO USE\_PERL\_ATOF
>    Built under linux
>    Compiled at Oct 15 2015 20&#8203;:45&#8203;:21
>    @&#8203;INC&#8203;:
>      /usr/local/perl\-afl/lib/site\_perl/5\.23\.4/x86\_64\-linux\-ld
>      /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
>      /usr/local/perl\-afl/lib/5\.23\.4/x86\_64\-linux\-ld
>      /usr/local/perl\-afl/lib/5\.23\.4
>      \.
>
>

I

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thanks for reporting this\.

Fixed by b297756b5d78ef23f3ebf878d0342947ece424aa
and tested for in 80edda0d5872f642d1b92e7581eb0882e59b9c2e
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for submitting this report\.  You have helped make Perl better\.
&nbsp;    
With the release of Perl 5\.24\.0 on May 9\, 2016\, this and 149 other issues have been resolved\.

Perl 5\.24\.0 may be downloaded via https://metacpan.org/release/RJBS/perl-5.24.0

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
