### ISSUE TITLE
Assert fail w/o other symptoms - pp_sys.c:690 Perl_pp_pipe_op when first arg to pipe is definitely not a filehandle

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15015]
Migrated from [rt.perl.org#126480](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126480) (status was 'resolved')

Searchable as RT126480$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers an assert fail in DEBUGGING perls without any other symptoms in the normal perl interpreter\. The testcase is the file&#8203;:

pipe$$5\,0

dcollins@&#8203;nightshade64&#8203;:/usr/local/perl\-afl$ \./bin/perl \-e 'pipe$$5\,0'
perl&#8203;: pp\_sys\.c&#8203;:690&#8203;: Perl\_pp\_pipe\_op&#8203;: Assertion \`\(\(\(\(rgv\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(rgv\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(rgv\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.
Aborted

The output with a normal perl is the expected error&#8203;:

dcollins@&#8203;nightshade64&#8203;:/usr/local/perl\-afl$ ~/perl/perl \-e 'pipe$$5\,0'           
Bad symbol for filehandle at \-e line 1\.


\*\*GDB\*\*

\(gdb\) run
Starting program&#8203;: /usr/local/perl\-afl/bin/perl \-e pipe\\$\\$5\,0
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
bperl&#8203;: pp\_sys\.c&#8203;:690&#8203;: Perl\_pp\_pipe\_op&#8203;: Assertion \`\(\(\(\(rgv\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(rgv\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(rgv\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6cf4107 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6cf4107 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x00007ffff6cf54e8 in abort \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#2  0x00007ffff6ced226 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#3  0x00007ffff6ced2d2 in \_\_assert\_fail \(\)
&nbsp;   from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#4  0x0000000000b95275 in Perl\_pp\_pipe\_op \(\) at pp\_sys\.c&#8203;:690
\#5  0x00000000007bdf7f in Perl\_runops\_debug \(\) at dump\.c&#8203;:2224
\#6  0x0000000000527fc1 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2459
\#7  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2382
\#8  0x0000000000428b18 in main \(argc=3\, argv=0x7fffffffe658\,
&nbsp;    env=0x7fffffffe678\) at perlmain\.c&#8203;:116
\(gdb\) f 4
\#4  0x0000000000b95275 in Perl\_pp\_pipe\_op \(\) at pp\_sys\.c&#8203;:690
690         assert \(isGV\_with\_GP\(rgv\)\);
\(gdb\) info locals
sp = 0x11a8a20
rstio = \<optimized out>
wstio = \<optimized out>
fd = \{0\, 0\}
wgv = 0x11ba5a0
rgv = 0x11a30a0 \<PL\_sv\_undef>
\_\_PRETTY\_FUNCTION\_\_ = "Perl\_pp\_pipe\_op"
\(gdb\) q
A debugging session is active\.

&nbsp;        Inferior 1 \[process 4065\] will be killed\.

Quit anyway? \(y or n\) y


\*\*VALGRIND\*\*

dcollins@&#8203;nightshade64&#8203;:/usr/local/perl\-afl$ valgrind \./bin/perl \-e 'pipe$$5\,0'
==11068== Memcheck\, a memory error detector
==11068== Copyright \(C\) 2002\-2015\, and GNU GPL'd\, by Julian Seward et al\.
==11068== Using Valgrind\-3\.11\.0 and LibVEX; rerun with \-h for copyright info
==11068== Command&#8203;: \./bin/perl \-e pipe$$5\,0
==11068==
perl&#8203;: pp\_sys\.c&#8203;:690&#8203;: Perl\_pp\_pipe\_op&#8203;: Assertion \`\(\(\(\(rgv\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(rgv\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(rgv\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.
==11068==
==11068== Process terminating with default action of signal 6 \(SIGABRT\)
==11068==    at 0x5BDC107&#8203;: raise \(raise\.c&#8203;:56\)
==11068==    by 0x5BDD4E7&#8203;: abort \(abort\.c&#8203;:89\)
==11068==    by 0x5BD5225&#8203;: \_\_assert\_fail\_base \(assert\.c&#8203;:92\)
==11068==    by 0x5BD52D1&#8203;: \_\_assert\_fail \(assert\.c&#8203;:101\)
==11068==    by 0xB95274&#8203;: Perl\_pp\_pipe\_op \(pp\_sys\.c&#8203;:690\)
==11068==    by 0x7BDF7E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==11068==    by 0x527FC0&#8203;: S\_run\_body \(perl\.c&#8203;:2459\)
==11068==    by 0x527FC0&#8203;: perl\_run \(perl\.c&#8203;:2382\)
==11068==    by 0x428B17&#8203;: main \(perlmain\.c&#8203;:116\)
==11068==
==11068== HEAP SUMMARY&#8203;:
==11068==     in use at exit&#8203;: 110\,234 bytes in 542 blocks
==11068==   total heap usage&#8203;: 681 allocs\, 139 frees\, 134\,449 bytes allocated
==11068==
==11068== LEAK SUMMARY&#8203;:
==11068==    definitely lost&#8203;: 176 bytes in 1 blocks
==11068==    indirectly lost&#8203;: 1\,974 bytes in 20 blocks
==11068==      possibly lost&#8203;: 0 bytes in 0 blocks
==11068==    still reachable&#8203;: 108\,084 bytes in 521 blocks
==11068==         suppressed&#8203;: 0 bytes in 0 blocks
==11068== Rerun with \-\-leak\-check=full to see details of leaked memory
==11068==
==11068== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==11068== ERROR SUMMARY&#8203;: 0 errors from 0 contexts \(suppressed&#8203;: 0 from 0\)
Aborted


\*\*PERL \-V\*\*

dcollins@&#8203;nightshade64&#8203;:/usr/local/perl\-afl$ \./bin/perl \-V
Summary of my perl5 \(revision 5 version 23 subversion 5\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 7195e5da55a40d15e29ad80562668bdd6895441f
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt11\-1\+deb8u4 \(2015\-09\-19\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='5\.2\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/x86\_64\-unknown\-linux\-gnu/5\.2\.0/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Oct 22 2015 15&#8203;:44&#8203;:40
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.5/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.5
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.5/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.5
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @tonycoz

On Wed Oct 28 19&#8203;:59&#8203;:00 2015\, dcollinsn@&#8203;gmail\.com wrote&#8203;:

> After reducing testcases using \`afl\-tmin\` and performing additional
> minimization by hand\, I have located the following testcase that
> triggers an assert fail in DEBUGGING perls without any other symptoms
> in the normal perl interpreter\. The testcase is the file&#8203;:
> 
> pipe$$5\,0
> 
> dcollins@&#8203;nightshade64&#8203;:/usr/local/perl\-afl$ \./bin/perl \-e 'pipe$$5\,0'
> perl&#8203;: pp\_sys\.c&#8203;:690&#8203;: Perl\_pp\_pipe\_op&#8203;: Assertion \`\(\(\(\(rgv\)\->sv\_flags &
> \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(rgv\)\->sv\_flags
> & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(rgv\)\->sv\_flags & 0xff\)\) ==
> SVt\_PVLV\)\)' failed\.
> Aborted
> 
> The output with a normal perl is the expected error&#8203;:
> 
> dcollins@&#8203;nightshade64&#8203;:/usr/local/perl\-afl$ ~/perl/perl \-e 'pipe$$5\,0'
> Bad symbol for filehandle at \-e line 1\.

I suspect the assertions are incorrect here\.

S\_rv2gv returns &PL\_sv\_undef when it can't turn the value into something resembling a GV\, and the GvIOn\(\) macro can handle that \(by croaking\)\.

So the assertions would be something like&#8203;:

<details><summary>Inline Patch</summary>

```diff
diff --git a/pp_sys.c b/pp_sys.c
index 373590f..8589413 100644
--- a/pp_sys.c
+++ b/pp_sys.c
@@ -695,8 +695,10 @@ PP(pp_pipe_op)
     GV * const wgv = MUTABLE_GV(POPs);
     GV * const rgv = MUTABLE_GV(POPs);
 
-    assert (isGV_with_GP(rgv));
-    assert (isGV_with_GP(wgv));
+    /* rv2gv pushes PL_sv_undef when it can't make a GV, and GvIOn() properly croaks
+       when it's supplied with such */
+    assert ((SV*)rgv == &PL_sv_undef || isGV_with_GP(rgv));
+    assert ((SV*)wgv == &PL_sv_undef || isGV_with_GP(wgv));
     rstio = GvIOn(rgv);
     if (IoIFP(rstio))
        do_close(rgv, FALSE);


```
</details>
The other I/O "openers" (socket, sysopen, open) either call GvIOn() or do a non-assertion test of isGV_with_GP().

Possibly the assertions should just be removed\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Wed Oct 28 20&#8203;:49&#8203;:47 2015\, tonyc wrote&#8203;:
> Possibly the assertions should just be removed\.

Like in the attached patch\.

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

<details><summary>0001-perl-126480-pipe-doesn-t-need-the-assertions.patch</summary>

```diff
From 992ebee3f63e16317109eca1eb0d76925c594593 Mon Sep 17 00:00:00 2001
From: Tony Cook <tony@develop-help.com>
Date: Mon, 2 Nov 2015 17:22:25 +1100
Subject: [perl 126480] pipe() doesn't need the assertions

GvIOn() already performs the checks and produces a nice error message.
---
 MANIFEST           |  1 +
 pp_sys.c           |  2 --
 t/lib/croak/pp_sys | 16 ++++++++++++++++
 3 files changed, 17 insertions(+), 2 deletions(-)
 create mode 100644 t/lib/croak/pp_sys

diff --git a/MANIFEST b/MANIFEST
index f07488f..ed47673 100644
--- a/MANIFEST
+++ b/MANIFEST
@@ -5043,6 +5043,7 @@ t/lib/croak/op			Test croak calls from op.c
 t/lib/croak/pp			Test croak calls from pp.c
 t/lib/croak/pp_ctl		Test croak calls from pp_ctl.c
 t/lib/croak/pp_hot		Test croak calls from pp_hot.c
+t/lib/croak/pp_sys		Test croak calls from pp_sys.c
 t/lib/croak.t			Test calls to Perl_croak() in the C source.
 t/lib/croak/toke		Test croak calls from toke.c
 t/lib/cygwin.t			Builtin cygwin function tests
diff --git a/pp_sys.c b/pp_sys.c
index 373590f..15b4d8b 100644
--- a/pp_sys.c
+++ b/pp_sys.c
@@ -695,8 +695,6 @@ PP(pp_pipe_op)
     GV * const wgv = MUTABLE_GV(POPs);
     GV * const rgv = MUTABLE_GV(POPs);
 
-    assert (isGV_with_GP(rgv));
-    assert (isGV_with_GP(wgv));
     rstio = GvIOn(rgv);
     if (IoIFP(rstio))
 	do_close(rgv, FALSE);
diff --git a/t/lib/croak/pp_sys b/t/lib/croak/pp_sys
new file mode 100644
index 0000000..001baa3
--- /dev/null
+++ b/t/lib/croak/pp_sys
@@ -0,0 +1,16 @@
+__END__
+# pp_sys.c
+# NAME pipe() croaks on bad left side [perl #126480]
+# SKIP ? use Config; !$Config{d_pipe} && "No pipe() available"
+my $fh;
+pipe($$5, $fh)
+EXPECT
+Bad symbol for filehandle at - line 3.
+########
+# NAME pipe() croaks on bad left side [perl #126480]
+# SKIP ? use Config; !$Config{d_pipe} && "No pipe() available"
+my $fh;
+pipe($fh, $$5)
+EXPECT
+Bad symbol for filehandle at - line 2.
+########
-- 
2.1.4


```
</details>

**Comment by p5pRT** [comment]
### From @tonycoz

On Sun Nov 01 22&#8203;:23&#8203;:07 2015\, tonyc wrote&#8203;:
> On Wed Oct 28 20&#8203;:49&#8203;:47 2015\, tonyc wrote&#8203;:
> > Possibly the assertions should just be removed\.
> 
> Like in the attached patch\.

Applied as e8c18a8486f7e900511cc2df8d2617ceab9ce437\, with a fix for the NAME line of the second test\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for submitting this report\.  You have helped make Perl better\.
&nbsp;    
With the release of Perl 5\.24\.0 on May 9\, 2016\, this and 149 other issues have been resolved\.

Perl 5\.24\.0 may be downloaded via https://metacpan.org/release/RJBS/perl-5.24.0

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
