### ISSUE TITLE
GPF/segfault while fuzzing Perl v5.20.2 and v5.23.4-81-g96524c2

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15038]
Migrated from [rt.perl.org#126601](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126601) (status was 'rejected')

Searchable as RT126601$

**Comment by p5pRT** [comment]
### From @geeknik

The following crashes Perl v5\.20\.2 and 5\.23\.4\-81\-g96524c2 with a General Protection Fault&#8203;:

perl \-e '$0=unpack p\,$0=u0000000'

==124949== Invalid read of size 1
==124949==    at 0x4C2ABC2&#8203;: strlen \(vg\_replace\_strmem\.c&#8203;:454\)
==124949==    by 0xA2D48B&#8203;: Perl\_newSVpv \(sv\.c&#8203;:9153\)
==124949==    by 0xE2FE96&#8203;: S\_unpack\_rec \(pp\_pack\.c&#8203;:1564\)
==124949==    by 0xEB5B0C&#8203;: Perl\_unpackstring \(pp\_pack\.c&#8203;:835\)
==124949==    by 0xEB63D7&#8203;: Perl\_pp\_unpack \(pp\_pack\.c&#8203;:1839\)
==124949==    by 0x7E0D0E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==124949==    by 0x544AF5&#8203;: S\_run\_body \(perl\.c&#8203;:2464\)
==124949==    by 0x544AF5&#8203;: perl\_run \(perl\.c&#8203;:2387\)
==124949==    by 0x42C617&#8203;: main \(perlmain\.c&#8203;:116\)
==124949==  Address 0x3030303030303075 is not stack'd\, malloc'd or \(recently\) free'd
==124949== 
==124949== 
==124949== Process terminating with default action of signal 11 \(SIGSEGV\)
==124949==  General Protection Fault
==124949==    at 0x4C2ABC2&#8203;: strlen \(vg\_replace\_strmem\.c&#8203;:454\)
==124949==    by 0xA2D48B&#8203;: Perl\_newSVpv \(sv\.c&#8203;:9153\)
==124949==    by 0xE2FE96&#8203;: S\_unpack\_rec \(pp\_pack\.c&#8203;:1564\)
==124949==    by 0xEB5B0C&#8203;: Perl\_unpackstring \(pp\_pack\.c&#8203;:835\)
==124949==    by 0xEB63D7&#8203;: Perl\_pp\_unpack \(pp\_pack\.c&#8203;:1839\)
==124949==    by 0x7E0D0E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==124949==    by 0x544AF5&#8203;: S\_run\_body \(perl\.c&#8203;:2464\)
==124949==    by 0x544AF5&#8203;: perl\_run \(perl\.c&#8203;:2387\)
==124949==    by 0x42C617&#8203;: main \(perlmain\.c&#8203;:116\)
Segmentation fault

**Comment by p5pRT** [comment]
### From @dcollinsn

Duplicate of \[perl \#126326\]\, and also not a bug\. The second argument to \`unpack p\` is interpreted as a pointer\. K0000000 is a bareword interpreted as a string\, and stored in memory \(due to endian\-ness\) as 0x30303030303030xx\. Of course\, there is no memory at that location\, certainly none accessible by perl\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @geeknik

Program received signal SIGSEGV\, Segmentation fault\.
strlen \(\) at \.\./sysdeps/x86\_64/strlen\.S&#8203;:106
106    \.\./sysdeps/x86\_64/strlen\.S&#8203;: No such file or directory\.
\(gdb\) bt
\#0  strlen \(\) at \.\./sysdeps/x86\_64/strlen\.S&#8203;:106
\#1  0x0000000000a2d48c in Perl\_newSVpv \(
&nbsp;    s=0x3030303030303075 \<error&#8203;: Cannot access memory at address 0x3030303030303075>\, 
&nbsp;    len=len@&#8203;entry=0\) at sv\.c&#8203;:9153
\#2  0x0000000000e2fe97 in S\_unpack\_rec \(symptr=symptr@&#8203;entry=0x7fffffffe010\, s=0x1210a68 ""\, 
&nbsp;    s@&#8203;entry=0x1210a60 "u0000000"\, strbeg=strbeg@&#8203;entry=0x1210a60 "u0000000"\, 
&nbsp;    strend=strend@&#8203;entry=0x1210a68 ""\, new\_s=new\_s@&#8203;entry=0x0\) at pp\_pack\.c&#8203;:1564
\#3  0x0000000000eb5b0d in Perl\_unpackstring \(pat=pat@&#8203;entry=0x1213390 "p"\, patend=0x1213391 ""\, 
&nbsp;    s=0x1210a60 "u0000000"\, strend=0x1210a68 ""\, flags=16\) at pp\_pack\.c&#8203;:835
\#4  0x0000000000eb63d8 in Perl\_pp\_unpack \(\) at pp\_pack\.c&#8203;:1839
\#5  0x00000000007e0d0f in Perl\_runops\_debug \(\) at dump\.c&#8203;:2224
\#6  0x0000000000544af6 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2464
\#7  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2387
\#8  0x000000000042c618 in main \(argc=3\, argv=0x7fffffffe358\, env=0x7fffffffe378\)
&nbsp;    at perlmain\.c&#8203;:116
\(gdb\) i r
rax            0x3030303030303075    3472328296227680373
rbx            0x11f6160    18833760
rcx            0x75    117
rdx            0x0    0
rsi            0x0    0
rdi            0x3030303030303075    3472328296227680373
rbp            0x11f8b58    0x11f8b58
rsp            0x7fffffffde68    0x7fffffffde68
r8             0x0    0
r9             0x1210a68    18942568
r10            0x1    1
r11            0x7f    127
r12            0x3030303030303075    3472328296227680373
r13            0x0    0
r14            0x11f8b50    18844496
r15            0x0    0
rip            0x7ffff6d40c8a    0x7ffff6d40c8a \<strlen\+42>
eflags         0x10297    \[ CF PF AF SF IF RF \]
cs             0x33    51
ss             0x2b    43
ds             0x0    0
es             0x0    0
fs             0x0    0
gs             0x0    0

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'rejected'
