### ISSUE TITLE
Assert fail/segfault in Perl_sv_pvn_force_flags

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15044]
Migrated from [rt.perl.org#126614](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126614) (status was 'resolved')

Searchable as RT126614$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers an assert fail in DEBUGGING perls without any other symptoms in the normal perl interpreter\. The testcase is the file&#8203;:

/\(?\{\}\)|\(??\{U&#8203;:0\}\)/|s|||g

dcollins@&#8203;nightshade64&#8203;:/usr/local/perl\-afl/out$ ~/perldebug/perl \-e '/\(?\{\}\)|\(??\{U&#8203;:0\}\)/|s|||g'
perl&#8203;: sv\.c&#8203;:9875&#8203;: Perl\_sv\_pvn\_force\_flags&#8203;: Assertion \`PL\_valid\_types\_PVX\[\(\(svtype\)\(\(\_svpvx\)\->sv\_flags & 0xff\)\) & 0xf\]' failed\.
Aborted

On non\-debugging perls\, this eventually leads to a segfault&#8203;:

==11561== Invalid read of size 8
==11561==    at 0x6630A5&#8203;: Perl\_pregfree2 \(regcomp\.c&#8203;:17498\)
==11561==    by 0x7B2CE7&#8203;: Perl\_sv\_clear \(sv\.c&#8203;:6458\)
==11561==    by 0x7ADD0F&#8203;: Perl\_sv\_free2 \(sv\.c&#8203;:6885\)
==11561==    by 0x6E9504&#8203;: S\_SvREFCNT\_dec \(inline\.h&#8203;:166\)
==11561==    by 0x6E9504&#8203;: S\_mg\_free\_struct \(mg\.c&#8203;:549\)
==11561==    by 0x6E9504&#8203;: Perl\_mg\_free \(mg\.c&#8203;:571\)
==11561==    by 0x7B2A0F&#8203;: Perl\_sv\_clear \(sv\.c&#8203;:6428\)
==11561==    by 0x7ADD0F&#8203;: Perl\_sv\_free2 \(sv\.c&#8203;:6885\)
==11561==    by 0x433874&#8203;: S\_SvREFCNT\_dec \(inline\.h&#8203;:166\)
==11561==    by 0x433874&#8203;: Perl\_op\_clear \(op\.c&#8203;:896\)
==11561==    by 0x43412B&#8203;: Perl\_op\_free \(op\.c&#8203;:779\)
==11561==    by 0x433FCB&#8203;: Perl\_op\_free \(op\.c&#8203;:762\)
==11561==    by 0x433808&#8203;: Perl\_op\_clear \(op\.c&#8203;:954\)
==11561==    by 0x43412B&#8203;: Perl\_op\_free \(op\.c&#8203;:779\)
==11561==    by 0x433FCB&#8203;: Perl\_op\_free \(op\.c&#8203;:762\)
==11561==  Address 0x28 is not stack'd\, malloc'd or \(recently\) free'd


\*\*GDB\*\*

\(gdb\) run
Starting program&#8203;: /home/dcollins/perldebug/perl \-e /\\\(\\?\\\{\\\}\\\)\\|\\\(\\?\\?\\\{U&#8203;:0\\\}\\\)/\\|s\\|\\|\\|g
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
perl&#8203;: sv\.c&#8203;:9875&#8203;: Perl\_sv\_pvn\_force\_flags&#8203;: Assertion \`PL\_valid\_types\_PVX\[\(\(svtype\)\(\(\_svpvx\)\->sv\_flags & 0xff\)\) & 0xf\]' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6cf4107 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6cf4107 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x00007ffff6cf54e8 in abort \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#2  0x00007ffff6ced226 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#3  0x00007ffff6ced2d2 in \_\_assert\_fail \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#4  0x00000000009d23dd in Perl\_sv\_pvn\_force\_flags \(sv=sv@&#8203;entry=0x11d8560\, lp=lp@&#8203;entry=0x7fffffffdfd0\, flags=flags@&#8203;entry=16384\) at sv\.c&#8203;:9875
\#5  0x00000000009dbb3e in Perl\_sv\_catpvn\_flags \(dsv=dsv@&#8203;entry=0x11d8560\, sstr=0x11d2460 ""\, slen=0\, flags=16384\) at sv\.c&#8203;:5361
\#6  0x00000000008f2bf3 in Perl\_pp\_subst \(\) at pp\_hot\.c&#8203;:3133
\#7  0x00000000007c90bf in Perl\_runops\_debug \(\) at dump\.c&#8203;:2224
\#8  0x0000000000532411 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2464
\#9  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2387
\#10 0x0000000000428928 in main \(argc=3\, argv=0x7fffffffe338\, env=0x7fffffffe358\) at perlmain\.c&#8203;:116
\(gdb\) f 4
\#4  0x00000000009d23dd in Perl\_sv\_pvn\_force\_flags \(sv=sv@&#8203;entry=0x11d8560\, lp=lp@&#8203;entry=0x7fffffffdfd0\, flags=flags@&#8203;entry=16384\) at sv\.c&#8203;:9875
9875            SvGROW\(sv\, len \+ 1\);
\(gdb\) info locals
\_svpvx = 0x11d8560
s = \<optimized out>
len = 6
\_\_PRETTY\_FUNCTION\_\_ = "Perl\_sv\_pvn\_force\_flags"


\*\*VALGRIND\*\*

==5662== Memcheck\, a memory error detector
==5662== Copyright \(C\) 2002\-2015\, and GNU GPL'd\, by Julian Seward et al\.
==5662== Using Valgrind\-3\.11\.0 and LibVEX; rerun with \-h for copyright info
==5662== Command&#8203;: /home/dcollins/perldebug/perl \-e /\(?\{\}\)|\(??\{U&#8203;:0\}\)/|s|||g
==5662== 
perl&#8203;: sv\.c&#8203;:9875&#8203;: Perl\_sv\_pvn\_force\_flags&#8203;: Assertion \`PL\_valid\_types\_PVX\[\(\(svtype\)\(\(\_svpvx\)\->sv\_flags & 0xff\)\) & 0xf\]' failed\.
==5662== 
==5662== Process terminating with default action of signal 6 \(SIGABRT\)
==5662==    at 0x5BDC107&#8203;: raise \(raise\.c&#8203;:56\)
==5662==    by 0x5BDD4E7&#8203;: abort \(abort\.c&#8203;:89\)
==5662==    by 0x5BD5225&#8203;: \_\_assert\_fail\_base \(assert\.c&#8203;:92\)
==5662==    by 0x5BD52D1&#8203;: \_\_assert\_fail \(assert\.c&#8203;:101\)
==5662==    by 0x9D23DC&#8203;: Perl\_sv\_pvn\_force\_flags \(sv\.c&#8203;:9875\)
==5662==    by 0x9DBB3D&#8203;: Perl\_sv\_catpvn\_flags \(sv\.c&#8203;:5361\)
==5662==    by 0x8F2BF2&#8203;: Perl\_pp\_subst \(pp\_hot\.c&#8203;:3133\)
==5662==    by 0x7C90BE&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==5662==    by 0x532410&#8203;: S\_run\_body \(perl\.c&#8203;:2464\)
==5662==    by 0x532410&#8203;: perl\_run \(perl\.c&#8203;:2387\)
==5662==    by 0x428927&#8203;: main \(perlmain\.c&#8203;:116\)
==5662== 
==5662== HEAP SUMMARY&#8203;:
==5662==     in use at exit&#8203;: 131\,879 bytes in 671 blocks
==5662==   total heap usage&#8203;: 858 allocs\, 187 frees\, 158\,569 bytes allocated
==5662== 
==5662== LEAK SUMMARY&#8203;:
==5662==    definitely lost&#8203;: 320 bytes in 1 blocks
==5662==    indirectly lost&#8203;: 2\,599 bytes in 38 blocks
==5662==      possibly lost&#8203;: 0 bytes in 0 blocks
==5662==    still reachable&#8203;: 128\,960 bytes in 632 blocks
==5662==         suppressed&#8203;: 0 bytes in 0 blocks
==5662== Rerun with \-\-leak\-check=full to see details of leaked memory
==5662== 
==5662== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==5662== ERROR SUMMARY&#8203;: 0 errors from 0 contexts \(suppressed&#8203;: 0 from 0\)
Aborted



\*\*PERL \-V\*\*

dcollins@&#8203;nightshade64&#8203;:/usr/local/perl\-afl$ \./bin/perl \-V
Summary of my perl5 \(revision 5 version 23 subversion 5\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 7195e5da55a40d15e29ad80562668bdd6895441f
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt11\-1\+deb8u4 \(2015\-09\-19\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='5\.2\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/x86\_64\-unknown\-linux\-gnu/5\.2\.0/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Oct 22 2015 15&#8203;:44&#8203;:40
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.5/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.5
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.5/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.5
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue Nov 10 19&#8203;:04&#8203;:55 2015\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> After reducing testcases using \`afl\-tmin\` and performing additional
> minimization by hand\, I have located the following testcase that
> triggers an assert fail in DEBUGGING perls without any other symptoms
> in the normal perl interpreter\. The testcase is the file&#8203;:
> 
> /\(?\{\}\)|\(??\{U&#8203;:0\}\)/|s|||g

This can be simplified further to&#8203;:

&nbsp;  s/\(?\{\}\)|\(??\{U&#8203;:0\}\)//g

> dcollins@&#8203;nightshade64&#8203;:/usr/local/perl\-afl/out$ ~/perldebug/perl \-e
> '/\(?\{\}\)|\(??\{U&#8203;:0\}\)/|s|||g'
> perl&#8203;: sv\.c&#8203;:9875&#8203;: Perl\_sv\_pvn\_force\_flags&#8203;: Assertion
> \`PL\_valid\_types\_PVX\[\(\(svtype\)\(\(\_svpvx\)\->sv\_flags & 0xff\)\) & 0xf\]'
> failed\.
> Aborted

There's two problems in the original&#8203;:

1\) it looks like \#124368 is biting us in a different way in that the regexp being used by pp\_subst is the one from the match

2\) pp\_subst\(\) \(in either example\) creates a new temp sv \(line 3078\)&#8203;:

&nbsp;    dstr = newSVpvn\_flags\(orig\, s\-orig\,
&nbsp;                    SVs\_TEMP | \(DO\_UTF8\(TARG\) ? SVf\_UTF8 : 0\)\);

then later calls CALLREGEXEC\(\) \(line 3129\)&#8203;:

&nbsp;    \} while \(CALLREGEXEC\(rx\, s\, strend\, orig\,
&nbsp;                             s == m\,    /\* Yields minend of 0 or 1 \*/
&nbsp;                 TARG\, NULL\,
&nbsp;        REXEC\_NOT\_FIRST|REXEC\_IGNOREPOS|REXEC\_FAIL\_ON\_UNDERFLOW\)\);

and the pp\_nextstate called when running the C\<U&#8203;:0> code calls FREETMPS\, releasing dstr\, and so the following \(line 3133\) tries to work with a freed SV&#8203;:

&nbsp;    sv\_catpvn\_nomg\_maybeutf8\(dstr\, s\, strend \- s\, DO\_UTF8\(TARG\)\);

and asserts\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Wed Dec 02 19&#8203;:45&#8203;:43 2015\, tonyc wrote&#8203;:
> 1\) it looks like \#124368 is biting us in a different way in that the
> regexp being used by pp\_subst is the one from the match

Or not\, s/// has the same empty regexp behaviour as m//

Tony

**Comment by p5pRT** [comment]
### From @hvds

I can't reproduce this with blead\. Bisect using&#8203;:

% Porting/bisect\.pl \-\-start=7195e5da55a40d15e29ad80562668bdd6895441f \-\-crash \-\-expect\-fail \-\-target=miniperl \-e '/\(?\{\}\)|\(??\{U&#8203;:0\}\)/|s|||g'

\.\.leads to 1dfbe6b4ad which is partway through the huge "revamp context system" from DaveM merged in February \(at 9d876b687d\)&#8203;:

It sounds reasonable to me that the context work fixes what appears to be a premature free\, so I'm resolving this ticket\.

Hugo

**Comment by p5pRT** [comment]
@hvds - Status changed from 'open' to 'resolved'
