### ISSUE TITLE
Segfault/assert fail with regex_sets warning

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15045]
Migrated from [rt.perl.org#126615](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126615) (status was 'resolved')

Searchable as RT126615$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers an assert fail in DEBUGGING perls and a segmentation fault in other perls\. The testcase is the file&#8203;:

00\./\(?\[\[0\]\+\(\)\+\]\)/

dcollins@&#8203;nightshade64&#8203;:\~$ perldebug/perl \-e '00\./\(?\[\[0\]\+\(\)\+\]\)/'
The regex\_sets feature is experimental in regex; marked by \<\-\- HERE in m/\(?\[ \<\-\- HERE \[0\]\+\(\)\+\]\)/ at \-e line 1\.
perl&#8203;: regcomp\.c&#8203;:13902&#8203;: S\_handle\_regex\_sets&#8203;: Assertion \`\(\! \(\(lhs\)\->sv\_flags & 0x00000100\)\)' failed\.
Aborted


\*\*GDB\*\*

\(gdb\) run
Starting program&#8203;: /home/dcollins/perl/perl \-e 00\./\\\(\\?\\\[\\\[0\\\]\+\\\(\\\)\+\\\]\\\)/
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
The regex\_sets feature is experimental in regex; marked by \<\-\- HERE in m/\(?\[ \<\-\- HERE \[0\]\+\(\)\+\]\)/ at \-e line 1\.

Program received signal SIGSEGV\, Segmentation fault\.
Perl\_\_invlist\_union\_maybe\_complement\_2nd \(a=a@&#8203;entry=0xe63898\,
&nbsp;    b=\<optimized out>\, complement\_b=complement\_b@&#8203;entry=false\,
&nbsp;    output=output@&#8203;entry=0x7fffffffd980\) at regcomp\.c&#8203;:8682
8682        array\_u = \_invlist\_array\_init\(u\, \(len\_a > 0 && array\_a\[0\] == 0\)
\(gdb\) bt
\#0  Perl\_\_invlist\_union\_maybe\_complement\_2nd \(a=a@&#8203;entry=0xe63898\,
&nbsp;    b=\<optimized out>\, complement\_b=complement\_b@&#8203;entry=false\,
&nbsp;    output=output@&#8203;entry=0x7fffffffd980\) at regcomp\.c&#8203;:8682
\#1  0x0000000000636dc5 in S\_handle\_regex\_sets \(
&nbsp;    pRExC\_state=pRExC\_state@&#8203;entry=0x7fffffffde70\,
&nbsp;    return\_invlist=return\_invlist@&#8203;entry=0x0\,
&nbsp;    flagp=flagp@&#8203;entry=0x7fffffffdad4\, depth=depth@&#8203;entry=5\,
&nbsp;    oregcomp\_parse=oregcomp\_parse@&#8203;entry=0xe6c3f1 "?\[\[0\]\+\(\)\+\]\)"\)
&nbsp;    at regcomp\.c&#8203;:13911
\#2  0x0000000000653f6a in S\_reg \(pRExC\_state=0x7fffffffde70\, paren=91\,
&nbsp;    flagp=0x7fffffffdad4\, depth=5\) at regcomp\.c&#8203;:10493
\#3  0x000000000063a521 in S\_regatom \(
&nbsp;    pRExC\_state=pRExC\_state@&#8203;entry=0x7fffffffde70\,
&nbsp;    flagp=flagp@&#8203;entry=0x7fffffffdc24\, depth=depth@&#8203;entry=4\) at regcomp\.c&#8203;:11801
\#4  0x0000000000646da2 in S\_regpiece \(depth=\<optimized out>\,
&nbsp;    flagp=\<synthetic pointer>\, pRExC\_state=0x7fffffffde70\) at regcomp\.c&#8203;:10879
\#5  S\_regbranch \(pRExC\_state=pRExC\_state@&#8203;entry=0x7fffffffde70\,
&nbsp;    flagp=flagp@&#8203;entry=0x7fffffffdc94\, first=first@&#8203;entry=1\,
&nbsp;    depth=depth@&#8203;entry=2\) at regcomp\.c&#8203;:10804
\#6  0x000000000065d916 in S\_reg \(
&nbsp;    pRExC\_state=pRExC\_state@&#8203;entry=0x7fffffffde70\,
&nbsp;    flagp=flagp@&#8203;entry=0x7fffffffdd54\, depth=1\, paren=0\) at regcomp\.c&#8203;:10549
\#7  0x00000000006819f6 in Perl\_re\_op\_compile \(patternp=patternp@&#8203;entry=0x0\,
\-\-\-Type \<return> to continue\, or q \<return> to quit\-\-\-
&nbsp;    pat\_count=\<optimized out>\, pat\_count@&#8203;entry=0\, expr=\<optimized out>\,
&nbsp;    expr@&#8203;entry=0xe6c1c8\, eng=\<optimized out>\, old\_re=old\_re@&#8203;entry=0x0\,
&nbsp;    is\_bare\_re=is\_bare\_re@&#8203;entry=0x0\, orig\_rx\_flags=0\, pm\_flags=0\)
&nbsp;    at regcomp\.c&#8203;:6954
\#8  0x00000000004b05c9 in Perl\_pmruntime \(o=0xe6c208\, expr=0xe6c1c8\,
&nbsp;    repl=0x0\, isreg=isreg@&#8203;entry=true\, floor=0\) at op\.c&#8203;:5580
\#9  0x00000000005ba77a in Perl\_yyparse \(gramtype=gramtype@&#8203;entry=258\)
&nbsp;    at perly\.y&#8203;:1032
\#10 0x00000000004e758d in S\_parse\_body \(xsinit=0x4274e0 \<xs\_init>\, env=0x0\)
&nbsp;    at perl\.c&#8203;:2312
\#11 perl\_parse \(my\_perl=\<optimized out>\,
&nbsp;    xsinit=xsinit@&#8203;entry=0x4274e0 \<xs\_init>\, argc=\<optimized out>\,
&nbsp;    argv=\<optimized out>\, env=env@&#8203;entry=0x0\) at perl\.c&#8203;:1634
\#12 0x0000000000427108 in main \(argc=3\, argv=0x7fffffffe668\,
&nbsp;    env=0x7fffffffe688\) at perlmain\.c&#8203;:114
\(gdb\) info locals
array\_b = \<optimized out>
len\_b = 2
u = 0xe638b0
array\_u = \<optimized out>
len\_u = \<optimized out>
i\_a = 0
i\_b = 0
i\_u = 0
count = 0


\*\*VALGRIND\*\*

==46142== Memcheck\, a memory error detector
==46142== Copyright \(C\) 2002\-2015\, and GNU GPL'd\, by Julian Seward et al\.
==46142== Using Valgrind\-3\.11\.0 and LibVEX; rerun with \-h for copyright info
==46142== Command&#8203;: perl/perl \-e 00\./\(?\[\[0\]\+\(\)\+\]\)/
==46142==
The regex\_sets feature is experimental in regex; marked by \<\-\- HERE in m/\(?\[ \<\-\- HERE \[0\]\+\(\)\+\]\)/ at \-e line 1\.
==46142== Conditional jump or move depends on uninitialised value\(s\)
==46142==    at 0x60E157&#8203;: Perl\_\_invlist\_union\_maybe\_complement\_2nd \(regcomp\.c&#8203;:8602\)
==46142==    by 0x636DC4&#8203;: S\_handle\_regex\_sets \(regcomp\.c&#8203;:13911\)
==46142==    by 0x653F69&#8203;: S\_reg \(regcomp\.c&#8203;:10493\)
==46142==    by 0x63A520&#8203;: S\_regatom \(regcomp\.c&#8203;:11801\)
==46142==    by 0x646DA1&#8203;: S\_regpiece \(regcomp\.c&#8203;:10879\)
==46142==    by 0x646DA1&#8203;: S\_regbranch \(regcomp\.c&#8203;:10804\)
==46142==    by 0x65D915&#8203;: S\_reg\.constprop\.25 \(regcomp\.c&#8203;:10549\)
==46142==    by 0x6819F5&#8203;: Perl\_re\_op\_compile \(regcomp\.c&#8203;:6954\)
==46142==    by 0x4B05C8&#8203;: Perl\_pmruntime \(op\.c&#8203;:5580\)
==46142==    by 0x5BA779&#8203;: Perl\_yyparse \(perly\.y&#8203;:1032\)
==46142==    by 0x4E758C&#8203;: S\_parse\_body \(perl\.c&#8203;:2312\)
==46142==    by 0x4E758C&#8203;: perl\_parse \(perl\.c&#8203;:1634\)
==46142==    by 0x427107&#8203;: main \(perlmain\.c&#8203;:114\)
==46142==
==46142== Conditional jump or move depends on uninitialised value\(s\)
==46142==    at 0x60E314&#8203;: Perl\_\_new\_invlist \(regcomp\.c&#8203;:8192\)
==46142==    by 0x60E314&#8203;: Perl\_\_invlist\_union\_maybe\_complement\_2nd \(regcomp\.c&#8203;:8679\)
==46142==    by 0x636DC4&#8203;: S\_handle\_regex\_sets \(regcomp\.c&#8203;:13911\)
==46142==    by 0x653F69&#8203;: S\_reg \(regcomp\.c&#8203;:10493\)
==46142==    by 0x63A520&#8203;: S\_regatom \(regcomp\.c&#8203;:11801\)
==46142==    by 0x646DA1&#8203;: S\_regpiece \(regcomp\.c&#8203;:10879\)
==46142==    by 0x646DA1&#8203;: S\_regbranch \(regcomp\.c&#8203;:10804\)
==46142==    by 0x65D915&#8203;: S\_reg\.constprop\.25 \(regcomp\.c&#8203;:10549\)
==46142==    by 0x6819F5&#8203;: Perl\_re\_op\_compile \(regcomp\.c&#8203;:6954\)
==46142==    by 0x4B05C8&#8203;: Perl\_pmruntime \(op\.c&#8203;:5580\)
==46142==    by 0x5BA779&#8203;: Perl\_yyparse \(perly\.y&#8203;:1032\)
==46142==    by 0x4E758C&#8203;: S\_parse\_body \(perl\.c&#8203;:2312\)
==46142==    by 0x4E758C&#8203;: perl\_parse \(perl\.c&#8203;:1634\)
==46142==    by 0x427107&#8203;: main \(perlmain\.c&#8203;:114\)
==46142==
==46142== Conditional jump or move depends on uninitialised value\(s\)
==46142==    at 0x60E40F&#8203;: Perl\_\_new\_invlist \(regcomp\.c&#8203;:8201\)
==46142==    by 0x60E40F&#8203;: Perl\_\_invlist\_union\_maybe\_complement\_2nd \(regcomp\.c&#8203;:8679\)
==46142==    by 0x636DC4&#8203;: S\_handle\_regex\_sets \(regcomp\.c&#8203;:13911\)
==46142==    by 0x653F69&#8203;: S\_reg \(regcomp\.c&#8203;:10493\)
==46142==    by 0x63A520&#8203;: S\_regatom \(regcomp\.c&#8203;:11801\)
==46142==    by 0x646DA1&#8203;: S\_regpiece \(regcomp\.c&#8203;:10879\)
==46142==    by 0x646DA1&#8203;: S\_regbranch \(regcomp\.c&#8203;:10804\)
==46142==    by 0x65D915&#8203;: S\_reg\.constprop\.25 \(regcomp\.c&#8203;:10549\)
==46142==    by 0x6819F5&#8203;: Perl\_re\_op\_compile \(regcomp\.c&#8203;:6954\)
==46142==    by 0x4B05C8&#8203;: Perl\_pmruntime \(op\.c&#8203;:5580\)
==46142==    by 0x5BA779&#8203;: Perl\_yyparse \(perly\.y&#8203;:1032\)
==46142==    by 0x4E758C&#8203;: S\_parse\_body \(perl\.c&#8203;:2312\)
==46142==    by 0x4E758C&#8203;: perl\_parse \(perl\.c&#8203;:1634\)
==46142==    by 0x427107&#8203;: main \(perlmain\.c&#8203;:114\)
==46142==
==46142== Conditional jump or move depends on uninitialised value\(s\)
==46142==    at 0x7DD12B&#8203;: Perl\_sv\_grow \(sv\.c&#8203;:1601\)
==46142==    by 0x60E4AA&#8203;: Perl\_\_new\_invlist \(regcomp\.c&#8203;:8201\)
==46142==    by 0x60E4AA&#8203;: Perl\_\_invlist\_union\_maybe\_complement\_2nd \(regcomp\.c&#8203;:8679\)
==46142==    by 0x636DC4&#8203;: S\_handle\_regex\_sets \(regcomp\.c&#8203;:13911\)
==46142==    by 0x653F69&#8203;: S\_reg \(regcomp\.c&#8203;:10493\)
==46142==    by 0x63A520&#8203;: S\_regatom \(regcomp\.c&#8203;:11801\)
==46142==    by 0x646DA1&#8203;: S\_regpiece \(regcomp\.c&#8203;:10879\)
==46142==    by 0x646DA1&#8203;: S\_regbranch \(regcomp\.c&#8203;:10804\)
==46142==    by 0x65D915&#8203;: S\_reg\.constprop\.25 \(regcomp\.c&#8203;:10549\)
==46142==    by 0x6819F5&#8203;: Perl\_re\_op\_compile \(regcomp\.c&#8203;:6954\)
==46142==    by 0x4B05C8&#8203;: Perl\_pmruntime \(op\.c&#8203;:5580\)
==46142==    by 0x5BA779&#8203;: Perl\_yyparse \(perly\.y&#8203;:1032\)
==46142==    by 0x4E758C&#8203;: S\_parse\_body \(perl\.c&#8203;:2312\)
==46142==    by 0x4E758C&#8203;: perl\_parse \(perl\.c&#8203;:1634\)
==46142==    by 0x427107&#8203;: main \(perlmain\.c&#8203;:114\)
==46142==
==46142== Conditional jump or move depends on uninitialised value\(s\)
==46142==    at 0x7DD584&#8203;: Perl\_sv\_grow \(sv\.c&#8203;:1601\)
==46142==    by 0x60E4AA&#8203;: Perl\_\_new\_invlist \(regcomp\.c&#8203;:8201\)
==46142==    by 0x60E4AA&#8203;: Perl\_\_invlist\_union\_maybe\_complement\_2nd \(regcomp\.c&#8203;:8679\)
==46142==    by 0x636DC4&#8203;: S\_handle\_regex\_sets \(regcomp\.c&#8203;:13911\)
==46142==    by 0x653F69&#8203;: S\_reg \(regcomp\.c&#8203;:10493\)
==46142==    by 0x63A520&#8203;: S\_regatom \(regcomp\.c&#8203;:11801\)
==46142==    by 0x646DA1&#8203;: S\_regpiece \(regcomp\.c&#8203;:10879\)
==46142==    by 0x646DA1&#8203;: S\_regbranch \(regcomp\.c&#8203;:10804\)
==46142==    by 0x65D915&#8203;: S\_reg\.constprop\.25 \(regcomp\.c&#8203;:10549\)
==46142==    by 0x6819F5&#8203;: Perl\_re\_op\_compile \(regcomp\.c&#8203;:6954\)
==46142==    by 0x4B05C8&#8203;: Perl\_pmruntime \(op\.c&#8203;:5580\)
==46142==    by 0x5BA779&#8203;: Perl\_yyparse \(perly\.y&#8203;:1032\)
==46142==    by 0x4E758C&#8203;: S\_parse\_body \(perl\.c&#8203;:2312\)
==46142==    by 0x4E758C&#8203;: perl\_parse \(perl\.c&#8203;:1634\)
==46142==    by 0x427107&#8203;: main \(perlmain\.c&#8203;:114\)
==46142==
==46142== Conditional jump or move depends on uninitialised value\(s\)
==46142==    at 0x7DD1A7&#8203;: Perl\_sv\_grow \(sv\.c&#8203;:1609\)
==46142==    by 0x60E4AA&#8203;: Perl\_\_new\_invlist \(regcomp\.c&#8203;:8201\)
==46142==    by 0x60E4AA&#8203;: Perl\_\_invlist\_union\_maybe\_complement\_2nd \(regcomp\.c&#8203;:8679\)
==46142==    by 0x636DC4&#8203;: S\_handle\_regex\_sets \(regcomp\.c&#8203;:13911\)
==46142==    by 0x653F69&#8203;: S\_reg \(regcomp\.c&#8203;:10493\)
==46142==    by 0x63A520&#8203;: S\_regatom \(regcomp\.c&#8203;:11801\)
==46142==    by 0x646DA1&#8203;: S\_regpiece \(regcomp\.c&#8203;:10879\)
==46142==    by 0x646DA1&#8203;: S\_regbranch \(regcomp\.c&#8203;:10804\)
==46142==    by 0x65D915&#8203;: S\_reg\.constprop\.25 \(regcomp\.c&#8203;:10549\)
==46142==    by 0x6819F5&#8203;: Perl\_re\_op\_compile \(regcomp\.c&#8203;:6954\)
==46142==    by 0x4B05C8&#8203;: Perl\_pmruntime \(op\.c&#8203;:5580\)
==46142==    by 0x5BA779&#8203;: Perl\_yyparse \(perly\.y&#8203;:1032\)
==46142==    by 0x4E758C&#8203;: S\_parse\_body \(perl\.c&#8203;:2312\)
==46142==    by 0x4E758C&#8203;: perl\_parse \(perl\.c&#8203;:1634\)
==46142==    by 0x427107&#8203;: main \(perlmain\.c&#8203;:114\)
==46142==
==46142== Conditional jump or move depends on uninitialised value\(s\)
==46142==    at 0x7DD1FB&#8203;: Perl\_sv\_grow \(sv\.c&#8203;:1612\)
==46142==    by 0x60E4AA&#8203;: Perl\_\_new\_invlist \(regcomp\.c&#8203;:8201\)
==46142==    by 0x60E4AA&#8203;: Perl\_\_invlist\_union\_maybe\_complement\_2nd \(regcomp\.c&#8203;:8679\)
==46142==    by 0x636DC4&#8203;: S\_handle\_regex\_sets \(regcomp\.c&#8203;:13911\)
==46142==    by 0x653F69&#8203;: S\_reg \(regcomp\.c&#8203;:10493\)
==46142==    by 0x63A520&#8203;: S\_regatom \(regcomp\.c&#8203;:11801\)
==46142==    by 0x646DA1&#8203;: S\_regpiece \(regcomp\.c&#8203;:10879\)
==46142==    by 0x646DA1&#8203;: S\_regbranch \(regcomp\.c&#8203;:10804\)
==46142==    by 0x65D915&#8203;: S\_reg\.constprop\.25 \(regcomp\.c&#8203;:10549\)
==46142==    by 0x6819F5&#8203;: Perl\_re\_op\_compile \(regcomp\.c&#8203;:6954\)
==46142==    by 0x4B05C8&#8203;: Perl\_pmruntime \(op\.c&#8203;:5580\)
==46142==    by 0x5BA779&#8203;: Perl\_yyparse \(perly\.y&#8203;:1032\)
==46142==    by 0x4E758C&#8203;: S\_parse\_body \(perl\.c&#8203;:2312\)
==46142==    by 0x4E758C&#8203;: perl\_parse \(perl\.c&#8203;:1634\)
==46142==    by 0x427107&#8203;: main \(perlmain\.c&#8203;:114\)
==46142==
==46142== Conditional jump or move depends on uninitialised value\(s\)
==46142==    at 0x4C27BA5&#8203;: malloc \(vg\_replace\_malloc\.c&#8203;:299\)
==46142==    by 0x6B98EC&#8203;: Perl\_safesysmalloc \(util\.c&#8203;:153\)
==46142==    by 0x7DD5D7&#8203;: Perl\_sv\_grow \(sv\.c&#8203;:1628\)
==46142==    by 0x60E4AA&#8203;: Perl\_\_new\_invlist \(regcomp\.c&#8203;:8201\)
==46142==    by 0x60E4AA&#8203;: Perl\_\_invlist\_union\_maybe\_complement\_2nd \(regcomp\.c&#8203;:8679\)
==46142==    by 0x636DC4&#8203;: S\_handle\_regex\_sets \(regcomp\.c&#8203;:13911\)
==46142==    by 0x653F69&#8203;: S\_reg \(regcomp\.c&#8203;:10493\)
==46142==    by 0x63A520&#8203;: S\_regatom \(regcomp\.c&#8203;:11801\)
==46142==    by 0x646DA1&#8203;: S\_regpiece \(regcomp\.c&#8203;:10879\)
==46142==    by 0x646DA1&#8203;: S\_regbranch \(regcomp\.c&#8203;:10804\)
==46142==    by 0x65D915&#8203;: S\_reg\.constprop\.25 \(regcomp\.c&#8203;:10549\)
==46142==    by 0x6819F5&#8203;: Perl\_re\_op\_compile \(regcomp\.c&#8203;:6954\)
==46142==    by 0x4B05C8&#8203;: Perl\_pmruntime \(op\.c&#8203;:5580\)
==46142==    by 0x5BA779&#8203;: Perl\_yyparse \(perly\.y&#8203;:1032\)
==46142==
==46142== Use of uninitialised value of size 8
==46142==    at 0x60E521&#8203;: Perl\_\_invlist\_union\_maybe\_complement\_2nd \(regcomp\.c&#8203;:8682\)
==46142==    by 0x636DC4&#8203;: S\_handle\_regex\_sets \(regcomp\.c&#8203;:13911\)
==46142==    by 0x653F69&#8203;: S\_reg \(regcomp\.c&#8203;:10493\)
==46142==    by 0x63A520&#8203;: S\_regatom \(regcomp\.c&#8203;:11801\)
==46142==    by 0x646DA1&#8203;: S\_regpiece \(regcomp\.c&#8203;:10879\)
==46142==    by 0x646DA1&#8203;: S\_regbranch \(regcomp\.c&#8203;:10804\)
==46142==    by 0x65D915&#8203;: S\_reg\.constprop\.25 \(regcomp\.c&#8203;:10549\)
==46142==    by 0x6819F5&#8203;: Perl\_re\_op\_compile \(regcomp\.c&#8203;:6954\)
==46142==    by 0x4B05C8&#8203;: Perl\_pmruntime \(op\.c&#8203;:5580\)
==46142==    by 0x5BA779&#8203;: Perl\_yyparse \(perly\.y&#8203;:1032\)
==46142==    by 0x4E758C&#8203;: S\_parse\_body \(perl\.c&#8203;:2312\)
==46142==    by 0x4E758C&#8203;: perl\_parse \(perl\.c&#8203;:1634\)
==46142==    by 0x427107&#8203;: main \(perlmain\.c&#8203;:114\)
==46142==
==46142== Invalid read of size 8
==46142==    at 0x60E521&#8203;: Perl\_\_invlist\_union\_maybe\_complement\_2nd \(regcomp\.c&#8203;:8682\)
==46142==    by 0x636DC4&#8203;: S\_handle\_regex\_sets \(regcomp\.c&#8203;:13911\)
==46142==    by 0x653F69&#8203;: S\_reg \(regcomp\.c&#8203;:10493\)
==46142==    by 0x63A520&#8203;: S\_regatom \(regcomp\.c&#8203;:11801\)
==46142==    by 0x646DA1&#8203;: S\_regpiece \(regcomp\.c&#8203;:10879\)
==46142==    by 0x646DA1&#8203;: S\_regbranch \(regcomp\.c&#8203;:10804\)
==46142==    by 0x65D915&#8203;: S\_reg\.constprop\.25 \(regcomp\.c&#8203;:10549\)
==46142==    by 0x6819F5&#8203;: Perl\_re\_op\_compile \(regcomp\.c&#8203;:6954\)
==46142==    by 0x4B05C8&#8203;: Perl\_pmruntime \(op\.c&#8203;:5580\)
==46142==    by 0x5BA779&#8203;: Perl\_yyparse \(perly\.y&#8203;:1032\)
==46142==    by 0x4E758C&#8203;: S\_parse\_body \(perl\.c&#8203;:2312\)
==46142==    by 0x4E758C&#8203;: perl\_parse \(perl\.c&#8203;:1634\)
==46142==    by 0x427107&#8203;: main \(perlmain\.c&#8203;:114\)
==46142==  Address 0x2b is not stack'd\, malloc'd or \(recently\) free'd
==46142==
==46142==
==46142== Process terminating with default action of signal 11 \(SIGSEGV\)
==46142==  Access not within mapped region at address 0x2B
==46142==    at 0x60E521&#8203;: Perl\_\_invlist\_union\_maybe\_complement\_2nd \(regcomp\.c&#8203;:8682\)
==46142==    by 0x636DC4&#8203;: S\_handle\_regex\_sets \(regcomp\.c&#8203;:13911\)
==46142==    by 0x653F69&#8203;: S\_reg \(regcomp\.c&#8203;:10493\)
==46142==    by 0x63A520&#8203;: S\_regatom \(regcomp\.c&#8203;:11801\)
==46142==    by 0x646DA1&#8203;: S\_regpiece \(regcomp\.c&#8203;:10879\)
==46142==    by 0x646DA1&#8203;: S\_regbranch \(regcomp\.c&#8203;:10804\)
==46142==    by 0x65D915&#8203;: S\_reg\.constprop\.25 \(regcomp\.c&#8203;:10549\)
==46142==    by 0x6819F5&#8203;: Perl\_re\_op\_compile \(regcomp\.c&#8203;:6954\)
==46142==    by 0x4B05C8&#8203;: Perl\_pmruntime \(op\.c&#8203;:5580\)
==46142==    by 0x5BA779&#8203;: Perl\_yyparse \(perly\.y&#8203;:1032\)
==46142==    by 0x4E758C&#8203;: S\_parse\_body \(perl\.c&#8203;:2312\)
==46142==    by 0x4E758C&#8203;: perl\_parse \(perl\.c&#8203;:1634\)
==46142==    by 0x427107&#8203;: main \(perlmain\.c&#8203;:114\)
==46142==  If you believe this happened as a result of a stack
==46142==  overflow in your program's main thread \(unlikely but
==46142==  possible\)\, you can try to increase the size of the
==46142==  main thread stack using the \-\-main\-stacksize= flag\.
==46142==  The main thread stack size used in this run was 8388608\.
==46142==
==46142== HEAP SUMMARY&#8203;:
==46142==     in use at exit&#8203;: 100\,183\,339 bytes in 555 blocks
==46142==   total heap usage&#8203;: 646 allocs\, 91 frees\, 100\,191\,816 bytes allocated
==46142==
==46142== LEAK SUMMARY&#8203;:
==46142==    definitely lost&#8203;: 168 bytes in 1 blocks
==46142==    indirectly lost&#8203;: 1\,948 bytes in 19 blocks
==46142==      possibly lost&#8203;: 24 bytes in 1 blocks
==46142==    still reachable&#8203;: 100\,181\,199 bytes in 534 blocks
==46142==         suppressed&#8203;: 0 bytes in 0 blocks
==46142== Rerun with \-\-leak\-check=full to see details of leaked memory
==46142==
==46142== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==46142== Use \-\-track\-origins=yes to see where uninitialised values come from
==46142== ERROR SUMMARY&#8203;: 10 errors from 10 contexts \(suppressed&#8203;: 0 from 0\)
Segmentation fault


\*\*PERL \-V\*\*

Summary of my perl5 \(revision 5 version 23 subversion 5\) configuration&#8203;:
&nbsp;  Commit id&#8203;: fdfd5e4d926a555f6d4f156d79198d8c6db9dc44
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt11\-1\+deb8u4 \(2015\-09\-19\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='5\.2\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/x86\_64\-unknown\-linux\-gnu/5\.2\.0/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Nov 10 2015 21&#8203;:44&#8203;:35
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.5/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.5
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.5/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.5
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thanks for finding this\, now fixed by 2985caa9ee0029932680fc8f354a35492d18fe9a

This and similar bugs you've found are due to my adding asserts to code where my limited imagination did not think the situation could come up\, but wanted to be sure of that\, and not to blindly forge ahead getting a wrong answer\.  You have found a bunch where it was a syntax error that I my imagination didn't realize\, and one \(I think it was only one\) where it was legitimate syntax that I overlooked\.  Now there are just a couple of these asserts left\.
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
@mauke - Status changed from 'pending release' to 'resolved'
