### ISSUE TITLE
"local *Package::" leads to segfaults and bizarre errors

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15059]
Migrated from [rt.perl.org#126709](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126709) (status was 'open')

Searchable as RT126709$

**Comment by p5pRT** [comment]
### From amon@cpan.org

\#\!/usr/bin/env perl
use strict;
use warnings;

BEGIN \{
&nbsp;    package Callback;
&nbsp;    sub new \{ my \($class\, $code\) = @&#8203;\_; return bless $code => $class \}
\}

sub compile \{
&nbsp;    my \($source\) = @&#8203;\_;
&nbsp;    my $namespace = 'TheNamespace';

&nbsp;    no strict 'refs';
&nbsp;    local \*\{ $namespace \. '&#8203;::' \};

&nbsp;    my $compiled = eval "package $namespace; sub \{ $source; return \}";
&nbsp;    die $@&#8203; if $@&#8203;;

&nbsp;    return Callback\->new\($compiled\);
\}

compile\('my $c = q\(NoSuchClass\); $c\->new'\)\->\(\);

\_\_END\_\_

The above program will segfault or produce bizarre errors\.

Usually\, the script dies with&#8203;:

> Attempt to access disallowed key 'NoSuchClass' in a restricted hash at \(eval 1\) line 1\.

Clearly\, that is wrong\.

But with some probability \(estimated 5% to 100%\) we get a segfault instead\, which is even worse\. This case can be forced by setting the environment variable "PERL\_HASH\_SEED=8"\. I can reproduce this behaviour on a variety of perls&#8203;:

 \- v5\.18\.2 built for i686\-linux\-gnu\-thread\-multi\-64int \(Ubuntu 14\.04 system perl\)
 \- v5\.18\.2 built for i686\-linux\-thread\-multi\-64int \(perlbrewed\)
 \- v5\.20\.1 built for i686\-linux\-thread\-multi\-64int \(perlbrewed\)

 \- v5\.20\.2 built for x86\_64\-linux\-gnu\-thread\-multi \(Ubuntu 15\.10 system perl\)
 \- v5\.22\.0 built for x86\_64\-linux \(perlbrewed\)
 \- v5\.23\.6 \(v5\.23\.5\-20\-g96b6870\) built for x86\_64\-linux \(perlbrewed\)

I cannot reproduce on v5\.10\.1 built for i686\-linux\-thread\-multi\-64int \(perlbrewed\)\.

That v5\.23\.6 perl was a debug build\. Running under GDB yielded the following stack trace&#8203;:

&nbsp;    \(gdb\) run testcase
&nbsp;    Starting program&#8203;: /home/atkinson\-lukas/perl5/perlbrew/perls/perl\-blead/bin/perl testcase
&nbsp;    \[Thread debugging using libthread\_db enabled\]
&nbsp;    Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.

&nbsp;    Program received signal SIGSEGV\, Segmentation fault\.
&nbsp;    0x00000000004a6040 in Perl\_hv\_common \(hv=0x7d6cd8\, keysv=keysv@&#8203;entry=0x0\, key=key@&#8203;entry=0x7f0340 "NoSuchClass"\, klen=11\, flags=0\, action=\<optimized out>\, val=0x0\, hash=2292890956\) at hv\.c&#8203;:671
&nbsp;    671             if \(HeHASH\(entry\) \!= hash\)              /\* strings can't be equal \*/
&nbsp;    \(gdb\) backtrace
&nbsp;    \#0  0x00000000004a6040 in Perl\_hv\_common \(hv=0x7d6cd8\, keysv=keysv@&#8203;entry=0x0\, key=key@&#8203;entry=0x7f0340 "NoSuchClass"\, klen=11\, flags=0\,  action=\<optimized out>\, val=0x0\, hash=2292890956\) at hv\.c&#8203;:671
&nbsp;    \#1  0x00000000004a74b4 in Perl\_hv\_common\_key\_len \(hv=hv@&#8203;entry=0x7d6cd8\, key=key@&#8203;entry=0x7f0340 "NoSuchClass"\, klen\_i32=klen\_i32@&#8203;entry=11\, action=\<optimized out>\, val=val@&#8203;entry=0x0\, hash=hash@&#8203;entry=0\) at hv\.c&#8203;:333
&nbsp;    \#2  0x000000000044572a in Perl\_gv\_fetchpvn\_flags \(nambeg=nambeg@&#8203;entry=0x7f0340 "NoSuchClass"\, full\_len=11\, flags=flags@&#8203;entry=0\, sv\_type=sv\_type@&#8203;entry=SVt\_PVIO\) at gv\.c&#8203;:2273
&nbsp;    \#3  0x00000000004b4088 in S\_opmethod\_stash \(meth=0x7ed8f8\) at pp\_hot\.c&#8203;:3770
&nbsp;    \#4  Perl\_pp\_method\_named \(\) at pp\_hot\.c&#8203;:3847
&nbsp;    \#5  0x00000000004aa9f3 in Perl\_runops\_standard \(\) at run\.c&#8203;:41
&nbsp;    \#6  0x0000000000441ec6 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2464
&nbsp;    \#7  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2387
&nbsp;    \#8  0x000000000041fd55 in main \(argc=2\, argv=0x7fffffffdc18\, env=0x7fffffffdc30\) at perlmain\.c&#8203;:116

If certain details of the script are changed\, it behaves as expected and dies with this message&#8203;:

> Can't locate object method "new" via package "NoSuchClass" \(perhaps you forgot to load "NoSuchClass"?\) at \(eval 1\) line 1\.

Why did I write such code in the first place? I was trying to produce code refs by eval'ing their source in individual packages\, and making sure the package is cleaned up after the code ref's refcount drops to zero\, as to avoid memory leaks\. Hence the \`local \*TheNamespace&#8203;::\` which would restore the previous \(empty\) package after the code ref has been compiled\. The code did previously work without problems\, but I didn't track the execution environment closely enough to pinpoint the breaking change\.

Subtle modifications to the script will produce the expected behaviour \(unknown method new\) rather than the restricted hash error or the segfault&#8203;:

 \- returning a bare code ref rather than a blessed object from \`compile\(\)\`\.
 \- not localizing the package stash
 \- loading or not loading additional packages
 \- referencing GVs inside the sub being compiled \(e\.g\. compiling \`our $foo; sub \{ $foo; NoSuchClass\->new \}\`\)

The attached perlbug information refers to the v5\.23\.6 build\, though other data can be posted on request\.



---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=low


---
Site configuration information for perl 5\.23\.6&#8203;:

Configured by atkinson\-lukas at Sun Nov 22 22&#8203;:02&#8203;:40 CET 2015\.

Summary of my perl5 \(revision 5 version 23 subversion 6\) configuration&#8203;:
&nbsp;  Snapshot of&#8203;: 96b68701e4c05574c9bcf792d65d088aa17da2a0
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=4\.2\.0\-18\-generic\, archname=x86\_64\-linux
&nbsp;    uname='linux mccd 4\.2\.0\-18\-generic \#22\-ubuntu smp fri nov 6 18&#8203;:25&#8203;:50 utc 2015 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;    config\_args='\-de \-Dprefix=/home/atkinson\-lukas/perl5/perlbrew/perls/perl\-blead \-Doptimize=\-O2 \-g \-Duse64bitall \-Dusedevel \-Aeval&#8203;:scriptdir=/home/atkinson\-lukas/perl5/perlbrew/perls/perl\-blead/bin'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2 \-g'\,
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='5\.2\.1 20151010'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/5/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.21\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.21'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-g \-L/usr/local/lib \-fstack\-protector\-strong'

Locally applied patches&#8203;:
&nbsp;    Devel&#8203;::PatchPerl 1\.38



---
@&#8203;INC for perl 5\.23\.6&#8203;:
&nbsp;    /home/atkinson\-lukas/perl5/perlbrew/perls/perl\-blead/lib/site\_perl/5\.23\.6/x86\_64\-linux
&nbsp;    /home/atkinson\-lukas/perl5/perlbrew/perls/perl\-blead/lib/site\_perl/5\.23\.6
&nbsp;    /home/atkinson\-lukas/perl5/perlbrew/perls/perl\-blead/lib/5\.23\.6/x86\_64\-linux
&nbsp;    /home/atkinson\-lukas/perl5/perlbrew/perls/perl\-blead/lib/5\.23\.6
&nbsp;    \.



---
Environment for perl 5\.23\.6&#8203;:
&nbsp;    HOME=/home/atkinson\-lukas
&nbsp;    LANG=de\_DE\.UTF\-8
&nbsp;    LANGUAGE=
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/atkinson\-lukas/perl5/perlbrew/bin&#8203;:/home/atkinson\-lukas/perl5/perlbrew/perls/perl\-blead/bin&#8203;:/usr/local/sbin&#8203;:/usr/local/bin&#8203;:/usr/sbin&#8203;:/usr/bin&#8203;:/sbin&#8203;:/bin&#8203;:/usr/games&#8203;:/usr/local/games&#8203;:/home/atkinson\-lukas/\.cabal/bin
&nbsp;    PERLBREW\_BASHRC\_VERSION=0\.73
&nbsp;    PERLBREW\_HOME=/home/atkinson\-lukas/\.perlbrew
&nbsp;    PERLBREW\_MANPATH=/home/atkinson\-lukas/perl5/perlbrew/perls/perl\-blead/man
&nbsp;    PERLBREW\_PATH=/home/atkinson\-lukas/perl5/perlbrew/bin&#8203;:/home/atkinson\-lukas/perl5/perlbrew/perls/perl\-blead/bin
&nbsp;    PERLBREW\_PERL=perl\-blead
&nbsp;    PERLBREW\_ROOT=/home/atkinson\-lukas/perl5/perlbrew
&nbsp;    PERLBREW\_VERSION=0\.73
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Nov 22\, 2015 at 02&#8203;:40&#8203;:52PM \-0800\, Lukas Atkinson wrote&#8203;:
> The above program will segfault or produce bizarre errors\.

It can be reduced to the following&#8203;:

&nbsp;    sub BAR&#8203;::new \{  \}

&nbsp;    my $cb;
&nbsp;    \{
&nbsp;        local \*\{FOO&#8203;::\};

&nbsp;        $cb = eval q\{
&nbsp;            package FOO;
&nbsp;            sub FOO&#8203;::foo \{ 'NoSuchClass'\->foo; \};
&nbsp;            \\&FOO&#8203;::foo;
&nbsp;        \};
&nbsp;        die $@&#8203; if $@&#8203;;

&nbsp;        bless $cb\, 'BAR';
&nbsp;        study;
&nbsp;    \}
&nbsp;    $cb\->\(\);

which on a debugging blead seems to consistently trigger this assert&#8203;:

&nbsp;    perl&#8203;: hv\.c&#8203;:355&#8203;: Perl\_hv\_common&#8203;: Assertion \`\(\(svtype\)\(\(hv\)\->sv\_flags & 0xff\)\) == SVt\_PVHV' failed\.

This is because the method call 'NoSuchClass'\->foo tries to find the
current stash while determining the class to use\.

I'm not sure whether that represents a bug \- i\.e\. I'm not sure whether
it should need to know the current stash to resolve that class method
call; but in any case\, it ends up looking at the current cop to find the
current package\, and since that cop was compiled in a stash that's
subsequently been freed by the scope exit\, the 'stash' is an SV that's
since been reallocated and happens to no longer be an HV \(hence the
assertion failure\)\.

I'm not sure what to do about this\. Arguably \*every\* COP's CopSTASH\(\)
pointer is a weak ref to the stash\, and so the stash should have a backref
magic entry for every COP that references it\. This seems a bit expensive
though\.

\-\- 
Dave's first rule of Opera&#8203;:
If something needs saying\, say it&#8203;: don't warble it\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'
