### ISSUE TITLE
Assert fail w/o other symptoms - regcomp.c:13901 S_concat_pat

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15051]
Migrated from [rt.perl.org#126667](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126667) (status was 'open')

Searchable as RT126667$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers an assert fail with no other symptoms\. The testcase is the file&#8203;:

qr/\(?\{\}\)@&#8203;0\{\(\)\}@&#8203;0/

dcollins@&#8203;nightshade64&#8203;:\~$ perl/perl \-e 'qr/\(?\{\}\)@&#8203;0\{\(\)\}@&#8203;0/'
dcollins@&#8203;nightshade64&#8203;:\~$ perldebug/perl \-e 'qr/\(?\{\}\)@&#8203;0\{\(\)\}@&#8203;0/'
perl&#8203;: regcomp\.c&#8203;:5958&#8203;: S\_concat\_pat&#8203;: Assertion \`oplist\->op\_type == OP\_PADAV || oplist\->op\_type == OP\_RV2AV' failed\.
Aborted

\*\*GDB\*\*

\(gdb\) run
Starting program&#8203;: /home/dcollins/perldebug/perl \-e qr/\\\(\\?\\\{\\\}\\\)@&#8203;0\\\{\\\(\\\)\\\}@&#8203;0/
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
perl&#8203;: regcomp\.c&#8203;:5958&#8203;: S\_concat\_pat&#8203;: Assertion \`oplist\->op\_type == OP\_PADAV || oplist\->op\_type == OP\_RV2AV' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6cf4107 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6cf4107 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x00007ffff6cf54e8 in abort \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#2  0x00007ffff6ced226 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#3  0x00007ffff6ced2d2 in \_\_assert\_fail \(\)
&nbsp;   from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#4  0x000000000069aec9 in S\_concat\_pat \(
&nbsp;    pRExC\_state=pRExC\_state@&#8203;entry=0x7fffffffe020\, pat=0x11d81c8\,
&nbsp;    pat@&#8203;entry=0x0\, patternp=patternp@&#8203;entry=0x11c6a28\,
&nbsp;    pat\_count=pat\_count@&#8203;entry=2\, oplist=0x11e24c8\, oplist@&#8203;entry=0x11c9658\,
&nbsp;    recompile\_p=recompile\_p@&#8203;entry=0x7fffffffdeeb\, delim=0x0\) at regcomp\.c&#8203;:5957
\#5  0x000000000077b4f1 in Perl\_re\_op\_compile \(patternp=\<optimized out>\,
&nbsp;    pat\_count=2\, expr=0x11c9658\, eng=0xf16600 \<PL\_core\_reg\_engine>\,
&nbsp;    old\_re=0x0\, is\_bare\_re=0x7fffffffe3b7\, orig\_rx\_flags=0\,
&nbsp;    pm\_flags=1879048192\) at regcomp\.c&#8203;:6572
\#6  0x0000000000b22e04 in Perl\_pp\_regcomp \(\) at pp\_ctl\.c&#8203;:119
\#7  0x00000000007c909f in Perl\_runops\_debug \(\) at dump\.c&#8203;:2224
\#8  0x0000000000532411 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2464
\#9  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2387
\#10 0x0000000000428928 in main \(argc=3\, argv=0x7fffffffe658\,
&nbsp;    env=0x7fffffffe678\) at perlmain\.c&#8203;:116
\(gdb\) f 4
\#4  0x000000000069aec9 in S\_concat\_pat \(
&nbsp;    pRExC\_state=pRExC\_state@&#8203;entry=0x7fffffffe020\, pat=0x11d81c8\,
&nbsp;    pat@&#8203;entry=0x0\, patternp=patternp@&#8203;entry=0x11c6a28\,
&nbsp;    pat\_count=pat\_count@&#8203;entry=2\, oplist=0x11e24c8\, oplist@&#8203;entry=0x11c9658\,
&nbsp;    recompile\_p=recompile\_p@&#8203;entry=0x7fffffffdeeb\, delim=0x0\) at regcomp\.c&#8203;:5957
5957                    assert\(oplist\->op\_type == OP\_PADAV
\(gdb\) info locals
maxarg = 0
array = \<optimized out>
rx = 0x0
sv = \<optimized out>
orig\_patlen = 0
code = false
msv = \<optimized out>
svp = \<optimized out>
n = 1
use\_delim = \<optimized out>
alloced = \<optimized out>
\_\_PRETTY\_FUNCTION\_\_ = "S\_concat\_pat"
\(gdb\) q


\*\*PERL \-V\*\*

Summary of my perl5 \(revision 5 version 23 subversion 5\) configuration&#8203;:
&nbsp;  Commit id&#8203;: fb034ed92b97457964b9c5566ffde039c0f0721e
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt11\-1\+deb8u4 \(2015\-09\-19\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DDEBUG\_LEAKING\_SCALARS \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='5\.2\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/x86\_64\-unknown\-linux\-gnu/5\.2\.0/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Nov 17 2015 16&#8203;:24&#8203;:08
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.5/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.5
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.5/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.5
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.4
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @demerphq

On 18 November 2015 at 00&#8203;:38\, Dan Collins \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> \# New Ticket Created by  Dan Collins
> \# Please include the string&#8203;:  \[perl \#126667\]
> \# in the subject line of all future correspondence about this issue\.
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126667 >
>
>
> Greetings Porters\,
>
> I have compiled bleadperl with the afl\-gcc compiler using&#8203;:
>
> \./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des
> AFL\_HARDEN=1 make && make test
>
> And then fuzzed the resulting binary using&#8203;:
>
> AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;
>
> After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers an assert fail with no other symptoms\. The testcase is the file&#8203;:
>
> qr/\(?\{\}\)@&#8203;0\{\(\)\}@&#8203;0/
>
> dcollins@&#8203;nightshade64&#8203;:\~$ perl/perl \-e 'qr/\(?\{\}\)@&#8203;0\{\(\)\}@&#8203;0/'
> dcollins@&#8203;nightshade64&#8203;:\~$ perldebug/perl \-e 'qr/\(?\{\}\)@&#8203;0\{\(\)\}@&#8203;0/'
> perl&#8203;: regcomp\.c&#8203;:5958&#8203;: S\_concat\_pat&#8203;: Assertion \`oplist\->op\_type == OP\_PADAV || oplist\->op\_type == OP\_RV2AV' failed\.
> Aborted

Its trying to stringify @&#8203;0

Yves

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'
