### ISSUE TITLE
Perl_cv_const_sv_or_av: Assertion `((svtype)((cv)->sv_flags & 0xff)) == SVt_PVCV || ((svtype)((cv)->sv_flags & 0xff)) == SVt_PVFM' failed (op.c:7766)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15085]
Migrated from [rt.perl.org#126871](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126871) (status was 'rejected')

Searchable as RT126871$

**Comment by p5pRT** [comment]
### From @geeknik

z;$z\{&i\};i causes an assertion failure in Perl\_cv\_const\_sv\_or\_av \(op\.c&#8203;:7766\)\. This bug was found using American Fuzzy Lop\. Perl v5\.23\.6 \(v5\.23\.5\-113\-g406d554\) was compiled as follows&#8203;:

\./Configure \-des \-Dusedevel \-DDEBUGGING \-Dcc=afl\-gcc \-Doptimize=\-O2\\ \-g && AFL\_HARDEN=1 make \-j6

valgrind \-q ~/perl/perl test09
Array found where operator expected at test09 line 1\, at end of line
&nbsp;        \(Missing operator before ?\)
perl&#8203;: op\.c&#8203;:7766&#8203;: Perl\_cv\_const\_sv\_or\_av&#8203;: Assertion \`\(\(svtype\)\(\(cv\)\->sv\_flags & 0xff\)\) == SVt\_PVCV || \(\(svtype\)\(\(cv\)\->sv\_flags & 0xff\)\) == SVt\_PVFM' failed\.
Aborted

Starting program&#8203;: /home/geeknik/perl/perl test09
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
Array found where operator expected at test09 line 1\, at end of line
&nbsp;        \(Missing operator before ?\)
perl&#8203;: op\.c&#8203;:7766&#8203;: Perl\_cv\_const\_sv\_or\_av&#8203;: Assertion \`\(\(svtype\)\(\(cv\)\->sv\_flags & 0xff\)\) == SVt\_PVCV || \(\(svtype\(\(cv\)\->sv\_flags & 0xff\)\) == SVt\_PVFM' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6d90165 in \*\_\_GI\_raise \(sig=\<optimized out>\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:64
64      \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;: No such file or directory\.
\(gdb\) bt
\#0  0x00007ffff6d90165 in \*\_\_GI\_raise \(sig=\<optimized out>\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:64
\#1  0x00007ffff6d933e0 in \*\_\_GI\_abort \(\) at abort\.c&#8203;:92
\#2  0x00007ffff6d89311 in \*\_\_GI\_\_\_assert\_fail \(
&nbsp;    assertion=assertion@&#8203;entry=0xe83af8 "\(\(svtype\)\(\(cv\)\->sv\_flags & 0xff\)\) == SVt\_PVCV || \(\(svtype\)\(\(cv\)\->sv\_fags & 0xff\)\) == SVt\_PVFM"\, file=\<optimized out>\, file@&#8203;entry=0xf50f22 "op\.c"\, line=line@&#8203;entry=7766\,
&nbsp;    function=function@&#8203;entry=0xe95f90 "Perl\_cv\_const\_sv\_or\_av"\) at assert\.c&#8203;:81
\#3  0x0000000000449ae5 in Perl\_cv\_const\_sv\_or\_av \(cv=cv@&#8203;entry=0x11bdbc0\) at op\.c&#8203;:7766
\#4  0x00000000005e3b1c in Perl\_yylex \(\) at toke\.c&#8203;:7056
\#5  0x000000000065aa7d in Perl\_yyparse \(gramtype=gramtype@&#8203;entry=258\) at perly\.c&#8203;:322
\#6  0x000000000052e625 in S\_parse\_body \(env=env@&#8203;entry=0x0\, xsinit=xsinit@&#8203;entry=0x42e190 \<xs\_init>\)
&nbsp;    at perl\.c&#8203;:2312
\#7  0x0000000000534737 in perl\_parse \(my\_perl=\<optimized out>\, xsinit=xsinit@&#8203;entry=0x42e190 \<xs\_init>\,
&nbsp;    argc=\<optimized out>\, argv=\<optimized out>\, env=env@&#8203;entry=0x0\) at perl\.c&#8203;:1634
\#8  0x000000000042dda8 in main \(argc=2\, argv=0x7fffffffe668\, env=0x7fffffffe680\) at perlmain\.c&#8203;:114

**Comment by p5pRT** [comment]
### From @tonycoz

On Thu Dec 10 08&#8203;:44&#8203;:03 2015\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> z;$z\{&i\};i causes an assertion failure in Perl\_cv\_const\_sv\_or\_av
> \(op\.c&#8203;:7766\)\. This bug was found using American Fuzzy Lop\. Perl v5\.23\.6
> \(v5\.23\.5\-113\-g406d554\) was compiled as follows&#8203;:
> 
> \./Configure \-des \-Dusedevel \-DDEBUGGING \-Dcc=afl\-gcc \-Doptimize=\-O2\\
> \-g && AFL\_HARDEN=1 make \-j6
> 
> valgrind \-q ~/perl/perl test09
> Array found where operator expected at test09 line 1\, at end of line
>         \(Missing operator before ?\)
> perl&#8203;: op\.c&#8203;:7766&#8203;: Perl\_cv\_const\_sv\_or\_av&#8203;: Assertion \`\(\(svtype\)\(\(cv\)\-
> >sv\_flags & 0xff\)\) == SVt\_PVCV || \(\(svtype\)\(\(cv\)\->sv\_flags & 0xff\)\) ==
> SVt\_PVFM' failed\.
> Aborted

I haven't managed to reproduce this\.

 $ hd \.\./126871\.pl 
 00000000  7a 3b 24 7a 7b 26 69 7d  3b 69             |z;$z\{&i\};i|
 0000000a

Built blead with and without afl\-gcc 1\.06b\, test runs with and without valgrind\, all builds with \-DDEBUGGING\.

Also tried with 5\.23\.7 and 5\.23\.4 build with \-DDEBUGGING and plain gcc\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @geeknik

On Tue Feb 09 21&#8203;:43&#8203;:44 2016\, tonyc wrote&#8203;:
> 
> I haven't managed to reproduce this\.
> 
> $ hd \.\./126871\.pl
> 00000000  7a 3b 24 7a 7b 26 69 7d  3b 69             |z;$z\{&i\};i|
> 0000000a
> 
> Built blead with and without afl\-gcc 1\.06b\, test runs with and without
> valgrind\, all builds with \-DDEBUGGING\.
> 
> Also tried with 5\.23\.7 and 5\.23\.4 build with \-DDEBUGGING and plain
> gcc\.
> 
> Tony

I am no longer able to reproduce this\.

**Comment by p5pRT** [comment]
### From @tonycoz

On Wed Feb 10 00&#8203;:51&#8203;:25 2016\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> On Tue Feb 09 21&#8203;:43&#8203;:44 2016\, tonyc wrote&#8203;:
> > I haven't managed to reproduce this\.
> 
> I am no longer able to reproduce this\.

Ok\, closing\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'rejected'
