### ISSUE TITLE
Perl_newATTRSUB_x: Assertion `block' failed (op.c:8410)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15081]
Migrated from [rt.perl.org#126845](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126845) (status was 'resolved')

Searchable as RT126845$

**Comment by p5pRT** [comment]
### From @geeknik

sub y\(\);sub y\(\)&#8203;:y\(\) causes an assertion failure in Perl\_newATTRSUB\_x \(op\.c&#8203;:8410\)\. This bug was found using American Fuzzy Lop\. Perl v5\.23\.6 \(v5\.23\.5\-113\-g406d554\) was compiled as follows&#8203;:

\./Configure \-des \-Dusedevel \-DDEBUGGING \-Dcc=afl\-gcc \-Doptimize=\-O2\\ \-g && AFL\_HARDEN=1 make \-j6

valgrind \-q ~/perl/perl test07
perl&#8203;: op\.c&#8203;:8410&#8203;: Perl\_newATTRSUB\_x&#8203;: Assertion \`block' failed\.
Aborted

perl&#8203;: op\.c&#8203;:8410&#8203;: Perl\_newATTRSUB\_x&#8203;: Assertion \`block' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6d90165 in \*\_\_GI\_raise \(sig=\<optimized out>\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:64
64      \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;: No such file or directory\.
\(gdb\) bt
\#0  0x00007ffff6d90165 in \*\_\_GI\_raise \(sig=\<optimized out>\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:64
\#1  0x00007ffff6d933e0 in \*\_\_GI\_abort \(\) at abort\.c&#8203;:92
\#2  0x00007ffff6d89311 in \*\_\_GI\_\_\_assert\_fail \(assertion=assertion@&#8203;entry=0xe812e4 "block"\,
&nbsp;    file=\<optimized out>\, file@&#8203;entry=0xf50f22 "op\.c"\, line=line@&#8203;entry=8410\,
&nbsp;    function=function@&#8203;entry=0xe96010 "Perl\_newATTRSUB\_x"\) at assert\.c&#8203;:81
\#3  0x00000000004d92a5 in Perl\_newATTRSUB\_x \(floor=39\, o=0x11c8b08\, proto=0x11c8ac8\, attrs=0x11c8f28\,
&nbsp;    block=0x0\, o\_is\_gv=o\_is\_gv@&#8203;entry=false\) at op\.c&#8203;:8410
\#4  0x0000000000662984 in Perl\_yyparse \(gramtype=gramtype@&#8203;entry=258\) at perly\.y&#8203;:294
\#5  0x000000000052e625 in S\_parse\_body \(env=env@&#8203;entry=0x0\, xsinit=xsinit@&#8203;entry=0x42e190 \<xs\_init>\)
&nbsp;    at perl\.c&#8203;:2312
\#6  0x0000000000534737 in perl\_parse \(my\_perl=\<optimized out>\, xsinit=xsinit@&#8203;entry=0x42e190 \<xs\_init>\,
&nbsp;    argc=\<optimized out>\, argv=\<optimized out>\, env=env@&#8203;entry=0x0\) at perl\.c&#8203;:1634
\#7  0x000000000042dda8 in main \(argc=2\, argv=0x7fffffffe668\, env=0x7fffffffe680\) at perlmain\.c&#8203;:114

**Comment by p5pRT** [comment]
### From @arc

Thanks for the report\. The failing assertion seems to be incorrect\, so it has been removed as of a934a4a7d4fa99d522e169b921286755a0f8d248\.

\-\- 
Aaron Crane \*\* http&#8203;://aaroncrane\.co\.uk/

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@arc - Status changed from 'open' to 'resolved'
