### ISSUE TITLE
Perl_rpeep: Assertion `oldoldop->op_next == oldop' failed (op.c:13716)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15080]
Migrated from [rt.perl.org#126844](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126844) (status was 'resolved')

Searchable as RT126844$

**Comment by p5pRT** [comment]
### From @geeknik

\{my\($f\,$b\)\,\($0\)\,my\($f\,$b\)\} causes an assertion failure in Perl\_rpeep\. This bug was found using American Fuzzy Lop\. Perl v5\.23\.6 \(v5\.23\.5\-113\-g406d554\) was compiled as follows&#8203;:

\./Configure \-des \-Dusedevel \-DDEBUGGING \-Dcc=afl\-gcc \-Doptimize=\-O2\\ \-g && AFL\_HARDEN=1 make \-j6

valgrind \-q ~/perl/perl test00
perl&#8203;: op\.c&#8203;:13716&#8203;: Perl\_rpeep&#8203;: Assertion \`oldoldop\->op\_next == oldop' failed\.
Aborted

perl&#8203;: op\.c&#8203;:13716&#8203;: Perl\_rpeep&#8203;: Assertion \`oldoldop\->op\_next == oldop' failed\.
Program received signal SIGABRT\, Aborted\.
0x00007ffff6d90165 in \*\_\_GI\_raise \(sig=\<optimized out>\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:64
64      \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;: No such file or directory\.
\(gdb\) bt
\#0  0x00007ffff6d90165 in \*\_\_GI\_raise \(sig=\<optimized out>\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:64
\#1  0x00007ffff6d933e0 in \*\_\_GI\_abort \(\) at abort\.c&#8203;:92
\#2  0x00007ffff6d89311 in \*\_\_GI\_\_\_assert\_fail \(
&nbsp;    assertion=assertion@&#8203;entry=0xe81a79 "oldoldop\->op\_next == oldop"\, file=\<optimized out>\,
&nbsp;    file@&#8203;entry=0xf50f22 "op\.c"\, line=line@&#8203;entry=13716\, function=function@&#8203;entry=0xe965f3 "Perl\_rpeep"\)
&nbsp;    at assert\.c&#8203;:81
\#3  0x00000000004c324d in Perl\_rpeep \(o=0x11c8e80\) at op\.c&#8203;:13716
\#4  0x000000000048b0f6 in Perl\_newPROG \(o=0x11c8c88\) at op\.c&#8203;:4113
\#5  0x000000000065cf18 in Perl\_yyparse \(gramtype=gramtype@&#8203;entry=258\) at perly\.y&#8203;:120
\#6  0x000000000052e625 in S\_parse\_body \(env=env@&#8203;entry=0x0\, xsinit=xsinit@&#8203;entry=0x42e190 \<xs\_init>\)
&nbsp;    at perl\.c&#8203;:2312
\#7  0x0000000000534737 in perl\_parse \(my\_perl=\<optimized out>\, xsinit=xsinit@&#8203;entry=0x42e190 \<xs\_init>\,
&nbsp;    argc=\<optimized out>\, argv=\<optimized out>\, env=env@&#8203;entry=0x0\) at perl\.c&#8203;:1634
\#8  0x000000000042dda8 in main \(argc=2\, argv=0x7fffffffe668\, env=0x7fffffffe680\) at perlmain\.c&#8203;:114

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, Dec 08\, 2015 at 10&#8203;:51&#8203;:15AM \-0800\, Brian Carpenter wrote&#8203;:
> \# New Ticket Created by  Brian Carpenter 
> \# Please include the string&#8203;:  \[perl \#126844\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126844 >
> 
> 
> \{my\($f\,$b\)\,\($0\)\,my\($f\,$b\)\} causes an assertion failure in Perl\_rpeep\.

Fixed by f5885b0; more general fixes in the follow\-up commits in the
branch 4945b30\.

\-\- 
You're only as old as you look\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
