### ISSUE TITLE
Duplicating filehandle changes $! even on success

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15093]
Migrated from [rt.perl.org#126929](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=126929) (status was 'rejected')

Searchable as RT126929$

**Comment by p5pRT** [comment]
### From @exodist

#### Created by @exodist

This is a bug report for perl from exodist7@&#8203;gmail\.com\,
generated with the help of perlbug 1\.40 running under perl 5\.22\.0\.


\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

Example&#8203;:

&nbsp;    $\! = 100;
&nbsp;    print '$\! == ' \. int\($\!\) \. "\\n";
&nbsp;    open\( my $out\, ">&STDOUT" \) or die "Can't dup STDOUT&#8203;:  $\!";
&nbsp;    print '$\! == ' \. int\($\!\) \. "\\n";

Output&#8203;:

&nbsp;    $\! == 100
&nbsp;    $\! == 29

An strace shows extra info&#8203;:

ioctl\(0\, SNDCTL\_TMR\_TIMEBASE or SNDRV\_TIMER\_IOCTL\_NEXT\_DEVICE or TCGETS\,
\{B38400 opost isig icanon echo \.\.\.\}\) = 0
lseek\(0\, 0\, SEEK\_CUR\)                   = \-1 ESPIPE \(Illegal seek\)
ioctl\(1\, SNDCTL\_TMR\_TIMEBASE or SNDRV\_TIMER\_IOCTL\_NEXT\_DEVICE or TCGETS\,
\{B38400 opost isig icanon echo \.\.\.\}\) = 0
lseek\(1\, 0\, SEEK\_CUR\)                   = \-1 ESPIPE \(Illegal seek\)
ioctl\(2\, SNDCTL\_TMR\_TIMEBASE or SNDRV\_TIMER\_IOCTL\_NEXT\_DEVICE or TCGETS\,
\{B38400 opost isig icanon echo \.\.\.\}\) = 0
lseek\(2\, 0\, SEEK\_CUR\)                   = \-1 ESPIPE \(Illegal seek\)
open\("test\.pl"\, O\_RDONLY\)               = 3
ioctl\(3\, SNDCTL\_TMR\_TIMEBASE or SNDRV\_TIMER\_IOCTL\_NEXT\_DEVICE or TCGETS\,
0x7fff7e6652b0\) = \-1 ENOTTY \(Inappropriate ioctl for device\)
lseek\(3\, 0\, SEEK\_CUR\)                   = 0
fcntl\(3\, F\_SETFD\, FD\_CLOEXEC\)           = 0
fstat\(3\, \{st\_mode=S\_IFREG|0664\, st\_size=152\, \.\.\.\}\) = 0

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.22.0:

Configured by exodist at Wed Jul 29 11:56:27 PDT 2015.

Summary of my perl5 (revision 5 version 22 subversion 0) configuration:

  Platform:
    osname=linux, osvers=3.13.0-44-generic,
archname=x86_64-linux-thread-multi
    uname='linux work 3.13.0-44-generic #73-ubuntu smp tue dec 16 00:22:43
utc 2014 x86_64 x86_64 x86_64 gnulinux '
    config_args='-de -Dprefix=/home/exodist/perl5/perlbrew/perls/main
-Dusethreads -Aeval:scriptdir=/home/exodist/perl5/perlbrew/perls/main/bin'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv
-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include
-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe
-fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.8.4', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678,
doublekind=3
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16,
longdblkind=3
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t',
lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed
/usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib/../lib
/usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.19'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -L/usr/local/lib
-fstack-protector'



@INC for perl 5.22.0:
    /home/exodist/.perlbrew/libs/main@exodist
/lib/perl5/x86_64-linux-thread-multi
    /home/exodist/.perlbrew/libs/main@exodist/lib/perl5

/home/exodist/perl5/perlbrew/perls/main/lib/site_perl/5.22.0/x86_64-linux-thread-multi
    /home/exodist/perl5/perlbrew/perls/main/lib/site_perl/5.22.0

/home/exodist/perl5/perlbrew/perls/main/lib/5.22.0/x86_64-linux-thread-multi
    /home/exodist/perl5/perlbrew/perls/main/lib/5.22.0
    .


Environment for perl 5.22.0:
    HOME=/home/exodist
    LANG=en_US.UTF-8
    LANGUAGE=en_US
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/exodist/.perlbrew/libs/main@exodist
/bin:/home/exodist/perl5/perlbrew/bin:/home/exodist/perl5/perlbrew/perls/main/bin:/home/exodist/bin:/home/exodist/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
    PERL5LIB=/home/exodist/.perlbrew/libs/main@exodist/lib/perl5
    PERLBREW_BASHRC_VERSION=0.66
    PERLBREW_HOME=/home/exodist/.perlbrew
    PERLBREW_LIB=exodist
    PERLBREW_MANPATH=/home/exodist/.perlbrew/libs/main@exodist
/man:/home/exodist/perl5/perlbrew/perls/main/man
    PERLBREW_PATH=/home/exodist/.perlbrew/libs/main@exodist
/bin:/home/exodist/perl5/perlbrew/bin:/home/exodist/perl5/perlbrew/perls/main/bin
    PERLBREW_PERL=main
    PERLBREW_ROOT=/home/exodist/perl5/perlbrew
    PERLBREW_VERSION=0.66
    PERL_BADLANG (unset)
    PERL_LOCAL_LIB_ROOT=/home/exodist/.perlbrew/libs/main@exodist
    PERL_MB_OPT=--install_base /home/exodist/.perlbrew/libs/main@exodist
    PERL_MM_OPT=INSTALL_BASE=/home/exodist/.perlbrew/libs/main@exodist
    SHELL=/usr/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Chad Granum wrote&#8203;:
>Subject&#8203;: \[perl \#126929\] Duplicating filehandle changes $\! even on success

Not a bug\.  errno\, and hence $\!\, is allowed to be changed arbitrarily
by many kinds of successful operation\.  It's only meaningful immediately
after a failure\.

\-zefram

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @exodist

On Tue Dec 15 13&#8203;:10&#8203;:40 2015\, zefram@&#8203;fysh\.org wrote&#8203;:
> Chad Granum wrote&#8203;:
> >Subject&#8203;: \[perl \#126929\] Duplicating filehandle changes $\! even on success
> 
> Not a bug\.  errno\, and hence $\!\, is allowed to be changed arbitrarily
> by many kinds of successful operation\.  It's only meaningful immediately
> after a failure\.
> 
> \-zefram
> 

My subject it probably wrong\. The problem isn't that $\! changes\. The problem is why it changes\. Under the hood there is an illegal seek\.

**Comment by p5pRT** [comment]
### From @exodist

just to be clear\, I will not protest if this is closed as not a bug\. I just wanted to point out that there was an illegal seek happening\, apparently harmless though\.

On Tue Dec 15 13&#8203;:19&#8203;:14 2015\, exodist7@&#8203;gmail\.com wrote&#8203;:
> On Tue Dec 15 13&#8203;:10&#8203;:40 2015\, zefram@&#8203;fysh\.org wrote&#8203;:
> > Chad Granum wrote&#8203;:
> > > Subject&#8203;: \[perl \#126929\] Duplicating filehandle changes $\! even on
> > > success
> >
> > Not a bug\.  errno\, and hence $\!\, is allowed to be changed arbitrarily
> > by many kinds of successful operation\.  It's only meaningful
> > immediately
> > after a failure\.
> >
> > \-zefram
> >
> 
> My subject it probably wrong\. The problem isn't that $\! changes\. The
> problem is why it changes\. Under the hood there is an illegal seek\.

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue Dec 15 13&#8203;:22&#8203;:36 2015\, exodist7@&#8203;gmail\.com wrote&#8203;:
> just to be clear\, I will not protest if this is closed as not a bug\. I
> just wanted to point out that there was an illegal seek happening\,
> apparently harmless though\.

PerlIOBuf\_pushed\(\) calls PerlIO\_tell\(\) to get the current position of the stream\, at the lowest level this becomes a call to lseek\(fd\, 0\, SEEK\_CUR\)

\#0  lseek64 \(\) at \.\./sysdeps/unix/syscall\-template\.S&#8203;:81
\#1  0x0000000000705ec9 in PerlIOUnix\_tell \(f=0xa924b0\) at perlio\.c&#8203;:2764
\#2  0x0000000000703e12 in Perl\_PerlIO\_tell \(f=0xa924b0\) at perlio\.c&#8203;:1596
\#3  0x0000000000707626 in PerlIOBuf\_pushed \(f=0xa931b0\, 
&nbsp;    mode=0x7fffffffe2c0 "w"\, arg=0x0\, tab=0x857e80 \<PerlIO\_perlio>\)
&nbsp;    at perlio\.c&#8203;:3808
\#4  0x0000000000702c74 in PerlIO\_push \(f=0xa931b0\, 
&nbsp;    tab=0x857e80 \<PerlIO\_perlio>\, mode=0x7fffffffe2c0 "w"\, arg=0x0\)
&nbsp;    at perlio\.c&#8203;:1152
\#5  0x0000000000704fc3 in PerlIOBase\_dup \(f=0xa931b0\, o=0xa93170\, param=0x0\, 
&nbsp;    flags=2\) at perlio\.c&#8203;:2195
\#6  0x0000000000708736 in PerlIOBuf\_dup \(f=0xa931b0\, o=0xa93170\, param=0x0\, 
&nbsp;    flags=2\) at perlio\.c&#8203;:4290
\#7  0x00000000007011a3 in PerlIO\_fdupopen \(f=0xa93170\, param=0x0\, flags=2\)
&nbsp;    at perlio\.c&#8203;:482
\#8  0x00000000006a9f76 in Perl\_do\_open6 \(gv=0xa85160\, 
&nbsp;    oname=0xaa17b0 ">&STDOUT"\, len=8\, supplied\_fp=0x0\, svp=0xa87b68\, num\_svs=0\)
&nbsp;    at doio\.c&#8203;:450
\#9  0x000000000067a481 in Perl\_pp\_open \(\) at pp\_sys\.c&#8203;:654

Closing as not a bug\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'rejected'

**Comment by p5pRT** [comment]
### From @wolfsage

On Tue\, Dec 15\, 2015 at 7&#8203;:29 PM\, Tony Cook via RT
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> PerlIOBuf\_pushed\(\) calls PerlIO\_tell\(\) to get the current position of the stream\, at the lowest level this becomes a call to lseek\(fd\, 0\, SEEK\_CUR\)
>
> \#0  lseek64 \(\) at \.\./sysdeps/unix/syscall\-template\.S&#8203;:81
> \#1  0x0000000000705ec9 in PerlIOUnix\_tell \(f=0xa924b0\) at perlio\.c&#8203;:2764
> \#2  0x0000000000703e12 in Perl\_PerlIO\_tell \(f=0xa924b0\) at perlio\.c&#8203;:1596
> \#3  0x0000000000707626 in PerlIOBuf\_pushed \(f=0xa931b0\,
>     mode=0x7fffffffe2c0 "w"\, arg=0x0\, tab=0x857e80 \<PerlIO\_perlio>\)
>     at perlio\.c&#8203;:3808
> \#4  0x0000000000702c74 in PerlIO\_push \(f=0xa931b0\,
>     tab=0x857e80 \<PerlIO\_perlio>\, mode=0x7fffffffe2c0 "w"\, arg=0x0\)
>     at perlio\.c&#8203;:1152
> \#5  0x0000000000704fc3 in PerlIOBase\_dup \(f=0xa931b0\, o=0xa93170\, param=0x0\,
>     flags=2\) at perlio\.c&#8203;:2195
> \#6  0x0000000000708736 in PerlIOBuf\_dup \(f=0xa931b0\, o=0xa93170\, param=0x0\,
>     flags=2\) at perlio\.c&#8203;:4290
> \#7  0x00000000007011a3 in PerlIO\_fdupopen \(f=0xa93170\, param=0x0\, flags=2\)
>     at perlio\.c&#8203;:482
> \#8  0x00000000006a9f76 in Perl\_do\_open6 \(gv=0xa85160\,
>     oname=0xaa17b0 ">&STDOUT"\, len=8\, supplied\_fp=0x0\, svp=0xa87b68\, num\_svs=0\)
>     at doio\.c&#8203;:450
> \#9  0x000000000067a481 in Perl\_pp\_open \(\) at pp\_sys\.c&#8203;:654
>
> Closing as not a bug\.

I told Exodist that this may be a bug because we're calling lseek\(\) on
a PIPE\, which on linux at least is illegal\.

Seems silly to be doing that at all when we know it's just going to
fail \- that I think is a 'bug' in the sense that it's wasted cpu
cycles\.

But it seems harmless\, so not fixing it doesn't bother me too much\.

\-\- Matthew Horsfall \(alh\)

**Comment by p5pRT** [comment]
### From @tonycoz

On Wed Dec 16 04&#8203;:57&#8203;:07 2015\, alh wrote&#8203;:
> On Tue\, Dec 15\, 2015 at 7&#8203;:29 PM\, Tony Cook via RT
> \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> > Closing as not a bug\.
> 
> I told Exodist that this may be a bug because we're calling lseek\(\) on
> a PIPE\, which on linux at least is illegal\.
> 
> Seems silly to be doing that at all when we know it's just going to
> fail \- that I think is a 'bug' in the sense that it's wasted cpu
> cycles\.
> 
> But it seems harmless\, so not fixing it doesn't bother me too much\.

We could make an extra fstat\(\) call to check if it's a pipe\, but then
we're doing two system calls on files\, which I'd call a needless cost\.

Tony
