### ISSUE TITLE
Segfault (GPF) in Perl_newSVpv at sv.c:9161

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15142]
Migrated from [rt.perl.org#127349](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=127349) (status was 'rejected')

Searchable as RT127349$

**Comment by p5pRT** [comment]
### From @geeknik

Found while fuzzing Perl v5\.23\.8 \(v5\.23\.7\-12\-g78e3ac8\) with American Fuzzy Lop\. This crash affects Perl 5\.14\.2 and 5\.20\.2 as well\.

perl \-e '\{\}for unpack q\{p\}\,\*0;\{\}'

Program received signal SIGSEGV\, Segmentation fault\.
strlen \(\) at \.\./sysdeps/x86\_64/strlen\.S&#8203;:106
106    \.\./sysdeps/x86\_64/strlen\.S&#8203;: No such file or directory\.
\(gdb\) bt
\#0  strlen \(\) at \.\./sysdeps/x86\_64/strlen\.S&#8203;:106
\#1  0x00000000009da67c in Perl\_newSVpv \(
&nbsp;    s=0x303a3a6e69616d2a \<error&#8203;: Cannot access memory at address 0x303a3a6e69616d2a>\, len=len@&#8203;entry=0\) at sv\.c&#8203;:9161
\#2  0x0000000000e54a28 in S\_unpack\_rec \(symptr=symptr@&#8203;entry=0x7fffffffe030\, 
&nbsp;    s=0x12304e8 ""\, s@&#8203;entry=0x12304e0 "\*main&#8203;::0"\, 
&nbsp;    strbeg=strbeg@&#8203;entry=0x12304e0 "\*main&#8203;::0"\, 
&nbsp;    strend=strend@&#8203;entry=0x12304e8 ""\, new\_s=new\_s@&#8203;entry=0x0\) at pp\_pack\.c&#8203;:1564
\#3  0x0000000000eda29d in Perl\_unpackstring \(pat=pat@&#8203;entry=0x123f380 "p"\, 
&nbsp;    patend=0x123f381 ""\, s=0x12304e0 "\*main&#8203;::0"\, strend=0x12304e8 ""\, 
&nbsp;    flags=flags@&#8203;entry=0\) at pp\_pack\.c&#8203;:835
\#4  0x0000000000edb2df in Perl\_pp\_unpack \(\) at pp\_pack\.c&#8203;:1839
\#5  0x00000000007e901f in Perl\_runops\_debug \(\) at dump\.c&#8203;:2224
\#6  0x0000000000545266 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2466
\#7  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2389
\#8  0x000000000042bf68 in main \(argc=2\, argv=0x7fffffffe378\, 
&nbsp;    env=0x7fffffffe390\) at perlmain\.c&#8203;:116

==55317== Invalid read of size 1
==55317==    at 0x4C2ABC2&#8203;: strlen \(vg\_replace\_strmem\.c&#8203;:454\)
==55317==    by 0x9DA67B&#8203;: Perl\_newSVpv \(sv\.c&#8203;:9161\)
==55317==    by 0xE54A27&#8203;: S\_unpack\_rec \(pp\_pack\.c&#8203;:1564\)
==55317==    by 0xEDA29C&#8203;: Perl\_unpackstring \(pp\_pack\.c&#8203;:835\)
==55317==    by 0xEDB2DE&#8203;: Perl\_pp\_unpack \(pp\_pack\.c&#8203;:1839\)
==55317==    by 0x7E901E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==55317==    by 0x545265&#8203;: S\_run\_body \(perl\.c&#8203;:2466\)
==55317==    by 0x545265&#8203;: perl\_run \(perl\.c&#8203;:2389\)
==55317==    by 0x42BF67&#8203;: main \(perlmain\.c&#8203;:116\)
==55317==  Address 0x303a3a6e69616d2a is not stack'd\, malloc'd or \(recently\) free'd
==55317== 
==55317== 
==55317== Process terminating with default action of signal 11 \(SIGSEGV\)
==55317==  General Protection Fault
==55317==    at 0x4C2ABC2&#8203;: strlen \(vg\_replace\_strmem\.c&#8203;:454\)
==55317==    by 0x9DA67B&#8203;: Perl\_newSVpv \(sv\.c&#8203;:9161\)
==55317==    by 0xE54A27&#8203;: S\_unpack\_rec \(pp\_pack\.c&#8203;:1564\)
==55317==    by 0xEDA29C&#8203;: Perl\_unpackstring \(pp\_pack\.c&#8203;:835\)
==55317==    by 0xEDB2DE&#8203;: Perl\_pp\_unpack \(pp\_pack\.c&#8203;:1839\)
==55317==    by 0x7E901E&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2224\)
==55317==    by 0x545265&#8203;: S\_run\_body \(perl\.c&#8203;:2466\)
==55317==    by 0x545265&#8203;: perl\_run \(perl\.c&#8203;:2389\)
==55317==    by 0x42BF67&#8203;: main \(perlmain\.c&#8203;:116\)
Segmentation fault

**Comment by p5pRT** [comment]
### From @tonycoz

On Fri Jan 22 11&#8203;:21&#8203;:56 2016\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> Found while fuzzing Perl v5\.23\.8 \(v5\.23\.7\-12\-g78e3ac8\) with American
> Fuzzy Lop\. This crash affects Perl 5\.14\.2 and 5\.20\.2 as well\.
> 
> perl \-e '\{\}for unpack q\{p\}\,\*0;\{\}'

The p unpack type uses the supplied value as a pointer\, feeding it some random value is likely to crash\.

Rejecting\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'rejected'
