### ISSUE TITLE
segfault / strange match with recursive subpattern (?0)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15228]
Migrated from [rt.perl.org#127705](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=127705) (status was 'resolved')

Searchable as RT127705$

**Comment by p5pRT** [comment]
### From lorenz@math.tu-berlin.de


This is a bug report for perl from lorenz@&#8203;math\.tu\-berlin\.de\,
generated with the help of perlbug 1\.40 running under perl 5\.23\.9\.

Since the rework related to \#126182\, the recursive pattern below causes perlblead to segfault\. We observed test failures for our software since March 8\. There is also a related \(probably\) invalid match listed further below\.

The pattern is almost the same as on 'perlre'\, except that I replaced \(?\-1\) by \(?0\)\. Changing that to \(?1\) fixes the segfault but should not really make any difference as far as I can see\.

Segfaulting expression&#8203;:

> perl5\.23\.9 \-Dr \-e 'print  "\(\(5maa\-maa\)\(maa\-3maa\)\)" =~ /\(\\\(\(?&#8203;:\[^\(\)\]\+\+|\(?0\)\)\*\+\\\)\)/;

Compiling REx "\(\\\(\(?&#8203;:\[^\(\)\]\+\+|\(?0\)\)\*\+\\\)\)"
rarest char \) at 0
rarest char \( at 0
Final program&#8203;:
&nbsp;   1&#8203;: OPEN1 \(3\)
&nbsp;   3&#8203;:   EXACT \<\(> \(5\)
&nbsp;   5&#8203;:   SUSPEND \(35\)
&nbsp;   7&#8203;:     CURLYX\[0\]\{0\,INFTY\} \(32\)
&nbsp;   9&#8203;:       BRANCH \(26\)
&nbsp;  10&#8203;:         SUSPEND \(31\)
&nbsp;  12&#8203;:           PLUS \(24\)
&nbsp;  13&#8203;:             ANYOF\[^\(\)\]\[0100\-INFINITY\] \(0\)
&nbsp;  24&#8203;:           SUCCEED \(0\)
&nbsp;  25&#8203;:         TAIL \(30\)
&nbsp;  26&#8203;:       BRANCH \(FAIL\)
&nbsp;  27&#8203;:         GOSUB0\[\-26&#8203;:1\] \(31\)
&nbsp;  30&#8203;:       TAIL \(31\)
&nbsp;  31&#8203;:     WHILEM\[2/2\] \(0\)
&nbsp;  32&#8203;:     NOTHING \(33\)
&nbsp;  33&#8203;:     SUCCEED \(0\)
&nbsp;  34&#8203;:   TAIL \(35\)
&nbsp;  35&#8203;:   EXACT \<\)> \(37\)
&nbsp;  37&#8203;: CLOSE1 \(39\)
&nbsp;  39&#8203;: END \(0\)
anchored "\(" at 0 floating "\)" at 1\.\.9223372036854775807 \(checking floating\) minlen 2 
Enabling $\` $& $' support \(0x7\)\.

EXECUTING\.\.\.

Matching REx "\(\\\(\(?&#8203;:\[^\(\)\]\+\+|\(?0\)\)\*\+\\\)\)" against "\(\(5maa\-maa\)\(maa\-3maa\)\)"
Intuit&#8203;: trying to determine minimum start position\.\.\.
&nbsp;  doing 'check' fbm scan\, \[1\.\.22\] gave 10
&nbsp;  Found floating substr "\)" at offset 10 \(rx\_origin now 0\)\.\.\.
&nbsp;  doing 'other' fbm scan\, \[0\.\.10\] gave 0
&nbsp;  Found anchored substr "\(" at offset 0 \(rx\_origin now 0\)\.\.\.
&nbsp;  \(multiline anchor test skipped\)
Intuit&#8203;: Successfully guessed&#8203;: match at offset 0
&nbsp;   0 \<> \<\(\(5maa\-maa>         |   0| 1&#8203;:OPEN1\(3\)
&nbsp;   0 \<> \<\(\(5maa\-maa>         |   0| 3&#8203;:EXACT \<\(>\(5\)
&nbsp;   1 \<\(> \<\(5maa\-maa\)>        |   0| 5&#8203;:SUSPEND\(35\)
&nbsp;   1 \<\(> \<\(5maa\-maa\)>        |   1|  7&#8203;:CURLYX\[0\]\{0\,INFTY\}\(32\)
&nbsp;   1 \<\(> \<\(5maa\-maa\)>        |   2|   31&#8203;:WHILEM\[2/2\]\(0\)
&nbsp;                             |   2|   whilem&#8203;: matched 0 out of 0\.\.32767
&nbsp;   1 \<\(> \<\(5maa\-maa\)>        |   3|    9&#8203;:BRANCH\(26\)
&nbsp;   1 \<\(> \<\(5maa\-maa\)>        |   4|     10&#8203;:SUSPEND\(31\)
&nbsp;   1 \<\(> \<\(5maa\-maa\)>        |   5|      12&#8203;:PLUS\(24\)
&nbsp;                             |   5|      ANYOF\[^\(\)\]\[0100\-INFINITY\] can match 0 times out of 2147483647\.\.\.
&nbsp;                             |   5|      failed\.\.\.
&nbsp;                             |   4|     failed\.\.\.
&nbsp;   1 \<\(> \<\(5maa\-maa\)>        |   3|    26&#8203;:BRANCH\(30\)
&nbsp;   1 \<\(> \<\(5maa\-maa\)>        |   4|     27&#8203;:GOSUB0\[\-26&#8203;:1\]\(31\)
&nbsp;   1 \<\(> \<\(5maa\-maa\)>        |   5|      1&#8203;:OPEN1\(3\)
&nbsp;   1 \<\(> \<\(5maa\-maa\)>        |   5|      3&#8203;:EXACT \<\(>\(5\)
&nbsp;   2 \<\(\(> \<5maa\-maa\)\(>       |   5|      5&#8203;:SUSPEND\(35\)
&nbsp;   2 \<\(\(> \<5maa\-maa\)\(>       |   6|       7&#8203;:CURLYX\[0\]\{0\,INFTY\}\(32\)
&nbsp;   2 \<\(\(> \<5maa\-maa\)\(>       |   7|        31&#8203;:WHILEM\[2/2\]\(0\)
&nbsp;                             |   7|        whilem&#8203;: matched 0 out of 0\.\.32767
&nbsp;   2 \<\(\(> \<5maa\-maa\)\(>       |   8|         9&#8203;:BRANCH\(26\)
&nbsp;   2 \<\(\(> \<5maa\-maa\)\(>       |   9|          10&#8203;:SUSPEND\(31\)
&nbsp;   2 \<\(\(> \<5maa\-maa\)\(>       |  10|           12&#8203;:PLUS\(24\)
&nbsp;                             |  10|           ANYOF\[^\(\)\]\[0100\-INFINITY\] can match 8 times out of 2147483647\.\.\.
&nbsp;                             |  10|           EVAL\_AB\[before\] GOSUB0 ce=62d600 recurse\_locinput=0
&nbsp;                             |  10|           EVAL trying tail \.\.\. \(cur\_eval=0\)
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |  11|            31&#8203;:WHILEM\[2/2\]\(0\)
&nbsp;                             |  11|            whilem&#8203;: matched 1 out of 0\.\.32767
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |  12|             9&#8203;:BRANCH\(26\)
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |  13|              10&#8203;:SUSPEND\(31\)
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |  14|               12&#8203;:PLUS\(24\)
&nbsp;                             |  14|               ANYOF\[^\(\)\]\[0100\-INFINITY\] can match 0 times out of 2147483647\.\.\.
&nbsp;                             |  14|               failed\.\.\.
&nbsp;                             |  13|              failed\.\.\.
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |  12|             26&#8203;:BRANCH\(30\)
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |  13|              27&#8203;:GOSUB0\[\-26&#8203;:1\]\(31\)
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |  14|               1&#8203;:OPEN1\(3\)
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |  14|               3&#8203;:EXACT \<\(>\(5\)
&nbsp;                             |  14|               failed\.\.\.
&nbsp;                             |  13|              EVAL\_AB\[before\] GOSUB0 ce=62da38 recurse\_locinput=0
&nbsp;                             |  12|             BRANCH failed\.\.\.
&nbsp;                             |  11|            whilem&#8203;: failed\, trying continuation\.\.\.
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |  12|             32&#8203;:NOTHING\(33\)
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |  12|             33&#8203;:SUCCEED\(0\)
&nbsp;                             |  12|             subpattern success\.\.\.
&nbsp;                             |  10|           EVAL\_AB\[before\] GOSUB0 ce=62d600 recurse\_locinput=62d2f1
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |   9|          31&#8203;:WHILEM\[2/2\]\(0\)

Program received signal SIGSEGV\, Segmentation fault\.
0x00002aaaaaffbefc in S\_regmatch \(reginfo=0x7fffffffd330\, startpos=0x62d2f0 "\(\(5maa\-maa\)\(maa\-3maa\)\)"\, prog=0x632100\)
&nbsp;    at regexec\.c&#8203;:7177
7177                min = ARG1\(cur\_curlyx\->u\.curlyx\.me\);
\(gdb\) bt
\#0  0x00002aaaaaffbefc in S\_regmatch \(reginfo=0x7fffffffd330\, startpos=0x62d2f0 "\(\(5maa\-maa\)\(maa\-3maa\)\)"\, 
&nbsp;    prog=0x632100\) at regexec\.c&#8203;:7177
\#1  0x00002aaaaafeccae in S\_regtry \(reginfo=0x7fffffffd330\, startposp=0x7fffffffd198\) at regexec\.c&#8203;:3615
\#2  0x00002aaaaafeb578 in Perl\_regexec\_flags \(rx=0x6293c8\, stringarg=0x62d2f0 "\(\(5maa\-maa\)\(maa\-3maa\)\)"\, 
&nbsp;    strend=0x62d306 ""\, strbeg=0x62d2f0 "\(\(5maa\-maa\)\(maa\-3maa\)\)"\, minend=0\, sv=0x6292a8\, data=0x0\, flags=97\)
&nbsp;    at regexec\.c&#8203;:3329
\#3  0x00002aaaaaeb16ec in Perl\_pp\_match \(\) at pp\_hot\.c&#8203;:1816
\#4  0x00002aaaaae5721d in Perl\_runops\_debug \(\) at dump\.c&#8203;:2239
\#5  0x00002aaaaad51eca in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2466
\#6  0x00002aaaaad513b4 in perl\_run \(my\_perl=0x603010\) at perl\.c&#8203;:2389
\#7  0x0000000000401062 in main \(argc=4\, argv=0x7fffffffd7b8\, env=0x7fffffffd7e0\) at perlmain\.c&#8203;:116



Another odd thing appears if you remove the possessiveness from both matches\, I do not think that the result is valid for the pattern\. Again\, changing to \(?1\) makes it work\, i\.e\. match the full string\.

> perl5\.23\.9 \-Dr \-e 'print  "\(\(5maa\-maa\)\(maa\-3maa\)\)" =~ /\(\\\(\(?&#8203;:\[^\(\)\]\+|\(?0\)\)\*\\\)\)/\,"\\n";'
Compiling REx "\(\\\(\(?&#8203;:\[^\(\)\]\+|\(?0\)\)\*\\\)\)"
rarest char \) at 0
rarest char \( at 0
Final program&#8203;:
&nbsp;   1&#8203;: OPEN1 \(3\)
&nbsp;   3&#8203;:   EXACT \<\(> \(5\)
&nbsp;   5&#8203;:   CURLYX\[0\]\{0\,INFTY\} \(26\)
&nbsp;   7&#8203;:     BRANCH \(20\)
&nbsp;   8&#8203;:       PLUS \(25\)
&nbsp;   9&#8203;:         ANYOF\[^\(\)\]\[0100\-INFINITY\] \(0\)
&nbsp;  20&#8203;:     BRANCH \(FAIL\)
&nbsp;  21&#8203;:       GOSUB0\[\-20&#8203;:1\] \(25\)
&nbsp;  24&#8203;:     TAIL \(25\)
&nbsp;  25&#8203;:   WHILEM\[2/2\] \(0\)
&nbsp;  26&#8203;:   NOTHING \(27\)
&nbsp;  27&#8203;:   EXACT \<\)> \(29\)
&nbsp;  29&#8203;: CLOSE1 \(31\)
&nbsp;  31&#8203;: END \(0\)
anchored "\(" at 0 floating "\)" at 1\.\.9223372036854775807 \(checking floating\) minlen 2 
Enabling $\` $& $' support \(0x7\)\.

EXECUTING\.\.\.

Matching REx "\(\\\(\(?&#8203;:\[^\(\)\]\+|\(?0\)\)\*\\\)\)" against "\(\(5maa\-maa\)\(maa\-3maa\)\)"
Intuit&#8203;: trying to determine minimum start position\.\.\.
&nbsp;  doing 'check' fbm scan\, \[1\.\.22\] gave 10
&nbsp;  Found floating substr "\)" at offset 10 \(rx\_origin now 0\)\.\.\.
&nbsp;  doing 'other' fbm scan\, \[0\.\.10\] gave 0
&nbsp;  Found anchored substr "\(" at offset 0 \(rx\_origin now 0\)\.\.\.
&nbsp;  \(multiline anchor test skipped\)
Intuit&#8203;: Successfully guessed&#8203;: match at offset 0
&nbsp;   0 \<> \<\(\(5maa\-maa>         |   0| 1&#8203;:OPEN1\(3\)
&nbsp;   0 \<> \<\(\(5maa\-maa>         |   0| 3&#8203;:EXACT \<\(>\(5\)
&nbsp;   1 \<\(> \<\(5maa\-maa\)>        |   0| 5&#8203;:CURLYX\[0\]\{0\,INFTY\}\(26\)
&nbsp;   1 \<\(> \<\(5maa\-maa\)>        |   1|  25&#8203;:WHILEM\[2/2\]\(0\)
&nbsp;                             |   1|  whilem&#8203;: matched 0 out of 0\.\.32767
&nbsp;   1 \<\(> \<\(5maa\-maa\)>        |   2|   7&#8203;:BRANCH\(20\)
&nbsp;   1 \<\(> \<\(5maa\-maa\)>        |   3|    8&#8203;:PLUS\(25\)
&nbsp;                             |   3|    ANYOF\[^\(\)\]\[0100\-INFINITY\] can match 0 times out of 2147483647\.\.\.
&nbsp;                             |   3|    failed\.\.\.
&nbsp;   1 \<\(> \<\(5maa\-maa\)>        |   2|   20&#8203;:BRANCH\(24\)
&nbsp;   1 \<\(> \<\(5maa\-maa\)>        |   3|    21&#8203;:GOSUB0\[\-20&#8203;:1\]\(25\)
&nbsp;   1 \<\(> \<\(5maa\-maa\)>        |   4|     1&#8203;:OPEN1\(3\)
&nbsp;   1 \<\(> \<\(5maa\-maa\)>        |   4|     3&#8203;:EXACT \<\(>\(5\)
&nbsp;   2 \<\(\(> \<5maa\-maa\)\(>       |   4|     5&#8203;:CURLYX\[0\]\{0\,INFTY\}\(26\)
&nbsp;   2 \<\(\(> \<5maa\-maa\)\(>       |   5|      25&#8203;:WHILEM\[2/2\]\(0\)
&nbsp;                             |   5|      whilem&#8203;: matched 0 out of 0\.\.32767
&nbsp;   2 \<\(\(> \<5maa\-maa\)\(>       |   6|       7&#8203;:BRANCH\(20\)
&nbsp;   2 \<\(\(> \<5maa\-maa\)\(>       |   7|        8&#8203;:PLUS\(25\)
&nbsp;                             |   7|        ANYOF\[^\(\)\]\[0100\-INFINITY\] can match 8 times out of 2147483647\.\.\.
&nbsp;                             |   7|        EVAL\_AB\[before\] GOSUB0 ce=903668 recurse\_locinput=0
&nbsp;                             |   7|        EVAL trying tail \.\.\. \(cur\_eval=0\)
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |   8|         25&#8203;:WHILEM\[2/2\]\(0\)
&nbsp;                             |   8|         whilem&#8203;: matched 1 out of 0\.\.32767
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |   9|          7&#8203;:BRANCH\(20\)
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |  10|           8&#8203;:PLUS\(25\)
&nbsp;                             |  10|           ANYOF\[^\(\)\]\[0100\-INFINITY\] can match 0 times out of 2147483647\.\.\.
&nbsp;                             |  10|           failed\.\.\.
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |   9|          20&#8203;:BRANCH\(24\)
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |  10|           21&#8203;:GOSUB0\[\-20&#8203;:1\]\(25\)
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |  11|            1&#8203;:OPEN1\(3\)
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |  11|            3&#8203;:EXACT \<\(>\(5\)
&nbsp;                             |  11|            failed\.\.\.
&nbsp;                             |  10|           EVAL\_AB\[before\] GOSUB0 ce=9039b0 recurse\_locinput=0
&nbsp;                             |   9|          BRANCH failed\.\.\.
&nbsp;                             |   8|         whilem&#8203;: failed\, trying continuation\.\.\.
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |   9|          26&#8203;:NOTHING\(27\)
&nbsp;  10 \<a\-maa> \<\)\(maa\-3maa>    |   9|          27&#8203;:EXACT \<\)>\(29\)
&nbsp;  11 \<\-maa\)> \<\(maa\-3maa\)>    |   9|          29&#8203;:CLOSE1\(31\)
&nbsp;  11 \<\-maa\)> \<\(maa\-3maa\)>    |   9|          31&#8203;:END\(0\)
&nbsp;                             |   7|        EVAL\_AB\[before\] GOSUB0 ce=903668 recurse\_locinput=9033d1
&nbsp;                             |   3|    EVAL\_AB\[before\] GOSUB0 ce=903668 recurse\_locinput=0
Match successful\!
\(\(5maa\-maa\)
Freeing REx&#8203;: "\(\\\(\(?&#8203;:\[^\(\)\]\+|\(?0\)\)\*\\\)\)"




---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=high


---
Site configuration information for perl 5\.23\.9&#8203;:

Configured by lorenz at Mon Mar 14 10&#8203;:48&#8203;:06 CET 2016\.

Summary of my perl5 \(revision 5 version 23 subversion 9\) configuration&#8203;:
&nbsp;  Commit id&#8203;: eb8fc9fea6fb514b7cdb298a1585178a7fdd0a5e
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.11\.10\-34\-default\, archname=x86\_64\-linux
&nbsp;    uname='linux borel 3\.11\.10\-34\-default \#1 smp wed jan 20 14&#8203;:13&#8203;:45 utc 2016 \(1e76e80\) x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;    config\_args='\-des \-Dprefix=/store/borel/lorenz/prefixes/perlblead \-Duseshrplib \-DEBUGGING \-Doptimize=\-O0 \-g \-pipe \-Dextras=XML&#8203;::LibXML XML&#8203;::LibXSLT XML&#8203;::Writer Term&#8203;::ReadLine&#8203;::Gnu Term&#8203;::ReadKey \-Dusedevel'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-D\_FORTIFY\_SOURCE=2'\,
&nbsp;    optimize='\-O0 \-g \-pipe'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.8\.1 20130909 \[gcc\-4\_8\-branch revision 202388\]'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib64/gcc/x86\_64\-suse\-linux/4\.8/include\-fixed /usr/lib64/gcc/x86\_64\-suse\-linux/4\.8/\.\./\.\./\.\./\.\./x86\_64\-suse\-linux/lib /usr/lib /lib/\.\./lib64 /usr/lib/\.\./lib64 /lib /lib64 /usr/lib64 /usr/local/lib64
&nbsp;    libs=\-lpthread \-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lc \-lgdbm\_compat
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.18\.so\, so=so\, useshrplib=true\, libperl=libperl\.so
&nbsp;    gnulibc\_version='2\.18'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E \-Wl\,\-rpath\,/store/borel/lorenz/prefixes/perlblead/lib/5\.23\.9/x86\_64\-linux/CORE'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O0 \-g \-pipe \-L/usr/local/lib \-fstack\-protector'




---
@&#8203;INC for perl 5\.23\.9&#8203;:
&nbsp;    /store/borel/lorenz/prefix/lib/perl5
&nbsp;    /store/borel/lorenz/prefix/lib/perl5
&nbsp;    /usr/site\-local/lib/perl5/site\_perl
&nbsp;    /store/borel/lorenz/prefixes/perlblead/lib/site\_perl/5\.23\.9/x86\_64\-linux
&nbsp;    /store/borel/lorenz/prefixes/perlblead/lib/site\_perl/5\.23\.9
&nbsp;    /store/borel/lorenz/prefixes/perlblead/lib/5\.23\.9/x86\_64\-linux
&nbsp;    /store/borel/lorenz/prefixes/perlblead/lib/5\.23\.9
&nbsp;    \.



---
Environment for perl 5\.23\.9&#8203;:
&nbsp;    HOME=/homes/combi/lorenz
&nbsp;    LANG=en\_GB\.UTF\-8
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LC\_COLLATE=en\_GB\.UTF\-8
&nbsp;    LC\_CTYPE=en\_GB\.UTF\-8
&nbsp;    LC\_MESSAGES=en\_GB\.UTF\-8
&nbsp;    LD\_LIBRARY\_PATH=/store/borel/lorenz/prefix/lib&#8203;:/store/borel/lorenz/prefix/lib&#8203;:/usr/lib64/mpi/gcc/openmpi/lib64
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/store/borel/lorenz/prefix/bin&#8203;:/store/borel/lorenz/prefix/bin&#8203;:/homes/combi/lorenz/\.cabal/bin&#8203;:/homes/combi/lorenz/\.local/bin&#8203;:/store/borel/lorenz/prefix/bin&#8203;:/store/borel/lorenz/prefix/bin&#8203;:/homes/combi/lorenz/\.cabal/bin&#8203;:/homes/combi/lorenz/\.local/bin&#8203;:/net/TeXLive/bin/x86\_64\-linux&#8203;:/usr/lib64/mpi/gcc/openmpi/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/bin/X11&#8203;:/usr/X11R6/bin&#8203;:/usr/games&#8203;:/opt/kde3/bin&#8203;:/usr/lib/mit/bin&#8203;:/usr/lib/mit/sbin&#8203;:/usr/site\-local/bin&#8203;:/usr/site\-local/share/bin
&nbsp;    PERL5LIB=/store/borel/lorenz/prefix/lib/perl5&#8203;:/store/borel/lorenz/prefix/lib/perl5&#8203;:/usr/site\-local/lib/perl5/site\_perl
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    PERL\_LOCAL\_LIB\_ROOT=&#8203;:/store/borel/lorenz/prefix&#8203;:/store/borel/lorenz/prefix
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @demerphq

On 14 March 2016 at 12&#8203;:03\, via RT \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> \# New Ticket Created by
> \# Please include the string&#8203;:  \[perl \#127705\]
> \# in the subject line of all future correspondence about this issue\.
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=127705 >
>
>
>
> This is a bug report for perl from lorenz@&#8203;math\.tu\-berlin\.de\,
> generated with the help of perlbug 1\.40 running under perl 5\.23\.9\.
>
> Since the rework related to \#126182\, the recursive pattern below causes perlblead to segfault\. We observed test failures for our software since March 8\. There is also a related \(probably\) invalid match listed further below\.

Thank you very much for the report\, and sorry for the inconvenience caused\.

>
> The pattern is almost the same as on 'perlre'\, except that I replaced \(?\-1\) by \(?0\)\. Changing that to \(?1\) fixes the segfault but should not really make any difference as far as I can see\.

That strongly suggests to me what I did wrong\.

I will do the best I can to get to the bottom of this\.

Thanks a lot\,
Yves

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @demerphq

I believe I have fixed both the issues reported in this ticket\. If the
original poster could confirm it would be nice\.

Yves

**Comment by p5pRT** [comment]
### From @mauke

Am Di 15\. Mär 2016\, 00&#8203;:35&#8203;:58\, demerphq schrieb&#8203;:
> I believe I have fixed both the issues reported in this ticket\. If the
> original poster could confirm it would be nice\.
> 

Relevant changes seem to be commit 595de7616f5ea9813e2\, ce12e2548182b5b\, and d1c49ad5e2e1b02db \(possibly\)\.

**Comment by p5pRT** [comment]
### From lorenz@math.tu-berlin.de

Both reported issues \(and the original issue in our code\) are fixed with
the latest git version \(d60341990a\)\.

Thanks a lot for the quick response and fix\,
Benjamin

**Comment by p5pRT** [comment]
### From @demerphq

On 15 March 2016 at 08&#8203;:51\, l\.mai@&#8203;web\.de via RT
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> Am Di 15\. Mär 2016\, 00&#8203;:35&#8203;:58\, demerphq schrieb&#8203;:
>> I believe I have fixed both the issues reported in this ticket\. If the
>> original poster could confirm it would be nice\.
>>
>
> Relevant changes seem to be commit 595de7616f5ea9813e2\, ce12e2548182b5b\, and d1c49ad5e2e1b02db \(possibly\)\.

d1c49ad5e2 was helpful in understanding the bug\, but was not directly
related to fixing the bug itself\.


\-\- 
perl \-Mre=debug \-e "/just|another|perl|hacker/"

**Comment by p5pRT** [comment]
### From @demerphq

On 15 March 2016 at 10&#8203;:56\, Benjamin Lorenz \<lorenz@&#8203;math\.tu\-berlin\.de> wrote&#8203;:
> Both reported issues \(and the original issue in our code\) are fixed with
> the latest git version \(d60341990a\)\.
>
> Thanks a lot for the quick response and fix\,

Thanks for the report\, and for running bleading edge perls for testing\.

It is very helpful\.

cheers\,
Yves



\-\- 
perl \-Mre=debug \-e "/just|another|perl|hacker/"

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for submitting this report\.  You have helped make Perl better\.
&nbsp;    
With the release of Perl 5\.24\.0 on May 9\, 2016\, this and 149 other issues have been resolved\.

Perl 5\.24\.0 may be downloaded via https://metacpan.org/release/RJBS/perl-5.24.0

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
