### ISSUE TITLE
$=x~0 segfaults Perl 5.24.0-RC1-2-gde1d2c7

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15279]
Migrated from [rt.perl.org#127915](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=127915) (status was 'resolved')

Searchable as RT127915$

**Comment by p5pRT** [comment]
### From @geeknik

While fuzzing Perl v5\.24\.0\-RC1\-2\-gde1d2c7 with American Fuzzy Lop\, I found that perl \-e '$=x~0' triggers a segfault\. Perl v5\.14\.2 dies with "panic&#8203;: memory wrap at test05\.pl line 1\."

Starting program&#8203;: /home/geeknik/perl/perl test05\.pl
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.

Program received signal SIGSEGV\, Segmentation fault\.
\_\_memcpy\_ssse3 \(\) at \.\./sysdeps/x86\_64/multiarch/memcpy\-ssse3\.S&#8203;:296
296     \.\./sysdeps/x86\_64/multiarch/memcpy\-ssse3\.S&#8203;: No such file or directory\.
\(gdb\) bt
\#0  \_\_memcpy\_ssse3 \(\) at \.\./sysdeps/x86\_64/multiarch/memcpy\-ssse3\.S&#8203;:296
\#1  0x00000000008208fb in memcpy \(\_\_len=131072\, \_\_src=0x11fb082\, \_\_dest=\<optimized out>\)
&nbsp;    at /usr/include/x86\_64\-linux\-gnu/bits/string3\.h&#8203;:52
\#2  Perl\_repeatcpy \(
&nbsp;    to=0x11fb082 "606060606060606060606060606060606060606060606060606060606060606060606060606060606060606060                                                                      60606060606060606060606060606060606060606060606060606060606060606060606060606060606060606060606060606060606060"\.\.\.\, from=\<optimized out>\, len=2\, count=9223372036854775806\) at util\.c&#8203;:3239
\#3  0x0000000000a62cdc in Perl\_pp\_repeat \(\) at pp\.c&#8203;:1895
\#4  0x00000000007ff5d4 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2239
\#5  0x0000000000539034 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2483
\#6  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2406
\#7  0x000000000042eac8 in main \(argc=2\, argv=0x7fffffffe678\, env=0x7fffffffe690\) at perlmain\.c&#8203;:116

==13016== Invalid write of size 1
==13016==    at 0x4C2A7C8&#8203;: memcpy \(mc\_replace\_strmem\.c&#8203;:838\)
==13016==    by 0x8208FA&#8203;: Perl\_repeatcpy \(string3\.h&#8203;:52\)
==13016==    by 0xA62CDB&#8203;: Perl\_pp\_repeat \(pp\.c&#8203;:1895\)
==13016==    by 0x7FF5D3&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2239\)
==13016==    by 0x539033&#8203;: perl\_run \(perl\.c&#8203;:2483\)
==13016==    by 0x42EAC7&#8203;: main \(perlmain\.c&#8203;:116\)
==13016==  Address 0x5eddfb1 is 7 bytes after a block of size 10 alloc'd
==13016==    at 0x4C28BED&#8203;: malloc \(vg\_replace\_malloc\.c&#8203;:263\)
==13016==    by 0x80EDD8&#8203;: Perl\_safesysmalloc \(util\.c&#8203;:153\)
==13016==    by 0x9A3C9F&#8203;: Perl\_sv\_grow \(sv\.c&#8203;:1603\)
==13016==    by 0x9BFD9F&#8203;: Perl\_sv\_2pv\_flags \(sv\.c&#8203;:3072\)
==13016==    by 0x9F0F99&#8203;: Perl\_sv\_pvn\_force\_flags \(sv\.c&#8203;:9939\)
==13016==    by 0xA638D6&#8203;: Perl\_pp\_repeat \(pp\.c&#8203;:1879\)
==13016==    by 0x7FF5D3&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2239\)
==13016==    by 0x539033&#8203;: perl\_run \(perl\.c&#8203;:2483\)
==13016==    by 0x42EAC7&#8203;: main \(perlmain\.c&#8203;:116\)
==13016==
==13016== Invalid write of size 2
==13016==    at 0x4C2A846&#8203;: memcpy \(mc\_replace\_strmem\.c&#8203;:838\)
==13016==    by 0x8208FA&#8203;: Perl\_repeatcpy \(string3\.h&#8203;:52\)
==13016==    by 0xA62CDB&#8203;: Perl\_pp\_repeat \(pp\.c&#8203;:1895\)
==13016==    by 0x7FF5D3&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2239\)
==13016==    by 0x539033&#8203;: perl\_run \(perl\.c&#8203;:2483\)
==13016==    by 0x42EAC7&#8203;: main \(perlmain\.c&#8203;:116\)
==13016==  Address 0x5eddfae is 4 bytes after a block of size 10 alloc'd
==13016==    at 0x4C28BED&#8203;: malloc \(vg\_replace\_malloc\.c&#8203;:263\)
==13016==    by 0x80EDD8&#8203;: Perl\_safesysmalloc \(util\.c&#8203;:153\)
==13016==    by 0x9A3C9F&#8203;: Perl\_sv\_grow \(sv\.c&#8203;:1603\)
==13016==    by 0x9BFD9F&#8203;: Perl\_sv\_2pv\_flags \(sv\.c&#8203;:3072\)
==13016==    by 0x9F0F99&#8203;: Perl\_sv\_pvn\_force\_flags \(sv\.c&#8203;:9939\)
==13016==    by 0xA638D6&#8203;: Perl\_pp\_repeat \(pp\.c&#8203;:1879\)
==13016==    by 0x7FF5D3&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2239\)
==13016==    by 0x539033&#8203;: perl\_run \(perl\.c&#8203;:2483\)
==13016==    by 0x42EAC7&#8203;: main \(perlmain\.c&#8203;:116\)
==13016==
==13016== Invalid read of size 1
==13016==    at 0x4C2A7C1&#8203;: memcpy \(mc\_replace\_strmem\.c&#8203;:838\)
==13016==    by 0x8208FA&#8203;: Perl\_repeatcpy \(string3\.h&#8203;:52\)
==13016==    by 0xA62CDB&#8203;: Perl\_pp\_repeat \(pp\.c&#8203;:1895\)
==13016==    by 0x7FF5D3&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2239\)
==13016==    by 0x539033&#8203;: perl\_run \(perl\.c&#8203;:2483\)
==13016==    by 0x42EAC7&#8203;: main \(perlmain\.c&#8203;:116\)
==13016==  Address 0x5eddfb1 is 7 bytes after a block of size 10 alloc'd
==13016==    at 0x4C28BED&#8203;: malloc \(vg\_replace\_malloc\.c&#8203;:263\)
==13016==    by 0x80EDD8&#8203;: Perl\_safesysmalloc \(util\.c&#8203;:153\)
==13016==    by 0x9A3C9F&#8203;: Perl\_sv\_grow \(sv\.c&#8203;:1603\)
==13016==    by 0x9BFD9F&#8203;: Perl\_sv\_2pv\_flags \(sv\.c&#8203;:3072\)
==13016==    by 0x9F0F99&#8203;: Perl\_sv\_pvn\_force\_flags \(sv\.c&#8203;:9939\)
==13016==    by 0xA638D6&#8203;: Perl\_pp\_repeat \(pp\.c&#8203;:1879\)
==13016==    by 0x7FF5D3&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2239\)
==13016==    by 0x539033&#8203;: perl\_run \(perl\.c&#8203;:2483\)
==13016==    by 0x42EAC7&#8203;: main \(perlmain\.c&#8203;:116\)
==13016==
==13016== Invalid read of size 8
==13016==    at 0x4C2A7E8&#8203;: memcpy \(mc\_replace\_strmem\.c&#8203;:838\)
==13016==    by 0x8208FA&#8203;: Perl\_repeatcpy \(string3\.h&#8203;:52\)
==13016==    by 0xA62CDB&#8203;: Perl\_pp\_repeat \(pp\.c&#8203;:1895\)
==13016==    by 0x7FF5D3&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2239\)
==13016==    by 0x539033&#8203;: perl\_run \(perl\.c&#8203;:2483\)
==13016==    by 0x42EAC7&#8203;: main \(perlmain\.c&#8203;:116\)
==13016==  Address 0x5eddfa8 is 8 bytes inside a block of size 10 alloc'd
==13016==    at 0x4C28BED&#8203;: malloc \(vg\_replace\_malloc\.c&#8203;:263\)
==13016==    by 0x80EDD8&#8203;: Perl\_safesysmalloc \(util\.c&#8203;:153\)
==13016==    by 0x9A3C9F&#8203;: Perl\_sv\_grow \(sv\.c&#8203;:1603\)
==13016==    by 0x9BFD9F&#8203;: Perl\_sv\_2pv\_flags \(sv\.c&#8203;:3072\)
==13016==    by 0x9F0F99&#8203;: Perl\_sv\_pvn\_force\_flags \(sv\.c&#8203;:9939\)
==13016==    by 0xA638D6&#8203;: Perl\_pp\_repeat \(pp\.c&#8203;:1879\)
==13016==    by 0x7FF5D3&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2239\)
==13016==    by 0x539033&#8203;: perl\_run \(perl\.c&#8203;:2483\)
==13016==    by 0x42EAC7&#8203;: main \(perlmain\.c&#8203;:116\)
==13016==
==13016== Invalid write of size 8
==13016==    at 0x4C2A7ED&#8203;: memcpy \(mc\_replace\_strmem\.c&#8203;:838\)
==13016==    by 0x8208FA&#8203;: Perl\_repeatcpy \(string3\.h&#8203;:52\)
==13016==    by 0xA62CDB&#8203;: Perl\_pp\_repeat \(pp\.c&#8203;:1895\)
==13016==    by 0x7FF5D3&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2239\)
==13016==    by 0x539033&#8203;: perl\_run \(perl\.c&#8203;:2483\)
==13016==    by 0x42EAC7&#8203;: main \(perlmain\.c&#8203;:116\)
==13016==  Address 0x5eddfb8 is 14 bytes after a block of size 10 alloc'd
==13016==    at 0x4C28BED&#8203;: malloc \(vg\_replace\_malloc\.c&#8203;:263\)
==13016==    by 0x80EDD8&#8203;: Perl\_safesysmalloc \(util\.c&#8203;:153\)
==13016==    by 0x9A3C9F&#8203;: Perl\_sv\_grow \(sv\.c&#8203;:1603\)
==13016==    by 0x9BFD9F&#8203;: Perl\_sv\_2pv\_flags \(sv\.c&#8203;:3072\)
==13016==    by 0x9F0F99&#8203;: Perl\_sv\_pvn\_force\_flags \(sv\.c&#8203;:9939\)
==13016==    by 0xA638D6&#8203;: Perl\_pp\_repeat \(pp\.c&#8203;:1879\)
==13016==    by 0x7FF5D3&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2239\)
==13016==    by 0x539033&#8203;: perl\_run \(perl\.c&#8203;:2483\)
==13016==    by 0x42EAC7&#8203;: main \(perlmain\.c&#8203;:116\)
==13016==
==13016== Invalid read of size 8
==13016==    at 0x4C2A7FA&#8203;: memcpy \(mc\_replace\_strmem\.c&#8203;:838\)
==13016==    by 0x8208FA&#8203;: Perl\_repeatcpy \(string3\.h&#8203;:52\)
==13016==    by 0xA62CDB&#8203;: Perl\_pp\_repeat \(pp\.c&#8203;:1895\)
==13016==    by 0x7FF5D3&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2239\)
==13016==    by 0x539033&#8203;: perl\_run \(perl\.c&#8203;:2483\)
==13016==    by 0x42EAC7&#8203;: main \(perlmain\.c&#8203;:116\)
==13016==  Address 0x5eddfa8 is 8 bytes inside a block of size 10 alloc'd
==13016==    at 0x4C28BED&#8203;: malloc \(vg\_replace\_malloc\.c&#8203;:263\)
==13016==    by 0x80EDD8&#8203;: Perl\_safesysmalloc \(util\.c&#8203;:153\)
==13016==    by 0x9A3C9F&#8203;: Perl\_sv\_grow \(sv\.c&#8203;:1603\)
==13016==    by 0x9BFD9F&#8203;: Perl\_sv\_2pv\_flags \(sv\.c&#8203;:3072\)
==13016==    by 0x9F0F99&#8203;: Perl\_sv\_pvn\_force\_flags \(sv\.c&#8203;:9939\)
==13016==    by 0xA638D6&#8203;: Perl\_pp\_repeat \(pp\.c&#8203;:1879\)
==13016==    by 0x7FF5D3&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2239\)
==13016==    by 0x539033&#8203;: perl\_run \(perl\.c&#8203;:2483\)
==13016==    by 0x42EAC7&#8203;: main \(perlmain\.c&#8203;:116\)
==13016==
==13016==
==13016== Process terminating with default action of signal 11 \(SIGSEGV\)
==13016==  Access not within mapped region at address 0x62DDFA1
==13016==    at 0x4C2A7C8&#8203;: memcpy \(mc\_replace\_strmem\.c&#8203;:838\)
==13016==    by 0x8208FA&#8203;: Perl\_repeatcpy \(string3\.h&#8203;:52\)
==13016==    by 0xA62CDB&#8203;: Perl\_pp\_repeat \(pp\.c&#8203;:1895\)
==13016==    by 0x7FF5D3&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2239\)
==13016==    by 0x539033&#8203;: perl\_run \(perl\.c&#8203;:2483\)
==13016==    by 0x42EAC7&#8203;: main \(perlmain\.c&#8203;:116\)
==13016==  If you believe this happened as a result of a stack
==13016==  overflow in your program's main thread \(unlikely but
==13016==  possible\)\, you can try to increase the size of the
==13016==  main thread stack using the \-\-main\-stacksize= flag\.
==13016==  The main thread stack size used in this run was 8388608\.
Segmentation fault

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Brian Carpenter wrote&#8203;:
>While fuzzing Perl v5\.24\.0\-RC1\-2\-gde1d2c7 with American Fuzzy Lop\, I
>found that perl \-e '$=x~0' triggers a segfault\. Perl v5\.14\.2 dies with
>"panic&#8203;: memory wrap at test05\.pl line 1\."

This doesn't depend on $=\.  Any two\-character string will do&#8203;:

$ perl \-lwe 'print "ab" x ~0'
panic&#8203;: memory wrap at \-e line 1\.

It's specific to length 2&#8203;:

$ perl \-lwe 'print "abc" x ~0'
Out of memory during string extend at \-e line 1\.
$ perl \-lwe 'print "a" x ~0'
Out of memory\!
panic&#8203;: fold\_constants JMPENV\_PUSH returned 2 at \-e line 1\.

The panic for length 1 is obviously a different problem\.  It's specific to
the constant\-foldable situation\, and didn't happen prior to Perl 5\.17\.1\.
It might also be considered a problem that length 1 yields the "Out of
memory\!" pseudo\-panic\, rather than the catchable exception generated
for length 3 and above\.

\-zefram

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Sun Apr 17 16&#8203;:31&#8203;:11 2016\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> While fuzzing Perl v5\.24\.0\-RC1\-2\-gde1d2c7 with American Fuzzy Lop\, I
> found that perl \-e '$=x~0' triggers a segfault\. Perl v5\.14\.2 dies with
> "panic&#8203;: memory wrap at test05\.pl line 1\."

As with \#128001\, this appears to have been fixed by 6bbd724fb7623fb05df66ca5ed83a09511903521\.

Can you reproduce it with blead?

Tony

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Jun 05\, 2016 at 09&#8203;:34&#8203;:12PM \-0700\, Tony Cook via RT wrote&#8203;:
> On Sun Apr 17 16&#8203;:31&#8203;:11 2016\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> > While fuzzing Perl v5\.24\.0\-RC1\-2\-gde1d2c7 with American Fuzzy Lop\, I
> > found that perl \-e '$=x~0' triggers a segfault\. Perl v5\.14\.2 dies with
> > "panic&#8203;: memory wrap at test05\.pl line 1\."
> 
> As with \#128001\, this appears to have been fixed by 6bbd724fb7623fb05df66ca5ed83a09511903521\.

Yes\, that commit was explicitly a fix for \[perl \#127915\]\, but I only
updated the \[perl \#127855\] ticket\. Closing\.

\-\- 
In economics\, the exam questions are the same every year\.
They just change the answers\.

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
