### ISSUE TITLE
-DDEBUGGING -Dusequadmath -Dusethreads builds crash early

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15274]
Migrated from [rt.perl.org#127894](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=127894) (status was 'resolved')

Searchable as RT127894$

**Comment by p5pRT** [comment]
### From @tonycoz

tony@&#8203;mars&#8203;:\.\.\./git/perl$ git describe
v5\.24\.0\-RC1
tony@&#8203;mars&#8203;:\.\.\./git/perl$ \./Configure \-des \-DDEBUGGING \-Dusequadmath \-Dusethreads \-Doptimize=\-ggdb3\\ \-O0 && make miniperl
\.\.\.
\./miniperl \-w \-Ilib \-Idist/Exporter/lib \-MExporter \-e '\<?>' || sh \-c 'echo >&2 Failed to build miniperl\.  Please run make minitest; exit 1'
Segmentation fault
Failed to build miniperl\. Please run make minitest
makefile&#8203;:382&#8203;: recipe for target 'lib/buildcustomize\.pl' failed
make&#8203;: \*\*\* \[lib/buildcustomize\.pl\] Error 1
tony@&#8203;mars&#8203;:\.\.\./git/perl$ gdb \-\-args \./miniperl \-e0
\.\.\.
Program received signal SIGSEGV\, Segmentation fault\.
0x00000000006325b5 in Perl\_init\_constants \(my\_perl=0xac5010\) at sv\.c&#8203;:15408
15408       SvNV\_set\(&PL\_sv\_no\, 0\);
\(gdb\) bt
\#0  0x00000000006325b5 in Perl\_init\_constants \(my\_perl=0xac5010\) at sv\.c&#8203;:15408
\#1  0x000000000044718f in perl\_construct \(my\_perl=0xac5010\) at perl\.c&#8203;:238
\#2  0x0000000000775355 in main \(argc=2\, argv=0x7fffffffe898\, 
&nbsp;    env=0x7fffffffe8b0\) at miniperlmain\.c&#8203;:116
\(gdb\) disassemble $pc\,$pc\+16
Dump of assembler code from 0x6325b5 to 0x6325c5&#8203;:
=> 0x00000000006325b5 \<Perl\_init\_constants\+1192>&#8203;:       movaps %xmm0\,0x30\(%rax\)
&nbsp;   0x00000000006325b9 \<Perl\_init\_constants\+1196>&#8203;:       mov    \-0x8\(%rbp\)\,%rax
&nbsp;   0x00000000006325bd \<Perl\_init\_constants\+1200>&#8203;:       mov    0x16c\(%rax\)\,%eax
&nbsp;   0x00000000006325c3 \<Perl\_init\_constants\+1206>&#8203;:       and    $0xf\,%eax
End of assembler dump\.
\(gdb\) info register rax
rax            0xac6de8 11300328

movaps requires 16\-byte aligned pointers&#8203;:

tony@&#8203;mars&#8203;:\.\.\./git/perl$ grep alignbytes config\.sh
alignbytes='8'

Oops\.

The alignbytes check in Configure doesn't appear to take usequadmath into account\.

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

On Wed Apr 13 21&#8203;:02&#8203;:19 2016\, tonyc wrote&#8203;:
> The alignbytes check in Configure doesn't appear to take usequadmath
> into account\.

Patch\.

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

<details><summary>0001-perl-127894-take-usequadmath-into-account-for-alignb.patch</summary>

```diff
From 001d4714f4564d74f3af9ce05470c698f534d0a8 Mon Sep 17 00:00:00 2001
From: Tony Cook <tony@develop-help.com>
Date: Thu, 14 Apr 2016 14:30:50 +1000
Subject: [PATCH] (perl #127894) take usequadmath into account for alignbytes

---
 Configure | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/Configure b/Configure
index ff864b0..94fb17e 100755
--- a/Configure
+++ b/Configure
@@ -20168,6 +20168,10 @@ case "$alignbytes" in
 	    $cat >try.c <<'EOCP'
 typedef long double NV;
 EOCP
+	elif $test "X$usequadmath" = Xdefine -a "X$i_quadmath" = Xdefine; then
+	    $cat >try.c <<'EOCP'
+typedef __float128 NV;
+EOCP
 	else
 	    $cat >try.c <<'EOCP'
 typedef double NV;
-- 
2.1.4


```
</details>

**Comment by p5pRT** [comment]
### From @tux

On Wed\, 13 Apr 2016 21&#8203;:33&#8203;:10 \-0700\, "Tony Cook via RT"
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

> On Wed Apr 13 21&#8203;:02&#8203;:19 2016\, tonyc wrote&#8203;:
> > The alignbytes check in Configure doesn't appear to take usequadmath
> > into account\.  
> 
> Patch\.

So close before 5\.24?

Is Rugby \(\#QAH\) soon enough?

> Tony

\-\- 
H\.Merijn Brand  http&#8203;://tux\.nl   Perl Monger  http&#8203;://amsterdam\.pm\.org/
using perl5\.00307 \.\. 5\.23   porting perl5 on HP\-UX\, AIX\, and openSUSE
http&#8203;://mirrors\.develooper\.com/hpux/        http&#8203;://www\.test\-smoke\.org/
http&#8203;://qa\.perl\.org   http&#8203;://www\.goldmark\.org/jeff/stupid\-disclaimers/

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @ilmari

"Tony Cook via RT" \<perlbug\-followup@&#8203;perl\.org> writes&#8203;:

> On Wed Apr 13 21&#8203;:02&#8203;:19 2016\, tonyc wrote&#8203;:
>> The alignbytes check in Configure doesn't appear to take usequadmath
>> into account\.
\[\.\.\.\]
> diff \-\-git a/Configure b/Configure
> index ff864b0\.\.94fb17e 100755
> \-\-\- a/Configure
> \+\+\+ b/Configure
> @&#8203;@&#8203; \-20168\,6 \+20168\,10 @&#8203;@&#8203; case "$alignbytes" in
>          $cat >try\.c \<\<'EOCP'
>  typedef long double NV;
>  EOCP
> \+    elif $test "X$usequadmath" = Xdefine \-a "X$i\_quadmath" = Xdefine; then
> \+        $cat >try\.c \<\<'EOCP'
> \+typedef \_\_float128 NV;
> \+EOCP
>      else
>          $cat >try\.c \<\<'EOCP'
>  typedef double NV;

Instead of having to modify this every time a new NV type comes along\,
why not make the check use $nvtype instead?

<details><summary>Inline Patch</summary>

```diff
diff --git a/Configure b/Configure
index ff864b0..2f4ffcc 100755
--- a/Configure
+++ b/Configure
@@ -20164,20 +20164,11 @@ eval $inlibc
 echo " "
 case "$alignbytes" in
     '') echo "Checking alignment constraints..." >&4
-    if $test "X$uselongdouble" = Xdefine -a "X$d_longdbl" = Xdefine; then
-        $cat >try.c <<'EOCP'
-typedef long double NV;
-EOCP
-       else
-           $cat >try.c <<'EOCP'
-typedef double NV;
-EOCP
-       fi
-       $cat >>try.c <<'EOCP'
+       $cat >try.c <<EOCP
 #include <stdio.h>
 struct foobar {
     char foo;
-    NV bar;
+    $nvtype bar;
 } try_algn;
 int main()
 {


-- 
```
</details>

"I use RMS as a guide in the same way that a boat captain would use
 a lighthouse\.  It's good to know where it is\, but you generally
 don't want to find yourself in the same spot\." \- Tollef Fog Heen

**Comment by p5pRT** [comment]
### From @tonycoz

On Thu Apr 14 12&#8203;:33&#8203;:04 2016\, ilmari wrote&#8203;:
> Instead of having to modify this every time a new NV type comes along\,
> why not make the check use $nvtype instead?
> 
> diff \-\-git a/Configure b/Configure
> index ff864b0\.\.2f4ffcc 100755
> \-\-\- a/Configure
> \+\+\+ b/Configure
> @&#8203;@&#8203; \-20164\,20 \+20164\,11 @&#8203;@&#8203; eval $inlibc
>  echo " "
>  case "$alignbytes" in
>      ''\) echo "Checking alignment constraints\.\.\." >&4
> \-    if $test "X$uselongdouble" = Xdefine \-a "X$d\_longdbl" = Xdefine; then
> \-        $cat >try\.c \<\<'EOCP'
> \-typedef long double NV;
> \-EOCP
> \-       else
> \-           $cat >try\.c \<\<'EOCP'
> \-typedef double NV;
> \-EOCP
> \-       fi
> \-       $cat >>try\.c \<\<'EOCP'
> \+       $cat >try\.c \<\<EOCP
>  \#include \<stdio\.h>
>  struct foobar \{
>      char foo;
> \-    NV bar;
> \+    $nvtype bar;
>  \} try\_algn;
>  int main\(\)
>  \{

Good point\, applied as ab462c7d2da3570ffe26e717642be96cccef8b23\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for submitting this report\.  You have helped make Perl better\.
&nbsp;    
With the release of Perl 5\.24\.0 on May 9\, 2016\, this and 149 other issues have been resolved\.

Perl 5\.24\.0 may be downloaded via https://metacpan.org/release/RJBS/perl-5.24.0

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'

**Comment by p5pRT** [comment]
### From @dcollinsn

This bug exists in 5\.22\.2\, so this fix should probably be backported to 5\.22\.3 if we're still supporting that?
