### ISSUE TITLE
Perl_ck_refassign: Assertion `left->op_type == OP_SREFGEN' failed (op.c:10498)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15285]
Migrated from [rt.perl.org#127952](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=127952) (status was 'resolved')

Searchable as RT127952$

**Comment by p5pRT** [comment]
### From @geeknik

perl \-e '0\,\!n||\!\\r=0' triggers an assertion failure in Perl v5\.24\.0\-RC1\-2\-gde1d2c7\. This bug was found with American Fuzzy Lop\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6d8e125 in \*\_\_GI\_raise \(sig=\<optimized out>\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:64
64      \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;: No such file or directory\.
\(gdb\) bt
\#0  0x00007ffff6d8e125 in \*\_\_GI\_raise \(sig=\<optimized out>\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:64
\#1  0x00007ffff6d913a0 in \*\_\_GI\_abort \(\) at abort\.c&#8203;:92
\#2  0x00007ffff6d87311 in \*\_\_GI\_\_\_assert\_fail \(
&nbsp;    assertion=assertion@&#8203;entry=0xebfb70 "left\->op\_type == OP\_SREFGEN"\, file=\<optimized out>\,
&nbsp;    file@&#8203;entry=0xf91722 "op\.c"\, line=line@&#8203;entry=10498\,
&nbsp;    function=function@&#8203;entry=0xed4720 "Perl\_ck\_refassign"\) at assert\.c&#8203;:81
\#3  0x00000000004a5869 in Perl\_ck\_refassign \(o=0x120b060\) at op\.c&#8203;:10498
\#4  0x000000000047c944 in Perl\_newBINOP \(type=type@&#8203;entry=388\, flags=flags@&#8203;entry=64\, first=0x120aa08\,
&nbsp;    last=last@&#8203;entry=0x120a988\) at op\.c&#8203;:5016
\#5  0x00000000004996ef in Perl\_newASSIGNOP \(flags=flags@&#8203;entry=64\, left=0x120a988\, optype=0\,
&nbsp;    right=0x120aa08\) at op\.c&#8203;:6518
\#6  0x00000000006608b5 in Perl\_yyparse \(gramtype=gramtype@&#8203;entry=258\) at perly\.y&#8203;:781
\#7  0x0000000000531035 in S\_parse\_body \(env=env@&#8203;entry=0x0\, xsinit=xsinit@&#8203;entry=0x42ec20 \<xs\_init>\)
&nbsp;    at perl\.c&#8203;:2331
\#8  0x0000000000537147 in perl\_parse \(my\_perl=\<optimized out>\, xsinit=xsinit@&#8203;entry=0x42ec20 \<xs\_init>\,
&nbsp;    argc=\<optimized out>\, argv=\<optimized out>\, env=env@&#8203;entry=0x0\) at perl\.c&#8203;:1650
\#9  0x000000000042e838 in main \(argc=3\, argv=0x7fffffffe658\, env=0x7fffffffe678\) at perlmain\.c&#8203;:114

Perl v5\.14\.2 fails with this message&#8203;:
Can't modify single ref constructor in scalar assignment at \-e line 1\, at EOF
Execution of \-e aborted due to compilation errors\.

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Brian Carpenter wrote&#8203;:
>perl \-e '0\,\!n||\!\\r=0' triggers an assertion failure

The initial "0\," is not required\, but all of the rest is\.  The assertion
is that the lhs of the assignment is an srefgen op\, and it's found to
actually be an ex\-not op whose child is an srefgen op\.  Something goes
awry in optimising that lhs&#8203;: that not op can't be validly optimised out\.
The same bug can be seen when using the same expression in rvalue context&#8203;:

$ perl \-le '$a = \!n||\!\\r; print $a || "false"'
SCALAR\(0xc8eb08\)

This clearly should have printed "false"\.  Nearby expressions behave
as expected&#8203;:

$ perl \-le '$a = \!"n"||\!\\r; print $a || "false"'
false
$ perl \-le '$a = \!n||\!\\"r"; print $a || "false"'
false
$ perl \-le '$a = \!\!\!n||\!\\r; print $a || "false"'
false
$ perl \-le '$a = \!n||\\r; print $a || "false"'
SCALAR\(0x246fb08\)
$ perl \-le '$a = n||\!\\r; print $a || "false"'
n
$ perl \-le '$a = n||\\r; print $a || "false"'
n

\-zefram

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @arc

Zefram \<zefram@&#8203;fysh\.org> wrote&#8203;:
> Brian Carpenter wrote&#8203;:
>>perl \-e '0\,\!n||\!\\r=0' triggers an assertion failure
>
> The initial "0\," is not required\, but all of the rest is\.  The assertion
> is that the lhs of the assignment is an srefgen op\, and it's found to
> actually be an ex\-not op whose child is an srefgen op\.  Something goes
> awry in optimising that lhs&#8203;: that not op can't be validly optimised out\.
> The same bug can be seen when using the same expression in rvalue context&#8203;:
>
> $ perl \-le '$a = \!n||\!\\r; print $a || "false"'
> SCALAR\(0xc8eb08\)
>
> This clearly should have printed "false"\.  Nearby expressions behave
> as expected&#8203;:
>
> $ perl \-le '$a = \!"n"||\!\\r; print $a || "false"'
> false
> $ perl \-le '$a = \!n||\!\\"r"; print $a || "false"'
> false
> $ perl \-le '$a = \!\!\!n||\!\\r; print $a || "false"'
> false
> $ perl \-le '$a = \!n||\\r; print $a || "false"'
> SCALAR\(0x246fb08\)
> $ perl \-le '$a = n||\!\\r; print $a || "false"'
> n
> $ perl \-le '$a = n||\\r; print $a || "false"'
> n

Thanks — your analysis there let me work out what was going on here\. Other incorrect cases include&#8203;:

$ perl \-le 'print scalar\( \!r || \!n \)'
n
$ perl \-le 'print scalar\( \!r && \!n \)'
r
$ perl \-le 'print scalar\( \!do \{ "r" \} || \!n \)'
n
$ perl \-le 'print scalar\( \!do \{ "r" \} && \!n \)'
r

This bug is fixed in blead by f15d05806fb7522031b75cb5a8784727ae03b98a&#8203;:

\[perl \#127952\] misoptimization for negated constant\-ish on lhs of logop

Negations were being incorrectly deleted from the op tree for an OP\_AND or
OP\_OR \(corresponding to Perl code with any of \`&& || and or\`\, or postfix
"if" or "unless"\) whose left\-hand side looks like "\!BAREWORD" or "\!do \{
'const' \}" and whose right\-hand side is a non\-constant\-foldable negation\.

The symptom in the reported case was an assertion failure in ck\_refassign
for an srefgen op\, caused by such an OP\_NOT having been nulled\. But other
cases exist that instead yielded incorrect results\.

The underlying cause is that two optimisations in S\_new\_logop\(\) were
partially interfering with each other\. One of those attempts to optimise
code like "\!$x && \!$y" to the equivalent of "\!\($x || $y\)"\, saving a
negation op; this is valid by De Morgan's laws\. If it detects code of
this form\, it nulls out the negations on each side of the "&&"\, and makes
a note to wrap the op it generates inside a new OP\_NOT\.

The other optimisation looks at the left\-hand arm\, and if it's a constant at
compile time\, avoids the entire logop in favour of directly evaluating the
lhs or rhs as appropriate\, and eliding whichever arm is no longer needed\.
This optimisation is important for code like this&#8203;:

&nbsp;    use constant DEBUG => …;
&nbsp;    print\_debug\_output\(\) if DEBUG;

because it allows the entire statement to be eliminated when DEBUG is false\.

When both conditions were true simultaneously\, the De Morgan optimisation
was applied before the constant\-based arm elision\. But the arm elision
involved returning early from S\_new\_logop\(\)\, so the code later in that
function that wraps the generated op in a new OP\_NOT never had a chance to
run\. This meant that "\!X && \!Y" when X is constant was being compiled as if
it were in fact "X || Y"\, which is clearly incorrect\.

This is\, however\, a very rare situation&#8203;: it requires the lhs to be an OP\_NOT
that dominates an OP\_CONST \(possibly with some intervening OP\_LINESEQ or
similar\)\. But OP\_NOT is constant\-foldable\, so that doesn't normally happen\.
The two ways for it to happen are&#8203;:

\- The constant is a bareword \(since even though barewords are constants\,
&nbsp;  they don't currently participate in constant folding\)

\- The constant is hidden inside one or more layers of do\{\} \(since that
&nbsp;  serves as a barrier to constant folding\, but the arm\-elision optimisation
&nbsp;  is smart enough to search recursively through the optree for the real
&nbsp;  constant\)

The fix is much simpler than the explanation&#8203;: apply the optimisations in the
opposite order\, so that when arm elision returns early\, the negation ops
haven't yet been nulled\.

\-\- 
Aaron Crane \*\* http&#8203;://aaroncrane\.co\.uk/

**Comment by p5pRT** [comment]
@arc - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
