### ISSUE TITLE
null pointer dereference in Perl_sv_setpvn at sv.c:4896

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15287]
Migrated from [rt.perl.org#127956](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=127956) (status was 'open')

Searchable as RT127956$

**Comment by p5pRT** [comment]
### From @geeknik

While fuzzing Perl v5\.24\.0\-RC1\-2\-gde1d2c7 with American Fuzzy Lop\, I discovered that perl \-e '$0=$\.^=\*\.=$0=0' causes a null pointer dereference and crash\. This crash affects Perl v5\.14\.2 as well\.

Program received signal SIGSEGV\, Segmentation fault\.
Perl\_sv\_setpvn \(sv=sv@&#8203;entry=0x1201948\, ptr=ptr@&#8203;entry=0xed4da7 ""\, len=len@&#8203;entry=0\) at sv\.c&#8203;:4896
4896        dptr\[len\] = '\\0';
\(gdb\) bt
\#0  Perl\_sv\_setpvn \(sv=sv@&#8203;entry=0x1201948\, ptr=ptr@&#8203;entry=0xed4da7 ""\, len=len@&#8203;entry=0\) at sv\.c&#8203;:4896
\#1  0x0000000000c2a6f3 in Perl\_do\_vop \(optype=optype@&#8203;entry=93\, sv=sv@&#8203;entry=0x1201948\,
&nbsp;    left=left@&#8203;entry=0x1201948\, right=right@&#8203;entry=0x1201930\) at doop\.c&#8203;:1011
\#2  0x0000000000a763a1 in Perl\_pp\_bit\_or \(\) at pp\.c&#8203;:2491
\#3  0x00000000007ff5d4 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2239
\#4  0x0000000000539034 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2483
\#5  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2406
\#6  0x000000000042eac8 in main \(argc=3\, argv=0x7fffffffe658\, env=0x7fffffffe678\) at perlmain\.c&#8203;:116
\(gdb\) list
4891        \}
4892        SvUPGRADE\(sv\, SVt\_PV\);
4893
4894        dptr = SvGROW\(sv\, len \+ 1\);
4895        Move\(ptr\,dptr\,len\,char\);
4896        dptr\[len\] = '\\0';
4897        SvCUR\_set\(sv\, len\);
4898        \(void\)SvPOK\_only\_UTF8\(sv\);          /\* validate pointer \*/
4899        SvTAINT\(sv\);
4900        if \(SvTYPE\(sv\) == SVt\_PVCV\) CvAUTOLOAD\_off\(sv\);

**Comment by p5pRT** [comment]
### From @Smylers

Brian Carpenter writes&#8203;:

> While fuzzing Perl v5\.24\.0\-RC1\-2\-gde1d2c7 with American Fuzzy Lop\, I
> discovered that perl \-e '$0=$\.^=\*\.=$0=0' causes a null pointer
> dereference and crash\. This crash affects Perl v5\.14\.2 as well\.

Smaller case that still yields the crash\, without special variables&#8203;:

&nbsp;  perl \-e '$x ^= \*x = 0'

Also&#8203;:
&nbsp;  
&nbsp;  perl \-e '$x |= \*x = 0'

But not&#8203;:

&nbsp;  perl \-e '$x &= \*x = 0'
&nbsp;  Can't coerce UNKNOWN to string in bitwise and \(&\) at \-e line 1\.

Smylers
\-\- 
http&#8203;://twitter\.com/Smylers2

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Fri Apr 22 01&#8203;:38&#8203;:07 2016\, smylers@&#8203;stripey\.com wrote&#8203;:
> Brian Carpenter writes&#8203;:
> 
> > While fuzzing Perl v5\.24\.0\-RC1\-2\-gde1d2c7 with American Fuzzy Lop\, I
> > discovered that perl \-e '$0=$\.^=\*\.=$0=0' causes a null pointer
> > dereference and crash\. This crash affects Perl v5\.14\.2 as well\.
> 
> Smaller case that still yields the crash\, without special variables&#8203;:
> 
>   perl \-e '$x ^= \*x = 0'
> 
> Also&#8203;:
>   
>   perl \-e '$x |= \*x = 0'
> 
> But not&#8203;:
> 
>   perl \-e '$x &= \*x = 0'
>   Can't coerce UNKNOWN to string in bitwise and \(&\) at \-e line 1\.

That UNKNOWN is an internal fallback value that should never be seen\.  I would say this last case is just as buggy\.  It smells like a stack issue\.


\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Brian Carpenter wrote&#8203;:
>perl \-e '$0=$\.^=\*\.=$0=0'

This reduces to

&nbsp;        perl \-e '$z ^= \*z=0'

which looks almost exactly like \[perl \#127934\]\.  That one used \*= and
asserted\, whereas this one uses ^= and segvs\.  They're probably the
same bug underneath\.  |= and \.= also segv&#8203;: the pattern seems to be that
numeric operations assert and string operations segv on handling the
string buffer\.

\-zefram

**Comment by p5pRT** [comment]
### From @cpansprout

On Fri Apr 22 08&#8203;:36&#8203;:02 2016\, zefram@&#8203;fysh\.org wrote&#8203;:
> Brian Carpenter wrote&#8203;:
> >perl \-e '$0=$\.^=\*\.=$0=0'
> 
> This reduces to
> 
>         perl \-e '$z ^= \*z=0'
> 
> which looks almost exactly like \[perl \#127934\]\.  That one used \*= and
> asserted\, whereas this one uses ^= and segvs\.  They're probably the
> same bug underneath\.  |= and \.= also segv&#8203;: the pattern seems to be that
> numeric operations assert and string operations segv on handling the
> string buffer\.

I am pretty sure these are both stack issues\.  The \*z=0 frees \*z\{SCALAR\} while the latter is on the stack\.

$ perl \-le 'print $^V'
v5\.12\.4
$ perl \-e '$z ^= \*z=0'
Segmentation fault&#8203;: 11
$ perl \-e '\*b=\*z; $z ^= \*z=0; print "$b\\n"' 
\*main&#8203;::0

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @geeknik

I just ran into this issue again while fuzzing v5\.25\.1\-152\-g81b22c1\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

I just ran into this issue again while fuzzing v5\.25\.1\-152\-g81b22c1\.
