### ISSUE TITLE
SIGSEGV in S_regmatch with S_study_chunk: Assertion `!frame' failed.

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15306]
Migrated from [rt.perl.org#128085](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=128085) (status was 'resolved')

Searchable as RT128085$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-Dusequadmath \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers a segmentation fault in the perl interpreter\. The testcase is the 17\-character file&#8203;:

/\(\)\(\)/~~/\\X\*\(?0\)/

On normal builds\, this crashes with a segmentation fault\. On debug builds\, this throws an assert failure that I cannot find an existing bug report for

dcollins@&#8203;nightshade64&#8203;:/usr/local/perl\-afl/out$ ~/perl/perl \-e "/\(\)\(\)/~~/\\X\*\(?0\)/"
Smartmatch is experimental at \-e line 1\.
Segmentation fault
dcollins@&#8203;nightshade64&#8203;:/usr/local/perl\-afl/out$ ~/perldebug/perl \-e "/\(\)\(\)/~~/\\X\*\(?0\)/"
Smartmatch is experimental at \-e line 1\.
perl&#8203;: regcomp\.c&#8203;:5928&#8203;: S\_study\_chunk&#8203;: Assertion \`\!frame' failed\.
Aborted
dcollins@&#8203;nightshade64&#8203;:/usr/local/perl\-afl/out$ 

Debugging tool output is below\.


\*\*GDB\*\*

dcollins@&#8203;nightshade64&#8203;:/usr/local/perl\-afl/out$ gdb \-\-args ~/perl/perl \-e "/\(\)\(\)/~~/\\X\*\(?0\)/"
GNU gdb \(GDB\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-unknown\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from /home/dcollins/perl/perl\.\.\.done\.
\(gdb\) run
Starting program&#8203;: /home/dcollins/perl/perl \-e /\\\(\\\)\\\(\\\)/\\~\\~/\\\\X\\\*\\\(\\?0\\\)/
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
Smartmatch is experimental at \-e line 1\.

Program received signal SIGSEGV\, Segmentation fault\.
0x0000000000a001f5 in S\_regmatch \(reginfo=reginfo@&#8203;entry=0x7fffffffdf10\, startpos=\<optimized out>\, prog=\<optimized out>\) at regexec\.c&#8203;:7209
7209            min = ARG1\(cur\_curlyx\->u\.curlyx\.me\);
\(gdb\) bt
\#0  0x0000000000a001f5 in S\_regmatch \(reginfo=reginfo@&#8203;entry=0x7fffffffdf10\, startpos=\<optimized out>\, prog=\<optimized out>\) at regexec\.c&#8203;:7209
\#1  0x0000000000a1e123 in S\_regtry \(reginfo=0x7fffffffdf10\, startposp=0x7fffffffdf00\) at regexec\.c&#8203;:3615
\#2  0x0000000000a5178d in Perl\_regexec\_flags \(rx=0xe993b0\, stringarg=0xea34c0 "\(?^&#8203;:\(\)\(\)\)"\, strend=0xea34c9 ""\, strbeg=0xea34c0 "\(?^&#8203;:\(\)\(\)\)"\, minend=\<optimized out>\, 
&nbsp;    sv=0xe85210\, data=0x0\, flags=97\) at regexec\.c&#8203;:3482
\#3  0x00000000007ab723 in Perl\_pp\_match \(\) at pp\_hot\.c&#8203;:1816
\#4  0x00000000008dcbd8 in S\_matcher\_matches\_sv \(matcher=matcher@&#8203;entry=0xea1e40\, sv=sv@&#8203;entry=0xe85210\) at pp\_ctl\.c&#8203;:4414
\#5  0x00000000008e7733 in S\_do\_smartmatch \(seen\_this=\<optimized out>\, seen\_other=0x0\, copied=\<optimized out>\) at pp\_ctl\.c&#8203;:4861
\#6  0x000000000079148b in Perl\_runops\_standard \(\) at run\.c&#8203;:41
\#7  0x00000000004ebf9f in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2483
\#8  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2406
\#9  0x00000000004276a8 in main \(argc=3\, argv=0x7fffffffe348\, env=0x7fffffffe368\) at perlmain\.c&#8203;:116
\(gdb\) info locals
n = \<optimized out>
min = \<optimized out>
max = \<optimized out>
A = \<optimized out>
utf8\_target = \<optimized out>
uniflags = \<optimized out>
rex\_sv = \<optimized out>
rex = 0xea3a78
rexi = 0xea6a30
st = 0xea27d8
scan = \<optimized out>
next = \<optimized out>
n = \<optimized out>
ln = \<optimized out>
locinput = \<optimized out>
pushinput = \<optimized out>
nextchr = \-10
result = false
depth = 11
nochange\_depth = 0
max\_nochange\_depth = \<optimized out>
yes\_state = 0xea2760
mark\_state = 0x0
cur\_eval = 0xea2760
cur\_curlyx = 0x0
state\_num = 48
no\_final = false
do\_cutgroup = false
startpoint = \<optimized out>
popmark = 0x0
sv\_commit = 0x0
sv\_yes\_mark = \<optimized out>
lastopen = 0
has\_cutgroup = \<optimized out>
sw = false
minmod = false
logical = 0
last\_pad = 0x0
multicall\_oldcatch = \<optimized out>
gimme = 2 '\\002'
caller\_cv = 0x0
last\_pushed\_cv = 0x0
runops\_cp = \<optimized out>
maxopenparen = 0
to\_complement = 0
classnum = \<optimized out>
is\_utf8\_pat = false
match = false
\(gdb\) 


dcollins@&#8203;nightshade64&#8203;:/usr/local/perl\-afl/out$ gdb \-\-args ~/perldebug/perl \-e "/\(\)\(\)/~~/\\X\*\(?0\)/"
GNU gdb \(GDB\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-unknown\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from /home/dcollins/perldebug/perl\.\.\.done\.
\(gdb\) run
Starting program&#8203;: /home/dcollins/perldebug/perl \-e /\\\(\\\)\\\(\\\)/\\~\\~/\\\\X\\\*\\\(\\?0\\\)/
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
Smartmatch is experimental at \-e line 1\.
perl&#8203;: regcomp\.c&#8203;:5928&#8203;: S\_study\_chunk&#8203;: Assertion \`\!frame' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6cf4107 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6cf4107 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x00007ffff6cf54e8 in abort \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#2  0x00007ffff6ced226 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#3  0x00007ffff6ced2d2 in \_\_assert\_fail \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#4  0x000000000078d8e1 in S\_study\_chunk \(pRExC\_state=pRExC\_state@&#8203;entry=0x7fffffffda70\, scanp=scanp@&#8203;entry=0x7fffffffd978\, minlenp=minlenp@&#8203;entry=0x7fffffffd958\, 
&nbsp;    deltap=deltap@&#8203;entry=0x7fffffffd968\, last=\<optimized out>\, data=data@&#8203;entry=0x7fffffffd990\, stopparen=\<optimized out>\, recursed\_depth=\<optimized out>\, 
&nbsp;    flags=\<optimized out>\, depth=\<optimized out>\, and\_withp=\<optimized out>\) at regcomp\.c&#8203;:5928
\#5  0x00000000007a1f38 in Perl\_re\_op\_compile \(patternp=patternp@&#8203;entry=0x0\, pat\_count=\<optimized out>\, pat\_count@&#8203;entry=0\, expr=\<optimized out>\, expr@&#8203;entry=0x1210dc8\, 
&nbsp;    eng=\<optimized out>\, old\_re=old\_re@&#8203;entry=0x0\, is\_bare\_re=is\_bare\_re@&#8203;entry=0x0\, orig\_rx\_flags=0\, pm\_flags=0\) at regcomp\.c&#8203;:7456
\#6  0x00000000004dc74a in Perl\_pmruntime \(o=0x1210d58\, expr=0x1210dc8\, repl=\<optimized out>\, isreg=isreg@&#8203;entry=true\, floor=\<optimized out>\) at op\.c&#8203;:5622
\#7  0x0000000000665471 in Perl\_yyparse \(gramtype=gramtype@&#8203;entry=258\) at perly\.y&#8203;:1028
\#8  0x000000000052b4c1 in S\_parse\_body \(env=env@&#8203;entry=0x0\, xsinit=xsinit@&#8203;entry=0x428f90 \<xs\_init>\) at perl\.c&#8203;:2331
\#9  0x0000000000532277 in perl\_parse \(my\_perl=\<optimized out>\, xsinit=xsinit@&#8203;entry=0x428f90 \<xs\_init>\, argc=\<optimized out>\, argv=\<optimized out>\, env=env@&#8203;entry=0x0\)
&nbsp;    at perl\.c&#8203;:1650
\#10 0x0000000000428bb8 in main \(argc=3\, argv=0x7fffffffe338\, env=0x7fffffffe358\) at perlmain\.c&#8203;:114
\(gdb\) frame 4
\#4  0x000000000078d8e1 in S\_study\_chunk \(pRExC\_state=pRExC\_state@&#8203;entry=0x7fffffffda70\, scanp=scanp@&#8203;entry=0x7fffffffd978\, minlenp=minlenp@&#8203;entry=0x7fffffffd958\, 
&nbsp;    deltap=deltap@&#8203;entry=0x7fffffffd968\, last=\<optimized out>\, data=data@&#8203;entry=0x7fffffffd990\, stopparen=\<optimized out>\, recursed\_depth=\<optimized out>\, 
&nbsp;    flags=\<optimized out>\, depth=\<optimized out>\, and\_withp=\<optimized out>\) at regcomp\.c&#8203;:5928
5928        assert\(\!frame\);
\(gdb\) info locals
min = \<optimized out>
pars = \<optimized out>
code = \<optimized out>
scan = 0x1214230
next = \<optimized out>
delta = \<optimized out>
is\_inf = \<optimized out>
is\_inf\_internal = \<optimized out>
is\_par = \<optimized out>
data\_fake = \{pos\_min = 6896942\, pos\_delta = 9\, last\_found = 0x994452 \<Perl\_sv\_upgrade\+2882>\, last\_end = 0\, last\_start\_min = 3\, last\_start\_max = 80\, longest = 0x0\, 
&nbsp;  longest\_fixed = 0x30\, offset\_fixed = 8339874\, minlen\_fixed = 0x0\, lookbehind\_fixed = \-150591968\, longest\_float = 0x1214420\, offset\_float\_min = 511101108334\, 
&nbsp;  offset\_float\_max = 0\, minlen\_float = 0x99701e \<Perl\_sv\_grow\+1774>\, lookbehind\_float = 0\, flags = 0\, whilem\_c = 0\, last\_closep = 0x1214420\, 
&nbsp;  start\_class = 0x6b41ba \<S\_\_append\_range\_to\_invlist\+2826>\}
re\_trie\_maxbuff = \<optimized out>
first\_non\_open = \<optimized out>
stopmin = \<optimized out>
frame = \<optimized out>
re\_debug\_flags = 0
\(gdb\) 


\*\*VALGRIND\*\*

dcollins@&#8203;nightshade64&#8203;:/usr/local/perl\-afl/out$ valgrind ~/perl/perl \-e "/\(\)\(\)/~~/\\X\*\(?0\)/"
==24308== Memcheck\, a memory error detector
==24308== Copyright \(C\) 2002\-2015\, and GNU GPL'd\, by Julian Seward et al\.
==24308== Using Valgrind\-3\.11\.0 and LibVEX; rerun with \-h for copyright info
==24308== Command&#8203;: /home/dcollins/perl/perl \-e /\(\)\(\)/~~/\\\\X\*\(?0\)/
==24308== 
Smartmatch is experimental at \-e line 1\.
==24308== Invalid read of size 8
==24308==    at 0xA001F5&#8203;: S\_regmatch \(regexec\.c&#8203;:7209\)
==24308==    by 0xA1E122&#8203;: S\_regtry \(regexec\.c&#8203;:3615\)
==24308==    by 0xA5178C&#8203;: Perl\_regexec\_flags \(regexec\.c&#8203;:3482\)
==24308==    by 0x7AB722&#8203;: Perl\_pp\_match \(pp\_hot\.c&#8203;:1816\)
==24308==    by 0x8DCBD7&#8203;: S\_matcher\_matches\_sv \(pp\_ctl\.c&#8203;:4414\)
==24308==    by 0x8E7732&#8203;: S\_do\_smartmatch \(pp\_ctl\.c&#8203;:4861\)
==24308==    by 0x79148A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==24308==    by 0x4EBF9E&#8203;: S\_run\_body \(perl\.c&#8203;:2483\)
==24308==    by 0x4EBF9E&#8203;: perl\_run \(perl\.c&#8203;:2406\)
==24308==    by 0x4276A7&#8203;: main \(perlmain\.c&#8203;:116\)
==24308==  Address 0x20 is not stack'd\, malloc'd or \(recently\) free'd
==24308== 
==24308== 
==24308== Process terminating with default action of signal 11 \(SIGSEGV\)
==24308==  Access not within mapped region at address 0x20
==24308==    at 0xA001F5&#8203;: S\_regmatch \(regexec\.c&#8203;:7209\)
==24308==    by 0xA1E122&#8203;: S\_regtry \(regexec\.c&#8203;:3615\)
==24308==    by 0xA5178C&#8203;: Perl\_regexec\_flags \(regexec\.c&#8203;:3482\)
==24308==    by 0x7AB722&#8203;: Perl\_pp\_match \(pp\_hot\.c&#8203;:1816\)
==24308==    by 0x8DCBD7&#8203;: S\_matcher\_matches\_sv \(pp\_ctl\.c&#8203;:4414\)
==24308==    by 0x8E7732&#8203;: S\_do\_smartmatch \(pp\_ctl\.c&#8203;:4861\)
==24308==    by 0x79148A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==24308==    by 0x4EBF9E&#8203;: S\_run\_body \(perl\.c&#8203;:2483\)
==24308==    by 0x4EBF9E&#8203;: perl\_run \(perl\.c&#8203;:2406\)
==24308==    by 0x4276A7&#8203;: main \(perlmain\.c&#8203;:116\)
==24308==  If you believe this happened as a result of a stack
==24308==  overflow in your program's main thread \(unlikely but
==24308==  possible\)\, you can try to increase the size of the
==24308==  main thread stack using the \-\-main\-stacksize= flag\.
==24308==  The main thread stack size used in this run was 8388608\.
==24308== 
==24308== HEAP SUMMARY&#8203;:
==24308==     in use at exit&#8203;: 134\,665 bytes in 649 blocks
==24308==   total heap usage&#8203;: 784 allocs\, 135 frees\, 151\,031 bytes allocated
==24308== 
==24308== LEAK SUMMARY&#8203;:
==24308==    definitely lost&#8203;: 320 bytes in 1 blocks
==24308==    indirectly lost&#8203;: 2\,604 bytes in 38 blocks
==24308==      possibly lost&#8203;: 0 bytes in 0 blocks
==24308==    still reachable&#8203;: 131\,741 bytes in 610 blocks
==24308==         suppressed&#8203;: 0 bytes in 0 blocks
==24308== Rerun with \-\-leak\-check=full to see details of leaked memory
==24308== 
==24308== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==24308== ERROR SUMMARY&#8203;: 1 errors from 1 contexts \(suppressed&#8203;: 0 from 0\)
Segmentation fault



\*\*PERL \-V\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perl$ \./perl \-Ilib \-V
Summary of my perl5 \(revision 5 version 24 subversion 0\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 10d36cf9c1885126580478a10462ed672361059e
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt20\-1\+deb8u3 \(2016\-01\-17\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='5\.2\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/x86\_64\-unknown\-linux\-gnu/5\.2\.0/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Locally applied patches&#8203;:
&nbsp;    RC3
&nbsp;  Built under linux
&nbsp;  Compiled at Apr 30 2016 15&#8203;:50&#8203;:19
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.24\.0/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.24\.0
&nbsp;    /usr/local/perl\-afl/lib/5\.24\.0/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.24\.0
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @hvds

The failure case can be simplified to&#8203;:
% miniperl \-e 'qr\{\\X\*\(?0\)\}'
miniperl&#8203;: regcomp\.c&#8203;:5928&#8203;: S\_study\_chunk&#8203;: Assertion \`\!frame' failed\.
Aborted \(core dumped\)
% 

A bisect leads to&#8203;:
&nbsp;  commit d5a00e4af6b155495be31a35728b8fef8e671ebe
&nbsp;  Author&#8203;: Yves Orton \<demerphq@&#8203;gmail\.com>
&nbsp;  Date&#8203;:   Sat Mar 5 22&#8203;:04&#8203;:28 2016 \+0100
&nbsp;    Unify GOSTART and GOSUB

I don't understand this\, but stepping through just after that commit at regcomp\.c&#8203;:4669&#8203;:
4669                start = RExC\_open\_parens\[paren\];
\(gdb\) s
4670                end   = RExC\_close\_parens\[paren\];
\(gdb\) p start
$1 = \(regnode \*\) 0xabb798
\(gdb\) p pRExC\_state\->open\_parens\[0\]@&#8203;2
$2 = \{0xabb798\, 0x0\}
\(gdb\) p pRExC\_state\->rxi\->program \+ 1
$3 = \(regnode \*\) 0xabb790
\(gdb\) 

\.\. where the latter expression is what the previous code would have evaluated for the GOSTART case\. As a result\, before that commit we recurse onto the STAR node rather than the WHILEM\.

Yves\, could you take a look?

Hugo

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @demerphq

On 8 May 2016 at 20&#8203;:32\, Hugo van der Sanden via RT
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> The failure case can be simplified to&#8203;:
> % miniperl \-e 'qr\{\\X\*\(?0\)\}'
> miniperl&#8203;: regcomp\.c&#8203;:5928&#8203;: S\_study\_chunk&#8203;: Assertion \`\!frame' failed\.
> Aborted \(core dumped\)
> %
>
> A bisect leads to&#8203;:
>   commit d5a00e4af6b155495be31a35728b8fef8e671ebe
>   Author&#8203;: Yves Orton \<demerphq@&#8203;gmail\.com>
>   Date&#8203;:   Sat Mar 5 22&#8203;:04&#8203;:28 2016 \+0100
>     Unify GOSTART and GOSUB
>
> I don't understand this\, but stepping through just after that commit at regcomp\.c&#8203;:4669&#8203;:
> 4669                start = RExC\_open\_parens\[paren\];
> \(gdb\) s
> 4670                end   = RExC\_close\_parens\[paren\];
> \(gdb\) p start
> $1 = \(regnode \*\) 0xabb798
> \(gdb\) p pRExC\_state\->open\_parens\[0\]@&#8203;2
> $2 = \{0xabb798\, 0x0\}
> \(gdb\) p pRExC\_state\->rxi\->program \+ 1
> $3 = \(regnode \*\) 0xabb790
> \(gdb\)
>
> \.\. where the latter expression is what the previous code would have evaluated for the GOSTART case\. As a result\, before that commit we recurse onto the STAR node rather than the WHILEM\.

I am not really sure I follow you there actually\. This assert fires
because the WHILEM handler goto'ed past the block that unwinds
recursion\. It should have jumped to just before the unwind block so
that it could fire if needed\.

>
> Yves\, could you take a look?

Fix pushed as branch yves/fix\_128085\.

I don't have time right now to sort out a proper test\. If you want to
hack one together it would be useful\. There are examples in t/re/pat\.t

Yves

\-\- 
perl \-Mre=debug \-e "/just|another|perl|hacker/"

**Comment by p5pRT** [comment]
### From @hvds

On Sun May 08 23&#8203;:58&#8203;:38 2016\, demerphq wrote&#8203;:
> > \.\. where the latter expression is what the previous code would have
> > evaluated for the GOSTART case\. As a result\, before that commit we
> > recurse onto the STAR node rather than the WHILEM\.
> 
> I am not really sure I follow you there actually\.

I'm saying that the bisected commit d5a00e4a\, in combining GOSUB and GOSTART\, has changed the "start" target we recurse to for the former GOSTART case \(now GOSUB\(0\)\)\.

> This assert fires
> because the WHILEM handler goto'ed past the block that unwinds
> recursion\. It should have jumped to just before the unwind block so
> that it could fire if needed\.

Ah ok; that has been the case since you added the framing stuff in 2006 \(8aa23a47\) and I had assumed this was genuinely asserting that we are not expected to hit a WHILEM when recursing \(faithfully preserved in S\_rck\_whilem\(\) in the hv/study\_chunk branch\)\.

Are you saying that's the \_only\_ problem here\, and the change of start target for GOSTART is fine?

Hugo

**Comment by p5pRT** [comment]
### From @demerphq

On 9 May 2016 at 10&#8203;:28\, Hugo van der Sanden via RT
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> On Sun May 08 23&#8203;:58&#8203;:38 2016\, demerphq wrote&#8203;:
>> > \.\. where the latter expression is what the previous code would have
>> > evaluated for the GOSTART case\. As a result\, before that commit we
>> > recurse onto the STAR node rather than the WHILEM\.
>>
>> I am not really sure I follow you there actually\.
>
> I'm saying that the bisected commit d5a00e4a\, in combining GOSUB and GOSTART\, has changed the "start" target we recurse to for the former GOSTART case \(now GOSUB\(0\)\)\.

Thanks\.

>> This assert fires
>> because the WHILEM handler goto'ed past the block that unwinds
>> recursion\. It should have jumped to just before the unwind block so
>> that it could fire if needed\.
>
> Ah ok; that has been the case since you added the framing stuff in 2006 \(8aa23a47\) and I had assumed this was genuinely asserting that we are not expected to hit a WHILEM when recursing \(faithfully preserved in S\_rck\_whilem\(\) in the hv/study\_chunk branch\)\.
>
> Are you saying that's the \_only\_ problem here\, and the change of start target for GOSTART is fine?

No\. You have identified another issue which really needs to be fixed\.
I haven't managed to come up with a satisfactory test case yet
unfortunately\.

Yves


\-\- 
perl \-Mre=debug \-e "/just|another|perl|hacker/"

**Comment by p5pRT** [comment]
### From @demerphq

I have pushed

da7cf1cc7cedc01f35ceb6724e8260c3b0ee0d12 fix \#128109 \- do not move
RExC\_open\_parens\[0\] in reginsert
1bda7a749022793a1a7ec1719cdd3d5b12feba7a fix \#128085 \- SIGSEGV in
S\_regmatch with S\_study\_chunk&#8203;: Assertion "\!frame" failed

to blead\.

Yves


\-\- 
perl \-Mre=debug \-e "/just|another|perl|hacker/"

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
