### ISSUE TITLE
SIGSEGV in hek_eq_pvn_flags

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15307]
Migrated from [rt.perl.org#128086](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=128086) (status was 'resolved')

Searchable as RT128086$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-Dusequadmath \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers a segmentation fault in the perl interpreter\. The testcase is the 25\-character file&#8203;:

/$\{\*&#8203;::&#8203;::&#8203;::=0\}$0\{\*&#8203;::&#8203;::=0\}/

On normal and debug builds\, this crashes with a segmentation fault\. 

dcollins@&#8203;nightshade64&#8203;:\~/perl$ ~/perl/perl \-e '/$\{\*&#8203;::&#8203;::&#8203;::=0\}$0\{\*&#8203;::&#8203;::=0\}/'
Segmentation fault
dcollins@&#8203;nightshade64&#8203;:\~/perl$ ~/perldebug/perl \-e '/$\{\*&#8203;::&#8203;::&#8203;::=0\}$0\{\*&#8203;::&#8203;::=0\}/'
Segmentation fault

Debugging tool output is below\. I don't think this has been reported yet\, strategic searches for "S\_mro\_gather\_and\_rename" don't seem to yield any past reports\. It's dereferencing something that isn't a pointer\.


\*\*GDB\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perl$ gdb \-\-args ~/perl/perl \-e '/$\{\*&#8203;::&#8203;::&#8203;::=0\}$0\{\*&#8203;::&#8203;::=0\}/'
GNU gdb \(GDB\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-unknown\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from /home/dcollins/perl/perl\.\.\.done\.
\(gdb\) run
Starting program&#8203;: /home/dcollins/perl/perl \-e /\\$\\\{\\\*&#8203;::&#8203;::&#8203;::=0\\\}\\$0\\\{\\\*&#8203;::&#8203;::=0\\\}/
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.

Program received signal SIGSEGV\, Segmentation fault\.
0x0000000000773478 in hek\_eq\_pvn\_flags \(flags=\<optimized out>\, pvlen=\<optimized out>\, pv=\<optimized out>\, hek=\<optimized out>\) at hv\.c&#8203;:2349
2349                return \(bytes\_cmp\_utf8\(
\(gdb\) bt
\#0  0x0000000000773478 in hek\_eq\_pvn\_flags \(flags=\<optimized out>\, pvlen=\<optimized out>\, pv=\<optimized out>\, hek=\<optimized out>\) at hv\.c&#8203;:2349
\#1  Perl\_hv\_ename\_delete \(hv=0xe99d58\, name=name@&#8203;entry=0xe92860 "&#8203;::"\, len=2\, flags=flags@&#8203;entry=0\) at hv\.c&#8203;:2488
\#2  0x000000000073020c in S\_mro\_gather\_and\_rename \(stashes=stashes@&#8203;entry=0xe99470\, seen\_stashes=seen\_stashes@&#8203;entry=0xe99500\, stash=stash@&#8203;entry=0x0\, 
&nbsp;    oldstash=oldstash@&#8203;entry=0xe99d58\, namesv=namesv@&#8203;entry=0xe994e8\) at mro\_core\.c&#8203;:962
\#3  0x000000000072d09a in S\_mro\_gather\_and\_rename \(stashes=stashes@&#8203;entry=0xe99470\, seen\_stashes=0xe99500\, stash=stash@&#8203;entry=0xe99d58\, oldstash=oldstash@&#8203;entry=0xe99cf8\, 
&nbsp;    namesv=namesv@&#8203;entry=0xe99458\) at mro\_core\.c&#8203;:1186
\#4  0x0000000000738e6b in Perl\_mro\_package\_moved \(stash=0xe99d58\, oldstash=oldstash@&#8203;entry=0xe99cf8\, gv=gv@&#8203;entry=0xe99ce0\, flags=flags@&#8203;entry=0\) at mro\_core\.c&#8203;:851
\#5  0x00000000007fd515 in Perl\_sv\_setsv\_flags \(dstr=dstr@&#8203;entry=0xe99ce0\, sstr=sstr@&#8203;entry=0xe99d40\, flags=flags@&#8203;entry=1538\) at sv\.c&#8203;:4561
\#6  0x00000000007949d0 in Perl\_pp\_sassign \(\) at pp\_hot\.c&#8203;:226
\#7  0x000000000079148b in Perl\_runops\_standard \(\) at run\.c&#8203;:41
\#8  0x00000000004ebf9f in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2483
\#9  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2406
\#10 0x00000000004276a8 in main \(argc=3\, argv=0x7fffffffe338\, env=0x7fffffffe358\) at perlmain\.c&#8203;:116
\(gdb\) info locals
No locals\.
\(gdb\) l
2344            if \(flags & SVf\_UTF8\)
2345                return \(bytes\_cmp\_utf8\(
2346                            \(const U8\*\)HEK\_KEY\(hek\)\, HEK\_LEN\(hek\)\,
2347                    \(const U8\*\)pv\, pvlen\) == 0\);
2348            else
2349                return \(bytes\_cmp\_utf8\(
2350                            \(const U8\*\)pv\, pvlen\,
2351                    \(const U8\*\)HEK\_KEY\(hek\)\, HEK\_LEN\(hek\)\) == 0\);
2352        \}
2353        else
\(gdb\) 


\*\*VALGRIND\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perl$ valgrind ~/perl/perl \-e '/$\{\*&#8203;::&#8203;::&#8203;::=0\}$0\{\*&#8203;::&#8203;::=0\}/'
==9173== Memcheck\, a memory error detector
==9173== Copyright \(C\) 2002\-2015\, and GNU GPL'd\, by Julian Seward et al\.
==9173== Using Valgrind\-3\.11\.0 and LibVEX; rerun with \-h for copyright info
==9173== Command&#8203;: /home/dcollins/perl/perl \-e /$\{\*&#8203;::&#8203;::&#8203;::=0\}$0\{\*&#8203;::&#8203;::=0\}/
==9173== 
==9173== Invalid read of size 4
==9173==    at 0x773478&#8203;: hek\_eq\_pvn\_flags \(hv\.c&#8203;:2349\)
==9173==    by 0x773478&#8203;: Perl\_hv\_ename\_delete \(hv\.c&#8203;:2488\)
==9173==    by 0x73020B&#8203;: S\_mro\_gather\_and\_rename \(mro\_core\.c&#8203;:962\)
==9173==    by 0x72D099&#8203;: S\_mro\_gather\_and\_rename \(mro\_core\.c&#8203;:1186\)
==9173==    by 0x738E6A&#8203;: Perl\_mro\_package\_moved \(mro\_core\.c&#8203;:851\)
==9173==    by 0x7FD514&#8203;: Perl\_sv\_setsv\_flags \(sv\.c&#8203;:4561\)
==9173==    by 0x7949CF&#8203;: Perl\_pp\_sassign \(pp\_hot\.c&#8203;:226\)
==9173==    by 0x79148A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==9173==    by 0x4EBF9E&#8203;: S\_run\_body \(perl\.c&#8203;:2483\)
==9173==    by 0x4EBF9E&#8203;: perl\_run \(perl\.c&#8203;:2406\)
==9173==    by 0x4276A7&#8203;: main \(perlmain\.c&#8203;:116\)
==9173==  Address 0x4 is not stack'd\, malloc'd or \(recently\) free'd
==9173== 
==9173== 
==9173== Process terminating with default action of signal 11 \(SIGSEGV\)
==9173==  Access not within mapped region at address 0x4
==9173==    at 0x773478&#8203;: hek\_eq\_pvn\_flags \(hv\.c&#8203;:2349\)
==9173==    by 0x773478&#8203;: Perl\_hv\_ename\_delete \(hv\.c&#8203;:2488\)
==9173==    by 0x73020B&#8203;: S\_mro\_gather\_and\_rename \(mro\_core\.c&#8203;:962\)
==9173==    by 0x72D099&#8203;: S\_mro\_gather\_and\_rename \(mro\_core\.c&#8203;:1186\)
==9173==    by 0x738E6A&#8203;: Perl\_mro\_package\_moved \(mro\_core\.c&#8203;:851\)
==9173==    by 0x7FD514&#8203;: Perl\_sv\_setsv\_flags \(sv\.c&#8203;:4561\)
==9173==    by 0x7949CF&#8203;: Perl\_pp\_sassign \(pp\_hot\.c&#8203;:226\)
==9173==    by 0x79148A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==9173==    by 0x4EBF9E&#8203;: S\_run\_body \(perl\.c&#8203;:2483\)
==9173==    by 0x4EBF9E&#8203;: perl\_run \(perl\.c&#8203;:2406\)
==9173==    by 0x4276A7&#8203;: main \(perlmain\.c&#8203;:116\)
==9173==  If you believe this happened as a result of a stack
==9173==  overflow in your program's main thread \(unlikely but
==9173==  possible\)\, you can try to increase the size of the
==9173==  main thread stack using the \-\-main\-stacksize= flag\.
==9173==  The main thread stack size used in this run was 8388608\.
==9173== 
==9173== HEAP SUMMARY&#8203;:
==9173==     in use at exit&#8203;: 121\,264 bytes in 656 blocks
==9173==   total heap usage&#8203;: 770 allocs\, 114 frees\, 138\,239 bytes allocated
==9173== 
==9173== LEAK SUMMARY&#8203;:
==9173==    definitely lost&#8203;: 328 bytes in 1 blocks
==9173==    indirectly lost&#8203;: 2\,631 bytes in 39 blocks
==9173==      possibly lost&#8203;: 0 bytes in 0 blocks
==9173==    still reachable&#8203;: 118\,305 bytes in 616 blocks
==9173==         suppressed&#8203;: 0 bytes in 0 blocks
==9173== Rerun with \-\-leak\-check=full to see details of leaked memory
==9173== 
==9173== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==9173== ERROR SUMMARY&#8203;: 1 errors from 1 contexts \(suppressed&#8203;: 0 from 0\)
Segmentation fault


\*\*PERL \-V\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perl$ \./perl \-Ilib \-V
Summary of my perl5 \(revision 5 version 24 subversion 0\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 10d36cf9c1885126580478a10462ed672361059e
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt20\-1\+deb8u3 \(2016\-01\-17\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='5\.2\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/x86\_64\-unknown\-linux\-gnu/5\.2\.0/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Locally applied patches&#8203;:
&nbsp;    RC3
&nbsp;  Built under linux
&nbsp;  Compiled at Apr 30 2016 15&#8203;:50&#8203;:19
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.24\.0/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.24\.0
&nbsp;    /usr/local/perl\-afl/lib/5\.24\.0/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.24\.0
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @hvds

This appears to be a precedence error\, fixable with an extra pair of parens as below\. I don't understand this area well though\, and I'd like to add a test that's less obscure than the reported test case\.

Any suggestions?

Hugo

<details><summary>Inline Patch</summary>

```diff
diff --git a/hv.c b/hv.c
index 7b5ad95..5523475 100644
--- a/hv.c
+++ b/hv.c
@@ -2476,9 +2476,10 @@ Perl_hv_ename_delete(pTHX_ HV *hv, const char *name, U32 
                return;
            }
        if (
-           count > 0 && (HEK_UTF8(*namep) || (flags & SVf_UTF8)) 
+           count > 0 && ((HEK_UTF8(*namep) || (flags & SVf_UTF8)) 
                 ? hek_eq_pvn_flags(aTHX_ *namep, name, (I32)len, flags)
                : (HEK_LEN(*namep) == (I32)len && memEQ(HEK_KEY(*namep), name, l
+            )
        ) {
            aux->xhv_name_count = -count;
        }
```
</details>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Tue May 10 01&#8203;:00&#8203;:01 2016\, hv wrote&#8203;:
> This appears to be a precedence error\, fixable with an extra pair of
> parens as below\. I don't understand this area well though\, and I'd
> like to add a test that's less obscure than the reported test case\.
> 
> Any suggestions?

I think there may be more to this bug than meets the eye\.

If I add the debugging code in the attached patch\, I get this&#8203;:

SV = PVHV\(0x7fda9280aec0\) at 0x7fda9282a938
&nbsp;  REFCNT = 1
&nbsp;  FLAGS = \(OOK\,SHAREKEYS\,OVERLOAD\)
&nbsp;  AUX\_FLAGS = 0
&nbsp;  ARRAY = 0x7fda924098e0
&nbsp;  KEYS = 0
&nbsp;  FILL = 0 \(cached = 0\)
&nbsp;  MAX = 7
&nbsp;  RITER = \-1
&nbsp;  EITER = 0x0
&nbsp;  RAND = 0x2da71023
&nbsp;  NAMECOUNT = \-3
&nbsp;  ENAME = "&#8203;::&#8203;::"\, \(null\)

etc\.

ENAME should never have null in it\.  That’s a bug\, possibly elsewhere\.  I need to dig deeper\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @cpansprout

<details><summary>Inline Patch</summary>

```diff
diff --git a/hv.c b/hv.c
index 7b5ad95..697a0aa 100644
--- a/hv.c
+++ b/hv.c
@@ -2478,7 +2478,7 @@ Perl_hv_ename_delete(pTHX_ HV *hv, const char *name, U32 len, U32 flags)
 	if (
 	    count > 0 && (HEK_UTF8(*namep) || (flags & SVf_UTF8)) 
                 ? hek_eq_pvn_flags(aTHX_ *namep, name, (I32)len, flags)
-	        : (HEK_LEN(*namep) == (I32)len && memEQ(HEK_KEY(*namep), name, len))
+	        : (*namep || (Perl_sv_dump(aTHX_ (SV*)hv),0), (HEK_LEN(*namep) == (I32)len && memEQ(HEK_KEY(*namep), name, len)))
 	) {
 	    aux->xhv_name_count = -count;
 	}
```
</details>

**Comment by p5pRT** [comment]
### From @cpansprout

On Tue May 10 21&#8203;:13&#8203;:32 2016\, sprout wrote&#8203;:
> On Tue May 10 01&#8203;:00&#8203;:01 2016\, hv wrote&#8203;:
> > This appears to be a precedence error\, fixable with an extra pair of
> > parens as below\. I don't understand this area well though\, and I'd
> > like to add a test that's less obscure than the reported test case\.
> >
> > Any suggestions?

This is the simplest test case I can come up with&#8203;:

%h; \*&#8203;::&#8203;::&#8203;::=\*h; delete $&#8203;::\{"&#8203;::"\}

It has to do with two code paths dividing up and reconstructing names like :&#8203;::&#8203;::&#8203;: differently\.

Perl keeps track of all the effective names of a stash\, if it gets aliased or reassigned\.  That is what HvENAME is for\, whereas HvNAME is the original\, canonical name of the stash\.

In the short case above\, %h must be vivified first\, before the assignment \(any compile\-time mention will work\)\.  Then\, when the assignment happens\, it gets the \*effective\* name :&#8203;::&#8203;: assigned to it\.

Internally\, a stash may have a list of names\.  If the canonical name \(the first name in the list\) is not one of the effective names\, then the name count is negative\, to indicate that\.  After the assignment above\, we have&#8203;:

NULL\, "&#8203;::&#8203;::"

\(with a name count of \-2\) such that HvNAME is NULL\, but HvENAME is a hek containing "&#8203;::&#8203;::"\.

The count>0 check in hv\_ename\_delete protects against reading that null\, but this is where the precedence problem prevents it and causes a crash\.

I think you can go ahead and apply your fix\, for this reason\.

> 
> I think there may be more to this bug than meets the eye\.
> 
> If I add the debugging code in the attached patch\, I get this&#8203;:
> 
> SV = PVHV\(0x7fda9280aec0\) at 0x7fda9282a938
>   REFCNT = 1
>   FLAGS = \(OOK\,SHAREKEYS\,OVERLOAD\)
>   AUX\_FLAGS = 0
>   ARRAY = 0x7fda924098e0
>   KEYS = 0
>   FILL = 0 \(cached = 0\)
>   MAX = 7
>   RITER = \-1
>   EITER = 0x0
>   RAND = 0x2da71023
>   NAMECOUNT = \-3
>   ENAME = "&#8203;::&#8203;::"\, \(null\)
> 
> etc\.
> 
> ENAME should never have null in it\.  That’s a bug\, possibly elsewhere\.
> I need to dig deeper\.

Actually two bugs\.  First\, \*&#8203;::&#8203;::=anything is assigning the empty string as a name to whatever hash is put there\.  Secondly\, dump\.c is dumping the empty string as \(null\)\, which should only be used for a null pointer\. \(The null\-handling code was added when ename supported was not partially written and nulls were appearing in the array due to bugs elsewhere that were fixed before the code was merged\.\)

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @cpansprout

On Sat May 14 10&#8203;:24&#8203;:41 2016\, sprout wrote&#8203;:
> On Tue May 10 21&#8203;:13&#8203;:32 2016\, sprout wrote&#8203;:
> > On Tue May 10 01&#8203;:00&#8203;:01 2016\, hv wrote&#8203;:
> > > This appears to be a precedence error\, fixable with an extra pair
> > > of
> > > parens as below\. I don't understand this area well though\, and I'd
> > > like to add a test that's less obscure than the reported test case\.
> > >
> > > Any suggestions?
> 
> This is the simplest test case I can come up with&#8203;:
> 
> %h; \*&#8203;::&#8203;::&#8203;::=\*h; delete $&#8203;::\{"&#8203;::"\}
\.\.\. 
> I think you can go ahead and apply your fix\, for this reason\.

I have applied your patch in 60a26c797bb\.  Thank you\.

I have applied the test in 7f1bd063e\.

> >
> > I think there may be more to this bug than meets the eye\.
> >
> > If I add the debugging code in the attached patch\, I get this&#8203;:
> >
> > SV = PVHV\(0x7fda9280aec0\) at 0x7fda9282a938
> >   REFCNT = 1
> >   FLAGS = \(OOK\,SHAREKEYS\,OVERLOAD\)
> >   AUX\_FLAGS = 0
> >   ARRAY = 0x7fda924098e0
> >   KEYS = 0
> >   FILL = 0 \(cached = 0\)
> >   MAX = 7
> >   RITER = \-1
> >   EITER = 0x0
> >   RAND = 0x2da71023
> >   NAMECOUNT = \-3
> >   ENAME = "&#8203;::&#8203;::"\, \(null\)
> >
> > etc\.
> >
> > ENAME should never have null in it\.  That’s a bug\, possibly
> > elsewhere\.
> > I need to dig deeper\.
> 
> Actually two bugs\.  First\, \*&#8203;::&#8203;::=anything is assigning the empty
> string as a name to whatever hash is put there\.  Secondly\, dump\.c is
> dumping the empty string as \(null\)\, which should only be used for a
> null pointer\.

I have fixed dump\.c in 8e5993c4dcf\.

As for the discrepancy in how :&#8203;::&#8203;: names are parsed\, I think we can leave things as they are unless some other real bug shows up as a result\.

I am marking this ticket as resolved\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
