### ISSUE TITLE
SIGSEGV in Perl_sv_resetpvn when "reset" catches a sub

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15314]
Migrated from [rt.perl.org#128106](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=128106) (status was 'resolved')

Searchable as RT128106$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-Dusequadmath \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers a segmentation fault in the perl interpreter\. The testcase is the 15\-character file&#8203;:

0\,reset u;sub u

On normal builds\, this crashes with a segmentation fault\. On debug builds\, this returns a segmentation fault\.

dcollins@&#8203;nightshade64&#8203;:\~/perl$ ~/perl/perl \-e 'reset u;sub u'
Segmentation fault
dcollins@&#8203;nightshade64&#8203;:\~/perl$ ~/perldebug/perl \-e 'reset u;sub u'
perl&#8203;: sv\.c&#8203;:9707&#8203;: Perl\_sv\_resetpvn&#8203;: Assertion \`\(\(svtype\)\(\(\_gvgp\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_gvgp\)\->sv\_flags & 0xff\)\) == SVt\_PVLV' failed\.
Aborted

Debugging tool output is below\. This bug exists at least going back to my installed system perl\, 5\.20\.2\.


\*\*GDB\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perl$ gdb \-\-args ~/perl/perl \-e 'reset u;sub u'         GNU gdb \(GDB\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-unknown\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from /home/dcollins/perl/perl\.\.\.done\.
\(gdb\) run
Starting program&#8203;: /home/dcollins/perl/perl \-e reset\\ u\\;sub\\ u
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.

Program received signal SIGSEGV\, Segmentation fault\.
0x00000000008339f4 in Perl\_sv\_resetpvn \(s=\<optimized out>\,
&nbsp;    len=\<optimized out>\, stash=0xe84ec8\) at sv\.c&#8203;:9707
9707                    sv = GvSV\(gv\);
\(gdb\) bt
\#0  0x00000000008339f4 in Perl\_sv\_resetpvn \(s=\<optimized out>\,
&nbsp;    len=\<optimized out>\, stash=0xe84ec8\) at sv\.c&#8203;:9707
\#1  0x000000000091b8b4 in Perl\_pp\_reset \(\) at pp\_ctl\.c&#8203;:1966
\#2  0x000000000079148b in Perl\_runops\_standard \(\) at run\.c&#8203;:41
\#3  0x00000000004ebf9f in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2483
\#4  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2406
\#5  0x00000000004276a8 in main \(argc=3\, argv=0x7fffffffe668\,
&nbsp;    env=0x7fffffffe688\) at perlmain\.c&#8203;:116
\(gdb\) info locals
gv = 0xe997d8
sv = \<optimized out>
entry = 0xe8fc60
max = \<optimized out>
i = 19
todo = '\\000' \<repeats 117 times>\, "\\001"\, '\\000' \<repeats 137 times>
send = 0xea1fe1 ""
stash = 0xe84ec8
len = \<optimized out>
s = 0xea1fe1 ""
\(gdb\)


dcollins@&#8203;nightshade64&#8203;:\~/perl$ gdb \-\-args ~/perldebug/perl \-e 'reset u;sub u'
GNU gdb \(GDB\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-unknown\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from /home/dcollins/perldebug/perl\.\.\.done\.
\(gdb\) run
Starting program&#8203;: /home/dcollins/perldebug/perl \-e reset\\ u\\;sub\\ u
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
perl&#8203;: sv\.c&#8203;:9707&#8203;: Perl\_sv\_resetpvn&#8203;: Assertion \`\(\(svtype\)\(\(\_gvgp\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_gvgp\)\->sv\_flags & 0xff\)\) == SVt\_PVLV' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6cf4107 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6cf4107 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x00007ffff6cf54e8 in abort \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#2  0x00007ffff6ced226 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#3  0x00007ffff6ced2d2 in \_\_assert\_fail \(\)
&nbsp;   from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#4  0x00000000009f2b4d in Perl\_sv\_resetpvn \(s=0x120f731 ""\,
&nbsp;    len=\<optimized out>\, stash=0x11f1ec8\) at sv\.c&#8203;:9707
\#5  0x00000000009f2f1d in Perl\_sv\_resetpvn \(s=\<optimized out>\,
&nbsp;    len=\<optimized out>\, stash=\<optimized out>\) at sv\.c&#8203;:9721
\#6  0x0000000000b83994 in Perl\_pp\_reset \(\) at pp\_ctl\.c&#8203;:1966
\#7  0x00000000007e4324 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2239
\#8  0x0000000000534e01 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2483
\#9  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2406
\#10 0x0000000000428e48 in main \(argc=3\, argv=0x7fffffffe658\,
&nbsp;    env=0x7fffffffe678\) at perlmain\.c&#8203;:116
\(gdb\) f 4
\#4  0x00000000009f2b4d in Perl\_sv\_resetpvn \(s=0x120f731 ""\,
&nbsp;    len=\<optimized out>\, stash=0x11f1ec8\) at sv\.c&#8203;:9707
9707                    sv = GvSV\(gv\);
\(gdb\) info locals
\_gvgp = 0x12068e8
gv = 0x12068e8
sv = \<optimized out>
entry = 0x11fcd70
max = \<optimized out>
i = 31
todo = '\\000' \<repeats 117 times>\, "\\001"\, '\\000' \<repeats 137 times>
send = 0x120f731 ""
\(gdb\)


\*\*VALGRIND\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perl$ valgrind ~/perl/perl \-e 'reset u;sub u'
==41582== Memcheck\, a memory error detector
==41582== Copyright \(C\) 2002\-2015\, and GNU GPL'd\, by Julian Seward et al\.
==41582== Using Valgrind\-3\.11\.0 and LibVEX; rerun with \-h for copyright info
==41582== Command&#8203;: /home/dcollins/perl/perl \-e reset\\ u;sub\\ u
==41582==
==41582== Invalid read of size 8
==41582==    at 0x8339F4&#8203;: Perl\_sv\_resetpvn \(sv\.c&#8203;:9707\)
==41582==    by 0x91B8B3&#8203;: Perl\_pp\_reset \(pp\_ctl\.c&#8203;:1966\)
==41582==    by 0x79148A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==41582==    by 0x4EBF9E&#8203;: S\_run\_body \(perl\.c&#8203;:2483\)
==41582==    by 0x4EBF9E&#8203;: perl\_run \(perl\.c&#8203;:2406\)
==41582==    by 0x4276A7&#8203;: main \(perlmain\.c&#8203;:116\)
==41582==  Address 0xffffffffffffffff is not stack'd\, malloc'd or \(recently\) free'd
==41582==
==41582==
==41582== Process terminating with default action of signal 11 \(SIGSEGV\)
==41582==  Access not within mapped region at address 0xFFFFFFFFFFFFFFFF
==41582==    at 0x8339F4&#8203;: Perl\_sv\_resetpvn \(sv\.c&#8203;:9707\)
==41582==    by 0x91B8B3&#8203;: Perl\_pp\_reset \(pp\_ctl\.c&#8203;:1966\)
==41582==    by 0x79148A&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==41582==    by 0x4EBF9E&#8203;: S\_run\_body \(perl\.c&#8203;:2483\)
==41582==    by 0x4EBF9E&#8203;: perl\_run \(perl\.c&#8203;:2406\)
==41582==    by 0x4276A7&#8203;: main \(perlmain\.c&#8203;:116\)
==41582==  If you believe this happened as a result of a stack
==41582==  overflow in your program's main thread \(unlikely but
==41582==  possible\)\, you can try to increase the size of the
==41582==  main thread stack using the \-\-main\-stacksize= flag\.
==41582==  The main thread stack size used in this run was 8388608\.
==41582==
==41582== HEAP SUMMARY&#8203;:
==41582==     in use at exit&#8203;: 108\,767 bytes in 536 blocks
==41582==   total heap usage&#8203;: 640 allocs\, 104 frees\, 124\,007 bytes allocated
==41582==
==41582== LEAK SUMMARY&#8203;:
==41582==    definitely lost&#8203;: 176 bytes in 1 blocks
==41582==    indirectly lost&#8203;: 1\,972 bytes in 20 blocks
==41582==      possibly lost&#8203;: 0 bytes in 0 blocks
==41582==    still reachable&#8203;: 106\,619 bytes in 515 blocks
==41582==         suppressed&#8203;: 0 bytes in 0 blocks
==41582== Rerun with \-\-leak\-check=full to see details of leaked memory
==41582==
==41582== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==41582== ERROR SUMMARY&#8203;: 1 errors from 1 contexts \(suppressed&#8203;: 0 from 0\)
Segmentation fault


\*\*PERL \-V\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perl$ \./perl \-Ilib \-V
Summary of my perl5 \(revision 5 version 24 subversion 0\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 10d36cf9c1885126580478a10462ed672361059e
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.16\.0\-4\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 3\.16\.0\-4\-amd64 \#1 smp debian 3\.16\.7\-ckt20\-1\+deb8u3 \(2016\-01\-17\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='5\.2\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/x86\_64\-unknown\-linux\-gnu/5\.2\.0/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL USE\_64\_BIT\_ALL
&nbsp;                        USE\_64\_BIT\_INT USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Locally applied patches&#8203;:
&nbsp;    RC3
&nbsp;  Built under linux
&nbsp;  Compiled at Apr 30 2016 15&#8203;:50&#8203;:19
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.24\.0/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.24\.0
&nbsp;    /usr/local/perl\-afl/lib/5\.24\.0/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.24\.0
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @cpansprout

On Mon May 09 16&#8203;:16&#8203;:07 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> Greetings Porters\,
> 
> I have compiled bleadperl with the afl\-gcc compiler using&#8203;:
> 
> \./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache
> afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly
> \-Uman1dir \-Uman3dir \-Dusequadmath \-des
> AFL\_HARDEN=1 make && make test
> 
> And then fuzzed the resulting binary using&#8203;:
> 
> AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;
> 
> After reducing testcases using \`afl\-tmin\` and performing additional
> minimization by hand\, I have located the following testcase that
> triggers a segmentation fault in the perl interpreter\. The testcase is
> the 15\-character file&#8203;:
> 
> 0\,reset u;sub u

This bug is old&#8203;:

$ perl5\.8\.8 \-e 'reset "u"; sub u;'
$ perl5\.8\.8 \-e 'reset "u"; sub u\($\);'
Bus error&#8203;: 10

$ perl5\.10 \-e 'reset "u"; sub u;'
Segmentation fault&#8203;: 11
$ perl5\.10 \-e 'reset "u"; sub u\($\);'
Segmentation fault&#8203;: 11

I made it worse in 5\.22&#8203;:

$ perl5\.20\.2 \-e 'reset u; sub u\{\}'
$ perl5\.22\.0 \-e 'reset u; sub u\{\}'
Segmentation fault&#8203;: 11

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Tue May 10 12&#8203;:54&#8203;:11 2016\, sprout wrote&#8203;:
> On Mon May 09 16&#8203;:16&#8203;:07 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> > Greetings Porters\,
> > 
> > I have compiled bleadperl with the afl\-gcc compiler using&#8203;:
> > 
> > \./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache
> > afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly
> > \-Uman1dir \-Uman3dir \-Dusequadmath \-des
> > AFL\_HARDEN=1 make && make test
> > 
> > And then fuzzed the resulting binary using&#8203;:
> > 
> > AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;
> > 
> > After reducing testcases using \`afl\-tmin\` and performing additional
> > minimization by hand\, I have located the following testcase that
> > triggers a segmentation fault in the perl interpreter\. The testcase is
> > the 15\-character file&#8203;:
> > 
> > 0\,reset u;sub u
> 
> This bug is old&#8203;:
> 
> $ perl5\.8\.8 \-e 'reset "u"; sub u;'
> $ perl5\.8\.8 \-e 'reset "u"; sub u\($\);'
> Bus error&#8203;: 10
> 
> $ perl5\.10 \-e 'reset "u"; sub u;'
> Segmentation fault&#8203;: 11
> $ perl5\.10 \-e 'reset "u"; sub u\($\);'
> Segmentation fault&#8203;: 11
> 
> I made it worse in 5\.22&#8203;:
> 
> $ perl5\.20\.2 \-e 'reset u; sub u\{\}'
> $ perl5\.22\.0 \-e 'reset u; sub u\{\}'
> Segmentation fault&#8203;: 11
> 

It’s worse than I thought\.  reset assumes that everything in a stash is a glob&#8203;:

$ \./perl \-Ilib \-e '$&#8203;::\{u\}=undef; reset "u"'
Assertion failed&#8203;: \(SvTYPE\(\_gvgp\) == SVt\_PVGV || SvTYPE\(\_gvgp\) == SVt\_PVLV\)\, function Perl\_sv\_resetpvn\, file sv\.c\, line 9715\.
Abort trap&#8203;: 6


\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @cpansprout

On Tue May 10 12&#8203;:58&#8203;:53 2016\, sprout wrote&#8203;:
> On Tue May 10 12&#8203;:54&#8203;:11 2016\, sprout wrote&#8203;:
> > On Mon May 09 16&#8203;:16&#8203;:07 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> > > Greetings Porters\,
> > >
> > > I have compiled bleadperl with the afl\-gcc compiler using&#8203;:
> > >
> > > \./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache
> > > afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly
> > > \-Uman1dir \-Uman3dir \-Dusequadmath \-des
> > > AFL\_HARDEN=1 make && make test
> > >
> > > And then fuzzed the resulting binary using&#8203;:
> > >
> > > AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;
> > >
> > > After reducing testcases using \`afl\-tmin\` and performing additional
> > > minimization by hand\, I have located the following testcase that
> > > triggers a segmentation fault in the perl interpreter\. The testcase
> > > is
> > > the 15\-character file&#8203;:
> > >
> > > 0\,reset u;sub u
> >
> > This bug is old&#8203;:
> >
> > $ perl5\.8\.8 \-e 'reset "u"; sub u;'
> > $ perl5\.8\.8 \-e 'reset "u"; sub u\($\);'
> > Bus error&#8203;: 10
> >
> > $ perl5\.10 \-e 'reset "u"; sub u;'
> > Segmentation fault&#8203;: 11
> > $ perl5\.10 \-e 'reset "u"; sub u\($\);'
> > Segmentation fault&#8203;: 11
> >
> > I made it worse in 5\.22&#8203;:
> >
> > $ perl5\.20\.2 \-e 'reset u; sub u\{\}'
> > $ perl5\.22\.0 \-e 'reset u; sub u\{\}'
> > Segmentation fault&#8203;: 11
> >
> 
> It’s worse than I thought\.  reset assumes that everything in a stash
> is a glob&#8203;:
> 
> $ \./perl \-Ilib \-e '$&#8203;::\{u\}=undef; reset "u"'
> Assertion failed&#8203;: \(SvTYPE\(\_gvgp\) == SVt\_PVGV || SvTYPE\(\_gvgp\) ==
> SVt\_PVLV\)\, function Perl\_sv\_resetpvn\, file sv\.c\, line 9715\.
> Abort trap&#8203;: 6

Fixed in fcd1306\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
