### ISSUE TITLE
Assert fail in toke.c postderef code with no other symptoms: /@0{0*->@/*0

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15333]
Migrated from [rt.perl.org#128171](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=128171) (status was 'resolved')

Searchable as RT128171$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-Dusequadmath \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers an assert fail in debugging builds of the perl interpreter\. The testcase is the 6\-character file&#8203;:

/@&#8203;0\{0\*\->@&#8203;/\*0

On normal builds\, this exits with the expected error\. On debug builds\, this returns an assert fail\.

dcollins@&#8203;nightshade64&#8203;:\~$ \./perldebug/miniperl \-e '/@&#8203;0\{0\*\->@&#8203;/\*0'
miniperl&#8203;: toke\.c&#8203;:1935&#8203;: S\_postderef&#8203;: Assertion \`strchr\("\*\[\{"\, next\)' failed\.
Aborted
dcollins@&#8203;nightshade64&#8203;:\~$ \./perl/miniperl \-e '/@&#8203;0\{0\*\->@&#8203;/\*0'
Number found where operator expected at \-e line 1\, near "\*0"
&nbsp;        \(Missing operator before 0?\)
syntax error at \-e line 1\, near "\*\->"
Execution of \-e aborted due to compilation errors\.

Debugging tool output is below\. A bisect was performed\, but it appears that this bug has existed since the feature was initally committed \(and is only appearing now because "use feature postderef" was a bit too much to expect a fuzzer to stumble on easily\)\.


\*\*GDB\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ gdb \-\-args \./miniperl \-e '/@&#8203;0\{0\*\->@&#8203;/\*0'
GNU gdb \(GDB\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-unknown\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from \./miniperl\.\.\.done\.
\(gdb\) run
Starting program&#8203;: /home/dcollins/perldebug/miniperl \-e /@&#8203;0\\\{0\\\*\-\\>@&#8203;/\\\*0
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
miniperl&#8203;: toke\.c&#8203;:1935&#8203;: S\_postderef&#8203;: Assertion \`strchr\("\*\[\{"\, next\)' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x00007ffff6cfa8fa in abort \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#2  0x00007ffff6cf23a7 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#3  0x00007ffff6cf2452 in \_\_assert\_fail \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#4  0x000000000047c77f in S\_postderef \(funny=42\, next=48 '0'\) at toke\.c&#8203;:1935
\#5  0x000000000048f4e1 in Perl\_yylex \(\) at toke\.c&#8203;:5373
\#6  0x00000000004b9f00 in Perl\_yyparse \(gramtype=258\) at perly\.c&#8203;:332
\#7  0x0000000000447469 in S\_parse\_body \(env=0x0\, xsinit=0x728923 \<xs\_init>\) at perl\.c&#8203;:2365
\#8  0x0000000000445f07 in perl\_parse \(my\_perl=0xa80010\, xsinit=0x728923 \<xs\_init>\, argc=3\, argv=0x7fffffffe628\, env=0x0\) at perl\.c&#8203;:1681
\#9  0x0000000000728882 in main \(argc=3\, argv=0x7fffffffe628\, env=0x7fffffffe648\) at miniperlmain\.c&#8203;:120
\(gdb\) f 4
\#4  0x000000000047c77f in S\_postderef \(funny=42\, next=48 '0'\) at toke\.c&#8203;:1935
1935        assert\(strchr\("\*\[\{"\, next\)\);
\(gdb\) l
1930
1931    static int
1932    S\_postderef\(pTHX\_ int const funny\, char const next\)
1933    \{
1934        assert\(funny == DOLSHARP || strchr\("$@&#8203;%&\*"\, funny\)\);
1935        assert\(strchr\("\*\[\{"\, next\)\);
1936        if \(next == '\*'\) \{
1937            PL\_expect = XOPERATOR;
1938            if \(PL\_lex\_state == LEX\_INTERPNORMAL && \!PL\_lex\_brackets\) \{
1939                assert\('@&#8203;' == funny || '$' == funny || DOLSHARP == funny\);
\(gdb\) info locals
\_\_PRETTY\_FUNCTION\_\_ = "S\_postderef"



\*\*PERL \-V\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perl$ \./perl \-Ilib \-V
Summary of my perl5 \(revision 5 version 25 subversion 1\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 8255316ac82c0fbd7ae49f2f9a217ce063d7bbfb
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=4\.5\.0\-2\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 4\.5\.0\-2\-amd64 \#1 smp debian 4\.5\.3\-2 \(2016\-05\-08\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='6\.1\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/x86\_64\-pc\-linux\-gnu/6\.1\.0/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.22\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.22'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_OP\_PARENT PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL
&nbsp;                        USE\_64\_BIT\_ALL USE\_64\_BIT\_INT USE\_LARGE\_FILES
&nbsp;                        USE\_LOCALE USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at May 16 2016 07&#8203;:45&#8203;:27
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.1/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.1
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.1/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.1
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.24\.0
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @cpansprout

On Tue May 17 17&#8203;:00&#8203;:26 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> Greetings Porters\,
> 
> I have compiled bleadperl with the afl\-gcc compiler using&#8203;:
> 
> \./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache
> afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly
> \-Uman1dir \-Uman3dir \-Dusequadmath \-des
> AFL\_HARDEN=1 make && make test
> 
> And then fuzzed the resulting binary using&#8203;:
> 
> AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;
> 
> After reducing testcases using \`afl\-tmin\` and performing additional
> minimization by hand\, I have located the following testcase that
> triggers an assert fail in debugging builds of the perl interpreter\.
> The testcase is the 6\-character file&#8203;:
> 
> /@&#8203;0\{0\*\->@&#8203;/\*0

Thank you\.  This is fixed in d6744494\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
