### ISSUE TITLE
Segfault in Perl_grok_number_flags under use feature 'bitwise'

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15346]
Migrated from [rt.perl.org#128204](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=128204) (status was 'resolved')

Searchable as RT128204$

**Comment by p5pRT** [comment]
### From @dcollinsn

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-Dusequadmath \-DDEBUGGING \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl \-t \-W @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers a segmentation fault in the perl interpreter\. The testcase is the file below\. On debug builds\, this returns an assert fail\.

use feature'&#8203;:all';@&#8203;0&=0

dcollins@&#8203;nightshade64&#8203;:\~$ od \-c f3i000134
0000000   u   s   e       f   e   a   t   u   r   e   '   :   a   l   l
0000020   '   ;   @&#8203;   0   &   =   0
0000027
dcollins@&#8203;nightshade64&#8203;:\~$ cd perl/
dcollins@&#8203;nightshade64&#8203;:\~/perl$ \./perl \-Ilib \.\./f3i000134
The bitwise feature is experimental at \.\./f3i000134 line 1\.
Segmentation fault
dcollins@&#8203;nightshade64&#8203;:\~/perl$ cd \.\./perldebug/
dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \.\./f3i000134
The bitwise feature is experimental at \.\./f3i000134 line 1\.
perl&#8203;: sv\.c&#8203;:2531&#8203;: Perl\_sv\_2uv\_flags&#8203;: Assertion \`\(\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) == SVt\_REGEXP || \(\(sv\)\->sv\_flags & \(0xff|0x00004000|0x00008000|0x01000000\)\) == \(SVt\_PVLV|0x01000000\)\) || \(\(sv\)\->sv\_flags & 0x00004000\)' failed\.
Aborted


Debugging tool output is below\. A git bisect was attempted\, but this persists as far back as 5\.22\, which is when the bitwise feature was first introduced\.


\*\*GDB\*\*

\(gdb\) run
Starting program&#8203;: /home/dcollins/perl/perl \-Ilib \.\./f3i000134
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
The bitwise feature is experimental at \.\./f3i000134 line 1\.

Program received signal SIGSEGV\, Segmentation fault\.
0x00000000005c41f2 in Perl\_grok\_number\_flags \(pv=0x0\,
&nbsp;    len=18446744073709551615\, valuep=0x7fffffffe300\, flags=0\) at numeric\.c&#8203;:857
857       while \(s \< send && isSPACE\(\*s\)\)
\(gdb\) bt
\#0  0x00000000005c41f2 in Perl\_grok\_number\_flags \(pv=0x0\,
&nbsp;    len=18446744073709551615\, valuep=0x7fffffffe300\, flags=0\) at numeric\.c&#8203;:857
\#1  0x00000000005c4190 in Perl\_grok\_number \(pv=0x0\, len=18446744073709551615\,
&nbsp;    valuep=0x7fffffffe300\) at numeric\.c&#8203;:841
\#2  0x000000000051b25f in Perl\_sv\_2uv\_flags \(sv=0x86d650\, flags=0\)
&nbsp;    at sv\.c&#8203;:2536
\#3  0x0000000000542238 in Perl\_pp\_nbit\_and \(\) at pp\.c&#8203;:2444
\#4  0x0000000000508326 in Perl\_runops\_standard \(\) at run\.c&#8203;:41
\#5  0x0000000000448e80 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2517
\#6  0x0000000000448a2f in perl\_run \(my\_perl=0x857010\) at perl\.c&#8203;:2440
\#7  0x000000000041e730 in main \(argc=3\, argv=0x7fffffffe628\,
&nbsp;    env=0x7fffffffe648\) at perlmain\.c&#8203;:116
\(gdb\) info locals
s = 0x0
send = 0xffffffffffffffff \<error&#8203;: Cannot access memory at address 0xffffffffffffffff>
d = 0x490000000041e550 \<error&#8203;: Cannot access memory at address 0x490000000041e550>
numtype = 0
\(gdb\) l
852       const char \*d;
853       int numtype = 0;
854
855       PERL\_ARGS\_ASSERT\_GROK\_NUMBER\_FLAGS;
856
857       while \(s \< send && isSPACE\(\*s\)\)
858         s\+\+;
859       if \(s == send\) \{
860         return 0;
861       \} else if \(\*s == '\-'\) \{
\(gdb\) q


\(gdb\) run
Starting program&#8203;: /home/dcollins/perldebug/perl \-Ilib \.\./f3i000134
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
The bitwise feature is experimental at \.\./f3i000134 line 1\.
perl&#8203;: sv\.c&#8203;:2531&#8203;: Perl\_sv\_2uv\_flags&#8203;: Assertion \`\(\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) == SVt\_REGEXP || \(\(sv\)\->sv\_flags & \(0xff|0x00004000|0x00008000|0x01000000\)\) == \(SVt\_PVLV|0x01000000\)\) || \(\(sv\)\->sv\_flags & 0x00004000\)' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x00007ffff6cfa8fa in abort \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#2  0x00007ffff6cf23a7 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#3  0x00007ffff6cf2452 in \_\_assert\_fail \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#4  0x00000000005ce153 in Perl\_sv\_2uv\_flags \(sv=0xab29e0\, flags=0\) at sv\.c&#8203;:2531
\#5  0x0000000000630232 in Perl\_pp\_nbit\_and \(\) at pp\.c&#8203;:2444
\#6  0x0000000000559af3 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2239
\#7  0x0000000000462138 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2517
\#8  0x0000000000461763 in perl\_run \(my\_perl=0xa9c010\) at perl\.c&#8203;:2440
\#9  0x000000000041e8f0 in main \(argc=3\, argv=0x7fffffffe618\, env=0x7fffffffe638\) at perlmain\.c&#8203;:116
\(gdb\) f 4
\#4  0x00000000005ce153 in Perl\_sv\_2uv\_flags \(sv=0xab29e0\, flags=0\) at sv\.c&#8203;:2531
2531            assert\(isREGEXP\(sv\) || SvPOKp\(sv\)\);
\(gdb\) info locals
\_\_PRETTY\_FUNCTION\_\_ = "Perl\_sv\_2uv\_flags"
\(gdb\) l
2526
2527        if \(SvVALID\(sv\) || isREGEXP\(sv\)\) \{
2528            /\* FBMs use the space for SvIVX and SvNVX for other purposes\, and use
2529               the same flag bit as SVf\_IVisUV\, so must not let them cache IVs\.
2530               Regexps have no SvIVX and SvNVX fields\. \*/
2531            assert\(isREGEXP\(sv\) || SvPOKp\(sv\)\);
2532            \{
2533                UV value;
2534                const char \* const ptr =
2535                    isREGEXP\(sv\) ? RX\_WRAPPED\(\(REGEXP\*\)sv\) : SvPVX\_const\(sv\);
\(gdb\)


\*\*VALGRIND\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perl$ valgrind \./perl \-Ilib \.\./f3i000134
==60697== Memcheck\, a memory error detector
==60697== Copyright \(C\) 2002\-2015\, and GNU GPL'd\, by Julian Seward et al\.
==60697== Using Valgrind\-3\.11\.0 and LibVEX; rerun with \-h for copyright info
==60697== Command&#8203;: \./perl \-Ilib \.\./f3i000134
==60697==
The bitwise feature is experimental at \.\./f3i000134 line 1\.
==60697== Invalid read of size 1
==60697==    at 0x5C41F2&#8203;: Perl\_grok\_number\_flags \(numeric\.c&#8203;:857\)
==60697==    by 0x5C418F&#8203;: Perl\_grok\_number \(numeric\.c&#8203;:841\)
==60697==    by 0x51B25E&#8203;: Perl\_sv\_2uv\_flags \(sv\.c&#8203;:2536\)
==60697==    by 0x542237&#8203;: Perl\_pp\_nbit\_and \(pp\.c&#8203;:2444\)
==60697==    by 0x508325&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==60697==    by 0x448E7F&#8203;: S\_run\_body \(perl\.c&#8203;:2517\)
==60697==    by 0x448A2E&#8203;: perl\_run \(perl\.c&#8203;:2440\)
==60697==    by 0x41E72F&#8203;: main \(perlmain\.c&#8203;:116\)
==60697==  Address 0x0 is not stack'd\, malloc'd or \(recently\) free'd
==60697==
==60697==
==60697== Process terminating with default action of signal 11 \(SIGSEGV\)
==60697==  Access not within mapped region at address 0x0
==60697==    at 0x5C41F2&#8203;: Perl\_grok\_number\_flags \(numeric\.c&#8203;:857\)
==60697==    by 0x5C418F&#8203;: Perl\_grok\_number \(numeric\.c&#8203;:841\)
==60697==    by 0x51B25E&#8203;: Perl\_sv\_2uv\_flags \(sv\.c&#8203;:2536\)
==60697==    by 0x542237&#8203;: Perl\_pp\_nbit\_and \(pp\.c&#8203;:2444\)
==60697==    by 0x508325&#8203;: Perl\_runops\_standard \(run\.c&#8203;:41\)
==60697==    by 0x448E7F&#8203;: S\_run\_body \(perl\.c&#8203;:2517\)
==60697==    by 0x448A2E&#8203;: perl\_run \(perl\.c&#8203;:2440\)
==60697==    by 0x41E72F&#8203;: main \(perlmain\.c&#8203;:116\)
==60697==  If you believe this happened as a result of a stack
==60697==  overflow in your program's main thread \(unlikely but
==60697==  possible\)\, you can try to increase the size of the
==60697==  main thread stack using the \-\-main\-stacksize= flag\.
==60697==  The main thread stack size used in this run was 8388608\.
==60697==
==60697== HEAP SUMMARY&#8203;:
==60697==     in use at exit&#8203;: 204\,449 bytes in 900 blocks
==60697==   total heap usage&#8203;: 1\,617 allocs\, 717 frees\, 325\,916 bytes allocated
==60697==
==60697== LEAK SUMMARY&#8203;:
==60697==    definitely lost&#8203;: 192 bytes in 1 blocks
==60697==    indirectly lost&#8203;: 2\,024 bytes in 22 blocks
==60697==      possibly lost&#8203;: 44\,648 bytes in 32 blocks
==60697==    still reachable&#8203;: 157\,585 bytes in 845 blocks
==60697==                       of which reachable via heuristic&#8203;:
==60697==                         newarray           : 224 bytes in 7 blocks
==60697==         suppressed&#8203;: 0 bytes in 0 blocks
==60697== Rerun with \-\-leak\-check=full to see details of leaked memory
==60697==
==60697== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==60697== ERROR SUMMARY&#8203;: 1 errors from 1 contexts \(suppressed&#8203;: 0 from 0\)
Segmentation fault


\*\*PERL \-V\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perl$ \./perl \-Ilib \-V
Summary of my perl5 \(revision 5 version 25 subversion 1\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 9e17953912c0ab4f21dd642345727a44c388a0af
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=4\.5\.0\-2\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 4\.5\.0\-2\-amd64 \#1 smp debian 4\.5\.3\-2 \(2016\-05\-08\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache gcc\-6\.1 \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache gcc\-6\.1'\, ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='6\.1\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache gcc\-6\.1'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/x86\_64\-pc\-linux\-gnu/6\.1\.0/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.22\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.22'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_OP\_PARENT PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL
&nbsp;                        USE\_64\_BIT\_ALL USE\_64\_BIT\_INT USE\_LARGE\_FILES
&nbsp;                        USE\_LOCALE USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at May 17 2016 20&#8203;:01&#8203;:23
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.1/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.1
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.1/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.1
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.24\.0
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @cpansprout

On Fri May 20 19&#8203;:41&#8203;:40 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> I have compiled bleadperl with the afl\-gcc compiler using&#8203;:
> 
> \./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache
> afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly
> \-Uman1dir \-Uman3dir \-Dusequadmath \-DDEBUGGING \-des
> AFL\_HARDEN=1 make && make test
> 
> And then fuzzed the resulting binary using&#8203;:
> 
> AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl \-t \-W @&#8203;@&#8203;
> 
> After reducing testcases using \`afl\-tmin\` and performing additional
> minimization by hand\, I have located the following testcase that
> triggers a segmentation fault in the perl interpreter\. The testcase is
> the file below\. On debug builds\, this returns an assert fail\.
> 
> use feature'&#8203;:all';@&#8203;0&=0

Thank you for the report\.  This is fixed in 76734a321\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
