### ISSUE TITLE
Assert fail in sv.c with no further symptoms: e t''/$0{\0}

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15340]
Migrated from [rt.perl.org#128189](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=128189) (status was 'resolved')

Searchable as RT128189$

**Comment by p5pRT** [comment]
### From @dcollinsn

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-Dusequadmath \-DDEBUGGING \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl \-t \-W @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers an assert fail in debugging builds of the perl interpreter\. The testcase is the file below\. On normal builds\, this exits with the expected error\. On debug builds with \-W\, this returns an assert fail\.

dcollins@&#8203;nightshade64&#8203;:\~$ perl/miniperl \-W \-e 'e t""/$0\{\\0\}'
Use of uninitialized value $0\{"\\200\\350\{\\2\\0\\0\\0\\0\\1\\0\\0\\0\\1\\21"\.\.\.\} in division \(/\) at \-e line 1\.
Argument "" isn't numeric in division \(/\) at \-e line 1\.
Illegal division by zero at \-e line 1\.
dcollins@&#8203;nightshade64&#8203;:\~$ perldebug/miniperl \-W \-e 'e t""/$0\{\\0\}'
miniperl&#8203;: sv\.c&#8203;:15687&#8203;: Perl\_varname&#8203;: Assertion \`PL\_valid\_types\_PVX\[\(\(svtype\)\(\(\_svcur\)\->sv\_flags & 0xff\)\) & 0xf\] || \(\(svtype\)\(\(\_svcur\)\->sv\_flags & 0xff\)\) == SVt\_REGEXP' failed\.
Aborted

Debugging tool output is below\. A git bisect was attempted\, but this persists as far back as 5\.14\.0\, which is also as far back as I'm able to compile right now\.


\*\*GDB\*\*

dcollins@&#8203;nightshade64&#8203;:\~$ gdb \-\-args perldebug/miniperl \-W \-e 'e t""/$0\{\\0\}'
GNU gdb \(GDB\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-unknown\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from perldebug/miniperl\.\.\.done\.
\(gdb\) run
Starting program&#8203;: /home/dcollins/perldebug/miniperl \-W \-e e\\ t\\"\\"/\\$0\\\{\\\\0\\\}
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
miniperl&#8203;: sv\.c&#8203;:15687&#8203;: Perl\_varname&#8203;: Assertion \`PL\_valid\_types\_PVX\[\(\(svtype\)\(\(\_svcur\)\->sv\_flags & 0xff\)\) & 0xf\] || \(\(svtype\)\(\(\_svcur\)\->sv\_flags & 0xff\)\) == SVt\_REGEXP' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x00007ffff6cfa8fa in abort \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#2  0x00007ffff6cf23a7 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#3  0x00007ffff6cf2452 in \_\_assert\_fail \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#4  0x00000000005fee9c in Perl\_varname \(gv=0xa96868\, gvtype=37 '%'\, targ=0\, keyname=0xa96bb0\, aindex=0\, subscript\_type=3\) at sv\.c&#8203;:15686
\#5  0x000000000060038c in S\_find\_uninit\_var \(obase=0xa9fd08\, uninit\_sv=0xa7e840 \<PL\_sv\_undef>\, match=false\, desc\_p=0x7fffffffdf78\) at sv\.c&#8203;:15926
\#6  0x00000000006018dd in S\_find\_uninit\_var \(obase=0xa9fcc0\, uninit\_sv=0xa7e840 \<PL\_sv\_undef>\, match=false\, desc\_p=0x7fffffffdf78\) at sv\.c&#8203;:16356
\#7  0x0000000000601a80 in Perl\_report\_uninit \(uninit\_sv=0xa7e840 \<PL\_sv\_undef>\) at sv\.c&#8203;:16390
\#8  0x00000000005b50a5 in Perl\_sv\_2nv\_flags \(sv=0xa7e840 \<PL\_sv\_undef>\, flags=0\) at sv\.c&#8203;:2645
\#9  0x000000000060f407 in Perl\_pp\_divide \(\) at pp\.c&#8203;:1627
\#10 0x000000000053f5f1 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2239
\#11 0x00000000004481a1 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2517
\#12 0x00000000004477cc in perl\_run \(my\_perl=0xa80010\) at perl\.c&#8203;:2440
\#13 0x000000000072889a in main \(argc=4\, argv=0x7fffffffe618\, env=0x7fffffffe640\) at miniperlmain\.c&#8203;:122
\(gdb\) f 4
\#4  0x00000000005fee9c in Perl\_varname \(gv=0xa96868\, gvtype=37 '%'\, targ=0\, keyname=0xa96bb0\, aindex=0\, subscript\_type=3\) at sv\.c&#8203;:15686
15686               pv\_pretty\(sv\, SvPVX\_const\(keyname\)\, SvCUR\(keyname\)\, 32\, NULL\, NULL\,
\(gdb\) info locals
\_svcur = 0xa96bb0
sv = 0xa963a0
name = 0xa82178
\_\_PRETTY\_FUNCTION\_\_ = "Perl\_varname"
\(gdb\) q



\*\*PERL \-V\*\*

dcollins@&#8203;nightshade64&#8203;:\~$ perl/perl  \-V
Summary of my perl5 \(revision 5 version 25 subversion 1\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 9e17953912c0ab4f21dd642345727a44c388a0af
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=4\.5\.0\-2\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 4\.5\.0\-2\-amd64 \#1 smp debian 4\.5\.3\-2 \(2016\-05\-08\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache afl\-gcc \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DDEBUG\_LEAKING\_SCALARS \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache afl\-gcc'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='6\.1\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache afl\-gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/x86\_64\-pc\-linux\-gnu/6\.1\.0/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.22\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.22'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_OP\_PARENT PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL
&nbsp;                        USE\_64\_BIT\_ALL USE\_64\_BIT\_INT USE\_LARGE\_FILES
&nbsp;                        USE\_LOCALE USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at May 17 2016 20&#8203;:01&#8203;:23
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.1/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.1
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.1/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.1
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.24\.0
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @dcollinsn

The slightly shorter testcase&#8203;:

perl \-W \-e 'e f/$0\{\\0\}/'

also shows this error

**Comment by p5pRT** [comment]
### From @dcollinsn

I really should finish looking through my queue before posting\. Best testcase is the 8\-character file&#8203;:

miniperl \-W \-e '0/$0\{\\0\}'

**Comment by p5pRT** [comment]
### From @cpansprout

On Thu May 19 14&#8203;:53&#8203;:18 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> The slightly shorter testcase&#8203;:
> 
> perl \-W \-e 'e f/$0\{\\0\}/'
> 
> also shows this error

Shorter&#8203;:

perl \-we '"$0\{\\0\}"'
perl \-we '/$0\{\\0\}/'

Any uninitialized warning that tries to mention $0\{\\0\} will trigger it\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Thu May 19 15&#8203;:02&#8203;:05 2016\, sprout wrote&#8203;:
> On Thu May 19 14&#8203;:53&#8203;:18 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> > The slightly shorter testcase&#8203;:
> > 
> > perl \-W \-e 'e f/$0\{\\0\}/'
> > 
> > also shows this error
> 
> Shorter&#8203;:
> 
> perl \-we '"$0\{\\0\}"'
> perl \-we '/$0\{\\0\}/'
> 
> Any uninitialized warning that tries to mention $0\{\\0\} will trigger it\.
> 

It appears that the subscript has to be an OP\_CONST\, because qr// doesn’t trigger it\.

A bisect points to&#8203;:

commit 04698ff67968faa57a46c12d31e17c17baf08876
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Sat Nov 27 06&#8203;:22&#8203;:24 2010 \-0800

&nbsp;    \[perl \#79178\] STORE/FETCH of tie\(\)d hash get stringified key

but that is a red herring\.  It fixed another bug\, exposing this one\.

Here is a similar bug with array indices\.  There is no crash here\, but the number in the subscript is bogus&#8203;:

$ \./miniperl \-we '"$0\[\\0\]"'
Useless use of string in void context at \-e line 1\.
Use of reference "SCALAR\(0x7fad6882fcf0\)" as array index at \-e line 1\.
Use of uninitialized value $0\[1753414896\] in string at \-e line 1\.
$ perl \-le 'print 0x7fad6882fcf0'
140382759484656

I would expect the output of the latter command to match the subscript in the uninit warning\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Father Chrysostomos via RT wrote&#8203;:
>Use of reference "SCALAR\(0x7fad6882fcf0\)" as array index at \-e line 1\.
>Use of uninitialized value $0\[1753414896\] in string at \-e line 1\.

$ perl \-le 'printf "%x\\n"\, 1753414896'
6882fcf0

The index has been truncated to 32 bits\, that's all\.

\-zefram

**Comment by p5pRT** [comment]
### From @cpansprout

On Thu May 19 15&#8203;:33&#8203;:41 2016\, zefram@&#8203;fysh\.org wrote&#8203;:
> Father Chrysostomos via RT wrote&#8203;:
> >Use of reference "SCALAR\(0x7fad6882fcf0\)" as array index at \-e line 1\.
> >Use of uninitialized value $0\[1753414896\] in string at \-e line 1\.
> 
> $ perl \-le 'printf "%x\\n"\, 1753414896'
> 6882fcf0
> 
> The index has been truncated to 32 bits\, that's all\.

I thought it might be that\.  I was too lazy to check\.  That itself is also a bug\, though\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, May 19\, 2016 at 05&#8203;:18&#8203;:31PM \-0700\, Father Chrysostomos via RT wrote&#8203;:
> On Thu May 19 15&#8203;:33&#8203;:41 2016\, zefram@&#8203;fysh\.org wrote&#8203;:
> > Father Chrysostomos via RT wrote&#8203;:
> > >Use of reference "SCALAR\(0x7fad6882fcf0\)" as array index at \-e line 1\.
> > >Use of uninitialized value $0\[1753414896\] in string at \-e line 1\.
> > 
> > $ perl \-le 'printf "%x\\n"\, 1753414896'
> > 6882fcf0
> > 
> > The index has been truncated to 32 bits\, that's all\.
> 
> I thought it might be that\.  I was too lazy to check\.  That itself is also a bug\, though\.

The original issue is now fixed with v5\.25\.2\-15\-g55b6481\.
I'm not going to address the 32\-bitness of the AV API here\.

\-\- 
Dave's first rule of Opera&#8203;:
If something needs saying\, say it&#8203;: don't warble it\.

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @cpansprout

On Tue Jun 21 07&#8203;:29&#8203;:25 2016\, davem wrote&#8203;:
> I'm not going to address the 32\-bitness of the AV API here\.

The AV API was changed to support 64\-bit indices some time ago \(e\.g\. v5\.19\.3\-99\-gc70927a\)\, but report\_uninit\_var got left behind\.

I have fixed it in commit 1b3df0e\.

\-\- 

Father Chrysostomos
