### ISSUE TITLE
Assert fail in op.c without other symptoms: sub{\@0[0]=0}

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15363]
Migrated from [rt.perl.org#128252](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=128252) (status was 'resolved')

Searchable as RT128252$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-Dusequadmath \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers an assert fail in debug buids of the perl interpreter\. The testcase is the file below\. On normal builds\, this runs normally \(albeit with an expected warning\)\. On debug builds\, this returns an assert fail\.

dcollins@&#8203;nightshade64&#8203;:\~/perl$ \./perl \-Ilib \-t \-W \-e 'sub\{\\@&#8203;0\[0\]=0\}'
Experimental aliasing via reference not enabled at \-e line 1\.
dcollins@&#8203;nightshade64&#8203;:\~/perl$ cd \.\./perldebug/
dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-t \-W \-e 'sub\{\\@&#8203;0\[0\]=0\}'
Experimental aliasing via reference not enabled at \-e line 1\.
perl&#8203;: op\.c&#8203;:731&#8203;: Perl\_op\_free&#8203;: Assertion \`\!\(o\->op\_private & ~PL\_op\_private\_valid\[type\]\)' failed\.
Aborted

The closing brace is not necessary in order to replicate\, and neither is \-t\, but \-W is\.

Debugging tool output is below\. A git bisect was performed and reported the following\.

0ca7b7f7720bb25ab1fc20faded8002d21b67c88 is the first bad commit
commit 0ca7b7f7720bb25ab1fc20faded8002d21b67c88
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Fri Sep 26 10&#8203;:40&#8203;:19 2014 \-0700

&nbsp;    \\@&#8203;array\[@&#8203;slice\] assignment

&nbsp;    plus changes to the aelem tests to check rhs context\.

&nbsp;    I did \\local @&#8203;a\[@&#8203;s\] at the same time\, since I was practically copying
&nbsp;    and pasting code from aslice \(ok\, not quite\)\.

:100644 100644 1184bf28927651410830cce06bf2f9018d44f4c2 150d70f3457ae67e43c9ec8bbe82836be0211c19 M       op\.c
:100644 100644 da6a72cfa55d635de4cc1649ab503fd9cc3bc835 baaa140e28a97c7385ddb64e4d9f910f8b945f0f M       pp\.c
:040000 040000 62d63f1a713fbd075cd67e5b7d452179088514e2 dcb2f8fc0165a9a5be98e2af41983bb4a9a39ae8 M       t
bisect run success



\*\*GDB\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ gdb \-\-args \./perl \-Ilib \-W \-e 'sub\{\\@&#8203;0\[0\]=0\}'
GNU gdb \(GDB\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-unknown\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from \./perl\.\.\.done\.
\(gdb\) run
Starting program&#8203;: /home/dcollins/perldebug/perl \-Ilib \-W \-e sub\\\{\\\\@&#8203;0\\\[0\\\]=0\\\}
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
Experimental aliasing via reference not enabled at \-e line 1\.
perl&#8203;: op\.c&#8203;:731&#8203;: Perl\_op\_free&#8203;: Assertion \`\!\(o\->op\_private & ~PL\_op\_private\_valid\[type\]\)' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x00007ffff6cfa8fa in abort \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#2  0x00007ffff6cf23a7 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#3  0x00007ffff6cf2452 in \_\_assert\_fail \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#4  0x00000000004213cf in Perl\_op\_free \(o=0xabbc00\) at op\.c&#8203;:731
\#5  0x0000000000420932 in Perl\_opslab\_force\_free \(slab=0xabbb00\) at op\.c&#8203;:448
\#6  0x00000000004da35c in Perl\_cv\_undef\_flags \(cv=0xab2710\, flags=0\) at pad\.c&#8203;:354
\#7  0x00000000004d9d88 in Perl\_cv\_undef \(cv=0xab2710\) at pad\.c&#8203;:302
\#8  0x00000000005f4cd1 in Perl\_sv\_clear \(orig\_sv=0xab2710\) at sv\.c&#8203;:6504
\#9  0x00000000005f7e2e in Perl\_sv\_free2 \(sv=0xab2710\, rc=1\) at sv\.c&#8203;:6954
\#10 0x00000000004d3d41 in S\_SvREFCNT\_dec \(sv=0xab2710\) at inline\.h&#8203;:166
\#11 0x00000000004d43df in S\_clear\_yystack \(parser=0xab9d40\) at perly\.c&#8203;:234
\#12 0x0000000000656917 in Perl\_leave\_scope \(base=0\) at scope\.c&#8203;:1176
\#13 0x000000000046e5d2 in S\_my\_exit\_jump \(\) at perl\.c&#8203;:5189
\#14 0x000000000046e41b in Perl\_my\_failure\_exit \(\) at perl\.c&#8203;:5173
\#15 0x0000000000664ed7 in Perl\_die\_unwind \(msv=0xab27a0\) at pp\_ctl\.c&#8203;:1722
\#16 0x0000000000560917 in Perl\_vcroak \(
&nbsp;    pat=0x746498 "Experimental aliasing via reference not enabled"\, args=0x7fffffffdd60\)
&nbsp;    at util\.c&#8203;:1791
\#17 0x00000000005609c8 in Perl\_croak \(
&nbsp;    pat=0x746498 "Experimental aliasing via reference not enabled"\) at util\.c&#8203;:1836
\#18 0x00000000004277dd in Perl\_op\_lvalue\_flags \(o=0xabc0d8\, type=38\, flags=0\) at op\.c&#8203;:3132
\#19 0x0000000000432e26 in Perl\_newASSIGNOP \(flags=64\, left=0xabc0d8\, optype=0\, right=0xabc098\)
&nbsp;    at op\.c&#8203;:6412
\#20 0x00000000004d7428 in Perl\_yyparse \(gramtype=258\) at perly\.y&#8203;:781
\#21 0x000000000046169b in S\_parse\_body \(env=0x0\, xsinit=0x41eb69 \<xs\_init>\) at perl\.c&#8203;:2365
\#22 0x000000000045fae1 in perl\_parse \(my\_perl=0xa9c010\, xsinit=0x41eb69 \<xs\_init>\, argc=5\,
&nbsp;    argv=0x7fffffffe608\, env=0x0\) at perl\.c&#8203;:1681
\#23 0x000000000041eac8 in main \(argc=5\, argv=0x7fffffffe608\, env=0x7fffffffe638\)
&nbsp;    at perlmain\.c&#8203;:114
\(gdb\) f 4
\#4  0x00000000004213cf in Perl\_op\_free \(o=0xabbc00\) at op\.c&#8203;:731
731                 assert\(\!\(o\->op\_private & ~PL\_op\_private\_valid\[type\]\)\);
\(gdb\) l
726     \#ifdef DEBUGGING
727             if \(   o\->op\_ppaddr == PL\_ppaddr\[o\->op\_type\]
728                 && PL\_parser
729                 && \!PL\_parser\->error\_count\)
730             \{
731                 assert\(\!\(o\->op\_private & ~PL\_op\_private\_valid\[type\]\)\);
732             \}
733     \#endif
734
735             if \(o\->op\_private & OPpREFCOUNTED\) \{
\(gdb\) info locals
type = 391
defer\_ix = \-1
defer\_stack\_alloc = 100
defer\_stack = 0xabe190
\_\_PRETTY\_FUNCTION\_\_ = "Perl\_op\_free"



\*\*VALGRIND\*\*

No reported memory management errors\.


\*\*PERL \-V\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-V
Summary of my perl5 \(revision 5 version 25 subversion 2\) configuration&#8203;:
&nbsp;  Commit id&#8203;: c29dfc6a6c45f86648c51f961304254cc3c449b9
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=4\.5\.0\-2\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 4\.5\.0\-2\-amd64 \#1 smp debian 4\.5\.3\-2 \(2016\-05\-08\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache gcc\-6\.1 \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache gcc\-6\.1'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='6\.1\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache gcc\-6\.1'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/x86\_64\-pc\-linux\-gnu/6\.1\.0/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.22\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.22'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_OP\_PARENT PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL
&nbsp;                        USE\_64\_BIT\_ALL USE\_64\_BIT\_INT USE\_LARGE\_FILES
&nbsp;                        USE\_LOCALE USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at May 26 2016 17&#8203;:57&#8203;:37
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.2/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.2
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.2/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.2
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.1
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.24\.0
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, May 26\, 2016 at 04&#8203;:33&#8203;:47PM \-0700\, Dan Collins wrote&#8203;:
> dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-t \-W \-e 'sub\{\\@&#8203;0\[0\]=0\}'
> Experimental aliasing via reference not enabled at \-e line 1\.
> perl&#8203;: op\.c&#8203;:731&#8203;: Perl\_op\_free&#8203;: Assertion \`\!\(o\->op\_private & ~PL\_op\_private\_valid\[type\]\)' failed\.

Fixed by v5\.25\.2\-53\-g36efb5a

\-\- 
Hofstadter's Law&#8203;: It always takes longer than you expect\, even when you
take into account Hofstadter's Law\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Mon Jun 27 07&#8203;:08&#8203;:15 2016\, davem wrote&#8203;:
> On Thu\, May 26\, 2016 at 04&#8203;:33&#8203;:47PM \-0700\, Dan Collins wrote&#8203;:
> > dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-t \-W \-e
> > 'sub\{\\@&#8203;0\[0\]=0\}'
> > Experimental aliasing via reference not enabled at \-e line 1\.
> > perl&#8203;: op\.c&#8203;:731&#8203;: Perl\_op\_free&#8203;: Assertion \`\!\(o\->op\_private &
> > ~PL\_op\_private\_valid\[type\]\)' failed\.
> 
> Fixed by v5\.25\.2\-53\-g36efb5a

Oops\.  Thank you\.  \(Why did you not add a test?\)

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Jun 27\, 2016 at 08&#8203;:27&#8203;:28AM \-0700\, Father Chrysostomos via RT wrote&#8203;:
> On Mon Jun 27 07&#8203;:08&#8203;:15 2016\, davem wrote&#8203;:
> > On Thu\, May 26\, 2016 at 04&#8203;:33&#8203;:47PM \-0700\, Dan Collins wrote&#8203;:
> > > dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-t \-W \-e
> > > 'sub\{\\@&#8203;0\[0\]=0\}'
> > > Experimental aliasing via reference not enabled at \-e line 1\.
> > > perl&#8203;: op\.c&#8203;:731&#8203;: Perl\_op\_free&#8203;: Assertion \`\!\(o\->op\_private &
> > > ~PL\_op\_private\_valid\[type\]\)' failed\.
> > 
> > Fixed by v5\.25\.2\-53\-g36efb5a
> 
> Oops\.  Thank you\.  \(Why did you not add a test?\)

Because I'm lazy??? :\-\)

Test added with v5\.25\.2\-60\-gc61e103

\-\- 
Any \[programming\] language that doesn't occasionally surprise the
novice will pay for it by continually surprising the expert\.
&nbsp;   \-\- Larry Wall

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
