### ISSUE TITLE
Taint-mode assert fail in Perl_magic_clearisa without other symptoms

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15365]
Migrated from [rt.perl.org#128254](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=128254) (status was 'open')

Searchable as RT128254$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-Dusequadmath \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers an assert fail in debug buids of the perl interpreter\. The testcase is the file below\. On normal builds\, this runs normally \(albeit with an expected warning\)\. On debug builds\, this returns an assert fail\.

dcollins@&#8203;nightshade64&#8203;:\~/perl$ \./perl \-Ilib \-tW \-e '\{@&#8203;\{\*a&#8203;::ISA\}=undef\*a&#8203;::ISA;@&#8203;a&#8203;::ISA=0\}'
Use of uninitialized value in list assignment at \-e line 1\.
dcollins@&#8203;nightshade64&#8203;:\~/perl$ cd \.\./perldebug/

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-tW \-e '\{@&#8203;\{\*a&#8203;::ISA\}=undef\*a&#8203;::ISA;@&#8203;a&#8203;::ISA=0\}'
Use of uninitialized value in list assignment at \-e line 1\.
perl&#8203;: mg\.c&#8203;:1726&#8203;: Perl\_magic\_clearisa&#8203;: Assertion \`\(\(\(\(\_gvstash\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(\_gvstash\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_gvstash\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.
Aborted



Debugging tool output is below\. A git bisect was performed and reported the following\.

5e267fb87fe17363909b2ed49f916dccf9939c3b is the first bad commit
commit 5e267fb87fe17363909b2ed49f916dccf9939c3b
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Wed Oct 21 13&#8203;:10&#8203;:44 2015 \+0100

&nbsp;    Always copy return values when exiting scope

&nbsp;    v5\.14\.0\-642\-g3ed94dc fixed certain instances where returning from a sub
&nbsp;    incorrectly returned the actual value rather than a copy\, e\.g\.

&nbsp;        sub f \{ delete $foo\{bar\} \}

&nbsp;    This was because if the value\(s\) being returned had SvTEMP set\, copying
&nbsp;    was skipped\. That commit added an extra condition to the skip test\,
&nbsp;    SvREFCNT\(sv\) == 1\.

&nbsp;    However\, this applies equally well to other scope exits\, for example

&nbsp;        do \{ \.\.\.; delete $foo\{bar\} \}

&nbsp;    So this commits adds the RC==1 test to S\_leave\_common\(\) too\, which handles
&nbsp;    all the non\-sub scope exits\. As well as adding a test to do\.t\, it adds an
&nbsp;    additional test to sub\.t\, since the original tests\, although they
&nbsp;    \*detected\* a non\-copied return\, didn't actually demonstrate a case where
&nbsp;    it was actually harmful\.

&nbsp;    Note that S\_leave\_common\(\) also sometimes skips on PADTMPs as well as
&nbsp;    TEMPs\, so this commit as a side\-effect also makes it copy PADTMPs unless
&nbsp;    their RC ==1\. But since their RC should in fact almost always be 1 anyway\,
&nbsp;    in practice it makes no difference\.

:100644 100644 82189bb5c188e77800176fe8cfcb80b15bcb2226 d1229af7609c41d1caa7944f8d90eb6a2b12859c M       pp\_ctl\.c
:040000 040000 95d71e14d5e47e4db9a5149492215aa45b9ad6c8 f69fbca5ed4bd5f0595f03be7deda11cca858d43 M       t
bisect run success



\*\*GDB\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ gdb \-\-args \./perl \-Ilib \-tW \-e '\{@&#8203;\{\*a&#8203;::ISA\}=undef\*a&#8203;::ISA;@&#8203;a&#8203;::ISA=0\}'
GNU gdb \(GDB\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-unknown\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from \./perl\.\.\.done\.
\(gdb\) run
Starting program&#8203;: /home/dcollins/perldebug/perl \-Ilib \-tW \-e \\\{@&#8203;\\\{\\\*a&#8203;::ISA\\\}=undef\\\*a&#8203;::ISA\\;@&#8203;a&#8203;::ISA=0\\\}
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
Use of uninitialized value in list assignment at \-e line 1\.
perl&#8203;: mg\.c&#8203;:1726&#8203;: Perl\_magic\_clearisa&#8203;: Assertion \`\(\(\(\(\_gvstash\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(\_gvstash\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_gvstash\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x00007ffff6cfa8fa in abort \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#2  0x00007ffff6cf23a7 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#3  0x00007ffff6cf2452 in \_\_assert\_fail \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#4  0x000000000057548f in Perl\_magic\_clearisa \(sv=0x0\, mg=0xabc3e0\) at mg\.c&#8203;:1724
\#5  0x0000000000575104 in Perl\_magic\_setisa \(sv=0xab20b0\, mg=0xabc3e0\) at mg\.c&#8203;:1691
\#6  0x000000000056dfa1 in Perl\_mg\_set \(sv=0xab20b0\) at mg\.c&#8203;:277
\#7  0x00000000005aeacc in Perl\_pp\_aassign \(\) at pp\_hot\.c&#8203;:1422
\#8  0x000000000055a245 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2239
\#9  0x00000000004623d3 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2517
\#10 0x00000000004619fe in perl\_run \(my\_perl=0xa9c010\) at perl\.c&#8203;:2440
\#11 0x000000000041eae0 in main \(argc=5\, argv=0x7fffffffe5f8\, env=0x7fffffffe628\)
&nbsp;    at perlmain\.c&#8203;:116
\(gdb\) f 4
\#4  0x000000000057548f in Perl\_magic\_clearisa \(sv=0x0\, mg=0xabc3e0\) at mg\.c&#8203;:1724
1724        stash = GvSTASH\(
\(gdb\) l
1719            \}
1720
1721            return 0;
1722        \}
1723
1724        stash = GvSTASH\(
1725            \(const GV \*\)mg\->mg\_obj
1726        \);
1727
1728        /\* The stash may have been detached from the symbol table\, so check its
\(gdb\) info locals
\_gvstash = 0xab2068
stash = 0xab20b0
\_\_PRETTY\_FUNCTION\_\_ = "Perl\_magic\_clearisa"


\*\*VALGRIND\*\*

No reported memory management errors\.


\*\*PERL \-V\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-V
Summary of my perl5 \(revision 5 version 25 subversion 2\) configuration&#8203;:
&nbsp;  Commit id&#8203;: c29dfc6a6c45f86648c51f961304254cc3c449b9
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=4\.5\.0\-2\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 4\.5\.0\-2\-amd64 \#1 smp debian 4\.5\.3\-2 \(2016\-05\-08\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache gcc\-6\.1 \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache gcc\-6\.1'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='6\.1\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache gcc\-6\.1'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/x86\_64\-pc\-linux\-gnu/6\.1\.0/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.22\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.22'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_OP\_PARENT PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL
&nbsp;                        USE\_64\_BIT\_ALL USE\_64\_BIT\_INT USE\_LARGE\_FILES
&nbsp;                        USE\_LOCALE USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at May 26 2016 17&#8203;:57&#8203;:37
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.2/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.2
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.2/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.2
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.1
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.24\.0
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, May 26\, 2016 at 05&#8203;:29&#8203;:21PM \-0700\, Dan Collins wrote&#8203;:
> dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-tW \-e '\{@&#8203;\{\*a&#8203;::ISA\}=undef\*a&#8203;::ISA;@&#8203;a&#8203;::ISA=0\}'
> Use of uninitialized value in list assignment at \-e line 1\.
> perl&#8203;: mg\.c&#8203;:1726&#8203;: Perl\_magic\_clearisa&#8203;: Assertion \`\(\(\(\(\_gvstash\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(\_gvstash\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_gvstash\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.
> Aborted

It's equivalent to the following&#8203;:

perl \-t run against&#8203;:

&nbsp;    undef \*a&#8203;::ISA;
&nbsp;    @&#8203;\{\*a&#8203;::ISA\}=\(\);
&nbsp;    @&#8203;a&#8203;::ISA=0

The problem is in the weak pointer from ISA magic to the GV\, i\.e\. where
the \*a&#8203;::ISA points to the GP which points to @&#8203;a&#8203;::ISA which has ISA magic
attached\, who's mg\_obj field contains a weak pointer back to \*a&#8203;::ISA\. It
has to be weak\, otherwise there would be a reference loop and leakage\.

However\, with this&#8203;: @&#8203;\{\*a&#8203;::ISA\}\, the \*a&#8203;::ISA expression is executed within
a block scope; when that scope is left\, a copy of the scope's return value
is returned \(as is done with all rvalue scope exits\)\. This copying creates
an SvTEMP GV whose GP is shared with the original \*a&#8203;::ISA GV\.
When the gp\_av slot of the temp GV is accessed\, it is empty due to the
earlier undef\, so is autovivified\. The autovivification sees that the GV's
name is 'ISA' so attaches ISA magic\, whose mg\_obj field is set to point
\(weakly\) to the temp GV copy of \*a&#8203;::ISA\.

At the next statement boundary temps are freed\, and @&#8203;a&#8203;::ISA's mg\_obj
field now points to a freed GV\. Crashes etc follow\.

I don't know how to fix this\.




\-\- 
Dave's first rule of Opera&#8203;:
If something needs saying\, say it&#8203;: don't warble it\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Dave Mitchell wrote&#8203;:
>I don't know how to fix this\.

The GP has a pointer to the interned \(\`effective'\) GV from which any
GV referencing it was cloned\.  Attaching ISA magic should follow that
pointer\.

\-zefram

**Comment by p5pRT** [comment]
### From @cpansprout

On Mon Jun 27 08&#8203;:54&#8203;:23 2016\, davem wrote&#8203;:
> It's equivalent to the following&#8203;:
> 
> perl \-t run against&#8203;:
> 
> undef \*a&#8203;::ISA;
> @&#8203;\{\*a&#8203;::ISA\}=\(\);
> @&#8203;a&#8203;::ISA=0

Why does it only happen under \-t and \-T?

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Jun 27\, 2016 at 05&#8203;:58&#8203;:15PM \-0700\, Father Chrysostomos via RT wrote&#8203;:
> On Mon Jun 27 08&#8203;:54&#8203;:23 2016\, davem wrote&#8203;:
> > It's equivalent to the following&#8203;:
> > 
> > perl \-t run against&#8203;:
> > 
> > undef \*a&#8203;::ISA;
> > @&#8203;\{\*a&#8203;::ISA\}=\(\);
> > @&#8203;a&#8203;::ISA=0
> 
> Why does it only happen under \-t and \-T?

I just checked\. In the absence of \-t\, the @&#8203;\{\*a&#8203;::ISA\} is compiled with
a scope rather than enter/leave\. Changing it to something like
@&#8203;\{my $x; \*a&#8203;::ISA\} to force full scope\, causes it to crash without the \-t\.

\-\- 
Any \[programming\] language that doesn't occasionally surprise the
novice will pay for it by continually surprising the expert\.
&nbsp;   \-\- Larry Wall

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Jun 27\, 2016 at 05&#8203;:27&#8203;:05PM \+0100\, Zefram wrote&#8203;:
> Dave Mitchell wrote&#8203;:
> >I don't know how to fix this\.
> 
> The GP has a pointer to the interned \(\`effective'\) GV from which any
> GV referencing it was cloned\.  Attaching ISA magic should follow that
> pointer\.

That won't work in a case like&#8203;:

&nbsp;    \*Bar&#8203;::ISA = \*Foo&#8203;::ISA

When the ISA array is modified\, both stashes need mro\_isa\_changed\_in\(\)
called on them\, but there's only a single GP involved\.

At the moment\, mg\_obj normally points to the ISA AV's GV\, but when there
are multiple GVs\, as in the above or \*Bar&#8203;::ISA = \\@&#8203;Foo&#8203;::ISA\, then
mg\_obj points to a non\-reified AV whose elements are the parent GVs\.

But the current scheme will \(I imagine\) fail in the case of something
like

&nbsp;    $Bar&#8203;::\{ISA\} = $Foo&#8203;::\{ISA\};

Perhaps instead of storing GV or GP pointer\(s\) in the ISA magic\,
we should store stash names \(i\.e\. a PV or an AV of PV's\)\.
Then when @&#8203;ISA is modified\, the stashes are looked up from the stash
names\.



\-\- 
Little fly\, thy summer's play my thoughtless hand
has terminated with extreme prejudice\.
&nbsp;        \(with apologies to William Blake\)

**Comment by p5pRT** [comment]
### From @cpansprout

On Tue Jun 28 02&#8203;:35&#8203;:26 2016\, davem wrote&#8203;:
> On Mon\, Jun 27\, 2016 at 05&#8203;:27&#8203;:05PM \+0100\, Zefram wrote&#8203;:
> > Dave Mitchell wrote&#8203;:
> > >I don't know how to fix this\.
> > 
> > The GP has a pointer to the interned \(\`effective'\) GV from which any
> > GV referencing it was cloned\.  Attaching ISA magic should follow that
> > pointer\.
> 
> That won't work in a case like&#8203;:
> 
>     \*Bar&#8203;::ISA = \*Foo&#8203;::ISA
> 
> When the ISA array is modified\, both stashes need mro\_isa\_changed\_in\(\)
> called on them\, but there's only a single GP involved\.
> 
> At the moment\, mg\_obj normally points to the ISA AV's GV\, but when there
> are multiple GVs\, as in the above or \*Bar&#8203;::ISA = \\@&#8203;Foo&#8203;::ISA\, then
> mg\_obj points to a non\-reified AV whose elements are the parent GVs\.
> 
> But the current scheme will \(I imagine\) fail in the case of something
> like
> 
>     $Bar&#8203;::\{ISA\} = $Foo&#8203;::\{ISA\};

It’s practically impossible for perl to track things correctly when people do direct stash assignment\.  \(That’s partly why perlmod says&#8203;:

The results of creating new symbol table entries directly or modifying any
entries that are not already typeglobs are undefined and subject to change
between releases of perl\.

\)

So as long as that case does not crash\, I think that’s fine\.


> 
> Perhaps instead of storing GV or GP pointer\(s\) in the ISA magic\,
> we should store stash names \(i\.e\. a PV or an AV of PV's\)\.
> Then when @&#8203;ISA is modified\, the stashes are looked up from the stash
> names\.

As long as things still work when stashes get effectively renamed \(Bar gets renamed in \*Foo&#8203;::=\*Bar&#8203;::\, \*Bar&#8203;::=\*Baz&#8203;::\)\.  I went to great lengths to make sure that worked \(in 5\.12\, iirc\)\, and I would hate to see it break\.

\-\- 

Father Chrysostomos
