### ISSUE TITLE
Segfault in Perl_gv_setref: 'sub U::0{}undef*U::;*U::0=sub{}'

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15368]
Migrated from [rt.perl.org#128257](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=128257) (status was 'resolved')

Searchable as RT128257$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-Dusequadmath \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers a segfault in the perl interpreter\. The testcase is the file below\. On normal builds and debug builds with \-W\, this segfaults\.

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-e 'sub U&#8203;::0\{\}undef\*U&#8203;::;\*U&#8203;::0=sub\{\}'
dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-W \-e 'sub U&#8203;::0\{\}undef\*U&#8203;::;\*U&#8203;::0=sub\{\}'
Segmentation fault

This testcase \*looks\* suspiciously like \[perl \#128254\]\, but it is rather different\. This one has nothing to do with ISA or taint mode\. It is\, however\, rather bizarre\. It only crashes under \-W\. Perhaps we're freeing something while it's still on the stack? But if this was a context stack issue\, I think it would segfault regardless of whether warnings are enabled\.

A bisect was attempted but this behavior has persisted since 5\.12\.0 at least\.

\*\*GDB\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ gdb \-\-args \./perl \-Ilib \-W \-e 'sub U&#8203;::0\{\}undef\*U&#8203;::;\*U&#8203;::0=sub\{\}'
GNU gdb \(GDB\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-unknown\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from \./perl\.\.\.done\.
\(gdb\) run
Starting program&#8203;: /home/dcollins/perldebug/perl \-Ilib \-W \-e sub\\ U&#8203;::0\\\{\\\}undef\\\*U&#8203;::\\;\\\*U&#8203;::0=sub\\\{\\\}
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.

Program received signal SIGSEGV\, Segmentation fault\.
0x00000000005dd873 in Perl\_gv\_setref \(dstr=0xab2798\, sstr=0xab2780\) at sv\.c&#8203;:4073
4073                            report\_redefined\_cv\(
\(gdb\) bt
\#0  0x00000000005dd873 in Perl\_gv\_setref \(dstr=0xab2798\, sstr=0xab2780\) at sv\.c&#8203;:4073
\#1  0x00000000005e32ef in Perl\_sv\_setsv\_flags \(dstr=0xab2798\, sstr=0xab2780\, flags=1538\)
&nbsp;    at sv\.c&#8203;:4510
\#2  0x00000000005a6dd4 in Perl\_pp\_sassign \(\) at pp\_hot\.c&#8203;:226
\#3  0x000000000055a245 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2239
\#4  0x00000000004623d3 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2517
\#5  0x00000000004619fe in perl\_run \(my\_perl=0xa9c010\) at perl\.c&#8203;:2440
\#6  0x000000000041eae0 in main \(argc=5\, argv=0x7fffffffe5f8\, env=0x7fffffffe628\)
&nbsp;    at perlmain\.c&#8203;:116
\(gdb\) l
4068                        \{
4069                            SV \* const new\_const\_sv =
4070                                CvCONST\(\(const CV \*\)sref\)
4071                                     ? cv\_const\_sv\(\(const CV \*\)sref\)
4072                                     : NULL;
4073                            report\_redefined\_cv\(
4074                               sv\_2mortal\(Perl\_newSVpvf\(aTHX\_
4075                                    "%"HEKf"&#8203;::%"HEKf\,
4076                                    HEKfARG\(
4077                                     HvNAME\_HEK\(GvSTASH\(\(const GV \*\)dstr\)\)
\(gdb\) info locals
new\_const\_sv = 0x0
cv = 0xab2738
sref = 0xab2708
\_\_PRETTY\_FUNCTION\_\_ = "Perl\_gv\_setref"
dref = 0xab2738
intro = 0
location = 0xabc090
import\_flag = 128 '\\200'
stype = 13


\*\*VALGRIND\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ valgrind \./perl \-Ilib \-W \-e 'sub U&#8203;::0\{\}undef\*U&#8203;::;\*U&#8203;::0=sub\{\}'
==47187== Memcheck\, a memory error detector
==47187== Copyright \(C\) 2002\-2015\, and GNU GPL'd\, by Julian Seward et al\.
==47187== Using Valgrind\-3\.11\.0 and LibVEX; rerun with \-h for copyright info
==47187== Command&#8203;: \./perl \-Ilib \-W \-e sub\\ U&#8203;::0\{\}undef\*U&#8203;::;\*U&#8203;::0=sub\{\}
==47187==
==47187== Invalid read of size 4
==47187==    at 0x5DD873&#8203;: Perl\_gv\_setref \(sv\.c&#8203;:4073\)
==47187==    by 0x5E32EE&#8203;: Perl\_sv\_setsv\_flags \(sv\.c&#8203;:4510\)
==47187==    by 0x5A6DD3&#8203;: Perl\_pp\_sassign \(pp\_hot\.c&#8203;:226\)
==47187==    by 0x55A244&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2239\)
==47187==    by 0x4623D2&#8203;: S\_run\_body \(perl\.c&#8203;:2517\)
==47187==    by 0x4619FD&#8203;: perl\_run \(perl\.c&#8203;:2440\)
==47187==    by 0x41EADF&#8203;: main \(perlmain\.c&#8203;:116\)
==47187==  Address 0xc is not stack'd\, malloc'd or \(recently\) free'd
==47187==
==47187==
==47187== Process terminating with default action of signal 11 \(SIGSEGV\)
==47187==  Access not within mapped region at address 0xC
==47187==    at 0x5DD873&#8203;: Perl\_gv\_setref \(sv\.c&#8203;:4073\)
==47187==    by 0x5E32EE&#8203;: Perl\_sv\_setsv\_flags \(sv\.c&#8203;:4510\)
==47187==    by 0x5A6DD3&#8203;: Perl\_pp\_sassign \(pp\_hot\.c&#8203;:226\)
==47187==    by 0x55A244&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2239\)
==47187==    by 0x4623D2&#8203;: S\_run\_body \(perl\.c&#8203;:2517\)
==47187==    by 0x4619FD&#8203;: perl\_run \(perl\.c&#8203;:2440\)
==47187==    by 0x41EADF&#8203;: main \(perlmain\.c&#8203;:116\)
==47187==  If you believe this happened as a result of a stack
==47187==  overflow in your program's main thread \(unlikely but
==47187==  possible\)\, you can try to increase the size of the
==47187==  main thread stack using the \-\-main\-stacksize= flag\.
==47187==  The main thread stack size used in this run was 8388608\.
==47187==
==47187== HEAP SUMMARY&#8203;:
==47187==     in use at exit&#8203;: 112\,125 bytes in 569 blocks
==47187==   total heap usage&#8203;: 696 allocs\, 127 frees\, 132\,072 bytes allocated
==47187==
==47187== LEAK SUMMARY&#8203;:
==47187==    definitely lost&#8203;: 192 bytes in 1 blocks
==47187==    indirectly lost&#8203;: 2\,016 bytes in 22 blocks
==47187==      possibly lost&#8203;: 1\,024 bytes in 2 blocks
==47187==    still reachable&#8203;: 108\,893 bytes in 544 blocks
==47187==         suppressed&#8203;: 0 bytes in 0 blocks
==47187== Rerun with \-\-leak\-check=full to see details of leaked memory
==47187==
==47187== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==47187== ERROR SUMMARY&#8203;: 1 errors from 1 contexts \(suppressed&#8203;: 0 from 0\)
Segmentation fault


\*\*PERL \-V\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-V
Summary of my perl5 \(revision 5 version 25 subversion 2\) configuration&#8203;:
&nbsp;  Commit id&#8203;: c29dfc6a6c45f86648c51f961304254cc3c449b9
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=4\.5\.0\-2\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 4\.5\.0\-2\-amd64 \#1 smp debian 4\.5\.3\-2 \(2016\-05\-08\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache gcc\-6\.1 \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache gcc\-6\.1'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='6\.1\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache gcc\-6\.1'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/x86\_64\-pc\-linux\-gnu/6\.1\.0/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.22\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.22'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_OP\_PARENT PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL
&nbsp;                        USE\_64\_BIT\_ALL USE\_64\_BIT\_INT USE\_LARGE\_FILES
&nbsp;                        USE\_LOCALE USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at May 26 2016 17&#8203;:57&#8203;:37
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.2/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.2
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.2/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.2
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.1
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.24\.0
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, May 26\, 2016 at 06&#8203;:29&#8203;:06PM \-0700\, Dan Collins wrote&#8203;:
> dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-W \-e 'sub U&#8203;::0\{\}undef\*U&#8203;::;\*U&#8203;::0=sub\{\}'
> Segmentation fault

Fixed with the following commit&#8203;:

&nbsp;    commit fc0fe26a7d286480c1bb25f57e469ece575bb68d
&nbsp;    Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
&nbsp;    AuthorDate&#8203;: Thu Jul 7 17&#8203;:03&#8203;:29 2016 \+0100
&nbsp;    Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
&nbsp;    CommitDate&#8203;: Thu Jul 7 17&#8203;:06&#8203;:58 2016 \+0100

&nbsp;    SEGV in "Subroutine redefined" warning
&nbsp;    
&nbsp;    RT \#128257
&nbsp;    
&nbsp;    The following SEGVed&#8203;:
&nbsp;    
&nbsp;        sub P&#8203;::f\{\}
&nbsp;        undef \*P&#8203;::;
&nbsp;        \*P&#8203;::f =sub\{\};
&nbsp;    
&nbsp;    due to the code which generates the "Subroutine STASH&#8203;::NAME redefined"
&nbsp;    warning assuming that the GV always has a stash\. Make it so that if it
&nbsp;    hasn't\, the message changes to  "Subroutine NAME redefined" rather than
&nbsp;    just crashing\.


\-\- 
No man treats a motor car as foolishly as he treats another human being\.
When the car will not go\, he does not attribute its annoying behaviour to
sin\, he does not say\, You are a wicked motorcar\, and I shall not give you
any more petrol until you go\. He attempts to find out what is wrong and
set it right\.
&nbsp;    \-\- Bertrand Russell\,
&nbsp;       Has Religion Made Useful Contributions to Civilization?

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
