### ISSUE TITLE
Assert fail in S_find_uninit_var (via Perl_pp_multideref) without other symptoms: $ISA[0][0]

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15364]
Migrated from [rt.perl.org#128253](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=128253) (status was 'resolved')

Searchable as RT128253$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-Dusequadmath \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers an assert fail in debug buids of the perl interpreter\. The testcase is the file below\. On normal builds\, this runs normally \(albeit with an expected warning\)\. On debug builds\, this returns an assert fail\.

dcollins@&#8203;nightshade64&#8203;:\~/perl$ \./perl \-Ilib \-W \-e '$ISA\[0\]\[0\]'
Useless use of array element in void context at \-e line 1\.
Use of uninitialized value in array element at \-e line 1\.
\*\*\*\*100 additional copies of the preceding line trimmed\*\*\*\*
Recursive inheritance detected in package 'main' at \-e line 1\.

dcollins@&#8203;nightshade64&#8203;:\~/perl$ cd \.\./perldebug/
dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-e '$ISA\[0\]\[0\]'
Recursive inheritance detected in package 'main' at \-e line 1\.

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-W \-e '$ISA\[0\]\[0\]'
Useless use of array element in void context at \-e line 1\.
perl&#8203;: sv\.c&#8203;:16093&#8203;: S\_find\_uninit\_var&#8203;: Assertion \`is\_hv' failed\.
Aborted


Debugging tool output is below\. A git bisect was performed and reported the following\.

fedf30e1c349130b23648c022f5f3cb4ad7928f3 is the first bad commit
commit fedf30e1c349130b23648c022f5f3cb4ad7928f3
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Fri Oct 24 16&#8203;:26&#8203;:38 2014 \+0100

&nbsp;    Add OP\_MULTIDEREF

&nbsp;    This op is an optimisation for any series of one or more array or hash
&nbsp;    lookups and dereferences\, where the key/index is a simple constant or
&nbsp;    package/lexical variable\. If the first\-level lookup is of a simple
&nbsp;    array/hash variable or scalar ref\, then that is included in the op too\.

&nbsp;    So all of the following are replaced with a single op&#8203;:

&nbsp;        $h\{foo\}
&nbsp;        $a\[$i\]
&nbsp;        $a\[5\]\[$k\]\[$i\]
&nbsp;        $r\->\{$k\}
&nbsp;        local $a\[0\]\[$i\]
&nbsp;        exists $a\[$i\]\{$k\}
&nbsp;        delete $h\{foo\}

&nbsp;    while these aren't&#8203;:

&nbsp;        $a\[0\]       already handled by OP\_AELEMFAST
&nbsp;        $a\[$x\+1\]    not a simple index

&nbsp;    and these are partially replaced&#8203;:

&nbsp;        \(expr\)\->\[0\]\{$k\}   the bit following \(expr\) is replaced
&nbsp;        $h\{foo\}\[$x\+1\]\[0\]  the first and third lookups are each done with
&nbsp;                          a multideref op\, while the $x\+1 expression and
&nbsp;                          middle lookup are done by existing add\, aelem etc
&nbsp;                          ops\.

&nbsp;    Up until now\, aggregate dereferencing has been very heavyweight in ops; for
&nbsp;    example\, $r\->\[0\]\{$x\} is compiled as&#8203;:

&nbsp;        gv\[\*r\] s
&nbsp;        rv2sv sKM/DREFAV\,1
&nbsp;        rv2av\[t2\] sKR/1
&nbsp;        const\[IV 0\] s
&nbsp;        aelem sKM/DREFHV\,2
&nbsp;        rv2hv sKR/1
&nbsp;        gvsv\[\*x\] s
&nbsp;        helem vK/2

&nbsp;    When executing this\, in addition to the actual calls to av\_fetch\(\) and
&nbsp;    hv\_fetch\(\)\, there is a lot of overhead of pushing SVs on and off the
&nbsp;    stack\, and calling lots of little pp\(\) functions from the runops loop
&nbsp;    \(each with its potential indirect branch miss\)\.

&nbsp;    The multideref op avoids that by running all the code in a loop in a
&nbsp;    switch statement\. It makes use of the new UNOP\_AUX type to hold an array
&nbsp;    of

&nbsp;        typedef union  \{
&nbsp;            PADOFFSET pad\_offset;
&nbsp;            SV        \*sv;
&nbsp;            IV        iv;
&nbsp;            UV        uv;
&nbsp;        \} UNOP\_AUX\_item;

&nbsp;    In something like $a\[7\]\[$i\]\{foo\}\, the GVs or pad offsets for @&#8203;a and $i are
&nbsp;    stored as items in the array\, along with a pointer to a const SV holding
&nbsp;    'foo'\, and the UV 7 is stored directly\. Along with this\, some UVs are used
&nbsp;    to store a sequence of actions \(several actions are squeezed into a single
&nbsp;    UV\)\.

&nbsp;    Then the main body of pp\_multideref is a big while loop round a switch\,
&nbsp;    which reads actions and values from the AUX array\. The two big branches in
&nbsp;    the switch are ones that are affectively unrolled \(/DREFAV\, rv2av\, aelem\)
&nbsp;    and \(/DREFHV\, rv2hv\, helem\) triplets\. The other branches are various entry
&nbsp;    points that handle retrieving the different types of initial value; for
&nbsp;    example 'my %h; $h\{foo\}' needs to get %h from the pad\, while '\(expr\)\->\{foo\}'
&nbsp;    needs to pop expr off the stack\.

&nbsp;    Note that there is a slight complication with /DEREF; in the example above
&nbsp;    of $r\->\[0\]\{$x\}\, the aelem op is actually

&nbsp;        aelem sKM/DREFHV\,2

&nbsp;    which means that the aelem\, after having retrieved a \(possibly undef\)
&nbsp;    value from the array\, is responsible for autovivifying it into a hash\,
&nbsp;    ready for the next op\. Similarly\, the rv2sv that retrieves $r from the
&nbsp;    typeglob is responsible for autovivifying it into an AV\. This action
&nbsp;    of doing the next op's work for it complicates matters somewhat\. Within
&nbsp;    pp\_multideref\, the autovivification action is instead included as the
&nbsp;    first step of the current action\.

&nbsp;    In terms of benchmarking with Porting/bench\.pl\, a simple lexical
&nbsp;    $a\[$i\]\[$j\] shows a reduction of approx 40% in numbers of instructions
&nbsp;    executed\, while $r\->\[0\]\[0\]\[0\] uses 54% fewer\. The speed\-up for hash
&nbsp;    accesses is relatively more modest\, since the actual hash lookup \(i\.e\.
&nbsp;    hv\_fetch\(\)\) is more expensive than an array lookup\. A lexical $h\{foo\}
&nbsp;    uses 10% fewer\, while $r\->\{foo\}\{bar\}\{baz\} uses 34% fewer instructions\.

&nbsp;    Overall\,
&nbsp;            bench\.pl \-\-tests='/expr&#8203;::\(array|hash\)/' \.\.\.
&nbsp;    gives&#8203;:
&nbsp;                  PRE   POST
&nbsp;               \-\-\-\-\-\- \-\-\-\-\-\-

&nbsp;            Ir 100\.00 145\.00
&nbsp;            Dr 100\.00 165\.30
&nbsp;            Dw 100\.00 175\.74
&nbsp;          COND 100\.00 132\.02
&nbsp;           IND 100\.00 171\.11

&nbsp;        COND\_m 100\.00 127\.65
&nbsp;         IND\_m 100\.00 203\.90

&nbsp;    with cache misses unchanged at 100%\.

&nbsp;    In general\, the more lookups done\, the bigger the proportionate saving\.

:100644 100644 4775d8ee963455f92943ec5801667f52c27d4cc8 7d04e1f4a95ce2052bf6d2edf5bb37f626fa81bb M       MANIFEST
:040000 040000 ead841309200671a901d9eba96adcd7b99dc8c18 6d89fbbb6a0630992a64357e75a117adc80db012 M       Porting
:040000 040000 e381210f04b7f4f650269461bd13281cdf504208 689f04448c02694a9edd98b34c9c21afee60a434 M       dist
:100644 100644 daeedf493f0295b47fdd157659e856e0f62fd9c1 9abfbb12bc89dfa97d544956b9c65846a3e79b4c M       dump\.c
:100644 100644 26d893d13d9147f791127676fa7970f8bdb04d34 c7b283b9f663ccf27f1b8608861079acd1170c50 M       embed\.fnc
:100644 100644 7108b3e331a35a9441f81cefb18988cf8a1c50ce 02d25be1cbaf1a81d95e97f8f6a59d4a3f280021 M       embed\.h
:100644 100644 9e4a910a57e54c8e8caa5c46b2e6d712e1d397f3 32a8b9b32710211bb54be950d275df4a707d649d M       embedvar\.h
:040000 040000 78f77af5676708a3d6d481c1984bebb46dd4cf40 e2e7280b7c1e47936223dbb0e100f54ff9bcff2c M       ext
:100644 100644 39eac06454ad06aee3598cc935d2c3553d84fc12 ffb1172c9f1c7eac9659d1421b77749e995874b8 M       intrpvar\.h
:040000 040000 a18a0cc712b77b7f80c32476b1d6b2e6df1f71d3 e95253c1697d54f421f58ba92a7885f4ffc6bddb M       lib
:100644 100644 f34e9326f7bfe0f99ef0f3d83528b1778b07baed 16ebd4244b24ffcd677999b219be3160b9d8f9ce M       op\.c
:100644 100644 61a382fb7614ac6f86320af4afb6785aa9963c55 9e60beb64dbd900c59eebac2fbaf6f45c6ab1728 M       op\.h
:100644 100644 e67318ffc82e60e765e8a16e5abb59037dd4119f 4266c49cf6d1c548842aebdf7e8c0f36cb084043 M       opcode\.h
:100644 100644 dce44f19e98b9ca7953da952300a810a26c25df1 1d259a15ddfb4a640d1e0c1cea5dfad469d65a01 M       opnames\.h
:100644 100644 2a77522c5efda6db3bb0b9413123c556193d61c5 ac674c1aa95c304715611c37b7f1f3f8f5923090 M       perl\.h
:100644 100644 97ad595119fc580b261a29e972b510ebf1f2efbb 67729994634c4e8d08c955f7c4b6797012f44451 M       pp\.c
:100644 100644 35493eb1b48215c53225ef53a21079410186941f 24bf8e9086954fb901ace8b99ce1854fb9d8fbfb M       pp\_hot\.c
:100644 100644 6959357dd25d306192727b5a9625736aaf8c8e26 074f4ab8a36df0d182883178737a1b3f8c4040a1 M       pp\_proto\.h
:100644 100644 eb2ba5a9adf0f5fe2853dd1fa7ee967eb6d4c30b f2be12dff5e07838dd3f840580834e041ab41c02 M       proto\.h
:040000 040000 bc56c3274ae52f12fa3efe24b8a5b353fdb4d63b 86365afc8cb53ffbfecb4c4c597d9d830b0caedd M       regen
:100644 100644 5a73d9565ce71cf33bd3b01e1dcb486927c22d33 b08899fc9992a106cab017c02e21a1bc3c6abdb8 M       sv\.c
:040000 040000 4243a5a21c1c1f030a71cd0988c01286e5e99b14 7b899063862060c43f47a069fa094dd30517fdfe M       t
bisect run success




\*\*GDB\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ gdb \-\-args \./perl \-Ilib \-W \-e '\(\($ISA\[0\]\[0\]\)\)'
GNU gdb \(GDB\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-unknown\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from \./perl\.\.\.done\.
\(gdb\) run
Starting program&#8203;: /home/dcollins/perldebug/perl \-Ilib \-W \-e \\\(\\\(\\$ISA\\\[0\\\]\\\[0\\\]\\\)\\\)
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
Useless use of array element in void context at \-e line 1\.
perl&#8203;: sv\.c&#8203;:16093&#8203;: S\_find\_uninit\_var&#8203;: Assertion \`is\_hv' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x00007ffff6cfa8fa in abort \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#2  0x00007ffff6cf23a7 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#3  0x00007ffff6cf2452 in \_\_assert\_fail \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#4  0x0000000000618df3 in S\_find\_uninit\_var \(obase=0xabc100\, uninit\_sv=0xa9e048\, match=false\,
&nbsp;    desc\_p=0x7fffffffd518\) at sv\.c&#8203;:16093
\#5  0x0000000000619c9d in Perl\_report\_uninit \(uninit\_sv=0xa9e048\) at sv\.c&#8203;:16392
\#6  0x00000000005d2003 in Perl\_sv\_2pv\_flags \(sv=0xa9e048\, lp=0x7fffffffd890\, flags=34\)
&nbsp;    at sv\.c&#8203;:3179
\#7  0x00000000005945b2 in Perl\_hv\_common \(hv=0xa9dc88\, keysv=0xa9e048\, key=0x0\, klen=0\,
&nbsp;    flags=0\, action=0\, val=0x0\, hash=0\) at hv\.c&#8203;:385
\#8  0x000000000047aaa4 in S\_gv\_stashsvpvn\_cached \(namesv=0xa9e048\, name=0x0\, namelen=0\,
&nbsp;    flags=0\) at gv\.c&#8203;:1453
\#9  0x000000000047ae23 in Perl\_gv\_stashsv \(sv=0xa9e048\, flags=0\) at gv\.c&#8203;:1505
\#10 0x0000000000581f7b in S\_mro\_get\_linear\_isa\_dfs \(stash=0xa9dec8\, level=0\) at mro\_core\.c&#8203;:280
\#11 0x000000000058269e in Perl\_mro\_get\_linear\_isa \(stash=0xa9dec8\) at mro\_core\.c&#8203;:413
\#12 0x000000000058428f in Perl\_mro\_isa\_changed\_in \(stash=0xa9dec8\) at mro\_core\.c&#8203;:652
\#13 0x0000000000575649 in Perl\_magic\_clearisa \(sv=0x0\, mg=0xabbc90\) at mg\.c&#8203;:1731
\#14 0x0000000000575104 in Perl\_magic\_setisa \(sv=0xab2728\, mg=0xabbc90\) at mg\.c&#8203;:1691
\#15 0x000000000056dfa1 in Perl\_mg\_set \(sv=0xab2728\) at mg\.c&#8203;:277
\#16 0x00000000005a2715 in Perl\_av\_store \(av=0xab2728\, key=0\, val=0xa9e048\) at av\.c&#8203;:381
\#17 0x00000000005a2216 in Perl\_av\_fetch \(av=0xab2728\, key=0\, lval=1\) at av\.c&#8203;:279
\#18 0x00000000005b5c6d in Perl\_pp\_multideref \(\) at pp\_hot\.c&#8203;:2346
\#19 0x000000000055a245 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2239
\#20 0x00000000004623d3 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2517
\#21 0x00000000004619fe in perl\_run \(my\_perl=0xa9c010\) at perl\.c&#8203;:2440
\#22 0x000000000041eae0 in main \(argc=5\, argv=0x7fffffffe608\, env=0x7fffffffe638\)
&nbsp;    at perlmain\.c&#8203;:116
\(gdb\) f 4
\#4  0x0000000000618df3 in S\_find\_uninit\_var \(obase=0xabc100\, uninit\_sv=0xa9e048\, match=false\,
&nbsp;    desc\_p=0x7fffffffd518\) at sv\.c&#8203;:16093
16093               assert\(is\_hv\); /\* AV index is an IV and can't be undef \*/
\(gdb\) l
16088               if \(index\_gv\)
16089                   return varname\(index\_gv\, '$'\, 0\, NULL\, 0\, FUV\_SUBSCRIPT\_NONE\);
16090               if \(index\_targ\)
16091                   return varname\(NULL\, '$'\, index\_targ\,
16092                                       NULL\, 0\, FUV\_SUBSCRIPT\_NONE\);
16093               assert\(is\_hv\); /\* AV index is an IV and can't be undef \*/
16094               /\* can a const HV index ever be undef? \*/
16095               return NULL;
16096           \}
16097
\(gdb\) info locals
agg\_targ = 0
index\_type = 16
items = 0xaacbf0
last = 0xaacbd8
is\_hv = false
agg\_gv = 0x0
index\_targ = 0
index\_gv = 0x0
index\_const\_iv = 0
actions = 84
index\_const\_sv = 0x0
depth = 2
sv = 0x55ba9e \<Perl\_safesysrealloc\+131>
gv = 0x48
o = 0xaacb80
o2 = 0x1a
kid = 0xaacb80
\_\_PRETTY\_FUNCTION\_\_ = "S\_find\_uninit\_var"


\*\*VALGRIND\*\*

No reported memory management errors\.


\*\*PERL \-V\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-V
Summary of my perl5 \(revision 5 version 25 subversion 2\) configuration&#8203;:
&nbsp;  Commit id&#8203;: c29dfc6a6c45f86648c51f961304254cc3c449b9
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=4\.5\.0\-2\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 4\.5\.0\-2\-amd64 \#1 smp debian 4\.5\.3\-2 \(2016\-05\-08\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache gcc\-6\.1 \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache gcc\-6\.1'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='6\.1\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache gcc\-6\.1'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/x86\_64\-pc\-linux\-gnu/6\.1\.0/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.22\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.22'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_OP\_PARENT PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL
&nbsp;                        USE\_64\_BIT\_ALL USE\_64\_BIT\_INT USE\_LARGE\_FILES
&nbsp;                        USE\_LOCALE USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at May 26 2016 17&#8203;:57&#8203;:37
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.2/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.2
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.2/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.2
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.1
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.24\.0
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, May 26\, 2016 at 05&#8203;:08&#8203;:31PM \-0700\, Dan Collins wrote&#8203;:
> dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-W \-e '$ISA\[0\]\[0\]'
> Useless use of array element in void context at \-e line 1\.
> perl&#8203;: sv\.c&#8203;:16093&#8203;: S\_find\_uninit\_var&#8203;: Assertion \`is\_hv' failed\.
> Aborted

Fixed by the below&#8203;:

commit 6fe82bd6d07db28c9792126ff851a29fe013401c
Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
AuthorDate&#8203;: Thu Jul 7 16&#8203;:24&#8203;:41 2016 \+0100
Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
CommitDate&#8203;: Thu Jul 7 16&#8203;:24&#8203;:41 2016 \+0100

&nbsp;    handle magic in multideref "unit val" var names
&nbsp;    
&nbsp;    \[perl \#128253\] Assert fail in S\_find\_uninit\_var
&nbsp;    
&nbsp;        $ perl5240 \-we'$ISA\[0\]\[0\]'
&nbsp;        Useless use of array element in void context at \-e line 1\.
&nbsp;        perl5240&#8203;: sv\.c&#8203;:16078&#8203;: S\_find\_uninit\_var&#8203;: Assertion \`is\_hv' failed\.
&nbsp;    
&nbsp;    The code in find\_uninit\_var\(\) which looks for a variable name associated
&nbsp;    with an uninitialized value assumed\, in the OP\_MULTIDEREF branch\, that the
&nbsp;    value was either an index if the op was top\-level \($foo\[$uninit\]\)\, or an
&nbsp;    array/hash element otherwise \(1\+$foo\[\.\.\.\]\)\.
&nbsp;    
&nbsp;    It turns out here's a third possibility&#8203;: magic\. In $ISA\[0\]\[0\]\, the first
&nbsp;    array lookup is in lval context\, so it initially autovivifies to undef\.
&nbsp;    Normally it would shortly afterwards be upgraded to a ref to an empty AV\,
&nbsp;    but first ISA set magic for @&#8203;ISA is invoked\. This ends up scanning @&#8203;ISA
&nbsp;    and finds an uninit value which it tries to use as a key into the stash
&nbsp;    cache\, triggering an ununit value warning\.
&nbsp;    
&nbsp;    This commit expands the OP\_MULTIDEREF code in find\_uninit\_var\(\) to handle
&nbsp;    this third possibility \- chiefly by not returning a variable name unless
&nbsp;    the index var is the same SV as the uninit value\. As well as fixing the
&nbsp;    assert failure in this ticket\, it also stops printing an incorrect index in
&nbsp;    code like this&#8203;:
&nbsp;    
&nbsp;        $ perl \-we'my $i = 0; $ISA\[$i\] = 1'
&nbsp;    
&nbsp;    before&#8203;:
&nbsp;    
&nbsp;        \.\.\.\.
&nbsp;        Use of uninitialized value $i in array element at \-e line 1\.
&nbsp;        Use of uninitialized value $i in array element at \-e line 1\.
&nbsp;        Recursive inheritance detected in package 'main' at \-e line 1\.
&nbsp;    
&nbsp;    after&#8203;:
&nbsp;    
&nbsp;        \.\.\.\.
&nbsp;        Use of uninitialized value in array element at \-e line 1\.
&nbsp;        Use of uninitialized value in array element at \-e line 1\.
&nbsp;        Recursive inheritance detected in package 'main' at \-e line 1\.
&nbsp;    
&nbsp;    @&#8203;ISA magic still has recursion issues with undef values\, as can be seen
&nbsp;    above\. I don't address those issues here\. Because of that\, I haven't
&nbsp;    been able to add tests\.


\-\- 
Any \[programming\] language that doesn't occasionally surprise the
novice will pay for it by continually surprising the expert\.
&nbsp;   \-\- Larry Wall

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
