### ISSUE TITLE
Assert fail in Perl_sv_2pv_flags: 'sub MODIFY_HASH_ATTRIBUTES{}my(%o):s==0'

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15371]
Migrated from [rt.perl.org#128261](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=128261) (status was 'open')

Searchable as RT128261$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-Dusequadmath \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers an assert fail in debug buids of the perl interpreter\. The testcase is the file below\. On normal builds\, this runs normally \(albeit with an expected warning\)\. On debug builds\, this returns an assert fail\.


dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-e 'sub MODIFY\_HASH\_ATTRIBUTES\{\}my\(%o\)&#8203;:s==0'
perl&#8203;: sv\.c&#8203;:2595&#8203;: Perl\_sv\_2nv\_flags&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= SVt\_PVAV && \(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= SVt\_PVHV && \(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= SVt\_PVFM' failed\.
Aborted


This seems to be the "hash equivalent" of \[perl \#128183\]?


Debugging tool output is below\. A git bisect was performed and reported the following\, which is the commit where the assert was initially added\.

217f6fa330a187be32a68556507e3165b8747f55 is the first bad commit
commit 217f6fa330a187be32a68556507e3165b8747f55
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Fri Jul 19 08&#8203;:51&#8203;:47 2013 \-0700

&nbsp;    sv\.c&#8203;: Assert that sv\_\[ivp\]v are not passed aggregates

&nbsp;    The lack of assertions can hide bugs\.  See 32a609747bffb for instance

:100644 100644 3ac0a2bce83bc12406be1fa22acefa8f8a2014c7 daa87f00081d96c8d15f94f02c32cd85e8af0266 M       sv\.c
bisect run success



\*\*GDB\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ gdb \-\-args \./perl \-Ilib \-e 'sub MODIFY\_HASH\_ATTRIBUTES\{\}my\(%o\)&#8203;:s==0'
GNU gdb \(GDB\) 7\.10
Copyright \(C\) 2015 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-unknown\-linux\-gnu"\.
Type "show configuration" for configuration details\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.
Find the GDB manual and other documentation resources online at&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/documentation/>\.
For help\, type "help"\.
Type "apropos word" to search for commands related to "word"\.\.\.
Reading symbols from \./perl\.\.\.done\.
\(gdb\) run
Starting program&#8203;: /home/dcollins/perldebug/perl \-Ilib \-e sub\\ MODIFY\_HASH\_ATTRIBUTES\\\{\\\}my\\\(%o\\\)&#8203;:s==0
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
perl&#8203;: sv\.c&#8203;:2595&#8203;: Perl\_sv\_2nv\_flags&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= SVt\_PVAV && \(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= SVt\_PVHV && \(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= SVt\_PVFM' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x00007ffff6cfa8fa in abort \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#2  0x00007ffff6cf23a7 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#3  0x00007ffff6cf2452 in \_\_assert\_fail \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#4  0x00000000005cd9fc in Perl\_sv\_2nv\_flags \(sv=0xab2730\, flags=0\) at sv\.c&#8203;:2594
\#5  0x000000000062c724 in Perl\_do\_ncmp \(left=0xab2730\, right=0xab27a8\) at pp\.c&#8203;:2281
\#6  0x00000000005a933d in Perl\_pp\_eq \(\) at pp\_hot\.c&#8203;:464
\#7  0x000000000055a245 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2239
\#8  0x00000000004623d3 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2517
\#9  0x00000000004619fe in perl\_run \(my\_perl=0xa9c010\) at perl\.c&#8203;:2440
\#10 0x000000000041eae0 in main \(argc=4\, argv=0x7fffffffe608\, env=0x7fffffffe630\)
&nbsp;    at perlmain\.c&#8203;:116
\(gdb\) f 4
\#4  0x00000000005cd9fc in Perl\_sv\_2nv\_flags \(sv=0xab2730\, flags=0\) at sv\.c&#8203;:2594
2594        assert \(SvTYPE\(sv\) \!= SVt\_PVAV && SvTYPE\(sv\) \!= SVt\_PVHV
\(gdb\) l
2589    NV
2590    Perl\_sv\_2nv\_flags\(pTHX\_ SV \*const sv\, const I32 flags\)
2591    \{
2592        PERL\_ARGS\_ASSERT\_SV\_2NV\_FLAGS;
2593
2594        assert \(SvTYPE\(sv\) \!= SVt\_PVAV && SvTYPE\(sv\) \!= SVt\_PVHV
2595             && SvTYPE\(sv\) \!= SVt\_PVFM\);
2596        if \(SvGMAGICAL\(sv\) || SvVALID\(sv\) || isREGEXP\(sv\)\) \{
2597            /\* FBMs use the space for SvIVX and SvNVX for other purposes\, and use
2598               the same flag bit as SVf\_IVisUV\, so must not let them cache NVs\.
\(gdb\) info locals
\_\_PRETTY\_FUNCTION\_\_ = "Perl\_sv\_2nv\_flags"
\(gdb\) q


\*\*VALGRIND\*\*

No reported memory management errors\.


\*\*PERL \-V\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-V
Summary of my perl5 \(revision 5 version 25 subversion 2\) configuration&#8203;:
&nbsp;  Commit id&#8203;: c29dfc6a6c45f86648c51f961304254cc3c449b9
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=4\.5\.0\-2\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 4\.5\.0\-2\-amd64 \#1 smp debian 4\.5\.3\-2 \(2016\-05\-08\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache gcc\-6\.1 \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache gcc\-6\.1'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='6\.1\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache gcc\-6\.1'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/x86\_64\-pc\-linux\-gnu/6\.1\.0/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.22\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.22'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_OP\_PARENT PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL
&nbsp;                        USE\_64\_BIT\_ALL USE\_64\_BIT\_INT USE\_LARGE\_FILES
&nbsp;                        USE\_LOCALE USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at May 26 2016 17&#8203;:57&#8203;:37
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.2/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.2
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.2/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.2
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.1
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.24\.0
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @cpansprout

On Thu May 26 18&#8203;:57&#8203;:12 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-e 'sub
> MODIFY\_HASH\_ATTRIBUTES\{\}my\(%o\)&#8203;:s==0'
> perl&#8203;: sv\.c&#8203;:2595&#8203;: Perl\_sv\_2nv\_flags&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\-
> >sv\_flags & 0xff\)\) \!= SVt\_PVAV && \(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!=
> SVt\_PVHV && \(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= SVt\_PVFM' failed\.
> Aborted
> 
> 
> This seems to be the "hash equivalent" of \[perl \#128183\]?

No\, \#128183 has a backslash before the my\(\) and an assignment operator after it\.  It has to do with refaliasing not playing nicely with attributes\.

This bug is different&#8203;:

$ \./perl \-Ilib \-MO=Concise \-e 'my\(%o\)&#8203;:s==0'
g  \<@&#8203;> leave\[1 ref\] vKP/REFC \->\(end\)
1     \<0> enter \->2
2     \<;> nextstate\(main 64 \-e&#8203;:1\) v&#8203;:\{ \->3
f     \<2> eq vK/2 \->g
d        \<@&#8203;> list sK \->e
3           \<0> pushmark v \->4
4           \<0> padhv\[%o&#8203;:64\,65\] vPM/LVINTRO \->5
c           \<1> entersub\[t2\] vKS\*/TARG \->d
5              \<0> pushmark s \->6
6              \<$> const\[PV "attributes"\] sM \->7
7              \<$> const\[PV "main"\] sM \->8
9              \<1> srefgen sKM/1 \->a
\-                 \<1> ex\-list lKRM \->9
8                    \<0> padsv\[%o&#8203;:64\,65\] sRM \->9
a              \<$> const\[PV "s"\] sM \->b
b              \<\.> method\_named\[PV "import"\] \->c
e        \<$> const\[IV 0\] s \->f
\-e syntax OK
$ \./perl \-Ilib \-MO=Concise \-e 'my\(%o\)==0'
6  \<@&#8203;> leave\[1 ref\] vKP/REFC \->\(end\)
1     \<0> enter \->2
2     \<;> nextstate\(main 1 \-e&#8203;:1\) v&#8203;:\{ \->3
5     \<2> eq vK/2 \->6
3        \<0> padhv\[%o&#8203;:1\,2\] sPM/LVINTRO \->4
4        \<$> const\[IV 0\] s \->5
\-e syntax OK

When we have an attribute\, the padhv op is in void context \(the v in vPM/LVINTRO\)\, whereas it should be in scalar context\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From zefram@fysh.org

The test case doesn't assert for me on blead\, but I still see the padhv
being in void context\.  I see some related misbehaviour\, anywhere that
an attributed hash is put into scalar context&#8203;:

$ perl \-lwe 'sub MODIFY\_HASH\_ATTRIBUTES\{\} print scalar\(my%o\) // "undef"'
0
$ perl \-lwe 'sub MODIFY\_HASH\_ATTRIBUTES\{\} print scalar\(my%p&#8203;:S\) // "undef"'
undef

There's also inconsistent behaviour in scalar lvalue context&#8203;:

$ perl \-lwe 'sub MODIFY\_HASH\_ATTRIBUTES\{\} \(my%o\) \.= 1'
Can't modify private hash in concatenation \(\.\) or string at \-e line 1\, at EOF
Execution of \-e aborted due to compilation errors\.
$ perl \-lwe 'sub MODIFY\_HASH\_ATTRIBUTES\{\} \(my%p&#8203;:S\) \.= 1'
Modification of a read\-only value attempted at \-e line 1\.

In fact anything that needs to understand that the hash declaration is
a hash declaration gets into trouble&#8203;:

$ perl \-lwe 'sub f \(\\%\) \{ print "ok" \} f\(my %o\)'
ok
$ perl \-lwe 'sub f \(\\%\) \{ print "ok" \} f\(my %p&#8203;:S\)'
Too many arguments for main&#8203;::f at \-e line 1\, near "&#8203;:S\)
"
Execution of \-e aborted due to compilation errors\.
$ perl \-lwe 'sub f \(\\%\) \{ print "ok" \} f\(\(my %p&#8203;:S\)\)'
Type of arg 1 to main&#8203;::f must be hash \(not list\) at \-e line 1\, near "\)\)
"
Execution of \-e aborted due to compilation errors\.

The problem is the dubious way in which an optree is constructed to apply
attributes at runtime\.  I'm sure at the time it seemed like a neat hack
to stick the object and its attribute\-applying expression into a list\,
but it's turned out to not be up to the task\.  Identifying an attributed
declaration in this form is tricky\, and easily omitted from places that
need to do it\.  It's one of the issues making \[perl \#114932\] so tricky\.

I think the optrees for declarations with attributes should have a
different form\, which is more distinct from ordinary lists and looks more
like ordinary object references\.  It should look as ordinary as possible\,
because attributes are obscure and will continue to be forgotten about
by the authors of most op munging code\.  \(They've got far too much to
think about without attributes too\.\)  So I think the attribute stuff
should be hidden away as children of the pad\[sah\]v op\.

\-zefram
