### ISSUE TITLE
Assert fail in Perl_magic_get without other symptoms - '{tell$0;i${^LAST_FH}}'

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15372]
Migrated from [rt.perl.org#128263](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=128263) (status was 'resolved')

Searchable as RT128263$

**Comment by p5pRT** [comment]
### From @dcollinsn

Greetings Porters\,

I have compiled bleadperl with the afl\-gcc compiler using&#8203;:

\./Configure \-Dusedevel \-Dprefix='/usr/local/perl\-afl' \-Dcc='ccache afl\-gcc' \-Uuselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-Dusequadmath \-des
AFL\_HARDEN=1 make && make test

And then fuzzed the resulting binary using&#8203;:

AFL\_NO\_VAR\_CHECK=1 afl\-fuzz \-i in \-o out bin/perl @&#8203;@&#8203;

After reducing testcases using \`afl\-tmin\` and performing additional minimization by hand\, I have located the following testcase that triggers an assert fail in debug buids of the perl interpreter\. The testcase is the file below\. On normal builds\, this runs normally\. On debug builds\, this returns an assert fail\.


dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-e '\{tell$0;i$\{^LAST\_FH\}\}'
perl&#8203;: mg\.c&#8203;:964&#8203;: Perl\_magic\_get&#8203;: Assertion \`\(\(\(\(PL\_last\_in\_gv\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(PL\_last\_in\_gv\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(PL\_last\_in\_gv\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.
Aborted



Debugging tool output is below\. A git bisect was performed and reported the following\, which is presumably the commit where the assert was initially added\.

8561ea1dd1a3357825e765e1df4f883e53f89a9d is the first bad commit
commit 8561ea1dd1a3357825e765e1df4f883e53f89a9d
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Mon Sep 17 23&#8203;:18&#8203;:08 2012 \-0700

&nbsp;    $\{^LAST\_FH\}

&nbsp;    This was brought up in ticket \#96672\.

&nbsp;    This variable gives access to the last\-read filehandle that Perl uses
&nbsp;    when it appends "\, \<STDIN> line 1" to a warning or error message\.

:100644 100644 55666f44cc99fb578eb299e45dc6c2b534094a96 08d41db074a06015b595273e07c4e11603544f22 M       gv\.c
:100644 100644 26cabbe62790425030531b111ae6fc0433363697 cbae42135884ed699c254aca1685fe728902dba5 M       mg\.c
:040000 040000 5562f9bc7ca8edc3abd731fecdc93c5a59d68230 653ba43ff406d65ff5fa01c522d0140b244b21cf M       pod
:040000 040000 f6638536166828af1bf573afebb12ab50d924b24 21a91ab3598eac7dff8e7d4d9b20e8f04231190c M       t
bisect run success



\*\*GDB\*\*

\(gdb\) run
Starting program&#8203;: /home/dcollins/perldebug/miniperl \-Ilib \-e \\\{tell\\$0\\;i\\$\\\{\\^LAST\_FH\\\}\\\}
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
miniperl&#8203;: mg\.c&#8203;:964&#8203;: Perl\_magic\_get&#8203;: Assertion \`\(\(\(\(PL\_last\_in\_gv\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(PL\_last\_in\_gv\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(PL\_last\_in\_gv\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\(gdb\) bt
\#0  0x00007ffff6cf9478 in raise \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#1  0x00007ffff6cfa8fa in abort \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#2  0x00007ffff6cf23a7 in ?? \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#3  0x00007ffff6cf2452 in \_\_assert\_fail \(\) from /lib/x86\_64\-linux\-gnu/libc\.so\.6
\#4  0x0000000000555c52 in Perl\_magic\_get \(sv=0xa95a50\, mg=0xa86400\) at mg\.c&#8203;:964
\#5  0x00000000005532eb in Perl\_mg\_get \(sv=0xa95a50\) at mg\.c&#8203;:197
\#6  0x00000000005a71c9 in S\_opmethod\_stash \(meth=0xa95ab0\) at pp\_hot\.c&#8203;:4150
\#7  0x00000000005a80cf in Perl\_pp\_method\_named \(\) at pp\_hot\.c&#8203;:4258
\#8  0x000000000053fac1 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2239
\#9  0x00000000004482ec in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2517
\#10 0x0000000000447917 in perl\_run \(my\_perl=0xa7f010\) at perl\.c&#8203;:2440
\#11 0x000000000072760b in main \(argc=4\, argv=0x7fffffffe618\, env=0x7fffffffe640\)
&nbsp;    at miniperlmain\.c&#8203;:122


\*\*VALGRIND\*\*

No reported memory management errors\.


\*\*PERL \-V\*\*

dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-V
Summary of my perl5 \(revision 5 version 25 subversion 2\) configuration&#8203;:
&nbsp;  Commit id&#8203;: c29dfc6a6c45f86648c51f961304254cc3c449b9
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=4\.5\.0\-2\-amd64\, archname=x86\_64\-linux\-ld
&nbsp;    uname='linux nightshade64 4\.5\.0\-2\-amd64 \#1 smp debian 4\.5\.3\-2 \(2016\-05\-08\) x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusedevel \-Dprefix=/usr/local/perl\-afl \-Dcc=ccache gcc\-6\.1 \-Duselongdouble \-Duse64bitall \-Doptimize=\-g \-Uversiononly \-Uman1dir \-Uman3dir \-DDEBUGGING \-DPERL\_POISON \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache gcc\-6\.1'\, ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='6\.1\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache gcc\-6\.1'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/local/lib/gcc/x86\_64\-pc\-linux\-gnu/6\.1\.0/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.22\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.22'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: DEBUGGING HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_OP\_PARENT PERL\_PRESERVE\_IVUV PERL\_USE\_DEVEL
&nbsp;                        USE\_64\_BIT\_ALL USE\_64\_BIT\_INT USE\_LARGE\_FILES
&nbsp;                        USE\_LOCALE USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at May 26 2016 17&#8203;:57&#8203;:37
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.2/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.2
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.2/x86\_64\-linux\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.25\.2
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.25\.1
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.24\.0
&nbsp;    /usr/local/perl\-afl/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @cpansprout

On Thu May 26 19&#8203;:24&#8203;:25 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-e
> '\{tell$0;i$\{^LAST\_FH\}\}'
> perl&#8203;: mg\.c&#8203;:964&#8203;: Perl\_magic\_get&#8203;: Assertion \`\(\(\(\(PL\_last\_in\_gv\)\-
> >sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) &&
> \(\(\(svtype\)\(\(PL\_last\_in\_gv\)\->sv\_flags & 0xff\)\) == SVt\_PVGV ||
> \(\(svtype\)\(\(PL\_last\_in\_gv\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.
> Aborted

Here is a clearer test case&#8203;:

$ \./perl \-Ilib \-e 'tell $0; $\{^LAST\_FH\}\->i'
Assertion failed&#8203;: \(isGV\_with\_GP\(PL\_last\_in\_gv\)\)\, function Perl\_magic\_get\, file mg\.c\, line 964\.
Abort trap&#8203;: 6

Without the method call\, it doesn’t fail\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Thu May 26 19&#8203;:44&#8203;:50 2016\, sprout wrote&#8203;:
> On Thu May 26 19&#8203;:24&#8203;:25 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> > dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-e
> > '\{tell$0;i$\{^LAST\_FH\}\}'
> > perl&#8203;: mg\.c&#8203;:964&#8203;: Perl\_magic\_get&#8203;: Assertion \`\(\(\(\(PL\_last\_in\_gv\)\-
> > > sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) &&
> > \(\(\(svtype\)\(\(PL\_last\_in\_gv\)\->sv\_flags & 0xff\)\) == SVt\_PVGV ||
> > \(\(svtype\)\(\(PL\_last\_in\_gv\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.
> > Aborted
> 
> Here is a clearer test case&#8203;:
> 
> $ \./perl \-Ilib \-e 'tell $0; $\{^LAST\_FH\}\->i'
> Assertion failed&#8203;: \(isGV\_with\_GP\(PL\_last\_in\_gv\)\)\, function
> Perl\_magic\_get\, file mg\.c\, line 964\.
> Abort trap&#8203;: 6
> 
> Without the method call\, it doesn’t fail\.

It's pretty much any reference to $\{^LAST\_FH\)\, since the assertion is in the magic for $\{^LAST\_FH\}\.

The attached fixes it for me\.

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

<details><summary>0001-perl-128263-don-t-leave-LAST_FH-as-a-non-GV.patch</summary>

```diff
From 3dff64555e9806caef34ea3fbe92d3734c268615 Mon Sep 17 00:00:00 2001
From: Tony Cook <tony@develop-help.com>
Date: Thu, 11 Aug 2016 11:37:07 +1000
Subject: (perl #128263) don't leave ${^LAST_FH} as a non-GV

---
 doio.c       |  7 ++++++-
 t/op/magic.t | 11 ++++++++++-
 2 files changed, 16 insertions(+), 2 deletions(-)

diff --git a/doio.c b/doio.c
index 2dc7082..241534a 100644
--- a/doio.c
+++ b/doio.c
@@ -1151,8 +1151,10 @@ Perl_do_eof(pTHX_ GV *gv)
 
     PERL_ARGS_ASSERT_DO_EOF;
 
-    if (!io)
+    if (!io) {
+        PL_last_in_gv = NULL;
 	return TRUE;
+    }
     else if (IoTYPE(io) == IoTYPE_WRONLY)
 	report_wrongway_fh(gv, '>');
 
@@ -1199,6 +1201,7 @@ Perl_do_tell(pTHX_ GV *gv)
     if (io && (fp = IoIFP(io))) {
 	return PerlIO_tell(fp);
     }
+    PL_last_in_gv = NULL;
     report_evil_fh(gv);
     SETERRNO(EBADF,RMS_IFI);
     return (Off_t)-1;
@@ -1213,6 +1216,7 @@ Perl_do_seek(pTHX_ GV *gv, Off_t pos, int whence)
     if (io && (fp = IoIFP(io))) {
 	return PerlIO_seek(fp, pos, whence) >= 0;
     }
+    PL_last_in_gv = NULL;
     report_evil_fh(gv);
     SETERRNO(EBADF,RMS_IFI);
     return FALSE;
@@ -1235,6 +1239,7 @@ Perl_do_sysseek(pTHX_ GV *gv, Off_t pos, int whence)
             return PerlLIO_lseek(fd, pos, whence);
         }
     }
+    PL_last_in_gv = NULL;
     report_evil_fh(gv);
     SETERRNO(EBADF,RMS_IFI);
     return (Off_t)-1;
diff --git a/t/op/magic.t b/t/op/magic.t
index f8c822b..79b4559 100644
--- a/t/op/magic.t
+++ b/t/op/magic.t
@@ -5,7 +5,7 @@ BEGIN {
     chdir 't' if -d 't';
     @INC = '../lib';
     require './test.pl';
-    plan (tests => 192);
+    plan (tests => 196);
 }
 
 # Test that defined() returns true for magic variables created on the fly,
@@ -642,6 +642,15 @@ is ${^LAST_FH}, \*STDIN, '${^LAST_FH} after another tell';
 # This also tests that ${^LAST_FH} is a weak reference:
 is ${^LAST_FH}, undef, '${^LAST_FH} is undef when PL_last_in_gv is NULL';
 
+# all of these would set PL_last_in_gv to a non-GV which would 
+# assert when referenced by the magic for ${^LAST_FH}.
+# Instead it should act like <$0> which NULLs PL_last_in_gv and the magic
+# returns that as undef.
+for my $code ('tell $0', 'sysseek $0, 0, 0', 'seek $0, 0, 0', 'eof $0') {
+    fresh_perl_is("$code; print defined \${^LAST_FH} ? qq(not ok\n) : qq(ok\n)", "ok\n",
+                  undef, "check $code doesn't define \${^LAST_FH}");
+}
+
 
 # $|
 fresh_perl_is 'print $| = ~$|', "1\n", {switches => ['-l']},
-- 
2.1.4


```
</details>

**Comment by p5pRT** [comment]
### From @cpansprout

On Wed Aug 10 18&#8203;:40&#8203;:21 2016\, tonyc wrote&#8203;:
> On Thu May 26 19&#8203;:44&#8203;:50 2016\, sprout wrote&#8203;:
> > On Thu May 26 19&#8203;:24&#8203;:25 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> > > dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-e
> > > '\{tell$0;i$\{^LAST\_FH\}\}'
> > > perl&#8203;: mg\.c&#8203;:964&#8203;: Perl\_magic\_get&#8203;: Assertion \`\(\(\(\(PL\_last\_in\_gv\)\-
> > > > sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) &&
> > > \(\(\(svtype\)\(\(PL\_last\_in\_gv\)\->sv\_flags & 0xff\)\) == SVt\_PVGV ||
> > > \(\(svtype\)\(\(PL\_last\_in\_gv\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.
> > > Aborted
> >
> > Here is a clearer test case&#8203;:
> >
> > $ \./perl \-Ilib \-e 'tell $0; $\{^LAST\_FH\}\->i'
> > Assertion failed&#8203;: \(isGV\_with\_GP\(PL\_last\_in\_gv\)\)\, function
> > Perl\_magic\_get\, file mg\.c\, line 964\.
> > Abort trap&#8203;: 6
> >
> > Without the method call\, it doesn’t fail\.
> 
> It's pretty much any reference to $\{^LAST\_FH\)\, since the assertion is
> in the magic for $\{^LAST\_FH\}\.
> 
> The attached fixes it for me\.

Before$ \./miniperl \-le '\*$0; tell $0; print \*$\{^LAST\_FH\}'
\*main&#8203;::\-e
After$ \./miniperl \-le '\*$0; tell $0; print \*$\{^LAST\_FH\}'
Can't use an undefined value as a symbol reference at \-e line 1\.

I would have expected the rv2gv op to prevent PL\_last\_in\_gv from being set to a non\-glob\.

$ \./perl \-Ilib \-MO=Concise \-e 'tell $0'
6  \<@&#8203;> leave\[1 ref\] vKP/REFC \->\(end\)
1     \<0> enter \->2
2     \<;> nextstate\(main 1 \-e&#8203;:1\) v&#8203;:\{ \->3
5     \<1> tell\[t1\] vK/1 \->6
4        \<1> rv2gv sK\*/FAKE\,1 \->5
\-           \<1> ex\-rv2sv sK/1 \->4
3              \<$> gvsv\(\*0\) s \->4
\-e syntax OK

But rv2gv can sometimes return &PL\_sv\_undef\.  To avoid a change in behaviour\, I think a better fix would be to use

&nbsp;        if \(PL\_last\_in\_gv && PL\_last\_in\_gv \!= &PL\_sv\_undef\) \{

in mg\.c \(and to leave the assertion as\-is\, since having PL\_last\_in\_gv set to anything else is a bug we want to be alerted about\)\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @tonycoz

On Wed Aug 10 19&#8203;:50&#8203;:01 2016\, sprout wrote&#8203;:
> But rv2gv can sometimes return &PL\_sv\_undef\.  To avoid a change in
> behaviour\, I think a better fix would be to use
> 
> if \(PL\_last\_in\_gv && PL\_last\_in\_gv \!= &PL\_sv\_undef\) \{
> 
> in mg\.c \(and to leave the assertion as\-is\, since having PL\_last\_in\_gv
> set to anything else is a bug we want to be alerted about\)\.

With that change \(with a cast to make the pointers the same type\)\,
should this from pp\_readline be simplified?&#8203;:

&nbsp;        PL\_last\_in\_gv = MUTABLE\_GV\(\*PL\_stack\_sp\-\-\);
&nbsp;        if \(PL\_last\_in\_gv == \(GV \*\)&PL\_sv\_undef\)
&nbsp;        PL\_last\_in\_gv = NULL;
&nbsp;        else
&nbsp;        assert\(isGV\_with\_GP\(PL\_last\_in\_gv\)\);

Tony

**Comment by p5pRT** [comment]
### From @cpansprout

On Mon Sep 05 21&#8203;:34&#8203;:29 2016\, tonyc wrote&#8203;:
> On Wed Aug 10 19&#8203;:50&#8203;:01 2016\, sprout wrote&#8203;:
> > But rv2gv can sometimes return &PL\_sv\_undef\.  To avoid a change in
> > behaviour\, I think a better fix would be to use
> > 
> > if \(PL\_last\_in\_gv && PL\_last\_in\_gv \!= &PL\_sv\_undef\) \{
> > 
> > in mg\.c \(and to leave the assertion as\-is\, since having PL\_last\_in\_gv
> > set to anything else is a bug we want to be alerted about\)\.
> 
> With that change \(with a cast to make the pointers the same type\)\,
> should this from pp\_readline be simplified?&#8203;:
> 
>         PL\_last\_in\_gv = MUTABLE\_GV\(\*PL\_stack\_sp\-\-\);
>         if \(PL\_last\_in\_gv == \(GV \*\)&PL\_sv\_undef\)
>         PL\_last\_in\_gv = NULL;
>         else
>         assert\(isGV\_with\_GP\(PL\_last\_in\_gv\)\);

Aha\!  I’m not consistent\, am I?

commit 84ee769f11470162885ddc894bb007e238ea68b1
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Mon Dec 15 09&#8203;:41&#8203;:54 2014 \-0800

&nbsp;    pp\_readline&#8203;: Don’t set PL\_last\_in\_gv to &PL\_sv\_undef

Yes\, I do think 84ee769f can be reverted \(except for the test\)\.  It did not occur to me at the time that many other ops are likewise affected\, and that the much cleaner approach is to check in just one spot in mg\.c\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon\, 05 Sep 2016 21&#8203;:50&#8203;:43 \-0700\, sprout wrote&#8203;:
> On Mon Sep 05 21&#8203;:34&#8203;:29 2016\, tonyc wrote&#8203;:
> > On Wed Aug 10 19&#8203;:50&#8203;:01 2016\, sprout wrote&#8203;:
> > > But rv2gv can sometimes return &PL\_sv\_undef\.  To avoid a change in
> > > behaviour\, I think a better fix would be to use
> > >
> > > if \(PL\_last\_in\_gv && PL\_last\_in\_gv \!= &PL\_sv\_undef\) \{
> > >
> > > in mg\.c \(and to leave the assertion as\-is\, since having
> > > PL\_last\_in\_gv
> > > set to anything else is a bug we want to be alerted about\)\.
> >
> > With that change \(with a cast to make the pointers the same type\)\,
> > should this from pp\_readline be simplified?&#8203;:
> >
> > PL\_last\_in\_gv = MUTABLE\_GV\(\*PL\_stack\_sp\-\-\);
> > if \(PL\_last\_in\_gv == \(GV \*\)&PL\_sv\_undef\)
> >     PL\_last\_in\_gv = NULL;
> > else
> >     assert\(isGV\_with\_GP\(PL\_last\_in\_gv\)\);
> 
> Aha\!  I’m not consistent\, am I?
> 
> commit 84ee769f11470162885ddc894bb007e238ea68b1
> Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
> Date&#8203;:   Mon Dec 15 09&#8203;:41&#8203;:54 2014 \-0800
> 
> pp\_readline&#8203;: Don’t set PL\_last\_in\_gv to &PL\_sv\_undef
> 
> Yes\, I do think 84ee769f can be reverted \(except for the test\)\.  It
> did not occur to me at the time that many other ops are likewise
> affected\, and that the much cleaner approach is to check in just one
> spot in mg\.c\.

Something like the attached\, I presume\.

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

<details><summary>0001-perl-128263-handle-PL_last_in_gv-being-PL_sv_undef.patch</summary>

```diff
From eb5f9c4a74fe61c3fcff32dbabac036d8c37588d Mon Sep 17 00:00:00 2001
From: Tony Cook <tony@develop-help.com>
Date: Thu, 9 Feb 2017 15:47:48 +1100
Subject: (perl #128263) handle PL_last_in_gv being &PL_sv_undef

rv2gv will return &PL_sv_undef when it can't get a GV, previously
this could cause an assertion failure in mg.c

My original fix for this changed each op that deals with GVs for I/O
to set PL_last_in_gv to NULL if there was no io object in the GV, but
this changes other behaviour as noted by FatherC.

Also partly reverts 84ee769f, which did the
---
 mg.c         |  2 +-
 pp_hot.c     |  5 +----
 t/op/magic.t | 12 +++++++++++-
 3 files changed, 13 insertions(+), 6 deletions(-)

diff --git a/mg.c b/mg.c
index 172127c..bddde19 100644
--- a/mg.c
+++ b/mg.c
@@ -951,7 +951,7 @@ Perl_magic_get(pTHX_ SV *sv, MAGIC *mg)
 	break;
     case '\014':		/* ^LAST_FH */
 	if (strEQ(remaining, "AST_FH")) {
-	    if (PL_last_in_gv) {
+	    if (PL_last_in_gv && (SV*)PL_last_in_gv != &PL_sv_undef) {
 		assert(isGV_with_GP(PL_last_in_gv));
 		SV_CHECK_THINKFIRST_COW_DROP(sv);
 		prepare_SV_for_RV(sv);
diff --git a/pp_hot.c b/pp_hot.c
index a3ee2a7..ea4f01e 100644
--- a/pp_hot.c
+++ b/pp_hot.c
@@ -445,10 +445,7 @@ PP(pp_readline)
 	    PUTBACK;
 	    Perl_pp_rv2gv(aTHX);
 	    PL_last_in_gv = MUTABLE_GV(*PL_stack_sp--);
-	    if (PL_last_in_gv == (GV *)&PL_sv_undef)
-		PL_last_in_gv = NULL;
-	    else
-		assert(isGV_with_GP(PL_last_in_gv));
+            assert((SV*)PL_last_in_gv == &PL_sv_undef || isGV_with_GP(PL_last_in_gv));
 	}
     }
     return do_readline();
diff --git a/t/op/magic.t b/t/op/magic.t
index 3f71f8e..36abafb 100644
--- a/t/op/magic.t
+++ b/t/op/magic.t
@@ -5,7 +5,7 @@ BEGIN {
     chdir 't' if -d 't';
     require './test.pl';
     set_up_inc( '../lib' );
-    plan (tests => 192); # some tests are run in BEGIN block
+    plan (tests => 196); # some tests are run in BEGIN block
 }
 
 # Test that defined() returns true for magic variables created on the fly,
@@ -643,6 +643,16 @@ is ${^LAST_FH}, \*STDIN, '${^LAST_FH} after another tell';
 # This also tests that ${^LAST_FH} is a weak reference:
 is ${^LAST_FH}, undef, '${^LAST_FH} is undef when PL_last_in_gv is NULL';
 
+# all of these would set PL_last_in_gv to a non-GV which would
+# assert when referenced by the magic for ${^LAST_FH}.
+# Instead it should act like <$0> which NULLs PL_last_in_gv and the magic
+# returns that as undef.
+# The approach to fixing this has changed (#128263), but it's still useful
+# to check each op.
+for my $code ('tell $0', 'sysseek $0, 0, 0', 'seek $0, 0, 0', 'eof $0') {
+    fresh_perl_is("$code; print defined \${^LAST_FH} ? qq(not ok\n) : qq(ok\n)", "ok\n",
+                  undef, "check $code doesn't define \${^LAST_FH}");
+}
 
 # $|
 fresh_perl_is 'print $| = ~$|', "1\n", {switches => ['-l']},
-- 
2.1.4


```
</details>

**Comment by p5pRT** [comment]
### From @tonycoz

On Wed\, 10 Aug 2016 18&#8203;:40&#8203;:21 \-0700\, tonyc wrote&#8203;:
> On Thu May 26 19&#8203;:44&#8203;:50 2016\, sprout wrote&#8203;:
> > On Thu May 26 19&#8203;:24&#8203;:25 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> > > dcollins@&#8203;nightshade64&#8203;:\~/perldebug$ \./perl \-Ilib \-e
> > > '\{tell$0;i$\{^LAST\_FH\}\}'
> > > perl&#8203;: mg\.c&#8203;:964&#8203;: Perl\_magic\_get&#8203;: Assertion \`\(\(\(\(PL\_last\_in\_gv\)\-
> > > > sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) &&
> > > \(\(\(svtype\)\(\(PL\_last\_in\_gv\)\->sv\_flags & 0xff\)\) == SVt\_PVGV ||
> > > \(\(svtype\)\(\(PL\_last\_in\_gv\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.
> > > Aborted
> >
> > Here is a clearer test case&#8203;:
> >
> > $ \./perl \-Ilib \-e 'tell $0; $\{^LAST\_FH\}\->i'
> > Assertion failed&#8203;: \(isGV\_with\_GP\(PL\_last\_in\_gv\)\)\, function
> > Perl\_magic\_get\, file mg\.c\, line 964\.
> > Abort trap&#8203;: 6
> >
> > Without the method call\, it doesn’t fail\.
> 
> It's pretty much any reference to $\{^LAST\_FH\)\, since the assertion is
> in the magic for $\{^LAST\_FH\}\.
> 
> The attached fixes it for me\.

Applied as 745e740c825d415f535852b90516127e64c24905\, fixing the incomplete sentence at the end\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release yesterday of Perl 5\.28\.0\, this and 185 other issues have been
resolved\.

Perl 5\.28\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.28.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
