### ISSUE TITLE
heap-buffer-overflow in Perl_sv_vcatpvfn_flags (sv.c:12897)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15518]
Migrated from [rt.perl.org#128951](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=128951) (status was 'resolved')

Searchable as RT128951$

**Comment by p5pRT** [comment]
### From @geeknik

The attached test case triggers a heap\-buffer\-overflow in Perl\_sv\_vcatpvfn\_flags \(sv\.c&#8203;:12897\)\. This was found with AFL\, ASAN and libdislocator\.so and affects v5\.25\.4 \(v5\.25\.3\-245\-g2e66fe9\)\. Perl 5\.20\.2 returns an error that says \`Unrecognized character \\xD7; marked by \<\-\- HERE after \!@&#8203;\{\<\-\- HERE near column \-1 at test00 line 1\.\`

==13440==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address 0x60200000dea8 at pc 0x0000004a9880 bp 0x7ffd00eeac90 sp 0x7ffd00eea450
READ of size 10 at 0x60200000dea8 thread T0
&nbsp;    \#0 0x4a987f in \_\_asan\_memcpy \(/home/geeknik/perl/perl\+0x4a987f\)
&nbsp;    \#1 0x980d45 in Perl\_sv\_vcatpvfn\_flags /home/geeknik/perl/sv\.c&#8203;:12897&#8203;:6
&nbsp;    \#2 0x963bc6 in Perl\_sv\_vsetpvfn /home/geeknik/perl/sv\.c&#8203;:10815&#8203;:5
&nbsp;    \#3 0x7fef42 in Perl\_vmess /home/geeknik/perl/util\.c&#8203;:1560&#8203;:5
&nbsp;    \#4 0x7fef42 in Perl\_vcroak /home/geeknik/perl/util\.c&#8203;:1789
&nbsp;    \#5 0x7f53ac in Perl\_croak /home/geeknik/perl/util\.c&#8203;:1836&#8203;:5
&nbsp;    \#6 0x66c3f0 in Perl\_yylex /home/geeknik/perl/toke\.c&#8203;:4901&#8203;:9
&nbsp;    \#7 0x6ac741 in Perl\_yyparse /home/geeknik/perl/perly\.c&#8203;:334&#8203;:19
&nbsp;    \#8 0x59bf12 in S\_parse\_body /home/geeknik/perl/perl\.c&#8203;:2372&#8203;:9
&nbsp;    \#9 0x59225c in perl\_parse /home/geeknik/perl/perl\.c&#8203;:1688&#8203;:2
&nbsp;    \#10 0x4de7d5 in main /home/geeknik/perl/perlmain\.c&#8203;:121&#8203;:18
&nbsp;    \#11 0x7fcba632cb44 in \_\_libc\_start\_main /build/glibc\-uPj9cH/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#12 0x4de46c in \_start \(/home/geeknik/perl/perl\+0x4de46c\)

0x60200000dea8 is located 8 bytes to the left of 10\-byte region \[0x60200000deb0\,0x60200000deba\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4c0deb in malloc \(/home/geeknik/perl/perl\+0x4c0deb\)
&nbsp;    \#1 0x7f5007 in Perl\_safesysmalloc /home/geeknik/perl/util\.c&#8203;:153&#8203;:21

SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow ??&#8203;:0 \_\_asan\_memcpy
Shadow bytes around the buggy address&#8203;:
&nbsp;  0x0c047fff9b80&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c047fff9b90&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c047fff9ba0&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c047fff9bb0&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c047fff9bc0&#8203;: fa fa fa fa fa fa fd fd fa fa 00 02 fa fa 00 02
=>0x0c047fff9bd0&#8203;: fa fa 00 02 fa\[fa\]00 02 fa fa 00 04 fa fa 02 fa
&nbsp;  0x0c047fff9be0&#8203;: fa fa 00 02 fa fa 00 03 fa fa 00 02 fa fa 00 00
&nbsp;  0x0c047fff9bf0&#8203;: fa fa 00 02 fa fa 00 02 fa fa 00 fa fa fa 00 02
&nbsp;  0x0c047fff9c00&#8203;: fa fa 00 00 fa fa 00 00 fa fa 00 06 fa fa 00 fa
&nbsp;  0x0c047fff9c10&#8203;: fa fa 00 02 fa fa 05 fa fa fa 00 07 fa fa 00 01
&nbsp;  0x0c047fff9c20&#8203;: fa fa 00 02 fa fa 06 fa fa fa 00 02 fa fa 00 03
Shadow byte legend \(one shadow byte represents 8 application bytes\)&#8203;:
&nbsp;  Addressable&#8203;:           00
&nbsp;  Partially addressable&#8203;: 01 02 03 04 05 06 07 
&nbsp;  Heap left redzone&#8203;:       fa
&nbsp;  Heap right redzone&#8203;:      fb
&nbsp;  Freed heap region&#8203;:       fd
&nbsp;  Stack left redzone&#8203;:      f1
&nbsp;  Stack mid redzone&#8203;:       f2
&nbsp;  Stack right redzone&#8203;:     f3
&nbsp;  Stack partial redzone&#8203;:   f4
&nbsp;  Stack after return&#8203;:      f5
&nbsp;  Stack use after scope&#8203;:   f8
&nbsp;  Global redzone&#8203;:          f9
&nbsp;  Global init order&#8203;:       f6
&nbsp;  Poisoned by user&#8203;:        f7
&nbsp;  Container overflow&#8203;:      fc
&nbsp;  ASan internal&#8203;:           fe
==13440==ABORTING

**Comment by p5pRT** [comment]
### From @geeknik

[test00](https://rt-archive.perl.org/perl5/Ticket/Attachment/1417081/766101/test00)

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Aug 15\, 2016 at 03&#8203;:15&#8203;:03PM \-0700\, Brian Carpenter wrote&#8203;:
> The attached test case triggers a heap\-buffer\-overflow in Perl\_sv\_vcatpvfn\_flags \(sv\.c&#8203;:12897\)\. This was found with AFL\, ASAN and libdislocator\.so and affects v5\.25\.4 \(v5\.25\.3\-245\-g2e66fe9\)\. Perl 5\.20\.2 returns an error that says \`Unrecognized character \\xD7; marked by \<\-\- HERE after \!@&#8203;\{\<\-\- HERE near column \-1 at test00 line 1\.\`
> 

The src code contains the bytes&#8203;:

&nbsp;    @&#8203; \{ \\327 \\n

after seeing "@&#8203;\{" the lexer calls scan\_ident\(\)\, which sees the \\327 as an
ident\, then calls S\_skipspace\_flags\(\) to skip the spaces following the
ident\.  This moves the current cursor position to the \\n\, and since that's
a line boundary\, its updates PL\_linestart and PL\_bufptr to point to \\n
too\.

When it finds that the next char isn't a '\}'\, it does this&#8203;:

&nbsp;            /\* Didn't find the closing \} at the point we expected\, so restore
&nbsp;               state such that the next thing to process is the opening \{ and \*/
&nbsp;        s = SvPVX\(PL\_linestr\) \+ bracket; /\* let the parser handle it \*/

i\.e\. it moves s back to the "\{\\317" then continues\.

However\, PL\_linestart doesn't get reset\, so later when the parser
encounters the \\327 and tries to croak with "Unrecognized character %s \.\.\."\,
when it prints out the section of src code in error\, since s \< PL\_linestr\,
negative string lengths and ASAN errors ensue\.

I don't know the best way to fix this\.

\-\- 
I before E\. Except when it isn't\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Tue Aug 16 08&#8203;:44&#8203;:17 2016\, davem wrote&#8203;:
> On Mon\, Aug 15\, 2016 at 03&#8203;:15&#8203;:03PM \-0700\, Brian Carpenter wrote&#8203;:
> > The attached test case triggers a heap\-buffer\-overflow in
> > Perl\_sv\_vcatpvfn\_flags \(sv\.c&#8203;:12897\)\. This was found with AFL\, ASAN
> > and libdislocator\.so and affects v5\.25\.4 \(v5\.25\.3\-245\-g2e66fe9\)\. Perl
> > 5\.20\.2 returns an error that says \`Unrecognized character \\xD7;
> > marked by \<\-\- HERE after \!@&#8203;\{\<\-\- HERE near column \-1 at test00 line
> > 1\.\`
> >
> 
> The src code contains the bytes&#8203;:
> 
> @&#8203; \{ \\327 \\n
> 
> after seeing "@&#8203;\{" the lexer calls scan\_ident\(\)\, which sees the \\327 as
> an
> ident\, then calls S\_skipspace\_flags\(\) to skip the spaces following the
> ident\.  This moves the current cursor position to the \\n\, and since
> that's
> a line boundary\, its updates PL\_linestart and PL\_bufptr to point to \\n
> too\.
> 
> When it finds that the next char isn't a '\}'\, it does this&#8203;:
> 
> /\* Didn't find the closing \} at the point we expected\, so restore
>    state such that the next thing to process is the opening \{ and \*/
> s = SvPVX\(PL\_linestr\) \+ bracket; /\* let the parser handle it \*/
> 
> i\.e\. it moves s back to the "\{\\317" then continues\.
> 
> However\, PL\_linestart doesn't get reset\, so later when the parser
> encounters the \\327 and tries to croak with "Unrecognized character %s
> \.\.\."\,
> when it prints out the section of src code in error\, since s \<
> PL\_linestr\,
> negative string lengths and ASAN errors ensue\.
> 
> I don't know the best way to fix this\.

This looks like fun\.  Do you mind if I take over?

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, Aug 16\, 2016 at 02&#8203;:12&#8203;:12PM \-0700\, Father Chrysostomos via RT wrote&#8203;:
> On Tue Aug 16 08&#8203;:44&#8203;:17 2016\, davem wrote&#8203;:
> > On Mon\, Aug 15\, 2016 at 03&#8203;:15&#8203;:03PM \-0700\, Brian Carpenter wrote&#8203;:
> > > The attached test case triggers a heap\-buffer\-overflow in
> > > Perl\_sv\_vcatpvfn\_flags \(sv\.c&#8203;:12897\)\. This was found with AFL\, ASAN
> > > and libdislocator\.so and affects v5\.25\.4 \(v5\.25\.3\-245\-g2e66fe9\)\. Perl
> > > 5\.20\.2 returns an error that says \`Unrecognized character \\xD7;
> > > marked by \<\-\- HERE after \!@&#8203;\{\<\-\- HERE near column \-1 at test00 line
> > > 1\.\`
> > >
> > 
> > The src code contains the bytes&#8203;:
> > 
> > @&#8203; \{ \\327 \\n
> > 
> > after seeing "@&#8203;\{" the lexer calls scan\_ident\(\)\, which sees the \\327 as
> > an
> > ident\, then calls S\_skipspace\_flags\(\) to skip the spaces following the
> > ident\.  This moves the current cursor position to the \\n\, and since
> > that's
> > a line boundary\, its updates PL\_linestart and PL\_bufptr to point to \\n
> > too\.
> > 
> > When it finds that the next char isn't a '\}'\, it does this&#8203;:
> > 
> > /\* Didn't find the closing \} at the point we expected\, so restore
> >    state such that the next thing to process is the opening \{ and \*/
> > s = SvPVX\(PL\_linestr\) \+ bracket; /\* let the parser handle it \*/
> > 
> > i\.e\. it moves s back to the "\{\\317" then continues\.
> > 
> > However\, PL\_linestart doesn't get reset\, so later when the parser
> > encounters the \\327 and tries to croak with "Unrecognized character %s
> > \.\.\."\,
> > when it prints out the section of src code in error\, since s \<
> > PL\_linestr\,
> > negative string lengths and ASAN errors ensue\.
> > 
> > I don't know the best way to fix this\.
> 
> This looks like fun\.  Do you mind if I take over?

Isn't it handy that people have such differing concepts of what
constitutes 'fun'? Yes\, please do take over :\-\)\.

\-\- 
Never do today what you can put off till tomorrow\.

**Comment by p5pRT** [comment]
### From @cpansprout

On Wed Aug 17 00&#8203;:09&#8203;:07 2016\, davem wrote&#8203;:
> On Tue\, Aug 16\, 2016 at 02&#8203;:12&#8203;:12PM \-0700\, Father Chrysostomos via RT wrote&#8203;:
> > This looks like fun\.  Do you mind if I take over?
> 
> Isn't it handy that people have such differing concepts of what
> constitutes 'fun'? Yes\, please do take over :\-\)\.

It’s practically a continuation of commit 21791330a\, so it was fairly easy \(except for the stupid mistakes that had me wonder why I was getting fleeting crashes; I must be getting rusty\)\.

In any case\, it’s now fixed by bf8a9a15e\.  I hope the following commits make the lexer slightly easier \(ahem\) to comprehend\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
