### ISSUE TITLE
heap-buffer-overflow S_scan_heredoc (toke.c:9587)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15546]
Migrated from [rt.perl.org#129064](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129064) (status was 'resolved')

Searchable as RT129064$

**Comment by p5pRT** [comment]
### From @geeknik

AFL\, ASAN and libdislocator trigger a heap\-buffer\-overflow in Perl
v5\.25\.4\-5\-g92d73bf\.

od \-tx1 test38
0000000 3c 3c 60 5c
0000004

==4872==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
0x60200000e29a at pc 0x0000004aa445 bp 0x7fffd1c76110 sp 0x7fffd1c758d0
READ of size 5 at 0x60200000e29a thread T0
&nbsp;    \#0 0x4aa444 in \_\_interceptor\_index \(/root/perl/perl\+0x4aa444\)
&nbsp;    \#1 0x6468eb in S\_scan\_heredoc /root/perl/toke\.c&#8203;:9587&#8203;:9
&nbsp;    \#2 0x6468eb in Perl\_yylex /root/perl/toke\.c&#8203;:6216
&nbsp;    \#3 0x6ac9f5 in Perl\_yyparse /root/perl/perly\.c&#8203;:334&#8203;:19
&nbsp;    \#4 0x59c4f1 in S\_parse\_body /root/perl/perl\.c&#8203;:2373&#8203;:9
&nbsp;    \#5 0x59288c in perl\_parse /root/perl/perl\.c&#8203;:1689&#8203;:2
&nbsp;    \#6 0x4de835 in main /root/perl/perlmain\.c&#8203;:121&#8203;:18
&nbsp;    \#7 0x7f5626732b44 in \_\_libc\_start\_main
/build/glibc\-uPj9cH/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#8 0x4de4cc in \_start \(/root/perl/perl\+0x4de4cc\)

0x60200000e29a is located 0 bytes to the right of 10\-byte region
\[0x60200000e290\,0x60200000e29a\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4c0e4b in malloc \(/root/perl/perl\+0x4c0e4b\)
&nbsp;    \#1 0x7f5bf7 in Perl\_safesysmalloc /root/perl/util\.c&#8203;:153&#8203;:21

SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow ??&#8203;:0 \_\_interceptor\_index
Shadow bytes around the buggy address&#8203;:
&nbsp;  0x0c047fff9c00&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c047fff9c10&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c047fff9c20&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c047fff9c30&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c047fff9c40&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa 00 02
=>0x0c047fff9c50&#8203;: fa fa 00\[02\]fa fa 00 04 fa fa 02 fa fa fa 00 02
&nbsp;  0x0c047fff9c60&#8203;: fa fa 00 07 fa fa 00 fa fa fa 00 02 fa fa 05 fa
&nbsp;  0x0c047fff9c70&#8203;: fa fa 00 02 fa fa 06 fa fa fa 00 02 fa fa 05 fa
&nbsp;  0x0c047fff9c80&#8203;: fa fa 00 05 fa fa 04 fa fa fa 05 fa fa fa 05 fa
&nbsp;  0x0c047fff9c90&#8203;: fa fa 00 00 fa fa 00 02 fa fa 05 fa fa fa 00 02
&nbsp;  0x0c047fff9ca0&#8203;: fa fa 00 fa fa fa 00 04 fa fa 07 fa fa fa 00 02
Shadow byte legend \(one shadow byte represents 8 application bytes\)&#8203;:
&nbsp;  Addressable&#8203;:           00
&nbsp;  Partially addressable&#8203;: 01 02 03 04 05 06 07
&nbsp;  Heap left redzone&#8203;:       fa
&nbsp;  Heap right redzone&#8203;:      fb
&nbsp;  Freed heap region&#8203;:       fd
&nbsp;  Stack left redzone&#8203;:      f1
&nbsp;  Stack mid redzone&#8203;:       f2
&nbsp;  Stack right redzone&#8203;:     f3
&nbsp;  Stack partial redzone&#8203;:   f4
&nbsp;  Stack after return&#8203;:      f5
&nbsp;  Stack use after scope&#8203;:   f8
&nbsp;  Global redzone&#8203;:          f9
&nbsp;  Global init order&#8203;:       f6
&nbsp;  Poisoned by user&#8203;:        f7
&nbsp;  Container overflow&#8203;:      fc
&nbsp;  ASan internal&#8203;:           fe
==4872==ABORTING

==7103== Conditional jump or move depends on uninitialised value\(s\)
==7103==    at 0x4C2BC5A&#8203;: \_\_GI\_strchr \(vg\_replace\_strmem\.c&#8203;:229\)
==7103==    by 0x477292&#8203;: S\_scan\_heredoc \(toke\.c&#8203;:9587\)
==7103==    by 0x477292&#8203;: Perl\_yylex \(toke\.c&#8203;:6216\)
==7103==    by 0x48A222&#8203;: Perl\_yyparse \(perly\.c&#8203;:334\)
==7103==    by 0x450CC7&#8203;: S\_parse\_body \(perl\.c&#8203;:2373\)
==7103==    by 0x45285C&#8203;: perl\_parse \(perl\.c&#8203;:1689\)
==7103==    by 0x4217AF&#8203;: main \(perlmain\.c&#8203;:121\)
==7103==
==7103== Conditional jump or move depends on uninitialised value\(s\)
==7103==    at 0x4C2BC60&#8203;: \_\_GI\_strchr \(vg\_replace\_strmem\.c&#8203;:229\)
==7103==    by 0x477292&#8203;: S\_scan\_heredoc \(toke\.c&#8203;:9587\)
==7103==    by 0x477292&#8203;: Perl\_yylex \(toke\.c&#8203;:6216\)
==7103==    by 0x48A222&#8203;: Perl\_yyparse \(perly\.c&#8203;:334\)
==7103==    by 0x450CC7&#8203;: S\_parse\_body \(perl\.c&#8203;:2373\)
==7103==    by 0x45285C&#8203;: perl\_parse \(perl\.c&#8203;:1689\)
==7103==    by 0x4217AF&#8203;: main \(perlmain\.c&#8203;:121\)
==7103==
Can't find string terminator "\\" anywhere before EOF at test38 line 1\.

**Comment by p5pRT** [comment]
### From @geeknik

[test38.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1419453/767491/test38.gz)

**Comment by p5pRT** [comment]
### From @iabyn

On Wed\, Aug 24\, 2016 at 02&#8203;:30&#8203;:08AM \-0700\, Brian Carpenter wrote&#8203;:
> od \-tx1 test38
> 0000000 3c 3c 60 5c
> 0000004
> 
> ==4872==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
> 0x60200000e29a at pc 0x0000004aa445 bp 0x7fffd1c76110 sp 0x7fffd1c758d0
> READ of size 5 at 0x60200000e29a thread T0
>     \#0 0x4aa444 in \_\_interceptor\_index \(/root/perl/perl\+0x4aa444\)
>     \#1 0x6468eb in S\_scan\_heredoc /root/perl/toke\.c&#8203;:9587&#8203;:9
>     \#2 0x6468eb in Perl\_yylex /root/perl/toke\.c&#8203;:6216
>     \#3 0x6ac9f5 in Perl\_yyparse /root/perl/perly\.c&#8203;:334&#8203;:19
>     \#4 0x59c4f1 in S\_parse\_body /root/perl/perl\.c&#8203;:2373&#8203;:9
>     \#5 0x59288c in perl\_parse /root/perl/perl\.c&#8203;:1689&#8203;:2
>     \#6 0x4de835 in main /root/perl/perlmain\.c&#8203;:121&#8203;:18
>     \#7 0x7f5626732b44 in \_\_libc\_start\_main
> /build/glibc\-uPj9cH/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
>     \#8 0x4de4cc in \_start \(/root/perl/perl\+0x4de4cc\)
> 
> 0x60200000e29a is located 0 bytes to the right of 10\-byte region
> \[0x60200000e290\,0x60200000e29a\)

The attached patch \(intended to be applied over Tony's pending heredoc
fix\) fixes this\.

It was a bug in Perl\_delimcpy\(\)\. This function copies a string
delineated by a specified char\, while handling \\\-delimiter\. If the last
char in the string was \\ it could overrun by a couple of bytes\.

It's not a security issue\. Here are the details of the callers of
Perl\_delimcpy&#8203;:

&nbsp;    S\_scan\_heredoc&#8203;:

&nbsp;        This can only be triggered if a source file \(but not eval nor perl
&nbsp;        \-e\) literally ends with the chars \[\<\<X\.\.\.something\.\.\.\\\]\, where X is
&nbsp;        one of \["'\`\] and there is no newline following the backslash \-
&nbsp;        i\.e\. the backslash is the last byte in the file\.

&nbsp;    S\_scan\_inputsymbol

&nbsp;        On something like
&nbsp;            $x = \<\\
&nbsp;        delimcpy\(\) returns a pointer beyond the end of string\, which
&nbsp;        immediately triggers this croak&#8203;:

&nbsp;            if \(s >= end\)
&nbsp;                Perl\_croak\(aTHX\_ "Unterminated \<> operator"\);

&nbsp;    Perl\_magic\_setenv&#8203;:

&nbsp;        Under taint\, in $ENV\{PATH\} = "ABC&#8203;:XYZ"\, it splits the path using
&nbsp;        delimcpy\(\) then examines each component to see whether it's
&nbsp;        non\-absolute or world\-writeable\.

&nbsp;        About the worst that could happen is in

&nbsp;            $ENV\{PATH\} = "/foo\\\\"

&nbsp;        where it would check the directory "/foo\\\\\\0" for
&nbsp;        world\-writeability\, rather than checking "/foo\\\\"\. But since
&nbsp;        system calls use \\0\-terminated strings anyway\, it makes no
&nbsp;        difference\.

\-\- 
I thought I was wrong once\, but I was mistaken\.

**Comment by p5pRT** [comment]
### From @iabyn

<details><summary>0001-Perl_delimcpy-handle-backslash-as-last-char.patch</summary>

```diff
From 1d409039e301d0d1d8200252d91cd2ad165995ab Mon Sep 17 00:00:00 2001
From: David Mitchell <davem@iabyn.com>
Date: Thu, 25 Aug 2016 17:48:34 +0100
Subject: [PATCH] Perl_delimcpy(): handle backslash as last char

[perl #129064] heap-buffer-overflow S_scan_heredoc

Perl_delimcpy() is supposed to copy a delimited string to another buffer;
it handles \-<delimiter> escapes, but if the backslash is the last
character in the src buffer, it could overrun the end of the buffer
slightly.

Also document slightly better what this function is supposed to do.
---
 t/op/heredoc.t | 12 +++++++++++-
 util.c         |  9 +++++++--
 2 files changed, 18 insertions(+), 3 deletions(-)

diff --git a/t/op/heredoc.t b/t/op/heredoc.t
index f47f7ce..13d1074 100644
--- a/t/op/heredoc.t
+++ b/t/op/heredoc.t
@@ -7,7 +7,7 @@ BEGIN {
 }
 
 use strict;
-plan(tests => 42);
+plan(tests => 43);
 
 
 # heredoc without newline (#65838)
@@ -115,4 +115,14 @@ HEREDOC
 	{},
 	"Don't assert parsing a here-doc if we hit EOF early"
     );
+
+    # [perl #129064] heap-buffer-overflow S_scan_heredoc
+    fresh_perl_like(
+        qq(<<`\\),
+        # valgrind and asan reports an error between these two lines
+        qr/^Unterminated delimiter for here document/,
+        {},
+        "delimcpy(): handle last char being backslash properly"
+    );
+
 }
diff --git a/util.c b/util.c
index 7748c6c..4579d1e 100644
--- a/util.c
+++ b/util.c
@@ -522,7 +522,12 @@ Free_t   Perl_mfree (Malloc_t where)
 
 #endif
 
-/* copy a string up to some (non-backslashed) delimiter, if any */
+/* copy a string up to some (non-backslashed) delimiter, if any.
+ * Converts \<delimiter> to <delimiter>, while leaves \<non-delimiter>
+ * as-is.
+ * Returns the position in the src string of the closing delimiter, if
+ * any, or returns fromend otherwise
+ * */
 
 char *
 Perl_delimcpy(char *to, const char *toend, const char *from, const char *fromend, int delim, I32 *retlen)
@@ -532,7 +537,7 @@ Perl_delimcpy(char *to, const char *toend, const char *from, const char *fromend
     PERL_ARGS_ASSERT_DELIMCPY;
 
     for (tolen = 0; from < fromend; from++, tolen++) {
-	if (*from == '\\') {
+	if (*from == '\\' && from + 1 < fromend) {
 	    if (from[1] != delim) {
 		if (to < toend)
 		    *to++ = *from;
-- 
2.4.11


```
</details>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Fri Aug 26 04&#8203;:19&#8203;:56 2016\, davem wrote&#8203;:
> The attached patch \(intended to be applied over Tony's pending heredoc
> fix\) fixes this\.

Which pending fix?

Tony

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, Sep 06\, 2016 at 09&#8203;:28&#8203;:52PM \-0700\, Tony Cook via RT wrote&#8203;:
> On Fri Aug 26 04&#8203;:19&#8203;:56 2016\, davem wrote&#8203;:
> > The attached patch \(intended to be applied over Tony's pending heredoc
> > fix\) fixes this\.
> 
> Which pending fix?

382450a68fa9cdd\, which you've now applied\.

I've now pushed my fix as 19e1655416b3c03817d6123958721515e146fc9f\.

\-\- 
I before E\. Except when it isn't\.

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
