### ISSUE TITLE
Perl_yyparse: Assertion `( (((PL_curcop == &PL_compiling ? PL_compiling.cop_hints : PL_curcop->cop_hints) & 0x1c000000) >> 26) == (0x1c000000 >> 26) && (((PL_curcop == &PL_compiling ? PL_compiling.cop

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15553]
Migrated from [rt.perl.org#129073](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129073) (status was 'resolved')

Searchable as RT129073$

**Comment by p5pRT** [comment]
### From @geeknik

Perl v5\.25\.4\-10\-g8d168aa

\./perl \-e '%\{p\{\};sub p\}\(\)'

perl&#8203;: perly\.y&#8203;:791&#8203;: int Perl\_yyparse\(int\)&#8203;: Assertion \`\( \(\(\(PL\_curcop == &PL\_compiling ? PL\_compiling\.cop\_hints : PL\_curcop\->cop\_hints\) & 0x1c000000\) >> 26\) == \(0x1c000000 >> 26\) && \(\(\(PL\_curcop == &PL\_compiling ? PL\_compiling\.cop\_hints : PL\_curcop\->cop\_hints\) & 0x00020000\) ? Perl\_feature\_is\_enabled\( \("" "signatures" ""\)\, \(sizeof\("signatures"\)\-1\)\) : \(0\)\) \)' failed\.

\#0  0x00007ffff6cf2067 in \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:56
\#1  0x00007ffff6cf3448 in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007ffff6ceb266 in \_\_assert\_fail\_base \(fmt=0x7ffff6e24238 "%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\,
&nbsp;    assertion=assertion@&#8203;entry=0xd6cd00 \<\.str50> "\( \(\(\(PL\_curcop == &PL\_compiling ? PL\_compiling\.cop\_hints : PL\_curcop\->cop\_hints\) & 0x1c000000\) >> 26\) == \(0x1c000000 >> 26\) && \(\(\(PL\_curcop == &PL\_compiling ? PL\_compiling\.cop\_hints : PL\_curcop\->cop\_h"\.\.\.\, file=file@&#8203;entry=0xd72f50 "perly\.y"\, line=line@&#8203;entry=791\,
&nbsp;    function=function@&#8203;entry=0xd6c9a0 \<\_\_PRETTY\_FUNCTION\_\_\.Perl\_yyparse> "int Perl\_yyparse\(int\)"\) at assert\.c&#8203;:92
\#3  0x00007ffff6ceb312 in \_\_GI\_\_\_assert\_fail \(
&nbsp;    assertion=0xd6cd00 \<\.str50> "\( \(\(\(PL\_curcop == &PL\_compiling ? PL\_compiling\.cop\_hints : PL\_curcop\->cop\_hints\) & 0x1c000000\) >> 26\) == \(0x1c000000 >> 26\) && \(\(\(PL\_curcop == &PL\_compiling ? PL\_compiling\.cop\_hints : PL\_curcop\->cop\_h"\.\.\.\, file=0xd72f50 "perly\.y"\, line=791\,
&nbsp;    function=0xd6c9a0 \<\_\_PRETTY\_FUNCTION\_\_\.Perl\_yyparse> "int Perl\_yyparse\(int\)"\) at assert\.c&#8203;:101
\#4  0x00000000006b9683 in Perl\_yyparse \(gramtype=\<optimized out>\) at perly\.y&#8203;:791
\#5  0x000000000059c502 in S\_parse\_body \(env=\<optimized out>\, xsinit=\<optimized out>\) at perl\.c&#8203;:2373
\#6  0x000000000059289d in perl\_parse \(my\_perl=\<optimized out>\, xsinit=\<optimized out>\, argc=\<optimized out>\, argv=\<optimized out>\, env=\<optimized out>\) at perl\.c&#8203;:1689
\#7  0x00000000004de836 in main \(argc=\<optimized out>\, argv=\<optimized out>\, env=\<optimized out>\) at perlmain\.c&#8203;:121

**Comment by p5pRT** [comment]
### From @cpansprout

On Wed Aug 24 16&#8203;:27&#8203;:33 2016\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> Perl v5\.25\.4\-10\-g8d168aa
> 
> \./perl \-e '%\{p\{\};sub p\}\(\)'

With a simple ‘\{sub f\}’\, the lexer emits a semicolon before the closing brace\.  Excerpt from \-DpT output&#8203;:

Reading a token&#8203;:
\#\#\# 1&#8203;:LEX\_NORMAL/XBLOCK "\}\\n"
\#\#\# forced token&#8203;:
\#\#\# \<== '\}'

\#\#\# \<== ';'

\(A ‘forced token’ is a pending token that will be emitted the next time yylex is called\.\)

With %\{p\{\}; before it\, it behaves differently&#8203;:

Reading a token&#8203;:
\#\#\# 1&#8203;:LEX\_NORMAL/XBLOCK "\}\(\)\\n"
\#\#\# 1&#8203;:LEX\_NORMAL/XOPERATOR "\(\)\\n"
\#\#\# \<== '\('

I have not looked into why\.

BTW\, perl interprets %\{p\{foo\}\} as %p\{foo\}\, and the parser starts to read the %\{p\{\.\.\. as a key/value slice\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

This is now fixed in bdc377e\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @mauke

Am 05\.09\.2016 um 00&#8203;:58 schrieb Father Chrysostomos via RT&#8203;:
> This is now fixed in bdc377e\.
>

\+                            if \(\!parser\->error\_count\) \{
\+                                assert\(FEATURE\_SIGNATURES\_IS\_ENABLED\);
\+                            \}

Why not  assert\(parser\->error\_count || FEATURE\_SIGNATURES\_IS\_ENABLED\); ?

\-\- 
Lukas Mai \<plokinom@&#8203;gmail\.com>

**Comment by p5pRT** [comment]
### From @cpansprout

On Wed Sep 07 23&#8203;:06&#8203;:18 2016\, plokinom@&#8203;gmail\.com wrote&#8203;:
> Am 05\.09\.2016 um 00&#8203;:58 schrieb Father Chrysostomos via RT&#8203;:
> > This is now fixed in bdc377e\.
> >
> 
> \+                            if \(\!parser\->error\_count\) \{
> \+                                assert\(FEATURE\_SIGNATURES\_IS\_ENABLED\);
> \+                            \}
> 
> Why not  assert\(parser\->error\_count || FEATURE\_SIGNATURES\_IS\_ENABLED\); ?
> 

I figured it would be harder to read that way\.  It would fail under the same circumstances anyway\, so it’s equivalent\.

\-\- 

Father Chrysostomos
