### ISSUE TITLE
Assertion Failure: pp_ctl.c:5140: MAGIC *S_doparseform(SV *)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15564]
Migrated from [rt.perl.org#129119](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129119) (status was 'resolved')

Searchable as RT129119$

**Comment by p5pRT** [comment]
### From @geeknik

Perl v5\.25\.4\-20\-gc2f7c0b\* and the attached script trigger this assertion failure\. Minimizing the script with afl\-tmin caused the assertion to go away\.

perl&#8203;: pp\_ctl\.c&#8203;:5140&#8203;: MAGIC \*S\_doparseform\(SV \*\)&#8203;: Assertion \`\!\(\(\(\(\_svpvx\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(\_svpvx\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_svpvx\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.

**Comment by p5pRT** [comment]
### From @geeknik

[assert61.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1420473/768135/assert61.gz)

**Comment by p5pRT** [comment]
### From @dcollinsn

On Sun Aug 28 18&#8203;:21&#8203;:51 2016\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> Perl v5\.25\.4\-20\-gc2f7c0b\* and the attached script trigger this
> assertion failure\. Minimizing the script with afl\-tmin caused the
> assertion to go away\.
> 
> perl&#8203;: pp\_ctl\.c&#8203;:5140&#8203;: MAGIC \*S\_doparseform\(SV \*\)&#8203;: Assertion
> \`\!\(\(\(\(\_svpvx\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) &&
> \(\(\(svtype\)\(\(\_svpvx\)\->sv\_flags & 0xff\)\) == SVt\_PVGV ||
> \(\(svtype\)\(\(\_svpvx\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.

Minimized by hand to&#8203;:

\./perl \-e 'print "map\{formline\*0\}\<DATA>\_\_END\_\_\\n\\n0"' | \./perl \-Ilib

No valgrind errors\, backtrace below&#8203;:

\(gdb\) run
Starting program&#8203;: /home/dcollins/toolchain/perl/perl \-Ilib assert61min
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
perl&#8203;: pp\_ctl\.c&#8203;:5140&#8203;: S\_doparseform&#8203;: Assertion \`\!isGV\_with\_GP\(\_svpvx\)' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6cf31c8 in \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:54
54      \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;: No such file or directory\.
\(gdb\) bt
\#0  0x00007ffff6cf31c8 in \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:54
\#1  0x00007ffff6cf464a in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007ffff6cec107 in \_\_assert\_fail\_base \(fmt=\<optimized out>\, assertion=assertion@&#8203;entry=0x602f1e "\!isGV\_with\_GP\(\_svpvx\)"\, file=file@&#8203;entry=0x67e154 "pp\_ctl\.c"\, line=line@&#8203;entry=5140\,
&nbsp;    function=function@&#8203;entry=0x67f268 \<\_\_PRETTY\_FUNCTION\_\_\.17530> "S\_doparseform"\) at assert\.c&#8203;:92
\#3  0x00007ffff6cec1b2 in \_\_GI\_\_\_assert\_fail \(assertion=assertion@&#8203;entry=0x602f1e "\!isGV\_with\_GP\(\_svpvx\)"\, file=file@&#8203;entry=0x67e154 "pp\_ctl\.c"\, line=line@&#8203;entry=5140\,
&nbsp;    function=function@&#8203;entry=0x67f268 \<\_\_PRETTY\_FUNCTION\_\_\.17530> "S\_doparseform"\) at assert\.c&#8203;:101
\#4  0x0000000000577718 in S\_doparseform \(sv=0x8e7848\) at pp\_ctl\.c&#8203;:5140
\#5  Perl\_pp\_formline \(\) at pp\_ctl\.c&#8203;:494
\#6  0x00000000004d7792 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2234
\#7  0x0000000000451f13 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2525
\#8  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2448
\#9  0x0000000000420805 in main \(argc=\<optimized out>\, argv=\<optimized out>\, env=\<optimized out>\) at perlmain\.c&#8203;:123
\(gdb\) f 4
\#4  0x0000000000577718 in S\_doparseform \(sv=0x8e7848\) at pp\_ctl\.c&#8203;:5140
5140                  && strnEQ\(SvPVX\(old\)\, SvPVX\(sv\)\, len\)
\(gdb\) l
5135        if \(mg\) \{
5136            /\* still the same as previously\-compiled string? \*/
5137            SV \*old = mg\->mg\_obj;
5138            if \( \!\(\!\!SvUTF8\(old\) ^ \!\!SvUTF8\(sv\)\)
5139                  && len == SvCUR\(old\)
5140                  && strnEQ\(SvPVX\(old\)\, SvPVX\(sv\)\, len\)
5141            \) \{
5142                DEBUG\_f\(PerlIO\_printf\(Perl\_debug\_log\,"Re\-using compiled format\\n"\)\);
5143                return mg;
5144            \}
\(gdb\) info locals
\_svpvx = 0x8e7848
old = 0x8e73b0
len = 8
send = \<optimized out>
skipspaces = 0
fops = \<optimized out>
fpc = \<optimized out>
ischop = \<optimized out>
sv\_copy = \<optimized out>
base = 0x0
postspace = false
arg = \<optimized out>
s = 0x8e1280 "\*main&#8203;::0"
noblank = false
unchopnum = false
maxops = 12
mg = 0x8e07f0
repeat = false
linepc = 0x0
\(gdb\) p \*old
$1 = \{sv\_any = 0x8d3e70\, sv\_refcnt = 1\, sv\_flags = 17411\, sv\_u = \{svu\_pv = 0x8ef6b0 "\*main&#8203;::0"\, svu\_iv = 9369264\, svu\_uv = 9369264\, svu\_nv = 4\.629031469217141e\-317\, svu\_rv = 0x8ef6b0\,
&nbsp;    svu\_rx = 0x8ef6b0\, svu\_array = 0x8ef6b0\, svu\_hash = 0x8ef6b0\, svu\_gp = 0x8ef6b0\, svu\_fp = 0x8ef6b0\}\}
\(gdb\) p \*sv
$2 = \{sv\_any = 0x8ea060\, sv\_refcnt = 2\, sv\_flags = 4227081\, sv\_u = \{svu\_pv = 0x8e7ed0 "\`x\\216"\, svu\_iv = 9338576\, svu\_uv = 9338576\, svu\_nv = 4\.6138695826775648e\-317\, svu\_rv = 0x8e7ed0\,
&nbsp;    svu\_rx = 0x8e7ed0\, svu\_array = 0x8e7ed0\, svu\_hash = 0x8e7ed0\, svu\_gp = 0x8e7ed0\, svu\_fp = 0x8e7ed0\}\}
\(gdb\)


\-\- 
Respectfully\,
Dan Collins

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Sun Aug 28 18&#8203;:21&#8203;:51 2016\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> Perl v5\.25\.4\-20\-gc2f7c0b\* and the attached script trigger this
> assertion failure\. Minimizing the script with afl\-tmin caused the
> assertion to go away\.
> 
> perl&#8203;: pp\_ctl\.c&#8203;:5140&#8203;: MAGIC \*S\_doparseform\(SV \*\)&#8203;: Assertion
> \`\!\(\(\(\(\_svpvx\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) &&
> \(\(\(svtype\)\(\(\_svpvx\)\->sv\_flags & 0xff\)\) == SVt\_PVGV ||
> \(\(svtype\)\(\(\_svpvx\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.

Minimized by hand to&#8203;:

\./perl \-e 'print "map\{formline\*0\}\<DATA>\_\_END\_\_\\n\\n0"' | \./perl \-Ilib

No valgrind errors\, backtrace below&#8203;:

\(gdb\) run
Starting program&#8203;: /home/dcollins/toolchain/perl/perl \-Ilib assert61min
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
perl&#8203;: pp\_ctl\.c&#8203;:5140&#8203;: S\_doparseform&#8203;: Assertion \`\!isGV\_with\_GP\(\_svpvx\)' failed\.

Program received signal SIGABRT\, Aborted\.
0x00007ffff6cf31c8 in \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:54
54      \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;: No such file or directory\.
\(gdb\) bt
\#0  0x00007ffff6cf31c8 in \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:54
\#1  0x00007ffff6cf464a in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007ffff6cec107 in \_\_assert\_fail\_base \(fmt=\<optimized out>\, assertion=assertion@&#8203;entry=0x602f1e "\!isGV\_with\_GP\(\_svpvx\)"\, file=file@&#8203;entry=0x67e154 "pp\_ctl\.c"\, line=line@&#8203;entry=5140\,
&nbsp;    function=function@&#8203;entry=0x67f268 \<\_\_PRETTY\_FUNCTION\_\_\.17530> "S\_doparseform"\) at assert\.c&#8203;:92
\#3  0x00007ffff6cec1b2 in \_\_GI\_\_\_assert\_fail \(assertion=assertion@&#8203;entry=0x602f1e "\!isGV\_with\_GP\(\_svpvx\)"\, file=file@&#8203;entry=0x67e154 "pp\_ctl\.c"\, line=line@&#8203;entry=5140\,
&nbsp;    function=function@&#8203;entry=0x67f268 \<\_\_PRETTY\_FUNCTION\_\_\.17530> "S\_doparseform"\) at assert\.c&#8203;:101
\#4  0x0000000000577718 in S\_doparseform \(sv=0x8e7848\) at pp\_ctl\.c&#8203;:5140
\#5  Perl\_pp\_formline \(\) at pp\_ctl\.c&#8203;:494
\#6  0x00000000004d7792 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2234
\#7  0x0000000000451f13 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2525
\#8  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2448
\#9  0x0000000000420805 in main \(argc=\<optimized out>\, argv=\<optimized out>\, env=\<optimized out>\) at perlmain\.c&#8203;:123
\(gdb\) f 4
\#4  0x0000000000577718 in S\_doparseform \(sv=0x8e7848\) at pp\_ctl\.c&#8203;:5140
5140                  && strnEQ\(SvPVX\(old\)\, SvPVX\(sv\)\, len\)
\(gdb\) l
5135        if \(mg\) \{
5136            /\* still the same as previously\-compiled string? \*/
5137            SV \*old = mg\->mg\_obj;
5138            if \( \!\(\!\!SvUTF8\(old\) ^ \!\!SvUTF8\(sv\)\)
5139                  && len == SvCUR\(old\)
5140                  && strnEQ\(SvPVX\(old\)\, SvPVX\(sv\)\, len\)
5141            \) \{
5142                DEBUG\_f\(PerlIO\_printf\(Perl\_debug\_log\,"Re\-using compiled format\\n"\)\);
5143                return mg;
5144            \}
\(gdb\) info locals
\_svpvx = 0x8e7848
old = 0x8e73b0
len = 8
send = \<optimized out>
skipspaces = 0
fops = \<optimized out>
fpc = \<optimized out>
ischop = \<optimized out>
sv\_copy = \<optimized out>
base = 0x0
postspace = false
arg = \<optimized out>
s = 0x8e1280 "\*main&#8203;::0"
noblank = false
unchopnum = false
maxops = 12
mg = 0x8e07f0
repeat = false
linepc = 0x0
\(gdb\) p \*old
$1 = \{sv\_any = 0x8d3e70\, sv\_refcnt = 1\, sv\_flags = 17411\, sv\_u = \{svu\_pv = 0x8ef6b0 "\*main&#8203;::0"\, svu\_iv = 9369264\, svu\_uv = 9369264\, svu\_nv = 4\.629031469217141e\-317\, svu\_rv = 0x8ef6b0\,
&nbsp;    svu\_rx = 0x8ef6b0\, svu\_array = 0x8ef6b0\, svu\_hash = 0x8ef6b0\, svu\_gp = 0x8ef6b0\, svu\_fp = 0x8ef6b0\}\}
\(gdb\) p \*sv
$2 = \{sv\_any = 0x8ea060\, sv\_refcnt = 2\, sv\_flags = 4227081\, sv\_u = \{svu\_pv = 0x8e7ed0 "\`x\\216"\, svu\_iv = 9338576\, svu\_uv = 9338576\, svu\_nv = 4\.6138695826775648e\-317\, svu\_rv = 0x8e7ed0\,
&nbsp;    svu\_rx = 0x8e7ed0\, svu\_array = 0x8e7ed0\, svu\_hash = 0x8e7ed0\, svu\_gp = 0x8e7ed0\, svu\_fp = 0x8e7ed0\}\}
\(gdb\)


\-\- 
Respectfully\,
Dan Collins

**Comment by p5pRT** [comment]
### From @cpansprout

On Sun Aug 28 20&#8203;:39&#8203;:54 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> On Sun Aug 28 18&#8203;:21&#8203;:51 2016\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> > Perl v5\.25\.4\-20\-gc2f7c0b\* and the attached script trigger this
> > assertion failure\. Minimizing the script with afl\-tmin caused the
> > assertion to go away\.
> >
> > perl&#8203;: pp\_ctl\.c&#8203;:5140&#8203;: MAGIC \*S\_doparseform\(SV \*\)&#8203;: Assertion
> > \`\!\(\(\(\(\_svpvx\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) &&
> > \(\(\(svtype\)\(\(\_svpvx\)\->sv\_flags & 0xff\)\) == SVt\_PVGV ||
> > \(\(svtype\)\(\(\_svpvx\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.
> 
> Minimized by hand to&#8203;:
> 
> \./perl \-e 'print "map\{formline\*0\}\<DATA>\_\_END\_\_\\n\\n0"' | \./perl \-Ilib

$ \./miniperl \-e 'formline \*0 for ""\, 0'
Assertion failed&#8203;: \(\!isGV\_with\_GP\(\_svpvx\)\)\, function S\_doparseform\, file pp\_ctl\.c\, line 5140\.
Abort trap&#8203;: 6

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Wed\, Sep 07\, 2016 at 12&#8203;:54&#8203;:02PM \-0700\, Father Chrysostomos via RT wrote&#8203;:
> On Sun Aug 28 20&#8203;:39&#8203;:54 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> > On Sun Aug 28 18&#8203;:21&#8203;:51 2016\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> > > Perl v5\.25\.4\-20\-gc2f7c0b\* and the attached script trigger this
> > > assertion failure\. Minimizing the script with afl\-tmin caused the
> > > assertion to go away\.
> > >
> > > perl&#8203;: pp\_ctl\.c&#8203;:5140&#8203;: MAGIC \*S\_doparseform\(SV \*\)&#8203;: Assertion
> > > \`\!\(\(\(\(\_svpvx\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) &&
> > > \(\(\(svtype\)\(\(\_svpvx\)\->sv\_flags & 0xff\)\) == SVt\_PVGV ||
> > > \(\(svtype\)\(\(\_svpvx\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.
> > 
> > Minimized by hand to&#8203;:
> > 
> > \./perl \-e 'print "map\{formline\*0\}\<DATA>\_\_END\_\_\\n\\n0"' | \./perl \-Ilib
> 
> $ \./miniperl \-e 'formline \*0 for ""\, 0'
> Assertion failed&#8203;: \(\!isGV\_with\_GP\(\_svpvx\)\)\, function S\_doparseform\, file pp\_ctl\.c\, line 5140\.
> Abort trap&#8203;: 6

Fixed by the following; closing

Author&#8203;: Tony Cook \<tony@&#8203;develop\-help\.com>
Date&#8203;:   Tue Feb 7 16&#8203;:14&#8203;:53 2017 \+1100

&nbsp;    \(perl \#130722\) don't call SvPVX\(\) on a glob
&nbsp;    
&nbsp;    S\_doparseform\(\) called SvPVX\(\) on the format argument\, which
&nbsp;    produced an assertion failure when the format was supplied as a
&nbsp;    glob\.
&nbsp;    
&nbsp;    Since S\_doparseform\(\) calls SvPV\(\) initially and stores the result\,
&nbsp;    just use that result\.


\-\- 
Counsellor Troi states something other than the blindingly obvious\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#16

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
