### ISSUE TITLE
global-buffer-overflow S_finalize_op (op.c:2634)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15560]
Migrated from [rt.perl.org#129099](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129099) (status was 'resolved')

Searchable as RT129099$

**Comment by p5pRT** [comment]
### From @geeknik

Perl v5\.25\.4\-20\-gc2f7c0b\, \+ AFL \+ ASAN \+ libdislocator

\./perl \-e 'BEGIN\(\)&#8203;:y\(\)'

Prototype mismatch&#8203;: sub main&#8203;::BEGIN \(\) vs none at over6 line 1\.
=================================================================
==23205==ERROR&#8203;: AddressSanitizer&#8203;: global\-buffer\-overflow on address
0x000000ed72b4 at pc 0x0000004f1e35 bp 0x7fff9e4cca50 sp 0x7fff9e4cca48
READ of size 4 at 0x000000ed72b4 thread T0
&nbsp;    \#0 0x4f1e34 in S\_finalize\_op /root/perl/op\.c&#8203;:2634&#8203;:9
&nbsp;    \#1 0x4f1b05 in S\_finalize\_op /root/perl/op\.c&#8203;:2671&#8203;:6
&nbsp;    \#2 0x4f1b05 in S\_finalize\_op /root/perl/op\.c&#8203;:2671&#8203;:6
&nbsp;    \#3 0x4f1b05 in S\_finalize\_op /root/perl/op\.c&#8203;:2671&#8203;:6
&nbsp;    \#4 0x4f09ed in Perl\_finalize\_optree /root/perl/op\.c&#8203;:2473&#8203;:5
&nbsp;    \#5 0x51c9ea in Perl\_newATTRSUB\_x /root/perl/op\.c&#8203;:8784&#8203;:5
&nbsp;    \#6 0x5239d2 in Perl\_utilize /root/perl/op\.c&#8203;:6205&#8203;:5
&nbsp;    \#7 0x524d42 in Perl\_vload\_module /root/perl/op\.c&#8203;:6352&#8203;:5
&nbsp;    \#8 0x4f9fa9 in Perl\_load\_module /root/perl/op\.c&#8203;:6295&#8203;:5
&nbsp;    \#9 0x51cdd2 in Perl\_newATTRSUB\_x /root/perl/op\.c&#8203;:8798&#8203;:2
&nbsp;    \#10 0x6afc50 in Perl\_yyparse /root/perl/perly\.y&#8203;:296&#8203;:12
&nbsp;    \#11 0x59c4e1 in S\_parse\_body /root/perl/perl\.c&#8203;:2373&#8203;:9
&nbsp;    \#12 0x59287c in perl\_parse /root/perl/perl\.c&#8203;:1689&#8203;:2
&nbsp;    \#13 0x4de815 in main /root/perl/perlmain\.c&#8203;:121&#8203;:18
&nbsp;    \#14 0x7fe24eb19b44 in \_\_libc\_start\_main
/build/glibc\-uPj9cH/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#15 0x4de4ac in \_start \(/root/perl/perl\+0x4de4ac\)

0x000000ed72b4 is located 0 bytes to the right of global variable
'PL\_opargs' defined in '\./opcode\.h&#8203;:1796&#8203;:14' \(0xed6c80\) of size 1588
SUMMARY&#8203;: AddressSanitizer&#8203;: global\-buffer\-overflow /root/perl/op\.c&#8203;:2634
S\_finalize\_op
Shadow bytes around the buggy address&#8203;:
&nbsp;  0x0000801d2e00&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0000801d2e10&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0000801d2e20&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0000801d2e30&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0000801d2e40&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0000801d2e50&#8203;: 00 00 00 00 00 00\[04\]f9 f9 f9 f9 f9 f9 f9 f9 f9
&nbsp;  0x0000801d2e60&#8203;: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
&nbsp;  0x0000801d2e70&#8203;: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
&nbsp;  0x0000801d2e80&#8203;: f9 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
&nbsp;  0x0000801d2e90&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0000801d2ea0&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend \(one shadow byte represents 8 application bytes\)&#8203;:
&nbsp;  Addressable&#8203;:           00
&nbsp;  Partially addressable&#8203;: 01 02 03 04 05 06 07
&nbsp;  Heap left redzone&#8203;:       fa
&nbsp;  Heap right redzone&#8203;:      fb
&nbsp;  Freed heap region&#8203;:       fd
&nbsp;  Stack left redzone&#8203;:      f1
&nbsp;  Stack mid redzone&#8203;:       f2
&nbsp;  Stack right redzone&#8203;:     f3
&nbsp;  Stack partial redzone&#8203;:   f4
&nbsp;  Stack after return&#8203;:      f5
&nbsp;  Stack use after scope&#8203;:   f8
&nbsp;  Global redzone&#8203;:          f9
&nbsp;  Global init order&#8203;:       f6
&nbsp;  Poisoned by user&#8203;:        f7
&nbsp;  Container overflow&#8203;:      fc
&nbsp;  ASan internal&#8203;:           fe
==23205==ABORTING

**Comment by p5pRT** [comment]
### From @iabyn

On Fri\, Aug 26\, 2016 at 06&#8203;:54&#8203;:52PM \-0700\, Brian Carpenter wrote&#8203;:
> \./perl \-e 'BEGIN\(\)&#8203;:y\(\)'
> 

This can only occur for the unusual \(some might say bizarre\) action of
applying an attribute to a sub called BEGIN\. The attribute application
causes BEGIN \{ require attrributes; \.\.\. \} to be compiled\, which causes
problems with BEGIN being re\-defined while BEGIN is still being defined\.

So its not a security issue\.

I've fixed it with the following commit\. I've also added som asserts with
v5\.25\.4\-75\-g68d1ee8 to better spot things like this in future\.

I'll move this ticket to public queue and close it in a few days unless
anyone objects\.

commit d1da3640384b1f8221ffa322a0ce6f7ff663a34c
Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
AuthorDate&#8203;: Mon Sep 5 11&#8203;:52&#8203;:23 2016 \+0100
Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
CommitDate&#8203;: Mon Sep 5 12&#8203;:55&#8203;:57 2016 \+0100

&nbsp;    avoid using freed ops on BEGIN :attr \{\}
&nbsp;    
&nbsp;    If a BEGIN sub has a code attribute applied \(no idea why you would want to
&nbsp;    do such a thing\, but it's not illegal\) then part of applying the attribute
&nbsp;    is to do 'use attributes'\, which compiles
&nbsp;    
&nbsp;        BEGIN \{ require "attributes"; attributes\->import\(AAA\) \}
&nbsp;    
&nbsp;    so we end up compiling a BEGIN while in the middle of compiling a BEGIN\.
&nbsp;    The part of Perl\_newATTRSUB\_x\(\) that under some circumstances copies
&nbsp;    the body of the newly\-compiled CV to the old CV which occupies the name
&nbsp;    slot\, kicks in here\.
&nbsp;    
&nbsp;    Since the ops that make up the AAA above were allocated from the old
&nbsp;    BEGIN's op slabs\, they get prematurely freed when the old BEGIN's
&nbsp;    ops are discarded by the SvREFCNT\_dec\(PL\_compcv\)\.
&nbsp;    
&nbsp;    The simplest fix is to just avoid the copy if we're compiling a BEGIN\.



\-\- 
Music lesson&#8203;: a symbiotic relationship whereby a pupil's embellishments
concerning the amount of practice performed since the last lesson are
rewarded with embellishments from the teacher concerning the pupil's
progress over the corresponding period\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
