### ISSUE TITLE
null ptr deref, segfault Perl_newSVpv (sv.c:9218)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15562]
Migrated from [rt.perl.org#129105](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129105) (status was 'rejected')

Searchable as RT129105$

**Comment by p5pRT** [comment]
### From @geeknik

Fuzzing Perl v5\.25\.4\-20\-gc2f7c0b\* with AFL\, ASAN and libdislocator\.

\./perl \-e 'unpack\+p\,w0000000'

==23795==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000000 \(pc 0x7f648b2aec3a bp 0x7ffd3b494e80 sp 0x7ffd3b494618 T0\)
&nbsp;    \#0 0x7f648b2aec39 in strlen /build/glibc\-uPj9cH/glibc\-2\.19/string/\.\./sysdeps/x86\_64/strlen\.S&#8203;:76
&nbsp;    \#1 0x4abacb in \_\_interceptor\_strlen \(/root/perl/perl\+0x4abacb\)
&nbsp;    \#2 0x962587 in Perl\_newSVpv /root/perl/sv\.c&#8203;:9218&#8203;:5
&nbsp;    \#3 0xc547ed in S\_unpack\_rec /root/perl/pp\_pack\.c&#8203;:1564&#8203;:3
&nbsp;    \#4 0xc4b955 in Perl\_unpackstring /root/perl/pp\_pack\.c&#8203;:835&#8203;:12
&nbsp;    \#5 0xc61499 in Perl\_pp\_unpack /root/perl/pp\_pack\.c&#8203;:1839&#8203;:11
&nbsp;    \#6 0x7f1c63 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2234&#8203;:23
&nbsp;    \#7 0x5a10a6 in S\_run\_body /root/perl/perl\.c&#8203;:2525&#8203;:2
&nbsp;    \#8 0x5a10a6 in perl\_run /root/perl/perl\.c&#8203;:2448
&nbsp;    \#9 0x4de6cd in main /root/perl/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#10 0x7f648b24eb44 in \_\_libc\_start\_main /build/glibc\-uPj9cH/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#11 0x4de33c in \_start \(/root/perl/perl\+0x4de33c\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /build/glibc\-uPj9cH/glibc\-2\.19/string/\.\./sysdeps/x86\_64/strlen\.S&#8203;:76 strlen
==23795==ABORTING

**Comment by p5pRT** [comment]
### From @cpansprout

On Sat Aug 27 14&#8203;:15&#8203;:58 2016\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> Fuzzing Perl v5\.25\.4\-20\-gc2f7c0b\* with AFL\, ASAN and libdislocator\.
> 
> \./perl \-e 'unpack\+p\,w0000000'

perlfunc \-f unpack&#8203;:

&nbsp;               The "p" and "P" formats should be used with care\.  Since Perl
&nbsp;               has no way of checking whether the value passed to "unpack\(\)"
&nbsp;               corresponds to a valid memory location\, passing a pointer value
&nbsp;               that's not known to be valid is likely to have disastrous
&nbsp;               consequences\.

I think any tickets concerning crashes with unpack\("p"\, \.\.\.\) will just have to be rejected as not\-a\-bug\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Sat Aug 27 15&#8203;:27&#8203;:59 2016\, sprout wrote&#8203;:
> On Sat Aug 27 14&#8203;:15&#8203;:58 2016\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> > Fuzzing Perl v5\.25\.4\-20\-gc2f7c0b\* with AFL\, ASAN and libdislocator\.
> >
> > \./perl \-e 'unpack\+p\,w0000000'
> 
> perlfunc \-f unpack&#8203;:
> 
> The "p" and "P" formats should be used with care\.  Since Perl
> has no way of checking whether the value passed to "unpack\(\)"
> corresponds to a valid memory location\, passing a pointer value
> that's not known to be valid is likely to have disastrous
> consequences\.
> 
> I think any tickets concerning crashes with unpack\("p"\, \.\.\.\) will just
> have to be rejected as not\-a\-bug\.

Same with&#8203;:

$ \./perl \-e 'kill 11\, $$'
Segmentation fault&#8203;: 11

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @dcollinsn

Agreed with Father Chrysostomos\. This came up a few months ago when I submitted the same ticket\. Unpack\, kill\, \-u\, and dump are all "supposed to" \- or at least allowed to \- dump core\. Closing \- but reopen if you disagree\.

\-\- 
Respectfully\,
Dan Collins

**Comment by p5pRT** [comment]
@dcollinsn - Status changed from 'open' to 'rejected'
