### ISSUE TITLE
Assertion `((((_gvstash)->sv_flags & (0x00004000|0x00008000)) == 0x00008000) && (((svtype)((_gvstash)->sv_flags & 0xff)) == SVt_PVGV || ((svtype)((_gvstash)->sv_flags & 0xff)) == SVt_PVLV))' failed (g

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15567]
Migrated from [rt.perl.org#129126](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129126) (status was 'resolved')

Searchable as RT129126$

**Comment by p5pRT** [comment]
### From @geeknik

\./perl \-Dx \-e 'END\{\}'

perl&#8203;: gv\.c&#8203;:2380&#8203;: void Perl\_gv\_fullname4\(SV \*\, const GV \*\, const char \*\, \_Bool\)&#8203;: Assertion \`\(\(\(\(\_gvstash\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(\_gvstash\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_gvstash\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.
Aborted

\#0  0x00007ffff6cf2067 in \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:56
\#1  0x00007ffff6cf3448 in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007ffff6ceb266 in \_\_assert\_fail\_base \(fmt=0x7ffff6e24238 "%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\,
&nbsp;    assertion=assertion@&#8203;entry=0x602a58 "\(\(\(\(\_gvstash\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(\_gvstash\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_gvstash\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)"\, file=file@&#8203;entry=0x63f7a4 "gv\.c"\, line=line@&#8203;entry=2380\,
&nbsp;    function=function@&#8203;entry=0x645490 \<\_\_PRETTY\_FUNCTION\_\_\.17492> "Perl\_gv\_fullname4"\) at assert\.c&#8203;:92
\#3  0x00007ffff6ceb312 in \_\_GI\_\_\_assert\_fail \(
&nbsp;    assertion=assertion@&#8203;entry=0x602a58 "\(\(\(\(\_gvstash\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(\_gvstash\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_gvstash\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)"\, file=file@&#8203;entry=0x63f7a4 "gv\.c"\, line=line@&#8203;entry=2380\,
&nbsp;    function=function@&#8203;entry=0x645490 \<\_\_PRETTY\_FUNCTION\_\_\.17492> "Perl\_gv\_fullname4"\) at assert\.c&#8203;:101
\#4  0x0000000000453dcf in Perl\_gv\_fullname4 \(sv=sv@&#8203;entry=0x9278b0\, gv=gv@&#8203;entry=0x927880\, prefix=prefix@&#8203;entry=0x0\, keepmain=keepmain@&#8203;entry=true\) at gv\.c&#8203;:2380
\#5  0x00000000004ce175 in Perl\_dump\_sub\_perl \(gv=gv@&#8203;entry=0x927880\, justperl=justperl@&#8203;entry=false\) at dump\.c&#8203;:615
\#6  0x00000000004ce3cc in Perl\_dump\_sub \(gv=gv@&#8203;entry=0x927880\) at dump\.c&#8203;:598
\#7  0x00000000004240e8 in S\_process\_special\_blocks \(floor=floor@&#8203;entry=39\, fullname=fullname@&#8203;entry=0x92c310 "END"\, gv=gv@&#8203;entry=0x927880\, cv=cv@&#8203;entry=0x927850\)
&nbsp;    at op\.c&#8203;:8913
\#8  0x000000000043fd24 in Perl\_newATTRSUB\_x \(floor=\<optimized out>\, o=\<optimized out>\, proto=0x0\, attrs=0x0\, block=\<optimized out>\, o\_is\_gv=\<optimized out>\)
&nbsp;    at op\.c&#8203;:8831
\#9  0x000000000048cb32 in Perl\_yyparse \(gramtype=0\) at perly\.y&#8203;:297
\#10 0x0000000000450cc8 in S\_parse\_body \(env=env@&#8203;entry=0x0\, xsinit=xsinit@&#8203;entry=0x421940 \<xs\_init>\) at perl\.c&#8203;:2373
\#11 0x000000000045285d in perl\_parse \(my\_perl=\<optimized out>\, xsinit=xsinit@&#8203;entry=0x421940 \<xs\_init>\, argc=4\, argv=0x7fffffffe6a8\, env=env@&#8203;entry=0x0\)
&nbsp;    at perl\.c&#8203;:1689
\#12 0x00000000004217b0 in main \(argc=4\, argv=0x7fffffffe6a8\, env=0x7fffffffe6d0\) at perlmain\.c&#8203;:121

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Fixed by 27b4ba23e0a765dcb0c320a5bd4590c45aad6820\.

\-zefram

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
