### ISSUE TITLE
null ptr deref, segfault Perl_sv_vcatpvfn_flags (sv.c:12398)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15563]
Migrated from [rt.perl.org#129106](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129106) (status was 'resolved')

Searchable as RT129106$

**Comment by p5pRT** [comment]
### From @geeknik

Fuzzing Perl v5\.25\.4\-20\-gc2f7c0b\* with AFL\, ASAN and libdislocator\.

1713 lines of Debug output later\.\.\.
http&#8203;://pastebin\.com/JiMN4fZP

==19229==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000038 \(pc 0x00000097c6ee bp 0x7fffba9d9130 sp 0x7fffba9d8b80 T0\)
&nbsp;    \#0 0x97c6ed in Perl\_sv\_vcatpvfn\_flags /root/perl/sv\.c&#8203;:12398&#8203;:21
&nbsp;    \#1 0x967dc8 in Perl\_sv\_vsetpvfn /root/perl/sv\.c&#8203;:10815&#8203;:5
&nbsp;    \#2 0x967dc8 in Perl\_vnewSVpvf /root/perl/sv\.c&#8203;:9429
&nbsp;    \#3 0xc23d60 in PerlIO\_vprintf /root/perl/perlio\.c&#8203;:4977&#8203;:10
&nbsp;    \#4 0x7d4cd9 in Perl\_dump\_vindent /root/perl/dump\.c&#8203;:520&#8203;:5
&nbsp;    \#5 0x7d4cd9 in Perl\_dump\_indent /root/perl/dump\.c&#8203;:511
&nbsp;    \#6 0x7e0887 in Perl\_do\_sv\_dump /root/perl/dump\.c&#8203;:1580&#8203;:2
&nbsp;    \#7 0x7f12a2 in Perl\_sv\_dump /root/perl/dump\.c&#8203;:2193&#8203;:2
&nbsp;    \#8 0x9478b4 in Perl\_sv\_clear /root/perl/sv\.c&#8203;:6639&#8203;:4
&nbsp;    \#9 0x94c452 in Perl\_sv\_free2 /root/perl/sv\.c&#8203;:6956&#8203;:9
&nbsp;    \#10 0x4e38b7 in S\_SvREFCNT\_dec /root/perl/\./inline\.h&#8203;:189&#8203;:6
&nbsp;    \#11 0x4e38b7 in Perl\_op\_clear /root/perl/op\.c&#8203;:973
&nbsp;    \#12 0x4e2195 in Perl\_op\_free /root/perl/op\.c&#8203;:854&#8203;:9
&nbsp;    \#13 0x4e1de5 in Perl\_op\_free /root/perl/op\.c&#8203;:837&#8203;:21
&nbsp;    \#14 0xa23a72 in Perl\_leave\_scope /root/perl/scope\.c&#8203;:1109&#8203;:6
&nbsp;    \#15 0xa56865 in S\_pop\_eval\_context\_maybe\_croak /root/perl/pp\_ctl\.c&#8203;:1605&#8203;:5
&nbsp;    \#16 0xa55f26 in Perl\_die\_unwind /root/perl/pp\_ctl\.c&#8203;:1733&#8203;:13
&nbsp;    \#17 0x7ffa2f in Perl\_vcroak /root/perl/util\.c&#8203;:1791&#8203;:5
&nbsp;    \#18 0x7ff91c in Perl\_die /root/perl/util\.c&#8203;:1722&#8203;:5
&nbsp;    \#19 0x9b7459 in Perl\_pp\_divide /root/perl/pp\.c&#8203;:1555&#8203;:17
&nbsp;    \#20 0x7f1c63 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2234&#8203;:23
&nbsp;    \#21 0x5a10a6 in S\_run\_body /root/perl/perl\.c&#8203;:2525&#8203;:2
&nbsp;    \#22 0x5a10a6 in perl\_run /root/perl/perl\.c&#8203;:2448
&nbsp;    \#23 0x4de6cd in main /root/perl/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#24 0x7f74425e5b44 in \_\_libc\_start\_main /build/glibc\-uPj9cH/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#25 0x4de33c in \_start \(/root/perl/perl\+0x4de33c\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /root/perl/sv\.c&#8203;:12398 Perl\_sv\_vcatpvfn\_flags
==19229==ABORTING

**Comment by p5pRT** [comment]
### From @geeknik

[null65.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1420275/767995/null65.gz)

**Comment by p5pRT** [comment]
### From @cpansprout

Shorter&#8203;:

$ \./miniperl \-DC \-e'eval "l/A"'

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Sat Aug 27 15&#8203;:33&#8203;:20 2016\, sprout wrote&#8203;:
> Shorter&#8203;:
> 
> $ \./miniperl \-DC \-e'eval "l/A"'
> 

This is now fixed in 6b42170\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
