### ISSUE TITLE
null ptr deref, segfault in Perl_pp_negate pp.c:2549

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15579]
Migrated from [rt.perl.org#129167](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129167) (status was 'resolved')

Searchable as RT129167$

**Comment by p5pRT** [comment]
### From @geeknik

v5\.25\.4\-27\-gf16e7fa

\./perl \-e '\-splice@&#8203;a\,$\#a=0'

==11739==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x00000000000c \(pc 0x0000009c9e00 bp 0x6210000113b8 sp 0x7ffc656105c0 T0\)
&nbsp;    \#0 0x9c9dff in Perl\_pp\_negate /home/geeknik/perl/pp\.c&#8203;:2549&#8203;:5
&nbsp;    \#1 0x7f2623 in Perl\_runops\_debug /home/geeknik/perl/dump\.c&#8203;:2234&#8203;:23
&nbsp;    \#2 0x5a10c6 in S\_run\_body /home/geeknik/perl/perl\.c&#8203;:2525&#8203;:2
&nbsp;    \#3 0x5a10c6 in perl\_run /home/geeknik/perl/perl\.c&#8203;:2448
&nbsp;    \#4 0x4de6cd in main /home/geeknik/perl/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#5 0x7fb0491e6b44 in \_\_libc\_start\_main /build/glibc\-uPj9cH/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#6 0x4de33c in \_start \(/home/geeknik/perl/perl\+0x4de33c\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /home/geeknik/perl/pp\.c&#8203;:2549 Perl\_pp\_negate
==11739==ABORTING

Program received signal SIGSEGV\, Segmentation fault\.
0x000000000054d9cb in Perl\_pp\_negate \(\) at pp\.c&#8203;:2549
2549        tryAMAGICun\_MG\(neg\_amg\, AMGf\_numeric\);
\(gdb\) bt
\#0  0x000000000054d9cb in Perl\_pp\_negate \(\) at pp\.c&#8203;:2549
\#1  0x00000000004d6262 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2234
\#2  0x0000000000452e97 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2525
\#3  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2448
\#4  0x0000000000421835 in main \(argc=3\, argv=0x7fffffffe6c8\, env=0x7fffffffe6e8\) at perlmain\.c&#8203;:123

==19494== Invalid read of size 4
==19494==    at 0x54D9CB&#8203;: Perl\_pp\_negate \(pp\.c&#8203;:2549\)
==19494==    by 0x4D6261&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2234\)
==19494==    by 0x452E96&#8203;: S\_run\_body \(perl\.c&#8203;:2525\)
==19494==    by 0x452E96&#8203;: perl\_run \(perl\.c&#8203;:2448\)
==19494==    by 0x421834&#8203;: main \(perlmain\.c&#8203;:123\)
==19494==  Address 0xc is not stack'd\, malloc'd or \(recently\) free'd
==19494==
==19494==
==19494== Process terminating with default action of signal 11 \(SIGSEGV\)
==19494==  Access not within mapped region at address 0xC
==19494==    at 0x54D9CB&#8203;: Perl\_pp\_negate \(pp\.c&#8203;:2549\)
==19494==    by 0x4D6261&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2234\)
==19494==    by 0x452E96&#8203;: S\_run\_body \(perl\.c&#8203;:2525\)
==19494==    by 0x452E96&#8203;: perl\_run \(perl\.c&#8203;:2448\)
==19494==    by 0x421834&#8203;: main \(perlmain\.c&#8203;:123\)
==19494==  If you believe this happened as a result of a stack
==19494==  overflow in your program's main thread \(unlikely but
==19494==  possible\)\, you can try to increase the size of the
==19494==  main thread stack using the \-\-main\-stacksize= flag\.
==19494==  The main thread stack size used in this run was 8388608\.
Segmentation fault

**Comment by p5pRT** [comment]
### From @cpansprout

Now fixed in 92b69f6\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
