### ISSUE TITLE
Assertion `((((U8)((*(((const U8*)(PL_parser->oldoldbufptr))+1 )) | 0)) & 0xC0) == 0x80)' failed (toke.c:525)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15575]
Migrated from [rt.perl.org#129157](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129157) (status was 'resolved')

Searchable as RT129157$

**Comment by p5pRT** [comment]
### From @geeknik

v5\.25\.4\-25\-g109ac34\*

Minimizing this testcase with afl\-tmin caused this assertion to be replaced with the one from bug \#129037\.

\./perl assert556
Malformed UTF\-8 character \(unexpected non\-continuation byte 0xc3\, immediately after start byte 0xc3\) at assert556 line 2\.
Malformed UTF\-8 character \(unexpected non\-continuation byte 0xc3\, immediately after start byte 0xc3\) at assert556 line 2\.
Malformed UTF\-8 character \(unexpected non\-continuation byte 0xc3\, immediately after start byte 0xc3\) at assert556 line 2\.
Malformed UTF\-8 character \(unexpected non\-continuation byte 0xc3\, immediately after start byte 0xc3\) at assert556 line 2\.
Malformed UTF\-8 character \(unexpected non\-continuation byte 0xc3\, immediately after start byte 0xc3\) at assert556 line 2\.
Malformed UTF\-8 character \(unexpected non\-continuation byte 0xc3\, immediately after start byte 0xc3\) at assert556 line 2\.
Malformed UTF\-8 character \(unexpected non\-continuation byte 0xc3\, immediately after start byte 0xc3\) at assert556 line 2\.
Malformed UTF\-8 character \(unexpected non\-continuation byte 0xc3\, immediately after start byte 0xc3\) at assert556 line 2\.
Malformed UTF\-8 character \(unexpected non\-continuation byte 0xc3\, immediately after start byte 0xc3\) at assert556 line 2\.
Malformed UTF\-8 character \(unexpected non\-continuation byte 0xc3\, immediately after start byte 0xc3\) at assert556 line 2\.
Malformed UTF\-8 character \(unexpected non\-continuation byte 0x74\, immediately after start byte 0xc3\) at assert556 line 2\.
Bareword found where operator expected at assert556 line 2\, near ""9 "Y"
&nbsp;        \(Missing operator before Y?\)
Wide character in print at assert556 line 86\.
Bareword found where operator expected at assert556 line 86\, near "▒▒▒▒▒▒▒▒tprotobyname"; "9 "Y=n \{pop and\-p\[p \};shmread $^H LLLLL\_'\_"
perl&#8203;: toke\.c&#8203;:525&#8203;: void S\_no\_op\(const char \*const\, char \*\)&#8203;: Assertion \`\(\(\(\(U8\)\(\(\*\(\(\(const U8\*\)\(PL\_parser\->oldoldbufptr\)\)\+1 \)\) | 0\)\) & 0xC0\) == 0x80\)' failed\.
Aborted\.

\#0  0x00007ffff6cf2067 in \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:56
\#1  0x00007ffff6cf3448 in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007ffff6ceb266 in \_\_assert\_fail\_base \(fmt=0x7ffff6e24238 "%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\,
&nbsp;    assertion=assertion@&#8203;entry=0xd5ae80 \<\.str1033> "\(\(\(\(U8\)\(\(\*\(\(\(const U8\*\)\(PL\_parser\->oldoldbufptr\)\)\+1 \)\) | 0\)\) & 0xC0\) == 0x80\)"\,
&nbsp;    file=file@&#8203;entry=0xd66637 "toke\.c"\, line=line@&#8203;entry=525\,
&nbsp;    function=function@&#8203;entry=0xd5ace0 \<\_\_PRETTY\_FUNCTION\_\_\.S\_no\_op> "void S\_no\_op\(const char \*const\, char \*\)"\) at assert\.c&#8203;:92
\#3  0x00007ffff6ceb312 in \_\_GI\_\_\_assert\_fail \(
&nbsp;    assertion=0xd5ae80 \<\.str1033> "\(\(\(\(U8\)\(\(\*\(\(\(const U8\*\)\(PL\_parser\->oldoldbufptr\)\)\+1 \)\) | 0\)\) & 0xC0\) == 0x80\)"\, file=0xd66637 "toke\.c"\,
&nbsp;    line=525\, function=0xd5ace0 \<\_\_PRETTY\_FUNCTION\_\_\.S\_no\_op> "void S\_no\_op\(const char \*const\, char \*\)"\) at assert\.c&#8203;:101
\#4  0x0000000000693c81 in S\_no\_op \(what=\<optimized out>\, s=\<optimized out>\) at toke\.c&#8203;:525
\#5  0x00000000006224f0 in Perl\_yylex \(\) at toke\.c&#8203;:6958
\#6  0x00000000006ad346 in Perl\_yyparse \(gramtype=\<optimized out>\) at perly\.c&#8203;:334
\#7  0x000000000059c392 in S\_parse\_body \(env=\<optimized out>\, xsinit=\<optimized out>\) at perl\.c&#8203;:2373
\#8  0x000000000059272d in perl\_parse \(my\_perl=\<optimized out>\, xsinit=\<optimized out>\, argc=\<optimized out>\, argv=\<optimized out>\,
&nbsp;    env=\<optimized out>\) at perl\.c&#8203;:1689
\#9  0x00000000004de6a6 in main \(argc=\<optimized out>\, argv=\<optimized out>\, env=\<optimized out>\) at perlmain\.c&#8203;:121

**Comment by p5pRT** [comment]
### From @geeknik

[assert556.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1421065/768533/assert556.gz)

**Comment by p5pRT** [comment]
### From @cpansprout

On Wed Aug 31 21&#8203;:51&#8203;:33 2016\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> v5\.25\.4\-25\-g109ac34\*
> 
> Minimizing this testcase with afl\-tmin caused this assertion to be
> replaced with the one from bug \#129037\.
> 
> \./perl assert556
> Malformed UTF\-8 character \(unexpected non\-continuation byte 0xc3\,

Does the patch from \#126310 fix this?

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thanks for finding and reporting this problem\.  It turns out that it was fixed by&#8203;:

commit 6cdc5cd8f36f88172b0fcefdcadec75f5b6600b2
Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
Date&#8203;:   Fri Dec 2 09&#8203;:35&#8203;:53 2016 \-0700

&nbsp;    PATCH&#8203;: \[perl \#126310\] single quote UTF\-8 malformation detection
&nbsp;    
&nbsp;    This adds UTF\-8 wellformedness checking in Perl\_lex\_next\_chunk\, which
&nbsp;    should get called for all program text\, so this makes sure the entire
&nbsp;    program is well\-formed\, not just single\- or double\-quoted strings\.

I've added the script for the failure in this ticket to our test suite in commit 1fb23c72f01044b382871df38d6a63287edccf14
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
