### ISSUE TITLE
Assertion `!((((_svcur)->sv_flags & (0x00004000|0x00008000)) == 0x00008000) && (((svtype)((_svcur)->sv_flags & 0xff)) == SVt_PVGV || ((svtype)((_svcur)->sv_flags & 0xff)) == SVt_PVLV))' failed (sv.c:1

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15571]
Migrated from [rt.perl.org#129147](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129147) (status was 'resolved')

Searchable as RT129147$

**Comment by p5pRT** [comment]
### From @geeknik

Perl v5\.25\.4\-25\-g109ac34\*

\./perl \-e '0>formline qr oo=>\*0'

perl&#8203;: sv\.c&#8203;:1587&#8203;: char \*Perl\_sv\_grow\(SV \*const\, STRLEN\)&#8203;: Assertion \`\!\(\(\(\(\_svcur\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(\_svcur\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_svcur\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.
Aborted

\#0  0x00007ffff6cf2067 in \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./nptl/sysdeps/unix/sysv/linux/raise\.c&#8203;:56
\#1  0x00007ffff6cf3448 in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007ffff6ceb266 in \_\_assert\_fail\_base \(fmt=0x7ffff6e24238 "%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\,
&nbsp;    assertion=assertion@&#8203;entry=0xe038c0 \<\.str101> "\!\(\(\(\(\_svcur\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(\_svcur\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_svcur\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)"\, file=file@&#8203;entry=0xe29ff8 "sv\.c"\, line=line@&#8203;entry=1587\,
&nbsp;    function=function@&#8203;entry=0xe03a80 \<\_\_PRETTY\_FUNCTION\_\_\.Perl\_sv\_grow> "char \*Perl\_sv\_grow\(SV \*const\, STRLEN\)"\) at assert\.c&#8203;:92
\#3  0x00007ffff6ceb312 in \_\_GI\_\_\_assert\_fail \(
&nbsp;    assertion=0xe038c0 \<\.str101> "\!\(\(\(\(\_svcur\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(\_svcur\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_svcur\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)"\, file=0xe29ff8 "sv\.c"\, line=1587\,
&nbsp;    function=0xe03a80 \<\_\_PRETTY\_FUNCTION\_\_\.Perl\_sv\_grow> "char \*Perl\_sv\_grow\(SV \*const\, STRLEN\)"\) at assert\.c&#8203;:101
\#4  0x00000000008eff8a in Perl\_sv\_grow \(sv=\<optimized out>\, newlen=\<optimized out>\) at sv\.c&#8203;:1587
\#5  0x0000000000909d62 in Perl\_sv\_setpvn \(sv=0x621000010f08\, ptr=0x60200000e071 "main&#8203;::0"\, len=7\) at sv\.c&#8203;:4898
\#6  0x0000000000a44b76 in Perl\_pp\_formline \(\) at pp\_ctl\.c&#8203;:699
\#7  0x00000000007f26a4 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2234
\#8  0x00000000005a10c7 in S\_run\_body \(oldscope=\<optimized out>\) at perl\.c&#8203;:2525
\#9  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2448
\#10 0x00000000004de6ce in main \(argc=\<optimized out>\, argv=\<optimized out>\, env=\<optimized out>\) at perlmain\.c&#8203;:123

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Reduces to 'formline "^"\, \*z'\.  Fixed by
a4031a721e0a1941c14467c7671da2ee1b91c969\.

\-zefram

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
