### ISSUE TITLE
null ptr deref, segfault in Perl_pp_split () at pp.c:5738

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15576]
Migrated from [rt.perl.org#129158](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129158) (status was 'resolved')

Searchable as RT129158$

**Comment by p5pRT** [comment]
### From @geeknik

Perl v5\.25\.5 \(v5\.25\.4\-25\-g109ac34\*\)\, found with AFL \+ ASAN\. A non\-instrumented build of 
v5\.25\.4\-5\-g92d73bf returns the valgrind output at the end\.

hexdump \-C over727
00000000  6d 61 70 7b 73 5b 5d 5b  5d 6f 3e 73 70 6c 69 74  |map\{s\[\]\[\]o>split|
00000010  00 30 2c 24 30 5b 73 70  6c 69 74 2f 28 30 29 2f  |\.0\,$0\[split/\(0\)/|
00000020  3e 30 5d 3e 6d 61 70 7b  30 3f 7b 7d 3a 30 7d 30  |>0\]>map\{0?\{\}&#8203;:0\}0|
00000030  7d 3c 44 41 54 41 3e 5f  5f 45 4e 44 5f 5f 0a 0a  |\}\<DATA>\_\_END\_\_\.\.|
00000040  30                                                |0|
00000041

ASAN&#8203;:SIGSEGV
=================================================================
==8284==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000000 \(pc 0x000000a0c999 bp 0x7fffa83f31a0 sp 0x7fffa83f3000 T0\)
&nbsp;    \#0 0xa0c998 in Perl\_pp\_split /root/perl/pp\.c&#8203;:5738&#8203;:5
&nbsp;    \#1 0x7f26a3 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2234&#8203;:23
&nbsp;    \#2 0x5a10c6 in S\_run\_body /root/perl/perl\.c&#8203;:2525&#8203;:2
&nbsp;    \#3 0x5a10c6 in perl\_run /root/perl/perl\.c&#8203;:2448
&nbsp;    \#4 0x4de6cd in main /root/perl/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#5 0x7f5b16991b44 in \_\_libc\_start\_main /build/glibc\-uPj9cH/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#6 0x4de33c in \_start \(/root/perl/perl\+0x4de33c\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /root/perl/pp\.c&#8203;:5738 Perl\_pp\_split
==8284==ABORTING

Program received signal SIGSEGV\, Segmentation fault\.
0x0000000000a0c999 in Perl\_pp\_split \(\) at pp\.c&#8203;:5738
5738        rx = PM\_GETRE\(pm\);
\(gdb\) bt
\#0  0x0000000000a0c999 in Perl\_pp\_split \(\) at pp\.c&#8203;:5738
\#1  0x00000000007f26a4 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2234
\#2  0x00000000005a10c7 in S\_run\_body \(oldscope=\<optimized out>\) at perl\.c&#8203;:2525
\#3  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2448
\#4  0x00000000004de6ce in main \(argc=\<optimized out>\, argv=\<optimized out>\, env=\<optimized out>\) at perlmain\.c&#8203;:123

Non\-instrumented v5\.25\.4\-5\-g92d73bf Valgrind output&#8203;:
==27188== Conditional jump or move depends on uninitialised value\(s\)
==27188==    at 0x55E88C&#8203;: Perl\_pp\_split \(pp\.c&#8203;:5736\)
==27188==    by 0x4D6261&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2234\)
==27188==    by 0x452E96&#8203;: S\_run\_body \(perl\.c&#8203;:2525\)
==27188==    by 0x452E96&#8203;: perl\_run \(perl\.c&#8203;:2448\)
==27188==    by 0x421834&#8203;: main \(perlmain\.c&#8203;:123\)
==27188==
==27188== Conditional jump or move depends on uninitialised value\(s\)
==27188==    at 0x4D8312&#8203;: Perl\_die \(util\.c&#8203;:1719\)
==27188==    by 0x5604C1&#8203;: Perl\_pp\_split \(pp\.c&#8203;:5737\)
==27188==    by 0x4D6261&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2234\)
==27188==    by 0x452E96&#8203;: S\_run\_body \(perl\.c&#8203;:2525\)
==27188==    by 0x452E96&#8203;: perl\_run \(perl\.c&#8203;:2448\)
==27188==    by 0x421834&#8203;: main \(perlmain\.c&#8203;:123\)
==27188==
panic&#8203;: pp\_split\, pm=0\, s=6def41 at over727 line 1\, \<DATA> line 2\.

**Comment by p5pRT** [comment]
### From @geeknik

[over727.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1421076/768540/over727.gz)

**Comment by p5pRT** [comment]
### From @cpansprout

On Thu Sep 01 01&#8203;:49&#8203;:12 2016\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> Perl v5\.25\.5 \(v5\.25\.4\-25\-g109ac34\*\)\, found with AFL \+ ASAN\. A non\-
> instrumented build of
> v5\.25\.4\-5\-g92d73bf returns the valgrind output at the end\.

I can reproduce it on dromedary\, but not locally\.  On dromedary I don’t have a functional gdb\, so it’s a little hard to debug\.

I tried bisecting\, but got perl\-5\.6\.0\-4727\-g4cddb5c\, which seems like a red herring\.

I managed to reduce it to this&#8203;:

$ cat foo
map\{s///o > split 0\,split /0/>0\}\<DATA>\_\_END\_\_


$ 

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Sep 11\, 2016 at 10&#8203;:17&#8203;:39PM \-0700\, Father Chrysostomos via RT wrote&#8203;:
> On Thu Sep 01 01&#8203;:49&#8203;:12 2016\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> > Perl v5\.25\.5 \(v5\.25\.4\-25\-g109ac34\*\)\, found with AFL \+ ASAN\. A non\-
> > instrumented build of
> > v5\.25\.4\-5\-g92d73bf returns the valgrind output at the end\.
> 
> I can reproduce it on dromedary\, but not locally\.  On dromedary I don’t have a functional gdb\, so it’s a little hard to debug\.
> 
> I tried bisecting\, but got perl\-5\.6\.0\-4727\-g4cddb5c\, which seems like a red herring\.
> 
> I managed to reduce it to this&#8203;:
> 
> $ cat foo
> map\{s///o > split 0\,split /0/>0\}\<DATA>\_\_END\_\_

It's only an issue on non\-threaded builds\. It started failing sometime
between 5\.16\.0 and 5\.18\.0\.
I'm looking into it\.

\-\- 
"Procrastination grows to fill the available time"
&nbsp;    \-\- Mitchell's corollary to Parkinson's Law

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Sep 12\, 2016 at 03&#8203;:23&#8203;:07PM \+0100\, Dave Mitchell wrote&#8203;:
> On Sun\, Sep 11\, 2016 at 10&#8203;:17&#8203;:39PM \-0700\, Father Chrysostomos via RT wrote&#8203;:
> > On Thu Sep 01 01&#8203;:49&#8203;:12 2016\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> > > Perl v5\.25\.5 \(v5\.25\.4\-25\-g109ac34\*\)\, found with AFL \+ ASAN\. A non\-
> > > instrumented build of
> > > v5\.25\.4\-5\-g92d73bf returns the valgrind output at the end\.
> > 
> > I can reproduce it on dromedary\, but not locally\.  On dromedary I don’t have a functional gdb\, so it’s a little hard to debug\.
> > 
> > I tried bisecting\, but got perl\-5\.6\.0\-4727\-g4cddb5c\, which seems like a red herring\.
> > 
> > I managed to reduce it to this&#8203;:
> > 
> > $ cat foo
> > map\{s///o > split 0\,split /0/>0\}\<DATA>\_\_END\_\_
> 
> It's only an issue on non\-threaded builds\. It started failing sometime
> between 5\.16\.0 and 5\.18\.0\.
> I'm looking into it\.

It turns out that this is another variant of RT \#124368&#8203;: on non\-threaded
builds\, the s///o combines&#8203;: modifying the op tree under /o to avoid
recompilation on subsequent iterations; and m// using the last successful
pattern\. The combination of the two makes /o end up modifying some random
other part of the op tree\.

I haven't fixed this yet\, but while investigating what was going on\, I
decided I would finally sort out the horrible OP\_SPLIT/OP\_PUSHRE mess\,
which I have now done and am smoking as smoke\-me/davem/pushre2\.

The most significant commit from that branch is the following\, which
I intend to merge into blead in few days time\. Note this it is \*not\* a fix
for this ticket\.

commit e505c6fa5fa71fde220a84dd42edbcb3b3c82566
Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
AuthorDate&#8203;: Thu Sep 15 10&#8203;:59&#8203;:37 2016 \+0100
Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
CommitDate&#8203;: Sun Sep 25 07&#8203;:57&#8203;:49 2016 \+0100

&nbsp;    make OP\_SPLIT a PMOP\, and eliminate OP\_PUSHRE
&nbsp;    
&nbsp;    Most ops that execute a regex\, such as match and subst\, are of type PMOP\.
&nbsp;    A PMOP allows the actual regex to be attached directly to that op\, due
&nbsp;    to its extra fields\.
&nbsp;    
&nbsp;    OP\_SPLIT is different; it is just a plain LISTOP\, but it always has an
&nbsp;    OP\_PUSHRE as its first child\, which \*is\* a PMOP and which has the regex
&nbsp;    attached\.
&nbsp;    
&nbsp;    At runtime\, pp\_pushre\(\)'s only job is to push itself \(i\.e\. the current
&nbsp;    PL\_op\) onto the stack\. Later pp\_split\(\) pops this to get access to the
&nbsp;    regex it wants to execute\.
&nbsp;    
&nbsp;    This is a bit unpleasant\, because we're pushing an OP\* onto the stack\,
&nbsp;    which is supposed to be an array of SV\*'s\. As a bit of a hack\, on
&nbsp;    DEBUGGING builds we push a PVLV with the PL\_op address embedded instead\,
&nbsp;    but this still isn't very satisfactory\.
&nbsp;    
&nbsp;    Now that regexes are first\-class SVs\, we could push a REGEXP onto the
&nbsp;    stack rather than PL\_op\. However\, there is an optimisation of @&#8203;array =
&nbsp;    split which eliminates the assign and embeds the array's GV/padix directly
&nbsp;    in the PUSHRE op\. So split still needs access to that op\. But the pushre
&nbsp;    op will always be splitop\->op\_first anyway\, so one possibility is to just
&nbsp;    skip executing the pushre altogether\, and make pp\_split just directly
&nbsp;    access op\_first instead to get the regex and @&#8203;array info\.
&nbsp;    
&nbsp;    But if we're doing that\, then why not just go the full hog and make
&nbsp;    OP\_SPLIT into a PMOP\, and eliminate the OP\_PUSHRE op entirely&#8203;: with the
&nbsp;    data that was spread across the two ops now combined into just the one
&nbsp;    split op\.
&nbsp;    
&nbsp;    That is exactly what this commit does\.
&nbsp;    
&nbsp;    For a simple compile\-time pattern like  split\(/foo/\, $s\, 1\)\, the optree
&nbsp;    looks like&#8203;:
&nbsp;    
&nbsp;        before&#8203;:
&nbsp;            \<@&#8203;> split\[t2\] lK
&nbsp;               \</> pushre\(/"foo"/\) s/RTIME
&nbsp;               \<0> padsv\[$s&#8203;:1\,2\] s
&nbsp;               \<$> const\(IV 1\) s
&nbsp;    
&nbsp;        after&#8203;:
&nbsp;            \</> split\(/"foo"/\)\[t2\] lK/RTIME
&nbsp;               \<0> padsv\[$s&#8203;:1\,2\] s
&nbsp;               \<$> const\[IV 1\] s
&nbsp;    
&nbsp;    while for a run\-time expression like split\(/$pat/\, $s\, 1\)\,
&nbsp;    
&nbsp;        before&#8203;:
&nbsp;            \<@&#8203;> split\[t3\] lK
&nbsp;               \</> pushre\(\) sK/RTIME
&nbsp;                  \<|> regcomp\(other\->8\) sK
&nbsp;                     \<0> padsv\[$pat&#8203;:2\,3\] s
&nbsp;               \<0> padsv\[$s&#8203;:1\,3\] s
&nbsp;               \<$> const\(IV 1\)s
&nbsp;    
&nbsp;        after&#8203;:
&nbsp;            \</> split\(\)\[t3\] lK/RTIME
&nbsp;               \<|> regcomp\(other\->8\) sK
&nbsp;                  \<0> padsv\[$pat&#8203;:2\,3\] s
&nbsp;               \<0> padsv\[$s&#8203;:1\,3\] s
&nbsp;               \<$> const\[IV 1\] s
&nbsp;    
&nbsp;    This makes the code faster and simpler\.
&nbsp;    
&nbsp;    At the same time\, two new private flags have been added for OP\_SPLIT \-
&nbsp;    OPpSPLIT\_ASSIGN and OPpSPLIT\_LEX \- which make it explicit that the
&nbsp;    assign op has been optimised away\, and if so\, whether the array is
&nbsp;    lexical\.
&nbsp;    
&nbsp;    Also\, deparsing of split has been improved\, to the extent that
&nbsp;    
&nbsp;        perl TEST \-deparse op/split\.t
&nbsp;    
&nbsp;    now passes\.
&nbsp;    
&nbsp;    Also\, a couple of panic messages in pp\_split\(\) have been replaced with
&nbsp;    asserts\(\)\.


\-\- 
Modern art&#8203;:
&nbsp;    "That's easy\, I could have done that\!"
&nbsp;    "Ah\, but you didn't\!"

**Comment by p5pRT** [comment]
### From @jkeenan

On Mon\, 26 Sep 2016 11&#8203;:58&#8203;:56 GMT\, davem wrote&#8203;:
> On Mon\, Sep 12\, 2016 at 03&#8203;:23&#8203;:07PM \+0100\, Dave Mitchell wrote&#8203;:
> > On Sun\, Sep 11\, 2016 at 10&#8203;:17&#8203;:39PM \-0700\, Father Chrysostomos via RT
> > wrote&#8203;:
> > > On Thu Sep 01 01&#8203;:49&#8203;:12 2016\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> > > > Perl v5\.25\.5 \(v5\.25\.4\-25\-g109ac34\*\)\, found with AFL \+ ASAN\. A
> > > > non\-
> > > > instrumented build of
> > > > v5\.25\.4\-5\-g92d73bf returns the valgrind output at the end\.
> > >
> > > I can reproduce it on dromedary\, but not locally\.  On dromedary I
> > > don’t have a functional gdb\, so it’s a little hard to debug\.
> > >
> > > I tried bisecting\, but got perl\-5\.6\.0\-4727\-g4cddb5c\, which seems
> > > like a red herring\.
> > >
> > > I managed to reduce it to this&#8203;:
> > >
> > > $ cat foo
> > > map\{s///o > split 0\,split /0/>0\}\<DATA>\_\_END\_\_
> >
> > It's only an issue on non\-threaded builds\. It started failing
> > sometime
> > between 5\.16\.0 and 5\.18\.0\.
> > I'm looking into it\.
> 
> It turns out that this is another variant of RT \#124368&#8203;: on non\-
> threaded
> builds\, the s///o combines&#8203;: modifying the op tree under /o to avoid
> recompilation on subsequent iterations; and m// using the last
> successful
> pattern\. The combination of the two makes /o end up modifying some
> random
> other part of the op tree\.
> 
> I haven't fixed this yet\, but while investigating what was going on\, I
> decided I would finally sort out the horrible OP\_SPLIT/OP\_PUSHRE mess\,
> which I have now done and am smoking as smoke\-me/davem/pushre2\.
> 
> The most significant commit from that branch is the following\, which
> I intend to merge into blead in few days time\. Note this it is \*not\* a
> fix
> for this ticket\.
> 

Dave\, Father C\, et al\.\,

Could we get an update on the status of this ticket?

> commit e505c6fa5fa71fde220a84dd42edbcb3b3c82566
> Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
> AuthorDate&#8203;: Thu Sep 15 10&#8203;:59&#8203;:37 2016 \+0100
> Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
> CommitDate&#8203;: Sun Sep 25 07&#8203;:57&#8203;:49 2016 \+0100
> 
> make OP\_SPLIT a PMOP\, and eliminate OP\_PUSHRE
> 
> Most ops that execute a regex\, such as match and subst\, are of type
> PMOP\.
> A PMOP allows the actual regex to be attached directly to that op\, due
> to its extra fields\.
> 
> OP\_SPLIT is different; it is just a plain LISTOP\, but it always has an
> OP\_PUSHRE as its first child\, which \*is\* a PMOP and which has the
> regex
> attached\.
> 
> At runtime\, pp\_pushre\(\)'s only job is to push itself \(i\.e\. the current
> PL\_op\) onto the stack\. Later pp\_split\(\) pops this to get access to the
> regex it wants to execute\.
> 
> This is a bit unpleasant\, because we're pushing an OP\* onto the stack\,
> which is supposed to be an array of SV\*'s\. As a bit of a hack\, on
> DEBUGGING builds we push a PVLV with the PL\_op address embedded
> instead\,
> but this still isn't very satisfactory\.
> 
> Now that regexes are first\-class SVs\, we could push a REGEXP onto the
> stack rather than PL\_op\. However\, there is an optimisation of @&#8203;array =
> split which eliminates the assign and embeds the array's GV/padix
> directly
> in the PUSHRE op\. So split still needs access to that op\. But the
> pushre
> op will always be splitop\->op\_first anyway\, so one possibility is to
> just
> skip executing the pushre altogether\, and make pp\_split just directly
> access op\_first instead to get the regex and @&#8203;array info\.
> 
> But if we're doing that\, then why not just go the full hog and make
> OP\_SPLIT into a PMOP\, and eliminate the OP\_PUSHRE op entirely&#8203;: with
> the
> data that was spread across the two ops now combined into just the one
> split op\.
> 
> That is exactly what this commit does\.
> 
> For a simple compile\-time pattern like  split\(/foo/\, $s\, 1\)\, the
> optree
> looks like&#8203;:
> 
> before&#8203;:
>     \<@&#8203;> split\[t2\] lK
>        \</> pushre\(/"foo"/\) s/RTIME
>        \<0> padsv\[$s&#8203;:1\,2\] s
>        \<$> const\(IV 1\) s
> 
> after&#8203;:
>     \</> split\(/"foo"/\)\[t2\] lK/RTIME
>        \<0> padsv\[$s&#8203;:1\,2\] s
>        \<$> const\[IV 1\] s
> 
> while for a run\-time expression like split\(/$pat/\, $s\, 1\)\,
> 
> before&#8203;:
>     \<@&#8203;> split\[t3\] lK
>        \</> pushre\(\) sK/RTIME
>           \<|> regcomp\(other\->8\) sK
>              \<0> padsv\[$pat&#8203;:2\,3\] s
>        \<0> padsv\[$s&#8203;:1\,3\] s
>        \<$> const\(IV 1\)s
> 
> after&#8203;:
>     \</> split\(\)\[t3\] lK/RTIME
>        \<|> regcomp\(other\->8\) sK
>           \<0> padsv\[$pat&#8203;:2\,3\] s
>        \<0> padsv\[$s&#8203;:1\,3\] s
>        \<$> const\[IV 1\] s
> 
> This makes the code faster and simpler\.
> 
> At the same time\, two new private flags have been added for OP\_SPLIT \-
> OPpSPLIT\_ASSIGN and OPpSPLIT\_LEX \- which make it explicit that the
> assign op has been optimised away\, and if so\, whether the array is
> lexical\.
> 
> Also\, deparsing of split has been improved\, to the extent that
> 
> perl TEST \-deparse op/split\.t
> 
> now passes\.
> 
> Also\, a couple of panic messages in pp\_split\(\) have been replaced with
> asserts\(\)\.


\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, Oct 28\, 2017 at 06&#8203;:30&#8203;:31AM \-0700\, James E Keenan via RT wrote&#8203;:
> On Mon\, 26 Sep 2016 11&#8203;:58&#8203;:56 GMT\, davem wrote&#8203;:
> > On Mon\, Sep 12\, 2016 at 03&#8203;:23&#8203;:07PM \+0100\, Dave Mitchell wrote&#8203;:
> > > On Sun\, Sep 11\, 2016 at 10&#8203;:17&#8203;:39PM \-0700\, Father Chrysostomos via RT
> > > wrote&#8203;:
> > > > On Thu Sep 01 01&#8203;:49&#8203;:12 2016\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> > > > > Perl v5\.25\.5 \(v5\.25\.4\-25\-g109ac34\*\)\, found with AFL \+ ASAN\. A
> > > > > non\-
> > > > > instrumented build of
> > > > > v5\.25\.4\-5\-g92d73bf returns the valgrind output at the end\.
> > > >
> > > > I can reproduce it on dromedary\, but not locally\.  On dromedary I
> > > > don’t have a functional gdb\, so it’s a little hard to debug\.
> > > >
> > > > I tried bisecting\, but got perl\-5\.6\.0\-4727\-g4cddb5c\, which seems
> > > > like a red herring\.
> > > >
> > > > I managed to reduce it to this&#8203;:
> > > >
> > > > $ cat foo
> > > > map\{s///o > split 0\,split /0/>0\}\<DATA>\_\_END\_\_
> > >
> > > It's only an issue on non\-threaded builds\. It started failing
> > > sometime
> > > between 5\.16\.0 and 5\.18\.0\.
> > > I'm looking into it\.
> > 
> > It turns out that this is another variant of RT \#124368&#8203;: on non\-
> > threaded
> > builds\, the s///o combines&#8203;: modifying the op tree under /o to avoid
> > recompilation on subsequent iterations; and m// using the last
> > successful
> > pattern\. The combination of the two makes /o end up modifying some
> > random
> > other part of the op tree\.
> > 
> > I haven't fixed this yet\, but while investigating what was going on\, I
> > decided I would finally sort out the horrible OP\_SPLIT/OP\_PUSHRE mess\,
> > which I have now done and am smoking as smoke\-me/davem/pushre2\.
> > 
> > The most significant commit from that branch is the following\, which
> > I intend to merge into blead in few days time\. Note this it is \*not\* a
> > fix
> > for this ticket\.
> > 
> 
> Dave\, Father C\, et al\.\,
> 
> Could we get an update on the status of this ticket?

It appears to have been fixed by v5\.27\.2\-138\-g3cb4cde\.

\-\- 
Nothing ventured\, nothing lost\.

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
