### ISSUE TITLE
null ptr deref, segfault in Perl_pp_subtract pp.c:1894

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15578]
Migrated from [rt.perl.org#129166](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129166) (status was 'resolved')

Searchable as RT129166$

**Comment by p5pRT** [comment]
### From @geeknik

Perl v5\.25\.4\-27\-gf16e7fa

\./perl \-e '@&#8203;0=\(\)\-splice@&#8203;a\,$\#a=0or@&#8203;0'

==35420==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x00000000000c \(pc 0x0000009bcd41 bp 0x0c32000012d2 sp 0x7ffe63e7dbd0 T0\)
&nbsp;    \#0 0x9bcd40 in Perl\_pp\_subtract /home/geeknik/perl/pp\.c&#8203;:1894&#8203;:5
&nbsp;    \#1 0x7f2623 in Perl\_runops\_debug /home/geeknik/perl/dump\.c&#8203;:2234&#8203;:23
&nbsp;    \#2 0x5a10c6 in S\_run\_body /home/geeknik/perl/perl\.c&#8203;:2525&#8203;:2
&nbsp;    \#3 0x5a10c6 in perl\_run /home/geeknik/perl/perl\.c&#8203;:2448
&nbsp;    \#4 0x4de6cd in main /home/geeknik/perl/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#5 0x7f501b7f1b44 in \_\_libc\_start\_main /build/glibc\-uPj9cH/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#6 0x4de33c in \_start \(/home/geeknik/perl/perl\+0x4de33c\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /home/geeknik/perl/pp\.c&#8203;:1894 Perl\_pp\_subtract
==35420==ABORTING

Program received signal SIGSEGV\, Segmentation fault\.
0x00000000009bcdc1 in Perl\_pp\_subtract \(\) at pp\.c&#8203;:1894
1894        tryAMAGICbin\_MG\(subtr\_amg\, AMGf\_assign|AMGf\_numeric\);
\(gdb\) bt
\#0  0x00000000009bcdc1 in Perl\_pp\_subtract \(\) at pp\.c&#8203;:1894
\#1  0x00000000007f26a4 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2234
\#2  0x00000000005a10c7 in S\_run\_body \(oldscope=\<optimized out>\) at perl\.c&#8203;:2525
\#3  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2448
\#4  0x00000000004de6ce in main \(argc=\<optimized out>\, argv=\<optimized out>\, env=\<optimized out>\) at perlmain\.c&#8203;:123


==17125== Invalid read of size 4
==17125==    at 0x54A013&#8203;: Perl\_pp\_subtract \(pp\.c&#8203;:1894\)
==17125==    by 0x4D6261&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2234\)
==17125==    by 0x452E96&#8203;: S\_run\_body \(perl\.c&#8203;:2525\)
==17125==    by 0x452E96&#8203;: perl\_run \(perl\.c&#8203;:2448\)
==17125==    by 0x421834&#8203;: main \(perlmain\.c&#8203;:123\)
==17125==  Address 0xc is not stack'd\, malloc'd or \(recently\) free'd
==17125==
==17125==
==17125== Process terminating with default action of signal 11 \(SIGSEGV\)
==17125==  Access not within mapped region at address 0xC
==17125==    at 0x54A013&#8203;: Perl\_pp\_subtract \(pp\.c&#8203;:1894\)
==17125==    by 0x4D6261&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2234\)
==17125==    by 0x452E96&#8203;: S\_run\_body \(perl\.c&#8203;:2525\)
==17125==    by 0x452E96&#8203;: perl\_run \(perl\.c&#8203;:2448\)
==17125==    by 0x421834&#8203;: main \(perlmain\.c&#8203;:123\)
==17125==  If you believe this happened as a result of a stack
==17125==  overflow in your program's main thread \(unlikely but
==17125==  possible\)\, you can try to increase the size of the
==17125==  main thread stack using the \-\-main\-stacksize= flag\.
==17125==  The main thread stack size used in this run was 8388608\.
Segmentation fault

**Comment by p5pRT** [comment]
### From @dcollinsn

\./perl \-e '$\#a=0;0\-splice@&#8203;a'

Also segfaults\.

The root cause of \#129164\, \#129166\, and \#129167 is almost certainly something in Perl\_pp\_splice when called on a zero\-length array\. 

$ \./perl \-Ilib \-MDevel&#8203;::Peek \-e '$\#a=0; Dump\(splice @&#8203;a\);'
SV = 0

Looks like a good starting point\.

\-\- 
Respectfully\,
Dan Collins

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Thu Sep 01 11&#8203;:56&#8203;:00 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> \./perl \-e '$\#a=0;0\-splice@&#8203;a'
> 
> Also segfaults\.
> 
> The root cause of \#129164\, \#129166\, and \#129167 is almost certainly
> something in Perl\_pp\_splice when called on a zero\-length array\.

Not zero\-length\, but one with a single null entry\.

> 
> $ \./perl \-Ilib \-MDevel&#8203;::Peek \-e '$\#a=0; Dump\(splice @&#8203;a\);'
> SV = 0
> 
> Looks like a good starting point\.

I think splice needs to do the same null checks that other array functions do\, and push &PL\_sv\_undef for null\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @cpansprout

On Thu Sep 01 21&#8203;:30&#8203;:30 2016\, sprout wrote&#8203;:
> On Thu Sep 01 11&#8203;:56&#8203;:00 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> > \./perl \-e '$\#a=0;0\-splice@&#8203;a'
> >
> > Also segfaults\.
> >
> > The root cause of \#129164\, \#129166\, and \#129167 is almost certainly
> > something in Perl\_pp\_splice when called on a zero\-length array\.
> 
> Not zero\-length\, but one with a single null entry\.
> 
> >
> > $ \./perl \-Ilib \-MDevel&#8203;::Peek \-e '$\#a=0; Dump\(splice @&#8203;a\);'
> > SV = 0
> >
> > Looks like a good starting point\.
> 
> I think splice needs to do the same null checks that other array
> functions do\, and push &PL\_sv\_undef for null\.

Now fixed in 92b69f6\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
