### ISSUE TITLE
Difficult-to-trigger panic: sv_setpvn called with negative strlen and sometimes segfaults

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15587]
Migrated from [rt.perl.org#129199](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129199) (status was 'resolved')

Searchable as RT129199$

**Comment by p5pRT** [comment]
### From @dcollinsn

The testcase is the following&#8203;:

perl \-e 'print "//\./\(?\{\<\<\}\)/\\n0\\n"' | valgrind perl

Normally\, perl exits normally\, with only&#8203;:

&nbsp;    Use of bare \<\< to mean \<\<"" is deprecated at \- line 1\.

Under valgrind\, we have the following message \(with NO valgrind warnings\)&#8203;:

&nbsp;    Use of bare \<\< to mean \<\<"" is deprecated at \- line 1\.
&nbsp;    panic&#8203;: sv\_setpvn called with negative strlen \-73 at \- line 1\.

Under GDB&#8203;:

&nbsp;    Use of bare \<\< to mean \<\<"" is deprecated at allcrash/f3i000018 line 1\.
&nbsp;    \[Inferior 1 \(process 54652\) exited normally\]
&nbsp;    \(gdb\)

Valgrind with libdislocator\, no segfault&#8203;:

&nbsp;    Use of bare \<\< to mean \<\<"" is deprecated at allcrash/f3i000018 line 1\.
&nbsp;    panic&#8203;: sv\_setpvn called with negative strlen \-8179 at
allcrash/f3i000018 line 1\.

GDB with libdislocator\, segfaults\, FINALLY a backtrace&#8203;:

\_\_memmove\_ssse3\_back \(\) at
\.\./sysdeps/x86\_64/multiarch/memcpy\-ssse3\-back\.S&#8203;:93
93      \.\./sysdeps/x86\_64/multiarch/memcpy\-ssse3\-back\.S&#8203;: No such file or
directory\.
\(gdb\) bt
\#0  \_\_memmove\_ssse3\_back \(\)
&nbsp;    at \.\./sysdeps/x86\_64/multiarch/memcpy\-ssse3\-back\.S&#8203;:93
\#1  0x00000000005dd0f9 in Perl\_sv\_setpvn \(sv=0x7ffff6841e08\,
&nbsp;    ptr=0x7ffff65b2ff2 'A' \<repeats 14 times>\, len=8205\) at sv\.c&#8203;:4893
\#2  0x00000000005f8337 in Perl\_newSVpvn \(buffer=\<optimized out>\,
&nbsp;    len=\<optimized out>\) at sv\.c&#8203;:9234
\#3  0x00000000004a19c2 in Perl\_yylex \(\) at toke\.c&#8203;:4745
\#4  0x00000000004edf1d in Perl\_yyparse \(gramtype=\<optimized out>\)
&nbsp;    at perly\.c&#8203;:334
\#5  0x00000000004778bd in S\_parse\_body \(env=\<optimized out>\,
&nbsp;    xsinit=\<optimized out>\) at perl\.c&#8203;:2373
\#6  perl\_parse \(my\_perl=\<optimized out>\, xsinit=\<optimized out>\,
&nbsp;    argc=\<optimized out>\, argv=\<optimized out>\, env=\<optimized out>\)
&nbsp;    at perl\.c&#8203;:1689
\#7  0x00000000004231ea in main \(argc=8205\, argv=0x9e6000
\<\_\_afl\_area\_initial>\,
&nbsp;    env=\<optimized out>\) at perlmain\.c&#8203;:121

Libdislocator is a preloadable library distributed with AFL that replaces
perfectly fine library functions like malloc and realloc with pathological
versions\. For example\, the new realloc will always allocate new memory\,
instead of trying to grow the original pointer\.

It's odd that Valgrind causes the Perl panic\. That is a Perl interpreter
panic\, right? This tells me that\, under Valgrind and only under Valgrind\,
Perl detects the "negative strlen" case\. Additionally\, there is a memory
management error \*later\* that causes the segfault only under libdislocator\,
so there is nothing for Valgrind to report when the panic kills Perl first\.

Anyway\, I'm reporting to the security queue because I have no idea what the
implications of this are\. It seems like normally\, Perl is surviving two
different errors here&#8203;: whatever triggers the panic\, and whatever triggers
the SEGV\. This may also be dependent on being built with X86 SSSE3
extensions?

**Comment by p5pRT** [comment]
### From @tonycoz

On Sun Sep 04 19&#8203;:50&#8203;:46 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> Anyway\, I'm reporting to the security queue because I have no idea what the
> implications of this are\. It seems like normally\, Perl is surviving two
> different errors here&#8203;: whatever triggers the panic\, and whatever triggers
> the SEGV\. This may also be dependent on being built with X86 SSSE3
> extensions?

The panic and SEGV appear to have the same cause\.

The problem is occuring at&#8203;:

&nbsp;        else sv = newSVpvn\(PL\_parser\->lex\_shared\->re\_eval\_start\,
&nbsp;             PL\_bufptr \- PL\_parser\->lex\_shared\->re\_eval\_start\);

where the problem is PL\_bufptr and PL\_parser\->lex\_shared\->re\_eval\_start
are pointing at different malloc\(\)ed block\.

When the block for PL\_bufptr is after the block for re\_eval\_start\, the length
it positive and we try to copy way too much data\, causing the SEGV\.

When the blocks are the other way around\, the length is negative\, and
sv\_setpvn\(\) panics\.

In the cases where neither happens I expect the memory blocks were ordered
per the first case\, and all the memory was mapped between them\.

The different tools add their own malloc\(\) implementations\, so I could see
this order differing between them\.

The SEGV from this issue is purely from reading unmapped memory\, the memory being written too has been allocated\.

The issue is finding why the two pointers are pointing into separate blocks\,
which I haven't tried to do yet\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Wed\, Sep 07\, 2016 at 09&#8203;:25&#8203;:30PM \-0700\, Tony Cook via RT wrote&#8203;:
> On Sun Sep 04 19&#8203;:50&#8203;:46 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> > Anyway\, I'm reporting to the security queue because I have no idea what the
> > implications of this are\. It seems like normally\, Perl is surviving two
> > different errors here&#8203;: whatever triggers the panic\, and whatever triggers
> > the SEGV\. This may also be dependent on being built with X86 SSSE3
> > extensions?
> 
> The panic and SEGV appear to have the same cause\.
> 
> The problem is occuring at&#8203;:
> 
>         else sv = newSVpvn\(PL\_parser\->lex\_shared\->re\_eval\_start\,
>              PL\_bufptr \- PL\_parser\->lex\_shared\->re\_eval\_start\);
> 
> where the problem is PL\_bufptr and PL\_parser\->lex\_shared\->re\_eval\_start
> are pointing at different malloc\(\)ed block\.
> 
> When the block for PL\_bufptr is after the block for re\_eval\_start\, the length
> it positive and we try to copy way too much data\, causing the SEGV\.
> 
> When the blocks are the other way around\, the length is negative\, and
> sv\_setpvn\(\) panics\.
> 
> In the cases where neither happens I expect the memory blocks were ordered
> per the first case\, and all the memory was mapped between them\.
> 
> The different tools add their own malloc\(\) implementations\, so I could see
> this order differing between them\.
> 
> The SEGV from this issue is purely from reading unmapped memory\, the memory being written too has been allocated\.
> 
> The issue is finding why the two pointers are pointing into separate blocks\,
> which I haven't tried to do yet\.

Fixed with the commit below\, which I've pushed to blead\.

It only occurs when there are heredocs within an re\_eval \(i\.e\.
/\(?\{ \<\<\.\.\. \}\)/\) and the lexer's line buffer gets realloced while parsing
that\.

The security implications are minimal\, because allowing an attacker to
control the source code within \(?\{\.\.\.?\) means you've already lost\. And if
the attacker can't control the source\, they have to find pre\-existing src
that contains a heredoc within a /\(?\{\.\.\.\}\)/ \(\*\) and is early enough in the
src file such that PL\_linestr stands a good chance of needing to be grown
and get reallocated\. And if they can find all that\, the worst that can
happen is a panic\, memory exhaustion\, or a qr// which stringifies to
garbage\.

But note that that garbage \*won't\* be used if the qr// is embedded within
another regex\.

\(\*\) and I can't see any such combination\, outside of test files\, on
http&#8203;://grep\.cpan\.me\.



\-\- 
A power surge on the Bridge is rapidly and correctly diagnosed as a faulty
capacitor by the highly\-trained and competent engineering staff\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#9

**Comment by p5pRT** [comment]
### From @tonycoz

On Sat\, 10 Dec 2016 07&#8203;:58&#8203;:36 \-0800\, davem wrote&#8203;:
> On Wed\, Sep 07\, 2016 at 09&#8203;:25&#8203;:30PM \-0700\, Tony Cook via RT wrote&#8203;:
> > On Sun Sep 04 19&#8203;:50&#8203;:46 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> > > Anyway\, I'm reporting to the security queue because I have no idea
> > > what the
> > > implications of this are\. It seems like normally\, Perl is surviving
> > > two
> > > different errors here&#8203;: whatever triggers the panic\, and whatever
> > > triggers
> > > the SEGV\. This may also be dependent on being built with X86 SSSE3
> > > extensions?
> >
> > The panic and SEGV appear to have the same cause\.
> >
> > The problem is occuring at&#8203;:
> >
> > else sv = newSVpvn\(PL\_parser\->lex\_shared\->re\_eval\_start\,
> >              PL\_bufptr \- PL\_parser\->lex\_shared\->re\_eval\_start\);
> >
> > where the problem is PL\_bufptr and PL\_parser\->lex\_shared\-
> > >re\_eval\_start
> > are pointing at different malloc\(\)ed block\.
> >
> > When the block for PL\_bufptr is after the block for re\_eval\_start\,
> > the length
> > it positive and we try to copy way too much data\, causing the SEGV\.
> >
> > When the blocks are the other way around\, the length is negative\, and
> > sv\_setpvn\(\) panics\.
> >
> > In the cases where neither happens I expect the memory blocks were
> > ordered
> > per the first case\, and all the memory was mapped between them\.
> >
> > The different tools add their own malloc\(\) implementations\, so I
> > could see
> > this order differing between them\.
> >
> > The SEGV from this issue is purely from reading unmapped memory\, the
> > memory being written too has been allocated\.
> >
> > The issue is finding why the two pointers are pointing into separate
> > blocks\,
> > which I haven't tried to do yet\.
> 
> Fixed with the commit below\, which I've pushed to blead\.

Presumably&#8203;:

commit 98d5e3efa825adce1bfa065a5deed791c30162ac
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Sat Dec 10 15&#8203;:06&#8203;:30 2016 \+0000

&nbsp;    misaligned buffer with heredoc and /\(?\{\.\.\.\}\)/
&nbsp;    
&nbsp;    RT \#129199
&nbsp;    
&nbsp;    When an re\_eval like /\(?\{\.\.\.\}\)/ is tokenised\, as well as tokenising the
&nbsp;    individual elements of the code\, the whole src string is returned as a
&nbsp;    constant too\, to enable the stringification of the regex to be calculated\.
&nbsp;    For example\,
&nbsp;    
&nbsp;        /abc\(?\{$x\}\)def/
&nbsp;    
&nbsp;    is tokenised like
&nbsp;    
&nbsp;        MATCH '\('
&nbsp;            CONST\('abc'\)
&nbsp;            DO  '\{'  '$'  CONST\('x'\) '\}'
&nbsp;            '\,'
&nbsp;            CONST\('\(?\{$x\}\)'\)
&nbsp;            '\,'
&nbsp;            CONST\('def'\)\,
&nbsp;        '\)'
&nbsp;    
&nbsp;    If the code within the \(?\{\.\.\.\}\) contains a heredoc \(\<\<\) and the PL\_linestr
&nbsp;    buffer happens to get reallocated\, the pointer which points to the start
&nbsp;    of the code string will get adjusted using the wrong buffer pointer\.
&nbsp;    Later when the end of the code is reached and the whole code string '\(?\{$x\}\)'
&nbsp;    is copied to a new SV\, garbage may get copied \(or it may panic with \-ve
&nbsp;    length\, out of memory etc\)\. Note that this garbage will only used for the
&nbsp;    string representation of the regex\, e\.g\.
&nbsp;    
&nbsp;        my $r = qr/abc\(?\{$x\}\)def/;
&nbsp;        print "$r"; \# garbage used here
&nbsp;        /xyz$r/;    \# garbage not used here

> The security implications are minimal\, because allowing an attacker to
> control the source code within \(?\{\.\.\.?\) means you've already lost\. And
> if
> the attacker can't control the source\, they have to find pre\-existing
> src
> that contains a heredoc within a /\(?\{\.\.\.\}\)/ \(\*\) and is early enough in
> the
> src file such that PL\_linestr stands a good chance of needing to be
> grown
> and get reallocated\. And if they can find all that\, the worst that can
> happen is a panic\, memory exhaustion\, or a qr// which stringifies to
> garbage\.
> 
> But note that that garbage \*won't\* be used if the qr// is embedded
> within
> another regex\.
> 
> \(\*\) and I can't see any such combination\, outside of test files\, on
> http&#8203;://grep\.cpan\.me\.

I agree\, made it public\.

Closing since it's fixed\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
