### ISSUE TITLE
heap-buffer-overflow Perl_sv_vcatpvfn_flags (sv.c:12912)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15599]
Migrated from [rt.perl.org#129274](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129274) (status was 'resolved')

Searchable as RT129274$

**Comment by p5pRT** [comment]
### From @geeknik

The attached test case triggers a heap\-use\-after\-free in Perl\_yylex
\(toke\.c&#8203;:4880\) in v5\.25\.5 \(v5\.25\.4\-130\-g7aa7bbc\)\. Perl 5\.20\.2 complains
about $\# no longer being supported\.

od \-tx1 test16
0000000 73 74 61 74 09 74 24 23 30
0000011

=================================================================
==28052==ERROR&#8203;: AddressSanitizer&#8203;: heap\-use\-after\-free on address
0x60200000e276 at pc 0x000000659334 bp 0x7ffc08f3c7b0 sp 0x7ffc08f3c7a8
READ of size 1 at 0x60200000e276 thread T0
&nbsp;    \#0 0x659333 in Perl\_yylex /root/perl/toke\.c&#8203;:4880&#8203;:5
&nbsp;    \#1 0x6add4e in Perl\_yyparse /root/perl/perly\.c&#8203;:334&#8203;:19
&nbsp;    \#2 0x59c491 in S\_parse\_body /root/perl/perl\.c&#8203;:2373&#8203;:9
&nbsp;    \#3 0x59283c in perl\_parse /root/perl/perl\.c&#8203;:1689&#8203;:2
&nbsp;    \#4 0x4de5d5 in main /root/perl/perlmain\.c&#8203;:121&#8203;:18
&nbsp;    \#5 0x7f5a33120b44 in \_\_libc\_start\_main
/build/glibc\-uPj9cH/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#6 0x4de26c in \_start \(/root/perl/perl\+0x4de26c\)

0x60200000e276 is located 6 bytes inside of 10\-byte region
\[0x60200000e270\,0x60200000e27a\)
freed by thread T0 here&#8203;:
&nbsp;    \#0 0x4c0ede in realloc \(/root/perl/perl\+0x4c0ede\)
&nbsp;    \#1 0x7f8a46 in Perl\_safesysrealloc /root/perl/util\.c&#8203;:274&#8203;:18

previously allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4c0beb in malloc \(/root/perl/perl\+0x4c0beb\)
&nbsp;    \#1 0x7f8357 in Perl\_safesysmalloc /root/perl/util\.c&#8203;:153&#8203;:21

SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-use\-after\-free /root/perl/toke\.c&#8203;:4880
Perl\_yylex
Shadow bytes around the buggy address&#8203;:
&nbsp;  0x0c047fff9bf0&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c047fff9c00&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c047fff9c10&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c047fff9c20&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c047fff9c30&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c047fff9c40&#8203;: fa fa fa fa fa fa 00 02 fa fa 00 02 fa fa\[fd\]fd
&nbsp;  0x0c047fff9c50&#8203;: fa fa 00 04 fa fa 02 fa fa fa 00 02 fa fa 00 07
&nbsp;  0x0c047fff9c60&#8203;: fa fa 00 fa fa fa 00 02 fa fa 05 fa fa fa 00 02
&nbsp;  0x0c047fff9c70&#8203;: fa fa 06 fa fa fa 00 02 fa fa 05 fa fa fa 00 05
&nbsp;  0x0c047fff9c80&#8203;: fa fa 04 fa fa fa 05 fa fa fa 05 fa fa fa 00 00
&nbsp;  0x0c047fff9c90&#8203;: fa fa 00 02 fa fa 05 fa fa fa 00 02 fa fa 00 fa
Shadow byte legend \(one shadow byte represents 8 application bytes\)&#8203;:
&nbsp;  Addressable&#8203;:           00
&nbsp;  Partially addressable&#8203;: 01 02 03 04 05 06 07
&nbsp;  Heap left redzone&#8203;:       fa
&nbsp;  Heap right redzone&#8203;:      fb
&nbsp;  Freed heap region&#8203;:       fd
&nbsp;  Stack left redzone&#8203;:      f1
&nbsp;  Stack mid redzone&#8203;:       f2
&nbsp;  Stack right redzone&#8203;:     f3
&nbsp;  Stack partial redzone&#8203;:   f4
&nbsp;  Stack after return&#8203;:      f5
&nbsp;  Stack use after scope&#8203;:   f8
&nbsp;  Global redzone&#8203;:          f9
&nbsp;  Global init order&#8203;:       f6
&nbsp;  Poisoned by user&#8203;:        f7
&nbsp;  Container overflow&#8203;:      fc
&nbsp;  ASan internal&#8203;:           fe
==28052==ABORTING

**Comment by p5pRT** [comment]
### From @geeknik

[test16.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1423396/770103/test16.gz)

**Comment by p5pRT** [comment]
### From @geeknik

The attached test case triggers a heap\-buffer\-overflow in
Perl\_sv\_vcatpvfn\_flags \(sv\.c&#8203;:12912\) in v5\.25\.5 \(v5\.25\.4\-130\-g7aa7bbc\)\. Perl
5\.20\.2 complains about $\# no longer being supported\.

od \-tx1 test17
0000000 73 74 61 74 09 74 24 23 10 24 24 24 24 6d 8d 2c
0000020 24 23 24 6d 6e 70 72 74 2c 70 6f 72 74 2c 73 6f
0000040 72 74 0a 73 6f 72 74 59
0000050

==21100==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
0x60400000a40e at pc 0x0000004a9680 bp 0x7ffd54be2db0 sp 0x7ffd54be2570
READ of size 10 at 0x60400000a40e thread T0
&nbsp;    \#0 0x4a967f in \_\_asan\_memcpy \(/root/perl/perl\+0x4a967f\)
&nbsp;    \#1 0x98cc46 in Perl\_sv\_vcatpvfn\_flags /root/perl/sv\.c&#8203;:12912&#8203;:6
&nbsp;    \#2 0x96d6d6 in Perl\_sv\_vsetpvfn /root/perl/sv\.c&#8203;:10809&#8203;:5
&nbsp;    \#3 0x802802 in Perl\_vmess /root/perl/util\.c&#8203;:1586&#8203;:5
&nbsp;    \#4 0x802802 in Perl\_vcroak /root/perl/util\.c&#8203;:1815
&nbsp;    \#5 0x7f86fc in Perl\_croak /root/perl/util\.c&#8203;:1862&#8203;:5
&nbsp;    \#6 0x62ca1e in Perl\_yylex /root/perl/toke\.c&#8203;:4910&#8203;:9
&nbsp;    \#7 0x6add4e in Perl\_yyparse /root/perl/perly\.c&#8203;:334&#8203;:19
&nbsp;    \#8 0x59c491 in S\_parse\_body /root/perl/perl\.c&#8203;:2373&#8203;:9
&nbsp;    \#9 0x59283c in perl\_parse /root/perl/perl\.c&#8203;:1689&#8203;:2
&nbsp;    \#10 0x4de5d5 in main /root/perl/perlmain\.c&#8203;:121&#8203;:18
&nbsp;    \#11 0x7fbb50d10b44 in \_\_libc\_start\_main
/build/glibc\-uPj9cH/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#12 0x4de26c in \_start \(/root/perl/perl\+0x4de26c\)

0x60400000a40e is located 2 bytes to the left of 48\-byte region
\[0x60400000a410\,0x60400000a440\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4c0ede in realloc \(/root/perl/perl\+0x4c0ede\)
&nbsp;    \#1 0x7f8a46 in Perl\_safesysrealloc /root/perl/util\.c&#8203;:274&#8203;:18

SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow ??&#8203;:0 \_\_asan\_memcpy
Shadow bytes around the buggy address&#8203;:
&nbsp;  0x0c087fff9430&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c087fff9440&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c087fff9450&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c087fff9460&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c087fff9470&#8203;: fa fa fa fa fa fa fa fa fa fa 00 00 00 00 03 fa
=>0x0c087fff9480&#8203;: fa\[fa\]00 00 00 00 00 00 fa fa 00 00 00 00 00 fa
&nbsp;  0x0c087fff9490&#8203;: fa fa 00 00 00 00 00 00 fa fa 00 00 00 00 00 00
&nbsp;  0x0c087fff94a0&#8203;: fa fa 00 00 00 00 00 00 fa fa 00 00 00 00 06 fa
&nbsp;  0x0c087fff94b0&#8203;: fa fa 00 00 00 00 00 01 fa fa 00 00 00 00 00 00
&nbsp;  0x0c087fff94c0&#8203;: fa fa 00 00 00 00 06 fa fa fa 00 00 00 00 00 00
&nbsp;  0x0c087fff94d0&#8203;: fa fa 00 00 00 00 07 fa fa fa 00 00 00 00 00 00
Shadow byte legend \(one shadow byte represents 8 application bytes\)&#8203;:
&nbsp;  Addressable&#8203;:           00
&nbsp;  Partially addressable&#8203;: 01 02 03 04 05 06 07
&nbsp;  Heap left redzone&#8203;:       fa
&nbsp;  Heap right redzone&#8203;:      fb
&nbsp;  Freed heap region&#8203;:       fd
&nbsp;  Stack left redzone&#8203;:      f1
&nbsp;  Stack mid redzone&#8203;:       f2
&nbsp;  Stack right redzone&#8203;:     f3
&nbsp;  Stack partial redzone&#8203;:   f4
&nbsp;  Stack after return&#8203;:      f5
&nbsp;  Stack use after scope&#8203;:   f8
&nbsp;  Global redzone&#8203;:          f9
&nbsp;  Global init order&#8203;:       f6
&nbsp;  Poisoned by user&#8203;:        f7
&nbsp;  Container overflow&#8203;:      fc
&nbsp;  ASan internal&#8203;:           fe
==21100==ABORTING

**Comment by p5pRT** [comment]
### From @geeknik

[test17.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1423403/770110/test17.gz)

**Comment by p5pRT** [comment]
### From @hvds

A shorter test case \(failure indicated by "column \-1"\)&#8203;:

% perl \-le 'print "stat t\\$\#\\x\{10\}"' | \./miniperl
$\# is no longer supported at \- line 1\.
Unrecognized character \\x10; marked by \<\-\- HERE after stat t$\#\<\-\- HERE near column \-1 at \- line 1\.
% 

This is a lexer issue that I do not have sufficient knowledge to fix&#8203;: at the point toke\.c&#8203;:4910 wants to report that \\x\{10\} is an unrecognized character\, PL\_linestart is already pointing at the following line\. This was advanced by S\_intuit\_method calling skipspace\(\) at the '\#' after seeing the '$'\, which skipspace then treated as a comment\.

I don't think this is likely to be a security concern\.

Hugo

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @hvds

I think this has the same root cause as \#129274\, just taking a different route after the call to skipspace\(\) from intuit\_method\(\)\.

Hugo

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Wed\, 05 Oct 2016 06&#8203;:04&#8203;:14 \-0700\, hv wrote&#8203;:
> A shorter test case \(failure indicated by "column \-1"\)&#8203;:
> 
> % perl \-le 'print "stat t\\$\#\\x\{10\}"' | \./miniperl
> $\# is no longer supported at \- line 1\.
> Unrecognized character \\x10; marked by \<\-\- HERE after stat t$\#\<\-\- HERE
> near column \-1 at \- line 1\.
>  %
> 
> This is a lexer issue that I do not have sufficient knowledge to fix&#8203;:
> at the point toke\.c&#8203;:4910 wants to report that \\x\{10\} is an
> unrecognized character\, PL\_linestart is already pointing at the
> following line\. This was advanced by S\_intuit\_method calling
> skipspace\(\) at the '\#' after seeing the '$'\, which skipspace then
> treated as a comment\.
> 
> I don't think this is likely to be a security concern\.

I agree\, so I've move the ticket to the public queue\.

Treating the \# immediately following the $ as a comment in
intuit\_method\(\) strikes me as a bug in itself\, which I think
the attached fixes\.

I don't think this fixes the base issue though \- I'm not sure
how to fix that\, perhaps intuit\_method\(\) should be restoring
PL\_linestart\.

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

<details><summary>0001-perl-129274-avoid-treating-the-in-as-a-comment-intro.patch</summary>

```diff
From e30a508ca4fb9d4cd2164e495ea9f76420d6dae4 Mon Sep 17 00:00:00 2001
From: Tony Cook <tony@develop-help.com>
Date: Wed, 30 Nov 2016 15:28:16 +1100
Subject: (perl #129274) avoid treating the # in $# as a comment intro

---
 toke.c | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/toke.c b/toke.c
index 11abf2b..2a7b374 100644
--- a/toke.c
+++ b/toke.c
@@ -4092,7 +4092,9 @@ S_intuit_method(pTHX_ char *start, SV *ioname, CV *cv)
 	if (cv || PL_last_lop_op == OP_PRINT || PL_last_lop_op == OP_SAY
             || isUPPER(*PL_tokenbuf))
 	    return 0;
-	s = skipspace(s);
+        /* this could be $# */
+        if (isSPACE(*s))
+            s = skipspace(s);
 	PL_bufptr = start;
 	PL_expect = XREF;
 	return *s == '(' ? FUNCMETH : METHOD;
-- 
2.1.4


```
</details>

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue\, 29 Nov 2016 20&#8203;:31&#8203;:40 \-0800\, tonyc wrote&#8203;:
> On Wed\, 05 Oct 2016 06&#8203;:04&#8203;:14 \-0700\, hv wrote&#8203;:
> > I don't think this is likely to be a security concern\.
> 
> I agree\, so I've move the ticket to the public queue\.
> 
> Treating the \# immediately following the $ as a comment in
> intuit\_method\(\) strikes me as a bug in itself\, which I think
> the attached fixes\.
> 
> I don't think this fixes the base issue though \- I'm not sure
> how to fix that\, perhaps intuit\_method\(\) should be restoring
> PL\_linestart\.

I spent some time trying to make this crash with my patch in place but couldn't manage it\.

I've applied my patch \(with a test added\) as 71776ae4fad9a7659deefe0c2376d45b873ffd6a\.

Please open a new ticket if you manage to find a similar issue this commit
doesn't fix\.

Closing this ticket\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @tonycoz

On Thu\, 06 Oct 2016 07&#8203;:17&#8203;:42 \-0700\, hv wrote&#8203;:
> I think this has the same root cause as \#129274\, just taking a
> different route after the call to skipspace\(\) from intuit\_method\(\)\.

I agree\, merging into 129274\, which is public and fixed/closed\.

Tony

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
