### ISSUE TITLE
Assertion `!(o->op_private & ~PL_op_private_valid[type])' failed

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15619]
Migrated from [rt.perl.org#129320](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129320) (status was 'resolved')

Searchable as RT129320$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered in Perl v5\.25\.5 \(v5\.25\.4\-110\-g95c0a76\)\.

\./perl \-e 'sub\{map\{0\}0\.\.~0'
Range iterator outside integer range at \-e line 1\.
perl&#8203;: op\.c&#8203;:791&#8203;: void Perl\_op\_free\(OP \*\)&#8203;: Assertion \`\!\(o\->op\_private & ~PL\_op\_private\_valid\[type\]\)' failed\.
Aborted

**Comment by p5pRT** [comment]
### From @hvds

On Tue\, 20 Sep 2016 13&#8203;:39&#8203;:11 \-0700\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> Triggered in Perl v5\.25\.5 \(v5\.25\.4\-110\-g95c0a76\)\.
> 
> \./perl \-e 'sub\{map\{0\}0\.\.~0'
> Range iterator outside integer range at \-e line 1\.
> perl&#8203;: op\.c&#8203;:791&#8203;: void Perl\_op\_free\(OP \*\)&#8203;: Assertion \`\!\(o\->op\_private &
> ~PL\_op\_private\_valid\[type\]\)' failed\.
> Aborted

op\_private is "by default\, set to the number of children until the operation is privatized by a check routine"\.

In this case we're in ck\_grep\(\) for the MAPSTART op\, and op\_private has been set to 2 for the number of children; however we see the range error and die \(and thus try to free the ops\) before that gets far enough to reset it at op\.c&#8203;:10304&#8203;:
&nbsp;    o\->op\_private = gwop\->op\_private = 0;

Here are the parts of the stack trace I think are relevant&#8203;:

\#3  0x00007ffff72e7ca2 in \_\_GI\_\_\_assert\_fail \(
&nbsp;    assertion=0x720f60 "\!\(o\->op\_private & ~PL\_op\_private\_valid\[type\]\)"\, 
&nbsp;    file=0x7204ee "op\.c"\, line=791\, 
&nbsp;    function=0x72e413 \<\_\_PRETTY\_FUNCTION\_\_\.15100> "Perl\_op\_free"\)
&nbsp;    at assert\.c&#8203;:101
\#4  0x00000000004073fa in Perl\_op\_free \(o=0xa6bad8\) at op\.c&#8203;:791
\[\.\.\.\]
\#17 0x00000000005408d5 in Perl\_die \(
&nbsp;    pat=0x7d8ed0 "Range iterator outside integer range"\) at util\.c&#8203;:1736
\#18 0x000000000063f182 in Perl\_pp\_flop \(\) at pp\_ctl\.c&#8203;:1187
\#19 0x000000000053a7ba in Perl\_runops\_debug \(\) at dump\.c&#8203;:2260
\#20 0x0000000000413494 in S\_gen\_constant\_list \(o=0xa6bb60\) at op\.c&#8203;:4581
\#21 0x000000000040aa3c in Perl\_list \(o=0xa6bb60\) at op\.c&#8203;:2295
\#22 0x000000000040a6a4 in S\_listkids \(o=0xa6bad8\) at op\.c&#8203;:2234
\#23 0x000000000042f487 in Perl\_ck\_fun \(o=0xa6bad8\) at op\.c&#8203;:10205
\#24 0x000000000042f855 in Perl\_ck\_grep \(o=0xa6bad8\) at op\.c&#8203;:10294
\[\.\.\.\]

I don't know why setting op\_private to numargs doesn't cause problems like this more regularly\, or how this sort of thing should be fixed\.

Hugo

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, Dec 06\, 2016 at 05&#8203;:40&#8203;:36AM \-0800\, Hugo van der Sanden via RT wrote&#8203;:
> On Tue\, 20 Sep 2016 13&#8203;:39&#8203;:11 \-0700\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> > Triggered in Perl v5\.25\.5 \(v5\.25\.4\-110\-g95c0a76\)\.
> > 
> > \./perl \-e 'sub\{map\{0\}0\.\.~0'
> > Range iterator outside integer range at \-e line 1\.
> > perl&#8203;: op\.c&#8203;:791&#8203;: void Perl\_op\_free\(OP \*\)&#8203;: Assertion \`\!\(o\->op\_private &
> > ~PL\_op\_private\_valid\[type\]\)' failed\.
> > Aborted
> 
> op\_private is "by default\, set to the number of children until the operation is privatized by a check routine"\.
> 
> In this case we're in ck\_grep\(\) for the MAPSTART op\, and op\_private has been set to 2 for the number of children; however we see the range error and die \(and thus try to free the ops\) before that gets far enough to reset it at op\.c&#8203;:10304&#8203;:
>     o\->op\_private = gwop\->op\_private = 0;
> 
> Here are the parts of the stack trace I think are relevant&#8203;:
> 
> \#3  0x00007ffff72e7ca2 in \_\_GI\_\_\_assert\_fail \(
>     assertion=0x720f60 "\!\(o\->op\_private & ~PL\_op\_private\_valid\[type\]\)"\, 
>     file=0x7204ee "op\.c"\, line=791\, 
>     function=0x72e413 \<\_\_PRETTY\_FUNCTION\_\_\.15100> "Perl\_op\_free"\)
>     at assert\.c&#8203;:101
> \#4  0x00000000004073fa in Perl\_op\_free \(o=0xa6bad8\) at op\.c&#8203;:791
> \[\.\.\.\]
> \#17 0x00000000005408d5 in Perl\_die \(
>     pat=0x7d8ed0 "Range iterator outside integer range"\) at util\.c&#8203;:1736
> \#18 0x000000000063f182 in Perl\_pp\_flop \(\) at pp\_ctl\.c&#8203;:1187
> \#19 0x000000000053a7ba in Perl\_runops\_debug \(\) at dump\.c&#8203;:2260
> \#20 0x0000000000413494 in S\_gen\_constant\_list \(o=0xa6bb60\) at op\.c&#8203;:4581
> \#21 0x000000000040aa3c in Perl\_list \(o=0xa6bb60\) at op\.c&#8203;:2295
> \#22 0x000000000040a6a4 in S\_listkids \(o=0xa6bad8\) at op\.c&#8203;:2234
> \#23 0x000000000042f487 in Perl\_ck\_fun \(o=0xa6bad8\) at op\.c&#8203;:10205
> \#24 0x000000000042f855 in Perl\_ck\_grep \(o=0xa6bad8\) at op\.c&#8203;:10294
> \[\.\.\.\]
> 
> I don't know why setting op\_private to numargs doesn't cause problems like this more regularly\, or how this sort of thing should be fixed\.

I haven't looked closely at this particular issue\, but that assert isn't
supposed to be checked if we have errored\, i\.e\.

&nbsp;    Perl\_op\_free\(pTHX\_ OP \*o\)
&nbsp;    \{
&nbsp;    \.\.\.
&nbsp;    \#ifdef DEBUGGING
&nbsp;            if \(   o\->op\_ppaddr == PL\_ppaddr\[o\->op\_type\]
&nbsp;                && PL\_parser
&nbsp;                && \!PL\_parser\->error\_count\)
&nbsp;            \{
&nbsp;                assert\(\!\(o\->op\_private & ~PL\_op\_private\_valid\[type\]\)\);
&nbsp;            \}
&nbsp;    \#endif

so perhaps the issue here is why PL\_parser\->error\_count isn't true at that
point\.

\-\- 
"I do not resent criticism\, even when\, for the sake of emphasis\,
it parts for the time with reality"\.
&nbsp;    \-\- Winston Churchill\, House of Commons\, 22nd Jan 1941\.

**Comment by p5pRT** [comment]
### From @hvds

On Tue\, 06 Dec 2016 06&#8203;:15&#8203;:08 \-0800\, davem wrote&#8203;:
> I haven't looked closely at this particular issue\, but that assert
> isn't supposed to be checked if we have errored\, i\.e\.
> 
> Perl\_op\_free\(pTHX\_ OP \*o\)
> \{
> \.\.\.
> \#ifdef DEBUGGING
>         if \(   o\->op\_ppaddr == PL\_ppaddr\[o\->op\_type\]
>             && PL\_parser
>             && \!PL\_parser\->error\_count\)
>         \{
>             assert\(\!\(o\->op\_private & ~PL\_op\_private\_valid\[type\]\)\);
>         \}
> \#endif
> 
> so perhaps the issue here is why PL\_parser\->error\_count isn't true at
> that point\.

Ah\, good point\, I missed that\. I'll look more this evening\.

Hugo

**Comment by p5pRT** [comment]
### From @hvds

On Tue\, 06 Dec 2016 06&#8203;:15&#8203;:08 \-0800\, davem wrote&#8203;:
> so perhaps the issue here is why PL\_parser\->error\_count isn't true at that
> point\.

It looks like error\_count is only touched by Perl\_qerror\(\)\, which is called in only a handful of places \- and I guess it's intended only for compile errors\. This particular error is a runtime error\, triggered at this point by constant folding\.

Given that a runtime error can kill us mid\-compile\, we could make the op\_free check require IN\_PERL\_RUNTIME \- but my gut says that's a lot too broad\, where the current check is only slightly too narrow\.

I think the right answer is not to let it happen in the first place\. Back in 2006 \(commit b7f7fd0b\)\, constant folding was \(effectively\) wrapped in an eval\{\} so we could defer till runtime if it raised an error\. I'm not sure why the same wasn't applied to gen\_constant\_list\(\) at the time\, but it feels like it's needed here for the same reason\, and it'd also handily fix this problem\.

The test\-case \(and primary justification\) for that is that neither of these should die&#8203;:

% perl \-le 'if \(0\) \{ $a = 1 / 0 \} print "fold\_constants ok"'
fold\_constants ok
% perl \-le 'if \(0\) \{ @&#8203;a = 0\.\.~0 \} print "gen\_constant\_list ok"'
Range iterator outside integer range at \-e line 1\.
% 

Hugo

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Fixed by 3a0fe090c1f24f4a3748d00616b87eb4c8dd4475\.

\-zefram

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
