### ISSUE TITLE
null ptr deref, segfault in Perl_mro_isa_changed_in (mro_core.c:501)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15614]
Migrated from [rt.perl.org#129301](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129301) (status was 'open')

Searchable as RT129301$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered with Perl v5\.25\.5 \(v5\.25\.4\-130\-g7aa7bbc\) and AFL\+ASAN\+libdislocator\.

\./perl \-e '0\<&#8203;::\,%&#8203;:=0\,\*&#8203;::&#8203;::=&#8203;::\,\*&#8203;:=%0'

ASAN&#8203;:SIGSEGV
=================================================================
==29936==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000004 \(pc 0x000000852782 bp 0x7ffe60699710 sp 0x7ffe606995c0 T0\)
&nbsp;    \#0 0x852781 in Perl\_mro\_isa\_changed\_in /root/perl/mro\_core\.c&#8203;:501&#8203;:5
&nbsp;    \#1 0x8570e4 in Perl\_mro\_package\_moved /root/perl/mro\_core\.c&#8203;:877&#8203;:6
&nbsp;    \#2 0x927f0e in Perl\_sv\_setsv\_flags /root/perl/sv\.c&#8203;:4559&#8203;:4
&nbsp;    \#3 0x8a228e in Perl\_pp\_sassign /root/perl/pp\_hot\.c&#8203;:226&#8203;:5
&nbsp;    \#4 0x7f4583 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2239&#8203;:23
&nbsp;    \#5 0x5a11c6 in S\_run\_body /root/perl/perl\.c&#8203;:2525&#8203;:2
&nbsp;    \#6 0x5a11c6 in perl\_run /root/perl/perl\.c&#8203;:2448
&nbsp;    \#7 0x4de5fd in main /root/perl/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#8 0x7f098f116b44 in \_\_libc\_start\_main /build/glibc\-uPj9cH/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#9 0x4de26c in \_start \(/root/perl/perl\+0x4de26c\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /root/perl/mro\_core\.c&#8203;:501 Perl\_mro\_isa\_changed\_in
==29936==ABORTING

**Comment by p5pRT** [comment]
### From @cpansprout

On Sun Sep 18 12&#8203;:50&#8203;:10 2016\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> Triggered with Perl v5\.25\.5 \(v5\.25\.4\-130\-g7aa7bbc\) and
> AFL\+ASAN\+libdislocator\.
> 
> \./perl \-e '0\<&#8203;::\,%&#8203;:=0\,\*&#8203;::&#8203;::=&#8203;::\,\*&#8203;:=%0'
> 

$ \./perl \-e '\*&#8203;::&#8203;::=&#8203;::; \*&#8203;:=%0'
Segmentation fault&#8203;: 11

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by richardleach** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
Perl_mro_isa_changed_in (my_perl=my_perl@entry=0x555555ad52a0, stash=stash@entry=0x555555b063f8) at mro_core.c:526
526	   const char * const stashname = HvENAME_get(stash);
(gdb) bt
#0  Perl_mro_isa_changed_in (my_perl=my_perl@entry=0x555555ad52a0, stash=stash@entry=0x555555b063f8) at mro_core.c:526
#1  0x00005555556a8089 in Perl_mro_package_moved (my_perl=my_perl@entry=0x555555ad52a0, stash=<optimized out>, oldstash=oldstash@entry=0x0, gv=gv@entry=0x555555b063c8, 
    flags=flags@entry=0) at mro_core.c:902
#2  0x00005555557e93aa in Perl_sv_setsv_flags (my_perl=0x555555ad52a0, dsv=0x555555b063c8, ssv=0x555555b063b0, flags=<optimized out>) at sv.c:4647
#3  0x00005555557104d3 in Perl_pp_sassign (my_perl=0x555555ad52a0) at pp_hot.c:497
#4  0x000055555566783a in Perl_runops_debug (my_perl=0x555555ad52a0) at dump.c:3486
#5  0x000055555564f409 in S_run_body (my_perl=0x555555ad52a0, oldscope=1) at perl.c:2935
#6  perl_run (my_perl=0x555555ad52a0) at perl.c:2848
#7  0x0000555555615e10 in main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>) at perlmain.c:127
```
