### ISSUE TITLE
null pointer deref Perl_re_intuit_start (regexec.c:1049)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15628]
Migrated from [rt.perl.org#129350](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129350) (status was 'resolved')

Searchable as RT129350$

**Comment by p5pRT** [comment]
### From @geeknik

This one crashes both Perl 5\.20\.2 and Perl v5\.25\.5\-8\-g3c42ae1\. Found with AFL\+ASAN\.

od \-tx1 test32
0000000 73 25 25 22 22 26 28 22 18 5c 37 30 30 22 3d 7e
0000020 2f 5c 62 5c 7a 30 2a 5c 37 30 30 2f 29 25 65
0000037

Perl v5\.25\.5\-8\-g3c42ae1&#8203;:
==16060==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x00000000000c \(pc 0x000000b51e90 bp 0x7ffc641c93f0 sp 0x7ffc641c9180 T0\)
&nbsp;    \#0 0xb51e8f in Perl\_re\_intuit\_start /root/perl/regexec\.c&#8203;:1049&#8203;:9
&nbsp;    \#1 0xb439a1 in Perl\_regexec\_flags /root/perl/regexec\.c&#8203;:2988&#8203;:6
&nbsp;    \#2 0x8c2ef8 in Perl\_pp\_match /root/perl/pp\_hot\.c&#8203;:1836&#8203;:10
&nbsp;    \#3 0x7f47d3 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2239&#8203;:23
&nbsp;    \#4 0x5a11c6 in S\_run\_body /root/perl/perl\.c&#8203;:2526&#8203;:2
&nbsp;    \#5 0x5a11c6 in perl\_run /root/perl/perl\.c&#8203;:2449
&nbsp;    \#6 0x4de5fd in main /root/perl/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#7 0x7f88f6ef3b44 in \_\_libc\_start\_main /build/glibc\-uPj9cH/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#8 0x4de26c in \_start \(/root/perl/perl\+0x4de26c\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /root/perl/regexec\.c&#8203;:1049 Perl\_re\_intuit\_start
==16060==ABORTING

\(gdb\) list
1044            s = HOP3c\(rx\_origin\, other\->min\_offset\, strend\);
1045            if \(s \< other\_last\)     /\* These positions already checked \*/
1046                s = other\_last;
1047
1048            must = utf8\_target ? other\->utf8\_substr : other\->substr;
1049            assert\(SvPOK\(must\)\);
1050            \{
1051                char \*from = s;
1052                char \*to   = last \+ SvCUR\(must\) \- \(SvTAIL\(must\)\!=0\);
1053

Perl 5\.20\.2&#8203;:
==23698== Invalid read of size 4
==23698==    at 0x4F6AF8A&#8203;: Perl\_re\_intuit\_start \(in /usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==23698==    by 0x4F6C34E&#8203;: Perl\_regexec\_flags \(in /usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==23698==    by 0x4EFEC7D&#8203;: Perl\_pp\_match \(in /usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==23698==    by 0x4EFB055&#8203;: Perl\_runops\_standard \(in /usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==23698==    by 0x4E8B73D&#8203;: perl\_run \(in /usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==23698==    by 0x400E18&#8203;: main \(in /usr/bin/perl\)
==23698==  Address 0xc is not stack'd\, malloc'd or \(recently\) free'd
==23698==
==23698==
==23698== Process terminating with default action of signal 11 \(SIGSEGV\)
==23698==  Access not within mapped region at address 0xC
==23698==    at 0x4F6AF8A&#8203;: Perl\_re\_intuit\_start \(in /usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==23698==    by 0x4F6C34E&#8203;: Perl\_regexec\_flags \(in /usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==23698==    by 0x4EFEC7D&#8203;: Perl\_pp\_match \(in /usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==23698==    by 0x4EFB055&#8203;: Perl\_runops\_standard \(in /usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==23698==    by 0x4E8B73D&#8203;: perl\_run \(in /usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==23698==    by 0x400E18&#8203;: main \(in /usr/bin/perl\)
==23698==  If you believe this happened as a result of a stack
==23698==  overflow in your program's main thread \(unlikely but
==23698==  possible\)\, you can try to increase the size of the
==23698==  main thread stack using the \-\-main\-stacksize= flag\.
==23698==  The main thread stack size used in this run was 8388608\.
Segmentation fault

**Comment by p5pRT** [comment]
### From @geeknik

[test32.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1424888/771016/test32.gz)

**Comment by p5pRT** [comment]
### From @cpansprout

On Sat Sep 24 17&#8203;:16&#8203;:05 2016\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> This one crashes both Perl 5\.20\.2 and Perl v5\.25\.5\-8\-g3c42ae1\. Found
> with AFL\+ASAN\.
> 
> od \-tx1 test32
> 0000000 73 25 25 22 22 26 28 22 18 5c 37 30 30 22 3d 7e
> 0000020 2f 5c 62 5c 7a 30 2a 5c 37 30 30 2f 29 25 65
> 0000037

This is a simple as I can get it&#8203;:

$ \./miniperl \-e '"\.\\x\{100\}" =~ /\\b\\z0\*\\x\{100\}/'
Segmentation fault&#8203;: 11

$ \./perl \-Ilib \-Mre=debug \-e '"\.\\x\{100\}" =~ /\\b\\z0\*\\x\{100\}/'
Compiling REx "\\b\\z0\*\\x\{100\}"
Final program&#8203;:
&nbsp;   1&#8203;: BOUNDU \(2\)
&nbsp;   2&#8203;: EOS \(3\)
&nbsp;   3&#8203;: STAR \(6\)
&nbsp;   4&#8203;:   EXACT \<0> \(0\)
&nbsp;   6&#8203;: EXACT \<\\x\{100\}> \(8\)
&nbsp;   8&#8203;: END \(0\)
anchored ""$ at 0 floating utf8 "%x\{100\}" at 0\.\.9223372036854775807 \(checking floating\) stclass BOUNDU minlen 1 
Matching REx "\\b\\z0\*\\x\{100\}" against "\.%x\{100\}"
UTF\-8 pattern and string\.\.\.
Intuit&#8203;: trying to determine minimum start position\.\.\.
&nbsp;  doing 'check' fbm scan\, \[0\.\.3\] gave 1
&nbsp;  Found floating substr "%x\{100\}" at offset 1 \(rx\_origin now 0\)\.\.\.
&nbsp;  \(multiline anchor test skipped\)
&nbsp;  looking for class&#8203;: start\_shift&#8203;: 0 check\_at&#8203;: 1 rx\_origin&#8203;: 0 endpos&#8203;: 1
&nbsp;  This position contradicts STCLASS\.\.\.
&nbsp;  about to retry anchored at offset 0 \(rx\_origin now 0\)\.\.\.
Segmentation fault&#8203;: 11


\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @hvds

This should be fixed by 2814f4b354&#8203;:

&nbsp;    \[perl \#129350\] anchored/floating substrings must be utf8 if target is
&nbsp;    
&nbsp;    If the target is utf8 and either the anchored or floating substrings
&nbsp;    are not\, we need to create utf8 copies to check against\. The state
&nbsp;    of the two substrings may not be the same\, but we were only testing
&nbsp;    whichever we planned to check first\.

Hugo

**Comment by p5pRT** [comment]
@hvds - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @hvds

This should be fixed by 2814f4b354&#8203;:

&nbsp;    \[perl \#129350\] anchored/floating substrings must be utf8 if target is
&nbsp;    
&nbsp;    If the target is utf8 and either the anchored or floating substrings
&nbsp;    are not\, we need to create utf8 copies to check against\. The state
&nbsp;    of the two substrings may not be the same\, but we were only testing
&nbsp;    whichever we planned to check first\.

Hugo

**Comment by p5pRT** [comment]
### From @xsawyerx

On Tue Oct 04 17&#8203;:21&#8203;:05 2016\, hv wrote&#8203;:
> This should be fixed by 2814f4b354

Is it verified?

I would be happy to resolve the ticket\. :\)

**Comment by p5pRT** [comment]
### From @hvds

On Tue Oct 11 08&#8203;:05&#8203;:21 2016\, xsawyerx@&#8203;cpan\.org wrote&#8203;:
> On Tue Oct 04 17&#8203;:21&#8203;:05 2016\, hv wrote&#8203;:
> > This should be fixed by 2814f4b354
> 
> Is it verified?
> 
> I would be happy to resolve the ticket\. :\)

I'm not sure I understand the question\, or the intended action\. The corresponding test passes in smokes \- is that the verification you're asking about? The fix is not yet in a stable release of perl\, so I think the ticket is as far resolved as it should be at this stage\.

Hugo

**Comment by p5pRT** [comment]
### From @xsawyerx



On 10/11/2016 05&#8203;:45 PM\, Hugo van der Sanden via RT wrote&#8203;:
> On Tue Oct 11 08&#8203;:05&#8203;:21 2016\, xsawyerx@&#8203;cpan\.org wrote&#8203;:
>> On Tue Oct 04 17&#8203;:21&#8203;:05 2016\, hv wrote&#8203;:
>>> This should be fixed by 2814f4b354
>> Is it verified?
>>
>> I would be happy to resolve the ticket\. :\)
> \[\.\.\.\] The fix is not yet in a stable release of perl\, so I think the ticket is as far resolved as it should be at this stage\.

You have answered my question\. Thank you\. :\)

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
