### ISSUE TITLE
null pointer deref S_ft_return_false (pp_sys.c:3036)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15626]
Migrated from [rt.perl.org#129347](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129347) (status was 'resolved')

Searchable as RT129347$

**Comment by p5pRT** [comment]
### From @geeknik

Found with AFL\+ASAN\, triggered in Perl v5\.25\.5\-8\-g3c42ae1\.

\./perl \-e '\($0\)=sort\{\-b\-d\}/\(\)\(\)/'

ASAN&#8203;:SIGSEGV
=================================================================
==24203==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000020 \(pc 0x000000ae09f0 bp 0x00000023636c sp 0x7ffd31ec7a20 T0\)
&nbsp;    \#0 0xae09ef in S\_ft\_return\_false /root/perl/pp\_sys\.c&#8203;:3036&#8203;:9
&nbsp;    \#1 0xae09ef in Perl\_pp\_ftrowned /root/perl/pp\_sys\.c&#8203;:3310
&nbsp;    \#2 0x7f47d3 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2239&#8203;:23
&nbsp;    \#3 0xca05fa in S\_sortcv /root/perl/pp\_sort\.c&#8203;:1800&#8203;:5
&nbsp;    \#4 0xc908ce in dynprep /root/perl/pp\_sort\.c&#8203;:197&#8203;:14
&nbsp;    \#5 0xc908ce in S\_mergesortsv /root/perl/pp\_sort\.c&#8203;:379
&nbsp;    \#6 0xc908ce in Perl\_sortsv\_flags /root/perl/pp\_sort\.c&#8203;:1464
&nbsp;    \#7 0xc9b847 in Perl\_pp\_sort /root/perl/pp\_sort\.c&#8203;:1687&#8203;:6
&nbsp;    \#8 0x7f47d3 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2239&#8203;:23
&nbsp;    \#9 0x5a11c6 in S\_run\_body /root/perl/perl\.c&#8203;:2526&#8203;:2
&nbsp;    \#10 0x5a11c6 in perl\_run /root/perl/perl\.c&#8203;:2449
&nbsp;    \#11 0x4de5fd in main /root/perl/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#12 0x7feccecd4b44 in \_\_libc\_start\_main /build/glibc\-uPj9cH/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#13 0x4de26c in \_start \(/root/perl/perl\+0x4de26c\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /root/perl/pp\_sys\.c&#8203;:3036 S\_ft\_return\_false
==24203==ABORTING

**Comment by p5pRT** [comment]
### From @mauke

Am 24\.09\.2016 um 14&#8203;:59 schrieb Brian Carpenter \(via RT\)&#8203;:
> \# New Ticket Created by  Brian Carpenter
> \# Please include the string&#8203;:  \[perl \#129347\]
> \# in the subject line of all future correspondence about this issue\.
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129347 >
>
>
> Found with AFL\+ASAN\, triggered in Perl v5\.25\.5\-8\-g3c42ae1\.
>
> \./perl \-e '\($0\)=sort\{\-b\-d\}/\(\)\(\)/'
>
> ASAN&#8203;:SIGSEGV
> =================================================================
> ==24203==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000020 \(pc 0x000000ae09f0 bp 0x00000023636c sp 0x7ffd31ec7a20 T0\)
>     \#0 0xae09ef in S\_ft\_return\_false /root/perl/pp\_sys\.c&#8203;:3036&#8203;:9
>     \#1 0xae09ef in Perl\_pp\_ftrowned /root/perl/pp\_sys\.c&#8203;:3310
>     \#2 0x7f47d3 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2239&#8203;:23
>     \#3 0xca05fa in S\_sortcv /root/perl/pp\_sort\.c&#8203;:1800&#8203;:5
>     \#4 0xc908ce in dynprep /root/perl/pp\_sort\.c&#8203;:197&#8203;:14
>     \#5 0xc908ce in S\_mergesortsv /root/perl/pp\_sort\.c&#8203;:379
>     \#6 0xc908ce in Perl\_sortsv\_flags /root/perl/pp\_sort\.c&#8203;:1464
>     \#7 0xc9b847 in Perl\_pp\_sort /root/perl/pp\_sort\.c&#8203;:1687&#8203;:6
>     \#8 0x7f47d3 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2239&#8203;:23
>     \#9 0x5a11c6 in S\_run\_body /root/perl/perl\.c&#8203;:2526&#8203;:2
>     \#10 0x5a11c6 in perl\_run /root/perl/perl\.c&#8203;:2449
>     \#11 0x4de5fd in main /root/perl/perlmain\.c&#8203;:123&#8203;:9
>     \#12 0x7feccecd4b44 in \_\_libc\_start\_main /build/glibc\-uPj9cH/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
>     \#13 0x4de26c in \_start \(/root/perl/perl\+0x4de26c\)
>
> AddressSanitizer can not provide additional info\.
> SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /root/perl/pp\_sys\.c&#8203;:3036 S\_ft\_return\_false
> ==24203==ABORTING

'\(\) = sort \{ \-d \-d \} 1\, 2' also crashes\. The trigger seems to be stacked 
filetests in a sort comparator\. \(You need at least 2 list elements to 
invoke the comparator\.\)

\-\- 
Lukas Mai \<plokinom@&#8203;gmail\.com>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @hvds

This crashes because PL\_op\->op\_next\->op\_next is NULL; I'm not sure if it's correct for it to be so \(I don't see that for the vaguely analagous case of a map block\) \- if that is expected\, the patch below is enough to fix it\.

Hugo
\-\-\- a/pp\_sys\.c
\+\+\+ b/pp\_sys\.c
@&#8203;@&#8203; \-3046\,7 \+3046\,7 @&#8203;@&#8203; S\_ft\_return\_false\(pTHX\_ SV \*ret\) \{
&nbsp;     PUTBACK;
 
&nbsp;     if \(PL\_op\->op\_private & OPpFT\_STACKING\) \{
\-        while \(OP\_IS\_FILETEST\(next\->op\_type\)
\+        while \(next && OP\_IS\_FILETEST\(next\->op\_type\)
&nbsp;                && next\->op\_private & OPpFT\_STACKED\)
&nbsp;             next = next\->op\_next;
&nbsp;     \}

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Hugo's patch is correct\.  \(The sort comparator ends with a null op\_next\.
sort's op structure is surprisingly different from map's\.\)  Applied\,
with test\, as commit 1af9149031d9f5d2d43b6df59b628a0f2c1041f6\.

\-zefram

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release yesterday of Perl 5\.28\.0\, this and 185 other issues have been
resolved\.

Perl 5\.28\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.28.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
