### ISSUE TITLE
null ptr deref, segfault Perl_mess_sv (util.c:1534)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15637]
Migrated from [rt.perl.org#129770](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129770) (status was 'resolved')

Searchable as RT129770$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered in Perl v5\.25\.6 \(v5\.25\.5\-42\-g850e14d\)\.

\./perl \-e '0\,$^=0==0\,0==0\,$0=S$^$^D=S'
Scalar found where operator expected at \-e line 1\, near "$^$^D"
&nbsp;        \(Missing operator before $^D?\)
allocating op at 61500000fc48\, slab 61500000fa80 at \(eval 1\) line 1\.
allocating op at 61500000fc08\, slab 61500000fa80 at \(eval 1\) line 1\.
allocating op at 61500000fba8\, slab 61500000fa80 at \(eval 1\) line 1\.
allocating op at 61500000fb60\, slab 61500000fa80 at \(eval 1\) line 1\.
allocating op at 61500000fb20\, slab 61500000fa80 at \(eval 1\) line 1\.
free op at 61500000fb20\, recorded in slab 61500000fa80 at \(eval 1\) line 1\.
ASAN&#8203;:SIGSEGV
=================================================================
==10990==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000021
\(pc 0x000000800b1f bp 0x7ffe86a4ba70 sp 0x7ffe86a4b9c0 T0\)
&nbsp;    \#0 0x800b1e in Perl\_mess\_sv /root/perl/util\.c&#8203;:1534&#8203;:6
&nbsp;    \#1 0x80011b in Perl\_vmess /root/perl/util\.c&#8203;:1587&#8203;:12
&nbsp;    \#2 0x80011b in Perl\_mess /root/perl/util\.c&#8203;:1417
&nbsp;    \#3 0x4e0385 in Perl\_Slab\_Free /root/perl/op\.c&#8203;:442&#8203;:5
&nbsp;    \#4 0x4e20cd in Perl\_op\_free /root/perl/op\.c&#8203;:855&#8203;:9
&nbsp;    \#5 0x4e1d15 in Perl\_op\_free /root/perl/op\.c&#8203;:837&#8203;:21
&nbsp;    \#6 0xa2b5ef in Perl\_leave\_scope /root/perl/scope\.c&#8203;:1109&#8203;:6
&nbsp;    \#7 0xa5e405 in S\_pop\_eval\_context\_maybe\_croak /root/perl/pp\_ctl\.c&#8203;:1605&#8203;:5
&nbsp;    \#8 0xa5dac4 in Perl\_die\_unwind /root/perl/pp\_ctl\.c&#8203;:1733&#8203;:13
&nbsp;    \#9 0x8027af in Perl\_vcroak /root/perl/util\.c&#8203;:1817&#8203;:5
&nbsp;    \#10 0x80269c in Perl\_die /root/perl/util\.c&#8203;:1748&#8203;:5
&nbsp;    \#11 0xa7e172 in S\_require\_file /root/perl/pp\_ctl\.c&#8203;:4062&#8203;:7
&nbsp;    \#12 0xa7e172 in Perl\_pp\_require /root/perl/pp\_ctl\.c&#8203;:4138
&nbsp;    \#13 0x7f4473 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2239&#8203;:23
&nbsp;    \#14 0x5a7dd8 in Perl\_eval\_sv /root/perl/perl\.c&#8203;:2968&#8203;:2
&nbsp;    \#15 0x5aa188 in Perl\_require\_pv /root/perl/perl\.c&#8203;:3071&#8203;:5
&nbsp;    \#16 0x5c1aa6 in Perl\_gv\_fetchmethod\_pvn\_flags /root/perl/gv\.c&#8203;:1103&#8203;:7
&nbsp;    \#17 0x5c09d6 in Perl\_gv\_fetchmethod\_sv\_flags /root/perl/gv\.c&#8203;:996&#8203;:12
&nbsp;    \#18 0x8e5b29 in Perl\_pp\_method\_named /root/perl/pp\_hot\.c&#8203;:4298&#8203;:10
&nbsp;    \#19 0x7f4473 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2239&#8203;:23
&nbsp;    \#20 0x5a11d6 in S\_run\_body /root/perl/perl\.c&#8203;:2526&#8203;:2
&nbsp;    \#21 0x5a11d6 in perl\_run /root/perl/perl\.c&#8203;:2449
&nbsp;    \#22 0x4de5fd in main /root/perl/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#23 0x7f4346b0ab44 in \_\_libc\_start\_main
/build/glibc\-daoqzt/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#24 0x4de26c in \_start \(/root/perl/perl\+0x4de26c\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /root/perl/util\.c&#8203;:1534 Perl\_mess\_sv
==10990==ABORTING

**Comment by p5pRT** [comment]
### From @geeknik

v5\.25\.6 \(v5\.25\.5\-76\-g91dca83\)

valgrind \-q perl \-e 'k$~$^D=$^'
Scalar found where operator expected at \-e line 1\, near "$~$^D"
&nbsp;        \(Missing operator before $^D?\)
invalid option \-DO\, use \-D'' to see choices
invalid option \-D\_\, use \-D'' to see choices
invalid option \-DO\, use \-D'' to see choices
\#\#\# 1&#8203;:LEX\_NORMAL/XSTATE "require q"
\#\#\# \<== REQUIRE

\#\#\# 1&#8203;:LEX\_NORMAL/XTERM "q"
allocating op at 5f85298\, slab 5f850d0 at \(eval 1\) line 1\.
\#\#\# \<== THING\(opval=op\_const\) PV\("IO/File\.pm"\\0\)

\#\#\# 1&#8203;:LEX\_NORMAL/XOPERATOR "\\n;"
\#\#\# \<== ';'

allocating op at 5f85258\, slab 5f850d0 at \(eval 1\) line 1\.
allocating op at 5f851f8\, slab 5f850d0 at \(eval 1\) line 1\.
allocating op at 5f851b0\, slab 5f850d0 at \(eval 1\) line 1\.
\#\#\# 1&#8203;:LEX\_NORMAL/XSTATE ""
\#\#\# Tokener got EOF
\#\#\# \<== EOF

allocating op at 5f85170\, slab 5f850d0 at \(eval 1\) line 1\.
free op at 5f85170\, recorded in slab 5f850d0 at \(eval 1\) line 1\.
==30738== Invalid read of size 1
==30738==    at 0x4DA2DA&#8203;: Perl\_mess\_sv \(util\.c&#8203;:1534\)
==30738==    by 0x4DA98D&#8203;: Perl\_mess \(util\.c&#8203;:1417\)
==30738==    by 0x424C59&#8203;: Perl\_Slab\_Free \(op\.c&#8203;:442\)
==30738==    by 0x425785&#8203;: Perl\_op\_free \(op\.c&#8203;:855\)
==30738==    by 0x4258BB&#8203;: Perl\_op\_free \(op\.c&#8203;:837\)
==30738==    by 0x568070&#8203;: Perl\_leave\_scope \(scope\.c&#8203;:1109\)
==30738==    by 0x56ADA4&#8203;: S\_pop\_eval\_context\_maybe\_croak \(pp\_ctl\.c&#8203;:1593\)
==30738==    by 0x579A15&#8203;: Perl\_die\_unwind \(pp\_ctl\.c&#8203;:1721\)
==30738==    by 0x4D9297&#8203;: Perl\_vcroak \(util\.c&#8203;:1817\)
==30738==    by 0x4D93C8&#8203;: Perl\_die \(util\.c&#8203;:1748\)
==30738==    by 0x580DB6&#8203;: S\_require\_file \(pp\_ctl\.c&#8203;:4050\)
==30738==    by 0x580DB6&#8203;: Perl\_pp\_require \(pp\_ctl\.c&#8203;:4126\)
==30738==    by 0x4D7131&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2246\)
==30738==  Address 0x21 is not stack'd\, malloc'd or \(recently\) free'd
==30738==
==30738==
==30738== Process terminating with default action of signal 11 \(SIGSEGV\)
==30738==  Access not within mapped region at address 0x21
==30738==    at 0x4DA2DA&#8203;: Perl\_mess\_sv \(util\.c&#8203;:1534\)
==30738==    by 0x4DA98D&#8203;: Perl\_mess \(util\.c&#8203;:1417\)
==30738==    by 0x424C59&#8203;: Perl\_Slab\_Free \(op\.c&#8203;:442\)
==30738==    by 0x425785&#8203;: Perl\_op\_free \(op\.c&#8203;:855\)
==30738==    by 0x4258BB&#8203;: Perl\_op\_free \(op\.c&#8203;:837\)
==30738==    by 0x568070&#8203;: Perl\_leave\_scope \(scope\.c&#8203;:1109\)
==30738==    by 0x56ADA4&#8203;: S\_pop\_eval\_context\_maybe\_croak \(pp\_ctl\.c&#8203;:1593\)
==30738==    by 0x579A15&#8203;: Perl\_die\_unwind \(pp\_ctl\.c&#8203;:1721\)
==30738==    by 0x4D9297&#8203;: Perl\_vcroak \(util\.c&#8203;:1817\)
==30738==    by 0x4D93C8&#8203;: Perl\_die \(util\.c&#8203;:1748\)
==30738==    by 0x580DB6&#8203;: S\_require\_file \(pp\_ctl\.c&#8203;:4050\)
==30738==    by 0x580DB6&#8203;: Perl\_pp\_require \(pp\_ctl\.c&#8203;:4126\)
==30738==    by 0x4D7131&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2246\)
==30738==  If you believe this happened as a result of a stack
==30738==  overflow in your program's main thread \(unlikely but
==30738==  possible\)\, you can try to increase the size of the
==30738==  main thread stack using the \-\-main\-stacksize= flag\.
==30738==  The main thread stack size used in this run was 8388608\.
Segmentation fault

**Comment by p5pRT** [comment]
### From @hvds

On Wed\, 12 Oct 2016 15&#8203;:46&#8203;:18 \-0700\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> v5\.25\.6 \(v5\.25\.5\-76\-g91dca83\)
> 
> valgrind \-q perl \-e 'k$~$^D=$^'

The trigger here is enabling \-DS; we end up attempting to report the freeing of an op when PL\_curcop == NULL\. I believe that's a legitimate situation\, so I propose the patch below to cater for PL\_curcop==NULL in mess\_sv\(\)\.

With that in place\, we see&#8203;:
% \./miniperl \-DS \-e 'k $~' 2>&1 | perl \-ne 'print if /EXECUTING/\.\.\./locate/'
EXECUTING\.\.\.

allocating op at 177e9d8\, slab 177e810 at \(eval 1\) line 1\.
allocating op at 177e998\, slab 177e810 at \(eval 1\) line 1\.
allocating op at 177e938\, slab 177e810 at \(eval 1\) line 1\.
allocating op at 177e8f0\, slab 177e810 at \(eval 1\) line 1\.
allocating op at 177e8b0\, slab 177e810 at \(eval 1\) line 1\.
free op at 177e8b0\, recorded in slab 177e810 at \(eval 1\) line 1\.
free op at 177e938\, recorded in slab 177e810\.
free op at 177e8f0\, recorded in slab 177e810\.
free op at 177e9d8\, recorded in slab 177e810\.
free op at 177e998\, recorded in slab 177e810\.
freeing slab 177e810\.
Can't locate object method "k" via package "IO&#8203;::File" at \-e line 1\.
% 
\.\. which seems more useful than a SEGV\.

Hugo

commit db4872386066192185409657dcd15f5c114dae9f
Author&#8203;: Hugo van der Sanden \<hv@&#8203;crypt\.org>
Date&#8203;:   Tue Dec 6 12&#8203;:28&#8203;:19 2016 \+0000

&nbsp;    \[perl \#129770\] Allow for PL\_curcop == NULL in mess\_sv\(\)
&nbsp;    
&nbsp;    This avoids coredumps in pathological cases such as&#8203;: perl \-DS \-e 'k $~'

<details><summary>Inline Patch</summary>

```diff
diff --git a/util.c b/util.c
index 02c84c8..0917747 100644
--- a/util.c
+++ b/util.c
@@ -1518,14 +1518,15 @@ Perl_mess_sv(pTHX_ SV *basemsg, bool consume)
         * from the sibling of PL_curcop.
         */
 
-       const COP *cop =
-           closest_cop(PL_curcop, OpSIBLING(PL_curcop), PL_op, FALSE);
+       const COP *cop = PL_curcop
+            ? closest_cop(PL_curcop, OpSIBLING(PL_curcop), PL_op, FALSE)
+            : NULL;
        if (!cop)
            cop = PL_curcop;
-
-       if (CopLINE(cop))
+       if (cop && CopLINE(cop))
            Perl_sv_catpvf(aTHX_ sv, " at %s line %" IVdf,
-           OutCopFILE(cop), (IV)CopLINE(cop));
+                   OutCopFILE(cop), (IV)CopLINE(cop));
+
        /* Seems that GvIO() can be untrustworthy during global destruction. */
        if (GvIO(PL_last_in_gv) && (SvTYPE(GvIOp(PL_last_in_gv)) == SVt_PVIO)
                && IoLINES(GvIOp(PL_last_in_gv)))
```
</details>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @hvds

I should clarify that I proposed rather than applied this patch only because mess\_sv\(\) seems quite a critical function\, so I'd like a second opinion on the sanity of this change\.

Hugo

On Tue\, 06 Dec 2016 04&#8203;:59&#8203;:14 \-0800\, hv wrote&#8203;:
> On Wed\, 12 Oct 2016 15&#8203;:46&#8203;:18 \-0700\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> > v5\.25\.6 \(v5\.25\.5\-76\-g91dca83\)
> >
> > valgrind \-q perl \-e 'k$~$^D=$^'
> 
> The trigger here is enabling \-DS; we end up attempting to report the
> freeing of an op when PL\_curcop == NULL\. I believe that's a legitimate
> situation\, so I propose the patch below to cater for PL\_curcop==NULL
> in mess\_sv\(\)\.
> 
> With that in place\, we see&#8203;:
> % \./miniperl \-DS \-e 'k $~' 2>&1 | perl \-ne 'print if
> /EXECUTING/\.\.\./locate/'
> EXECUTING\.\.\.
> 
> allocating op at 177e9d8\, slab 177e810 at \(eval 1\) line 1\.
> allocating op at 177e998\, slab 177e810 at \(eval 1\) line 1\.
> allocating op at 177e938\, slab 177e810 at \(eval 1\) line 1\.
> allocating op at 177e8f0\, slab 177e810 at \(eval 1\) line 1\.
> allocating op at 177e8b0\, slab 177e810 at \(eval 1\) line 1\.
> free op at 177e8b0\, recorded in slab 177e810 at \(eval 1\) line 1\.
> free op at 177e938\, recorded in slab 177e810\.
> free op at 177e8f0\, recorded in slab 177e810\.
> free op at 177e9d8\, recorded in slab 177e810\.
> free op at 177e998\, recorded in slab 177e810\.
> freeing slab 177e810\.
> Can't locate object method "k" via package "IO&#8203;::File" at \-e line 1\.
>  %
> \.\. which seems more useful than a SEGV\.
> 
> Hugo
> 
> commit db4872386066192185409657dcd15f5c114dae9f
> Author&#8203;: Hugo van der Sanden \<hv@&#8203;crypt\.org>
> Date&#8203;:   Tue Dec 6 12&#8203;:28&#8203;:19 2016 \+0000
> 
> \[perl \#129770\] Allow for PL\_curcop == NULL in mess\_sv\(\)
> 
> This avoids coredumps in pathological cases such as&#8203;: perl \-DS \-e 'k
> $~'
> 
> diff \-\-git a/util\.c b/util\.c
> index 02c84c8\.\.0917747 100644
> \-\-\- a/util\.c
> \+\+\+ b/util\.c
> @&#8203;@&#8203; \-1518\,14 \+1518\,15 @&#8203;@&#8203; Perl\_mess\_sv\(pTHX\_ SV \*basemsg\, bool consume\)
>          \* from the sibling of PL\_curcop\.
>          \*/
> 
> \-       const COP \*cop =
> \-           closest\_cop\(PL\_curcop\, OpSIBLING\(PL\_curcop\)\, PL\_op\,
> FALSE\);
> \+       const COP \*cop = PL\_curcop
> \+            ? closest\_cop\(PL\_curcop\, OpSIBLING\(PL\_curcop\)\, PL\_op\,
> FALSE\)
> \+            : NULL;
>         if \(\!cop\)
>             cop = PL\_curcop;
> \-
> \-       if \(CopLINE\(cop\)\)
> \+       if \(cop && CopLINE\(cop\)\)
>             Perl\_sv\_catpvf\(aTHX\_ sv\, " at %s line %" IVdf\,
> \-           OutCopFILE\(cop\)\, \(IV\)CopLINE\(cop\)\);
> \+                   OutCopFILE\(cop\)\, \(IV\)CopLINE\(cop\)\);
> \+
>         /\* Seems that GvIO\(\) can be untrustworthy during global
> destruction\. \*/
>         if \(GvIO\(PL\_last\_in\_gv\) && \(SvTYPE\(GvIOp\(PL\_last\_in\_gv\)\) ==
> SVt\_PVIO\)
>                 && IoLINES\(GvIOp\(PL\_last\_in\_gv\)\)\)

**Comment by p5pRT** [comment]
### From @hvds

On Mon\, 12 Dec 2016 08&#8203;:42&#8203;:03 \-0800\, hv wrote&#8203;:
> I should clarify that I proposed rather than applied this patch only
> because mess\_sv\(\) seems quite a critical function\, so I'd like a
> second opinion on the sanity of this change\.

I guess Dave never saw this\, since he has just committed a functionally identical change in f4c6177465 for \[perl \#130621\]\.

Marking as fixed pending release\.

Hugo

**Comment by p5pRT** [comment]
@hvds - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Jan 23\, 2017 at 11&#8203;:19&#8203;:26AM \-0800\, Hugo van der Sanden via RT wrote&#8203;:
> On Mon\, 12 Dec 2016 08&#8203;:42&#8203;:03 \-0800\, hv wrote&#8203;:
> > I should clarify that I proposed rather than applied this patch only
> > because mess\_sv\(\) seems quite a critical function\, so I'd like a
> > second opinion on the sanity of this change\.
> 
> I guess Dave never saw this\, since he has just committed a functionally
> identical change in f4c6177465 for \[perl \#130621\]\.

Oh yeah\. Sorry\!

\-\- 
In my day\, we used to edit the inodes by hand\.  With magnets\.

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
