### ISSUE TITLE
Assertion Failure: void S_mro_gather_and_rename (mro_core.c:1059)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15654]
Migrated from [rt.perl.org#129868](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129868) (status was 'open')

Searchable as RT129868$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered in Perl v5\.25\.6 \(v5\.25\.5\-76\-g91dca83\) with AFL\+ASAN\.

perl&#8203;: mro\_core\.c&#8203;:1059&#8203;: void S\_mro\_gather\_and\_rename\(HV \*const\, HV \*const\,
HV \*\, HV \*\, SV \*\)&#8203;: Assertion \`\!oldstash || \(\(\(\(oldstash\)\->sv\_flags &
0x02000000\) && \(\(struct xpvhv\_aux\*\)&\(\(\(oldstash\)\->sv\_u\.svu\_hash\)\[\(\(XPVHV\*\)
\(oldstash\)\->sv\_any\)\->xhv\_max\+1\]\)\)\->xhv\_name\_u\.xhvnameu\_name && \(\(struct
xpvhv\_aux\*\)&\(\(\(oldstash\)\->sv\_u\.svu\_hash\)\[\(\(XPVHV\*\)
\(oldstash\)\->sv\_any\)\->xhv\_max\+1\]\)\)\->xhv\_name\_count \!= \-1\) ? \(\( \(\(struct
xpvhv\_aux\*\)&\(\(\(oldstash\)\->sv\_u\.svu\_hash\)\[\(\(XPVHV\*\)
\(oldstash\)\->sv\_any\)\->xhv\_max\+1\]\)\)\->xhv\_name\_count > 0 ? \(\(struct
xpvhv\_aux\*\)&\(\(\(oldstash\)\->sv\_u\.svu\_hash\)\[\(\(XPVHV\*\)
\(oldstash\)\->sv\_any\)\->xhv\_max\+1\]\)\)\->xhv\_name\_u\.xhvnameu\_names\[0\] : \(\(struct
xpvhv\_aux\*\)&\(\(\(oldstash\)\->sv\_u\.svu\_hash\)\[\(\(XPVHV\*\)
\(oldstash\)\->sv\_any\)\->xhv\_max\+1\]\)\)\->xhv\_name\_count \< \-1 ? \(\(struct
xpvhv\_aux\*\)&\(\(\(oldstash\)\->sv\_u\.svu\_hash\)\[\(\(XPVHV\*\)
\(oldstash\)\->sv\_any\)\->xhv\_max\+1\]\)\)\->xhv\_name\_u\.xhvnameu\_names\[1\] : \(\(struct
xpvhv\_aux\*\)&\(\(\(oldstash\)\->sv\_u\.svu\_hash\)\[\(\(XPVHV\*\)
\(oldstash\)\->sv\_any\)\->xhv\_max\+1\]\)\)\->xhv\_name\_count == \-1 ? \(\(void\*\)0\) :
\(\(struct xpvhv\_aux\*\)&\(\(\(oldstash\)\->sv\_u\.svu\_hash\)\[\(\(XPVHV\*\)
\(oldstash\)\->sv\_any\)\->xhv\_max\+1\]\)\)\->xhv\_name\_u\.xhvnameu\_name \)\)\->hek\_key :
\(\(void\*\)0\)\)' failed\.
Aborted

With Valgrind and a non\-ASAN Perl v5\.25\.6 \(v5\.25\.5\-76\-g91dca83\) we get a
segfault&#8203;:

==10851== Invalid read of size 8
==10851==    at 0x4EE82C&#8203;: S\_mro\_gather\_and\_rename \(mro\_core\.c&#8203;:930\)
==10851==    by 0x4EF08C&#8203;: S\_mro\_gather\_and\_rename \(mro\_core\.c&#8203;:1186\)
==10851==    by 0x4F0B7D&#8203;: Perl\_mro\_package\_moved \(mro\_core\.c&#8203;:851\)
==10851==    by 0x52EDB1&#8203;: S\_glob\_assign\_glob \(sv\.c&#8203;:3981\)
==10851==    by 0x521F77&#8203;: Perl\_sv\_setsv\_flags \(sv\.c&#8203;:4462\)
==10851==    by 0x5001B5&#8203;: Perl\_pp\_sassign \(pp\_hot\.c&#8203;:226\)
==10851==    by 0x4D7131&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2246\)
==10851==    by 0x453146&#8203;: S\_run\_body \(perl\.c&#8203;:2526\)
==10851==    by 0x453146&#8203;: perl\_run \(perl\.c&#8203;:2449\)
==10851==    by 0x421944&#8203;: main \(perlmain\.c&#8203;:123\)
==10851==  Address 0x5f82b10 is 32 bytes before a block of size 16 in arena
"client"
==10851==
==10851== Invalid read of size 8
==10851==    at 0x4EE844&#8203;: S\_mro\_gather\_and\_rename \(mro\_core\.c&#8203;:932\)
==10851==    by 0x4EF08C&#8203;: S\_mro\_gather\_and\_rename \(mro\_core\.c&#8203;:1186\)
==10851==    by 0x4F0B7D&#8203;: Perl\_mro\_package\_moved \(mro\_core\.c&#8203;:851\)
==10851==    by 0x52EDB1&#8203;: S\_glob\_assign\_glob \(sv\.c&#8203;:3981\)
==10851==    by 0x521F77&#8203;: Perl\_sv\_setsv\_flags \(sv\.c&#8203;:4462\)
==10851==    by 0x5001B5&#8203;: Perl\_pp\_sassign \(pp\_hot\.c&#8203;:226\)
==10851==    by 0x4D7131&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2246\)
==10851==    by 0x453146&#8203;: S\_run\_body \(perl\.c&#8203;:2526\)
==10851==    by 0x453146&#8203;: perl\_run \(perl\.c&#8203;:2449\)
==10851==    by 0x421944&#8203;: main \(perlmain\.c&#8203;:123\)
==10851==  Address 0x78 is not stack'd\, malloc'd or \(recently\) free'd
==10851==
==10851==
==10851== Process terminating with default action of signal 11 \(SIGSEGV\)
==10851==  Access not within mapped region at address 0x78
==10851==    at 0x4EE844&#8203;: S\_mro\_gather\_and\_rename \(mro\_core\.c&#8203;:932\)
==10851==    by 0x4EF08C&#8203;: S\_mro\_gather\_and\_rename \(mro\_core\.c&#8203;:1186\)
==10851==    by 0x4F0B7D&#8203;: Perl\_mro\_package\_moved \(mro\_core\.c&#8203;:851\)
==10851==    by 0x52EDB1&#8203;: S\_glob\_assign\_glob \(sv\.c&#8203;:3981\)
==10851==    by 0x521F77&#8203;: Perl\_sv\_setsv\_flags \(sv\.c&#8203;:4462\)
==10851==    by 0x5001B5&#8203;: Perl\_pp\_sassign \(pp\_hot\.c&#8203;:226\)
==10851==    by 0x4D7131&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2246\)
==10851==    by 0x453146&#8203;: S\_run\_body \(perl\.c&#8203;:2526\)
==10851==    by 0x453146&#8203;: perl\_run \(perl\.c&#8203;:2449\)
==10851==    by 0x421944&#8203;: main \(perlmain\.c&#8203;:123\)
==10851==  If you believe this happened as a result of a stack
==10851==  overflow in your program's main thread \(unlikely but
==10851==  possible\)\, you can try to increase the size of the
==10851==  main thread stack using the \-\-main\-stacksize= flag\.
==10851==  The main thread stack size used in this run was 8388608\.
Segmentation fault

**Comment by p5pRT** [comment]
### From @geeknik

[test120.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1431296/773765/test120.gz)

**Comment by p5pRT** [comment]
### From @hvds

Reduces to&#8203;:

% \./miniperl \-e '%&#8203;: = \*&#8203;: = \*&#8203;::&#8203;::&#8203;:: = \*x; \*&#8203;::&#8203;:: = \*&#8203;::'
miniperl&#8203;: mro\_core\.c&#8203;:1059&#8203;: S\_mro\_gather\_and\_rename&#8203;: Assertion \`\!oldstash || \(\(\(\(oldstash\)\->sv\_flags & 0x02000000\) && \(\(struct xpvhv\_aux\*\)&\(\(\(oldstash\)\->sv\_u\.svu\_hash\)\[\(\(XPVHV\*\) \(oldstash\)\->sv\_any\)\->xhv\_max\+1\]\)\)\->xhv\_name\_u\.xhvnameu\_name && \(\(struct xpvhv\_aux\*\)&\(\(\(oldstash\)\->sv\_u\.svu\_hash\)\[\(\(XPVHV\*\) \(oldstash\)\->sv\_any\)\->xhv\_max\+1\]\)\)\->xhv\_name\_count \!= \-1\) ? \(\( \(\(struct xpvhv\_aux\*\)&\(\(\(oldstash\)\->sv\_u\.svu\_hash\)\[\(\(XPVHV\*\) \(oldstash\)\->sv\_any\)\->xhv\_max\+1\]\)\)\->xhv\_name\_count > 0 ? \(\(struct xpvhv\_aux\*\)&\(\(\(oldstash\)\->sv\_u\.svu\_hash\)\[\(\(XPVHV\*\) \(oldstash\)\->sv\_any\)\->xhv\_max\+1\]\)\)\->xhv\_name\_u\.xhvnameu\_names\[0\] : \(\(struct xpvhv\_aux\*\)&\(\(\(oldstash\)\->sv\_u\.svu\_hash\)\[\(\(XPVHV\*\) \(oldstash\)\->sv\_any\)\->xhv\_max\+1\]\)\)\->xhv\_name\_count \< \-1 ? \(\(struct xpvhv\_aux\*\)&\(\(\(oldstash\)\->sv\_u\.svu\_hash\)\[\(\(XPVHV\*\) \(oldstash\)\->sv\_any\)\->xhv\_max\+1\]\)\)\->xhv\_name\_u\.xhvnameu\_names\[1\] : \(\(struct xpvhv\_aux\*\)&\(\(\(oldstash\)\->sv\_u\.svu\_hash\)\[\(\(XPVHV\*\) \(oldstash\)\->sv\_any\)\->xhv\_max\+1\]\)\)\->xhv\_name\_count == \-1 ? \(\(void \*\)0\) : \(\(struct xpvhv\_aux\*\)&\(\(\(oldstash\)\->sv\_u\.svu\_hash\)\[\(\(XPVHV\*\) \(oldstash\)\->sv\_any\)\->xhv\_max\+1\]\)\)\->xhv\_name\_u\.xhvnameu\_name \)\)\->hek\_key : \(\(void \*\)0\)\)' failed\.
Aborted \(core dumped\)
% 

Using a simpler glob than \*&#8203;: gives a different segv\, still in S\_mro\_gather\_and\_rename&#8203;:
% \./miniperl \-e '%y = \*y = \*&#8203;::&#8203;::&#8203;:: = \*x; \*&#8203;::&#8203;:: = \*&#8203;::'
Segmentation fault \(core dumped\)
% gdb \./miniperl core
\(gdb\) where
\#0  0x000000000056640b in S\_mro\_gather\_and\_rename \(stashes=0x1340178\, 
&nbsp;    seen\_stashes=0x13402e0\, stash=0x133fff8\, oldstash=0x13541e8\, 
&nbsp;    namesv=0x13536d8\) at mro\_core\.c&#8203;:932
\#1  0x0000000000568092 in S\_mro\_gather\_and\_rename \(stashes=0x1340178\, 
&nbsp;    seen\_stashes=0x13402e0\, stash=0x133fff8\, oldstash=0x135f820\, 
&nbsp;    namesv=0x135f850\) at mro\_core\.c&#8203;:1186
\#2  0x0000000000565ded in Perl\_mro\_package\_moved \(stash=0x133fff8\, 
&nbsp;    oldstash=0x135f820\, gv=0x135f808\, flags=0\) at mro\_core\.c&#8203;:851
\#3  0x00000000005b9795 in S\_glob\_assign\_glob \(dstr=0x135f808\, sstr=0x1340028\, 
&nbsp;    dtype=9\) at sv\.c&#8203;:3977
\#4  0x00000000005bee6d in Perl\_sv\_setsv\_flags \(dstr=0x135f808\, sstr=0x1340028\, 
&nbsp;    flags=1538\) at sv\.c&#8203;:4458
\#5  0x0000000000582cc6 in Perl\_pp\_sassign \(\) at pp\_hot\.c&#8203;:226
\#6  0x00000000005394f4 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2235
\#7  0x0000000000445cb6 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2526
\#8  0x00000000004452a7 in perl\_run \(my\_perl=0x133e010\) at perl\.c&#8203;:2449
\#9  0x000000000071e64a in main \(argc=3\, argv=0x7ffe724ffcb8\, 
&nbsp;    env=0x7ffe724ffcd8\) at miniperlmain\.c&#8203;:129
\(gdb\) 

While I'm sure the primary issue here is the same as all the similar previous ones\, with multiple assignments into the same glob falling foul of the unrefcounted stack\, I'm not sure why we need to refer to \*&#8203;:: in three different ways to trigger this particular case \- that it makes a difference how many colon\-pairs we supply seems like it may point to an additional problem\.

Hugo

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by zb226** [comment]
This still crashes on blead:

```
$ git describe
v5.43.3-250-g25d8e128b2
$ ./perl -Ilib -V::config_args
'-des -Dusedevel -Accflags=-DDEBUGGING';
$ ./perl -e '%: = *: = *:::::: = *x; *:::: = *::'
perl: mro_core.c:1077: S_mro_gather_and_rename: Assertion `!oldstash || HvENAME(oldstash)' failed.
Aborted (core dumped)
$ ./perl ../test120
perl: mro_core.c:1077: S_mro_gather_and_rename: Assertion `!oldstash || HvENAME(oldstash)' failed.
Aborted (core dumped)
```

...and it also does with PERL_RC_STACK - would a TODO test make sense here?

```
$ ./perl -Ilib -V::config_args
'-des -Dusedevel -Accflags=-DDEBUGGING -DPERL_RC_STACK';
$ ./perl ../test120
perl: mro_core.c:1077: S_mro_gather_and_rename: Assertion `!oldstash || HvENAME(oldstash)' failed.
Aborted (core dumped)
$ ./perl -e '%: = *: = *:::::: = *x; *:::: = *::'
perl: mro_core.c:1077: S_mro_gather_and_rename: Assertion `!oldstash || HvENAME(oldstash)' failed.
Aborted (core dumped)
```

**Comment by jkeenan** [comment]
> This still crashes on blead:
> 
> ```
> $ git describe
> v5.43.3-250-g25d8e128b2
> $ ./perl -Ilib -V::config_args
> '-des -Dusedevel -Accflags=-DDEBUGGING';
> $ ./perl -e '%: = *: = *:::::: = *x; *:::: = *::'
> perl: mro_core.c:1077: S_mro_gather_and_rename: Assertion `!oldstash || HvENAME(oldstash)' failed.
> Aborted (core dumped)
> $ ./perl ../test120
> perl: mro_core.c:1077: S_mro_gather_and_rename: Assertion `!oldstash || HvENAME(oldstash)' failed.
> Aborted (core dumped)
> ```
> 
>  would a TODO test make sense here?
> 

Yes, but we'd first have to figure out which file to put the tests in.

I say tests (plural) because we should test both of the segfaults @hvds tested with miniperl 9 years ago.

**Comment by zb226** [comment]
Thanks for replying. Thus far I only knew about `t/run/todo.t`, but grepping over the test sources I see TODO tests in many places. Obviously I don't know where the right place is, maybe somewhere in `t/mro`?

Looking at hvds' second test case, in contrast to back then, it now crashes in the same location:

```
$ ./perl -e '%y = *y = *:::::: = *x; *:::: = *::'
perl: mro_core.c:1077: S_mro_gather_and_rename: Assertion `!oldstash || HvENAME(oldstash)' failed.
Aborted (core dumped)
```

**Comment by jkeenan** [comment]
> 
> Looking at hvds' second test case, in contrast to back then, it now crashes in the same location:
> 
> ```
> $ ./perl -e '%y = *y = *:::::: = *x; *:::: = *::'
> perl: mro_core.c:1077: S_mro_gather_and_rename: Assertion `!oldstash || HvENAME(oldstash)' failed.
> Aborted (core dumped)
> ```

If you have the time an inclination, it would be interesting to see if you could develop a technique for bisecting changes in the way a segfault occurs.

**Comment by zb226** [comment]
@jkeenan A coarse scan with perlbrew revealed the behaviour changed between 5.35.0 and 5.36.0. I wrote a little script that executes hvds' second test case and maps exit code 139/SIGSEGV to 0, so that I could bisect to see when that changed. [53a41f9](https://github.com/Perl/perl5/commit/53a41f9c2c0671d8e97b2d47afa3130fe376f322) turned out to be the first commit which exits with 134/SIGABRT instead. I don't know if it's necessary, but I had done the bisect with `miniperl`, so I verified it behaves the same with `perl`.

```
$ git describe
v5.35.4-92-gcf927cca44
$ ./perl -e '%y = *y = *:::::: = *x; *:::: = *::'
Segmentation fault (core dumped)

(...)

$ git describe
v5.35.4-93-g53a41f9c2c
$ ./perl -e '%y = *y = *:::::: = *x; *:::: = *::'
perl: mro_core.c:1066: S_mro_gather_and_rename: Assertion `!oldstash || HvENAME(oldstash)' failed.
Aborted (core dumped)
$ ./perl -e '%: = *: = *:::::: = *x; *:::: = *::'
perl: mro_core.c:1066: S_mro_gather_and_rename: Assertion `!oldstash || HvENAME(oldstash)' failed.
Aborted (core dumped)
```

**Comment by tonycoz** [comment]
The 53a41f9 change means there's always a physical aux struct, even when there's none logically, which eliminated the segfault.
