### ISSUE TITLE
null ptr deref, segfault in Perl_do_aexec5 (doio.c:1595)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15660]
Migrated from [rt.perl.org#129888](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129888) (status was 'resolved')

Searchable as RT129888$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered with AFL\+ASAN in Perl v5\.25\.6 \(v5\.25\.5\-104\-gaff2be5\)\.

od \-tx1 test274
0000000 7b 24 30 3d 24 53 49 47 7b 5f 5f 57 41 52 4e 5f
0000020 5f 7d 3d 73 75 62 7b 65 78 65 63 7d 3b 24 5e 57
0000040 3d 32 2c 65 78 65 63 24 70 00 30 7d
0000054

Number found where operator expected at test274 line 1\, near "$p0"
&nbsp;        \(Missing operator before 0?\)
ASAN&#8203;:SIGSEGV
=================================================================
==6592==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000000 \(pc
0x000000b30ea7 bp 0x7fffff249420 sp 0x7fffff249280 T0\)
&nbsp;    \#0 0xb30ea6 in Perl\_do\_aexec5 /root/perl/doio\.c&#8203;:1595&#8203;:13
&nbsp;    \#1 0xaf9bbc in Perl\_pp\_exec /root/perl/pp\_sys\.c&#8203;:4515&#8203;:15
&nbsp;    \#2 0x7f44b3 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2246&#8203;:23
&nbsp;    \#3 0x5a12b6 in S\_run\_body /root/perl/perl\.c&#8203;:2526&#8203;:2
&nbsp;    \#4 0x5a12b6 in perl\_run /root/perl/perl\.c&#8203;:2449
&nbsp;    \#5 0x4de60d in main /root/perl/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#6 0x7f7211793b44 in \_\_libc\_start\_main
/build/glibc\-daoqzt/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#7 0x4de27c in \_start \(/root/perl/perl\+0x4de27c\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /root/perl/doio\.c&#8203;:1595 Perl\_do\_aexec5
==6592==ABORTING

Number found where operator expected at test274 line 1\, near "$p0"
&nbsp;        \(Missing operator before 0?\)
==6567== Invalid read of size 8
==6567==    at 0x5A7B17&#8203;: Perl\_do\_aexec5 \(doio\.c&#8203;:1595\)
==6567==    by 0x598CD4&#8203;: Perl\_pp\_exec \(pp\_sys\.c&#8203;:4515\)
==6567==    by 0x4D71A1&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2246\)
==6567==    by 0x453156&#8203;: S\_run\_body \(perl\.c&#8203;:2526\)
==6567==    by 0x453156&#8203;: perl\_run \(perl\.c&#8203;:2449\)
==6567==    by 0x421984&#8203;: main \(perlmain\.c&#8203;:123\)
==6567==  Address 0x0 is not stack'd\, malloc'd or \(recently\) free'd
==6567==
==6567==
==6567== Process terminating with default action of signal 11 \(SIGSEGV\)
==6567==  Access not within mapped region at address 0x0
==6567==    at 0x5A7B17&#8203;: Perl\_do\_aexec5 \(doio\.c&#8203;:1595\)
==6567==    by 0x598CD4&#8203;: Perl\_pp\_exec \(pp\_sys\.c&#8203;:4515\)
==6567==    by 0x4D71A1&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2246\)
==6567==    by 0x453156&#8203;: S\_run\_body \(perl\.c&#8203;:2526\)
==6567==    by 0x453156&#8203;: perl\_run \(perl\.c&#8203;:2449\)
==6567==    by 0x421984&#8203;: main \(perlmain\.c&#8203;:123\)
==6567==  If you believe this happened as a result of a stack
==6567==  overflow in your program's main thread \(unlikely but
==6567==  possible\)\, you can try to increase the size of the
==6567==  main thread stack using the \-\-main\-stacksize= flag\.
==6567==  The main thread stack size used in this run was 8388608\.
Segmentation fault

Number found where operator expected at test274 line 1\, near "$p0"
&nbsp;        \(Missing operator before 0?\)

Program received signal SIGSEGV\, Segmentation fault\.
0x00000000005a7b17 in Perl\_do\_aexec5 \(really=0x939998\, mark=0x919b70\,
mark@&#8203;entry=0x919b60\, sp=sp@&#8203;entry=0x919b68\, fd=fd@&#8203;entry=0\,
do\_report=do\_report@&#8203;entry=0\) at doio\.c&#8203;:1595
1595                PerlProc\_execvp\(PL\_Argv\[0\]\,EXEC\_ARGV\_CAST\(PL\_Argv\)\);
\(gdb\) bt
\#0  0x00000000005a7b17 in Perl\_do\_aexec5 \(really=0x939998\, mark=0x919b70\,
mark@&#8203;entry=0x919b60\, sp=sp@&#8203;entry=0x919b68\, fd=fd@&#8203;entry=0\,
do\_report=do\_report@&#8203;entry=0\) at doio\.c&#8203;:1595
\#1  0x0000000000598cd5 in Perl\_pp\_exec \(\) at pp\_sys\.c&#8203;:4515
\#2  0x00000000004d71a2 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2246
\#3  0x0000000000453157 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2526
\#4  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2449
\#5  0x0000000000421985 in main \(argc=2\, argv=0x7fffffffe6b8\,
env=0x7fffffffe6d0\) at perlmain\.c&#8203;:123
\(gdb\) list
1590                TAINT\_ENV\(\);                /\* testing IFS here is
overkill\, probably \*/
1591            PERL\_FPU\_PRE\_EXEC
1592            if \(really && \*tmps\) \{
1593                PerlProc\_execvp\(tmps\,EXEC\_ARGV\_CAST\(PL\_Argv\)\);
1594            \} else \{
1595                PerlProc\_execvp\(PL\_Argv\[0\]\,EXEC\_ARGV\_CAST\(PL\_Argv\)\);
1596            \}
1597            PERL\_FPU\_POST\_EXEC
1598            S\_exec\_failed\(aTHX\_ \(really ? tmps : PL\_Argv\[0\]\)\, fd\,
do\_report\);
1599        \}
\(gdb\) i r
rax            0x0      0
rbx            0x6193c4 6394820
rcx            0x0      0
rdx            0x7ffff6cf20e0   140737334157536
rsi            0x7fffffffe140   140737488347456
rdi            0x8      8
rbp            0x7fffffffe360   0x7fffffffe360
rsp            0x7fffffffe350   0x7fffffffe350
r8             0x7fffffffe360   140737488348000
r9             0x7fffffffe1e0   140737488347616
r10            0x8      8
r11            0x206    518
r12            0x932d10 9645328
r13            0x939998 9673112
r14            0x932d20 9645344
r15            0x919b70 9542512
rip            0x5a7b17 0x5a7b17 \<Perl\_do\_aexec5\+359>
eflags         0x10246  \[ PF ZF IF RF \]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0

**Comment by p5pRT** [comment]
### From @geeknik

[test274.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1431567/773947/test274.gz)

**Comment by p5pRT** [comment]
### From @hvds

In short&#8203;:

% \./miniperl \-we '$SIG\{\_\_WARN\_\_\} = sub \{ exec \}; exec $p 0;'
Name "main&#8203;::p" used only once&#8203;: possible typo at \-e line 1\.
Segmentation fault \(core dumped\)
% 

Fetching the exec arguments in do\_aexec5\(\) can trigger arbitrary perl code\, which can cause the PL\_Argv array we're building up to get removed before we're done\.

I'm not sure what's the best approach here; here's a couple of possibilities&#8203;:

\# disallow reentrant calls&#8203;: UNLIKELY\(breaks some working code\)
\-\-\- a/doio\.c
\+\+\+ b/doio\.c
@&#8203;@&#8203; \-1574\,6 \+1574\,8 @&#8203;@&#8203; Perl\_do\_aexec5\(pTHX\_ SV \*really\, SV \*\*mark\, SV \*\*sp\,
 \#if defined\(\_\_SYMBIAN32\_\_\) || defined\(\_\_LIBCATAMOUNT\_\_\)
&nbsp;     Perl\_croak\(aTHX\_ "exec? I'm not \*that\* kind of operating system"\);
 \#else
\+    if \(PL\_Argv\)
\+        Perl\_croak\(aTHX\_ "panic&#8203;: do\_aexec5\(\) called reentrantly"\);
&nbsp;     if \(sp > mark\) \{
&nbsp;        const char \*\*a;
&nbsp;        const char \*tmps = NULL;

\# set PL\_Argv as late as possible&#8203;: UNLIKELY\(leaks some memory\)
\-\-\- a/doio\.c
\+\+\+ b/doio\.c
@&#8203;@&#8203; \-1575\,10 \+1575\,11 @&#8203;@&#8203; Perl\_do\_aexec5\(pTHX\_ SV \*really\, SV \*\*mark\, SV \*\*sp\,
&nbsp;     Perl\_croak\(aTHX\_ "exec? I'm not \*that\* kind of operating system"\);
 \#else
&nbsp;     if \(sp > mark\) \{
\+        const char \*\*argv;
&nbsp;        const char \*\*a;
&nbsp;        const char \*tmps = NULL;
\-       Newx\(PL\_Argv\, sp \- mark \+ 1\, const char\*\);
\-       a = PL\_Argv;
\+       Newx\(argv\, sp \- mark \+ 1\, const char\*\);
\+       a = argv;
 
&nbsp;        while \(\+\+mark \<= sp\) \{
&nbsp;            if \(\*mark\)
@&#8203;@&#8203; \-1589\,10 \+1590\,11 @&#8203;@&#8203; Perl\_do\_aexec5\(pTHX\_ SV \*really\, SV \*\*mark\, SV \*\*sp\,
&nbsp;        \*a = NULL;
&nbsp;        if \(really\)
&nbsp;            tmps = SvPV\_nolen\_const\(really\);
\-       if \(\(\!really && \*PL\_Argv\[0\] \!= '/'\) ||
\+       if \(\(\!really && \*argv\[0\] \!= '/'\) ||
&nbsp;            \(really && \*tmps \!= '/'\)\)           /\* will execvp use PATH? \*/
&nbsp;            TAINT\_ENV\(\);                /\* testing IFS here is overkill\, probably \*/
&nbsp;        PERL\_FPU\_PRE\_EXEC
\+        PL\_Argv = argv;
&nbsp;        if \(really && \*tmps\) \{
&nbsp;             PerlProc\_execvp\(tmps\,EXEC\_ARGV\_CAST\(PL\_Argv\)\);
&nbsp;        \} else \{

Hugo

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From zefram@fysh.org

The globals that are causing this problem don't need to be global at all\.
They're only managing the freeing of that memory\, and I reckon we can do
better by using the scope stack to arrange freeing\.  I've implemented this
on the branch zefram/smoke\-me/exec\_args\.  It fixes the original test case
on Unix\.  However\, there's a bunch of platform\-specific code in this area\,
so this needs broader testing\.  It also needs broad testing to make sure
the scope stack arrangement actually achieves correct memory management\,
for example around vfork and Windows's simulated fork\.

\-zefram

**Comment by p5pRT** [comment]
### From @jkeenan

On 12/06/2017 04&#8203;:37 PM\, Zefram wrote&#8203;:
> The globals that are causing this problem don't need to be global at all\.
> They're only managing the freeing of that memory\, and I reckon we can do
> better by using the scope stack to arrange freeing\.  I've implemented this
> on the branch zefram/smoke\-me/exec\_args\. 

For whatever benefit there might be of creating a branch for 
smoke\-testing\, you probably should rename it&#8203;:

smoke\-me/zefram/exec\_args

That way \(a\) in the rare case of someone \(i\.e\.\, TonyC\) who has set up 
automated smoke\-testing set up for non\-blead branches\, it gets 
recognized and run; and \(b\) its results get tabulated at 
perl\.develop\-help\.com \(e\.g\.\, 
http&#8203;://perl\.develop\-help\.com/?b=smoke\-me%2Fkhw\-locale\)\.

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From zefram@fysh.org

James E Keenan wrote&#8203;:
>For whatever benefit there might be of creating a branch for smoke\-testing\,
>you probably should rename it&#8203;:

Really?  I had got the impression that the "smoke\-me" segment could be
anywhere in the name\.  I see that perlgit\(1\) doesn't actually say what the
rules are\.  Could someone authoritative please give us a regexp defining
what constitutes a smoke\-me branch name?  And put it in perlgit\(1\)\.

\-zefram

**Comment by p5pRT** [comment]
### From @jkeenan

On 12/07/2017 02&#8203;:52 PM\, Zefram wrote&#8203;:
> James E Keenan wrote&#8203;:
>> For whatever benefit there might be of creating a branch for smoke\-testing\,
>> you probably should rename it&#8203;:
> 
> Really?  I had got the impression that the "smoke\-me" segment could be
> anywhere in the name\.  I see that perlgit\(1\) doesn't actually say what the
> rules are\.  Could someone authoritative please give us a regexp defining
> what constitutes a smoke\-me branch name?  And put it in perlgit\(1\)\.
> 

Zefram&#8203;:

I've had a commit bit since 2012\.  How many more years do I have to 
serve before you consider me "authoritative"?

For what it's worth\, all three of the examples of a smoke\-me branch 
presented in perlgit follow the "smoke\-me/\<committer>/\<branch\_name>" 
convention\.

In addition\, if you go to http&#8203;://perl\.develop\-help\.com/\, click on the 
drop\-down that says 'blead'\, then click on "I want an older branch" you 
will see that all the branches with Tony tracks on that site begin with 
'blead'\, 'maint' or 'smoke\-me'\.  The \<committer> part appears to be 
optional\, but 'smoke\-me' always appears first\.

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From zefram@fysh.org

James E Keenan wrote&#8203;:
>I've had a commit bit since 2012\.  How many more years do I have to serve
>before you consider me "authoritative"?

By "authoritative" I meant someone who maintains the smoke\-me automation\,
and so can look at the code and tell us first\-hand what the said
automation actually does\.  It's about the role one plays\, not about
expertise\, seniority\, or other qualities\.

\-zefram

**Comment by p5pRT** [comment]
### From carlos@carlosguevara.com

On Thu\, Dec 7\, 2017 at 11&#8203;:31 PM\, Zefram \<zefram@&#8203;fysh\.org> wrote&#8203;:

> James E Keenan wrote&#8203;:
> >I've had a commit bit since 2012\.  How many more years do I have to serve
> >before you consider me "authoritative"?
>
> By "authoritative" I meant someone who maintains the smoke\-me automation\,
> and so can look at the code and tell us first\-hand what the said
> automation actually does\.  It's about the role one plays\, not about
> expertise\, seniority\, or other qualities\.
>
> \-zefram
>

I use this command on my systems&#8203;:
git for\-each\-ref \-\-count=3 \-\-sort=\-committerdate refs/heads/smoke\-me
\-\-format='%\(refname&#8203;:short\)'

**Comment by p5pRT** [comment]
### From @xsawyerx



On 12/08/2017 05&#8203;:44 AM\, James E Keenan wrote&#8203;:
> On 12/07/2017 02&#8203;:52 PM\, Zefram wrote&#8203;:
>> James E Keenan wrote&#8203;:
>>> For whatever benefit there might be of creating a branch for
>>> smoke\-testing\,
>>> you probably should rename it&#8203;:
>>
>> Really?  I had got the impression that the "smoke\-me" segment could be
>> anywhere in the name\.  I see that perlgit\(1\) doesn't actually say
>> what the
>> rules are\.  Could someone authoritative please give us a regexp defining
>> what constitutes a smoke\-me branch name?  And put it in perlgit\(1\)\.
>>
>
> Zefram&#8203;:
>
> I've had a commit bit since 2012\.  How many more years do I have to
> serve before you consider me "authoritative"?

I think the intention here is for "definitive\," as in "What does the
darn regexp looks like\, so we can know for sure\."

Funny story&#8203;: I asked my brother for his car's code\. His partner gave me
a different code\. He jumped up and said "No\, that's the wrong code\. You
swapped two digits\!" She replied with "This is the number I use every
day\." And it so happens that both of the numbers indeed work\.\[1\]

The regexp could be /^smoke\-me/ or /smoke\-me/\. Either case\, it would be
good to know which it is\. Still\, I support your concern for having
uniformity\, regardless of where you put the "smoke\-me"\.

**Comment by p5pRT** [comment]
### From @craigberry

On Mon\, Dec 11\, 2017 at 6&#8203;:59 AM\, Sawyer X \<xsawyerx@&#8203;gmail\.com> wrote&#8203;:
>
> On 12/08/2017 05&#8203;:44 AM\, James E Keenan wrote&#8203;:
>> On 12/07/2017 02&#8203;:52 PM\, Zefram wrote&#8203;:
>>> I had got the impression that the "smoke\-me" segment could be
>>> anywhere in the name\.  I see that perlgit\(1\) doesn't actually say
>>> what the
>>> rules are\.  Could someone authoritative please give us a regexp defining
>>> what constitutes a smoke\-me branch name?  And put it in perlgit\(1\)\.

> The regexp could be /^smoke\-me/ or /smoke\-me/\. Either case\, it would be
> good to know which it is\. Still\, I support your concern for having
> uniformity\, regardless of where you put the "smoke\-me"\.

As far as I know the automatic selection of what branch or branches to
smoke is external to Test&#8203;::Smoke and the use of "smoke\-me" in the name
is just a convention to be used in whatever fashion the implementor of
a smoke set\-up sees fit\.  It's not even necessarily implemented
exactly the same way in every smoke\-me set\-up \(of which there have
never been more than a couple\, I think\)\.  And of course there are a
number of smokers that only do blead or only blead and maint and don't
do the smoke\-me branches\.  I would be happy to discover that there is
more consistency and ready\-to\-use code for automatic branch selection
than I am aware of\, but this is my impression of where we are now\.

That said\, I've always assumed the convention was that the branch
should start with "smoke\-me" and the one example in perlgit does that\.
Eyeballing the lengthy list of existing branches at
\<https://perl5.git.perl.org/perl.git/heads>&nbsp;  does not turn up any
examples prior to Zefram's that puts the "smoke\-me" anywhere but at
the beginning\.  In the absence of better information\, I'd say we
already have a convention and this is it&#8203;: "smoke\-me" at the beginning\.

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Carlos Guevara wrote&#8203;:
>I use this command on my systems&#8203;:
>git for\-each\-ref \-\-count=3 \-\-sort=\-committerdate refs/heads/smoke\-me

Thanks\, that makes it clear\.  I've renamed my branch to
"smoke\-me/zefram/exec\_args"\, and pushed a patch for perlgit\.pod\.

\-zefram

**Comment by p5pRT** [comment]
### From @xsawyerx



On 12/11/2017 08&#8203;:29 PM\, Craig A\. Berry wrote&#8203;:
> On Mon\, Dec 11\, 2017 at 6&#8203;:59 AM\, Sawyer X \<xsawyerx@&#8203;gmail\.com> wrote&#8203;:
>> On 12/08/2017 05&#8203;:44 AM\, James E Keenan wrote&#8203;:
>>> On 12/07/2017 02&#8203;:52 PM\, Zefram wrote&#8203;:
>>>> I had got the impression that the "smoke\-me" segment could be
>>>> anywhere in the name\.  I see that perlgit\(1\) doesn't actually say
>>>> what the
>>>> rules are\.  Could someone authoritative please give us a regexp defining
>>>> what constitutes a smoke\-me branch name?  And put it in perlgit\(1\)\.
>> The regexp could be /^smoke\-me/ or /smoke\-me/\. Either case\, it would be
>> good to know which it is\. Still\, I support your concern for having
>> uniformity\, regardless of where you put the "smoke\-me"\.
> \[\.\.\.\]
>
> That said\, I've always assumed the convention was that the branch
> should start with "smoke\-me" and the one example in perlgit does that\.
> Eyeballing the lengthy list of existing branches at
> \<https://perl5.git.perl.org/perl.git/heads>&nbsp;  does not turn up any
> examples prior to Zefram's that puts the "smoke\-me" anywhere but at
> the beginning\.  In the absence of better information\, I'd say we
> already have a convention and this is it&#8203;: "smoke\-me" at the beginning\.

Agreed\.

**Comment by p5pRT** [comment]
### From zefram@fysh.org

smoke\-me testing didn't cover as many platforms as I'd hoped\, but at
least didn't show any relevant failures\.  Patch applied to blead as
commit 282fc0b3cc2439f69587d980b62bef7f5d5bdfef\.

\-zefram

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
