### ISSUE TITLE
gv.c:1492: HV *S_gv_stashsvpvn_cached(SV *, const char *, U32, I32): Assertion `PL_valid_types_IVX[((svtype)((_svivx)->sv_flags & 0xff)) & 0xf]' failed

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15663]
Migrated from [rt.perl.org#129893](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129893) (status was 'open')

Searchable as RT129893$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered in Perl v5\.25\.6 \(v5\.25\.5\-106\-g877b982\)\.

od \-tx1 test123
0000000 70 72 69 6e 74 20 6d 61 70 20 63 68 72 24 5f 5b
0000020 30 5d 2d 6f 72 64 44 64 0a 5f 2c 40 5f 3d 5b 30
0000040 5d 2d 6f 72 64 2d 64 24 5f 2c 40 5f 3d 27 32 30
0000060 30 6f 63 54 01 00 67 5a 59 54 a8 78 63 56 5c c2
0000100 a8 60 67 65 c7 63 35 27 3d 7e 6d 3b 28 5c 64 1a
0000120 7c 22 29 3b 67 3b 0a
0000127

\./perl test123
Can't locate object method "ordDd" via package "\_" \(perhaps you forgot to
load "\_"?\) at test123 line 1\.
perl&#8203;: gv\.c&#8203;:1492&#8203;: HV \*S\_gv\_stashsvpvn\_cached\(SV \*\, const char \*\, U32\, I32\)&#8203;:
Assertion \`PL\_valid\_types\_IVX\[\(\(svtype\)\(\(\_svivx\)\->sv\_flags & 0xff\)\) & 0xf\]'
failed\.
Aborted


Running Perl 5\.20\.2\-3\+deb8u6 under Valgrind we get a nice segfault&#8203;:

Can't locate object method "ordDd" via package "\_" \(perhaps you forgot to
load "\_"?\) at test123 line 1\.
==12280== Invalid read of size 8
==12280==    at 0x4E90336&#8203;: Perl\_gv\_fetchmeth\_pvn \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4E90513&#8203;: Perl\_gv\_fetchmeth\_pvn \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4E907C4&#8203;: Perl\_gv\_fetchmeth\_pvn\_autoload \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F0C326&#8203;: ??? \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F0CECF&#8203;: Perl\_sv\_clear \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F0D289&#8203;: Perl\_sv\_free2 \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F0D5CC&#8203;: ??? \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F03DC6&#8203;: ??? \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F0D8E7&#8203;: Perl\_sv\_clean\_objs \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4E8641C&#8203;: perl\_destruct \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x400DE0&#8203;: main \(in /usr/bin/perl\)
==12280==  Address 0x5f3c7b8 is 8 bytes inside a block of size 32 free'd
==12280==    at 0x4C29E90&#8203;: free \(vg\_replace\_malloc\.c&#8203;:473\)
==12280==    by 0x4F0D1A7&#8203;: Perl\_sv\_clear \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F0D289&#8203;: Perl\_sv\_free2 \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F3018F&#8203;: Perl\_free\_tmps \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4E8B750&#8203;: perl\_run \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x400E18&#8203;: main \(in /usr/bin/perl\)
==12280==
==12280== Invalid read of size 4
==12280==    at 0x4E8FFA0&#8203;: Perl\_gv\_stashsv \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4E90346&#8203;: Perl\_gv\_fetchmeth\_pvn \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4E90513&#8203;: Perl\_gv\_fetchmeth\_pvn \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4E907C4&#8203;: Perl\_gv\_fetchmeth\_pvn\_autoload \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F0C326&#8203;: ??? \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F0CECF&#8203;: Perl\_sv\_clear \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F0D289&#8203;: Perl\_sv\_free2 \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F0D5CC&#8203;: ??? \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F03DC6&#8203;: ??? \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F0D8E7&#8203;: Perl\_sv\_clean\_objs \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4E8641C&#8203;: perl\_destruct \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x400DE0&#8203;: main \(in /usr/bin/perl\)
==12280==  Address 0xc is not stack'd\, malloc'd or \(recently\) free'd
==12280==
==12280==
==12280== Process terminating with default action of signal 11 \(SIGSEGV\)
==12280==  Access not within mapped region at address 0xC
==12280==    at 0x4E8FFA0&#8203;: Perl\_gv\_stashsv \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4E90346&#8203;: Perl\_gv\_fetchmeth\_pvn \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4E90513&#8203;: Perl\_gv\_fetchmeth\_pvn \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4E907C4&#8203;: Perl\_gv\_fetchmeth\_pvn\_autoload \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F0C326&#8203;: ??? \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F0CECF&#8203;: Perl\_sv\_clear \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F0D289&#8203;: Perl\_sv\_free2 \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F0D5CC&#8203;: ??? \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F03DC6&#8203;: ??? \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4F0D8E7&#8203;: Perl\_sv\_clean\_objs \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x4E8641C&#8203;: perl\_destruct \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==12280==    by 0x400DE0&#8203;: main \(in /usr/bin/perl\)
==12280==  If you believe this happened as a result of a stack
==12280==  overflow in your program's main thread \(unlikely but
==12280==  possible\)\, you can try to increase the size of the
==12280==  main thread stack using the \-\-main\-stacksize= flag\.
==12280==  The main thread stack size used in this run was 8388608\.
Segmentation fault

**Comment by p5pRT** [comment]
### From @geeknik

[test123.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1431641/773995/test123.gz)

**Comment by p5pRT** [comment]
### From @hvds

Here's a shorter version&#8203;:

% echo 'map xx\->yy\, \(@&#8203;z = 1\)\, \(@&#8203;z = \(\)\)' | \./miniperl
Can't locate object method "yy" via package "xx" \(perhaps you forgot to load "xx"?\) at \- line 1\.
miniperl&#8203;: gv\.c&#8203;:1500&#8203;: S\_gv\_stashsvpvn\_cached&#8203;: Assertion \`PL\_valid\_types\_IVX\[\(\(svtype\)\(\(\_svivx\)\->sv\_flags & 0xff\)\) & 0xf\]' failed\.
Aborted \(core dumped\)
% 

I'm pretty sure this is only a stack refcounting issue\, but here's the backtrace in case anyone is moved to look further&#8203;:

\#3  0x00007ffff72e7c32 in \_\_GI\_\_\_assert\_fail \(
&nbsp;    assertion=0x776ca0 "PL\_valid\_types\_IVX\[\(\(svtype\)\(\(\_svivx\)\->sv\_flags & 0xff\)\) & 0xf\]"\, file=0x76fcda "gv\.c"\, line=1500\, 
&nbsp;    function=0x77cf90 \<\_\_PRETTY\_FUNCTION\_\_\.15678> "S\_gv\_stashsvpvn\_cached"\)
&nbsp;    at assert\.c&#8203;:101
\#4  0x00000000004600ed in S\_gv\_stashsvpvn\_cached \(namesv=0x0\, 
&nbsp;    name=0x775b68 "UNIVERSAL"\, namelen=9\, flags=0\) at gv\.c&#8203;:1500
\#5  0x00000000004603c0 in Perl\_gv\_stashpvn \(name=0x775b68 "UNIVERSAL"\, 
&nbsp;    namelen=9\, flags=0\) at gv\.c&#8203;:1528
\#6  0x0000000000459684 in S\_gv\_fetchmeth\_internal \(stash=0x0\, meth=0x0\, 
&nbsp;    name=0x7e7e73 \<S\_destroy> "DESTROY"\, len=7\, level=1\, flags=0\) at gv\.c&#8203;:711
\#7  0x000000000045b051 in S\_gv\_fetchmeth\_internal \(stash=0xa9f6a8\, meth=0x0\, 
&nbsp;    name=0x7e7e73 \<S\_destroy> "DESTROY"\, len=7\, level=\-1\, flags=0\) at gv\.c&#8203;:832
\#8  0x000000000045b5cc in Perl\_gv\_fetchmeth\_pvn \(stash=0xa9f6a8\, 
&nbsp;    name=0x7e7e73 \<S\_destroy> "DESTROY"\, len=7\, level=\-1\, flags=0\) at gv\.c&#8203;:859
\#9  0x00000000005de80c in S\_curse \(sv=0xa9fa68\, check\_refcnt=true\) at sv\.c&#8203;:6839
\#10 0x00000000005dc30b in Perl\_sv\_clear \(orig\_sv=0xa9fa68\) at sv\.c&#8203;:6497
\#11 0x00000000005df82a in Perl\_sv\_free2 \(sv=0xa9fa68\, rc=1\) at sv\.c&#8203;:6994
\#12 0x00000000005a9548 in S\_SvREFCNT\_dec\_NN \(sv=0xa9fa68\) at inline\.h&#8203;:200
\#13 0x00000000005ab1b5 in do\_clean\_named\_io\_objs \(sv=0xa9fa50\) at sv\.c&#8203;:600
\#14 0x00000000005aa1ad in S\_visit \(f=0x5aadec \<do\_clean\_named\_io\_objs>\, 
&nbsp;    flags=32777\, mask=49407\) at sv\.c&#8203;:476
\#15 0x00000000005ab69b in Perl\_sv\_clean\_objs \(\) at sv\.c&#8203;:632
\#16 0x0000000000443c54 in perl\_destruct \(my\_perl=0xa8a010\) at perl\.c&#8203;:855
\#17 0x000000000072ab51 in main \(argc=3\, argv=0x7fffffffe518\, 
&nbsp;    env=0x7fffffffe538\) at miniperlmain\.c&#8203;:140

Hugo

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Fri\, Nov 11\, 2016 at 06&#8203;:20&#8203;:38AM \-0800\, Hugo van der Sanden via RT wrote&#8203;:
> Here's a shorter version&#8203;:
> 
> % echo 'map xx\->yy\, \(@&#8203;z = 1\)\, \(@&#8203;z = \(\)\)' | \./miniperl
> Can't locate object method "yy" via package "xx" \(perhaps you forgot to load "xx"?\) at \- line 1\.
> miniperl&#8203;: gv\.c&#8203;:1500&#8203;: S\_gv\_stashsvpvn\_cached&#8203;: Assertion \`PL\_valid\_types\_IVX\[\(\(svtype\)\(\(\_svivx\)\->sv\_flags & 0xff\)\) & 0xf\]' failed\.
> Aborted \(core dumped\)
> % 
> 
> I'm pretty sure this is only a stack refcounting issue\, but here's the backtrace in case anyone is moved to look further&#8203;:

It would indeed appear to be\. I've linked this ticket to the
"\[META\] stack not reference counted issues" ticket\.

\-\- 
Never do today what you can put off till tomorrow\.
