### ISSUE TITLE
null ptr deref + segfault in Perl_sv_setpv_bufsize (sv.c:4956)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15740]
Migrated from [rt.perl.org#130224](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130224) (status was 'open')

Searchable as RT130224$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered while fuzzing Perl v5\.25\.7\-26\-g7332835\.

\./perl \-e '$$\.=$A=\*$=0'
ASAN&#8203;:SIGSEGV
=================================================================
==8166==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000000 \(pc
0x0000009394e3 bp 0x0c4200002236 sp 0x7ffc09d74b20 T0\)
&nbsp;    \#0 0x9394e2 in Perl\_sv\_setpv\_bufsize /root/perl/sv\.c&#8203;:4956&#8203;:5
&nbsp;    \#1 0x8a6ab0 in Perl\_pp\_concat /root/perl/pp\_hot\.c&#8203;:292&#8203;:13
&nbsp;    \#2 0x7f63bb in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2260&#8203;:23
&nbsp;    \#3 0x5a06c3 in S\_run\_body /root/perl/perl\.c&#8203;:2526&#8203;:2
&nbsp;    \#4 0x5a06c3 in perl\_run /root/perl/perl\.c&#8203;:2449
&nbsp;    \#5 0x4de6cd in main /root/perl/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#6 0x7f592806bb44 in \_\_libc\_start\_main
/build/glibc\-daoqzt/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#7 0x4de33c in \_start \(/root/perl/perl\+0x4de33c\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /root/perl/sv\.c&#8203;:4956 Perl\_sv\_setpv\_bufsize
==8166==ABORTING

**Comment by p5pRT** [comment]
### From @arc

Brian Carpenter \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> Triggered while fuzzing Perl v5\.25\.7\-26\-g7332835\.
>
> \./perl \-e '$$\.=$A=\*$=0'

This can be reduced to&#8203;: $x \.= \*x = 0

The segfault comes from the SvPVCLEAR\(\) in this block of pp\_concat\(\)&#8203;:

&nbsp;  else \{ /\* $l \.= $r   and   left == TARG \*/
&nbsp;      if \(\!SvOK\(left\)\) \{
&nbsp;          if \(\(left == right                          /\* $l \.= $l \*/
&nbsp;               || \(PL\_op\->op\_private & OPpTARGET\_MY\)\) /\* $l = $l \. $r \*/
&nbsp;              && ckWARN\(WARN\_UNINITIALIZED\)
&nbsp;              \)
&nbsp;              report\_uninit\(left\);
&nbsp;          SvPVCLEAR\(left\);
&nbsp;      \}
&nbsp;      else \{
&nbsp;          SvPV\_force\_nomg\_nolen\(left\);
&nbsp;      \}
&nbsp;      lbyte = \!DO\_UTF8\(left\);
&nbsp;      if \(IN\_BYTES\)
&nbsp;          SvUTF8\_off\(left\);
&nbsp;  \}

As far as I can tell\, TARG has already been freed here \(by the \*x = 0\)
assignment\, but I'm afraid I'm a bit out of my depth on working out
how to fix that\. Should this be marked as a stack\-not\-refcounted
issue?

\-\- 
Aaron Crane \*\* http&#8203;://aaroncrane\.co\.uk/

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Jan 02\, 2017 at 07&#8203;:17&#8203;:59PM \+0000\, Aaron Crane wrote&#8203;:
> Brian Carpenter \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> > Triggered while fuzzing Perl v5\.25\.7\-26\-g7332835\.
> >
> > \./perl \-e '$$\.=$A=\*$=0'
> 
> This can be reduced to&#8203;: $x \.= \*x = 0
> 
> The segfault comes from the SvPVCLEAR\(\) in this block of pp\_concat\(\)&#8203;:
> 
>   else \{ /\* $l \.= $r   and   left == TARG \*/
>       if \(\!SvOK\(left\)\) \{
>           if \(\(left == right                          /\* $l \.= $l \*/
>                || \(PL\_op\->op\_private & OPpTARGET\_MY\)\) /\* $l = $l \. $r \*/
>               && ckWARN\(WARN\_UNINITIALIZED\)
>               \)
>               report\_uninit\(left\);
>           SvPVCLEAR\(left\);
>       \}
>       else \{
>           SvPV\_force\_nomg\_nolen\(left\);
>       \}
>       lbyte = \!DO\_UTF8\(left\);
>       if \(IN\_BYTES\)
>           SvUTF8\_off\(left\);
>   \}
> 
> As far as I can tell\, TARG has already been freed here \(by the \*x = 0\)
> assignment\, but I'm afraid I'm a bit out of my depth on working out
> how to fix that\.

> Should this be marked as a stack\-not\-refcounted issue?

Yes\. If the stack were refcounted\, $x wouldn't be freed by \*x = 0\.


\-\- 
Justice is when you get what you deserve\.
Law is when you get what you pay for\.
