### ISSUE TITLE
fuzzing testcase triggers LeakSanitizer over 101 byte memory leak

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15752]
Migrated from [rt.perl.org#130270](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130270) (status was 'open')

Searchable as RT130270$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered with Perl v5\.25\.7\-26\-g7332835\. I've never seen this before with
Perl\, not sure if it is even a bug or just an unlucky test case generated
by AFL\.

\./perl test269

=================================================================
==24156==ERROR&#8203;: LeakSanitizer&#8203;: detected memory leaks

Direct leak of 48 byte\(s\) in 1 object\(s\) allocated from&#8203;:
&nbsp;    \#0 0x4c0e10 in calloc \(/root/perl/perl\+0x4c0e10\)
&nbsp;    \#1 0x7fb251 in Perl\_safesyscalloc /root/perl/util\.c&#8203;:442&#8203;:18

Direct leak of 38 byte\(s\) in 1 object\(s\) allocated from&#8203;:
&nbsp;    \#0 0x4c0cbb in malloc \(/root/perl/perl\+0x4c0cbb\)
&nbsp;    \#1 0x7fa227 in Perl\_safesysmalloc /root/perl/util\.c&#8203;:153&#8203;:21

Indirect leak of 15 byte\(s\) in 1 object\(s\) allocated from&#8203;:
&nbsp;    \#0 0x4c0cbb in malloc \(/root/perl/perl\+0x4c0cbb\)
&nbsp;    \#1 0x7fa227 in Perl\_safesysmalloc /root/perl/util\.c&#8203;:153&#8203;:21

SUMMARY&#8203;: AddressSanitizer&#8203;: 101 byte\(s\) leaked in 3 allocation\(s\)\.

**Comment by p5pRT** [comment]
### From @geeknik

[test269.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1438453/778649/test269.gz)

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon\, 05 Dec 2016 10&#8203;:52&#8203;:13 \-0800\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> Triggered with Perl v5\.25\.7\-26\-g7332835\. I've never seen this before with
> Perl\, not sure if it is even a bug or just an unlucky test case generated
> by AFL\.
> 
> \./perl test269

This looks like more than one bug\, with some interactions between them\.

If I build blead with \-DDEBUGGING \-Doptimize=\-O0\\ \-g and run your
code as "130270\.pl" I see the leak you describe under valgrind \- sometimes&#8203;:

tony@&#8203;mars&#8203;:\.\.\./git/perl$ PERL\_DESTRUCT\_LEVEL=2 valgrind \-\-leak\-check=full \./perl \.\./130270\.pl
==7919== Memcheck\, a memory error detector
==7919== Copyright \(C\) 2002\-2013\, and GNU GPL'd\, by Julian Seward et al\.
==7919== Using Valgrind\-3\.10\.0 and LibVEX; rerun with \-h for copyright info
==7919== Command&#8203;: \./perl \.\./130270\.pl
==7919== 
Can't use an undefined value as a symbol reference at \.\./130270\.pl line 1\.
Attempt to free unreferenced scalar&#8203;: SV 0x5f71000\.
Attempt to free unreferenced scalar&#8203;: SV 0x5f71000\.
panic&#8203;: magic\_killbackrefs \(freed backref AV/SV\) during global destruction\.
==7919== 
==7919== HEAP SUMMARY&#8203;:
==7919==     in use at exit&#8203;: 100\,067 bytes in 173 blocks
==7919==   total heap usage&#8203;: 820 allocs\, 647 frees\, 162\,754 bytes allocated
==7919== 
==7919== 80 bytes in 1 blocks are definitely lost in loss record 94 of 145
==7919==    at 0x4C2AD10&#8203;: calloc \(in /usr/lib/valgrind/vgpreload\_memcheck\-amd64\-linux\.so\)
==7919==    by 0x558D5A&#8203;: Perl\_safesyscalloc \(util\.c&#8203;:440\)
==7919==    by 0x46E273&#8203;: Perl\_newGP \(gv\.c&#8203;:174\)
==7919==    by 0x46FBD2&#8203;: Perl\_gv\_init\_pvn \(gv\.c&#8203;:413\)
==7919==    by 0x47F2A9&#8203;: Perl\_gv\_fetchpvn\_flags \(gv\.c&#8203;:2401\)
==7919==    by 0x4954E5&#8203;: S\_force\_ident \(toke\.c&#8203;:2093\)
==7919==    by 0x4A7FEA&#8203;: Perl\_yylex \(toke\.c&#8203;:5491\)
==7919==    by 0x4D1A24&#8203;: Perl\_yyparse \(perly\.c&#8203;:347\)
==7919==    by 0x460116&#8203;: S\_parse\_body \(perl\.c&#8203;:2374\)
==7919==    by 0x45E5E6&#8203;: perl\_parse \(perl\.c&#8203;:1689\)
==7919==    by 0x41EFC5&#8203;: main \(perlmain\.c&#8203;:121\)
==7919== 
==7919== LEAK SUMMARY&#8203;:
==7919==    definitely lost&#8203;: 80 bytes in 1 blocks
==7919==    indirectly lost&#8203;: 0 bytes in 0 blocks
==7919==      possibly lost&#8203;: 0 bytes in 0 blocks
==7919==    still reachable&#8203;: 99\,987 bytes in 172 blocks
==7919==         suppressed&#8203;: 0 bytes in 0 blocks
==7919== Reachable blocks \(those to which a pointer was found\) are not shown\.
==7919== To see them\, rerun with&#8203;: \-\-leak\-check=full \-\-show\-leak\-kinds=all
==7919== 
==7919== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==7919== ERROR SUMMARY&#8203;: 1 errors from 1 contexts \(suppressed&#8203;: 0 from 0\)

Note the panic\, which probably causes the still reachable leaks\.

Sometimes the same invocation displays no "definitely lost"&#8203;:

tony@&#8203;mars&#8203;:\.\.\./git/perl$ PERL\_DESTRUCT\_LEVEL=2 valgrind \-\-leak\-check=full \./perl \.\./130270\.pl
==7916== Memcheck\, a memory error detector
==7916== Copyright \(C\) 2002\-2013\, and GNU GPL'd\, by Julian Seward et al\.
==7916== Using Valgrind\-3\.10\.0 and LibVEX; rerun with \-h for copyright info
==7916== Command&#8203;: \./perl \.\./130270\.pl
==7916== 
Can't use an undefined value as a symbol reference at \.\./130270\.pl line 1\.
Attempt to free unreferenced scalar&#8203;: SV 0x5f71000\.
Attempt to free unreferenced scalar&#8203;: SV 0x5f71000\.
panic&#8203;: magic\_killbackrefs \(freed backref AV/SV\) during global destruction\.
==7916== 
==7916== HEAP SUMMARY&#8203;:
==7916==     in use at exit&#8203;: 119\,933 bytes in 579 blocks
==7916==   total heap usage&#8203;: 820 allocs\, 241 frees\, 162\,754 bytes allocated
==7916== 
==7916== LEAK SUMMARY&#8203;:
==7916==    definitely lost&#8203;: 0 bytes in 0 blocks
==7916==    indirectly lost&#8203;: 0 bytes in 0 blocks
==7916==      possibly lost&#8203;: 0 bytes in 0 blocks
==7916==    still reachable&#8203;: 119\,933 bytes in 579 blocks
==7916==         suppressed&#8203;: 0 bytes in 0 blocks
==7916== Reachable blocks \(those to which a pointer was found\) are not shown\.
==7916== To see them\, rerun with&#8203;: \-\-leak\-check=full \-\-show\-leak\-kinds=all
==7916== 
==7916== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==7916== ERROR SUMMARY&#8203;: 0 errors from 0 contexts \(suppressed&#8203;: 0 from 0\)

but we still have a panic\.

If I change the name of the test script \(which I'd done to work on
reducing the test case\)&#8203;:

tony@&#8203;mars&#8203;:\.\.\./git/perl$ PERL\_DESTRUCT\_LEVEL=2 valgrind \-\-leak\-check=full \./perl \.\./130270b\.pl
==7999== Memcheck\, a memory error detector
==7999== Copyright \(C\) 2002\-2013\, and GNU GPL'd\, by Julian Seward et al\.
==7999== Using Valgrind\-3\.10\.0 and LibVEX; rerun with \-h for copyright info
==7999== Command&#8203;: \./perl \.\./130270b\.pl
==7999== 
==7999== Invalid read of size 8
==7999==    at 0x600122&#8203;: Perl\_newSV\_type \(sv\.c&#8203;:9654\)
==7999==    by 0x4794EC&#8203;: S\_parse\_gv\_stash\_name \(gv\.c&#8203;:1639\)
==7999==    by 0x47EDF7&#8203;: Perl\_gv\_fetchpvn\_flags \(gv\.c&#8203;:2324\)
==7999==    by 0x478A17&#8203;: Perl\_gv\_fetchsv \(gv\.c&#8203;:1561\)
==7999==    by 0x5DF5FE&#8203;: Perl\_sv\_setsv\_flags \(sv\.c&#8203;:4548\)
==7999==    by 0x5A109B&#8203;: Perl\_pp\_sassign \(pp\_hot\.c&#8203;:226\)
==7999==    by 0x5571AD&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2260\)
==7999==    by 0x460EB1&#8203;: S\_run\_body \(perl\.c&#8203;:2526\)
==7999==    by 0x460494&#8203;: perl\_run \(perl\.c&#8203;:2449\)
==7999==    by 0x41EFDD&#8203;: main \(perlmain\.c&#8203;:123\)
==7999==  Address 0x2200000c00000001 is not stack'd\, malloc'd or \(recently\) free'd
==7999== 
==7999== 
==7999== Process terminating with default action of signal 11 \(SIGSEGV\)
==7999==  General Protection Fault
==7999==    at 0x600122&#8203;: Perl\_newSV\_type \(sv\.c&#8203;:9654\)
==7999==    by 0x4794EC&#8203;: S\_parse\_gv\_stash\_name \(gv\.c&#8203;:1639\)
==7999==    by 0x47EDF7&#8203;: Perl\_gv\_fetchpvn\_flags \(gv\.c&#8203;:2324\)
==7999==    by 0x478A17&#8203;: Perl\_gv\_fetchsv \(gv\.c&#8203;:1561\)
==7999==    by 0x5DF5FE&#8203;: Perl\_sv\_setsv\_flags \(sv\.c&#8203;:4548\)
==7999==    by 0x5A109B&#8203;: Perl\_pp\_sassign \(pp\_hot\.c&#8203;:226\)
==7999==    by 0x5571AD&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2260\)
==7999==    by 0x460EB1&#8203;: S\_run\_body \(perl\.c&#8203;:2526\)
==7999==    by 0x460494&#8203;: perl\_run \(perl\.c&#8203;:2449\)
==7999==    by 0x41EFDD&#8203;: main \(perlmain\.c&#8203;:123\)
==7999== 

I tried the following local change to track down the location more accurately&#8203;:

<details><summary>Inline Patch</summary>

```diff
diff --git a/sv.c b/sv.c
index dc392f0..95b0dad 100644
--- a/sv.c
+++ b/sv.c
@@ -348,6 +348,7 @@ S_new_SV(pTHX_ const char *file, int line, const char *func)
 #  define new_SV(p) (p)=S_new_SV(aTHX_ __FILE__, __LINE__, FUNCTION__)
 
 #else
+#if 0
 #  define new_SV(p) \
     STMT_START {                                       \
        if (PL_sv_root)                                 \
@@ -360,6 +361,22 @@ S_new_SV(pTHX_ const char *file, int line, const char *func)
        MEM_LOG_NEW_SV(p, __FILE__, __LINE__, FUNCTION__);  \
     } STMT_END
 #endif
+#  define new_SV(p) \
+    ((p) = S_new_SV(aTHX))
+
+static __inline__
+SV * S_new_SV(aTHX) {
+    SV *p;
+    if (PL_sv_root)
+        uproot_SV(p);
+    else
+        (p) = S_more_sv(aTHX);
+    SvANY(p) = 0;
+    SvREFCNT(p) = 1;
+    SvFLAGS(p) = 0;
+    return p;
+}
+#endif
 
 
 /* del_SV(): return an empty SV head to the free list */


```
</details>
tony@mars:.../git/perl$ PERL_DESTRUCT_LEVEL=2 valgrind --leak-check=full ./perl ../130270b.pl
==10650== Memcheck\, a memory error detector
==10650== Copyright \(C\) 2002\-2013\, and GNU GPL'd\, by Julian Seward et al\.
==10650== Using Valgrind\-3\.10\.0 and LibVEX; rerun with \-h for copyright info
==10650== Command&#8203;: \./perl \.\./130270b\.pl
==10650== 
==10650== Invalid read of size 8
==10650==    at 0x5BEB21&#8203;: S\_new\_SV \(sv\.c&#8203;:371\)
==10650==    by 0x5FFC70&#8203;: Perl\_newSV\_type \(sv\.c&#8203;:9671\)
==10650==    by 0x4794EC&#8203;: S\_parse\_gv\_stash\_name \(gv\.c&#8203;:1639\)
==10650==    by 0x47EDF7&#8203;: Perl\_gv\_fetchpvn\_flags \(gv\.c&#8203;:2324\)
==10650==    by 0x478A17&#8203;: Perl\_gv\_fetchsv \(gv\.c&#8203;:1561\)
==10650==    by 0x5DF677&#8203;: Perl\_sv\_setsv\_flags \(sv\.c&#8203;:4565\)
==10650==    by 0x5A109B&#8203;: Perl\_pp\_sassign \(pp\_hot\.c&#8203;:226\)
==10650==    by 0x5571AD&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:2260\)
==10650==    by 0x460EB1&#8203;: S\_run\_body \(perl\.c&#8203;:2526\)
==10650==    by 0x460494&#8203;: perl\_run \(perl\.c&#8203;:2449\)
==10650==    by 0x41EFDD&#8203;: main \(perlmain\.c&#8203;:123\)
==10650==  Address 0x2200000c00000001 is not stack'd\, malloc'd or \(recently\) free'd
==10650== 
==10650== 
==10650== Process terminating with default action of signal 11 \(SIGSEGV\)
==10650==  General Protection Fault

which is the call to uproot\_SV\(\)\.

Without valgrind this doesn't always segfault&#8203;:

tony@&#8203;mars&#8203;:\.\.\./git/perl$ PERL\_DESTRUCT\_LEVEL=2 \./perl \.\./130270b\.pl
Attempt to free unreferenced glob pointers during global destruction\.
panic&#8203;: del\_backref\, svp=0 during global destruction\.

but usually does&#8203;:

tony@&#8203;mars&#8203;:\.\.\./git/perl$ PERL\_DESTRUCT\_LEVEL=2 \./perl \.\./130270b\.pl
Attempt to free unreferenced scalar&#8203;: SV 0x1d6a9c8 during global destruction\.
Segmentation fault

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon\, 05 Dec 2016 16&#8203;:27&#8203;:55 \-0800\, tonyc wrote&#8203;:
> On Mon\, 05 Dec 2016 10&#8203;:52&#8203;:13 \-0800\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> > Triggered with Perl v5\.25\.7\-26\-g7332835\. I've never seen this before
> > with
> > Perl\, not sure if it is even a bug or just an unlucky test case
> > generated
> > by AFL\.
> >
> > \./perl test269
> 
> This looks like more than one bug\, with some interactions between
> them\.
> 
> If I build blead with \-DDEBUGGING \-Doptimize=\-O0\\ \-g and run your
> code as "130270\.pl" I see the leak you describe under valgrind \-
> sometimes&#8203;:

Looking at this now&#8203;:

$ \./perl \-Ilib \-MO=Deparse \.\./130270\.pl
$$0 ^= \($0 |= \(\*0 = \*aHH&#8203;::HHMHHHHHHHOH\)\)\, \*& = \($$0 ^= \($0 |= \(\*0 = \*aHH&#8203;::HHMHHHHHHHOH = \*& = \*a6\)\)\) foreach \(\('b'\) x 56\);
'???';

it looks like another stack\-not\-refcounted bug\.

Tony
