### ISSUE TITLE
heap-buffer-overflow Perl_yyparse (perly.c:403)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15754]
Migrated from [rt.perl.org#130311](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130311) (status was 'resolved')

Searchable as RT130311$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered with Perl v5\.25\.7\-94\-gc9b6887 while fuzzing with AFL\.

od \-tx1 test11
0000000 69 20 61 20 66 7b 7b 7b 61 7b 7b 7b 7b 7b 7b 7b
0000020 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b
0000040 7b 5f 00 54 20 69 20 61 20 61 7b 7b 7b 7b 7b 7b
0000060 7b 7b 7b 7b 61 7b 7b 7b 7b 7b 7b 7b 7b 7b 5b 7b
0000100 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b
\*
0000140 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 7b 61 20 66
0000157

==23007==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
0x62300000fa08 at pc 0x0000006bc406 bp 0x7ffd024e9950 sp 0x7ffd024e9948
WRITE of size 2 at 0x62300000fa08 thread T0
&nbsp;    \#0 0x6bc405 in Perl\_yyparse /root/perl/perly\.c&#8203;:403&#8203;:13
&nbsp;    \#1 0x59bf51 in S\_parse\_body /root/perl/perl\.c&#8203;:2374&#8203;:9
&nbsp;    \#2 0x5921d0 in perl\_parse /root/perl/perl\.c&#8203;:1689&#8203;:2
&nbsp;    \#3 0x4de6b5 in main /root/perl/perlmain\.c&#8203;:121&#8203;:18
&nbsp;    \#4 0x7f24e029eb44 in \_\_libc\_start\_main
/build/glibc\-daoqzt/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#5 0x4de34c in \_start \(/root/perl/perl\+0x4de34c\)

0x62300000fa08 is located 8 bytes to the right of 6400\-byte region
\[0x62300000e100\,0x62300000fa00\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4c0ccb in malloc \(/root/perl/perl\+0x4c0ccb\)
&nbsp;    \#1 0x7fbe27 in Perl\_safesysmalloc /root/perl/util\.c&#8203;:153&#8203;:21
&nbsp;    \#2 0x59bf51 in S\_parse\_body /root/perl/perl\.c&#8203;:2374&#8203;:9
&nbsp;    \#3 0x5921d0 in perl\_parse /root/perl/perl\.c&#8203;:1689&#8203;:2
&nbsp;    \#4 0x4de6b5 in main /root/perl/perlmain\.c&#8203;:121&#8203;:18
&nbsp;    \#5 0x7f24e029eb44 in \_\_libc\_start\_main
/build/glibc\-daoqzt/glibc\-2\.19/csu/libc\-start\.c&#8203;:287

SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow /root/perl/perly\.c&#8203;:403
Perl\_yyparse
Shadow bytes around the buggy address&#8203;:
&nbsp;  0x0c467fff9ef0&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c467fff9f00&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c467fff9f10&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c467fff9f20&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c467fff9f30&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c467fff9f40&#8203;: fa\[fa\]fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c467fff9f50&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c467fff9f60&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c467fff9f70&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c467fff9f80&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c467fff9f90&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend \(one shadow byte represents 8 application bytes\)&#8203;:
&nbsp;  Addressable&#8203;:           00
&nbsp;  Partially addressable&#8203;: 01 02 03 04 05 06 07
&nbsp;  Heap left redzone&#8203;:       fa
&nbsp;  Heap right redzone&#8203;:      fb
&nbsp;  Freed heap region&#8203;:       fd
&nbsp;  Stack left redzone&#8203;:      f1
&nbsp;  Stack mid redzone&#8203;:       f2
&nbsp;  Stack right redzone&#8203;:     f3
&nbsp;  Stack partial redzone&#8203;:   f4
&nbsp;  Stack after return&#8203;:      f5
&nbsp;  Stack use after scope&#8203;:   f8
&nbsp;  Global redzone&#8203;:          f9
&nbsp;  Global init order&#8203;:       f6
&nbsp;  Poisoned by user&#8203;:        f7
&nbsp;  Container overflow&#8203;:      fc
&nbsp;  ASan internal&#8203;:           fe
==23007==ABORTING

**Comment by p5pRT** [comment]
### From @geeknik

[test11.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1439247/779242/test11.gz)

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, Dec 10\, 2016 at 10&#8203;:07&#8203;:58AM \-0800\, Brian Carpenter wrote&#8203;:
> Triggered with Perl v5\.25\.7\-94\-gc9b6887 while fuzzing with AFL\.

This was recently introduced by my own stupidity with v5\.25\.7\-60\-gb2c9b6e;
now reverted with v5\.25\.7\-98\-gdf13534\.

Since it hasn't been in a release\, its not a security issue :\-\)\.


\-\- 
The warp engines start playing up a bit\, but seem to sort themselves out
after a while without any intervention from boy genius Wesley Crusher\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#17

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Sat\, 10 Dec 2016 12&#8203;:21&#8203;:51 \-0800\, davem wrote&#8203;:
> On Sat\, Dec 10\, 2016 at 10&#8203;:07&#8203;:58AM \-0800\, Brian Carpenter wrote&#8203;:
> > Triggered with Perl v5\.25\.7\-94\-gc9b6887 while fuzzing with AFL\.
> 
> This was recently introduced by my own stupidity with v5\.25\.7\-60\-gb2c9b6e;
> now reverted with v5\.25\.7\-98\-gdf13534\.

So closing\.\.\.

> Since it hasn't been in a release\, its not a security issue :\-\)\.

\.\.\. after moving it to the public queue\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
