### ISSUE TITLE
Null pointer dereference + segfault in Perl_pp_subst (pp_hot.c:3368)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15756]
Migrated from [rt.perl.org#130315](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130315) (status was 'open')

Searchable as RT130315$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered with Perl v5\.25\.7\-98\-gdf13534 while fuzzing with AFL\.

od \-tx1 test114
0000000 6d 61 70 24 53 3d 25 5d 3d 73 2e 2e 54 0e 4d 2c
0000020 25 5f 42 44 2e 72 72 72 72 2c 4d 2c 25 5f 3d 44
0000040 2e 2e 54 2c 4d 2c 25 5f 3d 44 2e 2e 54 2c 4d 2c
0000060 04 22 04 3d 25 5d 3d 52 2e 2e 54 2c 54 2c 25 5f
0000100 3d 44 2e 2e 54 2c 4d 22 04 1d 22 6e 6e 70 67 1d
0000120 22 6c 6e 67 67 00 1b 02 00 7f 00 00 00 b9 9f
0000137

semi\-panic&#8203;: attempt to dup freed string at test114 line 1\.
ASAN&#8203;:SIGSEGV
=================================================================
==29301==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x00000000000c
\(pc 0x0000008d5abd bp 0x7ffdebe9de60 sp 0x7ffdebe9dc80 T0\)
&nbsp;    \#0 0x8d5abc in Perl\_pp\_subst /root/perl/pp\_hot\.c&#8203;:3368&#8203;:6
&nbsp;    \#1 0x7f81fb in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2260&#8203;:23
&nbsp;    \#2 0x5a0ab3 in S\_run\_body /root/perl/perl\.c&#8203;:2526&#8203;:2
&nbsp;    \#3 0x5a0ab3 in perl\_run /root/perl/perl\.c&#8203;:2449
&nbsp;    \#4 0x4de6dd in main /root/perl/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#5 0x7ff28cd26b44 in \_\_libc\_start\_main
/build/glibc\-daoqzt/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#6 0x4de34c in \_start \(/root/perl/perl\+0x4de34c\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /root/perl/pp\_hot\.c&#8203;:3368 Perl\_pp\_subst
==29301==ABORTING

**Comment by p5pRT** [comment]
### From @geeknik

[test114.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1439314/779294/test114.gz)

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Dec 11\, 2016 at 12&#8203;:39&#8203;:15PM \-0800\, Brian Carpenter wrote&#8203;:
> \# New Ticket Created by  Brian Carpenter 
> \# Please include the string&#8203;:  \[perl \#130315\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130315 >
> 
> 
> Triggered with Perl v5\.25\.7\-98\-gdf13534 while fuzzing with AFL\.
> 
> od \-tx1 test114
> 0000000 6d 61 70 24 53 3d 25 5d 3d 73 2e 2e 54 0e 4d 2c
> 0000020 25 5f 42 44 2e 72 72 72 72 2c 4d 2c 25 5f 3d 44
> 0000040 2e 2e 54 2c 4d 2c 25 5f 3d 44 2e 2e 54 2c 4d 2c
> 0000060 04 22 04 3d 25 5d 3d 52 2e 2e 54 2c 54 2c 25 5f
> 0000100 3d 44 2e 2e 54 2c 4d 22 04 1d 22 6e 6e 70 67 1d
> 0000120 22 6c 6e 67 67 00 1b 02 00 7f 00 00 00 b9 9f
> 0000137
> 
> semi\-panic&#8203;: attempt to dup freed string at test114 line 1\.
> ASAN&#8203;:SIGSEGV
> =================================================================
> ==29301==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x00000000000c
> \(pc 0x0000008d5abd bp 0x7ffdebe9de60 sp 0x7ffdebe9dc80 T0\)
>     \#0 0x8d5abc in Perl\_pp\_subst /root/perl/pp\_hot\.c&#8203;:3368&#8203;:6
>     \#1 0x7f81fb in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2260&#8203;:23
>     \#2 0x5a0ab3 in S\_run\_body /root/perl/perl\.c&#8203;:2526&#8203;:2
>     \#3 0x5a0ab3 in perl\_run /root/perl/perl\.c&#8203;:2449
>     \#4 0x4de6dd in main /root/perl/perlmain\.c&#8203;:123&#8203;:9
>     \#5 0x7ff28cd26b44 in \_\_libc\_start\_main
> /build/glibc\-daoqzt/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
>     \#6 0x4de34c in \_start \(/root/perl/perl\+0x4de34c\)

This is a stack\-not\-ref\-counted issue\.  It can be reduced to&#8203;:

&nbsp;    map 1\, \(%x\) = \(1\.\.3\)\, \(%x\) = \(\);

&nbsp;    perl&#8203;: sv\.c&#8203;:6540&#8203;: Perl\_sv\_clear&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= \(svtype\)0xff' failed\.


or using a for loop instead\, which has a hack that checks whether the
value about be iterated on has been freed&#8203;:

&nbsp;    1 for \(%x\) = \(1\.\.3\)\, \(%x\) = \(\);

&nbsp;    Use of freed value in iteration at /tmp/test114 line 1\.







\-\- 
Never work with children\, animals\, or actors\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'
