### ISSUE TITLE
segfault in Perl_magic_set (mg.c:2850)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15761]
Migrated from [rt.perl.org#130320](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130320) (status was 'open')

Searchable as RT130320$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered with Perl v5\.25\.7\-98\-gdf13534 while fuzzing with AFL\. The crash
doesn't happen on every execution\, sometimes it just fails with
\`Modification of a read\-only value attempted at test403 line 1\.\`

od \-tx1 test403
0000000 6d 61 70 24 5f 3d 20 24 24 5f 3d 24 5e 3c 24 30
0000020 2c 25 3a 3a 04 e5 30 30 30 30 30
0000033

\./perl test403
ASAN&#8203;:SIGSEGV
=================================================================
==14592==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000000
\(pc 0x00000084485e bp 0x7ffd3c771e90 sp 0x7ffd3c771cc0 T0\)
&nbsp;    \#0 0x84485d in Perl\_magic\_set /root/perl/mg\.c&#8203;:2850&#8203;:2
&nbsp;    \#1 0x825575 in Perl\_mg\_set /root/perl/mg\.c&#8203;:277&#8203;:6
&nbsp;    \#2 0x8a56b9 in Perl\_pp\_sassign /root/perl/pp\_hot\.c&#8203;:226&#8203;:5
&nbsp;    \#3 0x7f81fb in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2260&#8203;:23
&nbsp;    \#4 0x5a0ab3 in S\_run\_body /root/perl/perl\.c&#8203;:2526&#8203;:2
&nbsp;    \#5 0x5a0ab3 in perl\_run /root/perl/perl\.c&#8203;:2449
&nbsp;    \#6 0x4de6dd in main /root/perl/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#7 0x7fe77bb1eb44 in \_\_libc\_start\_main
/build/glibc\-daoqzt/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#8 0x4de34c in \_start \(/root/perl/perl\+0x4de34c\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /root/perl/mg\.c&#8203;:2850 Perl\_magic\_set
==14592==ABORTING

**Comment by p5pRT** [comment]
### From @geeknik

[test403.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1439374/779339/test403.gz)

**Comment by p5pRT** [comment]
### From @hvds

This reduces to&#8203;:
% \./miniperl \-e '$&#8203;::\{STDOUT\} = $^; $\{ $&#8203;::\{"^"\} \} = undef'
Segmentation fault \(core dumped\)
% 

At this point GvIOp\(PL\_defoutgv\) is NULL\. I've no idea what we should do with that\, and various other cases of the same switch statement look to have similar assumptions\.

Hugo

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Dec 12\, 2016 at 02&#8203;:45&#8203;:51AM \-0800\, Hugo van der Sanden via RT wrote&#8203;:
> This reduces to&#8203;:
> % \./miniperl \-e '$&#8203;::\{STDOUT\} = $^; $\{ $&#8203;::\{"^"\} \} = undef'
> Segmentation fault \(core dumped\)
> % 

It reduces even further to

&nbsp;    $&#8203;::\{'STDOUT'\} = 0;
&nbsp;    $^ = 'abc';

> At this point GvIOp\(PL\_defoutgv\) is NULL\. I've no idea what we should do
> with that\, and various other cases of the same switch statement look to
> have similar assumptions\.

I think assigning to the various format vars should just silently
do nothing if there isn't a valid default IO handle\. 

\-\- 
The Enterprise's efficient long\-range scanners detect a temporal vortex
distortion in good time\, allowing it to be safely avoided via a minor
course correction\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#21

**Comment by p5pRT** [comment]
### From @tux

On Mon\, 12 Dec 2016 12&#8203;:03&#8203;:45 \+0000\, Dave Mitchell \<davem@&#8203;iabyn\.com>
wrote&#8203;:

> On Mon\, Dec 12\, 2016 at 02&#8203;:45&#8203;:51AM \-0800\, Hugo van der Sanden via RT wrote&#8203;:
> > This reduces to&#8203;:
> > % \./miniperl \-e '$&#8203;::\{STDOUT\} = $^; $\{ $&#8203;::\{"^"\} \} = undef'
> > Segmentation fault \(core dumped\)
> > %   
> 
> It reduces even further to
> 
>     $&#8203;::\{'STDOUT'\} = 0;
>     $^ = 'abc';
> 
> > At this point GvIOp\(PL\_defoutgv\) is NULL\. I've no idea what we should do
> > with that\, and various other cases of the same switch statement look to
> > have similar assumptions\.  
> 
> I think assigning to the various format vars should just silently
> do nothing if there isn't a valid default IO handle\. 

Agree\, but

default → current

select $fh;

would make $^\, $=\, $\- work on $fh

The only way out is a lot of work&#8203;: currently most of the format\-related
globals are what it says&#8203;: global\. They ideally should be scoped to
a/the file\-handle they belong to\.

$= and $\- are the worst of these\. It is very easy to make $\- report
wrong values\.

\-\- 
H\.Merijn Brand  http&#8203;://tux\.nl   Perl Monger  http&#8203;://amsterdam\.pm\.org/
using perl5\.00307 \.\. 5\.25   porting perl5 on HP\-UX\, AIX\, and openSUSE
http&#8203;://mirrors\.develooper\.com/hpux/        http&#8203;://www\.test\-smoke\.org/
http&#8203;://qa\.perl\.org   http&#8203;://www\.goldmark\.org/jeff/stupid\-disclaimers/
