### ISSUE TITLE
double-free affecting multiple Perl versions

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15765]
Migrated from [rt.perl.org#130332](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130332) (status was 'open')

Searchable as RT130332$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered with Perl v5\.25\.7\-98\-gdf13534 while fuzzing with AFL\.

od \-tx1 test430
0000000 6d 61 70 2a 00 00 24 5f 3d 20 24 23 24 5f 3d 38
0000020 2c 25 5f 3d 44 2e 2e 00 20 46 54 2c 44 4f 55 4d
0000040 38 2c 25 5f 3d 44 2e 2e 00 20 46 2c 04 22 39 6e
0000060 6e 67 67 31 7f 00 00 80 ff ff 7f 44 68 55 4d 2c
0000100 04 22 22 6e 6e 67 67 31 24 2a 11 00 43 4b 57 a8
0000120 9f
0000121

=================================================================
==15593==ERROR&#8203;: AddressSanitizer&#8203;: attempting double\-free on 0x60200000b4f0
in thread T0&#8203;:
&nbsp;    \#0 0x4c0a4b in \_\_interceptor\_free \(/root/perl/perl\+0x4c0a4b\)
&nbsp;    \#1 0x7fce59 in Perl\_safesysfree /root/perl/util\.c&#8203;:388&#8203;:2
&nbsp;    \#2 0x8abb3d in Perl\_vivify\_ref /root/perl/pp\_hot\.c&#8203;:4362&#8203;:2
&nbsp;    \#3 0x9aeb55 in Perl\_pp\_rv2sv /root/perl/pp\.c&#8203;:404&#8203;:11
&nbsp;    \#4 0x7f81fb in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2260&#8203;:23
&nbsp;    \#5 0x5a0ab3 in S\_run\_body /root/perl/perl\.c&#8203;:2526&#8203;:2
&nbsp;    \#6 0x5a0ab3 in perl\_run /root/perl/perl\.c&#8203;:2449
&nbsp;    \#7 0x4de6dd in main /root/perl/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#8 0x7f5d28d62b44 in \_\_libc\_start\_main
/build/glibc\-daoqzt/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#9 0x4de34c in \_start \(/root/perl/perl\+0x4de34c\)

0x60200000b4f0 is located 0 bytes inside of 10\-byte region
\[0x60200000b4f0\,0x60200000b4fa\)
freed by thread T0 here&#8203;:
&nbsp;    \#0 0x4c0a4b in \_\_interceptor\_free \(/root/perl/perl\+0x4c0a4b\)
&nbsp;    \#1 0x7fce59 in Perl\_safesysfree /root/perl/util\.c&#8203;:388&#8203;:2
&nbsp;    \#2 0x957ec2 in Perl\_sv\_free2 /root/perl/sv\.c&#8203;:7056&#8203;:9

previously allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4c0ccb in malloc \(/root/perl/perl\+0x4c0ccb\)
&nbsp;    \#1 0x7fc067 in Perl\_safesysmalloc /root/perl/util\.c&#8203;:153&#8203;:21

SUMMARY&#8203;: AddressSanitizer&#8203;: double\-free ??&#8203;:0 \_\_interceptor\_free
==15593==ABORTING

Perl 5\.20\.2 fails under Valgrind with&#8203;:
==8886== Invalid free\(\) / delete / delete\[\] / realloc\(\)
==8886==    at 0x4C29E90&#8203;: free \(vg\_replace\_malloc\.c&#8203;:473\)
==8886==    by 0x4F031B7&#8203;: Perl\_vivify\_ref \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4F1ECCE&#8203;: Perl\_pp\_rv2sv \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4EFB055&#8203;: Perl\_runops\_standard \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4E8B73D&#8203;: perl\_run \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x400E18&#8203;: main \(in /usr/bin/perl\)
==8886==  Address 0x5f447b0 is 0 bytes inside a block of size 10 free'd
==8886==    at 0x4C29E90&#8203;: free \(vg\_replace\_malloc\.c&#8203;:473\)
==8886==    by 0x4F0CFAB&#8203;: Perl\_sv\_clear \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4F0D289&#8203;: Perl\_sv\_free2 \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4EF4C9A&#8203;: ??? \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4EF7D99&#8203;: Perl\_hv\_clear \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4EFDF04&#8203;: Perl\_pp\_aassign \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4EFB055&#8203;: Perl\_runops\_standard \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4E8B73D&#8203;: perl\_run \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x400E18&#8203;: main \(in /usr/bin/perl\)
==8886==
Not a GLOB reference at test430 line 1\.
==8886== Invalid read of size 1
==8886==    at 0x4F0DA54&#8203;: ??? \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4F0DBBD&#8203;: Perl\_sv\_unmagic \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4F0C7DE&#8203;: Perl\_sv\_clear \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4F0D289&#8203;: Perl\_sv\_free2 \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4F31D00&#8203;: Perl\_leave\_scope \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4E82775&#8203;: ??? \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4E8B902&#8203;: Perl\_my\_failure\_exit \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4F3AF5C&#8203;: Perl\_die\_unwind \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4EDD838&#8203;: Perl\_vcroak \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4EDD9C3&#8203;: Perl\_die \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4F1E999&#8203;: Perl\_pp\_rv2gv \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4EFB055&#8203;: Perl\_runops\_standard \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==  Address 0xff00000012 is not stack'd\, malloc'd or \(recently\) free'd
==8886==
==8886==
==8886== Process terminating with default action of signal 11 \(SIGSEGV\)
==8886==  Access not within mapped region at address 0xFF00000012
==8886==    at 0x4F0DA54&#8203;: ??? \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4F0DBBD&#8203;: Perl\_sv\_unmagic \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4F0C7DE&#8203;: Perl\_sv\_clear \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4F0D289&#8203;: Perl\_sv\_free2 \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4F31D00&#8203;: Perl\_leave\_scope \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4E82775&#8203;: ??? \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4E8B902&#8203;: Perl\_my\_failure\_exit \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4F3AF5C&#8203;: Perl\_die\_unwind \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4EDD838&#8203;: Perl\_vcroak \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4EDD9C3&#8203;: Perl\_die \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4F1E999&#8203;: Perl\_pp\_rv2gv \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==    by 0x4EFB055&#8203;: Perl\_runops\_standard \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==8886==  If you believe this happened as a result of a stack
==8886==  overflow in your program's main thread \(unlikely but
==8886==  possible\)\, you can try to increase the size of the
==8886==  main thread stack using the \-\-main\-stacksize= flag\.
==8886==  The main thread stack size used in this run was 8388608\.
Segmentation fault

**Comment by p5pRT** [comment]
### From @geeknik

[test430.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1439595/779482/test430.gz)

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon\, 12 Dec 2016 17&#8203;:26&#8203;:26 \-0800\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> Triggered with Perl v5\.25\.7\-98\-gdf13534 while fuzzing with AFL\.
> 
> od \-tx1 test430
> 0000000 6d 61 70 2a 00 00 24 5f 3d 20 24 23 24 5f 3d 38
> 0000020 2c 25 5f 3d 44 2e 2e 00 20 46 54 2c 44 4f 55 4d
> 0000040 38 2c 25 5f 3d 44 2e 2e 00 20 46 2c 04 22 39 6e
> 0000060 6e 67 67 31 7f 00 00 80 ff ff 7f 44 68 55 4d 2c
> 0000100 04 22 22 6e 6e 67 67 31 24 2a 11 00 43 4b 57 a8
> 0000120 9f
> 0000121

Another stack\-not\-refcounted bug\.

Rarely running this doesn't produce this error for me\, but&#8203;:

 $ \./perl \.\./130332\.pl 
 Modification of a read\-only value attempted at \.\./130332\.pl line 1\.

More rarely it produces&#8203;:

$ \./perl \.\./130332\.pl 
=================================================================
==18246==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address 0x6210000114f0 at pc 0x839aa3 bp 0x7ffe5993e640 sp 0x7ffe5993e638
READ of size 8 at 0x6210000114f0 thread T0
&nbsp;    \#0 0x839aa2 in Perl\_vivify\_ref /home/tony/dev/perl/git/perl/pp\_hot\.c&#8203;:4362
&nbsp;    \#1 0x923c4a in Perl\_pp\_rv2sv /home/tony/dev/perl/git/perl/pp\.c&#8203;:404
&nbsp;    \#2 0x73a813 in Perl\_runops\_debug /home/tony/dev/perl/git/perl/dump\.c&#8203;:2260
&nbsp;    \#3 0x4be8d3 in S\_run\_body /home/tony/dev/perl/git/perl/perl\.c&#8203;:2526
&nbsp;    \#4 0x4bcc5e in perl\_run /home/tony/dev/perl/git/perl/perl\.c&#8203;:2449
&nbsp;    \#5 0x41fa8b in main /home/tony/dev/perl/git/perl/perlmain\.c&#8203;:123
&nbsp;    \#6 0x7f22f781eb44 in \_\_libc\_start\_main \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x21b44\)
&nbsp;    \#7 0x41f808 \(/home/tony/dev/perl/git/perl/perl\+0x41f808\)

0x6210000114f0 is located 0 bytes to the right of 4080\-byte region \[0x621000010500\,0x6210000114f0\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x7f22f897073f in malloc \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.1\+0x5473f\)
&nbsp;    \#1 0x73e0ee in Perl\_safesysmalloc /home/tony/dev/perl/git/perl/util\.c&#8203;:153
&nbsp;    \#2 0x8434f3 in S\_more\_sv /home/tony/dev/perl/git/perl/sv\.c&#8203;:307
&nbsp;    \#3 0x8e6555 in Perl\_newSV\_type /home/tony/dev/perl/git/perl/sv\.c&#8203;:9654
&nbsp;    \#4 0x4f9aba in S\_parse\_gv\_stash\_name /home/tony/dev/perl/git/perl/gv\.c&#8203;:1639
&nbsp;    \#5 0x507c5b in Perl\_gv\_fetchpvn\_flags /home/tony/dev/perl/git/perl/gv\.c&#8203;:2324
&nbsp;    \#6 0x47876c in Perl\_newXS\_len\_flags /home/tony/dev/perl/git/perl/op\.c&#8203;:9134
&nbsp;    \#7 0x47854b in Perl\_newXS\_flags /home/tony/dev/perl/git/perl/op\.c&#8203;:9108
&nbsp;    \#8 0xb7ebf4 in Perl\_boot\_core\_UNIVERSAL /home/tony/dev/perl/git/perl/universal\.c&#8203;:1084
&nbsp;    \#9 0x4babf9 in S\_parse\_body /home/tony/dev/perl/git/perl/perl\.c&#8203;:2274
&nbsp;    \#10 0x4b7f50 in perl\_parse /home/tony/dev/perl/git/perl/perl\.c&#8203;:1689
&nbsp;    \#11 0x41fa73 in main /home/tony/dev/perl/git/perl/perlmain\.c&#8203;:121
&nbsp;    \#12 0x7f22f781eb44 in \_\_libc\_start\_main \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x21b44\)

SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow /home/tony/dev/perl/git/perl/pp\_hot\.c&#8203;:4362 Perl\_vivify\_ref
Shadow bytes around the buggy address&#8203;:
&nbsp;  0x0c427fffa240&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c427fffa250&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c427fffa260&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c427fffa270&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c427fffa280&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c427fffa290&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00\[fa\]fa
&nbsp;  0x0c427fffa2a0&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c427fffa2b0&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c427fffa2c0&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c427fffa2d0&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c427fffa2e0&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend \(one shadow byte represents 8 application bytes\)&#8203;:
&nbsp;  Addressable&#8203;:           00
&nbsp;  Partially addressable&#8203;: 01 02 03 04 05 06 07 
&nbsp;  Heap left redzone&#8203;:       fa
&nbsp;  Heap right redzone&#8203;:      fb
&nbsp;  Freed heap region&#8203;:       fd
&nbsp;  Stack left redzone&#8203;:      f1
&nbsp;  Stack mid redzone&#8203;:       f2
&nbsp;  Stack right redzone&#8203;:     f3
&nbsp;  Stack partial redzone&#8203;:   f4
&nbsp;  Stack after return&#8203;:      f5
&nbsp;  Stack use after scope&#8203;:   f8
&nbsp;  Global redzone&#8203;:          f9
&nbsp;  Global init order&#8203;:       f6
&nbsp;  Poisoned by user&#8203;:        f7
&nbsp;  Contiguous container OOB&#8203;:fc
&nbsp;  ASan internal&#8203;:           fe
==18246==ABORTING

which looks like \#130321\.

Simplifies to&#8203;:

 \./perl \-e 'map\*$\_= $\#$\_=8\,%\_=D\.\. FD\,%\_=D\.\. F'

The variations are likely from hash ordering\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, Dec 13\, 2016 at 09&#8203;:27&#8203;:33PM \-0800\, Tony Cook via RT wrote&#8203;:
> which looks like \#130321\.
> 
> Simplifies to&#8203;:
> 
>  \./perl \-e 'map\*$\_= $\#$\_=8\,%\_=D\.\. FD\,%\_=D\.\. F'
> 
> The variations are likely from hash ordering\.

And as for \#130321\, I propose that the ticket be moved to the public
queue\, added to the 'stack not ref counted' meta ticket\, then ignored
until such time as we fix that wider issue\.

\-\- 
Wesley Crusher gets beaten up by his classmates for being a smarmy git\,
and consequently has a go at making some friends of his own age for a
change\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#18

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Feb 20\, 2017 at 11&#8203;:45&#8203;:12AM \+0000\, Dave Mitchell wrote&#8203;:
> On Tue\, Dec 13\, 2016 at 09&#8203;:27&#8203;:33PM \-0800\, Tony Cook via RT wrote&#8203;:
> > which looks like \#130321\.
> > 
> > Simplifies to&#8203;:
> > 
> >  \./perl \-e 'map\*$\_= $\#$\_=8\,%\_=D\.\. FD\,%\_=D\.\. F'
> > 
> > The variations are likely from hash ordering\.
> 
> And as for \#130321\, I propose that the ticket be moved to the public
> queue\, added to the 'stack not ref counted' meta ticket\, then ignored
> until such time as we fix that wider issue\.

which I am now doing\.

\-\- 
Fire extinguisher \(n\) a device for holding open fire doors\.
