### ISSUE TITLE
attempting free on address which was not malloc()-ed

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15769]
Migrated from [rt.perl.org#130336](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130336) (status was 'open')

Searchable as RT130336$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered with Perl v5\.25\.7\-98\-gdf13534 while fuzzing with AFL\.

od \-tx1 test557
0000000 6d 61 70 25 00 00 24 5f 3d 20 25 5f 3d 20 25 00
0000020 24 5f 2c 25 3a 3a 04 32 22 6e 6e 3f ff ff e5 bd
0000040 3d 5d 3a 3a 2f 46 ff f5 80 ff 7f 40 48 48 1f 48
0000060 48 48 36 48 48 48 48 48 48 48 64 00 48 48 48 48
0000100 48 48 48 26 48 48 ff ff 80 6e 6e 40 00 fc ed fa
0000120 3a 3a 46 ff ff 80 6e 6e 40 00 ff ff 7f ff ff ff
0000140 f8 af 00 fc ed fa
0000146

==20040==ERROR&#8203;: AddressSanitizer&#8203;: attempting free on address which was not
malloc\(\)\-ed&#8203;: 0x60400000adb0 in thread T0
&nbsp;    \#0 0x4c0a4b in \_\_interceptor\_free \(/root/perl/perl\+0x4c0a4b\)
&nbsp;    \#1 0x7fce59 in Perl\_safesysfree /root/perl/util\.c&#8203;:388&#8203;:2
&nbsp;    \#2 0x8abb3d in Perl\_vivify\_ref /root/perl/pp\_hot\.c&#8203;:4362&#8203;:2
&nbsp;    \#3 0x9aeb55 in Perl\_pp\_rv2sv /root/perl/pp\.c&#8203;:404&#8203;:11
&nbsp;    \#4 0x7f81fb in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2260&#8203;:23
&nbsp;    \#5 0x5a0ab3 in S\_run\_body /root/perl/perl\.c&#8203;:2526&#8203;:2
&nbsp;    \#6 0x5a0ab3 in perl\_run /root/perl/perl\.c&#8203;:2449
&nbsp;    \#7 0x4de6dd in main /root/perl/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#8 0x7f8d15882b44 in \_\_libc\_start\_main
/build/glibc\-daoqzt/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#9 0x4de34c in \_start \(/root/perl/perl\+0x4de34c\)

0x60400000adb0 is located 32 bytes inside of 37\-byte region
\[0x60400000ad90\,0x60400000adb5\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4c0ccb in malloc \(/root/perl/perl\+0x4c0ccb\)
&nbsp;    \#1 0x7fc067 in Perl\_safesysmalloc /root/perl/util\.c&#8203;:153&#8203;:21

SUMMARY&#8203;: AddressSanitizer&#8203;: bad\-free ??&#8203;:0 \_\_interceptor\_free
==20040==ABORTING

Perl 5\.20\.2 fails under Valgrind like so&#8203;:
==22494== Invalid read of size 1
==22494==    at 0x4F0DA54&#8203;: ??? \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==22494==    by 0x4F0DBBD&#8203;: Perl\_sv\_unmagic \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==22494==    by 0x4F0C7DE&#8203;: Perl\_sv\_clear \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==22494==    by 0x4F0D289&#8203;: Perl\_sv\_free2 \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==22494==    by 0x4F3943C&#8203;: Perl\_pp\_mapwhile \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==22494==    by 0x4EFB055&#8203;: Perl\_runops\_standard \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==22494==    by 0x4E8B73D&#8203;: perl\_run \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==22494==    by 0x400E18&#8203;: main \(in /usr/bin/perl\)
==22494==  Address 0xff00000012 is not stack'd\, malloc'd or \(recently\)
free'd
==22494==
==22494==
==22494== Process terminating with default action of signal 11 \(SIGSEGV\)
==22494==  Access not within mapped region at address 0xFF00000012
==22494==    at 0x4F0DA54&#8203;: ??? \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==22494==    by 0x4F0DBBD&#8203;: Perl\_sv\_unmagic \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==22494==    by 0x4F0C7DE&#8203;: Perl\_sv\_clear \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==22494==    by 0x4F0D289&#8203;: Perl\_sv\_free2 \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==22494==    by 0x4F3943C&#8203;: Perl\_pp\_mapwhile \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==22494==    by 0x4EFB055&#8203;: Perl\_runops\_standard \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==22494==    by 0x4E8B73D&#8203;: perl\_run \(in
/usr/lib/x86\_64\-linux\-gnu/libperl\.so\.5\.20\.2\)
==22494==    by 0x400E18&#8203;: main \(in /usr/bin/perl\)
==22494==  If you believe this happened as a result of a stack
==22494==  overflow in your program's main thread \(unlikely but
==22494==  possible\)\, you can try to increase the size of the
==22494==  main thread stack using the \-\-main\-stacksize= flag\.
==22494==  The main thread stack size used in this run was 8388608\.
Segmentation fault

**Comment by p5pRT** [comment]
### From @geeknik

[test557.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1439637/779507/test557.gz)

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon\, 12 Dec 2016 22&#8203;:59&#8203;:57 \-0800\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> Triggered with Perl v5\.25\.7\-98\-gdf13534 while fuzzing with AFL\.
> 
> od \-tx1 test557
> 0000000 6d 61 70 25 00 00 24 5f 3d 20 25 5f 3d 20 25 00
> 0000020 24 5f 2c 25 3a 3a 04 32 22 6e 6e 3f ff ff e5 bd
> 0000040 3d 5d 3a 3a 2f 46 ff f5 80 ff 7f 40 48 48 1f 48
> 0000060 48 48 36 48 48 48 48 48 48 48 64 00 48 48 48 48
> 0000100 48 48 48 26 48 48 ff ff 80 6e 6e 40 00 fc ed fa
> 0000120 3a 3a 46 ff ff 80 6e 6e 40 00 ff ff 7f ff ff ff
> 0000140 f8 af 00 fc ed fa
> 0000146

I also got&#8203;:

 $ \./perl \.\./130336\.pl 
 perl&#8203;: sv\.c&#8203;:6540&#8203;: Perl\_sv\_clear&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= \(svtype\)0xff' failed\.
 Aborted

and&#8203;:

$ \./perl \.\./130336\.pl 
=================================================================
==18473==ERROR&#8203;: AddressSanitizer&#8203;: attempting double\-free on 0x60400000d0f0 in thread T0&#8203;:
&nbsp;    \#0 0x7f69be81d527 in \_\_interceptor\_free \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.1\+0x54527\)
&nbsp;    \#1 0x73e7ab in Perl\_safesysfree /home/tony/dev/perl/git/perl/util\.c&#8203;:388
&nbsp;    \#2 0x83a2d7 in Perl\_vivify\_ref /home/tony/dev/perl/git/perl/pp\_hot\.c&#8203;:4362
&nbsp;    \#3 0x923c4a in Perl\_pp\_rv2sv /home/tony/dev/perl/git/perl/pp\.c&#8203;:404
&nbsp;    \#4 0x73a813 in Perl\_runops\_debug /home/tony/dev/perl/git/perl/dump\.c&#8203;:2260
&nbsp;    \#5 0x4be8d3 in S\_run\_body /home/tony/dev/perl/git/perl/perl\.c&#8203;:2526
&nbsp;    \#6 0x4bcc5e in perl\_run /home/tony/dev/perl/git/perl/perl\.c&#8203;:2449
&nbsp;    \#7 0x41fa8b in main /home/tony/dev/perl/git/perl/perlmain\.c&#8203;:123
&nbsp;    \#8 0x7f69bd6cbb44 in \_\_libc\_start\_main \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x21b44\)
&nbsp;    \#9 0x41f808 \(/home/tony/dev/perl/git/perl/perl\+0x41f808\)

0x60400000d0f0 is located 32 bytes inside of 43\-byte region \[0x60400000d0d0\,0x60400000d0fb\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x7f69be81d73f in malloc \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.1\+0x5473f\)
&nbsp;    \#1 0x73e0ee in Perl\_safesysmalloc /home/tony/dev/perl/git/perl/util\.c&#8203;:153
&nbsp;    \#2 0x7e33f7 in S\_share\_hek\_flags /home/tony/dev/perl/git/perl/hv\.c&#8203;:3030
&nbsp;    \#3 0x7c95b7 in Perl\_hv\_common /home/tony/dev/perl/git/perl/hv\.c&#8203;:819
&nbsp;    \#4 0x7c680c in Perl\_hv\_common\_key\_len /home/tony/dev/perl/git/perl/hv\.c&#8203;:333
&nbsp;    \#5 0x4f940f in S\_parse\_gv\_stash\_name /home/tony/dev/perl/git/perl/gv\.c&#8203;:1625
&nbsp;    \#6 0x507c5b in Perl\_gv\_fetchpvn\_flags /home/tony/dev/perl/git/perl/gv\.c&#8203;:2324
&nbsp;    \#7 0x47876c in Perl\_newXS\_len\_flags /home/tony/dev/perl/git/perl/op\.c&#8203;:9134
&nbsp;    \#8 0x47854b in Perl\_newXS\_flags /home/tony/dev/perl/git/perl/op\.c&#8203;:9108
&nbsp;    \#9 0xb7ebf4 in Perl\_boot\_core\_UNIVERSAL /home/tony/dev/perl/git/perl/universal\.c&#8203;:1084
&nbsp;    \#10 0x4babf9 in S\_parse\_body /home/tony/dev/perl/git/perl/perl\.c&#8203;:2274
&nbsp;    \#11 0x4b7f50 in perl\_parse /home/tony/dev/perl/git/perl/perl\.c&#8203;:1689
&nbsp;    \#12 0x41fa73 in main /home/tony/dev/perl/git/perl/perlmain\.c&#8203;:121
&nbsp;    \#13 0x7f69bd6cbb44 in \_\_libc\_start\_main \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x21b44\)

SUMMARY&#8203;: AddressSanitizer&#8203;: double\-free ??&#8203;:0 \_\_interceptor\_free
==18473==ABORTING

and&#8203;:

$ \./perl \.\./130336\.pl 
=================================================================
==18728==ERROR&#8203;: AddressSanitizer&#8203;: alloc\-dealloc\-mismatch \(INVALID vs free\) on 0x60400000c1f0
&nbsp;    \#0 0x7f379aace527 in \_\_interceptor\_free \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.1\+0x54527\)
&nbsp;    \#1 0x73e7ab in Perl\_safesysfree /home/tony/dev/perl/git/perl/util\.c&#8203;:388
&nbsp;    \#2 0x83a2d7 in Perl\_vivify\_ref /home/tony/dev/perl/git/perl/pp\_hot\.c&#8203;:4362
&nbsp;    \#3 0x923c4a in Perl\_pp\_rv2sv /home/tony/dev/perl/git/perl/pp\.c&#8203;:404
&nbsp;    \#4 0x73a813 in Perl\_runops\_debug /home/tony/dev/perl/git/perl/dump\.c&#8203;:2260
&nbsp;    \#5 0x4be8d3 in S\_run\_body /home/tony/dev/perl/git/perl/perl\.c&#8203;:2526
&nbsp;    \#6 0x4bcc5e in perl\_run /home/tony/dev/perl/git/perl/perl\.c&#8203;:2449
&nbsp;    \#7 0x41fa8b in main /home/tony/dev/perl/git/perl/perlmain\.c&#8203;:123
&nbsp;    \#8 0x7f379997cb44 in \_\_libc\_start\_main \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x21b44\)
&nbsp;    \#9 0x41f808 \(/home/tony/dev/perl/git/perl/perl\+0x41f808\)

0x60400000c1f0 is located 32 bytes inside of 39\-byte region \[0x60400000c1d0\,0x60400000c1f7\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x7f379aace73f in malloc \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.1\+0x5473f\)
&nbsp;    \#1 0x73e0ee in Perl\_safesysmalloc /home/tony/dev/perl/git/perl/util\.c&#8203;:153
&nbsp;    \#2 0x7e33f7 in S\_share\_hek\_flags /home/tony/dev/perl/git/perl/hv\.c&#8203;:3030
&nbsp;    \#3 0x7c95b7 in Perl\_hv\_common /home/tony/dev/perl/git/perl/hv\.c&#8203;:819
&nbsp;    \#4 0x7c680c in Perl\_hv\_common\_key\_len /home/tony/dev/perl/git/perl/hv\.c&#8203;:333
&nbsp;    \#5 0x507d20 in Perl\_gv\_fetchpvn\_flags /home/tony/dev/perl/git/perl/gv\.c&#8203;:2336
&nbsp;    \#6 0x47876c in Perl\_newXS\_len\_flags /home/tony/dev/perl/git/perl/op\.c&#8203;:9134
&nbsp;    \#7 0x47854b in Perl\_newXS\_flags /home/tony/dev/perl/git/perl/op\.c&#8203;:9108
&nbsp;    \#8 0xb7ebf4 in Perl\_boot\_core\_UNIVERSAL /home/tony/dev/perl/git/perl/universal\.c&#8203;:1084
&nbsp;    \#9 0x4babf9 in S\_parse\_body /home/tony/dev/perl/git/perl/perl\.c&#8203;:2274
&nbsp;    \#10 0x4b7f50 in perl\_parse /home/tony/dev/perl/git/perl/perl\.c&#8203;:1689
&nbsp;    \#11 0x41fa73 in main /home/tony/dev/perl/git/perl/perlmain\.c&#8203;:121
&nbsp;    \#12 0x7f379997cb44 in \_\_libc\_start\_main \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x21b44\)

SUMMARY&#8203;: AddressSanitizer&#8203;: alloc\-dealloc\-mismatch ??&#8203;:0 \_\_interceptor\_free
==18728==HINT&#8203;: if you don't care about these warnings you may set ASAN\_OPTIONS=alloc\_dealloc\_mismatch=0
==18728==ABORTING

\(which is new to me\)

and&#8203;:

$ \./perl \.\./130336b\.pl 
=================================================================
==18686==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address 0x62100001c8f0 at pc 0x839aa3 bp 0x7ffe33854990 sp 0x7ffe33854988
READ of size 8 at 0x62100001c8f0 thread T0
&nbsp;    \#0 0x839aa2 in Perl\_vivify\_ref /home/tony/dev/perl/git/perl/pp\_hot\.c&#8203;:4362
&nbsp;    \#1 0x923c4a in Perl\_pp\_rv2sv /home/tony/dev/perl/git/perl/pp\.c&#8203;:404
&nbsp;    \#2 0x73a813 in Perl\_runops\_debug /home/tony/dev/perl/git/perl/dump\.c&#8203;:2260
&nbsp;    \#3 0x4be8d3 in S\_run\_body /home/tony/dev/perl/git/perl/perl\.c&#8203;:2526
&nbsp;    \#4 0x4bcc5e in perl\_run /home/tony/dev/perl/git/perl/perl\.c&#8203;:2449
&nbsp;    \#5 0x41fa8b in main /home/tony/dev/perl/git/perl/perlmain\.c&#8203;:123
&nbsp;    \#6 0x7fcdfab1db44 in \_\_libc\_start\_main \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x21b44\)
&nbsp;    \#7 0x41f808 \(/home/tony/dev/perl/git/perl/perl\+0x41f808\)

0x62100001c8f0 is located 0 bytes to the right of 4080\-byte region \[0x62100001b900\,0x62100001c8f0\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x7fcdfbc6f73f in malloc \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.1\+0x5473f\)
&nbsp;    \#1 0x73e0ee in Perl\_safesysmalloc /home/tony/dev/perl/git/perl/util\.c&#8203;:153
&nbsp;    \#2 0x8434f3 in S\_more\_sv /home/tony/dev/perl/git/perl/sv\.c&#8203;:307
&nbsp;    \#3 0x8e3004 in Perl\_newSVpvn /home/tony/dev/perl/git/perl/sv\.c&#8203;:9353
&nbsp;    \#4 0x4aff1e in perl\_construct /home/tony/dev/perl/git/perl/perl\.c&#8203;:272
&nbsp;    \#5 0x41f9d1 in main /home/tony/dev/perl/git/perl/perlmain\.c&#8203;:117
&nbsp;    \#6 0x7fcdfab1db44 in \_\_libc\_start\_main \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x21b44\)

SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow /home/tony/dev/perl/git/perl/pp\_hot\.c&#8203;:4362 Perl\_vivify\_ref
Shadow bytes around the buggy address&#8203;:
&nbsp;  0x0c427fffb8c0&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c427fffb8d0&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c427fffb8e0&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c427fffb8f0&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c427fffb900&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c427fffb910&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00\[fa\]fa
&nbsp;  0x0c427fffb920&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c427fffb930&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c427fffb940&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c427fffb950&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c427fffb960&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend \(one shadow byte represents 8 application bytes\)&#8203;:
&nbsp;  Addressable&#8203;:           00
&nbsp;  Partially addressable&#8203;: 01 02 03 04 05 06 07 
&nbsp;  Heap left redzone&#8203;:       fa
&nbsp;  Heap right redzone&#8203;:      fb
&nbsp;  Freed heap region&#8203;:       fd
&nbsp;  Stack left redzone&#8203;:      f1
&nbsp;  Stack mid redzone&#8203;:       f2
&nbsp;  Stack right redzone&#8203;:     f3
&nbsp;  Stack partial redzone&#8203;:   f4
&nbsp;  Stack after return&#8203;:      f5
&nbsp;  Stack use after scope&#8203;:   f8
&nbsp;  Global redzone&#8203;:          f9
&nbsp;  Global init order&#8203;:       f6
&nbsp;  Poisoned by user&#8203;:        f7
&nbsp;  Contiguous container OOB&#8203;:fc
&nbsp;  ASan internal&#8203;:           fe
==18686==ABORTING

which looks familiar\.

and occasionally no error at all\.

This seemds to be controlled by the hash order&#8203;:

$ PERL\_HASH\_SEED=0x00 \./perl \.\./130336\.pl 
=================================================================
==18920==ERROR&#8203;: AddressSanitizer&#8203;: alloc\-dealloc\-mismatch \(INVALID vs free\) on 0x60400000c270

$ PERL\_HASH\_SEED=0x01 \./perl \.\./130336\.pl 
perl&#8203;: sv\.c&#8203;:6540&#8203;: Perl\_sv\_clear&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) \!= \(svtype\)0xff' failed\.
Aborted

$ PERL\_HASH\_SEED=0x02 \./perl \.\./130336\.pl 
=================================================================
==18950==ERROR&#8203;: AddressSanitizer&#8203;: attempting double\-free on 0x60400000ae70 in thread T0&#8203;:
\.\.\.

$ PERL\_HASH\_SEED=0x07 \./perl \.\./130336\.pl 
=================================================================
==18984==ERROR&#8203;: AddressSanitizer&#8203;: attempting free on address which was not malloc\(\)\-ed&#8203;: 0x60400000adf0 in thread T0

Simplifies&#8203;:

$ PERL\_HASH\_SEED=0x01 \./perl \-e 'map%$\_= %\_= %$\_\,%&#8203;::'
=================================================================
==19013==ERROR&#8203;: AddressSanitizer&#8203;: attempting free on address which was not malloc\(\)\-ed&#8203;: 0x60400000ac30 in thread T0
&nbsp;    \#0 0x7f19400b6527 in \_\_interceptor\_free \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.1\+0x54527\)
&nbsp;    \#1 0x73e7ab in Perl\_safesysfree /home/tony/dev/perl/git/perl/util\.c&#8203;:388
&nbsp;    \#2 0x83a2d7 in Perl\_vivify\_ref /home/tony/dev/perl/git/perl/pp\_hot\.c&#8203;:4362
&nbsp;    \#3 0x923c4a in Perl\_pp\_rv2sv /home/tony/dev/perl/git/perl/pp\.c&#8203;:404
&nbsp;    \#4 0x73a813 in Perl\_runops\_debug /home/tony/dev/perl/git/perl/dump\.c&#8203;:2260
&nbsp;    \#5 0x4be8d3 in S\_run\_body /home/tony/dev/perl/git/perl/perl\.c&#8203;:2526
&nbsp;    \#6 0x4bcc5e in perl\_run /home/tony/dev/perl/git/perl/perl\.c&#8203;:2449
&nbsp;    \#7 0x41fa8b in main /home/tony/dev/perl/git/perl/perlmain\.c&#8203;:123
&nbsp;    \#8 0x7f193ef64b44 in \_\_libc\_start\_main \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x21b44\)
&nbsp;    \#9 0x41f808 \(/home/tony/dev/perl/git/perl/perl\+0x41f808\)

0x60400000ac30 is located 32 bytes inside of 37\-byte region \[0x60400000ac10\,0x60400000ac35\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x7f19400b673f in malloc \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.1\+0x5473f\)
&nbsp;    \#1 0x73e0ee in Perl\_safesysmalloc /home/tony/dev/perl/git/perl/util\.c&#8203;:153
&nbsp;    \#2 0x7e33f7 in S\_share\_hek\_flags /home/tony/dev/perl/git/perl/hv\.c&#8203;:3030
&nbsp;    \#3 0x7c95b7 in Perl\_hv\_common /home/tony/dev/perl/git/perl/hv\.c&#8203;:819
&nbsp;    \#4 0x7c680c in Perl\_hv\_common\_key\_len /home/tony/dev/perl/git/perl/hv\.c&#8203;:333
&nbsp;    \#5 0x507d20 in Perl\_gv\_fetchpvn\_flags /home/tony/dev/perl/git/perl/gv\.c&#8203;:2336
&nbsp;    \#6 0x4d36b9 in S\_init\_postdump\_symbols /home/tony/dev/perl/git/perl/perl\.c&#8203;:4360
&nbsp;    \#7 0x4bac8b in S\_parse\_body /home/tony/dev/perl/git/perl/perl\.c&#8203;:2299
&nbsp;    \#8 0x4b7f50 in perl\_parse /home/tony/dev/perl/git/perl/perl\.c&#8203;:1689
&nbsp;    \#9 0x41fa73 in main /home/tony/dev/perl/git/perl/perlmain\.c&#8203;:121
&nbsp;    \#10 0x7f193ef64b44 in \_\_libc\_start\_main \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x21b44\)

SUMMARY&#8203;: AddressSanitizer&#8203;: bad\-free ??&#8203;:0 \_\_interceptor\_free
==19013==ABORTING


Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @arc

I have a deterministic reduction to a double\-free\, omitting one of the assignments and one of the uses of the iteration variable\.

I get essentially the same trace regardless of what empty array or hash is on the rhs of the aassign\. I suspect this is a stack\-not\-refcounted issue\, tbh\.

$ \./miniperl \-e 'map %$\_ = %\_\, \*&#8203;::\, $&#8203;::\{Internals&#8203;::\}'
=================================================================
==59124==ERROR&#8203;: AddressSanitizer&#8203;: attempting double\-free on 0x611000009780 in thread T0&#8203;:
&nbsp;    \#0 0x10c868939 in wrap\_free \(libclang\_rt\.asan\_osx\_dynamic\.dylib\+0x46939\)
&nbsp;    \#1 0x10c23a66e in Perl\_vivify\_ref pp\_hot\.c&#8203;:4364
&nbsp;    \#2 0x10c2edfa4 in Perl\_pp\_rv2sv pp\.c&#8203;:404
&nbsp;    \#3 0x10c1c0c46 in Perl\_runops\_debug dump\.c&#8203;:2444
&nbsp;    \#4 0x10c0107f5 in perl\_run perl\.c&#8203;:2528
&nbsp;    \#5 0x10c51fe01 in main miniperlmain\.c&#8203;:129
&nbsp;    \#6 0x7fff928695fc in start \(libdyld\.dylib\+0x35fc\)
&nbsp;    \#7 0x2  \(\<unknown module>\)

0x611000009780 is located 0 bytes inside of 248\-byte region \[0x611000009780\,0x611000009878\)
freed by thread T0 here&#8203;:
&nbsp;    \#0 0x10c868939 in wrap\_free \(libclang\_rt\.asan\_osx\_dynamic\.dylib\+0x46939\)
&nbsp;    \#1 0x10c2aca40 in Perl\_sv\_clear sv\.c&#8203;:6770
&nbsp;    \#2 0x10c2b0d1f in Perl\_sv\_free2 sv\.c&#8203;:7072
&nbsp;    \#3 0x10c34b83a in Perl\_free\_tmps \.inline\.h&#8203;:200
&nbsp;    \#4 0x10c00c847 in S\_parse\_body perl\.c&#8203;:2401
&nbsp;    \#5 0x10c006c43 in perl\_parse perl\.c&#8203;:1691
&nbsp;    \#6 0x10c51fdf5 in main miniperlmain\.c&#8203;:127
&nbsp;    \#7 0x7fff928695fc in start \(libdyld\.dylib\+0x35fc\)
&nbsp;    \#8 0x2  \(\<unknown module>\)

previously allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x10c868b07 in wrap\_realloc \(libclang\_rt\.asan\_osx\_dynamic\.dylib\+0x46b07\)
&nbsp;    \#1 0x10c1c4659 in Perl\_safesysrealloc util\.c&#8203;:274
&nbsp;    \#2 0x10c26ebb8 in Perl\_sv\_grow sv\.c&#8203;:1598
&nbsp;    \#3 0x10c2d9ab9 in Perl\_sv\_vcatpvfn\_flags sv\.c&#8203;:13026
&nbsp;    \#4 0x10c2c5219 in Perl\_sv\_vsetpvfn sv\.c&#8203;:10945
&nbsp;    \#5 0x10c1c8846 in Perl\_vform util\.c&#8203;:1364
&nbsp;    \#6 0x10c1c875f in Perl\_form util\.c&#8203;:1354
&nbsp;    \#7 0x10c0098c1 in S\_parse\_body perl\.c&#8203;:3753
&nbsp;    \#8 0x10c006c43 in perl\_parse perl\.c&#8203;:1691
&nbsp;    \#9 0x10c51fdf5 in main miniperlmain\.c&#8203;:127
&nbsp;    \#10 0x7fff928695fc in start \(libdyld\.dylib\+0x35fc\)
&nbsp;    \#11 0x2  \(\<unknown module>\)

SUMMARY&#8203;: AddressSanitizer&#8203;: double\-free \(libclang\_rt\.asan\_osx\_dynamic\.dylib\+0x46939\) in wrap\_free
==59124==ABORTING
Abort trap&#8203;: 6

\-\- 
Aaron Crane \*\* http&#8203;://aaroncrane\.co\.uk/

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, Jan 28\, 2017 at 09&#8203;:01&#8203;:10AM \-0800\, Aaron Crane via RT wrote&#8203;:
> I have a deterministic reduction to a double\-free\, omitting one of the
> assignments and one of the uses of the iteration variable\.
> 
> I get essentially the same trace regardless of what empty array or hash
> is on the rhs of the aassign\. I suspect this is a stack\-not\-refcounted
> issue\, tbh\.
> 
> $ \./miniperl \-e 'map %$\_ = %\_\, \*&#8203;::\, $&#8203;::\{Internals&#8203;::\}'

The first part is equivalent to

&nbsp;    map %$\_ = \(\)\, \*&#8203;::

which aliases $\_ to \*&#8203;::\, then the hash %$\_ is actually %&#8203;::\, and assigning
\(\) to it empties the main stash\. After that\, anything left on the stack
which gets processed\, such as $&#8203;::\{Internals&#8203;::\}\, has already been freed\.

So it is indeed another stack\-not\-refcounted bug\.

As with \#130321 and \#130332\, \, I propose that the ticket be moved to the
public queue\, added to the 'stack not ref counted' meta ticket\, then
ignored until such time as we fix that wider issue\.

\-\- 
Modern art&#8203;:
&nbsp;    "That's easy\, I could have done that\!"
&nbsp;    "Ah\, but you didn't\!"

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Feb 20\, 2017 at 03&#8203;:14&#8203;:35PM \+0000\, Dave Mitchell wrote&#8203;:
> On Sat\, Jan 28\, 2017 at 09&#8203;:01&#8203;:10AM \-0800\, Aaron Crane via RT wrote&#8203;:
> > I have a deterministic reduction to a double\-free\, omitting one of the
> > assignments and one of the uses of the iteration variable\.
> > 
> > I get essentially the same trace regardless of what empty array or hash
> > is on the rhs of the aassign\. I suspect this is a stack\-not\-refcounted
> > issue\, tbh\.
> > 
> > $ \./miniperl \-e 'map %$\_ = %\_\, \*&#8203;::\, $&#8203;::\{Internals&#8203;::\}'
> 
> The first part is equivalent to
> 
>     map %$\_ = \(\)\, \*&#8203;::
> 
> which aliases $\_ to \*&#8203;::\, then the hash %$\_ is actually %&#8203;::\, and assigning
> \(\) to it empties the main stash\. After that\, anything left on the stack
> which gets processed\, such as $&#8203;::\{Internals&#8203;::\}\, has already been freed\.
> 
> So it is indeed another stack\-not\-refcounted bug\.
> 
> As with \#130321 and \#130332\, \, I propose that the ticket be moved to the
> public queue\, added to the 'stack not ref counted' meta ticket\, then
> ignored until such time as we fix that wider issue\.

which I am now doing\.


\-\- 
In England there is a special word which means the last sunshine
of the summer\. That word is "spring"\.
