### ISSUE TITLE
Coredump in Perl_sv_cmp_flags

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15807]
Migrated from [rt.perl.org#130559](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130559) (status was 'open')

Searchable as RT130559$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.25\.8\-207\-gcbe2fc5001 built with afl and run
under libdislocator\, I found the following program

@&#8203;0=s//0/;
@&#8203;0=sort\(0\,@&#8203;t00=0\,@&#8203;t00=0\,@&#8203;0=s///\);

to crash\. This is a regression in blead since v5\.24\. Bisect points to

commit 8b0c3377906a6f991cd6c21a674bf9561d85e3cb
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Wed Oct 5 10&#8203;:10&#8203;:56 2016 \+0100

&nbsp;    Better optimise array and hash assignment

&nbsp;    \[perl \#127999\] Slowdown in split \+ list assign

GDB info about the crash location&#8203;:

\(gdb\) bt
\#0  \_\_memcmp\_sse4\_1 \(\) at \.\./sysdeps/x86\_64/multiarch/memcmp\-sse4\.S&#8203;:62
\#1  0x00007f26ea232fff in Perl\_sv\_cmp\_flags \(sv1=0x7f26ea9a7e88\,
sv2=0x7f26ea9a74e0\, flags=2\) at sv\.c&#8203;:7954
\#2  0x00007f26ea232bbd in Perl\_sv\_cmp \(sv1=0x7f26ea9a7e88\,
sv2=0x7f26ea9a74e0\) at sv\.c&#8203;:7902
\#3  0x00007f26ea3842c1 in dynprep \(list1=0x7f26ea995b58\,
list2=0x7ffd596044d0\, nmemb=4\, cmp=0x7f26ea232b95 \<Perl\_sv\_cmp>\) at
pp\_sort\.c&#8203;:197
\#4  0x00007f26ea384741 in S\_mergesortsv \(base=0x7f26ea995b58\, nmemb=4\,
cmp=0x7f26ea232b95 \<Perl\_sv\_cmp>\, flags=0\) at pp\_sort\.c&#8203;:379
\#5  0x00007f26ea386bfa in Perl\_sortsv\_flags \(array=0x7f26ea995b58\,
nmemb=4\, cmp=0x7f26ea232b95 \<Perl\_sv\_cmp>\, flags=0\) at pp\_sort\.c&#8203;:1464
\#6  0x00007f26ea389279 in Perl\_pp\_sort \(\) at pp\_sort\.c&#8203;:1713
\#7  0x00007f26ea189b57 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2260
\#8  0x00007f26ea0840fd in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2528
\#9  0x00007f26ea08367b in perl\_run \(my\_perl=0x7f26ea991010\) at perl\.c&#8203;:2451
\#10 0x00007f26ea03ed3e in main \(argc=2\, argv=0x7ffd59605148\,
env=0x7ffd59605160\) at perlmain\.c&#8203;:123
\(gdb\) f 1
\#1  0x00007f26ea232fff in Perl\_sv\_cmp\_flags \(sv1=0x7f26ea9a7e88\,
sv2=0x7f26ea9a74e0\, flags=2\) at sv\.c&#8203;:7954
7954                const I32 retval = memcmp\(\(const void\*\)pv1\,
\(gdb\) l
7949            STRLEN shortest\_len = cur1 \< cur2 ? cur1 : cur2;
7950
7951    \#ifdef EBCDIC
7952            if \(\! DO\_UTF8\(sv1\)\) \{
7953    \#endif
7954                const I32 retval = memcmp\(\(const void\*\)pv1\,
7955                                          \(const void\*\)pv2\,
7956                                          shortest\_len\);
7957                if \(retval\) \{
7958                    cmp = retval \< 0 ? \-1 : 1;
\(gdb\) p pv2
$1 = 0x0

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl 5.25.9:

Configured by root at Sat Jan 14 02:25:05 MSK 2017.

Summary of my perl5 (revision 5 version 25 subversion 9) configuration:
  Commit id: cbe2fc5001aa59cdc73e04cc35e097a2ecfbeec0
  Platform:
    osname=linux
    osvers=3.16.0-4-amd64
    archname=x86_64-linux
    uname='linux dorothy 3.16.0-4-amd64 #1 smp debian 3.16.36-1+deb8u2
(2016-10-19) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING -Dcc=afl-clang-fast
-Doptimize=-O0 -g -ggdb3'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    bincompat5005=undef
  Compiler:
    cc='afl-clang-fast'
    ccflags ='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O0 -g -ggdb3'
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Clang 3.9.1 (tags/RELEASE_391/rc2)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='afl-clang-fast'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/lib
/usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu
/lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.24.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.24'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O0 -g -ggdb3 -L/usr/local/lib -fstack-protector-strong'



@INC for perl 5.25.9:
    lib
    /usr/local/lib/perl5/site_perl/5.25.9/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.25.9
    /usr/local/lib/perl5/5.25.9/x86_64-linux
    /usr/local/lib/perl5/5.25.9


Environment for perl 5.25.9:
    HOME=/home/afl
    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    PERLBREW_BASHRC_VERSION=0.78
    PERLBREW_HOME=/home/afl/.perlbrew
    PERLBREW_MANPATH=/home/afl/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/home/afl/perlbrew
    PERLBREW_VERSION=0.78
    PERL_BADLANG (unset)
    SHELL=/usr/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @tonycoz

On Sat\, 14 Jan 2017 14&#8203;:44&#8203;:54 \-0800\, randir wrote&#8203;:
> While fuzzing perl v5\.25\.8\-207\-gcbe2fc5001 built with afl and run
> under libdislocator\, I found the following program
> 
> @&#8203;0=s//0/;
> @&#8203;0=sort\(0\,@&#8203;t00=0\,@&#8203;t00=0\,@&#8203;0=s///\);
> 
> to crash\. This is a regression in blead since v5\.24\. Bisect points to
> 
> commit 8b0c3377906a6f991cd6c21a674bf9561d85e3cb
> Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
> Date&#8203;:   Wed Oct 5 10&#8203;:10&#8203;:56 2016 \+0100
> 
> Better optimise array and hash assignment

The crash is new\, unfortunately the brokenness isn't&#8203;:

 $ \./miniperl \-le '@&#8203;0=s//0/; @&#8203;0=sort\(2\,@&#8203;t00=3\,@&#8203;t00=4\,@&#8203;0=s///\); print join\("\,"\, @&#8203;0\)'
 1\,2\,4\,4
 $ git describe
 v5\.25\.6\-77\-gbeb8db2

which is immediately before Dave's commit\.

So this at base is a stack\-not\-refcounted issue\, but why is pv2 NULL?

I tried a watchpoint on the address of the pv in the SV head that was failing&#8203;:

\(gdb\) watch \*\(IV\*\)0x621000010990
Hardware watchpoint 1&#8203;: \*\(IV\*\)0x621000010990
\(gdb\) r
Starting program&#8203;: /home/tony/dev/perl/git/perl/miniperl \-e @&#8203;0=s//0/\\;\\ @&#8203;0=sort\\\(3\,@&#8203;t00=1\,@&#8203;t00=2\,@&#8203;0=s///\\\)
\.\.\.
\(gdb\) c
Continuing\.
Hardware watchpoint 1&#8203;: \*\(IV\*\)0x621000010990

Old value = 105690555275376
New value = 0
Perl\_pp\_subst \(\) at pp\_hot\.c&#8203;:3435
3435                SPAGAIN;
\(gdb\) c
Continuing\.

Program received signal SIGSEGV\, Segmentation fault\.
\_\_memcmp\_ssse3 \(\) at \.\./sysdeps/x86\_64/multiarch/memcmp\-ssse3\.S&#8203;:1810
1810    \.\./sysdeps/x86\_64/multiarch/memcmp\-ssse3\.S&#8203;: No such file or directory\.
\(gdb\) up 2
\#2  0x00000000008b4c5e in Perl\_sv\_cmp\_flags \(sv1=0x6210000113e8\, 
&nbsp;    sv2=0x621000010980\, flags=2\) at sv\.c&#8203;:7889
7889                const I32 retval = memcmp\(\(const void\*\)pv1\,
\(gdb\) p &\(sv2\->sv\_u\)
$4 = \(union \{\.\.\.\} \*\) 0x621000010990

So that SV has its PV being set to zero by this code&#8203;:

&nbsp;        SvCUR\_set\(TARG\, SvCUR\(dstr\)\);
&nbsp;        SvLEN\_set\(TARG\, SvLEN\(dstr\)\);
&nbsp;        SvFLAGS\(TARG\) |= SvUTF8\(dstr\);
&nbsp;        SvPV\_set\(dstr\, NULL\); \<\<== here

&nbsp;        SPAGAIN;

The dstr SV is a temp and normally shouldn't be in use anywhere else\,
but due to the stack refcounting bug it's re\-using the SV slot of an SV on the stack\.

When Perl\_sv\_cmp\(\) then SvPV\(\)'s that SV on the stack it receives the NULL pointer and we crash\.

Which might be better than returning the rubbish it returned before\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'
