### ISSUE TITLE
perl.c:528: perl_destruct: Assertion `PL_scopestack_ix == 1' failed

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15814]
Migrated from [rt.perl.org#130585](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130585) (status was 'pending release')

Searchable as RT130585$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.25\.8\-216\-gfbceb79751 built with afl and run
under libdislocator\, I found the following program

qr\!@&#8203;\{s\{0\}\)\(?\{\!

to cause an assertion failure\, even when run under \-c for a syntax
check\. This is a regression between v5\.16\.3 and v5\.18\.0\, bisect points
to

491453ba443e114f751f325a4734b3d07b897606 is the first bad commit
commit 491453ba443e114f751f325a4734b3d07b897606
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Wed Apr 17 17&#8203;:51&#8203;:16 2013 \+0100

&nbsp;    Handle /@&#8203;a/ array expansion within regex engine

&nbsp;    Previously /a@&#8203;\{b\}c/ would be parsed as

&nbsp;        regcomp\('a'\, join\($"\, @&#8203;b\)\, 'c'\)

&nbsp;    This means that the array was flattened and its contents stringified before
&nbsp;    hitting the regex engine\.

&nbsp;    Change it so that it is parsed as

&nbsp;        regcomp\('a'\, @&#8203;b\, 'c'\)

&nbsp;    \(but where the array isn't flattened\, but rather just the AV itself is
&nbsp;    pushed onto the stack\, c\.f\. push @&#8203;b\, \.\.\.\.\)\.

&nbsp;    This means that the regex engine itself can process any qr// objects
&nbsp;    within the array\, and correctly extract out any previously\-compiled
&nbsp;    code blocks \(thus preserving the correct closure behaviour\)\. This is
&nbsp;    an improvement on 5\.16\.x behaviour\, and brings it into line with the
&nbsp;    newish 5\.17\.x behaviour for \*scalar\* vars where they happen to hold
&nbsp;    regex objects\.

&nbsp;    It also fixes a regression from 5\.16\.x\, which meant that you suddenly
&nbsp;    needed a 'use re eval' in scope if any of the elements of the array were
&nbsp;    a qr// object with code blocks \(RT \#115004\)\.

GDB info about the crash location&#8203;:

\(gdb\) bt
\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:58
\#1  0x00007f2d6ecf940a in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007f2d6ecf0e47 in \_\_assert\_fail\_base \(fmt=\<optimized out>\,
assertion=assertion@&#8203;entry=0x7f2d703af467 "PL\_scopestack\_ix == 1"\,
&nbsp;    file=file@&#8203;entry=0x7f2d703af370 "perl\.c"\, line=line@&#8203;entry=571\,
function=function@&#8203;entry=0x7f2d703b1a08 \<\_\_PRETTY\_FUNCTION\_\_\.14855>
"perl\_destruct"\)
&nbsp;    at assert\.c&#8203;:92
\#3  0x00007f2d6ecf0ef2 in \_\_GI\_\_\_assert\_fail \(assertion=0x7f2d703af467
"PL\_scopestack\_ix == 1"\, file=0x7f2d703af370 "perl\.c"\, line=571\,
&nbsp;    function=0x7f2d703b1a08 \<\_\_PRETTY\_FUNCTION\_\_\.14855>
"perl\_destruct"\) at assert\.c&#8203;:101
\#4  0x00007f2d7006fff7 in perl\_destruct \(my\_perl=0x7f2d721f4010\) at perl\.c&#8203;:571
\#5  0x00007f2d7002fdc7 in main \(argc=2\, argv=0x7ffcc6177818\,
env=0x7ffcc6177830\) at perlmain\.c&#8203;:134
\(gdb\) f 4
\#4  0x00007f2d7006fff7 in perl\_destruct \(my\_perl=0x7f2d721f4010\) at perl\.c&#8203;:571
571         assert\(PL\_scopestack\_ix == 1\);
\(gdb\) p PL\_scopestack\_ix
$1 = 2

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.25.9:

Configured by root at Sat Jan 14 02:25:05 MSK 2017.

Summary of my perl5 (revision 5 version 25 subversion 9) configuration:
  Commit id: cbe2fc5001aa59cdc73e04cc35e097a2ecfbeec0
  Platform:
    osname=linux
    osvers=3.16.0-4-amd64
    archname=x86_64-linux
    uname='linux dorothy 3.16.0-4-amd64 #1 smp debian 3.16.36-1+deb8u2
(2016-10-19) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING -Dcc=afl-clang-fast
-Doptimize=-O0 -g -ggdb3'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    bincompat5005=undef
  Compiler:
    cc='afl-clang-fast'
    ccflags ='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O0 -g -ggdb3'
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Clang 3.9.1 (tags/RELEASE_391/rc2)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='afl-clang-fast'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/lib
/usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu
/lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.24.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.24'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O0 -g -ggdb3 -L/usr/local/lib -fstack-protector-strong'



@INC for perl 5.25.9:
    lib
    /usr/local/lib/perl5/site_perl/5.25.9/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.25.9
    /usr/local/lib/perl5/5.25.9/x86_64-linux
    /usr/local/lib/perl5/5.25.9


Environment for perl 5.25.9:
    HOME=/home/afl
    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    PERLBREW_BASHRC_VERSION=0.78
    PERLBREW_HOME=/home/afl/.perlbrew
    PERLBREW_MANPATH=/home/afl/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/home/afl/perlbrew
    PERLBREW_VERSION=0.78
    PERL_BADLANG (unset)
    SHELL=/usr/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @hvds

On Wed\, 18 Jan 2017 17&#8203;:08&#8203;:36 \-0800\, randir wrote&#8203;:
> While fuzzing perl v5\.25\.8\-216\-gfbceb79751 built with afl and run
> under libdislocator\, I found the following program
> 
> qr\!@&#8203;\{s\{0\}\)\(?\{\!
> 
> to cause an assertion failure\, even when run under \-c for a syntax
> check\. This is a regression between v5\.16\.3 and v5\.18\.0\, bisect points
> to
> 
> 491453ba443e114f751f325a4734b3d07b897606 is the first bad commit
> commit 491453ba443e114f751f325a4734b3d07b897606
> Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
> Date&#8203;:   Wed Apr 17 17&#8203;:51&#8203;:16 2013 \+0100
> 
> Handle /@&#8203;a/ array expansion within regex engine
\[snip\]
> \#3  0x00007f2d6ecf0ef2 in \_\_GI\_\_\_assert\_fail \(assertion=0x7f2d703af467
> "PL\_scopestack\_ix == 1"\, file=0x7f2d703af370 "perl\.c"\, line=571\,
>     function=0x7f2d703b1a08 \<\_\_PRETTY\_FUNCTION\_\_\.14855>
> "perl\_destruct"\) at assert\.c&#8203;:101
> \#4  0x00007f2d7006fff7 in perl\_destruct \(my\_perl=0x7f2d721f4010\) at
> perl\.c&#8203;:571
> \#5  0x00007f2d7002fdc7 in main \(argc=2\, argv=0x7ffcc6177818\,
> env=0x7ffcc6177830\) at perlmain\.c&#8203;:134
> \(gdb\) f 4
> \#4  0x00007f2d7006fff7 in perl\_destruct \(my\_perl=0x7f2d721f4010\) at
> perl\.c&#8203;:571
> 571         assert\(PL\_scopestack\_ix == 1\);
> \(gdb\) p PL\_scopestack\_ix
> $1 = 2

The scopestack imbalance here occurs because we call sublex\_start\(\) but never a corresponding sublex\_done\(\)\. I don't currently have a clue what's intended to ensure we will reach sublex\_done\, but I'll try to make some more progress if nobody else jumps in\.

The only part of 491453ba44 that gets hit by \./miniperl \-ce 'qr\!@&#8203;\{s\{0\}\)\(?\{\!' is the toke\.c chunk causing PL\_lex\_dojoin to become FALSE instead of TRUE\.

Hugo

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Fri\, 20 Jan 2017 06&#8203;:43&#8203;:12 \-0800\, hv wrote&#8203;:
> On Wed\, 18 Jan 2017 17&#8203;:08&#8203;:36 \-0800\, randir wrote&#8203;:
> > While fuzzing perl v5\.25\.8\-216\-gfbceb79751 built with afl and run
> > under libdislocator\, I found the following program
> >
> > qr\!@&#8203;\{s\{0\}\)\(?\{\!
> >
> > to cause an assertion failure\, even when run under \-c for a syntax
> > check\. This is a regression between v5\.16\.3 and v5\.18\.0\, bisect
> > points
> > to
> >
> > 491453ba443e114f751f325a4734b3d07b897606 is the first bad commit
> > commit 491453ba443e114f751f325a4734b3d07b897606
> > Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
> > Date&#8203;:   Wed Apr 17 17&#8203;:51&#8203;:16 2013 \+0100
> >
> > Handle /@&#8203;a/ array expansion within regex engine
> \[snip\]
> > \#3  0x00007f2d6ecf0ef2 in \_\_GI\_\_\_assert\_fail
> > \(assertion=0x7f2d703af467
> > "PL\_scopestack\_ix == 1"\, file=0x7f2d703af370 "perl\.c"\, line=571\,
> >     function=0x7f2d703b1a08 \<\_\_PRETTY\_FUNCTION\_\_\.14855>
> > "perl\_destruct"\) at assert\.c&#8203;:101
> > \#4  0x00007f2d7006fff7 in perl\_destruct \(my\_perl=0x7f2d721f4010\) at
> > perl\.c&#8203;:571
> > \#5  0x00007f2d7002fdc7 in main \(argc=2\, argv=0x7ffcc6177818\,
> > env=0x7ffcc6177830\) at perlmain\.c&#8203;:134
> > \(gdb\) f 4
> > \#4  0x00007f2d7006fff7 in perl\_destruct \(my\_perl=0x7f2d721f4010\) at
> > perl\.c&#8203;:571
> > 571         assert\(PL\_scopestack\_ix == 1\);
> > \(gdb\) p PL\_scopestack\_ix
> > $1 = 2
> 
> The scopestack imbalance here occurs because we call sublex\_start\(\)
> but never a corresponding sublex\_done\(\)\. I don't currently have a clue
> what's intended to ensure we will reach sublex\_done\, but I'll try to
> make some more progress if nobody else jumps in\.
> 
> The only part of 491453ba44 that gets hit by \./miniperl \-ce
> 'qr\!@&#8203;\{s\{0\}\)\(?\{\!' is the toke\.c chunk causing PL\_lex\_dojoin to become
> FALSE instead of TRUE\.

The closing \) is confusing the parser\.

Patch which \*might\* fix it \(passes all tests in a DEBUGGING build\) attached\.

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

[0001-prevent-a-spurious-in-a-subparse-confusing-the-parse.patch](https://rt-archive.perl.org/perl5/Ticket/Attachment/1612416/832955/0001-prevent-a-spurious-in-a-subparse-confusing-the-parse.patch)

**Comment by p5pRT** [comment]
### From @hvds

On Mon\, 11 Feb 2019 21&#8203;:32&#8203;:43 \-0800\, tonyc wrote&#8203;:
> On Fri\, 20 Jan 2017 06&#8203;:43&#8203;:12 \-0800\, hv wrote&#8203;:
> > The scopestack imbalance here occurs because we call sublex\_start\(\)
> > but never a corresponding sublex\_done\(\)\.
\[\.\.\.\]
> The closing \) is confusing the parser\.
> 
> Patch which \*might\* fix it \(passes all tests in a DEBUGGING build\) attached\.

It looks credible to me\, and a good solution\. What are your concerns about it?

I know very little about the grammar\, but I'm curious why "FUNC SUBLEXSTART optexpr SUBLEXEND" is in 'term' rather than next to "FUNC '\(' optexpr '\)'" in 'listop' \- I'm assuming the cases hitting the former with the patch would previously have hit the latter\.

Is it possible to construct an additional croak/toke test for the \\U case\, or does the means of construction imply it cannot trigger failure the same way?

Hugo

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue\, 12 Feb 2019 01&#8203;:40&#8203;:32 \-0800\, hv wrote&#8203;:
> On Mon\, 11 Feb 2019 21&#8203;:32&#8203;:43 \-0800\, tonyc wrote&#8203;:
> > On Fri\, 20 Jan 2017 06&#8203;:43&#8203;:12 \-0800\, hv wrote&#8203;:
> > > The scopestack imbalance here occurs because we call sublex\_start\(\)
> > > but never a corresponding sublex\_done\(\)\.
> \[\.\.\.\]
> > The closing \) is confusing the parser\.
> >
> > Patch which \*might\* fix it \(passes all tests in a DEBUGGING build\)
> > attached\.
> 
> It looks credible to me\, and a good solution\. What are your concerns
> about it?

Mostly I was confused by the parser doing this&#8203;:

$ \./perl \-Ilib \-MO=Deparse \-e 'qq/@&#8203;\{s\{0\}\}/'
join $"\, @&#8203;s\{'0'\};
\-e syntax OK

while I expected the s\{0\} to be treated as the beginning of a s///\.

> I know very little about the grammar\, but I'm curious why "FUNC
> SUBLEXSTART optexpr SUBLEXEND" is in 'term' rather than next to "FUNC
> '\(' optexpr '\)'" in 'listop' \- I'm assuming the cases hitting the
> former with the patch would previously have hit the latter\.

This is from the history of the patch\.  Originally I had an extra production called sublexexpr that I'd added to term\, since first rule I converted to use the new tokens was the '\(' expr '\)' case for term\.

But that rule isn't used \- subparses always generate something like the FUNC\(\) call \(where FUNC might be op\_stringify for "\.\.\."\)\, and I ended up adding the FUNC rule to sublexexpr too\.

Testing found that the \{expr\} sublex token rule wasn't being used so I removed it\, and finally added the remaining rule to term\.  Which is probably the wrong place\.

> Is it possible to construct an additional croak/toke test for the \\U
> case\, or does the means of construction imply it cannot trigger
> failure the same way?

I think it can\, though I couldn't reproduce it with an unpatched blead\.

I've attached an updated patch that moves the rule\, and some attempts at making qq\(\) reproduce the problem\, though I couldn't make them crash\.

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

[0001-prevent-a-spurious-in-a-subparse-confusing-the-parse.patch](https://rt-archive.perl.org/perl5/Ticket/Attachment/1612564/832982/0001-prevent-a-spurious-in-a-subparse-confusing-the-parse.patch)

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue\, 12 Feb 2019 15&#8203;:03&#8203;:01 \-0800\, tonyc wrote&#8203;:
> On Tue\, 12 Feb 2019 01&#8203;:40&#8203;:32 \-0800\, hv wrote&#8203;:
> > On Mon\, 11 Feb 2019 21&#8203;:32&#8203;:43 \-0800\, tonyc wrote&#8203;:
> > > On Fri\, 20 Jan 2017 06&#8203;:43&#8203;:12 \-0800\, hv wrote&#8203;:
> > > > The scopestack imbalance here occurs because we call
> > > > sublex\_start\(\)
> > > > but never a corresponding sublex\_done\(\)\.
> > \[\.\.\.\]
> > > The closing \) is confusing the parser\.
> > >
> > > Patch which \*might\* fix it \(passes all tests in a DEBUGGING build\)
> > > attached\.
> >
> > It looks credible to me\, and a good solution\. What are your concerns
> > about it?
> 
> Mostly I was confused by the parser doing this&#8203;:
> 
> $ \./perl \-Ilib \-MO=Deparse \-e 'qq/@&#8203;\{s\{0\}\}/'
> join $"\, @&#8203;s\{'0'\};
> \-e syntax OK
> 
> while I expected the s\{0\} to be treated as the beginning of a s///\.
> 
> > I know very little about the grammar\, but I'm curious why "FUNC
> > SUBLEXSTART optexpr SUBLEXEND" is in 'term' rather than next to "FUNC
> > '\(' optexpr '\)'" in 'listop' \- I'm assuming the cases hitting the
> > former with the patch would previously have hit the latter\.
> 
> This is from the history of the patch\.  Originally I had an extra
> production called sublexexpr that I'd added to term\, since first rule
> I converted to use the new tokens was the '\(' expr '\)' case for term\.
> 
> But that rule isn't used \- subparses always generate something like
> the FUNC\(\) call \(where FUNC might be op\_stringify for "\.\.\."\)\, and I
> ended up adding the FUNC rule to sublexexpr too\.
> 
> Testing found that the \{expr\} sublex token rule wasn't being used so I
> removed it\, and finally added the remaining rule to term\.  Which is
> probably the wrong place\.
> 
> > Is it possible to construct an additional croak/toke test for the \\U
> > case\, or does the means of construction imply it cannot trigger
> > failure the same way?
> 
> I think it can\, though I couldn't reproduce it with an unpatched
> blead\.
> 
> I've attached an updated patch that moves the rule\, and some attempts
> at making qq\(\) reproduce the problem\, though I couldn't make them
> crash\.
> 
> Tony

Applied as 69afcc21edd23e38a4aff806a14e666d77f2bd0c\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'pending release'
