### ISSUE TITLE
pp_sys.c:957: Perl_pp_tie: Assertion `!isGV_with_GP(_svcur)' failed

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15825]
Migrated from [rt.perl.org#130623](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130623) (status was 'resolved')

Searchable as RT130623$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.25\.8\-216\-gfbceb79751 built with afl and run
under libdislocator\, I found the following program

tie$0\,\*0

to cause an assertion failure\. This is a regression in blead\, bisect points to

0b077c88df88ab0d1e7e4c9d8a5a6992563912e1 is the first bad commit
commit 0b077c88df88ab0d1e7e4c9d8a5a6992563912e1
Author&#8203;: Dagfinn Ilmari Mannsåker \<ilmari@&#8203;ilmari\.org>
Date&#8203;:   Sun Nov 13 15&#8203;:10&#8203;:38 2016 \+0100

&nbsp;    Improve error for missing tie\(\) pacakge/method

&nbsp;    This brings the error messages in line with the ones used for normal
&nbsp;    method calls\, despite not using call\_method\(\)\.

GDB info about the crash location&#8203;:

\(gdb\) bt
\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:58
\#1  0x00007f869ed7f40a in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007f869ed76e47 in \_\_assert\_fail\_base \(fmt=\<optimized out>\,
assertion=assertion@&#8203;entry=0x7f86a04924f6 "\!isGV\_with\_GP\(\_svcur\)"\,
&nbsp;    file=file@&#8203;entry=0x7f86a049245f "pp\_sys\.c"\, line=line@&#8203;entry=957\,
function=function@&#8203;entry=0x7f86a0494a80 \<\_\_PRETTY\_FUNCTION\_\_\.15407>
"Perl\_pp\_tie"\)
&nbsp;    at assert\.c&#8203;:92
\#3  0x00007f869ed76ef2 in \_\_GI\_\_\_assert\_fail \(assertion=0x7f86a04924f6
"\!isGV\_with\_GP\(\_svcur\)"\, file=0x7f86a049245f "pp\_sys\.c"\, line=957\,
&nbsp;    function=0x7f86a0494a80 \<\_\_PRETTY\_FUNCTION\_\_\.15407> "Perl\_pp\_tie"\)
at assert\.c&#8203;:101
\#4  0x00007f86a033e545 in Perl\_pp\_tie \(\) at pp\_sys\.c&#8203;:957
\#5  0x00007f86a0200bde in Perl\_runops\_debug \(\) at dump\.c&#8203;:2260
\#6  0x00007f86a00fb156 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2528
\#7  0x00007f86a00fa6d4 in perl\_run \(my\_perl=0x7f86a1732010\) at perl\.c&#8203;:2451
\#8  0x00007f86a00b5d3e in main \(argc=2\, argv=0x7fff65409c28\,
env=0x7fff65409c40\) at perlmain\.c&#8203;:123

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.25.9:

Configured by root at Sat Jan 14 02:25:05 MSK 2017.

Summary of my perl5 (revision 5 version 25 subversion 9) configuration:
  Commit id: cbe2fc5001aa59cdc73e04cc35e097a2ecfbeec0
  Platform:
    osname=linux
    osvers=3.16.0-4-amd64
    archname=x86_64-linux
    uname='linux dorothy 3.16.0-4-amd64 #1 smp debian 3.16.36-1+deb8u2
(2016-10-19) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING -Dcc=afl-clang-fast
-Doptimize=-O0 -g -ggdb3'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    bincompat5005=undef
  Compiler:
    cc='afl-clang-fast'
    ccflags ='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O0 -g -ggdb3'
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Clang 3.9.1 (tags/RELEASE_391/rc2)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='afl-clang-fast'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/lib
/usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu
/lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.24.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.24'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O0 -g -ggdb3 -L/usr/local/lib -fstack-protector-strong'



@INC for perl 5.25.9:
    lib
    /usr/local/lib/perl5/site_perl/5.25.9/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.25.9
    /usr/local/lib/perl5/5.25.9/x86_64-linux
    /usr/local/lib/perl5/5.25.9


Environment for perl 5.25.9:
    HOME=/home/afl
    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    PERLBREW_BASHRC_VERSION=0.78
    PERLBREW_HOME=/home/afl/.perlbrew
    PERLBREW_MANPATH=/home/afl/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/home/afl/perlbrew
    PERLBREW_VERSION=0.78
    PERL_BADLANG (unset)
    SHELL=/usr/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @dur-randir

Different way to hit the same line\, but with another assertion&#8203;:

tie%0\,\\0

pp\_sys\.c&#8203;:957&#8203;: OP \*Perl\_pp\_tie\(\)&#8203;: Assertion \`PL\_valid\_types\_PVX\[SvTYPE\(\_svcur\) & SVt\_MASK\] || SvTYPE\(\_svcur\) == SVt\_REGEXP' failed\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Different way to hit the same line\, but with another assertion&#8203;:

tie%0\,\\0

pp\_sys\.c&#8203;:957&#8203;: OP \*Perl\_pp\_tie\(\)&#8203;: Assertion \`PL\_valid\_types\_PVX\[SvTYPE\(\_svcur\) & SVt\_MASK\] || SvTYPE\(\_svcur\) == SVt\_REGEXP' failed\.

**Comment by p5pRT** [comment]
### From @arc

Thanks for the report\. As you surmise\, these are subtly different bugs relating to the same area of code\. They are fixed as of 32207c637b216a1dfa7317d111af89f149743ff3\.

\-\- 
Aaron Crane \*\* http&#8203;://aaroncrane\.co\.uk/

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@arc - Status changed from 'open' to 'resolved'
