### ISSUE TITLE
op.c:14389: Perl_rpeep: Assertion `(kid->op_type == OP_NULL && ( kid->op_targ == OP_NEXTSTATE || kid->op_targ == OP_DBSTATE )) || kid->op_type == OP_STUB || kid->op_type == OP_ENTER' failed

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15823]
Migrated from [rt.perl.org#130617](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130617) (status was 'resolved')

Searchable as RT130617$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.25\.8\-216\-gfbceb79751 built with afl and run
under libdislocator\, I found the following program

\}my;0=sort\{i d&0\}0

to cause an assertion failure\, even when run under \-c for a syntax
check\. This is a regression between v5\.18\.4 and v5\.20\.0\, bisect points to

932bca295d64243e2ef2aeaacc779b68cc05e1b2 is the first bad commit
commit 932bca295d64243e2ef2aeaacc779b68cc05e1b2
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Wed Mar 5 14&#8203;:44&#8203;:41 2014 \+0000

&nbsp;    OP\_SORT&#8203;: store start of block in null\->op\_next

&nbsp;    When a sort with a code block\, like sort \{ BLOCK \} arg\, \.\.\.
&nbsp;    is compiled\, it comes out like

&nbsp;         sort
&nbsp;            pushmark
&nbsp;            null
&nbsp;               scope
&nbsp;                  BLOCK
&nbsp;            arg
&nbsp;            \.\.\.

&nbsp;    \(The 'scope' may be instead be 'ex\-leave' depending on circumstances\)\.

&nbsp;    At run time\, pp\_sort\(\) navigates its way down from the sort op to find the
&nbsp;    start op of the BLOCK\. We can shorten this process slightly by storing the
&nbsp;    start of BLOCK in the otherwise unused op\_next field of the OP\_NULL\.
&nbsp;    Effectively we are using the null\->op\_next field as a surrogate op\_other
&nbsp;    field for the op\_sort \(which doesn't have a spare field we could store
&nbsp;    the pointer in\)\.

&nbsp;    The main point of this commit however is not the slight speed up from
&nbsp;    skipping a couple of pointer follows at run\-time; rather that it will
&nbsp;    shortly allow us to trim any null ops from the beginning of the BLOCK\. We
&nbsp;    can't do this directly\, as that would involve changing the scope\->op\_first
&nbsp;    pointer\, which might confuse B&#8203;:: type modules\.

GDB info about the crash location&#8203;:

\(gdb\) bt
\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:58
\#1  0x00007fc95d34140a in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007fc95d338e47 in \_\_assert\_fail\_base \(fmt=\<optimized out>\,
&nbsp;    assertion=assertion@&#8203;entry=0x7fc95e9cf1e0 "\(kid\->op\_type == OP\_NULL
&& \( kid\->op\_targ == OP\_NEXTSTATE || kid\->op\_targ == OP\_DBSTATE \)\) ||
kid\->op\_type == OP\_STUB || kid\->op\_type == OP\_ENTER"\,
file=file@&#8203;entry=0x7fc95e9c952e "op\.c"\, line=line@&#8203;entry=14389\,
&nbsp;    function=function@&#8203;entry=0x7fc95e9d06d8 \<\_\_PRETTY\_FUNCTION\_\_\.19609>
"Perl\_rpeep"\) at assert\.c&#8203;:92
\#3  0x00007fc95d338ef2 in \_\_GI\_\_\_assert\_fail \(
&nbsp;    assertion=0x7fc95e9cf1e0 "\(kid\->op\_type == OP\_NULL && \(
kid\->op\_targ == OP\_NEXTSTATE || kid\->op\_targ == OP\_DBSTATE \)\) ||
kid\->op\_type == OP\_STUB || kid\->op\_type == OP\_ENTER"\,
file=0x7fc95e9c952e "op\.c"\, line=14389\, function=0x7fc95e9d06d8
\<\_\_PRETTY\_FUNCTION\_\_\.19609> "Perl\_rpeep"\) at assert\.c&#8203;:101
\#4  0x00007fc95e6b3266 in Perl\_rpeep \(o=0x7fc95ee00080\) at op\.c&#8203;:14384
\#5  0x00007fc95e6b3fa0 in Perl\_peep \(o=0x7fc95edfe168\) at op\.c&#8203;:14718
\#6  0x00007fc95e68647b in Perl\_newPROG \(o=0x7fc95edfe1a0\) at op\.c&#8203;:4273
\#7  0x00007fc95e7386f6 in Perl\_yyparse \(gramtype=258\) at perly\.y&#8203;:123
\#8  0x00007fc95e6bc33a in S\_parse\_body \(env=0x0\, xsinit=0x7fc95e677de8
\<xs\_init>\) at perl\.c&#8203;:2376
\#9  0x00007fc95e6ba69f in perl\_parse \(my\_perl=0x7fc95eddd010\,
xsinit=0x7fc95e677de8 \<xs\_init>\, argc=2\, argv=0x7ffd7a071f08\, env=0x0\)
at perl\.c&#8203;:1691
\#10 0x00007fc95e677d26 in main \(argc=2\, argv=0x7ffd7a071f08\,
env=0x7ffd7a071f20\) at perlmain\.c&#8203;:121
\(gdb\) f 4
\#4  0x00007fc95e6b3266 in Perl\_rpeep \(o=0x7fc95ee00080\) at op\.c&#8203;:14384
\(gdb\) p PL\_op\_name\[kid\->op\_type\]
$3 = 0x7fc95ea81aa2 "lineseq"

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.25.9:

Configured by root at Sat Jan 14 02:25:05 MSK 2017.

Summary of my perl5 (revision 5 version 25 subversion 9) configuration:
  Commit id: cbe2fc5001aa59cdc73e04cc35e097a2ecfbeec0
  Platform:
    osname=linux
    osvers=3.16.0-4-amd64
    archname=x86_64-linux
    uname='linux dorothy 3.16.0-4-amd64 #1 smp debian 3.16.36-1+deb8u2
(2016-10-19) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING -Dcc=afl-clang-fast
-Doptimize=-O0 -g -ggdb3'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    bincompat5005=undef
  Compiler:
    cc='afl-clang-fast'
    ccflags ='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O0 -g -ggdb3'
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Clang 3.9.1 (tags/RELEASE_391/rc2)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='afl-clang-fast'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/lib
/usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu
/lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.24.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.24'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O0 -g -ggdb3 -L/usr/local/lib -fstack-protector-strong'



@INC for perl 5.25.9:
    lib
    /usr/local/lib/perl5/site_perl/5.25.9/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.25.9
    /usr/local/lib/perl5/5.25.9/x86_64-linux
    /usr/local/lib/perl5/5.25.9


Environment for perl 5.25.9:
    HOME=/home/afl
    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    PERLBREW_BASHRC_VERSION=0.78
    PERLBREW_HOME=/home/afl/.perlbrew
    PERLBREW_MANPATH=/home/afl/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/home/afl/perlbrew
    PERLBREW_VERSION=0.78
    PERL_BADLANG (unset)
    SHELL=/usr/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Jan 22\, 2017 at 04&#8203;:18&#8203;:13AM \-0800\, Sergey Aleynikov wrote&#8203;:
> While fuzzing perl v5\.25\.8\-216\-gfbceb79751 built with afl and run
> under libdislocator\, I found the following program
> 
> \}my;0=sort\{i d&0\}0
> 
> to cause an assertion failure\, even when run under \-c for a syntax
> check\. This is a regression between v5\.18\.4 and v5\.20\.0\, bisect points to

Fixed with the following commit\. It's yet another example of the
difficulty of attempting to continue parsing after an error has been
encountered\.


commit 03fedefe18733baa9ed7c9c22bd816408d57de0d
Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
AuthorDate&#8203;: Mon Jan 23 12&#8203;:27&#8203;:20 2017 \+0000
Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
CommitDate&#8203;: Mon Jan 23 12&#8203;:27&#8203;:20 2017 \+0000

&nbsp;    avoid sort assert failure after compile fail
&nbsp;    
&nbsp;    RT \#130617
&nbsp;    
&nbsp;    in rpeep\(\)\, there's an assert that the optree is sane for the sort's
&nbsp;    codeblock\. After compile errors\, it isn;t necessary sane\, so skip the
&nbsp;    assert in that case\.
&nbsp;    
&nbsp;    I've also changed a kLISTOP\->op\_next into the equivalent but less
&nbsp;    obfuscated kid\->op\_next\.


\-\- 
Technology is dominated by two types of people&#8203;: those who understand what
they do not manage\, and those who manage what they do not understand\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
