### ISSUE TITLE
Segfault in Perl_vwarner (util.c:2051)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15824]
Migrated from [rt.perl.org#130621](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130621) (status was 'open')

Searchable as RT130621$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.25\.8\-216\-gfbceb79751 built with afl and run
under libdislocator\, I found the following program

eval q\!$^D = 'C';0 =~ ~v1000 / 0\!

to crash on debugging builds \(as assigning to $^D is a no\-op on
regular builds\)\. This is a regression between v5\.22\.2 and v5\.24\.0\,
bisect points to

4df352a81ba92beb6467d6dafdf988d8aba963c4 is the first bad commit
commit 4df352a81ba92beb6467d6dafdf988d8aba963c4
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Mon Oct 12 14&#8203;:56&#8203;:35 2015 \+0100

&nbsp;    reverse the order of POPBLOCK; POPFOO

&nbsp;    Currently most pp\_leavefoo subs have something along the lines of

&nbsp;        POPBLOCK\(cx\);
&nbsp;        POPFOO\(cx\);

&nbsp;    where POPBLOCK does cxstack\_ix\-\- and sets cx to point to the top CX stack
&nbsp;    entry\. It then restores a bunch of PL\_ vars saved in the CX struct\.

&nbsp;    Then POPFOO does any type\-specific restoration\, e\.g\. POPSUB decrements the
&nbsp;    ref count of the cv that was just executed\.

&nbsp;    However\, this is logically the wrong order\. When we \*enter\* a scope\, we do

&nbsp;        PUSHBLOCK;
&nbsp;        PUSHFOO;

&nbsp;    so undoing the PUSHBLOCK should be the last thing we do\.  As it happens\,
&nbsp;    it doesn't really make any difference to the running\, which is why we've
&nbsp;    never fixed it before\.

&nbsp;    Reordering it has two advantages\.

&nbsp;    First\, it allows the steps for scope exit to be the exact logical reverse
&nbsp;    of scope exit\, which makes understanding what's going on and debugging
&nbsp;    easier\.

&nbsp;    It allows us to make the code cleaner\.

&nbsp;    This commit also removes the cxstack\_ix\-\- and setting cx steps from
&nbsp;    POPBLOCK; now we already expect cx to be set \(which it usually already is\)
&nbsp;    and we do the cxstack\_ix\-\- ourselves\. This also means we can remove a
&nbsp;    whole bunch of cxstack\_ix\+\+'s that were added immediately after the
&nbsp;    POPBLOCK in order to prevent the context being inadvertently overwritten
&nbsp;    before we've finished using it\.

&nbsp;    So in full\,

&nbsp;        POPBLOCK\(cx\);
&nbsp;        POPFOO\(cx\);

&nbsp;    is now implemented as&#8203;:

&nbsp;        cx = &cxstack\[cxstack\_ix\];
&nbsp;        \.\.\. other stuff done with cx \.\.\.
&nbsp;        POPFOO\(cx\);
&nbsp;        POPBLOCK\(cx\);
&nbsp;        cxstack\_ix\-\-;

&nbsp;    Finally\, this commit also tweaks PL\_curcop in pp\_leaveeval\, since
&nbsp;    otherwise PL\_curcop could temporarily be NULL when debugging code is
&nbsp;    called in the presence of 'use re Debug'\. It also stops the debugging code
&nbsp;    crashing if PL\_curcop is still NULL\.

GDB info about the crash location&#8203;:

\#0  0x00007fbd1b8dc188 in Perl\_vwarner \(err=2\, pat=0x7fbd1bb87876
"%s"\, args=0x7ffd2c784800\) at util\.c&#8203;:2050
2050            \(PL\_warnhook == PERL\_WARNHOOK\_FATAL || ckDEAD\(err\)\) &&
\(gdb\) bt
\#0  0x00007fbd1b8dc188 in Perl\_vwarner \(err=2\, pat=0x7fbd1bb87876
"%s"\, args=0x7ffd2c784800\) at util\.c&#8203;:2050
\#1  0x00007fbd1b8dc117 in Perl\_warner \(err=2\, pat=0x7fbd1bb87876 "%s"\)
at util\.c&#8203;:2040
\#2  0x00007fbd1ba83105 in Perl\_utf8n\_to\_uvchr\_error \(s=0x7fbd1d62528d
""\, curlen=13\, retlen=0x0\, flags=0\, errors=0x7ffd2c784918\) at
utf8\.c&#8203;:1700
\#3  0x00007fbd1ba92f73 in Perl\_pv\_uni\_display \(dsv=0x7fbd1d61ba78\,
spv=0x7fbd1d625280
"\\377\\200\\217\\277\\277\\277\\277\\277\\277\\277\\277\\260\\227"\, len=13\,
&nbsp;    pvlim=78\, flags=3\) at utf8\.c&#8203;:5047
\#4  0x00007fbd1ba933b8 in Perl\_sv\_uni\_display \(dsv=0x7fbd1d61ba78\,
ssv=0x7fbd1d629ce0\, pvlim=78\, flags=3\) at utf8\.c&#8203;:5109
\#5  0x00007fbd1b8cc3fa in Perl\_do\_sv\_dump \(level=0\,
file=0x7fbd1d615620\, sv=0x7fbd1d629ce0\, nest=0\, maxnest=0\,
dumpops=false\, pvlim=0\) at dump\.c&#8203;:1627
\#6  0x00007fbd1b8d498f in Perl\_sv\_dump \(sv=0x7fbd1d629ce0\) at dump\.c&#8203;:2219
\#7  0x00007fbd1b9790c6 in Perl\_sv\_clear \(orig\_sv=0x7fbd1d629ce0\) at sv\.c&#8203;:6744
\#8  0x00007fbd1b97b125 in Perl\_sv\_free2 \(sv=0x7fbd1d629ce0\, rc=1\) at sv\.c&#8203;:7061
\#9  0x00007fbd1b859765 in S\_SvREFCNT\_dec \(sv=0x7fbd1d629ce0\) at inline\.h&#8203;:189
\#10 0x00007fbd1b8bc827 in Perl\_pregfree2 \(rx=0x7fbd1d61bfb8\) at regcomp\.c&#8203;:19330
\#11 0x00007fbd1b977f72 in Perl\_sv\_clear \(orig\_sv=0x7fbd1d61bfb8\) at sv\.c&#8203;:6607
\#12 0x00007fbd1b97b125 in Perl\_sv\_free2 \(sv=0x7fbd1d61bfb8\, rc=1\) at sv\.c&#8203;:7061
\#13 0x00007fbd1b78ad4d in S\_SvREFCNT\_dec \(sv=0x7fbd1d61bfb8\) at inline\.h&#8203;:189
\#14 0x00007fbd1b78d848 in Perl\_op\_clear \(o=0x7fbd1d625e20\) at op\.c&#8203;:1055
\#15 0x00007fbd1b78d330 in Perl\_op\_free \(o=0x7fbd1d625e20\) at op\.c&#8203;:855
\#16 0x00007fbd1b9dd58d in Perl\_leave\_scope \(base=0\) at scope\.c&#8203;:1109
\#17 0x00007fbd1b9ec13b in S\_pop\_eval\_context\_maybe\_croak
\(cx=0x7fbd1d609fc0\, errsv=0x7fbd1d629d10\, action=2\) at pp\_ctl\.c&#8203;:1613
\#18 0x00007fbd1b9ecc66 in Perl\_die\_unwind \(msv=0x7fbd1d629d10\) at pp\_ctl\.c&#8203;:1741
\#19 0x00007fbd1b8db690 in Perl\_vcroak \(pat=0x7fbd1bb5afa2 "Illegal
division by zero"\, args=0x7ffd2c786120\) at util\.c&#8203;:1805
\#20 0x00007fbd1b8db3b5 in Perl\_die \(pat=0x7fbd1bb5afa2 "Illegal
division by zero"\) at util\.c&#8203;:1736
\#21 0x00007fbd1b9acd21 in Perl\_pp\_divide \(\) at pp\.c&#8203;:1554
\#22 0x00007fbd1b8d4bde in Perl\_runops\_debug \(\) at dump\.c&#8203;:2260
\#23 0x00007fbd1b7cf156 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2528
\#24 0x00007fbd1b7ce6d4 in perl\_run \(my\_perl=0x7fbd1d605010\) at perl\.c&#8203;:2451
\#25 0x00007fbd1b789d3e in main \(argc=2\, argv=0x7ffd2c786608\,
env=0x7ffd2c786620\) at perlmain\.c&#8203;:123
\(gdb\) p PL\_curcop\->cop\_warnings
Cannot access memory at address 0x40

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.25.9:

Configured by root at Sat Jan 14 02:25:05 MSK 2017.

Summary of my perl5 (revision 5 version 25 subversion 9) configuration:
  Commit id: cbe2fc5001aa59cdc73e04cc35e097a2ecfbeec0
  Platform:
    osname=linux
    osvers=3.16.0-4-amd64
    archname=x86_64-linux
    uname='linux dorothy 3.16.0-4-amd64 #1 smp debian 3.16.36-1+deb8u2
(2016-10-19) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING -Dcc=afl-clang-fast
-Doptimize=-O0 -g -ggdb3'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    bincompat5005=undef
  Compiler:
    cc='afl-clang-fast'
    ccflags ='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O0 -g -ggdb3'
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Clang 3.9.1 (tags/RELEASE_391/rc2)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='afl-clang-fast'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/lib
/usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu
/lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.24.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.24'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O0 -g -ggdb3 -L/usr/local/lib -fstack-protector-strong'



@INC for perl 5.25.9:
    lib
    /usr/local/lib/perl5/site_perl/5.25.9/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.25.9
    /usr/local/lib/perl5/5.25.9/x86_64-linux
    /usr/local/lib/perl5/5.25.9


Environment for perl 5.25.9:
    HOME=/home/afl
    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    PERLBREW_BASHRC_VERSION=0.78
    PERLBREW_HOME=/home/afl/.perlbrew
    PERLBREW_MANPATH=/home/afl/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/home/afl/perlbrew
    PERLBREW_VERSION=0.78
    PERL_BADLANG (unset)
    SHELL=/usr/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Jan 22\, 2017 at 01&#8203;:10&#8203;:42PM \-0800\, Sergey Aleynikov wrote&#8203;:
> While fuzzing perl v5\.25\.8\-216\-gfbceb79751 built with afl and run
> under libdislocator\, I found the following program
> 
> eval q\!$^D = 'C';0 =~ ~v1000 / 0\!
> 
> to crash on debugging builds \(as assigning to $^D is a no\-op on
> regular builds\)\. This is a regression between v5\.22\.2 and v5\.24\.0\,
> bisect points to

I've fixed the proximate cause with the following two commits; the deeper
eval fix I'll leave till later\.

commit b1a69a65ecd83426da7ca1af26b757fe0da58007
Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
AuthorDate&#8203;: Mon Jan 23 13&#8203;:27&#8203;:07 2017 \+0000
Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
CommitDate&#8203;: Mon Jan 23 13&#8203;:52&#8203;:36 2017 \+0000

&nbsp;    ckDEAD&#8203;: PL\_curcop\->cop\_warnings only if PL\_curcop
&nbsp;    
&nbsp;    RT \#130621
&nbsp;    
&nbsp;    In ckDEAD\(\)\, don't check the value of PL\_curcop\->cop\_warnings unless
&nbsp;    PL\_curcop is non\-null\.
&nbsp;    
&nbsp;    In the ticket above\, the reason that PL\_curcop is null is the less
&nbsp;    than optimal way that evals free their optree&#8203;: ideally the optree should
&nbsp;    be attached to the eval CV and freed when the CV is; instead a separate
&nbsp;    SAVEFREEOP\(\) is done\. But that fix is for another time; regardless\,
&nbsp;    ckDEAD\(\) should have a PL\_curcop \!= NULL guard anyway like isLEXWARN\_on\(\)
&nbsp;    etc already do\.

commit f4c617746504f38fcb281a2b1c1da9426d8eab01
Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
AuthorDate&#8203;: Mon Jan 23 13&#8203;:37&#8203;:21 2017 \+0000
Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
CommitDate&#8203;: Mon Jan 23 13&#8203;:52&#8203;:36 2017 \+0000

&nbsp;    mess\_sv\(\)&#8203;: access only if PL\_curcop is non\-null
&nbsp;    
&nbsp;    RT \#130621
&nbsp;    
&nbsp;    In Perl\_mess\_sv\(\)\, don't try to add an "at foo line NN" to the error
&nbsp;    message if PL\_curcop is null\.
&nbsp;    
&nbsp;    In the ticket above\, the reason that PL\_curcop is null is the less
&nbsp;    than optimal way that evals free their optree&#8203;: ideally the optree should
&nbsp;    be attached to the eval CV and freed when the CV is; instead a separate
&nbsp;    SAVEFREEOP\(\) is done\. But that fix is for another time; regardless\,
&nbsp;    mess\_sv\(\) should have a PL\_curcop \!= NULL guard anyway\.

\-\- 
This email is confidential\, and now that you have read it you are legally
obliged to shoot yourself\. Or shoot a lawyer\, if you prefer\. If you have
received this email in error\, place it in its original wrapping and return
for a full refund\. By opening this email\, you accept that Elvis lives\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'
