### ISSUE TITLE
perly.c:341: Perl_yyparse: Assertion `parser->yychar >= 0' failed.

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15845]
Migrated from [rt.perl.org#130661](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130661) (status was 'resolved')

Searchable as RT130661$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.25\.9\-35\-g32207c637b built with afl and run
under libdislocator\, I found the following 5\-bytes program

hexdump \-C 0051
00000000  73 75 62 28 ec                                    |sub\(\.|
00000005

to cause an assertion failure when run with \-Mexperimental=signatures\.
This is a regression in blead\, bisect points to

0f8490d1d7ad76cac844fc2ae882994e38aaf2ef is the first bad commit
commit 0f8490d1d7ad76cac844fc2ae882994e38aaf2ef
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Sun Dec 4 08&#8203;:10&#8203;:27 2016 \+0000

&nbsp;    yyparse&#8203;: only calculate yytoken on yychar change

&nbsp;    yytoken is a translated \(via lookup table\) version of parser\->yychar\.
&nbsp;    So we only need to recalculate it when yychar changes \(usually by
&nbsp;    assigning the result of yylex\(\) to it\)\. This means when multiple
&nbsp;    reductions are done without shifting another token\, we skip the extra
&nbsp;    overhead each time\.

GDB info about the crash location&#8203;:

\(gdb\) bt
\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:58
\#1  0x00007fcb40e4c40a in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007fcb40e43e47 in \_\_assert\_fail\_base \(fmt=\<optimized out>\,
assertion=assertion@&#8203;entry=0x7fcb42cf9906 "parser\->yychar >= 0"\,
&nbsp;    file=file@&#8203;entry=0x7fcb42cf987a "perly\.c"\, line=line@&#8203;entry=341\,
function=function@&#8203;entry=0x7fcb42cfa320 \<\_\_PRETTY\_FUNCTION\_\_\.15814>
"Perl\_yyparse"\)
&nbsp;    at assert\.c&#8203;:92
\#3  0x00007fcb40e43ef2 in \_\_GI\_\_\_assert\_fail
\(assertion=assertion@&#8203;entry=0x7fcb42cf9906 "parser\->yychar >= 0"\,
file=file@&#8203;entry=0x7fcb42cf987a "perly\.c"\,
&nbsp;    line=line@&#8203;entry=341\, function=function@&#8203;entry=0x7fcb42cfa320
\<\_\_PRETTY\_FUNCTION\_\_\.15814> "Perl\_yyparse"\) at assert\.c&#8203;:101
\#4  0x00007fcb423ea803 in Perl\_yyparse \(gramtype=gramtype@&#8203;entry=258\)
at perly\.c&#8203;:341
\#5  0x00007fcb4229a131 in S\_parse\_body \(env=env@&#8203;entry=0x0\,
xsinit=xsinit@&#8203;entry=0x7fcb4218f990 \<xs\_init>\) at perl\.c&#8203;:2376
\#6  0x00007fcb422a0deb in perl\_parse \(my\_perl=\<optimized out>\,
xsinit=0x7fcb4218f990 \<xs\_init>\, argc=\<optimized out>\, argv=\<optimized
out>\, env=0x0\)
&nbsp;    at perl\.c&#8203;:1691
\#7  0x00007fcb4218f56e in main \(argc=\<optimized out>\, argv=\<optimized
out>\, env=\<optimized out>\) at perlmain\.c&#8203;:121
\(gdb\) f 4
\#4  0x00007fcb423ea803 in Perl\_yyparse \(gramtype=gramtype@&#8203;entry=258\)
at perly\.c&#8203;:341
341                     assert\(parser\->yychar >= 0\);
\(gdb\) p parser\->yychar
$1 = \-20

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.25.9:

Configured by root at Sat Jan 14 02:25:05 MSK 2017.

Summary of my perl5 (revision 5 version 25 subversion 9) configuration:
  Commit id: cbe2fc5001aa59cdc73e04cc35e097a2ecfbeec0
  Platform:
    osname=linux
    osvers=3.16.0-4-amd64
    archname=x86_64-linux
    uname='linux dorothy 3.16.0-4-amd64 #1 smp debian 3.16.36-1+deb8u2
(2016-10-19) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING -Dcc=afl-clang-fast
-Doptimize=-O0 -g -ggdb3'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    bincompat5005=undef
  Compiler:
    cc='afl-clang-fast'
    ccflags ='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O0 -g -ggdb3'
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Clang 3.9.1 (tags/RELEASE_391/rc2)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='afl-clang-fast'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/lib
/usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu
/lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.24.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.24'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O0 -g -ggdb3 -L/usr/local/lib -fstack-protector-strong'



@INC for perl 5.25.9:
    lib
    /usr/local/lib/perl5/site_perl/5.25.9/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.25.9
    /usr/local/lib/perl5/5.25.9/x86_64-linux
    /usr/local/lib/perl5/5.25.9


Environment for perl 5.25.9:
    HOME=/home/afl
    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    PERLBREW_BASHRC_VERSION=0.78
    PERLBREW_HOME=/home/afl/.perlbrew
    PERLBREW_MANPATH=/home/afl/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/home/afl/perlbrew
    PERLBREW_VERSION=0.78
    PERL_BADLANG (unset)
    SHELL=/usr/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @dur-randir

[0051](https://rt-archive.perl.org/perl5/Ticket/Attachment/1446249/784117/0051)

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, Jan 28\, 2017 at 09&#8203;:21&#8203;:30AM \-0800\, Sergey Aleynikov wrote&#8203;:
> While fuzzing perl v5\.25\.9\-35\-g32207c637b built with afl and run
> under libdislocator\, I found the following 5\-bytes program
> 
> hexdump \-C 0051
> 00000000  73 75 62 28 ec                                    |sub\(\.|
> 00000005
> 
> to cause an assertion failure when run with \-Mexperimental=signatures\.
> This is a regression in blead\, bisect points to

Now fixed with v5\.25\.9\-66\-gcbf40e7&#8203;:

commit cbf40e71df30fba4761230a8b62a34d7bb247495
Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
AuthorDate&#8203;: Mon Jan 30 12&#8203;:25&#8203;:55 2017 \+0000
Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
CommitDate&#8203;: Mon Jan 30 12&#8203;:30&#8203;:30 2017 \+0000

&nbsp;    signature sub \(\\x80 triggered an assertion
&nbsp;    
&nbsp;    RT \#130661
&nbsp;    
&nbsp;    In the presence of 'use feature "signatures"'\, a char >= 0x80 where a sigil
&nbsp;    was expected triggered an assert failure\, because the \(signed\) character
&nbsp;    was being was being promoted to int and ended up getting returned from
&nbsp;    yylex\(\) as a negative value\.

\-\- 
"There's something wrong with our bloody ships today\, Chatfield\."
&nbsp;    \-\- Admiral Beatty at the Battle of Jutland\, 31st May 1916\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon\, 30 Jan 2017 04&#8203;:39&#8203;:28 \-0800\, davem wrote&#8203;:
> Now fixed with v5\.25\.9\-66\-gcbf40e7&#8203;:

and closing\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.26\.0\, this and 210 other issues have been
resolved\.

Perl 5\.26\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.26.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
