### ISSUE TITLE
sv.c:6545: void Perl_sv_clear(SV *const): Assertion `SvTYPE(sv) != (svtype)SVTYPEMASK' failed

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15847]
Migrated from [rt.perl.org#130667](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130667) (status was 'open')

Searchable as RT130667$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.25\.9\-35\-g32207c637b built with afl and run
under libdislocator\, I found the following program

a\{%0=local$0\,%0=0\}

to cause an assertion failure on debugging builds and crash on regular builds\.
This is a regression in blead\, bisect points to

8b0c3377906a6f991cd6c21a674bf9561d85e3cb is the first bad commit
commit 8b0c3377906a6f991cd6c21a674bf9561d85e3cb
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Wed Oct 5 10&#8203;:10&#8203;:56 2016 \+0100

&nbsp;    Better optimise array and hash assignment

&nbsp;    \[perl \#127999\] Slowdown in split \+ list assign

GDB info about the crash location&#8203;:

\(gdb\) bt
\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:58
\#1  0x00007f96ae90f40a in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007f96ae906e47 in \_\_assert\_fail\_base \(fmt=\<optimized out>\,
assertion=assertion@&#8203;entry=0x7f96b07d8530 "SvTYPE\(sv\) \!=
\(svtype\)SVTYPEMASK"\,
&nbsp;    file=file@&#8203;entry=0x7f96b07d7196 "sv\.c"\, line=line@&#8203;entry=6545\,
function=function@&#8203;entry=0x7f96b07e5308 \<\_\_PRETTY\_FUNCTION\_\_\.19252>
"Perl\_sv\_clear"\)
&nbsp;    at assert\.c&#8203;:92
\#3  0x00007f96ae906ef2 in \_\_GI\_\_\_assert\_fail
\(assertion=assertion@&#8203;entry=0x7f96b07d8530 "SvTYPE\(sv\) \!=
\(svtype\)SVTYPEMASK"\,
&nbsp;    file=file@&#8203;entry=0x7f96b07d7196 "sv\.c"\, line=line@&#8203;entry=6545\,
function=function@&#8203;entry=0x7f96b07e5308 \<\_\_PRETTY\_FUNCTION\_\_\.19252>
"Perl\_sv\_clear"\)
&nbsp;    at assert\.c&#8203;:101
\#4  0x00007f96b01a1c87 in Perl\_sv\_clear
\(orig\_sv=orig\_sv@&#8203;entry=0x7f96b1d75510\) at sv\.c&#8203;:6545
\#5  0x00007f96b01a1f3c in Perl\_sv\_free2 \(sv=0x7f96b1d75510\,
rc=\<optimized out>\) at sv\.c&#8203;:7061
\#6  0x00007f96b037144d in S\_SvREFCNT\_dec\_NN \(sv=\<optimized out>\) at inline\.h&#8203;:200
\#7  Perl\_free\_tmps \(\) at scope\.c&#8203;:207
\#8  0x00007f96afd66dc5 in perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2456
\#9  0x00007f96afc52814 in main \(argc=\<optimized out>\, argv=\<optimized
out>\, env=\<optimized out>\) at perlmain\.c&#8203;:123

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.25.9:

Configured by root at Sat Jan 14 02:25:05 MSK 2017.

Summary of my perl5 (revision 5 version 25 subversion 9) configuration:
  Commit id: cbe2fc5001aa59cdc73e04cc35e097a2ecfbeec0
  Platform:
    osname=linux
    osvers=3.16.0-4-amd64
    archname=x86_64-linux
    uname='linux dorothy 3.16.0-4-amd64 #1 smp debian 3.16.36-1+deb8u2
(2016-10-19) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING -Dcc=afl-clang-fast
-Doptimize=-O0 -g -ggdb3'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    bincompat5005=undef
  Compiler:
    cc='afl-clang-fast'
    ccflags ='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O0 -g -ggdb3'
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Clang 3.9.1 (tags/RELEASE_391/rc2)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='afl-clang-fast'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/lib
/usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu
/lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.24.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.24'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O0 -g -ggdb3 -L/usr/local/lib -fstack-protector-strong'



@INC for perl 5.25.9:
    lib
    /usr/local/lib/perl5/site_perl/5.25.9/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.25.9
    /usr/local/lib/perl5/5.25.9/x86_64-linux
    /usr/local/lib/perl5/5.25.9


Environment for perl 5.25.9:
    HOME=/home/afl
    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    PERLBREW_BASHRC_VERSION=0.78
    PERLBREW_HOME=/home/afl/.perlbrew
    PERLBREW_MANPATH=/home/afl/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/home/afl/perlbrew
    PERLBREW_VERSION=0.78
    PERL_BADLANG (unset)
    SHELL=/usr/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Jan 29\, 2017 at 03&#8203;:16&#8203;:24AM \-0800\, Sergey Aleynikov wrote&#8203;:
> While fuzzing perl v5\.25\.9\-35\-g32207c637b built with afl and run
> under libdislocator\, I found the following program
> 
> a\{%0=local$0\,%0=0\}
> 
> to cause an assertion failure on debugging builds and crash on regular builds\.
> This is a regression in blead\, bisect points to
> 
> 8b0c3377906a6f991cd6c21a674bf9561d85e3cb is the first bad commit
> commit 8b0c3377906a6f991cd6c21a674bf9561d85e3cb
> Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
> Date&#8203;:   Wed Oct 5 10&#8203;:10&#8203;:56 2016 \+0100
> 
>     Better optimise array and hash assignment
> 
>     \[perl \#127999\] Slowdown in split \+ list assign

Its a stack\-not\-refcounted issue\.

The code can be simplified to

&nbsp;    @&#8203;a = \(\(\(%h\) = \("k"\,1\)\)\, %h = \("k"\,2\)\);

at the start of the second assignment to %h\, %h is cleared\, leaving the
'1' SV on the stack as a freed value\. Whether perl assert fails or not
just depends on whether that freed SV happens to get reallocated before it
gets accessed as a stack value in a place that checks it for being a valid
SV\. Before that commit\, printing "\[@&#8203;a\]\\n" gives&#8203;:

&nbsp;    \[k 2 k 2\]

which shows that the SV gets reallocated and has '2' assigned to it; on
blead\, you get

&nbsp;    \[k  k 2\]

meaning it hasn't been reallocated because the newer pp\_assign\(\) code
is better at skipping unnecessary copying\.

\-\- 
The crew of the Enterprise encounter an alien life form which is
surprisingly neither humanoid nor made from pure energy\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#22

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'
