### ISSUE TITLE
regcomp.c:6881: REGEXP *Perl_re_op_compile(SV **const, int, OP *, const regexp_engine *, REGEXP *, _Bool *, U32, U32): Assertion `expr' failed

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15841]
Migrated from [rt.perl.org#130651](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130651) (status was 'open')

Searchable as RT130651$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.25\.9\-35\-g32207c637b built with afl and run
under libdislocator\, I found the following program

qr\!@&#8203;\{return%0\}0\[\(?\{\!

to cause an assertion failure on debugging builds and crash on regular
build\. This is a regression between v5\.16\.0 and v5\.18\.0\, bisect points
to

9f141731d83a1ac6294a5580a5b11ff41490309a is the first bad commit
commit 9f141731d83a1ac6294a5580a5b11ff41490309a
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Fri Nov 4 10&#8203;:12&#8203;:20 2011 \+0000

&nbsp;    Move bulk of pp\_regcomp\(\) into re\_op\_compile\(\)

&nbsp;    When called\, pp\_regcomp\(\) is presented with a list of SVs on the stack\.
&nbsp;    Previously\, it would perform \(amongst other things\)&#8203;:
&nbsp;      \* overloading those SVs;
&nbsp;      \* concatenating them;
&nbsp;      \* detection of bare /$qr/;
&nbsp;      \* detection of unchanged pattern;
&nbsp;    optionally followed by a call to the built\-in or an external regexp
&nbsp;    compiler\.

&nbsp;    Since we want to avoid premature concatenation \(so that we can handle
&nbsp;    /$runtime\(?\{\.\.\.\}\)/\)\, move all these activities from pp\_regcomp\(\) into
&nbsp;    re\_op\_compile\(\)\.

&nbsp;    This makes re\_op\_compile\(\) a bit cumbersome\, with a large arg list\,
&nbsp;    but I haven't found any way of only moving only a subset of the above\.

&nbsp;    Note that a side\-effect of this is that qr\-overloading now works for all
&nbsp;    regex compilations\, not just those reached via pp\_regcomp\(\); in particular
&nbsp;    this now invokes the qr method rather than the "" method if available&#8203;:
&nbsp;    /\(??\{ $overloaded\_object \}\)/

GDB info about the crash location&#8203;:

\(gdb\) bt
\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:58
\#1  0x00007f638067840a in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007f638066fe47 in \_\_assert\_fail\_base \(fmt=\<optimized out>\,
assertion=assertion@&#8203;entry=0x7f6381d5c686 "expr"\,
&nbsp;    file=file@&#8203;entry=0x7f6381d5a198 "regcomp\.c"\, line=line@&#8203;entry=6881\,
&nbsp;    function=function@&#8203;entry=0x7f6381d63580 \<\_\_PRETTY\_FUNCTION\_\_\.16856>
"Perl\_re\_op\_compile"\) at assert\.c&#8203;:92
\#3  0x00007f638066fef2 in \_\_GI\_\_\_assert\_fail \(assertion=0x7f6381d5c686
"expr"\, file=0x7f6381d5a198 "regcomp\.c"\, line=6881\,
&nbsp;    function=0x7f6381d63580 \<\_\_PRETTY\_FUNCTION\_\_\.16856>
"Perl\_re\_op\_compile"\) at assert\.c&#8203;:101
\#4  0x00007f6381aa179b in Perl\_re\_op\_compile \(patternp=0x7f63838a0b58\,
pat\_count=0\, expr=0x0\, eng=0x7f6381fe6540 \<PL\_core\_reg\_engine>\,
old\_re=0x0\,
&nbsp;    is\_bare\_re=0x7ffeaf6f0a5a\, orig\_rx\_flags=0\, pm\_flags=1342177280\)
at regcomp\.c&#8203;:6881
\#5  0x00007f6381c080f1 in Perl\_pp\_regcomp \(\) at pp\_ctl\.c&#8203;:107
\#6  0x00007f6381afb6e9 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2444
\#7  0x00007f63819f4936 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2528
\#8  0x00007f63819f3eb4 in perl\_run \(my\_perl=0x7f638389c010\) at perl\.c&#8203;:2451
\#9  0x00007f63819aeeee in main \(argc=2\, argv=0x7ffeaf6f0e28\,
env=0x7ffeaf6f0e40\) at perlmain\.c&#8203;:123

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.25.9:

Configured by root at Sat Jan 14 02:25:05 MSK 2017.

Summary of my perl5 (revision 5 version 25 subversion 9) configuration:
  Commit id: cbe2fc5001aa59cdc73e04cc35e097a2ecfbeec0
  Platform:
    osname=linux
    osvers=3.16.0-4-amd64
    archname=x86_64-linux
    uname='linux dorothy 3.16.0-4-amd64 #1 smp debian 3.16.36-1+deb8u2
(2016-10-19) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING -Dcc=afl-clang-fast
-Doptimize=-O0 -g -ggdb3'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    bincompat5005=undef
  Compiler:
    cc='afl-clang-fast'
    ccflags ='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O0 -g -ggdb3'
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Clang 3.9.1 (tags/RELEASE_391/rc2)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='afl-clang-fast'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/lib
/usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu
/lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.24.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.24'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O0 -g -ggdb3 -L/usr/local/lib -fstack-protector-strong'



@INC for perl 5.25.9:
    lib
    /usr/local/lib/perl5/site_perl/5.25.9/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.25.9
    /usr/local/lib/perl5/5.25.9/x86_64-linux
    /usr/local/lib/perl5/5.25.9


Environment for perl 5.25.9:
    HOME=/home/afl
    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    PERLBREW_BASHRC_VERSION=0.78
    PERLBREW_HOME=/home/afl/.perlbrew
    PERLBREW_MANPATH=/home/afl/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/home/afl/perlbrew
    PERLBREW_VERSION=0.78
    PERL_BADLANG (unset)
    SHELL=/usr/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Jan 26\, 2017 at 07&#8203;:13&#8203;:37AM \-0800\, Sergey Aleynikov wrote&#8203;:
> While fuzzing perl v5\.25\.9\-35\-g32207c637b built with afl and run
> under libdislocator\, I found the following program
> 
> qr\!@&#8203;\{return%0\}0\[\(?\{\!

A bit of an edge case this\. runtime qr//s which include code blocks
are wrapped in a hidden sub to make all the closurey stuff work correctly\.
So for example

&nbsp;    $r = qr/a$b\(?\{\.\.\.\}\)/

is roughly equivalent to

&nbsp;    @&#8203;args = sub \{
&nbsp;                \('a'\, $b\, sub\{\.\.\.\}\);
&nbsp;            \}\->\(\);
&nbsp;    $args = join ''\, @&#8203;args;
&nbsp;    $r = qr/$args/

\(except that the inner sub isn't actually a separate anon sub \- its just a
code block compiled as part of the outer anon sub\, and the code block gets
passed to the regex compiler as\-is rather than being stringified and
concatenated\.\)

The 'return' inside the @&#8203;\{\.\.\.\} expression is causing a return from the
hidden sub\, returning nothing\, which then causes an assert fail inside
Perl\_re\_op\_compile\, since its expecting at least 1 arg\.

The most immediate fix would be to make Perl\_re\_op\_compile\(\) robust in the
presence of no \(or unexpected\) args\, but it is semantically incorrect\.
The return should cause a return out of two levels of sub \- the hidden
one\, and the expected one which the qr// is enclosed in\. There's already
a mechanism for returning from two nested subs&#8203;: CXp\_SUB\_RE\_FAKE; but
I don't yet see an easy way to get it set in this case\, without
polluting pp\_entersub with more flags and special cases\.

I need to think some more\.


\-\- 
"You may not work around any technical limitations in the software"
&nbsp;    \-\- Windows Vista license

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.25\.9\-35\-g32207c637b built with afl and run
under libdislocator\, I found the following program

qr\!0\(?\{\}\)$\{return''\}\!

to use an initialized memory slot as a pointer to data\. This is a
regression between v5\.16 and v5\.18\, bisect points to&#8203;:

b30fcab9d36ac78789465635e3b1009dcf6a9488 is the first bad commit
commit b30fcab9d36ac78789465635e3b1009dcf6a9488
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Wed Nov 30 13&#8203;:40&#8203;:15 2011 \+0000

&nbsp;    preserve code blocks in interpolated qr//s

&nbsp;    This now works&#8203;:

&nbsp;        \{ my $x = 1; $r = qr/\(??\{$x\}\)/ \}
&nbsp;        my $x = 2;
&nbsp;        print "ok\\n" if "1" =~ /^$r$/;

&nbsp;    When a qr// is interpolated into another pattern\, the pattern is still
&nbsp;    recompiled using the stringified qr\, but now the pre\-compiled code blocks
&nbsp;    from the qr are reused rather than being re\-compiled\, so it behaves like a
&nbsp;    closure\.

GDB info about the program state is&#8203;:

\#0  0x00007f755ebcefb8 in S\_SvREFCNT\_dec \(sv=0xcccccccccccccccc\) at inline\.h&#8203;:185
185             U32 rc = SvREFCNT\(sv\);
\(gdb\) bt
\#0  0x00007f755ebcefb8 in S\_SvREFCNT\_dec \(sv=0xcccccccccccccccc\) at inline\.h&#8203;:185
\#1  0x00007f755ebec7a6 in S\_free\_codeblocks \(cbs=0x7f755d207ff0\) at
regcomp\.c&#8203;:6141
\#2  0x00007f755ec32e38 in Perl\_regfree\_internal \(rx=0x7f755d4fe658\) at
regcomp\.c&#8203;:19539
\#3  0x00007f755ec31ea5 in Perl\_pregfree2 \(rx=0x7f755d4fe658\) at regcomp\.c&#8203;:19393
\#4  0x00007f755ecedbda in Perl\_sv\_clear \(orig\_sv=0x7f755d4fe658\) at sv\.c&#8203;:6609
\#5  0x00007f755ecf0d8d in Perl\_sv\_free2 \(sv=0x7f755d4fe658\, rc=1\) at sv\.c&#8203;:7063
\#6  0x00007f755eafef0d in S\_SvREFCNT\_dec \(sv=0x7f755d4fe658\) at inline\.h&#8203;:189
\#7  0x00007f755eb019e9 in Perl\_op\_clear \(o=0x7f755d23ff98\) at op\.c&#8203;:1056
\#8  0x00007f755eb014f0 in Perl\_op\_free \(o=0x7f755d23ff98\) at op\.c&#8203;:855
\#9  0x00007f755eb3ee1f in perl\_destruct \(my\_perl=0x7f755f12cfff\) at perl\.c&#8203;:832
\#10 0x00007f755eafdf87 in main \(argc=3\, argv=0x7fff346cf748\,
env=0x7fff346cf768\) at perlmain\.c&#8203;:134

Pattern 0xcccccccccccccccc is an afl's pattern to poison malloc'ed
memory\. If not for the SIGSEGV here\, S\_SvREFCNT\_dec would perform a
write into sv\_refcnt of what it thinks is an SV\*\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.25.9:

Configured by root at Sat Jan 14 02:25:05 MSK 2017.

Summary of my perl5 (revision 5 version 25 subversion 9) configuration:
  Commit id: cbe2fc5001aa59cdc73e04cc35e097a2ecfbeec0
  Platform:
    osname=linux
    osvers=3.16.0-4-amd64
    archname=x86_64-linux
    uname='linux dorothy 3.16.0-4-amd64 #1 smp debian 3.16.36-1+deb8u2
(2016-10-19) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING -Dcc=afl-clang-fast
-Doptimize=-O0 -g -ggdb3'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    bincompat5005=undef
  Compiler:
    cc='afl-clang-fast'
    ccflags ='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O0 -g -ggdb3'
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Clang 3.9.1 (tags/RELEASE_391/rc2)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='afl-clang-fast'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/lib
/usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu
/lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.24.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.24'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O0 -g -ggdb3 -L/usr/local/lib -fstack-protector-strong'



@INC for perl 5.25.9:
    lib
    /usr/local/lib/perl5/site_perl/5.25.9/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.25.9
    /usr/local/lib/perl5/5.25.9/x86_64-linux
    /usr/local/lib/perl5/5.25.9


Environment for perl 5.25.9:
    HOME=/home/afl
    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    PERLBREW_BASHRC_VERSION=0.78
    PERLBREW_HOME=/home/afl/.perlbrew
    PERLBREW_MANPATH=/home/afl/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/home/afl/perlbrew
    PERLBREW_VERSION=0.78
    PERL_BADLANG (unset)
    SHELL=/usr/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Feb 02\, 2017 at 07&#8203;:58&#8203;:44AM \-0800\, Sergey Aleynikov wrote&#8203;:
> \# New Ticket Created by  Sergey Aleynikov 
> \# Please include the string&#8203;:  \[perl \#130701\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130701 >
> 
> 
> This is a bug report for perl from sergey\.aleynikov@&#8203;gmail\.com\,
> generated with the help of perlbug 1\.40 running under perl 5\.25\.9\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
> 
> While fuzzing perl v5\.25\.9\-35\-g32207c637b built with afl and run
> under libdislocator\, I found the following program
> 
> qr\!0\(?\{\}\)$\{return''\}\!
> 
> to use an initialized memory slot as a pointer to data\. This is a
> regression between v5\.16 and v5\.18\, bisect points to&#8203;:

This is a variant on the issue discussed in RT \#130651

\-\- 
I before E\. Except when it isn't\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Fri\, 03 Feb 2017 01&#8203;:27&#8203;:17 \-0800\, davem wrote&#8203;:
> On Thu\, Feb 02\, 2017 at 07&#8203;:58&#8203;:44AM \-0800\, Sergey Aleynikov wrote&#8203;:
> > While fuzzing perl v5\.25\.9\-35\-g32207c637b built with afl and run
> > under libdislocator\, I found the following program
> > 
> > qr\!0\(?\{\}\)$\{return''\}\!
> > 
> > to use an initialized memory slot as a pointer to data\. This is a
> > regression between v5\.16 and v5\.18\, bisect points to&#8203;:
> 
> This is a variant on the issue discussed in RT \#130651

If I understand \#130651\, then this isn't a seecurity issue\, since it would require either the attacker to be able to feed code directly to the interpreter\, or for C\<use re 'eval';> to be enabled\.

Am I wrong?

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

On Fri\, 27 Jan 2017 07&#8203;:05&#8203;:43 \-0800\, davem wrote&#8203;:
> On Thu\, Jan 26\, 2017 at 07&#8203;:13&#8203;:37AM \-0800\, Sergey Aleynikov wrote&#8203;:
> > While fuzzing perl v5\.25\.9\-35\-g32207c637b built with afl and run
> > under libdislocator\, I found the following program
> > 
> > qr\!@&#8203;\{return%0\}0\[\(?\{\!
> 
> A bit of an edge case this\. runtime qr//s which include code blocks
> are wrapped in a hidden sub to make all the closurey stuff work correctly\.
> So for example
> 
>     $r = qr/a$b\(?\{\.\.\.\}\)/
> 
> is roughly equivalent to
> 
>     @&#8203;args = sub \{
>                 \('a'\, $b\, sub\{\.\.\.\}\);
>             \}\->\(\);
>     $args = join ''\, @&#8203;args;
>     $r = qr/$args/
> 
> \(except that the inner sub isn't actually a separate anon sub \- its just a
> code block compiled as part of the outer anon sub\, and the code block gets
> passed to the regex compiler as\-is rather than being stringified and
> concatenated\.\)
> 
> The 'return' inside the @&#8203;\{\.\.\.\} expression is causing a return from the
> hidden sub\, returning nothing\, which then causes an assert fail inside
> Perl\_re\_op\_compile\, since its expecting at least 1 arg\.
> 
> The most immediate fix would be to make Perl\_re\_op\_compile\(\) robust in the
> presence of no \(or unexpected\) args\, but it is semantically incorrect\.
> The return should cause a return out of two levels of sub \- the hidden
> one\, and the expected one which the qr// is enclosed in\. There's already
> a mechanism for returning from two nested subs&#8203;: CXp\_SUB\_RE\_FAKE; but
> I don't yet see an easy way to get it set in this case\, without
> polluting pp\_entersub with more flags and special cases\.
> 
> I need to think some more\.

If I understand correctly\, this is bug in interpolation \- and isn't a security issue\.

Is that correct?

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue\, 22 Aug 2017 22&#8203;:46&#8203;:34 \-0700\, tonyc wrote&#8203;:
> If I understand correctly\, this is bug in interpolation \- and isn't a
> security issue\.
> 
> Is that correct?

Nevermind\, wrong ticket\.

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

On Fri\, 03 Feb 2017 01&#8203;:27&#8203;:17 \-0800\, davem wrote&#8203;:
> On Thu\, Feb 02\, 2017 at 07&#8203;:58&#8203;:44AM \-0800\, Sergey Aleynikov wrote&#8203;:
> > \# New Ticket Created by  Sergey Aleynikov 
> > \# Please include the string&#8203;:  \[perl \#130701\]
> > \# in the subject line of all future correspondence about this issue\. 
> > \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130701 >
> > 
> > 
> > This is a bug report for perl from sergey\.aleynikov@&#8203;gmail\.com\,
> > generated with the help of perlbug 1\.40 running under perl 5\.25\.9\.
> > 
> > 
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > \[Please describe your issue here\]
> > 
> > While fuzzing perl v5\.25\.9\-35\-g32207c637b built with afl and run
> > under libdislocator\, I found the following program
> > 
> > qr\!0\(?\{\}\)$\{return''\}\!
> > 
> > to use an initialized memory slot as a pointer to data\. This is a
> > regression between v5\.16 and v5\.18\, bisect points to&#8203;:
> 
> This is a variant on the issue discussed in RT \#130651
> 

Now public\, and I'll merge it into 130651\.

Tony
