### ISSUE TITLE
heap-buffer-overflow in Perl_pp_formline (pp_ctl.c:801)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15858]
Migrated from [rt.perl.org#130703](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130703) (status was 'resolved')

Searchable as RT130703$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.25\.9\-35\-g32207c637b built with afl and run
under libdislocator\, I found the following program

use bytes;
formline\("00X9q&#8203;:88////F/\\232/////\\000\\n\\x\{1b6\}XXXXXX\\210\\210\\21066666d"\);

to perform an access outside of allocated memory slot\. This is a
regression between v5\.14 and v5\.16\, bisect points to&#8203;:

26e935cfa6e70de1bd5258e0cb0f22ee976909f3 is the first bad commit
commit 26e935cfa6e70de1bd5258e0cb0f22ee976909f3
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Sun May 29 19&#8203;:27&#8203;:56 2011 \+0100

&nbsp;    pp\_formline&#8203;: handle growing better

&nbsp;    We initially grow PL\_formtarget by the largest amount a formline can
&nbsp;    append \(since formats are fixed width\)\. The only thing that can exceed
&nbsp;    that is @&#8203;\*; but also\, if PL\_formtarget gets upgraded to utf8\, then some of
&nbsp;    the extra buffer we allocated can get eaten up by the upgrade\.

&nbsp;    Codify this so we only grow when necessary\, but always enough\.

&nbsp;    Prior to this commit\, we were growing FF\_ITEM/FF\_LITERAL too much\, and
&nbsp;    FF\_LINEGLOB too little \(the latter being my mistake from a few commits
&nbsp;    ago\)\.

&nbsp;    Also rename 'fudge' to 'linemax'\, to give a better idea what it's for\.

ASAN diagnostics are

=================================================================
==14948==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
0x6110000095c8 at pc 0x0000004d35c8 bp 0x7ffd22db1e10 sp
0x7ffd22db15c0
WRITE of size 225 at 0x6110000095c8 thread T0
&nbsp;    \#0 0x4d35c7 in \_\_asan\_memcpy \(/home/afl/afl\-asan/perl\+0x4d35c7\)
&nbsp;    \#1 0xacea07 in Perl\_pp\_formline /home/afl/afl\-asan/pp\_ctl\.c&#8203;:801&#8203;:3
&nbsp;    \#2 0x84cb44 in Perl\_runops\_debug /home/afl/afl\-asan/dump\.c&#8203;:2450&#8203;:23
&nbsp;    \#3 0x5f1c15 in S\_run\_body /home/afl/afl\-asan/perl\.c&#8203;:2528&#8203;:2
&nbsp;    \#4 0x5f1c15 in perl\_run /home/afl/afl\-asan/perl\.c&#8203;:2451
&nbsp;    \#5 0x5224d2 in main /home/afl/afl\-asan/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#6 0x7fd980e972b0 in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x202b0\)
&nbsp;    \#7 0x43adb9 in \_start \(/home/afl/afl\-asan/perl\+0x43adb9\)

0x6110000095c8 is located 0 bytes to the right of 200\-byte region
\[0x611000009500\,0x6110000095c8\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4eaae0 in realloc \(/home/afl/afl\-asan/perl\+0x4eaae0\)
&nbsp;    \#1 0x8527d9 in Perl\_safesysrealloc /home/afl/afl\-asan/util\.c&#8203;:274&#8203;:18
&nbsp;    \#2 0x95eb7c in Perl\_sv\_grow /home/afl/afl\-asan/sv\.c&#8203;:1598&#8203;:17
&nbsp;    \#3 0xac9c72 in Perl\_pp\_formline /home/afl/afl\-asan/pp\_ctl\.c&#8203;:509&#8203;:9
&nbsp;    \#4 0x84cb44 in Perl\_runops\_debug /home/afl/afl\-asan/dump\.c&#8203;:2450&#8203;:23
&nbsp;    \#5 0x5f1c15 in S\_run\_body /home/afl/afl\-asan/perl\.c&#8203;:2528&#8203;:2
&nbsp;    \#6 0x5f1c15 in perl\_run /home/afl/afl\-asan/perl\.c&#8203;:2451
&nbsp;    \#7 0x5224d2 in main /home/afl/afl\-asan/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#8 0x7fd980e972b0 in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x202b0\)

Non\-asan builds on this source shows just an assertion failure&#8203;:

pp\_ctl\.c&#8203;:933&#8203;: Perl\_pp\_formline&#8203;: Assertion \`t \<
SvPVX\_const\(PL\_formtarget\) \+ SvLEN\(PL\_formtarget\)' failed

So here's a lesser\-minified version that overwrites a large chunk of
memory and causes a bus error&#8203;:

% hexdump \-C \.\./afl\-asan/0057\_3
00000000  75 73 65 20 62 79 74 65  73 3b 0a 70 72 69 6e 74  |use bytes;\.print|
00000010  66 20 66 6f 72 6d 6c 69  6e 65 22 40 23 58 39 71  |f formline"@&#8203;\#X9q|
00000020  3a 38 38 2f 2f 2f 2f 46  2f 9a 2f 2f 2f 2f 21 00  |&#8203;:88////F/\.////\!\.|
00000030  0a 00 61 87 20 20 73 75  63 20 70 36 36 36 db 36  |\.\.a\.  suc p666\.6|
00000040  36 20 31 3f 32 3a 33 36  d0 d0 d0 d0 d0 d0 d0 d0  |6 1?2&#8203;:36\.\.\.\.\.\.\.\.|
00000050  36 6c 6f 63 6b 36 36 4f  36 36 36 36 36 36 36 36  |6lock66O66666666|
00000060  44 f6 3a 6d 79 20 73 75  62 20 70 36 36 36 db 36  |D\.&#8203;:my sub p666\.6|
00000070  36 36 36 36 36 54 36 36  36 36 36 36 36 36 db 36  |66666T66666666\.6|
00000080  57 36 36 36 25 36 36 36  d0 d0 36 36 25 76 36 36  |W666%666\.\.66%v66|
00000090  36 36 36 36 36 36 36 36  36 36 36 36 36 37 36 36  |6666666666666766|
000000a0  36 36 36 5c 36 36 36 00  00 04 00 88 88 88 88 88  |666\\666\.\.\.\.\.\.\.\.\.|
000000b0  88 88 88 88 88 88 88 88  36 36 36 36 36 64 22 3b  |\.\.\.\.\.\.\.\.66666d";|
000000c0

% \./perl \-Ilib \.\./afl\-asan/0057\_3
zsh&#8203;: bus error  \./perl \-Ilib \.\./afl\-asan/0057\_3

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.25.9:

Configured by root at Sat Jan 14 02:25:05 MSK 2017.

Summary of my perl5 (revision 5 version 25 subversion 9) configuration:
  Commit id: cbe2fc5001aa59cdc73e04cc35e097a2ecfbeec0
  Platform:
    osname=linux
    osvers=3.16.0-4-amd64
    archname=x86_64-linux
    uname='linux dorothy 3.16.0-4-amd64 #1 smp debian 3.16.36-1+deb8u2
(2016-10-19) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING -Dcc=afl-clang-fast
-Doptimize=-O0 -g -ggdb3'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    bincompat5005=undef
  Compiler:
    cc='afl-clang-fast'
    ccflags ='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O0 -g -ggdb3'
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Clang 3.9.1 (tags/RELEASE_391/rc2)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='afl-clang-fast'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/lib
/usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu
/lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.24.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.24'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O0 -g -ggdb3 -L/usr/local/lib -fstack-protector-strong'



@INC for perl 5.25.9:
    lib
    /usr/local/lib/perl5/site_perl/5.25.9/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.25.9
    /usr/local/lib/perl5/5.25.9/x86_64-linux
    /usr/local/lib/perl5/5.25.9


Environment for perl 5.25.9:
    HOME=/home/afl
    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    PERLBREW_BASHRC_VERSION=0.78
    PERLBREW_HOME=/home/afl/.perlbrew
    PERLBREW_MANPATH=/home/afl/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/home/afl/perlbrew
    PERLBREW_VERSION=0.78
    PERL_BADLANG (unset)
    SHELL=/usr/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @dur-randir

[0057_3](https://rt-archive.perl.org/perl5/Ticket/Attachment/1447128/784714/0057_3)

**Comment by p5pRT** [comment]
### From @dur-randir

[0057_6](https://rt-archive.perl.org/perl5/Ticket/Attachment/1447128/784715/0057_6)

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Feb 02\, 2017 at 09&#8203;:44&#8203;:48AM \-0800\, Sergey Aleynikov wrote&#8203;:
> use bytes;
> formline\("00X9q&#8203;:88////F/\\232/////\\000\\n\\x\{1b6\}XXXXXX\\210\\210\\21066666d"\);

fixed by v5\.25\.9\-76\-ge452bf1 with a follow\-up in v5\.25\.9\-77\-g90c3aa0\.

I don't think this is a realistic security issue&#8203;: it requires an
attacker\-controlled format within a 'use bytes' scope\, which
seems a tad unlikely\.


\-\- 
"I do not resent criticism\, even when\, for the sake of emphasis\,
it parts for the time with reality"\.
&nbsp;    \-\- Winston Churchill\, House of Commons\, 22nd Jan 1941\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @dur-randir

2017\-02\-04 19&#8203;:14 GMT\+03&#8203;:00 Dave Mitchell via RT
\<perl5\-security\-report@&#8203;perl\.org>&#8203;:
> fixed by v5\.25\.9\-76\-ge452bf1 with a follow\-up in v5\.25\.9\-77\-g90c3aa0\.
>
> I don't think this is a realistic security issue&#8203;: it requires an
> attacker\-controlled format within a 'use bytes' scope\, which
> seems a tad unlikely\.

Unfortunately\, 90c3aa01208e3c5b9ab464a058bbd2f6ebda4ff4 introduced a
regression into pp\_formline\. I'm able to trigger various out\-of\-bounds
writes\, here's an example program and asan output&#8203;:

perl \-e 'formline"0000000000000@&#8203;\*00000000@&#8203;\*00000000@&#8203;\.\#"\,\-200\.\.0'

=================================================================
==21481==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
0x6040000095b8 at pc 0x00000093e7a6 bp 0x7ffd2a1e9b30 sp
0x7ffd2a1e9b28
WRITE of size 1 at 0x6040000095b8 thread T0
&nbsp;    \#0 0x93e7a5 in Perl\_pp\_formline /home/afl/afl\-asan\-fresh/pp\_ctl\.c&#8203;:924&#8203;:9
&nbsp;    \#1 0x815d06 in Perl\_runops\_standard /home/afl/afl\-asan\-fresh/run\.c&#8203;:41&#8203;:26
&nbsp;    \#2 0x5c9c0f in S\_run\_body /home/afl/afl\-asan\-fresh/perl\.c&#8203;:2523&#8203;:2
&nbsp;    \#3 0x5c9c0f in perl\_run /home/afl/afl\-asan\-fresh/perl\.c&#8203;:2446
&nbsp;    \#4 0x5223b2 in main /home/afl/afl\-asan\-fresh/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#5 0x7f4e941922b0 in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x202b0\)
&nbsp;    \#6 0x43ac99 in \_start \(/home/afl/afl\-asan\-fresh/perl\+0x43ac99\)

0x6040000095b8 is located 0 bytes to the right of 40\-byte region
\[0x604000009590\,0x6040000095b8\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4ea9c0 in realloc \(/home/afl/afl\-asan\-fresh/perl\+0x4ea9c0\)
&nbsp;    \#1 0x7877c4 in Perl\_safesysrealloc /home/afl/afl\-asan\-fresh/util\.c&#8203;:274&#8203;:18
&nbsp;    \#2 0x850576 in Perl\_sv\_grow /home/afl/afl\-asan\-fresh/sv\.c&#8203;:1598&#8203;:17
&nbsp;    \#3 0x939b96 in Perl\_pp\_formline /home/afl/afl\-asan\-fresh/pp\_ctl\.c&#8203;:511&#8203;:9
&nbsp;    \#4 0x815d06 in Perl\_runops\_standard /home/afl/afl\-asan\-fresh/run\.c&#8203;:41&#8203;:26
&nbsp;    \#5 0x5c9c0f in S\_run\_body /home/afl/afl\-asan\-fresh/perl\.c&#8203;:2523&#8203;:2
&nbsp;    \#6 0x5c9c0f in perl\_run /home/afl/afl\-asan\-fresh/perl\.c&#8203;:2446
&nbsp;    \#7 0x5223b2 in main /home/afl/afl\-asan\-fresh/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#8 0x7f4e941922b0 in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x202b0\)

SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow
/home/afl/afl\-asan\-fresh/pp\_ctl\.c&#8203;:924&#8203;:9 in Perl\_pp\_formline

**Comment by p5pRT** [comment]
### From @iabyn

On Fri\, Feb 17\, 2017 at 01&#8203;:28&#8203;:29AM \+0300\, Sergey Aleynikov wrote&#8203;:
> Unfortunately\, 90c3aa01208e3c5b9ab464a058bbd2f6ebda4ff4 introduced a
> regression into pp\_formline\. I'm able to trigger various out\-of\-bounds
> writes\, here's an example program and asan output&#8203;:
> 
> perl \-e 'formline"0000000000000@&#8203;\*00000000@&#8203;\*00000000@&#8203;\.\#"\,\-200\.\.0'

Whoops\. Now fixed with

commit f62fd06d790b3f8da5a193403a316ebbea86ba52
Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
AuthorDate&#8203;: Sat Feb 18 10&#8203;:20&#8203;:00 2017 \+0000
Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
CommitDate&#8203;: Sat Feb 18 10&#8203;:20&#8203;:00 2017 \+0000

&nbsp;    pp\_formline\(\)&#8203;: avoid buffer overrun
&nbsp;    
&nbsp;    RT \#130703
&nbsp;    
&nbsp;    My recent commit v5\.25\.9\-77\-g90c3aa0 attempted to simplify buffer growth
&nbsp;    in pp\_formline\(\)\, but missed the operators which append data to
&nbsp;    PL\_formtarget \*without\* doing 'goto append'\. These ops either append a
&nbsp;    fieldsize's worth of bytes\, or a \\n \(FF\_NEWLINE\)\. So grow by fieldsize
&nbsp;    whenever we fetch something new\, and for each FF\_NEWLINE\.


\-\- 
The Enterprise is involved in a bizarre time\-warp experience which is in
some way unconnected with the Late 20th Century\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#14
