### ISSUE TITLE
null pointer dereference in Perl_ck_return() - op.c:10990

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15879]
Migrated from [rt.perl.org#130815](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130815) (status was 'resolved')

Searchable as RT130815$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered with Perl v5\.25\.10 \(v5\.25\.9\-154\-gd8f2fe0\) while fuzzing with AFL\.

\./perl \-e 'm\(@&#8203;\{if\(0\)\{sub d\{\]\]\]\)\}return'
ASAN&#8203;:SIGSEGV
=================================================================
==29483==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000000
\(pc 0x000000560efe bp 0x7ffcc2b41050 sp 0x7ffcc2b40e10 T0\)
&nbsp;    \#0 0x560efd in Perl\_ck\_return /home/geeknik/perl/op\.c&#8203;:10990&#8203;:9
&nbsp;    \#1 0x5124fe in Perl\_op\_convert\_list /home/geeknik/perl/op\.c&#8203;:4889&#8203;:9
&nbsp;    \#2 0x6bffd2 in Perl\_yyparse /home/geeknik/perl/perly\.y&#8203;:883&#8203;:23
&nbsp;    \#3 0x59d611 in S\_parse\_body /home/geeknik/perl/perl\.c&#8203;:2376&#8203;:9
&nbsp;    \#4 0x593890 in perl\_parse /home/geeknik/perl/perl\.c&#8203;:1691&#8203;:2
&nbsp;    \#5 0x4dea05 in main /home/geeknik/perl/perlmain\.c&#8203;:121&#8203;:18
&nbsp;    \#6 0x7f61db447b44 in \_\_libc\_start\_main
/build/glibc\-qK83Be/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#7 0x4de69c in \_start \(/home/geeknik/perl/perl\+0x4de69c\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /home/geeknik/perl/op\.c&#8203;:10990 Perl\_ck\_return
==29483==ABORTING

**Comment by p5pRT** [comment]
### From @arc

Thanks for the report\. This is fixed in e5c165a0b7551ffb94661aa7f18aabadba257782\.

\-\- 
Aaron Crane \*\* http&#8203;://aaroncrane\.co\.uk/

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@arc - Status changed from 'open' to 'resolved'
