### ISSUE TITLE
null pointer dereference in Perl_yyparse()

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15881]
Migrated from [rt.perl.org#130819](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130819) (status was 'open')

Searchable as RT130819$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered with Perl v5\.25\.10 \(v5\.25\.9\-154\-gd8f2fe0\) while fuzzing with AFL\.

\./perl \-e 'm\(\(\(\)\)\(\(\)\)@&#8203;\{if\(0\)\{sub\{\]\]\]\)\}my;sub y'
ASAN&#8203;:SIGSEGV
=================================================================
==11415==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000000
\(pc 0x0000006c2346 bp 0x7ffc83abbe70 sp 0x7ffc83abbca0 T0\)
&nbsp;    \#0 0x6c2345 in Perl\_yyparse /home/geeknik/perl/perly\.y&#8203;:283&#8203;:10
&nbsp;    \#1 0x59d611 in S\_parse\_body /home/geeknik/perl/perl\.c&#8203;:2376&#8203;:9
&nbsp;    \#2 0x593890 in perl\_parse /home/geeknik/perl/perl\.c&#8203;:1691&#8203;:2
&nbsp;    \#3 0x4dea05 in main /home/geeknik/perl/perlmain\.c&#8203;:121&#8203;:18
&nbsp;    \#4 0x7fb2cc67ab44 in \_\_libc\_start\_main
/build/glibc\-qK83Be/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#5 0x4de69c in \_start \(/home/geeknik/perl/perl\+0x4de69c\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /home/geeknik/perl/perly\.y&#8203;:283 Perl\_yyparse
==11415==ABORTING

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Minimises to 'qq\(@&#8203;\{sub\{\]\]\]\)\}my;sub z'\.  Looks to be the same mechanism as
\[perl \#126191\]\.

\-zefram

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by zb226** [comment]
RT#126191 mentioned here is the closed issue #14940. There's two more mentions of RT#126191: #14739 and #15570 which are closed as well. All three reference [bb4e4c3](https://github.com/Perl/perl5/commit/bb4e4c3869d9fb6ee5bddd820c2a373601ecc310) as the fix. Bisecting for this issue brought up the same commit:

```
commit bb4e4c3869d9fb6ee5bddd820c2a373601ecc310
Author: Tony Cook <tony@develop-help.com>
Date:   Tue Jan 30 16:40:53 2018 +1100

    (perl #125351) abort parsing if parse errors happen in a sub lex
(...)
```

So I think it can be closed as well.
