### ISSUE TITLE
Perl enters infinite loop with -d:Trace and binmode(STDERR, encoding(UTF-8))

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15921]
Migrated from [rt.perl.org#131115](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131115) (status was 'open')

Searchable as RT131115$

**Comment by p5pRT** [comment]
### From @wolfsage

Originally brought to my attention by tudor on \#moose&#8203;:

These are fine&#8203;:

&nbsp;   perl \-d&#8203;:Trace \-e 'binmode\(STDERR\, "&#8203;:encoding\(UTF\-8\)"\);' 2>&1
&nbsp;   perl \-d&#8203;:Trace \-e 'binmode\(STDERR\, "&#8203;:encoding\(UTF\-8\)"\);' | tee out\.txt

These enter infinite loops&#8203;:

&nbsp;  perl \-d&#8203;:Trace \-e 'binmode\(STDERR\, "&#8203;:encoding\(UTF\-8\)"\);' 2>&1 | tee out\.txt
&nbsp;  perl \-d&#8203;:Trace \-e 'binmode\(STDERR\, "&#8203;:encoding\(UTF\-8\)"\);' 2>&1 | grep thing

CPU is at 100%\, and if I attach to perl with gdb and grab a backtrace&#8203;:

&nbsp;  \(gdb\) bt
&nbsp;  \#0  0x00007fbb8a4a6780 in Perl\_PerlIO\_flush \(\) from /usr/lib/libperl\.so\.5\.18
&nbsp;  \#1  0x00007fbb8a4a761c in PerlIOBuf\_write \(\) from /usr/lib/libperl\.so\.5\.18
&nbsp;  \#2  0x00007fbb8a4855f5 in Perl\_do\_print \(\) from /usr/lib/libperl\.so\.5\.18
&nbsp;  \#3  0x00007fbb8a40dae7 in Perl\_write\_to\_stderr \(\) from
/usr/lib/libperl\.so\.5\.18
&nbsp;  \#4  0x00007fbb8a468c9d in Perl\_die\_unwind \(\) from /usr/lib/libperl\.so\.5\.18
&nbsp;  \#5  0x00007fbb8a40e5a9 in Perl\_vcroak \(\) from /usr/lib/libperl\.so\.5\.18
&nbsp;  \#6  0x00007fbb8a40efa7 in Perl\_croak \(\) from /usr/lib/libperl\.so\.5\.18
&nbsp;  \#7  0x00007fbb8a42b6ca in ?? \(\) from /usr/lib/libperl\.so\.5\.18
&nbsp;  \#8  0x00007fbb8a433eea in Perl\_pp\_method \(\) from /usr/lib/libperl\.so\.5\.18
&nbsp;  \#9  0x00007fbb8a42b266 in Perl\_runops\_standard \(\) from
/usr/lib/libperl\.so\.5\.18
&nbsp;  \#10 0x00007fbb8a3bc25c in Perl\_call\_sv \(\) from /usr/lib/libperl\.so\.5\.18
&nbsp;  \#11 0x00007fbb88bf4ca0 in PerlIOEncode\_flush \(\)
&nbsp;     from /usr/lib/perl/5\.18/auto/PerlIO/encoding/encoding\.so
&nbsp;  \#12 0x00007fbb8a4a67bf in Perl\_PerlIO\_flush \(\) from /usr/lib/libperl\.so\.5\.18
&nbsp;  \#13 0x00007fbb8a4a761c in PerlIOBuf\_write \(\) from /usr/lib/libperl\.so\.5\.18
&nbsp;  \#14 0x00007fbb8a4855f5 in Perl\_do\_print \(\) from /usr/lib/libperl\.so\.5\.18
&nbsp;  \#15 0x00007fbb8a42d4cf in Perl\_pp\_print \(\) from /usr/lib/libperl\.so\.5\.18
&nbsp;  \#16 0x00007fbb8a42b266 in Perl\_runops\_standard \(\) from
/usr/lib/libperl\.so\.5\.18
&nbsp;  \#17 0x00007fbb8a3bc25c in Perl\_call\_sv \(\) from /usr/lib/libperl\.so\.5\.18
 \#18 0x00007fbb88bf3459 in PerlIOEncode\_pushed \(\)
&nbsp;      from /usr/lib/perl/5\.18/auto/PerlIO/encoding/encoding\.so
&nbsp;  \#19 0x00007fbb8a4a630e in PerlIO\_push \(\) from /usr/lib/libperl\.so\.5\.18
&nbsp;  \#20 0x00007fbb8a4a6449 in PerlIO\_apply\_layera \(\) from /usr/lib/libperl\.so\.5\.18
&nbsp;  \-\-\-Type \<return> to continue\, or q \<return> to quit\-\-\-
&nbsp;  \#21 0x00007fbb8a4a6528 in PerlIO\_apply\_layers \(\) from /usr/lib/libperl\.so\.5\.18
&nbsp;  \#22 0x00007fbb8a4a6591 in PerlIO\_binmode \(\) from /usr/lib/libperl\.so\.5\.18
&nbsp;  \#23 0x00007fbb8a472ba0 in Perl\_pp\_binmode \(\) from /usr/lib/libperl\.so\.5\.18
&nbsp;  \#24 0x00007fbb8a42b266 in Perl\_runops\_standard \(\) from
/usr/lib/libperl\.so\.5\.18
&nbsp;  \#25 0x00007fbb8a3c3b44 in perl\_run \(\) from /usr/lib/libperl\.so\.5\.18
&nbsp;  \#26 0x0000000000400dd9 in main \(\)

Also tested with 5\.24\.1\, and blead\.

\-\- Matthew Horsfall \(alh\)

**Comment by p5pRT** [comment]
### From @shlomif

On Fri\, 07 Apr 2017 06&#8203;:13&#8203;:38 \-0700
Matthew Horsfall \(via RT\) \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

> Created by  Matthew Horsfall 
> \# Please include the string&#8203;:  \[perl \#131115\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131115 >
> 
> 
> Originally brought to my attention by tudor on \#moose&#8203;:
> 
> These are fine&#8203;:
> 
>    perl \-d&#8203;:Trace \-e 'binmode\(STDERR\, "&#8203;:encoding\(UTF\-8\)"\);' 2>&1
>    perl \-d&#8203;:Trace \-e 'binmode\(STDERR\, "&#8203;:encoding\(UTF\-8\)"\);' | tee out\.txt
> 
> These enter infinite loops&#8203;:
> 
>   perl \-d&#8203;:Trace \-e 'binmode\(STDERR\, "&#8203;:encoding\(UTF\-8\)"\);' 2>&1 | tee out\.txt
>   perl \-d&#8203;:Trace \-e 'binmode\(STDERR\, "&#8203;:encoding\(UTF\-8\)"\);' 2>&1 | grep thing
>

Just for the record \- I can reproduce this problem on Mageia x86\-64 v6 \(Linux\)
with&#8203;:

 shlomif@&#8203;telaviv1&#8203;:\~$ perl \-v

This is perl 5\, version 22\, subversion 3 \(v5\.22\.3\) built for
x86\_64\-linux\-thread\-multi \(with 1 registered patch\, see perl \-V for more detail\)

Copyright 1987\-2017\, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License\, which may be found in the Perl 5 source kit\.

Complete documentation for Perl\, including FAQ lists\, should be found on
this system using "man perl" or "perldoc perl"\.  If you have access to the
Internet\, point your browser at http&#8203;://www\.perl\.org/\, the Perl Home Page\.

shlomif@&#8203;telaviv1&#8203;:\~$ 


Regards\,

&nbsp;    Shlomi Fish


\-\- 


---
Shlomi Fish       http&#8203;://www\.shlomifish\.org/

How many “one\-liners” do I actually write? I don’t know; maybe a couple dozen
a day\. But I guess I must be unusual\, because as we all know\, AWK was a
complete failure and vanished into obscurity since it didn’t address anyone’s
real needs\. \(That was sarcasm\.\) — “Twelve Views of Mark Jason Dominus”

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Fri\, 07 Apr 2017 06&#8203;:13&#8203;:38 \-0700\, alh wrote&#8203;:
> Originally brought to my attention by tudor on \#moose&#8203;:
> 
> These are fine&#8203;:
> 
> perl \-d&#8203;:Trace \-e 'binmode\(STDERR\, "&#8203;:encoding\(UTF\-8\)"\);' 2>&1
> perl \-d&#8203;:Trace \-e 'binmode\(STDERR\, "&#8203;:encoding\(UTF\-8\)"\);' | tee out\.txt
> 
> These enter infinite loops&#8203;:
> 
> perl \-d&#8203;:Trace \-e 'binmode\(STDERR\, "&#8203;:encoding\(UTF\-8\)"\);' 2>&1 | tee
> out\.txt
> perl \-d&#8203;:Trace \-e 'binmode\(STDERR\, "&#8203;:encoding\(UTF\-8\)"\);' 2>&1 | grep
> thing
> 
> CPU is at 100%\, and if I attach to perl with gdb and grab a backtrace&#8203;:
> 
> \(gdb\) bt
> \#0  0x00007fbb8a4a6780 in Perl\_PerlIO\_flush \(\) from
> /usr/lib/libperl\.so\.5\.18
> \#1  0x00007fbb8a4a761c in PerlIOBuf\_write \(\) from
> /usr/lib/libperl\.so\.5\.18
> \#2  0x00007fbb8a4855f5 in Perl\_do\_print \(\) from
> /usr/lib/libperl\.so\.5\.18
> \#3  0x00007fbb8a40dae7 in Perl\_write\_to\_stderr \(\) from
> /usr/lib/libperl\.so\.5\.18
> \#4  0x00007fbb8a468c9d in Perl\_die\_unwind \(\) from
> /usr/lib/libperl\.so\.5\.18
> \#5  0x00007fbb8a40e5a9 in Perl\_vcroak \(\) from /usr/lib/libperl\.so\.5\.18
> \#6  0x00007fbb8a40efa7 in Perl\_croak \(\) from /usr/lib/libperl\.so\.5\.18
> \#7  0x00007fbb8a42b6ca in ?? \(\) from /usr/lib/libperl\.so\.5\.18
> \#8  0x00007fbb8a433eea in Perl\_pp\_method \(\) from
> /usr/lib/libperl\.so\.5\.18
> \#9  0x00007fbb8a42b266 in Perl\_runops\_standard \(\) from
> /usr/lib/libperl\.so\.5\.18
> \#10 0x00007fbb8a3bc25c in Perl\_call\_sv \(\) from
> /usr/lib/libperl\.so\.5\.18
> \#11 0x00007fbb88bf4ca0 in PerlIOEncode\_flush \(\)
>    from /usr/lib/perl/5\.18/auto/PerlIO/encoding/encoding\.so
> \#12 0x00007fbb8a4a67bf in Perl\_PerlIO\_flush \(\) from
> /usr/lib/libperl\.so\.5\.18
> \#13 0x00007fbb8a4a761c in PerlIOBuf\_write \(\) from
> /usr/lib/libperl\.so\.5\.18
> \#14 0x00007fbb8a4855f5 in Perl\_do\_print \(\) from
> /usr/lib/libperl\.so\.5\.18
> \#15 0x00007fbb8a42d4cf in Perl\_pp\_print \(\) from
> /usr/lib/libperl\.so\.5\.18
> \#16 0x00007fbb8a42b266 in Perl\_runops\_standard \(\) from
> /usr/lib/libperl\.so\.5\.18
> \#17 0x00007fbb8a3bc25c in Perl\_call\_sv \(\) from
> /usr/lib/libperl\.so\.5\.18
> \#18 0x00007fbb88bf3459 in PerlIOEncode\_pushed \(\)
>     from /usr/lib/perl/5\.18/auto/PerlIO/encoding/encoding\.so
> \#19 0x00007fbb8a4a630e in PerlIO\_push \(\) from /usr/lib/libperl\.so\.5\.18
> \#20 0x00007fbb8a4a6449 in PerlIO\_apply\_layera \(\) from
> /usr/lib/libperl\.so\.5\.18
> \-\-\-Type \<return> to continue\, or q \<return> to quit\-\-\-
> \#21 0x00007fbb8a4a6528 in PerlIO\_apply\_layers \(\) from
> /usr/lib/libperl\.so\.5\.18
> \#22 0x00007fbb8a4a6591 in PerlIO\_binmode \(\) from
> /usr/lib/libperl\.so\.5\.18
> \#23 0x00007fbb8a472ba0 in Perl\_pp\_binmode \(\) from
> /usr/lib/libperl\.so\.5\.18
> \#24 0x00007fbb8a42b266 in Perl\_runops\_standard \(\) from
> /usr/lib/libperl\.so\.5\.18
> \#25 0x00007fbb8a3c3b44 in perl\_run \(\) from /usr/lib/libperl\.so\.5\.18
> \#26 0x0000000000400dd9 in main \(\)
> 
> Also tested with 5\.24\.1\, and blead\.

I don't have Devel&#8203;::Trace installed \(I'm working with an uninstalled blead tree\)\, but I see an infinite loop with \-Dt with a \-DDEBUGGING build too\.

I expect what's happening in your case is Devel&#8203;::Trace is trying to trace the call to $encoding\->renew\(\) or $encoding\->needs\_lines\(\) \(both of which are done with G\_EVAL\)\, writing to STDERR\, which tries to use the partly initialised PerlIO&#8203;::encoding layer and dies\, which tries to write to the stream calling PerlIO\_flush\(\)\.

This loops because PerlIO&#8203;::encoding prevents recursive calls to $encoding\->encode\(\)\, losing the output rather than recursving infinitely\.

With \-Dt \(in blead at least\) it seems to get stuck earlier in the call to Encode&#8203;::find\_encoding\(\)\, but you get a similar result\.

The debugger doesn't seem to have a problem with this code\, presumably because it either clones STDERR or opens the TTY\.

Possible fixes&#8203;:

\- Devel&#8203;::Trace could clone STDERR and write to that clone\, this should work for older perls too\.

\- perl's \-D switch could do something similar\.

\- perl \(perhaps in PerlIO&#8203;::encoding\) could disable both \-Dt tracing and debugger tracing when pushing a layer onto or writing to STDERR\.  This might be a bit too magical though\.

Tony
