### ISSUE TITLE
segfault in S_mg_findext_flags()

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15942]
Migrated from [rt.perl.org#131101](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131101) (status was 'open')

Searchable as RT131101$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered with v5\.25\.11\-28\-g5fc3895\. Compiled with afl\-clang\-fast on Debian
8 x64\.

\#0 0x82fa26 in S\_mg\_findext\_flags /root/perl/mg\.c&#8203;:413&#8203;:10
\#1 0x82fa26 in Perl\_mg\_find\_mglob /root/perl/mg\.c&#8203;:462
\#2 0x8d20fc in Perl\_pp\_match /root/perl/pp\_hot\.c&#8203;:2129&#8203;:18
\#3 0x80077b in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2451&#8203;:23
\#4 0x5a2073 in S\_run\_body /root/perl/perl\.c&#8203;:2524&#8203;:2
\#5 0x5a2073 in perl\_run /root/perl/perl\.c&#8203;:2447
\#6 0x4de98d in main /root/perl/perlmain\.c&#8203;:123&#8203;:9
\#7 0x7ff1449c5b44 in \_\_libc\_start\_main
/build/glibc\-qK83Be/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
\#8 0x4de5fc in \_start \(/root/perl/perl\+0x4de5fc\)

**Comment by p5pRT** [comment]
### From @geeknik

[test043](https://rt-archive.perl.org/perl5/Ticket/Attachment/1455816/790234/test043)

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, Apr 04\, 2017 at 04&#8203;:51&#8203;:50PM \-0700\, Brian Carpenter wrote&#8203;:
> \# New Ticket Created by  Brian Carpenter 
> \# Please include the string&#8203;:  \[perl \#131101\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131101 >
> 
> 
> Triggered with v5\.25\.11\-28\-g5fc3895\. Compiled with afl\-clang\-fast on Debian
> 8 x64\.
> 
> \#0 0x82fa26 in S\_mg\_findext\_flags /root/perl/mg\.c&#8203;:413&#8203;:10
> \#1 0x82fa26 in Perl\_mg\_find\_mglob /root/perl/mg\.c&#8203;:462
> \#2 0x8d20fc in Perl\_pp\_match /root/perl/pp\_hot\.c&#8203;:2129&#8203;:18
> \#3 0x80077b in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2451&#8203;:23
> \#4 0x5a2073 in S\_run\_body /root/perl/perl\.c&#8203;:2524&#8203;:2
> \#5 0x5a2073 in perl\_run /root/perl/perl\.c&#8203;:2447
> \#6 0x4de98d in main /root/perl/perlmain\.c&#8203;:123&#8203;:9
> \#7 0x7ff1449c5b44 in \_\_libc\_start\_main
> /build/glibc\-qK83Be/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
> \#8 0x4de5fc in \_start \(/root/perl/perl\+0x4de5fc\)

It can be reduced to

&nbsp;    map /x/g\, \(%h = \("y"\, 0\)\)\, \(%h = \("y"\, 0\)\)

It's a stack\-not\-refcounted bug\.

\-\- 
A power surge on the Bridge is rapidly and correctly diagnosed as a faulty
capacitor by the highly\-trained and competent engineering staff\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#9

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'
