### ISSUE TITLE
heap-buffer-overflow (READ of size 1) in Perl_my_atof2()

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16002]
Migrated from [rt.perl.org#131526](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131526) (status was 'resolved')

Searchable as RT131526$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered with v5\.27\.0\-97\-gd555ed0\, compiled with afl\-clang\-fast on Debian
8 x64\.

==11137==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
0x60300000e87a at pc 0x10cfcad bp 0x7ffff61acd30 sp 0x7ffff61acd28
READ of size 1 at 0x60300000e87a thread T0
&nbsp;    \#0 0x10cfcac in Perl\_my\_atof2 /root/perl/numeric\.c&#8203;:1490
&nbsp;    \#1 0x10d08e1 in Perl\_my\_atof /root/perl/numeric\.c&#8203;:1244
&nbsp;    \#2 0xb01bf4 in S\_sv\_setnv /root/perl/sv\.c&#8203;:2111
&nbsp;    \#3 0xbc07a9 in S\_sv\_2iuv\_common /root/perl/sv\.c&#8203;:2313
&nbsp;    \#4 0xbc7b77 in Perl\_sv\_2iv\_flags /root/perl/sv\.c&#8203;:2506
&nbsp;    \#5 0xc98ec0 in Perl\_pp\_subtract /root/perl/pp\.c&#8203;:1950
&nbsp;    \#6 0x926e76 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2451
&nbsp;    \#7 0x59f02a in S\_run\_body /root/perl/perl\.c&#8203;:2543
&nbsp;    \#8 0x59f02a in perl\_run /root/perl/perl\.c&#8203;:2471
&nbsp;    \#9 0x43506d in main /root/perl/perlmain\.c&#8203;:123
&nbsp;    \#10 0x7f5015730b44 in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x21b44\)
&nbsp;    \#11 0x436015 \(/root/perl/perl\+0x436015\)

0x60300000e87a is located 0 bytes to the right of 26\-byte region
\[0x60300000e860\,0x60300000e87a\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x7f50168829f6 in \_\_interceptor\_realloc
\(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.1\+0x549f6\)
&nbsp;    \#1 0x96d481 in Perl\_safesysrealloc /root/perl/util\.c&#8203;:274

SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow /root/perl/numeric\.c&#8203;:1490
Perl\_my\_atof2

**Comment by p5pRT** [comment]
### From @geeknik

[test39.pl](https://rt-archive.perl.org/perl5/Ticket/Attachment/1464238/795088/test39.pl)

**Comment by p5pRT** [comment]
### From @tonycoz

On Wed\, 07 Jun 2017 00&#8203;:59&#8203;:50 \-0700\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> Triggered with v5\.27\.0\-97\-gd555ed0\, compiled with afl\-clang\-fast on Debian
> 8 x64\.
> 
> ==11137==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
> 0x60300000e87a at pc 0x10cfcad bp 0x7ffff61acd30 sp 0x7ffff61acd28
> READ of size 1 at 0x60300000e87a thread T0
>     \#0 0x10cfcac in Perl\_my\_atof2 /root/perl/numeric\.c&#8203;:1490
>     \#1 0x10d08e1 in Perl\_my\_atof /root/perl/numeric\.c&#8203;:1244
>     \#2 0xb01bf4 in S\_sv\_setnv /root/perl/sv\.c&#8203;:2111
>     \#3 0xbc07a9 in S\_sv\_2iuv\_common /root/perl/sv\.c&#8203;:2313
>     \#4 0xbc7b77 in Perl\_sv\_2iv\_flags /root/perl/sv\.c&#8203;:2506
>     \#5 0xc98ec0 in Perl\_pp\_subtract /root/perl/pp\.c&#8203;:1950
>     \#6 0x926e76 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2451
>     \#7 0x59f02a in S\_run\_body /root/perl/perl\.c&#8203;:2543
>     \#8 0x59f02a in perl\_run /root/perl/perl\.c&#8203;:2471
>     \#9 0x43506d in main /root/perl/perlmain\.c&#8203;:123
>     \#10 0x7f5015730b44 in \_\_libc\_start\_main
> \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x21b44\)
>     \#11 0x436015 \(/root/perl/perl\+0x436015\)
> 
> 0x60300000e87a is located 0 bytes to the right of 26\-byte region
> \[0x60300000e860\,0x60300000e87a\)
> allocated by thread T0 here&#8203;:
>     \#0 0x7f50168829f6 in \_\_interceptor\_realloc
> \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.1\+0x549f6\)
>     \#1 0x96d481 in Perl\_safesysrealloc /root/perl/util\.c&#8203;:274
> 
> SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow /root/perl/numeric\.c&#8203;:1490
> Perl\_my\_atof2

This tries to read from a file\, using the script as its own input worked for me\.

This is caused by this code&#8203;:

&nbsp;    else if \(\!seen\_dp && GROK\_NUMERIC\_RADIX\(&s\, send\)\) \{
&nbsp;        seen\_dp = 1;
&nbsp;        if \(sig\_digits > MAX\_SIG\_DIGITS\) \{
&nbsp;        do \{
&nbsp;            \+\+s;
&nbsp;        \} while \(isDIGIT\(\*s\)\);
&nbsp;        break;
&nbsp;        \}
&nbsp;    \}

GROK\_NUMERIC\_RADIX\(\) increments s past the decimal point\, which is at the end of string in this case\, so the following \+\+s steps past the NUL\.

I have a fix testing now\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon\, 12 Jun 2017 23&#8203;:30&#8203;:52 \-0700\, tonyc wrote&#8203;:
> On Wed\, 07 Jun 2017 00&#8203;:59&#8203;:50 \-0700\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> > Triggered with v5\.27\.0\-97\-gd555ed0\, compiled with afl\-clang\-fast on
> > Debian
> > 8 x64\.
> >
> > ==11137==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
> > 0x60300000e87a at pc 0x10cfcad bp 0x7ffff61acd30 sp 0x7ffff61acd28
> > READ of size 1 at 0x60300000e87a thread T0
> >     \#0 0x10cfcac in Perl\_my\_atof2 /root/perl/numeric\.c&#8203;:1490
> >     \#1 0x10d08e1 in Perl\_my\_atof /root/perl/numeric\.c&#8203;:1244
> >     \#2 0xb01bf4 in S\_sv\_setnv /root/perl/sv\.c&#8203;:2111
> >     \#3 0xbc07a9 in S\_sv\_2iuv\_common /root/perl/sv\.c&#8203;:2313
> >     \#4 0xbc7b77 in Perl\_sv\_2iv\_flags /root/perl/sv\.c&#8203;:2506
> >     \#5 0xc98ec0 in Perl\_pp\_subtract /root/perl/pp\.c&#8203;:1950
> >     \#6 0x926e76 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2451
> >     \#7 0x59f02a in S\_run\_body /root/perl/perl\.c&#8203;:2543
> >     \#8 0x59f02a in perl\_run /root/perl/perl\.c&#8203;:2471
> >     \#9 0x43506d in main /root/perl/perlmain\.c&#8203;:123
> >     \#10 0x7f5015730b44 in \_\_libc\_start\_main
> > \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x21b44\)
> >     \#11 0x436015 \(/root/perl/perl\+0x436015\)
> >
> > 0x60300000e87a is located 0 bytes to the right of 26\-byte region
> > \[0x60300000e860\,0x60300000e87a\)
> > allocated by thread T0 here&#8203;:
> >     \#0 0x7f50168829f6 in \_\_interceptor\_realloc
> > \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.1\+0x549f6\)
> >     \#1 0x96d481 in Perl\_safesysrealloc /root/perl/util\.c&#8203;:274
> >
> > SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow
> > /root/perl/numeric\.c&#8203;:1490
> > Perl\_my\_atof2
> 
> This tries to read from a file\, using the script as its own input
> worked for me\.
> 
> This is caused by this code&#8203;:
> 
> else if \(\!seen\_dp && GROK\_NUMERIC\_RADIX\(&s\, send\)\) \{
>     seen\_dp = 1;
>     if \(sig\_digits > MAX\_SIG\_DIGITS\) \{
>         do \{
>             \+\+s;
>         \} while \(isDIGIT\(\*s\)\);
>         break;
>     \}
> \}
> 
> GROK\_NUMERIC\_RADIX\(\) increments s past the decimal point\, which is at
> the end of string in this case\, so the following \+\+s steps past the
> NUL\.
> 
> I have a fix testing now\.

Fixed in 9604fbf0722bd97ca6031a263c50ad52b6633db7\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release yesterday of Perl 5\.28\.0\, this and 185 other issues have been
resolved\.

Perl 5\.28\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.28.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
