### ISSUE TITLE
heap-buffer-overflow (WRITE of size 8) in Perl_pp_reverse()

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16012]
Migrated from [rt.perl.org#131555](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131555) (status was 'resolved')

Searchable as RT131555$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered in Perl v5\.27\.0\-97\-gd555ed0\, compiled with afl\-clang\-fast on
Debian 8 x64\.

==376==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
0x619000009a80 at pc 0xd1b9c4 bp 0x7ffd21892230 sp 0x7ffd21892228
WRITE of size 8 at 0x619000009a80 thread T0
&nbsp;    \#0 0xd1b9c3 in Perl\_pp\_reverse /root/perl/pp\.c&#8203;:5740
&nbsp;    \#1 0x926e76 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2451
&nbsp;    \#2 0x59f02a in S\_run\_body /root/perl/perl\.c&#8203;:2543
&nbsp;    \#3 0x59f02a in perl\_run /root/perl/perl\.c&#8203;:2471
&nbsp;    \#4 0x43506d in main /root/perl/perlmain\.c&#8203;:123
&nbsp;    \#5 0x7f474413cb44 in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x21b44\)
&nbsp;    \#6 0x436015 \(/root/perl/perl\+0x436015\)

0x619000009a80 is located 0 bytes to the right of 1024\-byte region
\[0x619000009680\,0x619000009a80\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x7f474528e73f in malloc
\(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.1\+0x5473f\)
&nbsp;    \#1 0x962c71 in Perl\_safesysmalloc /root/perl/util\.c&#8203;:153

SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow /root/perl/pp\.c&#8203;:5740
Perl\_pp\_reverse

**Comment by p5pRT** [comment]
### From @geeknik

[test206.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1465632/795588/test206.gz)

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Jun 11\, 2017 at 12&#8203;:53&#8203;:30PM \-0700\, Brian Carpenter wrote&#8203;:
> ==376==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
> 0x619000009a80 at pc 0xd1b9c4 bp 0x7ffd21892230 sp 0x7ffd21892228
> WRITE of size 8 at 0x619000009a80 thread T0
>     \#0 0xd1b9c3 in Perl\_pp\_reverse /root/perl/pp\.c&#8203;:5740
>     \#1 0x926e76 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2451
>     \#2 0x59f02a in S\_run\_body /root/perl/perl\.c&#8203;:2543
>     \#3 0x59f02a in perl\_run /root/perl/perl\.c&#8203;:2471
>     \#4 0x43506d in main /root/perl/perlmain\.c&#8203;:123
>     \#5 0x7f474413cb44 in \_\_libc\_start\_main
> \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x21b44\)
>     \#6 0x436015 \(/root/perl/perl\+0x436015\)

scalar context reverse doesn't extend the stack before pushing the result\.
This is safe unless reverse doesn't have an argument \(when it defaults to
$\_\)\.

The following code can trigger it&#8203;:

&nbsp;    $\_ = "";
&nbsp;    for my $i \(1\.\.1000\) \{
&nbsp;        \(\) = \(1\.\.$i\, scalar reverse\);
&nbsp;    \}

\-\- 
The crew of the Enterprise encounter an alien life form which is
surprisingly neither humanoid nor made from pure energy\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#22

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Jun 11\, 2017 at 10&#8203;:43&#8203;:42PM \+0100\, Dave Mitchell wrote&#8203;:
> On Sun\, Jun 11\, 2017 at 12&#8203;:53&#8203;:30PM \-0700\, Brian Carpenter wrote&#8203;:
> > ==376==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
> > 0x619000009a80 at pc 0xd1b9c4 bp 0x7ffd21892230 sp 0x7ffd21892228
> > WRITE of size 8 at 0x619000009a80 thread T0
> >     \#0 0xd1b9c3 in Perl\_pp\_reverse /root/perl/pp\.c&#8203;:5740
> >     \#1 0x926e76 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2451
> >     \#2 0x59f02a in S\_run\_body /root/perl/perl\.c&#8203;:2543
> >     \#3 0x59f02a in perl\_run /root/perl/perl\.c&#8203;:2471
> >     \#4 0x43506d in main /root/perl/perlmain\.c&#8203;:123
> >     \#5 0x7f474413cb44 in \_\_libc\_start\_main
> > \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x21b44\)
> >     \#6 0x436015 \(/root/perl/perl\+0x436015\)
> 
> scalar context reverse doesn't extend the stack before pushing the result\.
> This is safe unless reverse doesn't have an argument \(when it defaults to
> $\_\)\.
> 
> The following code can trigger it&#8203;:
> 
>     $\_ = "";
>     for my $i \(1\.\.1000\) \{
>         \(\) = \(1\.\.$i\, scalar reverse\);
>     \}

But I don't think its \(much of\) a security issue\.
The attacker would need to find some code that uses argless reverse\(\) in
scalar context\, where reverse\(\) is called when the args stack is exactly
full\. In this case\, the address of the reverse op's target SV will be
written to the 4 or 8 bytes following the malloced stack block\. The
attacker can't control what is written\.

Unless anyone objects\, in a couple of days time I'll push a fix and move
this to the public queue\.

\-\- 
My get\-up\-and\-go just got up and went\.

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Jun 12\, 2017 at 08&#8203;:54&#8203;:32AM \+0100\, Dave Mitchell wrote&#8203;:
> But I don't think its \(much of\) a security issue\.
> The attacker would need to find some code that uses argless reverse\(\) in
> scalar context\, where reverse\(\) is called when the args stack is exactly
> full\. In this case\, the address of the reverse op's target SV will be
> written to the 4 or 8 bytes following the malloced stack block\. The
> attacker can't control what is written\.
> 
> Unless anyone objects\, in a couple of days time I'll push a fix and move
> this to the public queue\.

Since then I've been doing some thinking and decided that this sort of
thing ought to be automated\. So I have a branch \(not pushed yet\) which on
debugging builds&#8203;:

\* makes the runops loop set a high\-water\-mark \(HWM\) variable equal to
&nbsp;  PL\_stack\_sp just before calling each pp function;

\* modifies EXTEND\(\) etc to update this HWM;

\* on return from the pp function checks whether PL\_stack\_sp is > HWM\,
&nbsp;  and if so panics\.

This seems to work very well\, and has found the following bugs \- all of
which I have fixed in my branch \- with no false positives&#8203;:

\* Not extending the stack by 1 \(typically to return a scalar context result\)&#8203;:

&nbsp;    \* pp\_match/pp\_subst \(in variants where their args aren't supplied on
&nbsp;      the stack\)
&nbsp;    \* reverse\(\) \- the subject of this ticket
&nbsp;    \* empty list slice
&nbsp;    \* argless reset\(\)
&nbsp;    \* pp\_leavewrite
&nbsp;    \* recv&#8203;: in fact it wasn't popping its four args before returning undef
&nbsp;      on failure \-so it actually returned 5 args on failure\, which in
&nbsp;      scalar context used the last one\.
&nbsp;    \* Time&#8203;::Piece&#8203;::tzoffset\(\) called a private XS function which
&nbsp;      extended the stack by 9\, then returned 10 elements

\* Not extending the stack by N&#8203;:

&nbsp;    \* XS&#8203;::APItest&#8203;::test\_hv\_free\_ent\(\)&#8203;: not important as this is only an
&nbsp;        internal test XS function

&nbsp;    \* List&#8203;::Util&#8203;::pairmap\(\)&#8203;: didn't grow the stack if it returned more
&nbsp;      values than it was passed\. pairmap\(\) is like map\(\) except that in
&nbsp;      each iteration it consumes 2 args\, setting $a and $b to them\. In
&nbsp;      something like
&nbsp;        @&#8203;result = pairmap \{ \(1\,2\,3\) \} 10\,11\, 20\,21\, 30\,31;
&nbsp;      it receives 6 args and returns 9 args\, potentially overflowing the
&nbsp;      stack by 3 elements\. In an extreme case\,

&nbsp;        pairmap \{ $a\.\.$b \} 1\, 1\_000\_000;

&nbsp;      would write approx 1 million addresses beyond the end of the stack\.

I need to decide what to do next\. The only bug which seems particularly
significant is the List&#8203;::Util one\. At some point I would like to merge my
branch into blead \(containing the HWM debugging code\, the core fixes\, and
the Time&#8203;::Piece and List&#8203;::Util CPAN module fixes\)\.

I probably need to contact the Time&#8203;::Piece and List&#8203;::Util privately and
report the bugs and fixes\.

The other fixes I should be able to apply directly to blead since they
are relatively minor issues\.

The HWM debugging code can't be applied until all the other fixes are in
core \(including List&#8203;::Util\) \- otherwise it will fails tests\.

\-\- 
You never really learn to swear until you learn to drive\.

**Comment by p5pRT** [comment]
### From @hvds

On Thu\, 15 Jun 2017 07&#8203;:47&#8203;:06 \-0700\, davem wrote&#8203;:
> This seems to work very well\, and has found the following bugs \- all
> of which I have fixed in my branch \- with no false positives

\\o/

> I probably need to contact the Time&#8203;::Piece and List&#8203;::Util \[maintainers\]
> privately and report the bugs and fixes\.

I think it makes sense to try that\, see how they respond\, and then decide where to go from there\.

Hugo

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Jun 15\, 2017 at 03&#8203;:46&#8203;:47PM \+0100\, Dave Mitchell wrote&#8203;:
> Since then I've been doing some thinking and decided that this sort of
> thing ought to be automated\. So I have a branch \(not pushed yet\) which on
> debugging builds&#8203;:
> 
> \* makes the runops loop set a high\-water\-mark \(HWM\) variable equal to
>   PL\_stack\_sp just before calling each pp function;
> 
> \* modifies EXTEND\(\) etc to update this HWM;
> 
> \* on return from the pp function checks whether PL\_stack\_sp is > HWM\,
>   and if so panics\.
> 
> This seems to work very well\, and has found the following bugs \- all of
> which I have fixed in my branch \- with no false positives&#8203;:
> 
> \* Not extending the stack by 1 \(typically to return a scalar context result\)&#8203;:
> 
>     \* pp\_match/pp\_subst \(in variants where their args aren't supplied on
>       the stack\)
>     \* reverse\(\) \- the subject of this ticket
>     \* empty list slice
>     \* argless reset\(\)
>     \* pp\_leavewrite
>     \* recv&#8203;: in fact it wasn't popping its four args before returning undef
>       on failure \-so it actually returned 5 args on failure\, which in
>       scalar context used the last one\.
>     \* Time&#8203;::Piece&#8203;::tzoffset\(\) called a private XS function which
>       extended the stack by 9\, then returned 10 elements
> 
> \* Not extending the stack by N&#8203;:
> 
>     \* XS&#8203;::APItest&#8203;::test\_hv\_free\_ent\(\)&#8203;: not important as this is only an
>         internal test XS function
> 
>     \* List&#8203;::Util&#8203;::pairmap\(\)&#8203;: didn't grow the stack if it returned more
>       values than it was passed\. pairmap\(\) is like map\(\) except that in
>       each iteration it consumes 2 args\, setting $a and $b to them\. In
>       something like
>         @&#8203;result = pairmap \{ \(1\,2\,3\) \} 10\,11\, 20\,21\, 30\,31;
>       it receives 6 args and returns 9 args\, potentially overflowing the
>       stack by 3 elements\. In an extreme case\,
> 
>         pairmap \{ $a\.\.$b \} 1\, 1\_000\_000;
> 
>       would write approx 1 million addresses beyond the end of the stack\.
> 
> I need to decide what to do next\. The only bug which seems particularly
> significant is the List&#8203;::Util one\. At some point I would like to merge my
> branch into blead \(containing the HWM debugging code\, the core fixes\, and
> the Time&#8203;::Piece and List&#8203;::Util CPAN module fixes\)\.
> 
> I probably need to contact the Time&#8203;::Piece and List&#8203;::Util privately and
> report the bugs and fixes\.
> 
> The other fixes I should be able to apply directly to blead since they
> are relatively minor issues\.
> 
> The HWM debugging code can't be applied until all the other fixes are in
> core \(including List&#8203;::Util\) \- otherwise it will fails tests\.

The cpan modules have now both been fixed\, and everything has now been
pushed to blead and publicly announced\. So I'll close this ticket\.

core fixes\, including the pp\_reverse\(\) issue&#8203;:

&nbsp;    9399c60 pp\_match/subst&#8203;: extend stack
&nbsp;    d5d91c1 scalar reverse\(\)&#8203;: extend stack if no arg
&nbsp;    7da51ea extend stack on scalar empty list slice
&nbsp;    2372d07 argless reset\(\)&#8203;: extend stack
&nbsp;    b7effc9 pp\_leavewrite&#8203;: extend stack for return value
&nbsp;    78e69e6 recv&#8203;: reset stack when returning undef
&nbsp;    04849b3 XS&#8203;::APItest&#8203;::test\_hv\_free\_ent&#8203;: extend stack
&nbsp;    54ad4e1 porting/bench\.t&#8203;: skip under ASAN
&nbsp;    0599cd6 add DEBUGGING\_RE\_ONLY define

cpan module fixes&#8203;:

&nbsp;    060e131 upgrade Scalar\-List\-Utils from 1\.47 to 1\.48
&nbsp;    23c687d upgrade Time\-Piece from 1\.31 to 1\.3201

and the new debugging mechanism&#8203;:

&nbsp;    87058c3 add PL\_curstackinfo\->si\_stack\_hwm


\-\- 
Any \[programming\] language that doesn't occasionally surprise the
novice will pay for it by continually surprising the expert\.
&nbsp;   \-\- Larry Wall

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
