### ISSUE TITLE
stack-overflow in Perl_Gv_AMupdate

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16026]
Migrated from [rt.perl.org#131601](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131601) (status was 'rejected')

Searchable as RT131601$

**Comment by p5pRT** [comment]
### From @Mipu94

I found a sample that's causing recursion and triggered a bug out of
memory\. Is this bug?
Please check file attached below to check\.

ASAN report perl version 5

==7664==ERROR&#8203;: AddressSanitizer&#8203;: stack\-overflow on address 0x7ffc471ddff8
\(pc 0x7f4f3d8e9372 bp 0x000000000020 sp 0x7ffc471de000 T0\)
&nbsp;    \#0 0x7f4f3d8e9371  \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.4\+0x103371\)
&nbsp;    \#1 0x7f4f3d8e8ed7  \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.4\+0x102ed7\)
&nbsp;    \#2 0x7f4f3d80e041  \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.4\+0x28041\)
&nbsp;    \#3 0x7f4f3d8c48ea in malloc
\(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.4\+0xde8ea\)
&nbsp;    \#4 0x499354 in Perl\_safesysmalloc
\(/home/athos/fuzzing/fuzzperl/crash/perl\-asan\-5\.27\+0x499354\)
&nbsp;    \#5 0x4b3873 in Perl\_av\_extend\_guts
\(/home/athos/fuzzing/fuzzperl/crash/perl\-asan\-5\.27\+0x4b3873\)
&nbsp;    \.\.\.\.\.
&nbsp;    \#248 0x4b4fc2 in Perl\_runops\_standard
\(/home/athos/fuzzing/fuzzperl/crash/perl\-asan\-5\.27\+0x4b4fc2\)
&nbsp;    \#249 0x44b44c in Perl\_amagic\_call
\(/home/athos/fuzzing/fuzzperl/crash/perl\-asan\-5\.27\+0x44b44c\)
&nbsp;    \#250 0x4cc4a7 in Perl\_sv\_2pv\_flags
\(/home/athos/fuzzing/fuzzperl/crash/perl\-asan\-5\.27\+0x4cc4a7\)

SUMMARY&#8203;: AddressSanitizer&#8203;: stack\-overflow
\(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.4\+0x103371\)
\-\- 
Ta Dinh Sung\,

**Comment by p5pRT** [comment]
### From @Mipu94

[sample](https://rt-archive.perl.org/perl5/Ticket/Attachment/1467574/796180/sample)

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon\, 19 Jun 2017 02&#8203;:58&#8203;:05 \-0700\, tadinhsung@&#8203;gmail\.com wrote&#8203;:
> I found a sample that's causing recursion and triggered a bug out of
> memory\. Is this bug?
> Please check file attached below to check\.
> 
> ASAN report perl version 5
> 
> ==7664==ERROR&#8203;: AddressSanitizer&#8203;: stack\-overflow on address 0x7ffc471ddff8
> \(pc 0x7f4f3d8e9372 bp 0x000000000020 sp 0x7ffc471de000 T0\)
>     \#0 0x7f4f3d8e9371  \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.4\+0x103371\)
>     \#1 0x7f4f3d8e8ed7  \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.4\+0x102ed7\)
>     \#2 0x7f4f3d80e041  \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.4\+0x28041\)
>     \#3 0x7f4f3d8c48ea in malloc
> \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.4\+0xde8ea\)
>     \#4 0x499354 in Perl\_safesysmalloc
> \(/home/athos/fuzzing/fuzzperl/crash/perl\-asan\-5\.27\+0x499354\)
>     \#5 0x4b3873 in Perl\_av\_extend\_guts
> \(/home/athos/fuzzing/fuzzperl/crash/perl\-asan\-5\.27\+0x4b3873\)
>     \.\.\.\.\.
>     \#248 0x4b4fc2 in Perl\_runops\_standard
> \(/home/athos/fuzzing/fuzzperl/crash/perl\-asan\-5\.27\+0x4b4fc2\)
>     \#249 0x44b44c in Perl\_amagic\_call
> \(/home/athos/fuzzing/fuzzperl/crash/perl\-asan\-5\.27\+0x44b44c\)
>     \#250 0x4cc4a7 in Perl\_sv\_2pv\_flags
> \(/home/athos/fuzzing/fuzzperl/crash/perl\-asan\-5\.27\+0x4cc4a7\)
> 
> SUMMARY&#8203;: AddressSanitizer&#8203;: stack\-overflow
> \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.4\+0x103371\)

This is not a bug in perl\.

Your code uses string overloading then uses the object as a string in the implementation of that overloading\, causing recursion until you run out of stack\.

Moving to the public queue and closing\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'rejected'

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Jun 19\, 2017 at 02&#8203;:58&#8203;:06AM \-0700\, sung wrote&#8203;:
> \# New Ticket Created by  sung 
> \# Please include the string&#8203;:  \[perl \#131601\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131601 >
> 
> 
> I found a sample that's causing recursion and triggered a bug out of
> memory\. Is this bug?

Similarly to your ticket \#131596\,
this is fairly standard example of certain types of recursive perl code
triggering recursive C code calls and an eventual SEGV\.

I don't see any particular security issues with it\.

I'll move the ticket to the public queue and attach it to the relevant
meta\-ticket&#8203;:

&nbsp;    \#111358&#8203;: \[META\] C stack recursion




\-\- 
Little fly\, thy summer's play my thoughtless hand
has terminated with extreme prejudice\.
&nbsp;        \(with apologies to William Blake\)
