### ISSUE TITLE
op.c:13088: void S_maybe_multideref(OP *, OP *, UV, U8): Assertion `!(o->op_flags & ~(3|128))' failed.

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16029]
Migrated from [rt.perl.org#131627](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131627) (status was 'open')

Searchable as RT131627$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.27\.1\-37\-g4c95ee9f29 built with afl and run
under libdislocator\, I found the following program

m\!$0\{qw/0/\->@&#8203;\*\}\!

to cause an assertion failure\, even when run under \-c for a syntax
check\. GDB info about the crash location is&#8203;:

gdb$ bt
\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=0x6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:51
\#1  0x00007f581c96c3fa in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007f581c963e37 in \_\_assert\_fail\_base \(fmt=\<optimized out>\,
assertion=assertion@&#8203;entry=0x564edf332d0e "\!\(o\->op\_flags & ~\(3|128\)\)"\,
file=file@&#8203;entry=0x564edf32cf2e "op\.c"\, line=line@&#8203;entry=0x3320\,
function=function@&#8203;entry=0x564edf3348a0 \<\_\_PRETTY\_FUNCTION\_\_\.19849>
"S\_maybe\_multideref"\) at assert\.c&#8203;:92
\#3  0x00007f581c963ee2 in \_\_GI\_\_\_assert\_fail \(assertion=0x564edf332d0e
"\!\(o\->op\_flags & ~\(3|128\)\)"\, file=0x564edf32cf2e "op\.c"\, line=0x3320\,
function=0x564edf3348a0 \<\_\_PRETTY\_FUNCTION\_\_\.19849>
"S\_maybe\_multideref"\) at assert\.c&#8203;:101
\#4  0x0000564edf00b36f in S\_maybe\_multideref \(start=0x564edf7e07b8\,
orig\_o=0x564edf7e0738\, orig\_action=0xd\, hints=0x0\) at op\.c&#8203;:13088
\#5  0x0000564edf00c97c in Perl\_rpeep \(o=0x564edf7e07b8\) at op\.c&#8203;:13798
\#6  0x0000564edf00fedf in Perl\_peep \(o=0x564edf7e0b50\) at op\.c&#8203;:14819
\#7  0x0000564edefda649 in S\_process\_optree \(cv=0x0\,
optree=0x564edf7e0b88\, start=0x564edf7e0b50\) at op\.c&#8203;:2475
\#8  0x0000564edefe173f in Perl\_newPROG \(o=0x564edf7e0b88\) at op\.c&#8203;:4303
\#9  0x0000564edf09760c in Perl\_yyparse \(gramtype=0x102\) at perly\.y&#8203;:124
\#10 0x0000564edf018d4c in S\_parse\_body \(env=0x0\, xsinit=0x564edefd1fe8
\<xs\_init>\) at perl\.c&#8203;:2401
\#11 0x0000564edf0170b1 in perl\_parse \(my\_perl=0x564edf7b6010\,
xsinit=0x564edefd1fe8 \<xs\_init>\, argc=0x2\, argv=0x7ffff1567488\,
env=0x0\) at perl\.c&#8203;:1719
\#12 0x0000564edefd1f26 in main \(argc=0x2\, argv=0x7ffff1567488\,
env=0x7ffff15674a0\) at perlmain\.c&#8203;:121
gdb$ up 4
\#4  0x0000564edf00b36f in S\_maybe\_multideref \(start=0x564edf7e07b8\,
orig\_o=0x564edf7e0738\, orig\_action=0xd\, hints=0x0\) at op\.c&#8203;:13088
13088                    ASSUME\(\!\(o\->op\_flags & ~\(OPf\_WANT|OPf\_SPECIAL\)\)\);
gdb$ p o\->op\_flags
$1 = 0xa

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.27.1:

Configured by root at Sun May 28 01:44:41 MSK 2017.

Summary of my perl5 (revision 5 version 26 subversion 0) configuration:
  Derived from: 4c95ee9f298c2edfc1382d540ff89288790e78b6
  Platform:
    osname=linux
    osvers=4.9.0-3-amd64
    archname=x86_64-linux
    uname='linux dorothy 4.9.0-3-amd64 #1 smp debian 4.9.25-1
(2017-05-02) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING -Dcc=afl-clang-fast
-Doptimize=-O0 -g -ggdb3 -fno-omit-frame-pointer'
    hint=previous
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='afl-clang-fast'
    ccflags ='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O0 -g -ggdb3 -fno-omit-frame-pointer'
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Clang 3.9.1 (tags/RELEASE_391/rc2)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='afl-clang-fast'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/lib
/usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu
/lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
/usr/local/lib /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/lib
/usr/include/x86_64-linux-gnu /usr/lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.24.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.24'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O0 -g -ggdb3 -fno-omit-frame-pointer
-L/usr/local/lib -fstack-protector-strong'

Locally applied patches:
    uncommitted-changes


@INC for perl 5.27.1:
    lib
    /usr/local/lib/perl5/site_perl/5.26.0/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.26.0
    /usr/local/lib/perl5/5.26.0/x86_64-linux
    /usr/local/lib/perl5/5.26.0


Environment for perl 5.27.1:
    HOME=/home/afl
    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    LC_CTYPE=en_US.UTF-8
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.24.1-dbg/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    PERLBREW_BASHRC_VERSION=0.78
    PERLBREW_HOME=/home/afl/.perlbrew
    PERLBREW_MANPATH=/home/afl/perlbrew/perls/perl-5.24.1-dbg/man
    PERLBREW_PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.24.1-dbg/bin
    PERLBREW_PERL=perl-5.24.1-dbg
    PERLBREW_ROOT=/home/afl/perlbrew
    PERLBREW_VERSION=0.78
    PERL_BADLANG (unset)
    SHELL=/usr/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @ilmari

Sergey Aleynikov \(via RT\) \<perlbug\-followup@&#8203;perl\.org> writes&#8203;:

> While fuzzing perl v5\.27\.1\-37\-g4c95ee9f29 built with afl and run
> under libdislocator\, I found the following program
>
> m\!$0\{qw/0/\->@&#8203;\*\}\!
\[…\]
> \#4  0x0000564edf00b36f in S\_maybe\_multideref \(start=0x564edf7e07b8\,
> orig\_o=0x564edf7e0738\, orig\_action=0xd\, hints=0x0\) at op\.c&#8203;:13088
> 13088                    ASSUME\(\!\(o\->op\_flags & ~\(OPf\_WANT|OPf\_SPECIAL\)\)\);
> gdb$ p o\->op\_flags
> $1 = 0xa

The offending flag is OPf\_PARENS\, which is to indicate that the OP\_GV
came from a qw\(\) rather than a plain scalar value\.  Including that flag
in the ASSUME\(\) and in the below test for OPf\_WANT\_SCALAR not only fixes
this assert\, but allows multideref to do its thing with this \(which I
added as a test\)&#8203;:

&nbsp;    @&#8203;x = \(10\.\.12\);
&nbsp;    $i = 1;

&nbsp;    is $x\[qw\(i\)\->$\*\]\, 11\, 'RT \#131627&#8203;: $a\[qw\(i\)\->$\*\]';

Pushed as commit e13dc8886f\.

The fact that the above works under strict 'refs' is a separate bug\,
which I intend to address shortly unless someone feels like beating me
to it\.

\-\- 
"The surreality of the universe tends towards a maximum" \-\- Skud's Law
"Never formulate a law or axiom that you're not prepared to live with
 the consequences of\."                              \-\- Skud's Meta\-Law

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'
