### ISSUE TITLE
Malformed utf8 message; earlier bug fixed, was use heap after free

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16020]
Migrated from [rt.perl.org#131577](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131577) (status was 'open')

Searchable as RT131577$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered with Perl v5\.27\.0\-97\-gd555ed0\, compiled with afl\-clang\-fast on
Debian 8 x64\.

Unescaped left brace in regex is deprecated here \(and will be fatal in Perl
5\.30\)\, passed through in regex; marked by \<\-\- HERE in m/\[k@&#8203;▒l\]s\{ \<\-\- HERE \*
/ at test581 line 1\, \<DATA> line 5\.
Unescaped left brace in regex is deprecated here \(and will be fatal in Perl
5\.30\)\, passed through in regex; marked by \<\-\- HERE in m/\[k@&#8203;▒l\]s\{ \<\-\- HERE \*
/ at test581 line 1\, \<DATA> line 5\.
Unescaped left brace in regex is deprecated here \(and will be fatal in Perl
5\.30\)\, passed through in regex; marked by \<\-\- HERE in m/\[k@&#8203;▒l\]s\{ \<\-\- HERE \*
/ at test581 line 1\, \<DATA> line 5\.
Malformed UTF\-8 character \(unexpected end of string\) in substitution \(s///\)
at test581 line 1\, \<DATA> line 5\.
=================================================================
==22553==ERROR&#8203;: AddressSanitizer&#8203;: heap\-use\-after\-free on address
0x60300000ea47 at pc 0xf21e80 bp 0x7fff9a7bca70 sp 0x7fff9a7bca68
READ of size 1 at 0x60300000ea47 thread T0
&nbsp;    \#0 0xf21e7f in S\_reghop4 /root/perl/regexec\.c&#8203;:9494
&nbsp;    \#1 0xfc84f0 in Perl\_re\_intuit\_start /root/perl/regexec\.c&#8203;:1054
&nbsp;    \#2 0xfcae37 in Perl\_regexec\_flags /root/perl/regexec\.c&#8203;:3001
&nbsp;    \#3 0xac86d2 in Perl\_pp\_subst /root/perl/pp\_hot\.c&#8203;:3229
&nbsp;    \#4 0x926e76 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2451
&nbsp;    \#5 0x59f02a in S\_run\_body /root/perl/perl\.c&#8203;:2543
&nbsp;    \#6 0x59f02a in perl\_run /root/perl/perl\.c&#8203;:2471
&nbsp;    \#7 0x43506d in main /root/perl/perlmain\.c&#8203;:123
&nbsp;    \#8 0x7f3350585b44 in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x21b44\)
&nbsp;    \#9 0x436015 \(/root/perl/perl\+0x436015\)

0x60300000ea47 is located 7 bytes inside of 24\-byte region
\[0x60300000ea40\,0x60300000ea58\)
freed by thread T0 here&#8203;:
&nbsp;    \#0 0x7f33516d79f6 in \_\_interceptor\_realloc
\(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.1\+0x549f6\)
&nbsp;    \#1 0x96d481 in Perl\_safesysrealloc /root/perl/util\.c&#8203;:274

previously allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x7f33516d79f6 in \_\_interceptor\_realloc
\(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.1\+0x549f6\)
&nbsp;    \#1 0x96d481 in Perl\_safesysrealloc /root/perl/util\.c&#8203;:274

SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-use\-after\-free /root/perl/regexec\.c&#8203;:9494
S\_reghop4

**Comment by p5pRT** [comment]
### From @geeknik

[test581.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1466603/795952/test581.gz)

**Comment by p5pRT** [comment]
### From @tonycoz

On Wed\, 14 Jun 2017 17&#8203;:50&#8203;:42 \-0700\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> Triggered with Perl v5\.27\.0\-97\-gd555ed0\, compiled with afl\-clang\-fast on
> Debian 8 x64\.
> 
> Unescaped left brace in regex is deprecated here \(and will be fatal in Perl
> 5\.30\)\, passed through in regex; marked by \<\-\- HERE in m/\[k@&#8203;▒l\]s\{ \<\-\- HERE \*
> / at test581 line 1\, \<DATA> line 5\.
> Unescaped left brace in regex is deprecated here \(and will be fatal in Perl
> 5\.30\)\, passed through in regex; marked by \<\-\- HERE in m/\[k@&#8203;▒l\]s\{ \<\-\- HERE \*
> / at test581 line 1\, \<DATA> line 5\.
> Unescaped left brace in regex is deprecated here \(and will be fatal in Perl
> 5\.30\)\, passed through in regex; marked by \<\-\- HERE in m/\[k@&#8203;▒l\]s\{ \<\-\- HERE \*
> / at test581 line 1\, \<DATA> line 5\.
> Malformed UTF\-8 character \(unexpected end of string\) in substitution \(s///\)
> at test581 line 1\, \<DATA> line 5\.
> =================================================================
> ==22553==ERROR&#8203;: AddressSanitizer&#8203;: heap\-use\-after\-free on address
> 0x60300000ea47 at pc 0xf21e80 bp 0x7fff9a7bca70 sp 0x7fff9a7bca68
> READ of size 1 at 0x60300000ea47 thread T0
>     \#0 0xf21e7f in S\_reghop4 /root/perl/regexec\.c&#8203;:9494
>     \#1 0xfc84f0 in Perl\_re\_intuit\_start /root/perl/regexec\.c&#8203;:1054
>     \#2 0xfcae37 in Perl\_regexec\_flags /root/perl/regexec\.c&#8203;:3001
>     \#3 0xac86d2 in Perl\_pp\_subst /root/perl/pp\_hot\.c&#8203;:3229
>     \#4 0x926e76 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2451
>     \#5 0x59f02a in S\_run\_body /root/perl/perl\.c&#8203;:2543
>     \#6 0x59f02a in perl\_run /root/perl/perl\.c&#8203;:2471
>     \#7 0x43506d in main /root/perl/perlmain\.c&#8203;:123
>     \#8 0x7f3350585b44 in \_\_libc\_start\_main
> \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x21b44\)
>     \#9 0x436015 \(/root/perl/perl\+0x436015\)
> 
> 0x60300000ea47 is located 7 bytes inside of 24\-byte region
> \[0x60300000ea40\,0x60300000ea58\)
> freed by thread T0 here&#8203;:
>     \#0 0x7f33516d79f6 in \_\_interceptor\_realloc
> \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.1\+0x549f6\)
>     \#1 0x96d481 in Perl\_safesysrealloc /root/perl/util\.c&#8203;:274
> 
> previously allocated by thread T0 here&#8203;:
>     \#0 0x7f33516d79f6 in \_\_interceptor\_realloc
> \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.1\+0x549f6\)
>     \#1 0x96d481 in Perl\_safesysrealloc /root/perl/util\.c&#8203;:274
> 
> SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-use\-after\-free /root/perl/regexec\.c&#8203;:9494
> S\_reghop4

Attached is a partial minimization\.

This patch&#8203;:

<details><summary>Inline Patch</summary>

```diff
diff --git a/regexec.c b/regexec.c
index 05675ad..29ec5c7 100644
--- a/regexec.c
+++ b/regexec.c
@@ -9524,6 +9524,9 @@ S_reghopmaybe3(U8* s, SSize_t off, const U8* const lim)
        }
        if (off >= 0)
            return NULL;
+        if (s > lim) {
+            Perl_croak_nocontext("Malformed UTF-8 character (fatal)");
+        }
     }
     else {
         while (off++ && s > lim) {


```
</details>
prevents the crash[1], but I suspect the problem is the code is doing a substitution on $_ while a substitution on $_ is in progress.

Tony

\[1\] and is a little broken\, since s might be beyond the end of the allocated string

**Comment by p5pRT** [comment]
### From @tonycoz

[131577b.pl](https://rt-archive.perl.org/perl5/Ticket/Attachment/1468371/796473/131577b.pl)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by khwilliamson** [comment]
On blead, @tonycoz reduction doesn't generate any problem.  The original generates

Malformed UTF-8 character (unexpected end of string) in substitution (s///) at /var/tmp/test581 line 1, <DATA> line 5.
perl: util.c:830: char *Perl_fbm_instr(PerlInterpreter *, unsigned char *, unsigned char *, SV *, U32): Assertion `bigend >= big' failed.
