### ISSUE TITLE
Memory leak in Perl_yylex

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16034]
Migrated from [rt.perl.org#131636](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131636) (status was 'new')

Searchable as RT131636$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.27\.1\-37\-g4c95ee9f29 built with afl and run
under libdislocator\, I found the following program

eval q\!m|$0\[b\{INIT\{\]\]\]|\}0r\! \#while \(1\)

to leak memory\. To observe the leak without ASAN\, remove the '\#'
symbol\. ASAN info about the leaked allocation is&#8203;:

=================================================================
==4646==ERROR&#8203;: LeakSanitizer&#8203;: detected memory leaks

Direct leak of 48 byte\(s\) in 1 object\(s\) allocated from&#8203;:
&nbsp;    \#0 0x4ea970 in calloc \(/home/afl/afl\-asan/perl\+0x4ea970\)
&nbsp;    \#1 0x522aa3 in Perl\_Slab\_Alloc /home/afl/afl\-asan/op\.c&#8203;:277&#8203;:11
&nbsp;    \#2 0x540426 in Perl\_newSVOP /home/afl/afl\-asan/op\.c&#8203;:6100&#8203;:5
&nbsp;    \#3 0x677ec0 in Perl\_yylex /home/afl/afl\-asan/toke\.c&#8203;:7242&#8203;:35
&nbsp;    \#4 0x700592 in Perl\_yyparse /home/afl/afl\-asan/perly\.c&#8203;:340&#8203;:34
&nbsp;    \#5 0xb227bf in S\_doeval\_compile /home/afl/afl\-asan/pp\_ctl\.c&#8203;:3456&#8203;:77
&nbsp;    \#6 0xb1fa12 in Perl\_pp\_entereval /home/afl/afl\-asan/pp\_ctl\.c&#8203;:4415&#8203;:9
&nbsp;    \#7 0x85a804 in Perl\_runops\_debug /home/afl/afl\-asan/dump\.c&#8203;:2451&#8203;:23
&nbsp;    \#8 0x5f72f5 in S\_run\_body /home/afl/afl\-asan/perl\.c&#8203;:2548&#8203;:2
&nbsp;    \#9 0x5f72f5 in perl\_run /home/afl/afl\-asan/perl\.c&#8203;:2471
&nbsp;    \#10 0x5225c2 in main /home/afl/afl\-asan/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#11 0x7f7f4f1402b0 in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x202b0\)

SUMMARY&#8203;: AddressSanitizer&#8203;: 48 byte\(s\) leaked in 1 allocation\(s\)\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.27.1:

Configured by root at Sun May 28 01:44:41 MSK 2017.

Summary of my perl5 (revision 5 version 26 subversion 0) configuration:
  Derived from: 4c95ee9f298c2edfc1382d540ff89288790e78b6
  Platform:
    osname=linux
    osvers=4.9.0-3-amd64
    archname=x86_64-linux
    uname='linux dorothy 4.9.0-3-amd64 #1 smp debian 4.9.25-1
(2017-05-02) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING -Dcc=afl-clang-fast
-Doptimize=-O0 -g -ggdb3 -fno-omit-frame-pointer'
    hint=previous
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='afl-clang-fast'
    ccflags ='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O0 -g -ggdb3 -fno-omit-frame-pointer'
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Clang 3.9.1 (tags/RELEASE_391/rc2)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='afl-clang-fast'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/lib
/usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu
/lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
/usr/local/lib /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/lib
/usr/include/x86_64-linux-gnu /usr/lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.24.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.24'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O0 -g -ggdb3 -fno-omit-frame-pointer
-L/usr/local/lib -fstack-protector-strong'

Locally applied patches:
    uncommitted-changes


@INC for perl 5.27.1:
    lib
    /usr/local/lib/perl5/site_perl/5.26.0/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.26.0
    /usr/local/lib/perl5/5.26.0/x86_64-linux
    /usr/local/lib/perl5/5.26.0


Environment for perl 5.27.1:
    HOME=/home/afl
    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    LC_CTYPE=en_US.UTF-8
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.24.1-dbg/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    PERLBREW_BASHRC_VERSION=0.78
    PERLBREW_HOME=/home/afl/.perlbrew
    PERLBREW_MANPATH=/home/afl/perlbrew/perls/perl-5.24.1-dbg/man
    PERLBREW_PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.24.1-dbg/bin
    PERLBREW_PERL=perl-5.24.1-dbg
    PERLBREW_ROOT=/home/afl/perlbrew
    PERLBREW_VERSION=0.78
    PERL_BADLANG (unset)
    SHELL=/usr/bin/zsh

```
</details>
