### ISSUE TITLE
Coredump in Perl_yyparse

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16037]
Migrated from [rt.perl.org#131644](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131644) (status was 'new')

Searchable as RT131644$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.27\.1\-37\-g4c95ee9f29 built with afl and run
under libdislocator\, I found the following program

m|$0\[s0\{INIT\{\]\]\]|\}m|$0\[sub\{T\{\]\]\]|

to crash\, even when run under \-c for a syntax
check\. This is a regression between 5\.16 and 5\.18\, bisect points to&#8203;:

commit 9ffcdca1f504cb09088413c074b35af4b7f247e3
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Mon Nov 12 23&#8203;:04&#8203;:16 2012 \-0800

&nbsp;    Don’t leak subs containing syntax errors

&nbsp;    I fixed this for BEGIN blocks earlier\, but missed the fact that
&nbsp;    all subs are affected\.

&nbsp;    When called without an o argument \(from newANONATTRSUB\)\, newATTRSUB
&nbsp;    is expected to return a CV with an unowned reference count of which
&nbsp;    the caller will take ownership\.  We cannot have newATTRSUB returning
&nbsp;    a freed CV\, so we have it return null instead\.  But that means
&nbsp;    ck\_anoncode and pm\_runtime have to account for that\.

GDB info about the crash location is&#8203;:

\(gdb\) bt
\#0  0x00005585869a21b2 in Perl\_yyparse \(gramtype=258\) at perly\.c&#8203;:497
\#1  0x000055858691ed4c in S\_parse\_body \(env=0x0\, xsinit=0x5585868d7fe8
\<xs\_init>\) at perl\.c&#8203;:2401
\#2  0x000055858691d0b1 in perl\_parse \(my\_perl=0x55858794e010\,
xsinit=0x5585868d7fe8 \<xs\_init>\, argc=2\, argv=0x7ffc8ef357f8\, env=0x0\)
at perl\.c&#8203;:1719
\#3  0x00005585868d7f26 in main \(argc=2\, argv=0x7ffc8ef357f8\,
env=0x7ffc8ef35810\) at perlmain\.c&#8203;:121
\(gdb\) p PL\_compcv
$1 = \(CV \*\) 0x0

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.27.1:

Configured by root at Sun May 28 01:44:41 MSK 2017.

Summary of my perl5 (revision 5 version 26 subversion 0) configuration:
  Derived from: 4c95ee9f298c2edfc1382d540ff89288790e78b6
  Platform:
    osname=linux
    osvers=4.9.0-3-amd64
    archname=x86_64-linux
    uname='linux dorothy 4.9.0-3-amd64 #1 smp debian 4.9.25-1
(2017-05-02) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING -Dcc=afl-clang-fast
-Doptimize=-O0 -g -ggdb3 -fno-omit-frame-pointer'
    hint=previous
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='afl-clang-fast'
    ccflags ='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O0 -g -ggdb3 -fno-omit-frame-pointer'
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Clang 3.9.1 (tags/RELEASE_391/rc2)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='afl-clang-fast'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/lib
/usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu
/lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
/usr/local/lib /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/lib
/usr/include/x86_64-linux-gnu /usr/lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.24.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.24'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O0 -g -ggdb3 -fno-omit-frame-pointer
-L/usr/local/lib -fstack-protector-strong'

Locally applied patches:
    uncommitted-changes


@INC for perl 5.27.1:
    lib
    /usr/local/lib/perl5/site_perl/5.26.0/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.26.0
    /usr/local/lib/perl5/5.26.0/x86_64-linux
    /usr/local/lib/perl5/5.26.0


Environment for perl 5.27.1:
    HOME=/home/afl
    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    LC_CTYPE=en_US.UTF-8
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.24.1-dbg/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    PERLBREW_BASHRC_VERSION=0.78
    PERLBREW_HOME=/home/afl/.perlbrew
    PERLBREW_MANPATH=/home/afl/perlbrew/perls/perl-5.24.1-dbg/man
    PERLBREW_PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.24.1-dbg/bin
    PERLBREW_PERL=perl-5.24.1-dbg
    PERLBREW_ROOT=/home/afl/perlbrew
    PERLBREW_VERSION=0.78
    PERL_BADLANG (unset)
    SHELL=/usr/bin/zsh

```
</details>

**Comment by purinchu** [comment]
I'm not able to reproduce this on Perl 5.40.0, it may have already been fixed.

**Comment by jkeenan** [comment]
> I'm not able to reproduce this on Perl 5.40.0, it may have already been fixed.

@dur-randir, are you able to reproduce this crash in perl-5.40 or perl-5.42?  Thanks.

**Comment by dur-randir** [comment]
Looks like this was fixed somewhere between 5.26 and 5.28.

**Comment by jkeenan** [comment]
> Looks like this was fixed somewhere between 5.26 and 5.28.

Thanks; closing.
