### ISSUE TITLE
op.c:8067: SV *Perl_cv_const_sv_or_av(const CV *const): Assertion `SvTYPE(cv) == SVt_PVCV || SvTYPE(cv) == SVt_PVFM' failed.

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16040]
Migrated from [rt.perl.org#131647](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131647) (status was 'open')

Searchable as RT131647$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.27\.1\-37\-g4c95ee9f29 built with afl and run
under libdislocator\, I found the following program

@&#8203;I0&#8203;::""my I0"";sub f00\}f00

to cause an assertion failure\. This is a regression between 5\.20 and
5\.22\, bisect points to&#8203;:

commit 0f94cb1fe27e58a59d3391214dab34037ab184db
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Thu Nov 27 22&#8203;:30&#8203;:54 2014 \-0800

&nbsp;    \[perl \#123223\] Make PADNAME a separate type

&nbsp;    distinct from SV\.  This should fix the CPAN modules that were failing
&nbsp;    when the PadnameLVALUE flag was added\, because it shared the same
&nbsp;    bit as SVs\_OBJECT and pad names were going through code paths not
&nbsp;    designed to handle pad names\.

&nbsp;    Unfortunately\, it will probably break other CPAN modules\, but I think
&nbsp;    this change is for the better\, as it makes both pad names and SVs sim\-
&nbsp;    pler and makes pad names take less memory\.

GDB info about the crash location is&#8203;:

\(gdb\) bt
\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:51
\#1  0x00007ffff6cf63fa in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007ffff6cede37 in \_\_assert\_fail\_base \(fmt=\<optimized out>\,
&nbsp;    assertion=assertion@&#8203;entry=0x5555558e3158 "SvTYPE\(cv\) == SVt\_PVCV
|| SvTYPE\(cv\) == SVt\_PVFM"\, file=file@&#8203;entry=0x5555558def2e "op\.c"\,
&nbsp;    line=line@&#8203;entry=8067\, function=function@&#8203;entry=0x5555558e61f0
\<\_\_PRETTY\_FUNCTION\_\_\.17680> "Perl\_cv\_const\_sv\_or\_av"\) at assert\.c&#8203;:92
\#3  0x00007ffff6cedee2 in \_\_GI\_\_\_assert\_fail \(assertion=0x5555558e3158
"SvTYPE\(cv\) == SVt\_PVCV || SvTYPE\(cv\) == SVt\_PVFM"\,
file=0x5555558def2e "op\.c"\,
&nbsp;    line=8067\, function=0x5555558e61f0 \<\_\_PRETTY\_FUNCTION\_\_\.17680>
"Perl\_cv\_const\_sv\_or\_av"\) at assert\.c&#8203;:101
\#4  0x00005555555a19d7 in Perl\_cv\_const\_sv\_or\_av \(cv=0x555555c0b530\)
at op\.c&#8203;:8067
\#5  0x0000555555627e6b in Perl\_yylex \(\) at toke\.c&#8203;:7406
\#6  0x0000555555649164 in Perl\_yyparse \(gramtype=258\) at perly\.c&#8203;:340
\#7  0x00005555555cad4c in S\_parse\_body \(env=0x0\, xsinit=0x555555583fe8
\<xs\_init>\) at perl\.c&#8203;:2401
\#8  0x00005555555c90b1 in perl\_parse \(my\_perl=0x555555bed010\,
xsinit=0x555555583fe8 \<xs\_init>\, argc=2\, argv=0x7fffffffe1c8\, env=0x0\)
at perl\.c&#8203;:1719
\#9  0x0000555555583f26 in main \(argc=2\, argv=0x7fffffffe1c8\,
env=0x7fffffffe1e0\) at perlmain\.c&#8203;:121
\(gdb\) f 5
\#5  0x0000555555627e6b in Perl\_yylex \(\) at toke\.c&#8203;:7406
7406    if \(\(sv = cv\_const\_sv\_or\_av\(cv\)\)\) \{
\(gdb\) p sv\_dump\(cv\)
SV = PVHV\(0x555555bf6010\) at 0x555555c0b530
&nbsp;  REFCNT = 3
&nbsp;  FLAGS = \(OOK\,SHAREKEYS\)
&nbsp;  AUX\_FLAGS = 0
&nbsp;  ARRAY = 0x555555c17e00
&nbsp;  KEYS = 0
&nbsp;  FILL = 0
&nbsp;  MAX = 7
&nbsp;  RITER = \-1
&nbsp;  EITER = 0x0
&nbsp;  RAND = 0xd63e354b
&nbsp;  NAME = "Iz"
&nbsp;  ENAME = "Iz"
$1 = void

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.27.1:

Configured by root at Sun May 28 01:44:41 MSK 2017.

Summary of my perl5 (revision 5 version 26 subversion 0) configuration:
  Derived from: 4c95ee9f298c2edfc1382d540ff89288790e78b6
  Platform:
    osname=linux
    osvers=4.9.0-3-amd64
    archname=x86_64-linux
    uname='linux dorothy 4.9.0-3-amd64 #1 smp debian 4.9.25-1
(2017-05-02) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING -Dcc=afl-clang-fast
-Doptimize=-O0 -g -ggdb3 -fno-omit-frame-pointer'
    hint=previous
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='afl-clang-fast'
    ccflags ='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O0 -g -ggdb3 -fno-omit-frame-pointer'
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Clang 3.9.1 (tags/RELEASE_391/rc2)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='afl-clang-fast'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/lib
/usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu
/lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
/usr/local/lib /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/lib
/usr/include/x86_64-linux-gnu /usr/lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.24.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.24'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O0 -g -ggdb3 -fno-omit-frame-pointer
-L/usr/local/lib -fstack-protector-strong'

Locally applied patches:
    uncommitted-changes


@INC for perl 5.27.1:
    lib
    /usr/local/lib/perl5/site_perl/5.26.0/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.26.0
    /usr/local/lib/perl5/5.26.0/x86_64-linux
    /usr/local/lib/perl5/5.26.0


Environment for perl 5.27.1:
    HOME=/home/afl
    LANG=en_US.UTF-8
    LANGUAGE=en_US:en
    LC_CTYPE=en_US.UTF-8
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.24.1-dbg/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    PERLBREW_BASHRC_VERSION=0.78
    PERLBREW_HOME=/home/afl/.perlbrew
    PERLBREW_MANPATH=/home/afl/perlbrew/perls/perl-5.24.1-dbg/man
    PERLBREW_PATH=/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.24.1-dbg/bin
    PERLBREW_PERL=perl-5.24.1-dbg
    PERLBREW_ROOT=/home/afl/perlbrew
    PERLBREW_VERSION=0.78
    PERL_BADLANG (unset)
    SHELL=/usr/bin/zshpe

```
</details>

**Comment by p5pRT** [comment]
### From @tonycoz

On Sat\, 24 Jun 2017 07&#8203;:01&#8203;:54 \-0700\, randir wrote&#8203;:
> While fuzzing perl v5\.27\.1\-37\-g4c95ee9f29 built with afl and run
> under libdislocator\, I found the following program
> 
> @&#8203;I0&#8203;::""my I0"";sub f00\}f00
> 
> to cause an assertion failure\. This is a regression between 5\.20 and
> 5\.22\, bisect points to&#8203;:
> 
> commit 0f94cb1fe27e58a59d3391214dab34037ab184db
> Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
> Date&#8203;:   Thu Nov 27 22&#8203;:30&#8203;:54 2014 \-0800
> 
> \[perl \#123223\] Make PADNAME a separate type
> 
> distinct from SV\.  This should fix the CPAN modules that were failing
> when the PadnameLVALUE flag was added\, because it shared the same
> bit as SVs\_OBJECT and pad names were going through code paths not
> designed to handle pad names\.
> 
> Unfortunately\, it will probably break other CPAN modules\, but I think
> this change is for the better\, as it makes both pad names and SVs sim\-
> pler and makes pad names take less memory\.
> 
> GDB info about the crash location is&#8203;:
> 
> \(gdb\) bt
> \#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at
> \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:51
> \#1  0x00007ffff6cf63fa in \_\_GI\_abort \(\) at abort\.c&#8203;:89
> \#2  0x00007ffff6cede37 in \_\_assert\_fail\_base \(fmt=\<optimized out>\,
>     assertion=assertion@&#8203;entry=0x5555558e3158 "SvTYPE\(cv\) == SVt\_PVCV
> || SvTYPE\(cv\) == SVt\_PVFM"\, file=file@&#8203;entry=0x5555558def2e "op\.c"\,
>     line=line@&#8203;entry=8067\, function=function@&#8203;entry=0x5555558e61f0
> \<\_\_PRETTY\_FUNCTION\_\_\.17680> "Perl\_cv\_const\_sv\_or\_av"\) at assert\.c&#8203;:92
> \#3  0x00007ffff6cedee2 in \_\_GI\_\_\_assert\_fail \(assertion=0x5555558e3158
> "SvTYPE\(cv\) == SVt\_PVCV || SvTYPE\(cv\) == SVt\_PVFM"\,
> file=0x5555558def2e "op\.c"\,
>     line=8067\, function=0x5555558e61f0 \<\_\_PRETTY\_FUNCTION\_\_\.17680>
> "Perl\_cv\_const\_sv\_or\_av"\) at assert\.c&#8203;:101
> \#4  0x00005555555a19d7 in Perl\_cv\_const\_sv\_or\_av \(cv=0x555555c0b530\)
> at op\.c&#8203;:8067
> \#5  0x0000555555627e6b in Perl\_yylex \(\) at toke\.c&#8203;:7406
> \#6  0x0000555555649164 in Perl\_yyparse \(gramtype=258\) at perly\.c&#8203;:340
> \#7  0x00005555555cad4c in S\_parse\_body \(env=0x0\, xsinit=0x555555583fe8
> \<xs\_init>\) at perl\.c&#8203;:2401
> \#8  0x00005555555c90b1 in perl\_parse \(my\_perl=0x555555bed010\,
> xsinit=0x555555583fe8 \<xs\_init>\, argc=2\, argv=0x7fffffffe1c8\, env=0x0\)
> at perl\.c&#8203;:1719
> \#9  0x0000555555583f26 in main \(argc=2\, argv=0x7fffffffe1c8\,
> env=0x7fffffffe1e0\) at perlmain\.c&#8203;:121
> \(gdb\) f 5
> \#5  0x0000555555627e6b in Perl\_yylex \(\) at toke\.c&#8203;:7406
> 7406    if \(\(sv = cv\_const\_sv\_or\_av\(cv\)\)\) \{
> \(gdb\) p sv\_dump\(cv\)
> SV = PVHV\(0x555555bf6010\) at 0x555555c0b530
>   REFCNT = 3
>   FLAGS = \(OOK\,SHAREKEYS\)
>   AUX\_FLAGS = 0
>   ARRAY = 0x555555c17e00
>   KEYS = 0
>   FILL = 0
>   MAX = 7
>   RITER = \-1
>   EITER = 0x0
>   RAND = 0xd63e354b
>   NAME = "Iz"
>   ENAME = "Iz"
> $1 = void

The parser appears to be treating the final f00 as the name of a lexical sub\, but finding a non\-CV in the protocv&#8203;:

\(gdb\) 
7077                        cv = find\_lexical\_cv\(off\);
2&#8203;: off = 2
1&#8203;: cv = \(CV \*\) 0x0
\(gdb\) call Perl\_sv\_dump\(PL\_compcv\)
SV = PVCV\(0x621000014100\) at 0x62100001bf48
&nbsp;  REFCNT = 6
&nbsp;  FLAGS = \(UNIQUE\,SLABBED\)
&nbsp;  COMP\_STASH = 0x0
&nbsp;  SLAB = 0x61500000fa80
&nbsp;  ROOT = 0x0
&nbsp;  GVGV&#8203;::GV = 0x0
&nbsp;  FILE = "\(null\)"
&nbsp;  DEPTH = 0
&nbsp;  FLAGS = 0x900
&nbsp;  OUTSIDE\_SEQ = 0
&nbsp;  PADLIST = 0x60300000eb90
&nbsp;  OUTSIDE = 0x0 \(null\)
\(gdb\) s
Perl\_find\_lexical\_cv \(off=2\) at op\.c&#8203;:11425
11425       PADNAME \*name = PAD\_COMPNAME\(off\);
\(gdb\) n
11426       CV \*compcv = PL\_compcv;
\(gdb\) p name
$4 = \(PADNAME \*\) 0x604000009890
\(gdb\) p \*name
$5 = \{xpadn\_pv = 0x6040000098ba "&f00"\, xpadn\_ourstash = 0x0\, xpadn\_type\_u = \{
&nbsp;    xpadn\_typestash = 0x6210000127a0\, xpadn\_protocv = 0x6210000127a0\}\, 
&nbsp;  xpadn\_low = 4294967246\, xpadn\_high = 4294967295\, xpadn\_refcnt = 1\, 
&nbsp;  xpadn\_gen = 0\, xpadn\_len = 4 '\\004'\, xpadn\_flags = 8 '\\b'\}
\(gdb\) n
11427       while \(PadnameOUTER\(name\)\) \{
\(gdb\) 
11433       assert\(\!PadnameIsOUR\(name\)\);
\(gdb\) 
11434       if \(\!PadnameIsSTATE\(name\) && PadnamePROTOCV\(name\)\) \{
\(gdb\) 
11435           return PadnamePROTOCV\(name\);
\(gdb\) 
11438   \}
\(gdb\) s
Perl\_yylex \(\) at toke\.c&#8203;:7079
7079                    lex = TRUE;
2&#8203;: off = 2
1&#8203;: cv = \(CV \*\) 0x6210000127a0
\(gdb\) call Perl\_sv\_dump\(cv\)
SV = PVHV\(0x6210000195a0\) at 0x6210000127a0
&nbsp;  REFCNT = 2
&nbsp;  FLAGS = \(OOK\,SHAREKEYS\)
&nbsp;  AUX\_FLAGS = 0
&nbsp;  ARRAY = 0x60c00000a780
&nbsp;  KEYS = 0
&nbsp;  FILL = 0
&nbsp;  MAX = 7
&nbsp;  RITER = \-1
&nbsp;  EITER = 0x0
&nbsp;  RAND = 0xd9a94a3f
&nbsp;  NAME = "I0"
&nbsp;  ENAME = "I0"
\(gdb\) p PL\_parser\->bufptr 
$6 = 0x60300000e5d7 "f00\\n"

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by zb226** [comment]
Bisecting shows [eb54d46](https://github.com/Perl/perl5/commit/eb54d46f7264ff7af62c409d8a6ab984a5a34f57) fixed this issue:

```
$ git describe
v5.37.3-255-g14580ae6b9
$ ./perl -e '@I0::""my I0"";sub f00}f00'
String found where operator expected at -e line 1, near "@I0::"""
        (Missing operator before ""?)
perl: op.c:9647: Perl_cv_const_sv_or_av: Assertion `SvTYPE(cv) == SVt_PVCV || SvTYPE(cv) == SVt_PVFM' failed.
Aborted (core dumped)

(...)

$ git describe
v5.37.3-256-geb54d46f72
$ ./perl -e '@I0::""my I0"";sub f00}f00'
String found where operator expected at -e line 1, near "@I0::"""
        (Missing operator before ""?)
syntax error at -e line 1, near "@I0::"""
Execution of -e aborted due to compilation errors.
```

This makes sense, as the commit is called "Stop parsing on first syntax error.", it was merged as [PR #20168](https://github.com/Perl/perl5/pull/20168).

Sidenote: The PR says it also fixes #17397 and #16944, but they're still open. I can verify these if wanted.

**Comment by jkeenan** [comment]
> Bisecting shows [eb54d46](https://github.com/Perl/perl5/commit/eb54d46f7264ff7af62c409d8a6ab984a5a34f57) fixed this issue:

Can you post the invocation to `Porting/bisect.pl` that you used to identify the healing commit?  thanks.

**Comment by zb226** [comment]
Sure, it was:

```
Porting/bisect.pl --start=v5.37.0 --end=v5.38.0 -DDEBUGGING --target=miniperl -- \
    ../test-bisect-segfault-gh16040.sh 2>&1 | tee ../test-bisect-segfault-gh16040.log
```

...with `../test-bisect-segfault-gh16040.sh` being

```
#!/bin/bash
./miniperl -e '@I0::""my I0"";sub f00}f00'
rctmp=$?
if [ $rctmp -eq 134 ]; then
    rc=0
    echo "good: return code $rctmp == 134"
else
    rc=1
    echo "bad: return code $rctmp != 134"
fi
exit $rc
```

**Comment by jkeenan** [comment]
> Sure, it was:
> 
> ```
> Porting/bisect.pl --start=v5.37.0 --end=v5.38.0 -DDEBUGGING --target=miniperl -- \
>     ../test-bisect-segfault-gh16040.sh 2>&1 | tee ../test-bisect-segfault-gh16040.log
> ```
> 
> ...with `../test-bisect-segfault-gh16040.sh` being
> 
> ```
> #!/bin/bash
> ./miniperl -e '@I0::""my I0"";sub f00}f00'
> rctmp=$?
> if [ $rctmp -eq 134 ]; then
>     rc=0
>     echo "good: return code $rctmp == 134"
> else
>     rc=1
>     echo "bad: return code $rctmp != 134"
> fi
> exit $rc
> ```

That's quite clever ... indeed, perhaps too clever for my brain!  You're calling our standard bisection program written in `perl`, asking it to build `./miniperl` at each commit encountered, at which point you run a shell script from somewhere outside the repository checkout, with that shell script running the `miniperl` you've just built.

While I believe that delivers the correct result, I don't understand why you had to jump through all these hoops.  Couldn't you have checked the return code from an instance of `./miniperl` without having to write an outside shell script?

Another way of asking the same question:  Couldn't you have invoked `Porting/bisect.pl` in a way described in either the SYNOPSIS or EXAMPLES in `perldoc Porting/bisect-runner.pl`?

I ask in part because I would also like to determine the status of https://github.com/Perl/perl5/issues/17397 and https://github.com/Perl/perl5/issues/16944.  Thanks.

**Comment by zb226** [comment]
Thanks for replying. Let me explain myself: I had read the [documentation for `Porting/bisect.pl`](https://metacpan.org/pod/bisect.pl) but didn't see an easy way to test for exit code 134 as good vs. 255 as bad. However, SYNOPSIS hinted at the possibility to run a separate script, albeit a `perl` one:

> \# When did this test program stop exiting 0?
> .../Porting/bisect.pl -- ./perl -Ilib ../test_prog.pl 

Since I need to map exit codes, I thought a shell script would be a good way and it would also allow me to easily add extra steps for my learning and understanding, like outputting the actual exit codes, run `git describe` or other commands. Putting that script in the parent folder - like in the SYNOPSIS quoted above - has the benefit that I can still run `git clean -dfx` in the perl working copy to get a clean slate without deleting my script. This was a viable setup for me to experiment. 

I've spent some time looking for a condensed solution without separate shell script:

```
Porting/bisect.pl --start=v5.37.0 --end=v5.38.0 -DDEBUGGING --target=miniperl -- \
    bash -c './miniperl ../gh16040-reproducer.pl; [ $? -eq 134 ] && exit 0 || exit 1'
```
The perl script contains only the verbatim reproducer code:

```
$ cat ../gh16040-reproducer.pl
@I0::""my I0"";sub f00}f00
```

If this is acceptable, I'd like to apply this method to the other two issues.

**Comment by jkeenan** [comment]
> 
> If this is acceptable, I'd like to apply this method to the other two issues.

Thanks; please proceed.
