### ISSUE TITLE
runtime error: left shift of 1 by 31 places cannot be represented in type 'int' (dump.c:581:52)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16117]
Migrated from [rt.perl.org#131912](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131912) (status was 'resolved')

Searchable as RT131912$

**Comment by p5pRT** [comment]
### From @geeknik

While fuzzing v5\.27\.2\-135\-g7aaa36b196\*\, undefined\-behavior was triggered in
the form of a 'left shift of 1 by 31 places' in dump\.c\.

\./perl \-DB \-e "/0\\l0@&#8203;0@&#8203;0\-@&#8203;0@&#8203;@&#8203;0@&#8203;@&#8203;0@&#8203;@&#8203;0@&#8203;@&#8203;0@&#8203;0@&#8203;@&#8203;0@&#8203;@&#8203;0@&#8203;@&#8203;0@&#8203;@&#8203;0@&#8203;@&#8203;0@&#8203;'0/"

\*SNIP\*

dump\.c&#8203;:581&#8203;:52&#8203;: runtime error&#8203;: left shift of 1 by 31 places cannot be
represented in type 'int'
&nbsp;    \#0 0xc86d96 in S\_opdump\_indent /root/perl5/dump\.c&#8203;:581&#8203;:52
&nbsp;    \#1 0xc1b6a1 in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:986&#8203;:5
&nbsp;    \#2 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#3 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#4 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#5 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#6 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#7 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#8 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#9 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#10 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#11 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#12 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#13 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#14 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#15 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#16 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#17 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#18 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#19 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#20 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#21 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#22 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#23 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#24 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#25 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#26 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#27 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#28 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#29 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#30 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#31 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#32 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#33 0xc1dc8a in S\_do\_op\_dump\_bar /root/perl5/dump\.c&#8203;:1268&#8203;:6
&nbsp;    \#34 0xc1252c in Perl\_do\_op\_dump /root/perl5/dump\.c&#8203;:1278&#8203;:5
&nbsp;    \#35 0xc1252c in Perl\_op\_dump /root/perl5/dump\.c&#8203;:1294
&nbsp;    \#36 0xc1252c in Perl\_dump\_all\_perl /root/perl5/dump\.c&#8203;:640
&nbsp;    \#37 0x6c8487 in S\_run\_body /root/perl5/perl\.c&#8203;:2527&#8203;:6
&nbsp;    \#38 0x6c8487 in perl\_run /root/perl5/perl\.c&#8203;:2484
&nbsp;    \#39 0x5251dc in main /root/perl5/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#40 0x7ff3a1cb34d9 in \_\_libc\_start\_main \(/lib64/libc\.so\.6\+0x204d9\)
&nbsp;    \#41 0x4359d9 in \_start \(/root/perl5/perl\+0x4359d9\)

SUMMARY&#8203;: AddressSanitizer&#8203;: undefined\-behavior dump\.c&#8203;:581&#8203;:52

**Comment by p5pRT** [comment]
### From @iabyn

On Wed\, Aug 16\, 2017 at 11&#8203;:19&#8203;:22AM \-0700\, Brian Carpenter wrote&#8203;:
> \# New Ticket Created by  Brian Carpenter 
> \# Please include the string&#8203;:  \[perl \#131912\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131912 >
> 
> 
> While fuzzing v5\.27\.2\-135\-g7aaa36b196\*\, undefined\-behavior was triggered in
> the form of a 'left shift of 1 by 31 places' in dump\.c\.
> 
> \./perl \-DB \-e "/0\\l0@&#8203;0@&#8203;0\-@&#8203;0@&#8203;@&#8203;0@&#8203;@&#8203;0@&#8203;@&#8203;0@&#8203;@&#8203;0@&#8203;0@&#8203;@&#8203;0@&#8203;@&#8203;0@&#8203;@&#8203;0@&#8203;@&#8203;0@&#8203;@&#8203;0@&#8203;'0/"
> 
> \*SNIP\*
> 
> dump\.c&#8203;:581&#8203;:52&#8203;: runtime error&#8203;: left shift of 1 by 31 places cannot be
> represented in type 'int'
>     \#0 0xc86d96 in S\_opdump\_indent /root/perl5/dump\.c&#8203;:581&#8203;:52

It's kind of intended behaviour\. It's the mechanism for adding vertical
bars when dumping ops\, e\.g\.&#8203;:

11   \+\-\-add BINOP\(0x26fbbf0\) ===> 1 \[leave 0x26fa600\]
&nbsp;         TARG = 5
&nbsp;         FLAGS = \(VOID\,KIDS\,SLABBED\)
&nbsp;         PRIVATE = \(0x2\)
&nbsp;         |   
12       \+\-\-add BINOP\(0x26fbc70\) ===> 13 \[padsv 0x26fbc38\]
&nbsp;         |   TARG = 4
&nbsp;         |   FLAGS = \(SCALAR\,KIDS\,PARENS\,SLABBED\,MORESIB\)
&nbsp;         |   PRIVATE = \(0x2\)
&nbsp;         |   |   
10       |   \+\-\-padsv OP\(0x26fbcf0\) ===> 14 \[padsv 0x26fbcb8\]
&nbsp;         |   |   TARG = 1
&nbsp;         |   |   FLAGS = \(SCALAR\,SLABBED\,MORESIB\)
&nbsp;         |   |   
14       |   \+\-\-padsv OP\(0x26fbcb8\) ===> 12 \[add 0x26fbc70\]
&nbsp;         |       TARG = 2
&nbsp;         |       FLAGS = \(SCALAR\,SLABBED\)
&nbsp;         |   
13       \+\-\-padsv OP\(0x26fbc38\) ===> 11 \[add 0x26fbbf0\]
&nbsp;             TARG = 3
&nbsp;             FLAGS = \(SCALAR\,SLABBED\)

The code uses the bits in an int to indicate which columns in the leading
indentation get a vertical bar\. When the indentation gets too great\, it
doesn't bother with the left\-most bars\. However\, the code could be
tweaked to make clang happy\, which is what I've just pushed as
v5\.27\.2\-142\-gf649c62\.


\-\- 
The Enterprise is involved in a bizarre time\-warp experience which is in
some way unconnected with the Late 20th Century\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#14

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
