### ISSUE TITLE
runtime error: signed integer overflow: 1 + 9223372036854775807 cannot be represented in type 'long' (regcomp.c:5935:23)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16113]
Migrated from [rt.perl.org#131893](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131893) (status was 'resolved')

Searchable as RT131893$

**Comment by p5pRT** [comment]
### From @geeknik

While fuzzing v5\.27\.2\-135\-g7aaa36b196\*\, undefined\-behavior was triggered in
the form of a signed integer overflow in regcomp\.c\, however I'm not sure if
this is a bug\.

\./perl \-e "0=~'0\(0?\(0||00\*\)\)|'"

regcomp\.c&#8203;:5935&#8203;:23&#8203;: runtime error&#8203;: signed integer overflow&#8203;: 1 \+
9223372036854775807 cannot be represented in type 'long'
&nbsp;    \#0 0xa5aa70 in S\_study\_chunk /root/perl5/regcomp\.c&#8203;:5935&#8203;:23
&nbsp;    \#1 0xa6df1c in S\_study\_chunk /root/perl5/regcomp\.c&#8203;:5894&#8203;:35
&nbsp;    \#2 0x9d6c65 in Perl\_re\_op\_compile /root/perl5/regcomp\.c&#8203;:7574&#8203;:11
&nbsp;    \#3 0x56abc9 in Perl\_pmruntime /root/perl5/op\.c&#8203;:5885&#8203;:6
&nbsp;    \#4 0x56413d in Perl\_bind\_match /root/perl5/op\.c&#8203;:4017&#8203;:9
&nbsp;    \#5 0x96ddc0 in Perl\_yyparse /root/perl5/perly\.y&#8203;:990&#8203;:23
&nbsp;    \#6 0x6c1dfe in S\_parse\_body /root/perl5/perl\.c&#8203;:2414&#8203;:9
&nbsp;    \#7 0x6aeb39 in perl\_parse /root/perl5/perl\.c&#8203;:1732&#8203;:2
&nbsp;    \#8 0x5251b6 in main /root/perl5/perlmain\.c&#8203;:121&#8203;:18
&nbsp;    \#9 0x7fe7401094d9 in \_\_libc\_start\_main \(/lib64/libc\.so\.6\+0x204d9\)
&nbsp;    \#10 0x4359d9 in \_start \(/root/perl5/perl\+0x4359d9\)

SUMMARY&#8203;: AddressSanitizer&#8203;: undefined\-behavior regcomp\.c&#8203;:5935&#8203;:23

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Brian Carpenter wrote&#8203;:
>the form of a signed integer overflow in regcomp\.c\, however I'm not sure if
>this is a bug\.
>
>\./perl \-e "0=~'0\(0?\(0||00\*\)\)|'"

There's nothing pathological about that regexp\.  I reckon it's a bug\.

\-zefram

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Sun\, 13 Aug 2017 19&#8203;:33&#8203;:16 \-0700\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> While fuzzing v5\.27\.2\-135\-g7aaa36b196\*\, undefined\-behavior was triggered in
> the form of a signed integer overflow in regcomp\.c\, however I'm not sure if
> this is a bug\.
> 
> \./perl \-e "0=~'0\(0?\(0||00\*\)\)|'"

The attached fixes it for me\.

There's other similar issues\, perhaps it's finally time to do the work to close 121505\.

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

<details><summary>0001-perl-131893-prevent-integer-overflow-when-compiling-.patch</summary>

```diff
From f901dfa07af600039d9479d4da63db04b3b40f42 Mon Sep 17 00:00:00 2001
From: Tony Cook <tony@develop-help.com>
Date: Mon, 14 Aug 2017 15:10:22 +1000
Subject: (perl #131893) prevent integer overflow when compiling a regexp

a specific regexp in this case, other regexps may cause other overflows
---
 regcomp.c  | 8 ++++++--
 t/re/pat.t | 6 +++++-
 2 files changed, 11 insertions(+), 3 deletions(-)

diff --git a/regcomp.c b/regcomp.c
index 5a9e56b..a421d24 100644
--- a/regcomp.c
+++ b/regcomp.c
@@ -5931,8 +5931,12 @@ Perl_re_printf( aTHX_  "LHS=%" UVuf " RHS=%" UVuf "\n",
                     data->cur_is_floating = 1; /* float */
             }
             min += min1;
-            if (delta != SSize_t_MAX)
-                delta += max1 - min1;
+            if (delta != SSize_t_MAX) {
+                if (SSize_t_MAX - (max1 - min1) >= delta)
+                    delta += max1 - min1;
+                else
+                    delta = SSize_t_MAX;
+            }
             if (flags & SCF_DO_STCLASS_OR) {
                 ssc_or(pRExC_state, data->start_class, (regnode_charclass *) &accum);
                 if (min1) {
diff --git a/t/re/pat.t b/t/re/pat.t
index fb6d4c4..984fd66 100644
--- a/t/re/pat.t
+++ b/t/re/pat.t
@@ -23,7 +23,7 @@ BEGIN {
     skip_all('no re module') unless defined &DynaLoader::boot_DynaLoader;
     skip_all_without_unicode_tables();
 
-plan tests => 837;  # Update this when adding/deleting tests.
+plan tests => 838;  # Update this when adding/deleting tests.
 
 run_tests() unless caller;
 
@@ -1916,6 +1916,10 @@ EOP
         pos($text) = 3;
         ok(scalar($text !~ m{(~*=[a-z]=)}g), "RT #131575");
     }
+    {
+        # RT #131893 - fails with ASAN -fsanitize=undefined
+        fresh_perl_is('qr/0(0?(0||00*))|/', '', {}, "integer overflow during compilation");
+    }
 
 } # End of sub run_tests
 
-- 
2.1.4


```
</details>

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Tony's patch looks good to me\.  I've applied it as commit
6c4f4eb174d1e2e9f874786123a699d11ae741f9\.

\-zefram

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release yesterday of Perl 5\.28\.0\, this and 185 other issues have been
resolved\.

Perl 5\.28\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.28.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
