### ISSUE TITLE
heap-buffer-overflow in token.c:S_scan_formline()

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16125]
Migrated from [rt.perl.org#131955](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131955) (status was 'resolved')

Searchable as RT131955$

**Comment by p5pRT** [comment]
### From imdb95@gmail.com

Hello\,
I found this bug when fuzzing perl5 with afl\-fuzz\.

\*\*\*\*\*\*\*\*\*\*Build Date & Hardware\*\*\*\*\*\*\*\*\*\*
Version&#8203;: Version&#8203;: the dev version \(https://perl5.git.perl.org/perl.git)
manh@&#8203;manh\-VirtualBox&#8203;:\~/Fuzzing/afl/perl$ \./perl/perl \-v

This is perl 5\, version 27\, subversion 4 \(v5\.27\.4
\(v5\.27\.3\-14\-gd2dccc0\)\) built for x86\_64\-linux

Copyright 1987\-2017\, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License\, which may be found in the Perl 5 source kit\.

Complete documentation for Perl\, including FAQ lists\, should be found on
this system using "man perl" or "perldoc perl"\.  If you have access to the
Internet\, point your browser at http&#8203;://www\.perl\.org/\, the Perl Home Page\.


---
OS&#8203;: Ubuntu 16\.04 Desktop
manh@&#8203;manh\-VirtualBox&#8203;:\~/Fuzzing/afl/perl$ uname \-a
Linux manh\-VirtualBox 4\.4\.0\-92\-generic \#115\-Ubuntu SMP Thu Aug 10
09&#8203;:04&#8203;:33 UTC 2017 x86\_64 x86\_64 x86\_64 GNU/Linux


---
Compilation&#8203;:
AFL\_USE\_ASAN=1 \./Configure \-des \-Dusedevel \-DDEBUGGING
\-Dcc=afl\-clang\-fast \-Doptimize=\-O0\\ \-g && AFL\_USE\_ASAN=1 make

\*\*\*\*\*\*\*\*\*\*Reproduce\*\*\*\*\*\*\*\*\*\*
manh@&#8203;manh\-VirtualBox&#8203;:\~/Fuzzing/afl/perl$ \./perl/perl crash\_heap\_S\_scan\_formline
String found where operator expected at crash\_heap\_S\_scan\_formline
line 476\, near "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"sidekick function
called""
=================================================================
==24365==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
0x625000007108 at pc 0x00000044f1d5 bp 0x7fffffffc790 sp
0x7fffffffbf40
READ of size 30774 at 0x625000007108 thread T0
&nbsp;    \#0 0x44f1d4 in \_\_interceptor\_memchr
/scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-rt/lib/asan/\.\./sanitizer\_common/sanitizer\_common\_interceptors\.inc&#8203;:739&#8203;:3
&nbsp;    \#1 0x650340 in S\_scan\_formline
/home/manh/Fuzzing/afl/perl/perl/toke\.c&#8203;:11374&#8203;:17
&nbsp;    \#2 0x650340 in Perl\_yylex /home/manh/Fuzzing/afl/perl/perl/toke\.c&#8203;:5068
&nbsp;    \#3 0x6ed7c1 in Perl\_yyparse /home/manh/Fuzzing/afl/perl/perl/perly\.c&#8203;:340&#8203;:34
&nbsp;    \#4 0x5da9e9 in S\_parse\_body /home/manh/Fuzzing/afl/perl/perl/perl\.c&#8203;:2414&#8203;:9
&nbsp;    \#5 0x5d0f38 in perl\_parse /home/manh/Fuzzing/afl/perl/perl/perl\.c&#8203;:1732&#8203;:2
&nbsp;    \#6 0x5093cc in main /home/manh/Fuzzing/afl/perl/perl/perlmain\.c&#8203;:121&#8203;:18
&nbsp;    \#7 0x7ffff6caf82f in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2082f\)
&nbsp;    \#8 0x435928 in \_start \(/home/manh/Fuzzing/afl/perl/perl/perl\+0x435928\)

0x625000007108 is located 0 bytes to the right of 8200\-byte region
\[0x625000005100\,0x625000007108\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4dc9de in realloc
/scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-rt/lib/asan/asan\_malloc\_linux\.cc&#8203;:79&#8203;:3
&nbsp;    \#1 0x83f1b6 in Perl\_safesysrealloc
/home/manh/Fuzzing/afl/perl/perl/util\.c&#8203;:274&#8203;:18

SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow
/scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-rt/lib/asan/\.\./sanitizer\_common/sanitizer\_common\_interceptors\.inc&#8203;:739&#8203;:3
in \_\_interceptor\_memchr
Shadow bytes around the buggy address&#8203;:
&nbsp;  0x0c4a7fff8dd0&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c4a7fff8de0&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c4a7fff8df0&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c4a7fff8e00&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c4a7fff8e10&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c4a7fff8e20&#8203;: 00\[fa\]fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c4a7fff8e30&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c4a7fff8e40&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c4a7fff8e50&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c4a7fff8e60&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c4a7fff8e70&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend \(one shadow byte represents 8 application bytes\)&#8203;:
&nbsp;  Addressable&#8203;:           00
&nbsp;  Partially addressable&#8203;: 01 02 03 04 05 06 07
&nbsp;  Heap left redzone&#8203;:       fa
&nbsp;  Freed heap region&#8203;:       fd
&nbsp;  Stack left redzone&#8203;:      f1
&nbsp;  Stack mid redzone&#8203;:       f2
&nbsp;  Stack right redzone&#8203;:     f3
&nbsp;  Stack after return&#8203;:      f5
&nbsp;  Stack use after scope&#8203;:   f8
&nbsp;  Global redzone&#8203;:          f9
&nbsp;  Global init order&#8203;:       f6
&nbsp;  Poisoned by user&#8203;:        f7
&nbsp;  Container overflow&#8203;:      fc
&nbsp;  Array cookie&#8203;:            ac
&nbsp;  Intra object redzone&#8203;:    bb
&nbsp;  ASan internal&#8203;:           fe
&nbsp;  Left alloca redzone&#8203;:     ca
&nbsp;  Right alloca redzone&#8203;:    cb
==24365==ABORTING
\*\*\*\*\*\*\*\*\*\*Analysis\*\*\*\*\*\*\*\*\*\*
The heap\-buffer\-overflow occurs when memchr reads over the end of string s
&nbsp;             eol = \(char \*\) memchr\(s\,'\\n'\,PL\_bufend\-s\);
The memchr call that triggers the bug has s = 0x625000005158\,
\(PL\_bufend\-s\) = 0xffffffffffffffb2

\(gdb\) b /home/manh/Fuzzing/afl/perl/perl/toke\.c&#8203;:11374
Breakpoint 9 at 0x65030a&#8203;: file toke\.c\, line 11374\.
\(gdb\) ignore 9 346
Will ignore next 346 crossings of breakpoint 9\.
\(gdb\) r
The program being debugged has been started already\.
Start it from the beginning? \(y or n\) y
Starting program&#8203;: /home/manh/Fuzzing/afl/perl/perl/perl id&#8203;:000034\*
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
String found where operator expected at
id&#8203;:000034\,sig&#8203;:06\,src&#8203;:000048\+001627\,op&#8203;:splice\,rep&#8203;:2 line 476\, near
"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"sidekick function called""

Breakpoint 9\, S\_scan\_formline \(s=\<optimized out>\) at toke\.c&#8203;:11374
11374        eol = \(char \*\) memchr\(s\,'\\n'\,PL\_bufend\-s\);
\(gdb\) b \*memchr
Breakpoint 10 at 0x44ee80&#8203;: file
/scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-rt/lib/asan/\.\./sanitizer\_common/sanitizer\_common\_interceptors\.inc\,
line 723\.
\(gdb\) c
Continuing\.

Breakpoint 10\, \_\_interceptor\_memchr \(\)
&nbsp;    at /scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-rt/lib/asan/\.\./sanitizer\_common/sanitizer\_common\_interceptors\.inc&#8203;:723
723    /scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-rt/lib/asan/\.\./sanitizer\_common/sanitizer\_common\_interceptors\.inc&#8203;:
No such file or directory\.
\(gdb\) printf "arg0&#8203;: %p\, arg1&#8203;: %p\, arg2&#8203;: %p\\n"\, $rdi\, $rsi\, $rdx
arg0&#8203;: 0x625000005158\, arg1&#8203;: 0xa\, arg2&#8203;: 0xffffffffffffffb2

\*\*\*\*\*\*\*\*\*\*Additional Information\*\*\*\*\*\*\*\*\*\*
My default perl also crashes with the crafted file&#8203;:
manh@&#8203;manh\-VirtualBox&#8203;:\~/Fuzzing/afl/perl$ perl \-v

This is perl 5\, version 22\, subversion 1 \(v5\.22\.1\) built for
x86\_64\-linux\-gnu\-thread\-multi
\(with 58 registered patches\, see perl \-V for more detail\)

Copyright 1987\-2015\, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License\, which may be found in the Perl 5 source kit\.

Complete documentation for Perl\, including FAQ lists\, should be found on
this system using "man perl" or "perldoc perl"\.  If you have access to the
Internet\, point your browser at http&#8203;://www\.perl\.org/\, the Perl Home Page\.

manh@&#8203;manh\-VirtualBox&#8203;:\~/Fuzzing/afl/perl$ perl crash\_heap\_S\_scan\_formline
String found where operator expected at crash\_heap\_S\_scan\_formline
line 476\, near "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"sidekick function
called""
Attempt to free unreferenced scalar&#8203;: SV 0x835678\, Perl interpreter&#8203;:
0x7d2010 at crash\_heap\_S\_scan\_formline line 497\.
Attempt to free unreferenced scalar&#8203;: SV 0x835678\, Perl interpreter&#8203;:
0x7d2010 at crash\_heap\_S\_scan\_formline line 497\.
Segmentation fault \(core dumped\)

Best\,
Manh

**Comment by p5pRT** [comment]
### From imdb95@gmail.com

[crash_heap_S_scan_formline](https://rt-archive.perl.org/perl5/Ticket/Attachment/1484102/800953/crash_heap_S_scan_formline)

**Comment by p5pRT** [comment]
### From imdb95@gmail.com

Greetings\,
Have you take a look at fixing this bug please?

On Thu\, Aug 24\, 2017 at 12&#8203;:16 PM\, \<perl5\-security\-report@&#8203;perl\.org> wrote&#8203;:

> Greetings\,
>
> This message has been automatically generated in response to the
> creation of a perl security report regarding&#8203;:
>    "heap\-buffer\-overflow in token\.c&#8203;:S\_scan\_formline\(\)"\.
>
> There is no need to reply to this message right now\.  Your ticket has been
> assigned an ID of \[perl \#131955\]\.
>
> Please include the string&#8203;:
>
>    \[perl \#131955\]
>
> in the subject line of all future correspondence about this issue\. To do
> so\,
> you may reply to this message \(please delete unnecessary quotes and text\.\)
>
>   Thank you\,
>   perl5\-security\-report@&#8203;perl\.org
>
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> X\-GM\-Message\-State&#8203;: AHYfb5gYFqK4X9bQanqlIN28v4lvRQAhMyXAup1DxMqTNZSnESbQaaLL
> mQjNDAkAQ4aNGAToeR\+gtpom2zEaFW/c
> Dkim\-Signature&#8203;: v=1; a=rsa\-sha256; c=relaxed/relaxed; d=gmail\.com;
> s=20161025; h=mime\-version&#8203;:from&#8203;:date&#8203;:message\-id&#8203;:subject&#8203;:to;
> bh=wLm4OS1LVS7bwMAkvsK/MUFfM2EeUMNUe8IYtdrl6hM=;
> b=an1SIzrcHiF5e0dSEbsqrIQ\+JqtYjvrMb9838ejHZoNfCsnztu3l9oiWL5p0yKk4Qc
> pNWkfuaqHLOqB9/y6SaOWddD5bCb1n8Fmqm7d3OenSsyPDeFUrMe\+4bSPbM\+BwsRoXH2
> J0kqtsefIItWFuYPprQnaIU6fqhcEkVbz9I4DVQfieB3bvrQzQffhRyOPC1Zi0aNP3u5
> 15JWF6AHy/j6i88RiLW0tyJ546HXdN3lSQfpm8O8ZI\+SU9YJZzh1F2qu\+FAvMgn2lcSe
> 9a8Wv1LaEg4LvWHc86qBmdx5ExB1Wq2VpBWqxPk8PB8Wb6jjKe\+kH1UMubt18aA4ViE0
> XBAQ==
> MIME\-Version&#8203;: 1\.0
> X\-RT\-Mail\-Extension&#8203;: perl5\-security
> Received&#8203;: from xx1\.develooper\.com \(xx1\.dev \[10\.0\.100\.115\]\) by
> rtperl\.develooper\.com \(Postfix\) with ESMTP id 3E4071FD for
> \<rt\-perl5\-security@&#8203;rtperl\.dev>; Wed\, 23 Aug 2017 22&#8203;:16&#8203;:10 \-0700 \(PDT\)
> Received&#8203;: from localhost \(xx1\.develooper\.com \[127\.0\.0\.1\]\) by localhost
> \(Postfix\) with ESMTP id 4161E11DED8 for \<rt\-perl5\-security@&#8203;rtperl\.dev>;
> Wed\, 23 Aug 2017 22&#8203;:16&#8203;:05 \-0700 \(PDT\)
> Received&#8203;: from xx1\.develooper\.com \(xx1\.develooper\.com \[127\.0\.0\.1\]\) by
> localhost \(Postfix\) with SMTP id F080E11DA46 for
> \<rt\-perl5\-security@&#8203;rtperl\.dev>; Wed\, 23 Aug 2017 22&#8203;:16&#8203;:01 \-0700 \(PDT\)
> Received&#8203;: from x6\.develooper\.com \(x6\.develooper\.com \[207\.171\.7\.86\]\)
> \(using TLSv1 with cipher ADH\-AES256\-SHA \(256/256 bits\)\) \(No client
> certificate requested\) by xx1\.develooper\.com \(Postfix\) with ESMTPS id
> 9AD7911DA22 for \<rt\-perl5\-security@&#8203;rt\.perl\.org>; Wed\, 23 Aug 2017
> 22&#8203;:16&#8203;:01 \-0700 \(PDT\)
> Received&#8203;: by x6\.develooper\.com \(Postfix\, from userid 514\) id 66D415B;
> Wed\, 23 Aug 2017 22&#8203;:16&#8203;:01 \-0700 \(PDT\)
> Received&#8203;: \(qmail 22880 invoked from network\); 24 Aug 2017 05&#8203;:16&#8203;:01 \-0000
> Received&#8203;: from xx1\.develooper\.com \(207\.171\.7\.115\) by x6\.develooper\.com
> with SMTP; 24 Aug 2017 05&#8203;:16&#8203;:01 \-0000
> Received&#8203;: from localhost \(xx1\.develooper\.com \[127\.0\.0\.1\]\) by localhost
> \(Postfix\) with ESMTP id BDCDC11DA22 for \<perlmail\-perl5\-security\-
> report@&#8203;onion\.perl\.org>; Wed\, 23 Aug 2017 22&#8203;:16&#8203;:00 \-0700 \(PDT\)
> Received&#8203;: from xx1\.develooper\.com \(xx1\.develooper\.com \[127\.0\.0\.1\]\) by
> localhost \(Postfix\) with SMTP id B8FBE11DA46 for \<perlmail\-perl5\-security\-
> report@&#8203;onion\.perl\.org>; Wed\, 23 Aug 2017 22&#8203;:15&#8203;:57 \-0700 \(PDT\)
> Received&#8203;: from mail\-io0\-f173\.google\.com \(mail\-io0\-f173\.google\.com
> \[209\.85\.223\.173\]\) \(using TLSv1 with cipher AES128\-SHA \(128/128 bits\)\) \(No
> client certificate requested\) by xx1\.develooper\.com \(Postfix\) with ESMTPS
> id 9363411DA22 for \<perl5\-security\-report@&#8203;perl\.org>; Wed\, 23 Aug 2017
> 22&#8203;:15&#8203;:55 \-0700 \(PDT\)
> Received&#8203;: by mail\-io0\-f173\.google\.com with SMTP id j99so1243818ioo\.1 for \<
> perl5\-security\-report@&#8203;perl\.org>; Wed\, 23 Aug 2017 22&#8203;:15&#8203;:55 \-0700 \(PDT\)
> Received&#8203;: by 10\.79\.208\.248 with HTTP; Wed\, 23 Aug 2017 22&#8203;:15&#8203;:53 \-0700 \(PDT\)
> To&#8203;: perl5\-security\-report@&#8203;perl\.org
> Delivered\-To&#8203;: rt\-perl5\-security@&#8203;rtperl\.dev
> Delivered\-To&#8203;: perlmail\-perl5\-security\-report@&#8203;onion\.perl\.org
> Date&#8203;: Thu\, 24 Aug 2017 12&#8203;:15&#8203;:53 \+0700
> Content\-Type&#8203;: multipart/mixed; boundary="001a114441283a5834055778ecd3"
> X\-PMX\-Spam&#8203;: Gauge=IIIIIIII\, Probability=8%\, Report='
> BODYTEXTH\_SIZE\_10000\_LESS 0\, BODYTEXTH\_SIZE\_3000\_MORE 0\,
> BODY\_SIZE\_10000\_PLUS 0\, DKIM\_SIGNATURE 0\, SPF\_PASS 0\, WEBMAIL\_SOURCE 0\,
> \_\_ANY\_URI 0\, \_\_ATTACHMENT\_SIZE\_10\_25K 0\, \_\_CP\_URI\_IN\_BODY 0\, \_\_CT 0\,
> \_\_CTYPE\_HAS\_BOUNDARY 0\, \_\_CTYPE\_MULTIPART 0\, \_\_CTYPE\_MULTIPART\_MIXED 0\,
> \_\_DQ\_NEG\_HEUR 0\, \_\_DQ\_NEG\_IP 0\, \_\_FRAUD\_BADTHINGS 0\, \_\_FRAUD\_CONTACT\_ADDY
> 0\, \_\_FRAUD\_MONEY\_CURRENCY 0\, \_\_FRAUD\_MONEY\_CURRENCY\_DOLLAR 0\,
> \_\_FRAUD\_WEBMAIL 0\, \_\_FRAUD\_WEBMAIL\_FROM 0\, \_\_FROM\_GMAIL 0\, \_\_HAS\_ATTACHMENT
> 0\, \_\_HAS\_ATTACHMENT1 0\, \_\_HAS\_ATTACHMENT2 0\, \_\_HAS\_FROM 0\, \_\_HAS\_HTML 0\,
> \_\_HAS\_MSGID 0\, \_\_HELO\_GMAIL 0\, \_\_HEX28\_LC\_BOUNDARY 0\, \_\_HTML\_AHREF\_TAG 0\,
> \_\_HTML\_TAG\_DIV 0\, \_\_HTTPS\_URI 0\, \_\_INT\_PROD\_COMP 0\, \_\_MIME\_HTML 0\,
> \_\_MIME\_TEXT\_H 0\, \_\_MIME\_TEXT\_H1 0\, \_\_MIME\_TEXT\_H2 0\, \_\_MIME\_TEXT\_P 0\,
> \_\_MIME\_TEXT\_P1 0\, \_\_MIME\_TEXT\_P2 0\, \_\_MIME\_VERSION 0\, \_\_MULTIPLE\_URI\_HTML
> 0\, \_\_MULTIPLE\_URI\_TEXT 0\, \_\_PHISH\_SPEAR\_HTTP\_RECEIVED 0\,
> \_\_PHISH\_SPEAR\_STRUCTURE\_1 0\, \_\_RDNS\_GMAI
>  L 0\, \_\_SANE\_MSGID 0\, \_\_SUBJ\_ALPHA\_START 0\, \_\_TO\_MALFORMED\_2 0\,
> \_\_TO\_NO\_NAME 0\, \_\_URI\_IN\_BODY 0\, \_\_URI\_NOT\_IMG 0\, \_\_URI\_NO\_MAILTO 0\,
> \_\_URI\_NS \, \_\_URI\_WITHOUT\_PATH 0\, \_\_URI\_WITH\_PATH 0\, \_\_YOUTUBE\_RCVD 0\,
> \_\_zen\.spamhaus\.org\_ERROR '
> Return\-Path&#8203;: \<perlmail@&#8203;x6\.develooper\.com>
> Message\-ID&#8203;: \<CAMmf60gR68FgVtGkCEHJjyNZUhL5mxcuSOdZY0Ba2jicz0n\+KA@&#8203;mail\.
> gmail\.com>
> From&#8203;: Manh Nguyen \<imdb95@&#8203;gmail\.com>
> X\-Spam\-Checker\-Version&#8203;: SpamAssassin 3\.3\.1 \(2010\-03\-16\) on
> mx3\.develooper\.com
> X\-Original\-To&#8203;: rt\-perl5\-security@&#8203;rtperl\.dev
> X\-PMX\-Version&#8203;: 5\.6\.1\.2065439\, Antispam\-Engine&#8203;: 2\.7\.2\.376379\,
> Antispam\-Data&#8203;: 2017\.8\.24\.50316
> X\-PMX\-Version&#8203;: 5\.6\.1\.2065439\, Antispam\-Engine&#8203;: 2\.7\.2\.376379\,
> Antispam\-Data&#8203;: 2017\.8\.24\.50316
> X\-Spam\-Status&#8203;: No\, score=\-1\.5 required=6\.0 tests=BAYES\_00\,DKIM\_SIGNED\,
> DKIM\_VALID\,DKIM\_VALID\_AU\,FREEMAIL\_FROM\,HTML\_MESSAGE\,RCVD\_IN\_DNSWL\_NONE\,
> RCVD\_IN\_SORBS\_SPAM autolearn=no version=3\.3\.1
> Subject&#8203;: heap\-buffer\-overflow in token\.c&#8203;:S\_scan\_formline\(\)
> X\-Received&#8203;: by 10\.107\.48\.21 with SMTP id w21mr5010448iow\.12\.1503551754478;
> Wed\, 23 Aug 2017 22&#8203;:15&#8203;:54 \-0700 \(PDT\)
> X\-Google\-Dkim\-Signature&#8203;: v=1; a=rsa\-sha256; c=relaxed/relaxed; d=1e100\.net;
> s=20161025; h=x\-gm\-message\-state&#8203;:mime\-version&#8203;:from&#8203;:date&#8203;:message\-id&#8203;:subject&#8203;:to;
> bh=wLm4OS1LVS7bwMAkvsK/MUFfM2EeUMNUe8IYtdrl6hM=; b=VJGDQqCDnZBGSskJmXJ/
> aDhGxKdVn4Eo2kdySH9Xl9wve3JMnSVwbyemghzzbaUyOs CG\+
> e6sUgaS2RKBOY9j5GRVWdE5shBxfe63eNgbNR2zsY89trwcS4vhIYVFiYIWvZVoyN
> LF2U9hyz/m8v3YYzpjS4OZccM9m0yUttmPQvymNTcDZyo1pC9pLxkgHlmYBAc3yqWjoP
> LCnCC3cS0EHgu4DgdFk8AS6BupnoNcNEEv6RRPsLFnlQiCOXm81FMEY/of7\+kawWN5Tr
> gR7zr7ZQatwGnwwZxeGP7VclFfEmAKQXUMZzRNc9\+k74eIWRrySoJ5swBIWFwEfGLVGw
> \+UwA==
> From perlmail@&#8203;x6\.develooper\.com  Wed Aug 23 22&#8203;:16&#8203;:10 2017
> X\-RT\-Interface&#8203;: Email
>

**Comment by p5pRT** [comment]
### From @tonycoz

On Sun\, 27 Aug 2017 01&#8203;:10&#8203;:04 \-0700\, imdb95@&#8203;gmail\.com wrote&#8203;:
> Greetings\,
> Have you take a look at fixing this bug please?

I expect to take a close look at it tomorrow \(or maybe later today\)\.

Just from the backtrace it doesn't appear to be a security issue\, but I won't be sure of that until I take that close look\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Sun\, 27 Aug 2017 17&#8203;:10&#8203;:40 \-0700\, tonyc wrote&#8203;:
> On Sun\, 27 Aug 2017 01&#8203;:10&#8203;:04 \-0700\, imdb95@&#8203;gmail\.com wrote&#8203;:
> > Greetings\,
> > Have you take a look at fixing this bug please?
> 
> I expect to take a close look at it tomorrow \(or maybe later today\)\.
> 
> Just from the backtrace it doesn't appear to be a security issue\, but
> I won't be sure of that until I take that close look\.

This requires feeding code to the parser and isn't a security issue\.

scan\_formline\(\) is being entered with PL\_bufptr == PL\_bufend\+1 and things go downhill from there\.

I haven't tracked down exactly why that's happening though\.

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon\, 28 Aug 2017 18&#8203;:42&#8203;:02 \-0700\, tonyc wrote&#8203;:
> On Sun\, 27 Aug 2017 17&#8203;:10&#8203;:40 \-0700\, tonyc wrote&#8203;:
> > On Sun\, 27 Aug 2017 01&#8203;:10&#8203;:04 \-0700\, imdb95@&#8203;gmail\.com wrote&#8203;:
> > > Greetings\,
> > > Have you take a look at fixing this bug please?
> >
> > I expect to take a close look at it tomorrow \(or maybe later today\)\.
> >
> > Just from the backtrace it doesn't appear to be a security issue\, but
> > I won't be sure of that until I take that close look\.
> 
> This requires feeding code to the parser and isn't a security issue\.
> 
> scan\_formline\(\) is being entered with PL\_bufptr == PL\_bufend\+1 and
> things go downhill from there\.
> 
> I haven't tracked down exactly why that's happening though\.

This looks like it was fixed by 817480137a8b1165315f21d14b8968862101c3a2\.

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

On Sun\, 20 Jan 2019 19&#8203;:31&#8203;:32 \-0800\, tonyc wrote&#8203;:
> On Mon\, 28 Aug 2017 18&#8203;:42&#8203;:02 \-0700\, tonyc wrote&#8203;:
> > On Sun\, 27 Aug 2017 17&#8203;:10&#8203;:40 \-0700\, tonyc wrote&#8203;:
> > > On Sun\, 27 Aug 2017 01&#8203;:10&#8203;:04 \-0700\, imdb95@&#8203;gmail\.com wrote&#8203;:
> > > > Greetings\,
> > > > Have you take a look at fixing this bug please?
> > >
> > > I expect to take a close look at it tomorrow \(or maybe later today\)\.
> > >
> > > Just from the backtrace it doesn't appear to be a security issue\, but
> > > I won't be sure of that until I take that close look\.
> > 
> > This requires feeding code to the parser and isn't a security issue\.
> > 
> > scan\_formline\(\) is being entered with PL\_bufptr == PL\_bufend\+1 and
> > things go downhill from there\.
> > 
> > I haven't tracked down exactly why that's happening though\.
> 
> This looks like it was fixed by 817480137a8b1165315f21d14b8968862101c3a2\.

So closing\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.30\.0\, this and 160 other issues have been
resolved\.

Perl 5\.30\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.30.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
