### ISSUE TITLE
Null pointer dereference in Perl_sv_setpvn()

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16133]
Migrated from [rt.perl.org#132001](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132001) (status was 'rejected')

Searchable as RT132001$

**Comment by p5pRT** [comment]
### From fumfi.255@gmail.com

After some fuzz testing I found a crashing test case\.

perl \-v output&#8203;: This is perl 5\, version 27\, subversion 4 \(v5\.27\.4
\(v5\.27\.3\-15\-ga0fd450\)\) built for x86\_64\-linux

Faulting test case in attachment\.

Command&#8203;: perl perl\_nullptr\_Perl\_sv\_setpvn

ASAN Context&#8203;:

==19717==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000000
\(pc 0x0000004c692a bp 0x7ffc1268bd90 sp 0x7ffc1268b540 T0\)
==19717==The signal is caused by a READ memory access\.
==19717==Hint&#8203;: address points to the zero page\.
&nbsp;    \#0 0x4c6929 in AddressIsPoisoned
/scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-rt/lib/asan/asan\_mapping\.h&#8203;:322&#8203;:29
&nbsp;    \#1 0x4c6929 in QuickCheckForUnpoisonedRegion
/scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-rt/lib/asan/asan\_interceptors\.cc&#8203;:43
&nbsp;    \#2 0x4c6929 in \_\_asan\_memmove
/scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-rt/lib/asan/asan\_interceptors\.cc&#8203;:461
&nbsp;    \#3 0x96fcf3 in Perl\_sv\_setpvn XYZ/perl/sv\.c&#8203;:5001&#8203;:5
&nbsp;    \#4 0x9beff4 in Perl\_newSVpvn\_flags XYZ/perl/sv\.c&#8203;:9302&#8203;:5
&nbsp;    \#5 0xd11801 in S\_unpack\_rec XYZ/perl/pp\_pack\.c&#8203;:1627&#8203;:3
&nbsp;    \#6 0xd0bd11 in Perl\_unpackstring XYZ/perl/pp\_pack\.c&#8203;:838&#8203;:12
&nbsp;    \#7 0xd26662 in Perl\_pp\_unpack XYZ/perl/pp\_pack\.c&#8203;:1848&#8203;:11
&nbsp;    \#8 0x83945c in Perl\_runops\_debug XYZ/perl/dump\.c&#8203;:2486&#8203;:23
&nbsp;    \#9 0x5e0120 in S\_run\_body XYZ/perl/perl\.c
&nbsp;    \#10 0x5e0120 in perl\_run XYZ/perl/perl\.c&#8203;:2484
&nbsp;    \#11 0x509498 in main XYZ/perl/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#12 0x7f3f0faf082f in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2082f\)
&nbsp;    \#13 0x4359c8 in \_start \(XYZ/perl/perl\+0x4359c8\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV
/scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-rt/lib/asan/asan\_mapping\.h&#8203;:322&#8203;:29
in AddressIsPoisoned
==19717==ABORTING

Pozdrawiam / Best Regards
Kamil Frankowicz

**Comment by p5pRT** [comment]
### From fumfi.255@gmail.com

[perl_nullptr_Perl_sv_setpvn](https://rt-archive.perl.org/perl5/Ticket/Attachment/1486169/801604/perl_nullptr_Perl_sv_setpvn)

**Comment by p5pRT** [comment]
### From @atoomic

To save some time to readers\, the test case from attachment is the following

$$\_=0;$0=unpack'@&#8203;'|'0'&~\*0

On Thu\, 31 Aug 2017 00&#8203;:32&#8203;:54 \-0700\, fumfi\.255@&#8203;gmail\.com wrote&#8203;:
> After some fuzz testing I found a crashing test case\.
> 
> perl \-v output&#8203;: This is perl 5\, version 27\, subversion 4 \(v5\.27\.4
> \(v5\.27\.3\-15\-ga0fd450\)\) built for x86\_64\-linux
> 
> Faulting test case in attachment\.
> 
> Command&#8203;: perl perl\_nullptr\_Perl\_sv\_setpvn
> 
> ASAN Context&#8203;:
> 
> ==19717==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address
> 0x000000000000
> \(pc 0x0000004c692a bp 0x7ffc1268bd90 sp 0x7ffc1268b540 T0\)
> ==19717==The signal is caused by a READ memory access\.
> ==19717==Hint&#8203;: address points to the zero page\.
>     \#0 0x4c6929 in AddressIsPoisoned
> /scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-
> rt/lib/asan/asan\_mapping\.h&#8203;:322&#8203;:29
>     \#1 0x4c6929 in QuickCheckForUnpoisonedRegion
> /scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-
> rt/lib/asan/asan\_interceptors\.cc&#8203;:43
>     \#2 0x4c6929 in \_\_asan\_memmove
> /scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-
> rt/lib/asan/asan\_interceptors\.cc&#8203;:461
>     \#3 0x96fcf3 in Perl\_sv\_setpvn XYZ/perl/sv\.c&#8203;:5001&#8203;:5
>     \#4 0x9beff4 in Perl\_newSVpvn\_flags XYZ/perl/sv\.c&#8203;:9302&#8203;:5
>     \#5 0xd11801 in S\_unpack\_rec XYZ/perl/pp\_pack\.c&#8203;:1627&#8203;:3
>     \#6 0xd0bd11 in Perl\_unpackstring XYZ/perl/pp\_pack\.c&#8203;:838&#8203;:12
>     \#7 0xd26662 in Perl\_pp\_unpack XYZ/perl/pp\_pack\.c&#8203;:1848&#8203;:11
>     \#8 0x83945c in Perl\_runops\_debug XYZ/perl/dump\.c&#8203;:2486&#8203;:23
>     \#9 0x5e0120 in S\_run\_body XYZ/perl/perl\.c
>     \#10 0x5e0120 in perl\_run XYZ/perl/perl\.c&#8203;:2484
>     \#11 0x509498 in main XYZ/perl/perlmain\.c&#8203;:123&#8203;:9
>     \#12 0x7f3f0faf082f in \_\_libc\_start\_main
> \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2082f\)
>     \#13 0x4359c8 in \_start \(XYZ/perl/perl\+0x4359c8\)
> 
> AddressSanitizer can not provide additional info\.
> SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV
> /scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-
> rt/lib/asan/asan\_mapping\.h&#8203;:322&#8203;:29
> in AddressIsPoisoned
> ==19717==ABORTING
> 
> Pozdrawiam / Best Regards
> Kamil Frankowicz

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @atoomic

need more investigation\, seems this is happening in S\_unpack\_rec when calling SHIFT\_VAR
needs\_swap and utf8 are both false

&nbsp;   │1624                    char \*aptr;                                                                                               
&nbsp;   │1625                    SHIFT\_VAR\(utf8\, s\, strend\, aptr\, datumtype\, needs\_swap\);
&nbsp;   │1626                    /\* newSVpvn generates undef if aptr is NULL \*/
&nbsp;  >│1627                    PUSHs\(newSVpvn\_flags\(aptr\, len\, SVs\_TEMP\)\);

backtrace run

Program received signal SIGBUS\, Bus error\.
0x00007ffff6d2f55e in \_\_memmove\_sse2 \(dest=\<optimized out>\, src=\<optimized out>\, len=\<optimized out>\) at \.\./string/memmove\.c&#8203;:85
85          BYTE\_COPY\_FWD \(dstp\, srcp\, len\);
\(gdb\) bt
\#0  0x00007ffff6d2f55e in \_\_memmove\_sse2 \(dest=\<optimized out>\, src=\<optimized out>\, len=\<optimized out>\) at \.\./string/memmove\.c&#8203;:85
\#1  0x0000000000532d6a in Perl\_sv\_setpvn \(sv=0x89cd90\, ptr=0x302852414c414353 \<Address 0x302852414c414353 out of bounds>\, len=1\) at sv\.c&#8203;:5001
\#2  0x000000000053c465 in Perl\_newSVpvn\_flags \(s=0x302852414c414353 \<Address 0x302852414c414353 out of bounds>\, len=1\, flags=524288\) at sv\.c&#8203;:9302
\#3  0x00000000005e705e in S\_unpack\_rec \(symptr=0x7fffffffd9f0\, s=0x89f672 "x881190\)"\, strbeg=0x89f66a "SCALAR\(0x881190\)"\, strend=0x89f67a ""\, new\_s=0x0\) at pp\_pack\.c&#8203;:1627
\#4  0x00000000005e3a94 in Perl\_unpackstring \(pat=0x897610 "P"\, patend=0x897611 ""\, s=0x89f66a "SCALAR\(0x881190\)"\, strend=0x89f67a ""\, flags=16\) at pp\_pack\.c&#8203;:838
\#5  0x00000000005e7f15 in Perl\_pp\_unpack \(\) at pp\_pack\.c&#8203;:1848
\#6  0x000000000051524c in Perl\_runops\_standard \(\) at run\.c&#8203;:41
\#7  0x000000000044c6c0 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2561
\#8  0x000000000044c261 in perl\_run \(my\_perl=0x87f010\) at perl\.c&#8203;:2484
\#9  0x000000000041f255 in main \(argc=2\, argv=0x7fffffffdd98\, env=0x7fffffffddb0\) at perlmain\.c&#8203;:123


On Thu\, 31 Aug 2017 00&#8203;:32&#8203;:54 \-0700\, fumfi\.255@&#8203;gmail\.com wrote&#8203;:
> After some fuzz testing I found a crashing test case\.
> 
> perl \-v output&#8203;: This is perl 5\, version 27\, subversion 4 \(v5\.27\.4
> \(v5\.27\.3\-15\-ga0fd450\)\) built for x86\_64\-linux
> 
> Faulting test case in attachment\.
> 
> Command&#8203;: perl perl\_nullptr\_Perl\_sv\_setpvn
> 
> ASAN Context&#8203;:
> 
> ==19717==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address
> 0x000000000000
> \(pc 0x0000004c692a bp 0x7ffc1268bd90 sp 0x7ffc1268b540 T0\)
> ==19717==The signal is caused by a READ memory access\.
> ==19717==Hint&#8203;: address points to the zero page\.
>     \#0 0x4c6929 in AddressIsPoisoned
> /scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-
> rt/lib/asan/asan\_mapping\.h&#8203;:322&#8203;:29
>     \#1 0x4c6929 in QuickCheckForUnpoisonedRegion
> /scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-
> rt/lib/asan/asan\_interceptors\.cc&#8203;:43
>     \#2 0x4c6929 in \_\_asan\_memmove
> /scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-
> rt/lib/asan/asan\_interceptors\.cc&#8203;:461
>     \#3 0x96fcf3 in Perl\_sv\_setpvn XYZ/perl/sv\.c&#8203;:5001&#8203;:5
>     \#4 0x9beff4 in Perl\_newSVpvn\_flags XYZ/perl/sv\.c&#8203;:9302&#8203;:5
>     \#5 0xd11801 in S\_unpack\_rec XYZ/perl/pp\_pack\.c&#8203;:1627&#8203;:3
>     \#6 0xd0bd11 in Perl\_unpackstring XYZ/perl/pp\_pack\.c&#8203;:838&#8203;:12
>     \#7 0xd26662 in Perl\_pp\_unpack XYZ/perl/pp\_pack\.c&#8203;:1848&#8203;:11
>     \#8 0x83945c in Perl\_runops\_debug XYZ/perl/dump\.c&#8203;:2486&#8203;:23
>     \#9 0x5e0120 in S\_run\_body XYZ/perl/perl\.c
>     \#10 0x5e0120 in perl\_run XYZ/perl/perl\.c&#8203;:2484
>     \#11 0x509498 in main XYZ/perl/perlmain\.c&#8203;:123&#8203;:9
>     \#12 0x7f3f0faf082f in \_\_libc\_start\_main
> \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2082f\)
>     \#13 0x4359c8 in \_start \(XYZ/perl/perl\+0x4359c8\)
> 
> AddressSanitizer can not provide additional info\.
> SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV
> /scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-
> rt/lib/asan/asan\_mapping\.h&#8203;:322&#8203;:29
> in AddressIsPoisoned
> ==19717==ABORTING
> 
> Pozdrawiam / Best Regards
> Kamil Frankowicz

**Comment by p5pRT** [comment]
### From @tonycoz

On Fri\, 01 Sep 2017 12&#8203;:53&#8203;:02 \-0700\, atoomic wrote&#8203;:
> To save some time to readers\, the test case from attachment is the following
> 
> $$\_=0;$0=unpack'@&#8203;'|'0'&~\*0

The 

&nbsp;  '@&#8203;'|'0'&~\*0

expression evaluates to

&nbsp;  'P'

so the program is equivalent to&#8203;:

&nbsp;  $$\_=0; $0=unpack"P"

The $$\_ = 0 auto\-vivifies $\_ into a scalar reference\, so the unpack behaves like&#8203;:

&nbsp;  $0 = unpack "P"\, "SCALAR\(0x\.\.\.\)";

The P template for pack reads a pointer from the supplied scalar\, so treating the bytes "SCAL" or "SCALAR\(0" as a pointer\, which very reasonably crashes\.

This isn't a bug\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'rejected'

**Comment by p5pRT** [comment]
### From @demerphq

I agree it's not a bug but the P format is arguably a security concern\.
Maybe P should only be available under a pragma specifying it is legal \(and
thus that the programmer understands they get to keep both pieces if it
blows up in their face\)\.

Yves

On 4 Sep 2017 04&#8203;:30\, "Tony Cook via RT" \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

> On Fri\, 01 Sep 2017 12&#8203;:53&#8203;:02 \-0700\, atoomic wrote&#8203;:
> > To save some time to readers\, the test case from attachment is the
> following
> >
> > $$\_=0;$0=unpack'@&#8203;'|'0'&~\*0
>
> The
>
>   '@&#8203;'|'0'&~\*0
>
> expression evaluates to
>
>   'P'
>
> so the program is equivalent to&#8203;:
>
>   $$\_=0; $0=unpack"P"
>
> The $$\_ = 0 auto\-vivifies $\_ into a scalar reference\, so the unpack
> behaves like&#8203;:
>
>   $0 = unpack "P"\, "SCALAR\(0x\.\.\.\)";
>
> The P template for pack reads a pointer from the supplied scalar\, so
> treating the bytes "SCAL" or "SCALAR\(0" as a pointer\, which very reasonably
> crashes\.
>
> This isn't a bug\.
>
> Tony
>
> \-\-\-
> via perlbug&#8203;:  queue&#8203;: perl5 status&#8203;: open
> https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132001
>

**Comment by p5pRT** [comment]
### From @xsawyerx

Before we evaluate such an option\, it would be good to have a cursory
check of CPAN\.

On 09/04/2017 12&#8203;:18 PM\, demerphq wrote&#8203;:
> I agree it's not a bug but the P format is arguably a security
> concern\. Maybe P should only be available under a pragma specifying it
> is legal \(and thus that the programmer understands they get to keep
> both pieces if it blows up in their face\)\.
>
> Yves
>
> On 4 Sep 2017 04&#8203;:30\, "Tony Cook via RT" \<perlbug\-followup@&#8203;perl\.org
> \<mailto&#8203;:perlbug\-followup@&#8203;perl\.org>> wrote&#8203;:
>
>     On Fri\, 01 Sep 2017 12&#8203;:53&#8203;:02 \-0700\, atoomic wrote&#8203;:
>     > To save some time to readers\, the test case from attachment is
>     the following
>     >
>     > $$\_=0;$0=unpack'@&#8203;'|'0'&~\*0
>
>     The
>
>       '@&#8203;'|'0'&~\*0
>
>     expression evaluates to
>
>       'P'
>
>     so the program is equivalent to&#8203;:
>
>       $$\_=0; $0=unpack"P"
>
>     The $$\_ = 0 auto\-vivifies $\_ into a scalar reference\, so the
>     unpack behaves like&#8203;:
>
>       $0 = unpack "P"\, "SCALAR\(0x\.\.\.\)";
>
>     The P template for pack reads a pointer from the supplied scalar\,
>     so treating the bytes "SCAL" or "SCALAR\(0" as a pointer\, which
>     very reasonably crashes\.
>
>     This isn't a bug\.
>
>     Tony
>
>     \-\-\-
>     via perlbug&#8203;:  queue&#8203;: perl5 status&#8203;: open
>     https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132001
>     \<https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132001>
>

**Comment by p5pRT** [comment]
### From @khwilliamson

On 09/05/2017 07&#8203;:01 AM\, Sawyer X wrote&#8203;:
> Before we evaluate such an option\, it would be good to have a cursory
> check of CPAN\.

Since grep\.cpan\.me has been down for some time\, such a check is 
currently impossible\.
> 
> On 09/04/2017 12&#8203;:18 PM\, demerphq wrote&#8203;:
>> I agree it's not a bug but the P format is arguably a security
>> concern\. Maybe P should only be available under a pragma specifying it
>> is legal \(and thus that the programmer understands they get to keep
>> both pieces if it blows up in their face\)\.
>>
>> Yves
>>
>> On 4 Sep 2017 04&#8203;:30\, "Tony Cook via RT" \<perlbug\-followup@&#8203;perl\.org
>> \<mailto&#8203;:perlbug\-followup@&#8203;perl\.org>> wrote&#8203;:
>>
>>      On Fri\, 01 Sep 2017 12&#8203;:53&#8203;:02 \-0700\, atoomic wrote&#8203;:
>>      > To save some time to readers\, the test case from attachment is
>>      the following
>>      >
>>      > $$\_=0;$0=unpack'@&#8203;'|'0'&~\*0
>>
>>      The
>>
>>        '@&#8203;'|'0'&~\*0
>>
>>      expression evaluates to
>>
>>        'P'
>>
>>      so the program is equivalent to&#8203;:
>>
>>        $$\_=0; $0=unpack"P"
>>
>>      The $$\_ = 0 auto\-vivifies $\_ into a scalar reference\, so the
>>      unpack behaves like&#8203;:
>>
>>        $0 = unpack "P"\, "SCALAR\(0x\.\.\.\)";
>>
>>      The P template for pack reads a pointer from the supplied scalar\,
>>      so treating the bytes "SCAL" or "SCALAR\(0" as a pointer\, which
>>      very reasonably crashes\.
>>
>>      This isn't a bug\.
>>
>>      Tony
>>
>>      \-\-\-
>>      via perlbug&#8203;:  queue&#8203;: perl5 status&#8203;: open
>>      https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132001
>>      \<https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132001>
>>
>

**Comment by p5pRT** [comment]
### From @xsawyerx

grep\.metacpan\.org

On 09/05/2017 05&#8203;:57 PM\, Karl Williamson wrote&#8203;:
> On 09/05/2017 07&#8203;:01 AM\, Sawyer X wrote&#8203;:
>> Before we evaluate such an option\, it would be good to have a cursory
>> check of CPAN\.
>
> Since grep\.cpan\.me has been down for some time\, such a check is
> currently impossible\.
>>
>> On 09/04/2017 12&#8203;:18 PM\, demerphq wrote&#8203;:
>>> I agree it's not a bug but the P format is arguably a security
>>> concern\. Maybe P should only be available under a pragma specifying it
>>> is legal \(and thus that the programmer understands they get to keep
>>> both pieces if it blows up in their face\)\.
>>>
>>> Yves
>>>
>>> On 4 Sep 2017 04&#8203;:30\, "Tony Cook via RT" \<perlbug\-followup@&#8203;perl\.org
>>> \<mailto&#8203;:perlbug\-followup@&#8203;perl\.org>> wrote&#8203;:
>>>
>>>      On Fri\, 01 Sep 2017 12&#8203;:53&#8203;:02 \-0700\, atoomic wrote&#8203;:
>>>      > To save some time to readers\, the test case from attachment is
>>>      the following
>>>      >
>>>      > $$\_=0;$0=unpack'@&#8203;'|'0'&~\*0
>>>
>>>      The
>>>
>>>        '@&#8203;'|'0'&~\*0
>>>
>>>      expression evaluates to
>>>
>>>        'P'
>>>
>>>      so the program is equivalent to&#8203;:
>>>
>>>        $$\_=0; $0=unpack"P"
>>>
>>>      The $$\_ = 0 auto\-vivifies $\_ into a scalar reference\, so the
>>>      unpack behaves like&#8203;:
>>>
>>>        $0 = unpack "P"\, "SCALAR\(0x\.\.\.\)";
>>>
>>>      The P template for pack reads a pointer from the supplied scalar\,
>>>      so treating the bytes "SCAL" or "SCALAR\(0" as a pointer\, which
>>>      very reasonably crashes\.
>>>
>>>      This isn't a bug\.
>>>
>>>      Tony
>>>
>>>      \-\-\-
>>>      via perlbug&#8203;:  queue&#8203;: perl5 status&#8203;: open
>>>      https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132001
>>>      \<https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132001>
>>>
>>
>

**Comment by p5pRT** [comment]
### From @ilmari

Karl Williamson \<public@&#8203;khwilliamson\.com> writes&#8203;:

> On 09/05/2017 07&#8203;:01 AM\, Sawyer X wrote&#8203;:
>> Before we evaluate such an option\, it would be good to have a cursory
>> check of CPAN\.
>
> Since grep\.cpan\.me has been down for some time\, such a check is
> currently impossible\.

However\, https://grep.metacpan.org/ is up and running\, and gives 44
distributions \(some of which are false positives\)&#8203;:

https://grep.metacpan.org/search?q=\bunpack\s*\(%3F\s*\S%2BP&qd=&qft=

>> On 09/04/2017 12&#8203;:18 PM\, demerphq wrote&#8203;:
>>> I agree it's not a bug but the P format is arguably a security
>>> concern\. Maybe P should only be available under a pragma specifying it
>>> is legal \(and thus that the programmer understands they get to keep
>>> both pieces if it blows up in their face\)\.
>>>
>>> Yves
>>>
>>> On 4 Sep 2017 04&#8203;:30\, "Tony Cook via RT" \<perlbug\-followup@&#8203;perl\.org
>>> \<mailto&#8203;:perlbug\-followup@&#8203;perl\.org>> wrote&#8203;:
>>>
>>>      On Fri\, 01 Sep 2017 12&#8203;:53&#8203;:02 \-0700\, atoomic wrote&#8203;:
>>>      > To save some time to readers\, the test case from attachment is
>>>      the following
>>>      >
>>>      > $$\_=0;$0=unpack'@&#8203;'|'0'&~\*0
>>>
>>>      The
>>>
>>>        '@&#8203;'|'0'&~\*0
>>>
>>>      expression evaluates to
>>>
>>>        'P'
>>>
>>>      so the program is equivalent to&#8203;:
>>>
>>>        $$\_=0; $0=unpack"P"
>>>
>>>      The $$\_ = 0 auto\-vivifies $\_ into a scalar reference\, so the
>>>      unpack behaves like&#8203;:
>>>
>>>        $0 = unpack "P"\, "SCALAR\(0x\.\.\.\)";
>>>
>>>      The P template for pack reads a pointer from the supplied scalar\,
>>>      so treating the bytes "SCAL" or "SCALAR\(0" as a pointer\, which
>>>      very reasonably crashes\.
>>>
>>>      This isn't a bug\.
>>>
>>>      Tony
>>>
>>>      \-\-\-
>>>      via perlbug&#8203;:  queue&#8203;: perl5 status&#8203;: open
>>>      https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132001
>>>      \<https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132001>
>>>
>>
>

\-\- 
\- Twitter seems more influential \[than blogs\] in the 'gets reported in
&nbsp;  the mainstream press' sense at least\.               \- Matt McLeod
\- That'd be because the content of a tweet is easier to condense down
&nbsp;  to a mainstream media article\.                      \- Calle Dybedahl
