### ISSUE TITLE
heap-buffer-overflow (READ: 2) in sdbm_getnkey()

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16166]
Migrated from [rt.perl.org#132151](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132151) (status was 'resolved')

Searchable as RT132151$

**Comment by p5pRT** [comment]
### From CYoung@tripwire.com

I have found another interesting testcase related to SDBM handling in Perl5\.  The following is a base64 encoding of a crafted file\, demo\.dbm\.pag&#8203;:
AiD/A/4DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5AAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAGZo

When this is base64 decoded into the \.pag file and an empty demo\.dbm\.dir file is created\, run the following perl script in an ASAN instrumented perl binary&#8203;:
\#\!/usr/bin/perl
use warnings;
use strict;
use POSIX;
use SDBM\_File;

my %dbm;
my $db\_file="demo\.dbm";

tie %dbm\, 'SDBM\_File'\, $db\_file\, O\_RDWR\, 0;

foreach \(sort keys\(%dbm\)\) \{
&nbsp;             print "$\_ => $dbm\{$\_\}\\n";
\}

Here is the ASAN output I receive indicating a heap\-buffer\-overflow \(READ&#8203;: 2\) in sdbm\_getnkey\(\) :
=================================================================
==2839==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address 0x62200001ad50 at pc 0x7fdd9508e8da bp 0x7ffe207f5e00 sp 0x7ffe207f5df8
READ of size 2 at 0x62200001ad50 thread T0
&nbsp;    \#0 0x7fdd9508e8d9 in sdbm\_\_getnkey /home/cyoung/perl/build/perl5\-5\.26\.1/ext/SDBM\_File/pair\.c&#8203;:140&#8203;:20
&nbsp;    \#1 0x7fdd9509257d in getnext /home/cyoung/perl/build/perl5\-5\.26\.1/ext/SDBM\_File/sdbm\.c&#8203;:537&#8203;:9
&nbsp;    \#2 0x7fdd95092863 in sdbm\_nextkey /home/cyoung/perl/build/perl5\-5\.26\.1/ext/SDBM\_File/sdbm\.c&#8203;:419&#8203;:9
&nbsp;    \#3 0x7fdd9508a48c in XS\_SDBM\_File\_NEXTKEY /home/cyoung/perl/build/perl5\-5\.26\.1/ext/SDBM\_File/SDBM\_File\.c&#8203;:508&#8203;:11
&nbsp;    \#4 0x945828 in Perl\_pp\_entersub /home/cyoung/perl/build/perl5\-5\.26\.1/pp\_hot\.c&#8203;:4231&#8203;:2
&nbsp;    \#5 0x84cebc in Perl\_runops\_debug /home/cyoung/perl/build/perl5\-5\.26\.1/dump\.c&#8203;:2451&#8203;:23
&nbsp;    \#6 0x5c8eaa in Perl\_call\_sv /home/cyoung/perl/build/perl5\-5\.26\.1/perl\.c&#8203;:2831&#8203;:2
&nbsp;    \#7 0x89012b in Perl\_magic\_methcall /home/cyoung/perl/build/perl5\-5\.26\.1/mg\.c&#8203;:1839&#8203;:6
&nbsp;    \#8 0x8925ec in Perl\_magic\_nextpack /home/cyoung/perl/build/perl5\-5\.26\.1/mg\.c&#8203;:1974&#8203;:23
&nbsp;    \#9 0x8e35d4 in Perl\_hv\_iternext\_flags /home/cyoung/perl/build/perl5\-5\.26\.1/hv\.c&#8203;:2627&#8203;:13
&nbsp;    \#10 0xbaaef2 in Perl\_do\_kv /home/cyoung/perl/build/perl5\-5\.26\.1/doop\.c&#8203;:1325&#8203;:21
&nbsp;    \#11 0x84cebc in Perl\_runops\_debug /home/cyoung/perl/build/perl5\-5\.26\.1/dump\.c&#8203;:2451&#8203;:23
&nbsp;    \#12 0x5c6605 in S\_run\_body /home/cyoung/perl/build/perl5\-5\.26\.1/perl\.c&#8203;:2524&#8203;:2
&nbsp;    \#13 0x5c6605 in perl\_run /home/cyoung/perl/build/perl5\-5\.26\.1/perl\.c&#8203;:2447
&nbsp;    \#14 0x4f8094 in main /home/cyoung/perl/build/perl5\-5\.26\.1/perlmain\.c&#8203;:123&#8203;:9
&nbsp;    \#15 0x7fdd983f382f in \_\_libc\_start\_main \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2082f\)
&nbsp;    \#16 0x451a78 in \_start \(/usr/local/bin/perl5\.26\.1\+0x451a78\)

0x62200001ad50 is located 0 bytes to the right of 5200\-byte region \[0x622000019900\,0x62200001ad50\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4d8a42 in malloc \(/usr/local/bin/perl5\.26\.1\+0x4d8a42\)
&nbsp;    \#1 0x7fdd95090073 in sdbm\_prep /home/cyoung/perl/build/perl5\-5\.26\.1/ext/SDBM\_File/sdbm\.c&#8203;:123&#8203;:20
&nbsp;    \#2 0x7fdd9508fe98 in sdbm\_open /home/cyoung/perl/build/perl5\-5\.26\.1/ext/SDBM\_File/sdbm\.c&#8203;:112&#8203;:7

SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow /home/cyoung/perl/build/perl5\-5\.26\.1/ext/SDBM\_File/pair\.c&#8203;:140 sdbm\_\_getnkey
Shadow bytes around the buggy address&#8203;:
&nbsp;  0x0c447fffb550&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 0x0c447fffb560&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c447fffb570&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c447fffb580&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c447fffb590&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c447fffb5a0&#8203;: 00 00 00 00 00 00 00 00 00 00\[fa\]fa fa fa fa fa
&nbsp;  0x0c447fffb5b0&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c447fffb5c0&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c447fffb5d0&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c447fffb5e0&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c447fffb5f0&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend \(one shadow byte represents 8 application bytes\)&#8203;:
&nbsp;  Addressable&#8203;:           00
&nbsp;  Partially addressable&#8203;: 01 02 03 04 05 06 07
&nbsp;  Heap left redzone&#8203;:       fa
&nbsp;  Heap right redzone&#8203;:      fb
&nbsp;  Freed heap region&#8203;:       fd
&nbsp;  Stack left redzone&#8203;:      f1
&nbsp;  Stack mid redzone&#8203;:       f2
&nbsp;  Stack right redzone&#8203;:     f3
&nbsp;  Stack partial redzone&#8203;:   f4
&nbsp;  Stack after return&#8203;:      f5
&nbsp;  Stack use after scope&#8203;:   f8
&nbsp;  Global redzone&#8203;:          f9
&nbsp;  Global init order&#8203;:       f6
&nbsp;  Poisoned by user&#8203;:        f7
&nbsp;  Container overflow&#8203;:      fc
&nbsp;  Array cookie&#8203;:            ac
&nbsp;  Intra object redzone&#8203;:    bb
&nbsp;  ASan internal&#8203;:           fe
&nbsp;  Left alloca redzone&#8203;:     ca
&nbsp;  Right alloca redzone&#8203;:    cb
==2839==ABORTING

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
Craig Young | Security Researcher
Direct&#8203;: 404\-492\-9657
TRIPWIRE | CONFIDENCE&#8203;: SECURED
www\.tripwire\.com\<http&#8203;://www\.tripwire\.com/>

**Comment by p5pRT** [comment]
### From @tonycoz

On Sat\, 23 Sep 2017 12&#8203;:53&#8203;:55 \-0700\, CYoung@&#8203;tripwire\.com wrote&#8203;:
> I have found another interesting testcase related to SDBM handling in
> Perl5\.  The following is a base64 encoding of a crafted file\,
> demo\.dbm\.pag&#8203;:
\.\.\.
> Here is the ASAN output I receive indicating a heap\-buffer\-overflow
> \(READ&#8203;: 2\) in sdbm\_getnkey\(\) :
> =================================================================
> ==2839==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
> 0x62200001ad50 at pc 0x7fdd9508e8da bp 0x7ffe207f5e00 sp
> 0x7ffe207f5df8
> READ of size 2 at 0x62200001ad50 thread T0
>     \#0 0x7fdd9508e8d9 in sdbm\_\_getnkey /home/cyoung/perl/build/perl5\-
> 5\.26\.1/ext/SDBM\_File/pair\.c&#8203;:140&#8203;:20
>     \#1 0x7fdd9509257d in getnext /home/cyoung/perl/build/perl5\-
> 5\.26\.1/ext/SDBM\_File/sdbm\.c&#8203;:537&#8203;:9
>     \#2 0x7fdd95092863 in sdbm\_nextkey /home/cyoung/perl/build/perl5\-
> 5\.26\.1/ext/SDBM\_File/sdbm\.c&#8203;:419&#8203;:9
>     \#3 0x7fdd9508a48c in XS\_SDBM\_File\_NEXTKEY
> /home/cyoung/perl/build/perl5\-5\.26\.1/ext/SDBM\_File/SDBM\_File\.c&#8203;:508&#8203;:11

Fixed by the 7d5be4b67af37e3a46105aeafc0c7871322bdc7d merge\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.30\.0\, this and 160 other issues have been
resolved\.

Perl 5\.30\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.30.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
