### ISSUE TITLE
signed integer overflow in S_study_chunk (regcomp.c:5444)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16173]
Migrated from [rt.perl.org#132164](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132164) (status was 'resolved')

Searchable as RT132164$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered while fuzzing v5\.27\.4\-28\-g60dfa51

\./perl \-e 'm m0\*0\+\\Rm'

regcomp\.c&#8203;:5444&#8203;:26&#8203;: runtime error&#8203;: signed integer overflow&#8203;:
9223372036854775807 \+ 1 cannot be represented in type 'long'
&nbsp;    \#0 0xc36484 in S\_study\_chunk /root/perl/regcomp\.c&#8203;:5444&#8203;:26
&nbsp;    \#1 0xb7c063 in Perl\_re\_op\_compile /root/perl/regcomp\.c&#8203;:7574&#8203;:11
&nbsp;    \#2 0x567839 in Perl\_pmruntime /root/perl/op\.c&#8203;:5888&#8203;:6
&nbsp;    \#3 0xaf495b in Perl\_yyparse /root/perl/perly\.y&#8203;:1210&#8203;:23
&nbsp;    \#4 0x7289f7 in S\_parse\_body /root/perl/perl\.c&#8203;:2450&#8203;:9
&nbsp;    \#5 0x714363 in perl\_parse /root/perl/perl\.c&#8203;:1753&#8203;:2
&nbsp;    \#6 0x50af99 in main /root/perl/perlmain\.c&#8203;:121&#8203;:18
&nbsp;    \#7 0x7fd350558b44 in \_\_libc\_start\_main
/build/glibc\-6V9RKT/glibc\-2\.19/csu/libc\-start\.c&#8203;:287
&nbsp;    \#8 0x43c01b in \_start \(/root/perl/perl\+0x43c01b\)

SUMMARY&#8203;: UndefinedBehaviorSanitizer&#8203;: undefined\-behavior regcomp\.c&#8203;:5444&#8203;:26

**Comment by p5pRT** [comment]
### From @geeknik

Whoops\, that should be "signed" not unsigned\.

**Comment by p5pRT** [comment]
### From @khwilliamson

On Mon\, 25 Sep 2017 23&#8203;:19&#8203;:46 \-0700\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> Whoops\, that should be "signed" not unsigned\.

The attached patch fixes this\, and seems reasonable\.  The value is getting initialized to effective infinity\, and then incremented\.  Just above\, there is a special case to not incrment infinity\, and it seems proper to do the same thing here\.

But since I don't understand study\_chunk\(\)\, I won't apply the patch until the middle of April\, to give people a chance to say that it shouldn't be applied\.

\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
### From @khwilliamson

<details><summary>0006-regcomp.c-Don-t-try-to-increment-infinity.patch</summary>

```diff
From 2c03b53a90c951ba9aef715d6b8a0ec91fe55994 Mon Sep 17 00:00:00 2001
From: Karl Williamson <khw@cpan.org>
Date: Sun, 1 Apr 2018 13:58:47 -0600
Subject: [PATCH 6/6] regcomp.c: Don't try to increment infinity

This value can be infinity (which is here SSize_t_MAX).  Leave it there.
---
 regcomp.c | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/regcomp.c b/regcomp.c
index 018d5646fc..47e86933f7 100644
--- a/regcomp.c
+++ b/regcomp.c
@@ -5476,7 +5476,9 @@ Perl_re_printf( aTHX_  "LHS=%" UVuf " RHS=%" UVuf "\n",
                 /* Cannot expect anything... */
                 scan_commit(pRExC_state, data, minlenp, is_inf);
     	        data->pos_min += 1;
-	        data->pos_delta += 1;
+                if (data->pos_delta != SSize_t_MAX) {
+                    data->pos_delta += 1;
+                }
 		data->cur_is_floating = 1; /* float */
     	    }
 	}
-- 
2.11.0


```
</details>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @khwilliamson

Fixed by commit
5e20fb07d2b8373f53f053086ba668649763de9a
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release yesterday of Perl 5\.28\.0\, this and 185 other issues have been
resolved\.

Perl 5\.28\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.28.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
