### ISSUE TITLE
heap-buffer-overflow (READ of size 1) in S_scan_const (toke.c:3060)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16189]
Migrated from [rt.perl.org#132245](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132245) (status was 'resolved')

Searchable as RT132245$

**Comment by p5pRT** [comment]
### From @geeknik

Triggered in 1195d90\. Not a security concern as per Hugo in \#129342 which
was marked resolved for 5\.26\.0\.

\./perl \-e 'y//\\N\{\}\-0/'

==3236==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
0x602000000eef at pc 0x00000069952c bp 0x7ffdf060f1f0 sp 0x7ffdf060f1e8
READ of size 1 at 0x602000000eef thread T0
&nbsp;    \#0 0x69952b in S\_scan\_const /root/perl/toke\.c&#8203;:3060&#8203;:33
&nbsp;    \#1 0x628a3c in Perl\_yylex /root/perl/toke\.c&#8203;:5042&#8203;:10
&nbsp;    \#2 0x6c7943 in Perl\_yyparse /root/perl/perly\.c&#8203;:340&#8203;:34
&nbsp;    \#3 0x5bb75b in S\_parse\_body /root/perl/perl\.c&#8203;:2450&#8203;:9
&nbsp;    \#4 0x5b355a in perl\_parse /root/perl/perl\.c&#8203;:1753&#8203;:2
&nbsp;    \#5 0x505095 in main /root/perl/perlmain\.c&#8203;:121&#8203;:18
&nbsp;    \#6 0x7f176def882f in \_\_libc\_start\_main
/build/glibc\-bfm8X4/glibc\-2\.23/csu/\.\./csu/libc\-start\.c&#8203;:291
&nbsp;    \#7 0x435fa8 in \_start \(/root/perl/perl\+0x435fa8\)

0x602000000eef is located 1 bytes to the left of 10\-byte region
\[0x602000000ef0\,0x602000000efa\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4d9013 in malloc \(/root/perl/perl\+0x4d9013\)
&nbsp;    \#1 0x7ee078 in Perl\_safesysmalloc /root/perl/util\.c&#8203;:153&#8203;:21
&nbsp;    \#2 0x8e000b in Perl\_sv\_grow /root/perl/sv\.c&#8203;:1603&#8203;:17
&nbsp;    \#3 0x923227 in Perl\_newSV /root/perl/sv\.c&#8203;:5691&#8203;:2
&nbsp;    \#4 0x68aa5c in S\_scan\_const /root/perl/toke\.c&#8203;:2877&#8203;:14
&nbsp;    \#5 0x628a3c in Perl\_yylex /root/perl/toke\.c&#8203;:5042&#8203;:10
&nbsp;    \#6 0x6c7943 in Perl\_yyparse /root/perl/perly\.c&#8203;:340&#8203;:34
&nbsp;    \#7 0x5bb75b in S\_parse\_body /root/perl/perl\.c&#8203;:2450&#8203;:9
&nbsp;    \#8 0x5b355a in perl\_parse /root/perl/perl\.c&#8203;:1753&#8203;:2
&nbsp;    \#9 0x505095 in main /root/perl/perlmain\.c&#8203;:121&#8203;:18
&nbsp;    \#10 0x7f176def882f in \_\_libc\_start\_main
/build/glibc\-bfm8X4/glibc\-2\.23/csu/\.\./csu/libc\-start\.c&#8203;:291

SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow /root/perl/toke\.c&#8203;:3060&#8203;:33
in S\_scan\_const



The unminimized version of this testcase results in a slightly different
stack&#8203;:

\./perl \-e 'y/\+4N\{U0220\}/\\N\{\}\-\\N\{U\+400220\}/\\N\{U\+402\<0\}/c\[rp'

==4003==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
0x6030000006cf at pc 0x00000069914d bp 0x7ffc81e758b0 sp 0x7ffc81e758a8
READ of size 1 at 0x6030000006cf thread T0
&nbsp;    \#0 0x69914c in Perl\_utf8\_hop /root/perl/\./inline\.h&#8203;:946&#8203;:13
&nbsp;    \#1 0x69914c in S\_scan\_const /root/perl/toke\.c&#8203;:3047
&nbsp;    \#2 0x628a3c in Perl\_yylex /root/perl/toke\.c&#8203;:5042&#8203;:10
&nbsp;    \#3 0x6c7943 in Perl\_yyparse /root/perl/perly\.c&#8203;:340&#8203;:34
&nbsp;    \#4 0x5bb75b in S\_parse\_body /root/perl/perl\.c&#8203;:2450&#8203;:9
&nbsp;    \#5 0x5b355a in perl\_parse /root/perl/perl\.c&#8203;:1753&#8203;:2
&nbsp;    \#6 0x505095 in main /root/perl/perlmain\.c&#8203;:121&#8203;:18
&nbsp;    \#7 0x7f5d033c782f in \_\_libc\_start\_main
/build/glibc\-bfm8X4/glibc\-2\.23/csu/\.\./csu/libc\-start\.c&#8203;:291
&nbsp;    \#8 0x435fa8 in \_start \(/root/perl/perl\+0x435fa8\)

0x6030000006cf is located 1 bytes to the left of 19\-byte region
\[0x6030000006d0\,0x6030000006e3\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4d9013 in malloc \(/root/perl/perl\+0x4d9013\)
&nbsp;    \#1 0x7ee078 in Perl\_safesysmalloc /root/perl/util\.c&#8203;:153&#8203;:21
&nbsp;    \#2 0x8e000b in Perl\_sv\_grow /root/perl/sv\.c&#8203;:1603&#8203;:17
&nbsp;    \#3 0x923227 in Perl\_newSV /root/perl/sv\.c&#8203;:5691&#8203;:2
&nbsp;    \#4 0x68aa5c in S\_scan\_const /root/perl/toke\.c&#8203;:2877&#8203;:14
&nbsp;    \#5 0x628a3c in Perl\_yylex /root/perl/toke\.c&#8203;:5042&#8203;:10
&nbsp;    \#6 0x6c7943 in Perl\_yyparse /root/perl/perly\.c&#8203;:340&#8203;:34
&nbsp;    \#7 0x5bb75b in S\_parse\_body /root/perl/perl\.c&#8203;:2450&#8203;:9
&nbsp;    \#8 0x5b355a in perl\_parse /root/perl/perl\.c&#8203;:1753&#8203;:2
&nbsp;    \#9 0x505095 in main /root/perl/perlmain\.c&#8203;:121&#8203;:18
&nbsp;    \#10 0x7f5d033c782f in \_\_libc\_start\_main
/build/glibc\-bfm8X4/glibc\-2\.23/csu/\.\./csu/libc\-start\.c&#8203;:291

SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow
/root/perl/\./inline\.h&#8203;:946&#8203;:13 in Perl\_utf8\_hop

**Comment by p5pRT** [comment]
### From @tonycoz

On Sun\, 08 Oct 2017 03&#8203;:41&#8203;:21 \-0700\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> Triggered in 1195d90\. Not a security concern as per Hugo in \#129342 which
> was marked resolved for 5\.26\.0\.
> 
> \./perl \-e 'y//\\N\{\}\-0/'
> 

The first attached patch fixes this for me\.

The second fixes a SV leak in the same area of code\.

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

<details><summary>0001-perl-132245-don-t-try-to-process-a-char-range-with-n.patch</summary>

```diff
From 92ecd10d32742cd35f6ac53c77a6c51b50db0e81 Mon Sep 17 00:00:00 2001
From: Tony Cook <tony@develop-help.com>
Date: Thu, 19 Oct 2017 10:46:04 +1100
Subject: (perl #132245) don't try to process a char range with no preceding
 char

A range like \N{}-0 eventually results in compilation failing, but
before that, get_and_check_backslash_N_name() attempts to treat
the memory before the empty output of \N{} as a character.
---
 t/lib/croak/toke | 6 ++++++
 toke.c           | 6 +++---
 2 files changed, 9 insertions(+), 3 deletions(-)

diff --git a/t/lib/croak/toke b/t/lib/croak/toke
index 87d9580..1a7468f 100644
--- a/t/lib/croak/toke
+++ b/t/lib/croak/toke
@@ -413,3 +413,9 @@ EXPECT
 Illegal operator following parameter in a subroutine signature at - line 3, near "($a += 1"
 syntax error at - line 3, near "($a += 1"
 Execution of - aborted due to compilation errors.
+########
+# NAME tr/// range with empty \N{} at the start
+tr//\N{}-0/;
+EXPECT
+Unknown charname '' at - line 1, within string
+Execution of - aborted due to compilation errors.
diff --git a/toke.c b/toke.c
index 46dba4d..79be40c 100644
--- a/toke.c
+++ b/toke.c
@@ -2969,9 +2969,9 @@ S_scan_const(pTHX_ char *start)
 
                 /* Here, we don't think we're in a range.  If the new character
                  * is not a hyphen; or if it is a hyphen, but it's too close to
-                 * either edge to indicate a range, then it's a regular
-                 * character. */
-                if (*s != '-' || s >= send - 1 || s == start) {
+                 * either edge to indicate a range, or if we haven't output any
+                 * characters yet then it's a regular character. */
+                if (*s != '-' || s >= send - 1 || s == start || d == SvPVX(sv)) {
 
                     /* A regular character.  Process like any other, but first
                      * clear any flags */
-- 
2.1.4


```
</details>

**Comment by p5pRT** [comment]
### From @tonycoz

<details><summary>0002-perl-132245-don-t-leak-on-N.patch</summary>

```diff
From a24241f5473549aee40d36bedbd6a714a81a110f Mon Sep 17 00:00:00 2001
From: Tony Cook <tony@develop-help.com>
Date: Thu, 19 Oct 2017 10:47:22 +1100
Subject: (perl #132245) don't leak on \N{}

get_and_check_backslash_N_name() failed to free its working SV if
the name was empty.
---
 t/op/svleak.t | 7 ++++++-
 toke.c        | 1 +
 2 files changed, 7 insertions(+), 1 deletion(-)

diff --git a/t/op/svleak.t b/t/op/svleak.t
index e4e881d..7226dd8 100644
--- a/t/op/svleak.t
+++ b/t/op/svleak.t
@@ -15,7 +15,7 @@ BEGIN {
 
 use Config;
 
-plan tests => 141;
+plan tests => 142;
 
 # run some code N times. If the number of SVs at the end of loop N is
 # greater than (N-1)*delta at the end of loop 1, we've got a leak
@@ -593,3 +593,8 @@ EOF
     }
     ::leak(2, 0, \&named, "Perl_reg_named_buff_fetch() on no-name RE");
 }
+
+{
+    sub N_leak { eval 'tr//\N{}-0/' }
+    ::leak(2, 0, \&N_leak, "a bad \\N{} in a range leaks");
+}
diff --git a/toke.c b/toke.c
index 79be40c..58a651b 100644
--- a/toke.c
+++ b/toke.c
@@ -2595,6 +2595,7 @@ S_get_and_check_backslash_N_name(pTHX_ const char* s, const char* const e)
     PERL_ARGS_ASSERT_GET_AND_CHECK_BACKSLASH_N_NAME;
 
     if (!SvCUR(res)) {
+        SvREFCNT_dec_NN(res);
         /* diag_listed_as: Unknown charname '%s' */
         yyerror("Unknown charname ''");
         return NULL;
-- 
2.1.4


```
</details>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Wed\, 18 Oct 2017 16&#8203;:55&#8203;:37 \-0700\, tonyc wrote&#8203;:
> On Sun\, 08 Oct 2017 03&#8203;:41&#8203;:21 \-0700\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> > Triggered in 1195d90\. Not a security concern as per Hugo in \#129342 which
> > was marked resolved for 5\.26\.0\.
> > 
> > \./perl \-e 'y//\\N\{\}\-0/'
> > 
> 
> The first attached patch fixes this for me\.
> 
> The second fixes a SV leak in the same area of code\.

Applied as e8d55f27af460b2aea0e4f6867acad7ae6e154cc and ebcc725e3f7e5ec8b898a7035ff5c5e2c230522e\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release yesterday of Perl 5\.28\.0\, this and 185 other issues have been
resolved\.

Perl 5\.28\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.28.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
