### ISSUE TITLE
use-of-uninitialized-value in Perl_upg_version (vutil.c:669)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16186]
Migrated from [rt.perl.org#132234](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132234) (status was 'open')

Searchable as RT132234$

**Comment by p5pRT** [comment]
### From @geeknik

While building 1195d90 with \-fsanitize=memory\, the process fails during the
miniperl build\.

afl\-clang\-fast \[tpcg\] 2\.51b by \<lszekeres@&#8203;google\.com>
\./miniperl \-w \-Ilib \-Idist/Exporter/lib \-MExporter \-e '\<?>' || sh \-c 'echo
>&2 Failed to build miniperl\.  Please run make minitest; exit 1'
==11441==WARNING&#8203;: MemorySanitizer&#8203;: use\-of\-uninitialized\-value
&nbsp;    \#0 0x560a10786ab7 in Perl\_upg\_version /root/perl/\./vutil\.c&#8203;:669&#8203;:2
&nbsp;    \#1 0x560a107839a2 in Perl\_new\_version /root/perl/\./vutil\.c&#8203;:551&#8203;:12
&nbsp;    \#2 0x560a10acb9f4 in S\_require\_version /root/perl/pp\_ctl\.c&#8203;:3663&#8203;:10
&nbsp;    \#3 0x560a10acb9f4 in Perl\_pp\_require /root/perl/pp\_ctl\.c&#8203;:4291
&nbsp;    \#4 0x560a10757a0d in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2486&#8203;:23
&nbsp;    \#5 0x560a10432f4e in Perl\_call\_sv /root/perl/perl\.c&#8203;:2921&#8203;:6
&nbsp;    \#6 0x560a10419c56 in Perl\_call\_list /root/perl/perl\.c&#8203;:5086&#8203;:6
&nbsp;    \#7 0x560a103b2253 in S\_process\_special\_blocks /root/perl/op\.c&#8203;:9061&#8203;:6
&nbsp;    \#8 0x560a1037a348 in Perl\_newATTRSUB\_x /root/perl/op\.c&#8203;:8990&#8203;:21
&nbsp;    \#9 0x560a1038434b in Perl\_utilize /root/perl/op\.c&#8203;:6341&#8203;:5
&nbsp;    \#10 0x560a105c3ee4 in Perl\_yyparse /root/perl/perly\.y&#8203;:360&#8203;:6
&nbsp;    \#11 0x560a104296f9 in S\_parse\_body /root/perl/perl\.c&#8203;:2450&#8203;:9
&nbsp;    \#12 0x560a1041dc2e in perl\_parse /root/perl/perl\.c&#8203;:1753&#8203;:2
&nbsp;    \#13 0x560a10e00597 in main /root/perl/miniperlmain\.c&#8203;:127&#8203;:18
&nbsp;    \#14 0x7fa54f9ea82f in \_\_libc\_start\_main
/build/glibc\-bfm8X4/glibc\-2\.23/csu/\.\./csu/libc\-start\.c&#8203;:291
&nbsp;    \#15 0x560a102b4e88 in \_start \(/root/perl/miniperl\+0x2fe88\)

SUMMARY&#8203;: MemorySanitizer&#8203;: use\-of\-uninitialized\-value
/root/perl/\./vutil\.c&#8203;:669&#8203;:2 in Perl\_upg\_version
Exiting
Failed to build miniperl\. Please run make minitest
makefile&#8203;:362&#8203;: recipe for target 'lib/buildcustomize\.pl' failed
make&#8203;: \*\*\* \[lib/buildcustomize\.pl\] Error 1

**Comment by p5pRT** [comment]
### From @tonycoz

On Fri\, 06 Oct 2017 13&#8203;:42&#8203;:55 \-0700\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> While building 1195d90 with \-fsanitize=memory\, the process fails during the
> miniperl build\.

Could I have the Configure options and clang version you used to build this? \(since you obviously can't run perl \-V\)

Thanks\,
Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @geeknik

\./Configure \-des \-Dusedevel \-DDEBUGGING \-Dcc=afl\-clang\-fast \-Doptimize=\-O2\\
\-g \-Accflags='\-fno\-omit\-frame\-pointer \-fsanitize=memory
\-fsanitize\-coverage=edge\,trace\-pc\-guard\,indirect\-calls\,trace\-cmp\,trace\-div\,trace\-gep'
\-Aldflags='\-fno\-omit\-frame\-pointer \-fsanitize=memory
\-fsanitize\-coverage=edge\,trace\-pc\-guard\,indirect\-calls\,trace\-cmp\,trace\-div\,trace\-gep'
&&  AFL\_PATH=/root/afl\-2\.51b make

Chromium clang version 6\.0\.0\-trunk&#8203;: git clone
https://chromium.googlesource.com/chromium/src/tools/clang &&
clang/scripts/update\.py





On Wed\, Oct 18\, 2017 at 7&#8203;:51 PM\, Tony Cook via RT \<perlbug\-followup@&#8203;perl\.org
> wrote&#8203;:

> On Fri\, 06 Oct 2017 13&#8203;:42&#8203;:55 \-0700\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> > While building 1195d90 with \-fsanitize=memory\, the process fails during
> the
> > miniperl build\.
>
> Could I have the Configure options and clang version you used to build
> this? \(since you obviously can't run perl \-V\)
>
> Thanks\,
> Tony
>
>

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Brian Carpenter wrote&#8203;:
>==11441==WARNING&#8203;: MemorySanitizer&#8203;: use\-of\-uninitialized\-value
>    \#0 0x560a10786ab7 in Perl\_upg\_version /root/perl/\./vutil\.c&#8203;:669&#8203;:2

I can't make sense of this\, but I can see some other flaws in the
same code\.

That bit of code is concerned with expanding an NV to a version object\,
and more specifically with rendering the NV as a string\.  The process
it's trying to achieve is basically

&nbsp;    $\_ = sprintf\("%\.9f"\, $nv\);
&nbsp;    s/\\\.?0\+\\z//;

Line 669 is part of that trimming operation&#8203;:

&nbsp;    while \(buf\[len\-1\] == '0' && len > 0\) len\-\-;

One can immediately see a flaw\, that the conditions are in the wrong
order\.  The "len > 0" is clearly concerned about running off the beginning
of the buffer\, and ought to be tested before reading from buf\[len\-1\]\.
If the memory immediately before buf counts as uninitialised\, but is
mapped so accessing it doesn't segv\, this would explain getting the
correct behaviour from this line while also getting this uninitialised
read\.

But the logic of the situation is such that this trimming operation can't
ever reach the beginning of the string\.  The sprintf format means that
the trimmable trailing digits must always be preceded by the decimal
point\, which itself must be preceded by at least one digit\.  Indeed\,
the following line of code

&nbsp;    if \( buf\[len\-1\] == '\.' \) len\-\-; /\* eat the trailing decimal \*/

shows no worry about hitting the beginning of the string\.  And if I put in
assertions that check for len reaching zero\, those assertions always pass\,
not only in building but also in the entire test suite\.  I don't see how
the trimming operation could ever reach the beginning of the string\.
So the "len > 0" on line 669 isn't so much misplaced as completely
extraneous\.  It should be removed\, possibly replaced with assertions\.

If those lines are OK\, what about the preceding code that sets up buf
and len?  There are two versions of this code\, one using a stack\-allocated
fixed\-size buffer\, and one using an SV\.  There's logic attempting to use
the fixed\-size buffer if the result will fit\, with fallback to the SV\.
The use of "10e50" as a threshold for SV use suggests that the author
didn't quite understand "e" notation\, but ultimately I believe the
threshold is adequate to avoid overrunning the fixed\-size buffer\.

The code that uses the fixed\-size buffer goes further to avoid overrunning
it\, by using my\_snprintf\(\) rather than straight sprintf\(\)\.  This should
be unnecessary\, given the previous logic\.  It also doesn't actually
avoid undefined behaviour\, because len would still get the untruncated
string length\.  So using snprintf\(\) rather than straight sprintf\(\)
here isn't achieving much; either way it would be more useful to have an
assertion that truncation didn't happen\.  If I insert such an assertion\,
it always passes\, as we'd expect\.

The code that uses an SV buffer is much safer\, assuming we can rely
on the buffer management of the core SV code\.  However\, it has an
entertaining bug\, in that it constructs the SV initially with an undef
value and then uses sv\_catpvf\(\) to append the formatted string\.  So if
warnings are enabled in the relevant scope\, the version upgrade produces
a bogus "uninitialized value" warning\.  \(Try "require\(2e51\)"\.\)  If I
change the buffer choice logic to always go the SV route\, hundreds of
such warnings are duly produced\.  Correcting sv\_catpvf\(\) to sv\_setpvf\(\)
resolves those warnings\, and with that bugfix the always\-SV version of
the function passes all tests\.  I believe that code is correct apart
from the undef issue\.

So plenty of flaws there\, but I don't see the one claimed by the bug
report\.

\-zefram

**Comment by p5pRT** [comment]
### From @cpansprout

On Sat\, 09 Dec 2017 15&#8203;:36&#8203;:55 \-0800\, zefram@&#8203;fysh\.org wrote&#8203;:
> So plenty of flaws there\, but I don't see the one claimed by the bug
> report\.

Whatever changes you might make\, please make sure they get submitted to version\.pm’s bug queue\, and that they are compatible with older perl versions\.  \(Many committers have thus far ignored the comment at the top of the file\.\)

\-\- 

Father Chrysostomos
