### ISSUE TITLE
why it segfaults?

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#162]
Migrated from [rt.perl.org#967](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=967) (status was 'resolved')

Searchable as RT967$

**Comment by p5pRT** [comment]
### From frank@orion.ideare.com

Summary of my perl5 \(5\.0 patchlevel 5 subversion 3\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.2\.1\-ac1\, archname=i386\-linux
&nbsp;    uname='linux porky\.devel\.redhat\.com 2\.2\.1\-ac1 \#1 smp mon feb 1
17&#8203;:44&#8203;:44 est 1999 i686 unknown '
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef useperlio=undef d\_sfio=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, optimize='\-O2'\, gccversion=egcs\-2\.91\.66 19990314/Linux
\(egcs\-1\.1\.2 release\)
&nbsp;    cppflags='\-Dbool=char \-DHAS\_BOOL \-I/usr/local/include'
&nbsp;    ccflags ='\-Dbool=char \-DHAS\_BOOL \-I/usr/local/include'
&nbsp;    stdchar='char'\, d\_stdstdio=undef\, usevfork=false
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;   alignbytes=4\, usemymalloc=n\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-lndbm \-lgdbm \-ldb \-ldl \-lm \-lc \-lposix \-lcrypt
&nbsp;    libc=\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
&nbsp;    cccdlflags='\-fpic'\, lddlflags='\-shared \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Built under linux
&nbsp;  Compiled at Apr  6 1999 23&#8203;:34&#8203;:07
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/lib/perl5/5\.00503/i386\-linux
&nbsp;    /usr/lib/perl5/5\.00503
&nbsp;    /usr/lib/perl5/site\_perl/5\.005/i386\-linux
&nbsp;    /usr/lib/perl5/site\_perl/5\.005

I'm using DBI and DBD&#8203;::mysql\, and\, while I try to insert duplicate record
which contains the % char \(which is a thing allowed in mysql and I can
do it from the mysql client command line\)\, the perl program fails to
print the mysqld error code and often segaults&#8203;:

inserting record&#8203;: www\.acenet\.it/database/Azioni%20innovative%20in%20ambito%20locale%20nel%20campo%20dell%27INFORMATION%20SOCIETY\.html

error&#8203;:
DBD&#8203;::mysql&#8203;::db do failed&#8203;: Duplicate entry 'www\.acenet\.it/database/Azioni
135674528nnovative           135674528n%20ambito          1003074360caleel
ampo         \-1073743128ell%27INFORMATION%20SOCIETY\.html'

it does not segfault here\, but perl prints this "strange form" of the
error\.

but if we add one more %something&#8203;:

inserting record&#8203;: www\.acenet\.it/database/Azion%20i%20innovative%20in%20ambito%20locale%20nel%20campo%20dell%27INFORMATION%20SOCIETY\.html

Segmentation fault \(core dumped\)

then I built a debug version of perl and started gdb \(sorry\, I can't go
further\)\, here are the results&#8203;:


\(gdb\) r \-I\./lib ~frank/prova\.pl
Starting program&#8203;: /home2/frank/perldebug/perl5\.005\_03/\./perl \-I\./lib
~frank/prova\.pl
www\.acenet\.it/database/Azioni%20innovative%20in%20ambito%20locale%20nel%20campo%20dell%27INFORMATION%20SOCIETY\.html

Program received signal SIGSEGV\, Segmentation fault\.
0x80b0352 in Perl\_sv\_vcatpvfn \(sv=0x810fa38\, 
&nbsp;    pat=0x81bc600 "DBD&#8203;::mysql&#8203;::db do failed&#8203;: Duplicate entry
'www\.acenet\.it/database/Azioni%20innovative%20in%20ambito%20locale%20nel%20campo%20dell%27INFORMATION%20SOCIETY\.html'
for key 1"\, patlen=169\, args=0xbffff998\, svargs=0x0\, 
&nbsp;    svmax=0\, used\_locale=0x0\) at sv\.c&#8203;:4826
4826          default&#8203;:  \*\(va\_arg\(\*args\, int\*\)\) = i; break;


\(gdb\) backtrace
\#0  0x80b0352 in Perl\_sv\_vcatpvfn \(sv=0x810fa38\, 
&nbsp;    pat=0x81bc600 "DBD&#8203;::mysql&#8203;::db do failed&#8203;: Duplicate entry
'www\.acenet\.it/database/Azioni%20innovative%20in%20ambito%20locale%20nel%20campo%20dell%27INFORMATION%20SOCIETY\.html'
for key 1"\, patlen=169\, args=0xbffff998\, svargs=0x0\, 
&nbsp;    svmax=0\, used\_locale=0x0\) at sv\.c&#8203;:4826
\#1  0x80ae27b in Perl\_sv\_vsetpvfn \(sv=0x810fa38\, 
&nbsp;    pat=0x81bc600 "DBD&#8203;::mysql&#8203;::db do failed&#8203;: Duplicate entry
'www\.acenet\.it/database/Azioni%20innovative%20in%20ambito%20locale%20nel%20campo%20dell%27INFORMATION%20SOCIETY\.html'
for key 1"\, patlen=169\, args=0xbffff998\, svargs=0x0\, 
&nbsp;    svmax=0\, used\_locale=0x0\) at sv\.c&#8203;:4402
\#2  0x808e601 in Perl\_mess \(
&nbsp;    pat=0x81bc600 "DBD&#8203;::mysql&#8203;::db do failed&#8203;: Duplicate entry
'www\.acenet\.it/database/Azioni%20innovative%20in%20ambito%20locale%20nel%20campo%20dell%27INFORMATION%20SOCIETY\.html'
for key 1"\, args=0xbffff998\) at util\.c&#8203;:1222
\#3  0x808f0a6 in Perl\_warn \(
&nbsp;    pat=0x81bc600 "DBD&#8203;::mysql&#8203;::db do failed&#8203;: Duplicate entry
'www\.acenet\.it/database/Azioni%20innovative%20in%20ambito%20locale%20nel%20campo%20dell%27INFORMATION%20SOCIETY\.html'
for key 1"\) at util\.c&#8203;:1367
\#4  0x401af43e in XS\_DBI\_dispatch \(\)
\#5  0x80a2897 in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:2255
\#6  0x809b5a4 in Perl\_runops\_debug \(\) at run\.c&#8203;:66
\#7  0x805a77e in perl\_run \(sv\_interp=0x810aef8\) at perl\.c&#8203;:1100
\#8  0x8057f53 in main \(argc=3\, argv=0xbffffd14\, env=0xbffffd24\) at
perlmain\.c&#8203;:51
\#9  0x400a5cb3 in \_\_libc\_start\_main \(main=0x8057ed0 \<main>\, argc=3\,
argv=0xbffffd14\, init=0x80570a8 \<\_init>\, 
&nbsp;    fini=0x80f10dc \<\_fini>\, rtld\_fini=0x4000a350 \<\_dl\_fini>\,
stack\_end=0xbffffd0c\)
&nbsp;    at \.\./sysdeps/generic/libc\-start\.c&#8203;:78


I really hope that someone can point me out the right solution\, other than
not using % chars in mysql records\.\.\.

Regards\.

Francesco Messineo
