### ISSUE TITLE
segfault in S_check_uni (toke.c:1938)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16241]
Migrated from [rt.perl.org#132433](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132433) (status was 'resolved')

Searchable as RT132433$

**Comment by p5pRT** [comment]
### From @geeknik

\./perl \-e 'dj\{lc\-&1J' triggers a segfault in v5\.27\.5\-323\-g2b503742ec\.

==26052==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x602000010000
\(pc 0x7f3e54333caa bp 0x7fffccd42ab0 sp 0x7fffccd42248 T0\)
==26052==The signal is caused by a READ memory access\.
&nbsp;    \#0 0x7f3e54333ca9 in memchr \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x90ca9\)
&nbsp;    \#1 0x451731 in \_\_interceptor\_memchr \(/root/perl/perl\+0x451731\)
&nbsp;    \#2 0x6a520d in S\_check\_uni /root/perl/toke\.c&#8203;:1938&#8203;:9
&nbsp;    \#3 0x65a8ab in Perl\_yylex /root/perl/toke\.c&#8203;:5768&#8203;:7
&nbsp;    \#4 0x6cb273 in Perl\_yyparse /root/perl/perly\.c&#8203;:340&#8203;:34
&nbsp;    \#5 0x5bfd22 in S\_parse\_body /root/perl/perl\.c&#8203;:2452&#8203;:9
&nbsp;    \#6 0x5b7c5a in perl\_parse /root/perl/perl\.c&#8203;:1755&#8203;:2
&nbsp;    \#7 0x5033e5 in main /root/perl/perlmain\.c&#8203;:121&#8203;:18
&nbsp;    \#8 0x7f3e542c33f0 in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x203f0\)
&nbsp;    \#9 0x4360a9 in \_start \(/root/perl/perl\+0x4360a9\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x90ca9\)
in memchr
==26052==ABORTING

**Comment by p5pRT** [comment]
### From @geeknik

\./perl \-e '\-C\-' also triggers this segfault\, unless you put \-C\- in file and
run \./perl file in which case it triggers this&#8203;:

==26553==ERROR&#8203;: AddressSanitizer&#8203;: negative\-size\-param&#8203;: \(size=\-1\)
&nbsp;    \#0 0x451782 in \_\_interceptor\_memchr \(/root/perl/perl\+0x451782\)
&nbsp;    \#1 0x6a520d in S\_check\_uni /root/perl/toke\.c&#8203;:1938&#8203;:9
&nbsp;    \#2 0x65a8ab in Perl\_yylex /root/perl/toke\.c&#8203;:5768&#8203;:7
&nbsp;    \#3 0x6cb273 in Perl\_yyparse /root/perl/perly\.c&#8203;:340&#8203;:34
&nbsp;    \#4 0x5bfd22 in S\_parse\_body /root/perl/perl\.c&#8203;:2452&#8203;:9
&nbsp;    \#5 0x5b7c5a in perl\_parse /root/perl/perl\.c&#8203;:1755&#8203;:2
&nbsp;    \#6 0x5033e5 in main /root/perl/perlmain\.c&#8203;:121&#8203;:18
&nbsp;    \#7 0x7febd38513f0 in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x203f0\)
&nbsp;    \#8 0x4360a9 in \_start \(/root/perl/perl\+0x4360a9\)

0x602000000df3 is located 3 bytes inside of 10\-byte region
\[0x602000000df0\,0x602000000dfa\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4d6da3 in malloc \(/root/perl/perl\+0x4d6da3\)
&nbsp;    \#1 0x7f6f98 in Perl\_safesysmalloc /root/perl/util\.c&#8203;:153&#8203;:21
&nbsp;    \#2 0x8efcab in Perl\_sv\_grow /root/perl/sv\.c&#8203;:1603&#8203;:17
&nbsp;    \#3 0x9072d9 in Perl\_sv\_setpvn /root/perl/sv\.c&#8203;:5004&#8203;:12
&nbsp;    \#4 0x956fae in Perl\_newSVpvn /root/perl/sv\.c&#8203;:9441&#8203;:5
&nbsp;    \#5 0x60de28 in Perl\_lex\_start /root/perl/toke\.c&#8203;:768&#8203;:20
&nbsp;    \#6 0x5bfc32 in S\_parse\_body /root/perl/perl\.c&#8203;:2441&#8203;:5
&nbsp;    \#7 0x5b7c5a in perl\_parse /root/perl/perl\.c&#8203;:1755&#8203;:2
&nbsp;    \#8 0x5033e5 in main /root/perl/perlmain\.c&#8203;:121&#8203;:18
&nbsp;    \#9 0x7febd38513f0 in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x203f0\)

SUMMARY&#8203;: AddressSanitizer&#8203;: negative\-size\-param \(/root/perl/perl\+0x451782\)
in \_\_interceptor\_memchr
==26553==ABORTING

**Comment by p5pRT** [comment]
### From @mauke

On Sat\, 11 Nov 2017 14&#8203;:04&#8203;:40 \-0800\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> \./perl \-e '\-C\-' also triggers this segfault\, unless you put \-C\- in file and
> run \./perl file in which case it triggers this&#8203;:
> 
> ==26553==ERROR&#8203;: AddressSanitizer&#8203;: negative\-size\-param&#8203;: \(size=\-1\)
>     \#0 0x451782 in \_\_interceptor\_memchr \(/root/perl/perl\+0x451782\)
>     \#1 0x6a520d in S\_check\_uni /root/perl/toke\.c&#8203;:1938&#8203;:9
>     \#2 0x65a8ab in Perl\_yylex /root/perl/toke\.c&#8203;:5768&#8203;:7
>     \#3 0x6cb273 in Perl\_yyparse /root/perl/perly\.c&#8203;:340&#8203;:34
>     \#4 0x5bfd22 in S\_parse\_body /root/perl/perl\.c&#8203;:2452&#8203;:9
>     \#5 0x5b7c5a in perl\_parse /root/perl/perl\.c&#8203;:1755&#8203;:2
>     \#6 0x5033e5 in main /root/perl/perlmain\.c&#8203;:121&#8203;:18
>     \#7 0x7febd38513f0 in \_\_libc\_start\_main
> \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x203f0\)
>     \#8 0x4360a9 in \_start \(/root/perl/perl\+0x4360a9\)
> 
> 0x602000000df3 is located 3 bytes inside of 10\-byte region
> \[0x602000000df0\,0x602000000dfa\)
> allocated by thread T0 here&#8203;:
>     \#0 0x4d6da3 in malloc \(/root/perl/perl\+0x4d6da3\)
>     \#1 0x7f6f98 in Perl\_safesysmalloc /root/perl/util\.c&#8203;:153&#8203;:21
>     \#2 0x8efcab in Perl\_sv\_grow /root/perl/sv\.c&#8203;:1603&#8203;:17
>     \#3 0x9072d9 in Perl\_sv\_setpvn /root/perl/sv\.c&#8203;:5004&#8203;:12
>     \#4 0x956fae in Perl\_newSVpvn /root/perl/sv\.c&#8203;:9441&#8203;:5
>     \#5 0x60de28 in Perl\_lex\_start /root/perl/toke\.c&#8203;:768&#8203;:20
>     \#6 0x5bfc32 in S\_parse\_body /root/perl/perl\.c&#8203;:2441&#8203;:5
>     \#7 0x5b7c5a in perl\_parse /root/perl/perl\.c&#8203;:1755&#8203;:2
>     \#8 0x5033e5 in main /root/perl/perlmain\.c&#8203;:121&#8203;:18
>     \#9 0x7febd38513f0 in \_\_libc\_start\_main
> \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x203f0\)
> 
> SUMMARY&#8203;: AddressSanitizer&#8203;: negative\-size\-param \(/root/perl/perl\+0x451782\)
> in \_\_interceptor\_memchr
> ==26553==ABORTING

Fixed in commit 4efcdc02\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@mauke - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From zefram@fysh.org

l\.mai@&#8203;web\.de via RT wrote&#8203;:
>Fixed in commit 4efcdc02\.

That's not a fix\.  It avoids crashing\, but the parser state still gets
messed up\.

\-zefram

**Comment by p5pRT** [comment]
### From zefram@fysh.org

I wrote&#8203;:
>That's not a fix\.

Sorry\, I misread it\.  I think it's fine\.

\-zefram
