### ISSUE TITLE
Assertion failure in S_maybe_multiconcat (op.c:2727)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16295]
Migrated from [rt.perl.org#132554](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132554) (status was 'resolved')

Searchable as RT132554$

**Comment by p5pRT** [comment]
### From @geeknik

This assertion failure was triggered in Perl v5\.27\.6\-156\-g5d4548b73b\,
compiled with Clang 6\.0\.0\-trunk and \-fsanitize=address\.

 \./perl \-e 'H\.\-w\.w\.=0'
perl&#8203;: op\.c&#8203;:2727&#8203;: void S\_maybe\_multiconcat\(OP \*\)&#8203;: Assertion \`\!\(o\->op\_private
& ~\(OPpARG2\_MASK|OPpTARGET\_MY\)\)' failed\.
Aborted

\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:58
\#1  0x00007ffff6cc837a in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007ffff6cbeb47 in \_\_assert\_fail\_base \(fmt=\<optimized out>\,
assertion=assertion@&#8203;entry=0xbf9020 \<\.str> "\!\(o\->op\_private &
~\(OPpARG2\_MASK|OPpTARGET\_MY\)\)"\, file=file@&#8203;entry=0xbed660 \<\.str> "op\.c"\,
line=line@&#8203;entry=2727\,
&nbsp;    function=function@&#8203;entry=0xbf8f40 \<\_\_PRETTY\_FUNCTION\_\_\.S\_maybe\_multiconcat>
"void S\_maybe\_multiconcat\(OP \*\)"\) at assert\.c&#8203;:92
\#3  0x00007ffff6cbebf2 in \_\_GI\_\_\_assert\_fail \(assertion=0xbf9020 \<\.str>
"\!\(o\->op\_private & ~\(OPpARG2\_MASK|OPpTARGET\_MY\)\)"\, file=0xbed660 \<\.str>
"op\.c"\, line=2727\, function=0xbf8f40 \<\_\_PRETTY\_FUNCTION\_\_\.S\_maybe\_multiconcat>
"void S\_maybe\_multiconcat\(OP \*\)"\) at assert\.c&#8203;:101
\#4  0x000000000058b77a in S\_maybe\_multiconcat \(o=\<optimized out>\) at
op\.c&#8203;:2727
\#5  0x0000000000512f9b in S\_optimize\_op \(o=0x619000002200\) at op\.c&#8203;:3472
\#6  0x0000000000513082 in S\_optimize\_op \(o=\<optimized out>\) at op\.c&#8203;:3488
\#7  0x0000000000512c9c in Perl\_optimize\_optree \(o=0x619000002158\) at
op\.c&#8203;:3443
\#8  0x0000000000526dc1 in S\_process\_optree \(cv=0x0\, optree=0x619000002158\,
start=0x619000002120\) at op\.c&#8203;:3411
\#9  0x000000000052626a in Perl\_newPROG \(o=0x619000002158\) at op\.c&#8203;:5317
\#10 0x00000000006a8067 in Perl\_yyparse \(gramtype=\<optimized out>\) at
perly\.y&#8203;:124
\#11 0x00000000005a3c22 in S\_parse\_body \(env=\<optimized out>\,
xsinit=\<optimized out>\) at perl\.c&#8203;:2447
\#12 0x000000000059ea24 in perl\_parse \(my\_perl=\<optimized out>\,
xsinit=0x5036f0 \<xs\_init>\, argc=2\, argv=\<optimized out>\, env=0x0\) at
perl\.c&#8203;:1750
\#13 0x0000000000503486 in main \(argc=0\, argv=0x7ffff6cc677f
\<\_\_GI\_raise\+159>\, env=0x7fffffffe380\) at perlmain\.c&#8203;:121

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Brian Carpenter wrote&#8203;:
> \./perl \-e 'H\.\-w\.w\.=0'
>perl&#8203;: op\.c&#8203;:2727&#8203;: void S\_maybe\_multiconcat\(OP \*\)&#8203;: Assertion \`\!\(o\->op\_private
>& ~\(OPpARG2\_MASK|OPpTARGET\_MY\)\)' failed\.

The first bad commit is d962625ff9208c2f683374d283f74eee759c2202
"add OPpCONCAT\_NESTED flag" by DaveM\.  An obvious suspicion is that
the assertion should have been loosened to also permit the new flag\.
But over to DaveM\.

\-zefram

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, Dec 09\, 2017 at 09&#8203;:28&#8203;:45PM \+0000\, Zefram wrote&#8203;:
> Brian Carpenter wrote&#8203;:
> > \./perl \-e 'H\.\-w\.w\.=0'
> >perl&#8203;: op\.c&#8203;:2727&#8203;: void S\_maybe\_multiconcat\(OP \*\)&#8203;: Assertion \`\!\(o\->op\_private
> >& ~\(OPpARG2\_MASK|OPpTARGET\_MY\)\)' failed\.
> 
> The first bad commit is d962625ff9208c2f683374d283f74eee759c2202
> "add OPpCONCAT\_NESTED flag" by DaveM\.  An obvious suspicion is that
> the assertion should have been loosened to also permit the new flag\.
> But over to DaveM\.

Now fixed with v5\.27\.6\-190\-g62c1220

\-\- 
The warp engines start playing up a bit\, but seem to sort themselves out
after a while without any intervention from boy genius Wesley Crusher\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#17

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
