### ISSUE TITLE
Assertion failure in perl_yylex (toke.c:6333)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16303]
Migrated from [rt.perl.org#132583](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132583) (status was 'resolved')

Searchable as RT132583$

**Comment by p5pRT** [comment]
### From @geeknik

This assertion failure was triggered in Perl v5\.27\.6\-156\-g5d4548b73b\,
compiled with Clang 6\.0\.0\-trunk and \-fsanitize=address\.

\./perl \-e 'format=
^
0m\}\}
\.'

perl&#8203;: toke\.c&#8203;:6333&#8203;: int Perl\_yylex\(void\)&#8203;: Assertion
\`\(\(char\*\)PL\_scopestack\_name\[PL\_scopestack\_ix\-1\] == \(char\*\)"lex\_format"\) ||
strEQ\(PL\_scopestack\_name\[PL\_scopestack\_ix\-1\]\, "lex\_format"\)' failed\.
Aborted

\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:58
\#1  0x00007ffff6cc837a in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007ffff6cbeb47 in \_\_assert\_fail\_base \(fmt=\<optimized out>\,
assertion=assertion@&#8203;entry=0xc555c0 \<\.str\.182>
"\(\(char\*\)PL\_scopestack\_name\[PL\_scopestack\_ix\-1\] == \(char\*\)\\"lex\_format\\"\)
|| strEQ\(PL\_scopestack\_name\[PL\_scopestack\_ix\-1\]\, \\"lex\_format\\"\)"\,
file=file@&#8203;entry=0xc4b240 \<\.str\.1> "toke\.c"\,
&nbsp;    line=line@&#8203;entry=6333\, function=function@&#8203;entry=0xc4d840
\<\_\_PRETTY\_FUNCTION\_\_\.Perl\_yylex> "int Perl\_yylex\(void\)"\) at assert\.c&#8203;:92
\#3  0x00007ffff6cbebf2 in \_\_GI\_\_\_assert\_fail \(assertion=0xc555c0 \<\.str\.182>
"\(\(char\*\)PL\_scopestack\_name\[PL\_scopestack\_ix\-1\] == \(char\*\)\\"lex\_format\\"\)
|| strEQ\(PL\_scopestack\_name\[PL\_scopestack\_ix\-1\]\, \\"lex\_format\\"\)"\,
file=0xc4b240 \<\.str\.1> "toke\.c"\, line=6333\,
&nbsp;    function=0xc4d840 \<\_\_PRETTY\_FUNCTION\_\_\.Perl\_yylex> "int
Perl\_yylex\(void\)"\) at assert\.c&#8203;:101
\#4  0x000000000064d2ec in Perl\_yylex \(\) at toke\.c&#8203;:6333
\#5  0x00000000006a67f4 in Perl\_yyparse \(gramtype=\<optimized out>\) at
perly\.c&#8203;:340
\#6  0x00000000005a3c22 in S\_parse\_body \(env=\<optimized out>\,
xsinit=\<optimized out>\) at perl\.c&#8203;:2447
\#7  0x000000000059ea24 in perl\_parse \(my\_perl=\<optimized out>\,
xsinit=0x5036f0 \<xs\_init>\, argc=2\, argv=\<optimized out>\, env=0x0\) at
perl\.c&#8203;:1750
\#8  0x0000000000503486 in main \(argc=0\, argv=0x7ffff6cc677f
\<\_\_GI\_raise\+159>\, env=0x7fffffffe380\) at perlmain\.c&#8203;:121

**Comment by p5pRT** [comment]
### From @tonycoz

On Thu\, 14 Dec 2017 20&#8203;:46&#8203;:01 \-0800\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> This assertion failure was triggered in Perl v5\.27\.6\-156\-g5d4548b73b\,
> compiled with Clang 6\.0\.0\-trunk and \-fsanitize=address\.
> 
> \./perl \-e 'format=
> ^
> 0m\}\}
> \.'
> 

This looks like it was fixed by 817480137a8b1165315f21d14b8968862101c3a2\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Sun\, 20 Jan 2019 19&#8203;:26&#8203;:47 \-0800\, tonyc wrote&#8203;:
> On Thu\, 14 Dec 2017 20&#8203;:46&#8203;:01 \-0800\, brian\.carpenter@&#8203;gmail\.com wrote&#8203;:
> > This assertion failure was triggered in Perl v5\.27\.6\-156\-g5d4548b73b\,
> > compiled with Clang 6\.0\.0\-trunk and \-fsanitize=address\.
> > 
> > \./perl \-e 'format=
> > ^
> > 0m\}\}
> > \.'
> > 
> 
> This looks like it was fixed by 817480137a8b1165315f21d14b8968862101c3a2\.

And closing\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.30\.0\, this and 160 other issues have been
resolved\.

Perl 5\.30\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.30.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
