### ISSUE TITLE
Assertion failure in Perl_fbm_instr (util.c:816)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16329]
Migrated from [rt.perl.org#132630](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132630) (status was 'resolved')

Searchable as RT132630$

**Comment by p5pRT** [comment]
### From @geeknik

This assertion failure was triggered with Perl v5\.27\.6\-346\-gd4abdeed82\,
built with clang 6\-trunk and \-fsanitize=address\.

 \./perl \-e '$\_="0\\x\{1000000\}";/^000?\\0000/'
perl&#8203;: util\.c&#8203;:816&#8203;: char \*Perl\_fbm\_instr\(unsigned char \*\, unsigned char \*\, SV
\*\, U32\)&#8203;: Assertion \`bigend >= big' failed\.
Aborted

\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:58
\#1  0x00007ffff6cc837a in \_\_GI\_abort \(\) at abort\.c&#8203;:89
\#2  0x00007ffff6cbeb47 in \_\_assert\_fail\_base \(fmt=\<optimized out>\,
assertion=assertion@&#8203;entry=0xcbcde0 \<\.str\.35> "bigend >= big"\,
file=file@&#8203;entry=0xcbc440 \<\.str\.9> "util\.c"\, line=line@&#8203;entry=816\,
&nbsp;    function=function@&#8203;entry=0xcbcc40 \<\_\_PRETTY\_FUNCTION\_\_\.Perl\_fbm\_instr>
"char \*Perl\_fbm\_instr\(unsigned char \*\, unsigned char \*\, SV \*\, U32\)"\) at
assert\.c&#8203;:92
\#3  0x00007ffff6cbebf2 in \_\_GI\_\_\_assert\_fail \(assertion=0xcbcde0 \<\.str\.35>
"bigend >= big"\, file=0xcbc440 \<\.str\.9> "util\.c"\, line=816\,
function=0xcbcc40 \<\_\_PRETTY\_FUNCTION\_\_\.Perl\_fbm\_instr> "char
\*Perl\_fbm\_instr\(unsigned char \*\, unsigned char \*\, SV \*\, U32\)"\) at
assert\.c&#8203;:101
\#4  0x00000000007bda79 in Perl\_fbm\_instr \(big=\<optimized out>\,
bigend=0x602000000fb3 "\\200\\200\\200"\, littlestr=0x621000001968\, flags=0\) at
util\.c&#8203;:816
\#5  0x0000000000a9dbb4 in Perl\_re\_intuit\_start \(rx=0x602000000fb6\,
sv=\<optimized out>\, strbeg=0x602000000fb0 "0\\371\\200\\200\\200\\200"\,
strpos=\<optimized out>\, strend=0x602000000fb6 ""\, flags=\<optimized out>\,
data=\<optimized out>\) at regexec\.c&#8203;:935
\#6  0x0000000000a92680 in Perl\_regexec\_flags \(rx=0x62100000c328\,
stringarg=0x602000000fb0 "0\\371\\200\\200\\200\\200"\, strend=0x602000000fb6 ""\,
strbeg=0x602000000fb0 "0\\371\\200\\200\\200\\200"\, minend=0\, sv=\<optimized
out>\, data=\<optimized out>\, flags=\<optimized out>\) at regexec\.c&#8203;:3015
\#7  0x0000000000877578 in Perl\_pp\_match \(\) at pp\_hot\.c&#8203;:3046
\#8  0x00000000007b47e9 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2495
\#9  0x00000000005a6332 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2717
\#10 0x00000000005a5981 in perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2633
\#11 0x0000000000503698 in main \(argc=\<optimized out>\, argv=\<optimized out>\,
env=0x7fffffffe380\) at perlmain\.c&#8203;:123

**Comment by p5pRT** [comment]
### From @khwilliamson

I looked at this briefly\.  It looks like an issue where something is expecting a NUL\-terminated C string\, but the data contains an embedded NUL\.  Scanning through the fbm code\, I saw only operation that allowed embedded NULs\.

\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @demerphq

On 7 February 2018 at 22&#8203;:35\, Karl Williamson via RT
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> I looked at this briefly\.  It looks like an issue where something is expecting a NUL\-terminated C string\, but the data contains an embedded NUL\.  Scanning through the fbm code\, I saw only operation that allowed embedded NULs\.

Run it with \-Mre=Debug\,ALL
\.\.\.
Matching REx "^000?\\0000" against "0%x\{1000000\}"
UTF\-8 string\.\.\.
Intuit&#8203;: trying to determine minimum start position\.\.\.
&nbsp;  substrs\[0\]&#8203;: min=0 max=0 end shift=2 useful=100 utf8=1 \[PVMG\("00"\\0\)
\[UTF8 "00"\]\]
&nbsp;  substrs\[1\]&#8203;: min=2 max=3 end shift=0 useful=100 utf8=1
\[PVMG\("\\0000"\\0\) \[UTF8 "\\x\{0\}0"\]\]
&nbsp;  substrs\[2\]&#8203;: min=2 max=3 end shift=0 useful=100 utf8=1
\[PVMG\("\\0000"\\0\) \[UTF8 "\\x\{0\}0"\]\]
&nbsp;  At restart&#8203;: rx\_origin=0 Check offset min&#8203;: 2 Start shift&#8203;: 2 End shift
0 Real end Shift&#8203;: 0
\[assert goes here\]

The string is only two characters long\, and the string we are looking
for "\\x\{0\}0" has to be found at position 2 or later\.

We are falling into the block at around 1253 of regexec\.c where we
recompute the endpoint\, and we dont take into account that doing so
could move the endpoint to before the start point\.

Fixed in 12453e29a22d63862ba5924c61c08baabd9c6782

:\-\)

I think this can be closed\.

Yves

**Comment by p5pRT** [comment]
### From @khwilliamson

Agreed\.  Closing
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release yesterday of Perl 5\.28\.0\, this and 185 other issues have been
resolved\.

Perl 5\.28\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.28.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
