### ISSUE TITLE
PERL-5.26.1 negative-size-param

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16342]
Migrated from [rt.perl.org#132654](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132654) (status was 'rejected')

Searchable as RT132654$

**Comment by p5pRT** [comment]
### From sraums2498@gmail.com

=================================================================
==69672==ERROR&#8203;: AddressSanitizer&#8203;: negative\-size\-param&#8203;: \(size=1\)
&nbsp;    \#0 0x7f152c25805d in \_\_asan\_memmove
\(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.2\+0x8d05d\)
&nbsp;    \#1 0x1e8c935 in memmove /usr/include/x86\_64\-linux\-gnu/bits/string3\.h&#8203;:59
&nbsp;    \#2 0x1e8c935 in Perl\_sv\_setpvn
/home/asan\_perl/Documents/perl\-5\.26\.1/sv\.c&#8203;:5004
&nbsp;    \#3 0x1e903d0 in Perl\_newSVpvn\_flags
/home/asan\_perl/Documents/perl\-5\.26\.1/sv\.c&#8203;:9285
&nbsp;    \#4 0x2eb918e in S\_unpack\_rec
/home/asan\_perl/Documents/perl\-5\.26\.1/pp\_pack\.c&#8203;:1627
&nbsp;    \#5 0x2f6a66a in Perl\_unpackstring
/home/asan\_perl/Documents/perl\-5\.26\.1/pp\_pack\.c&#8203;:838
&nbsp;    \#6 0x2f6c002 in Perl\_pp\_unpack
/home/asan\_perl/Documents/perl\-5\.26\.1/pp\_pack\.c&#8203;:1848
&nbsp;    \#7 0x1b1bc2e in Perl\_runops\_standard
/home/asan\_perl/Documents/perl\-5\.26\.1/run\.c&#8203;:41
&nbsp;    \#8 0x9218a5 in S\_run\_body
/home/asan\_perl/Documents/perl\-5\.26\.1/perl\.c&#8203;:2519
&nbsp;    \#9 0x9218a5 in perl\_run
/home/asan\_perl/Documents/perl\-5\.26\.1/perl\.c&#8203;:2447
&nbsp;    \#10 0x46b6a7 in main
/home/asan\_perl/Documents/perl\-5\.26\.1/perlmain\.c&#8203;:123
&nbsp;    \#11 0x7f152b4bf82f in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2082f\)
&nbsp;    \#12 0x46c888 in \_start
\(/home/asan\_perl/Documents/perl\-5\.26\.1/perl\+0x46c888\)

==69672==AddressSanitizer CHECK failed&#8203;:
\.\./\.\./\.\./\.\./src/libsanitizer/asan/asan\_report\.cc&#8203;:322 "\(\(0 && "Address is
not in memory and not in shadow?"\)\) \!= \(0\)" \(0x0\, 0x0\)
&nbsp;    \#0 0x7f152c26b631  \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.2\+0xa0631\)
&nbsp;    \#1 0x7f152c2705e3 in \_\_sanitizer&#8203;::CheckFailed\(char const\*\, int\, char
const\*\, unsigned long long\, unsigned long long\)
\(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.2\+0xa55e3\)
&nbsp;    \#2 0x7f152c267b97  \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.2\+0x9cb97\)
&nbsp;    \#3 0x7f152c268c77  \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.2\+0x9dc77\)
&nbsp;    \#4 0x7f152c269daf  \(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.2\+0x9edaf\)
&nbsp;    \#5 0x7f152c2580d0 in \_\_asan\_memmove
\(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.2\+0x8d0d0\)
&nbsp;    \#6 0x1e8c935 in memmove /usr/include/x86\_64\-linux\-gnu/bits/string3\.h&#8203;:59
&nbsp;    \#7 0x1e8c935 in Perl\_sv\_setpvn
/home/asan\_perl/Documents/perl\-5\.26\.1/sv\.c&#8203;:5004
&nbsp;    \#8 0x1e903d0 in Perl\_newSVpvn\_flags
/home/asan\_perl/Documents/perl\-5\.26\.1/sv\.c&#8203;:9285
&nbsp;    \#9 0x2eb918e in S\_unpack\_rec
/home/asan\_perl/Documents/perl\-5\.26\.1/pp\_pack\.c&#8203;:1627
&nbsp;    \#10 0x2f6a66a in Perl\_unpackstring
/home/asan\_perl/Documents/perl\-5\.26\.1/pp\_pack\.c&#8203;:838
&nbsp;    \#11 0x2f6c002 in Perl\_pp\_unpack
/home/asan\_perl/Documents/perl\-5\.26\.1/pp\_pack\.c&#8203;:1848
&nbsp;    \#12 0x1b1bc2e in Perl\_runops\_standard
/home/asan\_perl/Documents/perl\-5\.26\.1/run\.c&#8203;:41
&nbsp;    \#13 0x9218a5 in S\_run\_body
/home/asan\_perl/Documents/perl\-5\.26\.1/perl\.c&#8203;:2519
&nbsp;    \#14 0x9218a5 in perl\_run
/home/asan\_perl/Documents/perl\-5\.26\.1/perl\.c&#8203;:2447
&nbsp;    \#15 0x46b6a7 in main
/home/asan\_perl/Documents/perl\-5\.26\.1/perlmain\.c&#8203;:123
&nbsp;    \#16 0x7f152b4bf82f in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2082f\)
&nbsp;    \#17 0x46c888 in \_start
\(/home/asan\_perl/Documents/perl\-5\.26\.1/perl\+0x46c888\)


\-\- 
Regards\,
SRAUMS

**Comment by p5pRT** [comment]
### From sraums2498@gmail.com

[id_000600,sig_11,src_039820,op_havoc,rep_4](https://rt-archive.perl.org/perl5/Ticket/Attachment/1519431/812713/id_000600,sig_11,src_039820,op_havoc,rep_4)

**Comment by p5pRT** [comment]
### From sraums2498@gmail.com

==3861==ERROR&#8203;: AddressSanitizer&#8203;: global\-buffer\-overflow on address
0x0000030f2da1 at pc 0x7ffff6ef6df8 bp 0x7fffffffd480 sp 0x7fffffffcc28
READ of size 555 at 0x0000030f2da1 thread T0
&nbsp;    \#0 0x7ffff6ef6df7 in \_\_asan\_memmove
\(/usr/lib/x86\_64\-linux\-gnu/libasan\.so\.2\+0x8cdf7\)
&nbsp;    \#1 0x1e8c935 in memmove /usr/include/x86\_64\-linux\-gnu/bits/string3\.h&#8203;:59
&nbsp;    \#2 0x1e8c935 in Perl\_sv\_setpvn
/home/asan\_perl/Documents/perl\-5\.26\.1/sv\.c&#8203;:5004
&nbsp;    \#3 0x1e903d0 in Perl\_newSVpvn\_flags
/home/asan\_perl/Documents/perl\-5\.26\.1/sv\.c&#8203;:9285
&nbsp;    \#4 0x2eb918e in S\_unpack\_rec
/home/asan\_perl/Documents/perl\-5\.26\.1/pp\_pack\.c&#8203;:1627
&nbsp;    \#5 0x2f6a66a in Perl\_unpackstring
/home/asan\_perl/Documents/perl\-5\.26\.1/pp\_pack\.c&#8203;:838
&nbsp;    \#6 0x2f6c002 in Perl\_pp\_unpack
/home/asan\_perl/Documents/perl\-5\.26\.1/pp\_pack\.c&#8203;:1848
&nbsp;    \#7 0x1b1bc2e in Perl\_runops\_standard
/home/asan\_perl/Documents/perl\-5\.26\.1/run\.c&#8203;:41
&nbsp;    \#8 0x9218a5 in S\_run\_body
/home/asan\_perl/Documents/perl\-5\.26\.1/perl\.c&#8203;:2519
&nbsp;    \#9 0x9218a5 in perl\_run
/home/asan\_perl/Documents/perl\-5\.26\.1/perl\.c&#8203;:2447
&nbsp;    \#10 0x46b6a7 in main
/home/asan\_perl/Documents/perl\-5\.26\.1/perlmain\.c&#8203;:123
&nbsp;    \#11 0x7ffff615e82f in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2082f\)
&nbsp;    \#12 0x46c888 in \_start
\(/home/asan\_perl/Documents/perl\-5\.26\.1/perl\+0x46c888\)

0x0000030f2da1 is located 63 bytes to the left of global variable 'PL\_Yes'
defined in 'perl\.h&#8203;:4769&#8203;:15' \(0x30f2de0\) of size 2
&nbsp;  'PL\_Yes' is ascii string '1'
0x0000030f2da1 is located 0 bytes to the right of global variable 'PL\_No'
defined in 'perl\.h&#8203;:4771&#8203;:15' \(0x30f2da0\) of size 1
&nbsp;  'PL\_No' is ascii string ''
SUMMARY&#8203;: AddressSanitizer&#8203;: global\-buffer\-overflow ??&#8203;:0 \_\_asan\_memmove
Shadow bytes around the buggy address&#8203;:
&nbsp;  0x000080616560&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 f9 f9 f9 f9
&nbsp;  0x000080616570&#8203;: 04 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
&nbsp;  0x000080616580&#8203;: 01 f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9
&nbsp;  0x000080616590&#8203;: 01 f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9
&nbsp;  0x0000806165a0&#8203;: 00 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 01 f9 f9 f9
=>0x0000806165b0&#8203;: f9 f9 f9 f9\[01\]f9 f9 f9 f9 f9 f9 f9 02 f9 f9 f9
&nbsp;  0x0000806165c0&#8203;: f9 f9 f9 f9 00 00 03 f9 f9 f9 f9 f9 00 00 00 00
&nbsp;  0x0000806165d0&#8203;: 03 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 02 f9 f9 f9
&nbsp;  0x0000806165e0&#8203;: f9 f9 f9 f9 00 00 00 00 01 f9 f9 f9 f9 f9 f9 f9
&nbsp;  0x0000806165f0&#8203;: 00 00 00 00 00 03 f9 f9 f9 f9 f9 f9 00 00 00 00
&nbsp;  0x000080616600&#8203;: 00 f9 f9 f9 f9 f9 f9 f9 00 00 00 04 f9 f9 f9 f9
Shadow byte legend \(one shadow byte represents 8 application bytes\)&#8203;:
&nbsp;  Addressable&#8203;:           00
&nbsp;  Partially addressable&#8203;: 01 02 03 04 05 06 07
&nbsp;  Heap left redzone&#8203;:       fa
&nbsp;  Heap right redzone&#8203;:      fb
&nbsp;  Freed heap region&#8203;:       fd
&nbsp;  Stack left redzone&#8203;:      f1
&nbsp;  Stack mid redzone&#8203;:       f2
&nbsp;  Stack right redzone&#8203;:     f3
&nbsp;  Stack partial redzone&#8203;:   f4
&nbsp;  Stack after return&#8203;:      f5
&nbsp;  Stack use after scope&#8203;:   f8
&nbsp;  Global redzone&#8203;:          f9
&nbsp;  Global init order&#8203;:       f6
&nbsp;  Poisoned by user&#8203;:        f7
&nbsp;  Container overflow&#8203;:      fc
&nbsp;  Array cookie&#8203;:            ac
&nbsp;  Intra object redzone&#8203;:    bb
&nbsp;  ASan internal&#8203;:           fe
==3861==ABORTING


\-\- 
Regards\,
SRAUMS

**Comment by p5pRT** [comment]
### From sraums2498@gmail.com

[314](https://rt-archive.perl.org/perl5/Ticket/Attachment/1521231/813245/314)

**Comment by p5pRT** [comment]
### From @hvds

This reduces to&#8203;:
&nbsp;  \./miniperl \-e 's/\(?=\)/abcdefgh/; unpack "P"'
with the same stack trace\.

With warnings\, I note that the unpack is \_not\_ warning about an undef argument\.

I'll look more at this if nobody else gets there first&#8203;: I suspect the stack is getting out of sync somehow\.

Hugo

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @hvds

This is a minor variant of rt132654\, I'll merge them\.

Hugo

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue\, 09 Jan 2018 00&#8203;:40&#8203;:48 \-0800\, hv wrote&#8203;:
> This reduces to&#8203;:
>   \./miniperl \-e 's/\(?=\)/abcdefgh/; unpack "P"'
> with the same stack trace\.
> 
> With warnings\, I note that the unpack is \_not\_ warning about an undef
> argument\.
> 
> I'll look more at this if nobody else gets there first&#8203;: I suspect the
> stack is getting out of sync somehow\.

The s/// turns $\_ into "abcdefhg"\.

The unpack "P"\, which uses $\_ if no EXPR is supplied\, then attempts to use those bytes as a pointer\, which of course fails horribly\.

As the documentation in unpack says&#8203;:

&nbsp;            The "p" and "P" formats should be used with care\. Since Perl has
&nbsp;            no way of checking whether the value passed to "unpack"
&nbsp;            corresponds to a valid memory location\, passing a pointer value
&nbsp;            that's not known to be valid is likely to have disastrous
&nbsp;            consequences\.

Moving to the public queue \(it isn't a security issue\) and rejecting\.

Tony

**Comment by p5pRT** [comment]
@tonycoz - Status changed from 'open' to 'rejected'
