### ISSUE TITLE
Re: Null pointer dereference in Perl_pp_multiconcat

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16470]
Migrated from [rt.perl.org#132996](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132996) (status was 'open')

Searchable as RT132996$

**Comment by p5pRT** [comment]
### From jeremy@feusi.co

I just realized that I used the wrong perlbug\. But as I can't seem to
get the correct perlbug to run I'll just have to give yout the most
important facts manually&#8203;:
Configure command&#8203;:
\./Configure \-des \-Dusedevel \-Dcc=clang \-Dcxx=clang\+\+ \-Dld=clang\+\+
\-Aldflags=\-fsanitize=address \-Accflags=\-g3\\ \-fsanitize=address
\-Acxxflags=\-g3\\ \-fsanitize=address

Perl version&#8203;:
perl 5\, version 27\, subversion 10 built for x86\_64\-linux

Platform&#8203;:
Linux Debian 4\.9\.65\-3 x86\_64 GNU/Linux

Tell me if you need anything else\.

In\-Reply\-To&#8203;: \<5\.26\.1\_42062\_1521280686@&#8203;debian\-vm\.localdomain>

On Sat\, Mar 17\, 2018 at 11&#8203;:32&#8203;:37AM \+0100\, jeremy@&#8203;feusi\.co wrote&#8203;:
> 
> Reply\-To&#8203;: jeremy@&#8203;feusi\.co
> 
> 
> This is a bug report for perl from jeremy@&#8203;feusi\.co\,
> generated with the help of perlbug 1\.40 running under perl 5\.26\.1\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> Perl segfaults when executing the attached program \(perl \<progname>\) due to a null pointer dereference in Perl\_pp\_multiconcat\.
> This bug can also reproduced on archlinux and debian with standard installation configuration and version 5\.26\.1\.
> 
> Detailed backtrace&#8203;:
> 
> ASAN&#8203;:DEADLYSIGNAL
> =================================================================
> ==9327==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x00000000000c \(pc 0x00000084e5f2 bp 0x7ffeed336030 sp 0x7ffeed335a40 T0\)
> ==9327==The signal is caused by a READ memory access\.
> ==9327==Hint&#8203;: address points to the zero page\.
>     \#0 0x84e5f1 in Perl\_pp\_multiconcat /home/jfe/perl52/pp\_hot\.c
>     \#1 0x8488be in Perl\_runops\_standard /home/jfe/perl52/run\.c&#8203;:41&#8203;:26
>     \#2 0xa95bf6 in S\_regmatch /home/jfe/perl52/regexec\.c&#8203;:7424&#8203;:3
>     \#3 0xa74ea0 in S\_regtry /home/jfe/perl52/regexec\.c&#8203;:4086&#8203;:14
>     \#4 0xa57204 in Perl\_regexec\_flags /home/jfe/perl52/regexec\.c&#8203;:3943&#8203;:7
>     \#5 0x877ab1 in Perl\_pp\_subst /home/jfe/perl52/pp\_hot\.c&#8203;:4212&#8203;:10
>     \#6 0x8488be in Perl\_runops\_standard /home/jfe/perl52/run\.c&#8203;:41&#8203;:26
>     \#7 0x5dbc91 in S\_run\_body /home/jfe/perl52/perl\.c
>     \#8 0x5dabb4 in perl\_run /home/jfe/perl52/perl\.c&#8203;:2646&#8203;:2
>     \#9 0x52f0b8 in main /home/jfe/perl52/perlmain\.c&#8203;:122&#8203;:9
>     \#10 0x7fe328886f29 in \_\_libc\_start\_main \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x20f29\)
>     \#11 0x43f999 in \_start \(/home/jfe/perl52/perl\+0x43f999\)
> 
> AddressSanitizer can not provide additional info\.
> SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /home/jfe/perl52/pp\_hot\.c in Perl\_pp\_multiconcat
> ==9327==ABORTING
> 
> This bug was found with honggfuzz and asan\.
> 
> 
> \[Please do not change anything below this line\]
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \-\-\-
> Flags&#8203;:
>     category=core
>     severity=high
> \-\-\-
> Site configuration information for perl 5\.26\.1&#8203;:
> 
> Configured by Debian at Fri Jan 12 19&#8203;:31&#8203;:09 UTC 2018\.
> 
> Summary of my perl5 \(revision 5 version 26 subversion 1\) configuration&#8203;:
>    
>   Platform&#8203;:
>     osname=linux
>     osvers=4\.9\.0
>     archname=x86\_64\-linux\-gnu\-thread\-multi
>     uname='linux localhost 4\.9\.0 \#1 smp debian 4\.9\.0 x86\_64 gnulinux '
>     config\_args='\-Dusethreads \-Duselargefiles \-Dcc=x86\_64\-linux\-gnu\-gcc \-Dcpp=x86\_64\-linux\-gnu\-cpp \-Dld=x86\_64\-linux\-gnu\-gcc \-Dccflags=\-DDEBIAN \-Wdate\-time \-D\_FORTIFY\_SOURCE=2 \-g \-O2 \-fdebug\-prefix\-map=/build/perl\-awpeXx/perl\-5\.26\.1=\. \-fstack\-protector\-strong \-Wformat \-Werror=format\-security \-Dldflags= \-Wl\,\-z\,relro \-Dlddlflags=\-shared \-Wl\,\-z\,relro \-Dcccdlflags=\-fPIC \-Darchname=x86\_64\-linux\-gnu \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.26 \-Darchlib=/usr/lib/x86\_64\-linux\-gnu/perl/5\.26 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/x86\_64\-linux\-gnu/perl5/5\.26 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.26\.1 \-Dsitearch=/usr/local/lib/x86\_64\-linux\-gnu/perl/5\.26\.1 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1 \-Dsiteman3dir=/usr/local/man/man3 \-Duse64bitint \-Dman1ext=1 \-Dman3ext=3perl
> \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Ud\_ualarm \-Uusesfio \-Uusenm \-Ui\_libutil \-Ui\_xlocale \-Uversiononly \-DDEBUGGING=\-g \-Doptimize=\-O2 \-dEs \-Duseshrplib \-Dlibperl=libperl\.so\.5\.26\.1'
>     hint=recommended
>     useposix=true
>     d\_sigaction=define
>     useithreads=define
>     usemultiplicity=define
>     use64bitint=define
>     use64bitall=define
>     uselongdouble=undef
>     usemymalloc=n
>     default\_inc\_excludes\_dot=define
>     bincompat5005=undef
>   Compiler&#8203;:
>     cc='x86\_64\-linux\-gnu\-gcc'
>     ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fwrapv \-fno\-strict\-aliasing \-pipe \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'
>     optimize='\-O2 \-g'
>     cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fwrapv \-fno\-strict\-aliasing \-pipe \-I/usr/local/include'
>     ccversion=''
>     gccversion='7\.2\.0'
>     gccosandvers=''
>     intsize=4
>     longsize=8
>     ptrsize=8
>     doublesize=8
>     byteorder=12345678
>     doublekind=3
>     d\_longlong=define
>     longlongsize=8
>     d\_longdbl=define
>     longdblsize=16
>     longdblkind=3
>     ivtype='long'
>     ivsize=8
>     nvtype='double'
>     nvsize=8
>     Off\_t='off\_t'
>     lseeksize=8
>     alignbytes=8
>     prototype=define
>   Linker and Libraries&#8203;:
>     ld='x86\_64\-linux\-gnu\-gcc'
>     ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
>     libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/7/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
>     libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
>     perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
>     libc=libc\-2\.26\.so
>     so=so
>     useshrplib=true
>     libperl=libperl\.so\.5\.26
>     gnulibc\_version='2\.26'
>   Dynamic Linking&#8203;:
>     dlsrc=dl\_dlopen\.xs
>     dlext=so
>     d\_dlsymun=undef
>     ccdlflags='\-Wl\,\-E'
>     cccdlflags='\-fPIC'
>     lddlflags='\-shared \-L/usr/local/lib \-fstack\-protector\-strong'
> 
> Locally applied patches&#8203;:
>     DEBPKG&#8203;:debian/cpan\_definstalldirs \- Provide a sensible INSTALLDIRS default for modules installed from CPAN\.
>     DEBPKG&#8203;:debian/db\_file\_ver \- https://bugs.debian.org/340047 Remove overly restrictive DB\_File version check\.
>     DEBPKG&#8203;:debian/doc\_info \- Replace generic man\(1\) instructions with Debian\-specific information\.
>     DEBPKG&#8203;:debian/enc2xs\_inc \- https://bugs.debian.org/290336 Tweak enc2xs to follow symlinks and ignore missing @&#8203;INC directories\.
>     DEBPKG&#8203;:debian/errno\_ver \- https://bugs.debian.org/343351 Remove Errno version check due to upgrade problems with long\-running processes\.
>     DEBPKG&#8203;:debian/libperl\_embed\_doc \- https://bugs.debian.org/186778 Note that libperl\-dev package is required for embedded linking
>     DEBPKG&#8203;:fixes/respect\_umask \- Respect umask during installation
>     DEBPKG&#8203;:debian/writable\_site\_dirs \- Set umask approproately for site install directories
>     DEBPKG&#8203;:debian/extutils\_set\_libperl\_path \- EU&#8203;:MM&#8203;: set location of libperl\.a under /usr/lib
>     DEBPKG&#8203;:debian/no\_packlist\_perllocal \- Don't install \.packlist or perllocal\.pod for perl or vendor
>     DEBPKG&#8203;:debian/fakeroot \- Postpone LD\_LIBRARY\_PATH evaluation to the binary targets\.
>     DEBPKG&#8203;:debian/instmodsh\_doc \- Debian policy doesn't install \.packlist files for core or vendor\.
>     DEBPKG&#8203;:debian/ld\_run\_path \- Remove standard libs from LD\_RUN\_PATH as per Debian policy\.
>     DEBPKG&#8203;:debian/libnet\_config\_path \- Set location of libnet\.cfg to /etc/perl/Net as /usr may not be writable\.
>     DEBPKG&#8203;:debian/perlivp \- https://bugs.debian.org/510895 Make perlivp skip include directories in /usr/local
>     DEBPKG&#8203;:debian/deprecate\-with\-apt \- https://bugs.debian.org/747628 Point users to Debian packages of deprecated core modules
>     DEBPKG&#8203;:debian/squelch\-locale\-warnings \- https://bugs.debian.org/508764 Squelch locale warnings in Debian package maintainer scripts
>     DEBPKG&#8203;:debian/patchlevel \- https://bugs.debian.org/567489 List packaged patches for 5\.26\.1\-4 in patchlevel\.h
>     DEBPKG&#8203;:fixes/document\_makemaker\_ccflags \- https://bugs.debian.org/628522 \[rt\.cpan\.org \#68613\] Document that CCFLAGS should include $Config\{ccflags\}
>     DEBPKG&#8203;:debian/find\_html2text \- https://bugs.debian.org/640479 Configure CPAN&#8203;::Distribution with correct name of html2text
>     DEBPKG&#8203;:debian/perl5db\-x\-terminal\-emulator\.patch \- https://bugs.debian.org/668490 Invoke x\-terminal\-emulator rather than xterm in perl5db\.pl
>     DEBPKG&#8203;:debian/cpan\-missing\-site\-dirs \- https://bugs.debian.org/688842 Fix CPAN&#8203;::FirstTime defaults with nonexisting site dirs if a parent is writable
>     DEBPKG&#8203;:fixes/memoize\_storable\_nstore \- \[rt\.cpan\.org \#77790\] https://bugs.debian.org/587650 Memoize&#8203;::Storable&#8203;: respect 'nstore' option not respected
>     DEBPKG&#8203;:debian/makemaker\-pasthru \- https://bugs.debian.org/758471 Pass LD settings through to subdirectories
>     DEBPKG&#8203;:debian/makemaker\-manext \- https://bugs.debian.org/247370 Make EU&#8203;::MakeMaker honour MANnEXT settings in generated manpage headers
>     DEBPKG&#8203;:debian/kfreebsd\-softupdates \- https://bugs.debian.org/796798 Work around Debian Bug\#796798
>     DEBPKG&#8203;:fixes/autodie\-scope \- https://bugs.debian.org/798096 Fix a scoping issue with "no autodie" and the "system" sub
>     DEBPKG&#8203;:fixes/memoize\-pod \- \[rt\.cpan\.org \#89441\] Fix POD errors in Memoize
>     DEBPKG&#8203;:debian/hurd\-softupdates \- https://bugs.debian.org/822735 Fix t/op/stat\.t failures on hurd
>     DEBPKG&#8203;:fixes/math\_complex\_doc\_great\_circle \- https://bugs.debian.org/697567 \[rt\.cpan\.org \#114104\] Math&#8203;::Trig&#8203;: clarify definition of great\_circle\_midpoint
>     DEBPKG&#8203;:fixes/math\_complex\_doc\_see\_also \- https://bugs.debian.org/697568 \[rt\.cpan\.org \#114105\] Math&#8203;::Trig&#8203;: add missing SEE ALSO
>     DEBPKG&#8203;:fixes/math\_complex\_doc\_angle\_units \- https://bugs.debian.org/731505 \[rt\.cpan\.org \#114106\] Math&#8203;::Trig&#8203;: document angle units
>     DEBPKG&#8203;:fixes/cpan\_web\_link \- https://bugs.debian.org/367291 CPAN&#8203;: Add link to main CPAN web site
>     DEBPKG&#8203;:fixes/time\_piece\_doc \- https://bugs.debian.org/817925 Time&#8203;::Piece&#8203;: Improve documentation for add\_months and add\_years
>     DEBPKG&#8203;:fixes/extutils\_makemaker\_reproducible \- https&#8203;://bugs\.debian\.org/835815 https://bugs.debian.org/834190 Make perllocal\.pod files reproducible
>     DEBPKG&#8203;:fixes/file\_path\_hurd\_errno \- File\-Path&#8203;: Fix test failure in Hurd due to hard\-coded ENOENT
>     DEBPKG&#8203;:debian/hppa\_op\_optimize\_workaround \- https://bugs.debian.org/838613 Temporarily lower the optimization of op\.c on hppa due to gcc\-6 problems
>     DEBPKG&#8203;:debian/installman\-utf8 \- https://bugs.debian.org/840211 Generate man pages with UTF\-8 characters
>     DEBPKG&#8203;:fixes/file\_path\_chmod\_race \- https://bugs.debian.org/863870 \[rt\.cpan\.org \#121951\] Prevent directory chmod race attack\.
>     DEBPKG&#8203;:fixes/extutils\_file\_path\_compat \- Correct the order of tests of chmod\(\)\. \(\#294\)
>     DEBPKG&#8203;:fixes/getopt\-long\-2 \- \[rt\.cpan\.org \#120300\] Withdraw part of commit 5d9947fb445327c7299d8beb009d609bc70066c0\, which tries to implement more GNU getopt\_long campatibility\. GNU
>     DEBPKG&#8203;:fixes/getopt\-long\-3 \- provide a default value for optional arguments
>     DEBPKG&#8203;:fixes/getopt\-long\-4 \- https://bugs.debian.org/864544 \[rt\.cpan\.org \#122068\] Fix issue \#122068\.
>     DEBPKG&#8203;:fixes/test\-builder\-reset \- https://bugs.debian.org/865894 Reset inside subtest maintains parent
>     DEBPKG&#8203;:debian/hppa\_opmini\_optimize\_workaround \- https://bugs.debian.org/869122 Lower the optimization level of opmini\.c on hppa
>     DEBPKG&#8203;:debian/sh4\_op\_optimize\_workaround \- https://bugs.debian.org/869373 Also lower the optimization level of op\.c and opmini\.c on sh4
>     DEBPKG&#8203;:fixes/json\-pp\-example \- \[rt\.cpan\.org \#92793\] https://bugs.debian.org/871837 fix RT\-92793&#8203;: bug in SYNOPSIS
>     DEBPKG&#8203;:debian/perldoc\-pager \- https://bugs.debian.org/870340 \[rt\.cpan\.org \#120229\] Fix perldoc terminal escapes when sensible\-pager is less
>     DEBPKG&#8203;:debian/prune\_libs \- https://bugs.debian.org/128355 Prune the list of libraries wanted to what we actually need\.
>     DEBPKG&#8203;:debian/configure\-regen \- https://bugs.debian.org/762638 Regenerate Configure et al\. after probe unit changes
>     DEBPKG&#8203;:fixes/rename\-filexp\.U\-phase1 \- regen\-configure&#8203;: rename filexp\.U to filexp\_path\.U\, phase 1
>     DEBPKG&#8203;:fixes/rename\-filexp\.U\-phase2 \- regen\-configure&#8203;: rename filexp\.U to filexp\_path\.U\, phase 2
>     DEBPKG&#8203;:fixes/packaging\_test\_skips \- Skip various tests if PERL\_BUILD\_PACKAGING is set
>     DEBPKG&#8203;:debian/mod\_paths \- Tweak @&#8203;INC ordering for Debian
>     DEBPKG&#8203;:fixes/encode\-alias\-regexp \- https&#8203;://bugs\.debian\.org/880085 fix https://github.com/dankogai/p5-encode/issues/127
> 
> \-\-\-
> @&#8203;INC for perl 5\.26\.1&#8203;:
>     /etc/perl
>     /usr/local/lib/x86\_64\-linux\-gnu/perl/5\.26\.1
>     /usr/local/share/perl/5\.26\.1
>     /usr/lib/x86\_64\-linux\-gnu/perl5/5\.26
>     /usr/share/perl5
>     /usr/lib/x86\_64\-linux\-gnu/perl/5\.26
>     /usr/share/perl/5\.26
>     /usr/local/lib/site\_perl
>     /usr/lib/x86\_64\-linux\-gnu/perl\-base
> 
> \-\-\-
> Environment for perl 5\.26\.1&#8203;:
>     HOME=/home/jfe
>     LANG=en\_US\.UTF\-8
>     LANGUAGE=en\_US\.UTF\-8
>     LC\_ADDRESS=de\_CH\.UTF\-8
>     LC\_ALL=en\_US\.UTF\-8
>     LC\_COLLATE=de\_CH\.UTF\-8
>     LC\_IDENTIFICATION=de\_CH\.UTF\-8
>     LC\_MEASUREMENT=de\_CH\.UTF\-8
>     LC\_MESSAGES=en\_US\.UTF\-8
>     LC\_MONETARY=de\_CH\.UTF\-8
>     LC\_NAME=de\_CH\.UTF\-8
>     LC\_NUMERIC=de\_CH\.UTF\-8
>     LC\_PAPER=de\_CH\.UTF\-8
>     LC\_TELEPHONE=de\_CH\.UTF\-8
>     LC\_TIME=en\_DK\.UTF\-8
>     LD\_LIBRARY\_PATH \(unset\)
>     LOGDIR \(unset\)
>     PATH=/home/jfe/\.cargo/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/local/games&#8203;:/usr/games
>     PERL\_BADLANG \(unset\)
>     SHELL=/bin/bash

> \#\!\./perl
> m/\(?\{print \<\<EOF
> A$A
> EOF
> \}\)/g;
> eval 's/$\{\\%A\}\{3\}//e';
>

**Comment by p5pRT** [comment]
### From @shlomif

Hi all\!

Here is the program&#8203;:

\<\<\<\<\<

\#\!\./perl
m/\(?\{print \<\<EOF
A$A
EOF
\}\)/g;
eval 's/$\{\\%A\}\{3\}//e';

>>>>>

it segfaults both /usr/bin/perl and bleadperl on my mageia v7 x64 system\.

Regards\,

&nbsp;    Shlomi Fish

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @shlomif



Begin forwarded message&#8203;:

Date&#8203;: Fri\, 23 Mar 2018 09&#8203;:20&#8203;:54 \+0000
From&#8203;: Dave Mitchell \<davem@&#8203;iabyn\.com>
To&#8203;: Shlomi Fish \<shlomif@&#8203;shlomifish\.org>
Subject&#8203;: Re&#8203;: \[perl \#132996\] Re&#8203;: Null pointer dereference in Perl\_pp\_multiconcat


On Fri\, Mar 23\, 2018 at 10&#8203;:46&#8203;:52AM \+0300\, Shlomi Fish wrote&#8203;:
> Hi all\!
> 
> Here is the program&#8203;:
> 
> \<\<\<\<\<
> 
> \#\!\./perl
> m/\(?\{print \<\<EOF
> A$A
> EOF
> \}\)/g;
> eval 's/$\{\\%A\}\{3\}//e';
>   
> >>>>>  
> 
> it segfaults both /usr/bin/perl and bleadperl on my mageia v7 x64 system\.  

It can be reduced further to

&nbsp;    my $a="";
&nbsp;    m/\(?\{"A$a"\}\)/;
&nbsp;    eval 'm//';


It's something to do with the 'use last successful match' behaviour of
m//; when the code block in the regex is executed for a second time\,
it looks like the wrong pad is in use and padsv\($a\) returns a null
pointer or other garbage\.

The bug is present back to at least 5\.8\.9\, so its \(fortunately\) not a
regression introduced by pp\_multiconcat\.


\-\- 
The optimist believes that he lives in the best of all possible worlds\.
As does the pessimist\.


\-\- 


---
Shlomi Fish       http&#8203;://www\.shlomifish\.org/
Stop Using MSIE \- http&#8203;://www\.shlomifish\.org/no\-ie/

Buffy Summers does not really need stakes to slay vampires\, because her kisses
are deadly for them\. And that includes those that she blows in the air\.
&nbsp;    — http&#8203;://www\.shlomifish\.org/humour/bits/facts/Buffy/

Please reply to list if it's a mailing list post \- http&#8203;://shlom\.in/reply \.
