### ISSUE TITLE
SEGV using a regex with an invalid repeat range

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16503]
Migrated from [rt.perl.org#133100](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133100) (status was 'resolved')

Searchable as RT133100$

**Comment by p5pRT** [comment]
### From Nick_Russell@McAfee.com

This is a bug report for perl from Nick Rrussell\,
generated with the help of perlbug 1\.39 running under perl 5\.26\.1\.



---
The following command&#8203;:

\# echo 'b' | perl \-ne 'print if /ba\{11\,2\}/;'

when executed under perl v5\.16\.3 produces the error below&#8203;:

Can't do \{n\,m\} with n > m in regex; marked by \<\-\- HERE in m/ba\{11\,2\} \<\-\- HERE / at \-e line 1\.

which is expected\. However when run under perl v5\.26\.1 the regex is considered valid and crashes perl when the range is evaluated&#8203;:

Core was generated by \`perl \-ne print if /ba\{11\,2\}/;'\.
Program terminated with signal 11\, Segmentation fault\.
\(gdb\) bt
\#0  0x00007efe26ddba24 in ?? \(\) from /usr/lib/perl5/core\_perl/CORE/libperl\.so
\#1  0x00007efe26de15f8 in Perl\_regexec\_flags \(\) from /usr/lib/perl5/core\_perl/CORE/libperl\.so
\#2  0x00007efe26d85a46 in Perl\_pp\_match \(\) from /usr/lib/perl5/core\_perl/CORE/libperl\.so
\#3  0x00007efe26d8219b in Perl\_runops\_standard \(\) from /usr/lib/perl5/core\_perl/CORE/libperl\.so
\#4  0x00007efe26d1d035 in perl\_run \(\) from /usr/lib/perl5/core\_perl/CORE/libperl\.so
\#5  0x0000557ea61a6c42 in main \(\)

Note that I was using a chroot that did not have perlbug installed so I used the version available under the host OS so the ' Locally applied patches' section is bogus\.


---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=high


---
This perlbug was built using Perl 5\.16\.3 \- Wed Aug  2 17&#8203;:44&#8203;:15 UTC 2017
It is being executed now by  Perl 5\.26\.1 \- Tue Oct 31 13&#8203;:26&#8203;:34 GMT 2017\.

Site configuration information for perl 5\.26\.1&#8203;:

Configured by Alpine at Tue Oct 31 13&#8203;:26&#8203;:34 GMT 2017\.

Summary of my perl5 \(revision 5 version 26 subversion 1\) configuration&#8203;:

&nbsp;  Platform&#8203;:
&nbsp;    osname=linux
&nbsp;    osvers=4\.4\.45\-0\-grsec
&nbsp;    archname=x86\_64\-linux\-thread\-multi
&nbsp;    uname='linux build\-3\-7\-x86\_64 4\.4\.45\-0\-grsec \#1\-alpine smp thu jan 26 14&#8203;:21&#8203;:00 gmt 2017 x86\_64 linux '
&nbsp;    config\_args='\-des \-Dcccdlflags=\-fPIC \-Dcccdlflags=\-fPIC \-Dccdlflags=\-rdynamic \-Dprefix=/usr \-Dprivlib=/usr/share/perl5/core\_perl \-Darchlib=/usr/lib/perl5/core\_perl \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5/vendor\_perl \-Dvendor
arch=/usr/lib/perl5/vendor\_perl \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl5/site\_perl \-Dsitearch=/usr/local/lib/perl5/site\_perl \-Dlocincpth=  \-Doptimize=\-Os \-fomit\-frame\-pointer \-Duselargefiles \-Dusethreads \-Duseshrplib \-Dd\_
semctl\_semun \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dinstallman1dir=/usr/share/man/man1 \-Dinstallman3dir=/usr/share/man/man3 \-Dman1ext=1 \-Dman3ext=3pm \-Dcf\_by=Alpine \-Ud\_csh \-Dusenm'
&nbsp;    hint=recommended
&nbsp;    useposix=true
&nbsp;    d\_sigaction=define
&nbsp;    useithreads=define
&nbsp;    usemultiplicity=define
&nbsp;    use64bitint=define
&nbsp;    use64bitall=define
&nbsp;    uselongdouble=undef
&nbsp;    usemymalloc=n
&nbsp;    default\_inc\_excludes\_dot=define
&nbsp;    bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'
&nbsp;    ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'
&nbsp;    optimize='\-Os \-fomit\-frame\-pointer'
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong'
&nbsp;    ccversion=''
&nbsp;    gccversion='6\.4\.0'
&nbsp;    gccosandvers=''
&nbsp;    intsize=4
&nbsp;    longsize=8
&nbsp;    ptrsize=8
&nbsp;    doublesize=8
&nbsp;    byteorder=12345678
&nbsp;    doublekind=3
&nbsp;    d\_longlong=define
&nbsp;    longlongsize=8
&nbsp;    d\_longdbl=define
&nbsp;    longdblsize=16
&nbsp;    longdblkind=3
&nbsp;    ivtype='long'
&nbsp;    ivsize=8
&nbsp;    nvtype='double'
&nbsp;    nvsize=8
&nbsp;    Off\_t='off\_t'
&nbsp;    lseeksize=8
&nbsp;    alignbytes=8
&nbsp;    prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'
&nbsp;    ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/include/fortify /usr/lib /usr/local/lib /lib/\.\./lib /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lpthread \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=/usr/lib/libc\.a
&nbsp;    so=so
&nbsp;    useshrplib=true
&nbsp;    libperl=libperl\.so
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs
&nbsp;    dlext=so
&nbsp;    d\_dlsymun=undef
&nbsp;    ccdlflags='\-rdynamic \-Wl\,\-rpath\,/usr/lib/perl5/core\_perl/CORE'
&nbsp;    cccdlflags='\-fPIC'
&nbsp;    lddlflags='\-shared \-Os \-fomit\-frame\-pointer \-L/usr/local/lib \-fstack\-protector\-strong'

Locally applied patches&#8203;:
&nbsp;    Fedora Patch1&#8203;: Removes date check\, Fedora/RHEL specific
&nbsp;    Fedora Patch3&#8203;: support for libdir64
&nbsp;    Fedora Patch4&#8203;: use libresolv instead of libbind
&nbsp;    Fedora Patch5&#8203;: USE\_MM\_LD\_RUN\_PATH
&nbsp;    Fedora Patch6&#8203;: Skip hostname tests\, due to builders not being network capable
&nbsp;    Fedora Patch7&#8203;: Dont run one io test due to random builder failures
&nbsp;    Fedora Patch9&#8203;: Fix find2perl to translate ? glob properly \(RT\#113054\)
&nbsp;    Fedora Patch10&#8203;: Fix broken atof \(RT\#109318\)
&nbsp;    Fedora Patch13&#8203;: Clear $@&#8203; before \\"do\\" I/O error \(RT\#113730\)
&nbsp;    Fedora Patch14&#8203;: Do not truncate syscall\(\) return value to 32 bits \(RT\#113980\)
&nbsp;    Fedora Patch15&#8203;: Override the Pod&#8203;::Simple&#8203;::parse\_file \(CPANRT\#77530\)
&nbsp;    Fedora Patch16&#8203;: Do not leak with attribute on my variable \(RT\#114764\)
&nbsp;    Fedora Patch17&#8203;: Allow operator after numeric keyword argument \(RT\#105924\)
&nbsp;    Fedora Patch18&#8203;: Extend stack in File&#8203;::Glob&#8203;::glob\, \(RT\#114984\)
&nbsp;    Fedora Patch19&#8203;: Do not crash when vivifying $|
&nbsp;    Fedora Patch20&#8203;: Fix misparsing of maketext strings \(CVE\-2012\-6329\)
&nbsp;    Fedora Patch21&#8203;: Add NAME headings to CPAN modules \(CPANRT\#73396\)
&nbsp;    Fedora Patch22&#8203;: Fix leaking tied hashes \(RT\#107000\) \[1\]
&nbsp;    Fedora Patch23&#8203;: Fix leaking tied hashes \(RT\#107000\) \[2\]
&nbsp;    Fedora Patch24&#8203;: Fix leaking tied hashes \(RT\#107000\) \[3\]
&nbsp;    Fedora Patch25&#8203;: Fix dead lock in PerlIO after fork from thread \(RT\#106212\)
&nbsp;    Fedora Patch26&#8203;: Make regexp safe in a signal handler \(RT\#114878\)
&nbsp;    Fedora Patch27&#8203;: Update h2ph\(1\) documentation \(RT\#117647\)
&nbsp;    Fedora Patch28&#8203;: Update pod2html\(1\) documentation \(RT\#117623\)
&nbsp;    Fedora Patch29&#8203;: Document Math&#8203;::BigInt&#8203;::CalcEmu requires Math&#8203;::BigInt \(CPAN RT\#85015\)
&nbsp;    RHEL Patch30&#8203;: Use stronger algorithm needed for FIPS in t/op/crypt\.t \(RT\#121591\)
&nbsp;    RHEL Patch31&#8203;: Make \*DBM\_File desctructors thread\-safe \(RT\#61912\)
&nbsp;    RHEL Patch32&#8203;: Use stronger algorithm needed for FIPS in t/op/taint\.t \(RT\#123338\)
&nbsp;    RHEL Patch33&#8203;: Remove CPU\-speed\-sensitive test in Benchmark test
&nbsp;    RHEL Patch34&#8203;: Make File&#8203;::Glob work with threads again
&nbsp;    RHEL Patch35&#8203;: Fix CRLF conversion in ASCII FTP upload \(CPAN RT\#41642\)
&nbsp;    RHEL Patch36&#8203;: Do not leak the temp utf8 copy of namepv \(CPAN RT\#123786\)
&nbsp;    RHEL Patch37&#8203;: Fix duplicating PerlIO&#8203;::encoding when spawning threads \(RT\#31923\)



---
@&#8203;INC for perl 5\.26\.1&#8203;:
&nbsp;    /usr/local/lib/perl5/site\_perl
&nbsp;    /usr/local/share/perl5/site\_perl
&nbsp;    /usr/lib/perl5/vendor\_perl
&nbsp;    /usr/share/perl5/vendor\_perl
&nbsp;    /usr/lib/perl5/core\_perl
&nbsp;    /usr/share/perl5/core\_perl



---
Environment for perl 5\.26\.1&#8203;:
&nbsp;    HOME=/root
&nbsp;    LANG=en\_GB\.UTF\-8
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/sbin&#8203;:/bin&#8203;:/usr/sbin&#8203;:/usr/bin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

The information contained in this email message may be privileged\, confidential and protected from disclosure\. If you are not the intended recipient\, any review\, dissemination\, distribution or copying is strictly prohibited\. If you have received this email message in error\, please notify the sender by reply email and delete the message and any attachments\.

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

McAfee Security UK Limited is registered in England and Wales with its registered address at C/O Skadden\, Arps\, Slate\, Meagher & Flom \(UK\) LLP\, 40 Bank Street\, Canary Wharf\, London\, United Kingdom\, E14 5DS\, Company No\. 10472868

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for your report

This is already fixed in blead\, and hence for 5\.28\.  It was fixed by this commit
commit 4dc12118f61b997fbd030230665b46e7c40f32d6
Author&#8203;: Yves Orton \<demerphq@&#8203;gmail\.com>
Date&#8203;:   Sun Sep 10 10&#8203;:59&#8203;:05 2017 \+0200

&nbsp;    fix \#132017 \- OPFAIL insert needs to set flags to 0
&nbsp;    
&nbsp;    why reginsert doesnt do this stuff I dont know\.

I believe tThis would be a candidate for backporting into the 5\.26 maintenance release series\.

The commit that broke it in 5\.26 is

commit 31fc93954d1f379c7a49889d91436ce99818e1f6
Author&#8203;: Yves Orton \<demerphq@&#8203;gmail\.com>
Date&#8203;:   Fri Jan 27 10&#8203;:18&#8203;:51 2017 \+0100

&nbsp;    fix RT \#130561 \- recursion and optimising away impossible quantifiers are not friends
&nbsp;    
&nbsp;    Instead of optimising away impossible quantifiers like \(foo\)\{1\,0\} treat them
&nbsp;    as unquantified\, and guard them with an OPFAIL\. Thus /\(foo\)\{1\,0\}/ is treated
&nbsp;    the same as /\(\*FAIL\)\(foo\)/ this is important in patterns like /\(foo\)\{1\,0\}|\(?1\)/
&nbsp;    where the \(?1\) needs to be able to recurse into the \(foo\) even though the
&nbsp;    \(foo\)\{1\,0\} can never match\. It also resolves various issues \(SEGVs\) with patterns
&nbsp;    like /\(\(?1\)\)\{1\,0\}/\.
&nbsp;    
&nbsp;    This patch would have been easier if S\_reginsert\(\) documented that it is
&nbsp;    the callers responsibility to properly set up the NEXT\_OFF\(\) of the inserted
&nbsp;    node \(if the node has a NEXT\_OFF\(\)\)

\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @khwilliamson

And it turns out that this fix is already in 5\.26\.2\, which is scheduled for release in 3 days\, unless something delays it\.
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

I meant it would be fixed in 5\.26\.2\, which was released on schedule\, and is now available
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release yesterday of Perl 5\.28\.0\, this and 185 other issues have been
resolved\.

Perl 5\.28\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.28.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
