### ISSUE TITLE
B::CC cannot sort

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#1659]
Migrated from [rt.perl.org#2900](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=2900) (status was 'resolved')

Searchable as RT2900$

**Comment by p5pRT** [comment]
This simple program:
```perl
for $k (sort { length $ENV{$b} <=> length $ENV{$a} } keys %ENV) {
print "$k=$ENV{$k}\n";
}
```

Under B::Bytecode, produces correct results, then SEGVs

Under B::C, produces correct results, then exits correctly.

Under B::CC, produces no results, but goes into recursive
doom in the sort, eventually SEGVing for lack of memory
in stack death.

--tom
```
#0 0x4015825e in tcgetattr ()
#1 0x40158535 in tcgetattr ()
#2 0x40158d6b in malloc ()
#3 0x40061e50 in Perl_safemalloc ()
#4 0x40076cd3 in S_more_xpv ()
#5 0x40076c7c in S_new_xpv ()
#6 0x400775f1 in L273 ()
#7 0x4007adfd in Perl_sv_setpvn ()
#8 0x4007ddd6 in Perl_newSVpvn ()
#9 0x4006d160 in Perl_hv_iterkeysv ()
#10 0x400aa655 in Perl_do_kv ()
#11 0x4008926c in Perl_pp_keys ()
#12 0x69e0 in pp_main () at /tmp/sort.p.c:1152
#13 0x4006f719 in Perl_runops_standard ()
#14 0x4009b6bd in sortcv ()
#15 0x4009ae99 in S_qsortsv ()
#16 0x40093590 in Perl_pp_sort ()
#17 0x6a0f in pp_main () at /tmp/sort.p.c:1155
#18 0x4006f719 in Perl_runops_standard ()
#19 0x4009b6bd in sortcv ()
#20 0x4009ae99 in S_qsortsv ()
#21 0x40093590 in Perl_pp_sort ()
#22 0x6a0f in pp_main () at /tmp/sort.p.c:1155
#23 0x4006f719 in Perl_runops_standard ()
#24 0x4009b6bd in sortcv ()
#25 0x4009ae99 in S_qsortsv ()
#26 0x40093590 in Perl_pp_sort ()
#27 0x6a0f in pp_main () at /tmp/sort.p.c:1155
#28 0x4006f719 in Perl_runops_standard ()
#29 0x4009b6bd in sortcv ()
#30 0x4009ae99 in S_qsortsv ()
#31 0x40093590 in Perl_pp_sort ()
#32 0x6a0f in pp_main () at /tmp/sort.p.c:1155
#33 0x4006f719 in Perl_runops_standard ()
#34 0x4009b6bd in sortcv ()
#35 0x4009ae99 in S_qsortsv ()
#36 0x40093590 in Perl_pp_sort ()
#37 0x6a0f in pp_main () at /tmp/sort.p.c:1155
#38 0x4006f719 in Perl_runops_standard ()
#39 0x4009b6bd in sortcv ()
#40 0x4009ae99 in S_qsortsv ()
#41 0x40093590 in Perl_pp_sort ()
#42 0x6a0f in pp_main () at /tmp/sort.p.c:1155
#43 0x4006f719 in Perl_runops_standard ()
#44 0x4009b6bd in sortcv ()
#45 0x4009ae99 in S_qsortsv ()
#46 0x40093590 in Perl_pp_sort ()
#47 0x6a0f in pp_main () at /tmp/sort.p.c:1155
#48 0x4006f719 in Perl_runops_standard ()
#49 0x4009b6bd in sortcv ()
#50 0x4009ae99 in S_qsortsv ()
#51 0x40093590 in Perl_pp_sort ()
#52 0x6a0f in pp_main () at /tmp/sort.p.c:1155
#53 0x4006f719 in Perl_runops_standard ()
#54 0x4009b6bd in sortcv ()
#55 0x4009ae99 in S_qsortsv ()
#56 0x40093590 in Perl_pp_sort ()
#57 0x6a0f in pp_main () at /tmp/sort.p.c:1155
#58 0x4006f719 in Perl_runops_standard ()
#59 0x4009b6bd in sortcv ()
#60 0x4009ae99 in S_qsortsv ()
#61 0x40093590 in Perl_pp_sort ()
#62 0x6a0f in pp_main () at /tmp/sort.p.c:1155
#63 0x4006f719 in Perl_runops_standard ()

[the following 25000 identical stackframes deleted]
```

**Comment by p5pRT** [comment]
### From tchrist@chthon.perl.com

This simple program&#8203;:

&nbsp;    for $k \(sort \{ length $ENV\{$b\} \<=> length $ENV\{$a\} \} keys %ENV\) \{
&nbsp;    print "$k=$ENV\{$k\}\\n";
&nbsp;    \} 

Under B&#8203;::Bytecode\, produces correct results\, then SEGVs

Under B&#8203;::C\, produces correct results\, then exits correctly\.

Under B&#8203;::CC\, produces no results\, but goes into recursive 
&nbsp;    doom in the sort\, eventually SEGVing for lack of memory
&nbsp;    in stack death\.

\-\-tom

\#0  0x4015825e in tcgetattr \(\)
\#1  0x40158535 in tcgetattr \(\)
\#2  0x40158d6b in malloc \(\)
\#3  0x40061e50 in Perl\_safemalloc \(\)
\#4  0x40076cd3 in S\_more\_xpv \(\)
\#5  0x40076c7c in S\_new\_xpv \(\)
\#6  0x400775f1 in L273 \(\)
\#7  0x4007adfd in Perl\_sv\_setpvn \(\)
\#8  0x4007ddd6 in Perl\_newSVpvn \(\)
\#9  0x4006d160 in Perl\_hv\_iterkeysv \(\)
\#10 0x400aa655 in Perl\_do\_kv \(\)
\#11 0x4008926c in Perl\_pp\_keys \(\)
\#12 0x69e0 in pp\_main \(\) at /tmp/sort\.p\.c&#8203;:1152
\#13 0x4006f719 in Perl\_runops\_standard \(\)
\#14 0x4009b6bd in sortcv \(\)
\#15 0x4009ae99 in S\_qsortsv \(\)
\#16 0x40093590 in Perl\_pp\_sort \(\)
\#17 0x6a0f in pp\_main \(\) at /tmp/sort\.p\.c&#8203;:1155
\#18 0x4006f719 in Perl\_runops\_standard \(\)
\#19 0x4009b6bd in sortcv \(\)
\#20 0x4009ae99 in S\_qsortsv \(\)
\#21 0x40093590 in Perl\_pp\_sort \(\)
\#22 0x6a0f in pp\_main \(\) at /tmp/sort\.p\.c&#8203;:1155
\#23 0x4006f719 in Perl\_runops\_standard \(\)
\#24 0x4009b6bd in sortcv \(\)
\#25 0x4009ae99 in S\_qsortsv \(\)
\#26 0x40093590 in Perl\_pp\_sort \(\)
\#27 0x6a0f in pp\_main \(\) at /tmp/sort\.p\.c&#8203;:1155
\#28 0x4006f719 in Perl\_runops\_standard \(\)
\#29 0x4009b6bd in sortcv \(\)
\#30 0x4009ae99 in S\_qsortsv \(\)
\#31 0x40093590 in Perl\_pp\_sort \(\)
\#32 0x6a0f in pp\_main \(\) at /tmp/sort\.p\.c&#8203;:1155
\#33 0x4006f719 in Perl\_runops\_standard \(\)
\#34 0x4009b6bd in sortcv \(\)
\#35 0x4009ae99 in S\_qsortsv \(\)
\#36 0x40093590 in Perl\_pp\_sort \(\)
\#37 0x6a0f in pp\_main \(\) at /tmp/sort\.p\.c&#8203;:1155
\#38 0x4006f719 in Perl\_runops\_standard \(\)
\#39 0x4009b6bd in sortcv \(\)
\#40 0x4009ae99 in S\_qsortsv \(\)
\#41 0x40093590 in Perl\_pp\_sort \(\)
\#42 0x6a0f in pp\_main \(\) at /tmp/sort\.p\.c&#8203;:1155
\#43 0x4006f719 in Perl\_runops\_standard \(\)
\#44 0x4009b6bd in sortcv \(\)
\#45 0x4009ae99 in S\_qsortsv \(\)
\#46 0x40093590 in Perl\_pp\_sort \(\)
\#47 0x6a0f in pp\_main \(\) at /tmp/sort\.p\.c&#8203;:1155
\#48 0x4006f719 in Perl\_runops\_standard \(\)
\#49 0x4009b6bd in sortcv \(\)
\#50 0x4009ae99 in S\_qsortsv \(\)
\#51 0x40093590 in Perl\_pp\_sort \(\)
\#52 0x6a0f in pp\_main \(\) at /tmp/sort\.p\.c&#8203;:1155
\#53 0x4006f719 in Perl\_runops\_standard \(\)
\#54 0x4009b6bd in sortcv \(\)
\#55 0x4009ae99 in S\_qsortsv \(\)
\#56 0x40093590 in Perl\_pp\_sort \(\)
\#57 0x6a0f in pp\_main \(\) at /tmp/sort\.p\.c&#8203;:1155
\#58 0x4006f719 in Perl\_runops\_standard \(\)
\#59 0x4009b6bd in sortcv \(\)
\#60 0x4009ae99 in S\_qsortsv \(\)
\#61 0x40093590 in Perl\_pp\_sort \(\)
\#62 0x6a0f in pp\_main \(\) at /tmp/sort\.p\.c&#8203;:1155
\#63 0x4006f719 in Perl\_runops\_standard \(\)

\[the following 25000 identical stackframes deleted\]

**Comment by p5pRT** [comment]
### From @rspier

Dupe of \#2900

**Comment by p5pRT** [comment]
@rspier - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @schwern

> \[tchrist@&#8203;chthon\.perl\.com \- Thu Mar 30 11&#8203;:30&#8203;:55 2000\]&#8203;:
> 
> This simple program&#8203;:
> 
>     for $k \(sort \{ length $ENV\{$b\} \<=> length $ENV\{$a\} \} keys %ENV\) \{
>     print "$k=$ENV\{$k\}\\n";
>     \} 
> 
> Under B&#8203;::Bytecode\, produces correct results\, then SEGVs

Now working in 5\.8\.6\.

> Under B&#8203;::C\, produces correct results\, then exits correctly\.

Still working in 5\.8\.6\.

> Under B&#8203;::CC\, produces no results\, but goes into recursive 
>     doom in the sort\, eventually SEGVing for lack of memory
>     in stack death\.

$ perlcc \-O foo
/sw/bin/perlcc&#8203;: foo did not compile\, which can't happen&#8203;:
Can't locate object method "\_save\_common\_middle" via package "B&#8203;::FAKEOP"
at /sw/lib/perl5\-core/5\.8\.6/darwin\-thread\-multi\-2level/B/C\.pm line 389\.
 CHECK failed\-\-call queue aborted\.

Same for bleadperl\.

**Comment by p5pRT** [comment]
### From guest@guest.guest.xxxxxxxx

&nbsp;  sub B&#8203;::OP&#8203;::\_save\_common\_middle \{ 
&nbsp;    my $op = shift; 
&nbsp;    sprintf \("%s\, %u\, %u\, $static\, 0x%x\, 0x%x"\, 
&nbsp;             $op\->fake\_ppaddr\, $op\->targ\, $op\->type\, $op\->flags\, 
$op\->private\); 
&nbsp;  \} 
 
Is the actual \_save\_common\_middle code\. Unfortuantely I don't quite 
see where the inheritance is occuring for it to call that function 
thusly&#8203;: 
 
sub B&#8203;::FAKEOP&#8203;::save \{ 
&nbsp;    my \($op\, $level\) = @&#8203;\_; 
&nbsp;    $opsect\->add\(sprintf\("%s\, %s\, %s"\, 
&nbsp;                         $op\->next\, $op\->sibling\, 
$op\->\_save\_common\_middle\)\); 
&nbsp;    my $ix = $opsect\->index; 
&nbsp;    $init\->add\(sprintf\("op\_list\[$ix\]\.op\_ppaddr = %s;"\, $op\->ppaddr\)\) 
&nbsp;        unless $optimize\_ppaddr; 
&nbsp;    return "&op\_list\[$ix\]"; 
\} 
 
I tried browsing the code to see where $op\-> would at all come up 
relating to B&#8203;::Op\, but didn't come up with anything\.

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'stalled'

**Comment by p5pRT** [comment]
### From @rurban

Ticket moved to \[CPAN \#53536\] in the B\-C queue\. Please close it someone\.
This simple pp\_sort bug for B&#8203;::CC was fixed 
in B\-C\-1\.04\_27\, B&#8203;::CC 1\.02\_03

\* CC\.pm \(1\.02\_03\)&#8203;: fixed endless loop in optimized sort\. The sortcv 
&nbsp;  cmp needed a return NULL \(test 19\)\.

More pp\_sort bugs are handled in 
tests 18 and 25 and I'm working on it\.

\# 25 \- simple sort
print sort \{ print $i\+\+\," "; $b \<=> $a \} 1\.\.4
=> 0 1 2 3 4321

\# 18 \- custom key sort 18
my $h = \{ a=>3\, b=>1 \}; print sort \{$h\->\{$a\} \<=> $h\->\{$b\}\} keys %$h
=> ba

\# 19 \- fool the sort optimizer by my $p\. This pp\_sort works ok now on CC
print sort \{ my $p; $b \<=> $a \} 1\,4\,3
431
\-\- 
Reini Urban

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'stalled' to 'open'

**Comment by p5pRT** [comment]
@rgs - Status changed from 'open' to 'resolved'
