### ISSUE TITLE
#1 Direct leak of 131264 byte(s) in 4 object(s)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16609]
Migrated from [rt.perl.org#133331](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133331) (status was 'resolved')

Searchable as RT133331$

**Comment by p5pRT** [comment]
### From superbsegfault@gmail.com

=================================================================
==19134==ERROR&#8203;: LeakSanitizer&#8203;: detected memory leaks

Direct leak of 131264 byte\(s\) in 4 object\(s\) allocated from&#8203;:
&nbsp;    \#0 0x4d4730 in malloc \(/home/perl\_asan/perl\-5\.28\.0/miniperl\+0x4d4730\)
&nbsp;    \#1 0x7fbdbb9da9b5 in \_\_alloc\_dir
/build/glibc\-OTsEL5/glibc\-2\.27/dirent/\.\./sysdeps/posix/opendir\.c&#8203;:216
&nbsp;    \#2 0x7fbdbb9da9b5 in opendir\_tail
/build/glibc\-OTsEL5/glibc\-2\.27/dirent/\.\./sysdeps/posix/opendir\.c&#8203;:136
&nbsp;    \#3 0x7fbdbb9da9b5 in opendir
/build/glibc\-OTsEL5/glibc\-2\.27/dirent/\.\./sysdeps/posix/opendir\.c&#8203;:190

SUMMARY&#8203;: AddressSanitizer&#8203;: 131264 byte\(s\) leaked in 4 allocation\(s\)\.


Steps to reproduce&#8203;:
CFLAGS="fsanitize=address" CXXFLAGS="\-fsanitize=address" \./configure\.gnu
make

**Comment by p5pRT** [comment]
### From @tonycoz

On Thu\, Jul 05\, 2018 at 02&#8203;:34&#8203;:02AM \-0700\, aaa bbb wrote&#8203;:
> \# New Ticket Created by  aaa bbb 
> \# Please include the string&#8203;:  \[perl \#133331\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133331 >
> 
> 
> =================================================================
> ==19134==ERROR&#8203;: LeakSanitizer&#8203;: detected memory leaks
> 
> Direct leak of 131264 byte\(s\) in 4 object\(s\) allocated from&#8203;:
>     \#0 0x4d4730 in malloc \(/home/perl\_asan/perl\-5\.28\.0/miniperl\+0x4d4730\)
>     \#1 0x7fbdbb9da9b5 in \_\_alloc\_dir
> /build/glibc\-OTsEL5/glibc\-2\.27/dirent/\.\./sysdeps/posix/opendir\.c&#8203;:216
>     \#2 0x7fbdbb9da9b5 in opendir\_tail
> /build/glibc\-OTsEL5/glibc\-2\.27/dirent/\.\./sysdeps/posix/opendir\.c&#8203;:136
>     \#3 0x7fbdbb9da9b5 in opendir
> /build/glibc\-OTsEL5/glibc\-2\.27/dirent/\.\./sysdeps/posix/opendir\.c&#8203;:190
> 
> SUMMARY&#8203;: AddressSanitizer&#8203;: 131264 byte\(s\) leaked in 4 allocation\(s\)\.
> 
> 
> Steps to reproduce&#8203;:
> CFLAGS="fsanitize=address" CXXFLAGS="\-fsanitize=address" \./configure\.gnu
> make

This is probably the same as \#133314\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Thu\, 05 Jul 2018 04&#8203;:06&#8203;:40 \-0700\, tonyc wrote&#8203;:
> > ==19134==ERROR&#8203;: LeakSanitizer&#8203;: detected memory leaks
> > 
> > Direct leak of 131264 byte\(s\) in 4 object\(s\) allocated from&#8203;:
> >     \#0 0x4d4730 in malloc \(/home/perl\_asan/perl\-5\.28\.0/miniperl\+0x4d4730\)
> >     \#1 0x7fbdbb9da9b5 in \_\_alloc\_dir
> > /build/glibc\-OTsEL5/glibc\-2\.27/dirent/\.\./sysdeps/posix/opendir\.c&#8203;:216
> >     \#2 0x7fbdbb9da9b5 in opendir\_tail
> > /build/glibc\-OTsEL5/glibc\-2\.27/dirent/\.\./sysdeps/posix/opendir\.c&#8203;:136
> >     \#3 0x7fbdbb9da9b5 in opendir
> > /build/glibc\-OTsEL5/glibc\-2\.27/dirent/\.\./sysdeps/posix/opendir\.c&#8203;:190
> > 
> > SUMMARY&#8203;: AddressSanitizer&#8203;: 131264 byte\(s\) leaked in 4 allocation\(s\)\.
> > 
> > 
> > Steps to reproduce&#8203;:
> > CFLAGS="fsanitize=address" CXXFLAGS="\-fsanitize=address" \./configure\.gnu
> > make
> 
> This is probably the same as \#133314\.

That said\, it might not be\, can you provide more context around the failure?  Which command run by make produced the error?

Thanks\,
Tony

**Comment by p5pRT** [comment]
### From @tonycoz

On Thu\, 05 Jul 2018 04&#8203;:06&#8203;:40 \-0700\, tonyc wrote&#8203;:
> On Thu\, Jul 05\, 2018 at 02&#8203;:34&#8203;:02AM \-0700\, aaa bbb wrote&#8203;:
> > \# New Ticket Created by  aaa bbb 
> > \# Please include the string&#8203;:  \[perl \#133331\]
> > \# in the subject line of all future correspondence about this issue\. 
> > \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133331 >
> > 
> > 
> > =================================================================
> > ==19134==ERROR&#8203;: LeakSanitizer&#8203;: detected memory leaks
> > 
> > Direct leak of 131264 byte\(s\) in 4 object\(s\) allocated from&#8203;:
> >     \#0 0x4d4730 in malloc \(/home/perl\_asan/perl\-5\.28\.0/miniperl\+0x4d4730\)
> >     \#1 0x7fbdbb9da9b5 in \_\_alloc\_dir
> > /build/glibc\-OTsEL5/glibc\-2\.27/dirent/\.\./sysdeps/posix/opendir\.c&#8203;:216
> >     \#2 0x7fbdbb9da9b5 in opendir\_tail
> > /build/glibc\-OTsEL5/glibc\-2\.27/dirent/\.\./sysdeps/posix/opendir\.c&#8203;:136
> >     \#3 0x7fbdbb9da9b5 in opendir
> > /build/glibc\-OTsEL5/glibc\-2\.27/dirent/\.\./sysdeps/posix/opendir\.c&#8203;:190
> > 
> > SUMMARY&#8203;: AddressSanitizer&#8203;: 131264 byte\(s\) leaked in 4 allocation\(s\)\.
> > 
> > 
> > Steps to reproduce&#8203;:
> > CFLAGS="fsanitize=address" CXXFLAGS="\-fsanitize=address" \./configure\.gnu
> > make
> 
> This is probably the same as \#133314\.

If it is\, is it a \(then and now public\) security issue?

It's my bug\, so I'm not sure I should be making the decision \(whatever else it is\, it is a serious bug\.\)

Tony

**Comment by p5pRT** [comment]
### From @steve-m-hay

Moved to public queue with the release of 5\.28\.1\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Moved to public queue with the release of 5\.28\.1\.

**Comment by p5pRT** [comment]
### From @steve-m-hay

This was fixed in blead by commit 3d5e9c119db6b727684fe75dfcfe5831c4351bec\, and back\-ported to 5\.28\.1 by commit e0eae03760cafde89463c4d3d238be9a629f7fca\. Awaiting release in 5\.30\.0\.

**Comment by p5pRT** [comment]
@steve-m-hay - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.30\.0\, this and 160 other issues have been
resolved\.

Perl 5\.30\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.30.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
