### ISSUE TITLE
#3 AddressSanitizer: heap-buffer-overflow on address 0x619000004fa0 at pc 0x000000ef95ec bp 0x7ffd45c68050 sp 0x7ffd45c68048 READ of size 8

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16611]
Migrated from [rt.perl.org#133335](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133335) (status was 'open')

Searchable as RT133335$

**Comment by p5pRT** [comment]
### From superbsegfault@gmail.com

=================================================================
==25922==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
0x619000004fa0 at pc 0x000000ef95ec bp 0x7ffd45c68050 sp 0x7ffd45c68048
READ of size 8 at 0x619000004fa0 thread T0
&nbsp;    \#0 0xef95eb in S\_mro\_gather\_and\_rename
/home/perl\_asan/perl\-5\.28\.0/mro\_core\.c&#8203;:930&#8203;:9
&nbsp;    \#1 0xeefbc4 in S\_mro\_gather\_and\_rename
/home/perl\_asan/perl\-5\.28\.0/mro\_core\.c&#8203;:1186&#8203;:4
&nbsp;    \#2 0xed6dd3 in Perl\_mro\_package\_moved
/home/perl\_asan/perl\-5\.28\.0/mro\_core\.c&#8203;:851&#8203;:5
&nbsp;    \#3 0x113bc64 in S\_glob\_assign\_glob
/home/perl\_asan/perl\-5\.28\.0/sv\.c&#8203;:3886&#8203;:6
&nbsp;    \#4 0x111cc3d in Perl\_sv\_setsv\_flags
/home/perl\_asan/perl\-5\.28\.0/sv\.c&#8203;:4365&#8203;:7
&nbsp;    \#5 0xfef1cb in Perl\_pp\_sassign
/home/perl\_asan/perl\-5\.28\.0/pp\_hot\.c&#8203;:226&#8203;:5
&nbsp;    \#6 0xfeb0f0 in Perl\_runops\_standard
/home/perl\_asan/perl\-5\.28\.0/run\.c&#8203;:41&#8203;:26
&nbsp;    \#7 0x71328f in S\_run\_body /home/perl\_asan/perl\-5\.28\.0/perl\.c
&nbsp;    \#8 0x71328f in perl\_run /home/perl\_asan/perl\-5\.28\.0/perl\.c&#8203;:2617
&nbsp;    \#9 0x52b888 in main /home/perl\_asan/perl\-5\.28\.0/perlmain\.c&#8203;:122&#8203;:9
&nbsp;    \#10 0x7efe79ce8b96 in \_\_libc\_start\_main
/build/glibc\-OTsEL5/glibc\-2\.27/csu/\.\./csu/libc\-start\.c&#8203;:310
&nbsp;    \#11 0x43c109 in \_start \(/home/perl\_asan/perl\-5\.28\.0/perl\+0x43c109\)

0x619000004fa0 is located 32 bytes to the right of 1024\-byte region
\[0x619000004b80\,0x619000004f80\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4f1b85 in realloc \(/home/perl\_asan/perl\-5\.28\.0/perl\+0x4f1b85\)
&nbsp;    \#1 0xdf7fe2 in Perl\_safesysrealloc
/home/perl\_asan/perl\-5\.28\.0/util\.c&#8203;:271&#8203;:18

SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow
/home/perl\_asan/perl\-5\.28\.0/mro\_core\.c&#8203;:930&#8203;:9 in S\_mro\_gather\_and\_rename
Shadow bytes around the buggy address&#8203;:
&nbsp;  0x0c327fff89a0&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c327fff89b0&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c327fff89c0&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c327fff89d0&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c327fff89e0&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c327fff89f0&#8203;: fa fa fa fa\[fa\]fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c327fff8a00&#8203;: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
&nbsp;  0x0c327fff8a10&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c327fff8a20&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c327fff8a30&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
&nbsp;  0x0c327fff8a40&#8203;: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend \(one shadow byte represents 8 application bytes\)&#8203;:
&nbsp;  Addressable&#8203;:           00
&nbsp;  Partially addressable&#8203;: 01 02 03 04 05 06 07
&nbsp;  Heap left redzone&#8203;:       fa
&nbsp;  Freed heap region&#8203;:       fd
&nbsp;  Stack left redzone&#8203;:      f1
&nbsp;  Stack mid redzone&#8203;:       f2
&nbsp;  Stack right redzone&#8203;:     f3
&nbsp;  Stack after return&#8203;:      f5
&nbsp;  Stack use after scope&#8203;:   f8
&nbsp;  Global redzone&#8203;:          f9
&nbsp;  Global init order&#8203;:       f6
&nbsp;  Poisoned by user&#8203;:        f7
&nbsp;  Container overflow&#8203;:      fc
&nbsp;  Array cookie&#8203;:            ac
&nbsp;  Intra object redzone&#8203;:    bb
&nbsp;  ASan internal&#8203;:           fe
&nbsp;  Left alloca redzone&#8203;:     ca
&nbsp;  Right alloca redzone&#8203;:    cb
==25922==ABORTING

**Comment by p5pRT** [comment]
### From superbsegfault@gmail.com

[heap_buffer_overflow](https://rt-archive.perl.org/perl5/Ticket/Attachment/1565338/824353/heap_buffer_overflow)

**Comment by p5pRT** [comment]
### From @hvds

I suspect this is the same issue as rt133334\, but we should check again after we get a fix for that\.

Hugo

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Fri\, 13 Jul 2018 04&#8203;:19&#8203;:23 \-0700\, hv wrote&#8203;:
> I suspect this is the same issue as rt133334\, but we should check
> again after we get a fix for that\.

It looks the same here&#8203;:

\.\.\.
stash
SV = PVHV\(0x557dea5db860\) at 0x557dea5fb578
&nbsp;  REFCNT = 1
&nbsp;  FLAGS = \(SHAREKEYS\)
&nbsp;  ARRAY = 0x557dea620200  \(0&#8203;:88\, 1&#8203;:34\, 2&#8203;:5\, 3&#8203;:1\)
&nbsp;  hash quality = 128\.2%
&nbsp;  KEYS = 47
&nbsp;  FILL = 40
&nbsp;  MAX = 127
oldstash
SV = PVHV\(0x557dea5db860\) at 0x557dea5fb578
&nbsp;  REFCNT = 1
&nbsp;  FLAGS = \(SHAREKEYS\)
&nbsp;  ARRAY = 0x557dea620200  \(0&#8203;:88\, 1&#8203;:34\, 2&#8203;:5\, 3&#8203;:1\)
&nbsp;  hash quality = 128\.2%
&nbsp;  KEYS = 47
&nbsp;  FILL = 40
&nbsp;  MAX = 127
miniperl&#8203;: mro\_core\.c&#8203;:934&#8203;: S\_mro\_gather\_and\_rename&#8203;: Assertion \`SvOOK\(oldstash\)' failed\.
Aborted

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

On Thu\, 02 Aug 2018 22&#8203;:19&#8203;:21 \-0700\, tonyc wrote&#8203;:
> On Fri\, 13 Jul 2018 04&#8203;:19&#8203;:23 \-0700\, hv wrote&#8203;:
> > I suspect this is the same issue as rt133334\, but we should check
> > again after we get a fix for that\.
> 
> It looks the same here&#8203;:
> 
> \.\.\.
> stash
> SV = PVHV\(0x557dea5db860\) at 0x557dea5fb578
>   REFCNT = 1
>   FLAGS = \(SHAREKEYS\)
>   ARRAY = 0x557dea620200  \(0&#8203;:88\, 1&#8203;:34\, 2&#8203;:5\, 3&#8203;:1\)
>   hash quality = 128\.2%
>   KEYS = 47
>   FILL = 40
>   MAX = 127
> oldstash
> SV = PVHV\(0x557dea5db860\) at 0x557dea5fb578
>   REFCNT = 1
>   FLAGS = \(SHAREKEYS\)
>   ARRAY = 0x557dea620200  \(0&#8203;:88\, 1&#8203;:34\, 2&#8203;:5\, 3&#8203;:1\)
>   hash quality = 128\.2%
>   KEYS = 47
>   FILL = 40
>   MAX = 127
> miniperl&#8203;: mro\_core\.c&#8203;:934&#8203;: S\_mro\_gather\_and\_rename&#8203;: Assertion
> \`SvOOK\(oldstash\)' failed\.
> Aborted

Since this seems like the same issue as \#13334\, it's also now public\.

Not quite confident enough to merge them though\.

Tony
