### ISSUE TITLE
NULL pointer deference in Perl_sv_setpv_bufsize

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16727]
Migrated from [rt.perl.org#133599](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133599) (status was 'open')

Searchable as RT133599$

**Comment by p5pRT** [comment]
### From zzw20124321@gmail.com

NULL pointer deference in Perl\_sv\_setpv\_bufsize

\./perl \-v

This is perl 5\, version 29\, subversion 3 \(v5\.29\.3\) built for x86\_64\-linux

Copyright 1987\-2018\, Larry Wall

Perl may be copied only under the terms of either the Artistic License or
the
GNU General Public License\, which may be found in the Perl 5 source kit\.

Complete documentation for Perl\, including FAQ lists\, should be found on
this system using "man perl" or "perldoc perl"\.  If you have access to the
Internet\, point your browser at http&#8203;://www\.perl\.org/\, the Perl Home Page\.



compile with \-fsanitize=address

\./perl null\_pointer\.pl
$\* is no longer supported\. Its use will be fatal in Perl 5\.30 at
null\_pointer\.pl line 1\.
ASAN&#8203;:SIGSEGV
=================================================================
==26073==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000000
\(pc 0x000000639f80 bp 0x000000000000 sp 0x7ffcf29b4330 T0\)
&nbsp;    \#0 0x639f7f in Perl\_sv\_setpv\_bufsize
/home/fan/github/perl5\-5\.29\.3/sv\.c&#8203;:4865
&nbsp;    \#1 0x6fa103 in Perl\_do\_vop /home/fan/github/perl5\-5\.29\.3/doop\.c&#8203;:1039
&nbsp;    \#2 0x661ce6 in Perl\_pp\_bit\_or /home/fan/github/perl5\-5\.29\.3/pp\.c&#8203;:2392
&nbsp;    \#3 0x5e983a in Perl\_runops\_standard
/home/fan/github/perl5\-5\.29\.3/run\.c&#8203;:41
&nbsp;    \#4 0x48efa7 in S\_run\_body /home/fan/github/perl5\-5\.29\.3/perl\.c&#8203;:2683
&nbsp;    \#5 0x48efa7 in perl\_run /home/fan/github/perl5\-5\.29\.3/perl\.c&#8203;:2611
&nbsp;    \#6 0x424814 in main /home/fan/github/perl5\-5\.29\.3/perlmain\.c&#8203;:122
&nbsp;    \#7 0x7f2f2194382f in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2082f\)
&nbsp;    \#8 0x424d88 in \_start \(/home/fan/github/perl5\-5\.29\.3/perl\+0x424d88\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /home/fan/github/perl5\-5\.29\.3/sv\.c&#8203;:4865
Perl\_sv\_setpv\_bufsize
==26073==ABORTING

cat null\_pointer\.pl
$\* ^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*&#8203;:







or we cat test this

\.\./perl \-e '$\* ^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*&#8203;:'

$\* is no longer supported\. Its use will be fatal in Perl 5\.30 at \-e line 1\.
ASAN&#8203;:SIGSEGV
=================================================================
==27827==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000000
\(pc 0x000000639f80 bp 0x000000000000 sp 0x7ffc146ae8f0 T0\)
&nbsp;    \#0 0x639f7f in Perl\_sv\_setpv\_bufsize
/home/fan/github/perl5\-5\.29\.3/sv\.c&#8203;:4865
&nbsp;    \#1 0x6fa103 in Perl\_do\_vop /home/fan/github/perl5\-5\.29\.3/doop\.c&#8203;:1039
&nbsp;    \#2 0x661ce6 in Perl\_pp\_bit\_or /home/fan/github/perl5\-5\.29\.3/pp\.c&#8203;:2392
&nbsp;    \#3 0x5e983a in Perl\_runops\_standard
/home/fan/github/perl5\-5\.29\.3/run\.c&#8203;:41
&nbsp;    \#4 0x48efa7 in S\_run\_body /home/fan/github/perl5\-5\.29\.3/perl\.c&#8203;:2683
&nbsp;    \#5 0x48efa7 in perl\_run /home/fan/github/perl5\-5\.29\.3/perl\.c&#8203;:2611
&nbsp;    \#6 0x424814 in main /home/fan/github/perl5\-5\.29\.3/perlmain\.c&#8203;:122
&nbsp;    \#7 0x7ffb6e6a382f in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2082f\)
&nbsp;    \#8 0x424d88 in \_start \(/home/fan/github/perl5\-5\.29\.3/perl\+0x424d88\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /home/fan/github/perl5\-5\.29\.3/sv\.c&#8203;:4865
Perl\_sv\_setpv\_bufsize
==27827==ABORTING

**Comment by p5pRT** [comment]
### From @jkeenan

On Fri\, 19 Oct 2018 05&#8203;:19&#8203;:47 GMT\, zzw20124321@&#8203;gmail\.com wrote&#8203;:
> NULL pointer deference in Perl\_sv\_setpv\_bufsize
> 
> \./perl \-v
> 
> This is perl 5\, version 29\, subversion 3 \(v5\.29\.3\) built for x86\_64\-linux
> 
> Copyright 1987\-2018\, Larry Wall
> 
> Perl may be copied only under the terms of either the Artistic License or
> the
> GNU General Public License\, which may be found in the Perl 5 source kit\.
> 
> Complete documentation for Perl\, including FAQ lists\, should be found on
> this system using "man perl" or "perldoc perl"\.  If you have access to the
> Internet\, point your browser at http&#8203;://www\.perl\.org/\, the Perl Home Page\.
> 
> 
> 
> compile with \-fsanitize=address
> 
> \./perl null\_pointer\.pl
> $\* is no longer supported\. Its use will be fatal in Perl 5\.30 at
> null\_pointer\.pl line 1\.
> ASAN&#8203;:SIGSEGV
> =================================================================
> ==26073==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000000
> \(pc 0x000000639f80 bp 0x000000000000 sp 0x7ffcf29b4330 T0\)
>     \#0 0x639f7f in Perl\_sv\_setpv\_bufsize
> /home/fan/github/perl5\-5\.29\.3/sv\.c&#8203;:4865
>     \#1 0x6fa103 in Perl\_do\_vop /home/fan/github/perl5\-5\.29\.3/doop\.c&#8203;:1039
>     \#2 0x661ce6 in Perl\_pp\_bit\_or /home/fan/github/perl5\-5\.29\.3/pp\.c&#8203;:2392
>     \#3 0x5e983a in Perl\_runops\_standard
> /home/fan/github/perl5\-5\.29\.3/run\.c&#8203;:41
>     \#4 0x48efa7 in S\_run\_body /home/fan/github/perl5\-5\.29\.3/perl\.c&#8203;:2683
>     \#5 0x48efa7 in perl\_run /home/fan/github/perl5\-5\.29\.3/perl\.c&#8203;:2611
>     \#6 0x424814 in main /home/fan/github/perl5\-5\.29\.3/perlmain\.c&#8203;:122
>     \#7 0x7f2f2194382f in \_\_libc\_start\_main
> \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2082f\)
>     \#8 0x424d88 in \_start \(/home/fan/github/perl5\-5\.29\.3/perl\+0x424d88\)
> 
> AddressSanitizer can not provide additional info\.
> SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /home/fan/github/perl5\-5\.29\.3/sv\.c&#8203;:4865
> Perl\_sv\_setpv\_bufsize
> ==26073==ABORTING
> 
> cat null\_pointer\.pl
> $\* ^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*&#8203;:
> 
> 
> 
> 
> 
> 
> 
> or we cat test this
> 
> \.\./perl \-e '$\* ^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*&#8203;:'
> 
> $\* is no longer supported\. Its use will be fatal in Perl 5\.30 at \-e line 1\.
> ASAN&#8203;:SIGSEGV
> =================================================================
> ==27827==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000000
> \(pc 0x000000639f80 bp 0x000000000000 sp 0x7ffc146ae8f0 T0\)
>     \#0 0x639f7f in Perl\_sv\_setpv\_bufsize
> /home/fan/github/perl5\-5\.29\.3/sv\.c&#8203;:4865
>     \#1 0x6fa103 in Perl\_do\_vop /home/fan/github/perl5\-5\.29\.3/doop\.c&#8203;:1039
>     \#2 0x661ce6 in Perl\_pp\_bit\_or /home/fan/github/perl5\-5\.29\.3/pp\.c&#8203;:2392
>     \#3 0x5e983a in Perl\_runops\_standard
> /home/fan/github/perl5\-5\.29\.3/run\.c&#8203;:41
>     \#4 0x48efa7 in S\_run\_body /home/fan/github/perl5\-5\.29\.3/perl\.c&#8203;:2683
>     \#5 0x48efa7 in perl\_run /home/fan/github/perl5\-5\.29\.3/perl\.c&#8203;:2611
>     \#6 0x424814 in main /home/fan/github/perl5\-5\.29\.3/perlmain\.c&#8203;:122
>     \#7 0x7ffb6e6a382f in \_\_libc\_start\_main
> \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2082f\)
>     \#8 0x424d88 in \_start \(/home/fan/github/perl5\-5\.29\.3/perl\+0x424d88\)
> 
> AddressSanitizer can not provide additional info\.
> SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /home/fan/github/perl5\-5\.29\.3/sv\.c&#8203;:4865
> Perl\_sv\_setpv\_bufsize
> ==27827==ABORTING

It so happens that just this week we introducted into blead \-\- our main development branch \-\- the commit which fatalizes use of $\*\.

\#\#\#\#\#
commit dcb414ac3e404a94d6b3ba0a9a06e72ae0ab368d
Author&#8203;:     James E Keenan \<jkeenan@&#8203;cpan\.org>
AuthorDate&#8203;: Fri Oct 12 11&#8203;:55&#8203;:40 2018
Commit&#8203;:     James E Keenan \<jkeenan@&#8203;cpan\.org>
CommitDate&#8203;: Wed Oct 17 07&#8203;:44&#8203;:45 2018

&nbsp;    Fatalize use of $\* and $\#
&nbsp;    
&nbsp;    Per&#8203;: RT \# 133583
\#\#\#\#\#

So now you won't get the segfault \(preceded by a deprecation warning\) when you run that program; you'll get an exception instead\.

\#\#\#\#\#
$ bleadperl \-v | head \-2 | tail \-1
This is perl 5\, version 29\, subversion 4 \(v5\.29\.4 \(v5\.29\.3\-71\-g083a0c3388\)\) built for x86\_64\-linux\-thread\-multi

$ bleadperl \-e '$\* ^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*&#8203;:'
$\* is no longer supported as of Perl 5\.30 at \-e line 1\.
\#\#\#\#\#

Thank you very much\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @xenu

On Fri\, 19 Oct 2018 18&#8203;:07&#8203;:10 \-0700
"James E Keenan via RT" \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

> It so happens that just this week we introducted into blead \-\- our main development branch \-\- the commit which fatalizes use of $\*\.
> 
> \#\#\#\#\#
> commit dcb414ac3e404a94d6b3ba0a9a06e72ae0ab368d
> Author&#8203;:     James E Keenan \<jkeenan@&#8203;cpan\.org>
> AuthorDate&#8203;: Fri Oct 12 11&#8203;:55&#8203;:40 2018
> Commit&#8203;:     James E Keenan \<jkeenan@&#8203;cpan\.org>
> CommitDate&#8203;: Wed Oct 17 07&#8203;:44&#8203;:45 2018
> 
>     Fatalize use of $\* and $\#
>     
>     Per&#8203;: RT \# 133583
> \#\#\#\#\#
> 
> So now you won't get the segfault \(preceded by a deprecation warning\) when you run that program; you'll get an exception instead\.
> 
> \#\#\#\#\#
> $ bleadperl \-v | head \-2 | tail \-1
> This is perl 5\, version 29\, subversion 4 \(v5\.29\.4 \(v5\.29\.3\-71\-g083a0c3388\)\) built for x86\_64\-linux\-thread\-multi
> 
> $ bleadperl \-e '$\* ^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*&#8203;:'
> $\* is no longer supported as of Perl 5\.30 at \-e line 1\.
> \#\#\#\#\#

If you replace $\* with $^\, it still segfaults&#8203;:

> perl5\.29\.4 \-e '$^ ^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*&#8203;:'
Segmentation fault

**Comment by p5pRT** [comment]
### From @jkeenan

On 10/19/2018 09&#8203;:27 PM\, Tomasz Konojacki wrote&#8203;:
> On Fri\, 19 Oct 2018 18&#8203;:07&#8203;:10 \-0700
> "James E Keenan via RT" \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> 
>> It so happens that just this week we introducted into blead \-\- our main development branch \-\- the commit which fatalizes use of $\*\.
>>
>> \#\#\#\#\#
>> commit dcb414ac3e404a94d6b3ba0a9a06e72ae0ab368d
>> Author&#8203;:     James E Keenan \<jkeenan@&#8203;cpan\.org>
>> AuthorDate&#8203;: Fri Oct 12 11&#8203;:55&#8203;:40 2018
>> Commit&#8203;:     James E Keenan \<jkeenan@&#8203;cpan\.org>
>> CommitDate&#8203;: Wed Oct 17 07&#8203;:44&#8203;:45 2018
>>
>>      Fatalize use of $\* and $\#
>>      
>>      Per&#8203;: RT \# 133583
>> \#\#\#\#\#
>>
>> So now you won't get the segfault \(preceded by a deprecation warning\) when you run that program; you'll get an exception instead\.
>>
>> \#\#\#\#\#
>> $ bleadperl \-v | head \-2 | tail \-1
>> This is perl 5\, version 29\, subversion 4 \(v5\.29\.4 \(v5\.29\.3\-71\-g083a0c3388\)\) built for x86\_64\-linux\-thread\-multi
>>
>> $ bleadperl \-e '$\* ^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*&#8203;:'
>> $\* is no longer supported as of Perl 5\.30 at \-e line 1\.
>> \#\#\#\#\#
> 
> If you replace $\* with $^\, it still segfaults&#8203;:
> 
>> perl5\.29\.4 \-e '$^ ^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*&#8203;:'
> Segmentation fault
> 

So\, is this a general problem with the punctuation variables?

**Comment by p5pRT** [comment]
### From @tonycoz

On Fri\, Oct 19\, 2018 at 10&#8203;:29&#8203;:23PM \-0400\, James E Keenan wrote&#8203;:
> On 10/19/2018 09&#8203;:27 PM\, Tomasz Konojacki wrote&#8203;:
> > On Fri\, 19 Oct 2018 18&#8203;:07&#8203;:10 \-0700
> > "James E Keenan via RT" \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> > 
> > > It so happens that just this week we introducted into blead \-\- our main development branch \-\- the commit which fatalizes use of $\*\.
> > > 
> > > \#\#\#\#\#
> > > commit dcb414ac3e404a94d6b3ba0a9a06e72ae0ab368d
> > > Author&#8203;:     James E Keenan \<jkeenan@&#8203;cpan\.org>
> > > AuthorDate&#8203;: Fri Oct 12 11&#8203;:55&#8203;:40 2018
> > > Commit&#8203;:     James E Keenan \<jkeenan@&#8203;cpan\.org>
> > > CommitDate&#8203;: Wed Oct 17 07&#8203;:44&#8203;:45 2018
> > > 
> > >      Fatalize use of $\* and $\#
> > >      Per&#8203;: RT \# 133583
> > > \#\#\#\#\#
> > > 
> > > So now you won't get the segfault \(preceded by a deprecation warning\) when you run that program; you'll get an exception instead\.
> > > 
> > > \#\#\#\#\#
> > > $ bleadperl \-v | head \-2 | tail \-1
> > > This is perl 5\, version 29\, subversion 4 \(v5\.29\.4 \(v5\.29\.3\-71\-g083a0c3388\)\) built for x86\_64\-linux\-thread\-multi
> > > 
> > > $ bleadperl \-e '$\* ^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*&#8203;:'
> > > $\* is no longer supported as of Perl 5\.30 at \-e line 1\.
> > > \#\#\#\#\#
> > 
> > If you replace $\* with $^\, it still segfaults&#8203;:
> > 
> > > perl5\.29\.4 \-e '$^ ^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*^= \*&#8203;: = \*\* = \*&#8203;:'
> > Segmentation fault
> > 
> 
> So\, is this a general problem with the punctuation variables?

No\, it's the stack\-not\-refcounted bug\.

Tony

**Comment by p5pRT** [comment]
### From geeknik@protonmail.ch

This looks like a duplicate of 130224\.

On Fri\, 19 Oct 2018 22&#8203;:22&#8203;:59 \-0700\, tonyc wrote&#8203;:
> 
> No\, it's the stack\-not\-refcounted bug\.
> 
> Tony

**Comment by xcainiao** [comment]
hello would this open a cve?

**Comment by tonycoz** [comment]
> hello would this open a cve?

No, it's a bug, but not a security issue.
