### ISSUE TITLE
double-free in Perl v5.29.4-36-gb4f5c5b5f6

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16743]
Migrated from [rt.perl.org#133642](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133642) (status was 'resolved')

Searchable as RT133642$

**Comment by p5pRT** [comment]
### From geeknik@protonmail.ch

This crafted bit of code triggers a double\-free in Perl v5\.29\.4\-36\-gb4f5c5b5f6&#8203;:

\./perl \-e '/\(\(?\<=\(0?\)\)\)/'

Variable length lookbehind not implemented in regex m/\(\(?\<=\(0?\)\)\)/ at \-e line 1\.
=================================================================
==24593==ERROR&#8203;: AddressSanitizer&#8203;: attempting double\-free on 0x6030000017b0 in thread T0&#8203;:
&nbsp;    \#0 0x4e7812 in \_\_interceptor\_free /b/swarming/w/ir/kitchen\-workdir/src/third\_party/llvm/compiler\-rt/lib/asan/asan\_malloc\_linux\.cc&#8203;:124&#8203;:3
&nbsp;    \#1 0x9d4956 in Perl\_leave\_scope /root/perl/scope\.c&#8203;:1132&#8203;:6
&nbsp;    \#2 0x5bebe7 in S\_my\_exit\_jump /root/perl/perl\.c&#8203;:5237&#8203;:5
&nbsp;    \#3 0x5c9ace in Perl\_my\_failure\_exit /root/perl/perl\.c&#8203;:5221&#8203;:5
&nbsp;    \#4 0x9ff76f in Perl\_die\_unwind /root/perl/pp\_ctl\.c&#8203;:1796&#8203;:5
&nbsp;    \#5 0x7eb8d1 in Perl\_vcroak /root/perl/util\.c&#8203;:1715&#8203;:5
&nbsp;    \#6 0x7e40eb in Perl\_croak /root/perl/util\.c&#8203;:1760&#8203;:5
&nbsp;    \#7 0x72355b in S\_study\_chunk /root/perl/regcomp\.c
&nbsp;    \#8 0x6e8700 in Perl\_re\_op\_compile /root/perl/regcomp\.c&#8203;:7788&#8203;:11
&nbsp;    \#9 0x5344e8 in Perl\_pmruntime /root/perl/op\.c&#8203;:7029&#8203;:6
&nbsp;    \#10 0x6beffd in Perl\_yyparse /root/perl/perly\.y&#8203;:1228&#8203;:23
&nbsp;    \#11 0x5b6ea2 in S\_parse\_body /root/perl/perl\.c&#8203;:2503&#8203;:9
&nbsp;    \#12 0x5b1a90 in perl\_parse /root/perl/perl\.c&#8203;:1797&#8203;:2
&nbsp;    \#13 0x516c19 in main /root/perl/perlmain\.c&#8203;:121&#8203;:10
&nbsp;    \#14 0x7fc0aee842e0 in \_\_libc\_start\_main \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x202e0\)
&nbsp;    \#15 0x43f409 in \_start \(/root/perl/perl\+0x43f409\)

0x6030000017b0 is located 0 bytes inside of 24\-byte region \[0x6030000017b0\,0x6030000017c8\)
freed by thread T0 here&#8203;:
&nbsp;    \#0 0x4e7812 in \_\_interceptor\_free /b/swarming/w/ir/kitchen\-workdir/src/third\_party/llvm/compiler\-rt/lib/asan/asan\_malloc\_linux\.cc&#8203;:124&#8203;:3
&nbsp;    \#1 0x9d4956 in Perl\_leave\_scope /root/perl/scope\.c&#8203;:1132&#8203;:6
&nbsp;    \#2 0x5bebe7 in S\_my\_exit\_jump /root/perl/perl\.c&#8203;:5237&#8203;:5
&nbsp;    \#3 0x5c9ace in Perl\_my\_failure\_exit /root/perl/perl\.c&#8203;:5221&#8203;:5
&nbsp;    \#4 0x9ff76f in Perl\_die\_unwind /root/perl/pp\_ctl\.c&#8203;:1796&#8203;:5
&nbsp;    \#5 0x7eb8d1 in Perl\_vcroak /root/perl/util\.c&#8203;:1715&#8203;:5
&nbsp;    \#6 0x7e40eb in Perl\_croak /root/perl/util\.c&#8203;:1760&#8203;:5
&nbsp;    \#7 0x72355b in S\_study\_chunk /root/perl/regcomp\.c
&nbsp;    \#8 0x6e8700 in Perl\_re\_op\_compile /root/perl/regcomp\.c&#8203;:7788&#8203;:11
&nbsp;    \#9 0x5344e8 in Perl\_pmruntime /root/perl/op\.c&#8203;:7029&#8203;:6
&nbsp;    \#10 0x6beffd in Perl\_yyparse /root/perl/perly\.y&#8203;:1228&#8203;:23
&nbsp;    \#11 0x5b6ea2 in S\_parse\_body /root/perl/perl\.c&#8203;:2503&#8203;:9
&nbsp;    \#12 0x5b1a90 in perl\_parse /root/perl/perl\.c&#8203;:1797&#8203;:2
&nbsp;    \#13 0x516c19 in main /root/perl/perlmain\.c&#8203;:121&#8203;:10
&nbsp;    \#14 0x7fc0aee842e0 in \_\_libc\_start\_main \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x202e0\)

previously allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4e7fb2 in realloc /b/swarming/w/ir/kitchen\-workdir/src/third\_party/llvm/compiler\-rt/lib/asan/asan\_malloc\_linux\.cc&#8203;:165&#8203;:3
&nbsp;    \#1 0x7e4734 in Perl\_safesysrealloc /root/perl/util\.c&#8203;:271&#8203;:18
&nbsp;    \#2 0x7023d3 in S\_reg /root/perl/regcomp\.c&#8203;:11822&#8203;:21
&nbsp;    \#3 0x789f4f in S\_regatom /root/perl/regcomp\.c&#8203;:13162&#8203;:15
&nbsp;    \#4 0x785027 in S\_regpiece /root/perl/regcomp\.c&#8203;:12214&#8203;:11
&nbsp;    \#5 0x773ec2 in S\_regbranch /root/perl/regcomp\.c&#8203;:12134&#8203;:18
&nbsp;    \#6 0x6fd235 in S\_reg /root/perl/regcomp\.c&#8203;:11855&#8203;:10
&nbsp;    \#7 0x789f4f in S\_regatom /root/perl/regcomp\.c&#8203;:13162&#8203;:15
&nbsp;    \#8 0x785027 in S\_regpiece /root/perl/regcomp\.c&#8203;:12214&#8203;:11
&nbsp;    \#9 0x773ec2 in S\_regbranch /root/perl/regcomp\.c&#8203;:12134&#8203;:18
&nbsp;    \#10 0x6fd235 in S\_reg /root/perl/regcomp\.c&#8203;:11855&#8203;:10
&nbsp;    \#11 0x789f4f in S\_regatom /root/perl/regcomp\.c&#8203;:13162&#8203;:15
&nbsp;    \#12 0x785027 in S\_regpiece /root/perl/regcomp\.c&#8203;:12214&#8203;:11
&nbsp;    \#13 0x773ec2 in S\_regbranch /root/perl/regcomp\.c&#8203;:12134&#8203;:18
&nbsp;    \#14 0x6fd235 in S\_reg /root/perl/regcomp\.c&#8203;:11855&#8203;:10
&nbsp;    \#15 0x6e5786 in Perl\_re\_op\_compile /root/perl/regcomp\.c&#8203;:7455&#8203;:9
&nbsp;    \#16 0x5344e8 in Perl\_pmruntime /root/perl/op\.c&#8203;:7029&#8203;:6
&nbsp;    \#17 0x6beffd in Perl\_yyparse /root/perl/perly\.y&#8203;:1228&#8203;:23
&nbsp;    \#18 0x5b6ea2 in S\_parse\_body /root/perl/perl\.c&#8203;:2503&#8203;:9
&nbsp;    \#19 0x5b1a90 in perl\_parse /root/perl/perl\.c&#8203;:1797&#8203;:2
&nbsp;    \#20 0x516c19 in main /root/perl/perlmain\.c&#8203;:121&#8203;:10
&nbsp;    \#21 0x7fc0aee842e0 in \_\_libc\_start\_main \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x202e0\)

SUMMARY&#8203;: AddressSanitizer&#8203;: double\-free /b/swarming/w/ir/kitchen\-workdir/src/third\_party/llvm/compiler\-rt/lib/asan/asan\_malloc\_linux\.cc&#8203;:124&#8203;:3 in \_\_interceptor\_free
==24593==ABORTING

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Nov 05\, 2018 at 07&#8203;:39&#8203;:13PM \-0800\, geeknik@&#8203;protonmail\.ch wrote&#8203;:
> \# New Ticket Created by  geeknik@&#8203;protonmail\.ch 
> \# Please include the string&#8203;:  \[perl \#133642\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133642 >
> 
> 
> This crafted bit of code triggers a double\-free in Perl v5\.29\.4\-36\-gb4f5c5b5f6&#8203;:
> 
> \./perl \-e '/\(\(?\<=\(0?\)\)\)/'

It bisects to

commit 7c932d07cab18751bfc7515b4320436273a459e2
Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
Date&#8203;:   Fri Oct 19 09&#8203;:48&#8203;:34 2018 \-0600

&nbsp;    Remove sizing pass from regular expression compiler


\-\- 
The Enterprise is involved in a bizarre time\-warp experience which is in
some way unconnected with the Late 20th Century\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#14

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @khwilliamson

I'm moving this ticket to the public queue since the bug doesn't exist in a stable release
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
### From @khwilliamson

Thanks for finding and reporting this

Now fixed in blead by commit
d0d8d0cb339722488ab4472815d936625b06704b
 \-\- 
Karl Williamson

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'resolved'
