### ISSUE TITLE
segfault triggered by invalid read in S_mg_findext_flags

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16742]
Migrated from [rt.perl.org#133640](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133640) (status was 'open')

Searchable as RT133640$

**Comment by p5pRT** [comment]
### From geeknik@protonmail.ch

While testing Perl v5\.29\.4\-32\-gf196658042\, I discovered that \./perl \-e '\\grep% N&ep%\\&hN\,@&#8203;N=hhN\,\*N=hNN&ep%\\&hN\,@&#8203;N=hhN\,\,K' causes a segfault triggered by an invalid read as seen by the following stack trace&#8203;:

Operator or semicolon missing before &ep at \-e line 1\.
Ambiguous use of & resolved as operator & at \-e line 1\.
Operator or semicolon missing before &ep at \-e line 1\.
Ambiguous use of & resolved as operator & at \-e line 1\.
UndefinedBehaviorSanitizer&#8203;:DEADLYSIGNAL
==18963==ERROR&#8203;: UndefinedBehaviorSanitizer&#8203;: SEGV on unknown address 0x00ff00000012 \(pc 0x00000069b85a bp 0x7fff7820f330 sp 0x7fff7820f300 T18963\)
==18963==The signal is caused by a READ memory access\.
&nbsp;    \#0 0x69b859 in S\_mg\_findext\_flags /root/perl/mg\.c&#8203;:412&#8203;:2
&nbsp;    \#1 0x6e5700 in Perl\_hv\_placeholders\_get /root/perl/hv\.c&#8203;:3183&#8203;:24
&nbsp;    \#2 0x711efe in S\_padhv\_rv2hv\_common /root/perl/pp\_hot\.c&#8203;:1812&#8203;:13
&nbsp;    \#3 0x71299e in Perl\_pp\_rv2av /root/perl/pp\_hot\.c&#8203;:2004&#8203;:16
&nbsp;    \#4 0x67d9d8 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2536&#8203;:23
&nbsp;    \#5 0x4b18ae in S\_run\_body /root/perl/perl\.c
&nbsp;    \#6 0x4b17da in perl\_run /root/perl/perl\.c&#8203;:2611&#8203;:2
&nbsp;    \#7 0x4461b9 in main /root/perl/perlmain\.c&#8203;:122&#8203;:9
&nbsp;    \#8 0x7f8fcfc932e0 in \_\_libc\_start\_main \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x202e0\)
&nbsp;    \#9 0x426889 in \_start \(/root/perl/perl\+0x426889\)

UndefinedBehaviorSanitizer can not provide additional info\.
==18963==ABORTING

**Comment by p5pRT** [comment]
### From @jkeenan

On Mon\, 05 Nov 2018 14&#8203;:41&#8203;:32 GMT\, geeknik@&#8203;protonmail\.ch wrote&#8203;:
> While testing Perl v5\.29\.4\-32\-gf196658042\, I discovered that \./perl \-e
> '\\grep% N&ep%\\&hN\,@&#8203;N=hhN\,\*N=hNN&ep%\\&hN\,@&#8203;N=hhN\,\,K' causes a segfault
> triggered by an invalid read as seen by the following stack trace&#8203;:
> 
> Operator or semicolon missing before &ep at \-e line 1\.
> Ambiguous use of & resolved as operator & at \-e line 1\.
> Operator or semicolon missing before &ep at \-e line 1\.
> Ambiguous use of & resolved as operator & at \-e line 1\.
> UndefinedBehaviorSanitizer&#8203;:DEADLYSIGNAL
> ==18963==ERROR&#8203;: UndefinedBehaviorSanitizer&#8203;: SEGV on unknown address
> 0x00ff00000012 \(pc 0x00000069b85a bp 0x7fff7820f330 sp 0x7fff7820f300
> T18963\)
> ==18963==The signal is caused by a READ memory access\.
>     \#0 0x69b859 in S\_mg\_findext\_flags /root/perl/mg\.c&#8203;:412&#8203;:2
>     \#1 0x6e5700 in Perl\_hv\_placeholders\_get /root/perl/hv\.c&#8203;:3183&#8203;:24
>     \#2 0x711efe in S\_padhv\_rv2hv\_common /root/perl/pp\_hot\.c&#8203;:1812&#8203;:13
>     \#3 0x71299e in Perl\_pp\_rv2av /root/perl/pp\_hot\.c&#8203;:2004&#8203;:16
>     \#4 0x67d9d8 in Perl\_runops\_debug /root/perl/dump\.c&#8203;:2536&#8203;:23
>     \#5 0x4b18ae in S\_run\_body /root/perl/perl\.c
>     \#6 0x4b17da in perl\_run /root/perl/perl\.c&#8203;:2611&#8203;:2
>     \#7 0x4461b9 in main /root/perl/perlmain\.c&#8203;:122&#8203;:9
>     \#8 0x7f8fcfc932e0 in \_\_libc\_start\_main \(/lib/x86\_64\-linux\-
> gnu/libc\.so\.6\+0x202e0\)
>     \#9 0x426889 in \_start \(/root/perl/perl\+0x426889\)
> 
> UndefinedBehaviorSanitizer can not provide additional info\.
> ==18963==ABORTING

This code has thrown warnings since at least perl\-5\.8\.4\.

\#\#\#\#\#
$ perlbrew use perl\-5\.8\.4
$ perl \-we '\\grep% N&ep%\\&hN\,@&#8203;N=hhN\,\*N=hNN&ep%\\&hN\,@&#8203;N=hhN\,\,K'
Unquoted string "ep" may clash with future reserved word at \-e line 1\.
Operator or semicolon missing before &ep at \-e line 1\.
Ambiguous use of & resolved as operator & at \-e line 1\.
Unquoted string "ep" may clash with future reserved word at \-e line 1\.
Operator or semicolon missing before &ep at \-e line 1\.
Ambiguous use of & resolved as operator & at \-e line 1\.
Useless use of reference constructor in void context at \-e line 1\.
Argument "ep" isn't numeric in modulus \(%\) at \-e line 1\.
Argument "hNN" isn't numeric in bitwise and \(&\) at \-e line 1\.
Argument "ep" isn't numeric in modulus \(%\) at \-e line 1\.
\#\#\#\#\#

But it only resulted in a segfault starting in January 2012\.

\#\#\#\#\#
$ perl Porting/bisect\.pl \-\-start=v5\.14\.4 \-\-end=v5\.16\.3 \-\-crash \-\- \./perl \-Ilib \-e '\\grep% N&ep%\\&hN\,@&#8203;N=hhN\,\*N=hNN&ep%\\&hN\,@&#8203;N=hhN\,\,K'

60edcf09a5cb026822f99270a4bfbe3149cfbb52 is the first bad commit
commit 60edcf09a5cb026822f99270a4bfbe3149cfbb52
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Mon Jan 9 19&#8203;:54&#8203;:26 2012 \-0800

&nbsp;    Better fix for perl \#107440
&nbsp;    
&nbsp;    > > Actually\, the simplest solution seem to be to put the av or hv on
&nbsp;    > > the mortals stack in pp\_aassign and pp\_undef\, rather than in
&nbsp;    > > \[ah\]v\_undef/clear\.
&nbsp;    >
&nbsp;    > This makes me nervous\. The tmps stack is typically cleared only on
&nbsp;    > statement boundaries\, so we run the risks of
&nbsp;    >
&nbsp;    >     \* user\-visible delaying of freeing elements;
&nbsp;    >     \* large tmps stack growth might be possible with
&nbsp;    >       certain types of loop that repeatedly assign to an array without
&nbsp;    >       freeing tmps \(eg map? I think I fixed most map/grep tmps leakage
&nbsp;    > a
&nbsp;    >       while back\, but there may still be some edge cases\)\.
&nbsp;    >
&nbsp;    > Surely an ENTER/SAVEFREESV/LEAVE inside pp\_aassign is just as
&nbsp;    > efficient\,
&nbsp;    > without any attendant risks?
&nbsp;    >
&nbsp;    > Also\, although pp\_aassign and pp\_undef are now fixed\, the
&nbsp;    > \[ah\]v\_undef/clear functions aren't\, and they're part of the public API
&nbsp;    > that can be called independently of pp\_aassign etc\. Ideally they
&nbsp;    > should
&nbsp;    > be fixed \(so they don't crash in mid\-loop\)\, and their documentation
&nbsp;    > updated to point out that on return\, their AV/HV arg may have been
&nbsp;    > freed\.
&nbsp;    
&nbsp;    This commit takes care of the first part; it changes pp\_aassign to use
&nbsp;    ENTER/SAVEFREESV/LEAVE and adds the same to h\_freeentries \(called both
&nbsp;    by hv\_undef and hv\_clear\)\, av\_undef and av\_clear\.
&nbsp;    
&nbsp;    It effectively reverts the C code part of 9f71cfe6ef2\.

:100644 100644 1671f16e401e21dce7ab7fd8c22188ee6cfb2a9d 472600b6f0ab2953d43d2d2a01b94a0695aaf282 M    av\.c
:100644 100644 af41de86917e0f097570da1dc2636a008aa888f2 2cfe25bb4db28d1a7c37d5e27cde2854f6696375 M    hv\.c
:100644 100644 5910e8691d1e3fd7af919b158f61755b13136f38 eaf6a85277d68172b23deb48a8491f800564e9eb M    pp\.c
:100644 100644 add940049bec699a5075feb1138c2eee0a74e3e3 ff834a924e8e2cb248bc2bbd36be15ccc4e40c4f M    pp\_hot\.c

Thank you very much\.
\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon\, 05 Nov 2018 06&#8203;:41&#8203;:32 \-0800\, geeknik@&#8203;protonmail\.ch wrote&#8203;:
> While testing Perl v5\.29\.4\-32\-gf196658042\, I discovered that \./perl \-e
> '\\grep% N&ep%\\&hN\,@&#8203;N=hhN\,\*N=hNN&ep%\\&hN\,@&#8203;N=hhN\,\,K' causes a segfault
> triggered by an invalid read as seen by the following stack trace&#8203;:

Going by the code I suspect it's a stack\-not\-refcounted bug\.

@&#8203;N is pushed\, \*N is modified \(freeing the old @&#8203;N\)\, access to now invalid SV formerly known as @&#8203;N\.

Tony
