### ISSUE TITLE
null pointer dereference in S_regclass()

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16813]
Migrated from [rt.perl.org#133770](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133770) (status was 'resolved')

Searchable as RT133770$

**Comment by p5pRT** [comment]
### From geeknik@protonmail.ch

While testing v5\.29\.6\-96\-g7397626020\, I discovered a segfault triggered by a null pointer dereference in S\_regclass\(\)\. I compiled perl5 with Clang\-8\.0\.0 and AddressSanitizer\.

echo "MAAvAG0AAABbADAwsh8AAA==" | base64 \-d | tee test0084\.pl | perl test0084\.pl

&nbsp;    \#0 0x77a733 in S\_regclass /root/perl/regcomp\.c&#8203;:18577&#8203;:37
&nbsp;    \#1 0x75e1b1 in S\_regatom /root/perl/regcomp\.c&#8203;:13191&#8203;:15
&nbsp;    \#2 0x7588be in S\_regpiece /root/perl/regcomp\.c&#8203;:12431&#8203;:11
&nbsp;    \#3 0x748391 in S\_regbranch /root/perl/regcomp\.c&#8203;:12349&#8203;:18
&nbsp;    \#4 0x6da1b7 in S\_reg /root/perl/regcomp\.c&#8203;:12070&#8203;:10
&nbsp;    \#5 0x6c330f in Perl\_re\_op\_compile /root/perl/regcomp\.c&#8203;:7652&#8203;:9
&nbsp;    \#6 0x5338b8 in Perl\_pmruntime /root/perl/op\.c&#8203;:7045&#8203;:6
&nbsp;    \#7 0x69f5e2 in Perl\_yyparse /root/perl/perly\.y&#8203;:1228&#8203;:23
&nbsp;    \#8 0x5a9a06 in S\_parse\_body /root/perl/perl\.c&#8203;:2506&#8203;:9
&nbsp;    \#9 0x5a4dd3 in perl\_parse /root/perl/perl\.c&#8203;:1797&#8203;:2
&nbsp;    \#10 0x519b7c in main /root/perl/perlmain\.c&#8203;:121&#8203;:10
&nbsp;    \#11 0x7fc0785922e0 in \_\_libc\_start\_main \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x202e0\)
&nbsp;    \#12 0x43f7f9 in \_start \(/root/perl/perl\+0x43f7f9\)

**Comment by p5pRT** [comment]
### From @hvds

On Tue\, 15 Jan 2019 07&#8203;:44&#8203;:03 \-0800\, geeknik@&#8203;protonmail\.ch wrote&#8203;:
> While testing v5\.29\.6\-96\-g7397626020\, I discovered a segfault
> triggered by a null pointer dereference in S\_regclass\(\)\. I compiled
> perl5 with Clang\-8\.0\.0 and AddressSanitizer\.
> 
> echo "MAAvAG0AAABbADAwsh8AAA==" | base64 \-d | tee test0084\.pl | perl
> test0084\.pl
> 
> \#0 0x77a733 in S\_regclass /root/perl/regcomp\.c&#8203;:18577&#8203;:37
\[\.\.\.\]

Without analysing the input too deeply\, I see that the code calls utf8\.c&#8203;:Perl\_\_inverse\_folds\(\)\, then uses an unsigned int i to loop over remaining\_folds&#8203;:
&nbsp;    for \(i = 0; i \< folds\_to\_this\_cp\_count \- 1; i\+\+\) \{
&nbsp;        fold\_list = add\_cp\_to\_invlist\(fold\_list\, remaining\_folds\[i\]\);
&nbsp;    \}

However when folds\_to\_this\_cp\_count is zero\, the loop condition is invalid\.

Certainly this patch is enough to avoid the coredump on this input&#8203;:
\-\-\- a/regcomp\.c
\+\+\+ b/regcomp\.c
@&#8203;@&#8203; \-18573\,7 \+18573\,7 @&#8203;@&#8203; S\_regclass\(pTHX\_ RExC\_state\_t \*pRExC\_state\, I32 \*flagp\, U32 depth\,
&nbsp;                     fold\_list = add\_cp\_to\_invlist\(fold\_list\, start\[0\]\);
&nbsp;                     fold\_list = add\_cp\_to\_invlist\(fold\_list\, folded\);
&nbsp;                     fold\_list = add\_cp\_to\_invlist\(fold\_list\, first\_fold\);
\-                    for \(i = 0; i \< folds\_to\_this\_cp\_count \- 1; i\+\+\) \{
\+                    for \(i = 0; i \+ 1 \< folds\_to\_this\_cp\_count; i\+\+\) \{
&nbsp;                         fold\_list = add\_cp\_to\_invlist\(fold\_list\,
&nbsp;                                                         remaining\_folds\[i\]\);
&nbsp;                     \}

% \./miniperl ~/133770\.pl 
Wide character in print at /home/hv/133770\.pl line 1\.
Unmatched \[ in regex; marked by \<\-\- HERE in m/\[ \<\-\- HERE 〰ᾲ/ at /home/hv/133770\.pl line 1\.
% 

However Perl\_\_inverse\_folds\(\) is also documented to return a NULL remaining\_folds when the count it returns is 1\, so it feels like there's more work to do here\. Karl\, can you take a look?

Hugo

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @khwilliamson

Now fixed by

commit c2d81cfd08d9a622c639058cd7eb870aa0991937
 Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
 Date&#8203;:   Sat Feb 16 11&#8203;:11&#8203;:59 2019 \-0700
 
&nbsp;     PATCH&#8203;: \[perl \#133770\] null pointer dereference in S\_regclass\(\)
&nbsp;     
&nbsp;     The failing case can be reduced to
&nbsp;     
&nbsp;     qr/\\x\{100\}\[\\x\{3030\}\\x\{1fb2\}/
&nbsp;     
&nbsp;     \(It only happens on UTF\-8 patterns\)\.
&nbsp;     
&nbsp;     The bottom line is that it was assuming that there was at least one
&nbsp;     character that folded to 1fb2 besides itself\, even though the function
&nbsp;     call said there weren't any such\.  The solution is to pay attention to
&nbsp;     the function return value\.
&nbsp;     
&nbsp;     I incorporated Hugo's\+\+ patch as part of this one\.
&nbsp;     
&nbsp;     However\, the original test case should never have gotten this far\.  The
&nbsp;     parser is getting passed garbage\, and instead of croaking\, it is somehow
&nbsp;     interpreting it as valid and calling the regex compiler\.  I will file a
&nbsp;     ticket about that\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @khwilliamson

On Sat\, 16 Feb 2019 11&#8203;:48&#8203;:41 \-0800\, khw wrote&#8203;:
> Now fixed by
> 
> commit c2d81cfd08d9a622c639058cd7eb870aa0991937
>  Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
>  Date&#8203;:   Sat Feb 16 11&#8203;:11&#8203;:59 2019 \-0700
> 
> PATCH&#8203;: \[perl \#133770\] null pointer dereference in S\_regclass\(\)
> 
> The failing case can be reduced to
> 
> qr/\\x\{100\}\[\\x\{3030\}\\x\{1fb2\}/
> 
> \(It only happens on UTF\-8 patterns\)\.
> 
> The bottom line is that it was assuming that there was at least one
> character that folded to 1fb2 besides itself\, even though the function
> call said there weren't any such\.  The solution is to pay attention to
> the function return value\.
> 
> I incorporated Hugo's\+\+ patch as part of this one\.
> 
> However\, the original test case should never have gotten this far\.
> The
> parser is getting passed garbage\, and instead of croaking\, it is
> somehow
> interpreting it as valid and calling the regex compiler\.  I will file
> a
> ticket about that\.

Note that this bug was introduced in the current 5\.29 release\, so should not go into the 5\.30 perldelta\, and hence is marked as 'resolved'
\-\- 
Karl Williamson
