### ISSUE TITLE
Memory leak in concatenation operator overload

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16823]
Migrated from [rt.perl.org#133789](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133789) (status was 'resolved')

Searchable as RT133789$

**Comment by p5pRT** [comment]
### From zdm@softvisio.net

#### Created by zdm@softvisio.net



New memory leak was introduces in perl 5\.28\.
Please\, see the discussion here&#8203;:
https://stackoverflow.com/questions/54304341/perl-overload-concatenation-operator-problem

\#\!/usr/bin/env perl

use strict;
use warnings;
use Devel&#8203;::Refcount qw\[refcount\];

package AAA \{
&nbsp;    use Devel&#8203;::Refcount qw\[refcount\];

&nbsp;    use overload
&nbsp;      '\.' => sub \{
&nbsp;    print 'CONCAT\, REFCOUNT&#8203;: '\, refcount\( $\_\[0\] \)\, "\\n";

&nbsp;    \# return AAA\->new;
&nbsp;    return $\_\[0\];
&nbsp;      \}\,
&nbsp;      fallback => 0;

&nbsp;    sub new \{ return bless \{\}\, $\_\[0\] \}

&nbsp;    sub DESTROY \{ print "DESTROY\\n" \}
\}

print "\-\-\- start\\n";

\{
&nbsp;    my $o = AAA\->new;

&nbsp;    my $s = '1' \. \( '2' \. \( '3' \. \( '4' \. \( '5' \. $o \) \) \) \);

&nbsp;    print "\-\-\- exit scope\\n";
&nbsp;    print 'REFCOUNT&#8203;: '\, refcount\($o\)\, "\\n";
\}

print "\-\-\- end\\n";

1;

Output&#8203;:

\-\-\- start
CONCAT\, REFCOUNT&#8203;: 1
CONCAT\, REFCOUNT&#8203;: 3
CONCAT\, REFCOUNT&#8203;: 5
CONCAT\, REFCOUNT&#8203;: 7
CONCAT\, REFCOUNT&#8203;: 9
\-\-\- exit scope
REFCOUNT&#8203;: 6
\-\-\- end
DESTROY

Refs count should stay untouched\, but it increased on each iteration\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl 5.28.1:

Configured by mockbuild at Mon Jan 21 14:05:45 UTC 2019.

Summary of my perl5 (revision 5 version 28 subversion 1) configuration:

  Platform:
    osname=linux
    osvers=4.16.13-300.fc28.x86_64
    archname=x86_64-linux-ld
    uname='linux 0b8553fb90eb4b24a5147b6ec2b37883
4.16.13-300.fc28.x86_64 #1 smp wed may 30 14:31:00 utc 2018 x86_64
x86_64 x86_64 gnulinux '
    config_args='-des -Dusemorebits -Duselargefiles
-Dprefix=/usr/perlbrew/perls/perl-5.28.1 -Duserelocatableinc
-Dman1dir=none -Dman3dir=none'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=define
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='8.2.1 20181215 (Red Hat 8.2.1-6)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='long double'
    nvsize=16
    Off_t='off_t'
    lseeksize=8
    alignbytes=16
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib /lib/../lib64 /usr/lib/../lib64 /lib
/lib64 /usr/lib64 /usr/local/lib64
    libs=-lpthread -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.28.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.28'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'



@INC for perl 5.28.1:
    /mnt/hgfs/projects/pcore-lib/pcore/lib
    /usr/perlbrew/perls/perl-5.28.1/lib/site_perl/5.28.1/x86_64-linux-ld
    /usr/perlbrew/perls/perl-5.28.1/lib/site_perl/5.28.1
    /usr/perlbrew/perls/perl-5.28.1/lib/5.28.1/x86_64-linux-ld
    /usr/perlbrew/perls/perl-5.28.1/lib/5.28.1


Environment for perl 5.28.1:
    HOME=/root
    LANG=en_US.UTF-8
    LANGUAGE=en_US.UTF-8
    LC_ALL=en_US.UTF-8
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)

PATH=/usr/perlbrew/bin:/usr/perlbrew/perls/perl-5.28.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/mnt/hgfs/projects/pcore-lib/pcore/bin
    PERL5LIB=/mnt/hgfs/projects/pcore-lib/pcore/lib
    PERLBREW=command perlbrew
    PERLBREW_HOME=/usr/perlbrew
    PERLBREW_MANPATH=/usr/perlbrew/perls/perl-5.28.1/man
    PERLBREW_PATH=/usr/perlbrew/bin:/usr/perlbrew/perls/perl-5.28.1/bin
    PERLBREW_PERL=perl-5.28.1
    PERLBREW_ROOT=/usr/perlbrew
    PERLBREW_SHELLRC_VERSION=0.86
    PERLBREW_VERSION=0.86
    PERL_BADLANG (unset)
    PERL_CPANM_HOME=/tmp/.cpanm
    PERL_CPANM_OPT=--metacpan --from https://cpan.metacpan.org/
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue\, 22 Jan 2019 02&#8203;:50&#8203;:40 \-0800\, zdm@&#8203;softvisio\.net wrote&#8203;:
> New memory leak was introduces in perl 5\.28\.
> Please\, see the discussion here&#8203;:
> https://stackoverflow.com/questions/54304341/perl-overload-
> concatenation\-operator\-problem
> 
> \#\!/usr/bin/env perl
> 
> use strict;
> use warnings;
> use Devel&#8203;::Refcount qw\[refcount\];
> 
> package AAA \{
>     use Devel&#8203;::Refcount qw\[refcount\];
> 
> use overload
>   '\.' => sub \{
>     print 'CONCAT\, REFCOUNT&#8203;: '\, refcount\( $\_\[0\] \)\, "\\n";
> 
> \# return AAA\->new;
> return $\_\[0\];
> \}\,
> fallback => 0;
> 
> sub new \{ return bless \{\}\, $\_\[0\] \}
> 
> sub DESTROY \{ print "DESTROY\\n" \}
> \}
> 
> print "\-\-\- start\\n";
> 
> \{
>     my $o = AAA\->new;
> 
> my $s = '1' \. \( '2' \. \( '3' \. \( '4' \. \( '5' \. $o \) \) \) \);
> 
> print "\-\-\- exit scope\\n";
> print 'REFCOUNT&#8203;: '\, refcount\($o\)\, "\\n";
> \}
> 
> print "\-\-\- end\\n";
> 
> 1;
> 
> Output&#8203;:
> 
> \-\-\- start
> CONCAT\, REFCOUNT&#8203;: 1
> CONCAT\, REFCOUNT&#8203;: 3
> CONCAT\, REFCOUNT&#8203;: 5
> CONCAT\, REFCOUNT&#8203;: 7
> CONCAT\, REFCOUNT&#8203;: 9
> \-\-\- exit scope
> REFCOUNT&#8203;: 6
> \-\-\- end
> DESTROY
> 
> Refs count should stay untouched\, but it increased on each iteration\.

This is present in blead too\.

There's two places the reference count is being incremented\.

The first is in leave\_adjust\_stacks\(\) as the return from the '\.' overload is being processed&#8203;:

\(gdb\) bt
\#0  S\_SvREFCNT\_inc \(sv=0x555555d204a8\) at inline\.h&#8203;:194
\#1  0x0000555555760634 in Perl\_leave\_adjust\_stacks \(from\_sp=0x555555d4ae10\, 
&nbsp;    to\_sp=0x555555d4ae08\, gimme=2 '\\002'\, pass=0\) at pp\_hot\.c&#8203;:4793
\#2  0x0000555555760a48 in Perl\_pp\_leavesub \(\) at pp\_hot\.c&#8203;:4902
\#3  0x00005555556f4b41 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2536
\#4  0x0000555555607358 in Perl\_amagic\_call \(left=0x555555d39c40\, 
&nbsp;    right=0x555555d43580\, method=70\, flags=0\) at gv\.c&#8203;:3525
\#5  0x0000555555748b19 in Perl\_pp\_multiconcat \(\) at pp\_hot\.c&#8203;:1060

Each of these is added to the tmps stack\.

The second is in Perl\_pp\_multiconcat at the end of the magical value fallback code&#8203;:

\(gdb\) bt
\#0  S\_SvREFCNT\_inc \(sv=0x555555d204a8\) at inline\.h&#8203;:194
\#1  0x000055555578ab26 in Perl\_sv\_setsv\_flags \(dstr=0x555555d43580\, 
&nbsp;    sstr=0x555555d39880\, flags=1538\) at sv\.c&#8203;:4261
\#2  0x0000555555748d85 in Perl\_pp\_multiconcat \(\) at pp\_hot\.c&#8203;:1106

&nbsp;        if \(is\_append\)
&nbsp;            SvTAINT\(targ\);
&nbsp;        else \{
&nbsp;            sv\_setsv\(targ\, left\); \<\-\-\-
&nbsp;            SvSETMAGIC\(targ\);
&nbsp;        \}

targ here comes from the PAD&#8203;:

&nbsp;        SV \*\*svp = &\(PAD\_SVl\(PL\_op\->op\_targ\)\);
&nbsp;        targ = \*svp;

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, Jan 22\, 2019 at 04&#8203;:17&#8203;:47PM \-0800\, Tony Cook via RT wrote&#8203;:
> > Refs count should stay untouched\, but it increased on each iteration\.
> 
> This is present in blead too\.
> 
> There's two places the reference count is being incremented\.
> 
 \.\.\.

> The second is in Perl\_pp\_multiconcat at the end of the magical value fallback code&#8203;:
> 
> \(gdb\) bt
> \#0  S\_SvREFCNT\_inc \(sv=0x555555d204a8\) at inline\.h&#8203;:194
> \#1  0x000055555578ab26 in Perl\_sv\_setsv\_flags \(dstr=0x555555d43580\, 
>     sstr=0x555555d39880\, flags=1538\) at sv\.c&#8203;:4261
> \#2  0x0000555555748d85 in Perl\_pp\_multiconcat \(\) at pp\_hot\.c&#8203;:1106
> 
>         if \(is\_append\)
>             SvTAINT\(targ\);
>         else \{
>             sv\_setsv\(targ\, left\); \<\-\-\-
>             SvSETMAGIC\(targ\);
>         \}
> 
> targ here comes from the PAD&#8203;:
> 
>         SV \*\*svp = &\(PAD\_SVl\(PL\_op\->op\_targ\)\);
>         targ = \*svp;

After each call to multiconcat that returns an overloaded value\, its targ
will end up holding an extra ref to the overloaded value\. So its not a
open\-ended leak in the sense that calling multiconcat in a loop won't leak
more and more objects\, but just delay freeing the last object\.

I'll need to think a bit about the best way to avoid assigning to the
targ\.

\-\- 
Diplomacy is telling someone to go to hell in such a way that they'll
look forward to the trip

**Comment by p5pRT** [comment]
### From @jkeenan

On Tue\, 22 Jan 2019 10&#8203;:50&#8203;:40 GMT\, zdm@&#8203;softvisio\.net wrote&#8203;:
> This is a bug report for perl from zdm@&#8203;softvisio\.net\,
> generated with the help of perlbug 1\.41 running under perl 5\.28\.1\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
> 
> New memory leak was introduces in perl 5\.28\.
> Please\, see the discussion here&#8203;:
> https://stackoverflow.com/questions/54304341/perl-overload-
> concatenation\-operator\-problem
> 
> \#\!/usr/bin/env perl
> 
> use strict;
> use warnings;
> use Devel&#8203;::Refcount qw\[refcount\];
> 
> package AAA \{
>     use Devel&#8203;::Refcount qw\[refcount\];
> 
> use overload
>   '\.' => sub \{
>     print 'CONCAT\, REFCOUNT&#8203;: '\, refcount\( $\_\[0\] \)\, "\\n";
> 
> \# return AAA\->new;
> return $\_\[0\];
> \}\,
> fallback => 0;
> 
> sub new \{ return bless \{\}\, $\_\[0\] \}
> 
> sub DESTROY \{ print "DESTROY\\n" \}
> \}
> 
> print "\-\-\- start\\n";
> 
> \{
>     my $o = AAA\->new;
> 
> my $s = '1' \. \( '2' \. \( '3' \. \( '4' \. \( '5' \. $o \) \) \) \);
> 
> print "\-\-\- exit scope\\n";
> print 'REFCOUNT&#8203;: '\, refcount\($o\)\, "\\n";
> \}
> 
> print "\-\-\- end\\n";
> 
> 1;
> 
> Output&#8203;:
> 
> \-\-\- start
> CONCAT\, REFCOUNT&#8203;: 1
> CONCAT\, REFCOUNT&#8203;: 3
> CONCAT\, REFCOUNT&#8203;: 5
> CONCAT\, REFCOUNT&#8203;: 7
> CONCAT\, REFCOUNT&#8203;: 9
> \-\-\- exit scope
> REFCOUNT&#8203;: 6
> \-\-\- end
> DESTROY
> 
> Refs count should stay untouched\, but it increased on each iteration\.
> 

FWIW\, bisection points to this commit&#8203;:

\#\#\#\#\#
e839e6ed99c6b25aee589f56bb58de2f8fa00f41 is the first bad commit
commit e839e6ed99c6b25aee589f56bb58de2f8fa00f41
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Tue Aug 8 18&#8203;:42&#8203;:14 2017 \+0100

&nbsp;    Add OP\_MULTICONCAT op
&nbsp;    
&nbsp;    Allow multiple OP\_CONCAT\, OP\_CONST ops\, plus optionally an OP\_SASSIGN
&nbsp;    or OP\_STRINGIFY\, to be combined into a single OP\_MULTICONCAT op\, which can
&nbsp;    make things a \*lot\* faster&#8203;: 4x or more\.
\.\.\.
\#\#\#\#\#

Thank you very much\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Jan 24\, 2019 at 12&#8203;:00&#8203;:41PM \+0000\, Dave Mitchell wrote&#8203;:
> On Tue\, Jan 22\, 2019 at 04&#8203;:17&#8203;:47PM \-0800\, Tony Cook via RT wrote&#8203;:
> > > Refs count should stay untouched\, but it increased on each iteration\.
> > 
> > This is present in blead too\.
> > 
> > There's two places the reference count is being incremented\.
> > 
>  \.\.\.
> 
> > The second is in Perl\_pp\_multiconcat at the end of the magical value fallback code&#8203;:
> > 
> > \(gdb\) bt
> > \#0  S\_SvREFCNT\_inc \(sv=0x555555d204a8\) at inline\.h&#8203;:194
> > \#1  0x000055555578ab26 in Perl\_sv\_setsv\_flags \(dstr=0x555555d43580\, 
> >     sstr=0x555555d39880\, flags=1538\) at sv\.c&#8203;:4261
> > \#2  0x0000555555748d85 in Perl\_pp\_multiconcat \(\) at pp\_hot\.c&#8203;:1106
> > 
> >         if \(is\_append\)
> >             SvTAINT\(targ\);
> >         else \{
> >             sv\_setsv\(targ\, left\); \<\-\-\-
> >             SvSETMAGIC\(targ\);
> >         \}
> > 
> > targ here comes from the PAD&#8203;:
> > 
> >         SV \*\*svp = &\(PAD\_SVl\(PL\_op\->op\_targ\)\);
> >         targ = \*svp;
> 
> After each call to multiconcat that returns an overloaded value\, its targ
> will end up holding an extra ref to the overloaded value\. So its not a
> open\-ended leak in the sense that calling multiconcat in a loop won't leak
> more and more objects\, but just delay freeing the last object\.
> 
> I'll need to think a bit about the best way to avoid assigning to the
> targ\.

Now fixed in blead with this commit&#8203;:

&nbsp;    commit 4e521aaf3ed717774455b3906bd5aa46bc397319
&nbsp;    Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
&nbsp;    AuthorDate&#8203;: Tue Feb 5 13&#8203;:48&#8203;:21 2019 \+0000

&nbsp;    Avoid leak in multiconcat with overloading\.
&nbsp;    
&nbsp;    RT \#133789
&nbsp;    
&nbsp;    In the path taken through pp\_multiconcat\(\) when one or more args have
&nbsp;    side\-effects such tieing or overloading\, multiconcat has to decide
&nbsp;    whether to just return the result of all the concatting as\-is\, or to
&nbsp;    first assign it to an expression or variable if the op includes an
&nbsp;    implicit assign \(such as $lex = x\.y\.z or $a\[0\] = x\.y\.z\)\.
&nbsp;    
&nbsp;    The code was getting this right for those two cases\, and was also
&nbsp;    getting it right for the append cases \($lex \.= x\.y\.z and $a\[0\] \.= x\.y\.z\)\,
&nbsp;    which don't need assigns\. But for the bare case \(x\.y\.z\) it was assigning
&nbsp;    to the op's targ as well as returning the value\. Hence leaking a
&nbsp;    reference until destruction of the sub and its pad\.
&nbsp;    
&nbsp;    This commit stops the assign in that last case\.

which is part of this just\-pushed branch&#8203;:

&nbsp;    Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
&nbsp;    AuthorDate&#8203;: Tue Feb 5 14&#8203;:04&#8203;:32 2019 \+0000

&nbsp;    \[MERGE\] various overload fixups
&nbsp;    
&nbsp;    This branch contains several commits which simplify the code concerning
&nbsp;    the processing of a value returned by an overload method\, and
&nbsp;    specifically whether that value should be returned as\-is by the op\, or
&nbsp;    assigned to the targ / stack value&#8203;: $lex = x op y\) and \(x op= y\)
&nbsp;    respectively\.
&nbsp;    
&nbsp;    The final commit fixes a bug in pp\_multiconcat\. That op bypasses most of
&nbsp;    the code in those earlier commits and "rolls it's own"\, and which was
&nbsp;    getting the set/assign decision wrong in some cases\, causing a leak\.


\-\- 
"Foul and greedy Dwarf \- you have eaten the last candle\."
&nbsp;    \-\- "Hordes of the Things"\, BBC Radio\.

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.30\.0\, this and 160 other issues have been
resolved\.

Perl 5\.30\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.30.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
