### ISSUE TITLE
Tokenizer accepts garbage input

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16848]
Migrated from [rt.perl.org#133851](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133851) (status was 'rejected')

Searchable as RT133851$

**Comment by p5pRT** [comment]
### From @khwilliamson

This is a bug report for perl from khw@&#8203;khw\-xps\-8930\.\(none\)\,
generated with the help of perlbug 1\.41 running under perl 5\.29\.8\.




---
This code should result in the parser rejecting the program\, as it is
garbage\, but instead it gets interpreted as valid input\.

echo "MAAvAG0AAABbADAwsh8AAA==" | base64 \-d | tee test0084\.pl | \./perl 
\-Dr test0084\.pl

The generated \.pl looks like&#8203;:

od \-t x1 test0084\.pl
0000000 30 00 2f 00 6d 00 00 00 5b 00 30 30 b2 1f 00 00
0000020


---


---
Flags&#8203;:
&nbsp;     category=core
&nbsp;     severity=medium


---
Site configuration information for perl 5\.29\.8&#8203;:

Configured by khw at Sat Feb 16 12&#8203;:51&#8203;:23 MST 2019\.

Summary of my perl5 \(revision 5 version 29 subversion 8\) configuration&#8203;:
&nbsp;   Commit id&#8203;: 2cbd034e1cb70cf9cb1ae2a83967a24dd90ecc53
&nbsp;   Platform&#8203;:
&nbsp;     osname=linux
&nbsp;     osvers=4\.15\.0\-45\-generic
&nbsp;     archname=x86\_64\-linux\-thread\-multi\-ld
&nbsp;     uname='linux khw\-xps\-8930 4\.15\.0\-45\-generic \#48\-ubuntu smp tue jan 
29 16&#8203;:28&#8203;:13 utc 2019 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;     config\_args='\-des \-Uversiononly \-Dprefix=/home/khw/blead \-Dusedevel 
\-A'optimize=\-ggdb3' \-A'optimize=\-O0' \-Accflags='\-Wno\-deprecated' 
\-Dman1dir=none \-Dman3dir=none \-Dcc=g\+\+ \-DDEBUGGING \-Dusemorebits 
\-Dusecbacktrace \-Dusethreads'
&nbsp;     hint=recommended
&nbsp;     useposix=true
&nbsp;     d\_sigaction=define
&nbsp;     useithreads=define
&nbsp;     usemultiplicity=define
&nbsp;     use64bitint=define
&nbsp;     use64bitall=define
&nbsp;     uselongdouble=define
&nbsp;     usemymalloc=n
&nbsp;     default\_inc\_excludes\_dot=define
&nbsp;     bincompat5005=undef
&nbsp;   Compiler&#8203;:
&nbsp;     cc='g\+\+'
&nbsp;     ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-Wno\-deprecated \-fwrapv 
\-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong 
\-I/usr/local/include \-DUSE\_C\_BACKTRACE \-g \-D\_LARGEFILE\_SOURCE 
\-D\_FILE\_OFFSET\_BITS=64 \-D\_FORTIFY\_SOURCE=2'
&nbsp;     optimize='\-O2 \-ggdb3 \-O0'
&nbsp;     cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-Wno\-deprecated \-fwrapv 
\-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong 
\-I/usr/local/include'
&nbsp;     ccversion=''
&nbsp;     gccversion='7\.3\.0'
&nbsp;     gccosandvers=''
&nbsp;     intsize=4
&nbsp;     longsize=8
&nbsp;     ptrsize=8
&nbsp;     doublesize=8
&nbsp;     byteorder=12345678
&nbsp;     doublekind=3
&nbsp;     d\_longlong=define
&nbsp;     longlongsize=8
&nbsp;     d\_longdbl=define
&nbsp;     longdblsize=16
&nbsp;     longdblkind=3
&nbsp;     ivtype='long'
&nbsp;     ivsize=8
&nbsp;     nvtype='long double'
&nbsp;     nvsize=16
&nbsp;     Off\_t='off\_t'
&nbsp;     lseeksize=8
&nbsp;     alignbytes=16
&nbsp;     prototype=define
&nbsp;   Linker and Libraries&#8203;:
&nbsp;     ld='g\+\+'
&nbsp;     ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;     libpth=/usr/include/c\+\+/7 /usr/include/x86\_64\-linux\-gnu/c\+\+/7 
/usr/include/c\+\+/7/backward /usr/local/lib 
/usr/lib/gcc/x86\_64\-linux\-gnu/7/include\-fixed 
/usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib 
/usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;     libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;     perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;     libc=libc\-2\.27\.so
&nbsp;     so=so
&nbsp;     useshrplib=false
&nbsp;     libperl=libperl\.a
&nbsp;     gnulibc\_version='2\.27'
&nbsp;   Dynamic Linking&#8203;:
&nbsp;     dlsrc=dl\_dlopen\.xs
&nbsp;     dlext=so
&nbsp;     d\_dlsymun=undef
&nbsp;     ccdlflags='\-Wl\,\-E'
&nbsp;     cccdlflags='\-fPIC'
&nbsp;     lddlflags='\-shared \-O2 \-ggdb3 \-O0 \-L/usr/local/lib 
\-fstack\-protector\-strong'




---
@&#8203;INC for perl 5\.29\.8&#8203;:
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.29\.8/x86\_64\-linux\-thread\-multi\-ld
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.29\.8
&nbsp;     /home/khw/blead/lib/perl5/5\.29\.8/x86\_64\-linux\-thread\-multi\-ld
&nbsp;     /home/khw/blead/lib/perl5/5\.29\.8
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.29\.7
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.29\.6
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.29\.5
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.29\.4
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.29\.3
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.29\.2
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.29\.1
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.29\.0
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.28\.0
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.27\.11
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.27\.10
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.27\.9
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.27\.8
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.27\.7
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.27\.6
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.27\.5
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.27\.4
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.27\.3
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.27\.2
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.27\.1
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.27\.0
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.26\.0
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.25\.12
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.25\.11
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.25\.10
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.25\.9
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.25\.8
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.25\.7
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.25\.6
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.25\.5
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.25\.4
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.25\.3
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.25\.2
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.25\.1
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.24\.0
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.23\.10
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.23\.9
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.23\.8
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.23\.7
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.23\.6
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.23\.5
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.23\.4
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.23\.3
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.23\.2
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.23\.1
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.23\.0
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.22\.0
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.12
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.11
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.10
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.9
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.8
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.7
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.6
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.5
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.4
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.3
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.2
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.1
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.20\.0
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.19\.12
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.19\.11
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.19\.10
&nbsp;     /home/khw/blead/lib/perl5/site\_perl



---
Environment for perl 5\.29\.8&#8203;:
&nbsp;     HOME=/home/khw
&nbsp;     LANG=en\_US\.UTF\-8
&nbsp;     LANGUAGE=en
&nbsp;     LD\_LIBRARY\_PATH \(unset\)
&nbsp;     LOGDIR \(unset\)

PATH=/usr/lib/ccache&#8203;:/home/khw/bin&#8203;:/home/khw/perl5/perlbrew/bin&#8203;:/home/khw/print/bin&#8203;:/bin&#8203;:/usr/local/sbin&#8203;:/usr/local/bin&#8203;:/usr/sbin&#8203;:/usr/bin&#8203;:/sbin&#8203;:/usr/games&#8203;:/usr/local/games&#8203;:/snap/bin&#8203;:/home/khw/iands/www&#8203;:/home/khw/cxoffice/bin
&nbsp;     PERL5OPT=\-w
&nbsp;     PERL\_BADLANG \(unset\)
&nbsp;     PERL\_DIFF\_TOOL=wgdiff
&nbsp;     PERL\_POD\_PEDANTIC=1
&nbsp;     SHELL=/usr/bin/ksh

**Comment by p5pRT** [comment]
### From @jkeenan

On Sat\, 16 Feb 2019 20&#8203;:45&#8203;:24 GMT\, public@&#8203;khwilliamson\.com wrote&#8203;:
> This is a bug report for perl from khw@&#8203;khw\-xps\-8930\.\(none\)\,
> generated with the help of perlbug 1\.41 running under perl 5\.29\.8\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> This code should result in the parser rejecting the program\, as it is
> garbage\, but instead it gets interpreted as valid input\.
> 

Can you elaborate as to why the parser should reject this?  \(I suspect that few readers know much about that area\.\)

> echo "MAAvAG0AAABbADAwsh8AAA==" | base64 \-d | tee test0084\.pl | \./perl
> \-Dr test0084\.pl
> 
> The generated \.pl looks like&#8203;:
> 
> od \-t x1 test0084\.pl
> 0000000 30 00 2f 00 6d 00 00 00 5b 00 30 30 b2 1f 00 00
> 0000020
> 

When I run the generated perl program with a debugging perl built at blead\, I get&#8203;:

\#\#\#\#\#
$ \./bin/perl \-Ilib \-Dr test0084\.pl 
Compiling REx "\[%x\{3030\}%x\{1fb2\}"
Wide character in print at /home/jkeenan/learn/perl/p5p/test0084\.pl line 1\.
Unmatched \[ in regex; marked by \<\-\- HERE in m/\[ \<\-\- HERE 〰ᾲ/ at test0084\.pl line 1\.
Freeing REx&#8203;: "\[%x\{3030\}%x\{1fb2\}"
\#\#\#\#\#

Is that relevant to the bug?

Thank you very much\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @khwilliamson

On 2/16/19 5&#8203;:12 PM\, James E Keenan via RT wrote&#8203;:
> On Sat\, 16 Feb 2019 20&#8203;:45&#8203;:24 GMT\, public@&#8203;khwilliamson\.com wrote&#8203;:
>> This is a bug report for perl from khw@&#8203;khw\-xps\-8930\.\(none\)\,
>> generated with the help of perlbug 1\.41 running under perl 5\.29\.8\.
>>
>>
>> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
>> This code should result in the parser rejecting the program\, as it is
>> garbage\, but instead it gets interpreted as valid input\.
>>
> 
> Can you elaborate as to why the parser should reject this?  \(I suspect that few readers know much about that area\.\)
> 
>> echo "MAAvAG0AAABbADAwsh8AAA==" | base64 \-d | tee test0084\.pl | \./perl
>> \-Dr test0084\.pl
>>
>> The generated \.pl looks like&#8203;:
>>
>> od \-t x1 test0084\.pl
>> 0000000 30 00 2f 00 6d 00 00 00 5b 00 30 30 b2 1f 00 00
>> 0000020
>>
> 
> When I run the generated perl program with a debugging perl built at blead\, I get&#8203;:
> 
> \#\#\#\#\#
> $ \./bin/perl \-Ilib \-Dr test0084\.pl
> Compiling REx "\[%x\{3030\}%x\{1fb2\}"
> Wide character in print at /home/jkeenan/learn/perl/p5p/test0084\.pl line 1\.
> Unmatched \[ in regex; marked by \<\-\- HERE in m/\[ \<\-\- HERE 〰ᾲ/ at test0084\.pl line 1\.
> Freeing REx&#8203;: "\[%x\{3030\}%x\{1fb2\}"
> \#\#\#\#\#
> 
> Is that relevant to the bug?

No

> 
> Thank you very much\.
>

**Comment by p5pRT** [comment]
### From @khwilliamson

On 2/16/19 5&#8203;:12 PM\, James E Keenan via RT wrote&#8203;:
> On Sat\, 16 Feb 2019 20&#8203;:45&#8203;:24 GMT\, public@&#8203;khwilliamson\.com wrote&#8203;:
>> This is a bug report for perl from khw@&#8203;khw\-xps\-8930\.\(none\)\,
>> generated with the help of perlbug 1\.41 running under perl 5\.29\.8\.
>>
>>
>> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
>> This code should result in the parser rejecting the program\, as it is
>> garbage\, but instead it gets interpreted as valid input\.
>>
> 
> Can you elaborate as to why the parser should reject this?  \(I suspect that few readers know much about that area\.\)
> 
>> echo "MAAvAG0AAABbADAwsh8AAA==" | base64 \-d | tee test0084\.pl | \./perl
>> \-Dr test0084\.pl
>>
>> The generated \.pl looks like&#8203;:
>>
>> od \-t x1 test0084\.pl
>> 0000000 30 00 2f 00 6d 00 00 00 5b 00 30 30 b2 1f 00 00
>> 0000020

Notice all the NULs\.  This string is getting turned into something 
almost completely different\, with somehow it looking like
m/\[\\x\{\\xE3\\x80\\xB0\}\\x\{\\xE1\\xBE\\xB2\}

Most of those bytes aren't in the original\, The inital 0x30 \(a digit 0\) 
is gone\, etc\. etc\.
>>
> 
> When I run the generated perl program with a debugging perl built at blead\, I get&#8203;:
> 
> \#\#\#\#\#
> $ \./bin/perl \-Ilib \-Dr test0084\.pl
> Compiling REx "\[%x\{3030\}%x\{1fb2\}"
> Wide character in print at /home/jkeenan/learn/perl/p5p/test0084\.pl line 1\.
> Unmatched \[ in regex; marked by \<\-\- HERE in m/\[ \<\-\- HERE 〰ᾲ/ at test0084\.pl line 1\.
> Freeing REx&#8203;: "\[%x\{3030\}%x\{1fb2\}"
> \#\#\#\#\#
> 
> Is that relevant to the bug?
> 
> Thank you very much\.
>

**Comment by p5pRT** [comment]
### From @khwilliamson

On 2/16/19 7&#8203;:14 PM\, Karl Williamson wrote&#8203;:
> On 2/16/19 5&#8203;:12 PM\, James E Keenan via RT wrote&#8203;:
>> On Sat\, 16 Feb 2019 20&#8203;:45&#8203;:24 GMT\, public@&#8203;khwilliamson\.com wrote&#8203;:
>>> This is a bug report for perl from khw@&#8203;khw\-xps\-8930\.\(none\)\,
>>> generated with the help of perlbug 1\.41 running under perl 5\.29\.8\.
>>>
>>>
>>> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
>>> This code should result in the parser rejecting the program\, as it is
>>> garbage\, but instead it gets interpreted as valid input\.
>>>
>>
>> Can you elaborate as to why the parser should reject this?  \(I suspect 
>> that few readers know much about that area\.\)
>>
>>> echo "MAAvAG0AAABbADAwsh8AAA==" | base64 \-d | tee test0084\.pl | \./perl
>>> \-Dr test0084\.pl
>>>
>>> The generated \.pl looks like&#8203;:
>>>
>>> od \-t x1 test0084\.pl
>>> 0000000 30 00 2f 00 6d 00 00 00 5b 00 30 30 b2 1f 00 00
>>> 0000020
> 
> Notice all the NULs\.  This string is getting turned into something 
> almost completely different\, with somehow it looking like
> m/\[\\x\{\\xE3\\x80\\xB0\}\\x\{\\xE1\\xBE\\xB2\}
> 
> Most of those bytes aren't in the original\, The inital 0x30 \(a digit 0\) 
> is gone\, etc\. etc\.

Actually\, I see that 3030 and 1fb2 are in there if the string is 
interpreted as UTF\-8\, but how that's happening I don't know\.
>>>
>>
>> When I run the generated perl program with a debugging perl built at 
>> blead\, I get&#8203;:
>>
>> \#\#\#\#\#
>> $ \./bin/perl \-Ilib \-Dr test0084\.pl
>> Compiling REx "\[%x\{3030\}%x\{1fb2\}"
>> Wide character in print at /home/jkeenan/learn/perl/p5p/test0084\.pl 
>> line 1\.
>> Unmatched \[ in regex; marked by \<\-\- HERE in m/\[ \<\-\- HERE 〰ᾲ/ at 
>> test0084\.pl line 1\.
>> Freeing REx&#8203;: "\[%x\{3030\}%x\{1fb2\}"
>> \#\#\#\#\#
>>
>> Is that relevant to the bug?
>>
>> Thank you very much\.
>>
>

**Comment by p5pRT** [comment]
### From @hvds

On Sat\, 16 Feb 2019 19&#8203;:06&#8203;:47 \-0800\, public@&#8203;khwilliamson\.com wrote&#8203;:
> >>> The generated \.pl looks like&#8203;:
> >>>
> >>> od \-t x1 test0084\.pl
> >>> 0000000 30 00 2f 00 6d 00 00 00 5b 00 30 30 b2 1f 00 00
> >>> 0000020
> > 
> > Notice all the NULs\.  This string is getting turned into something 
> > almost completely different\, with somehow it looking like
> > m/\[\\x\{\\xE3\\x80\\xB0\}\\x\{\\xE1\\xBE\\xB2\}
> > 
> > Most of those bytes aren't in the original\, The inital 0x30 \(a digit 0\) 
> > is gone\, etc\. etc\.
> 
> Actually\, I see that 3030 and 1fb2 are in there if the string is 
> interpreted as UTF\-8\, but how that's happening I don't know\.

I think the input is getting detected as UCS\-2 because of the pattern of nuls in the initial bytes\. I don't recall OTTOMH where that happens\, but it's probably in the same place as BOM detection\.

Hugo

**Comment by p5pRT** [comment]
### From @khwilliamson

Hugo is right\.  The data looks like UTF\-16\, and is legal as that encoding\.
Rejecting this ticket
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'rejected'

**Comment by p5pRT** [comment]
### From @tonycoz

On Sun\, Feb 17\, 2019 at 08&#8203;:33&#8203;:40AM \-0800\, Karl Williamson via RT wrote&#8203;:
> Hugo is right\.  The data looks like UTF\-16\, and is legal as that encoding\.
> Rejecting this ticket

Where's it picking up the closing / for the regexp?

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon\, Feb 18\, 2019 at 08&#8203;:41&#8203;:21AM \+1100\, Tony Cook wrote&#8203;:
> On Sun\, Feb 17\, 2019 at 08&#8203;:33&#8203;:40AM \-0800\, Karl Williamson via RT wrote&#8203;:
> > Hugo is right\.  The data looks like UTF\-16\, and is legal as that encoding\.
> > Rejecting this ticket
> 
> Where's it picking up the closing / for the regexp?

Ahh\, nevermind\, it's C\<\< 0 / m\\0\.\.\.\\0 >>\.

Though with a \-DDEBUGGING build&#8203;:

$ \./perl \-v | grep version
This is perl 5\, version 29\, subversion 8 \(v5\.29\.8 \(v5\.29\.7\-97\-g8ff14b702b\)\) built for x86\_64\-linux
$ \./perl \.\./133851\.pl 
Segmentation fault
\.\.\.
Program received signal SIGSEGV\, Segmentation fault\.
0x00005555556d17e7 in S\_regclass \(pRExC\_state=0x7fffffffdd20\, 
&nbsp;    flagp=0x7fffffffd414\, depth=5\, stop\_at\_1=false\, allow\_multi\_folds=true\, 
&nbsp;    silence\_non\_portable=false\, strict=false\, optimizable=true\, 
&nbsp;    ret\_invlist=0x0\) at regcomp\.c&#8203;:18632
18632                           fold\_list = add\_cp\_to\_invlist\(fold\_list\,
\(gdb\) bt
\#0  0x00005555556d17e7 in S\_regclass \(pRExC\_state=0x7fffffffdd20\, 
&nbsp;    flagp=0x7fffffffd414\, depth=5\, stop\_at\_1=false\, allow\_multi\_folds=true\, 
&nbsp;    silence\_non\_portable=false\, strict=false\, optimizable=true\, 
&nbsp;    ret\_invlist=0x0\) at regcomp\.c&#8203;:18632
\#1  0x00005555556af993 in S\_regatom \(pRExC\_state=0x7fffffffdd20\, 
&nbsp;    flagp=0x7fffffffd414\, depth=4\) at regcomp\.c&#8203;:13232
\#2  0x00005555556a95b4 in S\_regpiece \(pRExC\_state=0x7fffffffdd20\, 
&nbsp;    flagp=0x7fffffffd530\, depth=3\) at regcomp\.c&#8203;:12472
\#3  0x00005555556a8e96 in S\_regbranch \(pRExC\_state=0x7fffffffdd20\, 
&nbsp;    flagp=0x7fffffffd5d4\, first=1\, depth=2\) at regcomp\.c&#8203;:12390
\#4  0x00005555556a6762 in S\_reg \(pRExC\_state=0x7fffffffdd20\, paren=0\, 
&nbsp;    flagp=0x7fffffffda58\, depth=1\) at regcomp\.c&#8203;:12111
\#5  0x0000555555689ecd in Perl\_re\_op\_compile \(patternp=0x0\, pat\_count=1\, 
&nbsp;    expr=0x555555d4c828\, eng=0x555555d17500 \<PL\_core\_reg\_engine>\, old\_re=0x0\, 
&nbsp;    is\_bare\_re=0x0\, orig\_rx\_flags=0\, pm\_flags=0\) at regcomp\.c&#8203;:7667
\#6  0x00005555555a62d5 in Perl\_pmruntime \(o=0x555555d4c868\, 
&nbsp;    expr=0x555555d4c828\, repl=0x0\, flags=1\, floor=0\) at op\.c&#8203;:7094
\#7  0x000055555565d140 in Perl\_yyparse \(gramtype=258\) at perly\.y&#8203;:1228
\#8  0x00005555555d86c9 in S\_parse\_body \(env=0x0\, 
&nbsp;    xsinit=0x55555558d373 \<xs\_init>\) at perl\.c&#8203;:2506
\#9  0x00005555555d6984 in perl\_parse \(my\_perl=0x555555d22010\, 
&nbsp;    xsinit=0x55555558d373 \<xs\_init>\, argc=2\, argv=0x7fffffffe868\, env=0x0\)
&nbsp;    at perl\.c&#8203;:1797
\-\-\-Type \<return> to continue\, or q \<return> to quit\-\-\-
\#10 0x000055555558d2b6 in main \(argc=2\, argv=0x7fffffffe868\, 
&nbsp;    env=0x7fffffffe880\) at perlmain\.c&#8203;:121
\(gdb\) p folds\_to\_this\_cp\_count
$1 = 0

which has type Size\_t and the block causing the problem&#8203;:

&nbsp;                    for \(i = 0; i \< folds\_to\_this\_cp\_count \- 1; i\+\+\) \{
&nbsp;                        fold\_list = add\_cp\_to\_invlist\(fold\_list\,
&nbsp;                                                        remaining\_folds\[i\]\);
&nbsp;                    \}

\(gdb\) p folded
$2 = 8114
\(gdb\) p/x folded
$3 = 0x1fb2

Tony

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon\, Feb 18\, 2019 at 08&#8203;:55&#8203;:57AM \+1100\, Tony Cook wrote&#8203;:
> which has type Size\_t and the block causing the problem&#8203;:
> 
>                     for \(i = 0; i \< folds\_to\_this\_cp\_count \- 1; i\+\+\) \{
>                         fold\_list = add\_cp\_to\_invlist\(fold\_list\,
>                                                         remaining\_folds\[i\]\);
>                     \}
> 
> \(gdb\) p folded
> $2 = 8114
> \(gdb\) p/x folded
> $3 = 0x1fb2

Which you fixed in c2d81cfd08d9a622c639058cd7eb870aa0991937\.

Tony
