### ISSUE TITLE
heap-buffer-overflow in Perl_pp_uc

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16858]
Migrated from [rt.perl.org#133876](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133876) (status was 'resolved')

Searchable as RT133876$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.8\-21\-gde59f38ed9 built with afl and run
under libdislocator\, I found the following program \(also attached to
this message\)

00000000  75 73 65 20 35 2e 30 32  36 3b 6d 2e 5c 55 30 30  |use 5\.026;m\.\\U00|
00000010  ff ff 30 30 30 30 2e                              |\.\.0000\.|

to cause a heap\-buffer\-overflow write\. This is a regression in blead\,
so not a security issue\, bisect points to&#8203;:

commit 2f8f985a27faf25c5a535cbe67d098690668c0f9
Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
Date&#8203;:   Wed Jan 30 11&#8203;:24&#8203;:12 2019 \-0700

&nbsp;    pp\.c&#8203;: Don't assume worst case memory needs

&nbsp;    Since 5\.28\, there has been a function that will calculate the expansion
&nbsp;    of a string when converted into UTF\-8\, using per\-word operations\.  This
&nbsp;    means it runs 8 times faster than doing this count previously would have
&nbsp;    taken\.

ASAN trace is following&#8203;:

==6160==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
0x60200000dafa at pc 0x000000adc959 bp 0x7ffcd26c09d0 sp
0x7ffcd26c09c8
WRITE of size 1 at 0x60200000dafa thread T0
&nbsp;    \#0 0xadc958 in Perl\_pp\_uc /home/afl/afl\-asan/pp\.c&#8203;:4344&#8203;:9
&nbsp;    \#1 0x88f844 in Perl\_runops\_debug /home/afl/afl\-asan/dump\.c&#8203;:2537&#8203;:23
&nbsp;    \#2 0x5d1a94 in S\_fold\_constants\_eval /home/afl/afl\-asan/op\.c&#8203;:5527&#8203;:2
&nbsp;    \#3 0x54f509 in S\_fold\_constants /home/afl/afl\-asan/op\.c&#8203;:5657&#8203;:11
&nbsp;    \#4 0x54e19d in Perl\_op\_convert\_list /home/afl/afl\-asan/op\.c&#8203;:5997&#8203;:12
&nbsp;    \#5 0x70ca11 in Perl\_yyparse /home/afl/afl\-asan/perly\.y&#8203;:903&#8203;:23
&nbsp;    \#6 0x5eba6a in S\_parse\_body /home/afl/afl\-asan/perl\.c&#8203;:2507&#8203;:9
&nbsp;    \#7 0x5e1e23 in perl\_parse /home/afl/afl\-asan/perl\.c&#8203;:1798&#8203;:2
&nbsp;    \#8 0x50b5de in main /home/afl/afl\-asan/perlmain\.c&#8203;:126&#8203;:10
&nbsp;    \#9 0x7f2f085a509a in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2409a\)
&nbsp;    \#10 0x43bdc9 in \_start \(/home/afl/afl\-asan/perl\+0x43bdc9\)

0x60200000dafa is located 0 bytes to the right of 10\-byte region
\[0x60200000daf0\,0x60200000dafa\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4da398 in malloc \(/home/afl/afl\-asan/perl\+0x4da398\)
&nbsp;    \#1 0x89580e in Perl\_safesysmalloc /home/afl/afl\-asan/util\.c&#8203;:153&#8203;:21
&nbsp;    \#2 0x9bb6e9 in Perl\_sv\_grow /home/afl/afl\-asan/sv\.c&#8203;:1599&#8203;:17
&nbsp;    \#3 0xad8b80 in Perl\_pp\_uc /home/afl/afl\-asan/pp\.c&#8203;:4082&#8203;:11
&nbsp;    \#4 0x88f844 in Perl\_runops\_debug /home/afl/afl\-asan/dump\.c&#8203;:2537&#8203;:23
&nbsp;    \#5 0x5d1a94 in S\_fold\_constants\_eval /home/afl/afl\-asan/op\.c&#8203;:5527&#8203;:2
&nbsp;    \#6 0x54f509 in S\_fold\_constants /home/afl/afl\-asan/op\.c&#8203;:5657&#8203;:11
&nbsp;    \#7 0x54e19d in Perl\_op\_convert\_list /home/afl/afl\-asan/op\.c&#8203;:5997&#8203;:12
&nbsp;    \#8 0x70ca11 in Perl\_yyparse /home/afl/afl\-asan/perly\.y&#8203;:903&#8203;:23
&nbsp;    \#9 0x5eba6a in S\_parse\_body /home/afl/afl\-asan/perl\.c&#8203;:2507&#8203;:9
&nbsp;    \#10 0x5e1e23 in perl\_parse /home/afl/afl\-asan/perl\.c&#8203;:1798&#8203;:2
&nbsp;    \#11 0x50b5de in main /home/afl/afl\-asan/perlmain\.c&#8203;:126&#8203;:10
&nbsp;    \#12 0x7f2f085a509a in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2409a\)

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @dur-randir

[0097_1](https://rt-archive.perl.org/perl5/Ticket/Attachment/1615919/833416/0097_1)

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @khwilliamson

Fixed by

commit 56e36cbf2fdf9d90f61690c1c3fc35af0d65e0cd
 Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
 Date&#8203;:   Fri Mar 8 10&#8203;:01&#8203;:48 2019 \-0700
 
&nbsp;     PATCH&#8203;: \[perl \#133876\] Write out of bounds
&nbsp;     
&nbsp;     This was caused by a lapse on my part about the inputs to this function
&nbsp;     that grows memory\.  I was thinking the trailing NUL was included\, but
&nbsp;     it's not\.  This patch adds space for that to all calls of
&nbsp;     sv\_utf8\_upgrade\_flags\_grow\(\) in the file\.
&nbsp;     
&nbsp;     But it occurs to me that maybe the function itself should just add one
&nbsp;     instead of having the caller do it\.  If you think so\, let me know\.
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'resolved'
