### ISSUE TITLE
heap-buffer-overflow in S_reginsert

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16853]
Migrated from [rt.perl.org#133871](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133871) (status was 'resolved')

Searchable as RT133871$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.8\-21\-gde59f38ed9 built with afl and run
under libdislocator\, I found the following program

/\(?|\(\(\)\)|\(\)\)|/

to cause a heap\-buffer\-overflow read\. This is a regression in blead\,
so not a security issue\, bisect points to&#8203;:

7c932d07cab18751bfc7515b4320436273a459e2 is the first bad commit
commit 7c932d07cab18751bfc7515b4320436273a459e2
Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
Date&#8203;:   Fri Oct 19 09&#8203;:48&#8203;:34 2018 \-0600

&nbsp;    Remove sizing pass from regular expression compiler

&nbsp;    This commit removes the sizing pass for regular expression compilation\.
&nbsp;    It attempts to be the minimum required to do this\.  Future patches are
&nbsp;    in the works that improve it\,\, and there is certainly lots more that
&nbsp;    could be done\.

ASAN trace is following&#8203;:

=================================================================
==48675==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
0x60200000dc80 at pc 0x000000818fa4 bp 0x7ffebb1d2230 sp
0x7ffebb1d2228
READ of size 8 at 0x60200000dc80 thread T0
&nbsp;    \#0 0x818fa3 in S\_reginsert /home/afl/afl\-asan/regcomp\.c&#8203;:19439&#8203;:27
&nbsp;    \#1 0x759279 in S\_reg /home/afl/afl\-asan/regcomp\.c&#8203;:12024&#8203;:6
&nbsp;    \#2 0x73b5ed in Perl\_re\_op\_compile /home/afl/afl\-asan/regcomp\.c&#8203;:7665&#8203;:9
&nbsp;    \#3 0x53fb8d in Perl\_pmruntime /home/afl/afl\-asan/op\.c&#8203;:7094&#8203;:6
&nbsp;    \#4 0x70be8c in Perl\_yyparse /home/afl/afl\-asan/perly\.y&#8203;:1228&#8203;:23
&nbsp;    \#5 0x5eba6a in S\_parse\_body /home/afl/afl\-asan/perl\.c&#8203;:2507&#8203;:9
&nbsp;    \#6 0x5e1e23 in perl\_parse /home/afl/afl\-asan/perl\.c&#8203;:1798&#8203;:2
&nbsp;    \#7 0x50b5de in main /home/afl/afl\-asan/perlmain\.c&#8203;:126&#8203;:10
&nbsp;    \#8 0x7f2684ba309a in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2409a\)
&nbsp;    \#9 0x43bdc9 in \_start \(/home/afl/afl\-asan/perl\+0x43bdc9\)

0x60200000dc80 is located 0 bytes to the right of 16\-byte region
\[0x60200000dc70\,0x60200000dc80\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4da570 in calloc \(/home/afl/afl\-asan/perl\+0x4da570\)
&nbsp;    \#1 0x896bce in Perl\_safesyscalloc /home/afl/afl\-asan/util\.c&#8203;:439&#8203;:18
&nbsp;    \#2 0x758969 in S\_reg /home/afl/afl\-asan/regcomp\.c&#8203;:11962&#8203;:21
&nbsp;    \#3 0x81c995 in S\_regatom /home/afl/afl\-asan/regcomp\.c&#8203;:13155&#8203;:15
&nbsp;    \#4 0x7fe6f9 in S\_regpiece /home/afl/afl\-asan/regcomp\.c&#8203;:12372&#8203;:11
&nbsp;    \#5 0x7fe6f9 in S\_regbranch /home/afl/afl\-asan/regcomp\.c&#8203;:12290
&nbsp;    \#6 0x7599be in S\_reg /home/afl/afl\-asan/regcomp\.c&#8203;:12055&#8203;:14
&nbsp;    \#7 0x81c995 in S\_regatom /home/afl/afl\-asan/regcomp\.c&#8203;:13155&#8203;:15
&nbsp;    \#8 0x7fe6f9 in S\_regpiece /home/afl/afl\-asan/regcomp\.c&#8203;:12372&#8203;:11
&nbsp;    \#9 0x7fe6f9 in S\_regbranch /home/afl/afl\-asan/regcomp\.c&#8203;:12290
&nbsp;    \#10 0x759015 in S\_reg /home/afl/afl\-asan/regcomp\.c&#8203;:12011&#8203;:10
&nbsp;    \#11 0x73b5ed in Perl\_re\_op\_compile /home/afl/afl\-asan/regcomp\.c&#8203;:7665&#8203;:9
&nbsp;    \#12 0x53fb8d in Perl\_pmruntime /home/afl/afl\-asan/op\.c&#8203;:7094&#8203;:6
&nbsp;    \#13 0x70be8c in Perl\_yyparse /home/afl/afl\-asan/perly\.y&#8203;:1228&#8203;:23
&nbsp;    \#14 0x5eba6a in S\_parse\_body /home/afl/afl\-asan/perl\.c&#8203;:2507&#8203;:9
&nbsp;    \#15 0x5e1e23 in perl\_parse /home/afl/afl\-asan/perl\.c&#8203;:1798&#8203;:2
&nbsp;    \#16 0x50b5de in main /home/afl/afl\-asan/perlmain\.c&#8203;:126&#8203;:10
&nbsp;    \#17 0x7f2684ba309a in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2409a\)

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @khwilliamson

Fixed by
 commit e0814905161f8420d3be47dd3883b1f3c9590a82
 Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
 Date&#8203;:   Wed Mar 13 19&#8203;:11&#8203;:46 2019 \-0600
 
&nbsp;     PATCH&#8203;: \[perl \#133871\] heap\-buffer\-overflow in S\_reginsert
&nbsp;     
&nbsp;     The regex compiler was written assuming it knew how many parentheses
&nbsp;     pairs there were at code generation time\.  When I converted to a single
&nbsp;     pass in 7c932d07cab18751bfc7515b4320436273a459e2\, most things were
&nbsp;     straight forward to not have to know this number\, but there were a few
&nbsp;     where it was non\-trivial \(for me anyway\) to figure out how to handle\.
&nbsp;     So I punted on these and do a second pass when these are encountered\.
&nbsp;     There are few of them and are less commonly used\, namely \(?R\)\, \(?|\.\.\.\)
&nbsp;     and forward references to groups \(which most commonly will end up being
&nbsp;     a syntax error anyway\)\.
&nbsp;     
&nbsp;     The fix in this commit is to avoid doing some parentheses relocations
&nbsp;     when a regnode is inserted when it is known that the parentheses counts
&nbsp;     are unreliable \(during initial parsing of one of these tricky
&nbsp;     constructs\)\.  The code in the ticket is using a branch reset '\(?|\.\.\.\)'\.
&nbsp;     A second pass will get done\, and the insert properly handled then\, after
&nbsp;     the counts are reliable\.

\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'resolved'
