### ISSUE TITLE
Assertion failure in Perl_sv_sethek (sv.c:5038)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16866]
Migrated from [rt.perl.org#133884](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133884) (status was 'new')

Searchable as RT133884$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.8\-21\-gde59f38ed9 built with afl and run
under libdislocator\, I found the following program

s/\(\(?\{caller\}\)\)//;foreach $\_ \(0\)\{foo\(\)\}sub foo\{//\}

to cause an assertion failure&#8203;:

perl&#8203;: sv\.c&#8203;:5038&#8203;: void Perl\_sv\_sethek\(SV \*const\, const HEK \*const\)&#8203;:
Assertion \`sv' failed\.

GDB stack trace is following&#8203;:

\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:50
\#1  0x00007ffff7c25535 in \_\_GI\_abort \(\) at abort\.c&#8203;:79
\#2  0x00007ffff7c2540f in \_\_assert\_fail\_base \(fmt=0x7ffff7d87ee0
"%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\, assertion=0x555555a892ce
"sv"\,
&nbsp;    file=0x555555a89860 "sv\.c"\, line=5038\, function=\<optimized out>\)
at assert\.c&#8203;:92
\#3  0x00007ffff7c330f2 in \_\_GI\_\_\_assert\_fail \(assertion=0x555555a892ce
"sv"\, file=0x555555a89860 "sv\.c"\, line=5038\,
&nbsp;    function=0x555555a9c2b8 \<\_\_PRETTY\_FUNCTION\_\_\.20568>
"Perl\_sv\_sethek"\) at assert\.c&#8203;:101
\#4  0x00005555557951ca in Perl\_sv\_sethek \(sv=0x0\, hek=0x555555b383d8\)
at sv\.c&#8203;:5038
\#5  0x000055555581b80f in Perl\_pp\_caller \(\) at pp\_ctl\.c&#8203;:1909
\#6  0x00005555556f692d in Perl\_runops\_debug \(\) at dump\.c&#8203;:2537
\#7  0x00005555558a701e in S\_regmatch \(reginfo=0x7fffffffdd00\,
startpos=0x555555b53510 "0"\, prog=0x555555b533dc\) at regexec\.c&#8203;:7321
\#8  0x0000555555899513 in S\_regtry \(reginfo=0x7fffffffdd00\,
startposp=0x7fffffffdac8\) at regexec\.c&#8203;:3933
\#9  0x0000555555898e7e in Perl\_regexec\_flags \(rx=0x555555b4b520\,
stringarg=0x555555b53510 "0"\, strend=0x555555b53511 ""\,
strbeg=0x555555b53510 "0"\,
&nbsp;    minend=0\, sv=0x555555b4b5c8\, data=0x0\, flags=97\) at regexec\.c&#8203;:3790
\#10 0x0000555555754e89 in Perl\_pp\_match \(\) at pp\_hot\.c&#8203;:3018
\#11 0x00005555556f692d in Perl\_runops\_debug \(\) at dump\.c&#8203;:2537
\#12 0x00005555555da124 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2692
\#13 0x00005555555d96a2 in perl\_run \(my\_perl=0x555555b24260\) at perl\.c&#8203;:2615
\#14 0x000055555558e12e in main \(argc=2\, argv=0x7fffffffe1e8\,
env=0x7fffffffe200\) at perlmain\.c&#8203;:127

This is a regression between 5\.18 and 5\.20\, bisect points to

commit ce0d59fdd1c7d145efdf6bf8da56a259fed483e4
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Tue Jul 2 13&#8203;:07&#8203;:45 2013 \-0700

&nbsp;    \[perl \#7508\] Use NULL for nonexistent array elems

&nbsp;    This commit fixes bug \#7508 and provides the groundwork for fixing
&nbsp;    several other bugs\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>

**Comment by richardleach** [comment]
The `caller` OP has a `targ` assigned (`1`), but that contains NULL, not a SV*. Why?

**Comment by richardleach** [comment]
> The `caller` OP has a `targ` assigned (`1`), but that contains NULL, not a SV*. Why?

Something to do with the context in which regex code blocks are executed. (`PL_curpad` is also NULL - no pad?)

**Comment by richardleach** [comment]
_regexec.c_ has changed a fair bit since the breaking commit. The relevant code is somewhere around this today:
```
                /* we don't use MULTICALL here as we want to call the
                 * first op of the block of interest, rather than the
                 * first op of the sub. Also, we don't want to free
                 * the savestack frame */
                before = (IV)(SP-PL_stack_base);
                PL_op = nop;
                CALLRUNOPS(aTHX);                       /* Scalar context. */
                SPAGAIN;
                if ((IV)(SP-PL_stack_base) == before)
                    ret = &PL_sv_undef;   /* protect against empty (?{}) blocks. */
                else {
                    ret = POPs;
                    PUTBACK;
                }
```
