### ISSUE TITLE
Assertion failure in glob3 (bsd_glob.c:759)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16869]
Migrated from [rt.perl.org#133888](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133888) (status was 'open')

Searchable as RT133888$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.8\-21\-gde59f38ed9 built with afl and run
under libdislocator\, I found the program attached to this message to
cause an assertion failure&#8203;:

perl&#8203;: bsd\_glob\.c&#8203;:759&#8203;: int glob3\(Char \*\, Char \*\, Char \*\, Char \*\, Char
\*\, Char \*\, Char \*\, glob\_t \*\, size\_t \*\)&#8203;: Assertion \`restpattern \<
restpattern\_last' failed\.

GDB stack trace is following&#8203;:

\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:50
\#1  0x00007ffff7c25535 in \_\_GI\_abort \(\) at abort\.c&#8203;:79
\#2  0x00007ffff7c2540f in \_\_assert\_fail\_base \(fmt=0x7ffff7d87ee0
"%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\,
&nbsp;    assertion=0x7ffff7917040 "restpattern \< restpattern\_last"\,
file=0x7ffff7917003 "bsd\_glob\.c"\, line=759\, function=\<optimized out>\)
at assert\.c&#8203;:92
\#3  0x00007ffff7c330f2 in \_\_GI\_\_\_assert\_fail
\(assertion=assertion@&#8203;entry=0x7ffff7917040 "restpattern \<
restpattern\_last"\,
&nbsp;    file=file@&#8203;entry=0x7ffff7917003 "bsd\_glob\.c"\, line=line@&#8203;entry=759\,
function=function@&#8203;entry=0x7ffff791705f \<\_\_PRETTY\_FUNCTION\_\_\.17683>
"glob3"\)
&nbsp;    at assert\.c&#8203;:101
\#4  0x00007ffff791323b in glob3 \(pathbuf=pathbuf@&#8203;entry=0x7fffffff9cb0\,
pathbuf\_last=0x7fffffffbcae\, pathend=pathend@&#8203;entry=0x7fffffff9cb0\,
&nbsp;    pathend\_last=pathend\_last@&#8203;entry=0x7fffffffbcae\,
pattern=0x7fffffff7cb0\, restpattern=0x7fffffff9cae\,
restpattern\_last=0x7fffffff9cae\,
&nbsp;    pglob=0x7fffffffdd60\, limitp=0x7fffffff7ca8\) at bsd\_glob\.c&#8203;:759
\#5  0x00007ffff7912af3 in glob2 \(pathbuf=pathbuf@&#8203;entry=0x7fffffff9cb0\,
pathbuf\_last=pathbuf\_last@&#8203;entry=0x7fffffffbcae\,
pathend=pathend@&#8203;entry=0x7fffffff9cb0\,
&nbsp;    pathend\_last=pathend\_last@&#8203;entry=0x7fffffffbcae\, pattern=\<optimized
out>\, pattern@&#8203;entry=0x7fffffff7cb0\,
pattern\_last=pattern\_last@&#8203;entry=0x7fffffff9cae\,
&nbsp;    pglob=0x7fffffffdd60\, limitp=0x7fffffff7ca8\) at bsd\_glob\.c&#8203;:732
\#6  0x00007ffff79135fb in glob2 \(limitp=0x7fffffff7ca8\,
pglob=0x7fffffffdd60\, pattern\_last=0x7fffffff9cae\,
pattern=0x7fffffff7cb0\,
&nbsp;    pathend\_last=0x7fffffffbcae\, pathend=0x7fffffff9cb0\,
pathbuf\_last=0x7fffffffbcae\, pathbuf=0x7fffffff9cb0\) at bsd\_glob\.c&#8203;:668
\#7  glob1 \(limitp=0x7fffffff7ca8\, pglob=0x7fffffffdd60\,
pattern\_last=0x7fffffff9cae\, pattern=0x7fffffff7cb0\) at bsd\_glob\.c&#8203;:650
\#8  glob0 \(pattern=pattern@&#8203;entry=0x7fffffffbd30\,
pglob=pglob@&#8203;entry=0x7fffffffdd60\) at bsd\_glob\.c&#8203;:584
\#9  0x00007ffff7913a43 in globexp1 \(pattern=0x7fffffffbd30\,
pglob=pglob@&#8203;entry=0x7fffffffdd60\) at bsd\_glob\.c&#8203;:316
\#10 0x00007ffff7913b3e in bsd\_glob
\(pattern=pattern@&#8203;entry=0x5555559b6610 "0\<0>"\, '0' \<repeats 45 times>\,
"'"\, '0' \<repeats 150 times>\.\.\.\,
&nbsp;    flags=flags@&#8203;entry=11904\, errfunc=errfunc@&#8203;entry=0x7ffff7913bf0
\<errfunc>\, pglob=pglob@&#8203;entry=0x7fffffffdd60\) at bsd\_glob\.c&#8203;:292
\#11 0x00007ffff7913ced in doglob \(pattern=pattern@&#8203;entry=0x5555559b6610
"0\<0>"\, '0' \<repeats 45 times>\, "'"\, '0' \<repeats 150 times>\.\.\.\,
&nbsp;    flags=flags@&#8203;entry=11904\) at Glob\.xs&#8203;:49
\#12 0x00007ffff7915a66 in csh\_glob
\(entries=entries@&#8203;entry=0x555555989710\, pat=\<optimized out>\,
len=\<optimized out>\, is\_utf8=\<optimized out>\) at Glob\.xs&#8203;:282
\#13 0x00007ffff79143a2 in iterate \(globber=0x7ffff7915440 \<csh\_glob>\)
at Glob\.xs&#8203;:118
\#14 0x000055555571d148 in Perl\_pp\_glob \(\) at pp\_sys\.c&#8203;:364
\#15 0x0000555555655792 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2535
\#16 0x00005555555c45f0 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2694
\#17 perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2617
\#18 0x000055555558d1d2 in main \(argc=\<optimized out>\, argv=\<optimized
out>\, env=\<optimized out>\) at perlmain\.c&#8203;:122

This is a regression between 5\.18 and 5\.20\, bisect points to

commit 46a847d35219c7d246a7d6498769055e62afb5f3
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Wed Nov 13 12&#8203;:33&#8203;:40 2013 \+0000

&nbsp;    File&#8203;::Glob&#8203;: silence some compiler warnings

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @dur-randir

[0054](https://rt-archive.perl.org/perl5/Ticket/Attachment/1616306/833514/0054)

**Comment by p5pRT** [comment]
### From @tonycoz

On Sun\, 03 Mar 2019 11&#8203;:33&#8203;:07 \-0800\, randir wrote&#8203;:
> This is a bug report for perl from sergey\.aleynikov@&#8203;gmail\.com\,
> generated with the help of perlbug 1\.41 running under perl 5\.29\.9\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
> 
> While fuzzing perl v5\.29\.8\-21\-gde59f38ed9 built with afl and run
> under libdislocator\, I found the program attached to this message to
> cause an assertion failure&#8203;:
> 
> perl&#8203;: bsd\_glob\.c&#8203;:759&#8203;: int glob3\(Char \*\, Char \*\, Char \*\, Char \*\, Char
> \*\, Char \*\, Char \*\, glob\_t \*\, size\_t \*\)&#8203;: Assertion \`restpattern \<
> restpattern\_last' failed\.
> 

I believe this is an error in the assertion\.

The pattern in this case is exactly 4095 bytes long\, you can reproduce this with&#8203;:

 my $str = \("0" x 4094\) \. "?";
 glob $str;

At the point of the call to glob3\(\) restpattern points one past the end of the pattern \(ie\. at the terminating NUL for a simple glob\) and restpattern\_last points at the last byte in the buffer \(\*not\* one past the end\) ie\. patbuf \+ MAXPATHLEN \-1 \(patbuf in glob0\(\)\)\.

So in this case they're equal and the assertion fails\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by tonycoz** [comment]
From the discussion in #24710 this seems to be limited to linux and cygwin.

**Comment by tonycoz** [comment]
> From the discussion in [#24710](https://github.com/Perl/perl5/pull/24710) this seems to be limited to linux and cygwin.

Not quite, this depends on MAXPATHLEN which is platform dependent.

On MacOS I can run:
```
% ./perl -Ilib -E 'for my $sz (1..8192) { say $sz; my $g = ("0" x $sz) . "?"; glob $g; }'
```
and get:
```
...
1022
Assertion failed: (restpattern < restpattern_last), function glob3, file bsd_glob.c, line 755.
zsh: abort      ./perl -Ilib -E 
```
