### ISSUE TITLE
Segfault in Perl_was_lvalue_sub

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16875]
Migrated from [rt.perl.org#133902](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133902) (status was 'new')

Searchable as RT133902$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.8\-21\-gde59f38ed9 built with afl and run
under libdislocator\, I found the following program to segfault

eval q\!local sub\{while\(\)\{0\->\[0\]\{0\}\[0\]\}\}\->\(\)\!

GDB stack trace is following&#8203;:

\#0  0x0000555555818abb in Perl\_was\_lvalue\_sub \(\) at pp\_ctl\.c&#8203;:1398
\#1  0x00005555557451ef in S\_cx\_pushsub \(cx=0x555555b29270\,
cv=0x555555b40f18\, retop=0x555555b51280\, hasargs=true\) at
inline\.h&#8203;:2042
\#2  0x0000555555764210 in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:5117
\#3  0x00005555556f692d in Perl\_runops\_debug \(\) at dump\.c&#8203;:2537
\#4  0x00005555555da124 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2692
\#5  0x00005555555d96a2 in perl\_run \(my\_perl=0x555555b24260\) at perl\.c&#8203;:2615
\#6  0x000055555558e12e in main \(argc=3\, argv=0x7fffffffe1b8\,
env=0x7fffffffe1d8\) at perlmain\.c&#8203;:127

This is a regression between 5\.26 and 5\.28\, bisect points to

e839e6ed99c6b25aee589f56bb58de2f8fa00f41 is the first bad commit
commit e839e6ed99c6b25aee589f56bb58de2f8fa00f41
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Tue Aug 8 18&#8203;:42&#8203;:14 2017 \+0100

&nbsp;    Add OP\_MULTICONCAT op

&nbsp;    Allow multiple OP\_CONCAT\, OP\_CONST ops\, plus optionally an OP\_SASSIGN
&nbsp;    or OP\_STRINGIFY\, to be combined into a single OP\_MULTICONCAT op\, which can
&nbsp;    make things a \*lot\* faster&#8203;: 4x or more\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>
