### ISSUE TITLE
Assertion failure in S_ReANY/S_regmatch

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16878]
Migrated from [rt.perl.org#133908](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133908) (status was 'open')

Searchable as RT133908$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.8\-21\-gde59f38ed9 built with afl and run
under libdislocator\, I found the following program

```
s,(?{$$=t;$$$=qr{(?{})}})@0(??{$$$$=qr{$$$]}}),,
```

to cause an assertion failure

perl&#8203;: inline\.h&#8203;:182&#8203;: S\_ReANY&#8203;: Assertion \`isREGEXP\(re\)' failed\.

GDB stack trace is following&#8203;:

\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:50
\#1  0x00007ffff7c25535 in \_\_GI\_abort \(\) at abort\.c&#8203;:79
\#2  0x00007ffff7c2540f in \_\_assert\_fail\_base \(fmt=0x7ffff7d87ee0
"%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\, assertion=0x555555ac4937
"isREGEXP\(re\)"\,
&nbsp;    file=0x555555ac4811 "inline\.h"\, line=182\, function=\<optimized
out>\) at assert\.c&#8203;:92
\#3  0x00007ffff7c330f2 in \_\_GI\_\_\_assert\_fail \(assertion=0x555555ac4937
"isREGEXP\(re\)"\, file=0x555555ac4811 "inline\.h"\, line=182\,
&nbsp;    function=0x555555ad7ce8 \<\_\_PRETTY\_FUNCTION\_\_\.17420> "S\_ReANY"\) at
assert\.c&#8203;:101
\#4  0x000055555588377b in S\_ReANY \(re=0x555555b47ef0\) at inline\.h&#8203;:182
\#5  0x00005555558a6a07 in S\_regmatch \(reginfo=0x7fffffffdb90\,
startpos=0x555555a9174b ""\, prog=0x555555b547dc\) at regexec\.c&#8203;:7184
\#6  0x0000555555899bd9 in S\_regtry \(reginfo=0x7fffffffdb90\,
startposp=0x7fffffffd958\) at regexec\.c&#8203;:3928
\#7  0x0000555555899559 in Perl\_regexec\_flags \(rx=0x555555b2d8f0\,
stringarg=0x555555a9174b ""\, strend=0x555555a9174b ""\,
strbeg=0x555555a9174b ""\, minend=0\,
&nbsp;    sv=0x555555b47d70\, data=0x0\, flags=1\) at regexec\.c&#8203;:3791
\#8  0x000055555575eb1b in Perl\_pp\_subst \(\) at pp\_hot\.c&#8203;:4231
\#9  0x00005555556f6ff4 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2537
\#10 0x00005555555da157 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2692
\#11 0x00005555555d96d5 in perl\_run \(my\_perl=0x555555b2b260\) at perl\.c&#8203;:2615
\#12 0x000055555558e14e in main \(argc=3\, argv=0x7fffffffe1a8\,
env=0x7fffffffe1c8\) at perlmain\.c&#8203;:127

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>
[edit 2020-04-05 hvds: replace escaped code with literal code wrapped in backticks, for ease of pasting]

**Comment by p5pRT** [comment]
### From @khwilliamson

On Thu\, 07 Mar 2019 15&#8203;:45&#8203;:00 \-0800\, randir wrote&#8203;:
> This is a bug report for perl from sergey\.aleynikov@&#8203;gmail\.com\,
> generated with the help of perlbug 1\.41 running under perl 5\.29\.9\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
> 
> While fuzzing perl v5\.29\.8\-21\-gde59f38ed9 built with afl and run
> under libdislocator\, I found the following program
> 
> s\,\(?\{$$=t;$$$=qr\{\(?\{\}\)\}\}\)@&#8203;0\(??\{$$$$=qr\{$$$\]\}\}\)\,\,
> 
> to cause an assertion failure
> 
> perl&#8203;: inline\.h&#8203;:182&#8203;: S\_ReANY&#8203;: Assertion \`isREGEXP\(re\)' failed\.
> 
> GDB stack trace is following&#8203;:
> 
> \#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at
> \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:50
> \#1  0x00007ffff7c25535 in \_\_GI\_abort \(\) at abort\.c&#8203;:79
> \#2  0x00007ffff7c2540f in \_\_assert\_fail\_base \(fmt=0x7ffff7d87ee0
> "%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\, assertion=0x555555ac4937
> "isREGEXP\(re\)"\,
>     file=0x555555ac4811 "inline\.h"\, line=182\, function=\<optimized
> out> \) at assert\.c&#8203;:92
> \#3  0x00007ffff7c330f2 in \_\_GI\_\_\_assert\_fail \(assertion=0x555555ac4937
> "isREGEXP\(re\)"\, file=0x555555ac4811 "inline\.h"\, line=182\,
>     function=0x555555ad7ce8 \<\_\_PRETTY\_FUNCTION\_\_\.17420> "S\_ReANY"\) at
> assert\.c&#8203;:101
> \#4  0x000055555588377b in S\_ReANY \(re=0x555555b47ef0\) at inline\.h&#8203;:182
> \#5  0x00005555558a6a07 in S\_regmatch \(reginfo=0x7fffffffdb90\,
> startpos=0x555555a9174b ""\, prog=0x555555b547dc\) at regexec\.c&#8203;:7184
> \#6  0x0000555555899bd9 in S\_regtry \(reginfo=0x7fffffffdb90\,
> startposp=0x7fffffffd958\) at regexec\.c&#8203;:3928
> \#7  0x0000555555899559 in Perl\_regexec\_flags \(rx=0x555555b2d8f0\,
> stringarg=0x555555a9174b ""\, strend=0x555555a9174b ""\,
> strbeg=0x555555a9174b ""\, minend=0\,
>     sv=0x555555b47d70\, data=0x0\, flags=1\) at regexec\.c&#8203;:3791
> \#8  0x000055555575eb1b in Perl\_pp\_subst \(\) at pp\_hot\.c&#8203;:4231
> \#9  0x00005555556f6ff4 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2537
> \#10 0x00005555555da157 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2692
> \#11 0x00005555555d96d5 in perl\_run \(my\_perl=0x555555b2b260\) at
> perl\.c&#8203;:2615
> \#12 0x000055555558e14e in main \(argc=3\, argv=0x7fffffffe1a8\,
> env=0x7fffffffe1c8\) at perlmain\.c&#8203;:127
> 

Here's what 're' looks like at the point where the assertion fails

SV = PVMG\(0x555555e1c8c8\) at 0x555555e29770
&nbsp;  REFCNT = 4
&nbsp;  FLAGS = \(OBJECT\,ROK\)
&nbsp;  IV = 0
&nbsp;  NV = 0
&nbsp;  RV = 0x555555e29998
&nbsp;    SV = REGEXP\(0x555555e270a8\) at 0x555555e29998
&nbsp;      REFCNT = 2
&nbsp;      FLAGS = \(OBJECT\,POK\,FAKE\,pPOK\)
&nbsp;      PV = 0x555555e2b328 "\(?^&#8203;:\(?^&#8203;:\(?\{\}\)\)\]\)"
&nbsp;      CUR = 16
&nbsp;      LEN = 0
&nbsp;      STASH = 0x555555e09bf8    "Regexp"
&nbsp;      COMPFLAGS = 0x0 \(\)
&nbsp;      EXTFLAGS = 0x620000 \(EVAL\_SEEN\,USE\_INTUIT\_NOML\,USE\_INTUIT\_ML\)
&nbsp;      ENGINE = 0x555555dc5480 \(STANDARD\)
&nbsp;      INTFLAGS = 0x0 \(\)
&nbsp;      NPARENS = 0
&nbsp;      LASTPAREN = 0
&nbsp;      LASTCLOSEPAREN = 0
&nbsp;      MINLEN = 1
&nbsp;      MINLENRET = 1
&nbsp;      GOFS = 0
&nbsp;      PRE\_PREFIX = 4
&nbsp;      SUBLEN = 0
&nbsp;      SUBOFFSET = 0
&nbsp;      SUBCOFFSET = 0
&nbsp;      SUBBEG = 0x0
&nbsp;      MOTHER\_RE = 0x555555e29818
&nbsp;        SV = REGEXP\(0x555555e26fe0\) at 0x555555e29818
&nbsp;          REFCNT = 3
&nbsp;          FLAGS = \(POK\,pPOK\)
&nbsp;          PV = 0x555555e2b328 "\(?^&#8203;:\(?^&#8203;:\(?\{\}\)\)\]\)"
&nbsp;          CUR = 16
&nbsp;          LEN = 18
&nbsp;          COMPFLAGS = 0x0 \(\)
&nbsp;          EXTFLAGS = 0x620000 \(EVAL\_SEEN\,USE\_INTUIT\_NOML\,USE\_INTUIT\_ML\)
&nbsp;          ENGINE = 0x555555dc5480 \(STANDARD\)
&nbsp;          INTFLAGS = 0x0 \(\)
&nbsp;          NPARENS = 0
&nbsp;          LASTPAREN = 0
&nbsp;          LASTCLOSEPAREN = 0
&nbsp;          MINLEN = 1
&nbsp;          MINLENRET = 1
&nbsp;          GOFS = 0
&nbsp;          PRE\_PREFIX = 4
&nbsp;          SUBLEN = 0
&nbsp;          SUBOFFSET = 0
&nbsp;          SUBCOFFSET = 0
&nbsp;          SUBBEG = 0x0
&nbsp;          MOTHER\_RE = 0x0
&nbsp;          PAREN\_NAMES = 0x0
&nbsp;          SUBSTRS = 0x555555e21c28
&nbsp;          PPRIVATE = 0x555555e2b5f8
&nbsp;          OFFS = 0x555555e2b578
&nbsp;          QR\_ANONCV = 0x0
&nbsp;          SAVED\_COPY = 0x0
&nbsp;      PAREN\_NAMES = 0x0
&nbsp;      SUBSTRS = 0x555555e2bb88
&nbsp;      PPRIVATE = 0x555555e2b5f8
&nbsp;      OFFS = 0x555555e2c3a8
&nbsp;      QR\_ANONCV = 0x0
&nbsp;      SAVED\_COPY = 0x0
&nbsp;  PV = 0x555555e29998 "\\250p\\342UUU\\0\\0\\2\\0"
&nbsp;  CUR = 10
&nbsp;  LEN = 0
&nbsp;  STASH = 0x555555e09bf8    "Regexp"


\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by xsawyerx** [comment]
@khwilliamson thoughts on a fix?

**Comment by khwilliamson** [comment]
Since this involves code blocks which @iabyn understands much better than I, I'm hoping he will look at it.

**Comment by hvds** [comment]
FWIW I've not been able to reproduce this, can we unravel the code a bit to make clearer what's in play? Eg, can we replace `$$` with `$x`, or replace `$$` with a literal `t` (and then elide the `$$=t`)? Can we replace `@0` with something less magical, or remove it?

I tried with 3 of my standard builds: gcc, clang + sanitize=address, clang + sanitize=undefined; in each case built with DEBUGGING and otherwise standard options. (clang is: 6.0.0-1ubuntu2). If you have a build recipe for reproducing it, that would be useful too.

**Comment by dur-randir** [comment]
@xsawyerx, this is a regression before 5.18, I don't think it's too important


@hvds, either copy from the original RT ticket (looks like it was broken in transition), or this is a hex dump of it, DDEBUGGING build is enough:

00000000  73 2c 28 3f 7b 24 24 3d  74 3b 24 24 24 3d 71 72  |s,(?{$$=t;$$$=qr|
00000010  7b 28 3f 7b 7d 29 7d 7d  29 40 30 28 3f 3f 7b 24  |{(?{})}})@0(??{$|
00000020  24 24 24 3d 71 72 7b 24  24 24 5d 7d 7d 29 2c 2c  |$$$=qr{$$$]}}),,|

**Comment by hvds** [comment]
> @hvds, either copy from the original RT ticket (looks like it was broken in transition), or this is a hex dump of it, DDEBUGGING build is enough

Thanks, looks like there was an additional HTML-escaped character in there; I've taken the liberty of editing the converted post to replace the escaping with literal code.

**Comment by hvds** [comment]
It simplifies at least to: `./miniperl -e '$t = qr{(?{ })}; /(??{ $$t = qr{$t-} })/'`.

I'd be tempted to make the assert a mandatory panic, but I agree it doesn't seem urgent.
