### ISSUE TITLE
Assertion failure in Perl_av_push/S_handle_regex_sets

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16870]
Migrated from [rt.perl.org#133889](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133889) (status was 'resolved')

Searchable as RT133889$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.8\-21\-gde59f38ed9 built with afl and run
under libdislocator\, I found the following program

s>\(?\[\\P\{Is0\}>>

to cause an assertion failure&#8203;:

perl&#8203;: av\.c&#8203;:611&#8203;: Perl\_av\_push&#8203;: Assertion \`val' failed\.

GDB stack trace is following&#8203;:

\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:50
\#1  0x00007ffff7c25535 in \_\_GI\_abort \(\) at abort\.c&#8203;:79
\#2  0x00007ffff7c2540f in \_\_assert\_fail\_base \(fmt=0x7ffff7d87ee0
"%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\, assertion=0x555555a85d7b
"val"\,
&nbsp;    file=0x555555a85b16 "av\.c"\, line=611\, function=\<optimized out>\) at
assert\.c&#8203;:92
\#3  0x00007ffff7c330f2 in \_\_GI\_\_\_assert\_fail \(assertion=0x555555a85d7b
"val"\, file=0x555555a85b16 "av\.c"\, line=611\,
&nbsp;    function=0x555555a85e98 \<\_\_PRETTY\_FUNCTION\_\_\.18075>
"Perl\_av\_push"\) at assert\.c&#8203;:101
\#4  0x00005555557421cd in Perl\_av\_push \(av=0x555555b4b110\, val=0x0\) at av\.c&#8203;:611
\#5  0x00005555556c1214 in S\_handle\_regex\_sets
\(pRExC\_state=0x7fffffffd690\, return\_invlist=0x0\, flagp=0x7fffffffcaf8\,
depth=6\,
&nbsp;    oregcomp\_parse=0x555555b4f611 "?\[\\\\P\{Is0\}"\) at regcomp\.c&#8203;:16065
\#6  0x00005555556a5078 in S\_reg \(pRExC\_state=0x7fffffffd690\, paren=91\,
flagp=0x7fffffffcaf8\, depth=5\) at regcomp\.c&#8203;:11917
\#7  0x00005555556af40f in S\_regatom \(pRExC\_state=0x7fffffffd690\,
flagp=0x7fffffffcd84\, depth=4\) at regcomp\.c&#8203;:13155
\#8  0x00005555556a8d11 in S\_regpiece \(pRExC\_state=0x7fffffffd690\,
flagp=0x7fffffffcea0\, depth=3\) at regcomp\.c&#8203;:12372
\#9  0x00005555556a85f9 in S\_regbranch \(pRExC\_state=0x7fffffffd690\,
flagp=0x7fffffffcf44\, first=1\, depth=2\) at regcomp\.c&#8203;:12290
\#10 0x00005555556a5f5b in S\_reg \(pRExC\_state=0x7fffffffd690\, paren=0\,
flagp=0x7fffffffd3c8\, depth=1\) at regcomp\.c&#8203;:12011
\#11 0x000055555568a1b4 in Perl\_re\_op\_compile \(patternp=0x0\,
pat\_count=1\, expr=0x555555b4f508\, eng=0x555555b19d20
\<PL\_core\_reg\_engine>\, old\_re=0x0\,
&nbsp;    is\_bare\_re=0x0\, orig\_rx\_flags=0\, pm\_flags=0\) at regcomp\.c&#8203;:7665
\#12 0x00005555555a7080 in Perl\_pmruntime \(o=0x555555b4f548\,
expr=0x555555b4f508\, repl=0x555555b4f4c8\, flags=1\, floor=0\) at
op\.c&#8203;:7094
\#13 0x000055555565d51c in Perl\_yyparse \(gramtype=258\) at perly\.y&#8203;:1228
\#14 0x00005555555d92ea in S\_parse\_body \(env=0x0\, xsinit=0x55555558e1d8
\<xs\_init>\) at perl\.c&#8203;:2507
\#15 0x00005555555d75bc in perl\_parse \(my\_perl=0x555555b24260\,
xsinit=0x55555558e1d8 \<xs\_init>\, argc=3\, argv=0x7fffffffe1d8\, env=0x0\)
at perl\.c&#8203;:1798
\#16 0x000055555558e11b in main \(argc=3\, argv=0x7fffffffe1d8\,
env=0x7fffffffe1f8\) at perlmain\.c&#8203;:126

This is a regression in blead\, bisect points to

commit 73b95840bb1b55d761ec2dd075d2a8c37fa94bf4
Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
Date&#8203;:   Mon Aug 20 18&#8203;:31&#8203;:04 2018 \-0600

&nbsp;    Move \\p\{user\-defined\} to core from utf8\_heavy\.pl

&nbsp;    This large commit moves the handling of user\-defined properties to C
&nbsp;    code\.  This should speed it up\, but the main reason to do this is to
&nbsp;    stop using swashes in this case\, leaving only tr/// using them\.  Once
&nbsp;    that too is converted\, all swash handling can be ripped out of perl\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @khwilliamson

Fixed by
commit 62286d5869e7680741523d2a11be77cb79b83c99
 Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
 Date&#8203;:   Fri Mar 22 11&#8203;:32&#8203;:32 2019 \-0600
 
&nbsp;     PATCH&#8203;: \[perl \#133889\] Assertion failure
&nbsp;     
&nbsp;     I did not bisect this\, but this is a regression\.
&nbsp;     
&nbsp;     This code is using a user\-defined property that isn't defined\.  It
&nbsp;     should catch that and\, since this is within regex sets\,  quit\, but
&nbsp;     instead continues and ends up using an undefined value\.
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.30\.0\, this and 160 other issues have been
resolved\.

Perl 5\.30\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.30.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
