### ISSUE TITLE
panic: Unexpected op 45

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16873]
Migrated from [rt.perl.org#133899](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133899) (status was 'resolved')

Searchable as RT133899$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.8\-21\-gde59f38ed9 built with afl and run under
libdislocator\, I found the following program \(also attached to this
message\) to either panic\(\) or trigger ASAN diagnostics
heap\-use\-after\-free&#8203;:

00000000  73 04 7c 30 3f 68 5c 78  7b 33 30 30 7d 28 3f 7b  |s\.|0?h\\x\{300\}\(?\{|
00000010  7d 29 04 04 67 72 69                              |\}\)\.\.gri|

To trigger ASAN\, surround it with 'eval q\!\!'\. ASAN trace is following

==51489==ERROR&#8203;: AddressSanitizer&#8203;: heap\-use\-after\-free on address
0x604000009528 at pc 0x000000ca6f2d bp 0x7ffe1cccb540 sp
0x7ffe1cccb538
WRITE of size 8 at 0x604000009528 thread T0
&nbsp;    \#0 0xca6f2c in S\_cleanup\_regmatch\_info\_aux
/home/afl/afl\-asan/regexec\.c&#8203;:10074&#8203;:43
&nbsp;    \#1 0xb1c83a in Perl\_leave\_scope /home/afl/afl\-asan/scope\.c&#8203;:1269&#8203;:6
&nbsp;    \#2 0xb580ad in S\_pop\_eval\_context\_maybe\_croak
/home/afl/afl\-asan/pp\_ctl\.c&#8203;:1632&#8203;:5
&nbsp;    \#3 0xb576cd in Perl\_die\_unwind /home/afl/afl\-asan/pp\_ctl\.c&#8203;:1784&#8203;:13
&nbsp;    \#4 0x895c94 in Perl\_vcroak /home/afl/afl\-asan/util\.c&#8203;:1716&#8203;:5
&nbsp;    \#5 0x895c94 in Perl\_croak /home/afl/afl\-asan/util\.c&#8203;:1761
&nbsp;    \#6 0xcfaef4 in S\_setup\_EXACTISH\_ST\_c1\_c2
/home/afl/afl\-asan/regexec\.c&#8203;:4558&#8203;:25
&nbsp;    \#7 0xcbee68 in S\_regmatch /home/afl/afl\-asan/regexec\.c&#8203;:8363&#8203;:31
&nbsp;    \#8 0xca76bd in S\_regtry /home/afl/afl\-asan/regexec\.c&#8203;:3933&#8203;:14
&nbsp;    \#9 0xc6d2b3 in Perl\_regexec\_flags /home/afl/afl\-asan/regexec\.c&#8203;:3790&#8203;:7
&nbsp;    \#10 0x99500c in Perl\_pp\_subst /home/afl/afl\-asan/pp\_hot\.c&#8203;:4434&#8203;:11
&nbsp;    \#11 0x88f834 in Perl\_runops\_debug /home/afl/afl\-asan/dump\.c&#8203;:2537&#8203;:23
&nbsp;    \#12 0x5f1015 in S\_run\_body /home/afl/afl\-asan/perl\.c&#8203;:2692&#8203;:2
&nbsp;    \#13 0x5f1015 in perl\_run /home/afl/afl\-asan/perl\.c&#8203;:2615
&nbsp;    \#14 0x50b60a in main /home/afl/afl\-asan/perlmain\.c&#8203;:127&#8203;:9
&nbsp;    \#15 0x7f47a0a2709a in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2409a\)
&nbsp;    \#16 0x43bdc9 in \_start \(/home/afl/afl\-asan/perl\+0x43bdc9\)

0x604000009528 is located 24 bytes inside of 48\-byte region
\[0x604000009510\,0x604000009540\)
freed by thread T0 here&#8203;:
&nbsp;    \#0 0x4da200 in \_\_interceptor\_cfree\.localalias\.0
\(/home/afl/afl\-asan/perl\+0x4da200\)
&nbsp;    \#1 0x89696a in Perl\_safesysfree /home/afl/afl\-asan/util\.c&#8203;:385&#8203;:2
&nbsp;    \#2 0x8c4396 in S\_mg\_free\_struct /home/afl/afl\-asan/mg\.c&#8203;:567&#8203;:5
&nbsp;    \#3 0x8c4396 in Perl\_mg\_free /home/afl/afl\-asan/mg\.c&#8203;:588
&nbsp;    \#4 0xa1e210 in Perl\_sv\_clear /home/afl/afl\-asan/sv\.c&#8203;:6598&#8203;:3
&nbsp;    \#5 0xa269f7 in Perl\_sv\_free2 /home/afl/afl\-asan/sv\.c&#8203;:7092&#8203;:9
&nbsp;    \#6 0xb1ef16 in S\_SvREFCNT\_dec /home/afl/afl\-asan/\./inline\.h&#8203;:216&#8203;:6
&nbsp;    \#7 0xb1ef16 in Perl\_leave\_scope /home/afl/afl\-asan/scope\.c&#8203;:973
&nbsp;    \#8 0xb580ad in S\_pop\_eval\_context\_maybe\_croak
/home/afl/afl\-asan/pp\_ctl\.c&#8203;:1632&#8203;:5
&nbsp;    \#9 0xb576cd in Perl\_die\_unwind /home/afl/afl\-asan/pp\_ctl\.c&#8203;:1784&#8203;:13
&nbsp;    \#10 0x895c94 in Perl\_vcroak /home/afl/afl\-asan/util\.c&#8203;:1716&#8203;:5
&nbsp;    \#11 0x895c94 in Perl\_croak /home/afl/afl\-asan/util\.c&#8203;:1761
&nbsp;    \#12 0xcfaef4 in S\_setup\_EXACTISH\_ST\_c1\_c2
/home/afl/afl\-asan/regexec\.c&#8203;:4558&#8203;:25
&nbsp;    \#13 0xcbee68 in S\_regmatch /home/afl/afl\-asan/regexec\.c&#8203;:8363&#8203;:31
&nbsp;    \#14 0xca76bd in S\_regtry /home/afl/afl\-asan/regexec\.c&#8203;:3933&#8203;:14
&nbsp;    \#15 0xc6d2b3 in Perl\_regexec\_flags /home/afl/afl\-asan/regexec\.c&#8203;:3790&#8203;:7
&nbsp;    \#16 0x99500c in Perl\_pp\_subst /home/afl/afl\-asan/pp\_hot\.c&#8203;:4434&#8203;:11
&nbsp;    \#17 0x88f834 in Perl\_runops\_debug /home/afl/afl\-asan/dump\.c&#8203;:2537&#8203;:23
&nbsp;    \#18 0x5f1015 in S\_run\_body /home/afl/afl\-asan/perl\.c&#8203;:2692&#8203;:2
&nbsp;    \#19 0x5f1015 in perl\_run /home/afl/afl\-asan/perl\.c&#8203;:2615
&nbsp;    \#20 0x50b60a in main /home/afl/afl\-asan/perlmain\.c&#8203;:127&#8203;:9
&nbsp;    \#21 0x7f47a0a2709a in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2409a\)

previously allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4da570 in calloc \(/home/afl/afl\-asan/perl\+0x4da570\)
&nbsp;    \#1 0x896bbe in Perl\_safesyscalloc /home/afl/afl\-asan/util\.c&#8203;:439&#8203;:18
&nbsp;    \#2 0xa115a6 in Perl\_sv\_magicext /home/afl/afl\-asan/sv\.c&#8203;:5684&#8203;:5
&nbsp;    \#3 0xc65cc1 in S\_setup\_eval\_state /home/afl/afl\-asan/regexec\.c&#8203;:9993&#8203;:18
&nbsp;    \#4 0xc65cc1 in Perl\_regexec\_flags /home/afl/afl\-asan/regexec\.c&#8203;:3411
&nbsp;    \#5 0x992608 in Perl\_pp\_subst /home/afl/afl\-asan/pp\_hot\.c&#8203;:4231&#8203;:10
&nbsp;    \#6 0x88f834 in Perl\_runops\_debug /home/afl/afl\-asan/dump\.c&#8203;:2537&#8203;:23
&nbsp;    \#7 0x5f1015 in S\_run\_body /home/afl/afl\-asan/perl\.c&#8203;:2692&#8203;:2
&nbsp;    \#8 0x5f1015 in perl\_run /home/afl/afl\-asan/perl\.c&#8203;:2615
&nbsp;    \#9 0x50b60a in main /home/afl/afl\-asan/perlmain\.c&#8203;:127&#8203;:9
&nbsp;    \#10 0x7f47a0a2709a in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2409a\)

This is a regression in blead\, bisect points to

commit a9f8c7ac75c364c3e05305718f38c5f8ccd935d8
Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
Date&#8203;:   Tue Nov 27 09&#8203;:42&#8203;:45 2018 \-0700

&nbsp;    Add regnode EXACTFU\_ONLY8

&nbsp;    This is a regnode that otherwise would be an EXACTFU except that it
&nbsp;    contains a code point that requires UTF\-8 to match\, including all the
&nbsp;    possible folds involving it\.  Hence if the target string isn't UTF\-8\, we
&nbsp;    know it can't possibly match\, without needing to try\.

&nbsp;    For completeness\, there could also be an EXACTFAA\_ONLY8 and an
&nbsp;    EXACTFL\_ONLY8 created\, but I think these are unlikely to actually appear
&nbsp;    in the wild\, since using /aa is mainly about ASCII\, and /l mostly will
&nbsp;    involve characters that don't require UTF\-8\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @dur-randir

[0022_1](https://rt-archive.perl.org/perl5/Ticket/Attachment/1616768/833603/0022_1)

**Comment by p5pRT** [comment]
### From @khwilliamson

Fixed by 
commit 70ecb4be2ac4243cbdb6586f87a091a7f8055d91
 Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
 Date&#8203;:   Thu Mar 7 11&#8203;:37&#8203;:21 2019 \-0700
 
&nbsp;     PATCH&#8203;: \[perl \#133899\] panic in s///
&nbsp;     
&nbsp;     Thanks for finding this bug\, and the others you've been finding\.
&nbsp;     
&nbsp;     A new regnode was added\, but this function was not updated to account
&nbsp;     for that\.  I've now checked all the other new regnodes in 5\.29 and this
&nbsp;     was the only missing one\.

\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'resolved'
