### ISSUE TITLE
Assertion failure in Perl_av_push/S_handle_regex_sets

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16928]
Migrated from [rt.perl.org#133988](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133988) (status was 'resolved')

Searchable as RT133988$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.9\-63\-g2496d8f3f7 built with afl and run
under libdislocator\, I found the following

m\,\(?\[\\N\{U\+0\.0\}\,

to cause an assertion failure

perl&#8203;: av\.c&#8203;:611&#8203;: void Perl\_av\_push\(AV \*\, SV \*\)&#8203;: Assertion \`val' failed\.


GDB stack trace is following

\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:50
\#1  0x00007ffff7c25535 in \_\_GI\_abort \(\) at abort\.c&#8203;:79
\#2  0x00007ffff7c2540f in \_\_assert\_fail\_base \(fmt=0x7ffff7d87ee0
"%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\, assertion=0x555555aa7c1b
"val"\,
&nbsp;    file=0x555555aa79b6 "av\.c"\, line=611\, function=\<optimized out>\) at
assert\.c&#8203;:92
\#3  0x00007ffff7c330f2 in \_\_GI\_\_\_assert\_fail \(assertion=0x555555aa7c1b
"val"\, file=0x555555aa79b6 "av\.c"\, line=611\,
&nbsp;    function=0x555555aa7d38 \<\_\_PRETTY\_FUNCTION\_\_\.18093>
"Perl\_av\_push"\) at assert\.c&#8203;:101
\#4  0x0000555555756ca4 in Perl\_av\_push \(av=0x555555b72f00\, val=0x0\) at av\.c&#8203;:611
\#5  0x00005555556d4f84 in S\_handle\_regex\_sets
\(pRExC\_state=0x7fffffffd660\, return\_invlist=0x0\, flagp=0x7fffffffca98\,
depth=6\,
&nbsp;    oregcomp\_parse=0x555555b796b1 "?\[\\\\N\{U\+0\.0\}"\) at regcomp\.c&#8203;:16261
\#6  0x00005555556b84c8 in S\_reg \(pRExC\_state=0x7fffffffd660\, paren=91\,
flagp=0x7fffffffca98\, depth=5\) at regcomp\.c&#8203;:11975
\#7  0x00005555556c3431 in S\_regatom \(pRExC\_state=0x7fffffffd660\,
flagp=0x7fffffffcd24\, depth=4\) at regcomp\.c&#8203;:13354
\#8  0x00005555556bc7e4 in S\_regpiece \(pRExC\_state=0x7fffffffd660\,
flagp=0x7fffffffce40\, depth=3\) at regcomp\.c&#8203;:12457
\#9  0x00005555556bc0e4 in S\_regbranch \(pRExC\_state=0x7fffffffd660\,
flagp=0x7fffffffcee8\, first=1\, depth=2\) at regcomp\.c&#8203;:12377
\#10 0x00005555556b9906 in S\_reg \(pRExC\_state=0x7fffffffd660\, paren=0\,
flagp=0x7fffffffd398\, depth=1\) at regcomp\.c&#8203;:12088
\#11 0x000055555569d08c in Perl\_re\_op\_compile \(patternp=0x0\,
pat\_count=1\, expr=0x555555b795a8\, eng=0x555555b41d20
\<PL\_core\_reg\_engine>\, old\_re=0x0\,
&nbsp;    is\_bare\_re=0x0\, orig\_rx\_flags=0\, pm\_flags=0\) at regcomp\.c&#8203;:7705
\#12 0x00005555555ba159 in Perl\_pmruntime \(o=0x555555b795e8\,
expr=0x555555b795a8\, repl=0x0\, flags=1\, floor=0\) at op\.c&#8203;:7127
\#13 0x000055555566ffde in Perl\_yyparse \(gramtype=258\) at perly\.y&#8203;:1228
\#14 0x00005555555ec726 in S\_parse\_body \(env=0x0\, xsinit=0x5555555a11f8
\<xs\_init>\) at perl\.c&#8203;:2531
\#15 0x00005555555ea9f8 in perl\_parse \(my\_perl=0x555555b4c260\,
xsinit=0x5555555a11f8 \<xs\_init>\, argc=2\, argv=0x7fffffffe1c8\, env=0x0\)
at perl\.c&#8203;:1822
\#16 0x00005555555a113b in main \(argc=2\, argv=0x7fffffffe1c8\,
env=0x7fffffffe1e0\) at perlmain\.c&#8203;:126

This is a regression in blead\, and while being very similar to
https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133889 bisect points to a
different commit&#8203;:

commit 7c932d07cab18751bfc7515b4320436273a459e2
Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
Date&#8203;:   Fri Oct 19 09&#8203;:48&#8203;:34 2018 \-0600

&nbsp;    Remove sizing pass from regular expression compiler

&nbsp;    This commit removes the sizing pass for regular expression compilation\.
&nbsp;    It attempts to be the minimum required to do this\.  Future patches are
&nbsp;    in the works that improve it\,\, and there is certainly lots more that
&nbsp;    could be done\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @khwilliamson

Fixed by
commit bc035eed7aac5997a56d34b98261cc7a99da4787
 Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
 Date&#8203;:   Fri Apr 5 16&#8203;:34&#8203;:21 2019 \-0600
 
&nbsp;     PATCH&#8203;: \[perl \#133988\]\, Assertion failure
&nbsp;     
&nbsp;     This was due to not checking that a \\N\{\} expanded to a single code point
&nbsp;     in contexts where only that is legal\.  This never could have worked
&nbsp;     properly\, though the assertion failure is new\.
&nbsp;     
&nbsp;     The diagnostic needs to be reworded to accommodate this new case\, but
&nbsp;     its too late in the 5\.29 cycle to do that\, so I'm changing just the
&nbsp;     description\, and will reword in 5\.31\, \[perl \#133996\]

\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.30\.0\, this and 160 other issues have been
resolved\.

Perl 5\.30\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.30.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
