### ISSUE TITLE
Assertion failure in S_reg (regcomp.c:11970)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16926]
Migrated from [rt.perl.org#133986](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133986) (status was 'resolved')

Searchable as RT133986$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.9\-63\-g2496d8f3f7 built with afl and run
under libdislocator\, I found the following

m m\\x\{100\}\(?\(m

to cause an assertion failure

perl&#8203;: regcomp\.c&#8203;:11970&#8203;: regnode\_offset S\_reg\(RExC\_state\_t \*\, I32\, I32
\*\, U32\)&#8203;: Assertion \`\(\(pRExC\_state\->end\)\) > \(\(pRExC\_state\->parse\)\)'
failed\.

GDB stack trace is following

\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:50
\#1  0x00007ffff7c25535 in \_\_GI\_abort \(\) at abort\.c&#8203;:79
\#2  0x00007ffff7c2540f in \_\_assert\_fail\_base \(fmt=0x7ffff7d87ee0
"%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\,
&nbsp;    assertion=0xf0bac0 \<\.str\.603> "\(\(pRExC\_state\->end\)\) >
\(\(pRExC\_state\->parse\)\)"\, file=0xeb2ce0 \<\.str\.4> "regcomp\.c"\,
line=11970\, function=\<optimized out>\)
&nbsp;    at assert\.c&#8203;:92
\#3  0x00007ffff7c330f2 in \_\_GI\_\_\_assert\_fail \(assertion=0xf0bac0
\<\.str\.603> "\(\(pRExC\_state\->end\)\) > \(\(pRExC\_state\->parse\)\)"\,
&nbsp;    file=0xeb2ce0 \<\.str\.4> "regcomp\.c"\, line=11970\, function=0xf0ae40
\<\_\_PRETTY\_FUNCTION\_\_\.S\_reg> "regnode\_offset S\_reg\(RExC\_state\_t \*\, I32\,
I32 \*\, U32\)"\)
&nbsp;    at assert\.c&#8203;:101
\#4  0x000000000076fe39 in S\_reg \(pRExC\_state=\<optimized out>\, paren=2\,
flagp=\<optimized out>\, depth=5\) at regcomp\.c&#8203;:11970
\#5  0x000000000081d061 in S\_regatom \(pRExC\_state=\<optimized out>\,
flagp=\<optimized out>\, depth=4\) at regcomp\.c&#8203;:13354
\#6  0x00000000007ff8ae in S\_regpiece \(pRExC\_state=0x7fffffffcc30\,
depth=3\, flagp=\<optimized out>\) at regcomp\.c&#8203;:12457
\#7  S\_regbranch \(pRExC\_state=\<optimized out>\, flagp=0x7fffffffc800\,
first=4\, depth=4294965646\) at regcomp\.c&#8203;:12377
\#8  0x000000000075e110 in S\_reg \(pRExC\_state=\<optimized out>\,
paren=58\, flagp=\<optimized out>\, depth=1\) at regcomp\.c&#8203;:12088
\#9  0x0000000000739a1e in Perl\_re\_op\_compile \(patternp=\<optimized
out>\, pat\_count=\<optimized out>\, expr=0x7fffffffcac0\, eng=\<optimized
out>\, old\_re=0x0\,
&nbsp;    is\_bare\_re=\<optimized out>\, orig\_rx\_flags=\<optimized out>\,
pm\_flags=\<optimized out>\) at regcomp\.c&#8203;:7705
\#10 0x000000000053c08b in Perl\_pmruntime \(o=\<optimized out>\,
expr=\<optimized out>\, repl=0x0\, flags=\<optimized out>\, floor=0\) at
op\.c&#8203;:7127
\#11 0x000000000070a29d in Perl\_yyparse \(gramtype=\<optimized out>\) at
perly\.y&#8203;:1228
\#12 0x00000000005ec0ab in S\_parse\_body \(env=\<optimized out>\,
xsinit=\<optimized out>\) at perl\.c&#8203;:2531
\#13 0x00000000005e24b4 in perl\_parse \(my\_perl=\<optimized out>\,
xsinit=\<optimized out>\, argc=\<optimized out>\, argv=\<optimized out>\,
env=\<optimized out>\)
&nbsp;    at perl\.c&#8203;:1822
\#14 0x000000000050b5ff in main \(argc=0\, argv=0x7ffff7c3a8bb
\<\_\_GI\_raise\+267>\, env=0x7fffffffe1e0\) at perlmain\.c&#8203;:126

This is a regression in blead\, bisect points to&#8203;:

commit e33043825a7d2f1b577f3c8174bba4868d3a5ee3
Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
Date&#8203;:   Mon Mar 18 20&#8203;:16&#8203;:39 2019 \-0600

&nbsp;    regcomp\.c&#8203;: Use safe UTF8SKIP

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @khwilliamson

Fixed by
45671da298df5eb367286a19e0b03796307902c9
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'resolved'
