### ISSUE TITLE
Assertion failure in Perl_newSVOP (op.c:7346)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16938]
Migrated from [rt.perl.org#134001](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134001) (status was 'new')

Searchable as RT134001$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.9\-63\-g2496d8f3f7 built with afl and run
under libdislocator\, I found the following program

eval"$\{sub\{sub\{//\]\]\]"\}\}

to cause an assertion failure

perl&#8203;: op\.c&#8203;:7346&#8203;: Perl\_newSVOP&#8203;: Assertion \`sv' failed\.

GDB stack trace is following

\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:50
\#1  0x00007ffff7c25535 in \_\_GI\_abort \(\) at abort\.c&#8203;:79
\#2  0x00007ffff7c2540f in \_\_assert\_fail\_base \(fmt=0x7ffff7d87ee0
"%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\, assertion=0x555555927be6
"sv"\,
&nbsp;    file=0x5555559247ae "op\.c"\, line=7346\, function=\<optimized out>\)
at assert\.c&#8203;:92
\#3  0x00007ffff7c330f2 in \_\_GI\_\_\_assert\_fail \(assertion=0x555555927be6
"sv"\, file=0x5555559247ae "op\.c"\, line=7346\,
&nbsp;    function=0x55555592c380 \<\_\_PRETTY\_FUNCTION\_\_\.20224>
"Perl\_newSVOP"\) at assert\.c&#8203;:101
\#4  0x00005555555bab5e in Perl\_newSVOP \(type=17\, flags=0\, sv=0x0\) at op\.c&#8203;:7346
\#5  0x00005555555d10b5 in Perl\_newANONATTRSUB \(floor=141\, proto=0x0\,
attrs=0x0\, block=0x555555b7be50\) at op\.c&#8203;:10965
\#6  0x000055555566f3c9 in Perl\_yyparse \(gramtype=258\) at perly\.y&#8203;:1072
\#7  0x00005555555ec726 in S\_parse\_body \(env=0x0\, xsinit=0x5555555a11f8
\<xs\_init>\) at perl\.c&#8203;:2531
\#8  0x00005555555ea9f8 in perl\_parse \(my\_perl=0x555555b4c260\,
xsinit=0x5555555a11f8 \<xs\_init>\, argc=2\, argv=0x7fffffffe1c8\, env=0x0\)
at perl\.c&#8203;:1822
\#9  0x00005555555a113b in main \(argc=2\, argv=0x7fffffffe1c8\,
env=0x7fffffffe1e0\) at perlmain\.c&#8203;:126

This is a regression between 5\.16 and 5\.18\, bisect points to

commit 9ffcdca1f504cb09088413c074b35af4b7f247e3
Author&#8203;: Father Chrysostomos \<sprout@&#8203;cpan\.org>
Date&#8203;:   Mon Nov 12 23&#8203;:04&#8203;:16 2012 \-0800

&nbsp;    Don’t leak subs containing syntax errors

&nbsp;    I fixed this for BEGIN blocks earlier\, but missed the fact that
&nbsp;    all subs are affected\.

&nbsp;    When called without an o argument \(from newANONATTRSUB\)\, newATTRSUB
&nbsp;    is expected to return a CV with an unowned reference count of which
&nbsp;    the caller will take ownership\.  We cannot have newATTRSUB returning
&nbsp;    a freed CV\, so we have it return null instead\.  But that means
&nbsp;    ck\_anoncode and pm\_runtime have to account for that\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>

**Comment by richardleach** [comment]
This case was swept up by:
```
commit eb54d46f7264ff7af62c409d8a6ab984a5a34f57
Author: Yves Orton <demerphq@gmail.com>
Date:   Fri Aug 26 18:26:14 2022 +0200

    Stop parsing on first syntax error.
    
    We try to keep parsing after many types of errors, up to a (current)
    maximum of 10 errors. Continuing after a semantic error (like
    undeclared variables) can be helpful, for instance showing a set of
    common errors, but continuing after a syntax error isn't helpful
    most of the time as the internal state of the parser can get confused
    and is not reliably restored in between attempts. This can produce
    sometimes completely bizarre errors which just obscure the true error,
    and has resulted in security tickets being filed in the past.
    
    This patch makes the parser stop after the first syntax error, while
    preserving the current behavior for other errors. An error is considered
    a syntax error if the error message from our internals is the literal
    text "syntax error". This may not be a complete list of true syntax
    errors, we can iterate on that in the future.
    
    This fixes the segfaults reported in Issue #17397, and #16944 and
    likely fixes other "segfault due to compiler continuation after syntax
    error" bugs that we have on record, which has been a recurring issue
    over the years.
```
I'm not sure how far parsing gets, but `Perl_newANONATTRSUB` certainly isn't reached.

Will add a test.
