### ISSUE TITLE
Assertion failure in Perl_isSCRIPT_RUN (regexec.c:10475)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16935]
Migrated from [rt.perl.org#133997](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133997) (status was 'resolved')

Searchable as RT133997$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.9\-63\-g2496d8f3f7 built with afl and run
under libdislocator\, I found the following program

0=~'\(\(\(\*sr&#8203;:\(\)|\)0\)\(\*sr&#8203;:\)0|\)'

to cause an assertion failure

perl&#8203;: regexec\.c&#8203;:10475&#8203;: \_Bool Perl\_isSCRIPT\_RUN\(const U8 \*\, const U8 \*\,
const \_Bool\)&#8203;: Assertion \`send >= s' failed\.

GDB stack trace is following

\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:50
\#1  0x00007ffff7c25535 in \_\_GI\_abort \(\) at abort\.c&#8203;:79
\#2  0x00007ffff7c2540f in \_\_assert\_fail\_base \(fmt=0x7ffff7d87ee0
"%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\, assertion=0x555555ae0fe8
"send >= s"\,
&nbsp;    file=0x555555ae0348 "regexec\.c"\, line=10475\, function=\<optimized
out>\) at assert\.c&#8203;:92
\#3  0x00007ffff7c330f2 in \_\_GI\_\_\_assert\_fail \(assertion=0x555555ae0fe8
"send >= s"\, file=0x555555ae0348 "regexec\.c"\, line=10475\,
&nbsp;    function=0x555555af3270 \<\_\_PRETTY\_FUNCTION\_\_\.20773>
"Perl\_isSCRIPT\_RUN"\) at assert\.c&#8203;:101
\#4  0x00005555558ca5b9 in Perl\_isSCRIPT\_RUN \(s=0x555555b64481 ""\,
send=0x555555b64480 "0"\, utf8\_target=false\) at regexec\.c&#8203;:10475
\#5  0x00005555558bdf84 in S\_regmatch \(reginfo=0x7fffffffdce0\,
startpos=0x555555b64480 "0"\, prog=0x555555b793bc\) at regexec\.c&#8203;:7671
\#6  0x00005555558ae0bf in S\_regtry \(reginfo=0x7fffffffdce0\,
startposp=0x7fffffffdaa8\) at regexec\.c&#8203;:3956
\#7  0x00005555558ada3f in Perl\_regexec\_flags \(rx=0x555555b730c8\,
stringarg=0x555555b64480 "0"\, strend=0x555555b64481 ""\,
strbeg=0x555555b64480 "0"\,
&nbsp;    minend=0\, sv=0x555555b73080\, data=0x0\, flags=97\) at regexec\.c&#8203;:3819
\#8  0x0000555555769960 in Perl\_pp\_match \(\) at pp\_hot\.c&#8203;:3018
\#9  0x000055555570b640 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2537
\#10 0x00005555555ed560 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2716
\#11 0x00005555555ecade in perl\_run \(my\_perl=0x555555b4c260\) at perl\.c&#8203;:2639
\#12 0x00005555555a114e in main \(argc=2\, argv=0x7fffffffe1c8\,
env=0x7fffffffe1e0\) at perlmain\.c&#8203;:127

This appeared between 5\.26 and 5\.28\, bisect points to the following commit

commit d97906123bcd8c325c65db4f67e8c96e2cdafaec
Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
Date&#8203;:   Sun Feb 18 20&#8203;:28&#8203;:34 2018 \-0700

&nbsp;    Change syntax of script runs

&nbsp;    The new syntax is \(\*script\_run&#8203;:\.\.\.\)
&nbsp;    and a shortcut \(\*sr&#8203;:\.\.\.\)

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @khwilliamson

Fixed by
commit 8e9f3eef1e2836fe28e16465c5a7bb39af947d81
 Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
 Date&#8203;:   Sat Apr 13 19&#8203;:55&#8203;:56 2019 \-0600
 
&nbsp;     PATCH&#8203;: \[perl \#133997\] Assert fail with script runs
&nbsp;     
&nbsp;     The cause of this is the emulation of recursion in executing regex
&nbsp;     patterns and that the script run feature did not cooperate with it\.  The
&nbsp;     result is that the input pointers got pushed \(but not the script run\)
&nbsp;     and popped\, so that the script run was pointing to something that had
&nbsp;     been tried\, failed and otherwise popped\.
&nbsp;     
&nbsp;     The solution I've adopted is to always push the current script run start
&nbsp;     position whenever a push is done; and pop it whenever a pop is done\.
&nbsp;     
&nbsp;     If someone has suggestions about this code\, please step forward\.
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.30\.0\, this and 160 other issues have been
resolved\.

Perl 5\.30\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.30.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
