### ISSUE TITLE
Assertion failure in S_ReANY

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16939]
Migrated from [rt.perl.org#134003](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134003) (status was 'open')

Searchable as RT134003$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.9\-63\-g2496d8f3f7 built with afl and run
under libdislocator\, I found the following program

for\(0\.\.6\)\{0if split$p;\($$v0l0e\)&=\($f\,$v0l0e\)=0;\($e\)=0\}

to cause an assertion failure

perl&#8203;: \./inline\.h&#8203;:182&#8203;: struct regexp \*S\_ReANY\(const REGEXP \*const\)&#8203;:
Assertion \`isREGEXP\(re\)' failed\.

GDB stack trace is following

\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:50
\#1  0x00007ffff7c25535 in \_\_GI\_abort \(\) at abort\.c&#8203;:79
\#2  0x00007ffff7c2540f in \_\_assert\_fail\_base \(fmt=0x7ffff7d87ee0
"%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\, assertion=0x555555ac6c87
"isREGEXP\(re\)"\,
&nbsp;    file=0x555555ac6bd0 "inline\.h"\, line=182\, function=\<optimized
out>\) at assert\.c&#8203;:92
\#3  0x00007ffff7c330f2 in \_\_GI\_\_\_assert\_fail \(assertion=0x555555ac6c87
"isREGEXP\(re\)"\, file=0x555555ac6bd0 "inline\.h"\, line=182\,
&nbsp;    function=0x555555acda70 \<\_\_PRETTY\_FUNCTION\_\_\.17109> "S\_ReANY"\) at
assert\.c&#8203;:101
\#4  0x0000555555821313 in S\_ReANY \(re=0x555555b68e88\) at inline\.h&#8203;:182
\#5  0x0000555555822da6 in Perl\_pp\_regcomp \(\) at pp\_ctl\.c&#8203;:106
\#6  0x000055555570b89b in Perl\_runops\_debug \(\) at dump\.c&#8203;:2537
\#7  0x00005555555ed560 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2716
\#8  0x00005555555ecade in perl\_run \(my\_perl=0x555555b4c260\) at perl\.c&#8203;:2639
\#9  0x00005555555a114e in main \(argc=3\, argv=0x7fffffffe1c8\,
env=0x7fffffffe1e8\) at perlmain\.c&#8203;:127

While it looks like one from stack\-not\-refcounted pack\, I don't see
how altering $$v0l0e and $f could affect $p\. Bisected commit also
seems innocent \(this is a blead\-only failure\)

commit 6ef7fe531911e0b41ffcc04c1d6b6ec25a8b1bc9
Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
Date&#8203;:   Sun Mar 17 22&#8203;:11&#8203;:04 2019 \-0600

&nbsp;    PATCH&#8203;: \[perl \#131551\] Too deep regex compilation recursion

&nbsp;    This patch\, started by Yves Orton\, and refined in consultation with Tony
&nbsp;    Cook\, imposes a maximum depth of unclosed left parentheses\, at which
&nbsp;    point it croaks\.  This is to prevent the segfault in the ticket\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @khwilliamson

On Sun\, 07 Apr 2019 09&#8203;:51&#8203;:11 \-0700\, randir wrote&#8203;:
> This is a bug report for perl from sergey\.aleynikov@&#8203;gmail\.com\,
> generated with the help of perlbug 1\.41 running under perl 5\.29\.9\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
> 
> While fuzzing perl v5\.29\.9\-63\-g2496d8f3f7 built with afl and run
> under libdislocator\, I found the following program
> 
> for\(0\.\.6\)\{0if split$p;\($$v0l0e\)&=\($f\,$v0l0e\)=0;\($e\)=0\}
> 
> to cause an assertion failure
> 
> perl&#8203;: \./inline\.h&#8203;:182&#8203;: struct regexp \*S\_ReANY\(const REGEXP \*const\)&#8203;:
> Assertion \`isREGEXP\(re\)' failed\.
> 
> GDB stack trace is following
> 
> \#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at
> \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:50
> \#1  0x00007ffff7c25535 in \_\_GI\_abort \(\) at abort\.c&#8203;:79
> \#2  0x00007ffff7c2540f in \_\_assert\_fail\_base \(fmt=0x7ffff7d87ee0
> "%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\, assertion=0x555555ac6c87
> "isREGEXP\(re\)"\,
>     file=0x555555ac6bd0 "inline\.h"\, line=182\, function=\<optimized
> out> \) at assert\.c&#8203;:92
> \#3  0x00007ffff7c330f2 in \_\_GI\_\_\_assert\_fail \(assertion=0x555555ac6c87
> "isREGEXP\(re\)"\, file=0x555555ac6bd0 "inline\.h"\, line=182\,
>     function=0x555555acda70 \<\_\_PRETTY\_FUNCTION\_\_\.17109> "S\_ReANY"\) at
> assert\.c&#8203;:101
> \#4  0x0000555555821313 in S\_ReANY \(re=0x555555b68e88\) at inline\.h&#8203;:182
> \#5  0x0000555555822da6 in Perl\_pp\_regcomp \(\) at pp\_ctl\.c&#8203;:106
> \#6  0x000055555570b89b in Perl\_runops\_debug \(\) at dump\.c&#8203;:2537
> \#7  0x00005555555ed560 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2716
> \#8  0x00005555555ecade in perl\_run \(my\_perl=0x555555b4c260\) at
> perl\.c&#8203;:2639
> \#9  0x00005555555a114e in main \(argc=3\, argv=0x7fffffffe1c8\,
> env=0x7fffffffe1e8\) at perlmain\.c&#8203;:127
> 
> While it looks like one from stack\-not\-refcounted pack\, I don't see
> how altering $$v0l0e and $f could affect $p\. Bisected commit also
> seems innocent \(this is a blead\-only failure\)
> 
> commit 6ef7fe531911e0b41ffcc04c1d6b6ec25a8b1bc9
> Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
> Date&#8203;:   Sun Mar 17 22&#8203;:11&#8203;:04 2019 \-0600
> 
> PATCH&#8203;: \[perl \#131551\] Too deep regex compilation recursion
> 
> This patch\, started by Yves Orton\, and refined in consultation with
> Tony
> Cook\, imposes a maximum depth of unclosed left parentheses\, at which
> point it croaks\.  This is to prevent the segfault in the ticket\.
> 
> \[Please do not change anything below this line\]
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \-\-\-
> Flags&#8203;:
>     category=core
>     severity=medium
> \-\-\-
> Site configuration information for perl 5\.29\.9&#8203;:
> 
> Configured by dur\-randir at Wed Feb 27 14&#8203;:51&#8203;:01 MSK 2019\.
> 
> Summary of my perl5 \(revision 5 version 29 subversion 9\)
> configuration&#8203;:
>   Commit id&#8203;: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
>   Platform&#8203;:
>     osname=darwin
>     osvers=13\.4\.0
>     archname=darwin\-thread\-multi\-2level
>     uname='darwin isengard\.local 13\.4\.0 darwin kernel version 13\.4\.0&#8203;:
> mon jan 11 18&#8203;:17&#8203;:34 pst 2016; root&#8203;:xnu\-2422\.115\.15~1release\_x86\_64
> x86\_64 '
>     config\_args='\-de \-Dusedevel \-DDEBUGGING \-Dusethreads'
>     hint=recommended
>     useposix=true
>     d\_sigaction=define
>     useithreads=define
>     usemultiplicity=define
>     use64bitint=define
>     use64bitall=define
>     uselongdouble=undef
>     usemymalloc=n
>     default\_inc\_excludes\_dot=define
>     bincompat5005=undef
>   Compiler&#8203;:
>     cc='cc'
>     ccflags ='\-fno\-common \-DPERL\_DARWIN \-mmacosx\-version\-min=10\.9
> \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector
> \-I/usr/local/include \-DPERL\_USE\_SAFE\_PUTENV'
>     optimize='\-O3 \-g'
>     cppflags='\-fno\-common \-DPERL\_DARWIN \-mmacosx\-version\-min=10\.9
> \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector
> \-I/usr/local/include'
>     ccversion=''
>     gccversion='4\.2\.1 Compatible Apple LLVM 6\.0 \(clang\-600\.0\.56\)'
>     gccosandvers=''
>     intsize=4
>     longsize=8
>     ptrsize=8
>     doublesize=8
>     byteorder=12345678
>     doublekind=3
>     d\_longlong=define
>     longlongsize=8
>     d\_longdbl=define
>     longdblsize=16
>     longdblkind=3
>     ivtype='long'
>     ivsize=8
>     nvtype='double'
>     nvsize=8
>     Off\_t='off\_t'
>     lseeksize=8
>     alignbytes=8
>     prototype=define
>   Linker and Libraries&#8203;:
>     ld='cc'
>     ldflags =' \-mmacosx\-version\-min=10\.9 \-fstack\-protector
> \-L/usr/local/lib'
>     libpth=/usr/local/lib
> /Applications/Xcode\.app/Contents/Developer/Toolchains/XcodeDefault\.xctoolchain/usr/bin/\.\./lib/clang/6\.0/lib
> /Applications/Xcode\.app/Contents/Developer/Toolchains/XcodeDefault\.xctoolchain/usr/lib
> /usr/lib
>     libs=\-lpthread \-lgdbm \-ldbm \-ldl \-lm \-lutil \-lc
>     perllibs=\-lpthread \-ldl \-lm \-lutil \-lc
>     libc=
>     so=dylib
>     useshrplib=false
>     libperl=libperl\.a
>     gnulibc\_version=''
>   Dynamic Linking&#8203;:
>     dlsrc=dl\_dlopen\.xs
>     dlext=bundle
>     d\_dlsymun=undef
>     ccdlflags=' '
>     cccdlflags=' '
>     lddlflags=' \-mmacosx\-version\-min=10\.9 \-bundle \-undefined
> dynamic\_lookup \-L/usr/local/lib \-fstack\-protector'
> 
> 
> \-\-\-
> @&#8203;INC for perl 5\.29\.9&#8203;:
>     lib
>     /usr/local/lib/perl5/site\_perl/5\.29\.9/darwin\-thread\-multi\-2level
>     /usr/local/lib/perl5/site\_perl/5\.29\.9
>     /usr/local/lib/perl5/5\.29\.9/darwin\-thread\-multi\-2level
>     /usr/local/lib/perl5/5\.29\.9
> 
> \-\-\-
> Environment for perl 5\.29\.9&#8203;:
>     DYLD\_LIBRARY\_PATH \(unset\)
>     HOME=/Users/dur\-randir
>     LANG=en\_US\.UTF\-8
>     LANGUAGE \(unset\)
>     LD\_LIBRARY\_PATH \(unset\)
>     LOGDIR \(unset\)
>     PATH=/Users/dur\-randir/perlbrew/bin&#8203;:/Users/dur\-
> randir/perlbrew/perls/perl\-
> 5\.22\.1/bin&#8203;:/usr/local/bin&#8203;:/usr/local/sbin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/sbin&#8203;:/sbin&#8203;:/usr/texbin
>     PERLBREW\_HOME=/Users/dur\-randir/\.perlbrew
>     PERLBREW\_MANPATH=/Users/dur\-randir/perlbrew/perls/perl\-5\.22\.1/man
>     PERLBREW\_PATH=/Users/dur\-randir/perlbrew/bin&#8203;:/Users/dur\-
> randir/perlbrew/perls/perl\-5\.22\.1/bin
>     PERLBREW\_PERL=perl\-5\.22\.1
>     PERLBREW\_ROOT=/Users/dur\-randir/perlbrew
>     PERLBREW\_SHELLRC\_VERSION=0\.84
>     PERLBREW\_VERSION=0\.84
>     PERL\_BADLANG \(unset\)
>     SHELL=/usr/local/bin/zsh

I am unable to reproduce this on Linux\, \-O0\, g\+\+ 7\.3
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @dur-randir

On Wed\, 10 Apr 2019 15&#8203;:54&#8203;:24 \-0700\, khw wrote&#8203;:
> I am unable to reproduce this on Linux\, \-O0\, g\+\+ 7\.3

Here's a full \-V from a \-O0 perl that triggers this for me\, built with gcc 8\.3\.0&#8203;:

Summary of my perl5 \(revision 5 version 29 subversion 10\) configuration&#8203;:
&nbsp;  Derived from&#8203;: d304e731249cc1d281e8d3d6677cf23596f190b3
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux
&nbsp;    osvers=4\.19\.0\-2\-amd64
&nbsp;    archname=x86\_64\-linux
&nbsp;    uname='linux dorothy 4\.19\.0\-2\-amd64 \#1 smp debian 4\.19\.16\-1 \(2019\-01\-17\) x86\_64 gnulinux '
&nbsp;    config\_args='\-des \-Dusedevel \-Dcc=gcc \-DDEBUGGING \-Doptimize=\-O0 \-g \-ggdb3'
&nbsp;    hint=previous
&nbsp;    useposix=true
&nbsp;    d\_sigaction=define
&nbsp;    useithreads=undef
&nbsp;    usemultiplicity=undef
&nbsp;    use64bitint=define
&nbsp;    use64bitall=define
&nbsp;    uselongdouble=undef
&nbsp;    usemymalloc=n
&nbsp;    default\_inc\_excludes\_dot=define
&nbsp;    bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'
&nbsp;    ccflags ='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-D\_FORTIFY\_SOURCE=2'
&nbsp;    optimize='\-O0 \-g \-ggdb3'
&nbsp;    cppflags='\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''
&nbsp;    gccversion='8\.3\.0'
&nbsp;    gccosandvers=''
&nbsp;    intsize=4
&nbsp;    longsize=8
&nbsp;    ptrsize=8
&nbsp;    doublesize=8
&nbsp;    byteorder=12345678
&nbsp;    doublekind=3
&nbsp;    d\_longlong=define
&nbsp;    longlongsize=8
&nbsp;    d\_longdbl=define
&nbsp;    longdblsize=16
&nbsp;    longdblkind=3
&nbsp;    ivtype='long'
&nbsp;    ivsize=8
&nbsp;    nvtype='double'
&nbsp;    nvsize=8
&nbsp;    Off\_t='off\_t'
&nbsp;    lseeksize=8
&nbsp;    alignbytes=8
&nbsp;    prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='gcc'
&nbsp;    ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/8/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib /usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/8/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/8/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.28\.so
&nbsp;    so=so
&nbsp;    useshrplib=false
&nbsp;    libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.28'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs
&nbsp;    dlext=so
&nbsp;    d\_dlsymun=undef
&nbsp;    ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'
&nbsp;    lddlflags='\-shared \-O0 \-g \-ggdb3 \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;:
&nbsp;    DEBUGGING
&nbsp;    HAS\_TIMES
&nbsp;    PERLIO\_LAYERS
&nbsp;    PERL\_COPY\_ON\_WRITE
&nbsp;    PERL\_DONT\_CREATE\_GVSV
&nbsp;    PERL\_MALLOC\_WRAP
&nbsp;    PERL\_OP\_PARENT
&nbsp;    PERL\_PRESERVE\_IVUV
&nbsp;    PERL\_USE\_DEVEL
&nbsp;    USE\_64\_BIT\_ALL
&nbsp;    USE\_64\_BIT\_INT
&nbsp;    USE\_LARGE\_FILES
&nbsp;    USE\_LOCALE
&nbsp;    USE\_LOCALE\_COLLATE
&nbsp;    USE\_LOCALE\_CTYPE
&nbsp;    USE\_LOCALE\_NUMERIC
&nbsp;    USE\_LOCALE\_TIME
&nbsp;    USE\_PERLIO
&nbsp;    USE\_PERL\_ATOF
&nbsp;  Locally applied patches&#8203;:
&nbsp;    uncommitted\-changes
&nbsp;  Built under linux
&nbsp;  Compiled at Apr  8 2019 14&#8203;:39&#8203;:05
&nbsp;  %ENV&#8203;:
&nbsp;    PERLBREW\_BASHRC\_VERSION="0\.78"
&nbsp;    PERLBREW\_HOME="/home/afl/\.perlbrew"
&nbsp;    PERLBREW\_MANPATH="/home/afl/perlbrew/perls/perl\-5\.26\.0\-dbg/man"
&nbsp;    PERLBREW\_PATH="/home/afl/perlbrew/bin&#8203;:/home/afl/perlbrew/perls/perl\-5\.26\.0\-dbg/bin"
&nbsp;    PERLBREW\_PERL="perl\-5\.26\.0\-dbg"
&nbsp;    PERLBREW\_ROOT="/home/afl/perlbrew"
&nbsp;    PERLBREW\_VERSION="0\.78"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib/
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.29\.10/x86\_64\-linux
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.29\.10
&nbsp;    /usr/local/lib/perl5/5\.29\.10/x86\_64\-linux
&nbsp;    /usr/local/lib/perl5/5\.29\.10

**Comment by p5pRT** [comment]
### From @dur-randir

It also crashes for me with gcc 7\.4\.0

**Comment by p5pRT** [comment]
### From @hvds

On Wed\, 10 Apr 2019 15&#8203;:54&#8203;:24 \-0700\, khw wrote&#8203;:
> I am unable to reproduce this on Linux\, \-O0\, g\+\+ 7\.3

I can reproduce it here with gcc 4\.8\.4\, both at the specified commit and current blead \(a719c52\)\.

I can simplify it a bit to&#8203;:
&nbsp;  \./miniperl \-e 'for \(0\.\.5\) \{ split undef; $$x &= \($y\, $x\) = 0 \}'
\.\. but the loop count seems quite sensitive\.

For this variant\, looping \(0\.\.2\) instead gives just a bad free&#8203;:
% \./miniperl \-e 'for \(0\.\.2\) \{ split undef; $$x &= \($y\, $x\) = 0 \}'
Attempt to free unreferenced scalar&#8203;: SV 0x20c9c10\.
% 

I suspect these are all symptoms of corruption via stack refcounting on $x\.

Interestingly\, building with clang and address\-sanitizer I get a completely different result&#8203;:
% \./miniperl \-e 'for\(0\.\.6\)\{0if split$p;\($$v0l0e\)&=\($f\,$v0l0e\)=0;\($e\)=0\}'
ASAN&#8203;:SIGSEGV
=================================================================
==21782==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000000 \(pc 0x0000012ba34a sp 0x7ffe8601b400 bp 0x7ffe8601b910 T0\)
&nbsp;    \#0 0x12ba349 in Perl\_sv\_setiv sv\.c&#8203;:1658
&nbsp;    \#1 0x12bc8a1 in Perl\_sv\_setuv sv\.c&#8203;:1705
&nbsp;    \#2 0x12bd050 in Perl\_sv\_setuv\_mg sv\.c&#8203;:1726
&nbsp;    \#3 0x15f7677 in Perl\_pp\_bit\_and pp\.c&#8203;:2323
&nbsp;    \#4 0xefc9fc in Perl\_runops\_debug dump\.c&#8203;:2537
&nbsp;    \#5 0x6f7ca0 in S\_run\_body perl\.c&#8203;:2716
&nbsp;    \#6 0x6f364a in perl\_run perl\.c&#8203;:2639
&nbsp;    \#7 0x1f134f8 in main miniperlmain\.c&#8203;:133
&nbsp;    \#8 0x7fecc34b9f44 \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x21f44\)
&nbsp;    \#9 0x499cec in \_start \(miniperl\+0x499cec\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /src/package/lang/perl/gitperl/sv\.c&#8203;:1658 Perl\_sv\_setiv
==21782==ABORTING
% 

Hugo

**Comment by p5pRT** [comment]
### From @dur-randir

On Thu\, 11 Apr 2019 05&#8203;:34&#8203;:20 \-0700\, hv wrote&#8203;:
> I suspect these are all symptoms of corruption via stack refcounting
> on $x\.

Good\, so it can be shoved under some table\)

**Comment by p5pRT** [comment]
### From @hvds

On Thu\, 11 Apr 2019 06&#8203;:24&#8203;:51 \-0700\, randir wrote&#8203;:
> On Thu\, 11 Apr 2019 05&#8203;:34&#8203;:20 \-0700\, hv wrote&#8203;:
> > I suspect these are all symptoms of corruption via stack refcounting
> > on $x\.
> 
> Good\, so it can be shoved under some table\)

Bad\, because attempting to diagnose it properly would eat up time and give little back\. I don't know for sure that's the issue\, but suspecting it is already makes me reluctant to spend more time on it\.

Hugo

**Comment by richardleach** [comment]
The varying test cases above still fail (assert or segfault) on a standard build of blead, but **not** on a build with `Accflags='-DPERL_RC_STACK -DDEBUG_LEAKING_SCALARS'`. So it is indeed a stack refcounting issue.
