### ISSUE TITLE
Assertion failure in Perl_sv_vcatpvfn_flags (sv.c:12497)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16945]
Migrated from [rt.perl.org#134013](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134013) (status was 'new')

Searchable as RT134013$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.9\-63\-g2496d8f3f7 built with afl and run
under libdislocator\, I found the following program

eval q\!format=
@&#8203;
for\(0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
\!

to cause an assertion failure

perl&#8203;: sv\.c&#8203;:12497&#8203;: void Perl\_sv\_vcatpvfn\_flags\(SV \*const\, const char
\*const\, const STRLEN\, va\_list \*const\, SV \*\*const\, const size\_t\, \_Bool
\*const\, const U32\)&#8203;: Assertion \`0' failed\.

GDB stack trace is following

\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:50
\#1  0x00007ffff7c25535 in \_\_GI\_abort \(\) at abort\.c&#8203;:79
\#2  0x00007ffff7c2540f in \_\_assert\_fail\_base \(fmt=0x7ffff7d87ee0
"%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\, assertion=0x555555abc233
"0"\,
&nbsp;    file=0x555555aab720 "sv\.c"\, line=12497\, function=\<optimized out>\)
at assert\.c&#8203;:92
\#3  0x00007ffff7c330f2 in \_\_GI\_\_\_assert\_fail \(assertion=0x555555abc233
"0"\, file=0x555555aab720 "sv\.c"\, line=12497\,
&nbsp;    function=0x555555abe790 \<\_\_PRETTY\_FUNCTION\_\_\.23329>
"Perl\_sv\_vcatpvfn\_flags"\) at assert\.c&#8203;:101
\#4  0x00005555557d4738 in Perl\_sv\_vcatpvfn\_flags \(sv=0x555555b730c8\,
pat=0x555555959ea9 "near \\"%d%lu%4p\\"\\n"\, patlen=16\,
args=0x7fffffffd7d0\, svargs=0x0\,
&nbsp;    sv\_count=0\, maybe\_tainted=0x0\, flags=130\) at sv\.c&#8203;:12497
\#5  0x00005555557cfb68 in Perl\_sv\_catpvf \(sv=0x555555b730c8\,
pat=0x555555959ea9 "near \\"%d%lu%4p\\"\\n"\) at sv\.c&#8203;:10895
\#6  0x00005555556670a3 in Perl\_yyerror\_pvn \(s=0x555555960adf "syntax
error"\, len=12\, flags=0\) at toke\.c&#8203;:11832
\#7  0x000055555566684e in Perl\_yyerror \(s=0x555555960adf "syntax
error"\) at toke\.c&#8203;:11737
\#8  0x00005555556705df in Perl\_yyparse \(gramtype=258\) at perly\.c&#8203;:474
\#9  0x00005555558390a9 in S\_doeval\_compile \(gimme=1 '\\001'\,
outside=0x555555b4e8f0\, seq=4294967246\, hh=0x0\) at pp\_ctl\.c&#8203;:3502
\#10 0x0000555555840e44 in Perl\_pp\_entereval \(\) at pp\_ctl\.c&#8203;:4478
\#11 0x000055555570b895 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2537
\#12 0x00005555555ed560 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2716
\#13 0x00005555555ecade in perl\_run \(my\_perl=0x555555b4c260\) at perl\.c&#8203;:2639
\#14 0x00005555555a114e in main \(argc=2\, argv=0x7fffffffe1c8\,
env=0x7fffffffe1e0\) at perlmain\.c&#8203;:127

This assertion was added by the following commit\, but the current code
works around this situation on non\-debugging builds

commit 79980e0040a23a26a8a511476ebbe0069a750f00
Author&#8203;: Jarkko Hietaniemi \<jhi@&#8203;iki\.fi>
Date&#8203;:   Wed Sep 10 19&#8203;:42&#8203;:38 2014 \-0400

&nbsp;    Also protect against elen \< 0\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>
