### ISSUE TITLE
Assertion failure in Perl_pad_add_anon (pad.c:849)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16943]
Migrated from [rt.perl.org#134009](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134009) (status was 'new')

Searchable as RT134009$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.9\-63\-g2496d8f3f7 built with afl and run
under libdislocator\, I found the following program

eval q\!s\,\,$0\[sub\{m\[\]\]\]\,;s\,\,$0\[sub\{m\[\]\]\]\,\}\}\!

to cause an assertion failure

perl&#8203;: pad\.c&#8203;:614&#8203;: Perl\_pad\_add\_anon&#8203;: Assertion \`\!CvWEAKOUTSIDE\(\(const
CV \*\)sv\)' failed\.

GDB stack trace is following

\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:50
\#1  0x00007ffff7a22535 in \_\_GI\_abort \(\) at abort\.c&#8203;:79
\#2  0x00007ffff7a2240f in \_\_assert\_fail\_base \(fmt=0x7ffff7b84ee0
"%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\,
&nbsp;    assertion=0x55555596175e "\!CvWEAKOUTSIDE\(func\)"\,
file=0x5555559610e8 "pad\.c"\, line=810\, function=\<optimized out>\) at
assert\.c&#8203;:92
\#3  0x00007ffff7a300f2 in \_\_GI\_\_\_assert\_fail \(assertion=0x55555596175e
"\!CvWEAKOUTSIDE\(func\)"\, file=0x5555559610e8 "pad\.c"\, line=810\,
&nbsp;    function=0x555555962480 \<\_\_PRETTY\_FUNCTION\_\_\.18152>
"Perl\_pad\_add\_anon"\) at assert\.c&#8203;:101
\#4  0x0000555555674ac4 in Perl\_pad\_add\_anon \(func=0x7ffff748b988\,
optype=17\) at pad\.c&#8203;:810
\#5  0x00005555555d165f in Perl\_ck\_anoncode \(o=0x7ffff324dfd0\) at op\.c&#8203;:11104
\#6  0x00005555555bad4b in Perl\_newSVOP \(type=17\, flags=0\,
sv=0x7ffff748b988\) at op\.c&#8203;:7363
\#7  0x00005555555d10b5 in Perl\_newANONATTRSUB \(floor=177\, proto=0x0\,
attrs=0x0\, block=0x7ffff4519dc8\) at op\.c&#8203;:10965
\#8  0x000055555566f3c9 in Perl\_yyparse \(gramtype=258\) at perly\.y&#8203;:1072
\#9  0x00005555558390a9 in S\_doeval\_compile \(gimme=1 '\\001'\,
outside=0x7ffff79fb9a0\, seq=4294967265\, hh=0x0\) at pp\_ctl\.c&#8203;:3502
\#10 0x0000555555840e44 in Perl\_pp\_entereval \(\) at pp\_ctl\.c&#8203;:4478
\#11 0x000055555570b895 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2537
\#12 0x00005555555ed560 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2716
\#13 0x00005555555ecade in perl\_run \(my\_perl=0x7ffff7dc9fff\) at perl\.c&#8203;:2639
\#14 0x00005555555a114e in main \(argc=4\, argv=0x7fffffffe0b8\,
env=0x7fffffffe0e0\) at perlmain\.c&#8203;:127

This is present from at least 5\.8\.8\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>

**Comment by richardleach** [comment]
Seems fixed in blead? (I've not bisected.)

**Comment by jkeenan** [comment]
> Seems fixed in blead? (I've not bisected.)

This was originally reported as appearing in a perl *"built with afl and run
under libdislocator"*.  Would we have to do that in order to assess whether it had been fixed or not?  Or would it be sufficient to merely run it with a perl built `-DDEBUGGING -Duseithreads`?

**Comment by richardleach** [comment]
I thought just DDEBUGGING would suffice, but could easily be wrong.
