### ISSUE TITLE
Assertion failure in S_make_trie (regcomp.c:2799)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16955]
Migrated from [rt.perl.org#134029](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134029) (status was 'resolved')

Searchable as RT134029$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.9\-63\-g2496d8f3f7 built with afl and run
under libdislocator\, I found the following program

/\\p\{upper&#8203;:\]\}|\\337\(?|ss\)|\)\(?0/

to cause an assertion failure on debugging builds and emit 'Infinite
recursion in regex' on release builds

perl&#8203;: regcomp\.c&#8203;:2799&#8203;: I32 S\_make\_trie\(RExC\_state\_t \*\, regnode \*\,
regnode \*\, regnode \*\, regnode \*\, U32\, U32\, U32\)&#8203;: Assertion \`\*uc \!=
LATIN\_SMALL\_LETTER\_SHARP\_S' failed\.

GDB stack trace is following

\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:50
\#1  0x00007ffff7c25535 in \_\_GI\_abort \(\) at abort\.c&#8203;:79
\#2  0x00007ffff7c2540f in \_\_assert\_fail\_base \(fmt=0x7ffff7d87ee0
"%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\,
&nbsp;    assertion=0x555555a804c0 "\*uc \!= LATIN\_SMALL\_LETTER\_SHARP\_S"\,
file=0x555555a7fcd0 "regcomp\.c"\, line=2799\, function=\<optimized out>\)
at assert\.c&#8203;:92
\#3  0x00007ffff7c330f2 in \_\_GI\_\_\_assert\_fail \(assertion=0x555555a804c0
"\*uc \!= LATIN\_SMALL\_LETTER\_SHARP\_S"\, file=0x555555a7fcd0 "regcomp\.c"\,
line=2799\,
&nbsp;    function=0x555555a9eb20 \<\_\_PRETTY\_FUNCTION\_\_\.21394> "S\_make\_trie"\)
at assert\.c&#8203;:101
\#4  0x000055555568289b in S\_make\_trie \(pRExC\_state=0x7fffffffbbd0\,
startbranch=0x555555b8023c\, first=0x555555b80248\, last=0x555555b80264\,
&nbsp;    tail=0x555555b80268\, word\_count=2\, flags=39\, depth=2\) at regcomp\.c&#8203;:2799
\#5  0x000055555569046c in S\_study\_chunk \(pRExC\_state=0x7fffffffbbd0\,
scanp=0x7fffffffb988\, minlenp=0x7fffffffb960\, deltap=0x7fffffffb978\,
&nbsp;    last=0x555555b80274\, data=0x7fffffffbf40\, stopparen=0\,
recursed\_depth=1\, and\_withp=0x555555b80430\, flags=13312\, depth=1\) at
regcomp\.c&#8203;:5002
\#6  0x000055555569e930 in Perl\_re\_op\_compile \(patternp=0x7fffffffc050\,
pat\_count=1\, expr=0x0\, eng=0x555555b43d20 \<PL\_core\_reg\_engine>\,
old\_re=0x0\,
&nbsp;    is\_bare\_re=0x0\, orig\_rx\_flags=0\, pm\_flags=0\) at regcomp\.c&#8203;:8047
\#7  0x0000555555696564 in Perl\_re\_compile \(pattern=0x555555b75150\,
rx\_flags=0\) at regcomp\.c&#8203;:6547
\#8  0x00005555556f2a75 in Perl\_parse\_uniprop\_string
\(name=0x555555b69783 "upper&#8203;:\]\}|\\\\337\(?|ss\)|\)\(?0"\, name\_len=7\,
is\_utf8=false\, to\_fold=false\,
&nbsp;    runtime=false\, deferrable=true\, user\_defined\_ptr=0x7fffffffc568\,
msg=0x555555b75120\, level=0\) at regcomp\.c&#8203;:22717
\#9  0x00005555556db1c7 in S\_regclass \(pRExC\_state=0x7fffffffd650\,
flagp=0x7fffffffcd14\, depth=5\, stop\_at\_1=true\,
allow\_mutiple\_chars=false\,
&nbsp;    silence\_non\_portable=false\, strict=false\, optimizable=true\,
ret\_invlist=0x0\) at regcomp\.c&#8203;:17104
\#10 0x00005555556c5e1d in S\_regatom \(pRExC\_state=0x7fffffffd650\,
flagp=0x7fffffffcd14\, depth=4\) at regcomp\.c&#8203;:13647
\#11 0x00005555556bca5d in S\_regpiece \(pRExC\_state=0x7fffffffd650\,
flagp=0x7fffffffce30\, depth=3\) at regcomp\.c&#8203;:12457
\#12 0x00005555556bc35d in S\_regbranch \(pRExC\_state=0x7fffffffd650\,
flagp=0x7fffffffced8\, first=1\, depth=2\) at regcomp\.c&#8203;:12377
\#13 0x00005555556b9b7f in S\_reg \(pRExC\_state=0x7fffffffd650\, paren=0\,
flagp=0x7fffffffd388\, depth=1\) at regcomp\.c&#8203;:12088
\#14 0x000055555569d215 in Perl\_re\_op\_compile \(patternp=0x0\,
pat\_count=1\, expr=0x555555b7b5e8\, eng=0x555555b43d20
\<PL\_core\_reg\_engine>\, old\_re=0x0\,
&nbsp;    is\_bare\_re=0x0\, orig\_rx\_flags=0\, pm\_flags=0\) at regcomp\.c&#8203;:7705
\#15 0x00005555555ba159 in Perl\_pmruntime \(o=0x555555b7b628\,
expr=0x555555b7b5e8\, repl=0x0\, flags=1\, floor=0\) at op\.c&#8203;:7127
\#16 0x0000555555670167 in Perl\_yyparse \(gramtype=258\) at perly\.y&#8203;:1234
\#17 0x00005555555ec726 in S\_parse\_body \(env=0x0\, xsinit=0x5555555a11f8
\<xs\_init>\) at perl\.c&#8203;:2531
\#18 0x00005555555ea9f8 in perl\_parse \(my\_perl=0x555555b4e260\,
xsinit=0x5555555a11f8 \<xs\_init>\, argc=2\, argv=0x7fffffffe1c8\, env=0x0\)
at perl\.c&#8203;:1822
\#19 0x00005555555a113b in main \(argc=2\, argv=0x7fffffffe1c8\,
env=0x7fffffffe1e0\) at perlmain\.c&#8203;:126

This is a regression in blead\, bisect points to

commit 1532347b696561120241d1e6221c028acedff019
Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
Date&#8203;:   Mon Mar 11 17&#8203;:16&#8203;:34 2019 \-0600

&nbsp;    Add Unicode property wildcards

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @khwilliamson

Thanks\, fixed by
commit 11b48e7688e81ca14328a2d959770629efa83cde
 Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
 Date&#8203;:   Mon Apr 15 12&#8203;:05&#8203;:07 2019 \-0600
 
&nbsp;     PATCH&#8203;: \[perl \#134029\] Fail assert in pattern wildcard
&nbsp;     
&nbsp;     The failing pattern has a single character subpattern\, which should be
&nbsp;     caught and compilation aborted\, and this commit now does so\.
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'resolved'
