### ISSUE TITLE
undefining top-of-page format causes NULL pointer dereference

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16965]
Migrated from [rt.perl.org#134041](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134041) (status was 'open')

Searchable as RT134041$

**Comment by p5pRT** [comment]
### From @nwc10

#### Created by @nwc10

```
struct xpvio has this:

char * xio_top_name; /* $^ */
GV * xio_top_gv; /* $^ */
char * xio_fmt_name; /* $~ */
GV * xio_fmt_gv; /* $~ */
char * xio_bottom_name;/* $^B */
GV * xio_bottom_gv; /* $^B */
```

Going for a dig in sv.c and pp_ctl.c I realised that they aren't actually
reference counted references to the relevant GVs. Hence the pointers don't
get properly reset if the GV is eliminated:

```perl
#!/usr/bin/perl -w
use strict;

my $foo = "bar\n" x 4;

format STDOUT_TOP =
.

format STDOUT =
@<<
$foo
.

# Setting output lines to 3 forces the "top" format to be called again soon
$= = 3;

write STDOUT for 0..2;

delete $::{STDOUT_TOP};

write STDOUT for 0..2

__END__
```

gives this:

```
$ ./perl -Ilib IoTOP_GV.pl
bar
bar
bar
ASAN:DEADLYSIGNAL
=================================================================
==15129==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000030 (pc 0x55943ce5812c bp 0x62100000ad48 sp 0x7ffdcc8b6910 T0)
==15129==The signal is caused by a READ memory access.
==15129==Hint: address points to the zero page.
#0 0x55943ce5812b in Perl_pp_leavewrite /home/nick/Perl/perl/pp_sys.c:1532
#1 0x55943cd7e4d9 in Perl_runops_standard /home/nick/Perl/perl/run.c:41
#2 0x55943cc05121 in S_run_body /home/nick/Perl/perl/perl.c:2716
#3 0x55943cc05497 in perl_run /home/nick/Perl/perl/perl.c:2639
#4 0x55943cba2f7f in main /home/nick/Perl/perl/perlmain.c:127
#5 0x7fc34fbf7b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
#6 0x55943cba2d29 in _start (/home/nick/Perl/perl/perl+0xf7d29)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/nick/Perl/perl/pp_sys.c:1532 in Perl_pp_leavewrite
==15129==ABORTING
```

It's an assertion failure with a debugging build:

```
$ ~/Sandpit/snap-v5.29.9-132-g188c2c2fd5/bin/perl5.2
9.10 ../IoTOP_GV.pl
bar
bar
bar
perl5.29.10: pp_sys.c:1532: Perl_pp_leavewrite: Assertion `((svtype)((_gvgp)->sv_flags & 0xff)) == SVt_PVGV || ((svtype)((_gvgp)->sv_flags & 0xff)) == SVt_PVLV' failed.
Aborted
```

I couldn't spot an open bug about this in the security queue, hence this
report. I assume that the other two in the structure are equally fun.
I'm a bit surprised that none of the fuzzers have found this yet.

Bug probably dates back to 5.000, but I don't have a copy handy to check
that. Not sure what the fix should be - I sort of fear that we end up
needing the three to be (formal) weak references from the GV, so that the
GV knows how to reset any/all IOs that point to it like this when it is freed.

I haven't fully figured out the security implications of this - I thought
I'd get a read from uninitialised memory, not a NULL pointer dereference
(or captured by an assertion) - maybe it's not worthy of the security queue.

Nicholas Clark

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl 5.29.10:

Configured by nick at Tue Apr 16 10:17:55 CEST 2019.

Summary of my perl5 (revision 5 version 29 subversion 10) configuration:
  Commit id: 11b48e7688e81ca14328a2d959770629efa83cde
  Platform:
    osname=linux
    osvers=4.15.0-46-generic
    archname=x86_64-linux
    uname='linux ninne 4.15.0-46-generic #49-ubuntu smp wed feb 6 09:33:07 utc 2019 x86_64 x86_64 x86_64 gnulinux '
    config_args='-Dusedevel -Dcc=ccache gcc -Dld=gcc -Accflags=-ggdb -fsanitize=address -Aldflags=-fsanitize=address -UDEBUGGING -Doptimize=-Og -Dprefix=~/Sandpit/snap-v5.29.9-134-g11b48e7688-ASAN -de'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags ='-ggdb -fsanitize=address -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-Og'
    cppflags='-ggdb -fsanitize=address -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='7.3.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='gcc'
    ldflags =' -fsanitize=address -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed /usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.27.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.27'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -Og -L/usr/local/lib -fstack-protector-strong'



@INC for perl 5.29.10:
    /home/nick/Sandpit/snap-v5.29.9-134-g11b48e7688-ASAN/lib/perl5/site_perl/5.29.10/x86_64-linux
    /home/nick/Sandpit/snap-v5.29.9-134-g11b48e7688-ASAN/lib/perl5/site_perl/5.29.10
    /home/nick/Sandpit/snap-v5.29.9-134-g11b48e7688-ASAN/lib/perl5/5.29.10/x86_64-linux
    /home/nick/Sandpit/snap-v5.29.9-134-g11b48e7688-ASAN/lib/perl5/5.29.10


Environment for perl 5.29.10:
    HOME=/home/nick
    LANG=en_GB.UTF-8
    LANGUAGE=en_GB:en
    LC_ADDRESS=en_DK.UTF-8
    LC_IDENTIFICATION=en_DK.UTF-8
    LC_MEASUREMENT=en_DK.UTF-8
    LC_MONETARY=en_DK.UTF-8
    LC_NAME=en_DK.UTF-8
    LC_NUMERIC=en_DK.UTF-8
    LC_PAPER=en_DK.UTF-8
    LC_TELEPHONE=en_DK.UTF-8
    LC_TIME=en_DK.UTF-8
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @tonycoz

I don't think it's a security issue.

Those formats can only be removed under control of the perl code.

It is still a bug\.

\(xio\_bottom\_\* have existed since 5\.000 and are unused\, despite the reference to $^B\.\)

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Apr 21\, 2019 at 06&#8203;:16&#8203;:52PM \-0700\, Tony Cook via RT wrote&#8203;:
> I don't think it's a security issue\.
> 
> Those formats can only be removed under control of the perl code\.
> 
> It is still a bug\.
> 
> \(xio\_bottom\_\* have existed since 5\.000 and are unused\, despite the reference to $^B\.\)

I've now moved this ticket to the public queue

\-\- 
Overhead\, without any fuss\, the stars were going out\.
&nbsp;    \-\- Arthur C Clarke

**Comment by toddr** [comment]
@tonycoz I'm not able to reproduce this. Do I need a debugging perl to make it break?

**Comment by xenu** [comment]
It segfaults for me on all perl versions.

Note that this ticket's formatting is slightly broken due to migration, it cut the code block in half. You need both halves to make it crash.

**Comment by toddr** [comment]
fixed. thanks! 

```
$>perl5.30.0 foo
bar
bar
bar
zsh: segmentation fault  perl5.30.0 foo
```
