### ISSUE TITLE
Assertion failure in S_scan_const (toke.c:4063)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16981]
Migrated from [rt.perl.org#134064](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134064) (status was 'resolved')

Searchable as RT134064$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.10\-23\-g7c0d7520a3 built with afl and run
under libdislocator\, I found the following program

use utf8;
$foo="m'\\300'";eval$foo

To cause an assertion failure

perl&#8203;: toke\.c&#8203;:4063&#8203;: char \*S\_scan\_const\(char \*\)&#8203;: Assertion
\`isUTF8\_CHAR\(\(U8 \*\) s\, \(U8 \*\) send\)' failed\.

GDB stack trace is following

\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:50
\#1  0x00007ffff7c25535 in \_\_GI\_abort \(\) at abort\.c&#8203;:79
\#2  0x00007ffff7c2540f in \_\_assert\_fail\_base \(fmt=0x7ffff7d87ee0
"%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\,
&nbsp;    assertion=0x55555593ee78 "isUTF8\_CHAR\(\(U8 \*\) s\, \(U8 \*\) send\)"\,
file=0x5555559383e5 "toke\.c"\, line=4063\, function=\<optimized out>\) at
assert\.c&#8203;:92
\#3  0x00007ffff7c330f2 in \_\_GI\_\_\_assert\_fail \(assertion=0x55555593ee78
"isUTF8\_CHAR\(\(U8 \*\) s\, \(U8 \*\) send\)"\, file=0x5555559383e5 "toke\.c"\,
line=4063\,
&nbsp;    function=0x55555595da28 \<\_\_PRETTY\_FUNCTION\_\_\.18843>
"S\_scan\_const"\) at assert\.c&#8203;:101
\#4  0x00005555556308aa in S\_scan\_const \(start=0x555555b6a170 "\\300"\)
at toke\.c&#8203;:4063
\#5  0x0000555555638f3b in Perl\_yylex \(\) at toke\.c&#8203;:5096
\#6  0x000055555566bde0 in Perl\_yyparse \(gramtype=258\) at perly\.c&#8203;:340
\#7  0x0000555555839ec6 in S\_doeval\_compile \(gimme=1 '\\001'\,
outside=0x555555b53908\, seq=4294967256\, hh=0x0\) at pp\_ctl\.c&#8203;:3502
\#8  0x0000555555841c61 in Perl\_pp\_entereval \(\) at pp\_ctl\.c&#8203;:4478
\#9  0x000055555570c635 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2537
\#10 0x00005555555ed63d in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2716
\#11 0x00005555555ecbbb in perl\_run \(my\_perl=0x555555b51260\) at perl\.c&#8203;:2639
\#12 0x00005555555a1181 in main \(argc=3\, argv=0x7fffffffe1c8\,
env=0x7fffffffe1e8\) at perlmain\.c&#8203;:134

This is a regression in blead\, bisect points to

commit 7d6e74d636b95acb75fa67ff364e97ab1c8ef795
Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
Date&#8203;:   Sat Apr 6 14&#8203;:05&#8203;:29 2019 \-0600

&nbsp;    toke\.c&#8203;: Streamline a case

&nbsp;    When we are parsing a constant\, and the source and destination differ in
&nbsp;    UTF\-8ness\, I realized\, in single stepping through the code\, that it's
&nbsp;    simpler and more efficient to split these into two cases\, rather than
&nbsp;    try to do one case with some conditionals in the middle\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @khwilliamson

On 4/26/19 9&#8203;:05 AM\, Sergey Aleynikov \(via RT\) wrote&#8203;:
> \# New Ticket Created by  Sergey Aleynikov
> \# Please include the string&#8203;:  \[perl \#134064\]
> \# in the subject line of all future correspondence about this issue\.
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134064 >
> 
> 
> This is a bug report for perl from sergey\.aleynikov@&#8203;gmail\.com\,
> generated with the help of perlbug 1\.41 running under perl 5\.29\.9\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
> 
> While fuzzing perl v5\.29\.10\-23\-g7c0d7520a3 built with afl and run
> under libdislocator\, I found the following program
> 
> use utf8;
> $foo="m'\\300'";eval$foo
> 
> To cause an assertion failure
> 
> perl&#8203;: toke\.c&#8203;:4063&#8203;: char \*S\_scan\_const\(char \*\)&#8203;: Assertion
> \`isUTF8\_CHAR\(\(U8 \*\) s\, \(U8 \*\) send\)' failed\.
> 
> GDB stack trace is following
> 
> \#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:50
> \#1  0x00007ffff7c25535 in \_\_GI\_abort \(\) at abort\.c&#8203;:79
> \#2  0x00007ffff7c2540f in \_\_assert\_fail\_base \(fmt=0x7ffff7d87ee0
> "%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\,
>      assertion=0x55555593ee78 "isUTF8\_CHAR\(\(U8 \*\) s\, \(U8 \*\) send\)"\,
> file=0x5555559383e5 "toke\.c"\, line=4063\, function=\<optimized out>\) at
> assert\.c&#8203;:92
> \#3  0x00007ffff7c330f2 in \_\_GI\_\_\_assert\_fail \(assertion=0x55555593ee78
> "isUTF8\_CHAR\(\(U8 \*\) s\, \(U8 \*\) send\)"\, file=0x5555559383e5 "toke\.c"\,
> line=4063\,
>      function=0x55555595da28 \<\_\_PRETTY\_FUNCTION\_\_\.18843>
> "S\_scan\_const"\) at assert\.c&#8203;:101
> \#4  0x00005555556308aa in S\_scan\_const \(start=0x555555b6a170 "\\300"\)
> at toke\.c&#8203;:4063
> \#5  0x0000555555638f3b in Perl\_yylex \(\) at toke\.c&#8203;:5096
> \#6  0x000055555566bde0 in Perl\_yyparse \(gramtype=258\) at perly\.c&#8203;:340
> \#7  0x0000555555839ec6 in S\_doeval\_compile \(gimme=1 '\\001'\,
> outside=0x555555b53908\, seq=4294967256\, hh=0x0\) at pp\_ctl\.c&#8203;:3502
> \#8  0x0000555555841c61 in Perl\_pp\_entereval \(\) at pp\_ctl\.c&#8203;:4478
> \#9  0x000055555570c635 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2537
> \#10 0x00005555555ed63d in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2716
> \#11 0x00005555555ecbbb in perl\_run \(my\_perl=0x555555b51260\) at perl\.c&#8203;:2639
> \#12 0x00005555555a1181 in main \(argc=3\, argv=0x7fffffffe1c8\,
> env=0x7fffffffe1e8\) at perlmain\.c&#8203;:134
> 
> This is a regression in blead\, bisect points to
> 
> commit 7d6e74d636b95acb75fa67ff364e97ab1c8ef795
> Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
> Date&#8203;:   Sat Apr 6 14&#8203;:05&#8203;:29 2019 \-0600
> 
>      toke\.c&#8203;: Streamline a case
> 
>      When we are parsing a constant\, and the source and destination differ in
>      UTF\-8ness\, I realized\, in single stepping through the code\, that it's
>      simpler and more efficient to split these into two cases\, rather than
>      try to do one case with some conditionals in the middle\.
> 

The attached one word patch fixes this\.  This bug report illustrates my 
point in a recent post about these fuzzer failures from Sergey being 
something that should concern us\.  The actual problem is that string 
eval is not being checked for UTF\-8 well\-formedness when 'use utf8' is 
in effect\.

**Comment by p5pRT** [comment]
### From @khwilliamson

<details><summary>0002-PATCH-perl-134064-Assertion-failure-in-toke.c.patch</summary>

```diff
From 2b5333535c13124a8033f5027cab5cb1bd366c85 Mon Sep 17 00:00:00 2001
From: Karl Williamson <khw@cpan.org>
Date: Fri, 26 Apr 2019 14:42:37 -0600
Subject: [PATCH 2/5] PATCH: [perl #134064] Assertion failure in toke.c

The blamed commit simplified some code based on the assumption that
UTF-8 well-formedness had already been verified.  It had an assertion to
verify this.  The test case shows that there is a path, through 'eval',
that bypasses this usual checking.

The checking was based on the assumption that the program started not in
UTF-8, and something like a 'use utf8' would be needed to get it there,
at which point a flag would be set to the effect that well-formedness
should be checked.  But it turns out that a string eval (perhaps other
things) gets parsed separately and so the flag wasn't set, so no
well-formedness checking was being done.

The solution is a one word change, to initialize the flag to TRUE "'yes,
check" instead of FALSE "no, don't check" in the initialization routine
run at the beginning of lexing a code unit.  This catches eval and
presumably anything else that was being bypassed.

The checking is only actually done if the code being lexed is known to
be in UTF-8.  This will continue to get turned on by the ways it
currently gets turned on, such as 'use utf8'.
---
 t/lib/warnings/toke | 16 ++++++++++++++++
 toke.c              |  2 +-
 2 files changed, 17 insertions(+), 1 deletion(-)

diff --git a/t/lib/warnings/toke b/t/lib/warnings/toke
index faaf5bc6b8..83641e5106 100644
--- a/t/lib/warnings/toke
+++ b/t/lib/warnings/toke
@@ -1675,3 +1675,19 @@ Execution of - aborted due to compilation errors.
 use utf8;
 qw∘foo ∞ ♥ bar∘
 EXPECT
+########
+# NAME  [perl #134064]
+BEGIN {
+    if (ord('A') == 193) {
+        print "SKIPPED\n# test is ASCII-specific, but could be extended to EBCDIC";
+        exit 0;
+    }
+}
+use utf8;
+$foo="m'\302'";
+eval $foo ;
+print "The eval did not crash the program\n"
+EXPECT
+OPTION regex
+Malformed UTF-8 character: .*non-continuation.*
+The eval did not crash the program
diff --git a/toke.c b/toke.c
index 2f9c1d5228..5dca9de4b2 100644
--- a/toke.c
+++ b/toke.c
@@ -729,7 +729,7 @@ Perl_lex_start(pTHX_ SV *line, PerlIO *rsfp, U32 flags)
     parser->lex_state = LEX_NORMAL;
     parser->expect = XSTATE;
     parser->rsfp = rsfp;
-    parser->recheck_utf8_validity = FALSE;
+    parser->recheck_utf8_validity = TRUE;
     parser->rsfp_filters =
       !(flags & LEX_START_SAME_FILTER) || !oparser
         ? NULL
-- 
2.17.1


```
</details>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @dur-randir

I suggest this to be added to the 5\.30 blockers list\, as it's a heap\-buffer\-overrun on non\-debugging builds\.

**Comment by p5pRT** [comment]
### From @xsawyerx

\+1


On 5/2/19 1&#8203;:00 PM\, Sergey Aleynikov via RT wrote&#8203;:
> I suggest this to be added to the 5\.30 blockers list\, as it's a heap\-buffer\-overrun on non\-debugging builds\.
>
> \-\-\-
> via perlbug&#8203;:  queue&#8203;: perl5 status&#8203;: open
> https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134064

**Comment by p5pRT** [comment]
### From @jkeenan

On Thu\, 02 May 2019 10&#8203;:00&#8203;:24 GMT\, randir wrote&#8203;:
> I suggest this to be added to the 5\.30 blockers list\, as it's a heap\-
> buffer\-overrun on non\-debugging builds\.

Was this problem introduced during the 5\.29 development cycle?

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @jkeenan

On Thu\, 02 May 2019 12&#8203;:21&#8203;:39 GMT\, jkeenan wrote&#8203;:
> On Thu\, 02 May 2019 10&#8203;:00&#8203;:24 GMT\, randir wrote&#8203;:
> > I suggest this to be added to the 5\.30 blockers list\, as it's a heap\-
> > buffer\-overrun on non\-debugging builds\.
> 
> Was this problem introduced during the 5\.29 development cycle?

Yes\, I see now that it was\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @khwilliamson

Fixed by

commit b7b52646bdd14487f27b3cbf58bf526fbaee140f
 Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
 Date&#8203;:   Fri Apr 26 14&#8203;:42&#8203;:37 2019 \-0600
 
&nbsp;     PATCH&#8203;: \[perl \#134064\] Assertion failure in toke\.c
&nbsp;     
&nbsp;     The blamed commit simplified some code based on the assumption that
&nbsp;     UTF\-8 well\-formedness had already been verified\.  It had an assertion to
&nbsp;     verify this\.  The test case shows that there is a path\, through 'eval'\,
&nbsp;     that bypasses this usual checking\.
&nbsp;     
&nbsp;     The checking was based on the assumption that the program started not in
&nbsp;     UTF\-8\, and something like a 'use utf8' would be needed to get it there\,
&nbsp;     at which point a flag would be set to the effect that well\-formedness
&nbsp;     should be checked\.  But it turns out that a string eval \(perhaps other
&nbsp;     things\) gets parsed separately and so the flag wasn't set\, so no
&nbsp;     well\-formedness checking was being done\.
&nbsp;     
&nbsp;     The solution is a one word change\, to initialize the flag to TRUE "'yes\,
&nbsp;     check" instead of FALSE "no\, don't check" in the initialization routine
&nbsp;     run at the beginning of lexing a code unit\.  This catches eval and
&nbsp;     presumably anything else that was being bypassed\.
&nbsp;     
&nbsp;     The checking is only actually done if the code being lexed is known to
&nbsp;     be in UTF\-8\.  This will continue to get turned on by the ways it
&nbsp;     currently gets turned on\, such as 'use utf8'\.
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'pending release'

**Comment by p5pRT** [comment]
### From @khwilliamson

Thank you for filing this report\.  You have helped make Perl better\.

With the release today of Perl 5\.30\.0\, this and 160 other issues have been
resolved\.

Perl 5\.30\.0 may be downloaded via&#8203;:
https://metacpan.org/release/XSAWYERX/perl-5.30.0

If you find that the problem persists\, feel free to reopen this ticket\.

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'pending release' to 'resolved'
