### ISSUE TITLE
Assertion failure in Perl_pp_leave (pp_ctl.c:2121)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16982]
Migrated from [rt.perl.org#134065](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134065) (status was 'new')

Searchable as RT134065$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.10\-23\-g7c0d7520a3 built with afl and run
under libdislocator\, I found the following program

x\{\}u\{0^\\sort\{0\}0=>\(O\.\.0\);\{\}\}

To cause an assertion failure

perl&#8203;: pp\_ctl\.c&#8203;:2121&#8203;: OP \*Perl\_pp\_leave\(void\)&#8203;: Assertion \`CxTYPE\(cx\) ==
CXt\_BLOCK' failed\.

GDB stack trace is following

\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:50
\#1  0x00007ffff7c25535 in \_\_GI\_abort \(\) at abort\.c&#8203;:79
\#2  0x00007ffff7c2540f in \_\_assert\_fail\_base \(fmt=0x7ffff7d87ee0
"%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\,
&nbsp;    assertion=0x555555acd916 "CxTYPE\(cx\) == CXt\_BLOCK"\,
file=0x555555acc455 "pp\_ctl\.c"\, line=2121\, function=\<optimized out>\)
at assert\.c&#8203;:92
\#3  0x00007ffff7c330f2 in \_\_GI\_\_\_assert\_fail \(assertion=0x555555acd916
"CxTYPE\(cx\) == CXt\_BLOCK"\, file=0x555555acc455 "pp\_ctl\.c"\, line=2121\,
&nbsp;    function=0x555555ad3220 \<\_\_PRETTY\_FUNCTION\_\_\.18989>
"Perl\_pp\_leave"\) at assert\.c&#8203;:101
\#4  0x0000555555832e58 in Perl\_pp\_leave \(\) at pp\_ctl\.c&#8203;:2121
\#5  0x000055555570c635 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2537
\#6  0x000055555591f4f9 in S\_sortcv \(a=0x555555b77e80\,
b=0x555555b53740\) at pp\_sort\.c&#8203;:1132
\#7  0x000055555591b559 in dynprep \(list1=0x555555b55db0\,
list2=0x7fffffffd540\, nmemb=2\, cmp=0x55555591f136 \<S\_sortcv>\) at
pp\_sort\.c&#8203;:197
\#8  0x000055555591b9fc in Perl\_sortsv\_flags \(base=0x555555b55db0\,
nmemb=2\, cmp=0x55555591f136 \<S\_sortcv>\, flags=0\) at pp\_sort\.c&#8203;:388
\#9  0x000055555591e7c8 in Perl\_pp\_sort \(\) at pp\_sort\.c&#8203;:1014
\#10 0x000055555570c635 in Perl\_runops\_debug \(\) at dump\.c&#8203;:2537
\#11 0x00005555555ed63d in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2716
\#12 0x00005555555ecbbb in perl\_run \(my\_perl=0x555555b51260\) at perl\.c&#8203;:2639
\#13 0x00005555555a1181 in main \(argc=2\, argv=0x7fffffffe1d8\,
env=0x7fffffffe1f0\) at perlmain\.c&#8203;:134

This is a regression between 5\.24 and 5\.26\, bisect points to

commit b3698342565fb462291fba4b432cfcd05b6eb4e1
Author&#8203;: Zefram \<zefram@&#8203;fysh\.org>
Date&#8203;:   Fri Jan 27 03&#8203;:55&#8203;:46 2017 \+0000

&nbsp;    fix range op under aborted constant folding

&nbsp;    When constant\-folding a range/flipflop construct\, the op\_next threading
&nbsp;    of peephole optimisation caused multiple ops in the construct to have
&nbsp;    a null op\_next\, because the final \(and top\-level\) op in the construct
&nbsp;    is a null op\.  This meant that simple restoration of the top\-level
&nbsp;    op's op\_next after execution wouldn't get it back into a fit state
&nbsp;    to be composed with other ops\.  In the event that the range construct
&nbsp;    couldn't be constant\-folded this made it compile to a broken optree\.
&nbsp;    If it couldn't be constant\-folded but could actually be executed\, for
&nbsp;    example because it generated a warning\, this meant the brokenness would
&nbsp;    be encountered at runtime\.  Execution would stop after the range op\,
&nbsp;    because of the null op\_next\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>

**Comment by tonycoz** [comment]
(I originally had my notes for #16865 here, which has a similar cause)

This also re-enters sort leading to the context stack getting out of sync
