### ISSUE TITLE
panic: paren_elems_to_push

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16984]
Migrated from [rt.perl.org#134068](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134068) (status was 'new')

Searchable as RT134068$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.10\-23\-g7c0d7520a3 built with afl and run
under libdislocator\, I found the following program

q\!000000\!=~/\(\(0\(\*ACCEPT\)\)\{6\}\(\(0\)\)?0\)?\(?0\)/

to emit 'panic&#8203;: paren\_elems\_to\_push\, \-3 \< 0\, maxopenparen&#8203;: 0
parenfloor&#8203;: 1 REGCP\_PAREN\_ELEMS&#8203;: 3' diagnostics\. This has never
behaved well\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @dur-randir

GDB stacktrace is following

\#0  Perl\_vcroak \(pat=0x555555830b38 "panic&#8203;: paren\_elems\_to\_push\, %i \< 0\, maxopenparen&#8203;: %i parenfloor&#8203;: %i REGCP\_PAREN\_ELEMS&#8203;: %u"\,
&nbsp;    args=args@&#8203;entry=0x7fffffffda70\) at util\.c&#8203;:1709
\#1  0x0000555555629609 in Perl\_croak \(
&nbsp;    pat=pat@&#8203;entry=0x555555830b38 "panic&#8203;: paren\_elems\_to\_push\, %i \< 0\, maxopenparen&#8203;: %i parenfloor&#8203;: %i REGCP\_PAREN\_ELEMS&#8203;: %u"\) at util\.c&#8203;:1756
\#2  0x00005555556a7f6a in S\_regcppush \(rex=rex@&#8203;entry=0x5555558b3170\, parenfloor=\<optimized out>\, maxopenparen=\<optimized out>\) at regexec\.c&#8203;:226
\#3  0x00005555556b54ed in S\_regmatch \(prog=\<optimized out>\, startpos=\<optimized out>\, reginfo=\<optimized out>\) at regexec\.c&#8203;:8041
\#4  S\_regtry \(reginfo=\<optimized out>\, startposp=\<optimized out>\) at regexec\.c&#8203;:3974
\#5  0x00005555556bfcba in Perl\_regexec\_flags \(rx=\<optimized out>\, stringarg=0x5555558b1bb0 "000000"\, strend=0x5555558b1bb6 ""\,
&nbsp;    strbeg=0x5555558b1bb0 "000000"\, minend=\<optimized out>\, sv=0x5555558aed20\, data=0x0\, flags=97\) at regexec\.c&#8203;:3837
\#6  0x000055555564a33d in Perl\_pp\_match \(\) at inline\.h&#8203;:183
\#7  0x00005555556448f3 in Perl\_runops\_standard \(\) at run\.c&#8203;:42
\#8  0x00005555555c53f4 in S\_run\_body \(oldscope=\<optimized out>\) at perl\.c&#8203;:2716
\#9  perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2639
\#10 0x000055555559f292 in main \(argc=\<optimized out>\, argv=\<optimized out>\, env=\<optimized out>\) at perlmain\.c&#8203;:127
