### ISSUE TITLE
Assertion failure in S_regmatch (regexec.c: 6493)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16990]
Migrated from [rt.perl.org#134083](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134083) (status was 'new')

Searchable as RT134083$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



While fuzzing perl v5\.29\.10\-23\-g7c0d7520a3 built with afl and run
under libdislocator\, I found the following program

use utf8;
eval"\\320\\200 f'\\r\\r0'=~'\\\\R??\\r0'"

to cause an assertion failure

perl&#8203;: regexec\.c&#8203;:6493&#8203;: S\_regmatch&#8203;: Assertion \`n == REG\_INFTY ||
locinput == li' failed\.

GDB stack trace is following

\#0  \_\_GI\_raise \(sig=sig@&#8203;entry=6\) at \.\./sysdeps/unix/sysv/linux/raise\.c&#8203;:50
\#1  0x00007ffff7c48535 in \_\_GI\_abort \(\) at abort\.c&#8203;:79
\#2  0x00007ffff7c4840f in \_\_assert\_fail\_base \(fmt=0x7ffff7daaee0
"%s%s%s&#8203;:%u&#8203;: %s%sAssertion \`%s' failed\.\\n%n"\,
&nbsp;    assertion=0x555555796fc0 "n == REG\_INFTY || locinput == li"\,
file=0x555555795f88 "regexec\.c"\, line=6493\, function=\<optimized out>\)
at assert\.c&#8203;:92
\#3  0x00007ffff7c560f2 in \_\_GI\_\_\_assert\_fail
\(assertion=assertion@&#8203;entry=0x555555796fc0 "n == REG\_INFTY || locinput
== li"\,
&nbsp;    file=file@&#8203;entry=0x555555795f88 "regexec\.c"\, line=line@&#8203;entry=6493\,
function=function@&#8203;entry=0x555555798b08 \<\_\_PRETTY\_FUNCTION\_\_\.14818>
"S\_regmatch"\)
&nbsp;    at assert\.c&#8203;:101
\#4  0x000055555570670c in S\_regmatch \(prog=\<optimized out>\,
startpos=0x555555a00a10 "\\r\\r0"\, reginfo=0x7fffffffddb0\) at
regexec\.c&#8203;:6493
\#5  S\_regtry \(reginfo=reginfo@&#8203;entry=0x7fffffffddb0\,
startposp=startposp@&#8203;entry=0x7fffffffdd98\) at regexec\.c&#8203;:3200
\#6  0x0000555555711530 in Perl\_regexec\_flags \(rx=0x5555559f4c20\,
stringarg=0x555555a00a10 "\\r\\r0"\, strend=0x555555a00a13 ""\,
strbeg=0x555555a00a10 "\\r\\r0"\,
&nbsp;    minend=\<optimized out>\, sv=0x5555559f4b60\, data=0x0\, flags=97\) at
regexec\.c&#8203;:2917
\#7  0x0000555555656e29 in Perl\_pp\_match \(\) at pp\_hot\.c&#8203;:1446
\#8  0x000055555562aa8a in Perl\_runops\_debug \(\) at dump\.c&#8203;:2427
\#9  0x00005555555ae109 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2456
\#10 perl\_run \(my\_perl=\<optimized out>\) at perl\.c&#8203;:2372
\#11 0x0000555555582b1f in main \(argc=\<optimized out>\, argv=\<optimized
out>\, env=\<optimized out>\) at perlmain\.c&#8203;:114

This is a regression between 5\.18 and 5\.20\, bisect points to

commit b24b43f7631ee39f0260fc7bba01dd65715f5aff \(HEAD\, refs/bisect/bad\)
Author&#8203;: Karl Williamson \<public@&#8203;khwilliamson\.com>
Date&#8203;:   Mon Jan 6 13&#8203;:41&#8203;:46 2014 \-0700

&nbsp;    IDStart and IDCont no longer go out to disk

&nbsp;    These are the base names for various macros used in parsing identifiers\.
&nbsp;    Prior to this patch\, parsing a code point above Latin1 caused loading
&nbsp;    disk files\.  This patch causes all the information to be compiled into
&nbsp;    the Perl binary\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.29.9:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 29 subversion 9) configuration:
  Commit id: c1e47bad34ce1d9c84ed57c9b8978bcbd5a02e98
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-thread-multi-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING -Dusethreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector
-I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'



@INC for perl 5.29.9:
    lib
    /usr/local/lib/perl5/site_perl/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.29.9
    /usr/local/lib/perl5/5.29.9/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.29.9


Environment for perl 5.29.9:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.84
    PERLBREW_VERSION=0.84
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>

**Comment by richardleach** [comment]
Doesn't assert on blead. Attempting to bisect.

**Comment by richardleach** [comment]
The assertion starting to pass bisected to this:
```
commit c50e79de5d7380bf4269155ab659ec3f66d5aa35
Author: Hugo van der Sanden <hv@crypt.org>
Date:   Mon Mar 21 21:55:01 2022 +0000

    gh17746: add missing check on hardcount
    
    Failing to check for max iterations caused an assertion failure.
```
I'll look into whether a separate test should be added, but this seems very similar to https://github.com/Perl/perl5/issues/17746, for which a test was added in the commit above.

**Comment by hvds** [comment]
I haven't looked at this case in any detail (not sure how I missed it, sorry about that), but in #17746 I explicitly noted that the missing check was in "the non-utf8 branch" (for LNBREAK in regrepeat), so the `use utf8` in this case is suggestive of a difference.

**Comment by richardleach** [comment]
Thanks, I'll leave this open pending some more looking at it.
