### ISSUE TITLE
SEGV (gv.c:2445:12) in Perl_gv_fetchpvn_flags

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#17089]
Migrated from [rt.perl.org#134276](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134276) (status was 'open')

Searchable as RT134276$

**Comment by p5pRT** [comment]
### From imdb95@gmail.com

Hello\,
I found this bug when fuzzing perl5\.

\*\*\*\*\*\*\*\*\*\*Compilation and environment\*\*\*\*\*\*\*\*\*\*
root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# \./perl/perl \-v

This is perl 5\, version 31\, subversion 2 \(v5\.31\.2 \(v5\.31\.1\-6\-g9649a81\)\)
built for x86\_64\-linux

Copyright 1987\-2019\, Larry Wall

Perl may be copied only under the terms of either the Artistic License or
the
GNU General Public License\, which may be found in the Perl 5 source kit\.

Complete documentation for Perl\, including FAQ lists\, should be found on
this system using "man perl" or "perldoc perl"\.  If you have access to the
Internet\, point your browser at http&#8203;://www\.perl\.org/\, the Perl Home Page\.


---
root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# uname \-a
Linux instance\-2 4\.15\.0\-1036\-gcp \#38~16\.04\.1\-Ubuntu SMP Tue Jun 25 15&#8203;:30&#8203;:46
UTC 2019 x86\_64 x86\_64 x86\_64 GNU/Linux


---
root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# lsb\_release \-r
Release&#8203;:        16\.04


---
Compilation&#8203;:
AFL\_USE\_ASAN=1 \./Configure \-des \-Dusedevel \-DDEBUGGING \-Dcc=afl\-clang\-fast
\-Doptimize=\-g && AFL\_USE\_ASAN=1 make

\*\*\*\*\*\*\*\*\*\*Reproduce\*\*\*\*\*\*\*\*\*
root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# cat test\.pl
eval '"" =~ /$\{%&#8203;::=0\}\\i\{$k\{\*k=\\&0\}/';

root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# \./perl/perl test\.pl
ASAN&#8203;:DEADLYSIGNAL
=================================================================
==16882==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000038
\(pc 0x000000618d6b bp 0x7fff600e2950 sp 0x7fff600e27c0 T0\)
==16882==The signal is caused by a READ memory access\.
==16882==Hint&#8203;: address points to the zero page\.
&nbsp;    \#0 0x618d6a in Perl\_gv\_fetchpvn\_flags /root/fuzz\_perl/perl/gv\.c&#8203;:2445&#8203;:12
&nbsp;    \#1 0x61b1c7 in Perl\_gv\_fetchsv /root/fuzz\_perl/perl/gv\.c&#8203;:1588&#8203;:12
&nbsp;    \#2 0x9fd20d in S\_anonymise\_cv\_maybe /root/fuzz\_perl/perl/sv\.c&#8203;:6520&#8203;:14
&nbsp;    \#3 0x9fd20d in Perl\_sv\_kill\_backrefs /root/fuzz\_perl/perl/sv\.c&#8203;:6301
&nbsp;    \#4 0x8d1781 in Perl\_magic\_killbackrefs /root/fuzz\_perl/perl/mg\.c&#8203;:2548&#8203;:5
&nbsp;    \#5 0x9f9b4a in S\_sv\_unmagicext\_flags /root/fuzz\_perl/perl/sv\.c&#8203;:5863&#8203;:3
&nbsp;    \#6 0xa03991 in Perl\_sv\_unmagic /root/fuzz\_perl/perl/sv\.c&#8203;:5901&#8203;:12
&nbsp;    \#7 0xa03991 in Perl\_sv\_clear /root/fuzz\_perl/perl/sv\.c&#8203;:6598
&nbsp;    \#8 0xa0c16e in Perl\_sv\_free2 /root/fuzz\_perl/perl/sv\.c&#8203;:7093&#8203;:9
&nbsp;    \#9 0x511504 in S\_SvREFCNT\_dec\_NN /root/fuzz\_perl/perl/\./inline\.h&#8203;:227&#8203;:2
&nbsp;    \#10 0x511504 in S\_op\_clear\_gv /root/fuzz\_perl/perl/op\.c&#8203;:970
&nbsp;    \#11 0x511504 in Perl\_op\_clear /root/fuzz\_perl/perl/op\.c&#8203;:1003
&nbsp;    \#12 0x50e165 in Perl\_op\_free /root/fuzz\_perl/perl/op\.c&#8203;:914&#8203;:9
&nbsp;    \#13 0x50ddab in Perl\_op\_free /root/fuzz\_perl/perl/op\.c&#8203;:897&#8203;:21
&nbsp;    \#14 0xaf8fa1 in Perl\_leave\_scope /root/fuzz\_perl/perl/scope\.c&#8203;:1127&#8203;:6
&nbsp;    \#15 0xb31a86 in S\_pop\_eval\_context\_maybe\_croak
/root/fuzz\_perl/perl/pp\_ctl\.c&#8203;:1633&#8203;:5
&nbsp;    \#16 0xb310b8 in Perl\_die\_unwind /root/fuzz\_perl/perl/pp\_ctl\.c&#8203;:1785&#8203;:13
&nbsp;    \#17 0x88fc1f in Perl\_vcroak /root/fuzz\_perl/perl/util\.c&#8203;:1711&#8203;:5
&nbsp;    \#18 0x886a2a in Perl\_croak /root/fuzz\_perl/perl/util\.c&#8203;:1756&#8203;:5
\#19 0x826976 in S\_regatom /root/fuzz\_perl/perl/regcomp\.c
&nbsp;    \#20 0x7f744b in S\_regpiece /root/fuzz\_perl/perl/regcomp\.c&#8203;:12466&#8203;:11
&nbsp;    \#21 0x7f744b in S\_regbranch /root/fuzz\_perl/perl/regcomp\.c&#8203;:12386
&nbsp;    \#22 0x752f1e in S\_reg /root/fuzz\_perl/perl/regcomp\.c&#8203;:12097&#8203;:10
&nbsp;    \#23 0x72ecf5 in Perl\_re\_op\_compile /root/fuzz\_perl/perl/regcomp\.c&#8203;:7714&#8203;:9
&nbsp;    \#24 0xb09f34 in Perl\_pp\_regcomp /root/fuzz\_perl/perl/pp\_ctl\.c&#8203;:108&#8203;:14
&nbsp;    \#25 0x88087c in Perl\_runops\_debug /root/fuzz\_perl/perl/dump\.c&#8203;:2537&#8203;:23
&nbsp;    \#26 0x5e95f2 in S\_run\_body /root/fuzz\_perl/perl/perl\.c
&nbsp;    \#27 0x5e95f2 in perl\_run /root/fuzz\_perl/perl/perl\.c&#8203;:2639
&nbsp;    \#28 0x50a398 in main /root/fuzz\_perl/perl/perlmain\.c&#8203;:127&#8203;:9
&nbsp;    \#29 0x7f5fa777d82f in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2082f\)
&nbsp;    \#30 0x4368c8 in \_start \(/root/fuzz\_perl/perl/perl\+0x4368c8\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /root/fuzz\_perl/perl/gv\.c&#8203;:2445&#8203;:12 in
Perl\_gv\_fetchpvn\_flags
==16882==ABORTING

Please confirm the bug\.

Thanks\,
Manh Nguyen

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, Jul 09\, 2019 at 02&#8203;:20&#8203;:37AM \-0700\, Nguyen Duc Manh wrote&#8203;:
> eval '"" =~ /$\{%&#8203;::=0\}\\i\{$k\{\*k=\\&0\}/';

The important part of that code is

&nbsp;    %&#8203;:: = \(0\);

i\.e\. its deleting the entire contents of the root stash\. Bad things tend
to happen after that\. Ideally we'd like for perl not to crash even then\,
but its not a security issue\, for the same reasons I stated in another
of your tickets today\.

\-\- 
This is a great day for France\!
&nbsp;    \-\- Nixon at Charles De Gaulle's funeral

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue\, 09 Jul 2019 03&#8203;:17&#8203;:25 \-0700\, davem wrote&#8203;:
> On Tue\, Jul 09\, 2019 at 02&#8203;:20&#8203;:37AM \-0700\, Nguyen Duc Manh wrote&#8203;:
> > eval '"" =~ /$\{%&#8203;::=0\}\\i\{$k\{\*k=\\&0\}/';
> 
> The important part of that code is
> 
>     %&#8203;:: = \(0\);
> 
> i\.e\. its deleting the entire contents of the root stash\. Bad things tend
> to happen after that\. Ideally we'd like for perl not to crash even then\,
> but its not a security issue\, for the same reasons I stated in another
> of your tickets today\.

Agreed\, now public\.

Tony
