### ISSUE TITLE
SEGV (sv.c:16672:7) in S_find_uninit_var

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#17088]
Migrated from [rt.perl.org#134275](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134275) (status was 'pending release')

Searchable as RT134275$

**Comment by p5pRT** [comment]
### From imdb95@gmail.com

Hello\,
I found this bug when fuzzing perl5\.

\*\*\*\*\*\*\*\*\*\*Compilation and environment\*\*\*\*\*\*\*\*\*\*
root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# \./perl/perl \-v

This is perl 5\, version 31\, subversion 2 \(v5\.31\.2 \(v5\.31\.1\-6\-g9649a81\)\)
built for x86\_64\-linux

Copyright 1987\-2019\, Larry Wall

Perl may be copied only under the terms of either the Artistic License or
the
GNU General Public License\, which may be found in the Perl 5 source kit\.

Complete documentation for Perl\, including FAQ lists\, should be found on
this system using "man perl" or "perldoc perl"\.  If you have access to the
Internet\, point your browser at http&#8203;://www\.perl\.org/\, the Perl Home Page\.


---
root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# uname \-a
Linux instance\-2 4\.15\.0\-1036\-gcp \#38~16\.04\.1\-Ubuntu SMP Tue Jun 25 15&#8203;:30&#8203;:46
UTC 2019 x86\_64 x86\_64 x86\_64 GNU/Linux


---
root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# lsb\_release \-r
Release&#8203;:        16\.04


---
Compilation&#8203;:
AFL\_USE\_ASAN=1 \./Configure \-des \-Dusedevel \-DDEBUGGING \-Dcc=afl\-clang\-fast
\-Doptimize=\-g && AFL\_USE\_ASAN=1 make

\*\*\*\*\*\*\*\*\*\*Reproduce\*\*\*\*\*\*\*\*\*
root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# \./perl/perl test\.pl
Use of uninitialized value in regexp compilation at test\.pl line 1\.
ASAN&#8203;:DEADLYSIGNAL
=================================================================
==16809==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x00000000000e
\(pc 0x000000a5b363 bp 0x000000000000 sp 0x7ffefbd990c0 T0\)
==16809==The signal is caused by a READ memory access\.
==16809==Hint&#8203;: address points to the zero page\.
&nbsp;    \#0 0xa5b362 in S\_find\_uninit\_var /root/fuzz\_perl/perl/sv\.c&#8203;:16672&#8203;:7
&nbsp;    \#1 0xa589c5 in S\_find\_uninit\_var /root/fuzz\_perl/perl/sv\.c&#8203;:16923&#8203;:11
&nbsp;    \#2 0x9b333e in Perl\_report\_uninit /root/fuzz\_perl/perl/sv\.c&#8203;:16956&#8203;:16
&nbsp;    \#3 0x9acc4e in Perl\_sv\_2pv\_flags /root/fuzz\_perl/perl/sv\.c&#8203;:3251&#8203;:6
&nbsp;    \#4 0x9f5336 in Perl\_sv\_catsv\_flags /root/fuzz\_perl/perl/sv\.c&#8203;:5550&#8203;:20
&nbsp;    \#5 0x744ebd in S\_concat\_pat /root/fuzz\_perl/perl/regcomp\.c&#8203;:6822&#8203;:17
&nbsp;    \#6 0x7276d4 in Perl\_re\_op\_compile /root/fuzz\_perl/perl/regcomp\.c&#8203;:7478&#8203;:11
&nbsp;    \#7 0xb09f34 in Perl\_pp\_regcomp /root/fuzz\_perl/perl/pp\_ctl\.c&#8203;:108&#8203;:14
&nbsp;    \#8 0x88087c in Perl\_runops\_debug /root/fuzz\_perl/perl/dump\.c&#8203;:2537&#8203;:23
&nbsp;    \#9 0x5e95f2 in S\_run\_body /root/fuzz\_perl/perl/perl\.c
&nbsp;    \#10 0x5e95f2 in perl\_run /root/fuzz\_perl/perl/perl\.c&#8203;:2639
&nbsp;    \#11 0x50a398 in main /root/fuzz\_perl/perl/perlmain\.c&#8203;:127&#8203;:9
&nbsp;    \#12 0x7fbdff93282f in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2082f\)
&nbsp;    \#13 0x4368c8 in \_start \(/root/fuzz\_perl/perl/perl\+0x4368c8\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /root/fuzz\_perl/perl/sv\.c&#8203;:16672&#8203;:7 in
S\_find\_uninit\_var
==16809==ABORTING

Please confirm the bug\. Crash also happens with the default version v5\.22\.1
of perl on Ubuntu

Thanks\,
Manh Nguyen

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, Jul 09\, 2019 at 02&#8203;:15&#8203;:50AM \-0700\, Nguyen Duc Manh wrote&#8203;:
> root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# \./perl/perl test\.pl

You don't appear to have included the contents of test\.pl in your report\.

\-\- 
"Emacs isn't a bad OS once you get used to it\.
It just lacks a decent editor\."

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From imdb95@gmail.com

Sorry\!
Here it is&#8203;: '' =~ /@&#8203;\{$^W=g^\_\}$\_\{a\}$\{\*0=\*\_=0\}$00/;

On Tue\, Jul 9\, 2019 at 5&#8203;:10 PM Dave Mitchell via RT \<
perl5\-security\-report\-followup@&#8203;perl\.org> wrote&#8203;:

> You don't appear to have included the contents of test\.pl in your report\.
>

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, Jul 09\, 2019 at 05&#8203;:14&#8203;:27PM \+0700\, Peter Nguyen wrote&#8203;:
> Sorry\!
> Here it is&#8203;: '' =~ /@&#8203;\{$^W=g^\_\}$\_\{a\}$\{\*0=\*\_=0\}$00/;

Fixed with the commit below\. I don't consider it a security issue\, because
it can only be triggered by convoluted src code\, not by a convoluted
regex pattern\. And the only thing it can trigger is a SEGV from dereffing
a NULL pointer\.

commit 28eabf1185634216ca335b3a24e1131b0f392ca1
Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
AuthorDate&#8203;: Wed Jul 10 12&#8203;:59&#8203;:06 2019 \+0100
Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
CommitDate&#8203;: Wed Jul 10 12&#8203;:59&#8203;:06 2019 \+0100

&nbsp;    avoid SEGV with uninit warning with multideref
&nbsp;    
&nbsp;    RT \#134275
&nbsp;    
&nbsp;    When the 'uninitialized warning' code in S\_find\_uninit\_var\(\) comes
&nbsp;    across an OP\_MULTIDEREF node\, it scans it to see if any part of that op
&nbsp;    \(e\.g\. the indices or the returned value\) could have been the source of
&nbsp;    the uninitialized value which triggered the warning\.  Unfortunately when
&nbsp;    getting an AV or HV from a GV\, it wasn't checking whether gp\_av/gp\_hv
&nbsp;    contained a NULL value\. If so\, it would SEGV\.
&nbsp;    
&nbsp;    The test code is a bit contrived; you have to "pull the rug" from under
&nbsp;    the GV at just the right moment with \*foo = \*bar\, then trigger an uninit
&nbsp;    warning on an op whose subtree includes an OP\_MULTIDEREF\.

M       sv\.c
M       t/lib/warnings/9uninit


\-\- 
No man treats a motor car as foolishly as he treats another human being\.
When the car will not go\, he does not attribute its annoying behaviour to
sin\, he does not say\, You are a wicked motorcar\, and I shall not give you
any more petrol until you go\. He attempts to find out what is wrong and
set it right\.
&nbsp;    \-\- Bertrand Russell\,
&nbsp;       Has Religion Made Useful Contributions to Civilization?

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'pending release'
