### ISSUE TITLE
heap-buffer-overflow in Perl_sv_catpv_flags (perl/sv.c:5609:5)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#17085]
Migrated from [rt.perl.org#134271](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134271) (status was 'pending release')

Searchable as RT134271$

**Comment by p5pRT** [comment]
### From imdb95@gmail.com

Hello\,
I found this bug when fuzzing perl5\.

\*\*\*\*\*\*\*\*\*\*Compilation and environment\*\*\*\*\*\*\*\*\*\*
root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# \./perl/perl \-v

This is perl 5\, version 31\, subversion 2 \(v5\.31\.2 \(v5\.31\.1\-6\-g9649a81\)\)
built for x86\_64\-linux

Copyright 1987\-2019\, Larry Wall

Perl may be copied only under the terms of either the Artistic License or
the
GNU General Public License\, which may be found in the Perl 5 source kit\.

Complete documentation for Perl\, including FAQ lists\, should be found on
this system using "man perl" or "perldoc perl"\.  If you have access to the
Internet\, point your browser at http&#8203;://www\.perl\.org/\, the Perl Home Page\.


---
root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# uname \-a
Linux instance\-2 4\.15\.0\-1036\-gcp \#38~16\.04\.1\-Ubuntu SMP Tue Jun 25 15&#8203;:30&#8203;:46
UTC 2019 x86\_64 x86\_64 x86\_64 GNU/Linux


---
root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# lsb\_release \-r
Release&#8203;:        16\.04


---
Compilation&#8203;:
AFL\_USE\_ASAN=1 \./Configure \-des \-Dusedevel \-DDEBUGGING \-Dcc=afl\-clang\-fast
\-Doptimize=\-g && AFL\_USE\_ASAN=1 make

\*\*\*\*\*\*\*\*\*\*Reproduce\*\*\*\*\*\*\*\*\*\*
root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# cat test\.pl
"" =~ /\_\(?\)|\_0|\\h@&#8203;\{$^D=rv\}\\x\{100\}\(\)/;
root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# \./perl/perl test\.pl
Assembling pattern from 3 elements
Compiling REx "\_\(?\)|\_0|\\h\\x\{100\}\(\)"
Starting parse and generation
\<\_\(?\)|\_0|\\h\\>\.\.\.|   1|  reg
&nbsp;                |    |    brnc
&nbsp;                |    |      piec
&nbsp;                |    |        atom
exact&#8203;:19596&#8203;: \(op EXACT\) OK 1 \(len 0\) \(max 65\)\.
\*\* \(19603\) offset of node 1 is 0\.
\*\* \(14746\) size of node 1 is 0\.
\<\(?\)|\_0|\\h\\x>\.\.\.|   3|      piec
&nbsp;                |    |        atom
\<?\)|\_0|\\h\\x\{>\.\.\.|    |          reg
\<|\_0|\\h\\x\{10>\.\.\.|    |    inst \- BRANCH
reginsert\(19738\)&#8203;: \(op BRANCH\) OK copy 2 \-> 3 \(max 3\)\.
\*\* \(19745\) offset of node 3 is 0\.
\*\* \(19746\) size of node 3 is 0\.
reginsert\(19738\)&#8203;: \(op BRANCH\) OK copy 1 \-> 2 \(max 3\)\.
\*\* \(19745\) offset of node 2 is 0\.
\*\* \(19746\) size of node 2 is 0\.
reginsert\(19757\)&#8203;: \(op BRANCH\) OK 1 \<\- 4 \(max 3\)\.
\*\* \(19764\) offset of node 1 is 4\.
\*\* \(19765\) size of node 1 is 1\.
\*\* \(12111\) size of node 1 is 0\.
\*\* \(12112\) offset of node 1 is 0\.
\<\_0|\\h\\x\{100\}\(\)>|   4|    brnc
reg\_node&#8203;:19596&#8203;: \(op BRANCH\) OK 4 \(len 5\) \(max 4\)\.
\*\* \(19603\) offset of node 4 is 5\.
\*\* \(12376\) size of node 4 is 1\.
&nbsp;                |   5|      piec
&nbsp;                |    |        atom
exact&#8203;:19596&#8203;: \(op EXACT\) OK 5 \(len 5\) \(max 69\)\.
\*\* \(19603\) offset of node 5 is 5\.
\*\* \(14746\) size of node 5 is 1\.
\<|\\h\\x\{100\}\(\)>  |   7|    tail~ BRANCH \(1\) \-> BRANCH
\<\\h\\x\{100\}\(\)>   |    |    brnc
reg\_node&#8203;:19596&#8203;: \(op BRANCH\) OK 7 \(len 8\) \(max 7\)\.
\*\* \(19603\) offset of node 7 is 8\.
\*\* \(12376\) size of node 7 is 1\.
&nbsp;                |   8|      piec
&nbsp;                |    |        atom
reg\_node&#8203;:19596&#8203;: \(op POSIXU\) OK 8 \(len 9\) \(max 8\)\.
\*\* \(19603\) offset of node 8 is 9\.
\*\* \(13650\) size of node 8 is 2\.
\<\\x\{100\}\(\)>     |   9|      piec
&nbsp;                |    |        atom
exact&#8203;:19596&#8203;: \(op EXACT\) OK 9 \(len 10\) \(max 73\)\.
\*\* \(19603\) offset of node 9 is 10\.
UTF8 mismatch\! Converting to utf8 for resizing and compile
Need to redo parse after upgrade
Freeing REx&#8203;: "\_\(?\)|\_0|\\h\\x\{100\}\(\)"
Starting parse and generation
\<\_\(?\)|\_0|\\h\\>\.\.\.|   1|  reg
&nbsp;                |    |    brnc
&nbsp;                |    |      piec
&nbsp;                |    |        atom
exact&#8203;:19596&#8203;: \(op EXACT\) OK 1 \(len 0\) \(max 65\)\.
\*\* \(19603\) offset of node 1 is 0\.
\*\* \(14746\) size of node 1 is 0\.
\<\(?\)|\_0|\\h\\x>\.\.\.|   3|      piec
&nbsp;                |    |        atom
\<?\)|\_0|\\h\\x\{>\.\.\.|    |          reg
\<|\_0|\\h\\x\{10>\.\.\.|    |    inst \- BRANCH
reginsert\(19738\)&#8203;: \(op BRANCH\) OK copy 2 \-> 3 \(max 3\)\.
\*\* \(19745\) offset of node 3 is 0\.
\*\* \(19746\) size of node 3 is 0\.
reginsert\(19738\)&#8203;: \(op BRANCH\) OK copy 1 \-> 2 \(max 3\)\.
\*\* \(19745\) offset of node 2 is 0\.
\*\* \(19746\) size of node 2 is 0\.
reginsert\(19757\)&#8203;: \(op BRANCH\) OK 1 \<\- 4 \(max 3\)\.
\*\* \(19764\) offset of node 1 is 4\.
\*\* \(19765\) size of node 1 is 1\.
\*\* \(12111\) size of node 1 is 0\.
\*\* \(12112\) offset of node 1 is 0\.
\<\_0|\\h\\x\{100\}\(\)>|   4|    brnc
reg\_node&#8203;:19596&#8203;: \(op BRANCH\) OK 4 \(len 5\) \(max 4\)\.
\*\* \(19603\) offset of node 4 is 5\.
\*\* \(12376\) size of node 4 is 1\.
&nbsp;                |   5|      piec
&nbsp;                |    |        atom
exact&#8203;:19596&#8203;: \(op EXACT\) OK 5 \(len 5\) \(max 69\)\.
\*\* \(19603\) offset of node 5 is 5\.
\*\* \(14746\) size of node 5 is 1\.
\<|\\h\\x\{100\}\(\)>  |   7|    tail~ BRANCH \(1\) \-> BRANCH
\<\\h\\x\{100\}\(\)>   |    |    brnc
reg\_node&#8203;:19596&#8203;: \(op BRANCH\) OK 7 \(len 8\) \(max 7\)\.
\*\* \(19603\) offset of node 7 is 8\.
\*\* \(12376\) size of node 7 is 1\.
&nbsp;                |   8|      piec
&nbsp;                |    |        atom
reg\_node&#8203;:19596&#8203;: \(op POSIXU\) OK 8 \(len 9\) \(max 8\)\.
\*\* \(19603\) offset of node 8 is 9\.
\*\* \(13650\) size of node 8 is 2\.
\<\\x\{100\}\(\)>     |   9|      piec
&nbsp;                |    |        atom
exact&#8203;:19596&#8203;: \(op EXACT\) OK 9 \(len 10\) \(max 73\)\.
\*\* \(19603\) offset of node 9 is 10\.
\*\* \(14746\) size of node 9 is 6\.
\<\(\)>            |  11|      tail~ POSIXU\[&#8203;:blank&#8203;:\] \(8\) \-> EXACT\_ONLY8
&nbsp;                |    |      piec
&nbsp;                |    |        atom
\<\)>             |    |          reg
reganode&#8203;:19596&#8203;: \(op OPEN\) OK 11 \(len 18\) \(max 12\)\.
\*\* \(19603\) offset of node 11 is 18\.
&nbsp;                |    |            Setting open paren \#1 to 11
\*\* \(12081\) size of node 11 is 1\.
\*\* \(12082\) offset of node 11 is 18\.
&nbsp;                |  13|            brnc
reg\_node&#8203;:19596&#8203;: \(op NOTHING\) OK 13 \(len 18\) \(max 13\)\.
\*\* \(19603\) offset of node 13 is 18\.
&nbsp;                |  14|            tail~ OPEN1 \(11\) \-> NOTHING
reganode&#8203;:19596&#8203;: \(op CLOSE\) OK 14 \(len 18\) \(max 15\)\.
\*\* \(19603\) offset of node 14 is 18\.
&nbsp;                |    |            Setting close paren \#1 to 14
\*\* \(12173\) offset of node 14 is 19\.
\*\* \(12174\) size of node 14 is 1\.
&nbsp;                |  16|          lsbr~ tying lastbr NOTHING \(13\) to ender
CLOSE1 \(14\) offset 1
&nbsp;                |    |            tail~ NOTHING \(13\) \-> CLOSE
\<>              |    |      tail~ EXACT\_ONLY8 \<\\x\{100\}> \(9\) \-> OPEN
&nbsp;                |    |    tail~ BRANCH \(4\) \-> BRANCH
reg\_node&#8203;:19596&#8203;: \(op END\) OK 16 \(len 19\) \(max 16\)\.
\*\* \(19603\) offset of node 16 is 20\.
&nbsp;                |    |    Setting close paren \#0 \(END\) to 16
&nbsp;                |  17|  lsbr~ tying lastbr BRANCH \(7\) to ender END \(16\)
offset 9
&nbsp;                |    |    tail~ BRANCH \(7\) \-> END
&nbsp;                |    |    tsdy~ EXACT \<\_> \(2\) \-> EXACT
&nbsp;                |    |        ~ attach to END \(16\) offset to 14
&nbsp;                |    |    tsdy~ EXACT \<\_0> \(5\) \-> EXACT
&nbsp;                |    |        ~ attach to END \(16\) offset to 11
&nbsp;                |    |    tsdy~ POSIXU\[&#8203;:blank&#8203;:\] \(8\) \-> END
&nbsp;                |    |        ~ EXACT\_ONLY8 \<\\x\{100\}> \(9\) \-> END
&nbsp;                |    |        ~ OPEN1 \(11\) \-> END
&nbsp;                |    |        ~ NOTHING \(13\) \-> END
&nbsp;                |    |        ~ CLOSE1 \(14\) \-> END
&nbsp;                |    |        ~ attach to END \(16\) offset to 2
Required size 16 nodes
Got 33 bytes for offset annotations\.
Offsets&#8203;: \[16\]
&nbsp;        4&#8203;:5\[1\] 5&#8203;:5\[1\] 7&#8203;:8\[1\] 8&#8203;:9\[2\] 9&#8203;:10\[6\] 11&#8203;:18\[1\] 13&#8203;:18\[0\] 14&#8203;:19\[1\]
16&#8203;:20\[0\]
Starting post parse optimization

Multi Top Level
RExC\_seen&#8203;: REG\_TOP\_LEVEL\_BRANCHES\_SEEN
study\_chunk stopparen=\-1 recursed\_count=1 depth=0 recursed\_depth=0
scan=60c000001aac last=60c000001aec
Peep&#8203;: Pos&#8203;:0/0 Flags&#8203;: 0x0 Whilem\_c&#8203;: 0 Lcp&#8203;: 0
Peep>  1&#8203;: BRANCH \(4\) \[ SCF\_DO\_STCLASS\_AND SCF\_DO\_STCLASS
SCF\_WHILEM\_VISITED\_POS \]
Branch>  1&#8203;: BRANCH \(4\) \[ SCF\_DO\_STCLASS\_AND SCF\_DO\_STCLASS
SCF\_WHILEM\_VISITED\_POS \]
&nbsp;  study\_chunk stopparen=\-1 recursed\_count=2 depth=1 recursed\_depth=0
scan=60c000001ab0 last=60c000001ab8
&nbsp;  Peep&#8203;: Pos&#8203;:0/0 Flags&#8203;: 0x0 Whilem\_c&#8203;: 0 Lcp&#8203;: 0
&nbsp;  Peep>  2&#8203;: EXACT \<\_> \(16\) \[ SCF\_DO\_STCLASS\_AND SCF\_DO\_STCLASS
SCF\_WHILEM\_VISITED\_POS \]
&nbsp;    join>  2&#8203;: EXACT \<\_> \(16\)
&nbsp;  pre\-fin&#8203;: Pos&#8203;:0/0 Flags&#8203;: 0x0 Whilem\_c&#8203;: 0 Lcp&#8203;: 0
&nbsp;  post\-fin&#8203;: Pos&#8203;:0/0 Flags&#8203;: 0x0 Whilem\_c&#8203;: 0 Lcp&#8203;: 0
Branch>  4&#8203;: BRANCH \(7\) \[ SCF\_DO\_STCLASS\_AND SCF\_DO\_STCLASS
SCF\_WHILEM\_VISITED\_POS \]
&nbsp;  study\_chunk stopparen=\-1 recursed\_count=3 depth=1 recursed\_depth=0
scan=60c000001abc last=60c000001ac4
&nbsp;  Peep&#8203;: Pos&#8203;:0/0 Flags&#8203;: 0x0 Whilem\_c&#8203;: 0 Lcp&#8203;: 0
&nbsp;  Peep>  5&#8203;: EXACT \<\_0> \(16\) \[ SCF\_DO\_STCLASS\_AND SCF\_DO\_STCLASS
SCF\_WHILEM\_VISITED\_POS \]
&nbsp;    join>  5&#8203;: EXACT \<\_0> \(16\)
&nbsp;  pre\-fin&#8203;: Pos&#8203;:0/0 Flags&#8203;: 0x0 Whilem\_c&#8203;: 0 Lcp&#8203;: 0
&nbsp;  post\-fin&#8203;: Pos&#8203;:0/0 Flags&#8203;: 0x0 Whilem\_c&#8203;: 0 Lcp&#8203;: 0
Branch>  7&#8203;: BRANCH \(16\) \[ SCF\_DO\_STCLASS\_AND SCF\_DO\_STCLASS
SCF\_WHILEM\_VISITED\_POS \]
&nbsp;  study\_chunk stopparen=\-1 recursed\_count=4 depth=1 recursed\_depth=0
scan=60c000001ac8 last=60c000001ae8
&nbsp;  Peep&#8203;: Pos&#8203;:0/0 Flags&#8203;: 0x0 Whilem\_c&#8203;: 0 Lcp&#8203;: 0
&nbsp;  Peep>  8&#8203;: POSIXU\[&#8203;:blank&#8203;:\] \(9\) \[ SCF\_DO\_STCLASS\_AND SCF\_DO\_STCLASS
SCF\_WHILEM\_VISITED\_POS \]
&nbsp;  Peep&#8203;: Pos&#8203;:0/0 Flags&#8203;: 0x0 Whilem\_c&#8203;: 0 Lcp&#8203;: 0
&nbsp;  Peep>  9&#8203;: EXACT\_ONLY8 \<\\x\{100\}> \(11\) \[ SCF\_WHILEM\_VISITED\_POS \]
&nbsp;    join>  9&#8203;: EXACT\_ONLY8 \<\\x\{100\}> \(11\)
&nbsp;  Peep&#8203;: Pos&#8203;:0/0 Flags&#8203;: 0x0 Whilem\_c&#8203;: 0 Lcp&#8203;: 0
&nbsp;  Peep> 11&#8203;: OPEN1 \(13\) \[ SCF\_WHILEM\_VISITED\_POS \]
&nbsp;  Peep&#8203;: Pos&#8203;:0/0 Flags&#8203;: 0x0 Whilem\_c&#8203;: 0 Lcp&#8203;: 0
&nbsp;    Peep> 14&#8203;: CLOSE1 \(16\) \[ SCF\_WHILEM\_VISITED\_POS \]
&nbsp;  pre\-fin&#8203;: Pos&#8203;:0/0 Flags&#8203;: 0x0 Whilem\_c&#8203;: 0 Lcp&#8203;: 1
&nbsp;  post\-fin&#8203;: Pos&#8203;:0/0 Flags&#8203;: 0x80 \[SF\_HAS\_PAR \] Whilem\_c&#8203;: 0 Lcp&#8203;: 1
&nbsp;  Looking for TRIE'able sequences\. Tail node is  16&#8203;:END
&nbsp;  \- 1&#8203;:BRANCH \(1\) \-> 2&#8203;:EXACT \<\_> => 16&#8203;:END
\(First==\-1\,Last==\-1\,Cur==1\,tt==END\,ntt==EXACT\,nntt==END\)
&nbsp;  \- 4&#8203;:BRANCH \(4\) \-> 5&#8203;:EXACT \<\_0>        => 16&#8203;:END
\(First==1\,Last==\-1\,Cur==4\,tt==EXACT\,ntt==EXACT\,nntt==END\)
&nbsp;  \- 7&#8203;:BRANCH \(7\) \-> 8&#8203;:POSIXU\[&#8203;:blank&#8203;:\]   => 9&#8203;:EXACT\_ONLY8 \<\\x\{100\}>
 \(First==1\,Last==4\,Cur==7\,tt==EXACT\,ntt==END\,nntt==EXACT\)
&nbsp;    make\_trie start==1\, first==1\, last==7\, tail==16 depth=1
&nbsp;    TRIE\(NATIVE\)&#8203;: W&#8203;:2 C&#8203;:3 Uq&#8203;:2 Min&#8203;:1 Max&#8203;:2
&nbsp;    Compiling trie using table compiler
&nbsp;      Char :    \_   0
&nbsp;      State\+\-\-\-\-\-\-\-\-\-
&nbsp;         1 :    2   \. \(   1\)
&nbsp;         2 :    \.   3 \(   1\) W   1
&nbsp;         3 :    \.   \. \(   0\) W   2
&nbsp;    Alloc&#8203;: 9 Orig&#8203;: 7 elements\, Final&#8203;:2\. Savings of %71\.43
&nbsp;    Statecount&#8203;:4 Lasttrans&#8203;:3
&nbsp;    MJD offset&#8203;:0 MJD length&#8203;:0
&nbsp;    Prefix State&#8203;: 1 Ofs&#8203;:0 Char='\_'
&nbsp;    New Start State=2 Class&#8203;:
\[=================================================================
==31902==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
0x6020000054df at pc 0x000000448a35 bp 0x7ffd2a31e530 sp 0x7ffd2a31dcd8
READ of size 16 at 0x6020000054df thread T0
&nbsp;    \#0 0x448a34 in \_\_interceptor\_strlen
/scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-rt/lib/asan/\.\./sanitizer\_common/sanitizer\_common\_interceptors\.inc&#8203;:284&#8203;:5
&nbsp;    \#1 0xa4837d in Perl\_sv\_catpv\_flags /root/fuzz\_perl/perl/sv\.c&#8203;:5609&#8203;:5
&nbsp;    \#2 0xa4837d in Perl\_sv\_vcatpvfn\_flags /root/fuzz\_perl/perl/sv\.c&#8203;:11931
&nbsp;    \#3 0xa2ab53 in Perl\_sv\_vsetpvfn /root/fuzz\_perl/perl/sv\.c&#8203;:10987&#8203;:5
&nbsp;    \#4 0xa2ab53 in Perl\_vnewSVpvf /root/fuzz\_perl/perl/sv\.c&#8203;:9592
&nbsp;    \#5 0xd58d1b in PerlIO\_vprintf /root/fuzz\_perl/perl/perlio\.c&#8203;:5006&#8203;:10
&nbsp;    \#6 0x7247cd in Perl\_re\_printf /root/fuzz\_perl/perl/regcomp\.c&#8203;:1041&#8203;:14
&nbsp;    \#7 0x7dee0f in S\_make\_trie /root/fuzz\_perl/perl/regcomp\.c&#8203;:3515&#8203;:29
&nbsp;   \#8 0x77c3a8 in S\_study\_chunk /root/fuzz\_perl/perl/regcomp\.c&#8203;:4968&#8203;:41
&nbsp;    \#9 0x7350bf in Perl\_re\_op\_compile /root/fuzz\_perl/perl/regcomp\.c&#8203;:8185&#8203;:11
&nbsp;    \#10 0xb09f34 in Perl\_pp\_regcomp /root/fuzz\_perl/perl/pp\_ctl\.c&#8203;:108&#8203;:14
&nbsp;    \#11 0x88087c in Perl\_runops\_debug /root/fuzz\_perl/perl/dump\.c&#8203;:2537&#8203;:23
&nbsp;    \#12 0x5e95f2 in S\_run\_body /root/fuzz\_perl/perl/perl\.c
&nbsp;    \#13 0x5e95f2 in perl\_run /root/fuzz\_perl/perl/perl\.c&#8203;:2639
&nbsp;    \#14 0x50a398 in main /root/fuzz\_perl/perl/perlmain\.c&#8203;:127&#8203;:9
&nbsp;    \#15 0x7f63855a682f in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2082f\)
&nbsp;    \#16 0x4368c8 in \_start \(/root/fuzz\_perl/perl/perl\+0x4368c8\)

0x6020000054df is located 0 bytes to the right of 15\-byte region
\[0x6020000054d0\,0x6020000054df\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4dd5cc in malloc
/scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-rt/lib/asan/asan\_malloc\_linux\.cc&#8203;:66&#8203;:3
&nbsp;    \#1 0x88660e in Perl\_safesysmalloc /root/fuzz\_perl/perl/util\.c&#8203;:155&#8203;:21

SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow
/scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-rt/lib/asan/\.\./sanitizer\_common/sanitizer\_common\_interceptors\.inc&#8203;:284&#8203;:5
in \_\_interceptor\_strlen
Shadow bytes around the buggy address&#8203;:
&nbsp;  0x0c047fff8a40&#8203;: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
&nbsp;  0x0c047fff8a50&#8203;: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
&nbsp;  0x0c047fff8a60&#8203;: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
&nbsp;  0x0c047fff8a70&#8203;: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
&nbsp;  0x0c047fff8a80&#8203;: fa fa fd fd fa fa fd fd fa fa 04 fa fa fa fd fd
=>0x0c047fff8a90&#8203;: fa fa fd fd fa fa 00 07 fa fa 00\[07\]fa fa fd fd
&nbsp;  0x0c047fff8aa0&#8203;: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
&nbsp;  0x0c047fff8ab0&#8203;: fa fa 00 02 fa fa 00 02 fa fa fd fd fa fa fd fd
&nbsp;  0x0c047fff8ac0&#8203;: fa fa 00 02 fa fa fd fd fa fa fd fd fa fa fd fd
&nbsp;  0x0c047fff8ad0&#8203;: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
&nbsp;  0x0c047fff8ae0&#8203;: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
Shadow byte legend \(one shadow byte represents 8 application bytes\)&#8203;:
&nbsp;  Addressable&#8203;:           00
&nbsp;  Partially addressable&#8203;: 01 02 03 04 05 06 07
&nbsp;  Heap left redzone&#8203;:       fa
&nbsp;  Freed heap region&#8203;:       fd
&nbsp;  Stack left redzone&#8203;:      f1
&nbsp;  Stack mid redzone&#8203;:       f2
&nbsp;  Stack right redzone&#8203;:     f3
&nbsp;  Stack after return&#8203;:      f5
&nbsp;  Stack use after scope&#8203;:   f8
&nbsp;  Global redzone&#8203;:          f9
&nbsp;  Global init order&#8203;:       f6
&nbsp;  Poisoned by user&#8203;:        f7
&nbsp;  Container overflow&#8203;:      fc
&nbsp;  Array cookie&#8203;:            ac
&nbsp;  Intra object redzone&#8203;:    bb
&nbsp;  ASan internal&#8203;:           fe
&nbsp;  Left alloca redzone&#8203;:     ca
&nbsp;  Right alloca redzone&#8203;:    cb
==31902==ABORTING

Please confirm the bug\.

Thanks\,
Manh Nguyen

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Jul 08\, 2019 at 03&#8203;:45&#8203;:56AM \-0700\, Nguyen Duc Manh wrote&#8203;:
> \# cat test\.pl
> "" =~ /\_\(?\)|\_0|\\h@&#8203;\{$^D=rv\}\\x\{100\}\(\)/;

> \./perl/perl test\.pl
\.\.\.\.
>     New Start State=2 Class&#8203;:
> \[=================================================================
> ==31902==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
> 0x6020000054df at pc 0x000000448a35 bp 0x7ffd2a31e530 sp 0x7ffd2a31dcd8
> READ of size 16 at 0x6020000054df thread T0
>     \#0 0x448a34 in \_\_interceptor\_strlen
> /scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-rt/lib/asan/\.\./sanitizer\_common/sanitizer\_common\_interceptors\.inc&#8203;:284&#8203;:5
>     \#1 0xa4837d in Perl\_sv\_catpv\_flags /root/fuzz\_perl/perl/sv\.c&#8203;:5609&#8203;:5
>     \#2 0xa4837d in Perl\_sv\_vcatpvfn\_flags /root/fuzz\_perl/perl/sv\.c&#8203;:11931
>     \#3 0xa2ab53 in Perl\_sv\_vsetpvfn /root/fuzz\_perl/perl/sv\.c&#8203;:10987&#8203;:5
>     \#4 0xa2ab53 in Perl\_vnewSVpvf /root/fuzz\_perl/perl/sv\.c&#8203;:9592
>     \#5 0xd58d1b in PerlIO\_vprintf /root/fuzz\_perl/perl/perlio\.c&#8203;:5006&#8203;:10
>     \#6 0x7247cd in Perl\_re\_printf /root/fuzz\_perl/perl/regcomp\.c&#8203;:1041&#8203;:14
>     \#7 0x7dee0f in S\_make\_trie /root/fuzz\_perl/perl/regcomp\.c&#8203;:3515&#8203;:29

I've fixed this with the commit below\. It's not a security issue\, as the
buffer overrun only occurs when the regex engine is printing debugging
info at high levels of debugging\.

commit 1d84a25665013f389ffc6fad7dd133f1c6287a08
Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
AuthorDate&#8203;: Tue Aug 6 14&#8203;:36&#8203;:45 2019 \+0100
Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
CommitDate&#8203;: Tue Aug 6 14&#8203;:40&#8203;:52 2019 \+0100

&nbsp;    include a trailing \\0 in SVs holding trie info
&nbsp;    
&nbsp;    RT \#13427
&nbsp;    
&nbsp;    TRIE\_STORE\_REVCHAR\(\) was creating SvPV\(\)s with no trailing '\\0'\. This
&nbsp;    doesn't really matter given the specialised use these are put to\, but
&nbsp;    it upset valgrind et al when perl was run with \-Drv which printf\("%s"\)'s
&nbsp;    the contents of the string\.


\-\- 
I thought I was wrong once\, but I was mistaken\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'pending release'
