### ISSUE TITLE
heap-buffer-overflow (pad.c:1760:10) in Perl_pad_free

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#17090]
Migrated from [rt.perl.org#134277](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134277) (status was 'open')

Searchable as RT134277$

**Comment by p5pRT** [comment]
### From imdb95@gmail.com

Hello\,
I found this bug when fuzzing perl5\.

\*\*\*\*\*\*\*\*\*\*Compilation and environment\*\*\*\*\*\*\*\*\*\*
root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# \./perl/perl \-v

This is perl 5\, version 31\, subversion 2 \(v5\.31\.2 \(v5\.31\.1\-6\-g9649a81\)\)
built for x86\_64\-linux

Copyright 1987\-2019\, Larry Wall

Perl may be copied only under the terms of either the Artistic License or
the
GNU General Public License\, which may be found in the Perl 5 source kit\.

Complete documentation for Perl\, including FAQ lists\, should be found on
this system using "man perl" or "perldoc perl"\.  If you have access to the
Internet\, point your browser at http&#8203;://www\.perl\.org/\, the Perl Home Page\.


---
root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# uname \-a
Linux instance\-2 4\.15\.0\-1036\-gcp \#38~16\.04\.1\-Ubuntu SMP Tue Jun 25 15&#8203;:30&#8203;:46
UTC 2019 x86\_64 x86\_64 x86\_64 GNU/Linux


---
root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# lsb\_release \-r
Release&#8203;:        16\.04


---
Compilation&#8203;:
AFL\_USE\_ASAN=1 \./Configure \-des \-Dusedevel \-DDEBUGGING \-Dcc=afl\-clang\-fast
\-Doptimize=\-g && AFL\_USE\_ASAN=1 make

\*\*\*\*\*\*\*\*\*\*Reproduce\*\*\*\*\*\*\*\*\*
root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# cat test\.pl
'' =~ /$\{sub\{B\{\]\]\]\{;\_\{s\}\}\}\}\}@&#8203;0@&#8203;0/;
root@&#8203;instance\-2&#8203;:\~/fuzz\_perl\# \./perl/perl test\.pl
=================================================================
==16982==ERROR&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow on address
0x603000000330 at pc 0x000000716afd bp 0x7ffcae156b40 sp 0x7ffcae156b38
READ of size 8 at 0x603000000330 thread T0
&nbsp;    \#0 0x716afc in Perl\_pad\_free /root/fuzz\_perl/perl/pad\.c&#8203;:1760&#8203;:10
&nbsp;    \#1 0x511363 in Perl\_op\_clear /root/fuzz\_perl/perl/op\.c&#8203;:1251&#8203;:2
&nbsp;    \#2 0x50e165 in Perl\_op\_free /root/fuzz\_perl/perl/op\.c&#8203;:914&#8203;:9
&nbsp;    \#3 0x6fb753 in Perl\_yyparse /root/fuzz\_perl/perl/perly\.c&#8203;:546&#8203;:17
&nbsp;    \#4 0x5e4235 in S\_parse\_body /root/fuzz\_perl/perl/perl\.c&#8203;:2531&#8203;:9
&nbsp;    \#5 0x5da7d5 in perl\_parse /root/fuzz\_perl/perl/perl\.c&#8203;:1822&#8203;:2
&nbsp;    \#6 0x50a36c in main /root/fuzz\_perl/perl/perlmain\.c&#8203;:126&#8203;:10
&nbsp;    \#7 0x7f5fc044182f in \_\_libc\_start\_main
\(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2082f\)
&nbsp;    \#8 0x4368c8 in \_start \(/root/fuzz\_perl/perl/perl\+0x4368c8\)

0x603000000330 is located 0 bytes to the right of 32\-byte region
\[0x603000000310\,0x603000000330\)
allocated by thread T0 here&#8203;:
&nbsp;    \#0 0x4dd5cc in malloc
/scratch/llvm/clang\-4/xenial/final/llvm\.src/projects/compiler\-rt/lib/asan/asan\_malloc\_linux\.cc&#8203;:66&#8203;:3
&nbsp;    \#1 0x88660e in Perl\_safesysmalloc /root/fuzz\_perl/perl/util\.c&#8203;:155&#8203;:21

SUMMARY&#8203;: AddressSanitizer&#8203;: heap\-buffer\-overflow
/root/fuzz\_perl/perl/pad\.c&#8203;:1760&#8203;:10 in Perl\_pad\_free
Shadow bytes around the buggy address&#8203;:
&nbsp;  0x0c067fff8010&#8203;: 00 02 fa fa 00 00 04 fa fa fa 00 00 04 fa fa fa
&nbsp;  0x0c067fff8020&#8203;: 00 00 01 fa fa fa 00 00 00 01 fa fa 00 00 05 fa
&nbsp;  0x0c067fff8030&#8203;: fa fa 00 00 00 00 fa fa fd fd fd fd fa fa 00 00
&nbsp;  0x0c067fff8040&#8203;: 00 03 fa fa 00 00 00 00 fa fa 00 00 00 05 fa fa
&nbsp;  0x0c067fff8050&#8203;: 00 00 00 00 fa fa 00 00 00 00 fa fa 00 00 00 fa
=>0x0c067fff8060&#8203;: fa fa 00 00 00 00\[fa\]fa 00 00 00 00 fa fa 00 00
&nbsp;  0x0c067fff8070&#8203;: 00 00 fa fa fd fd fd fd fa fa fd fd fd fd fa fa
&nbsp;  0x0c067fff8080&#8203;: fd fd fd fd fa fa 00 00 00 00 fa fa fd fd fd fd
&nbsp;  0x0c067fff8090&#8203;: fa fa 00 00 00 00 fa fa 00 00 00 00 fa fa 00 00
&nbsp;  0x0c067fff80a0&#8203;: 00 00 fa fa 00 00 00 00 fa fa 00 00 00 00 fa fa
&nbsp;  0x0c067fff80b0&#8203;: 00 00 00 00 fa fa 00 00 00 00 fa fa 00 00 07 fa
Shadow byte legend \(one shadow byte represents 8 application bytes\)&#8203;:
&nbsp;  Addressable&#8203;:           00
&nbsp;  Partially addressable&#8203;: 01 02 03 04 05 06 07
&nbsp;  Heap left redzone&#8203;:       fa
&nbsp;  Freed heap region&#8203;:       fd
&nbsp;  Stack left redzone&#8203;:      f1
&nbsp;  Stack mid redzone&#8203;:       f2
&nbsp;  Stack right redzone&#8203;:     f3
&nbsp;  Stack after return&#8203;:      f5
&nbsp;  Stack use after scope&#8203;:   f8
&nbsp;  Global redzone&#8203;:          f9
&nbsp;  Global init order&#8203;:       f6
&nbsp;  Poisoned by user&#8203;:        f7
&nbsp;  Container overflow&#8203;:      fc
&nbsp;  Array cookie&#8203;:            ac
&nbsp;  Intra object redzone&#8203;:    bb
&nbsp;  ASan internal&#8203;:           fe
&nbsp;  Left alloca redzone&#8203;:     ca
&nbsp;  Right alloca redzone&#8203;:    cb
==16982==ABORTING

Please confirm the bug\. Crash also happens with default version v5\.22\.1 of
perl on Ubuntu\.

Thanks\,
Manh Nguyen

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, Jul 09\, 2019 at 02&#8203;:25&#8203;:57AM \-0700\, Nguyen Duc Manh wrote&#8203;:
> '' =~ /$\{sub\{B\{\]\]\]\{;\_\{s\}\}\}\}\}@&#8203;0@&#8203;0/;

This is feeding code containing a syntax error into the parser\.
Again\, not a security issue\.

\-\- 
"Emacs isn't a bad OS once you get used to it\.
It just lacks a decent editor\."

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue\, 09 Jul 2019 03&#8203;:20&#8203;:27 \-0700\, davem wrote&#8203;:
> On Tue\, Jul 09\, 2019 at 02&#8203;:25&#8203;:57AM \-0700\, Nguyen Duc Manh wrote&#8203;:
> > '' =~ /$\{sub\{B\{\]\]\]\{;\_\{s\}\}\}\}\}@&#8203;0@&#8203;0/;
> 
> This is feeding code containing a syntax error into the parser\.
> Again\, not a security issue\.
> 

Now public\.

Tony

**Comment by tonycoz** [comment]
I haven't been able to reproduce this at the specified commit using afl from git:
```
$ ./Configure -des -Dusedevel -DDEBUGGING -Doptimize=-g -Dcc=/home/tony/local/afl-git/bin/afl-clang && AFL_USE_ASAN=1 make perl
...
$ ./perl ../17090.pl
syntax error at ../17090.pl line 1, near "{]"
syntax error at ../17090.pl line 1, near "=~ /${sub{B{]]]{;_{s}}}}}@​0@​0/"
Execution of ../17090.pl aborted due to compilation errors.
$ git describe
v5.31.1-6-g9649a8179c
```

**Comment by dur-randir** [comment]
It's again html escapes from the converter, proper one is (i've tried to paste code here, but it doesn't work when copied, even when guarded by triple backticks) found in the original report - i've got heap-buffer-overflow diagnostics from it on blead.

**Comment by tonycoz** [comment]
I think the issue was the import process from RT added zero-width spaces after the two @ signs, I can now reproduce it.  Let me try pasting it, based on the original message to the list>:

```
'' =~ /${sub{B{]]]{;_{s}}}}}@0@0/;
```

Copying that from the preview reproduced it.

**Comment by tonycoz** [comment]
What's happening here is roughly the following sequence:

1. parsing starts, and PL_curpad/PL_comppad is the pad for the main program, some parsing is done leaving symbols on the shift-reduce stack (this is fine)
2. a subparse is started, and a new PL_curpad/PL_comppad is created
3. some tokens are parsed and more symbols pushed onto the shift-reduce stack, including an OP with an op_targ.
4. parsing fails in the subparse and sublex_done() calls yyquit() which croaks.
5. scopes are re-wound, resetting PL_curpad/PL_comppad to the main program pad
6. due to the error, yyparse() cleans up the shift-reduce stack, including calling op_free() on any ops
7. pad_free() frees the targs allocated on the nested pad from the main program pad, including an entry from beyond the end of the main program pad, which causes the ASAN error.

A kind of a fix would be for sublex_done() to pop the parser stack to where it started from before calling yyquit() but this won't help in the cases where the compilation croaks due to other errors (eg. more than 10 errors.)

I expect the only real fix is start a new parse for a sublex rather than re-using the current parser, as has been suggested before.

**Comment by iabyn** [comment]
On Wed, Apr 22, 2020 at 01:36:15AM +0000, Tony Cook wrote:
> A kind of a fix would be for sublex_done() to pop the parser stack to
> where it started from before calling yyquit() but this won't help in the
> cases where the compilation croaks due to other errors (eg. more than 10
> errors.)

My desire is that compiling should abort on the first encountered parse
error, rather than trying (badly) to continue. The current behaviour
has thrown up many hard-to-fix crashes under fuzzing.

We would still allow multiple semantic errors to accumulate; e.g.

    use strict; $x=1; $y=2;

would still output two 'Global symbol "$foo" requires explicit package name'
errors.



-- 
Art is anything that has a label (especially if the label is "untitled 1")
