### ISSUE TITLE
Memory leak in Perl_utf8_length

### ISSUE THREAD

**Issue by lightsey** [Perl/perl5#17366]
**Description**

This issue was originally reported to the Perl security team by Sergey Aleynikov as SEC-128. The Perl security team does not consider this issue to represent a vulnerability.

The bug is a 1 byte read overflow introduced by this commit between 5.18 and 5.20:
```
b24b43f7631ee39f0260fc7bba01dd65715f5aff is the first bad commit
commit b24b43f7631ee39f0260fc7bba01dd65715f5aff
Author: Karl Williamson <public@khwilliamson.com>
Date:   Mon Jan 6 13:41:46 2014 -0700

    IDStart and IDCont no longer go out to disk

    These are the base names for various macros used in parsing identifiers.
    Prior to this patch, parsing a code point above Latin1 caused loading
    disk files.  This patch causes all the information to be compiled into
    the Perl binary.
```

The overflow behavior causes no user visible bug. It is only evident when Perl is compiled with address sanitizer.

**Steps to Reproduce**

```
$ ./perl -e 'eval "\400=m!(?:0)(?0)|0\x{d0}0(?|x|x)(?0)!"'
=================================================================
==25571==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xf470204c at pc 0x57b69212 bp 0xffc57a78 sp 0xffc57a6c
READ of size 1 at 0xf470204c thread T0
    #0 0x57b69211 in Perl_utf8_length /home/jd/src/git/lab/perl5/utf8.c:2346
    #1 0x573257fc in S_study_chunk /home/jd/src/git/lab/perl5/regcomp.c:5221
    #2 0x5734ae81 in S_study_chunk /home/jd/src/git/lab/perl5/regcomp.c:6320
    #3 0x57322ef5 in S_study_chunk /home/jd/src/git/lab/perl5/regcomp.c:4670
    #4 0x5740f84d in Perl_re_op_compile /home/jd/src/git/lab/perl5/regcomp.c:8227
    #5 0x56f84f24 in Perl_pmruntime /home/jd/src/git/lab/perl5/op.c:8166
    #6 0x571d41da in Perl_yyparse /home/jd/src/git/lab/perl5/perly.y:1260
    #7 0x578bf58b in S_doeval_compile /home/jd/src/git/lab/perl5/pp_ctl.c:3540
    #8 0x5795f3cb in Perl_pp_entereval /home/jd/src/git/lab/perl5/pp_ctl.c:4516
    #9 0x57443714 in Perl_runops_debug /home/jd/src/git/lab/perl5/dump.c:2571
    #10 0x56febd78 in S_run_body /home/jd/src/git/lab/perl5/perl.c:2781
    #11 0x56febd78 in perl_run /home/jd/src/git/lab/perl5/perl.c:2709
    #12 0x56d53123 in main /home/jd/src/git/lab/perl5/perlmain.c:127
    #13 0xf7c54b40 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x1ab40)
    #14 0x56d53bf0 in _start (/home/jd/src/git/lab/perl5/perl+0x723bf0)

0xf470204c is located 0 bytes to the right of 108-byte region [0xf4701fe0,0xf470204c)
allocated by thread T0 here:
    #0 0x56e259bc in realloc (/home/jd/src/git/lab/perl5/perl+0x7f59bc)
    #1 0x5748dc2f in Perl_safesysrealloc /home/jd/src/git/lab/perl5/util.c:279
    #2 0x5748dc2f in Perl_safesysrealloc /home/jd/src/git/lab/perl5/util.c:213
```

**Perl configuration**
```
Summary of my perl5 (revision 5 version 31 subversion 7) configuration:
  Commit id: 06d9a3d13e993e5cadfae73035700bd536e31d44
  Platform:
    osname=linux
    osvers=4.19.0-6-amd64
    archname=x86_64-linux
    uname='linux toucan 4.19.0-6-amd64 #1 smp debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING -Dcc=gcc -Accflags=-m32 -O0 -ggdb3 -fsanitize=address -fsanitize=undefined -static-libasan -static-libubsan -Aldflags=-m32 -O0 -ggdb3 -fsanitize=address -fsanitize=undefined -static-libasan -static-libubsan -Alddlflags=-shared -m32 -O0 -ggdb3 -fsanitize=address -fsanitize=undefined -static-libasan -static-libubsan'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=undef
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags ='-m32 -O0 -ggdb3 -fsanitize=address -fsanitize=undefined -static-libasan -static-libubsan -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2 -g'
    cppflags='-m32 -O0 -ggdb3 -fsanitize=address -fsanitize=undefined -static-libasan -static-libubsan -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='8.3.0'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=4
    doublesize=8
    byteorder=1234
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=12
    longdblkind=3
    ivtype='long'
    ivsize=4
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=4
    prototype=define
  Linker and Libraries:
    ld='gcc'
    ldflags =' -m32 -O0 -ggdb3 -fsanitize=address -fsanitize=undefined -static-libasan -static-libubsan -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/gcc/x86_64-linux-gnu/8/include-fixed /usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -lgdbm -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.28.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.28'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags=' -shared -m32 -O0 -ggdb3 -fsanitize=address -fsanitize=undefined -static-libasan -static-libubsan -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl):
  Compile-time options:
    DEBUGGING
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Dec 16 2019 15:06:44
  %ENV:
    PERL5LIB="lib"
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.31.7/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.31.7
    /usr/local/lib/perl5/5.31.7/x86_64-linux
    /usr/local/lib/perl5/5.31.7
```

**Comment by khwilliamson** [comment]
So, since we are not treating old bugs as 5.32 blockers, this 5.20 one shouldn't be?

**Comment by khwilliamson** [comment]
In 5.35.10, ASAN no longer shows an overflow; but does show memory leaks

**Comment by khwilliamson** [comment]
I retested this, and there aren't any leaks when PERL_DESTRUCT_LEVEL=2 under both asan and valgrind
