### ISSUE TITLE
Null pointer deref with wildcard Unicode named sequences

### ISSUE THREAD

**Issue by lightsey** [Perl/perl5#17732]
**Description**
There are odd interactions between extended bracketed character classes and unicode wildcard properties in the regex engine that end up causing null pointer deref segfaults.

The segfaults are directly attributable to the lack of code verifying "current" was assigned a value by regclass() inside handle_regex_sets() here:  https://github.com/Perl/perl5/blob/c3ac3d3a0cd6dfd27ca304bfa677a49ca62fd76d/regcomp.c#L16499

There are likely additional problems with the way single character wildcards are matched, beyond the null pointer deref itself.

**Steps to Reproduce**
Compile blead with clang and ASAN:
```
./Configure -des -Dusedevel -DDEBUGGING=-g -Doptimize=-O0 -Dcc=clang -Accflags="-g -O0 -m32 -fsanitize=address -fno-omit-frame-pointer" -Aldflags="-g -O0 -m32 -fsanitize=address -fno-omit-frame-pointer" -Alddlflags="-shared -g -O0 -m32 -fsanitize=address  -fno-omit-frame-pointer"
```

Works with a two character wildcard match:
```
jd@toucan:~/src/git/lab/perl5 (blead)$ PERL5LIB=lib ./perl -e 'my $re = q<(?[ ![A-Z] + !\p{name=/UP/} ])>; eval { "" =~ /$re/ }; print $@ if $@; print "Done\n";'
The regex_sets feature is experimental in regex; marked by <-- HERE in m/(?[ <-- HERE  ![A-Z] + !\p{name=/UP/} ])/ at -e line 1.
The Unicode property wildcards feature is experimental at -e line 1.
Done
```

Segfaults with a single character wildcard match:
```
jd@toucan:~/src/git/lab/perl5 (blead)$ PERL5LIB=lib ./perl -e 'my $re = q<(?[ ![A-Z] + !\p{name=/U/} ])>; eval { "" =~ /$re/ }; print $@ if $@; print "Done\n";'
The regex_sets feature is experimental in regex; marked by <-- HERE in m/(?[ <-- HERE  ![A-Z] + !\p{name=/U/} ])/ at -e line 1.
The Unicode property wildcards feature is experimental at -e line 1.
The Unicode property wildcards feature is experimental at -e line 1.
The Unicode property wildcards feature is experimental at -e line 1.
AddressSanitizer:DEADLYSIGNAL
=================================================================
==21945==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000 (pc 0x084c8fd1 bp 0xff897ed8 sp 0xff897e90 T0)
==21945==The signal is caused by a READ memory access.
==21945==Hint: address points to the zero page.
    #0 0x84c8fd0 in S__invlist_len /home/jd/src/git/lab/perl5/./invlist_inline.h:57:13
    #1 0x84ccc76 in Perl__invlist_invert /home/jd/src/git/lab/perl5/regcomp.c:10371:9
    #2 0x853754a in S_handle_regex_sets /home/jd/src/git/lab/perl5/regcomp.c:16790:21
    #3 0x8496378 in S_reg /home/jd/src/git/lab/perl5/regcomp.c:12108:24
    #4 0x856ec5e in S_regatom /home/jd/src/git/lab/perl5/regcomp.c:13500:15
    #5 0x85579b7 in S_regpiece /home/jd/src/git/lab/perl5/regcomp.c:12591:11
    #6 0x8527b76 in S_regbranch /home/jd/src/git/lab/perl5/regcomp.c:12511:18
    #7 0x849b79c in S_reg /home/jd/src/git/lab/perl5/regcomp.c:12213:10
    #8 0x8440001 in Perl_re_op_compile /home/jd/src/git/lab/perl5/regcomp.c:7845:9
    #9 0x895b82f in Perl_pp_regcomp /home/jd/src/git/lab/perl5/pp_ctl.c:114:14
    #10 0x87928bf in Perl_runops_standard /home/jd/src/git/lab/perl5/run.c:41:26
    #11 0x825092d in S_run_body /home/jd/src/git/lab/perl5/perl.c:2759:2
    #12 0x824e546 in perl_run /home/jd/src/git/lab/perl5/perl.c:2682:2
    #13 0x8154029 in main /home/jd/src/git/lab/perl5/perlmain.c:127:9
    #14 0xf7b5fb40 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x1ab40)
    #15 0x807fd11 in _start (/home/jd/src/git/lab/perl5/perl+0x807fd11)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/jd/src/git/lab/perl5/./invlist_inline.h:57:13 in S__invlist_len
==21945==ABORTING
```

**Expected behavior**
No segfault

**Perl configuration**
```
Summary of my perl5 (revision 5 version 31 subversion 11) configuration:
  Local Commit: e4d5218bbcc5a37ead7296a5d2e16ed970c004a3
  Ancestor: c3ac3d3a0cd6dfd27ca304bfa677a49ca62fd76d
  Platform:
    osname=linux
    osvers=4.19.0-8-amd64
    archname=x86_64-linux
    uname='linux toucan 4.19.0-8-amd64 #1 smp debian 4.19.98-1 (2020-01-26) x86_64 gnulinux '
    config_args='-des -Dusedevel -DDEBUGGING=-g -Doptimize=-O0 -Dcc=clang -Accflags=-g -O0 -m32 -fsanitize=address -fno-omit-frame-pointer -Aldflags=-g -O0 -m32 -fsanitize=address -fno-omit-frame-pointer -Alddlflags=-shared -g -O0 -m32 -fsanitize=address  -fno-omit-frame-pointer'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=undef
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='clang'
    ccflags ='-g -O0 -m32 -fsanitize=address -fno-omit-frame-pointer -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O0 -g'
    cppflags='-g -O0 -m32 -fsanitize=address -fno-omit-frame-pointer -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Clang 7.0.1 (tags/RELEASE_701/final)'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=4
    doublesize=8
    byteorder=1234
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=12
    longdblkind=3
    ivtype='long'
    ivsize=4
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=4
    prototype=define
  Linker and Libraries:
    ld='clang'
    ldflags =' -g -O0 -m32 -fsanitize=address -fno-omit-frame-pointer -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/llvm-7/lib/clang/7.0.1/lib /usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -lgdbm -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.28.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.28'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags=' -shared -g -O0 -m32 -fsanitize=address -fno-omit-frame-pointer -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Locally applied patches:
    e4d5218bbcc5a37ead7296a5d2e16ed970c004a3
  Built under linux
  Compiled at Apr 20 2020 21:25:59
  %ENV:
    PERL5LIB="lib"
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.31.11/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.31.11
    /usr/local/lib/perl5/5.31.11/x86_64-linux
    /usr/local/lib/perl5/5.31.11
```

**Comment by khwilliamson** [comment]
I changed the title of this ticket because that it was short is a red herring.  The problem occurs when the name matches a Unicode named sequence, which is a multi-char sequence.  A short property name has more chances of hitting a named sequence name.  Longer names also fail should they match a named sequence
