### ISSUE TITLE
SEGV in XS_version_vcmp 

### ISSUE THREAD

**Issue by geeknik** [Perl/perl5#17759]
**Description**
Whilst fuzzing Perl5 built from git commit 089ad2, we encountered this null pointer dereference from the `I'm not sure this is a bug department` mostly because of how little I understand what is happening here:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==9576==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000ab16c0 bp 0x7fffffffe010 sp 0x7fffffffdfe0 T0)
==9576==The signal is caused by a READ memory access.
==9576==Hint: address points to the zero page.
    #0 0xab16bf in XS_version_vcmp /root/perl/./vxs.inc:325:30
    #1 0x84ad3f in Perl_pp_entersub /root/perl/pp_hot.c:5277:2
    #2 0x78dbf0 in Perl_runops_debug /root/perl/dump.c:2571:23
    #3 0x58cb84 in S_run_body /root/perl/perl.c:2759:2
    #4 0x58bf12 in perl_run /root/perl/perl.c:2682:2
    #5 0xb92440 in main /root/perl/miniperlmain.c:133:9
    #6 0x7ffff7c2709a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #7 0x420c89 in _start (/root/perl/miniperl+0x420c89)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /root/perl/./vxs.inc:325:30 in XS_version_vcmp
==9576==ABORTING
```

**Steps to Reproduce**
`sh ./Configure -des -Dusedevel -DDEBUGGING -Dcc=afl-clang-fast && AFL_USE_ASAN=1 make miniperl`
[Wait almost 3 days!](https://i.imgur.com/778VsFs.png)
`./miniperl -e '0^vcmp$^V'`

**Expected behavior**
No crash.

**Comment by dur-randir** [comment]
$^V is just broken in regards to string ops. It used to be maintained separately on CPAN and backported to core, but I won't wish anyone the burden of patching it.

**Comment by haarg** [comment]
I believe this can be fixed by Perl/version.pm#9.

**Comment by jkeenan** [comment]
> I believe this can be fixed by [Perl/version.pm#9](https://github.com/Perl/version.pm/pull/9).

Yes, I manually applied the part of that p.r. pertaining to `vxs.inc` and the segfault cleared.

**Comment by Grinnz** [comment]
Does anyone know the maintenance status of version.pm? The maintainer has expressed his wish to give up maintainership, and P5P currently holds first-come on CPAN, but as far as I know no changes have been made to the distribution since. Should it now be considered blead-first? Should PTG take over maintenance and remain cpan-first?

**Comment by Leont** [comment]
> Does anyone know the maintenance status of version.pm?

That appears not well-defined, but I'm willing to adopt it.

> Should it now be considered blead-first? Should PTG take over maintenance and remain cpan-first?

It's really the one module that's both, that does make this less obvious.

**Comment by khwilliamson** [comment]
On 5/1/20 9:30 AM, Leon Timmermans wrote:
>     Does anyone know the maintenance status of version.pm?
> 
> That appears not well-defined, but I'm willing to adopt it.
> 
>     Should it now be considered blead-first? Should PTG take over
>     maintenance and remain cpan-first?
> 
> It's really the one module that's both, that does make this trickier. 
> I'm willing to adopt it either way.
> 

leont++

**Comment by dur-randir** [comment]
Here's another one
```
perl -e '-1E80<$^V'
```

**Comment by Grinnz** [comment]
It seems to me like EUMM is in a similar role, and is still currently cpan-first. Leaving it cpan first would have the advantage of being able to keep using the current repo's pull requests as is. I think it only matters what way @Leont thinks would be easier to maintain because I doubt many developers of either group will touch it much.

**Comment by Leont** [comment]
> That appears not well-defined, but I'm willing to adopt it.

@xsawyerx if you agree with the above, can you give me the appropriate permissions?

**Comment by xsawyerx** [comment]
> > That appears not well-defined, but I'm willing to adopt it.
> 
> @xsawyerx if you agree with the above, can you give me the appropriate permissions?

Improved my notification system so I caught this now.

I agree and I will be providing you with the permissions momentarily.

**Comment by xsawyerx** [comment]
```
Added LEONT to co-maintainers of version.
Added LEONT to co-maintainers of version::regex.
Added LEONT to co-maintainers of version::vpp.
Added LEONT to co-maintainers of version::vxs.
```

**Comment by Leont** [comment]
@xsawyerx I also need right on the [repository](https://github.com/Perl/version.pm)

**Comment by xsawyerx** [comment]
> @xsawyerx I also need right on the [repository](https://github.com/Perl/version.pm)

Done.
