### ISSUE TITLE
panic() function in core

### ISSUE THREAD

**Issue by xsawyerx** [Perl/perl5#17802]
Quoting @dur-randir from #17747:

> I think that the route forward should be at least to introduce an actual panic() function into core, that terminates program regardless on compilation flags - since the interpreter has encountered an inconsistency in it's internal state.

**Comment by demerphq** [comment]
On Sun, 24 May 2020 at 00:09, Sawyer X <notifications@github.com> wrote:

> Quoting @dur-randir <https://github.com/dur-randir> from #17747
> <https://github.com/Perl/perl5/pull/17747>:
>
> I think that the route forward should be at least to introduce an actual
> panic() function into core, that terminates program regardless on
> compilation flags - since the interpreter has encountered an inconsistency
> in it's internal state.
>
> I guess this is bike-shedding, but because this is intended to handle
cases of inconsistent state, I think we should say that in the function
name. I can easily imagine someone converting a current panic message that
does not involve an inconsistent state into a panic() call and then being
surprised it broke sombodies "but it works" code. Any of

panic_untrappable()
panic_inconsistent_state()
panic_unrecoverable()

whatever, seem better than plain panic() in our current code state. If we
had done it from the beginning panic() might have made more sense but it
feels wrong to add now.

cheers,
Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by khwilliamson** [comment]
I'm having trouble visualizing something in the core croaking with the message containing 'panic', and it somehow being recoverable.  Does someone have an example?

**Comment by leonerd** [comment]
Coming back to look at this, I think this would be very handy indeed.

As things currently stand, any core panic is just a croak; e.g. the one I'm currently debugging:

```c
./util.c:377:                Perl_croak_nocontext("panic: free from wrong pool, %p!=%p",
...
```

That means that even on `-DDEBUGGING` builds there's nothing useful for gdb to see:

```
$ gdb --args ./perl -Ilib t/class/threads.t 
...
(gdb) run
...
panic: free from wrong pool, 555555cb7b70!=555555c7b2a0 at t/class/threads.t line 32.
Scalars leaked: 1
[Inferior 1 (process 2703947) exited with code 02]
(gdb) bt
No stack.
```

As compared, if an `assert()` fails this aborts the process with a `SIGABRT` whose entire purpose is to leave the stack trace somewhere nicely visible that gdb can see.

If core perl had a panic() function then under debugging it would be built to use SIGABRT in the same way, and thus be far more useful.

**Comment by leonerd** [comment]
As a one-off to help me debug my particular bug currently, I applied this:

```
diff --git a/util.c b/util.c
index 8590b3a4bc..50ea15d686 100644
--- a/util.c
+++ b/util.c
@@ -374,6 +374,11 @@ Perl_safesysfree(Malloc_t where)
 # endif
 # ifdef PERL_TRACK_MEMPOOL
             if (header->interpreter != aTHX) {
+#ifdef DEBUGGING
+                Perl_warn_nocontext("panic: free from wrong pool, %p!=%p",
+                        header->interpreter, aTHX);
+                raise(SIGABRT);
+#endif
                 Perl_croak_nocontext("panic: free from wrong pool, %p!=%p",
                                      header->interpreter, aTHX);
             }

```

which has the upshot that gdb can now see a backtrace:

```
ok 1 - Returned from dummy thread
panic: free from wrong pool, 555555cb7b30!=555555c7b2a0 at t/class/threads.t line 32.

Thread 1 "perl" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
    at ./nptl/pthread_kill.c:44
#1  0x00007ffff7d2bd2f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff7cdcef2 in __GI_raise (sig=6) at ../sysdeps/posix/raise.c:26
#3  0x00005555557a2e4b in Perl_safesysfree (where=0x555555f55fb8) at util.c:380
#4  0x0000555555867c0e in Perl_sv_clear (my_perl=0x555555c7b2a0, orig_sv=0x555555e46690) at sv.c:6903
#5  0x00005555558699e5 in Perl_sv_free2 (my_perl=0x555555c7b2a0, sv=0x555555e46690, rc=1) at sv.c:7228
#6  0x00005555558d64b3 in Perl_SvREFCNT_dec_NN (my_perl=0x555555c7b2a0, sv=0x555555e46690) at sv_inline.h:703
#7  0x00005555558d725a in Perl_free_tmps (my_perl=0x555555c7b2a0) at scope.c:236
#8  0x0000555555802f67 in Perl_pp_nextstate (my_perl=0x555555c7b2a0) at pp_hot.c:53
#9  0x000055555579f075 in Perl_runops_debug (my_perl=0x555555c7b2a0) at dump.c:2854
#10 0x00005555555ebdd1 in S_run_body (my_perl=0x555555c7b2a0, oldscope=1) at perl.c:2807
#11 0x00005555555eb036 in perl_run (my_perl=0x555555c7b2a0) at perl.c:2722
#12 0x000055555559a2e4 in main (argc=3, argv=0x7fffffffde58, env=0x7fffffffde78) at perlmain.c:127
```

I think some approach like that used as standard throughout would be far better than the current situation.
```
