### ISSUE TITLE
signed integer overflow in S_study_chunk

### ISSUE THREAD

**Issue by lightsey** [Perl/perl5#17847]
**Description**
This bug was originally submitted to the Perl security team by Brian Carpenter in July of 2019.

It does not meet the criteria the security team is using to distinguish vulnerabilities from bugs in the Perl regular expression engine.

The problem is a signed integer overflow visible to UBSAN on 32bit builds in S_study_chunk that wraps around several times in a way that tends to cancel itself out.

@hvds proposed a fix for the problem in the security team's issue tracker. I will sync those patches against blead, update the issue ID in the commit messages and submit them in a pull request.

**Steps to Reproduce**
```
jd@toucan:~/src/git/lab/perl5 (blead)$ export UBSAN_OPTIONS='print_stacktrace=1'; ./perl -e '/0+0+ss0?/i'
regcomp.c:5850:123: runtime error: signed integer overflow: 2147483647 - -2147483648 cannot be represented in type 'int'
    #0 0x84eaac4 in S_study_chunk /home/jd/src/git/lab/perl5/regcomp.c:5850:123
    #1 0x8475b10 in Perl_re_op_compile /home/jd/src/git/lab/perl5/regcomp.c:8243:11
    #2 0x81807ed in Perl_pmruntime /home/jd/src/git/lab/perl5/op.c:8375:6
    #3 0x842be50 in Perl_yyparse /home/jd/src/git/lab/perl5/perly.y:1293:23
    #4 0x82651d8 in S_parse_body /home/jd/src/git/lab/perl5/perl.c:2576:9
    #5 0x825adb1 in perl_parse /home/jd/src/git/lab/perl5/perl.c:1871:2
    #6 0x8151d34 in main /home/jd/src/git/lab/perl5/perlmain.c:126:10
    #7 0xf7c38b40 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x1ab40)
    #8 0x807dc91 in _start (/home/jd/src/git/lab/perl5/perl+0x807dc91)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior regcomp.c:5850:123 in 
```

**Perl configuration**
```
Summary of my perl5 (revision 5 version 32 subversion 0) configuration:
  Commit id: 41aa777b4de447bc68637ff0f3fe1575e1af76d4
  Platform:
    osname=linux
    osvers=4.19.0-9-amd64
    archname=x86_64-linux
    uname='linux toucan 4.19.0-9-amd64 #1 smp debian 4.19.118-2 (2020-04-29) x86_64 gnulinux '
    config_args='-des -Dusedevel -Dcc=clang -Accflags=-O3 -m32 -g -fsanitize=address -fsanitize=undefined -fsanitize-recover=undefined -fno-omit-frame-pointer -Aldflags=-m32 -g -fsanitize=address -fsanitize=undefined -fsanitize-recover=undefined -fno-omit-frame-pointer -Alddlflags=-shared -m32 -g -fsanitize=address -fsanitize=undefined -fsanitize-recover=undefined -fno-omit-frame-pointer'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=undef
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='clang'
    ccflags ='-O3 -m32 -g -fsanitize=address -fsanitize=undefined -fsanitize-recover=undefined -fno-omit-frame-pointer -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-O3 -m32 -g -fsanitize=address -fsanitize=undefined -fsanitize-recover=undefined -fno-omit-frame-pointer -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Clang 7.0.1 (tags/RELEASE_701/final)'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=4
    doublesize=8
    byteorder=1234
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=12
    longdblkind=3
    ivtype='long'
    ivsize=4
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=4
    prototype=define
  Linker and Libraries:
    ld='clang'
    ldflags =' -m32 -g -fsanitize=address -fsanitize=undefined -fsanitize-recover=undefined -fno-omit-frame-pointer -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/llvm-7/lib/clang/7.0.1/lib /usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -lgdbm -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.28.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.28'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags=' -shared -m32 -g -fsanitize=address -fsanitize=undefined -fsanitize-recover=undefined -fno-omit-frame-pointer -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Jun  7 2020 21:51:03
  %ENV:
    PERL5LIB="lib"
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.32.0/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.32.0
    /usr/local/lib/perl5/5.32.0/x86_64-linux
    /usr/local/lib/perl5/5.32.0
```

**Comment by khwilliamson** [comment]
#17848 referenced this more recently

**Comment by jkeenan** [comment]
@lightsey, can you give us an update on the status of this ticket?

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> @lightsey, can you give us an update on the status of this ticket?
> 
> Thank you very much.
> Jim Keenan

@lightsey ^^

**Comment by hvds** [comment]
This ticket has rather languished. I recommend that after 5.34 release we merge the gh17847 branch; I've refreshed it up to blead as partial preparation.

**Comment by hvds** [comment]
I've rebased against latest blead and opened #18810.

**Comment by hvds** [comment]
PR #18810 has been merged, so this issue should now be resolved. Closing.
