### ISSUE TITLE
oneliner that sigsegv (5.6)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#1848]
Migrated from [rt.perl.org#3111](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=3111) (status was 'resolved')

Searchable as RT3111$

**Comment by p5pRT** [comment]
### From pixel@mandrakesoft.com

#### Created by pixel@kenobi.mandrakesoft.com



% perl \-ne 'eval "next"' /etc/passwd

that's the shortest i've found\! Don't ask to try to understand why ;\-\(

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.6.0:

Configured by pixel at Fri Mar 31 16:32:49 CEST 2000.

Summary of my perl5 (revision 5.0 version 6 subversion 0) configuration:
  Platform:
    osname=linux, osvers=2.2.15-0.16mdksmp, archname=i386-linux
    uname='linux kenobi.mandrakesoft.com 2.2.15-0.16mdksmp #1 smp mon mar 13 16:40:10 cet 2000 i686 unknown '
    config_args='-des -Dprefix=/usr -Darchname=i386-linux -Dd_dosuid -Dd_semctl_semun -Di_db -Di_ndbm -Di_gdbm -Ud_csh -Dman3dir=/usr/lib/perl5/man/man3 -Doptimize=-O3 -fomit-frame-pointer -fno-exceptions -fno-rtti -pipe -s -mpentium -mcpu=pentium -march=pentium -ffast-math -fexpensive-optimizations'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define 
    use64bitint=undef use64bitall=undef uselongdouble=undef usesocks=undef
  Compiler:
    cc='cc', optimize='-O3 -fomit-frame-pointer -fno-exceptions -fno-rtti -pipe -s -mpentium -mcpu=pentium -march=pentium -ffast-math -fexpensive-optimizations', gccversion=2.95.3 19991030 (prerelease)
    cppflags='-fno-strict-aliasing'
    ccflags ='-fno-strict-aliasing -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    stdchar='char', d_stdstdio=define, usevfork=false
    intsize=4, longsize=4, ptrsize=4, doublesize=8
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -ldl -lm -lc -lposix -lcrypt
    libc=/lib/libc-2.1.3.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.0:
    /home/pixel/etc/perl/i386-linux
    /home/pixel/etc/perl
    /home/pixel/etc/perl/i386-linux
    /home/pixel/etc/perl/site_perl
    /usr/lib/perl5/5.6.0/i386-linux
    /usr/lib/perl5/5.6.0
    /usr/lib/perl5/site_perl/5.6.0/i386-linux
    /usr/lib/perl5/site_perl/5.6.0
    /usr/lib/perl5/site_perl/5.005/i386-linux
    /usr/lib/perl5/site_perl/5.005
    /usr/lib/perl5/site_perl
    .


Environment for perl v5.6.0:
    HOME=/home/pixel
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH=/home/pixel/lib/i386
    LOGDIR (unset)
    PATH=/home/pixel/bin:/home/pixel/bin/oneliner:/home/pixel/bin/perl:/home/pixel/bin/python:/home/pixel/bin/tcl:/home/pixel/bin/i386:/usr/freeware/bin:/usr/etc:/usr/local/bin:/usr/X11R6/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/home/pixel/bin
    PERL5LIB=/home/pixel/etc/perl:/home/pixel/etc/perl/i386-linux:/home/pixel/etc/perl/site_perl
    PERL_BADLANG (unset)
    SHELL=/bin/zsh


```
</details>

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Pixel \(lists\.p5p\)&#8203;:
>% perl \-ne 'eval "next"' /etc/passwd
>that's the shortest i've found\!

Congratulations\, of sorts\.

>Don't ask to try to understand why ;\-\(

GCC optimisations\. The minute you turn on debugging\, it goes away\.
Fun\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

At 10&#8203;:29 \+0000 2000\-04\-17\, Simon Cozens wrote&#8203;:
>GCC optimisations\. The minute you turn on debugging\, it goes away\.

Careful\!  Turning on debugging also makes perl's malloc\(\) more 
conservative\.  It may be that that's hiding the symptoms\.  See the 
comments at the head of malloc\.c for documentation\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

simon@&#8203;brecon\.co\.uk \(Simon Cozens\) wrote&#8203;:
> Pixel \(lists\.p5p\)&#8203;:
> >% perl \-ne 'eval "next"' /etc/passwd
> >that's the shortest i've found\!
> 
> Congratulations\, of sorts\.
> 
> >Don't ask to try to understand why ;\-\(
> 
> GCC optimisations\. The minute you turn on debugging\, it goes away\.
> Fun\.

Nope\.  I got it with \-O0\.

A COP structure is trashed in free\(\)\.\.\.

&nbsp;    \(gdb\) c
&nbsp;    Continuing\.
&nbsp;    Hardware watchpoint 2&#8203;: \*135546880

&nbsp;    Old value = 0
&nbsp;    New value = 56
&nbsp;    0x400e0b8a in free \(\) from /lib/libc\.so\.6
&nbsp;    \(gdb\) p/x 135546880
&nbsp;    $5 = 0x8144800
&nbsp;    \(gdb\) bt
&nbsp;    \#0  0x400e0b8a in free \(\) from /lib/libc\.so\.6
&nbsp;    \#1  0x400e09ed in free \(\) from /lib/libc\.so\.6
&nbsp;    \#2  0x80a669d in Perl\_safefree \(where=0x81447d0\) at util\.c&#8203;:163
&nbsp;    \#3  0x8087dba in Perl\_op\_free \(o=0x81447d0\) at op\.c&#8203;:738
&nbsp;    \#4  0x8087d4c in Perl\_op\_free \(o=0x8144808\) at op\.c&#8203;:719
&nbsp;    \#5  0x8087d4c in Perl\_op\_free \(o=0x8144830\) at op\.c&#8203;:719
&nbsp;    \#6  0x80e83cd in Perl\_leave\_scope \(base=6\) at scope\.c&#8203;:815
&nbsp;    \#7  0x80f062d in Perl\_pp\_next \(\) at pp\_ctl\.c&#8203;:2002
&nbsp;    \#8  0x80b9202 in Perl\_runops\_standard \(\) at run\.c&#8203;:25
&nbsp;    \#9  0x805e8d7 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1401
&nbsp;    \#10 0x805e4de in perl\_run \(my\_perl=0x813a920\) at perl\.c&#8203;:1325
&nbsp;    \#11 0x805aa9e in main \(argc=4\, argv=0xbffffc14\, env=0xbffffc28\)
&nbsp;    at perlmain\.c&#8203;:52
&nbsp;    \(gdb\) p/x &PL\_curcop\->cop\_warnings
&nbsp;    $6 = 0x8144800
&nbsp;    \(gdb\) 

\.\.\.leading to \.\.\.

&nbsp;    Continuing\.
&nbsp;    Hardware watchpoint 2&#8203;: \*135546880

&nbsp;    Old value = 56
&nbsp;    New value = 88
&nbsp;    0x400e0b8a in free \(\) from /lib/libc\.so\.6
&nbsp;    \(gdb\) 
&nbsp;    Continuing\.

&nbsp;    Program received signal SIGSEGV\, Segmentation fault\.
&nbsp;    0x80bd8b5 in Perl\_do\_readline \(\) at pp\_hot\.c&#8203;:1330
&nbsp;    \(gdb\) bt
&nbsp;    \#0  0x80bd8b5 in Perl\_do\_readline \(\) at pp\_hot\.c&#8203;:1330
&nbsp;    \#1  0x80ba1c4 in Perl\_pp\_readline \(\) at pp\_hot\.c&#8203;:228
&nbsp;    \#2  0x80b9202 in Perl\_runops\_standard \(\) at run\.c&#8203;:25
&nbsp;    \#3  0x805e8d7 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1401
&nbsp;    \#4  0x805e4de in perl\_run \(my\_perl=0x813a920\) at perl\.c&#8203;:1325
&nbsp;    \#5  0x805aa9e in main \(argc=4\, argv=0xbffffc14\, env=0xbffffc28\)
&nbsp;    at perlmain\.c&#8203;:52
&nbsp;    \(gdb\) 
&nbsp;    p \*PL\_curcop
&nbsp;    $7 = \{op\_next = 0x40167878\, op\_sibling = 0x40167878\, 
&nbsp;      op\_ppaddr = 0x80b92f4 \<Perl\_pp\_nextstate>\, op\_targ = 0\, op\_type = 174\, 
&nbsp;      op\_seq = 16\, op\_flags = 0 '\\000'\, op\_private = 0 '\\000'\, 
&nbsp;      cop\_label = 0x0\, cop\_stash = 0x813a9a8\, cop\_filegv = 0x813ab28\, 
&nbsp;      cop\_seq = 2\, cop\_arybase = 0\, cop\_line = 2\, cop\_warnings = 0x58\}
&nbsp;    \(gdb\) 

What's the recommended procedure for debugging malloc in perl these
days\, anyway?

**Comment by p5pRT** [comment]
### From @ask


Does this still happen with 5\.6\.1 or 5\.8\.0?

**Comment by p5pRT** [comment]
### From @rspier

chromatic say&#8203;:
> Bug \#3111 could not be reproduced with Perl 5\.6\.1 or 5\.8\.0 on Mandrake 
> Linux\.

**Comment by p5pRT** [comment]
@rspier - Status changed from 'open' to 'resolved'
