### ISSUE TITLE
[Win32] perl-5.34.0-RC1 crashes in t/op/write.t (quadmath build only)

### ISSUE THREAD

**Issue by sisyphus** [Perl/perl5#18768]
**Description**

As per the subject line, the first 18 tests pass, followed by a crash.
This didn't happen in 5.33.9 or earlier, and a <code>diff -u</code> indicates that write.t has not changed.
I've hit the issue using a mingw64 port of 64-bit gcc-10.2.0. (I'm nor sure whether 32-bit quadmath builds are also affected, and I'll also build with gcc-8.3.0. I'll update on all of that as the info becomes available.)
The "double" and "long double" builds of RC1 that I've already done were unaffected by this.
The crash occurs when the following line of code (line 476 ) in write.t is executed:
<code>eval { write(OUT18); };</code>
I think this must actually be test 19, because "ok 18" has been printed out immediately before the crash.
No other test scripts are failing.
**Steps to Reproduce**

.\perl -I.\lib t/op/write.t
**Expected behavior**

**Perl configuration**

```
Summary of my perl5 (revision 5 version 34 subversion 0) configuration:
   
  Platform:
    osname=MSWin32
    osvers=6.1.7601
    archname=MSWin32-x64-multi-thread-quadmath
    uname=''
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='gcc'
    ccflags =' -DWIN32 -DWIN64 -fdiagnostics-color=never -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -D__USE_MINGW_ANSI_STDIO -fwrapv -fno-strict-aliasing -mms-bitfields'
    optimize='-s -O2'
    cppflags='-DWIN32'
    ccversion=''
    gccversion='10.2.0'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long long'
    ivsize=8
    nvtype='__float128'
    nvsize=16
    Off_t='long long'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags ='-s -L"C:\perl-5.34.0-1020\lib\MSWin32-x64-multi-thread-quadmath\CORE" -L"C:\_64\winlibs-gcc-1020\mingw64\lib" -L"C:\_64\winlibs-gcc-1020\mingw64\x86_64-w64-mingw32\lib" -L"C:\_64\winlibs-gcc-1020\mingw64\lib\gcc\x86_64-w64-mingw32\10.2.0"'
    libpth=C:\_64\winlibs-gcc-1020\mingw64\lib C:\_64\winlibs-gcc-1020\mingw64\x86_64-w64-mingw32\lib C:\_64\winlibs-gcc-1020\mingw64\lib\gcc\x86_64-w64-mingw32\10.2.0 C:\_64\msys_1020\1.0\local\lib
    libs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32 -lquadmath
    perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32 -lquadmath
    libc=
    so=dll
    useshrplib=true
    libperl=libperl534.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-mdll -s -L"C:\perl-5.34.0-1020\lib\MSWin32-x64-multi-thread-quadmath\CORE" -L"C:\_64\winlibs-gcc-1020\mingw64\lib" -L"C:\_64\winlibs-gcc-1020\mingw64\x86_64-w64-mingw32\lib" -L"C:\_64\winlibs-gcc-1020\mingw64\lib\gcc\x86_64-w64-mingw32\10.2.0"'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    HAVE_INTERP_INTERN
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_IMPLICIT_SYS
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_QUADMATH
  Locally applied patches:
    RC1
  Built under MSWin32
  Compiled at May  5 2021 13:05:15
  @INC:
    .\lib
    C:/comp-1020/perl-5.34.0-RC1/lib

```

**Comment by sisyphus** [comment]
It seems to affect only the 64-bit gcc-10.2.0 quadmath build of perl on Windows .... and the problem was actually there in 5.33.9 but, despite what I thought, I hadn't taken the steps needed to expose it.

In a nutshell:
If I build a USE_QUADMATH perl with this 64-bit gcc-10.2.0 compiler, and CCFLAGS includes -fwrapv, then t/op/write.t crashes in perl-5.34.0-RC1 (and also in recent blead).
If any one of those 3 conditions is not met, then there's no problem.

I'm happy to regard this issue as a bug with this particular compiler.
Sorry for the noise.

As regards https://github.com/Perl/perl5/issues/18739 I'm still of the view that forcing the inclusion of -fwrapv in CCFLAGS is the right thing to do.

Can I now close this issue ?

**Comment by sisyphus** [comment]
I grabbed 64-bit mingw64 ports of 10.3.0 and 11.1.0 from the same vendor (http://winlibs.com/), and the same issue with the USE_QUADMATH builds persists.
Each of these 3 compilers that I have (10.2.0, 10.3.0 and 11.1.0) ship with the same version of the mingw64 runtime (8.0.0).
Could the problem lie within that runtime ?

I'll try out https://github.com/brechtsanders/winlibs_mingw/releases/download/10.2.0-7.0.0-r4/winlibs-x86_64-posix-seh-gcc-10.2.0-llvm-10.0.1-mingw-w64-7.0.0-r4.7z tomorrow and see if that makes any difference. (It apparently has version 7.0.0 of the runtime.)

**Comment by xenu** [comment]
I can't reproduce it. I tried building blead with USE_QUADMATH (with and without -fwrapv) using [this](https://github.com/brechtsanders/winlibs_mingw/releases/download/11.1.0-8.0.0-r2/winlibs-i686-posix-dwarf-gcc-11.1.0-mingw-w64-8.0.0-r2.zip) compiler and the test doesn't crash.

**Comment by sisyphus** [comment]
@xenu , you need to use a 64-bit compiler.
For example, I've tested with:
https://github.com/brechtsanders/winlibs_mingw/releases/download/11.1.0-8.0.0-r2/winlibs-x86_64-posix-seh-gcc-11.1.0-llvm-12.0.0-mingw-w64-8.0.0-r2.7z
and the USE_QUADMATH build exhibited the behaviour I've described.
That is, without -fwrapv, all tests pass; with -fwrapv t/op/write.t crashes.

If you don't find the same problem, then I'll have to start looking at the other non-standard things I'm doing - which are defining <code>INST_ARCH</code> and including <code>-fdiagnostics-color=never</code> in CCFLAGS.
I think they're the only "non-standard" things I'm doing, and I don't expect they're part of the problem.
But that would be the next thing that would need to be checked,

**Comment by sisyphus** [comment]
I've just tested with a couple of the other 64-bit compilers from http://winlibs.com/

The 10.2.0 compiler with runtime v7.0.0 suffers the problem. (The 10.2.0 compiler I was initially using, which also suffers the problem, has runtime v8.0.0.)
The 9.3.0 compiler with runtime v7.0.0 does not suffer the problem,
The 7.5.0 compiler with runtime v7.0.0 does not suffer the problem,
I haven't checked the 8.4.0 compiler (runtime v7.0.0).

It looks like the problem begins with their gcc-10.

**Comment by xenu** [comment]
Sorry, I forgot 32-bit compilers are still a thing, so I didn't bother to check the architecture of what I've downloaded :)

With a 64-bit compiler I can indeed reproduce the problem, and it seems it's yet another instance of #17521:
```
gdb: unknown target exception 0xc0000028 at 0x7ffc7e152266

Thread 1 received signal ?, Unknown signal.
0x00007ffc7e152266 in ntdll!RtlRaiseStatus () from C:\WINDOWS\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007ffc7e152266 in ntdll!RtlRaiseStatus () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x00007ffc7e080bb3 in ntdll!RtlUnwindEx () from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0x00007ffc7d982eed in msvcrt!_setjmpex () from C:\WINDOWS\System32\msvcrt.dll
#3  0x00007ffc209fd6ef in Perl_die_unwind (my_perl=my_perl@entry=0x156d9f75008, msv=msv@entry=0x156db8c1d98) at ..\pp_ctl.c:1843
#4  0x00007ffc20a9904c in Perl_vcroak (my_perl=0x156d9f75008, pat=<optimized out>, args=<optimized out>) at ..\util.c:2011
#5  0x00007ffc20a990e2 in Perl_die (my_perl=0x156d9f70000, my_perl@entry=0x156d9f75008, pat=0x50000163 <error: Cannot access memory at address 0x50000163>, pat@entry=0x7ffc20c2ab68 <CSWTCH.1164+1656> <error reading variable>)
    at ..\util.c:1944
#6  0x00007ffc209fbd20 in S_doparseform (sv=0x156db8c2290, my_perl=0x156d9f75008) at ..\pp_ctl.c:5686
#7  Perl_pp_formline (my_perl=0x156d9f75008) at ..\pp_ctl.c:514
#8  0x00007ffc20a8daa6 in Perl_runops_standard (my_perl=0x156d9f75008) at ..\run.c:41
#9  0x00007ffc20a3a68a in S_run_body (oldscope=<optimized out>, my_perl=<optimized out>) at perl.c:2743
#10 perl_run (my_perl=0x156d9f75008) at perl.c:2666
#11 0x00007ffc20aa40e0 in RunPerl (argc=<optimized out>, argv=<optimized out>, env=0x156d9f74d80) at perllib.c:201
#12 0x00007ff78abf1445 in __tmainCRTStartup ()
#13 0x00007ff78abf1146 in mainCRTStartup ()
```

**Comment by sisyphus** [comment]
Thanks @xenu.
The test that triggers the crash in t/op/write.t runs fine when taken out of that file, and run in isolation - so I guess we can be thankful for that, at least.

I'm idly wondering whether a compiler that doesn't use the 'seh' exception handling might avoid this issue. (I don't have such a 64-bit gcc-10 compiler at my disposal.)
Has this type of problem ever come up when gcc uses the 'sjlj' exception handler ?

I was a little surprised that the same issue did not arise when I used the 32-bit gcc-10.2.0 compiler to build RC1 with USE_QUADMATH && USE_64_BIT_INT.
In this case, the nvtype and ivtype are identical to the nvtype and ivtype of the 64-bit build.
One notable difference between the 64-bit and 32-bit environments is that the 32-bit compiler uses 'dwarf2' (not 'seh') exception handling.
But I guess there's probably other differences between the two environments that could also be relevant to this issue.

I can confirm that an unthreaded build of RC1 avoids this issue.
I don't know if that's in any way meaningful or useful information.
It's just that I noticed that the debugger announced "<code>Thread 1 received signal ?, Unknown signal</code>" and wondered how an unthreaded build would fare. So I tried it out - and all tests passed.

I think this sort of issue is a bit beyond me ... but I'm always willing to do some testing if anyone wants to ping me with stuff to try out.

**Comment by sisyphus** [comment]
I've noticed that this issue is not present in my builds of perl-5.36.0 and perl-5.37.2.
I think it went away in perl-5.35.x ... but I don't know what the values of "x" was.

Should this be Issue be closed ?

Cheers,
Rob
