### ISSUE TITLE
Perl 5.34 fails to compile on s390(x) (Attempt to free unreferenced scalar: SV 0x172ca48.)

### ISSUE THREAD

**Issue by thesamesam** [Perl/perl5#19307]
Perl 5.34.0 fails to build on s390(x) on Gentoo Linux. This issue was originally reported in Gentoo [here](https://bugs.gentoo.org/821577).

This seems to have started happening after modifying the *FLAGS used to build Perl. We modified our ebuild (build configuration/packaging) like so:
```
@@ -680,6 +665,7 @@
 		-Dnm="$(tc-getNM)" \
 		-Dcpp="$(tc-getCPP)" \
 		-Dranlib="$(tc-getRANLIB)" \
+		-Dccflags="${CFLAGS}" \
 		-Doptimize="${CFLAGS}" \
 		-Dldflags="${LDFLAGS}" \
 		-Dprefix="${EPREFIX}"'/usr' \
```

... which seems to have started the crashing, interestingly! Backing out this change results in a successful build.

I appreciate this is rather inaccessible hardware so if any Perl developers require access to such a machine, that can be arranged. Happy to try debugging based on hints/commands too, but I don't know anything about Perl internals.

Snippet from the build log (full log here: [build.log](https://github.com/Perl/perl5/files/7795045/build.log)).
```
s390x-ibm-linux-gnu-gcc -c -DPERL_CORE -O2 -pipe -march=z10 -Wimplicit-function-declaration -Wnonnull -Wstrict-aliasing -Wparentheses -Warray-bounds -Wfree-nonheap-object -Wreturn-local-addr -g -fwrapv -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -std=c89 -O2 -pipe -march=z10 -Wimplicit-function-declaration -Wnonnull -Wstrict-aliasing -Wparentheses -Warray-bounds -Wfree-nonheap-object -Wreturn-local-addr -g -Wall -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings -Werror=declaration-after-statement -fPIC op.c
s390x-ibm-linux-gnu-gcc -c -DPERL_CORE -O2 -pipe -march=z10 -Wimplicit-function-declaration -Wnonnull -Wstrict-aliasing -Wparentheses -Warray-bounds -Wfree-nonheap-object -Wreturn-local-addr -g -fwrapv -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -std=c89 -O2 -pipe -march=z10 -Wimplicit-function-declaration -Wnonnull -Wstrict-aliasing -Wparentheses -Warray-bounds -Wfree-nonheap-object -Wreturn-local-addr -g -Wall -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings -Werror=declaration-after-statement -fPIC perly.c
s390x-ibm-linux-gnu-gcc -Wl,-O1 -Wl,--as-needed -o miniperl \
    opmini.o perlmini.o  gv.o toke.o perly.o pad.o regcomp.o dump.o util.o mg.o reentr.o mro_core.o keywords.o hv.o av.o run.o pp_hot.o sv.o pp.o scope.o pp_ctl.o pp_sys.o doop.o doio.o regexec.o utf8.o taint.o deb.o universal.o globals.o perlio.o numeric.o mathoms.o locale.o pp_pack.o pp_sort.o caretx.o dquote.o time64.o  miniperlmain.o  -ldl -lm -lcrypt -lutil -lc
LD_LIBRARY_PATH=/var/tmp/portage/dev-lang/perl-5.34.0-r6/work/perl-5.34.0 /var/tmp/portage/dev-lang/perl-5.34.0-r6/work/perl-5.34.0/preload /var/tmp/portage/dev-lang/perl-5.34.0-r6/work/perl-5.34.0/libperl.so.5.34.0 ./miniperl -w -Ilib -Idist/Exporter/lib -MExporter -e '<?>' || sh -c 'echo >&2 Failed to build miniperl.  Please run make minitest; exit 1'
Attempt to free unreferenced scalar: SV 0x301faf0.
Attempt to free unreferenced scalar: SV 0x2fec720 at lib/strict.pm line 38.
Failed to build miniperl. Please run make minitest
make: *** [makefile:364: lib/buildcustomize.pl] Error 1
make: *** Waiting for unfinished jobs....
 * ERROR: dev-lang/perl-5.34.0-r6::gentoo failed (compile phase):
 *   emake failed
 *
```

```
# LD_LIBRARY_PATH=/var/tmp/portage/dev-lang/perl-5.34.0-r6/work/perl-5.34.0 gdb --args ./miniperl -w -Ilib -Idist/Exporter/lib -MExporter -e '<?>'
Reading symbols from ./miniperl...
(gdb) r
Starting program: /var/tmp/portage/dev-lang/perl-5.34.0-r6/work/perl-5.34.0/miniperl -w -Ilib -Idist/Exporter/lib -MExporter -e \<\?\>
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Attempt to free unreferenced scalar: SV 0x137e428.
Attempt to free unreferenced scalar: SV 0x135a708 at lib/strict.pm line 38.

Program received signal SIGSEGV, Segmentation fault.
0x0000000001010b18 in Perl_Slab_Alloc (sz=sz@entry=56) at op.c:414
414         INIT_OPSLOT(sz_in_p);
(gdb) bt
#0  0x0000000001010b18 in Perl_Slab_Alloc (sz=sz@entry=56) at op.c:414
#1  0x0000000001016c72 in Perl_newLISTOP (type=type@entry=158, flags=flags@entry=0, first=first@entry=0x139be80, last=last@entry=0x0) at op.c:6603
#2  0x0000000001017366 in S_force_list (o=o@entry=0x139be80, nullit=nullit@entry=true) at op.c:6563
#3  0x0000000001019278 in Perl_newUNOP (type=type@entry=184, flags=flags@entry=64, first=0x139be80) at op.c:6709
#4  0x0000000001064896 in Perl_yyparse (gramtype=gramtype@entry=258) at perly.y:1290
#5  0x0000000001110cda in S_doeval_compile (gimme=gimme@entry=2 '\002', outside=outside@entry=0x0, seq=<optimized out>, hh=hh@entry=0x0) at pp_ctl.c:3559
#6  0x0000000001112402 in S_require_file (sv=<optimized out>) at pp_ctl.c:4370
#7  Perl_pp_require () at pp_ctl.c:4394
#8  0x00000000010cc548 in Perl_runops_standard () at run.c:41
#9  0x00000000010312f4 in Perl_call_sv (sv=sv@entry=0x137e620, flags=flags@entry=13) at perl.c:3079
#10 0x00000000010339f8 in Perl_call_list (oldscope=oldscope@entry=6, paramList=0x137e590) at perl.c:5113
#11 0x000000000100fb94 in S_process_special_blocks (floor=floor@entry=144, fullname=<optimized out>, fullname@entry=0x136fe50 "BEGIN", cv=cv@entry=0x137e620, gv=<optimized out>) at op.c:11811
#12 0x0000000001029d9e in Perl_newATTRSUB_x (floor=floor@entry=144, o=<optimized out>, o@entry=0x138d970, proto=<optimized out>, proto@entry=0x0, attrs=<optimized out>, attrs@entry=0x0,
    block=0x138dd88, block@entry=0x138d898, o_is_gv=<optimized out>) at op.c:11736
#13 0x000000000102dcca in Perl_utilize (aver=<optimized out>, floor=<optimized out>, version=<optimized out>, idop=<optimized out>, arg=<optimized out>, arg@entry=0x0) at op.c:8834
#14 0x00000000010662aa in Perl_yyparse (gramtype=gramtype@entry=258) at perly.y:364
#15 0x0000000001110cda in S_doeval_compile (gimme=gimme@entry=2 '\002', outside=outside@entry=0x0, seq=<optimized out>, hh=hh@entry=0x0) at pp_ctl.c:3559
#16 0x0000000001112402 in S_require_file (sv=<optimized out>) at pp_ctl.c:4370
#17 Perl_pp_require () at pp_ctl.c:4394
#18 0x00000000010cc548 in Perl_runops_standard () at run.c:41
#19 0x00000000010312f4 in Perl_call_sv (sv=sv@entry=0x137e458, flags=flags@entry=13) at perl.c:3079
#20 0x00000000010339f8 in Perl_call_list (oldscope=oldscope@entry=2, paramList=0x135a8b8) at perl.c:5113
#21 0x000000000100fb94 in S_process_special_blocks (floor=floor@entry=42, fullname=<optimized out>, fullname@entry=0x136fe50 "BEGIN", cv=cv@entry=0x137e458, gv=<optimized out>) at op.c:11811
#22 0x0000000001029d9e in Perl_newATTRSUB_x (floor=floor@entry=42, o=<optimized out>, o@entry=0x1383520, proto=<optimized out>, proto@entry=0x0, attrs=<optimized out>, attrs@entry=0x0,
    block=0x13841a8, block@entry=0x1383448, o_is_gv=<optimized out>) at op.c:11736
#23 0x000000000102dcca in Perl_utilize (aver=<optimized out>, floor=<optimized out>, version=<optimized out>, idop=<optimized out>, arg=<optimized out>, arg@entry=0x0) at op.c:8834
#24 0x00000000010662aa in Perl_yyparse (gramtype=gramtype@entry=258) at perly.y:364
#25 0x0000000001038532 in S_parse_body (xsinit=0x1196f08 <xs_init>, env=0x0) at perl.c:2558
#26 perl_parse (my_perl=<optimized out>, xsinit=xsinit@entry=0x1196f08 <xs_init>, argc=<optimized out>, argv=<optimized out>, env=env@entry=0x0) at perl.c:1853
#27 0x000000000100dcb8 in main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>) at miniperlmain.c:115
(gdb)
```

System information:
```
# emerge --info
Portage 3.0.30 (python 3.9.9-final-0, default/linux/s390/17.0/s390x, gcc-9.3.0, glibc-2.34-r4, 5.10.7 s390x)
=================================================================
System uname: Linux-5.10.7-s390x-8561-with-glibc2.34
KiB Mem:     2055988 total,    461076 free
KiB Swap:      99160 total,     89948 free
Timestamp of repository gentoo: Fri, 31 Dec 2021 00:15:01 +0000
Head commit of repository gentoo: d72ce19f1c1751f430d5fe99db3d7d44a9da23ca
sh bash 5.1_p12
ld GNU ld (Gentoo 2.36.1 p3) 2.36.1
ccache version 4.5.1 [disabled]
app-misc/pax-utils:        1.3.3::gentoo
app-shells/bash:           5.1_p12::gentoo
dev-lang/perl:             5.34.0-r3::gentoo
dev-lang/python:           3.9.9::gentoo, 3.10.1-r1::gentoo
dev-util/ccache:           4.5.1::gentoo
dev-util/cmake:            3.22.1::gentoo
dev-util/meson:            0.60.3::gentoo
sys-apps/baselayout:       2.8::gentoo
sys-apps/openrc:           0.44.10::gentoo
sys-apps/sandbox:          2.29::gentoo
sys-devel/autoconf:        2.69-r5::gentoo, 2.71-r1::gentoo
sys-devel/automake:        1.16.5::gentoo
sys-devel/binutils:        2.36.1-r1::gentoo, 2.37_p1-r1::gentoo
sys-devel/binutils-config: 5.4::gentoo
sys-devel/gcc:             9.3.0-r1::gentoo
sys-devel/gcc-config:      2.5-r1::gentoo
sys-devel/libtool:         2.4.6-r6::gentoo
sys-devel/make:            4.3::gentoo
sys-kernel/linux-headers:  5.15-r2::gentoo (virtual/os-headers)
sys-libs/glibc:            2.34-r4::gentoo
Repositories:

gentoo
    location: /var/db/repos/gentoo
    sync-type: rsync
    sync-uri: rsync://rsync.namerica.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-verify-max-age: 24
    sync-rsync-extra-opts: 
    sync-rsync-verify-jobs: 1
    sync-rsync-verify-metamanifest: yes

ACCEPT_KEYWORDS="s390 ~s390"
ACCEPT_LICENSE="@FREE"
CBUILD="s390x-ibm-linux-gnu"
CFLAGS="-O2 -pipe -march=z10 -Wimplicit-function-declaration -Wnonnull -Wstrict-aliasing -Wparentheses -Warray-bounds -Wfree-nonheap-object -Wreturn-local-addr"
CHOST="s390x-ibm-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/env.d /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-O2 -pipe -march=z10"
DISTDIR="/var/cache/distfiles"
EMERGE_DEFAULT_OPTS="--keep-going=y"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs buildpkg-live config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news nodoc noinfo parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://gentoo.osuosl.org"
LANG="en_US.UTF8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j2"
PKGDIR="/var/cache/binpkgs"
PORTAGE_COMPRESS="xz"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
SHELL="/bin/bash"
USE="acl big-endian bzip2 cli crypt dri fortran gdbm iconv ipv6 multislot ncurses nls nptl openmp pam pcre readline s390 seccomp split-usr ssl unicode xattr zlib" ABI_S390="64" ADA_TARGET="gnat_2020" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="void libinput" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-3 php7-4" POSTGRES_TARGETS="postgres12 postgres13" PYTHON_SINGLE_TARGET="python3_9" PYTHON_TARGETS="python3_9" RUBY_TARGETS="ruby26 ruby27" USERLAND="GNU" VIDEO_CARDS="dummy v4l" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq proto steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  ADDR2LINE, AR, ARFLAGS, AS, ASFLAGS, CC, CCLD, CONFIG_SHELL, CPP, CPPFLAGS, CTARGET, CXX, CXXFILT, ELFEDIT, EXTRA_ECONF, F77FLAGS, FC, GCOV, GPROF, INSTALL_MASK, LC_ALL, LD, LEX, LFLAGS, LIBTOOL, LINGUAS, MAKE, MAKEFLAGS, NM, OBJCOPY, OBJDUMP, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, RANLIB, READELF, RUSTFLAGS, SIZE, STRINGS, STRIP, YACC, YFLAGS
```

```
-----------------------------------------------------------------
---
Flags:
    category=core
    severity=high
---
Site configuration information for perl 5.34.0:

Configured by Gentoo at Fri Nov  5 01:00:23 EDT 2021.

Summary of my perl5 (revision 5 version 34 subversion 0) configuration:
   
  Platform:
    osname=linux
    osvers=5.10.7
    archname=s390x-linux
    uname='linux localhost 5.10.7 #1 smp fri jan 15 01:31:34 est 2021 s390x 8561 ibm gnulinux '
    config_args='-des -Dinstallprefix=/usr -Dinstallusrbinperl=n -Ui_xlocale -Ui_ndbm -Di_gdbm -Ui_db -DDEBUGGING=none -Dlibpth=/usr/local/lib64 /lib64 /usr/lib64 -Dnoextensions=ODBM_File -Duseshrplib -Darchname=s390x-linux -Dcc=s390x-ibm-linux-gnu-gcc -Dar=s390x-ibm-linux-gnu-ar -Dnm=s390x-ibm-linux-gnu-nm -Dcpp=s390x-ibm-linux-gnu-gcc -E -Dranlib=s390x-ibm-linux-gnu-ranlib -Doptimize=-O2 -pipe -march=z10 -Wimplicit-function-declaration -Wnonnull -Wstrict-aliasing -Wparentheses -Warray-bounds -Wfree-nonheap-object -Wreturn-local-addr -Dldflags=-Wl,-O1 -Wl,--as-needed -Dprefix=/usr -Dsiteprefix=/usr/local -Dvendorprefix=/usr -Dscriptdir=/usr/bin -Dprivlib=/usr/lib64/perl5/5.34 -Darchlib=/usr/lib64/perl5/5.34/s390x-linux -Dsitelib=/usr/local/lib64/perl5/5.34 -Dsitearch=/usr/local/lib64/perl5/5.34/s390x-linux -Dvendorlib=/usr/lib64/perl5/vendor_perl/5.34
-Dvendorarch=/usr/lib64/perl5/vendor_perl/5.34/s390x-linux -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 -Dsiteman1dir=/usr/local/man/man1 -Dsiteman3dir=/usr/local/man/man3 -Dvendorman1dir=/usr/share/man/man1 -Dvendorman3dir=/usr/share/man/man3 -Dman1ext=1 -Dman3ext=3pm -Dlibperl=libperl.so.5.34.0 -Dlocincpth=/usr/include  -Dglibpth=/lib64 /usr/lib64	-Duselargefiles -Dd_semctl_semun -Dcf_by=Gentoo -Dmyhostname=localhost -Dperladmin=root@localhost -Ud_csh -Dsh=/bin/sh -Dtargetsh=/bin/sh -Uusenm -Ui_xlocale -Ui_ndbm -Di_gdbm -Ui_db -DDEBUGGING=none -Dlibpth=/usr/local/lib64 /lib64 /usr/lib64 -Dnoextensions=ODBM_File'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='s390x-ibm-linux-gnu-gcc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2 -pipe -march=z10 -Wimplicit-function-declaration -Wnonnull -Wstrict-aliasing -Wparentheses -Warray-bounds -Wfree-nonheap-object -Wreturn-local-addr'
    cppflags='-fwrapv -fno-strict-aliasing -pipe'
    ccversion=''
    gccversion='9.3.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=87654321
    doublekind=4
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=2
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='s390x-ibm-linux-gnu-gcc'
    ldflags ='-Wl,-O1 -Wl,--as-needed'
    libpth=/usr/local/lib64 /lib64 /usr/lib64 /usr/lib /lib
    libs=-lgdbm -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
    perllibs=-ldl -lm -lcrypt -lutil -lc
    libc=libc-2.33.so
    so=so
    useshrplib=true
    libperl=libperl.so.5.34.0
    gnulibc_version='2.33'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -pipe -march=z10 -Wimplicit-function-declaration -Wnonnull -Wstrict-aliasing -Wparentheses -Warray-bounds -Wfree-nonheap-object -Wreturn-local-addr -Wl,-O1 -Wl,--as-needed'

Locally applied patches:
    0001-Fix-hpux-hints.patch
    - Fix hpux hints
    0002-aix-gcc-detection-and-shared-library-soname-support.patch
    - aix gcc detection and shared library soname support
    0003-cpan-ExtUtils-MakeMaker-drop-PORTAGE_TMPDIR-from-LD_.patch
    - cpan/ExtUtils-MakeMaker: drop $PORTAGE_TMPDIR from LD_RUN_PATH
    - Bug: https://bugs.gentoo.org/105054
    0004-Remove-rpath-and-append-LDFLAGS-to-lddlflags.patch
    - Remove -rpath and append LDFLAGS to lddlflags
    0005-Add-headers-for-opensolaris.patch
    - Add headers for opensolaris
    0006-List-packaged-patches-in-patchlevel.h.patch
    - List packaged patches for perl-5.34.0-r3(perl-5.34.0-patches-1) in patchlevel.h
    - Bug: https://bugs.debian.org/567489
    0007-Cleanup-PATH-and-shrpenv.patch
    - Cleanup PATH and shrpenv
    0008-Tweak-enc2xs-to-follow-symlinks-and-ignore-missing-I.patch
    - Tweak enc2xs to follow symlinks and ignore missing @INC directories.
    - Bug: https://bugs.debian.org/290336
    0009-darwin-Use-CC-to-link.patch
    - darwin: Use $CC to link
    - Bug: https://bugs.gentoo.org/297751
    0010-Provide-a-sensible-INSTALLDIRS-default-for-modules-i.patch
    - Provide a sensible INSTALLDIRS default for modules installed from CPAN.
    0011-Fix-interix-hints.patch
    - Fix interix hints
    0012-Set-libperl-soname.patch
    - Set libperl soname
    - Bug: https://bugs.gentoo.org/286840
    0013-Add-etc-perl-to-INC.patch
    - Add /etc/perl to @INC
    0014-cpan-ExtUtils-MakeMaker-remove-targets-that-generate.patch
    - cpan/ExtUtils-MakeMaker: remove targets that generate perllocal.pod
    0015-Don-t-force-fstack-protector-on-everyone.patch
    - Don't force -fstack-protector on everyone
    - Bug: https://bugs.gentoo.org/348557
    0016-Do-not-set-custom-CFLAGS-in-cpan-Digest-SHA.patch
    - Do not set custom CFLAGS in cpan/Digest-SHA
    - Bug: https://bugs.gentoo.org/506818
    0017-Configure-Don-t-include-sources-in-usr-local-for-com.patch
    - Configure: Don't include sources in /usr/local/ for compiling perl
    0018-cpan-IO-Socket-IP-Disable-network-tests.patch
    - cpan/IO-Socket-IP: Disable network tests
    0019-Fix-EUMM-podlocal-tests.patch
    - Fix EUMM podlocal tests
    0020-Skip-auto-linking-nsl-and-cl.patch
    - Skip auto-linking nsl and cl
    - Bug: https://rt.perl.org/Public/Bug/Display.html?id=13148
    0021-Disable-porting-tests-which-create-fun-false-failure.patch
    - Disable porting tests which create fun false-failures all over travis
    0022-Disable-PathTools-tests-which-fails-under-sandboxing.patch
    - Disable PathTools tests which fails under sandboxing
    - Bug: https://bugs.gentoo.org/645084
    0023-Fix-CPAN-FirstTime-defaults-with-nonexisting-site-di.patch
    - Fix CPAN::FirstTime defaults with nonexisting site dirs if a parent is writable
    - Bug: https://bugs.debian.org/688842
    0024-Pass-LD-settings-through-to-subdirectories.patch
    - Pass LD settings through to subdirectories
    - Bug: https://bugs.debian.org/758471
    0025-Memoize-Storable-respect-nstore-option-not-respected.patch
    - Memoize::Storable: respect 'nstore' option not respected
    - Bug: https://bugs.debian.org/587650
    - Bug: https://rt.cpan.org/Public/Bug/Display.html?id=77790
    0026-Better-errors-for-man-pages-from-standard-input.patch
    - Better errors for man pages from standard input
    - Bug: https://bugs.debian.org/777405
    0027-Respect-umask-during-installation.patch
    - Respect umask during installation
    0028-Document-that-CCFLAGS-should-include-Config-ccflags.patch
    - Document that CCFLAGS should include $Config{ccflags}
    - Bug: https://bugs.debian.org/628522
    - Bug: https://rt.cpan.org/Public/Bug/Display.html?id=68613
    0029-Fix-parallel-building.patch
    - Fix parallel building
    0030-Add-support-for-Dgentoolibdirs.patch
    - Add support for -Dgentoolibdirs
    0101-Fix-build-with-gdb120.patch
    - Fix GDBM_File to compile with version 1.20 and earlier
    - Bug: https://bugs.gentoo.org/802945

---
@INC for perl 5.34.0:
    /etc/perl
    /usr/local/lib64/perl5/5.34/s390x-linux
    /usr/local/lib64/perl5/5.34
    /usr/lib64/perl5/vendor_perl/5.34/s390x-linux
    /usr/lib64/perl5/vendor_perl/5.34
    /usr/lib64/perl5/5.34/s390x-linux
    /usr/lib64/perl5/5.34

---
Environment for perl 5.34.0:
    HOME=/root
    LANG=en_US.UTF8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/sbin:/bin:/usr/sbin:/usr/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash
```

**Comment by thesamesam** [comment]
Changing the line to:
```
        -Dccflags="${CFLAGS} -fno-strict-aliasing" \
```
results in things working again.

Maybe we've misunderstood the purpose of `cflags` downstream? Although I think Perl should probably always force `-fno-strict-aliasing` if it's needed.

**Comment by jkeenan** [comment]
> Perl 5.34.0 fails to build on s390(x) on Gentoo Linux. This issue was originally reported in Gentoo [here](https://bugs.gentoo.org/821577).
> 
> This seems to have started happening after modifying the *FLAGS used to build Perl. We modified our ebuild (build configuration/packaging) like so:
> 
> ```
> @@ -680,6 +665,7 @@
>  		-Dnm="$(tc-getNM)" \
>  		-Dcpp="$(tc-getCPP)" \
>  		-Dranlib="$(tc-getRANLIB)" \
> +		-Dccflags="${CFLAGS}" \
>  		-Doptimize="${CFLAGS}" \
>  		-Dldflags="${LDFLAGS}" \
>  		-Dprefix="${EPREFIX}"'/usr' \
> ```
> 
> ... which seems to have started the crashing, interestingly! Backing out this change results in a successful build.
> 

Have you experimented with the content of `${CFLAGS}` to see if one of its terms is triggering the crash?  Farther below I see this:
```
CFLAGS="-O2 -pipe -march=z10 -Wimplicit-function-declaration -Wnonnull -Wstrict-aliasing -Wparentheses -Warray-bounds -Wfree-nonheap-object -Wreturn-local-addr"
```



> I appreciate this is rather inaccessible hardware so if any Perl developers require access to such a machine, that can be arranged. 

That will certainly be helpful and you might want to start the access process (though we'd have to identify who on the Perl side would be the best person to work with).

Thank you very much.
Jim Keenan

@khwilliamson, @iabyn, @tonycoz

**Comment by jkeenan** [comment]
On 12/30/21 8:37 PM, Sam James wrote:
> Changing the line to:
> 
> |-Dccflags="${CFLAGS} -fno-strict-aliasing" \ |
> 
> results in things working again.
> 

Note that I hadn't seen this post at the point where I hit Send on my 
previous comment.

> Maybe we've misunderstood the purpose of |cflags| downstream?
>

**Comment by khwilliamson** [comment]
On 12/30/21 18:37, Sam James wrote:
> Changing the line to:
> 
> |-Dccflags="${CFLAGS} -fno-strict-aliasing" \ |
> 
> results in things working again.
> 
>
Does that mean this fixes the bug report?

I was unaware of this hardware; so no we don't have access to it.  But 
we do have access to z/OS.

Is this running ASCII or EBCDIC (1047 no doubt if it is EBCDIC)

There have been substantial improvements in getting perl to work on z/OS 
in the 5.35 series.  Perhaps you'd want to take some of the patches

There is an ongoing effort to get z/OS in ASCII mode to work.

https://github.com/ZOSOpenTools/perlport

**Comment by khwilliamson** [comment]
Hi Sam

Would Like to collaborate with you on z/OS Perl. As Karl mentions I have been working on enhancing z/OS Perl. For the problem you mention, are you building its compiler optimization (I haven’t tried that yet but I think Karl was experimenting). 

Thanks, mike

**Comment by Leont** [comment]
Yeah, overriding ccflags instead of appending to it will almost always be the wrong thing. It's kind of unfortunate how that works, but it's not easy to change either.

Using `-Accflags="${CFLAGS}"` may work better for you.

**Comment by khwilliamson** [comment]
This has been fixed upstream (or maybe it might better be considered downstream)
