### ISSUE TITLE
PERL dumps core after XML-Encoding-1.01 test.pl completes

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#1956]
Migrated from [rt.perl.org#3229](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=3229) (status was 'resolved')

Searchable as RT3229$

**Comment by p5pRT** [comment]
### From jmilton@mesas.com

#### Created by jmilton@fundsxpress.com



bash$ cd CPAN/build/XML\-Encoding\-1\.01
bash$ myperl test\.pl 
1\.\.7
ok 1
ok 2
ok 3
ok 4
ok 5
ok 6
ok 7
Segmentation fault \(core dumped\)

I traced it in perl \-d&#8203;:
main&#8203;::\(test\.pl&#8203;:101\)&#8203;:    print "ok 7\\n";
ok 7
Carp&#8203;::\(/home/jmilton/base\-NB386/perl5/lib/5\.6\.0/Carp\.pm&#8203;:97\)&#8203;:
97&#8203;:         \{ local $@&#8203;; require Carp&#8203;::Heavy; \}  \# XXX fix require to not clear $@&#8203;?
Carp&#8203;::\(/home/jmilton/base\-NB386/perl5/lib/5\.6\.0/Carp\.pm&#8203;:97\)&#8203;:
97&#8203;:         \{ local $@&#8203;; require Carp&#8203;::Heavy; \}  \# XXX fix require to not clear $@&#8203;?
Carp&#8203;::\(/home/jmilton/base\-NB386/perl5/lib/5\.6\.0/Carp\.pm&#8203;:97\)&#8203;:
97&#8203;:         \{ local $@&#8203;; require Carp&#8203;::Heavy; \}  \# XXX fix require to not clear $@&#8203;?
Carp&#8203;::\(/home/jmilton/base\-NB386/perl5/lib/5\.6\.0/Carp\.pm&#8203;:98\)&#8203;:
98&#8203;:         goto &longmess\_heavy;
Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:30\)&#8203;:
30&#8203;:         return @&#8203;\_ if ref $\_\[0\];
Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:31\)&#8203;:
31&#8203;:         my $error = join ''\, @&#8203;\_;
Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:32\)&#8203;:
32&#8203;:         my $mess = "";
Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:33\)&#8203;:
33&#8203;:         my $i = 1 \+ $CarpLevel;
Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:34\)&#8203;:
34&#8203;:         my \($pack\,$file\,$line\,$sub\,$hargs\,$eval\,$require\);
Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:35\)&#8203;:
35&#8203;:         my \(@&#8203;a\);
Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:39\)&#8203;:
39&#8203;:         while \(do \{ \{ package DB; @&#8203;a = caller\($i\+\+\) \} \} \) \{
Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:39\)&#8203;:
39&#8203;:         while \(do \{ \{ package DB; @&#8203;a = caller\($i\+\+\) \} \} \) \{
Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:125\)&#8203;:
125&#8203;:        my $msg = \\\($mess || $error\);
Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:126\)&#8203;:
126&#8203;:        $$msg =~ tr/\\0//d;
Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:127\)&#8203;:
127&#8203;:        $$msg;
Signal SEGV&#8203;: 
Abort trap \(core dumped\)


I also dumped a stack backtrace with gdb from the core file&#8203;:
bash$ gdb /home/jmilton/base\-NB386/perl5/bin/perl perl\.core 
GNU gdb 4\.17
Copyright 1998 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and you are
welcome to change it and/or distribute copies of it under certain conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for details\.
This GDB was configured as "i386\-\-netbsd"\.\.\.\(no debugging symbols found\)\.\.\.
Core was generated by \`perl'\.
Program terminated with signal 6\, Abort trap\.
Reading symbols from /usr/libexec/ld\.so\.\.\.\(no debugging symbols found\)\.\.\.done\.
Reading symbols from /usr/lib/libm\.so\.0\.1\.\.\.\(no debugging symbols found\)\.\.\.
done\.
Reading symbols from /usr/lib/libposix\.so\.0\.1\.\.\.\(no debugging symbols found\)\.\.\.
done\.
Reading symbols from /usr/lib/libc\.so\.12\.40\.\.\.\(no debugging symbols found\)\.\.\.
done\.
Reading symbols from /usr/lib/libcrypt\.so\.0\.0\.\.\.\(no debugging symbols found\)\.\.\.
done\.
Reading symbols from /home/jmilton/base\-NB386/perl5/lib/site\_perl/5\.6\.0/i386\-netbsd/auto/XML/Parser/Expat/Expat\.so\.\.\.\(no debugging symbols found\)\.\.\.done\.
Reading symbols from /home/jmilton/base\-NB386/perl5/lib/site\_perl/5\.6\.0/i386\-netbsd/auto/HTML/Parser/Parser\.so\.\.\.\(no debugging symbols found\)\.\.\.done\.
Reading symbols from /home/jmilton/base\-NB386/perl5/lib/site\_perl/5\.6\.0/i386\-netbsd/auto/Term/ReadKey/ReadKey\.so\.\.\.\(no debugging symbols found\)\.\.\.done\.
\#0  0x40185aeb in kill \(\)
\(gdb\) backtrace
\#0  0x40185aeb in kill \(\)
\#1  0xc0969 in Perl\_apply \(\)
\#2  0xb9818 in Perl\_pp\_kill \(\)
\#3  0x8bf2e in Perl\_runops\_standard \(\)
\#4  0x4c072 in S\_call\_body \(\)
\#5  0x4bc72 in perl\_call\_sv \(\)
\#6  0x886f8 in Perl\_sighandler \(\)
\#7  0xbfbfdfd2 in ?? \(\)
\#8  0x401c6f26 in contentProcessor \(\)
\#9  0x401c92da in L863 \(\)
\#10 0x401c8d80 in prologProcessor \(\)
\#11 0x401c8d30 in prologInitProcessor \(\)
\#12 0x401c6931 in XML\_ParseBuffer \(\)
\#13 0x401c68e3 in XML\_Parse \(\)
\#14 0x401b2062 in XS\_XML\_\_Parser\_\_Expat\_ParseString \(\)
\#15 0x9108e in Perl\_pp\_entersub \(\)
\#16 0x8bf2e in Perl\_runops\_standard \(\)
\#17 0x4b868 in S\_run\_body \(\)
\#18 0x4b5d5 in perl\_run \(\)
\#19 0x183c in main \(\)

I have the core&#8203;:
1432 \-rw\-\-\-\-\-\-\-  1 jmilton  user  1454103 May 10 12&#8203;:37 perl\.core\.gz

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.6.0:

Configured by jmilton at Wed Apr 12 11:41:50 CDT 2000.

Summary of my perl5 (revision 5.0 version 6 subversion 0) configuration:
  Platform:
    osname=netbsd, osvers=1.4.2, archname=i386-netbsd
    uname='netbsd keel-verezy.mesas.com 1.4.2 netbsd 1.4.2 (eternal_doctrine) #0: mon mar 20 13:49:05 cst 2000 root@melnorme.mesas.com:melnorme-1netbsd-src-1.4.2usrsrcsysarchi386compileeternal_doctrine i386 '
    config_args=''
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define 
    use64bitint=undef use64bitall=undef uselongdouble=undef usesocks=undef
  Compiler:
    cc='cc', optimize='-O', gccversion=egcs-2.91.60 19981201 (egcs-1.1.1 release)
    cppflags='-fno-strict-aliasing -I/usr/pkg/include'
    ccflags ='-fno-strict-aliasing -I/usr/pkg/include'
    stdchar='char', d_stdstdio=undef, usevfork=false
    intsize=4, longsize=4, ptrsize=4, doublesize=8
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='ld', ldflags ='-L/home/jmilton/base-NB386/lib -L/usr/local/lib -L/usr/pkg/lib'
    libpth=/home/jmilton/base-NB386/lib /usr/local/lib /usr/pkg/lib /usr/lib
    libs=-lm -lc -lposix -lcrypt
    libc=/usr/lib/libc.so.12.40, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=define, ccdlflags='-Wl,-R/lib '
    cccdlflags='-DPIC -fPIC ', lddlflags='-Bshareable  -L/home/jmilton/base-NB386/lib -L/usr/local/lib -L/usr/pkg/lib'

Locally applied patches:
    


@INC for perl v5.6.0:
    /home/jmilton/base-NB386/perl5/lib/5.6.0/i386-netbsd
    /home/jmilton/base-NB386/perl5/lib/5.6.0
    /home/jmilton/base-NB386/perl5/lib/site_perl/5.6.0/i386-netbsd
    /home/jmilton/base-NB386/perl5/lib/site_perl/5.6.0
    /home/jmilton/base-NB386/perl5/lib/site_perl
    .


Environment for perl v5.6.0:
    HOME=/home/jmilton
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH=/home/jmilton/base-NB386/lib:/lib
    LOGDIR (unset)
    PATH=/home/jmilton/base/bin:/home/jmilton/base-NB386/bin:/usr/local/bin:/mesa/bin:/usr/pkg/bin:/usr/krb5/bin:/usr/bin:/bin:.:/usr/X11R6/bin:/sbin:/usr/sbin:/etc:/usr/games
    PERL_BADLANG (unset)
    SHELL=/bin/bash


```
</details>

**Comment by p5pRT** [comment]
### From @smpeters

> bash$ cd CPAN/build/XML\-Encoding\-1\.01
> bash$ myperl test\.pl
> 1\.\.7
> ok 1
> ok 2
> ok 3
> ok 4
> ok 5
> ok 6
> ok 7
> Segmentation fault \(core dumped\)
> 
> I traced it in perl \-d&#8203;:
> main&#8203;::\(test\.pl&#8203;:101\)&#8203;:    print "ok 7\\n";
> ok 7
> Carp&#8203;::\(/home/jmilton/base\-NB386/perl5/lib/5\.6\.0/Carp\.pm&#8203;:97\)&#8203;:
> 97&#8203;:         \{ local $@&#8203;; require Carp&#8203;::Heavy; \}  \# XXX fix require to
> not clear $@&#8203;?
> Carp&#8203;::\(/home/jmilton/base\-NB386/perl5/lib/5\.6\.0/Carp\.pm&#8203;:97\)&#8203;:
> 97&#8203;:         \{ local $@&#8203;; require Carp&#8203;::Heavy; \}  \# XXX fix require to
> not clear $@&#8203;?
> Carp&#8203;::\(/home/jmilton/base\-NB386/perl5/lib/5\.6\.0/Carp\.pm&#8203;:97\)&#8203;:
> 97&#8203;:         \{ local $@&#8203;; require Carp&#8203;::Heavy; \}  \# XXX fix require to
> not clear $@&#8203;?
> Carp&#8203;::\(/home/jmilton/base\-NB386/perl5/lib/5\.6\.0/Carp\.pm&#8203;:98\)&#8203;:
> 98&#8203;:         goto &longmess\_heavy;
> Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-
> NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:30\)&#8203;:
> 30&#8203;:         return @&#8203;\_ if ref $\_\[0\];
> Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-
> NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:31\)&#8203;:
> 31&#8203;:         my $error = join ''\, @&#8203;\_;
> Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-
> NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:32\)&#8203;:
> 32&#8203;:         my $mess = "";
> Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-
> NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:33\)&#8203;:
> 33&#8203;:         my $i = 1 \+ $CarpLevel;
> Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-
> NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:34\)&#8203;:
> 34&#8203;:         my \($pack\,$file\,$line\,$sub\,$hargs\,$eval\,$require\);
> Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-
> NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:35\)&#8203;:
> 35&#8203;:         my \(@&#8203;a\);
> Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-
> NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:39\)&#8203;:
> 39&#8203;:         while \(do \{ \{ package DB; @&#8203;a = caller\($i\+\+\) \} \} \) \{
> Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-
> NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:39\)&#8203;:
> 39&#8203;:         while \(do \{ \{ package DB; @&#8203;a = caller\($i\+\+\) \} \} \) \{
> Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-
> NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:125\)&#8203;:
> 125&#8203;:        my $msg = \\\($mess || $error\);
> Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-
> NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:126\)&#8203;:
> 126&#8203;:        $$msg =~ tr/\\0//d;
> Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-
> NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:127\)&#8203;:
> 127&#8203;:        $$msg;
> Signal SEGV&#8203;:
> Abort trap \(core dumped\)
> 
> 
> I also dumped a stack backtrace with gdb from the core file&#8203;:
> bash$ gdb /home/jmilton/base\-NB386/perl5/bin/perl perl\.core
> GNU gdb 4\.17
> Copyright 1998 Free Software Foundation\, Inc\.
> GDB is free software\, covered by the GNU General Public License\, and
> you are
> welcome to change it and/or distribute copies of it under certain
> conditions\.
> Type "show copying" to see the conditions\.
> There is absolutely no warranty for GDB\.  Type "show warranty" for
> details\.
> This GDB was configured as "i386\-\-netbsd"\.\.\.\(no debugging symbols
> found\)\.\.\.
> Core was generated by \`perl'\.
> Program terminated with signal 6\, Abort trap\.
> Reading symbols from /usr/libexec/ld\.so\.\.\.\(no debugging symbols
> found\)\.\.\.done\.
> Reading symbols from /usr/lib/libm\.so\.0\.1\.\.\.\(no debugging symbols
> found\)\.\.\.
> done\.
> Reading symbols from /usr/lib/libposix\.so\.0\.1\.\.\.\(no debugging symbols
> found\)\.\.\.
> done\.
> Reading symbols from /usr/lib/libc\.so\.12\.40\.\.\.\(no debugging symbols
> found\)\.\.\.
> done\.
> Reading symbols from /usr/lib/libcrypt\.so\.0\.0\.\.\.\(no debugging symbols
> found\)\.\.\.
> done\.
> Reading symbols from /home/jmilton/base\-
> NB386/perl5/lib/site\_perl/5\.6\.0/i386\-
> netbsd/auto/XML/Parser/Expat/Expat\.so\.\.\.\(no debugging symbols
> found\)\.\.\.done\.
> Reading symbols from /home/jmilton/base\-
> NB386/perl5/lib/site\_perl/5\.6\.0/i386\-
> netbsd/auto/HTML/Parser/Parser\.so\.\.\.\(no debugging symbols
> found\)\.\.\.done\.
> Reading symbols from /home/jmilton/base\-
> NB386/perl5/lib/site\_perl/5\.6\.0/i386\-
> netbsd/auto/Term/ReadKey/ReadKey\.so\.\.\.\(no debugging symbols
> found\)\.\.\.done\.
> \#0  0x40185aeb in kill \(\)
> \(gdb\) backtrace
> \#0  0x40185aeb in kill \(\)
> \#1  0xc0969 in Perl\_apply \(\)
> \#2  0xb9818 in Perl\_pp\_kill \(\)
> \#3  0x8bf2e in Perl\_runops\_standard \(\)
> \#4  0x4c072 in S\_call\_body \(\)
> \#5  0x4bc72 in perl\_call\_sv \(\)
> \#6  0x886f8 in Perl\_sighandler \(\)
> \#7  0xbfbfdfd2 in ?? \(\)
> \#8  0x401c6f26 in contentProcessor \(\)
> \#9  0x401c92da in L863 \(\)
> \#10 0x401c8d80 in prologProcessor \(\)
> \#11 0x401c8d30 in prologInitProcessor \(\)
> \#12 0x401c6931 in XML\_ParseBuffer \(\)
> \#13 0x401c68e3 in XML\_Parse \(\)
> \#14 0x401b2062 in XS\_XML\_\_Parser\_\_Expat\_ParseString \(\)
> \#15 0x9108e in Perl\_pp\_entersub \(\)
> \#16 0x8bf2e in Perl\_runops\_standard \(\)
> \#17 0x4b868 in S\_run\_body \(\)
> \#18 0x4b5d5 in perl\_run \(\)
> \#19 0x183c in main \(\)
> 

I installed XML\-Encoding\-1\.01 and had no such core dump\.  Of course\, the
core dump could have occured somewhere in one of the modules rather than
in Perl itself\.  Or the bug could have been in Perl and resolved
somewhere in the past four years\.

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @schwern

On Sun\, Oct 24\, 2004 at 01&#8203;:29&#8203;:27AM \-0000\, Steve Peters via RT wrote&#8203;:
> > Carp&#8203;::longmess\_heavy\(/home/jmilton/base\-
> > NB386/perl5/lib/5\.6\.0/Carp/Heavy\.pm&#8203;:127\)&#8203;:
> > 127&#8203;:        $$msg;
> > Signal SEGV&#8203;:
> > Abort trap \(core dumped\)

\<snip>

> I installed XML\-Encoding\-1\.01 and had no such core dump\.  Of course\, the
> core dump could have occured somewhere in one of the modules rather than
> in Perl itself\.  Or the bug could have been in Perl and resolved
> somewhere in the past four years\.

5\.6\.0 had a nasty habit of generating odd errors in Carp\.pm\.  "Bizarre copy
of array" was one of the more common ones\.  I wouldn't be surprised if this
was related and has long since been fixed\.


\-\- 
Michael G Schwern        schwern@&#8203;pobox\.com  http&#8203;://www\.pobox\.com/~schwern/
Now if you'll excuse me\, I've got about a hundred hours of memories to 
erase\!\!
&nbsp;        \-\- http&#8203;://www\.angryflower\.com/allrigh\.gif
