### ISSUE TITLE
cpan/Test-Harness/t/harness.t: Test failure under Address Sanitizer

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#19643]
https://github.com/Perl/perl5/pull/19635 requested synching of the latest CPAN version of Test-Harness into blead.  [CPANtesters results](http://matrix.cpantesters.org/?dist=Test-Harness) were good and the p.r. was favorably reviewed, so I hit the "rebase and merge" button.

Uh-oh!  Didn't see those CI failures under ASAN.  @LeonT is working on this.  Here, for the record, is the failure on my own machine.
```
$ uname -mrs
Linux 5.4.0-107-generic x86_64

$ ./perl -Ilib -V:config_args
config_args='-des -Dusedevel -DDEBUGGING -Dcc=clang -fsanitize=address -Dld=clang -fsanitize=address';

$ cd t;./perl harness ../cpan/Test-Harness/t/harness.t; cd -
../cpan/Test-Harness/t/harness.t .. 84/133 AddressSanitizer:DEADLYSIGNAL
=================================================================
==101927==ERROR: AddressSanitizer: SEGV on unknown address 0x03e800018e27 (pc 0x7fa0f167d40b bp 0x7fff4e180b60 sp 0x7fff4e180938 T0)
==101927==The signal is caused by a READ memory access.
    #0 0x7fa0f167d40b in kill /build/glibc-sMfBJT/glibc-2.31/signal/../sysdeps/unix/syscall-template.S:78
    #1 0x9829e9 in Perl_apply /home/jkeenan/gitwork/perl/doio.c:2719:26
    #2 0x94eddf in Perl_pp_chown /home/jkeenan/gitwork/perl/pp_sys.c:3744:28
    #3 0x73f685 in Perl_runops_debug /home/jkeenan/gitwork/perl/dump.c:2634:23
    #4 0x56e663 in S_run_body /home/jkeenan/gitwork/perl/perl.c
    #5 0x56de8e in perl_run /home/jkeenan/gitwork/perl/perl.c:2628:9
    #6 0x4e0bec in main /home/jkeenan/gitwork/perl/perlmain.c:110:9
    #7 0x7fa0f165e0b2 in __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:308:16
    #8 0x438bdd in _start (/home/jkeenan/gitwork/perl/perl+0x438bdd)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /build/glibc-sMfBJT/glibc-2.31/signal/../sysdeps/unix/syscall-template.S:78 in kill
==101927==ABORTING

#   Failed test 'SIGSEGV is parsed out'
#   at t/harness.t line 535.
#                   't/sample-tests/segfault ..Dubious, test returned 1 (wstat 256, 0x100)No subtests runTest Summary Report-------------------t/sample-tests/segfault (Wstat: 256 (exited 1) Tests: 0 Failed: 0)Non-zero exit status: 1Parse errors: No plan found in TAP outputFiles=1, Tests=0,  0 wallclock secs ( 0.00 usr  0.00 sys +  0.01 cusr  0.01 csys =  0.02 CPU)Result: FAIL'
#     doesn't match '(?^:SEGV)'
# Looks like you failed 1 test of 133.
../cpan/Test-Harness/t/harness.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/133 subtests 

Test Summary Report
-------------------
../cpan/Test-Harness/t/harness.t (Wstat: 256 (exited 1) Tests: 133 Failed: 1)
  Failed test:  86
  Non-zero exit status: 1
Files=1, Tests=133,  1 wallclock secs ( 0.07 usr  0.01 sys +  0.57 cusr  0.30 csys =  0.95 CPU)
Result: FAIL
```

**Comment by Leont** [comment]
The problem here is that ASAN causes the SEGV inducing script to not return 11 (= segv) but 256 (= return 1). I don't quite understand why they're thinking when deciding that.

**Comment by jkeenan** [comment]
With commit dafafd88993fc3625eed1f6e68f58248b6762bde, we are now skipping the failing test.  Ticket should remain open while we address the underlying problem.
