### ISSUE TITLE
Subtle av_extend memory badness

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#1990]
Migrated from [rt.perl.org#3264](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=3264) (status was 'resolved')

Searchable as RT3264$

**Comment by p5pRT** [comment]
### From @simoncozens

#### Created by 02552@scozens.uucp



The business about SVs overgrowing segments got me thinking\. Edge cases
expose bugs\, and sure enough\, perl \-e '\+\+$a\[2\*\*30\]' dumps core\.

This confirmed on Cygwin and Linux\, with and without Perl's malloc\.
The backtrace&#8203;:

154                         ary\[\-\-tmp\] = &PL\_sv\_undef;
\(gdb\) bt
\#0  0x401aac in Perl\_av\_extend \(av=0xa06764c\, key=1073741824\) at av\.c&#8203;:154
\#1  0x401df5 in Perl\_av\_store \(av=0xa06764c\, key=1073741824\, val=0xa059598\)
&nbsp;    at av\.c&#8203;:271
\#2  0x401be4 in Perl\_av\_fetch \(av=0xa06764c\, key=1073741824\, lval=1\)
&nbsp;    at av\.c&#8203;:204
\#3  0x469779 in Perl\_pp\_aelem \(\) at pp\_hot\.c&#8203;:2709
\#4  0x48b4ef in Perl\_runops\_standard \(\) at run\.c&#8203;:25

I'll be perfectly honest here and say that I don't understand how
av\_extend is supposed to work\. I think AvALLOC\(av\) may be getting a duff
pointer\, because tmp \(that's AvALLOC\(av\)\-AvARRAY\(av\)\) appears to be of
the order of 2\*\*30\. But I don't really want to debug memory problems
because they're really sticky and horrible\. :\)

\(Incidentally\, \+\+$a\[2\*\*28\] does the right thing and reports "out of memory
during large request for 1073745920 bytes"\, \+\+$a\[2\*\*29\] wraps and claims
it's being asked for \-2147479552 bytes\. Weird\, huh?\)

<details><summary>Perl Info</summary>

```


Site configuration information for perl v5.6.0:

Configured by 02552 at Wed Mar 15 11:25:20  2000.

Summary of my perl5 (revision 5.0 version 6 subversion 0) configuration:
  Platform:
    osname=cygwin, osvers=1.1.0(0.1832), archname=cygwin
    uname='cygwin_nt-4.0 scozens 1.1.0(0.1832) 2000-03-010 16:57:37i586 i586
unknown '
    config_args='-d'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef
usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define
    use64bitint=undef use64bitall=undef uselongdouble=undef usesocks=undef
  Compiler:
    cc='gcc', optimize='-O', gccversion=egcs-2.91.57 19980901 (egcs-1.1 release)
    cppflags='-fno-strict-aliasing -I/usr/local/include'
    ccflags ='-fno-strict-aliasing -I/usr/local/include'
    stdchar='char', d_stdstdio=undef, usevfork=false
    intsize=4, longsize=4, ptrsize=4, doublesize=8
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t',
lseeksize=4
    alignbytes=8, usemymalloc=y, prototype=define
  Linker and Libraries:
    ld='ld2', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /tmp/bleadperl /lib /usr/lib
    libs=-lm -lcrypt -lcygwin -lkernel32
    libc=/usr/lib/libc.a, so=dll, useshrplib=true, libperl=libperl5_6_0.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=dll, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags=' -L/usr/local/lib'

Locally applied patches:
    v5.6.0-RC1


@INC for perl v5.6.0:
    /usr/local/lib/perl5/5.6.0/cygwin
    /usr/local/lib/perl5/5.6.0
    /usr/local/lib/perl5/site_perl/5.6.0/cygwin
    /usr/local/lib/perl5/site_perl/5.6.0
    /usr/local/lib/perl5/site_perl/5.00562/cygwin
    /usr/local/lib/perl5/site_perl/5.00562
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.6.0:
    HOME=/home/simon
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)

PATH=/bin:/usr/local/bin:/usr/bin:/miktex/miktex/bin:/PROGRA~1/ORACLE/WIN32/bin:/WINNT/system32:/WINNT:/PROGRA~1/ORACLE/WIN16/BIN

    PERL_BADLANG (unset)
    SHELL=/bin/sh

__END__

----------------------------------------------------------------
The information transmitted is intended only for the person or entity to which
it is addressed and may contain confidential and/or privileged material.  Any
review, retransmission, dissemination or other use of, or taking of any action
in reliance upon, this information by persons or entities other than the
intended recipient is prohibited.   If you received this in error, please
contact the sender and delete the material from any computer.




```
</details>

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]


> \(Yes\, CC'ing p5p is bad\, but I don't trust the bugthing\)
> 
> This is a bug report for perl from 02552@&#8203;scozens\.uucp\,
> generated with the help of perlbug 1\.28 running under perl v5\.6\.0\.
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> 
> The business about SVs overgrowing segments got me thinking\. Edge cases
> expose bugs\, and sure enough\, perl \-e '\+\+$a\[2\*\*30\]' dumps core\.
> 
> This confirmed on Cygwin and Linux\, with and without Perl's malloc\.
> The backtrace&#8203;:
> 
> 154                         ary\[\-\-tmp\] = &PL\_sv\_undef;
> \(gdb\) bt
> \#0  0x401aac in Perl\_av\_extend \(av=0xa06764c\, key=1073741824\) at av\.c&#8203;:154
> \#1  0x401df5 in Perl\_av\_store \(av=0xa06764c\, key=1073741824\, val=0xa059598\)
>     at av\.c&#8203;:271
> \#2  0x401be4 in Perl\_av\_fetch \(av=0xa06764c\, key=1073741824\, lval=1\)
>     at av\.c&#8203;:204
> \#3  0x469779 in Perl\_pp\_aelem \(\) at pp\_hot\.c&#8203;:2709
> \#4  0x48b4ef in Perl\_runops\_standard \(\) at run\.c&#8203;:25
> 
> I'll be perfectly honest here and say that I don't understand how
> av\_extend is supposed to work\. I think AvALLOC\(av\) may be getting a duff
> pointer\, because tmp \(that's AvALLOC\(av\)\-AvARRAY\(av\)\) appears to be of
> the order of 2\*\*30\. But I don't really want to debug memory problems
> because they're really sticky and horrible\. :\)
> 
> \(Incidentally\, \+\+$a\[2\*\*28\] does the right thing and reports "out of memory
> during large request for 1073745920 bytes"\, \+\+$a\[2\*\*29\] wraps and claims
> it's being asked for \-2147479552 bytes\. Weird\, huh?\)
> 
> \[Please do not change anything below this line\]
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> 
> \-\-\-
> Site configuration information for perl v5\.6\.0&#8203;:
> 
> Configured by 02552 at Wed Mar 15 11&#8203;:25&#8203;:20  2000\.
> 
> Summary of my perl5 \(revision 5\.0 version 6 subversion 0\) configuration&#8203;:
>   Platform&#8203;:
>     osname=cygwin\, osvers=1\.1\.0\(0\.1832\)\, archname=cygwin
>     uname='cygwin\_nt\-4\.0 scozens 1\.1\.0\(0\.1832\) 2000\-03\-010 16&#8203;:57&#8203;:37i586 i586
> unknown '
>     config\_args='\-d'
>     hint=recommended\, useposix=true\, d\_sigaction=define
>     usethreads=undef use5005threads=undef useithreads=undef
> usemultiplicity=undef
>     useperlio=undef d\_sfio=undef uselargefiles=define
>     use64bitint=undef use64bitall=undef uselongdouble=undef usesocks=undef
>   Compiler&#8203;:
>     cc='gcc'\, optimize='\-O'\, gccversion=egcs\-2\.91\.57 19980901 \(egcs\-1\.1 release\)
>     cppflags='\-fno\-strict\-aliasing \-I/usr/local/include'
>     ccflags ='\-fno\-strict\-aliasing \-I/usr/local/include'
>     stdchar='char'\, d\_stdstdio=undef\, usevfork=false
>     intsize=4\, longsize=4\, ptrsize=4\, doublesize=8
>     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
>     ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,
> lseeksize=4
>     alignbytes=8\, usemymalloc=y\, prototype=define
>   Linker and Libraries&#8203;:
>     ld='ld2'\, ldflags =' \-L/usr/local/lib'
>     libpth=/usr/local/lib /tmp/bleadperl /lib /usr/lib
>     libs=\-lm \-lcrypt \-lcygwin \-lkernel32
>     libc=/usr/lib/libc\.a\, so=dll\, useshrplib=true\, libperl=libperl5\_6\_0\.a
>   Dynamic Linking&#8203;:
>     dlsrc=dl\_dlopen\.xs\, dlext=dll\, d\_dlsymun=undef\, ccdlflags=' '
>     cccdlflags=' '\, lddlflags=' \-L/usr/local/lib'
> 
> Locally applied patches&#8203;:
>     v5\.6\.0\-RC1
> 
> \-\-\-
> @&#8203;INC for perl v5\.6\.0&#8203;:
>     /usr/local/lib/perl5/5\.6\.0/cygwin
>     /usr/local/lib/perl5/5\.6\.0
>     /usr/local/lib/perl5/site\_perl/5\.6\.0/cygwin
>     /usr/local/lib/perl5/site\_perl/5\.6\.0
>     /usr/local/lib/perl5/site\_perl/5\.00562/cygwin
>     /usr/local/lib/perl5/site\_perl/5\.00562
>     /usr/local/lib/perl5/site\_perl
>     \.
> 
> \-\-\-
> Environment for perl v5\.6\.0&#8203;:
>     HOME=/home/simon
>     LANG \(unset\)
>     LANGUAGE \(unset\)
>     LD\_LIBRARY\_PATH \(unset\)
>     LOGDIR \(unset\)
> 
> PATH=/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/miktex/miktex/bin&#8203;:/PROGRA~1/ORACLE/WIN32/bin&#8203;:/WINNT/system32&#8203;:/WINNT&#8203;:/PROGRA~1/ORACLE/WIN16/BIN
> 
>     PERL\_BADLANG \(unset\)
>     SHELL=/bin/sh
> 
> \_\_END\_\_
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> The information transmitted is intended only for the person or entity to which
> it is addressed and may contain confidential and/or privileged material\.  Any
> review\, retransmission\, dissemination or other use of\, or taking of any action
> in reliance upon\, this information by persons or entities other than the
> intended recipient is prohibited\.   If you received this in error\, please
> contact the sender and delete the material from any computer\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]


> \(Yes\, CC'ing p5p is bad\, but I don't trust the bugthing\)
> 
> This is a bug report for perl from 02552@&#8203;scozens\.uucp\,
> generated with the help of perlbug 1\.28 running under perl v5\.6\.0\.
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> 
> The business about SVs overgrowing segments got me thinking\. Edge cases
> expose bugs\, and sure enough\, perl \-e '\+\+$a\[2\*\*30\]' dumps core\.
> 
> This confirmed on Cygwin and Linux\, with and without Perl's malloc\.
> The backtrace&#8203;:
> 
> 154                         ary\[\-\-tmp\] = &PL\_sv\_undef;
> \(gdb\) bt
> \#0  0x401aac in Perl\_av\_extend \(av=0xa06764c\, key=1073741824\) at av\.c&#8203;:154
> \#1  0x401df5 in Perl\_av\_store \(av=0xa06764c\, key=1073741824\, val=0xa059598\)
>     at av\.c&#8203;:271
> \#2  0x401be4 in Perl\_av\_fetch \(av=0xa06764c\, key=1073741824\, lval=1\)
>     at av\.c&#8203;:204
> \#3  0x469779 in Perl\_pp\_aelem \(\) at pp\_hot\.c&#8203;:2709
> \#4  0x48b4ef in Perl\_runops\_standard \(\) at run\.c&#8203;:25
> 
> I'll be perfectly honest here and say that I don't understand how
> av\_extend is supposed to work\. I think AvALLOC\(av\) may be getting a duff
> pointer\, because tmp \(that's AvALLOC\(av\)\-AvARRAY\(av\)\) appears to be of
> the order of 2\*\*30\. But I don't really want to debug memory problems
> because they're really sticky and horrible\. :\)
> 
> \(Incidentally\, \+\+$a\[2\*\*28\] does the right thing and reports "out of memory
> during large request for 1073745920 bytes"\, \+\+$a\[2\*\*29\] wraps and claims
> it's being asked for \-2147479552 bytes\. Weird\, huh?\)
> 
> \[Please do not change anything below this line\]
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> 
> \-\-\-
> Site configuration information for perl v5\.6\.0&#8203;:
> 
> Configured by 02552 at Wed Mar 15 11&#8203;:25&#8203;:20  2000\.
> 
> Summary of my perl5 \(revision 5\.0 version 6 subversion 0\) configuration&#8203;:
>   Platform&#8203;:
>     osname=cygwin\, osvers=1\.1\.0\(0\.1832\)\, archname=cygwin
>     uname='cygwin\_nt\-4\.0 scozens 1\.1\.0\(0\.1832\) 2000\-03\-010 16&#8203;:57&#8203;:37i586 i586
> unknown '
>     config\_args='\-d'
>     hint=recommended\, useposix=true\, d\_sigaction=define
>     usethreads=undef use5005threads=undef useithreads=undef
> usemultiplicity=undef
>     useperlio=undef d\_sfio=undef uselargefiles=define
>     use64bitint=undef use64bitall=undef uselongdouble=undef usesocks=undef
>   Compiler&#8203;:
>     cc='gcc'\, optimize='\-O'\, gccversion=egcs\-2\.91\.57 19980901 \(egcs\-1\.1 release\)
>     cppflags='\-fno\-strict\-aliasing \-I/usr/local/include'
>     ccflags ='\-fno\-strict\-aliasing \-I/usr/local/include'
>     stdchar='char'\, d\_stdstdio=undef\, usevfork=false
>     intsize=4\, longsize=4\, ptrsize=4\, doublesize=8
>     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
>     ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,
> lseeksize=4
>     alignbytes=8\, usemymalloc=y\, prototype=define
>   Linker and Libraries&#8203;:
>     ld='ld2'\, ldflags =' \-L/usr/local/lib'
>     libpth=/usr/local/lib /tmp/bleadperl /lib /usr/lib
>     libs=\-lm \-lcrypt \-lcygwin \-lkernel32
>     libc=/usr/lib/libc\.a\, so=dll\, useshrplib=true\, libperl=libperl5\_6\_0\.a
>   Dynamic Linking&#8203;:
>     dlsrc=dl\_dlopen\.xs\, dlext=dll\, d\_dlsymun=undef\, ccdlflags=' '
>     cccdlflags=' '\, lddlflags=' \-L/usr/local/lib'
> 
> Locally applied patches&#8203;:
>     v5\.6\.0\-RC1
> 
> \-\-\-
> @&#8203;INC for perl v5\.6\.0&#8203;:
>     /usr/local/lib/perl5/5\.6\.0/cygwin
>     /usr/local/lib/perl5/5\.6\.0
>     /usr/local/lib/perl5/site\_perl/5\.6\.0/cygwin
>     /usr/local/lib/perl5/site\_perl/5\.6\.0
>     /usr/local/lib/perl5/site\_perl/5\.00562/cygwin
>     /usr/local/lib/perl5/site\_perl/5\.00562
>     /usr/local/lib/perl5/site\_perl
>     \.
> 
> \-\-\-
> Environment for perl v5\.6\.0&#8203;:
>     HOME=/home/simon
>     LANG \(unset\)
>     LANGUAGE \(unset\)
>     LD\_LIBRARY\_PATH \(unset\)
>     LOGDIR \(unset\)
> 
> PATH=/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/miktex/miktex/bin&#8203;:/PROGRA~1/ORACLE/WIN32/bin&#8203;:/WINNT/system32&#8203;:/WINNT&#8203;:/PROGRA~1/ORACLE/WIN16/BIN
> 
>     PERL\_BADLANG \(unset\)
>     SHELL=/bin/sh
> 
> \_\_END\_\_
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> The information transmitted is intended only for the person or entity to which
> it is addressed and may contain confidential and/or privileged material\.  Any
> review\, retransmission\, dissemination or other use of\, or taking of any action
> in reliance upon\, this information by persons or entities other than the
> intended recipient is prohibited\.   If you received this in error\, please
> contact the sender and delete the material from any computer\.
