### ISSUE TITLE
BBC: TODDR/YAML-Syck-1.34.tar.gz

### ISSUE THREAD

**Issue by andk** [Perl/perl5#19939]
**Description**

Starting with 58cf04199f there is a SEGV on tests for TODDR/YAML-Syck-1.34.tar.gz

Sample fail report with perl ac57742 by Carlos Guevara: http://www.cpantesters.org/cpan/report/f9f37278-fedf-11ec-ba22-c2077611788e

Git bisect for this fail lead me to

``` text
   58cf04199f69d7a775bc88024df0bbb48712ea37 is the first bad commit                        
   commit 58cf04199f69d7a775bc88024df0bbb48712ea37
   Author: David Mitchell <davem@iabyn.com>
   Date:   Wed Jul 6 11:14:22 2022 +0100
   
       goto(&xs_sub): provide correct caller context
```

This bisect has already been dealt with in https://github.com/Perl/perl5/issues/19936 for Types-ReadOnly, but the fix there has not resolved the problem with YAML-Syck.

Sample fail report with the newer perl 8a4b911d06: http://www.cpantesters.org/cpan/report/6155c0dc-0026-11ed-9cc1-cebb0db46c39

**Steps to Reproduce**

cpan -i TODDR/YAML-Syck-1.34.tar.gz

**Expected behavior**

Should pass the tests and install the module

**Perl configuration**

```
# perl -V output goes here
Summary of my perl5 (revision 5 version 37 subversion 2) configuration:
  Commit id: 8a4b911d06671a03e21054142ab2c27b15d5fd3e
  Platform:
    osname=linux
    osvers=5.10.0-14-amd64
    archname=x86_64-linux-thread-multi
    uname='linux k93msid 5.10.0-14-amd64 #1 smp debian 5.10.113-1 (2022-04-29) x86_64 gnulinux '
    config_args='-Dprefix=/home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.37.1-103-g8a4b911d06/419a -Dmyhostname=k93msid -Dinstallusrbinperl=n -Uversiononly -Dusedevel -des -Ui_db -Dlibswanted=cl pthread socket inet nsl gdbm dbm malloc dl ld sun m crypt sec util c cposix posix ucb BSD gdbm_compat -Duseithreads -Uuselongdouble -DEBUGGING=none'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='11.3.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/lib64
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.33.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.33'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Jul  9 2022 21:02:03
  %ENV:
    PERL5LIB=""
    PERL5OPT=""
    PERL5_CPANPLUS_IS_RUNNING="1995545"
    PERL5_CPAN_IS_RUNNING="1995545"
    PERL_CANARY_STABILITY_NOPROMPT="1"
    PERL_MM_USE_DEFAULT="1"
    PERL_USE_UNSAFE_INC="1"
  @INC:
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.37.1-103-g8a4b911d06/419a/lib/site_perl/5.37.2/x86_64-linux-thread-multi
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.37.1-103-g8a4b911d06/419a/lib/site_perl/5.37.2
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.37.1-103-g8a4b911d06/419a/lib/5.37.2/x86_64-linux-thread-multi
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.37.1-103-g8a4b911d06/419a/lib/5.37.2
    .
```

**Comment by jkeenan** [comment]
Confirmed on FreeBSD-12:
```
[perlmonger: YAML-Syck-1.34-0] $ uname -mrs; cc --version | head -1; bleadperl -v | head -2 | tail -1;bleadperl -V
:config_args
FreeBSD 12.3-RELEASE-p1 amd64
FreeBSD clang version 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611aa2)
This is perl 5, version 37, subversion 2 (v5.37.2 (v5.37.1-103-g8a4b911d06)) built for amd64-freebsd-thread-multi
config_args='-des -Dusedevel -Uversiononly -Dprefix=/home/jkeenan/testing/blead -Dman1dir=none -Dman3dir=none -Duseithreads -Doptimize=-O2 -pipe -fstack-protector -fno-strict-aliasing';

$ bleadprove -vb t/11-loadfile.t 
t/11-loadfile.t .. 
1..12
ok 1 - LoadFile(*DATA) works
ok 2 - LoadFile(\*DATA) works
ok 3 - LoadFile works with file names
ok 4 - LoadFile works with IO::File
ok 5 - LoadFile works with indirect filehandles
ok 6 - LoadFile works with ordinary filehandles
ok 7 - LoadFile works with glob refs
ok 8 - LoadFile works with in-memory files
ok 9 - LoadFile dies loading an empty file
ok 10 - LoadFile returns undef loading an empty file
Failed 2/12 subtests 

Test Summary Report
-------------------
t/11-loadfile.t (Wstat: 139 (Signal: SEGV, dumped core) Tests: 10 Failed: 0)
  Non-zero wait status: 139
  Parse errors: Bad plan.  You planned 12 tests but ran 10.
Files=1, Tests=10,  1 wallclock secs ( 0.05 usr  0.01 sys +  0.10 cusr  0.03 csys =  0.20 CPU)
Result: FAIL
```
@iabyn, can you take a look?

**Comment by tonycoz** [comment]
Under the debugger, with -DDEBUGGING:
```
ok 10 - LoadFile returns undef loading an empty file
perl: pp_ctl.c:2187: Perl_pp_leave: Assertion `CxTYPE(cx) == CXt_BLOCK' failed.

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7c64537 in __GI_abort () at abort.c:79
#2  0x00007ffff7c6440f in __assert_fail_base (
    fmt=0x7ffff7dcd128 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x555555b15ad6 "CxTYPE(cx) == CXt_BLOCK", 
    file=0x555555b1488c "pp_ctl.c", line=2187, function=<optimized out>)
    at assert.c:92
#3  0x00007ffff7c73662 in __GI___assert_fail (
    assertion=0x555555b15ad6 "CxTYPE(cx) == CXt_BLOCK", 
    file=0x555555b1488c "pp_ctl.c", line=2187, 
    function=0x555555b1d6f0 <__PRETTY_FUNCTION__.55> "Perl_pp_leave")
    at assert.c:101
#4  0x000055555582ad07 in Perl_pp_leave () at pp_ctl.c:2187
#5  0x00005555557139d2 in Perl_runops_debug () at dump.c:2677
#6  0x00005555555def7c in S_run_body (oldscope=1) at perl.c:2736
#7  0x00005555555de531 in perl_run (my_perl=0x555555bb42a0) at perl.c:2664
#8  0x000055555559b117 in main (argc=3, argv=0x7fffffffe768, 
    env=0x7fffffffe788) at perlmain.c:107
(gdb) up 4
#4  0x000055555582ad07 in Perl_pp_leave () at pp_ctl.c:2187
2187        assert(CxTYPE(cx) == CXt_BLOCK);
(gdb) p cx
$1 = (PERL_CONTEXT *) 0x555555bb9338
(gdb) p cx->cx_u.cx_subst.sbu_type & 0xf
$3 = 9
```

**Comment by iabyn** [comment]
On Sun, Jul 10, 2022 at 10:25:28PM -0700, Tony Cook wrote:
> Under the debugger, with -DDEBUGGING:
> ```
> ok 10 - LoadFile returns undef loading an empty file
> perl: pp_ctl.c:2187: Perl_pp_leave: Assertion `CxTYPE(cx) == CXt_BLOCK' failed.

It's a bug in the module. There's an XS function which calls this code in
its perl_syck.h file:

    static SV * LoadYAML (char *s) {
        ...
        ENTER; SAVETMPS;
        ...
        if (*s == '\0') { return &PL_sv_undef; }
        ...
        FREETMPS; LEAVE;
    }    

In the case of trying to load an empty path, the LEAVE gets skipped,
which back in the caller, pp_goto(), means the LEAVE there doesn't
undo the SAVEOP() which was added by my recent comment. This means that
PL_op gets restored much too late - while leaving some other scope - and
all hell breaks loose.

Although the bug is in the module, I've removed the SAVEOP() in pp_goto(),
since after some thought I decided it wasn't needed. This fixes the BBC for
now, but the module really needs fixing at some point.



-- 
You're only as old as you look.

**Comment by jkeenan** [comment]
Confirmed that YAML-Syck now installs against blead:
```
 ./bin/perl -v | head -2 | tail -1;./bin/perl -MYAML::Syck -E 'say $YAML::Syck::VERSION;'
This is perl 5, version 37, subversion 2 (v5.37.2 (v5.37.1-184-g5888abcc02)) built for amd64-freebsd-thread-multi
1.34
```
Closing this ticket. @toddr, note what Dave is saying about the distro's problems.  Thanks.
