### ISSUE TITLE
Leaking locales under address sanitizer

### ISSUE THREAD

**Issue by demerphq** [Perl/perl5#20461]
**Description**
When building with the address sanitizer I can see leaking locale objects. This is preventing me from debugging leaks that I caused in https://github.com/Perl/perl5/pull/20457 which is how i noticed, see https://github.com/Perl/perl5/actions/runs/3361810659/jobs/5572900746

**Steps to Reproduce**
./Configure -Dusedevel -Doptimize=-g -d -DDEBUGGING -Dusethreads -Accflags=-DPURIFY -Dcc='gcc -fsanitize=address' -Dld='gcc -fsanitize=address' -Dprefix="$HOME/perl-blead"
make

Build blows up.

**Expected behavior**
Perl should build in this configuration in blead.

**Perl configuration**

```
$ ./Configure -Dusedevel -Doptimize=-g -d -DDEBUGGING -Dusethreads -Accflags=-DPURIFY -Dcc='gcc -fsanitize=address' -Dld='gcc -fsanitize=address' -Dprefix="$HOME/perl-blead"
$ make
# Build fails...
$ ./miniperl -Ilib -V
Can't locate Config.pm in @INC (you may need to install the Config module) (@INC contains: lib .).
BEGIN failed--compilation aborted.

=================================================================
==1706939==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 348 byte(s) in 1 object(s) allocated from:
    #0 0x7ff5edcc4808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7ff5ed83e1b9 in __newlocale /build/glibc-SzIz7B/glibc-2.31/locale/newlocale.c:200
    #2 0x55c87a1077ef in S_emulate_setlocale_i /home/yorton/git_tree/perl/locale.c:1251
    #3 0x55c87a10b230 in Perl_set_numeric_standard /home/yorton/git_tree/perl/locale.c:1970
    #4 0x55c87a10b039 in S_new_numeric /home/yorton/git_tree/perl/locale.c:1946
    #5 0x55c87a1109a9 in S_new_LC_ALL /home/yorton/git_tree/perl/locale.c:2447
    #6 0x55c87a119a3a in Perl_init_i18nl10n /home/yorton/git_tree/perl/locale.c:5162
    #7 0x55c8798ec2d6 in perl_construct /home/yorton/git_tree/perl/perl.c:466
    #8 0x55c87a184290 in main /home/yorton/git_tree/perl/miniperlmain.c:108
    #9 0x7ff5ed82f082 in __libc_start_main ../csu/libc-start.c:308

Direct leak of 244 byte(s) in 1 object(s) allocated from:
    #0 0x7ff5edcc4808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7ff5ed83e1b9 in __newlocale /build/glibc-SzIz7B/glibc-2.31/locale/newlocale.c:200
    #2 0x55c87a10a6ac in S_new_numeric /home/yorton/git_tree/perl/locale.c:1882
    #3 0x55c87a1109a9 in S_new_LC_ALL /home/yorton/git_tree/perl/locale.c:2447
    #4 0x55c87a119a3a in Perl_init_i18nl10n /home/yorton/git_tree/perl/locale.c:5162
    #5 0x55c8798ec2d6 in perl_construct /home/yorton/git_tree/perl/perl.c:466
    #6 0x55c87a184290 in main /home/yorton/git_tree/perl/miniperlmain.c:108
    #7 0x7ff5ed82f082 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: 592 byte(s) leaked in 2 allocation(s).
```
```
$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by khwilliamson** [comment]
AFAIK this doesn't show leaks with  PERL_DESTRUCT_LEVEL=2.

**Comment by demerphq** [comment]
No, it doesn't. I didnt realize I had to enable that to even build. Maybe comments in the code saying something so if people end up down the rabbit hole i just went down there is a note directing them back to sanity?

**Comment by demerphq** [comment]
I hacked up https://github.com/Perl/perl5/pull/20464

**Comment by demerphq** [comment]
Comments added. closing.
