### ISSUE TITLE
Crashes on "unpack+Punpack,chmodmod"

### ISSUE THREAD

**Issue by mikhailnov** [Perl/perl5#21539]
Fuzzing has found that perl 5.38.0 anf 5.30.3 crash on the following file:

```perl
unpack+Punpack,chmodmod
```

Backtrace:

```
$ gdb --args perl file
<...>
(gdb) bt
#0  0x00007ffff7933b04 in __memmove_avx_unaligned_erms () from /usr/lib64/libc.so.6
#1  0x00007ffff7bfbe01 in Perl_sv_setpvn_fresh (my_perl=0x4052a0, sv=0x408538, ptr=0x646f6d646f6d6863 <error: Cannot access memory at address 0x646f6d646f6d6863>, len=1) at sv.c:5045
#2  0x00007ffff7c05fdc in Perl_newSVpvn_flags (my_perl=0x4052a0, s=0x646f6d646f6d6863 <error: Cannot access memory at address 0x646f6d646f6d6863>, len=1, flags=524288) at sv.c:9572
#3  0x00007ffff7cb6bf0 in S_unpack_rec (my_perl=0x4052a0, symptr=0x7fffffffda80, s=0x43f068 "", strbeg=0x43f060 "chmodmod", strend=0x43f068 "", new_s=0x0) at pp_pack.c:1642
#4  0x00007ffff7cb2f9c in Perl_unpackstring (my_perl=0x4052a0, pat=0x43e860 "Punpack", patend=0x43e867 "", s=0x43f060 "chmodmod", strend=0x43f068 "", flags=0) at pp_pack.c:856
#5  0x00007ffff7cb7ce9 in Perl_pp_unpack (my_perl=0x4052a0) at pp_pack.c:1866
#6  0x00007ffff7bd7c4c in Perl_runops_standard (my_perl=0x4052a0) at run.c:41
#7  0x00007ffff7a82434 in S_run_body (my_perl=0x4052a0, oldscope=1) at perl.c:2812
#8  0x00007ffff7a81dc0 in perl_run (my_perl=0x4052a0) at perl.c:2727
#9  0x0000000000401309 in main (argc=2, argv=0x7fffffffde48, env=0x7fffffffde60) at perlmain.c:127
```

**Comment by xenu** [comment]
This parses as:

```
> perl -MO=Deparse,-p -e 'unpack+Punpack,chmodmod'
unpack('Punpack', 'chmodmod');
```

[As documented](https://perldoc.perl.org/5.38.0/functions/pack), the 'P' pack rule interprets its input as "a pointer to a structure (fixed-length string)". And indeed, in the stacktrace you provided, there's an attempt to read memory from the address 0x646f6d646f6d6863. which is a hex representation of the `"chmodmod"` string (in reverse order).

While this is a terrible misfeature, it's not a bug.

**Comment by mikhailnov** [comment]
Thanks for explaining! Maybe it is possible to handle memory reading error and avoid crashes of perl, just give an error?

**Comment by demerphq** [comment]
> While this is a terrible misfeature, it's not a bug.

Well said.

**Comment by Leont** [comment]
> While this is a terrible misfeature, it's not a bug.

Having used the feature in anger I don't agree; it's really more a rarely needed feature.
