### ISSUE TITLE
utf8::length() bad

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#2280]
Migrated from [rt.perl.org#3598](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=3598) (status was 'resolved')

Searchable as RT3598$

**Comment by p5pRT** [comment]
### From jfriedl@yahoo-inc.com

#### Created by jfriedl@yahoo-inc.com



Hi\,

&nbsp;   % perl \-mutf8 \-e "print utf8&#8203;::length\('a'\)"

causes my cpu to peg\, and memory to grow until I break out of it\.

I tried running it in gdb\, got a segfault report immediately\, but the
thing kept running \(and sucking memory\) until I broke out of it&#8203;:

&nbsp;    \(gdb\) run \-mutf8 \-e "print utf8&#8203;::length\('a'\)"
&nbsp;    Starting program&#8203;: /usr/src/perl\-5\.6\.0/perl \-mutf8 \-e "print utf8&#8203;::length\('a'\)"
&nbsp;    Segmentation fault \(core dumped\)

\-\-\- several seconds pass\, then I interrupt it \-\-\-

&nbsp;    Program received signal SIGINT\, Interrupt\.
&nbsp;    0x8091349 in Perl\_hv\_fetch \(hv=0x80f08e0\, key=0xbffff0e4 "utf8&#8203;::"\, klen=6\, 
&nbsp;    lval=1\) at hv\.c&#8203;:181
&nbsp;    181         PERL\_HASH\(hash\, key\, klen\);
&nbsp;    \(gdb\) where
&nbsp;    \#0  0x8091349 in Perl\_hv\_fetch \(hv=0x80f08e0\, key=0xbffff0e4 "utf8&#8203;::"\, klen=6\, 
&nbsp;    lval=1\) at hv\.c&#8203;:181
&nbsp;    \#1  0x805fe73 in Perl\_gv\_fetchpv \(nambeg=0x80fcb10 "utf8&#8203;::length"\, add=1\, 
&nbsp;    sv\_type=12\) at gv\.c&#8203;:550
&nbsp;    \#2  0x80a11e3 in Perl\_sv\_2cv \(sv=0x80fb010\, st=0xbffff224\, gvp=0xbffff228\, 
&nbsp;    lref=1\) at sv\.c&#8203;:4981
&nbsp;    \#3  0x80a3fde in Perl\_pp\_rv2cv \(\) at pp\.c&#8203;:379
&nbsp;    \#4  0x80949ed in Perl\_runops\_standard \(\) at run\.c&#8203;:27
&nbsp;    \#5  0x805bd4e in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1401
&nbsp;    \#6  0x805bad8 in perl\_run \(my\_perl=0x80f0858\) at perl\.c&#8203;:1325
&nbsp;    \#7  0x8059903 in main \(argc=4\, argv=0xbffff354\, env=0xbffff368\)
&nbsp;    at perlmain\.c&#8203;:52

Even though I have my coredumplimit set to zero\, when running this from
within gdb\, it does dump a small \(360k\) core file\. On a whim\, I ran

&nbsp;    jfriedl@&#8203;fummy> gdb /usr/src/perl\-5\.6\.0/perl core
&nbsp;    GNU gdb 4\.18
&nbsp;    Copyright 1998 Free Software Foundation\, Inc\.
&nbsp;    This GDB was configured as "i386\-mandrake\-linux"\.\.\.

&nbsp;    warning&#8203;: core file may not match specified executable file\.
&nbsp;    Core was generated by \`perl \-w test \-d /etc/profile\.d'\.
&nbsp;    Program terminated with signal 11\, Segmentation fault\.
&nbsp;    Reading symbols from /lib/libnsl\.so\.1\.\.\.done\.
&nbsp;    Reading symbols from /lib/libdb\.so\.3\.\.\.done\.
&nbsp;    Reading symbols from /usr/lib/libgdbm\.so\.2\.\.\.done\.
&nbsp;    Reading symbols from /lib/libdl\.so\.2\.\.\.done\.
&nbsp;    Reading symbols from /lib/libm\.so\.6\.\.\.done\.
&nbsp;    Reading symbols from /lib/libc\.so\.6\.\.\.done\.
&nbsp;    Reading symbols from /lib/libcrypt\.so\.1\.\.\.done\.
&nbsp;    Reading symbols from /lib/ld\-linux\.so\.2\.\.\.done\.
&nbsp;    \#0  0x400fd1f4 in memmove \(\) from /lib/libc\.so\.6
&nbsp;    \(gdb\) where
&nbsp;    \#0  0x400fd1f4 in memmove \(\) from /lib/libc\.so\.6
&nbsp;    \#1  0x80faf7c in ?? \(\)
&nbsp;    Cannot access memory at address 0x1\.

Which seems odd\, to say the least\.

&nbsp;    Jeffrey

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.6.0:

Configured by jfriedl at Sat Jul 29 20:09:33 PDT 2000.

Summary of my perl5 (revision 5.0 version 6 subversion 0) configuration:
  Platform:
    osname=linux, osvers=2.2.15, archname=i686-linux
    uname='linux fummy.dsl.yahoo.com 2.2.16 #6 smp sun jul 23 11:26:16 pdt 2000 i686 unknown '
    config_args='-ds -e -A optimize=-g'
    hint=previous, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define 
    use64bitint=undef use64bitall=undef uselongdouble=undef usesocks=undef
  Compiler:
    cc='cc', optimize='-O2 -g', gccversion=pgcc-2.91.66 19990314 (egcs-1.1.2 release)
    cppflags='-fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    ccflags ='-fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    stdchar='char', d_stdstdio=define, usevfork=false
    intsize=4, longsize=4, ptrsize=4, doublesize=8
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lndbm -lgdbm -ldb -ldl -lm -lc -lposix -lcrypt
    libc=/lib/libc-2.1.1.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.0:
    /home/jfriedl/lib/perl
    /home/jfriedl/lib/perl/yahoo
    /usr/local/lib/perl5/5.6.0/i686-linux
    /usr/local/lib/perl5/5.6.0
    /usr/local/lib/perl5/site_perl/5.6.0/i686-linux
    /usr/local/lib/perl5/site_perl/5.6.0
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.6.0:
    HOME=/home/jfriedl
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH=/usr/local/pgsql/lib:/home/jfriedl/src/rvplayer5.0
    LOGDIR (unset)
    PATH=/home/jfriedl/bin:/home/jfriedl/common/bin:/usr/local/gcc-2.95.2/bin:.:/usr/local/pgsql/bin:/usr/local/bin:/usr/X11R6/bin:/bin:/usr/bin:/usr/sbin:/sbin:/home/jfriedl/src/rvplayer5.0
    PERLLIB=/home/jfriedl/lib/perl:/home/jfriedl/lib/perl/yahoo
    PERL_BADLANG (unset)
    SHELL=/bin/tcsh


```
</details>

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Jeffrey Friedl \(lists\.p5p\)&#8203;:
>   % perl \-mutf8 \-e "print utf8&#8203;::length\('a'\)"
>
>causes my cpu to peg\, and memory to grow until I break out of it\.

Oh\, \*swear\*\. I know why this is happening\, and I'll have a look at it
today if possible\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Simon Cozens \(lists\.p5p\)&#8203;:
>Jeffrey Friedl \(lists\.p5p\)&#8203;:
>>   % perl \-mutf8 \-e "print utf8&#8203;::length\('a'\)"
>>
>>causes my cpu to peg\, and memory to grow until I break out of it\.
>
>Oh\, \*swear\*\. I know why this is happening\, and I'll have a look at it
>today if possible\.

Hm\, this was more fundamental than I thought\. Why do you think you
should be able to call utf8&#8203;::length? utf8 is a pragma\, not a module
which replaces Perl's builtins\.

Nevertheless\, recursive AUTOLOADs are certainly bad\.

<details><summary>Inline Patch</summary>

```diff
--- lib/utf8.pm~        Tue Aug  1 15:46:44 2000
+++ lib/utf8.pm Tue Aug  1 15:53:16 2000
@@ -13,7 +13,8 @@

 sub AUTOLOAD {
     require "utf8_heavy.pl";
-    goto &$AUTOLOAD;
+    goto &$AUTOLOAD if defined &$AUTOLOAD;
+    Carp::croak("Undefined subroutine $AUTOLOAD called");
 }

 1;
```
</details>

**Comment by p5pRT** [comment]
### From @jhi

> Nevertheless\, recursive AUTOLOADs are certainly bad\.
> 
> \-\-\- lib/utf8\.pm~        Tue Aug  1 15&#8203;:46&#8203;:44 2000
> \+\+\+ lib/utf8\.pm Tue Aug  1 15&#8203;:53&#8203;:16 2000
> @&#8203;@&#8203; \-13\,7 \+13\,8 @&#8203;@&#8203;
> 
>  sub AUTOLOAD \{
>      require "utf8\_heavy\.pl";
> \-    goto &$AUTOLOAD;
> \+    goto &$AUTOLOAD if defined &$AUTOLOAD;
> \+    Carp&#8203;::croak\("Undefined subroutine $AUTOLOAD called"\);
>  \}
> 
>  1;

Applied\, thanks\.
