### ISSUE TITLE
Not OK: perl v5.7.0 +SUIDMAIL +DEVEL6654 on    sparc64-linux-thread-multi-64all 2.2.14-5.0

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#2383]
Migrated from [rt.perl.org#3722](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=3722) (status was 'resolved')

Searchable as RT3722$

**Comment by p5pRT** [comment]
### From richard@polaris.empire2.com


This is a build failure report for perl from richard@&#8203;polaris\.empire2\.com\,
generated with the help of perlbug 1\.31 running under perl v5\.7\.0\.




---
One test failed \(also under @&#8203;6640\)\.  Is this a build failure?

R\.

lib/db\-recno\.\.\.\.\.\.\.\.\.FAILED at test 0

$ \./perl harness lib/db\-recno\.t
lib/db\-recno\.\.\.\.\.\.\.\.dubious                                                  
&nbsp;        Test returned status 0 \(wstat 138\, 0x8a\)
&nbsp;        test program seems to have generated a core
FAILED\-\-1 test script could be run\, alas\-\-no output ever seen

\(gdb\) bt
\#0  0x7019ac8c in chunk\_free \(ar\_ptr=0x70248ee4\, p=0x120e28\) at malloc\.c&#8203;:3111
\#1  0x7019aaf4 in free \(\) at malloc\.c&#8203;:2950
\#2  0x7005bb08 in \_\_bam\_close \(dbp=0x120cd0\) at btree/bt\_close\.c&#8203;:88
\#3  0x70065f34 in \_\_ram\_close \(argdbp=0x120cd0\) at btree/bt\_recno\.c&#8203;:395
\#4  0x7006e474 in db\_close \(dbp=0x120cd0\, flags=0\) at db/db\.c&#8203;:765
\#5  0x702ec8ac in XS\_DB\_File\_DESTROY \(\) 
&nbsp;      from /home/richard/perl/t/\.\./lib/auto/DB\_File/DB\_File\.so
\#6  0x7815c in Perl\_pp\_entersub \(\)
\#7  0x2697c in S\_call\_body \(\)
\#8  0x26700 in Perl\_call\_sv \(\)
\#9  0x80368 in Perl\_sv\_clear \(\)
\#10 0x80a58 in Perl\_sv\_free \(\)
\#11 0x80710 in Perl\_sv\_clear \(\)
\#12 0x80a58 in Perl\_sv\_free \(\)
\#13 0x7fa2c in Perl\_sv\_unmagic \(\)
\#14 0xab1c8 in Perl\_pp\_untie \(\)
\#15 0x710b4 in Perl\_runops\_standard \(\)
\#16 0x25f0c in S\_run\_body \(\)
\#17 0x25be4 in perl\_run \(\)
\#18 0x230dc in main \(\)
\#19 0x7015e9b4 in \_\_libc\_start\_main \(\) at
&nbsp;      \.\./sysdeps/generic/libc\-start\.c&#8203;:122



---


---
Flags&#8203;:
&nbsp;    category=install
&nbsp;    severity=none


---
Site configuration information for perl v5\.7\.0&#8203;:

Configured by richard at Wed Aug 16 10&#8203;:23&#8203;:03 PDT 2000\.

Summary of my perl5 \(revision 5\.0 version 7 subversion 0\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.2\.14\-5\.0\, archname=sparc64\-linux\-thread\-multi\-64all
&nbsp;    uname='linux polaris\.empire2\.com 2\.2\.14\-5\.0 \#1 tue mar 7 21&#8203;:50&#8203;:41 est 2000 sparc64 unknown '
&nbsp;    config\_args=''
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define 
&nbsp;    use64bitint=define use64bitall=define uselongdouble=define usesocks=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'\, optimize='\-O2'\, gccversion=egcs\-2\.91\.66 19990314/Linux \(egcs\-1\.1\.2 release\)\, gccosandvers=
&nbsp;    cppflags='\-D\_REENTRANT \-fno\-strict\-aliasing \-I/usr/local/include'
&nbsp;    ccflags ='\-D\_REENTRANT \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'
&nbsp;    stdchar='char'\, d\_stdstdio=define\, usevfork=false
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=8
&nbsp;    ivtype='long long'\, ivsize=8\, nvtype='long double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, usemymalloc=y\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='gcc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-lndbm \-lgdbm \-ldb \-ldl \-lm \-lpthread \-lc \-lposix \-lcrypt \-lutil
&nbsp;    libc=/lib/libc\-2\.1\.3\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
&nbsp;    cccdlflags='\-fpic'\, lddlflags='\-shared \-L/usr/local/lib'

Locally applied patches&#8203;:
&nbsp;    SUIDMAIL \- fixes for suidperl security
&nbsp;    DEVEL6654



---
@&#8203;INC for perl v5\.7\.0&#8203;:
&nbsp;    /etc/httpd/lib/perl
&nbsp;    /home/richard/perl\-jarkko/lib/5\.7\.0/sparc64\-linux\-thread\-multi\-64all
&nbsp;    /home/richard/perl\-jarkko/lib/5\.7\.0
&nbsp;    /home/richard/perl\-jarkko/lib/site\_perl/5\.7\.0/sparc64\-linux\-thread\-multi\-64all
&nbsp;    /home/richard/perl\-jarkko/lib/site\_perl/5\.7\.0
&nbsp;    /home/richard/perl\-jarkko/lib/site\_perl
&nbsp;    \.



---
Environment for perl v5\.7\.0&#8203;:
&nbsp;    HOME=/home/richard
&nbsp;    LANG=en\_US
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH=&#8203;:
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/richard/bin&#8203;:/usr/local/bin&#8203;:/usr/local/sbin&#8203;:/usr/X11R6/bin&#8203;:/usr/kerberos/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/sbin&#8203;:/sbin&#8203;:/usr/X11R6/bin
&nbsp;    PERL5LIB=/etc/httpd/lib/perl
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
@jhi - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @jhi

I'm closing off some of the older Not OK reports\.  If you still have problems\, please report them using Perl 5\.8\.0\.

**Comment by p5pRT** [comment]
@jhi - Status changed from 'open' to 'resolved'
