### ISSUE TITLE
Another segfault with regexes.

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#2606]
Migrated from [rt.perl.org#4279](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=4279) (status was 'resolved')

Searchable as RT4279$

**Comment by p5pRT** [comment]
### From @abigail

#### Created by @abigail



&nbsp;    \#\!/opt/perl/bin/perl \-wl

&nbsp;    use strict;
&nbsp;    $\_ = "foo";   
&nbsp;    s/f\(?\{s\!o\!o\!\}\)/f/;
&nbsp;    \_\_END\_\_
&nbsp;    Segmentation fault

Perl 5\.7\.0 segfaults too\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.6.0:

Configured by abigail at Wed Jun 14 21:00:02 EDT 2000.

Summary of my perl5 (revision 5.0 version 6 subversion 0) configuration:
  Platform:
    osname=linux, osvers=2.2.13, archname=i686-linux-64int
    uname='linux alexandra 2.2.13 #5 tue feb 8 15:37:54 est 2000 i686 unknown '
    config_args='-Dprefix=/opt/perl -d -Uinstallusrbinperl -Doptimize=-g -Dusemorebits'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define 
    use64bitint=define use64bitall=undef uselongdouble=define usesocks=undef
  Compiler:
    cc='cc', optimize='-g', gccversion=2.95.2 19991024 (release)
    cppflags='-DDEBUGGING -fno-strict-aliasing -I/usr/local/include'
    ccflags ='-DDEBUGGING -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    stdchar='char', d_stdstdio=define, usevfork=false
    intsize=4, longsize=4, ptrsize=4, doublesize=8
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long long', ivsize=8, nvtype='long double', nvsize=12, Off_t='off_t', lseeksize=8
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lndbm -lgdbm -ldbm -ldb -ldl -lm -lc -lposix -lcrypt
    libc=/lib/libc-2.1.2.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.0:
    /home/abigail/Perl
    /home/abigail/Sybase
    /opt/perl/lib/5.6.0/i686-linux-64int
    /opt/perl/lib/5.6.0
    /opt/perl/lib/site_perl/5.6.0/i686-linux-64int
    /opt/perl/lib/site_perl/5.6.0
    /opt/perl/lib/site_perl/5.005
    /opt/perl/lib/site_perl
    .


Environment for perl v5.6.0:
    HOME=/home/abigail
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH=/home/abigail/Lib:/usr/local/lib:/usr/lib:/lib:/usr/X11R6/lib:/opt/tcl/lib:/opt/tk/lib/tk8.0
    LOGDIR (unset)
    PATH=/home/abigail/Bin:/opt/perl/bin:/opt/tcl/bin:/opt/tk/bin:/usr/local/bin:/usr/local/X11/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/X11R6/bin:/usr/games:/opt/povray/bin:/opt/teTeX/bin/i686-pc-linux-gnu:/opt/python/bin
    PERL5LIB=/home/abigail/Perl:/home/abigail/Sybase
    PERLDIR=/opt/perl
    PERL_BADLANG (unset)
    SHELL=/bin/bash


```
</details>

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

abigail writes&#8203;:
>     use strict;
>     $\_ = "foo";   
>     s/f\(?\{s\!o\!o\!\}\)/f/;
>     \_\_END\_\_
>     Segmentation fault

I'm really out of my league here\, but it looks like the regex parser quit
prematurely\.
Take a look at the Purify trace after my \.sig\.
====================================================
Mark Leighton Fisher    Thomson Consumer Electronics
fisherm@&#8203;tce\.com         Indianapolis\, IN\, USA
"Display some adaptability\."  \-\- Doug Shaftoe\, \_Cryptonomicon\_




\[E\] IPR&#8203;: Invalid pointer read in S\_nextchar \{1 occurrence\}
&nbsp;    Reading 1 byte from 0x18261952 \(1 byte at 0x18261952 illegal\)
&nbsp;    Address 0x18261952 points into a malloc'd block 
&nbsp;    Thread ID&#8203;: 0x1a5
&nbsp;    Error location
&nbsp;    S\_nextchar     \[regcomp\.c&#8203;:3575\]
&nbsp;    
&nbsp;        for \(;;\) \{
&nbsp;        if \(\*PL\_regcomp\_parse == '\(' && PL\_regcomp\_parse\[1\] == '?' &&
 =>         PL\_regcomp\_parse\[2\] == '\#'\) \{
&nbsp;            while \(\*PL\_regcomp\_parse && \*PL\_regcomp\_parse \!= '\)'\)
&nbsp;            PL\_regcomp\_parse\+\+;
&nbsp;            PL\_regcomp\_parse\+\+;
&nbsp;    S\_reg          \[regcomp\.c&#8203;:1791\]
&nbsp;                FAIL\("Eval\-group in insecure regular expression"\);
&nbsp;            \}
&nbsp;    
 =>         nextchar\(\);
&nbsp;            if \(logical\) \{
&nbsp;                ret = reg\_node\(LOGICAL\);
&nbsp;                if \(\!SIZE\_ONLY\)
&nbsp;    S\_regatom      \[regcomp\.c&#8203;:2297\]
&nbsp;        break;
&nbsp;        case '\('&#8203;:
&nbsp;        nextchar\(\);
 =>     ret = reg\(1\, &flags\);
&nbsp;        if \(ret == NULL\) \{
&nbsp;            if \(flags & TRYAGAIN\)
&nbsp;                goto tryagain;
&nbsp;    S\_regpiece     \[regcomp\.c&#8203;:2096\]
&nbsp;        I32 min;
&nbsp;        I32 max = REG\_INFTY;
&nbsp;    
 =>     ret = regatom\(&flags\);
&nbsp;        if \(ret == NULL\) \{
&nbsp;        if \(flags & TRYAGAIN\)
&nbsp;            \*flagp |= TRYAGAIN;
&nbsp;    S\_regbranch    \[regcomp\.c&#8203;:2044\]
&nbsp;        nextchar\(\);
&nbsp;        while \(PL\_regcomp\_parse \< PL\_regxend && \*PL\_regcomp\_parse \!= '|' &&
\*PL\_regcomp\_parse \!= '\)'\) \{
&nbsp;        flags &= ~TRYAGAIN;
 =>     latest = regpiece\(&flags\);
&nbsp;        if \(latest == NULL\) \{
&nbsp;            if \(flags & TRYAGAIN\)
&nbsp;            continue;
&nbsp;    S\_reg          \[regcomp\.c&#8203;:1902\]
&nbsp;        ret = NULL;
&nbsp;                
&nbsp;                    /\* Pick up the branches\, linking them together\. \*/
&nbsp;             =>     br = regbranch\(&flags\, 1\);
&nbsp;                    if \(br == NULL\)
&nbsp;                    return\(NULL\);
&nbsp;                    if \(\*PL\_regcomp\_parse == '|'\) \{
&nbsp;            Perl\_pregcomp  \[regcomp\.c&#8203;:1415\]
&nbsp;                    PL\_regcode\->next\_off = \(\(PL\_seen\_evals > U16\_MAX\) ?
U16\_MAX : PL\_seen\_evals\);
&nbsp;                    REGC\(\(U8\)REG\_MAGIC\, \(char\*\) PL\_regcode\+\+\);
&nbsp;                    r\->data = 0;
&nbsp;             =>     if \(reg\(0\, &flags\) == NULL\)
&nbsp;                    return\(NULL\);
&nbsp;                
&nbsp;                    /\* Dig out information for optimizations\. \*/
&nbsp;            Perl\_pmruntime \[op\.c&#8203;:2859\]
&nbsp;                    \}
&nbsp;                    if \(\(PL\_hints & HINT\_UTF8\) || \(SvUTF8\(pat\) && \!\(PL\_hints
& HINT\_BYTE\)\)\)
&nbsp;                        pm\->op\_pmdynflags |= PMdf\_UTF8;
&nbsp;             =>     pm\->op\_pmregexp = CALLREGCOMP\(aTHX\_ p\, p \+ plen\, pm\);
&nbsp;                    if \(strEQ\("\\\\s\+"\, pm\->op\_pmregexp\->precomp\)\)
&nbsp;                        pm\->op\_pmflags |= PMf\_WHITE;
&nbsp;                    op\_free\(expr\);
&nbsp;            unknown\_function \[perly\.y&#8203;:650\]
&nbsp;                    |    PMFUNC '\(' term '\)'
&nbsp;                            \{ $$ = pmruntime\($1\, $3\, Nullop\); \}
&nbsp;                    |    PMFUNC '\(' term '\,' term '\)'
&nbsp;             =>             \{ $$ = pmruntime\($1\, $3\, $5\); \}
&nbsp;                    |    WORD
&nbsp;                    |    listop
&nbsp;                    ;
&nbsp;            S\_parse\_body   \[perl\.c&#8203;:1249\]
&nbsp;                
&nbsp;                    SETERRNO\(0\,SS$\_NORMAL\);
&nbsp;                    PL\_error\_count = 0;
&nbsp;             =>     if \(yyparse\(\) || PL\_error\_count\) \{
&nbsp;                    if \(PL\_minus\_c\)
&nbsp;                        Perl\_croak\(aTHX\_ "%s had compilation errors\.\\n"\,
PL\_origfilename\);
&nbsp;                    else \{
\[E\] ABW&#8203;: Array bounds write in S\_reganode \{1 occurrence\}

**Comment by p5pRT** [comment]
### From @simoncozens

On Tue\, Sep 12\, 2000 at 01&#8203;:15&#8203;:15PM \-0500\, Fisher Mark wrote&#8203;:
> I'm really out of my league here\, but it looks like the regex parser quit
> prematurely\.
> Take a look at the Purify trace after my \.sig\.

Please don't take this the wrong way\, and \*I\*'m way out of my league too\, but
Purify traces are sometimes not very helpful\. I'm afraid you're about to
be subjected to a "how to debug Perl"\. 

Let's see where gdb gets us\.



---
GNU gdb 5\.0
Copyright 2000 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and you are
welcome to change it and/or distribute copies of it under certain conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for details\.
This GDB was configured as "i686\-pc\-linux\-gnu"\.\.\.
\(gdb\) run \-e '$\_ = "foo";s/f\(?\{s\!o\!o\!\}\)/f/;'
Starting program&#8203;: /home/simon/patchbay/bleadperl/\./microperl \-e '$\_ = "foo";s/f\(?\{s\!o\!o\!\}\)/f/;'

Program received signal SIGSEGV\, Segmentation fault\.
0x80cbb0d in S\_regmatch \(prog=0x81232cc\) at regexec\.c&#8203;:2370
2370                PL\_op = \(OP\_4tree\*\)PL\_regdata\->data\[n\];


---
Hmm\, OK\. I'll bet "n" is some crazy number and we're walking off the end
of the array\. 



---
\(gdb\) print n
$1 = 0


---
Oh\, well\. It was a guess\. What's PL\_regdata?



---
\(gdb\) print PL\_regdata
$2 = \(struct reg\_data \*\) 0x0


---
That's pointing to nothing\. Aha\. \*WHY\* is that pointing to nothing? How did
we get here?



---
\(gdb\) bt
\#0  0x80cbb0d in S\_regmatch \(prog=0x81232cc\) at regexec\.c&#8203;:2370
\#1  0x80c9df1 in S\_regtry \(prog=0x8123290\, startpos=0x8123480 "foo"\)
&nbsp;    at regexec\.c&#8203;:1783
\#2  0x80c9440 in Perl\_regexec\_flags \(prog=0x8123290\,
&nbsp;    stringarg=0x8123480 "foo"\, strend=0x8123483 ""\, strbeg=0x8123480 "foo"\,
&nbsp;    minend=0\, sv=0x811f620\, data=0x0\, flags=2\) at regexec\.c&#8203;:1561


---
Well\, I'd be tempted to stop things at S\_regtry and step it through to
see what's happening to PL\_regdata\, but first let's have a look around
S\_regmatch&#8203;:



---
\(gdb\) list
2365                COP \*ocurcop = PL\_curcop;
2366                SV \*\*ocurpad = PL\_curpad;
2367                SV \*ret;
2368
2369                n = ARG\(scan\);
2370                PL\_op = \(OP\_4tree\*\)PL\_regdata\->data\[n\];
2371                DEBUG\_r\( PerlIO\_printf\(Perl\_debug\_log\, "  re\_eval 0x%"UVxf"\\n"\, PTR2UV\(PL\_op\)\) \);
2372                PL\_curpad = AvARRAY\(\(AV\*\)PL\_regdata\->data\[n \+ 2\]\);
2373                PL\_regendp\[0\] = PL\_reg\_magic\->mg\_len = locinput \- PL\_bostr;
2374


---
Nothing much we can glean from this; PL\_regdata is a global variable \(the
PL\_ prefix tells us that\) and it hasn't been manipulated in this function\,
so the breakage is further up\. We could try the same examination for S\_regtry\,
but PL\_regdata isn't used in that function either\.

First\, though\, where are we\, and what are we doing? Why are we using 
PL\_regdata? If you look a little further up\, you'll see we're in case EVAL
of our regular expression matching code\. So\, we expect that PL\_regdata
should contain some kind of data about the thing to eval\. But it doesn't\.

Why not? I'd guess it's because the second regexp\, s\!o\!o\! is wiping out
the data\, and PL\_regdata isn't being restored because the regexp engine 
isn't re\-entrant\. Oh boy\. Let's step through the compilation and see
what's going on\.



---
\(gdb\) break Perl\_pregcomp
Breakpoint 3 at 0x80bc0c7&#8203;: file regcomp\.c\, line 1516\.
\(gdb\) run \-e '$\_ = "foo";s/f\(?\{s\!o\!o\!\}\)/f/;'
The program being debugged has been started already\.
Start it from the beginning? \(y or n\) y

Starting program&#8203;: /home/simon/patchbay/bleadperl/\./microperl \-e '$\_ = "foo";s/f\(?\{s\!o\!o\!\}\)/f/;'

Breakpoint 3\, Perl\_pregcomp \(exp=0x8123210 "f\(?\{s\!o\!o\!\}\)"\, xend=0x812321c ""\,
&nbsp;    pm=0x8129b48\) at regcomp\.c&#8203;:1516
1516        I32 minlen = 0;


---
After stepping through\, we find that we eventually build up an SV containing
"s\!o\!o\!" and we do this&#8203;:



---
\(gdb\) step
1966                        rop = sv\_compile\_2op\(sv\, &sop\, "re"\, &av\);


---
OK\, it's going to get really hairy here soon\. However\, looking on a little\,
the next thing we do is actually add the data&#8203;:



---
1968                        n = add\_data\(3\, "nop"\);
1969                        PL\_regcomp\_rx\->data\->data\[n\] = \(void\*\)rop;
1970                        PL\_regcomp\_rx\->data\->data\[n\+1\] = \(void\*\)sop;
1971                        PL\_regcomp\_rx\->data\->data\[n\+2\] = \(void\*\)av;


---
So the data gets there fine\. No\, hang on \- the data gets \*somewhere\*
fine\. 



---
\(gdb\) run \-e '$\_ = "foo";s/f\(?\{s\!o\!o\!\}\)/f/;'
Starting program&#8203;: /home/simon/patchbay/bleadperl/\./microperl \-e '$\_ = "foo";s/f\(?\{s\!o\!o\!\}\)/f/;'

Breakpoint 1\, S\_reg \(paren=123\, flagp=0xbffff454\) at regcomp\.c&#8203;:1966
1966                        rop = sv\_compile\_2op\(sv\, &sop\, "re"\, &av\);
\(gdb\) print PL\_regcomp\_rx
$1 = \(regexp \*\) 0x8123290
\(gdb\) next
1968                        n = add\_data\(3\, "nop"\);
\(gdb\) print PL\_regcomp\_rx
$2 = \(regexp \*\) 0x812a868


---
Aha\! It's being added to the \*other\* regexp\, as we can check&#8203;:



---
\(gdb\) print \*PL\_regcomp\_rx
$3 = \{startp = 0x812a818\, endp = 0x812b150\, regstclass = 0x0\,
&nbsp;  substrs = 0x812a8b8\, precomp = 0x81292c8 "o"\, data = 0x0\, subbeg = 0x0\,
&nbsp;  sublen = 0\, refcnt = 1\, minlen = 1\, prelen = 1\, nparens = 0\, lastparen = 0\,
&nbsp;  reganch = 3145984\, program = \{\{flags = 156 '\\234'\, type = 0 '\\000'\,
&nbsp;      next\_off = 0\}\}\}


---
See that "precomp" is "o"? That tells me it's the s\!o\!o\! part\, not the 
s/f\{voodoo\}//

Right\. Bletch\. So\, here's the bug&#8203;: we're merrily compiling a regexp into
a global variable\, and we head off and do something which changes that
global variable\. Then we carry on as if nothing had happened\, and Perl
gets confused\.

How do we fix this? We need a good way of squirreling away the stuff
we're working on while we go into the eval\, just in case something like
this happens\. So\, PL\_regcomp\_rx on the save stack before entering the
eval and restore it afterwards\.

And that's left as an exercise\. :\)

**Comment by p5pRT** [comment]
### From @vanstyn

In \<20000911065324\.21688\.qmail@&#8203;foad\.org>\, abigail@&#8203;foad\.org writes&#8203;:
:This is a bug report for perl from abigail@&#8203;foad\.org\,
:generated with the help of perlbug 1\.28 running under perl v5\.6\.0\.
:
:
:\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
:\[Please enter your report here\]
:
:    \#\!/opt/perl/bin/perl \-wl
:
:    use strict;
:    $\_ = "foo";   
:    s/f\(?\{s\!o\!o\!\}\)/f/;
:    \_\_END\_\_
:    Segmentation fault
:
:Perl 5\.7\.0 segfaults too\.

The regexp engine is not reentrant\. Coredumps will happen\, I'm
afraid\. One day someone might fix that\.

Hugo

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Simon Cozens wrote&#8203;:
>Please don't take this the wrong way\, and \*I\*'m way out of my league too\,
but
>Purify traces are sometimes not very helpful\. I'm afraid you're about to
>be subjected to a "how to debug Perl"\. 
>
>Let's see where gdb gets us\.

Not taken the wrong way at all\.  The Purify traces have just been my way to
dip my toes in the water\, as it were\, of Perl debugging\.  I'm finally
starting to feel confident enough that I wouldn't be wasting my employer's
time by firing up xdb or Visual C\+\+ on Perl when it segfaults\.
===============================================
Mark Leighton Fisher            fisherm@&#8203;tce\.com
Thomson Consumer Electronics    Indianapolis IN
"Display some adaptability\." \-\- Doug Shaftoe\, \_Cryptonomicon\_

**Comment by p5pRT** [comment]
@abigail - Status changed from 'open' to 'resolved'
