### ISSUE TITLE
Lexical variables in regex code blocks not propagated (SEGFAULT)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#2683]
Migrated from [rt.perl.org#4383](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=4383) (status was 'resolved')

Searchable as RT4383$

**Comment by p5pRT** [comment]
### From @tux

\-\-8\<\-\-\-
\# cat re\.pl
\#\!/usr/bin/perl \-w

use strict;

my %hash = \(
&nbsp;    old => \{
&nbsp;        Data    => \[ "Date=05 Oct 2000\, 15&#8203;:17"\, "Version=1\.00" \]\,
&nbsp;        Version => "0\.00"\,
&nbsp;        Date    => "01 Jan 1970\, 00&#8203;:00"\,
&nbsp;        \}\,
&nbsp;    new => \{
&nbsp;        Data    => \[ "Date=05 Oct 2000\, 13&#8203;:11"\, "Version=0\.07" \]\,
&nbsp;        Version => "0\.00"\,
&nbsp;        Date    => "01 Jan 1970\, 00&#8203;:00"\,
&nbsp;        \}\,
&nbsp;    \);

print "\\n=== Extract lexical\\n";
foreach my $h \(qw\( old new \)\) \{
&nbsp;    grep m/^\(?\{print "$\_\\n"\}\)
&nbsp;            \(Date|Version\)=\(\.\*\)
&nbsp;            \(?\{ $hash\{$h\}\{$1\} = $2 \}\)/x => @&#8203;\{$hash\{$h\}\{Data\}\};
&nbsp;    \}

print "=== Report\\n";
foreach my $h \(qw\( old new \)\) \{
&nbsp;    foreach my $k \(qw\( Date Version \)\) \{
&nbsp;        print join \("\." => $h\, $k\, $hash\{$h\}\{$k\}\)\, "\\n";
&nbsp;        \}
&nbsp;    \}

print "\\n=== Extract global\\n";
use vars qw\($h\);
foreach $h \(qw\( old new \)\) \{
&nbsp;    grep m/^\(?\{print "$\_\\n"\}\)
&nbsp;            \(Date|Version\)=\(\.\*\)
&nbsp;            \(?\{ $hash\{$h\}\{$1\} = $2 \}\)/x => @&#8203;\{$hash\{$h\}\{Data\}\};
&nbsp;    \}

print "=== Report\\n";
foreach $h \(qw\( old new \)\) \{
&nbsp;    foreach my $k \(qw\( Date Version \)\) \{
&nbsp;        print join \("\." => $h\, $k\, $hash\{$h\}\{$k\}\)\, "\\n";
&nbsp;        \}
&nbsp;    \}
\# perl5\.7\.0 re\.pl

=== Extract lexical
Date=05 Oct 2000\, 15&#8203;:17
Use of uninitialized value in hash element at \(re\_eval 2\) line 1\.
Use of uninitialized value in hash element at \(re\_eval 2\) line 1\.
Version=1\.00
Use of uninitialized value in hash element at \(re\_eval 2\) line 1\.
Date=05 Oct 2000\, 13&#8203;:11
Use of uninitialized value in hash element at \(re\_eval 2\) line 1\.
Version=0\.07
Use of uninitialized value in hash element at \(re\_eval 2\) line 1\.
=== Report
old\.Date\.01 Jan 1970\, 00&#8203;:00
old\.Version\.0\.00
new\.Date\.01 Jan 1970\, 00&#8203;:00
new\.Version\.0\.00

=== Extract global
Date=05 Oct 2000\, 15&#8203;:17
Version=1\.00
Date=05 Oct 2000\, 13&#8203;:11
Version=0\.07
=== Report
old\.Date\.05 Oct 2000\, 15&#8203;:17
old\.Version\.1\.00
new\.Date\.05 Oct 2000\, 13&#8203;:11
new\.Version\.0\.07
\#
\-\->8\-\-\-

where it proves that a lexical $h isn't known inside \(?\{ $hash\{$h\}\{$1\} = $2 \}\)
where the global \(localized by foreach\) $h is\.

\# perl5\.7\.0 \-V
Summary of my perl5 \(revision 5\.0 version 7 subversion 0\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=hpux\, osvers=11\.00\, archname=PA\-RISC2\.0
&nbsp;    uname='hp\-ux l1 b\.11\.00 u 9000800 527706567 unlimited\-user license '
&nbsp;    config\_args='\-ds'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
&nbsp;    useperlio=undef d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags =' \-DDEBUGGING \-Ae \-D\_HPUX\_SOURCE \-I/pro/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 '\,
&nbsp;    optimize='\+O2 \+Onolimit'\,
&nbsp;    cppflags='\-DDEBUGGING \-Ae \-D\_HPUX\_SOURCE \-I/pro/local/include'
&nbsp;    ccversion='A\.11\.01\.21505\.GP'\, gccversion=''\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=4321
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, usemymalloc=y\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ld'\, ldflags ='\-L/pro/local/lib \-Wl\,\+vnocompatwarnings'
&nbsp;    libpth=/pro/local/lib /lib /usr/lib /usr/ccs/lib /usr/local/lib
&nbsp;    libs=\-lnsl \-lnm \-lndbm \-lgdbm \-ldb \-ldld \-lm \-lc \-lndir \-lcrypt \-lsec
&nbsp;    libc=/lib/libc\.sl\, so=sl\, useshrplib=false\, libperl=libperl\.a
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_hpux\.xs\, dlext=sl\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E \-Wl\,\-B\,deferred '
&nbsp;    cccdlflags='\+z'\, lddlflags='\-b \+vnocompatwarnings \-L/pro/local/lib'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: DEBUGGING USE\_LARGE\_FILES
&nbsp;  Locally applied patches&#8203;:
&nbsp;        DEVEL7149
&nbsp;  Built under hpux
&nbsp;  Compiled at Oct  5 2000 11&#8203;:47&#8203;:16
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /pro/lib/perl5/5\.7\.0/PA\-RISC2\.0
&nbsp;    /pro/lib/perl5/5\.7\.0
&nbsp;    /pro/lib/perl5/site\_perl/5\.7\.0/PA\-RISC2\.0
&nbsp;    /pro/lib/perl5/site\_perl/5\.7\.0
&nbsp;    /pro/lib/perl5/site\_perl/5\.005/PA\-RISC2\.0
&nbsp;    /pro/lib/perl5/site\_perl/5\.005
&nbsp;    /pro/lib/perl5/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @vanstyn

In \<20001005152535\.33DD\.H\.M\.BRAND@&#8203;hccnet\.nl>\, "H\.Merijn Brand" writes&#8203;:
\[\.\.\.\]
:where it proves that a lexical $h isn't known inside \(?\{ $hash\{$h\}\{$1\} = $2 \}\)
:where the global \(localized by foreach\) $h is\.

Thanks for the report\. This is a known problem\, and on my list\. :\(
The primary problem\, I think\, is that it is not well defined how
lexicals in re\_eval blocks should be looked up \- I have had some
discussion with Sarathy about this\. He noted in particular that
sv\_compile\_2op has no clearly defined scratchpad associated with
the compiled tree\, which violates assumptions made by the rest of
perl\. He suggested it must have a well\-defined scratchpad that&#8203;:
\- is associated with it for its entire lifetime
\- does not violate any assumptions made in the pad\_\*\(\) functions
&nbsp;  about a scratchpad having an associated array of names that
&nbsp;  doesn't grow at runtime
\- has a PL\_curpad that is stable \(i\.e\. it can't "go away" before
&nbsp;  the body of code compiles and subsequently executes\)
\- is capable of supporting recursion of the optree associated with
&nbsp;  it \(i\.e\. it is a stacked array of arrays\)
\- is capable of being cloned when appropriate \(just like any pad
&nbsp;  associated with anon\-CVs and any thing "callable" is\)
\- and possibly more

Sarathy&#8203;: \<\<
&nbsp;  One approach to fixing it would be to either make it more like a
pure subroutine\, or like a pure eval"" \(depending on whichever semantic
is more appropriate for \(?\{\.\.\.\}\)\.  I'm inclined towards the former\.
>>

A particularly difficult aspect of the problem\, however\, is the
question of when the regexp \(or fragment\) is compiled\. In code such
as this&#8203;:

&nbsp;  our $a = 1;
&nbsp;  my $re;
&nbsp;  \{
&nbsp;    my $a = 2;
&nbsp;    $re = qr\{\(?\{ print $a \}\)\(??\{ $a \}\)\};
&nbsp;  \}
&nbsp;  \{
&nbsp;    my $a = 3;
&nbsp;    "123" =~ $re and print $&;
&nbsp;    "123" =~ /\($re\)/ and print $1;
&nbsp;  \}

\.\. it is not at all clear to me what results we should expect\, only
that we ain't there yet\.

Hugo

**Comment by p5pRT** [comment]
### From @tux

On Thu 05 Oct 2000 16&#8203;:26\, Hugo \<hv@&#8203;crypt\.compulink\.co\.uk> wrote&#8203;:
> In \<20001005152535\.33DD\.H\.M\.BRAND@&#8203;hccnet\.nl>\, "H\.Merijn Brand" writes&#8203;:
> \[\.\.\.\]
> :where it proves that a lexical $h isn't known inside \(?\{ $hash\{$h\}\{$1\} = $2 \}\)
> :where the global \(localized by foreach\) $h is\.
> 
> Thanks for the report\. This is a known problem\, and on my list\. :\(

Solved before 5\.8?
Still on your list?
My latest blead still complains\, and there are several bug reports 'bout this
in bugtron

> The primary problem\, I think\, is that it is not well defined how
> lexicals in re\_eval blocks should be looked up \- I have had some
> discussion with Sarathy about this\. He noted in particular that
> sv\_compile\_2op has no clearly defined scratchpad associated with
> the compiled tree\, which violates assumptions made by the rest of
> perl\. He suggested it must have a well\-defined scratchpad that&#8203;:
> \- is associated with it for its entire lifetime
> \- does not violate any assumptions made in the pad\_\*\(\) functions
>   about a scratchpad having an associated array of names that
>   doesn't grow at runtime
> \- has a PL\_curpad that is stable \(i\.e\. it can't "go away" before
>   the body of code compiles and subsequently executes\)
> \- is capable of supporting recursion of the optree associated with
>   it \(i\.e\. it is a stacked array of arrays\)
> \- is capable of being cloned when appropriate \(just like any pad
>   associated with anon\-CVs and any thing "callable" is\)
> \- and possibly more
> 
> Sarathy&#8203;: \<\<
>   One approach to fixing it would be to either make it more like a
> pure subroutine\, or like a pure eval"" \(depending on whichever semantic
> is more appropriate for \(?\{\.\.\.\}\)\.  I'm inclined towards the former\.
> >>
> 
> A particularly difficult aspect of the problem\, however\, is the
> question of when the regexp \(or fragment\) is compiled\. In code such
> as this&#8203;:
> 
>   our $a = 1;
>   my $re;
>   \{
>     my $a = 2;
>     $re = qr\{\(?\{ print $a \}\)\(??\{ $a \}\)\};
>   \}
>   \{
>     my $a = 3;
>     "123" =~ $re and print $&;
>     "123" =~ /\($re\)/ and print $1;
>   \}
> 
> \.\. it is not at all clear to me what results we should expect\, only
> that we ain't there yet\.
> 
> Hugo

\-\- 
H\.Merijn Brand        Amsterdam Perl Mongers \(http&#8203;://amsterdam\.pm\.org/\)
using perl\-5\.6\.1\, 5\.7\.2 & 631 on HP\-UX 10\.20 & 11\.00\, AIX 4\.2\, AIX 4\.3\,
&nbsp;  WinNT 4\, Win2K pro & WinCE 2\.11\.  Smoking perl CORE&#8203;: smokers@&#8203;perl\.org
http&#8203;://archives\.develooper\.com/daily\-build@&#8203;perl\.org/   perl\-qa@&#8203;perl\.org
send smoke reports to&#8203;: smokers\-reports@&#8203;perl\.org\, QA&#8203;: http&#8203;://qa\.perl\.org

**Comment by p5pRT** [comment]
### From @vanstyn

"H\.Merijn Brand" \<h\.m\.brand@&#8203;hccnet\.nl> wrote&#8203;:
:On Thu 05 Oct 2000 16&#8203;:26\, Hugo \<hv@&#8203;crypt\.compulink\.co\.uk> wrote&#8203;:
:> In \<20001005152535\.33DD\.H\.M\.BRAND@&#8203;hccnet\.nl>\, "H\.Merijn Brand" writes&#8203;:
:> \[\.\.\.\]
:> :where it proves that a lexical $h isn't known inside \(?\{ $hash\{$h\}\{$1\} = $2 \}\)
:> :where the global \(localized by foreach\) $h is\.
:> 
:> Thanks for the report\. This is a known problem\, and on my list\. :\(
:
:Solved before 5\.8?

Unlikely\, now\.

:Still on your list?

Yes\. Volunteers welcome\, though\. :\)

Hugo

**Comment by p5pRT** [comment]
### From @tux

On Wed 27 Feb 2002 21&#8203;:38\, Hugo van der Sanden \<hv@&#8203;crypt\.compulink\.co\.uk> wrote&#8203;:
> "H\.Merijn Brand" \<h\.m\.brand@&#8203;hccnet\.nl> wrote&#8203;:
> :On Thu 05 Oct 2000 16&#8203;:26\, Hugo \<hv@&#8203;crypt\.compulink\.co\.uk> wrote&#8203;:
> :> In \<20001005152535\.33DD\.H\.M\.BRAND@&#8203;hccnet\.nl>\, "H\.Merijn Brand" writes&#8203;:
> :> \[\.\.\.\]
> :> :where it proves that a lexical $h isn't known inside \(?\{ $hash\{$h\}\{$1\} = $2 \}\)
> :> :where the global \(localized by foreach\) $h is\.
> :> 
> :> Thanks for the report\. This is a known problem\, and on my list\. :\(
> :
> :Solved before 5\.8?
> 
> Unlikely\, now\.
> 
> :Still on your list?
> 
> Yes\. Volunteers welcome\, though\. :\)

If I wave my hands any faster I will lift off

> Hugo

\-\- 
H\.Merijn Brand        Amsterdam Perl Mongers \(http&#8203;://amsterdam\.pm\.org/\)
using perl\-5\.6\.1\, 5\.7\.2 & 631 on HP\-UX 10\.20 & 11\.00\, AIX 4\.2\, AIX 4\.3\,
&nbsp;  WinNT 4\, Win2K pro & WinCE 2\.11\.  Smoking perl CORE&#8203;: smokers@&#8203;perl\.org
http&#8203;://archives\.develooper\.com/daily\-build@&#8203;perl\.org/   perl\-qa@&#8203;perl\.org
send smoke reports to&#8203;: smokers\-reports@&#8203;perl\.org\, QA&#8203;: http&#8203;://qa\.perl\.org

**Comment by p5pRT** [comment]
### From @smpeters

> \[hmbrand \- Wed Oct 04 23&#8203;:48&#8203;:50 2000\]&#8203;:
> 
> \-\-8\<\-\-\-
> \# cat re\.pl
> \#\!/usr/bin/perl \-w
> 
> use strict;
> 
> my %hash = \(
>     old => \{
>         Data    => \[ "Date=05 Oct 2000\, 15&#8203;:17"\, "Version=1\.00" \]\,
>         Version => "0\.00"\,
>         Date    => "01 Jan 1970\, 00&#8203;:00"\,
>         \}\,
>     new => \{
>         Data    => \[ "Date=05 Oct 2000\, 13&#8203;:11"\, "Version=0\.07" \]\,
>         Version => "0\.00"\,
>         Date    => "01 Jan 1970\, 00&#8203;:00"\,
>         \}\,
>     \);
> 
> print "\\n=== Extract lexical\\n";
> foreach my $h \(qw\( old new \)\) \{
>     grep m/^\(?\{print "$\_\\n"\}\)
>             \(Date|Version\)=\(\.\*\)
>             \(?\{ $hash\{$h\}\{$1\} = $2 \}\)/x => @&#8203;\{$hash\{$h\}\{Data\}\};
>     \}
> 
> print "=== Report\\n";
> foreach my $h \(qw\( old new \)\) \{
>     foreach my $k \(qw\( Date Version \)\) \{
>         print join \("\." => $h\, $k\, $hash\{$h\}\{$k\}\)\, "\\n";
>         \}
>     \}
> 
> print "\\n=== Extract global\\n";
> use vars qw\($h\);
> foreach $h \(qw\( old new \)\) \{
>     grep m/^\(?\{print "$\_\\n"\}\)
>             \(Date|Version\)=\(\.\*\)
>             \(?\{ $hash\{$h\}\{$1\} = $2 \}\)/x => @&#8203;\{$hash\{$h\}\{Data\}\};
>     \}
> 
> print "=== Report\\n";
> foreach $h \(qw\( old new \)\) \{
>     foreach my $k \(qw\( Date Version \)\) \{
>         print join \("\." => $h\, $k\, $hash\{$h\}\{$k\}\)\, "\\n";
>         \}
>     \}
> \# perl5\.7\.0 re\.pl
> 
> === Extract lexical
> Date=05 Oct 2000\, 15&#8203;:17
> Use of uninitialized value in hash element at \(re\_eval 2\) line 1\.
> Use of uninitialized value in hash element at \(re\_eval 2\) line 1\.
> Version=1\.00
> Use of uninitialized value in hash element at \(re\_eval 2\) line 1\.
> Date=05 Oct 2000\, 13&#8203;:11
> Use of uninitialized value in hash element at \(re\_eval 2\) line 1\.
> Version=0\.07
> Use of uninitialized value in hash element at \(re\_eval 2\) line 1\.
> === Report
> old\.Date\.01 Jan 1970\, 00&#8203;:00
> old\.Version\.0\.00
> new\.Date\.01 Jan 1970\, 00&#8203;:00
> new\.Version\.0\.00
> 
> === Extract global
> Date=05 Oct 2000\, 15&#8203;:17
> Version=1\.00
> Date=05 Oct 2000\, 13&#8203;:11
> Version=0\.07
> === Report
> old\.Date\.05 Oct 2000\, 15&#8203;:17
> old\.Version\.1\.00
> new\.Date\.05 Oct 2000\, 13&#8203;:11
> new\.Version\.0\.07
> \#
> \-\->8\-\-\-
> 
> where it proves that a lexical $h isn't known inside \(?\{ $hash\{$h\}\{$1\}
> = $2 \}\)
> where the global \(localized by foreach\) $h is\.
> 

I just tried this with bleadperl\, and got a coredump for my efforts\.
It appears that the unitialized variables in the regex are wreaking 
havoc on S\_varname\(\)\.  Sorry\, I don't a Perl built with \-g at the
moment\, but when I do\, I'll post the backtrace\.

**Comment by p5pRT** [comment]
### From @smpeters

> \[stmpeters \- Mon Nov 07 16&#8203;:10&#8203;:22 2005\]&#8203;:
> I just tried this with bleadperl\, and got a coredump for my efforts\.
> It appears that the unitialized variables in the regex are wreaking 
> havoc on S\_varname\(\)\.  Sorry\, I don't a Perl built with \-g at the
> moment\, but when I do\, I'll post the backtrace\.
> 
\#0  0x1c097ac6 in S\_varname \(gv=0x0\, gvtype=36 '$'\, targ=2\, keyname=0x0\, 
&nbsp;    aindex=0\, subscript\_type=1\) at sv\.c&#8203;:704
704             sv = \*av\_fetch\(av\, targ\, FALSE\);
\(gdb\) bt
\#0  0x1c097ac6 in S\_varname \(gv=0x0\, gvtype=36 '$'\, targ=2\, keyname=0x0\, 
&nbsp;    aindex=0\, subscript\_type=1\) at sv\.c&#8203;:704
\#1  0x1c097f58 in S\_find\_uninit\_var \(obase=0x7ff4aa80\,
uninit\_sv=0x82e60130\, 
&nbsp;    match=0 '\\0'\) at sv\.c&#8203;:812
\#2  0x1c098172 in S\_find\_uninit\_var \(obase=0x7ff4aaa0\,
uninit\_sv=0x82e60130\, 
&nbsp;    match=0 '\\0'\) at sv\.c&#8203;:864
\#3  0x1c098825 in Perl\_report\_uninit \(uninit\_sv=0x82e60130\) at sv\.c&#8203;:1056
\#4  0x1c09cd70 in Perl\_sv\_2pv\_flags \(sv=0x82e60130\, lp=0xcfbf864c\, flags=34\)
&nbsp;    at sv\.c&#8203;:3214
\#5  0x1c08465d in S\_hv\_fetch\_common \(hv=0x7da00ea0\, keysv=0x82e60130\,
key=0x0\, 
&nbsp;    klen=0\, flags=0\, action=4\, val=0x0\, hash=0\) at hv\.c&#8203;:433
\#6  0x1c0845e9 in Perl\_hv\_fetch\_ent \(hv=0x7da00ea0\, keysv=0x82e60130\,
lval=1\, 
&nbsp;    hash=0\) at hv\.c&#8203;:411
\#7  0x1c091502 in Perl\_pp\_helem \(\) at pp\_hot\.c&#8203;:1711
\#8  0x1c0757bf in Perl\_runops\_debug \(\) at dump\.c&#8203;:1597
\#9  0x1c0f5623 in S\_regmatch \(prog=0x852a8394\) at regexec\.c&#8203;:3213
\#10 0x1c0f90e0 in S\_regmatch \(prog=0x852a8374\) at regexec\.c&#8203;:4131
\#11 0x1c0f374c in S\_regmatch \(prog=0x852a8344\) at regexec\.c&#8203;:2734
\#12 0x1c0f1f58 in S\_regtry \(prog=0x852a8300\, 
&nbsp;    startpos=0x7ff4aa00 "Date=05 Oct 2000\, 15&#8203;:17"\) at regexec\.c&#8203;:2223
\#13 0x1c0f06a2 in Perl\_regexec\_flags \(prog=0x852a8300\, 
&nbsp;    stringarg=0x7ff4aa00 "Date=05 Oct 2000\, 15&#8203;:17"\, strend=0x7ff4aa17 ""\, 
&nbsp;    strbeg=0x7ff4aa00 "Date=05 Oct 2000\, 15&#8203;:17"\, minend=0\, sv=0x7da002f0\,
&nbsp;    data=0x0\, flags=3\) at regexec\.c&#8203;:1764
\#14 0x1c08fbb0 in Perl\_pp\_match \(\) at pp\_hot\.c&#8203;:1298
\#15 0x1c0757bf in Perl\_runops\_debug \(\) at dump\.c&#8203;:1597
\#16 0x1c01a748 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2298
\#17 0x1c01a2dd in perl\_run \(my\_perl=0x8b444030\) at perl\.c&#8203;:2225
\#18 0x1c015bf3 in main \(argc=2\, argv=0xcfbf923c\, env=0xcfbf9248\)
&nbsp;    at perlmain\.c&#8203;:103

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Nov 07\, 2005 at 04&#8203;:14&#8203;:46PM \-0800\, Steve Peters via RT wrote&#8203;:
> > \[stmpeters \- Mon Nov 07 16&#8203;:10&#8203;:22 2005\]&#8203;:
> > I just tried this with bleadperl\, and got a coredump for my efforts\.
> > It appears that the unitialized variables in the regex are wreaking 
> > havoc on S\_varname\(\)\.  Sorry\, I don't a Perl built with \-g at the
> > moment\, but when I do\, I'll post the backtrace\.

I think this another instance of "lexical in re\_evals are borked"\. I'll
add it to my list of things to check one I've fixed that\.

\-\- 
The Enterprise's efficient long\-range scanners detect a temporal vortex
distortion in good time\, allowing it to be safely avoided via a minor
course correction\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#21

**Comment by p5pRT** [comment]
### From @cpansprout

This has been fixed by the commits leading up to eb58a7e122\.

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
