### ISSUE TITLE
core dump (5.6.0, using several modules)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#2810]
Migrated from [rt.perl.org#4611](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=4611) (status was 'rejected')

Searchable as RT4611$

**Comment by p5pRT** [comment]
### From root@caffeine.contactdesigns.com

#### Created by scottw@contactdesigns.com



Perl violates segmentation\. Ooops\. Perl 5\.6\.0\,RedHat Linux x86\.
Code that caused this was ment for mod\_perl\, but has always 
passed syntax tests with \-c\, or errored out with \-e when the
mod\_perl request object was undefined\. 
Additionally\, DBI\, Mail&#8203;::Sendmail\, LWP are used\.

\(notes about code that caused condition\)
The code that caused this condition is pretty involved\. Lots of
namespace minipulation and general Perl trickery\. Spread
accrost several modules\. \(Comprises our custom object
framework and shoppingcart/category/admin etc\)\. Debugging
modules grab the warn and die SIG handlers\. Most functions are
generated from templates using lambdas\. All functions are
replaced with stubs that record evaluation path and use 
goto &$funcref to replace the original function in the stack frame\.

"medium" priority because other people are unlikely to stumble upon
this crasher ;\)

Thank you for your hard work on Perl\.\.\. Perl is da' bomb =\)

\-scott


\(gdb perl
set args \-e 'use Transexual;'
run\)

Program received signal SIGSEGV\, Segmentation fault\.
0x80a293c in Perl\_sv\_setsv \(\)
\(gdb\) bt
\#0  0x80a293c in Perl\_sv\_setsv \(\)
\#1  0x8098a79 in Perl\_pp\_sassign \(\)
\#2  0x809865a in Perl\_runops\_standard \(\)
\#3  0x80bd83e in Perl\_pp\_exit \(\)
\#4  0x80bd949 in Perl\_pp\_exit \(\)
\#5  0x80bfa10 in Perl\_pp\_entertry \(\)
\#6  0x809865a in Perl\_runops\_standard \(\)
\#7  0x805c8a6 in perl\_call\_sv \(\)
\#8  0x805c478 in perl\_call\_sv \(\)
\#9  0x808e1ef in Perl\_vcroak \(\)
\#10 0x808e349 in Perl\_croak \(\)
\#11 0x805f223 in Perl\_call\_list \(\)
\#12 0x8080789 in Perl\_newATTRSUB \(\)
\#13 0x807d837 in Perl\_utilize \(\)
\#14 0x8076fe4 in Perl\_yyparse \(\)
\#15 0x80bdff2 in Perl\_sv\_compile\_2op \(\)
\#16 0x80bf164 in Perl\_pp\_require \(\)
\#17 0x809865a in Perl\_runops\_standard \(\)
\#18 0x805c8a6 in perl\_call\_sv \(\)
\#19 0x805c681 in perl\_call\_sv \(\)
\#20 0x805f416 in Perl\_call\_list \(\)
\#21 0x805f116 in Perl\_call\_list \(\)
\#22 0x8080789 in Perl\_newATTRSUB \(\)
\#23 0x807d837 in Perl\_utilize \(\)
\#24 0x8076fe4 in Perl\_yyparse \(\)
\#25 0x805bb60 in perl\_parse \(\)
\#26 0x805b2e3 in perl\_parse \(\)
\#27 0x80599f9 in main \(\)
\#28 0x40074b65 in \_\_libc\_start\_main \(main=0x80599a0 \<main>\, argc=3\, ubp\_av=0xbffff844\, init=0x8058b80 \<\_init>\, 
&nbsp;    fini=0x80df51c \<\_fini>\, rtld\_fini=0x4000df24 \<\_dl\_fini>\, stack\_end=0xbffff83c\)
&nbsp;    at \.\./sysdeps/generic/libc\-start\.c&#8203;:111
\(gdb\) 

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.6.0:

Configured by prospector at Mon Aug  7 10:58:30 EDT 2000.

Summary of my perl5 (revision 5.0 version 6 subversion 0) configuration:
  Platform:
    osname=linux, osvers=2.2.5-22smp, archname=i386-linux
    uname='linux porky.devel.redhat.com 2.2.5-22smp #1 smp wed jun 2 09:11:51 edt 1999 i686 unknown '
    config_args='-des -Doptimize=-O2 -march=i386 -mcpu=i686 -Dcc=gcc -Dcccdlflags=-fPIC -Dinstallprefix=/usr -Dprefix=/usr -Darchname=i386-linux -Dd_dosuid -Dd_semctl_semun -Di_db -Di_ndbm -Di_gdbm -Di_shadow -Di_syslog -Dman3ext=3pm -Uuselargefiles'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=undef 
    use64bitint=undef use64bitall=undef uselongdouble=undef usesocks=undef
  Compiler:
    cc='gcc', optimize='-O2 -march=i386 -mcpu=i686', gccversion=2.96 20000731 (experimental)
    cppflags='-fno-strict-aliasing'
    ccflags ='-fno-strict-aliasing'
    stdchar='char', d_stdstdio=define, usevfork=false
    intsize=4, longsize=4, ptrsize=4, doublesize=8
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=4
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -ldl -lm -lc -lcrypt
    libc=/lib/libc-2.1.92.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.0:
    /usr/lib/perl5/5.6.0/i386-linux
    /usr/lib/perl5/5.6.0
    /usr/lib/perl5/site_perl/5.6.0/i386-linux
    /usr/lib/perl5/site_perl/5.6.0
    /usr/lib/perl5/site_perl
    .


Environment for perl v5.6.0:
    HOME=/root
    LANG=en_US
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/usr/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/mysql/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash


```
</details>

**Comment by p5pRT** [comment]
p5p@spam.wizbit.be - Status changed from 'open' to 'rejected'
