### ISSUE TITLE
fork() , $SIG{CHLD} on HPUX 10.20

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#3102]
Migrated from [rt.perl.org#5121](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=5121) (status was 'resolved')

Searchable as RT5121$

**Comment by p5pRT** [comment]
### From O.Flebbe@science-computing.de


\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
There was some confusion a while ago about a little script a collegue
wrote\. Its intention was to check wether a NFS mounted directory is
available\.
 
He wrote something like this&#8203;: Please note that /share/medina is a NFS
mounted directory\. 
 
This script crashes perl 5\.005\_53 most of the time when running on HPUX
10\.20\. I have some evidences that this may happen on AIX\, too\. 
 
On a local directory no problem was found\. Seems to be a timing issue\.
I added a small delay \(The commented out line\) and hoped for the best\.

The backtrace looks like

> \(gdb\) where
> \#0  0x3fbec in new\_xiv \(\)
> \#1  0x40128 in Perl\_sv\_upgrade \(\)
> \#2  0x42ea8 in Perl\_sv\_setsv \(\)
> \#3  0x6aa84 in Perl\_pp\_sassign \(\)
> \#4  0x6a408 in Perl\_runops\_standard \(\)
> \#5  0x23464 in perl\_run \(\)
> \#6  0x208a4 in main \(\)
> \#7  0xc0065594 in ?? \(\) from /usr/lib/libc\.1

As far as I can tell the new\_xiv is the assignment  to $childret\.



sub filetest \{
&nbsp;    my\($test\)     = shift;
&nbsp;    my\($file\)     = shift;

&nbsp;    local\($SIG\{CHLD\}\) = sub \{ wait; $childret = \($? >> 8\);\};

&nbsp;    $childret = 0;
&nbsp;    if\( $pid = fork \) \{

&nbsp;    $seconds = 0;

&nbsp;    \} else \{
&nbsp;        select undef\, undef\, undef\, 0\.1;
&nbsp;    $ret = \-d $file;

&nbsp;    exit $ret \+ 1;
&nbsp;    \}
\}

filetest\( "\-d"\, "/share/medina"\);

<details><summary>Perl Info</summary>

```


Site configuration information for perl 5.00503:

Configured by flebbe at Fri Aug 25 08:48:50 METDST 2000.

Summary of my perl5 (5.0 patchlevel 5 subversion 3) configuration:
  Platform:
    osname=hpux, osvers=10.20, archname=PA-RISC2.0
    uname='hp-ux io b.10.20 a 9000780 2016114561 two-user license '
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef useperlio=undef d_sfio=undef
  Compiler:
    cc='gcc', optimize='-O', gccversion=egcs-2.91.66 19990314 (egcs-1.1.2 release)
    cppflags='-D_HPUX_SOURCE -I/usr/local/include'
    ccflags ='-D_HPUX_SOURCE -I/usr/local/include'
    stdchar='unsigned char', d_stdstdio=define, usevfork=false
    intsize=4, longsize=4, ptrsize=4, doublesize=8
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=8
    alignbytes=8, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='ld', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib/pa1.1 /lib /usr/lib /usr/ccs/lib
    libs=-lnsl_s -lndbm -lgdbm -ldld -lm -lc -lndir -lcrypt
    libc=/lib/libc.sl, so=sl, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_hpux.xs, dlext=sl, d_dlsymun=undef, ccdlflags='-Wl,-E -Wl,-B,deferred '
    cccdlflags='-fpic', lddlflags='-b -L/usr/local/lib'

Locally applied patches:
    


@INC for perl 5.00503:
    /usr/local/perl5.005_03/lib/5.00503/PA-RISC2.0
    /usr/local/perl5.005_03/lib/5.00503
    /usr/local/perl5.005_03/lib/site_perl/5.005/PA-RISC2.0
    /usr/local/perl5.005_03/lib/site_perl/5.005
    .


Environment for perl 5.00503:
    HOME=/home/flebbe
    LANG=de_DE.iso88591
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/flebbe/bin/hp9000s700/HP-UX-B.10.20:/home/flebbe/bin/hp9000s700:/home/flebbe/bin:/usr/local/bin:/usr/bin:/opt/ansic/bin:/usr/ccs/bin:/usr/contrib/bin:/opt/nettladm/bin:/usr/bin/X11:/usr/contrib/bin/X11:/opt/pd/bin:/opt/upgrade/bin:/opt/aCC/bin:/opt/langtools/bin:/opt/perf/bin:/opt/java/bin:/opt/lrom/bin:/opt/graphics/OpenGL/debugger/bin:/opt/imake/bin:/opt/networker/bin:/opt/hparray/bin:/opt/fortran/bin:/usr/contrib/bin:/usr/contrib/bin/X11:/usr/dt/bin:/opt/softbench/bin:.:/usr/local/etc
    PERL_BADLANG (unset)
    SHELL=/bin/tcsh

```
</details>

**Comment by p5pRT** [comment]
### From @chorny

Can you check that this still happens with Perl 5\.12?

On Sun Jan 07 23&#8203;:54&#8203;:35 2001\, O\.Flebbe@&#8203;science\-computing\.de wrote&#8203;:
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> There was some confusion a while ago about a little script a collegue
> wrote\. Its intention was to check wether a NFS mounted directory is
> available\.
> 
> He wrote something like this&#8203;: Please note that /share/medina is a NFS
> mounted directory\.
> 
> This script crashes perl 5\.005\_53 most of the time when running on
>    HPUX
> 10\.20\. I have some evidences that this may happen on AIX\, too\.
> 
> On a local directory no problem was found\. Seems to be a timing issue\.
> I added a small delay \(The commented out line\) and hoped for the best\.
> 
> The backtrace looks like
> 
> > \(gdb\) where
> > \#0  0x3fbec in new\_xiv \(\)
> > \#1  0x40128 in Perl\_sv\_upgrade \(\)
> > \#2  0x42ea8 in Perl\_sv\_setsv \(\)
> > \#3  0x6aa84 in Perl\_pp\_sassign \(\)
> > \#4  0x6a408 in Perl\_runops\_standard \(\)
> > \#5  0x23464 in perl\_run \(\)
> > \#6  0x208a4 in main \(\)
> > \#7  0xc0065594 in ?? \(\) from /usr/lib/libc\.1
> 
> As far as I can tell the new\_xiv is the assignment  to $childret\.
> 
> 
> 
> sub filetest \{
>     my\($test\)     = shift;
>     my\($file\)     = shift;
> 
>     local\($SIG\{CHLD\}\) = sub \{ wait; $childret = \($? >> 8\);\};
> 
>     $childret = 0;
>     if\( $pid = fork \) \{
> 
>     $seconds = 0;
> 
>     \} else \{
>         select undef\, undef\, undef\, 0\.1;
>     $ret = \-d $file;
> 
>     exit $ret \+ 1;
>     \}
> \}
> 
> filetest\( "\-d"\, "/share/medina"\);
> 
> 
> 
> 
> \[Please do not change anything below this line\]
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> 
> \-\-\-
> Site configuration information for perl 5\.00503&#8203;:
> 
> Configured by flebbe at Fri Aug 25 08&#8203;:48&#8203;:50 METDST 2000\.
> 
> Summary of my perl5 \(5\.0 patchlevel 5 subversion 3\) configuration&#8203;:
>   Platform&#8203;:
>     osname=hpux\, osvers=10\.20\, archname=PA\-RISC2\.0
>     uname='hp\-ux io b\.10\.20 a 9000780 2016114561 two\-user license '
>     hint=recommended\, useposix=true\, d\_sigaction=define
>     usethreads=undef useperlio=undef d\_sfio=undef
>   Compiler&#8203;:
>     cc='gcc'\, optimize='\-O'\, gccversion=egcs\-2\.91\.66 19990314 \(egcs\-
>    1\.1\.2 release\)
>     cppflags='\-D\_HPUX\_SOURCE \-I/usr/local/include'
>     ccflags ='\-D\_HPUX\_SOURCE \-I/usr/local/include'
>     stdchar='unsigned char'\, d\_stdstdio=define\, usevfork=false
>     intsize=4\, longsize=4\, ptrsize=4\, doublesize=8
>     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=8
>     alignbytes=8\, usemymalloc=n\, prototype=define
>   Linker and Libraries&#8203;:
>     ld='ld'\, ldflags =' \-L/usr/local/lib'
>     libpth=/usr/local/lib /lib/pa1\.1 /lib /usr/lib /usr/ccs/lib
>     libs=\-lnsl\_s \-lndbm \-lgdbm \-ldld \-lm \-lc \-lndir \-lcrypt
>     libc=/lib/libc\.sl\, so=sl\, useshrplib=false\, libperl=libperl\.a
>   Dynamic Linking&#8203;:
>     dlsrc=dl\_hpux\.xs\, dlext=sl\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E
>    \-Wl\,\-B\,deferred '
>     cccdlflags='\-fpic'\, lddlflags='\-b \-L/usr/local/lib'
> 
> Locally applied patches&#8203;:
> 
> 
> \-\-\-
> @&#8203;INC for perl 5\.00503&#8203;:
>     /usr/local/perl5\.005\_03/lib/5\.00503/PA\-RISC2\.0
>     /usr/local/perl5\.005\_03/lib/5\.00503
>     /usr/local/perl5\.005\_03/lib/site\_perl/5\.005/PA\-RISC2\.0
>     /usr/local/perl5\.005\_03/lib/site\_perl/5\.005
>     \.
> 
> \-\-\-
> Environment for perl 5\.00503&#8203;:
>     HOME=/home/flebbe
>     LANG=de\_DE\.iso88591
>     LANGUAGE \(unset\)
>     LD\_LIBRARY\_PATH \(unset\)
>     LOGDIR \(unset\)
>     PATH=/home/flebbe/bin/hp9000s700/HP\-UX\-
>   
B\.10\.20&#8203;:/home/flebbe/bin/hp9000s700&#8203;:/home/flebbe/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/opt/ansic/bin&#8203;:/usr/ccs/bin&#8203;:/usr/contrib/bin&#8203;:/opt/nettladm/bin&#8203;:/usr/bin/X11&#8203;:/usr/contrib/bin/X11&#8203;:/opt/pd/bin&#8203;:/opt/upgrade/bin&#8203;:/opt/aCC/bin&#8203;:/opt/langtools/bin&#8203;:/opt/perf/bin&#8203;:/opt/java/bin&#8203;:/opt/lrom/bin&#8203;:/opt/graphics/OpenGL/debugger/bin&#8203;:/opt/imake/bin&#8203;:/opt/networker/bin&#8203;:/opt/hparray/bin&#8203;:/opt/fortran/bin&#8203;:/usr/contrib/bin&#8203;:/usr/contrib/bin/X11&#8203;:/usr/dt/bin&#8203;:/opt/softbench/bin&#8203;:\.&#8203;:/usr/local/etc
>     PERL\_BADLANG \(unset\)
>     SHELL=/bin/tcsh


\-\- 
Alexandr Ciornii\, http&#8203;://chorny\.net

**Comment by p5pRT** [comment]
### From e.pfeifer@science-computing.de

On Wed\, 14 Apr 2010\, Alexandr Ciornii wrote&#8203;:
>
> Can you check that this still happens with Perl 5\.12?

\(replying on behalf of O\.Flebbe@&#8203;science\-computing\.de\)

I no longer have a HPUX 10\.20 system available\, and I cannot replicate
the issue with 5\.12\.0 on HPUX 11\.00 and 11\.11 \(also tried with
PERL\_SIGNALS=unsafe for pre\-5\.8 behavior \- just in case\)\.

OTOH\, I cannot reproduce the issue with any other version of Perl
either now\, not even with the ancient 5\.005\_03 that did exhibit the
problem at the time \(I tried with 5\.12\.0\, 5\.10\.0\, 5\.8\.4\, 5\.6\.1\, 5\.005\_03\)\.
From this I conclude the culprit was more on the OS side\, or at least
some curious interaction of the 10\.20 system with Perl's signal
handling\.\.\.  In other words\, I guess we can consider the issue resolved\.

\-\- 
Vorstand/Board of Management&#8203;:
Dr\. Bernd Finkbeiner\, Dr\. Roland Niemeier\, 
Dr\. Arno Steitz\, Dr\. Ingrid Zech
Vorsitzender des Aufsichtsrats/
Chairman of the Supervisory Board&#8203;:
Michel Lepert
Sitz/Registered Office&#8203;: Tuebingen
Registergericht/Registration Court&#8203;: Stuttgart
Registernummer/Commercial Register No\.&#8203;: HRB 382196

**Comment by p5pRT** [comment]
### From @tux

Just testsed on HP\-UX 10\.20 with perl\-5\.8\.8

\-\-8\<\-\-\- test\.pl
\#\!/pro/bin/perl

use strict;
use warnings;

sub filetest
\{
&nbsp;    my \($test\, $file\) = @&#8203;\_;

&nbsp;    my $childret = 0;
&nbsp;    local $SIG\{CHLD\} = sub \{ wait; $childret = \($? >> 8\); \};

&nbsp;    unless \(fork\) \{
&nbsp;        select undef\, undef\, undef\, 0\.1;
&nbsp;        my $ret = \-d $file;
&nbsp;        exit $ret \+ 1;
&nbsp;        \}
&nbsp;    \}

filetest \("\-d"\, "/x1/pro"\);
\-\->8\-\-\-

$ di /x1/pro
Filesystem         Mount               Megs     Used    Avail %Used fs 
Type
x1&#8203;:/pro            /x1/pro          24576\.0  23367\.5   1146\.5  95%  nfs
$ perl test\.pl
$

Repeated that command several times\. No problem\.

Might have been NFS 1 or NFS 2 releated\.
Certainly when you mention AIX\, I remember connection over NFS from 
10\.20 to AIX\-4\.3 was a recipe for disaster\. /me blames AIX though

Closing this bug

**Comment by p5pRT** [comment]
@tux - Status changed from 'open' to 'resolved'
