### ISSUE TITLE
Excessively large set of values passed to subroutine results in    coredump

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#3118]
Migrated from [rt.perl.org#5172](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=5172) (status was 'resolved')

Searchable as RT5172$

**Comment by p5pRT** [comment]
### From @floatingatoll



\#\!\./perl

sub break \{ print $\#\_ \}
$a = 2;
break\( \(0\) x \(~0/$a\) \);

\_\_END\_\_

That code causes core dumps in 5\.00503 and perl\-current for me\.  Some of the
more interesting values of $a are 1\.\.6\, 2\*\*32\, 2\*\*35\, 2\*\*36\, 2\*\*38 \- try
them carefully\, if it doesn't core dump it'll eat RAM quickly\.

This is all under 64\-bit math\, by the way\.  For 5\.00503 \(32\-bit\)\, try 1\.\.6
for $a to get more interesting results\.

It appears I'm overflowing an Av in pp\_hot\.c \(line 2744\) called MARK;
I suppose it doesn't like being passed 2\*\*63 arguments\.  However\,
the problem exists at 

My previous PL\_modcount patch doesn't seem to affect it one way
or the other\.

Tested perl\-current with \-D and \-Uusemymalloc\, no difference between them\. 

Further testing requires sleep\.

5\.00503&#8203;:

\#0  0x807d7b8 in Perl\_repeatcpy \(\)
\#1  0x809188b in Perl\_pp\_repeat \(\)
\#2  0x80b26dd in Perl\_runops\_standard \(\)
\#3  0x80592c8 in perl\_run \(\)
\#4  0x80577df in main \(\)
\#5  0x400a89cb in \_\_libc\_start\_main \(main=0x8057770 \<main>\, argc=2\, argv=0xbffffcc4\, init=0x8056ab8 \<\_init>\, 
&nbsp;    fini=0x80b274c \<\_fini>\, rtld\_fini=0x4000ae60 \<\_dl\_fini>\, stack\_end=0xbffffcbc\)
&nbsp;    at \.\./sysdeps/generic/libc\-start\.c&#8203;:92

perl\-current \(@&#8203;8403\)&#8203;:

\#0  0x401b54a7 in memcpy \(dstpp=0x805cc08\, srcpp=0x805000c\, len=4294967292\)
at \.\./sysdeps/generic/memcpy\.c&#8203;:55
\#1  0x4008d7ed in Perl\_pp\_entersub \(my\_perl=0x804b7f8\) at pp\_hot\.c&#8203;:2744
\#2  0x4008651d in Perl\_runops\_debug \(my\_perl=0x804b7f8\) at run\.c&#8203;:53
\#3  0x40034efa in S\_run\_body \(my\_perl=0x804b7f8\, oldscope=1\) at perl\.c&#8203;:1457
\#4  0x40034b40 in perl\_run \(my\_perl=0x804b7f8\) at perl\.c&#8203;:1379
\#5  0x804949e in main \(argc=2\, argv=0xbffffcb4\, env=0xbffffcc0\) at perlmain\.c&#8203;:52

R\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.7.0:

Configured by rs at Thu Jan 11 18:09:23 PST 2001.

Summary of my perl5 (revision 5.0 version 7 subversion 0) configuration:
  Platform:
    osname=linux, osvers=2.2.14-5.0, archname=i686-linux-thread-multi-64all-ld
    uname='linux cyndi.oregonnet.com 2.2.14-5.0 #1 tue mar 7 21:07:39 est 2000 i686 unknown '
    config_args='-Dprefix=/home/rs/perl -Dusedevel -Dusethreads -Uuse5005threads -Duseithreads -Dusemultiplicity -Duseperlio -Duse64bitint -Duse64bitall -Duselongdouble -Doptimize=-O -g -Ubincompat5005 -Dusemorebits -Dusemymalloc -Duseshrplib -des'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=define use64bitall=define uselongdouble=define
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -DDEBUGGING -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O -g',
    cppflags='-D_REENTRANT -DDEBUGGING -fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='egcs-2.91.66 19990314/Linux (egcs-1.1.2 release)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long long', ivsize=8, nvtype='long double', nvsize=12, Off_t='off_t', lseeksize=8
    alignbytes=4, usemymalloc=y, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lndbm -lgdbm -ldb -ldl -lm -lpthread -lc -lposix -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lpthread -lc -lposix -lcrypt -lutil
    libc=/lib/libc-2.1.3.so, so=so, useshrplib=true, libperl=libperl.so
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic -Wl,-rpath,/home/rs/perl/lib/5.7.0/i686-linux-thread-multi-64all-ld/CORE'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    DEVEL8403


@INC for perl v5.7.0:
    /home/rs/perl/lib/5.7.0/i686-linux-thread-multi-64all-ld
    /home/rs/perl/lib/5.7.0
    /home/rs/perl/lib/site_perl/5.7.0/i686-linux-thread-multi-64all-ld
    /home/rs/perl/lib/site_perl/5.7.0
    /home/rs/perl/lib/site_perl
    .


Environment for perl v5.7.0:
    HOME=/home/rs
    LANG=en_US
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/rs/perl/bin:/usr/bin:/bin:/usr/local/bin:/usr/X11R6/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @jhi

On Fri\, Jan 12\, 2001 at 05&#8203;:27&#8203;:31AM \-0800\, rs@&#8203;oregonnet\.com wrote&#8203;:
> 
> This is a bug report for perl from rs@&#8203;cyndi\.oregonnet\.com\,
> generated with the help of perlbug 1\.33 running under perl v5\.7\.0\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> 
> \#\!\./perl
> 
> sub break \{ print $\#\_ \}
> $a = 2;
> break\( \(0\) x \(~0/$a\) \);
> 
> \_\_END\_\_
> 
> That code causes core dumps in 5\.00503 and perl\-current for me\.  Some of the
> more interesting values of $a are 1\.\.6\, 2\*\*32\, 2\*\*35\, 2\*\*36\, 2\*\*38 \- try
> them carefully\, if it doesn't core dump it'll eat RAM quickly\.
> 
> This is all under 64\-bit math\, by the way\.  For 5\.00503 \(32\-bit\)\, try 1\.\.6
> for $a to get more interesting results\.
> 
> It appears I'm overflowing an Av in pp\_hot\.c \(line 2744\) called MARK;
> I suppose it doesn't like being passed 2\*\*63 arguments\.  However\,
> the problem exists at 

There are still many explicit I32s lurking in the code\, I'm afraid\,
and MARK seems to one of them\.  Whether that should be changed to fix
the above\, errr\, feature\, is another matter\.  If you really want to
generate an array of 9E18 scalars you should have gone a\-shopping
from RAM first\.

**Comment by p5pRT** [comment]
### From @nwc10

On Fri\, Jan 12\, 2001 at 09&#8203;:00&#8203;:16AM \-0600\, Jarkko Hietaniemi wrote&#8203;:
> On Fri\, Jan 12\, 2001 at 05&#8203;:27&#8203;:31AM \-0800\, rs@&#8203;oregonnet\.com wrote&#8203;:
> > That code causes core dumps in 5\.00503 and perl\-current for me\.  Some of the

> There are still many explicit I32s lurking in the code\, I'm afraid\,
> and MARK seems to one of them\.  Whether that should be changed to fix
> the above\, errr\, feature\, is another matter\.  If you really want to
> generate an array of 9E18 scalars you should have gone a\-shopping
> from RAM first\.

Whilst I agree with the RAM shopping \(as will the RAM manufactures\, given
the current prices\) there's still&#8203;:

&nbsp;   core dumps bad\.

what's the best way to make perl issue an out of memory error?

Nicholas Clark

**Comment by p5pRT** [comment]
### From @jhi

On Fri\, Jan 12\, 2001 at 03&#8203;:06&#8203;:59PM \+0000\, Nicholas Clark wrote&#8203;:
> On Fri\, Jan 12\, 2001 at 09&#8203;:00&#8203;:16AM \-0600\, Jarkko Hietaniemi wrote&#8203;:
> > On Fri\, Jan 12\, 2001 at 05&#8203;:27&#8203;:31AM \-0800\, rs@&#8203;oregonnet\.com wrote&#8203;:
> > > That code causes core dumps in 5\.00503 and perl\-current for me\.  Some of the
> 
> > There are still many explicit I32s lurking in the code\, I'm afraid\,
> > and MARK seems to one of them\.  Whether that should be changed to fix
> > the above\, errr\, feature\, is another matter\.  If you really want to
> > generate an array of 9E18 scalars you should have gone a\-shopping
> > from RAM first\.
> 
> Whilst I agree with the RAM shopping \(as will the RAM manufactures\, given
> the current prices\) there's still&#8203;:
> 
>    core dumps bad\.

Yes\.  Maybe there could be a guard for stack growth&#8203;: if the stack
suddenly looks smaller than it used to \(meaning a wraparound happened\)\,
croak\.

> what's the best way to make perl issue an out of memory error?
>
> Nicholas Clark
