### ISSUE TITLE
malloc failure in DBD::Informix

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#3254]
Migrated from [rt.perl.org#5438](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=5438) (status was 'resolved')

Searchable as RT5438$

**Comment by p5pRT** [comment]
### From gary@pandemic.itc.nrcs.usda.gov



We are experiencing intermittent cores during execution of a perl app
using the DBD&#8203;::Informix module\. It happens with greater frequency when
the system is busy\, but it also happens that the exact procedure can
be rerun successfully just a few minutes after a crash\. I don't have
a lot to work with\, except that each gdb stack trace shows the failure
happens in malloc\, but the malloc is not always called from the same
place\. Many other processes are running at the same time without any
malloc failures\, and vmstat shows plenty of memory available\. A sample
stack trace looks like this&#8203;:

\#0  0x2a09c in malloc \(\)
\#1  0xff087728 in \_iqprepare \(\) from /usr/informix9/lib/esql/libifsql\.so
\#2  0xff087580 in sqli\_prep \(\) from /usr/informix9/lib/esql/libifsql\.so
\#3  0xff0ea7d0 in dbd\_ix\_st\_prepare \(\)
&nbsp;   from /usr/local/lib/perl5/site\_perl/5\.005/sun4\-solaris/auto/DBD/Informix/Inf
ormix\.so
\#4  0xff0e5654 in XS\_DBD\_\_Informix\_\_st\_\_prepare \(\)
&nbsp;   from /usr/local/lib/perl5/site\_perl/5\.005/sun4\-solaris/auto/DBD/Informix/Inf
ormix\.so
\#5  0x64fb4 in Perl\_pp\_entersub \(\)
\#6  0x9eb54 in Perl\_runops\_standard \(\)
\#7  0x26d28 in perl\_call\_sv \(\)
\#8  0xff118164 in XS\_DBI\_dispatch \(\)
&nbsp;   from /usr/local/lib/perl5/site\_perl/5\.005/sun4\-solaris/auto/DBI/DBI\.so
\#9  0x64fb4 in Perl\_pp\_entersub \(\)
\#10 0x9eb54 in Perl\_runops\_standard \(\)
\#11 0x26d28 in perl\_call\_sv \(\)
\#12 0xff118164 in XS\_DBI\_dispatch \(\)
&nbsp;   from /usr/local/lib/perl5/site\_perl/5\.005/sun4\-solaris/auto/DBI/DBI\.so
\#13 0x64fb4 in Perl\_pp\_entersub \(\)
\#14 0x9eb54 in Perl\_runops\_standard \(\)
\#15 0x26444 in perl\_run \(\)
\#16 0x23fc0 in main \(\)


My version of DBD&#8203;::Informix seems to be 0\.97005\.
The Informix engine is 9\.21\.UC1 and ESQL is 9\.40\.UC2

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl v5.6.0:

Configured by jmm at Wed Nov 29 11:10:25 MST 2000.

Summary of my perl5 (revision 5.0 version 6 subversion 0) configuration:
  Platform:
    osname=solaris, osvers=2.7, archname=sun4-solaris
    uname='sunos pandemic 5.7 generic_106541-12 sun4u sparc sunw,ultra-60 '
    config_args=''
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define 
    use64bitint=undef use64bitall=undef uselongdouble=undef usesocks=undef
  Compiler:
    cc='gcc', optimize='-g -O2', gccversion=2.95.2 19991024 (release)
    cppflags='-DDEBUGGING -fno-strict-aliasing -I/usr/local/include'
    ccflags ='-DDEBUGGING -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    stdchar='char', d_stdstdio=define, usevfork=false
    intsize=4, longsize=4, ptrsize=4, doublesize=8
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, usemymalloc=y, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib '
    libpth=/usr/local/lib /lib /usr/lib /usr/ccs/lib
    libs=-lsocket -lnsl -ldl -lm -lc -lcrypt -lsec
    libc=, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags=' -Wl,-E'
    cccdlflags='-fPIC', lddlflags=' -W,l-E -G -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.0:
    /usr/local/lib/perl5/5.6.0/sun4-solaris
    /usr/local/lib/perl5/5.6.0
    /usr/local/lib/perl5/site_perl/5.6.0/sun4-solaris
    /usr/local/lib/perl5/site_perl/5.6.0
    /usr/local/lib/perl5/site_perl/5.005/sun4-solaris
    /usr/local/lib/perl5/site_perl/5.005
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.6.0:
    HOME=/home/gary
    LANG=C
    LANGUAGE (unset)
    LD_LIBRARY_PATH=/usr/dt/lib:/usr/lib:/usr/openwin/lib:/usr/ucblib:/usr/local/lib
    LOGDIR (unset)
    PATH=/usr/informix9/bin:/share/CVS/bin:/usr/bin:/usr/dt/bin:/usr/openwin/bin:/usr/openwin/demo:/usr/ucb:/etc:/usr/local/bin:/usr/sbin:/home/gary/bin:/usr/ccs/bin::/usr/local/purecov:/usr/local/purify:/share/java/jdk/bin
    PERL_BADLANG (unset)
    SHELL=/bin/ksh

```
</details>

**Comment by p5pRT** [comment]
### From @timj



I think you will find that the problem is in Perl malloc\. There have been
numerous reports that using perl malloc \+ gcc is broken \(PDL has had these
problems\)\. The only solution currently is to rebuild your perl using Sun
malloc\. Build with \-Uusemymalloc\.

The solaris hints file should probably make this the default until the
problem in malloc can be found\. One thing that worries me is that in the
past many of the perl malloc solaris problems have gone away with
DEBUGGING turned on\.

It also doesn't help that ActiveState ship their Solaris perl binary using
Perl malloc\.

Hope this helps

Tim

On Tue\, 23 Jan 2001 gary@&#8203;pandemic\.itc\.nrcs\.usda\.gov wrote&#8203;:

>
> This is a bug report for perl from gspivak@&#8203;itc\.nrcs\.usda\.gov\,
> generated with the help of perlbug 1\.28 running under perl v5\.6\.0\.
>
>
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
>
> We are experiencing intermittent cores during execution of a perl app
> using the DBD&#8203;::Informix module\. It happens with greater frequency when
> the system is busy\, but it also happens that the exact procedure can
> be rerun successfully just a few minutes after a crash\. I don't have
> a lot to work with\, except that each gdb stack trace shows the failure
> happens in malloc\, but the malloc is not always called from the same
> place\. Many other processes are running at the same time without any
> malloc failures\, and vmstat shows plenty of memory available\. A sample
> stack trace looks like this&#8203;:
>
> \#0  0x2a09c in malloc \(\)
> \#1  0xff087728 in \_iqprepare \(\) from /usr/informix9/lib/esql/libifsql\.so
> \#2  0xff087580 in sqli\_prep \(\) from /usr/informix9/lib/esql/libifsql\.so
> \#3  0xff0ea7d0 in dbd\_ix\_st\_prepare \(\)
>    from /usr/local/lib/perl5/site\_perl/5\.005/sun4\-solaris/auto/DBD/Informix/Inf
> ormix\.so
> \#4  0xff0e5654 in XS\_DBD\_\_Informix\_\_st\_\_prepare \(\)
>    from /usr/local/lib/perl5/site\_perl/5\.005/sun4\-solaris/auto/DBD/Informix/Inf
> ormix\.so
> \#5  0x64fb4 in Perl\_pp\_entersub \(\)
> \#6  0x9eb54 in Perl\_runops\_standard \(\)
> \#7  0x26d28 in perl\_call\_sv \(\)
> \#8  0xff118164 in XS\_DBI\_dispatch \(\)
>    from /usr/local/lib/perl5/site\_perl/5\.005/sun4\-solaris/auto/DBI/DBI\.so
> \#9  0x64fb4 in Perl\_pp\_entersub \(\)
> \#10 0x9eb54 in Perl\_runops\_standard \(\)
> \#11 0x26d28 in perl\_call\_sv \(\)
> \#12 0xff118164 in XS\_DBI\_dispatch \(\)
>    from /usr/local/lib/perl5/site\_perl/5\.005/sun4\-solaris/auto/DBI/DBI\.so
> \#13 0x64fb4 in Perl\_pp\_entersub \(\)
> \#14 0x9eb54 in Perl\_runops\_standard \(\)
> \#15 0x26444 in perl\_run \(\)
> \#16 0x23fc0 in main \(\)
>
>
> My version of DBD&#8203;::Informix seems to be 0\.97005\.
> The Informix engine is 9\.21\.UC1 and ESQL is 9\.40\.UC2
>
>
>
> \[Please do not change anything below this line\]
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \-\-\-
> Flags&#8203;:
>     category=core
>     severity=high
> \-\-\-
> Site configuration information for perl v5\.6\.0&#8203;:
>
> Configured by jmm at Wed Nov 29 11&#8203;:10&#8203;:25 MST 2000\.
>
> Summary of my perl5 \(revision 5\.0 version 6 subversion 0\) configuration&#8203;:
>   Platform&#8203;:
>     osname=solaris\, osvers=2\.7\, archname=sun4\-solaris
>     uname='sunos pandemic 5\.7 generic\_106541\-12 sun4u sparc sunw\,ultra\-60 '
>     config\_args=''
>     hint=recommended\, useposix=true\, d\_sigaction=define
>     usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
>     useperlio=undef d\_sfio=undef uselargefiles=define
>     use64bitint=undef use64bitall=undef uselongdouble=undef usesocks=undef
>   Compiler&#8203;:
>     cc='gcc'\, optimize='\-g \-O2'\, gccversion=2\.95\.2 19991024 \(release\)
>     cppflags='\-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include'
>     ccflags ='\-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'
>     stdchar='char'\, d\_stdstdio=define\, usevfork=false
>     intsize=4\, longsize=4\, ptrsize=4\, doublesize=8
>     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
>     ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
>     alignbytes=8\, usemymalloc=y\, prototype=define
>   Linker and Libraries&#8203;:
>     ld='gcc'\, ldflags =' \-L/usr/local/lib '
>     libpth=/usr/local/lib /lib /usr/lib /usr/ccs/lib
>     libs=\-lsocket \-lnsl \-ldl \-lm \-lc \-lcrypt \-lsec
>     libc=\, so=so\, useshrplib=false\, libperl=libperl\.a
>   Dynamic Linking&#8203;:
>     dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags=' \-Wl\,\-E'
>     cccdlflags='\-fPIC'\, lddlflags=' \-W\,l\-E \-G \-L/usr/local/lib'
>
> Locally applied patches&#8203;:
>
>
> \-\-\-
> @&#8203;INC for perl v5\.6\.0&#8203;:
>     /usr/local/lib/perl5/5\.6\.0/sun4\-solaris
>     /usr/local/lib/perl5/5\.6\.0
>     /usr/local/lib/perl5/site\_perl/5\.6\.0/sun4\-solaris
>     /usr/local/lib/perl5/site\_perl/5\.6\.0
>     /usr/local/lib/perl5/site\_perl/5\.005/sun4\-solaris
>     /usr/local/lib/perl5/site\_perl/5\.005
>     /usr/local/lib/perl5/site\_perl
>     \.
>
> \-\-\-
> Environment for perl v5\.6\.0&#8203;:
>     HOME=/home/gary
>     LANG=C
>     LANGUAGE \(unset\)
>     LD\_LIBRARY\_PATH=/usr/dt/lib&#8203;:/usr/lib&#8203;:/usr/openwin/lib&#8203;:/usr/ucblib&#8203;:/usr/local/lib
>     LOGDIR \(unset\)
>     PATH=/usr/informix9/bin&#8203;:/share/CVS/bin&#8203;:/usr/bin&#8203;:/usr/dt/bin&#8203;:/usr/openwin/bin&#8203;:/usr/openwin/demo&#8203;:/usr/ucb&#8203;:/etc&#8203;:/usr/local/bin&#8203;:/usr/sbin&#8203;:/home/gary/bin&#8203;:/usr/ccs/bin&#8203;::/usr/local/purecov&#8203;:/usr/local/purify&#8203;:/share/java/jdk/bin
>     PERL\_BADLANG \(unset\)
>     SHELL=/bin/ksh
>
>

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Tue\, 23 Jan 2001 gary@&#8203;pandemic\.itc\.nrcs\.usda\.gov wrote&#8203;:
>
> We are experiencing intermittent cores during execution of a perl app
> using the DBD&#8203;::Informix module\. It happens with greater frequency when
> the system is busy\, but it also happens that the exact procedure can
> be rerun successfully just a few minutes after a crash\. I don't have
> a lot to work with\, except that each gdb stack trace shows the failure
> happens in malloc\, but the malloc is not always called from the same
> place\. Many other processes are running at the same time without any
> malloc failures\, and vmstat shows plenty of memory available\. A sample
> stack trace looks like this&#8203;:
>
> \#0  0x2a09c in malloc \(\)
> \#1  0xff087728 in \_iqprepare \(\) from /usr/informix9/lib/esql/libifsql\.so
> \#2  0xff087580 in sqli\_prep \(\) from /usr/informix9/lib/esql/libifsql\.so
> \#3  0xff0ea7d0 in dbd\_ix\_st\_prepare \(\)
>    from /usr/local/lib/perl5/site\_perl/5\.005/sun4\-solaris/auto/DBD/Informix/Inf

Does it always coredump in the esql libraries ?  Can you make an equivalent
esql/c program that exhibits the same behaviour ?  If the answer to these
is 'yes' then you might be experiencing a bug in the esql libraries\.

On the other hand it might be a problem with DBD&#8203;::Informix in which case you
might want to submit a bug report \( if you have a version >= 1\.00 PC1 \)
using the InformixTechSupport tool\.


/J\\

**Comment by p5pRT** [comment]
### From @smpeters

> \[RT\_System \- Sat Feb 03 21&#8203;:24&#8203;:58 2001\]&#8203;:
> 
> On Tue\, 23 Jan 2001 gary@&#8203;pandemic\.itc\.nrcs\.usda\.gov wrote&#8203;:
> >
> > We are experiencing intermittent cores during execution of a perl
> app
> > using the DBD&#8203;::Informix module\. It happens with greater frequency
> when
> > the system is busy\, but it also happens that the exact procedure can
> > be rerun successfully just a few minutes after a crash\. I don't have
> > a lot to work with\, except that each gdb stack trace shows the
> failure
> > happens in malloc\, but the malloc is not always called from the same
> > place\. Many other processes are running at the same time without any
> > malloc failures\, and vmstat shows plenty of memory available\. A
> sample
> > stack trace looks like this&#8203;:
> >
> > \#0  0x2a09c in malloc \(\)
> > \#1  0xff087728 in \_iqprepare \(\) from
> /usr/informix9/lib/esql/libifsql\.so
> > \#2  0xff087580 in sqli\_prep \(\) from
> /usr/informix9/lib/esql/libifsql\.so
> > \#3  0xff0ea7d0 in dbd\_ix\_st\_prepare \(\)
> >    from /usr/local/lib/perl5/site\_perl/5\.005/sun4\-
> solaris/auto/DBD/Informix/Inf
> 
> Does it always coredump in the esql libraries ?  Can you make an
> equivalent
> esql/c program that exhibits the same behaviour ?  If the answer to
> these
> is 'yes' then you might be experiencing a bug in the esql libraries\.
> 
> On the other hand it might be a problem with DBD&#8203;::Informix in which
> case you
> might want to submit a bug report \( if you have a version >= 1\.00 PC1
> \)
> using the InformixTechSupport tool\.
> 
> 
> /J\\
> 

The workaround at the time of \-Uusemymalloc should have worked\.  Along
with fixes to Perl's malloc since this ticket has been opened\, this
problem has been resolved\.

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'resolved'
