### ISSUE TITLE
Segmentation fault generated from './perl -Ilib t/lib/compmod.pl    CPAN'

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#3531]
Migrated from [rt.perl.org#5981](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=5981) (status was 'resolved')

Searchable as RT5981$

**Comment by p5pRT** [comment]
### From dcd@tc.fluke.com



When testing the latest bleadperl I'm seeing segfaults

 \(  cd t &&  \./perl TEST \-v lib/1\_compile\.t \)

jd&#8203;:q2$  \(  cd t &&  \./perl TEST \-v lib/1\_compile\.t \)
/tmp/q2/t
lib/1\_compile\.\.\.1\.\.137
ok 1
ok 2
ok 3
ok 4
ok 5
ok 6
ok 7
ok 8
ok 9
ok 10
ok 11
ok 12
\# CPAN compile failed
not ok 13

 exit code=0\,
 signal=13
FAILED at test 13
Failed 1 test script out of 1\, 0\.00% okay\.
&nbsp;   \#\#\# Since not all tests were successful\, you may want to run some
&nbsp;   \#\#\# of them individually and examine any diagnostic messages they
&nbsp;   \#\#\# produce\.  See the INSTALL document's section on "make test"\.
&nbsp;   \#\#\# If you are testing the compiler\, then ignore this message 
&nbsp;   \#\#\# and run 
&nbsp;   \#\#\#      \./perl harness
&nbsp;   \#\#\# in the directory \./t\.
u=0\.02  s=0  cu=2\.15  cs=0\.15  scripts=1  tests=137


If I use gdb to examine the core file

gdb \./perl \./core
Core was generated by \`\./perl \-Ilib t/lib/compmod\.pl CPAN'\.
Program terminated with signal 11\, Segmentation fault\.
Reading symbols from /lib/libnsl\.so\.1\.\.\.done\.
Reading symbols from /lib/libdl\.so\.2\.\.\.done\.
Reading symbols from /lib/libm\.so\.6\.\.\.done\.
Reading symbols from /lib/libc\.so\.6\.\.\.done\.
Reading symbols from /lib/libcrypt\.so\.1\.\.\.done\.
Reading symbols from /lib/libutil\.so\.1\.\.\.done\.
Reading symbols from /lib/ld\-linux\.so\.2\.\.\.done\.
Reading symbols from /tmp/q2/lib/auto/IO/IO\.so\.\.\.done\.
Reading symbols from /tmp/q2/lib/auto/Fcntl/Fcntl\.so\.\.\.done\.
Reading symbols from /tmp/q2/lib/auto/Opcode/Opcode\.so\.\.\.done\.
\#0  S\_op\_clear \(o=0x82d2078\) at op\.c&#8203;:860
860                         pmop = pmop\->op\_pmnext;


\#0  S\_op\_clear \(o=0x82d2078\) at op\.c&#8203;:860
\#1  0x80951c4 in Perl\_op\_free \(o=0x82d2078\) at op\.c&#8203;:751
\#2  0x809518d in Perl\_op\_free \(o=0x82d25e8\) at op\.c&#8203;:739
\#3  0x809518d in Perl\_op\_free \(o=0x82d2610\) at op\.c&#8203;:739
\#4  0x809518d in Perl\_op\_free \(o=0x82d2650\) at op\.c&#8203;:739
\#5  0x809518d in Perl\_op\_free \(o=0x82d26b8\) at op\.c&#8203;:739
\#6  0x809518d in Perl\_op\_free \(o=0x82d2800\) at op\.c&#8203;:739
\#7  0x809518d in Perl\_op\_free \(o=0x82d2828\) at op\.c&#8203;:739
\#8  0x809518d in Perl\_op\_free \(o=0x82d2848\) at op\.c&#8203;:739
\#9  0x809518d in Perl\_op\_free \(o=0x82d17f0\) at op\.c&#8203;:739
\#10 0x808e1c1 in Perl\_cv\_undef \(cv=0x82c179c\) at op\.c&#8203;:739
\#11 0x80c0ff6 in Perl\_sv\_clear \(sv=0x82c179c\) at sv\.c&#8203;:4443
\#12 0x80c14d6 in Perl\_sv\_free \(sv=0x82c179c\) at sv\.c&#8203;:4605
\#13 0x806321c in Perl\_gp\_free \(gv=0x82c1760\) at gv\.c&#8203;:1134
\#14 0x80c1036 in Perl\_sv\_clear \(sv=0x82c1760\) at sv\.c&#8203;:4455
\#15 0x80c14d6 in Perl\_sv\_free \(sv=0x82c1760\) at sv\.c&#8203;:4605
\#16 0x80c861f in do\_clean\_all \(sv=0x82c1760\) at sv\.c&#8203;:9355
\#17 0x80c6ca4 in Perl\_sv\_clean\_all \(\) at sv\.c&#8203;:161
\#18 0x805c0fb in perl\_destruct \(my\_perl=0x812a928\) at perl\.c&#8203;:670
\#19 0x805aa91 in main \(argc=4\, argv=0xbffff4b4\, env=0xbffff4c8\)
&nbsp;    at perlmain\.c&#8203;:55

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl v5.7.0:

Configured by dcd at Mon Mar  5 15:39:53 PST 2001.

Summary of my perl5 (revision 5.0 version 7 subversion 0) configuration:
  Platform:
    osname=linux, osvers=2.2.5, archname=i686-linux
    uname='linux jd 2.2.5 #1 tue apr 13 16:33:46 mest 1999 i686 unknown '
    config_args='-Dinstallusrbinperl -Dusedevel -Doptimize=-O3 -g -de -Dcf_email=dcd@tc.fluke.com'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='cc', ccflags ='-DDEBUGGING -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O3 -g',
    cppflags='-DDEBUGGING -fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='egcs-2.91.66 19990314 (egcs-1.1.2 release)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=4
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lndbm -lgdbm -ldbm -ldb -ldl -lm -lc -lposix -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lposix -lcrypt -lutil
    libc=, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    DEVEL9021


@INC for perl v5.7.0:
    lib
    /usr/local/lib/perl5/5.7.0/i686-linux
    /usr/local/lib/perl5/5.7.0
    /usr/local/lib/perl5/site_perl/5.7.0/i686-linux
    /usr/local/lib/perl5/site_perl/5.7.0
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.7.0:
    HOME=/home/dcd
    LANG=POSIX
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/dcd/bin:/sbin:/home/dcd/bin:/usr/local/bin:/usr/bin:/usr/X11R6/bin:/bin:/usr/openwin/bin:/var/lib/dosemu:/usr/games/bin:/usr/games:/opt/gnome/bin:/opt/kde/bin:.:/usr/lib/pgsql/bin:/usr/local/samba:/home/hobbes/tools/scripts:/home/hobbes/tools/linux:/usr0/hobbes/tools/scripts:/usr0/dcd/bin:/apps/general/bin:/usr/public
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @jhi

On Tue\, Mar 06\, 2001 at 08&#8203;:33&#8203;:00AM \-0800\, dcd@&#8203;tc\.fluke\.com wrote&#8203;:
> 
> This is a bug report for perl from dcd@&#8203;tc\.fluke\.com\,
> generated with the help of perlbug 1\.33 running under perl v5\.7\.0\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> 
> When testing the latest bleadperl I'm seeing segfaults

Define 'the latest'\.  The snapshot or a later \(rsynced?\) version?

>  \(  cd t &&  \./perl TEST \-v lib/1\_compile\.t \)
> 
> jd&#8203;:q2$  \(  cd t &&  \./perl TEST \-v lib/1\_compile\.t \)
> /tmp/q2/t
> lib/1\_compile\.\.\.1\.\.137
> ok 1
> ok 2
> ok 3
> ok 4
> ok 5
> ok 6
> ok 7
> ok 8
> ok 9
> ok 10
> ok 11
> ok 12
> \# CPAN compile failed
> not ok 13
> 
>  exit code=0\,
>  signal=13
> FAILED at test 13
> Failed 1 test script out of 1\, 0\.00% okay\.
>    \#\#\# Since not all tests were successful\, you may want to run some
>    \#\#\# of them individually and examine any diagnostic messages they
>    \#\#\# produce\.  See the INSTALL document's section on "make test"\.
>    \#\#\# If you are testing the compiler\, then ignore this message 
>    \#\#\# and run 
>    \#\#\#      \./perl harness
>    \#\#\# in the directory \./t\.
> u=0\.02  s=0  cu=2\.15  cs=0\.15  scripts=1  tests=137
> 
> 
> If I use gdb to examine the core file
> 
> gdb \./perl \./core
> Core was generated by \`\./perl \-Ilib t/lib/compmod\.pl CPAN'\.
> Program terminated with signal 11\, Segmentation fault\.
> Reading symbols from /lib/libnsl\.so\.1\.\.\.done\.
> Reading symbols from /lib/libdl\.so\.2\.\.\.done\.
> Reading symbols from /lib/libm\.so\.6\.\.\.done\.
> Reading symbols from /lib/libc\.so\.6\.\.\.done\.
> Reading symbols from /lib/libcrypt\.so\.1\.\.\.done\.
> Reading symbols from /lib/libutil\.so\.1\.\.\.done\.
> Reading symbols from /lib/ld\-linux\.so\.2\.\.\.done\.
> Reading symbols from /tmp/q2/lib/auto/IO/IO\.so\.\.\.done\.
> Reading symbols from /tmp/q2/lib/auto/Fcntl/Fcntl\.so\.\.\.done\.
> Reading symbols from /tmp/q2/lib/auto/Opcode/Opcode\.so\.\.\.done\.
> \#0  S\_op\_clear \(o=0x82d2078\) at op\.c&#8203;:860
> 860                         pmop = pmop\->op\_pmnext;
> 
> 
> \#0  S\_op\_clear \(o=0x82d2078\) at op\.c&#8203;:860
> \#1  0x80951c4 in Perl\_op\_free \(o=0x82d2078\) at op\.c&#8203;:751
> \#2  0x809518d in Perl\_op\_free \(o=0x82d25e8\) at op\.c&#8203;:739
> \#3  0x809518d in Perl\_op\_free \(o=0x82d2610\) at op\.c&#8203;:739
> \#4  0x809518d in Perl\_op\_free \(o=0x82d2650\) at op\.c&#8203;:739
> \#5  0x809518d in Perl\_op\_free \(o=0x82d26b8\) at op\.c&#8203;:739
> \#6  0x809518d in Perl\_op\_free \(o=0x82d2800\) at op\.c&#8203;:739
> \#7  0x809518d in Perl\_op\_free \(o=0x82d2828\) at op\.c&#8203;:739
> \#8  0x809518d in Perl\_op\_free \(o=0x82d2848\) at op\.c&#8203;:739
> \#9  0x809518d in Perl\_op\_free \(o=0x82d17f0\) at op\.c&#8203;:739
> \#10 0x808e1c1 in Perl\_cv\_undef \(cv=0x82c179c\) at op\.c&#8203;:739
> \#11 0x80c0ff6 in Perl\_sv\_clear \(sv=0x82c179c\) at sv\.c&#8203;:4443
> \#12 0x80c14d6 in Perl\_sv\_free \(sv=0x82c179c\) at sv\.c&#8203;:4605
> \#13 0x806321c in Perl\_gp\_free \(gv=0x82c1760\) at gv\.c&#8203;:1134
> \#14 0x80c1036 in Perl\_sv\_clear \(sv=0x82c1760\) at sv\.c&#8203;:4455
> \#15 0x80c14d6 in Perl\_sv\_free \(sv=0x82c1760\) at sv\.c&#8203;:4605
> \#16 0x80c861f in do\_clean\_all \(sv=0x82c1760\) at sv\.c&#8203;:9355
> \#17 0x80c6ca4 in Perl\_sv\_clean\_all \(\) at sv\.c&#8203;:161
> \#18 0x805c0fb in perl\_destruct \(my\_perl=0x812a928\) at perl\.c&#8203;:670
> \#19 0x805aa91 in main \(argc=4\, argv=0xbffff4b4\, env=0xbffff4c8\)
>     at perlmain\.c&#8203;:55
> 
> 
> 
> \[Please do not change anything below this line\]
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \-\-\-
> Flags&#8203;:
>     category=core
>     severity=high
> \-\-\-
> Site configuration information for perl v5\.7\.0&#8203;:
> 
> Configured by dcd at Mon Mar  5 15&#8203;:39&#8203;:53 PST 2001\.
> 
> Summary of my perl5 \(revision 5\.0 version 7 subversion 0\) configuration&#8203;:
>   Platform&#8203;:
>     osname=linux\, osvers=2\.2\.5\, archname=i686\-linux
>     uname='linux jd 2\.2\.5 \#1 tue apr 13 16&#8203;:33&#8203;:46 mest 1999 i686 unknown '
>     config\_args='\-Dinstallusrbinperl \-Dusedevel \-Doptimize=\-O3 \-g \-de \-Dcf\_email=dcd@&#8203;tc\.fluke\.com'
>     hint=recommended\, useposix=true\, d\_sigaction=define
>     usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
>     useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
>     use64bitint=undef use64bitall=undef uselongdouble=undef
>   Compiler&#8203;:
>     cc='cc'\, ccflags ='\-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
>     optimize='\-O3 \-g'\,
>     cppflags='\-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include'
>     ccversion=''\, gccversion='egcs\-2\.91\.66 19990314 \(egcs\-1\.1\.2 release\)'\, gccosandvers=''
>     intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
>     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
>     ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=4
>     alignbytes=4\, usemymalloc=n\, prototype=define
>   Linker and Libraries&#8203;:
>     ld='cc'\, ldflags =' \-L/usr/local/lib'
>     libpth=/usr/local/lib /lib /usr/lib
>     libs=\-lnsl \-lndbm \-lgdbm \-ldbm \-ldb \-ldl \-lm \-lc \-lposix \-lcrypt \-lutil
>     perllibs=\-lnsl \-ldl \-lm \-lc \-lposix \-lcrypt \-lutil
>     libc=\, so=so\, useshrplib=false\, libperl=libperl\.a
>   Dynamic Linking&#8203;:
>     dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
>     cccdlflags='\-fpic'\, lddlflags='\-shared \-L/usr/local/lib'
> 
> Locally applied patches&#8203;:
>     DEVEL9021
> 
> \-\-\-
> @&#8203;INC for perl v5\.7\.0&#8203;:
>     lib
>     /usr/local/lib/perl5/5\.7\.0/i686\-linux
>     /usr/local/lib/perl5/5\.7\.0
>     /usr/local/lib/perl5/site\_perl/5\.7\.0/i686\-linux
>     /usr/local/lib/perl5/site\_perl/5\.7\.0
>     /usr/local/lib/perl5/site\_perl
>     \.
> 
> \-\-\-
> Environment for perl v5\.7\.0&#8203;:
>     HOME=/home/dcd
>     LANG=POSIX
>     LANGUAGE \(unset\)
>     LD\_LIBRARY\_PATH \(unset\)
>     LOGDIR \(unset\)
>     PATH=/home/dcd/bin&#8203;:/sbin&#8203;:/home/dcd/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/usr/X11R6/bin&#8203;:/bin&#8203;:/usr/openwin/bin&#8203;:/var/lib/dosemu&#8203;:/usr/games/bin&#8203;:/usr/games&#8203;:/opt/gnome/bin&#8203;:/opt/kde/bin&#8203;:\.&#8203;:/usr/lib/pgsql/bin&#8203;:/usr/local/samba&#8203;:/home/hobbes/tools/scripts&#8203;:/home/hobbes/tools/linux&#8203;:/usr0/hobbes/tools/scripts&#8203;:/usr0/dcd/bin&#8203;:/apps/general/bin&#8203;:/usr/public
>     PERL\_BADLANG \(unset\)
>     SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @jhi

On Tue\, Mar 06\, 2001 at 10&#8203;:36&#8203;:08AM \-0600\, Jarkko Hietaniemi wrote&#8203;:
> On Tue\, Mar 06\, 2001 at 08&#8203;:33&#8203;:00AM \-0800\, dcd@&#8203;tc\.fluke\.com wrote&#8203;:
> > 
> > This is a bug report for perl from dcd@&#8203;tc\.fluke\.com\,
> > generated with the help of perlbug 1\.33 running under perl v5\.7\.0\.
> > 
> > 
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > \[Please enter your report here\]
> > 
> > When testing the latest bleadperl I'm seeing segfaults
> 
> Define 'the latest'\.  The snapshot or a later \(rsynced?\) version?

If a later one\, please re\-rsync\.  The PMOP patch wasn't apparently
quite right\, I took it out for further investigation\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]


On Tue\, 6 Mar 2001\, Jarkko Hietaniemi wrote&#8203;:

> On Tue\, Mar 06\, 2001 at 10&#8203;:36&#8203;:08AM \-0600\, Jarkko Hietaniemi wrote&#8203;:
> > On Tue\, Mar 06\, 2001 at 08&#8203;:33&#8203;:00AM \-0800\, dcd@&#8203;tc\.fluke\.com wrote&#8203;:
> > >
> > > When testing the latest bleadperl I'm seeing segfaults
> >
> > Define 'the latest'\.  The snapshot or a later \(rsynced?\) version?
>
> If a later one\, please re\-rsync\.  The PMOP patch wasn't apparently
> quite right\, I took it out for further investigation\.

It was an rsync through patch 9053

I've since rsync'ed agian
with patch 9059 and rebuilt with
&nbsp;  All tests successful\.

Please accept my thanks for backing
out the problems\, and mark this
bug resolved\.
