### ISSUE TITLE
syntax error leads to segfault

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#3578]
Migrated from [rt.perl.org#6053](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=6053) (status was 'resolved')

Searchable as RT6053$

**Comment by p5pRT** [comment]
### From flee@aracnet.com



$ perl \-e 'sub a \{ sub; die if @&#8203;\_; die "foo $a"; \}'
syntax error at \-e line 1\, near "sub;"
Segmentation fault

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.6.0:

Configured by prospector at Mon Aug  7 10:58:30 EDT 2000.

Summary of my perl5 (revision 5.0 version 6 subversion 0) configuration:
  Platform:
    osname=linux, osvers=2.2.5-22smp, archname=i386-linux
    uname='linux porky.devel.redhat.com 2.2.5-22smp #1 smp wed jun 2 09:11:51 edt 1999 i686 unknown '
    config_args='-des -Doptimize=-O2 -march=i386 -mcpu=i686 -Dcc=gcc -Dcccdlflags=-fPIC -Dinstallprefix=/usr -Dprefix=/usr -Darchname=i386-linux -Dd_dosuid -Dd_semctl_semun -Di_db -Di_ndbm -Di_gdbm -Di_shadow -Di_syslog -Dman3ext=3pm -Uuselargefiles'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=undef 
    use64bitint=undef use64bitall=undef uselongdouble=undef usesocks=undef
  Compiler:
    cc='gcc', optimize='-O2 -march=i386 -mcpu=i686', gccversion=2.96 20000731 (experimental)
    cppflags='-fno-strict-aliasing'
    ccflags ='-fno-strict-aliasing'
    stdchar='char', d_stdstdio=define, usevfork=false
    intsize=4, longsize=4, ptrsize=4, doublesize=8
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=4
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -ldl -lm -lc -lcrypt
    libc=/lib/libc-2.1.92.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    



```
</details>

**Comment by p5pRT** [comment]
### From @floatingatoll

Here's the stack backtrace from the coredump under @&#8203;10209\.

Compile\-time options&#8203;: DEBUGGING MULTIPLICITY USE\_ITHREADS USE\_LARGE\_FILES PERL\_IMPLICIT\_CONTEXT

R\.

\#0  0x8080cd8 in Perl\_pad\_swipe \(my\_perl=0x811d680\, po=4\) at op\.c&#8203;:574
574         SvPADTMP\_off\(PL\_curpad\[po\]\);
\(gdb\) bt
\#0  0x8080cd8 in Perl\_pad\_swipe \(my\_perl=0x811d680\, po=4\) at op\.c&#8203;:574
\#1  0x8080f2f in Perl\_op\_clear \(my\_perl=0x811d680\, o=0x812b168\) at op\.c&#8203;:767
\#2  0x8080e33 in Perl\_op\_free \(my\_perl=0x811d680\, o=0x812b168\) at op\.c&#8203;:727
\#3  0x8080dfa in Perl\_op\_free \(my\_perl=0x811d680\, o=0x812b238\) at op\.c&#8203;:715
\#4  0x8080dfa in Perl\_op\_free \(my\_perl=0x811d680\, o=0x812b290\) at op\.c&#8203;:715
\#5  0x8080dfa in Perl\_op\_free \(my\_perl=0x811d680\, o=0x812b2b8\) at op\.c&#8203;:715
\#6  0x8080dfa in Perl\_op\_free \(my\_perl=0x811d680\, o=0x812b300\) at op\.c&#8203;:715
\#7  0x8080dfa in Perl\_op\_free \(my\_perl=0x811d680\, o=0x8121fe0\) at op\.c&#8203;:715
\#8  0x80881c1 in Perl\_newATTRSUB \(my\_perl=0x811d680\, floor=84\, o=0x812b038\, proto=0x0\, attrs=0x0\, 
&nbsp;    block=0x8121fe0\) at op\.c&#8203;:4737
\#9  0x807e9dd in Perl\_yyparse \(my\_perl=0x811d680\) at perly\.y&#8203;:333
\#10 0x805f7fa in S\_parse\_body \(my\_perl=0x811d680\, env=0x0\, xsinit=0x805d0ec \<xs\_init>\) at perl\.c&#8203;:1343
\#11 0x805ed76 in perl\_parse \(my\_perl=0x811d680\, xsinit=0x805d0ec \<xs\_init>\, argc=3\, argv=0xbffffcc4\, env=0x0\)
&nbsp;    at perl\.c&#8203;:917
\#12 0x805d097 in main \(argc=3\, argv=0xbffffcc4\, env=0xbffffcd4\) at perlmain\.c&#8203;:55

**Comment by p5pRT** [comment]
### From @iabyn

\(Just reviewing old Perl bugs\)\.

This is fixed in the current development version of Perl\, which
will eventually be released as 5\.10\.0\.

Regards\,

Dave M\.

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
