### ISSUE TITLE
perl-5.6.1-TRIAL3 seg faults with ./perl -Ilib -e 'do    "dumpvar.pl"; dumpvar("main")'

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#3594]
Migrated from [rt.perl.org#6155](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=6155) (status was 'resolved')

Searchable as RT6155$

**Comment by p5pRT** [comment]
### From dcd@tc.fluke.com



when testing out TRIAL3 the following commadn seg faults
 \./perl \-Ilib \-e 'do "dumpvar\.pl"; dumpvar\("main"\)'

running under gdb the output is&#8203;:
 \.\.\.
@&#8203;\_ = \(
&nbsp;   0  0
&nbsp;   1  '\_'

Program received signal SIGSEGV\, Segmentation fault\.
0x8116e3b in PL\_reg\_oldsavedlen \(\)
\(gdb\) where
\#0  0x8116e3b in PL\_reg\_oldsavedlen \(\)
\#1  0x80a0516 in Perl\_mg\_free \(sv=0x8128af8\) at mg\.c&#8203;:313
\#2  0x80b0d32 in Perl\_sv\_clear \(sv=0x8128af8\) at sv\.c&#8203;:3770
\#3  0x80b11b7 in Perl\_sv\_free \(sv=0x8128af8\) at sv\.c&#8203;:3950
\#4  0x80b0eff in Perl\_sv\_clear \(sv=0x8128aec\) at sv\.c&#8203;:3824
\#5  0x80b11b7 in Perl\_sv\_free \(sv=0x8128aec\) at sv\.c&#8203;:3950
\#6  0x80c4fe7 in Perl\_free\_tmps \(\) at scope\.c&#8203;:182
\#7  0x80aad61 in Perl\_pp\_nextstate \(\) at pp\_hot\.c&#8203;:40
\#8  0x80a4741 in Perl\_runops\_debug \(\) at run\.c&#8203;:53
\#9  0x805b7a8 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1471
\#10 0x805b4c8 in perl\_run \(my\_perl=0x810b3a8\) at perl\.c&#8203;:1393
\#11 0x8059083 in main \(argc=4\, argv=0xbffff41c\, env=0xbffff430\)
&nbsp;    at perlmain\.c&#8203;:52
\#12 0x8058f7e in \_start \(\)

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl v5.6.1:

Configured by dcd at Mon Mar 19 12:10:28 PST 2001.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=linux, osvers=2.4.3-pre2, archname=i686-linux
    uname='linux dd 2.4.3-pre2 #1 mon mar 5 08:49:56 pst 2001 i686 '
    config_args='-Dinstallusrbinperl -Dusedevel -Doptimize=-O3 -g -de -Dcf_email=dcd@tc.fluke.com'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='cc', ccflags ='-DDEBUGGING -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O3 -g',
    cppflags='-DDEBUGGING -fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='egcs-2.91.66.1 19990314/Linux (egcs-1.1.2 release)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=4
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lgdbm -ldbm -ldb -ldl -lm -lc
    perllibs=-ldl -lm -lc
    libc=/lib/libc.so.5.4.44, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    v5.6.1-TRIAL3


@INC for perl v5.6.1:
    lib
    /usr/local/lib/perl5/5.6.1/i686-linux
    /usr/local/lib/perl5/5.6.1
    /usr/local/lib/perl5/site_perl/5.6.1/i686-linux
    /usr/local/lib/perl5/site_perl/5.6.1
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.6.1:
    HOME=/home/dcd
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/dcd/bin:/sbin:/usr/local/bin:/bin:/usr/bin:/usr/X11/bin:/usr/games:/usr/local/samba:/home/hobbes/tools/scripts:/home/hobbes/tools/linux:/usr0/hobbes/tools/scripts:/usr0/dcd/bin:/apps/general/bin:/usr/public
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From dcd@tc.fluke.com



when testing out TRIAL3 the following commadn seg faults
 \./perl \-Ilib \-e 'do "dumpvar\.pl"; dumpvar\("main"\)'

running under gdb the output is&#8203;:
 \.\.\.
@&#8203;\_ = \(
&nbsp;   0  0
&nbsp;   1  '\_'

Program received signal SIGSEGV\, Segmentation fault\.
0x8116e3b in PL\_reg\_oldsavedlen \(\)
\(gdb\) where
\#0  0x8116e3b in PL\_reg\_oldsavedlen \(\)
\#1  0x80a0516 in Perl\_mg\_free \(sv=0x8128af8\) at mg\.c&#8203;:313
\#2  0x80b0d32 in Perl\_sv\_clear \(sv=0x8128af8\) at sv\.c&#8203;:3770
\#3  0x80b11b7 in Perl\_sv\_free \(sv=0x8128af8\) at sv\.c&#8203;:3950
\#4  0x80b0eff in Perl\_sv\_clear \(sv=0x8128aec\) at sv\.c&#8203;:3824
\#5  0x80b11b7 in Perl\_sv\_free \(sv=0x8128aec\) at sv\.c&#8203;:3950
\#6  0x80c4fe7 in Perl\_free\_tmps \(\) at scope\.c&#8203;:182
\#7  0x80aad61 in Perl\_pp\_nextstate \(\) at pp\_hot\.c&#8203;:40
\#8  0x80a4741 in Perl\_runops\_debug \(\) at run\.c&#8203;:53
\#9  0x805b7a8 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1471
\#10 0x805b4c8 in perl\_run \(my\_perl=0x810b3a8\) at perl\.c&#8203;:1393
\#11 0x8059083 in main \(argc=4\, argv=0xbffff41c\, env=0xbffff430\)
&nbsp;    at perlmain\.c&#8203;:52
\#12 0x8058f7e in \_start \(\)

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl v5.6.1:

Configured by dcd at Mon Mar 19 12:10:28 PST 2001.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=linux, osvers=2.4.3-pre2, archname=i686-linux
    uname='linux dd 2.4.3-pre2 #1 mon mar 5 08:49:56 pst 2001 i686 '
    config_args='-Dinstallusrbinperl -Dusedevel -Doptimize=-O3 -g -de -Dcf_email=dcd@tc.fluke.com'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='cc', ccflags ='-DDEBUGGING -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O3 -g',
    cppflags='-DDEBUGGING -fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='egcs-2.91.66.1 19990314/Linux (egcs-1.1.2 release)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=4
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lgdbm -ldbm -ldb -ldl -lm -lc
    perllibs=-ldl -lm -lc
    libc=/lib/libc.so.5.4.44, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    v5.6.1-TRIAL3


@INC for perl v5.6.1:
    lib
    /usr/local/lib/perl5/5.6.1/i686-linux
    /usr/local/lib/perl5/5.6.1
    /usr/local/lib/perl5/site_perl/5.6.1/i686-linux
    /usr/local/lib/perl5/site_perl/5.6.1
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.6.1:
    HOME=/home/dcd
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/dcd/bin:/sbin:/usr/local/bin:/bin:/usr/bin:/usr/X11/bin:/usr/games:/usr/local/samba:/home/hobbes/tools/scripts:/home/hobbes/tools/linux:/usr0/hobbes/tools/scripts:/usr0/dcd/bin:/apps/general/bin:/usr/public
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From dcd@tc.fluke.com



when testing out TRIAL3 the following commadn seg faults
 \./perl \-Ilib \-e 'do "dumpvar\.pl"; dumpvar\("main"\)'

running under gdb the output is&#8203;:
 \.\.\.
@&#8203;\_ = \(
&nbsp;   0  0
&nbsp;   1  '\_'

Program received signal SIGSEGV\, Segmentation fault\.
0x8116e3b in PL\_reg\_oldsavedlen \(\)
\(gdb\) where
\#0  0x8116e3b in PL\_reg\_oldsavedlen \(\)
\#1  0x80a0516 in Perl\_mg\_free \(sv=0x8128af8\) at mg\.c&#8203;:313
\#2  0x80b0d32 in Perl\_sv\_clear \(sv=0x8128af8\) at sv\.c&#8203;:3770
\#3  0x80b11b7 in Perl\_sv\_free \(sv=0x8128af8\) at sv\.c&#8203;:3950
\#4  0x80b0eff in Perl\_sv\_clear \(sv=0x8128aec\) at sv\.c&#8203;:3824
\#5  0x80b11b7 in Perl\_sv\_free \(sv=0x8128aec\) at sv\.c&#8203;:3950
\#6  0x80c4fe7 in Perl\_free\_tmps \(\) at scope\.c&#8203;:182
\#7  0x80aad61 in Perl\_pp\_nextstate \(\) at pp\_hot\.c&#8203;:40
\#8  0x80a4741 in Perl\_runops\_debug \(\) at run\.c&#8203;:53
\#9  0x805b7a8 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1471
\#10 0x805b4c8 in perl\_run \(my\_perl=0x810b3a8\) at perl\.c&#8203;:1393
\#11 0x8059083 in main \(argc=4\, argv=0xbffff41c\, env=0xbffff430\)
&nbsp;    at perlmain\.c&#8203;:52
\#12 0x8058f7e in \_start \(\)

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl v5.6.1:

Configured by dcd at Mon Mar 19 12:10:28 PST 2001.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=linux, osvers=2.4.3-pre2, archname=i686-linux
    uname='linux dd 2.4.3-pre2 #1 mon mar 5 08:49:56 pst 2001 i686 '
    config_args='-Dinstallusrbinperl -Dusedevel -Doptimize=-O3 -g -de -Dcf_email=dcd@tc.fluke.com'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='cc', ccflags ='-DDEBUGGING -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O3 -g',
    cppflags='-DDEBUGGING -fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='egcs-2.91.66.1 19990314/Linux (egcs-1.1.2 release)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=4
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lgdbm -ldbm -ldb -ldl -lm -lc
    perllibs=-ldl -lm -lc
    libc=/lib/libc.so.5.4.44, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    v5.6.1-TRIAL3


@INC for perl v5.6.1:
    lib
    /usr/local/lib/perl5/5.6.1/i686-linux
    /usr/local/lib/perl5/5.6.1
    /usr/local/lib/perl5/site_perl/5.6.1/i686-linux
    /usr/local/lib/perl5/site_perl/5.6.1
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.6.1:
    HOME=/home/dcd
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/dcd/bin:/sbin:/usr/local/bin:/bin:/usr/bin:/usr/X11/bin:/usr/games:/usr/local/samba:/home/hobbes/tools/scripts:/home/hobbes/tools/linux:/usr0/hobbes/tools/scripts:/usr0/dcd/bin:/apps/general/bin:/usr/public
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>
