### ISSUE TITLE
[FAILURE 5.005_60] Assertion failed: file "pp_ctl.c",    line 2430, <DATA> line 212.

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#371]
Migrated from [rt.perl.org#1206](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=1206) (status was 'resolved')

Searchable as RT1206$

**Comment by p5pRT** [comment]
### From @schwern

bash\-2\.02$ /usr/local/perl5\.005\_60/bin/perl \-dw /usr/local/perl5\.005\_60/bin/pod2html

Loading DB routines from perl5db\.pl version 1\.0402
Emacs support available\.

Enter h or \`h h' for help\.

Assertion failed&#8203;: file "pp\_ctl\.c"\, line 2430\, \<DATA> line 212\.
Debugged program terminated\.  Use q to quit or R to restart\,
&nbsp;  use O inhibit\_exit to avoid stopping after program termination\,
&nbsp;  h q\, h R or h O to get additional info\.  
&nbsp;  DB\<1> 


This is just trying to run pod2html that comes with 5\.005\_60 under the
debugger with warnings on\.  Interestingly\, it works without the
debugger on\.

I brought the case down to&#8203;:

\#\!/usr/local/perl5\.005\_60/bin/perl
&nbsp;    eval 'exec /usr/local/perl5\.005\_60/bin/perl \-S $0 $\{1\+"$@&#8203;"\}'
&nbsp;    if $running\_under\_some\_shell;

use Pod&#8203;::Html;

That's enough to get the assertation to fail\.  Strangely enough it
\-has\- to be Pod&#8203;::Html\.  I tried a few other modules and nothing seemed
to do it\.

Maybe it just hates tchrist? ;\)


Summary of my perl5 \(revision 5\.0 version 5 subversion 60\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.2\.10\, archname=i686\-linux
&nbsp;    uname='linux athens 2\.2\.10 \#3 smp mon aug 2 16&#8203;:48&#8203;:09 edt 1999 i686 unknown '
&nbsp;    config\_args=''
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef useperlio=undef d\_sfio=undef
&nbsp;    use64bits=undef usemultiplicity=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, optimize='\-g'\, gccversion=2\.95 19990728 \(release\)
&nbsp;    cppflags='\-Dbool=char \-DHAS\_BOOL \-DDEBUGGING \-DDEBUGGING\_MSTATS \-DDEBUGGING\_OPS'
&nbsp;    ccflags ='\-Dbool=char \-DHAS\_BOOL \-DDEBUGGING \-DDEBUGGING\_MSTATS \-DDEBUGGING\_OPS'
&nbsp;    stdchar='char'\, d\_stdstdio=define\, usevfork=false
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    alignbytes=4\, usemymalloc=y\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-lndbm \-lgdbm \-ldbm \-ldb \-ldl \-lm \-lrt \-lc \-lposix \-lcrypt
&nbsp;    libc=/lib/libc\-2\.1\.2\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
&nbsp;    cccdlflags='\-fpic'\, lddlflags='\-shared \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: DEBUGGING
&nbsp;  Built under linux
&nbsp;  Compiled at Aug  6 1999 23&#8203;:43&#8203;:33
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl5\.005\_60/lib/i686\-linux
&nbsp;    /usr/local/perl5\.005\_60/lib
&nbsp;    /usr/local/perl5\.005\_60/lib/site\_perl/5\.00560/i686\-linux
&nbsp;    /usr/local/perl5\.005\_60/lib/site\_perl
&nbsp;    \.


\-\- 

Michael G Schwern                                           schwern@&#8203;pobox\.com
&nbsp;                    http&#8203;://www\.pobox\.com/~schwern
&nbsp;     /\(?&#8203;:\(?&#8203;:\(1\)\[\.\-\]?\)?\\\(?\(\\d\{3\}\)\\\)?\[\.\-\]?\)?\(\\d\{3\}\)\[\.\-\]?\(\\d\{4\}\)\(x\\d\+\)?/i

**Comment by p5pRT** [comment]
### From @schwern

Damnit\, it happened again\, this time in 5\.005\_61&#8203;:

$ /usr/local/perl5\.005\_61/bin/perl \-Mblib \-d t/fields\.t

Loading DB routines from perl5db\.pl version 1\.0402
Emacs support available\.

Enter h or \`h h' for help\.

Assertion failed&#8203;: file "pp\_ctl\.c"\, line 2430\.
BEGIN failed\-\-compilation aborted\.
Debugged program terminated\.  Use q to quit or R to restart\,
&nbsp;  use O inhibit\_exit to avoid stopping after program termination\,
&nbsp;  h q\, h R or h O to get additional info\.  
&nbsp;  DB\<1>

The assertation is&#8203;: 
assert\(CATCH\_GET == TRUE\)
which is just checking to see if PL\_top\_env\->je\_mustcatch is true \(it isn't\)\.

I found the following comment in scope\.h which might prove useful&#8203;:
 \* je\_mustcatch\, when set at any runlevel to TRUE\, means eval ops must
 \* establish a local jmpenv to handle exception traps\.  Care must be taken
 \* to restore the previous value of je\_mustcatch before exiting the
 \* stack frame iff JMPENV\_PUSH was not called in that stack frame\.
 \* GSAR 97\-03\-27

I guess care wasn't taken\. :\(

Something in blib\.pm is tripping the assertion\, because if I use
\-Iblib/lib instead of \-Mblib I don't get the error\.

For what its worth\, here's a stack backtrace&#8203;:

\#0  S\_docatch \(o=0x82ba1c8\) at pp\_ctl\.c&#8203;:2427
\#1  0x80e2e25 in Perl\_pp\_require \(\) at pp\_ctl\.c&#8203;:3007
\#2  0x80abbee in Perl\_runops\_debug \(\) at run\.c&#8203;:57
\#3  0x805cecd in S\_call\_xbody \(myop=0xbffff458\, is\_eval=0\) at perl\.c&#8203;:1347
\#4  0x805c87e in perl\_call\_sv \(sv=0x8234474\, flags=2\) at perl\.c&#8203;:1235
\#5  0x809e4ed in Perl\_vwarn \(pat=0x811a0e6 "%\_"\, args=0xbffff4f8\)
&nbsp;    at util\.c&#8203;:1637
\#6  0x809e640 in Perl\_warn \(pat=0x811a0e6 "%\_"\) at util\.c&#8203;:1672
\#7  0x80e64dc in Perl\_pp\_warn \(\) at pp\_sys\.c&#8203;:436
\#8  0x80abbee in Perl\_runops\_debug \(\) at run\.c&#8203;:57
\#9  0x805cecd in S\_call\_xbody \(myop=0xbffff718\, is\_eval=0\) at perl\.c&#8203;:1347
\#10 0x805ce74 in S\_call\_body \(args=0xbffff6d4\) at perl\.c&#8203;:1331
\#11 0x80d532e in Perl\_vdefault\_protect \(excpt=0xbffff704\, 
&nbsp;    body=0x805ce40 \<S\_call\_body>\, args=0xbffff6b4\) at scope\.c&#8203;:44
\#12 0x80d5260 in Perl\_default\_protect \(excpt=0xbffff704\, 
&nbsp;    body=0x805ce40 \<S\_call\_body>\) at scope\.c&#8203;:25
\#13 0x805cb3e in perl\_call\_sv \(sv=0x8136020\, flags=6\) at perl\.c&#8203;:1266
\#14 0x805ff24 in S\_call\_list\_body \(args=0xbffff890\) at perl\.c&#8203;:3045
\#15 0x80d532e in Perl\_vdefault\_protect \(excpt=0xbffff8a8\, 
&nbsp;    body=0x805fecc \<S\_call\_list\_body>\, args=0xbffff874\) at scope\.c&#8203;:44
\#16 0x80d5260 in Perl\_default\_protect \(excpt=0xbffff8a8\, 
&nbsp;    body=0x805fecc \<S\_call\_list\_body>\) at scope\.c&#8203;:25
\#17 0x805fbee in Perl\_call\_list \(oldscope=1\, paramList=0x81360c8\)
&nbsp;    at perl\.c&#8203;:2988
\#18 0x8089694 in Perl\_newSUB \(floor=78\, o=0x82639c8\, proto=0x0\, 
&nbsp;    block=0x8136f88\) at op\.c&#8203;:4122
\#19 0x8085955 in Perl\_utilize \(aver=1\, floor=78\, version=0x0\, id=0x8135408\, 
&nbsp;    arg=0x0\) at op\.c&#8203;:2816
\#20 0x807d265 in Perl\_yyparse \(\) at perly\.y&#8203;:333
\#21 0x805bcdb in S\_parse\_body \(args=0xbffffb64\) at perl\.c&#8203;:953
\#22 0x80d532e in Perl\_vdefault\_protect \(excpt=0xbffffb74\, 
&nbsp;    body=0x805b350 \<S\_parse\_body>\, args=0xbffffb44\) at scope\.c&#8203;:44
\#23 0x80d5260 in Perl\_default\_protect \(excpt=0xbffffb74\, 
&nbsp;    body=0x805b350 \<S\_parse\_body>\) at scope\.c&#8203;:25
\#24 0x805b25f in perl\_parse \(my\_perl=0x8128808\, xsinit=0x8059778 \<xs\_init>\, 
&nbsp;    argc=4\, argv=0xbffffc24\, env=0x0\) at perl\.c&#8203;:632
\#25 0x8059719 in main \(argc=4\, argv=0xbffffc24\, env=0xbffffc38\)
&nbsp;    at perlmain\.c&#8203;:51

And the value of \*PL\_top\_env at that point&#8203;:
\{je\_prev = 0xbffff7a0\, je\_buf = \{\{\_\_jmpbuf = \{64\, 135090752\, 1075154995\, 
&nbsp;        \-1073744244\, \-1073744460\, 135090921\}\, \_\_mask\_was\_saved = 1\, 
&nbsp;      \_\_saved\_mask = \{\_\_val = \{0\, 0\, 3221223288\, 3221223148\, 135090990\, 
&nbsp;          3221223220\, 1\, 3221223020\, 134959818\, 64\, 1074949332\, 135491584\, 
&nbsp;          134620189\, 135466292\, 0\, 0\, 3221223424\, 64\, 135090752\, 1075154995\, 
&nbsp;          3221223148\, 3221222932\, 135090921\, 1\, 0\, 0\, 3221223136\, 0\, 4\, 4\, 16\, 
&nbsp;          0\}\}\}\}\, je\_ret = 0\, je\_mustcatch = 0 '\\000'\, je\_throw = 0\}


Attached is a copy of the code which I was testing that caused the
problem\.  Its the complete directory tree\, every file\.  Just cd into
Class\-Fields and run /usr/local/perl5\.005\_61/bin/perl \-Mblib \-d
t/fields\.t


\-\- 

Michael G Schwern                                           schwern@&#8203;pobox\.com
&nbsp;                    http&#8203;://www\.pobox\.com/~schwern
&nbsp;     /\(?&#8203;:\(?&#8203;:\(1\)\[\.\-\]?\)?\\\(?\(\\d\{3\}\)\\\)?\[\.\-\]?\)?\(\\d\{3\}\)\[\.\-\]?\(\\d\{4\}\)\(x\\d\+\)?/i

**Comment by p5pRT** [comment]
### From @schwern

[Class-Fields.tar.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/4677/4442/Class-Fields.tar.gz)

**Comment by p5pRT** [comment]
### From The RT System itself

fixed in bleadperl DEVEL7093
