### ISSUE TITLE
nested eval/sub/eval/sub has a scope bug with seeing lexicals

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#3819]
Migrated from [rt.perl.org#6743](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=6743) (status was 'resolved')

Searchable as RT6743$

**Comment by p5pRT** [comment]
### From @tobez



The bug leads to incorrect results on 5\.6\.0 \(stock FreeBSD version\) and
to a coredump on 5\.6\.1 \(fools\-gold\)\.

=====> perl \-v
This is perl\, v5\.6\.0 built for i386\-freebsd
\(with 1 registered patch\, see perl \-V for more detail\)
\[snip\]
=====> \./perl \-v
This is perl\, v5\.6\.1 built for i386\-freebsd
\(with 1 registered patch\, see perl \-V for more detail\)
\[snip\]
=====> cat b1
sub foo \{ print "Foo\\n" \}

sub trigger\_bug
\{
&nbsp;   my \($s\) = @&#8203;\_;

&nbsp;   my $r =
&nbsp;      eval \<\<'E1';
&nbsp;   sub \{
&nbsp;      return eval \<\<'E2';
&nbsp;      sub \{
&nbsp;     &$s
&nbsp;      \}
E2
&nbsp;   \}
E1
\}

trigger\_bug\(\\&foo\)\->\(\)\->\(\);
=====> perl b1
Undefined subroutine &main&#8203;:: called at \(eval 2\) line 2\.
=====> \./perl b1
segmentation fault \(core dumped\)  \./perl b1
=====> gdb \./perl perl\.core
Program terminated with signal 11\, Segmentation fault\.
Reading symbols from /usr/lib/libm\.so\.2\.\.\.\(no debugging symbols found\)\.\.\.done\.
Reading symbols from /usr/lib/libc\.so\.5\.\.\.\(no debugging symbols found\)\.\.\.done\.
Reading symbols from /usr/lib/libcrypt\.so\.2\.\.\.\(no debugging symbols found\)\.\.\.done\.
Reading symbols from /usr/lib/libutil\.so\.3\.\.\.\(no debugging symbols found\)\.\.\.done\.
Reading symbols from /usr/libexec/ld\-elf\.so\.1\.\.\.\(no debugging symbols found\)\.\.\.done\.
\#0  0x8076570 in S\_pad\_findlex \(\)
\(gdb\) bt
\#0  0x8076570 in S\_pad\_findlex \(\)
\#1  0x8076a81 in Perl\_pad\_findmy \(\)
\#2  0x8064bdf in Perl\_yylex \(\)
\#3  0x80745d1 in Perl\_yyparse \(\)
\#4  0x80b9e01 in S\_doeval \(\)
\#5  0x80bb3bf in Perl\_pp\_entereval \(\)
\#6  0x80959c6 in Perl\_runops\_standard \(\)
\#7  0x805b8c0 in S\_run\_body \(\)
\#8  0x805b600 in perl\_run \(\)
\#9  0x80590a9 in main \(\)
\#10 0x8058f6d in \_start \(\)
=====> cat b2
sub foo \{ print "Foo\\n" \}

sub trigger\_bug
\{
&nbsp;   my \($s\) = @&#8203;\_;

&nbsp;   my $r =
&nbsp;      eval \<\<'E1';
&nbsp;   sub \{
&nbsp;      my $s2 = $s;
&nbsp;      return eval \<\<'E2';
&nbsp;      sub \{
&nbsp;     &$s2
&nbsp;      \}
E2
&nbsp;   \}
E1
\}

trigger\_bug\(\\&foo\)\->\(\)\->\(\);
=====> perl b2
Foo
=====> \./perl b2
Foo

Cheers\,
&Anton\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl v5.6.1:

Configured by tobez at Thu Apr  5 22:48:17 CEST 2001.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=freebsd, osvers=5.0-current, archname=i386-freebsd
    uname='freebsd heechee.tobez.org 5.0-current freebsd 5.0-current #6: tue mar 13 01:57:38 cet 2001 root@heechee.tobez.org:usrobjusrsrcsysheechee i386 '
    config_args='-des'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -I/usr/local/include',
    optimize='-O',
    cppflags='-fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='2.95.3 20010125 (prerelease)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags ='-Wl,-E  -L/usr/local/lib'
    libpth=/usr/lib /usr/local/lib
    libs=-lm -lc -lcrypt -lutil
    perllibs=-lm -lc -lcrypt -lutil
    libc=, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags=' '
    cccdlflags='-DPIC -fpic', lddlflags='-shared  -L/usr/local/lib'

Locally applied patches:
    fools-gold


@INC for perl v5.6.1:
    lib
    /home/tobez/src/Prima
    /home/tobez/src/IPA
    /usr/local/lib/perl5/5.6.1/i386-freebsd
    /usr/local/lib/perl5/5.6.1
    /usr/local/lib/perl5/site_perl/5.6.1/i386-freebsd
    /usr/local/lib/perl5/site_perl/5.6.1
    /usr/local/lib/perl5/site_perl/5.6.0
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.6.1:
    HOME=/home/tobez
    LANG=ru_RU.KOI8-R
    LANGUAGE (unset)
    LC_MESSAGES=ASCII
    LC_MONETARY=ASCII
    LC_NUMERIC=ASCII
    LC_TIME=ASCII
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/tobez/bin:/usr/local/site/bin:/usr/local/pgsql/bin:/usr/X11R6/bin
    PERL5LIB=/home/tobez/src/Prima:/home/tobez/src/IPA
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>
