### ISSUE TITLE
Segfaults from premature GC

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#3991]
Migrated from [rt.perl.org#6998](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=6998) (status was 'resolved')

Searchable as RT6998$

**Comment by p5pRT** [comment]
### From gary@dls.net



The following should segfault most versions of Perl&#8203;:

my @&#8203;h = 1\.\.10;
bad\(@&#8203;h\);

sub bad \{
&nbsp;  undef @&#8203;h;
&nbsp;  print for @&#8203;\_;
\}

This apparently has something to do with iterating over aliased values that
have been garbage\-collected\. Is it a known issue?

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.6.1:

Configured by kevin at Sat Apr 14 03:05:46 CDT 2001.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=linux, osvers=2.4.2, archname=i686-linux
    uname='linux matrix 2.4.2 #4 sun mar 4 02:20:36 pst 2001 i686 unknown '
    config_args=''
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef
usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='cc', ccflags
='-fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFS
ET_BITS=64',
    optimize='-O3',
    cppflags='-fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='2.95.2 20000220 (Debian GNU/Linux)',
gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t',
lseeksize=8
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lndbm -ldb -ldl -lm -lc -lposix -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lposix -lcrypt -lutil
    libc=/lib/libc-2.1.3.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:



@INC for perl v5.6.1:
    /usr/local/lib/perl5/5.6.1/i686-linux
    /usr/local/lib/perl5/5.6.1
    /usr/local/lib/perl5/site_perl/5.6.1/i686-linux
    /usr/local/lib/perl5/site_perl/5.6.1
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.6.1:
    HOME=/home/gary
    LANG=C
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

> The following should segfault most versions of Perl&#8203;:
> 
> my @&#8203;h = 1\.\.10;
> bad\(@&#8203;h\);
> 
> sub bad \{
>   undef @&#8203;h;
>   print for @&#8203;\_;
> \}

pp\_iter\(\) is avoiding av\_fetch\(\) in the non\-magic case and reading
directly from the AV's xav\_array\.  Presumably this is done for speed\, but
it leads to core dumps if the elements of xav\_array have been freed\.

Since this is hot code\, I'd like it if Sarathy could take a look and let
me know if there isn't a better way\.  Patch is against perl@&#8203;10133\.

Cheers\,
\-Ben

\-\- 
signer&#8203;: can't create ~/\.sig&#8203;: Resource deadlock avoided

<details><summary>Inline Patch</summary>

```diff
--- pp_hot.c.orig	Thu May 17 10:18:48 2001
+++ pp_hot.c	Thu May 10 11:18:56 2001
@@ -1747,6 +1747,7 @@ PP(pp_iter)
     SV* sv;
     AV* av;
     SV **itersvp;
+    SV **svp;
 
     EXTEND(SP, 1);
     cx = &cxstack[cxstack_ix];
@@ -1812,10 +1813,11 @@ PP(pp_iter)
 
     SvREFCNT_dec(*itersvp);
 
-    if ((sv = SvMAGICAL(av)
-	      ? *av_fetch(av, ++cx->blk_loop.iterix, FALSE)
-	      : AvARRAY(av)[++cx->blk_loop.iterix]))
+    svp = av_fetch(av, ++cx->blk_loop.iterix, FALSE);
+    if (svp) {
+	sv = *svp;
 	SvTEMP_off(sv);
+    }
     else
 	sv = &PL_sv_undef;
     if (av != PL_curstack && sv == &PL_sv_undef) {
```
</details>

**Comment by p5pRT** [comment]
### From @gsar

Doing the following is probably faster for the common cases&#8203;:

\-    if \(\(sv = SvMAGICAL\(av\)
\+    if \(\(sv = \(SvMAGICAL\(av\) || AvREIFY\(av\)\)
&nbsp;           ? \*av\_fetch\(av\, \+\+cx\->blk\_loop\.iterix\, FALSE\)
&nbsp;           : AvARRAY\(av\)\[\+\+cx\->blk\_loop\.iterix\]\)\)


Sarathy
gsar@&#8203;ActiveState\.com

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

> Doing the following is probably faster for the common cases&#8203;:
> 
> \-    if \(\(sv = SvMAGICAL\(av\)
> \+    if \(\(sv = \(SvMAGICAL\(av\) || AvREIFY\(av\)\)
>            ? \*av\_fetch\(av\, \+\+cx\->blk\_loop\.iterix\, FALSE\)
>            : AvARRAY\(av\)\[\+\+cx\->blk\_loop\.iterix\]\)\)

That doesn't seem to stop the core dump though :\-|

Cheers\,
\-Ben

**Comment by p5pRT** [comment]
### From @gsar

Does that mean AvREIFY\(\) \*isn't\* set on av?  Or is the coredump
happening somewhere else?  A backtrace might help\.


Sarathy
gsar@&#8203;ActiveState\.com

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

> Does that mean AvREIFY\(\) \*isn't\* set on av?  Or is the coredump
> happening somewhere else?  A backtrace might help\.

Core was generated by \`\./perl bug'\.
Program terminated with signal 11\, Segmentation fault\.
Reading symbols from /lib/libnsl\.so\.1\.\.\.done\.
Reading symbols from /lib/libdl\.so\.2\.\.\.done\.
Reading symbols from /lib/libm\.so\.6\.\.\.done\.
Reading symbols from /lib/libc\.so\.6\.\.\.done\.
Reading symbols from /lib/libcrypt\.so\.1\.\.\.done\.
Reading symbols from /lib/libutil\.so\.1\.\.\.done\.
Reading symbols from /lib/ld\-linux\.so\.2\.\.\.done\.
\#0  0x80c71ef in Perl\_pp\_iter \(\) at pp\_hot\.c&#8203;:1815
1815        if \(\(sv = \(SvMAGICAL\(av\) || AvREIFY\(av\)\)
\(gdb\) bt
\#0  0x80c71ef in Perl\_pp\_iter \(\) at pp\_hot\.c&#8203;:1815
\#1  0x80c0a3a in Perl\_runops\_debug \(\) at run\.c&#8203;:53
\#2  0x805f6e9 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1496
\#3  0x805f2dd in perl\_run \(my\_perl=0x815f788\) at perl\.c&#8203;:1418
\#4  0x805c0eb in main \(argc=2\, argv=0xbffff804\, env=0xbffff810\)
&nbsp;    at perlmain\.c&#8203;:57

This is a different core than the one produced by the unpatched
pp\_hot\.c\.  Here's the backtrace from the unpatched version&#8203;:

Core was generated by \`\./perl bug'\.
Program terminated with signal 11\, Segmentation fault\.
Reading symbols from /lib/libnsl\.so\.1\.\.\.done\.
Reading symbols from /lib/libdl\.so\.2\.\.\.done\.
Reading symbols from /lib/libm\.so\.6\.\.\.done\.
Reading symbols from /lib/libc\.so\.6\.\.\.done\.
Reading symbols from /lib/libcrypt\.so\.1\.\.\.done\.
Reading symbols from /lib/libutil\.so\.1\.\.\.done\.
Reading symbols from /lib/ld\-linux\.so\.2\.\.\.done\.
\#0  0x80b2c7a in Perl\_mg\_free \(sv=0x815f8d4\) at mg\.c&#8203;:314
314             if \(vtbl && vtbl\->svt\_free\)
\(gdb\) bt
\#0  0x80b2c7a in Perl\_mg\_free \(sv=0x815f8d4\) at mg\.c&#8203;:314
\#1  0x80d4ee9 in Perl\_sv\_clear \(sv=0x815f8d4\) at sv\.c&#8203;:4459
\#2  0x80d549a in Perl\_sv\_free \(sv=0x815f8d4\) at sv\.c&#8203;:4643
\#3  0x80c71b0 in Perl\_pp\_iter \(\) at pp\_hot\.c&#8203;:1813
\#4  0x80c0a3a in Perl\_runops\_debug \(\) at run\.c&#8203;:53
\#5  0x805f6e9 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1496
\#6  0x805f2dd in perl\_run \(my\_perl=0x815f768\) at perl\.c&#8203;:1418
\#7  0x805c0eb in main \(argc=2\, argv=0xbffff804\, env=0xbffff810\)
&nbsp;    at perlmain\.c&#8203;:57

Cheers\,
\-Ben

**Comment by p5pRT** [comment]
### From @gsar

It needs the rest of your patch\, since av\_fetch\(\) will return Nullsv
there\.


Sarathy
gsar@&#8203;ActiveState\.com
<details><summary>Inline Patch</summary>

```diff
-----------------------------------8<-----------------------------------
Change 10145 by gsar@rake on 2001/05/17 16:59:55

	fix for ID 20010515.004 (needs test)

Affected files ...

... //depot/maint-5.6/perl/pp_hot.c#29 edit

Differences ...

==== //depot/maint-5.6/perl/pp_hot.c#29 (text) ====
Index: perl/pp_hot.c
--- perl/pp_hot.c.~1~	Thu May 17 11:00:04 2001
+++ perl/pp_hot.c	Thu May 17 11:00:04 2001
@@ -1737,9 +1737,17 @@
 
     SvREFCNT_dec(*itersvp);
 
-    if ((sv = SvMAGICAL(av)
-	      ? *av_fetch(av, ++cx->blk_loop.iterix, FALSE) 
-	      : AvARRAY(av)[++cx->blk_loop.iterix]))
+    if (SvMAGICAL(av) || AvREIFY(av)) {
+	SV **svp = av_fetch(av, ++cx->blk_loop.iterix, FALSE);
+	if (svp)
+	    sv = *svp;
+	else
+	    sv = Nullsv;
+    }
+    else {
+	sv = AvARRAY(av)[++cx->blk_loop.iterix];
+    }
+    if (sv)
 	SvTEMP_off(sv);
     else
 	sv = &PL_sv_undef;
End of Patch.
```
</details>

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

> It needs the rest of your patch\, since av\_fetch\(\) will return Nullsv
> there\.

Thanks\, I'll roll a test\.

Cheers\,
\-Ben

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Cheers\,
\-Ben

\-\- 
signer&#8203;: can't create ~/\.sig&#8203;: Invalid or incomplete multibyte or wide character

<details><summary>Inline Patch</summary>

```diff
--- t/op/misc.t.orig	Thu May 17 15:29:24 2001
+++ t/op/misc.t	Thu May 17 15:32:48 2001
@@ -660,3 +660,15 @@
 # coredump in 5.7.1
 close STDERR; die;
 EXPECT
+########
+# Bug 20010515.004
+my @h = 1 .. 10;
+bad(@h);
+sub bad {
+   undef @h;
+   print "O";
+   print for @_;
+   print "K";
+}
+EXPECT
+OK
```
</details>

**Comment by p5pRT** [comment]
### From @jhi

Thanks\, applied\.
