### ISSUE TITLE
eval "return;a a a a a a-a;sub" segfaults on 5.7.1

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4045]
Migrated from [rt.perl.org#7058](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=7058) (status was 'resolved')

Searchable as RT7058$

**Comment by p5pRT** [comment]
### From iltzu@sci.fi



The following code segfaults on both 5\.7\.1 and bleadperl@&#8203;10259&#8203;:

&nbsp;  eval "return;a a a a a a\-a;sub"

The eval seems to be needed to trigger the bug\.  So is the return
and the seven barewords\, but any bareword will do instead of "a"\.
Some punctuation between the last two barewords will trigger the
bug\, some doesn't\, and I can't see any pattern there\.

The contrived test case was produced by my Markov chain random
input tester \-\- it's the first segfault it has generated that
hasn't involved "\\x\{"\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.7.1:

Configured by iltzu at Sun May 20 02:07:22 EEST 2001.

Summary of my perl5 (revision 5.0 version 7 subversion 1) configuration:
  Platform:
    osname=linux, osvers=2.2.14-storm, archname=i586-linux-64int-ld
    uname='linux storm 2.2.14-storm #2 mon jan 24 10:48:57 pst 2000 i586 unknown '
    config_args=''
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=define use64bitall=undef uselongdouble=define
  Compiler:
    cc='gcc', ccflags ='-fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2',
    cppflags='-fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='2.95.2 20000220 (Debian GNU/Linux)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long long', ivsize=8, nvtype='long double', nvsize=12, Off_t='off_t', lseeksize=8
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lndbm -ldb -ldl -lm -lc -lposix -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lposix -lcrypt -lutil
    libc=/lib/libc-2.1.3.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.7.1:
    /usr/local/perl5.7.1/lib/5.7.1/i586-linux-64int-ld
    /usr/local/perl5.7.1/lib/5.7.1
    /usr/local/perl5.7.1/lib/site_perl/5.7.1/i586-linux-64int-ld
    /usr/local/perl5.7.1/lib/site_perl/5.7.1
    /usr/local/perl5.7.1/lib/site_perl
    /usr/local/lib/site_perl
    /usr/lib/perl5
    .


Environment for perl v5.7.1:
    HOME=/home/iltzu
    LANG=C
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Okay\, further information\.  The problem is almost certainly related to
scratchpad allocation\, as shown by the following stack backtrace&#8203;:

&nbsp;  \(gdb\) run \-e 'eval "a\.b\.c\.d\.e\.f;sub"'
&nbsp;  Starting program&#8203;: /home/iltzu/bleadperl/\./perl \-e 'eval "a\.b\.c\.d\.e\.f;sub"'

&nbsp;  Program received signal SIGSEGV\, Segmentation fault\.
&nbsp;  0x808796c in Perl\_pad\_free \(po=4\) at op\.c&#8203;:550
&nbsp;  550             SvPADTMP\_off\(PL\_curpad\[po\]\);
&nbsp;  \(gdb\) bt
&nbsp;  \#0  0x808796c in Perl\_pad\_free \(po=4\) at op\.c&#8203;:550
&nbsp;  \#1  0x8087e48 in Perl\_op\_clear \(o=0x8161b48\) at op\.c&#8203;:852
&nbsp;  \#2  0x8087bb2 in Perl\_op\_free \(o=0x8161b48\) at op\.c&#8203;:727
&nbsp;  \#3  0x8087b55 in Perl\_op\_free \(o=0x8161bc8\) at op\.c&#8203;:715
&nbsp;  \#4  0x8087b55 in Perl\_op\_free \(o=0x8161bf0\) at op\.c&#8203;:715
&nbsp;  \#5  0x8087b55 in Perl\_op\_free \(o=0x8159540\) at op\.c&#8203;:715
&nbsp;  \#6  0x80ff92b in S\_doeval \(gimme=128\, startop=0x0\) at pp\_ctl\.c&#8203;:2900
&nbsp;  \#7  0x8101a79 in Perl\_pp\_entereval \(\) at pp\_ctl\.c&#8203;:3444
&nbsp;  \#8  0x80c01bd in Perl\_runops\_debug \(\) at run\.c&#8203;:53
&nbsp;  \#9  0x805fadf in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1498
&nbsp;  \#10 0x805f6a2 in perl\_run \(my\_perl=0x8155748\) at perl\.c&#8203;:1420
&nbsp;  \#11 0x805c1c5 in main \(argc=3\, argv=0xbffffbb4\, env=0xbffffbc4\)
&nbsp;      at perlmain\.c&#8203;:57
&nbsp;  \(gdb\) print PL\_curpad\[4\]
&nbsp;  $1 = \(SV \*\) 0x1

So SvPADTMP\_off is trying to use 0x1 as an SV\* and segfaults\.

Well\, I just looked into it a bit more\.  It seems the problem is that
start\_subparse\(\) is saving and changing PL\_comppad\.  When the syntax
error is then detected\, leave\_scope\(\) should restore the old PL\_comppad\.
For some reason\, however\, this isn't happening inside an eval\, and so
pad\_free\(\) ends up accessing the wrong pad\!

The next question is why\, and how can it be fixed?

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

&nbsp;  eval "a\.b\.c\.d\.e\.f;sub"

and seems to have no harmful side effects\.  That doesn't mean I consider
it a good solution \-\- it should either be replaced by a more fundamental
fix\, or at least be justified somehow as a valid cleanup step\.

\(Unfortunately I'm totally out of my depth when it comes to locating the
actual cause\, which is hidden somewhere inside \(or behind\) yyparse\.\)


<details><summary>Inline Patch</summary>

```diff
--- pp_ctl.c.orig	Thu May 31 16:13:12 2001
+++ pp_ctl.c	Sun Jun  3 00:33:45 2001
@@ -2800,6 +2800,7 @@
     CV *caller;
     AV* comppadlist;
     I32 i;
+    I32 savestack_ix_hack;
 
     PL_in_eval = ((saveop && saveop->op_type == OP_REQUIRE)
 		  ? (EVAL_INREQUIRE | (PL_in_eval & EVAL_INEVAL))
@@ -2888,12 +2889,18 @@
 	PL_in_eval |= EVAL_KEEPERR;
     else
 	sv_setpv(ERRSV,"");
+    savestack_ix_hack = PL_savestack_ix; /* XXX */
     if (yyparse() || PL_error_count || !PL_eval_root) {
 	SV **newsp;
 	I32 gimme;
 	PERL_CONTEXT *cx;
 	I32 optype = 0;			/* Might be reset by POPEVAL. */
 	STRLEN n_a;
+
+	/* XXX This just hides the symptoms (segfaults in op_free) of
+	   stack imbalance apparently produced by syntax errors just
+	   after start_subparse.  Really should fix the cause. */
+	LEAVE_SCOPE(savestack_ix_hack);
 	
 	PL_op = saveop;
 	if (PL_eval_root) {
```
</details>

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Sun\, 3 Jun 2001\, Ilmari Karonen wrote&#8203;:
> 
> Here's a patch that forces PL\_savestack back to its expected state when
> cleaning up after a failed eval\.  It fixes the segfault produced by
> 
>   eval "a\.b\.c\.d\.e\.f;sub"
> 
> and seems to have no harmful side effects\.  That doesn't mean I consider
> it a good solution \-\- it should either be replaced by a more fundamental
> fix\, or at least be justified somehow as a valid cleanup step\.

Well\, I found the cause\.  The parser is calling start\_subparse\(\) as soon
as the tokenizer hands it an ANONSUB token\, and then failing before it
gets around to calling newANONATTRSUB\(\) that would unwind the stack\.

This could perhaps be avoided with some careful tweaking of the grammar
rules\, but I don't think it's worth the trouble\.  The explicit unwind in
my patch seems quite reasonable in comparison\.  \(The reason this wasn't
happening outside eval is that perl\_destruct\(\) already does an explicit
LEAVE before op\_free\(\)\, which accomplishes the same thing\.\)

So here's the patch again\, with less scary comments this time&#8203;:


<details><summary>Inline Patch</summary>

```diff
--- pp_ctl.c.orig	Thu May 31 16:13:12 2001
+++ pp_ctl.c	Sun Jun  3 20:58:52 2001
@@ -2800,6 +2800,7 @@
     CV *caller;
     AV* comppadlist;
     I32 i;
+    I32 savestack_ix_save;
 
     PL_in_eval = ((saveop && saveop->op_type == OP_REQUIRE)
 		  ? (EVAL_INREQUIRE | (PL_in_eval & EVAL_INEVAL))
@@ -2888,12 +2889,18 @@
 	PL_in_eval |= EVAL_KEEPERR;
     else
 	sv_setpv(ERRSV,"");
+    savestack_ix_save = PL_savestack_ix;
     if (yyparse() || PL_error_count || !PL_eval_root) {
 	SV **newsp;
 	I32 gimme;
 	PERL_CONTEXT *cx;
 	I32 optype = 0;			/* Might be reset by POPEVAL. */
 	STRLEN n_a;
+
+	/* If a syntax error occurs in certain critical places (like
+	   just after "sub"), unpopped data may be left on the save
+	   stack.  This cleans it up.  (Fixes segfaults in op_free.)  */
+	LEAVE_SCOPE(savestack_ix_save);
 	
 	PL_op = saveop;
 	if (PL_eval_root) {
```
</details>

**Comment by p5pRT** [comment]
### From @gsar

I think it might be worth trying\, because I'm not completely sure that
the LEAVE\_SCOPE\(\) after the yyparse\(\) won't take away something that
is still needed\.  I'd prefer to vacate the innermost scope where the
error happened instead of \(potentially prematurely vacating\) the
outermost one\.

You could try adding an error production more\-or\-less like&#8203;:

&nbsp;    subrout :    \[\.\.\.\]
&nbsp;            |    SUB startsub error
&nbsp;                         \{ LEAVE\_SCOPE\($2\); \}

>The explicit unwind in
>my patch seems quite reasonable in comparison\.  \(The reason this wasn't
>happening outside eval is that perl\_destruct\(\) already does an explicit
>LEAVE before op\_free\(\)\, which accomplishes the same thing\.\)
>
>So here's the patch again\, with less scary comments this time&#8203;:
>
>
>\-\-\- pp\_ctl\.c\.orig    Thu May 31 16&#8203;:13&#8203;:12 2001
>\+\+\+ pp\_ctl\.c    Sun Jun  3 20&#8203;:58&#8203;:52 2001
>@&#8203;@&#8203; \-2800\,6 \+2800\,7 @&#8203;@&#8203;
>     CV \*caller;
>     AV\* comppadlist;
>     I32 i;
>\+    I32 savestack\_ix\_save;
> 
>     PL\_in\_eval = \(\(saveop && saveop\->op\_type == OP\_REQUIRE\)
>           ? \(EVAL\_INREQUIRE | \(PL\_in\_eval & EVAL\_INEVAL\)\)
>@&#8203;@&#8203; \-2888\,12 \+2889\,18 @&#8203;@&#8203;
>     PL\_in\_eval |= EVAL\_KEEPERR;
>     else
>     sv\_setpv\(ERRSV\,""\);
>\+    savestack\_ix\_save = PL\_savestack\_ix;
>     if \(yyparse\(\) || PL\_error\_count || \!PL\_eval\_root\) \{
>     SV \*\*newsp;
>     I32 gimme;
>     PERL\_CONTEXT \*cx;
>     I32 optype = 0;            /\* Might be reset by POPEVAL\. \*/
>     STRLEN n\_a;
>\+
>\+    /\* If a syntax error occurs in certain critical places \(like
>\+       just after "sub"\)\, unpopped data may be left on the save
>\+       stack\.  This cleans it up\.  \(Fixes segfaults in op\_free\.\)  \*/
>\+    LEAVE\_SCOPE\(savestack\_ix\_save\);
>     
>     PL\_op = saveop;
>     if \(PL\_eval\_root\) \{


Sarathy
gsar@&#8203;ActiveState\.com

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

I suppose adding those error handling rules might still be a good idea\,
but the patch I proposed is now useless\.  Oh well\.\.

**Comment by p5pRT** [comment]
### From @gsar

Good\. :\-\)

I suspected as much\, but wasn't sure\.


Sarathy
gsar@&#8203;ActiveState\.com

**Comment by p5pRT** [comment]
### From @jhi

5\.8\.0 final seems to do this&#8203;:

perl \-le 'eval "return;a a a a a a\-a;sub";print $@&#8203;'
syntax error at \(eval 1\) line 2\, at EOF

while 5\.8\.1\-to\-be \(and 5\.9\.0\-to\-be\) seem to do this&#8203;:

\./perl \-le 'eval "return;a a a a a a\-a;sub";print $@&#8203;'
Illegal declaration of anonymous subroutine at \(eval 1\) line 2\.

so I think this can problem ticket can be marked as resolved\.

**Comment by p5pRT** [comment]
@jhi - Status changed from 'open' to 'resolved'
