### ISSUE TITLE
[FATAL 5.005_03 & 5.005_60] Segfault in Perl_pad_free

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#406]
Migrated from [rt.perl.org#1241](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=1241) (status was 'resolved')

Searchable as RT1241$

**Comment by p5pRT** [comment]
### From @schwern

$ perl \-cw Schema\.pm
Global symbol "%COLUMNS" requires explicit package name at Schema\.pm line 203\.
syntax error at Schema\.pm line 233\, near "no strict ="
Segmentation fault

Simliar error with 5\.005\_60\.\.\.

$ /usr/local/perl5\.005\_60/bin/perl \-cw Schema\.pm
Global symbol "%COLUMNS" requires explicit package name at Schema\.pm line 203\.
syntax error at Schema\.pm line 233\, near "no strict ="
defined\(%hash\) is deprecated at Schema\.pm line 235\.
\(Maybe you should just omit the defined\(\)?\)
Segmentation fault


No core file was generated\.  Fortunately\, I happen to have 5\.005\_60
compiled with debugging flags&#8203;:


Program received signal SIGSEGV\, Segmentation fault\.
0x807fc88 in Perl\_pad\_free \(po=6\) at op\.c&#8203;:496
496             SvPADTMP\_off\(PL\_curpad\[po\]\);
\(gdb\) bt
\#0  0x807fc88 in Perl\_pad\_free \(po=6\) at op\.c&#8203;:496
\#1  0x8080068 in S\_op\_clear \(o=0x823e848\) at op\.c&#8203;:723
\#2  0x807fe70 in Perl\_op\_free \(o=0x823e848\) at op\.c&#8203;:650
\#3  0x807fe15 in Perl\_op\_free \(o=0x823e6c8\) at op\.c&#8203;:638
\#4  0x807fe15 in Perl\_op\_free \(o=0x823de88\) at op\.c&#8203;:638
\#5  0x807fe15 in Perl\_op\_free \(o=0x8240488\) at op\.c&#8203;:638
\#6  0x807fe15 in Perl\_op\_free \(o=0x823fbc8\) at op\.c&#8203;:638
\#7  0x807fe15 in Perl\_op\_free \(o=0x823fa48\) at op\.c&#8203;:638
\#8  0x807fe15 in Perl\_op\_free \(o=0x823fb48\) at op\.c&#8203;:638
\#9  0x807fe15 in Perl\_op\_free \(o=0x8243ec8\) at op\.c&#8203;:638
\#10 0x807fe15 in Perl\_op\_free \(o=0x8243f08\) at op\.c&#8203;:638
\#11 0x807fe15 in Perl\_op\_free \(o=0x8243988\) at op\.c&#8203;:638
\#12 0x8088abf in Perl\_newSUB \(floor=84\, o=0x823e0c8\, proto=0x0\, 
&nbsp;    block=0x8243988\) at op\.c&#8203;:4010
\#13 0x807cb8d in Perl\_yyparse \(\) at perly\.y&#8203;:293
\#14 0x805bcbb in S\_parse\_body \(args=0xbffffb74\) at perl\.c&#8203;:951
\#15 0x80d517e in Perl\_vdefault\_protect \(excpt=0xbffffb84\, 
&nbsp;    body=0x805b330 \<S\_parse\_body>\, args=0xbffffb54\) at scope\.c&#8203;:44
\#16 0x80d50b0 in Perl\_default\_protect \(excpt=0xbffffb84\, 
&nbsp;    body=0x805b330 \<S\_parse\_body>\) at scope\.c&#8203;:25
\#17 0x805b23f in perl\_parse \(my\_perl=0x8128408\, xsinit=0x8059758 \<xs\_init>\, 
&nbsp;    argc=3\, argv=0xbffffc34\, env=0x0\) at perl\.c&#8203;:630
\#18 0x80596f9 in main \(argc=3\, argv=0xbffffc34\, env=0xbffffc44\)
&nbsp;    at perlmain\.c&#8203;:51

Some other useful information&#8203;:
\(gdb\) print \*\*PL\_curpad
$15 = \{sv\_any = 0x0\, sv\_refcnt = 2147483170\, sv\_flags = 8388608\}
That ref count is a wee high\, no?


I'm sorry\, I can't provide a copy of the module which caused the
problem\, its kinda confidential\.  I'll try to break it down into a
simple case\, but somehow I doubt I can do that\.



Summary of my perl5 \(revision 5\.0 version 5 subversion 60\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.2\.10\, archname=i686\-linux
&nbsp;    uname='linux athens 2\.2\.10 \#3 smp mon aug 2 16&#8203;:48&#8203;:09 edt 1999 i686 unknown '
&nbsp;    config\_args=''
&nbsp;    hint=previous\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef useperlio=undef d\_sfio=undef
&nbsp;    use64bits=undef usemultiplicity=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'\, optimize='\-g'\, gccversion=2\.95\.1 19990809 \(prerelease\)
&nbsp;    cppflags='\-Dbool=char \-DHAS\_BOOL \-DDEBUGGING \-DDEBUGGING\_MSTATS \-DDEBUGGING\_OPS'
&nbsp;    ccflags ='\-Dbool=char \-DHAS\_BOOL \-DDEBUGGING \-DDEBUGGING\_MSTATS \-DDEBUGGING\_OPS'
&nbsp;    stdchar='char'\, d\_stdstdio=define\, usevfork=false
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    alignbytes=4\, usemymalloc=y\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-lndbm \-lgdbm \-ldbm \-ldb \-ldl \-lm \-lrt \-lc \-lposix \-lcrypt
&nbsp;    libc=/lib/libc\-2\.1\.2\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
&nbsp;    cccdlflags='\-fpic'\, lddlflags='\-shared \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: DEBUGGING
&nbsp;  Built under linux
&nbsp;  Compiled at Aug 17 1999 18&#8203;:05&#8203;:39
&nbsp;  %ENV&#8203;:
&nbsp;    PERL5LIB="/home/schwern/lib/perl5/site\_perl/5\.005"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /home/schwern/lib/perl5/site\_perl/5\.005/i686\-linux
&nbsp;    /home/schwern/lib/perl5/site\_perl/5\.005
&nbsp;    /usr/local/perl5\.005\_60/lib/i686\-linux
&nbsp;    /usr/local/perl5\.005\_60/lib
&nbsp;    /usr/local/perl5\.005\_60/lib/site\_perl/5\.00560/i686\-linux
&nbsp;    /usr/local/perl5\.005\_60/lib/site\_perl
&nbsp;    \.

\-\- 

Michael G Schwern                                           schwern@&#8203;pobox\.com
&nbsp;                    http&#8203;://www\.pobox\.com/~schwern
&nbsp;     /\(?&#8203;:\(?&#8203;:\(1\)\[\.\-\]?\)?\\\(?\(\\d\{3\}\)\\\)?\[\.\-\]?\)?\(\\d\{3\}\)\[\.\-\]?\(\\d\{4\}\)\(x\\d\+\)?/i

**Comment by p5pRT** [comment]
### From @schwern

On Fri\, Aug 20\, 1999 at 12&#8203;:54&#8203;:00PM \-0400\, Spider Boardman wrote&#8203;:
> I don't know what gdb means by '$15'\.  What would be the result of
> 
>     \(gdb\) print PL\_curpad\[6\]\[0\]
> 
> The high sv\_refcnt you saw is normal for things marked readonly
> at compile time\, since it helps to keep the constants around\.

\(gdb\) print PL\_curpad\[6\]\[0\]
Cannot access memory at address 0x55555555\.


Okay\, I can see this is going to be a painful debugging process\, so
I'm just going to give you guys a copy of the code causing the error\.
However\, I'm about to leave for TPC in like\, 5 minutes\.  I'll send the
code along later\, sorry to be a tease\!


\-\- 

Michael G Schwern                                           schwern@&#8203;pobox\.com
&nbsp;                    http&#8203;://www\.pobox\.com/~schwern
&nbsp;     /\(?&#8203;:\(?&#8203;:\(1\)\[\.\-\]?\)?\\\(?\(\\d\{3\}\)\\\)?\[\.\-\]?\)?\(\\d\{3\}\)\[\.\-\]?\(\\d\{4\}\)\(x\\d\+\)?/i
