### ISSUE TITLE
Core dump with File::Glob

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4069]
Migrated from [rt.perl.org#7101](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=7101) (status was 'resolved')

Searchable as RT7101$

**Comment by p5pRT** [comment]
### From skarkkai@woods.iki.fi



perl \-we 'use File&#8203;::Glob "&#8203;:glob"; glob \("\*"\); glob \("\*"\);'
or
perl \-we 'use File&#8203;::Glob "&#8203;:glob"; \<\*>; \<\*>;'

dumps core or gives out of memory error\. Happens on perl 5\.6\.0 on Redhat
7\.1\, and perl 5\.6\.1 on FreeBSD\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.6.0:

Configured by prospector at Fri Mar 23 12:48:14 EST 2001.

Summary of my perl5 (revision 5.0 version 6 subversion 0) configuration:
  Platform:
    osname=linux, osvers=2.2.17-8smp, archname=i386-linux
    uname='linux porky.devel.redhat.com 2.2.17-8smp #1 smp fri nov 17 16:12:17 est 2000 i686 unknown '
    config_args='-des -Doptimize=-O2 -march=i386 -mcpu=i686 -Dcc=gcc -Dcccdlflags=-fPIC -Dinstallprefix=/usr -Dprefix=/usr -Darchname=i386-linux -Dd_dosuid -Dd_semctl_semun -Di_db -Di_ndbm -Di_gdbm -Di_shadow -Di_syslog -Dman3ext=3pm -Uuselargefiles'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=undef 
    use64bitint=undef use64bitall=undef uselongdouble=undef usesocks=undef
  Compiler:
    cc='gcc', optimize='-O2 -march=i386 -mcpu=i686', gccversion=2.96 20000731 (Red Hat Linux 7.1 2.96-79)
    cppflags='-fno-strict-aliasing'
    ccflags ='-fno-strict-aliasing'
    stdchar='char', d_stdstdio=define, usevfork=false
    intsize=4, longsize=4, ptrsize=4, doublesize=8
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=4
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -ldl -lm -lc -lcrypt
    libc=/lib/libc-2.2.2.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.0:
    /usr/lib/perl5/5.6.0/i386-linux
    /usr/lib/perl5/5.6.0
    /usr/lib/perl5/site_perl/5.6.0/i386-linux
    /usr/lib/perl5/site_perl/5.6.0
    /usr/lib/perl5/site_perl
    .


Environment for perl v5.6.0:
    HOME=/home/skarkkai
    LANG=en_US
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/skarkkai/bin:/home/skarkkai/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/bin:/usr/X11R6/bin:/sbin:/usr/sbin:/usr/local/sbin:/opt/gnome/bin:/sbin:/usr/sbin:/usr/local/sbin:/opt/gnome/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @nwc10

And devel 10439 on FreeBSD\, and devel 10483 on arm linux\, so it's still
current and repeatable\.

FreeBSD said&#8203;:
\./perl \-I lib \-we 'use File&#8203;::Glob "&#8203;:glob"; glob \("\*"\); glob \("\*"\);'
perl in realloc\(\)&#8203;: warning&#8203;: modified \(chunk\-\) pointer\.
Out of memory\!

linux was plain "Segmentation fault" and I can't get a backtrace apart
from memcpy\(\)\.

Thanks for this report\.

Nicholas Clark

**Comment by p5pRT** [comment]
### From @jhi

kosh&#8203;:/tmp/jhi/perl ; gdb \./perl core\.perl\.kosh\.0 
GDB is free software and you are welcome to distribute copies of it
 under certain conditions; type "show copying" to see the conditions\.
There is absolutely no warranty for GDB; type "show warranty" for details\.
GDB 4\.16 \(alpha\-dec\-osf4\.0\)\, Copyright 1996 Free Software Foundation\, Inc\.\.\.
Core was generated by \`perl'\.
Program terminated with signal 11\, Segmentation fault\.
Reading symbols from /tmp/jhi/perl/libperl\.so\.\.\.done\.
Reading symbols from /usr/shlib/libm\.so\.\.\.done\.
Reading symbols from /usr/shlib/libiconv\.so\.\.\.done\.
Reading symbols from /usr/shlib/libc\.so\.\.\.done\.
Reading symbols from /usr/lib/nls/loc//fi\_FI\.ISO8859\-1\.\.\.done\.
Reading symbols from lib/auto/File/Glob/Glob\.so\.\.\.done\.
\#0  0x3ff8019ed40 in NLstrlen \(\)
\(gdb\) where
\#0  0x3ff8019ed40 in NLstrlen \(\)
\#1  0x300000040cc in XS\_File\_\_Glob\_doglob \(cv=0x14005faf0\) at Glob\.c&#8203;:191
\#2  0x3ffbff68a0c in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:2715
\#3  0x3ffbff5c6ec in Perl\_runops\_debug \(\) at run\.c&#8203;:53
\#4  0x3ffbfedeec4 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1498
\#5  0x3ffbfedeb34 in perl\_run \(my\_perl=0x140002280\) at perl\.c&#8203;:1420
\#6  0x120001f74 in main \(argc=4\, argv=0x11ffff428\, env=0x11ffff450\)
&nbsp;    at perlmain\.c&#8203;:57
\(gdb\)

**Comment by p5pRT** [comment]
### From @jhi

\#line 183 "Glob\.c"
XS\(XS\_File\_\_Glob\_doglob\); /\* prototype to pass \-Wmissing\-prototypes \*/
XS\(XS\_File\_\_Glob\_doglob\)
\{
&nbsp;    dXSARGS;
&nbsp;    if \(items \< 1\)
&nbsp;        Perl\_croak\(aTHX\_ "Usage&#8203;: File&#8203;::Glob&#8203;::doglob\(pattern\, \.\.\.\)"\);
&nbsp;    SP \-= items;
&nbsp;    \{
&nbsp;        char \*  pattern = \(char \*\)SvPV\(ST\(0\)\,PL\_na\);
\#line 180 "Glob\.xs"

The line \#191 is the pattern assignment\.

\(gdb\) p PL\_stack\_base\[0\]
$1 = \(SV \*\) 0x3ffffffafa0
\(gdb\) p \*PL\_stack\_base\[0\]
$2 = \{sv\_any = 0x0\, sv\_refcnt = 2147483459\, sv\_flags = 8388608\}
\(gdb\) call Perl\_sv\_dump\(PL\_stack\_base\[0\]\)
SV = NULL\(0x0\) at 0x3ffffffafa0
&nbsp;  REFCNT = 2147483459
&nbsp;  FLAGS = \(READONLY\)
\(gdb\) 

> \#2  0x3ffbff68a0c in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:2715
> \#3  0x3ffbff5c6ec in Perl\_runops\_debug \(\) at run\.c&#8203;:53
> \#4  0x3ffbfedeec4 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1498
> \#5  0x3ffbfedeb34 in perl\_run \(my\_perl=0x140002280\) at perl\.c&#8203;:1420
> \#6  0x120001f74 in main \(argc=4\, argv=0x11ffff428\, env=0x11ffff450\)
>     at perlmain\.c&#8203;:57
> \(gdb\) 
> 
> \-\- 
> $jhi\+\+; \# http&#8203;://www\.iki\.fi/jhi/
>         \# There is this special biologist word we use for 'stable'\.
>         \# It is 'dead'\. \-\- Jack Cohen

**Comment by p5pRT** [comment]
### From @smpeters

I've tried to recreate this core dump on various Perl 5\.8s on Linux\,
FreeBSD\, Mac OS X\, and Cygwin\.  I did not get any errors back at all\, so
it appears this has been fixed\.

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'resolved'
