### ISSUE TITLE
seg fault using Benchmark module

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4072]
Migrated from [rt.perl.org#7104](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=7104) (status was 'resolved')

Searchable as RT7104$

**Comment by p5pRT** [comment]
### From qchen@snet.net


The following leads to segmentation fault or hang&#8203;:

$ cat foo\.pl
\#\!/usr/local/bin/perl
use strict;
use Benchmark;
my @&#8203;words = qw\(this is foo test bar string\);
timethese \( 1 => \{
'use eval' => q&#8203;:
&nbsp;    for my $item \(qw\(foo bar\)\) \{
&nbsp;        my $match = eval 'sub \{ $\_\[0\] =~ /$item/o \}';
&nbsp;        @&#8203;results = grep $match\->\($\_\)\, @&#8203;words;
&nbsp;    \};
:\,
\}\);

$ \./foo\.pl
Benchmark&#8203;: timing 1 iterations of use eval\.\.\.
Segmentation fault \(core dumped\)

<details><summary>Perl Info</summary>

```

Flags:
    category=utilities
    severity=low

Site configuration information for perl v5.6.1:

Configured by richard at Wed Apr 11 08:39:09 EDT 2001.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=linux, osvers=2.2.14-5.0, archname=i686-linux
    uname='linux dell 2.2.14-5.0 #1 tue mar 7 21:07:39 est 2000 i686 unknown '
    config_args='-de'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2',
    cppflags='-fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='egcs-2.91.66 19990314/Linux (egcs-1.1.2 release)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lndbm -lgdbm -ldb -ldl -lm -lc -lposix -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lposix -lcrypt -lutil
    libc=/lib/libc-2.1.3.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.1:
    /usr/local/lib/perl5/5.6.1/i686-linux
    /usr/local/lib/perl5/5.6.1
    /usr/local/lib/perl5/site_perl/5.6.1/i686-linux
    /usr/local/lib/perl5/site_perl/5.6.1
    /usr/local/lib/perl5/site_perl/5.6.0/i686-linux
    /usr/local/lib/perl5/site_perl/5.6.0
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.6.1:
    HOME=/home/richard
    LANG=en_US
    LANGUAGE (unset)
    LD_LIBRARY_PATH=/u01/app/oracle/product/8.1.7/lib
    LOGDIR (unset)
    PATH=/usr/java/jdk1.3/bin:office52/program:/usr/local/apache/bin:/usr/local/bin:/usr/local/sbin:/usr/kerberos/bin:/bin:/usr/bin:/usr/X11R6/bin:/u01/app/oracle/product/8.1.7/bin:/sbin:/usr/sbin:.:/home/richard/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash2

```
</details>

**Comment by p5pRT** [comment]
### From @simoncozens

Will investigate after lunch\, but&#8203;:

\#0  0x8086ef5 in S\_pad\_findlex \(name=0x8156ce0 "@&#8203;\_"\, newoff=0\, seq=238\, 
&nbsp;    startcv=0x8199724\, cx\_ix=10\, saweval=0\, flags=0\) at op\.c&#8203;:248
248     AV \*curlist = CvPADLIST\(cv\);
\(gdb\) bt
\#0  0x8086ef5 in S\_pad\_findlex \(name=0x8156ce0 "@&#8203;\_"\, newoff=0\, seq=238\, 
&nbsp;    startcv=0x8199724\, cx\_ix=10\, saweval=0\, flags=0\) at op\.c&#8203;:248
\#1  0x80876de in Perl\_pad\_findmy \(name=0x8156ce0 "@&#8203;\_"\) at op\.c&#8203;:436
\#2  0x806d7bf in Perl\_yylex \(\) at toke\.c&#8203;:2225
\#3  0x80835f2 in Perl\_yyparse \(\) at perly\.c&#8203;:1542
\#4  0x8100ed7 in S\_doeval \(gimme=0\, startop=0x0\) at pp\_ctl\.c&#8203;:2891
\#5  0x8103081 in Perl\_pp\_entereval \(\) at pp\_ctl\.c&#8203;:3444
\#6  0x80c132d in Perl\_runops\_debug \(\) at run\.c&#8203;:53
\#7  0x805fb3f in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1498
\#8  0x805f702 in perl\_run \(my\_perl=0x81575c8\) at perl\.c&#8203;:1420
\#9  0x805c215 in main \(argc=2\, argv=0xbffff78c\, env=0xbffff798\)
&nbsp;    at perlmain\.c&#8203;:57
\#10 0x4007e2eb in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6
\(gdb\) print \*cv
$2 = \{sv\_any = 0x0\, sv\_refcnt = 1\, sv\_flags = 0\}

**Comment by p5pRT** [comment]
### From @gsar

FWIW\, I can't reproduce this with maint\-5\.6@&#8203;10472\.


Sarathy
gsar@&#8203;ActiveState\.com

**Comment by p5pRT** [comment]
### From @simoncozens

It seems this bug was fixed somewhere between patch 10155 and 10472\.

Richard\, this means that versions 5\.7\.2 and 5\.6\.2 of Perl will both contain
a fix to this bug\. Thanks very much for your report\.
