### ISSUE TITLE
segmentation fault in Perl_sv_2bool

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4086]
Migrated from [rt.perl.org#7121](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=7121) (status was 'resolved')

Searchable as RT7121$

**Comment by p5pRT** [comment]
### From dlux@spam.sch.bme.hu



I got a segfault\, here is the stack trace&#8203;:

\#0  0x80c772b in Perl\_sv\_2bool \(sv=0x81fb7b4\) at sv\.c&#8203;:2353
\#1  0x80b8fac in Perl\_pp\_cond\_expr \(\) at pp\_hot\.c&#8203;:123
\#2  0x80b863d in Perl\_runops\_debug \(\) at run\.c&#8203;:53
\#3  0x8066ba3 in Perl\_amagic\_call \(left=0x82fea14\, right=0x813f958\, method=30\, 
&nbsp;    flags=0\) at gv\.c&#8203;:1588
\#4  0x80d6341 in Perl\_pp\_gt \(\) at pp\.c&#8203;:1181
\#5  0x80b863d in Perl\_runops\_debug \(\) at run\.c&#8203;:53
\#6  0x805dd5f in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1471
\#7  0x805d931 in perl\_run \(my\_perl=0x8140280\) at perl\.c&#8203;:1393
\#8  0x805a205 in main \(argc=6\, argv=0xbffff944\, env=0xbffff960\) at perlmain\.c&#8203;:52
\#9  0x4006338b in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6

The segfault is caused by a "make test" in the upcoming release of Class&#8203;::Date 1\.1\.0\. It got the segfault signal after the 58th test case\. The module can be downloaded from http&#8203;://dlux\.sch\.bme\.hu/Class\-Date/trace/ directory\.

I am not 100% sure\, that it is a perl bug\, but I think it is\. I use operator overloading and autoloading in this package\.

The problem is disappeared when I run the test case \(30\_localtime\.t\) in perl debugger\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.6.1:

Configured by bod at Wed Jun 13 06:18:02 EST 2001.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=linux, osvers=2.4.5-ac9, archname=i386-linux
    uname='linux duende 2.4.5-ac9 #1 thu jun 7 13:40:15 est 2001 i686 unknown '
    config_args='-Dccflags=-DDEBIAN -Dcccdlflags=-fPIC -Darchname=i386-linux -Dprefix=/usr -Dprivlib=/usr/share/perl/5.6.1 -Darchlib=/usr/lib/perl/5.6.1 -Dvendorprefix=/usr -Dvendorlib=/usr/share/perl5 -Dvendorarch=/usr/lib/perl5 -Dsiteprefix=/usr/local -Dsitelib=/usr/local/share/perl/5.6.1 -Dsitearch=/usr/local/lib/perl/5.6.1 -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 -Dman1ext=1 -Dman3ext=3perl -Dpager=/usr/bin/sensible-pager -Uafs -Ud_csh -Uusesfio -Dotherlibdirs=/usr/lib/perl5/5.6:/usr/lib/perl5/5.005 -Duseshrplib -Dlibperl=libperl.so.5.6.1 -Dd_dosuid -des'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='cc', ccflags ='-DDEBIAN -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2',
    cppflags='-DDEBIAN -fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='2.95.4 20010604 (Debian prerelease)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lgdbm -ldbm -ldb -ldl -lm -lc -lcrypt
    perllibs=-ldl -lm -lc -lcrypt
    libc=/lib/libc-2.2.3.so, so=so, useshrplib=true, libperl=libperl.so.5.6.1
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.1:
    /usr/local/lib/perl/5.6.1
    /usr/local/share/perl/5.6.1
    /usr/lib/perl5
    /usr/share/perl5
    /usr/lib/perl/5.6.1
    /usr/share/perl/5.6.1
    /usr/local/lib/site_perl
    /usr/lib/perl5/5.6
    /usr/lib/perl5/5.005/i386-linux
    /usr/lib/perl5/5.005
    .


Environment for perl v5.6.1:
    HOME=/home/dlux
    LANG=C
    LANGUAGE (unset)
    LD_LIBRARY_PATH=~/lib
    LOGDIR (unset)
    PATH=/opt/bin:/usr/bin:/usr/local/bin:/home/dlux/bin:/home/dlux/projects/shell:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @smpeters

> \[dlux@&#8203;spam\.sch\.bme\.hu \- Sun Jun 17 17&#8203;:21&#8203;:28 2001\]&#8203;:
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> 
> I got a segfault\, here is the stack trace&#8203;:
> 
> \#0  0x80c772b in Perl\_sv\_2bool \(sv=0x81fb7b4\) at sv\.c&#8203;:2353
> \#1  0x80b8fac in Perl\_pp\_cond\_expr \(\) at pp\_hot\.c&#8203;:123
> \#2  0x80b863d in Perl\_runops\_debug \(\) at run\.c&#8203;:53
> \#3  0x8066ba3 in Perl\_amagic\_call \(left=0x82fea14\, right=0x813f958\,
>    method=30\,
>     flags=0\) at gv\.c&#8203;:1588
> \#4  0x80d6341 in Perl\_pp\_gt \(\) at pp\.c&#8203;:1181
> \#5  0x80b863d in Perl\_runops\_debug \(\) at run\.c&#8203;:53
> \#6  0x805dd5f in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1471
> \#7  0x805d931 in perl\_run \(my\_perl=0x8140280\) at perl\.c&#8203;:1393
> \#8  0x805a205 in main \(argc=6\, argv=0xbffff944\, env=0xbffff960\) at
>    perlmain\.c&#8203;:52
> \#9  0x4006338b in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6
> 
> The segfault is caused by a "make test" in the upcoming release of
>    Class&#8203;::Date 1\.1\.0\. It got the segfault signal after the 58th test
>    case\. The module can be downloaded from
>    http&#8203;://dlux\.sch\.bme\.hu/Class\-Date/trace/ directory\.
> 
> I am not 100% sure\, that it is a perl bug\, but I think it is\. I use
>    operator overloading and autoloading in this package\.
> 
> The problem is disappeared when I run the test case \(30\_localtime\.t\)
>    in perl debugger\.
> 


I was able to install without problems\.  CPAN Testers also shows that
there have been no additional problems going back several years\.

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'resolved'
