### ISSUE TITLE
Segfault on gethostbyaddr call which returns multiple PTR records

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4158]
Migrated from [rt.perl.org#7211](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=7211) (status was 'resolved')

Searchable as RT7211$

**Comment by p5pRT** [comment]
### From fillmore@nrn1.NRCan.gc.ca



The following code generates a segfault on Solaris 2\.6 and Solaris 8&#8203;:

&nbsp;   $addr = pack\('C4'\, split\(/\\\./\,'195\.226\.128\.9'\)\);
&nbsp;   $addrtype = 2;
&nbsp;   \($name\, $rest\) = gethostbyaddr\($addr\, $addrtype\);

The same lookup using nslookup on Solaris 8 does not segfault&#8203;:
&nbsp;   nslookup \-q=ptr 9\.128\.226\.195\.in\-addr\.arpa

Note that the segfault may be due to bad data returned from a corrupt
cache in the remote DNS\,
so this should be tested ASAP before that DNS is restarted\.

Thanks\,

&nbsp;    Bob Fillmore

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.6.0:

Configured by fillmore at Sun Sep  3 20:24:41 EDT 2000.

Summary of my perl5 (revision 5.0 version 6 subversion 0) configuration:
  Platform:
    osname=solaris, osvers=2.8, archname=sun4-solaris
    uname='sunos nrn1 5.8 generic_108528-02 sun4u sparc sunw,ultra-4 '
    config_args=''
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define 
    use64bitint=undef use64bitall=undef uselongdouble=undef usesocks=undef
  Compiler:
    cc='gcc', optimize='-O', gccversion=2.95.2 19991024 (release)
    cppflags='-fno-strict-aliasing -I/usr/local/include'
    ccflags ='-fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    stdchar='char', d_stdstdio=define, usevfork=false
    intsize=4, longsize=4, ptrsize=4, doublesize=8
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, usemymalloc=y, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib '
    libpth=/usr/local/lib /lib /usr/lib /usr/ccs/lib
    libs=-lsocket -lnsl -ldl -lm -lc -lcrypt -lsec
    libc=/lib/libc.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags=' '
    cccdlflags='-fPIC', lddlflags='-G -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.0:
    /usr/local/lib/perl5/5.6.0/sun4-solaris
    /usr/local/lib/perl5/5.6.0
    /usr/local/lib/perl5/site_perl/5.6.0/sun4-solaris
    /usr/local/lib/perl5/site_perl/5.6.0
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.6.0:
    HOME=/home/emr1/fillmore
    LANG (unset)
    LANGUAGE (unset)
    LC_CTYPE=iso_8859_1
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/bin:/usr/sbin:/usr/bin:/usr/ucb:/etc:/usr/etc:/usr/local:/usr/local/bin:/usr/local/etc:/operator:/home/etherdata:/home/emr1/fillmore/bin
    PERL_BADLANG (unset)
    SHELL=/bin/csh

```
</details>

**Comment by p5pRT** [comment]
### From @nwc10

FreeBSD on bleadperl goes Bus error \(core dumped\)
nd in gdb I get

\(gdb\) where
\#0  0x8100e1c in \_\_ns\_name\_unpack \(\)
\#1  0x8101081 in \_\_ns\_name\_uncompress \(\)
\#2  0x80fb9b1 in \_\_dn\_expand \(\)
\#3  0x80fc7db in irs\_dns\_ho \(\)
\#4  0x80fc52b in irs\_dns\_ho \(\)
\#5  0x80f4b60 in irs\_gen\_ho \(\)
\#6  0x80f0ea7 in gethostbyaddr \(\)
\#7  0x80ce095 in Perl\_pp\_ghostent \(\)
\#8  0x80cdf9f in Perl\_pp\_ghbyaddr \(\)
\#9  0x809c3f4 in Perl\_runops\_standard \(\)
\#10 0x805fb58 in S\_run\_body \(\)
\#11 0x805f898 in perl\_run \(\)
\#12 0x805d3fd in main \(\)
\#13 0x805d2ed in \_start \(\)


5\.00502 and 5\.6\.0 pass\, 5\.6\.1 also goes bus error on bleadperl as far back as
8102 \(which is the earliest I can find\.

Nicholas Clark

**Comment by p5pRT** [comment]
### From @nwc10

but on FreeBSD&#8203;:

nslookup \-q=ptr 9\.128\.226\.195\.in\-addr\.arpa
Server&#8203;:  roast\.cow\.org\.uk
Address&#8203;:  212\.240\.134\.132
Aliases&#8203;:  132\.134\.240\.212\.in\-addr\.arpa

Non\-authoritative answer&#8203;:
9\.128\.226\.195\.in\-addr\.arpa      name = www\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = cccars\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = advantage\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = bsi\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = sarkcomputers\.sark\.net
9\.128\.226\.195\.in\-addr\.arpa      name = chamberpo\.com
9\.128\.226\.195\.in\-addr\.arpa      name = scatreasury\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = c\-photo\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = evans\-co\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = swimarathon\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = herring\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = antiquefind\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = gyc\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = ms\-consulting\.com
9\.128\.226\.195\.in\-addr\.arpa      name = trainingplus\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = harlequin\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = gybobb\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = gdi\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = osa\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = southshow\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = ieg\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = etn\.org
9\.128\.226\.195\.in\-addr\.arpa      name = hawkins\.co\.gg
9\.128\.226\.195\.in\-addr\.arpa      name = capital\.co\.gg
9\.128\.226\.195\.in\-addr\.arpa      name = falla\.com
9\.128\.226\.195\.in\-addr\.arpa      name = ambassador\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = evolution\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = generali\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = paragon\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = latrelade\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = collinette\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = sedgwick\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = revolveco\.com
9\.128\.226\.195\.in\-addr\.arpa      name = revolvemm\.com
9\.128\.226\.195\.in\-addr\.arpa      name = easy\-it\.com
9\.128\.226\.195\.in\-addr\.arpa      name = momentum\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = sovereign\.guernsey\.net
9\.128\.226\.195\.in\-addr\.arpa      name = tiredeflator\.com
9\.128\.226\.195\.in\-addr\.arpa      name = jersey\.net\.je
9\.128\.226\.195\.in\-addr\.arpa      name = generali\-guernsey\.com
9\.128\.226\.195\.in\-addr\.arpa      name = laretraite\.guernsey\.net
ns\_sprintrrf&#8203;: No space left on device
Bus error \(core dumped\)

Linux isn't coredumping&#8203;:
nslookup \-q=ptr 9\.128\.226\.195\.in\-addr\.arpa | wc
&nbsp;    805    3210   42598

and I can't get any perl to coredump there\.

Nicholas Clark

**Comment by p5pRT** [comment]
### From @nwc10

Forgot to ask \- are you able to run a debugger and get a stack backtrace on
Solaris? It's quite possible that nslookup on Solaris links against different
libraries or is using different code\.

I think I know why 5\.6\.1 on this machine SIGBUSes\, 5\.6\.0 doesn't&#8203;:

$ ldd /usr/local/bin/perl5\.6\.0
/usr/local/bin/perl5\.6\.0&#8203;:
&nbsp;        libm\.so\.2 => /usr/lib/libm\.so\.2 \(0x280f8000\)
&nbsp;        libc\.so\.3 => /usr/lib/libc\.so\.3 \(0x28113000\)
&nbsp;        libcrypt\.so\.2 => /usr/lib/libcrypt\.so\.2 \(0x28195000\)
$ ldd /usr/local/bin/perl5\.6\.1
/usr/local/bin/perl5\.6\.1&#8203;:
&nbsp;        libm\.so\.2 => /usr/lib/libm\.so\.2 \(0x28146000\)
&nbsp;        libc\.so\.4 => /usr/lib/libc\.so\.4 \(0x28161000\)
&nbsp;        libcrypt\.so\.2 => /usr/lib/libcrypt\.so\.2 \(0x281f6000\)
&nbsp;        libutil\.so\.3 => /usr/lib/libutil\.so\.3 \(0x2820b000\)

Different libc\, plus libutil\.so\, although I don't know what that is\.

I suspect that your SEGV on Solaris is actually an OS bug but can't really
prove/disprove this without a backtrace on Solaris\.

Something certainly \*is\* broken with the DNS at the far end\, as host here
gives&#8203;:

host 195\.226\.128\.9
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer www\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer cccars\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer advantage\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer bsi\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer sarkcomputers\.sark\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer chamberpo\.com
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer scatreasury\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer c\-photo\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer evans\-co\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer swimarathon\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer herring\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer antiquefind\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer gyc\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer ms\-consulting\.com
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer trainingplus\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer harlequin\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer gybobb\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer gdi\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer osa\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer 9\.128\.226\.195\.IN\-ADDR\.ARPApacket size error \(0x0 \!= 0xbfbff054\)


but it seems that the bug is in the system libraries\, not perl\, which is
unfortunate\, as we can't fix those sort of bugs\.
\[And worse\, I can't see how perl can work round this bug\, if it is OS\]

Nicholas Clark

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

It looks like it's definitely the resolver library that's crashing\-
the "ns\_name\_unpack" code should protect itself against garbage\.

Here's an mdb stack trace on Solaris 8 / Perl 5\.6\.0&#8203;:

mdb /usr/local/bin/perl5\.6\.0 core
Loading modules&#8203;: \[ \]
> $c
libresolv\.so\.2\`\_\_ns\_name\_unpack\+0x28\(ffbecb84\, 560e\, ffbf05bc\, ffbec528\, ff\,
0\)
libresolv\.so\.2\`\_\_ns\_name\_uncompress\+0x14\(ffbecb84\, ffbf2192\, ffbf05bc\,
101bdc\,
1d5c\, e\)
libresolv\.so\.2\`dn\_expand\+0x14\(ffbecb84\, ffbf2192\, ffbf05bc\, 101bdc\, 1d5c\,
2e\)
libresolv\.so\.2\`gethostans\+0x218\(ffbecf84\, 2f0\, 10181c\, 29\, 101808\, ffbf2192\)
libresolv\.so\.2\`ho\_byaddr\+0x1dc\(ebca0\, 4\, 0\, 2\, ff0b2000\, f21d8\)
libresolv\.so\.2\`ho\_byaddr\+0x48\(ebce0\, ffffffff\, 4\, 2\, f0374\, 4\)
libresolv\.so\.2\`res\_gethostbyaddr\+0xf8\(ebce0\, 4\, 2\, 2\, 4\, f21d8\)
nss\_dns\.so\.1\`\_gethostbyaddr\+0x20\(ffbed760\, f21d8\, 4\, 2\, ffbed760\, ff0d4000\)
nss\_dns\.so\.1\`\_\_nss\_dns\_getbyaddr\+0x118\(f23b8\, ffbed760\, ff0d4000\, f5334\,
ffbed738\, 0\)
libc\.so\.1\`nss\_search\+0x1cc\(1\, ff23af4c\, ff23f54c\, ff0c10a4\, f5268\, f23b8\)
libnsl\.so\.1\`\_switch\_gethostbyaddr\_r\+0x4c\(f21d8\, 4\, 2\, fc814\, fc828\, 920\)
libnsl\.so\.1\`\_door\_gethostbyaddr\_r\+0xec\(e81d8\, ffbed7cc\, 2\, fc814\, fc828\,
920\)
libnsl\.so\.1\`\_get\_hostserv\_inetnetdir\_byaddr\+0x1e8\(7f000001\, ffbef8c0\, 0\,
ff31ae30\, ffbef8c8\, ff320b8c\)
libnsl\.so\.1\`gethostbyaddr\_r\+0x9c\(e81d8\, f5e00\, 2\, fc814\, fc828\, 920\)
libnsl\.so\.1\`gethostbyaddr\+0x8c\(ff322f34\, e81d8\, 0\, 0\, 4\, f21d8\)
Perl\_pp\_ghostent\+0x114\(0\, 0\, 0\, 0\, 0\, 0\)
Perl\_pp\_ghbyaddr\+4\(aa2e8\, e8800\, e90d6\, 0\, 0\, 1\)
Perl\_runops\_standard\+0x10\(e8400\, f4408\, fb0f8\, ffbefd10\, c3698\, 0\)
S\_run\_body\+0x130\(1\, e7c00\, e7c00\, e984c\, 0\, e828d\)
perl\_run\+0x8c\(0\, 212b4\, 2\, ffbefcac\, 0\, 0\)
main\+0x78\(0\, ffbefcac\, ffbefcb8\, e7cfc\, 0\, 0\)
\_start\+0x5c\(0\, 0\, 0\, 0\, 0\, 0\)
>

I guess I will pursue this with Sun\.\.\.\. you can close this bug\.

Thanks\!

&nbsp;   \- Bob


\-\-\-\-\-Original Message\-\-\-\-\-
From&#8203;: Nicholas Clark \[mailto&#8203;:nick@&#8203;ccl4\.org\]
Sent&#8203;: Saturday\, June 30\, 2001 6&#8203;:24 PM
To&#8203;: Nicholas Clark
Cc&#8203;: Bob Fillmore; perl5\-porters@&#8203;perl\.org; perlbug@&#8203;rfi\.net
Subject&#8203;: Re&#8203;: \[ID 20010630\.004\] Segfault on gethostbyaddr call which
returns multiple PTR records


On Sat\, Jun 30\, 2001 at 06&#8203;:12&#8203;:26PM \+0100\, Nicholas Clark wrote&#8203;:
> On Sat\, Jun 30\, 2001 at 11&#8203;:14&#8203;:06AM \-0400\, Bob Fillmore wrote&#8203;:
> > 
> > This is a bug report for perl from fillmore@&#8203;nrn1\.nrcan\.gc\.ca\,
> > generated with the help of perlbug 1\.28 running under perl v5\.6\.0\.
> > 
> > 
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > \[Please enter your report here\]
> > 
> > The following code generates a segfault on Solaris 2\.6 and Solaris 8&#8203;:
> > 
> >    $addr = pack\('C4'\, split\(/\\\./\,'195\.226\.128\.9'\)\);
> >    $addrtype = 2;
> >    \($name\, $rest\) = gethostbyaddr\($addr\, $addrtype\);
> 
> FreeBSD on bleadperl goes Bus error \(core dumped\)
> nd in gdb I get
> 
> \(gdb\) where
> \#0  0x8100e1c in \_\_ns\_name\_unpack \(\)
> \#1  0x8101081 in \_\_ns\_name\_uncompress \(\)
> \#2  0x80fb9b1 in \_\_dn\_expand \(\)
> \#3  0x80fc7db in irs\_dns\_ho \(\)
> \#4  0x80fc52b in irs\_dns\_ho \(\)
> \#5  0x80f4b60 in irs\_gen\_ho \(\)
> \#6  0x80f0ea7 in gethostbyaddr \(\)
> \#7  0x80ce095 in Perl\_pp\_ghostent \(\)
> \#8  0x80cdf9f in Perl\_pp\_ghbyaddr \(\)
> \#9  0x809c3f4 in Perl\_runops\_standard \(\)
> \#10 0x805fb58 in S\_run\_body \(\)
> \#11 0x805f898 in perl\_run \(\)
> \#12 0x805d3fd in main \(\)
> \#13 0x805d2ed in \_start \(\)
> 
> 
> 5\.00502 and 5\.6\.0 pass\, 5\.6\.1 also goes bus error on bleadperl as far back
as
> 8102 \(which is the earliest I can find\.

Forgot to ask \- are you able to run a debugger and get a stack backtrace on
Solaris? It's quite possible that nslookup on Solaris links against
different
libraries or is using different code\.

I think I know why 5\.6\.1 on this machine SIGBUSes\, 5\.6\.0 doesn't&#8203;:

$ ldd /usr/local/bin/perl5\.6\.0
/usr/local/bin/perl5\.6\.0&#8203;:
&nbsp;        libm\.so\.2 => /usr/lib/libm\.so\.2 \(0x280f8000\)
&nbsp;        libc\.so\.3 => /usr/lib/libc\.so\.3 \(0x28113000\)
&nbsp;        libcrypt\.so\.2 => /usr/lib/libcrypt\.so\.2 \(0x28195000\)
$ ldd /usr/local/bin/perl5\.6\.1
/usr/local/bin/perl5\.6\.1&#8203;:
&nbsp;        libm\.so\.2 => /usr/lib/libm\.so\.2 \(0x28146000\)
&nbsp;        libc\.so\.4 => /usr/lib/libc\.so\.4 \(0x28161000\)
&nbsp;        libcrypt\.so\.2 => /usr/lib/libcrypt\.so\.2 \(0x281f6000\)
&nbsp;        libutil\.so\.3 => /usr/lib/libutil\.so\.3 \(0x2820b000\)

Different libc\, plus libutil\.so\, although I don't know what that is\.

I suspect that your SEGV on Solaris is actually an OS bug but can't really
prove/disprove this without a backtrace on Solaris\.

Something certainly \*is\* broken with the DNS at the far end\, as host here
gives&#8203;:

host 195\.226\.128\.9
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer www\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer cccars\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer advantage\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer bsi\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer sarkcomputers\.sark\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer chamberpo\.com
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer scatreasury\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer c\-photo\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer evans\-co\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer swimarathon\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer herring\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer antiquefind\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer gyc\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer ms\-consulting\.com
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer trainingplus\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer harlequin\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer gybobb\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer gdi\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer osa\.guernsey\.net
9\.128\.226\.195\.IN\-ADDR\.ARPA domain name pointer
9\.128\.226\.195\.IN\-ADDR\.ARPApacket size error \(0x0 \!= 0xbfbff054\)


but it seems that the bug is in the system libraries\, not perl\, which is
unfortunate\, as we can't fix those sort of bugs\.
\[And worse\, I can't see how perl can work round this bug\, if it is OS\]

Nicholas Clark
