### ISSUE TITLE
map { while (1) } hangs perl during compilation

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#416]
Migrated from [rt.perl.org#1251](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=1251) (status was 'resolved')

Searchable as RT1251$

**Comment by p5pRT** [comment]
### From barries@slaysys.com



This&#8203;:

&nbsp;   sub foo \{
&nbsp;      map \{
&nbsp;     while \(1\) \{\} ;
&nbsp;      \} @&#8203;wits\_end ;
&nbsp;   \}

&nbsp;   BEGIN \{
&nbsp;      die ;
&nbsp;   \}

Never dies\.  It sucks up all CPU instead\.

This&#8203;:


&nbsp;   sub foo1 \{
&nbsp;      map \{
&nbsp;     ;
&nbsp;      \} @&#8203;wits\_end ;
&nbsp;   \}

&nbsp;   sub foo2 \{
&nbsp;      map \{
&nbsp;     while \($i\) \{\}
&nbsp;      \} @&#8203;wits\_end ;
&nbsp;   \}

&nbsp;   die ;

dies nicely\.  Haven't checked under \_60 \(let alone \_61\)\.

"Do not go gently into that dark night\.\.\.\."

<details><summary>Perl Info</summary>

```


Site configuration information for perl 5.00503:

Configured by root at Fri May 28 10:03:51 EDT 1999.

Summary of my perl5 (5.0 patchlevel 5 subversion 3) configuration:
  Platform:
    osname=linux, osvers=2.2.9, archname=i686-linux
    uname='linux jester.slaysys.com 2.2.9 #4 smp thu may 27 10:44:27 edt 1999 i686 unknown '
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef useperlio=undef d_sfio=undef
  Compiler:
    cc='cc', optimize='-O2', gccversion=egcs-2.91.66 19990314/Linux (egcs-1.1.2 release)
    cppflags='-Dbool=char -DHAS_BOOL'
    ccflags ='-Dbool=char -DHAS_BOOL'
    stdchar='char', d_stdstdio=undef, usevfork=false
    intsize=4, longsize=4, ptrsize=4, doublesize=8
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lndbm -lgdbm -ldb -ldl -lm -lc -lposix -lcrypt
    libc=, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl 5.00503:
    /home/barries/src/Safari/lib
    /usr/lib/perl5/5.00503/i686-linux
    /usr/lib/perl5/5.00503
    /usr/lib/perl5/site_perl/5.005/i686-linux
    /usr/lib/perl5/site_perl/5.005
    .


Environment for perl 5.00503:
    HOME=/home/barries
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:~/bin:~/bin
    PERL5LIB=/home/barries/src/Safari/lib
    PERLDB_OPTS=AutoTrace
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Sun\, 22 Aug 1999 at 23&#8203;:38&#8203;:17 \-0400\, Barrie Slaymaker wrote&#8203;:

>    sub foo \{
>       map \{
>      while \(1\) \{\} ;
>       \} @&#8203;wits\_end ;
>    \}
> 
>    BEGIN \{
>       die ;
>    \}
> 
> Never dies\.  It sucks up all CPU instead\.

A progress report&#8203;:

I took a peek with gdb\, and it's stuck in Perl\_ck\_grep running round a
small circular list of items
&nbsp;    pp\_nextstate\->pp\_stub\->pp\_unstack

We need to see where that came from\.\.\. fold\_constants getting confused?

Ian

**Comment by p5pRT** [comment]
### From The RT System itself

map \{ while \(1\) \{\} \} \(\);
BEGIN \{ die "ok 1" \}

**Comment by p5pRT** [comment]
### From @floatingatoll

\[RT\_System \- Tue Aug 24 07&#8203;:29&#8203;:00 1999\]&#8203;:

> On Sun\, 22 Aug 1999 at 23&#8203;:38&#8203;:17 \-0400\, Barrie Slaymaker wrote&#8203;:
> 
> >    sub foo \{
> >       map \{
> >      while \(1\) \{\} ;
> >       \} @&#8203;wits\_end ;
> >    \}
> >
> >    BEGIN \{
> >       die ;
> >    \}
> >
> > Never dies\.  It sucks up all CPU instead\.

This bug is still present\, as of the current development version of perl \(@&#8203;18374\)\.

\(gdb\) bt
\#0  0x00015c64 in Perl\_ck\_grep \(\)
\#1  0x0000d418 in Perl\_convert \(\)
\#2  0x000c79ac in Perl\_yyparse \(\)
\#3  0x0001b818 in S\_parse\_body \(\)
\#4  0x0001a77c in perl\_parse \(\)

**Comment by p5pRT** [comment]
### From @schwern

Bug still present in 5\.8\.1 RC 2

**Comment by p5pRT** [comment]
### From @rspier

not fixed in 5\.8\.4
will be fixed in 5\.9\.2 \(DEVEL22511\)

**Comment by p5pRT** [comment]
@rspier - Status changed from 'open' to 'resolved'
