### ISSUE TITLE
HP-UX core dump from op/pwent.t

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4285]
Migrated from [rt.perl.org#7460](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=7460) (status was 'stalled')

Searchable as RT7460$

**Comment by p5pRT** [comment]
### From @jhi



Core dump deep down in the bowels of libc when endpwent\(\) is called\.
I have little idea of how to even start fixing this\.  This used to
work as a few weeks ago\, the HP\-UX installation hasn't been patched\.

What little I do know is that the user database setup \(who can login\)
in the machine is a little bit wonky \(I won't go into details because
I don't know them :\)\, but that of course is no excuse for a coredump\.

elvis&#8203;:/tmp/jhi/perl ; gdb \./perl t/core
GNU gdb 4\.18
Copyright 1998 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and you are
welcome to change it and/or distribute copies of it under certain conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for details\.
This GDB was configured as "hppa1\.1\-hp\-hpux11\.00"\.\.\.
Core was generated by \`perl'\.
Program terminated with signal 10\, Bus error\.

warning&#8203;: The shared libraries were not privately mapped; setting a
breakpoint in a shared library will not work until you rerun the program\.

Reading symbols from \./perl\.\.\.done\.
Reading symbols from /usr/lib/libnsl\.1\.\.\.done\.
Reading symbols from /usr/lib/libxti\.2\.\.\.done\.
Reading symbols from /usr/lib/libnm\.sl\.\.\.done\.
Reading symbols from /usr/lib/libc\.2\.\.\.done\.
Reading symbols from /usr/lib/libdld\.2\.\.\.done\.
Reading symbols from /usr/lib/libsec\.2\.\.\.done\.
Reading symbols from /usr/lib/libm\.2\.\.\.done\.
Reading symbols from /usr/lib/nls/loc/locales\.2//fi\_FI\.iso88591\.\.\.done\.
Reading symbols from /usr/lib/libnss\_files\.1\.\.\.done\.
Reading symbols from /usr/lib/libnss\_nis\.1\.\.\.done\.
\#0  0xc004216c in  \(\) from /usr/lib/libc\.2
\(gdb\) where
\#0  0xc004216c in  \(\) from /usr/lib/libc\.2
\#1  0xc00d7550 in \_\_nss\_src\_state\_destr \(\) from /usr/lib/libc\.2
\#2  0xc00d7768 in \_\_nss\_src\_state\_destr \(\) from /usr/lib/libc\.2
\#3  0xc00d78a8 in nss\_delete \(\) from /usr/lib/libc\.2
\#4  0xc01126d8 in endpwent \(\) from /usr/lib/libc\.2
\#5  0x12b5f0 in Perl\_pp\_epwent \(\) at pp\_sys\.c&#8203;:5231
\#6  0xcf060 in Perl\_runops\_debug \(\) at run\.c&#8203;:51
\#7  0x25b68 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1572
\#8  0x25554 in perl\_run \(my\_perl=0x40026004\) at perl\.c&#8203;:1494
\#9  0x20544 in main \(argc=2\, argv=0x7f7e6870\, env=0x7f7e687c\) at perlmain\.c&#8203;:76
\(gdb\) up
\#1  0xc00d7550 in \_\_nss\_src\_state\_destr \(\) from /usr/lib/libc\.2
\(gdb\) up
\#2  0xc00d7768 in \_\_nss\_src\_state\_destr \(\) from /usr/lib/libc\.2
\(gdb\) up
\#3  0xc00d78a8 in nss\_delete \(\) from /usr/lib/libc\.2
\(gdb\) up
\#4  0xc01126d8 in endpwent \(\) from /usr/lib/libc\.2
\(gdb\) up
\#5  0x12b5f0 in Perl\_pp\_epwent \(\) at pp\_sys\.c&#8203;:5231
5231        endpwent\(\);
\(gdb\) 

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl v5.7.2:

Configured by jhi at Sat Aug  4 23:16:26 EET DST 2001.

Summary of my perl5 (revision 5.0 version 7 subversion 2 patch 11563) configuration:
  Platform:
    osname=hpux, osvers=11.00, archname=PA-RISC1.1
    uname='hp-ux elvis b.11.00 a 9000778 2000166257 two-user license '
    config_args='-des -Dusedevel -Dloclibpth=/p/shlib -Doptimize=-g'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=y, bincompat5005=define
  Compiler:
    cc='cc', ccflags =' -Ae -D_HPUX_SOURCE -Wl,+vnocompatwarnings -DDEBUGGING -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 ',
    optimize='-g',
    cppflags='-Aa -D__STDC_EXT__ -D_HPUX_SOURCE -Ae -D_HPUX_SOURCE -Wl,+vnocompatwarnings -DDEBUGGING'
    ccversion='A.11.00.14', gccversion='', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=4321
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='/usr/bin/ld', ldflags =' -L/p/shlib'
    libpth=/p/shlib /usr/shlib /lib /usr/lib /usr/ccs/lib /usr/local/lib
    libs=-lnsl -lnm -lndbm -lgdbm -ldb -ldld -lm -lc -lndir -lcrypt -lsec
    perllibs=-lnsl -lnm -ldld -lm -lc -lndir -lcrypt -lsec
    libc=/lib/libc.sl, so=sl, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_hpux.xs, dlext=sl, d_dlsymun=undef, ccdlflags='-Wl,-E -Wl,-B,deferred '
    cccdlflags='+Z', lddlflags='-b +vnocompatwarnings -L/p/shlib'

Locally applied patches:
    DEVEL11563


@INC for perl v5.7.2:
    lib
    /opt/perl5/lib/5.7.2/PA-RISC1.1
    /opt/perl5/lib/5.7.2
    /opt/perl5/lib/site_perl/5.7.2/PA-RISC1.1
    /opt/perl5/lib/site_perl/5.7.2
    /opt/perl5/lib/site_perl
    .


Environment for perl v5.7.2:
    HOME=/u/vieraat/vieraat/jhi
    LANG=C
    LANGUAGE (unset)
    LC_ALL=finnish.iso88591
    LC_CTYPE=finnish.iso88591
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/u/vieraat/vieraat/jhi/.s:/u/vieraat/vieraat/jhi/.b/HP-UX:/c/bin:/p/bin:/p/adm/bin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin:/usr/ccs/bin:/usr/etc:/usr/lib:/etc:/lib:/p/X6/bin:/p/X5/bin:/usr/bin/X11:/usr/lbin:/usr/sbin/acct:/u/vieraat/vieraat/jhi:/etc
    PERL_BADLANG (unset)
    SHELL=/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @smpeters

> \[jhi@&#8203;cc\.hut\.fi \- Sun Aug 05 01&#8203;:50&#8203;:04 2001\]&#8203;:
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> 
> Core dump deep down in the bowels of libc when endpwent\(\) is called\.
> I have little idea of how to even start fixing this\.  This used to
> work as a few weeks ago\, the HP\-UX installation hasn't been patched\.
> 
> What little I do know is that the user database setup \(who can login\)
> in the machine is a little bit wonky \(I won't go into details because
> I don't know them :\)\, but that of course is no excuse for a coredump\.
> 
> elvis&#8203;:/tmp/jhi/perl ; gdb \./perl t/core
> GNU gdb 4\.18
> Copyright 1998 Free Software Foundation\, Inc\.
> GDB is free software\, covered by the GNU General Public License\, and
>    you are
> welcome to change it and/or distribute copies of it under certain
>    conditions\.
> Type "show copying" to see the conditions\.
> There is absolutely no warranty for GDB\.  Type "show warranty" for
>    details\.
> This GDB was configured as "hppa1\.1\-hp\-hpux11\.00"\.\.\.
> Core was generated by \`perl'\.
> Program terminated with signal 10\, Bus error\.
> 
> warning&#8203;: The shared libraries were not privately mapped; setting a
> breakpoint in a shared library will not work until you rerun the
>    program\.
> 
> Reading symbols from \./perl\.\.\.done\.
> Reading symbols from /usr/lib/libnsl\.1\.\.\.done\.
> Reading symbols from /usr/lib/libxti\.2\.\.\.done\.
> Reading symbols from /usr/lib/libnm\.sl\.\.\.done\.
> Reading symbols from /usr/lib/libc\.2\.\.\.done\.
> Reading symbols from /usr/lib/libdld\.2\.\.\.done\.
> Reading symbols from /usr/lib/libsec\.2\.\.\.done\.
> Reading symbols from /usr/lib/libm\.2\.\.\.done\.
> Reading symbols from
>    /usr/lib/nls/loc/locales\.2//fi\_FI\.iso88591\.\.\.done\.
> Reading symbols from /usr/lib/libnss\_files\.1\.\.\.done\.
> Reading symbols from /usr/lib/libnss\_nis\.1\.\.\.done\.
> \#0  0xc004216c in  \(\) from /usr/lib/libc\.2
> \(gdb\) where
> \#0  0xc004216c in  \(\) from /usr/lib/libc\.2
> \#1  0xc00d7550 in \_\_nss\_src\_state\_destr \(\) from /usr/lib/libc\.2
> \#2  0xc00d7768 in \_\_nss\_src\_state\_destr \(\) from /usr/lib/libc\.2
> \#3  0xc00d78a8 in nss\_delete \(\) from /usr/lib/libc\.2
> \#4  0xc01126d8 in endpwent \(\) from /usr/lib/libc\.2
> \#5  0x12b5f0 in Perl\_pp\_epwent \(\) at pp\_sys\.c&#8203;:5231
> \#6  0xcf060 in Perl\_runops\_debug \(\) at run\.c&#8203;:51
> \#7  0x25b68 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1572
> \#8  0x25554 in perl\_run \(my\_perl=0x40026004\) at perl\.c&#8203;:1494
> \#9  0x20544 in main \(argc=2\, argv=0x7f7e6870\, env=0x7f7e687c\) at
>    perlmain\.c&#8203;:76
> \(gdb\) up
> \#1  0xc00d7550 in \_\_nss\_src\_state\_destr \(\) from /usr/lib/libc\.2
> \(gdb\) up
> \#2  0xc00d7768 in \_\_nss\_src\_state\_destr \(\) from /usr/lib/libc\.2
> \(gdb\) up
> \#3  0xc00d78a8 in nss\_delete \(\) from /usr/lib/libc\.2
> \(gdb\) up
> \#4  0xc01126d8 in endpwent \(\) from /usr/lib/libc\.2
> \(gdb\) up
> \#5  0x12b5f0 in Perl\_pp\_epwent \(\) at pp\_sys\.c&#8203;:5231
> 5231        endpwent\(\);
> \(gdb\)
> 

As in the following ticket\,
http&#8203;://rt\.perl\.org/rt3/Ticket/Display\.html?id=7460\, this core dump seems
to have been fixed prior to 5\.8\.0\.  I also built a 5\.8\.6\, and this test
passed without any failures\.

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @tux

On Wed 08 Dec 2004 01&#8203;:58\, "Steve Peters via RT" \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> > \[jhi@&#8203;cc\.hut\.fi \- Sun Aug 05 01&#8203;:50&#8203;:04 2001\]&#8203;:
> > 
> > 
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > \[Please enter your report here\]
> > 
> > Core dump deep down in the bowels of libc when endpwent\(\) is called\.
> > I have little idea of how to even start fixing this\.  This used to
> > work as a few weeks ago\, the HP\-UX installation hasn't been patched\.
> > 
> > What little I do know is that the user database setup \(who can login\)
> > in the machine is a little bit wonky \(I won't go into details because
> > I don't know them :\)\, but that of course is no excuse for a coredump\.
> > 
> > elvis&#8203;:/tmp/jhi/perl ; gdb \./perl t/core
> > GNU gdb 4\.18
> > Copyright 1998 Free Software Foundation\, Inc\.
> > GDB is free software\, covered by the GNU General Public License\, and
> >    you are
> > welcome to change it and/or distribute copies of it under certain
> >    conditions\.
> > Type "show copying" to see the conditions\.
> > There is absolutely no warranty for GDB\.  Type "show warranty" for
> >    details\.
> > This GDB was configured as "hppa1\.1\-hp\-hpux11\.00"\.\.\.
> > Core was generated by \`perl'\.
> > Program terminated with signal 10\, Bus error\.
> > 
> > warning&#8203;: The shared libraries were not privately mapped; setting a
> > breakpoint in a shared library will not work until you rerun the
> >    program\.
> > 
> > Reading symbols from \./perl\.\.\.done\.
> > Reading symbols from /usr/lib/libnsl\.1\.\.\.done\.
> > Reading symbols from /usr/lib/libxti\.2\.\.\.done\.
> > Reading symbols from /usr/lib/libnm\.sl\.\.\.done\.
> > Reading symbols from /usr/lib/libc\.2\.\.\.done\.
> > Reading symbols from /usr/lib/libdld\.2\.\.\.done\.
> > Reading symbols from /usr/lib/libsec\.2\.\.\.done\.
> > Reading symbols from /usr/lib/libm\.2\.\.\.done\.
> > Reading symbols from
> >    /usr/lib/nls/loc/locales\.2//fi\_FI\.iso88591\.\.\.done\.
> > Reading symbols from /usr/lib/libnss\_files\.1\.\.\.done\.
> > Reading symbols from /usr/lib/libnss\_nis\.1\.\.\.done\.
> > \#0  0xc004216c in  \(\) from /usr/lib/libc\.2
> > \(gdb\) where
> > \#0  0xc004216c in  \(\) from /usr/lib/libc\.2
> > \#1  0xc00d7550 in \_\_nss\_src\_state\_destr \(\) from /usr/lib/libc\.2
> > \#2  0xc00d7768 in \_\_nss\_src\_state\_destr \(\) from /usr/lib/libc\.2
> > \#3  0xc00d78a8 in nss\_delete \(\) from /usr/lib/libc\.2
> > \#4  0xc01126d8 in endpwent \(\) from /usr/lib/libc\.2
> > \#5  0x12b5f0 in Perl\_pp\_epwent \(\) at pp\_sys\.c&#8203;:5231
> > \#6  0xcf060 in Perl\_runops\_debug \(\) at run\.c&#8203;:51
> > \#7  0x25b68 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1572
> > \#8  0x25554 in perl\_run \(my\_perl=0x40026004\) at perl\.c&#8203;:1494
> > \#9  0x20544 in main \(argc=2\, argv=0x7f7e6870\, env=0x7f7e687c\) at
> >    perlmain\.c&#8203;:76
> > \(gdb\) up
> > \#1  0xc00d7550 in \_\_nss\_src\_state\_destr \(\) from /usr/lib/libc\.2
> > \(gdb\) up
> > \#2  0xc00d7768 in \_\_nss\_src\_state\_destr \(\) from /usr/lib/libc\.2
> > \(gdb\) up
> > \#3  0xc00d78a8 in nss\_delete \(\) from /usr/lib/libc\.2
> > \(gdb\) up
> > \#4  0xc01126d8 in endpwent \(\) from /usr/lib/libc\.2
> > \(gdb\) up
> > \#5  0x12b5f0 in Perl\_pp\_epwent \(\) at pp\_sys\.c&#8203;:5231
> > 5231        endpwent\(\);
> > \(gdb\)
> > 
> 
> As in the following ticket\,
> http&#8203;://rt\.perl\.org/rt3/Ticket/Display\.html?id=7460\, this core dump seems
> to have been fixed prior to 5\.8\.0\.  I also built a 5\.8\.6\, and this test
> passed without any failures\.

Did you also try that with a \*HUGE\* number of entries in /etc/group?
With HUGE I mean a lot\, like over 4k entries

And try that in threaded and non\-threaded

\-\- 
H\.Merijn Brand        Amsterdam Perl Mongers \(http&#8203;://amsterdam\.pm\.org/\)
using perl\-5\.6\.1\, 5\.8\.5\, & 5\.9\.x\, and 809 on  HP\-UX 10\.20 & 11\.00\, 11i\,
&nbsp;   AIX 4\.3\, AIX 5\.2\, SuSE 9\.1\, and Win2k\.  http&#8203;://www\.cmve\.net/~merijn/
http&#8203;://archives\.develooper\.com/daily\-build@&#8203;perl\.org/   perl\-qa@&#8203;perl\.org
send smoke reports to&#8203;: smokers\-reports@&#8203;perl\.org\, QA&#8203;: http&#8203;://qa\.perl\.org

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'resolved' to 'open'

**Comment by p5pRT** [comment]
### From steve@mccoy.peters.homeunix.org

On Wed\, Dec 08\, 2004 at 09&#8203;:12&#8203;:26AM \+0100\, H\.Merijn Brand wrote&#8203;:
> On Wed 08 Dec 2004 01&#8203;:58\, "Steve Peters via RT" \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> > > \[jhi@&#8203;cc\.hut\.fi \- Sun Aug 05 01&#8203;:50&#8203;:04 2001\]&#8203;:
> > > 
> > > 
> > > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > > \[Please enter your report here\]
> > > 
> > > Core dump deep down in the bowels of libc when endpwent\(\) is called\.
> > > I have little idea of how to even start fixing this\.  This used to
> > > work as a few weeks ago\, the HP\-UX installation hasn't been patched\.
> > > 
> > > What little I do know is that the user database setup \(who can login\)
> > > in the machine is a little bit wonky \(I won't go into details because
> > > I don't know them :\)\, but that of course is no excuse for a coredump\.
> > > 
> > > elvis&#8203;:/tmp/jhi/perl ; gdb \./perl t/core
> > > GNU gdb 4\.18
> > > Copyright 1998 Free Software Foundation\, Inc\.
> > > GDB is free software\, covered by the GNU General Public License\, and
> > >    you are
> > > welcome to change it and/or distribute copies of it under certain
> > >    conditions\.
> > > Type "show copying" to see the conditions\.
> > > There is absolutely no warranty for GDB\.  Type "show warranty" for
> > >    details\.
> > > This GDB was configured as "hppa1\.1\-hp\-hpux11\.00"\.\.\.
> > > Core was generated by \`perl'\.
> > > Program terminated with signal 10\, Bus error\.
> > > 
> > > warning&#8203;: The shared libraries were not privately mapped; setting a
> > > breakpoint in a shared library will not work until you rerun the
> > >    program\.
> > > 
> > > Reading symbols from \./perl\.\.\.done\.
> > > Reading symbols from /usr/lib/libnsl\.1\.\.\.done\.
> > > Reading symbols from /usr/lib/libxti\.2\.\.\.done\.
> > > Reading symbols from /usr/lib/libnm\.sl\.\.\.done\.
> > > Reading symbols from /usr/lib/libc\.2\.\.\.done\.
> > > Reading symbols from /usr/lib/libdld\.2\.\.\.done\.
> > > Reading symbols from /usr/lib/libsec\.2\.\.\.done\.
> > > Reading symbols from /usr/lib/libm\.2\.\.\.done\.
> > > Reading symbols from
> > >    /usr/lib/nls/loc/locales\.2//fi\_FI\.iso88591\.\.\.done\.
> > > Reading symbols from /usr/lib/libnss\_files\.1\.\.\.done\.
> > > Reading symbols from /usr/lib/libnss\_nis\.1\.\.\.done\.
> > > \#0  0xc004216c in  \(\) from /usr/lib/libc\.2
> > > \(gdb\) where
> > > \#0  0xc004216c in  \(\) from /usr/lib/libc\.2
> > > \#1  0xc00d7550 in \_\_nss\_src\_state\_destr \(\) from /usr/lib/libc\.2
> > > \#2  0xc00d7768 in \_\_nss\_src\_state\_destr \(\) from /usr/lib/libc\.2
> > > \#3  0xc00d78a8 in nss\_delete \(\) from /usr/lib/libc\.2
> > > \#4  0xc01126d8 in endpwent \(\) from /usr/lib/libc\.2
> > > \#5  0x12b5f0 in Perl\_pp\_epwent \(\) at pp\_sys\.c&#8203;:5231
> > > \#6  0xcf060 in Perl\_runops\_debug \(\) at run\.c&#8203;:51
> > > \#7  0x25b68 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1572
> > > \#8  0x25554 in perl\_run \(my\_perl=0x40026004\) at perl\.c&#8203;:1494
> > > \#9  0x20544 in main \(argc=2\, argv=0x7f7e6870\, env=0x7f7e687c\) at
> > >    perlmain\.c&#8203;:76
> > > \(gdb\) up
> > > \#1  0xc00d7550 in \_\_nss\_src\_state\_destr \(\) from /usr/lib/libc\.2
> > > \(gdb\) up
> > > \#2  0xc00d7768 in \_\_nss\_src\_state\_destr \(\) from /usr/lib/libc\.2
> > > \(gdb\) up
> > > \#3  0xc00d78a8 in nss\_delete \(\) from /usr/lib/libc\.2
> > > \(gdb\) up
> > > \#4  0xc01126d8 in endpwent \(\) from /usr/lib/libc\.2
> > > \(gdb\) up
> > > \#5  0x12b5f0 in Perl\_pp\_epwent \(\) at pp\_sys\.c&#8203;:5231
> > > 5231        endpwent\(\);
> > > \(gdb\)
> > > 
> > 
> > As in the following ticket\,
> > http&#8203;://rt\.perl\.org/rt3/Ticket/Display\.html?id=7460\, this core dump seems
> > to have been fixed prior to 5\.8\.0\.  I also built a 5\.8\.6\, and this test
> > passed without any failures\.
> 
> Did you also try that with a \*HUGE\* number of entries in /etc/group?
> With HUGE I mean a lot\, like over 4k entries
> 
> And try that in threaded and non\-threaded
> 

No\, actually\, I don't have access to an HP\-UX system with a large number of
entries in /etc/group\.  Reopened :\)

**Comment by p5pRT** [comment]
### From @jhi

>>
>>As in the following ticket\,
>>http&#8203;://rt\.perl\.org/rt3/Ticket/Display\.html?id=7460\, this core dump seems
>>to have been fixed prior to 5\.8\.0\.  I also built a 5\.8\.6\, and this test
>>passed without any failures\.
> 
> 
> Did you also try that with a \*HUGE\* number of entries in /etc/group?
> With HUGE I mean a lot\, like over 4k entries
> 
> And try that in threaded and non\-threaded

I agree\.  I do not think this ticket can be yet closed\.


\-\- 
Jarkko Hietaniemi \<jhi@&#8203;iki\.fi> http&#8203;://www\.iki\.fi/jhi/ "There is this special
biologist word we use for 'stable'\.  It is 'dead'\." \-\- Jack Cohen

**Comment by p5pRT** [comment]
### From @smpeters

> \[jhi \- Wed Dec 08 09&#8203;:02&#8203;:56 2004\]&#8203;:
> 
> >>
> >>As in the following ticket\,
> >>http&#8203;://rt\.perl\.org/rt3/Ticket/Display\.html?id=7460\, this core dump seems
> >>to have been fixed prior to 5\.8\.0\.  I also built a 5\.8\.6\, and this test
> >>passed without any failures\.
> > 
> > 
> > Did you also try that with a \*HUGE\* number of entries in /etc/group?
> > With HUGE I mean a lot\, like over 4k entries
> > 
> > And try that in threaded and non\-threaded
> 
> I agree\.  I do not think this ticket can be yet closed\.
> 
> 
> 

Change \#25084 may have implemented a possible fix to this problem\.  Are
you still able to replicate this with a current bleadperl?

**Comment by p5pRT** [comment]
@chorny - Status changed from 'open' to 'stalled'
