### ISSUE TITLE
Freeing pads after parse error

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4339]
Migrated from [rt.perl.org#7568](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=7568) (status was 'resolved')

Searchable as RT7568$

**Comment by p5pRT** [comment]
### From @simoncozens



This was reported to me by Ganesh Sittampalam\. Here's "bug"&#8203;:

sub blat \{
&nbsp;    sub \{
&nbsp;      &foo;
&nbsp;         or 1;
&nbsp;      &foo\(""\.""\)
&nbsp;         or &baz;
&nbsp;    \}
\}

This segfaults\, without an error message\. I think it is something
to do with the save stack and PL\_comppad\. If I disable leave\_scope
in the case of SAVEt\_COMPPAD when PL\_error\_count > 0\, I get an error
message as expected\, but I also get a pad\_free panic\.

This may be related to the comment in pp\_ctl\.c&#8203;:
&nbsp;    /\* I was having segfault trouble under Linux 2\.2\.5 after a
&nbsp;       parse error occured\.  \(Had to hack around it with a test
&nbsp;       for PL\_error\_count == 0\.\)  Solaris doesn't segfault \-\-
&nbsp;       not sure where the trouble is yet\.  XXX \*/

Here's the debugging&#8203;:

simon@&#8203;riot\-act ~/perl % \./perl \-DX bug
Pad 0x815b998 alloc 1 for entersub
Pad 0x815b998 alloc 2 for concat
Pad 0x815b998 alloc 3 for entersub
Pad 0x8164908 alloc 4 for entersub
Pad 0x815b958 free 2
Pad 0x815b958 free 3
Pad 0x815b958 free 4
zsh&#8203;: 8817 segmentation fault  \./perl \-DX bug
simon@&#8203;riot\-act ~/perl % gdb \./perl
GNU gdb 5\.0\.90\-cvs \(MI\_OUT\)
Copyright 2001 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and you are
welcome to change it and/or distribute copies of it under certain conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for details\.
This GDB was configured as "i686\-pc\-linux\-gnu"\.\.\.
\(gdb\) run bug
Starting program&#8203;: /home/simon/perl/\./perl bug

Program received signal SIGSEGV\, Segmentation fault\.
0x08087bfc in Perl\_pad\_free \(po=4\) at op\.c&#8203;:559
559             SvPADTMP\_off\(PL\_curpad\[po\]\);
\(gdb\) bt
\#0  0x08087bfc in Perl\_pad\_free \(po=4\) at op\.c&#8203;:559
\#1  0x080880d8 in Perl\_op\_clear \(o=0x81648f8\) at op\.c&#8203;:867
\#2  0x08087e42 in Perl\_op\_free \(o=0x81648f8\) at op\.c&#8203;:736
\#3  0x08087de5 in Perl\_op\_free \(o=0x8164950\) at op\.c&#8203;:724
\#4  0x08087de5 in Perl\_op\_free \(o=0x8164978\) at op\.c&#8203;:724
\#5  0x08087de5 in Perl\_op\_free \(o=0x81649d8\) at op\.c&#8203;:724
\#6  0x08092394 in Perl\_newATTRSUB \(floor=109\, o=0x81640c0\, proto=0x0\, attrs=0x0\, block=0x81649d8\) at op\.c&#8203;:4809
\#7  0x08084683 in Perl\_yyparse \(\) at perly\.y&#8203;:355
\#8  0x0805f672 in S\_parse\_body \(env=0x0\, xsinit=0x805c4a4 \<xs\_init>\) at perl\.c&#8203;:1434
\#9  0x0805ea63 in perl\_parse \(my\_perl=0x8157c50\, xsinit=0x805c4a4 \<xs\_init>\, argc=2\, argv=0xbffff95c\, env=0x0\) at perl\.c&#8203;:995
\#10 0x0805c42f in main \(argc=2\, argv=0xbffff95c\, env=0xbffff968\) at perlmain\.c&#8203;:74
\#11 0x4007746b in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6
\(gdb\)

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.6.1:

Configured by bod at Fri Jun 22 18:58:01 EST 2001.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=linux, osvers=2.4.5-ac9, archname=i386-linux
    uname='linux duende 2.4.5-ac9 #1 thu jun 21 00:52:39 est 2001 i686 unknown '
    config_args='-Dccflags=-DDEBIAN -Dcccdlflags=-fPIC -Darchname=i386-linux -Dprefix=/usr -Dprivlib=/usr/share/perl/5.6.1 -Darchlib=/usr/lib/perl/5.6.1 -Dvendorprefix=/usr -Dvendorlib=/usr/share/perl5 -Dvendorarch=/usr/lib/perl5 -Dsiteprefix=/usr/local -Dsitelib=/usr/local/share/perl/5.6.1 -Dsitearch=/usr/local/lib/perl/5.6.1 -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 -Dman1ext=1 -Dman3ext=3perl -Dpager=/usr/bin/sensible-pager -Uafs -Ud_csh -Uusesfio -Dotherlibdirs=/usr/lib/perl5/5.6:/usr/lib/perl5/5.005 -Duseshrplib -Dlibperl=libperl.so.5.6.1 -Dd_dosuid -des'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='cc', ccflags ='-DDEBIAN -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2',
    cppflags='-DDEBIAN -fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='2.95.4 20010604 (Debian prerelease)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lgdbm -ldbm -ldb -ldl -lm -lc -lcrypt
    perllibs=-ldl -lm -lc -lcrypt
    libc=/lib/libc-2.2.3.so, so=so, useshrplib=true, libperl=libperl.so.5.6.1
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.1:
    /usr/local/lib/perl/5.6.1
    /usr/local/share/perl/5.6.1
    /usr/lib/perl5
    /usr/share/perl5
    /usr/lib/perl/5.6.1
    /usr/share/perl/5.6.1
    /usr/local/lib/site_perl
    /usr/lib/perl5/5.6
    /usr/lib/perl5/5.005
    .


Environment for perl v5.6.1:
    HOME=/home/simon
    LANG=C
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/simon/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/local/sbin:/usr/sbin:/sbin
    PERL_BADLANG (unset)
    SHELL=/usr/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @simoncozens

Yes\. On error\, Perl is unwinding the save stack too many times\,
meaning that PL\_comppad is at the wrong level\. This causes Perl
to try to free an op from an element of PL\_comppad that isn't
there any more\. Here's a patch\.

<details><summary>Inline Patch</summary>

```diff
--- op.c~~	Mon Aug 13 01:30:59 2001
+++ op.c	Thu Aug 23 12:04:03 2001
@@ -2147,7 +2147,8 @@
 {
     int needblockscope = PL_hints & HINT_BLOCK_SCOPE;
     OP* retval = scalarseq(seq);
-    LEAVE_SCOPE(floor);
+    if (!PL_error_count)
+        LEAVE_SCOPE(floor);
     PL_pad_reset_pending = FALSE;
     PL_compiling.op_private = PL_hints;
     if (needblockscope)

Simon
```
</details>

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

> Yes\. On error\, Perl is unwinding the save stack too many times\,
> meaning that PL\_comppad is at the wrong level\. This causes Perl
> to try to free an op from an element of PL\_comppad that isn't
> there any more\. Here's a patch\.

Applied\, thanks\.

Possibly to be picked up for 5\.6\.2?

\-\- 
Arthur

**Comment by p5pRT** [comment]
### From @gsar

FWIW\, I'm not convinced the patch will do the right thing yet\, because
I think there might be cases where the scope stack may be pointing to
things that are expected to have gone out of scope in the outer scopes\.
\(Can't say much more than that without looking into it deeply\, and if
I do that I might even send in a patch\.  But don't hold your breath\-\-I'm
as old as a senile dog in this business\, and age teaches sloth\. :\)

I hope you do know that I don't currently plan to put out a 5\.6\.2
until after 5\.8\.0 is out?  I'm not positive it won't happen\, but
chances are that it won't\.


Sarathy
gsar@&#8203;ActiveState\.com

**Comment by p5pRT** [comment]
### From @simoncozens

It doesn't seem to\, but I can't find a better way of doing it without
major reworking\. Maybe I'm missing something obvious\.

But apparently it breaks "use strict" too\, so we're back to segfaults
for now\. :\(

**Comment by p5pRT** [comment]
### From @vanstyn

I can't reproduce that here&#8203;:
&nbsp;  crypt% perl \-DX ~/t0
&nbsp;  Pad 0x8115518 alloc 1 for entersub
&nbsp;  Pad 0x8115518 alloc 2 for concat
&nbsp;  Pad 0x8115518 alloc 3 for entersub
&nbsp;  Pad 0x811c6e0 alloc 4 for entersub
&nbsp;  Pad 0x811bc60 free 2
&nbsp;  Pad 0x811bc60 free 3
&nbsp;  Pad 0x811bc60 free 4
&nbsp;  syntax error at /home/hv/t0 line 4\, near "or"
&nbsp;  syntax error at /home/hv/t0 line 8\, near "\}"
&nbsp;  Execution of /home/hv/t0 aborted due to compilation errors\.
&nbsp;  crypt% 

That was mostly a 5\.6\.1 compiled on a recent Redhat\, but it may have had
one or two regexp patches applied\.

Hugo


---
Summary of my perl5 \(revision 5\.0 version 6 subversion 1\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.4\.2\-2\, archname=i686\-linux
&nbsp;    uname='linux crypt 2\.4\.2\-2 \#1 sun apr 8 20&#8203;:41&#8203;:30 edt 2001 i686 unknown '
&nbsp;    config\_args='\-des \-Dprefix=/opt/perl\-5\.6\.1 \-Doptimize=\-g \-O6'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
&nbsp;    useperlio=undef d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-DDEBUGGING \-fno\-strict\-aliasing \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g \-O6'\,
&nbsp;    cppflags='\-DDEBUGGING \-fno\-strict\-aliasing'
&nbsp;    ccversion=''\, gccversion='2\.96 20000731 \(Red Hat Linux 7\.1 2\.96\-81\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, usemymalloc=n\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-lndbm \-lgdbm \-ldl \-lm \-lc \-lcrypt \-lutil
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lc \-lcrypt \-lutil
&nbsp;    libc=/lib/libc\-2\.2\.2\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
&nbsp;    cccdlflags='\-fpic'\, lddlflags='\-shared \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: DEBUGGING USE\_LARGE\_FILES
&nbsp;  Built under linux
&nbsp;  Compiled at Jul  1 2001 14&#8203;:25&#8203;:14
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /opt/perl\-5\.6\.1/lib/5\.6\.1/i686\-linux
&nbsp;    /opt/perl\-5\.6\.1/lib/5\.6\.1
&nbsp;    /opt/perl\-5\.6\.1/lib/site\_perl/5\.6\.1/i686\-linux
&nbsp;    /opt/perl\-5\.6\.1/lib/site\_perl/5\.6\.1
&nbsp;    /opt/perl\-5\.6\.1/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @schwern

Nor can I\, with Debian's 5\.6\.1\, my own 5\.6\.1 or my own 5\.005\_03\.

Can we get the \-V info?

**Comment by p5pRT** [comment]
### From @simoncozens

Segfaults in both Debian's 5\.6\.1&#8203;:

Summary of my perl5 \(revision 5\.0 version 6 subversion 1\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.4\.5\-ac9\, archname=i386\-linux
&nbsp;    uname='linux duende 2\.4\.5\-ac9 \#1 thu jun 21 00&#8203;:52&#8203;:39 est 2001 i686 unknown '
&nbsp;    config\_args='\-Dccflags=\-DDEBIAN \-Dcccdlflags=\-fPIC \-Darchname=i386\-linux \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.6\.1 \-Darchlib=/usr/lib/perl/5\.6\.1 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.6\.1 \-Dsitearch=/usr/local/lib/perl/5\.6\.1 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dman1ext=1 \-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Uusesfio \-Dotherlibdirs=/usr/lib/perl5/5\.6&#8203;:/usr/lib/perl5/5\.005 \-Duseshrplib \-Dlibperl=libperl\.so\.5\.6\.1 \-Dd\_dosuid \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
&nbsp;    useperlio=undef d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-DDEBIAN \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2'\,
&nbsp;    cppflags='\-DDEBIAN \-fno\-strict\-aliasing \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='2\.95\.4 20010604 \(Debian prerelease\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, usemymalloc=n\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lgdbm \-ldbm \-ldb \-ldl \-lm \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lc \-lcrypt
&nbsp;    libc=/lib/libc\-2\.2\.3\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.6\.1
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: USE\_LARGE\_FILES
&nbsp;  Built under linux
&nbsp;  Compiled at Jun 22 2001 18&#8203;:52&#8203;:37
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/lib/perl/5\.6\.1
&nbsp;    /usr/local/share/perl/5\.6\.1
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/perl/5\.6\.1
&nbsp;    /usr/share/perl/5\.6\.1
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    /usr/lib/perl5/5\.6
&nbsp;    /usr/lib/perl5/5\.005
&nbsp;    \.

and my 5\.7\.2&#8203;:


Summary of my perl5 \(revision 5\.0 version 7 subversion 2\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.4\.4\, archname=i686\-linux
&nbsp;    uname='linux riot\-act 2\.4\.4 \#3 tue jun 26 15&#8203;:54&#8203;:52 jst 2001 i686 unknown '
&nbsp;    config\_args='\-Dusedevel \-Dotherlibdirs=/usr/local/lib/perl/5\.6\.1&#8203;:/usr/local/share/perl/5\.6\.1&#8203;:/usr/lib/perl5&#8203;:/usr/share/perl5&#8203;:/usr/lib/perl/5\.6\.1&#8203;:/usr/share/perl/5\.6\.1&#8203;:/usr/local/lib/site\_perl&#8203;:/usr/lib/perl5/5\.6&#8203;:/usr/lib/perl5/5\.005&#8203;:\. \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-Wall \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2'\,
&nbsp;    cppflags='\-Wall \-fno\-strict\-aliasing \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='2\.95\.4 20010703 \(Debian prerelease\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, usemymalloc=n\, prototype=define\, bincompat5005=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-ldl \-lm \-lc \-lcrypt \-lutil
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lc \-lcrypt \-lutil
&nbsp;    libc=/lib/libc\-2\.2\.3\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
&nbsp;    cccdlflags='\-fpic'\, lddlflags='\-shared \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: USE\_LARGE\_FILES
&nbsp;  Built under linux
&nbsp;  Compiled at Jul 24 2001 19&#8203;:12&#8203;:39
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/lib/perl5/5\.7\.2/i686\-linux
&nbsp;    /usr/local/lib/perl5/5\.7\.2
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.7\.2/i686\-linux
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.7\.2
&nbsp;    /usr/local/lib/perl5/site\_perl
&nbsp;    /usr/local/lib/perl/5\.6\.1
&nbsp;    /usr/local/share/perl/5\.6\.1
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/perl/5\.6\.1
&nbsp;    /usr/share/perl/5\.6\.1
&nbsp;    /usr/local/lib/site\_perl/i686\-linux
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    /usr/lib/perl5/5\.6
&nbsp;    /usr/lib/perl5/5\.005
&nbsp;    \.
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @nwc10

Segfaults on 12004 on x86 debian after the first \}

FreeBSD 12003 gives
syntax error at \- line 4\, near "or"
syntax error at \- line 8\, near "\}"

What's the significant difference between the 2 platforms that causes these
differences with syntax errors\.

Nicholas Clark

**Comment by p5pRT** [comment]
### From @schwern

Looking through my Debian 5\.6\.1 \(ie\. the PowerPC version\) and your
Debian 5\.6\.1 \(ie\. the x86 version\) the only significant difference I
see is&#8203;:

&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=4321
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=8
&nbsp;    alignbytes=8\, usemymalloc=n\, prototype=define

The different byteorder\, long double size and alignbytes\.  I have no
idea if this is signifcant\, but otherwise we should have perl binaries
built from the exact same source\, libs and compilers\.
