### ISSUE TITLE
Alpha error writing exceptional math value

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4349]
Migrated from [rt.perl.org#7585](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=7585) (status was 'resolved')

Searchable as RT7585$

**Comment by p5pRT** [comment]
### From dalke@pw600a.bioperl.org



There is a problem with Perl 5\.005\_03 and 5\.6\.1  when printing
the IEEE 754 NaN exception value\.

Here's the reproducible\, with the first to show that non\-exceptional
values really do work\.

 ===============
\[dalke@&#8203;pw600a perl\-5\.6\.1\]$ \./perl \-Ilib \-e 'use POSIX; print acos\(0\.5\)\, "\\n"'
1\.0471975511966
\[dalke@&#8203;pw600a perl\-5\.6\.1\]$ \./perl \-Ilib \-e 'use POSIX; print acos\(3\.7\)\, "\\n"'
Floating exception \(core dumped\)
\[dalke@&#8203;pw600a perl\-5\.6\.1\]$ \./perl \-version

This is perl\, v5\.6\.1 built for alpha\-linux

Copyright 1987\-2001\, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License\, which may be found in the Perl 5 source kit\.

Complete documentation for Perl\, including FAQ lists\, should be found on
this system using \`man perl' or \`perldoc perl'\.  If you have access to the
Internet\, point your browser at http&#8203;://www\.perl\.com/\, the Perl Home Page\.
&nbsp;  ===============

I recompiled Perl with \-g support to get a full stack trace\.

 \[\.\.\.\]
Reading symbols from /tmp/apd/perl\-5\.6\.1/lib/auto/POSIX/POSIX\.so\.\.\.done\.
\#0  0x12009a4ac in Perl\_cast\_iv \(f=NaN\(0x8000000000000\)\) at util\.c&#8203;:2828
2828        if \(f >= IV\_MAX\) \{
\(gdb\) where
\#0  0x12009a4ac in Perl\_cast\_iv \(f=NaN\(0x8000000000000\)\) at util\.c&#8203;:2828
\#1  0x1200c36d0 in Perl\_sv\_upgrade \(sv=0x120292a00\, mt=6\) at sv\.c&#8203;:957
\#2  0x1200c8c48 in Perl\_sv\_2pv \(sv=0x120292a00\, lp=0x11ffff928\) at sv\.c&#8203;:2209
\#3  0x1201416e4 in Perl\_do\_print \(sv=0x120292a00\, fp=0x200006a08a8\)
&nbsp;    at doio\.c&#8203;:1155
\#4  0x1200b3e90 in Perl\_pp\_print \(\) at pp\_hot\.c&#8203;:407
\#5  0x1200b0a8c in Perl\_runops\_debug \(\) at run\.c&#8203;:53
\#6  0x12001d0cc in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1471
\#7  0x12001ca70 in perl\_run \(my\_perl=0x120286b30\) at perl\.c&#8203;:1393
\#8  0x120017668 in main \(argc=4\, argv=0x11ffffbc8\, env=0x11ffffbf0\)
&nbsp;    at perlmain\.c&#8203;:52

\(gdb\) print f
$1 = NaN\(0x8000000000000\)
\(gdb\) list
2823    \}
2824
2825    IV
2826    Perl\_cast\_iv\(pTHX\_ NV f\)
2827    \{
2828        if \(f >= IV\_MAX\) \{
2829            UV uv;
2830
2831            if \(f >= \(NV\)UV\_MAX\)
2832                return \(IV\) UV\_MAX;

I can reproduce this problem in C\, as

lke@&#8203;pw600a perl\-5\.6\.1\]$ cat q\.c
\#include \<stdio\.h>
\#include \<math\.h>
\#include \<stdint\.h>

\#define IV\_MAX INT64\_MAX
main\(\) \{
&nbsp;  double f = acos\(4\.7\);
&nbsp;  if \(f >= IV\_MAX\) \{
&nbsp;    printf\("Yep\.\\n"\);
&nbsp;  \} else \{
&nbsp;    printf\("Nope\.\\n"\);
&nbsp;  \}
\}
\[dalke@&#8203;pw600a perl\-5\.6\.1\]$ cc q\.c \-lm \-g
\[dalke@&#8203;pw600a perl\-5\.6\.1\]$ \./a\.out
Floating exception \(core dumped\)
\[dalke@&#8203;pw600a perl\-5\.6\.1\]$ gdb a\.out core
GNU gdb 19991004
Copyright 1998 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and you are
welcome to change it and/or distribute copies of it under certain conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for details\.
This GDB was configured as "alpha\-redhat\-linux"\.\.\.

warning&#8203;: "/tmp/apd/perl\-5\.6\.1/core"&#8203;: ambiguous core format\, 2 handlers match
Core was generated by \`\./a\.out'\.
Program terminated with signal 8\, Floating point exception\.
Reading symbols from /lib/libm\.so\.6\.1\.\.\.done\.
Reading symbols from /lib/libc\.so\.6\.1\.\.\.done\.
Reading symbols from /lib/ld\-linux\.so\.2\.\.\.done\.
\#0  0x1200004c8 in main \(\) at q\.c&#8203;:8
8         if \(f >= IV\_MAX\) \{
\(gdb\)

Here's the assembly dump of that code&#8203;:

0x120000480 \<main>&#8203;:     ldah    gp\,17\(t12\)
0x120000484 \<main\+4>&#8203;:   lda     gp\,\-32296\(gp\)
0x120000488 \<main\+8>&#8203;:   subq    sp\,0x20\,sp
0x12000048c \<main\+12>&#8203;:  stq     ra\,0\(sp\)
0x120000490 \<main\+16>&#8203;:  stq     fp\,8\(sp\)
0x120000494 \<main\+20>&#8203;:  mov     sp\,fp
0x120000498 \<main\+24>&#8203;:  ldq     t0\,\-32672\(gp\)
0x12000049c \<main\+28>&#8203;:  ldt     $f16\,0\(t0\)
0x1200004a0 \<main\+32>&#8203;:  ldq     t12\,\-32728\(gp\)
0x1200004a4 \<main\+36>&#8203;:  jsr     ra\,\(t12\)\,0x120000000
0x1200004a8 \<main\+40>&#8203;:  ldah    gp\,17\(ra\)
0x1200004ac \<main\+44>&#8203;:  lda     gp\,\-32336\(gp\)
0x1200004b0 \<main\+48>&#8203;:  fmov    $f0\,$f10
0x1200004b4 \<main\+52>&#8203;:  stt     $f10\,16\(fp\)
0x1200004b8 \<main\+56>&#8203;:  ldt     $f10\,16\(fp\)
0x1200004bc \<main\+60>&#8203;:  ldq     t0\,\-32680\(gp\)
0x1200004c0 \<main\+64>&#8203;:  ldt     $f11\,0\(t0\)
0x1200004c4 \<main\+68>&#8203;:  cmptle  $f11\,$f10\,$f10
0x1200004c8 \<main\+72>&#8203;:  fbeq    $f10\,0x1200004e4 \<main\+100>
0x1200004cc \<main\+76>&#8203;:  ldq     a0\,\-32688\(gp\)
0x1200004b8 \<main\+56>&#8203;:  ldt     $f10\,16\(fp\)
0x1200004bc \<main\+60>&#8203;:  ldq     t0\,\-32680\(gp\)
0x1200004c0 \<main\+64>&#8203;:  ldt     $f11\,0\(t0\)
0x1200004c4 \<main\+68>&#8203;:  cmptle  $f11\,$f10\,$f10   \<\-\-\- SIGFPE occurs here
0x1200004c8 \<main\+72>&#8203;:  fbeq    $f10\,0x1200004e4 \<main\+100>
0x1200004cc \<main\+76>&#8203;:  ldq     a0\,\-32688\(gp\)
0x1200004d0 \<main\+80>&#8203;:  ldq     t12\,\-32744\(gp\)
0x1200004d4 \<main\+84>&#8203;:  jsr     ra\,\(t12\)\,0x12000063c
0x1200004d8 \<main\+88>&#8203;:  ldah    gp\,17\(ra\)
0x1200004dc \<main\+92>&#8203;:  lda     gp\,\-32384\(gp\)
0x1200004e0 \<main\+96>&#8203;:  br      0x1200004f8 \<main\+120>
0x1200004e4 \<main\+100>&#8203;: ldq     a0\,\-32696\(gp\)
0x1200004e8 \<main\+104>&#8203;: ldq     t12\,\-32744\(gp\)
0x1200004ec \<main\+108>&#8203;: jsr     ra\,\(t12\)\,0x12000063c
0x1200004f0 \<main\+112>&#8203;: ldah    gp\,17\(ra\)
0x1200004f4 \<main\+116>&#8203;: lda     gp\,\-32408\(gp\)
0x1200004f8 \<main\+120>&#8203;: mov     fp\,sp
0x1200004fc \<main\+124>&#8203;: ldq     ra\,0\(sp\)
0x120000500 \<main\+128>&#8203;: ldq     fp\,8\(sp\)
0x120000504 \<main\+132>&#8203;: addq    sp\,0x20\,sp
0x120000508 \<main\+136>&#8203;: ret     zero\,\(ra\)\,0x1

Whe running it assembly step by assembly step in the debugger&#8203;:
\(gdb\) nexti
0x1200004ac     7         double f = acos\(4\.7\);
\(gdb\) nexti
0x1200004b0     7         double f = acos\(4\.7\);
\(gdb\) nexti
0x1200004b4     7         double f = acos\(4\.7\);
\(gdb\) nexti
8         if \(f >= IV\_MAX\) \{
\(gdb\) nexti
0x1200004bc     8         if \(f >= IV\_MAX\) \{
\(gdb\) nexti
0x1200004c0     8         if \(f >= IV\_MAX\) \{
\(gdb\) nexti
0x1200004c4     8         if \(f >= IV\_MAX\) \{
\(gdb\) nexti

Program received signal SIGFPE\, Arithmetic exception\.
0x1200004c8 in main \(\) at q\.c&#8203;:8
8         if \(f >= IV\_MAX\) \{

which is this line of the assembly
0x1200004c4 \<main\+68>&#8203;:  cmptle  $f11\,$f10\,$f10   \<\-\-\- SIGFPE occurs here

I don't know enough about the Perl internals\, Alphas or 64 bit
programming to aid any more than this\.

&nbsp;                    Andrew Dalke
&nbsp;                    dalke@&#8203;dalkescientific\.com
P\.S\.
&nbsp;  This occured because the Perl Cookbook uses acos\(3\.7\) in an
example\.  This number is out of range and I've informed the authors\.
It will be updated to use 0\.37 but in the meanwhile my testing for
the PLEAC \(see pleac\.sf\.net\) translation of the cookbook to Python
found this problem\.

<details><summary>Perl Info</summary>

```

Flags:
    category=library
    severity=low

Site configuration information for perl v5.6.1:

Configured by dalke at Fri Aug 24 12:20:56 EDT 2001.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=linux, osvers=2.2.14-6.0, archname=alpha-linux
    uname='linux pw600a.bioperl.org 2.2.14-6.0 #1 tue mar 28 16:56:56 est 2000 alpha unknown '
    config_args='-de'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=define use64bitall=define uselongdouble=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2',
    cppflags='-fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='egcs-2.91.66 19990314/Linux (egcs-1.1.2 release)', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=8
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /usr/shlib /lib /usr/lib
    libs=-lnsl -lndbm -lgdbm -ldb -ldl -lm -lc -lposix -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lposix -lcrypt -lutil
    libc=, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.1:
    lib
    /usr/local/lib/perl5/5.6.1/alpha-linux
    /usr/local/lib/perl5/5.6.1
    /usr/local/lib/perl5/site_perl/5.6.1/alpha-linux
    /usr/local/lib/perl5/site_perl/5.6.1
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.6.1:
    HOME=/home/dalke
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/dalke/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11R6/bin:/home/biopython/bin
    PERL_BADLANG (unset)
    SHELL=/bin/tcsh

```
</details>

**Comment by p5pRT** [comment]
### From @nwc10

Thanks for the very thorough report\.

> There is a problem with Perl 5\.005\_03 and 5\.6\.1  when printing
> the IEEE 754 NaN exception value\.
> 
> Here's the reproducible\, with the first to show that non\-exceptional
> values really do work\.
> 
>  ===============
> \[dalke@&#8203;pw600a perl\-5\.6\.1\]$ \./perl \-Ilib \-e 'use POSIX; print acos\(0\.5\)\, "\\n"'
> 1\.0471975511966
> \[dalke@&#8203;pw600a perl\-5\.6\.1\]$ \./perl \-Ilib \-e 'use POSIX; print acos\(3\.7\)\, "\\n"'
> Floating exception \(core dumped\)

I asked a friend to run
perl \-we 'use POSIX; print acos\(3\.7\)\, "\\n"'

on an alpha running Debian GNU/Linux\. He gets NaN rather than a core dump\.
He suggests building with \-mieee in the cflags\, which is what Debian use\.


>   Compiler&#8203;:
>     cc='cc'\, ccflags ='\-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
>     optimize='\-O2'\,
>     cppflags='\-fno\-strict\-aliasing \-I/usr/local/include'
>     ccversion=''\, gccversion='egcs\-2\.91\.66 19990314/Linux \(egcs\-1\.1\.2 release\)'\, gccosandvers=''
>     intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
>     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=8
>     ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
>     alignbytes=8\, usemymalloc=n\, prototype=define
>   Linker and Libraries&#8203;:
>     ld='cc'\, ldflags =' \-L/usr/local/lib'
>     libpth=/usr/local/lib /usr/shlib /lib /usr/lib
>     libs=\-lnsl \-lndbm \-lgdbm \-ldb \-ldl \-lm \-lc \-lposix \-lcrypt \-lutil
>     perllibs=\-lnsl \-ldl \-lm \-lc \-lposix \-lcrypt \-lutil
>     libc=\, so=so\, useshrplib=false\, libperl=libperl\.a
>   Dynamic Linking&#8203;:
>     dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
>     cccdlflags='\-fpic'\, lddlflags='\-shared \-L/usr/local/lib'

Debian's Alpha perl gives a \-V of

Summary of my perl5 \(revision 5\.0 version 6 subversion 1\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.2\.15\, archname=alpha\-linux
&nbsp;    uname='linux flatline 2\.2\.15 \#8 smp fri jul 12 09&#8203;:36&#8203;:31 mst 2052 alpha unknown '
&nbsp;    config\_args='\-Dccflags=\-DDEBIAN \-mieee \-Dcccdlflags=\-fPIC \-Darchname=alpha\-linux \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.6\.1 \-Darchlib=/usr/lib/perl/5\.6\.1 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.6\.1 \-Dsitearch=/usr/local/lib/perl/5\.6\.1 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dman1ext=1 \-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Uusesfio \-Dotherlibdirs=/usr/lib/perl5/5\.6&#8203;:/usr/lib/perl5/5\.005 \-Duseshrplib \-Dlibperl=libperl\.so\.5\.6\.1 \-Dd\_dosuid \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
&nbsp;    useperlio=undef d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=define use64bitall=define uselongdouble=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-DDEBIAN \-mieee \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2'\,
&nbsp;    cppflags='\-DDEBIAN \-mieee \-fno\-strict\-aliasing \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='2\.95\.4 20010604 \(Debian prerelease\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=8
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, usemymalloc=n\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lgdbm \-ldbm \-ldb \-ldl \-lm \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lc \-lcrypt
&nbsp;    libc=\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.6\.1
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: USE\_64\_BIT\_INT USE\_64\_BIT\_ALL USE\_LARGE\_FILES
&nbsp;  Built under linux
&nbsp;  Compiled at Jun 24 2001 01&#8203;:25&#8203;:23
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/lib/perl/5\.6\.1
&nbsp;    /usr/local/share/perl/5\.6\.1
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/perl/5\.6\.1
&nbsp;    /usr/share/perl/5\.6\.1
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    /usr/lib/perl5/5\.6/alpha\-linux
&nbsp;    /usr/lib/perl5/5\.6
&nbsp;    /usr/lib/perl5/5\.005
&nbsp;    \.


Is building with \-mieee a sensible idea? If so\, should it be on by
default on Alpha linux?

Nicholas Clark

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

I recompiled the devel version of perl 5\.6\.1 to use
the \-mieee flag\.  That prevented the SIGFPE\.

\[perl\-5\.7\.2\]$ \./perl \-Ilib \-e 'use POSIX; print acos\(3\.7\)\, "\\n"'
nan
\[perl\-5\.7\.2\]$ perl \-e 'use POSIX; print acos\(3\.7\)\, "\\n"'
Floating exception \(core dumped\)
\[perl\-5\.7\.2\]$

> Is building with \-mieee a sensible idea? If so\, should
> it be on by default on Alpha linux?

Frankly\, I don't know\.  If Debian does it and since
it prevents this signal from occuring\, then I would
recommend it\.  I don't know enough of the consequences
for that to be a solid recommendation\.

&nbsp;                    Andrew
&nbsp;                    dalke@&#8203;dalkescientific\.com

**Comment by p5pRT** [comment]
### From @tux

Something to add to a hint file? \(hint hint\)

> \[perl\-5\.7\.2\]$ \./perl \-Ilib \-e 'use POSIX; print acos\(3\.7\)\, "\\n"'
> nan
> \[perl\-5\.7\.2\]$ perl \-e 'use POSIX; print acos\(3\.7\)\, "\\n"'
> Floating exception \(core dumped\)
> \[perl\-5\.7\.2\]$
> 
> > Is building with \-mieee a sensible idea? If so\, should
> > it be on by default on Alpha linux?
> 
> Frankly\, I don't know\.  If Debian does it and since
> it prevents this signal from occuring\, then I would
> recommend it\.  I don't know enough of the consequences
> for that to be a solid recommendation\.

**Comment by p5pRT** [comment]
### From @doy

Can this be reproduced on newer versions of perl? Do we have anyone
building on Alpha anymore?

\-doy

**Comment by p5pRT** [comment]
### From @doy

11&#8203;:43 \<@&#8203;BinGOs> doy&#8203;: \#7585 all my non\-debian perls on this debian/alpha
linux box produce 'nan' 
11&#8203;:43 \<@&#8203;BinGOs> v5\.10\.1 and upwards
11&#8203;:44 \<@&#8203;BinGOs> for perl \-e 'use POSIX; print acos\(3\.7\)\, "\\n"'

None of these perls were built with \-mieee\, so I think this can probably
be closed\.

\-doy

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

11&#8203;:43 \<@&#8203;BinGOs> doy&#8203;: \#7585 all my non\-debian perls on this debian/alpha
linux box produce 'nan' 
11&#8203;:43 \<@&#8203;BinGOs> v5\.10\.1 and upwards
11&#8203;:44 \<@&#8203;BinGOs> for perl \-e 'use POSIX; print acos\(3\.7\)\, "\\n"'

None of these perls were built with \-mieee\, so I think this can probably
be closed\.

\-doy

**Comment by p5pRT** [comment]
@doy - Status changed from 'open' to 'resolved'
