### ISSUE TITLE
SEGV from ($a, b) = (1, 2)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4364]
Migrated from [rt.perl.org#7605](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=7605) (status was 'resolved')

Searchable as RT7605$

**Comment by p5pRT** [comment]
### From john@TheUsGroup.com



Script started on Thu Aug 30 00&#8203;:18&#8203;:00 2001

% cat core\_test\.pl
\#\!/usr/bin/perl 
\($a\, b\) = \(1\, 2\);

% perl \-cw core\_test\.pl
Unquoted string "b" may clash with future reserved word at core\_test\.pl line 3\.
Name "main&#8203;::a" used only once&#8203;: possible typo at core\_test\.pl line 3\.
Name "main&#8203;::b" used only once&#8203;: possible typo at core\_test\.pl line 3\.
core\_test\.pl syntax OK
zsh&#8203;: segmentation fault \(core dumped\)  perl \-cw core\_test\.pl

% gdb /usr/bin/perl perl\.core
Core was generated by \`perl'\.
Program terminated with signal 11\, Segmentation fault\.
\#0  0x481d37b6 in wrtwarning \(\)
\(gdb\) bt
\#0  0x481d37b6 in wrtwarning \(\)
\#1  0x481d4673 in ifree \(\)
\#2  0x481d492b in free \(\)
\#3  0x480a5b45 in Perl\_safefree \(\)
\#4  0x4808b946 in Perl\_op\_free \(\)
\#5  0x4808b909 in Perl\_op\_free \(\)
\#6  0x4808b909 in Perl\_op\_free \(\)
\#7  0x4808b909 in Perl\_op\_free \(\)
\#8  0x4808b909 in Perl\_op\_free \(\)
\#9  0x4808b909 in Perl\_op\_free \(\)
\.\.\.
\(gdb\) q

%
Script done on Thu Aug 30 00&#8203;:19&#8203;:12 2001

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.6.1:

Configured by john at Thu May  3 02:53:35 PDT 2001.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=bsdos, osvers=4.1, archname=i386-bsdos
    uname='bsdos theusgroup.com 4.1 bsdi bsdos 4.1 kernel #2: sat jan 13 17:20:53 pst 2001 john@theusgroup.com:localsrcsyscompilegate i386 '
    config_args='-des'
    hint=previous, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -I/usr/local/include',
    optimize='-O2',
    cppflags='-fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='egcs-2.91.66 19990314 (egcs-1.1.2 release)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='ld', ldflags =' -L/usr/X11/lib -L/usr/local/lib'
    libpth=/usr/local/lib /usr/shlib /shlib /lib /usr/lib /usr/X11/lib
    libs=-lutil -lbind -lgdbm -ldl -lm -lc
    perllibs=-lutil -lbind -ldl -lm -lc
    libc=/shlib/libc.so, so=so, useshrplib=true, libperl=libperl.so
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic -Wl,-rpath,//CORE'
    cccdlflags='-fPIC', lddlflags='-shared -x  -L/usr/X11/lib -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.1:
    /usr/local/lib/perl5/5.6.1/i386-bsdos
    /usr/local/lib/perl5/5.6.1
    /usr/local/lib/perl5/site_perl/5.6.1/i386-bsdos
    /usr/local/lib/perl5/site_perl/5.6.1
    /usr/local/lib/perl5/site_perl/5.6.0/i386-bsdos
    /usr/local/lib/perl5/site_perl/5.6.0
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.6.1:
    HOME=/usr/home/john
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/local/bin:/usr/local/X11/bin:/bin:/sbin:/usr/sbin:/usr/bin:/usr/contrib/bin:/usr/X11/bin:/usr/local/gnu/bin
    PERL_BADLANG (unset)
    SHELL=/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @schwern

This appears to have been fixed in bleadperl\.


Hmmm\.\.\. with an eye towards writing a test for this\, how do you run a
program and reliably tell that it's segfaulted?  WCOREDUMP doesn't
appear to be universal\.

Best I can do is check to see if it exited with 255 and the right
output\, which appears to be perl's normal exit code on a syntax error\.

I also can't seem to get \`\` to pipe STDERR to STDOUT using like I did
in lib/warnings\.t\, so I'll have to use 2>&1 and just skip on Win32 and
VMS for the moment :\(


Right\.  Here's a new test where we can stick all these little bits of
code that cause segfaults\.  Hopefully someone can fix the 2>&1 problem\.


<details><summary>Inline Patch</summary>

```diff
--- /dev/null	Sun Jul  1 22:55:26 2001
+++ t/run/segfault.t	Fri Aug 31 15:35:08 2001
@@ -0,0 +1,43 @@
+#!./perl
+#
+# Tests for things which have caused segfaults in the past.
+
+BEGIN {
+    chdir 't' if -d 't';
+    @INC = '../lib';
+}
+
+# VMS and Windows need -e "...", most everything else works better with '
+my $quote = $^O =~ /^(VMS|MSWin\d+)$/ ? q{"} : q{'};
+
+my $IsVMS = $^O eq 'VMS';
+
+
+BEGIN {
+   if( $^O =~ /^(VMS|MSWin\d+)$/ ) {
+      print "1..0 # Skipped: platform temporarily not supported\n";
+      exit;
+   }
+}
+
+
+# Run some code, check that it has the expected output and exits
+# with the code for a perl syntax error.
+sub chk_segfault {
+    my($code, $expect, $name) = @_;
+    my $cmd = "$^X -e ";
+
+    # I *think* these are the right exit codes for syntax error.
+    my $expected_exit = $IsVMS ? 4 : 255;
+
+    my $out = `$cmd$quote$code$quote 2>&1`;
+
+    is( $? >> 8,    $expected_exit,     "$name - exit as expected" );
+    like( $out, qr/$expect at -e line 1/, '  with the right output' );
+}
+
+use Test::More tests => 2;
+
+chk_segfault('($a, b) = (1, 2)',  
+             "Can't modify constant item in list assignment",
+             'perlbug ID 20010831.001');
```
</details>

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'resolved'
