### ISSUE TITLE
Time::HiRes form perl dist makes perl segfault

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4483]
Migrated from [rt.perl.org#7797](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=7797) (status was 'resolved')

Searchable as RT7797$

**Comment by p5pRT** [comment]
### From root@schmorp.de



Since about 5\.7\.2\, I get this behaviour after installing a new perl&#8203;:

&nbsp;   perl some\_script\_suing\_time\_hires
&nbsp;   segfault

When I run make test im Event\, for example\, all tests fail quickly\, here
is a \(bad\, sorry\) backtrace&#8203;:

&nbsp;   \(gdb\) bt
&nbsp;   \#0  0x3bc0493e in ?? \(\) at eval\.c&#8203;:88
&nbsp;   \#1  0x401c4ef1 in pe\_watcher\_on \(\) from /localvol/root/\.cpan/build/Event\-0\.83/blib/arch/auto/Event/Event\.so
&nbsp;   \#2  0x401c4fe2 in pe\_watcher\_start \(\) from /localvol/root/\.cpan/build/Event\-0\.83/blib/arch/auto/Event/Event\.so
&nbsp;   \#3  0x401c9f7e in XS\_Event\_\_Watcher\_start \(\) from /localvol/root/\.cpan/build/Event\-0\.83/blib/arch/auto/Event/Event\.so
&nbsp;   \#4  0x80a666b in Perl\_pp\_entersub \(\) at eval\.c&#8203;:88
&nbsp;   \#5  0x80a0220 in Perl\_runops\_standard \(\) at eval\.c&#8203;:88
&nbsp;   \#6  0x805ed5d in S\_run\_body \(\) at eval\.c&#8203;:88
&nbsp;   \#7  0x805ea9b in perl\_run \(\) at eval\.c&#8203;:88
&nbsp;   \#8  0x805c4ed in main \(\) at eval\.c&#8203;:88
&nbsp;   \#9  0x400687d6 in \_\_libc\_start\_main \(main=0x805c464 \<main>\, argc=3\, ubp\_av=0xbffff6d4\, init=0x805b5e0 \<\_init>\, fini=0x80f77d8 \<\_fini>\, 
&nbsp;             rtld\_fini=0x4000b610 \<\_dl\_fini>\, stack\_end=0xbffff6cc\) at \.\./sysdeps/generic/libc\-start\.c&#8203;:129

The culprit seems to be Time&#8203;::HiRes\. If I install the 1\.20 cpan version
everything is fine\. If i go into perl\*/ext/Time/HiRes and do perl \*PL;make
install I get segfaults all over the place again\.

Very fishy\.

\(yes\, I did rm \-rf /usr/app/lib/perl5 before installing the new version
and don't have any HiRes\.so or somesuch lying around elsewhere\)\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl v5.7.2:

Configured by root at Sun Oct  7 14:09:45 CEST 2001.

Summary of my perl5 (revision 5.0 version 7 subversion 2 patch 12348) configuration:
  Platform:
    osname=linux, osvers=2.4.8, archname=i686-linux
    uname='linux cerebro 2.4.8-ac9 #7 smp thu aug 30 00:15:46 cest 2001 i686 unknown '
    config_args=''
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=y, bincompat5005=undef
  Compiler:
    cc='gcc-2.95.4', ccflags ='-fno-strict-aliasing -I/usr/local/include -I/opt/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-g -Os -march=pentium -mcpu=pentium -funroll-loops',
    cppflags='-fno-strict-aliasing -I/usr/local/include -I/opt/include'
    ccversion='', gccversion='2.95.4 20010319 (prerelease)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='gcc-2.95.4', ldflags ='-L/usr/local/lib -L/opt/lib'
    libpth=/usr/local/lib /lib /usr/lib /opt/lib
    libs=-ldl -lm -lc -lcrypt
    perllibs=-ldl -lm -lc -lcrypt
    libc=/lib/libc-2.2.4.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib -L/opt/lib'

Locally applied patches:
    DEVEL12339


@INC for perl v5.7.2:
    /usr/app/lib/perl5
    /usr/app/lib/perl5
    /usr/app/lib/perl5
    /usr/app/lib/perl5
    .


Environment for perl v5.7.2:
    HOME=/root
    LANG (unset)
    LANGUAGE (unset)
    LC_CTYPE=de_DE
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/root/s:/opt/qt/bin:/bin:/usr/bin:/usr/app/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/app/bin:/usr/app/sbin:/usr/X11/bin:/opt/jdk118/bin:/opt/bin:/opt/sbin:.:/root/cc/dejagnu/bin
    PERLDB_OPTS=ornaments=0
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @jhi

Duplicate report of a resolved ticket\, marking also this as resolved\.

**Comment by p5pRT** [comment]
@jhi - Status changed from 'open' to 'resolved'
