### ISSUE TITLE
signal handlers and waitpid

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4485]
Migrated from [rt.perl.org#7799](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=7799) (status was 'resolved')

Searchable as RT7799$

**Comment by p5pRT** [comment]
### From bergolth@ollie.wu-wien.ac.at



I've written a small test\-script \(see below\) that dumps core
because of a segmentation violation on many systems when the signal
handler is called while there is memory is allocated in the main
program\. The signal handler doesn't use or modify any variable\,
it's only&#8203;:

&nbsp;  $SIG\{'CHLD'\} = sub \{
&nbsp;    while \(waitpid\(\-1\,&WNOHANG\) > 0\) \{ \}
&nbsp;  \};

I've tested this with perl\-5\.6\.0 on AIX\-4\.2\.1 and AIX\-4\.3\.3 and
with perl\-5\.005\_03 on linux\-2\.2\.19\.

The test\-script and the stack backtrace is attached below\.\.\.
\(The random\- and delay\-parameters are optimised for a crash on
slower machines\.\)

\-\-\-\-\-\-\-\-\-\- snipp\! \-\-\-\-\-\-\-\-\-\-
\#\!/usr/local/bin/perl

use strict;
use POSIX "&#8203;:sys\_wait\_h";

my $RAND1= 2000;
my $RAND2= 2000;
my $DELAY\_MAIN = 0\.1;
my $DELAY\_CHILD = 2;

$SIG\{'CHLD'\} = sub \{
&nbsp;  while \(waitpid\(\-1\,&WNOHANG\) > 0\) \{ \}
\};

my $CHILD\_PID   = 0;

srand\(\);
$|= 1;

my $i;
for \($i = 1; $i \< 200; $i\+\+\) \{
&nbsp;  print "fork $i\\n";
&nbsp;  \# allocate some memory
&nbsp;  my \($i\, $r1\, $r2\, @&#8203;buf\);
&nbsp;  $r1= rand\($RAND1\);
&nbsp;  for \($i= 1; $i \<= $r1; $i\+\+\) \{
&nbsp;    $r2= rand\($RAND2\);
&nbsp;    $buf\[$i\] = "x" x $r2;
&nbsp;  \}

&nbsp;  my $pid;
&nbsp;  if \($pid = fork\) \{
&nbsp;    \# parent
&nbsp;    select\(undef\, undef\, undef\, $DELAY\_MAIN\);
&nbsp;    print "          Child $pid ready\\n";
&nbsp;    next;
&nbsp;  \} elsif \(defined $pid\) \{
&nbsp;    \# child
&nbsp;    $SIG\{'CHLD'\} = 'DEFAULT';
&nbsp;    print "          Child $$ ready\\n";
&nbsp;    select \(undef\, undef\, undef\, rand\($DELAY\_CHILD\)\);
&nbsp;    print "          Child $$ exit\\n";
&nbsp;    exit\(0\);
&nbsp;  \}
&nbsp;  else \{
&nbsp;    print "Fork error&#8203;: $\!\\n";
&nbsp;    return;
&nbsp;  \}
\}

print "Done\\n";

\-\-\-\-\-\-\-\-\-\- snipp\! \-\-\-\-\-\-\-\-\-\-

perl\-5\.6\.0 on Linux\-2\.2\.19&#8203;:
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
\#0  chunk\_alloc \(ar\_ptr=0x40141d40\, nb=16\) at malloc\.c&#8203;:2814
\#1  0x400ac5ae in malloc \(\) at malloc\.c&#8203;:2181
\#2  0x807bbe5 in Perl\_safemalloc \(\)
\#3  0x808abb6 in Perl\_sv\_grow \(\)
\#4  0x808cb10 in Perl\_sv\_setsv \(\)
\#5  0x808ebf5 in Perl\_sv\_mortalcopy \(\)
\#6  0x8087d8a in Perl\_pp\_leave \(\)
\#7  0x80b49ad in Perl\_runops\_standard \(\)
\#8  0x8059a01 in perl\_call\_sv \(\)
\#9  0x8081cb8 in Perl\_sighandler \(\)
\#10 0x40071c48 in \_\_restore \(\) at
\.\./sysdeps/unix/sysv/linux/i386/sigaction\.c&#8203;:127
\#11 0x400ac5ae in malloc \(\) at malloc\.c&#8203;:2181
\#12 0x807bbe5 in Perl\_safemalloc \(\)
\#13 0x808abb6 in Perl\_sv\_grow \(\)
\#14 0x808cb10 in Perl\_sv\_setsv \(\)
\#15 0x808533b in Perl\_pp\_sassign \(\)
\#16 0x80b49ad in Perl\_runops\_standard \(\)
\#17 0x8059338 in perl\_run \(\)
\#18 0x80577e1 in main \(\)
\#19 0x4006b9cb in \_\_libc\_start\_main \(\) at
\.\./sysdeps/generic/libc\-start\.c&#8203;:122


perl\-5\.6\.0 on AIX\-4\.2\.1&#8203;:
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
malloc\_y\.malloc\_y\(??\) at 0xd02656c8
malloc\.malloc\(??\) at 0xd0262f10
Perl\_safesysmalloc\(\) at 0x100313e4
Perl\_sv\_grow\(\) at 0x10027550
Perl\_sv\_setsv\(\) at 0x10024e08
Perl\_pp\_sassign\(\) at 0x1007d1b8
Perl\_runops\_standard\(\) at 0x1006340c
S\_run\_body\(\) at 0x100007c4
perl\_run\(\) at 0x100068d0
main\(\) at 0x100003cc

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.6.0:

Configured by bergolth at Fri Oct 20 19:23:46 MES 2000.

Summary of my perl5 (revision 5.0 version 6 subversion 0) configuration:
  Platform:
    osname=aix, osvers=4.2.1.0, archname=aix42
    uname='aix ollie 2 4 0045781a4c00 '
    config_args='-d'
    hint=previous, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define 
    use64bitint=undef use64bitall=undef uselongdouble=undef usesocks=undef
  Compiler:
    cc='/usr/vac/bin/cc_r', optimize='-O', gccversion=
    cppflags='-D_ALL_SOURCE -D_ANSI_C_SOURCE -D_POSIX_SOURCE -qmaxmem=16384 -I/usr/local/include -I/usr/local/BerkeleyDB.3.1/include'
    ccflags ='-D_ALL_SOURCE -D_ANSI_C_SOURCE -D_POSIX_SOURCE -qmaxmem=16384 -I/usr/local/include -I/usr/local/BerkeleyDB.3.1/include'
    stdchar='unsigned char', d_stdstdio=define, usevfork=false
    intsize=4, longsize=4, ptrsize=4, doublesize=8
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=8
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=4
    alignbytes=8, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='ld', ldflags ='-L/usr/local/lib -L/usr/local/BerkeleyDB.3.1/lib'
    libpth=/usr/local/lib /usr/local/BerkeleyDB.3.1/lib /lib /usr/lib /usr/ccs/lib
    libs=-lbind -lnsl -ldbm -ldl -lld -lm -lC -lc -lbsd -lPW -liconv -ldb
    libc=, so=a, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_aix.xs, dlext=so, d_dlsymun=undef, ccdlflags='  -bE:/usr/local/lib/perl5/5.6.0/aix42/CORE/perl.exp -bE:/usr/local/lib/perl5/5.6.0/aix42/CORE/perl.exp -bE:/usr/local/lib/perl5/5.6.0/aix42/CORE/perl.exp -bE:/usr/local/lib/perl5/5.6.0/aix42/CORE
/perl.exp -bE:/usr/local/lib/perl5/5.6.0/aix42/CORE/perl.exp'
    cccdlflags=' ', lddlflags='-bhalt:4 -bM:SRE -bI:$(PERL_INC)/perl.exp -bE:$(BASEEXT).exp -b noentry -lC -lc -L/usr/local/lib -L/usr/local/BerkeleyDB.3.1/lib'

Locally applied patches:
    


@INC for perl v5.6.0:
    /usr/local/lib/perl5/5.6.0/aix42
    /usr/local/lib/perl5/5.6.0
    /usr/local/lib/perl5/site_perl/5.6.0/aix42
    /usr/local/lib/perl5/site_perl/5.6.0
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.6.0:
    HOME=/afs/wu-wien.ac.at/home/edvz/bergolth
    LANG=C
    LANGUAGE (unset)
    LC_ALL=C
    LC_CTYPE=C
    LC__FASTMSG=true
    LD_LIBRARY_PATH (unset)
    LIBPATH (unset)
    LOGDIR (unset)
    PATH=/afs/wu-wien.ac.at/home/edvz/bergolth/bin:/afs/wu-wien.ac.at/home/edvz/bergolth/work/bin:/usr/ucb:/bin:/usr/bin:/usr/bin/X11:/usr/sbin:/usr/local/bin:/usr/afsws/local/bin:/usr/afsws/bin:/afs/wu/common/infoserv/hotline:/db/app/oracle/product/7.3.2
/bin/:/afs/wu/home/edvz/bergolth/notes
    PERL_BADLANG (unset)
    SHELL=/usr/bin/tcsh

```
</details>

**Comment by p5pRT** [comment]
### From @jhi

Hi\, if you could retry your code under Perl 5\.8\.0?  In Perl 5\.8\.0 signals are 'safe' meaning that signals should not be able to corrupt Perl's internal state as you observed\.

**Comment by p5pRT** [comment]
### From leo@strike.wu-wien.ac.at

Jarkko Hietaniemi \(via RT\) wrote&#8203;:
> Hi\, if you could retry your code under Perl 5\.8\.0?  In Perl 5\.8\.0
 > signals are 'safe' meaning that signals should not be able to corrupt
 > Perl's internal state as you observed\.

Great\!
I'll retry the code as soon as I've upgraded my perl\-version\.

Thanks\,
\-\-leo



---
Alexander \(Leo\) Bergolth                          leo@&#8203;leo\.wu\-wien\.ac\.at
WU\-Wien \- Zentrum fuer Informatikdienste       http&#8203;://leo\.wu\-wien\.ac\.at
&nbsp;                  Computers are like air conditioners \-
&nbsp;            they stop working properly when you open Windows

**Comment by p5pRT** [comment]
### From nick@ing-simmons.net


This is believed fixed by "safe signals" in perl5\.8\.0 and later\.

**Comment by p5pRT** [comment]
nick@ing-simmons.net - Status changed from 'open' to 'resolved'
