### ISSUE TITLE
typo in #! causes SIGABRT [5.6.1/5.7.2]

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4516]
Migrated from [rt.perl.org#7833](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=7833) (status was 'rejected')

Searchable as RT7833$

**Comment by p5pRT** [comment]
### From @pjscott

$ perl \-duse strict

Loading DB routines from perl5db\.pl version 1\.13
Editor support available\.

Enter h or \`h h' for help\, or \`man perldebug' for more help\.

Abort \(core dumped\)

\(Of course\, this originally showed up from a missing newline at the end of 
a \#\!\.\)

$ gdb /usr/bin/perl core
warning&#8203;: core file may not match specified executable file\.
Core was generated by \`perl \-duse strict'\.
Program terminated with signal 6\, Aborted\.
\#0  0x40070d41 in \_\_kill \(\) from /lib/libc\.so\.6
\(gdb\) where
\#0  0x40070d41 in \_\_kill \(\) from /lib/libc\.so\.6
\#1  0x805dcec in Perl\_my\_unexec \(\)
\#2  0x805c1f3 in S\_parse\_body \(\)
\#3  0x805b890 in perl\_parse \(\)
\#4  0x8059e6d in main \(\)
\#5  0x4006a9cb in \_\_libc\_start\_main \(main=0x8059e20 \<main>\, argc=3\,
&nbsp;     argv=0xbffff9b4\, init=0x80590a4 \<\_init>\, fini=0x80debcc \<\_fini>\,
&nbsp;     rtld\_fini=0x4000ae60 \<\_dl\_fini>\, stack\_end=0xbffff9ac\)
&nbsp;     at \.\./sysdeps/generic/libc\-start\.c&#8203;:92

5\.7\.2 built with Configure \-des\, RH6\.2\.  But 5\.6\.1 cores on Solaris 2\.5\.1 also\.
\-\-
Peter Scott
Pacific Systems Design Technologies

**Comment by p5pRT** [comment]
### From @smpeters

> \[Peter@&#8203;PSDT\.com \- Fri Oct 19 16&#8203;:36&#8203;:43 2001\]&#8203;: 
>  
> $ perl \-duse strict 
>  
> Loading DB routines from perl5db\.pl version 1\.13 
> Editor support available\. 
>  
> Enter h or \`h h' for help\, or \`man perldebug' for more help\. 
>  
> Abort \(core dumped\) 
>  
> \(Of course\, this originally showed up from a missing newline at the 
> end of 
> a \#\!\.\) 
>  
> $ gdb /usr/bin/perl core 
> warning&#8203;: core file may not match specified executable file\. 
> Core was generated by \`perl \-duse strict'\. 
> Program terminated with signal 6\, Aborted\. 
> \#0  0x40070d41 in \_\_kill \(\) from /lib/libc\.so\.6 
> \(gdb\) where 
> \#0  0x40070d41 in \_\_kill \(\) from /lib/libc\.so\.6 
> \#1  0x805dcec in Perl\_my\_unexec \(\) 
> \#2  0x805c1f3 in S\_parse\_body \(\) 
> \#3  0x805b890 in perl\_parse \(\) 
> \#4  0x8059e6d in main \(\) 
> \#5  0x4006a9cb in \_\_libc\_start\_main \(main=0x8059e20 \<main>\, argc=3\, 
>      argv=0xbffff9b4\, init=0x80590a4 \<\_init>\, fini=0x80debcc 
\<\_fini>\, 
>      rtld\_fini=0x4000ae60 \<\_dl\_fini>\, stack\_end=0xbffff9ac\) 
>      at \.\./sysdeps/generic/libc\-start\.c&#8203;:92 
>  
> 5\.7\.2 built with Configure \-des\, RH6\.2\.  But 5\.6\.1 cores on Solaris 
> 2\.5\.1 also\. 
> \-\- 
 
When handling the argument\, Perl sees \-duse as \-d and \-u\.  The \-u 
option tells Perl to dump core after parsing the program\.  This is not 
a bug\.

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'rejected'
