### ISSUE TITLE
Core dump on an incorrect syntax

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4544]
Migrated from [rt.perl.org#7865](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=7865) (status was 'resolved')

Searchable as RT7865$

**Comment by p5pRT** [comment]
### From av1046@comtv.ru



Perl segfaults on the following script&#8203;:

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

\{
package test;

sub TIEHANDLER
\{
&nbsp;    my $class = shift;
&nbsp;    my $scalar;
&nbsp;    bless \\$scalar\, $class;
\}

\}
sub test
\{
&nbsp;    local \*FILE;
&nbsp;    tie FILE\, 'test';
\}
test\(\)

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-


Traceback&#8203;:

1228        if \(\!o || \(o\->op\_flags & OPf\_WANT\) || PL\_error\_count
\(gdb\) bt
\#0  0x400612ac in Perl\_list \(o=0x11\) at op\.c&#8203;:1228
\#1  0x40061273 in Perl\_listkids \(o=0x806cb00\) at op\.c&#8203;:1217
\#2  0x4006ebef in Perl\_ck\_fun \(o=0x806cb00\) at op\.c&#8203;:5668
\#3  0x4006491d in Perl\_convert \(type=197\, flags=0\, o=0x806cb00\) at op\.c&#8203;:2396
\#4  0x4005c857 in Perl\_yyparse \(\) at perly\.y&#8203;:420
\#5  0x4003382b in S\_parse\_body \(env=0x0\, xsinit=0x80495c0 \<xs\_init>\)
&nbsp;    at perl\.c&#8203;:1317
\#6  0x400329ce in perl\_parse \(my\_perl=0x804bec8\, xsinit=0x80495c0 \<xs\_init>\, 
&nbsp;    argc=2\, argv=0xbffff8f4\, env=0x0\) at perl\.c&#8203;:895
\#7  0x804956a in main \(argc=2\, argv=0xbffff8f4\, env=0xbffff900\)
&nbsp;    at perlmain\.c&#8203;:50

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.6.1:

Configured by mhz at Fri Nov  2 00:55:56 MSK 2001.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=linux, osvers=2.4.12-alt1-mhz, archname=i386-linux
    uname='linux localhost.localdomain 2.4.12-alt1-mhz #1 thu oct 25 01:49:05 msd 2001 i686 unknown '
    config_args='-des -Darchname=i386-linux -Dd_dosuid -Ud_csh -Duseshrplib -Doptimize=-g -Dprefix=/home/mhz/devsite -Dprivlib=/home/mhz/devsite/lib/perl5 -Darchlib=/home/mhz/devsite/lib/perl5/i386-linux -Dlibperl=libperl.so.5 -Ui_db -Di_ndbm -Di_gdbm -Di_shadow -Di_syslog'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='cc', ccflags ='-DDEBUGGING -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-g',
    cppflags='-DDEBUGGING -fno-strict-aliasing'
    ccversion='', gccversion='2.96 20000731 (ALT Linux, build 2.96-ipl14mdk)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -ldl -lm -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lcrypt -lutil
    libc=/lib/libc-2.2.4.so, so=so, useshrplib=true, libperl=libperl.so.5
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic -Wl,-rpath,/home/mhz/devsite/lib/perl5/i386-linux/CORE'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.1:
    /home/mhz/devsite/lib/perl5/i386-linux
    /home/mhz/devsite/lib/perl5
    /home/mhz/devsite/lib/perl5/site_perl/5.6.1/i386-linux
    /home/mhz/devsite/lib/perl5/site_perl/5.6.1
    /home/mhz/devsite/lib/perl5/site_perl
    .


Environment for perl v5.6.1:
    HOME=/home/mhz
    LANG=ru_RU.KOI8-R
    LANGUAGE=ru_RU.KOI8-R
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/mhz/bin:/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin:/usr/games
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @schwern

This has been fixed in the development versions of Perl\.  Thanks for
the report\.


> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> 
> \{
> package test;
> 
> sub TIEHANDLER
> \{
>     my $class = shift;
>     my $scalar;
>     bless \\$scalar\, $class;
> \}
> 
> \}
> sub test
> \{
>     local \*FILE;
>     tie FILE\, 'test';
> \}
> test\(\)
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

\-\- 

Michael G\. Schwern   \<schwern@&#8203;pobox\.com>    http&#8203;://www\.pobox\.com/~schwern/
Perl6 Quality Assurance     \<perl\-qa@&#8203;perl\.org>         Kwalitee Is Job One
please remove your pants
we promise this won't hurt much
prepare for insertion
&nbsp;    \-\- Fmh

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]



Perl segfaults on the following script&#8203;:

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

\{
package test;

sub TIEHANDLER
\{
&nbsp;    my $class = shift;
&nbsp;    my $scalar;
&nbsp;    bless \\$scalar\, $class;
\}

\}
sub test
\{
&nbsp;    local \*FILE;
&nbsp;    tie FILE\, 'test';
\}
test\(\)

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-


Traceback&#8203;:

1228        if \(\!o || \(o\->op\_flags & OPf\_WANT\) || PL\_error\_count
\(gdb\) bt
\#0  0x400612ac in Perl\_list \(o=0x11\) at op\.c&#8203;:1228
\#1  0x40061273 in Perl\_listkids \(o=0x806cb00\) at op\.c&#8203;:1217
\#2  0x4006ebef in Perl\_ck\_fun \(o=0x806cb00\) at op\.c&#8203;:5668
\#3  0x4006491d in Perl\_convert \(type=197\, flags=0\, o=0x806cb00\) at op\.c&#8203;:2396
\#4  0x4005c857 in Perl\_yyparse \(\) at perly\.y&#8203;:420
\#5  0x4003382b in S\_parse\_body \(env=0x0\, xsinit=0x80495c0 \<xs\_init>\)
&nbsp;    at perl\.c&#8203;:1317
\#6  0x400329ce in perl\_parse \(my\_perl=0x804bec8\, xsinit=0x80495c0 \<xs\_init>\, 
&nbsp;    argc=2\, argv=0xbffff8f4\, env=0x0\) at perl\.c&#8203;:895
\#7  0x804956a in main \(argc=2\, argv=0xbffff8f4\, env=0xbffff900\)
&nbsp;    at perlmain\.c&#8203;:50

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.6.1:

Configured by mhz at Fri Nov  2 00:55:56 MSK 2001.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=linux, osvers=2.4.12-alt1-mhz, archname=i386-linux
    uname='linux localhost.localdomain 2.4.12-alt1-mhz #1 thu oct 25 01:49:05 msd 2001 i686 unknown '
    config_args='-des -Darchname=i386-linux -Dd_dosuid -Ud_csh -Duseshrplib -Doptimize=-g -Dprefix=/home/mhz/devsite -Dprivlib=/home/mhz/devsite/lib/perl5 -Darchlib=/home/mhz/devsite/lib/perl5/i386-linux -Dlibperl=libperl.so.5 -Ui_db -Di_ndbm -Di_gdbm -Di_shadow -Di_syslog'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='cc', ccflags ='-DDEBUGGING -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-g',
    cppflags='-DDEBUGGING -fno-strict-aliasing'
    ccversion='', gccversion='2.96 20000731 (ALT Linux, build 2.96-ipl14mdk)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -ldl -lm -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lcrypt -lutil
    libc=/lib/libc-2.2.4.so, so=so, useshrplib=true, libperl=libperl.so.5
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic -Wl,-rpath,/home/mhz/devsite/lib/perl5/i386-linux/CORE'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.1:
    /home/mhz/devsite/lib/perl5/i386-linux
    /home/mhz/devsite/lib/perl5
    /home/mhz/devsite/lib/perl5/site_perl/5.6.1/i386-linux
    /home/mhz/devsite/lib/perl5/site_perl/5.6.1
    /home/mhz/devsite/lib/perl5/site_perl
    .


Environment for perl v5.6.1:
    HOME=/home/mhz
    LANG=ru_RU.KOI8-R
    LANGUAGE=ru_RU.KOI8-R
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/mhz/bin:/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin:/usr/games
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Thu\, Nov 01\, 2001 at 08&#8203;:47&#8203;:34PM \-0500\, Michael G Schwern wrote&#8203;:
>
> On Fri\, Nov 02\, 2001 at 01&#8203;:43&#8203;:05AM \+0300\, Mikhail Zabaluev wrote&#8203;:
> > Perl segfaults on the following script&#8203;:
> 
> This has been fixed in the development versions of Perl\.  Thanks for
> the report\.

Any chance to get a patch for 5\.6\.1? I don't like that to occur in our
production packages\.

> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > 
> > \{
> > package test;
> > 
> > sub TIEHANDLER
> > \{
> >     my $class = shift;
> >     my $scalar;
> >     bless \\$scalar\, $class;
> > \}
> > 
> > \}
> > sub test
> > \{
> >     local \*FILE;
> >     tie FILE\, 'test';
> > \}
> > test\(\)
> > 
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

\-\- 
Stay tuned\,
&nbsp;  MhZ                                     JID&#8203;: mookid@&#8203;jabber\.org
\_\_\_\_\_\_\_\_\_\_\_
Two is company\, three is an orgy\.

**Comment by p5pRT** [comment]
### From @schwern

Hmm\, I don't know\.  Sarathy\, is there a maint patch for this?



> > > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > > 
> > > \{
> > > package test;
> > > 
> > > sub TIEHANDLER
> > > \{
> > >     my $class = shift;
> > >     my $scalar;
> > >     bless \\$scalar\, $class;
> > > \}
> > > 
> > > \}
> > > sub test
> > > \{
> > >     local \*FILE;
> > >     tie FILE\, 'test';
> > > \}
> > > test\(\)

\-\- 

Michael G\. Schwern   \<schwern@&#8203;pobox\.com>    http&#8203;://www\.pobox\.com/~schwern/
Perl6 Quality Assurance     \<perl\-qa@&#8203;perl\.org>         Kwalitee Is Job One
local $variable for local @&#8203;people;

**Comment by p5pRT** [comment]
### From @gsar

http&#8203;://public\.ActiveState\.com/gsar/APC/perl\-5\.6\.x\-diffs/9950\.gz


Sarathy
gsar@&#8203;ActiveState\.com
