### ISSUE TITLE
Seg fault at call_argv() when embedding under __threaded__ Perl 5.6.1

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4557]
Migrated from [rt.perl.org#7879](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=7879) (status was 'resolved')

Searchable as RT7879$

**Comment by p5pRT** [comment]
### From Stanley.Hopcroft@IPAustralia.gov.au



The example of a persistent embedded Perl interpreter in man perlembed
\(persistent\.c and persistent\.pl\) generats a seg fault at the call\_argv\(\)
call with a threaded Perl 5\.6\.1\.

The only change to the example is to add 'dTHX' early in main\(\) to get a
clean compile\.

> grep \-3 THX persistent\.c
&nbsp;        main\(int argc\, char \*\*argv\, char \*\*env\)
&nbsp;        \{

&nbsp;            dTHX;

&nbsp;            char \*embedding\[\] = \{ ""\, "persistent\.pl" \};
&nbsp;            char \*args\[\] = \{ ""\, DO\_CLEAN\, NULL \};
> 

A similar application \(my own hack\) works fine under

\.\. 5\.005\_03 
\.\. 5\.6\.1 built without thread support\.

but also fails at the same point with threaded Perl 5\.6\.1\.

> head persistent\.c
&nbsp;        /\* persistent\.c \*/
&nbsp;        \#include \<EXTERN\.h>
&nbsp;        \#include \<perl\.h>


&nbsp;        /\* 1 = clean out filename's symbol table after each request\, 0 = don't \*/
&nbsp;        \#ifndef DO\_CLEAN
&nbsp;        \#define DO\_CLEAN 0
&nbsp;        \#endif

> /opt/perl/bin/perl \-c persistent\.pl 
persistent\.pl syntax OK

> /opt/perl/bin/perl ap
In the beginning was the word and the word was with God

> gcc \-Wall \-g \-o persistent persistent\.c \`/opt/perl/bin/perl \-MExtUtils&#8203;::Embed \-e ccopts \-e ldopts\`
/tmp/ccLkH604\.o&#8203;: In function \`main'&#8203;:
/home/anwsmh/perl5\.6\.1/embed/netsaint/persistent\.c\(\.text\+0x105\)&#8203;: warning&#8203;: this program uses gets\(\)\, which is unsafe\.

> /opt/perl/bin/perl test\.pl 
foo says&#8203;: hello

> \./persistent 
warning&#8203;: this program uses gets\(\)\, which is unsafe\.
Enter file name&#8203;: test\.pl
Segmentation fault\(core dumped\)

> \./persistent 
warning&#8203;: this program uses gets\(\)\, which is unsafe\.
Enter file name&#8203;: ap
Segmentation fault\(core dumped\)

> gdb \-c persistent\.core persistent
GNU gdb 4\.18
Copyright 1998 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and you are
welcome to change it and/or distribute copies of it under certain conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for details\.
This GDB was configured as "i386\-unknown\-freebsd"\.\.\.
Core was generated by \`persistent'\.
Program terminated with signal 11\, Segmentation fault\.
Reading symbols from /usr/lib/libm\.so\.2\.\.\.done\.
Reading symbols from /usr/lib/libc\_r\.so\.4\.\.\.done\.
Reading symbols from /usr/lib/libcrypt\.so\.2\.\.\.done\.
Reading symbols from /usr/lib/libutil\.so\.3\.\.\.done\.
Reading symbols from /usr/libexec/ld\-elf\.so\.1\.\.\.done\.
\#0  0x805c5eb in Perl\_call\_argv \(\)
\(gdb\) r
Starting program&#8203;: /usr/home/anwsmh/perl5\.6\.1/embed/netsaint/persistent 
warning&#8203;: this program uses gets\(\)\, which is unsafe\.
Enter file name&#8203;: ap

Program received signal SIGSEGV\, Segmentation fault\.
0x805c5eb in Perl\_call\_argv \(\)
\(gdb\) bt
\#0  0x805c5eb in Perl\_call\_argv \(\)
\#1  0x805a0da in main \(argc=1\, argv=0xbfbffb8c\, env=0xbfbffb94\) at persistent\.c&#8203;:40
\#2  0x8059f15 in \_start \(\)
\(gdb\) Quit
\(gdb\) q
The program is running\. 

> /opt/perl/bin/perl \-ne 'print if \(35\.\.45\)' persistent\.c

&nbsp;               while\(printf\("Enter file name&#8203;: "\) && gets\(filename\)\) \{

&nbsp;                   /\* call the subroutine\, passing it the filename as an argument \*/
&nbsp;                   args\[0\] = filename;
&nbsp;                   call\_argv\("Embed&#8203;::Persistent&#8203;::eval\_file"\,
&nbsp;                                  G\_DISCARD | G\_EVAL\, args\);

&nbsp;                   /\* check $@&#8203; \*/
&nbsp;                   if\(SvTRUE\(ERRSV\)\)
&nbsp;                       fprintf\(stderr\, "eval error&#8203;: %s\\n"\, SvPV\(ERRSV\,n\_a\)\);
> 

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.6.1:

Configured by anwsmh at Sat Nov  3 20:58:13 EST 2001.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=freebsd, osvers=4.2-20010110-stable, archname=i386-freebsd-thread-multi
    uname='freebsd stan.aipo.gov.au 4.2-20010110-stable freebsd 4.2-20010110-stable #7: thu apr 5 18:33:44 est 2001 root@stan.aipo.gov.au:usrsrcsyscompilestan i386 '
    config_args='-Dprefix=/opt/perl -Dusethreads'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -I/usr/local/include',
    optimize='-O',
    cppflags='-fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='2.95.2 19991024 (release)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags ='-pthread -Wl,-E  -L/usr/local/lib'
    libpth=/usr/lib /usr/local/lib
    libs=-lgdbm -lm -lc_r -lcrypt -lutil
    perllibs=-lm -lc_r -lcrypt -lutil
    libc=, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags=' '
    cccdlflags='-DPIC -fpic', lddlflags='-shared  -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.1:
    /opt/perl/lib/5.6.1/i386-freebsd-thread-multi
    /opt/perl/lib/5.6.1
    /opt/perl/lib/site_perl/5.6.1/i386-freebsd-thread-multi
    /opt/perl/lib/site_perl/5.6.1
    /opt/perl/lib/site_perl
    .


Environment for perl v5.6.1:
    HOME=/home/anwsmh
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/bin:/usr/X11R6/bin:/home/anwsmh/bin
    PERL_BADLANG (unset)
    SHELL=/bin/tcsh

```
</details>
