### ISSUE TITLE
core is dumped in the depths of perl_destruct() in Perl 5.6.1

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4581]
Migrated from [rt.perl.org#7906](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=7906) (status was 'rejected')

Searchable as RT7906$

**Comment by p5pRT** [comment]
### From ccarey@vicinity.com




---
Hello there\,

I've encountered what seems to be a bug in an embedded Perl 5\.6\.1
within a C program\. There are three different core dump causes;
two of them happen while trying to finish perl\_destruct\(\)\, and
the third seems to be due just to memory corruption\. The
precondition is that an embedded Perl subroutine die\(\)s a certain
number of times \[which seems to vary by OS\, Perl version\, and
whether multiplicity is compiled in\]\, and each die\(\) is caught
because the G\_EVAL flag had been given to perl\_call\_pv\(\)\. What's
curious is that the G\_ARRAY flag is also a necessary precondition
for core to dump; core doesn't dump if the G\_SCALAR flag is used
instead of G\_ARRAY\. 

I have a test program called "death" that demonstrates
the problem\. It takes three arguments&#8203;: \-n number\, where number
is how many times the call to the embedded Perl subroutine should
be executed; \-a\, where G\_ARRAY is given to perl\_call\_pv\(\) rather
than G\_SCALAR; and \-s\, where certain signals are caught rather
than letting core dump\.

On Solaris 7\, with Perl 5\.6\.1 compiled with multiplicity\,
"death \-a \-n 10 \-s" reveals the following&#8203;:

&nbsp;    Divide&#8203;: dividend is zero at /home/ccarey/Perl\-5\.6\.1/Death\.pm line 27\.
&nbsp;    \.\.\.
&nbsp;    signal\_number&#8203;: 10
&nbsp;    si\->si\_signo&#8203;:  10
&nbsp;    si\->si\_errno&#8203;:  0
&nbsp;    si\->si\_code&#8203;:   BUS\_ADRALN
&nbsp;    si\->si\_addr&#8203;:   3d27675b

namely\, that SIGBUS is the cause of the core dump\. In this case\,
the si\->si\_addr value looks like an ASCII string in hexadecimal
format rather than a valid address\.

Similarly\, "death \-a \-n 147 \-s" on the same machine shows
a second cause&#8203;:

&nbsp;    Divide&#8203;: dividend is zero at /home/ccarey/Perl\-5\.6\.1/Death\.pm line 27\.
&nbsp;    \.\.\.
&nbsp;    signal\_number&#8203;: 11
&nbsp;    si\->si\_signo&#8203;:  11
&nbsp;    si\->si\_errno&#8203;:  0
&nbsp;    si\->si\_code&#8203;:   SEGV\_MAPERR
&nbsp;    si\->si\_addr&#8203;:   8d3f48

that in this case\, SIGSEGV causes core to dump\. Additionally\,
"death \-a \-n 574 \-s" on the same machine shows another case&#8203;:

&nbsp;    Divide&#8203;: dividend is zero at /home/ccarey/Perl\-5\.6\.1/Death\.pm line 27\.
&nbsp;    \.\.\.
&nbsp;    Can't use an undefined value as an ARRAY reference at /home/ccarey/Perl\-5\.6\.1/Death\.pm line 26\.
&nbsp;    Can't use string \("0"\) as an ARRAY ref while "strict refs" in use at /home/ccarey/Perl\-5\.6\.1/Death\.pm line 26\.
&nbsp;    Can't use string \("$$"\) as an ARRAY ref while "strict refs" in use at /home/ccarey/Perl\-5\.6\.1/Death\.pm line 26\.
&nbsp;    Can't use string \("$$"\) as an ARRAY ref while "strict refs" in use at /home/ccarey/Perl\-5\.6\.1/Death\.pm line 26\.
&nbsp;    signal\_number&#8203;: 4
&nbsp;    si\->si\_signo&#8203;:  4
&nbsp;    si\->si\_errno&#8203;:  0
&nbsp;    si\->si\_code&#8203;:   ILL\_ILLOPC
&nbsp;    si\->si\_addr&#8203;:   1cfc10

This SIGILL condition is the most intriguing\, since the four
warnings that begin with "Can't" don't appear in the other cases;
presumably this is due to memory corruption of some sort\.

When run without the "\-s" argument\, each of "\-n 10"\, "\-n 147"\,
and "\-n 574" dump core\. The SIGBUS core dump reveals the following
in gdb&#8203;:

&nbsp;    \(amber&#8203;:281\) gdb death core\.multiplicity\.010
&nbsp;    GNU gdb 4\.18
&nbsp;    \.\.\.
&nbsp;    Reading symbols from /usr/lib/locale/iso\_8859\_1/iso\_8859\_1\.so\.2\.\.\.done\.
&nbsp;    \#0  0xff1c6424 in \_free\_unlocked \(\) from /usr/lib/libc\.so\.1
&nbsp;    \(gdb\) where
&nbsp;    \#0  0xff1c6424 in \_free\_unlocked \(\) from /usr/lib/libc\.so\.1
&nbsp;    \#1  0xff1c63dc in free \(\) from /usr/lib/libc\.so\.1
&nbsp;    \#2  0x9e198 in Perl\_safesysfree \(where=0x72633d31\) at util\.c&#8203;:158
&nbsp;    \#3  0xa8db0 in Perl\_mg\_free \(my\_perl=0x195be8\, sv=0x1ad86c\) at mg\.c&#8203;:316
&nbsp;    \#4  0xda42c in Perl\_sv\_clear \(my\_perl=0x195be8\, sv=0x1ad86c\) at sv\.c&#8203;:3770
&nbsp;    \#5  0xdad88 in Perl\_sv\_free \(my\_perl=0x195be8\, sv=0x1ad86c\) at sv\.c&#8203;:3950
&nbsp;    \#6  0xb8560 in Perl\_av\_undef \(my\_perl=0x195be8\, av=0x1a0ad8\) at av\.c&#8203;:447
&nbsp;    \#7  0xda5d4 in Perl\_sv\_clear \(my\_perl=0x195be8\, sv=0x1a0ad8\) at sv\.c&#8203;:3798
&nbsp;    \#8  0xdad88 in Perl\_sv\_free \(my\_perl=0x195be8\, sv=0x1a0ad8\) at sv\.c&#8203;:3950
&nbsp;    \#9  0x75e00 in Perl\_cv\_undef \(my\_perl=0x195be8\, cv=0x1a0acc\) at op\.c&#8203;:4157
&nbsp;    \#10 0xda5a4 in Perl\_sv\_clear \(my\_perl=0x195be8\, sv=0x1a0acc\) at sv\.c&#8203;:3792
&nbsp;    \#11 0xdad88 in Perl\_sv\_free \(my\_perl=0x195be8\, sv=0x1a0acc\) at sv\.c&#8203;:3950
&nbsp;    \#12 0x75cbc in Perl\_cv\_undef \(my\_perl=0x195be8\, cv=0x1c8d8c\) at op\.c&#8203;:4140
&nbsp;    \#13 0xda5a4 in Perl\_sv\_clear \(my\_perl=0x195be8\, sv=0x1c8d8c\) at sv\.c&#8203;:3792
&nbsp;    \#14 0xdad88 in Perl\_sv\_free \(my\_perl=0x195be8\, sv=0x1c8d8c\) at sv\.c&#8203;:3950
&nbsp;    \#15 0x33884 in Perl\_gp\_free \(my\_perl=0x195be8\, gv=0x1a63ac\) at gv\.c&#8203;:1111
&nbsp;    \#16 0xda60c in Perl\_sv\_clear \(my\_perl=0x195be8\, sv=0x1a63ac\) at sv\.c&#8203;:3804
&nbsp;    \#17 0xdad88 in Perl\_sv\_free \(my\_perl=0x195be8\, sv=0x1a63ac\) at sv\.c&#8203;:3950
&nbsp;    \#18 0xe4ef8 in do\_clean\_all \(my\_perl=0x195be8\, sv=0x1a63ac\) at sv\.c&#8203;:8411
&nbsp;    \#19 0xcc5b4 in S\_visit \(my\_perl=0x195be8\, f=0xe4e8c \<do\_clean\_all>\) at sv\.c&#8203;:162
&nbsp;    \#20 0xcc698 in Perl\_sv\_clean\_all \(my\_perl=0x195be8\) at sv\.c&#8203;:193
&nbsp;    \#21 0x24e40 in perl\_destruct \(my\_perl=0x195be8\) at perl\.c&#8203;:665
&nbsp;    \#22 0x23b98 in destroy\_Perl\_interpreter \(perl\_interpreter=0x195be8\) at death\.c&#8203;:151
&nbsp;    \#23 0x22f10 in postmain \(argc=4\, argv=0xffbef72c\, wanting\_array=1\, iterations=\-1\) at main\.c&#8203;:288
&nbsp;    \#24 0x23244 in main \(argc=4\, argv=0xffbef72c\) at main\.c&#8203;:383
&nbsp;    \(gdb\) frame 3
&nbsp;    \#3  0xa8db0 in Perl\_mg\_free \(my\_perl=0x195be8\, sv=0x1ad86c\) at mg\.c&#8203;:316
&nbsp;    316                     Safefree\(mg\->mg\_ptr\);
&nbsp;    \(gdb\) print mg
&nbsp;    $1 = \(MAGIC \*\) 0x1c1a54
&nbsp;    \(gdb\) print \*mg
&nbsp;    $2 = \{mg\_moremagic = 0x1c1a48\, mg\_virtual = 0x0\, mg\_private = 0\, mg\_type = 0 '\\000'\, mg\_flags = 255 'ÿ'\, mg\_obj = 0xa01\, mg\_ptr = 0x72633d31 \<Address 0x72633d31 out of bounds>\, mg\_len = 32\}
&nbsp;    \(gdb\) \_

whereas the SIGSEGV core dump unveils the following&#8203;:

&nbsp;    \(amber&#8203;:282\) gdb death core\.multiplicity\.147
&nbsp;    GNU gdb 4\.18
&nbsp;    \.\.\.
&nbsp;    Reading symbols from /usr/lib/locale/iso\_8859\_1/iso\_8859\_1\.so\.2\.\.\.done\.
&nbsp;    \#0  0xb77d0 in Perl\_av\_fetch \(my\_perl=0x195be8\, av=0x1968c4\, key=1899656\, lval=0\) at av\.c&#8203;:202
&nbsp;    202         if \(AvARRAY\(av\)\[key\] == &PL\_sv\_undef\) \{
&nbsp;    \(gdb\) where
&nbsp;    \#0  0xb77d0 in Perl\_av\_fetch \(my\_perl=0x195be8\, av=0x1968c4\, key=1899656\, lval=0\) at av\.c&#8203;:202
&nbsp;    \#1  0x75d5c in Perl\_cv\_undef \(my\_perl=0x195be8\, cv=0x1968a0\) at op\.c&#8203;:4147
&nbsp;    \#2  0xda5a4 in Perl\_sv\_clear \(my\_perl=0x195be8\, sv=0x1968a0\) at sv\.c&#8203;:3792
&nbsp;    \#3  0xdad88 in Perl\_sv\_free \(my\_perl=0x195be8\, sv=0x1968a0\) at sv\.c&#8203;:3950
&nbsp;    \#4  0x24394 in perl\_destruct \(my\_perl=0x195be8\) at perl\.c&#8203;:407
&nbsp;    \#5  0x23b98 in destroy\_Perl\_interpreter \(perl\_interpreter=0x195be8\) at death\.c&#8203;:151
&nbsp;    \#6  0x22f10 in postmain \(argc=4\, argv=0xffbef72c\, wanting\_array=1\, iterations=\-1\) at main\.c&#8203;:288
&nbsp;    \#7  0x23244 in main \(argc=4\, argv=0xffbef72c\) at main\.c&#8203;:383
&nbsp;    \(gdb\) print av\->sv\_any\->xav\_array
&nbsp;    $1 = 0x194e18 ""
&nbsp;    \(gdb\) print key
&nbsp;    $2 = 1899656
&nbsp;    \(gdb\) \_

and the SIGILL core dump shows this&#8203;:

&nbsp;    \(amber&#8203;:283\) gdb death core\.multiplicity\.574
&nbsp;    GNU gdb 4\.18
&nbsp;    \.\.\.
&nbsp;    Reading symbols from /usr/lib/locale/iso\_8859\_1/iso\_8859\_1\.so\.2\.\.\.done\.
&nbsp;    \#0  0x1cfc4c in ?? \(\)
&nbsp;    \(gdb\) where
&nbsp;    \#0  0x1cfc4c in ?? \(\)
&nbsp;    \#1  0x28c98 in S\_call\_body \(my\_perl=0x195be8\, myop=0xffbef338\, is\_eval=0\) at perl\.c&#8203;:1824
&nbsp;    \#2  0x28744 in Perl\_call\_sv \(my\_perl=0x195be8\, sv=0x1cfc04\, flags=5\) at perl\.c&#8203;:1742
&nbsp;    \#3  0x27e30 in Perl\_call\_pv \(my\_perl=0x195be8\, sub\_name=0x16abc0 "Divide"\, flags=5\) at perl\.c&#8203;:1619
&nbsp;    \#4  0x2368c in Death\_Divide \(error\_message=0xffbef500 ""\, perl\_interpreter=0x195be8\, wanting\_array=1\, divisor=1\, dividend=0\) at death\.c&#8203;:101
&nbsp;    \#5  0x22e6c in postmain \(argc=4\, argv=0xffbef72c\, wanting\_array=1\, iterations=0\) at main\.c&#8203;:273
&nbsp;    \#6  0x23244 in main \(argc=4\, argv=0xffbef72c\) at main\.c&#8203;:383
&nbsp;    \(gdb\) frame 1
&nbsp;    \#1  0x28c98 in S\_call\_body \(my\_perl=0x195be8\, myop=0xffbef338\, is\_eval=0\) at perl\.c&#8203;:1824
&nbsp;    1824            CALLRUNOPS\(aTHX\);
&nbsp;    \(gdb\) \_

I have no experience with the perlguts\, so I'm not in a position
to easily suss out the reasons behind these core dumps\. Kindly
send a note to me at \<ccarey@&#8203;capaccess\.org> if you'd like a copy
of the "death" program; it's reasonably compact\, fairly portable\,
and it currently compiles on Solaris 7 and Linux 2\.0\.36 \[although
siginfo\(5\) information won't be provided if it's not available
in the OS\]\. As an aside\, only SIGSEGV occurs on Linux 2\.0\.36
with a debugging Perl 5\.6\.1 with multiplicity\, and the SIGSEGV
requires "\-n 3" or higher\.

Thanks for your attention\,

Christian Carey \<ccarey@&#8203;vicinity\.com>




---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=low


---
Site configuration information for perl v5\.6\.1&#8203;:

Configured by ccarey at Mon Nov 12 13&#8203;:50&#8203;:33 EST 2001\.

Summary of my perl5 \(revision 5\.0 version 6 subversion 1\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=solaris\, osvers=2\.7\, archname=sun4\-solaris\-multi
&nbsp;    uname='sunos amber 5\.7 generic\_106541\-12 sun4u sparc sunw\,ultra\-60 '
&nbsp;    config\_args='\-Dcc=gcc \-Dusemultiplicity \-Uusemymalloc \-Dprefix=/var/tmp/ccarey \-Doptimize=\-ggdb3 \-de'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=define
&nbsp;    useperlio=undef d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'\, ccflags ='\-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-ggdb3'\,
&nbsp;    cppflags='\-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='2\.95\.2 19991024 \(release\)'\, gccosandvers='solaris2\.7'
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=4321
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, usemymalloc=n\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='gcc'\, ldflags =' \-L/usr/local/lib '
&nbsp;    libpth=/usr/local/lib /usr/lib /usr/ccs/lib
&nbsp;    libs=\-lsocket \-lnsl \-lgdbm \-ldl \-lm \-lc
&nbsp;    perllibs=\-lsocket \-lnsl \-ldl \-lm \-lc
&nbsp;    libc=/lib/libc\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-G \-L/usr/local/lib'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl v5\.6\.1&#8203;:
&nbsp;    /var/tmp/ccarey/lib/perl5/5\.6\.1/sun4\-solaris\-multi
&nbsp;    /var/tmp/ccarey/lib/perl5/5\.6\.1
&nbsp;    /var/tmp/ccarey/lib/perl5/site\_perl/5\.6\.1/sun4\-solaris\-multi
&nbsp;    /var/tmp/ccarey/lib/perl5/site\_perl/5\.6\.1
&nbsp;    /var/tmp/ccarey/lib/perl5/site\_perl
&nbsp;    \.



---
Environment for perl v5\.6\.1&#8203;:
&nbsp;    HOME=/home/ccarey
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LC\_CTYPE=iso\_8859\_1
&nbsp;    LD\_LIBRARY\_PATH=/home/ccarey/lib&#8203;:/usr/local/lib&#8203;:/u0000/app/oracle/product/8\.1\.7/lib&#8203;:/usr/openwin/lib&#8203;:/usr/lib&#8203;:\.
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/ccarey/bin&#8203;:/usr/local/sbin&#8203;:/var/tmp/ccarey/bin&#8203;:/usr/local/bin&#8203;:/u0000/app/oracle/product/8\.1\.7/bin&#8203;:/usr/dt/bin&#8203;:/usr/openwin/bin&#8203;:/usr/sbin&#8203;:/usr/proc/bin&#8203;:/usr/ccs/bin&#8203;:/usr/xpg4/bin&#8203;:/usr/bin&#8203;:/usr/ucb&#8203;:\.
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/ksh

**Comment by p5pRT** [comment]
### From @Hugmeir

On Tue Nov 13 06&#8203;:39&#8203;:48 2001\, ccarey@&#8203;vicinity\.com wrote&#8203;:
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> 
> 
> Hello there\,
> 
> I've encountered what seems to be a bug in an embedded Perl 5\.6\.1
> within a C program\. There are three different core dump causes;
> two of them happen while trying to finish perl\_destruct\(\)\, and
> the third seems to be due just to memory corruption\. The
> precondition is that an embedded Perl subroutine die\(\)s a certain
> number of times \[which seems to vary by OS\, Perl version\, and
> whether multiplicity is compiled in\]\, and each die\(\) is caught
> because the G\_EVAL flag had been given to perl\_call\_pv\(\)\. What's
> curious is that the G\_ARRAY flag is also a necessary precondition
> for core to dump; core doesn't dump if the G\_SCALAR flag is used
> instead of G\_ARRAY\.
> 
> I have a test program called "death" that demonstrates
> the problem\. It takes three arguments&#8203;: \-n number\, where number
> is how many times the call to the embedded Perl subroutine should
> be executed; \-a\, where G\_ARRAY is given to perl\_call\_pv\(\) rather
> than G\_SCALAR; and \-s\, where certain signals are caught rather
> than letting core dump\.
> 
> On Solaris 7\, with Perl 5\.6\.1 compiled with multiplicity\,
> "death \-a \-n 10 \-s" reveals the following&#8203;:
> 
>     Divide&#8203;: dividend is zero at /home/ccarey/Perl\-5\.6\.1/Death\.pm line 27\.
>     \.\.\.
>     signal\_number&#8203;: 10
>     si\->si\_signo&#8203;:  10
>     si\->si\_errno&#8203;:  0
>     si\->si\_code&#8203;:   BUS\_ADRALN
>     si\->si\_addr&#8203;:   3d27675b
> 
> namely\, that SIGBUS is the cause of the core dump\. In this case\,
> the si\->si\_addr value looks like an ASCII string in hexadecimal
> format rather than a valid address\.
> 
> Similarly\, "death \-a \-n 147 \-s" on the same machine shows
> a second cause&#8203;:
> 
>     Divide&#8203;: dividend is zero at /home/ccarey/Perl\-5\.6\.1/Death\.pm line 27\.
>     \.\.\.
>     signal\_number&#8203;: 11
>     si\->si\_signo&#8203;:  11
>     si\->si\_errno&#8203;:  0
>     si\->si\_code&#8203;:   SEGV\_MAPERR
>     si\->si\_addr&#8203;:   8d3f48
> 
> that in this case\, SIGSEGV causes core to dump\. Additionally\,
> "death \-a \-n 574 \-s" on the same machine shows another case&#8203;:
> 
>     Divide&#8203;: dividend is zero at /home/ccarey/Perl\-5\.6\.1/Death\.pm line 27\.
>     \.\.\.
>     Can't use an undefined value as an ARRAY reference at
>    /home/ccarey/Perl\-5\.6\.1/Death\.pm line 26\.
>     Can't use string \("0"\) as an ARRAY ref while "strict refs" in use at
>    /home/ccarey/Perl\-5\.6\.1/Death\.pm line 26\.
>     Can't use string \("$$"\) as an ARRAY ref while "strict refs" in use at
>    /home/ccarey/Perl\-5\.6\.1/Death\.pm line 26\.
>     Can't use string \("$$"\) as an ARRAY ref while "strict refs" in use at
>    /home/ccarey/Perl\-5\.6\.1/Death\.pm line 26\.
>     signal\_number&#8203;: 4
>     si\->si\_signo&#8203;:  4
>     si\->si\_errno&#8203;:  0
>     si\->si\_code&#8203;:   ILL\_ILLOPC
>     si\->si\_addr&#8203;:   1cfc10
> 
> This SIGILL condition is the most intriguing\, since the four
> warnings that begin with "Can't" don't appear in the other cases;
> presumably this is due to memory corruption of some sort\.
> 
> When run without the "\-s" argument\, each of "\-n 10"\, "\-n 147"\,
> and "\-n 574" dump core\. The SIGBUS core dump reveals the following
> in gdb&#8203;:
> 
>     \(amber&#8203;:281\) gdb death core\.multiplicity\.010
>     GNU gdb 4\.18
>     \.\.\.
>     Reading symbols from
>    /usr/lib/locale/iso\_8859\_1/iso\_8859\_1\.so\.2\.\.\.done\.
>     \#0  0xff1c6424 in \_free\_unlocked \(\) from /usr/lib/libc\.so\.1
>     \(gdb\) where
>     \#0  0xff1c6424 in \_free\_unlocked \(\) from /usr/lib/libc\.so\.1
>     \#1  0xff1c63dc in free \(\) from /usr/lib/libc\.so\.1
>     \#2  0x9e198 in Perl\_safesysfree \(where=0x72633d31\) at util\.c&#8203;:158
>     \#3  0xa8db0 in Perl\_mg\_free \(my\_perl=0x195be8\, sv=0x1ad86c\) at
>    mg\.c&#8203;:316
>     \#4  0xda42c in Perl\_sv\_clear \(my\_perl=0x195be8\, sv=0x1ad86c\) at
>    sv\.c&#8203;:3770
>     \#5  0xdad88 in Perl\_sv\_free \(my\_perl=0x195be8\, sv=0x1ad86c\) at
>    sv\.c&#8203;:3950
>     \#6  0xb8560 in Perl\_av\_undef \(my\_perl=0x195be8\, av=0x1a0ad8\) at
>    av\.c&#8203;:447
>     \#7  0xda5d4 in Perl\_sv\_clear \(my\_perl=0x195be8\, sv=0x1a0ad8\) at
>    sv\.c&#8203;:3798
>     \#8  0xdad88 in Perl\_sv\_free \(my\_perl=0x195be8\, sv=0x1a0ad8\) at
>    sv\.c&#8203;:3950
>     \#9  0x75e00 in Perl\_cv\_undef \(my\_perl=0x195be8\, cv=0x1a0acc\) at
>    op\.c&#8203;:4157
>     \#10 0xda5a4 in Perl\_sv\_clear \(my\_perl=0x195be8\, sv=0x1a0acc\) at
>    sv\.c&#8203;:3792
>     \#11 0xdad88 in Perl\_sv\_free \(my\_perl=0x195be8\, sv=0x1a0acc\) at
>    sv\.c&#8203;:3950
>     \#12 0x75cbc in Perl\_cv\_undef \(my\_perl=0x195be8\, cv=0x1c8d8c\) at
>    op\.c&#8203;:4140
>     \#13 0xda5a4 in Perl\_sv\_clear \(my\_perl=0x195be8\, sv=0x1c8d8c\) at
>    sv\.c&#8203;:3792
>     \#14 0xdad88 in Perl\_sv\_free \(my\_perl=0x195be8\, sv=0x1c8d8c\) at
>    sv\.c&#8203;:3950
>     \#15 0x33884 in Perl\_gp\_free \(my\_perl=0x195be8\, gv=0x1a63ac\) at
>    gv\.c&#8203;:1111
>     \#16 0xda60c in Perl\_sv\_clear \(my\_perl=0x195be8\, sv=0x1a63ac\) at
>    sv\.c&#8203;:3804
>     \#17 0xdad88 in Perl\_sv\_free \(my\_perl=0x195be8\, sv=0x1a63ac\) at
>    sv\.c&#8203;:3950
>     \#18 0xe4ef8 in do\_clean\_all \(my\_perl=0x195be8\, sv=0x1a63ac\) at
>    sv\.c&#8203;:8411
>     \#19 0xcc5b4 in S\_visit \(my\_perl=0x195be8\, f=0xe4e8c \<do\_clean\_all>\)
>    at sv\.c&#8203;:162
>     \#20 0xcc698 in Perl\_sv\_clean\_all \(my\_perl=0x195be8\) at sv\.c&#8203;:193
>     \#21 0x24e40 in perl\_destruct \(my\_perl=0x195be8\) at perl\.c&#8203;:665
>     \#22 0x23b98 in destroy\_Perl\_interpreter \(perl\_interpreter=0x195be8\)
>    at death\.c&#8203;:151
>     \#23 0x22f10 in postmain \(argc=4\, argv=0xffbef72c\, wanting\_array=1\,
>    iterations=\-1\) at main\.c&#8203;:288
>     \#24 0x23244 in main \(argc=4\, argv=0xffbef72c\) at main\.c&#8203;:383
>     \(gdb\) frame 3
>     \#3  0xa8db0 in Perl\_mg\_free \(my\_perl=0x195be8\, sv=0x1ad86c\) at
>    mg\.c&#8203;:316
>     316                     Safefree\(mg\->mg\_ptr\);
>     \(gdb\) print mg
>     $1 = \(MAGIC \*\) 0x1c1a54
>     \(gdb\) print \*mg
>     $2 = \{mg\_moremagic = 0x1c1a48\, mg\_virtual = 0x0\, mg\_private = 0\,
>    mg\_type = 0 '\\000'\, mg\_flags = 255 '�'\, mg\_obj = 0xa01\, mg\_ptr =
>    0x72633d31 \<Address 0x72633d31 out of bounds>\, mg\_len = 32\}
>     \(gdb\) \_
> 
> whereas the SIGSEGV core dump unveils the following&#8203;:
> 
>     \(amber&#8203;:282\) gdb death core\.multiplicity\.147
>     GNU gdb 4\.18
>     \.\.\.
>     Reading symbols from
>    /usr/lib/locale/iso\_8859\_1/iso\_8859\_1\.so\.2\.\.\.done\.
>     \#0  0xb77d0 in Perl\_av\_fetch \(my\_perl=0x195be8\, av=0x1968c4\,
>    key=1899656\, lval=0\) at av\.c&#8203;:202
>     202         if \(AvARRAY\(av\)\[key\] == &PL\_sv\_undef\) \{
>     \(gdb\) where
>     \#0  0xb77d0 in Perl\_av\_fetch \(my\_perl=0x195be8\, av=0x1968c4\,
>    key=1899656\, lval=0\) at av\.c&#8203;:202
>     \#1  0x75d5c in Perl\_cv\_undef \(my\_perl=0x195be8\, cv=0x1968a0\) at
>    op\.c&#8203;:4147
>     \#2  0xda5a4 in Perl\_sv\_clear \(my\_perl=0x195be8\, sv=0x1968a0\) at
>    sv\.c&#8203;:3792
>     \#3  0xdad88 in Perl\_sv\_free \(my\_perl=0x195be8\, sv=0x1968a0\) at
>    sv\.c&#8203;:3950
>     \#4  0x24394 in perl\_destruct \(my\_perl=0x195be8\) at perl\.c&#8203;:407
>     \#5  0x23b98 in destroy\_Perl\_interpreter \(perl\_interpreter=0x195be8\)
>    at death\.c&#8203;:151
>     \#6  0x22f10 in postmain \(argc=4\, argv=0xffbef72c\, wanting\_array=1\,
>    iterations=\-1\) at main\.c&#8203;:288
>     \#7  0x23244 in main \(argc=4\, argv=0xffbef72c\) at main\.c&#8203;:383
>     \(gdb\) print av\->sv\_any\->xav\_array
>     $1 = 0x194e18 ""
>     \(gdb\) print key
>     $2 = 1899656
>     \(gdb\) \_
> 
> and the SIGILL core dump shows this&#8203;:
> 
>     \(amber&#8203;:283\) gdb death core\.multiplicity\.574
>     GNU gdb 4\.18
>     \.\.\.
>     Reading symbols from
>    /usr/lib/locale/iso\_8859\_1/iso\_8859\_1\.so\.2\.\.\.done\.
>     \#0  0x1cfc4c in ?? \(\)
>     \(gdb\) where
>     \#0  0x1cfc4c in ?? \(\)
>     \#1  0x28c98 in S\_call\_body \(my\_perl=0x195be8\, myop=0xffbef338\,
>    is\_eval=0\) at perl\.c&#8203;:1824
>     \#2  0x28744 in Perl\_call\_sv \(my\_perl=0x195be8\, sv=0x1cfc04\, flags=5\)
>    at perl\.c&#8203;:1742
>     \#3  0x27e30 in Perl\_call\_pv \(my\_perl=0x195be8\, sub\_name=0x16abc0
>    "Divide"\, flags=5\) at perl\.c&#8203;:1619
>     \#4  0x2368c in Death\_Divide \(error\_message=0xffbef500 ""\,
>    perl\_interpreter=0x195be8\, wanting\_array=1\, divisor=1\, dividend=0\)
>    at death\.c&#8203;:101
>     \#5  0x22e6c in postmain \(argc=4\, argv=0xffbef72c\, wanting\_array=1\,
>    iterations=0\) at main\.c&#8203;:273
>     \#6  0x23244 in main \(argc=4\, argv=0xffbef72c\) at main\.c&#8203;:383
>     \(gdb\) frame 1
>     \#1  0x28c98 in S\_call\_body \(my\_perl=0x195be8\, myop=0xffbef338\,
>    is\_eval=0\) at perl\.c&#8203;:1824
>     1824            CALLRUNOPS\(aTHX\);
>     \(gdb\) \_
> 
> I have no experience with the perlguts\, so I'm not in a position
> to easily suss out the reasons behind these core dumps\. Kindly
> send a note to me at \<ccarey@&#8203;capaccess\.org> if you'd like a copy
> of the "death" program; it's reasonably compact\, fairly portable\,
> and it currently compiles on Solaris 7 and Linux 2\.0\.36 \[although
> siginfo\(5\) information won't be provided if it's not available
> in the OS\]\. As an aside\, only SIGSEGV occurs on Linux 2\.0\.36
> with a debugging Perl 5\.6\.1 with multiplicity\, and the SIGSEGV
> requires "\-n 3" or higher\.
> 
> Thanks for your attention\,
> 
> Christian Carey \<ccarey@&#8203;vicinity\.com>
> 
> 

This report fell through the cracks; OP\, if you're still around\, are you
still having this issue with recent versions of Perl? If so\, could you
send a way to reproduce it?

Seeing how this ticket has been silent for over a decade\, I recommend
waiting another thirty days\, then closing it if we don't get new
information or other complains\.

\-\-hugmeir

**Comment by p5pRT** [comment]
### From @jkeenan

On Fri May 25 14&#8203;:25&#8203;:01 2012\, Hugmeir wrote&#8203;:
> On Tue Nov 13 06&#8203;:39&#8203;:48 2001\, ccarey@&#8203;vicinity\.com wrote&#8203;:
> > 
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > 
> > 
> > Hello there\,
> > 
> > I've encountered what seems to be a bug in an embedded Perl 5\.6\.1
> > within a C program\. 

\[snip\]
> > 
> 
> This report fell through the cracks; OP\, if you're still around\, are you
> still having this issue with recent versions of Perl? If so\, could you
> send a way to reproduce it?
> 
> Seeing how this ticket has been silent for over a decade\, I recommend
> waiting another thirty days\, then closing it if we don't get new
> information or other complains\.
> 
> \-\-hugmeir

Closing as per recommendation from hugmeir\.

**Comment by p5pRT** [comment]
@jkeenan - Status changed from 'open' to 'rejected'
