### ISSUE TITLE
[Solaris] perl segfaults

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4645]
Migrated from [rt.perl.org#7985](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=7985) (status was 'resolved')

Searchable as RT7985$

**Comment by p5pRT** [comment]
### From dvanbalen@jam.rr.com

when running the following script on a file which I'm trying to convert
from what I think is EBCDIC to ascii\, I got a segfault \(I had previously
run the file through dd \<options> conv=ascii before running it through
the perl script\)\.

\#\! /usr/bin/perl \-w

open\(FILE\, "\<$ARGV\[0\]"\);

\{
&nbsp;    local $/;
&nbsp;    $foo=\<FILE>;
\}

$foo=~s/\\C//;
$foo=~s/\\X//;

print "$foo";

The segfault only appears to occur when both the /C and /X regexps are
present\, regardless of which order I put them in\.

I'm not sure if my script is having any effect or if there're actually
any "eXtended unicode" or "sigle C char \(octet\)" present in the file\.
I'm just taking a stab in the dark with that script and I believe my
real problem is the "cbs=" value I'm giving dd\. However\, it would seem
that perl shouldn't segfault no matter how stupidly moronic a thing
I'm doing :\-\)
Here's my gdb output&#8203;:

$ gdb perl core
GNU gdb 5\.0
Copyright 2000 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and
you are
welcome to change it and/or distribute copies of it under certain
conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for
details\.
This GDB was configured as "sparc\-sun\-solaris2\.5\.1"\.\.\.\(no debugging
symbols found\)\.\.\.
Core was generated by \`perl \-w convert\.pl foofile\.out'\.
Program terminated with signal 11\, Segmentation Fault\.
Reading symbols from /usr/lib/libsocket\.so\.1\.\.\.\(no debugging symbols
found\)\.\.\.done\.
Loaded symbols for /usr/lib/libsocket\.so\.1
Reading symbols from /usr/lib/libnsl\.so\.1\.\.\.\(no debugging symbols
found\)\.\.\.done\.
Loaded symbols for /usr/lib/libnsl\.so\.1
Reading symbols from /usr/lib/libdl\.so\.1\.\.\.\(no debugging symbols
found\)\.\.\.done\.
Loaded symbols for /usr/lib/libdl\.so\.1
Reading symbols from /usr/lib/libc\.so\.1\.\.\.\(no debugging symbols
found\)\.\.\.done\.
Loaded symbols for /usr/lib/libc\.so\.1
Reading symbols from /usr/lib/libmp\.so\.2\.\.\.\(no debugging symbols
found\)\.\.\.done\.
Loaded symbols for /usr/lib/libmp\.so\.2
Reading symbols from
/usr/platform/SUNW\,Ultra\-Enterprise/lib/libc\_psr\.so\.1\.\.\.\(no debugging
symbols found\)\.\.\.
done\.
Loaded symbols for /usr/platform/SUNW\,Ultra\-Enterprise/lib/libc\_psr\.so\.1
Reading symbols from
/usr/lib/locale/en\_US\.ISO8859\-15/en\_US\.ISO8859\-15\.so\.2\.\.\.\(no debugging
symbols found\)\.\.\.
done\.
Loaded symbols for /usr/lib/locale/en\_US\.ISO8859\-15/en\_US\.ISO8859\-15\.so\.2
\#0  0xdf324 in Perl\_swash\_fetch \(\)
\(gdb\) bt
\#0  0xdf324 in Perl\_swash\_fetch \(\)
\#1  0xd901c in S\_regmatch \(\)
\#2  0xd7704 in S\_regtry \(\)
\#3  0xd6d88 in Perl\_regexec\_flags \(\)
\#4  0x82470 in Perl\_pp\_subst \(\)
\#5  0x7bfc8 in Perl\_runops\_standard \(\)
\#6  0x24f2c in S\_run\_body \(\)
\#7  0x24be8 in perl\_run \(\)
\#8  0x2190c in main \(\)
\(gdb\) quit


and here's my perl \-V&#8203;:

$ perl \-V
Summary of my perl5 \(revision 5\.0 version 6 subversion 1\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=solaris\, osvers=2\.8\, archname=sun4\-solaris
&nbsp;    uname='sunos exodus 5\.8 generic\_108528\-10 sun4u sparc sunw\,ultra\-enterprise       
'
&nbsp;    config\_args='\-de'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=unde      
f
&nbsp;    useperlio=undef d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags =' \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O'\,
&nbsp;    cppflags=''
&nbsp;    ccversion='WorkShop Compilers 5\.0 98/12/15 C 5\.0'\, gccversion=''\, gccosandve      
rs=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=4321
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize      
=8
&nbsp;    alignbytes=8\, usemymalloc=y\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/opt/SUNWspro/SC5\.0/lib '
&nbsp;    libpth=/opt/SUNWspro/SC5\.0/lib /usr/lib /usr/ccs/lib
&nbsp;    libs=\-lsocket \-lnsl \-ldl \-lm \-lc
&nbsp;    perllibs=\-lsocket \-lnsl \-ldl \-lm \-lc
&nbsp;    libc=/lib/libc\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags='\-KPIC'\, lddlflags='\-G \-L/opt/SUNWspro/SC5\.0/lib'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: USE\_LARGE\_FILES
&nbsp;  Built under solaris
&nbsp;  Compiled at Sep 27 2001 21&#8203;:42&#8203;:51
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/lib/perl5/5\.6\.1/sun4\-solaris
&nbsp;    /usr/local/lib/perl5/5\.6\.1
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.6\.1/sun4\-solaris
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.6\.1
&nbsp;    /usr/local/lib/perl5/site\_perl

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

I think I just sent this follow\-up to the wrong address\.\.\. \*sigh\*

Just tested on Linux \(Debian/Woody\) and I also see this bug on that
platform\. gdb/perl \-V output follows&#8203;:

$ gdb perl core
GNU gdb 5\.0\.90\-cvs \(MI\_OUT\)
Copyright 2001 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and you are
welcome to change it and/or distribute copies of it under certain conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for details\.
This GDB was configured as "i386\-linux"\.\.\.\(no debugging symbols found\)\.\.\.
Core was generated by \`perl \-w convert\.pl foofile\.out'\.
Program terminated with signal 11\, Segmentation fault\.
Reading symbols from /lib/libdl\.so\.2\.\.\.\(no debugging symbols found\)\.\.\.done\.
Loaded symbols for /lib/libdl\.so\.2
Reading symbols from /lib/libm\.so\.6\.\.\.\(no debugging symbols found\)\.\.\.done\.
Loaded symbols for /lib/libm\.so\.6
Reading symbols from /lib/libc\.so\.6\.\.\.\(no debugging symbols found\)\.\.\.done\.
Loaded symbols for /lib/libc\.so\.6
Reading symbols from /lib/libcrypt\.so\.1\.\.\.\(no debugging symbols found\)\.\.\.done\.
Loaded symbols for /lib/libcrypt\.so\.1
Reading symbols from /lib/ld\-linux\.so\.2\.\.\.\(no debugging symbols found\)\.\.\.done\.
Loaded symbols for /lib/ld\-linux\.so\.2
\#0  0x080d7bd8 in Perl\_swash\_fetch \(\)
\(gdb\) bt
\#0  0x080d7bd8 in Perl\_swash\_fetch \(\)
\#1  0x080d3212 in Perl\_regexec\_flags \(\)
\#2  0x080d1e7e in Perl\_regexec\_flags \(\)
\#3  0x080d1af6 in Perl\_regexec\_flags \(\)
\#4  0x0809b02b in Perl\_pp\_subst \(\)
\#5  0x080972c0 in Perl\_runops\_standard \(\)
\#6  0x0805c795 in perl\_run \(\)
\#7  0x0805c4fb in perl\_run \(\)
\#8  0x08059ed0 in main \(\)
\#9  0x4006065f in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6
\(gdb\) quit

$ perl \-V
Summary of my perl5 \(revision 5\.0 version 6 subversion 1\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.4\.5\-ac9\, archname=i386\-linux
&nbsp;    uname='linux duende 2\.4\.5\-ac9 \#1 thu jun 21 00&#8203;:52&#8203;:39 est 2001 i686 unknown '
&nbsp;    config\_args='\-Dccflags=\-DDEBIAN \-Dcccdlflags=\-fPIC \-Darchname=i386\-linux \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.6\.1 \-Darchlib=/usr/lib/perl/5\.6\.1 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.6\.1 \-Dsitearch=/usr/local/lib/perl/5\.6\.1 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dman1ext=1 \-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Uusesfio \-Dotherlibdirs=/usr/lib/perl5/5\.6&#8203;:/usr/lib/perl5/5\.005 \-Duseshrplib \-Dlibperl=libperl\.so\.5\.6\.1 \-Dd\_dosuid \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
&nbsp;    useperlio=undef d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-DDEBIAN \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2'\,
&nbsp;    cppflags='\-DDEBIAN \-fno\-strict\-aliasing \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='2\.95\.4 20010604 \(Debian prerelease\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, usemymalloc=n\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lgdbm \-ldbm \-ldb \-ldl \-lm \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lc \-lcrypt
&nbsp;    libc=/lib/libc\-2\.2\.3\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.6\.1
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: USE\_LARGE\_FILES
&nbsp;  Built under linux
&nbsp;  Compiled at Jun 22 2001 18&#8203;:52&#8203;:37
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/lib/perl/5\.6\.1
&nbsp;    /usr/local/share/perl/5\.6\.1
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/perl/5\.6\.1
&nbsp;    /usr/share/perl/5\.6\.1
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    /usr/lib/perl5/5\.6
&nbsp;    /usr/lib/perl5/5\.005

and\, since perl wasn't compiled on my machine\.\.\.

$ uname \-a
Linux sesquipedalian 2\.4\.16\-dvb1 \#1 Fri Nov 30 09&#8203;:47&#8203;:35 CST 2001 i686 unknown

**Comment by p5pRT** [comment]
### From @cpansprout

I can reproduce this same issue with 5\.6\.2\, but not with 5\.8\.1\. perl 5\.8
had a Unicode overhaul\, which I suspect squashed this bug\. I’m marking
it as resolved\.

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
