### ISSUE TITLE
Perl crash! (Segmentation Fault)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4691]
Migrated from [rt.perl.org#8048](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=8048) (status was 'resolved')

Searchable as RT8048$

**Comment by p5pRT** [comment]
### From demartines@yahoo.com

Hello\,

That's the first time it happens to me with such a simple program&#8203;:
perl crashes in a Segmentation Fault\.  I boiled down the program and
the data to the minimum possible\.  I'd be very glad if this can
help resolve a bug\.

I am using perl5\.6\.0 on linux RedHat7\.2 \(on this OS\, perl5\.6\.0 is the
standard version that comes with the OS; I tried to upgrade another 
machine to 5\.6\.1 with CPAN\, but it made my whole system very unstable
\-\-many scripts wouldn't work anymore; apparently on 5\.6\.1 the same
program seems to work\)\.  Anyway\, here is the report for perl5\.6\.0&#8203;:

\(prog\.pl and crashdata are included as attachements\)

1\. Symptoms


---
% \./prog\.pl crashdata > /dev/null
Segmentation fault \(core dumped\)

2\. OS specs


---
% uname \-a
Linux montreux 2\.4\.7\-10 \#1 Thu Sep 6 16&#8203;:46&#8203;:36 EDT 2001 i686 unknown

3\. perl config


---
% perlbug \-d


---
Flags&#8203;:
&nbsp;    category=
&nbsp;    severity=


---
Site configuration information for perl v5\.6\.0&#8203;:

Configured by bhcompile at Thu Aug  9 22&#8203;:47&#8203;:55 EDT 2001\.

Summary of my perl5 \(revision 5\.0 version 6 subversion 0\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.4\.6\-3\.1enterprise\, archname=i386\-linux
&nbsp;    uname='linux stripples\.devel\.redhat\.com 2\.4\.6\-3\.1enterprise \#1 smp
tue jul 24 14&#8203;:03&#8203;:17 edt 2001 i686 unknown '
&nbsp;    config\_args='\-des \-Doptimize=\-O2 \-march=i386 \-mcpu=i686 \-Dcc=gcc
\-Dcccdlflags=\-fPIC \-Dinstallprefix=/usr \-Dprefix=/usr
\-Darchname=i386\-linux \-Dd\_dosuid \-Dd\_semctl\_semun \-Di\_db \-Di\_ndbm
\-Di\_gdbm \-Di\_shadow \-Di\_syslog \-Dman3ext=3pm \-Uuselargefiles'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef use5005threads=undef useithreads=undef
usemultiplicity=undef
&nbsp;    useperlio=undef d\_sfio=undef uselargefiles=undef 
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
usesocks=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'\, optimize='\-O2 \-march=i386 \-mcpu=i686'\, gccversion=2\.96
20000731 \(Red Hat Linux 7\.1 2\.96\-96\)
&nbsp;    cppflags='\-fno\-strict\-aliasing \-I/usr/local/include'
&nbsp;    ccflags ='\-fno\-strict\-aliasing \-I/usr/local/include'
&nbsp;    stdchar='char'\, d\_stdstdio=define\, usevfork=false
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,
lseeksize=4
&nbsp;    alignbytes=4\, usemymalloc=n\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='gcc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-ldl \-lm \-lc \-lcrypt
&nbsp;    libc=/lib/libc\-2\.2\.4\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-L/usr/local/lib'

Locally applied patches&#8203;:



---
@&#8203;INC for perl v5\.6\.0&#8203;:
&nbsp;    /home/pierred/lib/perl
&nbsp;    /home/pierred/airtx/demo/lib/perl
&nbsp;    /usr/lib/perl5/5\.6\.0/i386\-linux
&nbsp;    /usr/lib/perl5/5\.6\.0
&nbsp;    /usr/lib/perl5/site\_perl/5\.6\.0/i386\-linux
&nbsp;    /usr/lib/perl5/site\_perl/5\.6\.0
&nbsp;    /usr/lib/perl5/site\_perl
&nbsp;    \.



---
Environment for perl v5\.6\.0&#8203;:
&nbsp;    HOME=/home/pierred
&nbsp;    LANG=en\_US
&nbsp;    LANGUAGE \(unset\)
&nbsp;   
LD\_LIBRARY\_PATH=/home/pierred/lib/arch\-ix86\-linux&#8203;:/usr/X11R6/lib&#8203;:/usr/local/lib
&nbsp;    LOGDIR \(unset\)
&nbsp;   
PATH=/usr/kerberos/bin&#8203;:\.&#8203;:/home/pierred/bin&#8203;:/home/pierred/bin/perl&#8203;:/home/pierred/bin/tcl&#8203;:/home/pierred/bin/arch\-ix86\-linux&#8203;:/usr/local/frame/bin&#8203;:/home/pierred/airtx/demo/bin&#8203;:/home/queuer/bin&#8203;:/home/queuer/scripts&#8203;:/usr/local/parasoft/bin\.linux&#8203;:/usr/local/bin&#8203;:/usr/local/gnu/bin&#8203;:/usr/sbin&#8203;:/usr/bsd&#8203;:/usr/ucb&#8203;:/sbin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/lib&#8203;:/usr/etc&#8203;:/usr/bin/X11&#8203;:/home/pierred/RIM/cross\-tools/bin&#8203;:/usr/X11R6/bin
&nbsp;    PERL5LIB=/home/pierred/lib/perl&#8203;:/home/pierred/airtx/demo/lib/perl
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/tcsh

\-\- 

Best regards\,
&nbsp;                        Pierre


\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
Pierre Demartines\, CTO AirTx   tel&#8203;:415\-641\-5481  cell&#8203;:415\-235\-1973

**Comment by p5pRT** [comment]
### From demartines@yahoo.com

[prog.pl](https://rt-archive.perl.org/perl5/Ticket/Attachment/19373/20275/prog.pl)

**Comment by p5pRT** [comment]
### From demartines@yahoo.com

From&#8203;: A

A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A



---

**Comment by p5pRT** [comment]
### From @schwern

On Wed\, Dec 12\, 2001 at 12&#8203;:32&#8203;:31PM \-0800\, Pierre Demartines wrote&#8203;:
> Hello\,
> 
> That's the first time it happens to me with such a simple program&#8203;:
> perl crashes in a Segmentation Fault\.  I boiled down the program and
> the data to the minimum possible\.  I'd be very glad if this can
> help resolve a bug\.
> 
> I am using perl5\.6\.0 on linux RedHat7\.2 \(on this OS\, perl5\.6\.0 is the
> standard version that comes with the OS; I tried to upgrade another 
> machine to 5\.6\.1 with CPAN\, but it made my whole system very unstable
> \-\-many scripts wouldn't work anymore; apparently on 5\.6\.1 the same
> program seems to work\)\.  Anyway\, here is the report for perl5\.6\.0&#8203;:

Confirmed\, it does segfault in 5\.6\.0\.  The bug's been fixed in 5\.6\.1


\-\- 

Michael G\. Schwern   \<schwern@&#8203;pobox\.com>    http&#8203;://www\.pobox\.com/~schwern/
Perl Quality Assurance        \<perl\-qa@&#8203;perl\.org>           Kwalitee Is Job One
Pancakes is the better part of valor\.
&nbsp;    http&#8203;://www\.goats\.com/archive/971202\.html

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

At 12&#8203;:32 \-0800 2001\-12\-12\, Pierre Demartines wrote&#8203;:
>Hello\,
>
>That's the first time it happens to me with such a simple program&#8203;:
>perl crashes in a Segmentation Fault\.  I boiled down the program and
>the data to the minimum possible\.  I'd be very glad if this can
>help resolve a bug\.

>\#\!/usr/local/bin/perl
>
>undef $/;
>$\_ = \<>;    \# slurps in the whole text file
>s/\\015//g;
>@&#8203;emails = split\(/\(?=From&#8203;:\\s\*\.\*\\n\)/m\);
>for \(@&#8203;emails\) \{
>     \($header\, $\_\) = split\(/\(?\<=\\n\)\\n/m\, $\_\, 2\);
>     \# try to remove quoted messages
>     \($\_\, $rest\) = split\(/^\[> \]\*\-\-\-\-\-/m\, $\_\, 2\);
>\}

Those regular expressions are going to beat the hell out of perl's 
regex engine\. The regex engine is \(and this is a known bug which may 
get fixed in perl 5\.10\, not in the coming release\, 5\.8\) prone to 
overflowing the stack in certain situations like this \(although I can 
only recall having seen the bug tickled by regexps involving 
alternation \-\- the '|' operator\, not lookahead as in your script\)\. If 
you can look at the core dump with a debugger \-\- say

$ gdb perl core
\.\.\.\.
\(gdb\) bt 10

and it says that perl expired out in the regmatch\(\) function\, with a 
load more regmatch\(\) stack frames above it\, then that's your problem\. 
If the script works with a small dataset\, but not with a big one\, 
then that's your problem\. If You can make the script run with a 
larger dataset by increasing perl's stack allocation \(with ulimit \-s\) 
than that's your problem\.

If none of these is the case\, then your problem is something else\.

That said\, I can't make your script crash perl5\.6\.0 running on Mac OS 
X \(Darwin\)\, even when I restrict the stack to just 100k \-\- although 
Michael G Schwern has managed to reproduce it\. It did take an hour to 
do the initial split of a 7\.5Mb mail box\, though \-\- admittedly on a 
busy system\.  This leads me to\.\.\.

What can you do to prevent your data from inciting your script to 
crash perl or perform badly? Rewrite your regular expressions\. Your 
first one is splitting on a null string with trailing context of the 
whole of the rest of the rest of the mail box\. You really need 
something a lot less greedy\.

You should also have another shot at installing 5\.6\.1\. Please submit 
another bug report if it is not stable on your system\.


\-\- 
Dominic Dunlop

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Thank you all \-\-I have to say I am overwhelmed with the quality and
dedication of your support\!  Very impressive\!

Re you comments\, Dominic&#8203;:
1\. I fail to see which regexp is going to beat the hell out of the engine\.
&nbsp;   BTW\, the crash actually occurs on the last regexp \(line 10\) which seems
&nbsp;   really inoccuous to me \(i\.e\. not prone to a lot of recursion\)\.
2\. The "minimal" crashing data set \(provided in my initial email\) is very
&nbsp;   small\.  It contains 103 lines for a total of 320 chars\.
3\. no matter what the stack size is\, the crash occurs\. And I can give it a
&nbsp;   lot of stack since my current machine has 1GB of ram\.
4\. It's really the split on line 10 that crashes\. If I change it into
&nbsp;   0010&#8203;:     s/^\[> \]\*\-\-\-\-\-\[^\\000\]\*//m;
&nbsp;   Then there is no crash\.
5\. When I run perl in gdb\, here is what I get&#8203;:
&nbsp;      gdb /usr/local/bin/perl
&nbsp;      GNU gdb Red Hat Linux 7\.x \(5\.0rh\-15\) \(MI\_OUT\)
&nbsp;      Copyright 2001 Free Software Foundation\, Inc\.
&nbsp;      GDB is free software\, covered by the GNU General Public License\, and
you are
&nbsp;      welcome to change it and/or distribute copies of it under certain
conditions\.
&nbsp;      Type "show copying" to see the conditions\.
&nbsp;      There is absolutely no warranty for GDB\.  Type "show warranty" for
details\.
&nbsp;      This GDB was configured as "i386\-redhat\-linux"\.\.\.\(no debugging symbols
found\)\.\.\.
&nbsp;      \(gdb\) run prog\.pl crashdata
&nbsp;      Starting program&#8203;: /usr/local/bin/perl prog\.pl crashdata

&nbsp;      Program received signal SIGSEGV\, Segmentation fault\.
&nbsp;      0x080d1cc6 in Perl\_re\_intuit\_start \(\) at eval\.c&#8203;:41
&nbsp;      41      eval\.c&#8203;: No such file or directory\.
&nbsp;              in eval\.c
&nbsp;      \(gdb\) bt 10
&nbsp;      \#0  0x080d1cc6 in Perl\_re\_intuit\_start \(\) at eval\.c&#8203;:41
&nbsp;      \#1  0x080d350a in Perl\_regexec\_flags \(\) at eval\.c&#8203;:41
&nbsp;      \#2  0x080b4d28 in Perl\_pp\_split \(\) at eval\.c&#8203;:41
&nbsp;      \#3  0x08097e28 in Perl\_runops\_standard \(\) at eval\.c&#8203;:41
&nbsp;      \#4  0x0805bfba in perl\_run \(\) at eval\.c&#8203;:41
&nbsp;      \#5  0x0805bd2b in perl\_run \(\) at eval\.c&#8203;:41
&nbsp;      \#6  0x08059a21 in main \(\) at eval\.c&#8203;:41
&nbsp;      \#7  0x4008c507 in \_\_libc\_start\_main \(main=0x80599b0 \<main>\, argc=3\,
ubp\_av=0xbffff494\, init=0x8058b80 \<\_init>\,
&nbsp;          fini=0x80de810 \<\_fini>\, rtld\_fini=0x4000dc14 \<\_dl\_fini>\,
stack\_end=0xbffff48c\) at \.\./sysdeps/generic/libc\-start\.c&#8203;:129
&nbsp;      \(gdb\) q

6\. Rewriting the regexps&#8203;: of course\, the example I gave in my script is for
&nbsp;   the purpose of showing a "minimal" script that crashes\.  In the real
system
&nbsp;   things are a bit more complex\.\.\.  BTW\, as I mentionned above the script
&nbsp;   works \(and fast enough to my taste\) when I change line 10 as explained in
&nbsp;   point 4\. above\.  With the modified "crashing" script \(only line 10
modified\)
&nbsp;   it takes 28 seconds to process 153 MB of email in a dozen of mailboxes
&nbsp;   \(10423 different emails\)\.
7\. re\-installing perl5\.6\.1&#8203;:  Point taken\, I know I should\.\.\.  It's just a
&nbsp;   matter of getting the time to do it properly\.

Thanks again and best regards\,

~Pierre


> \-\-\-\-\-Original Message\-\-\-\-\-
> From&#8203;: Dominic Dunlop \[mailto&#8203;:domo@&#8203;computer\.org\]
> Sent&#8203;: Wednesday\, December 19\, 2001 1&#8203;:38 PM
> To&#8203;: Pierre Demartines
> Cc&#8203;: perl5\-porters@&#8203;perl\.org; perlbug@&#8203;rfi\.net; Michael G Schwern
> Subject&#8203;: Re&#8203;: \[ID 20011212\.006\] Perl crash\! \(Segmentation Fault\)
>
>
> At 12&#8203;:32 \-0800 2001\-12\-12\, Pierre Demartines wrote&#8203;:
> >Hello\,
> >
> >That's the first time it happens to me with such a simple program&#8203;:
> >perl crashes in a Segmentation Fault\.  I boiled down the program and
> >the data to the minimum possible\.  I'd be very glad if this can
> >help resolve a bug\.
>
> >\#\!/usr/local/bin/perl
> >
> >undef $/;
> >$\_ = \<>;    \# slurps in the whole text file
> >s/\\015//g;
> >@&#8203;emails = split\(/\(?=From&#8203;:\\s\*\.\*\\n\)/m\);
> >for \(@&#8203;emails\) \{
> >     \($header\, $\_\) = split\(/\(?\<=\\n\)\\n/m\, $\_\, 2\);
> >     \# try to remove quoted messages
> >     \($\_\, $rest\) = split\(/^\[> \]\*\-\-\-\-\-/m\, $\_\, 2\);
> >\}
>
> Those regular expressions are going to beat the hell out of perl's
> regex engine\. The regex engine is \(and this is a known bug which may
> get fixed in perl 5\.10\, not in the coming release\, 5\.8\) prone to
> overflowing the stack in certain situations like this \(although I can
> only recall having seen the bug tickled by regexps involving
> alternation \-\- the '|' operator\, not lookahead as in your script\)\. If
> you can look at the core dump with a debugger \-\- say
>
> $ gdb perl core
> \.\.\.
> \(gdb\) bt 10
>
> and it says that perl expired out in the regmatch\(\) function\, with a
> load more regmatch\(\) stack frames above it\, then that's your problem\.
> If the script works with a small dataset\, but not with a big one\,
> then that's your problem\. If You can make the script run with a
> larger dataset by increasing perl's stack allocation \(with ulimit \-s\)
> than that's your problem\.
>
> If none of these is the case\, then your problem is something else\.
>
> That said\, I can't make your script crash perl5\.6\.0 running on Mac OS
> X \(Darwin\)\, even when I restrict the stack to just 100k \-\- although
> Michael G Schwern has managed to reproduce it\. It did take an hour to
> do the initial split of a 7\.5Mb mail box\, though \-\- admittedly on a
> busy system\.  This leads me to\.\.\.
>
> What can you do to prevent your data from inciting your script to
> crash perl or perform badly? Rewrite your regular expressions\. Your
> first one is splitting on a null string with trailing context of the
> whole of the rest of the rest of the mail box\. You really need
> something a lot less greedy\.
>
> You should also have another shot at installing 5\.6\.1\. Please submit
> another bug report if it is not stable on your system\.
>
>
> \-\-
> Dominic Dunlop


\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
Do You Yahoo\!?
Get your free @&#8203;yahoo\.com address at http&#8203;://mail\.yahoo\.com

**Comment by p5pRT** [comment]
### From @smpeters

> \[RT\_System \- Wed Dec 12 08&#8203;:46&#8203;:13 2001\]&#8203;:
> 
> On Wed\, Dec 12\, 2001 at 12&#8203;:32&#8203;:31PM \-0800\, Pierre Demartines wrote&#8203;:
> > Hello\,
> > 
> > That's the first time it happens to me with such a simple program&#8203;:
> > perl crashes in a Segmentation Fault\.  I boiled down the program and
> > the data to the minimum possible\.  I'd be very glad if this can
> > help resolve a bug\.
> > 
> > I am using perl5\.6\.0 on linux RedHat7\.2 \(on this OS\, perl5\.6\.0 is the
> > standard version that comes with the OS; I tried to upgrade another 
> > machine to 5\.6\.1 with CPAN\, but it made my whole system very unstable
> > \-\-many scripts wouldn't work anymore; apparently on 5\.6\.1 the same
> > program seems to work\)\.  Anyway\, here is the report for perl5\.6\.0&#8203;:
> 
> Confirmed\, it does segfault in 5\.6\.0\.  The bug's been fixed in 5\.6\.1
> 

I've confirmed that the segfault no longer occurs\.

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'resolved'
