### ISSUE TITLE
psuedohash Out of memory!

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4700]
Migrated from [rt.perl.org#8058](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=8058) (status was 'resolved')

Searchable as RT8058$

**Comment by p5pRT** [comment]
### From barries@sizzle.whoville.com

#### Created by barries@sizzle.whoville.com




perl5\.00503\, perl5\.6\.1\, and a not so old bleadperl all get very\!
excited\! when\! you\! do\! this\!

&nbsp;        Test\-Differences$ perl \-e '$s = \[ \{ Handler => bless \{\}\, "Foo" \} \]; $s\->\{Handler\} = 1;'
&nbsp;        Out of memory\!

<details><summary>Perl Info</summary>

```


This perlbug was built using Perl 5.00503 - Mon Jul 31 22:48:49 PDT 2000
It is being executed now by  Perl 5.006001 - Tue Apr 17 13:56:59 EDT 2001.

Site configuration information for perl 5.006001:

Configured by barries at Tue Apr 17 13:56:59 EDT 2001.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=linux, osvers=2.2.14-va.5.1, archname=i686-linux
    uname='linux sizzle 2.2.14-va.5.1 #1 tue sep 12 18:08:18 pdt 2000 i686 unknown '
    config_args='-d'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2',
    cppflags='-fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='egcs-2.91.66 19990314/Linux (egcs-1.1.2 release)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lndbm -lgdbm -ldb -ldl -lm -lc -lposix -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lposix -lcrypt -lutil
    libc=/lib/libc-2.1.3.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl 5.006001:
    /home/barries/src/XML-SAX-PHB/lib
    /usr/local/lib/perl5/5.6.1/i686-linux
    /usr/local/lib/perl5/5.6.1
    /usr/local/lib/perl5/site_perl/5.6.1/i686-linux
    /usr/local/lib/perl5/site_perl/5.6.1
    /usr/local/lib/perl5/site_perl
    .


Environment for perl 5.006001:
    HOME=/home/barries
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:~/bin:/sbin:/usr/sbin:/home/barries/bin:/usr/contrib/bin/:~/bin:/sbin:/usr/sbin:~/bin:/sbin:/usr/sbin:~/bin:/sbin:/usr/sbin:~/bin:/sbin:/usr/sbin
    PERL5LIB=/home/barries/src/XML-SAX-PHB/lib
    PERL_BADLANG (unset)
    SHELL=/bin/bash


```
</details>

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Dec 13\, barries@&#8203;sizzle\.whoville\.com said&#8203;:

>perl5\.00503\, perl5\.6\.1\, and a not so old bleadperl all get very\!
>excited\! when\! you\! do\! this\!
>
>  Test\-Differences$ perl \-e '$s = \[ \{ Handler => bless \{\}\, "Foo" \} \]; $s\->\{Handler\} = 1;'
>  Out of memory\!

Probably because \(0 \+ \{\}\) is a VERY large number\.

\-\- 
Jeff "japhy" Pinyan      japhy@&#8203;pobox\.com      http&#8203;://www\.pobox\.com/~japhy/
RPI Acacia brother \#734   http&#8203;://www\.perlmonks\.org/   http&#8203;://www\.cpan\.org/
\*\* Look for "Regular Expressions in Perl" published by Manning\, in 2002 \*\*
\<stu> what does y/// stand for?  \<tenderpuss> why\, yansliterate of course\.

**Comment by p5pRT** [comment]
### From @schwern

On Thu\, Dec 13\, 2001 at 11&#8203;:49&#8203;:10AM \-0500\, barries@&#8203;sizzle\.whoville\.com wrote&#8203;:
> perl5\.00503\, perl5\.6\.1\, and a not so old bleadperl all get very\!
> excited\! when\! you\! do\! this\!
> 
>         Test\-Differences$ perl \-e '$s = \[ \{ Handler => bless \{\}\, "Foo" \} \]; $s\->\{Handler\} = 1;'
>         Out of memory\!

The bleadperl error throws some light on it\.
Out of memory during "large" request for 2147487744 bytes\, total sbrk\(\) is 74468 bytes at \-e line 1\.


That $s\->\{Handler\} = 1 translates to&#8203;:

&nbsp;    $s\->\[$s\->\[0\]\{Handler\}\];

which is&#8203;:

&nbsp;    $s\->\[bless \{\}\, "Foo"\]

which is something like&#8203;:

&nbsp;    $s\->\[270104932\]

which doesn't cause an error\.  But this does&#8203;:

&nbsp;    $s\->\[270104932\] = 1;

so does this

&nbsp;    $\#s = 270104932;

So it must be that pseudo\-hash fetch is doing an av\_extend\.

Breakpoint 1\, Perl\_av\_extend \(av=0x10199080\, key=27010493\) at av\.c&#8203;:60
60          if \(\(mg = SvTIED\_mg\(\(SV\*\)av\, PERL\_MAGIC\_tied\)\)\) \{
\(gdb\) bt
\#0  Perl\_av\_extend \(av=0x10199080\, key=27010493\) at av\.c&#8203;:60
\#1  0x100a142c in Perl\_av\_store \(av=0x10199080\, key=27010493\, val=0x101992a8\)
&nbsp;    at av\.c&#8203;:271
\#2  0x100a10e0 in Perl\_av\_fetch \(av=0x10199080\, key=27010493\, lval=1\)
&nbsp;    at av\.c&#8203;:204
\#3  0x100a4878 in Perl\_avhv\_fetch\_ent \(av=0x10199080\, keysv=0x10199230\, 
&nbsp;    lval=1\, hash=1105802825\) at av\.c&#8203;:884
\#4  0x100ad064 in Perl\_pp\_helem \(\) at pp\_hot\.c&#8203;:1653
\#5  0x10088ddc in Perl\_runops\_debug \(\) at dump\.c&#8203;:1391
\#6  0x10018dc8 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1595
\#7  0x100187a0 in perl\_run \(my\_perl=0x10198808\) at perl\.c&#8203;:1516
\#8  0x10014090 in main \(argc=3\, argv=0x7ffffb54\, env=0x7ffffb64\)
&nbsp;    at perlmain\.c&#8203;:76
\#9  0x0fdd8a30 in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6

no\, av\_fetch is calling av\_store which is then extending\.  That can't
be right\.  Anyone want to explain the logic of that?

&nbsp;    if \(key > AvFILLp\(av\)\) \{
&nbsp;        if \(\!lval\)
&nbsp;            return 0;
&nbsp;        sv = NEWSV\(5\,0\);
&nbsp;        return av\_store\(av\,key\,sv\);
&nbsp;    \}



\-\- 

Michael G\. Schwern   \<schwern@&#8203;pobox\.com>    http&#8203;://www\.pobox\.com/~schwern/
Perl Quality Assurance        \<perl\-qa@&#8203;perl\.org>           Kwalitee Is Job One
Ooops\, fatal mutation in the test script\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

\-\-\- Michael G Schwern \<schwern@&#8203;pobox\.com> wrote&#8203;:
> no\, av\_fetch is calling av\_store which is then extending\.
>  That can't
> be right\.  Anyone want to explain the logic of that?
> 
>     if \(key > AvFILLp\(av\)\) \{
>         if \(\!lval\)
>             return 0;
>         sv = NEWSV\(5\,0\);
>         return av\_store\(av\,key\,sv\);
>     \}

It most certainly is right\. av\_fetch was called with lval =
TRUE\, denoting that this fetch \_must\_ return an lvalue\.
Since there isn't one already at that position in the
array\, av\_fetch creates a new SV\, stores it in the array\,
and returns it\.

\-\- BKS

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
Do You Yahoo\!?
Check out Yahoo\! Shopping and Yahoo\! Auctions for all of
your unique holiday gifts\! Buy at http&#8203;://shopping\.yahoo\.com
or bid at http&#8203;://auctions\.yahoo\.com

**Comment by p5pRT** [comment]
### From @schwern

The code does the equivalent of&#8203;:

&nbsp;    $s\->\[bless \{\}\] = 1;

and a reference numerifies to a Very Large Number\.  So its&#8203;:

&nbsp;    $s\->\[27010493\] = 1;     \# for example

which causes Perl to try to allocate a huge array\.


\-\- 

Michael G\. Schwern   \<schwern@&#8203;pobox\.com>    http&#8203;://www\.pobox\.com/~schwern/
Perl Quality Assurance        \<perl\-qa@&#8203;perl\.org>           Kwalitee Is Job One
Pancakes is the better part of valor\.
&nbsp;    http&#8203;://www\.goats\.com/archive/971202\.html

**Comment by p5pRT** [comment]
### From @schwern

On Thu\, Dec 13\, 2001 at 10&#8203;:11&#8203;:26AM \-0800\, Benjamin Stuhl wrote&#8203;:
> \-\-\- Michael G Schwern \<schwern@&#8203;pobox\.com> wrote&#8203;:
> > no\, av\_fetch is calling av\_store which is then extending\.
> >  That can't
> > be right\.  Anyone want to explain the logic of that?
> > 
> >     if \(key > AvFILLp\(av\)\) \{
> >         if \(\!lval\)
> >             return 0;
> >         sv = NEWSV\(5\,0\);
> >         return av\_store\(av\,key\,sv\);
> >     \}
> 
> It most certainly is right\. av\_fetch was called with lval =
> TRUE\, denoting that this fetch \_must\_ return an lvalue\.
> Since there isn't one already at that position in the
> array\, av\_fetch creates a new SV\, stores it in the array\,
> and returns it\.

Makes sense\.  Closed the bug as 'not a bug'


\-\- 

Michael G\. Schwern   \<schwern@&#8203;pobox\.com>    http&#8203;://www\.pobox\.com/~schwern/
Perl Quality Assurance        \<perl\-qa@&#8203;perl\.org>           Kwalitee Is Job One
Me? A robot? That's rediculous\! For one thing\, that doesn't compute at all\!
