### ISSUE TITLE
sv_setpvf("%vd",...) causing SEGV

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4724]
Migrated from [rt.perl.org#8083](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=8083) (status was 'resolved')

Searchable as RT8083$

**Comment by p5pRT** [comment]
### From @JohnPeacock

The following code&#8203;:

\{
&nbsp;    SV  \*rs = newSVpv\(""\,0\);
&nbsp;    char \*version = SvPVX\(lobj\);

&nbsp;    sv\_dump\(rs\);
&nbsp;    sv\_dump\(lobj\);

&nbsp;    sv\_setpvf\(rs\,"%s"\,version\);
&nbsp;    sv\_dump\(rs\);
\}

outputs the following&#8203;:

SV = PV\(0xa10ae54\) at 0xa026260
&nbsp;  REFCNT = 1
&nbsp;  FLAGS = \(POK\,pPOK\)
&nbsp;  PV = 0xa10f938 ""\\0
&nbsp;  CUR = 0
&nbsp;  LEN = 1
SV = PVMG\(0xa118c28\) at 0xa0261b8
&nbsp;  REFCNT = 2
&nbsp;  FLAGS = \(OBJECT\,POK\,READONLY\,pPOK\)
&nbsp;  IV = 0
&nbsp;  NV = 0
&nbsp;  PV = 0xa026e88 "\\1\\2\\4"\\0
&nbsp;  CUR = 3
&nbsp;  LEN = 6
&nbsp;  STASH = 0xa09b8b0     "Universal&#8203;::Version"
SV = PV\(0xa10ae54\) at 0xa026260
&nbsp;  REFCNT = 1
&nbsp;  FLAGS = \(POK\,pPOK\)
&nbsp;  PV = 0xa10f938 "\\1\\2\\4"\\0
&nbsp;  CUR = 3
&nbsp;  LEN = 4

However\, the following&#8203;:

\{
&nbsp;    SV  \*rs = newSVpv\(""\,0\);
&nbsp;    char \*version = SvPVX\(lobj\);

&nbsp;    sv\_dump\(rs\);
&nbsp;    sv\_dump\(lobj\);

&nbsp;    sv\_setpvf\(rs\,"%vd"\,version\); /\* THIS LINE IS THE ONLY CHANGE \*/
&nbsp;    sv\_dump\(rs\);
\}

generates the following&#8203;:

SV = PV\(0xa10ae54\) at 0xa026260
&nbsp;  REFCNT = 1
&nbsp;  FLAGS = \(POK\,pPOK\)
&nbsp;  PV = 0xa10f938 ""\\0
&nbsp;  CUR = 0
&nbsp;  LEN = 1
SV = PVMG\(0xa118c28\) at 0xa0261b8
&nbsp;  REFCNT = 2
&nbsp;  FLAGS = \(OBJECT\,POK\,READONLY\,pPOK\)
&nbsp;  IV = 0
&nbsp;  NV = 0
&nbsp;  PV = 0xa026e88 "\\1\\2\\4"\\0
&nbsp;  CUR = 3
&nbsp;  LEN = 6
&nbsp;  STASH = 0xa09b8b0     "Universal&#8203;::Version"

followed by a SEGV error with the following backtrace&#8203;:

\#0  0x6cdcdccb in Perl\_sv\_vcatpvfn \(sv=0xa026260\, pat=0x68e01410 "%vd"\,
&nbsp;    patlen=3\, args=0x22fc20\, svargs=0x0\, svmax=0\, maybe\_tainted=0x0\)
&nbsp;    at sv\.c&#8203;:7828
\#1  0x6cdcd5dc in Perl\_sv\_vsetpvfn \(sv=0xa026260\, pat=0x68e01410 "%vd"\,
&nbsp;    patlen=3\, args=0x22fc20\, svargs=0x0\, svmax=0\, maybe\_tainted=0x0\)
&nbsp;    at sv\.c&#8203;:7608
\#2  0x6cdcd426 in Perl\_sv\_vsetpvf \(sv=0xa026260\, pat=0x68e01410 "%vd"\,
&nbsp;    args=0x22fc20\) at sv\.c&#8203;:7475
\#3  0x6cdcd3ec in Perl\_sv\_setpvf \(sv=0xa026260\, pat=0x68e01410 "%vd"\)
&nbsp;    at sv\.c&#8203;:7466
\#4  0x68e01550 in XS\_Universal\_\_Version\_\_newstringify \(cv=0xa10726c\)
&nbsp;    at Version\.xs&#8203;:59
\#5  0x6cdbc93b in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:2727
\#6  0x6cd9f68d in Perl\_runops\_debug \(\) at dump\.c&#8203;:1391
\#7  0x6cd44275 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1597
\#8  0x6cd43db9 in perl\_run \(my\_perl=0xa010388\) at perl\.c&#8203;:1518
\#9  0x004010f3 in main \(argc=4\, argv=0x61553ba8\, env=0xa010278\)
&nbsp;    at perlmain\.c&#8203;:76

I am reading through Perl\_sv\_vcatpvfn\(\)\, but I don't see any reason why it
should blow up like that\.  I have to guess that is must have something to do
with the fact that the object in question is magic\.  However\, if I try and 
do this&#8203;:

\{
&nbsp;    SV  \*rs = newSVpv\(""\,0\);
&nbsp;    SV  \*vs = newSVpv\(""\,0\);
&nbsp;    char \*version = SvPVX\(lobj\);

&nbsp;    sv\_dump\(rs\);
&nbsp;    sv\_dump\(lobj\);

&nbsp;    sv\_setpvf\(rs\,"%s"\,version\);
&nbsp;    sv\_dump\(rs\);            
&nbsp;    version = SvPVX\(rs\);        /\* this is now an ordinary string \*/
&nbsp;    sv\_setpvf\(vs\,"%vd"\,version\);
\}

which still generates a SEGV&#8203;:

\#0  0x6cda5c3a in Perl\_mg\_get \(sv=0xa10f938\) at mg\.c&#8203;:115
\#1  0x6cdc2e5a in Perl\_sv\_2pv\_flags \(sv=0xa10f938\, lp=0x22fab8\, flags=2\)
&nbsp;    at sv\.c&#8203;:2907
\#2  0x6cdcdcf8 in Perl\_sv\_vcatpvfn \(sv=0xa02626c\, pat=0x68e01413 "%vd"\,
&nbsp;    patlen=3\, args=0x22fc10\, svargs=0x0\, svmax=0\, maybe\_tainted=0x0\)
&nbsp;    at sv\.c&#8203;:7828
\#3  0x6cdcd5dc in Perl\_sv\_vsetpvfn \(sv=0xa02626c\, pat=0x68e01413 "%vd"\,
&nbsp;    patlen=3\, args=0x22fc10\, svargs=0x0\, svmax=0\, maybe\_tainted=0x0\)
&nbsp;    at sv\.c&#8203;:7608
\#4  0x6cdcd426 in Perl\_sv\_vsetpvf \(sv=0xa02626c\, pat=0x68e01413 "%vd"\,
&nbsp;    args=0x22fc10\) at sv\.c&#8203;:7475
\#5  0x6cdcd3ec in Perl\_sv\_setpvf \(sv=0xa02626c\, pat=0x68e01413 "%vd"\)
&nbsp;    at sv\.c&#8203;:7466
\#6  0x68e0159c in XS\_Universal\_\_Version\_\_newstringify \(cv=0xa10726c\)
&nbsp;    at Version\.xs&#8203;:63
\#7  0x6cdbc93b in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:2727
\#8  0x6cd9f68d in Perl\_runops\_debug \(\) at dump\.c&#8203;:1391
\#9  0x6cd44275 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1597
\#10 0x6cd43db9 in perl\_run \(my\_perl=0xa010388\) at perl\.c&#8203;:1518
\#11 0x004010f3 in main \(argc=4\, argv=0x61553ba8\, env=0xa010278\)
&nbsp;    at perlmain\.c&#8203;:76

Any ideas?

John

\-\- 
John Peacock
Director of Information Research and Technology
Rowman & Littlefield Publishing Group
4720 Boston Way
Lanham\, MD 20706
301\-459\-3366 x\.5010
fax 301\-429\-5747

**Comment by p5pRT** [comment]
### From @vanstyn

John Peacock \<jpeacock@&#8203;rowman\.com> wrote&#8203;:
\[\.\.\.\]
:However\, the following&#8203;:
:
:\{
:    SV  \*rs = newSVpv\(""\,0\);
:    char \*version = SvPVX\(lobj\);
:
:    sv\_dump\(rs\);
:    sv\_dump\(lobj\);
:
:    sv\_setpvf\(rs\,"%vd"\,version\); /\* THIS LINE IS THE ONLY CHANGE \*/
:    sv\_dump\(rs\);
:\}
:
:generates \[a core dump at sv\.c&#8203;:7828\]

Looking at the code\, the C\-args interface to sv\_vcatpvfn\(\) expects
an SV for any vectorised argument\, not a char\* :

&nbsp;        if \(vectorize\) \{
&nbsp;            if \(vectorarg\) \{ \.\.\. \}
/\* if we have a direct C\-style arg list \*/
&nbsp;            if \(args\) \{
=>              vecsv = va\_arg\(\*args\, SV\*\);
=>              vecstr = \(U8\*\)SvPVx\(vecsv\,veclen\);
&nbsp;                vec\_utf = DO\_UTF8\(vecsv\);
&nbsp;            \}
/\* else if we haven't run out of our perl\-style list of SV\* \*/
&nbsp;            else if \(efix ? efix \<= svmax : svix \< svmax\) \{
&nbsp;                vecsv = svargs\[efix ? efix\-1 : svix\+\+\];
&nbsp;                vecstr = \(U8\*\)SvPVx\(vecsv\,veclen\);
&nbsp;                vec\_utf = DO\_UTF8\(vecsv\);
&nbsp;            \}
/\* else we don't have an argument\, so use an empty string \*/
&nbsp;            else \{
&nbsp;                vecstr = \(U8\*\)"";
&nbsp;                veclen = 0;
&nbsp;            \}
&nbsp;        \}

I can't find anywhere that such oddities would be documented \- perhaps
they should go in the apidoc\, at the risk of making that quite large\.
This is an aspect of the function I simply preserved in my rewrite of
a while back\.

:I am reading through Perl\_sv\_vcatpvfn\(\)\, but I don't see any reason why it
:should blow up like that\.  I have to guess that is must have something to do
:with the fact that the object in question is magic\.  However\, if I try and 
:do this&#8203;:
:
:\{
:    SV  \*rs = newSVpv\(""\,0\);
:    SV  \*vs = newSVpv\(""\,0\);
:    char \*version = SvPVX\(lobj\);
:
:    sv\_dump\(rs\);
:    sv\_dump\(lobj\);
:
:    sv\_setpvf\(rs\,"%s"\,version\);
:    sv\_dump\(rs\);            
:    version = SvPVX\(rs\);        /\* this is now an ordinary string \*/
:    sv\_setpvf\(vs\,"%vd"\,version\);
:\}
:
:which still generates a SEGV&#8203;:

This is still passing a char\* \- try calling with lobj as the argument\.

Hugo

**Comment by p5pRT** [comment]
### From @JohnPeacock

Hugo van der Sanden wrote&#8203;:
> 
> Looking at the code\, the C\-args interface to sv\_vcatpvfn\(\) expects
> an SV for any vectorised argument\, not a char\* :

Thanks for the extra pair of eyes\.

> 
>         if \(vectorize\) \{
>             if \(vectorarg\) \{ \.\.\. \}
> /\* if we have a direct C\-style arg list \*/
>             if \(args\) \{
> =>              vecsv = va\_arg\(\*args\, SV\*\);
> =>              vecstr = \(U8\*\)SvPVx\(vecsv\,veclen\);
>                 vec\_utf = DO\_UTF8\(vecsv\);
>             \}

ARG\!  This would seem to suggest that all of the sprintf\(\)\-style
calls in the API need to have a little added to the docs\, since no
where I could find did it suggest that the arguments were SV's\.  I 
just checked and sure enough\, the code works great when passed the
parameters it expected\. ;~\)

John

\-\- 
John Peacock
Director of Information Research and Technology
Rowman & Littlefield Publishing Group
4720 Boston Way
Lanham\, MD 20706
301\-459\-3366 x\.5010
fax 301\-429\-5747

**Comment by p5pRT** [comment]
### From @JohnPeacock

not a bug

**Comment by p5pRT** [comment]
@JohnPeacock - Status changed from 'open' to 'resolved'
