### ISSUE TITLE
The magic escapes

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4735]
Migrated from [rt.perl.org#8108](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=8108) (status was 'resolved')

Searchable as RT8108$

**Comment by p5pRT** [comment]
### From me-01@ton.iguana.be

#### Created by perl@ton.iguana.be



perl \-wle 'splice @&#8203;x\, 1\, 1 for @&#8203;x = qw\(a b c d e f g\)'

gives&#8203;:
Unhandled exception in file mg\.c\, line 318&#8203;: Assertion failed \(You should never see this\) myFree\(\#0x21\, mg\.c\, 318\) \(free\(\#0x21\)\) cannot possibly refer to valid malloced memory&#8203;: Success

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.7.1:

Configured by ton at Sat May 12 18:42:24 CEST 2001.

Summary of my perl5 (revision 5.0 version 7 subversion 1) configuration:
  Platform:
    osname=linux, osvers=2.4.3, archname=i686-linux
    uname='linux quasar 2.4.3 #19 sun apr 1 10:46:29 cest 2001 i686 unknown '
    config_args='-e'
    hint=previous, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DDEBUGGING',
    optimize='-g',
    cppflags='-fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DDEBUGGING'
    ccversion='', gccversion='egcs-2.91.66 19990314 (egcs-1.1.2 release)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib -L/opt/gnu/lib'
    libpth=/usr/local/lib /opt/gnu/lib /lib /usr/lib
    libs=-lnsl -lndbm -ldb -ldl -lm -lc -lposix -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lposix -lcrypt -lutil
    libc=/lib/libc-2.1.1.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic -Wl,-rpath,/usr/lib/perl5/5.7.1/i686-linux/CORE'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib -L/opt/gnu/lib'

Locally applied patches:
    


@INC for perl v5.7.1:
    /usr/lib/perl5/5.7.1/i686-linux
    /usr/lib/perl5/5.7.1
    /usr/lib/perl5/site_perl/5.7.1/i686-linux
    /usr/lib/perl5/site_perl/5.7.1
    /usr/lib/perl5/site_perl
    .


Environment for perl v5.7.1:
    HOME=/home/ton
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/ton/bin.Linux:/home/ton/bin:/home/ton/bin.SampleSetup:/usr/local/bin:/usr/local/sbin:/usr/local/jre/bin:/home/oracle/product/9.0.1/bin:/usr/games/bin:/usr/X11R6/bin:/usr/share/bin:/usr/bin:/usr/sbin:/bin:/sbin:.
    PERL_BADLANG (unset)
    SHELL=/bin/bash


```
</details>

**Comment by p5pRT** [comment]
### From @schwern

On Fri\, Dec 21\, 2001 at 12&#8203;:37&#8203;:46AM \-0000\, me\-01@&#8203;ton\.iguana\.be wrote&#8203;:
> perl \-wle 'splice @&#8203;x\, 1\, 1 for @&#8203;x = qw\(a b c d e f g\)'
> 
> gives&#8203;:
> Unhandled exception in file mg\.c\, line 318&#8203;: Assertion failed \(You should never see this\) myFree\(\#0x21\, mg\.c\, 318\) \(free\(\#0x21\)\) cannot possibly refer to valid malloced memory&#8203;: Success

That's a nasty one you've got there\.

$ bleadperl@&#8203;13745 \-wle 'splice @&#8203;x\, 1\, 1 for @&#8203;x = qw\(a b c d e f g\)'
Segmentation fault

$ perl5\.6\.1 \-wle 'splice @&#8203;x\, 1\, 1 for @&#8203;x = qw\(a b c d e f g\)'
Segmentation fault

$ perl5\.6\.0 \-wle 'splice @&#8203;x\, 1\, 1 for @&#8203;x = qw\(a b c d e f g\)'
Attempt to free unreferenced scalar at \-e line 1\.
Attempt to free unreferenced scalar at \-e line 1\.
\.\.\.\.about 50 lines more of this\.\.\.
Attempt to free unreferenced scalar at \-e line 1\.
Segmentation fault

$ perl5\.005\_03 \-wle 'splice @&#8203;x\, 1\, 1 for @&#8203;x = qw\(a b c d e f g\)'
Attempt to free unreferenced scalar at \-e line 1\.
Attempt to free unreferenced scalar at \-e line 1\.
Segmentation fault


Here's the back trace&#8203;:

\#0  0x100928f8 in Perl\_mg\_free \(sv=0x10199e78\) at mg\.c&#8203;:344
\#1  0x100c28d4 in Perl\_sv\_clear \(sv=0x10199e78\) at sv\.c&#8203;:4927
\#2  0x100c30b0 in Perl\_sv\_free \(sv=0x10199e78\) at sv\.c&#8203;:5130
\#3  0x100ae214 in Perl\_pp\_iter \(\) at pp\_hot\.c&#8203;:1830
\#4  0x10088c60 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1391
\#5  0x10018b8c in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1602
\#6  0x10018564 in perl\_run \(my\_perl=0x10199408\) at perl\.c&#8203;:1523
\#7  0x10013e18 in main \(argc=3\, argv=0x7ffffb54\, env=0x7ffffb64\)
&nbsp;    at perlmain\.c&#8203;:76
\#8  0x0fdd8a30 in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6


\-\- 

Michael G\. Schwern   \<schwern@&#8203;pobox\.com>    http&#8203;://www\.pobox\.com/~schwern/
Perl Quality Assurance        \<perl\-qa@&#8203;perl\.org>           Kwalitee Is Job One
Monkey tennis

**Comment by p5pRT** [comment]
### From @jhi

On Thu\, Dec 20\, 2001 at 10&#8203;:15&#8203;:38PM \-0500\, Michael G Schwern wrote&#8203;:
> On Fri\, Dec 21\, 2001 at 12&#8203;:37&#8203;:46AM \-0000\, me\-01@&#8203;ton\.iguana\.be wrote&#8203;:
> > perl \-wle 'splice @&#8203;x\, 1\, 1 for @&#8203;x = qw\(a b c d e f g\)'
> > 
> > gives&#8203;:
> > Unhandled exception in file mg\.c\, line 318&#8203;: Assertion failed \(You should never see this\) myFree\(\#0x21\, mg\.c\, 318\) \(free\(\#0x21\)\) cannot possibly refer to valid malloced memory&#8203;: Success
> 
> That's a nasty one you've got there\.

Not that this shouldn't be fixed\-\- but what was the expected result?
If one is modifying the list one is iterating over\, I'm a little bit
confused as to what is the correct behaviour\.

> $ bleadperl@&#8203;13745 \-wle 'splice @&#8203;x\, 1\, 1 for @&#8203;x = qw\(a b c d e f g\)'
> Segmentation fault
> 
> $ perl5\.6\.1 \-wle 'splice @&#8203;x\, 1\, 1 for @&#8203;x = qw\(a b c d e f g\)'
> Segmentation fault
> 
> $ perl5\.6\.0 \-wle 'splice @&#8203;x\, 1\, 1 for @&#8203;x = qw\(a b c d e f g\)'
> Attempt to free unreferenced scalar at \-e line 1\.
> Attempt to free unreferenced scalar at \-e line 1\.
> \.\.\.\.about 50 lines more of this\.\.\.
> Attempt to free unreferenced scalar at \-e line 1\.
> Segmentation fault
> 
> $ perl5\.005\_03 \-wle 'splice @&#8203;x\, 1\, 1 for @&#8203;x = qw\(a b c d e f g\)'
> Attempt to free unreferenced scalar at \-e line 1\.
> Attempt to free unreferenced scalar at \-e line 1\.
> Segmentation fault
> 
> 
> Here's the back trace&#8203;:
> 
> \#0  0x100928f8 in Perl\_mg\_free \(sv=0x10199e78\) at mg\.c&#8203;:344
> \#1  0x100c28d4 in Perl\_sv\_clear \(sv=0x10199e78\) at sv\.c&#8203;:4927
> \#2  0x100c30b0 in Perl\_sv\_free \(sv=0x10199e78\) at sv\.c&#8203;:5130
> \#3  0x100ae214 in Perl\_pp\_iter \(\) at pp\_hot\.c&#8203;:1830
> \#4  0x10088c60 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1391
> \#5  0x10018b8c in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1602
> \#6  0x10018564 in perl\_run \(my\_perl=0x10199408\) at perl\.c&#8203;:1523
> \#7  0x10013e18 in main \(argc=3\, argv=0x7ffffb54\, env=0x7ffffb64\)
>     at perlmain\.c&#8203;:76
> \#8  0x0fdd8a30 in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6
> 
> 
> \-\- 
> 
> Michael G\. Schwern   \<schwern@&#8203;pobox\.com>    http&#8203;://www\.pobox\.com/~schwern/
> Perl Quality Assurance        \<perl\-qa@&#8203;perl\.org>           Kwalitee Is Job One
> Monkey tennis

\-\- 
$jhi\+\+; \# http&#8203;://www\.iki\.fi/jhi/
&nbsp;        \# There is this special biologist word we use for 'stable'\.
&nbsp;        \# It is 'dead'\. \-\- Jack Cohen

**Comment by p5pRT** [comment]
### From @schwern

On Fri\, Dec 21\, 2001 at 05&#8203;:46&#8203;:09AM \+0200\, Jarkko Hietaniemi wrote&#8203;:
> Not that this shouldn't be fixed\-\- but what was the expected result?
> If one is modifying the list one is iterating over\, I'm a little bit
> confused as to what is the correct behaviour\.
> 
> > $ bleadperl@&#8203;13745 \-wle 'splice @&#8203;x\, 1\, 1 for @&#8203;x = qw\(a b c d e f g\)'
> > Segmentation fault

Same as this?

$ bleadperl \-wle '@&#8203;x = qw\(a b c d e f g\);  for \(@&#8203;x\) \{ splice @&#8203;x\, 1\, 1 \}  print @&#8203;x' 
afg


\-\- 

Michael G\. Schwern   \<schwern@&#8203;pobox\.com>    http&#8203;://www\.pobox\.com/~schwern/
Perl Quality Assurance        \<perl\-qa@&#8203;perl\.org>           Kwalitee Is Job One
Lord of Kwalitee\!  Wearer of the CPANTS and Slayer of Pseudo\-hashes\!

**Comment by p5pRT** [comment]
### From @mjdominus


Jarkko says&#8203;:
> Not that this shouldn't be fixed\-\- but what was the expected result?
> If one is modifying the list one is iterating over\, I'm a little bit
> confused as to what is the correct behaviour\.

I don't know what the 'correct' behavior is\.  But in every other case
I'm familiar with\, the behavior is easily described&#8203;: First you get the
first element of the list\, then the second\, and so on\, where 'first'\,
'second'\, etc\. are evaluated at the start of the iteration\.  So for
example&#8203;:

&nbsp;        @&#8203;a = \(1\,2\,3\);
&nbsp;        for \(@&#8203;a\) \{
&nbsp;          print;
&nbsp;          shift @&#8203;a;
&nbsp;        \}

This prints "13"\, because on the second iteration\, the array is \(2\,3\)
and the second element is 3\.

Then the loop exits at the start of the first iteration for which the
iteration number is larger than the length of the array\.  The loop
above stops just before the third iteration; the loop below is
infinite&#8203;:

&nbsp;        @&#8203;a = \(1\,2\,3\);
&nbsp;        for \(@&#8203;a\) \{
&nbsp;          print;
&nbsp;          push @&#8203;a\, 7;
&nbsp;        \}

This emits 1237777777\.\.\.

Compare&#8203;:

&nbsp;        @&#8203;a = \(1\,2\,3\);
&nbsp;        for \(@&#8203;a\) \{
&nbsp;          print;
&nbsp;          unshift @&#8203;a\, 7;
&nbsp;        \}

which emits 111111\.\.\.\.  because on iteration \#n\, element $a\[n\] always
contains the 1\.

If this rule is to hold\, then the example program&#8203;:

> > $ bleadperl@&#8203;13745 \-wle 'splice @&#8203;x\, 1\, 1 for @&#8203;x = qw\(a b c d e f g\)'
> > Segmentation fault

This should have set $\_ successively to  'a'\, 'c'\, 'e'\, 'g'\, splicing
out 'b'\, 'c'\, 'd'\, 'e'\, leaving @&#8203;x = \('a'\, 'f'\, 'g'\)\.

Hope this helps\.

**Comment by p5pRT** [comment]
### From @jhi

On Thu\, Dec 20\, 2001 at 10&#8203;:51&#8203;:06PM \-0500\, Michael G Schwern wrote&#8203;:
> On Fri\, Dec 21\, 2001 at 05&#8203;:46&#8203;:09AM \+0200\, Jarkko Hietaniemi wrote&#8203;:
> > Not that this shouldn't be fixed\-\- but what was the expected result?
> > If one is modifying the list one is iterating over\, I'm a little bit
> > confused as to what is the correct behaviour\.
> > 
> > > $ bleadperl@&#8203;13745 \-wle 'splice @&#8203;x\, 1\, 1 for @&#8203;x = qw\(a b c d e f g\)'
> > > Segmentation fault
> 
> Same as this?
> 
> $ bleadperl \-wle '@&#8203;x = qw\(a b c d e f g\);  for \(@&#8203;x\) \{ splice @&#8203;x\, 1\, 1 \}  print @&#8203;x' 
> afg

So the said loop is a "crafty" way of saying
&nbsp;    
&nbsp;    splice @&#8203;x\, 1\, \(@&#8203;x\+1\)/2;

:\-\)

\-\- 
$jhi\+\+; \# http&#8203;://www\.iki\.fi/jhi/
&nbsp;        \# There is this special biologist word we use for 'stable'\.
&nbsp;        \# It is 'dead'\. \-\- Jack Cohen

**Comment by p5pRT** [comment]
### From @jhi

On Thu\, Dec 20\, 2001 at 11&#8203;:07&#8203;:45PM \-0500\, Mark\-Jason Dominus wrote&#8203;:
> 
> Jarkko says&#8203;:
> > Not that this shouldn't be fixed\-\- but what was the expected result?
> > If one is modifying the list one is iterating over\, I'm a little bit
> > confused as to what is the correct behaviour\.
> 
> I don't know what the 'correct' behavior is\.  But in every other case
> I'm familiar with\, the behavior is easily described&#8203;: First you get the
> first element of the list\, then the second\, and so on\, where 'first'\,
> 'second'\, etc\. are evaluated at the start of the iteration\.  So for
> example&#8203;:
> 
>         @&#8203;a = \(1\,2\,3\);
>         for \(@&#8203;a\) \{
>           print;
>           shift @&#8203;a;
>         \}
> 
> This prints "13"\, because on the second iteration\, the array is \(2\,3\)
> and the second element is 3\.
> 
> Then the loop exits at the start of the first iteration for which the
> iteration number is larger than the length of the array\.  The loop
> above stops just before the third iteration; the loop below is
> infinite&#8203;:
> 
>         @&#8203;a = \(1\,2\,3\);
>         for \(@&#8203;a\) \{
>           print;
>           push @&#8203;a\, 7;
>         \}
> 
> This emits 1237777777\.\.\.
> 
> Compare&#8203;:
> 
>         @&#8203;a = \(1\,2\,3\);
>         for \(@&#8203;a\) \{
>           print;
>           unshift @&#8203;a\, 7;
>         \}
> 
> which emits 111111\.\.\.\.  because on iteration \#n\, element $a\[n\] always
> contains the 1\.

Thanks\.  But thanks to the last two examples I now remember why I
think anyone wanting to modify iteration lists like that should think
again\.  \(Unless\, of course\, endless loop is the goal\.\)

\-\- 
$jhi\+\+; \# http&#8203;://www\.iki\.fi/jhi/
&nbsp;        \# There is this special biologist word we use for 'stable'\.
&nbsp;        \# It is 'dead'\. \-\- Jack Cohen

**Comment by p5pRT** [comment]
### From @abigail

On Fri\, Dec 21\, 2001 at 06&#8203;:17&#8203;:27AM \+0200\, Jarkko Hietaniemi wrote&#8203;:
> 
> Thanks\.  But thanks to the last two examples I now remember why I
> think anyone wanting to modify iteration lists like that should think
> again\.  \(Unless\, of course\, endless loop is the goal\.\)


Or JAPHs\.  But I didn't say that\.



Abigail

**Comment by p5pRT** [comment]
### From @iabyn

"perldoc perlsyn" says

&nbsp;     If any part of LIST is an array\, \`foreach' will get very
&nbsp;     confused if you add or remove elements within the loop body\,
&nbsp;     for example with \`splice'\.   So don't do that\.

Does this let us off the hook of having to fix such bugs ? :\-\)

**Comment by p5pRT** [comment]
### From @tux

On Fri 21 Dec 2001 13&#8203;:15\, Dave Mitchell \<davem@&#8203;fdgroup\.co\.uk> wrote&#8203;:
> "perldoc perlsyn" says
> 
>      If any part of LIST is an array\, \`foreach' will get very
>      confused if you add or remove elements within the loop body\,
>      for example with \`splice'\.   So don't do that\.
> 
> Does this let us off the hook of having to fix such bugs ? :\-\)

Not if they cause core dumps\.

\-\- 
H\.Merijn Brand        Amsterdam Perl Mongers \(http&#8203;://amsterdam\.pm\.org/\)
using perl\-5\.6\.1\, 5\.7\.2 & 630 on HP\-UX 10\.20 & 11\.00\, AIX 4\.2\, AIX 4\.3\,
&nbsp;  WinNT 4\, Win2K pro & WinCE 2\.11\.  Smoking perl CORE&#8203;: smokers@&#8203;perl\.org
http&#8203;://archives\.develooper\.com/daily\-build@&#8203;perl\.org/   perl\-qa@&#8203;perl\.org
send smoke reports to&#8203;: smokers\-reports@&#8203;perl\.org\, QA&#8203;: http&#8203;://qa\.perl\.org

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Dave Mitchell wrote&#8203;:
> 
> "perldoc perlsyn" says
> 
>      If any part of LIST is an array\, \`foreach' will get very
>      confused if you add or remove elements within the loop body\,
>      for example with \`splice'\.   So don't do that\.
> 
> Does this let us off the hook of having to fix such bugs ? :\-\)

All that we're off the hook in terms of making the foreach execute in
any particular order\.\.\. 

We really really should fix perl so that the OP's code doesn't print a
wierd funky error such as it did\, and more important\, so that it doesn't
make bleadperl segfault\.  \(And we should think about providing a patch
to 5\.6 to fix it there\, too\)

\-\- 
Klein bottle for rent \- inquire within\.

**Comment by p5pRT** [comment]
### From @schwern

This appears to have been fixed in so much as it doesn't core dump and
displays the proper error\.

$ perl5\.8\.1 \-wle 'splice @&#8203;x\, 1\, 1 for @&#8203;x = qw\(a b c d e f g\)'
Use of freed value in iteration \(perhaps you modified the iterated array
within the loop?\) at \-e line 1\.

**Comment by p5pRT** [comment]
@schwern - Status changed from 'open' to 'resolved'
