### ISSUE TITLE
Garbage warning

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4796]
Migrated from [rt.perl.org#8193](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=8193) (status was 'resolved')

Searchable as RT8193$

**Comment by p5pRT** [comment]
### From @gisle

#### Created by gisle@caliper.activestate.com



I make a module called 'A\.pm' and put something like this in it&#8203;:

&nbsp;  \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
&nbsp;  package A;
&nbsp;  print FOO "bar\\n";
&nbsp;  1;
&nbsp;  \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

Then\, if I load it like this&#8203;:

&nbsp;  perl \-w \-MA \-e1

I see this error message&#8203;:

&nbsp;  Name "A&#8203;::FOO" used only once&#8203;: possible typo at \*\*\*\*\*A\.pmc line 2\.

where "\*\*\*\*\*" is just some random garbage\.  There is also an extra
"c" added to the module name but that might just be part of the
prefix garbage\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.7.2:

Configured by gisle at Mon Dec 31 10:12:57 PST 2001.

Summary of my perl5 (revision 5.0 version 7 subversion 2 patch 13982) configuration:
  Platform:
    osname=linux, osvers=2.4.7-10, archname=i686-linux-thread-multi
    uname='linux caliper.activestate.com 2.4.7-10 #1 thu sep 6 17:27:27 edt 2001 i686 unknown '
    config_args='-Dprefix=/local/perl/13942-thr -Dusedevel -Uversiononly -Dusethreads -Doptimize=-g -ders'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -DDEBUGGING -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-g',
    cppflags='-D_REENTRANT -DDEBUGGING -fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='2.96 20000731 (Red Hat Linux 7.1 2.96-98)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lgdbm -ldb -ldl -lm -lpthread -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lpthread -lc -lcrypt -lutil
    libc=/lib/libc-2.2.4.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    DEVEL13942


@INC for perl v5.7.2:
    /local/perl/13942-thr/lib/5.7.2/i686-linux-thread-multi
    /local/perl/13942-thr/lib/5.7.2
    /local/perl/13942-thr/lib/site_perl/5.7.2/i686-linux-thread-multi
    /local/perl/13942-thr/lib/site_perl/5.7.2
    /local/perl/13942-thr/lib/site_perl
    .


Environment for perl v5.7.2:
    HOME=/home/gisle
    LANG=en_US
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/gisle/bin:/local/perl/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash


```
</details>

**Comment by p5pRT** [comment]
### From @rspier



I can't reproduce this with a newer perl\-snap\.  Are you still seeing
it\, Gisle?

$ \.\./perl\-snap\-thr/bin/perl \-w \-MA \-e1
print\(\) on unopened filehandle A&#8203;::FOO at A\.pm line 2\.
Name "A&#8203;::FOO" used only once&#8203;: possible typo at \-e line 2\.

Summary of my perl5 \(revision 5\.0 version 7 subversion 2 patch 14190\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.4\.2\-2\, archname=i686\-linux\-thread\-multi
&nbsp;    config\_args='\-Dprefix=/home/rspier/perl\-snap\-thr \-Dusedevel \-Uversiononly \-Dusethreads \-Doptimize=\-g \-ders'


Gisle Aas writes&#8203;:
>I make a module called 'A\.pm' and put something like this in it&#8203;:
>  \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
>  package A;
>  print FOO "bar\\n";
>  1;
>  \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
>Then\, if I load it like this&#8203;:
>  perl \-w \-MA \-e1
>I see this error message&#8203;:
>  Name "A&#8203;::FOO" used only once&#8203;: possible typo at \*\*\*\*\*A\.pmc line 2\.
>where "\*\*\*\*\*" is just some random garbage\.  There is also an extra
>"c" added to the module name but that might just be part of the
>prefix garbage\.
>
>\[Please do not change anything below this line\]
>\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
>\-\-\-
>Flags&#8203;:
>    category=core
>    severity=low
>\-\-\-
>Site configuration information for perl v5\.7\.2&#8203;:
>
>Configured by gisle at Mon Dec 31 10&#8203;:12&#8203;:57 PST 2001\.
>
>Summary of my perl5 \(revision 5\.0 version 7 subversion 2 patch 13982\) configuration&#8203;:
>  Platform&#8203;:
>    osname=linux\, osvers=2\.4\.7\-10\, archname=i686\-linux\-thread\-multi
>    uname='linux caliper\.activestate\.com 2\.4\.7\-10 \#1 thu sep 6 17&#8203;:27&#8203;:27 edt 2001 i686 unknown '
>    config\_args='\-Dprefix=/local/perl/13942\-thr \-Dusedevel \-Uversiononly \-Dusethreads \-Doptimize=\-g \-ders'

**Comment by p5pRT** [comment]
### From @gisle

Robert Spier \<rspier@&#8203;pobox\.com> writes&#8203;:

> I can't reproduce this with a newer perl\-snap\.  Are you still seeing
> it\, Gisle?
> 
> $ \.\./perl\-snap\-thr/bin/perl \-w \-MA \-e1
> print\(\) on unopened filehandle A&#8203;::FOO at A\.pm line 2\.
> Name "A&#8203;::FOO" used only once&#8203;: possible typo at \-e line 2\.
&nbsp;                                                 ^^
&nbsp;                                                 why isn't this 'A\.pm'?

The garbage output change for me if I load more modules\.  Try&#8203;:

&nbsp;   perl \-w \-MFile&#8203;::Path \-MA \-e1

\[I'm compiling myself a brand new perl now\.\.\.\]

\-\-Gisle


> Summary of my perl5 \(revision 5\.0 version 7 subversion 2 patch 14190\) configuration&#8203;:
>   Platform&#8203;:
>     osname=linux\, osvers=2\.4\.2\-2\, archname=i686\-linux\-thread\-multi
>     config\_args='\-Dprefix=/home/rspier/perl\-snap\-thr \-Dusedevel \-Uversiononly \-Dusethreads \-Doptimize=\-g \-ders'
> 
> 
> Gisle Aas writes&#8203;:
> >I make a module called 'A\.pm' and put something like this in it&#8203;:
> >  \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> >  package A;
> >  print FOO "bar\\n";
> >  1;
> >  \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> >Then\, if I load it like this&#8203;:
> >  perl \-w \-MA \-e1
> >I see this error message&#8203;:
> >  Name "A&#8203;::FOO" used only once&#8203;: possible typo at \*\*\*\*\*A\.pmc line 2\.
> >where "\*\*\*\*\*" is just some random garbage\.  There is also an extra
> >"c" added to the module name but that might just be part of the
> >prefix garbage\.
> >
> >\[Please do not change anything below this line\]
> >\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> >\-\-\-
> >Flags&#8203;:
> >    category=core
> >    severity=low
> >\-\-\-
> >Site configuration information for perl v5\.7\.2&#8203;:
> >
> >Configured by gisle at Mon Dec 31 10&#8203;:12&#8203;:57 PST 2001\.
> >
> >Summary of my perl5 \(revision 5\.0 version 7 subversion 2 patch 13982\) configuration&#8203;:
> >  Platform&#8203;:
> >    osname=linux\, osvers=2\.4\.7\-10\, archname=i686\-linux\-thread\-multi
> >    uname='linux caliper\.activestate\.com 2\.4\.7\-10 \#1 thu sep 6 17&#8203;:27&#8203;:27 edt 2001 i686 unknown '
> >    config\_args='\-Dprefix=/local/perl/13942\-thr \-Dusedevel \-Uversiononly \-Dusethreads \-Doptimize=\-g \-ders'

**Comment by p5pRT** [comment]
### From @rspier

Gisle Aas writes&#8203;:
>> $ \.\./perl\-snap\-thr/bin/perl \-w \-MA \-e1
>> print\(\) on unopened filehandle A&#8203;::FOO at A\.pm line 2\.
>> Name "A&#8203;::FOO" used only once&#8203;: possible typo at \-e line 2\.
>                                                 ^^
>                                                 why isn't this 'A\.pm'?
>
>The garbage output change for me if I load more modules\.  Try&#8203;:
>   perl \-w \-MFile&#8203;::Path \-MA \-e1

Ahh\.  Now I see it\, I was just blind before\.  This is somehow related to
\-Dusethreads

Anyway\- 
&nbsp;    The memory holding the filename \(gv\->sv\_any\->xgv\_gp\->gp\_file\) gets
&nbsp;    freed during the leave\_scope\, but the error isn't printed till
&nbsp;    afterwards\.

This is about as far as I can take this\.  Hope this helps someone
else\.

\-R

\#0  Perl\_safesysfree \(where=0x8190b70\) at util\.c&#8203;:153
\#1  0x08108f1b in Perl\_leave\_scope \(my\_perl=0x81813c8\, base=156\) at
\#scope\.c&#8203;:656
\#2  0x0810736b in Perl\_pop\_scope \(my\_perl=0x81813c8\) at scope\.c&#8203;:129
\#3  0x080d730f in Perl\_pp\_leavesub \(my\_perl=0x81813c8\) at
\#pp\_hot\.c&#8203;:2242
\#4  0x080b94a3 in Perl\_runops\_debug \(my\_perl=0x81813c8\) at dump\.c&#8203;:1392
\#5  0x08064dd8 in S\_call\_body \(my\_perl=0x81813c8\, myop=0xbffff460\,
\#is\_eval=0\)
&nbsp;    at perl\.c&#8203;:1982
\#6  0x08064982 in Perl\_call\_sv \(my\_perl=0x81813c8\, sv=0x818d4d4\,
\#flags=6\)
&nbsp;    at perl\.c&#8203;:1900
\#7  0x08068f55 in S\_call\_list\_body \(my\_perl=0x81813c8\, cv=0x818d4d4\)
&nbsp;    at perl\.c&#8203;:3978
\#8  0x08068a5e in Perl\_call\_list \(my\_perl=0x81813c8\, oldscope=2\, 
&nbsp;    paramList=0x818d558\) at perl\.c&#8203;:3906
\#9  0x0809ea8b in Perl\_newATTRSUB \(my\_perl=0x81813c8\, floor=109\,
\#o=0x8190520\, 
&nbsp;    proto=0x0\, attrs=0x0\, block=0x81904e8\) at op\.c&#8203;:5076
\#10 0x08099999 in Perl\_utilize \(my\_perl=0x81813c8\, aver=1\, floor=109\, 
&nbsp;    version=0x0\, id=0x8189d48\, arg=0x0\) at op\.c&#8203;:3430
\#11 0x0808e753 in Perl\_yyparse \(my\_perl=0x81813c8\) at perly\.y&#8203;:414
\#12 0x0806362e in S\_parse\_body \(my\_perl=0x81813c8\, env=0x0\, 
&nbsp;    xsinit=0x805f354 \<xs\_init>\) at perl\.c&#8203;:1458
\#13 0x08062709 in perl\_parse \(my\_perl=0x81813c8\, xsinit=0x805f354
\#\<xs\_init>\, 
&nbsp;    argc=4\, argv=0xbffff91c\, env=0x0\) at perl\.c&#8203;:1001
\#14 0x0805f2dd in main \(argc=4\, argv=0xbffff91c\, env=0xbffff930\)

**Comment by p5pRT** [comment]
### From @smpeters

> \[RT\_System \- Sat Jan 12 14&#8203;:58&#8203;:18 2002\]&#8203;:
> 
> Gisle Aas writes&#8203;:
> >> $ \.\./perl\-snap\-thr/bin/perl \-w \-MA \-e1
> >> print\(\) on unopened filehandle A&#8203;::FOO at A\.pm line 2\.
> >> Name "A&#8203;::FOO" used only once&#8203;: possible typo at \-e line 2\.
> >                                                 ^^
> >                                                 why isn't this 'A\.pm'?
> >
> >The garbage output change for me if I load more modules\.  Try&#8203;:
> >   perl \-w \-MFile&#8203;::Path \-MA \-e1
> 
> Ahh\.  Now I see it\, I was just blind before\.  This is somehow related to
> \-Dusethreads
> 
> Anyway\- 
>     The memory holding the filename \(gv\->sv\_any\->xgv\_gp\->gp\_file\) gets
>     freed during the leave\_scope\, but the error isn't printed till
>     afterwards\.
> 
> This is about as far as I can take this\.  Hope this helps someone
> else\.
> 

It appears that someone\, or just ithreads\, have fixed this problem\.

\[spock&#8203;:\~\] steve% perl \-w \-MA \-e1
print\(\) on unopened filehandle FOO at A\.pm line 2\.
Name "A&#8203;::FOO" used only once&#8203;: possible typo at  line 2\.

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'resolved'
