### ISSUE TITLE
[BUG 5.005_03 and 5.005_61 mg.c] POPSTACK panic at line 1126

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#485]
Migrated from [rt.perl.org#1327](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=1327) (status was 'resolved')

Searchable as RT1327$

**Comment by p5pRT** [comment]
### From @schwern

ok 274
panic&#8203;: POPSTACK at \#1126\, mg\.c

In the Perl code\, the panic occurs at a fairly mundane place&#8203;:
&nbsp;    push @&#8203;&#8203;::failed\, $ok\_count  unless $\_\[0\];

I dug into the code and found out its failing at the POPSTACK macro
call in mg\.c at line 1126\.  Reason?  PL\_curstackinfo\->si\_prev is
empty\.  Not being very adept with gdb\, I can't elaborate much further\,
but I can provide a backtrace for what its worth&#8203;:

\[This is immediately before POPSTACK is called\]

\#0  Perl\_magic\_wipepack \(sv=0x818b0b0\, mg=0x81e6b08\) at mg\.c&#8203;:1126
\#1  0x80a10bb in Perl\_mg\_clear \(sv=0x818b0b0\) at mg\.c&#8203;:219
\#2  0x80a85c9 in Perl\_hv\_clear \(hv=0x818b0b0\) at hv\.c&#8203;:956
\#3  0x80ae959 in Perl\_pp\_aassign \(\) at pp\_hot\.c&#8203;:680
\#4  0x80abbee in Perl\_runops\_debug \(\) at run\.c&#8203;:57
\#5  0x80e0df3 in S\_docatch\_body \(args=0xbffff42c\) at pp\_ctl\.c&#8203;:2418
\#6  0x80d532e in Perl\_vdefault\_protect \(excpt=0xbffff448\, 
&nbsp;    body=0x80e0de4 \<S\_docatch\_body>\, args=0xbffff414\) at scope\.c&#8203;:44
\#7  0x80d5260 in Perl\_default\_protect \(excpt=0xbffff448\, 
&nbsp;    body=0x80e0de4 \<S\_docatch\_body>\) at scope\.c&#8203;:25
\#8  0x80e0e5c in S\_docatch \(o=0x81a2f48\) at pp\_ctl\.c&#8203;:2434
\#9  0x80e3a54 in Perl\_pp\_entertry \(\) at pp\_ctl\.c&#8203;:3167
\#10 0x80abbee in Perl\_runops\_debug \(\) at run\.c&#8203;:57
\#11 0x805cecd in S\_call\_xbody \(myop=0xbffff518\, is\_eval=0\) at perl\.c&#8203;:1347
\#12 0x805c87e in perl\_call\_sv \(sv=0x819e3c8\, flags=2\) at perl\.c&#8203;:1235
\#13 0x805c67d in perl\_call\_method \(methname=0x8116b38 "CLEAR"\, flags=2\)
&nbsp;    at perl\.c&#8203;:1182
\#14 0x80a3806 in Perl\_magic\_wipepack \(sv=0x818b0b0\, mg=0x81e6b08\) at mg\.c&#8203;:1125
\#15 0x80a10bb in Perl\_mg\_clear \(sv=0x818b0b0\) at mg\.c&#8203;:219
\#16 0x80a85c9 in Perl\_hv\_clear \(hv=0x818b0b0\) at hv\.c&#8203;:956
\#17 0x80ae959 in Perl\_pp\_aassign \(\) at pp\_hot\.c&#8203;:680
\#18 0x80abbee in Perl\_runops\_debug \(\) at run\.c&#8203;:57
\#19 0x80e0df3 in S\_docatch\_body \(args=0xbffff7dc\) at pp\_ctl\.c&#8203;:2418
\#20 0x80d532e in Perl\_vdefault\_protect \(excpt=0xbffff7f8\, 
&nbsp;    body=0x80e0de4 \<S\_docatch\_body>\, args=0xbffff7c4\) at scope\.c&#8203;:44
\#21 0x80d5260 in Perl\_default\_protect \(excpt=0xbffff7f8\, 
&nbsp;    body=0x80e0de4 \<S\_docatch\_body>\) at scope\.c&#8203;:25
\#22 0x80e0e5c in S\_docatch \(o=0x81e7088\) at pp\_ctl\.c&#8203;:2434
\#23 0x80e2e25 in Perl\_pp\_require \(\) at pp\_ctl\.c&#8203;:3007
\#24 0x80abbee in Perl\_runops\_debug \(\) at run\.c&#8203;:57
\#25 0x805cecd in S\_call\_xbody \(myop=0xbffff938\, is\_eval=0\) at perl\.c&#8203;:1347
\#26 0x805c87e in perl\_call\_sv \(sv=0x819e17c\, flags=2\) at perl\.c&#8203;:1235
\#27 0x805c67d in perl\_call\_method \(methname=0x8116b21 "STORE"\, flags=2\)
&nbsp;    at perl\.c&#8203;:1182
\#28 0x80a2dae in S\_magic\_methcall \(sv=0x81a25e8\, mg=0x81e6bc8\, 
&nbsp;    meth=0x8116b21 "STORE"\, flags=2\, n=3\, val=0x81a25e8\) at mg\.c&#8203;:1046
\#29 0x80a3208 in Perl\_magic\_setpack \(sv=0x81a25e8\, mg=0x81e6bc8\) at mg\.c&#8203;:1083
\#30 0x80a0e50 in Perl\_mg\_set \(sv=0x81a25e8\) at mg\.c&#8203;:140
\#31 0x80ac390 in Perl\_pp\_sassign \(\) at pp\_hot\.c&#8203;:124
\#32 0x80abbee in Perl\_runops\_debug \(\) at run\.c&#8203;:57
\#33 0x805c279 in S\_run\_body \(args=0xbffffbf0\) at perl\.c&#8203;:1072
\#34 0x80d532e in Perl\_vdefault\_protect \(excpt=0xbffffc14\, 
&nbsp;    body=0x805c10c \<S\_run\_body>\, args=0xbffffbd4\) at scope\.c&#8203;:44
\#35 0x80d5260 in Perl\_default\_protect \(excpt=0xbffffc14\, 
&nbsp;    body=0x805c10c \<S\_run\_body>\) at scope\.c&#8203;:25
\#36 0x805bed7 in perl\_run \(my\_perl=0x8128808\) at perl\.c&#8203;:1005
\#37 0x8059735 in main \(argc=3\, argv=0xbffffcb4\, env=0xbffffcc4\)
&nbsp;    at perlmain\.c&#8203;:53

\*PL\_curstackinfo is&#8203;:
\{si\_stack = 0x8129038\, si\_cxstack = 0x812b808\, si\_cxix = \-1\, 
&nbsp;  si\_cxmax = 105\, si\_type = 1\, si\_prev = 0x0\, si\_next = 0x8134208\, 
&nbsp;  si\_markbase = 0x812d808\}

The same result has been seen on Slackware \(5\.005\_02\, libc5\)\, Debian
Potato \(5\.005\_61 and 5\.005\_03\, glibc2\.1\)\, Solaris 2\.5\.1 \(5\.005\_03\) and
Digital Unix \(5\.004\_03\)\.


\[This is the perl \-V for the Debian machine\]
Summary of my perl5 \(5\.0 patchlevel 5 subversion 3\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.2\.7\, archname=i686\-linux
&nbsp;    uname='linux athens 2\.2\.7 \#2 smp mon may 10 23&#8203;:17&#8203;:01 edt 1999 i686 unknown '
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef useperlio=undef d\_sfio=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'\, optimize='\-O6'\, gccversion=egcs\-2\.91\.66 19990314 \(egcs\-1\.1\.2 release\)
&nbsp;    cppflags='\-Dbool=char \-DHAS\_BOOL \-I/usr/local/include'
&nbsp;    ccflags ='\-Dbool=char \-DHAS\_BOOL \-I/usr/local/include'
&nbsp;    stdchar='char'\, d\_stdstdio=undef\, usevfork=false
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    alignbytes=4\, usemymalloc=y\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='gcc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-lndbm \-lgdbm \-ldbm \-ldb \-ldl \-lm \-lc \-lposix \-lcrypt
&nbsp;    libc=\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
&nbsp;    cccdlflags='\-fpic'\, lddlflags='\-shared \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Built under linux
&nbsp;  Compiled at Jul 29 1999 00&#8203;:29&#8203;:00
&nbsp;  %ENV&#8203;:
&nbsp;    PERL5LIB="/home/schwern/lib/perl5/site\_perl/5\.005"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /home/schwern/lib/perl5/site\_perl/5\.005/i686\-linux
&nbsp;    /home/schwern/lib/perl5/site\_perl/5\.005
&nbsp;    /usr/lib/perl5/i686\-linux
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/lib/perl5/site\_perl/5\.005/i686\-linux
&nbsp;    /usr/lib/perl5/site\_perl/5\.005
&nbsp;    \.

\-\- 

Michael G Schwern                                           schwern@&#8203;pobox\.com
&nbsp;                    http&#8203;://www\.pobox\.com/~schwern
&nbsp;     /\(?&#8203;:\(?&#8203;:\(1\)\[\.\-\]?\)?\\\(?\(\\d\{3\}\)\\\)?\[\.\-\]?\)?\(\\d\{3\}\)\[\.\-\]?\(\\d\{4\}\)\(x\\d\+\)?/i

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Michael G Schwern \<schwern@&#8203;pobox\.com> writes&#8203;:
>While testing Tie&#8203;::SecureHash 1\.02 I get a "panic&#8203;: POPSTACK" during testing&#8203;:
>
>ok 274
>panic&#8203;: POPSTACK at \#1126\, mg\.c

You have my sympathy\. It took ages to track down something similar 
which was a side effect of $SIG\{\_\_DIE\_\_\} inside an implied eval \{\} of 
a require\. The snag in my case was that the stack switch for the 
handler was undone by the unwind for the eval \{\}\. And then eval longjmp\(\)'ed
to somewhere that attempted the popstack\. The snag in that case was 
that the DIE handler was using perl\_call\_sv\(\) which set the magic flag
which caused eval \{\} code to do a new setjmp\(\) which was not really 
appropriate\. As 'magic' \(=tie\) handling also does this kind of thing 
I suspect the fail mode is similar\.

There is now \(5\.005\_61\) a G\_NOCATCH flag to pass to perl\_call\_sv\(\) which inhibits
the setjmp\(\)\.

In may case the stack trace at the 'panic' was not that helpful
as code had reached that point via a longjmp\(\)\.

The code fragment in wipepack&#8203;:

&nbsp;    PUSHSTACKi\(PERLSI\_MAGIC\);
&nbsp;    PUSHMARK\(SP\);
&nbsp;    XPUSHs\(SvTIED\_obj\(sv\, mg\)\);
&nbsp;    PUTBACK;
&nbsp;    call\_method\("CLEAR"\, G\_SCALAR|G\_DISCARD\); \# add G\_NOCATCH ?????
&nbsp;    POPSTACK;

Looks very similar\.

What ticked my case use use new lightweight of Carp in the \_\_DIE\_\_ handler
which introduced a require \(=eval \{\}\) into things\.

>
>In the Perl code\, the panic occurs at a fairly mundane place&#8203;:
>    push @&#8203;&#8203;::failed\, $ok\_count  unless $\_\[0\];
>
>I dug into the code and found out its failing at the POPSTACK macro
>call in mg\.c at line 1126\.  Reason?  PL\_curstackinfo\->si\_prev is
>empty\.  Not being very adept with gdb\, I can't elaborate much further\,
>but I can provide a backtrace for what its worth&#8203;:
>
>\[This is immediately before POPSTACK is called\]
>
>\#0  Perl\_magic\_wipepack \(sv=0x818b0b0\, mg=0x81e6b08\) at mg\.c&#8203;:1126
>\#1  0x80a10bb in Perl\_mg\_clear \(sv=0x818b0b0\) at mg\.c&#8203;:219
>\#2  0x80a85c9 in Perl\_hv\_clear \(hv=0x818b0b0\) at hv\.c&#8203;:956
>\#3  0x80ae959 in Perl\_pp\_aassign \(\) at pp\_hot\.c&#8203;:680
>\#4  0x80abbee in Perl\_runops\_debug \(\) at run\.c&#8203;:57
>\#5  0x80e0df3 in S\_docatch\_body \(args=0xbffff42c\) at pp\_ctl\.c&#8203;:2418
>\#6  0x80d532e in Perl\_vdefault\_protect \(excpt=0xbffff448\, 
>    body=0x80e0de4 \<S\_docatch\_body>\, args=0xbffff414\) at scope\.c&#8203;:44
>\#7  0x80d5260 in Perl\_default\_protect \(excpt=0xbffff448\, 
>    body=0x80e0de4 \<S\_docatch\_body>\) at scope\.c&#8203;:25
>\#8  0x80e0e5c in S\_docatch \(o=0x81a2f48\) at pp\_ctl\.c&#8203;:2434
>\#9  0x80e3a54 in Perl\_pp\_entertry \(\) at pp\_ctl\.c&#8203;:3167
>\#10 0x80abbee in Perl\_runops\_debug \(\) at run\.c&#8203;:57
>\#11 0x805cecd in S\_call\_xbody \(myop=0xbffff518\, is\_eval=0\) at perl\.c&#8203;:1347
>\#12 0x805c87e in perl\_call\_sv \(sv=0x819e3c8\, flags=2\) at perl\.c&#8203;:1235
>\#13 0x805c67d in perl\_call\_method \(methname=0x8116b38 "CLEAR"\, flags=2\)
>    at perl\.c&#8203;:1182
>\#14 0x80a3806 in Perl\_magic\_wipepack \(sv=0x818b0b0\, mg=0x81e6b08\) at mg\.c&#8203;:1125
>\#15 0x80a10bb in Perl\_mg\_clear \(sv=0x818b0b0\) at mg\.c&#8203;:219
>\#16 0x80a85c9 in Perl\_hv\_clear \(hv=0x818b0b0\) at hv\.c&#8203;:956
>\#17 0x80ae959 in Perl\_pp\_aassign \(\) at pp\_hot\.c&#8203;:680
>\#18 0x80abbee in Perl\_runops\_debug \(\) at run\.c&#8203;:57
>\#19 0x80e0df3 in S\_docatch\_body \(args=0xbffff7dc\) at pp\_ctl\.c&#8203;:2418
>\#20 0x80d532e in Perl\_vdefault\_protect \(excpt=0xbffff7f8\, 
>    body=0x80e0de4 \<S\_docatch\_body>\, args=0xbffff7c4\) at scope\.c&#8203;:44
>\#21 0x80d5260 in Perl\_default\_protect \(excpt=0xbffff7f8\, 
>    body=0x80e0de4 \<S\_docatch\_body>\) at scope\.c&#8203;:25
>\#22 0x80e0e5c in S\_docatch \(o=0x81e7088\) at pp\_ctl\.c&#8203;:2434
>\#23 0x80e2e25 in Perl\_pp\_require \(\) at pp\_ctl\.c&#8203;:3007
>\#24 0x80abbee in Perl\_runops\_debug \(\) at run\.c&#8203;:57
>\#25 0x805cecd in S\_call\_xbody \(myop=0xbffff938\, is\_eval=0\) at perl\.c&#8203;:1347
>\#26 0x805c87e in perl\_call\_sv \(sv=0x819e17c\, flags=2\) at perl\.c&#8203;:1235
>\#27 0x805c67d in perl\_call\_method \(methname=0x8116b21 "STORE"\, flags=2\)
>    at perl\.c&#8203;:1182
>\#28 0x80a2dae in S\_magic\_methcall \(sv=0x81a25e8\, mg=0x81e6bc8\, 
>    meth=0x8116b21 "STORE"\, flags=2\, n=3\, val=0x81a25e8\) at mg\.c&#8203;:1046
>\#29 0x80a3208 in Perl\_magic\_setpack \(sv=0x81a25e8\, mg=0x81e6bc8\) at mg\.c&#8203;:1083
>\#30 0x80a0e50 in Perl\_mg\_set \(sv=0x81a25e8\) at mg\.c&#8203;:140
>\#31 0x80ac390 in Perl\_pp\_sassign \(\) at pp\_hot\.c&#8203;:124
>\#32 0x80abbee in Perl\_runops\_debug \(\) at run\.c&#8203;:57
>\#33 0x805c279 in S\_run\_body \(args=0xbffffbf0\) at perl\.c&#8203;:1072
>\#34 0x80d532e in Perl\_vdefault\_protect \(excpt=0xbffffc14\, 
>    body=0x805c10c \<S\_run\_body>\, args=0xbffffbd4\) at scope\.c&#8203;:44
>\#35 0x80d5260 in Perl\_default\_protect \(excpt=0xbffffc14\, 
>    body=0x805c10c \<S\_run\_body>\) at scope\.c&#8203;:25
>\#36 0x805bed7 in perl\_run \(my\_perl=0x8128808\) at perl\.c&#8203;:1005
>\#37 0x8059735 in main \(argc=3\, argv=0xbffffcb4\, env=0xbffffcc4\)
>    at perlmain\.c&#8203;:53
>
>\*PL\_curstackinfo is&#8203;:
>\{si\_stack = 0x8129038\, si\_cxstack = 0x812b808\, si\_cxix = \-1\, 
>  si\_cxmax = 105\, si\_type = 1\, si\_prev = 0x0\, si\_next = 0x8134208\, 
>  si\_markbase = 0x812d808\}
>
>The same result has been seen on Slackware \(5\.005\_02\, libc5\)\, Debian
>Potato \(5\.005\_61 and 5\.005\_03\, glibc2\.1\)\, Solaris 2\.5\.1 \(5\.005\_03\) and
>Digital Unix \(5\.004\_03\)\.
>
>
>\[This is the perl \-V for the Debian machine\]
>Summary of my perl5 \(5\.0 patchlevel 5 subversion 3\) configuration&#8203;:
>  Platform&#8203;:
>    osname=linux\, osvers=2\.2\.7\, archname=i686\-linux
>    uname='linux athens 2\.2\.7 \#2 smp mon may 10 23&#8203;:17&#8203;:01 edt 1999 i686 unknown '
>    hint=recommended\, useposix=true\, d\_sigaction=define
>    usethreads=undef useperlio=undef d\_sfio=undef
>  Compiler&#8203;:
>    cc='gcc'\, optimize='\-O6'\, gccversion=egcs\-2\.91\.66 19990314 \(egcs\-1\.1\.2 release\)
>    cppflags='\-Dbool=char \-DHAS\_BOOL \-I/usr/local/include'
>    ccflags ='\-Dbool=char \-DHAS\_BOOL \-I/usr/local/include'
>    stdchar='char'\, d\_stdstdio=undef\, usevfork=false
>    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8
>    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
>    alignbytes=4\, usemymalloc=y\, prototype=define
>  Linker and Libraries&#8203;:
>    ld='gcc'\, ldflags =' \-L/usr/local/lib'
>    libpth=/usr/local/lib /lib /usr/lib
>    libs=\-lnsl \-lndbm \-lgdbm \-ldbm \-ldb \-ldl \-lm \-lc \-lposix \-lcrypt
>    libc=\, so=so\, useshrplib=false\, libperl=libperl\.a
>  Dynamic Linking&#8203;:
>    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
>    cccdlflags='\-fpic'\, lddlflags='\-shared \-L/usr/local/lib'
>
>
>Characteristics of this binary \(from libperl\)&#8203;: 
>  Built under linux
>  Compiled at Jul 29 1999 00&#8203;:29&#8203;:00
>  %ENV&#8203;:
>    PERL5LIB="/home/schwern/lib/perl5/site\_perl/5\.005"
>  @&#8203;INC&#8203;:
>    /home/schwern/lib/perl5/site\_perl/5\.005/i686\-linux
>    /home/schwern/lib/perl5/site\_perl/5\.005
>    /usr/lib/perl5/i686\-linux
>    /usr/lib/perl5
>    /usr/lib/perl5/site\_perl/5\.005/i686\-linux
>    /usr/lib/perl5/site\_perl/5\.005
>    \.
>
>\-\- 
>
>Michael G Schwern                                           schwern@&#8203;pobox\.com
>                    http&#8203;://www\.pobox\.com/~schwern
>     /\(?&#8203;:\(?&#8203;:\(1\)\[\.\-\]?\)?\\\(?\(\\d\{3\}\)\\\)?\[\.\-\]?\)?\(\\d\{3\}\)\[\.\-\]?\(\\d\{4\}\)\(x\\d\+\)?/i
\-\- 
Nick Ing\-Simmons \<nik@&#8203;tiuk\.ti\.com>
Via\, but not speaking for&#8203;: Texas Instruments Ltd\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Tue\, 7 Sep 1999 12&#8203;:44&#8203;:41 \+0100 \(BST\)
&nbsp;    Nick Ing\-Simmons \<nik@&#8203;tiuk\.ti\.com> wrote
&nbsp;    using tkmail\-0\.011/Perl5 Mail&#8203;::Internet v1\.32
&nbsp;  in \<199909071144\.MAA25198@&#8203;tiuk\.ti\.com>&#8203;:

>You have my sympathy\. It took ages to track down something similar 
>which was a side effect of $SIG\{\_\_DIE\_\_\} inside an implied eval \{\} of 
>a require\. 

There's been serious talk of deprecating $SIG\{\_\_DIE\_\_\}\.  People who aren't
using it for its original purpose of being something of a UNIVERSAL&#8203;::END\,
but rather to cause strange action at a distance in other people's
unrelated modules\, are just making life difficult for innocents\.

\-\-tom

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Tom Christiansen \<tchrist@&#8203;jhereg\.perl\.com> writes&#8203;:
>On Tue\, 7 Sep 1999 12&#8203;:44&#8203;:41 \+0100 \(BST\)
>    Nick Ing\-Simmons \<nik@&#8203;tiuk\.ti\.com> wrote
>    using tkmail\-0\.011/Perl5 Mail&#8203;::Internet v1\.32
>  in \<199909071144\.MAA25198@&#8203;tiuk\.ti\.com>&#8203;:
>
>>You have my sympathy\. It took ages to track down something similar 
>>which was a side effect of $SIG\{\_\_DIE\_\_\} inside an implied eval \{\} of 
>>a require\. 
>
>There's been serious talk of deprecating $SIG\{\_\_DIE\_\_\}\.  People who aren't
>using it for its original purpose of being something of a UNIVERSAL&#8203;::END\,

The case that caused the problem was the debugging code

$SIG\{\_\_DIE\_\_\} = \\&Carp&#8203;::confess;

Which is exactly in inline with the original purpose\.

>but rather to cause strange action at a distance in other people's
>unrelated modules\, are just making life difficult for innocents\.

All too true \- and personally I agree \- but this particular case 
is not one of those\. Rather it is how new\-ish stack\-switching stuff
interacts with callbacks and eval\. $SIG\{\_\_DIE\_\_\} just happened
to be the "callback" that was involved\. Apparently "tie" callbacks are 
also vulnerable\.

\-\- 
Nick Ing\-Simmons \<nik@&#8203;tiuk\.ti\.com>
Via\, but not speaking for&#8203;: Texas Instruments Ltd\.

**Comment by p5pRT** [comment]
### From @gsar

On Tue\, 07 Sep 1999 12&#8203;:44&#8203;:41 BST\, Nick Ing\-Simmons wrote&#8203;:
>Michael G Schwern \<schwern@&#8203;pobox\.com> writes&#8203;:
>>While testing Tie&#8203;::SecureHash 1\.02 I get a "panic&#8203;: POPSTACK" during testing&#8203;:
>>
>>ok 274
>>panic&#8203;: POPSTACK at \#1126\, mg\.c
>
>You have my sympathy\. It took ages to track down something similar 
>which was a side effect of $SIG\{\_\_DIE\_\_\} inside an implied eval \{\} of 
>a require\. The snag in my case was that the stack switch for the 
>handler was undone by the unwind for the eval \{\}\. And then eval longjmp\(\)'ed
>to somewhere that attempted the popstack\. The snag in that case was 
>that the DIE handler was using perl\_call\_sv\(\) which set the magic flag
>which caused eval \{\} code to do a new setjmp\(\) which was not really 
>appropriate\. As 'magic' \(=tie\) handling also does this kind of thing 
>I suspect the fail mode is similar\.
>
>There is now \(5\.005\_61\) a G\_NOCATCH flag to pass to perl\_call\_sv\(\) which inhib
>its
>the setjmp\(\)\.

This\, as we discussed during the conference\, will have other undesirable
side effects in the general case \(such as exceptions caused within an
eval in a callback ending up in the wrong "runlevel"\)\.  Most locations
that dispatch callbacks expect them to return\, and G\_NOCATCH will
prevent that\, because it allows a longjmp\(\) out of there\.  G\_NOCATCH
looks appropriate for the \_\_DIE\_\_ case because of the "unusual"
circumstances\.

This has come up several times before now\.  I'll see about working
out a proper fix\.


Sarathy
gsar@&#8203;activestate\.com

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Gurusamy Sarathy \<gsar@&#8203;activestate\.com> writes&#8203;:
>On Tue\, 07 Sep 1999 12&#8203;:44&#8203;:41 BST\, Nick Ing\-Simmons wrote&#8203;:
>>>panic&#8203;: POPSTACK at \#1126\, mg\.c
>>
>>You have my sympathy\. 

\.\.\.
>>There is now \(5\.005\_61\) a G\_NOCATCH flag to pass to perl\_call\_sv\(\) which inhib
>>its
>>the setjmp\(\)\.
>
>This\, as we discussed during the conference\, will have other undesirable
>side effects in the general case \(such as exceptions caused within an
>eval in a callback ending up in the wrong "runlevel"\)\.  

I did not mean to imply that it was a correct fix in this case\.
Most of the problem is \(as we discussed during the conference\) insufficient 
documentation on what a "runlevel" actually \_is\_\.

The sequence 

&nbsp;  PUSHSTACK;
&nbsp;  perl\_call\_sv\(\);
&nbsp;  POPSTACK;

Seems to be fatally flawed as\-now if the callback contains an eval\. 

Without NOCATCH \(or G\_EVAL\) then call\_sv forces a eval to add new setjmp\(\)\, 
when eval's unwind occurs the popstack is done\, and then longjmp\(\) returns
from the call\_sv and POPSTACK is done \_again\_\.

There are two "obvious" fixes besides the NOCATCH hack&#8203;:
1\. Stop unwind doing the POPSTACK\.
2\. Make the POPSTACK; part of the LEAVE processing 

The 3rd alternative \(since 5\.000\) which Tk has had to use is 
"always use G\_EVAL for callbacks" \- but that is significant extra
overhead that should not be needed\.


>Most locations
>that dispatch callbacks expect them to return\, and G\_NOCATCH will
>prevent that\, because it allows a longjmp\(\) out of there\.  G\_NOCATCH
>looks appropriate for the \_\_DIE\_\_ case because of the "unusual"
>circumstances\.

Agreed\.

>
>This has come up several times before now\.  I'll see about working
>out a proper fix\.
>
>
>Sarathy
>gsar@&#8203;activestate\.com
\-\- 
Nick Ing\-Simmons \<nik@&#8203;tiuk\.ti\.com>
Via\, but not speaking for&#8203;: Texas Instruments Ltd\.

**Comment by p5pRT** [comment]
### From The RT System itself

appears to have been fixed in 5\.005\_61
