### ISSUE TITLE
perl 5.6.1 segfaults (probably in parser?)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4921]
Migrated from [rt.perl.org#8355](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=8355) (status was 'resolved')

Searchable as RT8355$

**Comment by p5pRT** [comment]
### From pasky@machine.sinus.cz

#### Created by pasky@ji.cz



Hi\,

&nbsp;  when playing with some script\, I suddenly stumbled at core dump\, probably
while parsing the script \- it's easily reproducable with perl v5\.6\.1 and
script bellow&#8203;:

sub mod\_load \{
&nbsp;  my \($self\, $mod\);
&nbsp;  if \(\-r "Abcd/$mod\.pm"\) \{
&nbsp;    my $ret;
&nbsp;    use "Abcd/$mod\.pm";
&nbsp;    if \(&\{"Abcd&#8203;::"\.$mod\."\->load"\}\) \{
&nbsp;      sys\_msg\($self\, "|$mod|"\);
&nbsp;      $ret\+$mod;
&nbsp;    \}
&nbsp;    return $ret\+$mod;
&nbsp;  \} else \{
&nbsp;    sys\_msg\($self\, "ee\!"\);
&nbsp;  \}
\}

I know the use "something"; is not syntactically correct\, but dumping core
appears like too rude reaction to me\. I reduced the script as far as I was
able to\, anything further I remove will make the segfault to vanish and
ordinary syntax error complaining to appear\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.6.1:

Configured by root at Thu Aug 23 20:31:39 CEST 2001.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=linux, osvers=2.4.6, archname=i586-linux
    uname='linux machine 2.4.6 #23 sun jul 15 15:51:22 cest 2001 i586 unknown '
    config_args=''
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='gcc', ccflags ='-fno-strict-aliasing -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2',
    cppflags='-fno-strict-aliasing'
    ccversion='', gccversion='2.95.3 20010315 (release)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =''
    libpth=/lib /usr/lib
    libs=-lnsl -lgdbm -ldb -ldl -lm -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lcrypt -lutil
    libc=/lib/libc-2.2.4.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared'

Locally applied patches:
    


@INC for perl v5.6.1:
    /opt/perl/lib/5.6.1/i586-linux
    /opt/perl/lib/5.6.1
    /opt/perl/lib/site_perl/5.6.1/i586-linux
    /opt/perl/lib/site_perl/5.6.1
    /opt/perl/lib/site_perl
    .


Environment for perl v5.6.1:
    HOME=/home/pasky
    LANG (unset)
    LANGUAGE (unset)
    LC_CTYPE=czech
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/opt/bin:/usr/bin:/bin:/usr/games/bin:.
    PERL_BADLANG (unset)
    SHELL=/bin/bash


```
</details>

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Here's a version that's easier to test&#8203;:
perl \-e 'sub\{\{use;&\{""\}\+a\(my$b\);my $a\}\}'

**Comment by p5pRT** [comment]
### From @jhi

On Mon\, Jan 28\, 2002 at 02&#8203;:36&#8203;:00AM \+0000\, Ton Hospel wrote&#8203;:
> Here's a version that's easier to test&#8203;:
> perl \-e 'sub\{\{use;&\{""\}\+a\(my$b\);my $a\}\}'

And here's a stack trace from blead&#8203;:

\(gdb\) run  \-e 'sub\{\{use;&\{""\}\+a\(my$b\);my $a\}\}' 
Starting program&#8203;: /tmp/jhi/perl/perl \-e 'sub\{\{use;&\{""\}\+a\(my$b\);my $a\}\}'

Program received signal SIGSEGV\, Segmentation fault\.
0x3ffbff0551c in Perl\_pad\_free \(po=5\) at op\.c&#8203;:607
607             SvPADTMP\_off\(PL\_curpad\[po\]\);
\(gdb\) where
\#0  0x3ffbff0551c in Perl\_pad\_free \(po=5\) at op\.c&#8203;:607
\#1  0x3ffbff05a5c in Perl\_op\_clear \(o=0x1400128a0\) at op\.c&#8203;:913
\#2  0x3ffbff057f8 in Perl\_op\_free \(o=0x1400128a0\) at op\.c&#8203;:784
\#3  0x3ffbff057a0 in Perl\_op\_free \(o=0x140019b00\) at op\.c&#8203;:772
\#4  0x3ffbff13d94 in Perl\_newATTRSUB \(floor=107\, o=0x0\, proto=0x0\, attrs=0x0\, 
&nbsp;    block=0x140019b00\) at op\.c&#8203;:5018
\#5  0x3ffbff15e0c in Perl\_newANONATTRSUB \(floor=107\, proto=0x0\, attrs=0x0\, 
&nbsp;    block=0x140019b00\) at op\.c&#8203;:5414
\#6  0x3ffbff025e4 in Perl\_yyparse \(\) at perly\.c&#8203;:1600
\#7  0x3ffbfecf4b4 in S\_parse\_body \(env=0x0\, xsinit=0x120001f60 \<xs\_init>\)
&nbsp;    at perl\.c&#8203;:1451
\#8  0x3ffbfece4ac in perl\_parse \(my\_perl=0x140002200\, 
&nbsp;    xsinit=0x120001f60 \<xs\_init>\, argc=3\, argv=0x11ffff4c8\, env=0x0\)
&nbsp;    at perl\.c&#8203;:994
\#9  0x120001edc in main \(argc=3\, argv=0x11ffff4c8\, env=0x11ffff4e8\)
&nbsp;    at perlmain\.c&#8203;:83
\(gdb\) 

\-\- 
$jhi\+\+; \# http&#8203;://www\.iki\.fi/jhi/
&nbsp;        \# There is this special biologist word we use for 'stable'\.
&nbsp;        \# It is 'dead'\. \-\- Jack Cohen

**Comment by p5pRT** [comment]
### From @iabyn

\(Just reviewing old Perl bug reports\)

This appears to have been fixed in the soon\-to\-be\-released Perl 5\.8\.1\.

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
