### ISSUE TITLE
GDBM_File/gdbm.t dumps core

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#5267]
Migrated from [rt.perl.org#8856](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=8856) (status was 'resolved')

Searchable as RT8856$

**Comment by p5pRT** [comment]
### From stas@stason.org

#### Created by stas@hope.stason.org



when running \./perl \.\./ext/GDBM\_File/gdbm\.t it dumps core\, 'make test'
hangs in this test\. seems like it picks a wrong lib? I've tried to run 
with hints from INSTALL with the same effect => segfault\.

PERL\_CORE=1 LD\_LIBRARY\_PATH=/home/stas/perl\.org/perl\-current \./perl \.\./ext/GDBM\_File/gdbm\.t
PERL\_CORE=1 LD\_LIBRARY\_PATH=/home/stas/perl\.org/perl\-current \./perl \-I\.\./lib \.\./ext/GDBM\_File/gdbm\.t

Here is the bt&#8203;:

\#0  0x40286647 in readdir64\_r \(\) from /lib/libc\.so\.6
\#1  0x4037e6c4 in my\_readdir \(d=0x80f74a8\) at bsd\_glob\.c&#8203;:203
\#2  0x4037f8ce in glob3 \(pathbuf=0xbfff9340\, pathbuf\_last=0xbfffb33c\, 
&nbsp;    pathend=0xbfff9340\, pathend\_last=0xbfffb33c\, pattern=0xbfffb370\, 
&nbsp;    pattern\_last=0xbfffd36c\, restpattern=0xbfffb380\, 
&nbsp;    restpattern\_last=0xbfffd36c\, pglob=0xbffff430\, limitp=0xbfffb36c\)
&nbsp;    at bsd\_glob\.c&#8203;:910
\#3  0x4037f766 in glob2 \(pathbuf=0xbfff9340\, pathbuf\_last=0xbfffb33c\, 
&nbsp;    pathend=0xbfff9340\, pathend\_last=0xbfffb33c\, pattern=0xbfffb370\, 
&nbsp;    pattern\_last=0xbfffd36c\, pglob=0xbffff430\, limitp=0xbfffb36c\)
&nbsp;    at bsd\_glob\.c&#8203;:801
\#4  0x4037f557 in glob1 \(pattern=0xbfffb370\, pattern\_last=0xbfffd36c\, 
&nbsp;    pglob=0xbffff430\, limitp=0xbfffb36c\) at bsd\_glob\.c&#8203;:716
\#5  0x4037f2ba in glob0 \(pattern=0xbfffd3d0\, pglob=0xbffff430\)
&nbsp;    at bsd\_glob\.c&#8203;:651
\#6  0x4037e940 in globexp1 \(pattern=0xbfffd3d0\, pglob=0xbffff430\)
&nbsp;    at bsd\_glob\.c&#8203;:391
\#7  0x4037e884 in bsd\_glob \(pattern=0x8052420 "Op\.dbmx\*"\, flags=11904\, 
&nbsp;    errfunc=0x403806f0 \<errfunc>\, pglob=0xbffff430\) at bsd\_glob\.c&#8203;:366
\#8  0x40380ac6 in XS\_File\_\_Glob\_doglob \(my\_perl=0x804c0b0\, cv=0x80bae14\)
&nbsp;    at Glob\.xs&#8203;:55
\#9  0x400b8910 in Perl\_pp\_entersub \(my\_perl=0x804c0b0\) at pp\_hot\.c&#8203;:2724
\#10 0x40096829 in Perl\_runops\_debug \(my\_perl=0x804c0b0\) at dump\.c&#8203;:1392
\#11 0x40039f9e in S\_run\_body \(my\_perl=0x804c0b0\, oldscope=1\) at 
perl\.c&#8203;:1601
\#12 0x400399f1 in perl\_run \(my\_perl=0x804c0b0\) at perl\.c&#8203;:1522
\#13 0x08049425 in main \(argc=2\, argv=0xbffff6f4\, env=0xbffff700\)
&nbsp;    at perlmain\.c&#8203;:85
\#14 0x401ea370 in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6

<details><summary>Perl Info</summary>

```

Flags:
    category=utilities
    severity=medium

This perlbug was built using Perl v5.7.3 - Tue Mar 19 10:22:00 SGT 2002
It is being executed now by  Perl v5.7.3 - Wed Mar  6 11:27:43 SGT 2002.

Site configuration information for perl v5.7.3:

Configured by stas at Wed Mar  6 11:27:43 SGT 2002.

Summary of my perl5 (revision 5.0 version 7 subversion 3 patch 15056) configuration:
  Platform:
    osname=linux, osvers=2.4.17-16mdksmp, archname=i686-linux-thread-multi
    uname='linux hope.stason.org 2.4.17-16mdksmp #1 smp fri feb 8 14:27:48 cet 2002 i686 unknown '
    config_args='-des -Dprefix=/home/stas/perl/ithread -Dusethreads -Doptimize=-g -Duseshrplib -Dusedevel'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -DDEBUGGING -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm',
    optimize='-g',
    cppflags='-D_REENTRANT -DDEBUGGING -fno-strict-aliasing -I/usr/local/include -I/usr/include/gdbm'
    ccversion='', gccversion='2.96 20000731 (Mandrake Linux 8.2 2.96-0.74mdk)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lgdbm -ldl -lm -lpthread -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lpthread -lc -lcrypt -lutil
    libc=/lib/libc-2.2.4.so, so=so, useshrplib=true, libperl=libperl.so
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic -Wl,-rpath,/home/stas/perl/ithread/lib/5.7.3/i686-linux-thread-multi/CORE'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    DEVEL15299


@INC for perl v5.7.3:
    /home/stas/perl/ithread/lib/5.7.3/i686-linux-thread-multi
    /home/stas/perl/ithread/lib/5.7.3
    /home/stas/perl/ithread/lib/site_perl/5.7.3/i686-linux-thread-multi
    /home/stas/perl/ithread/lib/site_perl/5.7.3
    /home/stas/perl/ithread/lib/site_perl/5.7.2/i686-linux-thread-multi
    /home/stas/perl/ithread/lib/site_perl/5.7.2
    /home/stas/perl/ithread/lib/site_perl
    .


Environment for perl v5.7.3:
    HOME=/home/stas
    LANG=en
    LANGUAGE=en_US:en
    LC_COLLATE=en_US
    LC_CTYPE=en_US
    LC_MESSAGES=en_US
    LC_MONETARY=en_US
    LC_NUMERIC=en_US
    LC_TIME=en_US
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr//bin:/bin:/usr/bin:.:/usr/local/bin:/home/stas/bin:/home/stas/bin:/usr/local/bin:/usr/X11R6/bin:/usr/java/j2re1.4.0/bin/:/home/stas/src/insure/bin.linux2
    PERL_BADLANG (unset)
    SHELL=/bin/tcsh


```
</details>

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

#### Created by stas@hope.stason.org



when running \./perl \.\./ext/GDBM\_File/gdbm\.t it dumps core\, 'make test'
hangs in this test\. seems like it picks a wrong lib? I've tried to run 
with hints from INSTALL with the same effect => segfault\.

PERL\_CORE=1 LD\_LIBRARY\_PATH=/home/stas/perl\.org/perl\-current \./perl \.\./ext/GDBM\_File/gdbm\.t
PERL\_CORE=1 LD\_LIBRARY\_PATH=/home/stas/perl\.org/perl\-current \./perl \-I\.\./lib \.\./ext/GDBM\_File/gdbm\.t

Here is the bt&#8203;:

\#0  0x40286647 in readdir64\_r \(\) from /lib/libc\.so\.6
\#1  0x4037e6c4 in my\_readdir \(d=0x80f74a8\) at bsd\_glob\.c&#8203;:203
\#2  0x4037f8ce in glob3 \(pathbuf=0xbfff9340\, pathbuf\_last=0xbfffb33c\, 
&nbsp;    pathend=0xbfff9340\, pathend\_last=0xbfffb33c\, pattern=0xbfffb370\, 
&nbsp;    pattern\_last=0xbfffd36c\, restpattern=0xbfffb380\, 
&nbsp;    restpattern\_last=0xbfffd36c\, pglob=0xbffff430\, limitp=0xbfffb36c\)
&nbsp;    at bsd\_glob\.c&#8203;:910
\#3  0x4037f766 in glob2 \(pathbuf=0xbfff9340\, pathbuf\_last=0xbfffb33c\, 
&nbsp;    pathend=0xbfff9340\, pathend\_last=0xbfffb33c\, pattern=0xbfffb370\, 
&nbsp;    pattern\_last=0xbfffd36c\, pglob=0xbffff430\, limitp=0xbfffb36c\)
&nbsp;    at bsd\_glob\.c&#8203;:801
\#4  0x4037f557 in glob1 \(pattern=0xbfffb370\, pattern\_last=0xbfffd36c\, 
&nbsp;    pglob=0xbffff430\, limitp=0xbfffb36c\) at bsd\_glob\.c&#8203;:716
\#5  0x4037f2ba in glob0 \(pattern=0xbfffd3d0\, pglob=0xbffff430\)
&nbsp;    at bsd\_glob\.c&#8203;:651
\#6  0x4037e940 in globexp1 \(pattern=0xbfffd3d0\, pglob=0xbffff430\)
&nbsp;    at bsd\_glob\.c&#8203;:391
\#7  0x4037e884 in bsd\_glob \(pattern=0x8052420 "Op\.dbmx\*"\, flags=11904\, 
&nbsp;    errfunc=0x403806f0 \<errfunc>\, pglob=0xbffff430\) at bsd\_glob\.c&#8203;:366
\#8  0x40380ac6 in XS\_File\_\_Glob\_doglob \(my\_perl=0x804c0b0\, cv=0x80bae14\)
&nbsp;    at Glob\.xs&#8203;:55
\#9  0x400b8910 in Perl\_pp\_entersub \(my\_perl=0x804c0b0\) at pp\_hot\.c&#8203;:2724
\#10 0x40096829 in Perl\_runops\_debug \(my\_perl=0x804c0b0\) at dump\.c&#8203;:1392
\#11 0x40039f9e in S\_run\_body \(my\_perl=0x804c0b0\, oldscope=1\) at 
perl\.c&#8203;:1601
\#12 0x400399f1 in perl\_run \(my\_perl=0x804c0b0\) at perl\.c&#8203;:1522
\#13 0x08049425 in main \(argc=2\, argv=0xbffff6f4\, env=0xbffff700\)
&nbsp;    at perlmain\.c&#8203;:85
\#14 0x401ea370 in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6

<details><summary>Perl Info</summary>

```

Flags:
    category=utilities
    severity=medium

This perlbug was built using Perl v5.7.3 - Tue Mar 19 10:22:00 SGT 2002
It is being executed now by  Perl v5.7.3 - Wed Mar  6 11:27:43 SGT 2002.

Site configuration information for perl v5.7.3:

Configured by stas at Wed Mar  6 11:27:43 SGT 2002.

Summary of my perl5 (revision 5.0 version 7 subversion 3 patch 15056) configuration:
  Platform:
    osname=linux, osvers=2.4.17-16mdksmp, archname=i686-linux-thread-multi
    uname='linux hope.stason.org 2.4.17-16mdksmp #1 smp fri feb 8 14:27:48 cet 2002 i686 unknown '
    config_args='-des -Dprefix=/home/stas/perl/ithread -Dusethreads -Doptimize=-g -Duseshrplib -Dusedevel'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -DDEBUGGING -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm',
    optimize='-g',
    cppflags='-D_REENTRANT -DDEBUGGING -fno-strict-aliasing -I/usr/local/include -I/usr/include/gdbm'
    ccversion='', gccversion='2.96 20000731 (Mandrake Linux 8.2 2.96-0.74mdk)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lgdbm -ldl -lm -lpthread -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lpthread -lc -lcrypt -lutil
    libc=/lib/libc-2.2.4.so, so=so, useshrplib=true, libperl=libperl.so
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic -Wl,-rpath,/home/stas/perl/ithread/lib/5.7.3/i686-linux-thread-multi/CORE'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    DEVEL15299


@INC for perl v5.7.3:
    /home/stas/perl/ithread/lib/5.7.3/i686-linux-thread-multi
    /home/stas/perl/ithread/lib/5.7.3
    /home/stas/perl/ithread/lib/site_perl/5.7.3/i686-linux-thread-multi
    /home/stas/perl/ithread/lib/site_perl/5.7.3
    /home/stas/perl/ithread/lib/site_perl/5.7.2/i686-linux-thread-multi
    /home/stas/perl/ithread/lib/site_perl/5.7.2
    /home/stas/perl/ithread/lib/site_perl
    .


Environment for perl v5.7.3:
    HOME=/home/stas
    LANG=en
    LANGUAGE=en_US:en
    LC_COLLATE=en_US
    LC_CTYPE=en_US
    LC_MESSAGES=en_US
    LC_MONETARY=en_US
    LC_NUMERIC=en_US
    LC_TIME=en_US
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr//bin:/bin:/usr/bin:.:/usr/local/bin:/home/stas/bin:/home/stas/bin:/usr/local/bin:/usr/X11R6/bin:/usr/java/j2re1.4.0/bin/:/home/stas/src/insure/bin.linux2
    PERL_BADLANG (unset)
    SHELL=/bin/tcsh


```
</details>
