### ISSUE TITLE
recently-introduced regex segfault

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#5279]
Migrated from [rt.perl.org#8870](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=8870) (status was 'resolved')

Searchable as RT8870$

**Comment by p5pRT** [comment]
### From jfriedl@yahoo.com



With the latest bleedperl\, this program segfaults if 're debug' is used\.

&nbsp;    use overload;
&nbsp;    BEGIN \{
&nbsp;          overload&#8203;::constant qr => sub \{ return $\_\[0\] \}
&nbsp;    \}

I'm fairly confident that this worked last week\.
A gdb session is appended\.
&nbsp;       Jeffrey


&nbsp;  \(gdb\) run \-w \-Ilib \-Mre\+debug /tmp/foo
&nbsp;  Starting program&#8203;: /home/jfriedl/src/bleedperl/perl \-w \-Ilib \-Mre\+debug /tmp/foo
&nbsp;  Unquoted string "debug" may clash with future reserved word\.
&nbsp;  Compiling REx \`&#8203;::'
&nbsp;  size 3 Got 28 bytes for offset annotations\.
&nbsp;  first at 1
&nbsp;     1&#8203;: EXACT \<&#8203;::>\(3\)
&nbsp;     3&#8203;: END\(0\)
&nbsp;  anchored \`&#8203;::' at 0 \(checking anchored isall\) minlen 2 
&nbsp;  Offsets&#8203;: \[3\]
&nbsp;          1\[2\] 0\[0\] 3\[0\] 
&nbsp;  Compiling REx \`\.\*&#8203;::'
&nbsp;  size 5 Got 44 bytes for offset annotations\.
&nbsp;  first at 2
&nbsp;     1&#8203;: STAR\(3\)
&nbsp;     2&#8203;:   REG\_ANY\(0\)
&nbsp;     3&#8203;: EXACT \<&#8203;::>\(5\)
&nbsp;     5&#8203;: END\(0\)
&nbsp;  floating \`&#8203;::' at 0\.\.2147483647 \(checking floating\) anchored\(MBOL\) implicit minlen 2 
&nbsp;  Offsets&#8203;: \[5\]
&nbsp;          2\[1\] 1\[1\] 3\[2\] 0\[0\] 5\[0\] 
&nbsp;  Compiling REx \`^&'
&nbsp;  size 4 Got 36 bytes for offset annotations\.
&nbsp;  first at 2
&nbsp;     1&#8203;: BOL\(2\)
&nbsp;     2&#8203;: EXACT \<&>\(4\)
&nbsp;     4&#8203;: END\(0\)
&nbsp;  anchored \`&' at 0 \(checking anchored\) anchored\(BOL\) minlen 1 
&nbsp;  Offsets&#8203;: \[4\]
&nbsp;          1\[1\] 2\[1\] 0\[0\] 3\[0\] 
&nbsp;  Compiling REx \`\\W'
&nbsp;  size 2 Got 20 bytes for offset annotations\.
&nbsp;  first at 1
&nbsp;     1&#8203;: NALNUM\(2\)
&nbsp;     2&#8203;: END\(0\)
&nbsp;  stclass \`NALNUM' minlen 1 
&nbsp;  Offsets&#8203;: \[2\]
&nbsp;          1\[2\] 3\[0\] 
&nbsp;  Compiling REx \`\\W'
&nbsp;  size 2 Got 20 bytes for offset annotations\.
&nbsp;  first at 1
&nbsp;     1&#8203;: NALNUM\(2\)
&nbsp;     2&#8203;: END\(0\)
&nbsp;  stclass \`NALNUM' minlen 1 
&nbsp;  Offsets&#8203;: \[2\]
&nbsp;          1\[2\] 3\[0\] 

&nbsp;  Program received signal SIGSEGV\, Segmentation fault\.
&nbsp;  0x401b23fd in my\_regexec \(prog=0x8148b98\, stringarg=0x813e948 "confess"\, strend=0x813e94f ""\, 
&nbsp;      strbeg=0x813e948 "confess"\, minend=0\, sv=0x813cecc\, data=0x0\, flags=2\) at re\_exec\.c&#8203;:1592
&nbsp;  1592        SV \*dsv0 = PERL\_DEBUG\_PAD\_ZERO\(0\);
&nbsp;  \(gdb\) where
&nbsp;  \#0  0x401b23fd in my\_regexec \(prog=0x8148b98\, stringarg=0x813e948 "confess"\, strend=0x813e94f ""\, 
&nbsp;      strbeg=0x813e948 "confess"\, minend=0\, sv=0x813cecc\, data=0x0\, flags=2\) at re\_exec\.c&#8203;:1592
&nbsp;  \#1  0x0809efb5 in Perl\_pp\_match \(\) at pp\_hot\.c&#8203;:1287
&nbsp;  \#2  0x0809c6e0 in Perl\_runops\_standard \(\) at run\.c&#8203;:25
&nbsp;  \#3  0x0805fa9f in S\_call\_body \(myop=0xbfffe98c\, is\_eval=0\) at perl\.c&#8203;:1987
&nbsp;  \#4  0x0805f881 in perl\_call\_sv \(sv=0x8138638\, flags=6\) at perl\.c&#8203;:1905
&nbsp;  \#5  0x08062396 in S\_call\_list\_body \(cv=0x8138638\) at perl\.c&#8203;:3986
&nbsp;  \#6  0x08062086 in Perl\_call\_list \(oldscope=12\, paramList=0x81385cc\) at perl\.c&#8203;:3914
&nbsp;  \#7  0x080834ff in Perl\_newATTRSUB \(floor=684\, o=0x813d0d8\, proto=0x0\, attrs=0x0\, block=0x813d0a0\) at op\.c&#8203;:5109
&nbsp;  \#8  0x08080535 in Perl\_utilize \(aver=1\, floor=684\, version=0x0\, id=0x8137d60\, arg=0x0\) at op\.c&#8203;:3449
&nbsp;  \#9  0x08079dec in Perl\_yyparse \(\) at perly\.y&#8203;:414
&nbsp;  \#10 0x080c03b8 in S\_doeval \(gimme=0\, startop=0x0\) at pp\_ctl\.c&#8203;:2750
&nbsp;  \#11 0x080c16de in Perl\_pp\_require \(\) at pp\_ctl\.c&#8203;:3227
&nbsp;  \#12 0x0809c6e0 in Perl\_runops\_standard \(\) at run\.c&#8203;:25
&nbsp;  \#13 0x0805fa9f in S\_call\_body \(myop=0xbfffedfc\, is\_eval=0\) at perl\.c&#8203;:1987
&nbsp;  \#14 0x0805f881 in perl\_call\_sv \(sv=0x8135aa8\, flags=6\) at perl\.c&#8203;:1905
&nbsp;  \#15 0x08062396 in S\_call\_list\_body \(cv=0x8135aa8\) at perl\.c&#8203;:3986
&nbsp;  \#16 0x08062086 in Perl\_call\_list \(oldscope=6\, paramList=0x811e980\) at perl\.c&#8203;:3914
&nbsp;  \#17 0x080834ff in Perl\_newATTRSUB \(floor=325\, o=0x8136d18\, proto=0x0\, attrs=0x0\, block=0x8136cf0\) at op\.c&#8203;:5109
&nbsp;  \#18 0x08080535 in Perl\_utilize \(aver=1\, floor=325\, version=0x0\, id=0x81366a0\, arg=0x0\) at op\.c&#8203;:3449
&nbsp;  \#19 0x08079dec in Perl\_yyparse \(\) at perly\.y&#8203;:414
&nbsp;  \#20 0x080c03b8 in S\_doeval \(gimme=0\, startop=0x0\) at pp\_ctl\.c&#8203;:2750
&nbsp;  \#21 0x080c16de in Perl\_pp\_require \(\) at pp\_ctl\.c&#8203;:3227
&nbsp;  \#22 0x0809c6e0 in Perl\_runops\_standard \(\) at run\.c&#8203;:25
&nbsp;  \#23 0x0805fa9f in S\_call\_body \(myop=0xbffff26c\, is\_eval=0\) at perl\.c&#8203;:1987
&nbsp;  \#24 0x0805f881 in perl\_call\_sv \(sv=0x8119e94\, flags=6\) at perl\.c&#8203;:1905
&nbsp;  \#25 0x08062396 in S\_call\_list\_body \(cv=0x8119e94\) at perl\.c&#8203;:3986
&nbsp;  \#26 0x08062086 in Perl\_call\_list \(oldscope=1\, paramList=0x8119f30\) at perl\.c&#8203;:3914
&nbsp;  \#27 0x080834ff in Perl\_newATTRSUB \(floor=107\, o=0x8125dc0\, proto=0x0\, attrs=0x0\, block=0x8125d98\) at op\.c&#8203;:5109
&nbsp;  \#28 0x08080535 in Perl\_utilize \(aver=1\, floor=107\, version=0x0\, id=0x8116708\, arg=0x0\) at op\.c&#8203;:3449
&nbsp;  \#29 0x08079dec in Perl\_yyparse \(\) at perly\.y&#8203;:414
&nbsp;  \#30 0x0805ee17 in S\_parse\_body \(env=0x0\, xsinit=0x805c8f4 \<xs\_init>\) at perl\.c&#8203;:1463
&nbsp;  \#31 0x0805e253 in perl\_parse \(my\_perl=0x81103a8\, xsinit=0x805c8f4 \<xs\_init>\, argc=5\, argv=0xbffff6a4\, env=0x0\)
&nbsp;      at perl\.c&#8203;:990
&nbsp;  \#32 0x0805c8af in main \(argc=5\, argv=0xbffff6a4\, env=0xbffff6bc\) at perlmain\.c&#8203;:83
&nbsp;  \#33 0x400756cf in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6
&nbsp;  \(gdb\)

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

This perlbug was built using Perl v5.7.3 - Sat Mar 23 20:17:40 PST 2002
It is being executed now by  Perl v5.7.3 - Sun Mar 17 16:13:39 PST 2002.

Site configuration information for perl v5.7.3:

Configured by jfriedl at Sun Mar 17 16:13:39 PST 2002.

Summary of my perl5 (revision 5.0 version 7 subversion 3 patch 15276) configuration:
  Platform:
    osname=linux, osvers=2.4.17, archname=i686-linux
    uname='linux fummy 2.4.17 #5 smp thu feb 14 15:21:38 pst 2002 i686 unknown '
    config_args='-Dusedevel -d -e -s -O -D optimize=-O2 -g'
    hint=previous, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=define
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2 -g',
    cppflags='-DDEBUGGING -fno-strict-aliasing -I/usr/local/include -DDEBUGGING -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DDEBUGGING -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DDEBUGGING -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DDEBUGGING -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    ccversion='', gccversion='2.95.4  (Debian prerelease)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -ldl -lm -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lcrypt -lutil
    libc=/lib/libc-2.2.5.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    DEVEL15449


@INC for perl v5.7.3:
    /home/jfriedl/lib/perl
    /home/jfriedl/lib/perl/yahoo
    /usr/local/lib/perl5/5.7.3/i686-linux
    /usr/local/lib/perl5/5.7.3
    /usr/local/lib/perl5/site_perl/5.7.3/i686-linux
    /usr/local/lib/perl5/site_perl/5.7.3
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.7.3:
    HOME=/home/jfriedl
    LANG=C
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/jfriedl/bin:/home/jfriedl/common/bin:.:/usr/local/pgsql/bin:/usr/local/bin:/usr/X11R6/bin:/bin:/usr/bin:/usr/sbin:/sbin:/home/jfriedl/src/rvplayer5.0:/usr/local/prod/bin:/usr/local/java/bin
    PERLLIB=/home/jfriedl/lib/perl:/home/jfriedl/lib/perl/yahoo
    PERL_BADLANG (unset)
    SHELL=/bin/tcsh


```
</details>

**Comment by p5pRT** [comment]
### From @schwern

On Sat\, Mar 23\, 2002 at 08&#8203;:53&#8203;:16PM \-0800\, Jeffrey Friedl wrote&#8203;:
> With the latest bleedperl\, this program segfaults if 're debug' is used\.
> 
>     use overload;
>     BEGIN \{
>           overload&#8203;::constant qr => sub \{ return $\_\[0\] \}
>     \}

Only 'use overload' is necessary for me\.

It segfaults @&#8203;15421 without \-DDEBUGGING\.  Can't tell exactly where
since it's not \-g\.  @&#8203;15421 with \-DDEBUGGING it works fine\.

This appears to be the opposite of what you're seeing since line 1592
is right in the middle of an \#ifdef DEBUGGING block\.


>     cppflags='\-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'

err\.\. what happened there?


\-\- 

Michael G\. Schwern   \<schwern@&#8203;pobox\.com>    http&#8203;://www\.pobox\.com/~schwern/
Perl Quality Assurance        \<perl\-qa@&#8203;perl\.org>           Kwalitee Is Job One
\.\.\.\.and that\, children\, is how to clean and load a \.38 revolver\.  Questions?

**Comment by p5pRT** [comment]
### From @jhi

> >     cppflags='\-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'
> 
> err\.\. what happened there?

Repeated Configures without make distclean\.  \(The hints files do
not reset the flags\.\)

\-\- 
$jhi\+\+; \# http&#8203;://www\.iki\.fi/jhi/
&nbsp;        \# There is this special biologist word we use for 'stable'\.
&nbsp;        \# It is 'dead'\. \-\- Jack Cohen

**Comment by p5pRT** [comment]
### From @schwern

The segfault \*is\* in the PERL\_DEBUG\_PAD\_ZERO\(0\) call\.  Here's what
that expands to&#8203;:

&nbsp;    \(\(\(XPV\*\)  \(  &\(PL\_debug\_pad\.pad\[  0  \]\)   \)\->sv\_any \)\->xpv\_pv \[0\] = 0\, \(\(XPV\*\)  \(  &\(PL\_debug\_pad\.pad\[  0  \]\)   \)\->sv\_any \)\->xpv\_cur  = 0\, &\(PL\_debug\_pad\.pad\[  0  \]\) \) ;

pretty\.

PL\_debug\_pad does not seem to contain anything useful\.

\(gdb\) p PL\_debug\_pad
$51 = \{pad = \{\{sv\_any = 0x0\, sv\_refcnt = 0\, sv\_flags = 0\}\, \{sv\_any = 0x0\, 
&nbsp;      sv\_refcnt = 0\, sv\_flags = 0\}\, \{sv\_any = 0x0\, sv\_refcnt = 0\, 
&nbsp;      sv\_flags = 0\}\}\}

and so those dereferences above will bomb\.

\(gdb\) p \(\(XPV\*\)  \(  &\(PL\_debug\_pad\.pad\[  0  \]\)   \)\->sv\_any \)\->xpv\_pv \[0\]    
Cannot access memory at address 0x0
\(gdb\) p \(\(XPV\*\)  \(  &\(PL\_debug\_pad\.pad\[  0  \]\)   \)\->sv\_any \)\->xpv\_cur     
Cannot access memory at address 0x4


This only happens if \-DDEBUGGING is off\.  re\.pm turns \-DDEBUGGING back
on for reexec\.c\.

&nbsp;    /\* need access to debugger hooks \*/
&nbsp;    \#  if defined\(PERL\_EXT\_RE\_DEBUG\) && \!defined\(DEBUGGING\)
&nbsp;    \#    define DEBUGGING
&nbsp;    \#  endif

I think what causes the problem is this code in perl\.h&#8203;:

&nbsp;    \#ifdef DEBUGGING
&nbsp;        sv\_setpvn\(PERL\_DEBUG\_PAD\(0\)\, ""\, 0\);
&nbsp;        sv\_setpvn\(PERL\_DEBUG\_PAD\(1\)\, ""\, 0\);
&nbsp;        sv\_setpvn\(PERL\_DEBUG\_PAD\(2\)\, ""\, 0\);
&nbsp;    \#endif

without \-DDEBUGGING when perl\.h is compiled DEBUGGING is off so the
init code doesn't run\.  When ext/re/ compiles re\_exec\.c \(which is
really regexec\.c\) it turns DEBUGGING on\, but PL\_debug\_pad was never
initialized\.  Boom\.


Solution?  Remove the \#ifdef DEBUGGING\.


\-\-\- perl\.c    2002/03/24 07&#8203;:20&#8203;:56    1\.1
\+\+\+ perl\.c    2002/03/24 07&#8203;:21&#8203;:10
@&#8203;@&#8203; \-258\,11 \+258\,9 @&#8203;@&#8203;
&nbsp;     PL\_fdpid = newAV\(\);            /\* for remembering popen pids by fd \*/
&nbsp;     PL\_modglobal = newHV\(\);        /\* pointers to per\-interpreter module globals \*/
&nbsp;     PL\_errors = newSVpvn\(""\,0\);
\-\#ifdef DEBUGGING
&nbsp;     sv\_setpvn\(PERL\_DEBUG\_PAD\(0\)\, ""\, 0\);    /\* For regex debugging\. \*/
&nbsp;     sv\_setpvn\(PERL\_DEBUG\_PAD\(1\)\, ""\, 0\);
&nbsp;     sv\_setpvn\(PERL\_DEBUG\_PAD\(2\)\, ""\, 0\);
\-\#endif
 \#ifdef USE\_ITHREADS
&nbsp;     PL\_regex\_padav = newAV\(\);
&nbsp;     av\_push\(PL\_regex\_padav\,\(SV\*\)newAV\(\)\);    /\* First entry is an array of empty elements \*/


\-\- 

Michael G\. Schwern   \<schwern@&#8203;pobox\.com>    http&#8203;://www\.pobox\.com/~schwern/
Perl Quality Assurance        \<perl\-qa@&#8203;perl\.org>           Kwalitee Is Job One
My enormous capacity for love is being WASTED on YOU guys
&nbsp;    \-\- http&#8203;://www\.angryflower\.com/497day\.gif

**Comment by p5pRT** [comment]
### From @jhi

> I think what causes the problem is this code in perl\.h&#8203;:
> 
>     \#ifdef DEBUGGING
>         sv\_setpvn\(PERL\_DEBUG\_PAD\(0\)\, ""\, 0\);
>         sv\_setpvn\(PERL\_DEBUG\_PAD\(1\)\, ""\, 0\);
>         sv\_setpvn\(PERL\_DEBUG\_PAD\(2\)\, ""\, 0\);
>     \#endif
> 
> without \-DDEBUGGING when perl\.h is compiled DEBUGGING is off so the
> init code doesn't run\.  When ext/re/ compiles re\_exec\.c \(which is
> really regexec\.c\) it turns DEBUGGING on\, but PL\_debug\_pad was never
> initialized\.  Boom\.
> 
> 
> Solution?  Remove the \#ifdef DEBUGGING\.

Looks good to me\.  In fact I have a severe case of of dejavu\.\.\.  ahhh\, yes&#8203;:

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
\[ 13246\] By&#8203;: jhi                                   on 2001/11/24  21&#8203;:45&#8203;:32
&nbsp;        Log&#8203;: The debug\_pag needs to be visible at all times
&nbsp;             because of the re extension\.
&nbsp;     Branch&#8203;: perl
&nbsp;           \! intrpvar\.h makedef\.pl perl\.c perl\.h regexec\.c
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\-\- 
$jhi\+\+; \# http&#8203;://www\.iki\.fi/jhi/
&nbsp;        \# There is this special biologist word we use for 'stable'\.
&nbsp;        \# It is 'dead'\. \-\- Jack Cohen

**Comment by p5pRT** [comment]
### From @smpeters

> \[RT\_System \- Sat Mar 23 22&#8203;:49&#8203;:25 2002\]&#8203;:
> 
> > I think what causes the problem is this code in perl\.h&#8203;:
> > 
> >     \#ifdef DEBUGGING
> >         sv\_setpvn\(PERL\_DEBUG\_PAD\(0\)\, ""\, 0\);
> >         sv\_setpvn\(PERL\_DEBUG\_PAD\(1\)\, ""\, 0\);
> >         sv\_setpvn\(PERL\_DEBUG\_PAD\(2\)\, ""\, 0\);
> >     \#endif
> > 
> > without \-DDEBUGGING when perl\.h is compiled DEBUGGING is off so the
> > init code doesn't run\.  When ext/re/ compiles re\_exec\.c \(which is
> > really regexec\.c\) it turns DEBUGGING on\, but PL\_debug\_pad was never
> > initialized\.  Boom\.
> > 
> > 
> > Solution?  Remove the \#ifdef DEBUGGING\.
> 
> Looks good to me\.  In fact I have a severe case of of dejavu\.\.\.  ahhh\,
yes&#8203;:
> 
>
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
> \[ 13246\] By&#8203;: jhi                                   on 2001/11/24  21&#8203;:45&#8203;:32
>         Log&#8203;: The debug\_pag needs to be visible at all times
>              because of the re extension\.
>      Branch&#8203;: perl
>            \! intrpvar\.h makedef\.pl perl\.c perl\.h regexec\.c
>
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
> 

This all appears to be working fine in multiple versions of 5\.8 and
bleadperl\.

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'resolved'
