### ISSUE TITLE
Recursion on stringify overload leads to segfaults.

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#5331]
Migrated from [rt.perl.org#8941](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=8941) (status was 'resolved')

Searchable as RT8941$

**Comment by p5pRT** [comment]
### From @abigail

#### Created by @abigail



&nbsp;    $ cat xxx
&nbsp;    use warnings 'all';
&nbsp;    use overload '""' => sub \{"$\_\[0\]"\};
&nbsp;    print \+\(bless \[\]\);
&nbsp;    $ /opt/perl/bleadperl/bin/perl xxx
&nbsp;    Deep recursion on anonymous subroutine at xxx line 2\.
&nbsp;    Segmentation fault
&nbsp;    $

\(It seems to segfault all the way back to at least 5\.002\_01\.\)

gdb says&#8203;:
&nbsp;   Program received signal SIGSEGV\, Segmentation fault\.
&nbsp;   0x400c222e in chunk\_alloc \(ar\_ptr=0x4015bcc0\, nb=1075173976\) at malloc\.c&#8203;:2740

Top of the call stack&#8203;:
&nbsp;   \#0  0x400c222e in chunk\_alloc \(ar\_ptr=0x4015bcc0\, nb=1075173976\)
&nbsp;       at malloc\.c&#8203;:2740
&nbsp;   \#1  0x400c20d4 in \_\_libc\_malloc \(bytes=32\) at malloc\.c&#8203;:2717
&nbsp;   \#2  0x80b3a17 in Perl\_safemalloc \(size=32\) at util\.c&#8203;:78
&nbsp;   \#3  0x80f842c in Perl\_new\_stackinfo \(stitems=32\, cxitems=23\) at scope\.c&#8203;:72
&nbsp;   \#4  0x806aedd in Perl\_amagic\_call \(left=0x81758c8\, right=0x8172d18\, method=4\,
&nbsp;       flags=9\) at gv\.c&#8203;:1706
&nbsp;   \#5  0x80d8897 in Perl\_sv\_copypv \(dsv=0xc817330\, ssv=0x81758c8\) at sv\.c&#8203;:3208
&nbsp;   \#6  0x80c837d in Perl\_pp\_stringify \(\) at pp\_hot\.c&#8203;:75
&nbsp;   \#7  0x80b34f3 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1394
&nbsp;   \#8  0x806b154 in Perl\_amagic\_call \(left=0x81758c8\, right=0x8172d18\, method=4\,
&nbsp;       flags=9\) at gv\.c&#8203;:1726

And then the last four frames keep repeating\.

This is for patch level 15951\.


Abigail

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.7.3:

Configured by abigail at Tue Apr 16 21:28:05 CEST 2002.

Summary of my perl5 (revision 5.0 version 7 subversion 3 patch 15951) configuration:
  Platform:
    osname=linux, osvers=2.4.5, archname=i686-linux-64int-ld
    uname='linux hermione 2.4.5 #6 fri jun 22 01:38:20 pdt 2001 i686 unknown '
    config_args='-des -Uversiononly -Dmydomain=.foad.org -Dcf_email=abigail@foad.org -Dperladmin=abigail@foad.org -Doptimize=-g -Dusemorebits -Dusedevel -Dusenm=false -Dprefix=/opt/perl/@15951'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=define use64bitall=undef uselongdouble=define
    usemymalloc=n, bincompat5005=define
  Compiler:
    cc='cc', ccflags ='-DDEBUGGING -fno-strict-aliasing -I/usr/local/include -I/opt/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-g',
    cppflags='-DDEBUGGING -fno-strict-aliasing -I/usr/local/include -I/opt/local/include'
    ccversion='', gccversion='2.95.3 20010315 (release)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long long', ivsize=8, nvtype='long double', nvsize=12, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib -L/opt/local/lib'
    libpth=/usr/local/lib /opt/local/lib /lib /usr/lib
    libs=-lnsl -lndbm -lgdbm -ldl -lm -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lcrypt -lutil
    libc=/lib/libc-2.2.3.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib -L/opt/local/lib'

Locally applied patches:
    DEVEL15929


@INC for perl v5.7.3:
    /home/abigail/Perl
    /home/abigail/Sybase
    /opt/perl/@15951/lib/5.7.3/i686-linux-64int-ld
    /opt/perl/@15951/lib/5.7.3
    /opt/perl/@15951/lib/site_perl/5.7.3/i686-linux-64int-ld
    /opt/perl/@15951/lib/site_perl/5.7.3
    /opt/perl/@15951/lib/site_perl
    .


Environment for perl v5.7.3:
    HOME=/home/abigail
    LANG (unset)
    LANGUAGE (unset)
    LC_ALL=POSIX
    LD_LIBRARY_PATH=/home/abigail/Lib:/usr/local/lib:/usr/lib:/lib:/usr/X11R6/lib:/opt/gnome/lib
    LOGDIR (unset)
    PATH=/home/abigail/Bin:/opt/perl/bin:/usr/local/bin:/usr/local/X11/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/X11R6/bin:/usr/games:/opt/povray/bin:/opt/gnome/bin:/opt/opera/bin:/usr/share/texmf/bin:/opt/Acrobat4/bin:/opt/java/blackdown/j2sdk1.3.1/bin:/usr/local/games/bin:/opt/gnuplot/bin:/opt/mysql/bin
    PERL5LIB=/home/abigail/Perl:/home/abigail/Sybase
    PERLDIR=/opt/perl
    PERL_BADLANG (unset)
    SHELL=/usr/bin/bash


```
</details>

**Comment by p5pRT** [comment]
### From @JohnPeacock

abigail@&#8203;foad\.org wrote&#8203;:
>     $ cat xxx
>     use warnings 'all';
>     use overload '""' => sub \{"$\_\[0\]"\};
>     print \+\(bless \[\]\);
>     $ /opt/perl/bleadperl/bin/perl xxx
>     Deep recursion on anonymous subroutine at xxx line 2\.
>     Segmentation fault
>     $
> 
> \(It seems to segfault all the way back to at least 5\.002\_01\.\)
> 

I'm confused; why would you expect anything different to happen\.  You have 
defined the overloaded stringify as the stringify operator itself\.  Or are you 
objecting to the segfault \(since Perl has obviously noticed the deep recursion\)?

On the other hand\, if you use the two term form of bless&#8203;:

&nbsp;    use warnings 'all';
&nbsp;    use overload '""' => sub \{"$\_\[0\]"\};
&nbsp;    print \+\(bless \[\]\,"xxx"\);

you will get

&nbsp;    $ \./perl xxx
&nbsp;    xxx=ARRAY\(0x100f116c\)

so it is only the blessing sans package that is the problem\.  Hmmm\.\.\.

John

\-\- 
John Peacock
Director of Information Research and Technology
Rowman & Littlefield Publishing Group
4720 Boston Way
Lanham\, MD 20706
301\-459\-3366 x\.5010
fax 301\-429\-5747

**Comment by p5pRT** [comment]
### From @abigail

On Wed\, Apr 17\, 2002 at 01&#8203;:39&#8203;:27PM \-0400\, John Peacock wrote&#8203;:
> abigail@&#8203;foad\.org wrote&#8203;:
> >     $ cat xxx
> >     use warnings 'all';
> >     use overload '""' => sub \{"$\_\[0\]"\};
> >     print \+\(bless \[\]\);
> >     $ /opt/perl/bleadperl/bin/perl xxx
> >     Deep recursion on anonymous subroutine at xxx line 2\.
> >     Segmentation fault
> >     $
> > 
> > \(It seems to segfault all the way back to at least 5\.002\_01\.\)
> > 
> 
> I'm confused; why would you expect anything different to happen\.  You have 
> defined the overloaded stringify as the stringify operator itself\.  Or are you 
> objecting to the segfault \(since Perl has obviously noticed the deep recursion\)?

I'm objecting against the segfault\.

> 
> On the other hand\, if you use the two term form of bless&#8203;:
> 
>     use warnings 'all';
>     use overload '""' => sub \{"$\_\[0\]"\};
>     print \+\(bless \[\]\,"xxx"\);
> 
> you will get
> 
>     $ \./perl xxx
>     xxx=ARRAY\(0x100f116c\)
> 
> so it is only the blessing sans package that is the problem\.  Hmmm\.\.\.


No\. The overload routine is never called in your example\. You've
overloaded 'main'\, but blessed the ref into the class 'xxx'\.



Abigail

**Comment by p5pRT** [comment]
### From @JohnPeacock

abigail@&#8203;foad\.org wrote&#8203;:
> No\. The overload routine is never called in your example\. You've
> overloaded 'main'\, but blessed the ref into the class 'xxx'\.
> 

DOH\!

&nbsp;    package xxx;
&nbsp;    use warnings 'all';
&nbsp;    use overload '""' => sub \{"$\_\[0\]"\};
&nbsp;    print \+\(bless \[\]\,"xxx"\);

$ \./perl xxx
Deep recursion on anonymous subroutine at xxx line 3\.

\(followed by SIGSEGV\)

Never mind me\.\.\. :\~\(

John

\-\- 
John Peacock
Director of Information Research and Technology
Rowman & Littlefield Publishing Group
4720 Boston Way
Lanham\, MD 20706
301\-459\-3366 x\.5010
fax 301\-429\-5747

**Comment by p5pRT** [comment]
@abigail - Status changed from 'open' to 'resolved'
