### ISSUE TITLE
perlio & -Dm dumps core

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#5370]
Migrated from [rt.perl.org#9027](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=9027) (status was 'resolved')

Searchable as RT9027$

**Comment by p5pRT** [comment]
### From @vanstyn

#### Created by @vanstyn



crypt% \./perl \-Dm \-e 1
Segmentation fault \(core dumped\)
crypt% 

Stacktrace of the core file shows a stackbusting recursion of
these three&#8203;:
\#15 0x0810e10a in PerlIO\_allocate \(\) at perlio\.c&#8203;:446
\#16 0x08112b04 in Perl\_PerlIO\_stderr \(\) at perlio\.c&#8203;:970
\#17 0x0806356f in malloc \(nbytes=256\) at malloc\.c&#8203;:1106

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.7.3:

Configured by hv at Thu Apr 25 12:24:47 BST 2002.

Summary of my perl5 (revision 5.0 version 7 subversion 3 patch 16151) configuration:
  Platform:
    osname=linux, osvers=2.4.2-2, archname=i686-linux
    uname='linux crypt.compulink.co.uk 2.4.2-2 #1 sun apr 8 20:41:30 edt 2001 i686 unknown '
    config_args='-des -Dprefix=/opt/bleadperl-m -Doptimize=-g -O6 -Dusedevel -Uversiononly -Dusemymalloc'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=y, bincompat5005=define
  Compiler:
    cc='cc', ccflags ='-DDEBUGGING -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm',
    optimize='-g -O6',
    cppflags='-DDEBUGGING -fno-strict-aliasing -I/usr/include/gdbm'
    ccversion='', gccversion='2.96 20000731 (Red Hat Linux 7.1 2.96-81)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lndbm -lgdbm -ldl -lm -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lcrypt -lutil
    libc=/lib/libc-2.2.2.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    DEVEL16151


@INC for perl v5.7.3:
    lib
    /opt/bleadperl-m/lib/5.7.3/i686-linux
    /opt/bleadperl-m/lib/5.7.3
    /opt/bleadperl-m/lib/site_perl/5.7.3/i686-linux
    /opt/bleadperl-m/lib/site_perl/5.7.3
    /opt/bleadperl-m/lib/site_perl
    .


Environment for perl v5.7.3:
    HOME=/home/hv
    LANG=C
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/hv/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash


```
</details>

**Comment by p5pRT** [comment]
### From @jhi

On Thu\, Apr 25\, 2002 at 02&#8203;:47&#8203;:03PM \+0100\, Hugo van der Sanden wrote&#8203;:
> This is a bug report for perl from hv@&#8203;crypt\.compulink\.co\.uk\,
> generated with the help of perlbug 1\.33 running under perl v5\.7\.3@&#8203;16151\.
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> 
> crypt% \./perl \-Dm \-e 1
> Segmentation fault \(core dumped\)
> crypt% 
> 
> Stacktrace of the core file shows a stackbusting recursion of
> these three&#8203;:
> \#15 0x0810e10a in PerlIO\_allocate \(\) at perlio\.c&#8203;:446
> \#16 0x08112b04 in Perl\_PerlIO\_stderr \(\) at perlio\.c&#8203;:970
> \#17 0x0806356f in malloc \(nbytes=256\) at malloc\.c&#8203;:1106

Interesting&#8203;: tru64@&#8203;16153 doesn't enter a recursion\, but instead
finishes nicely\.

\-\- 
$jhi\+\+; \# http&#8203;://www\.iki\.fi/jhi/
&nbsp;        \# There is this special biologist word we use for 'stable'\.
&nbsp;        \# It is 'dead'\. \-\- Jack Cohen

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Jarkko Hietaniemi \<jhi@&#8203;iki\.fi> writes&#8203;:
>\-\-\-\-\- Forwarded message from Hugo van der Sanden \<hv@&#8203;crypt\.compulink\.co\.uk> \-\-\-\-\-
>
>Subject&#8203;: \[ID 20020425\.009\] perlio & \-Dm dumps core
>From&#8203;: Hugo van der Sanden \<hv@&#8203;crypt\.compulink\.co\.uk>
>Date&#8203;: Thu\, 25 Apr 2002 14&#8203;:47&#8203;:03 \+0100
>Message\-Id&#8203;: \<200204251347\.g3PDl3f25967@&#8203;crypt\.compulink\.co\.uk>
>To&#8203;: perl5\-porters@&#8203;perl\.org
>Reply\-To&#8203;: hv@&#8203;crypt0\.demon\.co\.uk
>
>This is a bug report for perl from hv@&#8203;crypt\.compulink\.co\.uk\,
>generated with the help of perlbug 1\.33 running under perl v5\.7\.3@&#8203;16151\.
>
>\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
>\[Please enter your report here\]
>
>crypt% \./perl \-Dm \-e 1
>Segmentation fault \(core dumped\)
>crypt% 

I am not sure what to say here\. \-Dm tries to print something when 
you malloc\(\) and is using PerlIO \*\. PerlIO \* needs to malloc its 
data structures\. How can it do anything but recurse?

We either need to have another malloc\(\) for PerlIO to use\,
or \-Dm needs to be disabled while in PerlIO\, or \.\.\.\.

>
>Stacktrace of the core file shows a stackbusting recursion of
>these three&#8203;:
>\#15 0x0810e10a in PerlIO\_allocate \(\) at perlio\.c&#8203;:446
>\#16 0x08112b04 in Perl\_PerlIO\_stderr \(\) at perlio\.c&#8203;:970
>\#17 0x0806356f in malloc \(nbytes=256\) at malloc\.c&#8203;:1106


\-\- 
Nick Ing\-Simmons
http&#8203;://www\.ni\-s\.u\-net\.com/

**Comment by p5pRT** [comment]
### From @paulg1973

Nick Ing\-Simmons \[mailto&#8203;:nick\.ing\-simmons@&#8203;elixent\.com\] wrote&#8203;:
> Jarkko Hietaniemi \<jhi@&#8203;iki\.fi> writes&#8203;:
> >\-\-\-\-\- Forwarded message from Hugo van der Sanden 
> \<hv@&#8203;crypt\.compulink\.co\.uk> \-\-\-\-\-
\[snip\]
> >\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> >\[Please enter your report here\]
> >
> >crypt% \./perl \-Dm \-e 1
> >Segmentation fault \(core dumped\)
> >crypt% 
> 
> I am not sure what to say here\. \-Dm tries to print something when 
> you malloc\(\) and is using PerlIO \*\. PerlIO \* needs to malloc its 
> data structures\. How can it do anything but recurse?
> 
> We either need to have another malloc\(\) for PerlIO to use\,
> or \-Dm needs to be disabled while in PerlIO\, or \.\.\.\.

I submit that the way out is to first define the layers of abstraction\.  If
it is as follows&#8203;:

\<Perl Compiler & Interpreter>
\<PerlIO>
\<Storage Management>
\<C Libraries>
\<OS>

then it is pretty clear that \<Storage Management> shouldn't call "up" the
hierarchy\.  If it wants to print something\, it's got to use simpler
mechanism\.

Seems to me the problem arises from a muddled definition of the abstract
machine\.

PG

**Comment by p5pRT** [comment]
### From @vanstyn

Jarkko Hietaniemi \<jhi@&#8203;iki\.fi> wrote&#8203;:
:On Thu\, Apr 25\, 2002 at 02&#8203;:47&#8203;:03PM \+0100\, Hugo van der Sanden wrote&#8203;:
:> crypt% \./perl \-Dm \-e 1
:> Segmentation fault \(core dumped\)
:> crypt% 
:> 
:> Stacktrace of the core file shows a stackbusting recursion of
:> these three&#8203;:
:> \#15 0x0810e10a in PerlIO\_allocate \(\) at perlio\.c&#8203;:446
:> \#16 0x08112b04 in Perl\_PerlIO\_stderr \(\) at perlio\.c&#8203;:970
:> \#17 0x0806356f in malloc \(nbytes=256\) at malloc\.c&#8203;:1106
:
:Interesting&#8203;: tru64@&#8203;16153 doesn't enter a recursion\, but instead
:finishes nicely\.

This recursion only occurs with usemymalloc\, and it happens because
the perl\.h DEBUG\_m macro is safed against recursion but malloc\.c
overrides it with an unsafe variant\. The patch below duplicates the
safe version\, and allows me to get further\, but changing the macro
only gets C\< perl \-Dm \-e 1 > to the next segfault 484 malloc debug
lines later\. Along the way there are a couple of warnings&#8203;:

0x814f400&#8203;: \(00248\) malloc 1008 bytes
0x8144a30&#8203;: \(00249\) malloc 1 bytes
0x8144a38&#8203;: \(00250\) realloc 46 bytes the hard way
0x8150440&#8203;: \(00251\) malloc 46 bytes
0x8144a38&#8203;: \(00252\) free
0x8150448&#8203;: \(00253\) realloc 54 bytes the hard way
0x8143d00&#8203;: \(00254\) malloc 54 bytes
0x8150448&#8203;: \(00255\) free
Unaligned \`next' pointer in the free chain 0x3fbff0a at 0x814f400
0x8143d08&#8203;: \(00256\) free
\[\.\.\.\]
0x8144b08&#8203;: \(00483\) free
Unaligned pointer in the free chain 0x3fbff0a
0x8151848&#8203;: \(00484\) free
Segmentation fault \(core dumped\)

I guess this is a reentrancy problem&#8203;: note that not long before the
first warning\, 0x814f400 has been malloced \(and not since freed\)\,
but the complaint says it is in the free chain\. My guess is that
this occurs because the DEBUG\_m for malloc is inside the critical
section; the patch moves it to just after the critical section\, and
now the simple C\< perl \-Dm \-e 1 > runs to completion \(with a total
of 570 malloc debug lines\, or 1171 with PERL\_DESTRUCT\_LEVEL 2\)\.

The 'unaligned' warnings are still in the critical section\, but
as far as I can see they're just a shade shy of a panic\, so I
haven't touched them\. I'm more worried about the
&nbsp;  PerlIO\_puts\(PerlIO\_stderr\(\)\,s\);
style used to print the 'Out of memory' diagnostic before exiting;
if this isn't safe against additional malloc\, I think it is important
that it be made so \(either by changing the PerlIO implementation\,
or by providing a new interface that we could use here\)\, since
a core dump at this stage is going to snowball the initial problem
by filling up your disk\.

Hugo
<details><summary>Inline Patch</summary>

```diff
--- malloc.c.old	Mon Mar 11 04:15:42 2002
+++ malloc.c	Thu May  2 04:03:47 2002
@@ -356,9 +356,16 @@
 
 #ifdef DEBUGGING
 #  undef DEBUG_m
-#  define DEBUG_m(a)  \
+#  define DEBUG_m(a) 							\
     STMT_START {							\
-	if (PERL_GET_INTERP) { dTHX; if (DEBUG_m_TEST) { a; } }	\
+	if (PERL_GET_INTERP) {						\
+	    dTHX;							\
+	    if (DEBUG_m_TEST) {						\
+		PL_debug &= ~DEBUG_m_FLAG;				\
+		a;							\
+		PL_debug |= DEBUG_m_FLAG;				\
+	    }								\
+	}								\
     } STMT_END
 #endif
 
@@ -1103,11 +1110,6 @@
   		return (NULL);
 	}
 
-	DEBUG_m(PerlIO_printf(Perl_debug_log,
-			      "0x%"UVxf": (%05lu) malloc %ld bytes\n",
-			      PTR2UV(p), (unsigned long)(PL_an++),
-			      (long)size));
-
 	/* remove from linked list */
 #if defined(RCHECK)
 	if ((PTR2UV(p)) & (MEM_ALIGNBYTES - 1)) {
@@ -1127,6 +1129,11 @@
   	nextf[bucket] = p->ov_next;
 
 	MALLOC_UNLOCK;
+
+	DEBUG_m(PerlIO_printf(Perl_debug_log,
+			      "0x%"UVxf": (%05lu) malloc %ld bytes\n",
+			      PTR2UV(p), (unsigned long)(PL_an++),
+			      (long)size));
 
 #ifdef IGNORE_SMALL_BAD_FREE
 	if (bucket >= FIRST_BUCKET_WITH_CHECK)
```
</details>
