### ISSUE TITLE
perl5.7.3 hangs when trying to tragp SIGSEGV coming from C code

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#5375]
Migrated from [rt.perl.org#9047](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=9047) (status was 'resolved')

Searchable as RT9047$

**Comment by p5pRT** [comment]
### From stas@stason.org

#### Created by stas@stason.org



I'm tinkering with a module that traps SIGSEGV and friends and generates a backtrace without dumping core\.
Everything works fine when a segfault is happens in the perl code \(e\.g\. kill SEGV\, $$\)\. If the segfault
happens in the C code perl 5\.7\.3 hangs\. The same thing works fine with 5\.6\.1\.

Here is a stripped down version of the module that demonstrates the problem\. The patch will create a new
dir Devel\-CoreDump\, in which you should run the usual 'perl Makefile && make test'\. If you do it with 5\.6\.1
all should work\, on 5\.7\.3 patch 16125 here it hangs\. Notice that if in test\.pl you comment out the calls 
that causes segv on the C level and uncomment the 'kill SEGV\, $$' it works for 5\.6\.1 and bleadperl\.

Here is where it hangs \(relevant after you look at the patch following the trace\)&#8203;:

\[New Thread 1024 \(LWP 3049\)\]
0x40391bad in XS\_Debug\_\_CoreDump\_dump \(my\_perl=0x804c070\, cv=0x80f7b7c\)
&nbsp;    at CoreDump\.xs&#8203;:13
13        printf\("%d"\, \*p\); /\* cause a segfault \*/
\#0  0x40391bad in XS\_Debug\_\_CoreDump\_dump \(my\_perl=0x804c070\, cv=0x80f7b7c\)
&nbsp;    at CoreDump\.xs&#8203;:13
\#1  0x400bb950 in Perl\_pp\_entersub \(my\_perl=0x804c070\) at pp\_hot\.c&#8203;:2741
\#2  0x40097949 in Perl\_runops\_debug \(my\_perl=0x804c070\) at dump\.c&#8203;:1394
\#3  0x4003a70e in S\_run\_body \(my\_perl=0x804c070\, oldscope=1\) at perl\.c&#8203;:1663
\#4  0x4003a161 in perl\_run \(my\_perl=0x804c070\) at perl\.c&#8203;:1584
\#5  0x080493e5 in main \(argc=4\, argv=0xbffff5c4\, env=0xbffff5d8\)
&nbsp;    at perlmain\.c&#8203;:85
\#6  0x401f0280 in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6
\#0  0x40391bad in XS\_Debug\_\_CoreDump\_dump \(my\_perl=0x804c070\, cv=0x80f7b7c\)
&nbsp;    at CoreDump\.xs&#8203;:13

And the package&#8203;:

<details><summary>Inline Patch</summary>

```diff
--- /dev/null	Thu Jan  1 07:30:00 1970
+++ Debug-CoreDump/CoreDump.pm	Sat Apr 27 00:59:49 2002
@@ -0,0 +1,13 @@
+package Debug::CoreDump;
+
+use 5.006;
+use strict;
+use warnings;
+
+require DynaLoader;
+our @ISA = qw(DynaLoader);
+our $VERSION = '0.01';
+
+bootstrap Debug::CoreDump $VERSION;
+
+1;
--- /dev/null	Thu Jan  1 07:30:00 1970
+++ Debug-CoreDump/CoreDump.xs	Sat Apr 27 01:01:05 2002
@@ -0,0 +1,15 @@
+#include "EXTERN.h"
+#include "perl.h"
+#include "XSUB.h"
+
+MODULE = Debug::CoreDump    PACKAGE = Debug::CoreDump
+
+void
+dump()
+    PREINIT:
+    int *p = NULL;
+
+    CODE:
+    printf("%d", *p); /* cause a segfault */
+
+
--- /dev/null	Thu Jan  1 07:30:00 1970
+++ Debug-CoreDump/Makefile.PL	Sat Apr 27 01:02:16 2002
@@ -0,0 +1,8 @@
+use ExtUtils::MakeMaker;
+# See lib/ExtUtils/MakeMaker.pm for details of how to influence
+# the contents of the Makefile that is written.
+WriteMakefile(
+    'NAME'		=> 'Debug::CoreDump',
+    'VERSION_FROM'	=> 'CoreDump.pm',
+    'DEFINE'		=> '-O0 -g',
+);
--- /dev/null	Thu Jan  1 07:30:00 1970
+++ Debug-CoreDump/test.pl	Sat Apr 27 01:03:39 2002
@@ -0,0 +1,10 @@
+use Test;
+BEGIN { plan tests => 1};
+
+use Debug::CoreDump;
+ok 1;
+
+$SIG{SEGV} = sub { print "#dying with SIG$_[0]\n"; print "ok 2\n"; exit };
+
+Debug::CoreDump::dump();
+#kill SEGV, $$;
```
</details>


<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl v5.7.3:

Configured by stas at Wed Apr 24 15:41:57 SGT 2002.

Summary of my perl5 (revision 5.0 version 7 subversion 3 patch 16125) configuration:
  Platform:
    osname=linux, osvers=2.4.18-6mdksmp, archname=i686-linux-thread-multi
    uname='linux hope.stason.org 2.4.18-6mdksmp #1 smp fri mar 15 01:24:36 cet 2002 i686 unknown '
    config_args='-des -Dprefix=/home/stas/perl/ithread -Dusethreads -Doptimize=-g -Duseshrplib -Dusedevel'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DDEBUGGING -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm',
    optimize='-g',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DDEBUGGING -fno-strict-aliasing -I/usr/local/include -I/usr/include/gdbm'
    ccversion='', gccversion='2.96 20000731 (Mandrake Linux 8.2 2.96-0.76mdk)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lgdbm -ldb -ldl -lm -lpthread -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lpthread -lc -lcrypt -lutil
    libc=/lib/libc-2.2.4.so, so=so, useshrplib=true, libperl=libperl.so
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic -Wl,-rpath,/home/stas/perl/ithread/lib/5.7.3/i686-linux-thread-multi/CORE'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    DEVEL16080


@INC for perl v5.7.3:
    /home/stas/perl/ithread/lib/5.7.3/i686-linux-thread-multi
    /home/stas/perl/ithread/lib/5.7.3
    /home/stas/perl/ithread/lib/site_perl/5.7.3/i686-linux-thread-multi
    /home/stas/perl/ithread/lib/site_perl/5.7.3
    /home/stas/perl/ithread/lib/site_perl
    .


Environment for perl v5.7.3:
    HOME=/home/stas
    LANG=en_US
    LANGUAGE=en_US:en
    LC_COLLATE=en_US
    LC_CTYPE=en_US
    LC_MESSAGES=en_US
    LC_MONETARY=en_US
    LC_NUMERIC=en_US
    LC_TIME=en_US
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/bin:/usr/bin:/usr/X11R6/bin:/usr/local/bin:/usr/games:/home/stas/bin:/home/stas/bin:/usr/local/bin:/usr/X11R6/bin:/usr/java/j2re1.4.0/bin/:/home/stas/src/insure/bin.linux2
    PERL_BADLANG (unset)
    SHELL=/bin/tcsh


```
</details>

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

#### Created by stas@stason.org



I'm tinkering with a module that traps SIGSEGV and friends and generates a backtrace without dumping core\.
Everything works fine when a segfault is happens in the perl code \(e\.g\. kill SEGV\, $$\)\. If the segfault
happens in the C code perl 5\.7\.3 hangs\. The same thing works fine with 5\.6\.1\.

Here is a stripped down version of the module that demonstrates the problem\. The patch will create a new
dir Devel\-CoreDump\, in which you should run the usual 'perl Makefile && make test'\. If you do it with 5\.6\.1
all should work\, on 5\.7\.3 patch 16125 here it hangs\. Notice that if in test\.pl you comment out the calls 
that causes segv on the C level and uncomment the 'kill SEGV\, $$' it works for 5\.6\.1 and bleadperl\.

Here is where it hangs \(relevant after you look at the patch following the trace\)&#8203;:

\[New Thread 1024 \(LWP 3049\)\]
0x40391bad in XS\_Debug\_\_CoreDump\_dump \(my\_perl=0x804c070\, cv=0x80f7b7c\)
&nbsp;    at CoreDump\.xs&#8203;:13
13        printf\("%d"\, \*p\); /\* cause a segfault \*/
\#0  0x40391bad in XS\_Debug\_\_CoreDump\_dump \(my\_perl=0x804c070\, cv=0x80f7b7c\)
&nbsp;    at CoreDump\.xs&#8203;:13
\#1  0x400bb950 in Perl\_pp\_entersub \(my\_perl=0x804c070\) at pp\_hot\.c&#8203;:2741
\#2  0x40097949 in Perl\_runops\_debug \(my\_perl=0x804c070\) at dump\.c&#8203;:1394
\#3  0x4003a70e in S\_run\_body \(my\_perl=0x804c070\, oldscope=1\) at perl\.c&#8203;:1663
\#4  0x4003a161 in perl\_run \(my\_perl=0x804c070\) at perl\.c&#8203;:1584
\#5  0x080493e5 in main \(argc=4\, argv=0xbffff5c4\, env=0xbffff5d8\)
&nbsp;    at perlmain\.c&#8203;:85
\#6  0x401f0280 in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6
\#0  0x40391bad in XS\_Debug\_\_CoreDump\_dump \(my\_perl=0x804c070\, cv=0x80f7b7c\)
&nbsp;    at CoreDump\.xs&#8203;:13

And the package&#8203;:

<details><summary>Inline Patch</summary>

```diff
--- /dev/null	Thu Jan  1 07:30:00 1970
+++ Debug-CoreDump/CoreDump.pm	Sat Apr 27 00:59:49 2002
@@ -0,0 +1,13 @@
+package Debug::CoreDump;
+
+use 5.006;
+use strict;
+use warnings;
+
+require DynaLoader;
+our @ISA = qw(DynaLoader);
+our $VERSION = '0.01';
+
+bootstrap Debug::CoreDump $VERSION;
+
+1;
--- /dev/null	Thu Jan  1 07:30:00 1970
+++ Debug-CoreDump/CoreDump.xs	Sat Apr 27 01:01:05 2002
@@ -0,0 +1,15 @@
+#include "EXTERN.h"
+#include "perl.h"
+#include "XSUB.h"
+
+MODULE = Debug::CoreDump    PACKAGE = Debug::CoreDump
+
+void
+dump()
+    PREINIT:
+    int *p = NULL;
+
+    CODE:
+    printf("%d", *p); /* cause a segfault */
+
+
--- /dev/null	Thu Jan  1 07:30:00 1970
+++ Debug-CoreDump/Makefile.PL	Sat Apr 27 01:02:16 2002
@@ -0,0 +1,8 @@
+use ExtUtils::MakeMaker;
+# See lib/ExtUtils/MakeMaker.pm for details of how to influence
+# the contents of the Makefile that is written.
+WriteMakefile(
+    'NAME'		=> 'Debug::CoreDump',
+    'VERSION_FROM'	=> 'CoreDump.pm',
+    'DEFINE'		=> '-O0 -g',
+);
--- /dev/null	Thu Jan  1 07:30:00 1970
+++ Debug-CoreDump/test.pl	Sat Apr 27 01:03:39 2002
@@ -0,0 +1,10 @@
+use Test;
+BEGIN { plan tests => 1};
+
+use Debug::CoreDump;
+ok 1;
+
+$SIG{SEGV} = sub { print "#dying with SIG$_[0]\n"; print "ok 2\n"; exit };
+
+Debug::CoreDump::dump();
+#kill SEGV, $$;
```
</details>


<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl v5.7.3:

Configured by stas at Wed Apr 24 15:41:57 SGT 2002.

Summary of my perl5 (revision 5.0 version 7 subversion 3 patch 16125) configuration:
  Platform:
    osname=linux, osvers=2.4.18-6mdksmp, archname=i686-linux-thread-multi
    uname='linux hope.stason.org 2.4.18-6mdksmp #1 smp fri mar 15 01:24:36 cet 2002 i686 unknown '
    config_args='-des -Dprefix=/home/stas/perl/ithread -Dusethreads -Doptimize=-g -Duseshrplib -Dusedevel'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DDEBUGGING -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm',
    optimize='-g',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DDEBUGGING -fno-strict-aliasing -I/usr/local/include -I/usr/include/gdbm'
    ccversion='', gccversion='2.96 20000731 (Mandrake Linux 8.2 2.96-0.76mdk)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lgdbm -ldb -ldl -lm -lpthread -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lpthread -lc -lcrypt -lutil
    libc=/lib/libc-2.2.4.so, so=so, useshrplib=true, libperl=libperl.so
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic -Wl,-rpath,/home/stas/perl/ithread/lib/5.7.3/i686-linux-thread-multi/CORE'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    DEVEL16080


@INC for perl v5.7.3:
    /home/stas/perl/ithread/lib/5.7.3/i686-linux-thread-multi
    /home/stas/perl/ithread/lib/5.7.3
    /home/stas/perl/ithread/lib/site_perl/5.7.3/i686-linux-thread-multi
    /home/stas/perl/ithread/lib/site_perl/5.7.3
    /home/stas/perl/ithread/lib/site_perl
    .


Environment for perl v5.7.3:
    HOME=/home/stas
    LANG=en_US
    LANGUAGE=en_US:en
    LC_COLLATE=en_US
    LC_CTYPE=en_US
    LC_MESSAGES=en_US
    LC_MONETARY=en_US
    LC_NUMERIC=en_US
    LC_TIME=en_US
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/bin:/usr/bin:/usr/X11R6/bin:/usr/local/bin:/usr/games:/home/stas/bin:/home/stas/bin:/usr/local/bin:/usr/X11R6/bin:/usr/java/j2re1.4.0/bin/:/home/stas/src/insure/bin.linux2
    PERL_BADLANG (unset)
    SHELL=/bin/tcsh


```
</details>
