### ISSUE TITLE
eval causes segmentation fault perl v5.6.1 built for sun4-solaris

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#5391]
Migrated from [rt.perl.org#9088](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=9088) (status was 'resolved')

Searchable as RT9088$

**Comment by p5pRT** [comment]
### From root@somerset.sps.mot.com

#### Created by Mark.Nodine@Motorola.com



Here are the two files required to reproduce this bug&#8203;:
shell
small\.tmpl

Here is shell&#8203;:
\#\#\#
$sub\_string = "sub \{\\n" \. join\(""\,\<>\) \. "\\n\}\\n";
$sub = eval\($sub\_string\);
&$sub;
\#\#\#


Here is small\.tmpl
\#\#\#
Read\(\);
sub Read \{
&nbsp;    $\_ = "a=1";
&nbsp;    /^\(\[^=\]\+\)=\(\.\*\)/;
&nbsp;    my\($p\,$v\) = \($1\,$2\);
&nbsp;    my\(@&#8203;components\) = split\(/\\\./\,$p\);
&nbsp;    $p = '$P' \. join\(''\, grep\(s/^\(\[^\\\[\\\]\]\+\)/\{'$1'\}/\, @&#8203;components\)\);
&nbsp;    eval\("$p=q\($v\)"\);
\}
\#\#\#


How to contact the generator of this bug&#8203;:
Mark\.Nodine@&#8203;Motorola\.com
512\-996\-4872

The other things that were happening as we were reducing the problem
to these 12 lines of code
a\) Sometimes we got a segmentation error
b\) Sometimes we got a bus fault
c\) Sometimes this eval passed and another eval died\.
&nbsp;   But it was always a nested eval that failed
d\) Removing the Read subroutine and doing it inline\, makes the error
&nbsp;   go away\.

Dying at the eval statement in small\.tmpl\.

To invoke the bug under Perl 5\.6\.1 do this\.

$ /usr/local/bin/perl shell small\.tmpl
Segmentation Fault\(coredump\)

Under debug the code looks like this&#8203;:

$ /usr/local/bin/perl \-d shell small\.tmpl
Default die handler restored\.

Loading DB routines from perl5db\.pl version 1\.07
Editor support available\.

Enter h or \`h h' for help\, or \`man perldebug' for more help\.

main&#8203;::\(shell&#8203;:1\)&#8203;:    $sub\_string = "sub \{\\n" \. join\(""\,\<>\) \. "\\n\}\\n";
&nbsp;  DB\<1> t
Trace = on
&nbsp;  DB\<1> c
main&#8203;::\(shell&#8203;:2\)&#8203;:    $sub = eval\($sub\_string\);
main&#8203;::\(\(eval 5\)\[shell&#8203;:2\]&#8203;:14\)&#8203;:    ;
main&#8203;::\(shell&#8203;:3\)&#8203;:    &$sub;
main&#8203;::CODE\(0x20dabc\)\(\(eval 5\)\[shell&#8203;:2\]&#8203;:2\)&#8203;:
2&#8203;:    Read\(\);
3&#8203;:    sub Read \{
main&#8203;::Read\(\(eval 5\)\[shell&#8203;:2\]&#8203;:4\)&#8203;:        $\_ = "a=1";
main&#8203;::Read\(\(eval 5\)\[shell&#8203;:2\]&#8203;:5\)&#8203;:        /^\(\[^=\]\+\)=\(\.\*\)/;
main&#8203;::Read\(\(eval 5\)\[shell&#8203;:2\]&#8203;:6\)&#8203;:        my\($p\,$v\) = \($1\,$2\);
main&#8203;::Read\(\(eval 5\)\[shell&#8203;:2\]&#8203;:7\)&#8203;:        my\(@&#8203;components\) = split\(/\\\./\,$p\);
main&#8203;::Read\(\(eval 5\)\[shell&#8203;:2\]&#8203;:8\)&#8203;:        $p = '$P' \. join\(''\, grep\(s/^\(\[^\\\[\\\]\]\+\)/\{'$1'\}/\, @&#8203;components\)\);
main&#8203;::Read\(\(eval 5\)\[shell&#8203;:2\]&#8203;:9\)&#8203;:        eval\("$p=q\($v\)"\);
main&#8203;::Read\(/usr/local/lib/perl5/5\.6\.1/Carp\.pm&#8203;:97\)&#8203;:
97&#8203;:        \{ local $@&#8203;; require Carp&#8203;::Heavy; \}    \# XXX fix require to not clear $@&#8203;?
main&#8203;::Read\(/usr/local/lib/perl5/5\.6\.1/Carp\.pm&#8203;:97\)&#8203;:
97&#8203;:        \{ local $@&#8203;; require Carp&#8203;::Heavy; \}    \# XXX fix require to not clear $@&#8203;?
main&#8203;::Read\(/usr/local/lib/perl5/5\.6\.1/Carp\.pm&#8203;:97\)&#8203;:
97&#8203;:        \{ local $@&#8203;; require Carp&#8203;::Heavy; \}    \# XXX fix require to not clear $@&#8203;?
main&#8203;::Read\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:247\)&#8203;:
247&#8203;:    1;
main&#8203;::Read\(/usr/local/lib/perl5/5\.6\.1/Carp\.pm&#8203;:98\)&#8203;:
98&#8203;:        goto &longmess\_heavy;
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:30\)&#8203;:
30&#8203;:        return @&#8203;\_ if ref $\_\[0\];
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:31\)&#8203;:
31&#8203;:        my $error = join ''\, @&#8203;\_;
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:32\)&#8203;:
32&#8203;:        my $mess = "";
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:33\)&#8203;:
33&#8203;:        my $i = 1 \+ $CarpLevel;
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:34\)&#8203;:
34&#8203;:        my \($pack\,$file\,$line\,$sub\,$hargs\,$eval\,$require\);
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:35\)&#8203;:
35&#8203;:        my \(@&#8203;a\);
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:39\)&#8203;:
39&#8203;:        while \(do \{ \{ package DB; @&#8203;a = caller\($i\+\+\) \} \} \) \{
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:39\)&#8203;:
39&#8203;:        while \(do \{ \{ package DB; @&#8203;a = caller\($i\+\+\) \} \} \) \{
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:41\)&#8203;:
41&#8203;:        \($pack\,$file\,$line\,$sub\,$hargs\,undef\,$eval\,$require\) = @&#8203;a;
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:56\)&#8203;:
56&#8203;:        if \($error =~ m/\\n$/\) \{
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:61\)&#8203;:
61&#8203;:            if \(defined $eval\) \{
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:77\)&#8203;:
77&#8203;:            if \($hargs\) \{
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:79\)&#8203;:
79&#8203;:            @&#8203;a = @&#8203;DB&#8203;::args;    \# must get local copy of args
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:81\)&#8203;:
81&#8203;:            if \($MaxArgNums and @&#8203;a > $MaxArgNums\) \{
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:86\)&#8203;:
86&#8203;:            for \(@&#8203;a\) \{
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:108\)&#8203;:
108&#8203;:            $sub \.= '\(' \. join\('\, '\, @&#8203;a\) \. '\)';
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:111\)&#8203;:
111&#8203;:            $mess \.= "\\t$sub " if $error eq "called";
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:112\)&#8203;:
112&#8203;:            $mess \.= "$error at $file line $line";
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:113\)&#8203;:
113&#8203;:            if \(defined &Thread&#8203;::tid\) \{
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:117\)&#8203;:
117&#8203;:            $mess \.= "\\n";
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:122\)&#8203;:
122&#8203;:        $error = "called";
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:39\)&#8203;:
39&#8203;:        while \(do \{ \{ package DB; @&#8203;a = caller\($i\+\+\) \} \} \) \{
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:39\)&#8203;:
39&#8203;:        while \(do \{ \{ package DB; @&#8203;a = caller\($i\+\+\) \} \} \) \{
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:41\)&#8203;:
41&#8203;:        \($pack\,$file\,$line\,$sub\,$hargs\,undef\,$eval\,$require\) = @&#8203;a;
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:56\)&#8203;:
56&#8203;:        if \($error =~ m/\\n$/\) \{
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:61\)&#8203;:
61&#8203;:            if \(defined $eval\) \{
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:77\)&#8203;:
77&#8203;:            if \($hargs\) \{
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:111\)&#8203;:
111&#8203;:            $mess \.= "\\t$sub " if $error eq "called";
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:112\)&#8203;:
112&#8203;:            $mess \.= "$error at $file line $line";
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:113\)&#8203;:
113&#8203;:            if \(defined &Thread&#8203;::tid\) \{
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:117\)&#8203;:
117&#8203;:            $mess \.= "\\n";
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:122\)&#8203;:
122&#8203;:        $error = "called";
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:39\)&#8203;:
39&#8203;:        while \(do \{ \{ package DB; @&#8203;a = caller\($i\+\+\) \} \} \) \{
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:39\)&#8203;:
39&#8203;:        while \(do \{ \{ package DB; @&#8203;a = caller\($i\+\+\) \} \} \) \{
Carp&#8203;::longmess\_heavy\(/usr/local/lib/perl5/5\.6\.1/Carp/Heavy\.pm&#8203;:124\)&#8203;:
124&#8203;:        $mess || $error;
Signal BUS at \(eval 5\)\[shell&#8203;:2\] line 2
&nbsp;    main&#8203;::\_\_ANON\_\_\[\(eval 5\)\[shell&#8203;:2\]&#8203;:12\] called at shell line 3
Abort\(coredump\)
$ 

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl v5.6.1:

Configured by wood at Thu Apr 25 13:58:49 CDT 2002.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=solaris, osvers=2.8, archname=sun4-solaris
    uname='sunos death.somerset.sps.mot.com 5.8 generic_108528-11 sun4u sparc sunw,ultra-60 '
    config_args='-Dcc=gcc -Dprefix=/usr/local -Uinstallusrbinperl -des'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='gcc', ccflags ='-fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O',
    cppflags='-fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='2.95.2 19991024 (release)', gccosandvers='solaris2.8'
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=4321
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, usemymalloc=y, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib '
    libpth=/usr/local/lib /usr/lib /usr/ccs/lib
    libs=-lsocket -lnsl -lgdbm -ldl -lm -lc
    perllibs=-lsocket -lnsl -ldl -lm -lc
    libc=/lib/libc.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags=' -Wl,-E'
    cccdlflags='-fPIC', lddlflags=' -W,l-E -G -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.1:
    /usr/local/lib/perl5/5.6.1/sun4-solaris
    /usr/local/lib/perl5/5.6.1
    /usr/local/lib/perl5/site_perl/5.6.1/sun4-solaris
    /usr/local/lib/perl5/site_perl/5.6.1
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.6.1:
    HOME=/home/wood
    LANG (unset)
    LANGUAGE (unset)
    LC_COLLATE=en_US.ISO8859-1
    LC_CTYPE=en_US.ISO8859-1
    LC_MESSAGES=C
    LC_MONETARY=en_US.ISO8859-1
    LC_NUMERIC=en_US.ISO8859-1
    LC_TIME=en_US.ISO8859-1
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/local/perl/5.6.1.4/bin:/usr/local/pgsql-7.1.3.1/bin:/cad/bin:/usr/local/new/bin:/usr/local/bin:/usr/local/lsf/bin:/bin:/usr/ucb:/usr/sbin:/usr/dt/bin:/usr/openwin/bin:/home/wood/bin:/usr/local/bin:/usr/local/tools/bin:/nfs/ibmoto/tools/bin:/home/wood/local/sparc_sunos58/tools/ie/5/bin
    PERL_BADLANG (unset)
    SHELL=/bin/ksh


```
</details>

**Comment by p5pRT** [comment]
### From @schwern

On Mon\, Apr 29\, 2002 at 02&#8203;:40&#8203;:24PM \-0500\, root@&#8203;somerset\.sps\.mot\.com wrote&#8203;:
> $ /usr/local/bin/perl shell small\.tmpl
> Segmentation Fault\(coredump\)

Confirmed segfault in 5\.6\.1 and bleadperl@&#8203;16146\.  No problem with earlier
perls\.  Here's a stack trace&#8203;:

\(gdb\) bt
\#0  0x100599c8 in S\_pad\_findlex \(my\_perl=0x101cfa80\, name=0x101d0140 "%P"\, 
&nbsp;    newoff=0\, seq=3\, startcv=0x1021ac14\, cx\_ix=3\, saweval=0\, flags=0\)
&nbsp;    at op\.c&#8203;:300
\#1  0x1005a570 in Perl\_pad\_findmy \(my\_perl=0x101cfa80\, name=0x101d0140 "%P"\)
&nbsp;    at op\.c&#8203;:497
\#2  0x10048690 in S\_pending\_ident \(my\_perl=0x101cfa80\) at toke\.c&#8203;:5237
\#3  0x100356e0 in Perl\_yylex \(my\_perl=0x101cfa80\) at toke\.c&#8203;:2195
\#4  0x10054ef4 in Perl\_yyparse \(my\_perl=0x101cfa80\) at perly\.c&#8203;:1470
\#5  0x10121d40 in S\_doeval \(my\_perl=0x101cfa80\, gimme=128\, startop=0x0\)
&nbsp;    at pp\_ctl\.c&#8203;:2764
\#6  0x10124f04 in Perl\_pp\_entereval \(my\_perl=0x101cfa80\) at pp\_ctl\.c&#8203;:3330
\#7  0x10094334 in Perl\_runops\_debug \(my\_perl=0x101cfa80\) at dump\.c&#8203;:1394
\#8  0x1001cae0 in S\_run\_body \(my\_perl=0x101cfa80\, oldscope=1\) at perl\.c&#8203;:1663
\#9  0x1001c448 in perl\_run \(my\_perl=0x101cfa80\) at perl\.c&#8203;:1584
\#10 0x10016b20 in main \(argc=3\, argv=0x7ffffa94\, env=0x7ffffaa4\)
&nbsp;    at perlmain\.c&#8203;:85
\#11 0x0fda4c50 in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6


Oddly enough\, when I run bleadperl under gdb there is no segfault\.

schwern@&#8203;blackrider&#8203;:\~/tmp$ gdb bleadperl
GNU gdb 5\.1\.1
Copyright 2002 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and you are
welcome to change it and/or distribute copies of it under certain conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for details\.
This GDB was configured as "powerpc\-linux"\.\.\.
\(gdb\) set args shell small\.tmpl
\(gdb\) run
Starting program&#8203;: /usr/local/bin/bleadperl shell small\.tmpl
\[New Thread 1024 \(LWP 1289\)\]

Program exited normally\.
\(gdb\) 


\-\- 

Michael G\. Schwern   \<schwern@&#8203;pobox\.com>    http&#8203;://www\.pobox\.com/~schwern/
Perl Quality Assurance        \<perl\-qa@&#8203;perl\.org>           Kwalitee Is Job One
Follow me to certain death\!
&nbsp;    http&#8203;://www\.unamerican\.com/

**Comment by p5pRT** [comment]
### From p5p@spam.wizbit.be

perl\-5\.6\.1 code\.pl small\.tmp
Segmentation fault

perl\-5\.6\.2 code\.pl small\.tmp
Segmentation fault

perl\-5\.7\.0 code\.pl small\.tmp
\(no output\)

perl\-5\.8\.0 code\.pl small\.tmp
\(no output\)

**Comment by p5pRT** [comment]
p5p@spam.wizbit.be - Status changed from 'open' to 'resolved'
