### ISSUE TITLE
Unquoted string core dump

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#5395]
Migrated from [rt.perl.org#9108](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=9108) (status was 'resolved')

Searchable as RT9108$

**Comment by p5pRT** [comment]
### From prowlands@adeptra.com

#### Created by prowlands@adeptra.com



This program&#8203;:

\-\-\-\-\-\-\-\-\- snip here \-\-\-\-\-\-\-\-\-\-\-
\#\!/usr/bin/perl \-w

\# This crashes "perl \-c"
\# "undefined" is deliberate; I meant "undef"\, but any
\# unquoted string will do it
\($t1\, undefined\) = split\('/'\, "test/test/test"\, 2\);
\-\-\-\-\-\-\-\- snip here \-\-\-\-\-\-\-\-\-\-\-\-

crashes when syntax checked with "perl \-c"\, like this&#8203;:

$ perl \-c crash\.pl
Unquoted string "undefined" may clash with future reserved word at 
crash\.pl line 6\.
Segmentation fault \(core dumped\)

I haven't check the devel release \(currently 5\.7\.3\)\.

This is the gdb backtrace&#8203;:
\(gdb\) bt
\#0  0x0807adf5 in Perl\_mod \(\)
\#1  0x0807b15d in Perl\_mod \(\)
\#2  0x0807e816 in Perl\_newASSIGNOP \(\)
\#3  0x08077d68 in Perl\_yyparse \(\)
\#4  0x0805c11c in S\_parse\_body \(\)
\#5  0x0805b863 in perl\_parse \(\)
\#6  0x08059f09 in main \(\)
\#7  0x4007a306 in \_\_libc\_start\_main \(main=0x8059eb0 \<main>\, argc=2\, 
&nbsp;    ubp\_av=0xbfffdb04\, init=0x80590b4 \<\_init>\, fini=0x80e3700 \<\_fini>\, 
&nbsp;    rtld\_fini=0x4000d2dc \<\_dl\_fini>\, stack\_end=0xbfffdafc\)
&nbsp;    at \.\./sysdeps/generic/libc\-start\.c&#8203;:129

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.6.1:

Configured by bhcompile at Wed Feb 20 15:00:12 EST 2002.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=linux, osvers=2.4.17-0.13smp, archname=i386-linux
    uname='linux daffy.perf.redhat.com 2.4.17-0.13smp #1 smp fri feb 1 10:30:48 est 2002 i686 unknown '
    config_args='-des -Doptimize=-O2 -march=i386 -mcpu=i686 -Dcc=gcc -Dcf_by=Red Hat, Inc. -Dcccdlflags=-fPIC -Dinstallprefix=/usr -Dprefix=/usr -Darchname=i386-linux -Uusethreads -Uuseithreads -Uuselargefiles -Dd_dosuid -Dd_semctl_semun -Di_db -Di_ndbm -Di_gdbm -Di_shadow -Di_syslog -Dman3ext=3pm -Dlocincpth='
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=undef usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='gcc', ccflags ='-fno-strict-aliasing -I/usr/local/include',
    optimize='-O2 -march=i386 -mcpu=i686',
    cppflags='-fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='2.96 20000731 (Red Hat Linux 7.1 2.96-98)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=4
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -ldl -lm -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lcrypt -lutil
    libc=/lib/libc-2.2.4.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.1:
    /usr/lib/perl5/5.6.1/i386-linux
    /usr/lib/perl5/5.6.1
    /usr/lib/perl5/site_perl/5.6.1/i386-linux
    /usr/lib/perl5/site_perl/5.6.1
    /usr/lib/perl5/site_perl/5.6.0/i386-linux
    /usr/lib/perl5/site_perl/5.6.0
    /usr/lib/perl5/site_perl
    .


Environment for perl v5.6.1:
    HOME=/home/prowlands
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/X11R6/bin:/home/prowlands/bin
    PERL_BADLANG (unset)
    SHELL=/bin/tcsh


```
</details>

**Comment by p5pRT** [comment]
### From @rgarcia

Philip Rowlands wrote&#8203;:
> This program&#8203;:
> 
> \-\-\-\-\-\-\-\-\- snip here \-\-\-\-\-\-\-\-\-\-\-
> \#\!/usr/bin/perl \-w
> 
> \# This crashes "perl \-c"
> \# "undefined" is deliberate; I meant "undef"\, but any
> \# unquoted string will do it
> \($t1\, undefined\) = split\('/'\, "test/test/test"\, 2\);
> \-\-\-\-\-\-\-\- snip here \-\-\-\-\-\-\-\-\-\-\-\-
> 
> crashes when syntax checked with "perl \-c"\, like this&#8203;:
> 
> $ perl \-c crash\.pl
> Unquoted string "undefined" may clash with future reserved word at 
> crash\.pl line 6\.
> Segmentation fault \(core dumped\)
> 
> I haven't check the devel release \(currently 5\.7\.3\)\.

Thanks for your report\. It appears that this bug has already been fixed
in the current development version of Perl\.

\-\- 
Rafael Garcia\-Suarez

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Rafael Garcia\-Suarez wrote&#8203;:
> Thanks for your report\. It appears that this bug has already been fixed
> in the current development version of Perl\.

Great\. You might want to enter this into your bug tracking system\, and 
close the bug\. I getting regular reminders to chase this up\.


Cheers\,

Phil

**Comment by p5pRT** [comment]
### From @nwc10

On Mon\, Jul 01\, 2002 at 01&#8203;:09&#8203;:19PM \+0100\, Philip Rowlands wrote&#8203;:
> Rafael Garcia\-Suarez wrote&#8203;:
> > Thanks for your report\. It appears that this bug has already been fixed
> > in the current development version of Perl\.
> 
> Great\. You might want to enter this into your bug tracking system\, and 
> close the bug\. I getting regular reminders to chase this up\.

Done\. Although the bugtron doesn't seem to be mailing bug owners to say
that updates have been performed currently\.

I'm not sure how to get the bugtron to stop thinking it's a Linux specific
bug \(not that it matters for this particular bug now\)\. On FreeBSD I see an
infinite loop of&#8203;:

perl5\.6\.1 in free\(\)&#8203;: warning&#8203;: chunk is already free\.
perl5\.6\.1 in free\(\)&#8203;: warning&#8203;: chunk is already free\.
perl5\.6\.1 in free\(\)&#8203;: warning&#8203;: chunk is already free\.
perl5\.6\.1 in free\(\)&#8203;: warning&#8203;: chunk is already free\.

Nicholas Clark
