### ISSUE TITLE
seg fault in malloc(), called from Perl_safemalloc

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#5448]
Migrated from [rt.perl.org#9278](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=9278) (status was 'rejected')

Searchable as RT9278$

**Comment by p5pRT** [comment]
### From ryants@shawcable.net

#### Created by ryants@shaw.ca



Background&#8203;:

I have a cvs\-like server for very large binary files that uses
xdelta to keep track of binary differences between revisions\.

This server looks an awful like the server outlined on pages 350\-351
of "Programming Perl"\, Second Edition\.  That\, it sits in a loop 
accepting connections and using fork\(\) to handle each incoming
request\.

Eventually\, however\, one of the forked children will die with a
segmentation fault\.  I managed to catch this in the debugger by
writing a phony client that just hammers the server with requests\.
Sometimes the crash is triggered very quickly; other times it takes
a bit\, but it never takes more than a few minutes for Perl to crash\.

Here is the stack trace&#8203;:

\(gdb\) bt
\#0  0x400cc668 in malloc \(\) from /lib/libc\.so\.6
\#1  0x400cc47d in malloc \(\) from /lib/libc\.so\.6
\#2  0x080a56de in Perl\_safemalloc \(size=1\) at util\.c&#8203;:85
\#3  0x080c3ae1 in Perl\_sv\_grow \(sv=0x819342c\, newlen=1\) at sv\.c&#8203;:1252
\#4  0x080c8661 in Perl\_sv\_setpvn \(sv=0x819342c\, ptr=0x812e5c9 ""\, len=0\)
&nbsp;    at sv\.c&#8203;:2964
\#5  0x080ce8f8 in Perl\_sv\_vsetpvfn \(sv=0x819342c\, 
&nbsp;    pat=0x81316fc "%s %s %2d %02d&#8203;:%02d&#8203;:%02d %d"\, patlen=27\, args=0xbffff520\, 
&nbsp;    svargs=0x0\, svmax=0\, maybe\_tainted=0x0\) at sv\.c&#8203;:5953
\#6  0x080ccb61 in Perl\_vnewSVpvf \(pat=0x81316fc "%s %s %2d %02d&#8203;:%02d&#8203;:%02d %d"\, 
&nbsp;    args=0xbffff520\) at sv\.c&#8203;:4925
\#7  0x080ccacb in Perl\_newSVpvf \(pat=0x81316fc "%s %s %2d %02d&#8203;:%02d&#8203;:%02d %d"\)
&nbsp;    at sv\.c&#8203;:4915
\#8  0x0810517b in Perl\_pp\_gmtime \(\) at pp\_sys\.c&#8203;:4139
\#9  0x08104fab in Perl\_pp\_localtime \(\) at pp\_sys\.c&#8203;:4107
\#10 0x080b7e43 in Perl\_runops\_debug \(\) at run\.c&#8203;:53
\#11 0x0805d6b8 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1471
\#12 0x0805d27c in perl\_run \(my\_perl=0x813f500\) at perl\.c&#8203;:1393
\#13 0x08059f72 in main \(argc=8\, argv=0xbffff724\, env=0xbffff748\)
&nbsp;    at perlmain\.c&#8203;:52
\#14 0x40078f9a in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6

Now\, before you write this off as a bug in glibc\, I have observed this bug
on various machines using various versions of glibc\.

Since this crash always seems to occur in the fork\(\)ed child\, my server
is able to "carry on"\, however clients get a "server closed connection
unexpectedly" error\, and this is kind of annoying\.

In each instance it appears that Perl is doing the "localtime"
call in scalar context\.  I use "scalar localtime" a fair bit in my
program for logging purposes\.

These crashes were not observed in pre\-5\.6\.x release versions\.

If you require any more info\, please don't hesitate to ask\.  In the
meantime\, I'll try to come up with a small\-ish test case and more
information\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl v5.6.1:

Configured by gb at Wed Apr 17 18:54:40 CEST 2002.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=linux, osvers=2.4.18-10mdksmp, archname=i386-linux
    uname='linux no.mandrakesoft.com 2.4.18-10mdksmp #1 smp wed apr 10 13:53:12 cest 2002 i686 unknown '
    config_args='-des -Darchname=i386-linux -Dd_dosuid -Ud_csh -Duseshrplib -Doptimize=-O3 -fomit-frame-pointer -pipe -mcpu=pentiumpro -march=i586 -ffast-math -fno-strength-reduce -Dprefix=/usr -Di_ndbm -Di_gdbm -Di_shadow -Di_syslog -Uuselargefiles -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/lib/perl5/man/man3'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=undef usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -I/usr/local/include',
    optimize='-O3 -fomit-frame-pointer -pipe -mcpu=pentiumpro -march=i586 -ffast-math -fno-strength-reduce',
    cppflags='-fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='2.96 20000731 (Mandrake Linux 8.3 2.96-0.79mdk)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=4
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -ldl -lm -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lcrypt -lutil
    libc=/lib/libc-2.2.5.so, so=so, useshrplib=true, libperl=libperl.so
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic -Wl,-rpath,/usr/lib/perl5/5.6.1/i386-linux/CORE'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.1:
    /usr/lib/perl5/5.6.1/i386-linux
    /usr/lib/perl5/5.6.1
    /usr/lib/perl5/site_perl/5.6.1/i386-linux
    /usr/lib/perl5/site_perl/5.6.1
    /usr/lib/perl5/site_perl
    .


Environment for perl v5.6.1:
    HOME=/home/ryants
    LANG=en_US
    LANGUAGE=en_US:en
    LC_COLLATE=en_US
    LC_CTYPE=en_US
    LC_MESSAGES=en_US
    LC_MONETARY=en_US
    LC_NUMERIC=en_US
    LC_TIME=en_US
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/usr/games:/home/ryants/bin:/home/ryants/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash


```
</details>

**Comment by p5pRT** [comment]
### From @iabyn

marking this as stalled\, since a reproducible test case was never provided\.

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'stalled'

**Comment by p5pRT** [comment]
### From @doy

If we don't get more information about this \(preferably with a
reproducible test case against 5\.16\)\, this can probably be closed\.

\-doy

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'stalled' to 'open'

**Comment by p5pRT** [comment]
### From @jkeenan

On Thu Jul 05 00&#8203;:35&#8203;:47 2012\, doy wrote&#8203;:
> If we don't get more information about this \(preferably with a
> reproducible test case against 5\.16\)\, this can probably be closed\.
> 
> \-doy

No response in over two months\.  Closing ticket\.

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
@jkeenan - Status changed from 'open' to 'rejected'
