### ISSUE TITLE
problems with embedded API

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#5555]
Migrated from [rt.perl.org#9522](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=9522) (status was 'abandoned')

Searchable as RT9522$

**Comment by p5pRT** [comment]
### From Kevin.Regan@netiq.com


It seems that one can not do the following&#8203;:

PerlInterpreter\* interpreter = perl\_alloc\(\);

perl\_construct\( interptreter \);
perl\_parse\( interpreter\, \.\.\. \);
perl\_destruct\( interpreter \);
perl\_construct\( interpreter \);
perl\_parse\( interpreter\, \.\.\. \);
perl\_destruct\( interpreter \);
perl\_free\( interpreter \);

The example above dies with a bus error on the second parse&#8203;:

\(gdb\) where
\#0  0xfeff1c18 in S\_hsplit \(\)
&nbsp;   from
/space/kregan/P4/dev/UnixAgent/bin/solaris/\.\./\.\./\.\./solaris/thirdparty/lib/p
erl/libperl\.so
\#1  0xfeff2ac0 in Perl\_share\_hek \(\)
&nbsp;   from
/space/kregan/P4/dev/UnixAgent/bin/solaris/\.\./\.\./\.\./solaris/thirdparty/lib/p
erl/libperl\.so
\#2  0xfeff0f18 in Perl\_hv\_store \(\)
&nbsp;   from
/space/kregan/P4/dev/UnixAgent/bin/solaris/\.\./\.\./\.\./solaris/thirdparty/lib/p
erl/libperl\.so
\#3  0xfeff0ac4 in Perl\_hv\_fetch \(\)
&nbsp;   from
/space/kregan/P4/dev/UnixAgent/bin/solaris/\.\./\.\./\.\./solaris/thirdparty/lib/p
erl/libperl\.so
\#4  0xfefaad7c in Perl\_gv\_fetchpv \(\)
&nbsp;   from
/space/kregan/P4/dev/UnixAgent/bin/solaris/\.\./\.\./\.\./solaris/thirdparty/lib/p
erl/libperl\.so
\#5  0xfefa5530 in S\_init\_main\_stash \(\)
&nbsp;   from
/space/kregan/P4/dev/UnixAgent/bin/solaris/\.\./\.\./\.\./solaris/thirdparty/lib/p
erl/libperl\.so
\#6  0xfefa1eb0 in S\_parse\_body \(\)
&nbsp;   from
/space/kregan/P4/dev/UnixAgent/bin/solaris/\.\./\.\./\.\./solaris/thirdparty/lib/p
erl/libperl\.so
\#7  0xfefa1d1c in perl\_parse \(\)
&nbsp;   from
/space/kregan/P4/dev/UnixAgent/bin/solaris/\.\./\.\./\.\./solaris/thirdparty/l\-\-\-T
ype \<return> to continue\, or q \<return> to quit\-\-\- 
ib/perl/libperl\.so
\#8  0x10c7c in main \(argc=1\, argv=0xffbefa74\) at \.\./main\.cpp&#8203;:78

\-\-Kevin

Kevin Regan
NetIQ Corporation \(www\.netiq\.com\)
Technical Lead
Houston UNIX Team
Office&#8203;: 2200
Phone&#8203;: 713\-548\-1767

**Comment by p5pRT** [comment]
### From @talexb

A working example\, perhaps using code from http&#8203;://perldoc\.perl\.org/perlembed\.html would be useful\.

**Comment by p5pRT** [comment]
### From @dcollinsn

Abandoned\, closing

**Comment by p5pRT** [comment]
@dcollinsn - Status changed from 'open' to 'abandoned'
