### ISSUE TITLE
nested eval/sub segfaults

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#5585]
Migrated from [rt.perl.org#9728](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=9728) (status was 'resolved')

Searchable as RT9728$

**Comment by p5pRT** [comment]
### From root@schmorp.de

#### Created by root@cerebro.laendle



The following program segfaults with perl\-devel and 5\.6\.1\, but not with
5\.005\_03&#8203;:

&nbsp;   $eval = eval 'sub \{ eval "sub \{ %S \}" \}';
&nbsp;   $eval\->\(\{\}\);

here is a backtrace&#8203;:
&nbsp;   
&nbsp;   \#0  Perl\_av\_fetch \(av=0x13\, key=0\, lval=0\) at av\.c&#8203;:193
&nbsp;   \#1  0x0807c454 in S\_pad\_findlex \(name=0x811ad80 "%S"\, newoff=0\, seq=3\, startcv=0x812c5c8\, cx\_ix=2\, saweval=0\, flags=0\) at op\.c&#8203;:301
&nbsp;    for \(cv = startcv; cv; cv = CvOUTSIDE\(cv\)\) \{
&nbsp;        AV \*curlist = CvPADLIST\(cv\);
&nbsp;   \-\->  SV \*\*svp = av\_fetch\(curlist\, 0\, FALSE\);
&nbsp;        AV \*curname;
&nbsp;   \#2  0x0807ca49 in Perl\_pad\_findmy \(name=0x811ad80 "%S"\) at op\.c&#8203;:497
&nbsp;   \#3  0x08073c5f in S\_pending\_ident \(\) at toke\.c&#8203;:5243
&nbsp;   \#4  0x08069c12 in Perl\_yylex \(\) at toke\.c&#8203;:2201
&nbsp;   \#5  0x0807a415 in Perl\_yyparse \(\) at perly\.c&#8203;:1470
&nbsp;   \#6  0x080c83d6 in S\_doeval \(gimme=128\, startop=0x0\) at pp\_ctl\.c&#8203;:2771

the immediate cause seems to be that S\_pad\_findlex tries to access an
uninitialized or corrupted cv\, but that's unlikely to be the bug\, as even
small modifications of the program make it work here \(like replacing %S by
@&#8203;S\, or the hashref \{\} by a string\)\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.8.0:

Configured by root at Fri Jun 14 14:54:38 CEST 2002.

Summary of my perl5 (revision 5.0 version 8 subversion 0 patch 17236) configuration:
  Platform:
    osname=linux, osvers=2.4, archname=i686-linux
    uname='linux cerebro 2.4.18-pre8-ac3 #2 smp tue feb 5 17:35:23 cet 2002 i686 unknown '
    config_args=''
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc-2.95.4', ccflags ='-I/opt/include -D_GNU_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-Os -funroll-loops -mcpu=pentium -march=pentium -g',
    cppflags='-I/opt/include -D_GNU_SOURCE'
    ccversion='', gccversion='2.95.4 20010319 (prerelease)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='gcc-2.95.4', ldflags =''
    libpth=/usr/lib /opt/lib
    libs=-lcrypt -ldl -lm -lc
    perllibs=-lcrypt -ldl -lm -lc
    libc=/lib/libc-2.2.5.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.2.5'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared'

Locally applied patches:
    DEVEL17205


@INC for perl v5.8.0:
    /root/src/sex
    /opt/perl/lib/perl5
    /opt/perl/lib/perl5
    /opt/perl/lib/perl5
    /opt/perl/lib/perl5
    .


Environment for perl v5.8.0:
    HOME=/root
    LANG (unset)
    LANGUAGE (unset)
    LC_CTYPE=de_DE@euro
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/root/s2:/root/s:/opt/qt/bin:/bin:/usr/bin:/usr/app/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/app/bin:/usr/app/sbin:/usr/X11/bin:/opt/jdk118/bin:/opt/bin:/opt/sbin:.:/root/cc/dejagnu/bin
    PERL5LIB=/root/src/sex
    PERLDB_OPTS=ornaments=0
    PERL_BADLANG (unset)
    SHELL=/bin/bash


```
</details>

**Comment by p5pRT** [comment]
### From @vanstyn

Marc Lehmann \<root@&#8203;schmorp\.de> wrote&#8203;:
:The following program segfaults with perl\-devel and 5\.6\.1\, but not with
:5\.005\_03&#8203;:
:
:   $eval = eval 'sub \{ eval "sub \{ %S \}" \}';
:   $eval\->\(\{\}\);

At the point of coredump\, pad\_findlex\(\) has followed the CvOUTSIDE chain
to a CV that isn't&#8203;:
&nbsp;  Program received signal SIGSEGV\, Segmentation fault\.
&nbsp;  Perl\_av\_fetch \(av=0x22\, key=0\, lval=0\) at av\.c&#8203;:193
&nbsp;  193      if \(SvRMAGICAL\(av\)\) \{
&nbsp;  \(gdb\) up
&nbsp;  \#1  0x0808eb67 in S\_pad\_findlex \(name=0x813e860 "%a"\, newoff=0\, seq=3\, 
&nbsp;      startcv=0x814adf8\, cx\_ix=2\, saweval=0\, flags=0\) at op\.c&#8203;:301
&nbsp;  301   SV \*\*svp = av\_fetch\(curlist\, 0\, FALSE\);
&nbsp;  \(gdb\) p /x \*cv
&nbsp;  $1 = \{sv\_any = 0x8141610\, sv\_refcnt = 0x1\, sv\_flags = 0x4040004\}
&nbsp;  \(gdb\) p \*\(XPV\*\)cv\->sv\_any 
&nbsp;  $2 = \{xpv\_pv = 0x8146e50 "sub \{ %a \}\\n;"\, xpv\_cur = 12\, xpv\_len = 13\}
&nbsp;  \(gdb\) 
\.\.\. and as far as I can tell this is because the particular CV has been
overfreed and thus reused&#8203;: its refcnt gets inc'd once in new\_SV and
again in start\_subparse\(\) at&#8203;:
7550     CvOUTSIDE\(PL\_compcv\) = \(CV\*\)SvREFCNT\_inc\(outsidecv\);
\.\.\. and then dec'd once at op\.c&#8203;:5055 \(below\) and again in freetmps\(\)\.

I suspect the problem is this point here&#8203;:
&nbsp;    /\* If a potential closure prototype\, don't keep a refcount on outer CV\.
&nbsp;     \* This is okay as the lifetime of the prototype is tied to the
&nbsp;     \* lifetime of the outer CV\.  Avoids memory leak due to reference
&nbsp;     \* loop\. \-\-GSAR \*/
&nbsp;    if \(\!name\)
&nbsp;        SvREFCNT\_dec\(CvOUTSIDE\(cv\)\);
\.\.\. but I don't understand this area well enough to work out what is\, and
what should\, be happening\.

Sarathy\, can you shed any light?

Hugo

**Comment by p5pRT** [comment]
### From @gsar

On Tue\, 02 Jul 2002 18&#8203;:00&#8203;:49 BST\, Hugo van der Sanden wrote&#8203;:
>Marc Lehmann \<root@&#8203;schmorp\.de> wrote&#8203;:
>&#8203;:The following program segfaults with perl\-devel and 5\.6\.1\, but not with
>&#8203;:5\.005\_03&#8203;:
>&#8203;:
>&#8203;:   $eval = eval 'sub \{ eval "sub \{ %S \}" \}';
>&#8203;:   $eval\->\(\{\}\);
>
>At the point of coredump\, pad\_findlex\(\) has followed the CvOUTSIDE chain
>to a CV that isn't&#8203;:
>  Program received signal SIGSEGV\, Segmentation fault\.
>  Perl\_av\_fetch \(av=0x22\, key=0\, lval=0\) at av\.c&#8203;:193
>  193      if \(SvRMAGICAL\(av\)\) \{
>  \(gdb\) up
>  \#1  0x0808eb67 in S\_pad\_findlex \(name=0x813e860 "%a"\, newoff=0\, seq=3\, 
>      startcv=0x814adf8\, cx\_ix=2\, saweval=0\, flags=0\) at op\.c&#8203;:301
>  301   SV \*\*svp = av\_fetch\(curlist\, 0\, FALSE\);
>  \(gdb\) p /x \*cv
>  $1 = \{sv\_any = 0x8141610\, sv\_refcnt = 0x1\, sv\_flags = 0x4040004\}
>  \(gdb\) p \*\(XPV\*\)cv\->sv\_any 
>  $2 = \{xpv\_pv = 0x8146e50 "sub \{ %a \}\\n;"\, xpv\_cur = 12\, xpv\_len = 13\}
>  \(gdb\) 
>\.\.\. and as far as I can tell this is because the particular CV has been
>overfreed and thus reused&#8203;: its refcnt gets inc'd once in new\_SV and
>again in start\_subparse\(\) at&#8203;:
>7550     CvOUTSIDE\(PL\_compcv\) = \(CV\*\)SvREFCNT\_inc\(outsidecv\);
>\.\.\. and then dec'd once at op\.c&#8203;:5055 \(below\) and again in freetmps\(\)\.
>
>I suspect the problem is this point here&#8203;:
>    /\* If a potential closure prototype\, don't keep a refcount on outer CV\.
>     \* This is okay as the lifetime of the prototype is tied to the
>     \* lifetime of the outer CV\.  Avoids memory leak due to reference
>     \* loop\. \-\-GSAR \*/
>    if \(\!name\)
>        SvREFCNT\_dec\(CvOUTSIDE\(cv\)\);
>\.\.\. but I don't understand this area well enough to work out what is\, and
>what should\, be happening\.
>
>Sarathy\, can you shed any light?

That test snippet doesn't coredump with perl\-5\.6\.x\-current\.  Perhaps
changes\#13474\,13478\,13584 were never merged from 5\.6\.x into 5\.7\.x?


Sarathy
gsar@&#8203;ActiveState\.com

**Comment by p5pRT** [comment]
### From @gsar

On Tue\, 02 Jul 2002 12&#8203;:09&#8203;:30 PDT\, Gurusamy Sarathy wrote&#8203;:
>That test snippet doesn't coredump with perl\-5\.6\.x\-current\.  Perhaps
>changes\#13474\,13478\,13584 were never merged from 5\.6\.x into 5\.7\.x?

change\#16359 also looks relevant\.

I thought all the 5\.6\.x changes made it into 5\.8\.0\, but now I'm
not so sure\.  Can someone with the tuits verify this please?
Thanks\.


Sarathy
gsar@&#8203;ActiveState\.com

**Comment by p5pRT** [comment]
### From @jhi

> >That test snippet doesn't coredump with perl\-5\.6\.x\-current\.  Perhaps
> >changes\#13474\,13478\,13584 were never merged from 5\.6\.x into 5\.7\.x?
>
> change\#16359 also looks relevant\. I thought all the 5\.6\.x changes
> made it into 5\.8\.0\, but now I'm not so sure\.  Can someone with the
> tuits verify this please?

I grabbed a new sharp tuit spade and went out to the fields to dig
up some more\.  The \#17407 attempts to \(again\) integrate the above
mentioned patches \(effectively I cut and pasted the changed parts
of 5\.6\.1\+ cv\_undef\(\) into bleadperl\)\.  In the past there were "issues"
\(evilly twisted coredumps\) after applying them\, but now things seem
to work\, maybe because the ithreads has matured in the meanwhile\.

\-\- 
$jhi\+\+; \# http&#8203;://www\.iki\.fi/jhi/
&nbsp;        \# There is this special biologist word we use for 'stable'\.
&nbsp;        \# It is 'dead'\. \-\- Jack Cohen

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Sun\, Jul 07\, 2002 at 09&#8203;:36&#8203;:40PM \+0300\, Jarkko Hietaniemi \<jhi@&#8203;iki\.fi> wrote&#8203;:
> up some more\.  The \#17407 attempts to \(again\) integrate the above
> mentioned patches \(effectively I cut and pasted the changed parts
> of 5\.6\.1\+ cv\_undef\(\) into bleadperl\)\.  In the past there were "issues"
> \(evilly twisted coredumps\) after applying them\, but now things seem
> to work\, maybe because the ithreads has matured in the meanwhile\.

I installed DEVEL17411 and found that my testcase works fine\, but perl
still frequently coredumps after heavy eval activity\. The thing is that
this seems to be connected to errors in the eval'ed code\, which get
reported as warns\(\!\!\!\) first and then using die\. That is\, when I overwrite
$SIG\{\_\_WARN\_\_\} I get messages like&#8203;:

&nbsp;   \[Sat Jul  6 19&#8203;:47&#8203;:36 2002\] \[warn\] Warning\[8496\]&#8203;: Scalar found where operator expected at mercury&#8203;::2\_709&#8203;::edit line 1\, near "\#line 1 "mercury&#8203;::
&nbsp;   2\_709&#8203;::edit"
&nbsp;   \<?ef\_selectbox \{ size => $arg"

which gets reported as a warning \(but is an error\)\, immediately followed by the same message as an error message\.

undef'ing $SIG\{\_\_DIE\_\_\} and $SIG\{\_\_WARN\_\_\} seem to improve stability a
bit\, but coredumps still happen\. See also my other mail\, which indicates
that context structures get overwritten\.

\(btw\, all my reported bugs have been fixed really quickly\, thanks a lot to
everybody\!\)

\#0  0x400f295c in memcpy \(\) from /lib/libc\.so\.6
\#1  0x08c9500c in ?? \(\)
\#2  0x0811ef98 in Perl\_runops\_standard \(\) at run\.c&#8203;:25
\#3  0x080d95be in S\_call\_body \(myop=0xbfffec7c\, is\_eval=0\) at perl\.c&#8203;:2045
\#4  0x080d9186 in Perl\_call\_sv \(sv=0x8346e30\, flags=2\) at perl\.c&#8203;:1924
\#5  0x08112979 in Perl\_vcroak \(pat=0x81a3ba0 "Can't locate object method \\"%s\\" via package \\"%\.\*s\\""\, args=0xbfffed18\) at util\.c&#8203;:1285
\#6  0x08112b10 in Perl\_vwarn \(pat=0x81a3ba0 "Can't locate object method \\"%s\\" via package \\"%\.\*s\\""\, args=0x8440620\) at util\.c&#8203;:1350
\#7  0x08126183 in S\_method\_common \(meth=0x8a585e0\, hashp=0xbfffed88\) at pp\_hot\.c&#8203;:3154
\#8  0x08125dd6 in Perl\_pp\_method\_named \(\) at pp\_hot\.c&#8203;:3039
\#9  0x0811ef98 in Perl\_runops\_standard \(\) at run\.c&#8203;:25
\#10 0x08145575 in S\_docatch\_body \(\) at pp\_ctl\.c&#8203;:2536
\#11 0x08145601 in S\_docatch \(o=0x8a3c058\) at pp\_ctl\.c&#8203;:2572
\#12 0x08147b9c in Perl\_pp\_entertry \(\) at pp\_ctl\.c&#8203;:3435
\#13 0x0811ef98 in Perl\_runops\_standard \(\) at run\.c&#8203;:25
\#14 0x080d95be in S\_call\_body \(myop=0xbfffefdc\, is\_eval=0\) at perl\.c&#8203;:2045
\#15 0x080d9186 in Perl\_call\_sv \(sv=0x8c7dffc\, flags=66\) at perl\.c&#8203;:1924
\#16 0x080d8fda in Perl\_call\_method \(methname=0x81a308e "STORE"\, flags=2\) at perl\.c&#8203;:1857
\#17 0x08117352 in S\_magic\_methcall \(sv=0x8734808\, mg=0x8c711e0\, meth=0x81a308e "STORE"\, flags=2\, n=3\, val=0x8734808\) at mg\.c&#8203;:1317
\#18 0x081175f1 in Perl\_magic\_setpack \(sv=0x8734808\, mg=0x8c711e0\) at mg\.c&#8203;:1354
\#19 0x0811594e in Perl\_mg\_set \(sv=0x8734808\) at mg\.c&#8203;:180
\#20 0x0811f2e8 in Perl\_pp\_sassign \(\) at pp\_hot\.c&#8203;:108
\#21 0x0811ef98 in Perl\_runops\_standard \(\) at run\.c&#8203;:25
\#22 0x080d95be in S\_call\_body \(myop=0xbffff21c\, is\_eval=0\) at perl\.c&#8203;:2045
\#23 0x080d9396 in Perl\_call\_sv \(sv=0x81ef9e0\, flags=4\) at perl\.c&#8203;:1963
\#24 0x0806d4ef in perl\_call\_handler \(sv=0x81ef9e0\, r=0x8787dac\, args=0x0\) at mod\_perl\.c&#8203;:1658
\#25 0x0806cfd2 in perl\_run\_stacked\_handlers \(hook=0x817907d "PerlHandler"\, r=0x8787dac\, handlers=0x86e410c\) at mod\_perl\.c&#8203;:1371
\#26 0x0806c2c8 in perl\_handler \(r=0x8787dac\) at mod\_perl\.c&#8203;:897
\#27 0x080b2725 in ap\_invoke\_handler \(r=0x8787dac\) at http\_config\.c&#8203;:517

\-\- 
&nbsp;      \-\-\-\-\-==\-                                             |
&nbsp;      \-\-\-\-==\-\- \_                                           |
&nbsp;      \-\-\-==\-\-\-\(\_\)\_\_  \_\_ \_\_\_\_  \_\_       Marc Lehmann      \+\-\-
&nbsp;      \-\-==\-\-\-/ / \_ \\/ // /\\ \\/ /       pcg@&#8203;goof\.com      |e|
&nbsp;      \-=====/\_/\_//\_/\\\_\,\_/ /\_/\\\_\\       XX11\-RIPE         \-\-\+
&nbsp;    The choice of a GNU generation                       |
&nbsp;                                                         |

**Comment by p5pRT** [comment]
### From @jhi

Since the original test case seems to be happy with Perl 5\.8\.0\, I'm marking the problem ticket as resolved\.  \(Maybe I'll add the test case to the Perl test suite while I'm at it\.\)

**Comment by p5pRT** [comment]
@jhi - Status changed from 'open' to 'resolved'
