### ISSUE TITLE
coredump with variable our

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#5803]
Migrated from [rt.perl.org#15898](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=15898) (status was 'resolved')

Searchable as RT15898$

**Comment by p5pRT** [comment]
### From @lizmat



perl \-e 'my $i = 1; our $\{"scalar$i"\} : shared = 1'

coredumps

<details><summary>Perl Info</summary>

```


This perlbug was built using Perl 5.00503 - Wed Feb  2 15:34:50 EST 2000
It is being executed now by  Perl 5.008 - Wed Jul 24 14:27:23 CEST 2002.

Site configuration information for perl 5.008:

Configured by liz at Wed Jul 24 14:27:23 CEST 2002.

Summary of my perl5 (revision 5.0 version 8 subversion 0) configuration:
   Platform:
     osname=linux, osvers=2.2.20, archname=i686-linux-thread-multi
     uname='linux dolphin.hsyndicate.com 2.2.20 #1 smp wed jan 2 21:32:07 
cet 2002 i686 unknown '
     config_args='-de -Dusethreads'
     hint=recommended, useposix=true, d_sigaction=define
     usethreads=define use5005threads=undef useithreads=define 
usemultiplicity=define
     useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
     use64bitint=undef use64bitall=undef uselongdouble=undef
     usemymalloc=n, bincompat5005=undef
   Compiler:
     cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing 
-I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 
-I/usr/include/gdbm',
     optimize='-O2',
     cppflags='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing 
-I/usr/local/include -I/usr/include/gdbm'
     ccversion='', gccversion='egcs-2.91.66 19990314/Linux (egcs-1.1.2 
release)', gccosandvers=''
     intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
     d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
     ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', 
lseeksize=8
     alignbytes=4, prototype=define
   Linker and Libraries:
     ld='cc', ldflags =' -L/usr/local/lib'
     libpth=/usr/local/lib /lib /usr/lib
     libs=-lnsl -lndbm -lgdbm -ldb -ldl -lm -lpthread -lc -lposix -lcrypt 
-lutil
     perllibs=-lnsl -ldl -lm -lpthread -lc -lposix -lcrypt -lutil
     libc=/lib/libc-2.1.3.so, so=so, useshrplib=false, libperl=libperl.a
     gnulibc_version='2.1.3'
   Dynamic Linking:
     dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
     cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:



@INC for perl 5.008:
     /usr/local/lib/perl5/5.8.0/i686-linux-thread-multi
     /usr/local/lib/perl5/5.8.0
     /usr/local/lib/perl5/site_perl/5.8.0/i686-linux-thread-multi
     /usr/local/lib/perl5/site_perl/5.8.0
     /usr/local/lib/perl5/site_perl/5.6.1
     /usr/local/lib/perl5/site_perl
     .


Environment for perl 5.008:
     HOME=/home/liz
     LANG=en_US
     LANGUAGE (unset)
     LD_LIBRARY_PATH (unset)
     LOGDIR (unset)
     PATH=/usr/bin:/bin:/usr/local/bin:/usr/X11R6/bin
     PERL_BADLANG (unset)
     SHELL=/bin/bash



```
</details>

**Comment by p5pRT** [comment]
### From @abigail

On Wed\, Jul 31\, 2002 at 03&#8203;:21&#8203;:29PM \-0000\, Elizabeth Mattijsen wrote&#8203;:
> \# New Ticket Created by  Elizabeth Mattijsen
> \# Please include the string&#8203;:  \[perl \#15898\]
> \# in the subject line of all future correspondence about this issue\.
> \# \<URL&#8203;: http&#8203;://rt\.perl\.org/rt2/Ticket/Display\.html?id=15898 >
>
>
> This is a bug report for perl from liz@&#8203;dijkmat\.nl\.
> generated with the help of perlbug 1\.26 running under perl 5\.008\.
>
>
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
>
> perl \-e 'my $i = 1; our $\{"scalar$i"\} : shared = 1'
>
> coredumps


And it's the compiler that dumps core&#8203;:
&nbsp;                                      
&nbsp;    $ perl \-ce 'our $\{""\} : foo = 1'  
&nbsp;    Segmentation fault              
&nbsp;    $                 

This is the stack trace I got&#8203;:
&nbsp;                              
&nbsp;    \#0  0x808dc0e in S\_my\_kid \(o=0x817a378\, attrs=0x817a3a8\, imopsp=0xbffff3b8\)
&nbsp;        at op\.c&#8203;:2098
&nbsp;    \#1  0x808de36 in Perl\_my\_attrs \(o=0x817a378\, attrs=0x817a3a8\) at op\.c&#8203;:2149
&nbsp;    \#2  0x8089089 in Perl\_yyparse \(\) at perly\.y&#8203;:718                           
&nbsp;    \#3  0x806157a in S\_parse\_body \(env=0x0\, xsinit=0x805df74 \<xs\_init>\)
&nbsp;        at perl\.c&#8203;:1519
&nbsp;    \#4  0x80606f3 in perl\_parse \(my\_perl=0x81765e8\, xsinit=0x805df74 \<xs\_init>\,
&nbsp;        argc=3\, argv=0xbffff5f4\, env=0x0\) at perl\.c&#8203;:1041
&nbsp;    \#5  0x805df0f in main \(argc=3\, argv=0xbffff5f4\, env=0xbffff604\)
&nbsp;        at perlmain\.c&#8203;:83
&nbsp;    \#6  0x4006f2eb in \_\_libc\_start\_main \(main=0x805de90 \<main>\, argc=3\,
&nbsp;        ubp\_av=0xbffff5f4\, init=0x805cf5c \<\_init>\, fini=0x81516ec \<\_fini>\,
&nbsp;        rtld\_fini=0x4000c130 \<\_dl\_fini>\, stack\_end=0xbffff5ec\)
&nbsp;        at \.\./sysdeps/generic/libc\-start\.c&#8203;:129


Abigail

**Comment by p5pRT** [comment]
### From @rgarcia

Abigail wrote&#8203;:
> And it's the compiler that dumps core&#8203;:
>                                       
>     $ perl \-ce 'our $\{""\} : foo = 1'  
>     Segmentation fault              

Indeed\. With this patch\, the compiler reports a syntax error
"Can't declare scalar dereference in our"\.

<details><summary>Inline Patch</summary>

```diff
--- op.c.orig	Wed Jul 10 01:36:04 2002
+++ op.c	Wed Jul 31 17:51:37 2002
@@ -2089,17 +2089,20 @@ S_my_kid(pTHX_ OP *o, OP *attrs, OP **im
  	       type == OP_RV2AV ||
  	       type == OP_RV2HV) { /* XXX does this let anything illegal in? */
        if (cUNOPo->op_first->op_type != OP_GV) { /* MJD 20011224 */
-           yyerror(Perl_form(aTHX_ "Can't declare %s in my", OP_DESC(o)));
+           yyerror(Perl_form(aTHX_ "Can't declare %s in %s",
+		       OP_DESC(o),
+			  PL_in_my == KEY_our ? "our" : "my"));
          }
          if (attrs) {
              GV *gv = cGVOPx_gv(cUNOPo->op_first);
              PL_in_my = FALSE;
              PL_in_my_stash = Nullhv;
-            apply_attrs(GvSTASH(gv),
-                        (type == OP_RV2SV ? GvSV(gv) :
-                         type == OP_RV2AV ? (SV*)GvAV(gv) :
-                         type == OP_RV2HV ? (SV*)GvHV(gv) : (SV*)gv),
-                        attrs, FALSE);
+	    if (isGV(gv))
+		apply_attrs(GvSTASH(gv),
+			    (type == OP_RV2SV ? GvSV(gv) :
+			     type == OP_RV2AV ? (SV*)GvAV(gv) :
+			     type == OP_RV2HV ? (SV*)GvHV(gv) : (SV*)gv),
+			    attrs, FALSE);
          }
  	o->op_private |= OPpOUR_INTRO;
  	return o;

```
</details>
End of Patch.

I have to ask this question for the second time today :
Where should I add the regression test? Should I create a new
file under t/run for tests like that \(e\.g\. test that a syntax error
does not dump core ?\) \(And port the contents of t/run/fresh\_perl\.t
to it ?\)

**Comment by p5pRT** [comment]
### From @rgarcia

Rafael Garcia\-Suarez wrote&#8203;:
>          if \(attrs\) \{
>              GV \*gv = cGVOPx\_gv\(cUNOPo\->op\_first\);
>              PL\_in\_my = FALSE;
>              PL\_in\_my\_stash = Nullhv;
> \-            apply\_attrs\(GvSTASH\(gv\)\,
> \-                        \(type == OP\_RV2SV ? GvSV\(gv\) :
> \-                         type == OP\_RV2AV ? \(SV\*\)GvAV\(gv\) :
> \-                         type == OP\_RV2HV ? \(SV\*\)GvHV\(gv\) : \(SV\*\)gv\)\,
> \-                        attrs\, FALSE\);
> \+        if \(isGV\(gv\)\)

In fact for maximum safety this should be "if \(gv && isGV\(gv\)\)" here\.
Without this additional check the following will dump core :
&nbsp;     \./perl \-e 'my $$foo : bar'

**Comment by p5pRT** [comment]
### From @hvds

Rafael Garcia\-Suarez \<raphel\.garcia\-suarez@&#8203;hexaflux\.com> wrote&#8203;:
:I have to ask this question for the second time today :
:Where should I add the regression test? Should I create a new
:file under t/run for tests like that \(e\.g\. test that a syntax error
:does not dump core ?\) \(And port the contents of t/run/fresh\_perl\.t
:to it ?\)

Ideally\, we want the regression tests to be sorted by what they are
testing rather than by what happens when they fail\.

If I remember correctly\, the Test&#8203;:: modules have a mechanism for
running in a fresh\_perl; if the most appropriate test file already
uses the Test&#8203;:: modules\, it should be easy to add a fresh\_perl test\,
if not let's put them in a t/run/misc for now but with a comment
saying where they should really have gone \- perhaps we'll find a
useful way to put them there later\.

Hugo

**Comment by p5pRT** [comment]
### From @schwern

On Wed\, Jul 31\, 2002 at 05&#8203;:53&#8203;:48PM \+0200\, Rafael Garcia\-Suarez wrote&#8203;:
> I have to ask this question for the second time today :
> Where should I add the regression test? Should I create a new
> file under t/run for tests like that \(e\.g\. test that a syntax error
> does not dump core ?\) \(And port the contents of t/run/fresh\_perl\.t
> to it ?\)

Place it wherever the 'our' tests are\.  Since there's no t/op/our\.t\, start
one\.

The core dump can be tested with one of fresh\_perl\_is\(\) or fresh\_perl\_like\(\)
from t/test\.pl\.


\-\- 

Michael G\. Schwern   \<schwern@&#8203;pobox\.com>    http&#8203;://www\.pobox\.com/~schwern/
Perl Quality Assurance      \<perl\-qa@&#8203;perl\.org>         Kwalitee Is Job One
Cheating is often more efficient\.
&nbsp;        \- Seven of Nine

**Comment by p5pRT** [comment]
### From @rgarcia

Michael G Schwern wrote&#8203;:
> On Wed\, Jul 31\, 2002 at 05&#8203;:53&#8203;:48PM \+0200\, Rafael Garcia\-Suarez wrote&#8203;:
> 
>>I have to ask this question for the second time today :
>>Where should I add the regression test? Should I create a new
>>file under t/run for tests like that \(e\.g\. test that a syntax error
>>does not dump core ?\) \(And port the contents of t/run/fresh\_perl\.t
>>to it ?\)
> 
> 
> Place it wherever the 'our' tests are\.  Since there's no t/op/our\.t\, start
> one\.

As this is also a 'my' bug\, and related to attributes\,
I think t/op/attrs\.t is more appropriate\.

That doesn't help for the %&#8203;::="" segfault\. I suggest to
create t/op/stash\.t for various tests about the symbol table hashes\.

**Comment by p5pRT** [comment]
### From @rgs

Rafael Garcia\-Suarez wrote&#8203;:
> Abigail wrote&#8203;:
> > And it's the compiler that dumps core&#8203;:
> >                                       
> >     $ perl \-ce 'our $\{""\} : foo = 1'  
> >     Segmentation fault              
> 
> Indeed\. With this patch\, the compiler reports a syntax error
> "Can't declare scalar dereference in our"\.
> 
> \-\-\- op\.c\.orig    Wed Jul 10 01&#8203;:36&#8203;:04 2002
> \+\+\+ op\.c    Wed Jul 31 17&#8203;:51&#8203;:37 2002

Forget this patch\. It doesn't work with ithreads\.
Another \(simpler\) fix is to insert a simple "else" after
the "if \.\.\. \{ yyerror \}" block\.

There's also a patch to t/op/attrs\.t\. I added two tests
at the end and I ported it to use t/test\.pl\.

<details><summary>Inline Patch</summary>

```diff
--- op.c.orig	Wed Jul 10 23:13:08 2002
+++ op.c	Fri Aug  2 23:33:48 2002
@@ -2088,19 +2088,19 @@ S_my_kid(pTHX_ OP *o, OP *attrs, OP **im
     } else if (type == OP_RV2SV ||	/* "our" declaration */
 	       type == OP_RV2AV ||
 	       type == OP_RV2HV) { /* XXX does this let anything illegal in? */
-      if (cUNOPo->op_first->op_type != OP_GV) { /* MJD 20011224 */
-           yyerror(Perl_form(aTHX_ "Can't declare %s in my", OP_DESC(o)));
-        }
-        if (attrs) {
-            GV *gv = cGVOPx_gv(cUNOPo->op_first);
-            PL_in_my = FALSE;
-            PL_in_my_stash = Nullhv;
-            apply_attrs(GvSTASH(gv),
-                        (type == OP_RV2SV ? GvSV(gv) :
-                         type == OP_RV2AV ? (SV*)GvAV(gv) :
-                         type == OP_RV2HV ? (SV*)GvHV(gv) : (SV*)gv),
-                        attrs, FALSE);
-        }
+	if (cUNOPo->op_first->op_type != OP_GV) { /* MJD 20011224 */
+	    yyerror(Perl_form(aTHX_ "Can't declare %s in %s",
+			OP_DESC(o), PL_in_my == KEY_our ? "our" : "my"));
+	} else if (attrs) {
+	    GV *gv = cGVOPx_gv(cUNOPo->op_first);
+	    PL_in_my = FALSE;
+	    PL_in_my_stash = Nullhv;
+	    apply_attrs(GvSTASH(gv),
+			(type == OP_RV2SV ? GvSV(gv) :
+			 type == OP_RV2AV ? (SV*)GvAV(gv) :
+			 type == OP_RV2HV ? (SV*)GvHV(gv) : (SV*)gv),
+			attrs, FALSE);
+	}
 	o->op_private |= OPpOUR_INTRO;
 	return o;
     }
--- t/op/attrs.t.orig	Fri Mar 29 09:34:37 2002
+++ t/op/attrs.t	Fri Aug  2 23:38:07 2002
@@ -5,188 +5,93 @@
 BEGIN {
     chdir 't' if -d 't';
     @INC = '../lib';
+    require './test.pl';
 }
 
-sub NTESTS () ;
-
-my ($test, $ntests);
-BEGIN {$ntests=0}
-$test=0;
-my $failed = 0;
-
-print "1..".NTESTS."\n";
+plan tests => 37;
 
 $SIG{__WARN__} = sub { die @_ };
 
-sub mytest {
-    my $bad = '';
-    if (!$@ ne !$_[0] || $_[0] && $@ !~ $_[0]) {
-	if ($@) {
-	    my $x = $@;
-	    $x =~ s/\n.*\z//s;
-	    print "# Got: $x\n"
-	}
-	else {
-	    print "# Got unexpected success\n";
-	}
-	if ($_[0]) {
-	    print "# Expected: $_[0]\n";
-	}
-	else {
-	    print "# Expected success\n";
-	}
-	$failed = 1;
-	$bad = 'not ';
-    }
-    elsif (@_ == 3 && $_[1] ne $_[2]) {
-	print "# Got: $_[1]\n";
-	print "# Expected: $_[2]\n";
-	$failed = 1;
-	$bad = 'not ';
-    }
-    print $bad."ok ".++$test."\n";
+sub eval_ok ($) {
+    eval $_[0];
+    is( $@, '' );
 }
 
-eval 'sub t1 ($) : locked { $_[0]++ }';
-mytest;
-BEGIN {++$ntests}
-
-eval 'sub t2 : locked { $_[0]++ }';
-mytest;
-BEGIN {++$ntests}
-
-eval 'sub t3 ($) : locked ;';
-mytest;
-BEGIN {++$ntests}
-
-eval 'sub t4 : locked ;';
-mytest;
-BEGIN {++$ntests}
-
-my $anon1;
-eval '$anon1 = sub ($) : locked:method { $_[0]++ }';
-mytest;
-BEGIN {++$ntests}
-
-my $anon2;
-eval '$anon2 = sub : locked : method { $_[0]++ }';
-mytest;
-BEGIN {++$ntests}
-
-my $anon3;
-eval '$anon3 = sub : method { $_[0]->[1] }';
-mytest;
-BEGIN {++$ntests}
+eval_ok 'sub t1 ($) : locked { $_[0]++ }';
+eval_ok 'sub t2 : locked { $_[0]++ }';
+eval_ok 'sub t3 ($) : locked ;';
+eval_ok 'sub t4 : locked ;';
+our $anon1; eval_ok '$anon1 = sub ($) : locked:method { $_[0]++ }';
+our $anon2; eval_ok '$anon2 = sub : locked : method { $_[0]++ }';
+our $anon3; eval_ok '$anon3 = sub : method { $_[0]->[1] }';
 
 eval 'sub e1 ($) : plugh ;';
-mytest qr/^Invalid CODE attributes?: ["']?plugh["']? at/;
-BEGIN {++$ntests}
+like $@, qr/^Invalid CODE attributes?: ["']?plugh["']? at/;
 
 eval 'sub e2 ($) : plugh(0,0) xyzzy ;';
-mytest qr/^Invalid CODE attributes: ["']?plugh\(0,0\)["']? /;
-BEGIN {++$ntests}
+like $@, qr/^Invalid CODE attributes: ["']?plugh\(0,0\)["']? /;
 
 eval 'sub e3 ($) : plugh(0,0 xyzzy ;';
-mytest qr/Unterminated attribute parameter in attribute list at/;
-BEGIN {++$ntests}
+like $@, qr/Unterminated attribute parameter in attribute list at/;
 
 eval 'sub e4 ($) : plugh + xyzzy ;';
-mytest qr/Invalid separator character '[+]' in attribute list at/;
-BEGIN {++$ntests}
-
-eval 'my main $x : = 0;';
-mytest;
-BEGIN {++$ntests}
-
-eval 'my $x : = 0;';
-mytest;
-BEGIN {++$ntests}
-
-eval 'my $x ;';
-mytest;
-BEGIN {++$ntests}
-
-eval 'my ($x) : = 0;';
-mytest;
-BEGIN {++$ntests}
-
-eval 'my ($x) ;';
-mytest;
-BEGIN {++$ntests}
-
-eval 'my ($x) : ;';
-mytest;
-BEGIN {++$ntests}
-
-eval 'my ($x,$y) : = 0;';
-mytest;
-BEGIN {++$ntests}
-
-eval 'my ($x,$y) ;';
-mytest;
-BEGIN {++$ntests}
+like $@, qr/Invalid separator character '[+]' in attribute list at/;
 
-eval 'my ($x,$y) : ;';
-mytest;
-BEGIN {++$ntests}
+eval_ok 'my main $x : = 0;';
+eval_ok 'my $x : = 0;';
+eval_ok 'my $x ;';
+eval_ok 'my ($x) : = 0;';
+eval_ok 'my ($x) ;';
+eval_ok 'my ($x) : ;';
+eval_ok 'my ($x,$y) : = 0;';
+eval_ok 'my ($x,$y) ;';
+eval_ok 'my ($x,$y) : ;';
 
 eval 'my ($x,$y) : plugh;';
-mytest qr/^Invalid SCALAR attribute: ["']?plugh["']? at/;
-BEGIN {++$ntests}
+like $@, qr/^Invalid SCALAR attribute: ["']?plugh["']? at/;
 
 sub A::MODIFY_SCALAR_ATTRIBUTES { return }
 eval 'my A $x : plugh;';
-mytest qr/^SCALAR package attribute may clash with future reserved word: ["']?plugh["']? at/;
-BEGIN {++$ntests}
+like $@, qr/^SCALAR package attribute may clash with future reserved word: ["']?plugh["']? at/;
 
 eval 'my A $x : plugh plover;';
-mytest qr/^SCALAR package attributes may clash with future reserved words: ["']?plugh["']? /;
-BEGIN {++$ntests}
+like $@, qr/^SCALAR package attributes may clash with future reserved words: ["']?plugh["']? /;
 
 eval 'package Cat; my Cat @socks;';
-mytest qr/^Can't declare class for non-scalar \@socks in "my"/;
-BEGIN {++$ntests}
+like $@, qr/^Can't declare class for non-scalar \@socks in "my"/;
 
 sub X::MODIFY_CODE_ATTRIBUTES { die "$_[0]" }
 sub X::foo { 1 }
 *Y::bar = \&X::foo;
 *Y::bar = \&X::foo;	# second time for -w
 eval 'package Z; sub Y::bar : foo';
-mytest qr/^X at /;
-BEGIN {++$ntests}
+like $@, qr/^X at /;
 
 eval 'package Z; sub Y::baz : locked {}';
 my @attrs = eval 'attributes::get \&Y::baz';
-mytest '', "@attrs", "locked";
-BEGIN {++$ntests}
+is "@attrs", "locked";
 
 @attrs = eval 'attributes::get $anon1';
-mytest '', "@attrs", "locked method";
-BEGIN {++$ntests}
+is "@attrs", "locked method";
 
 sub Z::DESTROY { }
 sub Z::FETCH_CODE_ATTRIBUTES { return 'Z' }
 my $thunk = eval 'bless +sub : method locked { 1 }, "Z"';
-mytest '', ref($thunk), "Z";
-BEGIN {++$ntests}
+is ref($thunk), "Z";
 
 @attrs = eval 'attributes::get $thunk';
-mytest '', "@attrs", "locked method Z";
-BEGIN {++$ntests}
+is "@attrs", "locked method Z";
 
 # Test ability to modify existing sub's (or XSUB's) attributes.
 eval 'package A; sub X { $_[0] } sub X : lvalue';
 @attrs = eval 'attributes::get \&A::X';
-mytest '', "@attrs", "lvalue";
-BEGIN {++$ntests}
+is "@attrs", "lvalue";
 
 # Above not with just 'pure' built-in attributes.
 sub Z::MODIFY_CODE_ATTRIBUTES { (); }
 eval 'package Z; sub L { $_[0] } sub L : Z lvalue';
 @attrs = eval 'attributes::get \&Z::L';
-mytest '', "@attrs", "lvalue Z";
-BEGIN {++$ntests}
-
+is "@attrs", "lvalue Z";
 
 # Begin testing attributes that tie
 
@@ -196,26 +101,23 @@
     sub TIESCALAR { my $x = $_[1]; bless \$x, $_[0]; }
     sub FETCH { ${$_[0]} }
     sub STORE {
-	#print "# In Ttie::STORE\n";
-	::mytest '';
+	::pass;
 	${$_[0]} = $_[1]*2;
     }
     package Tloop;
     sub MODIFY_SCALAR_ATTRIBUTES { tie ${$_[1]}, 'Ttie', -1; (); }
 }
 
-eval '
+eval_ok '
     package Tloop;
     for my $i (0..2) {
 	my $x : TieLoop = $i;
-	$x != $i*2 and ::mytest "", $x, $i*2;
+	$x != $i*2 and ::is $x, $i*2;
     }
 ';
-mytest;
-BEGIN {$ntests += 4}
-
-# Other tests should be added above this line
 
-sub NTESTS () { $ntests }
-
-exit $failed;
+# bug #15898
+eval 'our ${""} : foo = 1';
+like $@, qr/Can't declare scalar dereference in our/;
+eval 'my $$foo : bar = 1';
+like $@, qr/Can't declare scalar dereference in my/;
```
</details>

**Comment by p5pRT** [comment]
### From @hvds

Rafael Garcia\-Suarez \<rgarciasuarez@&#8203;free\.fr> wrote&#8203;:
:Rafael Garcia\-Suarez wrote&#8203;:
:> \-\-\- op\.c\.orig    Wed Jul 10 01&#8203;:36&#8203;:04 2002
:> \+\+\+ op\.c    Wed Jul 31 17&#8203;:51&#8203;:37 2002
:
:Forget this patch\. It doesn't work with ithreads\.
:Another \(simpler\) fix is to insert a simple "else" after
:the "if \.\.\. \{ yyerror \}" block\.
:
:There's also a patch to t/op/attrs\.t\. I added two tests
:at the end and I ported it to use t/test\.pl\.

Thanks\, applied as \#17699\.

Hugo

**Comment by p5pRT** [comment]
@gbarr - Status changed from 'new' to 'resolved'
