### ISSUE TITLE
ithreads coredumps on join of joined thread

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#5850]
Migrated from [rt.perl.org#16681](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=16681) (status was 'resolved')

Searchable as RT16681$

**Comment by p5pRT** [comment]
### From davem@fdgroup.co.uk

#### Created by davem@gizmo.fdgroup.co.uk



the following simple bit of code coredumps for me on Solaris&#8203;:

&nbsp;    \#\!/usr/bin/perl \-w
&nbsp;    use threads;
&nbsp;    my $a = 'x'x 1; \#just a hook for the debugger

&nbsp;    my $t = threads\->new\(sub \{\}\);
&nbsp;    $t\->join;
&nbsp;    $t\->join;

What appears to be happing is that during the first call to join\,
Perl\_ithread\_join\(\) does

&nbsp;    sv\_unmagic\(SvRV\(obj\)\,PERL\_MAGIC\_shared\_scalar\);

which appears to the free up the ithread structure associated
with the thread\. So the next call to join\, rather than seeing
a PERL\_ITHR\_JOINED flag\, just randomly coredumps\.

This gdb stacktrace shows a watchpoint where thread\->state changes
back from 6 to 0 during the first join\.

Hardware watchpoint 3&#8203;: \(\(ithread \*\) 2319872\)\->state

Old value = 6 '\\006'
New value = 0 '\\000'
0xff1e18e8 in memset \(\) from /usr/platform/SUNW\,Ultra\-1/lib/libc\_psr\.so\.1
\(gdb\) bt
\#0  0xff1e18e8 in memset \(\) from /usr/platform/SUNW\,Ultra\-1/lib/libc\_psr\.so\.1
\#1  0x33db0 in Perl\_gv\_init \(my\_perl=0x1ff358\, gv=0x2e512c\, stash=0x28dbe0\, 
&nbsp;    name=0x1c9178 "DESTROY"\, len=7\, multi=1\) at gv\.c&#8203;:111
\#2  0x34434 in Perl\_gv\_fetchmeth \(my\_perl=0x1ff358\, stash=0x28dbe0\, 
&nbsp;    name=0x1c9178 "DESTROY"\, len=7\, level=0\) at gv\.c&#8203;:215
\#3  0x34c48 in Perl\_gv\_fetchmeth\_autoload \(my\_perl=0x1ff358\, stash=0x28dbe0\, 
&nbsp;    name=0x1c9178 "DESTROY"\, len=7\, level=0\) at gv\.c&#8203;:328
\#4  0x39188 in Perl\_Gv\_AMupdate \(my\_perl=0x1ff358\, stash=0x28dbe0\) at gv\.c&#8203;:1334
\#5  0x396d8 in Perl\_gv\_handler \(my\_perl=0x1ff358\, stash=0x28dbe0\, id=65\)
&nbsp;    at gv\.c&#8203;:1406
\#6  0xf0cf0 in Perl\_sv\_clear \(my\_perl=0x1ff358\, sv=0x2e5138\) at sv\.c&#8203;:4952
\#7  0xf1e1c in Perl\_sv\_free \(my\_perl=0x1ff358\, sv=0x2e5138\) at sv\.c&#8203;:5192
\#8  0x38bcc in Perl\_gp\_free \(my\_perl=0x1ff358\, gv=0x2e5120\) at gv\.c&#8203;:1248
\#9  0xf15c8 in Perl\_sv\_clear \(my\_perl=0x1ff358\, sv=0x2e5120\) at sv\.c&#8203;:5026
\#10 0xf1e1c in Perl\_sv\_free \(my\_perl=0x1ff358\, sv=0x2e5120\) at sv\.c&#8203;:5192
\#11 0xe223c in do\_clean\_named\_objs \(my\_perl=0x1ff358\, sv=0x2e5120\) at sv\.c&#8203;:367
\#12 0xe1d9c in S\_visit \(my\_perl=0x1ff358\, f=0xe1fac \<do\_clean\_named\_objs>\)
&nbsp;    at sv\.c&#8203;:292
\#13 0xe2280 in Perl\_sv\_clean\_objs \(my\_perl=0x1ff358\) at sv\.c&#8203;:388
\#14 0x283a0 in perl\_destruct \(my\_perl=0x1ff358\) at perl\.c&#8203;:469
\#15 0xff0922ec in Perl\_ithread\_destruct \(my\_perl=0x1e6dc0\, thread=0x236600\, 
&nbsp;    why=0xff095ae0 "no reference"\) at threads\.xs&#8203;:138
\#16 0xff0927ac in ithread\_mg\_free \(my\_perl=0x1e6dc0\, sv=0x1e7cd0\, mg=0x2f93b0\)
&nbsp;    at threads\.xs&#8203;:204
\#17 0xefc6c in Perl\_sv\_unmagic \(my\_perl=0x1e6dc0\, sv=0x1e7cd0\, type=110\)
&nbsp;    at sv\.c&#8203;:4687
\#18 0xff093dfc in Perl\_ithread\_join \(my\_perl=0x1e6dc0\, obj=0x1f78ac\)
&nbsp;    at threads\.xs&#8203;:524
\#19 0xff094b04 in XS\_threads\_join \(my\_perl=0x1e6dc0\, cv=0x26c514\)
&nbsp;    at threads\.xs&#8203;:598
\#20 0xdf7b4 in Perl\_pp\_entersub \(my\_perl=0x1e6dc0\) at pp\_hot\.c&#8203;:2773
\#21 0xad384 in Perl\_runops\_debug \(my\_perl=0x1e6dc0\) at dump\.c&#8203;:1398
\#22 0x2c244 in S\_run\_body \(my\_perl=0x1e6dc0\, oldscope=1\) at perl\.c&#8203;:1681
\#23 0x2bb2c in perl\_run \(my\_perl=0x1e6dc0\) at perl\.c&#8203;:1600
\#24 0x25ac8 in main \(argc=2\, argv=0xffbef5a4\, env=0xffbef5b0\) at perlmain\.c&#8203;:85

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.8.0:

Configured by davem at Mon Aug  5 12:46:42 BST 2002.

Summary of my perl5 (revision 5.0 version 8 subversion 0) configuration:
  Platform:
    osname=solaris, osvers=2.8, archname=sun4-solaris-thread-multi
    uname='sunos gizmo 5.8 generic_108528-03 sun4u sparc sunw,ultra-1 '
    config_args='-des -Dcc=gcc -Dprefix=/home/davem/perl5/perl-5.8.0t.out -Duseithreads -Uinstallusrbinperl -Doptimize=-g'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-D_REENTRANT -DDEBUGGING -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-g',
    cppflags='-D_REENTRANT -DDEBUGGING -fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='2.95.2 19991024 (release)', gccosandvers='solaris2.8'
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=4321
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib '
    libpth=/usr/local/lib /usr/lib /usr/ccs/lib
    libs=-lsocket -lnsl -ldl -lm -lrt -lpthread -lc
    perllibs=-lsocket -lnsl -ldl -lm -lrt -lpthread -lc
    libc=/lib/libc.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags=' '
    cccdlflags='-fPIC', lddlflags='-G -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.0:
    /home/davem/perl5/perl-5.8.0t.out/lib/5.8.0/sun4-solaris-thread-multi
    /home/davem/perl5/perl-5.8.0t.out/lib/5.8.0
    /home/davem/perl5/perl-5.8.0t.out/lib/site_perl/5.8.0/sun4-solaris-thread-multi
    /home/davem/perl5/perl-5.8.0t.out/lib/site_perl/5.8.0
    /home/davem/perl5/perl-5.8.0t.out/lib/site_perl
    .


Environment for perl v5.8.0:
    HOME=/home/davem
    LANG=C
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/ccs/bin:/usr/local/bin:/home/davem/bin:/usr/bin::/usr/dt/bin:/usr/openwin/bin:/bin:/usr/ucb
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @lizmat

At 10&#8203;:46 AM 8/21/02 \+0000\, via RT wrote&#8203;:
>    use threads;
>     my $a = 'x'x 1; \#just a hook for the debugger
>
>     my $t = threads\->new\(sub \{\}\);
>     $t\->join;
>     $t\->join;

Under Linux I get&#8203;:

$ perl \-Mthreads \-e 'my $t = threads\->new\( sub \{\} \); $t\->join; $t\->join'
Thread already joined at \-e line 1\.


Liz

**Comment by p5pRT** [comment]
arthur@contiller.se - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From arthur@contiller.se

Hi\,

Can you see if this still applies? I think I might have fixed it before
5\.8 came out\. I can't reproduce it on linux\.

Arthur

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, Jan 04\, 2003 at 01&#8203;:09&#8203;:09AM \-0000\, Arthur Bergman wrote&#8203;:
> Hi\,
> 
> Can you see if this still applies? I think I might have fixed it before
> 5\.8 came out\. I can't reproduce it on linux\.


On a copy of 18378 I have lying around\, I can get strange effects
on Linux by executing some code that reallocs stuff between the joins&#8203;:

&nbsp;    use threads;
&nbsp;    my $a = 'x'x 1; \#just a hook for the debugger

&nbsp;    my $t = threads\->new\(sub \{\}\);
&nbsp;    $t\->join;
&nbsp;    for \(1\.\.100\) \{
&nbsp;    $a\[$\_\] = "\\0xff" x $\_;
&nbsp;    \}

&nbsp;    $t\->join;

\[davem@&#8203;percy 18378t\]$ \./perl \-Ilib /tmp/p
Name "main&#8203;::a" used only once&#8203;: possible typo at /tmp/p line 9\.
panic&#8203;: MUTEX\_LOCK at /tmp/p line 12\.

So I guess the bug is still active :\-\(


Summary of my perl5 \(revision 5\.0 version 9 subversion 0 patch 18378\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.4\.7\-10\, archname=i686\-linux\-thread\-multi
&nbsp;    uname='linux percy 2\.4\.7\-10 \#1 thu sep 6 16&#8203;:46&#8203;:36 edt 2001 i686 unknown '
&nbsp;    config\_args='\-des \-Dusedevel \-Dprefix=/home/davem/perl5/18378t\.out \-Uinstallusrbinperl \-Duseithreads \-Doptimize=\-g'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=define useithreads=define usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-I/usr/include/gdbm'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-I/usr/include/gdbm'
&nbsp;    ccversion=''\, gccversion='2\.96 20000731 \(Red Hat Linux 7\.1 2\.96\-98\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-lndbm \-lgdbm \-ldl \-lm \-lpthread \-lc \-lcrypt \-lutil \-lrt
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lpthread \-lc \-lcrypt \-lutil \-lrt
&nbsp;    libc=/lib/libc\-2\.2\.4\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.2\.4'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
&nbsp;    cccdlflags='\-fpic'\, lddlflags='\-shared \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: DEBUGGING MULTIPLICITY USE\_ITHREADS USE\_LARGE\_FILES PERL\_IMPLICIT\_CONTEXT
&nbsp;  Locally applied patches&#8203;:
&nbsp;      DEVEL18374
&nbsp;  Built under linux
&nbsp;  Compiled at Jan  1 2003 15&#8203;:50&#8203;:28
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /home/davem/perl5/18378t\.out/lib/5\.9\.0/i686\-linux\-thread\-multi
&nbsp;    /home/davem/perl5/18378t\.out/lib/5\.9\.0
&nbsp;    /home/davem/perl5/18378t\.out/lib/site\_perl/5\.9\.0/i686\-linux\-thread\-multi
&nbsp;    /home/davem/perl5/18378t\.out/lib/site\_perl/5\.9\.0
&nbsp;    /home/davem/perl5/18378t\.out/lib/site\_perl
&nbsp;    \.


\-\- 
A walk of a thousand miles begins with a single step\.\.\.
then continues for another 1\,999\,999 or so\.

**Comment by p5pRT** [comment]
### From arthur@contiller.se


On lördag\, jan 4\, 2003\, at 02&#8203;:22 Europe/Stockholm\, Dave Mitchell wrote&#8203;:

> On Sat\, Jan 04\, 2003 at 01&#8203;:09&#8203;:09AM \-0000\, Arthur Bergman wrote&#8203;:
>> Hi\,
>>
>> Can you see if this still applies? I think I might have fixed it 
>> before
>> 5\.8 came out\. I can't reproduce it on linux\.
>
>
> On a copy of 18378 I have lying around\, I can get strange effects
> on Linux by executing some code that reallocs stuff between the joins&#8203;:
>
>     use threads;
>     my $a = 'x'x 1; \#just a hook for the debugger
>
>     my $t = threads\->new\(sub \{\}\);
>     $t\->join;
>     for \(1\.\.100\) \{
>     $a\[$\_\] = "\\0xff" x $\_;
>     \}
>
>     $t\->join;
>
> \[davem@&#8203;percy 18378t\]$ \./perl \-Ilib /tmp/p
> Name "main&#8203;::a" used only once&#8203;: possible typo at /tmp/p line 9\.
> panic&#8203;: MUTEX\_LOCK at /tmp/p line 12\.
>
> So I guess the bug is still active :\-\(
>
>

Gah\, how annoying\. Some seems very prematurely freed\.

Can someone run a memory verifier on this and see what is going on 
please?

Thanks

Arthur

**Comment by p5pRT** [comment]
### From arthur@contiller.se

Hi\,

Seems like substandard operating systems that actually free freed memory had a 
problem :\-\)

This patch fixes this since destroy works\.

Arthur

**Comment by p5pRT** [comment]
### From arthur@contiller.se

<details><summary>19240.patch</summary>

```diff
--- ext/threads/t/join.t-19239	Wed Apr 16 19:37:42 2003
+++ ext/threads/t/join.t	Wed Apr 16 19:37:45 2003
@@ -10,7 +10,7 @@
 
 use ExtUtils::testlib;
 use strict;
-BEGIN { print "1..11\n" };
+BEGIN { print "1..12\n" };
 use threads;
 use threads::shared;
 
@@ -117,4 +117,17 @@
   }
 } else {
   skip("\$0 check: only on Linux");
+}
+
+{
+    my $t = threads->new(sub {});
+    $t->join;
+    my $x = threads->new(sub {});
+    $x->join;
+    eval {
+      $t->join;
+    };
+    my $ok = 0;
+    $ok++ if($@ =~/Thread already joined/);
+    ok($ok, "Double join works");
 }
--- ext/threads/threads.xs-19239	Wed Apr 16 19:37:51 2003
+++ ext/threads/threads.xs	Wed Apr 16 19:37:53 2003
@@ -601,7 +601,7 @@
 	/* We have finished with it */
 	thread->state |= PERL_ITHR_JOINED;
 	MUTEX_UNLOCK(&thread->mutex);
-    	sv_unmagic(SvRV(obj),PERL_MAGIC_shared_scalar);
+    	
 	return retparam;
     }
     return (AV*)NULL;

```
</details>

**Comment by p5pRT** [comment]
arthur@contiller.se - Status changed from 'open' to 'resolved'
