### ISSUE TITLE
locale test core dump 5.8.0 release

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#5886]
Migrated from [rt.perl.org#16930](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=16930) (status was 'rejected')

Searchable as RT16930$

**Comment by p5pRT** [comment]
### From prlw1@newn.cam.ac.uk

#### Created by prlw1@newn.cam.ac.uk


lib/locale\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.Segmentation fault \- core dumped
FAILED at test 99
\#0  0x481c7c88 in vfprintf \(\) from /usr/lib/libc\.so\.12
\#1  0x481c34ae in snprintf \(\) from /usr/lib/libc\.so\.12
\#2  0x481b9330 in \_xpg4\_setrunelocale \(\) from /usr/lib/libc\.so\.12
\#3  0x481b8f30 in \_\_setlocale \(\) from /usr/lib/libc\.so\.12
\#4  0x481b8cdc in \_\_setlocale \(\) from /usr/lib/libc\.so\.12
\#5  0x481b8a6f in \_\_setlocale\_mb\_len\_max\_32 \(\) from /usr/lib/libc\.so\.12
\#6  0x4820f5b6 in XS\_POSIX\_setlocale \(cv=0x8135bc4\) at POSIX\.xs&#8203;:1067
\#7  0x80b5e96 in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:2773
\#8  0x80a1f31 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1398
\#9  0x8066ed3 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1676
\#10 0x8066bfc in perl\_run \(my\_perl=0x812d030\) at perl\.c&#8203;:1600
\#11 0x8063fa3 in main \(argc=5\, argv=0xbfbfd7f8\, env=0xbfbfd810\)
&nbsp;    at perlmain\.c&#8203;:85
\#12 0x805e9e0 in \_\_\_start \(\)
\(gdb\) frame 6
\#6  0x4820f5b6 in XS\_POSIX\_setlocale \(cv=0x8135bc4\) at POSIX\.xs&#8203;:1067
1067            RETVAL = setlocale\(category\, locale\);
\(gdb\) print category
$1 = 0
\(gdb\) print locale
$2 = 0x885dbb1f \<Address 0x885dbb1f out of bounds>
\(gdb\) frame 7
\#7  0x80b5e96 in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:2773
2773                \(void\)\(\*CvXSUB\(cv\)\)\(aTHX\_ cv\);
\(gdb\) list
2768                    SAVEVPTR\(PL\_curcop\);
2769                    PL\_curcop = PL\_curcopdb;
2770                    PL\_curcopdb = NULL;
2771                \}
2772                /\* Do we need to open block here? XXXX \*/
2773                \(void\)\(\*CvXSUB\(cv\)\)\(aTHX\_ cv\);

What of the XXX ?


\(gdb\) print cv
$3 = \(CV \*\) 0x8135bc4
\(gdb\) print \*cv
$4 = \{sv\_any = 0x813ef90\, sv\_refcnt = 2\, sv\_flags = 12\}
\(gdb\) print \*cv\->sv\_any
$5 = \{xpv\_pv = 0x0\, xpv\_cur = 0\, xpv\_len = 0\, xof\_off = 0\, xnv\_nv = 0\, 
&nbsp;  xmg\_magic = 0x0\, xmg\_stash = 0x0\, xcv\_stash = 0x0\, xcv\_start = 0x0\, 
&nbsp;  xcv\_root = 0x0\, xcv\_xsub = 0x4820f4d0 \<XS\_POSIX\_setlocale>\, xcv\_xsubany = \{
&nbsp;    any\_ptr = 0x0\, any\_i32 = 0\, any\_iv = 0\, any\_long = 0\, any\_dptr = 0\, 
&nbsp;    any\_dxptr = 0\}\, xcv\_gv = 0x8135bac\, xcv\_file = 0x4821801e "POSIX\.c"\, 
&nbsp;  xcv\_depth = 0\, xcv\_padlist = 0x0\, xcv\_outside = 0x0\, xcv\_flags = 0\}

What now?\!

<details><summary>Perl Info</summary>

```

Flags:
    category=library
    severity=high

Site configuration information for perl v5.8.0:

Configured by prlw1 at Mon Jul 15 19:49:14 BST 2002.

Summary of my perl5 (revision 5.0 version 8 subversion 0) configuration:
  Platform:
    osname=netbsd, osvers=1.6d, archname=i386-netbsd
    uname='netbsd gx240.newn.cam.ac.uk 1.6d netbsd 1.6d (admin) #12: wed jul 10 16:07:48 bst 2002 prlw1@quartz.newn.cam.ac.uk:usrsrcsysarchi386compileadmin i386 '
    config_args=''
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing',
    optimize='-O2',
    cppflags='-fno-strict-aliasing'
    ccversion='', gccversion='2.95.3 20010315 (release) (NetBSD nb2)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =''
    libpth=/usr/lib
    libs=-lm -lc -lposix -lcrypt -lutil
    perllibs=-lm -lc -lposix -lcrypt -lutil
    libc=/usr/lib/libc.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-whole-archive -lgcc -Wl,-no-whole-archive 			-Wl,-E '
    cccdlflags='-DPIC -fPIC ', lddlflags='--whole-archive -shared '

Locally applied patches:
    


@INC for perl v5.8.0:
    /usr/local/lib/perl5/5.8.0/i386-netbsd
    /usr/local/lib/perl5/5.8.0
    /usr/local/lib/perl5/site_perl/5.8.0/i386-netbsd
    /usr/local/lib/perl5/site_perl/5.8.0
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.8.0:
    HOME=/home/prlw1
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/prlw1/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
    PERL_BADLANG (unset)
    SHELL=/bin/csh

```
</details>

**Comment by p5pRT** [comment]
### From @rgs

Patrick Welche \(via RT\) \<perlbug@&#8203;perl\.org> wrote&#8203;:
> lib/locale\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.Segmentation fault \- core dumped
> FAILED at test 99
> \#0  0x481c7c88 in vfprintf \(\) from /usr/lib/libc\.so\.12

I suspect something is broken on your OS because\.\.\.\.

> \#7  0x80b5e96 in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:2773
> 2773                \(void\)\(\*CvXSUB\(cv\)\)\(aTHX\_ cv\);
> \(gdb\) list
> 2768                    SAVEVPTR\(PL\_curcop\);
> 2769                    PL\_curcop = PL\_curcopdb;
> 2770                    PL\_curcopdb = NULL;
> 2771                \}
> 2772                /\* Do we need to open block here? XXXX \*/
> 2773                \(void\)\(\*CvXSUB\(cv\)\)\(aTHX\_ cv\);
> 
> What of the XXX ?

\.\.\.\.\.\. this doesn't look like the cause of your problem\.

> Environment for perl v5\.8\.0&#8203;:
>     HOME=/home/prlw1
>     LANG \(unset\)
>     LANGUAGE \(unset\)
>     LD\_LIBRARY\_PATH \(unset\)
>     LOGDIR \(unset\)
>     PATH=/home/prlw1/bin&#8203;:/bin&#8203;:/sbin&#8203;:/usr/bin&#8203;:/usr/sbin&#8203;:/usr/local/bin&#8203;:/usr/local/sbin
>     PERL\_BADLANG \(unset\)
>     SHELL=/bin/csh

Had you tried setting LANG ? LC\_ALL ?

If you want a workaround : you can disable perl's locale support
by passing the argument \-Accflags=\-DNO\_LOCALE to Configure\.

**Comment by p5pRT** [comment]
### From @jhi

I would stay at frame 6 and try to figure out how the locale ended
up being bad \(Address 0x885dbb1f out of bounds\)\.  I suggest a breakpoint
at the entry of that frame\.

**Comment by p5pRT** [comment]
### From @chorny

Sep 02 06&#8203;:22&#8203;:09 2002\, prlw1@&#8203;newn\.cam\.ac\.uk wrote&#8203;:

Can you retest with 5\.10\.0?

> This is a bug report for perl from prlw1@&#8203;newn\.cam\.ac\.uk\,
> generated with the help of perlbug 1\.34 running under perl
> v5\.8\.0\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> lib/locale\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.Segmentation fault \- core dumped
> FAILED at test 99
> \#0  0x481c7c88 in vfprintf \(\) from /usr/lib/libc\.so\.12
> \#1  0x481c34ae in snprintf \(\) from /usr/lib/libc\.so\.12
> \#2  0x481b9330 in \_xpg4\_setrunelocale \(\) from /usr/lib/libc\.so\.12
> \#3  0x481b8f30 in \_\_setlocale \(\) from /usr/lib/libc\.so\.12
> \#4  0x481b8cdc in \_\_setlocale \(\) from /usr/lib/libc\.so\.12
> \#5  0x481b8a6f in \_\_setlocale\_mb\_len\_max\_32 \(\) from
> /usr/lib/libc\.so\.12
> \#6  0x4820f5b6 in XS\_POSIX\_setlocale \(cv=0x8135bc4\) at POSIX\.xs&#8203;:1067
> \#7  0x80b5e96 in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:2773
> \#8  0x80a1f31 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1398
> \#9  0x8066ed3 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1676
> \#10 0x8066bfc in perl\_run \(my\_perl=0x812d030\) at perl\.c&#8203;:1600
> \#11 0x8063fa3 in main \(argc=5\, argv=0xbfbfd7f8\, env=0xbfbfd810\)
>     at perlmain\.c&#8203;:85
> \#12 0x805e9e0 in \_\_\_start \(\)
> \(gdb\) frame 6
> \#6  0x4820f5b6 in XS\_POSIX\_setlocale \(cv=0x8135bc4\) at POSIX\.xs&#8203;:1067
> 1067            RETVAL = setlocale\(category\, locale\);
> \(gdb\) print category
> $1 = 0
> \(gdb\) print locale
> $2 = 0x885dbb1f \<Address 0x885dbb1f out of bounds>
> \(gdb\) frame 7
> \#7  0x80b5e96 in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:2773
> 2773                \(void\)\(\*CvXSUB\(cv\)\)\(aTHX\_ cv\);
> \(gdb\) list
> 2768                    SAVEVPTR\(PL\_curcop\);
> 2769                    PL\_curcop = PL\_curcopdb;
> 2770                    PL\_curcopdb = NULL;
> 2771                \}
> 2772                /\* Do we need to open block here? XXXX \*/
> 2773                \(void\)\(\*CvXSUB\(cv\)\)\(aTHX\_ cv\);
> 
> What of the XXX ?
> 
> 
> \(gdb\) print cv
> $3 = \(CV \*\) 0x8135bc4
> \(gdb\) print \*cv
> $4 = \{sv\_any = 0x813ef90\, sv\_refcnt = 2\, sv\_flags = 12\}
> \(gdb\) print \*cv\->sv\_any
> $5 = \{xpv\_pv = 0x0\, xpv\_cur = 0\, xpv\_len = 0\, xof\_off = 0\, xnv\_nv = 0\,
>   xmg\_magic = 0x0\, xmg\_stash = 0x0\, xcv\_stash = 0x0\, xcv\_start = 0x0\,
>   xcv\_root = 0x0\, xcv\_xsub = 0x4820f4d0 \<XS\_POSIX\_setlocale>\,
> xcv\_xsubany = \{
>     any\_ptr = 0x0\, any\_i32 = 0\, any\_iv = 0\, any\_long = 0\, any\_dptr =
> 0\,
>     any\_dxptr = 0\}\, xcv\_gv = 0x8135bac\, xcv\_file = 0x4821801e
> "POSIX\.c"\,
>   xcv\_depth = 0\, xcv\_padlist = 0x0\, xcv\_outside = 0x0\, xcv\_flags = 0\}
> 
> What now?\!
> 
> \[Please do not change anything below this line\]
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \-\-\-
> Flags&#8203;:
>     category=library
>     severity=high
> \-\-\-
> Site configuration information for perl v5\.8\.0&#8203;:
> 
> Configured by prlw1 at Mon Jul 15 19&#8203;:49&#8203;:14 BST 2002\.
> 
> Summary of my perl5 \(revision 5\.0 version 8 subversion 0\)
> configuration&#8203;:
>   Platform&#8203;:
>     osname=netbsd\, osvers=1\.6d\, archname=i386\-netbsd
>     uname='netbsd gx240\.newn\.cam\.ac\.uk 1\.6d netbsd 1\.6d \(admin\) \#12&#8203;:
> wed jul 10 16&#8203;:07&#8203;:48 bst 2002
> prlw1@&#8203;quartz\.newn\.cam\.ac\.uk&#8203;:usrsrcsysarchi386compileadmin i386 '
>     config\_args=''
>     hint=recommended\, useposix=true\, d\_sigaction=define
>     usethreads=undef use5005threads=undef useithreads=undef
> usemultiplicity=undef
>     useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
>     use64bitint=undef use64bitall=undef uselongdouble=undef
>     usemymalloc=n\, bincompat5005=undef
>   Compiler&#8203;:
>     cc='cc'\, ccflags ='\-fno\-strict\-aliasing'\,
>     optimize='\-O2'\,
>     cppflags='\-fno\-strict\-aliasing'
>     ccversion=''\, gccversion='2\.95\.3 20010315 \(release\) \(NetBSD nb2\)'\,
> gccosandvers=''
>     intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
>     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\,
> longdblsize=12
>     ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,
> lseeksize=8
>     alignbytes=4\, prototype=define
>   Linker and Libraries&#8203;:
>     ld='cc'\, ldflags =''
>     libpth=/usr/lib
>     libs=\-lm \-lc \-lposix \-lcrypt \-lutil
>     perllibs=\-lm \-lc \-lposix \-lcrypt \-lutil
>     libc=/usr/lib/libc\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
>     gnulibc\_version=''
>   Dynamic Linking&#8203;:
>     dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-
> whole\-archive \-lgcc \-Wl\,\-no\-whole\-archive             \-Wl\,\-E '
>     cccdlflags='\-DPIC \-fPIC '\, lddlflags='\-\-whole\-archive \-shared '
> 
> Locally applied patches&#8203;:
> 
> 
> \-\-\-
> @&#8203;INC for perl v5\.8\.0&#8203;:
>     /usr/local/lib/perl5/5\.8\.0/i386\-netbsd
>     /usr/local/lib/perl5/5\.8\.0
>     /usr/local/lib/perl5/site\_perl/5\.8\.0/i386\-netbsd
>     /usr/local/lib/perl5/site\_perl/5\.8\.0
>     /usr/local/lib/perl5/site\_perl
>     \.
> 
> \-\-\-
> Environment for perl v5\.8\.0&#8203;:
>     HOME=/home/prlw1
>     LANG \(unset\)
>     LANGUAGE \(unset\)
>     LD\_LIBRARY\_PATH \(unset\)
>     LOGDIR \(unset\)
>    
PATH=/home/prlw1/bin&#8203;:/bin&#8203;:/sbin&#8203;:/usr/bin&#8203;:/usr/sbin&#8203;:/usr/local/bin&#8203;:/usr/local/sbin
>     PERL\_BADLANG \(unset\)
>     SHELL=/bin/csh


\-\- 
Alexandr Ciornii\, http&#8203;://chorny\.net

**Comment by p5pRT** [comment]
### From @Hugmeir

On Fri Dec 19 04&#8203;:51&#8203;:38 2008\, chorny wrote&#8203;:
> Sep 02 06&#8203;:22&#8203;:09 2002\, prlw1@&#8203;newn\.cam\.ac\.uk wrote&#8203;:
> 
> Can you retest with 5\.10\.0?
> 

Or 5\.16\.0\, for that matter\. Seeing how this ticket has been silent for a
few years now\, I recommend leaving it open for thirty more days\, then
closing it unless we get new information or other complains\.

\-\-hugmeir

**Comment by p5pRT** [comment]
### From @jkeenan

On Fri May 25 17&#8203;:10&#8203;:08 2012\, Hugmeir wrote&#8203;:
> On Fri Dec 19 04&#8203;:51&#8203;:38 2008\, chorny wrote&#8203;:
> > Sep 02 06&#8203;:22&#8203;:09 2002\, prlw1@&#8203;newn\.cam\.ac\.uk wrote&#8203;:
> > 
> > Can you retest with 5\.10\.0?
> > 
> 
> Or 5\.16\.0\, for that matter\. Seeing how this ticket has been silent for a
> few years now\, I recommend leaving it open for thirty more days\, then
> closing it unless we get new information or other complains\.
> 
> \-\-hugmeir

Closing it per recommendation from Hugmeir\.

**Comment by p5pRT** [comment]
@jkeenan - Status changed from 'open' to 'rejected'
