### ISSUE TITLE
Problem with perl 5.6.1, Tru64 5.1A+pk3, and usemymalloc

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#5932]
Migrated from [rt.perl.org#17384](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=17384) (status was 'rejected')

Searchable as RT17384$

**Comment by p5pRT** [comment]
### From cmadams@hiwaay.net

#### Created by cmadams@hiwaay.net



I'm running perl 5\.6\.1 on Tru64 5\.1A\.  Since installing HPAQ patch kit 3
last week\, I'm having some trouble with certain of my system admin
scripts\.  I've narrowed it down to one change \- a new libc\.so \(which is
of course rather major\)\.  According to the release notes for this patch
\(which are available at&#8203;:

http&#8203;://ftp\.support\.compaq\.com/patches/public/Digital\_UNIX/v5\.1a/Tru64\_UNIX\_V5\.1A/doc/txt/OSFPAT00080700520\.txt

there are a couple of changes to the sytem malloc\(\)\.

The problem I'm seeing is this&#8203;: a certain script crashes with an SIGILL
\(Illegal instruction\)\.  The script generates random\, semi\-pronouncable
passwords\.  It successfully generates 4\-6 passwords and then gets
SIGILL\.  I'm running it with \-T; if I take that off\, it doesn't crash\.
If I add \-MCarp \_before\_ other module loads\, it doesn't crash\.  There
are no compiled/XS modules involved \(I've trussed the process\, and the
only binaries that get loaded are /usr/local/bin/perl\, libm\.so\,
libiconv\.so\, and libc\.so\)\.  I tried to strip down my code for generating
and testing passwords \(to make a simple test case\)\, but if I remove
certain lines \(even if they are just comments\)\, it doesn't crash\.

When I look at the core dump\, I see&#8203;:

Thread terminated at PC 0x140246004 by signal ILL
\(ladebug\) where
>0  0x140246004
\#1  0x3ff800e2294 in \_\_nl\_langinfo\(0x2c\, 0x3ffc009a608\, 0x11fffba07\, 0x11fffb9f8\, 0x0\, 0x3a3a6400\) in /usr/shlib/libc\.so
\#2  0x3ff801ba688 in \_\_gcvt\(0x2c\, 0x3ffc009a608\, 0x11fffba07\, 0x11fffb9f8\, 0x0\, 0x3a3a6400\) in /usr/shlib/libc\.so
\#3  0x12005c708 in Perl\_sv\_2pv\(0x2c\, 0x3ffc009a608\, 0x11fffba07\, 0x11fffb9f8\, 0x0\, 0x3a3a6400\) in /usr/local/bin/perl
\#4  0x12005f8b8 in Perl\_sv\_catsv\(0x2c\, 0x3ffc009a608\, 0x11fffba07\, 0x11fffb9f8\, 0x0\, 0x3a3a6400\) in /usr/local/bin/perl
\#5  0x12006aa68 in Perl\_pp\_concat\(0x2c\, 0x3ffc009a608\, 0x11fffba07\, 0x11fffb9f8\, 0x0\, 0x3a3a6400\) in /usr/local/bin/perl
\#6  0x1200fc474 in Perl\_runops\_standard\(0x2c\, 0x3ffc009a608\, 0x11fffba07\, 0x11fffb9f8\, 0x0\, 0x3a3a6400\) in /usr/local/bin/perl
\#7  0x120026054 in perl\_run\(0x2c\, 0x3ffc009a608\, 0x11fffba07\, 0x11fffb9f8\, 0x0\, 0x3a3a6400\) in /usr/local/bin/perl
\#8  0x120021b30 in main\(0x2c\, 0x3ffc009a608\, 0x11fffba07\, 0x11fffb9f8\, 0x0\, 0x3a3a6400\) in /usr/local/bin/perl
\#9  0x120021a18 in \_\_start\(0x2c\, 0x3ffc009a608\, 0x11fffba07\, 0x11fffb9f8\, 0x0\, 0x3a3a6400\) in /usr/local/bin/perl

0x2c is the nl\_langinfo define for RADIXCHAR\.  If I define a locale \(the
only two available are POSIX and en\_US\.ISO8859\-1\)\, it doesn't crash\.  If
I leave it in the default C locale\, it crashes\.

Tru64 comes with perl 5\.6\.0 in /usr/lib/perl5\.6\.0\.  If I run with that
perl instead of the perl I compiled\, it doesn't crash\.  So\, I looked at
how they were configured\.  The only significant differences I see are
that HPAQ compiled with "\-Dusemymalloc=no" and I compiled with
"\-Ubincompat5005 \-Uuseshrplib" \(I couldn't get mod\_perl to work
otherwise\)\.

I rebuilt perl 5\.6\.1 with my options plus "\-Dusemymalloc=no"\, and it
does not crash\.  So\, it would seem that there is some conflict between
perl's malloc and the "new & improved" malloc included in Tru64 5\.1A
patch kit 3 libc\.so\.

I'm not sure that reporting this to HPAQ is going to go anywhere
\(especially since their perl works\)\.  Is there anything I can do to
further debug/trace this?  If not\, will installing a new perl with
"\-Dusemymalloc=no" configured require me to rebuild all compiled
modules \(is that a binary incompatible change\)?

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.6.1:

Configured by cmadams at Tue Feb 12 12:31:21 CST 2002.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=dec_osf, osvers=5.1, archname=alpha-dec_osf
    uname='osf1 dns.hiwaay.net v5.1 1885 alpha '
    config_args='-des -Dinstallprefix=/usr/local -Dprefix=/usr/local -Dvendorprefix=/usr/local/hiwaay -Dvendorlib=/usr/local/hiwaay/lib/perl5 -Dd_dosuid -Dman3ext=3pm -Ubincompat5005 -Dcf_email=cmadams@hiwaay.net -Dperladmin=cmadams@hiwaay.net -Uuseshrplib -Dpager=/usr/bin/more'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=define use64bitall=define uselongdouble=undef
  Compiler:
    cc='cc', ccflags ='-std -fprm d -ieee -D_INTRINSICS -I/usr/local/include -DLANGUAGE_C',
    optimize='-O4',
    cppflags='-std -fprm d -ieee -D_INTRINSICS -I/usr/local/include -DLANGUAGE_C'
    ccversion='V6.4-014', gccversion='', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, usemymalloc=y, prototype=define
  Linker and Libraries:
    ld='ld', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /usr/shlib /usr/ccs/lib /usr/lib/cmplrs/cc /usr/lib /var/shlib
    libs=-ldbm -ldb -lm -liconv -lutil
    perllibs=-lm -liconv -lutil
    libc=/usr/shlib/libc.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags='-shared -expect_unresolved "*" -O4 -msym -std -s -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.1:
    /usr/local/lib/perl5/5.6.1/alpha-dec_osf
    /usr/local/lib/perl5/5.6.1
    /usr/local/lib/perl5/site_perl/5.6.1/alpha-dec_osf
    /usr/local/lib/perl5/site_perl/5.6.1
    /usr/local/lib/perl5/site_perl
    /usr/local/hiwaay/lib/perl5/alpha-dec_osf
    /usr/local/hiwaay/lib/perl5
    /usr/local/hiwaay/lib/perl5
    .


Environment for perl v5.6.1:
    HOME=/usr/users/cmadams
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/users/cmadams/bin:/usr/local/hiwaay/bin:/usr/local/bin:/usr/bin:/usr/bin/X11:/usr/opt/svr4/usr/bin:/usr/local/hiwaay/sbin:/usr/local/sbin:/usr/sbin:/sbin:.
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @iabyn

I'm closing this as it very old\, very version/OS specific\, and 
not reproducible\.

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'new' to 'rejected'
