### ISSUE TITLE
Segfault in perl 5.8.0 while running map { ... }

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6044]
Migrated from [rt.perl.org#18153](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=18153) (status was 'resolved')

Searchable as RT18153$

**Comment by p5pRT** [comment]
### From josh@chamas.com

#### Created by josh@chamas.com


This is a bug report for perl from josh@&#8203;chamas\.com\,
generated with the help of perlbug 1\.34 running under perl v5\.8\.0\.


\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

Dear Perl Gurus\,

I have isolated a segfault down to a few lines of perl code that 
runs fine with no output on 5\.6\.1\.  Its taken from an application
that I found to segfault under perl 5\.8\.0 & mod\_perl\, but I got it
to segfault just fine with command line perl 5\.8\.0&#8203;:

\#\!/usr/bin/perl

$var = 2;
map \{                 
&nbsp;    if\($var eq $\_\) \{
&nbsp;    \} else \{
&nbsp;    \}
\} \(2\)
;

That's it\.\.\. the stack trace I get after the segfault from running this program is&#8203;:

\(gdb\) run test\.pl
Starting program&#8203;: /usr/local/bin/perl test\.pl

Program received signal SIGSEGV\, Segmentation fault\.
0x080bd6ef in Perl\_pp\_mapwhile \(\) at eval\.c&#8203;:41
41      eval\.c&#8203;: No such file or directory\.
&nbsp;        in eval\.c
\(gdb\) bt
\#0  0x080bd6ef in Perl\_pp\_mapwhile \(\) at eval\.c&#8203;:41
\#1  0x0809d6b2 in Perl\_runops\_standard \(\) at eval\.c&#8203;:41
\#2  0x0805f424 in S\_run\_body \(\) at eval\.c&#8203;:41
\#3  0x0805f18a in perl\_run \(\) at eval\.c&#8203;:41
\#4  0x0805cbc3 in main \(\) at eval\.c&#8203;:41
\#5  0x40089657 in \_\_libc\_start\_main \(main=0x805cb40 \<main>\, argc=2\, 
&nbsp;    ubp\_av=0xbffff944\, init=0x805bce8 \<\_init>\, fini=0x80f4af0 \<\_fini>\, 
&nbsp;    rtld\_fini=0x4000dcd4 \<\_dl\_fini>\, stack\_end=0xbffff93c\)
&nbsp;    at \.\./sysdeps/generic/libc\-start\.c&#8203;:129
\(gdb\) 

Note\, I rated this a medium severity since it seems this bug could
affect a lot of people with how simple the code is to reproduce it\.

Thanks\,

Josh

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.8.0:

Configured by job at Mon Oct 21 12:11:21 PDT 2002.

Summary of my perl5 (revision 5.0 version 8 subversion 0) configuration:
  Platform:
    osname=linux, osvers=2.4.7-10smp, archname=i686-linux
    uname='linux gate 2.4.7-10smp #1 smp thu sep 6 17:09:31 edt 2001 i686 unknown '
    config_args='-d'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm',
    optimize='-O2',
    cppflags='-fno-strict-aliasing -I/usr/local/include -I/usr/include/gdbm'
    ccversion='', gccversion='2.96 20000731 (Red Hat Linux 7.2 2.96-108.7.2)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lndbm -lgdbm -ldl -lm -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lcrypt -lutil
    libc=/lib/libc-2.2.4.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.2.4'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.0:
    /usr/local/lib/perl5/5.8.0/i686-linux
    /usr/local/lib/perl5/5.8.0
    /usr/local/lib/perl5/site_perl/5.8.0/i686-linux
    /usr/local/lib/perl5/site_perl/5.8.0
    /usr/local/lib/perl5/site_perl/5.6.1
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.8.0:
    HOME=/root
    LANG=en_US
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/local/apache/bin:/usr/local/java/bin:/usr/local/mysql/bin:/root/mlink/scripts:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin/X11:/usr/X11R6/bin:/root/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @nwc10

On Tue\, Oct 29\, 2002 at 08&#8203;:04&#8203;:19PM \-0000\, josh@&#8203;chamas\.com \(via RT\) wrote&#8203;:
> I have isolated a segfault down to a few lines of perl code that 
> runs fine with no output on 5\.6\.1\.  Its taken from an application
> that I found to segfault under perl 5\.8\.0 & mod\_perl\, but I got it
> to segfault just fine with command line perl 5\.8\.0&#8203;:
> 
> \#\!/usr/bin/perl
> 
> $var = 2;
> map \{                 
>     if\($var eq $\_\) \{
>     \} else \{
>     \}
> \} \(2\)
> ;
> 
> That's it\.\.\. the stack trace I get after the segfault from running this program is&#8203;:

Thanks for getting this down to a really short test case\.

I've found that I can actually get it a bit shorter&#8203;:

$ perl5\.8\.0 \-le 'map \{if \($\_\)\{\}\} \(2\)'
Segmentation fault
$ perl5\.8\.0 \-le 'map \{if \($\(\)\{\}\} \(2\)'
Segmentation fault
$ perl5\.8\.0 \-le 'map \{if \($\)\)\{\}\} \(2\)'
Segmentation fault

It seems that the special thing is going into the if\, as I find

$ perl5\.8\.0 \-le '$a = 1; map \{if \($a\)\{\}\} \(2\)'
Segmentation fault
$ perl5\.8\.0 \-le '$a = 0; map \{if \($a\)\{\}\} \(2\)'
$ perl5\.8\.0 \-le '$a = 0; map \{unless \($a\)\{\}\} \(2\)'
Segmentation fault
$ perl5\.8\.0 \-le '$a = 1; map \{unless \($a\)\{\}\} \(2\)'

I don't have any idea what the actual cause is\, or how to fix it\.

Nicholas Clark
\-\- 
Befunge better than perl?    http&#8203;://www\.perl\.org/advocacy/spoofathon/

**Comment by p5pRT** [comment]
### From @iabyn

On Wed\, Oct 30\, 2002 at 09&#8203;:31&#8203;:35PM \+0000\, Nicholas Clark wrote&#8203;:
> $ perl5\.8\.0 \-le '$a = 1; map \{if \($a\)\{\}\} \(2\)'
> Segmentation fault
> $ perl5\.8\.0 \-le '$a = 0; map \{if \($a\)\{\}\} \(2\)'

I get the following&#8203;:

5\.8\.0 \- segfault
17914 \- segfault
17974 \- segfault
18020 \- fine
18052 \- fine

So either it's been fixed recently\, or Herr Heisenburg is involved\.

\-\- 
That he said that that that that is is is debatable\, is debatable\.

**Comment by p5pRT** [comment]
### From @pjcj

On Wed\, Oct 30\, 2002 at 10&#8203;:44&#8203;:53PM \+0000\, Dave Mitchell wrote&#8203;:
> On Wed\, Oct 30\, 2002 at 09&#8203;:31&#8203;:35PM \+0000\, Nicholas Clark wrote&#8203;:
> > $ perl5\.8\.0 \-le '$a = 1; map \{if \($a\)\{\}\} \(2\)'
> > Segmentation fault
> > $ perl5\.8\.0 \-le '$a = 0; map \{if \($a\)\{\}\} \(2\)'
> 
> I get the following&#8203;:
> 
> 5\.8\.0 \- segfault
> 17914 \- segfault
> 17974 \- segfault
> 18020 \- fine
> 18052 \- fine
> 
> So either it's been fixed recently\, or Herr Heisenburg is involved\.

I would suspect bug 17771 fixed by 17998\.

Funny how the bug numbers and change numbers are almost in sync \.\.\.

\-\- 
Paul Johnson \- paul@&#8203;pjcj\.net
http&#8203;://www\.pjcj\.net

**Comment by p5pRT** [comment]
### From josh@chamas.com

Dave Mitchell \(via RT\) wrote&#8203;:
> On Wed\, Oct 30\, 2002 at 09&#8203;:31&#8203;:35PM \+0000\, Nicholas Clark wrote&#8203;:
> 
>>$ perl5\.8\.0 \-le '$a = 1; map \{if \($a\)\{\}\} \(2\)'
>>Segmentation fault
>>$ perl5\.8\.0 \-le '$a = 0; map \{if \($a\)\{\}\} \(2\)'
> 
> 

Thanks for looking into this so quickly\.  I'll keep
hoping that it stays fixed for the next release\.

Regards\,

Josh

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
Josh Chamas\, Founder                   phone&#8203;:925\-552\-0128
Chamas Enterprises Inc\.                http&#8203;://www\.chamas\.com
NodeWorks Link Checking                http&#8203;://www\.nodeworks\.com

**Comment by p5pRT** [comment]
### From @jhi

I now added one of the variants of the bug to the test suite\, so that this bug won't have a chance of sneaking back in\.   I'm marking the problem ticket as resolved\.

**Comment by p5pRT** [comment]
@jhi - Status changed from 'new' to 'resolved'
