### ISSUE TITLE
'goto' confuses 'redo'

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6148]
Migrated from [rt.perl.org#19061](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=19061) (status was 'resolved')

Searchable as RT19061$

**Comment by p5pRT** [comment]
### From @mjdominus

#### Created by @mjdominus



&nbsp;        my $n = 1;

&nbsp;        sub blah \{
&nbsp;         TOP&#8203;: \{
&nbsp;            if \($n\) \{
&nbsp;              $n \-= 1;
&nbsp;              redo TOP;
&nbsp;            MIDDLE&#8203;:
&nbsp;              redo TOP;         \# I'm line 8
&nbsp;            \}
&nbsp;          \}
&nbsp;          goto MIDDLE;
&nbsp;        \}

&nbsp;        blah\(\);

&nbsp;        plover% perl5\.7\.3 /tmp/bug\.pl
&nbsp;        Label not found for "redo TOP" at /tmp/bug\.pl line 8\.

I don't know what's going on here\, and I don't have time to
investigate it\, but I bet it could be used to demonstrate even more
serious bugs\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.6.1:

Configured by root at Sat Dec 29 11:54:59 EST 2001.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=linux, osvers=2.4.2-2, archname=i586-linux
    uname='linux plover.com 2.4.2-2 #1 sun apr 8 19:37:14 edt 2001 i586 unknown '
    config_args='-des'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2',
    cppflags='-fno-strict-aliasing'
    ccversion='', gccversion='2.96 20000731 (Red Hat Linux 7.1 2.96-81)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lndbm -lgdbm -ldb -ldl -lm -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lcrypt -lutil
    libc=/lib/libc-2.2.2.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.1:
    /usr/local/lib/perl5/5.6.1/i586-linux
    /usr/local/lib/perl5/5.6.1
    /usr/local/lib/perl5/site_perl/5.6.1/i586-linux
    /usr/local/lib/perl5/site_perl/5.6.1
    /usr/local/lib/perl5/site_perl/5.6.0/i586-linux
    /usr/local/lib/perl5/site_perl/5.6.0
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.6.1:
    HOME=/home/mjd
    LANG=C
    LANGUAGE (unset)
    LD_LIBRARY_PATH=/lib:/usr/lib:/usr/X11R6/lib
    LOGDIR (unset)
    PATH=/home/mjd/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/usr/games:/sbin:/usr/sbin:/usr/local/bin/X11R6:/usr/local/bin/mh:/data/mysql/bin:/usr/local/bin/pbm:/usr/local/bin/ezmlm:/home/mjd/TPI/bin:/usr/local/teTeX/bin:/usr/local/mysql/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @andk

>>>>> On 12 Dec 2002 04&#8203;:19&#8203;:22 \-0000\, Mark\-Jason Dominus \(via RT\) \<perlbug\-followup@&#8203;perl\.org> said&#8203;:

&nbsp;  > \# New Ticket Created by  Mark\-Jason Dominus 
&nbsp;  > \# Please include the string&#8203;:  \[perl \#19061\]
&nbsp;  > \# in the subject line of all future correspondence about this issue\. 
&nbsp;  > \# \<URL&#8203;: http&#8203;://rt\.perl\.org/rt2/Ticket/Display\.html?id=19061 >


&nbsp;  > This is a bug report for perl from mjd@&#8203;plover\.com\,
&nbsp;  > generated with the help of perlbug 1\.33 running under perl v5\.6\.1\.


&nbsp;  > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
&nbsp;  > \[Please enter your report here\]

&nbsp;  >         my $n = 1;

&nbsp;  >         sub blah \{
&nbsp;  >          TOP&#8203;: \{
&nbsp;  >             if \($n\) \{
&nbsp;  >               $n \-= 1;
&nbsp;  >               redo TOP;
&nbsp;  >             MIDDLE&#8203;:
&nbsp;  >               redo TOP;         \# I'm line 8
&nbsp;  >             \}
&nbsp;  >           \}
&nbsp;  >           goto MIDDLE;
&nbsp;  >         \}

&nbsp;  >         blah\(\);

&nbsp;  >         plover% perl5\.7\.3 /tmp/bug\.pl
&nbsp;  >         Label not found for "redo TOP" at /tmp/bug\.pl line 8\.

&nbsp;  > I don't know what's going on here\, and I don't have time to
&nbsp;  > investigate it\, but I bet it could be used to demonstrate even more
&nbsp;  > serious bugs\.

I think this is not a bug\. It's documented that goto\.\.\.

&nbsp;               \.\.\.may
&nbsp;               not be used to go into any construct that requires
&nbsp;               initialization\, such as a subroutine or a
&nbsp;               "foreach" loop\.

\-\- 
andreas

**Comment by p5pRT** [comment]
### From @mjdominus


Andreas Koenig&#8203;:
> I think this is not a bug\. It's documented that goto\.\.\.
> 
>                \.\.\.may
>                not be used to go into any construct that requires
>                initialization\, such as a subroutine or a
>                "foreach" loop\.
> 

I am not sure what construct you are referring to here\.

>   >         my $n = 1;
> 
>   >         sub blah \{
>   >          TOP&#8203;: \{
>   >             if \($n\) \{
>   >               $n \-= 1;
>   >               redo TOP;
>   >             MIDDLE&#8203;:
>   >               redo TOP;         \# I'm line 8
>   >             \}
>   >           \}
>   >           goto MIDDLE;
>   >         \}
> 
>   >         blah\(\);
> 
>   >         plover% perl5\.7\.3 /tmp/bug\.pl
>   >         Label not found for "redo TOP" at /tmp/bug\.pl line 8\.
> 

I am not going into a subroutine or a 'foreach' loop\.

**Comment by p5pRT** [comment]
### From @rgarcia

Mark Jason Dominus \<mjd@&#8203;plover\.com> wrote&#8203;:
> 
> Andreas Koenig&#8203;:
> > I think this is not a bug\. It's documented that goto\.\.\.
> > 
> >                \.\.\.may
> >                not be used to go into any construct that requires
> >                initialization\, such as a subroutine or a
> >                "foreach" loop\.
> > 
> 
> I am not sure what construct you are referring to here\.

The goto\(\) at the end\.

> >   >         my $n = 1;
> > 
> >   >         sub blah \{
> >   >          TOP&#8203;: \{
> >   >             if \($n\) \{
> >   >               $n \-= 1;
> >   >               redo TOP;
> >   >             MIDDLE&#8203;:
> >   >               redo TOP;         \# I'm line 8
> >   >             \}
> >   >           \}
> >   >           goto MIDDLE;
> >   >         \}
> > 
> >   >         blah\(\);
> > 
> >   >         plover% perl5\.7\.3 /tmp/bug\.pl
> >   >         Label not found for "redo TOP" at /tmp/bug\.pl line 8\.
> > 
> 
> I am not going into a subroutine or a 'foreach' loop\.

Yes you are : "LABEL BLOCK" is effectively a one\-time loop\, as documented
in L\<perlsyn/Basic BLOCKs and Switch Statements>\. So I think Andreas
is right : this is not a bug\.

**Comment by p5pRT** [comment]
### From ams@wiw.org

At 2002\-12\-12 11&#8203;:37&#8203;:12 \+0100\, raphel\.garcia\-suarez@&#8203;hexaflux\.com wrote&#8203;:
>
> > I am not going into a subroutine or a 'foreach' loop\.
> 
> Yes you are : "LABEL BLOCK" is effectively a one\-time loop

BLOCK is a one\-time loop too\. Should the following also fail to work?

goto FOO; \{ FOO&#8203;: print 1; \}

\-\- ams

**Comment by p5pRT** [comment]
### From @rgarcia

Abhijit Menon\-Sen \<ams@&#8203;wiw\.org> wrote&#8203;:
> 
> BLOCK is a one\-time loop too\. Should the following also fail to work?
> 
> goto FOO; \{ FOO&#8203;: print 1; \}

The goto bypasses the enterloop op\, which always performs some kind
of initialization\, in this case setting the proper label or mark
for redo/last/next inside the block/loop\. So the goto succeeds
indeed\, but any loop statement inside the loop will fail if it
can find the proper context to restore\.

$ bleadperl \-MO=Concise \-e 'goto FOO; \{ FOO&#8203;: print 1; \}'
b  \<@&#8203;> leave\[t1\] vKP/REFC \->\(end\)
1     \<0> enter \->2
2     \<;> nextstate\(main 1 \-e&#8203;:1\) v \->3
3     \<"> goto\("FOO"\) v \->4
4     \<;> nextstate\(main 2 \-e&#8203;:1\) v \->5
a     \<2> leaveloop vK/2 \->b
5        \<\{> enterloop\(next\->a last\->a redo\->6\) v \->6
\-        \<@&#8203;> lineseq vKP \->a
6           \<;> nextstate\(FOO&#8203;: main 1 \-e&#8203;:1\) v \->7
9           \<@&#8203;> print vK \->a
7              \<0> pushmark s \->8
8              \<$> const\(IV 1\) s \->9
\-e syntax OK

$ bleadperl \-Dt \-le 'goto FOO; \{ FOO&#8203;: print 1; \}'

EXECUTING\.\.\.

\(\-e&#8203;:0\)  enter
\(\-e&#8203;:0\)  nextstate
\(\-e&#8203;:1\)  goto
\(\-e&#8203;:1\)  nextstate       \<\-\- no enterloop
\(\-e&#8203;:1\)  pushmark
\(\-e&#8203;:1\)  const\(IV\(1\)\)
\(\-e&#8203;:1\)  print
1
\(\-e&#8203;:1\)  leaveloop
\(\-e&#8203;:1\)  leave


$ bleadperl \-le 'goto FOO; BAR&#8203;:\{ FOO&#8203;: print 1; redo BAR\}'
1
Label not found for "redo BAR" at \-e line 1\.

I don't think it's a bug\, even if this can be considered harmful ;\-\)

**Comment by p5pRT** [comment]
### From @rgarcia

I wrote&#8203;:
> indeed\, but any loop statement inside the loop will fail if it
> can find the proper context to restore\.
&nbsp;  ^^^
I meant "can't" of course\.

**Comment by p5pRT** [comment]
### From smcc@mit.edu

>>>>> "RG\-S" == Rafael Garcia\-Suarez \<raphel\.garcia\-suarez@&#8203;hexaflux\.com> writes&#8203;:

RG\-S> Abhijit Menon\-Sen \<ams@&#8203;wiw\.org> wrote&#8203;:
 
AMS> BLOCK is a one\-time loop too\. Should the following also fail to work?
 
AMS> goto FOO; \{ FOO&#8203;: print 1; \}

RG\-S> The goto bypasses the enterloop op\, which always performs some
RG\-S> kind of initialization\, in this case setting the proper label or
RG\-S> mark for redo/last/next inside the block/loop\. So the goto
RG\-S> succeeds indeed\, but any loop statement inside the loop will
RG\-S> fail if it can find the proper context to restore\.

RG\-S> $ bleadperl \-Dt \-le 'goto FOO; \{ FOO&#8203;: print 1; \}'

RG\-S> EXECUTING\.\.\.

RG\-S> \(\-e&#8203;:0\)  enter
RG\-S> \(\-e&#8203;:0\)  nextstate
RG\-S> \(\-e&#8203;:1\)  goto
RG\-S> \(\-e&#8203;:1\)  nextstate       \<\-\- no enterloop
RG\-S> \(\-e&#8203;:1\)  pushmark
RG\-S> \(\-e&#8203;:1\)  const\(IV\(1\)\)
RG\-S> \(\-e&#8203;:1\)  print
RG\-S> 1
RG\-S> \(\-e&#8203;:1\)  leaveloop
RG\-S> \(\-e&#8203;:1\)  leave

Actually\, the entersub is executed\, but in a weird way \(so you don't
see it with \-Dt\)&#8203;: the PP function is called directly from inside
pp\_goto\(\)\. This is an ugly hack\, but at least most of the time it
works\.

% gdb \./perl
\(gdb\) set args \-e 'goto FOO; \{ FOO&#8203;: print "hi\\n"\} '
\(gdb\) b Perl\_pp\_enterloop 
\(gdb\) run
Starting program&#8203;: /src/perl@&#8203;17967/perl \-e 'goto FOO; \{ FOO&#8203;: print "hi\\n"\} '

Breakpoint 1\, Perl\_pp\_enterloop \(\) at pp\_ctl\.c&#8203;:1724
1724        dSP;
\(gdb\) bt
\#0  Perl\_pp\_enterloop \(\) at pp\_ctl\.c&#8203;:1724
\#1  0x08100b3a in Perl\_pp\_goto \(\) at pp\_ctl\.c&#8203;:2405
\#2  0x080b0f4f in Perl\_runops\_debug \(\) at dump\.c&#8203;:1400
\#3  0x08061ab1 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1686
\#4  0x08061632 in perl\_run \(my\_perl=0x816f568\) at perl\.c&#8203;:1605
\#5  0x0805ddbb in main \(argc=3\, argv=0xbffff9d4\, env=0xbffff9e4\)
&nbsp;    at perlmain\.c&#8203;:85

The loop context mainly gets set up correctly\, which is why something
like this still works&#8203;:

% \./perl \-e 'goto FOO; \{ FOO&#8203;: print "hi\\n"; last; print "bye\\n"\}
hi

RG\-S> $ bleadperl \-le 'goto FOO; BAR&#8203;:\{ FOO&#8203;: print 1; redo BAR\}'
RG\-S> 1
RG\-S> Label not found for "redo BAR" at \-e line 1\.

As this example shows\, the label is set incorrectly\, though\. When the
loop context is pushed\, it gets its label from the current value of
PL\_curcop\, which when it's called from goto is still the one that came
before the call to goto\. Contrast&#8203;:

% \./perl \-e 'goto FOO; other\_code;
&nbsp;                BAR&#8203;: \{ FOO&#8203;: print "hi\\n"; last BAR; print "bye\\n"\}'
hi
Label not found for "last BAR" at \-e line 1\.

% \./perl \-e 'BAR&#8203;: goto FOO; other\_code;
&nbsp;               \{ FOO&#8203;: print "hi\\n"; last BAR; print "bye\\n"\}'
hi

 \-\- Stephen

**Comment by p5pRT** [comment]
### From smcc@mit.edu

>>>>> "SMcC" == Stephen McCamant \<smcc@&#8203;mit\.edu> writes&#8203;:

SMcC> Actually\, the entersub is executed\, but in a weird way \(so you
SMcC> don't see it with \-Dt\)&#8203;: the PP function is called directly from
SMcC> inside pp\_goto\(\)\. This is an ugly hack\, but at least most of the
SMcC> time it works\.
&nbsp;   \.\.\.
SMcC> The loop context mainly gets set up correctly\, which is why
SMcC> something like this still works&#8203;:

SMcC> % \./perl \-e 'goto FOO; \{ FOO&#8203;: print "hi\\n"; last; print "bye\\n"\}
SMcC> hi

RG\-S> $ bleadperl \-le 'goto FOO; BAR&#8203;:\{ FOO&#8203;: print 1; redo BAR\}'
RG\-S> 1
RG\-S> Label not found for "redo BAR" at \-e line 1\.

SMcC> As this example shows\, the label is set incorrectly\,
SMcC> though\. When the loop context is pushed\, it gets its label from
SMcC> the current value of PL\_curcop\, which when it's called from goto
SMcC> is still the one that came before the call to goto\. Contrast&#8203;:

SMcC> % \./perl \-e 'goto FOO; other\_code;
SMcC>                 BAR&#8203;: \{ FOO&#8203;: print "hi\\n"; last BAR; print "bye\\n"\}'
SMcC> hi
SMcC> Label not found for "last BAR" at \-e line 1\.

SMcC> % \./perl \-e 'BAR&#8203;: goto FOO; other\_code;
SMcC>                \{ FOO&#8203;: print "hi\\n"; last BAR; print "bye\\n"\}'
SMcC> hi

I've been looking into this\, and it doesn't appear hard to fix\. As I
allude to above\, pp\_goto has a mechanism to save a stack of OPs the
goto is entering\, and execute them; the only problem is that the
nextstate that labels the loop isn't getting pushed onto that stack
when the search in dofindlabel\(\) encounters it\.

The simplest thing for dofindlabel\(\) to do would be to record every
nextstate it finds in its tree walk\, simulating all the execution down
to the target\, but that would be inefficient and perhaps exhaust the
fixed\-size buffer allocated for the purpose\. An obvious optimization
would be to collapse a sequence of adjacent nextstates in the sequence
down to a single one\, since everything that nexstate does other than
setting PL\_curcop is idempotent\. This is what an older version of this
code \(say from 5\.000\) looks like it is trying to do&#8203;:

if \(kid\->op\_type == OP\_NEXTSTATE || kid\->op\_type == OP\_DBSTATE\) \{
&nbsp;    if \(ops > opstack &&
&nbsp;      \(ops\[\-1\]\->op\_type == OP\_NEXTSTATE ||
&nbsp;       ops\[\-1\]\->op\_type == OP\_DBSTATE\)\)
&nbsp;        \*ops = kid;
&nbsp;    else
&nbsp;        \*ops\+\+ = kid;
\}

I'm guessing that based on the assumption that "\*ops = kid" is
supposed to mean "replace the top element of the stack with kid"\.
Unfortunately\, that's not actually what it does&#8203;: this code uses a
stack discipline where ops points to the first free spot in the stack\,
not the last filled spot\, so "\*ops = kid" won't have any effect\. \(I
think this is a plausible mistake\, though\, since I made it myself
playing around with the code\. In a last\-filled\-style stack\, the
analogous relationship between "\*sp = foo" and "\*\(\+\+sp\) = foo" does
hold\)\.

I'm still a little curious as to why the code was changed to its
current state&#8203;:

if \(\(kid\->op\_type == OP\_NEXTSTATE || kid\->op\_type == OP\_DBSTATE\) &&
&nbsp;    \(ops == opstack ||
&nbsp;     \(ops\[\-1\]\->op\_type \!= OP\_NEXTSTATE &&
&nbsp;      ops\[\-1\]\->op\_type \!= OP\_DBSTATE\)\)\)
&nbsp;    \*ops\+\+ = kid;

which would have the effect of saving the oldest\, rather than the most
recent\, nextstate\.

This is the sort of fix that cries out for adding more test cases\, but
for the moment let me throw out the following patch for people to
ponder\. It passes all the existing tests\, and seems to have the right
behavior&#8203;:

% \./perl \-e 'BAR&#8203;: goto FOO; BAZ&#8203;: \{ print "a\\n"; FOO&#8203;: print "b\\n";
&nbsp;                                   last BAZ; \}'
b

% \./perl \-e 'BAR&#8203;: goto FOO; BAZ&#8203;: \{ print "a\\n"; FOO&#8203;: print "b\\n";
&nbsp;                                   last BAR; \}'
Label not found for "last BAR" at \-e line 1\.

 \-\- Stephen

<details><summary>Inline Patch</summary>

```diff
--- pp_ctl.c.orig	2002-12-22 18:46:55.000000000 -0500
+++ pp_ctl.c	2002-12-22 21:24:35.000000000 -0500
@@ -2048,11 +2048,15 @@ S_dofindlabel(pTHX_ OP *o, char *label, 
 	for (kid = cUNOPo->op_first; kid; kid = kid->op_sibling) {
 	    if (kid == PL_lastgotoprobe)
 		continue;
-	    if ((kid->op_type == OP_NEXTSTATE || kid->op_type == OP_DBSTATE) &&
-		(ops == opstack ||
-		 (ops[-1]->op_type != OP_NEXTSTATE &&
-		  ops[-1]->op_type != OP_DBSTATE)))
-		*ops++ = kid;
+	    if (kid->op_type == OP_NEXTSTATE || kid->op_type == OP_DBSTATE) {
+	        if (ops == opstack)
+		    *ops++ = kid;
+		else if (ops[-1]->op_type == OP_NEXTSTATE ||
+		         ops[-1]->op_type == OP_DBSTATE)
+		    ops[-1] = kid;
+		else
+		    *ops++ = kid;
+	    }
 	    if ((o = dofindlabel(kid, label, ops, oplimit)))
 		return o;
 	}
```
</details>

**Comment by p5pRT** [comment]
### From @hvds

Stephen McCamant \<smcc@&#8203;mit\.edu> wrote&#8203;:
:I'm still a little curious as to why the code was changed to its
:current state&#8203;:
:
:if \(\(kid\->op\_type == OP\_NEXTSTATE || kid\->op\_type == OP\_DBSTATE\) &&
:    \(ops == opstack ||
:     \(ops\[\-1\]\->op\_type \!= OP\_NEXTSTATE &&
:      ops\[\-1\]\->op\_type \!= OP\_DBSTATE\)\)\)
:    \*ops\+\+ = kid;
:
:which would have the effect of saving the oldest\, rather than the most
:recent\, nextstate\.

I'm guessing someone got confused\. It certainly seems like the sort of
logic that could cause that\, particularly given our historical and
egregious lack of commentary\.

:This is the sort of fix that cries out for adding more test cases

There are sorts that don't? :\)

:but for the moment let me throw out the following patch for people to
:ponder\. It passes all the existing tests\, and seems to have the right
:behavior&#8203;:

Thanks\, applied as \#18411\.

Hugo

**Comment by p5pRT** [comment]
### From @jhi

Since a patch was applied that seems to work as expected\,
I'm marking the problem ticket as resolved\.

**Comment by p5pRT** [comment]
@jhi - Status changed from 'new' to 'resolved'

**Comment by p5pRT** [comment]
### From @gsar

On Fri\, 03 Jan 2003 12&#8203;:23&#8203;:51 GMT\, hv@&#8203;crypt\.org wrote&#8203;:
>Stephen McCamant \<smcc@&#8203;mit\.edu> wrote&#8203;:
>&#8203;:I'm still a little curious as to why the code was changed to its
>&#8203;:current state&#8203;:
>&#8203;:
>&#8203;:if \(\(kid\->op\_type == OP\_NEXTSTATE || kid\->op\_type == OP\_DBSTATE\) &&
>&#8203;:    \(ops == opstack ||
>&#8203;:     \(ops\[\-1\]\->op\_type \!= OP\_NEXTSTATE &&
>&#8203;:      ops\[\-1\]\->op\_type \!= OP\_DBSTATE\)\)\)
>&#8203;:    \*ops\+\+ = kid;
>&#8203;:
>&#8203;:which would have the effect of saving the oldest\, rather than the most
>&#8203;:recent\, nextstate\.
>
>I'm guessing someone got confused\. It certainly seems like the sort of
>logic that could cause that\, particularly given our historical and
>egregious lack of commentary\.

FWIW\, the above change seems to have come in at 5\.003\_97i&#8203;:

&nbsp;  Title&#8203;:  "Guard against C\<goto> to deeply nested label"
&nbsp;   From&#8203;:  Chip Salzenberg
&nbsp;  Files&#8203;:  pod/perldiag\.pod pp\_ctl\.c

The nearest thread of discussion about goto is this one&#8203;:

&nbsp;  http&#8203;://www\.xray\.mpe\.mpg\.de/mailing\-lists/perl5\-porters/1997\-04/msg01061\.html

but I can't find the exact bug it was meant to fix\.  Perhaps it was
just "random cleanup"?  The relevant extract of the patch to pp\_ctl\.c
is&#8203;:

:Index&#8203;: pp\_ctl\.c
:\*\*\* perl5\.003\_97/pp\_ctl\.c       Tue Apr  1 13&#8203;:32&#8203;:10 1997
:\-\-\- perl5\.003\_98/pp\_ctl\.c       Thu Apr 24 21&#8203;:55&#8203;:09 1997
:\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*
:\*\*\* 27\,33 \*\*\*\*
:
:  static OP \*docatch \_\(\(OP \*o\)\);
:  static OP \*doeval \_\(\(int gimme\)\);
:\! static OP \*dofindlabel \_\(\(OP \*op\, char \*label\, OP \*\*opstack\)\);
:  static void doparseform \_\(\(SV \*sv\)\);
:  static I32 dopoptoeval \_\(\(I32 startingblock\)\);
:  static I32 dopoptolabel \_\(\(char \*label\)\);
:\-\-\- 27\,33 \-\-\-\-
:
:  static OP \*docatch \_\(\(OP \*o\)\);
:  static OP \*doeval \_\(\(int gimme\)\);
:\! static OP \*dofindlabel \_\(\(OP \*op\, char \*label\, OP \*\*opstack\, OP \*\*oplimit\)\);
:  static void doparseform \_\(\(SV \*sv\)\);
:  static I32 dopoptoeval \_\(\(I32 startingblock\)\);
:  static I32 dopoptolabel \_\(\(char \*label\)\);
:\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*
:\*\*\* 1549\,1567 \*\*\*\*
:  static OP\* lastgotoprobe;
:
:  static OP \*
:\! dofindlabel\(op\,label\,opstack\)
:  OP \*op;
:  char \*label;
:  OP \*\*opstack;
:  \{
:      OP \*kid;
:      OP \*\*ops = opstack;
:
:      if \(op\->op\_type == OP\_LEAVE ||
:        op\->op\_type == OP\_SCOPE ||
:        op\->op\_type == OP\_LEAVELOOP ||
:        op\->op\_type == OP\_LEAVETRY\)
:\!           \*ops\+\+ = cUNOP\->op\_first;
:      \*ops = 0;
:      if \(op\->op\_flags & OPf\_KIDS\) \{
:        /\* First try all the kids at this level\, since that's likeliest\. \*/
:\-\-\- 1545\,1571 \-\-\-\-
:  static OP\* lastgotoprobe;
:
:  static OP \*
:\! dofindlabel\(op\,label\,opstack\,oplimit\)
:  OP \*op;
:  char \*label;
:  OP \*\*opstack;
:\+ OP \*\*oplimit;
:  \{
:      OP \*kid;
:      OP \*\*ops = opstack;
:\+     static char too\_deep\[\] = "Target of goto is too deeply nested";
:
:\+     if \(ops >= oplimit\)
:\+       croak\(too\_deep\);
:      if \(op\->op\_type == OP\_LEAVE ||
:        op\->op\_type == OP\_SCOPE ||
:        op\->op\_type == OP\_LEAVELOOP ||
:        op\->op\_type == OP\_LEAVETRY\)
:\!     \{
:\!       \*ops\+\+ = cUNOP\->op\_first;
:\!       if \(ops >= oplimit\)
:\!           croak\(too\_deep\);
:\!     \}
:      \*ops = 0;
:      if \(op\->op\_flags & OPf\_KIDS\) \{
:        /\* First try all the kids at this level\, since that's likeliest\. \*/
:\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*
:\*\*\* 1573\,1587 \*\*\*\*
:        for \(kid = cUNOP\->op\_first; kid; kid = kid\->op\_sibling\) \{
:            if \(kid == lastgotoprobe\)
:                continue;
:\!           if \(kid\->op\_type == OP\_NEXTSTATE || kid\->op\_type == OP\_DBSTATE\) \{
:\!               if \(ops > opstack &&
:\!                 \(ops\[\-1\]\->op\_type == OP\_NEXTSTATE ||
:\!                  ops\[\-1\]\->op\_type == OP\_DBSTATE\)\)
:\!                   \*ops = kid;
:\!               else
:\!                   \*ops\+\+ = kid;
:\!           \}
:\!           if \(op = dofindlabel\(kid\,label\,ops\)\)
:                return op;
:        \}
:      \}
:\-\-\- 1577\,1588 \-\-\-\-
:        for \(kid = cUNOP\->op\_first; kid; kid = kid\->op\_sibling\) \{
:            if \(kid == lastgotoprobe\)
:                continue;
:\!           if \(\(kid\->op\_type == OP\_NEXTSTATE || kid\->op\_type == OP\_DBSTATE\) &&
:\!               \(ops == opstack ||
:\!                \(ops\[\-1\]\->op\_type \!= OP\_NEXTSTATE &&
:\!                 ops\[\-1\]\->op\_type \!= OP\_DBSTATE\)\)\)
:\!               \*ops\+\+ = kid;
:\!           if \(op = dofindlabel\(kid\, label\, ops\, oplimit\)\)
:                return op;
:        \}
:      \}
:\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*
:\*\*\* 1817\,1823 \*\*\*\*
:                gotoprobe = main\_root;
:                break;
:            \}
:\!           retop = dofindlabel\(gotoprobe\, label\, enterops\);
:            if \(retop\)
:                break;
:            lastgotoprobe = gotoprobe;
:\-\-\- 1819\,1826 \-\-\-\-
:                gotoprobe = main\_root;
:                break;
:            \}
:\!           retop = dofindlabel\(gotoprobe\, label\,
:\!                               enterops\, enterops \+ GOTO\_DEPTH\);
:            if \(retop\)
:                break;
:            lastgotoprobe = gotoprobe;



Sarathy
gsar@&#8203;ActiveState\.com

**Comment by p5pRT** [comment]
### From @rgs

Change \#18703\, aimed at fixing bugs \#20154 and \#20357\, fixes also this one\.

**Comment by p5pRT** [comment]
@rgs - Status changed from 'open' to 'resolved'
