### ISSUE TITLE
PerlIO flush issue

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6207]
Migrated from [rt.perl.org#19863](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=19863) (status was 'resolved')

Searchable as RT19863$

**Comment by p5pRT** [comment]
### From acme@parrot.fotango.com

#### Created by acme@astray.com



I have a segfault bug under Perl 5\.8\.0 / mod\_perl 1\.27 \(Apache 1\.3\.27\) which
unfortunately isn't entirely reproducable and I can't knock the test case down to
less than tens of thousands of lines of code\. I've also failed to get mod\_perl to
give debugging symbols\, so unfortunately the best I can offer at the moment is a 
simple stack trace\. Perhaps this will job someone's memory while I try and get
more information about the issue\.

\#0  0x400f01ee in fflush \(\) from /lib/libc\.so\.6
\#1  0x081b37ca in PerlIOStdio\_flush \(\)
\#2  0x081b183a in Perl\_PerlIO\_flush \(\)
\#3  0x081b1904 in Perl\_PerlIO\_flush \(\)
\#4  0x0818c40c in Perl\_pp\_system \(\)
\#5  0x0812a9bd in Perl\_runops\_debug \(\)
\#6  0x080dc86d in Perl\_call\_sv \(\)
\#7  0x080dc4d3 in Perl\_call\_sv \(\)
\#8  0x080818be in perl\_call\_handler \(\)
\#9  0x08080f41 in perl\_run\_stacked\_handlers \(\)
\#10 0x0807f0d4 in perl\_handler \(\)
\#11 0x080ac749 in ap\_invoke\_handler \(\)
\#12 0x080c250f in ap\_some\_auth\_required \(\)
\#13 0x080c257a in ap\_process\_request \(\)
\#14 0x080b8e06 in ap\_child\_terminate \(\)
\#15 0x080b908a in ap\_child\_terminate \(\)
\#16 0x080b9146 in ap\_child\_terminate \(\)
\#17 0x080b97dd in ap\_child\_terminate \(\)
\#18 0x080ba04c in main \(\)
\#19 0x400a5671 in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6

Cheers\, Leon

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.8.0:

Configured by acme at Wed Jan  8 16:07:48 GMT 2003.

Summary of my perl5 (revision 5.0 version 8 subversion 0) configuration:
  Platform:
    osname=linux, osvers=2.4.19-gentoo-r7, archname=i686-linux
    uname='linux parrot.fotango.com 2.4.19-gentoo-r7 #1 tue jun 25 15:20:52 bst 2002 i686 pentium iii (coppermine) genuineintel gnulinux '
    config_args='-ds -e -Dprefix=/home/acme -Doptimize=-g'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-DDEBUGGING -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-g',
    cppflags='-DDEBUGGING -fno-strict-aliasing'
    ccversion='', gccversion='2.95.3 20010315 (release)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lndbm -lgdbm -ldb -ldl -lm -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lcrypt -lutil
    libc=/lib/libc-2.2.5.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.2.5'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.0:
    /home/acme/lib/perl5/5.8.0/i686-linux
    /home/acme/lib/perl5/5.8.0
    /home/acme/lib/perl5/site_perl/5.8.0/i686-linux
    /home/acme/lib/perl5/site_perl/5.8.0
    /home/acme/lib/perl5/site_perl
    .


Environment for perl v5.8.0:
    HOME=/home/acme
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/acme/bin:/bin:/usr/bin:/usr/local/bin:/opt/bin:/usr/X11R6/bin:/opt/sun-jdk-1.4.0/bin:/opt/sun-jdk-1.4.0/jre/bin:/usr/qt/3/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
arthur@contiller.se - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From arthur@contiller.se

This is full debugging stack trace\.


\#0  \_\_pthread\_mutex\_lock \(mutex=0x6120794d\) at mutex\.c&#8203;:82
\#1  0x40460c2b in \_\_flockfile \(stream=0xa352ef8\) at lockfile\.c&#8203;:32
\#2  0x40281630 in \_IO\_fflush \(fp=0xa352ef8\) at iofflush\.c&#8203;:40
\#3  0x81be543 in PerlIOStdio\_flush \(f=0x822906c\) at perlio\.c&#8203;:2812
\#4  0x81bc727 in Perl\_PerlIO\_flush \(f=0x822906c\) at perlio\.c&#8203;:1507
\#5  0x81bc7e1 in Perl\_PerlIO\_flush \(f=0x822906c\) at perlio\.c&#8203;:1535
\#6  0x81303d2 in Perl\_my\_popen \(cmd=0xa937488 "\-"\, mode=0xbffff460 "r"\) at 
util\.c&#8203;:2084
\#7  0x819ac1d in Perl\_do\_openn \(gv=0xa4f5478\, name=0xa937488 "\-"\, len=1\, 
as\_raw=0\, rawmode=0\, rawperm=0\, supplied\_fp=0x0\,
&nbsp;    svp=0x96abbd8\, num\_svs=0\) at doio\.c&#8203;:490
\#8  0x8185f4f in Perl\_pp\_open \(\) at pp\_sys\.c&#8203;:542
\#9  0x812bde4 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1398
\#10 0x80de7df in S\_call\_body \(myop=0xbffff620\, is\_eval=0\) at perl\.c&#8203;:2045
\#11 0x80de42f in Perl\_call\_sv \(sv=0x980e698\, flags=4\) at perl\.c&#8203;:1963
\#12 0x8083d3c in perl\_call\_handler \(sv=0x980e698\, r=0xa33bbec\, args=0x0\) at 
mod\_perl\.c&#8203;:1658
\#13 0x8083238 in perl\_run\_stacked\_handlers \(hook=0x81d7099 "PerlHandler"\, 
r=0xa33bbec\, handlers=0x82a4670\) at mod\_perl\.c&#8203;:1371
\#14 0x80808c8 in perl\_handler \(r=0xa33bbec\) at mod\_perl\.c&#8203;:897
\#15 0x80afa93 in ap\_invoke\_handler \(r=0xa33bbec\) at http\_config\.c&#8203;:518
\#16 0x80c47e9 in process\_request\_internal \(r=0xa33bbec\) at http\_request\.c&#8203;:1308
\#17 0x80c484c in ap\_process\_request \(r=0xa33bbec\) at http\_request\.c&#8203;:1324
\#18 0x80bb84e in child\_main \(child\_num\_arg=0\) at http\_main\.c&#8203;:4603
\#19 0x80bba8c in make\_child \(s=0x82182cc\, slot=0\, now=1052215224\) at 
http\_main\.c&#8203;:4773
\-\-\-Type \<return> to continue\, or q \<return> to quit\-\-\-
\#20 0x80bbb39 in startup\_children \(number\_to\_start=2\) at http\_main\.c&#8203;:4800
\#21 0x80bc196 in standalone\_main \(argc=3\, argv=0xbffff874\) at http\_main\.c&#8203;:5108
\#22 0x80bc963 in main \(argc=3\, argv=0xbffff874\) at http\_main\.c&#8203;:5456

**Comment by p5pRT** [comment]
### From arthur@contiller.se

This bug is essentially a dupe of http&#8203;://mathforum\.org/epigone/modperl/
zhoolamgheld/m3lm9ml44m\.fsf@&#8203;k242\.linux\.bogus which was reported by Andreas 
König Tue\, 11 Jun 2002 and caused quite a lot of headache before the culprit was 
found\.

The solution to the bug is to upgrade to libapreq 1\.1 / Apache&#8203;::Request 1\.1 since 1\.0 is 
the offending module\. Sadly 1\.1 was not released until february 2003 even if the patch 
was from the summer 2002\. 1\.1 incorprates the patch slightly differently and even more 
robust\. The other solution is to make sure you don't have upload filehandles around 
when you do a system\(\) call \(or anything that flushes all filehandles\)\.

What happens essentially is that Apache&#8203;::Request gets a filehandle for the upload and 
tells perl about it\, however it forgot to tell Perl it was a readonly filehandle\. So when perl 
does a backtik or system operation it tries to flush all filehandles\, this include trying to 
flush the readonly filehandle it thought was writeable\. This lead to a segfault depending 
on what data was in there\.

Apache&#8203;::Request 1\.1 fixes this by importing the filehandle as readonly\.

Arthur

**Comment by p5pRT** [comment]
arthur@contiller.se - Status changed from 'open' to 'resolved'
