### ISSUE TITLE
anonymous sub/eval/magic(?) segfault

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6244]
Migrated from [rt.perl.org#20508](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=20508) (status was 'resolved')

Searchable as RT20508$

**Comment by p5pRT** [comment]
### From shellreef@yahoo.com



Crashes perl5\.8\.0&#8203;:
\-\-shell session\-\-
> cat crash
my \($quux\, $foo\);      \# or&#8203;: our\($quux\, $foo\)

sub
\{
&nbsp;    my $coderef = eval 'sub \{ $quux \}';   \# Segfaults
here
&nbsp;    $foo\->\(\) if 0      \# or&#8203;: goto &\{$foo\}
\}\->\(\)


> perl \-D crash
Recompile perl with \-DDEBUGGING to use \-D switch
perl in free\(\)&#8203;: warning&#8203;: junk pointer\, too high to
make sense
Bus error \(core dumped\)
>
\-\-end shell session\-\-
Tested on&#8203;:
Perl 5\.8\.0 FreeBSD 5\.0\-RELEASE crash
Perl 5\.8\.0 FreeBSD 4\.7\-STABLE  crash
Perl 5\.8\.0 Windows XP Pro      no crash
Perl 5\.6\.0 FreeBSD 4\.7\-STABLE  no crash
Perl 5\.6\.0 FreeBSD 5\.0\-RELEASE no crash

Looks to me that an SV is created such that SvANY\(sv\)
returns NULL\, which
is then dereferenced in sv\.c&#8203;:3860&#8203;:
&nbsp;   if \(SvPVX\(dstr\)\) \{       /\* SvPVX\->pv\_any\->\, but
pv\_any is 0 \*/
This code is called from pp\_hot\.c&#8203;:108
"SvSetMagicSV\(right\, left\)" so I suspect
it has to do with magic\, but I am by no means a Perl
guts expert\.
The segmentation fault or bus error \(depending on
various conditions\) occurs
when "my $coderef = eval 'sub \{ $quux \}'" is executed\,
but in my testings
a call or goto $foo must come after\, although this
code is only compiled but
never executed \(as proven by the "if 0" modifier\)\.

Stack backtrace&#8203;:
Program received signal SIGSEGV\, Segmentation fault\.
0x80a7622 in Perl\_sv\_setsv\_flags \(dstr=0x8120078\,
sstr=0x8126460\, flags=2\)
&nbsp;    at sv\.c&#8203;:3860
3860                if \(SvPVX\(dstr\)\) \{
\(gdb\) bt
\#0  0x80a7622 in Perl\_sv\_setsv\_flags \(dstr=0x8120078\,
sstr=0x8126460\, flags=2\)
&nbsp;    at sv\.c&#8203;:3860
\#1  0x809cd12 in Perl\_pp\_sassign \(\) at pp\_hot\.c&#8203;:108
\#2  0x809c9d8 in Perl\_runops\_standard \(\) at run\.c&#8203;:25
\#3  0x805e468 in S\_run\_body \(oldscope=1\) at
perl\.c&#8203;:1681
\#4  0x805e1a0 in perl\_run \(my\_perl=0x8115030\) at
perl\.c&#8203;:1600
\#5  0x805b9be in main \(argc=2\, argv=0xbfbff748\,
env=0xbfbff754\)
&nbsp;    at perlmain\.c&#8203;:85
\#6  0x805b8a5 in \_start \(\)


Hope this helps\,
Jeff Connelly

<details><summary>Perl Info</summary>

```


This perlbug was built using Perl 5.00503 - Sun Mar  5
13:39:27 SAST 2000
It is being executed now by  Perl 5.008 - Mon Jan 20
15:49:10 PST 2003.

Site configuration information for perl 5.008:

Configured by jeff at Mon Jan 20 15:49:10 PST 2003.

Summary of my perl5 (revision 5.0 version 8 subversion
0) configuration:
  Platform:
    osname=freebsd, osvers=4.7-stable,
archname=i386-freebsd
    uname='freebsd dragon.jeff.tk 4.7-stable freebsd
4.7-stable #1: sun nov 24 15:14:26 pst 2002
root@dragon.jeff.tk:usrobjusrsrcsysdragon i386 '
    config_args=''    hint=previous, useposix=true,
d_sigaction=define
    usethreads=undef use5005threads=undef
useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define
usesocks=undef
    use64bitint=undef use64bitall=undef
uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags
='-DAPPLLIB_EXP="/usr/local/lib/perl5/5.8.0/BSDPAN"
-DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H
-fno-strict-aliasing -I/usr/local/include',
    optimize='-O -pipe -march=pentiumpro -g',
   
cppflags='-DAPPLLIB_EXP="/usr/local/lib/perl5/5.8.0/BSDPAN"
-DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H
-fno-strict-aliasing -I/usr/local/include
-DAPPLLIB_EXP="/usr/local/lib/perl5/5.8.0/BSDPAN"
-DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H
-fno-strict-aliasing -I/usr/local/include -DDEBUGGING
-DAPPLLIB_EXP="/usr/local/lib/perl5/5.8.0/BSDPAN"
-DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H
-fno-strict-aliasing -I/usr/local/include -DDEBUGGING
-DAPPLLIB_EXP="/usr/local/lib/perl5/5.8.0/BSDPAN"
-DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H
-fno-strict-aliasing -I/usr/local/include
-DAPPLLIB_EXP="/usr/local/lib/perl5/5.8.0/BSDPAN"
-DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H
-fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='2.95.3 20010315
(release) [FreeBSD]', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8,
byteorder=1234
    d_longlong=define, longlongsize=8,
d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double',
nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags ='-Wl,-E  -L/usr/local/lib'
    libpth=/usr/lib /usr/local/lib
    libs=-lgdbm -lm -lc -lcrypt -lutil
    perllibs=-lm -lc -lcrypt -lutil
    libc=, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef,
ccdlflags=' '
    cccdlflags='-DPIC -fPIC', lddlflags='-shared 
-L/usr/local/lib'

Locally applied patches:



@INC for perl 5.008:
    /usr/local/lib/perl5/site_perl/5.8.0/mach
    /usr/local/lib/perl5/site_perl/5.8.0
    /usr/local/lib/perl5/site_perl/5.6.1
    /usr/local/lib/perl5/site_perl/5.005
    /usr/local/lib/perl5/site_perl
    /usr/local/lib/perl5/5.8.0/BSDPAN
    /usr/local/lib/perl5/5.8.0/mach
    /usr/local/lib/perl5/5.8.0
    .


Environment for perl 5.008:
    HOME=/home/jeff
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
   
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/usr/X11R6/bin:/home/jeff/bin
    PERL_BADLANG (unset)
    SHELL=/bin/tcsh
~







__________________________________________________
Do you Yahoo!?
Yahoo! Mail Plus - Powerful. Affordable. Sign up now.
http://mailplus.yahoo.com

```
</details>

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Jan 23\, 2003 at 05&#8203;:09&#8203;:56AM \-0000\, Jeff Connelly wrote&#8203;:
> Crashes perl5\.8\.0&#8203;:
> \-\-shell session\-\-
> > cat crash
> my \($quux\, $foo\);      \# or&#8203;: our\($quux\, $foo\)
> 
> sub
> \{
>     my $coderef = eval 'sub \{ $quux \}';   \# Segfaults
> here
>     $foo\->\(\) if 0      \# or&#8203;: goto &\{$foo\}
> \}\->\(\)

Thanks for the report\. This has been fixed in the current development
version of Perl \(patch \#18048\)\.

\-\- 
"I do not resent critisism\, even when\, for the sake of emphasis\,
it parts for the time with reality"\.
Winston Churchill\, House of Commons\, 22nd Jan 1941\.

**Comment by p5pRT** [comment]
### From @iabyn

closed already\-resolved bug report\.

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'new' to 'resolved'
