### ISSUE TITLE
Segfault in a "for" over uninitialized array, embedded inside a "map"

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6254]
Migrated from [rt.perl.org#20559](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=20559) (status was 'resolved')

Searchable as RT20559$

**Comment by p5pRT** [comment]
### From jsnell@iki.fi

#### Created by jsnell@iki.fi



The following \(minimal?\) test program results in a segfault\.

\#\!perl
map\{1 for @&#8203;n\}0
\_\_END\_\_

Stacktrace&#8203;:

\#0  0x400a30b2 in Perl\_sv\_tainted \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/CORE/libperl\.so
\#1  0x4009bbd0 in Perl\_sv\_setsv\_flags \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/CORE/libperl\.so
\#2  0x400a10b6 in Perl\_sv\_mortalcopy \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/CORE/libperl\.so
\#3  0x400bd622 in Perl\_pp\_mapwhile \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/CORE/libperl\.so
\#4  0x4008e059 in Perl\_runops\_standard \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/CORE/libperl\.so
\#5  0x400355bb in S\_run\_body \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/CORE/libperl\.so
\#6  0x40035355 in perl\_run \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/CORE/libperl\.so
\#7  0x08049173 in main \(\)
\#8  0x420158d4 in \_\_libc\_start\_main \(\) from /lib/i686/libc\.so\.6

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.8.0:

Configured by bhcompile at Sun Sep  1 23:55:07 EDT 2002.

Summary of my perl5 (revision 5.0 version 8 subversion 0) configuration:
  Platform:
    osname=linux, osvers=2.4.18-11smp, archname=i386-linux-thread-multi
    uname='linux daffy.perf.redhat.com 2.4.18-11smp #1 smp thu aug 15 06:41:59 edt 2002 i686 i686 i386 gnulinux '
    config_args='-des -Doptimize=-O2 -march=i386 -mcpu=i686 -Dmyhostname=localhost -Dperladmin=root@localhost -Dcc=gcc -Dcf_by=Red Hat, Inc. -Dinstallprefix=/usr -Dprefix=/usr -Darchname=i386-linux -Dvendorprefix=/usr -Dsiteprefix=/usr -Duseshrplib -Dusethreads -Duseithreads -Duselargefiles -Dd_dosuid -Dd_semctl_semun -Di_db -Ui_ndbm -Di_gdbm -Di_shadow -Di_syslog -Dman3ext=3pm -Duseperlio -Dinstallusrbinperl -Ubincompat5005 -Uversiononly -Dpager=/usr/bin/less -isr'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm',
    optimize='-O2 -march=i386 -mcpu=i686',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -I/usr/include/gdbm'
    ccversion='', gccversion='3.2 20020822 (Red Hat Linux Rawhide 3.2-5)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lgdbm -ldb -ldl -lm -lpthread -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lpthread -lc -lcrypt -lutil
    libc=/lib/libc-2.2.92.so, so=so, useshrplib=true, libperl=libperl.so
    gnulibc_version='2.2.92'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic -Wl,-rpath,/usr/lib/perl5/5.8.0/i386-linux-thread-multi/CORE'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.0:
    /usr/lib/perl5/5.8.0/i386-linux-thread-multi
    /usr/lib/perl5/5.8.0
    /usr/lib/perl5/site_perl/5.8.0/i386-linux-thread-multi
    /usr/lib/perl5/site_perl/5.8.0
    /usr/lib/perl5/site_perl/5.6.1
    /usr/lib/perl5/site_perl
    /usr/lib/perl5/vendor_perl/5.8.0/i386-linux-thread-multi
    /usr/lib/perl5/vendor_perl/5.8.0
    /usr/lib/perl5/vendor_perl/5.6.1
    /usr/lib/perl5/vendor_perl
    .


Environment for perl v5.8.0:
    HOME=/home/jsnell
    LANG=en_US
    LANGUAGE (unset)
    LC_CTYPE=fi_FI
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/jsnell/bin/common:/home/jsnell/bin/linux:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/X11R6/bin
    PERL_BADLANG (unset)
    SHELL=/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @rgs

"jsnell@&#8203;iki\.fi \(via RT\)" \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> The following \(minimal?\) test program results in a segfault\.
> 
> \#\!perl
> map\{1 for @&#8203;n\}0
> \_\_END\_\_

Thanks for your report\. This bug has been corrected in the current
development version of perl \(by change \#17998 probably\)\.

**Comment by p5pRT** [comment]
@rgs - Status changed from 'new' to 'resolved'
