### ISSUE TITLE
perl segfaults on $SIG{RTMIN} = "DEFAULT"

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6287]
Migrated from [rt.perl.org#20773](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=20773) (status was 'resolved')

Searchable as RT20773$

**Comment by p5pRT** [comment]
### From root@.nonet

#### Created by root@(none).nonet



Summary&#8203;: perl \-e '$SIG\{RTMIN\} = "DEFAULT"' segfaults\.
System summary&#8203;: gcc\-3\.2\, glibc\-2\.3\.1\, perl\-5\.8\.0

Details follow\.

root@&#8203;p405u ~$ perl \-e '$SIG\{RTMIN\} = "DEFAULT"'
Segmentation fault
root@&#8203;p405u ~$ gdb perl
GNU gdb 5\.3
Copyright 2002 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and you are
welcome to change it and/or distribute copies of it under certain
conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for details\.
This GDB was configured as "i686\-pc\-linux\-gnu"\.\.\.
\(no debugging symbols found\)\.\.\.
\(gdb\) run \-e '$SIG\{RTMIN\} = "DEFAULT"'
Starting program&#8203;: /usr/bin/perl \-e '$SIG\{RTMIN\} = "DEFAULT"'
\(no debugging symbols found\)\.\.\.\(no debugging symbols found\)\.\.\.
\(no debugging symbols found\)\.\.\.\(no debugging symbols found\)\.\.\.
\(no debugging symbols found\)\.\.\.\(no debugging symbols found\)\.\.\.
\(no debugging symbols found\)\.\.\.
Program received signal SIGSEGV\, Segmentation fault\.
0x080bb5a4 in Perl\_sv\_free \(\)
\(gdb\) bt
\#0  0x080bb5a4 in Perl\_sv\_free \(\)
\#1  0x080a4413 in Perl\_magic\_setsig \(\)
\#2  0x080a6b82 in Perl\_mg\_set \(\)
\#3  0x080ae11b in Perl\_pp\_sassign \(\)
\#4  0x080ae058 in Perl\_runops\_standard \(\)
\#5  0x0805f2d4 in perl\_run \(\)
\#6  0x0805f0ce in perl\_run \(\)
\#7  0x0805c7c3 in main \(\)
\#8  0x4006d9c4 in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6
\(gdb\) The program is running\.  Exit anyway? \(y or n\) y
root@&#8203;p405u ~$ uname \-a
Linux p405u\.localdomain 2\.4\.19\-gentoo\-r10 \#2 Mon Jan 20 17&#8203;:50&#8203;:15 GMT 2003
i686 Pentium III \(Coppermine\) GenuineIntel GNU/Linux
root@&#8203;p405u ~$ gcc \-\-version
gcc \(GCC\) 3\.2\.1 20021207 \(Gentoo Linux 3\.2\.1\-20021207\)
Copyright \(C\) 2002 Free Software Foundation\, Inc\.
This is free software; see the source for copying conditions\.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\.

root@&#8203;p405u ~$ ls \-l /lib/libc\-\*
\-rwxr\-xr\-x    1 root     root      1450109 Jan 20 01&#8203;:10 /lib/libc\-2\.3\.1\.so\*

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=critical

Site configuration information for perl v5.8.0:

Configured by root at Mon Jan 20 04:26:43 Local time zone must be set--see zic manual page 2003.

Summary of my perl5 (revision 5.0 version 8 subversion 0) configuration:
  Platform:
    osname=linux, osvers=2.4.19-gentoo-r7, archname=i686-linux
    uname='linux (none) 2.4.19-gentoo-r7 #4 wed jun 5 07:09:05 local time zone must be set--see zic manuali686 i686 pentium iii (coppermine) genuineintel gnulinux '
    config_args='-des -Darchname=i686-linux -Dcc=gcc -Dprefix=/usr -Dvendorprefix=/usr -Dsiteprefix=/usr -Dlocincpth=  -Doptimize=-mcpu=pentium3 -march=pentium3 -O3 -pipe -Duselargefiles -Dd_dosuid -Dd_semctl_semun -Dscriptdir=/usr/bin -Dman3ext=3pm -Dcf_by=Gentoo -Ud_csh -Di_gdbm -Di_db -Di_ndbm'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-DPERL5 -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-mcpu=pentium3 -march=pentium3 -O3 -pipe',
    cppflags='-DPERL5 -DPERL5 -fno-strict-aliasing'
    ccversion='', gccversion='3.2.1 20021207 (Gentoo Linux 3.2.1-20021207)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lndbm -lgdbm -ldb -ldl -lm -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lcrypt -lutil
    libc=/lib/libc-2.3.1.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.3.1'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.0:
    /usr/lib/perl5/5.8.0/i686-linux
    /usr/lib/perl5/5.8.0
    /usr/lib/perl5/site_perl/5.8.0/i686-linux
    /usr/lib/perl5/site_perl/5.8.0
    /usr/lib/perl5/site_perl
    /usr/lib/perl5/vendor_perl/5.8.0/i686-linux
    /usr/lib/perl5/vendor_perl/5.8.0
    /usr/lib/perl5/vendor_perl
    .


Environment for perl v5.8.0:
    HOME=/root
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/opt/bin:/usr/heimdal/sbin:/usr/athena/sbin:/usr/i686-pc-linux-gnu/gcc-bin/3.2:/usr/X11R6/bin:/opt/blackdown-jdk-1.3.1/bin:/opt/blackdown-jdk-1.3.1/jre/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @smpeters

> \[root@&#8203;\.nonet \- Thu Feb 06 16&#8203;:57&#8203;:26 2003\]&#8203;:
> 
> 
> This is a bug report for perl from root@&#8203;\(none\)\.nonet\,
> generated with the help of perlbug 1\.34 running under perl v5\.8\.0\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> 
> Summary&#8203;: perl \-e '$SIG\{RTMIN\} = "DEFAULT"' segfaults\.
> System summary&#8203;: gcc\-3\.2\, glibc\-2\.3\.1\, perl\-5\.8\.0
> 

I just gave it a try with Perl 5\.8\.5 and I did not get a segfault\.  Is
this still a problem?

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'resolved'
