### ISSUE TITLE
Broken Pipe dumps core

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6397]
Migrated from [rt.perl.org#21713](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=21713) (status was 'resolved')

Searchable as RT21713$

**Comment by p5pRT** [comment]
### From dan@verliba.cz


This is a bug report for perl from dan@&#8203;verliba\.cz\,
generated with the help of perlbug 1\.34 running under perl v5\.8\.0\.



---
My script is a network client\. After more that an hour of no problems\, it
carshes on broken pipe\, and a core is dumped\. I tried to examine the core
against the script\, byt I don't know how to do it\. I found in one forum\, that a
core file should never be dumped\, so it's a bug of perl\. Here am I submitting it
:o\)



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=medium


---
Site configuration information for perl v5\.8\.0&#8203;:

Configured by pixel at Fri Sep  6 23&#8203;:23&#8203;:23 CEST 2002\.

Summary of my perl5 \(revision 5\.0 version 8 subversion 0\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.4\.19\-2mdkenterprise\, archname=i386\-linux\-thread\-multi
&nbsp;    uname='linux no\.mandrakesoft\.com 2\.4\.19\-2mdkenterprise \#1 smp tue aug 13 00&#8203;:17&#8203;:42 cest 2002 i686 unknown unknown gnulinux '
&nbsp;    config\_args='\-des \-Darchname=i386\-linux \-Dcc=gcc \-Doptimize=\-O3 \-fomit\-frame\-pointer \-pipe \-mcpu=pentiumpro \-march=i586 \-ffast\-math \-fno\-strength\-reduce \-Dprefix=/usr \-Dvendorprefix=/usr \-Dsiteprefix=/usr \-Dman3ext=3pm \-Dcf\_by=MandrakeSoft \-Dmyhostname=localhost \-Dperladmin=root@&#8203;localhost \-Dd\_dosuid \-Ud\_csh \-Duseshrplib \-Dusethreads'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-I/usr/include/gdbm'\,
&nbsp;    optimize='\-O3 \-fomit\-frame\-pointer \-pipe \-mcpu=pentiumpro \-march=i586 \-ffast\-math \-fno\-strength\-reduce'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-I/usr/include/gdbm'
&nbsp;    ccversion=''\, gccversion='3\.2 \(Mandrake Linux 9\.0 3\.2\-1mdk\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='gcc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-lndbm \-lgdbm \-ldl \-lm \-lpthread \-lc \-lcrypt \-lutil
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lpthread \-lc \-lcrypt \-lutil
&nbsp;    libc=/lib/libc\-2\.2\.5\.so\, so=so\, useshrplib=true\, libperl=libperl\.so
&nbsp;    gnulibc\_version='2\.2\.5'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic \-Wl\,\-rpath\,/usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/CORE'
&nbsp;    cccdlflags='\-fpic'\, lddlflags='\-shared \-L/usr/local/lib'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl v5\.8\.0&#8203;:
&nbsp;    /usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/5\.8\.0
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.0/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.0
&nbsp;    /usr/lib/perl5/site\_perl
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.0/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.0
&nbsp;    /usr/lib/perl5/vendor\_perl
&nbsp;    \.



---
Environment for perl v5\.8\.0&#8203;:
&nbsp;    HOME=/home/dan
&nbsp;    LANG=en\_US
&nbsp;    LANGUAGE=en\_US&#8203;:en
&nbsp;    LC\_COLLATE=en\_US
&nbsp;    LC\_CTYPE=en\_US
&nbsp;    LC\_MESSAGES=en\_US
&nbsp;    LC\_MONETARY=en\_US
&nbsp;    LC\_NUMERIC=en\_US
&nbsp;    LC\_TIME=en\_US
&nbsp;    LD\_LIBRARY\_PATH=/usr/X11R6/lib
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/usr/local/bin&#8203;:/bin&#8203;:/usr/bin&#8203;:/usr/X11R6/bin&#8203;:/usr/games&#8203;:/home/dan/bin&#8203;:\.&#8203;:/home/dan
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @nwc10

On Thu\, Mar 27\, 2003 at 10&#8203;:03&#8203;:07AM \-0000\, dan@&#8203;verliba\.cz \(via RT\) wrote&#8203;:

> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> My script is a network client\. After more that an hour of no problems\, it
> carshes on broken pipe\, and a core is dumped\. I tried to examine the core
> against the script\, byt I don't know how to do it\. I found in one forum\, that a
> core file should never be dumped\, so it's a bug of perl\. Here am I submitting it
> :o\)

Indeed\, perl should not core dump\. \(Although there are a few ways to make it
core dump that we can't currently stop\) and sometimes it actually a third\-party
extension linked in that is core dumping\, not the perl interpreter itself\.

However\, given the above description of the problem\, how are we going to work
out where the bug is? :\-\(

Do you have the core file on disk? If you run gdb
\(something like gdb /usr/bin/perl core
\) by typing where at the gdb prompt can you get a stack backtrace to show
where the problem happens? This might start to pin the problem down

Nicholas Clark

**Comment by p5pRT** [comment]
### From dan@verliba.cz

> Do you have the core file on disk? If you run gdb
> \(something like gdb /usr/bin/perl core
> \) by typing where at the gdb prompt can you get a stack backtrace to show
> where the problem happens? This might start to pin the problem down
> 
> Nicholas Clark
>

$ gdb \`which perl\` core\.11500
GNU gdb 5\.3\-0\.1mdk \(Mandrake Linux\)
Copyright 2002 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and you
are
welcome to change it and/or distribute copies of it under certain
conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for
details\.
This GDB was configured as "i586\-mandrake\-linux\-gnu"\.\.\.\(no debugging
symbols found\)\.\.\.
Core was generated by \`perl \-d bot\.pl core\.727 \-d \-e 42'\.
Program terminated with signal 3\, Quit\.
Reading symbols from
/usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/CORE/libperl\.so\.\.\.
\(no debugging symbols found\)\.\.\.done\.
Loaded symbols for
/usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/CORE/libperl\.so
Reading symbols from /lib/libnsl\.so\.1\.\.\.\(no debugging symbols
found\)\.\.\.done\.
Loaded symbols for /lib/libnsl\.so\.1
Reading symbols from /lib/libdl\.so\.2\.\.\.\(no debugging symbols
found\)\.\.\.done\.
Loaded symbols for /lib/libdl\.so\.2
Reading symbols from /lib/i686/libm\.so\.6\.\.\.\(no debugging symbols
found\)\.\.\.done\.
Loaded symbols for /lib/i686/libm\.so\.6
Reading symbols from /lib/i686/libpthread\.so\.0\.\.\.\(no debugging symbols
found\)\.\.\.done\.
Loaded symbols for /lib/i686/libpthread\.so\.0
Reading symbols from /lib/i686/libc\.so\.6\.\.\.\(no debugging symbols
found\)\.\.\.done\.
Loaded symbols for /lib/i686/libc\.so\.6
Reading symbols from /lib/libcrypt\.so\.1\.\.\.\(no debugging symbols
found\)\.\.\.done\.
Loaded symbols for /lib/libcrypt\.so\.1
Reading symbols from /lib/libutil\.so\.1\.\.\.\(no debugging symbols
found\)\.\.\.done\.
Loaded symbols for /lib/libutil\.so\.1
Reading symbols from /lib/ld\-linux\.so\.2\.\.\.done\.
Loaded symbols for /lib/ld\-linux\.so\.2
Reading symbols from
/usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/auto/Socket/Socket\.so\.\.\.done\.
Loaded symbols for
/usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/auto/Socket/Socket\.so
Reading symbols from
/usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/auto/IO/IO\.so\.\.\.done\.
Loaded symbols for
/usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/auto/IO/IO\.so
Reading symbols from
/usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/auto/Fcntl/Fcntl\.so\.\.\.done\.
Loaded symbols for
/usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/auto/Fcntl/Fcntl\.so
Reading symbols from
/usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/auto/POSIX/POSIX\.so\.\.\.done\.
Loaded symbols for
/usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/auto/POSIX/POSIX\.so
Reading symbols from
/usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/auto/Cwd/Cwd\.so\.\.\.done\.
Loaded symbols for
/usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/auto/Cwd/Cwd\.so
Reading symbols from
/usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/auto/File/Glob/Glob\.so\.\.\.done\.
Loaded symbols for
/usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/auto/File/Glob/Glob\.so
Reading symbols from
/usr/lib/perl5/vendor\_perl/5\.8\.0/i386\-linux\-thread\-multi/auto/Term/ReadLine/Gnu/Gnu\.so\.\.\.
done\.
Loaded symbols for
/usr/lib/perl5/vendor\_perl/5\.8\.0/i386\-linux\-thread\-multi/auto/Term/ReadLine/Gnu/Gnu\.so
Reading symbols from /lib/libreadline\.so\.4\.3\.\.\.done\.
Loaded symbols for /lib/libreadline\.so\.4\.3
Reading symbols from /lib/libtermcap\.so\.2\.\.\.done\.
Loaded symbols for /lib/libtermcap\.so\.2
\#0  0x401bd392 in sigprocmask \(\) from /lib/i686/libc\.so\.6
\(gdb\) back
\#0  0x401bd392 in sigprocmask \(\) from /lib/i686/libc\.so\.6
\#1  0x403c91db in rl\_free\_line\_state \(\) from /lib/libreadline\.so\.4\.3
\(gdb\)

Dan

**Comment by p5pRT** [comment]
### From @wolfsage

Hello\,

Any way we can get more information on this coredump at this point \-
like source code \- or are you able to still trigger it on more recent
versions of Perl?

Otherwise\, should this ticket be closed? I don't think there's much that
can be done\, and both Perl and Readline have come along way since this
was filed\, suggesting that this bug \_may\_ have gone away\.

\-\- Matthew Horsfall \(alh\)

**Comment by p5pRT** [comment]
### From @ikegami

On Thu Mar 27 02&#8203;:03&#8203;:05 2003\, dan@&#8203;verliba\.cz wrote&#8203;:
> My script is a network client\. After more that an hour of no problems\,
> it carshes on broken pipe

I would expect a program to "crash" from SIGPIPE on writing to a broken
pipe\.

Is it possible the dump is the result of having received a SIGPIPE?

**Comment by p5pRT** [comment]
### From @doy

Closing this due to lack of information\. If this issue is still
reproducible\, feel free to reopen this ticket\.

\-doy

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Closing this due to lack of information\. If this issue is still
reproducible\, feel free to reopen this ticket\.

\-doy

**Comment by p5pRT** [comment]
@doy - Status changed from 'open' to 'resolved'
