### ISSUE TITLE
segfault in 5.8.0's PerlIOStdio_close

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6400]
Migrated from [rt.perl.org#21724](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=21724) (status was 'resolved')

Searchable as RT21724$

**Comment by p5pRT** [comment]
### From stas@stason.org

#### Created by stas@stason.org



Running the 5\.8\.0 perl bundled with mandrake\-8\.0\.

% /usr/bin/cpan

Your configuration suggests "/root/\.cpan" as your
CPAN\.pm working directory\. I could not create this directory due
to this error&#8203;: mkdir /root/\.cpan&#8203;: Permission denied at
/usr/lib/perl5/5\.8\.0/CPAN\.pm line 530

Please make sure the directory exists and is writable\.

Segmentation fault \(core dumped\)

\#0  0x40189092 in pthread\_mutex\_lock \(\) from /lib/i686/libpthread\.so\.0
\#1  0x4018b922 in flockfile \(\) from /lib/i686/libpthread\.so\.0
\#2  0x42062278 in fclose \(\) from /lib/i686/libc\.so\.6
\#3  0x40109fb8 in PerlIOStdio\_close \(\)
&nbsp;    from /usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/CORE/libperl\.so
\#4  0x401077b0 in PerlIO\_cleantable \(\)
&nbsp;    from /usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/CORE/libperl\.so
\#5  0x40109778 in PerlIO\_cleanup \(\)
&nbsp;    from /usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/CORE/libperl\.so
\#6  0x400345cd in perl\_destruct \(\)
&nbsp;    from /usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/CORE/libperl\.so
\#7  0x08049191 in main \(\)
\#8  0x42015b17 in \_\_libc\_start\_main \(\) from /lib/i686/libc\.so\.6

I've tried to reproduce with another 5\.8\.0 that I have installed on the
same system\, which was built with DEBUGGING enabled\, so I could get a better
trace\, but I can't reproduce it with that version\. The difference seems to
be in the optimization flags&#8203;:

the segfaulting build has&#8203;:
&nbsp;    config\_args='\-des \-Darchname=i386\-linux \-Dcc=gcc \-Doptimize=\-O3
&nbsp;   \-fomit\-frame\-pointer \-pipe \-mcpu=pentiumpro \-march=i586 \-ffast\-math
&nbsp;   \-fno\-strength\-reduce \-Dprefix=/usr \-Dvendorprefix=/usr \-Dsiteprefix=/usr
&nbsp;   \-Dman3ext=3pm \-Dcf\_by=MandrakeSoft \-Dmyhostname=localhost
&nbsp;   \-Dperladmin=root@&#8203;localhost \-Dd\_dosuid \-Ud\_csh \-Duseshrplib \-Dusethreads'
&nbsp;     optimize='\-O3 \-fomit\-frame\-pointer \-pipe \-mcpu=pentiumpro \-march=i586
&nbsp;   \-ffast\-math \-fno\-strength\-reduce'\,
&nbsp;   Compile\-time options&#8203;: MULTIPLICITY USE\_ITHREADS USE\_LARGE\_FILES
&nbsp;    PERL\_IMPLICIT\_CONTEXT

the non\-segfaulting build has&#8203;:
&nbsp;     config\_args='\-des \-Dprefix=/home/stas/perl/5\.8\.0\-ithread
&nbsp;    \-Dusethreads \-Doptimize=\-g \-Duseshrplib \-Dusedevel'
&nbsp;     optimize='\-g'\,
&nbsp;   Compile\-time options&#8203;: DEBUGGING MULTIPLICITY USE\_ITHREADS
&nbsp;   USE\_LARGE\_FILES PERL\_IMPLICIT\_CONTEXT

<details><summary>Perl Info</summary>

```

Flags:
     category=core
     severity=low

Site configuration information for perl v5.8.0:

Configured by pixel at Fri Sep  6 23:23:23 CEST 2002.

Summary of my perl5 (revision 5.0 version 8 subversion 0) configuration:
   Platform:
     osname=linux, osvers=2.4.19-2mdkenterprise, archname=i386-linux-thread-multi
     uname='linux no.mandrakesoft.com 2.4.19-2mdkenterprise #1 smp tue aug 13 
00:17:42 cest 2002 i686 unknown unknown gnulinux '
     config_args='-des -Darchname=i386-linux -Dcc=gcc -Doptimize=-O3 
-fomit-frame-pointer -pipe -mcpu=pentiumpro -march=i586 -ffast-math 
-fno-strength-reduce -Dprefix=/usr -Dvendorprefix=/usr -Dsiteprefix=/usr 
-Dman3ext=3pm -Dcf_by=MandrakeSoft -Dmyhostname=localhost 
-Dperladmin=root@localhost -Dd_dosuid -Ud_csh -Duseshrplib -Dusethreads'
     hint=recommended, useposix=true, d_sigaction=define
     usethreads=define use5005threads=undef useithreads=define 
usemultiplicity=define
     useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
     use64bitint=undef use64bitall=undef uselongdouble=undef
     usemymalloc=n, bincompat5005=undef
   Compiler:
     cc='gcc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing 
-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm',
     optimize='-O3 -fomit-frame-pointer -pipe -mcpu=pentiumpro -march=i586 
-ffast-math -fno-strength-reduce',
     cppflags='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing 
-I/usr/include/gdbm'
     ccversion='', gccversion='3.2 (Mandrake Linux 9.0 3.2-1mdk)', gccosandvers=''
     intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
     d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
     ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', 
lseeksize=8
     alignbytes=4, prototype=define
   Linker and Libraries:
     ld='gcc', ldflags =' -L/usr/local/lib'
     libpth=/usr/local/lib /lib /usr/lib
     libs=-lnsl -lndbm -lgdbm -ldl -lm -lpthread -lc -lcrypt -lutil
     perllibs=-lnsl -ldl -lm -lpthread -lc -lcrypt -lutil
     libc=/lib/libc-2.2.5.so, so=so, useshrplib=true, libperl=libperl.so
     gnulibc_version='2.2.5'
   Dynamic Linking:
     dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic 
-Wl,-rpath,/usr/lib/perl5/5.8.0/i386-linux-thread-multi/CORE'
     cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:



@INC for perl v5.8.0:
     /usr/lib/perl5/5.8.0/i386-linux-thread-multi
     /usr/lib/perl5/5.8.0
     /usr/lib/perl5/site_perl/5.8.0/i386-linux-thread-multi
     /usr/lib/perl5/site_perl/5.8.0
     /usr/lib/perl5/site_perl/5.6.1
     /usr/lib/perl5/site_perl/5.6.0
     /usr/lib/perl5/site_perl
     /usr/lib/perl5/vendor_perl/5.8.0/i386-linux-thread-multi
     /usr/lib/perl5/vendor_perl/5.8.0
     /usr/lib/perl5/vendor_perl
     .


Environment for perl v5.8.0:
     HOME=/home/stas
     LANG=en_US
     LANGUAGE=en_US:en
     LC_COLLATE=en_US
     LC_CTYPE=en_US
     LC_MESSAGES=en_US
     LC_MONETARY=en_US
     LC_NUMERIC=en_US
     LC_TIME=en_US
     LD_LIBRARY_PATH=/usr/X11R6/lib:/usr/X11R6/lib/modules
     LOGDIR (unset)
 
PATH=/usr//bin:/bin:/usr/bin:.:/usr/local/bin:/usr/X11R6/bin:/usr/games:/home/stas/bin:/home/stas/bin:/usr/local/bin:/usr/X11R6/bin:/usr/java/j2re1.4.0/bin/
     PERL_BADLANG (unset)
     SHELL=/bin/tcsh


__________________________________________________________________
Stas Bekman            JAm_pH ------> Just Another mod_perl Hacker
http://stason.org/     mod_perl Guide ---> http://perl.apache.org
mailto:stas@stason.org http://use.perl.org http://apacheweek.com
http://modperlbook.org http://apache.org   http://ticketmaster.com


```
</details>

**Comment by p5pRT** [comment]
### From @TJC

Hi\,
Since this bug was reported against a very old version of Perl\, I am 
marking it as resolved since I'm fairly sure it has been\.
However if you are still experiencing the issue on Perl 5\.10 or later\, 
please reply to this email to re\-open the bug for investigation\.

Thanks\.

On Thu Mar 27 19&#8203;:07&#8203;:18 2003\, stas wrote&#8203;:
> 
> This is a bug report for perl from stas@&#8203;stason\.org\,
> generated with the help of perlbug 1\.34 running under perl v5\.8\.0\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-


---
> \[Please enter your report here\]
> 
> Running the 5\.8\.0 perl bundled with mandrake\-8\.0\.
> 
> % /usr/bin/cpan
> 
> Your configuration suggests "/root/\.cpan" as your
> CPAN\.pm working directory\. I could not create this directory due
> to this error&#8203;: mkdir /root/\.cpan&#8203;: Permission denied at
> /usr/lib/perl5/5\.8\.0/CPAN\.pm line 530
> 
> Please make sure the directory exists and is writable\.
> 
> Segmentation fault \(core dumped\)
> 
> \#0  0x40189092 in pthread\_mutex\_lock \(\) from 
/lib/i686/libpthread\.so\.0
> \#1  0x4018b922 in flockfile \(\) from /lib/i686/libpthread\.so\.0
> \#2  0x42062278 in fclose \(\) from /lib/i686/libc\.so\.6
> \#3  0x40109fb8 in PerlIOStdio\_close \(\)
>     from /usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-
multi/CORE/libperl\.so
> \#4  0x401077b0 in PerlIO\_cleantable \(\)
>     from /usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-
multi/CORE/libperl\.so
> \#5  0x40109778 in PerlIO\_cleanup \(\)
>     from /usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-
multi/CORE/libperl\.so
> \#6  0x400345cd in perl\_destruct \(\)
>     from /usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-
multi/CORE/libperl\.so
> \#7  0x08049191 in main \(\)
> \#8  0x42015b17 in \_\_libc\_start\_main \(\) from /lib/i686/libc\.so\.6
> 
> I've tried to reproduce with another 5\.8\.0 that I have installed on
> the
> same system\, which was built with DEBUGGING enabled\, so I could 
get a
> better
> trace\, but I can't reproduce it with that version\. The difference
> seems to
> be in the optimization flags&#8203;:
> 
> the segfaulting build has&#8203;:
>     config\_args='\-des \-Darchname=i386\-linux \-Dcc=gcc \-
Doptimize=\-O3
>    \-fomit\-frame\-pointer \-pipe \-mcpu=pentiumpro \-march=i586 \-
ffast\-math
>    \-fno\-strength\-reduce \-Dprefix=/usr \-Dvendorprefix=/usr
> \-Dsiteprefix=/usr
>    \-Dman3ext=3pm \-Dcf\_by=MandrakeSoft \-
Dmyhostname=localhost
>    \-Dperladmin=root@&#8203;localhost \-Dd\_dosuid \-Ud\_csh \-Duseshrplib
> \-Dusethreads'
>      optimize='\-O3 \-fomit\-frame\-pointer \-pipe \-mcpu=pentiumpro
> \-march=i586
>    \-ffast\-math \-fno\-strength\-reduce'\,
>    Compile\-time options&#8203;: MULTIPLICITY USE\_ITHREADS 
USE\_LARGE\_FILES
>     PERL\_IMPLICIT\_CONTEXT
> 
> the non\-segfaulting build has&#8203;:
>      config\_args='\-des \-Dprefix=/home/stas/perl/5\.8\.0\-ithread
>     \-Dusethreads \-Doptimize=\-g \-Duseshrplib \-Dusedevel'
>      optimize='\-g'\,
>    Compile\-time options&#8203;: DEBUGGING MULTIPLICITY USE\_ITHREADS
>    USE\_LARGE\_FILES PERL\_IMPLICIT\_CONTEXT
> 
> 
> \[Please do not change anything below this line\]
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-


---
> \-\-\-
> Flags&#8203;:
>      category=core
>      severity=low
> \-\-\-
> Site configuration information for perl v5\.8\.0&#8203;:
> 
> Configured by pixel at Fri Sep  6 23&#8203;:23&#8203;:23 CEST 2002\.
> 
> Summary of my perl5 \(revision 5\.0 version 8 subversion 0\)
> configuration&#8203;:
>    Platform&#8203;:
>      osname=linux\, osvers=2\.4\.19\-2mdkenterprise\, archname=i386\-
linux\-
> thread\-multi
>      uname='linux no\.mandrakesoft\.com 2\.4\.19\-2mdkenterprise \#1 
smp tue
> aug 13
> 00&#8203;:17&#8203;:42 cest 2002 i686 unknown unknown gnulinux '
>      config\_args='\-des \-Darchname=i386\-linux \-Dcc=gcc \-
Doptimize=\-O3
> \-fomit\-frame\-pointer \-pipe \-mcpu=pentiumpro \-march=i586 \-
ffast\-math
> \-fno\-strength\-reduce \-Dprefix=/usr \-Dvendorprefix=/usr
> \-Dsiteprefix=/usr
> \-Dman3ext=3pm \-Dcf\_by=MandrakeSoft \-Dmyhostname=localhost
> \-Dperladmin=root@&#8203;localhost \-Dd\_dosuid \-Ud\_csh \-Duseshrplib
> \-Dusethreads'
>      hint=recommended\, useposix=true\, d\_sigaction=define
>      usethreads=define use5005threads=undef useithreads=define
> usemultiplicity=define
>      useperlio=define d\_sfio=undef uselargefiles=define 
usesocks=undef
>      use64bitint=undef use64bitall=undef uselongdouble=undef
>      usemymalloc=n\, bincompat5005=undef
>    Compiler&#8203;:
>      cc='gcc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE
> \-fno\-strict\-aliasing
> \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-
I/usr/include/gdbm'\,
>      optimize='\-O3 \-fomit\-frame\-pointer \-pipe \-mcpu=pentiumpro
> \-march=i586
> \-ffast\-math \-fno\-strength\-reduce'\,
>      cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing
> \-I/usr/include/gdbm'
>      ccversion=''\, gccversion='3\.2 \(Mandrake Linux 9\.0 3\.2\-1mdk\)'\,
> gccosandvers=''
>      intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
>      d\_longlong=define\, longlongsize=8\, d\_longdbl=define\,
> longdblsize=12
>      ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\,
> Off\_t='off\_t'\,
> lseeksize=8
>      alignbytes=4\, prototype=define
>    Linker and Libraries&#8203;:
>      ld='gcc'\, ldflags =' \-L/usr/local/lib'
>      libpth=/usr/local/lib /lib /usr/lib
>      libs=\-lnsl \-lndbm \-lgdbm \-ldl \-lm \-lpthread \-lc \-lcrypt \-lutil
>      perllibs=\-lnsl \-ldl \-lm \-lpthread \-lc \-lcrypt \-lutil
>      libc=/lib/libc\-2\.2\.5\.so\, so=so\, useshrplib=true\,
> libperl=libperl\.so
>      gnulibc\_version='2\.2\.5'
>    Dynamic Linking&#8203;:
>      dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-
> rdynamic
> \-Wl\,\-rpath\,/usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/CORE'
>      cccdlflags='\-fpic'\, lddlflags='\-shared \-L/usr/local/lib'
> 
> Locally applied patches&#8203;:
> 
> 
> \-\-\-
> @&#8203;INC for perl v5\.8\.0&#8203;:
>      /usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi
>      /usr/lib/perl5/5\.8\.0
>      /usr/lib/perl5/site\_perl/5\.8\.0/i386\-linux\-thread\-multi
>      /usr/lib/perl5/site\_perl/5\.8\.0
>      /usr/lib/perl5/site\_perl/5\.6\.1
>      /usr/lib/perl5/site\_perl/5\.6\.0
>      /usr/lib/perl5/site\_perl
>      /usr/lib/perl5/vendor\_perl/5\.8\.0/i386\-linux\-thread\-multi
>      /usr/lib/perl5/vendor\_perl/5\.8\.0
>      /usr/lib/perl5/vendor\_perl
>      \.
> 
> \-\-\-
> Environment for perl v5\.8\.0&#8203;:
>      HOME=/home/stas
>      LANG=en\_US
>      LANGUAGE=en\_US&#8203;:en
>      LC\_COLLATE=en\_US
>      LC\_CTYPE=en\_US
>      LC\_MESSAGES=en\_US
>      LC\_MONETARY=en\_US
>      LC\_NUMERIC=en\_US
>      LC\_TIME=en\_US
>      LD\_LIBRARY\_PATH=/usr/X11R6/lib&#8203;:/usr/X11R6/lib/modules
>      LOGDIR \(unset\)
> 
> 
PATH=/usr//bin&#8203;:/bin&#8203;:/usr/bin&#8203;:\.&#8203;:/usr/local/bin&#8203;:/usr/X11R6/bin&#8203;:/usr/ga
mes&#8203;:/home/stas/bin&#8203;:/home/stas/bin&#8203;:/usr/local/bin&#8203;:/usr/X11R6/bin&#8203;:/u
sr/java/j2re1\.4\.0/bin/
>      PERL\_BADLANG \(unset\)
>      SHELL=/bin/tcsh
> 
> 
> \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
> Stas Bekman            JAm\_pH \-\-\-\-\-\-> Just Another mod\_perl Hacker
> http&#8203;://stason\.org/     mod\_perl Guide \-\-\-> http&#8203;://perl\.apache\.org
> mailto&#8203;:stas@&#8203;stason\.org http&#8203;://use\.perl\.org http&#8203;://apacheweek\.com
> http&#8203;://modperlbook\.org http&#8203;://apache\.org   http&#8203;://ticketmaster\.com
>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@TJC - Status changed from 'open' to 'resolved'
