### ISSUE TITLE
[5.8] :scalar and magic strings

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6443]
Migrated from [rt.perl.org#21950](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=21950) (status was 'resolved')

Searchable as RT21950$

**Comment by p5pRT** [comment]
### From gnat@oreilly.com

This coredumps&#8203;:

 open $fh\, "\<"\, \\$0;
 print \<$fh>;         \# coredump

Strangely\, opening $/ in this fashion works but $\! does not\.  This is
tested on 5\.8\.0 and the 5\.8\.1 tree snapshot\, on Mac OS X 10\.2\.4\.

Nat

**Comment by p5pRT** [comment]
### From @tux

On Thu 17 Apr 2003 05&#8203;:54\, Nathan Torkington \(via RT\) \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> 
> \[perlbug note \- this message was caught in the spam filter because it
> does not contain the special sequence of four magic letters \- RS\]
> 
> This coredumps&#8203;:
> 
>  open $fh\, "\<"\, \\$0;
>  print \<$fh>;         \# coredump
> 
> Strangely\, opening $/ in this fashion works but $\! does not\.  This is
> tested on 5\.8\.0 and the 5\.8\.1 tree snapshot\, on Mac OS X 10\.2\.4\.

Confirmed on HP\-UX 11\.00&#8203;:

l1&#8203;:/u/usr/merijn 101 > cat >xx\.pl
open $fh\, "\<"\, \\$0;
print \<$fh>;
l1&#8203;:/u/usr/merijn 102 > perl5\.00503 xx\.pl
Too many arguments for open at xx\.pl line 1\, near "$0;"
Execution of xx\.pl aborted due to compilation errors\.
Exit 255
l1&#8203;:/u/usr/merijn 103 > perl5\.6\.1 xx\.pl
l1&#8203;:/u/usr/merijn 104 > perl5\.8\.0 xx\.pl
Segmentation fault \(core dumped\)
Exit 139
l1&#8203;:/u/usr/merijn 105 > perl5\.9\.0 xx\.pl
Segmentation fault \(core dumped\)
Exit 139
l1&#8203;:/u/usr/merijn 106 >

\(gdb\) where
\#0  0x00049060 in Perl\_mg\_get \(\)
\#1  0x00056548 in Perl\_sv\_2pv\_flags \(\)
\#2  0x0005640c in Perl\_sv\_2pv\_nolen \(\)
\#3  0xc0cbf1a4 in PerlIOScalar\_get\_base \(\)
&nbsp;   from /pro/lib/perl5/5\.9\.0/PA\-RISC2\.0/auto/PerlIO/scalar/scalar\.sl
\#4  0xc0cbf204 in PerlIOScalar\_get\_ptr \(\)
&nbsp;   from /pro/lib/perl5/5\.9\.0/PA\-RISC2\.0/auto/PerlIO/scalar/scalar\.sl
\#5  0x00064f10 in Perl\_PerlIO\_get\_ptr \(\)
\#6  0x0005cc10 in Perl\_sv\_gets \(\)
\#7  0x000a68cc in Perl\_do\_readline \(\)
\#8  0x000a35ec in Perl\_pp\_readline \(\)
\#9  0x0009e308 in Perl\_runops\_debug \(\)
\#10 0x0002bc88 in S\_run\_body \(\)
\#11 0x0002b8b0 in perl\_run \(\)
\#12 0x00027f94 in main \(\)
\(gdb\)

\-\- 
H\.Merijn Brand        Amsterdam Perl Mongers \(http&#8203;://amsterdam\.pm\.org/\)
using perl\-5\.6\.1\, 5\.8\.0 & 633 on HP\-UX 10\.20 & 11\.00\, AIX 4\.2\, AIX 4\.3\,
&nbsp;  WinNT 4\, Win2K pro & WinCE 2\.11\.  Smoking perl CORE&#8203;: smokers@&#8203;perl\.org
http&#8203;://archives\.develooper\.com/daily\-build@&#8203;perl\.org/   perl\-qa@&#8203;perl\.org
send smoke reports to&#8203;: smokers\-reports@&#8203;perl\.org\, QA&#8203;: http&#8203;://qa\.perl\.org

**Comment by p5pRT** [comment]
### From nick.ing-simmons@elixent.com

H\.Merijn Brand \<h\.m\.brand@&#8203;hccnet\.nl> writes&#8203;:
>On Thu 17 Apr 2003 05&#8203;:54\, Nathan Torkington \(via RT\) \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
>> 
>> \[perlbug note \- this message was caught in the spam filter because it
>> does not contain the special sequence of four magic letters \- RS\]
>> 
>> This coredumps&#8203;:
>> 
>>  open $fh\, "\<"\, \\$0;
>>  print \<$fh>;         \# coredump
>> 
>> Strangely\, opening $/ in this fashion works but $\! does not\.  This is
>> tested on 5\.8\.0 and the 5\.8\.1 tree snapshot\, on Mac OS X 10\.2\.4\.

When writing :scalar I had not really considered magical variables\.
But none the less I don't see why it fails here\.

>
>Confirmed on HP\-UX 11\.00&#8203;:
>
>l1&#8203;:/u/usr/merijn 101 > cat >xx\.pl
>open $fh\, "\<"\, \\$0;
>print \<$fh>;
>l1&#8203;:/u/usr/merijn 102 > perl5\.00503 xx\.pl
>Too many arguments for open at xx\.pl line 1\, near "$0;"
>Execution of xx\.pl aborted due to compilation errors\.
>Exit 255
>l1&#8203;:/u/usr/merijn 103 > perl5\.6\.1 xx\.pl
>l1&#8203;:/u/usr/merijn 104 > perl5\.8\.0 xx\.pl
>Segmentation fault \(core dumped\)
>Exit 139
>l1&#8203;:/u/usr/merijn 105 > perl5\.9\.0 xx\.pl
>Segmentation fault \(core dumped\)
>Exit 139
>l1&#8203;:/u/usr/merijn 106 >
>
>\(gdb\) where
>\#0  0x00049060 in Perl\_mg\_get \(\)
>\#1  0x00056548 in Perl\_sv\_2pv\_flags \(\)
>\#2  0x0005640c in Perl\_sv\_2pv\_nolen \(\)
>\#3  0xc0cbf1a4 in PerlIOScalar\_get\_base \(\)
>   from /pro/lib/perl5/5\.9\.0/PA\-RISC2\.0/auto/PerlIO/scalar/scalar\.sl
>\#4  0xc0cbf204 in PerlIOScalar\_get\_ptr \(\)
>   from /pro/lib/perl5/5\.9\.0/PA\-RISC2\.0/auto/PerlIO/scalar/scalar\.sl
>\#5  0x00064f10 in Perl\_PerlIO\_get\_ptr \(\)
>\#6  0x0005cc10 in Perl\_sv\_gets \(\)
>\#7  0x000a68cc in Perl\_do\_readline \(\)
>\#8  0x000a35ec in Perl\_pp\_readline \(\)
>\#9  0x0009e308 in Perl\_runops\_debug \(\)
>\#10 0x0002bc88 in S\_run\_body \(\)
>\#11 0x0002b8b0 in perl\_run \(\)
>\#12 0x00027f94 in main \(\)
>\(gdb\)

And linux&#8203;:

\(gdb\) bt
\#0  0x80a978b in Perl\_mg\_get \(my\_perl=0x81426a8\, sv=0x814fb70\) at mg\.c&#8203;:134
\#1  0x80bfaff in Perl\_sv\_2pv\_flags \(my\_perl=0x81426a8\, sv=0x814fb70\,
&nbsp;    lp=0xbfffcf98\, flags=2\) at sv\.c&#8203;:2929
\#2  0x80bfa19 in Perl\_sv\_2pv\_nolen \(my\_perl=0x81426a8\, sv=0x814fb70\)
&nbsp;    at sv\.c&#8203;:2857
\#3  0x4021782d in PerlIOScalar\_get\_base \(my\_perl=0x81426a8\, f=0x814c550\)
&nbsp;    at scalar\.xs&#8203;:164
\#4  0x40217870 in PerlIOScalar\_get\_ptr \(my\_perl=0x81426a8\, f=0x814c550\)
&nbsp;    at scalar\.xs&#8203;:175
\#5  0x810cdb9 in Perl\_PerlIO\_get\_ptr \(my\_perl=0x81426a8\, f=0x814c550\)
&nbsp;    at perlio\.c&#8203;:1712
\#6  0x80c55d4 in Perl\_sv\_gets \(my\_perl=0x81426a8\, sv=0x81432fc\, fp=0x814c550\,
&nbsp;    append=0\) at sv\.c&#8203;:6462
\#7  0x80b7e85 in Perl\_do\_readline \(my\_perl=0x81426a8\) at pp\_hot\.c&#8203;:1542
\#8  0x80b501c in Perl\_pp\_readline \(my\_perl=0x81426a8\) at pp\_hot\.c&#8203;:224
\#9  0x80a38fc in Perl\_runops\_debug \(my\_perl=0x81426a8\) at dump\.c&#8203;:1424
\#10 0x806314d in S\_run\_body \(my\_perl=0x81426a8\, oldscope=1\) at perl\.c&#8203;:1576
\#11 0x8062da6 in perl\_run \(my\_perl=0x81426a8\) at perl\.c&#8203;:1495
\#12 0x805f002 in main \(argc=3\, argv=0xbffff314\, env=0xbffff324\)

But I don't see why \- when I poke at vars they seem okay&#8203;:

134             if \(\!\(mg\->mg\_flags & MGf\_GSKIP\) && vtbl && vtbl\->svt\_get\) \{
\(gdb\) print mg
$1 = \(MAGIC \*\) 0x815a920
\(gdb\) print vtbl
$2 = \(MGVTBL \*\) 0x6f4c5358
\(gdb\) print \*vtbl
$3 = \{svt\_get = 0\, svt\_set = 0\, svt\_len = 0\, svt\_clear = 0\, svt\_free = 0\,
&nbsp;  svt\_copy = 0\, svt\_dup = 0\}
\(gdb\) print \*mg
$4 = \{mg\_moremagic = 0x2f62696c\, mg\_virtual = 0x6f4c5358\, mg\_private = 25697\,
&nbsp;  mg\_type = 101 'e'\, mg\_flags = 114 'r'\, mg\_obj = 0x6d702e\,
&nbsp;  mg\_ptr = 0x18 \<Address 0x18 out of bounds>\, mg\_len = 25\}
\(gdb\)
\-\- 
Nick Ing\-Simmons
http&#8203;://www\.ni\-s\.u\-net\.com/

**Comment by p5pRT** [comment]
### From enache@rdslink.ro

On Wed\, Apr 16\, 2003 at 08&#8203;:54&#8203;:29PM \-0700\, Nathan Torkington wrote&#8203;:
> 
> \[perlbug note \- this message was caught in the spam filter because it
> does not contain the special sequence of four magic letters \- RS\]
> 
> This coredumps&#8203;:
> 
>  open $fh\, "\<"\, \\$0;
>  print \<$fh>;         \# coredump
> 
> Strangely\, opening $/ in this fashion works but $\! does not\.  This is
> tested on 5\.8\.0 and the 5\.8\.1 tree snapshot\, on Mac OS X 10\.2\.4\.

Please try this&#8203;:



---
<details><summary>Inline Patch</summary>

```diff
diff -rup /arc/bleadperl/ext/PerlIO/scalar/scalar.xs perl/ext/PerlIO/scalar/scalar.xs
--- /arc/bleadperl/ext/PerlIO/scalar/scalar.xs	2003-02-12 05:30:09.000000000 +0200
+++ perl/ext/PerlIO/scalar/scalar.xs	2003-04-17 14:32:54.000000000 +0300
@@ -37,7 +37,7 @@ PerlIOScalar_pushed(pTHX_ PerlIO * f, co
     else {
 	s->var = newSVpvn("", 0);
     }
-    sv_upgrade(s->var, SVt_PV);
+    SvUPGRADE(s->var, SVt_PV);
     code = PerlIOBase_pushed(aTHX_ f, mode, Nullsv, tab);
     if ((PerlIOBase(f)->flags) & PERLIO_F_TRUNCATE)
 	SvCUR(s->var) = 0;
diff -rup /arc/bleadperl/ext/PerlIO/t/scalar.t perl/ext/PerlIO/t/scalar.t
--- /arc/bleadperl/ext/PerlIO/t/scalar.t	2002-08-06 23:55:23.000000000 +0300
+++ perl/ext/PerlIO/t/scalar.t	2003-04-17 14:28:32.000000000 +0300
@@ -10,7 +10,7 @@ BEGIN {
 }
 
 $| = 1;
-print "1..23\n";
+print "1..24\n";
 
 my $fh;
 my $var = "ok 2\n";
@@ -120,3 +120,9 @@ close($dup);
 open $fh, '<', \42;
 print <$fh> eq "42" ? "ok 23\n" : "not ok 23\n";
 close $fh;
+
+# reading from magic scalars
+
+{ package P; sub TIESCALAR {bless{}} sub FETCH {"ok 24\n"} }
+tie $p, P; open $fh, '<', \$p;
+print <$fh>;
----------------------------------------------------------------------

Regards
Adi
```
</details>

**Comment by p5pRT** [comment]
### From enache@rdslink.ro

On Wed\, Apr 16\, 2003 at 08&#8203;:54&#8203;:29PM \-0700\, Nathan Torkington wrote&#8203;:
> 
> \[perlbug note \- this message was caught in the spam filter because it
> does not contain the special sequence of four magic letters \- RS\]
> 
> This coredumps&#8203;:
> 
>  open $fh\, "\<"\, \\$0;
>  print \<$fh>;         \# coredump
> 
> Strangely\, opening $/ in this fashion works but $\! does not\.  This is
> tested on 5\.8\.0 and the 5\.8\.1 tree snapshot\, on Mac OS X 10\.2\.4\.

Please try this&#8203;:



---
<details><summary>Inline Patch</summary>

```diff
diff -rup /arc/bleadperl/ext/PerlIO/scalar/scalar.xs perl/ext/PerlIO/scalar/scalar.xs
--- /arc/bleadperl/ext/PerlIO/scalar/scalar.xs	2003-02-12 05:30:09.000000000 +0200
+++ perl/ext/PerlIO/scalar/scalar.xs	2003-04-17 14:32:54.000000000 +0300
@@ -37,7 +37,7 @@ PerlIOScalar_pushed(pTHX_ PerlIO * f, co
     else {
 	s->var = newSVpvn("", 0);
     }
-    sv_upgrade(s->var, SVt_PV);
+    SvUPGRADE(s->var, SVt_PV);
     code = PerlIOBase_pushed(aTHX_ f, mode, Nullsv, tab);
     if ((PerlIOBase(f)->flags) & PERLIO_F_TRUNCATE)
 	SvCUR(s->var) = 0;
diff -rup /arc/bleadperl/ext/PerlIO/t/scalar.t perl/ext/PerlIO/t/scalar.t
--- /arc/bleadperl/ext/PerlIO/t/scalar.t	2002-08-06 23:55:23.000000000 +0300
+++ perl/ext/PerlIO/t/scalar.t	2003-04-17 14:28:32.000000000 +0300
@@ -10,7 +10,7 @@ BEGIN {
 }
 
 $| = 1;
-print "1..23\n";
+print "1..24\n";
 
 my $fh;
 my $var = "ok 2\n";
@@ -120,3 +120,9 @@ close($dup);
 open $fh, '<', \42;
 print <$fh> eq "42" ? "ok 23\n" : "not ok 23\n";
 close $fh;
+
+# reading from magic scalars
+
+{ package P; sub TIESCALAR {bless{}} sub FETCH {"ok 24\n"} }
+tie $p, P; open $fh, '<', \$p;
+print <$fh>;
----------------------------------------------------------------------

Regards
Adi
```
</details>

**Comment by p5pRT** [comment]
### From ams@wiw.org

At 2003\-04\-17 14&#8203;:35&#8203;:36 \+0300\, enache@&#8203;rdslink\.ro wrote&#8203;:
>
> \-\-\- /arc/bleadperl/ext/PerlIO/t/scalar\.t    2002\-08\-06 23&#8203;:55&#8203;:23\.000000000 \+0300
> \+\+\+ perl/ext/PerlIO/t/scalar\.t    2003\-04\-17 14&#8203;:28&#8203;:32\.000000000 \+0300
> @&#8203;@&#8203; \-10\,7 \+10\,7 @&#8203;@&#8203; BEGIN \{

I was about to commit the SvUPGRADE fix\, and I noticed your message just
in time for me to steal your test case\.

Thanks\, applied\. \(\#19247\)

\-\- ams

**Comment by p5pRT** [comment]
### From dankogai@dan.co.jp

On Thursday\, April 17\, 2003\, at 12&#8203;:54  PM\, Nathan Torkington \(via RT\) 
wrote&#8203;:
> This coredumps&#8203;:
>
>  open $fh\, "\<"\, \\$0;
>  print \<$fh>;         \# coredump
>
> Strangely\, opening $/ in this fashion works but $\! does not\.  This is
> tested on 5\.8\.0 and the 5\.8\.1 tree snapshot\, on Mac OS X 10\.2\.4\.

Also happens on FreeBSD\.  FYI this is where caused SIGSEGV according to 
bleedperl

> Program received signal SIGSEGV\, Segmentation fault\.
> Perl\_mg\_get \(my\_perl=0x8185000\, sv=0x8190228\) at mg\.c&#8203;:132
> 132             MGVTBL \*vtbl = mg\->mg\_virtual;

&nbsp;  What is so strange is that

&nbsp;    open my $fh\, '\<' \\$0 or die "$\!";

does NOT die and neither does

&nbsp;    my $fn = \\$0;
&nbsp;    open my $fh\, '\<' $fn or die "$\!";

If you coerce stringification with "" as in

&nbsp;    my $fn = \\$0;
&nbsp;    open my $fh\, '\<'\, "$fn" or die "$\!";

perl finally dies gracefully with "No such file or directory"\.  So all 
it takes to fix this to force stringification\.

Dan the Man with too Many Cores Dumped

**Comment by p5pRT** [comment]
@cwest - Status changed from 'new' to 'resolved'
