### ISSUE TITLE
Very simple and looks like a bug...

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6451]
Migrated from [rt.perl.org#21969](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=21969) (status was 'resolved')

Searchable as RT21969$

**Comment by p5pRT** [comment]
### From xlaboratory@aol.com

Very simple and looks like a bug\.\.\.

I tried this using perl 5\.6 and 5\.8 on SUN and Linux\. The following code always cause "Segmentation fault" if you are going to produce upto 500K recursive calls\, in the same time 100K iterations works fine\. BTW\.\.\. The same C sample works fine\. 

The code is below\.\.\.

\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
sub count\($$\) \{

&nbsp;        my\( $i\, $i\_max\) = @&#8203;\_;

&nbsp;        count\($i\, $i\_max\) if\( \+\+$$i \< $i\_max \);

&nbsp;        return;
\}

my $i;
my $i\_max = 500000;

print "Start\\n";

count\(\\$i\, $i\_max\);

print "Stop&#8203;: $i iterations\.\.\.\\n";

exit;
\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#

**Comment by p5pRT** [comment]
### From @schwern

On Tue\, Apr 15\, 2003 at 08&#8203;:13&#8203;:39PM \-0000\, xlaboratory@&#8203;aol\.com \(via RT\) wrote&#8203;:
> Very simple and looks like a bug\.\.\.
> 
> I tried this using perl 5\.6 and 5\.8 on SUN and Linux\. The following code always cause "Segmentation fault" if you are going to produce upto 500K recursive calls\, in the same time 100K iterations works fine\. BTW\.\.\. The same C sample works fine\. 

OS X says "Illegal Instruction"\.  Here's what gdb on 5\.8\.0 has to say&#8203;:

Program received signal EXC\_BAD\_INSTRUCTION\, Illegal instruction/operand\.
0x000103c0 in ?? \(\)
\(gdb\) bt
\#0  0x000103c0 in ?? \(\)
\#1  0x00342b8c in Perl\_runops\_debug \(\) at dump\.c&#8203;:1398
\#2  0x002e6ef8 in perl\_run \(my\_perl=0x0\) at perl\.c&#8203;:1600
\#3  0x000027a0 in main \(argc=2\, argv=0x3f5a18\, env=0x180000\) at perlmain\.c&#8203;:85
\#4  0x00002490 in \_start \(argc=2\, argv=0xbffffb58\, envp=0xbffffb64\) at /SourceCache/Csu/Csu\-45/crt\.c&#8203;:267
\#5  0x00002310 in start \(\)


\-\- 
Obscenity is the last resort of the illiterate\, Mother Fucker
&nbsp;        \-\- KAL

**Comment by p5pRT** [comment]
### From @tux

On Tue 15 Apr 2003 22&#8203;:13\, "xlaboratory@&#8203;aol\.com \(via RT\)" \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> Very simple and looks like a bug\.\.\.
> 
> I tried this using perl 5\.6 and 5\.8 on SUN and Linux\. The following code
> always cause "Segmentation fault" if you are going to produce upto 500K
> recursive calls\, in the same time 100K iterations works fine\. BTW\.\.\. The
> same C sample works fine\. 

Guess it has changed over time\, but is solved in the development track \(5\.9\.0\)\,
and is already fixed in the upcoming 5\.8\.1\, so await that version eagerly :\)

l1&#8203;:/u/usr/merijn 102 > cat xx\.pl
sub count \($$\)
\{
&nbsp;    my \($i\, $i\_max\) = @&#8203;\_;

&nbsp;    count \($i\, $i\_max\) if \(\+\+$$i \< $i\_max\);

&nbsp;    return;
&nbsp;    \} \# count

my $i;
my $i\_max = 500000;

print "Start\\n";

count \(\\$i\, $i\_max\);

print "Stop&#8203;: $i iterations\.\.\.\\n";
l1&#8203;:/u/usr/merijn 103 > perl5\.00503 xx\.pl
Start
Out of memory during "large" request for 67112960 bytes at xx\.pl line 5\.
Attempt to clear deleted array at xx\.pl line 5\.
Bus error \(core dumped\)
Exit 138
l1&#8203;:/u/usr/merijn 104 > perl5\.6\.1 xx\.pl
Start
Out of memory during request for 16 bytes\, total sbrk\(\) is 265096092 bytes\!
Bus error \(core dumped\)
Exit 138
l1&#8203;:/u/usr/merijn 105 > perl5\.8\.0 xx\.pl
Start
Bus error \(core dumped\)
Exit 138
l1&#8203;:/u/usr/merijn 106 > perl5\.9\.0 xx\.pl
Start
Stop&#8203;: 500000 iterations\.\.\.
l1&#8203;:/u/usr/merijn 107 > /pro/3gl/CPAN/perl\-5\.8\.x/perl \-I/pro/3gl/CPAN/perl\-5\.8\.x/lib xx\.pl
Start
Stop&#8203;: 500000 iterations\.\.\.
l1&#8203;:/u/usr/merijn 108 >

\-\- 
H\.Merijn Brand        Amsterdam Perl Mongers \(http&#8203;://amsterdam\.pm\.org/\)
using perl\-5\.6\.1\, 5\.8\.0 & 633 on HP\-UX 10\.20 & 11\.00\, AIX 4\.2\, AIX 4\.3\,
&nbsp;  WinNT 4\, Win2K pro & WinCE 2\.11\.  Smoking perl CORE&#8203;: smokers@&#8203;perl\.org
http&#8203;://archives\.develooper\.com/daily\-build@&#8203;perl\.org/   perl\-qa@&#8203;perl\.org
send smoke reports to&#8203;: smokers\-reports@&#8203;perl\.org\, QA&#8203;: http&#8203;://qa\.perl\.org

**Comment by p5pRT** [comment]
### From @eserte

"xlaboratory@&#8203;aol\.com \(via RT\)" \<perlbug\-followup@&#8203;perl\.org> writes&#8203;:

> \# New Ticket Created by  xlaboratory@&#8203;aol\.com 
> \# Please include the string&#8203;:  \[perl \#21969\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: http&#8203;://rt\.perl\.org/rt2/Ticket/Display\.html?id=21969 >
> 
> 
> Very simple and looks like a bug\.\.\.
> 
> I tried this using perl 5\.6 and 5\.8 on SUN and Linux\. The following code always cause "Segmentation fault" if you are going to produce upto 500K recursive calls\, in the same time 100K iterations works fine\. BTW\.\.\. The same C sample works fine\. 
> 

Do you get "Out of memory" messages? On my FreeBSD box\, the code eats
about 800 bytes per recursion call\. Sometimes it's just an "Out of
memory" message\, sometimes I get an additional segmentation fault\.

Regards\,
&nbsp;    Slaven


> The code is below\.\.\.
> 
> \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
> sub count\($$\) \{
> 
>         my\( $i\, $i\_max\) = @&#8203;\_;
> 
>         count\($i\, $i\_max\) if\( \+\+$$i \< $i\_max \);
> 
>         return;
> \}
> 
> my $i;
> my $i\_max = 500000;
> 
> print "Start\\n";
> 
> count\(\\$i\, $i\_max\);
> 
> print "Stop&#8203;: $i iterations\.\.\.\\n";
> 
> exit;
> \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
> 
> 

\-\- 
Slaven Rezic \- slaven@&#8203;rezic\.de
&nbsp;  BBBike \- route planner for cyclists in Berlin
&nbsp;  WWW version&#8203;:                           http&#8203;://www\.bbbike\.de
&nbsp;  Perl/Tk version for Unix and Windows&#8203;:  http&#8203;://bbbike\.sourceforge\.net

**Comment by p5pRT** [comment]
### From xlaboratory@aol.com

In a message dated 4/17/2003 5&#8203;:13&#8203;:45 AM Eastern Daylight Time\, 
perlbug\-followup@&#8203;perl\.org writes&#8203;:

> On Tue 15 Apr 2003 22&#8203;:13\, "xlaboratory@&#8203;aol\.com \(via RT\)" \<
> perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> >Very simple and looks like a bug\.\.\.
> >
> >I tried this using perl 5\.6 and 5\.8 on SUN and Linux\. The following code
> >always cause "Segmentation fault" if you are going to produce upto 500K
> >recursive calls\, in the same time 100K iterations works fine\. BTW\.\.\. The
> >same C sample works fine\. 
> 
> Guess it has changed over time\, but is solved in the development track 
> \(5\.9\.0\)\,
> and is already fixed in the upcoming 5\.8\.1\, so await that version eagerly 
> :\)
> 

Nice to hear about it\.\.\. but I guess the problem is deeper\.\.\. I guess the 
perl uses wrong strategy in recursive operations\.\.\. if we are able to break 
it\. This test was using to get metrics of time what perl spending on the 
recursive calls\. The recursive calls/returns in my program waste the same 
time like\, for instance\, print to a file from this recursive function\. 

I did compare C \(no optimization\) vs Perl in loops like this\.\.\. Perl shows a 
second at 100K iterations \(was not able to get better metrics due to this 
issue\) and C shows this second when 100M iterations produced\. 

I had to break down my beautiful Perl code to avoid additional recursive 
calls\. So\, it works but became ugly \.\.\. and I'm thinking about to move 
everything on the C\.

\- Serge

**Comment by p5pRT** [comment]
### From @JohnPeacock

XLaboratory@&#8203;aol\.com wrote&#8203;:
> I did compare C \(no optimization\) vs Perl in loops like this\.\.\. Perl shows a 
> second at 100K iterations \(was not able to get better metrics due to this 
> issue\) and C shows this second when 100M iterations produced\. 
> 
> I had to break down my beautiful Perl code to avoid additional recursive 
> calls\. So\, it works but became ugly \.\.\. and I'm thinking about to move 
> everything on the C\.
> 

Perl is a wonderful tool\, but it is by no means suitable for every program out 
there\.  Now that you have modelled your application in Perl\, and discovered the 
limitations\, converting it to C for the production version is completely 
understandable\.  There is nothing wrong with Perl \(now that the core dumping has 
been fixed ;~\); it just isn't suitable for the task at hand\.

John

\-\- 
John Peacock
Director of Information Research and Technology
Rowman & Littlefield Publishing Group
4501 Forbes Boulevard
Suite H
Lanham\, MD  20706
301\-459\-3366 x\.5010
fax 301\-429\-5748

**Comment by p5pRT** [comment]
### From @schwern

On Thu\, Apr 17\, 2003 at 12&#8203;:23&#8203;:44PM \-0400\, XLaboratory@&#8203;aol\.com wrote&#8203;:
> > Guess it has changed over time\, but is solved in the development track 
> > \(5\.9\.0\)\,
> > and is already fixed in the upcoming 5\.8\.1\, so await that version eagerly 
> > :\)
> 
> Nice to hear about it\.\.\. but I guess the problem is deeper\.\.\. I guess the 
> perl uses wrong strategy in recursive operations\.\.\. if we are able to break 
> it\. This test was using to get metrics of time what perl spending on the 
> recursive calls\. The recursive calls/returns in my program waste the same 
> time like\, for instance\, print to a file from this recursive function\. 
> 
> I did compare C \(no optimization\) vs Perl in loops like this\.\.\. Perl shows a 
> second at 100K iterations \(was not able to get better metrics due to this 
> issue\) and C shows this second when 100M iterations produced\. 
> 
> I had to break down my beautiful Perl code to avoid additional recursive 
> calls\. So\, it works but became ugly \.\.\. and I'm thinking about to move 
> everything on the C\.

Well\, as mentioned the problem is fixed in the upcoming 5\.8\.1\, a prerelease
version of which is available here&#8203;:
ftp&#8203;://ftp\.linux\.activestate\.com/pub/staff/gsar/APC/perl\-5\.8\.x/

If you can't wait for that\, instead of moving \*everything\* to C consider
just moving the part of your code that has to go deeply recursive to C using
either XS or the brilliant Inline&#8203;::C module\.  Its a lot less effort to port
a handful of hot subroutines than an entire application and you'll probably 
get just as much of a performance boost\.


\-\- 
One disease\, long life\.  No disease\, short life\.

**Comment by p5pRT** [comment]
@schwern - Status changed from 'new' to 'resolved'
