### ISSUE TITLE
perlio callback functions get their args mangled

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6499]
Migrated from [rt.perl.org#22163](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=22163) (status was 'resolved')

Searchable as RT22163$

**Comment by p5pRT** [comment]
### From stas@stason.org

I get C function arguments changing their values "at will" with perlio
callback functions\.

Something strange happens with APR&#8203;::PerlIO perlio layer running with
perl\-5\.8\.0 w/o threads\. it works fine w/ threads\. I can reproduce a
similar problem with a standalone script \(using Inline for
convenience\) and you should be able to reproduce it as well\. More over
this time the problem inhibits itself w/ and w/o thread\-enabled
perl\-5\.8\.0\.

When I run the code listed next I get&#8203;:

% perl\-5\.8\.0 perliobug\.pl
starting debug
in seek&#8203;: offset=1\, whence=0\, check=0
in seek&#8203;: offset=0\, whence=0\, check=1
in seek&#8203;: offset=2\, whence=0\, check=2

Notice that the automatic var 'check' which is a copy of the argument
'whence' works just fine\, however whence itself gets reset to zero
when used\. The C function to look at is&#8203;: PerlIOFoo\_seek

At the end you will also find a gdb script\, which you can invoke with&#8203;:

% gdb \-command=\.debug

to debug this thing interactively\. It's already adjusted to make it easy to 
get to PerlIOFoo\_seek's guts

Here is the script&#8203;:

\-\-\-\-\-\-\-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

use strict;
use warnings;

BEGIN \{
&nbsp;     use Inline Config =>
&nbsp;         \#FORCE\_BUILD => 1\,
&nbsp;         CLEAN\_AFTER\_BUILD => 0;

&nbsp;     use Inline C => Config =>
&nbsp;         AUTO\_INCLUDE => '\#include "perliol\.h"'\,
&nbsp;         BOOT         => 'PerlIO\_define\_layer\(aTHX\_ &PerlIO\_Foo\);'\,
&nbsp;         OPTIMIZE     => '\-g';

&nbsp;     use Inline C => \<\<END;
void my\_bp\(\) \{
&nbsp;     dTHX;
&nbsp;     Perl\_warn\(aTHX\_ "starting debug\\n"\);
\}

typedef struct \{
&nbsp;     struct \_PerlIO base;
\} PerlIOFoo;

static IV PerlIOFoo\_seek\(pTHX\_ PerlIO \*f\, Off\_t offset\, int whence\)
\{
&nbsp;     int check = whence;

&nbsp;     Perl\_warn\(aTHX\_ "in seek&#8203;: offset=%d\, whence=%d\, check=%d\\n"\,
&nbsp;               offset\, whence\, check\);

&nbsp;     return 0;
\}

static PerlIO\_funcs PerlIO\_Foo = \{
&nbsp;     sizeof\(PerlIO\_funcs\)\,
&nbsp;     "Foo"\,
&nbsp;     sizeof\(PerlIOFoo\)\,
&nbsp;     PERLIO\_K\_MULTIARG\,
&nbsp;     PerlIOBase\_pushed\,
&nbsp;     PerlIOBase\_popped\,
&nbsp;     NULL\,
&nbsp;     PerlIOBase\_binmode\,         /\* binmode\(\) is handled by :crlf \*/
&nbsp;     NULL\,                       /\* no getarg needed \*/
&nbsp;     PerlIOBase\_fileno\,
&nbsp;     NULL\,
&nbsp;     NULL\,
&nbsp;     NULL\,
&nbsp;     NULL\,
&nbsp;     PerlIOFoo\_seek\,
&nbsp;     NULL\,
&nbsp;     PerlIOBase\_noop\_ok\,         /\* close \*/
&nbsp;     NULL\,
&nbsp;     PerlIOBase\_noop\_fail\,       /\* fill \*/
&nbsp;     PerlIOBase\_eof\,
&nbsp;     PerlIOBase\_error\,
&nbsp;     PerlIOBase\_clearerr\,
&nbsp;     PerlIOBase\_setlinebuf\,
&nbsp;     NULL\,                       /\* get\_base \*/
&nbsp;     NULL\,                       /\* get\_bufsiz \*/
&nbsp;     NULL\,                       /\* get\_ptr \*/
&nbsp;     NULL\,                       /\* get\_cnt \*/
&nbsp;     NULL\,                       /\* set\_ptrcnt \*/
\};

END

&nbsp;     Inline\->init;

\}

my $tmp = "/tmp/perliobug";

open my $out\, ">"\,    $tmp or die "Can't open $tmp&#8203;: $\!";
print $out "x" x 20;
close $out;

open my $in\, "\<&#8203;:Foo"\, $tmp or die "Can't open $tmp&#8203;: $\!";
my\_bp\(\);
seek $in\, 1\, 0;
seek $in\, 0\, 1;
seek $in\, 2\, 2;
close $in;

unlink $tmp;

\-\-\-\-\-\-\-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

Here is a debug script

\-\-\-\-\-\-\-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-


\# NOTE&#8203;: Adjust the path to the perl executable
file /usr/bin/perl\-5\.8\.0

tb main
\# NOTE&#8203;: adjust the name of the script that you run
run perliobug\.pl

\# when Perl\_runops\_debug breakpoint is hit Inline will already load
\# the autogenerated \.so\, so we can set the bp in it \(that's only if
\# you have run 'Inline\->init' inside the BEGIN \{\} block

b S\_run\_body
continue
b Perl\_runops\_debug
continue

\# here you set your breakpoints
b my\_bp
b Perl\_PerlIO\_seek
b PerlIOFoo\_seek
continue
continue
continue

\-\-\-\-\-\-\-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

Summary of my perl5 \(revision 5\.0 version 8 subversion 0\) configuration&#8203;:
&nbsp;   Platform&#8203;:
&nbsp;     osname=linux\, osvers=2\.4\.18\-6mdksmp\, archname=i686\-linux
&nbsp;     uname='linux hope\.stason\.org 2\.4\.18\-6mdksmp \#1 smp fri mar 15 01&#8203;:24&#8203;:36 
cet 2002 i686 unknown '
&nbsp;     config\_args='\-des \-Dprefix=/home/stas/perl/5\.8\.0 \-Doptimize=\-g 
\-Duseshrplib \-Dusedevel'
&nbsp;     hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;     usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
&nbsp;     useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;     use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;     usemymalloc=n\, bincompat5005=undef
&nbsp;   Compiler&#8203;:
&nbsp;     cc='cc'\, ccflags ='\-DDEBUGGING \-fno\-strict\-aliasing \-D\_LARGEFILE\_SOURCE 
\-D\_FILE\_OFFSET\_BITS=64 \-I/usr/include/gdbm'\,
&nbsp;     optimize='\-g'\,
&nbsp;     cppflags='\-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/include/gdbm'
&nbsp;     ccversion=''\, gccversion='3\.2 \(Mandrake Linux 9\.1 3\.2\-4mdk\)'\, gccosandvers=''
&nbsp;     intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;     ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, 
lseeksize=8
&nbsp;     alignbytes=4\, prototype=define
&nbsp;   Linker and Libraries&#8203;:
&nbsp;     ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;     libpth=/usr/local/lib /lib /usr/lib
&nbsp;     libs=\-lnsl \-lgdbm \-ldb \-ldl \-lm \-lc \-lcrypt \-lutil
&nbsp;     perllibs=\-lnsl \-ldl \-lm \-lc \-lcrypt \-lutil
&nbsp;     libc=/lib/libc\-2\.2\.5\.so\, so=so\, useshrplib=true\, libperl=libperl\.so
&nbsp;     gnulibc\_version='2\.2\.5'
&nbsp;   Dynamic Linking&#8203;:
&nbsp;     dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic 
\-Wl\,\-rpath\,/home/stas/perl/5\.8\.0/lib/5\.8\.0/i686\-linux/CORE'
&nbsp;     cccdlflags='\-fpic'\, lddlflags='\-shared \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;   Compile\-time options&#8203;: DEBUGGING USE\_LARGE\_FILES
&nbsp;   Built under linux
&nbsp;   Compiled at Nov 26 2002 17&#8203;:32&#8203;:54
&nbsp;   @&#8203;INC&#8203;:
&nbsp;     /home/stas/perl/5\.8\.0/lib/5\.8\.0/i686\-linux
&nbsp;     /home/stas/perl/5\.8\.0/lib/5\.8\.0
&nbsp;     /home/stas/perl/5\.8\.0/lib/site\_perl/5\.8\.0/i686\-linux
&nbsp;     /home/stas/perl/5\.8\.0/lib/site\_perl/5\.8\.0
&nbsp;     /home/stas/perl/5\.8\.0/lib/site\_perl
&nbsp;     \.



\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
Stas Bekman            JAm\_pH \-\-\-\-\-\-> Just Another mod\_perl Hacker
http&#8203;://stason\.org/     mod\_perl Guide \-\-\-> http&#8203;://perl\.apache\.org
mailto&#8203;:stas@&#8203;stason\.org http&#8203;://use\.perl\.org http&#8203;://apacheweek\.com
http&#8203;://modperlbook\.org http&#8203;://apache\.org   http&#8203;://ticketmaster\.com

**Comment by p5pRT** [comment]
### From nick@ing-simmons.net

Stas Bekman \<perl5\-porters@&#8203;perl\.org> writes&#8203;:
>
>Something strange happens with APR&#8203;::PerlIO perlio layer running with
>perl\-5\.8\.0 w/o threads\. it works fine w/ threads\. I can reproduce a
>similar problem with a standalone script \(using Inline for
>convenience\) and you should be able to reproduce it as well\. More over
>this time the problem inhibits itself w/ and w/o thread\-enabled
>perl\-5\.8\.0\.
>
>
>static IV PerlIOFoo\_seek\(pTHX\_ PerlIO \*f\, Off\_t offset\, int whence\)
&nbsp;                                           ^^^^^
>\{
>     int check = whence;
>
>     Perl\_warn\(aTHX\_ "in seek&#8203;: offset=%d\, whence=%d\, check=%d\\n"\,
&nbsp;                                       ^^
>               offset\, whence\, check\);
>
>     return 0;
>\}

I suspect Seek arguments are fine \- problem is your format is expecting 
a %d \- int 32\-bits but is passing an Off\_t which is most likely 64\-bits\.

My guess is that threads works by accident as extra "my\_perl" 
caused by aTHX\_ causes stack alignment to give right values by accident\.

\-\- 
Nick Ing\-Simmons
http&#8203;://www\.ni\-s\.u\-net\.com/

**Comment by p5pRT** [comment]
### From stas@stason.org

Nick Ing\-Simmons wrote&#8203;:
> Stas Bekman \<perl5\-porters@&#8203;perl\.org> writes&#8203;:
> 
>>Something strange happens with APR&#8203;::PerlIO perlio layer running with
>>perl\-5\.8\.0 w/o threads\. it works fine w/ threads\. I can reproduce a
>>similar problem with a standalone script \(using Inline for
>>convenience\) and you should be able to reproduce it as well\. More over
>>this time the problem inhibits itself w/ and w/o thread\-enabled
>>perl\-5\.8\.0\.
>>
>>
>>static IV PerlIOFoo\_seek\(pTHX\_ PerlIO \*f\, Off\_t offset\, int whence\)
> 
>                                            ^^^^^
> 
>>\{
>>    int check = whence;
>>
>>    Perl\_warn\(aTHX\_ "in seek&#8203;: offset=%d\, whence=%d\, check=%d\\n"\,
> 
>                                        ^^
> 
>>              offset\, whence\, check\);
>>
>>    return 0;
>>\}
> 
> 
> I suspect Seek arguments are fine \- problem is your format is expecting 
> a %d \- int 32\-bits but is passing an Off\_t which is most likely 64\-bits\.

Indeed\, removing %d/offset makes my test work \(I haven't thought of checking 
the offset var\)\. However this doesn't solve the original problem\. Here is the 
trace that shows that the problem is in perlio\. See how 'whence' gets 
nullified\, when a custom callback is called?

\#0  PerlIOAPR\_seek \(f=0x85b74e8\, offset=0\, whence=0\) at apr\_perlio\.c&#8203;:209
\#1  0x404350c8 in Perl\_PerlIO\_seek \(f=0x85b74e8\, offset=0\, whence=2\) at 
perlio\.c&#8203;:1537
\#2  0x40438664 in PerlIOPending\_seek \(f=0x85b74e8\, offset=0\, whence=2\) at 
perlio\.c&#8203;:3845
\#3  0x404350c8 in Perl\_PerlIO\_seek \(f=0x85b74e8\, offset=0\, whence=2\) at 
perlio\.c&#8203;:1537
\#4  0x404162c4 in Perl\_do\_seek \(gv=0x89063b0\, pos=0\, whence=2\) at doio\.c&#8203;:1088
\#5  0x40404160 in Perl\_pp\_sysseek \(\) at pp\_sys\.c&#8203;:2002
\#6  0x40403de4 in Perl\_pp\_seek \(\) at pp\_sys\.c&#8203;:1964
\#7  0x403a06b4 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1424

All this happens before my code gets a chance to run\.

> My guess is that threads works by accident as extra "my\_perl" 
> caused by aTHX\_ causes stack alignment to give right values by accident\.

Probably\, but I don't see any offset manipulations in PerlIOPending\_seek or 
Perl\_PerlIO\_seek which may trigger this problem\.


\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
Stas Bekman            JAm\_pH \-\-\-\-\-\-> Just Another mod\_perl Hacker
http&#8203;://stason\.org/     mod\_perl Guide \-\-\-> http&#8203;://perl\.apache\.org
mailto&#8203;:stas@&#8203;stason\.org http&#8203;://use\.perl\.org http&#8203;://apacheweek\.com
http&#8203;://modperlbook\.org http&#8203;://apache\.org   http&#8203;://ticketmaster\.com

**Comment by p5pRT** [comment]
### From nick.ing-simmons@elixent.com

Stas Bekman \<stas@&#8203;stason\.org> writes&#8203;:
>Nick Ing\-Simmons wrote&#8203;:
>> Stas Bekman \<perl5\-porters@&#8203;perl\.org> writes&#8203;:
>> 
>>>Something strange happens with APR&#8203;::PerlIO perlio layer running with
>>>perl\-5\.8\.0 w/o threads\. it works fine w/ threads\. I can reproduce a
>>>similar problem with a standalone script \(using Inline for
>>>convenience\) and you should be able to reproduce it as well\. More over
>>>this time the problem inhibits itself w/ and w/o thread\-enabled
>>>perl\-5\.8\.0\.
>>>
>>>
>>>static IV PerlIOFoo\_seek\(pTHX\_ PerlIO \*f\, Off\_t offset\, int whence\)
>> 
>>                                            ^^^^^
>> 
>>>\{
>>>    int check = whence;
>>>
>>>    Perl\_warn\(aTHX\_ "in seek&#8203;: offset=%d\, whence=%d\, check=%d\\n"\,
>> 
>>                                        ^^
>> 
>>>              offset\, whence\, check\);
>>>
>>>    return 0;
>>>\}
>> 
>> 
>> I suspect Seek arguments are fine \- problem is your format is expecting 
>> a %d \- int 32\-bits but is passing an Off\_t which is most likely 64\-bits\.
>
>Indeed\, removing %d/offset makes my test work \(I haven't thought of checking 
>the offset var\)\. However this doesn't solve the original problem\. Here is the 
>trace that shows that the problem is in perlio\. See how 'whence' gets 
>nullified\, when a custom callback is called?
>
>\#0  PerlIOAPR\_seek \(f=0x85b74e8\, offset=0\, whence=0\) at apr\_perlio\.c&#8203;:209
>\#1  0x404350c8 in Perl\_PerlIO\_seek \(f=0x85b74e8\, offset=0\, whence=2\) at 
>perlio\.c&#8203;:1537
>\#2  0x40438664 in PerlIOPending\_seek \(f=0x85b74e8\, offset=0\, whence=2\) at 
>perlio\.c&#8203;:3845

I still think this is most\-likely caused by your \.c file and perl 
having different ideas about size of Off\_t argument\.
So debugger and you are seeing One of words of offset as whence\.


>\#3  0x404350c8 in Perl\_PerlIO\_seek \(f=0x85b74e8\, offset=0\, whence=2\) at 
>perlio\.c&#8203;:1537
>\#4  0x404162c4 in Perl\_do\_seek \(gv=0x89063b0\, pos=0\, whence=2\) at doio\.c&#8203;:1088
>\#5  0x40404160 in Perl\_pp\_sysseek \(\) at pp\_sys\.c&#8203;:2002
>\#6  0x40403de4 in Perl\_pp\_seek \(\) at pp\_sys\.c&#8203;:1964
>\#7  0x403a06b4 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1424
>
>All this happens before my code gets a chance to run\.
>
>> My guess is that threads works by accident as extra "my\_perl" 
>> caused by aTHX\_ causes stack alignment to give right values by accident\.
>
>Probably\, but I don't see any offset manipulations in PerlIOPending\_seek or 
>Perl\_PerlIO\_seek which may trigger this problem\.

If Off\_t is 64\-bit then compiler's operand alinement rules may come into play&#8203;:

&nbsp;    32\-bit F
&nbsp;    32\-bit Hole    ???
&nbsp;    64\-bit offset 
&nbsp;    32\-bit whence 
vs   
&nbsp;    32\-bit my\_perl
&nbsp;    32\-bit F
&nbsp;    64\-bit offset 
&nbsp;    32\-bit whence 


\-\- 
Nick Ing\-Simmons
http&#8203;://www\.ni\-s\.u\-net\.com/

**Comment by p5pRT** [comment]
### From stas@stason.org

Nick Ing\-Simmons wrote&#8203;:
> Stas Bekman \<stas@&#8203;stason\.org> writes&#8203;:
> 
>>Nick Ing\-Simmons wrote&#8203;:
>>
>>>Stas Bekman \<perl5\-porters@&#8203;perl\.org> writes&#8203;:
>>>
>>>
>>>>Something strange happens with APR&#8203;::PerlIO perlio layer running with
>>>>perl\-5\.8\.0 w/o threads\. it works fine w/ threads\. I can reproduce a
>>>>similar problem with a standalone script \(using Inline for
>>>>convenience\) and you should be able to reproduce it as well\. More over
>>>>this time the problem inhibits itself w/ and w/o thread\-enabled
>>>>perl\-5\.8\.0\.
>>>>
>>>>
>>>>static IV PerlIOFoo\_seek\(pTHX\_ PerlIO \*f\, Off\_t offset\, int whence\)
>>>
>>>                                           ^^^^^
>>>
>>>
>>>>\{
>>>>   int check = whence;
>>>>
>>>>   Perl\_warn\(aTHX\_ "in seek&#8203;: offset=%d\, whence=%d\, check=%d\\n"\,
>>>
>>>                                       ^^
>>>
>>>
>>>>             offset\, whence\, check\);
>>>>
>>>>   return 0;
>>>>\}
>>>
>>>
>>>I suspect Seek arguments are fine \- problem is your format is expecting 
>>>a %d \- int 32\-bits but is passing an Off\_t which is most likely 64\-bits\.
>>
>>Indeed\, removing %d/offset makes my test work \(I haven't thought of checking 
>>the offset var\)\. However this doesn't solve the original problem\. Here is the 
>>trace that shows that the problem is in perlio\. See how 'whence' gets 
>>nullified\, when a custom callback is called?
>>
>>\#0  PerlIOAPR\_seek \(f=0x85b74e8\, offset=0\, whence=0\) at apr\_perlio\.c&#8203;:209
>>\#1  0x404350c8 in Perl\_PerlIO\_seek \(f=0x85b74e8\, offset=0\, whence=2\) at 
>>perlio\.c&#8203;:1537
>>\#2  0x40438664 in PerlIOPending\_seek \(f=0x85b74e8\, offset=0\, whence=2\) at 
>>perlio\.c&#8203;:3845
> 
> 
> I still think this is most\-likely caused by your \.c file and perl 
> having different ideas about size of Off\_t argument\.
> So debugger and you are seeing One of words of offset as whence\.

I've checked that and tried to use the perl's definition as you can see below\.

>>\#3  0x404350c8 in Perl\_PerlIO\_seek \(f=0x85b74e8\, offset=0\, whence=2\) at 
>>perlio\.c&#8203;:1537
>>\#4  0x404162c4 in Perl\_do\_seek \(gv=0x89063b0\, pos=0\, whence=2\) at doio\.c&#8203;:1088
>>\#5  0x40404160 in Perl\_pp\_sysseek \(\) at pp\_sys\.c&#8203;:2002
>>\#6  0x40403de4 in Perl\_pp\_seek \(\) at pp\_sys\.c&#8203;:1964
>>\#7  0x403a06b4 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1424
>>
>>All this happens before my code gets a chance to run\.
>>
>>
>>>My guess is that threads works by accident as extra "my\_perl" 
>>>caused by aTHX\_ causes stack alignment to give right values by accident\.
>>
>>Probably\, but I don't see any offset manipulations in PerlIOPending\_seek or 
>>Perl\_PerlIO\_seek which may trigger this problem\.
> 
> 
> If Off\_t is 64\-bit then compiler's operand alinement rules may come into play&#8203;:
> 
>     32\-bit F
>     32\-bit Hole    ???
>     64\-bit offset 
>     32\-bit whence 
> vs   
>     32\-bit my\_perl
>     32\-bit F
>     64\-bit offset 
>     32\-bit whence 

I understand that\. but I fail to find what could be the problem with my code&#8203;:

% perl5\.8\.0 \-V | grep Off\_t
&nbsp;     ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, 
lseeksize=8

so perl sees&#8203;: Off\_t='off\_t'\,

I've expanded Off\_t and it shows&#8203;:

typedef long int \_\_off\_t;
typedef \_\_off\_t off\_t;

so even if I change the API to be the same as perl's Off\_t&#8203;:

static IV PerlIOAPR\_seek\(pTHX\_ PerlIO \*f\, long int offset\, int whence\)
\{
&nbsp;     Perl\_warn\(aTHX\_ "in seek&#8203;: whence=%d\\n"\, whence\);
&nbsp;     return 0;
\}

instead of&#8203;:
static IV PerlIOAPR\_seek\(pTHX\_ PerlIO \*f\, Off\_t offset\, int whence\)

I still get 'whence' nullified\.

The file in question is here&#8203;:
http&#8203;://cvs\.apache\.org/viewcvs\.cgi/modperl\-2\.0/xs/APR/PerlIO/apr\_perlio\.c

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
Stas Bekman            JAm\_pH \-\-\-\-\-\-> Just Another mod\_perl Hacker
http&#8203;://stason\.org/     mod\_perl Guide \-\-\-> http&#8203;://perl\.apache\.org
mailto&#8203;:stas@&#8203;stason\.org http&#8203;://use\.perl\.org http&#8203;://apacheweek\.com
http&#8203;://modperlbook\.org http&#8203;://apache\.org   http&#8203;://ticketmaster\.com

**Comment by p5pRT** [comment]
### From nick@ing-simmons.net

Stas Bekman \<stas@&#8203;stason\.org> writes&#8203;:
>
>% perl5\.8\.0 \-V | grep Off\_t
>     ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, 
>lseeksize=8
>
>so perl sees&#8203;: Off\_t='off\_t'\,
>
>I've expanded Off\_t and it shows&#8203;:
>
>typedef long int \_\_off\_t;
>typedef \_\_off\_t off\_t;

I thought "lseeksize" was supposed to be size of off\_t?
Do perl compiles pass any command line \-D flags to C compiler 
that might change expansion of of off\_t ?

\-\- 
Nick Ing\-Simmons
http&#8203;://www\.ni\-s\.u\-net\.com/

**Comment by p5pRT** [comment]
### From stas@stason.org

\[CC'ing modperl dev list\, so we have this issue archived\]

Nick Ing\-Simmons wrote&#8203;:
> Stas Bekman \<stas@&#8203;stason\.org> writes&#8203;:
> 
>>% perl5\.8\.0 \-V | grep Off\_t
>>    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, 
>>lseeksize=8
>>
>>so perl sees&#8203;: Off\_t='off\_t'\,
>>
>>I've expanded Off\_t and it shows&#8203;:
>>
>>typedef long int \_\_off\_t;
>>typedef \_\_off\_t off\_t;
> 
> 
> I thought "lseeksize" was supposed to be size of off\_t?
> Do perl compiles pass any command line \-D flags to C compiler 
> that might change expansion of of off\_t ?

Thanks Nick\.

After confirming that using an explicit 'long long int offset' solves the 
problem \(for the given setup\)&#8203;:

static IV PerlIOAPR\_seek\(pTHX\_ PerlIO \*f\, long long int offset\, int whence\)

I went to figure out where the difference comes from\. And then I've found that 
mod\_perl rips off the flags '\-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64' when 
building mod\_perl objects\, since Apache 2\.0 \(to be exact libapr\) always builds 
without largefiles support \(at least on linux\)\. The two are binary 
incompatible\. Sigh :\(

Looks like it happens to work for me\, if I build only apr\_perlio\.c with 
'\-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\, since that's the only place 
where we use Off\_t\. I don't know whether it'll work on other platforms\.

Currently\, if you want to use APR&#8203;::PerlIO's seek function\, with offset 
different from 0\, you have to rebuild perl without uselargefiles\, which is far 
from being an acceptable solution\.

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
Stas Bekman            JAm\_pH \-\-\-\-\-\-> Just Another mod\_perl Hacker
http&#8203;://stason\.org/     mod\_perl Guide \-\-\-> http&#8203;://perl\.apache\.org
mailto&#8203;:stas@&#8203;stason\.org http&#8203;://use\.perl\.org http&#8203;://apacheweek\.com
http&#8203;://modperlbook\.org http&#8203;://apache\.org   http&#8203;://ticketmaster\.com

**Comment by p5pRT** [comment]
### From nick.ing-simmons@elixent.com

Stas Bekman \<stas@&#8203;stason\.org> writes&#8203;:
>
>Thanks Nick\.
>
>After confirming that using an explicit 'long long int offset' solves the 
>problem \(for the given setup\)&#8203;:
>
>static IV PerlIOAPR\_seek\(pTHX\_ PerlIO \*f\, long long int offset\, int whence\)
>
>I went to figure out where the difference comes from\. And then I've found that 
>mod\_perl rips off the flags '\-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64' when 
>building mod\_perl objects\, since Apache 2\.0 \(to be exact libapr\) always builds 
>without largefiles support \(at least on linux\)\. The two are binary 
>incompatible\. Sigh :\(
>
>Looks like it happens to work for me\, if I build only apr\_perlio\.c with 
>'\-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\, since that's the only place 
>where we use Off\_t\. I don't know whether it'll work on other platforms\.
>
>Currently\, if you want to use APR&#8203;::PerlIO's seek function\, with offset 
>different from 0\, you have to rebuild perl without uselargefiles\, which is far 
>from being an acceptable solution\.

Does this make the ticket "resolved" \- as far as perl is concerned?


>
\-\- 
Nick Ing\-Simmons
http&#8203;://www\.ni\-s\.u\-net\.com/

**Comment by p5pRT** [comment]
### From nick@ing-simmons.net

>>Looks like it happens to work for me\, if I build only apr\_perlio\.c with 
>>'\-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\, since that's the only place 
>>where we use Off\_t\. I don't know whether it'll work on other platforms\.
>>
>>Currently\, if you want to use APR&#8203;::PerlIO's seek function\, with offset 
>>different from 0\, you have to rebuild perl without uselargefiles\,
which is far 
> 
>>from being an acceptable solution\.
> 
> Does this make the ticket "resolved" \- as far as perl is concerned?

Yes\, please\! Thank you\, Nick\, for the help to nail the problem down\.

**Comment by p5pRT** [comment]
nick@ing-simmons.net - Status changed from 'new' to 'resolved'
