### ISSUE TITLE
Mac OS X dyld undefined symbols during 5.8.x upgrade

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6501]
Migrated from [rt.perl.org#22170](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=22170) (status was 'resolved')

Searchable as RT22170$

**Comment by p5pRT** [comment]
### From mmtaylormd@mac.com

Open Letter to Perl\.org and Aaron Faby\,

Perl\.org's source code and your package distribution of the perl 5\.8\.0 
package may cause problems with Mac OS X applications such as command 
line CPAN\, Fink\, among others\.

I discovered the problem by trying to update perl 5\.6\.0 to 5\.8\.0\. Like 
so many others\, I first tried Apple's instructions on installing 
perl\-5\.8\.0\. Then I tried Aaron Faby's package installer\. Both gave the 
same problem\. I kept getting errors in various dyld&#8203;: perl Undefined 
symbols\.

After many hours of frustration and web searching I think I have 
eliminated the problem\. It seems the build either has an older version 
of Storable\.pm or the standard Mac OS X perl5\.6\.0 it isn't overwritten 
using the latest Storable\.pm \(hidden in the darwin and perl5 folders\)\.

This has been reported before&#8203;:
http&#8203;://search\.cpan\.org/author/JHI/perl\-5\.8\.0/pod/perldelta\.pod\#Mac\_OS\_X\,
http&#8203;://bluedot\.net/mail/archive/read\.php?f=6&i=5559&t=5557\,
http&#8203;://archive\.develooper\.com/macosx@&#8203;perl\.org/msg05559\.html\,
http&#8203;://archive\.develooper\.com/macosx@&#8203;perl\.org/msg05541\.html\.

The solution for me was to \(having tried the way on the above page and 
failed\) load a fresh OS X install \(with perl\-5\.6\.0\) on one drive and 
and second fresh OS X install on a second drive \(using your 
distribution of perl\-5\.8\.0\)\. I installed Fink on the first drive and 
installed the latest version of Storable\.pm\-2\.07\. I used Path Finder 
from www\.cocoatech\.com to track down the older Storable\.pm perl modules&#8203;:

file&#8203;://localhost/System/Library/Perl/darwin/Storable\.pm
file&#8203;://localhost/System/Library/Perl/darwin/auto/Storable/
file&#8203;://localhost/System/Library/Perl/Memoize/Storable\.pm

and substitute the updated versions on the second drive\. Everything 
works beautifully\. No more dyld&#8203;: perl Undefined symbols\!

I included the perl crash log for reference\.

\*\*\*\*\*\*\*\*\*\* \*\*\*\*\*\*\*\*\*\* \*\*\*\*\*\*\*\*\*\*
Perl version 5\.8\.0
Date/Time&#8203;:  2003\-05\-10 09&#8203;:40&#8203;:00 \-0400
OS Version&#8203;: 10\.2\.6 \(Build 6L60\)

Command&#8203;:    perl
PID&#8203;:        11760

Exception&#8203;:  EXC\_BREAKPOINT \(0x0006\)
Code\[0\]&#8203;:    0x00000001Code\[1\]&#8203;:    0x8fe01280

Thread 0 Crashed&#8203;:
&nbsp;  \#0   0x8fe01280 in halt
&nbsp;  \#1   0x8fe106b4 in link\_in\_need\_modules
&nbsp;  \#2   0x8fe12230 in \_dyld\_link\_module
&nbsp;  \#3   0x90016ac8 in NSLinkModule
&nbsp;  \#4   0x00001c7c in XS\_DynaLoader\_dl\_load\_file
&nbsp;  \#5   0x00180060 in Perl\_pp\_entersub
&nbsp;  \#6   0x001796f8 in Perl\_runops\_standard
&nbsp;  \#7   0x0011c564 in S\_run\_body
&nbsp;  \#8   0x0011c158 in perl\_run
&nbsp;  \#9   0x00001a9c in main
&nbsp;  \#10  0x0000178c in \_start \(crt\.c&#8203;:267\)
&nbsp;  \#11  0x0000160c in start

PPC Thread State&#8203;:
&nbsp;   srr0&#8203;: 0x8fe01280 srr1&#8203;: 0x0002d030                vrsave&#8203;: 0x00000000
&nbsp;    xer&#8203;: 0x20000000   lr&#8203;: 0x8fe09c38  ctr&#8203;: 0x8fe29468   mq&#8203;: 0x00000000
&nbsp;     r0&#8203;: 0x00000004   r1&#8203;: 0xbffff320   r2&#8203;: 0x8fe0b7f4   r3&#8203;: 0x00000086
&nbsp;     r4&#8203;: 0x00000000   r5&#8203;: 0x00000086   r6&#8203;: 0x0000000a   r7&#8203;: 0x6c5f6765
&nbsp;     r8&#8203;: 0x7376005f   r9&#8203;: 0x00000000  r10&#8203;: 0x8fe4850c  r11&#8203;: 0x0000000c
&nbsp;    r12&#8203;: 0x8fe71aad  r13&#8203;: 0x002a0af0  r14&#8203;: 0x00209adc  r15&#8203;: 0x0020fb1c
&nbsp;    r16&#8203;: 0x0020c0b4  r17&#8203;: 0x0020c0b4  r18&#8203;: 0x00000046  r19&#8203;: 0x003dd7e0
&nbsp;    r20&#8203;: 0x0020fb1c  r21&#8203;: 0x00209984  r22&#8203;: 0x00000001  r23&#8203;: 0x00000000
&nbsp;    r24&#8203;: 0x0020fb1c  r25&#8203;: 0x00001af0  r26&#8203;: 0x00001af0  r27&#8203;: 0x0001d4cc
&nbsp;    r28&#8203;: 0x8fe4841c  r29&#8203;: 0x8fe484ec  r30&#8203;: 0x8fe484ec  r31&#8203;: 0x8fe099bc

\*\*\*\*\*\*\*\*\*\* \*\*\*\*\*\*\*\*\*\* \*\*\*\*\*\*\*\*\*\*

Sincerely\,

Michael M\. Taylor\, M\.D\.
Hope this helps someone\!

**Comment by p5pRT** [comment]
### From mmtaylormd@mac.com

Open Letter to Perl\.org and Aaron Faby\,


Perl\.org's source code and your package distribution of the perl 5\.8\.0
package may cause problems with Mac OS X applications such as command
line CPAN\, Fink\, among others\.


I discovered the problem by trying to update perl 5\.6\.0 to 5\.8\.0\. Like
so many others\, I first tried Apple's instructions on installing
perl\-5\.8\.0\. Then I tried Aaron Faby's package installer\. Both gave the
same problem\. I kept getting errors in various \<bold>dyld&#8203;: perl
Undefined symbols\</bold>\. 


After many hours of frustration and web searching I think I have
eliminated the problem\. It seems the build either has an older version
of \<color>\<param>08ED\,083F\,FFFF\</param>Storable\.pm\</color> or the
standard Mac OS X perl5\.6\.0 it \<italic>isn't overwritten\</italic>
using the latest
\<color>\<param>07BE\,0DCD\,FFFF\</param>Storable\.pm\</color> \(hidden in the
darwin and perl5 folders\)\.


This has been reported before&#8203;: 

\<bold>\<underline>\<color>\<param>FFFF\,17BA\,059A\</param>http&#8203;://search\.cpan\.org/author/JHI/perl\-5\.8\.0/pod/perldelta\.pod\#Mac\_OS\_X\</color>\</underline>\</bold>\<color>\<param>07BE\,0DCD\,FFFF\</param>\,

\<underline>http&#8203;://bluedot\.net/mail/archive/read\.php?f=6&i=5559&t=5557\</underline>\,

\<underline>http&#8203;://archive\.develooper\.com/macosx@&#8203;perl\.org/msg05559\.html\</underline>\,

\<underline>http&#8203;://archive\.develooper\.com/macosx@&#8203;perl\.org/msg05541\.html\</underline>\.\</color>\<color>\<param>0000\,0000\,0000\</param>


The solution for me was to \(having tried the way on the above page and
failed\) load a fresh OS X install \(with perl\-5\.6\.0\) on one drive and
and second fresh OS X install on a second drive \(using your
distribution of perl\-5\.8\.0\)\. I installed Fink on the first drive and
installed the latest version of Storable\.pm\-2\.07\. I used Path Finder
from
\</color>\<underline>\<fontfamily>\<param>Times\</param>\<color>\<param>1A1A\,1A1A\,FFFF\</param>www\.cocoatech\.com\</color>\</fontfamily>\</underline>\<color>\<param>0000\,0000\,0000\</param>
to track down the older Storable\.pm perl modules&#8203;:


file&#8203;://localhost/System/Library/Perl/darwin/Storable\.pm 

file&#8203;://localhost/System/Library/Perl/darwin/auto/Storable/

file&#8203;://localhost/System/Library/Perl/Memoize/Storable\.pm


and substitute the updated versions on the second drive\. Everything
works beautifully\. \<italic>No more \</italic>\</color>\<italic>dyld&#8203;: perl
Undefined symbols\!\</italic>


I included the perl crash log for reference\.


\*\*\*\*\*\*\*\*\*\* \*\*\*\*\*\*\*\*\*\* \*\*\*\*\*\*\*\*\*\*

Perl version 5\.8\.0

Date/Time&#8203;:  2003\-05\-10 09&#8203;:40&#8203;:00 \-0400

OS Version&#8203;: 10\.2\.6 \(Build 6L60\)


Command&#8203;:    perl

PID&#8203;:        11760


Exception&#8203;:  EXC\_BREAKPOINT \(0x0006\)

Code\[0\]&#8203;:    0x00000001Code\[1\]&#8203;:    0x8fe01280


Thread 0 Crashed&#8203;:

 \#0   0x8fe01280 in halt

 \#1   0x8fe106b4 in link\_in\_need\_modules

 \#2   0x8fe12230 in \_dyld\_link\_module

 \#3   0x90016ac8 in NSLinkModule

 \#4   0x00001c7c in XS\_DynaLoader\_dl\_load\_file

 \#5   0x00180060 in Perl\_pp\_entersub

 \#6   0x001796f8 in Perl\_runops\_standard

 \#7   0x0011c564 in S\_run\_body

 \#8   0x0011c158 in perl\_run

 \#9   0x00001a9c in main

 \#10  0x0000178c in \_start \(crt\.c&#8203;:267\)

 \#11  0x0000160c in start


PPC Thread State&#8203;:

&nbsp;  srr0&#8203;: 0x8fe01280 srr1&#8203;: 0x0002d030                vrsave&#8203;: 0x00000000

&nbsp;   xer&#8203;: 0x20000000   lr&#8203;: 0x8fe09c38  ctr&#8203;: 0x8fe29468   mq&#8203;: 0x00000000

&nbsp;    r0&#8203;: 0x00000004   r1&#8203;: 0xbffff320   r2&#8203;: 0x8fe0b7f4   r3&#8203;: 0x00000086

&nbsp;    r4&#8203;: 0x00000000   r5&#8203;: 0x00000086   r6&#8203;: 0x0000000a   r7&#8203;: 0x6c5f6765

&nbsp;    r8&#8203;: 0x7376005f   r9&#8203;: 0x00000000  r10&#8203;: 0x8fe4850c  r11&#8203;: 0x0000000c

&nbsp;   r12&#8203;: 0x8fe71aad  r13&#8203;: 0x002a0af0  r14&#8203;: 0x00209adc  r15&#8203;: 0x0020fb1c

&nbsp;   r16&#8203;: 0x0020c0b4  r17&#8203;: 0x0020c0b4  r18&#8203;: 0x00000046  r19&#8203;: 0x003dd7e0

&nbsp;   r20&#8203;: 0x0020fb1c  r21&#8203;: 0x00209984  r22&#8203;: 0x00000001  r23&#8203;: 0x00000000

&nbsp;   r24&#8203;: 0x0020fb1c  r25&#8203;: 0x00001af0  r26&#8203;: 0x00001af0  r27&#8203;: 0x0001d4cc

&nbsp;   r28&#8203;: 0x8fe4841c  r29&#8203;: 0x8fe484ec  r30&#8203;: 0x8fe484ec  r31&#8203;: 0x8fe099bc


\*\*\*\*\*\*\*\*\*\* \*\*\*\*\*\*\*\*\*\* \*\*\*\*\*\*\*\*\*\*


Sincerely\,


Michael M\. Taylor\, M\.D\.

Hope this helps someone\!

**Comment by p5pRT** [comment]
### From @smpeters

> \[mmtaylormd@&#8203;mac\.com \- Sat May 10 10&#8203;:50&#8203;:47 2003\]&#8203;:
> 
> Open Letter to Perl\.org and Aaron Faby\,
> 
> Perl\.org's source code and your package distribution of the perl 5\.8\.0 
> package may cause problems with Mac OS X applications such as command 
> line CPAN\, Fink\, among others\.
> 
> I discovered the problem by trying to update perl 5\.6\.0 to 5\.8\.0\. Like 
> so many others\, I first tried Apple's instructions on installing 
> perl\-5\.8\.0\. Then I tried Aaron Faby's package installer\. Both gave the 
> same problem\. I kept getting errors in various dyld&#8203;: perl Undefined 
> symbols\.
> 
> After many hours of frustration and web searching I think I have 
> eliminated the problem\. It seems the build either has an older version 
> of Storable\.pm or the standard Mac OS X perl5\.6\.0 it isn't overwritten 
> using the latest Storable\.pm \(hidden in the darwin and perl5 folders\)\.
> 
> This has been reported before&#8203;:
> http&#8203;://search\.cpan\.org/author/JHI/perl\-5\.8\.0/pod/perldelta\.pod\#Mac\_OS\_X\,
> http&#8203;://bluedot\.net/mail/archive/read\.php?f=6&i=5559&t=5557\,
> http&#8203;://archive\.develooper\.com/macosx@&#8203;perl\.org/msg05559\.html\,
> http&#8203;://archive\.develooper\.com/macosx@&#8203;perl\.org/msg05541\.html\.
> 
> The solution for me was to \(having tried the way on the above page and 
> failed\) load a fresh OS X install \(with perl\-5\.6\.0\) on one drive and 
> and second fresh OS X install on a second drive \(using your 
> distribution of perl\-5\.8\.0\)\. I installed Fink on the first drive and 
> installed the latest version of Storable\.pm\-2\.07\. I used Path Finder 
> from www\.cocoatech\.com to track down the older Storable\.pm perl modules&#8203;:
> 
> file&#8203;://localhost/System/Library/Perl/darwin/Storable\.pm
> file&#8203;://localhost/System/Library/Perl/darwin/auto/Storable/
> file&#8203;://localhost/System/Library/Perl/Memoize/Storable\.pm
> 
> and substitute the updated versions on the second drive\. Everything 
> works beautifully\. No more dyld&#8203;: perl Undefined symbols\!
> 
> I included the perl crash log for reference\.
> 
> \*\*\*\*\*\*\*\*\*\* \*\*\*\*\*\*\*\*\*\* \*\*\*\*\*\*\*\*\*\*
> Perl version 5\.8\.0
> Date/Time&#8203;:  2003\-05\-10 09&#8203;:40&#8203;:00 \-0400
> OS Version&#8203;: 10\.2\.6 \(Build 6L60\)
> 
> Command&#8203;:    perl
> PID&#8203;:        11760
> 
> Exception&#8203;:  EXC\_BREAKPOINT \(0x0006\)
> Code\[0\]&#8203;:    0x00000001Code\[1\]&#8203;:    0x8fe01280
> 
> Thread 0 Crashed&#8203;:
>   \#0   0x8fe01280 in halt
>   \#1   0x8fe106b4 in link\_in\_need\_modules
>   \#2   0x8fe12230 in \_dyld\_link\_module
>   \#3   0x90016ac8 in NSLinkModule
>   \#4   0x00001c7c in XS\_DynaLoader\_dl\_load\_file
>   \#5   0x00180060 in Perl\_pp\_entersub
>   \#6   0x001796f8 in Perl\_runops\_standard
>   \#7   0x0011c564 in S\_run\_body
>   \#8   0x0011c158 in perl\_run
>   \#9   0x00001a9c in main
>   \#10  0x0000178c in \_start \(crt\.c&#8203;:267\)
>   \#11  0x0000160c in start
> 
> PPC Thread State&#8203;:
>    srr0&#8203;: 0x8fe01280 srr1&#8203;: 0x0002d030                vrsave&#8203;: 0x00000000
>     xer&#8203;: 0x20000000   lr&#8203;: 0x8fe09c38  ctr&#8203;: 0x8fe29468   mq&#8203;: 0x00000000
>      r0&#8203;: 0x00000004   r1&#8203;: 0xbffff320   r2&#8203;: 0x8fe0b7f4   r3&#8203;: 0x00000086
>      r4&#8203;: 0x00000000   r5&#8203;: 0x00000086   r6&#8203;: 0x0000000a   r7&#8203;: 0x6c5f6765
>      r8&#8203;: 0x7376005f   r9&#8203;: 0x00000000  r10&#8203;: 0x8fe4850c  r11&#8203;: 0x0000000c
>     r12&#8203;: 0x8fe71aad  r13&#8203;: 0x002a0af0  r14&#8203;: 0x00209adc  r15&#8203;: 0x0020fb1c
>     r16&#8203;: 0x0020c0b4  r17&#8203;: 0x0020c0b4  r18&#8203;: 0x00000046  r19&#8203;: 0x003dd7e0
>     r20&#8203;: 0x0020fb1c  r21&#8203;: 0x00209984  r22&#8203;: 0x00000001  r23&#8203;: 0x00000000
>     r24&#8203;: 0x0020fb1c  r25&#8203;: 0x00001af0  r26&#8203;: 0x00001af0  r27&#8203;: 0x0001d4cc
>     r28&#8203;: 0x8fe4841c  r29&#8203;: 0x8fe484ec  r30&#8203;: 0x8fe484ec  r31&#8203;: 0x8fe099bc
> 
> \*\*\*\*\*\*\*\*\*\* \*\*\*\*\*\*\*\*\*\* \*\*\*\*\*\*\*\*\*\*
> 
> Sincerely\,
> 
> Michael M\. Taylor\, M\.D\.
> Hope this helps someone\!
> 
> 
> 
As noted in
http&#8203;://search\.cpan\.org/author/JHI/perl\-5\.8\.0/pod/perldelta\.pod\#Mac\_OS\_X\,
the errors are not Perl's fault\, but Apple's\.

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'new' to 'resolved'
