### ISSUE TITLE
segfault with nested eval

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6576]
Migrated from [rt.perl.org#22743](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=22743) (status was 'resolved')

Searchable as RT22743$

**Comment by p5pRT** [comment]
### From frederik@ugcs.caltech.edu

#### Created by frederik@ugcs.caltech.edu



Segmentation fault on 5\.6\.1 i386 \(several distributions\)\, 5\.8\.0 ppc
\(debian\) and i386 \(several\)\, and blead alpha\-openbsd\.

Failed to reproduce on 5\.6\.0 i386 \(custom\)\.

Contents of 'bug'&#8203;:
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
\#\!/usr/bin/perl
use strict;
use warnings;
my $T; our $x; my $q;
sub foo \{
&nbsp;  my \($f\, $ev\) = @&#8203;\_;
&nbsp;  $ev ||= sub \{ eval\(shift\) \};
&nbsp;  local $x;
&nbsp;  my $res = &$ev\($f\.'return sub \{ eval\(shift\); \};'\);
&nbsp;  return $res;
\}
my $a = '$q = sub \{$T\};';
my $b = '$T=2;';
foo\($a\, undef\);
foo\($a\, foo\($b\, undef\)\);
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

% \./bug
Segmentation fault

In gdb \.\.\.
Program received signal SIGSEGV\, Segmentation fault\.
\[Switching to Thread 16384 \(LWP 8358\)\]
0x0ff0ed00 in Perl\_pad\_allocmy \(\) from /usr/lib/libperl\.so\.5\.8
\(gdb\) bt
\#0  0x0ff0ed00 in Perl\_pad\_allocmy \(\) from /usr/lib/libperl\.so\.5\.8
\#1  0x0ff0ed0c in Perl\_pad\_allocmy \(\) from /usr/lib/libperl\.so\.5\.8
\#2  0x0ff011f4 in Perl\_yylex \(\) from /usr/lib/libperl\.so\.5\.8
\#3  0x0ff01130 in Perl\_yylex \(\) from /usr/lib/libperl\.so\.5\.8
\#4  0x0ff0e584 in Perl\_yyparse \(\) from /usr/lib/libperl\.so\.5\.8
\#5  0x0ff7c184 in Perl\_sv\_compile\_2op \(\) from /usr/lib/libperl\.so\.5\.8
\#6  0x0ff7dbc8 in Perl\_pp\_entereval \(\) from /usr/lib/libperl\.so\.5\.8
\#7  0x0ff45b08 in Perl\_runops\_standard \(\) from /usr/lib/libperl\.so\.5\.8
\#8  0x0fee5960 in perl\_run \(\) from /usr/lib/libperl\.so\.5\.8
\#9  0x0fee5638 in perl\_run \(\) from /usr/lib/libperl\.so\.5\.8
\#10 0x1000209c in main \(\)
\#11 0x0fc54d04 in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6

Valgrind\, on a friend's machine&#8203;:
==26997== valgrind\-1\.0\.0\, a memory error detector for x86 GNU/Linux\.
==26997== Copyright \(C\) 2000\-2002\, and GNU GPL'd\, by Julian Seward\.
==26997== Estimated CPU clock rate is 758 MHz
==26997== For more details\, rerun with&#8203;: \-v
==26997== 
==26997== Invalid read of size 4
==26997==    at 0x8077A18&#8203;: \(within /usr/bin/perl\)
==26997==    by 0x8077F53&#8203;: \(within /usr/bin/perl\)
==26997==    by 0x8066027&#8203;: \(within /usr/bin/perl\)
==26997==    by 0x8075AB6&#8203;: \(within /usr/bin/perl\)
==26997==    Address 0x42C7B5E4 is 12 bytes after a block of size 52 alloc'd
==26997==    at 0x4004322B&#8203;: malloc \(vg\_clientfuncs\.c&#8203;:100\)
==26997==    by 0x808B58B&#8203;: \(within /usr/bin/perl\)
==26997==    by 0x809E2FA&#8203;: \(within /usr/bin/perl\)
==26997==    by 0x80600CD&#8203;: \(within /usr/bin/perl\)
==26997== 
==26997== Invalid read of size 4
==26997==    at 0x8077D36&#8203;: \(within /usr/bin/perl\)
==26997==    by 0x8077F53&#8203;: \(within /usr/bin/perl\)
==26997==    by 0x8066027&#8203;: \(within /usr/bin/perl\)
==26997==    by 0x8075AB6&#8203;: \(within /usr/bin/perl\)
==26997==    Address 0x42C7B5E8 is not stack'd\, malloc'd or free'd
==26997== 
==26997== Invalid read of size 4
==26997==    at 0x8077A13&#8203;: \(within /usr/bin/perl\)
==26997==    by 0x8077F53&#8203;: \(within /usr/bin/perl\)
==26997==    by 0x8066027&#8203;: \(within /usr/bin/perl\)
==26997==    by 0x8075AB6&#8203;: \(within /usr/bin/perl\)
==26997==    Address 0x19 is not stack'd\, malloc'd or free'd

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl v5.8.0:

Configured by Debian Project at Fri Jun  6 00:08:36 EST 2003.

Summary of my perl5 (revision 5.0 version 8 subversion 0) configuration:
  Platform:
    osname=linux, osvers=2.4.20-xfs, archname=powerpc-linux-thread-multi
    uname='linux vir 2.4.20-xfs #1 sat nov 30 13:02:47 est 2002 ppc gnulinux '
    config_args='-Dusethreads -Duselargefiles -Dccflags=-DDEBIAN -Dcccdlflags=-fPIC -Darchname=powerpc-linux -Dprefix=/usr -Dprivlib=/usr/share/perl/5.8.0 -Darchlib=/usr/lib/perl/5.8.0 -Dvendorprefix=/usr -Dvendorlib=/usr/share/perl5 -Dvendorarch=/usr/lib/perl5 -Dsiteprefix=/usr/local -Dsitelib=/usr/local/share/perl/5.8.0 -Dsitearch=/usr/local/lib/perl/5.8.0 -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 -Dman1ext=1 -Dman3ext=3perl -Dpager=/usr/bin/sensible-pager -Uafs -Ud_csh -Uusesfio -Uusenm -Duseshrplib -Dlibperl=libperl.so.5.8.0 -Dd_dosuid -des'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O3',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fno-strict-aliasing'
    ccversion='', gccversion='3.3 (Debian)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=4321
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=8
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lgdbm -ldb -ldl -lm -lpthread -lc -lcrypt
    perllibs=-ldl -lm -lpthread -lc -lcrypt
    libc=/lib/libc-2.3.1.so, so=so, useshrplib=true, libperl=libperl.so.5.8.0
    gnulibc_version='2.3.1'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.0:
    /etc/perl
    /usr/local/lib/perl/5.8.0
    /usr/local/share/perl/5.8.0
    /usr/lib/perl5
    /usr/share/perl5
    /usr/lib/perl/5.8.0
    /usr/share/perl/5.8.0
    /usr/local/lib/site_perl
    .


Environment for perl v5.8.0:
    HOME=/home/frederik
    LANG=C
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/frederik/bin:/usr/local/bin:/usr/X11R6/bin:/usr/bin:/bin:/home/frederik/sbin:/usr/local/sbin:/usr/X11R6/sbin:/usr/sbin:/sbin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @iabyn

On Fri\, Jun 20\, 2003 at 12&#8203;:45&#8203;:32AM \-0000\, frederik@&#8203;ugcs\.caltech\.edu \(via RT\) wrote&#8203;:
> Segmentation fault on 5\.6\.1 i386 \(several distributions\)\, 5\.8\.0 ppc
> \(debian\) and i386 \(several\)\, and blead alpha\-openbsd\.

I can't reproduce this on recent bleeds \(18597 onwards\)\. Which patch
level of bleed were you able to get a segfault on?

Dave\.

> 
> Failed to reproduce on 5\.6\.0 i386 \(custom\)\.
> 
> Contents of 'bug'&#8203;:
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \#\!/usr/bin/perl
> use strict;
> use warnings;
> my $T; our $x; my $q;
> sub foo \{
>   my \($f\, $ev\) = @&#8203;\_;
>   $ev ||= sub \{ eval\(shift\) \};
>   local $x;
>   my $res = &$ev\($f\.'return sub \{ eval\(shift\); \};'\);
>   return $res;
> \}
> my $a = '$q = sub \{$T\};';
> my $b = '$T=2;';
> foo\($a\, undef\);
> foo\($a\, foo\($b\, undef\)\);
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> 
> % \./bug
> Segmentation fault
> 
> In gdb \.\.\.
> Program received signal SIGSEGV\, Segmentation fault\.
> \[Switching to Thread 16384 \(LWP 8358\)\]
> 0x0ff0ed00 in Perl\_pad\_allocmy \(\) from /usr/lib/libperl\.so\.5\.8
> \(gdb\) bt
> \#0  0x0ff0ed00 in Perl\_pad\_allocmy \(\) from /usr/lib/libperl\.so\.5\.8
> \#1  0x0ff0ed0c in Perl\_pad\_allocmy \(\) from /usr/lib/libperl\.so\.5\.8
> \#2  0x0ff011f4 in Perl\_yylex \(\) from /usr/lib/libperl\.so\.5\.8
> \#3  0x0ff01130 in Perl\_yylex \(\) from /usr/lib/libperl\.so\.5\.8
> \#4  0x0ff0e584 in Perl\_yyparse \(\) from /usr/lib/libperl\.so\.5\.8
> \#5  0x0ff7c184 in Perl\_sv\_compile\_2op \(\) from /usr/lib/libperl\.so\.5\.8
> \#6  0x0ff7dbc8 in Perl\_pp\_entereval \(\) from /usr/lib/libperl\.so\.5\.8
> \#7  0x0ff45b08 in Perl\_runops\_standard \(\) from /usr/lib/libperl\.so\.5\.8
> \#8  0x0fee5960 in perl\_run \(\) from /usr/lib/libperl\.so\.5\.8
> \#9  0x0fee5638 in perl\_run \(\) from /usr/lib/libperl\.so\.5\.8
> \#10 0x1000209c in main \(\)
> \#11 0x0fc54d04 in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6
> 
> Valgrind\, on a friend's machine&#8203;:
> ==26997== valgrind\-1\.0\.0\, a memory error detector for x86 GNU/Linux\.
> ==26997== Copyright \(C\) 2000\-2002\, and GNU GPL'd\, by Julian Seward\.
> ==26997== Estimated CPU clock rate is 758 MHz
> ==26997== For more details\, rerun with&#8203;: \-v
> ==26997== 
> ==26997== Invalid read of size 4
> ==26997==    at 0x8077A18&#8203;: \(within /usr/bin/perl\)
> ==26997==    by 0x8077F53&#8203;: \(within /usr/bin/perl\)
> ==26997==    by 0x8066027&#8203;: \(within /usr/bin/perl\)
> ==26997==    by 0x8075AB6&#8203;: \(within /usr/bin/perl\)
> ==26997==    Address 0x42C7B5E4 is 12 bytes after a block of size 52 alloc'd
> ==26997==    at 0x4004322B&#8203;: malloc \(vg\_clientfuncs\.c&#8203;:100\)
> ==26997==    by 0x808B58B&#8203;: \(within /usr/bin/perl\)
> ==26997==    by 0x809E2FA&#8203;: \(within /usr/bin/perl\)
> ==26997==    by 0x80600CD&#8203;: \(within /usr/bin/perl\)
> ==26997== 
> ==26997== Invalid read of size 4
> ==26997==    at 0x8077D36&#8203;: \(within /usr/bin/perl\)
> ==26997==    by 0x8077F53&#8203;: \(within /usr/bin/perl\)
> ==26997==    by 0x8066027&#8203;: \(within /usr/bin/perl\)
> ==26997==    by 0x8075AB6&#8203;: \(within /usr/bin/perl\)
> ==26997==    Address 0x42C7B5E8 is not stack'd\, malloc'd or free'd
> ==26997== 
> ==26997== Invalid read of size 4
> ==26997==    at 0x8077A13&#8203;: \(within /usr/bin/perl\)
> ==26997==    by 0x8077F53&#8203;: \(within /usr/bin/perl\)
> ==26997==    by 0x8066027&#8203;: \(within /usr/bin/perl\)
> ==26997==    by 0x8075AB6&#8203;: \(within /usr/bin/perl\)
> ==26997==    Address 0x19 is not stack'd\, malloc'd or free'd
> 
> \[Please do not change anything below this line\]
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \-\-\-
> Flags&#8203;:
>     category=core
>     severity=high
> \-\-\-
> Site configuration information for perl v5\.8\.0&#8203;:
> 
> Configured by Debian Project at Fri Jun  6 00&#8203;:08&#8203;:36 EST 2003\.
> 
> Summary of my perl5 \(revision 5\.0 version 8 subversion 0\) configuration&#8203;:
>   Platform&#8203;:
>     osname=linux\, osvers=2\.4\.20\-xfs\, archname=powerpc\-linux\-thread\-multi
>     uname='linux vir 2\.4\.20\-xfs \#1 sat nov 30 13&#8203;:02&#8203;:47 est 2002 ppc gnulinux '
>     config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN \-Dcccdlflags=\-fPIC \-Darchname=powerpc\-linux \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.8\.0 \-Darchlib=/usr/lib/perl/5\.8\.0 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.8\.0 \-Dsitearch=/usr/local/lib/perl/5\.8\.0 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dman1ext=1 \-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Uusesfio \-Uusenm \-Duseshrplib \-Dlibperl=libperl\.so\.5\.8\.0 \-Dd\_dosuid \-des'
>     hint=recommended\, useposix=true\, d\_sigaction=define
>     usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
>     useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
>     use64bitint=undef use64bitall=undef uselongdouble=undef
>     usemymalloc=n\, bincompat5005=undef
>   Compiler&#8203;:
>     cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
>     optimize='\-O3'\,
>     cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing'
>     ccversion=''\, gccversion='3\.3 \(Debian\)'\, gccosandvers=''
>     intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=4321
>     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=8
>     ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
>     alignbytes=8\, prototype=define
>   Linker and Libraries&#8203;:
>     ld='cc'\, ldflags =' \-L/usr/local/lib'
>     libpth=/usr/local/lib /lib /usr/lib
>     libs=\-lgdbm \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
>     perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
>     libc=/lib/libc\-2\.3\.1\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.8\.0
>     gnulibc\_version='2\.3\.1'
>   Dynamic Linking&#8203;:
>     dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
>     cccdlflags='\-fPIC'\, lddlflags='\-shared \-L/usr/local/lib'
> 
> Locally applied patches&#8203;:
>     
> 
> \-\-\-
> @&#8203;INC for perl v5\.8\.0&#8203;:
>     /etc/perl
>     /usr/local/lib/perl/5\.8\.0
>     /usr/local/share/perl/5\.8\.0
>     /usr/lib/perl5
>     /usr/share/perl5
>     /usr/lib/perl/5\.8\.0
>     /usr/share/perl/5\.8\.0
>     /usr/local/lib/site\_perl
>     \.
> 
> \-\-\-
> Environment for perl v5\.8\.0&#8203;:
>     HOME=/home/frederik
>     LANG=C
>     LANGUAGE \(unset\)
>     LD\_LIBRARY\_PATH \(unset\)
>     LOGDIR \(unset\)
>     PATH=/home/frederik/bin&#8203;:/usr/local/bin&#8203;:/usr/X11R6/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/home/frederik/sbin&#8203;:/usr/local/sbin&#8203;:/usr/X11R6/sbin&#8203;:/usr/sbin&#8203;:/sbin
>     PERL\_BADLANG \(unset\)
>     SHELL=/bin/bash

\-\- 
The optimist believes that he lives in the best of all possible worlds\.
As does the pessimist\.

**Comment by p5pRT** [comment]
### From @andk

Dave Mitchell \<davem@&#8203;fdgroup\.com> writes&#8203;:

> On Fri\, Jun 20\, 2003 at 12&#8203;:45&#8203;:32AM \-0000\, frederik@&#8203;ugcs\.caltech\.edu \(via RT\) wrote&#8203;:
>> Segmentation fault on 5\.6\.1 i386 \(several distributions\)\, 5\.8\.0 ppc
>> \(debian\) and i386 \(several\)\, and blead alpha\-openbsd\.
>
> I can't reproduce this on recent bleeds \(18597 onwards\)\. Which patch
> level of bleed were you able to get a segfault on?

Looks like your 18220 fixed that\.

\-\- 
andreas

**Comment by p5pRT** [comment]
@rgs - Status changed from 'new' to 'resolved'
