### ISSUE TITLE
Segmentation fault on "make install" on AIX 4.2.1.0

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6588]
Migrated from [rt.perl.org#22819](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=22819) (status was 'rejected')

Searchable as RT22819$

**Comment by p5pRT** [comment]
### From mcooper@magnicomp.com

#### Created by mcooper@magnicomp.com


This is a bug report for perl from mcooper@&#8203;magnicomp\.com\,
generated with the help of perlbug 1\.34 running under perl v5\.8\.0\.


\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
I'm attempting to install perl 5\.8\.0 from source on AIX 4\.2\.  When I run "make 
install" \(after a successful "make"\) I get a Segmentation fault&#8203;:

aix2% make install
\.\.\.\. lots of text deleted \.\.\.\.
\./perl installperl
gnumake\[1\]&#8203;: \*\*\* \[install\.perl\] Segmentation fault \(core dumped\)
gnumake\[1\]&#8203;: Leaving directory \`/tmp/p\.obj'
gnumake&#8203;: \*\*\* \[install\] Error 2
aix2% /usr/local/bin/gdb perl
GNU gdb 5\.3
Copyright 2002 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and you are
welcome to change it and/or distribute copies of it under certain conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for details\.
This GDB was configured as "powerpc\-ibm\-aix4\.2\.0\.0"\.\.\.
\(gdb\) run installperl
Starting program&#8203;: /tmp/p\.obj/perl installperl

Program received signal SIGSEGV\, Segmentation fault\.
0x10008b68 in Perl\_pp\_entersub \(\)
\(gdb\) where
\#0  0x10008b68 in Perl\_pp\_entersub \(\)
\#1  0x100a840c in Perl\_runops\_standard \(\)
\#2  0x1005bf48 in S\_call\_body \(\)
\#3  0x1005bc04 in Perl\_call\_sv \(\)
\#4  0x1005fbb0 in S\_call\_list\_body \(\)
\#5  0x1005f778 in Perl\_call\_list \(\)
\#6  0x10043c74 in Perl\_newATTRSUB \(\)
\#7  0x1003f470 in Perl\_utilize \(\)
\#8  0x100996f0 in Perl\_yyparse \(\)
\#9  0x1005ab28 in S\_parse\_body \(\)
\#10 0x10059b7c in perl\_parse \(\)
\#11 0x100002b4 in main \(\)
\#12 0x100001a0 in \_\_start \(\)
\(gdb\) quit
aix2% file perl
perl&#8203;:           executable \(RISC System/6000\) or object module not stripped

A good number of "make test" tests also fail\.

When running Configure I accept all default values\.  I compiled with GCC 3\.3\, 
but also have tried GCC 2\.95\.1\.  I've tried this numerous times all with the 
same result\.

The system is freshly installed with default options\.  It has the AIX updates applied\.

If I boot the system off of its AIX 4\.3 OS disk and configure/build/install perl\, I have
no problems\.

Anybody have any clues on this?

Thanks in advance\.

&nbsp;     mike

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

This perlbug was built using Perl v5.8.0 - Tue Jun 24 15:06:17 PDT 2003
It is being executed now by  Perl v5.8.0 - Mon Jul 22 10:24:32 PDT 2002.

Site configuration information for perl v5.8.0:

Configured by library at Mon Jul 22 10:24:32 PDT 2002.

Summary of my perl5 (revision 5.0 version 8 subversion 0) configuration:
  Platform:
    osname=aix, osvers=4.2.0.0, archname=aix
    uname='aix pdslib42 2 4 000042024900 '
    config_args='-de'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_ALL_SOURCE -D_ANSI_C_SOURCE -D_POSIX_SOURCE -qmaxmem=16384 -qnoansialias -I/usr/local/include',
    optimize='-O',
    cppflags='-D_ALL_SOURCE -D_ANSI_C_SOURCE -D_POSIX_SOURCE -qmaxmem=16384 -qnoansialias -I/usr/local/include'
    ccversion='3.1.4.0', gccversion='', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=4321
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=8
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=4
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='ld', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib /usr/ccs/lib
    libs=-lnsl -lgdbm -ldbm -ldb -ldl -lld -lm -lc -lbsd -lPW
    perllibs=-lnsl -ldl -lld -lm -lc -lbsd -lPW
    libc=, so=a, useshrplib=false, libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_aix.xs, dlext=so, d_dlsymun=undef, ccdlflags='  -bE:/usr/local/lib/perl5/5.8.0/aix/CORE/perl.exp'
    cccdlflags=' ', lddlflags=' -bhalt:4 -bM:SRE -bI:$(PERL_INC)/perl.exp -bE:$(BASEEXT).exp -bnoentry -lc -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.0:
    /usr/local/lib/perl5/5.8.0/aix
    /usr/local/lib/perl5/5.8.0
    /usr/local/lib/perl5/site_perl/5.8.0/aix
    /usr/local/lib/perl5/site_perl/5.8.0
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.8.0:
    HOME=/home/mcooper
    LANG=en_US
    LANGUAGE (unset)
    LC__FASTMSG=true
    LD_LIBRARY_PATH=/usr/lib:/usr/lib::/usr/local/lib:/usr/dt/lib::/usr/local/lib:/usr/dt/lib
    LIBPATH (unset)
    LOGDIR (unset)
    PATH=/usr/local/gcc/default/bin:/tools/bin:/usr/local/bin:/usr/dt/bin:/usr/ucb:/bin:/usr/bin:/usr/ccs/bin:/home/mcooper/bin:/usr/sbin:/sbin
    PERL_BADLANG (unset)
    SHELL=/tools/bin/tcsh

```
</details>

**Comment by p5pRT** [comment]
### From @jkeenan

On Thu Jun 26 11&#8203;:52&#8203;:42 2003\, mcooper7290 wrote&#8203;:
> 
> I'm attempting to install perl 5\.8\.0 from source on AIX 4\.2\.  When I
> run "make
> install" \(after a successful "make"\) I get a Segmentation fault&#8203;:
> 
> aix2% make install
> \.\.\.\. lots of text deleted \.\.\.\.
> \./perl installperl
> gnumake\[1\]&#8203;: \*\*\* \[install\.perl\] Segmentation fault \(core dumped\)
> gnumake\[1\]&#8203;: Leaving directory \`/tmp/p\.obj'
> gnumake&#8203;: \*\*\* \[install\] Error 2
> aix2% /usr/local/bin/gdb perl
> GNU gdb 5\.3
> Copyright 2002 Free Software Foundation\, Inc\.
> GDB is free software\, covered by the GNU General Public License\, and
> you are
> welcome to change it and/or distribute copies of it under certain
> conditions\.
> Type "show copying" to see the conditions\.
> There is absolutely no warranty for GDB\.  Type "show warranty" for
> details\.
> This GDB was configured as "powerpc\-ibm\-aix4\.2\.0\.0"\.\.\.
> \(gdb\) run installperl
> Starting program&#8203;: /tmp/p\.obj/perl installperl
> 
> Program received signal SIGSEGV\, Segmentation fault\.
> 0x10008b68 in Perl\_pp\_entersub \(\)
> \(gdb\) where
> \#0  0x10008b68 in Perl\_pp\_entersub \(\)
> \#1  0x100a840c in Perl\_runops\_standard \(\)
> \#2  0x1005bf48 in S\_call\_body \(\)
> \#3  0x1005bc04 in Perl\_call\_sv \(\)
> \#4  0x1005fbb0 in S\_call\_list\_body \(\)
> \#5  0x1005f778 in Perl\_call\_list \(\)
> \#6  0x10043c74 in Perl\_newATTRSUB \(\)
> \#7  0x1003f470 in Perl\_utilize \(\)
> \#8  0x100996f0 in Perl\_yyparse \(\)
> \#9  0x1005ab28 in S\_parse\_body \(\)
> \#10 0x10059b7c in perl\_parse \(\)
> \#11 0x100002b4 in main \(\)
> \#12 0x100001a0 in \_\_start \(\)
> \(gdb\) quit
> aix2% file perl
> perl&#8203;:           executable \(RISC System/6000\) or object module not
> stripped
> 
> A good number of "make test" tests also fail\.
> 
> When running Configure I accept all default values\.  I compiled with
> GCC 3\.3\,
> but also have tried GCC 2\.95\.1\.  I've tried this numerous times all
> with the
> same result\.
> 
> The system is freshly installed with default options\.  It has the AIX
> updates applied\.
> 
> If I boot the system off of its AIX 4\.3 OS disk and
> configure/build/install perl\, I have
> no problems\.
> 
> Anybody have any clues on this?
> 

Given the age of this ticket and the fact that the version of Perl
described is no longer supported\, I doubt that there is much we can do
about this ticket\.

But would any of us who are familiar with AIX have any comments about
this problem?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From mike.cooper@magnicomp.com

I think you can safely close this ticket\.  Needless to say\, we moved on and 
don't use AIX 4\.2 any longer\.

&nbsp;    mike

On 12/11/2011 05&#8203;:59 AM\, James E Keenan via RT wrote&#8203;:
> On Thu Jun 26 11&#8203;:52&#8203;:42 2003\, mcooper7290 wrote&#8203;:
>>
>> I'm attempting to install perl 5\.8\.0 from source on AIX 4\.2\.  When I
>> run "make
>> install" \(after a successful "make"\) I get a Segmentation fault&#8203;:
>>
>> aix2% make install
>> \.\.\.\. lots of text deleted \.\.\.\.
>> \./perl installperl
>> gnumake\[1\]&#8203;: \*\*\* \[install\.perl\] Segmentation fault \(core dumped\)
>> gnumake\[1\]&#8203;: Leaving directory \`/tmp/p\.obj'
>> gnumake&#8203;: \*\*\* \[install\] Error 2
>> aix2% /usr/local/bin/gdb perl
>> GNU gdb 5\.3
>> Copyright 2002 Free Software Foundation\, Inc\.
>> GDB is free software\, covered by the GNU General Public License\, and
>> you are
>> welcome to change it and/or distribute copies of it under certain
>> conditions\.
>> Type "show copying" to see the conditions\.
>> There is absolutely no warranty for GDB\.  Type "show warranty" for
>> details\.
>> This GDB was configured as "powerpc\-ibm\-aix4\.2\.0\.0"\.\.\.
>> \(gdb\) run installperl
>> Starting program&#8203;: /tmp/p\.obj/perl installperl
>>
>> Program received signal SIGSEGV\, Segmentation fault\.
>> 0x10008b68 in Perl\_pp\_entersub \(\)
>> \(gdb\) where
>> \#0  0x10008b68 in Perl\_pp\_entersub \(\)
>> \#1  0x100a840c in Perl\_runops\_standard \(\)
>> \#2  0x1005bf48 in S\_call\_body \(\)
>> \#3  0x1005bc04 in Perl\_call\_sv \(\)
>> \#4  0x1005fbb0 in S\_call\_list\_body \(\)
>> \#5  0x1005f778 in Perl\_call\_list \(\)
>> \#6  0x10043c74 in Perl\_newATTRSUB \(\)
>> \#7  0x1003f470 in Perl\_utilize \(\)
>> \#8  0x100996f0 in Perl\_yyparse \(\)
>> \#9  0x1005ab28 in S\_parse\_body \(\)
>> \#10 0x10059b7c in perl\_parse \(\)
>> \#11 0x100002b4 in main \(\)
>> \#12 0x100001a0 in \_\_start \(\)
>> \(gdb\) quit
>> aix2% file perl
>> perl&#8203;:           executable \(RISC System/6000\) or object module not
>> stripped
>>
>> A good number of "make test" tests also fail\.
>>
>> When running Configure I accept all default values\.  I compiled with
>> GCC 3\.3\,
>> but also have tried GCC 2\.95\.1\.  I've tried this numerous times all
>> with the
>> same result\.
>>
>> The system is freshly installed with default options\.  It has the AIX
>> updates applied\.
>>
>> If I boot the system off of its AIX 4\.3 OS disk and
>> configure/build/install perl\, I have
>> no problems\.
>>
>> Anybody have any clues on this?
>>
>
> Given the age of this ticket and the fact that the version of Perl
> described is no longer supported\, I doubt that there is much we can do
> about this ticket\.
>
> But would any of us who are familiar with AIX have any comments about
> this problem?
>
> Thank you very much\.
> Jim Keenan

**Comment by p5pRT** [comment]
@jkeenan - Status changed from 'open' to 'rejected'

**Comment by p5pRT** [comment]
### From tammer@tammer.net

Hello\,
sorry\, I have no useful comment on this besides that
Perl 5\.8\.9 does compile on 4\.3\.3 without a problem\.
Unfortunately I do no longer have access to a AIX 4\.2 system\.
AIX 4\.2\.x was released in 1996 and 4\.2\.1 in 1997\.\.\.

Bye
&nbsp;  Rainer

On 11\.12\.2011 14&#8203;:59\, James E Keenan via RT wrote&#8203;:
> On Thu Jun 26 11&#8203;:52&#8203;:42 2003\, mcooper7290 wrote&#8203;:
>> I'm attempting to install perl 5\.8\.0 from source on AIX 4\.2\.  When I
>> run "make
>> install" \(after a successful "make"\) I get a Segmentation fault&#8203;:
>>
>> aix2% make install
>> \.\.\.\. lots of text deleted \.\.\.\.
>> \./perl installperl
>> gnumake\[1\]&#8203;: \*\*\* \[install\.perl\] Segmentation fault \(core dumped\)
>> gnumake\[1\]&#8203;: Leaving directory \`/tmp/p\.obj'
>> gnumake&#8203;: \*\*\* \[install\] Error 2
>> aix2% /usr/local/bin/gdb perl
>> GNU gdb 5\.3
>> Copyright 2002 Free Software Foundation\, Inc\.
>> GDB is free software\, covered by the GNU General Public License\, and
>> you are
>> welcome to change it and/or distribute copies of it under certain
>> conditions\.
>> Type "show copying" to see the conditions\.
>> There is absolutely no warranty for GDB\.  Type "show warranty" for
>> details\.
>> This GDB was configured as "powerpc\-ibm\-aix4\.2\.0\.0"\.\.\.
>> \(gdb\) run installperl
>> Starting program&#8203;: /tmp/p\.obj/perl installperl
>>
>> Program received signal SIGSEGV\, Segmentation fault\.
>> 0x10008b68 in Perl\_pp\_entersub \(\)
>> \(gdb\) where
>> \#0  0x10008b68 in Perl\_pp\_entersub \(\)
>> \#1  0x100a840c in Perl\_runops\_standard \(\)
>> \#2  0x1005bf48 in S\_call\_body \(\)
>> \#3  0x1005bc04 in Perl\_call\_sv \(\)
>> \#4  0x1005fbb0 in S\_call\_list\_body \(\)
>> \#5  0x1005f778 in Perl\_call\_list \(\)
>> \#6  0x10043c74 in Perl\_newATTRSUB \(\)
>> \#7  0x1003f470 in Perl\_utilize \(\)
>> \#8  0x100996f0 in Perl\_yyparse \(\)
>> \#9  0x1005ab28 in S\_parse\_body \(\)
>> \#10 0x10059b7c in perl\_parse \(\)
>> \#11 0x100002b4 in main \(\)
>> \#12 0x100001a0 in \_\_start \(\)
>> \(gdb\) quit
>> aix2% file perl
>> perl&#8203;:           executable \(RISC System/6000\) or object module not
>> stripped
>>
>> A good number of "make test" tests also fail\.
>>
>> When running Configure I accept all default values\.  I compiled with
>> GCC 3\.3\,
>> but also have tried GCC 2\.95\.1\.  I've tried this numerous times all
>> with the
>> same result\.
>>
>> The system is freshly installed with default options\.  It has the AIX
>> updates applied\.
>>
>> If I boot the system off of its AIX 4\.3 OS disk and
>> configure/build/install perl\, I have
>> no problems\.
>>
>> Anybody have any clues on this?
>>
> Given the age of this ticket and the fact that the version of Perl
> described is no longer supported\, I doubt that there is much we can do
> about this ticket\.
>
> But would any of us who are familiar with AIX have any comments about
> this problem?
>
> Thank you very much\.
> Jim Keenan
>
>
