### ISSUE TITLE
Perl core dumps

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#663]
Migrated from [rt.perl.org#1543](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=1543) (status was 'resolved')

Searchable as RT1543$

**Comment by p5pRT** [comment]
### From stavros@esc.net.au

I have a perl program which is core dumping\.  I've been told that if perl
core dumps then its it perl's fault\.

Here are the details\, please let me know if the probelm is mine or perl's&#8203;:

bang2\# uname \-a
FreeBSD bang2\.esc\.net\.au 3\.2\-RELEASE FreeBSD 3\.2\-RELEASE \#0&#8203;: Wed Aug 18
14&#8203;:32&#8203;:45 CST 1 999 stavros@&#8203;bang2\.esc\.net\.au&#8203;:/usr/src/sys/compile/TEST
i386

bang2\# perl \-V
Summary of my perl5 \(5\.0 patchlevel 5 subversion 3\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=freebsd\, osvers=4\.0\-current\, archname=i386\-freebsd
&nbsp;    uname='freebsd freefall\.freebsd\.org 4\.0\-current freebsd 4\.0\-current
\#0&#8203;: $Date&#8203;: 199
9/05/05 19&#8203;:42&#8203;:40 $'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef useperlio=undef d\_sfio=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, optimize='undef'\, gccversion=egcs\-2\.91\.66 19990314
\(egcs\-1\.1\.2 release\)
&nbsp;    cppflags=''
&nbsp;    ccflags =''
&nbsp;    stdchar='char'\, d\_stdstdio=undef\, usevfork=true
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    alignbytes=4\, usemymalloc=n\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags ='\-Wl\,\-E'
&nbsp;    libpth=/usr/lib
&nbsp;    libs=\-lm \-lc \-lcrypt
&nbsp;    libc=/usr/lib/libc\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.3
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags='\-DPIC \-fpic'\, lddlflags='\-shared'
 
 
Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Built under freebsd
&nbsp;  Compiled at May 18 1999 02&#8203;:56&#8203;:17
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/libdata/perl/5\.00503/mach
&nbsp;    /usr/libdata/perl/5\.00503
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.005/i386\-freebsd
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.005
&nbsp;    \.

Finally the script&#8203;:

bang2\# cat make\_headings\.pl

\#\!/usr/local/bin/perl
 
use DB\_File;
 
dbmopen\(%all\, "db/ALL"\, 0444\);
dbmopen\(%info\, "info/INFO"\, 0655\);
 
for \($i=1; $i \< 2000000; $i\+\+\)\{
&nbsp;    $temp = $all\{$i\} ;
&nbsp;    $temp =~ s/\.\*HEADING&#8203;:\(\.\*?\)\\n\.\*/$1/isg;
&nbsp;    $temp  =~ s/\\s|'|\-|&|\\/|\,|\\\.//g;
 
&nbsp;    split \(/\\\,/\, $info\{$temp\}\);
 
&nbsp;    foreach $num \(@&#8203;\_\)\{
&nbsp;        if \($num == $i\)\{
&nbsp;            $NO = 1;
&nbsp;        \}
&nbsp;    \}
 
&nbsp;    if \(\! defined $NO\)\{
&nbsp;        $info\{$temp\} \.= "$i\,";
&nbsp;    \}
&nbsp;    undef $NO;
 
\}
 
dbmclose\(%info\);
dbmclose\(%all\);


bang2\# \./make\_headings\.pl
Bus error \(core dumped\)

The script is a really basic version of another more complicated script
that I was writing to perfom seraching over the db file\.  The keys are
numbers 1\-2\,000\,000 \(2million\)\.  The db file is about 1\.5Gb on size\,
however it occupies about 4\.3Gb\.  I can send you a copy of the core dump
if you need it\.  



Regards\,


Stavros Patiniotis


---
\-System Administrator / Network Manager             Escape\.Net            \-
\-                                      465b South Rd         \- 
\-email&#8203;: stavros@&#8203;esc\.net\.au                   Keswick SA 5035       \-
\-URL&#8203;: http&#8203;://www\.esc\.net\.au                   Ph 82932526 Fax 82932949\-


---

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Fri\, 01 Oct 1999 at 00&#8203;:45&#8203;:48 \+0930\, Stavros Patiniotis wrote&#8203;:

> I have a perl program which is core dumping\.  I've been told that if perl
> core dumps then its it perl's fault\.

It's the fault of the program that's running&#8203;: in this case we have
Berkeley DB in the pot as well\.

> use DB\_File;
> dbmopen\(%all\, "db/ALL"\, 0444\);
> dbmopen\(%info\, "info/INFO"\, 0655\);

It may be worth trying again\, using tie/DB\_File \(dbmopen is a hangover from
perl 4\, and is only really intended for use with NDBM or SDBM\)\.

> The script is a really basic version of another more complicated script
> that I was writing to perfom seraching over the db file\.  The keys are
> numbers 1\-2\,000\,000 \(2million\)\.  The db file is about 1\.5Gb on size\,
> however it occupies about 4\.3Gb\.  I can send you a copy of the core dump
> if you need it\.  

A 'backtrace' from the core dump would be quite useful\. Use 'gdb perl
core' and 'backtrace'

Also specify exactly which version of DB you're using\. There are
core\-dump issues with Berkeley DB \(sorry\, don't have details to hand\)\.

Ian

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Ian Phillipps \<ian@&#8203;dial\.pipex\.com> wrote
> It may be worth trying again\, using tie/DB\_File \(dbmopen is a hangover from
> perl 4\, and is only really intended for use with NDBM or SDBM\)\.

Well\, that's not quite what the man page says\.   It explicitly mentions
use with all the \*DBM modules\.    And I doubt that trying with tie/DB\_File
will make a difference \(unless his default \*DBM is something other
than DB\_File :\-\)\, since dbmopen\(\) is effectively just syntactic sugar for
the tie operation\.


Mike Guy

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Fri\, 1 Oct 1999\, M\.J\.T\. Guy wrote&#8203;:

> Ian Phillipps \<ian@&#8203;dial\.pipex\.com> wrote
> > It may be worth trying again\, using tie/DB\_File \(dbmopen is a hangover from
> > perl 4\, and is only really intended for use with NDBM or SDBM\)\.
> 
> Well\, that's not quite what the man page says\.   It explicitly mentions
> use with all the \*DBM modules\.    And I doubt that trying with tie/DB\_File
> will make a difference \(unless his default \*DBM is something other
> than DB\_File :\-\)\, since dbmopen\(\) is effectively just syntactic sugar for
> the tie operation\.

Well I tried the tie option\, and it worked on the program that I sent to
this list\, however it didn't work on all my other programs\. 

I'm not sure how to get the version of the DB files\, so could someone
please let me know\.

This is the error I'm getting now&#8203;:

\./stats\.pl  
Bus error \(core dumped\)


I can include the script if you like?  I'm not sure how to process the
core dump\, so any info would be appreciated\.

 
Thanks\!


Regards\,


Stavros Patiniotis


---
\-System Administrator / Network Manager             Escape\.Net            \-
\-                                      465b South Rd         \- 
\-email&#8203;: stavros@&#8203;esc\.net\.au                   Keswick SA 5035       \-
\-URL&#8203;: http&#8203;://www\.esc\.net\.au                   Ph 82932526 Fax 82932949\-


---

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Fri\, 01 Oct 1999 at 18&#8203;:34&#8203;:34 \+0100\, M\.J\.T\. Guy wrote&#8203;:
> Ian Phillipps \<ian@&#8203;dial\.pipex\.com> wrote
> > It may be worth trying again\, using tie/DB\_File \(dbmopen is a hangover from
> > perl 4\, and is only really intended for use with NDBM or SDBM\)\.
> 
> Well\, that's not quite what the man page says\.   It explicitly mentions
> use with all the \*DBM modules\.    And I doubt that trying with tie/DB\_File
> will make a difference \(unless his default \*DBM is something other
> than DB\_File :\-\)\, since dbmopen\(\) is effectively just syntactic sugar for
> the tie operation\.

Sorry\, bad editing\.  I submitted three p5p postings last night\, all of
them c\-\-p\.  \(Read the Date headers to see why :\-\)

It's GDBM that doesn't always fly with AnyDBM\_File \(and therefore
dbmopen\)\, because of its different use of flags&#8203;: as discussed here a
while ago\.

In particular\, GDBM\_WRCREATE == 2\, whereas O\_CREAT|O\_RDWR == 66\.

\[Aside&#8203;: bug in SDBM\_File documentation omits 'use Fcntl'\.  Try&#8203;:
&nbsp;    perl \-e 'use SDBM\_File; print O\_RDWR|O\_CREAT; print "\\n";'
and see if you can work out the reason for what it prints\.\.\.\]

To Stavros&#8203;: if you have gdb \(not gdbm\!\) then run
&nbsp;    gdb /your/path/to/perl core
and issue the
&nbsp;    backtrace
command\.   \(Note that many BSDs have /usr/bin/perl and
/usr/local/bin/perl as quite different versions \- get the right one\!\)

This should give an idea if the dump is occurring in perl itself or DB\.
It's possible for DB to have passed perl a dud pointer\, of course :\-\(
More useful stuff is inferrable if you compiled your perl\, and
preferably the Berkeley DB\, with a '\-g' flag; fortunately GCC permits
this at the same time as optimisation\.

Oh\, and I don't think anyone's mentioned 'use sigtrap'\, either\.
Now they have :\-\)

Ian
\-\-
In theory\, there's no difference between theory and practice\.
In practice\, there is\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Sat\, 2 Oct 1999\, Ian Phillipps wrote&#8203;:


> To Stavros&#8203;: if you have gdb \(not gdbm\!\) then run
>     gdb /your/path/to/perl core
> and issue the
>     backtrace
> command\.   \(Note that many BSDs have /usr/bin/perl and
> /usr/local/bin/perl as quite different versions \- get the right one\!\)

They are both the same\, 5\.005\_03\.
 
> This should give an idea if the dump is occurring in perl itself or DB\.
> It's possible for DB to have passed perl a dud pointer\, of course :\-\(
> More useful stuff is inferrable if you compiled your perl\, and
> preferably the Berkeley DB\, with a '\-g' flag; fortunately GCC permits
> this at the same time as optimisation\.

I have no idea\!

Core was generated by \`perl'\.
Program terminated with signal 10\, Bus error\.
Reading symbols from /usr/lib/libperl\.so\.3\.\.\.\(no debugging symbols
found\)\.\.\.
done\.
Reading symbols from /usr/lib/libm\.so\.2\.\.\.\(no debugging symbols
found\)\.\.\.done\.
Reading symbols from /usr/lib/libcrypt\.so\.2\.\.\.\(no debugging symbols
found\)\.\.\.
done\.
Reading symbols from /usr/lib/libc\.so\.3\.\.\.\(no debugging symbols
found\)\.\.\.done\.
Reading symbols from /usr/libdata/perl/5\.00503/mach/auto/Fcntl/Fcntl\.so\.\.\.
\(no debugging symbols found\)\.\.\.done\.
Reading symbols from
/usr/libdata/perl/5\.00503/mach/auto/DB\_File/DB\_File\.so\.\.\.
done\.
Reading symbols from /usr/libexec/ld\-elf\.so\.1\.\.\.done\.
\#0  0x2817703f in isatty \(\) from /usr/lib/libc\.so\.3
\(gdb\) backtrace
\#0  0x2817703f in isatty \(\) from /usr/lib/libc\.so\.3
\#1  0x2817732e in isatty \(\) from /usr/lib/libc\.so\.3
\#2  0x28177a3e in malloc \(\) from /usr/lib/libc\.so\.3
\#3  0x280b670a in Perl\_safemalloc \(\) from /usr/lib/libperl\.so\.3
\#4  0x280a2e0e in Perl\_sv\_grow \(\) from /usr/lib/libperl\.so\.3
\#5  0x280a5169 in Perl\_sv\_setpvn \(\) from /usr/lib/libperl\.so\.3
\#6  0x2819a2c2 in XS\_DB\_File\_NEXTKEY \(cv=0x80c2ae8\) at DB\_File\.xs&#8203;:1674
\#7  0x280ae26d in Perl\_pp\_entersub \(\) from /usr/lib/libperl\.so\.3
\#8  0x280df836 in perl\_call\_sv \(\) from /usr/lib/libperl\.so\.3
\#9  0x280df3bf in perl\_call\_method \(\) from /usr/lib/libperl\.so\.3
\#10 0x280b469d in Perl\_magic\_nextpack \(\) from /usr/lib/libperl\.so\.3
\#11 0x280b1ffd in Perl\_hv\_iternext \(\) from /usr/lib/libperl\.so\.3
\#12 0x2809cad1 in Perl\_pp\_each \(\) from /usr/lib/libperl\.so\.3
\#13 0x28079c3d in Perl\_runops\_standard \(\) from /usr/lib/libperl\.so\.3
\#14 0x280df0be in perl\_run \(\) from /usr/lib/libperl\.so\.3
\#15 0x8048da8 in perl\_free \(\)
\#16 0x8048cd5 in perl\_free \(\)
\(gdb\)

I assumes that my postings should all be sent to this list\, not to you in
private?
 
> Oh\, and I don't think anyone's mentioned 'use sigtrap'\, either\.
> Now they have :\-\)

?

Sorry but your dealing with a novice here\.

tie %info\, "DB\_File"\, "info/INFO"\, \(O\_RDONLY\)\, 0444;
tie %data\, "DB\_File"\, "db/ALL"\, \(O\_RDONLY\)\, 0444;

\#This line crashes it\.
while \(\($key\, $val\) = each %info\)


Regards\,


Stavros Patiniotis


---
\-System Administrator / Network Manager             Escape\.Net            \-
\-                                      465b South Rd         \- 
\-email&#8203;: stavros@&#8203;esc\.net\.au                   Keswick SA 5035       \-
\-URL&#8203;: http&#8203;://www\.esc\.net\.au                   Ph 82932526 Fax 82932949\-


---

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Tue\, 05 Oct 1999 at 09&#8203;:36&#8203;:35 \+0930\, Stavros Patiniotis wrote&#8203;:

> I assumes that my postings should all be sent to this list\, not to you in
> private?
>  
> > Oh\, and I don't think anyone's mentioned 'use sigtrap'\, either\.
> > Now they have :\-\)
> 
> ?
> 
> Sorry but your dealing with a novice here\.

Well\, the simplest case is that you include the phrase
&nbsp;    use sigtrap;
into your program\. Easier than you thought\, eh?
There are all sorts of extra features\, but this gives perl\-oriented
output for most SEGV or BUS traps\.

You can say 'man sigtrap' or 'perldoc sigtrap' and get useful
information\, too\.

Ian

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

> > Sorry but your dealing with a novice here\.
> 
> Well\, the simplest case is that you include the phrase
>     use sigtrap;
> into your program\. Easier than you thought\, eh?
> There are all sorts of extra features\, but this gives perl\-oriented
> output for most SEGV or BUS traps\.
> 
> You can say 'man sigtrap' or 'perldoc sigtrap' and get useful
> information\, too\.

Ahh\, so we are running out of memory\!  Too easy\.   I guess I should now
take this off to a different list to get over this problem\- unless anyone
wants to suggest something I can do to get over this\.

bang2\# \./easy info/INFO
KEY                         VALUE
perl in malloc\(\)&#8203;: warning&#8203;: recursive call\.
Out of memory\!
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in free\(\)&#8203;: warning&#8203;: recursive call\.
perl in malloc\(\)&#8203;: warning&#8203;: recursive call\.
Out of memory\!
bang2\#
 
> Ian
> 


Regards\,


Stavros Patiniotis


---
\-System Administrator / Network Manager             Escape\.Net            \-
\-                                      465b South Rd         \- 
\-email&#8203;: stavros@&#8203;esc\.net\.au                   Keswick SA 5035       \-
\-URL&#8203;: http&#8203;://www\.esc\.net\.au                   Ph 82932526 Fax 82932949\-


---
