### ISSUE TITLE
coredump on ext/POSIX/t/posix with NetBSD-1.6

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6673]
Migrated from [rt.perl.org#23202](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=23202) (status was 'resolved')

Searchable as RT23202$

**Comment by p5pRT** [comment]
### From alian@cpan.org

#### Created by alian@cpan.org


This is a bug report for perl from alian@&#8203;cpan\.org\,
generated with the help of perlbug 1\.34 running under perl v5\.8\.0\.


\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
I get coredump on blead & 5\.8\.x with \-Duseithreads

mars&#8203;:\~/perl/perl\-current$ \./perl \-Ilib ext/POSIX/t/posix\.t
1\.\.61
ok 1 \- O\_RDONLY with open
ok 2 \-     with read
not ok 3 \-     read to array element \# TODO read to array element not working
\# Failed at ext/POSIX/t/posix\.t line 40
\#      got undef
\# expected 'perl
\# '
ok 4
ok 5 \- POSIX&#8203;::pipe
ok 6
ok 7 \- POSIX&#8203;::SigSet\->delset
ok 8 \- POSIX&#8203;::SigSet\->ismember
ok 9 \- sigaction SIGHUP
Segmentation fault \(core dumped\)

I get this with NetBSD\-1\.6 on i386 & NetBSD\-1\.6\.1 on sparc
I don't see it on NetBSD\-1\.5\.3 on sparc\, nor on NetBSD\-1\.5 on i386
Even if it sound like a libthread bug more than a Perl bug\, may be
a skip must be added for this config\.

Here output for debugger&#8203;:

mars&#8203;:\~/perl/perl\-current$ gdb perl t/perl\.core
GNU gdb 5\.0nb1
Copyright 2000 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and you are
welcome to change it and/or distribute copies of it under certain conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for details\.
This GDB was configured as "i386\-\-netbsdelf"\.\.\.\(no debugging symbols found\)\.\.\.
Core was generated by \`perl'\.
Program terminated with signal 11\, Segmentation fault\.
Reading symbols from /usr/libexec/ld\.elf\_so\.\.\.\(no debugging symbols found\)\.\.\.
done\.
Loaded symbols for /usr/libexec/ld\.elf\_so
Reading symbols from /usr/lib/libm387\.so\.0\.\.\.\(no debugging symbols found\)\.\.\.
done\.
Loaded symbols for /usr/lib/libm387\.so\.0
Reading symbols from /usr/lib/libm\.so\.0\.\.\.\(no debugging symbols found\)\.\.\.done\.
Loaded symbols for /usr/lib/libm\.so\.0
Reading symbols from /usr/lib/libcrypt\.so\.0\.\.\.\(no debugging symbols found\)\.\.\.
done\.
Loaded symbols for /usr/lib/libcrypt\.so\.0
Reading symbols from /usr/lib/libutil\.so\.6\.\.\.\(no debugging symbols found\)\.\.\.
done\.
Loaded symbols for /usr/lib/libutil\.so\.6
Reading symbols from /usr/lib/libc\.so\.12\.\.\.\(no debugging symbols found\)\.\.\.done\.
Loaded symbols for /usr/lib/libc\.so\.12
Reading symbols from /usr/lib/libposix\.so\.0\.\.\.\(no debugging symbols found\)\.\.\.
done\.
Loaded symbols for /usr/lib/libposix\.so\.0
Reading symbols from /usr/pkg/lib/libpthread\.so\.14\.\.\.
\(no debugging symbols found\)\.\.\.done\.
Loaded symbols for /usr/pkg/lib/libpthread\.so\.14
Reading symbols from /home/alian/perl/perl\-current/t/\.\./lib/auto/POSIX/POSIX\.so\.\.\.\(no debugging symbols found\)\.\.\.done\.
Loaded symbols for /home/alian/perl/perl\-current/t/\.\./lib/auto/POSIX/POSIX\.so
\#0  0x48226ff2 in pth\_key\_getdata \(\) from /usr/pkg/lib/libpthread\.so\.14
\(gdb\) where
\#0  0x48226ff2 in pth\_key\_getdata \(\) from /usr/pkg/lib/libpthread\.so\.14
\#1  0x4822158a in pthread\_getspecific \(\) from /usr/pkg/lib/libpthread\.so\.14
\#2  0x80b07d0 in Perl\_csighandler \(\)
\#3  0xbfbfdfdc in ?? \(\)
\#4  0x482244ff in \_\_pth\_scheduler \(\) from /usr/pkg/lib/libpthread\.so\.14
\#5  0x48225cc8 in pth\_spawn\_trampoline \(\) from /usr/pkg/lib/libpthread\.so\.14
\#6  0x48223ab1 in pth\_mctx\_set\_bootstrap \(\) from /usr/pkg/lib/libpthread\.so\.14
\#7  0x48223a25 in pth\_mctx\_set\_trampoline \(\) from /usr/pkg/lib/libpthread\.so\.14
\#8  0x815cfa0 in ?? \(\)
\#9  0x1f in ?? \(\)
Cannot access memory at address 0x1f
\(gdb\) quit

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.8.0:

Configured by alian at Wed Jan 29 00:16:13 UTC 2003.

Summary of my perl5 (revision 5.0 version 8 subversion 0) configuration:
  Platform:
    osname=netbsd, osvers=1.6, archname=i386-netbsd-thread-multi
    uname='netbsd mars 1.6 netbsd 1.6 (generic) #0: sun sep 8 19:43:40 utc 2002 autobuild@tgm.daemon.org:autobuildi386objautobuildsrcsysarchi386compilegeneric i386 '
    config_args='-Dcf_email=alian@cpan.org -Dprefix=/usr/local/perl-5.8.0 -Dusethreads -des'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=y, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -I/usr/pkg/include',
    optimize='-O',
    cppflags='-fno-strict-aliasing -I/usr/pkg/include'
    ccversion='', gccversion='2.95.3 20010315 (release) (NetBSD nb3)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -Wl,-rpath,/usr/pkg/lib -Wl,-rpath,/usr/local/lib -L/usr/pkg/lib -L/usr/local/lib'
    libpth=/usr/pkg/lib /usr/local/lib /usr/lib
    libs=-lm -lc -lposix -lcrypt -lutil -lpthread
    perllibs=-lm -lc -lposix -lcrypt -lutil -lpthread
    libc=/usr/lib/libc.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-whole-archive -lgcc -Wl,-no-whole-archive 			-Wl,-E '
    cccdlflags='-DPIC -fPIC ', lddlflags='--whole-archive -shared  -L/usr/pkg/lib -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.0:
    /usr/local/perl-5.8.0/lib/5.8.0/i386-netbsd-thread-multi
    /usr/local/perl-5.8.0/lib/5.8.0
    /usr/local/perl-5.8.0/lib/site_perl/5.8.0/i386-netbsd-thread-multi
    /usr/local/perl-5.8.0/lib/site_perl/5.8.0
    /usr/local/perl-5.8.0/lib/site_perl
    .


Environment for perl v5.8.0:
    HOME=/home/alian
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/alian/bin:/usr/local/perl-5.8.0/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/pkg/bin:/usr/pkg/sbin:/usr/games:/usr/local/bin:/usr/local/sbin
    PERL_BADLANG (unset)
    SHELL=/usr/pkg/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @rgs

Alain \(via RT\) wrote&#8203;:
> I get coredump on blead & 5\.8\.x with \-Duseithreads
> 
> mars&#8203;:\~/perl/perl\-current$ \./perl \-Ilib ext/POSIX/t/posix\.t
> 1\.\.61
> ok 1 \- O\_RDONLY with open
> ok 2 \-     with read
> not ok 3 \-     read to array element \# TODO read to array element not working
> \# Failed at ext/POSIX/t/posix\.t line 40
> \#      got undef
> \# expected 'perl
> \# '
> ok 4
> ok 5 \- POSIX&#8203;::pipe
> ok 6
> ok 7 \- POSIX&#8203;::SigSet\->delset
> ok 8 \- POSIX&#8203;::SigSet\->ismember
> ok 9 \- sigaction SIGHUP
> Segmentation fault \(core dumped\)
> 
> I get this with NetBSD\-1\.6 on i386 & NetBSD\-1\.6\.1 on sparc
> I don't see it on NetBSD\-1\.5\.3 on sparc\, nor on NetBSD\-1\.5 on i386
> Even if it sound like a libthread bug more than a Perl bug\, may be
> a skip must be added for this config\.

Looks like there are already known problems in darwin and freebsd :
I read in posit\.t :

&nbsp;        printf "%s 11 \-   masked SIGINT received %s\\n"\,
&nbsp;          $sigint\_called ? "ok" : "not ok"\,
&nbsp;          \# At least OpenBSD/i386 3\.3 is okay\, as is NetBSD 1\.5\.
&nbsp;          $^O =~ /^\(?&#8203;:darwin|freebsd\)$/ ?
&nbsp;              "\# TODO $^O seems to loose blocked signals"
&nbsp;              : '';

I'll welcome a patch to skip it on NetBSD 1\.6\.\* \(what's
$Config\{osvers\} and $^O ?\)

**Comment by p5pRT** [comment]
### From alian@cpan.org

>>ok 8 \- POSIX&#8203;::SigSet\->ismember
>>ok 9 \- sigaction SIGHUP
>>Segmentation fault \(core dumped\)

> Looks like there are already known problems in darwin and freebsd :
> I read in posit\.t :
> 
>         printf "%s 11 \-   masked SIGINT received %s\\n"\,
>           $sigint\_called ? "ok" : "not ok"\,
>           \# At least OpenBSD/i386 3\.3 is okay\, as is NetBSD 1\.5\.
>           $^O =~ /^\(?&#8203;:darwin|freebsd\)$/ ?
>               "\# TODO $^O seems to loose blocked signals"
>               : '';
> 
> I'll welcome a patch to skip it on NetBSD 1\.6\.\* \(what's
> $Config\{osvers\} and $^O ?\)

mars&#8203;:\~/perl/perl\-current$ uname \-prs
NetBSD 1\.6 i386
mars&#8203;:\~/perl/perl\-current$ \./perl \-Ilib \-MConfig \-e'print $^O\, " \<=> "\, 
$Config\{osvers\}\,"\\n";'
netbsd \<=> 1\.6

centaure&#8203;:\~$ uname \-prs
NetBSD 1\.6\.1 sparc
centaure&#8203;:\~$ perl \-Ilib \-MConfig \-e'print $^O\, " \<=> "\, 
$Config\{osvers\}\,"\\n";'
netbsd \<=> 1\.6\.1

**Comment by p5pRT** [comment]
### From alian@cpan.org

<details><summary>posix-netbsd1.6#23202.patch</summary>

```diff
--- perl-current.old/ext/POSIX/t/posix.t	Sat Aug  2 15:41:50 2003
+++ perl-current/ext/POSIX/t/posix.t	Sat Aug  2 16:14:55 2003
@@ -75,15 +75,22 @@
 	my $action = new POSIX::SigAction 'main::SigHUP', $mask, 0;
 	sigaction(&SIGHUP, $action);
 	$SIG{'INT'} = 'SigINT';
-	kill 'HUP', $$;
+
+	# At least OpenBSD/i386 3.3 is okay, as is NetBSD 1.5.
+	# But not for NetBSD 1.6 & 1.6.1: it crash the test and stop.
+	# So the call of kill must not be done with this config
+	# for be able to finish the test.
+	# For others (darwin & freebsd), let the test fail without
+	# crash.
+	my $todo = ($^O eq 'netbsd' && $Config{osvers}=~/^1\.6\.?/) ?
+                   1 : 0;
+	kill 'HUP', $$ if !$todo;
 	sleep 1;
 
+	$todo = 1 if ($^O =~ /^(?:darwin|freebsd)$/);
         printf "%s 11 -   masked SIGINT received %s\n",
           $sigint_called ? "ok" : "not ok",
-          # At least OpenBSD/i386 3.3 is okay, as is NetBSD 1.5.
-          $^O =~ /^(?:darwin|freebsd)$/ ?
-	      "# TODO $^O seems to loose blocked signals" 
-	      : '';
+          $todo ? "# TODO $^O $Config{osvers} seems to loose blocked signals" : '';
 
 	print "ok 12 - signal masks successful\n";
 	

```
</details>

**Comment by p5pRT** [comment]
### From @schwern

On Sat\, Aug 02\, 2003 at 03&#8203;:17&#8203;:02PM \+0200\, Rafael Garcia\-Suarez wrote&#8203;:
> Looks like there are already known problems in darwin and freebsd :

OS X 10\.2\.6 and recent FreeBSDs seem to be passing this test\.
Maybe it got fixed?


> I read in posit\.t :
> 
>         printf "%s 11 \-   masked SIGINT received %s\\n"\,
>           $sigint\_called ? "ok" : "not ok"\,
>           \# At least OpenBSD/i386 3\.3 is okay\, as is NetBSD 1\.5\.
>           $^O =~ /^\(?&#8203;:darwin|freebsd\)$/ ?
>               "\# TODO $^O seems to loose blocked signals"
>               : '';
> 
> I'll welcome a patch to skip it on NetBSD 1\.6\.\* \(what's
> $Config\{osvers\} and $^O ?\)

\-\- 
We don't know\.  But if we did\, we wouldn't tell you\.

**Comment by p5pRT** [comment]
### From @rgs

Michael G Schwern wrote&#8203;:
> On Sat\, Aug 02\, 2003 at 03&#8203;:17&#8203;:02PM \+0200\, Rafael Garcia\-Suarez wrote&#8203;:
> > Looks like there are already known problems in darwin and freebsd :
> 
> OS X 10\.2\.6 and recent FreeBSDs seem to be passing this test\.
> Maybe it got fixed?

Noticed it already :
http&#8203;://www\.xray\.mpe\.mpg\.de/mailing\-lists/perl5\-porters/2003\-07/msg01503\.html
I can remove the \# TODO mention for MacOS X/10\.2\.6 \-\- just help me to
get $^O and $Config\{osvers\} right\. Looks like osvers="6\.6" for some reason\,
right ?

**Comment by p5pRT** [comment]
### From @schwern

On Sun\, Aug 03\, 2003 at 12&#8203;:02&#8203;:01AM \+0200\, Rafael Garcia\-Suarez wrote&#8203;:
> > OS X 10\.2\.6 and recent FreeBSDs seem to be passing this test\.
> > Maybe it got fixed?
> 
> Noticed it already :
> http&#8203;://www\.xray\.mpe\.mpg\.de/mailing\-lists/perl5\-porters/2003\-07/msg01503\.html
> I can remove the \# TODO mention for MacOS X/10\.2\.6 \-\- just help me to
> get $^O and $Config\{osvers\} right\. Looks like osvers="6\.6" for some reason\,
> right ?

Sounds right\.  Its 6\.6 because that's the Darwin version \#\.  OS X is \+4\.

I also noticed a FreeBSD build getting an Unexpectedly Succeeded\.\.\.
can't find the message now\.


\-\- 
If you can't remember\, the Claymore is pointed at you\.

**Comment by p5pRT** [comment]
### From enache@rdslink.ro

On Sat\, Aug 02\, 2003 a\.d\.\, Michael G Schwern wrote&#8203;:
> On Sun\, Aug 03\, 2003 at 12&#8203;:02&#8203;:01AM \+0200\, Rafael Garcia\-Suarez wrote&#8203;:
> > > OS X 10\.2\.6 and recent FreeBSDs seem to be passing this test\.
> > > Maybe it got fixed?

At least in FreeBSD\, the bug is \_not\_ fixed \(tested with the libc\_r
of today\) and the PR \(49087\) is still open\.

Notice that even if that bug gets eventually fixed \(Anton Berezin
proposed a patch for it\) working it around is not just a matter of
testing the FreeBSD's version&#8203;: when perl is built with other threads
libraries \(libpthread aka KSE\, libthr\, ported linuxthreads\) it
doesn't show up \-\- unfortunately those threads libraries don't
get perl's own threads right \(ext/threads tests either fail or hang\)\.

Considering this\, it's probably a good idea to skip that test
completely on FreeBSD\.

> I also noticed a FreeBSD build getting an Unexpectedly Succeeded\.\.\.
> can't find the message now\.

That's probably the one in ext/Encode/t/enc\_module\.t\.

Regards\,
Adi

**Comment by p5pRT** [comment]
### From @rgs

alian wrote&#8203;:
> >>ok 8 \- POSIX&#8203;::SigSet\->ismember
> >>ok 9 \- sigaction SIGHUP
> >>Segmentation fault \(core dumped\)
> 
> > Looks like there are already known problems in darwin and freebsd :
> > I read in posit\.t :
> > 
> >         printf "%s 11 \-   masked SIGINT received %s\\n"\,
> >           $sigint\_called ? "ok" : "not ok"\,
> >           \# At least OpenBSD/i386 3\.3 is okay\, as is NetBSD 1\.5\.
> >           $^O =~ /^\(?&#8203;:darwin|freebsd\)$/ ?
> >               "\# TODO $^O seems to loose blocked signals"
> >               : '';
> > 
> > I'll welcome a patch to skip it on NetBSD 1\.6\.\* \(what's
> > $Config\{osvers\} and $^O ?\)
> 
> mars&#8203;:\~/perl/perl\-current$ uname \-prs
> NetBSD 1\.6 i386
> mars&#8203;:\~/perl/perl\-current$ \./perl \-Ilib \-MConfig \-e'print $^O\, " \<=> "\, 
> $Config\{osvers\}\,"\\n";'
> netbsd \<=> 1\.6
> 
> centaure&#8203;:\~$ uname \-prs
> NetBSD 1\.6\.1 sparc
> centaure&#8203;:\~$ perl \-Ilib \-MConfig \-e'print $^O\, " \<=> "\, 
> $Config\{osvers\}\,"\\n";'
> netbsd \<=> 1\.6\.1

Merci\, appliqué \(\#20461\)\.

**Comment by p5pRT** [comment]
@rgs - Status changed from 'new' to 'resolved'

**Comment by p5pRT** [comment]
### From alian@cpan.org

Rafael Garcia\-Suarez via RT wrote&#8203;:
> According to our records\, your request regarding 
>   "coredump on ext/POSIX/t/posix with NetBSD\-1\.6" 
> has been resolved\. 

Ok the test no longer crash\, but it miss two tests&#8203;:

\.\.\.
ok 5 \- POSIX&#8203;::pipe
ok 6
ok 7 \- POSIX&#8203;::SigSet\->delset
ok 8 \- POSIX&#8203;::SigSet\->ismember
not ok 11 \-   masked SIGINT received \# TODO netbsd 1\.6 seems to loose 
blocked signals
ok 12 \- signal masks successful
ok 13 \- The minimum allowed values according to susv2
ok 14 \- getcwd
\.\.\.

no test 9 & 10\. Attached patch for correct this\, else test will be see 
as fail\.

Here the output now&#8203;:
1\.\.61
ok 1 \- O\_RDONLY with open
ok 2 \-     with read
not ok 3 \-     read to array element \# TODO read to array element not 
working
\# Failed at ext/POSIX/t/posix\.t line 40
\#      got undef
\# expected 'perl
\# '
ok 4
ok 5 \- POSIX&#8203;::pipe
ok 6
ok 7 \- POSIX&#8203;::SigSet\->delset
ok 8 \- POSIX&#8203;::SigSet\->ismember
not ok 9 \- sigaction SIGHUP \# TODO netbsd 1\.6 seems to loose blocked signals
not ok 10 \- sig mask delayed SIGINT \# TODO netbsd 1\.6 seems to loose 
blocked signals
not ok 11 \- masked SIGINT received \# TODO netbsd 1\.6 seems to loose 
blocked signals
ok 12 \- signal masks successful
ok 13 \- The minimum allowed values according to susv2
ok 14 \- getcwd
ok 15 \- strtod works
ok 16 \- strtol\(\) number
ok 17 \-          unparsed chars
ok 18 \- strtoul\(\) number
ok 19 \-           unparsed chars
ok 20 \- dynamic loading
ok 21 \# 10&#8203;:08\, on 08/05/03
ok 22 \- validating mini\_mktime\(\) and strftime\(\)&#8203;: Wed Feb 28 00&#8203;:00&#8203;:00 
1996 059
ok 23 \- validating mini\_mktime\(\) and strftime\(\)&#8203;: Thu Feb 29 00&#8203;:00&#8203;:60 
1996 060
ok 24 \- validating mini\_mktime\(\) and strftime\(\)&#8203;: Fri Mar 01 00&#8203;:00&#8203;:00 
1996 061
ok 25 \- validating mini\_mktime\(\) and strftime\(\)&#8203;: Sun Feb 28 00&#8203;:00&#8203;:00 
1999 059
ok 26 \- validating mini\_mktime\(\) and strftime\(\)&#8203;: Mon Mar 01 00&#8203;:00&#8203;:00 
1999 060
ok 27 \- validating mini\_mktime\(\) and strftime\(\)&#8203;: Mon Feb 28 00&#8203;:00&#8203;:00 
2000 059
ok 28 \- validating mini\_mktime\(\) and strftime\(\)&#8203;: Tue Feb 29 00&#8203;:00&#8203;:00 
2000 060
ok 29 \- validating mini\_mktime\(\) and strftime\(\)&#8203;: Wed Mar 01 00&#8203;:00&#8203;:00 
2000 061
ok 30 \- validating mini\_mktime\(\) and strftime\(\)&#8203;: Fri Mar 31 00&#8203;:00&#8203;:00 
2000 091
ok 31 \- autoloading and errno\(\) mix
ok 32 \- autoloading and errno\(\) mix
ok 33 \- check we have CORE&#8203;::kill
ok 34 \- we should now have POSIX&#8203;::kill
ok 35 \- check its usage message
ok 36 \- offsetof should fail
ok 37 \- check its unimplemented message
ok 38 \- fgets should fail
ok 39 \- check its redef message
ok 40 \- isalnum
ok 41 \- isalnum
ok 42 \- isalpha
ok 43 \- isalpha
ok 44 \- iscntrl
ok 45 \- iscntrl
ok 46 \- isdigit
ok 47 \- isdigit
ok 48 \- isgraph
ok 49 \- isgraph
ok 50 \- islower
ok 51 \- islower
ok 52 \- isupper
ok 53 \- isupper
ok 54 \- isprint
ok 55 \- isprint
ok 56 \- ispunct
ok 57 \- ispunct
ok 58 \- isspace
ok 59 \- isspace
ok 60 \- isxdigit
ok 61 \- isxdigit

**Comment by p5pRT** [comment]
### From alian@cpan.org

<details><summary>posix-netbsd1.6#23202-2.patch</summary>

```diff
--- posix.t	Tue Aug  5 12:09:13 2003
+++ perl-current/ext/POSIX/t/posix.t	Tue Aug  5 12:08:46 2003
@@ -82,15 +82,20 @@
 	# finish the test.
 	# For others (darwin & freebsd), let the test fail without crashing.
 	my $todo = $^O eq 'netbsd' && $Config{osvers}=~/^1\.6/;
-	kill 'HUP', $$ if !$todo;
+	my $why_todo = "# TODO $^O $Config{osvers} seems to loose blocked signals";
+	if (!$todo) { 
+	  kill 'HUP', $$; 
+	} else {
+	  print "not ok 9 - sigaction SIGHUP ",$why_todo,"\n";
+	  print "not ok 10 - sig mask delayed SIGINT ",$why_todo,"\n";
+	}
 	sleep 1;
 
 	$todo = 1 if ($^O eq 'freebsd')
 		  || ($^O eq 'darwin' && $Config{osvers} lt '6.6');
-	printf "%s 11 -   masked SIGINT received %s\n",
+	printf "%s 11 - masked SIGINT received %s\n",
 	    $sigint_called ? "ok" : "not ok",
-	    $todo ? "# TODO $^O $Config{osvers} seems to loose blocked signals"
-	    : '';
+	    $todo ? $why_todo : '';
 
 	print "ok 12 - signal masks successful\n";
 	

```
</details>

**Comment by p5pRT** [comment]
### From @rgs

This latest patch being applied as \#20495\, => resolved\.

**Comment by p5pRT** [comment]
@rgs - Status changed from 'open' to 'resolved'
