### ISSUE TITLE
5.8.1-RC4: Cannot eval a large string under -Dusemymalloc

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6678]
Migrated from [rt.perl.org#23214](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=23214) (status was 'resolved')

Searchable as RT23214$

**Comment by p5pRT** [comment]
### From stephenc@localhost.localdomain

#### Created by stephenc@localhost.localdomain



Attempting to eval a very large string in a perl built with with \-Dusemymalloc
causes what appears to be some memory corruption\, and perl freezes attempting to
allocate a ludicrious amount of memory\.  The problem does not occur when using
the system malloc \(\-Uusemymalloc\)\.

I noticed the problem trying to reconstitute the output of Data&#8203;::Dumper on a 
very large complex hash\.  This very short snippet\, however\, reproduces it
consistently&#8203;:

&nbsp;   my $foo = qq\{print "hello world\\n"\} x 100000;
&nbsp;   eval $foo;

A backtrace at the point it freezes&#8203;:

0x4003c025 in Perl\_mfree \(mp=0x8a66800\) at malloc\.c&#8203;:1344
1344            \*lp\+\+ = lfill;
\(gdb\) bt
\#0  0x4003c025 in Perl\_mfree \(mp=0x8a66800\) at malloc\.c&#8203;:1344
\#1  0x4003c671 in Perl\_realloc \(mp=0x8865808\, nbytes=143022088\) at malloc\.c&#8203;:2291
\#2  0x40068c3c in S\_scan\_str \(
&nbsp;    start=0x89b28f0
"��������������������������������������������������"\.\.\.\,
&nbsp;    keep\_quoted=0\, keep\_delims=0\) at toke\.c&#8203;:7163
\#3  0x400596f3 in Perl\_yylex \(\) at toke\.c&#8203;:3683
\#4  0x400708da in Perl\_yyparse \(\) at perly\.c&#8203;:1470
\#5  0x400dda09 in S\_doeval \(gimme=128\, startop=0x0\, outside=0x804d2cc\,
seq=144386292\) at pp\_ctl\.c&#8203;:2802
\#6  0x400df87c in Perl\_pp\_entereval \(\) at pp\_ctl\.c&#8203;:3398
\#7  0x40095dd1 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1434
\#8  0x400361cf in S\_run\_body \(oldscope=144386292\) at perl\.c&#8203;:1827
\#9  0x40035e6e in perl\_run \(my\_perl=0x804b588\) at perl\.c&#8203;:1746
\#10 0x0804923a in main \(env=0xbfffea10\) at perlmain\.c&#8203;:86
\#11 0x420158f7 in \_\_libc\_start\_main \(\) from /lib/i686/libc\.so\.6

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl v5.8.1:

Configured by stephenc at Fri Aug  1 17:12:39 CDT 2003.

Summary of my perl5 (revision 5.0 version 8 subversion 1) configuration:
  Platform:
    osname=linux, osvers=2.4.20-19.8, archname=i686-linux
    uname='linux stephenc.theiqgroup.com 2.4.20-19.8 #1 tue jul 15 15:25:37 edt 2003 i686 i686 i386 gnulinux '
    config_args='-des -Dprefix=/opt/perl -Dinstallprefix=/opt/perl -Dvendorprefix=/opt/perl -Dsiteprefix=/opt/perl -Dmyhostname=localhost -Dperladmin=root@localhost -Dcf_by=IQG-SPC -Dcc=gcc -Doptimize=-O3 -march=i686 -mcpu=i686 -ggdb3 -Duseshrplib -Duseperlio -Dusemymalloc'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=y, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-DDEBUGGING -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O3 -march=i686 -mcpu=i686 -ggdb3',
    cppflags='-DDEBUGGING -fno-strict-aliasing'
    ccversion='', gccversion='3.2 20020903 (Red Hat Linux 8.0 3.2-7)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/libc-2.3.2.so, so=so, useshrplib=true, libperl=libperl.so
    gnulibc_version='2.3.2'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic -Wl,-rpath,/opt/perl/lib/5.8.1/i686-linux/CORE'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    RC4


@INC for perl v5.8.1:
    /opt/perl/lib/5.8.1/i686-linux
    /opt/perl/lib/5.8.1
    /opt/perl/lib/site_perl/5.8.1/i686-linux
    /opt/perl/lib/site_perl/5.8.1
    /opt/perl/lib/site_perl
    /opt/perl/lib/vendor_perl/5.8.1/i686-linux
    /opt/perl/lib/vendor_perl/5.8.1
    /opt/perl/lib/vendor_perl
    .


Environment for perl v5.8.1:
    HOME=/home/stephenc
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/stephenc/bin/*/bin:/home/stephenc/bin:/home/stephenc/perlbin:/opt/perl/bin:/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:/usr/jdk1.2/bin:/opt/oracle/bin:/opt/apache/bin:/opt/subversion/bin:/home/stephenc/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @TJC

This bug has been fixed as of 5\.10\.0\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@TJC - Status changed from 'open' to 'resolved'
