### ISSUE TITLE
segfault in untie

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6697]
Migrated from [rt.perl.org#23287](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=23287) (status was 'resolved')

Searchable as RT23287$

**Comment by p5pRT** [comment]
### From @mauke

#### Created by .lmai@web.de



Greetings\!

\#\!perl
use warnings;
use strict;

sub TIESCALAR \{
&nbsp;    bless $\_\[1\]\, $\_\[0\];
\}

my $var;
tie $var\, 'main'\, \\$var;
untie $var;
\_\_END\_\_

This program segfaults\.

gdb says&#8203;:
\#0  0x081063ed in Perl\_pp\_untie \(\) at pp\_sys\.c&#8203;:855
855             SV \*obj = SvRV\(mg\->mg\_obj\);
\(gdb\) bt
\#0  0x081063ed in Perl\_pp\_untie \(\) at pp\_sys\.c&#8203;:855
\#1  0x080b0944 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1398
\#2  0x080618e9 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1681
\#3  0x080614b5 in perl\_run \(my\_perl=0x816ef08\) at perl\.c&#8203;:1600
\#4  0x0805df9b in main \(argc=2\, argv=0xbffff7c4\, env=0xbffff7d0\)
&nbsp;    at perlmain\.c&#8203;:85
\#5  0x40078baf in \_\_libc\_start\_main \(\) from /lib/libc\.so\.6
\(gdb\) p mg
$1 = \(struct magic \*\) 0x8180b48
\(gdb\) p mg\->mg\_obj
$2 = \(struct sv \*\) 0x0

HTH
Lukas Mai

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl v5.8.0:

Configured by lmai at Mon Aug 11 21:55:49 CEST 2003.

Summary of my perl5 (revision 5.0 version 8 subversion 0) configuration:
  Platform:
    osname=linux, osvers=2.2.18, archname=i686-linux-64int-ld
    uname='linux barubary 2.2.18 #1 fri jan 19 22:10:35 gmt 2001 i686 unknown '
    config_args=''
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=define use64bitall=undef uselongdouble=define
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-DDEBUGGING -fno-strict-aliasing -pipe -D_LARGEFILE_SOURCE -
D_FILE_OFFSET_BITS=64',
    optimize='-g',
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe'
    ccversion='', gccversion='3.1', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long long', ivsize=8, nvtype='long double', nvsize=12, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lndbm -lgdbm -ldbm -ldl -lm -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lcrypt -lutil
    libc=, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.2'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:



@INC for perl v5.8.0:
    perl-5.8.0/lib/
    /usr/local/lib/perl5/5.8.0/i686-linux-64int-ld
    /usr/local/lib/perl5/5.8.0
    /usr/local/lib/perl5/site_perl/5.8.0/i686-linux-64int-ld
    /usr/local/lib/perl5/site_perl/5.8.0
    /usr/local/lib/perl5/site_perl/5.6.1
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.8.0:
    HOME=/home/lmai
    LANG=en_US
    LANGUAGE (unset)
    LC_COLLATE=POSIX
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)

PATH=/home/lmai/bin:/usr/local/bin:/usr/bin:/usr/X11R6/bin:/bin:/usr/lib/java/bin:/var/lib/dosemu:/usr/games
/bin:/usr/games:/opt/gnome/bin:/opt/kde2/bin:/opt/kde/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash


```
</details>

**Comment by p5pRT** [comment]
### From @schwern

On Tue\, Aug 12\, 2003 at 01&#8203;:25&#8203;:24AM \-0000\, Lukas Mai wrote&#8203;:
> \#\!perl
> use warnings;
> use strict;
> 
> sub TIESCALAR \{
>     bless $\_\[1\]\, $\_\[0\];
> \}
> 
> my $var;
> tie $var\, 'main'\, \\$var;
> untie $var;
> \_\_END\_\_
> 
> This program segfaults\.

This problem still exists in 5\.8\.1 RC4 and bleadperl@&#8203;20566


\-\- 
Michael G Schwern        schwern@&#8203;pobox\.com  http&#8203;://www\.pobox\.com/~schwern/
"I might even owe you an apology\."
"That would be nice\."
"On the other hand\, I thought that I was right\."
&nbsp;        \-\- "The Courts Of Chaos"\, Roger Zelazny

**Comment by p5pRT** [comment]
### From @andk

>>>>> On Mon\, 11 Aug 2003 23&#8203;:21&#8203;:12 \-0700\, Michael G Schwern \<schwern@&#8203;pobox\.com> said&#8203;:

&nbsp;  > This problem still exists in 5\.8\.1 RC4 and bleadperl@&#8203;20566

But it seemed already fixed in 16500\. With 16501 it started
segfaulting\.



\-\-\-\-Program\-\-\-\-
\#\!perl
use warnings;
use strict;

sub TIESCALAR \{
&nbsp;    bless $\_\[1\]\, $\_\[0\];
\}

my $var;
tie $var\, 'main'\, \\$var;
untie $var;
\_\_END\_\_

\-\-\-\-Output of \.\.\./pEk5Awc/perl\-5\.7\.3@&#8203;16500/bin/perl\-\-\-\-
untie attempted while 1 inner references still exist at tests/lokasmai\-tie\.pl li
ne 11\.

\-\-\-\-EOF \($?='0'\)\-\-\-\-
\-\-\-\-Output of \.\.\./pcLXNIc/perl\-5\.7\.3@&#8203;16501/bin/perl\-\-\-\-

\-\-\-\-EOF \($?='11'\)\-\-\-\-

\-\- 
andreas

**Comment by p5pRT** [comment]
### From @rgs

Fixed \(or hidden\) by change 20630\.

**Comment by p5pRT** [comment]
@rgs - Status changed from 'new' to 'resolved'

**Comment by p5pRT** [comment]
### From @ysth

On Tue\, 12 Aug 2003 12&#8203;:48&#8203;:49 \+0200\, andreas\.koenig@&#8203;anima\.de wrote&#8203;:
>>>>>> On Mon\, 11 Aug 2003 23&#8203;:21&#8203;:12 \-0700\, Michael G Schwern \<schwern@&#8203;pobox\.com> said&#8203;:
>
>  > This problem still exists in 5\.8\.1 RC4 and bleadperl@&#8203;20566
>
>But it seemed already fixed in 16500\. With 16501 it started
>segfaulting\.

IIRC\, 16501 was a bad patch and got retracted\.  Can you make your binsearch
skip anything from there up to 16885?

**Comment by p5pRT** [comment]
### From @ysth

On Tue\, 12 Aug 2003\, Yitzchak Scott\-Thoennes wrote&#8203;:

> On Tue\, 12 Aug 2003 12&#8203;:48&#8203;:49 \+0200\, andreas\.koenig@&#8203;anima\.de wrote&#8203;:
> >>>>>> On Mon\, 11 Aug 2003 23&#8203;:21&#8203;:12 \-0700\, Michael G Schwern \<schwern@&#8203;pobox\.com> said&#8203;:
> >
> >  > This problem still exists in 5\.8\.1 RC4 and bleadperl@&#8203;20566
> >
> >But it seemed already fixed in 16500\. With 16501 it started
> >segfaulting\.
>
> IIRC\, 16501 was a bad patch and got retracted\.  Can you make your binsearch
> skip anything from there up to 16885?

I can't build a perl or run tests at the moment\, but it looks like
something like this is needed \(plus tie\.t change\)&#8203;:

<details><summary>Inline Patch</summary>

```diff
--- pp_sys.c.orig	2003-07-01 05:34:10.000000000 -0700
+++ pp_sys.c	2003-08-12 10:27:42.000000000 -0700
@@ -861,7 +861,7 @@ PP(pp_untie)
 	RETPUSHYES;

     if ((mg = SvTIED_mg(sv, how))) {
-	SV *obj = SvRV(mg->mg_obj);
+	SV *obj = SvRV(SvTIED_obj(sv, mg));
 	GV *gv;
 	CV *cv = NULL;
         if (obj) {
End of Patch.A
```
</details>

**Comment by p5pRT** [comment]
### From @andk

>>>>> On Tue\, 12 Aug 2003 10&#8203;:10&#8203;:40 \-0700\, sthoenna@&#8203;efn\.org \(Yitzchak Scott\-Thoennes\) said&#8203;:

&nbsp;  > On Tue\, 12 Aug 2003 12&#8203;:48&#8203;:49 \+0200\, andreas\.koenig@&#8203;anima\.de wrote&#8203;:
 >>>>>>> On Mon\, 11 Aug 2003 23&#8203;:21&#8203;:12 \-0700\, Michael G Schwern \<schwern@&#8203;pobox\.com> said&#8203;:
 >> 
 >> > This problem still exists in 5\.8\.1 RC4 and bleadperl@&#8203;20566
 >> 
 >> But it seemed already fixed in 16500\. With 16501 it started
 >> segfaulting\.

&nbsp;  > IIRC\, 16501 was a bad patch and got retracted\.  Can you make your binsearch
&nbsp;  > skip anything from there up to 16885?

I'm sorry for the incomplete analysis\, I'll have to keep more perls
lying around to notice the number of turning points\.

Executive summary&#8203;:

16501 broke it\, 16810 fixed it\, 16845 changed the output\, 16885 broke
it\, 20630 fixed it\. 20630 looks similar to your patch of yesterday\.

Full story&#8203;:

\-\-\-\-Output of \.\.\./pOXlfn5/perl\-5\.7\.3@&#8203;16500/bin/perl\-\-\-\-
untie attempted while 1 inner references still exist at tests/lokasmai\-tie\.pl line 11\.

\-\-\-\-EOF \($?='0'\)\-\-\-\-
\-\-\-\-Output of \.\.\./pKU5aUv/perl\-5\.7\.3@&#8203;16501/bin/perl\-\-\-\-

\-\-\-\-EOF \($?='11'\)\-\-\-\-
\-\-\-\-Output of \.\.\./pItCm1U/perl\-5\.7\.3@&#8203;16807/bin/perl\-\-\-\-

\-\-\-\-EOF \($?='11'\)\-\-\-\-
\-\-\-\-Output of \.\.\./pf6fECO/perl\-5\.7\.3@&#8203;16810/bin/perl\-\-\-\-

\-\-\-\-EOF \($?='0'\)\-\-\-\-
\-\-\-\-Output of \.\.\./pbs7lwx/perl\-5\.7\.3@&#8203;16843/bin/perl\-\-\-\-

\-\-\-\-EOF \($?='0'\)\-\-\-\-
\-\-\-\-Output of \.\.\./pCPNlVj/perl\-5\.7\.3@&#8203;16845/bin/perl\-\-\-\-
untie attempted while 1 inner references still exist at tests/lokasmai\-tie\.pl line 11\.

\-\-\-\-EOF \($?='0'\)\-\-\-\-
\-\-\-\-Output of \.\.\./pLnHOCT/perl\-5\.7\.3@&#8203;16884/bin/perl\-\-\-\-
untie attempted while 1 inner references still exist at tests/lokasmai\-tie\.pl line 11\.

\-\-\-\-EOF \($?='0'\)\-\-\-\-
\-\-\-\-Output of \.\.\./pMCCktt/perl\-5\.7\.3@&#8203;16885/bin/perl\-\-\-\-

\-\-\-\-EOF \($?='11'\)\-\-\-\-
\-\-\-\-Output of \.\.\./pSeZUuC/perl\-5\.8\.0@&#8203;20629/bin/perl\-\-\-\-

\-\-\-\-EOF \($?='11'\)\-\-\-\-
\-\-\-\-Output of \.\.\./pYyiDiO/perl\-5\.8\.0@&#8203;20630/bin/perl\-\-\-\-

\-\-\-\-EOF \($?='0'\)\-\-\-\-



\-\- 
andreas

**Comment by p5pRT** [comment]
### From @rgs

Resolved by change 20660

**Comment by p5pRT** [comment]
@rgs - Status changed from 'open' to 'resolved'
