### ISSUE TITLE
threads async segfaults (5.8.1)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6827]
Migrated from [rt.perl.org#24165](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=24165) (status was 'resolved')

Searchable as RT24165$

**Comment by p5pRT** [comment]
### From mjp-perl@pilcrow.madison.wi.us

#### Created by perlbuild@box.securepipe.com



With async\-spawned threads\, combinations of $thr\->tid\(\) and $thr\->join\(\)
can cause segfaults&#8203;:

&nbsp;  \# tid\, \<delay>\, join
&nbsp;  \#
&nbsp;  $ perl \-Mthreads \-le '$t = async \{1;\}; $t\->tid; sleep 2; $\_\->join for threads\->list;'
&nbsp;  Segmentation fault

&nbsp;  \# tid\, join\, tid
&nbsp;  \#
&nbsp;  $ perl \-Mthreads \-le '$t = async \{1;\}; $t\->tid; $t\->join; $t\->tid;'
&nbsp;  Segmentation fault

&nbsp;  \# tid\, join\, tid\, join
&nbsp;  \#
&nbsp;  $ perl \-Mthreads \-le '$t = async \{1;\}; $t\->join; $t\->tid; $t\->join; $t\->tid'
&nbsp;  Thread already joined at \-e line 1\.
&nbsp;  Segmentation fault

This does \_not\_ happen if the threads are \_not\_ created via async\{\}\.  That is\,
"threads\->create\(sub \{1;\}\) \.\.\." in the above examples does not segfault\.
FWIW\, \(abbreviated\) ltrace puts the SEGV in perl\_destruct&#8203;:

&nbsp;  \.\.\.
&nbsp;  perl\_run
&nbsp;  SIGRTMIN
&nbsp;  SIGRTMIN
&nbsp;  "Thread already joined at \-e line 1\."
&nbsp;  \<\.\.\. perl\_run resumed>
&nbsp;  perl\_destruct         \<\-\-\- async\{\} examples SEGV here\, new/create continue
&nbsp;  perl\_free
&nbsp;  pthread\_mutex\_destroy
&nbsp;  exit

\(perl\-5\.8\.0\-55 from Redhat's Rawhide 3\.2\-5 does not segfault with the
above async\{\} examples\.\)

<details><summary>Perl Info</summary>

```

Flags:
    category=library
    severity=medium

Site configuration information for perl v5.8.1:

Configured by mjp at Fri Sep 26 09:06:03 CDT 2003.

Summary of my perl5 (revision 5.0 version 8 subversion 1) configuration:
  Platform:
    osname=linux, osvers=2.4.20-19.7, archname=i686-linux-thread-multi
    uname='linux box.securepipe.com 2.4.20-19.7 #1 tue jul 15 13:44:14 edt 2003 i686 unknown '
    config_args='-dse'
    hint=previous, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm',
    optimize='-O2',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -fno-strict-aliasing -I/usr/local/include -I/usr/include/gdbm -D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm'
    ccversion='', gccversion='2.96 20000731 (Red Hat Linux 7.3 2.96-113)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lndbm -lgdbm -ldl -lm -lcrypt -lutil -lpthread -lc
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
    libc=/lib/libc-2.2.5.so, so=so, useshrplib=true, libperl=libperl.so
    gnulibc_version='2.2.5'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic -Wl,-rpath,/home/mjp/opt/lib/perl5/5.8.1/i686-linux-thread-multi/CORE'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.1:
    /home/mjp/opt/lib/perl5/5.8.1/i686-linux-thread-multi
    /home/mjp/opt/lib/perl5/5.8.1
    /home/mjp/opt/lib/perl5/site_perl/5.8.1/i686-linux-thread-multi
    /home/mjp/opt/lib/perl5/site_perl/5.8.1
    /home/mjp/opt/lib/perl5/site_perl
    .


Environment for perl v5.8.1:
    HOME=/home/mjp
    LANG=en_US.iso885915
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/mjp/opt/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/home/mjp/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @lizmat

At 05&#8203;:04 \+0000 10/9/03\, Michael J\.Pomraning \(via RT\) wrote&#8203;:
>\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
>\[Please enter your report here\]
>
>With async\-spawned threads\, combinations of $thr\->tid\(\) and $thr\->join\(\)
>can cause segfaults&#8203;:
>
>   \# tid\, \<delay>\, join
>   \#
>   $ perl \-Mthreads \-le '$t = async \{1;\}; $t\->tid; sleep 2; $\_\->join 
>for threads\->list;'
>   Segmentation fault

Bombs on Mac OS X as well\.  A stack trace&#8203;:

\#0  0x080a59f0 in Perl\_pad\_swipe \(my\_perl=0x81acba0\, po=13\, refadjust=1 '\\001'\)
&nbsp;     at pad\.c&#8203;:1002
\#1  0x0809209a in Perl\_op\_clear \(my\_perl=0x81acba0\, o=0x81f5ab8\) at op\.c&#8203;:378
\#2  0x08091f2d in Perl\_op\_free \(my\_perl=0x81acba0\, o=0x81f5ab8\) at op\.c&#8203;:324
\#3  0x08091ecc in Perl\_op\_free \(my\_perl=0x81acba0\, o=0x81f5b50\) at op\.c&#8203;:312
\#4  0x08091ecc in Perl\_op\_free \(my\_perl=0x81acba0\, o=0x81adee0\) at op\.c&#8203;:312
\#5  0x0806192c in perl\_destruct \(my\_perl=0x81acba0\) at perl\.c&#8203;:470
\#6  0x400196a7 in Perl\_ithread\_destruct \(my\_perl=0x8192878\, thread=0x81aaa80\,
&nbsp;     why=0x4001bef6 "no reference"\) at threads\.xs&#8203;:146
\#7  0x40019a01 in ithread\_mg\_free \(my\_perl=0x8192878\, sv=0x819339c\,
&nbsp;     mg=0x8232fb8\) at threads\.xs&#8203;:217
\#8  0x080e878c in Perl\_sv\_unmagic \(my\_perl=0x8192878\, sv=0x819339c\, type=110\)
&nbsp;     at sv\.c&#8203;:4808
\#9  0x4001aa76 in Perl\_ithread\_DESTROY \(my\_perl=0x8192878\, sv=0x81f4354\)
&nbsp;     at threads\.xs&#8203;:621
\#10 0x4001b713 in XS\_threads\_DESTROY \(my\_perl=0x8192878\, cv=0x81ac8d4\)
&nbsp;     at threads\.c&#8203;:797
\#11 0x080dde5e in Perl\_pp\_entersub \(my\_perl=0x8192878\) at pp\_hot\.c&#8203;:2817
\#12 0x08065c79 in S\_call\_body \(my\_perl=0x8192878\, myop=0xbfffedd0\, is\_eval=0\)
&nbsp;     at perl\.c&#8203;:2190
\#13 0x08065808 in Perl\_call\_sv \(my\_perl=0x8192878\, sv=0x81ac8d4\, flags=150\)
&nbsp;     at perl\.c&#8203;:2111
\#14 0x080e9477 in Perl\_sv\_clear \(my\_perl=0x8192878\, sv=0x819339c\) at sv\.c&#8203;:5095
\#15 0x080e9e0c in Perl\_sv\_free \(my\_perl=0x8192878\, sv=0x819339c\) at sv\.c&#8203;:5339
\#16 0x080df5c7 in do\_clean\_objs \(my\_perl=0x8192878\, sv=0x81a7350\) at sv\.c&#8203;:385
\#17 0x080df46c in S\_visit \(my\_perl=0x8192878\, f=0x80df4e9 \<do\_clean\_objs>\)
&nbsp;     at sv\.c&#8203;:331
\#18 0x080df767 in Perl\_sv\_clean\_objs \(my\_perl=0x8192878\) at sv\.c&#8203;:424
\#19 0x080619ad in perl\_destruct \(my\_perl=0x8192878\) at perl\.c&#8203;:492
\#20 0x0805fbdc in main \(argc=4\, argv=0xbffff064\, env=0xbffff078\)
&nbsp;     at perlmain\.c&#8203;:88



>   \# tid\, join\, tid
>   \#
>   $ perl \-Mthreads \-le '$t = async \{1;\}; $t\->tid; $t\->join; $t\->tid;'
>   Segmentation fault

Can't get this to bomb on Mac OS X\.  Same backtrace as above\.


>   \# tid\, join\, tid\, join
>   \#
>   $ perl \-Mthreads \-le '$t = async \{1;\}; $t\->join; $t\->tid; $t\->join; $t\->tid'
>   Thread already joined at \-e line 1\.
>   Segmentation fault

Also bombs with Mac OS X\.  Same tracktrace\.

Oddly enough these segfault also with Valgrind\.  the resulting core 
dump is Perl's though \(still looking at what is going on there\, if I 
know more I'll report\)



Liz

**Comment by p5pRT** [comment]
### From @lizmat

At 05&#8203;:04 \+0000 10/9/03\, Michael J\.Pomraning \(via RT\) wrote&#8203;:
>This does \_not\_ happen if the threads are \_not\_ created via async\{\}\.  That is\,
>"threads\->create\(sub \{1;\}\) \.\.\." in the above examples does not segfault\.
>FWIW\, \(abbreviated\) ltrace puts the SEGV in perl\_destruct&#8203;:

Based on this observation\, I changed "async" in threads\.pm from&#8203;:

&nbsp;   sub async \(&;@&#8203;\) \{
&nbsp;       my $cref = shift;
&nbsp;       return threads\->new\($cref\,@&#8203;\_\);
&nbsp;   \}

to&#8203;:

&nbsp;   sub async \(&;@&#8203;\) \{threads\->new\( @&#8203;\_ \)\}   \# also segfaults

&nbsp;   sub async \(&;@&#8203;\) \{new\( 'threads'\,@&#8203;\_ \)\}   \# also segfaults

&nbsp;   sub async \(&;@&#8203;\) \{unshift @&#8203;\_\,'threads'; goto &new\}   \# doesn't segfault\!

The reason behind this last change would be to make the environment 
of async to be exactly like that of new/create \(by removing the extra 
entry for "asunc" from the call stack altogether\)\.  With this last 
change\, I can't get it to segfault anymore\.  And all the 5\.8\.1 
threads tests pass\.


This means that it would in principle be possible to issue a new 
version of threads\.pm to CPAN to fix this problem\.


Liz

**Comment by p5pRT** [comment]
### From @iabyn

On Fri\, Oct 10\, 2003 at 10&#8203;:46&#8203;:17PM \+0200\, Elizabeth Mattijsen wrote&#8203;:
> At 23&#8203;:35 \+0300 10/10/03\, Enache Adrian wrote&#8203;:
> >On Sat\, Oct 11\, 2003 a\.d\.\, Abhijit Menon\-Sen wrote&#8203;:
> >> At 2003\-10\-10 16&#8203;:37&#8203;:55 \+0200\, liz@&#8203;dijkmat\.nl wrote&#8203;:
> >> >
> >> > This patch for now fixes the problem of segfaulting when using async\(\)
> >> > in 5\.8\.1\.
> >>
> > > Thanks\, applied\. \(\#21436\)
> >However\, please don't close the ticket\. The bug is still there and
> >should be fixed :\-\)
> >$ perl \-Mthreads \-e 'sub a\{threads\->new\(shift\)\} $t = a sub\{\}; 
> >$t\->tid; $t\->join; $t\->tid'
> >Segmentation fault
> 
> Indeed\, which was implied by my "for now"\.  It's a workaround for the 
> async problem\.
> 
> Looking at the stack trace \(which I posted yesterday to p5p\)\, I think 
> the problem is pad related\.  And since there have been pad related 
> fixes between 5\.8\.0 and 5\.8\.1\, I think we need to look for the final 
> fix of the problem there\.  But that is defenitely out of my league\.

The problem is that when threads call perl\_destruct\(\)\, PL\_comppad and
PL\_curpad point to the pad of the CV from where they were created\, rather
than to the pad of PL\_main\_cv\. When the last thread exits\, PL\_main\_root
is freed\, and coredumps occur as op\_free\(\) tries to do things with the pad
slots pointed to by various ops\.

In this particular case\, when the main program exits it calls
perl\_destruct\(\)\, which decrements the refcount of PL\_main\_root; it then
frees $t\, which invokes perl\_destruct\(\) on the \(previously joined\) child
thread\, which then causes PL\_main\_root to be freed while PL\_comppad
points to the wrong place\.

The following patch\, applied as \#21470\, fixes the immediate problem \(\*\)\.

I must confess that I was suprised to find that perl\_destruct isn't
called on behalf of a thread immediately after it is joined\, but rather
only after the thread ref is freed\.

Dave\.

\(\*\) Whoo hoo\, my first commit :\-\)

\-\- 
Please note that ash\-trays are provided for the use of smokers\,
whereas the floor is provided for the use of all patrons\.
&nbsp;    \- Bill Royston


Change 21470 by davem@&#8203;davem\-percy on 2003/10/16 20&#8203;:03&#8203;:44

&nbsp;    Ensure PL\_comppad/curpad point to PL\_main\_cv's padlist when
&nbsp;    PL\_main\_root is freed; this may not have been be the case if a
&nbsp;    thread other than the main one is the last to be destroyed

Affected files \.\.\.

\.\.\. //depot/perl/ext/threads/t/thread\.t\#10 edit
\.\.\. //depot/perl/pad\.h\#9 edit
\.\.\. //depot/perl/perl\.c\#526 edit

Differences \.\.\.

==== //depot/perl/ext/threads/t/thread\.t\#10 \(text\) ====

@&#8203;@&#8203; \-12\,7 \+12\,7 @&#8203;@&#8203;
 
 use ExtUtils&#8203;::testlib;
 use strict;
\-BEGIN \{ $| = 1; print "1\.\.25\\n" \};
\+BEGIN \{ $| = 1; print "1\.\.26\\n" \};
 use threads;
 use threads&#8203;::shared;
 
@&#8203;@&#8203; \-153\,5 \+153\,10 @&#8203;@&#8203;
&nbsp;     ok\(\(keys %rand == 25\)\, "Check that rand works after a new thread"\);
 \}
 
\+\# bugid \#24165
\+
\+run\_perl\(prog =>
\+    'use threads; sub a\{threads\->new\(shift\)\} $t = a sub\{\}; $t\->tid; $t\->join; $t\->tid'\);
\+is\($?\, 0\, 'coredump in global destruction'\);
 
 

==== //depot/perl/pad\.h\#9 \(text\) ====

@&#8203;@&#8203; \-105\,6 \+105\,9 @&#8203;@&#8203;
 Set the current pad to be pad C\<n> in the padlist\, saving
 the previous current pad\.
 
\+=for apidoc m|void|PAD\_SET\_CUR\_NOSAVE    |PADLIST padlist|I32 n
\+like PAD\_SET\_CUR\, but without the save
\+
 =for apidoc m|void|PAD\_SAVE\_SETNULLPAD
 Save the current pad then set it to null\.
 
@&#8203;@&#8203; \-133\,8 \+136\,7 @&#8203;@&#8203;
&nbsp;         ? AvARRAY\(\(AV\*\)\(AvARRAY\(padlist\)\[1\]\)\)\[po\] : Nullsv;
&nbsp;     
 
\-\#define PAD\_SET\_CUR\(padlist\,n\) \\
\-    SAVECOMPPAD\(\);                        \\
\+\#define PAD\_SET\_CUR\_NOSAVE\(padlist\,n\) \\
&nbsp;     PL\_comppad = \(PAD\*\) \(AvARRAY\(padlist\)\[n\]\);        \\
&nbsp;     PL\_curpad = AvARRAY\(PL\_comppad\);            \\
&nbsp;     DEBUG\_Xv\(PerlIO\_printf\(Perl\_debug\_log\,            \\
@&#8203;@&#8203; \-142\,6 \+144\,11 @&#8203;@&#8203;
&nbsp;           PTR2UV\(PL\_comppad\)\, PTR2UV\(PL\_curpad\)\, \(int\)\(n\)\)\);
 
 
\+\#define PAD\_SET\_CUR\(padlist\,n\) \\
\+    SAVECOMPPAD\(\);                        \\
\+    PAD\_SET\_CUR\_NOSAVE\(padlist\,n\);
\+
\+
 \#define PAD\_SAVE\_SETNULLPAD\(\)    SAVECOMPPAD\(\); \\
&nbsp;     PL\_comppad = Null\(PAD\*\); PL\_curpad = Null\(SV\*\*\);    \\
&nbsp;     DEBUG\_Xv\(PerlIO\_printf\(Perl\_debug\_log\, "Pad set\_null\\n"\)\);

==== //depot/perl/perl\.c\#526 \(text\) ====

@&#8203;@&#8203; \-354\,6 \+354\,10 @&#8203;@&#8203;
 
&nbsp;     /\* Destroy the main CV and syntax tree \*/
&nbsp;     if \(PL\_main\_root\) \{
\+    /\* ensure comppad/curpad to refer to main's pad \*/
\+    if \(CvPADLIST\(PL\_main\_cv\)\) \{
\+        PAD\_SET\_CUR\_NOSAVE\(CvPADLIST\(PL\_main\_cv\)\, 1\);
\+    \}
&nbsp;     op\_free\(PL\_main\_root\);
&nbsp;     PL\_main\_root = Nullop;
&nbsp;     \}

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'new' to 'resolved'
