### ISSUE TITLE
qr((??{})) causes runaway perl process

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6887]
Migrated from [rt.perl.org#24382](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=24382) (status was 'resolved')

Searchable as RT24382$

**Comment by p5pRT** [comment]
### From dwollmann@puttybox.com

#### Created by boss@thumper.puttybox.local



Recursive regular expression definition using qr// expression with
paren delimiters and a postponed regular subexpression \(??\{\}\)
causes the perl process to run away\, consuming resources until
OOM kill\.

$p = qr/\(??\{$p\}\)/x; /$p/        \# works as expected

$p = qr\(\(??\{$p\}\)\)x; /$p/        \# causes a runaway perl

This behavior occurs with perl versions 5\.6\.0\, 5\.6\.1 and 5\.8\.0\.

Limiting the user's stack size via ulimit \-s 8192 \(for example\)
prevents the runaway\, resulting in a segfault instead\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.8.0:

Configured by boss at Tue Jul 29 00:56:33 CDT 2003.

Summary of my perl5 (revision 5.0 version 8 subversion 0) configuration:
  Platform:
    osname=linux, osvers=2.4.20-gentoo-r5, archname=i686-linux
    uname='linux thumper 2.4.20-gentoo-r5 #1 tue may 20 00:25:16 cdt 2003 i686 
pentium iii (coppermine) genuineintel gnulinux '
    config_args='-des -Darchname=i686-linux -Dcc=gcc -Dprefix=/usr 
-Dvendorprefix=/usr -Dsiteprefix=/usr -Dlocincpth=  
-Doptimize=-march=pentium3 -O3 -pipe -Duselargefiles -Dd_dosuid 
-Dd_semctl_semun -Dscriptdir=/usr/bin -Dman3ext=3pm -Dcf_by=Gentoo -Ud_csh 
-Di_gdbm -Di_db -Di_ndbm'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef 
usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-DPERL5 -fno-strict-aliasing -D_LARGEFILE_SOURCE 
-D_FILE_OFFSET_BITS=64',
    optimize='-march=pentium3 -O3 -pipe',
    cppflags='-DPERL5 -DPERL5 -fno-strict-aliasing'
    ccversion='', gccversion='3.2.2', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', 
lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lpthread -lnsl -lndbm -lgdbm -ldb -ldl -lm -lc -lcrypt -lutil
    perllibs=-lpthread -lnsl -ldl -lm -lc -lcrypt -lutil
    libc=/lib/libc-2.3.1.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.3.1'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.0:
    /home/boss/perllib
    /etc/perl
    /usr/lib/perl5/site_perl/5.8.0/i686-linux
    /usr/lib/perl5/site_perl/5.8.0
    /usr/lib/perl5/site_perl/5.6.1
    /usr/lib/perl5/site_perl
    /usr/lib/perl5/vendor_perl/5.8.0/i686-linux
    /usr/lib/perl5/vendor_perl/5.8.0
    /usr/lib/perl5/vendor_perl
    /usr/lib/perl5/5.8.0/i686-linux
    /usr/lib/perl5/5.8.0
    /usr/local/lib/site_perl
    /usr/lib/perl5/site_perl/5.6.1
    .


Environment for perl v5.8.0:
    HOME=/home/boss
    LANG=en_US
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    
PATH=/home/boss/bin:/bin:/usr/bin:/usr/local/bin:/opt/bin:/usr/i686-pc-linux-gnu/gcc-bin/3.2:/opt/Acrobat5:/usr/X11R6/bin:/opt/sun-jdk-1.4.2.01/bin:/opt/sun-jdk-1.4.2.01/jre/bin:/opt/sun-jdk-1.4.2.01/jre/javaws:/usr/qt/3/bin:/usr/kde/3.1/bin:/usr/kde/3.1/bin:/usr/qt/2/bin:/usr/kde/3/bin:/usr/games/bin:/opt/sun-jdk-1.4.2.01/bin:/opt/sun-jdk-1.4.2.01/jre/bin:/opt/sun-jdk-1.4.2.01/jre/javaws
    PERL5LIB=/home/boss/perllib
    PERL5TESTLIB=/home/boss/perltestlib
    PERL_BADLANG (unset)
    SHELL=/bin/bash


```
</details>

**Comment by p5pRT** [comment]
### From @eserte

D Wollmann \(via RT\) \<perlbug\-followup@&#8203;perl\.org> writes&#8203;:

> \# New Ticket Created by  D Wollmann 
> \# Please include the string&#8203;:  \[perl \#24382\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: http&#8203;://rt\.perl\.org/rt2/Ticket/Display\.html?id=24382 >
> 
> 
> This is a bug report for perl from boss@&#8203;thumper\.puttybox\.local\,
> generated with the help of perlbug 1\.34 running under perl v5\.8\.0\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> 
> Recursive regular expression definition using qr// expression with
> paren delimiters and a postponed regular subexpression \(??\{\}\)
> causes the perl process to run away\, consuming resources until
> OOM kill\.
> 
> $p = qr/\(??\{$p\}\)/x; /$p/        \# works as expected
> 
> $p = qr\(\(??\{$p\}\)\)x; /$p/        \# causes a runaway perl
> 
> This behavior occurs with perl versions 5\.6\.0\, 5\.6\.1 and 5\.8\.0\.
> 
> Limiting the user's stack size via ulimit \-s 8192 \(for example\)
> prevents the runaway\, resulting in a segfault instead\.
> 
> 

I don't see a difference with both expressions \-\-\- both lead to a
segmentation fault\, as expected\.

Regards\,
&nbsp;    Slaven

\-\- 
Slaven Rezic \- slaven@&#8203;rezic\.de
&nbsp;  BBBike \- route planner for cyclists in Berlin
&nbsp;  WWW version&#8203;:                           http&#8203;://www\.bbbike\.de
&nbsp;  Perl/Tk version for Unix and Windows&#8203;:  http&#8203;://bbbike\.sourceforge\.net

**Comment by p5pRT** [comment]
### From dwollmann@puttybox.com

\[slaven \<\!\-\-c\-\-> \<i>at\</i> \<\!\-\-a\-\-> rezic\.de \- Sat Nov  1 17&#8203;:51&#8203;:53 2003\]&#8203;:

> D Wollmann \(via RT\) \<perlbug\-followup \<\!\-\-c\-\-> \<i>at\</i> \<\!\-\-a\-\->
perl\.org> writes&#8203;:
> 
> > \# New Ticket Created by  D Wollmann 
> > \# Please include the string&#8203;:  \[perl \#24382\]
> > \# in the subject line of all future correspondence about this issue\. 
> > \# \<URL&#8203;: http&#8203;://rt\.perl\.org/rt2/Ticket/Display\.html?id=24382 >
> > 
> > 
> > This is a bug report for perl from boss@&#8203;thumper\.puttybox\.local\,
> > generated with the help of perlbug 1\.34 running under perl v5\.8\.0\.
> > 
> > 
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > \[Please enter your report here\]
> > 
> > Recursive regular expression definition using qr// expression with
> > paren delimiters and a postponed regular subexpression \(??\{\}\)
> > causes the perl process to run away\, consuming resources until
> > OOM kill\.
> > 
> > $p = qr/\(??\{$p\}\)/x; /$p/        \# works as expected
> > 
> > $p = qr\(\(??\{$p\}\)\)x; /$p/        \# causes a runaway perl
> > 
> > This behavior occurs with perl versions 5\.6\.0\, 5\.6\.1 and 5\.8\.0\.
> > 
> > Limiting the user's stack size via ulimit \-s 8192 \(for example\)
> > prevents the runaway\, resulting in a segfault instead\.
> > 
> > 
> 
> I don't see a difference with both expressions \-\-\- both lead to a
> segmentation fault\, as expected\.
> 
> Regards\,
>     Slaven

Sorry\, I oversimplified the cases\.

This should demonstrate the bad behavior&#8203;:

$ perl \-le '$p = qr\( \\\( \(?&#8203;: \(?>\[^\(\)\]\+\) | \(??\{ $p \}\) \)\* \\\) \)x; print
"match $1" if "camel\(foo\(bar\)\)" =~ /camel\($\{p\}\)/'

This behaves well&#8203;:

$ perl \-le '$p = qr/ \\\( \(?&#8203;: \(?>\[^\(\)\]\+\) | \(??\{ $p \}\) \)\* \\\) /x; print
"match $1" if "camel\(foo\(bar\)\)" =~ /camel\($\{p\}\)/'


David

**Comment by p5pRT** [comment]
### From dwollmann@puttybox.com

On Saturday 01 November 2003 19&#8203;:51\, perlbug\-followup@&#8203;perl\.org wrote&#8203;:
> D Wollmann \(via RT\) \<perlbug\-followup@&#8203;perl\.org> writes&#8203;:
> > \# New Ticket Created by  D Wollmann
> > \# Please include the string&#8203;:  \[perl \#24382\]
> > \# in the subject line of all future correspondence about this issue\.
> > \# \<URL&#8203;: http&#8203;://rt\.perl\.org/rt2/Ticket/Display\.html?id=24382 >
> >
> >
> > This is a bug report for perl from boss@&#8203;thumper\.puttybox\.local\,
> > generated with the help of perlbug 1\.34 running under perl v5\.8\.0\.
> >
> >
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > \[Please enter your report here\]
> >
> > Recursive regular expression definition using qr// expression with
> > paren delimiters and a postponed regular subexpression \(??\{\}\)
> > causes the perl process to run away\, consuming resources until
> > OOM kill\.
> >
> > $p = qr/\(??\{$p\}\)/x; /$p/        \# works as expected
> >
> > $p = qr\(\(??\{$p\}\)\)x; /$p/        \# causes a runaway perl
> >
> > This behavior occurs with perl versions 5\.6\.0\, 5\.6\.1 and 5\.8\.0\.
> >
> > Limiting the user's stack size via ulimit \-s 8192 \(for example\)
> > prevents the runaway\, resulting in a segfault instead\.
>
> I don't see a difference with both expressions \-\-\- both lead to a
> segmentation fault\, as expected\.
>
> Regards\,
>     Slaven

I posted this reply on RT\, but I'm not sure if RT forwards replies posted 
online&#8203;:


---
Sorry\, I oversimplified the cases\.

This should demonstrate the bad behavior&#8203;:

$ perl \-le '$p = qr\( \\\( \(?&#8203;: \(?>\[^\(\)\]\+\) | \(??\{ $p \}\) \)\* \\\) \)x; print
"match $1" if "camel\(foo\(bar\)\)" =~ /camel\($\{p\}\)/'

This behaves well&#8203;:

$ perl \-le '$p = qr/ \\\( \(?&#8203;: \(?>\[^\(\)\]\+\) | \(??\{ $p \}\) \)\* \\\) /x; print
"match $1" if "camel\(foo\(bar\)\)" =~ /camel\($\{p\}\)/'


David
\-\- 
D\. Wollmann
gpg 58A7 2C9A FCBC 8B4A 6F76  1BF1 9BE0 FB93 34C8 8A21

**Comment by p5pRT** [comment]
@rspier - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From domo@ieee.org

> \[converter \- Fri Oct 31 15&#8203;:23&#8203;:59 2003\]&#8203;:
> 
\.\.\.
> 
> Recursive regular expression definition using qr// expression with
> paren delimiters and a postponed regular subexpression \(??\{\}\)
> causes the perl process to run away\, consuming resources until
> OOM kill\.

\(Until what? Nevermind\.\)
> 
> $p = qr/\(??\{$p\}\)/x; /$p/        \# works as expected
> 
> $p = qr\(\(??\{$p\}\)\)x; /$p/        \# causes a runaway perl
> 
> This behavior occurs with perl versions 5\.6\.0\, 5\.6\.1 and 5\.8\.0\.
> 
> Limiting the user's stack size via ulimit \-s 8192 \(for example\)
> prevents the runaway\, resulting in a segfault instead\.

> Summary of my perl5 \(revision 5\.0 version 8 subversion 0\)
>    configuration&#8203;:

Still present in blead@&#8203;27631\. Both examples crash for me\. By cutting down the stack size\, I 
can make them crash more quickly \(on Mac OS X\)\.

This is the proof that it is possible to use \(??\{ in a pathologically recursive manner&#8203;: the stack 
trace consists of

\#0  0x0025cfa4 in S\_regmatch \(my\_perl=0x1800400\, prog=0x11060e4\) at regexec\.c&#8203;:2468
\#1  0x002637ac in S\_regmatch \(my\_perl=0x1800400\, prog=0x11060e4\) at regexec\.c&#8203;:3415
\#2  0x002637ac in S\_regmatch \(my\_perl=0x1800400\, prog=0x11060e4\) at regexec\.c&#8203;:3415
\.\.\.

where regexec\.c&#8203;:3415 is

&nbsp;            /\* XXX the only recursion left in regmatch\(\) \*/
&nbsp;            if \(regmatch\(re\->program \+ 1\)\) \{

Not that having a test case makes the fix any easier\.\.\.

**Comment by p5pRT** [comment]
### From @cpansprout

Something I noticed\.\.\.\.

On Mon Nov 03 08&#8203;:01&#8203;:14 2003\, converter wrote&#8203;:
> Sorry\, I oversimplified the cases\.
> 
> This should demonstrate the bad behavior&#8203;:
> 
> $ perl \-le '$p = qr\( \\\( \(?&#8203;: \(?>\[^\(\)\]\+\) | \(??\{ $p \}\) \)\* \\\) \)x; print
> "match $1" if "camel\(foo\(bar\)\)" =~ /camel\($\{p\}\)/'

This case is escaping a delimiter\, so the \\\( inside the regexp is a
capturing group\, not a literal parenthesis\.

> 
> This behaves well&#8203;:
> 
> $ perl \-le '$p = qr/ \\\( \(?&#8203;: \(?>\[^\(\)\]\+\) | \(??\{ $p \}\) \)\* \\\) /x; print
> "match $1" if "camel\(foo\(bar\)\)" =~ /camel\($\{p\}\)/'
> 
> 
> David

**Comment by p5pRT** [comment]
### From @cpansprout

Apparently this was fixed some time before 5\.10\.0&#8203;:

$ perl5\.10\.0 \-e '$p = qr\(\(??\{$p\}\)\)x; /$p/'
EVAL without pos change exceeded limit in regex at \-e line 1\.
$ perl5\.8\.9 \-e '$p = qr\(\(??\{$p\}\)\)x; /$p/'
Segmentation fault

Now the infinite recursion is trapped\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Apparently this was fixed some time before 5\.10\.0&#8203;:

$ perl5\.10\.0 \-e '$p = qr\(\(??\{$p\}\)\)x; /$p/'
EVAL without pos change exceeded limit in regex at \-e line 1\.
$ perl5\.8\.9 \-e '$p = qr\(\(??\{$p\}\)\)x; /$p/'
Segmentation fault

Now the infinite recursion is trapped\.

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
