### ISSUE TITLE
Large string crashes regex engine by using more stack 5.6.0

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6964]
Migrated from [rt.perl.org#24612](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=24612) (status was 'resolved')

Searchable as RT24612$

**Comment by p5pRT** [comment]
### From macdonch@dcs.gla.ac.uk

Hi\,

I've discovered a "problem" with the regex engine in Perl 5\.8\.\(0|2\)\. My
full script to crash it can be found at 
http&#8203;://www\.dcs\.gla\.ac\.uk/~macdonch/crashperl\.pl
however\, it I have included the important bits of the script\.

The signifcant point is that the script works in Perl 5\.6\.0\, but seg\-
faults in Perl 5\.8\.0 and Perl 5\.8\.2\. It can be prevented from crashing
by increasing the stack size \(ulimit \-s\) form it's default 8192 to 16000\.

I have enclosed five outputs in the body of this email
1\. A cut down version of the script\. NB&#8203;: The string being passed to the
regex engine includes 6000 URLs \- I've cut this down to three\.

2\. Perl \-V for Redhat's Perl 5\.6\.0 \(script works with stacksize 8192\)

3\. Perl \-V for Redhat's Perl 5\.8\.0 \(script segfaults with stacksize 8192\)

4\. Perl \-V for my build of Perl 5\.8\.2 \(script segfaults w/ stacksize 8192\)

5\. A gdb run of the script with stacksize 8192 on my Perl 5\.8\.2

I've spoken to Nicholas Clarke\, who believes this problem to be a
currently known bug\. I have not been able to access RT to determine
which bug that is\.

Many thanks for the good work guys\.

Craig



---
1\.


---
\#\!/usr/bin/perl \-w
\#Full script can be found here&#8203;:
\#http&#8203;://www\.dcs\.gla\.ac\.uk/~macdonch/crashperl\.pl
my $request = \<\<VERB;
FINISHED http&#8203;://www\.dcs\.gla\.ac\.uk/~ian/javadocs/AllNames\.html
http&#8203;://www\.dcs\.gla\.ac\.uk/~ian/javadocs/packages\.html\#
\<insert 6000 URLs here>
http&#8203;://www\.dcs\.gla\.ac\.uk/~ian/javadocs/AllNames\.html\#
VERB

$request =~ s/\(\(?&#8203;:\.\*\\n\)\+?\)\\\.\\n//;
print length $1;
print "\\n";



---
2\.


---
Summary of my perl5 \(revision 5\.0 version 6 subversion 0\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.4\.6\-3\.1enterprise\, archname=i386\-linux
&nbsp;    uname='linux stripples\.devel\.redhat\.com 2\.4\.6\-3\.1enterprise \#1 smp tue jul 24 14&#8203;:03&#8203;:17 edt 2001 i686 unknown '
&nbsp;    config\_args='\-des \-Doptimize=\-O2 \-march=i386 \-mcpu=i686 \-Dcc=gcc \-Dcccdlflags=\-fPIC \-Dinstallprefix=/usr \-Dprefix=/usr \-Darchname=i386\-linux \-Dd\_dosuid \-Dd\_semctl\_semun \-Di\_db \-Di\_ndbm \-Di\_gdbm \-Di\_shadow \-Di\_syslog \-Dman3ext=3pm \-Uuselargefiles'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
&nbsp;    useperlio=undef d\_sfio=undef uselargefiles=undef 
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef usesocks=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'\, optimize='\-O2 \-march=i386 \-mcpu=i686'\, gccversion=2\.96 20000731 \(Red Hat Linux 7\.1 2\.96\-96\)
&nbsp;    cppflags='\-fno\-strict\-aliasing \-I/usr/local/include'
&nbsp;    ccflags ='\-fno\-strict\-aliasing \-I/usr/local/include'
&nbsp;    stdchar='char'\, d\_stdstdio=define\, usevfork=false
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=4
&nbsp;    alignbytes=4\, usemymalloc=n\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='gcc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-ldl \-lm \-lc \-lcrypt
&nbsp;    libc=/lib/libc\-2\.2\.4\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;:
&nbsp;  Built under linux
&nbsp;  Compiled at Aug  9 2001 22&#8203;:48&#8203;:52
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/lib/perl5/5\.6\.0/i386\-linux
&nbsp;    /usr/lib/perl5/5\.6\.0
&nbsp;    /usr/lib/perl5/site\_perl/5\.6\.0/i386\-linux
&nbsp;    /usr/lib/perl5/site\_perl/5\.6\.0
&nbsp;    /usr/lib/perl5/site\_perl
&nbsp;    \.



---
3\.


---
Summary of my perl5 \(revision 5\.0 version 8 subversion 0\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.4\.20\-2\.48smp\, archname=i386\-linux\-thread\-multi
&nbsp;    uname='linux stripples\.devel\.redhat\.com 2\.4\.20\-2\.48smp \#1 smp thu feb 13 11&#8203;:44&#8203;:55 est 2003 i686 i686 i386 gnulinux '
&nbsp;    config\_args='\-des \-Doptimize=\-O2 \-march=i386 \-mcpu=i686 \-g \-Dmyhostname=localhost \-Dperladmin=root@&#8203;localhost \-Dcc=gcc \-Dcf\_by=Red Hat\, Inc\. \-Dinstallprefix=/usr \-Dprefix=/usr \-Darchname=i386\-linux \-Dvendorprefix=/usr \-Dsiteprefix=/usr \-Dotherlibdirs=/usr/lib/perl5/5\.8\.0 \-Duseshrplib \-Dusethreads \-Duseithreads \-Duselargefiles \-Dd\_dosuid \-Dd\_semctl\_semun \-Di\_db \-Ui\_ndbm \-Di\_gdbm \-Di\_shadow \-Di\_syslog \-Dman3ext=3pm \-Duseperlio \-Dinstallusrbinperl \-Ubincompat5005 \-Uversiononly \-Dpager=/usr/bin/less \-isr'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-I/usr/include/gdbm'\,
&nbsp;    optimize='\-O2 \-march=i386 \-mcpu=i686 \-g'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-I/usr/include/gdbm'
&nbsp;    ccversion=''\, gccversion='3\.2\.2 20030213 \(Red Hat Linux 8\.0 3\.2\.2\-1\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='gcc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-lgdbm \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt \-lutil
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lpthread \-lc \-lcrypt \-lutil
&nbsp;    libc=/lib/libc\-2\.3\.1\.so\, so=so\, useshrplib=true\, libperl=libperl\.so
&nbsp;    gnulibc\_version='2\.3\.1'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic \-Wl\,\-rpath\,/usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi/CORE'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: DEBUGGING MULTIPLICITY USE\_ITHREADS USE\_LARGE\_FILES PERL\_IMPLICIT\_CONTEXT
&nbsp;  Locally applied patches&#8203;:
&nbsp;      MAINT18379
&nbsp;  Built under linux
&nbsp;  Compiled at Feb 18 2003 22&#8203;:19&#8203;:53
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/5\.8\.0
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.0/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.0
&nbsp;    /usr/lib/perl5/site\_perl
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.0/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.0
&nbsp;    /usr/lib/perl5/vendor\_perl
&nbsp;    /usr/lib/perl5/5\.8\.0/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/5\.8\.0
&nbsp;    \.



---
4\. 


---
Summary of my perl5 \(revision 5\.0 version 8 subversion 2\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.4\.20\-18\.9smp\, archname=i686\-linux\-thread\-multi
&nbsp;    uname='linux maikoor 2\.4\.20\-18\.9smp \#1 smp thu may 29 06&#8203;:55&#8203;:05 edt 2003 i686 i686 i386 gnulinux '
&nbsp;    config\_args='\-des \-Doptimize=\-g \-O2 \-march=i386 \-mcpu=i686 \-Dmyhostname=maikoor \-Dperladmin=macdonch@&#8203;dcs\.gla\.ac\.uk \-Dcc=gcc \-Dcf\_by=Craig \-Darchname=i386\-linux \-Duseshrplib \-Dusethreads \-Duseithreads \-Duselargefiles \-Dd\_dosuid \-Dd\_semctl\_semun \-Di\_db \-Ui\_ndbm \-Di\_gdbm \-Di\_shadow \-Di\_syslog \-Dman3ext=3pm \-Duseperlio \-Dinstallusrbinperl \-Ubincompat5005 \-Uversiononly \-Dpager=/usr/bin/less \-Dprefix=/local/terrier\_tmp/macdonch/perl5\.8\.2/'
&nbsp;    hint=previous\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-I/usr/include/gdbm'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-I/usr/include/gdbm \-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-I/usr/include/gdbm'
&nbsp;    ccversion=''\, gccversion='3\.2\.2 20030222 \(Red Hat Linux 3\.2\.2\-5\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    libc=/lib/libc\-2\.3\.2\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.3\.2'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
&nbsp;    cccdlflags='\-fpic'\, lddlflags='\-shared \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: DEBUGGING MULTIPLICITY USE\_ITHREADS USE\_LARGE\_FILES PERL\_IMPLICIT\_CONTEXT
&nbsp;  Built under linux
&nbsp;  Compiled at Dec  3 2003 23&#8203;:08&#8203;:15
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /local/terrier\_tmp/macdonch/perl5\.8\.2/lib/5\.8\.2/i686\-linux\-thread\-multi
&nbsp;    /local/terrier\_tmp/macdonch/perl5\.8\.2/lib/5\.8\.2
&nbsp;    /local/terrier\_tmp/macdonch/perl5\.8\.2//lib/site\_perl/5\.8\.2/i686\-linux\-thread\-multi
&nbsp;    /local/terrier\_tmp/macdonch/perl5\.8\.2//lib/site\_perl/5\.8\.2
&nbsp;    /local/terrier\_tmp/macdonch/perl5\.8\.2//lib/site\_perl
&nbsp;    \.



---
5\.


---
Program received signal SIGSEGV\, Segmentation fault\.
\[Switching to Thread 1074455712 \(LWP 4968\)\]
0x0813ea05 in S\_regcppush \(my\_perl=0x8193830\, parenfloor=0\) at 
regexec\.c&#8203;:176
176     in regexec\.c
\(gdb\) bt
\#0  0x0813ea05 in S\_regcppush \(my\_perl=0x8193830\, parenfloor=0\) at 
regexec\.c&#8203;:176
\#1  0x081490e7 in S\_regmatch \(my\_perl=0x8193830\, prog=0x8484750\) at 
regexec\.c&#8203;:3220
\#2  0x0814bb16 in S\_regmatch \(my\_perl=0x8193830\, prog=0x8484748\) at 
regexec\.c&#8203;:3784
\#3  0x081493c5 in S\_regmatch \(my\_perl=0x8193830\, prog=0x8484750\) at 
regexec\.c&#8203;:3254

\<alternates between lines 3254\, 3284>

\#10272 0x0814bb16 in S\_regmatch \(my\_perl=0x8193830\, prog=0x8484748\) at 
regexec\.c&#8203;:3784
\#10273 0x08148d76 in S\_regmatch \(my\_perl=0x8193830\, prog=0x8484758\) at 
regexec\.c&#8203;:3159
\#10274 0x08148b86 in S\_regmatch \(my\_perl=0x8193830\, prog=0x8484734\) at 
regexec\.c&#8203;:3104
\#10275 0x081458b0 in S\_regtry \(my\_perl=0x8193830\, prog=0x84846f0\,
&nbsp;    startpos=0x40302008 "FINISHED 
http&#8203;://www\.dcs\.gla\.ac\.uk/~ian/javadocs/AllNames\.html\\nhttp&#8203;://www\.dcs\.gla\.ac\.uk/~ian/javadocs/packages\.html\#\\nhttp&#8203;://www\.dcs\.gla\.ac\.uk/~ian/javadocs/tree\.html\#\\nhttp&#8203;://www\.dcs\.gla\.ac\.uk/~ian/java"\.\.\.\) 
at regexec\.c&#8203;:2185
\#10276 0x08145158 in Perl\_regexec\_flags \(my\_perl=0x8193830\, 
prog=0x84846f0\,
&nbsp;    stringarg=0x40302008 "FINISHED 
http&#8203;://www\.dcs\.gla\.ac\.uk/~ian/javadocs/AllNames\.html\\nhttp&#8203;://www\.dcs\.gla\.ac\.uk/~ian/javadocs/packages\.html\#\\nhttp&#8203;://www\.dcs\.gla\.ac\.uk/~ian/javadocs/tree\.html\#\\nhttp&#8203;://www\.dcs\.gla\.ac\.uk/~ian/java"\.\.\.\,
&nbsp;    strend=0x4037384f "\\n\.\\n"\,
&nbsp;    strbeg=0x40302008 "FINISHED 
http&#8203;://www\.dcs\.gla\.ac\.uk/~ian/javadocs/AllNames\.html\\nhttp&#8203;://www\.dcs\.gla\.ac\.uk/~ian/javadocs/packages\.html\#\\nhttp&#8203;://www\.dcs\.gla\.ac\.uk/~ian/javadocs/tree\.html\#\\nhttp&#8203;://www\.dcs\.gla\.ac\.uk/~ian/java"\.\.\.\, 
minend=0\, sv=0x81ac3e0\,
&nbsp;    data=0x0\, flags=3\) at regexec\.c&#8203;:2012
\#10277 0x080dbca7 in Perl\_pp\_subst \(my\_perl=0x8193830\) at pp\_hot\.c&#8203;:2067
\#10278 0x080bb5c7 in Perl\_runops\_debug \(my\_perl=0x8193830\) at dump\.c&#8203;:1438
\#10279 0x08065026 in S\_run\_body \(my\_perl=0x8193830\, oldscope=1\) at 
perl\.c&#8203;:1855
\#10280 0x08064ad3 in perl\_run \(my\_perl=0x8193830\) at perl\.c&#8203;:1779
\#10281 0x0805fc83 in main \(argc=3\, argv=0xbffff044\, env=0xbffff054\) at 
perlmain\.c&#8203;:86
\#10282 0x420156a4 in \_\_libc\_start\_main \(\) from /lib/tls/libc\.so\.6
\(gdb\)

**Comment by p5pRT** [comment]
### From @eserte

Craig Macdonald \(via RT\) \<perlbug\-followup@&#8203;perl\.org> writes&#8203;:

> \# New Ticket Created by  Craig Macdonald 
> \# Please include the string&#8203;:  \[perl \#24612\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: http&#8203;://rt\.perl\.org&#8203;:80/rt3/Ticket/Display\.html?id=24612 >
> 
> 
> Hi\,
> 
> I've discovered a "problem" with the regex engine in Perl 5\.8\.\(0|2\)\. My
> full script to crash it can be found at 
> http&#8203;://www\.dcs\.gla\.ac\.uk/~macdonch/crashperl\.pl
> however\, it I have included the important bits of the script\.
> 
> The signifcant point is that the script works in Perl 5\.6\.0\, but seg\-
> faults in Perl 5\.8\.0 and Perl 5\.8\.2\. It can be prevented from crashing
> by increasing the stack size \(ulimit \-s\) form it's default 8192 to 16000\.

I think the more significant difference is the 5\.6\.0 version being
non\-threaded while your 5\.8\.x versions are threaded\. With threaded
perls\, nearly every internal function call gets an additional argument
\(look at "my\_perl" in the gdb backtrace\) which may cause the increase
in stack usage\.

> I have enclosed five outputs in the body of this email
> 1\. A cut down version of the script\. NB&#8203;: The string being passed to the
> regex engine includes 6000 URLs \- I've cut this down to three\.
> 
> 2\. Perl \-V for Redhat's Perl 5\.6\.0 \(script works with stacksize 8192\)
> 
> 3\. Perl \-V for Redhat's Perl 5\.8\.0 \(script segfaults with stacksize 8192\)
> 
> 4\. Perl \-V for my build of Perl 5\.8\.2 \(script segfaults w/ stacksize 8192\)
> 
> 5\. A gdb run of the script with stacksize 8192 on my Perl 5\.8\.2
> 
> I've spoken to Nicholas Clarke\, who believes this problem to be a
> currently known bug\. I have not been able to access RT to determine
> which bug that is\.
> 
> Many thanks for the good work guys\.
> 
> Craig
> 
\[\.\.\.\]

Regards\,
&nbsp;        Slaven

\-\- 
Slaven Rezic \- slaven@&#8203;rezic\.de
&nbsp;  BBBike \- route planner for cyclists in Berlin
&nbsp;  WWW version&#8203;:                           http&#8203;://www\.bbbike\.de
&nbsp;  Perl/Tk version for Unix and Windows&#8203;:  http&#8203;://bbbike\.sourceforge\.net

**Comment by p5pRT** [comment]
### From @cpansprout

This was fixed in 5\.10\.0 when the regexp engine stopped using the C
stack for recursion\.

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
