### ISSUE TITLE
Segmentation fault in perl 5.8.2

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7039]
Migrated from [rt.perl.org#24914](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=24914) (status was 'resolved')

Searchable as RT24914$

**Comment by p5pRT** [comment]
### From apocalypse@0ne.us

After some narrowing down\, I've produced a minimal case that will always
segfault\. Sky told me to try build a non\-threaded perl\, but alas my box
doesn't have enough HD space to try it out\, so I now give the problem to
ya'll :\)

Here's the code&#8203;:

\# Standard stuff to catch errors
use strict qw\(subs vars refs\);                \# Make sure we can't mess up
use warnings FATAL => 'all';                \# Enable warnings to catch errors

\# Load some stuff
use POE;
use POE&#8203;::Component&#8203;::SimpleDBI;

\# Fire off the SimpleDBI stuff
POE&#8203;::Component&#8203;::SimpleDBI\->new\(
&nbsp;    'ALIAS'        =>    'SimpleDBI'\,

&nbsp;    \# Be sure to put something totally non\-real in here
&nbsp;    \# Hint&#8203;: put in a real database\, but get the username\+password wrong
&nbsp;    'DSN'        =>    'DBI&#8203;:mysql&#8203;:database=NonExistant;host=192\.168\.1\.1;port=3306'\,

&nbsp;    'USERNAME'    =>    'TEST'\,
&nbsp;    'PASSWORD'    =>    'TEST'\,
\) or die 'Unable to create the SimpleDBI session';

POE&#8203;::Kernel\->run\(\);

\# Now\, it should hang for a little bit\, just wait for DBI to fail\.\.\.
\# Here's the exact line in SimpleDBI that causes perl to die&#8203;:
\# die\( "Could not connect to the DataBase&#8203;: $\_\[ARG0\]\->\{'ERROR'\}" \);
\# Now\, IT SEGFAULTS on my debian testing box \( Perl 5\.8\.2 with threading \)
\_\_END\_\_

Luckily\, I got the perl\-debug package\, so here's a nice backtrace of the
segfault&#8203;:

gdb \-\-args /usr/bin/debugperl /test\.pl

Program received signal SIGSEGV\, Segmentation fault\.
\[Switching to Thread 16384 \(LWP 10629\)\]
0x0811f4b6 in Perl\_leave\_scope \(my\_perl=0x81a7df8\, base=0\) at scope\.c&#8203;:902
902     scope\.c&#8203;: No such file or directory\.
&nbsp;        in scope\.c
\(gdb\) bt
\#0  0x0811f4b6 in Perl\_leave\_scope \(my\_perl=0x81a7df8\, base=0\) at scope\.c&#8203;:902
\#1  0x0811cb32 in Perl\_pop\_scope \(my\_perl=0x81a7df8\) at scope\.c&#8203;:137
\#2  0x0806b9e9 in S\_my\_exit\_jump \(my\_perl=0x81a7df8\) at perl\.c&#8203;:4524
\#3  0x0806b67f in Perl\_my\_failure\_exit \(my\_perl=0x81a7df8\) at perl\.c&#8203;:4504
\#4  0x08125b01 in Perl\_die\_where \(my\_perl=0x81a7df8\,
&nbsp;    message=0x8698f90 "POE&#8203;::Component&#8203;::SimpleDBI tried 5 times to create a
Wheel and is giving up\.\.\. at
/usr/local/share/perl/5\.8\.2/POE/Component/SimpleDBI\.pm line 466\.\\n"\,
msglen=146\) at pp\_ctl\.c&#8203;:1388
\#5  0x080c7075 in Perl\_vdie \(my\_perl=0x81a7df8\, pat=0x8193e57 "%\_"\,
args=0xbffffb50\) at util\.c&#8203;:1099
\#6  0x080c7188 in Perl\_die \(my\_perl=0x81a7df8\, pat=0x8193e57 "%\_"\) at
util\.c&#8203;:1129
\#7  0x08130e5f in Perl\_pp\_die \(my\_perl=0x81a7df8\) at pp\_sys\.c&#8203;:510
\#8  0x080c40a3 in Perl\_runops\_debug \(my\_perl=0x81a7df8\) at dump\.c&#8203;:1438
\#9  0x080654ce in S\_run\_body \(my\_perl=0x81a7df8\, oldscope=1\) at perl\.c&#8203;:1860
\#10 0x08064f11 in perl\_run \(my\_perl=0x81a7df8\) at perl\.c&#8203;:1779
\#11 0x0805fc68 in main \(argc=2\, argv=0xbffffd94\, env=0xbffffda0\) at
perlmain\.c&#8203;:86

Running on Debian Testing \( 2\.4\.18\-bf24 kernel \)

perl \-V shows&#8203;:
Summary of my perl5 \(revision 5\.0 version 8 subversion 2\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.4\.22\-xfs\+ti1211\, archname=i386\-linux\-thread\-multi
&nbsp;    uname='linux kosh 2\.4\.22\-xfs\+ti1211 \#1 sat oct 25 10&#8203;:11&#8203;:37 est 2003
i686 gnulinux '
&nbsp;    config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN
\-Dcccdlflags=\-fPIC \-Darchname=i386\-linux \-Dprefix=/usr
\-Dprivlib=/usr/share/perl/5\.8\.2 \-Darchlib=/usr/lib/perl/5\.8\.2
\-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5
\-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local
\-Dsitelib=/usr/local/share/perl/5\.8\.2
\-Dsitearch=/usr/local/lib/perl/5\.8\.2 \-Dman1dir=/usr/share/man/man1
\-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1
\-Dsiteman3dir=/usr/local/man/man3 \-Dman1ext=1 \-Dman3ext=3perl
\-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Uusesfio \-Uusenm
\-Duseshrplib \-Dlibperl=libperl\.so\.5\.8\.2 \-Dd\_dosuid \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=define use5005threads=undef useithreads=define
usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS
\-DDEBIAN \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE
\-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O3'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBIAN
\-fno\-strict\-aliasing \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='3\.3\.2 \(Debian\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,
lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    libc=/lib/libc\-2\.3\.2\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.8\.2
&nbsp;    gnulibc\_version='2\.3\.2'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: MULTIPLICITY USE\_ITHREADS USE\_LARGE\_FILES
PERL\_IMPLICIT\_CONTEXT
&nbsp;  Built under linux
&nbsp;  Compiled at Nov 15 2003 17&#8203;:52&#8203;:08
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /etc/perl
&nbsp;    /usr/local/lib/perl/5\.8\.2
&nbsp;    /usr/local/share/perl/5\.8\.2
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/perl/5\.8\.2
&nbsp;    /usr/share/perl/5\.8\.2
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Jan 15\, 2004 at 11&#8203;:35&#8203;:46AM \-0000\, apocalypse@&#8203;0ne\.us \(via RT\) wrote&#8203;:
> \# New Ticket Created by  apocalypse@&#8203;0ne\.us 
> \# Please include the string&#8203;:  \[perl \#24914\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: http&#8203;://rt\.perl\.org/rt3/Ticket/Display\.html?id=24914 >
> 
> 
> After some narrowing down\, I've produced a minimal case that will always
> segfault\. Sky told me to try build a non\-threaded perl\, but alas my box
> doesn't have enough HD space to try it out\, so I now give the problem to
> ya'll :\)

Which can be reduced further to&#8203;:

&nbsp;    sub mydie \{ die \}

&nbsp;    my $f;
&nbsp;    $f = sub \{
&nbsp;    my $x = 1;
&nbsp;    $f = 0;
&nbsp;    mydie;
&nbsp;    \};
&nbsp;    $f\->\(\);

deleting $f's reference to the anon sub while it's active causes nasty
things to happen\, principally because various savestack restores do stuff
to the now freed pad\.

Fixed in bleedperl by patch \#22167

Dave\.


\-\- 
This is a great day for France\!
&nbsp;    \-\- Nixon at Charles De Gaulle's funeral

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, Jan 17\, 2004 at 04&#8203;:37&#8203;:25PM \+0000\, Dave Mitchell wrote&#8203;:
> Which can be reduced further to&#8203;:
> 
>     sub mydie \{ die \}
> 
>     my $f;
>     $f = sub \{
>     my $x = 1;
>     $f = 0;
>     mydie;
>     \};
>     $f\->\(\);
> 
> deleting $f's reference to the anon sub while it's active causes nasty
> things to happen\, principally because various savestack restores do stuff
> to the now freed pad\.

Note to self&#8203;: the real problem is the winding down through the contexts
during the die \- all the contexts are popped first\, including the sub
context that holds a ref to the anon CV \- thus causing it and it's pad
to be freed\. Only then is the savestack popped\, which tries to restore
lexicals etc in the now vanished pad\. In an ideal world the individual
context popping would be interspersed with the scope popping\, but since
contexts don't record PL\_scopestack\_ix\, this isn't possible\.

\-\- 
Thank God I'm an atheist\.\.\.\.\.

**Comment by p5pRT** [comment]
### From perl5-porters@ton.iguana.be

In article \<20040117170701\.GD14442@&#8203;\_disolutions\.com>\,
&nbsp;    Dave Mitchell \<davem@&#8203;fdisolutions\.com> writes&#8203;:
> Note to self&#8203;: the real problem is the winding down through the contexts
> during the die \- all the contexts are popped first\, including the sub
> context that holds a ref to the anon CV \- thus causing it and it's pad
> to be freed\. Only then is the savestack popped\, which tries to restore
> lexicals etc in the now vanished pad\. In an ideal world the individual
> context popping would be interspersed with the scope popping\, but since
> contexts don't record PL\_scopestack\_ix\, this isn't possible\.
> 

How about incrementing the refcount on the codereference in case of an
indirect function call \(and decreasing it on return of course\) ?

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, Jan 17\, 2004 at 05&#8203;:14&#8203;:42PM \+0000\, Ton Hospel wrote&#8203;:
> In article \<20040117170701\.GD14442@&#8203;\_disolutions\.com>\,
>     Dave Mitchell \<davem@&#8203;fdisolutions\.com> writes&#8203;:
> > Note to self&#8203;: the real problem is the winding down through the contexts
> > during the die \- all the contexts are popped first\, including the sub
> > context that holds a ref to the anon CV \- thus causing it and it's pad
> > to be freed\. Only then is the savestack popped\, which tries to restore
> > lexicals etc in the now vanished pad\. In an ideal world the individual
> > context popping would be interspersed with the scope popping\, but since
> > contexts don't record PL\_scopestack\_ix\, this isn't possible\.
> > 
> 
> How about incrementing the refcount on the codereference in case of an
> indirect function call \(and decreasing it on return of course\) ?

Thats already happens \- the refcnt of a CV is incremented when it is
called\, and decremented upon return\. Its just the order in which die
unwinds things that causes problems\.

\-\- 
Never do today what you can put off till tomorrow\.

**Comment by p5pRT** [comment]
### From @rgs

Dave Mitchell wrote&#8203;:
> 
> Fixed in bleedperl by patch \#22167

Weird\. The test you added to closure\.t seems to hang randomly and unreproducibly\,
entering an infinite loop\. \(If I see this again I'll try to produce a core\.\)

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, Jan 17\, 2004 at 10&#8203;:32&#8203;:16PM \+0100\, Rafael Garcia\-Suarez wrote&#8203;:
> Dave Mitchell wrote&#8203;:
> > 
> > Fixed in bleedperl by patch \#22167
> 
> Weird\. The test you added to closure\.t seems to hang randomly and unreproducibly\,
> entering an infinite loop\. \(If I see this again I'll try to produce a core\.\)

It gets stuck in the system malloc library\.
Using Perl's malloc it segfaults\, so the patch clearly didn't fix the
original problem\. I've retracted the whole patch for the time being\.
Who knows\, perhaps the mysterious op/write\.t failures will go away too\!

Dave\.

\-\- 
Little fly\, thy summer's play my thoughtless hand
has terminated with extreme prejudice\.
&nbsp;        \(with apologies to William Blake\)

**Comment by p5pRT** [comment]
### From @rgs

Dave Mitchell wrote&#8203;:
> On Sat\, Jan 17\, 2004 at 10&#8203;:32&#8203;:16PM \+0100\, Rafael Garcia\-Suarez wrote&#8203;:
> > Dave Mitchell wrote&#8203;:
> > > 
> > > Fixed in bleedperl by patch \#22167
> > 
> > Weird\. The test you added to closure\.t seems to hang randomly and unreproducibly\,
> > entering an infinite loop\. \(If I see this again I'll try to produce a core\.\)
> 
> It gets stuck in the system malloc library\.
> Using Perl's malloc it segfaults\, so the patch clearly didn't fix the
> original problem\. I've retracted the whole patch for the time being\.
> Who knows\, perhaps the mysterious op/write\.t failures will go away too\!

Doubtful\. On linux\, at patchlevel 22172\, with \-Dusemorebits :

Failed Test Stat Wstat Total Fail  Failed  List of Failed


---
op/write\.t                86    1   1\.16%  44

With default config options\, all tests passes\.

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Jan 18\, 2004 at 12&#8203;:20&#8203;:10AM \+0000\, Dave Mitchell wrote&#8203;:
> On Sat\, Jan 17\, 2004 at 10&#8203;:32&#8203;:16PM \+0100\, Rafael Garcia\-Suarez wrote&#8203;:
> > Dave Mitchell wrote&#8203;:
> > > 
> > > Fixed in bleedperl by patch \#22167
> > 
> > Weird\. The test you added to closure\.t seems to hang randomly and unreproducibly\,
> > entering an infinite loop\. \(If I see this again I'll try to produce a core\.\)
> 
> It gets stuck in the system malloc library\.
> Using Perl's malloc it segfaults\, so the patch clearly didn't fix the
> original problem\. I've retracted the whole patch for the time being\.

Now fixed by change \#22182\. Entering a sub now incs the refcnt on the CV
\*twice\*&#8203;: one is undone when the context is popped\, the other when the
savestack is popped\. This avoids premature freeing of the CV \(and its pad\)
during dounwind\, which unwinds \*all\* contexts before processing the
savestack\. In theory the correct solution is to get dounwind to
intersperse the two\, but I couldn't get that to work\.

Dave\.


\-\- 
"Foul and greedy Dwarf \- you have eaten the last candle\."
&nbsp;    \-\- "Hoardes of the Things"\, BBC Radio\.
