### ISSUE TITLE
Core dump on setting $[

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7129]
Migrated from [rt.perl.org#27024](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=27024) (status was 'resolved')

Searchable as RT27024$

**Comment by p5pRT** [comment]
### From perl-5.8.0@ton.iguana.be

#### Created by perl-5.8.0@ton.iguana.be



perl \-wle '$\[=1 while $=\-\-'
Segmentation fault \(core dumped\)

Wasn't use of $\[ deprecated by the way ? I don't see that mentioned in
perldoc perlvar at least\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.8.2:

Configured by ton at Sun Jan  4 19:19:06 CET 2004.

Summary of my perl5 (revision 5.0 version 8 subversion 2) configuration:
  Platform:
    osname=linux, osvers=2.6.0, archname=i686-linux-64int-ld
    uname='linux quasar 2.6.0 #3 thu dec 18 18:22:48 cet 2003 i686 gnulinux '
    config_args=''
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=define use64bitall=undef uselongdouble=define
    usemymalloc=y, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2 -fomit-frame-pointer',
    cppflags='-fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='3.4.0 20031231 (experimental)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long long', ivsize=8, nvtype='long double', nvsize=12, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/libc-2.3.2.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.3.2'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.2:
    /usr/lib/perl5/5.8.2/i686-linux-64int-ld
    /usr/lib/perl5/5.8.2
    /usr/lib/perl5/site_perl/5.8.2/i686-linux-64int-ld
    /usr/lib/perl5/site_perl/5.8.2
    /usr/lib/perl5/site_perl
    .


Environment for perl v5.8.2:
    HOME=/home/ton
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/ton/bin.Linux:/home/ton/bin:/home/ton/bin.SampleSetup:/usr/local/bin:/usr/local/sbin:/usr/local/jre/bin:/home/oracle/product/9.0.1/bin:/usr/local/ar/bin:/usr/games/bin:/usr/X11R6/bin:/usr/share/bin:/usr/bin:/usr/sbin:/bin:/sbin:.
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @rgs

perl\-5\.8\.0@&#8203;ton\.iguana\.be \(via RT\) wrote&#8203;:
> perl \-wle '$\[=1 while $=\-\-'
> Segmentation fault \(core dumped\)

I can't reproduce this with bleadperl\. I suppose that the recent
parser or format changes fixed it anyway \(but I don't know what was the
original cause of the error\.\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From thelenm@cs.utah.edu

\* Rafael Garcia\-Suarez \<rgarciasuarez@&#8203;free\.fr> \[2004\-02\-24 10&#8203;:21\]&#8203;:
> > perl \-wle '$\[=1 while $=\-\-'
> > Segmentation fault \(core dumped\)
> 
> I can't reproduce this with bleadperl\. I suppose that the recent
> parser or format changes fixed it anyway \(but I don't know what was the
> original cause of the error\.\)

For what it's worth\, I get the segmentation fault in bleadperl \(@&#8203;22352\) on my
machine\.  Here's a GDB backtrace and my perl \-V in case it's useful \(I don't
consider myself competent enough right now to debug or fix it\, but I'd like to
do what I can to help\)\.

\(gdb\) set args \-wle '$\[=1 while $=\-\-'
\(gdb\) run
Starting program&#8203;: /home/mthelen/opt/perl/bin/blead/perl \-wle '$\[=1 while $=\-\-'
 
Program received signal SIGSEGV\, Segmentation fault\.
0x08093090 in Perl\_newLOOPOP \(flags=8\, debuggable=1\, expr=0x81745f8\, block=0x0\) at op\.c&#8203;:3581
3581            \(\(LISTOP\*\)listop\)\->op\_last\->op\_next = LINKLIST\(o\);
\(gdb\) back
\#0  0x08093090 in Perl\_newLOOPOP \(flags=8\, debuggable=1\, expr=0x81745f8\, block=0x0\) at op\.c&#8203;:3581
\#1  0x080886a3 in Perl\_yyparse \(\) at perly\.y&#8203;:163
\#2  0x08062818 in S\_parse\_body \(env=0x0\, xsinit=0x805e5ac \<xs\_init>\) at perl\.c&#8203;:1572
\#3  0x0806197d in perl\_parse \(my\_perl=0x8163008\, xsinit=0x805e5ac \<xs\_init>\, argc=3\, argv=0xbfffee84\, env=0x0\) at perl\.c&#8203;:1082
\#4  0x0805e56e in main \(argc=3\, argv=0xbfffee84\, env=0xbfffee94\) at perlmain\.c&#8203;:84

Output of perl \-V&#8203;:

Summary of my perl5 \(revision 5 version 9 subversion 1 patch 22352\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.3\, archname=i686\-linux
&nbsp;    uname='linux gandalf 2\.6\.1 \#10 fri jan 9 10&#8203;:06&#8203;:34 mst 2004 i686 gnulinux '
&nbsp;    config\_args=''
&nbsp;    hint=previous\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef useithreads=undef usemultiplicity=undef
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g \-Wall'\,
&nbsp;    cppflags='\-fno\-strict\-aliasing \-I/usr/local/include \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'
&nbsp;    ccversion=''\, gccversion='3\.3\.3 \(Debian\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=/lib/libc\-2\.3\.2\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.3\.2'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
&nbsp;    cccdlflags='\-fpic'\, lddlflags='\-shared \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: USE\_LARGE\_FILES
&nbsp;  Locally applied patches&#8203;:
&nbsp;        DEVEL21538
&nbsp;  Built under linux
&nbsp;  Compiled at Feb 24 2004 15&#8203;:00&#8203;:05
&nbsp;  %ENV&#8203;:
&nbsp;    PERL\_CURRENT\_VERSION="blead"
&nbsp;    PERL\_DEFAULT="/usr/bin/perl"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /home/mthelen/opt/perl/lib/blead/i686\-linux
&nbsp;    /home/mthelen/opt/perl/lib/blead
&nbsp;    /home/mthelen/opt/perl/lib/site\_perl/blead/i686\-linux
&nbsp;    /home/mthelen/opt/perl/lib/site\_perl/blead
&nbsp;    /home/mthelen/opt/perl/lib/site\_perl/blead

\-\- Mike

\-\- 
Michael W\. Thelen
It is well to remember that the universe\, with one trifling exception\, is
composed of others\.
&nbsp;                \-\- John Andrew Holmes

**Comment by p5pRT** [comment]
### From @rgs

Michael W Thelen wrote&#8203;:
>
> \* Rafael Garcia\-Suarez \<rgarciasuarez@&#8203;free\.fr> \[2004\-02\-24 10&#8203;:21\]&#8203;:
> > > perl \-wle '$\[=1 while $=\-\-'
> > > Segmentation fault \(core dumped\)
> > 
> > I can't reproduce this with bleadperl\. I suppose that the recent
> > parser or format changes fixed it anyway \(but I don't know what was the
> > original cause of the error\.\)
> 
> For what it's worth\, I get the segmentation fault in bleadperl \(@&#8203;22352\) on my
> machine\.  Here's a GDB backtrace and my perl \-V in case it's useful \(I don't
> consider myself competent enough right now to debug or fix it\, but I'd like to
> do what I can to help\)\.

Funny thing\, if I add \-MO=Concise to this command\-line I \*do\* get the
segfault \(and the same backtrace as you do\.\) Moreover replacing $= by $x
still produces the segfault\.

**Comment by p5pRT** [comment]
### From @rgs

Rafael Garcia\-Suarez wrote&#8203;:
>
> Michael W Thelen wrote&#8203;:
> >
> > \* Rafael Garcia\-Suarez \<rgarciasuarez@&#8203;free\.fr> \[2004\-02\-24 10&#8203;:21\]&#8203;:
> > > > perl \-wle '$\[=1 while $=\-\-'
> > > > Segmentation fault \(core dumped\)
> > > 
> > > I can't reproduce this with bleadperl\. I suppose that the recent
> > > parser or format changes fixed it anyway \(but I don't know what was the
> > > original cause of the error\.\)
> > 
> > For what it's worth\, I get the segmentation fault in bleadperl \(@&#8203;22352\) on my
> > machine\.  Here's a GDB backtrace and my perl \-V in case it's useful \(I don't
> > consider myself competent enough right now to debug or fix it\, but I'd like to
> > do what I can to help\)\.
> 
> Funny thing\, if I add \-MO=Concise to this command\-line I \*do\* get the
> segfault \(and the same backtrace as you do\.\) Moreover replacing $= by $x
> still produces the segfault\.

OK found it\.
The fix is quite simple :

Change 22371 by rgs@&#8203;rgs\-home on 2004/02/24 22&#8203;:34&#8203;:06

&nbsp;        Fix a segfault during optree construction\. \(bug \#27024\)

Affected files \.\.\.

\.\.\. //depot/perl/op\.c\#611 edit
\.\.\. //depot/perl/t/comp/parser\.t\#15 edit

Differences \.\.\.

==== //depot/perl/op\.c\#611 \(text\) ====

@&#8203;@&#8203; \-3577\,6 \+3577\,10 @&#8203;@&#8203;
&nbsp;        \}
&nbsp;     \}
 
\+    /\* if block is null\, the next append\_elem\(\) would put UNSTACK\, a scalar
\+     \* op\, in listop\. This is wrong\. \[perl \#27024\] \*/
\+    if \(\!block\)
\+       block = newOP\(OP\_NULL\, 0\);
&nbsp;     listop = append\_elem\(OP\_LINESEQ\, block\, newOP\(OP\_UNSTACK\, 0\)\);
&nbsp;     o = new\_logop\(OP\_AND\, 0\, &expr\, &listop\);
 

==== //depot/perl/t/comp/parser\.t\#15 \(text\) ====

@&#8203;@&#8203; \-9\,7 \+9\,7 @&#8203;@&#8203;
 \}
 
 require "\./test\.pl";
\-plan\( tests => 43 \);
\+plan\( tests => 44 \);
 
 eval '%@&#8203;x=0;';
 like\( $@&#8203;\, qr/^Can't modify hash dereference in repeat \\\(x\\\)/\, '%@&#8203;x=0' \);
@&#8203;@&#8203; \-147\,3 \+147\,11 @&#8203;@&#8203;
&nbsp;     eval q\{ sub f \{ @&#8203;a=@&#8203;b=@&#8203;c;  \{use\} \} \};
&nbsp;     like\( $@&#8203;\, qr/syntax error/\, "use without body" \);
 \}
\+
\+\# Bug \#27024
\+\{
\+    \# this used to segfault \(because $\[=1 is optimized away to a null block\)
\+    my $x;
\+    $\[ = 1 while $x;
\+    pass\(\);
\+\}

**Comment by p5pRT** [comment]
@rgs - Status changed from 'open' to 'resolved'
