### ISSUE TITLE
perl-5.9.0 SegFault during cpan> r

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7184]
Migrated from [rt.perl.org#27769](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=27769) (status was 'resolved')

Searchable as RT27769$

**Comment by p5pRT** [comment]
### From martin.thurn@ngc.com

#### Created by martin.thurn@ngc.com

This is a bug report for perl from martin\.thurn@&#8203;ngc\.com\,
generated with the help of perlbug 1\.34 running under perl v5\.9\.0\.


\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

I have CPAN 1\.76\_01; during the 'cpan> r' command\, perl SegFaults
while eval\-ing the $VERSION string of the 2397th module inspected\.  If
I install or remove modules\, it always dies on the 2397th one\.

Here is a stack trace


\#0  0x00136f64 in S\_save\_scalar\_at \(my\_perl=0x1fe078\, sptr=0x21cf720\) at scope\.c&#8203;:221
221                         || \!SvMAGIC\(sv\)\->mg\_virtual\->svt\_set\)
\(gdb\) where
\#0  0x00136f64 in S\_save\_scalar\_at \(my\_perl=0x1fe078\, sptr=0x21cf720\) at scope\.c&#8203;:221
\#1  0x00137178 in Perl\_save\_scalar \(my\_perl=0x1fe078\, gv=0x2136b30\) at scope\.c&#8203;:246
\#2  0x000dca9c in Perl\_pp\_gvsv \(my\_perl=0x1fe078\) at pp\_hot\.c&#8203;:46
\#3  0x000b5ec8 in Perl\_runops\_debug \(my\_perl=0x1fe078\) at dump\.c&#8203;:1443
\#4  0x0002fa64 in S\_run\_body \(my\_perl=0x1fe078\, oldscope=1\) at perl\.c&#8203;:1727
\#5  0x0002f358 in perl\_run \(my\_perl=0x1fe078\) at perl\.c&#8203;:1651
\#6  0x00027510 in main \(argc=2\, argv=0xffbefc14\, env=0xffbefc20\) at perlmain\.c&#8203;:86
\(gdb\) p \*sptr
$1 = \(SV \*\) 0x215a83c
\(gdb\) p \*\*sptr
$2 = \{sv\_any = 0x58e590\, sv\_refcnt = 1\, sv\_flags = 7\}

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl v5.9.0:

Configured by mthurn at Thu Mar 11 16:19:04 EST 2004.

Summary of my perl5 (revision 5.0 version 9 subversion 0) configuration:
  Platform:
    osname=solaris, osvers=2.8, archname=sun4-solaris-thread-multi
    uname='sunos copper 5.8 generic_108528-29 sun4u sparc '
    config_args=''
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-DDEBUGGING -D_REENTRANT -fno-strict-aliasing -I/usr/local/include -I/opt/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-g',
    cppflags='-D_REENTRANT -fno-strict-aliasing -I/usr/local/include -I/opt/local/include'
    ccversion='', gccversion='3.0.3', gccosandvers='solaris2.8'
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=4321
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib -L/opt/local/lib '
    libpth=/usr/local/lib /opt/local/lib /usr/lib /usr/ccs/lib
    libs=-lsocket -lnsl -ldb -ldl -lm -lpthread -lc
    perllibs=-lsocket -lnsl -ldl -lm -lpthread -lc
    libc=, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags=' -Wl,-E  -z ignore -z lazyload -z combreloc'
    cccdlflags='-fPIC', lddlflags=' -Wl,-E -G -G  -z ignore -z lazyload -z combreloc -L/usr/local/lib -L/opt/local/lib'

Locally applied patches:
    


@INC for perl v5.9.0:
    /PROJECTS/TIR/lib/perl5
    /usr/local/lib/perl5/5.9.0/sun4-solaris-thread-multi
    /usr/local/lib/perl5/5.9.0
    /usr/local/lib/perl5/site_perl/5.9.0/sun4-solaris-thread-multi
    /usr/local/lib/perl5/site_perl/5.9.0
    /usr/local/lib/perl5/site_perl/5.8.2
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.9.0:
    HOME=/accts/mthurn
    LANG=C
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=.:/usr/local/bin:/bin:/usr/ucb:/usr/openwin/bin:/usr/X11R5/bin:/usr/sbin:/usr/ccs/bin:/accts/mthurn/bin:/PROJECTS/TIR/bin:/DATA/Tools:/usr/java1.2/bin:/apps/DOOM:/usr/local/games:/usr/local/apache2/bin
    PERL5LIB=/PROJECTS/TIR/lib/perl5
    PERLDOC=-t
    PERL_BADLANG (unset)
    SHELL=/bin/tcsh

```
</details>

**Comment by p5pRT** [comment]
### From @iabyn

On Fri\, Mar 19\, 2004 at 02&#8203;:57&#8203;:31PM \-0000\, Thurn\, Martin wrote&#8203;:
> I have CPAN 1\.76\_01; during the 'cpan> r' command\, perl SegFaults
> while eval\-ing the $VERSION string of the 2397th module inspected\.  If
> I install or remove modules\, it always dies on the 2397th one\.
> 
> Here is a stack trace
> 
> 
> \#0  0x00136f64 in S\_save\_scalar\_at \(my\_perl=0x1fe078\, sptr=0x21cf720\) at scope\.c&#8203;:221
> 221                         || \!SvMAGIC\(sv\)\->mg\_virtual\->svt\_set\)
> \(gdb\) where
> \#0  0x00136f64 in S\_save\_scalar\_at \(my\_perl=0x1fe078\, sptr=0x21cf720\) at scope\.c&#8203;:221
> \#1  0x00137178 in Perl\_save\_scalar \(my\_perl=0x1fe078\, gv=0x2136b30\) at scope\.c&#8203;:246
> \#2  0x000dca9c in Perl\_pp\_gvsv \(my\_perl=0x1fe078\) at pp\_hot\.c&#8203;:46
> \#3  0x000b5ec8 in Perl\_runops\_debug \(my\_perl=0x1fe078\) at dump\.c&#8203;:1443
> \#4  0x0002fa64 in S\_run\_body \(my\_perl=0x1fe078\, oldscope=1\) at perl\.c&#8203;:1727
> \#5  0x0002f358 in perl\_run \(my\_perl=0x1fe078\) at perl\.c&#8203;:1651
> \#6  0x00027510 in main \(argc=2\, argv=0xffbefc14\, env=0xffbefc20\) at perlmain\.c&#8203;:86
> \(gdb\) p \*sptr
> $1 = \(SV \*\) 0x215a83c
> \(gdb\) p \*\*sptr
> $2 = \{sv\_any = 0x58e590\, sv\_refcnt = 1\, sv\_flags = 7\}

Do you mean you have >2397 CPAN modules installed locally? If so\, it going
to be a bit of a pain to reproduce locally here\.

The code at fault is&#8203;:

&nbsp;    /\* if it's a special scalar or if it has no 'set' magic\,
&nbsp;     \* propagate the SvREADONLY flag\. \-\-rgs 20030922 \*/
&nbsp;    for \(mg = SvMAGIC\(sv\); mg; mg = mg\->mg\_moremagic\) \{
&nbsp;        if \(SvMAGIC\(sv\)\->mg\_type == '\\0'
&nbsp;            || \!SvMAGIC\(sv\)\->mg\_virtual\->svt\_set\)
&nbsp;        \{
&nbsp;        SvFLAGS\(sv\) |= SvREADONLY\(osv\);
&nbsp;        break;
&nbsp;        \}
&nbsp;    \}

There appears to be a thinko here in that in the loop\, mg progresses along
the chain of magic\, but the test in the loop always examines the head of
the chain\. However\, this shouldn't cause the core dump\. It looks like
mg\_virtual is null for some reason\. Does anyone know whether this is
legal?

In the meantime Martin\, would it be possible for you to set a breakpoint
on the line in question\, and print out the value of sv at that point?
ie

b scope\.c&#8203;:220
cond 1 mg\->mg\_virtual == 0
run
\.\.\.
call Perl\_sv\_dump\(my\_perl\,sv\)

Thanks\.


\-\- 
A power surge on the Bridge is rapidly and correctly diagnosed as a faulty
capacitor by the highly\-trained and competent engineering staff\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#9

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @rgs

Dave Mitchell wrote in perl\.perl5\.porters :
> 
> The code at fault is&#8203;:
> 
>     /\* if it's a special scalar or if it has no 'set' magic\,
>      \* propagate the SvREADONLY flag\. \-\-rgs 20030922 \*/
>     for \(mg = SvMAGIC\(sv\); mg; mg = mg\->mg\_moremagic\) \{
>         if \(SvMAGIC\(sv\)\->mg\_type == '\\0'
>             || \!SvMAGIC\(sv\)\->mg\_virtual\->svt\_set\)
>         \{
>         SvFLAGS\(sv\) |= SvREADONLY\(osv\);
>         break;
>         \}
>     \}
> 
> There appears to be a thinko here in that in the loop\, mg progresses along
> the chain of magic\, but the test in the loop always examines the head of
> the chain\. However\, this shouldn't cause the core dump\. It looks like
> mg\_virtual is null for some reason\. Does anyone know whether this is
> legal?

Well\, other places in the code test the non\-nullness of vtables\. Good
catches\.

**Comment by p5pRT** [comment]
### From martin.thurn@ngc.com

> Do you mean you have >2397 CPAN modules installed locally? If 
> so\, it going
> to be a bit of a pain to reproduce locally here\.

Sorry I'm a CPAN junkie ;\-\)  Yes indeed I have more than 10\,000 \.pm files under /usr/local/lib/perl5\.\.\.

It seems that Perl\_sv\_dump\(\) calls the same code that is crashing?  So it crashes during the dump?  See partial gdb session below\.  If I don't disable 1\, it stops on that line again instead of segfault\.

=====

Breakpoint 1\, S\_save\_scalar\_at \(my\_perl=0x1fe078\, sptr=0x216c178\) at scope\.c&#8203;:221
221                         || \!SvMAGIC\(sv\)\->mg\_virtual\->svt\_set\)
\(gdb\) disable 1
\(gdb\) call Perl\_sv\_dump\(my\_perl\,sv\)
\[LWP    3         exited\]

Program received signal SIGSEGV\, Segmentation fault\.
0x00136f64 in S\_save\_scalar\_at \(my\_perl=0x1fe078\, sptr=0x216c178\) at scope\.c&#8203;:221
221                         || \!SvMAGIC\(sv\)\->mg\_virtual\->svt\_set\)
The program being debugged was signaled while in a function called from GDB\.
GDB remains in the frame where the signal was received\.
To change this behavior use "set unwindonsignal on"
Evaluation of the expression containing the function \(Perl\_sv\_dump\) will be abandoned\.

 \- \- Martin



> \-\-\-\-\-Original Message\-\-\-\-\-
> From&#8203;: Dave Mitchell via RT \[mailto&#8203;:perlbug\-followup@&#8203;perl\.org\]
> Sent&#8203;: Wednesday\, March 24\, 2004 7&#8203;:35 AM
> To&#8203;: Thurn\, Martin
> Subject&#8203;: Re&#8203;: \[perl \#27769\] perl\-5\.9\.0 SegFault during cpan> r
> 
>

**Comment by p5pRT** [comment]
### From @iabyn

On Wed\, Mar 24\, 2004 at 07&#8203;:51&#8203;:49AM \-0800\, Thurn\, Martin wrote&#8203;:
> > Do you mean you have >2397 CPAN modules installed locally? If 
> > so\, it going
> > to be a bit of a pain to reproduce locally here\.
> 
> Sorry I'm a CPAN junkie ;\-\)  Yes indeed I have more than 10\,000 \.pm
> files under /usr/local/lib/perl5\.\.\.

The mind boggles ;\-\)

Rafael has applied a patch to bleedperl which guards against a certain null
pointer being dereferenced\. I've included it below in case you want to
try it againt 5\.9\.0\. I suspect it will cure your problem\, since in
particular\, version object magic has that null pointer\, and you said it
crashed when it was evaling the $VERSION strings of modules\.

Dave\.

\-\- 
Please note that ash\-trays are provided for the use of smokers\,
whereas the floor is provided for the use of all patrons\.
&nbsp;    \-\- Bill Royston


Change 22578 by rgs@&#8203;rgs\-home on 2004/03/24 13&#8203;:54&#8203;:31

&nbsp;    Good catch from Dave Mitchell; plus a null pointer protection\.

Affected files \.\.\.

\.\.\. //depot/perl/scope\.c\#121 edit

Differences \.\.\.

==== //depot/perl/scope\.c\#121 \(text\) ====
Index&#8203;: perl/scope\.c
<details><summary>Inline Patch</summary>

```diff
--- perl/scope.c#120~22509~	Tue Mar 16 10:19:52 2004
+++ perl/scope.c	Wed Mar 24 05:54:31 2004
@@ -217,8 +217,8 @@
 	/* if it's a special scalar or if it has no 'set' magic,
 	 * propagate the SvREADONLY flag. --rgs 20030922 */
 	for (mg = SvMAGIC(sv); mg; mg = mg->mg_moremagic) {
-	    if (SvMAGIC(sv)->mg_type == '\0'
-		    || !SvMAGIC(sv)->mg_virtual->svt_set)
+	    if (mg->mg_type == '\0'
+		    || !(mg->mg_virtual && mg->mg_virtual->svt_set))
 	    {
 		SvFLAGS(sv) |= SvREADONLY(osv);
 		break;
End of Patch.
```
</details>

**Comment by p5pRT** [comment]
### From martin.thurn@ngc.com

> > Sorry I'm a CPAN junkie ;\-\)  Yes indeed I have more than 10\,000 \.pm
> > files under /usr/local/lib/perl5\.\.\.
> 
> The mind boggles ;\-\)

Actually 15\,847 total files\, "only" 5808 \.pm files

With the patch 22578\, my segfault does not happen\.  Thank you\!

 \- \- Martin

**Comment by p5pRT** [comment]
### From nick@ing-simmons.net

Dave Mitchell \<davem@&#8203;fdisolutions\.com> writes&#8203;:
>
>There appears to be a thinko here in that in the loop\, mg progresses along
>the chain of magic\, but the test in the loop always examines the head of
>the chain\. However\, this shouldn't cause the core dump\. It looks like
>mg\_virtual is null for some reason\. Does anyone know whether this is
>legal?

I think it can be for '~' magic used by XS code to attach data to 
an SV but which doesn't really affect SVs get/set 

>
>In the meantime Martin\, would it be possible for you to set a breakpoint
>on the line in question\, and print out the value of sv at that point?
>ie
>
>b scope\.c&#8203;:220
>cond 1 mg\->mg\_virtual == 0
>run
>\.\.\.
>call Perl\_sv\_dump\(my\_perl\,sv\)
>
>Thanks\.

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From martin.thurn@ngc.com

This bug is still present in perl\-5\.9\.1
\(Sorry it took me so long to install enough CPAN modules to reproduce it ;\-\)
Applying the patch referenced below fixes the problem\.
I recommend that you make sure this patch gets applied to 5\.9\.2 or whatever the next release is going to be\!  Thank you

 \- \- Martin



> \-\-\-\-\-Original Message\-\-\-\-\-
> From&#8203;: Dave Mitchell \[mailto&#8203;:davem@&#8203;fdisolutions\.com\]
> Sent&#8203;: Wednesday\, March 24\, 2004 16&#8203;:08
> To&#8203;: Thurn\, Martin
> Cc&#8203;: 'perlbug\-followup@&#8203;perl\.org'
> Subject&#8203;: Re&#8203;: \[perl \#27769\] perl\-5\.9\.0 SegFault during cpan> r
> 
> 
> On Wed\, Mar 24\, 2004 at 07&#8203;:51&#8203;:49AM \-0800\, Thurn\, Martin wrote&#8203;:
> > > Do you mean you have >2397 CPAN modules installed locally? If 
> > > so\, it going
> > > to be a bit of a pain to reproduce locally here\.
> > 
> > Sorry I'm a CPAN junkie ;\-\)  Yes indeed I have more than 10\,000 \.pm
> > files under /usr/local/lib/perl5\.\.\.
> 
> The mind boggles ;\-\)
> 
> Rafael has applied a patch to bleedperl which guards against 
> a certain null
> pointer being dereferenced\. I've included it below in case you want to
> try it againt 5\.9\.0\. I suspect it will cure your problem\, since in
> particular\, version object magic has that null pointer\, and 
> you said it
> crashed when it was evaling the $VERSION strings of modules\.
> 
> Dave\.
> 
> \-\- 
> Please note that ash\-trays are provided for the use of smokers\,
> whereas the floor is provided for the use of all patrons\.
>     \-\- Bill Royston
> 
> 
> Change 22578 by rgs@&#8203;rgs\-home on 2004/03/24 13&#8203;:54&#8203;:31
> 
>     Good catch from Dave Mitchell; plus a null pointer protection\.
> 
> Affected files \.\.\.
> 
> \.\.\. //depot/perl/scope\.c\#121 edit
> 
> Differences \.\.\.
> 
> ==== //depot/perl/scope\.c\#121 \(text\) ====
> Index&#8203;: perl/scope\.c
> \-\-\- perl/scope\.c\#120~22509~    Tue Mar 16 10&#8203;:19&#8203;:52 2004
> \+\+\+ perl/scope\.c    Wed Mar 24 05&#8203;:54&#8203;:31 2004
> @&#8203;@&#8203; \-217\,8 \+217\,8 @&#8203;@&#8203;
>      /\* if it's a special scalar or if it has no 'set' magic\,
>       \* propagate the SvREADONLY flag\. \-\-rgs 20030922 \*/
>      for \(mg = SvMAGIC\(sv\); mg; mg = mg\->mg\_moremagic\) \{
> \-        if \(SvMAGIC\(sv\)\->mg\_type == '\\0'
> \-            || \!SvMAGIC\(sv\)\->mg\_virtual\->svt\_set\)
> \+        if \(mg\->mg\_type == '\\0'
> \+            || \!\(mg\->mg\_virtual && mg\->mg\_virtual\->svt\_set\)\)
>          \{
>          SvFLAGS\(sv\) |= SvREADONLY\(osv\);
>          break;
> End of Patch\.
>

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, May 25\, 2004 at 02&#8203;:56&#8203;:23PM \-0700\, Thurn\, Martin wrote&#8203;:
> This bug is still present in perl\-5\.9\.1

The patch was applied shortly after the cut\-off date for 5\.9\.1; it
will be present in 5\.9\.2\.

Dave\.

\-\- 
Red sky at night \- gerroff my land\!
Red sky at morning \- gerroff my land\!
&nbsp;    \-\- old farmers' sayings \#14
