### ISSUE TITLE
Storable free_context() crash

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7206]
Migrated from [rt.perl.org#28099](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=28099) (status was 'rejected')

Searchable as RT28099$

**Comment by p5pRT** [comment]
### From root@site-3.infogears.com

#### Created by root@site-3.infogears.com


This is a bug report for perl from root@&#8203;site\-3\.infogears\.com\,
generated with the help of perlbug 1\.34 running under perl v5\.8\.3\.


\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

Crasher in 5\.8\.3

backtrace&#8203;:

\#0  0x403f2d2a in free\_context \(cxt=0xbe9e898\) at Storable\.xs&#8203;:1465
\#1  0x403fb0e2 in do\_store \(f=0x0\, sv=0xc1064f4\, optype=1\, network\_order=1\, res=0xbffff950\)
&nbsp;    at Storable\.xs&#8203;:3529
\#2  0x403fb1eb in net\_mstore \(sv=0xb8b5554\) at Storable\.xs&#8203;:3607
\#3  0x404017dd in XS\_Storable\_net\_mstore \(cv=0x8205968\) at Storable\.c&#8203;:6008
\#4  0x080cc880 in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:2840
\#5  0x080af483 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1438
\#6  0x0806313f in S\_call\_body \(myop=0xbffffb70\, is\_eval=0\) at perl\.c&#8203;:2221
\#7  0x08062dc5 in Perl\_call\_sv \(sv=0x8a1e5cc\, flags=150\) at perl\.c&#8203;:2139
\#8  0x080d6f08 in Perl\_sv\_clear \(sv=0xba564d0\) at sv\.c&#8203;:5109
\#9  0x080d7792 in Perl\_sv\_free \(sv=0xba564d0\) at sv\.c&#8203;:5355
\#10 0x080cdde0 in do\_clean\_objs \(sv=0xba9130c\) at sv\.c&#8203;:385
\#11 0x080cdc98 in S\_visit \(f=0x80cdd0f \<do\_clean\_objs>\) at sv\.c&#8203;:331
\#12 0x080cdf70 in Perl\_sv\_clean\_objs \(\) at sv\.c&#8203;:424
\#13 0x0805fb15 in perl\_destruct \(my\_perl=0x816bba8\) at perl\.c&#8203;:496
\#14 0x0805e576 in main \(argc=5\, argv=0xbffffdf4\, env=0xbffffe0c\) at perlmain\.c&#8203;:88
\#15 0x400a1a67 in \_\_libc\_start\_main \(\) from /lib/i686/libc\.so\.6


In frame \#0 ctx is this&#8203;:


\(gdb\) p cxt
$1 = \(stcxt\_t \*\) 0xbe9e898
\(gdb\) p \*cxt
$2 = \{entry = 0\, optype = 0\, hseen = 0x0\, hook\_seen = 0x0\, aseen = 0x0\, hclass = 0x0\,
&nbsp;  aclass = 0x0\, hook = 0x0\, tagnum = 16\, classnum = \-1\, netorder = 1\, s\_tainted = 0\,
&nbsp;  forgive\_me = \-1\, deparse = \-1\, eval = 0x0\, canonical = \-1\, accept\_future\_minor = 0\,
&nbsp;  s\_dirty = 0\, membuf\_ro = 0\, keybuf = \{arena = 0x0\, asiz = 0\, aptr = 0x0\, aend = 0x0\}\,
&nbsp;  membuf = \{arena = 0xc0d6308 "\\005\\006\\003"\, asiz = 8192\,
&nbsp;    aptr = 0xc0d64b9 "\[data removed\]"\.\.\.\,
&nbsp;    aend = 0xc0d8308 ""\}\, msaved = \{arena = 0x0\, asiz = 0\, aptr = 0x0\,
&nbsp;    aend = 0x0\}\, fio = 0x0\, ver\_major = 0\, ver\_minor = 0\, retrieve\_vtbl = 0x0\, prev = 0x98\,
&nbsp;  my\_sv = 0xba301a8\}


\(gdb\) p prev
$3 = \(stcxt\_t \*\) 0x0

It appears by these lines that if assertions were enabled this would fail\, as prev is null\.

ASSERT\(\!cxt\->s\_dirty\, \("clean context"\)\);
ASSERT\(prev\, \("not freeing root context"\)\);

Any help would be appreciated

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.8.3:

Configured by root at Fri Mar  5 12:02:19 MST 2004.

Summary of my perl5 (revision 5.0 version 8 subversion 3) configuration:
  Platform:
    osname=linux, osvers=2.4.24, archname=i686-linux
    uname='linux 2.4.24 #6 mon feb 9 21:28:02 mst 2004 i686 i686 i386 gnulinux '
    config_args=''
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-DDEBUGGING -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm',
    optimize='-g',
    cppflags='-DDEBUGGING -fno-strict-aliasing -I/usr/local/include -I/usr/include/gdbm'
    ccversion='', gccversion='3.2.2 20030222 (Red Hat Linux 3.2.2-5)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/libc-2.3.2.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.3.2'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.3:
    /usr/local/lib/perl5/5.8.3/i686-linux
    /usr/local/lib/perl5/5.8.3
    /usr/local/lib/perl5/site_perl/5.8.3/i686-linux
    /usr/local/lib/perl5/site_perl/5.8.3
    /usr/local/lib/perl5/site_perl/5.8.2/i686-linux
    /usr/local/lib/perl5/site_perl/5.8.2
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.8.3:
    HOME=/root
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/local/BerkeleyDB.4.2/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/X11R6/bin:/usr/local/pgsql/bin:/usr/local/ibolis-corporate:/usr/local/java/bin:/root/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @nwc10

On Wed\, Mar 31\, 2004 at 01&#8203;:26&#8203;:53AM \-0000\, root@&#8203;site\-3\.infogears\.com \(via RT\) wrote&#8203;:

> Crasher in 5\.8\.3

Are you using the Storable which ships with perl 5\.8\.3\, or a more recent
version downloaded from CPAN?

> Summary of my perl5 \(revision 5\.0 version 8 subversion 3\) configuration&#8203;:
>   Platform&#8203;:
>     osname=linux\, osvers=2\.4\.24\, archname=i686\-linux
>     uname='linux 2\.4\.24 \#6 mon feb 9 21&#8203;:28&#8203;:02 mst 2004 i686 i686 i386 gnulinux '
>     config\_args=''
>     hint=recommended\, useposix=true\, d\_sigaction=define
>     usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
>     useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
>     use64bitint=undef use64bitall=undef uselongdouble=undef
>     usemymalloc=n\, bincompat5005=undef
>   Compiler&#8203;:
>     cc='cc'\, ccflags ='\-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-I/usr/include/gdbm'\,
>     optimize='\-g'\,
>     cppflags='\-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include \-I/usr/include/gdbm'
>     ccversion=''\, gccversion='3\.2\.2 20030222 \(Red Hat Linux 3\.2\.2\-5\)'\, gccosandvers=''

This all looks like a pretty standard unthreaded x86 Linux build\. I've not
seen crashes on x86 Linux\, and the automatic smoke testing machines which
repeatedly build the development versions don't report crashes either\, so
I'm not sure why you see this and we don't\.

What sort of data are you storing? Is it large\, self\-referential data
structures? Or simple data structures with very large strings in them?
Or data structures containing objects that use Storable features such
as freeze and thaw hooks?

Are you able to produce a simple test case which you can supply that
reproduces the crash?

Nicholas Clark

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'stalled'

**Comment by p5pRT** [comment]
p5p@spam.wizbit.be - Status changed from 'stalled' to 'rejected'
