### ISSUE TITLE
Crash on assignment to lexical filehandle

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7262]
Migrated from [rt.perl.org#29102](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=29102) (status was 'resolved')

Searchable as RT29102$

**Comment by p5pRT** [comment]
### From @gisle

#### Created by gisle@ask.upc.no



The following program segfaults&#8203;:

&nbsp;    foo\(\);
&nbsp;    foo\(\);

&nbsp;    sub foo \{
&nbsp;        open\(my $fh\, ">xxx"\) || die;
&nbsp;        $fh = "foo";
&nbsp;    \}

This is the gdb backtrace&#8203;:

&nbsp;    Program received signal SIGSEGV\, Segmentation fault\.
&nbsp;    0x4207c07c in memmove \(\) from /lib/tls/libc\.so\.6
&nbsp;    \(gdb\) bt
&nbsp;    \#0  0x4207c07c in memmove \(\) from /lib/tls/libc\.so\.6
&nbsp;    \#1  0x08146e14 in \_\_libc\_csu\_init \(\)
&nbsp;    \#2  0x080c42c4 in Perl\_pp\_sassign \(\) at pp\_hot\.c&#8203;:109
&nbsp;    \#3  0x080afbf6 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1442
&nbsp;    \#4  0x08062528 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1921
&nbsp;    \#5  0x080620b7 in perl\_run \(my\_perl=0x816dba8\) at perl\.c&#8203;:1840
&nbsp;    \#6  0x0805e5d1 in main \(argc=2\, argv=0xbfffe6d4\, env=0xbfffe6e0\) at perlmain\.c&#8203;:86
&nbsp;    \#7  0x42015704 in \_\_libc\_start\_main \(\) from /lib/tls/libc\.so\.6
&nbsp;    

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl v5.8.4:

Configured by gisle at Fri Apr 23 14:16:58 MEST 2004.

Summary of my perl5 (revision 5 version 8 subversion 4) configuration:
  Platform:
    osname=linux, osvers=2.4.20-20.9smp, archname=i686-linux
    uname='linux ask 2.4.20-20.9smp #1 smp mon aug 18 11:32:15 edt 2003 i686 i686 i386 gnulinux '
    config_args='-Dprefix=/local/perl/5.8.4-debug -Doptimize=-g -ders'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-DDEBUGGING -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm',
    optimize='-g',
    cppflags='-DDEBUGGING -fno-strict-aliasing -I/usr/include/gdbm'
    ccversion='', gccversion='3.2.2 20030222 (Red Hat Linux 3.2.2-5)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =''
    libpth=/lib /usr/lib
    libs=-lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/libc-2.3.2.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.3.2'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fpic', lddlflags='-shared'

Locally applied patches:
    


@INC for perl v5.8.4:
    /local/perl/5.8.4-debug/lib/5.8.4/i686-linux
    /local/perl/5.8.4-debug/lib/5.8.4
    /local/perl/5.8.4-debug/lib/site_perl/5.8.4/i686-linux
    /local/perl/5.8.4-debug/lib/site_perl/5.8.4
    /local/perl/5.8.4-debug/lib/site_perl
    .


Environment for perl v5.8.4:
    HOME=/home/gisle
    LANG=en_US.ISO-8859-1
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/gisle/bin:/local/ccache:/local/perl/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin
    PERLAPP_LIBC_OK=1
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @iabyn

On Fri\, Apr 23\, 2004 at 01&#8203;:21&#8203;:51PM \-0000\, Gisle Aas wrote&#8203;:
> The following program segfaults&#8203;:
> 
>     foo\(\);
>     foo\(\);
> 
>     sub foo \{
>         open\(my $fh\, ">xxx"\) || die;
>         $fh = "foo";
>     \}

Fixed by change \#22746\, and test added by change \#22778\.

Dave\.

\-\- 
The perl5 internals are a complete mess\. It's like Jenga \- to get the
perl5 tower taller and do something new you select a block somewhere in
the middle\, with trepidation pull it out slowly\, and then carefully
balance it somewhere new\, hoping the whole edifice won't collapse as a
result\.
&nbsp;        \- Nicholas Clark\, based on an original by Simon Cozens\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
