### ISSUE TITLE
segfault on perl 5.8.4

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7282]
Migrated from [rt.perl.org#29437](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=29437) (status was 'resolved')

Searchable as RT29437$

**Comment by p5pRT** [comment]
### From gotar@polanet.pl

Hi\!

Here's the sample code&#8203;:

\#v\+
\#\!/usr/bin/perl

use open OUT => '&#8203;:locale';

open F\,'/etc/shadow';
warn "$\!\\n";
\#v\-

If one runs it from unprivileged account he gets "Permission denied"
UNLESS he had set locale producing error message with national letters\,
e\.g\. "Brak dostępu" in polish \(eogonek between 't' and 'p'\)&#8203;:

LC\_ALL=pl\_PL \./perl\-test
zsh&#8203;: segmentation fault  LC\_ALL=pl\_PL \./perl\-test

\-\- 
Tom Pala \<gotar@&#8203;pld\-linux\.org>           http&#8203;://vfmg\.sourceforge\.net/
&nbsp;                              http&#8203;://www\.pld\-linux\.org/Members/gotar/

**Comment by p5pRT** [comment]
### From radek42@gmail.com

\(Probably\) related&#8203;:

$ perl \-Mencoding=latin2 \-Mopen=&#8203;:locale \-wle 'print "\\x\{ea\}"'
"\\x\{a2ad\}" does not map to iso\-8859\-2 at \-e line 1\.
panic&#8203;: sv\_setpvn called with negative strlen at \-e line 1\.
"\\x\{a2aa\}" does not map to iso\-8859\-2\.
\\x\{a2aa\}
$ perl \-Mopen=&#8203;:locale  \-Mencoding=latin2 \-wle 'print "\\x\{ea\}"'
ę

"\\x\{ea\}" eq "\\N\{LATIN SMALL LETTER E WITH OGONEK\}" in the
iso\-8859\-2 charset\.  Using the "\\N\{\}" notation gives exactly
the same output in the examples above\.

My setup&#8203;:

$ locale
LANG=pl\_PL\.ISO\-8859\-2
LC\_CTYPE="pl\_PL\.ISO\-8859\-2"
LC\_NUMERIC="pl\_PL\.ISO\-8859\-2"
LC\_TIME="pl\_PL\.ISO\-8859\-2"
LC\_COLLATE="pl\_PL\.ISO\-8859\-2"
LC\_MONETARY="pl\_PL\.ISO\-8859\-2"
LC\_MESSAGES="pl\_PL\.ISO\-8859\-2"
LC\_PAPER="pl\_PL\.ISO\-8859\-2"
LC\_NAME="pl\_PL\.ISO\-8859\-2"
LC\_ADDRESS="pl\_PL\.ISO\-8859\-2"
LC\_TELEPHONE="pl\_PL\.ISO\-8859\-2"
LC\_MEASUREMENT="pl\_PL\.ISO\-8859\-2"
LC\_IDENTIFICATION="pl\_PL\.ISO\-8859\-2"
LC\_ALL=

$ perl \-V
Summary of my perl5 \(revision 5 version 8 subversion 4\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.5\, archname=athlon\-pld\-linux\-thread\-multi
&nbsp;    uname='linux bongo 2\.6\.5 \#1 sun apr 4 18&#8203;:56&#8203;:17 utc 2004 i686
amd\_athlon\(tm\)\_xp\_1700\+ unknown pld linux '
&nbsp;    config\_args='\-des \-Dcc=athlon\-pld\-linux\-gcc
\-Darchname=athlon\-pld\-linux \-Dcccdlflags=\-fPIC \-Dccdlflags=\-rdynamic
\-Doptimize=\-O2 \-march=athlon \-Duseshrplib \-Dd\_dosuid
\-Dman1dir=/usr/share/man/man1 \-Dman1ext=1 \-Dman3dir=/usr/share/man/man3
\-Dman3ext=3perl \-Dvendorman1=/usr/share/man/man1 \-Dvendorman1ext=1p
\-Dvendorman3=/usr/share/man/man3 \-Dvendorman3ext=3pm
\-Dsiteman1=/usr/local/share/man/man1 \-Dsiteman1ext=1p
\-Dsiteman3=/usr/local/share/man/man3p \-Dsiteman3ext=3pm \-Dprefix=/usr
\-Dvendorprefix=/usr \-Dsiteprefix=/usr/local \-Dlibpth=/usr/lib /lib
\-Dprivlib=/usr/share/perl5/5\.8\.4
\-Darchlib=/usr/lib/perl5/5\.8\.4/athlon\-pld\-linux\-thread\-multi
\-Dsitelib=/usr/local/share/perl5
\-Dsitearch=/usr/local/lib/perl5/5\.8\.0/athlon\-pld\-linux\-thread\-multi
\-Dvendorlib=/usr/share/perl5/vendor\_perl
\-Dvendorarch=/usr/lib/perl5/vendor\_perl/5\.8\.0/athlon\-pld\-linux\-thread\-multi
\-Ui\_db \-Ui\_dbm \-Di\_gdbm \-Ui\_ndbm \-Dlibswanted=dl m c crypt gdbm
\-Dusethreads \-Duselargefiles'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=define use5005threads=undef useithreads=define
usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='athlon\-pld\-linux\-gcc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE
\-DTHREADS\_HAVE\_PIDS \-fno\-strict\-aliasing \-I/usr/local/include
\-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2 \-march=athlon'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS
\-fno\-strict\-aliasing \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='3\.3\.3 \(PLD Linux\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,
lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='athlon\-pld\-linux\-gcc'\, ldflags =''
&nbsp;    libpth=/usr/lib /lib
&nbsp;    libs=\-ldl \-lm \-lpthread \-lc \-lcrypt \-lgdbm
&nbsp;    perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    libc=/lib/libc\-2\.3\.3\.so\, so=so\, useshrplib=true\, libperl=libperl\.so
&nbsp;    gnulibc\_version='2\.3\.3'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic
\-Wl\,\-rpath\,/usr/lib/perl5/5\.8\.4/athlon\-pld\-linux\-thread\-multi/CORE'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: MULTIPLICITY USE\_ITHREADS USE\_LARGE\_FILES
PERL\_IMPLICIT\_CONTEXT
&nbsp;  Built under linux
&nbsp;  Compiled at Apr 26 2004 19&#8203;:54&#8203;:11
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/lib/perl5/5\.8\.0/athlon\-pld\-linux\-thread\-multi
&nbsp;    /usr/local/share/perl5
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.0/athlon\-pld\-linux\-thread\-multi
&nbsp;    /usr/share/perl5/vendor\_perl
&nbsp;    /usr/lib/perl5/5\.8\.4/athlon\-pld\-linux\-thread\-multi
&nbsp;    /usr/share/perl5/5\.8\.4
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, May 08\, 2004 at 10&#8203;:26&#8203;:03AM \-0000\, Tomasz Pala wrote&#8203;:
> \#\!/usr/bin/perl
> 
> use open OUT => '&#8203;:locale';
> 
> open F\,'/etc/shadow';
> warn "$\!\\n";
> \#v\-
> 
> If one runs it from unprivileged account he gets "Permission denied"
> UNLESS he had set locale producing error message with national letters\,
> e\.g\. "Brak dost??pu" in polish \(eogonek between 't' and 'p'\)&#8203;:
> 
> LC\_ALL=pl\_PL \./perl\-test
> zsh&#8203;: segmentation fault  LC\_ALL=pl\_PL \./perl\-test

I couldn't reproduce this with the code above\, but I could with the
following \(using the default locale\)&#8203;:

use open OUT => '&#8203;:locale';
print STDERR "\\x\{100\}\\n";

The printing calls encode\(\) which does \(in the encode\_method\(\) C
function\)&#8203;:

Perl\_warner \(my\_perl=0x81a9988\, err=0x2c\, pat=0x4002ebc0 "\\"\\\\x\{%04lx\}\\" does not map to %s"\)

which then merrily recurses until the stack blows up\.
SAlso happens on Bleed\. I have no particular ideas as to how this should
be fixed\. Ideas\, anyone?

The error message expands to&#8203;:

&nbsp;    "\\x\{0100\}" does not map to iso\-8859\-1

\-\- 
Thank God I'm an atheist\.\.\.\.\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @nwc10

On Sat\, May 08\, 2004 at 10&#8203;:26&#8203;:03AM \-0000\, Tomasz Pala wrote&#8203;:
> \# New Ticket Created by  Tomasz Pala 
> \# Please include the string&#8203;:  \[perl \#29437\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: http&#8203;://rt\.perl\.org&#8203;:80/rt3/Ticket/Display\.html?id=29437 >
> 
> 
> Hi\!
> 
> Here's the sample code&#8203;:
> 
> \#v\+
> \#\!/usr/bin/perl
> 
> use open OUT => '&#8203;:locale';
> 
> open F\,'/etc/shadow';
> warn "$\!\\n";
> \#v\-
> 
> If one runs it from unprivileged account he gets "Permission denied"
> UNLESS he had set locale producing error message with national letters\,
> e\.g\. "Brak dostÄpu" in polish \(eogonek between 't' and 'p'\)&#8203;:
> 
> LC\_ALL=pl\_PL \./perl\-test
> zsh&#8203;: segmentation fault  LC\_ALL=pl\_PL \./perl\-test

Hmm\. Interesting\. I can recreate this\. Here's a section of the stack trace&#8203;:

\#1147 0x080ba90c in Perl\_warner \(err=44\, 
&nbsp;    pat=0x400c1a00 "\\"\\\\x\{%04lx\}\\" does not map to %s"\) at util\.c&#8203;:1346
\#1148 0x400bd5c0 in encode\_method \(enc=0x400f89a8\, dir=0x400f6c00\, 
&nbsp;    src=0x817d230\, check=258\, offset=0x0\, term=0x0\, retcode=0x0\)
&nbsp;    at Encode\.xs&#8203;:154
\#1149 0x400bed6a in XS\_Encode\_\_XS\_encode \(cv=0x8202af0\) at Encode\.xs&#8203;:472
\#1150 0x080d753c in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:2798
\#1151 0x080b7370 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1564
\#1152 0x08063ce6 in S\_call\_body \(myop=0xbf818c10\, is\_eval=0\) at perl\.c&#8203;:2160
\#1153 0x080635b7 in Perl\_call\_sv \(sv=0x966084c\, flags=64\) at perl\.c&#8203;:2039
\#1154 0x08063349 in Perl\_call\_method \(methname=0x400cd52d "encode"\, flags=0\)
&nbsp;    at perl\.c&#8203;:1972
\#1155 0x400cbdf0 in PerlIOEncode\_flush \(f=0x818592c\) at encoding\.xs&#8203;:419
\#1156 0x0814792d in Perl\_PerlIO\_flush \(f=0x818592c\) at perlio\.c&#8203;:1599
\#1157 0x0814a997 in PerlIOBuf\_write \(f=0x818592c\, vbuf=0x966bc80\, count=63\)
&nbsp;    at perlio\.c&#8203;:3727
\#1158 0x400cca7f in PerlIOEncode\_write \(f=0x818592c\, vbuf=0x966bc80\, count=63\)
&nbsp;    at encoding\.xs&#8203;:582
\#1159 0x081477d0 in Perl\_PerlIO\_write \(f=0x818592c\, vbuf=0x966bc80\, count=63\)
&nbsp;    at perlio\.c&#8203;:1576
\#1160 0x080b96ba in Perl\_write\_to\_stderr \(
&nbsp;    message=0x966bc80 "\\"\\\\x\{ac35\}\\" does not map to iso\-8859\-15 at perl\-test line 6\.\\n"\, msglen=63\) at util\.c&#8203;:1021
\#1161 0x080bb3f6 in Perl\_vwarner \(err=44\, 
&nbsp;    pat=0x400c1a00 "\\"\\\\x\{%04lx\}\\" does not map to %s"\, args=0xbf818e34\)
&nbsp;    at util\.c&#8203;:1432
\#1162 0x080ba90c in Perl\_warner \(err=44\, 
&nbsp;    pat=0x400c1a00 "\\"\\\\x\{%04lx\}\\" does not map to %s"\) at util\.c&#8203;:1346



I'm not sure what the true cause is\, let alone the correct fix\, but it appears
that there is an infinite loop within Encode trying to report the error\, and
the SEGV occurs when memory \(probably the C stack\) is exhausted\.

Nicholas Clark

**Comment by p5pRT** [comment]
### From mjtg@cam.ac.uk

Nicholas Clark \<nick@&#8203;ccl4\.org> wrote
> \#1147 0x080ba90c in Perl\_warner \(err=44\, 
>     pat=0x400c1a00 "\\"\\\\x\{%04lx\}\\" does not map to %s"\) at util\.c&#8203;:1346
&nbsp;    \.\.\.
> \#1155 0x400cbdf0 in PerlIOEncode\_flush \(f=0x818592c\) at encoding\.xs&#8203;:419
&nbsp;    \.\.\.
> \#1162 0x080ba90c in Perl\_warner \(err=44\, 
>     pat=0x400c1a00 "\\"\\\\x\{%04lx\}\\" does not map to %s"\) at util\.c&#8203;:1346

Speaking in total ignorance of the code \(and far too lazy to look at it\)\,
let me guess&#8203;:

while \(1\) \{
&nbsp;    Encode is generating a warning because it finds in its buffer a character
&nbsp;    it can't convert\.

&nbsp;    The perlIO routines do a flush\, calling on Encode to flush its buffers\.

&nbsp;    Encode attempts to process the failing character\.
\}

If so\, the fix is presumably to get Encode to step past the character
and/or replace it with something harmless \*before\* generating the warning\.


Mike Guy

**Comment by p5pRT** [comment]
### From @Hugmeir

On Mon May 10 08&#8203;:18&#8203;:54 2004\, mjtg@&#8203;cam\.ac\.uk wrote&#8203;:
> Nicholas Clark \<nick@&#8203;ccl4\.org> wrote
> > \#1147 0x080ba90c in Perl\_warner \(err=44\,
> >     pat=0x400c1a00 "\\"\\\\x\{%04lx\}\\" does not map to %s"\) at
> util\.c&#8203;:1346
>     \.\.\.
> > \#1155 0x400cbdf0 in PerlIOEncode\_flush \(f=0x818592c\) at
> encoding\.xs&#8203;:419
>     \.\.\.
> > \#1162 0x080ba90c in Perl\_warner \(err=44\,
> >     pat=0x400c1a00 "\\"\\\\x\{%04lx\}\\" does not map to %s"\) at
> util\.c&#8203;:1346
> 
> Speaking in total ignorance of the code \(and far too lazy to look at
> it\)\,
> let me guess&#8203;:
> 
> while \(1\) \{
>     Encode is generating a warning because it finds in its buffer a
> character
>     it can't convert\.
> 
>     The perlIO routines do a flush\, calling on Encode to flush its
> buffers\.
> 
>     Encode attempts to process the failing character\.
> \}
> 
> If so\, the fix is presumably to get Encode to step past the character
> and/or replace it with something harmless \*before\* generating the
> warning\.
> 
> 
> Mike Guy
> 


I can't reproduce any of the bugs in this ticket with newer Perls; so it
seems that Encode was fixed\. I vote to close this\.

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @nwc10

On Sun\, Apr 29\, 2012 at 10&#8203;:44&#8203;:24AM \-0700\, Brian Fraser via RT wrote&#8203;:
> On Mon May 10 08&#8203;:18&#8203;:54 2004\, mjtg@&#8203;cam\.ac\.uk wrote&#8203;:
> > Nicholas Clark \<nick@&#8203;ccl4\.org> wrote
> > > \#1147 0x080ba90c in Perl\_warner \(err=44\,
> > >     pat=0x400c1a00 "\\"\\\\x\{%04lx\}\\" does not map to %s"\) at
> > util\.c&#8203;:1346
> >     \.\.\.
> > > \#1155 0x400cbdf0 in PerlIOEncode\_flush \(f=0x818592c\) at
> > encoding\.xs&#8203;:419
> >     \.\.\.
> > > \#1162 0x080ba90c in Perl\_warner \(err=44\,
> > >     pat=0x400c1a00 "\\"\\\\x\{%04lx\}\\" does not map to %s"\) at
> > util\.c&#8203;:1346
> > 
> > Speaking in total ignorance of the code \(and far too lazy to look at
> > it\)\,
> > let me guess&#8203;:
> > 
> > while \(1\) \{
> >     Encode is generating a warning because it finds in its buffer a
> > character
> >     it can't convert\.
> > 
> >     The perlIO routines do a flush\, calling on Encode to flush its
> > buffers\.
> > 
> >     Encode attempts to process the failing character\.
> > \}
> > 
> > If so\, the fix is presumably to get Encode to step past the character
> > and/or replace it with something harmless \*before\* generating the
> > warning\.
> > 
> > 
> > Mike Guy
> > 
> 
> 
> I can't reproduce any of the bugs in this ticket with newer Perls; so it
> seems that Encode was fixed\. I vote to close this\.

I ran this&#8203;:

LC\_ALL=pl\_PL\.ISO8859\-2 \.\./perl/Porting/bisect\.pl \-\-expect\-fail \-\-start perl\-5\.8\.0 \-e 'use open OUT => "&#8203;:locale"; print STDERR "\\x\{100\}\\n";'

It said this&#8203;:

commit 74f6c1ca58b1c40741f55591ab97a77b6751f510
Author&#8203;: Slaven Rezic \<slaven@&#8203;rezic\.de>
Date&#8203;:   Tue Feb 6 00&#8203;:04&#8203;:07 2007 \+0100

&nbsp;    Re&#8203;: \[perl \#41442\] segfault \(dead loop\) with Encoding\, use open :locale\, print STDERR
&nbsp;    Message\-ID&#8203;: \<87veiggt2g\.fsf@&#8203;biokovo\.herceg\.de>

&nbsp;    p4raw\-id&#8203;: //depot/perl@&#8203;30213

:100644 100644 760c921584ee6ced54e6f51ea2657881178689d3 41874528b76a354ab83c6c332b6e317e60f0fe16 M      MANIFEST
:040000 040000 fca5fa13398978ebf037e2770ed4dea2ca10f705 2d1b3562c74933e1446f1b09bcc10cedad48bc55 M      ext
bisect run success
That took 1970 seconds

Seems that 41442 and 29437 are duplicates\.

I guess that if there is something to learn here\, it's that once 29437 was
diagnosed a bit better\, the title of it should have been changed to reflect
the cause\. Which would have made the title closer to that of 41442's title\.

Nicholas Clark
