### ISSUE TITLE
Perl 5.8.3/5.8.4 - ithreads - solaris 5.8 -libpthread - reg.exp seg. fault.

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7300]
Migrated from [rt.perl.org#29650](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=29650) (status was 'resolved')

Searchable as RT29650$

**Comment by p5pRT** [comment]
### From rafiq@joshua.dreamthought.com

Hi All\,

I discovered a bug whilst trying to use template toolkit under a threaded
mod\_perl environment\.  This seg fault didn't occur when tested against a
perl without ithreads\.  I managed to trace the flaw down to one regular
expression\.  On the suggestion of Perrin Harkins off the modperl list\, I'm
submitting this as a bug\.  Not sure if it is\, but it appears so\.  I've
attached a quick sample script which simulates what happens in the
template module where it seg\. faults\.  With this there is an example
template which is simply read into a variable and matched against the
expression\.

The syntax for running this would be perl \-w \./thtest\.pl \./index\.html; you
can rewrite the paths for yourselves\.  I find that it only seg\. faults on
files where it seems to match\.

Tested with both perl 5\.8\.3 and 5\.8\.4\, although I'll just include the
output from 5\.8\.4 which I built with \-DDEBUGGING&#8203;:

=head2 perl \-V

\[rafiq@&#8203;hobbes&#8203;:rafiq\]\[2\]$ perl \-V
Summary of my perl5 \(revision 5 version 8 subversion 4\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=solaris\, osvers=2\.8\, archname=sun4\-solaris\-thread\-multi
&nbsp;    uname='sunos hobbes 5\.8 generic\_108528\-15 sun4u sparc
sunw\,sun\-blade\-100 '
&nbsp;    config\_args='\-Ubincompat5005 \-DDEBUGGGING'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=define use5005threads=undef useithreads=define
usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'\, ccflags ='\-D\_REENTRANT \-fno\-strict\-aliasing
\-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O'\,
&nbsp;    cppflags='\-D\_REENTRANT \-fno\-strict\-aliasing \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='3\.3'\, gccosandvers='solaris2\.8'
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=4321
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,
lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='gcc'\, ldflags =' \-L/usr/local/lib '
&nbsp;    libpth=/usr/local/lib /usr/lib /usr/ccs/lib
&nbsp;    libs=\-lsocket \-lnsl \-lgdbm \-ldl \-lm \-lpthread \-lc
&nbsp;    perllibs=\-lsocket \-lnsl \-ldl \-lm \-lpthread \-lc
&nbsp;    libc=/lib/libc\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-G \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: MULTIPLICITY USE\_ITHREADS USE\_LARGE\_FILES
PERL\_IMPLICIT\_CONTEXT
&nbsp;  Built under solaris
&nbsp;  Compiled at May 17 2004 11&#8203;:04&#8203;:03
&nbsp;  %ENV&#8203;:
&nbsp;    PERL\_INLINE\_JAVE\_JNI="1"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-5\.8\.4/lib
&nbsp;    /usr/local/perl\-5\.8\.4/lib
&nbsp;    /usr/local/perl\-5\.8\.4/lib
&nbsp;    /usr/local/perl\-5\.8\.4/lib
&nbsp;    /appl/awgmdb/perl/lib
&nbsp;    /appl/awgmdb/perl\-5\.8\.3/lib
&nbsp;    /appl/twgmdb/perl/lib
&nbsp;    /appl/twgmdb/perl\-5\.8\.3/lib
&nbsp;    /appl/pwgmdb/perl/lib
&nbsp;    /appl/pwgmdb/perl\-5\.8\.3/lib
&nbsp;    /appl/fwgmdb/perl/lib
&nbsp;    /appl/fwgmdb/perl\-5\.8\.3/lib
&nbsp;    /appl/aagmdb/perl/lib
&nbsp;    /appl/aagmdb/perl\-5\.8\.3/lib
&nbsp;    /appl/tagmdb/perl\-5\.8\.3/lib
&nbsp;    /appl/tagmdb/perl/lib
&nbsp;    /appl/pagmdb/perl\-5\.8\.3/lib
&nbsp;    /appl/pagmdb/perl/lib
&nbsp;    /appl/fagmdb/perl\-5\.8\.3/lib
&nbsp;    /appl/fagmdb/perl/lib
&nbsp;    /usr/zlocal/perl\-5\.8\.3/lib
&nbsp;    /usr/zlocal/perl/lib
&nbsp;    \.

=cut

=head2 appropriate bit of back trace

Segmentation Fault \(core dumped\)
\[rafiq@&#8203;hobbes&#8203;:rafiq\]\[1\]$ gdb \`which perl\` \./core
GNU gdb 6\.0
Copyright 2003 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and you are
welcome to change it and/or distribute copies of it under certain conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for details\.
This GDB was configured as "sparc\-sun\-solaris2\.8"\.\.\.
Core was generated by \`perl \-w \./thtest\.pl
/home/rafiq/Projects/gmdbsite/html/index\.html'\.
Program terminated with signal 11\, Segmentation fault\.
Reading symbols from /lib/libsocket\.so\.1\.\.\.done\.
Loaded symbols for /lib/libsocket\.so\.1
Reading symbols from /lib/libnsl\.so\.1\.\.\.done\.
Loaded symbols for /lib/libnsl\.so\.1
Reading symbols from /lib/libdl\.so\.1\.\.\.done\.
Loaded symbols for /lib/libdl\.so\.1
Reading symbols from /lib/libm\.so\.1\.\.\.done\.
Loaded symbols for /lib/libm\.so\.1
Reading symbols from /lib/libpthread\.so\.1\.\.\.done\.
Loaded symbols for /lib/libpthread\.so\.1
Reading symbols from /lib/libc\.so\.1\.\.\.done\.
Loaded symbols for /lib/libc\.so\.1
Reading symbols from /lib/libmp\.so\.2\.\.\.done\.
Loaded symbols for /lib/libmp\.so\.2
Reading symbols from
/usr/platform/SUNW\,Sun\-Blade\-100/lib/libc\_psr\.so\.1\.\.\.done\.
Loaded symbols for /usr/platform/SUNW\,Sun\-Blade\-100/lib/libc\_psr\.so\.1
Reading symbols from /lib/libthread\.so\.1\.\.\.done\.
Loaded symbols for /lib/libthread\.so\.1
Reading symbols from
/usr/local/perl\-5\.8\.4/lib/auto/threads/threads\.so\.\.\.done\.
Loaded symbols for /usr/local/perl\-5\.8\.4/lib/auto/threads/threads\.so
\#0  0x000e2644 in S\_reginclass \(\)
\(gdb\) bt
\#0  0x000e2644 in S\_reginclass \(\)
Cannot access memory at address 0xfec09f84
\(gdb\)

=cut

Many thanks\,

Rafiq

**Comment by p5pRT** [comment]
### From rafiq@joshua.dreamthought.com

[thtest.pl](https://rt-archive.perl.org/perl5/Ticket/Attachment/87589/62068/thtest.pl)

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, May 17\, 2004 at 10&#8203;:53&#8203;:25AM \-0000\, Rafiq Ismail \(ADMIN\) wrote&#8203;:
> The syntax for running this would be perl \-w \./thtest\.pl \./index\.html; you
> can rewrite the paths for yourselves\.  I find that it only seg\. faults on
> files where it seems to match\.

Thanks for the report\. Is it possible to make available a sample
index\.html which you know causes a segfault?

Thanks\,

Dave\.

\-\- 
Nothing ventured\, nothing lost\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From rafiq@joshua.dreamthought.com

Dave Mitchell via RT said&#8203;:
> On Mon\, May 17\, 2004 at 10&#8203;:53&#8203;:25AM \-0000\, Rafiq Ismail \(ADMIN\) wrote&#8203;:
>> The syntax for running this would be perl \-w \./thtest\.pl \./index\.html;
>> you can rewrite the paths for yourselves\.  I find that it only seg\.
>> faults on files where it seems to match\.
>
> Thanks for the report\. Is it possible to make available a sample
> index\.html which you know causes a segfault?
>

Hi Dave\,

Apologies for having ommited the sample template\.  Friday was a bit of a
crazy day\, not very much unlike today\.\.  still I've attached the file
which gave me problems\.


I hope that this helps\.

Many thanks\,

Raf

**Comment by p5pRT** [comment]
### From @nwc10

On Wed\, May 19\, 2004 at 11&#8203;:20&#8203;:11AM \+0200\, Raf wrote&#8203;:

> Apologies for having ommited the sample template\.  Friday was a bit of a
> crazy day\, not very much unlike today\.\.  still I've attached the file
> which gave me problems\.

The attachment hasn't made it to RT\, and hence hasn't been forwarded on to
the perl5\-porters list\. Did you actually attach it \(something I often forget
to do\)\, or has something stripped it out along the way?

Nicholas Clark

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, May 17\, 2004 at 10&#8203;:53&#8203;:25AM \-0000\, Rafiq Ismail \(ADMIN\) wrote&#8203;:
> I discovered a bug whilst trying to use template toolkit under a threaded
> mod\_perl environment\.  This seg fault didn't occur when tested against a
> perl without ithreads\.  I managed to trace the flaw down to one regular
> expression\.  On the suggestion of Perrin Harkins off the modperl list\, I'm
> submitting this as a bug\.  Not sure if it is\, but it appears so\.  I've
> attached a quick sample script which simulates what happens in the
> template module where it seg\. faults\.  With this there is an example
> template which is simply read into a variable and matched against the
> expression\.
> 
> The syntax for running this would be perl \-w \./thtest\.pl \./index\.html; you
> can rewrite the paths for yourselves\.  I find that it only seg\. faults on
> files where it seems to match\.
> 
> Tested with both perl 5\.8\.3 and 5\.8\.4\, although I'll just include the
> output from 5\.8\.4 which I built with \-DDEBUGGING&#8203;:

Sorry about this report being ignored \- there was some confusion over
whether you had included a sample index\.html \- it hadn't made it to the
list\, but  when I checked on the RT website\, it was sitting there\!

The segfault is being caused by deep recursion in S\_regmatch&#8203;:

&nbsp;    \.\.\.
&nbsp;    \#2373 0x08160eb6 in S\_regmatch \(my\_perl=0x829c938\, prog=0x8317010\) at regexec\.c&#8203;:3291
&nbsp;    \#2374 0x08160666 in S\_regmatch \(my\_perl=0x829c938\, prog=0x8317054\) at regexec\.c&#8203;:3178
&nbsp;    \#2375 0x08160472 in S\_regmatch \(my\_perl=0x829c938\, prog=0x8316ffc\) at regexec\.c&#8203;:3123
&nbsp;    \#2376 0x0815d083 in S\_regtry \(my\_perl=0x829c938\, prog=0x8316fb8\, startpos=0x82fb338 "\<\!DOCTYPE html PUBLIC \\"\-//W3C//DTD HTML 4\.01 Transitional//EN\\">\\n\<html>\\n\<head>\\n  \<title>GMDB Main Page\</title>\\n"\, ' ' \<repeats 72 times>\, "\\n"\, ' ' \<repeats 15 times>\, "\\n "\.\.\.\) at regexec\.c&#8203;:2204

This is\, unfortunately\, the normal outcome for a regex that recurses
too deeply \- do the way the current perl regex engine is implemented\,
and can't be fixed without a major rewrite\.

My only vague handwaving advice would be to rewrite the regex in such a
way that it avoids the deep back\-tracking and recursion\. In particular\,
I suspect that if you could make the '3000' a lot smaller in

&nbsp;    \( \(?&#8203;: \\\\\. | \[^\\$\] \)\{1\,3000\} \) 

The problem might go away\.

Dave\.

\-\- 
Red sky at night \- gerroff my land\!
Red sky at morning \- gerroff my land\!
&nbsp;    \-\- old farmers' sayings \#14

**Comment by p5pRT** [comment]
### From @smpeters

On Mon May 17 03&#8203;:53&#8203;:23 2004\, rafiq@&#8203;joshua\.dreamthought\.com wrote&#8203;:
> Hi All\,
> 
> I discovered a bug whilst trying to use template toolkit under a
> threaded
> mod\_perl environment\.  This seg fault didn't occur when tested against
> a
> perl without ithreads\.  I managed to trace the flaw down to one
> regular
> expression\.  On the suggestion of Perrin Harkins off the modperl list\,
> I'm
> submitting this as a bug\.  Not sure if it is\, but it appears so\.  I've
> attached a quick sample script which simulates what happens in the
> template module where it seg\. faults\.  With this there is an example
> template which is simply read into a variable and matched against the
> expression\.
> 
> The syntax for running this would be perl \-w \./thtest\.pl \./index\.html;
> you
> can rewrite the paths for yourselves\.  I find that it only seg\. faults
> on
> files where it seems to match\.
> 
> Tested with both perl 5\.8\.3 and 5\.8\.4\, although I'll just include the
> output from 5\.8\.4 which I built with \-DDEBUGGING&#8203;:
> 
> =head2 perl \-V
> 
> \[rafiq@&#8203;hobbes&#8203;:rafiq\]\[2\]$ perl \-V
> Summary of my perl5 \(revision 5 version 8 subversion 4\) configuration&#8203;:
>   Platform&#8203;:
>     osname=solaris\, osvers=2\.8\, archname=sun4\-solaris\-thread\-multi
>     uname='sunos hobbes 5\.8 generic\_108528\-15 sun4u sparc
> sunw\,sun\-blade\-100 '
>     config\_args='\-Ubincompat5005 \-DDEBUGGGING'
>     hint=recommended\, useposix=true\, d\_sigaction=define
>     usethreads=define use5005threads=undef useithreads=define
> usemultiplicity=define
>     useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
>     use64bitint=undef use64bitall=undef uselongdouble=undef
>     usemymalloc=n\, bincompat5005=undef
>   Compiler&#8203;:
>     cc='gcc'\, ccflags ='\-D\_REENTRANT \-fno\-strict\-aliasing
> \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
>     optimize='\-O'\,
>     cppflags='\-D\_REENTRANT \-fno\-strict\-aliasing \-I/usr/local/include'
>     ccversion=''\, gccversion='3\.3'\, gccosandvers='solaris2\.8'
>     intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=4321
>     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\,
> longdblsize=16
>     ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,
> lseeksize=8
>     alignbytes=8\, prototype=define
>   Linker and Libraries&#8203;:
>     ld='gcc'\, ldflags =' \-L/usr/local/lib '
>     libpth=/usr/local/lib /usr/lib /usr/ccs/lib
>     libs=\-lsocket \-lnsl \-lgdbm \-ldl \-lm \-lpthread \-lc
>     perllibs=\-lsocket \-lnsl \-ldl \-lm \-lpthread \-lc
>     libc=/lib/libc\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
>     gnulibc\_version=''
>   Dynamic Linking&#8203;:
>     dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags=' '
>     cccdlflags='\-fPIC'\, lddlflags='\-G \-L/usr/local/lib'
> 
> 
> Characteristics of this binary \(from libperl\)&#8203;:
>   Compile\-time options&#8203;: MULTIPLICITY USE\_ITHREADS USE\_LARGE\_FILES
> PERL\_IMPLICIT\_CONTEXT
>   Built under solaris
>   Compiled at May 17 2004 11&#8203;:04&#8203;:03
>   %ENV&#8203;:
>     PERL\_INLINE\_JAVE\_JNI="1"
>   @&#8203;INC&#8203;:
>     /usr/local/perl\-5\.8\.4/lib
>     /usr/local/perl\-5\.8\.4/lib
>     /usr/local/perl\-5\.8\.4/lib
>     /usr/local/perl\-5\.8\.4/lib
>     /appl/awgmdb/perl/lib
>     /appl/awgmdb/perl\-5\.8\.3/lib
>     /appl/twgmdb/perl/lib
>     /appl/twgmdb/perl\-5\.8\.3/lib
>     /appl/pwgmdb/perl/lib
>     /appl/pwgmdb/perl\-5\.8\.3/lib
>     /appl/fwgmdb/perl/lib
>     /appl/fwgmdb/perl\-5\.8\.3/lib
>     /appl/aagmdb/perl/lib
>     /appl/aagmdb/perl\-5\.8\.3/lib
>     /appl/tagmdb/perl\-5\.8\.3/lib
>     /appl/tagmdb/perl/lib
>     /appl/pagmdb/perl\-5\.8\.3/lib
>     /appl/pagmdb/perl/lib
>     /appl/fagmdb/perl\-5\.8\.3/lib
>     /appl/fagmdb/perl/lib
>     /usr/zlocal/perl\-5\.8\.3/lib
>     /usr/zlocal/perl/lib
>     \.
> 
> =cut
> 
> =head2 appropriate bit of back trace
> 
> Segmentation Fault \(core dumped\)
> \[rafiq@&#8203;hobbes&#8203;:rafiq\]\[1\]$ gdb \`which perl\` \./core
> GNU gdb 6\.0
> Copyright 2003 Free Software Foundation\, Inc\.
> GDB is free software\, covered by the GNU General Public License\, and
> you are
> welcome to change it and/or distribute copies of it under certain
> conditions\.
> Type "show copying" to see the conditions\.
> There is absolutely no warranty for GDB\.  Type "show warranty" for
> details\.
> This GDB was configured as "sparc\-sun\-solaris2\.8"\.\.\.
> Core was generated by \`perl \-w \./thtest\.pl
> /home/rafiq/Projects/gmdbsite/html/index\.html'\.
> Program terminated with signal 11\, Segmentation fault\.
> Reading symbols from /lib/libsocket\.so\.1\.\.\.done\.
> Loaded symbols for /lib/libsocket\.so\.1
> Reading symbols from /lib/libnsl\.so\.1\.\.\.done\.
> Loaded symbols for /lib/libnsl\.so\.1
> Reading symbols from /lib/libdl\.so\.1\.\.\.done\.
> Loaded symbols for /lib/libdl\.so\.1
> Reading symbols from /lib/libm\.so\.1\.\.\.done\.
> Loaded symbols for /lib/libm\.so\.1
> Reading symbols from /lib/libpthread\.so\.1\.\.\.done\.
> Loaded symbols for /lib/libpthread\.so\.1
> Reading symbols from /lib/libc\.so\.1\.\.\.done\.
> Loaded symbols for /lib/libc\.so\.1
> Reading symbols from /lib/libmp\.so\.2\.\.\.done\.
> Loaded symbols for /lib/libmp\.so\.2
> Reading symbols from
> /usr/platform/SUNW\,Sun\-Blade\-100/lib/libc\_psr\.so\.1\.\.\.done\.
> Loaded symbols for /usr/platform/SUNW\,Sun\-Blade\-100/lib/libc\_psr\.so\.1
> Reading symbols from /lib/libthread\.so\.1\.\.\.done\.
> Loaded symbols for /lib/libthread\.so\.1
> Reading symbols from
> /usr/local/perl\-5\.8\.4/lib/auto/threads/threads\.so\.\.\.done\.
> Loaded symbols for /usr/local/perl\-5\.8\.4/lib/auto/threads/threads\.so
> \#0  0x000e2644 in S\_reginclass \(\)
> \(gdb\) bt
> \#0  0x000e2644 in S\_reginclass \(\)
> Cannot access memory at address 0xfec09f84
> \(gdb\)
> 
> =cut
> 
> Many thanks\,
> 
> Rafiq
> 


At some point during the past four years\, this bug has been fixed\.  My guess is that the 
"Great Regexp Engine Fix" was the likely cause\.  Anyways\, I've had multiple Perls on multiple 
machines confirm the fix\, so this bug appears to be fully resolved\.

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'resolved'
