### ISSUE TITLE
Problem with autouse (causing Perl to crash)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7307]
Migrated from [rt.perl.org#29708](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=29708) (status was 'resolved')

Searchable as RT29708$

**Comment by p5pRT** [comment]
### From @steve-m-hay

#### Created by @steve-m-hay



I have a problem using the "autouse" pragma which is causing perl 
\(5\.8\.4\) to crash\.  I've reduced it to the following two modules&#8203;:

Foo\.pm
======
package Foo;
use Exporter qw\(\);
our @&#8203;EXPORT = qw\(foo\);
our @&#8203;ISA = qw\(Exporter\);
sub foo\(\) \{ require Bar; Bar&#8203;::bar\(\) \}
1;

Bar\.pm
======
package Bar;
use autouse 'Foo' => qw\(foo\(\)\);
my $done = 0;
sub bar\(\) \{
&nbsp;    return if $done;
&nbsp;    $done = 1;
&nbsp;    print "calling foo\(\) once \.\.\.\\n";
&nbsp;    foo\(\);
&nbsp;    print "\.\.\. ok\\n";
&nbsp;    print "calling foo\(\) again \.\.\.\\n";
&nbsp;    foo\(\);
&nbsp;    print "\.\.\. ok\\n";
\}
1;

Running&#8203;:

&nbsp;    >perl \-MBar \-MFoo \-we "Foo&#8203;::foo\(\)"

produces the output&#8203;:

&nbsp;    calling foo\(\) once \.\.\.
&nbsp;    \.\.\. ok
&nbsp;    calling foo\(\) again \.\.\.

and then perl\.exe crashes with an Access Violation\.  Here's a stacktrace 
from the crash \(under perl\-5\.8\.4\)&#8203;:

Perl\_pp\_entersub\(\) line 2912 \+ 2 bytes
Perl\_runops\_standard\(\) line 24 \+ 3 bytes
S\_run\_body\(long 1\) line 1924
perl\_run\(interpreter \* 0x00223c40\) line 1840 \+ 9 bytes
RunPerl\(int 5\, char \* \* 0x00223c00\, char \* \* 0x00222ba8\) line 202 \+ 6 bytes
PERL\! mainCRTStartup \+ 227 bytes
KERNEL32\! 77e814c7\(\)

The same command\-line runs fine\, producing the second "\.\.\. ok" line\, 
under the "\-d" debugger \(e\.g\. perl \-d&#8203;:ptkdb \-MBar \-MFoo \-we "Foo&#8203;::foo\(\)"\)\.

I can fix it by reversing the order in which the Foo and Bar modules are 
loaded&#8203;:

&nbsp;    >perl \-MFoo \-MBar \-we "Foo&#8203;::foo\(\)"

or by not loading Bar initially&#8203;:

&nbsp;    >perl \-MFoo \-we "Foo&#8203;::foo\(\)"

or by changing the following line within Bar\.pm&#8203;:

&nbsp;    use autouse 'Foo' => qw\(foo\(\)\);

to either&#8203;:

&nbsp;    use autouse 'Foo' => qw\(foo\);

\(\!\!\!\) or simply&#8203;:

&nbsp;    use Foo;

\(understandable\)\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.8.4:

Configured by steveh at Mon Apr 26 14:01:56 2004.

Summary of my perl5 (revision 5 version 8 subversion 4) configuration:
  Platform:
    osname=MSWin32, osvers=4.0, archname=MSWin32-x86-perlio
    uname=''
    config_args='undef'
    hint=recommended, useposix=true, d_sigaction=undef
    usethreads=undef use5005threads=undef useithreads=undef 
usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=undef usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=y, bincompat5005=undef
  Compiler:
    cc='cl', ccflags ='-nologo -Gf -W3 -MD -Zi -DNDEBUG -O1 -DWIN32 
-D_CONSOLE -DNO_STRICT -DHAVE_DES_FCRYPT  -DPERL_DEBUGGING_MSTATS 
-DUSE_PERLIO -DPERL_MSVCRT_READFIX',
    optimize='-MD -Zi -DNDEBUG -O1',
    cppflags='-DWIN32'
    ccversion='', gccversion='', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=undef, longlongsize=8, d_longdbl=define, longdblsize=10
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', 
lseeksize=4
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='link', ldflags ='-nologo -nodefaultlib -debug -opt:ref,icf  
-libpath:"C:\perl5\lib\CORE"  -machine:x86'
    libpth=C:\PROGRA~1\MICROS~2\VC98\lib
    libs=  oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib  
comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib  
netapi32.lib uuid.lib wsock32.lib mpr.lib winmm.lib  version.lib 
odbc32.lib odbccp32.lib msvcrt.lib
    perllibs=  oldnames.lib kernel32.lib user32.lib gdi32.lib 
winspool.lib  comdlg32.lib advapi32.lib shell32.lib ole32.lib 
oleaut32.lib  netapi32.lib uuid.lib wsock32.lib mpr.lib winmm.lib  
version.lib odbc32.lib odbccp32.lib msvcrt.lib
    libc=msvcrt.lib, so=dll, useshrplib=yes, libperl=perl58.lib
    gnulibc_version='undef'
  Dynamic Linking:
    dlsrc=dl_win32.xs, dlext=dll, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags='-dll -nologo -nodefaultlib -debug 
-opt:ref,icf  -libpath:"C:\perl5\lib\CORE"  -machine:x86'

Locally applied patches:
    


@INC for perl v5.8.4:
    C:/perl5/lib
    C:/perl5/site/lib
    .


Environment for perl v5.8.4:
    HOME (unset)
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    
PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\perl5\bin
    PERL_BADLANG (unset)
    SHELL (unset)




------------------------------------------------
Radan Computational Ltd.

The information contained in this message and any files transmitted with it are confidential and intended for the addressee(s) only.  If you have received this message in error or there are any problems, please notify the sender immediately.  The unauthorized use, disclosure, copying or alteration of this message is strictly forbidden.  Note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of Radan Computational Ltd.  The recipient(s) of this message should check it and any attached files for viruses: Radan Computational will accept no liability for any damage caused by any virus transmitted by this email.


```
</details>

**Comment by p5pRT** [comment]
### From @nwc10

On Wed\, May 19\, 2004 at 11&#8203;:00&#8203;:58AM \-0000\, Steve Hay wrote&#8203;:

> I have a problem using the "autouse" pragma which is causing perl 
> \(5\.8\.4\) to crash\.  I've reduced it to the following two modules&#8203;:

$ valgrind \-\-db\-attach=yes \./perl \-Ilib  \-MBar \-MFoo \-we "Foo&#8203;::foo\(\)"
==25808== Memcheck\, a memory error detector for x86\-linux\.
==25808== Copyright \(C\) 2002\-2004\, and GNU GPL'd\, by Julian Seward\.
==25808== Using valgrind\-2\.1\.1\, a program supervision framework for x86\-linux\.
==25808== Copyright \(C\) 2000\-2004\, and GNU GPL'd\, by Julian Seward\.
==25808== For more details\, rerun with&#8203;: \-v
==25808== 
==25808== Syscall param sigaction\(act\) contains uninitialised or unaddressable byte\(s\)
==25808==    at 0x3C0F9025&#8203;: \_\_libc\_sigaction \(in /lib/tls/libc\-2\.3\.2\.so\)
==25808==    by 0x7F&#8203;: ???
==25808==  Address 0x4FFFE980 is on thread 1's stack
==25808== 
==25808== \-\-\-\- Attach to debugger ? \-\-\- \[Return/N/n/Y/y/C/c\] \-\-\-\- n
calling foo\(\) once \.\.\.
\.\.\. ok
calling foo\(\) again \.\.\.
==25808== 
==25808== Invalid read of size 1
==25808==    at 0x80F3148&#8203;: Perl\_pp\_entersub \(pp\_hot\.c&#8203;:2701\)
==25808==    by 0x80CBDF2&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:1564\)
==25808==    by 0x80668DF&#8203;: S\_run\_body \(perl\.c&#8203;:1796\)
==25808==    by 0x8066308&#8203;: perl\_run \(perl\.c&#8203;:1714\)
==25808==  Address 0x2C is not stack'd\, malloc'd or free'd
==25808== 
==25808== \-\-\-\- Attach to debugger ? \-\-\- \[Return/N/n/Y/y/C/c\] \-\-\-\- y

\.\.\.

0x080f3148 in Perl\_pp\_entersub \(my\_perl=0x3c20d024\) at pp\_hot\.c&#8203;:2701
2701                if \(AvREAL\(av\)\) \{
\(gdb\) print av
$1 = \(AV \*\) 0x3c20d6c0
\(gdb\) print \*av
$2 = \{sv\_any = 0x0\, sv\_refcnt = 2147483529\, sv\_flags = 8388608\}
\(gdb\) where
\#0  0x080f3148 in Perl\_pp\_entersub \(my\_perl=0x3c20d024\) at pp\_hot\.c&#8203;:2701
\#1  0x080cbdf3 in Perl\_runops\_debug \(my\_perl=0x3c20d024\) at dump\.c&#8203;:1564
\#2  0x080668e0 in S\_run\_body \(my\_perl=0x3c20d024\, oldscope=1\) at perl\.c&#8203;:1796
\#3  0x08066309 in perl\_run \(my\_perl=0x3c20d024\) at perl\.c&#8203;:1714
\#4  0x0805fdc8 in main \(argc=6\, argv=0x4fffec24\, env=0x4fffec40\)
&nbsp;    at perlmain\.c&#8203;:86


2147483529 is 0x7fffff89

I'm not sure where to go next\. That first sigaction warning is irritating\,
but I don't think that it's relevant\.

Nicholas Clark

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, May 29\, 2004 at 09&#8203;:00&#8203;:25PM \+0100\, Nicholas Clark wrote&#8203;:
> On Wed\, May 19\, 2004 at 11&#8203;:00&#8203;:58AM \-0000\, Steve Hay wrote&#8203;:
> 
> > I have a problem using the "autouse" pragma which is causing perl 
> > \(5\.8\.4\) to crash\.  I've reduced it to the following two modules&#8203;:

it can be reduced to the following&#8203;:

&nbsp;    $done = 0;
&nbsp;    sub f \{
&nbsp;    return if $done;
&nbsp;    $done = 1;
&nbsp;    my $anon = sub \{ goto &f \};
&nbsp;    &$anon;
&nbsp;    f\(\);
&nbsp;    \}

&nbsp;    f\(\);

basically the first time f\(\) is called at nested depth 2\, its via goto &f\,
and asince the caller of the goto was invoked without args \(&$anon\)\, an
@&#8203;\_ array wasn't created at slot 0 in the depth\-2 pad\.
The next time f\(\) was called convetionally deth 2\, there was already
a pad for this depth\, but slot 0 contained &PL\_sv\_undef rather than an AV\.

I've fixed it so that goto &f unconditionally creates a new @&#8203;\_ in slot 0\.

Dave\.

\-\- 
The Enterprise successfully ferries an alien VIP from one place to another
without serious incident\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#7

Change 22870 by davem@&#8203;davem\-percy on 2004/05/30 14&#8203;:30&#8203;:45

&nbsp;    \[perl \#29708\] Problem with autouse \(causing Perl to crash\)
&nbsp;    @&#8203;\_ sometimes wasn't getting created right

Affected files \.\.\.

\.\.\. //depot/perl/pad\.c\#32 edit
\.\.\. //depot/perl/pp\_ctl\.c\#394 edit
\.\.\. //depot/perl/t/op/goto\.t\#22 edit

Differences \.\.\.

==== //depot/perl/pad\.c\#32 \(text\) ====

@&#8203;@&#8203; \-1523\,6 \+1523\,9 @&#8203;@&#8203;
 =cut
 \*/
 
\+/\* XXX pad\_push is now always called with has\_args == 1\. Get rid of
\+ \* this arg at some point \*/
\+
 void
 Perl\_pad\_push\(pTHX\_ PADLIST \*padlist\, int depth\, int has\_args\)
 \{

==== //depot/perl/pp\_ctl\.c\#394 \(text\) ====

@&#8203;@&#8203; \-2329\,7 \+2329\,7 @&#8203;@&#8203;
&nbsp;         else \{
&nbsp;             if \(CvDEPTH\(cv\) == 100 && ckWARN\(WARN\_RECURSION\)\)
&nbsp;             sub\_crush\_depth\(cv\);
\-            pad\_push\(padlist\, CvDEPTH\(cv\)\, cx\->blk\_sub\.hasargs\);
\+            pad\_push\(padlist\, CvDEPTH\(cv\)\, 1\);
&nbsp;         \}
&nbsp;         PAD\_SET\_CUR\(padlist\, CvDEPTH\(cv\)\);
&nbsp;         if \(cx\->blk\_sub\.hasargs\)

==== //depot/perl/t/op/goto\.t\#22 \(xtext\) ====

@&#8203;@&#8203; \-7\,7 \+7\,7 @&#8203;@&#8203;
&nbsp;     @&#8203;INC = qw\(\. \.\./lib\);
 \}
 
\-print "1\.\.32\\n";
\+print "1\.\.33\\n";
 
 require "test\.pl";
 
@&#8203;@&#8203; \-229\,6 \+229\,19 @&#8203;@&#8203;
 print "not ";
 returned\_label : print "ok 32 \- done to returned\_label\\n";
 
\+\# \[perl \#29708\] \- goto &foo could leave foo\(\) at depth two with
\+\# @&#8203;\_ == PL\_sv\_undef\, causing a coredump
\+
\+
\+my $r = runperl\(
\+    prog =>
\+    'sub f \{ return if $d; $d=1; my $a=sub \{goto &f\}; &$a; f\(\) \} f\(\); print qq\(ok\\n\)'\,
\+    stderr => 1
\+    \);
\+print "not " if $r ne "ok\\n";
\+print "ok 33 \- avoid pad without an \\@&#8203;\_\\n";
\+
\+
 exit;
 
 bypass&#8203;:

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
