### ISSUE TITLE
segfault in eval (5.8.x)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7313]
Migrated from [rt.perl.org#29845](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=29845) (status was 'resolved')

Searchable as RT29845$

**Comment by p5pRT** [comment]
### From stas@stason.org

#### Created by stas@stason.org



% perl test\.pl
Scalar found where operator expected at \(eval 1\) line 6\, near "'refs'
&nbsp;         $parsed"
&nbsp;         \(Missing operator before
&nbsp;         $parsed?\)
Segmentation fault \(core dumped\)

code&#8203;:

\#\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- start \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
my $code = \<\<'EOF';
sub handler \{
&nbsp;     my $r = shift;
&nbsp;     plan $r;
&nbsp;     \{
&nbsp;         no strict 'refs'
&nbsp;         $parsed\->$method;
&nbsp;     \}
\}
EOF

eval \{ $code \};
eval $code;
\#\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- end \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

yes\, there is a syntax error\. and yes there are two evals\. The
segfault was appearing and disappearing as I was trying to make the
shortest possible test\. Even comments were affecting the case\. It seems that I 
can't make it shorter\. Looks like some parser's problem\.

back trace&#8203;:

\#0  0x40083540 in Perl\_pad\_free \(my\_perl=0x804d008\, po=4\) at pad\.c&#8203;:1166
1166            SvPADTMP\_off\(PL\_curpad\[po\]\);
\(gdb\) bt
\#0  0x40083540 in Perl\_pad\_free \(my\_perl=0x804d008\, po=4\) at pad\.c&#8203;:1166
\#1  0x4006dd92 in Perl\_op\_clear \(my\_perl=0x804d008\, o=0x8051860\) at op\.c&#8203;:460
\#2  0x4006d91e in Perl\_op\_free \(my\_perl=0x804d008\, o=0x8051860\) at op\.c&#8203;:324
\#3  0x4006d8bd in Perl\_op\_free \(my\_perl=0x804d008\, o=0x8069210\) at op\.c&#8203;:312
\#4  0x40078d09 in Perl\_newATTRSUB \(my\_perl=0x804d008\, floor=157\, o=0x8060258\,
&nbsp;     proto=0x0\, attrs=0x0\, block=0x8069210\) at op\.c&#8203;:4311
\#5  0x4006b1cb in Perl\_yyparse \(my\_perl=0x804d008\) at perly\.y&#8203;:355
\#6  0x400ffc1c in S\_doeval \(my\_perl=0x804d008\, gimme=128\, startop=0x0\,
&nbsp;     outside=0x804dd3c\, seq=2\) at pp\_ctl\.c&#8203;:2816
\#7  0x40102570 in Perl\_pp\_entereval \(my\_perl=0x804d008\) at pp\_ctl\.c&#8203;:3410
\#8  0x4009993f in Perl\_runops\_debug \(my\_perl=0x804d008\) at dump\.c&#8203;:1442
\#9  0x4003eba6 in S\_run\_body \(my\_perl=0x804d008\, oldscope=1\) at perl\.c&#8203;:1921
\#10 0x4003e5e8 in perl\_run \(my\_perl=0x804d008\) at perl\.c&#8203;:1840
\#11 0x0804947e in main \(argc=2\, argv=0xbffff414\, env=0xbffff420\)
&nbsp;     at perlmain\.c&#8203;:86

reproducable with all ithreads\-enabled 5\.8\.x perls\. Doesn't happen
with non\-threaded perls and not with blead perl\.

<details><summary>Perl Info</summary>

```

Flags:
     category=core
     severity=low

Site configuration information for perl v5.8.4:

Configured by stas at Sat May  8 23:36:56 PDT 2004.

Summary of my perl5 (revision 5 version 8 subversion 4) configuration:
   Platform:
     osname=linux, osvers=2.6.3-9mdk, archname=i686-linux-thread-multi
     uname='linux rabbit.stason.org 2.6.3-9mdk #1 fri apr 23 16:41:09 edt 2004 
i686 unknown unknown gnulinux '
     config_args='-des -Dprefix=/home/stas/perl/5.8.4-ithread -Dusethreads 
-Doptimize=-g -Duseshrplib -Dusedevel -Accflags=-DDEBUG_LEAKING_SCALARS'
     hint=recommended, useposix=true, d_sigaction=define
     usethreads=define use5005threads=undef useithreads=define 
usemultiplicity=define
     useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
     use64bitint=undef use64bitall=undef uselongdouble=undef
     usemymalloc=n, bincompat5005=undef
   Compiler:
     cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS 
-DDEBUG_LEAKING_SCALARS -DDEBUGGING -fno-strict-aliasing -I/usr/local/include 
-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm',
     optimize='-g',
     cppflags='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS 
-DDEBUG_LEAKING_SCALARS -DDEBUGGING -fno-strict-aliasing -I/usr/local/include 
-I/usr/include/gdbm'
     ccversion='', gccversion='3.3.2 (Mandrake Linux 10.0 3.3.2-6mdk)', 
gccosandvers=''
     intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
     d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
     ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', 
lseeksize=8
     alignbytes=4, prototype=define
   Linker and Libraries:
     ld='cc', ldflags =' -L/usr/local/lib'
     libpth=/usr/local/lib /lib /usr/lib
     libs=-lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lpthread -lc
     perllibs=-lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
     libc=/lib/libc-2.3.3.so, so=so, useshrplib=true, libperl=libperl.so
     gnulibc_version='2.3.3'
   Dynamic Linking:
     dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E 
-Wl,-rpath,/home/stas/perl/5.8.4-ithread/lib/5.8.4/i686-linux-thread-multi/CORE'
     cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:



@INC for perl v5.8.4:
     /home/stas/perl/5.8.4-ithread/lib/5.8.4/i686-linux-thread-multi
     /home/stas/perl/5.8.4-ithread/lib/5.8.4
     /home/stas/perl/5.8.4-ithread/lib/site_perl/5.8.4/i686-linux-thread-multi
     /home/stas/perl/5.8.4-ithread/lib/site_perl/5.8.4
     /home/stas/perl/5.8.4-ithread/lib/site_perl
     .


Environment for perl v5.8.4:
     HOME=/home/stas
     LANG=en_GB
     LANGUAGE=en_GB:en
     LC_ADDRESS=en_CA
     LC_COLLATE=en_GB
     LC_CTYPE=en_GB
     LC_IDENTIFICATION=en_CA
     LC_MEASUREMENT=en_CA
     LC_MESSAGES=en_GB
     LC_MONETARY=en_CA
     LC_NAME=en_CA
     LC_NUMERIC=en_CA
     LC_PAPER=en_CA
     LC_TELEPHONE=en_CA
     LC_TIME=en_GB
     LD_LIBRARY_PATH (unset)
     LOGDIR (unset)
 
PATH=/usr//bin:/bin:/usr/bin:.:/usr/local/bin:/usr/X11R6/bin/:/usr/games:/home/stas/bin:/home/stas/bin:/usr/local/bin:/usr/X11R6/bin:/usr/java/j2re1.4.0/bin/
     PERLDOC_PAGER=less -R
     PERL_BADLANG (unset)
     SHELL=/bin/tcsh


-- 
__________________________________________________________________
Stas Bekman            JAm_pH ------> Just Another mod_perl Hacker
http://stason.org/     mod_perl Guide ---> http://perl.apache.org
mailto:stas@stason.org http://use.perl.org http://apacheweek.com
http://modperlbook.org http://apache.org   http://ticketmaster.com

```
</details>

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, May 25\, 2004 at 04&#8203;:19&#8203;:19AM \-0000\, Stas Bekman wrote&#8203;:
> \#\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- start \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> my $code = \<\<'EOF';
> sub handler \{
>      my $r = shift;
>      plan $r;
>      \{
>          no strict 'refs'
>          $parsed\->$method;
>      \}
> \}
> EOF
> 
> eval \{ $code \};
> eval $code;
> \#\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- end \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> 
> yes\, there is a syntax error\. and yes there are two evals\. The segfault
> was appearing and disappearing as I was trying to make the shortest
> possible test\. Even comments were affecting the case\. It seems that I
> can't make it shorter\. Looks like some parser's problem\.

I can't reproduce it on any of my 5\.8\.x perls \- presumably due to the
sensitivity you mention\. However\, it does look suspiciously similar to
the bug I fixed with change \#22306&#8203;:

&nbsp;    \[perl \#25824\] Segault with sub x \{ shift; @&#8203;a = @&#8203;b; eval \+\{ use \} \}

which is in 5\.9\.1 but not integrated into maint\. This was when an error
while parsing a use statement \(or in your case a no statement\) caused the
parser to get confused about what the current sub was \(since use's are
effectively wrapped in a BEGIN sub\)\.

I presume it hasn't been integrated into maint because the patch as
written needs to be applied on top of the byacc/bison parser changes;
in fact it was the difficulty of working with the old byacc system while
developing this patch that prompted me to do the bison cleanup\.

Dave\.

\-\- 
In the 70's we wore flares because we didn't know any better\.
What possible excuse does the current generation have?

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @nwc10

On Sun\, May 30\, 2004 at 11&#8203;:09&#8203;:24PM \+0100\, Dave Mitchell wrote&#8203;:
> I presume it hasn't been integrated into maint because the patch as
> written needs to be applied on top of the byacc/bison parser changes;

Indeed\, and the byacc/bison changes aren't in because no\-one's been able
to verify that they work on MVS\. I must find more arms to twist\.

Nicholas Clark

**Comment by p5pRT** [comment]
### From @smpeters

> % perl test\.pl
> Scalar found where operator expected at \(eval 1\) line 6\, near "'refs'
>          $parsed"
>          \(Missing operator before
>          $parsed?\)
> Segmentation fault \(core dumped\)
> 
> code&#8203;:
> 
> \#\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- start \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> my $code = \<\<'EOF';
> sub handler \{
>      my $r = shift;
>      plan $r;
>      \{
>          no strict 'refs'
>          $parsed\->$method;
>      \}
> \}
> EOF
> 
> eval \{ $code \};
> eval $code;
> \#\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- end \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> 
> yes\, there is a syntax error\. and yes there are two evals\. The
> segfault was appearing and disappearing as I was trying to make the
> shortest possible test\. Even comments were affecting the case\. It
> seems that I
> can't make it shorter\. Looks like some parser's problem\.
> 

I'm thinking this might be fixed now in at least 5\.8\.6\.  When I run the above\, I get\.\.\.

Useless use of private variable in void context at rt\_29845\.pl line 18\.
Scalar found where operator expected at \(eval 1\) line 6\, near "'refs'
&nbsp;         $parsed"
&nbsp;        \(Missing operator before 
&nbsp;         $parsed?\)

Unless anyone else can repeat this segfault in 5\.8\.6 or later\, I'm assuming this has been 
resolved\.

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @hvds

"Steve Peters via RT" \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
\[snip code\]
:> yes\, there is a syntax error\. and yes there are two evals\. The
:> segfault was appearing and disappearing as I was trying to make the
:> shortest possible test\. Even comments were affecting the case\. It
:> seems that I
:> can't make it shorter\. Looks like some parser's problem\.
:> 
:
:I'm thinking this might be fixed now in at least 5\.8\.6\.  When I run the above\, I get\.\.\.
:
:Useless use of private variable in void context at rt\_29845\.pl line 18\.
:Scalar found where operator expected at \(eval 1\) line 6\, near "'refs'
:         $parsed"
:        \(Missing operator before 
:         $parsed?\)
:
:Unless anyone else can repeat this segfault in 5\.8\.6 or later\, I'm assuming this has been 
:resolved\.

With this sort of SEGV that apperas and disappears with minor changes\,
that isn't necessarily a safe bet\.

Since the nature of such bugs tends to be highly dependent on precise
locations of things in memory\, you'll often find that the given test case
doesn't SEGV on another platform\, or on a different build\. One approach
is a scattergun \- adding a comment at the beginning of the code\, and
running repeatedly with different sizes of comment \(and maybe again with
the comment at the end\) would be one way to get statistical evidence that
the bug is gone\. Alternatively\, Valgrind might be able to offer good
supporting evidence \- I think it would normally pick up such bugs even
in the cases that they manage to avoid a coredump\.

Hugo

**Comment by p5pRT** [comment]
### From @iabyn

On Fri\, Jun 10\, 2005 at 03&#8203;:24&#8203;:25AM \-0000\, Steve Peters via RT wrote&#8203;:
> >          no strict 'refs'
\.\.\.

> I'm thinking this might be fixed now in at least 5\.8\.6\.  When I run the above\, I get\.\.\.

It's still present\. The fix for coping with syntax errors in use \(and no\)
hasn't been integrated into maint\, due to changes in the way perly\.y is
processed \(and no\-one on a EBCDIC system being available to test that
change\)\.

\-\- 
Fire extinguisher \(n\) a device for holding open fire doors\.

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'resolved' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

This was fixed in perl 5\.10\.0 by change 22306/500bed\.

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
