### ISSUE TITLE
perl 5.6.1 parser dumps core undef'ing file handle in subroutine

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7367]
Migrated from [rt.perl.org#30297](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=30297) (status was 'resolved')

Searchable as RT30297$

**Comment by p5pRT** [comment]
### From perlbug@fivevalve.com

#### Created by perlbug@fivevalve.com



This program causes perl5\.6\.1 to dump core&#8203;:

sub foo \{
&nbsp;    open YPM\, "/etc/passwd";
&nbsp;    undef YPM;
\}

$ gdb /home/y/bin/perl5\.6\.1 perl5\.6\.1\.core
GNU gdb 4\.18 \(FreeBSD\)
Copyright 1998 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and you are
welcome to change it and/or distribute copies of it under certain conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for details\.
This GDB was configured as "i386\-unknown\-freebsd"\.\.\.Deprecated bfd\_read called at /home/src/gnu/usr\.bin/binutils/gdb/\.\./\.\./\.\./\.\./contrib/gdb/gdb/dbxread\.c line 2627 in elfstab\_build\_psymtabs
Deprecated bfd\_read called at /home/src/gnu/usr\.bin/binutils/gdb/\.\./\.\./\.\./\.\./contrib/gdb/gdb/dbxread\.c line 933 in fill\_symbuf

Core was generated by \`perl5\.6\.1'\.
Program terminated with signal 11\, Segmentation fault\.
Reading symbols from /home/y/lib/perl5/5\.6\.1/i386\-freebsd/CORE/libperl\.so\.\.\.
done\.
Reading symbols from /usr/lib/libm\.so\.2\.\.\.done\.
Reading symbols from /usr/lib/libc\.so\.4\.\.\.done\.
Reading symbols from /usr/lib/libcrypt\.so\.2\.\.\.done\.
Reading symbols from /usr/lib/libutil\.so\.3\.\.\.done\.
Reading symbols from /usr/libexec/ld\-elf\.so\.1\.\.\.done\.
\#0  Perl\_linklist \(o=0x8059400\) at op\.c&#8203;:900
900     op\.c&#8203;: No such file or directory\.
\(gdb\) where
\#0  Perl\_linklist \(o=0x8059400\) at op\.c&#8203;:900
\#1  0x280a19b6 in Perl\_linklist \(o=0x80593e0\) at op\.c&#8203;:900
\#2  0x280a198f in Perl\_linklist \(o=0x8059400\) at op\.c&#8203;:897
\#3  0x280a19b6 in Perl\_linklist \(o=0x8059320\) at op\.c&#8203;:900
\#4  0x280a198f in Perl\_linklist \(o=0x8059460\) at op\.c&#8203;:897
\#5  0x280a9990 in Perl\_newATTRSUB \(floor=84\, o=0x8059300\, proto=0x0\,
&nbsp;    attrs=0x0\, block=0x8059320\) at op\.c&#8203;:4656
\#6  0x2809efee in Perl\_yyparse \(\) at perly\.y&#8203;:323
\#7  0x28080fb9 in S\_parse\_body \(env=0x0\, xsinit=0x8049268 \<xs\_init>\)
&nbsp;    at perl\.c&#8203;:1317
\#8  0x28080360 in perl\_parse \(my\_perl=0x804d030\, xsinit=0x8049268 \<xs\_init>\,
&nbsp;    argc=3\, argv=0x9fbff88c\, env=0x0\) at perl\.c&#8203;:895
\#9  0x804921d in main \(argc=3\, argv=0x9fbff88c\, env=0x9fbff89c\)
&nbsp;    at perlmain\.c&#8203;:50


Removing the "undef YPM;" statement fixes it\, as does removing
"sub foo \{" and the corresponding closing "\}"\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.6.1:

Configured by rr at Thu Mar  7 23:10:53 PST 2002.

Summary of my perl5 (revision 5.0 version 6 subversion 1) configuration:
  Platform:
    osname=freebsd, osvers=4, archname=i386-freebsd
    uname='FreeBSD pkgbuild2.corp.yahoo.com 4.1-YAHOO-20001028 FreeBSD 4.1-YAHOO-20001028 #0: Sat Dec  1 16:59:23 PST 2001     root@pkgbuild2.corp.yahoo.com:/home/obj/home/src/sys/YAHOO  i386'
    config_args=''
    hint=previous, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='gcc', ccflags ='-fno-strict-aliasing -I/home/y/include -I/usr/local/include -march=pentiumpro -pipe',
    optimize='-g -O2',
    cppflags='-fno-strict-aliasing -I/home/y/include -I/usr/local/include -march=pentiumpro -pipe'
    ccversion='', gccversion='2.95.3 20010315 (release)', gccosandvers='freebsdelf'
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags ='-Wl,-E  -L/home/y/lib -L/usr/local/lib'
    libpth=/usr/lib /home/y/lib /usr/local/lib
    libs=-lm -lc -lcrypt -lutil
    perllibs=-lm -lc -lcrypt -lutil
    libc=, so=so, useshrplib=true, libperl=libperl.so
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='  -Wl,-R/home/y/lib/perl5/5.6.1/i386-freebsd/CORE -Wl,-R/home/y/lib -Wl,-R/usr/local/lib'
    cccdlflags='-DPIC -fpic', lddlflags='-shared  -L/home/y/lib -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.6.1:
    /home/y/lib/perl5/5.6.1/i386-freebsd
    /home/y/lib/perl5/5.6.1
    /home/y/lib/perl5/site_perl/5.6.1/i386-freebsd
    /home/y/lib/perl5/site_perl/5.6.1
    /home/y/lib/perl5/site_perl
    .


Environment for perl v5.6.1:
    HOME=/homes/andrewe
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH=/home/y/libexec/oracle/lib:
    LOGDIR (unset)
    PATH=/home/y/libexec/oracle/bin:/home/y/bin:/usr/local/sbin:/sbin:/usr/sbin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @iabyn

On Wed\, Jun 16\, 2004 at 02&#8203;:43&#8203;:05AM \-0000\, perlbug @&#8203; fivevalve\. com wrote&#8203;:
> This program causes perl5\.6\.1 to dump core&#8203;:
> 
> sub foo \{
>     open YPM\, "/etc/passwd";
>     undef YPM;
> \}
> 

Thanks for the report\. This has been fixed in \.5\.80 and later\.

\-\- 
The perl5 internals are a complete mess\. It's like Jenga \- to get the
perl5 tower taller and do something new you select a block somewhere in
the middle\, with trepidation pull it out slowly\, and then carefully
balance it somewhere new\, hoping the whole edifice won't collapse as a
result\.
&nbsp;        \- Nicholas Clark\, based on an original by Simon Cozens\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
