### ISSUE TITLE
memory corruption compiling malformed program

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7394]
Migrated from [rt.perl.org#30518](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=30518) (status was 'resolved')

Searchable as RT30518$

**Comment by p5pRT** [comment]
### From andrew@pimlott.net

#### Created by andrew@pimlott.net



This program crashes my perl during compilation \(ie\, when run with \-c\)\.
It's fairly sensitive to the details&#8203;: removing one of the my variables\, the
right side of the assignment\, or the prototype all cause perl to give an
appropriate syntax error\.

&nbsp;    sub bar \(&\);
&nbsp;    sub foo \{
&nbsp;        my \($a\, $b\) = @&#8203;\_;
&nbsp;        bar sub \{ and \};
&nbsp;    \}

This is the backtrace from debugperl in the Debian perl\-debug package\.  \(I
don't know why it doesn't have line numbers\.\)

&nbsp;    \#0  0x080a2aa9 in Perl\_pad\_free \(\)
&nbsp;    \#1  0x0808f59d in Perl\_op\_clear \(\)
&nbsp;    \#2  0x0808f4c0 in Perl\_op\_free \(\)
&nbsp;    \#3  0x0808f48f in Perl\_op\_free \(\)
&nbsp;    \#4  0x080984ef in Perl\_newATTRSUB \(\)
&nbsp;    \#5  0x0808d168 in Perl\_yyparse \(\)
&nbsp;    \#6  0x08062687 in S\_parse\_body \(\)
&nbsp;    \#7  0x00000001 in ?? \(\)
&nbsp;    \#8  0xbffff88c in ?? \(\)
&nbsp;    \#9  0x0816c2a0 in ?? \(\)
&nbsp;    \#10 0xbffff6d4 in ?? \(\)
&nbsp;    \#11 0x00000020 in ?? \(\)
&nbsp;    \#12 0x00000020 in ?? \(\)
&nbsp;    \#13 0x080b5aad in Perl\_my\_setenv \(\)
&nbsp;    Previous frame inner to this frame \(corrupt stack?\)

Andrew

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.8.3:

Configured by Debian Project at Sat Mar 27 17:07:14 EST 2004.

Summary of my perl5 (revision 5.0 version 8 subversion 3) configuration:
  Platform:
    osname=linux, osvers=2.4.25-ti1211, archname=i386-linux-thread-multi
    uname='linux kosh 2.4.25-ti1211 #1 thu feb 19 18:20:12 est 2004 i686 gnulinux '
    config_args='-Dusethreads -Duselargefiles -Dccflags=-DDEBIAN -Dcccdlflags=-fPIC -Darchname=i386-linux -Dprefix=/usr -Dprivlib=/usr/share/perl/5.8 -Darchlib=/usr/lib/perl/5.8 -Dvendorprefix=/usr -Dvendorlib=/usr/share/perl5 -Dvendorarch=/usr/lib/perl5 -Dsiteprefix=/usr/local -Dsitelib=/usr/local/share/perl/5.8.3 -Dsitearch=/usr/local/lib/perl/5.8.3 -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 -Dsiteman1dir=/usr/local/man/man1 -Dsiteman3dir=/usr/local/man/man3 -Dman1ext=1 -Dman3ext=3perl -Dpager=/usr/bin/sensible-pager -Uafs -Ud_csh -Uusesfio -Uusenm -Duseshrplib -Dlibperl=libperl.so.5.8.3 -Dd_dosuid -des'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -DDEBIAN -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O3',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -DDEBIAN -fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='3.3.3 (Debian 20040314)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lgdbm -lgdbm_compat -ldb -ldl -lm -lpthread -lc -lcrypt
    perllibs=-ldl -lm -lpthread -lc -lcrypt
    libc=/lib/libc-2.3.2.so, so=so, useshrplib=true, libperl=libperl.so.5.8.3
    gnulibc_version='2.3.2'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.3:
    /home/andrew/lib/perl
    /home/andrew/local/lib/perl
    /etc/perl
    /usr/local/lib/perl/5.8.3
    /usr/local/share/perl/5.8.3
    /usr/lib/perl5
    /usr/share/perl5
    /usr/lib/perl/5.8
    /usr/share/perl/5.8
    /usr/local/lib/site_perl
    .


Environment for perl v5.8.3:
    HOME=/home/andrew
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/andrew/bin:/usr/sbin:/sbin:/home/andrew/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games
    PERL5LIB=/home/andrew/lib/perl:/home/andrew/local/lib/perl
    PERL_BADLANG (unset)
    SHELL=/usr/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @rgs

andrew@&#8203;pimlott\.net \(via RT\) wrote&#8203;:
> This program crashes my perl during compilation \(ie\, when run with \-c\)\.
> It's fairly sensitive to the details&#8203;: removing one of the my variables\, the
> right side of the assignment\, or the prototype all cause perl to give an
> appropriate syntax error\.
> 
>     sub bar \(&\);
>     sub foo \{
>         my \($a\, $b\) = @&#8203;\_;
>         bar sub \{ and \};
>     \}

I can reproduce this with maintperl \(compiled with threads\); without
threads\, I have no segfault\, but valgrind shows errors; on the other
hand\, bleadperl is fine\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From stas@stason.org

Rafael Garcia\-Suarez wrote&#8203;:
> andrew@&#8203;pimlott\.net \(via RT\) wrote&#8203;:
> 
>>This program crashes my perl during compilation \(ie\, when run with \-c\)\.
>>It's fairly sensitive to the details&#8203;: removing one of the my variables\, the
>>right side of the assignment\, or the prototype all cause perl to give an
>>appropriate syntax error\.
>>
>>    sub bar \(&\);
>>    sub foo \{
>>        my \($a\, $b\) = @&#8203;\_;
>>        bar sub \{ and \};
>>    \}
> 
> 
> I can reproduce this with maintperl \(compiled with threads\); without
> threads\, I have no segfault\, but valgrind shows errors; on the other
> hand\, bleadperl is fine\.

Yes\, it's the problem with threads perl\. I've reported the exact same trace 
with a different source code here&#8203;:
http&#8203;://rt\.perl\.org/rt3/Ticket/Display\.html?id=29845

where David Mitchell also points to fix \#22306 in blead\, which wasn't 
backported to 5\.8\.x

\-\- 
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
Stas Bekman            JAm\_pH \-\-\-\-\-\-> Just Another mod\_perl Hacker
http&#8203;://stason\.org/     mod\_perl Guide \-\-\-> http&#8203;://perl\.apache\.org
mailto&#8203;:stas@&#8203;stason\.org http&#8203;://use\.perl\.org http&#8203;://apacheweek\.com
http&#8203;://modperlbook\.org http&#8203;://apache\.org   http&#8203;://ticketmaster\.com

**Comment by p5pRT** [comment]
### From @nwc10

On Tue\, Jun 29\, 2004 at 10&#8203;:35&#8203;:09AM \-0700\, Stas Bekman wrote&#8203;:

> Yes\, it's the problem with threads perl\. I've reported the exact same trace 
> with a different source code here&#8203;:
> http&#8203;://rt\.perl\.org/rt3/Ticket/Display\.html?id=29845
> 
> where David Mitchell also points to fix \#22306 in blead\, which wasn't 
> backported to 5\.8\.x

because it depends on the change from yacc to bison\, which in turn won't
be backported until we know it works on MVS\, and this is proving
troublesome to ascertain\.

Nicholas Clark

**Comment by p5pRT** [comment]
### From @cpansprout

This was fixed in perl 5\.10\.0 by change 22306/500bed\.

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
