### ISSUE TITLE
localizing $foo, then glob-aliasing to an LVALUE segfaults when trying to restore.

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7432]
Migrated from [rt.perl.org#30778](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=30778) (status was 'resolved')

Searchable as RT30778$

**Comment by p5pRT** [comment]
### From james@mastros.biz

#### Created by james@mastros.biz



Hello\, everybody\.  I was recently playing with LVALUEs trying to get
exercise 2 of http&#8203;://perlmonks\.org/?node=how's\+your\+perl?\+\(II\)\, and managed
to get perl to segfault\.  While I was doing strange things with it at the
time\, a segfault isn't a good response\, ever\.

Code&#8203;:
\#\!/usr/bin/perl
use warnings;
use Devel&#8203;::Peek;
$|=1;

\{
&nbsp;    local $foo;    \# Local \*foo instead\, and it works\.
&nbsp;    my $x;         \# Only to shut up warnings \-\- both lexical and global $x exhibit this behavior
&nbsp;    \*foo=\\pos\($x\); \# Neccessary
&nbsp;    Dump \*foo;
&nbsp;    print "Got here\\n";
\}
print "Got here\\n";
\_\_DATA\_\_

Output&#8203;:
SV = PVGV\(0x8192ef8\) at 0x8164ee0
&nbsp;  REFCNT = 5
&nbsp;  FLAGS = \(GMG\,SMG\,MULTI\,IN\_PAD\)
&nbsp;  IV = 0
&nbsp;  NV = 0
&nbsp;  MAGIC = 0x8190960
&nbsp;    MG\_VIRTUAL = &PL\_vtbl\_glob
&nbsp;    MG\_TYPE = PERL\_MAGIC\_glob\(\*\)
&nbsp;    MG\_OBJ = 0x8164ee0
&nbsp;  NAME = "foo"
&nbsp;  NAMELEN = 3
&nbsp;  GvSTASH = 0x814cb48   "main"
&nbsp;  GP = 0x8192f30
&nbsp;    SV = 0x8164f40
&nbsp;    REFCNT = 1
&nbsp;    IO = 0x0
&nbsp;    FORM = 0x0
&nbsp;    AV = 0x0
&nbsp;    HV = 0x0
&nbsp;    CV = 0x0
&nbsp;    CVGEN = 0x0
&nbsp;    GPFLAGS = 0x0
&nbsp;    LINE = 7
&nbsp;    FILE = "howsyourperl2\.pl\_segfault"
&nbsp;    FLAGS = 0xa
&nbsp;    EGV = 0x8164ee0     "foo"
Got here
&nbsp;    
Note the lack of the second "Got here" line\.

Backtrace&#8203;:
\(gdb\) bt
\#0  0x080b27ce in Perl\_magic\_setpos \(\)
\#1  0x080af335 in Perl\_mg\_set \(\)
\#2  0x080e76d0 in Perl\_leave\_scope \(\)
\#3  0x080e5fac in Perl\_pop\_scope \(\)
\#4  0x080ecfb4 in Perl\_pp\_leaveloop \(\)
\#5  0x080bbbb9 in Perl\_runops\_standard \(\)
\#6  0x080635e8 in perl\_run \(\)
\#7  0x080633f5 in perl\_run \(\)
\#8  0x0805fb9f in main \(\)

Sorry\, I don't have a 5\.8\.5 or debugging perl handy \-\- let me know if either
is neccessary\.
&nbsp;        
Thanks\!
&nbsp;       \-=\- James Mastros\,
&nbsp;       theorbtwo

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.8.4:

Configured by Debian Project at Wed May 12 00:32:16 EST 2004.

Summary of my perl5 (revision 5 version 8 subversion 4) configuration:
  Platform:
    osname=linux, osvers=2.4.26-ti1211, archname=i386-linux-thread-multi
    uname='linux kosh 2.4.26-ti1211 #1 sat apr 24 14:46:58 est 2004 i686 gnulinux '
    config_args='-Dusethreads -Duselargefiles -Dccflags=-DDEBIAN -Dcccdlflags=-fPIC -Darchname=i386-linux -Dprefix=/usr -Dprivlib=/usr/share/perl/5.8 -Darchlib=/usr/lib/perl/5.8 -Dvendorprefix=/usr -Dvendorlib=/usr/share/perl5 -Dvendorarch=/usr/lib/perl5 -Dsiteprefix=/usr/local -Dsitelib=/usr/local/share/perl/5.8.4 -Dsitearch=/usr/local/lib/perl/5.8.4 -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 -Dsiteman1dir=/usr/local/man/man1 -Dsiteman3dir=/usr/local/man/man3 -Dman1ext=1 -Dman3ext=3perl -Dpager=/usr/bin/sensible-pager -Uafs -Ud_csh -Uusesfio -Uusenm -Duseshrplib -Dlibperl=libperl.so.5.8.4 -Dd_dosuid -des'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -DDEBIAN -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -DDEBIAN -fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='3.3.3 (Debian 20040429)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lgdbm -lgdbm_compat -ldb -ldl -lm -lpthread -lc -lcrypt
    perllibs=-ldl -lm -lpthread -lc -lcrypt
    libc=/lib/libc-2.3.2.so, so=so, useshrplib=true, libperl=libperl.so.5.8.4
    gnulibc_version='2.3.2'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.4:
    /etc/perl
    /usr/local/lib/perl/5.8.4
    /usr/local/share/perl/5.8.4
    /usr/lib/perl5
    /usr/share/perl5
    /usr/lib/perl/5.8
    /usr/share/perl/5.8
    /usr/local/lib/site_perl
    /usr/local/lib/perl/5.8.3
    /usr/local/share/perl/5.8.3
    /usr/local/lib/perl/5.8.2
    /usr/local/share/perl/5.8.2
    /usr/local/lib/perl/5.8.1
    /usr/local/share/perl/5.8.1
    /usr/local/lib/perl/5.8.0
    /usr/local/share/perl/5.8.0
    .


Environment for perl v5.8.4:
    HOME=/home/theorb
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/theorb/bin:/usr/X11R6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:.
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @hvds

James Mastros \(via RT\) \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
:Code&#8203;:
:\#\!/usr/bin/perl
:use warnings;
:use Devel&#8203;::Peek;
:$|=1;
:
:\{
:    local $foo;    \# Local \*foo instead\, and it works\.
:    my $x;         \# Only to shut up warnings \-\- both lexical and global $x exhibit this behavior
:    \*foo=\\pos\($x\); \# Neccessary
:    Dump \*foo;
:    print "Got here\\n";
:\}
:print "Got here\\n";
:\_\_DATA\_\_

Segfault confirmed on bleadperl \(@&#8203;23061\)&#8203;:

perl \-e '\{ local $foo; my $x; \*foo = \\pos\($x\) \}'

\#0  Perl\_magic\_setpos \(sv=0x8160330\, mg=0x0\) at mg\.c&#8203;:1687
1687        if \(SvTYPE\(lsv\) >= SVt\_PVMG && SvMAGIC\(lsv\)\)
\(gdb\) where
\#0  Perl\_magic\_setpos \(sv=0x8160330\, mg=0x0\) at mg\.c&#8203;:1687
\#1  0x080b90d2 in Perl\_mg\_set \(sv=0x8160330\) at mg\.c&#8203;:224
\#2  0x080e8440 in Perl\_leave\_scope \(base=6\) at scope\.c&#8203;:788
\#3  0x080e96e0 in Perl\_pop\_scope \(\) at scope\.c&#8203;:137
\#4  0x080efa90 in Perl\_pp\_leaveloop \(\) at pp\_ctl\.c&#8203;:1870
\#5  0x080b301f in Perl\_runops\_debug \(\) at dump\.c&#8203;:1564
\#6  0x08061ff8 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1797
\#7  0x08061caa in perl\_run \(my\_perl=0x8153d68\) at perl\.c&#8203;:1715
\#8  0x0805e76b in main \(argc=3\, argv=0xbffffbbc\, env=0xbffffbcc\)
&nbsp;    at perlmain\.c&#8203;:86
\#9  0x400b0336 in \_\_libc\_start\_main \(main=0x805e6e0 \<main>\, argc=3\, 
&nbsp;    ubp\_av=0xbffffbbc\, init=0x805d860 \<\_init>\, fini=0x812e980 \<\_fini>\, 
&nbsp;    rtld\_fini=0x4000d2fc \<\_dl\_fini>\, stack\_end=0xbffffbac\)
&nbsp;    at \.\./sysdeps/generic/libc\-start\.c&#8203;:129

Hugo

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Jul 22\, 2004 at 03&#8203;:41&#8203;:59PM \+0100\, hv@&#8203;crypt\.org wrote&#8203;:
> James Mastros \(via RT\) \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> :Code&#8203;:
> :\#\!/usr/bin/perl
> :use warnings;
> :use Devel&#8203;::Peek;
> :$|=1;
> :
> :\{
> :    local $foo;    \# Local \*foo instead\, and it works\.
> :    my $x;         \# Only to shut up warnings \-\- both lexical and global $x exhibit this behavior
> :    \*foo=\\pos\($x\); \# Neccessary
> :    Dump \*foo;
> :    print "Got here\\n";
> :\}
> :print "Got here\\n";
> :\_\_DATA\_\_
> 
> Segfault confirmed on bleadperl \(@&#8203;23061\)&#8203;:

It occurs because when unlocalizing\, any magic associated with the local
value is copied back to the restored value\, but the extra fields
associated with PVLV types\, such as LvTARG\, aren't copied across\.
This results in the restored value being a mangled PVLV \(with null
LvTARG\)\. When SvSETMAGIC\(\) is called on this PVLV\, it blows up\.

Now\, I'm not sure why magic is copied across to the restored value; I
guess it's something to do with preserving the magicalness of magic vars
like $/ across localizations? But I'd have thought that for that\, it's
important to copy the magic forward in the local\(\) rather than copying
back during the leave\_scope\(\) ???

Anyway\, I guess the fix is to not copy across the magic if it's a PVLV
in leave\_scope\(\)\.

Dave\.

\-\- 
print\+qq&$\}$"$/$s$\,$\*$\{d\}$g$s$@&#8203;$\.$q$\,$&#8203;:$\.$q$^$\,$@&#8203;$\*$~$;$\.$q$m&if\+map\{m\,^\\d\{0\\\,\}\,\,$\{$&#8203;::\{$'\}\}=chr\($"\+=$&||1\)\}q&10m22\,42\}6&#8203;:17\*2~2\.3@&#8203;3;^2dg3q/s"&=~m\*\\d\\\*\.\*g

**Comment by p5pRT** [comment]
### From @smpeters

> \[davem@&#8203;iabyn\.com \- Thu Jul 22 14&#8203;:44&#8203;:50 2004\]&#8203;:
> 
> On Thu\, Jul 22\, 2004 at 03&#8203;:41&#8203;:59PM \+0100\, hv@&#8203;crypt\.org wrote&#8203;:
> > James Mastros \(via RT\) \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> > :Code&#8203;:
> > :\#\!/usr/bin/perl
> > :use warnings;
> > :use Devel&#8203;::Peek;
> > :$|=1;
> > :
> > :\{
> > :    local $foo;    \# Local \*foo instead\, and it works\.
> > :    my $x;         \# Only to shut up warnings \-\- both lexical and
> global $x exhibit this behavior
> > :    \*foo=\\pos\($x\); \# Neccessary
> > :    Dump \*foo;
> > :    print "Got here\\n";
> > :\}
> > :print "Got here\\n";
> > :\_\_DATA\_\_
> >
> > Segfault confirmed on bleadperl \(@&#8203;23061\)&#8203;:
> 
> It occurs because when unlocalizing\, any magic associated with the
> local
> value is copied back to the restored value\, but the extra fields
> associated with PVLV types\, such as LvTARG\, aren't copied across\.
> This results in the restored value being a mangled PVLV \(with null
> LvTARG\)\. When SvSETMAGIC\(\) is called on this PVLV\, it blows up\.
> 
> Now\, I'm not sure why magic is copied across to the restored value; I
> guess it's something to do with preserving the magicalness of magic
> vars
> like $/ across localizations? But I'd have thought that for that\, it's
> important to copy the magic forward in the local\(\) rather than copying
> back during the leave\_scope\(\) ???
> 
> Anyway\, I guess the fix is to not copy across the magic if it's a PVLV
> in leave\_scope\(\)\.
> 
> Dave\.
> 

Again\, not sure what the fix was\, but it works just fine in bleadperl\.

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'resolved'
