### ISSUE TITLE
perl5.8.4 segfault w/POE

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7562]
Migrated from [rt.perl.org#32163](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=32163) (status was 'resolved')

Searchable as RT32163$

**Comment by p5pRT** [comment]
### From perlbug20041027.z.jp@xoxy.net

#### Created by perlbug20041027.z.jp@xoxy.net



This 4\-line program generates a segmentation fault&#8203;:

use POE; \# $POE&#8203;::REVISION == 1\.0177
\{package POE&#8203;::Session; use overload '""' => 'ID';\}
POE&#8203;::Session\->create\(\);
$poe\_kernel\->run\(\);

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.8.4:

Configured by Debian Project at Mon Oct 25 01:52:37 EST 2004.

Summary of my perl5 (revision 5 version 8 subversion 4) configuration:
  Platform:
    osname=linux, osvers=2.4.27-ti1211, archname=i386-linux-thread-multi
    uname='linux kosh 2.4.27-ti1211 #1 sun sep 19 18:17:45 est 2004 i686 gnulinux '
    config_args='-Dusethreads -Duselargefiles -Dccflags=-DDEBIAN -Dcccdlflags=-fPIC -Darchname=i386-linux -Dprefix=/usr -Dprivlib=/usr/share/perl/5.8 -Darchlib=/usr/lib/perl/5.8 -Dvendorprefix=/usr -Dvendorlib=/usr/share/perl5 -Dvendorarch=/usr/lib/perl5 -Dsiteprefix=/usr/local -Dsitelib=/usr/local/share/perl/5.8.4 -Dsitearch=/usr/local/lib/perl/5.8.4 -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 -Dsiteman1dir=/usr/local/man/man1 -Dsiteman3dir=/usr/local/man/man3 -Dman1ext=1 -Dman3ext=3perl -Dpager=/usr/bin/sensible-pager -Uafs -Ud_csh -Uusesfio -Uusenm -Duseshrplib -Dlibperl=libperl.so.5.8.4 -Dd_dosuid -des'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -DDEBIAN -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -DDEBIAN -fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='3.3.5 (Debian 1:3.3.5-1)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lgdbm -lgdbm_compat -ldb -ldl -lm -lpthread -lc -lcrypt
    perllibs=-ldl -lm -lpthread -lc -lcrypt
    libc=/lib/libc-2.3.2.so, so=so, useshrplib=true, libperl=libperl.so.5.8.4
    gnulibc_version='2.3.2'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.4:
    /etc/perl
    /usr/local/lib/perl/5.8.4
    /usr/local/share/perl/5.8.4
    /usr/lib/perl5
    /usr/share/perl5
    /usr/lib/perl/5.8
    /usr/share/perl/5.8
    /usr/local/lib/site_perl
    .


Environment for perl v5.8.4:
    HOME=/home/joshp
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/joshp/bin:/usr/local/imatix/bin:/command:/usr/local/pgsql/bin:/usr/lib/firebird2/bin:/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:/usr/games
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @smpeters

Perl is going into an infinite loop\.  The following bt was repeated
again and again in my core file\.

\#0  Perl\_amagic\_call \(left=0xaa302a8\, right=0x8146914\, method=4\, flags=9\)
&nbsp;    at gv\.c&#8203;:1463
\#1  0x080c70f5 in Perl\_sv\_2pv\_flags \(sv=0xaa302a8\, lp=0xbf80016c\, flags=2\)
&nbsp;    at sv\.c&#8203;:3634
\#2  0x080b4c3b in S\_hv\_fetch\_common \(hv=0x830a594\, keysv=0xaa302a8\, key=0x0\,
&nbsp;    klen=0\, flags=0\, action=2\, val=0x0\, hash=0\) at hv\.c&#8203;:420
\#3  0x080b41b0 in Perl\_hv\_exists\_ent \(hv=0x8146914\, keysv=0x8146914\,
&nbsp;    hash=135555348\) at hv\.c&#8203;:352
\#4  0x080dcdf3 in Perl\_pp\_exists \(\) at pp\.c&#8203;:3891
\#5  0x080a867a in Perl\_runops\_debug \(\) at dump\.c&#8203;:1572
\#6  0x0806adf6 in Perl\_amagic\_call \(left=0xaa30188\, right=0x8146914\,
method=4\,
&nbsp;    flags=178457992\) at gv\.c&#8203;:1753

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @jkeenan

On Wed Oct 27 00&#8203;:27&#8203;:23 2004\, perlbug20041027\.z\.jp@&#8203;xoxy\.net wrote&#8203;:
> 
> This is a bug report for perl from perlbug20041027\.z\.jp@&#8203;xoxy\.net\,
> generated with the help of perlbug 1\.35 running under perl v5\.8\.4\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> 
> This 4\-line program generates a segmentation fault&#8203;:
> 
> use POE; \# $POE&#8203;::REVISION == 1\.0177
> \{package POE&#8203;::Session; use overload '""' => 'ID';\}
> POE&#8203;::Session\->create\(\);
> $poe\_kernel\->run\(\);
> 

Reviewed this older ticket tonight\, but I don't have POE installed or
have expertise with it\.

Could someone with POE take a look?

Is this a problem with POE or a problem with Perl \(and with supported
Perls in particular\)?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From @jkeenan

On Fri Mar 30 18&#8203;:03&#8203;:14 2012\, jkeenan wrote&#8203;:
> On Wed Oct 27 00&#8203;:27&#8203;:23 2004\, perlbug20041027\.z\.jp@&#8203;xoxy\.net wrote&#8203;:
> > 
> > This is a bug report for perl from perlbug20041027\.z\.jp@&#8203;xoxy\.net\,
> > generated with the help of perlbug 1\.35 running under perl v5\.8\.4\.
> > 
> > 
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > \[Please enter your report here\]
> > 
> > This 4\-line program generates a segmentation fault&#8203;:
> > 
> > use POE; \# $POE&#8203;::REVISION == 1\.0177
> > \{package POE&#8203;::Session; use overload '""' => 'ID';\}
> > POE&#8203;::Session\->create\(\);
> > $poe\_kernel\->run\(\);
> > 
> 
> Reviewed this older ticket tonight\, but I don't have POE installed or
> have expertise with it\.
> 
> Could someone with POE take a look?
> 

I have installed POE version 1\.352 \(latest from CPAN\) on a Linux/i386
machine running perl 5\.12\.0\.  I ran the program above\, with these results&#8203;:

\#\#\#\#\#

$ perl 32163\.pl
discarding session  \- no '\_start' state at 32163\.pl line 3

\#\#\#\#\#

No segfault\.  The program apparently is deficient but POE prints an
appropriate error message and exits in an orderly manner\.

So\, do we still have a problem here?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From @cpansprout

On Wed Apr 25 13&#8203;:20&#8203;:49 2012\, jkeenan wrote&#8203;:
> On Fri Mar 30 18&#8203;:03&#8203;:14 2012\, jkeenan wrote&#8203;:
> > On Wed Oct 27 00&#8203;:27&#8203;:23 2004\, perlbug20041027\.z\.jp@&#8203;xoxy\.net wrote&#8203;:
> > > 
> > > This is a bug report for perl from perlbug20041027\.z\.jp@&#8203;xoxy\.net\,
> > > generated with the help of perlbug 1\.35 running under perl v5\.8\.4\.
> > > 
> > > 
> > > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > > \[Please enter your report here\]
> > > 
> > > This 4\-line program generates a segmentation fault&#8203;:
> > > 
> > > use POE; \# $POE&#8203;::REVISION == 1\.0177
> > > \{package POE&#8203;::Session; use overload '""' => 'ID';\}
> > > POE&#8203;::Session\->create\(\);
> > > $poe\_kernel\->run\(\);
> > > 
> > 
> > Reviewed this older ticket tonight\, but I don't have POE installed or
> > have expertise with it\.
> > 
> > Could someone with POE take a look?
> > 
> 
> I have installed POE version 1\.352 \(latest from CPAN\) on a Linux/i386
> machine running perl 5\.12\.0\.  I ran the program above\, with these results&#8203;:
> 
> \#\#\#\#\#
> 
> $ perl 32163\.pl
> discarding session  \- no '\_start' state at 32163\.pl line 3
> 
> \#\#\#\#\#
> 
> No segfault\.  The program apparently is deficient but POE prints an
> appropriate error message and exits in an orderly manner\.
> 
> So\, do we still have a problem here?

The stack trace posted earlier suggests this is the same bug as \#110488\.
 So I’m pretty sure changes to POE stop it from triggering this bug\. 
I’m marking this as resolved\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
