### ISSUE TITLE
Perl segfaults; test case available

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7580]
Migrated from [rt.perl.org#32332](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=32332) (status was 'resolved')

Searchable as RT32332$

**Comment by p5pRT** [comment]
### From timwi@gmx.net

This is a bug report for perl from timwi@&#8203;gmx\.net\,
generated with the help of perlbug 1\.35 running under perl v5\.8\.4\.
\(Though I had to mail it manually\. Hope that's OK\.\)



---
Perl segfaults upon the execution of the following 26\-line script\.

If you don't get the segfault\, try duplicating lines 14\-16 \(the
contents of the 'starthere' string\)\. The more you put in\, the
more likely you are to get the segfault\.

I am aware that line 19 \(my $ac = '';\) seems pointless\, because
$ac is never used again anywhere\. However\, if I remove that line\,
then instead of a segfault it gets stuck in an endless loop\.\.\.

I have a suspicion that line 22 is the actual culprit\.

Here is the script\.

\#\!/usr/bin/perl
use strict;
SegFaultFunction \('starthere'\);

sub SegFaultFunction \{
&nbsp;     my $variable = shift;
&nbsp;     my $params = shift;
&nbsp;     my $cns =   \{   'abcdefg' => sub \{
&nbsp;                         return \(shift\)\->\{'x'\};
&nbsp;                     \}\,
&nbsp;                     starthere => "
&nbsp;                         \<?abcdefg \<?xy xy?> abcdefg?>
&nbsp;                         \<?abcdefg \<?xy xy?> abcdefg?>
&nbsp;                         \<?abcdefg \<?xy xy?> abcdefg?>
&nbsp;                     "\,
&nbsp;                 \}\->\{$variable\};
&nbsp;     $cns = $cns\->\($params\) if ref $cns eq 'CODE';
&nbsp;     while \($cns =~ s/^\(\.\*?\)\(?=\<\\?\)//os\) \{
&nbsp;         my $ac = '';
&nbsp;         if \($cns =~ /^\<\\?\(\[a\-zA\-Z0\-9\_\]\+\)\(\\s|$\)/os\) \{
&nbsp;             my $var = $1;
&nbsp;             \($cns =~ s/^\.\*?$var\\?>/ $\_=$&; s\!^\.\*\<\\?$var\\s\*\(\.\*?\)\\s\*$var\\?>\!
&nbsp;                 SegFaultFunction \($var\, \{ x => $1 \}\); \!es; $\_ /es\);
&nbsp;         \}
&nbsp;     \}
\}



---


---
Flags&#8203;:
&nbsp;     category=core
&nbsp;     severity=high


---
Site configuration information for perl v5\.8\.4&#8203;:

Configured by Debian Project at Sun Sep 26 12&#8203;:11&#8203;:30 CEST 2004\.

Summary of my perl5 \(revision 5 version 8 subversion 4\) configuration&#8203;:
&nbsp;   Platform&#8203;:
&nbsp;     osname=linux\, osvers=2\.6\.8\-1\-686\, archname=i386\-linux\-thread\-multi
&nbsp;     uname='linux cachaca 2\.6\.8\-1\-686 \#1 sat aug 28 14&#8203;:11&#8203;:39 edt 2004 
i686 gnulinux '
&nbsp;     config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN 
\-Dcccdlflags=\-fPIC \-Darchname=i386\-linux \-Dprefix=/usr 
\-Dprivlib=/usr/share/perl/5\.8 \-Darchlib=/usr/lib/perl/5\.8 
\-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 
\-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local 
\-Dsitelib=/usr/local/share/perl/5\.8\.4 
\-Dsitearch=/usr/local/lib/perl/5\.8\.4 \-Dman1dir=/usr/share/man/man1 
\-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1 
\-Dsiteman3dir=/usr/local/man/man3 \-Dman1ext=1 \-Dman3ext=3perl 
\-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Uusesfio \-Uusenm 
\-Duseshrplib \-Dlibperl=libperl\.so\.5\.8\.4 \-Dd\_dosuid \-des'
&nbsp;     hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;     usethreads=define use5005threads=undef useithreads=define 
usemultiplicity=define
&nbsp;     useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;     use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;     usemymalloc=n\, bincompat5005=undef
&nbsp;   Compiler&#8203;:
&nbsp;     cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS 
\-DDEBIAN \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE 
\-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;     optimize='\-O2'\,
&nbsp;     cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBIAN 
\-fno\-strict\-aliasing \-I/usr/local/include'
&nbsp;     ccversion=''\, gccversion='3\.3\.4 \(Debian 1&#8203;:3\.3\.4\-12\)'\, gccosandvers=''
&nbsp;     intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;     ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, 
lseeksize=8
&nbsp;     alignbytes=4\, prototype=define
&nbsp;   Linker and Libraries&#8203;:
&nbsp;     ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;     libpth=/usr/local/lib /lib /usr/lib
&nbsp;     libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;     perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;     libc=/lib/libc\-2\.3\.2\.so\, so=so\, useshrplib=true\, 
libperl=libperl\.so\.5\.8\.4
&nbsp;     gnulibc\_version='2\.3\.2'
&nbsp;   Dynamic Linking&#8203;:
&nbsp;     dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;     cccdlflags='\-fPIC'\, lddlflags='\-shared \-L/usr/local/lib'

Locally applied patches&#8203;:




---
@&#8203;INC for perl v5\.8\.4&#8203;:
&nbsp;     /etc/perl
&nbsp;     /usr/local/lib/perl/5\.8\.4
&nbsp;     /usr/local/share/perl/5\.8\.4
&nbsp;     /usr/lib/perl5
&nbsp;     /usr/share/perl5
&nbsp;     /usr/lib/perl/5\.8
&nbsp;     /usr/share/perl/5\.8
&nbsp;     /usr/local/lib/site\_perl
&nbsp;     \.



---
Environment for perl v5\.8\.4&#8203;:
&nbsp;     HOME=/home/timwi
&nbsp;     LANG=en\_GB
&nbsp;     LANGUAGE \(unset\)
&nbsp;     LD\_LIBRARY\_PATH \(unset\)
&nbsp;     LOGDIR \(unset\)
&nbsp;     PATH=/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/bin/X11&#8203;:/usr/games
&nbsp;     PERL\_BADLANG \(unset\)
&nbsp;     SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From timwi@gmx.net

> This is a bug report for perl from timwi@&#8203;gmx\.net\,
> generated with the help of perlbug 1\.35 running under perl v5\.8\.4\.

I just downloaded and installed 5\.8\.5 and the segfault still occurs\.

**Comment by p5pRT** [comment]
timwi@gmx.net - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @smpeters

> \[timwi \- Thu Nov 04 16&#8203;:53&#8203;:40 2004\]&#8203;:
> 
> This is a bug report for perl from timwi@&#8203;gmx\.net\,
> generated with the help of perlbug 1\.35 running under perl v5\.8\.4\.
> \(Though I had to mail it manually\. Hope that's OK\.\)
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> 
> Perl segfaults upon the execution of the following 26\-line script\.
> 
> If you don't get the segfault\, try duplicating lines 14\-16 \(the
> contents of the 'starthere' string\)\. The more you put in\, the
> more likely you are to get the segfault\.
> 
> I am aware that line 19 \(my $ac = '';\) seems pointless\, because
> $ac is never used again anywhere\. However\, if I remove that line\,
> then instead of a segfault it gets stuck in an endless loop\.\.\.
> 
> I have a suspicion that line 22 is the actual culprit\.
> 
> Here is the script\.
> 
> \#\!/usr/bin/perl
> use strict;
> SegFaultFunction \('starthere'\);
> 
> sub SegFaultFunction \{
>      my $variable = shift;
>      my $params = shift;
>      my $cns =   \{   'abcdefg' => sub \{
>                          return \(shift\)\->\{'x'\};
>                      \}\,
>                      starthere => "
>                          \<?abcdefg \<?xy xy?> abcdefg?>
>                          \<?abcdefg \<?xy xy?> abcdefg?>
>                          \<?abcdefg \<?xy xy?> abcdefg?>
>                      "\,
>                  \}\->\{$variable\};
>      $cns = $cns\->\($params\) if ref $cns eq 'CODE';
>      while \($cns =~ s/^\(\.\*?\)\(?=\<\\?\)//os\) \{
>          my $ac = '';
>          if \($cns =~ /^\<\\?\(\[a\-zA\-Z0\-9\_\]\+\)\(\\s|$\)/os\) \{
>              my $var = $1;
>              \($cns =~ s/^\.\*?$var\\?>/ $\_=$&; s\!^\.\*\<\\?$var\\s\*\(\.\*?\)\\s\*$var\\?>\!
>                  SegFaultFunction \($var\, \{ x => $1 \}\); \!es; $\_ /es\);
>          \}
>      \}
> \}
> 

Welcome to a completely different problem\!

steve@&#8203;kirk&#8203;:\~/smoke/perl\-current$ \./perl \-Ilib rt\_32332\.pl 
\*\*\* glibc detected \*\*\* double free or corruption \(fasttop\)&#8203;: 0x08297730 \*\*\*
Aborted \(core dumped\)

I get the following backtrace from the core dump\.

\#0  0xffffe410 in \_\_kernel\_vsyscall \(\)
\(gdb\) bt
\#0  0xffffe410 in \_\_kernel\_vsyscall \(\)
\#1  0xb7d939a1 in raise \(\) from /lib/tls/i686/cmov/libc\.so\.6
\#2  0xb7d952b9 in abort \(\) from /lib/tls/i686/cmov/libc\.so\.6
\#3  0xb7dc787a in \_\_fsetlocking \(\) from /lib/tls/i686/cmov/libc\.so\.6
\#4  0xb7dcdfd4 in malloc\_usable\_size \(\) from /lib/tls/i686/cmov/libc\.so\.6
\#5  0xb7dce34a in free \(\) from /lib/tls/i686/cmov/libc\.so\.6
\#6  0x0808c669 in Perl\_safesysfree \(where=0x8297730\) at util\.c&#8203;:250
\#7  0x0823d0b9 in Perl\_pregfree \(r=0x82976c0\) at regcomp\.c&#8203;:6034
\#8  0x081362b8 in Perl\_pp\_regcomp \(\) at pp\_ctl\.c&#8203;:135
\#9  0x0808bc02 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1695
\#10 0x080b7f0d in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2366
\#11 0x080b74d9 in perl\_run \(my\_perl=0x826b008\) at perl\.c&#8203;:2286
\#12 0x0805ea60 in main \(argc=3\, argv=0xbfa28c84\, env=0xbfa28c94\)
&nbsp;    at perlmain\.c&#8203;:103

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Mar 30\, 2006 at 07&#8203;:34&#8203;:37PM \-0800\, Steve Peters via RT wrote&#8203;:
> > \[timwi \- Thu Nov 04 16&#8203;:53&#8203;:40 2004\]&#8203;:
> > Perl segfaults upon the execution of the following 26\-line script\.
> > 
> > If you don't get the segfault\, try duplicating lines 14\-16 \(the
> > contents of the 'starthere' string\)\. The more you put in\, the
> > more likely you are to get the segfault\.
> > 
> > I am aware that line 19 \(my $ac = '';\) seems pointless\, because
> > $ac is never used again anywhere\. However\, if I remove that line\,
> > then instead of a segfault it gets stuck in an endless loop\.\.\.
> > 
> > I have a suspicion that line 22 is the actual culprit\.
> > 
> > Here is the script\.
> > 
> > \#\!/usr/bin/perl
> > use strict;
> > SegFaultFunction \('starthere'\);
> > 
> > sub SegFaultFunction \{
> >      my $variable = shift;
> >      my $params = shift;
> >      my $cns =   \{   'abcdefg' => sub \{
> >                          return \(shift\)\->\{'x'\};
> >                      \}\,
> >                      starthere => "
> >                          \<?abcdefg \<?xy xy?> abcdefg?>
> >                          \<?abcdefg \<?xy xy?> abcdefg?>
> >                          \<?abcdefg \<?xy xy?> abcdefg?>
> >                      "\,
> >                  \}\->\{$variable\};
> >      $cns = $cns\->\($params\) if ref $cns eq 'CODE';
> >      while \($cns =~ s/^\(\.\*?\)\(?=\<\\?\)//os\) \{
> >          my $ac = '';
> >          if \($cns =~ /^\<\\?\(\[a\-zA\-Z0\-9\_\]\+\)\(\\s|$\)/os\) \{
> >              my $var = $1;
> >              \($cns =~ s/^\.\*?$var\\?>/ $\_=$&; s\!^\.\*\<\\?$var\\s\*\(\.\*?\)\\s\*$var\\?>\!
> >                  SegFaultFunction \($var\, \{ x => $1 \}\); \!es; $\_ /es\);
> >          \}
> >      \}
> > \}
> > 
> 
> Welcome to a completely different problem\!
> 
> steve@&#8203;kirk&#8203;:\~/smoke/perl\-current$ \./perl \-Ilib rt\_32332\.pl 
> \*\*\* glibc detected \*\*\* double free or corruption \(fasttop\)&#8203;: 0x08297730 \*\*\*
> Aborted \(core dumped\)

fixed by the change below\. The refcounting of REs got a bit messed up\.

\-\- 
The crew of the Enterprise encounter an alien life form which is
suprisingly neither humanoid nor made from pure energy\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#22

Change 28251 by davem@&#8203;davem\-splatty on 2006/05/20 11&#8203;:58&#8203;:07

&nbsp;    \[perl \#32332\] Perl segfaults; test case available
&nbsp;    sub f \{ s/$var/f\(\)/e \} could free the wrong RE

Affected files \.\.\.

\.\.\. //depot/perl/cop\.h\#118 edit
\.\.\. //depot/perl/pp\_ctl\.c\#566 edit
\.\.\. //depot/perl/pp\_hot\.c\#468 edit

Differences \.\.\.

==== //depot/perl/cop\.h\#118 \(text\) ====

@&#8203;@&#8203; \-576\,10 \+576\,12 @&#8203;@&#8203;
&nbsp;     cx\->sb\_rxres        = NULL\,                    \\
&nbsp;     cx\->sb\_rx        = rx\,                    \\
&nbsp;     cx\->cx\_type        = CXt\_SUBST;                \\
\-    rxres\_save\(&cx\->sb\_rxres\, rx\)
\+    rxres\_save\(&cx\->sb\_rxres\, rx\);                    \\
\+    ReREFCNT\_inc\(rx\)
 
 \#define POPSUBST\(cx\) cx = &cxstack\[cxstack\_ix\-\-\];            \\
\-    rxres\_free\(&cx\->sb\_rxres\)
\+    rxres\_free\(&cx\->sb\_rxres\);                    \\
\+    ReREFCNT\_dec\(cx\->sb\_rx\)
 
 struct context \{
&nbsp;     U32        cx\_type;    /\* what kind of context this is \*/

==== //depot/perl/pp\_ctl\.c\#566 \(text\) ====

@&#8203;@&#8203; \-197\,7 \+197\,7 @&#8203;@&#8203;
&nbsp;     if\(old \!= rx\) \{
&nbsp;     if\(old\)
&nbsp;         ReREFCNT\_dec\(old\);
\-    PM\_SETRE\(pm\,rx\);
\+    PM\_SETRE\(pm\,ReREFCNT\_inc\(rx\)\);
&nbsp;     \}
 
&nbsp;     rxres\_restore\(&cx\->sb\_rxres\, rx\);
@&#8203;@&#8203; \-256\,7 \+256\,6 @&#8203;@&#8203;
&nbsp;         SvTAINT\(targ\);
 
&nbsp;         LEAVE\_SCOPE\(cx\->sb\_oldsave\);
\-        ReREFCNT\_dec\(rx\);
&nbsp;         POPSUBST\(cx\);
&nbsp;         RETURNOP\(pm\->op\_next\);
&nbsp;     \}

==== //depot/perl/pp\_hot\.c\#468 \(text\) ====

@&#8203;@&#8203; \-2303\,7 \+2303\,6 @&#8203;@&#8203;
&nbsp;     if \(\!c\) \{
&nbsp;         register PERL\_CONTEXT \*cx;
&nbsp;         SPAGAIN;
\-        \(void\)ReREFCNT\_inc\(rx\);
&nbsp;         PUSHSUBST\(cx\);
&nbsp;         RETURNOP\(cPMOP\->op\_pmreplroot\);
&nbsp;     \}

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
