### ISSUE TITLE
UTF-8 string substitution corrupts memory

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7724]
Migrated from [rt.perl.org#33185](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=33185) (status was 'resolved')

Searchable as RT33185$

**Comment by p5pRT** [comment]
### From sroy@search-box.com


This is a bug report for perl from sroy@&#8203;search\-box\.com\,
generated with the help of perlbug 1\.35 running under perl v5\.8\.4\.




---
The following test program corrupts perl's memory&#8203;:



---
\#\!/usr/bin/perl
\#
\# Demonstrates memory corruption bug in 5\.8\.4\.  The 'use Benchmark'
\# line does not affect the corruption\, but on my system it
\# moves memory allocations around enough to ensure that 'perl \-d bug\.pl'
\# hangs\, and that under 'gdb debugperl' it produces a segmentation fault\.
\# The exact string is also unimportant as long as it has characters
\# that match the string class in the s///\.  The one chosen here simply
\# reliably reproduces the problem on my system\.
\#

use Encode;
use Benchmark;

$\_ = decode\_utf8\('title&#8203;: Ã¿ÂÃ¿Ã¿ÂÂÃ¿ÂÂÃ¿Ã¿ÂÃ¿ÂÃ¿Ã¿Â'\, 1\);
$\_ =~ s/\[^\[&#8203;:print&#8203;:\]\]/ /g;


---
Since it's a memory corruption\, it may or may not crash when running
under perl\, perl \-d\, or gdb\.  To reliably observe the problem under gdb&#8203;:

1\. gdb debugperl \(a perl compiled with debugging on\)
2\. b regexec\.c&#8203;:4373
3\. r \-d bug\.pl
4\. c \(from within the perl debugger\)
5\. c
6\. c
7\. crash \(on my system\)

The breakpoint stops the first time perl needs to check whether a
utf8 character is part of a string class\.  At this point \(step \#5\) everything
is ok\.  By step \#6 the value of PL\_bostr \(my\_perl\->Tbostr\) is corrupted\.
To see more details\, instead of c at step \#6 do&#8203;:

6\. fin
7\. s 4

Now the debugger is sitting at the line that corrupts prog\->startp\.
Ultimately\, this corruption leads to a seg fault at pp\_hot\.c&#8203;:2151 when perl
tries to copy characters as part of the s/// operation\.

ANALYSIS&#8203;:

In the middle of processing the regular expression\, The regex library
demand\-loads a bunch of stuff to create the swashes for the \[&#8203;:print&#8203;:\]
expression\.  At the end of all that PL\_bostr has a completely new value\.
I have no idea whether the right fix is to move away from using PL\_bostr
in the regex library in favor of some local variable\, or to try and
save PL\_bostr and restore it before any line that might change it\.

WORKAROUND&#8203;:

Adding a 'use utf8' pragma at the top of the program seems to load everything
ahead of time and avoid the problem with the demand\-load\.  I have no real
confidence that it avoids other bugs of this sort\, though\.  Note that
if you add 'use utf8' to the test program\, you'll want to get rid of the
decode\_utf8 call since now perl interprets the string directly as utf8\.

Scott



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=high


---
Site configuration information for perl v5\.8\.4&#8203;:

Configured by Debian Project at Mon Oct 25 01&#8203;:52&#8203;:37 EST 2004\.

Summary of my perl5 \(revision 5 version 8 subversion 4\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.4\.27\-ti1211\, archname=i386\-linux\-thread\-multi
&nbsp;    uname='linux kosh 2\.4\.27\-ti1211 \#1 sun sep 19 18&#8203;:17&#8203;:45 est 2004 i686 gnulinux '
&nbsp;    config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN \-Dcccdlflags=\-fPIC \-Darchname=i386\-linux \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.8 \-Darchlib=/usr/lib/perl/5\.8 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.8\.4 \-Dsitearch=/usr/local/lib/perl/5\.8\.4 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1 \-Dsiteman3dir=/usr/local/man/man3 \-Dman1ext=1 \-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Uusesfio \-Uusenm \-Duseshrplib \-Dlibperl=libperl\.so\.5\.8\.4 \-Dd\_dosuid \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBIAN \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBIAN \-fno\-strict\-aliasing \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='3\.3\.5 \(Debian 1&#8203;:3\.3\.5\-1\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    libc=/lib/libc\-2\.3\.2\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.8\.4
&nbsp;    gnulibc\_version='2\.3\.2'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-L/usr/local/lib'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl v5\.8\.4&#8203;:
&nbsp;    /etc/perl
&nbsp;    /usr/local/lib/perl/5\.8\.4
&nbsp;    /usr/local/share/perl/5\.8\.4
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/perl/5\.8
&nbsp;    /usr/share/perl/5\.8
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    /usr/local/lib/perl/5\.8\.3
&nbsp;    /usr/local/share/perl/5\.8\.3
&nbsp;    \.



---
Environment for perl v5\.8\.4&#8203;:
&nbsp;    HOME=/home/sroy
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LC\_ALL=C
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/sroy/cvs/searchbox/server&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/bin/X11&#8203;:/usr/games
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From hsr@cs.stanford.edu

It looks like something in the mail chain doesn't like bytes with their high order bits set\.  Here's a corrected test program that's ASCII\.

Scott



---
\#\!/usr/bin/perl
\#
\# Demonstrates memory corruption bug in 5\.8\.4\.  The 'use Benchmark'
\# line does not affect the corruption\, but on my system it
\# moves memory allocations around enough to ensure that 'perl \-d bug\.pl'
\# hangs\, and that under 'gdb debugperl' it produces a segmentation fault\.
\# The exact string is also unimportant as long as it has characters
\# that match the string class in the s///\.  The one chosen here simply
\# reliably reproduces the problem on my system\.
\#

use Encode;
use Benchmark;

$\_ = decode\_utf8\("\\164\\151\\164\\154\\145\\72\\40\\303\\277\\302\\200\\303\\277\\303\\277\\302\\202\\302\\222\\303\\277\\302\\217\\302\\220\\303\\277\\303\\277\\302\\210\\303\\277\\302\\201\\303\\277\\303\\277\\302\\202"\, 1\);
$\_ =~ s/\[^\[&#8203;:print&#8203;:\]\]/ /g;


---

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @nwc10

On Sat\, Dec 25\, 2004 at 09&#8203;:50&#8203;:46PM \-0000\, sroy @&#8203; search\-box\. com wrote&#8203;:

> The breakpoint stops the first time perl needs to check whether a
> utf8 character is part of a string class\.  At this point \(step \#5\) everything
> is ok\.  By step \#6 the value of PL\_bostr \(my\_perl\->Tbostr\) is corrupted\.
> To see more details\, instead of c at step \#6 do&#8203;:
> 
> 6\. fin
> 7\. s 4
> 
> Now the debugger is sitting at the line that corrupts prog\->startp\.
> Ultimately\, this corruption leads to a seg fault at pp\_hot\.c&#8203;:2151 when perl
> tries to copy characters as part of the s/// operation\.

I can recreate this on OS X when running with the perl debugger\. I can't
recreate it on FreeBSD \(on a box where valgrind has been installed\) and
annoyingly the x86 Linux box I usually use for this sort of thing is
currently inaccessible\.

> ANALYSIS&#8203;:
> 
> In the middle of processing the regular expression\, The regex library
> demand\-loads a bunch of stuff to create the swashes for the \[&#8203;:print&#8203;:\]
> expression\.  At the end of all that PL\_bostr has a completely new value\.
> I have no idea whether the right fix is to move away from using PL\_bostr
> in the regex library in favor of some local variable\, or to try and
> save PL\_bostr and restore it before any line that might change it\.

Thanks for the analysis\, which seems to be spot on\. \(Seems\, because I'm no
expert on the regexp engine's guts\)\.

Ideally we'd really like to re\-write the regexp engine sufficiently to remove
all the global state\, and hence make it totally re\-entrant\. Currently no\-one
with the expertise to do this has the time\.

Currently there are kludges to save enough state to theoretically make the
utf8 initialisation work&#8203;:

/\* XXX Here's a total kludge\.  But we need to re\-enter for swash routines\. \*/

void
Perl\_save\_re\_context\(pTHX\)
\{
&nbsp;    SAVEI32\(PL\_reg\_flags\);        /\* from regexec\.c \*/
&nbsp;    SAVEPPTR\(PL\_bostr\);
&nbsp;    SAVEPPTR\(PL\_reginput\);        /\* String\-input pointer\. \*/

but what doesn't make sense to me is why PL\_bostr isn't being saved \(or
maybe isn't being restored\) via the code path that you code takes\.

The realistic fix is going to be to make it save and restore correctly for
the class of operations that your code represents\. I don't have the
experience with the regexp engine to know where to look to quickly find the
correct solution\, but I believe that several other people on the
perl5\-porters mailing list do\.

Nicholas Clark

**Comment by p5pRT** [comment]
### From @nwc10

On Thu\, Dec 30\, 2004 at 06&#8203;:56&#8203;:49PM \+0000\, Nicholas Clark wrote&#8203;:
> The realistic fix is going to be to make it save and restore correctly for
> the class of operations that your code represents\. I don't have the
> experience with the regexp engine to know where to look to quickly find the
> correct solution\, but I believe that several other people on the
> perl5\-porters mailing list do\.

OK\. I underestimate my brute force and ignorance\. With a watchpoint on
my\_perl\->Tbostr\, a backtrace at the first point of modification is&#8203;:

0  Perl\_pp\_match \(my\_perl=0x800200\) at pp\_hot\.c&#8203;:1288
\#1  0x000cfd70 in Perl\_runops\_debug \(my\_perl=0x800200\) at dump\.c&#8203;:1572
\#2  0x0001fde0 in Perl\_call\_sv \(my\_perl=0x800200\, sv=0x4c\, flags=6\) at perl\.c&#8203;:2134
\#3  0x00024308 in S\_call\_list\_body \(my\_perl=0x800200\, cv=0x888224\) at perl\.c&#8203;:4721
\#4  0x00023e34 in Perl\_call\_list \(my\_perl=0x800200\, oldscope=3\, paramList=0x80b278\) at perl\.c&#8203;:4650
\#5  0x00014de4 in Perl\_newATTRSUB \(my\_perl=0x800200\, floor=3\, o=0x0\, proto=0x888224\, attrs=0x0\, block=0x111e050\) at op\.c&#8203;:4482
\#6  0x00011228 in Perl\_utilize \(my\_perl=0x800200\, aver=1\, floor=3\, version=0x111e100\, idop=0x63a360\, arg=0x111df60\) at op\.c&#8203;:3039
\#7  0x00011434 in Perl\_vload\_module \(my\_perl=0x800200\, flags=2\, name=0x1\, ver=0x111df60\, args=0x4599e0\) at op\.c&#8203;:3141
\#8  0x00011284 in Perl\_load\_module \(my\_perl=0x68a7e0\, flags=8430128\, name=0x1\, ver=0x68a7e0\) at op\.c&#8203;:3093
\#9  0x000b139c in Perl\_swash\_init \(my\_perl=0x800200\, pkg=0xeaf84 "utf8"\, name=0xe7ef0 ""\, listsv=0x32b14c\, minbits=1\, none=0\) at utf8\.c&#8203;:1587
\#10 0x000df018 in Perl\_regclass\_swash \(my\_perl=0x800200\, node=0x80a230\, doinit=1 '\\001'\, listsvp=0x0\, altsvp=0xbfffee34\) at regexec\.c&#8203;:4337
\#11 0x000df254 in S\_reginclass \(my\_perl=0x800200\, n=0x6e31c4\, p=0x111e017 "\\202"\, lenp=0x0\, do\_utf8=1 '\\001'\) at regexec\.c&#8203;:4388
\#12 0x000d5854 in S\_find\_byclass \(my\_perl=0x800200\, prog=0x6e3180\, c=0x6e31c4\, s=0x111e017 " perl\.c&#8203;:1853
\#17 0x0001f03c in perl\_run \(my\_perl=0x800200\) at perl\.c&#8203;:1771
\#18 0x0000289c in main \(argc=4\, argv=0xbffff730\, env=0x1\) at perlmain\.c&#8203;:98

where the culprit is \#9\, which was exercising this code \*before\* saving the
regexp engine context&#8203;:

&nbsp;    if \(\!gv\_fetchmeth\(stash\, "SWASHNEW"\, 8\, \-1\)\) \{    /\* demand load utf8 \*/
&nbsp;    ENTER;
&nbsp;    errsv\_save = newSVsv\(ERRSV\);
&nbsp;    Perl\_load\_module\(aTHX\_ PERL\_LOADMOD\_NOIMPORT\, newSVpvn\(pkg\,pkg\_len\)\,
&nbsp;             Nullsv\);
&nbsp;    if \(\!SvTRUE\(ERRSV\)\)
&nbsp;        sv\_setsv\(ERRSV\, errsv\_save\);
&nbsp;    SvREFCNT\_dec\(errsv\_save\);
&nbsp;    LEAVE;
&nbsp;    \}

The appended patch seems to cure the problem for me\, but I'm not confident
that it's the correct way\.

Nicholas Clark

==== //depot/perl/utf8\.c\#212 \- /Users/nick/p4perl/perl/utf8\.c ====
<details><summary>Inline Patch</summary>

```diff
--- /tmp/tmp.26186.0    Thu Dec 30 19:46:18 2004
+++ /Users/nick/p4perl/perl/utf8.c      Thu Dec 30 19:24:46 2004
@@ -1581,6 +1581,8 @@ Perl_swash_init(pTHX_ char* pkg, char* n
     HV *stash = gv_stashpvn(pkg, pkg_len, FALSE);
     SV* errsv_save;

+    ENTER;
+    save_re_context();
     if (!gv_fetchmeth(stash, "SWASHNEW", 8, -1)) {     /* demand load utf8 */
        ENTER;
        errsv_save = newSVsv(ERRSV);
@@ -1601,10 +1603,8 @@ Perl_swash_init(pTHX_ char* pkg, char* n
     PUSHs(sv_2mortal(newSViv(minbits)));
     PUSHs(sv_2mortal(newSViv(none)));
     PUTBACK;
-    ENTER;
     SAVEI32(PL_hints);
     PL_hints = 0;
-    save_re_context();
     if (IN_PERL_COMPILETIME) {
        /* XXX ought to be handled by lex_start */
        SAVEI32(PL_in_my);
```
</details>

**Comment by p5pRT** [comment]
### From @hvds

Nicholas Clark \<nick@&#8203;ccl4\.org> wrote&#8203;:
:The appended patch seems to cure the problem for me\, but I'm not confident
:that it's the correct way\.

I notice that this changes the order things are stacked; I'm not sure if
that's ever going to be relevant\. In particularly this swaps the first
two of the sequence&#8203;:
&nbsp;  PUSHSTACKi; ENTER; LEAVE; POPSTACK
\.\. but I'm not sure what they all do without expanding a lot of macros\.

Hugo

**Comment by p5pRT** [comment]
### From @nwc10

On Fri\, Dec 31\, 2004 at 03&#8203;:04&#8203;:49PM \+0000\, hv@&#8203;crypt\.org wrote&#8203;:
> Nicholas Clark \<nick@&#8203;ccl4\.org> wrote&#8203;:
> :The appended patch seems to cure the problem for me\, but I'm not confident
> :that it's the correct way\.
> 
> I notice that this changes the order things are stacked; I'm not sure if
> that's ever going to be relevant\. In particularly this swaps the first
> two of the sequence&#8203;:
>   PUSHSTACKi; ENTER; LEAVE; POPSTACK
> \.\. but I'm not sure what they all do without expanding a lot of macros\.

Aha\. I was rather hoping that someone would be able to tell me if the changes
were going to be relevant\. The "simplest" fix appears to be add
save\_re\_context\(\); after the ENTER in

&nbsp;    if \(\!gv\_fetchmeth\(stash\, "SWASHNEW"\, 8\, \-1\)\) \{    /\* demand load utf8 \*/
&nbsp;    ENTER;
&nbsp;    errsv\_save = newSVsv\(ERRSV\);
&nbsp;    Perl\_load\_module\(aTHX\_ PERL\_LOADMOD\_NOIMPORT\, newSVpvn\(pkg\,pkg\_len\)\,
&nbsp;             Nullsv\);
&nbsp;    if \(\!SvTRUE\(ERRSV\)\)
&nbsp;        sv\_setsv\(ERRSV\, errsv\_save\);
&nbsp;    SvREFCNT\_dec\(errsv\_save\);
&nbsp;    LEAVE;
&nbsp;    \}


except that seems to be wasteful\, as it would mean doing all the save work
twice\, because of the existing save\_re\_context\(\) later in Perl\_swatch\_init\.
I was hoping that there was a good way to save the regexp engine's context
just once for the entire function\.

Nicholas Clark

**Comment by p5pRT** [comment]
### From @iabyn

On Fri\, Dec 31\, 2004 at 03&#8203;:04&#8203;:49PM \+0000\, hv@&#8203;crypt\.org wrote&#8203;:
> Nicholas Clark \<nick@&#8203;ccl4\.org> wrote&#8203;:
> :The appended patch seems to cure the problem for me\, but I'm not confident
> :that it's the correct way\.
> 
> I notice that this changes the order things are stacked; I'm not sure if
> that's ever going to be relevant\. In particularly this swaps the first
> two of the sequence&#8203;:
>   PUSHSTACKi; ENTER; LEAVE; POPSTACK
> \.\. but I'm not sure what they all do without expanding a lot of macros\.

I'd have thought that the better approach would be to move the

&nbsp;    if \(\!gv\_fetchmeth\(stash\, "SWASHNEW"\, 8\, \-1\)\) \{    /\* demand load utf8 \*/

block further down to just above the line

&nbsp;    if \(call\_method\("SWASHNEW"\, G\_SCALAR\)\)

then the call to Perl\_load\_module is protected by the PUSHSTACKi\. Note
that PUSHSTACKi is needed any place where the caller isn't prepared for
the stack to get extended and thus possibly reallocated \(thus invalidating
SP etc\)\. It gives you a brand new stack to play with\.

\-\- 
In England there is a special word which means the last sunshine
of the summer\. That word is "spring"\.

**Comment by p5pRT** [comment]
### From @iabyn

On Fri\, Dec 31\, 2004 at 04&#8203;:11&#8203;:16PM \+0000\, Dave Mitchell wrote&#8203;:
> On Fri\, Dec 31\, 2004 at 03&#8203;:04&#8203;:49PM \+0000\, hv@&#8203;crypt\.org wrote&#8203;:
> > Nicholas Clark \<nick@&#8203;ccl4\.org> wrote&#8203;:
> > :The appended patch seems to cure the problem for me\, but I'm not confident
> > :that it's the correct way\.
> > 
> > I notice that this changes the order things are stacked; I'm not sure if
> > that's ever going to be relevant\. In particularly this swaps the first
> > two of the sequence&#8203;:
> >   PUSHSTACKi; ENTER; LEAVE; POPSTACK
> > \.\. but I'm not sure what they all do without expanding a lot of macros\.
> 
> I'd have thought that the better approach would be to move the
> 
>     if \(\!gv\_fetchmeth\(stash\, "SWASHNEW"\, 8\, \-1\)\) \{    /\* demand load utf8 \*/
> 
> block further down to just above the line
> 
>     if \(call\_method\("SWASHNEW"\, G\_SCALAR\)\)
> 
> then the call to Perl\_load\_module is protected by the PUSHSTACKi\. Note
> that PUSHSTACKi is needed any place where the caller isn't prepared for
> the stack to get extended and thus possibly reallocated \(thus invalidating
> SP etc\)\. It gives you a brand new stack to play with\.

Nicolas just reminded of this outstanding issue from December\, so I've
committed the following change\. It \(hopefully\) does all the state saving
needed \*before\* doing the require\.

Dave\.

\-\- 
Spock \(or Data\) is fired from his high\-ranking position for not being able
to understand the most basic nuances of about one in three sentences that
anyone says to him\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#19

Change 24084 by davem@&#8203;davem\-splatty on 2005/03/26 21&#8203;:25&#8203;:47

&nbsp;    \[perl \#33185\] UTF\-8 string substitution corrupts memory
&nbsp;    The implicit call of 'require utf8' triggered by code like
&nbsp;        "\\x\{100\}" =~ /\[\[&#8203;:print&#8203;:\]\]/
&nbsp;    wasn't saving state correctly first\.

Affected files \.\.\.

\.\.\. //depot/perl/utf8\.c\#223 edit

Differences \.\.\.

==== //depot/perl/utf8\.c\#223 \(text\) ====

@&#8203;@&#8203; \-1578\,6 \+1578\,11 @&#8203;@&#8203;
&nbsp;     HV \*stash = gv\_stashpvn\(pkg\, pkg\_len\, FALSE\);
&nbsp;     SV\* errsv\_save;
 
\+    PUSHSTACKi\(PERLSI\_MAGIC\);
\+    ENTER;
\+    SAVEI32\(PL\_hints\);
\+    PL\_hints = 0;
\+    save\_re\_context\(\);
&nbsp;     if \(\!gv\_fetchmeth\(stash\, "SWASHNEW"\, 8\, \-1\)\) \{    /\* demand load utf8 \*/
&nbsp;     ENTER;
&nbsp;     errsv\_save = newSVsv\(ERRSV\);
@&#8203;@&#8203; \-1589\,7 \+1594\,6 @&#8203;@&#8203;
&nbsp;     LEAVE;
&nbsp;     \}
&nbsp;     SPAGAIN;
\-    PUSHSTACKi\(PERLSI\_MAGIC\);
&nbsp;     PUSHMARK\(SP\);
&nbsp;     EXTEND\(SP\,5\);
&nbsp;     PUSHs\(sv\_2mortal\(newSVpvn\(pkg\, pkg\_len\)\)\);
@&#8203;@&#8203; \-1598\,10 \+1602\,6 @&#8203;@&#8203;
&nbsp;     PUSHs\(sv\_2mortal\(newSViv\(minbits\)\)\);
&nbsp;     PUSHs\(sv\_2mortal\(newSViv\(none\)\)\);
&nbsp;     PUTBACK;
\-    ENTER;
\-    SAVEI32\(PL\_hints\);
\-    PL\_hints = 0;
\-    save\_re\_context\(\);
&nbsp;     if \(IN\_PERL\_COMPILETIME\) \{
&nbsp;     /\* XXX ought to be handled by lex\_start \*/
&nbsp;     SAVEI32\(PL\_in\_my\);

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
