### ISSUE TITLE
Segfault in 5.6.2 (in parser?)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7739]
Migrated from [rt.perl.org#33710](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=33710) (status was 'resolved')

Searchable as RT33710$

**Comment by p5pRT** [comment]
### From @arc

#### Created by @arc



Reproducible segfault in 5\.6\.2 \(and 5\.6\.1\) on compiling a program with a
missing sub declaration\.  Test case follows&#8203;:

&nbsp;  $ cat foo\.pl
&nbsp;  \#\! /usr/bin/perl \-w

&nbsp;  \# Adding this line fixes the segfault \(and the bug in the program\)&#8203;:
&nbsp;  \#sub foo;

&nbsp;  \($z = foo $x\, y => $y\) =~ s/\.//;

&nbsp;  $ \./perl \-c foo\.pl
&nbsp;  Segmentation fault

This is apparently fixed in 5\.8\.4\, which I have running on a different
machine; it issues the compilation error "Can't modify constant item in
substitution \(s///\) at foo\.pl line 6\, near "/\.//;"\."\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.6.2:

Configured by arc at Fri Jan  7 15:34:50 GMT 2005.

Summary of my perl5 (revision 5.0 version 6 subversion 2) configuration:
  Platform:
    osname=linux, osvers=2.4.20-local, archname=i686-linux
    uname='linux dev 2.4.20-local #1 mon dec 16 11:04:42 gmt 2002 i686 unknown '
    config_args='-Dprefix=/var/tmp/PERL -de'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FI    optimize='-O3',
    cppflags='-fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='2.95.4 20011002 (Debian prerelease)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -ldl -lm -lc -lcrypt -lutil
    perllibs=-lnsl -ldl -lm -lc -lcrypt -lutil
    libc=/lib/libc-2.2.5.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:



@INC for perl v5.6.2:
    /var/tmp/PERL/lib/perl5/5.6.2/i686-linux
    /var/tmp/PERL/lib/perl5/5.6.2
    /var/tmp/PERL/lib/perl5/site_perl/5.6.2/i686-linux
    /var/tmp/PERL/lib/perl5/site_perl/5.6.2
    /var/tmp/PERL/lib/perl5/site_perl
    .


Environment for perl v5.6.2:
    HOME=/home/arc
    LANG=en_GB.UTF-8
    LANGUAGE (unset)
    LC_COLLATE=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin:/sbin:/usr/sbin:/usr/local/sbin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @Smylers

Aaron Crane writes&#8203;:

>   $ cat foo\.pl
>   \#\! /usr/bin/perl \-w
>   \($z = foo $x\, y => $y\) =~ s/\.//;
> 
>   $ \./perl \-c foo\.pl
>   Segmentation fault

I think this can be cut down to just&#8203;:

&nbsp;  % perl5\.6\.2 \-ce '\(a\, b\) =~ s/\.//;'
&nbsp;  Segmentation fault

\(Unless that's a different bug\.\)

Smylers

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tux

On Fri 07 Jan 2005 18&#8203;:03\, Smylers \<Smylers@&#8203;stripey\.com> wrote&#8203;:
> Aaron Crane writes&#8203;:
> 
> >   $ cat foo\.pl
> >   \#\! /usr/bin/perl \-w
> >   \($z = foo $x\, y => $y\) =~ s/\.//;
> > 
> >   $ \./perl \-c foo\.pl
> >   Segmentation fault
> 
> I think this can be cut down to just&#8203;:
> 
>   % perl5\.6\.2 \-ce '\(a\, b\) =~ s/\.//;'
>   Segmentation fault
> 
> \(Unless that's a different bug\.\)

This one does not occur in 5\.8 \(at least 5\.8\.3 and up\)

pc03&#8203;:/P/perl\-current 544 $ perl \-ce'\(a\,b\)=~s/\.//'
Can't modify constant item in substitution \(s///\) at \-e line 1\, at EOF
\-e had compilation errors\.
pc03&#8203;:/P/perl\-current 545 $

\-\- 
H\.Merijn Brand        Amsterdam Perl Mongers \(http&#8203;://amsterdam\.pm\.org/\)
using perl\-5\.6\.1\, 5\.8\.5\, & 5\.9\.x\, and 809 on  HP\-UX 10\.20 & 11\.00\, 11i\,
&nbsp;   AIX 4\.3\, AIX 5\.2\, SuSE 9\.1\, and Win2k\.  http&#8203;://www\.cmve\.net/~merijn/
http&#8203;://archives\.develooper\.com/daily\-build@&#8203;perl\.org/   perl\-qa@&#8203;perl\.org
send smoke reports to&#8203;: smokers\-reports@&#8203;perl\.org\, QA&#8203;: http&#8203;://qa\.perl\.org

**Comment by p5pRT** [comment]
### From @smpeters

> \[hmbrand \- Sat Jan 08 05&#8203;:23&#8203;:35 2005\]&#8203;:
> 
> On Fri 07 Jan 2005 18&#8203;:03\, Smylers \<Smylers@&#8203;stripey\.com> wrote&#8203;:
> > Aaron Crane writes&#8203;:
> > 
> > >   $ cat foo\.pl
> > >   \#\! /usr/bin/perl \-w
> > >   \($z = foo $x\, y => $y\) =~ s/\.//;
> > > 
> > >   $ \./perl \-c foo\.pl
> > >   Segmentation fault
> > 
> > I think this can be cut down to just&#8203;:
> > 
> >   % perl5\.6\.2 \-ce '\(a\, b\) =~ s/\.//;'
> >   Segmentation fault
> > 
> > \(Unless that's a different bug\.\)
> 
> This one does not occur in 5\.8 \(at least 5\.8\.3 and up\)
> 
> pc03&#8203;:/P/perl\-current 544 $ perl \-ce'\(a\,b\)=~s/\.//'
> Can't modify constant item in substitution \(s///\) at \-e line 1\, at EOF
> \-e had compilation errors\.
> pc03&#8203;:/P/perl\-current 545 $
> 

Here's the backtrace I'm getting from 5\.6\.2\.

\#0  Perl\_scalar \(o=0x3c020d80\) at op\.c&#8203;:996
996                 if \(kid\->op\_sibling\)
\(gdb\) bt
\#0  Perl\_scalar \(o=0x3c020d80\) at op\.c&#8203;:996
\#1  0x1c03230d in Perl\_bind\_match \(type=31\, left=0x3c020d80\,
right=0x3c02c440\)
&nbsp;    at op\.c&#8203;:2044
\#2  0x1c02ea1a in Perl\_yyparse \(\) at perly\.y&#8203;:507
\#3  0x1c013671 in S\_parse\_body \(env=0x0\, xsinit=0x1c0110bc \<xs\_init>\)
&nbsp;    at perl\.c&#8203;:1317
\#4  0x1c012d23 in perl\_parse \(my\_perl=0x3c021030\, xsinit=0x1c0110bc
\<xs\_init>\,
&nbsp;    argc=3\, argv=0xcfbf30d8\, env=0x0\) at perl\.c&#8203;:895
\#5  0x1c011079 in main \(argc=3\, argv=0xcfbf30d8\, env=0xcfbf30e8\)
&nbsp;    at perlmain\.c&#8203;:50

**Comment by p5pRT** [comment]
### From @iabyn

Appears to be fixed in 5\.8\.0\, so closing

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
