### ISSUE TITLE
segfault in perl_clone under ithreads and custom PerlIO layer

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7805]
Migrated from [rt.perl.org#34180](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=34180) (status was 'open')

Searchable as RT34180$

**Comment by p5pRT** [comment]
### From stas@stason.org

#### Created by stas@rabbit.stason.org

This is a bug report for perl from stas@&#8203;rabbit\.stason\.org\,
generated with the help of perlbug 1\.35 running under perl v5\.8\.6\.

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

We have yet another chicken\-n\-egg problem with perl\_clone\. If you do a
simple&#8203;:

use threads;
my $thread = threads\->create\(sub \{\}\, undef\)

and STDOUT is opened to some PerlIO layer\, an attempt to clone it will be
performed\. The problem is that this cloning happens too early&#8203;:

perl\-5\.8\.6/sv\.c&#8203;:10859&#8203;:

\#ifdef PERLIO\_LAYERS
&nbsp;     /\* Clone PerlIO tables as soon as we can handle general xx\_dup\(\) \*/
&nbsp;     PerlIO\_clone\(aTHX\_ proto\_perl\, param\);
\#endif

xx\_dup\(\) works for the core perl\, but it doesn't
take into account that a custom PerlIO layer may need other bits set
in my\_perl\. In the above case I get a segfault because PL\_defstash is
bogus\. it's set only after PerlIO\_clone is called\. \(line 10954\)
I get this segfault&#8203;:

\#0  0x404c8a04 in Perl\_gv\_fetchpv \(my\_perl=0x85e6540\,
&nbsp;     nambeg=0x404939d0 "Apache&#8203;::RequestRec"\, add=1\, sv\_type=11\) at gv\.c&#8203;:670
\#1  0x40479f37 in PerlIOApache\_getarg \(my\_perl=0x85e6540\, f=0x828634c\,
&nbsp;     param=0xbfffe9c0\, flags=1\) at modperl\_io\_apache\.c&#8203;:87
\#2  0x405c55b5 in PerlIOBase\_dup \(my\_perl=0x85e6540\, f=0x83576c4\, o=0x828634c\,
&nbsp;     param=0xbfffe9c0\, flags=1\) at perlio\.c&#8203;:2187
\#3  0x405c1e50 in PerlIO\_fdupopen \(my\_perl=0x85e6540\, f=0x828634c\,
&nbsp;     param=0xbfffe9c0\, flags=1\) at perlio\.c&#8203;:542
\#4  0x40555faf in Perl\_fp\_dup \(my\_perl=0x85e6540\, fp=0x828634c\, type=0 '\\0'\,
&nbsp;     param=0xbfffe9c0\) at sv\.c&#8203;:9505
\#5  0x405c22a5 in PerlIO\_clone \(my\_perl=0x85e6540\, proto=0x8abfb10\,
&nbsp;     param=0xbfffe9c0\) at perlio\.c&#8203;:650
\#6  0x4055a6fe in perl\_clone \(proto\_perl=0x8abfb10\, flags=2\) at sv\.c&#8203;:10859
\#7  0x4078aa50 in Perl\_ithread\_create \(my\_perl=0x8abfb10\, obj=0x0\,
&nbsp;     classname=0x82dc948 "threads"\, init\_function=0x8153728\, params=0x815377c\)
&nbsp;     at threads\.xs&#8203;:426
\#8  0x4078b3f7 in XS\_threads\_new \(my\_perl=0x8abfb10\, cv=0x82f0698\)
&nbsp;     at threads\.xs&#8203;:687

the segfault happens here&#8203;:

&nbsp;        if \(\!stash\)
&nbsp;        stash = PL\_defstash;
&nbsp;        if \(\!stash || \!SvREFCNT\(stash\)\) /\* symbol table under destruction \*/

PL\_defstash == 0xabababab here

PerlIOApache\_getarg happens to call gv\_fetchpv which needs a valid
PL\_defstash\.

How do we resolve this problem?

This is not the first time we hit a segfault\, due to
PerlIO\+clone\. Some of those are still unresolved \(e\.g\. perl \-m still
segfaults under threads\)

<details><summary>Perl Info</summary>

```

Flags:
     category=core
     severity=high

Site configuration information for perl v5.8.6:

Configured by stas at Sun Nov 28 13:23:47 EST 2004.

Summary of my perl5 (revision 5 version 8 subversion 6) configuration:
   Platform:
     osname=linux, osvers=2.6.8.1-12mdk, archname=i686-linux-thread-multi
     uname='linux rabbit.stason.org 2.6.8.1-12mdk #1 fri oct 1 12:53:41 
cest 2004 i686 mobile intel(r) pentium(r) 4 - m cpu 2.00ghz unknown gnulinux '
     config_args='-des -Dprefix=/home/stas/perl/5.8.6-ithread -Dusethreads 
-Doptimize=-g -Duseshrplib -Dusedevel -Accflags=-DDEBUG_LEAKING_SCALARS'
     hint=recommended, useposix=true, d_sigaction=define
     usethreads=define use5005threads=undef useithreads=define 
usemultiplicity=define
     useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
     use64bitint=undef use64bitall=undef uselongdouble=undef
     usemymalloc=n, bincompat5005=undef
   Compiler:
     cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS 
-DDEBUG_LEAKING_SCALARS -DDEBUGGING -fno-strict-aliasing -pipe 
-I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 
-I/usr/include/gdbm',
     optimize='-g',
     cppflags='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS 
-DDEBUG_LEAKING_SCALARS -DDEBUGGING -fno-strict-aliasing -pipe 
-I/usr/local/include -I/usr/include/gdbm'
     ccversion='', gccversion='3.4.1 (Mandrakelinux 10.1 3.4.1-4mdk)', 
gccosandvers=''
     intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
     d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
     ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', 
lseeksize=8
     alignbytes=4, prototype=define
   Linker and Libraries:
     ld='cc', ldflags =' -L/usr/local/lib'
     libpth=/usr/local/lib /lib /usr/lib
     libs=-lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lpthread -lc
     perllibs=-lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
     libc=/lib/libc-2.3.3.so, so=so, useshrplib=true, libperl=libperl.so
     gnulibc_version='2.3.3'
   Dynamic Linking:
     dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E 
-Wl,-rpath,/home/stas/perl/5.8.6-ithread/lib/5.8.6/i686-linux-thread-multi/CORE'
     cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:



@INC for perl v5.8.6:
     /home/stas/perl/5.8.6-ithread/lib/5.8.6/i686-linux-thread-multi
     /home/stas/perl/5.8.6-ithread/lib/5.8.6
     /home/stas/perl/5.8.6-ithread/lib/site_perl/5.8.6/i686-linux-thread-multi
     /home/stas/perl/5.8.6-ithread/lib/site_perl/5.8.6
     /home/stas/perl/5.8.6-ithread/lib/site_perl
     .


Environment for perl v5.8.6:
     HOME=/home/stas
     LANG=en_GB
     LANGUAGE=en_GB:en
     LC_ADDRESS=en_CA
     LC_COLLATE=en_GB
     LC_CTYPE=en_GB
     LC_IDENTIFICATION=en_CA
     LC_MEASUREMENT=en_CA
     LC_MESSAGES=en_GB
     LC_MONETARY=en_CA
     LC_NAME=en_CA
     LC_NUMERIC=en_CA
     LC_PAPER=en_CA
     LC_SOURCED=1
     LC_TELEPHONE=en_CA
     LC_TIME=en_GB
     LD_LIBRARY_PATH (unset)
     LOGDIR (unset)
 
PATH=/usr//bin:/bin:/usr/bin:.:/usr/local/bin:/usr/X11R6/bin/:/usr/games:/home/stas/bin:/home/stas/bin:/usr/local/bin:/usr/X11R6/bin:/usr/java/j2re1.4.0/bin/
     PERLDOC_PAGER=less -R
     PERL_BADLANG (unset)
     SHELL=/bin/tcsh

```
</details>

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, Feb 19\, 2005 at 02&#8203;:20&#8203;:28AM \-0000\, Stas Bekman wrote&#8203;:
> We have yet another chicken\-n\-egg problem with perl\_clone\. If you do a
> simple&#8203;:
> 
> use threads;
> my $thread = threads\->create\(sub \{\}\, undef\)
> 
> and STDOUT is opened to some PerlIO layer\, an attempt to clone it will be
> performed\. The problem is that this cloning happens too early&#8203;:

do you have a complete script that reproduces this?

something simple like 
&nbsp;    binmode STDOUT\, '&#8203;:utf8';
didn't segfault


\-\- 
Counsellor Troi states something other than the blindingly obvious\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#16

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From stas@stason.org

Dave Mitchell wrote&#8203;:
> On Sat\, Feb 19\, 2005 at 02&#8203;:20&#8203;:28AM \-0000\, Stas Bekman wrote&#8203;:
> 
>>We have yet another chicken\-n\-egg problem with perl\_clone\. If you do a
>>simple&#8203;:
>>
>>use threads;
>>my $thread = threads\->create\(sub \{\}\, undef\)
>>
>>and STDOUT is opened to some PerlIO layer\, an attempt to clone it will be
>>performed\. The problem is that this cloning happens too early&#8203;:
> 
> 
> do you have a complete script that reproduces this?
> 
> something simple like 
>     binmode STDOUT\, '&#8203;:utf8';
> didn't segfault

Under mod\_perl2

package My&#8203;::Bug;

use Apache2&#8203;::RequestRec \(\);
use Apache2&#8203;::RequestIO \(\);

use Apache2&#8203;::Const \-compile => qw\(OK\);

use threads;

sub handler \{
&nbsp;     my $r = shift;

&nbsp;     my $thread = threads\->create\(sub \{\}\, undef\);
&nbsp;     $thread\->join;

&nbsp;     $r\->content\_type\('text/plain'\);
&nbsp;     print 'found a bug';

&nbsp;     return Apache2&#8203;::Const&#8203;::OK;
\}

1;

and config&#8203;:

\<Location /bug>
&nbsp;   SetHandler perl\-script
&nbsp;   PerlResponseHandler My&#8203;::Bug
\</Location>

I've attached a tarball that reproduces the problem\. Assuming that you've 
mod\_perl2 installed\, unpack it and run&#8203;:

perl Makefile\.PL \-httpd /home/stas/httpd/prefork/bin/httpd
make
make test
\(you should get a segfault\)
\(adjust the path to the location of your httpd\)

Thanks Dave\.

\-\- 
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
Stas Bekman            JAm\_pH \-\-\-\-\-\-> Just Another mod\_perl Hacker
http&#8203;://stason\.org/     mod\_perl Guide \-\-\-> http&#8203;://perl\.apache\.org
mailto&#8203;:stas@&#8203;stason\.org http&#8203;://use\.perl\.org http&#8203;://apacheweek\.com
http&#8203;://modperlbook\.org http&#8203;://apache\.org   http&#8203;://ticketmaster\.com

**Comment by p5pRT** [comment]
### From stas@stason.org

[bug-reporting-skeleton-mp2.tar.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/116698/79757/bug-reporting-skeleton-mp2.tar.gz)

**Comment by p5pRT** [comment]
### From stas@stason.org

A few other related things using APR&#8203;::PerlIO which can be used outside 
mod\_perl&#8203;:

\#foo
use APR&#8203;::Pool;
use APR&#8203;::PerlIO;

my $pool = APR&#8203;::Pool\->new;
my $filename = "/tmp/file";
open my $fh\, ">&#8203;:APR"\, $filename\, $pool or die $\!;

use threads;
my $thread = threads\->create\(sub \{\}\, undef\);
$thread\->join;

% perl\-5\.8\.6\-ithread /tmp/foo
\*\*\* glibc detected \*\*\* double free or corruption \(\!prev\)&#8203;: 0x080f6518 \*\*\*
Abort

% perl\-5\.8\.7\-ithread /tmp/foo

so it looks like it was fixed in 5\.8\.7\.



The following was also segfaulting with 5\.8\.6\, but not with 5\.8\.7&#8203;:


---
use APR&#8203;::Pool;
use APR&#8203;::PerlIO;

my $pool = APR&#8203;::Pool\->new;
my $filename = "/tmp/file";
close STDOUT;
open STDOUT\, ">&#8203;:APR"\, $filename\, $pool or die $\!;

use threads;
my $thread = threads\->create\(sub \{\}\, undef\);
$thread\->join;


---
Adding dup is still not good with 5\.8\.7&#8203;:


---
use APR&#8203;::Pool;
use APR&#8203;::PerlIO;

my $pool = APR&#8203;::Pool\->new;
my $filename = "/tmp/file";
close STDOUT;
open STDOUT\, ">&#8203;:APR"\, $filename\, $pool or die $\!;

open OLDOUT\, ">&STDOUT" or die $\!;

use threads;
my $thread = threads\->create\(sub \{\}\, undef\);
$thread\->join;



---
% perl\-5\.8\.7\-ithread /tmp/foo2
leaked PerlIOAPR handle 0x812d0e8 during global destruction\.
leaked PerlIOAPR handle 0x8065208 during global destruction\.

So this is stilll an issue\. Do you think it's a bug in perl?

\-\- 
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
Stas Bekman            JAm\_pH \-\-\-\-\-\-> Just Another mod\_perl Hacker
http&#8203;://stason\.org/     mod\_perl Guide \-\-\-> http&#8203;://perl\.apache\.org
mailto&#8203;:stas@&#8203;stason\.org http&#8203;://use\.perl\.org http&#8203;://apacheweek\.com
http&#8203;://modperlbook\.org http&#8203;://apache\.org   http&#8203;://ticketmaster\.com

**Comment by p5pRT** [comment]
### From @dcollinsn

Under perl 5\.22 \(mod\_perl from the debian packages\)\, Stas' third test program still segfaults&#8203;:

leaked PerlIOAPR handle 0x70008a0 during global destruction\.
Warning&#8203;: unable to close filehandle properly&#8203;: Illegal seek during global destruction\.
==63931== Invalid read of size 4
==63931==    at 0x6375C38&#8203;: apr\_file\_flush \(in /usr/lib/x86\_64\-linux\-gnu/libapr\-1\.so\.0\.5\.2\)
==63931==    by 0x6DCCB5F&#8203;: ??? \(in /usr/lib/x86\_64\-linux\-gnu/perl5/5\.22/auto/APR/PerlIO/PerlIO\.so\)
==63931==    by 0x53B74E&#8203;: Perl\_PerlIO\_flush \(in /usr/bin/perl\)
==63931==    by 0x53B798&#8203;: Perl\_PerlIO\_flush \(in /usr/bin/perl\)
==63931==    by 0x43EF29&#8203;: perl\_destruct \(in /usr/bin/perl\)
==63931==    by 0x41CBC2&#8203;: main \(in /usr/bin/perl\)
==63931==  Address 0x402a108 is not stack'd\, malloc'd or \(recently\) free'd
