### ISSUE TITLE
syntax error segfaults parser

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7809]
Migrated from [rt.perl.org#34207](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=34207) (status was 'resolved')

Searchable as RT34207$

**Comment by p5pRT** [comment]
### From @nwc10

#### Created by @nwc10



The appended script segfaults Perl's parser\.

\(gdb\) where
\#0  0x80abb4b in Perl\_pad\_free \(my\_perl=0x81db000\, po=8\) at pad\.c&#8203;:1171
\#1  0x809589c in Perl\_op\_clear \(my\_perl=0x81db000\, o=0x81e7be0\) at op\.c&#8203;:516
\#2  0x8095453 in Perl\_op\_free \(my\_perl=0x81db000\, o=0x81e7be0\) at op\.c&#8203;:380
\#3  0x80953ed in Perl\_op\_free \(my\_perl=0x81db000\, o=0x81e7c20\) at op\.c&#8203;:368
\#4  0x80953ed in Perl\_op\_free \(my\_perl=0x81db000\, o=0x81e7cc0\) at op\.c&#8203;:368
\#5  0x80953ed in Perl\_op\_free \(my\_perl=0x81db000\, o=0x81e7ce0\) at op\.c&#8203;:368
\#6  0x80953ed in Perl\_op\_free \(my\_perl=0x81db000\, o=0x81e7d00\) at op\.c&#8203;:368
\#7  0x80953ed in Perl\_op\_free \(my\_perl=0x81db000\, o=0x81e7a20\) at op\.c&#8203;:368
\#8  0x80a0c2f in Perl\_newATTRSUB \(my\_perl=0x81db000\, floor=103\, o=0x81e79c0\, 
&nbsp;    proto=0x0\, attrs=0x0\, block=0x81e7a20\) at op\.c&#8203;:4376
\#9  0x80928de in Perl\_yyparse \(my\_perl=0x81db000\) at perly\.y&#8203;:355
\#10 0x8065065 in S\_parse\_body \(my\_perl=0x81db000\, env=0x0\, 
&nbsp;    xsinit=0x805ff00 \<xs\_init>\) at perl\.c&#8203;:1778
\#11 0x8063df4 in perl\_parse \(my\_perl=0x81db000\, xsinit=0x805ff00 \<xs\_init>\, 
&nbsp;    argc=2\, argv=0xbfbff6a4\, env=0x0\) at perl\.c&#8203;:1282
\#12 0x805fe6b in main \(argc=2\, argv=0xbfbff6a4\, env=0xbfbff6b0\)
&nbsp;    at perlmain\.c&#8203;:96
\#13 0x805fd2e in \_start \(\)


The problem only seems to happen for ithreads\, and there is no segfault in
blead\, so I assume that it would go away if the bison based tokeniser were
integrated into maint\. \(Anyone got a spare EBCDIC machine?\)

Nicholas Clark


sub thunk
\{
&nbsp;  my $method;
&nbsp;  my $arg;
&nbsp;  foreach my $arg \(keys %args\)
&nbsp;  \{
&nbsp;    $string \.= '';
&nbsp;  \}

&nbsp;  \{
&nbsp;    no strict 'refs'
&nbsp;    unless \(1\)
&nbsp;    \{
&nbsp;    \}
&nbsp;  \}
\}
\_\_END\_\_

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

This perlbug was built using Perl v5.8.6 - Mon Feb  7 07:42:56 GMT 2005
It is being executed now by  Perl v5.8.6 - Mon Feb  7 07:28:59 GMT 2005.

Site configuration information for perl v5.8.6:

Configured by nick at Mon Feb  7 07:28:59 GMT 2005.

Summary of my perl5 (revision 5 version 8 subversion 6) configuration:
  Platform:
    osname=freebsd, osvers=4.7-stable, archname=i386-freebsd-thread-multi
    uname='freebsd plum.flirble.org 4.7-stable freebsd 4.7-stable #0: sun mar 23 18:33:06 gmt 2003 scot@pear.flirble.org:usrsrcsyscompileplum i386 '
    config_args='-Dprefix=/home/nick/Reference/5.8.6 -Doptimize=-Os -Duseithreads -Dcc=ccache gcc -Dld=gcc -Dcf_email=nick@ccl4.org -Dperladmin=nick@ccl4.org -Dman1dir=  -Dman3dir=  -de'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='ccache gcc', ccflags ='-DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -fno-strict-aliasing -pipe -I/usr/local/include',
    optimize='-Os',
    cppflags='-DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -fno-strict-aliasing -pipe -I/usr/local/include'
    ccversion='', gccversion='2.95.4 20020320 [FreeBSD]', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags ='-pthread -Wl,-E  -L/usr/local/lib'
    libpth=/usr/lib /usr/local/lib
    libs=-lbind -lgdbm -ldb -lm -lcrypt -lutil -lc_r
    perllibs=-lbind -lm -lcrypt -lutil -lc_r
    libc=, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags=' '
    cccdlflags='-DPIC -fPIC', lddlflags='-shared  -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.6:
    /home/nick/Reference/5.8.6/lib/perl5/5.8.6/i386-freebsd-thread-multi
    /home/nick/Reference/5.8.6/lib/perl5/5.8.6
    /home/nick/Reference/5.8.6/lib/perl5/site_perl/5.8.6/i386-freebsd-thread-multi
    /home/nick/Reference/5.8.6/lib/perl5/site_perl/5.8.6
    /home/nick/Reference/5.8.6/lib/perl5/site_perl
    .


Environment for perl v5.8.6:
    HOME=/home/nick
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/nick/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/usr/X11R6/bin:/home/nick/bin:/usr/local/sbin:/sbin:/usr/sbin
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/bash

```
</details>

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'new' to 'resolved'
