### ISSUE TITLE
core dump with unmatched empty quotes

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7828]
Migrated from [rt.perl.org#34346](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=34346) (status was 'resolved')

Searchable as RT34346$

**Comment by p5pRT** [comment]
### From trew@nologin.org

#### Created by trew@nologin.org


This is a bug report for perl from trew@&#8203;nologin\.org\,
generated with the help of perlbug 1\.35 running under perl v5\.8\.5\.


\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

null ptr handling unmatched quotes :&#8203;:  '"""' || "'''"

trew@&#8203;cecilia trew $ perl \-e '"""'
Segmentation fault \(core dumped\)
trew@&#8203;cecilia trew $ gdb \-q \-c core
Core was generated by \`perl \-e """'\.
Program terminated with signal 11\, Segmentation fault\.
\#0  0x80044e22 in ?? \(\)
\(gdb\) x/i $eip
0x80044e22&#8203;:     movzbl \(%edx\)\,%eax
\(gdb\) i r edx eax
edx            0x0      0
eax            0x8011a93c       \-2146326212

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.8.5:

Configured by Gentoo at Thu Feb 24 00:04:26 PST 2005.

Summary of my perl5 (revision 5 version 8 subversion 5) configuration:
  Platform:
    osname=linux, osvers=2.6.10-hardened-r3, archname=i686-linux
    uname='linux cecilia 2.6.10-hardened-r3 #1 smp mon jan 24 14:16:21 pst 2005 i686 amd athlon(tm) mp 2400+ authenticamd gnulinux '
    config_args='-des -Darchname=i686-linux -Dcccdlflags=-fPIC -Dccdlflags=-rdynamic -Dcc=gcc -Dprefix=/usr -Dvendorprefix=/usr -Dsiteprefix=/usr -Dlocincpth=  -Doptimize=-O3 -march=athlon-xp -fomit-frame-pointer -pipe -Duselargefiles -Dd_semctl_semun -Dscriptdir=/usr/bin -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 -Dinstallman1dir=/usr/share/man/man1 -Dinstallman3dir=/var/tmp/portage/perl-5.8.5-r4/image//usr/share/man/man3 -Dman1ext=1 -Dman3ext=3pm -Dinc_version_list=5.8.0 5.8.0/i686-linux 5.8.2 5.8.2/i686-linux 5.8.4 5.8.4/i686-linux  -Dcf_by=Gentoo -Ud_csh -Di_ndbm -Di_gdbm -Di_db -Dusrinc=/usr/include'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-fno-strict-aliasing -pipe -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O3 -march=athlon-xp -fomit-frame-pointer -pipe',
    cppflags='-DPERL5 -fno-strict-aliasing -pipe'
    ccversion='', gccversion='3.3.5  (Gentoo Hardened Linux 3.3.5-r1, ssp-3.3.2-3, pie-8.7.7.1)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lpthread -lnsl -lndbm -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/libc-2.3.4.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.3.4'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.5:
    /etc/perl
    /usr/lib/perl5/site_perl/5.8.5/i686-linux
    /usr/lib/perl5/site_perl/5.8.5
    /usr/lib/perl5/site_perl/5.8.4
    /usr/lib/perl5/site_perl/5.8.4/i686-linux
    /usr/lib/perl5/site_perl
    /usr/lib/perl5/vendor_perl/5.8.5/i686-linux
    /usr/lib/perl5/vendor_perl/5.8.5
    /usr/lib/perl5/vendor_perl
    /usr/lib/perl5/5.8.5/i686-linux
    /usr/lib/perl5/5.8.5
    /usr/local/lib/site_perl
    /usr/lib/perl5/site_perl/5.8.4
    /usr/lib/perl5/site_perl/5.8.4/i686-linux
    .


Environment for perl v5.8.5:
    HOME=/home/trew
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/bin:/usr/bin:/usr/local/bin:/opt/bin:/usr/i686-pc-linux-gnu/gcc-bin/3.3.5
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @smpeters

> \[trew@&#8203;nologin\.org \- Sat Mar 05 09&#8203;:54&#8203;:59 2005\]&#8203;:
> 
> 
> This is a bug report for perl from trew@&#8203;nologin\.org\,
> generated with the help of perlbug 1\.35 running under perl v5\.8\.5\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> 
> null ptr handling unmatched quotes :&#8203;:  '"""' || "'''"
> 
> trew@&#8203;cecilia trew $ perl \-e '"""'
> Segmentation fault \(core dumped\)
> trew@&#8203;cecilia trew $ gdb \-q \-c core
> Core was generated by \`perl \-e """'\.
> Program terminated with signal 11\, Segmentation fault\.
> \#0  0x80044e22 in ?? \(\)
> \(gdb\) x/i $eip
> 0x80044e22&#8203;:     movzbl \(%edx\)\,%eax
> \(gdb\) i r edx eax
> edx            0x0      0
> eax            0x8011a93c       \-2146326212
> 
> 

Can anyone else been able to replicate this core dump?  I've tried the
following without being able to replicate\.  It get the following error&#8203;:

\[steve@&#8203;kirk ~\]$ perl \-e '"""'
String found where operator expected at \-e line 1\, at end of line
&nbsp;        \(Missing semicolon on previous line?\)
Can't find string terminator '"' anywhere before EOF at \-e line 1\.

I've tried the following Perls&#8203;:
current\-blead&#8203;: OpenBSD\, Linux 2\.6\.10
5\.8\.6&#8203;:  Mac OS X
5\.8\.5&#8203;:  OpenBSD\, Linux 2\.6\.10
5\.6\.2&#8203;:  OpenBSD

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @nwc10

On Wed\, Mar 16\, 2005 at 05&#8203;:27&#8203;:20AM \-0000\, Steve Peters via RT wrote&#8203;:

> Can anyone else been able to replicate this core dump?  I've tried the

No\. Not with \-O3 \-fomit\-framepointer on maint on x86 debian\.

Nicholas Clark

**Comment by p5pRT** [comment]
### From @mhx

On 2005\-03\-16\, at 05&#8203;:27&#8203;:20 \-0000\, Steve Peters via RT wrote&#8203;:

> > \[trew@&#8203;nologin\.org \- Sat Mar 05 09&#8203;:54&#8203;:59 2005\]&#8203;:
> > 
> > 
> > This is a bug report for perl from trew@&#8203;nologin\.org\,
> > generated with the help of perlbug 1\.35 running under perl v5\.8\.5\.
> > 
> > 
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > 
> > null ptr handling unmatched quotes :&#8203;:  '"""' || "'''"
> > 
> > trew@&#8203;cecilia trew $ perl \-e '"""'
> > Segmentation fault \(core dumped\)
> > trew@&#8203;cecilia trew $ gdb \-q \-c core
> > Core was generated by \`perl \-e """'\.
> > Program terminated with signal 11\, Segmentation fault\.
> > \#0  0x80044e22 in ?? \(\)
> > \(gdb\) x/i $eip
> > 0x80044e22&#8203;:     movzbl \(%edx\)\,%eax
> > \(gdb\) i r edx eax
> > edx            0x0      0
> > eax            0x8011a93c       \-2146326212
> > 
> > 
> 
> Can anyone else been able to replicate this core dump?  I've tried the
> following without being able to replicate\.  It get the following error&#8203;:

No\. Tested on Linux 2\.6\.10 with nearly 100 versions/configurations
between 5\.003 and blead\, even running the whole 5\.8\.x series under
valgrind doesn't show any problems\.

Marcus

\-\- 
Real Users never know what they want\, but they always know when your program
doesn't deliver it\.

**Comment by p5pRT** [comment]
### From sitz@onastick.net

On Wed\, Mar 16\, 2005 at 05&#8203;:27&#8203;:20AM \-0000\, Steve Peters via RT wrote&#8203;:
> > \[trew@&#8203;nologin\.org \- Sat Mar 05 09&#8203;:54&#8203;:59 2005\]&#8203;:
> > 
> > 
> > This is a bug report for perl from trew@&#8203;nologin\.org\,
> > generated with the help of perlbug 1\.35 running under perl v5\.8\.5\.
> > 
> > 
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > 
> > null ptr handling unmatched quotes :&#8203;:  '"""' || "'''"
> > 
> > trew@&#8203;cecilia trew $ perl \-e '"""'
> > Segmentation fault \(core dumped\)
> > trew@&#8203;cecilia trew $ gdb \-q \-c core
> > Core was generated by \`perl \-e """'\.
> > Program terminated with signal 11\, Segmentation fault\.
> > \#0  0x80044e22 in ?? \(\)
> > \(gdb\) x/i $eip
> > 0x80044e22&#8203;:     movzbl \(%edx\)\,%eax
> > \(gdb\) i r edx eax
> > edx            0x0      0
> > eax            0x8011a93c       \-2146326212
> > 
> > 
> 
> Can anyone else been able to replicate this core dump?  I've tried the
> following without being able to replicate\.  It get the following error&#8203;:

I came across something similar to this the other day\, using a recent
gentoo ebuild of 5\.8\.6 \(I /think/ it was 5\.8\.6\-r1\, but it might have
been r2 or r3\); triggered a segfault with&#8203;:

perl \-e 'print if $\. >= 1"'

Upgrading to \-r4 fixed the issue\. FYI\, HTH\, HAND\. =\)

My make\.conf \(minus comments\)&#8203;:

USE="\-cups \-emacs \-emacs\-w3 gnome \-kde \-fastcgi \-informix \-ipv6 \-java
jpeg \-kerberos \-krb4 \-ldap mmx \-pcmcia png \-pnp readline \-snmp \-socks5
sse ssl tcpd \-tiff usb X zlib"
CHOST="i686\-pc\-linux\-gnu"
CFLAGS="\-O3 \-march=pentium4 \-funroll\-loops \-pipe"
CXXFLAGS="$\{CFLAGS\}"
ACCEPT\_KEYWORDS="~x86"
MAKEOPTS="\-j3"
AUTOCLEAN="yes"
FEATURES="sandbox ccache buildpkg userpriv usersandbox"

gcc \(GCC\) 3\.4\.3 20050110 \(Gentoo Linux 3\.4\.3\.20050110\,
ssp\-3\.4\.3\.20050110\-0\, pie\-8\.7\.7\)

Single 2\.8Ghz hyperthreaded P4

FYI\, HTH\, HAND\.

\-\-n

\-\- 
\<huey> dd of=/dev/fd0 if=/dev/flippy bs=1024
\<huey> ^^^ Making Flippy Floppy

**Comment by p5pRT** [comment]
### From @smpeters

> 
> I came across something similar to this the other day\, using a recent
> gentoo ebuild of 5\.8\.6 \(I /think/ it was 5\.8\.6\-r1\, but it might have
> been r2 or r3\); triggered a segfault with&#8203;:
> 
> perl \-e 'print if $\. >= 1"'
> 
> Upgrading to \-r4 fixed the issue\. FYI\, HTH\, HAND\. =\)
> 

Great\,  problem resolved\.

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'resolved'
