### ISSUE TITLE
Segfault on &DB::sub declared but not defined

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7866]
Migrated from [rt.perl.org#34892](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=34892) (status was 'resolved')

Searchable as RT34892$

**Comment by p5pRT** [comment]
### From ambrus@math.bme.hu

#### Created by ambrus@math.bme.hu



The following code segfaults my perl&#8203;:

&nbsp;  perl \-we 'sub DB&#8203;::sub; sub foo \{ \} BEGIN \{ $^P |= 1; \} foo\(\);'

I belive that pure perl should never segfault without a reason\, so unless
you know a good reason for this\, I consider this a bug\.

Here\, the BEGIN \{ $^P |= 1 \} part should make perl call &DB&#8203;::sub on entry
to the function foo\.  If I define &DB&#8203;::sub\, this works fine\.  If I don't
even declare &DB&#8203;::sub\, foo\(\) is called and the debugging bit is ignored\.

I was able to reproduce this bug on various versions of perl \(from 5\.8\.2
to 5\.8\.6\) on i686\-linux\, and someone has reported that it happens on
windows too\.

Here's a quick backtrace of perl 5\.8\.6 in case you cannot reproduce the
bug \(but I'm sure you can\)&#8203;:

&nbsp;  \(gdb\) r \-we 'sub DB&#8203;::sub; sub foo \{ \} BEGIN \{ $^P |= 1; \} foo\(\);'
&nbsp;  Starting program&#8203;: /home/ambrus/local/gperl/bin/perl \-we 'sub DB&#8203;::sub; sub
&nbsp;  foo \{ \} BEGIN \{ $^P |= 1;
&nbsp;  \} foo\(\);'

&nbsp;  Program received signal SIGSEGV\, Segmentation fault\.
&nbsp;  0x080d21e1 in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:2948
&nbsp;  2948                if \(AvREAL\(av\)\) \{
&nbsp;  \(gdb\) bt
&nbsp;  \#0  0x080d21e1 in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:2948
&nbsp;  \#1  0x080b4004 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1449
&nbsp;  \#2  0x08062660 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1934
&nbsp;  \#3  0x080621f7 in perl\_run \(my\_perl=0x8174c70\) at perl\.c&#8203;:1853
&nbsp;  \#4  0x0805e73a in main \(argc=3\, argv=0xbffff854\, env=0xbffff864\) at
&nbsp;  perlmain\.c&#8203;:98
&nbsp;  \(gdb\) p av
&nbsp;  $1 = \(AV \*\) 0x8172298
&nbsp;  \(gdb\) p \*av
&nbsp;  $2 = \{sv\_any = 0x0\, sv\_refcnt = 2147483645\, sv\_flags = 8388608\}

Now AvREAL\(av\) calls AvFLAGS\(av\) which tries to dereference SvANY\(av\)
which is really av\->sv\_any\, that is\, a null pointer\, so it segfaults; but
I don't know why I'm saying this because surely it won't help you much\.

Thanks\,

ambrus

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.8.6:

Configured by ambrus at Thu Mar 24 20:47:34 CET 2005.

Summary of my perl5 (revision 5 version 8 subversion 6) configuration:
  Platform:
    osname=linux, osvers=2.4.29, archname=i686-linux
    uname='linux king 2.4.29 #1 fri mar 4 22:34:34 cet 2005 i686 pentium ii (deschutes) genuineintel gnulinux '
    config_args='-Dprefix=~ambrus/local/gperl/ -Doptimize=-g'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-DDEBUGGING -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-g',
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe -I/usr/local/include'
    ccversion='', gccversion='3.4.3', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lndbm -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/libc-2.3.2.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.3.2'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.6:
    /home/ambrus/local/gperl/lib/5.8.6/i686-linux
    /home/ambrus/local/gperl/lib/5.8.6
    /home/ambrus/local/gperl//lib/site_perl/5.8.6/i686-linux
    /home/ambrus/local/gperl//lib/site_perl/5.8.6
    /home/ambrus/local/gperl//lib/site_perl
    .


Environment for perl v5.8.6:
    HOME=/home/ambrus
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/ambrus/local/bin:/usr/local/bin:/bin:/usr/bin:/usr/games/bin:/usr/X11R6/bin:/usr/qt/3/bin:/usr/kde/3.2/bin:/opt/Acrobat5
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @rgs

Zsban Ambrus wrote&#8203;:
> The following code segfaults my perl&#8203;:
> 
>   perl \-we 'sub DB&#8203;::sub; sub foo \{ \} BEGIN \{ $^P |= 1; \} foo\(\);'
> 
> I belive that pure perl should never segfault without a reason\, so unless
> you know a good reason for this\, I consider this a bug\.

Thanks for this report; I've fixed this bug in the development version
of perl with change \#24215\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@rgs - Status changed from 'open' to 'resolved'
