### ISSUE TITLE
reset coredumps pre 5.8.0

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7910]
Migrated from [rt.perl.org#35427](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=35427) (status was 'resolved')

Searchable as RT35427$

**Comment by p5pRT** [comment]
### From @nwc10

#### Created by @nwc10



/Users/nick/Reference/5\.6\.2\-g/bin/perl5\.6\.2\-32 \-MData&#8203;::Dumper \-e 'package Data&#8203;::Dumper; reset'
Bus error

\(gdb\) where
\#0  0x0005a1d8 in Perl\_sv\_reset \(s=0x129570 ""\, stash=0x806fe0\) at sv\.c&#8203;:5063
\#1  0x000ad534 in Perl\_pp\_reset \(\) at pp\_ctl\.c&#8203;:1631
\#2  0x000dd590 in Perl\_runops\_debug \(\) at run\.c&#8203;:53
\#3  0x0002114c in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1471
\#4  0x00020a74 in perl\_run \(my\_perl=0x300140\) at perl\.c&#8203;:1393
\#5  0x00001c5c in main \(argc=4\, argv=0xbffff6c4\, env=0xbffff6d8\) at perlmain\.c&#8203;:52

Line 5063 is the middle line of&#8203;:

&nbsp;    if \(\!\*s\) \{        /\* reset ?? searches \*/
&nbsp;    for \(pm = HvPMROOT\(stash\); pm; pm = pm\->op\_pmnext\) \{
&nbsp;        pm\->op\_pmdynflags &= ~PMdf\_USED;
&nbsp;    \}
&nbsp;    return;
&nbsp;    \}

I'm not convinced that gdb has the correct value of pm\. It seems to have
pm for the second iteration&#8203;:

\(gdb\) p pm
$7 = \(PMOP \*\) 0xa7f2c
\(gdb\) p stash\->sv\_any\->xhv\_pmroot
$8 = \(PMOP \*\) 0x336470
\(gdb\) p stash\->sv\_any\->xhv\_pmroot\->op\_pmnext
$9 = \(PMOP \*\) 0xa7f2c

However\, the cause of the bus error is clear&#8203;:

\(gdb\) p \*pm\->op\_pmnext           
$10 = \{
&nbsp;  op\_next = 0x7f9a0000\, 
&nbsp;  op\_sibling = 0x40be0014\, 
&nbsp;  op\_ppaddr = 0x3c9f0ffe\, 
&nbsp;  op\_targ = 945815552\, 
&nbsp;  op\_type = 14468\, 
&nbsp;  op\_seq = 18156\, 
&nbsp;  op\_flags = 72 'H'\, 
&nbsp;  op\_private = 5 '\\005'\, 
&nbsp;  op\_first = 0x3c000800\, 
&nbsp;  op\_last = 0x60000100\, 
&nbsp;  op\_pmreplroot = 0x7f9a0000\, 
&nbsp;  op\_pmreplstart = 0x40be005c\, 
&nbsp;  op\_pmnext = 0x7f83e378\, 
&nbsp;  op\_pmregexp = 0x4bff34ad\, 
&nbsp;  op\_pmflags = 31869\, 
&nbsp;  op\_pmpermflags = 7032\, 
&nbsp;  op\_pmdynflags = 127 '\\177'
\}

\(gdb\) p \*pm\->op\_pmnext\->op\_pmnext
Cannot access memory at address 0x7f83e378

And my question\, which I fear will be Warnocked \- do we know what change
caused this bug to be fixed by 5\.8\.0?
Or can anyone reproduce it in 5\.8\.0 or later?

Nicholas Clark

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

This perlbug was built using Perl v5.8.6 - Wed May 11 11:02:38 BST 2005
It is being executed now by  Perl v5.6.2 - Sat Mar 20 21:41:05 GMT 2004.

Site configuration information for perl v5.6.2:

Configured by nick at Sat Mar 20 21:41:05 GMT 2004.

Summary of my perl5 (revision 5.0 version 6 subversion 2) configuration:
  Platform:
    osname=darwin, osvers=7.3.0, archname=darwin
    uname='darwin ship-in-a-bottle.local 7.3.0 darwin kernel version 7.3.0: fri mar 5 14:22:55 pst 2004; root:xnuxnu-517.3.15.obj~4release_ppc power macintosh powerpc '
    config_args='-Dusedevel=y -Dcc=ccache gcc -Dld=gcc -Ubincompat5005 -Uinstallusrbinperl -Dcf_email=nick@ccl4.org -Dperladmin=nick@ccl4.org -Dinc_version_list=  -Dinc_version_list_init=0 -Dprefix=~/Reference/5.6.2-g -Doptimize=-g -Uusethreads -Duse64bitint -de'
    hint=previous, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=undef d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
  Compiler:
    cc='ccache gcc', ccflags ='-pipe -fno-common -DPERL_DARWIN -no-cpp-precomp -DDEBUGGING -fno-strict-aliasing',
    optimize='-g',
    cppflags='-pipe -fno-common -DPERL_DARWIN -no-cpp-precomp -DDEBUGGING -fno-strict-aliasing'
    ccversion='', gccversion='3.3 20030304 (Apple Computer, Inc. build 1495)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=4321
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=8
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='env MACOSX_DEPLOYMENT_TARGET=10.3 cc', ldflags =''
    libpth=/usr/lib
    libs=-ldbm -ldl -lm -lc
    perllibs=-ldl -lm -lc
    libc=/usr/lib/libc.dylib, so=dylib, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dyld.xs, dlext=bundle, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags=' -bundle -undefined dynamic_lookup'

Locally applied patches:
    MAINT24305


@INC for perl v5.6.2:
    /sw/lib/perl5/darwin
    /sw/lib/perl5
    /sw/lib/perl5/darwin
    /Users/nick/Reference/5.6.2-g/lib/perl5/5.6.2/darwin
    /Users/nick/Reference/5.6.2-g/lib/perl5/5.6.2
    /Users/nick/Reference/5.6.2-g/lib/perl5/site_perl/5.6.2/darwin
    /Users/nick/Reference/5.6.2-g/lib/perl5/site_perl/5.6.2
    /Users/nick/Reference/5.6.2-g/lib/perl5/site_perl
    .


Environment for perl v5.6.2:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/nick
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/nick/bin:/sw/bin:/sw/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/sbin:/sbin:/usr/sbin
    PERL5LIB=/sw/lib/perl5:/sw/lib/perl5/darwin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @smpeters

> \[nicholas \- Thu May 12 14&#8203;:52&#8203;:46 2005\]&#8203;:
> 
> This is a bug report for perl from nick@&#8203;ccl4\.org\,
> generated with the help of perlbug 1\.35 running under perl v5\.6\.2\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> 
> /Users/nick/Reference/5\.6\.2\-g/bin/perl5\.6\.2\-32 \-MData&#8203;::Dumper \-e
>    'package Data&#8203;::Dumper; reset'
> Bus error
> 
> \(gdb\) where
> \#0  0x0005a1d8 in Perl\_sv\_reset \(s=0x129570 ""\, stash=0x806fe0\) at
>    sv\.c&#8203;:5063
> \#1  0x000ad534 in Perl\_pp\_reset \(\) at pp\_ctl\.c&#8203;:1631
> \#2  0x000dd590 in Perl\_runops\_debug \(\) at run\.c&#8203;:53
> \#3  0x0002114c in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1471
> \#4  0x00020a74 in perl\_run \(my\_perl=0x300140\) at perl\.c&#8203;:1393
> \#5  0x00001c5c in main \(argc=4\, argv=0xbffff6c4\, env=0xbffff6d8\) at
>    perlmain\.c&#8203;:52
> 
> Line 5063 is the middle line of&#8203;:
> 
>     if \(\!\*s\) \{        /\* reset ?? searches \*/
>     for \(pm = HvPMROOT\(stash\); pm; pm = pm\->op\_pmnext\) \{
>         pm\->op\_pmdynflags &= ~PMdf\_USED;
>     \}
>     return;
>     \}
> 
> I'm not convinced that gdb has the correct value of pm\. It seems to
>    have
> pm for the second iteration&#8203;:
> 
> \(gdb\) p pm
> $7 = \(PMOP \*\) 0xa7f2c
> \(gdb\) p stash\->sv\_any\->xhv\_pmroot
> $8 = \(PMOP \*\) 0x336470
> \(gdb\) p stash\->sv\_any\->xhv\_pmroot\->op\_pmnext
> $9 = \(PMOP \*\) 0xa7f2c
> 
> However\, the cause of the bus error is clear&#8203;:
> 
> \(gdb\) p \*pm\->op\_pmnext
> $10 = \{
>   op\_next = 0x7f9a0000\,
>   op\_sibling = 0x40be0014\,
>   op\_ppaddr = 0x3c9f0ffe\,
>   op\_targ = 945815552\,
>   op\_type = 14468\,
>   op\_seq = 18156\,
>   op\_flags = 72 'H'\,
>   op\_private = 5 '\\005'\,
>   op\_first = 0x3c000800\,
>   op\_last = 0x60000100\,
>   op\_pmreplroot = 0x7f9a0000\,
>   op\_pmreplstart = 0x40be005c\,
>   op\_pmnext = 0x7f83e378\,
>   op\_pmregexp = 0x4bff34ad\,
>   op\_pmflags = 31869\,
>   op\_pmpermflags = 7032\,
>   op\_pmdynflags = 127 '\\177'
> \}
> 
> \(gdb\) p \*pm\->op\_pmnext\->op\_pmnext
> Cannot access memory at address 0x7f83e378
> 
> And my question\, which I fear will be Warnocked \- do we know what
>    change
> caused this bug to be fixed by 5\.8\.0?
> Or can anyone reproduce it in 5\.8\.0 or later?
> 
> Nicholas Clark
> 

It is working fine in 5\.5\-maint\.

steve@&#8203;kirk&#8203;:\~/perl\-5\.5\.x$ \./perl \-Ilib \-MData&#8203;::Dumper \-e 'package
Data&#8203;::Dumper; reset'
steve@&#8203;kirk&#8203;:\~/perl\-5\.5\.x$

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @smpeters

On Thu May 12 14&#8203;:52&#8203;:46 2005\, nicholas wrote&#8203;:
> This is a bug report for perl from nick@&#8203;ccl4\.org\,
> generated with the help of perlbug 1\.35 running under perl v5\.6\.2\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> 
> /Users/nick/Reference/5\.6\.2\-g/bin/perl5\.6\.2\-32 \-MData&#8203;::Dumper \-e
>    'package Data&#8203;::Dumper; reset'
> Bus error
> 
> \(gdb\) where
> \#0  0x0005a1d8 in Perl\_sv\_reset \(s=0x129570 ""\, stash=0x806fe0\) at
>    sv\.c&#8203;:5063
> \#1  0x000ad534 in Perl\_pp\_reset \(\) at pp\_ctl\.c&#8203;:1631
> \#2  0x000dd590 in Perl\_runops\_debug \(\) at run\.c&#8203;:53
> \#3  0x0002114c in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1471
> \#4  0x00020a74 in perl\_run \(my\_perl=0x300140\) at perl\.c&#8203;:1393
> \#5  0x00001c5c in main \(argc=4\, argv=0xbffff6c4\, env=0xbffff6d8\) at
>    perlmain\.c&#8203;:52
> 
> Line 5063 is the middle line of&#8203;:
> 
>     if \(\!\*s\) \{        /\* reset ?? searches \*/
>     for \(pm = HvPMROOT\(stash\); pm; pm = pm\->op\_pmnext\) \{
>         pm\->op\_pmdynflags &= ~PMdf\_USED;
>     \}
>     return;
>     \}
> 
> I'm not convinced that gdb has the correct value of pm\. It seems to
>    have
> pm for the second iteration&#8203;:
> 
> \(gdb\) p pm
> $7 = \(PMOP \*\) 0xa7f2c
> \(gdb\) p stash\->sv\_any\->xhv\_pmroot
> $8 = \(PMOP \*\) 0x336470
> \(gdb\) p stash\->sv\_any\->xhv\_pmroot\->op\_pmnext
> $9 = \(PMOP \*\) 0xa7f2c
> 
> However\, the cause of the bus error is clear&#8203;:
> 
> \(gdb\) p \*pm\->op\_pmnext
> $10 = \{
>   op\_next = 0x7f9a0000\,
>   op\_sibling = 0x40be0014\,
>   op\_ppaddr = 0x3c9f0ffe\,
>   op\_targ = 945815552\,
>   op\_type = 14468\,
>   op\_seq = 18156\,
>   op\_flags = 72 'H'\,
>   op\_private = 5 '\\005'\,
>   op\_first = 0x3c000800\,
>   op\_last = 0x60000100\,
>   op\_pmreplroot = 0x7f9a0000\,
>   op\_pmreplstart = 0x40be005c\,
>   op\_pmnext = 0x7f83e378\,
>   op\_pmregexp = 0x4bff34ad\,
>   op\_pmflags = 31869\,
>   op\_pmpermflags = 7032\,
>   op\_pmdynflags = 127 '\\177'
> \}
> 
> \(gdb\) p \*pm\->op\_pmnext\->op\_pmnext
> Cannot access memory at address 0x7f83e378
> 
> And my question\, which I fear will be Warnocked \- do we know what
>    change
> caused this bug to be fixed by 5\.8\.0?
> Or can anyone reproduce it in 5\.8\.0 or later?
> 
> Nicholas Clark
> 

It appears to be some change between 5\.7\.0 and 5\.7\.1 that fixed the core
dump in reset\(\)\.

**Comment by p5pRT** [comment]
@chorny - Status changed from 'open' to 'stalled'

**Comment by p5pRT** [comment]
@chorny - Status changed from 'stalled' to 'resolved'
