### ISSUE TITLE
Perl dumps core (SIGBUS) while eval'ing a string

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7911]
Migrated from [rt.perl.org#35449](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=35449) (status was 'rejected')

Searchable as RT35449$

**Comment by p5pRT** [comment]
### From ks@helios-net.ru

Perl crashes \(SIGBUS\) while eval'ing a string\.

Unfortunately\, it's not very easy to provide a good test case\, because the
bug reveals in a rather complex case\, involving many preliminary steps\.
But I will try to describe the situation as completely as possible\.

My program is a CGI script in perl\, which provides web\-access to a database
in Informix\.
The described situation occures after an error happenes in DBD&#8203;::Informix
module\. The error is\, to be exact\, a syntax error in a prepared SQL
expression\.
After an Informix error is thrown and catched\, my script prints error
description to STDOUT and after that evals a string\, which must append the
error text with an appropriate HTML footer for the page\.
While this string is evaluated\, a SIGBUS occures and perl dumps core\.

I encountered this error on perl 5\.8\.5\, but after that I've built perl 5\.8\.6
with debug info and installed it in a separate directory\. The error is still
there\.
Appearance of the problem depends on the contents of the string being
evaluated\.
These are short test examples of such strings&#8203;:

'print scalar localtime;print scalar localtime;' => OK
'print scalar localtime;print scalar localtime' => OK
'print scalar localtime;print scalar localtime;print scalar localtime;' =>
OK
'print scalar localtime;print scalar localtime;print scalar localtime' =>
SIGBUS
'print scalar localtime;print scalar localtime;print scalar localtime;print
scalar localtime;' => SIGBUS
'print scalar localtime;print scalar localtime;print scalar localtime;print
scalar localtime' => SIGBUS
'print scalar localtime;print $var' => OK
'print scalar localtime;print "$var"' => SIGBUS
'print scalar localtime;print "$var";' => OK
'print scalar localtime;print "$\{var\}";' => OK
'print scalar localtime;print "$\{var\}sometext";' => SIGBUS
'print "A";print "$\{var\}sometext";' => SIGBUS
'my $a = "A"; my $b = $var' => OK
'my $a = "A"; my $b = "$var"' => SIGBUS
'my $a = "A"; my $b = "$var";' => OK
'my $a = "A"; my $b = "$\{var\}sometext";' => SIGBUS

The stack trace from the coredump also differs depending on the contents of
the string being evaluated\, but it always ends up using the new\_SV\(\) macro\.

Here is one of the stack traces for reference&#8203;:
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
\[\.\.\.\]
Core was generated by \`/home/ks/tmp/perl \-w
/backups/apache\+mod\_ssl/cgi\-bin/phtml'\.
Program terminated with signal 10\, Bus Error\.
\[\.\.\.\]
\#0  0xf6ecc in Perl\_newSV \(len=0\) at sv\.c&#8203;:4561
4561        new\_SV\(sv\);
\(gdb\) bt
\#0  0xf6ecc in Perl\_newSV \(len=0\) at sv\.c&#8203;:4561
\#1  0xd1a28 in Perl\_av\_fetch \(av=0x3994e8\, key=5\, lval=1\) at av\.c&#8203;:236
\#2  0x9218c in Perl\_pad\_alloc \(optype=67\, tmptype=512\) at pad\.c&#8203;:428
\#3  0x7b170 in Perl\_fold\_constants \(o=0x45b800\) at op\.c&#8203;:2048
\#4  0x7ba68 in Perl\_convert \(type=67\, flags=0\, o=0x45b800\) at op\.c&#8203;:2167
\#5  0x717fc in Perl\_yyparse \(\) at perly\.y&#8203;:462
\#6  0x13ee04 in S\_doeval \(gimme=128\, startop=0x0\, outside=0x317780\,
seq=1093\) at pp\_ctl\.c&#8203;:2847
\#7  0x1428ac in Perl\_pp\_entereval \(\) at pp\_ctl\.c&#8203;:3441
\#8  0xb5244 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1449
\#9  0x2b830 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1929
\#10 0x2b08c in perl\_run \(my\_perl=0x1ee4f8\) at perl\.c&#8203;:1853
\#11 0x24dfc in main \(argc=3\, argv=0xffbeec5c\, env=0xffbeec6c\) at
perlmain\.c&#8203;:98
\(gdb\)
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

Here is another stack trace\, produced by a slightly different variant of the
evaluated string&#8203;:
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
\[\.\.\.\]
Core was generated by \`/home/ks/tmp/perl \-w
/backups/apache\+mod\_ssl/cgi\-bin/phtml'\.
Program terminated with signal 10\, Bus Error\.
\[\.\.\.\]
\#0  0xfee44 in Perl\_sv\_mortalcopy \(oldstr=0x1ee4b8\) at sv\.c&#8203;:6767
6767        new\_SV\(sv\);
\(gdb\) bt
\#0  0xfee44 in Perl\_sv\_mortalcopy \(oldstr=0x1ee4b8\) at sv\.c&#8203;:6767
\#1  0x1397f0 in Perl\_pp\_leaveloop \(\) at pp\_ctl\.c&#8203;:1801
\#2  0xb5244 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1449
\#3  0x2cd7c in S\_call\_body \(myop=0xffbee848\, is\_eval=0\) at perl\.c&#8203;:2298
\#4  0x2c1fc in Perl\_call\_sv \(sv=0x5e171c\, flags=64\) at perl\.c&#8203;:2177
\#5  0x2bdec in Perl\_call\_method \(methname=0x1c82b0 "PRINT"\, flags=0\) at
perl\.c&#8203;:2110
\#6  0xd9c30 in Perl\_pp\_print \(\) at pp\_hot\.c&#8203;:580
\#7  0xb5244 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1449
\#8  0x2b830 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1929
\#9  0x2b08c in perl\_run \(my\_perl=0x1ee4f8\) at perl\.c&#8203;:1853
\#10 0x24dfc in main \(argc=3\, argv=0xffbeec5c\, env=0xffbeec6c\) at
perlmain\.c&#8203;:98
\(gdb\)
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

Here is a list of loaded modules by the time the string gets executed&#8203;:
\(print sort keys %INC\)

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
/usr/local/perl\-5\.8\.6\-test/lib/5\.8\.6/sun4\-solaris/auto/POSIX/autosplit\.ix
/usr/local/perl\-5\.8\.6\-test/lib/5\.8\.6/sun4\-solaris/auto/POSIX/load\_imports\.al
AutoLoader\.pm
CGI\.pm
CGI/Util\.pm
Cache/FastMmap\.pm
Cache/FastMmap/CImpl\.pm
Carp\.pm
Config\.pm
DBD/Informix\.pm
DBD/Informix/Defaults\.pm
DBI\.pm
Data/Dumper\.pm
DynaLoader\.pm
Exporter\.pm
Exporter/Heavy\.pm
File/Spec\.pm
File/Spec/Unix\.pm
POSIX\.pm
SKL/CGI\.pm
SKL/DBA\.pm
SKL/PHTML\.pm
Tie/Handle\.pm
URI\.pm
URI/Escape\.pm
WMS/Billing\.pm
WMS/Billing/Account\.pm
WMS/Billing/Client\.pm
WMS/Billing/Permissions\.pm
WMS/Billing/Service\.pm
WMS/Billing/Webint\.pm
XSLoader\.pm
bytes\.pm
constant\.pm
locale\.pm
overload\.pm
strict\.pm
vars\.pm
warnings\.pm
warnings/register\.pm
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

modules\, beginning with 'WMS&#8203;::' and 'SKL&#8203;::' are my own\. They are purely
perl'ish \(no C code\)\.

BTW\, when trying to obtain a list of %INC keys just before evaluating the
problem string I also got perl coredumping with the following stack trace&#8203;:
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
\[\.\.\.\]
Core was generated by \`/home/ks/tmp/perl \-w
/backups/apache\+mod\_ssl/cgi\-bin/phtml'\.
Program terminated with signal 10\, Bus Error\.
\[\.\.\.\]
\#0  0xff4c4 in Perl\_newSVpvn\_share \(src=0x329058 "XSLoader\.pm"\, len=11\,
hash=384126496\) at sv\.c&#8203;:6894
6894        new\_SV\(sv\);
\(gdb\) bt
\#0  0xff4c4 in Perl\_newSVpvn\_share \(src=0x329058 "XSLoader\.pm"\, len=11\,
hash=384126496\) at sv\.c&#8203;:6894
\#1  0xcf9fc in Perl\_hv\_iterkeysv \(entry=0x2fb938\) at hv\.c&#8203;:1867
\#2  0x168810 in Perl\_do\_kv \(\) at doop\.c&#8203;:1405
\#3  0x121750 in Perl\_pp\_keys \(\) at pp\.c&#8203;:3796
\#4  0xb5244 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1449
\#5  0x2b830 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:1929
\#6  0x2b08c in perl\_run \(my\_perl=0x1ee4f8\) at perl\.c&#8203;:1853
\#7  0x24dfc in main \(argc=3\, argv=0xffbeec5c\, env=0xffbeec6c\) at
perlmain\.c&#8203;:98
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-


Please feel free to contact me with any questions\, if there is any
information I can provide you with\.

Best regards\,
Konstantin Solodovnikov\,
JSC "Web Media Servises"\.
ks@&#8203;helios\-net\.ru\.

<details><summary>Perl Info</summary>

```

Flags:
category=core
severity=high

Site configuration information for perl v5.8.6:

Configured by ks at Sat May 14 15:02:16 MSD 2005.

Summary of my perl5 (revision 5 version 8 subversion 6) configuration:
  Platform:
    osname=solaris, osvers=2.8, archname=sun4-solaris
    uname='sunos netra-dev 5.8 generic_108528-19 sun4u sparc sunw,ultraax-i2
'
    config_args='-Dcc=gcc -B/usr/ccs/bin -DDEBUGGING'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef
usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc -B/usr/ccs/bin', ccflags
='-DDEBUGGING -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_S
OURCE -D_FILE_OFFSET_BITS=64',
    optimize='-g',
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe -I/usr/local/include'
    ccversion='', gccversion='3.3.2', gccosandvers='solaris2.8'
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=4321
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t',
lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='gcc -B/usr/ccs/bin', ldflags =' -L/usr/local/lib '
    libpth=/usr/local/lib /usr/lib /usr/ccs/lib
    libs=-lsocket -lnsl -ldl -lm -lc
    perllibs=-lsocket -lnsl -ldl -lm -lc
    libc=/lib/libc.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags=' '
    cccdlflags='-fPIC', lddlflags='-G -L/usr/local/lib'

Locally applied patches:



@INC for perl v5.8.6:
    /usr/local/perl-5.8.6-test/lib/5.8.6/sun4-solaris
    /usr/local/perl-5.8.6-test/lib/5.8.6
    /usr/local/perl-5.8.6-test/lib/site_perl/5.8.6/sun4-solaris
    /usr/local/perl-5.8.6-test/lib/site_perl/5.8.6
    /usr/local/perl-5.8.6-test/lib/site_perl/5.8.5/sun4-solaris
    /usr/local/perl-5.8.6-test/lib/site_perl/5.8.5
    /usr/local/perl-5.8.6-test/lib/site_perl/5.8.0/sun4-solaris
    /usr/local/perl-5.8.6-test/lib/site_perl/5.8.0
    /usr/local/perl-5.8.6-test/lib/site_perl
    .


Environment for perl v5.8.6:
    HOME=/home/ks
    LANG (unset)
    LANGUAGE (unset)
    LC_ALL=ru_RU.KOI8-R

LD_LIBRARY_PATH=/home/informix/ids_9.30.uc1/lib:/home/informix/ids_9.30.uc1/
lib/esql:/home/informix/ids_9.30.uc1/lib/tools:/usr/lib:/usr/local/lib
    LOGDIR (unset)

PATH=/home/informix/ids_9.30.uc1/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/OBSD
ssh/bin:/usr/ccs/bin:/usr/local/bin:/usr/local/sbin:/etc/init.d
    PERL_BADLANG (unset)
    SHELL=/usr/bin/bash


```
</details>

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, May 14\, 2005 at 04&#8203;:45&#8203;:12PM \-0000\, Konstantin Solodovnikov wrote&#8203;:
> Perl crashes \(SIGBUS\) while eval'ing a string\.
> 
> Unfortunately\, it's not very easy to provide a good test case\, because the
> bug reveals in a rather complex case\, involving many preliminary steps\.
> But I will try to describe the situation as completely as possible\.
> 
> My program is a CGI script in perl\, which provides web\-access to a database
> in Informix\.
> The described situation occures after an error happenes in DBD&#8203;::Informix
> module\. The error is\, to be exact\, a syntax error in a prepared SQL
> expression\.

I'm afaid ther's not really a lot we can do about this with a
reproducable test\-case\. My gut feeling is that it's most likely
DBD&#8203;::Informix corrupting something during the syntax error\, then the
later eval errors you see in Perl are just consequences of that\, with the
different permuations of eval strings just sometimes ticking the corruption\.

\-\- 
Never do today what you can put off till tomorrow\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From ks@helios-net.ru



> \-\-\-\-\-Original Message\-\-\-\-\-
> From&#8203;: Dave Mitchell via RT \[mailto&#8203;:perlbug\-followup@&#8203;perl\.org\]
> Sent&#8203;: Tuesday\, May 17\, 2005 4&#8203;:04 AM
> To&#8203;: ks@&#8203;helios\-net\.ru
> Subject&#8203;: Re&#8203;: \[perl \#35449\] Perl dumps core \(SIGBUS\) while eval'ing a
> string
> 
> 
> I'm afaid ther's not really a lot we can do about this with a
> reproducable test\-case\. My gut feeling is that it's most likely
> DBD&#8203;::Informix corrupting something during the syntax error\, then the
> later eval errors you see in Perl are just consequences of that\, with the
> different permuations of eval strings just sometimes ticking the 
> corruption\.

During some additional investigation I also came to a feeling that 
 DBD&#8203;::Informix is \(maybe partly\) responsible for the problem\.
Fortunately\, I succeeded in procucing a simple test case for the problem\.
So\, you can check if your assumption regarding DBD&#8203;::Informix is right\.
See the attached file for the test case code\.
It works slightly different from the way i described in my first letter\.
 SIGBUS comes \*after\* evaluating the string\, but it is still there
 and you may see it with your own eyes\.
It works for me on my solaris8 both under perl 5\.8\.6 and 5\.8\.5 and with both
 DBD&#8203;::Informix 2003\.04 and 2005\.01\.

Best regards\,
Konstantin Solodovnikov\,
JSC "Web Media Servises"\.
ks@&#8203;helios\-net\.ru\.

**Comment by p5pRT** [comment]
### From ks@helios-net.ru

[test.pl](https://rt-archive.perl.org/perl5/Ticket/Attachment/113095/77808/test.pl)

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, May 17\, 2005 at 03&#8203;:23&#8203;:06PM \+0400\, Konstantin Solodovnikov wrote&#8203;:
> During some additional investigation I also came to a feeling that 
>  DBD&#8203;::Informix is \(maybe partly\) responsible for the problem\.
> Fortunately\, I succeeded in procucing a simple test case for the problem\.
> So\, you can check if your assumption regarding DBD&#8203;::Informix is right\.
> See the attached file for the test case code\.
> It works slightly different from the way i described in my first letter\.
>  SIGBUS comes \*after\* evaluating the string\, but it is still there
>  and you may see it with your own eyes\.

Unfortunately I don't have an Informix installation so I can't test this\.
You might want to forward your test script to the relavant address for
reporting bugs in DBD&#8203;::Informix\.

Dave

\-\- 
In my day\, we used to edit the inodes by hand\.  With magnets\.

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'stalled'

**Comment by p5pRT** [comment]
### From @doy

Without a test case that doesn't depend on Informix\, I don't think
there's anything more we can do here\. If nothing more is forthcoming\, I
suggest this ticket be closed\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'stalled' to 'open'

**Comment by p5pRT** [comment]
### From @jkeenan

On Sun Jun 24 14&#8203;:39&#8203;:56 2012\, doy wrote&#8203;:
> Without a test case that doesn't depend on Informix\, I don't think
> there's anything more we can do here\. If nothing more is forthcoming\, I
> suggest this ticket be closed\.

There has been no further correpondence in this RT ticket in nearly
twelve months\.

I am taking it for the purpose of closing it within 7 days unless
someone wishes to take it over\, provide an updated bug report or patch\,
and move the discussion forward\.

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From @jkeenan

On Sun Jun 16 18&#8203;:34&#8203;:22 2013\, jkeenan wrote&#8203;:
> On Sun Jun 24 14&#8203;:39&#8203;:56 2012\, doy wrote&#8203;:
> > Without a test case that doesn't depend on Informix\, I don't think
> > there's anything more we can do here\. If nothing more is forthcoming\, I
> > suggest this ticket be closed\.
> 
> There has been no further correpondence in this RT ticket in nearly
> twelve months\.
> 
> I am taking it for the purpose of closing it within 7 days unless
> someone wishes to take it over\, provide an updated bug report or patch\,
> and move the discussion forward\.
> 

Closing as per schedule\.

**Comment by p5pRT** [comment]
@jkeenan - Status changed from 'open' to 'rejected'
