### ISSUE TITLE
GvHV() can end up pointing at garbage - thread dup bug

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7922]
Migrated from [rt.perl.org#35925](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=35925) (status was 'resolved')

Searchable as RT35925$

**Comment by p5pRT** [comment]
### From @nwc10

#### Created by @nwc10



There is a bug in duping \- GvHV\(\) can end up pointing at garbage\.

If I add this assertion to gv\.c \(\*without\* my recent HV changes\, so this
bug predates them\)&#8203;:

<details><summary>Inline Patch</summary>

```diff
--- gv.c.orig   Sat May 21 04:25:40 2005
+++ gv.c        Sat May 21 13:44:49 2005
@@ -1304,7 +1304,12 @@ Perl_gp_free(pTHX_ GV *gv)

     if (gp->gp_sv) SvREFCNT_dec(gp->gp_sv);
     if (gp->gp_av) SvREFCNT_dec(gp->gp_av);
+    /* FIXME - another reference loop GV -> symtab -> GV ?
+       Somehow gp->gp_hv can end up pointing at freed garbage.  */
     if (gp->gp_hv) {
+       if (SvTYPE(gp->gp_hv) != SVTYPEMASK) {
+           assert(SvTYPE(gp->gp_hv) == SVt_PVHV);
+       }
         if (PL_stashcache && HvNAME(gp->gp_hv))
              hv_delete(PL_stashcache,
                        HvNAME(gp->gp_hv), strlen(HvNAME(gp->gp_hv)),



```
</details>
then various thread-creating tests fail during global destruction:

Failed Test                       Stat Wstat Total Fail  Failed  List of Failed
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
\.\./ext/Storable/t/threads\.t         29  7424     2    0   0\.00%  ??
\.\./ext/threads/shared/t/sv\_refs\.t   29  7424    10    0   0\.00%  ??
\.\./ext/threads/t/end\.t              29  7424     6    0   0\.00%  ??
\.\./ext/threads/t/join\.t             29  7424    14    0   0\.00%  ??
\.\./ext/threads/t/problems\.t         29  7424    10    0   0\.00%  ??
op/getpid\.t                          2   512     3    0   0\.00%  ??

1\.\.3
ok 1 \- thread modules loaded
ok 2 \- pids
ok 3 \- ppids

Breakpoint 1\, Perl\_croak \(my\_perl=0x800200\, pat=0x1ad1c0 "Assertion \(\(gp\->gp\_hv\)\->sv\_flags & 0xff\) == SVt\_PVHV failed&#8203;: file \\"%s\\"\, line %d"\) at util\.c&#8203;:1253
1253        va\_start\(args\, pat\);
\(gdb\) up
\#1  0x00095604 in Perl\_gp\_free \(my\_perl=0x800200\, gv=0x823e74\) at gv\.c&#8203;:1311
1311                assert\(SvTYPE\(gp\->gp\_hv\) == SVt\_PVHV\);
\(gdb\) where
\#0  Perl\_croak \(my\_perl=0x800200\, pat=0x1ad1c0 "Assertion \(\(gp\->gp\_hv\)\->sv\_flags & 0xff\) == SVt\_PVHV failed&#8203;: file \\"%s\\"\, line %d"\) at util\.c&#8203;:1253
\#1  0x00095604 in Perl\_gp\_free \(my\_perl=0x800200\, gv=0x823e74\) at gv\.c&#8203;:1311
\#2  0x00068654 in Perl\_sv\_clear \(my\_perl=0x800200\, sv=0x823e74\) at sv\.c&#8203;:6022
\#3  0x00068e3c in Perl\_sv\_free2 \(my\_perl=0x800200\, sv=0x823e74\) at sv\.c&#8203;:6218
\#4  0x0010ccbc in Perl\_av\_undef \(my\_perl=0x800200\, av=0x823ee0\) at av\.c&#8203;:501
\#5  0x0006850c in Perl\_sv\_clear \(my\_perl=0x800200\, sv=0x823ee0\) at sv\.c&#8203;:6010
\#6  0x00068e3c in Perl\_sv\_free2 \(my\_perl=0x800200\, sv=0x823ee0\) at sv\.c&#8203;:6218
\#7  0x00056edc in do\_clean\_all \(my\_perl=0x800200\, sv=0x823ee0\) at sv\.c&#8203;:489
\#8  0x00056804 in S\_visit \(my\_perl=0x800200\, f=0x56df8 \<do\_clean\_all>\, flags=0\, mask=0\) at sv\.c&#8203;:376
\#9  0x00056f44 in Perl\_sv\_clean\_all \(my\_perl=0x800200\) at sv\.c&#8203;:507
\#10 0x0002dd9c in perl\_destruct \(my\_perl=0x800200\) at perl\.c&#8203;:789
\#11 0x00002be4 in main \(argc=3\, argv=0xbffff70c\, env=0xbffff71c\) at perlmain\.c&#8203;:105
\(gdb\) p \*\(gp\->gp\_hv\)
$1 = \{
&nbsp;  sv\_any = 0x804018\, 
&nbsp;  sv\_refcnt = 2147483646\, 
&nbsp;  sv\_flags = 126287878
\}
\(gdb\) p \*\(gp\->gp\_hv\->sv\_any\)
$2 = \{
&nbsp;  xhv\_array = 0x400190 ""\, 
&nbsp;  xhv\_fill = 0\, 
&nbsp;  xhv\_max = 1\, 
&nbsp;  xhv\_keys = 0\, 
&nbsp;  xnv\_nv = 0\, 
&nbsp;  xmg\_magic = 0x4001a0\, 
&nbsp;  xmg\_stash = 0x1\, 
&nbsp;  xhv\_riter = 2\, 
&nbsp;  xhv\_eiter = 0x1\, 
&nbsp;  xhv\_name = 0x3ff00000 \<Address 0x3ff00000 out of bounds>
\}
\(gdb\) p/x \(gp\->gp\_hv\->sv\_flags\) 
$3 = 0x7870006
\(gdb\) call Perl\_sv\_dump\(my\_perl\, gp\->gp\_hv\)
SV = PVNV\(0x804018\) at 0x800b10
&nbsp;  REFCNT = 2147483646
&nbsp;  FLAGS = \(IOK\,NOK\,POK\,READONLY\,pIOK\,pNOK\,pPOK\)
&nbsp;  IV = 0
&nbsp;  NV = 0
&nbsp;  PV = 0x400190 ""\\0
&nbsp;  CUR = 0
&nbsp;  LEN = 1

Most strange\. It looks like an immortal\, but it's not this perl interpreter's
sv\_yes\, sv\_no or sv\_undef

\(gdb\) p &\(my\_perl\->Isv\_yes\)
$12 = \(SV \*\) 0x800b1c
\(gdb\) p &\(my\_perl\->Isv\_no\)
$13 = \(SV \*\) 0x800b10
\(gdb\) p &\(my\_perl\->Isv\_undef\)
$14 = \(SV \*\) 0x800b04

Thoughts?

Nicholas Clark

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.9.3:

Configured by nick at Sat May 21 12:45:31 BST 2005.

Summary of my perl5 (revision 5 version 9 subversion 3 patch 24525) configuration:
  Platform:
    osname=darwin, osvers=7.9.0, archname=darwin-thread-multi-2level
    uname='darwin ship-in-a-bottle 7.9.0 darwin kernel version 7.9.0: wed mar 30 20:11:17 pst 2005; root:xnuxnu-517.12.7.obj~1release_ppc power macintosh powerpc '
    config_args='-Dusedevel=y -Dcc=ccache gcc -Dld=gcc -Ubincompat5005 -Uinstallusrbinperl -Dcf_email=nick@ccl4.org -Dperladmin=nick@ccl4.org -Dinc_version_list=  -Dinc_version_list_init=0 -Doptimize=-g -Dusethreads=y -Dinstallman1dir=none -Dinstallman3dir=none -de'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='ccache gcc', ccflags ='-fno-common -DPERL_DARWIN -no-cpp-precomp -DDEBUGGING -fno-strict-aliasing -pipe',
    optimize='-g',
    cppflags='-no-cpp-precomp -fno-common -DPERL_DARWIN -no-cpp-precomp -DDEBUGGING -fno-strict-aliasing -pipe'
    ccversion='', gccversion='3.3 20030304 (Apple Computer, Inc. build 1666)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=4321
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=8
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='env MACOSX_DEPLOYMENT_TARGET=10.3 cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib
    libs=-ldbm -ldl -lm -lc
    perllibs=-ldl -lm -lc
    libc=/usr/lib/libc.dylib, so=dylib, useshrplib=false, libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dyld.xs, dlext=bundle, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags=' -bundle -undefined dynamic_lookup -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.9.3:
    lib
    /sw/lib/perl5
    /sw/lib/perl5/darwin
    /usr/local/lib/perl5/5.9.3/darwin-thread-multi-2level
    /usr/local/lib/perl5/5.9.3
    /usr/local/lib/perl5/site_perl/5.9.3/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.9.3
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.9.3:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/nick
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/nick/bin:/sw/bin:/sw/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/sbin:/sbin:/usr/sbin
    PERL5LIB=/sw/lib/perl5:/sw/lib/perl5/darwin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, May 21\, 2005 at 04&#8203;:25&#8203;:10PM \-0000\, Nicholas Clark wrote&#8203;:
> There is a bug in duping \- GvHV\(\) can end up pointing at garbage\.



I can reproduce it with&#8203;:

&nbsp;    our $foo : unique = 'abc';
&nbsp;    use threads;
&nbsp;    threads\->create\(sub \{ 1\} \)\->join\(\);

It seems to be down to the code in S\_gv\_share\(\)\, which at clone time
basically fills all unused slots \(eg gv\_hv\) in the :unique GV with
&PL\_sv\_no from the \*parent\* thread&#8203;:

&nbsp;    /\* attempt to make everything in the typeglob readonly \*/

&nbsp;    STATIC SV \*
&nbsp;    S\_gv\_share\(pTHX\_ SV \*sstr\, CLONE\_PARAMS \*param\)
&nbsp;    \{
&nbsp;    GV \*gv = \(GV\*\)sstr;
&nbsp;    SV \*sv = &param\->proto\_perl\->Isv\_no; /\* just need SvREADONLY\-ness \*/

&nbsp;    \.\.\.

&nbsp;    /\*
&nbsp;     \* write attempts will die with
&nbsp;     \* "Modification of a read\-only value attempted"
&nbsp;     \*/
&nbsp;    if \(\!GvSV\(gv\)\) \{
&nbsp;        GvSV\(gv\) = sv;
&nbsp;    \}

\-\- 
The Enterprise's efficient long\-range scanners detect a temporal vortex
distortion in good time\, allowing it to be safely avoided via a minor
course correction\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#21

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @nwc10

On Sat\, May 21\, 2005 at 07&#8203;:49&#8203;:04PM \+0100\, Dave Mitchell wrote&#8203;:
> On Sat\, May 21\, 2005 at 04&#8203;:25&#8203;:10PM \-0000\, Nicholas Clark wrote&#8203;:
> > There is a bug in duping \- GvHV\(\) can end up pointing at garbage\.
> 
> 
> 
> I can reproduce it with&#8203;:
> 
>     our $foo : unique = 'abc';
>     use threads;
>     threads\->create\(sub \{ 1\} \)\->join\(\);
> 
> It seems to be down to the code in S\_gv\_share\(\)\, which at clone time
> basically fills all unused slots \(eg gv\_hv\) in the :unique GV with
> &PL\_sv\_no from the \*parent\* thread&#8203;:


Surely that logic is pants\, in that&#8203;:

a&#8203;: it should be PL\_sv\_no from the child thread
and
b&#8203;: even PL\_sv\_no is wrong\, because too much other code assumes that GVs
&nbsp;   point to the "correct" type\.

Can a parent thread go away before its child? What happens if a child thread
creates a new unique GV\, spawns a grandchild and then quits? Does this mess
with the assumptions of the :unique implementation?i

Nicholas Clark

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, May 21\, 2005 at 07&#8203;:54&#8203;:09PM \+0100\, Nicholas Clark wrote&#8203;:
> Surely that logic is pants\, in that&#8203;:

correct\.

:unique seems to be a badly\-thought out hack\.

> a&#8203;: it should be PL\_sv\_no from the child thread

that would be an improvement

> b&#8203;: even PL\_sv\_no is wrong\, because too much other code assumes that GVs
>    point to the "correct" type\.

yep\.

> Can a parent thread go away before its child?

Yep\.

>What happens if a child thread
> creates a new unique GV\, spawns a grandchild and then quits? Does this mess
> with the assumptions of the :unique implementation?i

I think "pants" sums it all up very well\.

\-\- 
"Emacs isn't a bad OS once you get used to it\.
It just lacks a decent editor\."

**Comment by p5pRT** [comment]
### From @nwc10

On Sat\, May 21\, 2005 at 08&#8203;:06&#8203;:22PM \+0100\, Dave Mitchell wrote&#8203;:
> On Sat\, May 21\, 2005 at 07&#8203;:54&#8203;:09PM \+0100\, Nicholas Clark wrote&#8203;:
> > Surely that logic is pants\, in that&#8203;:
> 
> correct\.
> 
> :unique seems to be a badly\-thought out hack\.
> 
> > a&#8203;: it should be PL\_sv\_no from the child thread
> 
> that would be an improvement
> 
> > b&#8203;: even PL\_sv\_no is wrong\, because too much other code assumes that GVs
> >    point to the "correct" type\.
> 
> yep\.

So a better fix would be to have a real collection of read\-only scalars of
the correct types to populate the GV with at clone time?

> > Can a parent thread go away before its child?
> 
> Yep\.
> 
> >What happens if a child thread
> > creates a new unique GV\, spawns a grandchild and then quits? Does this mess
> > with the assumptions of the :unique implementation?i

So presumably at clone time\, when the unique kicks in and makes things read
only\, the child perl should gain and own a reference on the parent which
prevents the parent thread from clearing up/entering global destruction?
And presumably also gain a reference on the parent typeglob\, so that that
can't disappear prior to the parent thread's exit due to any part of the
parent thread doing SvREFCNT\_dec\(\) once for each \(current\) reference in the
parent thread?

Nicholas Clark

**Comment by p5pRT** [comment]
### From @nwc10

On Sat\, May 21\, 2005 at 08&#8203;:06&#8203;:22PM \+0100\, Dave Mitchell wrote&#8203;:
> On Sat\, May 21\, 2005 at 07&#8203;:54&#8203;:09PM \+0100\, Nicholas Clark wrote&#8203;:
> > Surely that logic is pants\, in that&#8203;:
> 
> correct\.
> 
> :unique seems to be a badly\-thought out hack\.

> >What happens if a child thread
> > creates a new unique GV\, spawns a grandchild and then quits? Does this mess
> > with the assumptions of the :unique implementation?i
> 
> I think "pants" sums it all up very well\.

I'm not sure\. "pants" doesn't have enough expletives in it\.
It's going to get fixed\, or it's heading to /dev/null

\(and it looks like I'm going to be the one fixing it\, because the breakage
it causes it getting in the way of me doing other stuff\)

Nicholas Clark

**Comment by p5pRT** [comment]
### From @cpansprout

On Sat May 21 09&#8203;:25&#8203;:10 2005\, nicholas wrote&#8203;:
> There is a bug in duping \- GvHV\(\) can end up pointing at garbage\.
> 
> If I add this assertion to gv\.c \(\*without\* my recent HV changes\, so
>    this
> bug predates them\)&#8203;:
> 
> \-\-\- gv\.c\.orig   Sat May 21 04&#8203;:25&#8203;:40 2005
> \+\+\+ gv\.c        Sat May 21 13&#8203;:44&#8203;:49 2005
> @&#8203;@&#8203; \-1304\,7 \+1304\,12 @&#8203;@&#8203; Perl\_gp\_free\(pTHX\_ GV \*gv\)
> 
>      if \(gp\->gp\_sv\) SvREFCNT\_dec\(gp\->gp\_sv\);
>      if \(gp\->gp\_av\) SvREFCNT\_dec\(gp\->gp\_av\);
> \+    /\* FIXME \- another reference loop GV \-> symtab \-> GV ?
> \+       Somehow gp\->gp\_hv can end up pointing at freed garbage\.  \*/
>      if \(gp\->gp\_hv\) \{
> \+       if \(SvTYPE\(gp\->gp\_hv\) \!= SVTYPEMASK\) \{
> \+           assert\(SvTYPE\(gp\->gp\_hv\) == SVt\_PVHV\);
> \+       \}
>          if \(PL\_stashcache && HvNAME\(gp\->gp\_hv\)\)
>               hv\_delete\(PL\_stashcache\,
>                         HvNAME\(gp\->gp\_hv\)\, strlen\(HvNAME\(gp\->gp\_hv\)\)\,
> 
> 
> then various thread\-creating tests fail during global destruction&#8203;:

Since :unique has been made a no\-op\, this can’t happen any more\, so I’m
marking this as resolved\. If I’m wrong\, somebody please re\-open it\.

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'
