### ISSUE TITLE
Deep recursion on subroutine "CGI::Carp::warn"

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8015]
Migrated from [rt.perl.org#36521](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=36521) (status was 'resolved')

Searchable as RT36521$

**Comment by p5pRT** [comment]
### From dmuell@gmx.net


This is a bug report for perl from dmuell@&#8203;gmx\.net\,
generated with the help of perlbug 1\.35 running under perl v5\.8\.6\.




---
running this test application crashes perl 5\.8\.6 or newer \(5\.8\.5 and
older works fine\)&#8203;: 

=== Cut ===
\#\!/usr/bin/perl

use CGI&#8203;::Carp qw\(fatalsToBrowser\);
use diagnostics;

warn "foo";
=== Cut ===

output is a lot of garbage\, and then&#8203;: 

Deep recursion on subroutine "CGI&#8203;::Carp&#8203;::warn" at /usr/lib/perl5/5\.8\.6/diagnostics\.pm line 506\.
Segmentation fault \(core dumped\)




---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=high


---
This perlbug was built using Perl v5\.8\.6 \- Fri Jun 24 16&#8203;:05&#8203;:45 UTC 2005
It is being executed now by  Perl v5\.8\.6 \- Fri Jun 24 16&#8203;:00&#8203;:32 UTC 2005\.

Site configuration information for perl v5\.8\.6&#8203;:

Configured by abuild at Fri Jun 24 16&#8203;:00&#8203;:32 UTC 2005\.

Summary of my perl5 \(revision 5 version 8 subversion 6\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.12\, archname=i586\-linux\-thread\-multi
&nbsp;    uname='linux salieri 2\.6\.12 \#1 smp tue jun 21 14&#8203;:03&#8203;:10 utc 2005 i686 athlon i386 gnulinux '
&nbsp;    config\_args='\-ds \-e \-Dprefix=/usr \-Dvendorprefix=/usr \-Dinstallusrbinperl \-Dusethreads \-Di\_db \-Di\_dbm \-Di\_ndbm \-Di\_gdbm \-Duseshrplib=true \-Doptimize=\-O2 \-march=i586 \-mtune=i686 \-fmessage\-length=0 \-Wall \-D\_FORTIFY\_SOURCE=2 \-g \-Wall \-pipe'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2 \-march=i586 \-mtune=i686 \-fmessage\-length=0 \-Wall \-D\_FORTIFY\_SOURCE=2 \-g \-Wall \-pipe'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBUGGING \-fno\-strict\-aliasing \-pipe'
&nbsp;    ccversion=''\, gccversion='4\.0\.1 20050621 \(prerelease\) \(SUSE Linux\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =''
&nbsp;    libpth=/lib /usr/lib /usr/local/lib
&nbsp;    libs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    libc=\, so=so\, useshrplib=true\, libperl=libperl\.so
&nbsp;    gnulibc\_version='2\.3\.5'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E \-Wl\,\-rpath\,/usr/lib/perl5/5\.8\.6/i586\-linux\-thread\-multi/CORE'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl v5\.8\.6&#8203;:
&nbsp;    /usr/lib/perl5/5\.8\.6/i586\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/5\.8\.6
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.6/i586\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.6
&nbsp;    /usr/lib/perl5/site\_perl
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.6/i586\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.6
&nbsp;    /usr/lib/perl5/vendor\_perl
&nbsp;    \.



---
Environment for perl v5\.8\.6&#8203;:
&nbsp;    HOME=/home/dirk
&nbsp;    LANG=en\_US\.UTF\-8
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/opt/gcc/bin&#8203;:/home/dirk/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/usr/X11R6/bin&#8203;:/bin&#8203;:/usr/games&#8203;:/opt/gnome/bin&#8203;:/opt/kde3/bin&#8203;:/opt/kde/bin&#8203;:/usr/lib/jvm/jre/bin&#8203;:/usr/lib/mit/bin&#8203;:/usr/lib/mit/sbin&#8203;:/opt/kde/bin&#8203;:/home/dirk/src/kde/qt/bin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From dmuell@gmx.net

On Wednesday 13 July 2005 00&#8203;:11\, perlbug\-followup@&#8203;perl\.org wrote&#8203;:

>   perlbug\-followup@&#8203;perl\.org

And this patch fixes it&#8203;: 

\-\-\- lib/diagnostics\.pm
\+\+\+ lib/diagnostics\.pm
@&#8203;@&#8203; \-503\,7 \+503\,7 @&#8203;@&#8203;
&nbsp;            print STDERR $warning;
&nbsp;        \}
&nbsp;     \} 
\-    goto &$oldwarn if defined $oldwarn and $oldwarn and $oldwarn ne 
\\&warn\_trap;
\+    &$oldwarn if defined $oldwarn and $oldwarn and $oldwarn ne \\&warn\_trap;
 \};
 
 sub death\_trap \{



Dirk

**Comment by p5pRT** [comment]
### From @schwern

On Tue\, Jul 12\, 2005 at 03&#8203;:11&#8203;:49PM \-0700\, dmuell @&#8203; gmx\. net wrote&#8203;:
> === Cut ===
> \#\!/usr/bin/perl
> 
> use CGI&#8203;::Carp qw\(fatalsToBrowser\);
> use diagnostics;
> 
> warn "foo";
> === Cut ===
> 
> output is a lot of garbage\, and then&#8203;: 
> 
> Deep recursion on subroutine "CGI&#8203;::Carp&#8203;::warn" at /usr/lib/perl5/5\.8\.6/diagnostics\.pm line 506\.
> Segmentation fault \(core dumped\)

Deep recursion on subroutine "CGI&#8203;::Carp&#8203;::warn" at /usr/local/perl/bleadperl/lib/5\.9\.3/diagnostics\.pm line 506\.

Program received signal EXC\_BAD\_ACCESS\, Could not access memory\.
0x000bec6c in Perl\_pad\_push \(\)
\(gdb\) bt
\#0  0x000bec6c in Perl\_pad\_push \(\)
\#1  0x0007b620 in Perl\_pp\_goto \(\)
\#2  0x000d1e5c in Perl\_runops\_standard \(\)
\#3  0x0001e964 in Perl\_call\_sv \(\)
\#4  0x00005e68 in Perl\_vwarn \(\)
\#5  0x000062b8 in Perl\_vwarner \(\)
\#6  0x00006078 in Perl\_warner \(\)
\#7  0x0007b60c in Perl\_pp\_goto \(\)
\#8  0x000d1e5c in Perl\_runops\_standard \(\)
\#9  0x0001e964 in Perl\_call\_sv \(\)
\#10 0x00005e68 in Perl\_vwarn \(\)
\#11 0x00005fe8 in Perl\_warn \(\)
\#12 0x00067324 in Perl\_pp\_warn \(\)
\#13 0x000d1e5c in Perl\_runops\_standard \(\)
\#14 0x0001e964 in Perl\_call\_sv \(\)
\#15 0x00005e68 in Perl\_vwarn \(\)
\#16 0x00005fe8 in Perl\_warn \(\)
\#17 0x00067324 in Perl\_pp\_warn \(\)
\#18 0x000d1e5c in Perl\_runops\_standard \(\)
\#19 0x0001e964 in Perl\_call\_sv \(\)
\#20 0x00005e68 in Perl\_vwarn \(\)
\#21 0x00005fe8 in Perl\_warn \(\)
\#22 0x00067324 in Perl\_pp\_warn \(\)
\#23 0x000d1e5c in Perl\_runops\_standard \(\)
\.\.\.and so on until\.\.\.
\#503 0x000d1e5c in Perl\_runops\_standard \(\)
\#504 0x0001e964 in Perl\_call\_sv \(\)
\#505 0x00005e68 in Perl\_vwarn \(\)
\#506 0x00005fe8 in Perl\_warn \(\)
\#507 0x00067324 in Perl\_pp\_warn \(\)
\#508 0x000d1e5c in Perl\_runops\_standard \(\)
\#509 0x0001e394 in S\_run\_body \(\)
\#510 0x0001dff4 in perl\_run \(\)
\#511 0x00002d60 in main \(\)
\#512 0x00002780 in \_start \(argc=2\, argv=0x0\, envp=0xec09c\) at /SourceCache/Csu/Csu\-47/crt\.c&#8203;:267
\#513 0x8fe1a278 in \_\_dyld\_\_dyld\_start \(\)




\-\- 
Michael G Schwern     schwern@&#8203;pobox\.com     http&#8203;://www\.pobox\.com/~schwern
Ahh email\, my old friend\.  Do you know that revenge is a dish that is best 
served cold?  And it is very cold on the Internet\!

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @schwern

On Wed\, Jul 13\, 2005 at 03&#8203;:51&#8203;:38AM \+0200\, Dirk Mueller wrote&#8203;:
> And this patch fixes it&#8203;: 
>
> \-\-\- lib/diagnostics\.pm
> \+\+\+ lib/diagnostics\.pm
> @&#8203;@&#8203; \-503\,7 \+503\,7 @&#8203;@&#8203;
>             print STDERR $warning;
>         \}
>      \} 
> \-    goto &$oldwarn if defined $oldwarn and $oldwarn and $oldwarn ne 
> \\&warn\_trap;
> \+    &$oldwarn if defined $oldwarn and $oldwarn and $oldwarn ne \\&warn\_trap;
>  \};
>  
>  sub death\_trap \{

No\, that goto is important\.  It ensures the old warning handler is called
in the same caller context as when diagnostics\.pm is not there\.

&nbsp;  \#\!/usr/bin/perl \-w

&nbsp;  BEGIN \{ $SIG\{\_\_WARN\_\_\} = sub \{ print join "\\n"\, caller\, @&#8203;\_ \} \}
&nbsp;  use diagnostics;

&nbsp;  warn "foo";

If you run that with and without "use diagnostics" the output from the
\_\_WARN\_\_ handler should be the same\, it should think its called from line
6\.  With your patch it thinks its called from inside diagnostics\.pm\.

The problem is the use of goto &foo inside a \_\_WARN\_\_ when &foo also calls
warn\(\)\.  I suspect whatever magic that keeps warn\(\) from calling 
$SIG\{\_\_WARN\_\_\} when its already inside one is lost\.

&nbsp;  \#\!/sw/bin/perl \-w

&nbsp;  my $warn = sub \{ warn\(join "\\n"\, caller\, @&#8203;\_\) \};

&nbsp;  $SIG\{\_\_WARN\_\_\} = sub \{
&nbsp;      \# &$warn;      \# this is ok
&nbsp;      goto &$warn;   \# this segfaults
&nbsp;  \};

&nbsp;  warn "foo";


\-\- 
Michael G Schwern     schwern@&#8203;pobox\.com     http&#8203;://www\.pobox\.com/~schwern
Reality is that which\, when you stop believing in it\, doesn't go away\.
&nbsp;    \-\- Phillip K\. Dick

**Comment by p5pRT** [comment]
### From @iabyn

On Wed\, Jul 13\, 2005 at 01&#8203;:40&#8203;:03PM \-0700\, Michael G Schwern wrote&#8203;:
> The problem is the use of goto &foo inside a \_\_WARN\_\_ when &foo also calls
> warn\(\)\.  I suspect whatever magic that keeps warn\(\) from calling 
> $SIG\{\_\_WARN\_\_\} when its already inside one is lost\.
> 
>   \#\!/sw/bin/perl \-w
> 
>   my $warn = sub \{ warn\(join "\\n"\, caller\, @&#8203;\_\) \};
> 
>   $SIG\{\_\_WARN\_\_\} = sub \{
>       \# &$warn;      \# this is ok
>       goto &$warn;   \# this segfaults
>   \};
> 
>   warn "foo";

the disabling of $SIG\{\_\_WARN\_\_\} was done by cheking the call depth of the
associated sub\. The goto &foo ensured that this was always at zero\.

The change below fixes this by localsised PL\_warnhook t6o zero within a
call to a warn hook\.

\-\- 
Britain\, Britain\, Britain\! Discovered by Sir Henry Britain in
sixteen\-oh\-ten\. Sold to Germany a year later for a pfennig and the promise
of a kiss\. Destroyed in eighteen thirty\-fourty two\, and rebuilt a week
later by a man\. This we know\. Hello\. But what of the people of Britain?
Who they? What do? And why?   \-\- Little Britain


Change 25160 by davem@&#8203;davem\-splatty on 2005/07/17 20&#8203;:12&#8203;:54

&nbsp;    $SIG\{\_\_WARN\_\_\} = sub \{ goto &foo \} could recurse infinitely

Affected files \.\.\.

\.\.\. //depot/perl/t/op/goto\.t\#30 edit
\.\.\. //depot/perl/util\.c\#484 edit

Differences \.\.\.

==== //depot/perl/t/op/goto\.t\#30 \(xtext\) ====

@&#8203;@&#8203; \-10\,7 \+10\,7 @&#8203;@&#8203;
 
 use warnings;
 use strict;
\-plan tests => 56;
\+plan tests => 57;
 
 our $foo;
 while \($?\) \{
@&#8203;@&#8203; \-436\,3 \+436\,13 @&#8203;@&#8203;
 like\($@&#8203;\, qr/Can't goto subroutine from an eval\-string/\, 'eval string'\);
 eval \{ goto &null \};
 like\($@&#8203;\, qr/Can't goto subroutine from an eval\-block/\, 'eval block'\);
\+
\+\# \[perl \#36521\] goto &foo in warn handler could defeat recursion avoider
\+
\+\{
\+    my $r = runperl\(
\+        stderr => 1\,
\+        prog => 'my $d; my $w = sub \{ return if $d\+\+; warn q\(bar\)\}; local $SIG\{\_\_WARN\_\_\} = sub \{ goto &$w; \}; warn q\(foo\);'
\+    \);
\+    like\($r\, qr/bar/\, "goto &foo in warn"\);
\+\}

==== //depot/perl/util\.c\#484 \(text\) ====

@&#8203;@&#8203; \-1278\,6 \+1278\,8 @&#8203;@&#8203;
&nbsp;         SV \*msg;
 
&nbsp;         ENTER;
\+        SAVESPTR\(PL\_warnhook\);
\+        PL\_warnhook = Nullsv;
&nbsp;         save\_re\_context\(\);
&nbsp;         msg = newSVpvn\(message\, msglen\);
&nbsp;         SvFLAGS\(msg\) |= utf8;

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @schwern

> \[davem@&#8203;iabyn\.com \- Sun Jul 17 13&#8203;:42&#8203;:34 2005\]&#8203;:
> 
> On Wed\, Jul 13\, 2005 at 01&#8203;:40&#8203;:03PM \-0700\, Michael G Schwern wrote&#8203;:
> > The problem is the use of goto &foo inside a \_\_WARN\_\_ when &foo also
calls
> > warn\(\)\.  I suspect whatever magic that keeps warn\(\) from calling 
> > $SIG\{\_\_WARN\_\_\} when its already inside one is lost\.
> > 
> >   \#\!/sw/bin/perl \-w
> > 
> >   my $warn = sub \{ warn\(join "\\n"\, caller\, @&#8203;\_\) \};
> > 
> >   $SIG\{\_\_WARN\_\_\} = sub \{
> >       \# &$warn;      \# this is ok
> >       goto &$warn;   \# this segfaults
> >   \};
> > 
> >   warn "foo";
> 
> the disabling of $SIG\{\_\_WARN\_\_\} was done by cheking the call depth of the
> associated sub\. The goto &foo ensured that this was always at zero\.
> 
> The change below fixes this by localsised PL\_warnhook t6o zero within a
> call to a warn hook\.
> 
> 
>

**Comment by p5pRT** [comment]
@schwern - Status changed from 'resolved' to 'open'

**Comment by p5pRT** [comment]
### From @schwern

On Sun\, Jul 17\, 2005 at 09&#8203;:41&#8203;:58PM \+0100\, Dave Mitchell wrote&#8203;:
> \+\# \[perl \#36521\] goto &foo in warn handler could defeat recursion avoider
> \+
> \+\{
> \+    my $r = runperl\(
> \+        stderr => 1\,
> \+        prog => 'my $d; my $w = sub \{ return if $d\+\+; warn q\(bar\)\}; local $SIG\{\_\_WARN\_\_\} = sub \{ goto &$w; \}; warn q\(foo\);'
> \+    \);
> \+    like\($r\, qr/bar/\, "goto &foo in warn"\);

This program does not segfault\, it does nothing\.

0 ~$ perl5\.8\.6 \-wle 'my $d; my $w = sub \{ return if $d\+\+; warn q\(bar\)\}; local $SIG\{\_\_WARN\_\_\} = sub \{ goto &$w; \}; warn q\(foo\);'
0 ~$ 

I think the problem is you have code to deliberately avoid the recursion in
the subroutine\.  "return if $d\+\+"\.  Get rid of that and it segfaults\.

0 ~$ perl5\.8\.6 \-wle 'my $d; my $w = sub \{ warn @&#8203;\_\}; $SIG\{\_\_WARN\_\_\} = sub \{ goto &$w; \}; warn q\(foo\);'
Bus error
0 ~$ 


\-\- 
Michael G Schwern     schwern@&#8203;pobox\.com     http&#8203;://www\.pobox\.com/~schwern
Don't try the paranormal until you know what's normal\.
&nbsp;    \-\- "Lords and Ladies" by Terry Prachett

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Jul 17\, 2005 at 02&#8203;:27&#8203;:35PM \-0700\, Michael G Schwern wrote&#8203;:
> On Sun\, Jul 17\, 2005 at 09&#8203;:41&#8203;:58PM \+0100\, Dave Mitchell wrote&#8203;:
> > \+\# \[perl \#36521\] goto &foo in warn handler could defeat recursion avoider
> > \+
> > \+\{
> > \+    my $r = runperl\(
> > \+        stderr => 1\,
> > \+        prog => 'my $d; my $w = sub \{ return if $d\+\+; warn q\(bar\)\}; local $SIG\{\_\_WARN\_\_\} = sub \{ goto &$w; \}; warn q\(foo\);'
> > \+    \);
> > \+    like\($r\, qr/bar/\, "goto &foo in warn"\);
> 
> This program does not segfault\, it does nothing\.
> 
> 0 ~$ perl5\.8\.6 \-wle 'my $d; my $w = sub \{ return if $d\+\+; warn q\(bar\)\}; local $SIG\{\_\_WARN\_\_\} = sub \{ goto &$w; \}; warn q\(foo\);'
> 0 ~$ 

That's the idea\. In fixed bleed\, it prints a warning&#8203;:

$ \./perl \-wle 'my $d; my $w = sub \{ return if $d\+\+; warn q\(bar\)\}; local $SIG\{\_\_WARN\_\_\} = sub \{ goto &$w; \}; warn q\(foo\);'
bar at \-e line 1\.
$

The test minimally detects bad behaviour while avoiding runaway recursion
and segfault\.




\-\- 
"Emacs isn't a bad OS once you get used to it\.
It just lacks a decent editor\."

**Comment by p5pRT** [comment]
### From @schwern

On Mon\, Jul 18\, 2005 at 12&#8203;:07&#8203;:23AM \+0100\, Dave Mitchell wrote&#8203;:
> > > \+\{
> > > \+    my $r = runperl\(
> > > \+        stderr => 1\,
> > > \+        prog => 'my $d; my $w = sub \{ return if $d\+\+; warn q\(bar\)\}; local $SIG\{\_\_WARN\_\_\} = sub \{ goto &$w; \}; warn q\(foo\);'
> > > \+    \);
> > > \+    like\($r\, qr/bar/\, "goto &foo in warn"\);
> > 
> > This program does not segfault\, it does nothing\.
> > 
> > 0 ~$ perl5\.8\.6 \-wle 'my $d; my $w = sub \{ return if $d\+\+; warn q\(bar\)\}; local $SIG\{\_\_WARN\_\_\} = sub \{ goto &$w; \}; warn q\(foo\);'
> > 0 ~$ 
> 
> That's the idea\. In fixed bleed\, it prints a warning&#8203;:
> 
> $ \./perl \-wle 'my $d; my $w = sub \{ return if $d\+\+; warn q\(bar\)\}; local $SIG\{\_\_WARN\_\_\} = sub \{ goto &$w; \}; warn q\(foo\);'
> bar at \-e line 1\.
> $
> 
> The test minimally detects bad behaviour while avoiding runaway recursion
> and segfault\.

But with runperl\(\) its ok to segfault\, its run in a different process\.  You
can even reduce it using fresh\_perl\_like\(\)\.

fresh\_perl\_like\(\<\<'CODE'\, qr/bar/\);
&nbsp;  my $w = sub \{ warn q\(bar\) \}; local $SIG\{\_\_WARN\_\_\} = sub \{ goto &$w; \}; warn q\(foo\);
CODE


\-\- 
Michael G Schwern     schwern@&#8203;pobox\.com     http&#8203;://www\.pobox\.com/~schwern
Insulting our readers is part of our business model\.
&nbsp;        http&#8203;://somethingpositive\.net/sp07122005\.shtml

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Jul 17\, 2005 at 04&#8203;:25&#8203;:19PM \-0700\, Michael G Schwern wrote&#8203;:
> On Mon\, Jul 18\, 2005 at 12&#8203;:07&#8203;:23AM \+0100\, Dave Mitchell wrote&#8203;:
> But with runperl\(\) its ok to segfault\, its run in a different process\.

I know\. Orignally I was trying to write the test to run in the same process
\(thus the need to avoid segfault\)\, but couldn't get round the fact that
when working correctly\, it needed to write to STDERR\, which is why I then
bunged it in a freshperl\.

> You can even reduce it using fresh\_perl\_like\(\)\.

Ooh\, I'll try to remember that in future\.

\-\- 
SCO \- a train crash in slow motion

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
