### ISSUE TITLE
Syntax error crashing perl-5.8.6

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8082]
Migrated from [rt.perl.org#36969](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=36969) (status was 'resolved')

Searchable as RT36969$

**Comment by p5pRT** [comment]
### From lace@jankratochvil.net

#### Created by lace@jankratochvil.net



Source w/syntax error causes crash of Perl\.

Unfortunately unable to minimize some reproducible case\. It occurs in mod\_perl
environment\. Prepared reproducibility binary kit \(Fedora Core 4 based\)&#8203;:
&nbsp;    http&#8203;://www\.jankratochvil\.net/priv/perl\-semicolon\-crash\-2005082100\-chrooted\.tar\.gz

Everything contained inside\, reproducible by&#8203;:
&nbsp;    chroot /tmp/chrooted/ /usr/sbin/httpd \-d /home/lace/www/engine/etc/httpd \-DPERL \-X

Tried also perl\-5\.8\.7 \(ported myself\) and it still crashes\. All the binaries
tried only in their Fedora Core 4 variants\.

Source fix to avoid this bug&#8203;:
<details><summary>Inline Patch</summary>

```diff
--- home/lace/www/www.jankratochvil.net/project/captive/CVS.pm-orig	2005-08-21 11:00:52.058785000 +0900
+++ home/lace/www/www.jankratochvil.net/project/captive/CVS.pm	2005-08-21 11:01:02.607094776 +0900
@@ -99,7 +99,7 @@
 						.'<hr />requirement: '
 						.a_href('http://linux-ntfs.sourceforge.net/downloads.html#downloads','ntfsprogs')
 						.' '.$format.' &ge; 1.8.0'
-					.'</td></tr></table>';
+					.'</td></tr></table>'
 				.'</td></tr></table>';
 	};
 


```
</details>
Extracted relevant part from gdb(1):

\#0  Perl\_pad\_free \(my\_perl=0x8390f10\, po=29\) at pad\.c&#8203;:1171
1171        SvPADTMP\_off\(PL\_curpad\[po\]\);
\(gdb\) bt
\#0  Perl\_pad\_free \(my\_perl=0x8390f10\, po=29\) at pad\.c&#8203;:1171
\#1  0x00e1fafa in Perl\_op\_clear \(my\_perl=0x8390f10\, o=0x8878480\) at op\.c&#8203;:516
\#2  0x00e1fe49 in Perl\_op\_free \(my\_perl=0x8390f10\, o=0x8878480\) at op\.c&#8203;:380
\#3  0x00e1fe04 in Perl\_op\_free \(my\_perl=0x8390f10\, o=0x88784a8\) at op\.c&#8203;:368
\#4  0x00e1fe04 in Perl\_op\_free \(my\_perl=0x8390f10\, o=0x88a7ac8\) at op\.c&#8203;:368
\#5  0x00e1fe04 in Perl\_op\_free \(my\_perl=0x8390f10\, o=0x88a7b10\) at op\.c&#8203;:368
\#6  0x00e1fe04 in Perl\_op\_free \(my\_perl=0x8390f10\, o=0x88a7aa0\) at op\.c&#8203;:368
\#7  0x00e2daff in Perl\_newATTRSUB \(my\_perl=0x8390f10\, floor=293\, o=0x88a74a0\, proto=0x0\, attrs=0x0\, block=0x88a7aa0\)
&nbsp;    at op\.c&#8203;:4376
\#8  0x00e1d536 in Perl\_yyparse \(my\_perl=0x8390f10\) at perly\.y&#8203;:355
\#9  0x00e95628 in S\_doeval \(my\_perl=0x8390f10\, gimme=0\, startop=0x0\, outside=0x0\, seq=137958892\) at pp\_ctl\.c&#8203;:2847
\#10 0x00e9c277 in Perl\_pp\_require \(my\_perl=0x8390f10\) at pp\_ctl\.c&#8203;:3344
\#11 0x003e5026 in modperl\_perl\_global\_request\_restore \(\) from /home/lace/www/engine/etc/httpd/modules/mod\_perl\.so
\#12 0x00e436e1 in Perl\_runops\_debug \(my\_perl=0x8390f10\) at dump\.c&#8203;:1449
\#13 0x00df0b9e in S\_call\_body \(my\_perl=0x8390f10\, myop=0x19\, is\_eval=58\) at perl\.c&#8203;:2299
\#14 0x00df3c73 in Perl\_eval\_sv \(my\_perl=0x8390f10\, sv=0x83a37a0\, flags=2\) at perl\.c&#8203;:2363
\#15 0x003db8f8 in modperl\_require\_module \(\) from /home/lace/www/engine/etc/httpd/modules/mod\_perl\.so
\#16 0x003d6d0d in modperl\_cmd\_modules \(\) from /home/lace/www/engine/etc/httpd/modules/mod\_perl\.so
\#17 0x00d52e02 in ap\_add\_named\_module \(\) from /usr/sbin/httpd
\#18 0x00d532f9 in ap\_walk\_config \(\) from /usr/sbin/httpd
\#19 0x00d53839 in ap\_process\_config\_tree \(\) from /usr/sbin/httpd
\#20 0x00d5766b in main \(\) from /usr/sbin/httpd
\(gdb\) p my\_perl\->Tcurpad\[po\]
$1 = \(SV \*\) 0x19
\(gdb\) up
\#1  0x00e1fafa in Perl\_op\_clear \(my\_perl=0x8390f10\, o=0x8878480\) at op\.c&#8203;:516
516        pad\_free\(o\->op\_targ\);
\(gdb\) p \*o
$2 = \{op\_next = 0x8878460\, op\_sibling = 0x8878460\, op\_ppaddr = 0xe5a962 \<Perl\_pp\_concat>\, op\_targ = 29\, op\_type = 66\, 
&nbsp;  op\_seq = 0\, op\_flags = 70 'F'\, op\_private = 2 '\\002'\}
\(gdb\) p \*o\->op\_next
$3 = \{op\_next = 0x88784a8\, op\_sibling = 0x0\, op\_ppaddr = 0xe5a3c0 \<Perl\_pp\_const>\, op\_targ = 0\, op\_type = 5\, op\_seq = 0\, 
&nbsp;  op\_flags = 2 '\\002'\, op\_private = 0 '\\0'\}

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

This perlbug was built using Perl v5.8.6 in the Red Hat build system.
It is being executed now by Perl v5.8.6 - Wed May 18 18:20:12 EDT 2005.

Site configuration information for perl v5.8.6:

Configured by Red Hat, Inc. at Wed May 18 18:20:12 EDT 2005.

Summary of my perl5 (revision 5 version 8 subversion 6) configuration:
  Platform:
    osname=linux, osvers=2.4.21-27.0.2.elsmp, archname=i386-linux-thread-multi
    uname='linux decompose.build.redhat.com 2.4.21-27.0.2.elsmp #1 smp wed jan 12 23:35:44 est 2005 i686 i686 i386 gnulinux '
    config_args='-des -Doptimize=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -m32 -march=i386 -mtune=pentium4 -fasynchronous-unwind-tables -Dversion=5.8.6 -Dmyhostname=localhost -Dperladmin=root@localhost -Dcc=gcc -Dcf_by=Red Hat, Inc. -Dinstallprefix=/usr -Dprefix=/usr -Darchname=i386-linux -Dvendorprefix=/usr -Dsiteprefix=/usr -Duseshrplib -Dusethreads -Duseithreads -Duselargefiles -Dd_dosuid -Dd_semctl_semun -Di_db -Ui_ndbm -Di_gdbm -Di_shadow -Di_syslog -Dman3ext=3pm -Duseperlio -Dinstallusrbinperl=n -Ubincompat5005 -Uversiononly -Dpager=/usr/bin/less -isr -Dd_gethostent_r_proto -Ud_endhostent_r_proto -Ud_endprotoent_r_proto -Ud_endservent_r_proto -Ud_sethostent_r_proto -Ud_setprotoent_r_proto -Ud_setservent_r_proto -Dinc_version_list=5.8.5 5.8.4 5.8.3'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DDEBUGGING -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm',
    optimize='-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -m32 -march=i386 -mtune=pentium4 -fasynchronous-unwind-tables',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DDEBUGGING -fno-strict-aliasing -pipe -I/usr/local/include -I/usr/include/gdbm'
    ccversion='', gccversion='4.0.0 20050516 (Red Hat 4.0.0-6)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lresolv -lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lpthread -lc
    perllibs=-lresolv -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
    libc=/lib/libc-2.3.5.so, so=so, useshrplib=true, libperl=libperl.so
    gnulibc_version='2.3.5'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E -Wl,-rpath,/usr/lib/perl5/5.8.6/i386-linux-thread-multi/CORE'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.6:
    /home/lace/lib/perl/site_perl/5.8.6/i386-linux-thread-multi
    /home/lace/lib/perl/site_perl/5.8.6
    /home/lace/lib/perl/site_perl/i386-linux-thread-multi
    /home/lace/lib/perl/site_perl
    /home/lace/lib/perl/5.8.6/i386-linux-thread-multi
    /home/lace/lib/perl/5.8.6
    /home/lace/lib/perl/i386-linux-thread-multi
    /home/lace/lib/perl
    /home/lace/share/perl/site_perl/5.8.6/i386-linux-thread-multi
    /home/lace/share/perl/site_perl/5.8.6
    /home/lace/share/perl/site_perl/i386-linux-thread-multi
    /home/lace/share/perl/site_perl
    /home/lace/share/perl/5.8.6/i386-linux-thread-multi
    /home/lace/share/perl/5.8.6
    /home/lace/share/perl/i386-linux-thread-multi
    /home/lace/share/perl
    /home/lace/lib/perl5/site_perl/5.8.6/i386-linux-thread-multi
    /home/lace/lib/perl5/site_perl/5.8.6
    /home/lace/lib/perl5/site_perl/i386-linux-thread-multi
    /home/lace/lib/perl5/site_perl
    /home/lace/lib/perl5/5.8.6/i386-linux-thread-multi
    /home/lace/lib/perl5/5.8.6
    /home/lace/lib/perl5/i386-linux-thread-multi
    /home/lace/lib/perl5
    /usr/lib/perl/site_perl/5.8.6/i386-linux-thread-multi
    /usr/lib/perl/site_perl/5.8.6
    /usr/lib/perl/site_perl/i386-linux-thread-multi
    /usr/lib/perl/site_perl
    /usr/lib/perl/5.8.6/i386-linux-thread-multi
    /usr/lib/perl/5.8.6
    /usr/lib/perl/i386-linux-thread-multi
    /usr/lib/perl
    /usr/share/perl/site_perl/5.8.6/i386-linux-thread-multi
    /usr/share/perl/site_perl/5.8.6
    /usr/share/perl/site_perl/i386-linux-thread-multi
    /usr/share/perl/site_perl
    /usr/share/perl/5.8.6/i386-linux-thread-multi
    /usr/share/perl/5.8.6
    /usr/share/perl/i386-linux-thread-multi
    /usr/share/perl
    /usr/lib/perl5/site_perl/5.8.6/i386-linux-thread-multi
    /usr/lib/perl5/site_perl/5.8.6
    /usr/lib/perl5/site_perl/i386-linux-thread-multi
    /usr/lib/perl5/site_perl
    /usr/lib/perl5/5.8.6/i386-linux-thread-multi
    /usr/lib/perl5/5.8.6
    /usr/lib/perl5/i386-linux-thread-multi
    /usr/lib/perl5
    /usr/lib/perl5/site_perl/5.8.6/i386-linux-thread-multi
    /usr/lib/perl5/site_perl/5.8.5/i386-linux-thread-multi
    /usr/lib/perl5/site_perl/5.8.4/i386-linux-thread-multi
    /usr/lib/perl5/site_perl/5.8.3/i386-linux-thread-multi
    /usr/lib/perl5/site_perl/5.8.6
    /usr/lib/perl5/site_perl/5.8.5
    /usr/lib/perl5/site_perl/5.8.4
    /usr/lib/perl5/site_perl/5.8.3
    /usr/lib/perl5/site_perl
    /usr/lib/perl5/vendor_perl/5.8.6/i386-linux-thread-multi
    /usr/lib/perl5/vendor_perl/5.8.5/i386-linux-thread-multi
    /usr/lib/perl5/vendor_perl/5.8.4/i386-linux-thread-multi
    /usr/lib/perl5/vendor_perl/5.8.3/i386-linux-thread-multi
    /usr/lib/perl5/vendor_perl/5.8.6
    /usr/lib/perl5/vendor_perl/5.8.5
    /usr/lib/perl5/vendor_perl/5.8.4
    /usr/lib/perl5/vendor_perl/5.8.3
    /usr/lib/perl5/vendor_perl
    /usr/lib/perl5/5.8.6/i386-linux-thread-multi
    /usr/lib/perl5/5.8.6
    .


Environment for perl v5.8.6:
    HOME=/home/lace
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_COLLATE=C
    LC_CTYPE=ja_JP.UTF-8
    LD_LIBRARY_PATH=/home/lace/lib:/opt/sfw/lib
    LOGDIR (unset)
    PATH=/home/lace/bin:/usr/local/bin:/opt/sfw/bin:/usr/sbin:/sbin:/usr/dist/exe:/opt/SUNWspro/bin:/usr/kerberos/bin:/usr/bin:/bin:/usr/X11R6/bin
    PERLLIB=/home/lace/lib/perl/site_perl/5.8.6/i386-linux-thread-multi:/home/lace/lib/perl/site_perl/5.8.6:/home/lace/lib/perl/site_perl/i386-linux-thread-multi:/home/lace/lib/perl/site_perl:/home/lace/lib/perl/5.8.6/i386-linux-thread-multi:/home/lace/lib/perl/5.8.6:/home/lace/lib/perl/i386-linux-thread-multi:/home/lace/lib/perl:/home/lace/share/perl/site_perl/5.8.6/i386-linux-thread-multi:/home/lace/share/perl/site_perl/5.8.6:/home/lace/share/perl/site_perl/i386-linux-thread-multi:/home/lace/share/perl/site_perl:/home/lace/share/perl/5.8.6/i386-linux-thread-multi:/home/lace/share/perl/5.8.6:/home/lace/share/perl/i386-linux-thread-multi:/home/lace/share/perl:/home/lace/lib/perl5/site_perl/5.8.6/i386-linux-thread-multi:/home/lace/lib/perl5/site_perl/5.8.6:/home/lace/lib/perl5/site_perl/i386-linux-thread-multi:/home/lace/lib/perl5/site_perl:/home/lace/lib/perl5/5.8.6/i386-linux-thread-multi:/home/lace/lib/perl5/5.8.6:/home/lace/lib/perl5/i386-linux-thread-multi:/home/lace/lib!
 /perl5:/usr/lib/perl/site_perl/5.8.6/i386-linux-thread-multi:/usr/lib/perl/site_perl/5.8.6:/usr/lib/perl/site_perl/i386-linux-thread-multi:/usr/lib/perl/site_perl:/usr/lib/perl/5.8.6/i386-linux-thread-multi:/usr/lib/perl/5.8.6:/usr/lib/perl/i386-linux-thread-multi:/usr/lib/perl:/usr/share/perl/site_perl/5.8.6/i386-linux-thread-multi:/usr/share/perl/site_perl/5.8.6:/usr/share/perl/site_perl/i386-linux-thread-multi:/usr/share/perl/site_perl:/usr/share/perl/5.8.6/i386-linux-thread-multi:/usr/share/perl/5.8.6:/usr/share/perl/i386-linux-thread-multi:/usr/share/perl:/usr/lib/perl5/site_perl/5.8.6/i386-linux-thread-multi:/usr/lib/perl5/site_perl/5.8.6:/usr/lib/perl5/site_perl/i386-linux-thread-multi:/usr/lib/perl5/site_perl:/usr/lib/perl5/5.8.6/i386-linux-thread-multi:/usr/lib/perl5/5.8.6:/usr/lib/perl5/i386-linux-thread-multi:/usr/lib/perl5
    PERL_BADLANG (unset)
    PERL_MM_OPT=PERL=/home/lace/bin/perlilib PREFIX=/home/lace
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @smpeters

> \[lace@&#8203;jankratochvil\.net \- Sat Aug 20 19&#8203;:14&#8203;:14 2005\]&#8203;:
> 
> 
> This is a bug report for perl from lace@&#8203;jankratochvil\.net\,
> generated with the help of perlbug 1\.35 running under perl v5\.8\.6\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> 
> Source w/syntax error causes crash of Perl\.
> 
> Unfortunately unable to minimize some reproducible case\. It occurs in
>    mod\_perl
> environment\. Prepared reproducibility binary kit \(Fedora Core 4
>    based\)&#8203;:
>     http&#8203;://www\.jankratochvil\.net/priv/perl\-semicolon\-crash\-2005082100\-
>    chrooted\.tar\.gz
> 
> Everything contained inside\, reproducible by&#8203;:
>     chroot /tmp/chrooted/ /usr/sbin/httpd \-d
>    /home/lace/www/engine/etc/httpd \-DPERL \-X
> 
> Tried also perl\-5\.8\.7 \(ported myself\) and it still crashes\. All the
>    binaries
> tried only in their Fedora Core 4 variants\.
> 
> Source fix to avoid this bug&#8203;:
> \-\-\- home/lace/www/www\.jankratochvil\.net/project/captive/CVS\.pm\-orig
>    2005\-08\-21 11&#8203;:00&#8203;:52\.058785000 \+0900
> \+\+\+ home/lace/www/www\.jankratochvil\.net/project/captive/CVS\.pm    2005\-
>    08\-21 11&#8203;:01&#8203;:02\.607094776 \+0900
> @&#8203;@&#8203; \-99\,7 \+99\,7 @&#8203;@&#8203;
>                          \.'\<hr />requirement&#8203;: '
>                          \.a\_href\('http&#8203;://linux\-
>    ntfs\.sourceforge\.net/downloads\.html\#downloads'\,'ntfsprogs'\)
>                          \.' '\.$format\.' &ge; 1\.8\.0'
> \-                    \.'\</td>\</tr>\</table>';
> \+                    \.'\</td>\</tr>\</table>'
>                  \.'\</td>\</tr>\</table>';
>      \};
> 
> 
> Extracted relevant part from gdb\(1\)&#8203;:
> 
> \#0  Perl\_pad\_free \(my\_perl=0x8390f10\, po=29\) at pad\.c&#8203;:1171
> 1171        SvPADTMP\_off\(PL\_curpad\[po\]\);
> \(gdb\) bt
> \#0  Perl\_pad\_free \(my\_perl=0x8390f10\, po=29\) at pad\.c&#8203;:1171
> \#1  0x00e1fafa in Perl\_op\_clear \(my\_perl=0x8390f10\, o=0x8878480\) at
>    op\.c&#8203;:516
> \#2  0x00e1fe49 in Perl\_op\_free \(my\_perl=0x8390f10\, o=0x8878480\) at
>    op\.c&#8203;:380
> \#3  0x00e1fe04 in Perl\_op\_free \(my\_perl=0x8390f10\, o=0x88784a8\) at
>    op\.c&#8203;:368
> \#4  0x00e1fe04 in Perl\_op\_free \(my\_perl=0x8390f10\, o=0x88a7ac8\) at
>    op\.c&#8203;:368
> \#5  0x00e1fe04 in Perl\_op\_free \(my\_perl=0x8390f10\, o=0x88a7b10\) at
>    op\.c&#8203;:368
> \#6  0x00e1fe04 in Perl\_op\_free \(my\_perl=0x8390f10\, o=0x88a7aa0\) at
>    op\.c&#8203;:368
> \#7  0x00e2daff in Perl\_newATTRSUB \(my\_perl=0x8390f10\, floor=293\,
>    o=0x88a74a0\, proto=0x0\, attrs=0x0\, block=0x88a7aa0\)
>     at op\.c&#8203;:4376
> \#8  0x00e1d536 in Perl\_yyparse \(my\_perl=0x8390f10\) at perly\.y&#8203;:355
> \#9  0x00e95628 in S\_doeval \(my\_perl=0x8390f10\, gimme=0\, startop=0x0\,
>    outside=0x0\, seq=137958892\) at pp\_ctl\.c&#8203;:2847
> \#10 0x00e9c277 in Perl\_pp\_require \(my\_perl=0x8390f10\) at pp\_ctl\.c&#8203;:3344
> \#11 0x003e5026 in modperl\_perl\_global\_request\_restore \(\) from
>    /home/lace/www/engine/etc/httpd/modules/mod\_perl\.so
> \#12 0x00e436e1 in Perl\_runops\_debug \(my\_perl=0x8390f10\) at dump\.c&#8203;:1449
> \#13 0x00df0b9e in S\_call\_body \(my\_perl=0x8390f10\, myop=0x19\,
>    is\_eval=58\) at perl\.c&#8203;:2299
> \#14 0x00df3c73 in Perl\_eval\_sv \(my\_perl=0x8390f10\, sv=0x83a37a0\,
>    flags=2\) at perl\.c&#8203;:2363
> \#15 0x003db8f8 in modperl\_require\_module \(\) from
>    /home/lace/www/engine/etc/httpd/modules/mod\_perl\.so
> \#16 0x003d6d0d in modperl\_cmd\_modules \(\) from
>    /home/lace/www/engine/etc/httpd/modules/mod\_perl\.so
> \#17 0x00d52e02 in ap\_add\_named\_module \(\) from /usr/sbin/httpd
> \#18 0x00d532f9 in ap\_walk\_config \(\) from /usr/sbin/httpd
> \#19 0x00d53839 in ap\_process\_config\_tree \(\) from /usr/sbin/httpd
> \#20 0x00d5766b in main \(\) from /usr/sbin/httpd
> \(gdb\) p my\_perl\->Tcurpad\[po\]
> $1 = \(SV \*\) 0x19
> \(gdb\) up
> \#1  0x00e1fafa in Perl\_op\_clear \(my\_perl=0x8390f10\, o=0x8878480\) at
>    op\.c&#8203;:516
> 516        pad\_free\(o\->op\_targ\);
> \(gdb\) p \*o
> $2 = \{op\_next = 0x8878460\, op\_sibling = 0x8878460\, op\_ppaddr =
>    0xe5a962 \<Perl\_pp\_concat>\, op\_targ = 29\, op\_type = 66\,
>   op\_seq = 0\, op\_flags = 70 'F'\, op\_private = 2 '\\002'\}
> \(gdb\) p \*o\->op\_next
> $3 = \{op\_next = 0x88784a8\, op\_sibling = 0x0\, op\_ppaddr = 0xe5a3c0
>    \<Perl\_pp\_const>\, op\_targ = 0\, op\_type = 5\, op\_seq = 0\,
>   op\_flags = 2 '\\002'\, op\_private = 0 '\\0'\}
> 
> 
> 

You mentioned that this problem occured while using mod\_perl\.  What
version of mod\_perl?  Also\, what version of Apache?  Also\, do you have
anything smaller that a 22MB file that demonstrates this problem?

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, Aug 20\, 2005 at 07&#8203;:14&#8203;:14PM \-0700\, lace @&#8203; jankratochvil\. net wrote&#8203;:
> \#0  Perl\_pad\_free \(my\_perl=0x8390f10\, po=29\) at pad\.c&#8203;:1171
> 1171        SvPADTMP\_off\(PL\_curpad\[po\]\);
> \(gdb\) bt
> \#0  Perl\_pad\_free \(my\_perl=0x8390f10\, po=29\) at pad\.c&#8203;:1171
> \#1  0x00e1fafa in Perl\_op\_clear \(my\_perl=0x8390f10\, o=0x8878480\) at op\.c&#8203;:516
> \#2  0x00e1fe49 in Perl\_op\_free \(my\_perl=0x8390f10\, o=0x8878480\) at op\.c&#8203;:380
> \#3  0x00e1fe04 in Perl\_op\_free \(my\_perl=0x8390f10\, o=0x88784a8\) at op\.c&#8203;:368
> \#4  0x00e1fe04 in Perl\_op\_free \(my\_perl=0x8390f10\, o=0x88a7ac8\) at op\.c&#8203;:368
> \#5  0x00e1fe04 in Perl\_op\_free \(my\_perl=0x8390f10\, o=0x88a7b10\) at op\.c&#8203;:368
> \#6  0x00e1fe04 in Perl\_op\_free \(my\_perl=0x8390f10\, o=0x88a7aa0\) at op\.c&#8203;:368
> \#7  0x00e2daff in Perl\_newATTRSUB \(my\_perl=0x8390f10\, floor=293\, o=0x88a74a0\, proto=0x0\, attrs=0x0\, block=0x88a7aa0\)

Without looking at the original code\, this looks a bit like a well\-known
problem that's fixed in 5\.9\.1\. Are you able to try your code with 5\.9\.1 or
5\.9\.2 so that we can confirm whether it's the same problem?

\-\- 
My Dad used to say 'always fight fire with fire'\, which is probably why
he got thrown out of the fire brigade\.

**Comment by p5pRT** [comment]
### From lace@jankratochvil.net

Hi\,

On Sun\, 04 Sep 2005 12&#8203;:50&#8203;:31 \+0900\, Steve Peters via RT wrote&#8203;:
\.\.\.
> >     http&#8203;://www\.jankratochvil\.net/priv/perl\-semicolon\-crash\-2005082100\-chrooted\.tar\.gz
\.\.\.
> You mentioned that this problem occured while using mod\_perl\.  What
> version of mod\_perl?

mod\_perl\-2\.0\.1\-1\.fc4
&nbsp;    http&#8203;://www\.jankratochvil\.net/priv/perl\-semicolon\-crash\-2005082100\-chrooted\.tar\.gz/Fedora\-Core\-4\-rpm\-qa

> Also\, what version of Apache?  Also\, do you have

httpd\-2\.0\.54\-10\.1
&nbsp;    http&#8203;://www\.jankratochvil\.net/priv/perl\-semicolon\-crash\-2005082100\-chrooted\.tar\.gz/Fedora\-Core\-4\-rpm\-qa

> anything smaller that a 22MB file that demonstrates this problem?

No\. I tried \(not so hard\) and failed to reproduce it in smaller case\.

> > Unfortunately unable to minimize some reproducible case\.


If you do not see the reason easily maybe feel free to drop it as it caused by
Perl source syntax error and this part of Perl parsing code has a lot of
FIXMEs\. I expect it should get resolved in some 5\.9\.x\, maybe already\, not sure\.


Regards\,
Lace

**Comment by p5pRT** [comment]
### From lace@jankratochvil.net

On Sun\, 04 Sep 2005 18&#8203;:29&#8203;:40 \+0900\, Dave Mitchell via RT wrote&#8203;:
\.\.\.
> Without looking at the original code\, this looks a bit like a well\-known
> problem that's fixed in 5\.9\.1\. Are you able to try your code with 5\.9\.1 or
> 5\.9\.2 so that we can confirm whether it's the same problem?

Do you expect just replacing the binary "CORE/libperl\.so" is possibly?
Therefore \- is this library binary compatible from 5\.8\.6 to 5\.9\.2 for all its
libraries? I do not think so\, so I will have to rebuild all the libraries\.


Regards\,
Lace

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Sep 04\, 2005 at 06&#8203;:41&#8203;:20PM \+0900\, Jan Kratochvil wrote&#8203;:
> Do you expect just replacing the binary "CORE/libperl\.so" is possibly?
> Therefore \- is this library binary compatible from 5\.8\.6 to 5\.9\.2 for all its
> libraries? I do not think so\, so I will have to rebuild all the libraries\.

No\, everything would have to be recompoiled from scratch\.

\-\- 
You never really learn to swear until you learn to drive\.

**Comment by p5pRT** [comment]
### From p5p@spam.wizbit.be

Attached is a tgz file with the relevant files\.

References to non core modules in My/Web\.pm got removed \(to make it 
easier to test\)\.

perl\-5\.8\.8 \-c CVS\.pm
Segmentation fault

perl\-5\.9\.0 \-c CVS\.pm
Segmentation fault

perl\-5\.9\.1 \-c CVS\.pm 
syntax error at CVS\.pm line 103\, near "\."
CVS\.pm had compilation errors\.

perl\-5\.10\.0 \-c CVS\.pm 
syntax error at CVS\.pm line 103\, near "\."
CVS\.pm had compilation errors\.

perl\-blead \-c CVS\.pm
syntax error at CVS\.pm line 103\, near "\."
CVS\.pm had compilation errors\.


Marking it as resolved based on this\.

**Comment by p5pRT** [comment]
### From p5p@spam.wizbit.be

[rt-36969.tgz](https://rt-archive.perl.org/perl5/Ticket/Attachment/411830/187054/rt-36969.tgz)

**Comment by p5pRT** [comment]
p5p@spam.wizbit.be - Status changed from 'open' to 'resolved'
