### ISSUE TITLE
perl segfault at 'compile'-time

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8089]
Migrated from [rt.perl.org#37036](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=37036) (status was 'resolved')

Searchable as RT37036$

**Comment by p5pRT** [comment]
### From tassadar+perl@xephon.org


This is a bug report for perl from tassadar\+perl@&#8203;xephon\.org\,
generated with the help of perlbug 1\.35 running under perl v5\.8\.7\.




---
Hi\, i've found a small code that triggers a segfault on the
following perl versions :

5\.8\.4 \(ubuntu package\)
5\.8\.7 \(debian testing package\)
5\.8\.7 \(freebsd port 5\.3\-RELEASE\)
5\.9\.1 \(compiled on my linux debian testing i386\, gcc\-4\.0\.1\)

unaffected versions :
version 5\.005\_03 built for sun4\-solaris

Priority is low\, since this code is incorrect\, but it might help
resolving other issues\.

the segfault does not appear when not using 'strict'\.
note that no code is executed since it's in a sub that is never
called at runtime\.

\-\- CODE BEGINS HERE \-\-
\#\!/usr/bin/perl
use strict;
sub s \{ open $X\, my $Y\, r; \}
\-\- CODE ENDS HERE \-\-

hope it might help\,

Nicolas



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=low


---
Site configuration information for perl v5\.8\.7&#8203;:

Configured by Debian Project at Thu Jun  9 00&#8203;:28&#8203;:22 EST 2005\.

Summary of my perl5 \(revision 5 version 8 subversion 7\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.4\.27\-ti1211\, archname=i386\-linux\-thread\-multi
&nbsp;    uname='linux kosh 2\.4\.27\-ti1211 \#1 sun sep 19 18&#8203;:17&#8203;:45 est 2004 i686 gnulinux '
&nbsp;    config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN \-Dcccdlflags=\-fPIC \-Darchname=i386\-linux \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.8 \-Darchlib=/usr/lib/perl/5\.8 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.8\.7 \-Dsitearch=/usr/local/lib/perl/5\.8\.7 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1 \-Dsiteman3dir=/usr/local/man/man3 \-Dman1ext=1 \-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Uusesfio \-Uusenm \-Duseshrplib \-Dlibperl=libperl\.so\.5\.8\.7 \-Dd\_dosuid \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBIAN \-fno\-strict\-aliasing \-pipe \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBIAN \-fno\-strict\-aliasing \-pipe \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='3\.3\.6 \(Debian 1&#8203;:3\.3\.6\-6\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    libc=/lib/libc\-2\.3\.2\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.8\.7
&nbsp;    gnulibc\_version='2\.3\.2'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-L/usr/local/lib'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl v5\.8\.7&#8203;:
&nbsp;    /etc/perl
&nbsp;    /usr/local/lib/perl/5\.8\.7
&nbsp;    /usr/local/share/perl/5\.8\.7
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/perl/5\.8
&nbsp;    /usr/share/perl/5\.8
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    \.



---
Environment for perl v5\.8\.7&#8203;:
&nbsp;    HOME=/home/tassadar
&nbsp;    LANG=fr\_FR@&#8203;euro
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/tassadar/bison&#8203;:/home/tassadar/bin/&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/bin/X11&#8203;:/usr/games
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/zsh

**Comment by p5pRT** [comment]
### From @smpeters

> \[tassadar\+perl@&#8203;xephon\.org \- Wed Aug 31 01&#8203;:38&#8203;:30 2005\]&#8203;:
> 
> 
> This is a bug report for perl from tassadar\+perl@&#8203;xephon\.org\,
> generated with the help of perlbug 1\.35 running under perl v5\.8\.7\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> Hi\, i've found a small code that triggers a segfault on the
> following perl versions :
> 
> 5\.8\.4 \(ubuntu package\)
> 5\.8\.7 \(debian testing package\)
> 5\.8\.7 \(freebsd port 5\.3\-RELEASE\)
> 5\.9\.1 \(compiled on my linux debian testing i386\, gcc\-4\.0\.1\)
> 
> unaffected versions :
> version 5\.005\_03 built for sun4\-solaris
> 
> Priority is low\, since this code is incorrect\, but it might help
> resolving other issues\.
> 
> the segfault does not appear when not using 'strict'\.
> note that no code is executed since it's in a sub that is never
> called at runtime\.
> 
> \-\- CODE BEGINS HERE \-\-
> \#\!/usr/bin/perl
> use strict;
> sub s \{ open $X\, my $Y\, r; \}
> \-\- CODE ENDS HERE \-\-
> 

This appears to have been fixed in bleadperl\.  I'm not sure\, though\,
what the exact fix was\.  Using perl\-current\, I get&#8203;:

> \./perl \-Mstrict \-wle'sub s \{ open $X\, my $Y\, r; \}'
Global symbol "$X" requires explicit package name at \-e line 1\.
Execution of \-e aborted due to compilation errors\.

In the 5\.8 releases\, the coredump occurs in Perl\_ck\_open\.

\#0  0x0809964c in Perl\_ck\_open \(\)
\(gdb\) bt
\#0  0x0809964c in Perl\_ck\_open \(\)
\#1  0x08092698 in Perl\_convert \(\)
\#2  0x08089336 in Perl\_yyparse \(\)
\#3  0x0806731a in Perl\_my\_failure\_exit \(\)
\#4  0x08068d0e in perl\_parse \(\)
\#5  0x0805fda9 in main \(\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From domo@computer.org

Summary&#8203;: already fixed by patch 24523\.

On 2005–08–31\, at 10&#8203;:38\, tassadar\+perl@&#8203;xephon\.org \(via RT\) wrote&#8203;:

> \-\- CODE BEGINS HERE \-\-
> \#\!/usr/bin/perl
> use strict;
> sub s \{ open $X\, my $Y\, r; \}
> \-\- CODE ENDS HERE \-\-
> \[crashes on 5\.8\.x\, 5\.9\.1\]

FWIW\, I see the crash \(on Darwin\) with 5\.8\.1\-7 \(omitting 5\.8\.2\, which  
I don't have lying around\) and 5\.9\.2\, but not with bleadperl@&#8203;25275\.  
Stack trace for the crashed perls is like

Thread 0 Crashed&#8203;:
0   perl     0x0002893c Perl\_ck\_open \+ 452 \(op\.c&#8203;:5835\)
1   perl     0x00017624 Perl\_convert \+ 452 \(op\.c&#8203;:2131\)
2   perl     0x001adc60 Perl\_yyparse \+ 8252 \(perly\.y&#8203;:427\)
3   perl     0x00033018 S\_parse\_body \+ 6184 \(perl\.c&#8203;:1733\)
4   perl     0x000315a4 perl\_parse \+ 1780 \(perl\.c&#8203;:1203\)
5   perl     0x000028b8 main \+ 308 \(perlmain\.c&#8203;:97\)
6   perl     0x00001fe0 \_start \+ 344 \(crt\.c&#8203;:272\)
7   perl     0x00001e84 start \+ 60

\(That happens to be 5\.9\.2; others are similar\.\)

A sniff of the blame log shows that patch 24523 did a little consting  
in that area\. Reverting the changed lines in bleadperl brings the  
crash back\. So consting fixed a bug that hadn't even been reported\!

Does consting stuff like this get rolled into the various maints as a  
matter of course?
\-\- 
Dominic Dunlop

**Comment by p5pRT** [comment]
### From @smpeters

> \[domo@&#8203;computer\.org \- Wed Aug 31 06&#8203;:01&#8203;:12 2005\]&#8203;:
> 
> Summary&#8203;: already fixed by patch 24523\.
> 
> On 2005–08–31\, at 10&#8203;:38\, tassadar\+perl@&#8203;xephon\.org \(via RT\) wrote&#8203;:
> 
> > \-\- CODE BEGINS HERE \-\-
> > \#\!/usr/bin/perl
> > use strict;
> > sub s \{ open $X\, my $Y\, r; \}
> > \-\- CODE ENDS HERE \-\-
> > \[crashes on 5\.8\.x\, 5\.9\.1\]
> 
> FWIW\, I see the crash \(on Darwin\) with 5\.8\.1\-7 \(omitting 5\.8\.2\, which  
> I don't have lying around\) and 5\.9\.2\, but not with bleadperl@&#8203;25275\.  
> Stack trace for the crashed perls is like
> 
> Thread 0 Crashed&#8203;:
> 0   perl     0x0002893c Perl\_ck\_open \+ 452 \(op\.c&#8203;:5835\)
> 1   perl     0x00017624 Perl\_convert \+ 452 \(op\.c&#8203;:2131\)
> 2   perl     0x001adc60 Perl\_yyparse \+ 8252 \(perly\.y&#8203;:427\)
> 3   perl     0x00033018 S\_parse\_body \+ 6184 \(perl\.c&#8203;:1733\)
> 4   perl     0x000315a4 perl\_parse \+ 1780 \(perl\.c&#8203;:1203\)
> 5   perl     0x000028b8 main \+ 308 \(perlmain\.c&#8203;:97\)
> 6   perl     0x00001fe0 \_start \+ 344 \(crt\.c&#8203;:272\)
> 7   perl     0x00001e84 start \+ 60
> 
> \(That happens to be 5\.9\.2; others are similar\.\)
> 
> A sniff of the blame log shows that patch 24523 did a little consting  
> in that area\. Reverting the changed lines in bleadperl brings the  
> crash back\. So consting fixed a bug that hadn't even been reported\!
> 
> Does consting stuff like this get rolled into the various maints as a  
> matter of course?
> 

This seems to go a bit deeper\.  My current bleadperl works fine on
OpenBSD\, but segfaults on Linux\.  I'll have to play with the
configurations to see what the backtrace from Linux will show me now\.

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'resolved' to 'open'

**Comment by p5pRT** [comment]
### From @rgs

tassadar\+perl@&#8203;xephon\.org \(via RT\) wrote&#8203;:
> Priority is low\, since this code is incorrect\, but it might help
> resolving other issues\.
> 
> the segfault does not appear when not using 'strict'\.
> note that no code is executed since it's in a sub that is never
> called at runtime\.
> 
> \-\- CODE BEGINS HERE \-\-
> \#\!/usr/bin/perl
> use strict;
> sub s \{ open $X\, my $Y\, r; \}
> \-\- CODE ENDS HERE \-\-

Thanks for the report\, fixed as below in the development version of
perl&#8203;:

Change 25341 by rgs@&#8203;bloom on 2005/08/31 14&#8203;:14&#8203;:21

&nbsp;        Fix for \[perl \#37036\] perl segfault at 'compile'\-time

Affected files \.\.\.

\.\.\. //depot/perl/op\.c\#702 edit

Differences \.\.\.

==== //depot/perl/op\.c\#702 \(text\) ====

@&#8203;@&#8203; \-5896\,6 \+5896\,7 @&#8203;@&#8203;
&nbsp;             \(last\->op\_private & OPpCONST\_STRICT\) &&
&nbsp;             \(oa = first\->op\_sibling\) &&                /\* The fh\. \*/
&nbsp;             \(oa = oa\->op\_sibling\) &&                   /\* The mode\. \*/
\+            \(oa\->op\_type == OP\_CONST\) &&
&nbsp;             SvPOK\(\(\(SVOP\*\)oa\)\->op\_sv\) &&
&nbsp;             \(mode = SvPVX\_const\(\(\(SVOP\*\)oa\)\->op\_sv\)\) &&
&nbsp;             mode\[0\] == '>' && mode\[1\] == '&' &&        /\* A dup open\. \*/

**Comment by p5pRT** [comment]
@rgs - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @nwc10

On Wed\, Aug 31\, 2005 at 03&#8203;:00&#8203;:31PM \+0200\, Dominic Dunlop wrote&#8203;:

> Does consting stuff like this get rolled into the various maints as a  
> matter of course?

It will get into 5\.8\.x if it doesn't seem to break anything else\.

Nicholas Clark
