### ISSUE TITLE
script produces segfault (testcase attached)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8093]
Migrated from [rt.perl.org#37058](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=37058) (status was 'open')

Searchable as RT37058$

**Comment by p5pRT** [comment]
### From Nikolaus@rath.org

#### Created by Nikolaus@rath.org


Hi\!

The following perl\-file produces a segfault as soon as the last line of
code has been executed\. I removed as much stuff as possible\, removing
anything more makes the segfault disappear\.

\-\-\-\-\-\-\-\-\-\-snip\-\-\-\-\-\-\-\-\-\-\-\-
\#\!/usr/bin/perl

use strict;
use warnings;
use Date&#8203;::Parse;
use IO&#8203;::File;
use XML&#8203;::Writer;
use Term&#8203;::ReadLine;
use File&#8203;::Find;
use File&#8203;::Temp qw/tempfile tempdir/;
use File&#8203;::Path;
use POSIX;

get\_tags\(\);


sub generate\_tar
\{
\}

sub generate\_iif
\{
&nbsp;    my @&#8203;indexfiles;
\}

sub arrayindex\_lc
\{
\}

sub get\_tags
\{
&nbsp;    my $term = new Term&#8203;::ReadLine 'Archiver';
\}

sub get\_tag\_hash
\{
\}

sub generate\_taglist
\{
\}

sub process\_file
\{
\}

sub run\_filter
\{
\}
\-\-\-\-\-\-\-\-\-\-snip\-\-\-\-\-\-\-\-\-\-\-\-

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.8.4:

Configured by Debian Project at Thu Mar 10 13:47:05 GMT 2005.

Summary of my perl5 (revision 5 version 8 subversion 4) configuration:
  Platform:
    osname=linux, osvers=2.6.8.1, archname=i386-linux-thread-multi
    uname='linux mcmurdo 2.6.8.1 #1 smp sat feb 26 13:03:40 utc 2005 i686 gnulinux '
    config_args='-Dusethreads -Duselargefiles -Dccflags=-DDEBIAN -Dcccdlflags=-fPIC -Darchname=i386-linux -Dprefix=/usr -Dprivlib=/usr/share/perl/5.8 -Darchlib=/usr/lib/perl/5.8 -Dvendorprefix=/usr -Dvendorlib=/usr/share/perl5 -Dvendorarch=/usr/lib/perl5 -Dsiteprefix=/usr/local -Dsitelib=/usr/local/share/perl/5.8.4 -Dsitearch=/usr/local/lib/perl/5.8.4 -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 -Dsiteman1dir=/usr/local/man/man1 -Dsiteman3dir=/usr/local/man/man3 -Dman1ext=1 -Dman3ext=3perl -Dpager=/usr/bin/sensible-pager -Uafs -Ud_csh -Uusesfio -Uusenm -Duseshrplib -Dlibperl=libperl.so.5.8.4 -Dd_dosuid -des'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -DDEBIAN -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -DDEBIAN -fno-strict-aliasing -I/usr/local/include'
    ccversion='', gccversion='3.3.5 (Debian 1:3.3.5-8ubuntu2)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lgdbm -lgdbm_compat -ldb -ldl -lm -lpthread -lc -lcrypt
    perllibs=-ldl -lm -lpthread -lc -lcrypt
    libc=/lib/libc-2.3.2.so, so=so, useshrplib=true, libperl=libperl.so.5.8.4
    gnulibc_version='2.3.2'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.4:
    /etc/perl
    /usr/local/lib/perl/5.8.4
    /usr/local/share/perl/5.8.4
    /usr/lib/perl5
    /usr/share/perl5
    /usr/lib/perl/5.8
    /usr/share/perl/5.8
    /usr/local/lib/site_perl
    .


Environment for perl v5.8.4:
    HOME=/home/nikratio
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_ADDRESS=de_DE.UTF-8
    LC_COLLATE=de_DE.UTF-8
    LC_CTYPE=de_DE.UTF-8
    LC_IDENTIFICATION=en_US.UTF-8
    LC_MEASUREMENT=de_DE.UTF-8
    LC_MESSAGES=en_US.UTF-8
    LC_MONETARY=de_DE.UTF-8
    LC_NAME=de_DE.UTF-8
    LC_NUMERIC=de_DE.UTF-8
    LC_PAPER=de_DE.UTF-8
    LC_TELEPHONE=de_DE.UTF-8
    LC_TIME=de_DE.UTF-8
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=~/bin:~/Projekte/Scripts:/opt/emperor/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From sts@accognoscere.org

On Fri\, Sep 02\, 2005 at 02&#8203;:58&#8203;:35PM \-0700\, Nikolaus Rath wrote&#8203;:
> \# New Ticket Created by  Nikolaus Rath 
> \# Please include the string&#8203;:  \[perl \#37058\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=37058 >
> 
> 
> 
> This is a bug report for perl from Nikolaus@&#8203;rath\.org\,
> generated with the help of perlbug 1\.35 running under perl v5\.8\.4\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> Hi\!
> 
> The following perl\-file produces a segfault as soon as the last line of
> code has been executed\. I removed as much stuff as possible\, removing
> anything more makes the segfault disappear\.
> 
> \-\-\-\-\-\-\-\-\-\-snip\-\-\-\-\-\-\-\-\-\-\-\-
> \#\!/usr/bin/perl
> 
> use strict;
> use warnings;
> use Date&#8203;::Parse;
> use IO&#8203;::File;
> use XML&#8203;::Writer;
> use Term&#8203;::ReadLine;
> use File&#8203;::Find;
> use File&#8203;::Temp qw/tempfile tempdir/;
> use File&#8203;::Path;
> use POSIX;
> 
> get\_tags\(\);
> 
> 
> sub generate\_tar
> \{
> \}
> 
> sub generate\_iif
> \{
>     my @&#8203;indexfiles;
> \}
> 
> sub arrayindex\_lc
> \{
> \}
> 
> sub get\_tags
> \{
>     my $term = new Term&#8203;::ReadLine 'Archiver';
> \}
> 
> sub get\_tag\_hash
> \{
> \}
> 
> sub generate\_taglist
> \{
> \}
> 
> sub process\_file
> \{
> \}
> 
> sub run\_filter
> \{
> \}
> \-\-\-\-\-\-\-\-\-\-snip\-\-\-\-\-\-\-\-\-\-\-\-

Couldn't neither reproduce the segmentation fault with Perl 5\.8\.5
nor with Perl 5\.8\.7 on OpenBSD 3\.6\. The last lines get parsed & 
compiled\, but are never executed since there's no call of one of 
the subs except solely get\_tags\(\) itself\.

If you remove which lines the segmentation fault disappears?

\-\- 
Steven Schubiger \(sts@&#8203;accognoscere\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From Nikolaus@rath.org

Steven Schubiger via RT wrote&#8203;:
> On Fri\, Sep 02\, 2005 at 02&#8203;:58&#8203;:35PM \-0700\, Nikolaus Rath wrote&#8203;:
> 
>>\# New Ticket Created by  Nikolaus Rath 
>>\# Please include the string&#8203;:  \[perl \#37058\]
>>\# in the subject line of all future correspondence about this issue\. 
>>\# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=37058 >
>>
>>
>>
>>This is a bug report for perl from Nikolaus@&#8203;rath\.org\,
>>generated with the help of perlbug 1\.35 running under perl v5\.8\.4\.
>>
>>
>>\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
>>\[Please enter your report here\]
>>Hi\!
>>
>>The following perl\-file produces a segfault as soon as the last line of
>>code has been executed\. I removed as much stuff as possible\, removing
>>anything more makes the segfault disappear\.
>>
>>\-\-\-\-\-\-\-\-\-\-snip\-\-\-\-\-\-\-\-\-\-\-\-
>>\#\!/usr/bin/perl
>>
>>use strict;
>>use warnings;
>>use Date&#8203;::Parse;
>>use IO&#8203;::File;
>>use XML&#8203;::Writer;
>>use Term&#8203;::ReadLine;
>>use File&#8203;::Find;
>>use File&#8203;::Temp qw/tempfile tempdir/;
>>use File&#8203;::Path;
>>use POSIX;
>>
>>get\_tags\(\);
>>
>>
>>sub generate\_tar
>>\{
>>\}
>>
>>sub generate\_iif
>>\{
>>    my @&#8203;indexfiles;
>>\}
>>
>>sub arrayindex\_lc
>>\{
>>\}
>>
>>sub get\_tags
>>\{
>>    my $term = new Term&#8203;::ReadLine 'Archiver';
>>\}
>>
>>sub get\_tag\_hash
>>\{
>>\}
>>
>>sub generate\_taglist
>>\{
>>\}
>>
>>sub process\_file
>>\{
>>\}
>>
>>sub run\_filter
>>\{
>>\}
>>\-\-\-\-\-\-\-\-\-\-snip\-\-\-\-\-\-\-\-\-\-\-\-
> 
> 
> Couldn't neither reproduce the segmentation fault with Perl 5\.8\.5
> nor with Perl 5\.8\.7 on OpenBSD 3\.6\. The last lines get parsed & 
> compiled\, but are never executed since there's no call of one of 
> the subs except solely get\_tags\(\) itself\.
> 
> If you remove which lines the segmentation fault disappears?

For example\, if I remove the definition of run\_filter\.

Regards\,
Nikolaus

**Comment by p5pRT** [comment]
### From sts@accognoscere.org

On Mon\, Sep 26\, 2005 at 08&#8203;:09&#8203;:08AM \+0200\, Nikolaus Rath wrote&#8203;:
> Steven Schubiger via RT wrote&#8203;:
>
> >Couldn't neither reproduce the segmentation fault with Perl 5\.8\.5
> >nor with Perl 5\.8\.7 on OpenBSD 3\.6\. The last lines get parsed & 
> >compiled\, but are never executed since there's no call of one of 
> >the subs except solely get\_tags\(\) itself\.
> >
> >If you remove which lines the segmentation fault disappears?
> 
> For example\, if I remove the definition of run\_filter\.

Could you provide us a gdb backtrace of this code composition?

\-\- 
Steven Schubiger \(sts@&#8203;accognoscere\.org\)

**Comment by p5pRT** [comment]
### From sts@accognoscere.org

\-\-\-\-\- Forwarded message from Nikolaus Rath \<Nikolaus@&#8203;rath\.org> \-\-\-\-\-

Date&#8203;: Mon\, 26 Sep 2005 15&#8203;:57&#8203;:49 \+0200
From&#8203;: Nikolaus Rath \<Nikolaus@&#8203;rath\.org>
To&#8203;: Steven Schubiger \<sts@&#8203;accognoscere\.org>
Subject&#8203;: Re&#8203;: \[perl \#37058\] script produces segfault \(testcase attached\)


>>>>>Couldn't neither reproduce the segmentation fault with Perl 5\.8\.5
>>>>>nor with Perl 5\.8\.7 on OpenBSD 3\.6\. The last lines get parsed & 
>>>>>compiled\, but are never executed since there's no call of one of 
>>>>>the subs except solely get\_tags\(\) itself\.
>>>>>
>>>>>If you remove which lines the segmentation fault disappears?
>>>>
>>>>For example\, if I remove the definition of run\_filter\.
>>>
>>>
>>>Could you provide us a gdb backtrace of this code composition?

Backtrace is attached\.

Regards\,
Nikolaus

Program received signal SIGSEGV\, Segmentation fault\.
\[Switching to Thread \-1210167168 \(LWP 8349\)\]
0xb7e72acd in fclose \(\) from /lib/tls/i686/cmov/libc\.so\.6
\(gdb\) bt
\#0  0xb7e72acd in fclose \(\) from /lib/tls/i686/cmov/libc\.so\.6
\#1  0x0811878d in PerlIOStdio\_close \(\)
\#2  0x08116673 in PerlIO\_\_close \(\)
\#3  0x081166aa in Perl\_PerlIO\_close \(\)
\#4  0x08115196 in PerlIO\_cleantable \(\)
\#5  0x08117bb7 in PerlIO\_cleanup \(\)
\#6  0x08061cfd in perl\_destruct \(\)
\#7  0x0805fb0d in main \(\)

\-\-\-\-\- End forwarded message \-\-\-\-\-

**Comment by p5pRT** [comment]
### From Nikolaus@rath.org

Hello\!

Any news on this bug? If not\, maybe this is helpful&#8203;: After the last
glibc upgrade\, perl no longer segfaults but prints&#8203;:

\[127\] nokile&#8203;:\~/\.vmware/sambashare$ ~/Work/perlbug\.pl 
\*\*\* glibc detected \*\*\* double free or corruption \(\!prev\)&#8203;: 0x084deba0 \*\*\*
Aborted
\[134\] nokile&#8203;:\~/\.vmware/sambashare$


Regards\,

&nbsp;   \-\-Nikolaus

\-\- 
Es ist Ã¤rgerlich\, wie oft man manche Arbeit aufschieben muss\, ehe man
sie entgÃ¼ltig vergessen hat\.

**Comment by khwilliamson** [comment]
I believe this is fixed.  Please try it to make sure

**Comment by khwilliamson** [comment]
It hadn't occurred to me that tickets migrated to github wouldn't keep the subscribed-to status of the involved people.  And especially if the person isn't in github that they wouldn't get notified. 

I have now emailed the OP, and got the response that he has long ago moved on, and has nothing to add on this 20 year-old ticket.

I think we should close it.
