### ISSUE TITLE
threads + 'require IO' causes segmentation fault

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8094]
Migrated from [rt.perl.org#37076](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=37076) (status was 'resolved')

Searchable as RT37076$

**Comment by p5pRT** [comment]
### From ikegami@ni.aist.go.jp

#### Created by ikegami@p06cmp000.asc.hpcc.jp



On dual Opteron \(2 GHz\) machine\, perl 5\.8\.7 frequently causes
segmentation fault with the following code snippet\.

&nbsp;        \#\!/usr/bin/perl
&nbsp;        use threads;
&nbsp;        use threads&#8203;::shared;
&nbsp;        
&nbsp;        sub socket \(\) \{
&nbsp;          require IO;
&nbsp;          return;
&nbsp;        \}
&nbsp;        
&nbsp;        my $s = new threads \\&socket;
&nbsp;        my $c = new threads \\&socket;
&nbsp;        
&nbsp;        $s\->join;
&nbsp;        $c\->join;

It is not reproducible by 100 %\, and may not be reproducible on
slow/single\-processor machines\.  As a workaround\, put 'use IO'
somewhere\.  A stack trace taken from core file follows\.

\#0  0x0000002a95da8d88 in chunk\_alloc \(\) from /lib64/libc\.so\.6
\#1  0x0000002a95da8bc1 in malloc \(\) from /lib64/libc\.so\.6
\#2  0x0000000040065cb0 in Perl\_safesysmalloc \(\)
\#3  0x000000004007026f in S\_save\_hek\_flags \(\)
\#4  0x00000000400712fb in S\_share\_hek\_flags \(\)
\#5  0x00000000400722ee in S\_hv\_fetch\_common \(\)
\#6  0x0000000040072c20 in Perl\_hv\_fetch \(\)
\#7  0x0000000040026ff7 in Perl\_gv\_fetchpv \(\)
\#8  0x00000000400484a6 in Perl\_newXS \(\)
\#9  0x0000000040048a9e in Perl\_newCONSTSUB \(\)
\#10 0x0000002a9670225a in boot\_IO \(\)
&nbsp;   from /home/ikegami/local/perl/lib/5\.8\.7/x86\_64\-linux\-thread\-multi/auto/IO/IO\.so
\#11 0x000000004007780f in Perl\_pp\_entersub \(\)
\#12 0x000000004007609e in Perl\_runops\_standard \(\)
\#13 0x000000004001f92d in S\_call\_body \(\)
\#14 0x0000000040020741 in Perl\_call\_sv \(\)
\#15 0x00000000400209ec in Perl\_call\_list \(\)
\#16 0x00000000400527bc in Perl\_newATTRSUB \(\)
\#17 0x00000000400510bb in Perl\_utilize \(\)
\#18 0x00000000400434af in Perl\_yyparse \(\)
\#19 0x00000000400a6e4a in S\_doeval \(\)
\#20 0x00000000400a890d in Perl\_pp\_require \(\)
\#21 0x000000004007609e in Perl\_runops\_standard \(\)
\#22 0x000000004001f92d in S\_call\_body \(\)
\#23 0x0000000040020741 in Perl\_call\_sv \(\)
\#24 0x00000000400209ec in Perl\_call\_list \(\)
\#25 0x00000000400527bc in Perl\_newATTRSUB \(\)
\#26 0x00000000400510bb in Perl\_utilize \(\)
\#27 0x00000000400434af in Perl\_yyparse \(\)
\#28 0x00000000400a6e4a in S\_doeval \(\)
\#29 0x00000000400a890d in Perl\_pp\_require \(\)
\#30 0x000000004007609e in Perl\_runops\_standard \(\)
\#31 0x000000004001f92d in S\_call\_body \(\)
\#32 0x0000000040020741 in Perl\_call\_sv \(\)
\#33 0x0000002a95f6f020 in Perl\_ithread\_run \(\)
&nbsp;   from /home/ikegami/local/perl/lib/5\.8\.7/x86\_64\-linux\-thread\-multi/auto/threads/threads\.so
\#34 0x0000002a95c22c26 in pthread\_start\_thread \(\) from /lib64/libpthread\.so\.0
\#35 0x0000002a95dfbc95 in thread\_start \(\) from /lib64/libc\.so\.6

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.8.7:

Configured by ikegami at Tue Jun 21 18:32:40 JST 2005.

Summary of my perl5 (revision 5 version 8 subversion 7) configuration:
  Platform:
    osname=linux, osvers=2.4.21-251-smp, archname=x86_64-linux-thread-multi
    uname='linux p06cmp000.asc.hpcc.jp 2.4.21-251-smp #1 smp sun nov 7 22:25:59 jst 2004 x86_64 unknown '
    config_args='-ds -e -Dprefix=/home/ikegami/local/perl -Dusethreads'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=define use64bitall=define uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -fno-strict-aliasing -pipe -I/usr/local/include'
    ccversion='', gccversion='3.3.3 (SUSE Linux)', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
    libc=, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.2.5'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.7:
    /home/ikegami/lib/perl/x86_64-linux-thread-multi
    /home/ikegami/lib/perl
    /home/ikegami/local/perl/lib/5.8.7/x86_64-linux-thread-multi
    /home/ikegami/local/perl/lib/5.8.7
    /home/ikegami/local/perl/lib/site_perl/5.8.7/x86_64-linux-thread-multi
    /home/ikegami/local/perl/lib/site_perl/5.8.7
    /home/ikegami/local/perl/lib/site_perl
    .


Environment for perl v5.8.7:
    HOME=/home/ikegami
    LANG=ja_JP.ujis
    LANGUAGE (unset)
    LC_COLLATE=POSIX
    LD_LIBRARY_PATH=/home/ikegami/local/intel_fc_80/lib:/home/ikegami/local/intel_cc_80/lib:/opt/intel_fc_80/lib:/opt/intel_cc_80/lib:/opt/gt2/lib:/home/ikegami/local/lib
    LOGDIR (unset)
    PATH=/home/ikegami/local/ninfg-2.4.0/bin:/home/ikegami/bin:/home/ikegami/util:/home/ikegami/local/bin:/opt/gcc33/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11R6/bin:/home/ikegami/local/intel_fc_80/bin:/home/ikegami/local/intel_cc_80/bin:/opt/score/bin:/opt/score/sbin:/opt/score/deploy:/usr/pbs/bin:/opt/intel_fc_80/bin:/opt/intel_cc_80/bin:/opt/gt2/bin:/opt/gt2/sbin:/usr/games:/opt/gnome2/bin:/opt/gnome/bin:/opt/kde3/bin:/usr/lib/java/bin:/opt/gm/bin:/opt/pathscale/bin:/opt/pgi/linux86-64/5.2/bin:/opt/pgi/linux86/5.2/bin:.
    PERL5LIB=/home/ikegami/lib/perl
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @nwc10

On Mon\, Sep 05\, 2005 at 01&#8203;:42&#8203;:52AM \-0700\, ikegami @&#8203; ni\. aist\. go\. jp wrote&#8203;:

> On dual Opteron \(2 GHz\) machine\, perl 5\.8\.7 frequently causes
> segmentation fault with the following code snippet\.
> 
>         \#\!/usr/bin/perl
>         use threads;
>         use threads&#8203;::shared;
>         
>         sub socket \(\) \{
>           require IO;
>           return;
>         \}
>         
>         my $s = new threads \\&socket;
>         my $c = new threads \\&socket;
>         
>         $s\->join;
>         $c\->join;
> 
> It is not reproducible by 100 %\, and may not be reproducible on
> slow/single\-processor machines\.  As a workaround\, put 'use IO'
> somewhere\.  A stack trace taken from core file follows\.

It's more like 1\-5% reproducible on x86 Linux \(this was a dual CPU machine\)

> \#0  0x0000002a95da8d88 in chunk\_alloc \(\) from /lib64/libc\.so\.6
> \#1  0x0000002a95da8bc1 in malloc \(\) from /lib64/libc\.so\.6
> \#2  0x0000000040065cb0 in Perl\_safesysmalloc \(\)
> \#3  0x000000004007026f in S\_save\_hek\_flags \(\)
> \#4  0x00000000400712fb in S\_share\_hek\_flags \(\)
> \#5  0x00000000400722ee in S\_hv\_fetch\_common \(\)
> \#6  0x0000000040072c20 in Perl\_hv\_fetch \(\)
> \#7  0x0000000040026ff7 in Perl\_gv\_fetchpv \(\)
> \#8  0x00000000400484a6 in Perl\_newXS \(\)
> \#9  0x0000000040048a9e in Perl\_newCONSTSUB \(\)
> \#10 0x0000002a9670225a in boot\_IO \(\)
>    from /home/ikegami/local/perl/lib/5\.8\.7/x86\_64\-linux\-thread\-multi/auto/IO/IO\.so
> \#11 0x000000004007780f in Perl\_pp\_entersub \(\)
> \#12 0x000000004007609e in Perl\_runops\_standard \(\)
> \#13 0x000000004001f92d in S\_call\_body \(\)
> \#14 0x0000000040020741 in Perl\_call\_sv \(\)
> \#15 0x00000000400209ec in Perl\_call\_list \(\)
> \#16 0x00000000400527bc in Perl\_newATTRSUB \(\)
> \#17 0x00000000400510bb in Perl\_utilize \(\)
> \#18 0x00000000400434af in Perl\_yyparse \(\)
> \#19 0x00000000400a6e4a in S\_doeval \(\)
> \#20 0x00000000400a890d in Perl\_pp\_require \(\)
> \#21 0x000000004007609e in Perl\_runops\_standard \(\)
> \#22 0x000000004001f92d in S\_call\_body \(\)
> \#23 0x0000000040020741 in Perl\_call\_sv \(\)
> \#24 0x00000000400209ec in Perl\_call\_list \(\)
> \#25 0x00000000400527bc in Perl\_newATTRSUB \(\)
> \#26 0x00000000400510bb in Perl\_utilize \(\)
> \#27 0x00000000400434af in Perl\_yyparse \(\)
> \#28 0x00000000400a6e4a in S\_doeval \(\)
> \#29 0x00000000400a890d in Perl\_pp\_require \(\)
> \#30 0x000000004007609e in Perl\_runops\_standard \(\)
> \#31 0x000000004001f92d in S\_call\_body \(\)
> \#32 0x0000000040020741 in Perl\_call\_sv \(\)
> \#33 0x0000002a95f6f020 in Perl\_ithread\_run \(\)
>    from /home/ikegami/local/perl/lib/5\.8\.7/x86\_64\-linux\-thread\-multi/auto/threads/threads\.so
> \#34 0x0000002a95c22c26 in pthread\_start\_thread \(\) from /lib64/libpthread\.so\.0
> \#35 0x0000002a95dfbc95 in thread\_start \(\) from /lib64/libc\.so\.6

Stack backtrace from blead compiled with \-g

\#0  0xb749fa8e in \_int\_malloc \(\) from /lib/tls/libc\.so\.6
\(gdb\) where
\#0  0xb749fa8e in \_int\_malloc \(\) from /lib/tls/libc\.so\.6
\#1  0xb749ee9d in malloc \(\) from /lib/tls/libc\.so\.6
\#2  0x080d3b77 in Perl\_savesharedpv \(my\_perl=0x8347568\,
&nbsp;    pv=0x841a5ec "IO&#8203;::Handle"\) at util\.c&#8203;:820
\#3  0x080aa378 in Perl\_newCONSTSUB \(my\_perl=0x8347568\, stash=0x8414700\,
&nbsp;    name=0xb5efd321 "SEEK\_CUR"\, sv=0x8403b08\) at op\.c&#8203;:4610
\#4  0xb5efcd9b in boot\_IO \(my\_perl=0x8347568\, cv=0x84b5a48\) at IO\.xs&#8203;:497
\#5  0x080fa824 in Perl\_pp\_entersub \(my\_perl=0x8347568\) at pp\_hot\.c&#8203;:2788
\#6  0x080d1d9c in Perl\_runops\_debug \(my\_perl=0x8347568\) at dump\.c&#8203;:1597
\#7  0x0806841a in S\_call\_body \(my\_perl=0x8347568\, myop=0xb68ffa10\,
&nbsp;    is\_eval=0 '\\0'\) at perl\.c&#8203;:2617
\#8  0x08067ef8 in Perl\_call\_sv \(my\_perl=0x8347568\, sv=0x84b5948\, flags=4\)
&nbsp;    at perl\.c&#8203;:2546
\#9  0xb75e640a in Perl\_ithread\_run \(arg=0x8347520\) at threads\.xs&#8203;:301
\#10 0xb756adec in start\_thread \(\) from /lib/tls/libpthread\.so\.0
\#11 0xb750aa2a in clone \(\) from /lib/tls/libc\.so\.6

backtrace from blead compiled \-O2

\(gdb\) where
\#0  0xb74a02c0 in malloc\_consolidate \(\) from /lib/tls/libc\.so\.6
\#1  0xb749faf9 in \_int\_malloc \(\) from /lib/tls/libc\.so\.6
\#2  0xb749ee9d in malloc \(\) from /lib/tls/libc\.so\.6
\#3  0x080b071f in Perl\_safesysmalloc \(\)
\#4  0x080bfe1b in S\_hsplit \(\)
\#5  0x080c0391 in S\_share\_hek\_flags \(\)
\#6  0x080c123e in S\_hv\_fetch\_common \(\)
\#7  0x080c1211 in S\_hv\_fetch\_common \(\)
\#8  0x080c1e4e in Perl\_hv\_fetch \(\)
\#9  0x0806abad in Perl\_gv\_fetchpvn\_flags \(\)
\#10 0x0806bf33 in Perl\_gv\_fetchpv \(\)
\#11 0x0808e475 in Perl\_newXS \(\)
\#12 0xb5efdb20 in ?? \(\) from lib/auto/IO/IO\.so
\#13 0x00000002 in ?? \(\)
\#14 0x0000000d in ?? \(\)
\#15 0x083d34b8 in ?? \(\)
\#16 0x082737d8 in ?? \(\)
\#17 0x00000010 in ?? \(\)
\#18 0x082737a0 in ?? \(\)
\#19 0x082dd3c0 in ?? \(\)
\#20 0x082bc428 in ?? \(\)
\#21 0xb68ff858 in ?? \(\)
\#22 0x0808eb33 in Perl\_newCONSTSUB \(\)
Previous frame inner to this frame \(corrupt stack?\)

From 5\.8\.7 compiled \-O2

\(gdb\) where
\#0  0xb749fa8e in \_int\_malloc \(\) from /lib/tls/libc\.so\.6
\#1  0xb749ee9d in malloc \(\) from /lib/tls/libc\.so\.6
\#2  0x080ad937 in Perl\_savesharedpv \(\)
\#3  0x0808d698 in Perl\_newCONSTSUB \(\)
\#4  0xb5f94441 in boot\_IO \(\) from lib/auto/IO/IO\.so
\#5  0x080c5b6d in Perl\_pp\_entersub \(\)
\#6  0x080be7e9 in Perl\_runops\_standard \(\)
\#7  0x080641ba in Perl\_call\_sv \(\)
\#8  0xb7407de0 in Perl\_ithread\_run \(\) from lib/auto/threads/threads\.so
\#9  0xb756adec in start\_thread \(\) from /lib/tls/libpthread\.so\.0
\#10 0xb750aa2a in clone \(\) from /lib/tls/libc\.so\.6

\(gdb\) where
\#0  0xb749fa8e in \_int\_malloc \(\) from /lib/tls/libc\.so\.6
\#1  0xb749ee9d in malloc \(\) from /lib/tls/libc\.so\.6
\#2  0x080ac90f in Perl\_safesysmalloc \(\)
\#3  0x080cac1e in Perl\_sv\_grow \(\)
\#4  0x080cafe6 in Perl\_sv\_setpv \(\)
\#5  0x0808d6fa in Perl\_newCONSTSUB \(\)
\#6  0xb5dfd3df in boot\_IO \(\) from lib/auto/IO/IO\.so
\#7  0x080c5b6d in Perl\_pp\_entersub \(\)
\#8  0x080be7e9 in Perl\_runops\_standard \(\)
\#9  0x080641ba in Perl\_call\_sv \(\)
\#10 0xb7407de0 in Perl\_ithread\_run \(\) from lib/auto/threads/threads\.so
\#11 0xb756adec in start\_thread \(\) from /lib/tls/libpthread\.so\.0
\#12 0xb750aa2a in clone \(\) from /lib/tls/libc\.so\.6

So I assume that all this in\-malloc\(\) corruption comes from scribbling over
memory at some other point in some other thread\. Reasonable?

Nicholas Clark

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Sep 05\, 2005 at 04&#8203;:18&#8203;:11PM \+0100\, Nicholas Clark wrote&#8203;:
> On Mon\, Sep 05\, 2005 at 01&#8203;:42&#8203;:52AM \-0700\, ikegami @&#8203; ni\. aist\. go\. jp wrote&#8203;:
> 
> > On dual Opteron \(2 GHz\) machine\, perl 5\.8\.7 frequently causes
> > segmentation fault with the following code snippet\.
> > 
> >         \#\!/usr/bin/perl
> >         use threads;
> >         use threads&#8203;::shared;
> >         
> >         sub socket \(\) \{
> >           require IO;
> >           return;
> >         \}
> >         
> >         my $s = new threads \\&socket;
> >         my $c = new threads \\&socket;
> >         
> >         $s\->join;
> >         $c\->join;
> > 
> > It is not reproducible by 100 %\, and may not be reproducible on
> > slow/single\-processor machines\.  As a workaround\, put 'use IO'
> > somewhere\.  A stack trace taken from core file follows\.
> 
> It's more like 1\-5% reproducible on x86 Linux \(this was a dual CPU machine\)

It's more reproducable on a 4\-CPU x86\_64 box\.

It turns out that IO\.xs's BOOT section calls newCONSTSUB\(\)\, and
newCONSTSUB\(\) isn't threadsafe\, as it messes with fields of PL\_curcop\,
while ops are shared between threads\. Whoops\.

Not sure yet what the best fix is\, or how pervasive this problem is \(ie
what other code \(if any\) diddles with PL\_curcop fields?\)

\-\- 
"Do not dabble in paradox\, Edward\, it puts you in danger of fortuitous
wit\." \-\- Lady Croom \- Arcadia

**Comment by p5pRT** [comment]
### From @nwc10

On Mon\, Jan 09\, 2006 at 01&#8203;:09&#8203;:32AM \+0000\, Dave Mitchell wrote&#8203;:

> It turns out that IO\.xs's BOOT section calls newCONSTSUB\(\)\, and
> newCONSTSUB\(\) isn't threadsafe\, as it messes with fields of PL\_curcop\,
> while ops are shared between threads\. Whoops\.
> 
> Not sure yet what the best fix is\, or how pervasive this problem is \(ie
> what other code \(if any\) diddles with PL\_curcop fields?\)

I think a solution would be to rewrite newCONSTSUB so that it doesn't
use any of PL\_curcop \(etc\)\. It's doing a rather simple job\, and currently
it seems that it's calling into a complex function to get its work done\.
I assume that it can be turned inside out\, so that either newXS calls it\,
or both call a shared function that does what it needs\, but I've not looked
into the practicality of this\.

Nicholas Clark

**Comment by p5pRT** [comment]
### From p5p@spam.wizbit.be

On Mon Sep 05 01&#8203;:42&#8203;:51 2005\, ikegami@&#8203;ni\.aist\.go\.jp wrote&#8203;:
> This is a bug report for perl from ikegami@&#8203;p06cmp000\.asc\.hpcc\.jp\,
> generated with the help of perlbug 1\.35 running under perl v5\.8\.7\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> 
> On dual Opteron \(2 GHz\) machine\, perl 5\.8\.7 frequently causes
> segmentation fault with the following code snippet\.
> 
>         \#\!/usr/bin/perl
>         use threads;
>         use threads&#8203;::shared;
> 
>         sub socket \(\) \{
>           require IO;
>           return;
>         \}
> 
>         my $s = new threads \\&socket;
>         my $c = new threads \\&socket;
> 
>         $s\->join;
>         $c\->join;
> 
> It is not reproducible by 100 %\, and may not be reproducible on
> slow/single\-processor machines\.  As a workaround\, put 'use IO'
> somewhere\.  A stack trace taken from core file follows\.
> 

Re\-tested this with&#8203;:

perl\-5\.8\.8&#8203;: segfault
perl\-5\.8\.x&#8203;: no segfault
perl\-5\.10&#8203;: no segfault
perl\-blead&#8203;: no segfault

by using&#8203;:

perl \-wle 'for \(1 \.\. 5000\) \{ system\("\./perl \-Ilib /tmp/rt\-37076\.pl"\); \}'

So I'm assuming this got resolved\.

Can someone else test as well?


Kind regards\,

Bram

**Comment by p5pRT** [comment]
p5p@spam.wizbit.be - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From p5p@spam.wizbit.be

This was fixed by Change 32091\.

http&#8203;://public\.activestate\.com/cgi\-bin/perlbrowse/p/32091
Change 32091 by davem@&#8203;davem\-pigeon on 2007/10/10 15&#8203;:03&#8203;:16

&nbsp;    newCONTSUB\(\) wasn't thread\-safe \(\[perl \#45053\]\)
