### ISSUE TITLE
Data crash when executing substitution on the Perl debugger

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8108]
Migrated from [rt.perl.org#37144](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=37144) (status was 'resolved')

Searchable as RT37144$

**Comment by p5pRT** [comment]
### From manabe@kodensha.jp

This is a bug report for perl from manabe@&#8203;kodensha\.jp\,
generated with the help of perlbug 1\.35 running under perl v5\.8\.7\.

\# Here is a sample code for what's happening
for \($i = 0; $i \< 10; \+\+$i\) \{
 $temp = "\\x\{100\}X";  \# X is an arbitrary character; \\x\{100\} is an arbitrary character over \\x\{100\}
 $temp =~ s/\[^X\]\+//;  \# data crash on the second \(or so\) iteration when run on the debugger
&nbsp;       \# or sometimes the Perl itself crashes;
&nbsp;       \# or sometimes it simply do nothing \(no replacement\)
&nbsp;       \# It's quite unpredictable\.
\}


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=critical


---
Site configuration information for perl v5\.8\.7&#8203;:

Configured by builder at Mon Jun  6 13&#8203;:36&#8203;:05 2005\.

Summary of my perl5 \(revision 5 version 8 subversion 7\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=MSWin32\, osvers=5\.0\, archname=MSWin32\-x86\-multi\-thread
&nbsp;    uname=''
&nbsp;    config\_args='undef'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=undef
&nbsp;    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cl'\, ccflags
='\-nologo \-Gf \-W3 \-MD \-Zi \-DNDEBUG \-O1 \-DWIN32 \-D\_CONSOLE \-DNO\_STRICT \-DHAVE\_DES\_FCRYPT \-DBUILT\_BY\_ACTIVESTATE \-DNO\_HASH\_SEED \-DUSE\_
SITECUSTOMIZE \-DPERL\_IMPLICIT\_CONTEXT \-DPERL\_IMPLICIT\_SYS \-DUSE\_PERLIO \-DPERL\_MSVCRT\_READFIX'\,
&nbsp;    optimize='\-MD \-Zi \-DNDEBUG \-O1'\,
&nbsp;    cppflags='\-DWIN32'
&nbsp;    ccversion='12\.00\.8804'\, gccversion=''\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=undef\, longlongsize=8\, d\_longdbl=define\, longdblsize=10
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='\_\_int64'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='link'\, ldflags ='\-nologo \-nodefaultlib \-debug \-opt&#8203;:ref\,icf  \-libpath&#8203;:"I&#8203;:\\Perl\\lib\\CORE"  \-machine&#8203;:x86'
&nbsp;    libpth=\\lib
&nbsp;    libs=  oldnames\.lib kernel32\.lib user32\.lib gdi32\.lib winspool\.lib  comdlg32\.lib advapi32\.lib shell32\.lib ole32\.lib oleaut32\.lib
netapi32\.lib uuid\.lib ws2\_32\.lib mpr\.lib winmm\.lib  version\.lib odbc32\.lib odbccp32\.lib msvcrt\.lib
&nbsp;    perllibs=  oldnames\.lib kernel32\.lib user32\.lib gdi32\.lib winspool\.lib  comdlg32\.lib advapi32\.lib shell32\.lib ole32\.lib
oleaut32\.lib  netapi32\.lib uuid\.lib ws2\_32\.lib mpr\.lib winmm\.lib  version\.lib odbc32\.lib odbccp32\.lib msvcrt\.lib
&nbsp;    libc=msvcrt\.lib\, so=dll\, useshrplib=yes\, libperl=perl58\.lib
&nbsp;    gnulibc\_version='undef'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_win32\.xs\, dlext=dll\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags=' '\, lddlflags='\-dll \-nologo \-nodefaultlib \-debug \-opt&#8203;:ref\,icf  \-libpath&#8203;:"I&#8203;:\\Perl\\lib\\CORE"  \-machine&#8203;:x86'

Locally applied patches&#8203;:
&nbsp;    ACTIVEPERL\_LOCAL\_PATCHES\_ENTRY
&nbsp;    \#  if \!defined\(PERL\_DARWIN\)
&nbsp;    Iin\_load\_module moved for compatibility with build 806
&nbsp;    \#  endif
&nbsp;    \#  if defined\(\_\_hpux\)
&nbsp;    Avoid signal flag SA\_RESTART for older versions of HP\-UX
&nbsp;    \#  endif
&nbsp;    PerlEx hacks for CGI&#8203;::Carp
&nbsp;    Less verbose ExtUtils&#8203;::Install and Pod&#8203;::Find
&nbsp;    instmodsh upgraded from ExtUtils\-MakeMaker\-6\.25
&nbsp;    24699 ICMP\_UNREACHABLE handling in Net&#8203;::Ping
&nbsp;    21540 Fix backward\-compatibility issues in if\.pm



---
@&#8203;INC for perl v5\.8\.7&#8203;:
&nbsp;    I&#8203;:/Perl/lib
&nbsp;    I&#8203;:/Perl/site/lib
&nbsp;    \.



---
Environment for perl v5\.8\.7&#8203;:
&nbsp;    HOME \(unset\)
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=I&#8203;:\\Perl\\bin\\;i&#8203;:\\program
files\\imagemagick\-6\.0\.7\-q16;C&#8203;:\\WINNT\\system32;C&#8203;:\\WINNT;C&#8203;:\\WINNT\\System32\\Wbem;I&#8203;:\\perl\\bin;I&#8203;:\\jperl\\5\.00503\\bin\\MSWin32\-x86;E&#8203;:\\cygwin
\\bin;C&#8203;:\\Fonix\\FRE\\Win32\\Lib;C&#8203;:\\gs\\gs8\.14\\bin;C&#8203;:\\gs\\gs8\.14\\lib;C&#8203;:\\Program Files\\Microsoft Visual Studio\\Common\\Tools\\WinNT;C&#8203;:\\Program
Files\\Microsoft Visual Studio\\Common\\MSDev98\\Bin;C&#8203;:\\Program Files\\Microsoft Visual Studio\\Common\\Tools;C&#8203;:\\Program Files\\Microsoft
Visual Studio\\VC98\\bin;I&#8203;:\\EmEditor3;I&#8203;:\\Program Files\\kakasi\\bin;
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL \(unset\)

**Comment by p5pRT** [comment]
### From schubiger@cpan.org

> \[manabe \- Mon Sep 12 00&#8203;:21&#8203;:47 2005\]&#8203;:
> \# Here is a sample code for what's happening
> for \($i = 0; $i \< 10; \+\+$i\) \{
>  $temp = "\\x\{100\}X";  \# X is an arbitrary character; \\x\{100\} is an
> arbitrary character over \\x\{100\}
>  $temp =~ s/\[^X\]\+//;  \# data crash on the second \(or so\) iteration
> when run on the debugger
>        \# or sometimes the Perl itself crashes;
>        \# or sometimes it simply do nothing \(no replacement\)
>        \# It's quite unpredictable\.
> \}

This is likely to be a Windows related bug\, as I could not reproduce
it with Perl\-5\.8\.5 \- 5\.8\.7 nor with Bleadperl on OpenBSD 3\.6 with
more than a dozen runs per each version\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, Oct 01\, 2005 at 10&#8203;:49&#8203;:24AM \-0700\, Steven Schubiger via RT wrote&#8203;:
> > \[manabe \- Mon Sep 12 00&#8203;:21&#8203;:47 2005\]&#8203;:
> > \# Here is a sample code for what's happening
> > for \($i = 0; $i \< 10; \+\+$i\) \{
> >  $temp = "\\x\{100\}X";  \# X is an arbitrary character; \\x\{100\} is an
> > arbitrary character over \\x\{100\}
> >  $temp =~ s/\[^X\]\+//;  \# data crash on the second \(or so\) iteration
> > when run on the debugger
> >        \# or sometimes the Perl itself crashes;
> >        \# or sometimes it simply do nothing \(no replacement\)
> >        \# It's quite unpredictable\.
> > \}
> 
> This is likely to be a Windows related bug\, as I could not reproduce
> it with Perl\-5\.8\.5 \- 5\.8\.7 nor with Bleadperl on OpenBSD 3\.6 with
> more than a dozen runs per each version\.

I can get it to crash with bleedperl on linux&#8203;:

$ gdb \./perl

\[snip\]

\(gdb\) run  \-Ilib \-d /tmp/p

\[snip\]

main&#8203;::\(/tmp/p&#8203;:9\)&#8203;:       \}
&nbsp;  DB\<1> c

Program received signal SIGSEGV\, Segmentation fault\.
\[Switching to Thread \-1208162624 \(LWP 3509\)\]
0x00a97e4c in memmove \(\) from /lib/tls/libc\.so\.6
\(gdb\) bt
\#0  0x00a97e4c in memmove \(\) from /lib/tls/libc\.so\.6
\#1  0x080f76f4 in Perl\_sv\_setsv\_flags \(my\_perl=0x81b8008\, dstr=0x838c3b0\,
&nbsp;    sstr=0x81d4728\, flags=0x2\) at sv\.c&#8203;:4123
\#2  0x080e310f in Perl\_pp\_sassign \(my\_perl=0x81b8008\) at pp\_hot\.c&#8203;:118
\#3  0x080c850a in Perl\_runops\_debug \(my\_perl=0x81b8008\) at dump\.c&#8203;:1597
\#4  0x08066ce4 in S\_run\_body \(my\_perl=0x81b8008\, oldscope=0x1\) at perl\.c&#8203;:2272
\#5  0x0806675e in perl\_run \(my\_perl=0x81b8008\) at perl\.c&#8203;:2204
\#6  0x08060501 in main \(argc=0x4\, argv=0xbfff5084\, env=0xbfff5098\)
&nbsp;    at perlmain\.c&#8203;:103

&nbsp;     
\-\- 
Thank God I'm an atheist\.\.\.\.\.

**Comment by p5pRT** [comment]
### From @smpeters

> \[davem@&#8203;iabyn\.com \- Sun Oct 02 05&#8203;:05&#8203;:14 2005\]&#8203;:
> 
> On Sat\, Oct 01\, 2005 at 10&#8203;:49&#8203;:24AM \-0700\, Steven Schubiger via RT
> wrote&#8203;:
> > > \[manabe \- Mon Sep 12 00&#8203;:21&#8203;:47 2005\]&#8203;:
> > > \# Here is a sample code for what's happening
> > > for \($i = 0; $i \< 10; \+\+$i\) \{
> > >  $temp = "\\x\{100\}X";  \# X is an arbitrary character; \\x\{100\} is an
> > > arbitrary character over \\x\{100\}
> > >  $temp =~ s/\[^X\]\+//;  \# data crash on the second \(or so\) iteration
> > > when run on the debugger
> > >        \# or sometimes the Perl itself crashes;
> > >        \# or sometimes it simply do nothing \(no replacement\)
> > >        \# It's quite unpredictable\.
> > > \}
> >
> > This is likely to be a Windows related bug\, as I could not reproduce
> > it with Perl\-5\.8\.5 \- 5\.8\.7 nor with Bleadperl on OpenBSD 3\.6 with
> > more than a dozen runs per each version\.
> 
> I can get it to crash with bleedperl on linux&#8203;:
> 
> $ gdb \./perl
> 
> \[snip\]
> 
> \(gdb\) run  \-Ilib \-d /tmp/p
> 
> \[snip\]
> 
> main&#8203;::\(/tmp/p&#8203;:9\)&#8203;:       \}
>   DB\<1> c
> 
> Program received signal SIGSEGV\, Segmentation fault\.
> \[Switching to Thread \-1208162624 \(LWP 3509\)\]
> 0x00a97e4c in memmove \(\) from /lib/tls/libc\.so\.6
> \(gdb\) bt
> \#0  0x00a97e4c in memmove \(\) from /lib/tls/libc\.so\.6
> \#1  0x080f76f4 in Perl\_sv\_setsv\_flags \(my\_perl=0x81b8008\,
> dstr=0x838c3b0\,
>     sstr=0x81d4728\, flags=0x2\) at sv\.c&#8203;:4123
> \#2  0x080e310f in Perl\_pp\_sassign \(my\_perl=0x81b8008\) at pp\_hot\.c&#8203;:118
> \#3  0x080c850a in Perl\_runops\_debug \(my\_perl=0x81b8008\) at dump\.c&#8203;:1597
> \#4  0x08066ce4 in S\_run\_body \(my\_perl=0x81b8008\, oldscope=0x1\) at
> perl\.c&#8203;:2272
> \#5  0x0806675e in perl\_run \(my\_perl=0x81b8008\) at perl\.c&#8203;:2204
> \#6  0x08060501 in main \(argc=0x4\, argv=0xbfff5084\, env=0xbfff5098\)
>     at perlmain\.c&#8203;:103
> 
> 
> 

This problem seems to have been fixed with change \#26228\.

Change 26228 by nicholas@&#8203;nicholas\-switch on 2005/11/30 13&#8203;:55&#8203;:05

&nbsp;    The regexp engine should check SV flags rather than SV type for
&nbsp;    determining if something is a reference\, because under the debugger
&nbsp;    the value returned by the swash code is SVt\_PVMG\.
&nbsp;    Not doing this has the side effect of repeatedly reassigning the
&nbsp;    same array element\, which causes destructors to fire on the reassignment
&nbsp;    which in turn causes &utf8&#8203;::DESTROY to run outside of the pseudo\-safety
&nbsp;    of save\_re\_context\, which under the debugger involves re\-entering the
&nbsp;    regexp engine\, which causes corruption of the regexp engine's global
&nbsp;    state\.

Affected files \.\.\.

\.\.\. //depot/perl/regexec\.c\#363 edit

Differences \.\.\.

==== //depot/perl/regexec\.c\#363 \(text\) ====

@&#8203;@&#8203; \-4668\,7 \+4668\,7 @&#8203;@&#8203;
&nbsp;          \* documentation of these array elements\. \*/
 
&nbsp;         si = \*ary;
\-        a  = SvTYPE\(ary\[1\]\) == SVt\_RV   ? &ary\[1\] : 0;
\+        a  = SvROK\(ary\[1\]\) ? &ary\[1\] : 0;
&nbsp;         b  = SvTYPE\(ary\[2\]\) == SVt\_PVAV ? &ary\[2\] : 0;
 
&nbsp;         if \(a\)

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'resolved'
