### ISSUE TITLE
Core dump when calling Devel::Peek::Dump() on a subroutine

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8198]
Migrated from [rt.perl.org#37636](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=37636) (status was 'resolved')

Searchable as RT37636$

**Comment by p5pRT** [comment]
### From @smpeters

When attempting to look at the return of a subroutine with Devel&#8203;::Peek\, I
got a SEGV using bleadperl\.  Below is the backtrace from gdb\.

> \./perl \-MDevel&#8203;::Peek \-wle'@&#8203;foo=qw\(foo bar baz\);sub foo\{@&#8203;foo\}; print Dump foo;'
Segmentation fault \(core dumped\) 

With Perl\-5\.8\.6\, I get an error message instead\.

> perl \-MDevel&#8203;::Peek \-wle'@&#8203;foo=qw\(foo bar baz\);sub foo\{@&#8203;foo\}; print Dump foo;'
Usage&#8203;: Devel&#8203;::Peek&#8203;::Dump\(sv\, lim=4\) at \-e line 1\.


\#0  0x09ed238d in strlen \(\) from /usr/lib/libc\.so\.38\.2
\(gdb\) bt
\#0  0x09ed238d in strlen \(\) from /usr/lib/libc\.so\.38\.2
\#1  0x1c0a9b27 in Perl\_sv\_vcatpvfn \(sv=0x7fe3d9e0\, pat=0x276af6b6 "%s&#8203;::%s"\,
&nbsp;    patlen=6\, args=0xcfbcad50\, svargs=0x0\, svmax=0\, maybe\_tainted=0x0\) at sv\.c&#8203;:8863
\#2  0x1c0a83a1 in Perl\_sv\_vsetpvfn \(sv=0x7fe3d9e0\, pat=0x276af6b6 "%s&#8203;::%s"\,
&nbsp;    patlen=6\, args=0xcfbcad50\, svargs=0x0\, svmax=0\, maybe\_tainted=0x0\) at sv\.c&#8203;:8341
\#3  0x1c0773d7 in Perl\_vform \(pat=0x276af6b6 "%s&#8203;::%s"\, args=0xcfbcad50\)
&nbsp;    at util\.c&#8203;:925
\#4  0x1c077398 in Perl\_form \(pat=0x276af6b6 "%s&#8203;::%s"\) at util\.c&#8203;:916
\#5  0x076b15a4 in boot\_Devel\_\_Peek \(\)
&nbsp;   from /usr/local/lib/perl5/5\.9\.3/OpenBSD\.i386\-openbsd/auto/Devel/Peek/Peek\.so
\#6  0x1c095e0f in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:2815
\#7  0x1c0757bb in Perl\_runops\_debug \(\) at dump\.c&#8203;:1597
\#8  0x1c01b3c0 in S\_call\_body \(myop=0xcfbcaf00\, is\_eval=0 '\\0'\) at perl\.c&#8203;:2641
\#9  0x1c01aff9 in Perl\_call\_sv \(sv=0x861d3ee0\, flags=6\) at perl\.c&#8203;:2570
\#10 0x1c01f476 in S\_call\_list\_body \(cv=0x861d3ee0\) at perl\.c&#8203;:5160
\#11 0x1c01f077 in Perl\_call\_list \(oldscope=2\, paramList=0x861d3f80\) at perl\.c&#8203;:5099
\#12 0x1c052fc8 in Perl\_newATTRSUB \(floor=112\, o=0x88e14260\, proto=0x0\, attrs=0x0\,
&nbsp;    block=0x88e14220\) at op\.c&#8203;:4549
\#13 0x1c04eb2c in Perl\_utilize \(aver=1\, floor=112\, version=0x0\, idop=0x88e14120\,
&nbsp;    arg=0x0\) at op\.c&#8203;:3086
\#14 0x1c04619a in Perl\_yyparse \(\) at perly\.y&#8203;:383
\#15 0x1c01a04f in S\_parse\_body \(env=0x0\, xsinit=0x1c015be6 \<xs\_init>\) at perl\.c&#8203;:2157
\#16 0x1c019170 in perl\_parse \(my\_perl=0x81156030\, xsinit=0x1c015be6 \<xs\_init>\,
&nbsp;    argc=3\, argv=0xcfbcb3ec\, env=0x0\) at perl\.c&#8203;:1554
\#17 0x1c015b99 in main \(argc=3\, argv=0xcfbcb3ec\, env=0xcfbcb3fc\) at perlmain\.c&#8203;:101


Summary of my perl5 \(revision 5 version 9 subversion 3 patch 26044\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=openbsd\, osvers=3\.8\, archname=OpenBSD\.i386\-openbsd
&nbsp;    uname='openbsd mccoy\.peters\.homeunix\.org 3\.8 generic\#207 i386 '
&nbsp;    config\_args='\-des \-Dusedevel \-Doptimize=\-g'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-I/usr/local/include'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='3\.3\.5 \(propolice\)'\, gccosandvers='openbsd3\.8'
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags ='\-Wl\,\-E  \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib
&nbsp;    libs=\-lm \-lutil \-lc
&nbsp;    perllibs=\-lm \-lutil \-lc
&nbsp;    libc=/usr/lib/libc\.so\.38\.2\, so=so\, useshrplib=false\, libperl=libperl\.a
> \./myconfig
Summary of my perl5 \(revision 5 version 9 subversion 3 patch 26044\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=openbsd\, osvers=3\.8\, archname=OpenBSD\.i386\-openbsd
&nbsp;    uname='openbsd mccoy\.peters\.homeunix\.org 3\.8 generic\#207 i386 '
&nbsp;    config\_args='\-des \-Dusedevel \-Doptimize=\-g'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-I/usr/local/include'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='3\.3\.5 \(propolice\)'\, gccosandvers='openbsd3\.8'
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags ='\-Wl\,\-E  \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib
&nbsp;    libs=\-lm \-lutil \-lc
&nbsp;    perllibs=\-lm \-lutil \-lc
&nbsp;    libc=/usr/lib/libc\.so\.38\.2\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags='\-DPIC \-fPIC '\, lddlflags='\-shared \-fPIC  \-L/usr/local/lib'

**Comment by p5pRT** [comment]
### From @ysth

On Tue\, Nov 08\, 2005 at 05&#8203;:01&#8203;:27AM \-0800\, Steve Peters wrote&#8203;:
> When attempting to look at the return of a subroutine with Devel&#8203;::Peek\, I
> got a SEGV using bleadperl\.  Below is the backtrace from gdb\.
> 
> > \./perl \-MDevel&#8203;::Peek \-wle'@&#8203;foo=qw\(foo bar baz\);sub foo\{@&#8203;foo\}; print Dump foo;'
> Segmentation fault \(core dumped\) 

WFM; I have a feeling you wanted an \-Ilib before that \-MDevel&#8203;::Peek; I
wouldn't trust any bleadperl to necessarily work with an older bleadperl
or 5\.9\.x\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @smpeters

> \[ysth \- Tue Nov 08 14&#8203;:33&#8203;:20 2005\]&#8203;:
> 
> On Tue\, Nov 08\, 2005 at 05&#8203;:01&#8203;:27AM \-0800\, Steve Peters wrote&#8203;:
> > When attempting to look at the return of a subroutine with
> Devel&#8203;::Peek\, I
> > got a SEGV using bleadperl\.  Below is the backtrace from gdb\.
> >
> > > \./perl \-MDevel&#8203;::Peek \-wle'@&#8203;foo=qw\(foo bar baz\);sub foo\{@&#8203;foo\};
> print Dump foo;'
> > Segmentation fault \(core dumped\)
> 
> WFM; I have a feeling you wanted an \-Ilib before that \-MDevel&#8203;::Peek; I
> wouldn't trust any bleadperl to necessarily work with an older
> bleadperl
> or 5\.9\.x\.
> 
D'oh\!  Closed :\-/

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'resolved'
