### ISSUE TITLE
many threads => various crashes

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8203]
Migrated from [rt.perl.org#37652](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=37652) (status was 'open')

Searchable as RT37652$

**Comment by p5pRT** [comment]
### From zefram@fysh.org

#### Created by zefram@fysh.org



I have a multithreaded server\, using the "threads" interface\, that fires
off a new thread to handle each client\.  It typically has between zero
and two clients connected at once\, and gets a new client connection
every couple of seconds\.  I've found that after running for a few hours
\(time is variable\) it crashes\, in a variety of ways\.  I have seen it
terminate\, and I have also seen it lock up completely\, apparently during
thread creation&#8203;: the parent thread uses 99% CPU and never gets past the
thread creation instruction\, while the child thread is created at the
Unix level but I think never does its work\.

I have a test program that simulates this thread usage pattern at a much
faster speed&#8203;:

\#\#\# t0 start \#\#\#
\#\!/usr/bin/perl
use warnings;
use strict;
use threads;
use threads&#8203;::shared;
my $n : shared = 0;
while\(1\) \{
&nbsp;    async \{
&nbsp;        threads\->self\->detach;
&nbsp;        threads\->yield;
&nbsp;        lock $n;
&nbsp;        threads\->yield;
&nbsp;        print "thread $n\\n";
&nbsp;        threads\->yield;
&nbsp;        $n\+\+;
&nbsp;        threads\->yield;
&nbsp;    \};
&nbsp;    threads\->yield;
\}
\#\#\# t0 end \#\#\#

When running this program\, I've seen it abort in various ways&#8203;:

$ \./t0
thread 0
\[\.\.\.\]
thread 26117
\*\*\* glibc detected \*\*\* corrupted double\-linked list&#8203;: 0x401cd858 \*\*\*
zsh&#8203;: abort      \./t0
$ \./t0
thread 0
\[\.\.\.\]
thread 1770
Attempt to free non\-existent shared string '\_\<th'\, Perl interpreter&#8203;: 0x410090c0 during global destruction\.
Unbalanced string table refcount&#8203;: \(1\) for "\_\<th" during global destruction\.
\*\*\* glibc detected \*\*\* corrupted double\-linked list&#8203;: 0x082a0960 \*\*\*
zsh&#8203;: abort      \./t0
$

I've also seen it abort with these error messages from glibc&#8203;:

\*\*\* glibc detected \*\*\* free\(\)&#8203;: invalid next size \(fast\)&#8203;: 0x0819cef8 \*\*\*
\*\*\* glibc detected \*\*\* double free or corruption \(fasttop\)&#8203;: 0x0819cef8 \*\*\*
\*\*\* glibc detected \*\*\* free\(\)&#8203;: invalid pointer&#8203;: 0x40dbca64 \*\*\*

If the read and incrementation of $n are commented out\, I see it crash in
the same kinds of way\, and also sometimes crash with a segmentation fault\.
I've never seen it lock up as my real program does\.

I've run this test program with Perl 5\.8\.6 on a Gentoo Linux machine\.
The original program was run with Perl 5\.8\.4 on a Debian \(stable\) Linux
machine\, with an older version of the Linux kernel\.  The Debian machine
is a commercially sensitive server\, so I can't run test code on it\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl v5.8.6:

Configured by Gentoo at Wed Sep 28 16:05:01 BST 2005.

Summary of my perl5 (revision 5 version 8 subversion 6) configuration:
  Platform:
    osname=linux, osvers=2.6.12-gentoo-r4, archname=i686-linux-thread-multi
    uname='linux localhost 2.6.12-gentoo-r4 #3 smp thu jul 21 11:11:50 bst 2005 i686 intel(r) pentium(r) 4 cpu 3.20ghz genuineintel gnulinux '
    config_args='-des -Darchname=i686-linux-thread -Dcccdlflags=-fPIC -Dccdlflags=-rdynamic -Dcc=i686-pc-linux-gnu-gcc -Dprefix=/usr -Dvendorprefix=/usr -Dsiteprefix=/usr -Dlocincpth=  -Doptimize=-O3 -march=pentium4 -mtune=pentium4 --force-addr -momit-leaf-frame-pointer -fomit-frame-pointer -ftracer -pipe -Duselargefiles -Dd_semctl_semun -Dscriptdir=/usr/bin -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 -Dinstallman1dir=/usr/share/man/man1 -Dinstallman3dir=/var/tmp/portage/perl-5.8.6-r6/image//usr/share/man/man3 -Dman1ext=1 -Dman3ext=3pm -Dinc_version_list=5.8.0 5.8.0/i686-linux-thread-multi 5.8.2 5.8.2/i686-linux-thread-multi 5.8.4 5.8.4/i686-linux-thread-multi 5.8.5 5.8.5/i686-linux-thread-multi  -Dcf_by=Gentoo -Ud_csh -Dusethreads -Di_ndbm -Di_gdbm -Di_db'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='i686-pc-linux-gnu-gcc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -fno-strict-aliasing -pipe -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O3 -march=pentium4 -mtune=pentium4 --force-addr -momit-leaf-frame-pointer -fomit-frame-pointer -ftracer -pipe',
    cppflags='-DPERL5 -D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -fno-strict-aliasing -pipe'
    ccversion='', gccversion='3.4.4 (Gentoo 3.4.4-r1, ssp-3.4.4-1.0, pie-8.7.8)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='i686-pc-linux-gnu-gcc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lpthread -lnsl -lndbm -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/libc-2.3.5.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.3.5'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.6:
    /etc/perl
    /usr/lib/perl5/site_perl/5.8.6/i686-linux-thread-multi
    /usr/lib/perl5/site_perl/5.8.6
    /usr/lib/perl5/site_perl/5.8.5
    /usr/lib/perl5/site_perl/5.8.5/i686-linux-thread-multi
    /usr/lib/perl5/site_perl
    /usr/lib/perl5/vendor_perl/5.8.6/i686-linux-thread-multi
    /usr/lib/perl5/vendor_perl/5.8.6
    /usr/lib/perl5/vendor_perl/5.8.5
    /usr/lib/perl5/vendor_perl/5.8.5/i686-linux-thread-multi
    /usr/lib/perl5/vendor_perl
    /usr/lib/perl5/5.8.6/i686-linux-thread-multi
    /usr/lib/perl5/5.8.6
    /usr/local/lib/site_perl
    .


Environment for perl v5.8.6:
    HOME=/home/zefram
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/zefram/pub/i686-pc-linux-gnu/bin:/home/zefram/pub/common/bin:/usr/bin:/usr/X11R6/bin:/bin:/usr/local/bin:/usr/games:/opt/exim/bin:/opt/opera/bin:/opt/sun-jdk-1.4.2.09/bin:/opt/tomcat5/bin
    PERL_BADLANG (unset)
    SHELL=/home/zefram/pub/i686-pc-linux-gnu/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Additional information&#8203;: I've had a chance to analyse the program I started
with in its locked\-up state \(the crash type that the test program didn't
exhibit\)\.  The purpose of the program is to maintain high\-value encryption
keys in RAM\, so unfortunately taking a core dump was out of the question\.

The program locked up with exactly one child thread in existence at
the Unix level\.  From log entries it now appears that this last thread
created \*did\* perform its intended work before locking up\.  Attaching to
the child with gdb\, I got this stack trace&#8203;:

\#0  0x40048604 in \_\_pthread\_sigsuspend \(\) from /lib/libpthread\.so\.0
\#1  0x400483c8 in \_\_pthread\_wait\_for\_restart\_signal \(\)
&nbsp;   from /lib/libpthread\.so\.0
\#2  0x40049d99 in \_\_pthread\_alt\_lock \(\) from /lib/libpthread\.so\.0
\#3  0x40046ba5 in pthread\_mutex\_lock \(\) from /lib/libpthread\.so\.0
\#4  0x40215d90 in Perl\_ithread\_run \(\)
&nbsp;   from /usr/lib/perl/5\.8/auto/threads/threads\.so
\#5  0x40045e51 in pthread\_start\_thread \(\) from /lib/libpthread\.so\.0
\#6  0x4016892a in clone \(\) from /lib/libc\.so\.6

The child was not using any CPU time\.  The parent was using 99% CPU time\,
and strace showed it making no system calls\.  I attached to it twice
with gdb\, and got these stack traces&#8203;:

\#0  0x40049cc7 in wait\_node\_free \(\) from /lib/libpthread\.so\.0
\#1  0x40046d7a in pthread\_mutex\_unlock \(\) from /lib/libpthread\.so\.0
\#2  0x4021555d in Perl\_ithread\_destruct \(\)
&nbsp;   from /usr/lib/perl/5\.8/auto/threads/threads\.so
\#3  0x402159f9 in ithread\_mg\_free \(\)
&nbsp;   from /usr/lib/perl/5\.8/auto/threads/threads\.so
\#4  0x080cb285 in Perl\_sv\_unmagic \(\)
\#5  0x40216995 in Perl\_ithread\_DESTROY \(\)
&nbsp;   from /usr/lib/perl/5\.8/auto/threads/threads\.so
\#6  0x40217483 in XS\_threads\_DESTROY \(\)
&nbsp;   from /usr/lib/perl/5\.8/auto/threads/threads\.so
\#7  0x080c32d6 in Perl\_pp\_entersub \(\)
\#8  0x080640ec in Perl\_call\_sv \(\)
\#9  0x08063ec1 in Perl\_call\_sv \(\)
\#10 0x080cbad5 in Perl\_sv\_clear \(\)
\#11 0x080cc2a0 in Perl\_sv\_free \(\)
\#12 0x080cbc99 in Perl\_sv\_clear \(\)
\#13 0x080cc2a0 in Perl\_sv\_free \(\)
\#14 0x080e63a1 in Perl\_free\_tmps \(\)
\#15 0x080bc32a in Perl\_pp\_unstack \(\)
\#16 0x080bbdc9 in Perl\_runops\_standard \(\)
\#17 0x080635e8 in perl\_run \(\)
\#18 0x080633f5 in perl\_run \(\)
\#19 0x0805fb9f in main \(\)

\#0  0x4004a155 in \_\_pthread\_acquire \(\) from /lib/libpthread\.so\.0
\#1  0x40049ca8 in wait\_node\_free \(\) from /lib/libpthread\.so\.0
\#2  0x4004a017 in \_\_pthread\_alt\_unlock \(\) from /lib/libpthread\.so\.0
\#3  0x40046d7a in pthread\_mutex\_unlock \(\) from /lib/libpthread\.so\.0
\#4  0x4021555d in Perl\_ithread\_destruct \(\)
&nbsp;   from /usr/lib/perl/5\.8/auto/threads/threads\.so
\#5  0x402159f9 in ithread\_mg\_free \(\)
&nbsp;   from /usr/lib/perl/5\.8/auto/threads/threads\.so
\#6  0x080cb285 in Perl\_sv\_unmagic \(\)
\#7  0x40216995 in Perl\_ithread\_DESTROY \(\)
&nbsp;   from /usr/lib/perl/5\.8/auto/threads/threads\.so
\#8  0x40217483 in XS\_threads\_DESTROY \(\)
&nbsp;   from /usr/lib/perl/5\.8/auto/threads/threads\.so
\#9  0x080c32d6 in Perl\_pp\_entersub \(\)
\#10 0x080640ec in Perl\_call\_sv \(\)
\#11 0x08063ec1 in Perl\_call\_sv \(\)
\#12 0x080cbad5 in Perl\_sv\_clear \(\)
\#13 0x080cc2a0 in Perl\_sv\_free \(\)
\#14 0x080cbc99 in Perl\_sv\_clear \(\)
\#15 0x080cc2a0 in Perl\_sv\_free \(\)
\#16 0x080e63a1 in Perl\_free\_tmps \(\)
\#17 0x080bc32a in Perl\_pp\_unstack \(\)
\#18 0x080bbdc9 in Perl\_runops\_standard \(\)
\#19 0x080635e8 in perl\_run \(\)
\#20 0x080633f5 in perl\_run \(\)
\#21 0x0805fb9f in main \(\)

This is on a Debian \(stable\) Linux machine\.  The output of \`perl \-V\`&#8203;:

Summary of my perl5 \(revision 5 version 8 subversion 4\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.4\.27\-ti1211\, archname=i386\-linux\-thread\-multi
&nbsp;    uname='linux kosh 2\.4\.27\-ti1211 \#1 sun sep 19 18&#8203;:17&#8203;:45 est 2004 i686 gnulinux '
&nbsp;    config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN \-Dcccdlflags=\-fPIC \-Darchname=i386\-linux \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.8 \-Darchlib=/usr/lib/perl/5\.8 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.8\.4 \-Dsitearch=/usr/local/lib/perl/5\.8\.4 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1 \-Dsiteman3dir=/usr/local/man/man3 \-Dman1ext=1 \-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Uusesfio \-Uusenm \-Duseshrplib \-Dlibperl=libperl\.so\.5\.8\.4 \-Dd\_dosuid \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBIAN \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBIAN \-fno\-strict\-aliasing \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='3\.3\.5 \(Debian 1&#8203;:3\.3\.5\-9\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    libc=/lib/libc\-2\.3\.2\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.8\.4
&nbsp;    gnulibc\_version='2\.3\.2'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: MULTIPLICITY USE\_ITHREADS USE\_LARGE\_FILES PERL\_IMPLICIT\_CONTEXT
&nbsp;  Built under linux
&nbsp;  Compiled at Mar  8 2005 19&#8203;:51&#8203;:48
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /etc/perl
&nbsp;    /usr/local/lib/perl/5\.8\.4
&nbsp;    /usr/local/share/perl/5\.8\.4
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/perl/5\.8
&nbsp;    /usr/share/perl/5\.8
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    \.

\-zefram

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Nov 10\, 2005 at 08&#8203;:49&#8203;:05AM \-0800\, Zefram wrote&#8203;:
> I have a test program that simulates this thread usage pattern at a much
> faster speed&#8203;:
> 
> \#\#\# t0 start \#\#\#
> \#\!/usr/bin/perl
> use warnings;
> use strict;
> use threads;
> use threads&#8203;::shared;
> my $n : shared = 0;
> while\(1\) \{
>     async \{
>         threads\->self\->detach;
>         threads\->yield;
>         lock $n;
>         threads\->yield;
>         print "thread $n\\n";
>         threads\->yield;
>         $n\+\+;
>         threads\->yield;
>     \};
>     threads\->yield;
> \}

The only way I can get that code to crash is when it runs out of memory on
32\-bit systems \(which on Linux seems to have a 128Mb limit\)\. This
happened simply when the supply of new threads exceeded the destructions
of old threadsand so memory use grew\. Thus\, I'm not sure it's replicating
the problem you're seeing with your real code\.

\-\- 
"I do not resent critisism\, even when\, for the sake of emphasis\,
it parts for the time with reality"\.
&nbsp;    \-\- Winston Churchill\, House of Commons\, 22nd Jan 1941\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Fri\, Nov 11\, 2005 at 10&#8203;:48&#8203;:22AM \+0000\, Zefram wrote&#8203;:
> The child was not using any CPU time\.  The parent was using 99% CPU time\,
> and strace showed it making no system calls\.  I attached to it twice
> with gdb\, and got these stack traces&#8203;:
> 
> \#0  0x40049cc7 in wait\_node\_free \(\) from /lib/libpthread\.so\.0
> \#1  0x40046d7a in pthread\_mutex\_unlock \(\) from /lib/libpthread\.so\.0
> \#2  0x4021555d in Perl\_ithread\_destruct \(\)
>    from /usr/lib/perl/5\.8/auto/threads/threads\.so
> \#3  0x402159f9 in ithread\_mg\_free \(\)
>    from /usr/lib/perl/5\.8/auto/threads/threads\.so
> \#4  0x080cb285 in Perl\_sv\_unmagic \(\)
> \#5  0x40216995 in Perl\_ithread\_DESTROY \(\)
>    from /usr/lib/perl/5\.8/auto/threads/threads\.so
> \#6  0x40217483 in XS\_threads\_DESTROY \(\)
>    from /usr/lib/perl/5\.8/auto/threads/threads\.so
> \#7  0x080c32d6 in Perl\_pp\_entersub \(\)
> \#8  0x080640ec in Perl\_call\_sv \(\)
> \#9  0x08063ec1 in Perl\_call\_sv \(\)
> \#10 0x080cbad5 in Perl\_sv\_clear \(\)
> \#11 0x080cc2a0 in Perl\_sv\_free \(\)
> \#12 0x080cbc99 in Perl\_sv\_clear \(\)
> \#13 0x080cc2a0 in Perl\_sv\_free \(\)
> \#14 0x080e63a1 in Perl\_free\_tmps \(\)
> \#15 0x080bc32a in Perl\_pp\_unstack \(\)
> \#16 0x080bbdc9 in Perl\_runops\_standard \(\)
> \#17 0x080635e8 in perl\_run \(\)
> \#18 0x080633f5 in perl\_run \(\)
> \#19 0x0805fb9f in main \(\)

It would be interesting to to see the results of continuing to execute
using 'finish' a few times\, to see at what level in the call stack it is
looping\.

\-\- 
Nothing ventured\, nothing lost\.

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Dave Mitchell via RT wrote&#8203;:
>The only way I can get that code to crash is when it runs out of memory on
>32\-bit systems \(which on Linux seems to have a 128Mb limit\)\. This
>happened simply when the supply of new threads exceeded the destructions
>of old threadsand so memory use grew\. Thus\, I'm not sure it's replicating
>the problem you're seeing with your real code\.

That's definitely not what I was seeing with any of my code\.  I never
saw the test program with more than four Linux\-level subthreads\, and its
memory usage stayed small enough to not be a problem\.  Obviously it was
keeping up with thread terminations\.

\-zefram

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Dave Mitchell via RT wrote&#8203;:
>It would be interesting to to see the results of continuing to execute
>using 'finish' a few times\, to see at what level in the call stack it is
>looping\.

Unfortunately that's not an option\.  I don't have a proper test
environment for the code that does this\.

\-zefram

**Comment by p5pRT** [comment]
### From guest@guest.guest.xxxxxxxx

http&#8203;://guest&#8203;:guest@&#8203;rt\.perl\.org/rt3/Ticket/Display\.html?id=37652

Dave Mitchell wrote&#8203;:
>The only way I can get that code to crash is when it runs
>out of memory on 32\-bit systems \(which on Linux seems to
>have a 128Mb limit\)\. This happened simply when the supply
>of new threads exceeded the destructions of old threads and
>so memory use grew\. Thus\, I'm not sure it's replicating the
>problem you're seeing with your real code\.

zefram wrote&#8203;:
> That's definitely not what I was seeing with any of my
> code\.  I never saw the test program with more than four
> Linux\-level subthreads\, and its memory usage stayed small
> enough to not be a problem\.  Obviously it was keeping up
> with thread terminations\.

I would be inclined to dispute this\.  The test program\, as
written\, generates threads in a fast loop such that garbage
collection of terminated threads is\, at best\, hindered\.
Trying it under Cygwin Perl 5\.8\.8 and threads 1\.29\, it
failed after 2400 threads\.  Watching it in the Task Manager\,
memory steady grows until it fails after 350 MB\.  Similarly\,
all the failures reported by the poster can be interpreted
as resulting from memory allocation errors \(which usually
lead to various memory corruption failures\)\.

I then modified the test program to add a sleep after each
1000 threads&#8203;:

\#\!/usr/bin/perl
use warnings;
use strict;
use threads;
use threads&#8203;::shared;
my $n : shared = 0;
while\(1\) \{
&nbsp;    for \(1\.\.1000\) \{
&nbsp;    async \{
&nbsp;        threads\->self\->detach;
&nbsp;        threads\->yield;
&nbsp;        lock $n;
&nbsp;        threads\->yield;
&nbsp;        print "thread $n\\n";
&nbsp;        threads\->yield;
&nbsp;        $n\+\+;
&nbsp;        threads\->yield;
&nbsp;    \};
&nbsp;    threads\->yield;
&nbsp;    \}
&nbsp;    sleep\(10\);
\}

\(On my machine\, it takes about 10 sec\. to create and destroy
1000 threads\.  If I try 5 sec\.\, for instance\, Perl doesn't
have enough time to cleanup before the next loop\, and
eventually the program fails\, as before\, on memory\.  Of
course\, faster machines can get away with a shorter pause\.\)

This version runs virtually indefinitely \(> 2\,000\,000
threads\)\.  \(It dies on memory\, too\, at that point due to a
memory leak in Windows whereby each thread comsumes about
500 bytes that are never returned\.\)

Additionally\, older versions of 'threads' did have issues
with memory leaks which would have compounded the poster's
problem\.  However\, the lastest version does not suffer in
that regard\.  \(Again\, the leak I mentioned above is due to
Windows; not Perl/'threads'\.\)

Jerry D\. Hedden \<jdhedden AT cpan DOT org>
