### ISSUE TITLE
perl core dumps on syntax error

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8238]
Migrated from [rt.perl.org#37864](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=37864) (status was 'resolved')

Searchable as RT37864$

**Comment by p5pRT** [comment]
### From bhirt@mobygames.com

#### Created by bhirt@mobygames.com



I ran across a syntax error \(; in ternary\) that causes perl
to crash\.  I've been able to create a pretty simple test case
which is included below\.  I've testet with 5\.8\.5\, 5\.8\.6 and 5\.8\.7
on several differnt platforms and architectures \(including cygwin\)
and they all crash\.

\-\-start file\-\-
\#\!/usr/bin/perl \-w

=head1 crash

crash demo\.  crashes on

=cut

package Something&#8203;::CrashMe;

use strict;

sub crashme
\{
&nbsp;   my $this = shift;

&nbsp;   my $test1 = '';
&nbsp;   my $test2 = undef;
&nbsp;   my @&#8203;test3 = \(\);
&nbsp;   my @&#8203;test4 = \(\);
&nbsp;   my @&#8203;test5 = \(\);

&nbsp;   my @&#8203;listColumns = \(
&nbsp;         sub \{
&nbsp;           1 ?  'does'; :  'crash';
&nbsp;         \}
&nbsp;   \);

&nbsp;   return '';
\}

1;
\-\-end file\-\-

gdb stack trace&#8203;:

pb15&#8203;:\~ bhirt$ gdb /usr/bin/perl
GNU gdb 6\.1\-20040303 \(Apple version gdb\-413\) \(Wed May 18 10&#8203;:17&#8203;:02 GMT  
2005\)
Copyright 2004 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and  
you are
welcome to change it and/or distribute copies of it under certain  
conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for  
details\.
This GDB was configured as "powerpc\-apple\-darwin"\.\.\.Reading symbols  
for shared libraries \.\.\. done

\(gdb\) set args /tmp/test
\(gdb\) run
Starting program&#8203;: /usr/bin/perl /tmp/test
Reading symbols for shared libraries \. done

Program received signal EXC\_BAD\_ACCESS\, Could not access memory\.
Reason&#8203;: KERN\_INVALID\_ADDRESS at address&#8203;: 0x000f0016
0x9713f320 in Perl\_pad\_free \(\)
\(gdb\) bt
\#0  0x9713f320 in Perl\_pad\_free \(\)
\#1  0x9712df44 in Perl\_op\_clear \(\)
\#2  0x9712dc18 in Perl\_op\_free \(\)
\#3  0x9712dbcc in Perl\_op\_free \(\)
\#4  0x97137364 in Perl\_newATTRSUB \(\)
\#5  0x9712c30c in Perl\_yyparse \(\)
\#6  0x9710c1a8 in S\_parse\_body \(\)
\#7  0x9710b168 in perl\_parse \(\)
\#8  0x000029a8 in ?? \(\)
\#9  0x00002120 in ?? \(\)
\#10 0x00001fc0 in ?? \(\)
\(gdb\) quit
The program is running\.  Exit anyway? \(y or n\) y
pb15&#8203;:\~ bhirt$

<details><summary>Perl Info</summary>

```

Flags:
     category=core
     severity=high

Site configuration information for perl v5.8.6:

Configured by root at Sun Mar 20 16:31:42 PST 2005.

Summary of my perl5 (revision 5 version 8 subversion 6) configuration:
   Platform:
     osname=darwin, osvers=8.0, archname=darwin-thread-multi-2level
     uname='darwin b28.apple.com 8.0 darwin kernel version 7.5.0: thu  
mar 3 18:48:46 pst 2005; root:xnuxnu-517.99.13.obj~1release_ppc power  
macintosh powerpc '
     config_args='-ds -e -Dprefix=/usr -Dccflags=-g  -pipe  - 
Dldflags=-Dman3ext=3pm -Duseithreads -Duseshrplib'
     hint=recommended, useposix=true, d_sigaction=define
     usethreads=define use5005threads=undef useithreads=define  
usemultiplicity=define
     useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
     use64bitint=undef use64bitall=undef uselongdouble=undef
     usemymalloc=n, bincompat5005=undef
   Compiler:
     cc='cc', ccflags ='-g -pipe -fno-common -DPERL_DARWIN -no-cpp- 
precomp -fno-strict-aliasing -I/usr/local/include',
     optimize='-Os',
     cppflags='-no-cpp-precomp -g -pipe -fno-common -DPERL_DARWIN -no- 
cpp-precomp -fno-strict-aliasing -I/usr/local/include'
     ccversion='', gccversion='3.3 20030304 (Apple Computer, Inc.  
build 1809)', gccosandvers=''
     intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=4321
     d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=8
     ivtype='long', ivsize=4, nvtype='double', nvsize=8,  
Off_t='off_t', lseeksize=8
     alignbytes=8, prototype=define
   Linker and Libraries:
     ld='env MACOSX_DEPLOYMENT_TARGET=10.3 cc', ldflags ='-L/usr/ 
local/lib'
     libpth=/usr/local/lib /usr/lib
     libs=-ldbm -ldl -lm -lc
     perllibs=-ldl -lm -lc
     libc=/usr/lib/libc.dylib, so=dylib, useshrplib=true,  
libperl=libperl.dylib
     gnulibc_version=''
   Dynamic Linking:
     dlsrc=dl_dlopen.xs, dlext=bundle, d_dlsymun=undef, ccdlflags=' '
     cccdlflags=' ', lddlflags='-bundle -undefined dynamic_lookup -L/ 
usr/local/lib'

Locally applied patches:
     23953 - fix for File::Path::rmtree CAN-2004-0452 security issue
     33990 - fix for setuid perl security issues


@INC for perl v5.8.6:
     /sw/lib/perl5/5.8.6/darwin-thread-multi-2level
     /sw/lib/perl5/5.8.6
     /sw/lib/perl5
     /sw/lib/perl5/darwin
     /System/Library/Perl/5.8.6/darwin-thread-multi-2level
     /System/Library/Perl/5.8.6
     /Library/Perl/5.8.6/darwin-thread-multi-2level
     /Library/Perl/5.8.6
     /Library/Perl
     /Network/Library/Perl/5.8.6/darwin-thread-multi-2level
     /Network/Library/Perl/5.8.6
     /Network/Library/Perl
     /System/Library/Perl/Extras/5.8.6/darwin-thread-multi-2level
     /System/Library/Perl/Extras/5.8.6
     /Library/Perl/5.8.1
     .


Environment for perl v5.8.6:
     DYLD_LIBRARY_PATH (unset)
     HOME=/Users/bhirt
     LANG (unset)
     LANGUAGE (unset)
     LD_LIBRARY_PATH (unset)
     LOGDIR (unset)
     PATH=/sw/bin:/sw/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/pg-8.1/ 
bin:/usr/local/bin:/usr/X11R6/bin:/Users/bhirt/bin:/usr/pg-8.1/bin
     PERL5LIB=/sw/lib/perl5:/sw/lib/perl5/darwin
     PERL_BADLANG (unset)
     SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @pjcj

On Thu\, Dec 08\, 2005 at 12&#8203;:37&#8203;:28PM \-0800\, Brian Hirt wrote&#8203;:

> I ran across a syntax error \(; in ternary\) that causes perl
> to crash\.  I've been able to create a pretty simple test case
> which is included below\.  I've testet with 5\.8\.5\, 5\.8\.6 and 5\.8\.7
> on several differnt platforms and architectures \(including cygwin\)
> and they all crash\.

This seems to have been fixed in bleadperl\.

$ perl5\.9\.3 /tmp/y
syntax error at /tmp/y line 25\, near "'does';"
Execution of /tmp/y aborted due to compilation errors\.

The fix doesn't seem to be part of 5\.8\.8 as of my build from October
31st\, and it seems to have been fixed by 5\.9\.2\, so I suspect it won't be
going into the maint releases for some reason\.

\-\- 
Paul Johnson \- paul@&#8203;pjcj\.net
http&#8203;://www\.pjcj\.net

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Fri\, Dec 09\, 2005 at 12&#8203;:33&#8203;:36AM \+0100\, Paul Johnson wrote&#8203;:
> On Thu\, Dec 08\, 2005 at 12&#8203;:37&#8203;:28PM \-0800\, Brian Hirt wrote&#8203;:
> This seems to have been fixed in bleadperl\.
> 
> $ perl5\.9\.3 /tmp/y
> syntax error at /tmp/y line 25\, near "'does';"
> Execution of /tmp/y aborted due to compilation errors\.
> 
> The fix doesn't seem to be part of 5\.8\.8 as of my build from October
> 31st\, and it seems to have been fixed by 5\.9\.2\, so I suspect it won't be
> going into the maint releases for some reason\.

It's the standard 'syntax error during sub\, use or no' problem\. The fix in
bleed was tied up with the whole yacc \-> bison migration\, which is too
complex \(and untested on EBCDIC platforms\) to be comfortably packported
to 5\.8\.x\.

\-\- 
"Strange women lying in ponds distributing swords is no basis for a system
of government\. Supreme executive power derives from a mandate from the
masses\, not from some farcical aquatic ceremony\."
&nbsp;    \-\- Dennis \- Monty Python and the Holy Grail\.

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'resolved'
