### ISSUE TITLE
SEGMENTATION FAULT

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8284]
Migrated from [rt.perl.org#38265](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=38265) (status was 'rejected')

Searchable as RT38265$

**Comment by p5pRT** [comment]
### From Subrahmanian.Kalyanasundaram@igate.com

 
Hi\,

I have a problem in executing the perl program\, it is showing as "Segmentation Fault"\.\.the thing happened\, 
my environment is

Sun solaris os \- Ver 5\.8
Perl \- Ver 5\.8\.7
GCC \- Ver 3\.4\.2
Crypt\-SSLeay \- Ver 0\.51
Net\_SSLeay\- Ver 1\.30
IO\-Socket\-SSL\- Ver 0\.97

I am trying to execute the WWW&#8203;:Mechanizer program for that i have installed the "Crypt&#8203;::SSleay" 
and while executing the program it is showing error as "Crypt&#8203;::SSleay not installed"\, 
and we upgraded the gcc\(version 3\.4\.2\) and reinstalled the "Crypt&#8203;::SSleay"  and "Net&#8203;::SSleay" 
and "IO" after this when i execute the program  it is showing as "Segmentation fault"

\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
my perl program is 
\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
\#\!/usr/bin/perl
use WWW&#8203;::Mechanize;
use LWP&#8203;::Debug qw\(\+\);
$url = 'https://my.igate.com/psp/IGATE/?cmd=login';
my $mechanize = WWW&#8203;::Mechanize\->new\(autocheck => 1\);
$mechanize\->get\($url\);
my $page = $mechanize\->content;
print $page;

\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
The output is 
\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
LWP&#8203;::UserAgent&#8203;::new&#8203;: \(\)
LWP&#8203;::UserAgent&#8203;::request&#8203;: \(\)
HTTP&#8203;::Cookies&#8203;::add\_cookie\_header&#8203;: Checking my\.igate\.com for cookies
HTTP&#8203;::Cookies&#8203;::add\_cookie\_header&#8203;: Checking \.igate\.com for cookies
HTTP&#8203;::Cookies&#8203;::add\_cookie\_header&#8203;: Checking igate\.com for cookies
HTTP&#8203;::Cookies&#8203;::add\_cookie\_header&#8203;: Checking \.com for cookies
LWP&#8203;::UserAgent&#8203;::send\_request&#8203;: GET https://my.igate.com/psp/IGATE/?cmd=login
LWP&#8203;::UserAgent&#8203;::\_need\_proxy&#8203;: Not proxied
LWP&#8203;::Protocol&#8203;::http&#8203;::request&#8203;: \(\)
Segmentation Fault
\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
can u help me out\, why the program is not executing any patches or modules need to be installed

Thanks in advance

Regards

K\.Subrahmanian

 

 

\_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_

Information transmitted by this EMAIL is proprietary to iGATE Group of Companies and is intended for use only by the individual 
or entity to whom it is addressed and may contain information that is privileged\, confidential\, or exempt from disclosure under 
applicable law\. If you are not the intended recipient of this EMAIL immediately notify the sender at iGATE or mailadmin@&#8203;igate\.com 
and delete this EMAIL including any attachments
\_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_

**Comment by p5pRT** [comment]
### From @smpeters

> \[Subrahmanian\.Kalyanasundaram@&#8203;igate\.com \- Tue Jan 17 21&#8203;:48&#8203;:16 2006\]&#8203;:
> 
>  
> Hi\,
> 
> I have a problem in executing the perl program\, it is
> showing as "Segmentation Fault"\.\.the thing happened\, 
> my environment
> is
> 
> Sun solaris os \- Ver 5\.8
> Perl \- Ver 5\.8\.7
> GCC \- Ver 3\.4\.2
> Crypt\-SSLeay \- Ver 0\.51
> Net\_SSLeay\- Ver 1\.30
> IO\-Socket\-SSL\- Ver 0\.97
> I am trying to execute the WWW&#8203;:Mechanizer program for that i have
> installed the "Crypt&#8203;::SSleay" 
> and while executing the program it is
> showing error as "Crypt&#8203;::SSleay not installed"\, 
> and we upgraded the
> gcc\(version 3\.4\.2\) and reinstalled the "Crypt&#8203;::SSleay"  and
> "Net&#8203;::SSleay" 
> and "IO" after this when i execute the program  it is
> showing as "Segmentation fault"
> \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
> my
> perl program is
> \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
> \#\!/usr/bin/perl
> use WWW&#8203;::Mechanize;
> use LWP&#8203;::Debug qw\(\+\);
> $url =
> 'https://my.igate.com/psp/IGATE/?cmd=login';
> my $mechanize =
> WWW&#8203;::Mechanize\->new\(autocheck => 1\);
> $mechanize\->get\($url\);
> my $page
> = $mechanize\->content;
> print $page;
> \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
> The
> output is
> \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
> LWP&#8203;::UserAgent&#8203;::new&#8203;: \(\)
> LWP&#8203;::UserAgent&#8203;::request&#8203;: \(\)
> HTTP&#8203;::Cookies&#8203;::add\_cookie\_header&#8203;: Checking my\.igate\.com for cookies
> HTTP&#8203;::Cookies&#8203;::add\_cookie\_header&#8203;: Checking \.igate\.com for cookies
> HTTP&#8203;::Cookies&#8203;::add\_cookie\_header&#8203;: Checking igate\.com for cookies
> HTTP&#8203;::Cookies&#8203;::add\_cookie\_header&#8203;: Checking \.com for cookies
> LWP&#8203;::UserAgent&#8203;::send\_request&#8203;: GET
> https://my.igate.com/psp/IGATE/?cmd=login
> LWP&#8203;::UserAgent&#8203;::\_need\_proxy&#8203;: Not proxied
> LWP&#8203;::Protocol&#8203;::http&#8203;::request&#8203;: \(\)
> Segmentation Fault
> \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
> can u
> help me out\, why the program is not executing any patches or modules
> need to be installed
> 

It looks like Crypt&#8203;::SSLeay is the problem\.

\#0  0xb7bb1bf2 in SSL\_CTX\_ctrl \(\) 
from /usr/lib/i686/cmov/libssl\.so\.0\.9\.8
\(gdb\) bt
\#0  0xb7bb1bf2 in SSL\_CTX\_ctrl \(\) 
from /usr/lib/i686/cmov/libssl\.so\.0\.9\.8
\#1  0xb7bc8865 in XS\_Crypt\_\_SSLeay\_\_CTX\_new \(my\_perl=0x8160008\, 
cv=0x85a2dbc\)
&nbsp;    at SSLeay\.xs&#8203;:133
\#2  0x080ccb5f in Perl\_pp\_entersub \(my\_perl=0x8160008\) at pp\_hot\.c&#8203;:2906
\#3  0x080c4ccb in Perl\_runops\_standard \(my\_perl=0x8160008\) at run\.c&#8203;:38
\#4  0x08065494 in perl\_run \(my\_perl=0x8160008\) at perl\.c&#8203;:2321
\#5  0x0806030e in main \(argc=\-1212474382\, argv=0xb7bb1bf2\, 
env=0xbfab0350\)
&nbsp;    at perlmain\.c&#8203;:103


&nbsp;    125         if\(ssl\_version == 23\) \{
&nbsp;    126                 ctx = SSL\_CTX\_new\(SSLv23\_client\_method\(\)\);
&nbsp;    127         \} else if\(ssl\_version == 3\) \{
&nbsp;    128                 ctx = SSL\_CTX\_new\(SSLv3\_client\_method\(\)\);
&nbsp;    129         \} else \{
&nbsp;    130                 /\* v2 is the default \*/
&nbsp;    131                 ctx = SSL\_CTX\_new\(SSLv2\_client\_method\(\)\);
&nbsp;    132         \}
&nbsp;    133         SSL\_CTX\_set\_options\(ctx\,SSL\_OP\_ALL|0\);
&nbsp;    134
&nbsp;    135         SSL\_CTX\_set\_default\_verify\_paths\(ctx\);
&nbsp;    136         SSL\_CTX\_set\_verify\(ctx\, SSL\_VERIFY\_NONE\, NULL\);
&nbsp;    137
&nbsp;    138         RETVAL = ctx;
&nbsp;    139
&nbsp;    140      OUTPUT&#8203;:
&nbsp;    141         RETVAL


My guess is that some changes in OpenSSL are preventing Crypt&#8203;::SSLeay 
from working correctly\.  Since neither LWP nor Crypt&#8203;::SSLeay nor 
WWW&#8203;::Mechanize are part of the core\, this is as far as the ticket can 
go here\.  I'd suggest working with the maintainer of Crypt&#8203;::SSLeay\.  In 
fact\, this suggestion at the Crypt&#8203;::SSLeay ticket queue 
\<http&#8203;://rt\.cpan\.org/Public/Bug/Display\.html?id=15241> is probabably 
your best bet for fixing the problem\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'rejected'
