### ISSUE TITLE
"*** glibc detected *** free(): invalid pointer" from Perl_mg_free

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8487]
Migrated from [rt.perl.org#39528](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=39528) (status was 'resolved')

Searchable as RT39528$

**Comment by p5pRT** [comment]
### From cmr@financial.com


This is a bug report for perl from cmr@&#8203;financial\.com\,
generated with the help of perlbug 1\.35 running under perl v5\.8\.5\.




---
While installing some mod\_perl webapp \(ocsinventory\) i tripped about a crash reoccuring all the time\. It seems that something is passed to free\(\) from Perl\_mg\_free which makes it crash\. I made a stacktrace and did some debugging without any sucess&#8203;:

Here is the stacktrace&#8203;:

\[Thread debugging using libthread\_db enabled\]
\[New Thread 182925685056 \(LWP 18808\)\]
\*\*\* glibc detected \*\*\* free\(\)&#8203;: invalid pointer&#8203;: 0x000000552b78fd50 \*\*\*

Program received signal SIGABRT\, Aborted\.
\[Switching to Thread 182925685056 \(LWP 18808\)\]
0x0000002a966252ed in raise \(\) at \.\./string/bits/string2\.h&#8203;:1000
1000        \+\+\_\_result;
\(gdb\) bt
\#0  0x0000002a966252ed in raise \(\) at \.\./string/bits/string2\.h&#8203;:1000
\#1  0x0000002a96626a3e in abort \(\) at \.\./string/bits/string2\.h&#8203;:1000
\#2  0x0000002a96659d41 in \_\_libc\_message \(do\_abort=Variable "do\_abort" is not available\.
\) at \.\./sysdeps/unix/sysv/linux/libc\_fatal\.c&#8203;:145
\#3  0x0000002a9665f81e in \_int\_free \(av=0x2a96827620\, mem=Variable "mem" is not available\.
\) at malloc\.c&#8203;:5525
\#4  0x0000002a9665fb66 in \_\_libc\_free \(mem=Variable "mem" is not available\.
\) at malloc\.c&#8203;:3404
\#5  0x0000002a9a11f883 in Perl\_mg\_free \(my\_perl=0x552b0bbac0\, sv=0x552b40f230\) at mg\.c&#8203;:389
\#6  0x0000002a9a137ff6 in Perl\_sv\_clear \(my\_perl=0x552b0bbac0\, sv=0x552b40f230\) at sv\.c&#8203;:5160
\#7  0x0000002a9a13837d in Perl\_sv\_free \(my\_perl=0x552b0bbac0\, sv=0x552b40f230\) at sv\.c&#8203;:5371
\#8  0x0000002a9a137edd in Perl\_sv\_clear \(my\_perl=0x552b0bbac0\, sv=0x552b76b770\) at sv\.c&#8203;:5223
\#9  0x0000002a9a13837d in Perl\_sv\_free \(my\_perl=0x552b0bbac0\, sv=0x552b76b770\) at sv\.c&#8203;:5371
\#10 0x0000002a9a11f8cc in Perl\_mg\_free \(my\_perl=0x552b0bbac0\, sv=0x552b40f250\) at mg\.c&#8203;:388
\#11 0x0000002a9a137ff6 in Perl\_sv\_clear \(my\_perl=0x552b0bbac0\, sv=0x552b40f250\) at sv\.c&#8203;:5160
\#12 0x0000002a9a13837d in Perl\_sv\_free \(my\_perl=0x552b0bbac0\, sv=0x552b40f250\) at sv\.c&#8203;:5371
\#13 0x0000002a9a15d43c in Perl\_free\_tmps \(my\_perl=0x552b0bbac0\) at scope\.c&#8203;:189
\#14 0x0000002a99f76762 in modperl\_callback \(\) from /etc/httpd/modules/mod\_perl\.so
\#15 0x0000002a99f76ca9 in modperl\_callback\_run\_handlers \(\) from /etc/httpd/modules/mod\_perl\.so
\#16 0x0000002a99f76eff in modperl\_callback\_per\_dir \(\) from /etc/httpd/modules/mod\_perl\.so
\#17 0x0000002a99f722f0 in modperl\_response\_finish \(\) from /etc/httpd/modules/mod\_perl\.so
\#18 0x0000002a99f72566 in modperl\_response\_handler\_cgi \(\) from /etc/httpd/modules/mod\_perl\.so
\#19 0x000000552aac79f3 in ap\_run\_handler \(r=0x552b1ed858\) at /usr/src/debug/httpd\-2\.0\.52/server/config\.c&#8203;:156
\#20 0x000000552aac7eb1 in ap\_invoke\_handler \(r=0x552b1ed858\) at /usr/src/debug/httpd\-2\.0\.52/server/config\.c&#8203;:368
\#21 0x000000552aac4cb8 in ap\_process\_request \(r=0x552b1ed858\) at /usr/src/debug/httpd\-2\.0\.52/modules/http/http\_request\.c&#8203;:246
\#22 0x000000552aac0089 in ap\_process\_http\_connection \(c=0x552b1e64e8\) at /usr/src/debug/httpd\-2\.0\.52/modules/http/http\_core\.c&#8203;:250
\#23 0x000000552aad1693 in ap\_run\_process\_connection \(c=0x552b1e64e8\) at /usr/src/debug/httpd\-2\.0\.52/server/connection\.c&#8203;:42
\#24 0x000000552aac5b20 in child\_main \(child\_num\_arg=Variable "child\_num\_arg" is not available\.
\) at /usr/src/debug/httpd\-2\.0\.52/server/mpm/prefork/prefork\.c&#8203;:609
\#25 0x000000552aac5dbd in make\_child \(s=0x552ac03620\, slot=0\) at /usr/src/debug/httpd\-2\.0\.52/server/mpm/prefork/prefork\.c&#8203;:649
\#26 0x000000552aac5ea4 in startup\_children \(number\_to\_start=8\) at /usr/src/debug/httpd\-2\.0\.52/server/mpm/prefork/prefork\.c&#8203;:721
\#27 0x000000552aac65db in ap\_mpm\_run \(\_pconf=0x552abfe138\, plog=Variable "plog" is not available\.
\) at /usr/src/debug/httpd\-2\.0\.52/server/mpm/prefork/prefork\.c&#8203;:940
\#28 0x000000552aacccef in main \(argc=2\, argv=0x7fbffff998\) at /usr/src/debug/httpd\-2\.0\.52/server/main\.c&#8203;:618


I only used CentOS RPM versions of the software playing together here \(apache\, mod\_perl\, perl\) so if you need sources to verify you can get it from any CentOS\-mirror directory centos/4\.3/os/SRPMS/\.


Chris



---


---
Flegs&#8203;:
&nbsp;    category=core
&nbsp;    severity=high


---
This perlbug was built using Perl v5\.8\.5 in the Red Hat build system\.
It is being executed now by Perl v5\.8\.5 \- Tue Dec 20 19&#8203;:07&#8203;:04 CST 2005\.

Site configuration information for perl v5\.8\.5&#8203;:

Configured by Red Hat\, Inc\. at Tue Dec 20 19&#8203;:07&#8203;:04 CST 2005\.

Summary of my perl5 \(revision 5 version 8 subversion 5\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.9\-22\.0\.1\.el\, archname=x86\_64\-linux\-thread\-multi
&nbsp;    uname='linux x8664\-build\.centos\.org 2\.6\.9\-22\.0\.1\.el \#1 thu oct 27 14&#8203;:29&#8203;:45 cdt 2005 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;    config\_args='\-des \-Doptimize=\-O2 \-g \-pipe \-m64 \-Dversion=5\.8\.5 \-Dmyhostname=localhost \-Dperladmin=root@&#8203;localhost \-Dcc=gcc \-Dcf\_by=Red Hat\, Inc\. \-Dinstallprefix=/usr \-Dprefix=/usr \-Dlibpth=/usr/local/lib64 /lib64 /usr/lib64 \-Dprivlib=/usr/lib/perl5/5\.8\.5 \-Dsitelib=/usr/lib/perl5/site\_perl/5\.8\.5 \-Dvendorlib=/usr/lib/perl5/vendor\_perl/5\.8\.5 \-Darchlib=/usr/lib64/perl5/5\.8\.5/x86\_64\-linux\-thread\-multi \-Dsitearch=/usr/lib64/perl5/site\_perl/5\.8\.5/x86\_64\-linux\-thread\-multi \-Dvendorarch=/usr/lib64/perl5/vendor\_perl/5\.8\.5/x86\_64\-linux\-thread\-multi \-Darchname=x86\_64\-linux \-Dvendorprefix=/usr \-Dsiteprefix=/usr \-Duseshrplib \-Dusethreads \-Duseithreads \-Duselargefiles \-Dd\_dosuid \-Dd\_semctl\_semun \-Di\_db \-Ui\_ndbm \-Di\_gdbm \-Di\_shadow \-Di\_syslog \-Dman3ext=3pm \-Duseperlio \-Dinstallusrbinperl \-Ubincompat5005 \-Uversiononly \-Dpager=/usr/bin/less \-isr \-Dinc\_version\_list=5\.8\.4 5\.8\.3 5\.8\.2 5\.8\.1 5\.8\.0'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=define use64bitall=define uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-I/usr/include/gdbm'\,
&nbsp;    optimize='\-O2 \-g \-pipe \-m64'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-I/usr/local/include \-I/usr/include/gdbm'
&nbsp;    ccversion=''\, gccversion='3\.4\.4 20050721 \(Red Hat 3\.4\.4\-2\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='gcc'\, ldflags =''
&nbsp;    libpth=/usr/local/lib64 /lib64 /usr/lib64
&nbsp;    libs=\-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    libc=/lib/libc\-2\.3\.4\.so\, so=so\, useshrplib=true\, libperl=libperl\.so
&nbsp;    gnulibc\_version='2\.3\.4'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E \-Wl\,\-rpath\,/usr/lib64/perl5/5\.8\.5/x86\_64\-linux\-thread\-multi/CORE'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl v5\.8\.5&#8203;:
&nbsp;    /usr/lib64/perl5/5\.8\.5/x86\_64\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/5\.8\.5
&nbsp;    /usr/lib64/perl5/site\_perl/5\.8\.5/x86\_64\-linux\-thread\-multi
&nbsp;    /usr/lib64/perl5/site\_perl/5\.8\.4/x86\_64\-linux\-thread\-multi
&nbsp;    /usr/lib64/perl5/site\_perl/5\.8\.3/x86\_64\-linux\-thread\-multi
&nbsp;    /usr/lib64/perl5/site\_perl/5\.8\.2/x86\_64\-linux\-thread\-multi
&nbsp;    /usr/lib64/perl5/site\_perl/5\.8\.1/x86\_64\-linux\-thread\-multi
&nbsp;    /usr/lib64/perl5/site\_perl/5\.8\.0/x86\_64\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.5
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.4
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.3
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.2
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.1
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.0
&nbsp;    /usr/lib/perl5/site\_perl
&nbsp;    /usr/lib64/perl5/vendor\_perl/5\.8\.5/x86\_64\-linux\-thread\-multi
&nbsp;    /usr/lib64/perl5/vendor\_perl/5\.8\.4/x86\_64\-linux\-thread\-multi
&nbsp;    /usr/lib64/perl5/vendor\_perl/5\.8\.3/x86\_64\-linux\-thread\-multi
&nbsp;    /usr/lib64/perl5/vendor\_perl/5\.8\.2/x86\_64\-linux\-thread\-multi
&nbsp;    /usr/lib64/perl5/vendor\_perl/5\.8\.1/x86\_64\-linux\-thread\-multi
&nbsp;    /usr/lib64/perl5/vendor\_perl/5\.8\.0/x86\_64\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.5
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.4
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.3
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.2
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.1
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.0
&nbsp;    /usr/lib/perl5/vendor\_perl
&nbsp;    \.



---
Environment for perl v5\.8\.5&#8203;:
&nbsp;    HOME=/root
&nbsp;    LANG=de\_DE
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/usr/kerberos/sbin&#8203;:/usr/kerberos/bin&#8203;:/usr/local/sbin&#8203;:/usr/local/bin&#8203;:/sbin&#8203;:/bin&#8203;:/usr/sbin&#8203;:/usr/bin&#8203;:/usr/X11R6/bin&#8203;:/usr/java/jdk1\.5\.0\_06/bin&#8203;:/root/bin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @nwc10

On Mon\, Jun 19\, 2006 at 06&#8203;:40&#8203;:28AM \-0700\, cmr @&#8203; financial\. com wrote&#8203;:

> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> While installing some mod\_perl webapp \(ocsinventory\) i tripped about a crash reoccuring all the time\. It seems that something is passed to free\(\) from Perl\_mg\_free which makes it crash\. I made a stacktrace and did some debugging without any sucess&#8203;:
> 
> Here is the stacktrace&#8203;:
> 
> \[Thread debugging using libthread\_db enabled\]
> \[New Thread 182925685056 \(LWP 18808\)\]
> \*\*\* glibc detected \*\*\* free\(\)&#8203;: invalid pointer&#8203;: 0x000000552b78fd50 \*\*\*
> 
> Program received signal SIGABRT\, Aborted\.
> \[Switching to Thread 182925685056 \(LWP 18808\)\]
> 0x0000002a966252ed in raise \(\) at \.\./string/bits/string2\.h&#8203;:1000
> 1000        \+\+\_\_result;
> \(gdb\) bt
> \#0  0x0000002a966252ed in raise \(\) at \.\./string/bits/string2\.h&#8203;:1000
> \#1  0x0000002a96626a3e in abort \(\) at \.\./string/bits/string2\.h&#8203;:1000
> \#2  0x0000002a96659d41 in \_\_libc\_message \(do\_abort=Variable "do\_abort" is not available\.
> \) at \.\./sysdeps/unix/sysv/linux/libc\_fatal\.c&#8203;:145
> \#3  0x0000002a9665f81e in \_int\_free \(av=0x2a96827620\, mem=Variable "mem" is not available\.
> \) at malloc\.c&#8203;:5525

Sadly this doesn't give me any clues as to what is going on\.
Are you able to get this down to a smaller test case that only uses core
modules?

> I only used CentOS RPM versions of the software playing together here \(apache\, mod\_perl\, perl\) so if you need sources to verify you can get it from any CentOS\-mirror directory centos/4\.3/os/SRPMS/\.

The volunteers on perl5\-porters only really deal with the official releases of
perl released to CPAN\. Can you replicate the problem with perl built from
CPAN source?

Otherwise\, you should consider reporting the problem to whoever supports
the CentOS Perl\.

Nicholas Clark

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From cmr@financial.com

\-\-\-\-\-BEGIN PGP SIGNED MESSAGE\-\-\-\-\-
Hash&#8203;: SHA1

Thanks for looking into it\. Unluckily i have not found time for this
issue lately\. I reported this problem to the CentOS bugtracking also\,
without any response so far\. I will try the next release candidate of
ocsinventory wich is scheduled for 7/7/2006\. If the problem persists i
try to find out where it happens\, maybe with some help from the
ocsinventory guys\.

Chris


\-\-\-\-\-BEGIN PGP SIGNATURE\-\-\-\-\-
Version&#8203;: GnuPG v1\.4\.2\.1 \(Cygwin\)
Comment&#8203;: Using GnuPG with Mozilla \- http&#8203;://enigmail\.mozdev\.org

iD8DBQFEqAMWsLjW0HYht7URAuZfAKDcN3NMg0ONQEDB68L2B4QK\+9nq6QCfcKFK
Lfb8pO54HSqAu9hgKtVD4I0=
=IGir
\-\-\-\-\-END PGP SIGNATURE\-\-\-\-\-

**Comment by p5pRT** [comment]
### From cmr@financial.com

\-\-\-\-\-BEGIN PGP SIGNED MESSAGE\-\-\-\-\-
Hash&#8203;: SHA1

I have found a solution for this issue\, i installed DBD&#8203;::MySQL version 2\.9008 instead of
the provided 2\.9004\, the error dissapeared\.


Chris
\-\-\-\-\-BEGIN PGP SIGNATURE\-\-\-\-\-
Version&#8203;: GnuPG v1\.4\.2\.1 \(Cygwin\)
Comment&#8203;: Using GnuPG with Mozilla \- http&#8203;://enigmail\.mozdev\.org

iD8DBQFEqQyusLjW0HYht7URAsGkAJwN20NS0XicZD3Lisx451zPDjMJ0QCfagPS
AuOn8jpmKwsIitg2IMYWdvY=
=3K7K
\-\-\-\-\-END PGP SIGNATURE\-\-\-\-\-

**Comment by p5pRT** [comment]
p5p@spam.wizbit.be - Status changed from 'open' to 'resolved'
