### ISSUE TITLE
Mortality of objects (e.g. %$_) passed as args... - bug or feature?

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8520]
Migrated from [rt.perl.org#39800](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=39800) (status was 'open')

Searchable as RT39800$

**Comment by p5pRT** [comment]
### From vaclav.ovsik@i.cz


This is a bug report for perl from vaclav\.ovsik@&#8203;i\.cz\,
generated with the help of perlbug 1\.35 running under perl v5\.8\.4\.




---
Dear perl maintainer\,
after several hours of seraching bug in Carp&#8203;::Heavy\, witch was dying
with different errors \(Bizarre copy of HASH in sassign\, Modification
of a read\-only value attempted\.\.\.\) I probably found problem in perl
core\.
From code and its output it's obvious I think&#8203;:

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\<code>\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
\#\!/usr/bin/perl
use strict;
use Data&#8203;::Dumper;

sub foo
\{
&nbsp;    undef $\_;
&nbsp;    print Data&#8203;::Dumper\->Dump\(\[\\@&#8203;\_\]\, \[qw\(args\)\]\);
\}

$\_ = \{
&nbsp;    one => 1\,
&nbsp;    two => 2\,
&nbsp;    three => 3\,
\};

foo\(%$\_\);
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\<code>\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\<output>\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
zito@&#8203;bobek&#8203;:\~/pokusy/devel/perl/bug/carp$ \./accum\-hashref\-mortality 
$args = \[
&nbsp;          'three'\,
&nbsp;          \[
&nbsp;            $args
&nbsp;          \]\,
&nbsp;          'one'\,
&nbsp;          $args\,
&nbsp;          'two'\,
&nbsp;          $\{$args\->\[1\]\}
&nbsp;        \];
Attempt to free unreferenced scalar&#8203;: SV 0x814cd4c\.
Attempt to free unreferenced scalar&#8203;: SV 0x814cd28\.
Attempt to free unreferenced scalar&#8203;: SV 0x816401c\.
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\<output>\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

Yes\, code is ugly\, but I think correct\. Or no?
Before this my discovery I believed\, that %$\_ creates in list
context list which has nothing to do with $\_ after entering
subrutine any more\. It seems to me\, that when hashref is garbage
collected\, list created from this hash is also garbage collected?

This problem I found in perl 5\.8\.x including 5\.8\.8 and 5\.6\.1
around me\.



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=low


---
Site configuration information for perl v5\.8\.4&#8203;:

Configured by Debian Project at Thu Mar 23 21&#8203;:57&#8203;:50 UTC 2006\.

Summary of my perl5 \(revision 5 version 8 subversion 4\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.15\.4\, archname=i386\-linux\-thread\-multi
&nbsp;    uname='linux ninsei 2\.6\.15\.4 \#1 smp preempt mon feb 20 09&#8203;:48&#8203;:53 pst 2006 i686 gnulinux '
&nbsp;    config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN \-Dcccdlflags=\-fPIC \-Darchname=i386\-linux \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.8 \-Darchlib=/usr/lib/perl/5\.8 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.8\.4 \-Dsitearch=/usr/local/lib/perl/5\.8\.4 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1 \-Dsiteman3dir=/usr/local/man/man3 \-Dman1ext=1 \-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Uusesfio \-Uusenm \-Duseshrplib \-Dlibperl=libperl\.so\.5\.8\.4 \-Dd\_dosuid \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBIAN \-fno\-strict\-aliasing \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DDEBIAN \-fno\-strict\-aliasing \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='3\.3\.5 \(Debian 1&#8203;:3\.3\.5\-13\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    libc=/lib/libc\-2\.3\.2\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.8\.4
&nbsp;    gnulibc\_version='2\.3\.2'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-L/usr/local/lib'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl v5\.8\.4&#8203;:
&nbsp;    /etc/perl
&nbsp;    /usr/local/lib/perl/5\.8\.4
&nbsp;    /usr/local/share/perl/5\.8\.4
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/perl/5\.8
&nbsp;    /usr/share/perl/5\.8
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    \.



---
Environment for perl v5\.8\.4&#8203;:
&nbsp;    HOME=/home/zito
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LC\_CTYPE=cs\_CZ\.ISO\-8859\-2
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/zito/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/bin/X11&#8203;:/usr/games&#8203;:/opt/informix\-7\.31/bin&#8203;:/opt/oracle\-10\.2\.0\.1\.0/bin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @mhx

On 2006\-07\-12\, at 06&#8203;:58&#8203;:25 \-0700\, Vaclav Ovsik \(via RT\) wrote&#8203;:

> \[\.\.\.\] 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\<output>\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> zito@&#8203;bobek&#8203;:\~/pokusy/devel/perl/bug/carp$ \./accum\-hashref\-mortality 
> $args = \[
>           'three'\,
>           \[
>             $args
>           \]\,
>           'one'\,
>           $args\,
>           'two'\,
>           $\{$args\->\[1\]\}
>         \];
> Attempt to free unreferenced scalar&#8203;: SV 0x814cd4c\.
> Attempt to free unreferenced scalar&#8203;: SV 0x814cd28\.
> Attempt to free unreferenced scalar&#8203;: SV 0x816401c\.
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\<output>\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> 
> Yes\, code is ugly\, but I think correct\. Or no?

Looks correct to me\.

> Before this my discovery I believed\, that %$\_ creates in list
> context list which has nothing to do with $\_ after entering
> subrutine any more\. It seems to me\, that when hashref is garbage
> collected\, list created from this hash is also garbage collected?
> 
> This problem I found in perl 5\.8\.x including 5\.8\.8 and 5\.6\.1
> around me\.

I can still reproduce this with the development version\.
Actually\, it even shows one more warning when built with
debug support&#8203;:

&nbsp;  mhx@&#8203;r2d2 ~ $ bleadperl\-debug /tmp/xxx\.pl 
&nbsp;  $args = \[
&nbsp;            'three'\,
&nbsp;            undef\,
&nbsp;            'one'\,
&nbsp;            $args\,
&nbsp;            'two'\,
&nbsp;            \\$args\->\[1\]
&nbsp;          \];
&nbsp;  Attempt to free unreferenced scalar&#8203;: SV 0x82f38f4\, Perl interpreter&#8203;: 0x82d5008\.
&nbsp;  Attempt to free unreferenced scalar&#8203;: SV 0x82d5e04\, Perl interpreter&#8203;: 0x82d5008\.
&nbsp;  Attempt to free temp prematurely&#8203;: SV 0x82d5b34\, Perl interpreter&#8203;: 0x82d5008\.
&nbsp;  Attempt to free unreferenced scalar&#8203;: SV 0x82d5b34\, Perl interpreter&#8203;: 0x82d5008\.

By slightly modifying the script I can even make it segfault&#8203;:

&nbsp;  mhx@&#8203;r2d2 ~ $ cat /tmp/xxx\.pl 
&nbsp;  \#\!/usr/bin/perl \-w
&nbsp;  
&nbsp;  sub foo
&nbsp;  \{
&nbsp;      undef $\_;
&nbsp;      \\@&#8203;\_;
&nbsp;  \}
&nbsp;  
&nbsp;  $\_ = \{
&nbsp;      one => 1\,
&nbsp;      two => 2\,
&nbsp;      three => 3\,
&nbsp;  \};
&nbsp;  
&nbsp;  foo\(%$\_\);

&nbsp;  mhx@&#8203;r2d2 ~ $ bleadperl\-debug /tmp/xxx\.pl 
&nbsp;  Segmentation fault

&nbsp;  mhx@&#8203;r2d2 ~ $ gdb bleadperl\-debug             
&nbsp;  GNU gdb 6\.4
&nbsp;  Copyright 2005 Free Software Foundation\, Inc\.
&nbsp;  GDB is free software\, covered by the GNU General Public License\, and you are
&nbsp;  welcome to change it and/or distribute copies of it under certain conditions\.
&nbsp;  Type "show copying" to see the conditions\.
&nbsp;  There is absolutely no warranty for GDB\.  Type "show warranty" for details\.
&nbsp;  This GDB was configured as "i686\-pc\-linux\-gnu"\.\.\.Using host libthread\_db library "/lib/tls/libthread\_db\.so\.1"\.
&nbsp;  
&nbsp;  \(gdb\) r /tmp/xxx\.pl 
&nbsp;  Starting program&#8203;: /home/mhx/apps/bin/bleadperl\-debug /tmp/xxx\.pl
&nbsp;  \[Thread debugging using libthread\_db enabled\]
&nbsp;  \[New Thread \-1210788176 \(LWP 10997\)\]
&nbsp;  
&nbsp;  Program received signal SIGSEGV\, Segmentation fault\.
&nbsp;  \[Switching to Thread \-1210788176 \(LWP 10997\)\]
&nbsp;  0x080a3416 in Perl\_mg\_free \(my\_perl=0x82d5008\, sv=0x82f3954\) at mg\.c&#8203;:471
&nbsp;  471             const MGVTBL\* const vtbl = mg\->mg\_virtual;
&nbsp;  \(gdb\) bt
&nbsp;  \#0  0x080a3416 in Perl\_mg\_free \(my\_perl=0x82d5008\, sv=0x82f3954\) at mg\.c&#8203;:471
&nbsp;  \#1  0x08108fd9 in Perl\_sv\_clear \(my\_perl=0x82d5008\, sv=0x82f3954\) at sv\.c&#8203;:5085
&nbsp;  \#2  0x08109b32 in Perl\_sv\_free2 \(my\_perl=0x82d5008\, sv=0x82f3954\) at sv\.c&#8203;:5276
&nbsp;  \#3  0x080bf0f2 in Perl\_av\_undef \(my\_perl=0x82d5008\, av=0x82f3a80\) at av\.c&#8203;:481
&nbsp;  \#4  0x081091e2 in Perl\_sv\_clear \(my\_perl=0x82d5008\, sv=0x82f3a80\) at sv\.c&#8203;:5116
&nbsp;  \#5  0x08109b32 in Perl\_sv\_free2 \(my\_perl=0x82d5008\, sv=0x82f3a80\) at sv\.c&#8203;:5276
&nbsp;  \#6  0x0810980a in Perl\_sv\_clear \(my\_perl=0x82d5008\, sv=0x82d5c9c\) at sv\.c&#8203;:5152
&nbsp;  \#7  0x08109b32 in Perl\_sv\_free2 \(my\_perl=0x82d5008\, sv=0x82d5c9c\) at sv\.c&#8203;:5276
&nbsp;  \#8  0x0815bfc5 in Perl\_free\_tmps \(my\_perl=0x82d5008\) at scope\.c&#8203;:156
&nbsp;  \#9  0x080c9f83 in perl\_run \(my\_perl=0x82d5008\) at perl\.c&#8203;:2316
&nbsp;  \#10 0x080603ff in main \(argc=2\, argv=0xbfd266a4\, env=0xbfd266b0\) at perlmain\.c&#8203;:103
&nbsp;  \(gdb\) p mg
&nbsp;  $1 = \(MAGIC \*\) 0x8021101
&nbsp;  \(gdb\) p mg\->mg\_virtual 
&nbsp;  Cannot access memory at address 0x8021105

With pre\-5\.6\.0 perls\, your script runs just fine&#8203;:

&nbsp;  mhx@&#8203;r2d2 ~ $ /tmp/perl/install/debug/perl5\.005\_04/bin/perl5\.00504 /tmp/xxx\.pl 
&nbsp;  $args = \[
&nbsp;            'three'\,
&nbsp;            3\,
&nbsp;            'two'\,
&nbsp;            2\,
&nbsp;            'one'\,
&nbsp;            1
&nbsp;          \];

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Jul 13\, 2006 at 12&#8203;:08&#8203;:54AM \+0200\, Marcus Holland\-Moritz wrote&#8203;:
> I can still reproduce this with the development version\.
> Actually\, it even shows one more warning when built with
> debug support&#8203;:

This is all because the perl stack \(and @&#8203;\_\) isn't refcounted \(and can't
easily be made so\)\. So if things are put on the stack and then freed\, Bad
things happen\.

\-\- 
Hofstadter's Law&#8203;: It always takes longer than you expect\, even when you
take into account Hofstadter's Law\.

**Comment by p5pRT** [comment]
p5p@spam.wizbit.be - Status changed from 'open' to 'stalled'

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'stalled' to 'open'
