### ISSUE TITLE
utf8-related crash

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8530]
Migrated from [rt.perl.org#39870](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=39870) (status was 'resolved')

Searchable as RT39870$

**Comment by p5pRT** [comment]
### From vvv@vsu.ru


This is a bug report for perl from vvv@&#8203;vsu\.ru\,
generated with the help of perlbug 1\.35 running under perl v5\.8\.8\.




---
\[Please enter your report here\]

here is a file test\.pl\, uuencoded to preserve the non\-ascii characters&#8203;:

**Comment by p5pRT** [comment]
### From vvv@vsu.ru

[test.pl](https://rt-archive.perl.org/perl5/Ticket/Attachment/138755/92496/test.pl)

**Comment by p5pRT** [comment]
### From peter.karl.mueller@gmx.de

> ·

**Comment by p5pRT** [comment]
### From @andk

>>>>> On Tue\, 18 Jul 2006 18&#8203;:01&#8203;:51 \-0700\, "vvv@&#8203;vsu\.ru \(via RT\)" \<perlbug\-followup@&#8203;perl\.org> said&#8203;:

Workaround is simple&#8203;: you really want

&nbsp;    use utf8;

instead of the rather clumsy

&nbsp;    use encoding "utf8";

It's still a bug in 'use encoding'\, of course\.

\-\- 
andreas

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @andk

>>>>> On Thu\, 20 Jul 2006 09&#8203;:29&#8203;:59 \+0200\, andreas\.koenig\.gmwojprw@&#8203;franz\.ak\.mind\.de \(Andreas J\. Koenig\) said&#8203;:

>>>>> On Tue\, 18 Jul 2006 18&#8203;:01&#8203;:51 \-0700\, "vvv@&#8203;vsu\.ru \(via RT\)" \<perlbug\-followup@&#8203;perl\.org> said&#8203;:
&nbsp;  > Workaround is simple&#8203;: you really want

&nbsp;  >     use utf8;

&nbsp;  > instead of the rather clumsy

&nbsp;  >     use encoding "utf8";

&nbsp;  > It's still a bug in 'use encoding'\, of course\.

As a further datapoint\, I just tried with bleadperl after patch 28603&#8203;:

% \./installed\-perls/perl/pMHbXRG/perl\-5\.8\.0@&#8203;28603/bin/perl  tests/vvv\-utf8\.pl
\*\*\* glibc detected \*\*\* double free or corruption \(\!prev\)&#8203;: 0x083362b0 \*\*\*
zsh&#8203;: abort \(core dumped\)  \./installed\-perls/perl/pMHbXRG/perl\-5\.8\.0@&#8203;28603/bin/perl tests/vvv\-utf8\.pl
% gdb \./installed\-perls/perl/pMHbXRG/perl\-5\.8\.0@&#8203;28603/bin/perl  core
GNU gdb 6\.4\.90\-debian
Copyright \(C\) 2006 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and you are
welcome to change it and/or distribute copies of it under certain conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for details\.
This GDB was configured as "i486\-linux\-gnu"\.\.\.Using host libthread\_db library "/lib/tls/libthread\_db\.so\.1"\.


warning&#8203;: Can't read pathname for load map&#8203;: Input/output error\.
Reading symbols from /lib/tls/libnsl\.so\.1\.\.\.done\.
Loaded symbols for /lib/tls/libnsl\.so\.1
Reading symbols from /lib/tls/libdl\.so\.2\.\.\.done\.
Loaded symbols for /lib/tls/libdl\.so\.2
Reading symbols from /lib/tls/libm\.so\.6\.\.\.done\.
Loaded symbols for /lib/tls/libm\.so\.6
Reading symbols from /lib/tls/libcrypt\.so\.1\.\.\.done\.
Loaded symbols for /lib/tls/libcrypt\.so\.1
Reading symbols from /lib/tls/libutil\.so\.1\.\.\.done\.
Loaded symbols for /lib/tls/libutil\.so\.1
Reading symbols from /lib/tls/libc\.so\.6\.\.\.done\.
Loaded symbols for /lib/tls/libc\.so\.6
Reading symbols from /lib/ld\-linux\.so\.2\.\.\.done\.
Loaded symbols for /lib/ld\-linux\.so\.2
Reading symbols from /home/src/perl/repoperls/installed\-perls/perl/pMHbXRG/perl\-5\.8\.0@&#8203;28603/lib/5\.9\.4/i686\-linux\-64int/auto/Encode/Encode\.so\.\.\.done\.
Loaded symbols for /home/src/perl/repoperls/installed\-perls/perl/pMHbXRG/perl\-5\.8\.0@&#8203;28603/lib/5\.9\.4/i686\-linux\-64int/auto/Encode/Encode\.so
Reading symbols from /home/src/perl/repoperls/installed\-perls/perl/pMHbXRG/perl\-5\.8\.0@&#8203;28603/lib/5\.9\.4/i686\-linux\-64int/auto/PerlIO/encoding/encoding\.so\.\.\.done\.
Loaded symbols for /home/src/perl/repoperls/installed\-perls/perl/pMHbXRG/perl\-5\.8\.0@&#8203;28603/lib/5\.9\.4/i686\-linux\-64int/auto/PerlIO/encoding/encoding\.so
Core was generated by \`\./installed\-perls/perl/pMHbXRG/perl\-5\.8\.0@&#8203;28603/bin/perl tests/vvv\-utf8\.pl'\.
Program terminated with signal 6\, Aborted\.
\#0  0xa7e527c7 in raise \(\) from /lib/tls/libc\.so\.6
\(gdb\) bt
\#0  0xa7e527c7 in raise \(\) from /lib/tls/libc\.so\.6
\#1  0xa7e5406b in abort \(\) from /lib/tls/libc\.so\.6
\#2  0xa7e89545 in \_\_fsetlocking \(\) from /lib/tls/libc\.so\.6
\#3  0xa7e8fb97 in malloc\_usable\_size \(\) from /lib/tls/libc\.so\.6
\#4  0xa7e90032 in free \(\) from /lib/tls/libc\.so\.6
\#5  0x0808f7c9 in Perl\_safesysfree \(where=0x83362b0\) at util\.c&#8203;:250
\#6  0x08258909 in Perl\_pregfree \(r=0x83362b0\) at regcomp\.c&#8203;:6791
\#7  0x0805f301 in Perl\_op\_clear \(o=0x8337fa8\) at op\.c&#8203;:471
\#8  0x0805ef8b in Perl\_op\_free \(o=0x8337fa8\) at op\.c&#8203;:329
\#9  0x0805ef40 in Perl\_op\_free \(o=0x82a65d0\) at op\.c&#8203;:318
\#10 0x0805ef40 in Perl\_op\_free \(o=0x8367fa0\) at op\.c&#8203;:318
\#11 0x0805ef40 in Perl\_op\_free \(o=0x82a6710\) at op\.c&#8203;:318
\#12 0x080b8e4a in perl\_destruct \(my\_perl=0x829e008\) at perl\.c&#8203;:753
\#13 0x0805e9a1 in main \(argc=2\, argv=0xaf8fac14\, env=0xaf8fac20\)
&nbsp;    at perlmain\.c&#8203;:115
\(gdb\) 


\-\- 
andreas

**Comment by p5pRT** [comment]
p5p@spam.wizbit.be - Status changed from 'open' to 'resolved'
