### ISSUE TITLE
segmentation fault upon syntax check

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8547]
Migrated from [rt.perl.org#40014](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=40014) (status was 'rejected')

Searchable as RT40014$

**Comment by p5pRT** [comment]
### From sturm@erisiandiscord.de

#### Created by sturm@erisiandiscord.de


Performing a syntax check on a trivial perl script that uses
SVN&#8203;::Core of subversion\, results in a segmentation fault\.

$ echo 'use SVN&#8203;::Core;' > tmp\.pl
$ echo 'print "Hello world\!\\n";' >> tmp\.pl
$ perl \-c tmp\.pl
tmp\.pl syntax OK
Segmentation fault \(core dumped\)

Here is the backtrace&#8203;:

\#0  Perl\_sv\_setiv \(sv=0x0\, i=7\) at /usr/src/gnu/usr\.bin/perl/sv\.c&#8203;:1692
\#1  0x09f6fb51 in \_wrap\_val\_current\_pool \(sv=0x7e0808e0\, mg=0x88a3e840\)
&nbsp;    at core\.c&#8203;:1319
\#2  0x0785f56d in Perl\_mg\_get \(sv=0x81add1bc\)
&nbsp;    at /usr/src/gnu/usr\.bin/perl/mg\.c&#8203;:169
\#3  0x078b84c4 in Perl\_pp\_defined \(\) at /usr/src/gnu/usr\.bin/perl/pp\.c&#8203;:764
\#4  0x0789d5b9 in Perl\_runops\_standard \(\) at /usr/src/gnu/usr\.bin/perl/run\.c&#8203;:37
\#5  0x07884008 in S\_call\_body \(myop=0xcf7d7ad0\, is\_eval=7 '\\a'\)
&nbsp;    at /usr/src/gnu/usr\.bin/perl/perl\.c&#8203;:2733
\#6  0x07883e11 in Perl\_call\_sv \(sv=0x89a98c54\, flags=150\)
&nbsp;    at /usr/src/gnu/usr\.bin/perl/perl\.c&#8203;:2648
\#7  0x07858609 in Perl\_sv\_clear \(sv=0x8a9b5c6c\)
&nbsp;    at /usr/src/gnu/usr\.bin/perl/sv\.c&#8203;:5175
\#8  0x07858ce7 in Perl\_sv\_free \(sv=0x8a9b5c6c\)
&nbsp;    at /usr/src/gnu/usr\.bin/perl/sv\.c&#8203;:5429
\#9  0x0785202b in do\_clean\_objs \(sv=0x861fdca8\)
&nbsp;    at /usr/src/gnu/usr\.bin/perl/sv\.c&#8203;:422
\#10 0x07851fc6 in S\_visit \(f=0x7851fd8 \<do\_clean\_objs>\, flags=524288\, 
&nbsp;    mask=524288\) at /usr/src/gnu/usr\.bin/perl/sv\.c&#8203;:368
\#11 0x07852115 in Perl\_sv\_clean\_objs \(\) at /usr/src/gnu/usr\.bin/perl/sv\.c&#8203;:466
\#12 0x078820fb in perl\_destruct \(my\_perl=0x7d3ce030\)
&nbsp;    at /usr/src/gnu/usr\.bin/perl/perl\.c&#8203;:844
\#13 0x1c001282 in main \(\)

I am not sure whether this is a bug in perl\, SVN&#8203;::Core or swig\, 
which was used to generate the offending C file\. But my feeling is
that perl should not rely on external code and if it did\, that should 
be clearly documented\. I was however not able to find any documentation
suggesting that \_wrap\_val\_current\_pool\(\) is wrong\.

The offending function in
subversion\-1\.3\.2/subversion/bindings/swig/perl/native/core\.c is

SWIGCLASS\_STATIC int \_wrap\_val\_current\_pool\(pTHX\_ SV \*sv\, MAGIC \*mg\) \{
&nbsp;    MAGIC\_PPERL
&nbsp;    mg = mg;
&nbsp;    sv\_setiv\(SvRV\(sv\)\,\(IV\) current\_pool\);
&nbsp;    return 1;
\}

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.8.8:

Configured by root at Thu Jan  1  0:00:00 UTC 1970.

Summary of my perl5 (revision 5 version 8 subversion 8) configuration:
  Platform:
    osname=openbsd, osvers=4.0, archname=i386-openbsd
    uname='openbsd'
    config_args='-dsE -Dopenbsd_distribution=defined'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -fno-delete-null-pointer-checks -pipe -I/usr/local/include',
    optimize='-O2',
    cppflags='-fno-strict-aliasing -fno-delete-null-pointer-checks -pipe -I/usr/local/include'
    ccversion='', gccversion='3.3.5 (propolice)', gccosandvers='openbsd3.9'
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags ='-Wl,-E '
    libpth=/usr/lib
    libs=-lm -lutil -lc
    perllibs=-lm -lutil -lc
    libc=/usr/lib/libc.a, so=so, useshrplib=true, libperl=libperl.so.10.1
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-R/usr/libdata/perl5/i386-openbsd/5.8.8/CORE'
    cccdlflags='-DPIC -fPIC ', lddlflags='-shared -fPIC '

Locally applied patches:
    


@INC for perl v5.8.8:
    /usr/libdata/perl5/i386-openbsd/5.8.8
    /usr/local/libdata/perl5/i386-openbsd/5.8.8
    /usr/libdata/perl5
    /usr/local/libdata/perl5
    /usr/local/libdata/perl5/site_perl/i386-openbsd
    /usr/libdata/perl5/site_perl/i386-openbsd
    /usr/local/libdata/perl5/site_perl
    /usr/libdata/perl5/site_perl
    /usr/local/lib/perl5/site_perl
    .


Environment for perl v5.8.8:
    HOME=/home/sturm
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/games:/usr/X11R6/bin:.:/home/sturm/bin
    PERL_BADLANG (unset)
    SHELL=/bin/ksh

```
</details>

**Comment by p5pRT** [comment]
### From @JohnPeacock

sturm@&#8203;erisiandiscord\.de \(via RT\) wrote&#8203;:
> I am not sure whether this is a bug in perl\, SVN&#8203;::Core or swig\, 
> which was used to generate the offending C file\. But my feeling is
> that perl should not rely on external code and if it did\, that should 
> be clearly documented\. I was however not able to find any documentation
> suggesting that \_wrap\_val\_current\_pool\(\) is wrong\.

This is not the appropriate place to report this particular bug\.  SVN&#8203;::Core is
supported by the Subversion project and should be the first place to report such
errors\.  Please be sure to include all relevant details\, such as Perl version\,
SWIG version\, compiler and platform\.  Loading bad code into Perl isn't something
that the Perl code can fix alone\.

FWIW\, I use SVK every single day with a variety of Subversion and SWIG releases
and it works fine\.  There is something specific about your build environment
that is causing the problem you are reporting\.\.\.

John

John


\-\- 
John Peacock
Director of Information Research and Technology
Rowman & Littlefield Publishing Group
4501 Forbes Blvd
Suite H
Lanham\, MD 20706
301\-459\-3366 x\.5010
fax 301\-429\-5747

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
p5p@spam.wizbit.be - Status changed from 'open' to 'rejected'
