### ISSUE TITLE
XML-Twig-3.26's Tests Cause bleadperl to segfault

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8622]
Migrated from [rt.perl.org#40420](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=40420) (status was 'resolved')

Searchable as RT40420$

**Comment by p5pRT** [comment]
### From @shlomif

#### Created by @shlomif



The XML\-Twig\-3\.26's tests cause bleadperl to segfault\. I'm using Mandriva
2007 on a Pentium 4 2\.4 GHz machine\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl 5.9.4:

Configured by shlomi at Tue Sep 26 14:10:55 IDT 2006.

Summary of my perl5 (revision 5 version 9 subversion 4 patch 28891) configuration:
  Platform:
    osname=linux, osvers=2.6.17.13-mm-desktop-1mdvsmp, archname=i686-linux
    uname='linux localhost 2.6.17.13-mm-desktop-1mdvsmp #1 smp preempt tue sep 12 17:44:56 cest 2006 i686 intel(r) pentium(r) 4 cpu 2.40ghz gnulinux '
    config_args='-de -Dprefix=/home/cpan/apps/perl/perl-5.9.4 -Dusedevel'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=undef, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm',
    optimize='-O2',
    cppflags='-fno-strict-aliasing -pipe -I/usr/local/include -I/usr/include/gdbm'
    ccversion='', gccversion='4.1.1 20060724 (prerelease) (4.1.1-3mdk)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/libc-2.4.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.4'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl 5.9.4:
    /home/cpan/apps/perl/perl-5.9.4/lib/5.9.4/i686-linux
    /home/cpan/apps/perl/perl-5.9.4/lib/5.9.4
    /home/cpan/apps/perl/perl-5.9.4/lib/site_perl/5.9.4/i686-linux
    /home/cpan/apps/perl/perl-5.9.4/lib/site_perl/5.9.4
    .


Environment for perl 5.9.4:
    HOME=/home/cpan
    LANG=en_US
    LANGUAGE=en_US:en
    LC_ADDRESS=he_IL
    LC_COLLATE=en_US
    LC_CTYPE=en_US
    LC_IDENTIFICATION=he_IL
    LC_MEASUREMENT=he_IL
    LC_MESSAGES=en_US
    LC_MONETARY=he_IL
    LC_NAME=he_IL
    LC_NUMERIC=he_IL
    LC_PAPER=he_IL
    LC_SOURCED=1
    LC_TELEPHONE=he_IL
    LC_TIME=en_US
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/apps/perl/perl-5.9.4/bin/:/bin:/usr/bin:/usr/local/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/games:/usr/lib/qt3//bin:/home/cpan/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @doughera88

On Wed\, 27 Sep 2006\, Shlomi Fish wrote&#8203;:

> \# New Ticket Created by  Shlomi Fish 
> \# Please include the string&#8203;:  \[perl \#40420\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: http&#8203;://rt\.perl\.org/rt3/Ticket/Display\.html?id=40420 >

> This is a bug report for perl from shlomif@&#8203;iglu\.org\.il\,
> generated with the help of perlbug 1\.35 running under perl 5\.9\.4\.
> 

> The XML\-Twig\-3\.26's tests cause bleadperl to segfault\. I'm using Mandriva
> 2007 on a Pentium 4 2\.4 GHz machine\.

Which tests?  I just tried with a fresh bleadperl install on Debian Linux\,
and I got

Failed Test          Stat Wstat Total Fail  List of Failed


---
t/test\_3\_26\.t           2   512    13    4  12\-13
t/test\_additional\.t     2   512   647  620  338\-647
t/test\_bugs\_3\_18\.t      2   512   157   12  152\-157
t/test\_errors\.t                   110    1  98
t/test\_safe\_encode\.t  255 65280     8   16  1\-8
Failed 5/87 test scripts\. 327/2054 subtests failed\.
Files=87\, Tests=2054\, 24 wallclock secs \(22\.36 cusr \+  1\.05 csys = 23\.41 CPU\)
Failed 5/87 test programs\. 327/2054 subtests failed\.

Although 327 subtests failed\, I don't see any core files left behind\, and 
I see no obvious segfaults\.  

\-\- 
&nbsp;    Andy Dougherty        doughera@&#8203;lafayette\.edu

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @rgarcia

On 27/09/06\, Andy Dougherty \<doughera@&#8203;lafayette\.edu> wrote&#8203;:
> > The XML\-Twig\-3\.26's tests cause bleadperl to segfault\. I'm using Mandriva
> > 2007 on a Pentium 4 2\.4 GHz machine\.
>
> Which tests?  I just tried with a fresh bleadperl install on Debian Linux\,
> and I got
>
> Failed Test          Stat Wstat Total Fail  List of Failed
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> t/test\_3\_26\.t           2   512    13    4  12\-13
> t/test\_additional\.t     2   512   647  620  338\-647
> t/test\_bugs\_3\_18\.t      2   512   157   12  152\-157
> t/test\_errors\.t                   110    1  98
> t/test\_safe\_encode\.t  255 65280     8   16  1\-8
> Failed 5/87 test scripts\. 327/2054 subtests failed\.
> Files=87\, Tests=2054\, 24 wallclock secs \(22\.36 cusr \+  1\.05 csys = 23\.41 CPU\)
> Failed 5/87 test programs\. 327/2054 subtests failed\.

I have these failures :

Failed Test         Stat Wstat Total Fail  List of Failed


---
t/test\_3\_26\.t          2   512    13    4  12\-13
t/test\_additional\.t    0    11   647   16  640\-647
t/test\_errors\.t                  110    1  98
Failed 3/87 test scripts\. 11/2054 subtests failed\.

and a core file with the following backtrace :

\#0  0x400fb4a1 in free \(\) from /lib/i686/libc\.so\.6
\#1  0x400fcd85 in malloc \(\) from /lib/i686/libc\.so\.6
\#2  0x080b2920 in Perl\_safesysmalloc \(size=96\) at util\.c&#8203;:92
\#3  0x081036fd in Perl\_sv\_grow \(sv=0x8767750\, newlen=96\) at sv\.c&#8203;:1456
\#4  0x08112697 in Perl\_sv\_setsv\_flags \(dstr=0x8767750\, sstr=0x85a9a58\,
flags=2\) at sv\.c&#8203;:3591
\#5  0x081230f6 in Perl\_sv\_mortalcopy \(oldstr=0x85a9a58\) at sv\.c&#8203;:6866
\#6  0x0816f8bc in Perl\_pp\_return \(\) at pp\_ctl\.c&#8203;:2048
\#7  0x080b2148 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1908
\#8  0x080e1487 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2386
\#9  0x080e0ac1 in perl\_run \(my\_perl=0x828d008\) at perl\.c&#8203;:2311
\#10 0x0805e922 in main \(argc=3\, argv=0xbfb663e4\, env=0xbfb663f4\) at
perlmain\.c&#8203;:113

the core file comes from t/test\_additionnal\.t\.

**Comment by p5pRT** [comment]
@rgs - Status changed from 'open' to 'resolved'
