### ISSUE TITLE
weak references cause corruption, crashes etc.

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8705]
Migrated from [rt.perl.org#41061](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=41061) (status was 'abandoned')

Searchable as RT41061$

**Comment by p5pRT** [comment]
### From perlbug@plan9.de

#### Created by perlbug@plan9.de



Hi\!

I seem to be the only user of weak references\, because no matter what\, as
soon as I use them in nontrivial programs\, I start to get random crashes\,
memory corruption or just plain "Attempt to free unreferenced scalar"
messages\.

This is usually triggered by freeing a reference that keeps a big graph of
objects alive that contain many weak references\.

Unfortunately\, all my attempts at either creating a small testcase or at
finding/fixing the bug itself were futile so far\, thus I can only give
some examples and thoughts I have\.

I can currently reproduce the problem in a single case\. Depending on the
architetcure and timing\, I get various outcomes\, for example&#8203;:

&nbsp;   Program received signal SIGSEGV\, Segmentation fault\.
&nbsp;   Perl\_mg\_free \(sv=0x1c8d050\) at mg\.c&#8203;:465
&nbsp;   465             const MGVTBL\* const vtbl = mg\->mg\_virtual;
&nbsp;   \(gdb\) bt
&nbsp;   \#0  Perl\_mg\_free \(sv=0x1c8d050\) at mg\.c&#8203;:465
&nbsp;   \#1  0x000000000049668e in Perl\_sv\_clear \(sv=0x1c8d050\) at sv\.c&#8203;:4370
&nbsp;   \#2  0x000000000049737b in Perl\_sv\_free \(sv=0x1c8d050\) at sv\.c&#8203;:4542
&nbsp;   \#3  0x00000000004c0bb1 in Perl\_leave\_scope \(base=161\) at scope\.c&#8203;:660
&nbsp;   \#4  0x00000000004c58f4 in Perl\_pp\_leaveloop \(\) at pp\_ctl\.c&#8203;:1808
&nbsp;   \#5  0x000000000048a13e in Perl\_runops\_standard \(\) at run\.c&#8203;:37
&nbsp;   \#6  0x000000000041dee7 in Perl\_call\_sv \(sv=0x16fd250\, flags=\<value optimized out>\) at perl\.c&#8203;:2806
&nbsp;   \#7  0x00002b23cb388ad3 in pe\_event\_invoke \(ev=0x1c3d5d0\) at c/ev\.c&#8203;:308
&nbsp;   \#8  0x00002b23cb38a878 in one\_event \(tm=0\.016628742218017578\) at c/queue\.c&#8203;:91
&nbsp;   \#9  0x00002b23cb38aded in XS\_Event\_\_loop \(cv=\<value optimized out>\) at Event\.xs&#8203;:503
&nbsp;   \#10 0x0000000000494308 in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:2869
&nbsp;   \#11 0x000000000048a13e in Perl\_runops\_standard \(\) at run\.c&#8203;:37
&nbsp;   \#12 0x000000000041fe30 in perl\_run \(my\_perl=\<value optimized out>\) at perl\.c&#8203;:2441
&nbsp;   \#13 0x000000000041bcfc in main \(argc=4\, argv=0x7fffe0831ca8\, env=\<value optimized out>\) at perlmain\.c&#8203;:99

mg is 0xff00000000\, and sv is an already freed scalar\.

Same program\, on x86\, crashes in Perl\_mfree because it tries to free magic at 0x00000001 in Perl\_mg\_free\.

Under other circumstances/other programs\, I get similar crashes or
"Attempt to free unreferenced scalar" messages\.

Now\, looking at the backref code in perl\, I see no obviously wrong code\. I
do imagine that those bugs are caused by freeing scalars that are already
free\. Along that line\, this comment in mg\.c scares me&#8203;:

&nbsp;    /\* Not sure why the av can get freed ahead of its sv\, but somehow it does
&nbsp;              in ext/B/t/bytecode\.t test 15 \(involving print \<DATA>\)  \*/

\.\.\. short of global descruction \(which in my eyes is simply a big bug\)
this should indeed not happen\.

Now\, when I set a breakpoint on Perl\_magic\_killbackrefs\, I usually get
backtraces like this&#8203;:

&nbsp;   \#0  Perl\_magic\_killbackrefs \(sv=0x1c8ca50\, mg=0x1c8b420\) at mg\.c&#8203;:2062
&nbsp;   \#1  0x000000000047c892 in Perl\_mg\_free \(sv=0x1c8ca50\) at mg\.c&#8203;:468
&nbsp;   \#2  0x000000000049668e in Perl\_sv\_clear \(sv=0x1c8ca50\) at sv\.c&#8203;:4370
&nbsp;   \#3  0x000000000049737b in Perl\_sv\_free \(sv=0x1c8ca50\) at sv\.c&#8203;:4542
&nbsp;   \#4  0x0000000000496bf5 in Perl\_sv\_clear \(sv=0x1c8c970\) at sv\.c&#8203;:4435
&nbsp;   \#5  0x000000000049737b in Perl\_sv\_free \(sv=0x1c8ca50\) at sv\.c&#8203;:4542
&nbsp;   \#6  0x0000000000488398 in Perl\_av\_undef \(av=0x17298f0\) at av\.c&#8203;:473
&nbsp;   \#7  0x00000000004968b0 in Perl\_sv\_clear \(sv=0x17298f0\) at sv\.c&#8203;:4401
&nbsp;   \#8  0x000000000049737b in Perl\_sv\_free \(sv=0x1c8ca50\) at sv\.c&#8203;:4542
&nbsp;   \#9  0x0000000000496bf5 in Perl\_sv\_clear \(sv=0x1c8cd50\) at sv\.c&#8203;:4435
&nbsp;   \#10 0x000000000049737b in Perl\_sv\_free \(sv=0x1c8ca50\) at sv\.c&#8203;:4542
&nbsp;   \#11 0x00000000004827e5 in Perl\_hv\_free\_ent \(hv=0x1c8cca0\, entry=0x1718778\) at hv\.c&#8203;:1424
&nbsp;   \#12 0x0000000000482f5b in Perl\_hv\_clear \(hv=0x1c8cca0\) at hv\.c&#8203;:1594
&nbsp;   \#13 0x00000000004915e6 in Perl\_pp\_aassign \(\) at pp\_hot\.c&#8203;:1067
&nbsp;   \#14 0x000000000048a13e in Perl\_runops\_standard \(\) at run\.c&#8203;:37
&nbsp;   \#15 0x000000000041dee7 in Perl\_call\_sv \(sv=0x16fd250\, flags=\<value optimized out>\) at perl\.c&#8203;:2806
&nbsp;   \#16 0x00002b91bff03ad3 in pe\_event\_invoke \(ev=0x1c8b390\) at c/ev\.c&#8203;:308
&nbsp;   \#17 0x00002b91bff05878 in one\_event \(tm=0\.016648769378662109\) at c/queue\.c&#8203;:91
&nbsp;   \#18 0x00002b91bff05ded in XS\_Event\_\_loop \(cv=\<value optimized out>\) at Event\.xs&#8203;:503
&nbsp;   \#19 0x0000000000494308 in Perl\_pp\_entersub \(\) at pp\_hot\.c&#8203;:2869
&nbsp;   \#20 0x000000000048a13e in Perl\_runops\_standard \(\) at run\.c&#8203;:37
&nbsp;   \#21 0x000000000041fe30 in perl\_run \(my\_perl=\<value optimized out>\) at perl\.c&#8203;:2441
&nbsp;   \#22 0x000000000041bcfc in main \(argc=4\, argv=0x7fffebcb9138\, env=\<value optimized out>\) at perlmain\.c&#8203;:99

&nbsp;   SV = PVHV\(0x1768880\) at 0x1c8ca50
&nbsp;     REFCNT = 0
&nbsp;     FLAGS = \(RMG\,SHAREKEYS\)
&nbsp;     IV = 0
&nbsp;     NV = 0
&nbsp;     MAGIC = 0x1c8b420
&nbsp;       MG\_VIRTUAL = &PL\_vtbl\_backref
&nbsp;       MG\_TYPE = PERL\_MAGIC\_backref\(\<\)
&nbsp;       MG\_FLAGS = 0x02
&nbsp;         REFCOUNTED
&nbsp;       MG\_OBJ = 0x1c89680
&nbsp;           SV = PVAV\(0x1c8ff90\) at 0x1c89680
&nbsp;             REFCNT = 2
&nbsp;             FLAGS = \(\)
&nbsp;             IV = 0
&nbsp;             NV = 0
&nbsp;             ARRAY = 0x1c8b460
&nbsp;             FILL = \-1
&nbsp;             MAX = 3
&nbsp;             ARYLEN = 0x0
&nbsp;             FLAGS = \(REAL\)
&nbsp;     STASH = 0x123d850     "CFPlus&#8203;::UI&#8203;::Label"
&nbsp;     ARRAY = 0x1cd9270
&nbsp;     KEYS = 0
&nbsp;     FILL = 0
&nbsp;     MAX = 31
&nbsp;     RITER = \-1
&nbsp;     EITER = 0x0

Where sv\_free is called recursively on the same sv repeatedly\. I haven't
seen anything obvious in sv\_free/clear that would cause this to stop it
from working\, but I can imagine that would cause the spurious "Attempt to
unreference scalar" messages\, and maybe the bugs I see\.

Perl\_magic\_backrefs is called often iny my programs\, but the backtraces
are usually not very deep \(straight sv\_free/clear/mg\_free/killbackrefs\)
when it works\, and usually \(always when i check\) like above before it
crashes\.

I hope this helps somebody with more knowledge about the internals :\(

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.8.8:

Configured by Marc Lehmann at Sat Dec  9 14:03:08 CET 2006.

Summary of my perl5 (revision 5 version 8 subversion 8) configuration:
  Platform:
    osname=linux, osvers=2.6.17.6, archname=amd64-linux
    uname='linux cerebro 2.6.17.6 #1 smp fri oct 20 19:28:13 cest 2006 x86_64 gnulinux '
    config_args='-Duselargefiles -Dxxxxuse64bitint -Uuse64bitall -Dusemymalloc=n -Dcc=gcc -Dccflags=-DPERL_DONT_CREATE_GVSV -ggdb -Dcppflags=-DPERL_DONT_CREATE_GVSV -D_GNU_SOURCE -I/opt/include -Doptimize=-O4 -march=opteron -mtune=opteron -funroll-loops -fno-strict-aliasing -Dcccdlflags=-fPIC -Dldflags=-L/opt/perl/lib -L/opt/lib -Dlibs=-ldl -lm -lcrypt -Darchname=amd64-linux -Dprefix=/opt/perl -Dprivlib=/opt/perl/lib/perl5 -Darchlib=/opt/perl/lib/perl5 -Dvendorprefix=/opt/perl -Dvendorlib=/opt/perl/lib/perl5 -Dvendorarch=/opt/perl/lib/perl5 -Dsiteprefix=/opt/perl -Dsitelib=/opt/perl/lib/perl5 -Dsitearch=/opt/perl/lib/perl5 -Dsitebin=/opt/perl/bin -Dman1dir=/opt/perl/man/man1 -Dman3dir=/opt/perl/man/man3 -Dsiteman1dir=/opt/perl/man/man1 -Dsiteman3dir=/opt/perl/man/man3 -Dman1ext=1 -Dman3ext=3 -Dpager=/usr/bin/less -Uafs -Uusesfio -Uusenm -Uuseshrplib -Dd_dosuid -Dusethreads=undef -Duse5005threads=undef -Duseithreads=undef -Dusemultiplicity=undef -Demail=perl-binary@plan9.de -Dcf_email=perl-binary@plan9.de -Dcf_by=Marc Lehmann -Dlocincpth=/opt/perl/include /opt/include -Dmyhostname=localhost -Dmultiarch=undef -Dbin=/opt/perl/bin -Dusedevel -des'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=define use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-DPERL_DONT_CREATE_GVSV -ggdb -fno-strict-aliasing -pipe -Wdeclaration-after-statement -I/opt/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O4 -march=opteron -mtune=opteron -funroll-loops -fno-strict-aliasing',
    cppflags='-DPERL_DONT_CREATE_GVSV -D_GNU_SOURCE -I/opt/include -DPERL_DONT_CREATE_GVSV -ggdb -fno-strict-aliasing -pipe -Wdeclaration-after-statement -I/opt/include'
    ccversion='', gccversion='4.1.2 20061115 (prerelease) (Debian 4.1.1-20)', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags ='-L/opt/perl/lib -L/opt/lib -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-ldl -lm -lcrypt
    perllibs=-ldl -lm -lcrypt
    libc=/lib/libc-2.3.6.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.3.6'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -L/opt/perl/lib -L/opt/lib -L/usr/local/lib'

Locally applied patches:
    MAINT28213


@INC for perl v5.8.8:
    /root/src/sex
    /opt/perl/lib/perl5
    /opt/perl/lib/perl5
    /opt/perl/lib/perl5
    /opt/perl/lib/perl5
    /opt/perl/lib/perl5
    .


Environment for perl v5.8.8:
    HOME=/root
    LANG (unset)
    LANGUAGE (unset)
    LC_CTYPE=de_DE.UTF-8
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/root/s2:/root/s:/opt/bin:/opt/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11/bin:/usr/games:/root/src/uunet:.
    PERL5LIB=/root/src/sex
    PERL5_CPANPLUS_CONFIG=/root/.cpanplus/config
    PERLDB_OPTS=ornaments=0
    PERL_BADLANG (unset)
    PERL_UNICODE=EAL
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, Dec 09\, 2006 at 08&#8203;:19&#8203;:24AM \-0800\, perlbug @&#8203; plan9\. de wrote&#8203;:
>    \#1  0x000000000047c892 in Perl\_mg\_free \(sv=0x1c8ca50\) at mg\.c&#8203;:468
>    \#2  0x000000000049668e in Perl\_sv\_clear \(sv=0x1c8ca50\) at sv\.c&#8203;:4370
>    \#3  0x000000000049737b in Perl\_sv\_free \(sv=0x1c8ca50\) at sv\.c&#8203;:4542
>    \#4  0x0000000000496bf5 in Perl\_sv\_clear \(sv=0x1c8c970\) at sv\.c&#8203;:4435
>    \#5  0x000000000049737b in Perl\_sv\_free \(sv=0x1c8ca50\) at sv\.c&#8203;:4542
>    \#6  0x0000000000488398 in Perl\_av\_undef \(av=0x17298f0\) at av\.c&#8203;:473
>    \#7  0x00000000004968b0 in Perl\_sv\_clear \(sv=0x17298f0\) at sv\.c&#8203;:4401
>    \#8  0x000000000049737b in Perl\_sv\_free \(sv=0x1c8ca50\) at sv\.c&#8203;:4542
>    \#9  0x0000000000496bf5 in Perl\_sv\_clear \(sv=0x1c8cd50\) at sv\.c&#8203;:4435
>    \#10 0x000000000049737b in Perl\_sv\_free \(sv=0x1c8ca50\) at sv\.c&#8203;:4542

This backtrack makes no sense to me\.

sv\_clear\(\) should always be called with the same sv arg as the parent
sv\_free\(\); but it often isn't in the above stack trace\. I see no code in
sv\_free\(\) that could make this happen\.

\-\- 
"I do not resent criticism\, even when\, for the sake of emphasis\,
it parts for the time with reality"\.
&nbsp;    \-\- Winston Churchill\, House of Commons\, 22nd Jan 1941\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

I'm marking this ticket as stalled\, as there is insufficient information
to investigate further

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'open' to 'stalled'

**Comment by p5pRT** [comment]
@dcollinsn - Status changed from 'stalled' to 'abandoned'
