### ISSUE TITLE
bad syntax causes segfault

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8782]
Migrated from [rt.perl.org#41536](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=41536) (status was 'resolved')

Searchable as RT41536$

**Comment by p5pRT** [comment]
### From g@netcraft.com.au

#### Created by g@netcraft.com.au



This bogus program causes perl to segfault instead of printing the
more usual "syntax error" message&#8203;:

$ \./segfault
Segmentation fault
$ cat segfault
\#\!/usr/bin/perl
sub a \{ $\_ = f\($\_\); sub \{\); \}
$ gdb perl
GNU gdb Red Hat Linux \(6\.5\-15\.fc6rh\)
Copyright \(C\) 2006 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and you are
welcome to change it and/or distribute copies of it under certain conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for details\.
This GDB was configured as "i386\-redhat\-linux\-gnu"\.\.\.
\(no debugging symbols found\)
Using host libthread\_db library "/lib/libthread\_db\.so\.1"\.

\(gdb\) set args segfault
\(gdb\) r
Starting program&#8203;: /usr/bin/perl segfault
\(no debugging symbols found\)
\(no debugging symbols found\)
\(no debugging symbols found\)
\(no debugging symbols found\)
\(no debugging symbols found\)
\(no debugging symbols found\)
\(no debugging symbols found\)
\(no debugging symbols found\)
\(no debugging symbols found\)
\(no debugging symbols found\)
\[Thread debugging using libthread\_db enabled\]
\[New Thread \-1208260928 \(LWP 4312\)\]
\(no debugging symbols found\)

Program received signal SIGSEGV\, Segmentation fault\.
\[Switching to Thread \-1208260928 \(LWP 4312\)\]
0x00521471 in Perl\_pad\_free \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi/CORE/libperl\.so
\(gdb\) bt
\#0  0x00521471 in Perl\_pad\_free \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi/CORE/libperl\.so
\#1  0x00511553 in Perl\_op\_clear \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi/CORE/libperl\.so
\#2  0x005138e5 in Perl\_op\_free \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi/CORE/libperl\.so
\#3  0x005138a2 in Perl\_op\_free \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi/CORE/libperl\.so
\#4  0x005138a2 in Perl\_op\_free \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi/CORE/libperl\.so
\#5  0x0051f19b in Perl\_newATTRSUB \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi/CORE/libperl\.so
\#6  0x0050dfe6 in Perl\_yyparse \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi/CORE/libperl\.so
\#7  0x004e9c87 in perl\_free \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi/CORE/libperl\.so
\#8  0x004ec6b9 in perl\_parse \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi/CORE/libperl\.so
\#9  0x08049185 in main \(\)

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

This perlbug was built using Perl v5.8.8 in the Red Hat build system.
It is being executed now by Perl v5.8.8 - Tue Oct  3 11:01:05 EDT 2006.

Site configuration information for perl v5.8.8:

Configured by Red Hat, Inc. at Tue Oct  3 11:01:05 EDT 2006.

Summary of my perl5 (revision 5 version 8 subversion 8) configuration:
  Platform:
    osname=linux, osvers=2.6.9-34.elsmp, archname=i386-linux-thread-multi
    uname='linux hs20-bc2-2.build.redhat.com 2.6.9-34.elsmp #1 smp fri feb 24 16:56:28 est 2006 i686 i686 i386 gnulinux '
    config_args='-des -Doptimize=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables -Dversion=5.8.8 -Dmyhostname=localhost -Dperladmin=root@localhost -Dcc=gcc -Dcf_by=Red Hat, Inc. -Dinstallprefix=/usr -Dprefix=/usr -Darchname=i386-linux -Dvendorprefix=/usr -Dsiteprefix=/usr -Duseshrplib -Dusethreads -Duseithreads -Duselargefiles -Dd_dosuid -Dd_semctl_semun -Di_db -Ui_ndbm -Di_gdbm -Di_shadow -Di_syslog -Dman3ext=3pm -Duseperlio -Dinstallusrbinperl=n -Ubincompat5005 -Uversiononly -Dpager=/usr/bin/less -isr -Dd_gethostent_r_proto -Ud_endhostent_r_proto -Ud_sethostent_r_proto -Ud_endprotoent_r_proto -Ud_setprotoent_r_proto -Ud_endservent_r_proto -Ud_setservent_r_proto -Dinc_version_list=5.8.7 5.8.6 5.8.5 -Dscriptdir=/usr/bin'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -Wdeclaration-after-statement -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm',
    optimize='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -Wdeclaration-after-statement -I/usr/local/include -I/usr/include/gdbm'
    ccversion='', gccversion='4.1.1 20060928 (Red Hat 4.1.1-28)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lresolv -lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lpthread -lc
    perllibs=-lresolv -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
    libc=/lib/libc-2.5.so, so=so, useshrplib=true, libperl=libperl.so
    gnulibc_version='2.5'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E -Wl,-rpath,/usr/lib/perl5/5.8.8/i386-linux-thread-multi/CORE'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.8:
    /usr/lib/perl5/site_perl/5.8.8/i386-linux-thread-multi
    /usr/lib/perl5/site_perl/5.8.7/i386-linux-thread-multi
    /usr/lib/perl5/site_perl/5.8.6/i386-linux-thread-multi
    /usr/lib/perl5/site_perl/5.8.5/i386-linux-thread-multi
    /usr/lib/perl5/site_perl/5.8.8
    /usr/lib/perl5/site_perl/5.8.7
    /usr/lib/perl5/site_perl/5.8.6
    /usr/lib/perl5/site_perl/5.8.5
    /usr/lib/perl5/site_perl
    /usr/lib/perl5/vendor_perl/5.8.8/i386-linux-thread-multi
    /usr/lib/perl5/vendor_perl/5.8.7/i386-linux-thread-multi
    /usr/lib/perl5/vendor_perl/5.8.6/i386-linux-thread-multi
    /usr/lib/perl5/vendor_perl/5.8.5/i386-linux-thread-multi
    /usr/lib/perl5/vendor_perl/5.8.8
    /usr/lib/perl5/vendor_perl/5.8.7
    /usr/lib/perl5/vendor_perl/5.8.6
    /usr/lib/perl5/vendor_perl/5.8.5
    /usr/lib/perl5/vendor_perl
    /usr/lib/perl5/5.8.8/i386-linux-thread-multi
    /usr/lib/perl5/5.8.8
    .


Environment for perl v5.8.8:
    HOME=/h/g
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/java/jre1.3.1/bin:/usr/java/jre1.3.1/bin:/usr/lib/qt-3.3/bin:/usr/kerberos/bin:/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:/sbin:/usr/sbin:/h/g/bin:/sbin:/usr/sbin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

-- 
Geoffrey D. Bennett, RHCE, RHCX               mailto:g@netcraft.com.au
Senior Systems Engineer                          sip:g@netcraft.com.au
NetCraft Australia Pty Ltd        http://www.netcraft.com.au/geoffrey/

```
</details>

**Comment by p5pRT** [comment]
### From @rgs

This segfault appears to have been resolved in the development version
of perl\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

This segfault appears to have been resolved in the development version
of perl\.

**Comment by p5pRT** [comment]
@rgs - Status changed from 'new' to 'resolved'
