### ISSUE TITLE
Blead segfaults on local *@; eval {1}

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8913]
Migrated from [rt.perl.org#43073](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=43073) (status was 'resolved')

Searchable as RT43073$

**Comment by p5pRT** [comment]
### From eirik@allverden.no

#### Created by eirik@blackbox.dav



To demonstrate&#8203;:

eirik@&#8203;blackbox\[05&#8203;:14&#8203;:50\]~$ bleadperl \-e 'local \*@&#8203;; eval \{1\}'
Segmentation fault
eirik@&#8203;blackbox\[05&#8203;:16&#8203;:50\]~$ 

If I trace or step through the code in the debugger\, it terminates
successfully at the end of the code \(which made this failure a pain to
track down\)\.  Otherwise it segfaults in the debugger as well\.

It's just blead\, as far as I can tell\.  This runs just fine in 5\.8\.8
and older releases\, as well as in maint \(as of a week ago\, at least\)\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.9.5:

Configured by eirik at Wed May 30 04:30:09 CEST 2007.

Summary of my perl5 (revision 5 version 9 subversion 5 patch 31308) configuration:
  Platform:
    osname=linux, osvers=2.6.17.1320070524, archname=i686-linux
    uname='linux blackbox 2.6.17.1320070524 #1 thu may 24 11:29:03 cest 2007 i686 pentium4 i386 gnulinux '
    config_args='-des -Dusedevel -Dprefix=/opt/perl-blead'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=undef, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2',
    cppflags='-fno-strict-aliasing -pipe -I/usr/local/include'
    ccversion='', gccversion='3.4.6', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/libc-2.3.6.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.3.6'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -L/usr/local/lib'

Locally applied patches:
    DEVEL


@INC for perl 5.9.5:
    /opt/perl-blead/lib/5.9.5/i686-linux
    /opt/perl-blead/lib/5.9.5
    /opt/perl-blead/lib/site_perl/5.9.5/i686-linux
    /opt/perl-blead/lib/site_perl/5.9.5
    .


Environment for perl 5.9.5:
    HOME=/home/eirik
    LANG=en_US
    LANGUAGE (unset)
    LC_COLLATE=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:/usr/games:/usr/lib/java/bin:/usr/lib/java/jre/bin:/usr/local/apache/bin:/local/bin:/home/eirik/bin:/home/eirik/reddwarf/bin:/opt/kde/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @nwc10

On Tue\, May 29\, 2007 at 09&#8203;:26&#8203;:54PM \-0700\, eirik @&#8203; allverden\. no wrote&#8203;:

Thanks for the report

> eirik@&#8203;blackbox\[05&#8203;:14&#8203;:50\]~$ bleadperl \-e 'local \*@&#8203;; eval \{1\}'
> Segmentation fault
> eirik@&#8203;blackbox\[05&#8203;:16&#8203;:50\]~$ 

> It's just blead\, as far as I can tell\.  This runs just fine in 5\.8\.8
> and older releases\, as well as in maint \(as of a week ago\, at least\)\.

==10919== Invalid read of size 4
==10919==    at 0x8107B0D&#8203;: Perl\_sv\_setpvn \(sv\.c&#8203;:3859\)
==10919==    by 0x81641CD&#8203;: Perl\_create\_eval\_scope \(pp\_ctl\.c&#8203;:3620\)
==10919==    by 0x81641FF&#8203;: Perl\_pp\_entertry \(pp\_ctl\.c&#8203;:3630\)
==10919==    by 0x80AD2F2&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:1920\)
==10919==  Address 0x8 is not stack'd\, malloc'd or \(recently\) free'd
==10919== 
==10919== \-\-\-\- Attach to debugger ? \-\-\- \[Return/N/n/Y/y/C/c\] \-\-\-\- y

0x08107b0d in Perl\_sv\_setpvn \(sv=0x0\, ptr=0x8254c40 ""\, len=0\) at sv\.c&#8203;:3859
3859        SV\_CHECK\_THINKFIRST\_COW\_DROP\(sv\);
\(gdb\) up
\#1  0x081641ce in Perl\_create\_eval\_scope \(flags=0\) at pp\_ctl\.c&#8203;:3620
3620            sv\_setpvn\(ERRSV\,""\,0\);
\(gdb\) P PL\_errgv
$1 = \(GV \*\) 0x1bab42c0

\(gdb\) p \*\(PL\_errgv\->sv\_u\.svu\_gp\)
$4 = \{gp\_sv = 0x0\, gp\_io = 0x0\, gp\_cv = 0x0\, gp\_cvgen = 0\, gp\_refcnt = 1\,
&nbsp;  gp\_hv = 0x0\, gp\_av = 0x0\, gp\_form = 0x0\, gp\_egv = 0x1bab42c0\, gp\_line = 1\,
&nbsp;  gp\_file\_hek = 0x1bac4d64\}

so\, ERRSV is clearly a NULL pointer\. But quite why\, I don't know\.
And whether it's "allowed" to be\, I also don't know\.

Nicholas Clark

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @smpeters

On Wed\, May 30\, 2007 at 06&#8203;:20&#8203;:47PM \+0100\, Nicholas Clark wrote&#8203;:
> On Tue\, May 29\, 2007 at 09&#8203;:26&#8203;:54PM \-0700\, eirik @&#8203; allverden\. no wrote&#8203;:
> 
> Thanks for the report
> 
> > eirik@&#8203;blackbox\[05&#8203;:14&#8203;:50\]~$ bleadperl \-e 'local \*@&#8203;; eval \{1\}'
> > Segmentation fault
> > eirik@&#8203;blackbox\[05&#8203;:16&#8203;:50\]~$ 
> 
> > It's just blead\, as far as I can tell\.  This runs just fine in 5\.8\.8
> > and older releases\, as well as in maint \(as of a week ago\, at least\)\.
> 
> ==10919== Invalid read of size 4
> ==10919==    at 0x8107B0D&#8203;: Perl\_sv\_setpvn \(sv\.c&#8203;:3859\)
> ==10919==    by 0x81641CD&#8203;: Perl\_create\_eval\_scope \(pp\_ctl\.c&#8203;:3620\)
> ==10919==    by 0x81641FF&#8203;: Perl\_pp\_entertry \(pp\_ctl\.c&#8203;:3630\)
> ==10919==    by 0x80AD2F2&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:1920\)
> ==10919==  Address 0x8 is not stack'd\, malloc'd or \(recently\) free'd
> ==10919== 
> ==10919== \-\-\-\- Attach to debugger ? \-\-\- \[Return/N/n/Y/y/C/c\] \-\-\-\- y
> 
> 0x08107b0d in Perl\_sv\_setpvn \(sv=0x0\, ptr=0x8254c40 ""\, len=0\) at sv\.c&#8203;:3859
> 3859        SV\_CHECK\_THINKFIRST\_COW\_DROP\(sv\);
> \(gdb\) up
> \#1  0x081641ce in Perl\_create\_eval\_scope \(flags=0\) at pp\_ctl\.c&#8203;:3620
> 3620            sv\_setpvn\(ERRSV\,""\,0\);
> \(gdb\) P PL\_errgv
> $1 = \(GV \*\) 0x1bab42c0
> 
> \(gdb\) p \*\(PL\_errgv\->sv\_u\.svu\_gp\)
> $4 = \{gp\_sv = 0x0\, gp\_io = 0x0\, gp\_cv = 0x0\, gp\_cvgen = 0\, gp\_refcnt = 1\,
>   gp\_hv = 0x0\, gp\_av = 0x0\, gp\_form = 0x0\, gp\_egv = 0x1bab42c0\, gp\_line = 1\,
>   gp\_file\_hek = 0x1bac4d64\}
> 
> so\, ERRSV is clearly a NULL pointer\. But quite why\, I don't know\.
> And whether it's "allowed" to be\, I also don't know\.
> 

Looking in perl\.c\, my guess is that it shouldn't be allowed to be NULL\.
PL\_errgv is initialized along with the rest of the stash in S\_init\_main\_stash\(\)\.
If PL\_errgv is NULL\, then I'd not be surprised if other necessary things are
missing as well\.

\(This is the point Dave M\. usually pulls out his wand\, repeating his incantation
mentioning stashes and COPs until my eyes water\.  Suddenly\, a fix appears\.\)

Steve Peters
steve@&#8203;fisharerojo\.org

**Comment by p5pRT** [comment]
### From @avar

On 5/30/07\, Steve Peters \<steve@&#8203;fisharerojo\.org> wrote&#8203;:
> Looking in perl\.c\, my guess is that it shouldn't be allowed to be NULL\.
> PL\_errgv is initialized along with the rest of the stash in
> S\_init\_main\_stash\(\)\.
> If PL\_errgv is NULL\, then I'd not be surprised if other necessary things are
> missing as well\.

PL\_errgv\->sv\_u\.svu\_gp\->gp\_sv is actually NULL here\, not the PL\_errgv GV\.

**Comment by p5pRT** [comment]
### From @avar

Changing&#8203;:

\#define ERRSV GvSV\(PL\_errgv\)

to&#8203;:

\#define ERRSV GvSVn\(PL\_errgv\)

Would work around this\, whether it's a proper fix I don't know\.

**Comment by p5pRT** [comment]
### From @jbenjore

On 5/29/07\, via RT eirik @&#8203; allverden\. no \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> eirik@&#8203;blackbox\[05&#8203;:14&#8203;:50\]~$ bleadperl \-e 'local \*@&#8203;; eval \{1\}'

> It's just blead\, as far as I can tell\.  This runs just fine in 5\.8\.8
> and older releases\, as well as in maint \(as of a week ago\, at least\)\.

I've just moved to a new house and don't have easy access to my stack
of perls but I've expected for quite some time now that that
localizing \*@&#8203; is asking for segfaults\. I'm just now realizing I should
have filed a bug against that and perhaps fixed it\.\.\.

Anyway\, my memory is that this has existed as a problem for a while
now and wouldn't be new to blead\.

Josh

**Comment by p5pRT** [comment]
### From @nwc10

On Wed\, May 30\, 2007 at 06&#8203;:34&#8203;:28PM \+0000\, var Arnfjr Bjarmason wrote&#8203;:
> Changing&#8203;:
> 
> \#define ERRSV GvSV\(PL\_errgv\)
> 
> to&#8203;:
> 
> \#define ERRSV GvSVn\(PL\_errgv\)
> 
> Would work around this\, whether it's a proper fix I don't know\.

Yes\, I think that it would actually be a correct fix\. But I think that the
appended fix would be more efficient\.

Nicholas Clark

Change 31313 by nicholas@&#8203;nicholas\-saigo on 2007/05/31 08&#8203;:25&#8203;:57

&nbsp;    blead segfaults on local \*@&#8203;; eval \{1\} because ERRSV assumes that
&nbsp;    GvSV\(PL\_errgv\) is always non\-NULL\. That stopped being the case with
&nbsp;    change 25009 \(ish\) \- when we stopped automatically creating a\(n unused\)
&nbsp;    SV at GV creation time\.

Affected files \.\.\.

\.\.\. //depot/perl/scope\.c\#210 edit
\.\.\. //depot/perl/t/op/local\.t\#36 edit

Differences \.\.\.

==== //depot/perl/scope\.c\#210 \(text\) ====

@&#8203;@&#8203; \-261\,6 \+261\,14 @&#8203;@&#8203;
&nbsp;         gp\->gp\_io = newIO\(\);
&nbsp;         IoFLAGS\(gp\->gp\_io\) |= IOf\_ARGV|IOf\_START;
&nbsp;     \}
\+\#ifdef PERL\_DONT\_CREATE\_GVSV
\+    if \(gv == PL\_errgv\) \{
\+        /\* We could scatter this logic everywhere by changing the
\+           definition of ERRSV from GvSV\(\) to GvSVn\(\)\, but it seems more
\+           efficient to do this check once here\.  \*/
\+        gp\->gp\_sv = newSV\(0\);
\+    \}
\+\#endif
&nbsp;     GvGP\(gv\) = gp;
&nbsp;     \}
&nbsp;     else \{

==== //depot/perl/t/op/local\.t\#36 \(xtext\) ====

@&#8203;@&#8203; \-5\,7 \+5\,7 @&#8203;@&#8203;
&nbsp;     @&#8203;INC = qw\(\. \.\./lib\);
&nbsp;     require '\./test\.pl';
 \}
\-plan tests => 120;
\+plan tests => 122;
 
 my $list\_assignment\_supported = 1;
 
@&#8203;@&#8203; \-453\,3 \+453\,12 @&#8203;@&#8203;
&nbsp;     ok\(\! exists\($h\{'k2'\}\)\);
&nbsp;     is\($h\{'k1'\}\,111\);
 \}
\+
\+\# Keep this test last\, as it can SEGV
\+\{
\+    local \*@&#8203;;
\+    pass\("Localised \*@&#8203;"\);
\+    eval \{1\};
\+    pass\("Can eval with \*@&#8203; localised"\);
\+\}
\+

**Comment by p5pRT** [comment]
p5p@spam.wizbit.be - Status changed from 'open' to 'resolved'
