### ISSUE TITLE
"warn" causes segmentation fault in Encode

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8928]
Migrated from [rt.perl.org#43214](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=43214) (status was 'resolved')

Searchable as RT43214$

**Comment by p5pRT** [comment]
### From vincent-perl@vinc17.net

#### Created by vincent@vinc17.org



The following script causes a segmentation fault&#8203;:

\#\!/usr/bin/env perl

use strict;
use I18N&#8203;::Langinfo qw\(langinfo CODESET\);

my $encoding = langinfo CODESET;
print "Encoding&#8203;: $encoding\\n";

my $agrave = chr\(0xe0\);
my $str = "A grave = '$agrave'";
print "Test 1\\n";
print STDERR "   print&#8203;: $str\\n";
print "Test 2\\n";
warn "    warn&#8203;: $str\\n";
binmode STDERR\, "&#8203;:encoding\($encoding\)";
print "Test 3\\n";
print STDERR "   print&#8203;: $str\\n";
print "Test 4\\n";
warn "    warn&#8203;: $str\\n";

$ \./warntest
Encoding&#8203;: ISO\-8859\-1
Test 1
&nbsp;   print&#8203;: A grave = 'à'
Test 2
&nbsp;    warn&#8203;: A grave = 'à'
Test 3
&nbsp;   print&#8203;: A grave = 'à'
Test 4
zsh&#8203;: segmentation fault \(core dumped\)  \./warntest

The backtrace&#8203;:

\(gdb\) bt
\#0  0xb7e6effc in \_int\_malloc \(\) from /lib/i686/cmov/libc\.so\.6
\#1  0xb7e70d0e in malloc \(\) from /lib/i686/cmov/libc\.so\.6
\#2  0x080ac83f in Perl\_safesysmalloc \(\)
\#3  0x080cae8c in Perl\_sv\_grow \(\)
\#4  0x080cafa3 in Perl\_newSV \(\)
\#5  0xb7ba6fd3 in ?? \(\) from /usr/lib/perl/5\.8/auto/Encode/Encode\.so
\#6  0x0814e008 in ?? \(\)
\#7  0x00000401 in ?? \(\)
\#8  0x00000000 in ?? \(\)

There seems to be something wrong with the backtrace\. With 5\.8\.7\,
there was an infinite recursion\, as shown by&#8203;:

&nbsp;  http&#8203;://bugs\.debian\.org/cgi\-bin/bugreport\.cgi?bug=343831

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl v5.8.8:

Configured by Debian Project at Wed Dec  6 23:17:41 UTC 2006.

Summary of my perl5 (revision 5 version 8 subversion 8) configuration:
  Platform:
    osname=linux, osvers=2.6.18.3, archname=i486-linux-gnu-thread-multi
    uname='linux saens 2.6.18.3 #1 smp sat nov 25 13:39:52 est 2006 i686 gnulinux '
    config_args='-Dusethreads -Duselargefiles -Dccflags=-DDEBIAN -Dcccdlflags=-fPIC -Darchname=i486-linux-gnu -Dprefix=/usr -Dprivlib=/usr/share/perl/5.8 -Darchlib=/usr/lib/perl/5.8 -Dvendorprefix=/usr -Dvendorlib=/usr/share/perl5 -Dvendorarch=/usr/lib/perl5 -Dsiteprefix=/usr/local -Dsitelib=/usr/local/share/perl/5.8.8 -Dsitearch=/usr/local/lib/perl/5.8.8 -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 -Dsiteman1dir=/usr/local/man/man1 -Dsiteman3dir=/usr/local/man/man3 -Dman1ext=1 -Dman3ext=3perl -Dpager=/usr/bin/sensible-pager -Uafs -Ud_csh -Uusesfio -Uusenm -Duseshrplib -Dlibperl=libperl.so.5.8.8 -Dd_dosuid -des'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -DDEBIAN -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -DDEBIAN -fno-strict-aliasing -pipe -I/usr/local/include'
    ccversion='', gccversion='4.1.2 20061115 (prerelease) (Debian 4.1.1-20)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lgdbm -lgdbm_compat -ldb -ldl -lm -lpthread -lc -lcrypt
    perllibs=-ldl -lm -lpthread -lc -lcrypt
    libc=/lib/libc-2.3.6.so, so=so, useshrplib=true, libperl=libperl.so.5.8.8
    gnulibc_version='2.3.6'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl v5.8.8:
    /home/vlefevre/lib/site_perl/i486-linux-gnu-thread-multi
    /home/vlefevre/lib/site_perl
    /etc/perl
    /usr/local/lib/perl/5.8.8
    /usr/local/share/perl/5.8.8
    /usr/lib/perl5
    /usr/share/perl5
    /usr/lib/perl/5.8
    /usr/share/perl/5.8
    /usr/local/lib/site_perl
    .


Environment for perl v5.8.8:
    HOME=/home/vlefevre
    LANG=POSIX
    LANGUAGE (unset)
    LC_COLLATE=POSIX
    LC_CTYPE=en_US.ISO8859-1
    LC_TIME=en_DK
    LD_LIBRARY_PATH=/lib:/home/vlefevre/i686/lib:/home/vlefevre/lib
    LOGDIR (unset)
    PATH=/home/vlefevre/bin:/home/vlefevre/i686/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/games:/usr/milip-local/stow/maple-10/maple/bin:.
    PERL5LIB=/home/vlefevre/lib/site_perl
    PERL_BADLANG (unset)
    SHELL=zsh

```
</details>

**Comment by p5pRT** [comment]
### From @smpeters

On Thu Jun 14 03&#8203;:57&#8203;:22 2007\, vincent \<\!\-\- x \-\-> at vinc17\.org wrote&#8203;:
> 
> This is a bug report for perl from vincent \<\!\-\- x \-\-> at vinc17\.org\,
> generated with the help of perlbug 1\.35 running under perl v5\.8\.8\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> 
> The following script causes a segmentation fault&#8203;:
> 
> \#\!/usr/bin/env perl
> 
> use strict;
> use I18N&#8203;::Langinfo qw\(langinfo CODESET\);
> 
> my $encoding = langinfo CODESET;
> print "Encoding&#8203;: $encoding\\n";
> 
> my $agrave = chr\(0xe0\);
> my $str = "A grave = '$agrave'";
> print "Test 1\\n";
> print STDERR "   print&#8203;: $str\\n";
> print "Test 2\\n";
> warn "    warn&#8203;: $str\\n";
> binmode STDERR\, "&#8203;:encoding\($encoding\)";
> print "Test 3\\n";
> print STDERR "   print&#8203;: $str\\n";
> print "Test 4\\n";
> warn "    warn&#8203;: $str\\n";
> 
> $ \./warntest
> Encoding&#8203;: ISO\-8859\-1
> Test 1
>    print&#8203;: A grave = 'à'
> Test 2
>     warn&#8203;: A grave = 'à'
> Test 3
>    print&#8203;: A grave = 'à'
> Test 4
> zsh&#8203;: segmentation fault \(core dumped\)  \./warntest
> 
> The backtrace&#8203;:
> 
> \(gdb\) bt
> \#0  0xb7e6effc in \_int\_malloc \(\) from /lib/i686/cmov/libc\.so\.6
> \#1  0xb7e70d0e in malloc \(\) from /lib/i686/cmov/libc\.so\.6
> \#2  0x080ac83f in Perl\_safesysmalloc \(\)
> \#3  0x080cae8c in Perl\_sv\_grow \(\)
> \#4  0x080cafa3 in Perl\_newSV \(\)
> \#5  0xb7ba6fd3 in ?? \(\) from /usr/lib/perl/5\.8/auto/Encode/Encode\.so
> \#6  0x0814e008 in ?? \(\)
> \#7  0x00000401 in ?? \(\)
> \#8  0x00000000 in ?? \(\)
> 
> There seems to be something wrong with the backtrace\. With 5\.8\.7\,
> there was an infinite recursion\, as shown by&#8203;:
> 
>   http&#8203;://bugs\.debian\.org/cgi\-bin/bugreport\.cgi?bug=343831
> 

I can't reproduce this problem\, but I also don't know what version of
Encode you're using\.  Please reply to this email with the output from\.\.\.

&nbsp;    perl \-MEncode \-wle'print $Encode&#8203;::VERSION'

Thanks\!

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From vincent-perl@vinc17.net

On 2007\-06\-29 09&#8203;:05&#8203;:41 \-0700\, Steve Peters via RT wrote&#8203;:
> I can't reproduce this problem\, but I also don't know what version of
> Encode you're using\.  Please reply to this email with the output from\.\.\.
> 
>     perl \-MEncode \-wle'print $Encode&#8203;::VERSION'

$ perl \-MEncode \-wle'print $Encode&#8203;::VERSION'
2\.12

Note&#8203;: the module is provided by the Debian perl package \(current
perl package version&#8203;: 5\.8\.8\-7\)\.

\-\- 
Vincent Lefèvre \<vincent@&#8203;vinc17\.org> \- Web&#8203;: \<http&#8203;://www\.vinc17\.org/>
100% accessible validated \(X\)HTML \- Blog&#8203;: \<http&#8203;://www\.vinc17\.org/blog/>
Work&#8203;: CR INRIA \- computer arithmetic / Arenaire project \(LIP\, ENS\-Lyon\)

**Comment by p5pRT** [comment]
### From vincent-perl@vinc17.net

Note&#8203;: this is even worse with the C locale&#8203;:

vin% locale
LANG=POSIX
LC\_CTYPE=en\_US\.ISO8859\-1
LC\_NUMERIC="POSIX"
LC\_TIME=en\_DK
LC\_COLLATE=POSIX
LC\_MONETARY="POSIX"
LC\_MESSAGES="POSIX"
LC\_PAPER="POSIX"
LC\_NAME="POSIX"
LC\_ADDRESS="POSIX"
LC\_TELEPHONE="POSIX"
LC\_MEASUREMENT="POSIX"
LC\_IDENTIFICATION="POSIX"
LC\_ALL=
vin% \./warntest 
Encoding&#8203;: ISO\-8859\-1
Test 1
&nbsp;   print&#8203;: A grave = 'à'
Test 2
&nbsp;    warn&#8203;: A grave = 'à'
Test 3
&nbsp;   print&#8203;: A grave = 'à'
Test 4
zsh&#8203;: segmentation fault \(core dumped\)  \./warntest
vin% LC\_ALL=C \./warntest
Encoding&#8203;: ANSI\_X3\.4\-1968
Test 1
&nbsp;   print&#8203;: A grave = 'à'
Test 2
&nbsp;    warn&#8203;: A grave = 'à'
Test 3
zsh&#8203;: segmentation fault \(core dumped\)  LC\_ALL=C \./warntest
vin% 

\-\- 
Vincent Lefèvre \<vincent@&#8203;vinc17\.org> \- Web&#8203;: \<http&#8203;://www\.vinc17\.org/>
100% accessible validated \(X\)HTML \- Blog&#8203;: \<http&#8203;://www\.vinc17\.org/blog/>
Work&#8203;: CR INRIA \- computer arithmetic / Arenaire project \(LIP\, ENS\-Lyon\)

**Comment by p5pRT** [comment]
### From @smpeters

On Fri Jun 29 09&#8203;:25&#8203;:45 2007\, vincent \<\!\-\- x \-\-> at vinc17\.org wrote&#8203;:
> On 2007\-06\-29 09&#8203;:05&#8203;:41 \-0700\, Steve Peters via RT wrote&#8203;:
> > I can't reproduce this problem\, but I also don't know what version of
> > Encode you're using\.  Please reply to this email with the output from\.\.\.
> > 
> >     perl \-MEncode \-wle'print $Encode&#8203;::VERSION'
> 
> $ perl \-MEncode \-wle'print $Encode&#8203;::VERSION'
> 2\.12
> 
> Note&#8203;: the module is provided by the Debian perl package \(current
> perl package version&#8203;: 5\.8\.8\-7\)\.
> 

Can you replicate the problem with the most recent version available on
CPAN \(2\.23\)?

**Comment by p5pRT** [comment]
### From vincent-perl@vinc17.net

On 2007\-06\-29 13&#8203;:58&#8203;:10 \-0700\, Steve Peters via RT wrote&#8203;:
> Can you replicate the problem with the most recent version available
> on CPAN \(2\.23\)?

Same problem \(here under Mac OS X\)&#8203;:

prunille% perl \-MEncode \-wle'print $Encode&#8203;::VERSION'
2\.23
prunille% \./warntest
Encoding&#8203;: ISO8859\-1
Test 1
&nbsp;   print&#8203;: A grave = 'à'
Test 2
&nbsp;    warn&#8203;: A grave = 'à'
Test 3
&nbsp;   print&#8203;: A grave = 'à'
Test 4
zsh&#8203;: segmentation fault  \./warntest
prunille% LC\_ALL=C \./warntest
Encoding&#8203;: US\-ASCII
Test 1
&nbsp;   print&#8203;: A grave = 'à'
Test 2
&nbsp;    warn&#8203;: A grave = 'à'
Test 3
zsh&#8203;: segmentation fault  LC\_ALL=C \./warntest
prunille% 

\-\- 
Vincent Lefèvre \<vincent@&#8203;vinc17\.org> \- Web&#8203;: \<http&#8203;://www\.vinc17\.org/>
100% accessible validated \(X\)HTML \- Blog&#8203;: \<http&#8203;://www\.vinc17\.org/blog/>
Work&#8203;: CR INRIA \- computer arithmetic / Arenaire project \(LIP\, ENS\-Lyon\)

**Comment by p5pRT** [comment]
### From vincent@vinc17.net

With perl 5\.10\.0 and 5\.10\.1\, I no longer get a segmentation fault\,
but the result of Test 4 is incorrect&#8203;:

Encoding&#8203;: ISO\-8859\-1
\[\.\.\.\]
Test 4
&nbsp;    warn&#8203;: A grave = '\\x\{09ca\}

without a newline\, and under UTF\-8 locales&#8203;:

Encoding&#8203;: UTF\-8
\[\.\.\.\]
Test 4
&nbsp;    warn&#8203;: A grave = '\\xE0'

\-\- 
Vincent Lefèvre \<vincent@&#8203;vinc17\.net> \- Web&#8203;: \<http&#8203;://www\.vinc17\.net/>
100% accessible validated \(X\)HTML \- Blog&#8203;: \<http&#8203;://www\.vinc17\.net/blog/>
Work&#8203;: CR INRIA \- computer arithmetic / Arénaire project \(LIP\, ENS\-Lyon\)

**Comment by p5pRT** [comment]
### From @jkeenan

On Thu Oct 29 08&#8203;:56&#8203;:06 2009\, vincent@&#8203;vinc17\.net wrote&#8203;:
> With perl 5\.10\.0 and 5\.10\.1\, I no longer get a segmentation fault\,
> but the result of Test 4 is incorrect&#8203;:
> 
> Encoding&#8203;: ISO\-8859\-1
> \[\.\.\.\]
> Test 4
>     warn&#8203;: A grave = '\\x\{09ca\}
> 
> without a newline\, and under UTF\-8 locales&#8203;:
> 
> Encoding&#8203;: UTF\-8
> \[\.\.\.\]
> Test 4
>     warn&#8203;: A grave = '\\xE0'
> 

There has been no correspondence in this RT in more than four years\.

Tonight I built Perl blead with \-Dusethreads and \-Duselargefiles on the Dromedary server\, then ran the OP's program\.  This was the output&#8203;:

\#\#\#\#\#
$ \./perl \-Ilib \.\./p5p/43214\-langinfo\.pl 
Encoding&#8203;: UTF\-8
Test 1
&nbsp;   print&#8203;: A grave = '?'
Test 2
&nbsp;    warn&#8203;: A grave = '?'
Test 3
&nbsp;   print&#8203;: A grave = 'à'
Test 4
&nbsp;    warn&#8203;: A grave = 'à'
\#\#\#\#\#

Is there still a problem which needs addressing?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From vincent@vinc17.net

On 2013\-12\-15 18&#8203;:58&#8203;:28 \-0800\, James E Keenan via RT wrote&#8203;:
> Is there still a problem which needs addressing?

No\, everything is OK \(both with ISO\-8859\-1 and with UTF\-8\) in
Debian/unstable\, using perl v5\.18\.1\.

This bug can be closed\.

\-\- 
Vincent Lefèvre \<vincent@&#8203;vinc17\.net> \- Web&#8203;: \<http&#8203;://www\.vinc17\.net/>
100% accessible validated \(X\)HTML \- Blog&#8203;: \<http&#8203;://www\.vinc17\.net/blog/>
Work&#8203;: CR INRIA \- computer arithmetic / AriC project \(LIP\, ENS\-Lyon\)

**Comment by p5pRT** [comment]
### From @jkeenan

On Mon Dec 16 10&#8203;:18&#8203;:03 2013\, vincent@&#8203;vinc17\.net wrote&#8203;:
> On 2013\-12\-15 18&#8203;:58&#8203;:28 \-0800\, James E Keenan via RT wrote&#8203;:
> > Is there still a problem which needs addressing?
> 
> No\, everything is OK \(both with ISO\-8859\-1 and with UTF\-8\) in
> Debian/unstable\, using perl v5\.18\.1\.
> 
> This bug can be closed\.
> 

Closing per request from OP\.


Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
@jkeenan - Status changed from 'open' to 'resolved'
