### ISSUE TITLE
Warning and segfault when using use constant and use sub

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9035]
Migrated from [rt.perl.org#45607](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=45607) (status was 'resolved')

Searchable as RT45607$

**Comment by p5pRT** [comment]
### From srezic@cpan.org

This is a bug report for perl from srezic@&#8203;cpan\.org\,
generated with the help of perlbug 1\.36 running under perl 5\.10\.0\.




---
The following script generates a new warning in perl5\.10\.0\, but not
in perl5\.8\.8&#8203;:

&nbsp;     Constant subroutine main&#8203;::BLA redefined at /usr/perl5\.10\.0d/lib/5\.10\.0/subs\.pm line 36\.

Also\, on exit there is a core dump

\#\!perl
use constant BLA => "foo";
use subs qw\(BLA\);
\_\_END\_\_

Here's the backtrace&#8203;:

Program received signal SIGSEGV\, Segmentation fault\.
0x000000000049623e in do\_clean\_named\_objs \(sv=0x6e8b38\) at sv\.c&#8203;:463
463             if \(\(
\(gdb\) bt
\#0  0x000000000049623e in do\_clean\_named\_objs \(sv=0x6e8b38\) at sv\.c&#8203;:463
\#1  0x0000000000495e95 in S\_visit \(f=0x496100 \<do\_clean\_named\_objs>\, 
&nbsp;    flags=32777\, mask=49407\) at sv\.c&#8203;:387
\#2  0x00000000004962f3 in Perl\_sv\_clean\_objs \(\) at sv\.c&#8203;:498
\#3  0x000000000047f7a8 in perl\_destruct \(my\_perl=0x6b9040\) at perl\.c&#8203;:767
\#4  0x000000000041af80 in main \(argc=2\, argv=0x7fffffffe058\, 
&nbsp;    env=0x7fffffffe070\) at perlmain\.c&#8203;:115

Regards\,
&nbsp;    Slaven



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=low


---
Site configuration information for perl 5\.10\.0&#8203;:

Configured by eserte at Wed Sep 19 23&#8203;:41&#8203;:00 CEST 2007\.

Summary of my perl5 \(revision 5 version 10 subversion 0 patch 31894\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=freebsd\, osvers=6\.2\-release\, archname=amd64\-freebsd
&nbsp;    uname='freebsd biokovo\-amd64\.herceg\.de 6\.2\-release freebsd 6\.2\-release \#0&#8203;: fri jan 12 08&#8203;:32&#8203;:24 utc 2007 root@&#8203;portnoy\.cse\.buffalo\.edu&#8203;:usrobjusrsrcsysgeneric amd64 '
&nbsp;    config\_args='\-Dprefix=/usr/perl5\.10\.0 \-D cc=ccache cc \-Dgccansipedantic \-de'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='ccache cc'\, ccflags ='\-DHAS\_FPSETMASK \-DHAS\_FLOATINGPOINT\_H \-fno\-strict\-aliasing \-pipe \-I/usr/local/include'\,
&nbsp;    optimize='\-O2 \-pipe'\,
&nbsp;    cppflags='\-DHAS\_FPSETMASK \-DHAS\_FLOATINGPOINT\_H \-fno\-strict\-aliasing \-pipe \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='3\.4\.6 \[FreeBSD\] 20060305'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ccache cc'\, ldflags ='\-Wl\,\-E  \-L/usr/local/lib'
&nbsp;    libpth=/usr/lib /usr/local/lib
&nbsp;    libs=\-lgdbm \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags='\-DPIC \-fPIC'\, lddlflags='\-shared  \-L/usr/local/lib'

Locally applied patches&#8203;:
&nbsp;    DEVEL



---
@&#8203;INC for perl 5\.10\.0&#8203;:
&nbsp;    /usr/perl5\.10\.0/lib/5\.10\.0/amd64\-freebsd
&nbsp;    /usr/perl5\.10\.0/lib/5\.10\.0
&nbsp;    /usr/perl5\.10\.0/lib/site\_perl/5\.10\.0/amd64\-freebsd
&nbsp;    /usr/perl5\.10\.0/lib/site\_perl/5\.10\.0
&nbsp;    \.



---
Environment for perl 5\.10\.0&#8203;:
&nbsp;    HOME=/home/e/eserte
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LC\_ALL=de\_DE\.ISO8859\-1
&nbsp;    LC\_CTYPE=de\_DE\.ISO8859\-1
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/usr/X11R6/bin&#8203;:/usr/X11/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/gnu/bin&#8203;:/usr/TeX/bin&#8203;:/usr/local/sbin&#8203;:/usr/sbin&#8203;:/sbin&#8203;:/usr/local/pilot/bin&#8203;:/home/e/eserte/bin/FreeBSD&#8203;:/home/e/eserte/bin/sh&#8203;:/home/e/eserte/bin&#8203;:/usr/X386/bin&#8203;:/usr/games&#8203;:/home/e/eserte/devel
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    PERL\_HTML\_DISPLAY\_CLASS=HTML&#8203;::Display&#8203;::Mozilla
&nbsp;    SHELL=/bin/tcsh

**Comment by p5pRT** [comment]
### From @nwc10

On Thu\, Sep 20\, 2007 at 03&#8203;:22&#8203;:47PM \-0700\, srezic @&#8203; cpan\. org wrote&#8203;:
> \# New Ticket Created by  srezic@&#8203;cpan\.org 
> \# Please include the string&#8203;:  \[perl \#45607\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: http&#8203;://rt\.perl\.org/rt3/Ticket/Display\.html?id=45607 >
> 
> 
> This is a bug report for perl from srezic@&#8203;cpan\.org\,
> generated with the help of perlbug 1\.36 running under perl 5\.10\.0\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> The following script generates a new warning in perl5\.10\.0\, but not
> in perl5\.8\.8&#8203;:
> 
>      Constant subroutine main&#8203;::BLA redefined at /usr/perl5\.10\.0d/lib/5\.10\.0/subs\.pm line 36\.
> 
> Also\, on exit there is a core dump
> 
> \#\!perl
> use constant BLA => "foo";
> use subs qw\(BLA\);

Mmm\, that line probably shouldn't warn&#8203;:

sub import \{
&nbsp;    my $callpack = caller;
&nbsp;    my $pack = shift;
&nbsp;    my @&#8203;imports = @&#8203;\_;
&nbsp;    foreach $sym \(@&#8203;imports\) \{
&nbsp;        \*\{"$\{callpack\}&#8203;::$sym"\} = \\&\{"$\{callpack\}&#8203;::$sym"\};
&nbsp;    \}
\};

but thinking about the implementation\, and what happens when\, it might be
tricky to stop it from warning\.

> \_\_END\_\_
> 
> Here's the backtrace&#8203;:
> 
> Program received signal SIGSEGV\, Segmentation fault\.
> 0x000000000049623e in do\_clean\_named\_objs \(sv=0x6e8b38\) at sv\.c&#8203;:463
> 463             if \(\(
> \(gdb\) bt
> \#0  0x000000000049623e in do\_clean\_named\_objs \(sv=0x6e8b38\) at sv\.c&#8203;:463
> \#1  0x0000000000495e95 in S\_visit \(f=0x496100 \<do\_clean\_named\_objs>\, 
>     flags=32777\, mask=49407\) at sv\.c&#8203;:387
> \#2  0x00000000004962f3 in Perl\_sv\_clean\_objs \(\) at sv\.c&#8203;:498
> \#3  0x000000000047f7a8 in perl\_destruct \(my\_perl=0x6b9040\) at perl\.c&#8203;:767
> \#4  0x000000000041af80 in main \(argc=2\, argv=0x7fffffffe058\, 
>     env=0x7fffffffe070\) at perlmain\.c&#8203;:115

I can get a stacktrace earlier than that&#8203;:

==32668== Invalid read of size 4
==32668==    at 0x810EA48&#8203;: Perl\_sv\_force\_normal\_flags \(sv\.c&#8203;:4123\)
==32668==    by 0x80BE38F&#8203;: S\_save\_magic \(mg\.c&#8203;:92\)
==32668==    by 0x80BE5C2&#8203;: Perl\_mg\_get \(mg\.c&#8203;:196\)
==32668==    by 0x81038DD&#8203;: Perl\_sv\_2pv\_flags \(sv\.c&#8203;:2561\)
==32668==    by 0x8115E40&#8203;: Perl\_sv\_cmp \(sv\.c&#8203;:6061\)
==32668==    by 0x8109479&#8203;: S\_glob\_assign\_ref \(sv\.c&#8203;:3302\)
==32668==    by 0x810B458&#8203;: Perl\_sv\_setsv\_flags \(sv\.c&#8203;:3540\)
==32668==    by 0x80E87BF&#8203;: Perl\_pp\_sassign \(pp\_hot\.c&#8203;:184\)
==32668==    by 0x80B249D&#8203;: Perl\_runops\_debug \(dump\.c&#8203;:1918\)
==32668==    by 0x80E08F4&#8203;: Perl\_call\_sv \(perl\.c&#8203;:2593\)
==32668==    by 0x80E6FF3&#8203;: Perl\_call\_list \(perl\.c&#8203;:5075\)
==32668==    by 0x806F118&#8203;: S\_process\_special\_blocks \(op\.c&#8203;:5626\)
==32668==    by 0x806EF56&#8203;: Perl\_newATTRSUB \(op\.c&#8203;:5599\)
==32668==    by 0x8067C84&#8203;: Perl\_utilize \(op\.c&#8203;:3757\)
==32668==    by 0x823056E&#8203;: Perl\_yyparse \(perly\.y&#8203;:654\)
==32668==    by 0x80DEEE4&#8203;: S\_parse\_body \(perl\.c&#8203;:2180\)
==32668==    by 0x80DD976&#8203;: perl\_parse \(perl\.c&#8203;:1618\)
==32668==    by 0x805EF15&#8203;: main \(perlmain\.c&#8203;:111\)
==32668==  Address 0xC is not stack'd\, malloc'd or \(recently\) free'd
==32668==
==32668== Process terminating with default action of signal 11 \(SIGSEGV\)

Not sure why\, and not time today to investigate\.

Nicholas Clark

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@nwc10 - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @nwc10

On Fri\, Sep 21\, 2007 at 12&#8203;:25&#8203;:44PM \+0100\, Nicholas Clark wrote&#8203;:
> On Thu\, Sep 20\, 2007 at 03&#8203;:22&#8203;:47PM \-0700\, srezic @&#8203; cpan\. org wrote&#8203;:
> > \# New Ticket Created by  srezic@&#8203;cpan\.org 
> > \# Please include the string&#8203;:  \[perl \#45607\]
> > \# in the subject line of all future correspondence about this issue\. 
> > \# \<URL&#8203;: http&#8203;://rt\.perl\.org/rt3/Ticket/Display\.html?id=45607 >
> > 
> > 
> > This is a bug report for perl from srezic@&#8203;cpan\.org\,
> > generated with the help of perlbug 1\.36 running under perl 5\.10\.0\.
> > 
> > 
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > The following script generates a new warning in perl5\.10\.0\, but not
> > in perl5\.8\.8&#8203;:
> > 
> >      Constant subroutine main&#8203;::BLA redefined at /usr/perl5\.10\.0d/lib/5\.10\.0/subs\.pm line 36\.
> > 
> > Also\, on exit there is a core dump
> > 
> > \#\!perl
> > use constant BLA => "foo";
> > use subs qw\(BLA\);
> 
> Mmm\, that line probably shouldn't warn&#8203;:
> 
> sub import \{
>     my $callpack = caller;
>     my $pack = shift;
>     my @&#8203;imports = @&#8203;\_;
>     foreach $sym \(@&#8203;imports\) \{
>         \*\{"$\{callpack\}&#8203;::$sym"\} = \\&\{"$\{callpack\}&#8203;::$sym"\};
>     \}
> \};
> 
> but thinking about the implementation\, and what happens when\, it might be
> tricky to stop it from warning\.

Fixing the bug fixed the warning\. \(change 31940\)\. It's a sutle corner case\.

For the general case\, what happens for \*\{"GLIPP"\} = \\&\{"BONK"\} is that the
peephole optimiser spots that construction\, and adds flags to two of the ops
to make the code lookup return a scalar reference if possible\, and the glob
assignment to assign that reference direct to the symbol table if possible\,
otherwise fix things up as if there had never been any cheating&#8203;:

The corner case is when $&#8203;::BONK is a reference\, and you execute
\*\{"BONK"\} = \\&\{"BONK"\}


Step 1&#8203;:  ops for \\&\{"BONK"\}; return us the constant in the symbol table
Step 2&#8203;:  ops for \*\{"BONK"\} cause that symbol table entry \(and our reference
&nbsp;         to it\) to be upgraded from RV to typeblob\)
Step 3&#8203;:  We got to the code that attempted to assign the reference into the
&nbsp;         symbol table\. A new reference needs to be created and the referant
&nbsp;         \(the constant\) pointed to it\. \(Rather than simply bumping the
&nbsp;         reference count of the existing reference\, making a new alias to it\)
&nbsp;         However\, what has happened in step 2 is that the reference placed on
&nbsp;         the stack by step 1 has been converted to a typeglob\, which the old
&nbsp;         code didn't realise could happen\. So it still merrily called SvRV\(\) on
&nbsp;         it to dereference it\, and boom\!

So now the code in step 3 is more robust\, and handles the case of the item
on the stack being changed from RV to PVGV\.

Nicholas Clark
