### ISSUE TITLE
Segfaults examining %+ under debugger

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9065]
Migrated from [rt.perl.org#46433](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=46433) (status was 'resolved')

Searchable as RT46433$

**Comment by p5pRT** [comment]
### From josh@lik.nonet

#### Created by josh@lik.nonet



The following program dereferences a pull pointer in
PL\_curpm\->paren\_names when asked to dump the %\+ hash\.

use feature '&#8203;:5\.10';
for my $\_ \( '123' =~ /\(\.\)/g \) \{
&nbsp;    given \($\_\) \{
&nbsp;        when \(/\(?\<x>\.\)/\) \{
&nbsp;        \}
&nbsp;    \}
\}
say 'ok';


\[lik ~/src/myblead2\]$ ls /home/gdb /opt/perl\-5\.10\.0/bin/perl
GNU gdb 6\.6\-debian
Copyright \(C\) 2006 Free Software Foundation\, Inc\.
GDB is free software\, covered by the GNU General Public License\, and you are
welcome to change it and/or distribute copies of it under certain conditions\.
Type "show copying" to see the conditions\.
There is absolutely no warranty for GDB\.  Type "show warranty" for details\.
This GDB was configured as "i486\-linux\-gnu"\.\.\.
Using host libthread\_db library "/lib/tls/i686/cmov/libthread\_db\.so\.1"\.
\(gdb\) set args \-d /home/josh/Documents/Political\\ Data/er/names
\(gdb\) run
Starting program&#8203;: /opt/perl\-5\.10\.0/bin/perl \-d /home/josh/Documents/Political\\ Data/er/names

Loading DB routines from perl5db\.pl version 1\.3
Editor support available\.

Enter h or \`h h' for help\, or \`man perldebug' for more help\.

main&#8203;::\(/home/josh/Documents/Political Data/er/names&#8203;:2\)&#8203;:
2&#8203;:      for my $\_ \( '123' =~ /\(\.\)/g \) \{
&nbsp;  DB\<1> s
main&#8203;::\(/home/josh/Documents/Political Data/er/names&#8203;:3\)&#8203;:
3&#8203;:          given \($\_\) \{
&nbsp;  DB\<2> x \\%\+
0  HASH\(0x837b4b0\)

Program received signal SIGSEGV\, Segmentation fault\.
0x0809851f in Perl\_hv\_iterinit \(\)
\(gdb\) bt
\#0  0x0809851f in Perl\_hv\_iterinit \(\)
\#1  0x08073f93 in Perl\_reg\_named\_buff\_firstkey \(\)
\#2  0x080fc187 in XS\_Tie\_Hash\_NamedCapture\_FIRSTK \(\)
\#3  0x080a5263 in Perl\_pp\_entersub \(\)
\#4  0x080a3abe in Perl\_runops\_standard \(\)
\#5  0x0809f5f6 in Perl\_call\_sv \(\)
\#6  0x08091638 in Perl\_magic\_nextpack \(\)
\#7  0x08098725 in Perl\_hv\_iternext\_flags \(\)
\#8  0x080e2f0d in Perl\_do\_kv \(\)
\#9  0x080a3abe in Perl\_runops\_standard \(\)
\#10 0x0809ff17 in perl\_run \(\)
\#11 0x080622e5 in main \(\)
\(gdb\) 

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.10.0:

Configured by josh at Sun Oct 14 09:55:17 PDT 2007.

Summary of my perl5 (revision 5 version 10 subversion 0 patch 32107) configuration:
  Platform:
    osname=linux, osvers=2.6.20-16-generic, archname=i686-linux
    uname='linux lik 2.6.20-16-generic #2 smp sun sep 23 19:50:39 utc 2007 i686 gnulinux '
    config_args='-DEBUGGING=both -Dprefix=/opt/perl-5.10.0-dbg -des'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=undef, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-DDEBUGGING -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2 -g',
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe -I/usr/local/include'
    ccversion='', gccversion='4.1.2 (Ubuntu 4.1.2-0ubuntu4)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib /usr/lib64
    libs=-lnsl -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/libc-2.5.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.5'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -g -L/usr/local/lib'

Locally applied patches:
    DEVEL


@INC for perl 5.10.0:
    /opt/perl-5.10.0-dbg/lib/5.10.0/i686-linux
    /opt/perl-5.10.0-dbg/lib/5.10.0
    /opt/perl-5.10.0-dbg/lib/site_perl/5.10.0/i686-linux
    /opt/perl-5.10.0-dbg/lib/site_perl/5.10.0
    .


Environment for perl 5.10.0:
    HOME=/home/josh
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/josh/bin/perl/5.8.8/bin:/home/josh/bin:/home/josh/bin/bin:/home/josh/bin/perl/5.8.8/bin:/home/josh/bin:/home/josh/bin/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @jbenjore

On Sun\, Oct 14\, 2007 at 06&#8203;:02&#8203;:23PM \-0700\, josh@&#8203;lik\.nonet wrote&#8203;:

Fixed by "\[PATCH\] Fix a few segfaults and a when\(\) bug"\. I didn't know
I was going to fix the bug when I reported it\.

Josh

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
@rgs - Status changed from 'open' to 'resolved'
