### ISSUE TITLE
Perl syntax error core dump: syntax error near "; ]"

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9141]
Migrated from [rt.perl.org#48234](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=48234) (status was 'resolved')

Searchable as RT48234$

**Comment by p5pRT** [comment]
### From in-perlbug@baka.org

#### Created by in-perlbug@baka.org


cat > /tmp/x\.pl \<\<'EOF'
sub client\_input
\{
&nbsp;  my \( $heap\, $input \) = @&#8203;\_\[ HEAP\, ARG0 \];
&nbsp;  my \(@&#8203;components\) = split\(/\,/\,$input\);
&nbsp;  find\( sub \{ /\\\.tar\\z/s && \-f $\_ && \( /^FROM\-/ && push\(@&#8203;fromhost\,$File&#8203;::Find&#8203;::name\) || push\(@&#8203;official\,$File&#8203;::Find&#8203;::name\)\); \]\, "/"\);
\}
EOF

perl /tmp/x\.pl
Segmentation fault \(core dumped\)
\(gdb\) where
\#0  Perl\_pad\_free \(po=7\) at pad\.c&#8203;:1180
\#1  0x000000000044b7df in Perl\_op\_clear \(o=0x74a760\) at op\.c&#8203;:515
\#2  0x000000000044cb1e in Perl\_op\_free \(o=0x74a760\) at op\.c&#8203;:379
\#3  0x000000000044caeb in Perl\_op\_free \(o=0x74ab90\) at op\.c&#8203;:367
\#4  0x0000000000455e4c in Perl\_newATTRSUB \(floor=103\, o=\<value optimized out>\, proto=\<value optimized out>\, 
&nbsp;    attrs=\<value optimized out>\, block=0x74ab90\) at op\.c&#8203;:4424
\#5  0x000000000044903b in Perl\_yyparse \(\) at perly\.y&#8203;:364
\#6  0x0000000000427c0f in S\_parse\_body \(env=0x0\, xsinit=0x422270 \<xs\_init>\) at perl\.c&#8203;:2206
\#7  0x000000000042a5a5 in perl\_parse \(my\_perl=\<value optimized out>\, xsinit=0x422270 \<xs\_init>\, argc=2\, argv=0x7fff02a88438\, env=0x0\)
&nbsp;    at perl\.c&#8203;:1598
\#8  0x0000000000422228 in main \(argc=2\, argv=0x7fff02a88438\, env=\<value optimized out>\) at perlmain\.c&#8203;:97

This does not happen on some 32bit machines with very similar perl
distributions installed\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl v5.8.8:

Configured by Gentoo at Sun Nov 25 21:37:09 EST 2007.

Summary of my perl5 (revision 5 version 8 subversion 8) configuration:
  Platform:
    osname=linux, osvers=2.6.22-gentoo-r2, archname=x86_64-linux
    uname='linux startide.sysdetect.com 2.6.22-gentoo-r2 #1 smp fri nov 16 23:24:11 est 2007 x86_64 amd athlon(tm) 64 x2 dual core processor 3800+ authenticamd gnulinux '
    config_args='-des -Darchname=x86_64-linux -Dcccdlflags=-fPIC -Dccdlflags=-rdynamic -Dcc=x86_64-pc-linux-gnu-gcc -Dprefix=/usr -Dvendorprefix=/usr -Dsiteprefix=/usr -Dlocincpth=  -Doptimize=-O2 -g -pipe -march=athlon64 -msse3 -Duselargefiles -Dd_semctl_semun -Dscriptdir=/usr/bin -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 -Dinstallman1dir=/usr/share/man/man1 -Dinstallman3dir=/usr/share/man/man3 -Dman1ext=1 -Dman3ext=3pm -Dinc_version_list=5.8.0 5.8.0/x86_64-linux 5.8.2 5.8.2/x86_64-linux 5.8.4 5.8.4/x86_64-linux 5.8.5 5.8.5/x86_64-linux 5.8.6 5.8.6/x86_64-linux 5.8.7 5.8.7/x86_64-linux  -Dcf_by=Gentoo -Ud_csh -Dusenm -Di_ndbm -Di_gdbm -Di_db -Dusrinc=/usr/include/gentoo-multilib/amd64 -Dlibpth=/usr/local/lib64 /lib64 /usr/lib64'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=define use64bitall=define uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='x86_64-pc-linux-gnu-gcc', ccflags ='-DDEBUGGING -fno-strict-aliasing -pipe -Wdeclaration-after-statement -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2 -g -pipe -march=athlon64 -msse3',
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe -Wdeclaration-after-statement'
    ccversion='', gccversion='4.1.2 (Gentoo 4.1.2)', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='x86_64-pc-linux-gnu-gcc', ldflags =' -L/usr/local/lib64'
    libpth=/usr/local/lib64 /lib64 /usr/lib64
    libs=-lpthread -lnsl -lndbm -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/libc-2.6.1.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.6.1'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib64'

Locally applied patches:
    


@INC for perl v5.8.8:
    /usr/local/lib/perl
    /home/seth/lib/perl
    /usr/local/perl5/lib/site_perl
    /etc/perl
    /usr/lib64/perl5/vendor_perl/5.8.8/x86_64-linux
    /usr/lib64/perl5/vendor_perl/5.8.8
    /usr/lib64/perl5/vendor_perl
    /usr/lib64/perl5/site_perl/5.8.8/x86_64-linux
    /usr/lib64/perl5/site_perl/5.8.8
    /usr/lib64/perl5/site_perl
    /usr/lib64/perl5/5.8.8/x86_64-linux
    /usr/lib64/perl5/5.8.8
    /usr/local/lib/site_perl
    .


Environment for perl v5.8.8:
    HOME=/home/seth
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/seth/bin/shell:/home/seth/bin/perl:/usr/local/bin:/usr/local/sbin:/usr/local/lib:/bin:/usr/bin:/usr/libexec:/usr/sbin:/sbin:/usr/games:/usr/lib:/etc:.
    PERLLIB=/usr/local/lib/perl:/home/seth/lib/perl:/usr/local/perl5/lib/site_perl
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @schwern

in\-perlbug@&#8203;baka\.org \(via RT\) wrote&#8203;:
> cat > /tmp/x\.pl \<\<'EOF'
> sub client\_input
> \{
>   my \( $heap\, $input \) = @&#8203;\_\[ HEAP\, ARG0 \];
>   my \(@&#8203;components\) = split\(/\,/\,$input\);
>   find\( sub \{ /\\\.tar\\z/s && \-f $\_ && \( /^FROM\-/ && push\(@&#8203;fromhost\,$File&#8203;::Find&#8203;::name\) || push\(@&#8203;official\,$File&#8203;::Find&#8203;::name\)\); \]\, "/"\);
> \}
> EOF
> 
> perl /tmp/x\.pl
> Segmentation fault \(core dumped\)
> \(gdb\) where
> \#0  Perl\_pad\_free \(po=7\) at pad\.c&#8203;:1180
> \#1  0x000000000044b7df in Perl\_op\_clear \(o=0x74a760\) at op\.c&#8203;:515
> \#2  0x000000000044cb1e in Perl\_op\_free \(o=0x74a760\) at op\.c&#8203;:379
> \#3  0x000000000044caeb in Perl\_op\_free \(o=0x74ab90\) at op\.c&#8203;:367
> \#4  0x0000000000455e4c in Perl\_newATTRSUB \(floor=103\, o=\<value optimized out>\, proto=\<value optimized out>\, 
>     attrs=\<value optimized out>\, block=0x74ab90\) at op\.c&#8203;:4424
> \#5  0x000000000044903b in Perl\_yyparse \(\) at perly\.y&#8203;:364
> \#6  0x0000000000427c0f in S\_parse\_body \(env=0x0\, xsinit=0x422270 \<xs\_init>\) at perl\.c&#8203;:2206
> \#7  0x000000000042a5a5 in perl\_parse \(my\_perl=\<value optimized out>\, xsinit=0x422270 \<xs\_init>\, argc=2\, argv=0x7fff02a88438\, env=0x0\)
>     at perl\.c&#8203;:1598
> \#8  0x0000000000422228 in main \(argc=2\, argv=0x7fff02a88438\, env=\<value optimized out>\) at perlmain\.c&#8203;:97
> 
> This does not happen on some 32bit machines with very similar perl
> distributions installed\.

FWIW I cannot reproduce on OS X 10\.4\.11 on an original Macbook \(32 bit\) on
5\.5\.5\, 5\.6\.2\, 5\.8\.6\, 5\.8\.8 or bleadperl\.  I get the proper syntax error\.


\-\- 
There will be snacks\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Wed\, Dec 05\, 2007 at 06&#8203;:56&#8203;:46PM \-0800\, Michael G Schwern wrote&#8203;:
> in\-perlbug@&#8203;baka\.org \(via RT\) wrote&#8203;:
> > cat > /tmp/x\.pl \<\<'EOF'
> > sub client\_input
> > \{
> >   my \( $heap\, $input \) = @&#8203;\_\[ HEAP\, ARG0 \];
> >   my \(@&#8203;components\) = split\(/\,/\,$input\);
> >   find\( sub \{ /\\\.tar\\z/s && \-f $\_ && \( /^FROM\-/ && push\(@&#8203;fromhost\,$File&#8203;::Find&#8203;::name\) || push\(@&#8203;official\,$File&#8203;::Find&#8203;::name\)\); \]\, "/"\);
> > \}
> > EOF
> > 
> > perl /tmp/x\.pl
> > Segmentation fault \(core dumped\)
> > \(gdb\) where
> > \#0  Perl\_pad\_free \(po=7\) at pad\.c&#8203;:1180
> > \#1  0x000000000044b7df in Perl\_op\_clear \(o=0x74a760\) at op\.c&#8203;:515
> > \#2  0x000000000044cb1e in Perl\_op\_free \(o=0x74a760\) at op\.c&#8203;:379
> > \#3  0x000000000044caeb in Perl\_op\_free \(o=0x74ab90\) at op\.c&#8203;:367
> > \#4  0x0000000000455e4c in Perl\_newATTRSUB \(floor=103\, o=\<value optimized out>\, proto=\<value optimized out>\, 
> >     attrs=\<value optimized out>\, block=0x74ab90\) at op\.c&#8203;:4424
> > \#5  0x000000000044903b in Perl\_yyparse \(\) at perly\.y&#8203;:364
> > \#6  0x0000000000427c0f in S\_parse\_body \(env=0x0\, xsinit=0x422270 \<xs\_init>\) at perl\.c&#8203;:2206
> > \#7  0x000000000042a5a5 in perl\_parse \(my\_perl=\<value optimized out>\, xsinit=0x422270 \<xs\_init>\, argc=2\, argv=0x7fff02a88438\, env=0x0\)
> >     at perl\.c&#8203;:1598
> > \#8  0x0000000000422228 in main \(argc=2\, argv=0x7fff02a88438\, env=\<value optimized out>\) at perlmain\.c&#8203;:97
> > 
> > This does not happen on some 32bit machines with very similar perl
> > distributions installed\.
> 
> FWIW I cannot reproduce on OS X 10\.4\.11 on an original Macbook \(32 bit\) on
> 5\.5\.5\, 5\.6\.2\, 5\.8\.6\, 5\.8\.8 or bleadperl\.  I get the proper syntax error\.

This should have been fixed in 5\.9\.1 by change \#22306

\-\- 
Never do today what you can put off till tomorrow\.

**Comment by p5pRT** [comment]
p5p@spam.wizbit.be - Status changed from 'open' to 'resolved'
