### ISSUE TITLE
Segmentation fault in Perl 5.8.8 regex engine

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9196]
Migrated from [rt.perl.org#49956](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=49956) (status was 'resolved')

Searchable as RT49956$

**Comment by p5pRT** [comment]
### From wojtyk@eclipse.ncsc.mil


This is a bug report for perl from wojtyk@&#8203;eclipse\.ncsc\.mil\,
generated with the help of perlbug 1\.35 running under perl v5\.8\.8\.




---
Possibly related to prior bug \#33945 \(?\)&#8203;:

Deep recursion in regex engine causes segmentation fault\.

Reproducible sample code&#8203;:

&nbsp;    perl \-le'my $rx="b"\."a"x99999; $rx=~/b\(\[^b\]|c\.\)\+/;'

Snippet from backtrace&#8203;:

\.\.\.
\#4  0x0064536b in Perl\_regclass\_swash \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi/CORE/libperl\.so
\#5  0x0064536b in Perl\_regclass\_swash \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi/CORE/libperl\.so
\#6  0x0064536b in Perl\_regclass\_swash \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi/CORE/libperl\.so
\#7  0x0064536b in Perl\_regclass\_swash \(\)
&nbsp;   from /usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi/CORE/libperl\.so
\.\.\.



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=low


---
This perlbug was built using Perl v5\.8\.8 in the Red Hat build system\.
It is being executed now by Perl v5\.8\.8 \- Mon Nov 12 21&#8203;:35&#8203;:26 EST 2007\.

Site configuration information for perl v5\.8\.8&#8203;:

Configured by Red Hat\, Inc\. at Mon Nov 12 21&#8203;:35&#8203;:26 EST 2007\.

Summary of my perl5 \(revision 5 version 8 subversion 8\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.9\-55\.0\.9\.elsmp\, archname=i386\-linux\-thread\-multi
&nbsp;    uname='linux hs20\-bc2\-2\.build\.redhat\.com 2\.6\.9\-55\.0\.9\.elsmp \#1 smp tue sep 25 02&#8203;:16&#8203;:15 edt 2007 i686 i686 i386 gnulinux '
&nbsp;    config\_args='\-des \-Doptimize=\-O2 \-g \-pipe \-Wall \-Wp\,\-D\_FORTIFY\_SOURCE=2 \-fexceptions \-fstack\-protector \-\-param=ssp\-buffer\-size=4 \-m32 \-march=i386 \-mtune=generic \-fasynchronous\-unwind\-tables \-Dversion=5\.8\.8 \-Dmyhostname=localhost \-Dperladmin=root@&#8203;localhost \-Dcc=gcc \-Dcf\_by=Red Hat\, Inc\. \-Dinstallprefix=/usr \-Dprefix=/usr \-Darchname=i386\-linux \-Dvendorprefix=/usr \-Dsiteprefix=/usr \-Duseshrplib \-Dusethreads \-Duseithreads \-Duselargefiles \-Dd\_dosuid \-Dd\_semctl\_semun \-Di\_db \-Ui\_ndbm \-Di\_gdbm \-Di\_shadow \-Di\_syslog \-Dman3ext=3pm \-Duseperlio \-Dinstallusrbinperl=n \-Ubincompat5005 \-Uversiononly \-Dpager=/usr/bin/less \-isr \-Dd\_gethostent\_r\_proto \-Ud\_endhostent\_r\_proto \-Ud\_sethostent\_r\_proto \-Ud\_endprotoent\_r\_proto \-Ud\_setprotoent\_r\_proto \-Ud\_endservent\_r\_proto \-Ud\_setservent\_r\_proto \-Dinc\_version\_list=5\.8\.7 5\.8\.6 5\.8\.5 \-Dscriptdir=/usr/bin'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-pipe \-Wdeclaration\-after\-statement \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-I/usr/include/gdbm'\,
&nbsp;    optimize='\-O2 \-g \-pipe \-Wall \-Wp\,\-D\_FORTIFY\_SOURCE=2 \-fexceptions \-fstack\-protector \-\-param=ssp\-buffer\-size=4 \-m32 \-march=i386 \-mtune=generic \-fasynchronous\-unwind\-tables'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-pipe \-Wdeclaration\-after\-statement \-I/usr/local/include \-I/usr/include/gdbm'
&nbsp;    ccversion=''\, gccversion='4\.1\.2 20070626 \(Red Hat 4\.1\.2\-13\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='gcc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lresolv \-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    perllibs=\-lresolv \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    libc=/lib/libc\-2\.5\.so\, so=so\, useshrplib=true\, libperl=libperl\.so
&nbsp;    gnulibc\_version='2\.5'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E \-Wl\,\-rpath\,/usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi/CORE'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-g \-pipe \-Wall \-Wp\,\-D\_FORTIFY\_SOURCE=2 \-fexceptions \-fstack\-protector \-\-param=ssp\-buffer\-size=4 \-m32 \-march=i386 \-mtune=generic \-fasynchronous\-unwind\-tables \-L/usr/local/lib'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl v5\.8\.8&#8203;:
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.8/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.7/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.6/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.5/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.8
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.7
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.6
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.5
&nbsp;    /usr/lib/perl5/site\_perl
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.8/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.7/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.6/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.5/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.8
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.7
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.6
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.5
&nbsp;    /usr/lib/perl5/vendor\_perl
&nbsp;    /usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/5\.8\.8
&nbsp;    \.



---
Environment for perl v5\.8\.8&#8203;:
&nbsp;    HOME=/home/wojtyk
&nbsp;    LANG=en\_US\.UTF\-8
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/wojtyk/firefox&#8203;:/usr/kerberos/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/X11R6/bin&#8203;:/home/wojtyk/bin&#8203;:/sbin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @smpeters

On Jan 18\, 2008 3&#8203;:52 PM\, via RT wojtyk @&#8203; eclipse\. ncsc\. mil
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> \# New Ticket Created by  wojtyk@&#8203;eclipse\.ncsc\.mil
> \# Please include the string&#8203;:  \[perl \#49956\]
> \# in the subject line of all future correspondence about this issue\.
> \# \<URL&#8203;: http&#8203;://rt\.perl\.org/rt3/Ticket/Display\.html?id=49956 >
>
>
>
> This is a bug report for perl from wojtyk@&#8203;eclipse\.ncsc\.mil\,
> generated with the help of perlbug 1\.35 running under perl v5\.8\.8\.
>
>
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
>
> Possibly related to prior bug \#33945 \(?\)&#8203;:
>
> Deep recursion in regex engine causes segmentation fault\.
>
> Reproducible sample code&#8203;:
>
>         perl \-le'my $rx="b"\."a"x99999; $rx=~/b\(\[^b\]|c\.\)\+/;'
>
> Snippet from backtrace&#8203;:
>
> \.\.\.
> \#4  0x0064536b in Perl\_regclass\_swash \(\)
>    from /usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi/CORE/libperl\.so
> \#5  0x0064536b in Perl\_regclass\_swash \(\)
>    from /usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi/CORE/libperl\.so
> \#6  0x0064536b in Perl\_regclass\_swash \(\)
>    from /usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi/CORE/libperl\.so
> \#7  0x0064536b in Perl\_regclass\_swash \(\)
>    from /usr/lib/perl5/5\.8\.8/i386\-linux\-thread\-multi/CORE/libperl\.so
> \.\.\.
>

This has been fixed in Perl 5\.10\.

Steve Peters
steve@&#8203;fisharerojo\.org

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
p5p@spam.wizbit.be - Status changed from 'open' to 'resolved'
