### ISSUE TITLE
segfault on perl -e 'split //, unpack "(B)*", "ab"'

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9208]
Migrated from [rt.perl.org#50256](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=50256) (status was 'resolved')

Searchable as RT50256$

**Comment by p5pRT** [comment]
### From @mauke

#### Created by @mauke



% perl \-e 'split //\, unpack "\(B\)\*"\, "ab"'
Segmentation fault

Oh\, those "locally applied patches" below aren't in this perl; they
were from v5\.8\.8\. But 5\.8\.8 also crashes with this code\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

This perlbug was built using Perl v5.8.8 - Wed Mar 22 20:53:12 CET 2006
It is being executed now by  Perl v5.10.0 - Wed Dec 19 19:01:35 CET 2007.

Site configuration information for perl v5.10.0:

Configured by mauke at Wed Dec 19 19:01:35 CET 2007.

Summary of my perl5 (revision 5 version 10 subversion 0) configuration:
  Platform:
    osname=linux, osvers=2.6.22-gentoo-r9, archname=i686-linux
    uname='linux nora 2.6.22-gentoo-r9 #3 preempt sat nov 3 22:12:09 cet 2007 i686 amd athlon(tm) 64 processor 3200+ authenticamd gnulinux '
    config_args=''
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=undef, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm',
    optimize='-O2 -march=native -fomit-frame-pointer',
    cppflags='-fno-strict-aliasing -pipe -I/usr/local/include -I/usr/include/gdbm'
    ccversion='', gccversion='4.2.2', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/libc-2.6.1.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.6.1'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -march=native -fomit-frame-pointer -L/usr/local/lib'

Locally applied patches:
    SAFEARGV0 - disable magic open in <ARGV>
    METHQUAL0 - allow qualified method calls without a valid object
    UNWARN0 - disable stupid warnings for print and qw


@INC for perl v5.10.0:
    /home/mauke/usr/local/lib/perl5/5.10.0/i686-linux
    /home/mauke/usr/local/lib/perl5/5.10.0
    /home/mauke/usr/local/lib/perl5/site_perl/5.10.0/i686-linux
    /home/mauke/usr/local/lib/perl5/site_perl/5.10.0
    .


Environment for perl v5.10.0:
    HOME=/home/mauke
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_COLLATE=POSIX
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/mauke/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/i686-pc-linux-gnu/gcc-bin/4.1.2:/opt/sun-jdk-1.4.2.13/bin:/opt/sun-jdk-1.4.2.13/jre/bin:/opt/sun-jdk-1.4.2.13/jre/javaws:/usr/kde/3.5/bin:/usr/qt/3/bin:/usr/games/bin:/opt/vmware/player/bin
    PERL_BADLANG (unset)
    PERL_UNICODE=SAL
    SHELL=/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @avar

This looks to my untrained eye like something unpack is causing its
return value to be a damaged PMOP\.

&nbsp;    $ \./perl \-le 'split //\, unpack\("\(B\)\*"\, "ab"\)'
&nbsp;    Segmentation fault
&nbsp;    $ \./perl \-le 'my $s = unpack\("\(B\)\*"\, "ab"\); split //\, $s'
&nbsp;    $ \./perl \-le 'my $s = unpack\("\(B\)\*"\, "ab"\); unpack "\(a\)\*"\, $s'
&nbsp;    $ \./perl \-le 'unpack "\(a\)\*"\, unpack\("\(B\)\*"\, "ab"\);'
&nbsp;    Invalid type '0' in unpack at \-e line 1\.

This will actually segfault at different times in Perl\_pp\_split
depending on whether you compile with \-DDEBUGGING or not\, at least on
my system\.

Without debugging\, => marks the segfault&#8203;:

&nbsp;    \#ifdef DEBUGGING
&nbsp;        Copy\(&LvTARGOFF\(POPs\)\, &pm\, 1\, PMOP\*\);
&nbsp;    \#else
&nbsp;        pm = \(PMOP\*\)POPs;
&nbsp;    \#endif
&nbsp;        if \(\!pm || \!s\)
&nbsp;        DIE\(aTHX\_ "panic&#8203;: pp\_split"\);
&nbsp;        rx = PM\_GETRE\(pm\);

&nbsp;    =>  TAINT\_IF\(\(rx\->extflags & RXf\_PMf\_LOCALE\) &&
&nbsp;             \(rx\->extflags & \(RXf\_WHITE | RXf\_SKIPWHITE\)\)\);

In gdb&#8203;:

&nbsp;    Program received signal SIGSEGV\, Segmentation fault\.
&nbsp;    0x00000000004ba3aa in Perl\_pp\_split \(\) at pp\.c&#8203;:4617
&nbsp;    \(gdb\) bt
&nbsp;    \#0  0x00000000004ba3aa in Perl\_pp\_split \(\) at pp\.c&#8203;:4617
&nbsp;    \#1  0x000000000047f9da in Perl\_runops\_standard \(\) at run\.c&#8203;:38
&nbsp;    \#2  0x000000000047a2af in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2384
&nbsp;    \#3  0x0000000000479e4f in perl\_run \(my\_perl=0x7fffffeef970\) at perl\.c&#8203;:2302
&nbsp;    \#4  0x000000000041bfb9 in main \(argc=3\, argv=0x7fffffeefce8\,
env=0x7fffffeefd08\) at perlmain\.c&#8203;:113
&nbsp;    \(gdb\) p pm
&nbsp;    $10 = \(PMOP \*\) 0x6a12f0
&nbsp;    \(gdb\) p rx
&nbsp;    $11 = \(REGEXP \*\) 0x2200000c00000001
&nbsp;    \(gdb\) p \*rx
&nbsp;    Cannot access memory at address 0x2200000c00000001

With debugging&#8203;:

&nbsp;    \#ifdef DEBUGGING
&nbsp;        Copy\(&LvTARGOFF\(POPs\)\, &pm\, 1\, PMOP\*\);
&nbsp;    \#else
&nbsp;        pm = \(PMOP\*\)POPs;
&nbsp;    \#endif
&nbsp;        if \(\!pm || \!s\)
&nbsp;        DIE\(aTHX\_ "panic&#8203;: pp\_split"\);
&nbsp;    =>  rx = PM\_GETRE\(pm\);

in gdb&#8203;:

&nbsp;    Program received signal SIGSEGV\, Segmentation fault\.
&nbsp;    0x00000000004d8aca in Perl\_pp\_split \(\) at pp\.c&#8203;:4615
&nbsp;    \(gdb\) bt
&nbsp;    \#0  0x00000000004d8aca in Perl\_pp\_split \(\) at pp\.c&#8203;:4615
&nbsp;    \#1  0x0000000000468612 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1931
&nbsp;    \#2  0x000000000048cadc in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2384
&nbsp;    \#3  0x000000000048c592 in perl\_run \(my\_perl=0x6dd010\) at perl\.c&#8203;:2302
&nbsp;    \#4  0x000000000041c0c9 in main \(argc=3\, argv=0x7fffffba5e38\,
env=0x7fffffba5e58\) at perlmain\.c&#8203;:113
&nbsp;    \(gdb\) p pm
&nbsp;    $1 = \(PMOP \*\) 0x8

So under debugging the pm from the stack is invalid while without
debugging the regex from the regex pad is\.

\(btw how does one build perl without \-DDEBUGGING properly? I did
\`\./Configure \-Dcc='ccache gcc' \-Dld=gcc \-Doptimize=\-ggdb3 \-d \-e' which
put \-DDEBUGGING in my makefile\, presumably because it picked up
\-ggdb3\, I edited the definition out by hand\)

On 1/26/08\, via RT l\. mai @&#8203; web\. de \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> \# New Ticket Created by  l\.mai@&#8203;web\.de
> \# Please include the string&#8203;:  \[perl \#50256\]
> \# in the subject line of all future correspondence about this issue\.
> \# \<URL&#8203;: http&#8203;://rt\.perl\.org/rt3/Ticket/Display\.html?id=50256 >
>
>
>
> This is a bug report for perl from l\.mai@&#8203;web\.de\,
> generated with the help of perlbug 1\.35 running under perl v5\.10\.0\.
>
>
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
>
> % perl \-e 'split //\, unpack "\(B\)\*"\, "ab"'
> Segmentation fault
>
> Oh\, those "locally applied patches" below aren't in this perl; they
> were from v5\.8\.8\. But 5\.8\.8 also crashes with this code\.
>
> \[Please do not change anything below this line\]
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \-\-\-
> Flags&#8203;:
>     category=core
>     severity=medium
> \-\-\-
> This perlbug was built using Perl v5\.8\.8 \- Wed Mar 22 20&#8203;:53&#8203;:12 CET 2006
> It is being executed now by  Perl v5\.10\.0 \- Wed Dec 19 19&#8203;:01&#8203;:35 CET 2007\.
>
> Site configuration information for perl v5\.10\.0&#8203;:
>
> Configured by mauke at Wed Dec 19 19&#8203;:01&#8203;:35 CET 2007\.
>
> Summary of my perl5 \(revision 5 version 10 subversion 0\) configuration&#8203;:
>   Platform&#8203;:
>     osname=linux\, osvers=2\.6\.22\-gentoo\-r9\, archname=i686\-linux
>     uname='linux nora 2\.6\.22\-gentoo\-r9 \#3 preempt sat nov 3 22&#8203;:12&#8203;:09 cet
> 2007 i686 amd athlon\(tm\) 64 processor 3200\+ authenticamd gnulinux '
>     config\_args=''
>     hint=recommended\, useposix=true\, d\_sigaction=define
>     useithreads=undef\, usemultiplicity=undef
>     useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
>     use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
>     usemymalloc=n\, bincompat5005=undef
>   Compiler&#8203;:
>     cc='gcc'\, ccflags ='\-fno\-strict\-aliasing \-pipe \-I/usr/local/include
> \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-I/usr/include/gdbm'\,
>     optimize='\-O2 \-march=native \-fomit\-frame\-pointer'\,
>     cppflags='\-fno\-strict\-aliasing \-pipe \-I/usr/local/include
> \-I/usr/include/gdbm'
>     ccversion=''\, gccversion='4\.2\.2'\, gccosandvers=''
>     intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
>     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
>     ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,
> lseeksize=8
>     alignbytes=4\, prototype=define
>   Linker and Libraries&#8203;:
>     ld='gcc'\, ldflags =' \-L/usr/local/lib'
>     libpth=/usr/local/lib /lib /usr/lib
>     libs=\-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lc
>     perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
>     libc=/lib/libc\-2\.6\.1\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
>     gnulibc\_version='2\.6\.1'
>   Dynamic Linking&#8203;:
>     dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
>     cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-march=native
> \-fomit\-frame\-pointer \-L/usr/local/lib'
>
> Locally applied patches&#8203;:
>     SAFEARGV0 \- disable magic open in \<ARGV>
>     METHQUAL0 \- allow qualified method calls without a valid object
>     UNWARN0 \- disable stupid warnings for print and qw
>
> \-\-\-
> @&#8203;INC for perl v5\.10\.0&#8203;:
>     /home/mauke/usr/local/lib/perl5/5\.10\.0/i686\-linux
>     /home/mauke/usr/local/lib/perl5/5\.10\.0
>     /home/mauke/usr/local/lib/perl5/site\_perl/5\.10\.0/i686\-linux
>     /home/mauke/usr/local/lib/perl5/site\_perl/5\.10\.0
>     \.
>
> \-\-\-
> Environment for perl v5\.10\.0&#8203;:
>     HOME=/home/mauke
>     LANG=en\_US\.UTF\-8
>     LANGUAGE \(unset\)
>     LC\_COLLATE=POSIX
>     LD\_LIBRARY\_PATH \(unset\)
>     LOGDIR \(unset\)
>
> PATH=/home/mauke/usr/local/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/opt/bin&#8203;:/usr/i686\-pc\-linux\-gnu/gcc\-bin/4\.1\.2&#8203;:/opt/sun\-jdk\-1\.4\.2\.13/bin&#8203;:/opt/sun\-jdk\-1\.4\.2\.13/jre/bin&#8203;:/opt/sun\-jdk\-1\.4\.2\.13/jre/javaws&#8203;:/usr/kde/3\.5/bin&#8203;:/usr/qt/3/bin&#8203;:/usr/games/bin&#8203;:/opt/vmware/player/bin
>     PERL\_BADLANG \(unset\)
>     PERL\_UNICODE=SAL
>     SHELL=/bin/zsh
>
>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tux

On Sat\, 26 Jan 2008 05&#8203;:27&#8203;:05 \+0000\, "Ævar Arnfjörð Bjarmason"
\<avarab@&#8203;gmail\.com> wrote&#8203;:

> This looks to my untrained eye like something unpack is causing its
> return value to be a damaged PMOP\.
> 
>     $ \./perl \-le 'split //\, unpack\("\(B\)\*"\, "ab"\)'
>     Segmentation fault
>     $ \./perl \-le 'my $s = unpack\("\(B\)\*"\, "ab"\); split //\, $s'
>     $ \./perl \-le 'my $s = unpack\("\(B\)\*"\, "ab"\); unpack "\(a\)\*"\, $s'
>     $ \./perl \-le 'unpack "\(a\)\*"\, unpack\("\(B\)\*"\, "ab"\);'
>     Invalid type '0' in unpack at \-e line 1\.
> 
> This will actually segfault at different times in Perl\_pp\_split
> depending on whether you compile with \-DDEBUGGING or not\, at least on
> my system\.
> :
> \(btw how does one build perl without \-DDEBUGGING properly? I did
> \`\./Configure \-Dcc='ccache gcc' \-Dld=gcc \-Doptimize=\-ggdb3 \-d \-e' which
> put \-DDEBUGGING in my makefile\, presumably because it picked up
> \-ggdb3\, I edited the definition out by hand\)

I hope I was explainatory enough in my addition to INSTALL when I added
support for \-DDEBUGGING to Configure&#8203;:

&nbsp;      Building a debugging perl

&nbsp;       You can run perl scripts under the perl debugger at any time with perl
&nbsp;       −d your\_script\.  If\, however\, you want to debug perl itself\, you
&nbsp;       probably want to have support for perl internal debugging code
&nbsp;       \(activated by adding −DDEBUGGING to ccflags\)\, and/or support for the
&nbsp;       system debugger by adding −g to the optimisation flags\. For that\, use
&nbsp;       the parameter&#8203;:

&nbsp;               sh Configure −DDEBUGGING

&nbsp;       or

&nbsp;               sh Configure −DDEBUGGING=\<mode>

&nbsp;       For a more eye appealing call\, −DEBUGGING is defined to be an alias for
&nbsp;       −DDEBUGGING\. For both\, the −U calls are also supported\, in order to be
&nbsp;       able to overrule the hints or Policy\.sh settings\.

&nbsp;       Here are the DEBUGGING modes&#8203;:

&nbsp;       −DDEBUGGING
&nbsp;       −DEBUGGING
&nbsp;       −DEBUGGING=both
&nbsp;           Sets both −DDEBUGGING in the ccflags\, and adds −g to optimize\.

&nbsp;           You can actually specify −g and −DDEBUGGING independently \(see
&nbsp;           below\)\, but usually it’s convenient to have both\.

&nbsp;       −DEBUGGING=−g
&nbsp;       −Doptimize=−g
&nbsp;           Adds −g to optimize\, but does not set −DDEBUGGING\.

&nbsp;           \(Note&#8203;:  Your system may actually require something like cc −g2\.
&nbsp;           Check your man pages for cc\(1\) and also any hint file for your
&nbsp;           system\.\)

&nbsp;       −DEBUGGING=none
&nbsp;       −UDEBUGGING
&nbsp;           Removes −g from optimize\, and −DDEBUGGING from ccflags\.

&nbsp;       If you are using a shared libperl\, see the warnings about multiple
&nbsp;       versions of perl under "Building a shared Perl library"\.

\-\- 
H\.Merijn Brand         Amsterdam Perl Mongers \(http&#8203;://amsterdam\.pm\.org/\)
using & porting perl 5\.6\.2\, 5\.8\.x\, 5\.10\.x  on HP\-UX 10\.20\, 11\.00\, 11\.11\,
& 11\.23\, SuSE 10\.1 & 10\.2\, AIX 5\.2\, and Cygwin\.       http&#8203;://qa\.perl\.org
http&#8203;://mirrors\.develooper\.com/hpux/            http&#8203;://www\.test\-smoke\.org
&nbsp;                        http&#8203;://www\.goldmark\.org/jeff/stupid\-disclaimers/

**Comment by p5pRT** [comment]
### From @nwc10

On Sat\, Jan 26\, 2008 at 05&#8203;:27&#8203;:05AM \+0000\, var Arnfjr Bjarmason wrote&#8203;:
> This looks to my untrained eye like something unpack is causing its
> return value to be a damaged PMOP\.
> 
>     $ \./perl \-le 'split //\, unpack\("\(B\)\*"\, "ab"\)'
>     Segmentation fault
>     $ \./perl \-le 'my $s = unpack\("\(B\)\*"\, "ab"\); split //\, $s'
>     $ \./perl \-le 'my $s = unpack\("\(B\)\*"\, "ab"\); unpack "\(a\)\*"\, $s'
>     $ \./perl \-le 'unpack "\(a\)\*"\, unpack\("\(B\)\*"\, "ab"\);'
>     Invalid type '0' in unpack at \-e line 1\.

To save duplication\, it turned out to be stack issue\, as explained in

http&#8203;://www\.xray\.mpe\.mpg\.de/mailing\-lists/perl5\-porters/2008\-02/msg00178\.html

How many bonus items do you want on the stack in scalar context?

$ perl \-Ds \-e 'scalar unpack\("\(B\)\*"\, "ab"\)'

EXECUTING\.\.\.

&nbsp;    =>  
&nbsp;    =>  
&nbsp;    =>  
&nbsp;    =>  PV\("\(B\)\*"\\0\)  
&nbsp;    =>  PV\("\(B\)\*"\\0\)  PV\("ab"\\0\)  
&nbsp;    =>  PV\("0"\\0\)  PV\("0"\\0\)  
$ perl \-Ds \-e 'scalar unpack\("\(B\)\*"\, "abc"\)'

EXECUTING\.\.\.

&nbsp;    =>  
&nbsp;    =>  
&nbsp;    =>  
&nbsp;    =>  PV\("\(B\)\*"\\0\)  
&nbsp;    =>  PV\("\(B\)\*"\\0\)  PV\("abc"\\0\)  
&nbsp;    =>  PV\("0"\\0\)  PV\("0"\\0\)  PV\("0"\\0\)  
$ perl \-Ds \-e 'scalar unpack\("\(B\)\*"\, "abcd"\)'

EXECUTING\.\.\.

&nbsp;    =>  
&nbsp;    =>  
&nbsp;    =>  
&nbsp;    =>  PV\("\(B\)\*"\\0\)  
&nbsp;    =>  PV\("\(B\)\*"\\0\)  PV\("abcd"\\0\)  
&nbsp;    =>  PV\("0"\\0\)  PV\("0"\\0\)  PV\("0"\\0\)  PV\("0"\\0\)  


Basically \(\) constructions in scalar context were broken\, but it seems that
most ops don't notice\. Fixed in change 33239

Nicholas Clark

Change 33239 by nicholas@&#8203;nicholas\-bouvard on 2008/02/06 01&#8203;:00&#8203;:43

&nbsp;    in unpack\, \(\) groups in scalar context were still returning a list\,
&nbsp;    resulting in garbage on the stack\, which could manifest as a SEGV
&nbsp;    \(Bug 50256\)

Affected files \.\.\.

\.\.\. //depot/perl/pp\_pack\.c\#141 edit
\.\.\. //depot/perl/t/op/pack\.t\#115 edit

Differences \.\.\.

==== //depot/perl/pp\_pack\.c\#141 \(text\) ====

@&#8203;@&#8203; \-1258\,6 \+1258\,7 @&#8203;@&#8203;
&nbsp;         symptr\->previous = &savsym;
&nbsp;             symptr\->level\+\+;
&nbsp;         PUTBACK;
\+        if \(len && unpack\_only\_one\) len = 1;
&nbsp;         while \(len\-\-\) \{
&nbsp;               symptr\->patptr = savsym\.grpbeg;
&nbsp;         if \(utf8\) symptr\->flags |=  FLAG\_PARSE\_UTF8;

==== //depot/perl/t/op/pack\.t\#115 \(xtext\) ====

@&#8203;@&#8203; \-12\,7 \+12\,7 @&#8203;@&#8203;
 my $no\_signedness = $\] > 5\.009 ? '' :
&nbsp;   "Signed/unsigned pack modifiers not available on this perl";
 
\-plan tests => 14696;
\+plan tests => 14697;
 
 use strict;
 use warnings qw\(FATAL all\);
@&#8203;@&#8203; \-1980\,3 \+1980\,8 @&#8203;@&#8203;
&nbsp;     is\(unpack\('@&#8203;\!4 a\*'\, "\\x\{301\}\\x\{302\}\\x\{303\}\\x\{304\}\\x\{305\}"\)\,
&nbsp;        "\\x\{303\}\\x\{304\}\\x\{305\}"\, 'Test basic utf8 @&#8203;\!'\);
 \}
\+\{
\+    \#50256
\+    my \($v\) = split //\, unpack \('\(B\)\*'\, 'ab'\);
\+    is\($v\, 0\); \# Doesn't SEGV :\-\)
\+\}

**Comment by p5pRT** [comment]
p5p@spam.wizbit.be - Status changed from 'open' to 'resolved'
