### ISSUE TITLE
s/// on tied hashes

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9243]
Migrated from [rt.perl.org#51514](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=51514) (status was 'resolved')

Searchable as RT51514$

**Comment by p5pRT** [comment]
### From mawic@gmx.de

There seems to be a bug regarding tied hashes\. If s/// is applied to a 
string in such a hash\, it either has no effect or Perl crashes\. The outcome 
is somewhat random\, little changes in the code can completely change the 
result\. Minimal test case&#8203;:

\-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
my $hr = \{ a => 'abc' \};
tie my %h\, 'CaseInsHash'\, $hr;
$h\{A\} =~ s/\(\.\)/x$1x/g;
print $h\{A\};

package CaseInsHash;
sub TIEHASH\(\) \{ bless $\_\[1\] \}
sub FETCH\(\)   \{ $\_\[0\]\->\{lc\($\_\[1\]\)\} \}
sub STORE\(\)   \{ $\_\[0\]\->\{lc\($\_\[1\]\)\} = $\_\[2\] \}
\-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

Expected result&#8203;: prints "xaxxbxxcx"
Actual result&#8203;: sometimes crashes\, sometimes prints "abc" with
\- ActivePerl 5\.8\.8\.822 on WinXP
\- ActivePerl 5\.10\.0\.1002 on WinXP
\- Perl 5\.10\.0 debug build on WinXP
\- Perl 5\.10\.0 debug build on Ubuntu 7\.10&#8203;:

\-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
$ gdb \-\-args /usr/local/perl/bin/perl test\.pl
GNU gdb 6\.6\-debian
This GDB was configured as "i486\-linux\-gnu"\.\.\.
\(gdb\) r
Starting program&#8203;: /usr/local/perl/bin/perl hashcrash\.pl

Program received signal SIGSEGV\, Segmentation fault\.
Perl\_mg\_find \(sv=0x82697c8\, type=103\) at mg\.c&#8203;:393
393                 if \(mg\->mg\_type == type\)
\(gdb\) bt
\#0  Perl\_mg\_find \(sv=0x82697c8\, type=103\) at mg\.c&#8203;:393
\#1  0x0814014b in Perl\_pp\_substcont \(\) at pp\_ctl\.c&#8203;:290
\#2  0x0809b160 in Perl\_runops\_debug \(\) at dump\.c&#8203;:1931
\#3  0x080c6047 in perl\_run \(my\_perl=0x8250008\) at perl\.c&#8203;:2384
\#4  0x080624b5 in main \(argc=2\, argv=0xbfcfacd4\, env=0xbfcface0\) at 
perlmain\.c&#8203;:113
\-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

FWIW\, the \-V of the latter build&#8203;:

\-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
Summary of my perl5 \(revision 5 version 10 subversion 0\) configuration&#8203;:
&nbsp;   Platform&#8203;:
&nbsp;     osname=linux\, osvers=2\.6\.22\-14\-generic\, archname=i686\-linux
&nbsp;     uname='linux vbuntu 2\.6\.22\-14\-generic \#1 smp fri feb 1 04&#8203;:59&#8203;:50 utc 
2008 i686 gnulinux '
&nbsp;     config\_args='\-DDEBUGGING'
&nbsp;     hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;     useithreads=undef\, usemultiplicity=undef
&nbsp;     useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;     use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;     usemymalloc=n\, bincompat5005=undef
&nbsp;   Compiler&#8203;:
&nbsp;     cc='cc'\, ccflags ='\-DDEBUGGING \-fno\-strict\-aliasing \-pipe 
\-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;     optimize='\-O2 \-g'\,
&nbsp;     cppflags='\-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-I/usr/local/include'
&nbsp;     ccversion=''\, gccversion='4\.1\.3 20070929 \(prerelease\) \(Ubuntu 
4\.1\.2\-16ubuntu2\)'\, gccosandvers=''
&nbsp;     intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;     ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, 
lseeksize=8
&nbsp;     alignbytes=4\, prototype=define
&nbsp;   Linker and Libraries&#8203;:
&nbsp;     ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;     libpth=/usr/local/lib /lib /usr/lib
&nbsp;     libs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;     perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;     libc=/lib/libc\-2\.6\.1\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;     gnulibc\_version='2\.6\.1'
&nbsp;   Dynamic Linking&#8203;:
&nbsp;     dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;     cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-g \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;   Compile\-time options&#8203;: DEBUGGING PERL\_DONT\_CREATE\_GVSV PERL\_MALLOC\_WRAP
&nbsp;                         USE\_LARGE\_FILES USE\_PERLIO
&nbsp;   Built under linux
&nbsp;   Compiled at Feb 26 2008 08&#8203;:00&#8203;:45
&nbsp;   @&#8203;INC&#8203;:
&nbsp;     /usr/local/perl/lib/5\.10\.0/i686\-linux
&nbsp;     /usr/local/perl/lib/5\.10\.0
&nbsp;     /usr/local/perl/lib/site\_perl/5\.10\.0/i686\-linux
&nbsp;     /usr/local/perl/lib/site\_perl/5\.10\.0
&nbsp;     \.
\-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

A workaround that has worked for me so far&#8203;:

my $sr = \\$h\{A\};
$$sr =~ s/\(\.\)/x$1x/g;

**Comment by p5pRT** [comment]
### From p5p@spam.wizbit.be

On Fri Mar 07 07&#8203;:14&#8203;:49 2008\, mawic@&#8203;gmx\.de wrote&#8203;:
> There seems to be a bug regarding tied hashes\. If s/// is applied to 
a 
> string in such a hash\, it either has no effect or Perl crashes\. The 
outcome 
> is somewhat random\, little changes in the code can completely change 
the 
> result\. Minimal test case&#8203;:
> 
> \-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> my $hr = \{ a => 'abc' \};
> tie my %h\, 'CaseInsHash'\, $hr;
> $h\{A\} =~ s/\(\.\)/x$1x/g;
> print $h\{A\};
> 
> package CaseInsHash;
> sub TIEHASH\(\) \{ bless $\_\[1\] \}
> sub FETCH\(\)   \{ $\_\[0\]\->\{lc\($\_\[1\]\)\} \}
> sub STORE\(\)   \{ $\_\[0\]\->\{lc\($\_\[1\]\)\} = $\_\[2\] \}
> \-8\<\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
 

That code doesn't segfault with me but

\#\!/usr/bin/perl \-l

my $hr = \{ a => 'abc' \};
tie my %h\, 'CaseInsHash'\, $hr;
$h\{A\} =~ s/\(\.\)/x$1x/g;
print $h\{A\};

package CaseInsHash;
sub TIEHASH\(\) \{ bless $\_\[1\] \}
sub FETCH\(\) \{ print "FETCH \($\_\[1\]\)" if 0; $\_\[0\]\->\{lc\($\_\[1\]\)\} \}
sub STORE\(\) \{ print "STORE \($\_\[1\] = $\_\[2\]\)" if 0; $\_\[0\]\->\{lc\($\_\[1\]\)\} = 
$\_\[2\] \}

\_\_END\_\_

does\. \(Which is essentially the same thing\)\.


I couldn't get 5\.8\.8 to segfault\, but 5\.10\.0 did segfault\.

Trying the same code with maint \(5\.10\.x \- eventually 5\.10\.1\) did not 
segfault neither did perl\-current \(blead\)\.

Both output&#8203;:
xaxxbxxcx


Is it possible for you to build perl\-current and test as well?


Kind regards\,

Bram

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From p5p@spam.wizbit.be

Intordoced with Change 26334&#8203;:

\-\-\-\-Program\-\-\-\-
\#\!/usr/bin/perl \-l

my $hr = \{ a => 'abc' \};
tie my %h\, 'CaseInsHash'\, $hr;
$h\{A\} =~ s/\(\.\)/x$1x/g;
print $h\{A\};

package CaseInsHash;
sub TIEHASH\(\) \{ bless $\_\[1\] \}
sub FETCH\(\) \{ print "FETCH \($\_\[1\]\)" if 0; $\_\[0\]\->\{lc\($\_\[1\]\)\} \}
sub STORE\(\) \{ print "STORE \($\_\[1\] = $\_\[2\]\)" if 0; $\_\[0\]\->\{lc\($\_\[1\]\)\} = 
$\_\[2\] \}

\-\-\-\-Output of \.\.\./pWBW5W8/perl\-5\.9\.2@&#8203;26332/bin/perl\-\-\-\-
xaxxbxxcx

\-\-\-\-EOF \($?='0'\)\-\-\-\-
\-\-\-\-Output of \.\.\./pvxu6nl/perl\-5\.9\.2@&#8203;26334/bin/perl\-\-\-\-

\-\-\-\-EOF \($?='11'\)\-\-\-\-


http&#8203;://public\.activestate\.com/cgi\-bin/perlbrowse/p/26334
Change 26334 by rgs@&#8203;stencil on 2005/12/12 16&#8203;:03&#8203;:00

&nbsp;    A suggestion by Yamashina Hio to speed up substitutions
&nbsp;    with right\-hand side expressions by freeing temporaries\.
&nbsp;    See :
&nbsp;    
&nbsp;    Subject&#8203;: s///ge; consumes PL\_tmps\_stack in its loop
&nbsp;    From&#8203;: YAMASHINA Hio \<hio@&#8203;hio\.jp>
&nbsp;    Date&#8203;: Tue\, 30 Aug 2005 17&#8203;:17&#8203;:23 \+0900
&nbsp;    Message\-Id&#8203;: \<20050830160113\.9716\.HIO@&#8203;ymir\.co\.jp>




Reverted with Change 33685&#8203;:

\-\-\-\-Program\-\-\-\-
\#\!/usr/bin/perl \-l

my $hr = \{ a => 'abc' \};
tie my %h\, 'CaseInsHash'\, $hr;
$h\{A\} =~ s/\(\.\)/x$1x/g;
print $h\{A\};

package CaseInsHash;
sub TIEHASH\(\) \{ bless $\_\[1\] \}
sub FETCH\(\) \{ print "FETCH \($\_\[1\]\)" if 0; $\_\[0\]\->\{lc\($\_\[1\]\)\} \}
sub STORE\(\) \{ print "STORE \($\_\[1\] = $\_\[2\]\)" if 0; $\_\[0\]\->\{lc\($\_\[1\]\)\} = 
$\_\[2\] \}

\-\-\-\-Output of \.\.\.peQPavL/perl\-5\.10\.0@&#8203;33684/bin/perl\-\-\-\-

\-\-\-\-EOF \($?='11'\)\-\-\-\-
\-\-\-\-Output of \.\.\.pRZsdjX/perl\-5\.10\.0@&#8203;33685/bin/perl\-\-\-\-
xaxxbxxcx

\-\-\-\-EOF \($?='0'\)\-\-\-\-

Change 33685 by rgs@&#8203;stcosmo on 2008/04/15 12&#8203;:29&#8203;:33

&nbsp;    Revert change \#26334\, which was introducing too many bugs


A test case was introduced with Change 33686\.
http&#8203;://public\.activestate\.com/cgi\-bin/perlbrowse/p/33686
Change 33686 by rgs@&#8203;stcosmo on 2008/04/15 12&#8203;:43&#8203;:02

&nbsp;    Add a regression test for bug \#52658 \(fixed by change \#33685\)
&nbsp;    based on code by Wolf\-Dietrich Moeller

**Comment by p5pRT** [comment]
p5p@spam.wizbit.be - Status changed from 'open' to 'resolved'
