### ISSUE TITLE
Segfault on ISA push after symbol table delete

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9265]
Migrated from [rt.perl.org#52074](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=52074) (status was 'resolved')

Searchable as RT52074$

**Comment by p5pRT** [comment]
### From @pjscott

The last time I can find this being addressed here was in 2003 in 
http&#8203;://groups\.google\.com/group/perl\.perl5\.porters/browse\_thread/thread/16832fe88182a06 
\, but there doesn't appear to have been a resolution\.  I couldn't 
find open bugs on a subject seach\, so I'm putting this in just on the 
principle that there ought to be a better response than segfaulting&#8203;:

$ perl \-e 'delete $main&#8203;::\{"foo&#8203;::"\}; push @&#8203;foo&#8203;::ISA\, "bar"'
Segmentation fault

Summary of my perl5 \(revision 5 version 10 subversion 0\) configuration&#8203;:
&nbsp;   Platform&#8203;:
&nbsp;     osname=linux\, osvers=2\.6\.16\-1\.2133\_fc5\, archname=i686\-linux
&nbsp;     uname='linux tweety 2\.6\.16\-1\.2133\_fc5 \#1 tue jun 6 00&#8203;:52&#8203;:14 edt 
2006 i686 athlon i386 gnulinux '
&nbsp;     config\_args='\-des \-DDEBUGGING'
&nbsp;     hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;     useithreads=undef\, usemultiplicity=undef
&nbsp;     useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;     use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;     usemymalloc=n\, bincompat5005=undef
&nbsp;   Compiler&#8203;:
&nbsp;     cc='cc'\, ccflags ='\-DDEBUGGING \-fno\-strict\-aliasing \-pipe 
\-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 
\-I/usr/include/gdbm'\,
&nbsp;     optimize='\-O2 \-g'\,
&nbsp;     cppflags='\-DDEBUGGING \-fno\-strict\-aliasing \-pipe 
\-I/usr/local/include \-I/usr/include/gdbm'
&nbsp;     ccversion=''\, gccversion='4\.1\.1 20060525 \(Red Hat 4\.1\.1\-1\)'\, 
gccosandvers=''
&nbsp;     intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;     ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, 
Off\_t='off\_t'\, lseeksize=8
&nbsp;     alignbytes=4\, prototype=define
&nbsp;   Linker and Libraries&#8203;:
&nbsp;     ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;     libpth=/usr/local/lib /lib /usr/lib
&nbsp;     libs=\-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;     perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;     libc=/lib/libc\-2\.4\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;     gnulibc\_version='2\.4'
&nbsp;   Dynamic Linking&#8203;:
&nbsp;     dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;     cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-g \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;   Compile\-time options&#8203;: DEBUGGING PERL\_DONT\_CREATE\_GVSV PERL\_MALLOC\_WRAP
&nbsp;                         USE\_LARGE\_FILES USE\_PERLIO
&nbsp;   Built under linux
&nbsp;   Compiled at Dec 26 2007 19&#8203;:03&#8203;:58
&nbsp;   @&#8203;INC&#8203;:
&nbsp;     /usr/local/lib/perl5/5\.10\.0/i686\-linux
&nbsp;     /usr/local/lib/perl5/5\.10\.0
&nbsp;     /usr/local/lib/perl5/site\_perl/5\.10\.0/i686\-linux
&nbsp;     /usr/local/lib/perl5/site\_perl/5\.10\.0
&nbsp;     /usr/local/lib/perl5/site\_perl/5\.8\.8
&nbsp;     /usr/local/lib/perl5/site\_perl
&nbsp;     \.

**Comment by p5pRT** [comment]
### From @tux

On Tue\, 25 Mar 2008 05&#8203;:03&#8203;:56 \-0700\, Peter Scott \(via RT\)
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

> The last time I can find this being addressed here was in 2003 in 
> http&#8203;://groups\.google\.com/group/perl\.perl5\.porters/browse\_thread/thread/16832fe88182a06 
> \, but there doesn't appear to have been a resolution\.  I couldn't 
> find open bugs on a subject seach\, so I'm putting this in just on the 
> principle that there ought to be a better response than segfaulting&#8203;:
> 
> $ perl \-e 'delete $main&#8203;::\{"foo&#8203;::"\}; push @&#8203;foo&#8203;::ISA\, "bar"'
> Segmentation fault

Still segfaults in blead\.

Doctor  says&#8203;: well\, don't do that
Patient says&#8203;: but\, it shouldn't segfault

both are right

I'd be worried if some extra check on existence of named variables on every
action would severely slow down perl\.

\-\- 
H\.Merijn Brand         Amsterdam Perl Mongers \(http&#8203;://amsterdam\.pm\.org/\)
using & porting perl 5\.6\.2\, 5\.8\.x\, 5\.10\.x  on HP\-UX 10\.20\, 11\.00\, 11\.11\,
& 11\.23\, SuSE 10\.1 & 10\.2\, AIX 5\.2\, and Cygwin\.       http&#8203;://qa\.perl\.org
http&#8203;://mirrors\.develooper\.com/hpux/            http&#8203;://www\.test\-smoke\.org
&nbsp;                        http&#8203;://www\.goldmark\.org/jeff/stupid\-disclaimers/

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @nwc10

On Tue\, Mar 25\, 2008 at 02&#8203;:08&#8203;:25PM \+0100\, H\.Merijn Brand wrote&#8203;:
> On Tue\, 25 Mar 2008 05&#8203;:03&#8203;:56 \-0700\, Peter Scott \(via RT\)
> \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> 
> > The last time I can find this being addressed here was in 2003 in 
> > http&#8203;://groups\.google\.com/group/perl\.perl5\.porters/browse\_thread/thread/16832fe88182a06 
> > \, but there doesn't appear to have been a resolution\.  I couldn't 
> > find open bugs on a subject seach\, so I'm putting this in just on the 
> > principle that there ought to be a better response than segfaulting&#8203;:
> > 
> > $ perl \-e 'delete $main&#8203;::\{"foo&#8203;::"\}; push @&#8203;foo&#8203;::ISA\, "bar"'
> > Segmentation fault
> 
> Still segfaults in blead\.

But doesn't segfault in 5\.8\.8 \(or later\)

It now seems to be a 5\.10\.0 regression\, as it's happening in the MRO code&#8203;:

Program received signal EXC\_BAD\_ACCESS\, Could not access memory\.
Reason&#8203;: KERN\_INVALID\_ADDRESS at address&#8203;: 0x000000000000000c
0x00000001001247bc in Perl\_mro\_isa\_changed\_in \(my\_perl=0x100800000\, stash=0x0\) at mro\.c&#8203;:481
481         const char \* const stashname = HvNAME\_get\(stash\);
\(gdb\) where
\#0  0x00000001001247bc in Perl\_mro\_isa\_changed\_in \(my\_perl=0x100800000\, stash=0x0\) at mro\.c&#8203;:481
\#1  0x000000010010f3dd in Perl\_magic\_setisa \(my\_perl=0x100800000\, sv=0x100816f80\, mg=0x10050bae8\) at mg\.c&#8203;:1609
\#2  0x00000001001063b9 in Perl\_mg\_set \(my\_perl=0x100800000\, sv=0x100816f80\) at mg\.c&#8203;:291
\#3  0x0000000100236490 in Perl\_pp\_push \(my\_perl=0x100800000\) at pp\.c&#8203;:4530
\#4  0x00000001000efc1b in Perl\_runops\_debug \(my\_perl=0x100800000\) at dump\.c&#8203;:1984
\#5  0x00000001001454d8 in S\_run\_body \(my\_perl=0x100800000\, oldscope=1\) at perl\.c&#8203;:2400
\#6  0x0000000100144524 in perl\_run \(my\_perl=0x100800000\) at perl\.c&#8203;:2320
\#7  0x0000000100001683 in main \(argc=3\, argv=0x7fff5fbfeda8\, env=0x7fff5fbfedc8\) at perlmain\.c&#8203;:113

Nicholas Clark

**Comment by p5pRT** [comment]
### From @rgs

On 25/03/2008\, via RT Peter Scott \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
>  $ perl \-e 'delete $main&#8203;::\{"foo&#8203;::"\}; push @&#8203;foo&#8203;::ISA\, "bar"'
>  Segmentation fault

Change \#33684 fixes that :

Change 33684 by rgs@&#8203;stcosmo on 2008/04/15 08&#8203;:36&#8203;:48

&nbsp;        Fix for \[perl \#52074\] Segfault on ISA push after symbol table delete

&nbsp;        This restores the 5\.8\.8 behaviour\. The deleted stash is not vivified
&nbsp;        again\, hence the hierarchy remains broken\. But there's no segfault\.

More generally\, what should perl do when asked to act on a deleted
stash? I think the current behaviour is correct\, although a bit
surprising \(we could warn\.\) If someone deletes a stash by hand\, it's
probably because it's not going to be used again and the memory can be
used for other purposes\.

**Comment by p5pRT** [comment]
@rgs - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @nwc10

On Tue\, Apr 15\, 2008 at 10&#8203;:41&#8203;:54AM \+0200\, Rafael Garcia\-Suarez wrote&#8203;:

> More generally\, what should perl do when asked to act on a deleted
> stash? I think the current behaviour is correct\, although a bit
> surprising \(we could warn\.\) If someone deletes a stash by hand\, it's
> probably because it's not going to be used again and the memory can be
> used for other purposes\.

I'm in two minds\. The counter argument is "Why should there be any difference
in behaviour between these two?"

perl \-e 'delete $main&#8203;::\{"foo&#8203;::"\}; push @&#8203;foo&#8203;::ISA\, "bar"'
perl \-e 'delete $main&#8203;::\{"foo&#8203;::"\}; eval q\{push @&#8203;foo&#8203;::ISA\, "bar"\}'

Nicholas Clark

**Comment by p5pRT** [comment]
### From @rgs

On 15/04/2008\, Nicholas Clark \<nick@&#8203;ccl4\.org> wrote&#8203;:
> On Tue\, Apr 15\, 2008 at 10&#8203;:41&#8203;:54AM \+0200\, Rafael Garcia\-Suarez wrote&#8203;:
>
>  > More generally\, what should perl do when asked to act on a deleted
>  > stash? I think the current behaviour is correct\, although a bit
>  > surprising \(we could warn\.\) If someone deletes a stash by hand\, it's
>  > probably because it's not going to be used again and the memory can be
>  > used for other purposes\.
>
>
> I'm in two minds\. The counter argument is "Why should there be any difference
>  in behaviour between these two?"
>
>
>  perl \-e 'delete $main&#8203;::\{"foo&#8203;::"\}; push @&#8203;foo&#8203;::ISA\, "bar"'
>
> perl \-e 'delete $main&#8203;::\{"foo&#8203;::"\}; eval q\{push @&#8203;foo&#8203;::ISA\, "bar"\}'

What difference do you see ?

$ \./perl \-le 'delete $main&#8203;::\{"foo&#8203;::"\}; push @&#8203;foo&#8203;::ISA\, "bar"; print
foo\->isa\("bar"\) ? 1&#8203;:0'
0
$ \./perl \-le 'delete $main&#8203;::\{"foo&#8203;::"\}; eval q\{push @&#8203;foo&#8203;::ISA\, "bar"\};
print foo\->isa\("bar"\) ? 1&#8203;:0'
0

\(same with 5\.8\.8\)

**Comment by p5pRT** [comment]
### From @nwc10

On Tue\, Apr 15\, 2008 at 11&#8203;:02&#8203;:08AM \+0200\, Rafael Garcia\-Suarez wrote&#8203;:
> On 15/04/2008\, Nicholas Clark \<nick@&#8203;ccl4\.org> wrote&#8203;:
> > On Tue\, Apr 15\, 2008 at 10&#8203;:41&#8203;:54AM \+0200\, Rafael Garcia\-Suarez wrote&#8203;:
> >
> >  > More generally\, what should perl do when asked to act on a deleted
> >  > stash? I think the current behaviour is correct\, although a bit
> >  > surprising \(we could warn\.\) If someone deletes a stash by hand\, it's
> >  > probably because it's not going to be used again and the memory can be
> >  > used for other purposes\.
> >
> >
> > I'm in two minds\. The counter argument is "Why should there be any difference
> >  in behaviour between these two?"
> >
> >
> >  perl \-e 'delete $main&#8203;::\{"foo&#8203;::"\}; push @&#8203;foo&#8203;::ISA\, "bar"'
> >
> > perl \-e 'delete $main&#8203;::\{"foo&#8203;::"\}; eval q\{push @&#8203;foo&#8203;::ISA\, "bar"\}'
> 
> What difference do you see ?
> 
> $ \./perl \-le 'delete $main&#8203;::\{"foo&#8203;::"\}; push @&#8203;foo&#8203;::ISA\, "bar"; print
> foo\->isa\("bar"\) ? 1&#8203;:0'
> 0
> $ \./perl \-le 'delete $main&#8203;::\{"foo&#8203;::"\}; eval q\{push @&#8203;foo&#8203;::ISA\, "bar"\};
> print foo\->isa\("bar"\) ? 1&#8203;:0'
> 0
> 
> \(same with 5\.8\.8\)

Oh\. I assumed that there was a difference\. Not following my own advice of
look first\, mail second\.

But there does seem to be one&#8203;:

$ perl \-le 'sub bar&#8203;::pie \{print "Pie\!"\}; delete $main&#8203;::\{"foo&#8203;::"\}; eval q\{push @&#8203;foo&#8203;::ISA\, "bar"\}; foo\->pie'
Pie\!
$ perl \-le 'sub bar&#8203;::pie \{print "Pie\!"\}; delete $main&#8203;::\{"foo&#8203;::"\}; push @&#8203;foo&#8203;::ISA\, "bar"; foo\->pie'
Can't locate object method "pie" via package "foo" \(perhaps you forgot to load "foo"?\) at \-e line 1\.
$ perl \-le 'sub bar&#8203;::pie \{print "Pie\!"\}; push @&#8203;foo&#8203;::ISA\, "bar"; foo\->pie'
Pie\!

\(that was 5\.8\.8\, same results with blead\)

That failure example smells of "implementation detail poking through"

Nicholas Clark

**Comment by p5pRT** [comment]
### From @rgs

On 15/04/2008\, Nicholas Clark \<nick@&#8203;ccl4\.org> wrote&#8203;:
>  But there does seem to be one&#8203;:
>
>  $ perl \-le 'sub bar&#8203;::pie \{print "Pie\!"\}; delete $main&#8203;::\{"foo&#8203;::"\}; eval q\{push @&#8203;foo&#8203;::ISA\, "bar"\}; foo\->pie'
>  Pie\!
>  $ perl \-le 'sub bar&#8203;::pie \{print "Pie\!"\}; delete $main&#8203;::\{"foo&#8203;::"\}; push @&#8203;foo&#8203;::ISA\, "bar"; foo\->pie'
>  Can't locate object method "pie" via package "foo" \(perhaps you forgot to load "foo"?\) at \-e line 1\.
>  $ perl \-le 'sub bar&#8203;::pie \{print "Pie\!"\}; push @&#8203;foo&#8203;::ISA\, "bar"; foo\->pie'
>  Pie\!
>
>  \(that was 5\.8\.8\, same results with blead\)
>
>  That failure example smells of "implementation detail poking through"

Maybe\. Since eval\-string starts a new compilation phase\, creation of
stashes happens\. I expect a require to have the same effect\.

**Comment by p5pRT** [comment]
### From @gbarr


On Apr 15\, 2008\, at 4&#8203;:25 AM\, Rafael Garcia\-Suarez wrote&#8203;:
> On 15/04/2008\, Nicholas Clark \<nick@&#8203;ccl4\.org> wrote&#8203;:
>>  But there does seem to be one&#8203;:
>>
>>  $ perl \-le 'sub bar&#8203;::pie \{print "Pie\!"\}; delete $main&#8203;::\{"foo&#8203;::"\};  
>> eval q\{push @&#8203;foo&#8203;::ISA\, "bar"\}; foo\->pie'
>>  Pie\!
>>  $ perl \-le 'sub bar&#8203;::pie \{print "Pie\!"\}; delete $main&#8203;::\{"foo&#8203;::"\};  
>> push @&#8203;foo&#8203;::ISA\, "bar"; foo\->pie'
>>  Can't locate object method "pie" via package "foo" \(perhaps you  
>> forgot to load "foo"?\) at \-e line 1\.
>>  $ perl \-le 'sub bar&#8203;::pie \{print "Pie\!"\}; push @&#8203;foo&#8203;::ISA\, "bar";  
>> foo\->pie'
>>  Pie\!
>>
>>  \(that was 5\.8\.8\, same results with blead\)
>>
>>  That failure example smells of "implementation detail poking  
>> through"
>
> Maybe\. Since eval\-string starts a new compilation phase\, creation of
> stashes happens\. I expect a require to have the same effect\.

Because @&#8203;foo&#8203;::ISA is resolved at compile time before the delete  
happens\, so anything which makes the resolution of @&#8203;foo&#8203;::ISA come  
after the delete will avoid the failure

perl \-le 'sub bar&#8203;::pie \{print "Pie\!"\}; BEGIN \{ delete $main&#8203;:: 
\{"foo&#8203;::"\}; \} push @&#8203;foo&#8203;::ISA\, "bar"; foo\->pie'
Pie\!

perl \-le 'sub bar&#8203;::pie \{print "Pie\!"\}; delete $main&#8203;::\{"foo&#8203;::"\};  
$isa="foo&#8203;::ISA"; push @&#8203;\{$isa\}\, "bar"; foo\->pie'
Pie\!

Graham\.
