### ISSUE TITLE
crash when localizing a symtab entry

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9287]
Migrated from [rt.perl.org#52740](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=52740) (status was 'resolved')

Searchable as RT52740$

**Comment by p5pRT** [comment]
### From @ntyni

This snippet crashes Perl 5\.10\.0 and blead \(as of change 33541 which
is the last one in the utsl\.gen\.nz git repository\) with a segmentation fault&#8203;:

 \#\!/usr/bin/perl \-w
 use Compress&#8203;::Zlib;
 use Devel&#8203;::Symdump;
 print Devel&#8203;::Symdump\->isa\_tree;
 \_\_END\_\_

\(The snippet is reduced from the mod\_perl2 2\.0\.4rc1 test suite\,
 where Apache crashes on shutdown after the tests\.\)

This can be reduced to

 \#\!/usr/bin/perl
 use constant "foo" => "a";
 index\("a"\, foo\);
 local\(\*g\) = $\{&#8203;::\}\{foo\};
 \_\_END\_\_

and expanded to this core\-only test&#8203;:

 \#\!/usr/bin/perl 
 BEGIN \{
&nbsp;    $|=1;
&nbsp;    print "1\.\.2\\n";
&nbsp;    my $name = "foo";
&nbsp;    my $scalar = "a";
&nbsp;    if \($\] > 5\.009002\) \{
&nbsp;        my $symtab = \\%\{'&#8203;::'\};
&nbsp;        $symtab\->\{$name\} = \\$scalar;
&nbsp;    \} else \{
&nbsp;        \*\{"&#8203;::$name"\} = sub \(\) \{ $scalar \};
&nbsp;    \}
 \}
 print "ok 1\\n" if index\("a"\, foo\) >= 0;
 local\(\*g\) = $\{&#8203;::\}\{foo\};
 END \{print "ok 2\\n";\}
 \_\_END\_\_

Bisecting shows the segfault started with

\[ 29544\] By&#8203;: nicholas                              on 2006/12/13  08&#8203;:35&#8203;:43
&nbsp;        Log&#8203;: Eliminate PVBM\. Store fast Boyer\-Moore tables in PVGV\.
&nbsp;             Add the placeholder for new type\, temporarily named BIND\, for binding
&nbsp;             and aliasing in 6 on 5\.
&nbsp;     Branch&#8203;: perl
&nbsp;           \! dump\.c ext/B/B\.xs ext/Storable/Storable\.xs op\.h
&nbsp;           \! pod/perltodo\.pod pp\_hot\.c sv\.c sv\.h util\.c


On blead\, change 32708 turns this into an assertion failure with \-DDEBUGGING&#8203;:

 miniperl&#8203;: sv\.c&#8203;:3231&#8203;: S\_glob\_assign\_glob&#8203;: Assertion \`\(\(\(\(shplep\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(shplep\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(shplep\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.
 \.\./testscript&#8203;: line 3&#8203;:  3158 Aborted                 \(core dumped\) \./miniperl $\{HOME\}/t\.pl


Backtrace of 'miniperl' as of change 33541 without \-DDEBUGGING&#8203;:

Core was generated by \`\./miniperl /home/niko/t\.pl'\.
Program terminated with signal 11\, Segmentation fault\.
\[New process 23428\]
\#0  0x0000000000488f67 in S\_unshare\_hek\_or\_pvn \(my\_perl=0x7c7010\, hek=0x31\, str=0x0\, len=0\, hash=0\)
&nbsp;    at hv\.c&#8203;:2294
2294        if \(he\->shared\_he\_he\.he\_valu\.hent\_refcount \- 1\) \{
\(gdb\) bt
\#0  0x0000000000488f67 in S\_unshare\_hek\_or\_pvn \(my\_perl=0x7c7010\, hek=0x31\, str=0x0\, len=0\, hash=0\)
&nbsp;    at hv\.c&#8203;:2294
\#1  0x0000000000488f18 in Perl\_unshare\_hek \(my\_perl=0x7c7010\, hek=0x31\) at hv\.c&#8203;:2263
\#2  0x000000000040a776 in Perl\_gp\_free \(my\_perl=0x7c7010\, gv=0x7e8820\) at gv\.c&#8203;:1583
\#3  0x00000000004ed305 in Perl\_leave\_scope \(my\_perl=0x7c7010\, base=0\) at scope\.c&#8203;:821
\#4  0x00000000004ea2cd in Perl\_pop\_scope \(my\_perl=0x7c7010\) at scope\.c&#8203;:102
\#5  0x00000000004a48a6 in Perl\_pp\_leave \(my\_perl=0x7c7010\) at pp\_hot\.c&#8203;:1882
\#6  0x000000000049b9d3 in Perl\_runops\_standard \(my\_perl=0x7c7010\) at run\.c&#8203;:38
\#7  0x0000000000494971 in S\_run\_body \(my\_perl=0x7c7010\, oldscope=1\) at perl\.c&#8203;:2400
\#8  0x000000000049437e in perl\_run \(my\_perl=0x7c7010\) at perl\.c&#8203;:2320
\#9  0x000000000057375e in main \(argc=2\, argv=0x7fff820a3c88\, env=0x7fff820a3ca0\) at miniperlmain\.c&#8203;:113

Backtrace with \-DDEBUGGING and the assertion failure above&#8203;:

Core was generated by \`\./miniperl /home/niko/t\.pl'\.
Program terminated with signal 6\, Aborted\.
\[New process 14219\]
\#0  0x00002b50c8c431d5 in raise \(\) from /lib/libc\.so\.6
\(gdb\) bt
\#0  0x00002b50c8c431d5 in raise \(\) from /lib/libc\.so\.6
\#1  0x00002b50c8c44680 in abort \(\) from /lib/libc\.so\.6
\#2  0x00002b50c8c3c75f in \_\_assert\_fail \(\) from /lib/libc\.so\.6
\#3  0x000000000053affd in S\_glob\_assign\_glob \(my\_perl=0x984010\, dstr=0x9a70d8\, sstr=0x9a70a8\, dtype=9\)
&nbsp;    at sv\.c&#8203;:3366
\#4  0x0000000000540f07 in Perl\_sv\_setsv\_flags \(my\_perl=0x984010\, dstr=0x9a70d8\, sstr=0x9a70a8\, 
&nbsp;    flags=1538\) at sv\.c&#8203;:3717
\#5  0x000000000050cc8a in Perl\_pp\_aassign \(my\_perl=0x984010\) at pp\_hot\.c&#8203;:1074
\#6  0x00000000004ad3dc in Perl\_runops\_debug \(my\_perl=0x984010\) at dump\.c&#8203;:1984
\#7  0x00000000004f6ae3 in S\_run\_body \(my\_perl=0x984010\, oldscope=1\) at perl\.c&#8203;:2400
\#8  0x00000000004f5e15 in perl\_run \(my\_perl=0x984010\) at perl\.c&#8203;:2320
\#9  0x00000000006b087e in main \(argc=2\, argv=0x7fffe2987578\, env=0x7fffe2987590\) at miniperlmain\.c&#8203;:113




---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=medium


---
Site configuration information for perl 5\.10\.0&#8203;:

Configured by Debian Project at Sun Mar 30 20&#8203;:28&#8203;:28 UTC 2008\.

Summary of my perl5 \(revision 5 version 10 subversion 0\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.18\-6\-xen\-amd64\, archname=x86\_64\-linux\-gnu\-thread\-multi
&nbsp;    uname='linux sid 2\.6\.18\-6\-xen\-amd64 \#1 smp sun feb 10 18&#8203;:02&#8203;:52 utc 2008 x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN \-Dcccdlflags=\-fPIC \-Darchname=x86\_64\-linux\-gnu \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.10 \-Darchlib=/usr/lib/perl/5\.10 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.10\.0 \-Dsitearch=/usr/local/lib/perl/5\.10\.0 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1 \-Dsiteman3dir=/usr/local/man/man3 \-Dman1ext=1 \-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Ud\_ualarm \-Uusesfio \-Uusenm \-DDEBUGGING=\-g \-Doptimize=\-O2 \-Duseshrplib \-Dlibperl=libperl\.so\.5\.10\.0 \-Dd\_dosuid \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing \-pipe \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2 \-g'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing \-pipe \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.2\.3 \(Debian 4\.2\.3\-3\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64
&nbsp;    libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    libc=/lib/libc\-2\.7\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.10\.0
&nbsp;    gnulibc\_version='2\.7'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-g \-L/usr/local/lib'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl 5\.10\.0&#8203;:
&nbsp;    /etc/perl
&nbsp;    /usr/local/lib/perl/5\.10\.0
&nbsp;    /usr/local/share/perl/5\.10\.0
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/perl/5\.10
&nbsp;    /usr/share/perl/5\.10
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    \.



---
Environment for perl 5\.10\.0&#8203;:
&nbsp;    HOME=/root
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/usr/local/sbin&#8203;:/usr/local/bin&#8203;:/usr/sbin&#8203;:/usr/bin&#8203;:/sbin&#8203;:/bin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @rgs

2008/4/11 via RT Niko Tyni \<perlbug\-followup@&#8203;perl\.org>&#8203;:
> This snippet crashes Perl 5\.10\.0 and blead \(as of change 33541 which
> is the last one in the utsl\.gen\.nz git repository\) with a segmentation fault&#8203;:
>
>  \#\!/usr/bin/perl \-w
>  use Compress&#8203;::Zlib;
>  use Devel&#8203;::Symdump;
>  print Devel&#8203;::Symdump\->isa\_tree;
>  \_\_END\_\_
>
> \(The snippet is reduced from the mod\_perl2 2\.0\.4rc1 test suite\,
>  where Apache crashes on shutdown after the tests\.\)
>
> This can be reduced to
>
>  \#\!/usr/bin/perl
>  use constant "foo" => "a";
>  index\("a"\, foo\);
>  local\(\*g\) = $\{&#8203;::\}\{foo\};
>  \_\_END\_\_

Thanks for the impressive and detailed bug report\, that was useful\.

Here's a patch that solves the problem\. I've not had time yet to run all tests
with it\, but core tests are fine\.

\-\-\- sv\.c
\+\+\+ sv\.c
@&#8203;@&#8203; \-3718\,8 \+3718\,10 @&#8203;@&#8203; Perl\_sv\_setsv\_flags\(pTHX\_ SV \*dstr\, regi
&nbsp;                GvMULTI\_on\(dstr\);
&nbsp;                return;
&nbsp;            \}
\-           glob\_assign\_glob\(dstr\, sstr\, dtype\);
\-           return;
\+           if \(isGV\_with\_GP\(sstr\)\) \{
\+               glob\_assign\_glob\(dstr\, sstr\, dtype\);
\+               return;
\+           \}
&nbsp;        \}

&nbsp;        if \(dtype >= SVt\_PV\) \{

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @rgs

I've now applied the patch to bleadperl as change \#33807\.

**Comment by p5pRT** [comment]
@rgs - Status changed from 'open' to 'resolved'

**Comment by p5pRT** [comment]
### From @rurban

2008/5/10 Rafael Garcia\-Suarez via RT \<perlbug\-followup@&#8203;perl\.org>&#8203;:
> I've now applied the patch to bleadperl as change \#33807\.

We also need that for maint \(5\.10\.x\)
\-\- 
Reini

**Comment by p5pRT** [comment]
### From p5p@spam.wizbit.be

On Fri May 09 08&#8203;:50&#8203;:13 2008\, rafael wrote&#8203;:
> 2008/4/11 via RT Niko Tyni \<perlbug\-followup@&#8203;perl\.org>&#8203;:
> > This snippet crashes Perl 5\.10\.0 and blead \(as of change 33541 which
> > is the last one in the utsl\.gen\.nz git repository\) with a
> segmentation fault&#8203;:
> >
> >  \#\!/usr/bin/perl \-w
> >  use Compress&#8203;::Zlib;
> >  use Devel&#8203;::Symdump;
> >  print Devel&#8203;::Symdump\->isa\_tree;
> >  \_\_END\_\_
> >
> > \(The snippet is reduced from the mod\_perl2 2\.0\.4rc1 test suite\,
> >  where Apache crashes on shutdown after the tests\.\)
> >
> > This can be reduced to
> >
> >  \#\!/usr/bin/perl
> >  use constant "foo" => "a";
> >  index\("a"\, foo\);
> >  local\(\*g\) = $\{&#8203;::\}\{foo\};
> >  \_\_END\_\_
> 
> Thanks for the impressive and detailed bug report\, that was useful\.
> 
> Here's a patch that solves the problem\. I've not had time yet to run
> all tests
> with it\, but core tests are fine\.
> 
> \-\-\- sv\.c
> \+\+\+ sv\.c
> @&#8203;@&#8203; \-3718\,8 \+3718\,10 @&#8203;@&#8203; Perl\_sv\_setsv\_flags\(pTHX\_ SV \*dstr\, regi
>                 GvMULTI\_on\(dstr\);
>                 return;
>             \}
> \-           glob\_assign\_glob\(dstr\, sstr\, dtype\);
> \-           return;
> \+           if \(isGV\_with\_GP\(sstr\)\) \{
> \+               glob\_assign\_glob\(dstr\, sstr\, dtype\);
> \+               return;
> \+           \}
>         \}
> 
>         if \(dtype >= SVt\_PV\) \{
> 


The patch was applied with Change 33807 but no tests were included\.

A patch with the test is attached \(added it in t/op/local\.t\)\.


Kind regards\,

Bram

**Comment by p5pRT** [comment]
### From p5p@spam.wizbit.be

<details><summary>Inline Patch</summary>

```diff
--- old/t/op/local.t	2008-08-10 19:47:08.000000000 +0200
+++ new/t/op/local.t	2008-08-10 19:55:51.000000000 +0200
@@ -5,7 +5,7 @@
     @INC = qw(. ../lib);
     require './test.pl';
 }
-plan tests => 122;
+plan tests => 123;
 
 my $list_assignment_supported = 1;
 
@@ -451,6 +451,11 @@
     is($h{'k1'},111);
 }
 
+like( runperl(stderr => 1,
+              prog => 'use constant foo => q(a);' .
+                      'index(q(a), foo);' .
+                      'local *g=${::}{foo};print "ok";'), "ok", "[perl #52740]");
+
 # Keep this test last, as it can SEGV
 {
     local *@;
```
</details>

**Comment by p5pRT** [comment]
### From @tux

On Sun\, 10 Aug 2008 10&#8203;:59&#8203;:16 \-0700\, "Bram via RT"
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

> The patch was applied with Change 33807 but no tests were included\.
> 
> A patch with the test is attached \(added it in t/op/local\.t\)\.

Thanks\, applied as change \#34198

> Kind regards\,
> 
> Bram


\-\- 
H\.Merijn Brand          Amsterdam Perl Mongers  http&#8203;://amsterdam\.pm\.org/
using & porting perl 5\.6\.2\, 5\.8\.x\, 5\.10\.x\, 5\.11\.x on HP\-UX 10\.20\, 11\.00\,
11\.11\, 11\.23\, and 11\.31\, SuSE 10\.1\, 10\.2\, and 10\.3\, AIX 5\.2\, and Cygwin\.
http&#8203;://mirrors\.develooper\.com/hpux/           http&#8203;://www\.test\-smoke\.org/
http&#8203;://qa\.perl\.org      http&#8203;://www\.goldmark\.org/jeff/stupid\-disclaimers/
