### ISSUE TITLE
segfault in perl_clone(), probably due to running out of memory

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9332]
Migrated from [rt.perl.org#54224](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=54224) (status was 'open')

Searchable as RT54224$

**Comment by p5pRT** [comment]
### From @ntyni

This is a bug report for perl from Niko Tyni \<ntyni@&#8203;debian\.org>\,
generated with the help of perlbug 1\.36 running under perl 5\.10\.0\.




---
As reported in \<http&#8203;://bugs\.debian\.org/343690>\, the attached script
crashes 5\.8\.8\, 5\.10\.0 and blead @&#8203;33824 in a mostly reproducible way with
a segmentation fault\.

Note that unlimiting the process stack size \('ulimit \-s unlimited' or the
like\) seems to be required\, and it takes three or four tries on my amd64
SMP host to get it to crash\. The sysctls may be required on Linux to keep
the system from swapping itself to death first \(vm\.overcommit\_memory=2
means never overcommit\, see proc\(5\)\)\.

Severity set to "low" because I assume the system is running out of
memory during perl\_clone\(\)\, which makes it mostly a user error\. The
situation is not handled very gracefully\, though\.

Backtrace on 5\.10\.0 follows\. The resulting core file is obscenely big\. The
number of Perl\_\*\_dup calls and the final crashing place in the stack
trace varies\.

% debugperl ~/t\.pl
sid% debugperl ~/t\.pl
0
Thread creation failed&#8203;: pthread\_create returned 12 at /home/niko/t\.pl
line 26\.
Out of memory\!
sid% debugperl ~/t\.pl
0
Thread creation failed&#8203;: pthread\_create returned 12 at /home/niko/t\.pl
line 26\.
\-\-76\-\-
76
76
76

sid% debugperl ~/t\.pl
0
Thread creation failed&#8203;: pthread\_create returned 12 at /home/niko/t\.pl
line 26\.
Thread creation failed&#8203;: pthread\_create returned 12 at /home/niko/t\.pl
line 26\.
zsh&#8203;: segmentation fault \(core dumped\)  debugperl ~/t\.pl

\#0  0x00000000004833bf in S\_more\_bodies \(my\_perl=0x1d50da0\, sv\_type=SVt\_PVAV\) at sv\.c&#8203;:1065
\#1  0x0000000000484536 in Perl\_sv\_dup \(my\_perl=0x1d50da0\, sstr=0x9c5d88\, param=0x40601c20\) at sv\.c&#8203;:10106
\#2  0x00000000004844b6 in Perl\_sv\_dup \(my\_perl=0x1d50da0\, sstr=0x9c5d70\, param=0x40601c20\) at sv\.c&#8203;:10218
\#3  0x00000000004845d0 in Perl\_sv\_dup \(my\_perl=0x1d50da0\, sstr=0x9c5d58\, param=0x40601c20\) at sv\.c&#8203;:10304
\#4  0x0000000000484413 in Perl\_sv\_dup \(my\_perl=0x1d50da0\, sstr=0x9c5bd8\, param=0x40601c20\) at sv\.c&#8203;:10305
\#5  0x0000000000485605 in Perl\_gp\_dup \(my\_perl=0x1d50da0\, gp=0x9c9fc8\, param=0x40601c20\) at sv\.c&#8203;:9738
\#6  0x0000000000483e59 in Perl\_sv\_dup \(my\_perl=0x1d50da0\, sstr=0x9c5bc0\, param=0x40601c20\) at sv\.c&#8203;:10172
\#7  0x000000000046c973 in Perl\_he\_dup \(my\_perl=0x1d50da0\, e=0x9c02f8\, shared=\-96 ' '\, param=0x40601c20\)
&nbsp;    at hv\.c&#8203;:189
\#8  0x0000000000484023 in Perl\_sv\_dup \(my\_perl=0x1d50da0\, sstr=0x9c5b90\, param=0x40601c20\) at sv\.c&#8203;:10247
\#9  0x00000000004855ca in Perl\_gp\_dup \(my\_perl=0x1d50da0\, gp=0x9c9df8\, param=0x40601c20\) at sv\.c&#8203;:9736
\#10 0x0000000000483e59 in Perl\_sv\_dup \(my\_perl=0x1d50da0\, sstr=0x9c5b78\, param=0x40601c20\) at sv\.c&#8203;:10172
\#11 0x000000000046c973 in Perl\_he\_dup \(my\_perl=0x1d50da0\, e=0x9c02b0\, shared=\-32 'à'\, param=0x40601c20\)
&nbsp;    at hv\.c&#8203;:189
\#12 0x0000000000484023 in Perl\_sv\_dup \(my\_perl=0x1d50da0\, sstr=0x9605d8\, param=0x40601c20\) at sv\.c&#8203;:10247
\#13 0x0000000000483e47 in Perl\_sv\_dup \(my\_perl=0x1d50da0\, sstr=0x9605c0\, param=0x40601c20\) at sv\.c&#8203;:10171
\#14 0x0000000000498995 in perl\_clone \(proto\_perl=0x91cda0\, flags=2\) at sv\.c&#8203;:11077
\#15 0x00002b2f8a126244 in XS\_threads\_create \(my\_perl=0x91cda0\, cv=\<value optimized out>\)
&nbsp;    at threads\.xs&#8203;:666
\#16 0x0000000000479a78 in Perl\_pp\_entersub \(my\_perl=0x91cda0\) at pp\_hot\.c&#8203;:2847
\#17 0x00000000004533f1 in Perl\_runops\_debug \(my\_perl=0x91cda0\) at dump\.c&#8203;:1931
\#18 0x0000000000472628 in Perl\_call\_sv \(my\_perl=0x91cda0\, sv=0x9d5e08\, flags=4\) at perl\.c&#8203;:2653
\#19 0x00002b2f8a127d6e in S\_ithread\_run \(arg=\<value optimized out>\) at threads\.xs&#8203;:440
\#20 0x00002b2f84787017 in start\_thread \(\) from /lib/libpthread\.so\.0
\#21 0x00002b2f84a6154d in clone \(\) from /lib/libc\.so\.6
\#22 0x0000000000000000 in ?? \(\)




---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=low


---
Site configuration information for perl 5\.10\.0&#8203;:

Configured by Debian Project at Thu May  8 11&#8203;:57&#8203;:24 UTC 2008\.

Summary of my perl5 \(revision 5 version 10 subversion 0\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.18\-6\-xen\-amd64\, archname=x86\_64\-linux\-gnu\-thread\-multi
&nbsp;    uname='linux sid 2\.6\.18\-6\-xen\-amd64 \#1 smp thu apr 24 05&#8203;:10&#8203;:26 utc 2008 x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN \-Dcccdlflags=\-fPIC \-Darchname=x86\_64\-linux\-gnu \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.10 \-Darchlib=/usr/lib/perl/5\.10 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.10\.0 \-Dsitearch=/usr/local/lib/perl/5\.10\.0 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1 \-Dsiteman3dir=/usr/local/man/man3 \-Dman1ext=1 \-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Ud\_ualarm \-Uusesfio \-Uusenm \-DDEBUGGING=\-g \-Doptimize=\-O2 \-Duseshrplib \-Dlibperl=libperl\.so\.5\.10\.0 \-Dd\_dosuid \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing \-pipe \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2 \-g'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing \-pipe \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.2\.3 \(Debian 4\.2\.3\-5\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64
&nbsp;    libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    libc=/lib/libc\-2\.7\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.10\.0
&nbsp;    gnulibc\_version='2\.7'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-g \-L/usr/local/lib'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl 5\.10\.0&#8203;:
&nbsp;    /etc/perl
&nbsp;    /usr/local/lib/perl/5\.10\.0
&nbsp;    /usr/local/share/perl/5\.10\.0
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/perl/5\.10
&nbsp;    /usr/share/perl/5\.10
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    \.



---
Environment for perl 5\.10\.0&#8203;:
&nbsp;    HOME=/home/niko
&nbsp;    LANG=en\_US\.UTF\-8
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LC\_CTYPE=fi\_FI\.UTF\-8
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/niko/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/bin/X11&#8203;:/usr/games&#8203;:/sbin&#8203;:/usr/sbin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/zsh

**Comment by p5pRT** [comment]
### From @ntyni

[t.pl](https://rt-archive.perl.org/perl5/Ticket/Attachment/405274/183986/t.pl)

**Comment by p5pRT** [comment]
### From @jimc




 fg
\./perl \-Ilib ~/Download/t\.pl
Perl exited with active threads&#8203;:
&nbsp;    28 running and unjoined
&nbsp;    1 finished and unjoined
&nbsp;    222 running and detached

with \-Dm also\, it segfaults quickly

dmesg says&#8203;:
perl\[12674\]&#8203;: segfault at abababb3 ip 0814f755 sp bf970f10 error 4 in
perl\[8048000\+28a000\]

the abababb3 looks a lot like a poisoned addr&#8203;: = abababab \+ 8


I get lots of segvs in the spawned threads 
\(apparently\, cuz main script finishes\)

Thread creation failed&#8203;: pthread\_create returned 11 at
/home/jimc/Download/t\.pl line 25\.
Thread creation failed&#8203;: pthread\_create returned 11 at
/home/jimc/Download/t\.pl line 25\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'
