### ISSUE TITLE
assertion failure fiddling with @ISA

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9337]
Migrated from [rt.perl.org#54566](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=54566) (status was 'resolved')

Searchable as RT54566$

**Comment by p5pRT** [comment]
### From @ntyni


This is a bug report for perl from Niko Tyni \<ntyni@&#8203;debian\.org>\,
generated with the help of perlbug 1\.36 running under perl 5\.10\.0\.




---
This one\-liner\, reduced from code in HTML&#8203;::Mason&#8203;::Request\, causes an
assertion failure on blead@&#8203;33852&#8203;:

% \./miniperl \-e '@&#8203;ISA=q/a/; $\#ISA; $ISA\[0\]=q/b/'
miniperl&#8203;: mg\.c&#8203;:1587&#8203;: Perl\_magic\_setisa&#8203;: Assertion \`\(\(\(\(\_gv\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(\_gv\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_gv\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.
zsh&#8203;: abort \(core dumped\)  \./miniperl \-e '@&#8203;ISA=q/a/; $\#ISA; $ISA\[0\]=q/b/'

\#0  0x00002b6aba3ac165 in raise \(\) from /lib/libc\.so\.6
\#1  0x00002b6aba3ad610 in abort \(\) from /lib/libc\.so\.6
\#2  0x00002b6aba3a560f in \_\_assert\_fail \(\) from /lib/libc\.so\.6
\#3  0x00000000004c7ae7 in Perl\_magic\_setisa \(my\_perl=0x985010\, sv=0x988e78\, mg=0x9b0988\) at mg\.c&#8203;:1583
\#4  0x00000000004c05f5 in Perl\_mg\_set \(my\_perl=0x985010\, sv=0x988e78\) at mg\.c&#8203;:291
\#5  0x000000000050434c in Perl\_pp\_sassign \(my\_perl=0x985010\) at pp\_hot\.c&#8203;:196
\#6  0x00000000004ad840 in Perl\_runops\_debug \(my\_perl=0x985010\) at dump\.c&#8203;:1984
\#7  0x00000000004f7072 in S\_run\_body \(my\_perl=0x985010\, oldscope=1\) at perl\.c&#8203;:2392
\#8  0x00000000004f63a4 in perl\_run \(my\_perl=0x985010\) at perl\.c&#8203;:2312
\#9  0x00000000006b1712 in main \(argc=3\, argv=0x7ffff121fdf8\, env=0x7ffff121fe18\) at miniperlmain\.c&#8203;:113

As seen in \<http&#8203;://bugs\.debian\.org/480480>\, this segfaults on 5\.10\.0
in the subsequent call to Perl\_mro\_isa\_changed\_in\(\) as 'stash' ends up NULL\. 

The segfault is gone with change 33684\, but the assertion failure remains
with \-DDEBUGGING\, indicating there's another bug in there\.


---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=medium


---
Site configuration information for perl 5\.10\.0&#8203;:

Configured by Debian Project at Tue May 20 20&#8203;:09&#8203;:17 UTC 2008\.

Summary of my perl5 \(revision 5 version 10 subversion 0\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.18\-6\-xen\-amd64\, archname=x86\_64\-linux\-gnu\-thread\-multi
&nbsp;    uname='linux sid 2\.6\.18\-6\-xen\-amd64 \#1 smp thu may 8 08&#8203;:34&#8203;:37 utc 2008 x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN \-Dcccdlflags=\-fPIC \-Darchname=x86\_64\-linux\-gnu \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.10 \-Darchlib=/usr/lib/perl/5\.10 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.10\.0 \-Dsitearch=/usr/local/lib/perl/5\.10\.0 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1 \-Dsiteman3dir=/usr/local/man/man3 \-Dman1ext=1 \-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Ud\_ualarm \-Uusesfio \-Uusenm \-DDEBUGGING=\-g \-Doptimize=\-O2 \-Duseshrplib \-Dlibperl=libperl\.so\.5\.10\.0 \-Dd\_dosuid \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing \-pipe \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2 \-g'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing \-pipe \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.2\.3 \(Debian 4\.2\.3\-5\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64
&nbsp;    libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    libc=/lib/libc\-2\.7\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.10\.0
&nbsp;    gnulibc\_version='2\.7'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-g \-L/usr/local/lib'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl 5\.10\.0&#8203;:
&nbsp;    /etc/perl
&nbsp;    /usr/local/lib/perl/5\.10\.0
&nbsp;    /usr/local/share/perl/5\.10\.0
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/perl/5\.10
&nbsp;    /usr/share/perl/5\.10
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    \.



---
Environment for perl 5\.10\.0&#8203;:
&nbsp;    HOME=/home/niko
&nbsp;    LANG=en\_US\.UTF\-8
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LC\_CTYPE=fi\_FI\.UTF\-8
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/niko/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/bin/X11&#8203;:/usr/games&#8203;:/sbin&#8203;:/usr/sbin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/zsh

**Comment by p5pRT** [comment]
### From @rgs

2008/5/21 via RT Niko Tyni \<perlbug\-followup@&#8203;perl\.org>&#8203;:
> This one\-liner\, reduced from code in HTML&#8203;::Mason&#8203;::Request\, causes an
> assertion failure on blead@&#8203;33852&#8203;:
>
> % \./miniperl \-e '@&#8203;ISA=q/a/; $\#ISA; $ISA\[0\]=q/b/'
> miniperl&#8203;: mg\.c&#8203;:1587&#8203;: Perl\_magic\_setisa&#8203;: Assertion \`\(\(\(\(\_gv\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(\_gv\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_gv\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.
> zsh&#8203;: abort \(core dumped\)  \./miniperl \-e '@&#8203;ISA=q/a/; $\#ISA; $ISA\[0\]=q/b/'
>

Looks like the original author of the code overlooked the possibility
for @&#8203;ISA to have several kinds of magic\.

Here's a patch :

<details><summary>Inline Patch</summary>

```diff
--- mg.c.orig   2008-05-12 18:29:57.000000000 +0200
+++ mg.c        2008-05-21 14:23:45.000000000 +0200
@@ -1583,7 +1583,7 @@ Perl_magic_setisa(pTHX_ SV *sv, MAGIC *m
     stash = GvSTASH(
         SvTYPE(mg->mg_obj) == SVt_PVGV
             ? (GV*)mg->mg_obj
-            : (GV*)SvMAGIC(mg->mg_obj)->mg_obj
+            : (GV*)mg_find(mg->mg_obj, PERL_MAGIC_isa)->mg_obj
     );

     if (stash)
@@ -1609,7 +1609,7 @@ Perl_magic_clearisa(pTHX_ SV *sv, MAGIC
     stash = GvSTASH(
         SvTYPE(mg->mg_obj) == SVt_PVGV
             ? (GV*)mg->mg_obj
-            : (GV*)SvMAGIC(mg->mg_obj)->mg_obj
+            : (GV*)mg_find(mg->mg_obj, PERL_MAGIC_isa)->mg_obj
     );

     if (stash)
```
</details>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tux

On Wed\, 21 May 2008 14&#8203;:42&#8203;:48 \+0200\, "Rafael Garcia\-Suarez"
\<rgarciasuarez@&#8203;gmail\.com> wrote&#8203;:

> 2008/5/21 via RT Niko Tyni \<perlbug\-followup@&#8203;perl\.org>&#8203;:
> > This one\-liner\, reduced from code in HTML&#8203;::Mason&#8203;::Request\, causes an
> > assertion failure on blead@&#8203;33852&#8203;:
> >
> > % \./miniperl \-e '@&#8203;ISA=q/a/; $\#ISA; $ISA\[0\]=q/b/'
> > miniperl&#8203;: mg\.c&#8203;:1587&#8203;: Perl\_magic\_setisa&#8203;: Assertion \`\(\(\(\(\_gv\)\->sv\_flags & \(0x00004000|0x00008000\)\) == 0x00008000\) && \(\(\(svtype\)\(\(\_gv\)\->sv\_flags & 0xff\)\) == SVt\_PVGV || \(\(svtype\)\(\(\_gv\)\->sv\_flags & 0xff\)\) == SVt\_PVLV\)\)' failed\.
> > zsh&#8203;: abort \(core dumped\)  \./miniperl \-e '@&#8203;ISA=q/a/; $\#ISA; $ISA\[0\]=q/b/'
> >
> 
> Looks like the original author of the code overlooked the possibility
> for @&#8203;ISA to have several kinds of magic\.
> 
> Here's a patch :

Change 33898 submitted\.

> \-\-\- mg\.c\.orig   2008\-05\-12 18&#8203;:29&#8203;:57\.000000000 \+0200
> \+\+\+ mg\.c        2008\-05\-21 14&#8203;:23&#8203;:45\.000000000 \+0200
> @&#8203;@&#8203; \-1583\,7 \+1583\,7 @&#8203;@&#8203; Perl\_magic\_setisa\(pTHX\_ SV \*sv\, MAGIC \*m
>      stash = GvSTASH\(
>          SvTYPE\(mg\->mg\_obj\) == SVt\_PVGV
>              ? \(GV\*\)mg\->mg\_obj
> \-            : \(GV\*\)SvMAGIC\(mg\->mg\_obj\)\->mg\_obj
> \+            : \(GV\*\)mg\_find\(mg\->mg\_obj\, PERL\_MAGIC\_isa\)\->mg\_obj
>      \);
> 
>      if \(stash\)
> @&#8203;@&#8203; \-1609\,7 \+1609\,7 @&#8203;@&#8203; Perl\_magic\_clearisa\(pTHX\_ SV \*sv\, MAGIC
>      stash = GvSTASH\(
>          SvTYPE\(mg\->mg\_obj\) == SVt\_PVGV
>              ? \(GV\*\)mg\->mg\_obj
> \-            : \(GV\*\)SvMAGIC\(mg\->mg\_obj\)\->mg\_obj
> \+            : \(GV\*\)mg\_find\(mg\->mg\_obj\, PERL\_MAGIC\_isa\)\->mg\_obj
>      \);
> 
>      if \(stash\)

\-\- 
H\.Merijn Brand         Amsterdam Perl Mongers \(http&#8203;://amsterdam\.pm\.org/\)
using & porting perl 5\.6\.2\, 5\.8\.x\, 5\.10\.x  on HP\-UX 10\.20\, 11\.00\, 11\.11\,
& 11\.23\, SuSE 10\.1 & 10\.2\, AIX 5\.2\, and Cygwin\.       http&#8203;://qa\.perl\.org
http&#8203;://mirrors\.develooper\.com/hpux/            http&#8203;://www\.test\-smoke\.org
&nbsp;                        http&#8203;://www\.goldmark\.org/jeff/stupid\-disclaimers/

**Comment by p5pRT** [comment]
@rgs - Status changed from 'open' to 'resolved'
