### ISSUE TITLE
crash on binary-or lvalue operation on qr//

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9353]
Migrated from [rt.perl.org#54956](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=54956) (status was 'resolved')

Searchable as RT54956$

**Comment by p5pRT** [comment]
### From @ntyni


This is a bug report for perl from Niko Tyni \<ntyni@&#8203;debian\.org>\,
generated with the help of perlbug 1\.36 running under perl 5\.10\.0\.




---
As seen in \<http&#8203;://bugs\.debian\.org/483150>\, this one\-liner crashes 5\.10\.0
and blead@&#8203;33937 but not 5\.8\.8&#8203;:

\# \./miniperl \-e 'my $re = qr/x/; $re |= "y"'
miniperl&#8203;: doop\.c&#8203;:1259&#8203;: Perl\_do\_vop&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) >= SVt\_PV' failed\.

\#0  0x00002b358c697165 in raise \(\) from /lib/libc\.so\.6
\#1  0x00002b358c698610 in abort \(\) from /lib/libc\.so\.6
\#2  0x00002b358c69060f in \_\_assert\_fail \(\) from /lib/libc\.so\.6
\#3  0x000000000062bed6 in Perl\_do\_vop \(my\_perl=0x987010\, optype=93\, sv=0x9a9f28\, left=0x9a9f28\, 
&nbsp;    right=0x9a9fa0\) at doop\.c&#8203;:1259
\#4  0x000000000059c4bb in Perl\_pp\_bit\_or \(my\_perl=0x987010\) at pp\.c&#8203;:2385
\#5  0x00000000004ada20 in Perl\_runops\_debug \(my\_perl=0x987010\) at dump\.c&#8203;:1984
\#6  0x00000000004f716e in S\_run\_body \(my\_perl=0x987010\, oldscope=1\) at perl\.c&#8203;:2392
\#7  0x00000000004f64a0 in perl\_run \(my\_perl=0x987010\) at perl\.c&#8203;:2312
\#8  0x00000000006b1c4a in main \(argc=3\, argv=0x7fff1ef33b08\, env=0x7fff1ef33b28\) at miniperlmain\.c&#8203;:113

On 5\.10\.0 without \-DDEBUGGING this results in 'double free or corruption'\.

Bisecting shows it was broken by change 27859&#8203;:

 commit a39e44f1b8a997f82f02847b565d62c2cd84111f
 Author&#8203;: Jarkko Hietaniemi \<jhi@&#8203;iki\.fi>
 Date&#8203;:   Mon Apr 17 13&#8203;:19&#8203;:37 2006 \+0300

&nbsp;    dooop\.c&#8203;: the strong asserts in Sv\* macros could cause memory leakage \-\- move the macro calls earlier \(Coverity CID 84\)
&nbsp;    Message\-Id&#8203;: \<20060417071937\.C13346CF2D@&#8203;aprikoosi\.hut\.fi>
&nbsp;    
&nbsp;    p4raw\-id&#8203;: //depot/perl@&#8203;27859



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=medium


---
Site configuration information for perl 5\.10\.0&#8203;:

Configured by Debian Project at Thu May  8 11&#8203;:57&#8203;:24 UTC 2008\.

Summary of my perl5 \(revision 5 version 10 subversion 0\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.18\-6\-xen\-amd64\, archname=x86\_64\-linux\-gnu\-thread\-multi
&nbsp;    uname='linux sid 2\.6\.18\-6\-xen\-amd64 \#1 smp thu apr 24 05&#8203;:10&#8203;:26 utc 2008 x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN \-Dcccdlflags=\-fPIC \-Darchname=x86\_64\-linux\-gnu \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.10 \-Darchlib=/usr/lib/perl/5\.10 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.10\.0 \-Dsitearch=/usr/local/lib/perl/5\.10\.0 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1 \-Dsiteman3dir=/usr/local/man/man3 \-Dman1ext=1 \-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Ud\_ualarm \-Uusesfio \-Uusenm \-DDEBUGGING=\-g \-Doptimize=\-O2 \-Duseshrplib \-Dlibperl=libperl\.so\.5\.10\.0 \-Dd\_dosuid \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing \-pipe \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2 \-g'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing \-pipe \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.2\.3 \(Debian 4\.2\.3\-5\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64
&nbsp;    libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    libc=/lib/libc\-2\.7\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.10\.0
&nbsp;    gnulibc\_version='2\.7'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-g \-L/usr/local/lib'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl 5\.10\.0&#8203;:
&nbsp;    /etc/perl
&nbsp;    /usr/local/lib/perl/5\.10\.0
&nbsp;    /usr/local/share/perl/5\.10\.0
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/perl/5\.10
&nbsp;    /usr/share/perl/5\.10
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    \.



---
Environment for perl 5\.10\.0&#8203;:
&nbsp;    HOME=/home/niko
&nbsp;    LANG=en\_US\.UTF\-8
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LC\_CTYPE=fi\_FI\.UTF\-8
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/niko/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/bin/X11&#8203;:/usr/games&#8203;:/sbin&#8203;:/usr/sbin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/zsh

**Comment by p5pRT** [comment]
### From @smpeters

On Tue May 27 23&#8203;:17&#8203;:19 2008\, ntyni@&#8203;debian\.org wrote&#8203;:
> 
> This is a bug report for perl from Niko Tyni \<ntyni@&#8203;debian\.org>\,
> generated with the help of perlbug 1\.36 running under perl 5\.10\.0\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> As seen in \<http&#8203;://bugs\.debian\.org/483150>\, this one\-liner crashes
>    5\.10\.0
> and blead@&#8203;33937 but not 5\.8\.8&#8203;:
> 
> \# \./miniperl \-e 'my $re = qr/x/; $re |= "y"'
> miniperl&#8203;: doop\.c&#8203;:1259&#8203;: Perl\_do\_vop&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\-
>    >sv\_flags & 0xff\)\) >= SVt\_PV' failed\.
> 
> \#0  0x00002b358c697165 in raise \(\) from /lib/libc\.so\.6
> \#1  0x00002b358c698610 in abort \(\) from /lib/libc\.so\.6
> \#2  0x00002b358c69060f in \_\_assert\_fail \(\) from /lib/libc\.so\.6
> \#3  0x000000000062bed6 in Perl\_do\_vop \(my\_perl=0x987010\, optype=93\,
>    sv=0x9a9f28\, left=0x9a9f28\,
>     right=0x9a9fa0\) at doop\.c&#8203;:1259
> \#4  0x000000000059c4bb in Perl\_pp\_bit\_or \(my\_perl=0x987010\) at
>    pp\.c&#8203;:2385
> \#5  0x00000000004ada20 in Perl\_runops\_debug \(my\_perl=0x987010\) at
>    dump\.c&#8203;:1984
> \#6  0x00000000004f716e in S\_run\_body \(my\_perl=0x987010\, oldscope=1\) at
>    perl\.c&#8203;:2392
> \#7  0x00000000004f64a0 in perl\_run \(my\_perl=0x987010\) at perl\.c&#8203;:2312
> \#8  0x00000000006b1c4a in main \(argc=3\, argv=0x7fff1ef33b08\,
>    env=0x7fff1ef33b28\) at miniperlmain\.c&#8203;:113
> 
> On 5\.10\.0 without \-DDEBUGGING this results in 'double free or
>    corruption'\.
> 
> Bisecting shows it was broken by change 27859&#8203;:
> 
>  commit a39e44f1b8a997f82f02847b565d62c2cd84111f
>  Author&#8203;: Jarkko Hietaniemi \<jhi@&#8203;iki\.fi>
>  Date&#8203;:   Mon Apr 17 13&#8203;:19&#8203;:37 2006 \+0300
> 
>     dooop\.c&#8203;: the strong asserts in Sv\* macros could cause memory
>    leakage \-\- move the macro calls earlier \(Coverity CID 84\)
>     Message\-Id&#8203;: \<20060417071937\.C13346CF2D@&#8203;aprikoosi\.hut\.fi>
> 
>     p4raw\-id&#8203;: //depot/perl@&#8203;27859
> 

Yep\, running with a debugging Perl gives me\.\.\.

Assertion \(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) >= SVt\_PV failed&#8203;: file
"doop\.c"\, line 1234 at \-e line 1\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @smpeters

On Wed\, May 28\, 2008 at 8&#8203;:35 AM\, Steve Peters via RT
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> On Tue May 27 23&#8203;:17&#8203;:19 2008\, ntyni@&#8203;debian\.org wrote&#8203;:
>>
>> This is a bug report for perl from Niko Tyni \<ntyni@&#8203;debian\.org>\,
>> generated with the help of perlbug 1\.36 running under perl 5\.10\.0\.
>>
>>
>> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
>> As seen in \<http&#8203;://bugs\.debian\.org/483150>\, this one\-liner crashes
>>    5\.10\.0
>> and blead@&#8203;33937 but not 5\.8\.8&#8203;:
>>
>> \# \./miniperl \-e 'my $re = qr/x/; $re |= "y"'
>> miniperl&#8203;: doop\.c&#8203;:1259&#8203;: Perl\_do\_vop&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\-
>>    >sv\_flags & 0xff\)\) >= SVt\_PV' failed\.
>>
>> \#0  0x00002b358c697165 in raise \(\) from /lib/libc\.so\.6
>> \#1  0x00002b358c698610 in abort \(\) from /lib/libc\.so\.6
>> \#2  0x00002b358c69060f in \_\_assert\_fail \(\) from /lib/libc\.so\.6
>> \#3  0x000000000062bed6 in Perl\_do\_vop \(my\_perl=0x987010\, optype=93\,
>>    sv=0x9a9f28\, left=0x9a9f28\,
>>     right=0x9a9fa0\) at doop\.c&#8203;:1259
>> \#4  0x000000000059c4bb in Perl\_pp\_bit\_or \(my\_perl=0x987010\) at
>>    pp\.c&#8203;:2385
>> \#5  0x00000000004ada20 in Perl\_runops\_debug \(my\_perl=0x987010\) at
>>    dump\.c&#8203;:1984
>> \#6  0x00000000004f716e in S\_run\_body \(my\_perl=0x987010\, oldscope=1\) at
>>    perl\.c&#8203;:2392
>> \#7  0x00000000004f64a0 in perl\_run \(my\_perl=0x987010\) at perl\.c&#8203;:2312
>> \#8  0x00000000006b1c4a in main \(argc=3\, argv=0x7fff1ef33b08\,
>>    env=0x7fff1ef33b28\) at miniperlmain\.c&#8203;:113
>>
>> On 5\.10\.0 without \-DDEBUGGING this results in 'double free or
>>    corruption'\.
>>
>> Bisecting shows it was broken by change 27859&#8203;:
>>
>>  commit a39e44f1b8a997f82f02847b565d62c2cd84111f
>>  Author&#8203;: Jarkko Hietaniemi \<jhi@&#8203;iki\.fi>
>>  Date&#8203;:   Mon Apr 17 13&#8203;:19&#8203;:37 2006 \+0300
>>
>>     dooop\.c&#8203;: the strong asserts in Sv\* macros could cause memory
>>    leakage \-\- move the macro calls earlier \(Coverity CID 84\)
>>     Message\-Id&#8203;: \<20060417071937\.C13346CF2D@&#8203;aprikoosi\.hut\.fi>
>>
>>     p4raw\-id&#8203;: //depot/perl@&#8203;27859
>>
>
> Yep\, running with a debugging Perl gives me\.\.\.
>
> Assertion \(\(svtype\)\(\(sv\)\->sv\_flags & 0xff\)\) >= SVt\_PV failed&#8203;: file
> "doop\.c"\, line 1234 at \-e line 1\.
>

OK\, after coffee and a think\, a couple of things came up\.  First\, &=
fails similarly\.\.\.

steve@&#8203;picard&#8203;:\~/perl\-current$  \./perl \-e 'my $re = qr/x/; $re &= "y"'
perl&#8203;: doop\.c&#8203;:1259&#8203;: Perl\_do\_vop&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\->sv\_flags &
0xff\)\) >= SVt\_PV' failed\.
Aborted

Second\, the failures only occur with debugging Perls\.  Without debugging\.\.\.

\[steve@&#8203;kirk perl\-current\]$ \./perl \-Ilib \-E'my $re = qr/x/; $re |= "y"; say $re'
y?\-xism&#8203;:x\)

is same as what I get under Perl 5\.8\.8\.

Finally\, the problem isn't qr//\.  Its references in general\.  For example\.\.\.

steve@&#8203;picard&#8203;:\~/perl\-current$ \./perl \-e ' my $sploosh = "aiieee";
$powie = \\$sploosh; $powie &= "spla\_a\_t"'
perl&#8203;: doop\.c&#8203;:1259&#8203;: Perl\_do\_vop&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\->sv\_flags &
0xff\)\) >= SVt\_PV' failed\.

steve@&#8203;picard&#8203;:\~/perl\-current$ \./perl \-e ' my $sploosh = bless \{\}\,
"Aiieee"; $sploosh &= "spla\_a\_t"'
perl&#8203;: doop\.c&#8203;:1259&#8203;: Perl\_do\_vop&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\->sv\_flags &
0xff\)\) >= SVt\_PV' failed\.

steve@&#8203;picard&#8203;:\~/perl\-current$ \./perl \-e ' my $sploosh = 1; $powie =
\\$sploosh; $powie &= "spla\_a\_t"'
perl&#8203;: doop\.c&#8203;:1259&#8203;: Perl\_do\_vop&#8203;: Assertion \`\(\(svtype\)\(\(sv\)\->sv\_flags &
0xff\)\) >= SVt\_PV' failed\.

\.\.\.although\, if we have a reference to a number and a number on the
other side\.\.\.

steve@&#8203;picard&#8203;:\~/perl\-current$ \./perl \-e ' my $sploosh = 1; $powie =
\\$sploosh; $powie &= 2'

it works\.  Obviously\, then\, we don't have test cases for bitwise & and
| with references that are not numeric\.  I also don't think I can add
them at the moment since the asserts would kill the tests\.  I'll try
digging into a fix unless someone else wants to take a stab at it
first\.

Steve Peters
steve@&#8203;fisharerojo\.org

**Comment by p5pRT** [comment]
### From module@renee-baecker.de

fixed with
http&#8203;://perl5\.git\.perl\.org/perl\.git/commit/8c8eee8276dbc780932b841fe5183943a7117a3d

**Comment by p5pRT** [comment]
module@renee-baecker.de - Status changed from 'open' to 'resolved'
