### ISSUE TITLE
PerlIO resource leaks on open() and then :pop in :unix and :stdio

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9406]
Migrated from [rt.perl.org#56644](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=56644) (status was 'resolved')

Searchable as RT56644$

**Comment by p5pRT** [comment]
### From g.psy.va@gmail.com

This is a bug report for perl from garo@&#8203;goro\.nonet\,
generated with the help of perlbug 1\.36 running under perl 5\.10\.0\.




---
Hi\, perl5porters\.

I found some problems in perlio\.c; please see and try the following&#8203;:

\#\!perl
my $file = '/dev/null'; \# it doesn't matter
for\(1 \.\. 10\)\{
&nbsp;    open my $fh\, '\<&#8203;:unix'\, $file;
&nbsp;    print fileno\($in\)\, "\\n";
&nbsp;    binmode $fh\, '&#8203;:pop';
\}
\_\_END\_\_

It leads to resource leaks when :unix and :stdio are used\.

The :pop pseudo layer invokes a destructor Popped\(\) of the vtable\, and
the destructor should release their resources\. However\, the :unix and
:stdio layers
do nothing on Popped\(\)\. They release their resources only when their
Close\(\) is called\.

\(Moreover\, PerlIOMmap\_close\(\) is defined in perlio\.c\, but it is not
used anywhere\, although it may be harmless\. I think these issues come
from a bad design of PerlIO virtual table; there are two kind of
destructors\, Popped\(\) and Close\(\)\, which may confuse the PerlIO
authors\. Actually\, only Popped\(\) might be required\.\)

The "ioleaks\.diff" solves these problems\, and "ioleaks\.t" is its tests\.

P\.S\.
I also found a trivial mistake in perliol\.pod\. See the "perliol\.diff"\.



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=low


---
Site configuration information for perl 5\.10\.0&#8203;:

Configured by garo at Sun Jan  6 08&#8203;:39&#8203;:07 JST 2008\.

Summary of my perl5 \(revision 5 version 10 subversion 0\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=cygwin\, osvers=1\.5\.25\(0\.15642\)\, archname=cygwin\-thread\-multi
&nbsp;    uname='cygwin\_nt\-5\.1 goro 1\.5\.25\(0\.15642\) 2007\-12\-14 19&#8203;:21 i686 cygwin '
&nbsp;    config\_args='\-de \-Dmksymlnks \-Doptimize=\-O3 \-Dusethreads
\-Acccdlflags=\-s \-Alddlflags=\-s \-Accdlflags=\-s \-Dman3ext=3pm'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;    usemymalloc=y\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'\, ccflags ='\-DPERL\_USE\_SAFE\_PUTENV \-U\_\_STRICT\_ANSI\_\_
\-fno\-strict\-aliasing \-pipe \-Wall \-Wextra \-Wmissing\-prototypes
\-Winit\-self'\,
&nbsp;    optimize='\-O3'\,
&nbsp;    cppflags='\-DPERL\_USE\_SAFE\_PUTENV \-U\_\_STRICT\_ANSI\_\_
\-fno\-strict\-aliasing \-pipe'
&nbsp;    ccversion=''\, gccversion='3\.4\.4 \(cygming special\, gdc 0\.12\, using
dmd 0\.125\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,
lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='g\+\+'\, ldflags =' \-Wl\,\-\-enable\-auto\-import
\-Wl\,\-\-export\-all\-symbols \-Wl\,\-\-stack\,8388608
\-Wl\,\-\-enable\-auto\-image\-base \-Wl\,\-\-enable\-auto\-import
\-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib /lib
&nbsp;    libs=\-ldl \-lcrypt
&nbsp;    perllibs=\-ldl \-lcrypt
&nbsp;    libc=/usr/lib/libc\.a\, so=dll\, useshrplib=true\, libperl=libperl\.a
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=dll\, d\_dlsymun=undef\, ccdlflags=' \-s'
&nbsp;    cccdlflags='  \-s'\, lddlflags=' \-\-shared  \-Wl\,\-\-enable\-auto\-import
\-Wl\,\-\-export\-all\-symbols \-Wl\,\-\-stack\,8388608
\-Wl\,\-\-enable\-auto\-image\-base \-Wl\,\-\-enable\-auto\-import \-s
\-L/usr/local/lib'

Locally applied patches&#8203;:




---
@&#8203;INC for perl 5\.10\.0&#8203;:
&nbsp;    /usr/local/lib/perl5/5\.10\.0/cygwin\-thread\-multi
&nbsp;    /usr/local/lib/perl5/5\.10\.0
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.10\.0/cygwin\-thread\-multi
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.10\.0
&nbsp;    \.



---
Environment for perl 5\.10\.0&#8203;:
&nbsp;    HOME=/home/garo
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/usr/local/parrot/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/X11R6/bin&#8203;:/usr/local/bin&#8203;:/cygdrive/c/Program
Files/Microsoft Visual Studio 8/Common7/IDE&#8203;:/cygdrive/c/Program
Files/Microsoft Visual Studio 8/VC/BIN&#8203;:/cygdrive/c/Program
Files/Microsoft Visual Studio 8/Common7/Tools&#8203;:/cygdrive/c/Program
Files/Microsoft Visual Studio 8/Common7/Tools/bin&#8203;:/cygdrive/c/Program
Files/Microsoft Visual Studio 8/VC/PlatformSDK/bin&#8203;:/cygdrive/c/Program
Files/Microsoft Visual Studio
8/SDK/v2\.0/bin&#8203;:/cygdrive/c/WINDOWS/Microsoft\.NET/Framework/v2\.0\.50727&#8203;:/cygdrive/c/Program
Files/Microsoft Visual Studio 8/VC/VCPackages&#8203;:/cygdrive/c/program
files/imagemagick\-6\.2\.8\-q16&#8203;:/cygdrive/c/ActivePerl5\.10/bin&#8203;:/cygdrive/c/WINDOWS/system32&#8203;:/cygdrive/c/WINDOWS&#8203;:/cygdrive/c/WINDOWS/System32/Wbem&#8203;:/cygdrive/c/Program
Files/ATI Technologies/ATI Control Panel&#8203;:/cygdrive/c/Program
Files/Microsoft SQL
Server/90/Tools/binn/&#8203;:/cygdrive/c/PROGRA~1/IBM/IBMHOM~1\.04/Outloud&#8203;:/cygdrive/c/Program
Files/QuickTime/QTSystem/&#8203;:/cygdrive/c/Program Files/Microsoft Visual
Studio 8/VC/bin&#8203;:/cygdrive/c/Program Files/R/bin&#8203;:/cygdrive/c/program
files/imagemagick\-6\.2\.8\-q16&#8203;:/cygdrive/c/ActivePerl5\.10/bin&#8203;:/cygdrive/c/WINDOWS/system32&#8203;:/cygdrive/c/WINDOWS&#8203;:/cygdrive/c/WINDOWS/System32/Wbem&#8203;:/cygdrive/c/Program
Files/ATI Technologies/ATI Control Panel&#8203;:/cygdrive/c/Program
Files/Microsoft SQL
Server/90/Tools/binn/&#8203;:/cygdrive/c/PROGRA~1/IBM/IBMHOM~1\.04/Outloud&#8203;:/cygdrive/c/Program
Files/QuickTime/QTSystem/
&nbsp;    PERLIO=&#8203;:perlio
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL \(unset\)

**Comment by p5pRT** [comment]
### From @gfx

I'm sorry\. I forgot to attach the files\.

\-\- 
Goro Fuji

**Comment by p5pRT** [comment]
### From @gfx

\#\!perl
\# ioleaks\.t

use strict;
use warnings;
use Test&#8203;::More 'no\_plan';

\# :unix   \-> not ok
\# :stdio  \-> not ok
\# :perlio \-> ok
\# :crlf   \-> ok

foreach my $layer\(qw\(&#8203;:unix :stdio  :perlio :crlf\)\)\{
&nbsp;    my $base\_fd = do\{ open my $in\, '\<'\, $0 or die $\!; fileno $in \};

&nbsp;    for\(1 \.\. 3\)\{
&nbsp;        open my $fh\, "\<$layer"\, $0 or die $\!;

&nbsp;        is fileno\($fh\)\, $base\_fd\, $layer;
&nbsp;        binmode $fh\, '&#8203;:pop';
&nbsp;    \}
\}

**Comment by p5pRT** [comment]
### From @gfx

<details><summary>ioleaks.diff</summary>

```diff
--- perlio.c~	2008-05-24 19:08:07.373992000 +0900
+++ perlio.c	2008-07-06 20:36:43.547300800 +0900
@@ -2723,10 +2723,15 @@
     return PerlLIO_lseek(PerlIOSelf(f, PerlIOUnix)->fd, 0, SEEK_CUR);
 }
 
-
 IV
 PerlIOUnix_close(pTHX_ PerlIO *f)
 {
+	return PerlIOBase_noop_ok(aTHX_ f);
+}
+
+IV
+PerlIOUnix_popped(pTHX_ PerlIO *f)
+{
     dVAR;
     const int fd = PerlIOSelf(f, PerlIOUnix)->fd;
     int code = 0;
@@ -2759,7 +2764,7 @@
     sizeof(PerlIOUnix),
     PERLIO_K_RAW,
     PerlIOUnix_pushed,
-    PerlIOBase_popped,
+    PerlIOUnix_popped,
     PerlIOUnix_open,
     PerlIOBase_binmode,         /* binmode */
     NULL,
@@ -3109,6 +3114,12 @@
 IV
 PerlIOStdio_close(pTHX_ PerlIO *f)
 {
+	return PerlIOBase_noop_ok(aTHX_ f);
+}
+
+IV
+PerlIOStdio_popped(pTHX_ PerlIO *f)
+{
     FILE * const stdio = PerlIOSelf(f, PerlIOStdio)->stdio;
     if (!stdio) {
 	errno = EBADF;
@@ -3505,7 +3516,7 @@
     sizeof(PerlIOStdio),
     PERLIO_K_BUFFERED|PERLIO_K_RAW,
     PerlIOStdio_pushed,
-    PerlIOBase_popped,
+    PerlIOStdio_popped,
     PerlIOStdio_open,
     PerlIOBase_binmode,         /* binmode */
     NULL,

```
</details>

**Comment by p5pRT** [comment]
### From @gfx

<details><summary>perliol.diff</summary>

```diff
--- perliol.pod~	2007-12-18 19:47:08.000000000 +0900
+++ perliol.pod	2008-07-06 18:31:41.720203200 +0900
@@ -145,7 +145,7 @@
    IV		(*Pushed)(pTHX_ PerlIO *f,const char *mode,SV *arg, PerlIO_funcs *tab);
    IV		(*Popped)(pTHX_ PerlIO *f);
    PerlIO *	(*Open)(pTHX_ PerlIO_funcs *tab,
-  			AV *layers, IV n,
+  			PerlIO_list_t *layers, IV n,
   			const char *mode,
   			int fd, int imode, int perm,
   			PerlIO *old,
@@ -486,7 +486,7 @@
 follows:
 
  PerlIO *	(*Open)(pTHX_ PerlIO_funcs *tab,
-			AV *layers, IV n,
+			PerlIO_list_t *layers, IV n,
 			const char *mode,
 			int fd, int imode, int perm,
 			PerlIO *old,
@@ -494,7 +494,7 @@
 
 Open should (perhaps indirectly) call C<PerlIO_allocate()> to allocate
 a slot in the table and associate it with the layers information for
-the opened file, by calling C<PerlIO_push>.  The I<layers> AV is an
+the opened file, by calling C<PerlIO_push>.  The I<layers> is an
 array of all the layers destined for the C<PerlIO *>, and any
 arguments passed to them, I<n> is the index into that array of the
 layer being called. The macro C<PerlIOArg> will return a (possibly

```
</details>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @smpeters

On Sun Jul 06 16&#8203;:05&#8203;:22 2008\, gfuji@&#8203;cpan\.org wrote&#8203;:
> I'm sorry\. I forgot to attach the files\.
> 


Thanks so much for the excellent work\!  These patches were applied as change \#34775\.

Steve Peters\.

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'open' to 'resolved'

**Comment by khwilliamson** [comment]
This still fails TODO tests on Linux.

**Comment by bram-perl** [comment]
> Thanks so much for the excellent work! These patches were applied as change #34775.

For reference: applied in commit 2556f95e0f4f5e8e95c9766374614ab52edefe3d
```
commit 2556f95e0f4f5e8e95c9766374614ab52edefe3d
Author:     Goro Fuji <gfuji@cpan.org>
AuthorDate: Mon Jul 7 17:04:52 2008 +0900
Commit:     Steve Peters <steve@fisharerojo.org>
CommitDate: Sat Nov 8 05:18:16 2008 +0000

    Re: [perl #56644] PerlIO resource leaks on open() and then :pop in :unix and :stdio
    From: "Goro Fuji" <gfuji@cpan.org>
    Message-ID: <efb9c59b0807061604q476025e9n85893f131a6bf23e@mail.gmail.com>

    p4raw-id: //depot/perl@34775

 MANIFEST               |  1 +
 ext/PerlIO/t/ioleaks.t | 23 +++++++++++++++++++++++
 perlio.c               | 17 ++++++++++++++---
 pod/perliol.pod        |  6 +++---
 4 files changed, 41 insertions(+), 6 deletions(-)
```

but reverted with commit 2376d97dd5675c65de55efc384814387b6c9a63f
```
commit 2376d97dd5675c65de55efc384814387b6c9a63f
Author:     Steve Peters <steve@fisharerojo.org>
AuthorDate: Sat Nov 8 15:51:45 2008 +0000
Commit:     Steve Peters <steve@fisharerojo.org>
CommitDate: Sat Nov 8 15:51:45 2008 +0000

    From change #34775, reverting perlio.c change for now.  Also,
    setting the tests to TODO.
    p4raw-link: @34775 on //depot/perl: 2556f95e0f4f5e8e95c9766374614ab52edefe3d

    p4raw-id: //depot/perl@34778

 ext/PerlIO/t/ioleaks.t | 17 ++++++++++-------
 perlio.c               | 17 +++--------------
 2 files changed, 13 insertions(+), 21 deletions(-)
```

So it was committed and reverted 10 hours later.

**Comment by bram-perl** [comment]
> So it was committed and reverted 10 hours later.

Revert reason: https://www.nntp.perl.org/group/perl.perl5.porters/2008/11/msg141398.html
```
Change 34775 by stevep@stevep-kirk on 2008/11/08 05:18:16

	Subject:  Re: [perl #56644] PerlIO resource leaks on open() and then :pop in :unix and :stdio
	From: "Goro Fuji" <gfuji@cpan.org>
	Date: Mon, 7 Jul 2008 08:04:52 +0900
	Message-ID: <efb9c59b0807061604q476025e9n85893f131a6bf23e@mail.gmail.com>

causes cloexec.t to hang after the second test:

  mhx@r2d2 ~/src/perl/dist/rsync/perl-current-debug $ ./perl -I lib t/run/cloexec.t
  1..22
  ok 1 - parent open fd=3 ($^F=2)
  ok 2 - tmpfile 'tmp26883D' exists


(gdb) bt
#0  0xffffe424 in __kernel_vsyscall ()
#1  0xb7f15fd3 in __read_nocancel () from /lib/libpthread.so.0
#2  0x082c902f in PerlIOUnix_read (my_perl=0x8402db8, f=0x84bdb6c, vbuf=0x84bdbe4, count=4096) at perlio.c:2689
#3  0x082c6cba in Perl_PerlIO_read (my_perl=0x8402db8, f=0x84bdb6c, vbuf=0x84bdbe4, count=4096) at perlio.c:1634
#4  0x082cac20 in PerlIOBuf_fill (my_perl=0x8402db8, f=0x841cf98) at perlio.c:3907
#5  0x082c7125 in Perl_PerlIO_fill (my_perl=0x8402db8, f=0x841cf98) at perlio.c:1730
#6  0x082c7d65 in PerlIOBase_read (my_perl=0x8402db8, f=0x841cf98, vbuf=0xbfacda17, count=1) at perlio.c:2148
#7  0x082cacfc in PerlIOBuf_read (my_perl=0x8402db8, f=0x841cf98, vbuf=0xbfacda17, count=1) at perlio.c:3928
#8  0x082c6cba in Perl_PerlIO_read (my_perl=0x8402db8, f=0x841cf98, vbuf=0xbfacda17, count=1) at perlio.c:1634
#9  0x082ccb7f in PerlIO_getc (f=0x841cf98) at perlio.c:5078
#10 0x08186c63 in Perl_sv_gets (my_perl=0x8402db8, sv=0x84a4aa8, fp=0x841cf98, append=0) at sv.c:6889
#11 0x08230227 in Perl_pp_backtick (my_perl=0x8402db8) at pp_sys.c:334
#12 0x080dd888 in Perl_runops_debug (my_perl=0x8402db8) at dump.c:1981
#13 0x08126d4b in S_run_body (my_perl=0x8402db8, oldscope=1) at perl.c:2399
#14 0x08126112 in perl_run (my_perl=0x8402db8) at perl.c:2319
#15 0x08063fa7 in main (argc=4, argv=0xbfad00a4, env=0xbfad00b8) at perlmain.c:117
```
