### ISSUE TITLE
Segmentation fault in Perl_csighandler when receiving SIGCHLD during thread creation

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9570]
Migrated from [rt.perl.org#60724](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=60724) (status was 'resolved')

Searchable as RT60724$

**Comment by p5pRT** [comment]
### From mail@pascalhofmann.de

I'have a program which uses threads and has a custom signal handler for 
SIGCHLD\. If a SIGCHLD is received during thread creation perl produces a 
segfault\. Here is the stacktrace from two gdb\-sessions&#8203;:


Program received signal SIGSEGV\, Segmentation fault\.
\[Switching to Thread 0xb7ee08c0 \(LWP 1328\)\]
0x0809ad07 in Perl\_csighandler \(\)
\(gdb\) bt
\#0  0x0809ad07 in Perl\_csighandler \(\)
\#1  \<signal handler called>
\#2  0xb7f8538c in ?? \(\) from /lib/tls/i686/cmov/libc\.so\.6
\#3  0xb7f86865 in malloc \(\) from /lib/tls/i686/cmov/libc\.so\.6
\#4  0x0809498c in Perl\_safesysmalloc \(\)
\#5  0x080a8373 in Perl\_av\_extend \(\)
\#6  0x080a8e13 in Perl\_av\_store \(\)
\#7  0x080a9523 in Perl\_av\_push \(\)
\#8  0x080cc700 in perl\_clone \(\)
\#9  0xb7dbafc4 in XS\_threads\_create \(\) from 
/usr/lib/perl/5\.10/auto/threads/threads\.so
\#10 0x080b3f02 in Perl\_pp\_entersub \(\) 

\#11 0x080b22e9 in Perl\_runops\_standard \(\) 

\#12 0x080b0750 in perl\_run \(\) 

\#13 0x08063ebd in main \(\)




---
Program received signal SIGSEGV\, Segmentation fault\.
\[Switching to Thread 0xb7df18c0 \(LWP 16487\)\]
0x0809ad07 in Perl\_csighandler \(\)
\(gdb\) bt
\#0  0x0809ad07 in Perl\_csighandler \(\)
\#1  \<signal handler called>
\#2  0xb7e9cb56 in memcpy \(\) from /lib/tls/i686/cmov/libc\.so\.6
\#3  0x09804638 in ?? \(\)
\#4  0x080bc91f in Perl\_sv\_dup \(\)
\#5  0x080bd13d in Perl\_sv\_dup \(\)
\#6  0x080bd13d in Perl\_sv\_dup \(\)
\#7  0x080bd196 in Perl\_sv\_dup \(\)
\#8  0x080bdfa1 in Perl\_gp\_dup \(\)
\#9  0x080bd2c6 in Perl\_sv\_dup \(\)
\#10 0x080a73da in Perl\_he\_dup \(\)
\#11 0x080bcd54 in Perl\_sv\_dup \(\)
\#12 0x080bc970 in Perl\_sv\_dup \(\)
\#13 0x080bda18 in Perl\_rvpv\_dup \(\)
\#14 0x080bcfb7 in Perl\_sv\_dup \(\)
\#15 0x080bdeaa in Perl\_gp\_dup \(\)
\#16 0x080bd2c6 in Perl\_sv\_dup \(\)
\#17 0x080bd13d in Perl\_sv\_dup \(\)
\#18 0x080bd13d in Perl\_sv\_dup \(\)
\#19 0x080bd196 in Perl\_sv\_dup \(\)
\#20 0x080bd093 in Perl\_sv\_dup \(\)
\#21 0x080bda18 in Perl\_rvpv\_dup \(\)
\#22 0x080bc91f in Perl\_sv\_dup \(\)
\#23 0x080a73da in Perl\_he\_dup \(\)
\#24 0x080bcd54 in Perl\_sv\_dup \(\)
\#25 0x080bdf59 in Perl\_gp\_dup \(\)
\#26 0x080bd2c6 in Perl\_sv\_dup \(\)
\#27 0x080bd13d in Perl\_sv\_dup \(\)
\#28 0x080bd13d in Perl\_sv\_dup \(\)
\#29 0x080bd196 in Perl\_sv\_dup \(\)
\#30 0x080bdfa1 in Perl\_gp\_dup \(\)
\#31 0x080bd2c6 in Perl\_sv\_dup \(\)
\#32 0x080a73da in Perl\_he\_dup \(\)
\#33 0x080bcd54 in Perl\_sv\_dup \(\)
\#34 0x080bdf59 in Perl\_gp\_dup \(\)
\#35 0x080bd2c6 in Perl\_sv\_dup \(\)
\#36 0x080a73da in Perl\_he\_dup \(\)
\#37 0x080bcd54 in Perl\_sv\_dup \(\)
\#38 0x080bca54 in Perl\_sv\_dup \(\)
\#39 0x080bdfa1 in Perl\_gp\_dup \(\)
\#40 0x080bd2c6 in Perl\_sv\_dup \(\)
\#41 0x080a73da in Perl\_he\_dup \(\)
\#42 0x080bcd54 in Perl\_sv\_dup \(\)
\#43 0x080bca54 in Perl\_sv\_dup \(\)
\#44 0x080bdfa1 in Perl\_gp\_dup \(\)
\#45 0x080bd2c6 in Perl\_sv\_dup \(\)
\#46 0x080a73da in Perl\_he\_dup \(\)
\#47 0x080bcd54 in Perl\_sv\_dup \(\)
\#48 0x080bc970 in Perl\_sv\_dup \(\)
\#49 0x080bded5 in Perl\_gp\_dup \(\)
\#50 0x080bd2c6 in Perl\_sv\_dup \(\)
\#51 0x080bd13d in Perl\_sv\_dup \(\)
\#52 0x080bd13d in Perl\_sv\_dup \(\)
\#53 0x080bd196 in Perl\_sv\_dup \(\)
\#54 0x080bdfa1 in Perl\_gp\_dup \(\)
\#55 0x080bd2c6 in Perl\_sv\_dup \(\)
\#56 0x080a73da in Perl\_he\_dup \(\)
\#57 0x080bcd54 in Perl\_sv\_dup \(\)
\#58 0x080bdf59 in Perl\_gp\_dup \(\)
\#59 0x080bd2c6 in Perl\_sv\_dup \(\)
\#60 0x080a73da in Perl\_he\_dup \(\)
\#61 0x080a7380 in Perl\_he\_dup \(\)
\#62 0x080a7380 in Perl\_he\_dup \(\)
\#63 0x080bcd54 in Perl\_sv\_dup \(\)
\#64 0x080bca54 in Perl\_sv\_dup \(\)
\#65 0x080bdfa1 in Perl\_gp\_dup \(\)
\#66 0x080bd2c6 in Perl\_sv\_dup \(\)
\#67 0x080a73da in Perl\_he\_dup \(\)
\#68 0x080bcd54 in Perl\_sv\_dup \(\)
\#69 0x080bd2ab in Perl\_sv\_dup \(\)
\#70 0x080cc2cc in perl\_clone \(\)
\#71 0xb7ccbfc4 in XS\_threads\_create \(\) from 
/usr/lib/perl/5\.10/auto/threads/threads\.so
\#72 0x080b3f02 in Perl\_pp\_entersub \(\) 

\#73 0x080b22e9 in Perl\_runops\_standard \(\) 

\#74 0x080b0750 in perl\_run \(\) 

\#75 0x08063ebd in main \(\)



---
Flags&#8203;: 

&nbsp;     category= 

&nbsp;     severity=


---
Site configuration information for perl 5\.10\.0&#8203;:

Configured by Debian Project at Thu Jul 24 09&#8203;:01&#8203;:44 UTC 2008\.

Summary of my perl5 \(revision 5 version 10 subversion 0\) configuration&#8203;:
&nbsp;   Platform&#8203;:
&nbsp;     osname=linux\, osvers=2\.6\.24\-15\-server\, 
archname=i486\-linux\-gnu\-thread\-multi
&nbsp;     uname='linux palmer 2\.6\.24\-15\-server \#1 smp tue apr 8 01&#8203;:08&#8203;:17 utc 
2008 i686 gnulinux '
&nbsp;     config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN 
\-Dcccdlflags=\-fPIC \-Darchname=i486\-linux\-gnu \-Dprefix=/usr 
\-Dprivlib=/usr/share/perl/5\.10 \-Darchlib=/usr/lib/perl/5\.10 
\-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 
\-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local 
\-Dsitelib=/usr/local/share/perl/5\.10\.0 
\-Dsitearch=/usr/local/lib/perl/5\.10\.0 \-Dman1dir=/usr/share/man/man1 
\-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1 
\-Dsiteman3dir=/usr/local/man/man3 \-Dman1ext=1 \-Dman3ext=3perl 
\-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Ud\_ualarm \-Uusesfio 
\-Uusenm \-DDEBUGGING=\-g \-Doptimize=\-O2 \-Duseshrplib 
\-Dlibperl=libperl\.so\.5\.10\.0 \-Dd\_dosuid \-des'
&nbsp;     hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;     useithreads=define\, usemultiplicity=define
&nbsp;     useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;     use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;     usemymalloc=n\, bincompat5005=undef
&nbsp;   Compiler&#8203;:
&nbsp;     cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN 
\-fno\-strict\-aliasing \-pipe \-I/usr/local/include \-D\_LARGEFILE\_SOURCE 
\-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;     optimize='\-O2 \-g'\,
&nbsp;     cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing 
\-pipe \-I/usr/local/include'
&nbsp;     ccversion=''\, gccversion='4\.3\.1'\, gccosandvers=''
&nbsp;     intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;     ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, 
lseeksize=8
&nbsp;     alignbytes=4\, prototype=define
&nbsp;   Linker and Libraries&#8203;:
&nbsp;     ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;     libpth=/usr/local/lib /lib /usr/lib /usr/lib64
&nbsp;     libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;     perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;     libc=/lib/libc\-2\.8\.90\.so\, so=so\, useshrplib=true\, 
libperl=libperl\.so\.5\.10\.0
&nbsp;     gnulibc\_version='2\.8\.90'
&nbsp;   Dynamic Linking&#8203;:
&nbsp;     dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;     cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-g \-L/usr/local/lib'

Locally applied patches&#8203;:




---
@&#8203;INC for perl 5\.10\.0&#8203;:
&nbsp;     /etc/perl
&nbsp;     /usr/local/lib/perl/5\.10\.0
&nbsp;     /usr/local/share/perl/5\.10\.0
&nbsp;     /usr/lib/perl5
&nbsp;     /usr/share/perl5
&nbsp;     /usr/lib/perl/5\.10
&nbsp;     /usr/share/perl/5\.10
&nbsp;     /usr/local/lib/site\_perl
&nbsp;     \.



---
Environment for perl 5\.10\.0&#8203;:
&nbsp;     HOME=/home/pascal
&nbsp;     LANG=de\_DE\.UTF\-8
&nbsp;     LANGUAGE=de
&nbsp;     LD\_LIBRARY\_PATH \(unset\)
&nbsp;     LOGDIR \(unset\)
 
PATH=/home/pascal/bin&#8203;:/usr/local/sbin&#8203;:/usr/local/bin&#8203;:/usr/sbin&#8203;:/usr/bin&#8203;:/sbin&#8203;:/bin&#8203;:/usr/games
&nbsp;     PERL\_BADLANG \(unset\)
&nbsp;     SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From john.wright@hp.com

On Fri Nov 21 00&#8203;:39&#8203;:51 2008\, mail@&#8203;pascalhofmann\.de wrote&#8203;:
> I'have a program which uses threads and has a custom signal handler
> for SIGCHLD\. If a SIGCHLD is received during thread creation perl
> produces a segfault\.

This bug lies in the fact that Perl\_csighandler\(\) relies on the
thread\-specific my\_perl struct being in a consistent state\.  But unless
we block signals during certain points in the code\, that's not
guaranteed to be the case\.

I have attached a reproducer\, crash\-with\-threads\.pl\, based on one
written by Pascal Hofmann\.  It crashes variously in two ways&#8203;:

 1\. Crash when trying to do "PL\_psig\_pend\[sig\]\+\+;"\.  This happens
&nbsp;    sometimes when Perl is cloning the interpreter for a new thread \(as
&nbsp;    in the backtrace attached here\)\, and sometimes when it's tearing
&nbsp;    down a thread\, with the same effect\.
&nbsp;    
&nbsp;    When it's cloning the interpreter\, it changes its context to the new
&nbsp;    interpreter before it's actually fully initialized\, so if the signal
&nbsp;    handler fires during this time\, it gets the cloned interpreter
&nbsp;    \(which hasn't been actually assigned to a new thread yet\)\, and tries
&nbsp;    to access a pointer inside that struct that is yet NULL\.

&nbsp;    It can also get a signal while it's tearing down a thread\.  I've
&nbsp;    seen this happen both in the "parent" thread \(where it changes its
&nbsp;    context like above\)\, and in the thread that the victim interpreter
&nbsp;    was actually running in \(where it happens to receive a signal after
&nbsp;    the parent starts destroying the interpreter and before the thread
&nbsp;    goes away\)\.

&nbsp;    My solution here is to wrap the potentially dangerous sections
&nbsp;    \(either around where the code changes its context before the
&nbsp;    interpreter is ready or before the interpreter will get destroyed\)
&nbsp;    with some code that masks most of the signals\, and restores to the
&nbsp;    orginal signal mask state afterwards\.

 2\. Crashing when accessing PL\_signals \(which expands to
&nbsp;    my\_perl\->Isignals for me\)\.  This occurs when a new thread has been
&nbsp;    created \(using pthread\_create\) but the thread hasn't had a chance to
&nbsp;    set its interpreter context with PERL\_SET\_CONTEXT\(\)\.  Even though
&nbsp;    this is the first thing the thread does\, it could receive a signal
&nbsp;    while pthread\_create is doing its thing\.

&nbsp;    My solution here is to block signals in the calling thread before
&nbsp;    calling pthread\_create \(actually\, while it's setting up the new
&nbsp;    interpreter struct \-\- see case 1\)\, setting the old signal mask to a
&nbsp;    new member of the thread struct\, and then restore the signal mask
&nbsp;    when everything is clear in the new thread\, and in the "parent"
&nbsp;    thread right after thread creation\.

I also ran into a related bug\, in the non\-threaded case&#8203;: If Perl is in
the middle of exiting \(after it is finished with actually interpreting
the Perl code\)\, and it receivs a signal that had a registered handler in
the script\, it is possible for the struct representing the interpreter
to have been torn down and its thread\-local reference already removed\.
Since the signal handler refers to this\, it segfaults\.  \(See
crash\-without\-threads\.pl\.

My solution to this is to de\-register the signal handler before
destroying the Perl interpreter\.

I have attached\, as well as the reproducers above\, two patches which fix
the problems for me\.  I'm sure the threading one needs some preprocessor
work\, since it relies on pthread\_sigmask\(\)\.  I'm not familiar with any
of the other threading libraries Perl supports\.

**Comment by p5pRT** [comment]
### From john.wright@hp.com

<details><summary>0002-Mask-signals-in-thread-creation-and-destruction-to-a.patch</summary>

```diff
From 4c0ed7b7d0b87ebd1cd194a5232ea8b2813edaec Mon Sep 17 00:00:00 2001
From: John Wright <john.wright@hp.com>
Date: Wed, 6 May 2009 15:48:12 -0600
Subject: [PATCH 2/2] Mask signals in thread creation and destruction to avoid a segfault

If our signal handler gets called before a thread got a chance to run
PERL_SET_CONTEXT(), the call to get the thread-specific interpreter will
fail, and we'll end up with aTHX == NULL.  Prevent this from happening
by blocking most signals right before creating the new thread.  This
way, the new thread starts out with most signals blocked, and it
unblocks them when it's ready to handle them.

This required saving the original signal mask somewhere - I put it in
the thread struct.

In several places, PERL_SET_CONTEXT() is called before the target perl
interpreter struct has been fully initialized, so this patch adds code
to block signals around those blocks of code.
---
 ext/threads/threads.xs |   82 ++++++++++++++++++++++++++++++++++++++++++++++++
 1 files changed, 82 insertions(+), 0 deletions(-)
 mode change 100644 => 100755 ext/threads/threads.xs

diff --git a/ext/threads/threads.xs b/ext/threads/threads.xs
old mode 100644
new mode 100755
index a15f7ec..9574653
--- a/ext/threads/threads.xs
+++ b/ext/threads/threads.xs
@@ -75,6 +75,7 @@ typedef struct _ithread {
     IV stack_size;
     SV *err;                    /* Error from abnormally terminated thread */
     char *err_class;            /* Error object's classname if applicable */
+    sigset_t initial_sigmask;   /* Thread wakes up with signals blocked */
 } ithread;
 
 
@@ -114,6 +115,44 @@ typedef struct {
 
 #define MY_POOL (*my_poolp)
 
+/* Block most signals for calling thread, setting the old signal mask to
+ * oldmask, if it is not NULL */
+STATIC int
+S_block_most_signals(sigset_t *oldmask)
+{
+    sigset_t newmask;
+
+    sigfillset(&newmask);
+    /* Don't block certain "important" signals (stolen from mg.c) */
+#ifdef SIGILL
+    sigdelset(&newmask, SIGILL);
+#endif
+#ifdef SIGBUS
+    sigdelset(&newmask, SIGBUS);
+#endif
+#ifdef SIGSEGV
+    sigdelset(&newmask, SIGSEGV);
+#endif
+
+#ifdef WIN32
+    /* XXX: How to do this on win32? */
+    return 0;
+#else
+    return pthread_sigmask(SIG_BLOCK, &newmask, oldmask);
+#endif /* WIN32 */
+}
+
+/* Set the signal mask for this thread to newmask */
+STATIC int
+S_set_sigmask(sigset_t *newmask)
+{
+#ifdef WIN32
+    /* XXX: How to do this on win32? */
+    return 0;
+#else
+    return pthread_sigmask(SIG_SETMASK, newmask, NULL);
+#endif /* WIN32 */
+}
 
 /* Used by Perl interpreter for thread context switching */
 STATIC void
@@ -142,12 +181,19 @@ STATIC void
 S_ithread_clear(pTHX_ ithread *thread)
 {
     PerlInterpreter *interp;
+    sigset_t origmask;
 
     assert(((thread->state & PERL_ITHR_FINISHED) &&
             (thread->state & PERL_ITHR_UNCALLABLE))
                 ||
            (thread->state & PERL_ITHR_NONVIABLE));
 
+    /* We temporarily set the interpreter context to the interpreter being
+     * destroyed.  It's in no condition to handle signals while it's being
+     * taken apart.
+     */
+    S_block_most_signals(&origmask);
+
     interp = thread->interp;
     if (interp) {
         dTHXa(interp);
@@ -169,6 +215,7 @@ S_ithread_clear(pTHX_ ithread *thread)
     }
 
     PERL_SET_CONTEXT(aTHX);
+    S_set_sigmask(&origmask);
 }
 
 
@@ -415,6 +462,11 @@ S_ithread_run(void * arg)
     PERL_SET_CONTEXT(thread->interp);
     S_ithread_set(aTHX_ thread);
 
+    /* Thread starts with most signals blocked - restore the signal mask from
+     * the ithread struct.
+     */
+    S_set_sigmask(&thread->initial_sigmask);
+
     PL_perl_destruct_level = 2;
 
     {
@@ -448,6 +500,12 @@ S_ithread_run(void * arg)
         }
         JMPENV_POP;
 
+        /* The interpreter is finished, so this thread can stop receiving
+         * signals.  This way, our signal handler doesn't get called in the
+         * middle of our parent thread calling perl_destruct()...
+         */
+        S_block_most_signals(NULL);
+
         /* Remove args from stack and put back in params array */
         SPAGAIN;
         for (ii=len-1; ii >= 0; ii--) {
@@ -660,6 +718,25 @@ S_ithread_create(
     PL_srand_called = FALSE;   /* Set it to false so we can detect if it gets
                                   set during the clone */
 
+    /* perl_clone() will leave us the new interpreter's context.  This poses
+     * two problems for our signal handler.  First, it sets the new context
+     * before the new interpreter struct is fully initialized, so our signal
+     * handler might find bogus data in the interpreter struct it gets.
+     * Second, even if the interpreter is initialized before a signal comes in,
+     * we would like to avoid that interpreter receiving notifications for
+     * signals (especially when they ought to be for the one running in this
+     * thread), until it is running in its own thread.  Another problem is that
+     * the new thread will not have set the context until some time after it
+     * has started, so it won't be safe for our signal handler to run until
+     * that time.
+     *
+     * So we block most signals here, so the new thread will inherit the signal
+     * mask, and unblock them right after the thread creation.  The original
+     * mask is saved in the thread struct so that the new thread can restore
+     * the original mask.
+     */
+    S_block_most_signals(&thread->initial_sigmask);
+
 #ifdef WIN32
     thread->interp = perl_clone(aTHX, CLONEf_KEEP_PTR_TABLE | CLONEf_CLONE_HOST);
 #else
@@ -774,6 +851,11 @@ S_ithread_create(
 #  endif
         }
 
+    /* Now it's safe to accept signals, since we're in our own interpreter's
+     * context and we have created the thread.
+     */
+    S_set_sigmask(&thread->initial_sigmask);
+
 #  ifdef _POSIX_THREAD_ATTR_STACKSIZE
         /* Try to get thread's actual stack size */
         {
-- 
1.5.6.5


```
</details>

**Comment by p5pRT** [comment]
### From john.wright@hp.com

[crash-with-threads.pl](https://rt-archive.perl.org/perl5/Ticket/Attachment/562256/267550/crash-with-threads.pl)

**Comment by p5pRT** [comment]
### From john.wright@hp.com

[crash-without-threads.pl](https://rt-archive.perl.org/perl5/Ticket/Attachment/562256/267556/crash-without-threads.pl)

**Comment by p5pRT** [comment]
### From john.wright@hp.com

<details><summary>0001-main-Unregister-signal-handler-before-destroying-my.patch</summary>

```diff
From a9450face7394716acd9ca8403d0f50e16b60b0a Mon Sep 17 00:00:00 2001
From: John Wright <john@johnwright.org>
Date: Wed, 6 May 2009 00:47:15 -0600
Subject: [PATCH 1/2] main: Unregister signal handler before destroying my_perl

If the signal handler runs after perl_destruct() has been called, it
will get an invalid (or NULL) my_perl when it asks for the
thread-specific interpreter struct.  This patch resets the signal
handler for any signal previously handled by PL_csighandlerp to SIG_DFL
before calling perl_destruct().
---
 miniperlmain.c |    9 ++++++++-
 1 files changed, 8 insertions(+), 1 deletions(-)

diff --git a/miniperlmain.c b/miniperlmain.c
index f60a3e0..f2302c2 100644
--- a/miniperlmain.c
+++ b/miniperlmain.c
@@ -67,7 +67,7 @@ main(int argc, char **argv, char **env)
 #endif
 {
     dVAR;
-    int exitstatus;
+    int exitstatus, i;
 #ifdef PERL_GLOBAL_STRUCT
     struct perl_vars *plvarsp = init_global_struct();
 #  ifdef PERL_GLOBAL_STRUCT_PRIVATE
@@ -116,6 +116,13 @@ main(int argc, char **argv, char **env)
     if (!exitstatus)
         perl_run(my_perl);
 
+    /* Unregister our signal handler before destroying my_perl */
+    for (i = 0; PL_sig_name[i]; i++) {
+	if (rsignal_state(PL_sig_num[i]) == (Sighandler_t) PL_csighandlerp) {
+	    rsignal(PL_sig_num[i], (Sighandler_t) SIG_DFL);
+	}
+    }
+
     exitstatus = perl_destruct(my_perl);
 
     perl_free(my_perl);
-- 
1.5.6.5


```
</details>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @rgs

Fixed by those patches :

commit b762d8667351cb765bc1d6419d30acff085da502
Author&#8203;: John Wright \<john\.wright@&#8203;hp\.com>
Date&#8203;:   Wed May 6 15&#8203;:48&#8203;:12 2009 \-0600

&nbsp;    Mask signals in thread creation and destruction to avoid a segfault
&nbsp;    
&nbsp;    If our signal handler gets called before a thread got a chance to run
&nbsp;    PERL\_SET\_CONTEXT\(\)\, the call to get the thread\-specific interpreter will
&nbsp;    fail\, and we'll end up with aTHX == NULL\.  Prevent this from happening
&nbsp;    by blocking most signals right before creating the new thread\.  This
&nbsp;    way\, the new thread starts out with most signals blocked\, and it
&nbsp;    unblocks them when it's ready to handle them\.
&nbsp;    
&nbsp;    This required saving the original signal mask somewhere \- I put it in
&nbsp;    the thread struct\.
&nbsp;    
&nbsp;    In several places\, PERL\_SET\_CONTEXT\(\) is called before the target perl
&nbsp;    interpreter struct has been fully initialized\, so this patch adds code
&nbsp;    to block signals around those blocks of code\.

 ext/threads/threads\.xs |   82
\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+\+
 1 files changed\, 82 insertions\(\+\)\, 0 deletions\(\-\)

commit 01be0729981136a058cce07a897ccdb94609e1c0
Author&#8203;: John Wright \<john@&#8203;johnwright\.org>
Date&#8203;:   Wed May 6 00&#8203;:47&#8203;:15 2009 \-0600

&nbsp;    main&#8203;: Unregister signal handler before destroying my\_perl
&nbsp;    
&nbsp;    If the signal handler runs after perl\_destruct\(\) has been called\, it
&nbsp;    will get an invalid \(or NULL\) my\_perl when it asks for the
&nbsp;    thread\-specific interpreter struct\.  This patch resets the signal
&nbsp;    handler for any signal previously handled by PL\_csighandlerp to SIG\_DFL
&nbsp;    before calling perl\_destruct\(\)\.

**Comment by p5pRT** [comment]
@rgs - Status changed from 'open' to 'resolved'
