### ISSUE TITLE
HVs having SVs_GMG and SVs_RMG set are sometimes wrongly handled as tied arrays

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9624]
Migrated from [rt.perl.org#62486](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=62486) (status was 'open')

Searchable as RT62486$

**Comment by p5pRT** [comment]
### From perl@profvince.com

#### Created by perl@province.com



This bug isn't specific to 5\.10 or to H&#8203;::U&#8203;::FH\, but it gives a
convenient way to show it without writing XS code\.

&nbsp;    perl \-MHash&#8203;::Util&#8203;::FieldHash=fieldhash \-e 'fieldhash %SIG; @&#8203;a = %SIG
= \(A => sub \{ \}\)'

segfaults with backtrace

Program received signal SIGSEGV\, Segmentation fault\.
0x00000000004788fe in S\_magic\_methcall \(sv=0x12a6d00\, mg=0x0\,
&nbsp;    meth=0x5a2c13 "EXISTS"\, flags=0\, n=2\, val=0x0\) at mg\.c&#8203;:1605
1605        PUSHs\(SvTIED\_obj\(sv\, mg\)\);
\(gdb\) bt
\#0  0x00000000004788fe in S\_magic\_methcall \(sv=0x12a6d00\, mg=0x0\,
&nbsp;    meth=0x5a2c13 "EXISTS"\, flags=0\, n=2\, val=0x0\) at mg\.c&#8203;:1605
\#1  0x0000000000478bdf in S\_magic\_methpack \(sv=0x12a6d00\, mg=0x0\,
&nbsp;    meth=0x5a2c13 "EXISTS"\) at mg\.c&#8203;:1634
\#2  0x0000000000479ea6 in Perl\_magic\_existspack \(sv=0x12a6d00\, mg=0x0\)
&nbsp;    at mg\.c&#8203;:1738
\#3  0x0000000000482178 in Perl\_hv\_common \(hv=0x1292ce0\, keysv=0x12a6940\,
&nbsp;    key=0x1258170 "A"\, klen=1\, flags=0\, action=8\, val=0x0\, hash=0\) at
hv\.c&#8203;:486
\#4  0x0000000000499932 in Perl\_pp\_aassign \(\) at pp\_hot\.c&#8203;:1057
\#5  0x000000000046beef in Perl\_runops\_debug \(\) at dump\.c&#8203;:1931
\#6  0x000000000048f677 in S\_run\_body \(oldscope=1\) at perl\.c&#8203;:2384
\#7  0x000000000048f133 in perl\_run \(my\_perl=0x1238010\) at perl\.c&#8203;:2302
\#8  0x000000000041f8dd in main \(argc=4\, argv=0x7fffa4ab6b08\,
&nbsp;    env=0x7fffa4ab6b30\) at perlmain\.c&#8203;:113
\(gdb\) call Perl\_sv\_dump\(sv\)
SV = NULL\(0x0\) at 0x12a6d00
&nbsp;  REFCNT = 1
&nbsp;  FLAGS = \(TEMP\)
\(gdb\) p mg
$1 = \(const MAGIC \*\) 0x0
\(gdb\) up 3
\#3  0x0000000000482178 in Perl\_hv\_common \(hv=0x1292ce0\, keysv=0x12a6940\,
&nbsp;    key=0x1258170 "A"\, klen=1\, flags=0\, action=8\, val=0x0\, hash=0\) at
hv\.c&#8203;:486
486                     magic\_existspack\(svret\, mg\_find\(sv\,
PERL\_MAGIC\_tiedelem\)\);
\(gdb\) l
481                     \} else \{
482                         mg\_copy\(\(SV\*\)hv\, sv\, key\, klen\);
483                     \}
484                     if \(flags & HVhek\_FREEKEY\)
485                         Safefree\(key\);
486                     magic\_existspack\(svret\, mg\_find\(sv\,
PERL\_MAGIC\_tiedelem\)\);
487                     /\* This cast somewhat evil\, but I'm merely using
NULL/
488                        not NULL to return the boolean exists\.
489                        And I know hv is not NULL\.  \*/
490                     return SvTRUE\(svret\) ? \(void \*\)hv : NULL;
\(gdb\) l 470
465             \} /\* ISFETCH \*/
466             else if \(SvRMAGICAL\(hv\) && \(action & HV\_FETCH\_ISEXISTS\)\) \{
467                 if \(mg\_find\(\(SV\*\)hv\, PERL\_MAGIC\_tied\) ||
SvGMAGICAL\(\(SV\*\)hv\)\) \{
468                     /\* I don't understand why hv\_exists\_ent has
svret and sv\,
469                        whereas hv\_exists only had one\.  \*/
470                     SV \* const svret = sv\_newmortal\(\);
471                     sv = sv\_newmortal\(\);
472
473                     if \(keysv || is\_utf8\) \{
474                         if \(\!keysv\) \{
\(gdb\) call Perl\_sv\_dump\(hv\)
SV = PVHV\(0x12428a0\) at 0x1292ce0
&nbsp;  REFCNT = 1
&nbsp;  FLAGS = \(GMG\,SMG\,RMG\,SHAREKEYS\)
&nbsp;  MAGIC = 0x1257f50
&nbsp;    MG\_VIRTUAL = &PL\_vtbl\_uvar
&nbsp;    MG\_TYPE = PERL\_MAGIC\_uvar\(U\)
&nbsp;    MG\_LEN = 24
&nbsp;    MG\_PTR = 0x125aab0
"\\332\`f\\233\\225\\177\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\10\\0\\0\\0\\0\\0\\0\\0"
&nbsp;  MAGIC = 0x12a6060
&nbsp;    MG\_VIRTUAL = &PL\_vtbl\_sig
&nbsp;    MG\_TYPE = PERL\_MAGIC\_sig\(S\)
&nbsp;  ARRAY = 0x12aa1f0
&nbsp;  KEYS = 0
&nbsp;  FILL = 0
&nbsp;  MAX = 127
&nbsp;  RITER = \-1
&nbsp;  EITER = 0x0

What happens is that %SIG originally has RMG set\, because sig magic
doesn't have set/get magic callbacks\. When uvar magic is applied on it
with fieldhash\(\)\, GMG is also set\. If %SIG is assigned in list context\,
pp\_aassign calls exist ; and since SvRMAGICAL\(hv\) && \(action &
HV\_FETCH\_ISEXISTS\) && SvGMAGICAL\(\(SV\*\)hv\) is true\, the hash is wrongly
handled as a tied hash\.

A first memory misread happens with mg\_find\(sv\, PERL\_MAGIC\_tiedelem\)\,
because sv is not a PVMG \(mg\_copy couldn't upgrade it since there's no
copy magic in this case\)\. This doesn't cause the segfault in this
example\, but it's still wrong\.
And even if this would be right\, SvTIED\_obj\(sv\, mg\) segvs later because
mg \(which should be the tied magic token\) is righteously NULL\.

This example is pretty unlikely to happen in real life\, but this problem
applies also to any extension magic that has both get and clear
callbacks \(which I think is quite reasonable\)\.

Vincent\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.10.0:

Configured by vince at Sat Sep 27 22:36:33 CEST 2008.

Summary of my perl5 (revision 5 version 10 subversion 0) configuration:
  Platform:
    osname=linux, osvers=2.6.26.3-fuuka.profvince.com,
archname=x86_64-linux-ld
    uname='linux fuuka 2.6.26.3-fuuka.profvince.com #1 smp tue sep 2
23:24:24 cest 2008 x86_64 intel(r) core(tm)2 duo cpu e6750 @ 2.66ghz
genuineintel gnulinux '
    config_args='-des -Dcf_email=vpit@cpan.org
-Dmydomain=fuuka.profvince.com -Dusemorebits -Dman1dir=none
-Dman3dir=none -DDEBUGGING -Doptimize='-g3'
-Dprefix=/home/vince/perl/builds/dbg/5.10.0'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=define, uselongdouble=define
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-DDEBUGGING -fno-strict-aliasing -pipe
-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm',
    optimize='-g3',
    cppflags='-DDEBUGGING -fno-strict-aliasing -pipe -I/usr/include/gdbm'
    ccversion='', gccversion='4.3.1', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='long double', nvsize=16,
Off_t='off_t', lseeksize=8
    alignbytes=16, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64 /usr/local/lib64
    libs=-lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/lib/libc-2.8.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.8'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -g3 -L/usr/local/lib'

Locally applied patches:
   


@INC for perl 5.10.0:
    /home/vince/perl/builds/dbg/5.10.0/lib/5.10.0/x86_64-linux-ld
    /home/vince/perl/builds/dbg/5.10.0/lib/5.10.0
    /home/vince/perl/builds/dbg/5.10.0/lib/site_perl/5.10.0/x86_64-linux-ld
    /home/vince/perl/builds/dbg/5.10.0/lib/site_perl/5.10.0
    .


Environment for perl 5.10.0:
    HOME=/home/vince
    LANG=fr_FR.UTF-8
    LANGUAGE (unset)
    LC_ALL=fr_FR.UTF-8
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
   
PATH=/home/vince/bin:/home/vince/perl/builds/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/4.3.2:/opt/intel/cce/10.1.018/bin:/usr/local/texlive/2007/bin/x86_64-linux:/usr/games/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash


```
</details>

**Comment by p5pRT** [comment]
### From bitcard@profvince.com

>     perl \-MHash&#8203;::Util&#8203;::FieldHash=fieldhash \-e 'fieldhash %SIG; @&#8203;a =
> %SIG
> = \(A => sub \{ \}\)'
> 
> segfaults with backtrace

This example no longer segfaults in blead\, as the result of my own
http&#8203;://perl5\.git\.perl\.org/perl\.git/commit/218787bdb7a9250de0cc00118d84dcb23ff2f1c5
\- because %SIG no longer has RMG set\. It may still be a problem in
extensions if one define an ext magic with get and clear\, but I don't
see how to forge a pure perl example without the hash being tied\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'
