### ISSUE TITLE
crash in PerlIOStdio_dup()

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9650]
Migrated from [rt.perl.org#63244](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=63244) (status was 'open')

Searchable as RT63244$

**Comment by p5pRT** [comment]
### From @ntyni


This is a bug report for perl from Niko Tyni \<ntyni@&#8203;debian\.org>\,
generated with the help of perlbug 1\.36 running under perl 5\.10\.0\.




---
As reported in http&#8203;://bugs\.debian\.org/164615 :

env PERLIO=stdio perl \-e 'open\(F\, "\<&STDOUT"\)' 1\< /dev/null

crashes on 5\.8\.8\, 5\.10\.0\, and blead@&#8203;b9ba2fa\.

Backtrace on blead&#8203;:

\#0  0x00007ffcff010110 in fileno\_unlocked \(\) from /lib/libc\.so\.6
\#1  0x00000000006958bd in PerlIOStdio\_dup \(my\_perl=0xcc4010\, f=0xce08f8\, o=0xce08e8\, param=0x0\, flags=2\)
&nbsp;    at perlio\.c&#8203;:3036
\#2  0x000000000068fb54 in PerlIO\_fdupopen \(my\_perl=0xcc4010\, f=0xce08e8\, param=0x0\, flags=2\)
&nbsp;    at perlio\.c&#8203;:570
\#3  0x000000000063a155 in Perl\_do\_openn \(my\_perl=0xcc4010\, gv=0xce7288\, oname=0xcf0318 "\<&STDOUT"\, 
&nbsp;    len=8\, as\_raw=0\, rawmode=0\, rawperm=0\, supplied\_fp=0x0\, svp=0xcc9c60\, num\_svs=0\) at doio\.c&#8203;:379
\#4  0x00000000005ff0c5 in Perl\_pp\_open \(my\_perl=0xcc4010\) at pp\_sys\.c&#8203;:555
\#5  0x00000000004b33fa in Perl\_runops\_debug \(my\_perl=0xcc4010\) at dump\.c&#8203;:1983
\#6  0x00000000006ef740 in S\_run\_body \(my\_perl=0xcc4010\, oldscope=1\) at perlmini\.c&#8203;:2320
\#7  0x00000000006eea86 in perl\_run \(my\_perl=0xcc4010\) at perlmini\.c&#8203;:2240
\#8  0x00000000006c08e6 in main \(argc=3\, argv=0x7fff07dee7c8\, env=0x7fff07dee7e8\) at miniperlmain\.c&#8203;:117




---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=low


---
Site configuration information for perl 5\.10\.0&#8203;:

Configured by Debian Project at Thu Jan  1 15&#8203;:40&#8203;:00 UTC 2009\.

Summary of my perl5 \(revision 5 version 10 subversion 0\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.26\-1\-vserver\-amd64\, archname=x86\_64\-linux\-gnu\-thread\-multi
&nbsp;    uname='linux excelsior 2\.6\.26\-1\-vserver\-amd64 \#1 smp sat nov 8 20&#8203;:24&#8203;:14 utc 2008 x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN \-Dcccdlflags=\-fPIC \-Darchname=x86\_64\-linux\-gnu \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.10 \-Darchlib=/usr/lib/perl/5\.10 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.10\.0 \-Dsitearch=/usr/local/lib/perl/5\.10\.0 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1 \-Dsiteman3dir=/usr/local/man/man3 \-Dman1ext=1 \-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Ud\_ualarm \-Uusesfio \-Uusenm \-DDEBUGGING=\-g \-Doptimize=\-O2 \-Duseshrplib \-Dlibperl=libperl\.so\.5\.10\.0 \-Dd\_dosuid \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing \-pipe \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2 \-g'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing \-pipe \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.3\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib /lib64 /usr/lib64
&nbsp;    libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    libc=/lib/libc\-2\.7\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.10\.0
&nbsp;    gnulibc\_version='2\.7'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-g \-L/usr/local/lib'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl 5\.10\.0&#8203;:
&nbsp;    /etc/perl
&nbsp;    /usr/local/lib/perl/5\.10\.0
&nbsp;    /usr/local/share/perl/5\.10\.0
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/perl/5\.10
&nbsp;    /usr/share/perl/5\.10
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    \.



---
Environment for perl 5\.10\.0&#8203;:
&nbsp;    HOME=/home/niko
&nbsp;    LANG=en\_US\.UTF\-8
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LC\_CTYPE=fi\_FI\.UTF\-8
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/niko/bin&#8203;:/home/niko/bin&#8203;:/home/niko/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/games&#8203;:/sbin&#8203;:/usr/sbin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/zsh

**Comment by p5pRT** [comment]
### From p5p@spam.wizbit.be

> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> As reported in http&#8203;://bugs\.debian\.org/164615 :
> 
> env PERLIO=stdio perl \-e 'open\(F\, "\<&STDOUT"\)' 1\< /dev/null
> 
> crashes on 5\.8\.8\, 5\.10\.0\, and blead@&#8203;b9ba2fa\.

Binary search&#8203;:

\-\-\-\-Program\-\-\-\-
\#\!/usr/bin/perl \-l

close STDERR;
open STDERR\, ">"\, "/dev/null";
system\(qq\(export PERLIO=stdio ; $^X \-e 'open\(F\, "\<&STDOUT"\)' 1\< /dev/
null\)\);
if \($?\) \{
&nbsp;  print "not ok";
\}
else \{
&nbsp;  print "ok";
\}

\-\-\-\-Output of \.\.\./pN8S2gQ/perl\-5\.7\.2@&#8203;13082/bin/perl\-\-\-\-
ok

\-\-\-\-EOF \($?='0'\)\-\-\-\-
\-\-\-\-Output of \.\.\./pe6KUT8/perl\-5\.7\.2@&#8203;13083/bin/perl\-\-\-\-
not ok

\-\-\-\-EOF \($?='0'\)\-\-\-\-



http&#8203;://public\.activestate\.com/cgi\-bin/perlbrowse/p/13083
Change 13083 by jhi@&#8203;alpha on 2001/11/18 21&#8203;:37&#8203;:06

&nbsp;    Integrate perlio&#8203;:
&nbsp;    
&nbsp;    \[ 13081\]
&nbsp;    Win32 layer has a dup which needs to match new prototype\.
&nbsp;    
&nbsp;    \[ 13080\]
&nbsp;    Wrong way to get stdio mode used\.
&nbsp;    
&nbsp;    \[ 13072\]
&nbsp;    Allow dup'ing of PerlIO&#8203;::Scalar etc\.


But I don't really understand that Change\.\.\.

The message indicates it was an integrate of 13080\, 13080 and 13072\.
But the changes indicate an integrate of 13081\, 13080?



Kind regards\,

Bram

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @jmdh

I couldn't reproduce this with \(Debian based\) 5\.10\.1 or above\.

**Comment by p5pRT** [comment]
### From @dcollinsn

On Wed Jun 01 14&#8203;:32&#8203;:51 2011\, dom wrote&#8203;:
> I couldn't reproduce this with \(Debian based\) 5\.10\.1 or above\.

I \*can\* reproduce this with at least 5\.8\.0 through 5\.25\.2

\-\- 
Respectfully\,
Dan Collins

**Comment by p5pRT** [comment]
### From @mauke

On Mon Jul 18 13&#8203;:02&#8203;:07 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> On Wed Jun 01 14&#8203;:32&#8203;:51 2011\, dom wrote&#8203;:
> > I couldn't reproduce this with \(Debian based\) 5\.10\.1 or above\.
> 
> I \*can\* reproduce this with at least 5\.8\.0 through 5\.25\.2

So can I\. valgrind says&#8203;:

==3492== Invalid read of size 4
==3492==    at 0x418BCA7&#8203;: ferror \(in /usr/lib/libc\-2\.23\.so\)
==3492==    by 0x80A70D8&#8203;: Perl\_io\_close \(in /home/mauke/usr/bin/perl\)
==3492==    by 0x80C04F7&#8203;: Perl\_sv\_clear \(in /home/mauke/usr/bin/perl\)
==3492==    by 0x80ADD24&#8203;: Perl\_sv\_free2 \(in /home/mauke/usr/bin/perl\)
==3492==    by 0x80BFE19&#8203;: do\_clean\_named\_io\_objs \(in /home/mauke/usr/bin/perl\)
==3492==    by 0x80BF922&#8203;: S\_visit \(in /home/mauke/usr/bin/perl\)
==3492==    by 0x80BFE76&#8203;: Perl\_sv\_clean\_objs \(in /home/mauke/usr/bin/perl\)
==3492==    by 0x81253CF&#8203;: perl\_destruct \(in /home/mauke/usr/bin/perl\)
==3492==    by 0x8062104&#8203;: main \(in /home/mauke/usr/bin/perl\)
==3492==  Address 0x0 is not stack'd\, malloc'd or \(recently\) free'd

**Comment by zb226** [comment]
Still seems to be an issue with blead:

```
$ env PERLIO=stdio ./perl -e 'open(F, "<&STDOUT")' 1</dev/null
Segmentation fault (core dumped)
```

Would the following be a valid TODO-test? It's a bit hacky...

```
TODO: {
    local $::TODO = 'GH 9650';
    local $ENV{PERL_RUNPERL_DEBUG} = 'env PERLIO=stdio';
    fresh_perl('open(F, "<&STDOUT")', { args => [ '1</dev/null' ] });
    is($?, 0, 'perl exited normally; GH 9650');
}
```

Output:

```
not ok 1 - perl exited normally; GH 9650 # TODO GH 9650
# Failed test 1 - perl exited normally; GH 9650 at t/run/todo_local.t line 114
#      got "35584"
# expected "0"
1..1
```
